### ISSUE TITLE
io.appium.settings.data_connection setstatus doesn't work

### ISSUE THREAD

**Issue by lubshilk** [appium/appium#12454] opened 2019-04-08 08:41 UTC
## The problem

We use the following command to turn mobile data ON/OFF on not-rooted devices:
_adb -s udid shell "am broadcast -a io.appium.settings.data_connection --es setstatus disable"
adb -s udid shell "am broadcast -a io.appium.settings.data_connection --es setstatus enable"_

For some testers the output is
_Broadcasting: Intent { act=io.appium.settings.data_connection (has extras) }
Broadcast completed: result=0_

For other
_Broadcasting: Intent { act=io.appium.settings.data_connection (has extras) }
Broadcast completed: result=-1_

But verification by command
_adb -s udid shell "dumpsys telephony.registry | grep 'mDataConnectionState'"_
shows the state didn't change

On the same devices turning WiFI on/off by the command works:
_adb -s udid shell "am broadcast -a io.appium.settings.wifi --es setstatus disable"_

## Environment

* Appium version that exhibits the issue: 1.11.1 and above
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows
* Mobile platform/version under test: Android 6 (LG), Android 8 (Samsung J6) 
* Real device

**Comment by mykola-mokhnach** [comment] 2019-04-08 09:19
This is by design. Android API since version 21 does not allow to control data state on real devices (it was also not possible before v21, but there was a hacky workaround). 

Closed as not an issue

**Closed by mykola-mokhnach** 2019-04-08 09:19 UTC
