### ISSUE TITLE
[bug] fail to create session in IOS 12.4.1 simulator

### ISSUE THREAD

**Issue by cheffey** [appium/appium#14026] opened 2020-03-04 16:39 UTC
## The problem
fail to create session in IOS 12.4.1 simulator, also happens to iPhone Xs max IOS 12.4.1 real device in appcenter.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:6.13.6
* Mobile platform/version under test: IOS 12.4.1
* Real device or emulator/simulator: iPhone Xs Max simulator
* Appium CLI or Appium.app|exe: 

## Details
I'm able to use the similar desiredCap to create session and start tests in IOS 13.1:

but when trying to connect to IOS 12.4 simulator, it stuck when post /session to WDA. I debug WDA using xcode and find FBXCAXClientProxy.activeApplications is where the request stuck.
also waitForQuiescence takes way too long after the app appear to be quiescence.
<img width="1440" alt="Screen Shot 2020-03-05 at 12 16 56 AM" src="https://user-images.githubusercontent.com/56681567/75899670-c7d50600-5e76-11ea-9867-14ed9b84de69.png">

## Link to Appium logs
https://gist.github.com/cheffey/c1581fe716f39805d844fc25f3d32db8

## Code To Reproduce Issue [ Good To Have ]
        driverConfig.capabilities.setCapability("platformName", "iOS");
        driverConfig.capabilities.setCapability("platformVersion", "12.4");(same as simulator)
        driverConfig.capabilities.setCapability("deviceName", "iPhone Xs Max");(same as simulator)
        driverConfig.capabilities.setCapability("bundleId", "com.jaydai.wonderqa");
        driverConfig.capabilities.setCapability("automationName", "XCUITest");
        driverConfig.capabilities.setCapability("autoAcceptAlerts", true);
        driverConfig.capabilities.setCapability(MobileCapabilityType.APP, "wonder.app");
        driverConfig.capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 1200);

Pardon me for not being able to share the app, it's base on react native framework.

**Comment by mykola-mokhnach** [comment] 2020-03-04 17:37
Possible duplicate of https://github.com/appium/appium/issues/13580

**Comment by cheffey** [comment] 2020-03-04 17:44
> Possible duplicate of #13580

Thanks for fast response, I resolved my issue with cap:
WaitForQuiescence=false
but since WaitForQuiescence is an old capability, I don't know if it's deprecated or what. What is the know issue with this cap set false?

**Comment by mykola-mokhnach** [comment] 2020-03-04 17:59
No, it's not deprecated. Where did you find such information?

If it is set to false then XCTest won't wait for the app to be in idle state. However, the final influence of this option to the final automation flow depends on how the app behaves and how the tests are designed. There is no universal answer.

**Comment by mykola-mokhnach** [comment] 2020-03-05 07:19
Closed as third party issue

**Closed by mykola-mokhnach** 2020-03-05 07:19 UTC
Labels: ThirdParty, XCUITest

**Comment by cheffey** [comment] 2020-03-05 07:33
> No, it's not deprecated. Where did you find such information?
> 
> If it is set to false then XCTest won't wait for the app to be in idle state. However, the influence of this option to the final automation flow depends on how the app behaves and how the tests are designed. There is no universal answer.

Thanks. I just can't find WaitForQuiescence cap in appium.io, if I can find that option in appium.io it would save me a lot of time. I will close it as solved.

**Comment by mykola-mokhnach** [comment] 2020-03-05 07:36
The cap is present at https://github.com/appium/appium-xcuitest-driver

the documentation at appium.io is badly maintained and we have many doc-related issues here marked with `NeedsHelp` tag. We'd be happy if people could join us to improve the situation there.

**Comment by cheffey** [comment] 2020-03-28 15:49
> The cap is present at https://github.com/appium/appium-xcuitest-driver
> 
> the documentation at appium.io is badly maintained and we have many doc-related issues here marked with `NeedsHelp` tag. We'd be happy if people could join us to improve the situation there.

I have been benefit by using appium, and studying appium code for a while. I would love to help maintaining and improve appium. Could you tell me how could I join your team?

**Comment by mykola-mokhnach** [comment] 2020-03-28 16:01
> I have been benefit by using appium, and studying appium code for a while. I would love to help maintaining and improve appium. Could you tell me how could I join your team?

I'm happy to know that you like the product @cheffey . Simply start contributing to the project and when the team decides your contribution and dedication has reached a good level then we accept you as Appium team member.
We also have a Slack channel where one could ask dev-related questions. I could add you there if you provide your email address.

**Comment by cheffey** [comment] 2020-03-28 16:30
> > I have been benefit by using appium, and studying appium code for a while. I would love to help maintaining and improve appium. Could you tell me how could I join your team?
> 
> I'm happy to know that you like the product @cheffey . Simply start contributing to the project and when the team decides your contribution and dedication has reached a good level then we accept you as Appium team member.
> We also have a Slack channel where one could ask dev-related questions. I could add you there if you provide your email address.

Thanks Mykola, My email: chefxie@chancetop.com
Could you instruct me what kind of contribution should I start with? Also may I ask what kind of contribution is need now?

**Comment by mykola-mokhnach** [comment] 2020-03-28 17:38
Do what you like or where you have the most experience. You could start with the documentation, for example, since you anyway have a practical Appium usage experience. Just go through the issues list and check what's pending there.

Invitation to Slack has been sent
