### ISSUE TITLE
Can not verify the toast message via appium(1.6.3) with uiautomator2

### ISSUE THREAD

**Issue by Carlgege** [appium/appium#8284] opened 2017-04-19 13:57 UTC
## The problem

Try to verify toast message failed.

## Environment
Appium version: 1.6.3
Java version: 1.8
Java client version: 5.0.0-beta7
android, Real device

## Details
Start the test app with uiautomator2 successfully, click action is pass.
When try to verify the toast message, it failed.

## Result
`org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.xpath: //*contains(@text, 'port')`

## Code To Reproduce Issue [ Good To Have ]
`//Toast content

Toast.makeText(getBaseContext(), "Change port successfully", Toast.LENGTH_SHORT).show();`

`//capabilities

capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);`

`//click the button to verify the toast message

driver.findElementByXPath("//*[contains(@text,'Button')]").click();
WebDriverWait wait = new WebDriverWait(driver, 10);
wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[contains(@text, 'port')]")))`

`// If i use the same API to find one button, result is pass

wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@text='Button']")));`

**Comment by mykola-mokhnach** [comment] 2017-04-19 14:44
Duplicate of https://github.com/appium/appium/issues/7774

**Closed by mykola-mokhnach** 2017-04-19 14:44 UTC
