### ISSUE TITLE
Toggle wifi not working using code in java 8.x and appium 2.x

### ISSUE THREAD

**Issue by ravibabu101143** [appium/appium#17637] opened 2022-10-21 05:54 UTC
Wifi connection not turned on/off using java client 8.2 on real android 11 device. It doesn't give any error message nor it turned off.

Code that I have used..

`import io.appium.java_client.CommandExecutionHelper;
import io.appium.java_client.ExecutesMethod;
import static io.appium.java_client.android.AndroidMobileCommandHelper.toggleWifiCommand;

public class AndroidUtils implements ExecutesMethod {

public void toggleWifi() {
CommandExecutionHelper.execute(this, toggleWifiCommand());
}
}`

Java client: 8.2.0
appium :2.0.0-beta.43
uiautomator2@2.7.0 [installed (NPM)]

**Comment by mykola-mokhnach** [comment] 2022-10-21 06:25
Duplicate of https://github.com/appium/appium/issues/16941

**Closed by mykola-mokhnach** 2022-10-21 06:25 UTC

**Comment by ravibabu101143** [comment] 2022-10-21 06:58
@ mykola-mokhnach

My apologies i am not able to follow it. It shows issue closed. Is this resolved? Can you help me how to resolve this issue?

**Comment by mykola-mokhnach** [comment] 2022-10-21 07:18
There is no way to resolve it as Google changed permissions in newer Android releases and denied non-system apps from changing the wifi state

**Comment by ravibabu101143** [comment] 2022-10-21 07:21
Thank you. Appreciate your response..we will try to do through UI flow instead of through code.
