### ISSUE TITLE
Error: Could not install app: 'Couldn't push 

### ISSUE THREAD

**Issue by romainlouvet** [appium/appium#13413] opened 2019-10-11 15:12 UTC
## The problem

When try to launch new session
Error: Could not install app: 'Couldn't push '/var/folders/mb/84j6wccx1m72h594ny26lpr80000gn/T/2019911-73328-1qpi4mt.x1h3i/Payload/Leboncoin.app/AppIcon20x20@2x.png' within the timeout 30000ms'

## Environment

* Appium version (or git revision) that exhibits the issue: v1.16.0-beta.1
* Mobile platform/version under test: ios
* Real device : iPhone X ios 13.1.2
Mac OS 10.14.5 / Xcode 11.1

## Link to Appium logs

https://gist.github.com/romainlouvet/983861e9c06a060a59141239da6be897

**Comment by mykola-mokhnach** [comment] 2019-10-11 17:43
Duplicate of https://github.com/appium/appium/issues/13330

**Closed by mykola-mokhnach** 2019-10-11 17:43 UTC

**Comment by romainlouvet** [comment] 2019-11-05 13:57
@mykola-mokhnach  same error on appium 1.16.0-beta.1
> [XCUITest] An error was thrown during the installation process. Falling back to ios-deploy
[XCUITest] TimeoutError: Couldn't push '/var/folders/mb/84j6wccx1m72h594ny26lpr80000gn/T/2019105-45148-1bcui4q.860ak/Payload/Leboncoin.app/AppIcon20x20@2x.png' within the timeout 30000ms
[XCUITest]     at afterTimeout (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/timers.js:49:15)
[XCUITest]     at Timeout.timeoutTimeout [as _onTimeout] (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/timers.js:76:13)
[XCUITest]     at ontimeout (timers.js:498:11)
[XCUITest]     at tryOnTimeout (timers.js:323:5)
[XCUITest]     at Timer.listOnTimeout (timers.js:290:5)

**Comment by saranya-duraisamy-dev** [comment] 2019-11-25 01:29
Hi Team,
is there an update on the above issue. Please advise.
We are also facing the issue with the below 
Selenium server version: 3.141
appium version: 1.15.1
npm version: 6.12.1
node version: v13.1.0
Xcode version: 11.2
iOS 12.4.1
