### ISSUE TITLE
The element waits for less than 3 minutes, APPIUM will get stuck, not looking for elements.

### ISSUE THREAD

**Issue by 18070592371** [appium/appium#12413] opened 2019-03-29 13:10 UTC
Hello：
APPIUM version number V1.7.1, 1.7.2, 1.10.0 have this problem, the system is windows10.
I set the element to wait for 330 seconds, but after running for almost 200 seconds, the APPIUM diary will not print, and I will not move to find my element. How can I solve this problem?
![image](https://user-images.githubusercontent.com/37534431/55234827-f7db5880-5266-11e9-8415-c93762da4270.png)
![image](https://user-images.githubusercontent.com/37534431/55234877-0de91900-5267-11e9-9820-b54c376d1ea5.png)

**Comment by mykola-mokhnach** [comment] 2019-03-29 18:48
Please attach full server log. Also, all these Appium versions are out of date. Try the most recent one

**Comment by 18070592371** [comment] 2019-03-30 01:19
@mykola-mokhnach  
This is my report log.
[log.txt](https://github.com/appium/appium/files/3024980/log.txt)

**Comment by 18070592371** [comment] 2019-03-30 01:31
@mykola-mokhnach 
I will use the latest version of appium execution to prompt me that I can't find appium-uiautomator2-server-debug-androidTest.apk and will automatically delete this APK for me. I can't find the reason. Many people have this problem.
Serial number 12180
![image](https://user-images.githubusercontent.com/37534431/55269460-8505c800-52ce-11e9-8e38-3b583a320e4b.png)

**Comment by mykola-mokhnach** [comment] 2019-03-30 07:47
^
The most obvious reason for the above problem is an antivirus, which erroneously threats Appium server apk as viruses and removes them.

**Comment by 18070592371** [comment] 2019-03-30 08:35
@mykola-mokhnach 
I use 1.7.2APPIUM will not be deleted, with the latest version will be deleted, very strange. The main problem is that APPIUM will be dormant after the element has been waiting for a long time. Is there any way?

**Comment by 18070592371** [comment] 2019-03-30 09:32
@mykola-mokhnach 
![image](https://user-images.githubusercontent.com/37534431/55274277-93c19e80-5311-11e9-983e-19a99972899a.png)
I've updated it to the latest version. This is the latest version of log.
About two minutes later, appium was dormant, not helping me find the elements.

**Comment by 18070592371** [comment] 2019-03-30 09:35
@mykola-mokhnach 
The new edition has a wrong diary. Look at it.

[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hu
b/session/4c3e9197-fe2a-494e-86b8-53a17d3fac3b/element] with body: {"strategy":"
xpath","selector":"//h4[text()='个人登录交易系统']","context":"","multiple":fals
e}
[WD Proxy] Got an unexpected response: {"code":"ESOCKETTIMEDOUT","connect":false
}
[debug] [W3C (d096bc99)] Encountered internal error running command: UnknownErro
r: An unknown server-side error occurred while processing the command. Original
error: Could not proxy command to remote server. Original error: Error: ESOCKETT
IMEDOUT
[debug] [W3C (d096bc99)]     at JWProxy.command (C:\Users\Administrator\AppData\
Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy
\proxy.js:236:13)
[HTTP] <-- POST /wd/hub/session/d096bc99-a1b0-441d-8f67-d328829cd095/element 500
 240027 ms - 572
[HTTP]

**Comment by mykola-mokhnach** [comment] 2019-03-30 18:35
What is the output of page source command? Does it contain the target element? 

Have you checked the logcat output? Are there any errors/exceptions there?

Are there any active animations on that page?

**Comment by 18070592371** [comment] 2019-03-31 02:09
@mykola-mokhnach 
The element target will appear in 200 seconds, but the APPIUM log is no longer active. You can try it with APPIUM.

**Comment by 18070592371** [comment] 2019-03-31 02:36
@mykola-mokhnach 
Is this an appium bug? This bug has affected my progress?

**Comment by KazuCocoa** [comment] 2019-03-31 06:34
As

> What is the output of page source command? Does it contain the target element?

, what the result of this?
(and how long did it take?)

I wonder if you can find it as content description. It can find it as find by accessibility id, BTW.

**Comment by 18070592371** [comment] 2019-03-31 06:59
@KazuCocoa 
After about 200 seconds, the element APPIUM stopped searching for the element. It won't continue to help me find the element. After about 500 seconds, the error was reported.

This is an error report.
The new edition has a wrong diary. Look at it.

[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hu
b/session/4c3e9197-fe2a-494e-86b8-53a17d3fac3b/element] with body: {"strategy":"
xpath","selector":"//h4[text()='个人登录交易系统']","context":"","multiple":fals
e}
[WD Proxy] Got an unexpected response: {"code":"ESOCKETTIMEDOUT","connect":false
}
[debug] [W3C (d096bc99)] Encountered internal error running command: UnknownErro
r: An unknown server-side error occurred while processing the command. Original
error: Could not proxy command to remote server. Original error: Error: ESOCKETT
IMEDOUT
[debug] [W3C (d096bc99)] at JWProxy.command (C:\Users\Administrator\AppData
Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy
\proxy.js:236:13)
[HTTP] <-- POST /wd/hub/session/d096bc99-a1b0-441d-8f67-d328829cd095/element 500
240027 ms - 572
[HTTP]

**Comment by KazuCocoa** [comment] 2019-03-31 07:15
Can you share the logcat in the call?

**Comment by 18070592371** [comment] 2019-03-31 07:36
@KazuCocoa @mykola-mokhnach 
[log.txt](https://github.com/appium/appium/files/3026309/log.txt)
This is mine logcat

**Comment by 18070592371** [comment] 2019-04-01 01:35
@KazuCocoa 
Did I find the reason for my problem? I can't work as hard as I can.

**Comment by 18070592371** [comment] 2019-04-01 02:40
@KazuCocoa 
I found that using virtual machines without this problem, real machines will appear.

**Comment by KazuCocoa** [comment] 2019-04-01 08:11
mmm, I could not find odd logs... Purelly, UIA2 failed to find the log.

```
03-31 15:29:24.902 24832 24860 E appium  : io.appium.uiautomator2.common.exceptions.ElementNotFoundException: Could not find an element using supplied strategy. 
03-31 15:29:24.902 24832 24860 E appium  : 	at io.appium.uiautomator2.handler.FindElement.findElement(FindElement.java:106)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:75)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:37)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:243)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
03-31 15:29:24.902 24832 24860 E appium  : 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
03-31 15:29:24.902 24832 24860 E appium  : 	at java.lang.Thread.run(Thread.java:761)
03-31 15:29:24.902 24832 24860 I appium  : AppiumResponse: {"sessionId":"c97aedc1-aec4-4c21-a9eb-a9ae9276af78","status":7,"value":"An element could not be located on the page using the given search parameters."}
03-31 15:29:25.437 24832 24966 I appium  : channel read invoked
```

but actually appium probably stop responsing. It could happen the server stopped or framework's response stopped etc.

```
03-31 15:29:27.223 24832 24967 I appium  : channel read invoked!
03-31 15:29:27.223 24832 24967 I appium  : channel read: POST /wd/hub/session/c97aedc1-aec4-4c21-a9eb-a9ae9276af78/element
03-31 15:29:27.224 24832 24967 I appium  : Find element command
03-31 15:29:27.225 24832 24967 I appium  : find element command using 'xpath' with selector '//android.view.View[@text='阿廉']'.
03-31 15:29:27.232 24880 24880 W ResourceType: No known package when getting name for resource number 0xff000001
03-31 15:29:27.233 24880 24880 W ResourceType: No known package when getting name for resource number 0xff000002
03-31 15:29:27.234 24880 24880 W ResourceType: No known package when getting name for resource number 0xff000003
03-31 15:29:27.235 24880 24880 W ResourceType: No known package when getting name for resource number 0xff000004
03-31 15:29:32.891  1412  1412 I DeviceIdleController: updateChargingLocked: charging=true
03-31 15:29:32.891  1412  1412 I DeviceIdleController: becomeActiveLocked, reason = charging
03-31 15:29:32.900  2185  2185 I BatteryController:  fireBatteryLevelChanged mLevel:82 PluggedIn:true Charging:true Fastcharge:false show:true style:0
03-31 15:29:38.866  1412  1412 I DeviceIdleController: updateChargingLocked: charging=true
03-31 15:29:38.866  1412  1412 I DeviceIdleController: becomeActiveLocked, reason = charging
03-31 15:29:38.867  2185  2185 I BatteryController:  fireBatteryLevelChanged mLevel:82 PluggedIn:true Charging:true Fastcharge:false show:true style:0
03-31 15:29:39.011  1412  2115 D OnePlusProcessManager: checkWhiteUid fail 10088
```

> I found that using virtual machines without this problem, real machines will appear.

Okay. What about changing the real device to another one?
Maybe, the cause is data geting by Android framework.

Another option.
You can run with `automationName: espresso`. The driver get view data by Espresso framework.

**Comment by 18070592371** [comment] 2019-04-01 09:15
@KazuCocoa 
How can I solve this problem?
I'm currently working on a virtual machine.

**Comment by KazuCocoa** [comment] 2019-04-01 16:49
If the issue happens on a particular device model, you can wait for the device update.
Or make view hierarchy simple on your test app if another simple app can work on the device.
e.g. Appium's sample app in https://github.com/appium/appium/tree/master/sample-code

If the test app's view is complicated, resolving the source tree also needs more time.
Potentially, `automationName: espresso` can improve the performance if your test app works fine via Espresso framework than uiautomator framework.(I suggested as _another option_.)

**Comment by 18070592371** [comment] 2019-04-02 02:02
@KazuCocoa 
I think you're right. I should change my equipment.

**Comment by mykola-mokhnach** [comment] 2019-04-04 07:35
Closed as third party issue

**Closed by mykola-mokhnach** 2019-04-04 07:35 UTC
Labels: NeedsInfo, ThirdParty
