### ISSUE TITLE
iOS 13: Appium gets timed out at Sending '_rpc_forwardSocketData:'

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#13270] opened 2019-09-21 07:42 UTC
## The problem

On executing the Appium script on a hybrid app. The script is getting stuck and later timed out at 

```
2019-09-21 07:50:39:258 - [HTTP] --> POST /wd/hub/session/2d7e69d4-96a8-4ae1-bc56-e04819ee958c/element
2019-09-21 07:50:39:258 - [HTTP] {"using":"xpath","value":"//span[text()='xxx']"}
2019-09-21 07:50:39:259 - [debug] [W3C (2d7e69d4)] Calling AppiumDriver.findElement() with args: ["xpath","//span[text()='xxx']","2d7e69d4-96a8-4ae1-bc56-e04819ee958c"]
2019-09-21 07:50:39:259 - [debug] [XCUITest] Executing command 'findElement'
2019-09-21 07:50:39:260 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
2019-09-21 07:50:39:260 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2019-09-21 07:50:39:260 - [debug] [RemoteDebugger] Executing atom 'find_element'
2019-09-21 07:50:39:260 - [debug] [RemoteDebugger] Executing 'find_element' atom in default context
2019-09-21 07:50:39:260 - [debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var k=this;functi...'
2019-09-21 07:50:39:261 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:1169', page '1' (id: 8)
2019-09-21 07:52:39:257 - [HTTP] <-- POST /wd/hub/session/2d7e69d4-96a8-4ae1-bc56-e04819ee958c/element - - ms - -

```
 
## Environment

* Appium version (or git revision) that exhibits the issue:  v1.15.0-beta.1 
* Desktop OS/version used to run Appium: 10.14.5
* Node.js version (unless using Appium.app|exe): v10.16.2
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: iOS 13
* Real device or emulator/simulator: iPhone X
* Appium Python Client: 0.47

## Details

On trying to perform a simple findElement, the appium gets stuck and does not proceed further. After 300 secs it gets timed out. Switching to the webiew and identifying the webview works fine, but no commands are been executed. 

## Link to Appium logs

https://gist.github.com/mayureshshirodkar/6705eb5c6d3ef7f50d29ebb704593cbc

## Code To Reproduce Issue [ Good To Have ]

    element = helper_wait_for_visibility_element(context, xpath, 10)

**Comment by mayureshshirodkar** [comment] 2019-09-23 05:37
@mykola-mokhnach  @imurchie 
I tried the above script on multiple previous iPhone versions:
iOS 12.3.1 
iOS 12.4.1

The scripts are executed on these versions and are not getting stuck at **Sending '_rpc_forwardSocketData:'** 

iOS 12.3.1  logs:
https://gist.github.com/mayureshshirodkar/b4779500de42eade993299b7725d0fef

iOS 12.4.1 logs:
https://gist.github.com/mayureshshirodkar/418789f3d0c2938c5abf0b530a4e4391

iOS 13 logs:
https://gist.github.com/mayureshshirodkar/6705eb5c6d3ef7f50d29ebb704593cbc

**Comment by nghiadhd** [comment] 2019-09-23 10:03
@mayureshshirodkar 
I got same issue with you.
I also got 'An unknown server-side error occurred while processing the command' while running with iOS 9.3.5.

**Comment by imurchie** [comment] 2019-09-27 19:08
Can you try on the latest beta of Appium (`npm uninstall -g appium && npm install -g appium@beta`). v1.16.0-beta.1 should install.

**Comment by imurchie** [comment] 2019-10-02 22:56
Can you try the steps outlined here: https://github.com/appium/appium/issues/13285#issuecomment-537210985

**Comment by mayureshshirodkar** [comment] 2019-10-05 06:41
Thanks @imurchie the latest Appium beta (Appium v1.16.0-beta.1) has fixed the issue.

**Comment by mykola-mokhnach** [comment] 2019-10-06 13:09
Closed as fixed

**Closed by mykola-mokhnach** 2019-10-06 13:09 UTC
Labels: Mobile Safari

**Comment by patrjam** [comment] 2019-11-14 14:23
Hi,

I have the same problem with Sending '_rpc_forwardSocketData, so I uninstalled 1.15.0 version and installed  v1.16.0-beta.1, but it did not fix the issue. Running of tests is veeery slow because of these timeouts.

### The problem:

```
2019-11-14 12:26:35:813 [HTTP] --> POST /wd/hub/session/57ca9e5b-6e17-4114-8b65-ee432ff7d553/elements

2019-11-14 12:26:35:813 [HTTP] {"using":"css selector","value":".input--hp-search"}

2019-11-14 12:26:35:814 [W3C (57ca9e5b)] Calling AppiumDriver.findElements() with args: ["css selector",".input--hp-search","57ca9e5b-6e17-4114-8b65-ee432ff7d553"]

2019-11-14 12:26:35:814 [XCUITest] Executing command 'findElements'

2019-11-14 12:26:35:814 [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id

2019-11-14 12:26:35:815 [BaseDriver] Waiting up to 0 ms for condition

2019-11-14 12:26:35:815 Executing atom 'find_elements'

2019-11-14 12:26:35:815 Executing 'find_elements' atom in default context

2019-11-14 12:26:35:815 Sending javascript command: '(function(){return function(){var k=this;functi...'

2019-11-14 12:26:35:817 Sending '_rpc_forwardSocketData:' message to app 'PID:5399', page '1', target 'page-6' (id: 41)

2019-11-14 12:28:35:813 [HTTP] <-- POST /wd/hub/session/57ca9e5b-6e17-4114-8b65-ee432ff7d553/elements - - ms - -
```

### Environment:
Mobile platform/version under test: iOS 13.2
Real device or emulator/simulator: iPad 2
npm version 6.11.3 
CodeceptJS Appium 


### Code To Reproduce Issue

```
Feature('The Internet example test');

Scenario('Home page', (I) => {

    I.amOnPage('http://www.seznam.cz')
    I.fillField('.input--hp-search', 'dog')
    I.click('.button--with-input')
    I.seeElement('.ZooCardAnimal')
});
```
