### ISSUE TITLE
Appium 1.14.1 on a  iOS 13 device not interacting with elements

### ISSUE THREAD

**Issue by mjm987mj** [appium/appium#13052] opened 2019-08-08 14:06 UTC
## The problem
When trying to validate our application on iOS 13 I see that none of my tests cases are working. When switching back to an iOS 12 device everything works fine. Our mobile elements are based on accessibility identifiers. When inspecting via Appium desktop I can see the identifiers.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.1
* Last Appium version that did not exhibit the issue (if applicable): iOS specific
* Mobile platform/version under test: iOS 13
* Real device or emulator/simulator: simulator and real device
* Appium CLI or Appium.app|exe: CLI

## Details

Test running on < iOS 12 are going fine. When switching to iOS 13 Appium does not interact with the elements.

## Link to Appium logs

https://gist.github.com/mjm987mj/22818bfba95822ea4a2e384450afa266

**Comment by mykola-mokhnach** [comment] 2019-08-08 14:07
Duplicate of https://github.com/appium/appium/issues/12960

iOS14 beta4 is not supported by Appium for now. Lower beta versions are supported only by appium@beta

**Closed by mykola-mokhnach** 2019-08-08 14:07 UTC

**Comment by mjm987mj** [comment] 2019-08-08 14:09
Thanks for the quick reply
