### ISSUE TITLE
【switch to webview】Failed to get PID for the following process

### ISSUE THREAD

**Issue by lynnchma** [appium/appium#13621] opened 2019-11-20 07:34 UTC
# The problem
switch to webview Failed ，but chrome inspect OK

[W3C (d5d964db)] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get PID for the following process: com.whty.xtjk
[W3C (d5d964db)]   (process name must be specified if not equal to package name)
[W3C (d5d964db)]   (Driver info: chromedriver=74.0.3729.6 

# ENV

hybrid APP （ionic）
android 9
android system webview (74.0.3729.136)
appium-desktop：1.15.1
Appium-Python-Client： 0.47

# Des
how can I fixed it？？？
 
# Details
[fail.txt](https://github.com/appium/appium/files/3867834/fail.txt)

**Comment by mykola-mokhnach** [comment] 2019-11-20 08:39
Please use appium@beta

**Comment by mykola-mokhnach** [comment] 2019-11-20 08:40
Also, make sure the web view itself is debuggable and you can inspect it via Chrome remote debugger

**Comment by mykola-mokhnach** [comment] 2019-11-20 08:49
https://stackoverflow.com/questions/52429593/appium-getting-error-failed-to-start-chromedriver-session-original-error-unk could also be helpful

**Comment by mykola-mokhnach** [comment] 2019-11-20 08:58
Possible duplicate of https://github.com/appium/appium/issues/13093

**Comment by mykola-mokhnach** [comment] 2019-11-23 07:17
Closed as third party issue

**Closed by mykola-mokhnach** 2019-11-23 07:17 UTC
Labels: Mobile Chrome, ThirdParty

**Comment by lynnchma** [comment] 2019-12-12 08:36
useless reply

**Comment by imurchie** [comment] 2019-12-12 15:37
You can get more information by specifying the `showChromedriverLog` capability (set to `true`), which will turn on Chromedriver verbose logging, to see what it is trying to do and what it is seeing.

**Comment by wanghengkun** [comment] 2021-03-14 12:15
> Also, make sure the web view itself is debuggable

How to verify debugability？
