### ISSUE TITLE
Returning wrong value for iOS Switch status while using getText() or getAttribute("value") for iOS OS <  13.0

### ISSUE THREAD

**Issue by SharmaKKamal** [appium/appium#13813] opened 2020-01-08 09:13 UTC
## The problem

The appium returning the wrong value for the iOS switch status. I have a iOS switch element which is selected(means ON). In Appium Desktop the value for the element displayed as "1". But when i am using getText() or getAttribute("value") for switch status value, it is returning "0".

However the things works fine for iOS 13. Only iOS OS < 13.0 facing this issue. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable):1.14.1
* Desktop OS/version used to run Appium:Mac (macOS Mojave 10.14.6)
* Node.js version (unless using Appium.app|exe):(10.17.0)
* Npm or Yarn package manager:(6.11.3)
* Mobile platform/version under test: iOS OS 12.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment] 2020-01-08 11:20
Duplicate of https://github.com/appium/appium/issues/13691

Unfortunately we cannot do nothing there as it is an XCTest bug

**Closed by mykola-mokhnach** 2020-01-08 11:20 UTC
