### ISSUE TITLE
npm Install -g appium fails with error as "npm ERR! Failed at the appium-chromedriver@3.0.1 install script 'node install-npm.js"

### ISSUE THREAD

**Issue by anjanabendre** [appium/appium#9460] opened 2017-10-16 10:46 UTC
## On Windows-7, 64 bit, Appium installation via npm failing with error:
npm Install -g appium fails with error as "npm ERR! Failed at the appium-chromedriver@3.0.1 install script 'node install-npm.js"

Trying to install appium using npm:
command: npm install -g appium

every time it fails giving error for chromedriver install issue.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@3.0.1 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@3.0.1 install script 'node install-np
m.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-chromedriver p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log
npm ERR! code 1

## Environment

* Appium version (or git revision) that exhibits the issue: latest
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Windows 7-64 bit
* Node.js version (unless using Appium.app|exe): v6.11.4
* Mobile platform/version under test: Android 6.0.1, 7.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I was facing problem with appium installation using npm. So I have installed Appium GUI version some time back. I am using that. But to start appium programmatically, I need to install appium CLI using npm.
Its failing every time.

## Link to Appium logs
C:\Windows\system32>npm install -g appium
C:\Users\LocaluE0441161\AppData\Roaming\npm\appium -> C:\Users\LocaluE0441161\
pData\Roaming\npm\node_modules\appium\build\lib\main.js

> appium-chromedriver@3.0.1 install C:\Users\LocaluE0441161\AppData\Roaming\np
node_modules\appium\node_modules\appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.30' for platform
in' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.
m/2.30/chromedriver_win32.zip...
RequestError: Error: connect ETIMEDOUT 172.217.4.16:443
    at new RequestError (C:\Users\LocaluE0441161\AppData\Roaming\npm\node_modu
s\appium\node_modules\request-promise\lib\errors.js:11:15)
    at Request.RP$callback [as _callback] (C:\Users\LocaluE0441161\AppData\Roa
ng\npm\node_modules\appium\node_modules\request-promise\lib\rp.js:60:32)
    at self.callback (C:\Users\LocaluE0441161\AppData\Roaming\npm\node_modules
ppium\node_modules\request\request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\LocaluE0441161\AppData\Roaming\npm\nod
modules\appium\node_modules\request\request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
C:\Users\LocaluE0441161\AppData\Roaming\npm
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.x (node_modules\app
m\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevent
1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64
)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@3.0.1 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@3.0.1 install script 'node install-
m.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-chromedriver
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with
npm ERR!     npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log
npm ERR! code 1

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2017-10-16 11:00
Setup the proxy for npm if you are behind a corporate firewall. Also. update npm and node to the most recent version.

**Comment by anjanabendre** [comment] 2017-10-16 11:21
Hi, I am specifying the proxy details as
npm config set proxy http://proxy.***.***.com:8080
npm config set https-proxy http://proxy.***.***.com:8080

My node.js and npm is latets I guess:
npm:  v3.10.10
node: v6.11.4

Will you please specify specific versions I should have.

**Comment by mykola-mokhnach** [comment] 2017-10-16 11:29
Closed as duplicate of https://github.com/appium/appium/issues/9100

**Closed by mykola-mokhnach** 2017-10-16 11:29 UTC
Labels: ThirdParty

**Comment by samsonbarukula** [comment] 2017-11-24 16:04
I have Tried with "npm install -g appium --chromedriver_cdnurl=http://localhost:8080" but still the same error :
Johns-Mac-mini-4:~ john$ npm install -g appium --chromedriver_cdnurl=http://localhost:8080
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js

appium-chromedriver@3.0.1 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
node install-npm.js
info Chromedriver Install Installing Chromedriver version '2.30' for platform 'mac' and architecture '64'
info Chromedriver Install Opening temp file to write chromedriver_mac64 to...
info Chromedriver Install Downloading http://localhost:8080/2.30/chromedriver_mac64.zip...
RequestError: Error: connect ECONNREFUSED 127.0.0.1:8080
at new RequestError (/usr/local/lib/node_modules/appium/node_modules/request-promise/lib/errors.js:11:15)
at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/appium/node_modules/request-promise/lib/rp.js:60:32)
at self.callback (/usr/local/lib/node_modules/appium/node_modules/request/request.js:186:22)
at emitOne (events.js:116:13)
at Request.emit (events.js:211:7)
at Request.onRequestError (/usr/local/lib/node_modules/appium/node_modules/request/request.js:878:8)
at emitOne (events.js:116:13)
at ClientRequest.emit (events.js:211:7)
at Socket.socketErrorListener (_http_client.js:387:9)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at emitErrorNT (internal/streams/destroy.js:64:8)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@3.0.1 install: node install-npm.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/john/.npm/_logs/2017-11-24T15_34_11_801Z-debug.log

**Comment by samsonbarukula** [comment] 2017-11-24 16:56
it is working by setting npm proxy server.... thank you all
