### ISSUE TITLE
Error: Cannot verify the signature , Original error: The JAVA_HOME location

### ISSUE THREAD

**Issue by mohammad-genie** [appium/appium#15205] opened 2021-03-21 12:04 UTC
## The problem

Encountered internal error running command: Error: Cannot verify the signature 
Original error: The JAVA_HOME location 'C:\Program Files\Java\jre1.8.0_261' must exist

How I can run the app without errors.

## Environment

* Appium version Windows desktop: v1.20.2
* Last Appium version that did not exhibit the issue (if applicable): yes
* Desktop OS/version used to run Appium: windows
* Node.js version (unless using Appium.app|exe): v15.12.0
* Npm or Yarn package manager:
* Mobile platform/version under test:  Android 10 
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:
* JDK  16

## Details

Error: Cannot verify the signature

## Link to Appium logs

https://gist.github.com/mohammad-genie/1459eb157e9f9d057deee2e692f10b19

**Comment by mykola-mokhnach** [comment] 2021-03-21 14:44
Duplicate of https://github.com/appium/appium/issues/15137

**Closed by mykola-mokhnach** 2021-03-21 14:44 UTC
