### ISSUE TITLE
"Failed to hide keyboard." error coming on real device with iOS 8.2 and Appium 1.3.7

### ISSUE THREAD

**Issue by sahajamit** [appium/appium#4975] opened 2015-04-21 12:44 UTC
I am facing this issue on a real iPad Mini device with XCode 6.2 and Appium 1.3.7 when I am executing this command 

driver.hideKeyboard()

For me I am setting a value to an editbox and while setting it, it opens the keyboard and this keyboard comes over the Signin button so I am unable to click this signin button as it is hidden behind the keyboard. So this is a kind of blocker for me.

Here is the console error:

info: [debug] Pushing command to appium work queue: "au.hideKeyboard('default')"
info: [debug] Sending command to instruments: au.hideKeyboard('default')
info: [debug] [INST] 2015-04-21 12:28:11 +0000 Debug: responding with:
info: [debug] [INST] 2015-04-21 12:28:11 +0000 Debug: Running system command #41: /usr/local/Cellar/node/0.12.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] [INST] 2015-04-21 12:35:27 +0000 Debug: Got new command 41 from instruments: au.hideKeyboard('default')
info: [debug] [INST] 2015-04-21 12:35:27 +0000 Debug: evaluating au.hideKeyboard('default')
info: [debug] [INST] 2015-04-21 12:35:27 +0000 Debug: target.frontMostApp().mainWindow().tapWithOptions({})
info: [debug] Socket data received (50 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":17,"value":"Failed to hide keyboard."}
info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"Failed to hide keyboard."},"sessionId":"5e684b54-d0de-4d07-91f3-26a4320bfbc8"}
info: <-- POST /wd/hub/session/5e684b54-d0de-4d07-91f3-26a4320bfbc8/appium/device/hide_keyboard 500 18592.068 ms - 185 
info: [debug] [INST] 2015-04-21 12:35:45 +0000 Error: VerboseError: Failed to hide keyboard.
info: [debug] [INST] 2015-04-21 12:35:45 +0000 Error: Error during eval: hideKeyboard@file:///usr/local/lib/node_modules/appium/298D68FC-2943-4D6B-9184-C76C2FF22BF1/bootstrap-445563c75b389324.js:1361:52
eval code
eval@[native code]
startProcessing@file:///usr/local/lib/node_modules/appium/298D68FC-2943-4D6B-9184-C76C2FF22BF1/bootstrap-445563c75b389324.js:2693:30
bootstrap@file:///usr/local/lib/node_modules/appium/298D68FC-2943-4D6B-9184-C76C2FF22BF1/bootstrap-445563c75b389324.js:2761:31
global code@file:///usr/local/lib/node_modules/appium/298D68FC-2943-4D6B-9184-C76C2FF22BF1/bootstrap-445563c75b389324.js:2770:10
info: [debug] [INST] 2015-04-21 12:35:45 +0000 Debug: responding with:

**Comment by Jonahss** [comment] 2015-05-07 23:34
Looks like a duplicate of #4977 5054

**Closed** 2015-05-07 23:35 UTC
