### ISSUE TITLE
Setting AutoWebView / Switching to Webview causes Webdriver crashes on IOS/IpadOS 14.6 

### ISSUE THREAD

**Issue by yadavsvmx** [appium/appium#15505] opened 2021-06-15 17:58 UTC
## The problem

Setting AutoWebView / Switching to Webview causes Webdriver crashes on IOS 14.6 Appium 18.3 to new beta versions

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0 and appium beta
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: MacOs 11.4
* Node.js version (unless using Appium.app|exe): 15
* Npm or Yarn package manager:
* Mobile platform/version under test: IOS / IpadOS 14.6
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI and App both verified

## Details

Setting AutoWebView / Switching to Webview causes Webdriver crashes on IOS/IpadOS 14.6 

Verified in multiple versions of appium CLI and app , its the same

## Link to Appium logs

[https://gist.github.com/yadavsvmx/2b70d2cd8d0ae875d36147f8595a57da.js](url)

## Code To Reproduce Issue [ Good To Have ]

Set the setCapability("autoWebview", true) capability 

OR

In between after app launch try to switch to webview
E.g
Set<String> availableContextNames = driver.getContextHandles();

driver.context("WebView");

**Comment by mykola-mokhnach** [comment] 2021-06-15 18:21
I don't observe any explicit errors in the attached log. Could you be more specific about which part of it corresponds to the described issue?

**Comment by yadavsvmx** [comment] 2021-06-16 02:52
Updated Console log:
[https://gist.github.com/yadavsvmx/2b70d2cd8d0ae875d36147f8595a57da.js](url)

Mainly in console I get this error:

 org.openqa.selenium.InvalidElementStateException: The application under test with bundle id 'com.servicemaxinc.svmxfieldserviceapp' is not running, possibly crashed
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'MacBook-Pro-2.local', ip: 'fe80:0:0:0:10b8:b6d:1a3b:ed74%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '15.0.1'
Driver info: io.appium.java_client.ios.IOSDriver

Reattaching the logs with the location of error:

debug] [RemoteDebugger] Sending javascript command: 'document.readyState;'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:3966', page '2' (id: 34): 'Runtime.evaluate'
[debug] [RemoteDebugger] Application 'PID:3966' disconnected. Removing from app dictionary.
[debug] [RemoteDebugger] Current app is 'PID:3966'
[debug] [RemoteDebugger] No longer have app id. Attempting to find new one.
[debug] [RemoteDebugger] Application 'PID:3966' disconnected. Removing from app dictionary.
[debug] [RemoteDebugger] Current app is 'PID:3966'
[debug] [RemoteDebugger] No longer have app id. Attempting to find new one.
[debug] [RemoteDebugger] Page readiness check timed out after 5000ms
[debug] [RemoteDebugger] Page unloading
[debug] [RemoteDebugger] Waiting for dom...
[debug] [RemoteDebugger] Page load timer not a timer. Creating new timer
[debug] [RemoteDebugger] Page loaded, verifying whether ready
[debug] [RemoteDebugger] Not connected to an application. Ignoring page load
[debug] [RemoteDebugger] Page load completed in 503ms
[debug] [RemoteDebugger] Selected page after 5521ms
[debug] [RemoteDebugger] Starting to listen for JavaScript console
[debug] [RemoteDebugger] Starting to listen for network events
[debug] [RemoteDebugger] Unregistering from page readiness notifications
[debug] [BaseDriver] Event 'initialWebviewNavigated' logged at 1623811806132 (08:20:06 GMT+0530 (India Standard Time))
[debug] [BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[debug] [BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[Appium] New XCUITestDriver session created successfully, session c57b398e-a5f6-4cc9-99a7-42c8e7d610ef added to master session list

**Comment by KazuCocoa** [comment] 2021-06-16 03:54
What happens when you attach to the WebView via Safari Web Inspector?
I wondered https://github.com/appium/appium/issues/15325 . If your Web View was `UIWebView` instead of `WKWebView`, the root cause might be Apple side.

**Comment by yadavsvmx** [comment] 2021-06-16 03:57
Yes, i observed that when I attach it to safri dev console also, it crashes the app / does not load the web-view

Found something related to this here:
https://github.com/WebKit/WebKit/commit/db0740fe4f4d8ec1ccd673582a61bb55605c268e

**Comment by jlipps** [comment] 2021-06-16 17:58
More or less a duplicate of https://github.com/appium/appium/issues/15325, then. UIWebView is no longer supported by Apple or Appium. If the safari dev console web inspector does not work on the webview, then neither will Appium.

**Closed by jlipps** 2021-06-16 17:58 UTC
Labels: Mobile Safari, ThirdParty
