### ISSUE TITLE
js.executeScript("mobile: swipe", swipeObject) and scroll throws error "..Proxy error: Could not proxy command to remote server. Original error: 404 - undefined"

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#9771] opened 2017-12-09 18:30 UTC
## The problem

1. I need to do swipe / scroll action android device and below is the code
           
 ```
HashMap<String, String> swipeObject = new HashMap<String, String>();
swipeObject.put("direction", "up");
swipeObject.put("startX", "120");
swipeObject.put("startY", "650");
swipeObject.put("endX", "120");
swipeObject.put("endY", "35");
swipeObject.put("duration", "1.8");
//js.executeScript("mobile: swipe", swipeObject);  //FAILS
 js.executeScript("mobile: scroll", swipeObject); //FAILS
```
this is not working on android device with below error

`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined (WARNING: The server did not provide any stacktrace information)`

```
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:536)

```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2-beta2
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: MAC  10.12.6
* Node.js version (unless using Appium.app|exe):  v8.4.0
* Mobile platform/version under test: Android physical device 6.0
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

```
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/ce516ed4-86cb-4550-a046-45271ce4f7d3/execute] to [POST http://localhost:8200/wd/hub/session/df49e9ac-376f-47f2-b48d-fecfa93cc43b/execute] with body: {"script":"mobile: swipe","args":[{"duration":"1.8","endY":"35","endX":"120","startY":"650","startX":"120","direction":"up"}]}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined
    at doJwpProxy$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/mjsonwp/mjsonwp.js:397:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[HTTP] <-- POST /wd/hub/session/ce516ed4-86cb-4550-a046-45271ce4f7d3/execute 500 17 ms - 274 

```
## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2017-12-09 18:33
There is no such endpoint on android. Use TouchAction interface instead.

Closed as not an issue.

**Closed by mykola-mokhnach** 2017-12-09 18:33 UTC

**Comment by vikramvi** [comment] 2017-12-09 18:49
@mykola-mokhnach I think we need to fix error message with proper info.

**Comment by mykola-mokhnach** [comment] 2017-12-09 19:34
Such generic message is always shown as a response to any non-existing endpoint query. You're welcome to push a PR if you'd like to improve it.

**Comment by vikramvi** [comment] 2017-12-10 07:25
@mykola-mokhnach can you please point me to latest document about swipe / scroll on both iOS and Android, I will submit PR for documentation for sure

**Comment by KazuCocoa** [comment] 2017-12-10 07:56
Only for XCUITest, the below is the `mobile:` related actions.
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md

And more commonly, the followings are commands for interactions so far.
https://github.com/appium/appium/tree/master/docs/en/commands/interactions

**Comment by vikramvi** [comment] 2017-12-10 10:08
@KazuCocoa  Thanks for info, I will put this in my to-do for next week

**Comment by jinisrivastava-Mediware** [comment] 2018-09-11 06:16
Then how can we perform swipe gesture in C# with touchaction because TouchAction.perform() is showing error method not yet implemented.

**Comment by KazuCocoa** [comment] 2018-09-11 06:45
I guess the error comes from Appium server. If so, the error isn't C# specific issue.
Could you share the log with us? Since I'm curious about what command/s get/s the error. @jinisrivastava-Mediware

**Comment by jinisrivastava-Mediware** [comment] 2018-09-11 06:54
I am using appium version 1.6.2 and visual studio 2015

**Comment by KazuCocoa** [comment] 2018-09-11 07:10
Do you mean you can't get server-side logs? hm..

If the 1.6.2 is https://github.com/appium/appium/releases/tag/v1.6.2 , that's outdated version.
What about using `appium@1.9.0`?

**Comment by jinisrivastava-Mediware** [comment] 2018-09-11 07:10
i am sorry its version 1.8.1 and visual studio 2015

**Comment by KazuCocoa** [comment] 2018-09-11 09:43
ah, web. Maybe, you tried to work with Chrome browser on Android, right? @jinisrivastava-Mediware 
In the case, it depends on the Chrome driver, I assume. (I can guide/assume correctly if you have any logs though)

Can you share your capabilities here? It helps to guess the cause.

**Comment by jinisrivastava-Mediware** [comment] 2018-09-11 09:54
Yes i am trying to work with chrome browser on Android.
I am using these capabilities:
 var cap = new DesiredCapabilities();
                cap.SetCapability("platformName", "Android");
              
                cap.SetCapability("deviceName", "Samsung Galaxy Note 10.1");
                cap.SetCapability(MobileCapabilityType.BrowserName, "Chrome");
                cap.SetCapability("webdriver.chrome.driver", @"..\ChromeDriver\chromedriver.exe");
                var driver = new AndroidDriver<AndroidElement>(new Uri("http://127.0.0.1:4723/wd/hub"), cap);

**Comment by SacDin** [comment] 2019-08-20 17:23
If it does not exist, why it is still written here in code examples ?
http://appium.io/docs/en/writing-running-appium/touch-actions/#scrolling
