### ISSUE TITLE
Safari on iPad, error with proxying web views

### ISSUE THREAD

**Issue by pmswatuser** [appium/appium#13059] opened 2019-08-10 16:41 UTC
## The problem

Unable to run mobile web tests on real iOS device or simulator. This could seem similar to #5794 but that issue was locked down due to inactivity.

## Environment
- Appium version 1.12.1 and 1.13.0
- Xcode 10.3
- Appium java-client 3.4.1
- iOS 12.2 on real iPad 6th gen
- Appium server on Mac OS Mojave

## Details

Followed all instructions to setup Appium for real iOS device, as found under http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/

The WDA is deployed to the device and the test launches safari but does not navigate to the URL specified in the code or get web views. IWDP was started using all suggested methods. 

ios_webkit_debug_proxy returns 9222 for attach A, first device with the UDID

Also tried launching IWDP using ios_webkit_debug_proxy -c  <udid>:27753 -d and changing the port to 9222. Tried combination of both, keeping both sessions on.

## Link to Appium logs
gist log link for Appium and iOS-webkit-debug-proxy logs

https://gist.github.com/pmswatuser/2d5b0428828d2b9b07d25fa223d0c063

## Code
Capabilitites used:
		capabilities = new DesiredCapabilities();
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "name-of-device");
		capabilities.setCapability(MobileCapabilityType.UDID, "removed");
		capabilities.setCapability(MobileCapabilityType.PLATFORM, "iOS");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "12.2");
		capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");
		capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");

**Comment by mykola-mokhnach** [comment] 2019-08-10 17:56
Duplicate of https://github.com/appium/appium/search?q=%22%27Console%27+domain+was+not+found%22&unscoped_q=%22%27Console%27+domain+was+not+found%22

**Closed by mykola-mokhnach** 2019-08-10 17:56 UTC

**Comment by pmswatuser** [comment] 2019-08-10 18:59
Duplicate of what? Cannot access that link.

**Comment by mykola-mokhnach** [comment] 2019-08-10 19:20
There are many. https://github.com/appium/appium/issues/12869, for example, has exactly the same problem and the solution was to update the server.

**Comment by pmswatuser** [comment] 2019-08-11 03:48
I don't see how they are same, although the title uses the word "web views". Anyway, this is closed and I'm already using the latest server to begin with.
