### ISSUE TITLE
Error while executing CLI command for help.

### ISSUE THREAD

**Issue by WasiqB** [appium/appium#9569] opened 2017-11-01 10:59 UTC
## The problem

When executing command `appium -h`, I don't see help with available command list. Instead I get an exception.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 8.8.1
* NPM version: 5.4.2
* Mobile platform/version under test: NA
* Real device or emulator/simulator: NA
* Appium CLI or Appium.app|exe: CLI

## Details

Execute following command:

```sh
$ appium -h
```

## Link to Appium logs

[See Error Log here](https://gist.github.com/WasiqB/9daf9124c617b525d68c0cc1ca15f25c)

**Comment by mykola-mokhnach** [comment] 2017-11-01 11:03
Duplicate of https://github.com/appium/appium/issues/9529

**Closed by mykola-mokhnach** 2017-11-01 11:03 UTC
