### ISSUE TITLE
 [XCUITest] Error: Could not navigate to webview! Err: Cannot read property 'deviceId' of undefined

### ISSUE THREAD

**Issue by Baymax408** [appium/appium#8119] opened 2017-03-29 02:31 UTC
## The problem

XCUITestDriver try to navigate to web view of my Hybrid app on my iPhone, but failed.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): Unknown
* Desktop OS/version used to run Appium: MAC 10.12.3
* Node.js version (unless using Appium.app|exe): 4.5.0
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

1. Start ios_webkit_debug_proxy and bind my iPhone's UDID to port 27753.
ios_webkit_debug_proxy -c 193FA77169C1FEB115326DA2AF342FA4C23D2541:27753
Connected :27753 to little white rabbit (193fa77169c1feb115326da2af342fa4c23d2541)
2. Start appium.
[Appium] Welcome to Appium v1.6.3
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
3. Run my test case.
Eclipse: Neon.2 Release (4.6.2)
TestNG: 6.10
Java Client: 5.0.0-BETA4
4. WebDriverAgentRunner.app and my target app have been installed and launched on the phone.

## Link to Appium logs
The error log is short, so I paste them here.

[debug] [XCUITest] Waiting for initial webview
[debug] [iOS] Waiting for 3000 ms before navigating to view.
[debug] [iOS] Navigating to most recently opened webview
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false 
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[XCUITest] Error: Could not navigate to webview! Err: Cannot read property 'deviceId' of undefined
    at XCUITestDriver.spinHandles$ (../../../lib/commands/context.js:495:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:136:37)
 Error: Could not navigate to webview! Err: Cannot read property 'deviceId' of undefined
    at XCUITestDriver.spinHandles$ (../../../lib/commands/context.js:495:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:136:37)

## Code To Reproduce Issue [ Good To Have ]

capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,deviceConfig.getString("deviceName"));
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION,deviceConfig.getString("platformVersion"));
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.IOS);
capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,AutomationName.IOS_XCUI_TEST);
capabilities.setCapability(MobileCapabilityType.UDID, deviceConfig.getString("UDID"));
capabilities.setCapability(MobileCapabilityType.AUTO_WEBVIEW, true);
capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, CMD_TIMEOUT);

**Comment by mykola-mokhnach** [comment] 2017-03-29 06:03
Please attach full log.

**Comment by mykola-mokhnach** [comment] 2017-03-29 06:03
Might be a duplicate of https://github.com/appium/appium/issues/8091

**Comment by Baymax408** [comment] 2017-03-29 06:45
OK. Full logs are here. Please check, thanks.
gist:26fb85c897f5c38c07d8fe8c9c98c2a4

**Comment by Baymax408** [comment] 2017-03-29 06:47
<script src="https://gist.github.com/anonymous/26fb85c897f5c38c07d8fe8c9c98c2a4.js"></script>

**Comment by mykola-mokhnach** [comment] 2017-03-29 07:08
The attached gist is not available as a link

**Comment by Baymax408** [comment] 2017-03-29 09:48
Sorry, updated the gist link above.

**Comment by mykola-mokhnach** [comment] 2017-03-29 09:50
got 404

**Comment by imurchie** [comment] 2017-03-29 13:28
Webkit is returning something weird. I've updated the code to be a little more defensive, which should at least allow us to see what, if anything, is being returned.

Could you re-install appium (`npm uninstall -g appium && npm install -g appium@beta`) and try again? There will still be an error but it should get us a step closer to figuring out the root cause.

**Comment by Baymax408** [comment] 2017-03-29 23:47
@imurchie Thank you. I will update to both the latest Appium 1.6.4 beta and Java Client 5.0.0-BETA6, then try again. BTW, Apple has delivered Xcode 8.3 with iOS 10.3 two days ago, shall I update them too?

**Comment by imurchie** [comment] 2017-03-30 12:14
I would hold off on upgrading Xcode/iOS if your having an issue already.

**Comment by Baymax408** [comment] 2017-04-01 02:48
@imurchie After I updated to Appium 1.6.4-beta.2 and Java Client 5.0.0-BETA6, "No web frames found" error was in an endless loop.
Steps:
1. Code signing for /usr/local/lib/node_modules/appium/node_modules/.2.25.1@appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj in Xcode
2. ios_webkit_debug_proxy -c 193fa77169c1feb115326da2af342fa4c23d2541:27753
Connected :27753 to little white rabbit (193fa77169c1feb115326da2af342fa4c23d2541)
3. Start appium
[Appium] Welcome to Appium v1.6.4-beta.2
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"capabilities":[{"desiredCapabilities":{"app":"/Users/user/Documents/workspace/IPWCMobileAutoTest/apps/IBM_MNAA.ipa","platformVersion":"10.2","automationName":"XCuiTest","autoWebview":true,"platformName":"iOS","udid":"193fa77169c1feb115326da2af342fa4c23d2541","deviceName":"little white rabbit"}},{"requiredCapabilities":{}}],"desiredCapabilities":{"app":"/Users/user/Documents/workspace/IPWCMobileAutoTest/apps/IBM_MNAA.ipa","platformVersion":"10.2","automationName":"XCuiTest","autoWebview":true,"platformName":"iOS","udid":"193fa77169c1feb115326da2af342fa4c23d2541","deviceName":"little white rabbit"},"requiredCapabilities":{}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/user/Documents/workspace/IPWCMobileAutoTest/apps/IBM_MNAA.ipa","platformVersion":"10.2","automationName":"XCuiTest","autoWebview":true,"platformName":"iOS","udid":"193fa77169c1feb115326da2af342fa4c23d2541","deviceName":"little white rabbit"},{},[{"desiredCapabilities":{"app":"/Users/user/Documents/workspace/IPWCMobileAutoTest/apps/IBM_MNAA.ipa","platformVersion":"10.2","automationName":"XCuiTest","autoWebview":true,"platformName":"iOS","udid":"193fa77169c1feb115326da2af342fa4c23d2541","deviceName":"little white rabbit"}},{"requiredCapabilities":{}}],null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1491012694341 (10:11:34 GMT+0800 (CST))
[Appium] Creating new XCUITestDriver (v2.25.1) session
[Appium] Capabilities:
[Appium]   app: '/Users/user/Documents/workspace/IPWCMobileAutoTest/apps/IBM_MNAA.ipa'
[Appium]   platformVersion: '10.2'
[Appium]   automationName: 'XCuiTest'
[Appium]   autoWebview: true
[Appium]   platformName: 'iOS'
[Appium]   udid: '193fa77169c1feb115326da2af342fa4c23d2541'
[Appium]   deviceName: 'little white rabbit'
[debug] [XCUITest] XCUITestDriver version: 2.25.1
[BaseDriver] Session created with session id: e39b10d0-90f9-4b62-89a6-2195b2b49b22
[debug] [XCUITest] Xcode version set to '8.2.1' (tools v8.2.0.0.1.1480973914)
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1491012696328 (10:11:36 GMT+0800 (CST))
[debug] [XCUITest] Available devices: 193fa77169c1feb115326da2af342fa4c23d2541
[debug] [XCUITest] Creating iDevice object with udid '193fa77169c1feb115326da2af342fa4c23d2541'
[XCUITest] Determining device to run tests on: udid: '193fa77169c1feb115326da2af342fa4c23d2541', real device: true
[BaseDriver] Using local app '/Users/user/Documents/workspace/IPWCMobileAutoTest/apps/IBM_MNAA.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/d2/2m8tw_f51q5g6rkrj7403tm00000gn/T/201731-3273-hpmw8e.mp5g1wz5mi/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/d2/2m8tw_f51q5g6rkrj7403tm00000gn/T/201731-3273-hpmw8e.mp5g1wz5mi/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/d2/2m8tw_f51q5g6rkrj7403tm00000gn/T/201731-3273-hpmw8e.mp5g1wz5mi/Payload/IBM_MNAA.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1491012697379 (10:11:37 GMT+0800 (CST))
[debug] [XCUITest] Checking whether app '/var/folders/d2/2m8tw_f51q5g6rkrj7403tm00000gn/T/201731-3273-hpmw8e.mp5g1wz5mi/Payload/IBM_MNAA.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/d2/2m8tw_f51q5g6rkrj7403tm00000gn/T/201731-3273-hpmw8e.mp5g1wz5mi/Payload/IBM_MNAA.app': 'com.ibm.cio.be.iphone.mnaa'
[debug] [BaseDriver] Event 'resetStarted' logged at 1491012697387 (10:11:37 GMT+0800 (CST))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1491012697388 (10:11:37 GMT+0800 (CST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1491012697557 (10:11:37 GMT+0800 (CST))
[XCUITest] Setting up real device
[debug] [XCUITest] Reset requested. Removing app with id 'com.ibm.cio.be.iphone.mnaa' from the device
[debug] [XCUITest] Installing '/var/folders/d2/2m8tw_f51q5g6rkrj7403tm00000gn/T/201731-3273-hpmw8e.mp5g1wz5mi/Payload/IBM_MNAA.app' on device with UUID '193fa77169c1feb115326da2af342fa4c23d2541'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1491012709549 (10:11:49 GMT+0800 (CST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1491012709551 (10:11:49 GMT+0800 (CST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/.2.25.1@appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/.2.25.1@appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[debug] [XCUITest] Creating WebDriverAgent resources directory
[debug] [XCUITest] Creating WebDriverAgent resource bundle directory
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/.2.25.1@appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=193fa77169c1feb115326da2af342fa4c23d2541 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.2' in directory '/usr/local/lib/node_modules/appium/node_modules/.2.25.1@appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-gkaivcogndvvwlfvntjomxsnftja/Logs/Test/3AB60E0C-5474-4794-8970-D0AF7F029657/Session-WebDriverAgentRunner-2017-04-01_101212-g3WzlJ.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.2\",\n      \"ip\" : \"9.112.129.39\"\n    },\n    \"build\" : {\n      \"time\" : \"Apr  1 2017 10:12:04\"\n    }\n  },\n  \"sessionId\" : \"9BAAE867-F7B7-49C4-8329-A5BD4F319872\",\n  \"status\" : 0\n}"
[debug] [XCUITest] WebDriverAgent running on ip '9.112.129.39'
[debug] [XCUITest] WebDriverAgent successfully started after 23663ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1491012742488 (10:12:22 GMT+0800 (CST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.ibm.cio.be.iphone.mnaa","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"A935FB6B-B0C6-4C77-B319-9922F49AFC54","capabilities":{"device":"iphone","browserName":"IBM M&AA","sdkVersion":"10.2","CFBundleIdentifier":"com.ibm.cio.be.iphone.mnaa"}},"sessionId":"A935FB6B-B0C6-4C77-B319-9922F49AFC54","status":0}
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1491012744179 (10:12:24 GMT+0800 (CST))
[debug] [XCUITest] Found WDA derived data folder: '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-atmcauubtrczumbsbbrkgsmgewed'
[XCUITest] Setting '555' permissions to '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-atmcauubtrczumbsbbrkgsmgewed/Logs/Test/Attachments' folder
[debug] [XCUITest] Found WDA derived data folder: '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-gkaivcogndvvwlfvntjomxsnftja'
[XCUITest] Setting '555' permissions to '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-gkaivcogndvvwlfvntjomxsnftja/Logs/Test/Attachments' folder
[debug] [BaseDriver] Event 'wdaPermsAdjusted' logged at 1491012744183 (10:12:24 GMT+0800 (CST))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1491012744183 (10:12:24 GMT+0800 (CST))
[debug] [XCUITest] Setting initial orientation to 'PORTRAIT'
[debug] [JSONWP Proxy] Proxying [POST /orientation] to [POST http://localhost:8100/session/A935FB6B-B0C6-4C77-B319-9922F49AFC54/orientation] with body: {"orientation":"PORTRAIT"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"A935FB6B-B0C6-4C77-B319-9922F49AFC54","status":0}
[debug] [BaseDriver] Event 'orientationSet' logged at 1491012744512 (10:12:24 GMT+0800 (CST))
[debug] [XCUITest] Waiting for initial webview
[debug] [iOS] Waiting for 3000 ms before navigating to view.
[debug] [iOS] Navigating to most recently opened webview
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false 
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[debug] [RemoteDebugger] Page element JSON: []
[debug] [iOS] No web frames found.
[iOS] Could not find any webviews yet, refreshing/retrying
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false 
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[debug] [RemoteDebugger] Page element JSON: []
[debug] [iOS] No web frames found.
[iOS] Could not find any webviews yet, refreshing/retrying
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false 
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[debug] [RemoteDebugger] Page element JSON: []
[debug] [iOS] No web frames found.
[iOS] Could not find any webviews yet, refreshing/retrying
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false

**Comment by imurchie** [comment] 2017-04-03 14:35
Is anything being found by the ios-webkit-debug-proxy? If you manually go to the page, with the proxy running, what is returned when you use
```
curl --get http://localhost:27753/json
```

**Comment by Baymax408** [comment] 2017-04-05 01:59
@imurchie the inspectable pages for little white rabbit is BLANK when I type http://localhost:27753 in Chrome. So is it the problem in my target ipa? Project source code structure is attached.
<img width="259" alt="code structure" src="https://cloud.githubusercontent.com/assets/16680837/24686449/893a92f2-19e6-11e7-8362-2d4c7ef73d8a.png">

**Comment by pnrpramod** [comment] 2017-04-27 20:16
I have similar issue, but, it works fine for simulator.

To outline the scenarios exactly,

1. When I launch the app on the device, I see nothing
curl --get http://localhost:9223/json returns me []

2. When I launch the .app file built locally on simulator, I am able to switch to web view.

**Comment by pnrpramod** [comment] 2017-04-27 20:17
@imurchie Please suggest if this sounds known

**Comment by imurchie** [comment] 2017-04-28 13:01
Unfortunately if the proxy does not return anything, there is not much Appium can do.

It may be known. It would be worth exploring the proxy project: https://github.com/google/ios-webkit-debug-proxy

**Comment by bitpit** [comment] 2017-05-11 16:32
second this issue, i have the same symptoms with the environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): Unknown
* Desktop OS/version used to run Appium: Mac OS X 10.12.4
* Node.js version: v7.7.4
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

Works great on the iOS simulator, on the Android device, and on the Android emulator, craps out on the real iOS device.

WebDriverAgent installs and boots successfully, the hybrid app under test installs and boots successfully, but then I get the `Could not find any webviews yet, refreshing/retrying` ad infinitum.

Also getting the empty array when `curl`ing the device; however, if I open Safari and pull up a tab, that shows up in the `curl`ed results...

**Closed** 2017-07-20 15:19 UTC
Labels: LogRequested, XCUITest
