### ISSUE TITLE
Accessibility services stops when running appium tests on android device

### ISSUE THREAD

**Issue by vivek978** [appium/appium#6170] opened 2016-02-22 16:29 UTC
## The problem

I am automating an android application which uses accessibility services to function. As soon as I use appium with the app accessibility services stops.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.4.0
- Last Appium version that did not exhibit the issue (if applicable): 
- Desktop OS/version used to run Appium: Mac OS X Yosomite
- Node.js version (unless using Appium.app|exe): 
- Mobile platform/version under test: Android 4.4.4
- Real device or emulator/simulator: Real Device
- Appium CLI or Appium.app|exe:  Appium.app
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

**Comment by scottdixon** [comment] 2016-03-01 18:37
@vivek978 - please try with a more recent version of Appium:
`npm install -g appium`

Let me know if the issue persists and I'll investigate further.

**Comment by vivek978** [comment] 2016-03-02 09:47
I checked with more recent version of Appium i.e 1.5, but issue still persist.

**Comment by nikhil969** [comment] 2016-06-02 11:00
any updates

**Comment by adarliu** [comment] 2016-10-11 08:53
I also met this issue. After some investigation, I think this issue was not caused by Appium, but a limitation of Android uiautomator. It seems when ui automator is running, the other app accessibility services will be stopped.

To prove this, you can:
1 enable the accessibility "TalkBack", or any other third-party apps.
2 start uiautomator process: adb shell uiautomator events (This will just print the accessibility events)
3 The "TalkBack" service (or any other apps) won't work.

**Comment by srahul91** [comment] 2017-07-17 06:52
Hi Guys,
I am also facing the same issue with Appium 1.6.5 version. Is there any update on this ???

**Comment by dpgraham** [comment] 2017-07-20 18:33
Duplicate of: https://github.com/appium/appium/issues/4910

This is a third party problem.

**Closed by dpgraham** 2017-07-20 18:33 UTC
Labels: Android
