### ISSUE TITLE
IOS13(Iphone11)Fail to take screenshot!

### ISSUE THREAD

**Issue by jiaoyujulx** [appium/appium#13590] opened 2019-11-12 11:58 UTC
## The problem

IOS13(Iphone11)Fail to take screenshot!

## Environment

* Appium version (or git revision) that exhibits the issue:1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:10.14.5
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:ios13.0
* Appium CLI or Appium.app|exe:

## Details

IOS13+(Iphone11)Fail to take screenshot,12+and bellow is sucessful.
 
## Link to Appium logs

19:40:55.056 [Thread-6] INFO  util.Util - [idevicescreenshot -u 00008030-0002399A36C0802E /Users/mt2/Desktop/bengkui/UICrawler/UICrawler-master/target/crawler_output/00008030-0002399A36C0802E-2019-11-12-19_39_49/del.png]  ---output is : Usage: idevicescreenshot [OPTIONS] [FILE]
Gets a screenshot from a device.
The screenshot is saved as a TIFF image with the given FILE name,
where the default name is "screenshot-DATE.tiff", e.g.:
   ./screenshot-2013-12-31-23-59-59.tiff

NOTE: A mounted developer disk image is required on the device, otherwise
the screenshotr service is not available.

  -d, --debug		enable communication debugging
  -u, --udid UDID	target specific device by its 40-digit device UDID
  -h, --help		prints usage information

Homepage: <http://libimobiledevice.org>
19:40:55.057 [Thread-6] INFO  util.Driver - screenShotName: /Users/mt2/Desktop/bengkui/UICrawler/UICrawler-master/target/crawler_output/00008030-0002399A36C0802E-2019-11-12-19_39_49/screenshot/2019-11-12_19-40-55.png
19:40:55.057 [Thread-6] INFO  util.Driver - Fail to take screenshot!
java.io.FileNotFoundException: Source '/Users/mt2/Desktop/bengkui/UICrawler/UICrawler-master/target/crawler_output/00008030-0002399A36C0802E-2019-11-12-19_39_49/del.png' does not exist
	at org.apache.commons.io.FileUtils.checkFileRequirements(FileUtils.java:1383)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1060)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1028)
	at util.Driver.takeScreenShot(Driver.java:154)
	at util.Driver.takeScreenShot(Driver.java:133)
	at util.PictureUtil.takeAndModifyScreenShot(PictureUtil.java:88)
	at util.PictureUtil.takeAndModifyScreenShot(PictureUtil.java:83)
	at util.PictureUtil.takeAndModifyScreenShot(PictureUtil.java:77)
	at util.PictureUtil.takeAndModifyScreenShot(PictureUtil.java:72)
	at util.PictureRunnable.run(PictureUtil.java:41)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mykola-mokhnach** [comment] 2019-11-12 12:56
Can you please provide the full server log? also, since version 1.15 libmobiledevice is not used anymore, so I'm not quire sure this error is coming from

**Comment by umutuzgur** [comment] 2019-11-12 19:15
@jiaoyujulx This is not related to Appium but I know what the problem is. You need to push the developer images to the phone. You can either do that with `ideviceimagemounter` or by starting xcode and it will take care of it

**Comment by jiaoyujulx** [comment] 2019-11-13 09:33
I try to do run ideviceimagemounter command,but remainly failed.The information is ImageMountFailed

**Comment by mykola-mokhnach** [comment] 2019-11-16 09:25
Closed as not an Appium issue. Please use Appium forum to ask questions

**Closed by mykola-mokhnach** 2019-11-16 09:25 UTC
Labels: NeedsInfo, NotABug
