### ISSUE TITLE
driver.findElementById(ID).clear(); method is not working for iOS 12.x with Xcode 11 to clear text in textfield 

### ISSUE THREAD

**Issue by deepu451** [appium/appium#13409] opened 2019-10-11 07:00 UTC
## The problem

driver.findElementById(ID).clear() method is no longer working for iOS 12.x with Xcode 11, Appium 1.15.0

## Environment

* Appium version (or git revision) that exhibits the issue:1.15.0
* Last Appium version that did not exhibit the issue (if applicable):1.14.2
* Desktop OS/version used to run Appium:MAC OS Mojave 10.14.6
* Node.js version (unless using Appium.app|exe):10.15.3
* Npm or Yarn package manager:6.9.0
* Mobile platform/version under test:iPhone 6(iOS 12.2)
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:

## Details

Appium server returning the result as null

## Link to Appium logs
Attached the Appium server logs at the step of clear method.

[HTTP] 
[HTTP] --> POST /wd/hub/session/5817e547-7b04-4f53-a2fb-84db21c1ed0b/element/34000000-0000-0000-3201-000000000000/clear
[HTTP] {"id":"34000000-0000-0000-3201-000000000000"}
[debug] [W3C (5817e547)] Calling AppiumDriver.clear() with args: ["34000000-0000-0000-3201-000000000000","5817e547-7b04-4f53-a2fb-84db21c1ed0b"]
[debug] [XCUITest] Executing command 'clear'
[debug] [WD Proxy] Matched '/element/34000000-0000-0000-3201-000000000000/clear' to command name 'clear'
[debug] [WD Proxy] Proxying [POST /element/34000000-0000-0000-3201-000000000000/clear] to [POST http://localhost:8100/session/F4FA6B3A-F75D-49D0-A248-824A8313ECA2/element/34000000-0000-0000-3201-000000000000/clear] with no body
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : null,
[debug] [WD Proxy]   "sessionId" : "F4FA6B3A-F75D-49D0-A248-824A8313ECA2"
[debug] [WD Proxy] }
[debug] [W3C (5817e547)] Responding to client with driver.clear() result: null
[HTTP] <-- POST /wd/hub/session/5817e547-7b04-4f53-a2fb-84db21c1ed0b/element/34000000-0000-0000-3201-000000000000/clear 200 211 ms - 14

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2019-10-11 07:52
Duplicate of https://github.com/appium/appium/issues/13288

It might be that the page source has changed with the new SDK. Make sure the clear action is sent to the appropriate element (having text field type) and update the locator accordingly.

**Closed by mykola-mokhnach** 2019-10-11 07:52 UTC
