### ISSUE TITLE
Cant run on real iOS, app still terminate and restarts

### ISSUE THREAD

**Issue by MildaGenius** [appium/appium#12266] opened 2019-03-06 10:41 UTC
## The problem
When trying run test application on iOS device (Android is working), application starts for while, then terminate and start again.

[https://www.youtube.com/watch?v=LKipTZBIr_M](url)

## Environment

* Appium version: 1.11.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.14.3
* Node.js version (unless using Appium.app|exe): v10.15.1
* Npm package manager: 6.4.1
* Real device or emulator/simulator: iPad 9.7 with OS 11.3
* Appium CLI or Appium.app|exe:  Desktop
* xCode: 10.1

## Details

Running simple iOS app from Unity3D on iPad over Appium results into cyclic app restarting on device.

I can see this error in log:
`Could not proxy command to remote server. Original error: Error: socket hang up). Retrying...` which looks like in this post [https://github.com/appium/appium/issues/12155](url)

or
`Error: socket hang up Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.`

## Link to Appium logs

[Appium log](https://gist.github.com/MildaGenius/76c4445bd19193b9e8c03fa2d462669b)
[Testing python script](https://gist.github.com/MildaGenius/91fecfbfb1239944ee120dc783274eff)

## Code To Reproduce Issue [ Good To Have ]

`#!/usr/bin/python

import unittest
from appium import webdriver

desired_caps = {}
desired_caps['showXcodeLog'] = 'true'
desired_caps['platformName'] = 'iOS'
desired_caps['platformVersion'] = '11.3'
desired_caps['xcodeOrgId'] = '7DC7W55G5S'
desired_caps['automationName'] = 'xcuitest'
desired_caps['xcodeSigningId'] = 'iPhone Developer'
desired_caps['bundleId'] = 'com.bistudio.DebuggerTest'
desired_caps['deviceName'] = 'BIMG_Milan_Malek_iPad9.7'
desired_caps['udid'] = 'auto'

driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
#driver.unlock()
#self.driver.unlock()`

**Comment by mykola-mokhnach** [comment] 2019-03-06 10:45
Please attach the correct server log with xcodebuild and iOS logging enabled

**Comment by MildaGenius** [comment] 2019-03-06 10:50
Fixed urls to logs.

**Comment by mykola-mokhnach** [comment] 2019-03-06 12:34
It does not look like the full log. WDA build is still in progress there

**Comment by MildaGenius** [comment] 2019-03-06 13:46
Event if you [view full file](https://gist.githubusercontent.com/MildaGenius/76c4445bd19193b9e8c03fa2d462669b/raw/036187d954bfbea388cc8c8bf9ddc14a89fd7d69/startDebuggerTestiOS_log.txt)?

**Comment by mykola-mokhnach** [comment] 2019-03-06 13:54
Try to increase the default startup timeout. Seems like on your machine WDA requires more time for compilation than is assigned by default

**Comment by MildaGenius** [comment] 2019-03-06 15:14
Which timeout do you exactly mean and when is possible to change it?

I try this:
`desired_caps['launchTimeout'] = '600000'`
but the result is the same.

[Appium log with launchTimeout 600000](https://gist.githubusercontent.com/MildaGenius/4ddd63faa5adfa10f844b5755386a2e2/raw/6571bc03fb3f377c94b4ed524916c3a63de4e366/startDebuggerTestiOS_launchTimeout_log.txt)

**Comment by mykola-mokhnach** [comment] 2019-03-06 18:04
wdaLaunchTimeout

**Comment by MildaGenius** [comment] 2019-03-06 18:55
The same behaviour for 
`desired_caps['wdaLaunchTimeout'] = 600000`

[Appium log with wdaLaunchTimeout 600000](https://gist.github.com/MildaGenius/4fd5868d0082b2c9428c842d681e0ed4)

**Comment by mykola-mokhnach** [comment] 2019-03-06 19:39
Try also wdaStartupRetryInterval/wdaStartupRetries

**Comment by mykola-mokhnach** [comment] 2019-03-06 19:55
If that does not help then the problem is most likely on [WebDriverAgent](https://github.com/facebook/WebDriverAgent) side, so we can do nothing to solve it.

**Comment by mykola-mokhnach** [comment] 2019-03-06 20:20
> [debug] [35m[WD Proxy][39m Got response with status 200: ""

This string also looks suspicious to me. Make sure the iproxy service works as expected, because WDA must return proper JSON instead of an empty strings

**Comment by MildaGenius** [comment] 2019-03-08 06:24
Finally I found source of weird behaviour.

Problem is in checked "Connect via network" in xCode device organiser.

[xCode Connect via network](https://photos.google.com/photo/AF1QipPd6xnd4v8CEpmUfMB34OmKBmeZqw8djGtUvOCo)

After uncheck this options in xCode problem is gone.

**Comment by mykola-mokhnach** [comment] 2019-03-08 07:18
Good to know that. Closed as resolved

**Closed by mykola-mokhnach** 2019-03-08 07:18 UTC
Labels: ThirdParty, XCUITest

**Comment by ManningZhang** [comment] 2019-03-18 13:58
@MildaGenius I met the same error like yours, but my iphone was running via network,so your solution"unlock via network" may be unuseful, do you have other solutions?

**Comment by MildaGenius** [comment] 2019-03-18 15:58
@ManningZhang

**Comment by MildaGenius** [comment] 2019-03-18 16:01
@ManningZhang
So mayby you can try it over cabel?

Second case of these error was, when I run game from xCode and let this connection still active.
