### ISSUE TITLE
Cannot run latest appium app (1.4.13) with xcode 7.0.1

### ISSUE THREAD

**Issue by igalep** [appium/appium#5724] opened 2015-10-14 08:32 UTC
Hi,

I've updated the appium app to the latest ver (1.4.13) and using xcode 7.0.1

On the first launch I got "error: uncaughtException: Cannot find module 'appium-instruments'"

After following the next post :http://stackoverflow.com/questions/33080101/appium-failed-to-start-uncaught-error-instruments

I'm getting next error :
[INST STDERR] dyld: could not load inserted library '/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib' because no suitable image found.  Did find:
	/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib: mmap() error 1 at address=0x10447C000, size=0x00001000 segment=__TEXT in Segment::map() mapping /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib

**Comment by scottdixon** [comment] 2015-10-14 16:05
Duplicate of https://github.com/appium/appium/issues/5720

Let me know if this doesn't solve the issue and I'll reopen.

**Closed by scottdixon** 2015-10-14 16:05 UTC
Labels: NeedsTriage

**Comment by igalep** [comment] 2015-10-15 11:25
Worked for me, thanks !!
