### ISSUE TITLE
InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

### ISSUE THREAD

**Issue by imkouga** [appium/appium#10876] opened 2018-06-14 05:34 UTC
## The problem

Testing started at 13:24 ...
/usr/bin/python "/Applications/PyCharm CE.app/Contents/helpers/pycharm/_jb_unittest_runner.py" --target vip.VIPTest.test_vip
Launching unittests with arguments python -m unittest vip.VIPTest.test_vip in /Users/sunny/test/ttxs_android_test/testcase/personalcenter
超时了，没有找到元素:com.hlg.daydaytobusiness:id/tv_skip_ad
无启屏广告页
非小米手机，没有权限弹框
无活动弹窗
无升级弹窗
无继续编辑模板弹窗

Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/Users/sunny/test/ttxs_android_test/testcase/personalcenter/vip.py", line 23, in test_vip
    self.driver.find_element_by_id("com.hlg.daydaytobusiness:id/rl_new_vip").click()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 791, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session

## Environment

* Appium version is 1.8.1:
* macOS sierra 10.12.6

**Comment by mykola-mokhnach** [comment] 2018-06-14 05:50
Duplicate of https://github.com/appium/appium/issues/10874

**Closed by mykola-mokhnach** 2018-06-14 05:50 UTC
