### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by PythonDarkening** [appium/appium#13675] opened 2019-12-03 23:04 UTC
## The problem

I am not able to run several test cases at the same time due to socket hang up

## Environment

* Appium version: 1.15.1
* Desktop OS/version used to run Appium: MacOS Mojave 10.14.6
* Node.js version (v12.12.0):
* Npm:
* Mobile platform/version under test: Android version Q
*emulator:
* Appium CLI:

## Details

I have several test cases in mocha, and when I run by separately they run perfectly, but the issue is when I run them together the following message appears:

- An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

and most of the test cases starts to fail

## Link to Appium logs

Please check the logs
https://gist.github.com/PythonDarkening/1f37b17cd4e56e187154444a5051e573

Any help here is welcome

**Comment by KazuCocoa** [comment] 2019-12-04 00:46
Thanks.
Can you get the logcat and attach it?

**Comment by PythonDarkening** [comment] 2019-12-04 04:54
sure, this is the logcat

- https://gist.github.com/PythonDarkening/3eaf492bfc0c67a99fd3c389639d031a

**Comment by mykola-mokhnach** [comment] 2019-12-04 07:18
In the attached log I can observe that some parallel sessions are being terminated because of command timeout while the others are running. Please check the client script properly quits sessions after test cases are finished (in the tear down section).

**Comment by PythonDarkening** [comment] 2019-12-04 16:03
how can I terminate a session? I mean, there is a command for this?

**Comment by mykola-mokhnach** [comment] 2019-12-04 16:06
In Python, I think, there is `driver.quit` method for that

**Comment by PythonDarkening** [comment] 2019-12-04 16:08
I am with JavaScript, I`ve tried this method but seems that does not works

**Comment by mykola-mokhnach** [comment] 2019-12-04 16:10
Sorry, I don't have expertise in all the clients. Try asking at Appium forum

**Comment by KazuCocoa** [comment] 2019-12-05 07:18
https://appium.io/docs/en/commands/session/delete/

```
// webdriver.io example
driver.endSession();

// wd example
await driver.quit();
```

?

**Comment by PythonDarkening** [comment] 2019-12-05 20:50
thanks but that does not works with javascript

**Comment by KazuCocoa** [comment] 2019-12-06 01:05
What does not work mean?

1. the original issue happened
2. the JS delete session code did not work (Then, the full server log helps us if the cause was client side or Appium server side)
    - I'm not familiar with JS clients, so it is needed to take a look at their documentation if it was client side

**Comment by mykola-mokhnach** [comment] 2019-12-09 15:27
Closed as not an issue. I would try to look for help at the particular client forum

**Closed by mykola-mokhnach** 2019-12-09 15:27 UTC
Labels: NeedsInfo, NotABug

**Comment by samanthamurphy5** [comment] 2020-01-07 18:23
I'm having the similar original problem to @PythonDarkening.

I have a set of four groovy files with tests in them. Selecting and running the Tests 1-4, not the folder itself, I can get two test files to pass, one after the other. The other two don't run as well. Of these other two, I ran the first once, and it had issues during the test but didn't stop and made it through. Running these other two again, the first test passed completely this time, but about 40 seconds into test two, the test stopped with:

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up (WARNING: The server did not provide any stacktrace information)

Running on a real device.
Appium version: 1.14.0-beta.1
Windows 10
IntelliJ IDEA 2018.2.8 (Community Edition) Build #IC-182.5262.2, build on March 28, 2019
JRE: 1.8.0_152

**Logs from IntelliJ IDEA:**
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 21 milliseconds
Build info: version: '2.53.1', revision: 'x', time: '2016-06-30 19:26:09'
System info: host: 'LaptopName', ip: 'x.x.x.x', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=companyApp, statBarHeight=24, noReset=true, viewportRect={top=24, left=0, width=1920, height=1056}, deviceName=x, platform=LINUX, chromeAndroidProcess=companyAndroidProcess, deviceUDID=x, chromedriverExecutable=C:\ChromedriverV2.38\chromedriver.exe, desired={appPackage=x, noReset=true, autoWebView=true, deviceName=x, chromeAndroidProcess=x, appActivity=x, chromedriverExecutable=C:\ChromedriverV2.38\chromedriver.exe, newCommandTimeout=3660, platformVersion=9, showChromedriverLog=true, automationName=UiAutomator2, autoGrantPermissions=true, platformName=Android, device=Android, cssSelectorsEnabled=true}, newCommandTimeout=3660, platformVersion=9, showChromedriverLog=true, webStorageEnabled=false, automationName=UiAutomator2, takesScreenshot=true, javascriptEnabled=true, platformName=Android, deviceApiLevel=28, deviceManufacturer=freescale, deviceScreenSize=1920x1080, networkConnectionEnabled=true, warnings={}, autoWebView=true, databaseEnabled=false, appActivity=x, pixelRatio=1, locationContextEnabled=false, autoGrantPermissions=true, deviceScreenDensity=160, deviceModel=X, device=Android, cssSelectorsEnabled=true}]
Session ID: 8fabc640-66c4-4129-a887-6cfa84d9796b
*** Element info: {Using=id, value=x:id/setup_title}

at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:388)
at io.appium.java_client.DefaultGenericMobileDriver.findElements(DefaultGenericMobileDriver.java:48)
at io.appium.java_client.AppiumDriver.findElements(AppiumDriver.java:195)
at org.openqa.selenium.remote.RemoteWebDriver.findElementsById(RemoteWebDriver.java:421)
at io.appium.java_client.DefaultGenericMobileDriver.findElementsById(DefaultGenericMobileDriver.java:60)
at io.appium.java_client.AppiumDriver.findElementsById(AppiumDriver.java:199)
at org.openqa.selenium.By$ById.findElements(By.java:210)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:351)
at io.appium.java_client.DefaultGenericMobileDriver.findElements(DefaultGenericMobileDriver.java:44)
at io.appium.java_client.AppiumDriver.findElements(AppiumDriver.java:191)
at io.appium.java_client.pagefactory.bys.ContentMappedBy.findElements(ContentMappedBy.java:36)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:351)
at io.appium.java_client.DefaultGenericMobileDriver.findElements(DefaultGenericMobileDriver.java:44)
at io.appium.java_client.AppiumDriver.findElements(AppiumDriver.java:191)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:154)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:1)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:88)
at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:103)
at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:57)
at org.openqa.selenium.support.ui.ExpectedConditions$12.apply(ExpectedConditions.java:341)
at org.openqa.selenium.support.ui.ExpectedConditions$12.apply(ExpectedConditions.java:337)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
at util.AbstractScreen.waitForTextInElementLong(AbstractScreen.groovy:195)
at util.AndroidSetup.waitForTextInElementLong(AndroidSetup.groovy:154)
at tests.MainClasses.xClass.x(x.groovy:302)

**Comment by israe1** [comment] 2021-09-01 19:54
I had this same issue and all I had to do was to close my emulator, clear the data and restart it back. I think the problem has a link with cached data of the emulator but I don't know what exactly the problem is.

**Comment by MOliv3ira** [comment] 2022-08-24 15:26
I had the same problem, but in my case I deleted the emulator apk and installed it again. A tip every time you use the emulator install the apk. 

Hope this helps you guys.
