### ISSUE TITLE
bug: <title>iPhone 6sp启动WDA失败，提示崩溃信息

### ISSUE THREAD

**Issue by liuyabin-svg** [appium/appium#20627] opened 2024-09-28 10:39 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在 低端机上，WDA 安装成功，http://127.0.0.1:8100/status访问显示正常，但是Test后APP桌面没有启动起来，Xcode显示崩溃
![iShot_2024-09-28_18 36 55](https://github.com/user-attachments/assets/4c9437c4-9512-4455-b181-02e82c2d2eeb)
![iShot_2024-09-28_18 36 55](https://github.com/user-attachments/assets/9249ad67-cd9f-410f-86ec-06999602c53a)
Crash: WebDriverAgentRunner-Runner (14381) 0x102fd8000: Namespace SIGNAL, Code 0xb

### Expected Behavior

点击Test后能够在桌面启动WDA成功

### Minimal Reproducible Example

![iShot_2024-09-28_18 36 55](https://github.com/user-attachments/assets/38dbaa2d-0e3e-4abf-842a-97695856c889)

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

![iShot_2024-09-28_18 36 55](https://github.com/user-attachments/assets/5a1053b0-d3d7-43f2-a4b8-bbe10e1eaec9)

**Comment by eglitise** [comment] 2024-09-28 16:27
Duplicate of #20626. Reiterating once again, please fill out all the requested details when creating your issue - we cannot help you otherwise.

**Closed by eglitise** 2024-09-28 16:27 UTC
Labels: Bug, Needs Triage
