### ISSUE TITLE
After update android API version through SDK manager then getting an error

### ISSUE THREAD

**Issue by usshah** [appium/appium#12749] opened 2019-06-10 12:53 UTC
## The problem

Updated API version through SDK manager due to work on emulator and then open automation script and run it then got the error i.e..
 "**Encountered internal error running command: Error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command ''C:\\Program Files (x86)\\Android\\android-sdk-windows\\platform-tools\\adb.exe' -P 5037 -s PDAID18102005437 shell getprop ro.build.version.release' exited with code 3221226356'; Stderr: ''; Code: '322122635'** "

**Automation script is properly working till yesterday with every version of android**

**Environment**
Appium version : 1.6.2
OS : Window 10
Real device Mobile : Samsung 
OS : 7.1.1 & 9

**Logs:** 
Encountered internal error running command: Error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command ''C:\\Program Files (x86)\\Android\\android-sdk-windows\\platform-tools\\adb.exe' -P 5037 -s PDAID18102005437 shell getprop ro.build.version.release' exited with code 3221226356'; Stderr: ''; Code: '3221226356'
[MJSONWP]     at ADB.callee$0$0$ (C:\Users\user1\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\adb-commands.js:89:11)
[MJSONWP]     at tryCatch 

(C:\Users\user1\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] 

(C:\Users\user1\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] 

(C:\Users\user1\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke 

(C:\Users\user1
\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- POST /wd/hub/session 500 4593 ms - 462

**Capabilities:**
deviceName : PDAID18102
platformName : Android
appPackage : com.demo.test
appActivity: be3c2a.SplashActivity
platformVersion: 9
app: path

![Error](https://user-images.githubusercontent.com/49755321/59196475-66fcf380-8bac-11e9-93ee-9028a38a9cec.PNG)

**Comment by KazuCocoa** [comment] 2019-06-10 13:47
Do you use version 29 tools? According to some issues, the version has issues on Windows
e.g. https://discuss.appium.io/t/unable-to-perform-appium-test-after-latest-android-studioupdate/26721 , https://github.com/appium/appium/issues/12736

**Comment by usshah** [comment] 2019-06-10 14:12
@KazuCocoa Yes. I'm using version 29 (API level) but It also create issue on 7.1.1 Nougat (API level 25) as well?
Just deleted all the packages in version 29 tools through SDK manager and getting same error

**Comment by KazuCocoa** [comment] 2019-06-10 14:20
Not sure, but I sometimes see the error code on Windows x adb in stackoverflow.

The cause is probably Windows and adb. What about restarting/re-install etc...

**Comment by Amrkamel1** [comment] 2019-06-10 14:49
@usshah
download platform-tools version 28 , delete the one u have (29) and but version 28 in same directory /android/sdk/platfom-tools

**Comment by usshah** [comment] 2019-06-11 05:51
@KazuCocoa  : Restart/Re-install latest version but still it's not working and getting same error i.e..

An unknown server-side error occurred while processing the command. Original error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command ''C:\\Program Files (x86)\\Android\\android-sdk-windows\\platform-tools\\adb.exe' -P 5037 -s 07d79c460ddf4c50 shell getprop ro.build.version.release' exited with code 3221226356'; Stderr: ''; Code: '3221226356'

**Comment by usshah** [comment] 2019-06-11 05:54
@Amrkamel1 
I have already version - 28 and deleted 29 but still it is not working

**Comment by KazuCocoa** [comment] 2019-06-11 06:50
Can you do https://github.com/appium/appium/issues/12736#issuecomment-500644829 ?
We should clarify the cause if the adb returns error code even if the command returns exact value.
If such mismatch happens, we should ask/report Google by Windows users.

**Comment by usshah** [comment] 2019-06-11 07:58
@KazuCocoa : Now script is running as downgraded 29 to 28 platform tool version
@Amrkamel1 : You are right. I have deleted install packages on 29 API level but didn't downgrade so it didn't work After downgrade platform tool version 29 to 28 script is running

Downgrade version for different OS:
Windows: http://dl-ssl.google.com/android/repository/platform-tools_r28.0.2-windows.zip
macOS: http://dl-ssl.google.com/android/repository/platform-tools_r28.0.2-darwin.zip
Linux: http://dl-ssl.google.com/android/repository/platform-tools_r28.0.2-linux.zip

@KazuCocoa  @Amrkamel1 Thanks for your valuable time to investing on this :)

**Comment by SergeySerj** [comment] 2019-06-11 08:23
Guys, I was able to resolve similar error by updating SDK tools [details](https://github.com/appium/appium/issues/12736#issuecomment-500738217)

**Comment by mykola-mokhnach** [comment] 2019-06-12 20:12
Closed as third party issue

**Closed by mykola-mokhnach** 2019-06-12 20:12 UTC
Labels: ThirdParty
