### ISSUE TITLE
iOS 15.3.1 Unable to click or type in list elements found via By.className

### ISSUE THREAD

**Issue by ikhaled28** [appium/appium#16495] opened 2022-02-23 22:04 UTC
## The problem

iOS 15.3.1 Unable to click or type in list elements found via By.className ( String values are not shown for getText )

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v2.0.0-beta.25, Appium 1.22.0, Appium 1.22.0
* Last Appium version that did not exhibit the issue (if applicable): 1.20.2
* Desktop OS/version used to run Appium: macOS Monterey 12.2.1 (21D62)
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 15.3.1
* Real device or emulator/simulator: iPhone 11
* Appium CLI or Appium.app|exe: Appium CLI 

## Details

I tried to find a TextField element by className and wrote into it. The list element was found, but the click or typing did not work. 

## Link to Appium logs

https://gist.github.com/ikhaled28/cd7ab3f712242fdb6cddcffcec6924f9

**Comment by KazuCocoa** [comment] 2022-02-24 02:02
Could you share the device log as well?

Possible workarounds are
- click the element with coordinate like via W3C actions
- send keys to an active element e.g. https://github.com/appium/appium/issues/16419#issuecomment-1031764419

**Comment by ikhaled28** [comment] 2022-02-24 10:12
@KazuCocoa it solved by clicking with coordinate. One naive question I turned on "appium:showXcodeLog" but where to look for the device log? Is it the log which available at Xcode console?

**Comment by mykola-mokhnach** [comment] 2022-02-24 14:16
The issue might have something to do with https://github.com/appium/appium/issues/16497. Check if a vanilla XCTest could tap these fields properly

**Comment by KazuCocoa** [comment] 2022-02-24 17:35
> One naive question I turned on "appium:showXcodeLog" but where to look for the device log?

`appium:showIOSLog` outputs the device log as appium log. The showXcodeLog is for xcodebuild stuff.

**Comment by KazuCocoa** [comment] 2022-02-24 17:37
> it solved by clicking with coordinate.

Nice. Then, I guess the root cause was XCTest framework internal, only apple can improve it. Appium calls tap action in XCTest API as the endpoint.

**Comment by mykola-mokhnach** [comment] 2022-03-01 06:28
Closed as third party issue

**Closed by mykola-mokhnach** 2022-03-01 06:28 UTC
Labels: ThirdParty, XCUITest
