### ISSUE TITLE
Appium: run ios real device via network

### ISSUE THREAD

**Issue by world-tian** [appium/appium#12362] opened 2019-03-21 13:37 UTC
## The problem

Cannot run ios real device via network. I should use via network to do appium test. My test environment can run appium with cable successfully, but via network won't

## Environment

* Appium version (or git revision) that exhibits the issue: v1.11.1
* Last Appium version that did not exhibit the issue (if applicable): ?
* Desktop OS/version used to run Appium: 10.14.3
* Node.js version (unless using Appium.app|exe): v11.6.0
* Npm or Yarn package manager: 6.5.0
* Mobile platform/version under test:  12.1.4
* Real device or emulator/simulator: real device iphone7

## Details

1. WDA can launch successfully via network without Appium, can get response from http://localhost:8100/status
2. Use Appium to do test, Appium can launch wda server, but cannot get the json data from http://localhost:8100/status
3. If telnet localhost 8100, when Appium launch WDA, you will see the log "Connected to localhost
Escape character is '^]'. Connection closed by foreign host.",so refused quickly after trying to get data from WDA server.

## Link to Appium logs

[debug] [XCUITest] Using Xcode configuration file: '/var/folders/t1/dcfxdngx5_1gvjt5k00p9p140000gn/T/2019221-35880-12thohg.44hzh/appium-temp.xcconfig'
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=758c795277e6871626cf621bee9a69a580a901f9 -xcconfig /var/folders/t1/dcfxdngx5_1gvjt5k00p9p140000gn/T/2019221-35880-12thohg.44hzh/appium-temp.xcconfig' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will be logged. To change this, use 'showXcodeLog' desired capability
[Xcode] Build settings from configuration file '/var/folders/t1/dcfxdngx5_1gvjt5k00p9p140000gn/T/2019221-35880-12thohg.44hzh/appium-temp.xcconfig':
[Xcode] 
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode]     CODE_SIGN_IDENTITY = iPhone Developer
[Xcode]     DEVELOPMENT_TEAM = 7UL3LRJL93
[Xcode] 
[Xcode] 
[WD Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}

## Code To Reproduce Issue [ Good To Have ]

do test via network with real device.

**Comment by world-tian** [comment] 2019-03-21 13:54
Can anyone use Appium test iOS real device via network.

**Comment by mykola-mokhnach** [comment] 2019-03-21 13:57
Duplicate of https://github.com/appium/appium/issues/12089

**Comment by world-tian** [comment] 2019-03-21 14:14
Ok. I will try other version appium

**Closed** 2019-03-25 06:54 UTC
Labels: ThirdParty
