### ISSUE TITLE
appiun didn't see app expo application on Android 7.0-8.0

### ISSUE THREAD

**Issue by ArtemAbakumov** [appium/appium#11808] opened 2018-12-10 13:02 UTC
## The problem

I run the any application created using Expo, the application starts, but the appium writes that the application is not running

## Environment

* Appium version (or git revision) that exhibits the issue: all, latest 1.9
* Last Appium version that did not exhibit the issue (if applicable): all versions
* Desktop OS/version used to run Appium: ubuntu 18.04, macOS mojave
* Node.js version (unless using Appium.app|exe):v8.10.0
* Mobile platform/version under test: 7.0-8.0
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: both

## Details
I tried using appPackage, appWaitPackage, appWaitActivity with different variation
and the app is seen on the android version 5.1.1 or 9.0
thanks for the help

## Link to Appium logs

https://gist.github.com/ArtemAbakumov/a8b06ddd368bfa891f3a7eb98ff6e2db

## Code To Reproduce Issue [ Good To Have ]
from appium appImage
{
  "platformName": "android",
  "deviceName": "emulator-5554",
  "app": "./app/berlogaapp.apk",
  "noReset": false,
  "appWaitAcivity": "*",
  "platformVersion": "7.1.1"
}

**Comment by mykola-mokhnach** [comment] 2018-12-10 13:38
Duplicate of https://github.com/appium/appium/issues/11804

**Closed by mykola-mokhnach** 2018-12-10 13:38 UTC
Labels: NeedsInfo, NotABug

**Comment by ArtemAbakumov** [comment] 2018-12-10 13:52
I used ui2 the same result
