### ISSUE TITLE
hit gyp ERR! build error  appium install 1.9.1 with node 11.0 and npm 6.4.1

### ISSUE THREAD

**Issue by helenren** [appium/appium#11795] opened 2018-12-06 18:41 UTC
try to install appium 1.9.1 via npm install -g appium@1.9.1, hit following error. node version is 11.0, npm version is 6.4.1.  While with npm 3.10.0 and node 7.1.0 it works fine. Any one hit the same issue.

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/11.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/appium/node_modules/heapdump
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: heapdump@0.3.9 (node_modules/appium/node_modules/heapdump):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: heapdump@0.3.9 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by helenren** [comment] 2018-12-06 18:48
the more related error:
heapdump@0.3.9 install /usr/local/lib/node_modules/appium/node_modules/heapdump
> node-gyp rebuild

  CXX(target) Release/obj.target/addon/src/heapdump.o
In file included from ../src/heapdump.cc:17:
../src/compat-inl.h:300:19: error: no member named 'GetCpuProfiler' in 'v8::Isolate'
  return isolate->GetCpuProfiler()->StartProfiling(title, record_samples);
         ~~~~~~~  ^
../src/compat-inl.h:310:19: error: no member named 'GetCpuProfiler' in 'v8::Isolate'
  return isolate->GetCpuProfiler()->StopProfiling(title);
         ~~~~~~~  ^

**Comment by mykola-mokhnach** [comment] 2018-12-06 20:47
Duplicate of https://github.com/appium/appium/issues/11587

**Closed by mykola-mokhnach** 2018-12-06 20:47 UTC
