### ISSUE TITLE
bug: WindowsDriver is not recognizing xpath locator strategy

### ISSUE THREAD

**Issue by Klarahov** [appium/appium#19522] opened 2023-12-12 13:01 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [ ] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using a Windows 11 VM to run my tests in. These tests have been running green for months in another VM, on Windows 10. They also run green on a physical Windows 11 machine. There are various issues with the windows driver, to start with it's not recognizing xpath as a valid strategy anymore.

![image](https://github.com/appium/appium/assets/79255275/d1f9b7dc-6ce9-402a-a88f-02ecc66a07f0)

Please see https://github.com/SeleniumHQ/selenium/issues/13269#issuecomment-1851940885

Other issues I experienced when temporarily disabling the xpath locators I had
https://discuss.appium.io/t/no-attributes-are-being-recognized/40625
https://discuss.appium.io/t/action-sendkeys-command-not-recognized/40646

### Expected Behavior

The driver should not complain about the xpath locator strategy.

### Minimal Reproducible Example

Run a test in a Win 11 VM.

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s): Appium WebDriver 5.0.0-rc2
- Appium plugin(s) and their version(s): -
- Node.js version (output of `node --version`): 20.10.0
- `npm` version (output of `npm --version`): 10.2.3
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Windows app
- Real device or emulator/simulator: -

**Comment by Klarahov** [comment] 2023-12-12 17:39
So basically there is nothing we can do? I also ran the tests with WinAppDriver directly + an older Appium WebDriver version and it doesn’t work. Is there any other Driver to try except the WindowsDriver (I mean the driver in the test) for Windows apps..? I get the feeling I cannot use Appium anymore for Windows tests.

**Comment by mykola-mokhnach** [comment] 2023-12-12 18:29
There are some alternatives, although I don't observe much of [interest](https://discuss.appium.io/t/winappdriver-and-dotnet-client-development-and-maintenance/40240) there from the contribution perspective.

**Comment by daluu** [comment] 2023-12-13 21:11
For alternatives, you'd have to find one that is WebDriver / JSONWireProtocol compatible to be usable with Appium. The one @mykola-mokhnach mentioned would be one of the best alternatives. I had compiled a list a while back for possible alternatives from a request from someone else, but note that that was with respect to a test framework, so it may have some listings that are not relevant to this context here.

https://github.com/Accruent/robotframework-applicationlibrary/issues/72#issuecomment-1745389341

**Comment by daluu** [comment] 2023-12-13 21:18
Just for reference/tracking, you may want to file the issue with WnAppDriver project as well, so that others are aware, and maybe someone else has your issue and might have a fix or workaround. But in terms of the actual tool developer to help you, based on this: https://github.com/microsoft/WinAppDriver/issues/1550, good luck with that ...

**Comment by daluu** [comment] 2023-12-13 21:29
For your issue, to dig at the root of the problem unless the WinAppDriver developers can investigate and tell you, you probably would have to do more testing to find exact deployment scenario where problem occurs.

- we know physical PC + Win11 works
- we know Win 10 VM works

For the Win 10 VM is it exactly the same VM config as this win 11? Sometimes the VM config can make a difference if not exactly same.

Also with respect to VM, if I had time, I would debug further to see if you would get same issue if you deployed a Win 11 VM using alternative tools than VMWare:

- Oracle VirtualBox
- Microsoft Hyper-V
- UTM (on macOS)
- other VM providers

would like to know if the issue is specific to VMWare or not. Based on your post in Selenium forum:

```
This is the config of my VM
OS Name: MIcrosoft Windows 11 Pro
Version: 10.0.2262
System Manufacturer: VMware, Inc.
System Model: VMware7,1
System Type: x64-based PC
Processor: Intel(R) Xeon(R)
```

I would also confirm if the VM session console UI is unlocked with desktop open, not sure if remote access or locking VM has implications for GUI automation not operating correctly - it has in the past.

**Comment by mykola-mokhnach** [comment] 2023-12-13 22:01
> Just for reference/tracking, you may want to file the issue with WnAppDriver project as well, so that others are aware, and maybe someone else has your issue and might have a fix or workaround. But in terms of the actual tool developer to help you, based on this: https://github.com/microsoft/WinAppDriver/issues/1550, good luck with that ...

@daluu Actually I meant a [different thing](https://github.com/licanhua/YWinAppDriver/issues/33#issuecomment-1712837924) 
We'd be happy to replace the one from MS with an open-source alternative, just looking for a person or a team who would be ready to maintain it on a regular basis, so we don't get into the same kind of troubles we are now. Maybe you know some people that would be interested in that kind of activity or feel strong in dotnet development and want to participate yourself?

**Comment by daluu** [comment] 2023-12-13 22:32
Thanks for the clarification @mykola-mokhnach. What I was referring to previously was not about Appium project not being able to help here, but that WinAppDriver project is not likely going to help fix any bugs or investigate the issue on their end, but regardless the OP could/should file an issue there just for reference for all. Pardon me, if I wasn't being clear.

I would be interested to help, but I don't have much time nor work on GUI automation these days, so I couldn't step up to be an active maintainer.

**Comment by Klarahov** [comment] 2023-12-14 07:02
Thanks for all replies! For the VM type, it would be interesting try a different one if I get a chance (however the working Win 10 VM is basically the same as the non-working Win 11 VM apart from the processor). I'm also now trying out FlaUI instead of Appium for Windows automation to not be dependent on WinAppDriver. It seems very fast and so far working with the little code I've tried. The downside is that I then cannot reuse my code with Android and iOS and I have to split my implementations instead of having reusable code for all three platforms.

**Comment by mykola-mokhnach** [comment] 2023-12-18 08:07
Closed as third party issue

**Closed by mykola-mokhnach** 2023-12-18 08:07 UTC
Labels: Windows, ThirdParty

**Comment by licanhua** [comment] 2023-12-18 17:50
@Klarahov I guess you are using the wrong version of WinAppDriver. Expecting [v1.2-RC](https://github.com/microsoft/WinAppDriver/tree/v1.2-RC) or [v1.2.1](https://github.com/microsoft/WinAppDriver/tree/v1.2.1) to be installed on Windows 11.

**Comment by Klarahov** [comment] 2023-12-19 06:48
Thanks for the hint @licanhua , you are actually right! I am running the Appium Windows driver and not WinAppDriver directly, and it seems like installing the Appium Windows driver installed an old WinAppDriver version on my machine (or I guess that's what happened). I read this now on the Appium Windows driver page
"Appium downloads and installs WinAppDriver package automatically upon executing its installation scripts, **although, the actual binary version could be out of date**. In such case you could download and install the most recent version of WinAppDriver manually from the [GitHub releases](https://github.com/microsoft/WinAppDriver/releases) page."

**Comment by licanhua** [comment] 2023-12-19 17:51
Possible the wrong appium windows driver is used or there is bug in it. You may debug this on file https://github.com/appium/appium-windows-driver/blob/master/lib/installer.js or raise this issue to their repo
