### ISSUE TITLE
Appium 5.0.0 - No swipe method detected

### ISSUE THREAD

**Issue by tlytvyn** [appium/appium#9095] opened 2017-08-28 12:05 UTC
There is no swipe method for AppiumDriver in 5.0.0 version ?

**Comment by mykola-mokhnach** [comment] 2017-08-28 13:14
It's by design. One has to use TouchActions interface instead. 
Closed as server unrelated.

**Closed by mykola-mokhnach** 2017-08-28 13:14 UTC

**Comment by tlytvyn** [comment] 2017-08-28 13:15
@mykola-mokhnach 
Can you provide swipe example using TouchActions? I didn't find any related up to date docs

**Comment by mykola-mokhnach** [comment] 2017-08-28 13:18
https://github.com/appium/sample-code/search?utf8=✓&q=touch
