### ISSUE TITLE
Not informative response to Curl requests "curl -N http://localhost:4723/wd/hub/status" to Appium

### ISSUE THREAD

**Issue by chibert** [appium/appium#8985] opened 2017-08-07 16:55 UTC
## The problem
During the running session on the Android device on the curl request:
`curl -N http://localhost:4723/wd/hub/status`
received the response:
{"status":0,"value":{"build":{"version":"1.6.5","revision":null}},"sessionId":null}

## Environment
* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: Mac OS 10.12.6 (16G29)
* Node.js version (unless using Appium.app|exe): v6.11.1
* Mobile platform/version under test: Android 4.4-6
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details
Previously used Appium version **1.4.13**. During the running session on the Android device on the request:
`curl -N http://localhost:4723/wd/hub/status`
received the response:
`{"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}},"sessionId":"29b3c645-a825-404a-aded-d3c97717abad"}`
Updated on the Appium **1.6.5**. Now the same request get the response:
`{"status":0,"value":{"build":{"version":"1.6.5","revision":null}},"sessionId":null}`
It does not matter is now going session or not!

First of all, I'm interested in knowing the sessionId. Or some other pointer to the fact that the test session is currently running.
Perhaps there are other CURL requests to the Appium server?

Sorry for bad english.
Thank you all in advance!

**Comment by imurchie** [comment] 2017-08-07 17:02
Interesting. Thanks for reporting. I'll look into what was changed.

**Comment by imurchie** [comment] 2017-08-07 17:32
This is by design. The call to get the status is not associated with any session, so there is no session id associated with it. The purpose of the function is to find out if the server is running, and its state.

We _could_ add a list of the running sessions.

**Comment by chibert** [comment] 2017-08-08 09:14
> We could add a list of the running sessions.

It would be great!
Thank you!

**Comment by imurchie** [comment] 2017-08-08 12:10
Thinking about this, I think it should be behind a server flag, since, as Appium becomes better-capable of handling multiple sessions concurrently, there could be multiple users, which means if you knew someone else's session id you could hijack their session.

**Comment by tfcardoso** [comment] 2017-08-14 17:24
I'm getting:

    {"status":0,"value":[{"id":"aaf24de2-d50c-4022-81ab-519d7fde887f","capabilities":{"app":"«my.ipa»","noReset":true,"newCommandTimeout":3600,"platformVersion":"10.3.3","xcodeOrgId":"«myID»","automationName":"XCUITest","platformName":"iOS","udid":"«myID»","deviceName":"iPhone5S","xcodeSigningId":"iPhone Developer","isFirstSession":true}}],"sessionId":null}

isn't the id the session-id?

**Comment by jlipps** [comment] 2017-08-29 22:32
calling `GET /sessions` will return a list of the sessions, which should fulfill the need of the OP. The call to /status according to the spec should only indicate the readiness of the server to accept new session requests. It shouldn't say anything about which sessions are running. Closing since I don't think there's need for any change here.

**Closed by jlipps** 2017-08-29 22:31 UTC
Labels: Enhancement
