### ISSUE TITLE
Invalid argument error in chromedriver

### ISSUE THREAD

**Issue by sasasa42** [appium/appium#13391] opened 2019-10-09 06:05 UTC
## The problem

After recently updating the appium, the execution stops while running on a real Android device in the Chrome webviews. 
## Environment

* Appium version : 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): 1.14.0
* Desktop OS/version used to run Appium: 10.14.6
* Node.js version (unless using Appium.app|exe): 12.11.1
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

When the webview is trying to be opened, an Invalid argument error appears. PFA the logs.

## Link to Appium logs

https://gist.github.com/sasasa42/004e29b0ec0f5c215c548ccfc9437a7e#file-gistfile1-txt

**Comment by mykola-mokhnach** [comment] 2019-10-09 06:18
Duplicate of https://github.com/appium/appium/issues/13306

**Closed by mykola-mokhnach** 2019-10-09 06:18 UTC

**Comment by sasasa42** [comment] 2019-10-18 07:20
Finally. it works as per the change commented in https://github.com/appium/appium/issues/13306
