### ISSUE TITLE
[iOS] Appium can't retrieve value of TextView after specific query

### ISSUE THREAD

**Issue by avrahams1** [appium/appium#13520] opened 2019-10-31 07:27 UTC
## The problem

When trying to retrieve value of TextView, one that's clearly set when using inspector, Appium returns null if the last query used to retrieve the element used xpath.

* I realize this may seem like a duplicate of https://github.com/appium/appium/issues/13477 and https://github.com/appium/appium/issues/13508, but I have additional details that narrow down the issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.14.2
* Desktop OS/version used to run Appium: macOS Mojave 10.14.5
* Node.js version (unless using Appium.app|exe): 10.9.0
* Npm or Yarn package manager: npm 16.12.0
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Capabilities used to create the session:

```
{
	"desiredCapabilities": {
	  "app": "path_to_app",
	  "automationName": "XCuiTest",
	  "deviceName": "iPhone X",
	  "platformName": "iOS",
	  "platformVersion": "12.2",
	  "appium.server": "http://0.0.0.0",
	  "appium.server.port": 4723,
	  "appium.server.url": "http://localhost:4723",
	  "connectHardwareKeyboard": false,
	  "noReset": true,
	  "showIOSLog": true,
	  "newCommandTimeout": 86400
	}
}
```

Element in question as viewed in Appium Inspector:
![image](https://user-images.githubusercontent.com/26322761/67927168-9a263a80-fbc0-11e9-82a5-8e2a266cc8c1.png)

**Step 1:**
Query for elements using XPath.
![Screen Shot 2019-10-31 at 09 13 25](https://user-images.githubusercontent.com/26322761/67926508-e3758a80-fbbe-11e9-88bc-5c8c88d44fe9.png)

**Step 2:**
Try retrieving value of queried element.
![image](https://user-images.githubusercontent.com/26322761/67926603-0c961b00-fbbf-11e9-9eac-d20e44cf8024.png)
As you can see, value is returned as null.

**Step 3:**
Query same element using classname. (notice: exact same element ID)
![Screen Shot 2019-10-31 at 09 16 59](https://user-images.githubusercontent.com/26322761/67926687-4cf59900-fbbf-11e9-86dd-21de385c5074.png)

**Step 4:**
Execute the exact same query for the TextView's value.
![image](https://user-images.githubusercontent.com/26322761/67926729-6d255800-fbbf-11e9-8e58-8b0a9db84558.png)
Value is returned correctly.

This reproduces consistently - if the queried element was returned in an XPath request, it's value seems to be null.

## Link to Appium logs

Logs of failed retrieval + the query preceding it:
https://gist.github.com/avrahams1/231495c89aac7645e6b12be379a21b6a

Logs of successful retrieval + the query preceding it:
https://gist.github.com/avrahams1/28352f76fa0a8c3485fedf5f5034ad16

## Code To Reproduce Issue [ Good To Have ]

I'm hope I provided enough details, please let me know if anything else is required.

**Comment by mykola-mokhnach** [comment] 2019-10-31 08:27
Duplicate of https://github.com/appium/appium/issues/13288

Consider using iOS 12 with Xcode10 SDK

**Closed by mykola-mokhnach** 2019-10-31 08:27 UTC

**Comment by mykola-mokhnach** [comment] 2019-10-31 08:30
Thanks for the additional details, but there is no good workaround for now we could implement in WDA code. PRs are welcome
