### ISSUE TITLE
appium command '/bin/bash scripts/bootstrap.sh -d' exited with code 1

### ISSUE THREAD

**Issue by amrutab** [appium/appium#7277] opened 2016-11-23 16:55 UTC
## The problem

When I try to run cucumber-js tests using appium on iPhone7 then i get the following error and it then closes the iPhone7 emulator opened by xcode

Error:- 
[XCUITest] Error: Command '/bin/bash scripts/bootstrap.sh -d' exited with code 1

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable):1.6.0
* Desktop OS/version used to run Appium: Mac iOS 10.1
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: 10.1
* Real device or emulator/simulator:iPhone 7 simulator
* Appium CLI or Appium.app|exe: Appium.app

**Comment by jlipps** [comment] 2016-11-23 16:57
Please create a gist of your full appium logs and link to them here.

**Comment by mykola-mokhnach** [comment] 2016-11-23 18:41
Duplicate of https://github.com/appium/appium/issues/7276

**Comment by amrutab** [comment] 2016-11-24 10:24
Thanks mykola-mokhnach. It is the same issue I am facing

**Closed** 2017-01-31 21:06 UTC
Labels: NeedsTriage
