### ISSUE TITLE
Instrument launching time out when app requires access permission

### ISSUE THREAD

**Issue by stevechun** [appium/appium#5113] opened 2015-05-12 23:13 UTC
If the app requires some access permission when first launched (i.e. location),
then the test doesn't get started and times out.
The app is launched successfully, and the permission alert is displayed.
If i tap 'Allow' button manually, Appium successfully starts the test.

This is happening often, but not always.

Appium Version: 1.3.7, 1.4.0
Simulator iOS Version: 8.3
noReset: false (this is required for my test)

Here is the Appium log:
```
warn: Instruments socket client never checked in; timing out (global)

info: [debug] Killall instruments

info: [debug] [INSTSERVER] Instruments exited with code null

info: [debug] Killall instruments
info: [debug] Instruments never checked in
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iOS Simulator
```
Retry happening but ends up getting tests not executed successfully.

**Comment by Jonahss** [comment] 2015-05-12 23:21
This is a duplicate of #4178 and a known bug in Apple Instruments. The workaround is to put a delay into your app before requiring the service which generates the alert.

**Closed by Jonahss** 2015-05-12 23:21 UTC
Labels: NeedsTriage
