### ISSUE TITLE
Error: stdout maxBuffer exceeded.

### ISSUE THREAD

**Issue by bagiro44** [appium/appium#3071] opened 2014-07-07 14:29 UTC
When I am setting up my app I get this error:
"Error: stdout maxBuffer exceeded."

Appium log:
error: Failed to start an Appium session, err was: Error: stdout maxBuffer exceeded.
debug: Error: stdout maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:688:13)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at Pipe.onread (net.js:528:21)
debug: Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: stdout maxBuffer exceeded.)","origValue":"stdout maxBuffer exceeded."},"sessionId":null}
info: <-- POST /wd/hub/session 500 9752.447 ms - 174 

Appium version 1.2

**Comment by Jonahss** [comment] 2015-04-14 22:40
Closing due to inactivity

**Comment by beemi** [comment] 2015-07-21 17:15
2015-07-21 18:14:25:659 - info: Welcome to Appium v1.4.0 (REV 8f63e2f91ef7907aed8bda763f4e5ca08e86970a)
2015-07-21 18:14:25:662 - info: Appium REST http interface listener started on 127.0.0.1:4723
2015-07-21 18:14:25:664 - info: [debug] Non-default server args: {"address":"127.0.0.1","noReset":true,"log":"/Users/rajb/Desktop/appium.log","logTimestamp":true,"localTimezone":true,"chromeDriverPort":9516,"defaultCommandTimeout":90,"debugLogSpacing":true}
2015-07-21 18:14:25:665 - info: Console LogLevel: debug
2015-07-21 18:14:25:665 - info: File LogLevel: debug
2015-07-21 18:14:34:232 - info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"Chrome","androidDeviceReadyTimeout":"30","platformVersion":"Android","browserName":"Chrome","chromeOptions":{"args":["disable-translate","disable-popup-blocking","disable-save-password-bubble","enable-automatic-password-saving"],"extensions":[]},"platformName":"Android","deviceName":"Rajgalaxy","enablePerformanceLogging":"true"}}
2015-07-21 18:14:34:234 - info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
2015-07-21 18:14:34:235 - info: *************************************
2015-07-21 18:14:34:235 - info: *************************************
2015-07-21 18:14:34:236 - info: *************************************
2015-07-21 18:14:34:236 - info: *************************************
2015-07-21 18:14:34:237 - info: *************************************
2015-07-21 18:14:34:237 - info: *************************************
2015-07-21 18:14:34:237 - info: *************************************
2015-07-21 18:14:34:238 - info: *************************************
2015-07-21 18:14:34:238 - info: ****        NEW SESSION           ***
2015-07-21 18:14:34:238 - info: ****        NEW SESSION           ***
2015-07-21 18:14:34:239 - info: ****        NEW SESSION           ***
2015-07-21 18:14:34:239 - info: ****        NEW SESSION           ***
2015-07-21 18:14:34:240 - info: ****        NEW SESSION           ***
2015-07-21 18:14:34:240 - info: ****        NEW SESSION           ***
2015-07-21 18:14:34:241 - info: ****        NEW SESSION           ***
2015-07-21 18:14:34:241 - info: ****        NEW SESSION           ***
2015-07-21 18:14:34:241 - info: *************************************
2015-07-21 18:14:34:241 - info: *************************************
2015-07-21 18:14:34:242 - info: *************************************
2015-07-21 18:14:34:242 - info: *************************************
2015-07-21 18:14:34:242 - info: *************************************
2015-07-21 18:14:34:242 - info: *************************************
2015-07-21 18:14:34:243 - info: *************************************
2015-07-21 18:14:34:243 - info: *************************************
2015-07-21 18:14:34:244 - warn: Converting cap enablePerformanceLogging from string to boolean. This might cause unexpected behavior.
2015-07-21 18:14:34:245 - info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : androidDeviceReadyTimeout, chromeOptions
2015-07-21 18:14:34:246 - info: Set mode: Proxying straight through to Chromedriver
2015-07-21 18:14:34:247 - info: [debug] Looks like we want chrome on android
2015-07-21 18:14:34:248 - info: [debug] Creating new appium session 1088afcd-0843-4baf-a576-628a2fbf3bef
2015-07-21 18:14:34:249 - info: [debug] Checking whether adb is present
2015-07-21 18:14:34:251 - info: [debug] Using adb from C:\androidSdk\platform-tools\adb.exe
2015-07-21 18:14:34:251 - info: [debug] Using fast reset? false
2015-07-21 18:14:34:252 - info: [debug] Preparing device for session
2015-07-21 18:14:34:253 - info: [debug] Not checking whether app is present since we are assuming it's already on the device
2015-07-21 18:14:34:253 - info: Retrieving device
2015-07-21 18:14:34:254 - info: [debug] Trying to find a connected android device
2015-07-21 18:14:34:254 - info: [debug] Getting connected devices...
2015-07-21 18:14:34:256 - info: [debug] executing cmd: C:\androidSdk\platform-tools\adb.exe devices
2015-07-21 18:14:34:305 - info: [debug] 1 device(s) connected
2015-07-21 18:14:34:306 - info: Found device 8f5a31e7
2015-07-21 18:14:34:307 - info: [debug] Setting device id to 8f5a31e7
2015-07-21 18:14:34:307 - info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 30)
2015-07-21 18:14:34:309 - info: [debug] executing cmd: C:\androidSdk\platform-tools\adb.exe -s 8f5a31e7 wait-for-device
2015-07-21 18:14:34:473 - info: [debug] executing cmd: C:\androidSdk\platform-tools\adb.exe -s 8f5a31e7 shell "echo 'ready'"
2015-07-21 18:14:34:571 - info: [debug] Starting logcat capture
2015-07-21 18:14:34:761 - info: [debug] Set chromedriver binary as: C:\Program Files (x86)\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
2015-07-21 18:14:34:761 - info: Set chromedriver binary as: C:\Program Files (x86)\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
2015-07-21 18:14:34:762 - info: [debug] Pushing unlock helper app to device...
2015-07-21 18:14:34:764 - info: [debug] executing cmd: C:\androidSdk\platform-tools\adb.exe -s 8f5a31e7 install "C:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
2015-07-21 18:14:38:200 - info: [debug] executing cmd: C:\androidSdk\platform-tools\adb.exe -s 8f5a31e7 shell "dumpsys window"
2015-07-21 18:14:38:776 - info: [debug] Cleaning up appium session
2015-07-21 18:14:38:778 - error: Failed to start an Appium session, err was: Error: stdout maxBuffer exceeded.
2015-07-21 18:14:38:783 - info: [debug] Error: stdout maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:792:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)
2015-07-21 18:14:38:785 - info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: stdout maxBuffer exceeded.)","cmd":"C:\\windows\\system32\\cmd.exe /s /c \"C:\\androidSdk\\platform-tools\\adb.exe -s 8f5a31e7 shell \"dumpsys window\"\"","origValue":"stdout maxBuffer exceeded."},"sessionId":null}
2015-07-21 18:14:38:797 - info: <-- POST /wd/hub/session 500 4564.377 ms - 300

**Comment by beemi** [comment] 2015-07-21 17:16
{"message":"A new session could not be created. (Original error: stdout maxBuffer

**Comment by Jonahss** [comment] 2015-07-23 18:41
Oh hello.
Can you switch to the latest version of appium (1.4.8) and see if the issue persists?

**Comment by beemi** [comment] 2015-07-23 19:20
Hey jonahss, 
i am using window , is there v1.4.8 available ?  
https://bitbucket.org/appium/appium.app/downloads/

**Comment by Jonahss** [comment] 2015-07-23 19:45
Ohh. Will have to wait for that release then. Or you can install yourself using npm.

**Comment by beemi** [comment] 2015-07-23 20:39
Jonahss , i did run the latest version by using node ,still i got the Error

2015-07-23 21:37:12:360 - info: Welcome to Appium v1.4.8 (REV c8179bd8352d3c62d98fa58b324491230df9342a)
2015-07-23 21:37:12:362 - info: Appium REST http interface listener started on 0.0.0.0:4723
2015-07-23 21:37:12:365 - info: [debug] Non-default server args: {"sessionOverride":true,"noReset":true,"log":"/Users/rajb/Desktop/appium.log","logTimestamp":true,"localTimezone":true,"chromeDriverPort":9516,"defaultCommandTimeout":90,"debugLogSpacing":true}
2015-07-23 21:37:12:365 - info: Console LogLevel: debug
2015-07-23 21:37:12:366 - info: File LogLevel: debug
2015-07-23 21:37:26:500 - info: --> POST /wd/hub/session {"desiredCapabilities":{"appPackage":"com.android.chrome","appActivity":".MainActivity","newCommandTimeout":"60","platformVersion":"5.0.1","automationName":"Selendroid","appWaitActivity":"SplashActivity","browserName":"Chrome","platformName":"Android","deviceName":"Rajgalaxy","selendroidPort":"8080","deviceReadyTimeout":"5"}}
2015-07-23 21:37:26:504 - info: Client User-Agent string: Apache-HttpClient/4.4.1 (Java/1.8.0_45)
2015-07-23 21:37:26:505 - info: *************************************
2015-07-23 21:37:26:505 - info: *************************************
2015-07-23 21:37:26:506 - info: *************************************
2015-07-23 21:37:26:507 - info: *************************************
2015-07-23 21:37:26:508 - info: *************************************
2015-07-23 21:37:26:509 - info: *************************************
2015-07-23 21:37:26:509 - info: *************************************
2015-07-23 21:37:26:509 - info: *************************************
2015-07-23 21:37:26:510 - info: ****        NEW SESSION           ***
2015-07-23 21:37:26:510 - info: ****        NEW SESSION           ***
2015-07-23 21:37:26:512 - info: ****        NEW SESSION           ***
2015-07-23 21:37:26:515 - info: ****        NEW SESSION           ***
2015-07-23 21:37:26:516 - info: ****        NEW SESSION           ***
2015-07-23 21:37:26:516 - info: ****        NEW SESSION           ***
2015-07-23 21:37:26:517 - info: ****        NEW SESSION           ***
2015-07-23 21:37:26:517 - info: ****        NEW SESSION           ***
2015-07-23 21:37:26:517 - info: *************************************
2015-07-23 21:37:26:518 - info: *************************************
2015-07-23 21:37:26:518 - info: *************************************
2015-07-23 21:37:26:519 - info: *************************************
2015-07-23 21:37:26:519 - info: *************************************
2015-07-23 21:37:26:519 - info: *************************************
2015-07-23 21:37:26:520 - info: *************************************
2015-07-23 21:37:26:522 - info: *************************************
2015-07-23 21:37:26:525 - info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : selendroidPort
2015-07-23 21:37:26:526 - info: Set mode: Proxying straight through to Chromedriver
2015-07-23 21:37:26:527 - info: [debug] Looks like we want chrome on android
2015-07-23 21:37:26:528 - info: [debug] Creating new appium session 1a2924c6-554c-46d1-b395-fdadf85f0c8e
2015-07-23 21:37:26:531 - info: [debug] Checking whether adb is present
2015-07-23 21:37:26:533 - info: [debug] Using adb from C:\androidSdk\platform-tools\adb.exe
2015-07-23 21:37:26:536 - info: [debug] Using fast reset? false
2015-07-23 21:37:26:543 - info: [debug] Preparing device for session
2015-07-23 21:37:26:544 - info: [debug] Not checking whether app is present since we are assuming it's already on the device
2015-07-23 21:37:26:548 - info: Retrieving device
2015-07-23 21:37:26:552 - info: [debug] Trying to find a connected android device
2015-07-23 21:37:26:572 - info: [debug] Getting connected devices...
2015-07-23 21:37:26:580 - info: [debug] executing cmd: C:\androidSdk\platform-tools\adb.exe devices
2015-07-23 21:37:26:655 - info: [debug] 1 device(s) connected
2015-07-23 21:37:26:656 - info: Found device 8f5a31e7
2015-07-23 21:37:26:660 - info: [debug] Setting device id to 8f5a31e7
2015-07-23 21:37:26:662 - info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
2015-07-23 21:37:26:665 - info: [debug] executing cmd: C:\androidSdk\platform-tools\adb.exe -s 8f5a31e7 wait-for-device
2015-07-23 21:37:26:727 - info: [debug] executing cmd: C:\androidSdk\platform-tools\adb.exe -s 8f5a31e7 shell "echo 'ready'"
2015-07-23 21:37:26:905 - info: [debug] Starting logcat capture
2015-07-23 21:37:27:071 - info: [debug] Pushing unlock helper app to device...
2015-07-23 21:37:27:076 - info: [debug] executing cmd: C:\androidSdk\platform-tools\adb.exe -s 8f5a31e7 install "C:\Users\rajb\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
2015-07-23 21:37:30:076 - info: [debug] executing cmd: C:\androidSdk\platform-tools\adb.exe -s 8f5a31e7 shell "dumpsys window"
2015-07-23 21:37:30:744 - info: [debug] Cleaning up appium session
2015-07-23 21:37:30:750 - error: Failed to start an Appium session, err was: Error: stdout maxBuffer exceeded.
2015-07-23 21:37:30:759 - info: [debug] Error: stdout maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:792:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)
2015-07-23 21:37:30:761 - info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: stdout maxBuffer exceeded.)","cmd":"C:\\windows\\system32\\cmd.exe /s /c \"C:\\androidSdk\\platform-tools\\adb.exe -s 8f5a31e7 shell \"dumpsys window\"\"","origValue":"stdout maxBuffer exceeded."},"sessionId":null}
2015-07-23 21:37:30:774 - info: <-- POST /wd/hub/session 500 4271.982 ms - 300

**Comment by beemi** [comment] 2015-07-24 14:59
Restart my device , issue not occured so far 
Thank you

**Comment by Jonahss** [comment] 2015-07-24 17:27
Any reason why you are using the "Selendroid" automation? You should remove that desired capability unless you want to be using Selendroid.

**Comment by SrinivasanTarget** [comment] 2016-03-08 17:50
@scottdixon We can close this issue.I didn't see any such issues on Appium 1.5 with android and iOS

**Comment by scottdixon** [comment] 2016-03-08 17:54
Good to know. Thanks

**Closed by scottdixon** 2016-03-08 17:54 UTC
