### ISSUE TITLE
Error getting screenshot: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up

### ISSUE THREAD

**Issue by udaykittu** [appium/appium#15262] opened 2021-04-08 07:34 UTC
## The problem
Socket hung up error occurs all of sudden when the Automation Tests are getting executed.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Desktop OS/version used to run Appium: MAC OS - BigSur 11.2.3 & MAC OS - Catalina 10.15.7
* Node.js version (unless using Appium.app|exe): v15.12.0
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iOS 14.4.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI & Appium.app

## Details

We are facing the above issue while running the Automation Tests continuously on single device for hours.
the same method where failure occurred has been passed for the continuous 10-12 hours of execution

## Link to Appium logs

https://gist.github.com/udaykittu/e067eac89165f7f3179c6635ae5f14cc

**Comment by mykola-mokhnach** [comment] 2021-04-08 07:49
Duplicate of https://github.com/appium/appium/issues/15199

Kindly use search feature to avoid creating multiple duplicates of the same issue

**Closed by mykola-mokhnach** 2021-04-08 07:49 UTC

**Comment by udaykittu** [comment] 2021-04-15 10:18
@mykola-mokhnach , Issue Still seen on 1.21.0-beta.0 version of appium

Restarted the machine, Deleted webdriveragent from ios devices, restarted devices and started execution

Xcode 12.4
Mac OS - Big Sur

Appium Logs
https://gist.github.com/udaykittu/396c1b07d9813457ba53edebbf5afe2a

**Comment by 1451297455** [comment] 2021-05-13 09:26
@mykola-mokhnach  how to fix it? I tried it on three Macs , got the same Error.

**Comment by IlyassABALI** [comment] 2021-05-18 15:19
Hello, please I have the same problem. How can I fix it. 

Xcode14.5, IOS 14.5 - [XCUIScreen screenshotDataForQuality:rect:error:] #15309
 Closed

**Comment by 1451297455** [comment] 2021-05-19 01:04
update to appium desktop 1.21.0

**Comment by IlyassABALI** [comment] 2021-05-19 14:38
I Updated Appium but still not working :(

**Comment by greyreality** [comment] 2021-06-01 06:19
> I Updated Appium but still not working :(

i updated cmd appium
`npm uninstall -g appium && npm install -g appium@1.21.0`
and  upgraded desktop appium, 
rebuild  both projects in xCode
`cd /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent`
`cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent`

and installed  my app by desktop and tests with appium option
clearSystemFiles=true

after several runs it worked on iphone with ios 12.2 and 14.4
