### ISSUE TITLE
【IOS real Devices】Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running."  

### ISSUE THREAD

**Issue by a67c** [appium/appium#10289] opened 2018-03-02 07:51 UTC
## The problem

when i excute test，if the previous  test exit because of some problems，and appium-python-client not send deleteSession， next I want to restart this test ，and sometimes the wda  can't lanuch successfully

## Environment

* Appium version ：1.7.2
* Desktop OS/version used to run Appium:none
* Node.js version (unless using Appium.app|exe):8.9.1
* Mobile platform/version under test:IOS
* Real device
*Xcodebuild:9.2

## Details
if open the xcodebuild and run WebDriverAgentRunner  and  resart test  is ok,or  restart the device and test the case again is successfully。

so I want to consult appium-python-client quitWdaSession faild，the next wda launched  maybe failed?

thank you！

## Link to Appium logs

[Xcode] === BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[Xcode] 
[Xcode] 
[Xcode] Check dependencies
[Xcode] Code Signing Error: "WebDriverAgentRunner" requires a provisioning profile. Select a provisioning profile for the "Debug" build configuration in the project editor.
[Xcode] Code Signing Error: Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.2'
[Xcode] 
[Xcode] Code Signing Error: "WebDriverAgentRunner" requires a provisioning profile. Select a provisioning profile for the "Debug" build configuration in the project editor.
[Xcode] Code Signing Error: Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.2'
[Xcode] Code Signing Error: "WebDriverAgentRunner" requires a provisioning profile. Select a provisioning profile for the "Debug" build configuration in the project editor.
[Xcode] 
[Xcode] Code Signing Error: Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.2'
[Xcode] 
[Xcode] Code Signing Error: "WebDriverAgentRunner" requires a provisioning profile. Select a provisioning profile for the "Debug" build configuration in the project editor.
[Xcode] Code Signing Error: Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.2'
[Xcode] Code Signing Error: Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.2'
[Xcode] Code Signing Error: Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.2'
[Xcode] 
[Xcode] 
[Xcode] ** TEST BUILD FAILED **
[Xcode] 
[Xcode] 
[Xcode] The following build commands failed:
[Xcode] 	Check dependencies
[Xcode] (1 failure)
[Xcode] 
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/_b/h8cxgjtd6h9f4kkz6st6sph80000gn/T/com.apple.dt.XCTest/IDETestRunSession-D6B6EC5C-33F9-490B-898F-DA6B958ECF4B/WebDriverAgentRunner-A2EF698D-AC72-4B38-80D9-BCCBBBE747D7/Session-WebDriverAgentRunner-2018-03-02_151827-DdjgoS.log
[Xcode] 2018-03-02 15:18:27.881 xcodebuild[29166:5317400]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[Xcode] /var/folders/_b/h8cxgjtd6h9f4kkz6st6sph80000gn/T/com.apple.dt.XCTest/IDETestRunSession-D6B6EC5C-33F9-490B-898F-DA6B958ECF4B/WebDriverAgentRunner-A2EF698D-AC72-4B38-80D9-BCCBBBE747D7/Session-WebDriverAgentRunner-2018-03-02_151827-DdjgoS.log
[Xcode] 2018-03-02 15:18:27.881 xcodebuild[29166:5317297] [MT] IDETestOperationsObserverDebug: (F1C19D65-06DD-41A1-B889-02C76403BC8E) Beginning test session WebDriverAgentRunner-F1C19D65-06DD-41A1-B889-02C76403BC8E at 2018-03-02 15:18:27.881 with Xcode 9C40b on target <DVTiOSDevice: 0x7faaabb06fa0> {
[Xcode] 		deviceSerialNumber:         F2LJTC1GF8H6
[Xcode] 		identifier:                 cec770baeb3180fa66b95f88f3535f18ddfbf6c3
[Xcode] 		deviceClass:                iPhone
[Xcode] 		deviceName:                 iPhone5 slave15
[Xcode] 		deviceIdentifier:           cec770baeb3180fa66b95f88f3535f18ddfbf6c3
[Xcode] 		productVersion:             9.3.2
[Xcode] 		buildVersion:               13F69
[Xcode] 		deviceSoftwareVersion:      9.3.2 (13F69)
[Xcode] 		deviceArchitecture:         armv7s
[Xcode] 		deviceTotalCapacity:        29077270528
[Xcode] 		deviceAvailableCapacity:    25744236544
[Xcode] 		deviceIsTransient:          NO
[Xcode] 		ignored:                    NO
[Xcode] 		deviceIsBusy:               NO
[Xcode] 		deviceIsActivated:          YES
[Xcode] 		deviceActivationState:      Activated
[Xcode] 		isPasscodeLocked:           NO
[Xcode] 		deviceType:                 <DVTDeviceType:0x7faaab5ec0e0 Xcode.DeviceType.iPhone>
[Xcode] 		supportedDeviceFamilies:    (
[Xcode]     1
[Xcode] )
[Xcode] 		applications:              (null)
[Xcode] 		provisioningProfiles:      (null)
[Xcode] 		hasInternalSupport:        NO
[Xcode] 		isSupportedOS:             YES
[Xcode] 		developerDiskMountError:   (null)
[Xcode] (null)
[Xcode] 	bootArgs:                  <unavailable>
[Xcode] 		connected:                 yes
[Xcode] 		isWirelessEnabled:         no
[Xcode] 		connectionType:            direct
[Xcode] 		} (9.3.2 (13F69))
[Xcode] 
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[Xcode] writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/_b/h8cxgjtd6h9f4kkz6st6sph80000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/e37540b9b4e096d93617db143c63ec30/cec770baeb3180fa66b95f88f3535f18ddfbf6c3/ManifestCache.plist
[Xcode] 
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8300/status] with no body
[Xcode] 2018-03-02 15:18:35.795 xcodebuild[29166:5317302]  DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.WebDriverAgentRunner-Runner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running." UserInfo={NSLocalizedDescription=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(
[Xcode] 	0   DTDeviceKitBase                     0x0000000110d1afed DTDKCreateNSError + 113
[Xcode] 	1   DTDeviceKitBase                     0x0000000110d1b831 DTDK_AMDErrorToNSError + 1135
[Xcode] 	2   DTDeviceKitBase                     0x0000000110d2d685 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 98
[Xcode] 	3   DTDeviceKitBase                     0x0000000110d2c521 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
[Xcode] 	4   DTDeviceKitBase                     0x0000000110d1d815 __DTDKExecuteInSession_block_invoke_2 + 35
[Xcode] 	5   DTDeviceKitBase                     0x0000000110d1cc1f __DTDKExecuteWithConnection_block_invoke_2 + 474
[Xcode] 	6   DTDeviceKitBase                     0x0000000110d1ca1a __DTDKExecuteWithConnection_block_invoke + 111
[Xcode] 	7   libdispatch.dylib                   0x00007fff5883ae88 _dispatch_client_callout + 8
[Xcode] 	8   libdispatch.dylib                   0x00007fff5884e31d _dispatch_queue_barrier_sync_invoke_and_complete + 60
[Xcode] 	9   DVTFoundation                       0x0000000105b886f0 DVTDispatchBarrierSync + 213
[Xcode] 	10  DVTFoundation                       0x0000000105b61c7a -[DVTDispatchLock performLockedBlock:] + 75
[Xcode] 	11  DTDeviceKitBase                     0x0000000110d1c915 DTDKExecuteWithConnection + 231
[Xcode] 	12  DTDeviceKitBase                     0x0000000110d1d681 DTDKExecuteInSession + 381
[Xcode] 	13  DTDeviceKitBase                     0x0000000110d2c458 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 119
[Xcode] 	14  DVTFoundation                       0x0000000105b87a4f __DVTDispatchAsync_block_invoke + 806
[Xcode] 	15  libdispatch.dylib                   0x00007fff588426cd _dispatch_call_block_and_release + 12
[Xcode] 	16  libdispatch.dylib                   0x00007fff5883ae88 _dispatch_client_callout + 8
[Xcode] 	17  libdispatch.dylib                   0x00007fff5884f356 _dispatch_queue_serial_drain + 635
[Xcode] 	18  libdispatch.dylib                   0x00007fff58842239 _dispatch_queue_invoke + 373
[Xcode] 	19  libdispatch.dylib                   0x00007fff58850042 _dispatch_root_queue_drain_deferred_wlh + 332
[Xcode] 	20  libdispatch.dylib                   0x00007fff58853e1b _dispatch_workloop_worker_thread + 880
[Xcode] 	21  libsystem_pthread.dylib             0x00007fff58afe033 _pthread_wqthread + 980
[Xcode] 	22  libsystem_pthread.dylib             0x00007fff58afdc4d start_wqthread + 13
[Xcode] ), NSLocalizedRecoverySuggestion=Too many instances of this service are already running., NSLocalizedFailureReason=Too many instances of this service are already running.}]
[Xcode] 
[Xcode] 2018-03-02 15:18:35.795 xcodebuild[29166:5317958]  iPhoneConnect: Error uploading test configuration to app container: Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running." UserInfo={NSLocalizedDescription=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(
[Xcode] 	0   DTDeviceKitBase                     0x0000000110d1afed DTDKCreateNSError + 113
[Xcode] 	1   DTDeviceKitBase                     0x0000000110d1b831 DTDK_AMDErrorToNSError + 1135
[Xcode] 	2   DTDeviceKitBase                     0x0000000110d2d685 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 98
[Xcode] 	3   DTDeviceKitBase                     0x0000000110d2c521 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
[Xcode] 	4   DTDeviceKitBase                     0x0000000110d1d815 __DTDKExecuteInSession_block_invoke_2 + 35
[Xcode] 	5   DTDeviceKitBase                     0x0000000110d1cc1f __DTDKExecuteWithConnection_block_invoke_2 + 474
[Xcode] 	6   DTDeviceKitBase                     0x0000000110d1ca1a __DTDKExecuteWithConnection_block_invoke + 111
[Xcode] 	7   libdispatch.dylib                   0x00007fff5883ae88 _dispatch_client_callout + 8
[Xcode] 	8   libdispatch.dylib                   0x00007fff5884e31d _dispatch_queue_barrier_sync_invoke_and_complete + 60
[Xcode] 	9   DVTFoundation                       0x0000000105b886f0 DVTDispatchBarrierSync + 213
[Xcode] 	10  DVTFoundation                       0x0000000105b61c7a -[DVTDispatchLock performLockedBlock:] + 75
[Xcode] 	11  DTDeviceKitBase                     0x0000000110d1c915 DTDKExecuteWithConnection + 231
[Xcode] 	12  DTDeviceKitBase                     0x0000000110d1d681 DTDKExecuteInSession + 381
[Xcode] 	13  DTDeviceKitBase                     0x0000000110d2c458 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 119
[Xcode] 	14  DVTFoundation                       0x0000000105b87a4f __DVTDispatchAsync_block_invoke + 806
[Xcode] 	15  libdispatch.dylib                   0x00007fff588426cd _dispatch_call_block_and_release + 12
[Xcode] 	16  libdispatch.dylib                   0x00007fff5883ae88 _dispatch_client_callout + 8
[Xcode] 	17  libdispatch.dylib                   0x00007fff5884f356 _dispatch_queue_serial_drain + 635
[Xcode] 	18  libdispatch.dylib                   0x00007fff58842239 _dispatch_queue_invoke + 373
[Xcode] 	19  libdispatch.dylib                   0x00007fff58850042 _dispatch_root_queue_drain_deferred_wlh + 332
[Xcode] 	20  libdispatch.dylib                   0x00007fff58853e1b _dispatch_workloop_worker_thread + 880
[Xcode] 	21  libsystem_pthread.dylib             0x00007fff58afe033 _pthread_wqthread + 980
[Xcode] 	22  libsystem_pthread.dylib             0x00007fff58afdc4d start_wqthread + 13
[Xcode] ), NSLocalizedRecoverySuggestion=Too many instances of this service are already running., NSLocalizedFailureReason=Too many instances of this service are already running.}
[Xcode] 
[Xcode] 2018-03-02 15:18:35.804 xcodebuild[29166:5317297] Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running." UserInfo={NSLocalizedDescription=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(
[Xcode] 	0   DTDeviceKitBase                     0x0000000110d1afed DTDKCreateNSError + 113
[Xcode] 	1   DTDeviceKitBase                     0x0000000110d1b831 DTDK_AMDErrorToNSError + 1135
[Xcode] 	2   DTDeviceKitBase                     0x0000000110d2d685 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 98
[Xcode] 	3   DTDeviceKitBase                     0x0000000110d2c521 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
[Xcode] 	4   DTDeviceKitBase                     0x0000000110d1d815 __DTDKExecuteInSession_block_invoke_2 + 35
[Xcode] 	5   DTDeviceKitBase                     0x0000000110d1cc1f __DTDKExecuteWithConnection_block_invoke_2 + 474
[Xcode] 	6   DTDeviceKitBase                     0x0000000110d1ca1a __DTDKExecuteWithConnection_block_invoke + 111
[Xcode] 	7   libdispatch.dylib                   0x00007fff5883ae88 _dispatch_client_callout + 8
[Xcode] 	8   libdispatch.dylib                   0x00007fff5884e31d _dispatch_queue_barrier_sync_invoke_and_complete + 60
[Xcode] 	9   DVTFoundation                       0x0000000105b886f0 DVTDispatchBarrierSync + 213
[Xcode] 	10  DVTFoundation                       0x0000000105b61c7a -[DVTDispatchLock performLockedBlock:] + 75
[Xcode] 	11  DTDeviceKitBase                     0x0000000110d1c915 DTDKExecuteWithConnection + 231
[Xcode] 	12  DTDeviceKitBase                     0x0000000110d1d681 DTDKExecuteInSession + 381
[Xcode] 	13  DTDeviceKitBase                     0x0000000110d2c458 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 119
[Xcode] 	14  DVTFoundation                       0x0000000105b87a4f __DVTDispatchAsync_block_invoke + 806
[Xcode] 	15  libdispatch.dylib                   0x00007fff588426cd _dispatch_call_block_and_release + 12
[Xcode] 	16  libdispatch.dylib                   0x00007fff5883ae88 _dispatch_client_callout + 8
[Xcode] 	17  libdispatch.dylib                   0x00007fff5884f356 _dispatch_queue_serial_drain + 635
[Xcode] 	18  libdispatch.dylib                   0x00007fff58842239 _dispatch_queue_invoke + 373
[Xcode] 	19  libdispatch.dylib                   0x00007fff58850042 _dispatch_root_queue_drain_deferred_wlh + 332
[Xcode] 	20  libdispatch.dylib                   0x00007fff58853e1b _dispatch_workloop_worker_thread + 880
[Xcode] 	21  libsystem_pthread.dylib             0x00007fff58afe033 _pthread_wqthread + 980
[Xcode] 	22  libsystem_pthread.dylib             0x00007fff58afdc4d start_wqthread + 13
[Xcode] ), NSLocalizedRecoverySuggestion=Too many instances of this service are already running., NSLocalizedFailureReason=Too many instances of this service are already running.}
[Xcode] 
[Xcode] 2018-03-02 15:18:35.804 xcodebuild[29166:5317297] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'

## Code To Reproduce Issue [ Good To Have ]

https://github.com/facebook/WebDriverAgent/issues/355

**Comment by mykola-mokhnach** [comment] 2018-03-02 10:58
Duplicate of https://github.com/facebook/WebDriverAgent/issues/507

**Closed by mykola-mokhnach** 2018-03-02 10:58 UTC
