### ISSUE TITLE
Not able to create session in latest Appium version 1.17.0

### ISSUE THREAD

**Issue by apiautoamtion** [appium/appium#14244] opened 2020-04-28 17:43 UTC
## The problem

Not able to create session in latest Appium version 1.17.0

2020-04-28 13:41:43.317434-0400 WebDriverAgentRunner-Runner[56884:1746806] Enqueue Failure: Application '<XCUIApplicationImpl: 0x28251e7f0 >' failed to activate (current state: Not Running) /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 38 1
    t =  1137.83s         Wait for accessibility to load
    t =  1197.86s         Wait for  to idle
2020-04-28 13:42:44.388221-0400 WebDriverAgentRunner-Runner[56884:1746806] Enqueue Failure: Application '' has not loaded accessibility /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 38 1
2020-04-28 13:42:49.405380-0400 WebDriverAgentRunner-Runner[56884:1746806] The application ' is not running in foreground after 5.00 seconds
    t =  1204.95s Open 
    t =  1204.96s     Launch 
## Environment

* Appium version (or git revision) that exhibits the issue:1.17.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:1.12.4
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2020-04-28 17:46
> Enqueue Failure: Application '' has not loaded accessibility 

This is the error reported by XCTest. Nothing we can do on Appium side.

**Comment by apiautoamtion** [comment] 2020-04-28 17:58
Nothing we can do in the sense ?

it was working for old version, why not with new version

**Comment by apiautoamtion** [comment] 2020-04-28 18:00
So far i didn't get any proper support from Appium, when ever there is a issue will change label and ignore 

it's impacting on Appium reputation

**Comment by apiautoamtion** [comment] 2020-04-28 18:07
Whenever Appium release a new version, need to make sure compatible dependencies should work otherwise it wont make any sense to release new versions 


can u assign this to some one else? who can guide me properly

**Comment by apiautoamtion** [comment] 2020-04-28 18:43
2020-04-28 14:42:10.346395-0400 WebDriverAgentRunner-Runner[66447:2091330] Enqueue Failure: Failed to launch c: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.) /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 38 1
[Xcode]

**Comment by apiautoamtion** [comment] 2020-04-28 18:44
Relevant issue :https://github.com/facebookarchive/WebDriverAgent/issues/1013

**Comment by mykola-mokhnach** [comment] 2020-04-28 19:13
> Whenever Appium release a new version, need to make sure compatible dependencies should work otherwise it wont make any sense to release new versions
> can u assign this to some one else? who can guide me properly

Unfortunately it does not work like that. All people here are volunteers and doing their best to keep the project in a good shape. The project source is open to anyone and we are happy to accept pull requests and support committers. 

For immediate support consider hiring a consultant.

**Comment by apiautoamtion** [comment] 2020-04-28 19:21
Thanks mykola.

Now I downgrade only Appium to 16 rest all up to date, still facing the same issue it's a blocker for my execution :(

it was working before the upgrade to 17

2020-04-28 15:18:06.173636-0400 WebDriverAgentRunner-Runner[66545:2155678] Enqueue Failure: Failed to launch : The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 38 1

**Comment by KazuCocoa** [comment] 2020-04-29 08:26
You can try below step:

1. Launch XCTest with `autoLaunch: false`
2. http://appium.io/docs/en/commands/device/app/activate-app/ the app
    - install https://appium.io/docs/en/commands/device/app/install-app/

If this case also did not work for you, the root cause is probably in 
https://developer.apple.com/documentation/xctest/xcuiapplication/2873317-activate?language=objc


BTW, Appium's launching app logic depends on https://developer.apple.com/documentation/xctest/xcuiapplication/1500467-launch?language=objc
https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/FBApplication.m#L159

**Comment by shibupanda** [comment] 2020-04-29 20:46
Yes I agree with the solution provided by @KazuCocoa it helped many folks. 
Even I suggest below capability as well and it worked like charm for them.
waitForQuiescence = false

**Comment by apiautoamtion** [comment] 2020-04-30 17:38
Thanks for the response mykola and shibupanda.

I upgrade to Xcode 11.3.1, am able to solve it with out any changes .

@will try your suggestion other nodes .

**Comment by mykola-mokhnach** [comment] 2020-04-30 17:46
Closed as third party issue

**Closed by mykola-mokhnach** 2020-04-30 17:46 UTC
Labels: ThirdParty, XCUITest

**Comment by apiautoamtion** [comment] 2020-04-30 17:56
cap.setCapability("waitForQuiescence" , false);

do I need to use cap like this ?

if yes not able to create session with this
