### ISSUE TITLE
Appium not finding elements inside tableview (ios)

### ISSUE THREAD

**Issue by Sureshkumar5694** [appium/appium#8813] opened 2017-07-10 12:00 UTC
## The problem
 
   
 I have the table view header cell whose  accessibility is set to true. 
but still appium not finding the elements inside the header cell. 
Header cell has two text label and an imageview

**Comment by mykola-mokhnach** [comment] 2017-07-10 13:31
Closed as duplicate of https://github.com/appium/appium/issues/6517

**Closed by mykola-mokhnach** 2017-07-10 13:31 UTC
