### ISSUE TITLE
Appium does not see the UITableView subviews.

### ISSUE THREAD

**Issue by Sergey6233** [appium/appium#11909] opened 2018-12-27 09:02 UTC
## The problem

Appium does not see the UITableView subviews.

## Environment

* Appium version: 1.9.1
* Desktop OS/version used to run Appium: macOS Mojave 10.14.2
* Mobile platform/version under test: iOS Simulator 10.1

## Details

I'm testing the elements in the table. Cells and their subviews are available. But when I add a UIView to a UITableView, you can't access its elements from Appium (Accessibility Inspector doesn't see its elements too). Please tell me how I can solve this problem.

## Link to Appium logs

https://gist.github.com/Sergey6233/70ef5c6bfdd3b659f7b1f9fa344156be

## Screenshots

https://drive.google.com/open?id=1oJQu_PjmOCTpxdWpwmBkeyw2SFdqErSD

## Code To Reproduce Issue. Demo Project

https://github.com/Sergey6233/AppiumDemo

**Comment by mykola-mokhnach** [comment] 2018-12-27 09:56
Duplicate of https://github.com/appium/appium/issues/6517

**Closed by mykola-mokhnach** 2018-12-27 09:56 UTC
