### ISSUE TITLE
Since upgrading to Android 5.0 I'm unable to tap buttons to change date in date picker

### ISSUE THREAD

**Issue by jwillcott** [appium/appium#4104] opened 2014-11-19 16:52 UTC
![screen shot 2014-11-19 at 11 39 32 am](https://cloud.githubusercontent.com/assets/1175959/5109673/e26ea046-6fe0-11e4-961c-037825e3f3cd.png)

I don't get any errors when I attempt to tap the year up/down, month up/down or day up/down buttons, but the value doesn't change in any of the date pickers I've tried.

It doesn't work using code... 

WebElement incrementMonthButton = datePicker.findElement(MobileBy.AndroidUIAutomator(
                "new UiSelector().className(\"android.widget.NumberPicker\").index(0)" +
                ".childSelector(new UiSelector().className(\"android.widget.Button\").index(2))"));
incrementMonthButton.click();

Or if I locate the button in inspector and click the tap button.

Here's the output when I attempt to tap it:

info: --> POST /wd/hub/session/2a4d032e-15eb-42da-b172-7bb4c5f6d04e/element/26/click {"id":"26"}
info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"26"}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"26"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: click

info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}

info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"2a4d032e-15eb-42da-b172-7bb4c5f6d04e"}
info: <-- POST /wd/hub/session/2a4d032e-15eb-42da-b172-7bb4c5f6d04e/element/26/click 200 3154.565 ms - 76 {"status":0,"value":true,"sessionId":"2a4d032e-15eb-42da-b172-7bb4c5f6d04e"}

It was working okay before I updated my phone to lollypop.

**Comment by sumio** [comment] 2015-03-21 12:39
I was faced with the same problem.
I found that tap() can change the number instead of click().

Ad-hoc sleep is required because the tap() seems to be asynchronous API.

```java
TimeUnit.SECONDS.sleep(1);
theButton.tap(1, 10);
TimeUnit.SECONDS.sleep(1);
```

**Comment by handerson-handy** [comment] 2015-09-23 18:45
I'm seeing this exact behavior using Appium 1.4.8, but none of the recommended fixes are working. Adding explicit sleeps does not make a difference, and using sendKeys only works about 10% of the time. For no apparent reason, the new values are not entered most of the time. Using tap vs. click vs. swipe does not make a difference (though of course they work in the rest of the app; just not on the date picker). Has any solution been found for this?

**Comment by handerson-handy** [comment] 2015-09-24 19:37
I did find a fix - `sendKeys()` works for the DatePicker when the xpath points to the NumberPicker, i.e. '//android.widget.DatePicker[1]//android.widget.NumberPicker[1]' and it works for the TimePicker when the xpath points directly to the text field, i.e. '//android.widget.TimePicker[1]//android.widget.NumberPicker[1]/android.widget.EditText[1]' *and* you run `clear()` on the field first. Also, the last selected field does not save, so you have to go back and select a previously entered field (by using `sendKeys()` again since tapping does not work), and catch a NoSuchElementException that randomly shows up, before hitting next in order for all the values to save. This is a slow and ugly fix, so I hope the Appium team will be able to work on this issue!

**Comment by jlipps** [comment] 2016-11-10 22:18
We'll look into this, and should see if any similar problems persist in Android 6 or 7.

**Comment by abvijay** [comment] 2017-02-04 06:27
Below is the code we r using to select particular date from excel, but it Selects the given value very rarely.  Need help to solve this issue.

  List<WebElement> date = driver.findElements(By.className("android.widget.NumberPicker"));     
     String dob_year = sheet.getRow(i).getCell(3).getStringCellValue();
     date.get(2).sendKeys(dob_year);
     
     String month_keyword4 = sheet.getRow(i).getCell(4).getStringCellValue();
     date.get(1).sendKeys(month_keyword4);     
     
     String date_keyword5 = sheet.getRow(i).getCell(5).getStringCellValue();
     date.get(0).sendKeys(date_keyword5);

**Comment by Kavitha14manoj** [comment] 2017-08-03 14:27
Any updates , I am also not able to set the date on Android 7.0 and 7.1.2 devices (appium 1.6.5)
I am using xpath and send_keys and it works fine with android 5.0 and 6.0 devices ( Appium app 1.5.3)

**Comment by CharanpreetHora** [comment] 2017-09-01 18:55
This is pretty strange. I am able to select date picker date if I am using below capability instead of uiautomator2.
capability name="automationName" value="Appium"

removed below

capability name="automationName" value="uiautomator2"
But now for me Allow Permission is blocker.
Can you suggest?

**Comment by mykola-mokhnach** [comment] 2018-05-11 10:06
Duplicate of https://github.com/appium/appium/issues/7398

**Closed by mykola-mokhnach** 2018-05-11 10:06 UTC
Labels: Android, Bug, P1
