### ISSUE TITLE
Click on pop-up from safari browser in iOS

### ISSUE THREAD

**Issue by ariaclear** [appium/appium#12824] opened 2019-06-25 10:08 UTC
## The problem

Click on URL from html page in Safari browser (iOS). The page redirects to the app store and display a pop-up with 'Open' or 'Cancel' options. Failed to inspect the pop-up with Appium. The element is not found. 
This html page has JS with redirect links to app store.

- Tried to use switch_to to alert, get an exception that the alert is not found.
- Execute script also failed can't find the element on the page.
- Added appium capabilities to handle pop-up: "autoGrantPermissions": "True".
The following capabilities used:
self.capabilities[IOSMobileCapabilityType.SAFARI_ALLOW_POPUPS] = True
self.capabilities[IOSMobileCapabilityType.SAFARI_OPEN_LINKS_IN_BACKGROUND] = True
self.capabilities[IOSMobileCapabilityType.AUTO_ACCEPT_ALERTS] = True

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Mobile platform/version under test: iOS OS 9 and above
* Real device: iPhone XR

**Comment by mykola-mokhnach** [comment] 2019-06-25 12:45
Duplicate of https://github.com/appium/appium/issues/8582

**Closed by mykola-mokhnach** 2019-06-25 12:45 UTC
