### ISSUE TITLE
Children of shadow-root elements not found on Safari/iOS.

### ISSUE THREAD

**Issue by TheScientist** [appium/appium#9986] opened 2018-01-15 12:46 UTC
## The problem

Children of shadow-root elements not found on Safari/iOS.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): - 
* Desktop OS/version used to run Appium: MacOS 10.12
* Node.js version (unless using Appium.app|exe): 8.9.4
* Mobile platform/version under test: iOS 11.0
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

We're trying to test a [polymer](https://www.polymer-project.org/) web app using webdriver/appium.
To get sub-elements of [shadow-root](https://w3c.github.io/webcomponents/spec/shadow/) elements we use the only known workaround described [here](https://gist.github.com/ChadKillingsworth/d4cb3d30b9d7fbc3fd0af93c2a133a53). This is working for Chrome (Desktop and Android), but not for Safari.
When trying to get the elements in the shadow dom an empty array is returned (see sample code and gist log at the bottom)

## Link to Appium logs

 [GIST](https://gist.github.com/TheScientist/4c5b15d71f69e026cb7517affbe924a5)

## Code To Reproduce Issue [ Good To Have ]
    WebElement root1 = driver.findElement(By.tagName("con-app"));
    //Get shadow root element
    WebElement shadowRoot1 = (WebElement) ((JavascriptExecutor) driver).executeScript("return     arguments[0].shadowRoot",root1);
    // Get elements from shadow dom of root1
    List<WebElement> children = shadowRoot1.findElements(By.cssSelector("con-modal"));
    // Working for chrome, empty in safari

**Comment by mykola-mokhnach** [comment] 2018-01-15 12:58
Does it work for Desktop Safari?

**Comment by mykola-mokhnach** [comment] 2018-01-15 12:59
Also the gist log is not available (returns 404)

**Comment by caseycantwell** [comment] 2018-05-08 23:43
Any update on this issue?

**Comment by mykola-mokhnach** [comment] 2018-10-05 17:49
Duplicate of https://github.com/appium/appium/issues/9733

**Closed by mykola-mokhnach** 2018-10-05 17:49 UTC
Labels: Mobile Safari, ThirdParty
