### ISSUE TITLE
Appium 1.6.0-beta1: iOS: HideKeyboard method not implemented

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#6872] opened 2016-09-21 07:41 UTC
## The problem

Can't hide keyboard with:
`((IOSDriver) driver).hideKeyboard(HideKeyboardStrategy.PRESS_KEY, "Done");`

## Environment

* Appium version: 1.6.0-beta1
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: OS X 10.11.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 
* Real device or emulator/simulator: Simulator 10.0
* Appium CLI or Appium.app|exe:

## Details

Server error is: "Method has not yet been implemented"

**Comment by imurchie** [comment] 2016-09-21 13:02
Yes. We have not yet figured out a way to do (reliably) this in the new system.

**Comment by amedvedjev** [comment] 2016-09-21 13:39
in the mean time my workaround is tap last key on keyboard.
`
List<WebElement> el = driver.findElements(MobileBy.className("XCUIElementTypeKeyboard")).get(0).findElements(MobileBy.className("XCUIElementTypeButton"));

tapElement((MobileElement) el.get(el.size() - 1))
`

**Comment by jlipps** [comment] 2016-09-21 16:51
closing as a duplicate of #6816

**Closed by jlipps** 2016-09-21 16:51 UTC
Labels: Bug, iOS, XCUITest
