### ISSUE TITLE
bug: Element is not accessible on iOS 16.1 (16.2 beta) on real device only

### ISSUE THREAD

**Issue by StsiapanPal** [appium/appium#17776] opened 2022-11-15 09:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Element on iOS 16.1 (iOS 16.2 beta) on real device is accessible = false. This issue is not reproducible on iOS 16.1 simulator/ iOS 15.6 real device.
Console error message: 
`....selenium.exceptions.SeleniumAtomicException: Element with locator: AppiumBy.iOSClassChain: **/XCUIElementTypeCell[`name == 'address'`]/XCUIElementTypeTextView[`name = 'detail_1'`] was not found from webdriver / root element after 20 seconds`

![Screenshot 2022-11-10 at 13 29 34](https://user-images.githubusercontent.com/94680206/201879049-6752b78e-068b-4764-bacb-14c342fd4945.png)

### Expected Behavior

Element should be accessible = true and SeleniumAtomicException should not be dispalyed

### Minimal Reproducible Example

Method which throws SeleniumAtomicException: Link to gist: https://gist.github.com/StsiapanPal/6768ffa42d10fe52c724c1e5a0f2a09c

### Environment

- Operating system: mac
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.44
  - Node.js version (output of `node --version`): v17.4.0
  - `npm` version (output of `npm --version`): 8.3.1
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator: real device iOS 16.1

### Link to Appium Logs

https://gist.github.com/StsiapanPal/094699586b69ee2e5a27bbd1bcfbd664

**Comment by mykola-mokhnach** [comment] 2022-11-15 09:57
Duplicate of https://github.com/appium/appium/issues/16425

**Closed by mykola-mokhnach** 2022-11-15 09:57 UTC
Labels: XCUITest
