### ISSUE TITLE
iOS Swiping action takes 5 minutes to complete

### ISSUE THREAD

**Issue by kienmun** [appium/appium#9809] opened 2017-12-18 09:23 UTC
## The problem

By using the iOS swipe code below, notice the action to complete 1 swipe left action it took about 5 minutes.

Below is the appium.log content:

[HTTP] --> POST /wd/hub/session/2106c5c7-40f5-432d-994a-e1bdbcc18c07/execute {"script":"mobile:swipe","args":[{"direction":"left","element":"A34EDEC2-6355-4C17-9AAE-05DCAAC586AE"}]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile:swipe",[{"direction":"left","element":"A34EDEC2-6355-4C17-9AAE-05DCAAC586AE"}],"2106c5c7-40f5-432d-994a-e1bdbcc18c07"]
[debug] [XCUITest] Executing command 'execute'
[debug] [JSONWP Proxy] Proxying [POST /wda/element/A34EDEC2-6355-4C17-9AAE-05DCAAC586AE/swipe] to [POST http://localhost:8100/session/42A7282A-DD01-4B1D-825E-01C3ACFAC366/wda/element/A34EDEC2-6355-4C17-9AAE-05DCAAC586AE/swipe] with body: {"direction":"left"}

## Environment

* Appium version: 1.7.1
* Desktop OS/version used to run Appium: mac mini
* xcode 9.0
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: Real device and simulator also having same issue

## Code To Reproduce Issue [ Good To Have ]
//step for the swipe action
getInstance().swipeToDirection_iOS_XCTest(screenElement, "l");

// iOS scroll by object
    public boolean swipeToDirection_iOS_XCTest(MobileElement el, String direction) {
        try {
            JavascriptExecutor js = (JavascriptExecutor) driver;
            HashMap<String, String> swipeObject = new HashMap<String, String>();
            if (direction.equals("d")) {
                swipeObject.put("direction", "down");
            } else if (direction.equals("u")) {
                swipeObject.put("direction", "up");
            } else if (direction.equals("l")) {
                swipeObject.put("direction", "left");
            } else if (direction.equals("r")) {
                swipeObject.put("direction", "right");
            }
            swipeObject.put("element", el.getId());
            js.executeScript("mobile:swipe", swipeObject);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

**Comment by mykola-mokhnach** [comment] 2017-12-18 13:08
duplicate of https://github.com/facebook/WebDriverAgent/issues/628

Closed as third-party issue.

**Closed by mykola-mokhnach** 2017-12-18 13:08 UTC

**Comment by kienmun** [comment] 2017-12-18 15:28
The issue WebDriverAfent#628 is not same as mine, my screen does not have any animations, but still take around 5 minutes to complete 1 swipe action,

**Comment by mykola-mokhnach** [comment] 2017-12-18 15:36
The problem happens on XCTest side and we cannot change anything in Appium to workaround it. You can report it to Apple though.
