### ISSUE TITLE
1.6.0-beta2 and real iOS iPhone 6s - Hangs on [XCUITest] Waiting for WebDriverAgent to start on device

### ISSUE THREAD

**Issue by MaciejCiach** [appium/appium#6906] opened 2016-09-28 15:44 UTC
## The problem

I try to run some previously e2e test written in Protractor on real iPhone . 
As far as it is possible on iOS simulator , I have some trobules with running it on my iPhone 6s .

## Environment

* Appium 1.6.0-beta2
* XCode 8 
* macOS Sierra
* Node 6.4.0
* iPhone 6 s iOS 10.0
* appium run from node

  capabilities: {
    browserName: 'Safari',
    platformName: 'iOS',
    platformVersion: '10.0',
    deviceName: 'iPhone 6s',
  },

## Details

I run appium then run my protractor tets. 
I can see that WebDriverAgent is opened , it shows black screen for a while and then it is closed and nothing happens 

Everything hangs on 

[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/maciejciach/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/D137F2DB-91CC-4779-8306-B51F8DF05BE3/Session-WebDriverAgentRunner-2016-09-28_172935-4yazAz.log

Appium gist 
https://gist.github.com/MaciejCiach/a74e2a8de6035f84ab9bc0db7c2132b0
XCode log gist 

https://gist.github.com/MaciejCiach/a9796a395cf13c2df036d4234e290e55

**Comment by imurchie** [comment] 2016-09-28 15:57
Duplicate of 6895

**Closed by imurchie** 2016-09-28 15:57 UTC
Labels: NeedsTriage
