### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 Using Xcode14 and Appium 1.22.3

### ISSUE THREAD

**Issue by yobelioekaharja** [appium/appium#17598] opened 2022-10-12 04:58 UTC
## The problem

I got issue `Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65` after trying to use appium 1.22.3 and Xcode 14.

## Environment

* Appium version: 1.22.3
* Desktop OS/version used to run Appium: MacOS Monterey ver 12.6
* Simulator: iPhone 11 iOS 15.5

## Details

I have to use simulator using iOS 15 and iOS 16, but this version is only available on the xcode latest version (xcode14) and latest macos version (Monterey). Therefore, I update it and successfully create a new simulator iOS 15. Unfortunately, when I was trying to execute a code using appium 1.22, I got some error `Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65`. This just happened after I moved to Xcode14. When I was trying to use the old version Xcode 13.3 and appium 1.21, the code running successfully (On iOS 14.1 because there are no simulator iOS 15 on Xcode 13.3). If I use the old version of Xcode and appium, this problem was not happen, but the needs is I have to use the simulator iOS 15. Is there any solution to fix this issue?

## Link to Appium logs

https://gist.github.com/yobelioekaharja/f6b20fffa4f07e7ceb50ce01cf0e9e44

**Comment by mykola-mokhnach** [comment] 2022-10-12 05:03
Duplicate of https://github.com/appium/appium/issues/17174

**Closed by mykola-mokhnach** 2022-10-12 05:03 UTC

**Comment by Haochenyu2021** [comment] 2023-02-22 03:52
Hi @mykola-mokhnach, how did you resolve this issue please? I got the one exactly the same and have tried millions ways and WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 still there...

**Comment by Haochenyu2021** [comment] 2023-02-22 03:58
Hi @mykola-mokhnach, how did you resolve this issue please? I got exactly the same issue and have tried millions ways and WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 still there...

**Comment by Haochenyu2021** [comment] 2023-02-22 20:39
Hi @yobelioekaharja - I wonder how did you fix this issue please? I got exactly the same one with the same after I upgraded versions and tried millions of ways (including #17174) still the same...

**Comment by bisweswar47** [comment] 2023-06-14 09:17
I ran into the same problem with iOS 16.4. Here is how I solved it:

1- In case of any OS upgrade(iOS), the framework gets disturbed as the other apps(Appium version/xcode/mac os) become unsupported. We need to make sure all the apps and OS should be compativle for the updated iOS version, we need to upgrade xcode as well as Mac OS(for latest xcode version, if required).

2- We might get errors like ‘Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65’ or ‘A valid provisioning profile for this executable was not found.’

3- Check the signing and capabilities for webdriveragentrunner and webdriveragentlib, it should be signed in using a proper developer account

4- Try running the tests again and check if the error isn’t coming anymore. In case the same errors still comes we need to do the next steps mentioned below

5- In such cases we can download the latest webdriver agent from ‘https://github.com/appium/WebDriverAgent/releases’

6- Then delete all files except Build folder from appium gui’s webdriver agent folder

7- From the downloaded folder we can copy all files and paste inside the appium gui’s webdriver agent folder

It worked for me.
