### ISSUE TITLE
App is launching Randomly in appium for IOS

### ISSUE THREAD

**Issue by Manish503** [appium/appium#11139] opened 2018-08-01 03:06 UTC
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment] 2018-08-01 04:38
@Manish503 
Could you give us any server logs?

**Comment by mykola-mokhnach** [comment] 2018-08-01 05:34
...not only logs, but describe the issue properly according to the given template

**Comment by Manish503** [comment] 2018-08-01 05:44
Environment:
Appium Version: 1.8
xcode: 9.1
Trying to launch app in IOS simulator, but after installing the app randomly opening and immediately closing.
These are the server logs:

[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.1\",\n      \"sdkVersion\" : \"11.1\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.1\",\n      \"ip\" : \"10.252.198.158\"\n    },\n    \"build\" : {\n      \"time\" : \"Jul 24 2018 11:22:30\"\n    }\n  },\n  \"sessionId\" : \"605FBF08-4859-4EF8-A609-A3B4613EBD2E\",\n  \"status\" : 0\n}"
[XCUITest] WebDriverAgent running on ip '10.252.198.158'
[XCUITest] WebDriverAgent successfully started after 12545ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1533102004810 (13:40:04 GMT+0800 (+08))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.mayBank.MKETradeUAT","arguments":[],"environment":{},"shouldWaitForQuiescence":false,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.mayBank.MKETradeUAT application","sessionId":"605FBF08-4859-4EF8-A609-A3B4613EBD2E","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1533102187244 (13:43:07 GMT+0800 (+08))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.mayBank.MKETradeUAT","arguments":[],"environment":{},"shouldWaitForQuiescence":false,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}

**Comment by mykola-mokhnach** [comment] 2018-08-01 05:50
> [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.mayBank.MKETradeUAT application","sessionId":"605FBF08-4859-4EF8-A609-A3B4613EBD2E","status":13}

The app cannot be executed. Make sure the bundle id is correct, the app itself is signed properly, installed on the device and is built for the appropriate architecture. Also it would be useful to see the full log, not just a part of it

**Comment by Manish503** [comment] 2018-08-01 06:03
@mykola-mokhnach Thanks

Bundle Id Added still facing same issue could you please check the full log details

**Full Log Details**
[Appium] Welcome to Appium v1.8.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 6 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/anakin/Downloads/MKETradeUAT.ipa","bundleId":"com.mbb.mketrade.uat","clearSystemFiles":true,"deviceName":"iPhone SE","noReset":true,"platformName":"IOS","platformVersion":"11.1","shouldUseSingletonTestManager":false,"shouldUseTestManagerForVisibilityDetection":true,"showXcodeLog":true,"udid":"0ABC6F72-16E0-408F-BD2E-3AF2AED22F28","useNewWDA":true,"waitForQuiescence":false,"newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/anakin/Downloads/MKETradeUAT.ipa","bundleId":"com.mbb.mketrade.uat","clearSystemFiles":true,"deviceName":"iPhone SE","noReset":true,"platformName":"IOS","platformVersion":"11.1","shouldUseSingletonTestManager":false,"shouldUseTestManagerForVisibilityDetection":true,"showXcodeLog":true,"udid":"0ABC6F72-16E0-408F-BD2E-3AF2AED22F28","useNewWDA":true,"waitForQuiescence":false,"newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1533103091328 (13:58:11 GMT+0800 (+08))
[Appium] Requested iOS support with version >= 10, using 'xcuitest' driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.84.0) session
[Appium] Capabilities:
[Appium]   app: /Users/anakin/Downloads/MKETradeUAT.ipa
[Appium]   bundleId: com.mbb.mketrade.uat
[Appium]   clearSystemFiles: true
[Appium]   deviceName: iPhone SE
[Appium]   noReset: true
[Appium]   platformName: IOS
[Appium]   platformVersion: 11.1
[Appium]   shouldUseSingletonTestManager: false
[Appium]   shouldUseTestManagerForVisibilityDetection: true
[Appium]   showXcodeLog: true
[Appium]   udid: 0ABC6F72-16E0-408F-BD2E-3AF2AED22F28
[Appium]   useNewWDA: true
[Appium]   waitForQuiescence: false
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"/Users/anakin/Downl...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: shouldUseTestManagerForVisibilityDetection.
[BaseDriver] Session created with session id: 3f8062be-6996-4cfe-b6d7-b5405668d833
[XCUITest] Current user: 'anakin'
[XCUITest] Xcode version set to '9.1' (tools v9.1.0.0.1.1508540944)
[XCUITest] iOS SDK Version set to '11.1'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1533103091563 (13:58:11 GMT+0800 (+08))
[iOSSim] Constructing iOS simulator for Xcode version 9.1 with udid '0ABC6F72-16E0-408F-BD2E-3AF2AED22F28'
[XCUITest] Determining device to run tests on: udid: '0ABC6F72-16E0-408F-BD2E-3AF2AED22F28', real device: false
[BaseDriver] Using local app '/Users/anakin/Downloads/MKETradeUAT.ipa'
[BaseDriver] Copying local zip to tmp dir
[BaseDriver] Unzipping local app '/var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/201871-20193-mumrup.1uptj/appium-app.zip'...
[BaseDriver] Unzipping /var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/201871-20193-mumrup.1uptj/appium-app.zip
[BaseDriver] Testing zip archive: /var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/201871-20193-mumrup.1uptj/appium-app.zip
[BaseDriver] Got a relaxed match for app in zip, be careful for app match errors
[BaseDriver] Unzipped local app to '/var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/201871-20193-mumrup.1uptj/Payload/MKETradeUAT.app'
[BaseDriver] Event 'appConfigured' logged at 1533103096117 (13:58:16 GMT+0800 (+08))
[XCUITest] Checking whether app '/var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/201871-20193-mumrup.1uptj/Payload/MKETradeUAT.app' is actually present on file system
[XCUITest] App is present
[BaseDriver] Event 'resetStarted' logged at 1533103096118 (13:58:16 GMT+0800 (+08))
[XCUITest] Reset: noReset is on. Leaving simulator as is
[BaseDriver] Event 'resetComplete' logged at 1533103096118 (13:58:16 GMT+0800 (+08))
[XCUITest] Starting log capture for iOS Simulator with udid '0ABC6F72-16E0-408F-BD2E-3AF2AED22F28', using 'xcrun simctl spawn 0ABC6F72-16E0-408F-BD2E-3AF2AED22F28 log stream --style compact'
[BaseDriver] Event 'logCaptureStarted' logged at 1533103096524 (13:58:16 GMT+0800 (+08))
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[iOSSim] Matched 1 Simulator cache item for cleanup: /Users/anakin/Library/Developer/CoreSimulator/Devices/0ABC6F72-16E0-408F-BD2E-3AF2AED22F28/data/Library/Caches/com.apple.mobile.installd.staging
[iOSSim] Setting preferences of 0ABC6F72-16E0-408F-BD2E-3AF2AED22F28 Simulator to {"ConnectHardwareKeyboard":true}
[iOSSim] Setting common Simulator preferences to {"ConnectHardwareKeyboard":true}
[iOSSim] Updated 0ABC6F72-16E0-408F-BD2E-3AF2AED22F28 Simulator preferences at '/Users/anakin/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"0ABC6F72-16E0-408F-BD2E-3AF2AED22F28":{"ConnectHardwareKeyboard":true}},"ConnectHardwareKeyboard":true}
[iOSSim] The count of running Simulator UI client instances is 1
[iOSSim] Both Simulator with UDID 0ABC6F72-16E0-408F-BD2E-3AF2AED22F28 and the UI client are currently running
[BaseDriver] Event 'simStarted' logged at 1533103097010 (13:58:17 GMT+0800 (+08))
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITest] *********************************
[XCUITest] Simulator architecture appears to be unsupported by the '/var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/201871-20193-mumrup.1uptj/Payload/MKETradeUAT.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
[XCUITest] Don't be surprised if the application fails to launch.
[XCUITest] *********************************
[XCUITest] Installing '/var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/201871-20193-mumrup.1uptj/Payload/MKETradeUAT.app' on Simulator with UUID '0ABC6F72-16E0-408F-BD2E-3AF2AED22F28'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1533103098556 (13:58:18 GMT+0800 (+08))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[XCUITest] Capability 'useNewWDA' set to true, so uninstalling WDA before proceeding
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaUninstalled' logged at 1533103100106 (13:58:20 GMT+0800 (+08))
[BaseDriver] Event 'wdaStartAttempted' logged at 1533103100107 (13:58:20 GMT+0800 (+08))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing running processes 'xcodebuild.*0ABC6F72-16E0-408F-BD2E-3AF2AED22F28, iproxy 8100, 0ABC6F72-16E0-408F-BD2E-3AF2AED22F28.*XCTRunner' for the device 0ABC6F72-16E0-408F-BD2E-3AF2AED22F28...
[XCUITest] 'pgrep -nif xcodebuild.*0ABC6F72-16E0-408F-BD2E-3AF2AED22F28' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -nif 0ABC6F72-16E0-408F-BD2E-3AF2AED22F28.*XCTRunner' didn't detect any matching processes. Return code: 1
[XCUITest] Using Xcode 9.1, so fixing WDA codebase
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=0ABC6F72-16E0-408F-BD2E-3AF2AED22F28 IPHONEOS_DEPLOYMENT_TARGET=11.1' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will be logged. To change this, use 'showXcodeLog' desired capability
[Xcode] Build settings from command line:
[Xcode]     IPHONEOS_DEPLOYMENT_TARGET = 11.1
[Xcode] 
[Xcode] 
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] === BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] Check dependencies
[Xcode] 
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 
[Xcode] 
[Xcode] === BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[Xcode] 
[Xcode] 
[Xcode] Check dependencies
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] ** TEST BUILD SUCCEEDED **
[Xcode] 
[Xcode] 
[XCUITest] Log file for xcodebuild test: /var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/com.apple.dt.XCTest/IDETestRunSession-61FD9627-AB8F-4286-9292-F0EA69A254D2/WebDriverAgentRunner-A7B09419-A847-41FF-9328-7FFA317C9CA2/Session-WebDriverAgentRunner-2018-08-01_135822-CtmnhJ.log
[Xcode] 2018-08-01 13:58:22.892 xcodebuild[20519:926252]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[Xcode] /var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/com.apple.dt.XCTest/IDETestRunSession-61FD9627-AB8F-4286-9292-F0EA69A254D2/WebDriverAgentRunner-A7B09419-A847-41FF-9328-7FFA317C9CA2/Session-WebDriverAgentRunner-2018-08-01_135822-CtmnhJ.log
[Xcode] 2018-08-01 13:58:22.892 xcodebuild[20519:926251] [MT] IDETestOperationsObserverDebug: (1232269E-5409-4049-BE1F-3C22134CB53F) Beginning test session WebDriverAgentRunner-1232269E-5409-4049-BE1F-3C22134CB53F at 2018-08-01 13:58:22.892 with Xcode 9B55 on target  {
[Xcode] 		SimDevice: iPhone SE (0ABC6F72-16E0-408F-BD2E-3AF2AED22F28, iOS 11.1, Booted)
[Xcode] } (11.1 (15B87))
[Xcode] 
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.1\",\n      \"sdkVersion\" : \"11.1\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.1\",\n      \"ip\" : \"10.252.198.158\"\n    },\n    \"build\" : {\n      \"time\" : \"Jul 24 2018 11:22:30\"\n    }\n  },\n  \"sessionId\" : \"CEE130F9-3702-4F1E-A157-EEF4B15CF377\",\n  \"status\" : 0\n}"
[XCUITest] WebDriverAgent running on ip '10.252.198.158'
[XCUITest] WebDriverAgent successfully started after 7055ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1533103107498 (13:58:27 GMT+0800 (+08))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.mbb.mketrade.uat","arguments":[],"environment":{},"shouldWaitForQuiescence":false,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}

**Comment by mykola-mokhnach** [comment] 2018-08-01 06:05
> [XCUITest] *********************************
> [XCUITest] Simulator architecture appears to be unsupported by the '/var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/201871-20193-mumrup.1uptj/Payload/MKETradeUAT.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
> [XCUITest] Don't be surprised if the application fails to launch.
> [XCUITest] *********************************

Closed as not a bug

**Closed by mykola-mokhnach** 2018-08-01 06:05 UTC
Labels: NeedsInfo, NotABug
