### ISSUE TITLE
deviceName is set BUT "desiredCapabilities object was not valid for the following reason(s):  deviceName can't be blank"

### ISSUE THREAD

**Issue by zaper4life** [appium/appium#10056] opened 2018-01-23 12:51 UTC
## The problem

I can't run on automation on a real device,  any iOS device,
For some reason I can use Perfecto Mobile :/

## Environment
Host: Mac OSX High Sierra
Device: iPad Pro iOS 10.3.3 (Can reproduce using any Apple Device)
Appium 1.7.2 Beta 3
Node: 9.3.0

## Details
**I get following error:**
_[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s):  deviceName can't be blank,_

Although it can clearly be seen that deviceName is not Blank it's Polka

## Link to Appium logs
[HTTP] <-- POST /wd/hub/session 500 10 ms - 146
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"deviceType":"tablet","server":"http://127.0.0.1:4723/wd/hub","maxTypingFrequency":"1","newCommandTimeout":"12000","platformVersion":"10.3.3","bundleId":"com.att.mobile.dfw","automationName":"XCUITest","platformName":"iOS","udid":"6b14bb541fb5c0e75b72a27ad54df1e11f2fbba1","deviceName":"Polka","fullReset":false},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"deviceType":"tablet","server":"http://127.0.0.1:4723/wd/hub","maxTypingFrequency":"1","newCommandTimeout":"12000","platformVersion":"10.3.3","bundleId":"com.***","automationName":"XCUITest","platformName":"iOS","udid":"6b14bb541fb****75b72a27ad54df1e11f2fbba1","deviceName":"\"Polka\"","fullReset":false},"requiredCapabilities":{},"alwaysMatch":{"platformName":"iOS"},"firstMatch":[]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceType":"tablet","server":"http://127.0.0.1:4723/wd/hub","maxTypingFrequency":"1","newCommandTimeout":"12000","platformVersion":"10.3.3","bundleId":"com.***","automationName":"XCUITest","platformName":"iOS","udid":"6b14bb541fb****75b72a27ad54df1e11f2fbba1","deviceName":"Polka","fullReset":false},{},{"desiredCapabilities":{"deviceType":"tablet","server":"http://127.0.0.1:4723/wd/hub","maxTypingFrequency":"1","newCommandTimeout":"12000","platformVersion":"10.3.3","bundleId":"com.***","automationName":"XCUITest","platformName":"iOS","udid":"6b14bb541fb****75b72a27ad54df1e11f2fbba1","deviceName":"Polka","fullReset":false},"requiredCapabilities":{},"alwaysMatch":{"platformName":"iOS"},"firstMatch":[]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1516711087094 (14:38:07 GMT+0200 (IST))
[Appium] Creating new IosDriver (v1.28.0) session
[Appium] Capabilities:
[Appium]   platformName: iOS
[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s):  deviceName can't be blank,

**Comment by vjmaiky** [comment] 2018-01-23 12:52
posted something similar 3h ago:
https://github.com/appium/appium/issues/10055

**Comment by KazuCocoa** [comment] 2018-01-23 14:25
What about using Appium `1.7.2`?
Appium 1.7.2 beta 3 was the enabled W3C create session version and `1.7.2` was disabled the feature, and the error looks `W3C create session` issue.

**Comment by vjmaiky** [comment] 2018-01-23 14:30
on 1.7.2 works

**Comment by mykola-mokhnach** [comment] 2018-01-23 15:25
Duplicate of https://github.com/appium/appium/issues/10055

**Closed by mykola-mokhnach** 2018-01-23 15:25 UTC
Labels: W3C
