### ISSUE TITLE
bug: Cannot press 'Add' button in messages app in iOS17

### ISSUE THREAD

**Issue by RoP09** [appium/appium#19677] opened 2024-01-18 12:47 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

I have recently updated to iOS17.2.1 and cannot press the "Add" button in the messages app anymore with the latest Appium version (after receiving a shared car key that is).
I can see the button is available in the page source XML, but the phone does not react anymore.

It works fine if I do not run a test session when I press the button manually. But once I start a test, the button becomes unresponsive - even if I disconnect the USB cable and disable testing again. I have to restart the phone to make it work again until I start another test session.

Any ideas? Worked fine using iOS16.4.1 and the same Appium version...

### Expected Behavior

"Add" button can be pressed.

### Minimal Reproducible Example

Share a car key, go to messages app and press "Add" key button in the received message containing the key.

### Environment

- Operating system: MacOS 14.2.1
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s): xcuitest 5.14.0
- Appium plugin(s) and their version(s): -
- Node.js version (output of `node --version`): 20.5.1
- `npm` version (output of `npm --version`): 9.8.0
- Last component(s) version which did _not_ exhibit the problem: iOS16
- Platform and version under test: iOS17.2.1
- Real device or emulator/simulator: iPhone 13 / 13 Pro Max

### Further Information

`

> Query chain:
> [Xcode]  →Find: Application 'com.apple.MobileSMS'
> [Xcode]   Output: {
> [Xcode]     Application, 0x10c138730, pid: 335, label: 'Messages'
> [Xcode]   }
> [Xcode]   ↪︎Find: Descendants matching type StaticText
> [Xcode]     Output: {
> [Xcode]       StaticText, 0x10c206c80, {{330.0, 57.0}, {0.0, 0.0}}
> [Xcode]       StaticText, 0x10c212670, {{16.0, -10.0}, {358.0, 13.3}}, label: 'Today 10:47'
> [Xcode]       StaticText, 0x10c214050, {{16.0, 237.3}, {358.0, 13.3}}, label: 'Today 12:44'
> [Xcode]       StaticText, 0x10c2170b0, {{95.0, 703.3}, {199.4, 13.1}}, label: 'The sender is not in your contact list.'
> [Xcode]       StaticText, 0x10c2172f0, {{161.0, 721.8}, {67.0, 14.0}}, label: 'Report Junk'
> [Xcode]       StaticText, 0x10c213870, {{6.0, 54.8}, {56.4, 4.8}}, label: 'CarMake CarModel'
> [Xcode]       StaticText, 0x10c213ab0, {{6.0, 59.6}, {56.4, 5.2}}, label: 'Car Key'
> [Xcode]       StaticText, 0x10c213cf0, {{72.8, 57.4}, {8.1, 5.2}}, label: 'Add'
> [Xcode]       StaticText, 0x10c215250, {{6.0, 54.8}, {56.4, 4.8}}, label: 'CarMake CarModel'
> [Xcode]       StaticText, 0x10c215490, {{6.0, 59.6}, {56.4, 5.2}}, label: 'Car Key'
> [Xcode]       StaticText, 0x10c2156d0, {{72.8, 57.4}, {8.1, 5.2}}, label: 'Add'
> [Xcode]       StaticText, 0x10c2168d0, {{6.0, 54.8}, {56.4, 4.8}}, label: 'CarMake CarModel'
> [Xcode]       StaticText, 0x10c216b10, {{6.0, 59.6}, {56.4, 5.2}}, label: 'Car Key'
> [Xcode]       StaticText, 0x10c216d50, {{72.8, 57.4}, {8.1, 5.2}}, label: 'Add'
> [Xcode]     }

> [Xcode]     ↪︎Find: Elements matching predicate 'fb_uid IN {"2D000000-0000-0000-F601-000000000000"}'
> [Xcode]       Output: {
> [Xcode]         StaticText, 0x10c210150, {{72.8, 57.4}, {8.1, 5.2}}, label: 'Add'
> [Xcode]       }
> [Xcode]       ↪︎Find: Element at index 0
> [Xcode]         Output: {
> [Xcode] 
> [Xcode]           StaticText, 0x10c133100, {{72.8, 57.4}, {8.1, 5.2}}, label: 'Add'
> [Xcode]         }
> [Xcode] ' for hit point calculation instead
> [Xcode]     t =  2135.00s Find the "Add" StaticText
> [Xcode]     t =  2135.00s     Requesting snapshot of accessibility hierarchy for app with pid 335
> [Xcode] 
> [Xcode]     t =  2135.04s     Find: Descendants matching type StaticText
> [Xcode] 
> [Xcode]     t =  2135.04s     Find: Elements matching predicate 'fb_uid IN {"2D000000-0000-0000-F601-000000000000"}'
> [Xcode] 
> [Xcode]     t =  2135.04s     Find: Element at index 0
> [Xcode] 
> [Xcode]     t =  2135.05s Find the "Add" StaticText
> [Xcode] 
> [Xcode]     t =  2135.05s     Requesting snapshot of accessibility hierarchy for app with pid 335
> [Xcode] 
> [Xcode]     t =  2135.08s     Find: Descendants matching type StaticText
> [Xcode] 
> [Xcode]     t =  2135.08s     Find: Elements matching predicate 'fb_uid IN {"2D000000-0000-0000-F601-000000000000"}'
> [Xcode]     t =  2135.08s     Find: Element at index 0
> [Xcode] 
> [Xcode]     t =  2135.09s Find the "Add" StaticText
> [Xcode] 
> [Xcode]     t =  2135.09s     Requesting snapshot of accessibility hierarchy for app with pid 335
> [Xcode] 
> [Xcode]     t =  2135.13s     Find: Descendants matching type StaticText
> [Xcode] 
> [Xcode]     t =  2135.13s     Find: Elements matching predicate 'fb_uid IN {"2D000000-0000-0000-F601-000000000000"}'
> [Xcode]     t =  2135.13s     Find: Element at index 0
> [Xcode] 
> [Xcode] 2024-01-18 13:34:15.395714+0100 WebDriverAgentRunner-Runner[470:8425] Waiting up to 2s until com.apple.MobileSMS is in idle state (including animations)
> [Xcode] 
> [Xcode]     t =  2135.66s Wait for com.apple.MobileSMS to idle
> [Xcode] 
> [XCUITestDriver@70d0 (31105143)] Got response with status 200: {"value":null,"sessionId":"796F3027-6A43-4366-B9D8-59BD763DDA1C"}
> [XCUITestDriver@70d0 (31105143)] Responding to client with driver.performTouch() result: null

`

**Comment by mykola-mokhnach** [comment] 2024-01-18 12:53
It is probably an issue with the app or the iOS version. I don't think there is anything we can do from the driver side to address such issues

**Comment by eglitise** [comment] 2024-01-18 14:50
Can you share the relevant parts of the Appium log? I wonder if the problem is with finding the button, or pressing it.
If it's the latter, I've had situations where the element ID changes between finding it and pressing it, which I handled by retrieving the button midpoint coordinates, and then clicking using those.

**Comment by RoP09** [comment] 2024-01-19 08:01
I guess it is more about pressing the button, because once I connected via Appium I also cannot press it manually anymore - even if I disconnect compeltely from Appium. Requires a phone restart to work again...

**Comment by KazuCocoa** [comment] 2024-01-19 08:49
Potentially XCTest for UI (testmanagerd or accessibility feature) occupied the main thread to scan or do something, which could block the UI interaction. The typical case is when you get the page source. Then XCTest framework gets element info recursively (vAppium/WDA calls them to get data), which could keep using the main thread. Then, it looks like iOS internal rather than Appium/WDA as mykola commented as the above.

**Comment by mykola-mokhnach** [comment] 2024-01-23 10:46
Closed as not an issue

**Closed by mykola-mokhnach** 2024-01-23 10:46 UTC
Labels: Needs Info
