### ISSUE TITLE
Appium 2.x WDA is not running on iOS real device?

### ISSUE THREAD

**Issue by MobileAut** [appium/appium#18260] opened 2023-02-27 16:56 UTC
I am seeing an issue the Appium inspector (running via command line by just 'appium') cannot connect to iOS real device? Caps are normal, but inspector sends err 65. Made everything as in guide.

WebDriverAgent can be built with Xcode, but not with terminal. Err: Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64.

Xcode - Version 14.2
Node - v19.6.0
Java - V 11.0.17
appium - 2.x beta
MacOS - Monterey V 12.6.3
iOS Real Device - iPhone 13 (OS 16.3.1)
Any help really appreciated.

WebDriverAgent should work on iOS real device.

**Comment by jlipps** [comment] 2023-02-27 18:17
What is the version of the xcuitest driver that you are using?

**Comment by mykola-mokhnach** [comment] 2023-02-27 20:01
Duplicate of https://github.com/appium/appium/issues/17174

Make sure xcuitest driver is up to date. Also make sure the xcode caches have been reset

**Comment by MobileAut** [comment] 2023-02-28 17:45
I am using xcuitest@4.18.3 .

**Comment by mykola-mokhnach** [comment] 2023-02-28 19:14
Then make sure xcode caches are empty and WebDriverAgent has been compiled from the current sources supplied with xcuitest driver.

**Comment by MobileAut** [comment] 2023-03-01 20:35
My issue got fixed. I need to run WebDriverAgentRunner>>Project>> Test from XCode so that WebDriverAgentRunner got installed in iPhone.

**Closed** 2023-03-01 21:42 UTC
Labels: Needs Info
