### ISSUE TITLE
WebDriverException: Message: An unknown server-side error occurred while processing the command.

### ISSUE THREAD

**Issue by rockyav** [appium/appium#5333] opened 2015-07-02 08:31 UTC
Got error when click button on iOS :

Here is appium logs:

info: [debug] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"ItsOn","label":"ItsOn","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":20,"width":320,"height":548},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid"
info: [debug] Responding to client with success: {"status":0,"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AppiumAUT>\n    <UIAApplication name=\"ItsOn\" label=\"ItsOn\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0\" x=\"0\" y=\"20\" width=\"320\" height=\"548\">\n        <UIAWindow name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0/0\" x=\"0\" y=\"0\" width=\"320\" height=\"568\">\n            <UIANavigationBar name=\"Add Credit Card\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0/0/0\" x=\"0\" y=\"20\" width=\"320\" height=\"44\">\n                <UIAImage name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"false\" hint=\"\" path=\"/0/0/0/0\" x=\"0\" y=\"0\" width=\"320\" height=\"64\">\n                    <UIAImage name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"false\" hint=\"\" path=\"/0/0/0/0/0\" x=\"0\" y=\"64\" width=\"320\" height=\"0.5\">\n                    </UIAImage>\n                </UIAImage>\n                <UIAButton name=\"\" label=\"\" value=\"\" dom...","sessionId":"973ba6e8-bd14-45ab-9220-ca07f8aa523f"}
info: <-- GET /wd/hub/session/973ba6e8-bd14-45ab-9220-ca07f8aa523f/source 200 2280.326 ms - 17434 {"status":0,"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AppiumAUT>\n    <UIAApplication name=\"ItsOn\" label=\"ItsOn\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0\" x=\"0\" y=\"20\" width=\"320\" height=\"548\">\n        <UIAWindow name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0/0\" x=\"0\" y=\"0\" width=\"320\" height=\"568\">\n            <UIANavigationBar name=\"Add Credit Card\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0/0/0\" x=\"0\" y=\"20\" width=\"320\" height=\"44\">\n                <UIAImage name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"false\" hint=\"\" path=\"/0/0/0/0\" x=\"0\" y=\"0\" width=\"320\" height=\"64\">\n                    <UIAImage name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"false\" hint=\"\" path=\"/0/0/0/0/0\" x=\"0\" y=\"64\" width=\"320\" height=\"0.5\">\n                    </UIAImage>\n                </UIAImage>\n                <UIAButton name=\"\" label=\"\" value=\"\" dom...","sessionId":"973ba6e8-bd14-45ab-9220-ca07f8aa523f"}
info: --> POST /wd/hub/session/973ba6e8-bd14-45ab-9220-ca07f8aa523f/element {"using":"name","sessionId":"973ba6e8-bd14-45ab-9220-ca07f8aa523f","value":"Add"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementByName('Add')"
info: [debug] Sending command to instruments: au.getElementByName('Add')
info: [debug] [INST] 2015-07-02 08:23:11 +0000 Debug: Got new command 44 from instruments: au.getElementByName('Add')
info: [debug] [INST] 2015-07-02 08:23:11 +0000 Debug: evaluating au.getElementByName('Add')
info: [debug] [INST] 2015-07-02 08:23:11 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-07-02 08:23:11 +0000 Debug: Lookup returned [object UIAButton] with the name "next_button" (id: 2).
info: [debug] [INST] 2015-07-02 08:23:11 +0000 Debug: responding with:
info: [debug] [INST] 2015-07-02 08:23:11 +0000 Debug: Running system command #45: /usr/local/Cellar/node/0.12.4/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"2"}}...
info: [debug] Socket data received (38 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"2"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"2"},"sessionId":"973ba6e8-bd14-45ab-9220-ca07f8aa523f"}
info: <-- POST /wd/hub/session/973ba6e8-bd14-45ab-9220-ca07f8aa523f/element 200 1034.337 ms - 87 {"status":0,"value":{"ELEMENT":"2"},"sessionId":"973ba6e8-bd14-45ab-9220-ca07f8aa523f"}
info: --> POST /wd/hub/session/973ba6e8-bd14-45ab-9220-ca07f8aa523f/element/2/click {"sessionId":"973ba6e8-bd14-45ab-9220-ca07f8aa523f","id":"2"}
info: [debug] Pushing command to appium work queue: "au.tapById('2')"
info: [debug] Sending command to instruments: au.tapById('2')
info: [debug] [INST] 2015-07-02 08:23:12 +0000 Debug: Got new command 45 from instruments: au.tapById('2')
info: [debug] [INST] 2015-07-02 08:23:12 +0000 Debug: evaluating au.tapById('2')
info: [debug] [INST] 2015-07-02 08:23:12 +0000 Debug: UIAButton.tap()
info: [debug] [INST] 2015-07-02 08:23:13 +0000 Debug: UIAButton could not be tapped
info: [debug] [INST] 2015-07-02 08:23:13 +0000 Error: VerboseError: elementId 2 could not be tapped
info: [debug] Socket data received (57 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":13,"value":"elementId 2 could not be tapped"}
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"elementId 2 could not be tapped"},"sessionId":"973ba6e8-bd14-45ab-9220-ca07f8aa523f"}
info: <-- POST /wd/hub/session/973ba6e8-bd14-45ab-9220-ca07f8aa523f/element/2/click 500 1323.453 ms - 200 
info: [debug] [INST] 2015-07-02 08:23:13 +0000 Error: Error during eval: tapById@file:///usr/local/lib/node_modules/appium/B07B679D-77CD-4FD5-85CD-1C02FD225F46/bootstrap-072528be314c3cc6.js:1110:25
       eval code
eval@[native code]
startProcessing@file:///usr/local/lib/node_modules/appium/B07B679D-77CD-4FD5-85CD-1C02FD225F46/bootstrap-072528be314c3cc6.js:2702:30
bootstrap@file:///usr/local/lib/node_modules/appium/B07B679D-77CD-4FD5-85CD-1C02FD225F46/bootstrap-072528be314c3cc6.js:2770:31
global code@file:///usr/local/lib/node_modules/appium/B07B679D-77CD-4FD5-85CD-1C02FD225F46/bootstrap-072528be314c3cc6.js:2779:10
info: --> GET /wd/hub/session/973ba6e8-bd14-45ab-9220-ca07f8aa523f/screenshot {}
info: [debug] Pushing command to appium work queue: "au.getScreenOrientation()"
info: [debug] [INST] 2015-07-02 08:23:13 +0000 Debug: responding with:
info: [debug] Sending command to instruments: au.getScreenOrientation()
info: [debug] [INST] 2015-07-02 08:23:13 +0000 Debug: Running system command #46: /usr/local/Cellar/node/0.12.4/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":13,"value":"elementId 2 could not be tapped"}...
info: [debug] [INST] 2015-07-02 08:23:14 +0000 Debug: Got new command 46 from instruments: au.getScreenOrientation()
info: [debug] [INST] 2015-07-02 08:23:14 +0000 Debug: evaluating au.getScreenOrientation()
info: [debug] [INST] 2015-07-02 08:23:14 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-07-02 08:23:14 +0000 Debug: responding with:
info: [debug] [INST] 2015-07-02 08:23:14 +0000 Debug: Running system command #47: /usr/local/Cellar/node/0.12.4/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":"PORTRAIT"}...

**Comment by Jonahss** [comment] 2015-07-03 00:05
See if you can check to make sure the element exists before tapping on it. It's possible that it's disabled or not visible.

Try getting the location of the button, then creating a TouchAction to touch the screen with those coordinates.

**Comment by imurchie** [comment] 2016-03-04 23:23
Is this still an issue? Does it occur in Appium 1.5?

**Comment by hanfeya** [comment] 2016-05-12 07:52
Maybe this issue still exists on Appium 1.5.2
''WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: elementId 2 could not be tapped'',i met on appium 1.5.2.
before i tap the element, i assert the element exists

**Comment by hanfeya** [comment] 2016-05-12 09:45
My appium server log:

[HTTP] --> POST /wd/hub/session/1abf2dcd-cec7-44ad-b495-a06b47ebfbc1/element {"using":"accessibility id","sessionId":"1abf2dcd-cec7-44ad-b495-a06b47ebfbc1","value":"目录"}

[MJSONWP] Calling AppiumDriver.findElement() with args: ["accessibility id","目录","1abf2dcd-cec7-44ad-b495-a06b47ebfbc1"]
[debug] [iOS] Executing iOS command 'findElement'

[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [UIAuto] Sending command to instruments: au.getElementByAccessibilityId('目录')

[debug] [Instruments] [INST] 2016-05-12 09:40:30 +0000 Debug: evaluation finished

[debug] [Instruments] [INST] 2016-05-12 09:40:30 +0000 Debug: responding with:

[debug] [Instruments] [INST] 2016-05-12 09:40:30 +0000 Debug: Running system command #10: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/xw/h9t7nnls21lf2_gtjpghx27r0000gn/T/instruments_sock 2,{"status":0,"v...

[debug] [Instruments] [INST] 2016-05-12 09:40:41 +0000 Debug: Got new command 10 from instruments: au.getElementByAccessibilityId('目录')

[debug] [Instruments] [INST] 2016-05-12 09:40:41 +0000 Debug: evaluating au.getElementByAccessibilityId('目录')

[debug] [Instruments] [INST] 2016-05-12 09:40:42 +0000 Debug: evaluation finished

[debug] [Instruments] [INST] 2016-05-12 09:40:42 +0000 Debug: Lookup returned [object UIAButton] with the name "目录" (id: 2).

[debug] [Instruments] [INST] 2016-05-12 09:40:42 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-05-12 09:40:42 +0000 Debug: Running system command #11: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/xw/h9t7nnls21lf2_gtjpghx27r0000gn/T/instruments_sock 2,{"status":0,"v...

[debug] [UIAuto] Socket data received (38 bytes)

[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"ELEMENT":"2"}}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"2"}
[HTTP] <-- POST /wd/hub/session/1abf2dcd-cec7-44ad-b495-a06b47ebfbc1/element 200 1387 ms - 87 
[HTTP] --> GET /wd/hub/session/1abf2dcd-cec7-44ad-b495-a06b47ebfbc1/element/2/location {}

[MJSONWP] Calling AppiumDriver.getLocation() with args: ["2","1abf2dcd-cec7-44ad-b495-a06b47ebfbc1"]
[debug] [iOS] Executing iOS command 'getLocation'
[debug] [UIAuto] Sending command to instruments: au.getElement('2').getElementLocation()

[debug] [Instruments] [INST] 2016-05-12 09:40:43 +0000 Debug: Got new command 11 from instruments: au.getElement('2').getElementLocation()

[debug] [Instruments] [INST] 2016-05-12 09:40:43 +0000 Debug: evaluating au.getElement('2').getElementLocation()

[debug] [UIAuto] Socket data received (55 bytes)

[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"x":-288,"y":14.64900016784668}}
[MJSONWP] Responding to client with driver.getLocation() result: {"x":-288,"y":14.64900016784668}

[HTTP] <-- GET /wd/hub/session/1abf2dcd-cec7-44ad-b495-a06b47ebfbc1/element/2/location 200 1087 ms - 104 
[HTTP] --> GET /wd/hub/session/1abf2dcd-cec7-44ad-b495-a06b47ebfbc1/element/2/size {}
[MJSONWP] Calling AppiumDriver.getSize() with args: ["2","1abf2dcd-cec7-44ad-b495-a06b47ebfbc1"]
[debug] [iOS] Executing iOS command 'getSize'
[debug] [UIAuto] Sending command to instruments: au.getElement('2').getElementSize()
[debug] [Instruments] [INST] 2016-05-12 09:40:43 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-05-12 09:40:43 +0000 Debug: responding with:

[debug] [Instruments] [INST] 2016-05-12 09:40:43 +0000 Debug: Running system command #12: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/xw/h9t7nnls21lf2_gtjpghx27r0000gn/T/instruments_sock 2,{"status":0,"v...

[debug] [Instruments] [INST] 2016-05-12 09:40:44 +0000 Debug: Got new command 12 from instruments: au.getElement('2').getElementSize()

[debug] [Instruments] [INST] 2016-05-12 09:40:44 +0000 Debug: evaluating au.getElement('2').getElementSize()

[debug] [UIAuto] Socket data received (63 bytes)

[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"width":96,"height":30.000001907348633}}

[MJSONWP] Responding to client with driver.getSize() result: {"width":96,"height":30.000001907348633}
[HTTP] <-- GET /wd/hub/session/1abf2dcd-cec7-44ad-b495-a06b47ebfbc1/element/2/size 200 935 ms - 112 
[HTTP] --> GET /wd/hub/session/1abf2dcd-cec7-44ad-b495-a06b47ebfbc1/window/current/size {}
[MJSONWP] Calling AppiumDriver.getWindowSize() with args: ["current","1abf2dcd-cec7-44ad-b495-a06b47ebfbc1"]
[debug] [iOS] Executing iOS command 'getWindowSize'
[debug] [UIAuto] Sending command to instruments: au.getWindowSize()
[debug] [Instruments] [INST] 2016-05-12 09:40:44 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-05-12 09:40:44 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-05-12 09:40:44 +0000 Debug: Running system command #13: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/xw/h9t7nnls21lf2_gtjpghx27r0000gn/T/instruments_sock 2,{"status":0,"v...

[debug] [Instruments] [INST] 2016-05-12 09:40:45 +0000 Debug: Got new command 13 from instruments: au.getWindowSize()

[debug] [Instruments] [INST] 2016-05-12 09:40:45 +0000 Debug: evaluating au.getWindowSize()

[debug] [UIAuto] Socket data received (49 bytes)

[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"width":320,"height":480}}

[MJSONWP] Responding to client with driver.getWindowSize() result: {"width":320,"height":480}
[HTTP] <-- GET /wd/hub/session/1abf2dcd-cec7-44ad-b495-a06b47ebfbc1/window/current/size 200 1083 ms - 98 
[HTTP] --> POST /wd/hub/session/1abf2dcd-cec7-44ad-b495-a06b47ebfbc1/element/2/click {"sessionId":"1abf2dcd-cec7-44ad-b495-a06b47ebfbc1","id":"2"}
[MJSONWP] Calling AppiumDriver.click() with args: ["2","1abf2dcd-cec7-44ad-b495-a06b47ebfbc1"]
[debug] [iOS] Executing iOS command 'click'
[debug] [UIAuto] Sending command to instruments: au.tapById('2')
[debug] [Instruments] [INST] 2016-05-12 09:40:45 +0000 Debug: evaluation finished

[debug] [Instruments] [INST] 2016-05-12 09:40:45 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-05-12 09:40:45 +0000 Debug: Running system command #14: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/xw/h9t7nnls21lf2_gtjpghx27r0000gn/T/instruments_sock 2,{"status":0,"v...

[iOSLog] [IOS_SYSLOG_ROW] May 12 17:40:46 Jiliang-iphone4 MobileGestaltHelper[74] <Error>: libMobileGestalt MobileGestalt.c:267: server_access_check denied access to question UniqueDeviceID for pid 2504

[iOSLog] [IOS_SYSLOG_ROW] May 12 17:40:46 Jiliang-iphone4 ScriptAgent[2504] <Error>: libMobileGestalt MobileGestaltSupport.m:167: pid 2504 (ScriptAgent) does not have sandbox access for re6Zb+zwFKJNlkQTUeT+/w and IS NOT appropriately entitled

[iOSLog] [IOS_SYSLOG_ROW] May 12 17:40:46 Jiliang-iphone4 ScriptAgent[2504] <Error>: libMobileGestalt MobileGestalt.c:528: no access to UniqueDeviceID (see <rdar://problem/11744455>)

[debug] [Instruments] [INST] 2016-05-12 09:40:46 +0000 Debug: Got new command 14 from instruments: au.tapById('2')

[debug] [Instruments] [INST] 2016-05-12 09:40:46 +0000 Debug: evaluating au.tapById('2')

[iOSLog] [IOS_SYSLOG_ROW] May 12 17:40:46 Jiliang-iphone4 MobileGestaltHelper[74] <Error>: libMobileGestalt MobileGestalt.c:267: server_access_check denied access to question UniqueDeviceID for pid 2504
[iOSLog] [IOS_SYSLOG_ROW] May 12 17:40:46 Jiliang-iphone4 ScriptAgent[2504] <Error>: libMobileGestalt MobileGestaltSupport.m:167: pid 2504 (ScriptAgent) does not have sandbox access for re6Zb+zwFKJNlkQTUeT+/w and IS NOT appropriately entitled
[iOSLog] [IOS_SYSLOG_ROW] May 12 17:40:46 Jiliang-iphone4 ScriptAgent[2504] <Error>: libMobileGestalt MobileGestalt.c:528: no access to UniqueDeviceID (see <rdar://problem/11744455>)

[debug] [Instruments] [INST] 2016-05-12 09:40:46 +0000 Debug: UIAButton.tap()
[debug] [Instruments] [INST] 2016-05-12 09:40:46 +0000 Debug: UIAButton could not be tapped

[debug] [Instruments] [INST] 2016-05-12 09:40:46 +0000 Error: VerboseError: elementId 2 could not be tapped

[debug] [UIAuto] Socket data received (57 bytes)

[debug] [UIAuto] Got result from instruments: {"status":13,"value":"elementId 2 could not be tapped"}
[HTTP] <-- POST /wd/hub/session/1abf2dcd-cec7-44ad-b495-a06b47ebfbc1/element/2/click 500 1490 ms - 202 
[HTTP] --> DELETE /wd/hub/session/1abf2dcd-cec7-44ad-b495-a06b47ebfbc1 {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["1abf2dcd-cec7-44ad-b495-a06b47ebfbc1"]
[debug] [iOS] Deleting ios session
[debug] [UIAuto] Destroying instruments client socket.
[debug] [UIAuto] Closing socket server.
[debug] [UIAuto] Instruments socket server was closed
[debug] [Instruments] Starting shutdown.
[debug] [Instruments] Sending sigterm to instruments

[debug] [Instruments] [INST] 2016-05-12 09:40:46 +0000 Error: Error during eval: tapById@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/C44BFD72-4F3F-4B64-939B-1A7519CAB852/bootstrap-19aed9f87e793abb.js:1196:25
       eval code
eval@[native code]
startProcessing@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/C44BFD72-4F3F-4B64-939B-1A7519CAB852/bootstrap-19aed9f87e793abb.js:2793:30
bootstrap@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/C44BFD72-4F3F-4B64-939B-1A7519CAB852/bootstrap-19aed9f87e793abb.js:2861:31
global code@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/C44BFD72-4F3F-4B64-939B-1A7519CAB852/bootstrap-19aed9f87e793abb.js:2870:10

[debug] [Instruments] [INST] 2016-05-12 09:40:46 +0000 Debug: responding with:

[debug] [Instruments] [INST] 2016-05-12 09:40:46 +0000 Debug: Running system command #15: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/xw/h9t7nnls21lf2_gtjpghx27r0000gn/T/instruments_sock 2,{"status":13,"...

[debug] [Instruments] [INST] 2016-05-12 09:40:54 +0000 Stopped: Script was stopped by the user

[iOSLog] [IOS_SYSLOG_ROW] May 12 17:40:47 Jiliang-iphone4 com.apple.launchd[1] (UIKitApplication:com.zhangyue.zyiReader.iReader[0x4c1][2502]) <Notice>: (UIKitApplication:com.zhangyue.zyiReader.iReader[0x4c1]) Exited: Killed: 9

[iOSLog] [IOS_SYSLOG_ROW] May 12 17:40:47 Jiliang-iphone4 backboardd[28] <Warning>: Application 'UIKitApplication:com.zhangyue.zyiReader.iReader[0x4c1]' exited abnormally with signal 9: Killed: 9

[debug] [Instruments] [INST STDERR] 2016-05-12 17:40:54.834 instruments[13158:1140846] Attempting to change event horizon while disengage

[debug] [Instruments] [INST] Instruments Trace Complete (Duration : 75.985664s; Output : /var/folders/xw/h9t7nnls21lf2_gtjpghx27r0000gn/T/appium-instruments/instrumentscli0.trace)

**Comment by HoratiuMoldovan** [comment] 2016-08-02 11:27
Hi,
 I am having the same problem: "An unknown server-side error occurred while processing the command. Original error: elementId 5 could not be tapped" on Appium 1.5.3

Server response: Calling AppiumDriver.findElementFromElement() with args: ["accessibility id","Assign...
[debug] [iOS] Executing iOS command 'findElementFromElement'
[debug] [BaseDriver] Waiting up to 100000 ms for condition
[debug] [UIAuto] Sending command to instruments: au.getElementByAccessibilityId('AssignToMeButton_2377076', '4')
[debug] [Instruments] [INST] 2016-08-02 11:17:32 +0000 Debug: Got new command 14 from instruments: au.getElementByAccessibilityId('AssignToMeButton_2377076', '4')
[debug] [Instruments] [INST] 2016-08-02 11:17:32 +0000 Debug: evaluating au.getElementByAccessibilityId('AssignToMeButton_2377076', '4')
[debug] [Instruments] [INST] 2016-08-02 11:17:32 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-08-02 11:17:32 +0000 Debug: Lookup returned [object UIAButton] with the name "AssignToMeButton_2377076" (id: 5).
[debug] [Instruments] [INST] 2016-08-02 11:17:32 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-08-02 11:17:32 +0000 Debug: Running system command #15: /usr/local/Cellar/node/6.3.1/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/85/6gkq4q4505zd_h5ftmy6fcbr0000gp/T/instruments_sock 2,{"status":0,"value":{"ELEMENT":"5"}}...
[debug] [UIAuto] Socket data received (38 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"ELEMENT":"5"}}
[MJSONWP] Responding to client with driver.findElementFromElement() result: {"ELEMENT":"5"}
[HTTP] <-- POST /wd/hub/session/59922512-bb86-4c58-9c25-afb9f3e497b9/element/4/element 200 1081 ms - 87 
[HTTP] --> POST /wd/hub/session/59922512-bb86-4c58-9c25-afb9f3e497b9/element/5/click {"id":"5"}
[MJSONWP] Calling AppiumDriver.click() with args: ["5","59922512-bb86-4c58-9c...
[debug] [iOS] Executing iOS command 'click'
[debug] [UIAuto] Sending command to instruments: au.tapById('5')
[debug] [Instruments] [INST] 2016-08-02 11:17:33 +0000 Debug: Got new command 15 from instruments: au.tapById('5')
[debug] [Instruments] [INST] 2016-08-02 11:17:33 +0000 Debug: evaluating au.tapById('5')
[debug] [Instruments] [INST] 2016-08-02 11:17:33 +0000 Debug: UIAButton.tap()
[debug] [Instruments] [INST] 2016-08-02 11:17:33 +0000 Debug: UIAButton could not be tapped
[debug] [UIAuto] Socket data received (57 bytes)
[debug] [UIAuto] Got result from instruments: {"status":13,"value":"elementId 5 could not be tapped"}
[HTTP] <-- POST /wd/hub/session/59922512-bb86-4c58-9c25-afb9f3e497b9/element/5/click 500 1173 ms - 202 

The command is  Page.getButoane().get(0).findElementByAccessibilityId("AssignToMeButton_2377076").click()

**Comment by HoratiuMoldovan** [comment] 2016-08-03 06:12
I have found the problem for my error. The problem is when I try to press the button, the button couldn't be found because it wasn't on the focus, although the button had an id. The problem is if you are in a main screen and you try to access a button from a table first you have to scroll to the exact position from the screen and then find the button by id and only then to press it.  As a conclusion for future updates of appium it would be nice to have access to the elements with unique identifier if there are in the main screen  even if the element is inside of a list.

**Comment by DixantDubey** [comment] 2016-08-03 11:11
@Jonahss : i am also facing the same issue with respect to iOS and it's work's fine with android.

**Comment by DixantDubey** [comment] 2016-08-03 11:16
@imurchie @rockyav @HoratiuMoldovan - Please let me know if get any solution.. on this

**Comment by HoratiuMoldovan** [comment] 2016-08-03 15:07
@DixantDubey give me more details about your situation, I fix my problem as I explain in the comment above , i locate the element in the list and I focused on that list

**Comment by DixantDubey** [comment] 2016-08-08 07:33
@HoratiuMoldovan : Please find the code below.
	driver.findElement(By.xpath("//UIAApplication[1]/UIAWindow[1]/UIATableView[1]/UIATableCell[2]/UIAStaticText[1]"));
		System.out.println("-----1----");
		Assert.assertTrue(driver.findElement(By.xpath("//UIAApplication[1]/UIAWindow[1]/UIATableView[1]/UIATableCell[2]/UIAStaticText[1]")).isDisplayed(), "element is not displayed");
		System.out.println("-----2----");
		driver.findElement(By.xpath("//UIAApplication[1]/UIAWindow[1]/UIATableView[1]/UIATableCell[2]/UIAStaticText[1]")).click();
		System.out.println("-----3----");

**Comment by HoratiuMoldovan** [comment] 2016-08-08 08:06
@DixantDubey , As I understand your problem is that your element cannot be located, from your find path your element is located into a table so you can try to iterate from your table and in each row to search for your element: something like this: 

for (int i = 0; i <= table.getTable().size(); i++) {
                table.getTableList().get(i).findElementfindElement(By.xpath.....);
                Assert.assertTrue(driver.findElement(By.xpath
            }

Make a list which contains all the rows  of the tables.

**Comment by DixantDubey** [comment] 2016-08-08 08:24
@HoratiuMoldovan : i tried with that, still i am facing the same issue.

but the same code is working fine in another system with the same device.

**Comment by HoratiuMoldovan** [comment] 2016-08-08 08:57
@DixantDubey You can try before to search the element to make a tap on that row where you search: 
for ...
table.getTableList().get(i).findElementfindElement(By. (row identifier )...).click();
find you element...
Assert....

**Comment by sysco-QA** [comment] 2016-10-16 10:06
I am facing DixantDubey's issue. Don't know how to proceed.
 Any help is appreciated.

**Comment by imurchie** [comment] 2016-10-17 12:24
@sysco-QA Can you provide more information? Full appium logs as a [gist](https://gist.github.com) would be good, for most configuration information.

**Comment by thejuskrishna** [comment] 2017-06-08 08:54
I faced the same issue when I press key code 67 (delete) during the run. It happens usually when you are running appium continuously may be for 4 to 5 days. Here's[ gist](https://gist.github.com/thejuskrishna/09317a7fafac17c285964cbcfdae4c85)

**Comment by jlipps** [comment] 2017-07-20 17:47
closing since there doesn't seem to be any workaround to tapping on an element which is not on the screen, in case that generates an error.

**Closed by jlipps** 2017-07-20 17:47 UTC
Labels: OnGoing

**Comment by vijayj** [comment] 2017-12-19 05:03
I had this exact issue while trying to automate an app with an embedded web view in iOS. I had to restart the simulator and the appium server and the error went away. I think having a more meaningful error will help.  All I got was 

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x107743f28>
response = {'status': 500, 'value': '{"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. Original error: connect ECONNREFUSED ::1:27753"},"sessionId":"d9941cb1-1f41-4b86-8ecd-8c63443478c0"}'}

```
Not very googleable

**Comment by CRivlaldo** [comment] 2018-07-06 07:32
I had the following line in a log:
`[JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Keyboard is not present\" UserInfo={NSLocalizedDescription=Keyboard is not present}","sessionId":"4103DE97-5E4E-4699-AB27-BED832B159BC","status":13}`

Next, I pressed CMD+K to present a keyboard. This made the unknown server-side error gone.

**Comment by mali5590** [comment] 2018-07-09 10:07
Thank you @CRivlaldo  you saved my time 💯  Before when i try to send key to the field the keyboard was not visible but after i pressed CMD +K and tried again it works..

**Comment by DavidAlexandre93** [comment] 2019-01-17 17:45
I am having the following problem


Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: unknown error: Argument to isShown must be of type Element
