### ISSUE TITLE
Unable to invoke chrome browser in Android Real Device

### ISSUE THREAD

**Issue by Zarmeena** [appium/appium#13404] opened 2019-10-10 10:47 UTC
We are trying to invoke Chrome browser in an Android Real Device through Appium Desktop but the browser window opens and then crashes with the following error:

An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: [object Object] unknown error: Failed to forward ports to device 52005970eee8b4f9: . unknown error: The adb command failed. Extra response: <>. (Driver info: chromedriver=77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}),platform=Windows NT 10.0.17134 x86_64)

## Environment

* Appium version: 1.14.1
* ADB version: 1.0.41
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android 9 & Android 8.1.0
* Real device or emulator/simulator: Android Emulator
* Appium CLI or Appium.app|exe: Appium.exe

Following are the Desired Capabilities being used:

{
  "platformName": "android",
  "platformVersion": "9",
  "deviceName": "android",
  "browserName": "chrome",
  "noReset": true,
  "automationName": "UIAutomator2",
  "chromedriverExecutableDir": "C:\\Users\\..\\Downloads\\chromedriver_win32_77"
}

**Comment by mykola-mokhnach** [comment] 2019-10-10 11:53
Duplicate of https://github.com/appium/appium/search?q=%22The+adb+command+failed.+Extra+response%3A+%3C%3E%22&type=Issues

**Closed by mykola-mokhnach** 2019-10-10 11:53 UTC
