### ISSUE TITLE
Cannot get 'xml' source of the current application error

### ISSUE THREAD

**Issue by ShwethaSarathy** [appium/appium#13705] opened 2019-12-11 15:09 UTC
## The problem

I am getting "Cannot get 'xml' source of the current application" error on refreshing page source on one page for a native application. On Apppium desktop the spinner keeps spinning when i click on the button and after a while spinner vanishes but page refresh doesn't happen. When i run through code i get the error as "org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot get 'xml' source of the current application". I have attached the appium server logs. Could you please look into the issue? 

[Appium_Server_Log.txt](https://github.com/appium/appium/files/3950992/Appium_Server_Log.txt)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.13
* Desktop OS/version used to run Appium: macOS mojave 10.14.6
* Node.js version (unless using Appium.app|exe): 11.6.0
* Npm or Yarn package manager: npm - 6.5.0
* Mobile platform/version under test: 13.1
* Real device or emulator/simulator: Real Device (iPhone X)
*Appium CLI or Appium.app|exe: .app file

##Code
public void i_print_pagesource() throws Throwable {
        Log.info("Page source is:\n" + driver.getPageSource());
    }

**Comment by imurchie** [comment] 2019-12-11 15:22
Is there anything in the device logs when this is happening?

Is there anything different about the one page on which this happens?

**Comment by mykola-mokhnach** [comment] 2019-12-11 15:28
Duplicate of https://github.com/appium/appium/issues?q=is%3Aissue+%22Cannot+get+%27xml%27+source+of+the+current+application%22+is%3Aclosed

**Comment by ShwethaSarathy** [comment] 2019-12-11 15:34
> Is there anything in the device logs when this is happening?
> 
> Is there anything different about the one page on which this happens?

I see below error on the device log:

XCTAS Error: XCTAutomationSupportErrorSnapshotFailure: Error kAXErrorIPCTimeout getting snapshot for element <private>

XCTAS Error: Error Domain=com.apple.dt.xctest.automation-support.error Code=5 UserInfo={NSLocalizedDescription=<private>}

XCTAS Error: XCTAutomationSupportErrorUnknownElement: Error getting main window kAXErrorIPCTimeout

XCTAS Error: Error Domain=com.apple.dt.xctest.automation-support.error Code=8 UserInfo={NSLocalizedDescription=<private>}

**Comment by mykola-mokhnach** [comment] 2019-12-11 15:37
I'm sure other people who reported their issues before already had similar problems. Check if any of the solutions proposed there work for your case. We don't have anything more to suggest on the case as it is not an issue in Appium, but the XCTest one

**Comment by ShwethaSarathy** [comment] 2019-12-11 15:43
> I'm sure other people who reported their issues before already had similar problems. Check if any of the solutions proposed there work for your case. We don't have anything more to suggest on the case as it is not an issue in Appium, but the XCTest one

I went through all the similar reported issues. But most were resolved with latest version of appium. I am already on one of the latest version for iOS13 testing.

**Comment by mykola-mokhnach** [comment] 2019-12-11 15:47
> I went through all the similar reported issues

Which particular solutions did you try, that were described there?

**Comment by imurchie** [comment] 2019-12-11 15:48
There have also been significant changes in the beta/rc versions of Appium, particularly in the evolving support for iOS 13. I would at least try the latest release candidate.

**Comment by ShwethaSarathy** [comment] 2019-12-11 15:51
> > I went through all the similar reported issues
> 
> Which particular solutions did you try, that were described there?

Issues that were in resolved state had the solution of upgrading to 1.15.1 version, which i am already on. I didnt see any other solution

**Comment by ShwethaSarathy** [comment] 2019-12-11 15:53
> There have also been significant changes in the beta/rc versions of Appium, particularly in the evolving support for iOS 13. I would at least try the latest release candidate.

Will try this.

**Comment by mykola-mokhnach** [comment] 2019-12-11 15:57
Also linking https://github.com/appium/appium/issues/13595

**Comment by liviulupei** [comment] 2019-12-11 17:22
You should try it with [Endtest](https://endtest.io) and see if it works.

**Comment by mykola-mokhnach** [comment] 2019-12-14 08:00
Unfortunately there is nothing more we can advice on this issue.

**Closed by mykola-mokhnach** 2019-12-14 08:00 UTC
Labels: ThirdParty, XCUITest
