### ISSUE TITLE
从1.6.5升级到1.7.2后不能启动appium session了。然后退回到1.6.5后还是不行。提示The capabilities argument was not valid for the following reason(s): "capabilities" must be a JSON object.

### ISSUE THREAD

**Issue by dedelost** [appium/appium#9991] opened 2018-01-16 07:55 UTC
debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","newCommandTimeout":600,"appPackage":"com.hunantv.imgo.activity","appActivity":"com.hunantv.imgo.activity.MainActivity","unicodeKeyboard":true,"platformVersion":"7.0","resetKeyboard":true,"deviceName":"abd30bcc"},null,{"firstMatch":[{}],"alwaysMatch":{"platformName":"Android"}}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1516088806197 (15:46:46 GMT+0800 (CST))
[Appium] Creating new AndroidDriver (v1.37.2) session
[Appium] Capabilities:
[Appium]   platformName: 'Android'
[Appium]   newCommandTimeout: 600
[Appium]   appPackage: 'com.hunantv.imgo.activity'
[Appium]   appActivity: 'com.hunantv.imgo.activity.MainActivity'
[Appium]   unicodeKeyboard: true
[Appium]   platformVersion: '7.0'
[Appium]   resetKeyboard: true
[Appium]   deviceName: 'abd30bcc'
[Appium]   noReset: true
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[HTTP] <-- POST /wd/hub/session 400 12 ms - 106
^C[Appium] Received SIGINT - shutting down

**Comment by senevit4** [comment] 2018-01-16 08:35
It is a duplicate of https://github.com/appium/appium/issues/9984.

**Closed** 2018-01-16 08:58 UTC
