### ISSUE TITLE
Install process fails when trying to install appium-chromedriver

### ISSUE THREAD

**Issue by piperRyan** [appium/appium#10225] opened 2018-02-20 19:05 UTC
## The problem

Unable to install appium-chromedriver@3.3.0 as part install process 

## Environment

* Version I tried installing: 1.8.0-beta3, 1.72 and 1.71:
* OS: Fedora 27 64bit 
* Node.js version: 5.6.0

## Details

Tried to install appium via: 

```bash
sudo npm install -g appium@1.8.0-beta3 # I changed the version as implied above
```
Tried clearing the cache namely I did 

```
sudo npm cache clear --force
```

and tried the same steps above. 

## Link to npm logs

```
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
/usr/bin/appium -> /usr/lib/node_modules/appium/build/lib/main.js

> appium-chromedriver@3.3.0 install /usr/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

(node:26179) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/appium/node_modules/appium-chromedriver/2018120-26179-1xcrok3.7w7'
(node:26179) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info Chromedriver Install Installing Chromedriver version '2.35' for platform 'linux' and architecture '64'
info Chromedriver Install Opening temp file to write chromedriver_linux64 to...
Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/appium/node_modules/appium-chromedriver/2018120-26179-1rnxnxn.br1m'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/appium/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@3.3.0 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@3.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-20T18_51_40_588Z-debug.log
```

Full debug log can be found here: [debug.log](https://gist.github.com/piperRyan/b28bd6c35393a34043409e83776acdee)

## Code To Reproduce Issue [ Good To Have ]

See the above code is how I produced the issue, but not sure if this a machine specific issue (knowing my luck it is :P) . However, I can if I find some time to create a docker image I will see if is reproducible. Let me know if there is any other details I can add.

**Comment by mykola-mokhnach** [comment] 2018-02-20 19:30
Duplicate of https://github.com/appium/appium/issues/10020

**Closed by mykola-mokhnach** 2018-02-20 19:30 UTC
