### ISSUE TITLE
Get page sources: AX error -25205

### ISSUE THREAD

**Issue by shynkevich-alex** [appium/appium#9439] opened 2017-10-11 16:46 UTC
## The problem
When I call getPageSource() method on iPad Air 2 (Model A1566) iOS 10.2.1 the issue happens.
A lot of elemens have values/names in sources as "AX error -25205",
**See**: https://gist.github.com/shynkevich-alex/904523e6aa4f8e4aa1a25e98bc6b976b

## Environment

* Appium 1.7.2-beta
* Java client 5.0.4
* iOS / 10.2.1
* Real iPad Air 2 (Model A1566)
* Xcuitest driver: 2.54.0

## Link to Appium logs
https://gist.github.com/shynkevich-alex/d8d0be1acccf31c0d2cd7866398acfd2

##P.S.
Also I can't get sources on Home screen of device. 
Error below occurred:

> debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Cannot get 'xml' source of the current application\",\n  \"sessionId\" : \"4090EF6A-76CB-4C12-941D-DBB647A9C2F8\",\n  \"status\" : 13\n}"

**Comment by purecynicism** [comment] 2017-10-11 17:05
Have the same issue in Appium 1.7.1 on iOS devices that run 9.x (iPad 3 / iOS 9.3.5, iPhone 5 / iOS 9.3.1)

**Comment by mykola-mokhnach** [comment] 2017-10-11 17:18
Closed as duplicate of https://github.com/facebook/WebDriverAgent/issues/703

**Closed by mykola-mokhnach** 2017-10-11 17:18 UTC
