### ISSUE TITLE
Cannot get 'xml' source reported while trying to get PageSource for iOS13

### ISSUE THREAD

**Issue by lubshilk** [appium/appium#13595] opened 2019-11-13 07:10 UTC
## The problem

The problem is not reported on IOS12, only on IOS13 for the same page
The Appium doesn't find and existing element on the page. When trying to catch page source of the page, getting the exception "Cannot get 'xml' source" 

I've seen https://github.com/facebookarchive/WebDriverAgent/issues/1001 for older Appium version but there is no solution for the problem

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0 and 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.14.2
* Desktop OS/version used to run Appium: macOS Mojave
* Node.js version (unless using Appium.app|exe): 10.16.3
* Mobile platform/version under test:  IOS 13.2.2
* Real device
* Xcode 11.2

**Comment by mykola-mokhnach** [comment] 2019-11-13 07:15
There's nothing to do here unless we can get server and system logs

**Comment by lubshilk** [comment] 2019-11-13 07:23
Will provide shortly, sorry

**Comment by lubshilk** [comment] 2019-11-13 08:11
https://gist.github.com/lubshilk/802cd84afc2f2d213e2cf1a8fdd0082f

**Comment by mykola-mokhnach** [comment] 2019-11-13 08:43
What is the output of page source if you call `mobile: source` endpoint with `format` equal to `json` or `description`?

**Comment by lubshilk** [comment] 2019-11-13 10:00
Page source in description format: https://gist.github.com/lubshilk/cad8821c276bf59c33ae23499fa88bf5

**Comment by mykola-mokhnach** [comment] 2019-11-13 10:20
how about `json` ?

**Comment by lubshilk** [comment] 2019-11-13 11:29
On json it was a problem reported and driver crashed:
```
2019-11-13 11:41:46:259 [HTTP] --> POST /wd/hub/session/2e01ee76-e448-41ec-a9f4-4f43654a5eeb/execute/sync
2019-11-13 11:41:46:259 [HTTP] {"script":"mobile: source","args":[{"format":"json"}]}
2019-11-13 11:41:46:260 [W3C (2e01ee76)] Calling AppiumDriver.execute() with args: ["mobile: source",[{"format":"json"}],"2e01ee76-e448-41ec-a9f4-4f43654a5eeb"]
2019-11-13 11:41:46:260 [XCUITest] Executing command 'execute'
2019-11-13 11:41:46:262 [WD Proxy] Matched '/source?format=json' to command name 'getPageSource'
2019-11-13 11:41:46:263 [WD Proxy] Proxying [GET /source?format=json] to [GET http://localhost:8100/session/21511BD0-0BE5-4120-A095-4E82E17702CF/source?format=json] with no body
2019-11-13 11:41:46:305 [Xcode]     t =    23.49s Find the Application 'com.cellact.secnum2'
2019-11-13 11:41:46:306 [Xcode] 
2019-11-13 11:41:46:306 [Xcode]     t =    23.50s     Requesting snapshot of accessibility hierarchy for app with pid 280
2019-11-13 11:41:46:306 [Xcode] 
2019-11-13 11:41:46:376 [Xcode] 2019-11-13 11:41:46.376642+0200 WebDriverAgentRunner-Runner[276:4676] Cannot take the snapshot of Application 'com.cellact.secnum2' after 15 seconds
2019-11-13 11:41:46:376 [Xcode] 2019-11-13 11:41:46.376778+0200 WebDriverAgentRunner-Runner[276:4676] Internal error: Error Domain=com.apple.dt.xctest.automation-support.error Code=5 "Timed out snapshotting com.apple.testmanagerd, app is either unresponsive or taking too long to snapshot." UserInfo={accessibility-error=-25204, NSLocalizedDescription=Timed out snapshotting com.apple.testmanagerd, app is either unresponsive or taking too long to snapshot.}
2019-11-13 11:41:46:377 [Xcode]     t =    23.57s Requesting snapshot of accessibility hierarchy for app with pid 280
2019-11-13 11:41:46:377 [Xcode] 
2019-11-13 11:41:46:384 [WD Proxy] Got response with status 200: {
2019-11-13 11:41:46:384 [WD Proxy]   "value" : {
2019-11-13 11:41:46:385 [WD Proxy]     "rawIdentifier" : null,
2019-11-13 11:41:46:385 [WD Proxy]     "isVisible" : "0",
2019-11-13 11:41:46:385 [WD Proxy]     "frame" : "{{0, 0}, {0, 0}}",
2019-11-13 11:41:46:385 [WD Proxy]     "value" : null,
2019-11-13 11:41:46:386 [WD Proxy]     "label" : null,
2019-11-13 11:41:46:386 [WD Proxy]     "type" : "Any",
2019-11-13 11:41:46:386 [WD Proxy]     "name" : null,
2019-11-13 11:41:46:386 [WD Proxy]     "isEnabled" : "0"
2019-11-13 11:41:46:387 [WD Proxy]   },
2019-11-13 11:41:46:387 [WD Proxy]   "sessionId" : "21511BD0-0BE5-4120-A095-4E82E17702CF"
2019-11-13 11:41:46:387 [WD Proxy] }
2019-11-13 11:41:46:389 [W3C (2e01ee76)] Responding to client with driver.execute() result: {"rawIdentifier":null,"isVisible":"0","frame":"{{0, 0}, {0, 0}}","value":null,"label":null,"type":"Any","name":null,"isEnabled":"0"}
2019-11-13 11:41:46:390 [HTTP] <-- POST /wd/hub/session/2e01ee76-e448-41ec-a9f4-4f43654a5eeb/execute/sync 200 131 ms - 142
```

**Comment by mykola-mokhnach** [comment] 2019-11-13 11:46
> 2019-11-13 11:41:46:376 [Xcode] 2019-11-13 11:41:46.376778+0200 WebDriverAgentRunner-Runner[276:4676] Internal error: Error Domain=com.apple.dt.xctest.automation-support.error Code=5 "Timed out snapshotting com.apple.testmanagerd, app is either unresponsive or taking too long to snapshot." UserInfo={accessibility-error=-25204, NSLocalizedDescription=Timed out snapshotting com.apple.testmanagerd, app is either unresponsive or taking too long to snapshot.}

This XCTest error and I don't think we can do much about it. There is a possibility to increase the snapshot timeout though. Try the `snapshotTimeout` driver setting

**Comment by lubshilk** [comment] 2019-11-13 11:50
There are so many problems with XCTest! Do you now if they will be fixed?

**Comment by lubshilk** [comment] 2019-11-13 11:53
I'll try to run with snapshotTimeout, thanks

**Comment by mykola-mokhnach** [comment] 2019-11-13 11:53
![pain](https://i.imgflip.com/156vxq.jpg)

Apple made it and only Apple can fix it ;)

**Comment by mykola-mokhnach** [comment] 2019-11-13 11:55
You can also try to set the `defaultActiveApplication` setting to the current app bundle identifier. This is not really necessary, but just to make sure the correct app is always selected

**Comment by 3a4oT** [comment] 2019-11-13 13:49
we have the same issue and `snapshotTimeout` doesn't help. Then I set `useJSONSource: true` and I was able to bypass this issue, unfortunately, we faced the new one - only one element shown by the inspector instead of a tree.

 ```
 "automationName": "XCUITest",
  "platformVersion": "13.2",
  "snapshotTimeout": 30,
  "useJSONSource": true
```

**Comment by mykola-mokhnach** [comment] 2019-11-15 08:07
@lubshilk I've made several improvements to WDA recently, so now it is possible to get the xml source without including the `visible` attribute, which is usually the cause of snapshotting issues.
Reinstall appium@beta and request the source using `mobile: source` endpoint with arguments `format`: `xml` and `excludedAttributes`: visible`

**Comment by lubshilk** [comment] 2019-11-17 15:00
@mykola-mokhnach Upgraded Appium to v1.16.0-beta.1 and used arguments as you suggested. 
Got xml page source. Thanks :)
Could WDA be improved to catch elements by classname and id as well? ;) This is our original problem, we began to try to catch page source to verify what changed on the page and why elements are not found

**Comment by mykola-mokhnach** [comment] 2019-11-17 15:07
> Could WDA be improved to catch elements by classname and id as well? 

What do you mean?

**Comment by jniosdeveloper** [comment] 2019-11-18 05:44
@lubshilk Hello, I'd like to ask you a question. How do you run it on a real machine? After I clone WebDriverAgent and run it in Xcode 11.2, I can't compile successfully. An error (could not build module 'routinghttpserver') will be reported. WebDrivertAgent can't run, so I can't test it.

**Comment by lubshilk** [comment] 2019-11-18 06:34
I needed pagesource to check why an element we are trying to find by classname reported as not found. It cleared in ios13 it shown differently from ios12 (the same page in application)
So it looks like no WDA, but again XCUItest problem :( So you cannot help here, right?

**Comment by lubshilk** [comment] 2019-11-18 07:26
@mykola-mokhnach Thanks for helping :) 
When the next not-beta version is expected?

**Comment by lubshilk** [comment] 2019-11-18 09:15
@jniosdeveloper We don't build the WDA in Xcode app. It is built and installed on the real device by appium while creating a session

**Comment by mykola-mokhnach** [comment] 2019-11-18 09:29
> So it looks like no WDA, but again XCUItest problem :( So you cannot help here, right?

Yes, the tree itself is built by XCTest.

Closed as third party issue

**Closed by mykola-mokhnach** 2019-11-18 09:29 UTC
Labels: NeedsInfo, ThirdParty, XCUITest

**Comment by lubshilk** [comment] 2019-11-18 10:03
@mykola-mokhnach When the next not-beta version with mentioned WDA improvements is expected?

**Comment by mykola-mokhnach** [comment] 2019-11-18 10:27
I cannot say the exact dates. As soon as we address known problems in iOS and Android

**Comment by GunkanjimaQA** [comment] 2019-11-26 10:51
> @lubshilk I've made several improvements to WDA recently, so now it is possible to get the xml source without including the `visible` attribute, which is usually the cause of snapshotting issues.
> Reinstall appium@beta and request the source using `mobile: source` endpoint with arguments `format`: `xml` and `excludedAttributes`: `visible`

Quite an offtopic but is it possible to use these parameters when running Appium desktop with appium@beta 1.16? Maybe you can point the direction to dig?

**Comment by narasimhanukala** [comment] 2019-11-29 15:11
> @lubshilk I've made several improvements to WDA recently, so now it is possible to get the xml source without including the `visible` attribute, which is usually the cause of snapshotting issues.
> Reinstall appium@beta and request the source using `mobile: source` endpoint with arguments `format`: `xml` and `excludedAttributes`: `visible`

@mykola-mokhnach ,
i am a beginer to Appium.
Can you provide more details on how to use following attributes while using appium desktop?

`mobile: source` endpoint with arguments `format`: `xml` and `excludedAttributes`: `visible`

**Comment by narasimhanukala** [comment] 2019-12-02 07:19
> @mykola-mokhnach Upgraded Appium to v1.16.0-beta.1 and used arguments as you suggested.
> Got xml page source. Thanks :)
> Could WDA be improved to catch elements by classname and id as well? ;) This is our original problem, we began to try to catch page source to verify what changed on the page and why elements are not found

@lubshilk ,
How did you use the arguments to resolve the xml structure issue?

**Comment by lubshilk** [comment] 2019-12-02 08:28
@narasimhanukala Code in Java
			

> HashMap<String,String> obj = new HashMap<String,String>();
> 			obj.put("format", "xml");
> 			obj.put("excludedAttributes", "visible");
> 			String PageSource = ((JavascriptExecutor)driver).executeScript("mobile: source", obj).toString();

**Comment by narasimhanukala** [comment] 2019-12-02 09:07
> @narasimhanukala I didn't use it in Appium desktop
> Code in Java:
> 
> > HashMap<String,String> obj = new HashMap<String,String>();
> > obj.put("format", "xml");
> > obj.put("excludedAttributes", "visible");
> > String PageSource = ((JavascriptExecutor)driver).executeScript("mobile: source", obj).toString();

Hi @lubshilk , thanks for quick turnaround.
i don't think i need PageSource in my framework.
What exactly you are doing after getting pagesource??

**Comment by lubshilk** [comment] 2019-12-02 09:13
@narasimhanukala I needed page source to check how an element is shown in our application on IOS13 device (In the same application on devices with IOS12 and IOS13 the same element can be shown differently by XCUItest)

**Comment by narasimhanukala** [comment] 2019-12-02 09:17
> @narasimhanukala I needed page source to check how an element is shown in our application on IOS13 device (In the same application on devices with IOS12 and IOS13 the same element can be shown differently by XCUItest)

Thanks @lubshilk

**Comment by czandler22** [comment] 2020-08-14 10:04
> @lubshilk I've made several improvements to WDA recently, so now it is possible to get the xml source without including the `visible` attribute, which is usually the cause of snapshotting issues.
> Reinstall appium@beta and request the source using `mobile: source` endpoint with arguments `format`: `xml` and `excludedAttributes`: `visible`

I tried everything from this topic and nothing helped. Please help!!!
