### ISSUE TITLE
is there any change for appium-xcuitest-driver webdriveragent.xcodeproj in appium 15.0

### ISSUE THREAD

**Issue by Sourabh25** [appium/appium#13327] opened 2019-09-30 14:58 UTC
## The problem

Is there any change with the webdriveragent.xcodeproj in the appium-xcuitest-driver for appium 1.15.0 After downloading the new appium I am not able to see the webdriveragent.xcodeproj  in the appium-xcuitest-driver as I was able to see it earlier in appium 1.13.0

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): 1.13.0
* Desktop OS/version used to run Appium: macOS mojave 10.14.6
* Node.js version (unless using Appium.app|exe): 12.6.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: ios 13.0
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment] 2019-09-30 15:12
Duplicate of https://github.com/appium/appium/issues/13297

**Closed by mykola-mokhnach** 2019-09-30 15:12 UTC

**Comment by Sourabh25** [comment] 2019-09-30 15:15
thanks @imurchie . One question. Do i need to the following steps:

cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
mkdir -p Resources/WebDriverAgent.bundle
sh ./Scripts/bootstrap.sh -d.

Kindly update

**Comment by imurchie** [comment] 2019-09-30 15:18
If you are running through Appium, no. This will be handled in session initialization, if it is necessary.

If for some reason you need to do it (for instance, to build in Xcode), yes. But the initial location will be as described above.

**Comment by Sourabh25** [comment] 2019-09-30 15:21
@imurchie I am not sure but I am getting the below exception

RemoteTestNG] detected TestNG version 6.14.3
Trying to start the Appium Server.....
[35m[Appium][39m Welcome to Appium v1.15.0
[35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723
FAILED CONFIGURATION: @BeforeSuite appiumServerSetup
io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: /usr/local/Cellar/node/12.6.0/bin/node Arguments: [/usr/local/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 0.0.0.0] 
Process output: [35m[Appium][39m Welcome to Appium v1.15.0
[35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723


	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:161)
	at com.comcast.sparta.base.TestBase.appiumServerSetup(TestBase.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://0.0.0.0:4723/wd/hub/status] to be available after 120006 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:125)
	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:148)
	... 21 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 23 more

**Comment by mykola-mokhnach** [comment] 2019-09-30 15:34
The above question has been already answered in https://github.com/appium/java-client/issues/1243
