### ISSUE TITLE
WebDriverAgent class chain returns elements that don't exist in /source

### ISSUE THREAD

**Issue by s-glatshtein** [appium/appium#14828] opened 2020-10-21 09:02 UTC
## The problem

In several applications (such as Airbnb and Youtube), when opening a search panel, searching for children of the first window returns additional element that doesn't exist.

## Environment

* WebDriverAgent tag 2.27.2 compiled using xcode 11

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

I have performed the following requests after running WebDriverAgent from xcode:

1. `POST /session` with body 
`{"capabilities":{"firstMatch":[{"bundleId":"com.airbnb.app","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":false,"shouldUseTestManagerForVisibilityDetection":true,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
`
2. `GET  /session/:session_id/elements` with body 
`{"using":"xpath", "value":"XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]"}
`
3. `POST /session/:session_id/element/:element_id/click` - this opens the search of airbnb
4. `GET  /session/:session_id/elements` with body 
`{"using":"xpath", "value":"//XCUIElementTypeWindow[1]/XCUIElementTypeOther"}` 
**Result**: returns 1 element
5. `GET  /session/:session_id/elements` with body 
`{"using":"class chain", "value":"XCUIElementTypeWindow[1]/XCUIElementTypeOther"}`
**Result**: returns 2 elements, one of which found by xpath

## Additional Details

If after running step 1. I will try to run steps 4. and 5. I will get in both the extra element found when running the scenario above

**Comment by mykola-mokhnach** [comment] 2020-10-21 09:06
Duplicate of https://github.com/appium/appium/issues/13958

**Closed by mykola-mokhnach** 2020-10-21 09:06 UTC
