### ISSUE TITLE
WebdriverAgentLib no longer built on Xcode Version 14.0 (14A309) and up

### ISSUE THREAD

**Issue by kontownik** [appium/appium#17621] opened 2022-10-17 08:37 UTC
## The problem

I tried to rebuild WebdriverAgentLib as I always did with https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md#full-manual-configuration
with one of the latest XCode but then I got compilation error:

**error build: Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64**

I am pretty sure it's connected with Xcode as I didn't update Appium recently.
## Environment

* Appium version: 1.22.2 and 
* Xcode version: 14.0 (14A309) and
* Last Appium version that did not exhibit the issue (if applicable): not sure?
* Desktop OS/version used to run Appium: macOS
* Node.js version: v18.3.0
* Npm version: 8.11.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: generic iOS device

**Comment by mykola-mokhnach** [comment] 2022-10-17 08:39
Duplicate of https://github.com/appium/appium/issues/17174

**Closed by mykola-mokhnach** 2022-10-17 08:39 UTC

**Comment by kontownik** [comment] 2022-10-17 08:45
@mykola-mokhnach sorry about creating duplicate, I checked linked issue but I don't understand how to fix it for Appium 1.x

**Comment by mykola-mokhnach** [comment] 2022-10-17 08:54
the only "fix" is to switch to Appium 2. We do not maintain Appium 1 anymore
