### ISSUE TITLE
Throwing InvalidElementStateException while click and send keys to XCUIElementTypeSearchField 

### ISSUE THREAD

**Issue by MohanaSArumugam** [appium/appium#14730] opened 2020-09-14 05:00 UTC
Hi,
I recently upgraded appium to 1.18.1 for testing in iOS 13.7. In that i'm getting below error while clicking and sending values to XCUIElementTypeSearchField

org.openqa.selenium.InvalidElementStateException: Error Domain=com.facebook.WebDriverAgent Code=1 “‘”Search” Button’ is not ready for a text input. Neither the accessibility element itself nor its accessible descendants have the input focus” UserInfo={NSLocalizedDescription=‘“Search” Button’ is not ready for a text input. Neither the accessibility element itself nor its accessible descendants have the input focus}
Build info: version: ‘3.12.0’, revision: ‘7c6e0b3’, time: ‘2018-05-08T14:04:26.12Z’
System info: host: ‘Mohana01-mbp-micmini.local’, ip: ‘fe80:0:0:0:100c:9597:6074:f9ae%en0’, os.name: ‘Mac OS X’, os.arch: ‘x86_64’, os.version: ‘10.15.5’, java.version: ‘1.8.0_131’
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {automationName: Xcuitest, browserName: , bundleId: com.vocera.uc, databaseEnabled: false, derivedDataPath: /Users/mohana_arumugam/Docu..., deviceName: iPhone 6, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, newCommandTimeout: 96000, platform: MAC, platformName: iOS, platformVersion: 11.1, takesScreenshot: true, udid: 46e58ce0871791339ec2b0625e3..., useNewWDA: true, usePrebuiltWDA: true, waitForAppScript: true, wdaConnectionTimeout: 1200000, wdaLocalPort: 8200, wdaStartupRetryInterval: 10000, webStorageEnabled: false}
Session ID: ed14ea4c-983b-40f0-95de-6e61b0b9c224

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.1 and beta version
* Last Appium version that did not exhibit the issue (if applicable): 1.17.1
* Desktop OS/version used to run Appium: MacOS Catalina
* Mobile platform/version under test: iOS 13.6.1
* Real device or emulator/simulator: Real device-iPhone XS
* Webdriveragent version : appium-webdriveragent@2.20.0
* Xcode version: Xcode 12 beta 6

## Link to Appium logs

[Appium Log](https://gist.github.com/MohanaSArumugam/10dc64a921376284eef5e4418eda37d1)

## Code To Reproduce Issue [ Good To Have ]

Here is the piece of code which throws this error. Throwing error in step 2

        this.getStartAChatObject().Search.click()
        this.getStartAChatObject().Search.sendKeys(UserOrGroup);
        this.wait(2);
        driver.findElement(By.id("Search")).click();//closing keyboard
        List<WebElement> userList = driver.findElements(By.id(UserOrGroup));

**Comment by mykola-mokhnach** [comment] 2020-09-14 08:05
Duplicate of https://github.com/appium/java-client/issues/1386

**Closed by mykola-mokhnach** 2020-09-14 08:05 UTC
