### ISSUE TITLE
send keys clear the text field after typing in mobile safari

### ISSUE THREAD

**Issue by Summerxia88** [appium/appium#13066] opened 2019-08-13 14:51 UTC
## The problem

I'm facing issue with safari browser on ios simulator. Please help to fix this issue!!
I tried the following ways, but no luck.
```java
input.click();
input.clear();
Thread.sleep(1000);
input.sendKeys(username);
input.sendKeys(Keys.TAB); not working

((JavascriptExecutor) driver).executeScript("console.log(arguments[0]); $(arguments[0]).change(); return true;", input); not working
```

The value is sent but cleared right away.

## Environment

* Appium version that exhibits the issue: 1.10.0
* Mac OS High Sierra 10.13.6
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: 6.5.0
* Mobile platform/version under test: iOS 12.0
* Real device or emulator/simulator: iphone X simulator 
* Appium CLI or Appium.app|exe:

## Link to Appium logs
```
[info] [35m[HTTP][39m [90m{"using":"xpath","value":"//input[@aria-label='login-email-id']"}[39m
[debug] [35m[W3C (e7e62ff4)][39m Calling AppiumDriver.findElement() with args: ["xpath","//input[@aria-label='login-email-id']","e7e62ff4-7f92-4fcf-a985-d133e9717e25"]
[debug] [35m[XCUITest][39m Executing command 'findElement'
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [35m[BaseDriver][39m Waiting up to 15000 ms for condition
[debug] [35m[RemoteDebugger][39m Executing 'find_element' atom in default context
[debug] [35m[RemoteDebugger][39m Garbage collecting with 5000ms timeout
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [35m[RemoteDebugger][39m Found data handler for response
[debug] [35m[RemoteDebugger][39m Received data response from socket send: '{}'
[debug] [35m[RemoteDebugger][39m Original command: garbageCollect
[debug] [35m[RemoteDebugger][39m Garbage collection successful
[debug] [35m[RemoteDebugger][39m Sending javascript command (function(){return function(){var k=this;functi...
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [35m[RemoteDebugger][39m Found data handler for response
[debug] [35m[RemoteDebugger][39m Received data response from socket send: '{"status":0,"value":{"ELEMENT":":wdc:1565717462...'
[debug] [35m[RemoteDebugger][39m Original command: sendJSCommand
[debug] [35m[RemoteDebugger][39m Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1565717462767"}
[debug] [35m[W3C (e7e62ff4)][39m Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"5008"}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/e7e62ff4-7f92-4fcf-a985-d133e9717e25/element [39m[32m200[39m [90m54 ms - 56[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/e7e62ff4-7f92-4fcf-a985-d133e9717e25/element/5008/value[39m
[info] [35m[HTTP][39m [90m{"id":"5008","text":"auto_preferred_01@sothebysqa.com","value":["a","u","t","o","_","p","r","e","f","e","r","r","e","d","_","0","1","@","s","o","t","h","e","b","y","s","q","a",".","c","o","m"]}[39m
[debug] [35m[W3C (e7e62ff4)][39m Calling AppiumDriver.setValue() with args: [["a","u","t","o","_","p","r","e","f","e","r","r","e","d","_","0","1","@","s","o","t","h","e","b","y","s","q","a",".","c","o","m"],"5008","e7e62ff4-7f92-4fcf-a985-d133e9717e25"]
[debug] [35m[XCUITest][39m Executing command 'setValue'
[debug] [35m[RemoteDebugger][39m Executing 'click' atom in default context
[debug] [35m[RemoteDebugger][39m Garbage collecting with 5000ms timeout
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [35m[RemoteDebugger][39m Found data handler for response
[debug] [35m[RemoteDebugger][39m Received data response from socket send: '{}'
[debug] [35m[RemoteDebugger][39m Original command: garbageCollect
[debug] [35m[RemoteDebugger][39m Garbage collection successful
[debug] [35m[RemoteDebugger][39m Sending javascript command (function(){return function(){var h,aa=this;fun...
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [35m[RemoteDebugger][39m Found data handler for response
[debug] [35m[RemoteDebugger][39m Received data response from socket send: '{"status":0,"value":null}'
[debug] [35m[RemoteDebugger][39m Original command: sendJSCommand
[debug] [35m[RemoteDebugger][39m Received result for atom 'click' execution: null
[debug] [35m[RemoteDebugger][39m Executing 'type' atom in default context
[debug] [35m[RemoteDebugger][39m Garbage collecting with 5000ms timeout
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [35m[RemoteDebugger][39m Found data handler for response
[debug] [35m[RemoteDebugger][39m Received data response from socket send: '{}'
[debug] [35m[RemoteDebugger][39m Original command: garbageCollect
[debug] [35m[RemoteDebugger][39m Garbage collection successful
[debug] [35m[RemoteDebugger][39m Sending javascript command (function(){return function(){var h,aa=this;fun...
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [35m[RemoteDebugger][39m Found data handler for response
[debug] [35m[RemoteDebugger][39m Received data response from socket send: '{"status":0,"value":null}'
[debug] [35m[RemoteDebugger][39m Original command: sendJSCommand
[debug] [35m[RemoteDebugger][39m Received result for atom 'type' execution: null
[debug] [35m[W3C (e7e62ff4)][39m Responding to client with driver.setValue() result: null
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/e7e62ff4-7f92-4fcf-a985-d133e9717e25/element/5008/value [39m[32m200[39m [90m114 ms - 14[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/e7e62ff4-7f92-4fcf-a985-d133e9717e25/element[39m
[info] [35m[HTTP][39m [90m{"using":"xpath","value":"//input[@aria-label='login-email-id']"}[39m
[debug] [35m[W3C (e7e62ff4)][39m Calling AppiumDriver.findElement() with args: ["xpath","//input[@aria-label='login-email-id']","e7e62ff4-7f92-4fcf-a985-d133e9717e25"]
[debug] [35m[XCUITest][39m Executing command 'findElement'
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [35m[BaseDriver][39m Waiting up to 15000 ms for condition
[debug] [35m[RemoteDebugger][39m Executing 'find_element' atom in default context
[debug] [35m[RemoteDebugger][39m Garbage collecting with 5000ms timeout
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to remote debugger[debug] [35m[RemoteDebugger][39m Found data handler for response
[debug] [35m[RemoteDebugger][39m Received data response from socket send: '{}'
[debug] [35m[RemoteDebugger][39m Original command: garbageCollect
[debug] [35m[RemoteDebugger][39m Garbage collection successful
[debug] [35m[RemoteDebugger][39m Sending javascript command (function(){return function(){var k=this;functi...
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [35m[RemoteDebugger][39m Found data handler for response
[debug] [35m[RemoteDebugger][39m Received data response from socket send: '{"status":0,"value":{"ELEMENT":":wdc:1565717462...'
[debug] [35m[RemoteDebugger][39m Original command: sendJSCommand
[debug] [35m[RemoteDebugger][39m Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1565717462767"}
[debug] [35m[W3C (e7e62ff4)][39m Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"5009"}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/e7e62ff4-7f92-4fcf-a985-d133e9717e25/element [39m[32m200[39m [90m59 ms - 56[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/e7e62ff4-7f92-4fcf-a985-d133e9717e25/element/5009/value[39m
[info] [35m[HTTP][39m [90m{"id":"5009","text":"","value":[""]}[39m
[debug] [35m[W3C (e7e62ff4)][39m Calling AppiumDriver.setValue() with args: [[""],"5009","e7e62ff4-7f92-4fcf-a985-d133e9717e25"]
[debug] [35m[XCUITest][39m Executing command 'setValue'
[debug] [35m[RemoteDebugger][39m Executing 'click' atom in default context
[debug] [35m[RemoteDebugger][39m Garbage collecting with 5000ms timeout
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [35m[RemoteDebugger][39m Found data handler for response
[debug] [35m[RemoteDebugger][39m Received data response from socket send: '{}'
[debug] [35m[RemoteDebugger][39m Original command: garbageCollect
[debug] [35m[RemoteDebugger][39m Garbage collection successful
[debug] [35m[RemoteDebugger][39m Sending javascript command (function(){return function(){var h,aa=this;fun...
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [35m[RemoteDebugger][39m Found data handler for response
[debug] [35m[RemoteDebugger][39m Received data response from socket send: '{"status":0,"value":null}'
[debug] [35m[RemoteDebugger][39m Original command: sendJSCommand
[debug] [35m[RemoteDebugger][39m Received result for atom 'click' execution: null
[debug] [35m[RemoteDebugger][39m Executing 'type' atom in default context
[debug] [35m[RemoteDebugger][39m Garbage collecting with 5000ms timeout
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [35m[RemoteDebugger][39m Found data handler for response
[debug] [35m[RemoteDebugger][39m Received data response from socket send: '{}'
[debug] [35m[RemoteDebugger][39m Original command: garbageCollect
[debug] [35m[RemoteDebugger][39m Garbage collection successful
[debug] [35m[RemoteDebugger][39m Sending javascript command (function(){return function(){var h,aa=this;fun...
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to remote debugger[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/e7e62ff4-7f92-4fcf-a985-d133e9717e25/element[39m

```

## Code To Reproduce Issue [ Good To Have ]
```
input.click();
input.clear();
Thread.sleep(1000);
input.sendKeys(username);
input.sendKeys(Keys.TAB);
```

**Comment by imurchie** [comment] 2019-08-13 16:15
I don't see the second `sendKeys` in the logs. Is something missing?

**Comment by Summerxia88** [comment] 2019-08-13 17:49
@imurchie I updated the logs. Thanks

**Comment by imurchie** [comment] 2019-08-13 19:41
Thanks!

I cannot reproduce this. Can you provide more information about the context?

What happens if you send more text, rather than `Keys.TAB`?

**Comment by Summerxia88** [comment] 2019-08-14 20:51
if I send more text, it will clear right away and move to the next text field.

**Comment by Summerxia88** [comment] 2019-09-17 18:53
@imurchie I'm still facing the issue with mobile safari browser. Look like the input can't be saved and wiped once cursor moved to the other field. 
Code is as below:
input.click();
input.clear();
Thread.sleep(1000);
input.sendKeys(username);
input.sendKeys(Keys.TAB);

input.click();
input.clear();
Thread.sleep(1000);
input.sendKeys(password);
input.sendKeys(Keys.TAB);

**Comment by BinayakPadhi** [comment] 2020-01-16 03:34
@Summerxia88 , is this issue fixed ? becoz I am facing same issue while pressing TAB key & its not working.

**Comment by BinayakPadhi** [comment] 2020-01-16 15:06
@imurchie , Could you please help here if you got any feasible solution.

**Comment by imurchie** [comment] 2020-01-16 16:18
Tab does nothing on the browser. Mobile Safari does not know tabs.

**Comment by BinayakPadhi** [comment] 2020-01-16 16:53
@imurchie thank you! Any other suggestion or idea to achieve this?

**Comment by imurchie** [comment] 2020-01-16 17:18
The only way that I know of getting to the next element is to find it as you would any other element. This is also a faithful model of how a user interacts with a mobile web app.

**Comment by BinayakPadhi** [comment] 2020-01-16 17:32
This is one instance how we should navigate between the elements. 

But if one button(disabled) is dependent on a text field and after filling the text field, I am trying to make the cursor focus out of the text field by pressing tab key so that the disabled button should get enabled. 
Since tab out did not happen, button is still in disable state. That's where the challenge is.

Hope you got the scenario.

**Comment by imurchie** [comment] 2020-01-16 19:32
I guess click somewhere else on the screen? Whatever might trigger the callback on data entry.

**Comment by IvanSkotar** [comment] 2020-02-01 02:45
I feel the sam e issue. After I enter a value to input field, then perform any of action as: click to anywhere (any button, input field or just to empty space), put the value to next field and so on
the entered value disappears.

**Comment by anuanambiar-git** [comment] 2020-02-08 05:55
I am also facing the same issue, entered value in one input field disappear while passing value to another input filed on the same page.

**Comment by anuanambiar-git** [comment] 2020-02-08 06:02
Facing the same issue on iOS safari browser on Simulator, the entered value in one input field disappears while passing value to another input filed on the same page.

**Comment by shibupanda** [comment] 2020-04-16 01:42
@imurchie Is there any update on this issue.
I am trying to do the same what @anuanambiar-git mentioned and same is happening in my case as well. It clear the one input field while passing or performing any action to other field.

Appium v1.17, v1.15
iOS: 12.1.4

**Comment by shibupanda** [comment] 2020-04-16 07:01
@anuanambiar-git and @IvanSkotar Is the issue still there for you.
If you have fixed it could you please share those as I am completely blocked here.

It's really appreciated if someone can unblock me.

**Comment by Rockswat** [comment] 2020-04-29 20:28
Hi, I was facing similar problem wherein sendkeys was not working and clearing text after entering in ios safari browser. Issue resolved for me after upgrading the appium version using the command npm install -g appium.

**Comment by BinayakPadhi** [comment] 2020-05-16 05:16
Hi All,
I think I got this issue. Sometimes I think we should do automation according to the application behavior not simply by running with our requirement to achieve. In my case, I just swapped the field to clear any text in it. 
For example: in a web/mobile application, you want to edit the company address field and it has zip code in separate field next to address field. First try to edit the Zip code so that the binding in between Zip code and address should get removed. then try to edit the Address field. It will be erased successfully  if you try to clear the text init and also, you can sendkeys any value init.

For me it worked. I believe it will work for you. Lets see. Give a try and post here.

**Comment by VictorDementiev** [comment] 2020-06-09 15:45
Hello,
The same issue appears for me.

os iOS
os_version 13
browser safari
device iPad Pro 12.9 2018
appium_version 1.17.0

It works fine for login page (fills correctly two fields) but doesn't work for other pages of site. When I'm filling a field and going to filling another field (or just clicking the Save button), the field clears...

Does anyone have a solution? I have no any ideas why some pages work fine and other pages don't. Can it relates to SPA technology maybe?

**Comment by VictorDementiev** [comment] 2020-06-10 09:06
I have found a solution for me.
When I'm typing some text -- SeleniumLibrary.Input Text    ${locator}    ${text}
after that I should focus the field out by clicking other element (not input, not button and etc.), just static element, e.g. HR line -- Click Element    //hr

**Comment by climbwithme** [comment] 2020-10-01 10:02
@Summerxia88  Try this as a workaround: 

elem = driver.findElement("your_By");
elem.sendKeys(text_to_key);
JavascriptExecutor js = (JavascriptExecutor) driver;
js.executeScript("arguments[0].focus(); arguments[0].blur(); return true", elem);

**Comment by MeghaIyer1988** [comment] 2021-08-02 13:35
Hello @climbwithme,  @VictorDementiev 
I am facing an issue with IOS safari , appium, automating the mobile web browser
Login page sendkeys is working fine

On certain field the sendkeys is not working - it is not entering any text in the field - locator is correct - same is working on android chrome

**Scenario - Next button gets enabled only when the age field has value.**

I tried with javascript document.getElementById - set value --> it sets the value in the  age field but then the next button doesnt get enabled.

But when I manually do it or do it on Android Chrome - it works fine.

Can you please help me.

Thank you.

**Comment by jlipps** [comment] 2021-08-03 23:08
@MeghaIyer1988  Looks like your 'next' button is keyed to some event like keyup or keypress in the field, which you could trigger in Javascript using dispatchEvent after setting the value

**Comment by mykola-mokhnach** [comment] 2021-09-05 06:17
Closed as not an issue

**Closed by mykola-mokhnach** 2021-09-05 06:17 UTC
Labels: Mobile Safari

**Comment by imtiaz-mAtallshorestaffingDotcom** [comment] 2022-01-13 21:30
Any solution guys? I am facing same issue
