### ISSUE TITLE
getting an error Carthage Binary Not found 

### ISSUE THREAD

**Issue by kommuswamy** [appium/appium#10338] opened 2018-03-12 15:15 UTC
Hi team,
I am getting error Carthage binary not found when I ran the script in Appium 1.7.2.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium:10.13.3
* Node.js version (unless using Appium.app|exe):6.11
* Mobile platform/version under test:10.3,11.2
* Real device or emulator/simulator:simulator (iPad Air)

## Link to Appium logs 

https://gist.github.com/kommuswamy/237bc4d0a05857d95460c597befc44bf

**Comment by mykola-mokhnach** [comment] 2018-03-12 16:12
this means carthage is not available in PATH. Make sure it is present in appium's process environment (https://apple.stackexchange.com/questions/140327/how-can-i-inspect-the-environment-variables-of-a-running-process)

**Comment by kommuswamy** [comment] 2018-03-13 09:55
Hi @mykola-mokhnach,

I am seeing few paths variables identified by the appium process but the Carthage location was not identified by the appium process.
what should I do to verify the appium.
I am seeing the below path variables in the mac machine
![image](https://user-images.githubusercontent.com/18289360/37334735-b451bbba-26d2-11e8-863e-58ecf180aa4a.png)

But Appium recognizing only /usr/bin ,/usr/sbin,/bin,/sbin locations.

Thanks,
Swamy.

**Comment by mykola-mokhnach** [comment] 2018-03-13 09:58
It depends on how you start the server process. Make sure it receives the correct env on startup: either inherited or custom.

**Comment by mykola-mokhnach** [comment] 2018-03-13 10:00
Duplicate of https://github.com/appium/appium/issues/10337

**Closed by mykola-mokhnach** 2018-03-13 10:00 UTC
Labels: NeedsInfo, NotABug
