### ISSUE TITLE
Failed to start WDA - 'bundleId' desired capability not provided 

### ISSUE THREAD

**Issue by FirstAM** [appium/appium#13353] opened 2019-10-03 15:22 UTC
## The problem
 When i sign manual WDA and try to start test , i get strange error 'bundleId' desired capability not provided  
Xcode was building successful

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): 1.14.2
* Desktop OS/version used to run Appium: Mac Os 10.14.5 
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS
* Real device or emulator/simulator:  Iphone XS / 13.1.2
* Appium CLI or Appium.app|exe:  Node Appium

## Details

My Appium Capability 

=> {:caps=>
  {:deviceName=>"Iphone XS",
   :platformName=>"iOS",
   :automationName=>"XCUITest",
   :wdaLaunchTimeout=>600000,
   :waitForQuiescence=>false,
   :shouldUseSingletonTestManager=>false,
   :wdaLocalPort=>8399,
   :udid=>"-",
   :platformVersion=>"12.1",
   :useNewWDA=>true,
   :newCommandTimeout=>1000,
   :noReset=>false,
   :usePrebuiltWDA=>true,
   :useXctestrunFile=>true,
   :derivedDataPath=>"/Users/user/autotest/wda_app/real/0-/Build/Products",
   :bootstrapPath=>"/Users/user/autotest/wda_app/real/-Build/Products",
   :bundleId=>"com.my.app",
   :language=>"ru",
   :app=>"versions/real/my.app-ios-v.3.14.14-build.1016.app"},
 :appium_lib=>{:port=>4733, :wait=>0, :wait_timeout=>0, :wait_interval=>0}}

## Link to Appium logs

[appium_logs_97.txt](https://github.com/appium/appium/files/3686809/appium_logs_97.txt)

**Comment by mykola-mokhnach** [comment] 2019-10-03 17:45
To me it looks like you are trying to use old WDA with new xcuitest driver. This won't work because of the protocol change.

**Comment by FirstAM** [comment] 2019-10-04 08:10
Interesting , becouse i use your WDA fork
https://github.com/appium/WebDriverAgent
And WDA app builded with last commit
`master bfed7b22 [behind 22] feat: Consider active application based on the current screen element (#214)`

**Comment by mykola-mokhnach** [comment] 2019-10-06 13:04
Perhaps some stuff from previous installation has been cached somewhere. Double check if the old stuff has been properly cleaned up from both the server and the device under test

**Comment by mykola-mokhnach** [comment] 2019-10-08 08:57
Closed as not a bug

**Closed by mykola-mokhnach** 2019-10-08 08:57 UTC
Labels: NeedsInfo, NotABug
