### ISSUE TITLE
iOS app is launching and getting crashed on real device with xcode 11 and Appium 1.13.0

### ISSUE THREAD

**Issue by vinodp6001** [appium/appium#13295] opened 2019-09-26 08:46 UTC
## The problem

When I start the Appium desktop app and run script from the eclipes. App and web driver agent app got install, My app is getting launched and crashing again from splash screen only.

## Environment

* Appium version that exhibits the issue: 1.13.0
* Desktop OS/version used to run Appium: 10
* Node.js version (unless using Appium.app|exe): 1.15.0.rc
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: ipad (6th Gen) real device

please find attached logs
[appium-server-logs.txt](https://github.com/appium/appium/files/3656832/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment] 2019-09-26 08:59
Duplicate of https://github.com/appium/appium/issues/13294

**Closed by mykola-mokhnach** 2019-09-26 08:59 UTC

**Comment by vinodp6001** [comment] 2019-09-26 09:22
@mykola-mokhnach its not an duplicate of #13294 .
In my case I am able to see the app screen in Inspector and I am able to inspect the elements but when When I try to run my test script then while running my test script app is getting install in device but  its crashing after launching

**Comment by mykola-mokhnach** [comment] 2019-09-26 09:24
Sorry, but you still must install Appium 1.15+ to work with Xcode11. We don't provide patches to older versions

**Comment by vinodp6001** [comment] 2019-09-26 09:30
@mykola-mokhnach  I have installed 1.15.0rc by npm.. For Appium desktop app as well do I need to install 1.15+ ?

**Comment by javierfuentesm** [comment] 2019-09-30 18:14
i got the same error and i have appium 1.15 ,but in the inspector i have Versión 1.13.0 (1.13.0.20190505.5) is there a newer version for the inspector i couldnt find it in your website
