### ISSUE TITLE
Cannot get nor set ios Pickerwheel value

### ISSUE THREAD

**Issue by gabrycasta96** [appium/appium#13422] opened 2019-10-14 13:47 UTC
## The problem

calling attribute/value through the rest api on a pickerwheel ios element return value null

## Environment

* Appium version (or git revision) that exhibits the issue: Appium Desktop 1.15.0
* Desktop OS/version used to run Appium: MacOs 10.15
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test: Ios 12.1
* Real device or emulator/simulator: iphone x simulator
* Appium CLI or Appium.app|exe: 1.15.0

## Code To Reproduce Issue [ Good To Have ]

-Start ios appium session
-Open calender
-Tap plus to create a new event
-Tap begin to show a picker wheel
-execute GET http://localhost:4723/wd/hub/session/{sessionId}/element/{pickerWheelId}/attribute/value
-Return null value even if in appium explorer value is shown

**Comment by mykola-mokhnach** [comment] 2019-10-14 14:01
Possible duplicate of https://github.com/appium/appium/issues/13288

**Comment by mykola-mokhnach** [comment] 2019-10-14 14:02
Please attach the full server log and the page source output

**Closed** 2019-10-17 07:00 UTC
Labels: NeedsInfo, XCUITest

**Comment by gabrycasta96** [comment] 2019-11-05 09:09
was an app bug sorry
