### ISSUE TITLE
ERROR: could not reset simulator. Then test execution hangs.

### ISSUE THREAD

**Issue by chris1248** [appium/appium#5319] opened 2015-07-01 01:21 UTC
Guys guys guys

I'm beginning to lose faith in appium. This library has failed on me twice in a row when I try to push the envelope. In my case I'm trying to run about a hundred test cases on the IOS simulator. 

This time I got another fatal error:

`error: Could not reset simulator. Leaving as is. Error: Command failed: /bin/sh -c xcrun simctl erase 58AF4973-093F-411B-B89A-28E98B78792E
An error was encountered processing the command (code=146):
Unable to erase contents and settings in current state: Booted`

Once that error appeared my simulator disappeared, and my rspec test's just hung...

Come on, is writing stable javascript code so difficult?

**Comment by Jonahss** [comment] 2015-07-01 23:26
Ah. So what happened here is we tried to erase the simulator before it actually finished shutting down. Yup, an async bug. Even if it failed, we should have retried or something rather than hanging.

Yes actually, writing async javascript code is so difficult ^.^

This is why we're working on a major rewrite in version 1.5. Using promises and async-await will solve our "callback hell" where we sometimes operate on things out of order or lose execution flow.

I've actually already written the improved function we will use for this, in the new appium-ios-simulator module under construction :)

This is a bug, but difficult to pin down seeing as it's hard to reproduce.

**Comment by Jonahss** [comment] 2015-07-01 23:27
Could you post the appium logs where it failed?

**Comment by SrinivasanTarget** [comment] 2016-05-01 12:24
closing this because of incativity

**Comment by SrinivasanTarget** [comment] 2016-05-01 12:24
@triager please close

**Closed by SrinivasanTarget** 2016-05-01 12:24 UTC
Labels: OnGoing
