### ISSUE TITLE
Some Elements missing after Update iOS 11.2 and XCode 9.2

### ISSUE THREAD

**Issue by Corji** [appium/appium#9762] opened 2017-12-07 16:08 UTC
## The problem

After the update to IOS 11.2 i had to update my XCode to 9.2 as well. After that some specific elements on the screen can't be found. Either in the appium test run nor with the inspector of appium desktop.

I can't say what was the trigger, i think it could be the xcode 9.2 update. I can't downgrade everything because then i wont be able to deploy apps for 11.2.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: 1.7.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: 11.2
* Appium CLI or Appium.app|exe:

## Details

The elements are in the Header section of the app. Its the "forward" and the "back" button. I can't find them in every screen in wich they are present. So its not only a screen problem itself. The Text between the two buttons is visible and i can find the textview without any problem. The Buttons have/had a id aswell.

## Link to Appium logs

If we need logs please ask. In the log there is the normal "NoSuchElementException", but i cant find the buttons in inspector as well.

**Comment by ochubey** [comment] 2017-12-07 16:32
@Corji have the similar issue. Check (in inspector) if element have `enabled` and `visible` attributes values equal `true`. Otherwise, they would not be intractable.

**Comment by mykola-mokhnach** [comment] 2017-12-07 19:39
Duplicate of https://github.com/appium/appium/issues/9756

**Closed by mykola-mokhnach** 2017-12-07 19:39 UTC

**Comment by Corji** [comment] 2017-12-11 07:23
Ist not the same Problem as described in #9756. Everything was fine before the update. I try to automate the **same** app, not new build, and some elements are missing. The only thing that was build new was the WebDriverAgent.

Something changed with the new ios Version or with the update of xcode. Which tool uses appium to locate or scan the ui of the app? Maybe this tool need to be updated.

@ochubey I cant check this attributes because i can't see the Buttons in inspector anymore. I have the accessability id from the readout a week ago, so i just try to locate them with the id.

**Comment by rslynch** [comment] 2017-12-12 03:50
I had some issues with the 11.2 simulato as well. Some page elements that I require to tap() now have their isHittable attributes as false where they were previously true in 11.1 at the same break point. Since the tap() function requires isHittable to be true, many of my UI tests are failing under 11.2.

I ended up downloading the old 11.1 version through Xcode preferences->components to use for now, assuming the 11.2 will hopefully be updated with a fix at some point.

**Comment by Corji** [comment] 2017-12-12 09:55
I just downgraded xcode to 9.0 and my phone to 10.3, now i can find the elements again. They are now displayed in the appium inspector and i can find them through appium automation.

@rslynch Yeah i think ios 11.2 is not ready for appium or its depending libraries to finding the elements.

@mykola-mokhnach Do you know wich component can lead to this problems?  Is it the appium-xcuitest-driver that scanns the app for the elements? Its realy bad that i cant automate my app on the newest ios version. Probably its a error in the WebDriverAgent because he will be build on the new xcode and that can lead to this errors?

**Comment by mykola-mokhnach** [comment] 2017-12-12 10:00
The tree is buult by WebDriverAgent and is based on the information provided by XCTest. So if something is changed there then it most caused by some internal stuff, that Apple added to XCTest.
