### ISSUE TITLE
bug: <title> iOS 14 getScreenShot failed(xcodebuild exited with code '65' and signal 'null')

### ISSUE THREAD

**Issue by chanchifan** [appium/appium#19411] opened 2023-11-13 03:10 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use the getScreenShot method on an iOS14 device, xcodebuild throws an exception(xcodebuild exited with code '65' and signal 'null'). We have tested devices with different systems. There is a problem on iOS 14.0-14.4.2, but it is normal on iOS 14.7.1 and above (including 15, 16, and 17).

### Expected Behavior

Use Appium Inspector to display the mobile page normally

### Minimal Reproducible Example

The easiest way to reproduce the bug is to use Appium Inspector. The system in question will report an error when connecting.

### Environment

- Operating system: macos 14.1
- Appium server version (output of `appium --version`):2.2.1
- Appium driver(s) and their version(s): xcuitest 5.8.2
- Appium plugin(s) and their version(s): images 2.1.6(but not used)
- Node.js version (output of `node --version`): v18.11.0
- `npm` version (output of `npm --version`): 8.19.2
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iOS 14.0~iOS 14.4.2
- Real device or emulator/simulator: Real device(iPhone XR\XS\XsMax\11)

### Further Information

[appium_new.log](https://github.com/appium/appium/files/13330324/appium_new.log)

**Comment by mykola-mokhnach** [comment] 2023-11-13 06:41
Duplicate of https://github.com/appium/appium/issues/19267

**Closed by mykola-mokhnach** 2023-11-13 06:41 UTC
Labels: Bug, Needs Triage
