### ISSUE TITLE
Logging issue for latest Appium

### ISSUE THREAD

**Issue by jcavar** [appium/appium#7537] opened 2016-12-14 17:16 UTC
## The problem

When using showIOSLogs capability and from version 1.6.1 iOS logs are not displayed after WebDriver is run. Before WebDriver is run logs are shown normally.

## Environment

* Appium version: 1.6.1, 1.6.2, 1.6.3
* Last Appium version that did not exhibit the issue: 1.6.0
* Desktop OS/version used to run Appium: Mac OS X El Capitan, macOS Sierra
* Node.js version (unless using Appium.app|exe): v7.0.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/jcavar/9567423b490b9f068a5327e6576e4faa

**Comment by jcavar** [comment] 2016-12-14 17:19
I am not familiar with appium source code but from my investigation it seems that:

https://github.com/appium/appium-xcuitest-driver/blob/master/lib/webdriveragent.js#L317

`this.iosLogAlreadyShown` is not reset when 

https://github.com/appium/appium-xcuitest-driver/blob/master/lib/webdriveragent.js#L359

`on('error'` condition happens

**Comment by jlipps** [comment] 2016-12-14 19:37
@jcavar there might be a problem here but I'm not sure it's what you mentioned. If you're not seeing ios logs, it's more likely the issue is somewhere in https://github.com/appium/appium-xcuitest-driver/blob/4fc5aee30f20040ca8da400135898bde7886dcc5/lib/commands/log.js. @imurchie what do you think?

**Comment by jcavar** [comment] 2016-12-14 22:10
Yeah, I am not sure, maybe. But the thing is that logs are shown until WebDriver is launched so that is why I thought it is in webdriveragent.js.

Are you able to reproduce this issue?

**Comment by jlipps** [comment] 2016-12-14 23:04
Just tried, and I could reproduce it. Once WDA started, I stopped seeing the IOS_SYSLOG_ROW messages. Presumably it is indeed a bug. We'll add to our backlog.

**Comment by codiophile** [comment] 2017-01-04 16:17
@jlipps We are facing some random failures that started after upgrading to XCUITest. The tests were stable when we were still using UIAutomation. Anyway, the lack of logs is making it hard to debug these failures, so it would be very valuable for us if we could get the logs working again. Is there anything we can do to help getting this addressed sooner?

**Comment by imurchie** [comment] 2017-01-04 17:28
If you use the latest (as yet unreleased in an Appium version) code this is fixed.

You can get it by running `npm uninstall -g appium && npm install -g appium --no-shrinkwrap`.

**Comment by codiophile** [comment] 2017-01-05 10:10
@imurchie That's cool, thanks. I will try that. Any ETA for the next Appium release?

**Comment by codiophile** [comment] 2017-02-07 17:51
@imurchie We've been running an in between version of Appium for a while and that has been causing us a lot of problems. Today I updated hoping that our issues might have been resolved, but that completely broke our tests.

So, I am wondering if it would be possible to patch 1.6.3 with only the fix for the logging? Because that's the only problem we didn't have a workaround for with 1.6.3 and it would be nice not to be affected by the new bugs that have been introduced since then.

**Comment by imurchie** [comment] 2017-02-07 18:03
There is no way, no. What are the problems you are running into?

**Comment by codiophile** [comment] 2017-02-07 19:14
@imurchie So there is an EOF problem. Multiple scenarios in a row are failing because the driver fails to start with `end of file reached (EOFError)`. Not really sure if that message is coming directly from Appium or if it's a side effect from our script, but I never saw this with 1.6.3. I've downgraded to 1.6.3, so we'll see if that solves it.

The problem I am having with the latest version is that it seems to have broken process arguments and we heavily depend on process arguments in our tests, so almost every scenario is failing.

I am currently running our suite on 1.6.3 and so far there hasn't been any failures. Therefor, I've concluded that 1.6.3 with working logging would solve our problems until there's a stable 1.6.4.

**Comment by imurchie** [comment] 2017-02-07 19:16
Can you provide some logs for the two issues? Nothing has changed with the process arguments, and I have not seen any reports of issues with EOF stuff. If I can't diagnose it then there is no way for it to bet fixed in 1.6.4.

**Comment by codiophile** [comment] 2017-02-07 19:26
Alright, I will see what I can do. I just need to make sure that those logs don't reveal things about our product that I am not allowed to reveal.

**Comment by codiophile** [comment] 2017-10-03 15:57
I just ran showIOSLog on 1.7.1 and it seems to be working. I think this issue should be closed.

**Closed** 2018-01-25 20:23 UTC
Labels: Bug, P1, XCUITest
