### ISSUE TITLE
MultiAction is executed sequentially instead of parallel.

### ISSUE THREAD

**Issue by atimofeev86** [appium/appium#16057] opened 2021-11-09 14:31 UTC
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: Real device 
* Appium CLI or Appium.app|exe: Appium CLI 

## Details

I need use multitouch to Pinch screen. I try:
OpenQA.Selenium.Appium.MultiTouch.TouchAction touchAction = new OpenQA.Selenium.Appium.MultiTouch.TouchAction(driver);
            OpenQA.Selenium.Appium.MultiTouch.MultiAction multiTouchAction = new OpenQA.Selenium.Appium.MultiTouch.MultiAction(driver);

            var a1 = touchAction.LongPress(500, 770).MoveTo(400, 550).Wait(500).Release();
            var a2 = touchAction.LongPress(600, 900).MoveTo(800, 1000).Wait(500).Release();

            multiTouchAction.Add(a1).Add(a2).Perform();

But MultiAction is executed sequentially instead of parallel.
and instead of zooming out, I get movement across the screen
![2021-11-09_16-30-04](https://user-images.githubusercontent.com/41478386/140942857-16976cc3-6d4a-4f99-a3c5-c4c56d10a8ad.gif)

## Link to Appium logs

![2021-11-09_16-29-38](https://user-images.githubusercontent.com/41478386/140942843-4041d0f5-be38-45b6-81c6-21684f6c3642.png)

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2021-11-09 14:37
Duplicate of https://github.com/appium/appium/issues/15139

**Closed by mykola-mokhnach** 2021-11-09 14:37 UTC

**Comment by jlipps** [comment] 2021-11-09 16:54
You might find this article helpful: https://appiumpro.com/editions/67-generating-touch-gestures-to-zoom-in-and-out-on-google-maps
