### ISSUE TITLE
Method sendKeys() type only first letter from all text and freezes (iOS)

### ISSUE THREAD

**Issue by Belf33** [appium/appium#8849] opened 2017-07-13 14:43 UTC
## The problem

When I sendKeys (for example - "My Text") in the native SearchField  (XCUIElementTypeSearchField) it type "M" and freeze. So Driver found element and type, but not all text.
Have anyone else similar problem?

## Environment

* Appium version 1.6.5
* iOS 10.3.2
* Real device iPhone 6 Plus
* Appium CLI

**Comment by mykola-mokhnach** [comment] 2017-07-14 05:51
Closed as duplicate of https://github.com/appium/appium/issues/8846

**Closed by mykola-mokhnach** 2017-07-14 05:51 UTC
