### ISSUE TITLE
Android Device gets Shut Down while running Test Suite

### ISSUE THREAD

**Issue by amitrparmar** [appium/appium#8531] opened 2017-05-25 09:21 UTC
## The problem

I have long running test suite. So I daily keep it run. But sometimes my android device shutdown and couldn't able to execute whole test suite.

## Environment

* Appium version:1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version: 3.10.9
* Mobile platform: Nexus 9 (Android 7.1.1)
* Real device

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

I have capture the log of my device (_using adb logcat_) and placed at below link.

https://gist.github.com/amitrparmar/e1abffc9c64fe960ae579b0eb06ed5c8

## client side error is -  

java.lang.AssertionError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 27.63 seconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'RDIAParmar', ip: '192.168.133.60', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_91'
Driver info: io.appium.java_client.android.AndroidDriver

**Comment by mykola-mokhnach** [comment] 2017-05-25 09:23
Please fill out the issue reporting form. One cannot help if there is no information about the problem

**Comment by amitrparmar** [comment] 2017-05-25 09:30
@mykola-mokhnach , I was adding the details but before I edit, you have closed my issue.

**Comment by mykola-mokhnach** [comment] 2017-05-25 09:32
Possible duplicate of https://github.com/appium/appium/issues/8312

**Comment by amitrparmar** [comment] 2017-05-26 03:56
@mykola-mokhnach , Hi, I don't thing it is duplicate of #8312. It is about the ADB, or time out. In My case, device totally gets shut down. It would be really good, if anyone can review attached log and suggest. Thanks.

**Comment by amitrparmar** [comment] 2017-05-31 12:14
Hi, I want to add my observation. This issue mostly happens in NIGHT run. Where my machine will be locked and test running process runs in background.

I also observed that whenever I execute it in my working hours then it didn't shutdown. Not sure whether it has any relation with this.

Could someone please have a look into this issue. Thanks.

**Comment by dpgraham** [comment] 2017-07-21 19:58
Are you still experiencing this issue?

**Comment by jlipps** [comment] 2017-08-04 20:00
closing due to inactivity

**Closed by jlipps** 2017-08-04 20:00 UTC
Labels: NeedsInfo
