### ISSUE TITLE
getAttribute is not working

### ISSUE THREAD

**Issue by deepika-t** [appium/appium#13462] opened 2019-10-21 06:41 UTC
## The problem

Trying to get the value of the element using getAttribute. After updating Appium to 1.15.1 its returning the value as 'null'. Even Though the element has value which could be seen through Appium Desktop inspector.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.15.1 
* Last Appium version that did not exhibit the issue (if applicable): Appium 1.13.0
* Desktop OS/version used to run Appium: version 10.14.4 (Mac)
* Node.js version (unless using Appium.app|exe):v11.10.1
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 12.4
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe: Appium CLI
<img width="650" alt="Screenshot 2019-10-21 at 11 52 56 AM" src="https://user-images.githubusercontent.com/36626567/67181149-5fbae180-f3f9-11e9-82f2-a4ff18ccfbcd.png">

**Comment by mykola-mokhnach** [comment] 2019-10-21 09:47
Duplicate of https://github.com/appium/appium/issues/13418

**Closed by mykola-mokhnach** 2019-10-21 09:47 UTC
