### ISSUE TITLE
Appium install WebDriverAgent on device fail

### ISSUE THREAD

**Issue by codexkz** [appium/appium#17511] opened 2022-09-22 07:00 UTC
Mac OS: 12.5.1 ( Monterey )
NodeJS: v12.22.11
Appium: v1.22.3 ( install by homebrew )
Xcode:  Xcode 14.0 (Build version 14A309)
Simulator : iPhone 13 ( 15.5 )

The strange thing is that I use the version of the Appium Server GUI and it works.
But I need to use cli version for my workflow.

below is XcodeLog
```
** TEST BUILD FAILED **
The following build commands failed:
	Ld /Users/wright/Library/Developer/Xcode/DerivedData/WebDriverAgent-btjqtpptcrfnbqfwuclckhvwqpfl/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/WebDriverAgentLib normal (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
(1 failure)
2022-09-22 14:45:59.893 xcodebuild[37108:2579818] [MT] IDETestOperationsObserverDebug: 0.006 elapsed -- Testing started completed.
2022-09-22 14:45:59.893 xcodebuild[37108:2579818] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2022-09-22 14:45:59.893 xcodebuild[37108:2579818] [MT] IDETestOperationsObserverDebug: 0.006 sec, +0.006 sec -- end
Test session results, code coverage, and logs:
	/Users/wright/Library/Developer/Xcode/DerivedData/WebDriverAgent-btjqtpptcrfnbqfwuclckhvwqpfl/Logs/Test/Test-WebDriverAgentRunner-2022.09.22_14-45-57-+0800.xcresult
Testing failed:
	Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture x86_64
	Test target WebDriverAgentRunner encountered an error (The bundle identifier for WebDriverAgentRunner-Runner.app couldn’t be read. The application may be damaged or incomplete: “/Users/wright/Library/Developer/Xcode/DerivedData/WebDriverAgent-btjqtpptcrfnbqfwuclckhvwqpfl/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app”.)
** TEST EXECUTE FAILED **
Testing started
    at getResponseForW3CError (/Users/wright/.nvm/versions/node/v12.22.11/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/Users/wright/.nvm/versions/node/v12.22.11/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)
```

**Comment by mykola-mokhnach** [comment] 2022-09-22 07:20
Duplicate of https://github.com/appium/appium/issues/17174

**Closed by mykola-mokhnach** 2022-09-22 07:20 UTC
