### ISSUE TITLE
iOS driver doesn't throw NoSuchElementException if element isn't found

### ISSUE THREAD

**Issue by jyotijaggasaxena** [appium/appium#13698] opened 2019-12-10 12:03 UTC
## The problem

I am using Appium 1.15.1. My scenario works fine against Android but not with iOS. I am handling a conditional pop up by checking for element and catching the 'NoSuchElementException'. When ran against iOS device, it retries till timeout(10 mins).

## Environment

* Appium version (or git revision) that exhibits the issue:1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Catalina
* Node.js version (unless using Appium.app|exe):10.15.3
* Mobile platform/version under test: iOS 12.1.4
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:CLI

## Link to Appium logs
https://gist.github.com/jyotijaggasaxena/c0a33f1af1577a7445001859700f4456

## Code To Reproduce Issue [ Good To Have ]
driver.findElement("doesn't exist")

**Comment by mykola-mokhnach** [comment] 2019-12-10 12:05
Sorry, I cannot understand what the problem is. NoSuchElementException must not be thrown if implicit timeout is still in progress.

**Comment by mykola-mokhnach** [comment] 2019-12-13 11:20
Closed as not an issue

**Closed by mykola-mokhnach** 2019-12-13 11:20 UTC
Labels: Mobile Safari, NeedsInfo
