### ISSUE TITLE
iOS application crashes on launch when test starts 

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#13164] opened 2019-09-02 08:03 UTC
## The problem
After starting a test, the application crashes immediately.
The iOS device log is showing a weird logs which I cannot understand the root cause. 
 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.2
* Last Appium version that did not exhibit the issue (if applicable): 1.11.0
* Desktop OS/version used to run Appium: Desktop
* Node.js version (unless using Appium.app|exe): 8.12.0
* Npm or Yarn package manager: yarn
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: cli

## Details
The device log is this:
http://assets-production.applicaster.com.s3.amazonaws.com/qa/zapp_qa/manual/boaz/appium.log

## Link to Appium logs
http://assets-production.applicaster.com.s3.amazonaws.com/qa/zapp_qa/manual/boaz/appium_server.log

## Code To Reproduce Issue [ Good To Have ]
Start test on iOS Simulator.

**Comment by BoazWarshawsky** [comment] 2019-09-02 13:17
My test is throwing these errors too:
[12:52:37] ============================= test session starts ==============================
[12:52:37] platform darwin -- Python 3.7.3, pytest-4.4.0, py-1.8.0, pluggy-0.12.0 -- /Users/distiller/.asdf/installs/python/3.7.3/bin/python3.7
[12:52:37] cachedir: .pytest_cache
[12:52:37] metadata: {'Python': '3.7.3', 'Platform': 'Darwin-18.5.0-x86_64-i386-64bit', 'Packages': {'pytest': '4.4.0', 'py': '1.8.0', 'pluggy': '0.12.0'}, 'Plugins': {'html': '1.20.0', 'metadata': '1.8.0'}, 'CI': 'true', 'CIRCLE_PROJECT_USERNAME': 'applicaster', 'CIRCLE_PROJECT_REPONAME': 'Zapp-iOS', 'CIRCLE_BRANCH': 'update_ui_tests_app', 'CIRCLE_SHA1': 'a17220da80a4570de78c2035e8acae8ba30b0516', 'CIRCLE_REPOSITORY_URL': 'git@github.com:applicaster/Zapp-iOS.git', 'CIRCLE_COMPARE_URL': 'https://github.com/applicaster/Zapp-iOS/compare/45be821af01e...a17220da80a4', 'CIRCLE_BUILD_URL': 'https://circleci.com/gh/applicaster/Zapp-iOS/46167', 'CIRCLE_BUILD_NUM': '46167', 'CIRCLE_PREVIOUS_BUILD_NUM': '46164', 'CI_PULL_REQUESTS': 'https://github.com/applicaster/Zapp-iOS/pull/2168', 'CI_PULL_REQUEST': 'https://github.com/applicaster/Zapp-iOS/pull/2168', 'CIRCLE_USERNAME': 'BoazWarshawsky', 'CIRCLE_NODE_TOTAL': '1', 'CIRCLE_NODE_INDEX': '0'}
[12:52:37] rootdir: /Users/distiller/Zapp-iOS/ZappAutomationInfrastructure
[12:52:37] plugins: html-1.20.0, metadata-1.8.0
[12:52:38] collecting ... collected 32 items / 21 deselected / 11 selected
[12:52:38] 
[Xcode] 2019-09-02 05:58:04.647136-0700 WebDriverAgentRunner-Runner[72888:303370] Enqueue Failure: Failure to determine system application: Error Domain=com.apple.dt.XCTest.XCTFuture Code=1000 "Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeSystemAppApplication' for Device system-wide element'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeSystemAppApplication' for Device system-wide element'.} /Users/distiller/.asdf/installs/nodejs/8.12.0/.npm/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2019-09-02 05:58:04.647756-0700 WebDriverAgentRunner-Runner[72888:303370] Enqueue Failure: Failure to determine system application: (null) /Users/distiller/.asdf/installs/nodejs/8.12.0/.npm/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2019-09-02 05:59:09.657041-0700 WebDriverAgentRunner-Runner[72888:303370] Enqueue Failure: Failure getting list of active applications: Error Domain=com.apple.dt.XCTest.XCTFuture Code=1000 "Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeFocusedApplications' for (null)'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeFocusedApplications' for (null)'.} /Users/distiller/.asdf/installs/nodejs/8.12.0/.npm/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2019-09-02 05:59:09.657773-0700 WebDriverAgentRunner-Runner[72888:303370] Enqueue Failure: Failure getting list of active applications: (null) /Users/distiller/.asdf/installs/nodejs/8.12.0/.npm/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[35m[Xcode][39m 2019-09-02 06:00:14.769827-0700 WebDriverAgentRunner-Runner[72888:303370] Enqueue Failure: Failure to determine system application: Error Domain=com.apple.dt.XCTest.XCTFuture Code=1000 "Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeSystemAppApplication' for Device system-wide element'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeSystemAppApplication' for Device system-wide element'.} /Users/distiller/.asdf/installs/nodejs/8.12.0/.npm/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[35m[Xcode][39m 
[35m[Xcode][39m 2019-09-02 06:00:14.770454-0700 WebDriverAgentRunner-Runner[72888:303370] Enqueue Failure: Failure to determine system application: (null) /Users/distiller/.asdf/installs/nodejs/8.12.0/.npm/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[35m[Xcode][39m 
[35m[Xcode][39m 2019-09-02 06:01:19.782479-0700 WebDriverAgentRunner-Runner[72888:303370] Enqueue Failure: Failure getting list of active applications: Error Domain=com.apple.dt.XCTest.XCTFuture Code=1000 "Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeFocusedApplications' for (null)'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeFocusedApplications' for (null)'.} /Users/distiller/.asdf/installs/nodejs/8.12.0/.npm/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[35m[Xcode][39m 
[35m[Xcode][39m 2019-09-02 06:01:19.783147-0700 WebDriverAgentRunner-Runner[72888:303370] Enqueue Failure: Failure getting list of active applications: (null) /Users/distiller/.asdf/installs/nodejs/8.12.0/.npm/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[35m[Xcode][39m 
[35m[Xcode][39m     t =   322.56s Unable to monitor event loop
[35m[Xcode][39m     t =   322.57s Unable to monitor animations
[35m[Xcode][39m 
[35m[Xcode][39m     t =   332.69s Terminate com.featureapp:72891


The crash might coming from WebDriverAgentRunner?

**Comment by BoazWarshawsky** [comment] 2019-09-03 11:38
@mykola-mokhnach hi,
can you please help me with this issue?
THANKS!

**Comment by KazuCocoa** [comment] 2019-09-03 13:25
Could you update http://assets-production.applicaster.com.s3.amazonaws.com/qa/zapp_qa/manual/boaz/appium_server.log again?
I could see a blank page.

**Comment by BoazWarshawsky** [comment] 2019-09-03 13:37
@KazuCocoa please retry now.
thx

**Comment by KazuCocoa** [comment] 2019-09-03 14:13
After establishing the session, appium said as below.
Did your app run properly without error? 

```
[debug] [35m[XCUITest][39m Executing command 'getAlertText'
[debug] [35m[WD Proxy][39m Matched '/alert/text' to command name 'getAlertText'
[debug] [35m[WD Proxy][39m Proxying [GET /alert/text] to [GET http://localhost:8100/session/F75B695F-1364-4D9B-8B8E-146EA528CCF4/alert/text] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: "{\n  \"value\" : \"The application under test with bundle id 'com.featureapp' is not running, possibly crashed\",\n  \"sessionId\" : \"F75B695F-1364-4D9B-8B8E-146EA528CCF4\",\n  \"status\" : 889\n}"
[debug] [35m[MJSONWP][39m Matched JSONWP error code 889 to UnknownError
[debug] [35m[W3C (92f62100)][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: The application under test with bundle id 'com.featureapp' is not running, possibly crashed
[debug] [35m[W3C (92f62100)][39m     at errorFromMJSONWPStatusCode (/Users/distiller/.asdf/installs/nodejs/8.12.0/.npm/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:789:10)
[debug] [35m[W3C (92f62100)][39m     at ProxyRequestError.errorFromMJSONWPStatusCode [as getActualError] (/Users/distiller/.asdf/installs/nodejs/8.12.0/.npm/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:683:14)
[debug] [35m[W3C (92f62100)][39m     at JWProxy.getActualError [as command] (/Users/distiller/.asdf/installs/nodejs/8.12.0/.npm/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:237:19)
[debug] [35m[W3C (92f62100)][39m     at <anonymous>
[35m[HTTP][39m [37m<-- GET /wd/hub/session/92f62100-73ee-416a-9722-4bde0f5a3f46/alert/text [39m[31m500[39m [90m49 ms - 1020[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/9
```

Appium handled as below after the above repeated error messages. So, the cause was your app or between XCTest framework _XC_kAXXCAttributeSystemAppApplication_ and your app, I assume.

```
[35m[HTTP][39m [37m<-- POST /wd/hub/session/92f62100-73ee-416a-9722-4bde0f5a3f46/element [39m[33m404[39m [90m18 ms - 439[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/92f62100-73ee-416a-9722-4bde0f5a3f46/screenshot[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (92f62100)][39m Calling AppiumDriver.getScreenshot() with args: ["92f62100-73ee-416a-9722-4bde0f5a3f46"]
[debug] [35m[XCUITest][39m Executing command 'getScreenshot'
[debug] [35m[XCUITest][39m Taking screenshot with WDA
[debug] [35m[WD Proxy][39m Matched '/screenshot' to command name 'getScreenshot'
[debug] [35m[WD Proxy][39m Proxying [GET /screenshot] to [GET http://localhost:8100/session/F75B695F-1364-4D9B-8B8E-146EA528CCF4/screenshot] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: "{\n  \"value\" : 
```

**Comment by mykola-mokhnach** [comment] 2019-09-06 08:06
Closed as not an issue

**Closed by mykola-mokhnach** 2019-09-06 08:06 UTC
Labels: NeedsInfo, NotABug
