### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70

### ISSUE THREAD

**Issue by sampathkumar537** [appium/appium#13268] opened 2019-09-20 09:50 UTC
Xcode10.3
and appium 6.10.2
node v12.6.0
mac : 10.14.6
we face issue :
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70

Any can help me out from this issue. Am stayed for an day with this issue

**Comment by mykola-mokhnach** [comment] 2019-09-20 09:51
Duplicate of https://github.com/appium/appium/issues/13267

**Closed by mykola-mokhnach** 2019-09-20 09:51 UTC
