### ISSUE TITLE
Appium2.0: InvalidArgumentError: 'automationName' can't be blank

### ISSUE THREAD

**Issue by atzdmyp** [appium/appium#17779] opened 2022-11-16 09:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i run script, i got these error:
Stacktrace:
InvalidArgumentError: 'automationName' can't be blank
    at processCapabilities (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:330:13)
    at parseCapsForInnerDriver (/usr/local/lib/node_modules/appium/lib/utils.js:134:21)
    at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:241:26)
    at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:126:9)
    at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:143:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:668:16)
    at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:762:16)
    at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:684:17)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:346:19)

but when i use 'appium' prefix for capabilities, will be no error. who can help me.

### Expected Behavior

create session

### Minimal Reproducible Example

it's my code:

from appium import webdriver

desired_cap = {
                "platformName": "iOS",
                "appium:options":{
                    "platformVersion": platform_version,
                    "udid": udid,
                    "deviceName": device_name,
                    "bundleId": bundle_id,
                    "automationName": "XCUITest",
                    "xcodeOrgId": xcode_org_id,
                    "xcodeSigningId": xcode_signing_id,
                    "wdaLocalPort": wda_local_port,
                    "derivedDataPath": derived_data_path,
                    "appPushTimeout": 150000,
                }
            }
driver = webdriver.Remote(
                "/usr/local/bin/appium -a 127.0.0.1 -p 4723" , desired_cap
            )

### Environment

- Operating system: mac os monterey 12.1
- env
  - Appium version : 2.0.0-beta.46
  - Node.js version : v18.12.1
  - `npm` version :  8.19.2
  - Last `appium` version which did _not_ exhibit the problem: 2.0.0-beta.46
- Real device : iphone11

### Futher Information

[35m[Appium][39m Welcome to Appium v2.0.0-beta.46
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m, usePlugins: [ [32m'images'[39m ] }
[35m[Appium][39m Attempting to load driver xcuitest...
[debug] [35m[Appium][39m Requiring driver at /Users/username/.appium/node_modules/appium-xcuitest-driver
[35m[Appium][39m Attempting to load driver uiautomator2...
[debug] [35m[Appium][39m Requiring driver at /Users/username/.appium/node_modules/appium-uiautomator2-driver
[35m[Appium][39m Appium REST http interface listener started on 127.0.0.1:4723
[35m[Appium][39m Available drivers:
[35m[Appium][39m   - xcuitest@4.12.2 (automationName 'XCUITest')
[35m[Appium][39m   - uiautomator2@2.10.2 (automationName 'UiAutomator2')
[35m[Appium][39m No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[debug] [35m[HTTP][39m Request idempotency key: 2ef8aa61-9343-4dcf-af2f-5a6b75ac4e7c
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/session[39m
[35m[HTTP][39m [90m{"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"iOS","appium:options":{"platformVersion":"15.6.1","udid":"00008030-0006083902A2802E","deviceName":"iPhone11","bundleId":"com.beeblio.app","automationName":"XCUITest","xcodeOrgId":"xcodeOrgId","xcodeSigningId":"iPhone Developer","wdaLocalPort":8100,"derivedDataPath":"/Users/username/PycharmProjects/ios/docs/docs0","appPushTimeout":150000,"wdaLaunchTimeout":350000,"useNewWDA":false}}}}[39m
[debug] [35m[AppiumDriver@6dfd][39m Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{}],"alwaysMatch":{"platformName":"iOS","appium:options":{"platformVersion":"15.6.1","udid":"00008030-0006083902A2802E","deviceName":"iPhone11","bundleId":"com.beeblio.app","automationName":"XCUITest","xcodeOrgId":"xcodeOrgId","xcodeSigningId":"iPhone Developer","wdaLocalPort":8100,"derivedDataPath":"/Users/username/PycharmProjects/ios/docs/docs0","appPushTimeout":150000,"wdaLaunchTimeout":350000,"useNewWDA":false}}}]
[debug] [35m[AppiumDriver@6dfd][39m Event 'newSessionRequested' logged at 1668588007847 (16:40:07 GMT+0800 (China Standard Time))
[35m[Appium][39m Could not parse W3C capabilities: 'automationName' can't be blank
[debug] [35m[AppiumDriver@6dfd][39m Event 'newSessionStarted' logged at 1668588007852 (16:40:07 GMT+0800 (China Standard Time))
[debug] [35m[AppiumDriver@6dfd][39m Encountered internal error running command: InvalidArgumentError: 'automationName' can't be blank
[debug] [35m[AppiumDriver@6dfd][39m     at processCapabilities (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:330:13)
[debug] [35m[AppiumDriver@6dfd][39m     at parseCapsForInnerDriver (/usr/local/lib/node_modules/appium/lib/utils.js:134:21)
[debug] [35m[AppiumDriver@6dfd][39m     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:241:26)
[debug] [35m[AppiumDriver@6dfd][39m     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:126:9)
[debug] [35m[AppiumDriver@6dfd][39m     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:143:15)
[debug] [35m[AppiumDriver@6dfd][39m     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [35m[AppiumDriver@6dfd][39m     at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:668:16)
[debug] [35m[AppiumDriver@6dfd][39m     at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:762:16)
[debug] [35m[AppiumDriver@6dfd][39m     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:684:17)
[debug] [35m[AppiumDriver@6dfd][39m     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:346:19)
[35m[HTTP][39m [37m<-- POST /session [39m[33m400[39m [90m29 ms - 1207[39m
[35m[HTTP][39m [90m[39m
[35m[Appium][39m Received SIGINT - shutting down
[debug] [35m[AppiumDriver@6dfd][39m There are no active sessions for cleanup
[35m[HTTP][39m Waiting until the server is closed
[35m[HTTP][39m Received server close event

**Comment by mykola-mokhnach** [comment] 2022-11-16 11:24
It looks like the server does not support parsing of automationName from `appium:options` map. @jlipps Is it the expected behaviour or a bug?

**Comment by jlipps** [comment] 2022-11-16 20:09
seems like a bug, i think automationName should be able to go inside `appium:options`

**Comment by garg3133** [comment] 2022-11-18 08:18
I'm also facing the same issue. According to the documentation [here](https://appium.github.io/appium/docs/en/2.0/guides/caps/#appiumoptions), we should be able to put `automationName` inside `appium:options` but when I run using the same capability example as given on the doc attached above, I get the following error:
![image](https://user-images.githubusercontent.com/39924567/202653896-2d278e8f-8bb7-46fb-8070-d56a72f7f29b.png)

While moving `automationName` to outside of `appium:options` and adding a `appium:` prefix to it seems to be working fine.

**Comment by jlipps** [comment] 2022-11-18 19:33
the linked PR has the fix and this issue will be closed when it's merged. subsequent releases of appium won't have the bug.

**Closed** 2022-11-21 04:44 UTC
Labels: Bug

**Comment by sonugupta029** [comment] 2023-07-26 08:09
@mykola-mokhnach is the fix released with Appium version 2.0.1? I am still facing same issue when using below code:
```
val options = XCUITestOptions()
options.setAutomationName("XCUITest")
```
[Appium] Could not parse W3C capabilities: 'automationName' can't be blank

Works fine if I use Desired Capabilities
```
val capabilities = DesiredCapabilities() 
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest")
```

My appium server version is 2.0.1. 

Please let me know if I am missing something.

**Comment by agray** [comment] 2023-08-04 09:37
has this fix been released?

**Comment by agray** [comment] 2023-08-04 11:04
> I'm also facing the same issue. According to the documentation [here](https://appium.github.io/appium/docs/en/2.0/guides/caps/#appiumoptions), we should be able to put `automationName` inside `appium:options` but when I run using the same capability example as given on the doc attached above, I get the following error: ![image](https://user-images.githubusercontent.com/39924567/202653896-2d278e8f-8bb7-46fb-8070-d56a72f7f29b.png)
> 
> While moving `automationName` to outside of `appium:options` and adding a `appium:` prefix to it seems to be working fine.

Tried this as well.  Doesn't work.  Appium 2.0 is BROKEN on Apple.

![image](https://github.com/appium/appium/assets/118102/df4ba927-6a6b-4645-9053-0a8bb1038b7f)

**Comment by agray** [comment] 2023-08-04 11:07
@atzdmyp Please reopen.
