### ISSUE TITLE
Appium script is very slow when working on camera view on Android

### ISSUE THREAD

**Issue by tandt53** [appium/appium#13774] opened 2019-12-27 10:16 UTC
## The problem

Appium script is very slow when working on camera view on Android

## Environment

* Node.js version (unless using Appium.app|exe): 8.10.0
* Npm or Yarn package manager: 6.12.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: appium 
* Appium java-client: 7.2.0
* Appium server: 1.15.1

## Details

Our application is native android app that developed using Kotlin.
There's scanning QR code function, so there need to have some script to verify those functions.
Text or buttons are placed above a camera view. I donot have any idea why appium work very slow.

Exmaple: checking element displayed takes longer than 20 secs, Click on element take > 50 secs
![image](https://user-images.githubusercontent.com/22423679/71512623-ab8e7900-28c9-11ea-87e1-1e4f2d24ebf1.png)

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element
[HTTP] {"using":"xpath","value":"//android.widget.TextView[@text='Cấp quyền truy cập Máy ảnh']"}
[debug] [W3C (0226cfd7)] Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.TextView[@text='Cấp quyền truy cập Máy ảnh']","0226cfd7-eca9-489d-837f-c6cd3e9227bd"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 20000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/fb4caa21-3ff0-48b9-a319-8edca1e9fc47/element] with body: {"strategy":"xpath","selector":"//android.widget.TextView[@text='Cấp quyền truy cập Máy ảnh']","context":"","multiple":false}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"fb4caa21-3ff0-48b9-a319-8edca1e9fc47","value":{"ELEMENT":"a467ea0d-e4e3-4517-a1d9-e25cac4d7e9d","element-6066-11e4-a52e-4f735466cecf":"a467ea0d-e4e3-4517-a1d9-e25cac4d7e9d"}}
[debug] [W3C (0226cfd7)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"a467ea0d-e4e3-4517-a1d9-e25cac4d7e9d","ELEMENT":"a467ea0d-e4e3-4517-a1d9-e25cac4d7e9d"}
[HTTP] <-- POST /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element 200 10477 ms - 137
[HTTP] 
[HTTP] --> GET /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element/a467ea0d-e4e3-4517-a1d9-e25cac4d7e9d/displayed
[HTTP] {}
[debug] [W3C (0226cfd7)] Calling AppiumDriver.elementDisplayed() with args: ["a467ea0d-e4e3-4517-a1d9-e25cac4d7e9d","0226cfd7-eca9-489d-837f-c6cd3e9227bd"]
[debug] [WD Proxy] Matched '/element/a467ea0d-e4e3-4517-a1d9-e25cac4d7e9d/attribute/displayed' to command name 'getAttribute'
[debug] [WD Proxy] Proxying [GET /element/a467ea0d-e4e3-4517-a1d9-e25cac4d7e9d/attribute/displayed] to [GET http://localhost:8200/wd/hub/session/fb4caa21-3ff0-48b9-a319-8edca1e9fc47/element/a467ea0d-e4e3-4517-a1d9-e25cac4d7e9d/attribute/displayed] with body: {}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"fb4caa21-3ff0-48b9-a319-8edca1e9fc47","value":"true"}
[debug] [W3C (0226cfd7)] Responding to client with driver.elementDisplayed() result: true
[HTTP] <-- GET /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element/a467ea0d-e4e3-4517-a1d9-e25cac4d7e9d/displayed 200 20127 ms - 14
[HTTP] 
[HTTP] --> GET /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element/a467ea0d-e4e3-4517-a1d9-e25cac4d7e9d/displayed
[HTTP] {}
[debug] [W3C (0226cfd7)] Calling AppiumDriver.elementDisplayed() with args: ["a467ea0d-e4e3-4517-a1d9-e25cac4d7e9d","0226cfd7-eca9-489d-837f-c6cd3e9227bd"]
[debug] [WD Proxy] Matched '/element/a467ea0d-e4e3-4517-a1d9-e25cac4d7e9d/attribute/displayed' to command name 'getAttribute'
[debug] [WD Proxy] Proxying [GET /element/a467ea0d-e4e3-4517-a1d9-e25cac4d7e9d/attribute/displayed] to [GET http://localhost:8200/wd/hub/session/fb4caa21-3ff0-48b9-a319-8edca1e9fc47/element/a467ea0d-e4e3-4517-a1d9-e25cac4d7e9d/attribute/displayed] with body: {}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"fb4caa21-3ff0-48b9-a319-8edca1e9fc47","value":"true"}
[debug] [W3C (0226cfd7)] Responding to client with driver.elementDisplayed() result: true
[HTTP] <-- GET /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element/a467ea0d-e4e3-4517-a1d9-e25cac4d7e9d/displayed 200 20182 ms - 14
[HTTP] 
[HTTP] --> POST /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element
[HTTP] {"using":"xpath","value":"//android.widget.TextView[@text='Cấp quyền truy cập Máy ảnh']"}
[debug] [W3C (0226cfd7)] Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.TextView[@text='Cấp quyền truy cập Máy ảnh']","0226cfd7-eca9-489d-837f-c6cd3e9227bd"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 20000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/fb4caa21-3ff0-48b9-a319-8edca1e9fc47/element] with body: {"strategy":"xpath","selector":"//android.widget.TextView[@text='Cấp quyền truy cập Máy ảnh']","context":"","multiple":false}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"fb4caa21-3ff0-48b9-a319-8edca1e9fc47","value":{"ELEMENT":"b99758a5-9b97-47e5-9a2a-56a46eda11cc","element-6066-11e4-a52e-4f735466cecf":"b99758a5-9b97-47e5-9a2a-56a46eda11cc"}}
[debug] [W3C (0226cfd7)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"b99758a5-9b97-47e5-9a2a-56a46eda11cc","ELEMENT":"b99758a5-9b97-47e5-9a2a-56a46eda11cc"}
[HTTP] <-- POST /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element 200 10623 ms - 137
[HTTP] 
[HTTP] --> GET /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element/b99758a5-9b97-47e5-9a2a-56a46eda11cc/displayed
[HTTP] {}
[debug] [W3C (0226cfd7)] Calling AppiumDriver.elementDisplayed() with args: ["b99758a5-9b97-47e5-9a2a-56a46eda11cc","0226cfd7-eca9-489d-837f-c6cd3e9227bd"]
[debug] [WD Proxy] Matched '/element/b99758a5-9b97-47e5-9a2a-56a46eda11cc/attribute/displayed' to command name 'getAttribute'
[debug] [WD Proxy] Proxying [GET /element/b99758a5-9b97-47e5-9a2a-56a46eda11cc/attribute/displayed] to [GET http://localhost:8200/wd/hub/session/fb4caa21-3ff0-48b9-a319-8edca1e9fc47/element/b99758a5-9b97-47e5-9a2a-56a46eda11cc/attribute/displayed] with body: {}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"fb4caa21-3ff0-48b9-a319-8edca1e9fc47","value":"true"}
[debug] [W3C (0226cfd7)] Responding to client with driver.elementDisplayed() result: true
[HTTP] <-- GET /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element/b99758a5-9b97-47e5-9a2a-56a46eda11cc/displayed 200 20256 ms - 14
[HTTP] 
[HTTP] --> GET /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element/b99758a5-9b97-47e5-9a2a-56a46eda11cc/text
[HTTP] {}
[W3C (0226cfd7)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element/b99758a5-9b97-47e5-9a2a-56a46eda11cc/text' to command name 'getText'
[debug] [WD Proxy] Proxying [GET /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element/b99758a5-9b97-47e5-9a2a-56a46eda11cc/text] to [GET http://localhost:8200/wd/hub/session/fb4caa21-3ff0-48b9-a319-8edca1e9fc47/element/b99758a5-9b97-47e5-9a2a-56a46eda11cc/text] with body: {}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"fb4caa21-3ff0-48b9-a319-8edca1e9fc47","value":"Cấp quyền truy cập Máy ảnh"}
[WD Proxy] Replacing sessionId fb4caa21-3ff0-48b9-a319-8edca1e9fc47 with 0226cfd7-eca9-489d-837f-c6cd3e9227bd
[HTTP] <-- GET /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element/b99758a5-9b97-47e5-9a2a-56a46eda11cc/text 200 20117 ms - 98
[HTTP] 
[HTTP] --> POST /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element
[HTTP] {"using":"xpath","value":"//android.widget.TextView[@text='Để quét mã QR, mã vạch, VinID cần được cấp quyền truy cập Máy ảnh.']"}
[debug] [W3C (0226cfd7)] Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.TextView[@text='Để quét mã QR, mã vạch, VinID cần được cấp quyền truy cập Máy ảnh.']","0226cfd7-eca9-489d-837f-c6cd3e9227bd"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 20000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/fb4caa21-3ff0-48b9-a319-8edca1e9fc47/element] with body: {"strategy":"xpath","selector":"//android.widget.TextView[@text='Để quét mã QR, mã vạch, VinID cần được cấp quyền truy cập Máy ảnh.']","context":"","multiple":false}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"fb4caa21-3ff0-48b9-a319-8edca1e9fc47","value":{"ELEMENT":"88a63a90-f3b8-4bee-ae01-1b45b6939f8f","element-6066-11e4-a52e-4f735466cecf":"88a63a90-f3b8-4bee-ae01-1b45b6939f8f"}}
[debug] [W3C (0226cfd7)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"88a63a90-f3b8-4bee-ae01-1b45b6939f8f","ELEMENT":"88a63a90-f3b8-4bee-ae01-1b45b6939f8f"}
[HTTP] <-- POST /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element 200 10531 ms - 137
[HTTP] 
[HTTP] --> GET /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element/88a63a90-f3b8-4bee-ae01-1b45b6939f8f/displayed
[HTTP] {}
[debug] [W3C (0226cfd7)] Calling AppiumDriver.elementDisplayed() with args: ["88a63a90-f3b8-4bee-ae01-1b45b6939f8f","0226cfd7-eca9-489d-837f-c6cd3e9227bd"]
[debug] [WD Proxy] Matched '/element/88a63a90-f3b8-4bee-ae01-1b45b6939f8f/attribute/displayed' to command name 'getAttribute'
[debug] [WD Proxy] Proxying [GET /element/88a63a90-f3b8-4bee-ae01-1b45b6939f8f/attribute/displayed] to [GET http://localhost:8200/wd/hub/session/fb4caa21-3ff0-48b9-a319-8edca1e9fc47/element/88a63a90-f3b8-4bee-ae01-1b45b6939f8f/attribute/displayed] with body: {}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"fb4caa21-3ff0-48b9-a319-8edca1e9fc47","value":"true"}
[debug] [W3C (0226cfd7)] Responding to client with driver.elementDisplayed() result: true
[HTTP] <-- GET /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element/88a63a90-f3b8-4bee-ae01-1b45b6939f8f/displayed 200 20217 ms - 14
[HTTP] 
[HTTP] --> GET /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element/88a63a90-f3b8-4bee-ae01-1b45b6939f8f/displayed
[HTTP] {}
[debug] [W3C (0226cfd7)] Calling AppiumDriver.elementDisplayed() with args: ["88a63a90-f3b8-4bee-ae01-1b45b6939f8f","0226cfd7-eca9-489d-837f-c6cd3e9227bd"]
[debug] [WD Proxy] Matched '/element/88a63a90-f3b8-4bee-ae01-1b45b6939f8f/attribute/displayed' to command name 'getAttribute'
[debug] [WD Proxy] Proxying [GET /element/88a63a90-f3b8-4bee-ae01-1b45b6939f8f/attribute/displayed] to [GET http://localhost:8200/wd/hub/session/fb4caa21-3ff0-48b9-a319-8edca1e9fc47/element/88a63a90-f3b8-4bee-ae01-1b45b6939f8f/attribute/displayed] with body: {}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"fb4caa21-3ff0-48b9-a319-8edca1e9fc47","value":"true"}
[debug] [W3C (0226cfd7)] Responding to client with driver.elementDisplayed() result: true
[HTTP] <-- GET /wd/hub/session/0226cfd7-eca9-489d-837f-c6cd3e9227bd/element/88a63a90-f3b8-4bee-ae01-1b45b6939f8f/displayed 200 20151 ms - 14

**Comment by mykola-mokhnach** [comment] 2019-12-27 16:13
Possible duplicate of https://github.com/appium/appium/issues/13694

**Comment by mykola-mokhnach** [comment] 2019-12-27 16:14
Elements selection is done by UiAutomator2. Unfortunately, there is nothing we can do there from Appium side.

**Comment by mykola-mokhnach** [comment] 2019-12-31 08:56
Closed as third party issue

**Closed by mykola-mokhnach** 2019-12-31 08:56 UTC
Labels: ThirdParty, UIAutomator2
