### ISSUE TITLE
bug: can't find webView but a android.widget.FrameLayout for chrome

### ISSUE THREAD

**Issue by liu6x6** [appium/appium#20334] opened 2024-07-05 07:04 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi there
i am launch the chrome by the packageId instead of using the broswerName, 
Sometimes i can find the webView.but some times i cannot find the webView, it's like below

```xml
<android.widget.FrameLayout index="1" package="com.android.chrome" class="android.widget.FrameLayout" text="" content-desc="Web View" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="true" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,81][1080,2196]" displayed="true" />

```

### Expected Behavior

it's should be a webView all the time

### Minimal Reproducible Example

just using the appium inspector could reproduce this issue

### Environment

- Operating system: windows10
- Appium server version (output of `appium --version`):2.11.0
- Appium driver(s) and their version(s) (`appium driver list`): uiautomator2
- Appium plugin(s) and their version(s) (`appium plugin list`): 
- Node.js version (output of `node --version`): nodejs 18
- `npm` version (output of `npm --version`):10.2.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: android 14 / android 13
- Real device or emulator/simulator: device 

### Link to Appium Logs

https://gist.github.com/liu6x6/9b8fe2986f38934453021a67d9c33dd5

**Comment by liu6x6** [comment] 2024-07-05 07:05
![MicrosoftTeams-image](https://github.com/appium/appium/assets/5752274/3c23ddb7-c5fc-45cc-a242-e23824c1dcdc)
add a photo

**Comment by mykola-mokhnach** [comment] 2024-07-05 09:50
Duplicate of https://github.com/appium/appium/issues/20311

**Closed by mykola-mokhnach** 2024-07-05 09:50 UTC
Labels: Bug, Needs Triage
