### ISSUE TITLE
preventWDAAttachments not working if fullReset is true

### ISSUE THREAD

**Issue by h3dkandi** [appium/appium#7687] opened 2017-01-12 15:41 UTC
## The problem

When fullReset cap is set the preventWDAAttachments cap is not working.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.3 (REV ea239916f56cc63c13ebf527fc116a606f102792)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.12.2
* Node.js version (unless using Appium.app|exe): 7.2.1
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
The tests were Safari web tests.
```
{
    "fullReset": true,
    "preventWDAAttachments": true
}
```
Wda creates a folder ~/Library/Developer/Xcode/DerivedData/WebDriverAgent-UUID/Logs/Test/Attachments

Which is a problem because the files in that folder are not chmod-ed properly and cant be override or deleted. This seems to make webdriver unable to start a session(because it probably needs to override them?), hence my `"preventWDAAttachments": true` option which doesn't work if I add `"fullReset": true`.
It could be that it can't start safari or something. If I click the safari the iproxy hooks.

Also after the fullReset broke the stuff I can't figure how to fix it. Only removing the full reset and deleting the webdriveragent folder doesn't seem to work. I did once succeed to fix it but don't know what exactly fixed it.
## Link to Appium logs

The [Appium Log gist](https://gist.github.com/h3dkandi/a7fe2960eaab4745aeb52b22b46c83ec)

**Comment by mykola-mokhnach** [comment] 2017-01-12 16:06
What do you see in device logs when WDA tries to execute Safari? 

> Which is a problem because the files in that folder are not chmod-ed properly and cant be override or deleted

The idea is just to prevent XCTest to create new files. And this is more like a workaround rather than a solution. You may consider using _clearSystemFiles_ capability instead , which simply deletes the content of derived data folder on every driver init

**Comment by h3dkandi** [comment] 2017-01-13 08:33
Sorry for my ignorance but where should I search for the device logs. I am afraid that if they are in the webdriveragent/log folder they are now wiped.
 
Today it all seems to work well - this is without the "fullReset": true.
I tried the reset option in hopes that it will run a "clean" Safari with no tabs - currently they accumulate. I wouldn't want to break the setup again unless the fullReset option does exactly that and I don't believe it does.

**Comment by mykola-mokhnach** [comment] 2017-01-13 09:52
> PS: About the clearSystemFiles capability I haven't seen it in the git docs.

Yup, somebody has overlooked to document it. Check the changelist for the version 1.6.1:
https://github.com/appium/appium/blob/db58c998ea538829b70e0d1d52cbebc31d6600cb/CHANGELOG.md

Regarding closing tabs in Safari - you may override webdriver's quit method and add something like this code snippet there:

```java
  public static void quit(AppiumDriver driver) {
      Iterator i =  driver.getWindowHandles().iterator();

        while(i.hasNext()) {
          String windowHandle = (String) i.next();
          driver.switchTo().window(windowHandle);
          driver.close();
       }

        driver.quit();
  }
```

**Comment by h3dkandi** [comment] 2017-01-13 11:42
Thanks for the suggestion.

If the information provided for this issue is not enough I think it can be closed as I am not willing to experiment any further, for which I am sorry.

**Closed** 2017-01-13 14:38 UTC
Labels: NeedsTriage

**Comment by imurchie** [comment] 2017-01-13 23:13
I'm not able to reproduce this. But the `preventWDAAttachments` capability gets applied _after_ the WebDriverAgent gets built and run, so I don't see how it would be causing this.
