### ISSUE TITLE
uncaughtException: The frame is bigger than expected. Length: 2511609, max: 1000000

### ISSUE THREAD

**Issue by RamSaiMallik** [appium/appium#13229] opened 2019-09-12 17:57 UTC
## Description

uncaughtException: The frame is bigger than expected. Length: 2511609, max: 1000000
Error: The frame is bigger than expected. Length: 2511609, max: 1000000
    at LengthBasedSplitter._decode (/usr/local/lib/node_modules/appium/node_modules/appium-ios-device/lib/util/transformer/length-based-splitter.js:38:13)
    at LengthBasedSplitter._transform (/usr/local/lib/node_modules/appium/node_modules/appium-ios-device/lib/util/transformer/length-based-splitter.js:19:48)
    at LengthBasedSplitter.Transform._read (_stream_transform.js:189:10)
    at LengthBasedSplitter.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:428:12)
    at writeOrBuffer (_stream_writable.js:412:5)
    at LengthBasedSplitter.Writable.write (_stream_writable.js:302:11)
    at Socket.ondata (_stream_readable.js:722:22)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)

## Environment

*Xcode 10.3
*Appium v1.10.0
Tried with v1.8.2 beta, v1.9.0,  v1.8.1
*IOS 12.4

**Comment by RamSaiMallik** [comment] 2019-09-13 09:21
Hi

I'm working on real device automation. 
Devices used: Iphone 6s, Iphone 7plus

**Appium server log** 

[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:2602', page '1', target 'page-1' (id: 42)
[debug] [RemoteDebugger] Received data response from send (id: 42): 'complete'
[debug] [RemoteDebugger] Sending to Web Inspector took 5ms
[debug] [RemoteDebugger] Document readyState is 'complete'
[debug] [RemoteDebugger] Page is ready
[HTTP] --> POST /wd/hub/session/c082179b-0b47-4cf8-9803-66f034006fd8/url
[HTTP] {"url":"https://www.staging.medscape.com/examroom/sample"}
[debug] [MJSONWP (c082179b)] Calling AppiumDriver.setUrl() with args: ["https://www.staging.medscape.com/examroom/sample","c082179b-0b47-4cf8-9803-66f034006fd8"]
[debug] [XCUITest] Executing command 'setUrl'
[debug] [iOS] Attempting to set url 'https://www.staging.medscape.com/examroom/sample'
[debug] [RemoteDebugger] Navigating to new URL: 'https://www.staging.medscape.com/examroom/sample'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:2602', page '1', target 'page-1' (id: 43)
[debug] [RemoteDebugger] Received data response from send (id: 43): '{}'
[debug] [RemoteDebugger] Sending to Web Inspector took 11ms
[debug] [RemoteDebugger] Waiting for frame navigated message...
[debug] [RemoteDebugger] Frame navigated in 0.148 sec from source: remote-debugger
[debug] [RemoteDebugger] Waiting for dom...
[debug] [RemoteDebugger] Page loaded, verifying whether ready
uncaughtException: The frame is bigger than expected. Length: 2511608, max: 1000000
Error: The frame is bigger than expected. Length: 2511608, max: 1000000
    at LengthBasedSplitter._decode (/usr/local/lib/node_modules/appium/node_modules/appium-ios-device/lib/util/transformer/length-based-splitter.js:38:13)
    at LengthBasedSplitter._transform (/usr/local/lib/node_modules/appium/node_modules/appium-ios-device/lib/util/transformer/length-based-splitter.js:19:48)
    at LengthBasedSplitter.Transform._read (_stream_transform.js:189:10)
    at LengthBasedSplitter.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:428:12)
    at writeOrBuffer (_stream_writable.js:412:5)
    at LengthBasedSplitter.Writable.write (_stream_writable.js:302:11)
    at Socket.ondata (_stream_readable.js:722:22)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
[debug] [RemoteDebugger] Checking document readyState
[debug] [RemoteDebugger] Sending javascript command: '(function (){ return document.readyState; })()'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:2602', page '1', target 'page-1' (id: 44)

**Eclipse console log**

iosweb launched

Error communicating with the remote browser. It may have died.
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'E1314T1D', ip: '172.18.121.13', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_91'
Driver info: driver.version: RemoteWebDriver
Capabilities [{noReset=true, startIWDP=true, deviceName=iPhone6S - iOS11.0.3, xcodeSigningId=iPhone Developer, nativeWebTap=true, platform=MAC, showXcodeLog=true, newCommandTimeout=120, acceptInsecureCerts=true, platformVersion=11.0.3, webStorageEnabled=false, --command-timeout=60000, automationName=XCUITest, browserName=Safari, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=81a9af36847bcec289533772a3c89dfbd45cd572, safariIngoreFraudWarning=true, networkConnectionEnabled=false, safariOpenLinksInBackground=true, xcodeOrgId=Narasimha K(Personal Team), unhandledPromptBehavior=true, autoDismissAlerts=false, databaseEnabled=false, proxy={proxyAutoconfigUrl=null, autodetect=false, socksUsername=null, socksPassword=null, httpProxy=localhost:8888, proxyType=MANUAL, noProxy=null, ftpProxy=null, socksProxy=null, hCode=1109020385, class=org.openqa.selenium.Proxy, sslProxy=localhost:8888}, safariIgnoreFraudWarning=true, safariAllowPopups=true, locationContextEnabled=false}]
Session ID: c082179b-0b47-4cf8-9803-66f034006fd8

org.openqa.selenium.remote.RemoteWebDriver execute 665
io.appium.java_client.DefaultGenericMobileDriver execute 40
io.appium.java_client.AppiumDriver execute 1
io.appium.java_client.ios.IOSDriver execute 1
org.openqa.selenium.remote.RemoteWebDriver get 316
<b style='color:red'>com.webmd.automation.accel.ActionMethods get 256
test.webmd.patientExamRoom.PERAndroidScenario startUpBrowser 48
sun.reflect.NativeMethodAccessorImpl invoke0 -2
sun.reflect.NativeMethodAccessorImpl invoke 62
sun.reflect.DelegatingMethodAccessorImpl invoke 43
java.lang.reflect.Method invoke 498
org.testng.internal.MethodInvocationHelper invokeMethod 133
org.testng.internal.MethodInvocationHelper invokeMethodConsideringTimeout 62
org.testng.internal.ConfigInvoker invokeConfigurationMethod 340
org.testng.internal.ConfigInvoker invokeConfigurations 294
org.testng.internal.TestMethodWorker invokeBeforeClassMethods 176
org.testng.internal.TestMethodWorker run 122
java.util.ArrayList forEach 1249

**Versions**

npm - v6.11.3
node - v12.10.0
appium - v1.10.0

**Observed**
*After appium server error, In eclipe getting "Error communicating with the remote browser. It may have died."

**Comment by RamSaiMallik** [comment] 2019-09-16 09:58
Hi,

Is there any solution for this error ?

Regards
Ram

**Comment by umutuzgur** [comment] 2019-09-25 08:05
I'm gonna take a look at that today

**Comment by umutuzgur** [comment] 2019-09-25 10:12
@RamSaiMallik Can I get the url of the website if it is a public page?

**Comment by RamSaiMallik** [comment] 2019-09-25 12:03
@umutuzgur  I tried with many URLs.After loading URL also this issue is coming.

**Comment by umutuzgur** [comment] 2019-09-25 12:08
I'm doing a load test with simulators right now and can't repro it. I will try with a real device

**Comment by umutuzgur** [comment] 2019-09-25 12:09
@RamSaiMallik Is the issue also happening with Appium 1.15.0 btw?

**Comment by RamSaiMallik** [comment] 2019-09-25 12:21
@umutuzgur I tried 1.8.2 to 1.12

**Comment by RamSaiMallik** [comment] 2019-09-25 12:35
@umutuzgur  Just now, I tried Appium v1.15.0-beta.0.
No result,I got same issue.

**Comment by umutuzgur** [comment] 2019-09-25 12:48
I'm still failing to repro it. I tried on a real device and a simulator with a load test. Could you send me your desired capabilities? Maybe that is the missing link

**Comment by RamSaiMallik** [comment] 2019-09-25 13:02
capabilities.setCapability("platformName" ,"iOS"); 
		capabilities.setCapability("--command-timeout", 60000);
	         capabilities.setCapability(CapabilityType.BROWSER_NAME, "Safari");
		capabilities.setCapability(MobileCapabilityType.UDID, action.UDID);
		capabilities.setCapability("automationName", "XCUITest");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, action.IOS_PLATFORM_VERSION);
	      capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,action.IOS_device_name);
		capabilities.setCapability("startIWDP", true);
		capabilities.setCapability("showXcodeLog", true);
	        capabilities.setCapability("xcodeSigningId", "iPhone Developer");
		capabilities.setCapability("safariIgnoreFraudWarning", true);
		capabilities.setCapability("safariAllowPopups", "true");
		capabilities.setCapability("unhandledPromptBehavior", "true");
		capabilities.setCapability("noReset", true);  // for iOS only
		capabilities.setCapability("safariOpenLinksInBackground",true);
		capabilities.setCapability("nativeWebTap",true);
		capabilities.setCapability("safariIngoreFraudWarning",true);
		capabilities.setCapability("autoDismissAlerts",false);
		capabilities.setCapability("pageLoadStrategy", "none");
		capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT,1000);
		capabilities.setCapability("newCommandTimeout", "120");

**Comment by RamSaiMallik** [comment] 2019-09-26 12:35
@umutuzgur Are you able to repro this issue ?

**Comment by umutuzgur** [comment] 2019-09-27 08:30
@RamSaiMallik I still can't repro it and I load tested it pretty throughly with multiple devices, simulators and nodejs versions. I feel like there is something wrong with your installation but I'm not 100% sure

**Comment by bennid** [comment] 2019-10-03 17:43
We just updated to appium 1.15.0 and are trying to use this on iOS simulators at iOS 12.1 (iPhone Xr).  We lost 7 appium processes due to this.  Here are a couple of snippets:

```
2019-10-03 17:10:31:886 - [HTTP] --> GET /wd/hub/session/09c3b171-1d02-4df6-aab9-223628d9c858/source
2019-10-03 17:10:31:886 - [HTTP] {}
2019-10-03 17:10:31:886 - [debug] [W3C (09c3b171)] Calling AppiumDriver.getPageSource() with args: ["09c3b171-1d02-4df6-aab9-223628d9c858"]
2019-10-03 17:10:31:887 - [debug] [XCUITest] Executing command 'getPageSource'
2019-10-03 17:10:31:889 - [debug] [RemoteDebugger] Executing atom 'execute_script'
2019-10-03 17:10:31:890 - [debug] [RemoteDebugger] Executing 'execute_script' atom in default context
2019-10-03 17:10:31:890 - [debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var e=this;
2019-10-03 17:10:31:891 - [debug] [RemoteDebugger] funct...'
2019-10-03 17:10:31:891 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:21637', page '1' (id: 117)
2019-10-03 17:10:31:951 - uncaughtException: The frame is bigger than expected. Length: 1500565, max: 1000000
Error: The frame is bigger than expected. Length: 1500565, max: 1000000
    at LengthBasedSplitter._decode (/Users/qa/Library/Developer/CoreSimulator/Devices/CB5D8C0D-461F-4E26-8C31-0C0E9A1F6FD5/node_modules/appium/node_modules/appium-ios-device/lib/util/transformer/length-based-splitter.js:38:13)
    at LengthBasedSplitter._decode [as _transform] (/Users/qa/Library/Developer/CoreSimulator/Devices/CB5D8C0D-461F-4E26-8C31-0C0E9A1F6FD5/node_modules/appium/node_modules/appium-ios-device/lib/util/transformer/length-based-splitter.js:19:48)
    at LengthBasedSplitter.Transform._read (_stream_transform.js:189:10)
    at LengthBasedSplitter.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:428:12)
    at writeOrBuffer (_stream_writable.js:412:5)
    at LengthBasedSplitter.Writable.write (_stream_writable.js:302:11)
    at Socket.ondata (_stream_readable.js:722:22)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
```
AND
```2019-10-03 17:11:51:849 - [HTTP] --> POST /wd/hub/session/0419d8a9-3972-4321-852c-30ca6348995a/url
2019-10-03 17:11:51:850 - [HTTP] {"url":"https://our.test.server.co.uk"}
2019-10-03 17:11:51:851 - [debug] [W3C (0419d8a9)] Calling AppiumDriver.setUrl() with args: ["https://our.test.server.co.uk","0419d8a9-3972-4321-852c-30ca6348995a"]
2019-10-03 17:11:51:851 - [debug] [XCUITest] Executing command 'setUrl'
2019-10-03 17:11:51:854 - [debug] [iOS] Attempting to set url 'https://hare.tripadvisor.co.uk'
2019-10-03 17:11:51:854 - [debug] [RemoteDebugger] Navigating to new URL: 'https://hare.tripadvisor.co.uk'
2019-10-03 17:11:51:854 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:24019', page '1' (id: 10)
2019-10-03 17:11:51:859 - [debug] [RemoteDebugger] Received response for message '10'
2019-10-03 17:11:51:859 - [debug] [RemoteDebugger] Handling message (id: '10')
2019-10-03 17:11:51:859 - [debug] [RemoteDebugger] Received data response from send (id: 10): '{}'
2019-10-03 17:11:51:859 - [debug] [RemoteDebugger] Sending to Web Inspector took 5ms
2019-10-03 17:11:52:867 - [debug] [RemoteDebugger] Waiting for frame navigated message...
2019-10-03 17:11:53:373 - [debug] [RemoteDebugger] Frame navigated in 0.505 sec from source: timeout
2019-10-03 17:11:53:374 - [debug] [RemoteDebugger] Waiting for dom...
2019-10-03 17:11:53:374 - [debug] [RemoteDebugger] Page loaded, verifying whether ready
2019-10-03 17:11:53:483 - [debug] [RemoteDebugger] Frame navigated in 0.615 sec from source: remote-debugger
2019-10-03 17:11:53:875 - [debug] [RemoteDebugger] Checking document readyState
2019-10-03 17:11:53:875 - [debug] [RemoteDebugger] Sending javascript command: '(function (){ return document.readyState; })()'
2019-10-03 17:11:53:875 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:24019', page '1' (id: 11)
2019-10-03 17:11:54:290 - [debug] [RemoteDebugger] Received response for message '11'
2019-10-03 17:11:54:290 - [debug] [RemoteDebugger] Handling message (id: '11')
2019-10-03 17:11:54:290 - [debug] [RemoteDebugger] Received data response from send (id: 11): 'loading'
2019-10-03 17:11:54:290 - [debug] [RemoteDebugger] Sending to Web Inspector took 415ms
2019-10-03 17:11:54:290 - [debug] [RemoteDebugger] Document readyState is 'loading'
2019-10-03 17:11:54:291 - [debug] [RemoteDebugger] Page was not ready, retrying
2019-10-03 17:11:54:790 - [debug] [RemoteDebugger] Checking document readyState
2019-10-03 17:11:54:791 - [debug] [RemoteDebugger] Sending javascript command: '(function (){ return document.readyState; })()'
2019-10-03 17:11:54:791 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:24019', page '1' (id: 12)
2019-10-03 17:11:54:800 - [debug] [RemoteDebugger] Received response for message '12'
2019-10-03 17:11:54:800 - [debug] [RemoteDebugger] Handling message (id: '12')
2019-10-03 17:11:54:800 - [debug] [RemoteDebugger] Received data response from send (id: 12): 'loading'
2019-10-03 17:11:54:801 - [debug] [RemoteDebugger] Sending to Web Inspector took 9ms
2019-10-03 17:11:54:801 - [debug] [RemoteDebugger] Document readyState is 'loading'
2019-10-03 17:11:54:801 - [debug] [RemoteDebugger] Page was not ready, retrying
2019-10-03 17:11:55:301 - [debug] [RemoteDebugger] Checking document readyState
2019-10-03 17:11:55:301 - [debug] [RemoteDebugger] Sending javascript command: '(function (){ return document.readyState; })()'
2019-10-03 17:11:55:302 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:24019', page '1' (id: 13)
2019-10-03 17:11:55:306 - [debug] [RemoteDebugger] Received response for message '13'
2019-10-03 17:11:55:306 - [debug] [RemoteDebugger] Handling message (id: '13')
2019-10-03 17:11:55:306 - [debug] [RemoteDebugger] Received data response from send (id: 13): 'loading'
2019-10-03 17:11:55:306 - [debug] [RemoteDebugger] Sending to Web Inspector took 5ms
2019-10-03 17:11:55:307 - [debug] [RemoteDebugger] Document readyState is 'loading'
2019-10-03 17:11:55:307 - [debug] [RemoteDebugger] Page was not ready, retrying
2019-10-03 17:11:55:807 - [debug] [RemoteDebugger] Checking document readyState
2019-10-03 17:11:55:807 - [debug] [RemoteDebugger] Sending javascript command: '(function (){ return document.readyState; })()'
2019-10-03 17:11:55:807 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:24019', page '1' (id: 14)
2019-10-03 17:11:55:841 - [debug] [RemoteDebugger] Received response for message '14'
2019-10-03 17:11:55:842 - [debug] [RemoteDebugger] Handling message (id: '14')
2019-10-03 17:11:55:842 - [debug] [RemoteDebugger] Received data response from send (id: 14): 'loading'
2019-10-03 17:11:55:842 - [debug] [RemoteDebugger] Sending to Web Inspector took 34ms
2019-10-03 17:11:55:842 - [debug] [RemoteDebugger] Document readyState is 'loading'
2019-10-03 17:11:55:842 - [debug] [RemoteDebugger] Page was not ready, retrying
2019-10-03 17:11:56:371 - [debug] [RemoteDebugger] Received page change notice for app 'PID:24019' but the listing has not changed. Ignoring.
2019-10-03 17:11:56:371 - [debug] [RemoteDebugger] Checking document readyState
2019-10-03 17:11:56:372 - [debug] [RemoteDebugger] Sending javascript command: '(function (){ return document.readyState; })()'
2019-10-03 17:11:56:372 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:24019', page '1' (id: 15)
2019-10-03 17:11:56:708 - [debug] [RemoteDebugger] Received page change notice for app 'PID:24019' but the listing has not changed. Ignoring.
2019-10-03 17:11:56:975 - [debug] [RemoteDebugger] Received page change notice for app 'PID:24019' but the listing has not changed. Ignoring.
2019-10-03 17:11:57:264 - [debug] [RemoteDebugger] Received page change notice for app 'PID:24019' but the listing has not changed. Ignoring.
2019-10-03 17:11:57:320 - [debug] [RemoteDebugger] Received response for message '15'
2019-10-03 17:11:57:320 - [debug] [RemoteDebugger] Handling message (id: '15')
2019-10-03 17:11:57:320 - [debug] [RemoteDebugger] Received data response from send (id: 15): 'interactive'
2019-10-03 17:11:57:321 - [debug] [RemoteDebugger] Sending to Web Inspector took 948ms
2019-10-03 17:11:57:321 - [debug] [RemoteDebugger] Document readyState is 'interactive'
2019-10-03 17:11:57:321 - [debug] [RemoteDebugger] Page was not ready, retrying
2019-10-03 17:11:57:821 - [debug] [RemoteDebugger] Checking document readyState
2019-10-03 17:11:57:822 - [debug] [RemoteDebugger] Sending javascript command: '(function (){ return document.readyState; })()'
2019-10-03 17:11:57:822 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:24019', page '1' (id: 16)
2019-10-03 17:11:57:924 - uncaughtException: The frame is bigger than expected. Length: 1363492, max: 1000000
Error: The frame is bigger than expected. Length: 1363492, max: 1000000
    at LengthBasedSplitter._decode (/Users/qa/Library/Developer/CoreSimulator/Devices/C653C526-1549-4AB4-AC8A-45A79E65C79C/node_modules/appium/node_modules/appium-ios-device/lib/util/transformer/length-based-splitter.js:38:13)
    at LengthBasedSplitter._decode [as _transform] (/Users/qa/Library/Developer/CoreSimulator/Devices/C653C526-1549-4AB4-AC8A-45A79E65C79C/node_modules/appium/node_modules/appium-ios-device/lib/util/transformer/length-based-splitter.js:19:48)
    at LengthBasedSplitter.Transform._read (_stream_transform.js:189:10)
    at LengthBasedSplitter.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:428:12)
    at writeOrBuffer (_stream_writable.js:412:5)
    at LengthBasedSplitter.Writable.write (_stream_writable.js:302:11)
    at Socket.ondata (_stream_readable.js:722:22)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
```

**Comment by imurchie** [comment] 2019-10-03 18:44
I have reproduced this. It works to just bump the maximum frame size.

**Comment by mykola-mokhnach** [comment] 2019-10-03 18:46
I assume it might be happening for larger pages, where xml page source size is above 1MB. 10-20 MB limit might be enough for now

**Comment by imurchie** [comment] 2019-10-03 18:47
Yes, that seems to be the case. It is reproducible with the production TripAdvisor site (UK, at least).

**Comment by imurchie** [comment] 2019-10-03 19:05
@RamSaiMallik Can you try the latest beta of Appium?

**Comment by bennid** [comment] 2019-10-03 19:47
If this is working, what release / timeframe would this be available (I'm assuming there will be a 1.15.1 appium release sometime)

**Comment by RamSaiMallik** [comment] 2019-10-04 10:29
> @RamSaiMallik Can you try the latest beta of Appium?

@imurchie I tried with 1.15.0-beta.0.But there is not result, same issue is coming.

**Comment by imurchie** [comment] 2019-10-04 16:26
The latest beta should be 1.16.0-beta.1

**Comment by mykola-mokhnach** [comment] 2019-10-06 13:07
Closed as fixed

**Closed by mykola-mokhnach** 2019-10-06 13:07 UTC
Labels: Mobile Safari, iOS

**Comment by grant-mccarriagher** [comment] 2019-10-18 19:47
@imurchie This is still happening on 1.16.0-beta.1, but I'm not sure if `appium-ios-device` 0.11.0 made it into that release?

**Comment by grant-mccarriagher** [comment] 2019-10-18 20:23
I should note however, that in my case the frame is absurdly large (1347703880), so even the PR I saw above wouldn't help me. I think there may be something else at play here, because our app shouldn't be doing anything that crazy. Should I open up a new issue for this?
