### ISSUE TITLE
Appium 1.5.2: Inspector automatically shut down after less then 1 minute 

### ISSUE THREAD

**Issue by louis57** [appium/appium#6492] opened 2016-05-10 14:39 UTC
I am using Version 1.5.2 (Ara). When I use Inspector, the app is launched and I could see all UIs, but Inspector is shut down automatically after less than 1 minute, with the log below. So I can't continue to inspect the app. It seems there is a time out 60 seconds is added in Inspector

> [BaseDriver] Shutting down because we waited 60 seconds for a command
> [debug] [AndroidDriver] Shutting down Android driver
> [Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
> [Appium] Removing session 8b38ccce-296e-4079-bc15-b726ffb9c138 from our master session list
> [debug] [ADB] Getting connected devices...
> [debug] [ADB] 1 device(s) connected
> [debug] [ADB] Pressing the HOME button
> [debug] [ADB] Getting connected devices...
> [debug] [ADB] 1 device(s) connected
> [debug] [ADB] Running /Users/l.quitran/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","06157df683e4993c","shell","input","keyevent",3]
> [debug] [Logcat] Stopping logcat capture
> [debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
> [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
> [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
> [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
> [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
> [debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
> [debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
> [debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> [debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> [debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> [debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1
> [debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> [debug] [AndroidBootstrap] Received command result from bootstrap
> [debug] [UiAutomator] Shutting down UiAutomator
> [debug] [UiAutomator] Moving to state 'stopping'
> [debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=
> [debug] [AndroidBootstrap] [UIAUTO STDOUT] Test results for WatcherResultPrinter=.
> [debug] [AndroidBootstrap] [UIAUTO STDOUT] Time: 63.92
> [debug] [AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
> [debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> [debug] [UiAutomator] UiAutomator shut down normally
> [debug] [UiAutomator] Moving to state 'stopped'
> [debug] [ADB] Attempting to kill all uiautomator processes
> [debug] [ADB] Getting all processes with uiautomator
> [debug] [ADB] Getting connected devices...
> [debug] [ADB] 1 device(s) connected
> [debug] [ADB] Running /Users/l.quitran/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","06157df683e4993c","shell","ps","uiautomator"]
> [ADB] No uiautomator process found to kill, continuing...

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.5.2 (Ara)
* Last Appium version that did not exhibit the issue (if applicable): Appium 1.4.13
* Desktop OS/version used to run Appium: Mac Capitan
* Mobile platform/version under test: Android 5.1.1

**Comment by imurchie** [comment] 2016-05-10 14:41
Duplicate of https://github.com/appium/appium-dot-app/issues/548

**Closed by imurchie** 2016-05-10 14:41 UTC
Labels: NeedsTriage

**Comment by AlbaBrito** [comment] 2018-06-01 20:54
@imurchie the link doesn't exist, could you provide a solution please?

**Comment by vani20** [comment] 2018-07-24 20:47
add capability 'newCommandTimeout' to 0
