### ISSUE TITLE
"index" used in xpath does not work with xcuitest automationName on appium 1.6.5 vs ios 10.3.2

### ISSUE THREAD

**Issue by lavi-xu** [appium/appium#8621] opened 2017-06-07 09:54 UTC
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ios 10.3.2
* Node.js version (unless using Appium.app|exe): v7.8.0
* Mobile platform/version under test: ipad
* Real device or emulator/simulator: device
* Appium CLI or Appium.app|exe: python binding

## Details

>>> print driver.find_elements_by_xpath('//UIAImage[contains(@name, "listDownArrow")]')
[<appium.webdriver.webelement.WebElement (session="1f0eb9dc-3f83-4ee0-936f-b2dfce1e9012", element="947BB2B1-D6CE-4DE4-A7AF-0E5CBFECFEDD")>, <appium.webdriver.webelement.WebElement (session="1f0eb9dc-3f83-4ee0-936f-b2dfce1e9012", element="ECC648D2-ED6C-43CE-9560-9117BBA69585")>]
>>> print driver.find_element_by_xpath('//UIAImage[contains(@name, "listDownArrow")][2]')
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 172, in fe
    return self.find_element_by_xpath (text)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 317, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 778, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 260, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

**Comment by mykola-mokhnach** [comment] 2017-06-07 10:04
Can you attach the output of get_page_source method?

**Comment by lavi-xu** [comment] 2017-06-09 00:55
@mykola-mokhnach 

attached page source, please have a check:
[pagesource.txt](https://github.com/appium/appium/files/1062783/pagesource.txt)

**Comment by mykola-mokhnach** [comment] 2017-06-09 05:48
the xpath you use does not look correct if you want to find the second occurrence of **listDownArrow** element in the document. It should be changed to:

```
(//XCUIElementTypeImage[@name='listDownArrow'])[2]
```

**Comment by lavi-xu** [comment] 2017-06-09 06:59
@mykola-mokhnach 
No, you were using wrong syntax script. It's python code. It can located element with:
print driver.find_element_by_xpath('//UIAImage[contains(@name, "listDownArrow")][1]')

To show a simple case, now it even can not locate XCUIElementTypeOther:
[pagesource.2.txt](https://github.com/appium/appium/files/1063197/pagesource.2.txt)

>>> print driver.find_element_by_class_name('XCUIElementTypePickerWheel').find_elements_by_ios_classchain('XCUIElementTypeOther')
[]

**Comment by lavi-xu** [comment] 2017-06-09 08:28
It's strange that xpath also did not work for the case above:
>>> wd1.find_element_by_class_name('XCUIElementTypePicker').find_elements_by_xpath('//XCUIElementTypeAny')
[<appium.webdriver.webelement.WebElement (session="e3f556fb-d66a-49b2-9e5b-72df434c402a", element="C45B03AC-C749-4947-8DF2-74AEED19A3E8")>]
>>> wd1.find_element_by_class_name('XCUIElementTypePicker').find_element_by_xpath('//XCUIElementTypeAny')
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 260, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 508, in find_element
    {"using": by, "value": value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 491, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 260, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

**Comment by lavi-xu** [comment] 2017-06-12 08:09
@mykola-mokhnach 

Any updates please?

**Comment by mykola-mokhnach** [comment] 2017-06-12 08:25
It works for me. You can also try Appium 1.6.6-beta, where the recent WDA changes have been merged. It also has several improvements for xpath search.

**Comment by lavi-xu** [comment] 2017-06-13 04:21
I have no idea why it works for you. I am using appium1.6.5 and  the latest WDA from WDA souce-repo.

Are you using elements tree (2 page source file)offered by me? Because in most of element tree it works.

I am using appium (automationName with uiautomation2 vs uiauto) for a long time and I am sure that I am good at using these stuff. We are just trying to upgrade automate for ios10.

is there any other ways that I can reproduce this issue for your debug?

BR.

**Comment by mykola-mokhnach** [comment] 2017-06-13 06:13
It's hardly possible to reproduce anything without an actual build. I believe you can investigate the root of the problem yourself having enough experience in this area.
[Here](https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/migrating-to-xcuitest.md) you can also find XCTest migration guide.

**Closed** 2017-07-21 20:28 UTC
Labels: NotABug, XCUITest
