### ISSUE TITLE
switch to webview throws "chrome not reachable" or "Failed to get PID for the following process"

### ISSUE THREAD

**Issue by loveiset** [appium/appium#10970] opened 2018-06-29 10:04 UTC
## The problem

swith to webview throws error "chrome not reachable" or "Failed to get PID for the following process"

## Environment

* Appium version (or git revision): 1.8.1
* Desktop OS/version used to run Appium: win7 SP1
* Node.js version (unless using Appium.app|exe): v8.11.0
* Mobile platform/version under test: 7.1.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: `appium --session-override --chromedriver-executable path/to/chromedriver`

## Details

|webview version|chromedriver version|with chromedriver-executable|result|
|-|-|-|-|
|60.0.3112.116|2.28|true|chrome not reachable|
|60.0.3112.116|2.32|true|chrome not reachable|
|60.0.3112.116|2.33|true|chrome not reachable|
|60.0.3112.116|2.34|true|chrome not reachable|
|60.0.3112.116|2.35|true|chrome not reachable|
|60.0.3112.116|2.40|true|Failed to get PID for the following process|
|60.0.3112.116|appium built-in|false|No Chromedriver found that can automate Chrome|
|67.0.3396.87|2.40|true|Failed to get PID for the following process|
|67.0.3396.87|2.39|true|Failed to get PID for the following process|
|67.0.3396.87|2.38|true|Failed to get PID for the following process|
|67.0.3396.87|2.37|true|chrome not reachable|

## Link to Appium logs

[log to chrome not reachable](https://gist.github.com/loveiset/03b773d457b2c9a9cbbd9860abf61d49)
[Failed to get PID for the following process](https://gist.github.com/loveiset/0cc654248150bb67aca09cc0801decba)
[all logs seperated by many ==](https://gist.github.com/loveiset/27a96b17255491a19a351752ff94952c)

**Comment by mayureshshirodkar** [comment] 2018-06-29 10:40
What kind of app are you testing? Are you using a Cordova App with Crosswalk?

**Comment by mykola-mokhnach** [comment] 2018-06-29 11:49
Are you able to connect using chrome remote debugger?

**Comment by mykola-mokhnach** [comment] 2018-06-29 11:58
The exception happens inside https://github.com/bayandin/chromedriver/blob/907b958e09dbfdafb13e9257b181009d0ab43b4a/chrome/adb_impl.cc#L260, so I'd say either the process itself dies when chromedriver is trying to look for it or there is some issue with package name detection.

**Comment by loveiset** [comment] 2018-07-02 01:22
@mykola-mokhnach chrome remote dubugger works fine, it shows `WebView in com.crc.hrt (67.0.3396.87)` and I can inspect into it.

**Comment by Fabiolino88** [comment] 2018-07-07 10:32
Hi guys, I don't know whether this can help or not, but I was facing the same issue in the last three days. Looking for the issue on google I've found out that a lot of people is actually facing the same issue.
I got an android app that at some point switch to a custom tab to do the authentication and there was no way to connect to the webview to automate the process.

The simulator that I'm using is a Nexus 5X with Android 8.1 + Chrome 67.0.3396 - Appium 1.8.1 and Chromedriver 2.40.
I've tried all the combination to make it works.
At the beginning appium was looking for the driver using the version of the System WebView instead of the Chrome version and to solve this problem I've found out that you need to pass the path to the specific Chromedriver into the "chromedriverExecutable" capability.
After that I was able to retrieve the full list of webviews but the Chromedriver was complaining with the message "chrome not reachable".

When I was trying to switch the context to the webview I've noticed that the Chromedriver.js was calling the JWProxy passing the 'chromeOptions: { androidPackage: the.Package.OfMyApp, ...... }.
I've tried to pass the chromeOptions capability while setting the driver in my java project, but appium was crashing for unknown capability.
So I went into Chromedriver.js and I've injected manually the "com.android.chrome" package to the capabilities before to call the JWProxy. Now switching to the 'WEBVIEW_chrome" + force chromedriver to use the chrome package made the trick and everything is working fine.

Please let me know if you need more details or if you guys know if there is better way to pass the chromeOptions capabilities.
Looking at this page: http://chromedriver.chromium.org/capabilities I didn't find any "androidPackage" in the list of available capabilities.

**Comment by mykola-mokhnach** [comment] 2018-07-07 16:02
@imurchie FYI

**Comment by loveiset** [comment] 2018-07-20 02:20
I tried your solution，but it did not work，now I don't know what to do @Fabiolino88

**Comment by roosto** [comment] 2018-07-26 18:40
This issue may be a duplicate of #8958 
cc: @loveiset

**Comment by zhangpeibisha** [comment] 2018-07-30 08:01
Hello, may you solve the problem?

**Comment by Fabiolino88** [comment] 2018-08-03 13:20
Hi @loveiset, what did you do exactly? can you please give more details?

**Comment by loveiset** [comment] 2018-08-06 02:10
@Fabiolino88 I edit `Chomedriver.js` as following, but it did not work
```javascript
async start (caps, emitStartingState = true) {
    this.capabilities = caps;
    // add this line
    // change androidPackage to package.of.myApp or com.android.chrome, neither works.
    this.capabilities["chromeOptions"]["androidPackage"] = "package.of.myApp";
    if (emitStartingState) {
      this.changeState(Chromedriver.STATE_STARTING);
    }
```

**Comment by Fabiolino88** [comment] 2018-08-06 12:57
Hi @loveiset, sorry probably in the post I didn't explain it well, but you need to set the android package to the chrome app package. 
Setting it to the App package it's exactly why is not working.
I've done it like that:

this.capabilities.chromeOptions.androidPackage = "com.android.chrome"

on line 253 after the start (like you done already) and on line 404 in the startSession method

**Comment by mykola-mokhnach** [comment] 2018-08-31 12:38
Closed as inactive

**Closed by mykola-mokhnach** 2018-08-31 12:38 UTC
Labels: Mobile Chrome

**Comment by Lanuet** [comment] 2018-10-04 10:59
thank @Fabiolino88 this solution worked for me

**Comment by PrasadMadge** [comment] 2018-10-31 12:39
@Fabiolino88 ,@Lanuet, can you please brief how did your issue got fixed.

"C:\Users\q2019\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js" 

I have updated the package to chrome in both async and start session method in chromedriver.js , still facing the issue.
this.capabilities["chromeOptions"]["androidPackage"] = "com.android.chrome";

What do you mean recompile the packages ?

**Comment by tahirakhlaaq** [comment] 2019-08-19 06:58
Any solution for this. I'm also facing the problem.
[https://gist.github.com/tahirakhlaaq/53de659cb5fe89889ab9dec7432c135c]

**Comment by tahirakhlaaq** [comment] 2019-08-19 06:59
[https://gist.github.com/tahirakhlaaq/53de659cb5fe89889ab9dec7432c135c](url)
