### ISSUE TITLE
Actions on any element in an app in a specific page taking over 30s to perform (Mobile Android App)

### ISSUE THREAD

**Issue by sandeepraju8787** [appium/appium#14657] opened 2020-08-17 06:25 UTC
## The problem

I'm testing the app Pinterest with appium/java/selenium. The page under test has a video playing. A back button on top and google results like related search results at the bottom. When checked with appium desktop, it is found to be in the scope of native app context itself. 
Target is to click on the back button as soon as we land on this page. However, using any identifier or approach, it takes 30s to perform the actions. 
1. with id - 20s
2. with xpath - 30s
3. with content description/accessibility id - 15s
4. with tapping on static coordinates of the element - 20s
5. with mobile back button using keyevent(which performs the same functionality) - 12s 

The issue occurs only with this google results kind of page. In all other pages in the application, it works like a charm. Please help.
I will be able to provide only data based on what is needed since it is confidential data.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Appium: Mac OS Mojave - 10.14.6
* Node.js version (unless using Appium.app|exe): v13.1.0
* Npm or Yarn package manager: 6.12.1
* Mobile platform/version under test: Android 8.0.0
* Real device or emulator/simulator: Real Device. Samsung Galaxy S7 Edge
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2020-08-17 07:35
Duplicate of https://github.com/appium/appium/issues/14594

**Closed by mykola-mokhnach** 2020-08-17 07:36 UTC

**Comment by sandeepraju8787** [comment] 2020-08-17 10:28
@mykola-mokhnach This issue is entirely different from what you have sited as duplicated. 
Please note that, in my case each millisecond matters. Explicit wait is not what i'm looking for. As soon as my page is loaded, counters in my start measuring in view time. I want to start performing actions the moment this page is loaded. Even one second error is accepted. But in actual, after the page loads, and even if i add an explicit wait, it takes appium over 12 seconds to do any action.

**Comment by sandeepraju8787** [comment] 2020-08-17 10:28
Please let me know what else can i provide so that i could give more details.

**Comment by sandeepraju8787** [comment] 2020-08-17 10:34
> ## The problem
> I'm testing the app Pinterest with appium/java/selenium. The page under test has a video playing. A back button on top and google results like related search results at the bottom. When checked with appium desktop, it is found to be in the scope of native app context itself.
> Target is to click on the back button as soon as we land on this page. However, using any identifier or approach, it takes 30s to perform the actions.
> 
> 1. with id - 20s
> 2. with xpath - 30s
> 3. with content description/accessibility id - 15s
> 4. with tapping on static coordinates of the element - 20s
> 5. with mobile back button using keyevent(which performs the same functionality) - 12s
> 
> The issue occurs only with this google results kind of page. In all other pages in the application, it works like a charm. Please help.
> I will be able to provide only data based on what is needed since it is confidential data.
> 
> ## Environment
> * Appium version (or git revision) that exhibits the issue: 1.17.1
> * Last Appium version that did not exhibit the issue (if applicable): None
> * Desktop OS/version used to run Appium: Mac OS Mojave - 10.14.6
> * Node.js version (unless using Appium.app|exe): v13.1.0
> * Npm or Yarn package manager: 6.12.1
> * Mobile platform/version under test: Android 8.0.0
> * Real device or emulator/simulator: Real Device. Samsung Galaxy S7 Edge
> * Appium CLI or Appium.app|exe: Appium CLI
> 
> ## Details
> If necessary, describe the problem you have been experiencing in more detail.
> 
> ## Link to Appium logs
> Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
> Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
> If you are reporting a bug, _always_ include Appium logs!
> 
> ## Code To Reproduce Issue [ Good To Have ]
> Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.
> 
> Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.
> 
> In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment] 2020-08-17 10:44
Without the entire Appium log, we cannot say anything, unfortunately.
`waitForIdleTimeout` handles UIA2 framework's internal. If your issue was uia2 server internal layer, the timeout may help.
