### ISSUE TITLE
iOS - WebDriverAgentRunner; dyld: Library not loaded: @rpath/XCTest.framework/XCTest; code signing blocked mmap()

### ISSUE THREAD

**Issue by ChiWhiteSox56** [appium/appium#7740] opened 2017-01-24 20:24 UTC
## The problem

Ever since the incorporation of the XCUITest framework for iOS, I cannot run Appium tests on real iOS devices. When I try to test my WebDriverAgent setup in the terminal (`xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test`), the log reports the following failures: 

> dyld: Library not loaded: @rpath/XCTest.framework/XCTest
> ...
> Reason: no suitable image found.  Did find:
> 	/private/var/containers/Bundle/Application/F12F1AED-47C4-4163-BA3B-85F0EDF579A1/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/F12F1AED-47C4-4163-BA3B-85F0EDF579A1/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
> ...	
>  Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Full terminal and Appium logs are in gists below. I have no problems running Appium tests on the iOS simulator.

## Environment

* Appium version (or git revision) that exhibits the issue: seen in Appium 1.6.1 and Appium 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): Pre XCUITest
* Desktop OS/version used to run Appium: EL Capitan (10.11.6)
* Node.js version: 7.3.0
* Mobile platform/version under test: 10.2
* Real device or emulator/simulator: real device (iPhone 6)
* Appium CLI or Appium.app|exe: Appium CLI

## Details
I tried to fix this issue by linking to XCTest.framework in WebDriverAgent.xcodeproj under WebDriverAgentLib -> Build Phases -> Link Binary With Libraries, and WebDriverAgentRunner -> Build Phases -> Link Binary With Libraries. I changed the status of both to 'Optional' on the advice of other discussions around this issue.

## Link to Appium logs

Appium log with showXcodeLog = true:
https://gist.github.com/ChiWhiteSox56/d001feecbe98d1c486d11797cd9a7953

Xcodebuild test log (`xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test`):
https://gist.github.com/ChiWhiteSox56/e93736b565a28de5637d547e0b71ad43

## Code To Reproduce Issue [ Good To Have ]

My desired capabilities are as follows:
```
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(CapabilityType.PLATFORM, "Mac");
capabilities.setCapability("nativeWebTap", true);
capabilities.setCapability("platformName", ConfigIOSspk.PLATFORM_NAME);
capabilities.setCapability("automationName", "XCUITest");
capabilities.setCapability("platformVersion", ConfigIOSspk.IOS_VERSION);
capabilities.setCapability("device", ConfigIOSspk.DEVICE);
capabilities.setCapability("deviceName", ConfigIOSspk.DEVICE_NAME);
capabilities.setCapability("sendKeyStrategy", "setValue");
capabilities.setCapability("autoAcceptAlerts", true);
capabilities.setCapability("xcodeConfigFile", "/Users/cmichalowski/.nvm/versions/node/v7.3.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig");
capabilities.setCapability("launchTimeout", 60000);
if (!ConfigIOSspk.IS_SIMULATOR) { 
     capabilities.setCapability("app", System.getProperty(ConfigIOSspk.USER_DIR) + ConfigIOSspk.APP_FILE_LOCATION_IPA);
capabilities.setCapability("realDeviceLogger", "/Users/cmichalowski/node_modules/deviceconsole/deviceconsole");
capabilities.setCapability("keychainPath", "/Users/cmichalowski/Library/Keychains/CindyKeychainA.keychain"); // <-- add full path to private development key exported from the system keychain
capabilities.setCapability("keychainPassword", "keychainPass"); 
capabilities.setCapability("bundleId", ConfigIOSspk.BUNDLE_ID);
capabilities.setCapability("showXcodeLog", true);
capabilities.setCapability(MobileCapabilityType.UDID, ConfigIOSspk.UDID);
} else {
               capabilities.setCapability("app", System.getProperty(ConfigIOSspk.USER_DIR) + ConfigIOSspk.APP_FILE_LOCATION_APP);
}
```

**Comment by mykola-mokhnach** [comment] 2017-01-24 21:03
Possible duplicate of https://github.com/appium/appium/issues/7094

**Comment by imurchie** [comment] 2017-01-25 14:25
Looking into the security stuff.

**Comment by imurchie** [comment] 2017-02-01 20:22
Appium 1.6.4-beta has been released (to upgrade, run `npm uninstall -g appium && npm install -g appium@beta`). How we connect to devices has been significantly changed, and should be more reliable. Please try it out.

There is some documentation here: https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

I am closing this issue since the details will have changed completely. If you still have problems, please see if there is a similar issue, or else create a new issue with as much information as possible. We are committed to tracking down these elusive problems!

**Closed by imurchie** 2017-02-01 20:22 UTC
Labels: NeedsTriage

**Comment by Saurabh0311** [comment] 2018-01-30 08:19
I am not able to launch my app on real device my mac:|
[Appium] Welcome to Appium v1.7.2
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/admin/Downloads/Influenster_iOS/app/Influenster.ipa","automationName":"XCUITest","bundleid":"com.influenster.mobile","clearSystemFiles":"True","deviceName":"iPhone 6s Plus","fullReset":true,"platformName":"iOS","platformVersion":"10.3","showIOSLog":true,"udid":"1f4a8caaecb50c2ebe93dfd8ab3edd560fc48804"},"capabilities":{"desiredCapabilities":{"app":"/Users/admin/Downloads/Influenster_iOS/app/Influenster.ipa","automationName":"XCUITest","bundleid":"com.influenster.mobile","clearSystemFiles":"True","deviceName":"iPhone 6s Plus","fullReset":true,"platformName":"iOS","platformVersion":"10.3","showIOSLog":true,"udid":"1f4a8caaecb50c2ebe93dfd8ab3edd560fc48804"},"firstMatch":[{"platformName":"ios"}]}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/admin/Downloads/Influenster_iOS/app/Influenster.ipa","automationName":"XCUITest","bundleid":"com.influenster.mobile","clearSystemFiles":"True","deviceName":"iPhone 6s Plus","fullReset":true,"platformName":"iOS","platformVersion":"10.3","showIOSLog":true,"udid":"1f4a8caaecb50c2ebe93dfd8ab3edd560fc48804"},null,{"desiredCapabilities":{"app":"/Users/admin/Downloads/Influenster_iOS/app/Influenster.ipa","automationName":"XCUITest","bundleid":"com.influenster.mobile","clearSystemFiles":"True","deviceName":"iPhone 6s Plus","fullReset":true,"platformName":"iOS","platformVersion":"10.3","showIOSLog":true,"udid":"1f4a8caaecb50c2ebe93dfd8ab3edd560fc48804"},"firstMatch":[{"platformName":"ios"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1517300068494 (13:44:28 GMT+0530 (IST))
[Appium] Merged W3C capabilities {"desiredCapabilities":{"app":"/Users/admin/Dow... into desiredCapabilities object {"app":"/Users/admin/Downloads/Influenster_iOS/...
[Appium] Creating new XCUITestDriver (v2.64.0) session
[Appium] Capabilities:
[Appium]   app: /Users/admin/Downloads/Influenster_iOS/app/Influenster.ipa
[Appium]   automationName: XCUITest
[Appium]   bundleid: com.influenster.mobile
[Appium]   clearSystemFiles: True
[Appium]   deviceName: iPhone 6s Plus
[Appium]   fullReset: true
[Appium]   platformName: ios
[Appium]   platformVersion: 10.3
[Appium]   showIOSLog: true
[Appium]   udid: 1f4a8caaecb50c2ebe93dfd8ab3edd560fc48804
[BaseDriver] Capability 'clearSystemFiles' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: bundleid.
[BaseDriver] Session created with session id: 58ae4d68-9b7d-4163-a599-17269ddb52d6
[XCUITest] Current user: 'admin'
[XCUITest] Current version of libimobiledevice: stable 1.2.0 (bottled), HEAD
[XCUITest] Xcode version set to '9.1' 
[XCUITest] iOS SDK Version set to '11.1'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1517300069682 (13:44:29 GMT+0530 (IST))
[XCUITest] Error: Command 'idevice_id -l' exited with code null
    at ChildProcess. (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/teen_process/lib/teen_process.js:97:19)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
 { Error: Command 'idevice_id -l' exited with code null
    at ChildProcess. (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/teen_process/lib/teen_process.js:97:19)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
  stdout: '',
  stderr: 'dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib\n  Referenced from: /usr/local/bin/idevice_id\n  Reason: no suitable image found.  Did find:\n\t/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib: not a file\n\t/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib: stat() failed with errno=1\n\t/usr/local/Cellar/openssl/1.0.2n/lib/libcrypto.1.0.0.dylib: not a file\n',
  code: null }
[XCUITest] No WebDriverAgent derived data available, so unable to clear system files
[MJSONWP] Encountered internal error running command: Error: Command 'idevice_id -l' exited with code null
    at ChildProcess. (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/teen_process/lib/teen_process.js:97:19)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[HTTP] <-- POST /wd/hub/session 500 1360 ms - 182

**Comment by imurchie** [comment] 2018-01-30 12:11
@Saurabh0311 Your installation of `libimobiledevice` is broken. Please uninstall and reinstall it.
