### ISSUE TITLE
App closing immediately after launching on ios

### ISSUE THREAD

**Issue by VasaviUppada** [appium/appium#9478] opened 2017-10-17 21:16 UTC
App is closing immediately after launching on simulator

Here are the desired capabilities : 
		File iosApp = new File(appDir, "MyApp.app");
//		File iosApp = new File("/Users/vasavi.uppada/Documents/Appium/Device App", "SunBasket.app");
		caps.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 7");
		caps.setCapability(MobileCapabilityType.PLATFORM_NAME, "IOS");
		caps.setCapability(MobileCapabilityType.PLATFORM_VERSION, "11.0");
		caps.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
		caps.setCapability("useNewWDA", true);
		caps.setCapability("showXcodeLog", true);
		caps.setCapability(MobileCapabilityType.APP, iosApp.getAbsolutePath());
        driver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), caps);

Here is the gist link : 
https://gist.github.com/VasaviUppada/5438096ff1974a0675a09e537764e297

**Comment by saikrishna321** [comment] 2017-10-18 04:42
@VasaviUppada logs looks fine .. When you install the app manually, does it open on simulator ?

**Comment by VasaviUppada** [comment] 2017-10-18 04:50
Yes, when I’m running through Xcode, app is launching fine on simulator.

**Comment by mykola-mokhnach** [comment] 2017-10-18 05:37
Please attach the simulator log as well.

**Comment by VasaviUppada** [comment] 2017-10-18 05:59
Here are the logs which are captured on xcode while launching app throught xcode on simulator

2017-10-17 22:56:55.957040-0700 SunBasket[1758:152018] [Firebase/Analytics][I-ACS023007] Firebase Analytics v.40003000 started
2017-10-17 22:56:55.957978-0700 SunBasket[1758:152018] [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2017-10-17 22:56:55.995608-0700 SunBasket[1758:151874] AppsFlyer SDK version 4.7.11 started build (572)
2017-10-17 22:56:56.097794-0700 SunBasket[1758:152009] [BoringSSL] Function boringssl_context_get_peer_sct_list: line 1754 received sct extension length is less than sct data length
2017-10-17 22:56:56.102523-0700 SunBasket[1758:151874] [MC] Lazy loading NSBundle MobileCoreServices.framework
2017-10-17 22:56:56.103632-0700 SunBasket[1758:151874] [MC] Loaded MobileCoreServices.framework
2017-10-17 22:56:56.109599-0700 SunBasket[1758:151874] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/vasavi.uppada/Library/Developer/CoreSimulator/Devices/A78F07FA-EC63-4E07-8762-B1CCE52E1DA6/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-10-17 22:56:56.386697-0700 SunBasket[1758:152019] [BoringSSL] Function boringssl_context_get_peer_sct_list: line 1754 received sct extension length is less than sct data length
2017-10-17 22:56:56.635054-0700 SunBasket[1758:151874] [MC] Reading from private effective user settings.
2017-10-17 22:56:56.772179-0700 SunBasket[1758:152009] TIC Read Status [1:0x0]: 1:57
2017-10-17 22:56:56.774432-0700 SunBasket[1758:152009] TIC Read Status [1:0x0]: 1:57
2017-10-17 22:56:57.785603-0700 SunBasket[1758:152018] AppsFlyer: sent information to server, status = 200

**Comment by mykola-mokhnach** [comment] 2017-10-18 06:17
>  launching app throught xcode on simulator

These logs are not very helpful. I'd like to see the one when the app is started by Appium.

**Comment by VasaviUppada** [comment] 2017-10-18 06:25
Here are the logs, when i'm running through Appium
https://gist.github.com/VasaviUppada/5438096ff1974a0675a09e537764e297

**Comment by mykola-mokhnach** [comment] 2017-10-18 06:50
Is it so complicated to use google?

https://stackoverflow.com/questions/10165641/how-can-i-get-the-console-logs-from-the-ios-simulator

**Comment by VasaviUppada** [comment] 2017-10-18 06:58
@mykola-mokhnach 
I just followed the link you provided to get logs from simulator when im running through Appium
Please find below gist list for the same
https://gist.github.com/VasaviUppada/79dbe73b358867db6a8d17996e9ee0b7

**Comment by mykola-mokhnach** [comment] 2017-10-18 07:05
> Oct 18 00:02:03 SF-VUPP-MBP com.apple.CoreSimulator.SimDevice.A78F07FA-EC63-4E07-8762-B1CCE52E1DA6[9560] (UIKitApplication:com.sunbasket.sunbasket[0x5ad1][9589][9683]): Program specified by service does not contain any valid architectures for this system.

Please show this log line to your application developer. Closed as not a bug.

**Closed by mykola-mokhnach** 2017-10-18 07:05 UTC
Labels: NeedsInfo, XCUITest

**Comment by VasaviUppada** [comment] 2017-10-18 07:20
@mykola-mokhnach Issue was closed & I didn't get any solution though...

**Comment by mykola-mokhnach** [comment] 2017-10-18 07:23
The application under test is corrupted and cannot be started and this is reflected in the log. How it might be related to Appium?

**Comment by VasaviUppada** [comment] 2017-10-18 07:27
In that case, app shouldn’t be launched when we run the same through Xcode.
But it is working fine there. I can able to launch app successfully.

Well, if that’s the issue, any other suggestions to resolve this issue are
appreciated.

**Comment by imurchie** [comment] 2017-10-18 12:12
Are you sure that the version you are attempting to install using Appium is not built differently than the one you install/run from Xcode? What if you install/run from Xcode, then use the `bundleId` capability (deleting the `app` capability) to run _that_?
