### ISSUE TITLE
Appium XCUITest WebDriverAgent stop connection after swipe

### ISSUE THREAD

**Issue by rutin31** [appium/appium#9122] opened 2017-08-30 11:16 UTC
## The problem
I run C# test on iphone real device
I have to get OTP code from notification msg. After success swipe function and find element by xpath I got exception on Visual studio:
A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL <XXX>
 The status of the exception was KeepAliveFailure, and the message was: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.

Appium logs for findelement after swipe

debug] [XCUITest] Connection to WDA timed out

[debug] [iProxy] recv failed: Operation not permitted

## Environment

* Appium version 1.6.5
* Desktop OS/version macOS Sierra 10.12.5
* Node.js version v8.1.0
* Mobile platform/version 10.1.1
* Real device 

## Link to Appium logs

[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":187,"y":3}},{"action":"wait","options":{"ms":3000}},{"action":"moveTo","options":{"x":0,"y":530}},{"action":"release"}],"f8196556-7e37-428f-8b03-eb8cfdc3c072"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"x":187,"y":3})-wait(options={"ms":3000})-moveTo(options={"x":0,"y":530})-release
[debug] [XCUITest] Found matching gesture: drag
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8100/session/4E57CD02-AC97-42F3-8258-CF7566B51D5B/wda/dragfromtoforduration] with body: {"fromX":187,"fromY":3,"toX":187,"toY":533,"duration":3}
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.5","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 14 ms - 83 
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"4E57CD02-AC97-42F3-8258-CF7566B51D5B","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/f8196556-7e37-428f-8b03-eb8cfdc3c072/touch/perform 200 7822 ms - 76 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.5","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 13 ms - 83 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.5","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 14 ms - 83 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.5","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 15 ms - 83 
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",120000,"f8196556-7e37-428f-8b03-eb8cfdc3c072"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] Set implicit wait to 120000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/f8196556-7e37-428f-8b03-eb8cfdc3c072/timeouts 200 9 ms - 76 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.5","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 16 ms - 83 
[HTTP] --> POST /wd/hub/session/f8196556-7e37-428f-8b03-eb8cfdc3c072/element {"using":"xpath","value":"//XCUIElementTypeCell[contains(@label,'MESSAGES')][1]"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeCell[contains(@label,'MESSAGES')][1]","f8196556-7e37-428f-8b03-eb8cfdc3c072"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 120000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/4E57CD02-AC97-42F3-8258-CF7566B51D5B/element] with body: {"using":"xpath","value":"//XCUIElementTypeCell[contains(@label,'MESSAGES')][1]"}
[HTTP] <-- POST /wd/hub/session/f8196556-7e37-428f-8b03-eb8cfdc3c072/element - - ms - - 
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"DD687094-AE4E-456C-9E26-69C06D40D73C","type":"XCUIElementTypeCell","label":"MESSAGES, 3m ago, , code  8938"},"sessionId":"4E57CD02-AC97-42F3-8258-CF7566B51D5B","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"DD687094-AE4E-456C-9E26-69C06D40D73C","type":"XCUIElementTypeCell","label":"MESSAGES, 3m ago, LeumiCard, לקוח לאומי קארד, קוד האימות שלך הינו 8938"}
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.5","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 15 ms - 83 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.5","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 15 ms - 83 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.5","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 13 ms - 83 
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[HTTP] --> DELETE /wd/hub/session {}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 2 ms - 57 
[HTTP] --> DELETE /wd/hub/session/1de421e3-e3de-499d-bbc5-311f369f1382 {}
[HTTP] <-- DELETE /wd/hub/session/1de421e3-e3de-499d-bbc5-311f369f1382 404 2 ms - 131 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.5","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 126 ms - 83 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.5","revision":null}}

code for swipe:
 var size = Driver.Manage().Window.Size;
                int y_start = 3;
                int y_end = (int)(size.Height * 0.80);
                int x = size.Width / 2;
                Driver.Swipe(x, y_start, x, y_end, 3000);

**Comment by mykola-mokhnach** [comment] 2017-08-30 11:55
This might be a duplicate of https://github.com/facebook/WebDriverAgent/issues/552
or
https://github.com/facebook/WebDriverAgent/issues/675

Unfortunately, there is nothing we can improve on Appium side.

**Closed by mykola-mokhnach** 2017-08-30 11:55 UTC
