### ISSUE TITLE
implicit_wait not work when an element could not be located on the page

### ISSUE THREAD

**Issue by robin-xl** [appium/appium#10809] opened 2018-06-06 08:49 UTC
## The problem

Running test on android real device with uiautomator2, after init python driver, call `/session/:session_id/timeouts/implicit_wait` set wait time for 20000ms, when an element not be find in de page, the endpoint "/element" response immediately not wait 20s.

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.1
* Last Appium version that did not exhibit the issue (if applicable):1.7.2
* Desktop OS/version used to run Appium: macOS 10.13.5
* Node.js version (unless using Appium.app|exe):v8.11.2
* Mobile platform/version under test: android/5.1.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

firstly, call endpoint `/timeouts/implicit_wait` set 20000ms,
secondly, call endpoint "/element",
finally, the element not located on the page, appium not wait for this element for 20s, and raise Encountered internal error

Hope set implicit_wait time work. 

## Link to Appium logs

 [Appium log](https://gist.github.com/robin-xl/5af9fafce9de3a0e388d2a516aeb471e)

**Comment by mykola-mokhnach** [comment] 2018-06-07 07:11
It is not fully fixed yet. https://github.com/appium/appium-base-driver/pull/218 should be published first, so then you can test it by installing appium@beta

**Comment by zuzeac** [comment] 2018-06-07 07:15
Hi,
I updated the appium-android-driver to 3.0.2 were I saw that the fix is included.
But for me it seems it doesn't work. The test will stop if the element is not found in less that 1-2 sec, and I have implicit wait set to 20 sec.

appium log:
gist:3e9307c5d6d882a2f151dfdbb44ddec0

**Comment by robin-xl** [comment] 2018-06-07 13:31
As @Mykola Mokhnach  say, it will be fix in the beta version, just wait.

2018-06-07 15:15 GMT+08:00 zuzeac <notifications@github.com>:

**Comment by mykola-mokhnach** [comment] 2018-06-07 14:06
The fix is published, so it can be tested now. Do not forget to make sure the version of appium-base-driver component is 2.32.0+

**Comment by robin-xl** [comment] 2018-06-08 03:35
upgrade appium to 1.8.2-beta
It alse has the same problem, Is there some info i miss?
[dependencies](https://gist.github.com/robin-xl/19931b8d37469e87768ad8dbe6bc55fb)
[appium log](https://gist.github.com/robin-xl/36b281fa6a81c93607d2e1ce53166847)

**Comment by zuzeac** [comment] 2018-06-08 05:58
I think we need to update the appium-base-driver to 2.32.1 not appium server.

**Comment by mykola-mokhnach** [comment] 2018-06-08 06:15
Nah, it's all good, but requires more corrections. I've created one more PR: https://github.com/appium/appium-base-driver/pull/220

**Comment by mykola-mokhnach** [comment] 2018-06-11 05:38
The fix should be published in beta. Credits to @jlipps ;)

**Closed by mykola-mokhnach** 2018-06-11 05:38 UTC
Labels: Android, Bug, NeedsInfo, UIAutomator2

**Comment by zuzeac** [comment] 2018-06-12 06:35
Hi @mykola-mokhnach ,

Not sure if I'm doing it right, but in my case still not working as expected. 
I update the appium-android-driver to 2.32.2 and still the same behaviour.

Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction@29c2c826 (tried for 1 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:303)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:271)

**Comment by vasogiamarelou** [comment] 2018-09-05 10:37
Hello any update on the above issue?
"appium": {"version": "1.9.0","appium-android-driver": "3.7.0"} and still appium responds immediately and does not wait.
