### ISSUE TITLE
Unable build a WebDriver agent. Getting xcodebuild failed with code 65

### ISSUE THREAD

**Issue by ashwithpoojary98** [appium/appium#17597] opened 2022-10-12 03:42 UTC
## Problem
Webdriver build agent failed with code 65
OS: MACOS Monterey
Version: 12.6
Chip: Apple
Appium Version: 1.22.3
Xcode version: 14.0.1
Device: IPAD pro/Simulator iPhone 16 Pro 
Version: 15.7/16.0

**Logs**
[test.log](https://github.com/appium/appium/files/9761269/test.log)

**I tried this also**
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by mykola-mokhnach** [comment] 2022-10-12 05:02
Duplicate of https://github.com/appium/appium/issues/17174

**Closed by mykola-mokhnach** 2022-10-12 05:02 UTC
