### ISSUE TITLE
Encountered internal error running command: Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: [object Object] unknown error: Failed to forward ports to device 03157df3441aae36

### ISSUE THREAD

**Issue by mskhan2345** [appium/appium#13250] opened 2019-09-17 13:28 UTC
Logs: Android 7.0 Device, Browser opens and closed immediately giving Failed to Forward ports to Device
[Chromedriver] Chromedriver version: '77.0.3865.40'
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[WD Proxy] Got response with status 200: "{\"value\":{\"build\":{\"version\":\"77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442})\"},\"message\":\"ChromeDriver ready for new sessions.\",\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"10.0.18362\"},\"ready\":true}}"
[WD Proxy] Determined that the downstream protocol for proxy is W3C
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"03157df3441aae36"},"loggingPrefs":{"browser":"ALL"}}}
[WD Proxy] Got response with status 200: {"sessionId":"c592bd46d39b7324ca139de64997485b","status":13,"value":{"message":"unknown error: Failed to forward ports to device 03157df3441aae36: . unknown error: The adb command failed. Extra response: <>.\n  (Driver info: chromedriver=77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}),platform=Windows NT 10.0.18362 x86_64)"}}
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[Chromedriver] Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: [object Object] unknown error: Failed to forward ports to device 03157df3441aae36: . unknown error: The adb command failed. Extra response: <>.
[Chromedriver]   (Driver info: chromedriver=77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}),platform=Windows NT 10.0.18362 x86_64)
[Chromedriver]     at Object.wrappedLogger.errorAndThrow (C:\Users\mohkhan4\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:78:13)
[Chromedriver]     at errorAndThrow (C:\Users\mohkhan4\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:493:13)

**Comment by mykola-mokhnach** [comment] 2019-09-17 13:31
Duplicate of https://github.com/appium/appium/issues/13239

**Closed by mykola-mokhnach** 2019-09-17 13:31 UTC
