### ISSUE TITLE
WebDriverAgentLib error when trying to build

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#7022] opened 2016-10-14 13:55 UTC
WebDriverAgentLib error when trying to build

Hello. I`m trying to use Appium 1.6 + xCode 8 + iOS10 on a real device and i encounter some problems.
The last one which i cannot pass is related to WebDriverAgentLib. Previosly when i was starting to run a test i got the message with signing certificate. I opened webDriverAgebtLib.xcodeproj, added automatically sign and team (which is the same one as the ipa file). But...when i hit build to WebDriverAgentLib i got tons of errors.
## Environment
- Appium version 1.6
- Desktop OS/version : MacMini, OsX El Capitan 10.11.6
- Node.js : 6.8.0
- Mobile platform: iOS10
- Real device
- Appium CLI or Appium.app|exe:

Please see attached screenshots.
![27f5e9a0d5f39be35860f69de240853c577d9096a2e7d60f5d pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/22839217/19389994/da349aa8-922e-11e6-8efd-686a6426c794.png)
![b33d98ffb5920148a17c48945f0d02bc48265b05b880c6eb55 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/22839217/19389995/da3581d4-922e-11e6-8465-7f4d0fcbd0a9.png)

**Comment by imurchie** [comment] 2016-10-14 14:39
Try running Appium with an xcode config file instead.

https://github.com/appium/appium-xcuitest-driver#real-devices

**Comment by vjmaiky** [comment] 2016-10-14 14:46
Resolved the problem with WebDriverAgent. now it builds with success; but still i got the error with signing

**Comment by vjmaiky** [comment] 2016-10-14 14:54
So i put the WebDriverAgent runner to automaticall and put there the development team and certificate. I also have a config file with those value and added it as a capability on project. Still no result..now i get WebDriverAgentLib has conflicting provisioning settings. WebDriverAgentLib is automatically signed, but code signing identity iphone dev....    has been manually specified. Set the code signing identity value to "iPhone Developer" in the build settings editor, or switch to manual signing in the project editor.

**Comment by vjmaiky** [comment] 2016-10-14 15:16
I tried also to put the same for development team in xcode and commented the capability for xcode config file. 
"Open WebDriverAgent.xcodeproj in Xcode. Select your development team for both the WebDriverAgentLib and WebDriverAgentRunner targets. This should also auto select Signing Ceritificate"

I have the same think as in screenshot.

But now i get this: Signing for "WebDriverAgentRunner" requires a development team. Select a development team . Select a development team in the project editor. Code signing is required for product type "UI Testing BUndle: in SDK "IOS 10.0"....

Any resolution?

**Comment by imurchie** [comment] 2016-10-14 17:51
Is this in Xcode or in an Appium session?

I would, personally, would reset everything in Xcode and just use the config file.

**Comment by vjmaiky** [comment] 2016-10-14 18:08
Error is displayed in Appium session. I tried too many things and now my head is messed up....
So:
1. i have an ipa file (the application) created by one of my devs (it is already signed with a certificate)
2. my automation setup manages to install it on my real device, but when tries to open it, i got that error that the app needs to be signed 
3. I used WebDriverAgent.xcodeproj and added that auto sign for both (lib and runner)..but still i got that error
4. I created a local file like this, and added as a capability+path in my project..but now i got the conflict part
DEVELOPMENT_TEAM = <Team ID>
CODE_SIGN_IDENTITY = iPhone Developer
5. I`ll try to reset WebDriverAgent.csproj and use only the config file...but i wonder why that does not work from the start..because ipa file is already signed with a certificate used for automation runs for ios8 and ios9...
6. What i do not get it with this config file (in that forum post it says that should be on device..that means on the phone...but on the phone i have only the certificate installed and the config file on my mac machine and used as a capability + path in project..is this correct? i cannot try it now because i`m no longer at work..

p.s. thank you for all your support; i really appreciate it

**Comment by imurchie** [comment] 2016-10-14 18:16
The config file should be on your hard drive, with the full path sent to the Appium server using the `xcodeConfigFile` desired capability. The team and identity in it are used to sign the WebDriverAgent system, which needs to be signed because it _also_ (in addition to your own app) needs to be installed onto the device.

Apple has, once again, made everything as hard as possible. :(

**Comment by imurchie** [comment] 2016-10-14 18:17
The config file should be something like:

```
DEVELOPMENT_TEAM = <Team ID>
CODE_SIGN_IDENTITY = iPhone Developer
```

Where `<Team ID>` is a 10-character string generated by Apple, retrievable from the Apple development website.

**Comment by imurchie** [comment] 2016-10-14 18:19
Another thing of note is that the WebDriverAgent "running" involves opening, and then going into the background. There is no UI involved.

**Comment by vjmaiky** [comment] 2016-10-18 08:43
Ok..i did the automatically signing from xCode for webdriveragent and it worked (after i run xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test).....an ipa is intalled on device and when i run it i get what is written here: "Last line on build output above command should be Listening on USB. Then you are all set!". So it works for this case.

But when i run my tests, i still get the missing signing certificate..so i guess that it is a problem with my test setup..something is no longer valid...

**Comment by vjmaiky** [comment] 2016-10-18 10:59
DesiredCapabilities capabilities = new DesiredCapabilities();

capabilities.setCapability("appium-version", APPIUM_VERSION);
capabilities.setCapability("platformName", PLATFORM_NAME);
capabilities.setCapability("platformVersion", IOS_VERSION);
capabilities.setCapability("deviceName", DEVICE_NAME);
capabilities.setCapability("app", APP_LOCATION);
if (!IS_SIMULATOR) {
capabilities.setCapability("udid", DEVICE_UDID);
}
capabilities.setCapability("newCommandTimeout", TIMEOUT_COMMAND);
capabilities.setCapability("automationName", AUTOMATION_NAME); (XCUITest is the name)
capabilities.setCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
// capabilities.setCapability("xcodeConfigFile", "/Users/Shared/Appium/myconfig.xcconfig");
// capabilities.setCapability("keychainPath", "/Users/Shared/Appium/certificate");
// capabilities.setCapability("keychainPassword", "password");

**Comment by vjmaiky** [comment] 2016-10-18 11:00
List with my capabilities

**Comment by imurchie** [comment] 2016-10-18 13:24
Why is the xcode config capability commented out?

**Comment by vjmaiky** [comment] 2016-10-18 13:29
because when i run me test it says that there is a conflict...

WebDriverAgentLib has conflicting provisioning settings. WebDriverAgentLib is automatically signed, but code signing identity iphone dev.... has been manually specified. Set the code signing identity value to "iPhone Developer" in the build settings editor, or switch to manual signing in the project editor.

**Comment by imurchie** [comment] 2016-10-18 13:32
And if you do the opposite? No fiddling with Xcode, just using the config file?

**Comment by vjmaiky** [comment] 2016-10-18 13:32
it says that no certificate was found for the development ID which i wrote in that config file...

**Comment by imurchie** [comment] 2016-10-18 13:34
And the id is correct and the added to Xcode locally?

**Comment by vjmaiky** [comment] 2016-10-18 13:37
- the id is the same as the one which we signed the ipa file/our app (the 10 characters code); 
- in MobileDriverAgent.xcodeproj i changed manually to use that specific certificate
- still not working...

**Comment by vjmaiky** [comment] 2016-10-18 14:13
ok..suddenly it started to work...i just shut down the mac..put again on manual settings de mobileagentdriver.xcodeproj using my certificate..run appium and a test and it run...i also commented out all capabilities with config, and keychain....

**Comment by imurchie** [comment] 2016-10-18 14:14
Weird. Glad it is working, though.

**Comment by vjmaiky** [comment] 2016-10-18 14:26
short update..found the key..so:

1. i have my old project setup (nothing changed beside adding the new capability for XCUItest, and other prerequisites to work on iOS10)
2. in WebDriverAgent i put on manual settings and manually selected the certificate and saved changes
3. In OLD APPIUM version i just modified the new information about device and hit the inspector button; EVEN IF you got the ERROR after pressing the button go to terminal and type appium (appium server for 1.6 will start)
4. Run the test and it will work....

NOTE: if i skip step 3 it will not work..it will crash on startup

**Comment by andreiaionitoaiesv** [comment] 2016-10-25 14:41
Hey,

Have the same issue, but the solution provided is not working for me. I think I'm going crazy. 
@imurchie 
Having the same issues with the WebDriverAgentRunner signing problems. I've made all the steps that @vjmaiky described in this ticket. I tried setting development team automaticaly from xCode workspace, i tried setting manually, i tried sending a config file through desired capabilieties, nothing seems to work. Can't find a solution, please help. 

2016-10-25 14:36:27:345 - info: [Xcode]  Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
 Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'
 TEST FAILED 
The following build commands failed:
 Check dependencies
(1 failure)
2016-10-25 14:36:27:379 - info: [XCUITest] xcodebuild exited with code '0' and signal 'null'
2016-10-25 14:36:46:418 - debug: [XCUITest] Waiting for WebDriverAgent server to finish loading...
2016-10-25 14:37:08:787 - debug: [XCUITest] Waiting for WebDriverAgent server to finish loading...
2016-10-25 14:37:40:645 - debug: [XCUITest] Waiting for WebDriverAgent server to finish loading...
2016-10-25 14:38:08:686 - debug: [XCUITest] Waiting for WebDriverAgent server to finish loading...
2016-10-25 14:38:35:367 - debug: [XCUITest] Waiting for WebDriverAgent server to finish loading...

**Comment by mykola-mokhnach** [comment] 2016-10-25 15:15
@andreiaionitoaiesv Please provide your Xcode log. The given details won't help much to solve the problem.

**Comment by andreiaionitoaiesv** [comment] 2016-10-25 15:35
[log(1).txt](https://github.com/appium/appium/files/551032/log.1.txt)

Here are the logs.

Thanks

**Comment by mykola-mokhnach** [comment] 2016-10-25 15:42
@andreiaionitoaiesv You have to sign both the library and the runner. The right way to test it is to execute runner in Test mode or you can try the same command that appium generates from the terminal

**Comment by andreiaionitoaiesv** [comment] 2016-10-26 05:50
@mykola-mokhnach 
I've already sign both the library and the runner, manually or automatically. I receive the same error. Here are the short version of the logs for Test mode.  
[log_test_mode.txt](https://github.com/appium/appium/files/552410/log_test_mode.txt)

Thanks

**Comment by andreiaionitoaiesv** [comment] 2016-10-26 05:54
Also here I've added search path for the frameworks, found this issue online but the error above is still reproducing. 
![screen shot 2016-10-26 at 08 52 41](https://cloud.githubusercontent.com/assets/14057245/19714821/c1f73d86-9b59-11e6-9e78-15a975c8d8a4.png)

**Comment by vjmaiky** [comment] 2016-10-26 08:03
Hello @andreiaionitoaiesv here are some thing that i did before starting to work:

1. after you open WebDriverAgent.xcodeproj, be sure that all dependencies are downloaded for it (nothing should be displayed with red in frameworks, etc.) - there is a script which you need to run in webdriveragent directory
2. On WebDriverAgentLib be sure that on Signing Debug/Release you add the development team id (be sure that it`s the same as the certificate you use in keychain and that is the same which you signed your ipa file)
3. After that switch to WebDriverAgentRunner and in Signing Debug/Release select the profile which is installed on our mac (the same as above)
4. Save configuration and build both lib and runner
5. Be sure that on your project you add the new capabilities for automationName - XCUITest and realDeviceLogger (i commented out the xcodeconfigfile, keychainpath, and keychainpassword)
6. Open terminal and type appium and after that start your test (it should work)

Hope it helps you.
Br,
maiky

**Comment by andreiaionitoaiesv** [comment] 2016-10-26 08:17
@vjmaiky 
Thanks for the response. 
1. When I run the bootstrap script with parameter -d , it remains in a state "Fetching dependicies" .
If I run with -d parameter it fails on building Inspectpr/app.js.

![error_bootstrap_script](https://cloud.githubusercontent.com/assets/14057245/19718249/374c51d0-9b6d-11e6-9d3a-cc422d8547ae.png)
![linked_frameworks](https://cloud.githubusercontent.com/assets/14057245/19718250/37671574-9b6d-11e6-9e57-08f5d671f835.png)

2. and 3. Both are signed with the development ID. I'm sure that is correct certificate since I can build and install the app on the real device from the xcode project workspace.
4. Build succeeds from xcode WebDriverAgend project workspace.
5. Already added the capabilities needed.

![desired_caps](https://cloud.githubusercontent.com/assets/14057245/19718371/b4b9d520-9b6d-11e6-8360-866af3772c5a.png)

6. Test failed with the error from the logs above( Signing issues for WebDriverAgentRunner)

**Comment by vjmaiky** [comment] 2016-10-26 08:21
Until you don`t solve the problem with WebDriverAgent dependencies i think you cannot run the tests.

i used this (https://github.com/appium/appium-xcuitest-driver#real-devices) :

Open terminal go to node_modules/appium-xcuitest-driver/WebDriverAgent (this path is relative to your appium installation).

mkdir -p Resources/WebDriverAgent.bundle
sh ./Scripts/bootstrap.sh -d

**Comment by vjmaiky** [comment] 2016-10-26 08:22
you need somehow to run that script to add the dependencies (also be sure that script is phisically there)

**Comment by andreiaionitoaiesv** [comment] 2016-10-26 08:26
Already did those steps. That's why I ask for your help, because I've ran out of options and google pages:)

**Comment by mykola-mokhnach** [comment] 2016-10-26 08:39
![screenshot](https://cloud.githubusercontent.com/assets/7767781/19719026/671b134c-9b68-11e6-9526-ef66109d7cda.png)

**Comment by imurchie** [comment] 2016-10-26 09:10
The script with print `Fetching dependencies" and then exit if the dependencies are already fetched. Appium will do this automatically, though. There is no reason to do it manually.

**Comment by andreiaionitoaiesv** [comment] 2016-10-26 09:24
Added the XCTestFramework. Ran the xcodebuil test for the WebDriverAgent project with WebDriverAgentRunner scheme...still fails. Here are the logs: 
[test_log.txt](https://github.com/appium/appium/files/552856/test_log.txt)


![runner](https://cloud.githubusercontent.com/assets/14057245/19720478/f628c9c2-9b76-11e6-894a-f951750eba9a.png)
![lib](https://cloud.githubusercontent.com/assets/14057245/19720479/f62af4b8-9b76-11e6-9002-f6ceedf3cdb0.png)

Also something weird happens when I run the test command from terminal. The WebDriver is installed on the phone but it just flickers, like opening and closing, opening and closing.....

**Comment by vjmaiky** [comment] 2016-10-26 10:13
Let it on manual (uncheck automatically manage signing) and add manually on both lib and runner. I`m using on manual configuration.

**Comment by andreiaionitoaiesv** [comment] 2016-10-28 10:11
I revoked and created a new certificate and now when I run the test command:
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=XXXXXXXX' test
The output is "Listening on USB'...this is good. But when I run my tests I receive the same error, that one with WebDriverAgentRunner needs a development team...

Summary:
Run WebDriverAgent project from Xcode workspace -> build ok.
Run WebDriverAgent project with test command from terminal -> all is ok.
Start the test -> WebDriverAgentRunner error - Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
 Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'

**Comment by imurchie** [comment] 2016-10-28 11:10
@andreiaionitoaiesv Can you try the command that appium uses to run xcodebuild? It is in the logs. Otherwise it is hard to say.

**Comment by vjmaiky** [comment] 2016-10-28 12:13
I`ll post some screenshots with my configuration...maybe it helps. And also be sure that you have installed web driver agent on your phone (if can run this command with your UDID  xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test)
![screen shot 2016-10-28 at 14 57 51](https://cloud.githubusercontent.com/assets/22839217/19806079/03f5f5a6-9d21-11e6-93c5-84c1e8198af3.png)
![screen shot 2016-10-28 at 14 58 40](https://cloud.githubusercontent.com/assets/22839217/19806080/03f7a2de-9d21-11e6-9013-7d011aa2ba5c.png)
![screen shot 2016-10-28 at 14 59 13](https://cloud.githubusercontent.com/assets/22839217/19806081/03fab866-9d21-11e6-925d-65c661279e32.png)

**Comment by andreiaionitoaiesv** [comment] 2016-10-28 14:08
@imurchie 

Here is the log running that command. 
[log_appium.txt](https://github.com/appium/appium/files/558578/log_appium.txt)

**Comment by imurchie** [comment] 2016-10-28 14:26
If you're insisting on doing it manually, click "Automatically manage signing" on both targets.

**Comment by andreiaionitoaiesv** [comment] 2016-10-28 14:47
I tried with automatically on both targets.

**Comment by imurchie** [comment] 2016-11-01 21:05
And?

**Comment by andreiaionitoaiesv** [comment] 2016-11-03 12:35
I've tried reinstalling node and it worked. Feel free to close this issue.

**Comment by SrinivasanTarget** [comment] 2016-11-03 16:40
@triager please close

**Closed by SrinivasanTarget** 2016-11-03 16:40 UTC
Labels: NeedsTriage

**Comment by JasonZhu0603** [comment] 2016-12-16 10:47
@imurchie  One Quick question for the appium, for the appium@1.6.3, I could start the WebDriverAgent, and it would listen to the device:8100, I could using curl deviceIp:8100 to see sth, and of course I could send the api of the WebDriverAgent to start the app in the real device, and but the appium never launch the app under test, do i miss any component? 

I installed following:
1 :Latest Node js
2: appium 1.6.3
3: ideviceinstaller
4: xpretty

and the WebDriverAgent could start without problem since I sign for WebDriverAgent and WebDriverLib, it looks good since I launched from the Xcode and the command line, I do it manually from Xcode.

So I think I am good with all staff needed for Appium? Do I really miss anything? Please help Point out.

It really stuck me for a while. Thanks in advance. 

Thanks
Jason

**Comment by JasonZhu0603** [comment] 2016-12-16 10:52
@vjmaiky 

For the steps you mentioned, below, do u mea the signing cert need to be same for WebDriverAgentLib and the app under test? Really?

"On WebDriverAgentLib be sure that on Signing Debug/Release you add the development team id (be sure that it`s the same as the certificate you use in keychain and that is the same which you signed your ipa file)"

**Comment by imurchie** [comment] 2016-12-16 12:17
@JasonZhu0603 Can you post the full Appium logs as a [gist](https://gist.github.com)? Otherwise I have no idea.

**Comment by chanugithub** [comment] 2017-11-17 23:46
@andreiaionitoaiesv hello, you just tried reinstalling node and it worked.
Can you please explain in detail, i am unable to resolve this code sign error with correct sign in  ids,
 thanks
