### ISSUE TITLE
[iOS] An element command failed because the referenced element is no longer attached to the DOM.

### ISSUE THREAD

**Issue by gauravgandhi1315** [appium/appium#16432] opened 2022-02-09 21:13 UTC
## The problem

Im trying to enter username in the text field and seeing this error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Desktop OS/version used to run Appium: Mac Big Sur
* Node.js version (unless using Appium.app|exe): 12.22.0
* Mobile platform/version under test: iOS, iPhone X Simulator
* Real device or emulator/simulator: Simulator iOS 15.0

```
It works fine on Android with no issues.
get userId() {
    return $('[class*="form-group-dls-color-text"]>div');
  }

 browser.pause(WAIT_TIME.LONG);
 this.userId.setValue(username);
```

Has anyone seen this issue before?

**Comment by mykola-mokhnach** [comment] 2022-02-09 21:19
Please provide the full server log

**Comment by gauravgandhi1315** [comment] 2022-02-09 21:46
> Please provide the full server log
![Screen Shot 2022-02-09 at 4 37 48 PM](https://user-images.githubusercontent.com/66381899/153294765-3a39ad2b-f0c4-4b52-a3c1-760c0d75ef8c.png)
![Screen Shot 2022-02-09 at 4 37 55 PM](https://user-images.githubusercontent.com/66381899/153294766-922656c3-fc30-4450-8169-79349b6068cb.png)
[logs.docx](https://github.com/appium/appium/files/8036426/logs.docx)

**Comment by mykola-mokhnach** [comment] 2022-02-09 22:39
Please provide the log as gist. A simple text would do as well

**Comment by mykola-mokhnach** [comment] 2022-02-09 22:41
It also makes sense to try the most recent server version (only available in Appium2)

**Comment by mykola-mokhnach** [comment] 2022-02-09 22:43
Closing this one as duplicate of https://github.com/appium/appium/issues/16354. Please continue the thread in the original issue

**Closed by mykola-mokhnach** 2022-02-09 22:43 UTC
Labels: NeedsInfo

**Comment by gauravgandhi1315** [comment] 2022-02-09 23:04
@mykola-mokhnach It doesn't look like the same issue. Please reopen

**Comment by mykola-mokhnach** [comment] 2022-02-09 23:06
Why it does not? Same error, same platform

**Comment by gauravgandhi1315** [comment] 2022-02-10 14:48
@mykola-mokhnach its not the same error
