### ISSUE TITLE
Issue from my side Android, 10, Redmi device

### ISSUE THREAD

**Issue by Lakshmanan4233** [appium/appium#17126] opened 2022-07-04 04:43 UTC
<img width="311" alt="Snag_29931bb" src="https://user-images.githubusercontent.com/96466534/177082847-b0e188aa-2f79-45d2-a061-757d88888ae1.png">

Failed to create session. An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\ShalliniPA\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s c3624d4a9907 install -g 'C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk'' exited with code 1'; Command output: adb: failed to install C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk: Security exception: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:553) at com.android.server.pm.PackageInstallerService.createSession(Package

Please.Shall you tell the probelm

**Comment by mykola-mokhnach** [comment] 2022-07-04 05:03
Duplicate of https://github.com/appium/appium/issues/13301

**Closed by mykola-mokhnach** 2022-07-04 05:03 UTC

**Comment by Lakshmanan4233** [comment] 2022-07-04 05:11
Thank you for your response. it is working
