### ISSUE TITLE
Unable to turn off wifi with appium 2.0.0-beta.35

### ISSUE THREAD

**Issue by Jiyvn** [appium/appium#16941] opened 2022-05-13 07:36 UTC
## The problem

Unable to turn off wifi with appium 2.0.0-beta.35 but with appium 1.22.2

## Environment
using: https://github.com/appium/appium-docker-android with appium@next
* Appium CLI: 2.0.0-beta.35 installed by npm
* Last Appium version that did not exhibit the issue (been used for testing): 1.22.2
* Drivers (only for Appium2): 
    * uiautomator2@2.1.1
* Node.js: v12.22.12/v16.15.0
* Mobile devices: 
    - nokia7.2: android 10
    - nokia g50: android 12
    - samsung s22: android 12
    - samsung a52: android 11
* android SDK (the same between v1.22.2 && 2.0.0-beta.35)
![image](https://user-images.githubusercontent.com/73217816/168231338-c500f306-b743-4253-a93c-482697a25617.png)
* java-client: 7.3.0/8.0.0

## Details
removed these apps before each trial
- io.appium.settings
- io.appium.uiautomator2.server
- io.appium.uiautomator2.server.test

ps: using io.appium.settings installed by appium 2.0 with appium 1.22.2 will also fail the wifi action

## Link to Appium logs
appium/adb logs for 2.0 and 1.22.2: https://gist.github.com/e74a6f025a5e5ca566b77207c7e52cc8.git

timestamp of turn off wifi: 
(appium log in US/Pacific, but looks like timestamp is incorrect)
- 2.0: adb logcat > UTC+8, 05-12 18:09:42 - 05-12 18:09:43
- 1.22.2: adb logcat > UTC+8, 05-13 12:15:55 - 05-13 12:15:56

## Code To Reproduce Issue
```Java
((AndroidDriver) driver).setConnection(new ConnectionStateBuilder().withWiFiDisabled().build());
```

**Comment by mykola-mokhnach** [comment] 2022-05-13 08:37
I assume the newer Appium Settings version which is bundled with newer UIA2 driver has compatible SDK number bumped. Android applies stricter security limitations to it, thus denying to change the wifi state even though the source code is still the same. 

Please let us know if there is any available API, which allows to change global WiFi state since Android10

**Comment by Jiyvn** [comment] 2022-05-13 17:28
@mykola-mokhnach 
appium v1.22.2 and appium 2.0 shares the same Android SDK (API 29) and the same devices. but it works on v1.22.2 while fails on v2.0.0-beta35

according to my trials, the adb command that seems invoked by driver uiautomator2 is actually ineffective on both appium v1.22.2 and v2.0.0-beta35 (https://github.com/appium/appium/issues/12327) 
`adb shell am broadcast -a io.appium.settings.wifi -n io.appium.settings/.receivers.WiFiConnectionSettingReceiver --es setstatus disable`
however, it works using `setConnection` with appium v1.22.2 but not appium v2.0.0-beta35. 

could it be the appium settings/UIA2 driver changes between v1.22.2 and v2.0.0-beta35 leading to this issue?
will check other SDK API if I am available, and I might double check the adb command

**Comment by mykola-mokhnach** [comment] 2022-05-13 17:51
It would be nice if you could investigate it further and/or find a reliable way to change wifi state on Android real devices

**Comment by Jiyvn** [comment] 2022-05-16 06:39
@mykola-mokhnach 
`runAppInBackground`/`pressKey(new KeyEvent(AndroidKey.HOME))` will kill app with appium 2.0.

**Comment by Jiyvn** [comment] 2022-05-16 08:58
@mykola-mokhnach 
I've tried adb command again.
```
adb shell am broadcast -a io.appium.settings.wifi -n io.appium.settings/.receivers.WiFiConnectionSettingReceiver --es setstatus disable
```
adb command with appium 1.22.2 `io.appium.settings` works while fails with appium 2.0.0-beta35 `io.appium.settings`
That means adb command could work, I think it could be fixed on `io.appium.settings` side?

**Comment by KazuCocoa** [comment] 2022-05-16 10:05
The WiFi command did not work on my Nokia7.2 Android 11 device with appium 1.22.3. (`3.4.0` was the version of `io.appium.settings` as same as 1.22.2) as `setWifiEnabled not allowed for uid=10115` error. Potentially these are particular conditions(?) in addition to the SDK version.

**Comment by Jiyvn** [comment] 2022-05-16 10:21
> I think I have already explained the reason for such behaviour above. It won't be an acceptable solution for us to lower the supported SDK version, Google would anyway close it sooner or later.

got it

**Comment by Jiyvn** [comment] 2022-05-16 10:43
> The WiFi command did not work on my Nokia7.2 Android 11 device with appium 1.22.3. (`3.4.0` was the version of `io.appium.settings` as same as 1.22.2) as `setWifiEnabled not allowed for uid=10115` error. Potentially these are particular conditions(?) in addition to the SDK version.

@KazuCocoa tested again on 1.22.3. always succeed on my side. 
<img width="1555" alt="image" src="https://user-images.githubusercontent.com/73217816/168576034-70e473c3-5bfd-4c30-819c-5cf7aaa35276.png">


have you removed these three apps before testing with 1.22.3?
- io.appium.settings
- io.appium.uiautomator2.server
- io.appium.uiautomator2.server.test

**Comment by Jiyvn** [comment] 2022-05-16 10:56
@KazuCocoa 
checked our report, we have used appium 1.22.2 for 3 weeks on devices above(android 10/11/12), `setConnection` is always working
<img width="642" alt="image" src="https://user-images.githubusercontent.com/73217816/168577380-5254c210-86dd-46de-8c1b-1db6e9fff40a.png">

<img width="648" alt="image" src="https://user-images.githubusercontent.com/73217816/168578000-ab0de2d7-b330-40c6-b6ad-084ef3b701ab.png">

**Comment by KazuCocoa** [comment] 2022-05-16 16:34
My end hasn't worked since https://github.com/appium/appium/issues/12327#issuecomment-473611851 (Android 10 at that time), so only you can debug this for now. You can check in which version started this behavior. 1.22.2 and .3 had the 3.5.0.
https://github.com/appium/io.appium.settings

If the behavior is newer target SDK stuff (changes in app/build.gradle) since the 3.5.0, we cannot revert the change to keep updating Google's dependencies as https://github.com/appium/appium/issues/16941#issuecomment-1127412408

**Comment by Jiyvn** [comment] 2022-05-17 05:21
@KazuCocoa 
works on 3.4.0, ineffective on 3.5.0. but it's strange if 1.22.2 and .3 had the 3.5.0.
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/73217816/168729172-22b233f4-5ce8-4af5-9400-a9d5deb2f83a.png">

<img width="925" alt="image" src="https://user-images.githubusercontent.com/73217816/168729462-7dd6bc81-5696-4050-8c23-4fbfa3679355.png">

3.4.0 also fail to grant permission though able to turn on/off wifi
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/73217816/168734700-d7aa02bc-5b7e-4fc3-bd4c-72b46a59d109.png">

**Comment by KazuCocoa** [comment] 2022-05-17 06:07
Thank you. Then, maybe the compile sdk version affected..? Google probably has restricted the permission/access level etc that could change the system preference.

**Comment by Jiyvn** [comment] 2022-05-17 07:35
> @mykola-mokhnach `runAppInBackground`/`pressKey(new KeyEvent(AndroidKey.HOME))` will kill app with appium 2.0.

@KazuCocoa what about the background issue?

**Comment by KazuCocoa** [comment] 2022-05-17 08:13
What's it mean?
When you opened Home, then the app under test was brought to the background, then the app stopped... like this? Or io.appium.settings process was killed after calling `io.appium.settings/.receivers.WiFiConnectionSettingReceiver` and Home...? Then, how long did you wait?

I could not observe such process stop behavior via https://appium.io/docs/en/commands/device/app/app-state/ . They kept running in the background in my device.

**Comment by Jiyvn** [comment] 2022-05-17 11:09
first one
> When you opened Home, then the app under test was brought to the background, then the app stopped

log: https://gist.github.com/00bee6dac62d620df5d8b2a41b884113.git
background for 8 secs, timestamp: adb logcat > 2022-05-17 18:38:38-2022-05-17 18:38:50

**Comment by KazuCocoa** [comment] 2022-05-17 17:57
Like the below lines? (during 2022-05-17 18:38:38-2022-05-17 18:38:50)

It seems like the app under test (`com.viu.phone`?) changed the state to on stop by Android, and the app activity had `NullPointerException`.

```
05-17 18:38:51.509 32506   327 I DefaultDeliveryClient: Event: 'Home' recorded to local filestore
05-17 18:38:51.510 32506   327 D DefaultDeliveryClient: Time of enqueueEventForDelivery: 2
...
05-17 18:38:52.155 32506 32506 D viu_jinyifeng: ExpiredPrompt: 未初始化过期弹出日期表
05-17 18:38:52.158 32506 32506 W viu_jinyifeng: 
05-17 18:38:52.158 32506 32506 W viu_jinyifeng: java.lang.NullPointerException: Attempt to read from field 'com.ott.tv.lib.domain.LiveInfo$Data com.ott.tv.lib.domain.LiveInfo.data' on a null object reference
05-17 18:38:52.158 32506 32506 W viu_jinyifeng: 	at com.viu.phone.ui.activity.HomeActivity.changeTrailerTag(HomeActivity.java:1754)
05-17 18:38:52.158 32506 32506 W viu_jinyifeng: 	at com.viu.phone.ui.activity.HomeActivity.handleMessage(HomeActivity.java:1276)
05-17 18:38:52.158 32506 32506 W viu_jinyifeng: 	at com.ott.tv.lib.Interface.HandlerInterface$MyHandler.handleMessage(HandlerInterface.java:28)
05-17 18:38:52.158 32506 32506 W viu_jinyifeng: 	at android.os.Handler.dispatchMessage(Handler.java:107)
05-17 18:38:52.158 32506 32506 W viu_jinyifeng: 	at android.os.Looper.loop(Looper.java:214)
05-17 18:38:52.158 32506 32506 W viu_jinyifeng: 	at android.app.ActivityThread.main(ActivityThread.java:7397)
05-17 18:38:52.158 32506 32506 W viu_jinyifeng: 	at java.lang.reflect.Method.invoke(Native Method)
05-17 18:38:52.158 32506 32506 W viu_jinyifeng: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-17 18:38:52.158 32506 32506 W viu_jinyifeng: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
05-17 18:38:52.158 32506 32506 E viu_jinyifeng: 首页预告片Tag设置错误
05-17 18:38:52.158 32506 32506 I viu_jinyifeng: AppStartEvent ======= TaskChangeAreaNotice ====== loadTask
...
05-17 18:38:52.451 32506 32506 I System.out: Base activity----onStop====class com.viu.phone.ui.activity.WelcomeActivity
05-17 18:38:52.453 32506   328 W FlurryAgent: Flurry session paused for context:com.viu.phone.ui.activity.WelcomeActivity@d4558bc
05-17 18:38:52.458 32506 32543 D TransportRuntime.JobInfoScheduler: Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lDY2traUg4aTJaQVJ3T3MxTEV6RktsZDE1YU9HOG96S28=) is already scheduled. Returning...
05-17 18:38:52.478 32506 32506 I System.out: Base activity----onDestroy====class com.viu.phone.ui.activity.WelcomeActivity
05-17 18:38:52.488 32506 32543 D TransportRuntime.SQLiteEventStore: Storing event with priority=DEFAULT, name=FIREPERF for destination cct
05-17 18:38:52.499 32506 32543 D TransportRuntime.JobInfoScheduler: Upload for context TransportContext(cct, DEFAULT, 
```

Appium responded screenshot and orientation, but they were after the above onStop/Destroy event on probably your app log.

**Comment by Jiyvn** [comment] 2022-05-18 02:36
@KazuCocoa 
yes. 
 I capture the screen and reset orientation (for video playing) after the background is finished
`Appium responded screenshot and orientation`

it works with 1.22.2
log: https://gist.github.com/Jiyvn/09b5ada93431c83a4bd400f00451bd04
background for 8 sec, timestamp: adb logcat > 2022-05-18 10:13:57 - 2022-05-18 10:14:09

**Comment by KazuCocoa** [comment] 2022-05-18 04:32
I wonder if https://github.com/appium/appium-android-driver/pull/729/files affected your case.

```
05-17 18:38:47.904  2173  2173 D AndroidRuntime: Calling main entry com.android.commands.monkey.Monkey
05-17 18:38:47.904 32506   508 W GoogleTagManager: Bad response received for https://dev-audience-pccw.ottuat.com/image/?ep_device_id=undefined&device_id=undefined&event_name=user_engagement&ep_ga_action=undefined&gtmcb=844758348: 404
05-17 18:38:47.905  2173  2173 W Monkey  : args: [--pct-syskeys, 0, -p, com.viu.phone, -c, android.intent.category.LAUNCHER, 1]
05-17 18:38:47.905  2173  2173 W Monkey  :  arg: "--pct-syskeys"
05-17 18:38:47.905  2173  2173 W Monkey  :  arg: "0"
05-17 18:38:47.905  2173  2173 W Monkey  :  arg: "-p"
05-17 18:38:47.906  2173  2173 W Monkey  :  arg: "com.viu.phone"
05-17 18:38:47.906 32506   508 W GoogleTagManager: Error Message: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><title>404 Not Found</title><h1>Not Found</h1><p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
05-17 18:38:47.906  2173  2173 W Monkey  :  arg: "-c"
05-17 18:38:47.906  2173  2173 W Monkey  :  arg: "android.intent.category.LAUNCHER"
05-17 18:38:47.906  2173  2173 W Monkey  :  arg: "1"
05-17 18:38:47.906  2173  2173 W Monkey  : arg="--pct-syskeys" mCurArgData="null" mNextArg=1 argwas="--pct-syskeys" nextarg="0"
05-17 18:38:47.907  2173  2173 W Monkey  : data="0"
05-17 18:38:47.907  2173  2173 W Monkey  : data="com.viu.phone"
05-17 18:38:47.907  2173  2173 W Monkey  : data="android.intent.category.LAUNCHER"
05-17 18:38:43.407  1600  1955 I chatty  : uid=1000(system) InputReader identical 10 lines
```

vs


```
8 10:14:06.037 12498 12498 W Monkey  : args: [-p, com.viu.phone, -c, android.intent.category.LAUNCHER, 1]
05-18 10:14:06.037 12498 12498 W Monkey  :  arg: "-p"
05-18 10:14:06.037 12498 12498 W Monkey  :  arg: "com.viu.phone"
05-18 10:14:06.037 12498 12498 W Monkey  :  arg: "-c"
05-18 10:14:06.038 12498 12498 W Monkey  :  arg: "android.intent.category.LAUNCHER"
05-18 10:14:06.038 12498 12498 W Monkey  :  arg: "1"
05-18 10:14:06.038 12498 12498 W Monkey  : data="com.viu.phone"
05-18 10:14:06.038 12498 12498 W Monkey  : data="android.intent.category.LAUNCHER"
```

---


> --pct-syskeys <percent> | Adjust percentage of "system" key events. (These are keys that are generally reserved for use by the system, such as Home, Back, Start Call, End Call, or Volume controls.)


The option was needed to launch an activity on an emulator, but possibly it affected your case.

**Comment by KazuCocoa** [comment] 2022-05-18 04:44
Did you start the app with `activateApp` in the middle of a session?
The command currently calls monkey command as https://github.com/appium/appium-uiautomator2-driver#applications-management , maybe https://github.com/appium/appium-uiautomator2-driver#mobile-startactivity is safer in your case.

Could you try out with https://github.com/appium/appium-uiautomator2-driver#mobile-startactivity if it resolves current your issue?

**Comment by Jiyvn** [comment] 2022-05-18 06:34
> Did you start the app with activateApp in the middle of a session?

@KazuCocoa tested with `runAppInBackground ` above. 
but `pressKey(new KeyEvent(AndroidKey.HOME))` is actually combined with `activateApp`

I've tried monkey command with/without `--pct-syskeys 0`, they work normally.
`adb shell monkey --pct-syskeys 0 -p <pkg_name> -c android.intent.category.LAUNCHER 1`

**Comment by KazuCocoa** [comment] 2022-05-18 06:48
I wonder about sending HOME after the monkey command with `--pct-syskeys 0`. This is what I found, but i have no idea except for it for now.

https://github.com/appium/appium/issues/16941#issuecomment-1129157586 is the root cause, probably, if your package name is included in the stack trace. (Then, it also indicates the null pointer exception could occur in production)

**Comment by Jiyvn** [comment] 2022-05-18 07:35
@KazuCocoa 
also works well before/after `adb shell input keyevent 3/KEYCODE_HOME`

**Comment by Jiyvn** [comment] 2022-05-18 09:15
@KazuCocoa 
we found that some of devices do restart with `--pct-syskeys 0`, e.g. Samsung a52, while some work well with adb command but fail with appium

**Comment by SHI-ZP** [comment] 2022-05-18 10:24
Hi @KazuCocoa I tried to dig deeper in terms of the background issue between appium 1 and appium 2,

And find that the args feed to the ADB am cli will affect the behavior, I extracted the key adb cli from the appium logs then run them in 2 sets via my local terminal.

Nokia72 real device with Appium 1.22 approach--> normal app resume:
`adb -P 5037 -s {{uuid}} shell am start -W -n com.viu.phone/com.viu.phone.ui.activity.WelcomeActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000`

`adb -P 5037 -s {{uuid}} shell input keyevent 3`

`adb -s {{uuid}} shell monkey --pct-syskeys 0 -p com.viu.phone -c android.intent.category.LAUNCHER 1 `

Nokia72 real device with Appium 2 (driver: uiautomator2@2.1.0) approach--> app resumed with restarting:
`/Users/zhongping/Library/Android/sdk/platform-tools/adb -P 5037 -s {{uuid}} shell am start -W -n com.viu.phone/com.viu.phone.ui.activity.WelcomeActivity -S`

`/Users/zhongping/Library/Android/sdk/platform-tools/adb -P 5037 -s {{uuid}} shell input keyevent 3`

`/Users/zhongping/Library/Android/sdk/platform-tools/adb -s {{uuid}} shell monkey --pct-syskeys 0 -p com.viu.phone -c android.intent.category.LAUNCHER 1`

It looks like these args "-a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000" will change the way monkey works.

Do you have any idea about how to fix this issue? Thanks for the help.

**Comment by KazuCocoa** [comment] 2022-05-18 16:03
What Appium command did you send for the `am start` one?

Then, i would recommend you to use https://github.com/appium/appium-uiautomator2-driver#mobile-startactivity instead of activateApp. As https://github.com/appium/appium-uiautomator2-driver#applications-management , the activateApp uses monkey. The `monkey` seems to have some special behaviors. We'll use am start one for over API level 24 as https://github.com/appium/appium-android-driver/pull/744 in the future version, but for now, you can use the mobile command.

**Comment by SHI-ZP** [comment] 2022-05-19 06:18
> 

Hi @KazuCocoa, thank you so much for your time and reply.

The appium cmd for `am start` is AppiumDriver.background() according the appium2 server log:

`[HTTP] --> POST /session/9fb2a051-ea8c-44e3-a1d4-0cae1c442a5b/appium/app/background
[HTTP] {"seconds":6}`
`[debug] [AndroidUiautomator2Driver@a395 (9fb2a051)] Calling AppiumDriver.background() with args: [6,"9fb2a051-ea8c-44e3-a1d4-0cae1c442a5b"]`
`[debug] [ADB] Getting focused package and activity`
`[debug] [ADB] Running 'adb -P 5037 -s {{uuid}} shell dumpsys window displays'`
`[debug] [ADB] Pressing the HOME button`
`[debug] [ADB] Running 'adb -P 5037 -s {{uuid}} shell input keyevent 3'`

I send this cmd via the appium inspector 2021.9.2:
![image](https://user-images.githubusercontent.com/16377386/169222482-9d94273c-05bd-4421-95da-032b8d22ca18.png)

As for [https://github.com/appium/appium-android-driver/pull/744](https://github.com/appium/appium-android-driver/pull/744) I am wondering that does this change also applied to the Appium2 driver [uiautomator2-driver](https://github.com/appium/appium-uiautomator2-driver)?

**Comment by KazuCocoa** [comment] 2022-05-19 07:36
Yes, it will be in UIA2 driver after https://github.com/appium/appium-uiautomator2-driver/pull/526

**Comment by SHI-ZP** [comment] 2022-05-19 07:53
OK thanks.

**Comment by Jiyvn** [comment] 2022-05-19 09:37
@KazuCocoa 
I've tried https://github.com/appium/appium-uiautomator2-driver#mobile-startactivity .
```java
Map<String, Object> args = new HashMap<>();
args.put("intent", currentPackage+"/"+currentActivity);
((JavascriptExecutor)driver).executeScript("mobile: startActivity", args);
```
error hit:
` Security exception: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.viu.phone/.ui.activity.DemandActivity } from null (pid=17971, uid=2000) not exported from uid 11304`. 

And command `adb shell am start -W -n com.viu.phone/.ui.activity.DemandActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000` doesn't work. (according to https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md#javalangsecurityexception-permission-denial-starting-intent). checked with developer, activity is correct

**Comment by KazuCocoa** [comment] 2022-05-19 18:45
Was the activity launchable one?

**Comment by Jiyvn** [comment] 2022-05-20 02:14
@KazuCocoa 
I couldn't find `.ui.activity.DemandActivity` in `dumsys package <package_name>`. confirmed with developer, no launcher set for this page

**Comment by KazuCocoa** [comment] 2022-05-20 04:31
Then, the start activity method cannot start it.

Hm... `monkey` worked to resume the app...?
https://stackoverflow.com/questions/60207769/adb-command-to-resume-android-app-to-foreground-without-knowing-activity Then, the behavior was unexpected as `activateApp`, so it worked accidentally...

You could use https://github.com/appium/appium-uiautomator2-driver#mobile-shell to build `adb shell monkey -p your.app.package.name -c android.intent.category.LAUNCHER 1`

I need to address this behavior in https://github.com/appium/appium-uiautomator2-driver/pull/526 as well.

**Comment by KazuCocoa** [comment] 2022-05-20 04:40
No, you could build it with the start activity command with the below argument. Then, it works as resume.
`package: "com.viu.phone"`, `categories: "android.intent.category.LAUNCHER"`

**Comment by KazuCocoa** [comment] 2022-05-20 04:56
let me create another issue about this behavior since this main issue was wifi thing.

**Comment by KazuCocoa** [comment] 2022-05-20 05:03
https://github.com/appium/appium/issues/16967 is for the activateApp behavior thing.

**Comment by mykola-mokhnach** [comment] 2022-05-24 19:59
All patches were merged, thus closing

**Closed by mykola-mokhnach** 2022-05-24 19:59 UTC
Labels: Android, ThirdParty, NotABug
