### ISSUE TITLE
Hang during session start (2-15 minutes)

### ISSUE THREAD

**Issue by Hexxeh** [appium/appium#6386] opened 2016-04-08 16:37 UTC
## The problem

Occasionally during starting a new session, Appium will hang for several minutes with no additional log output.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.1
- Last Appium version that did not exhibit the issue (if applicable): n/a
- Desktop OS/version used to run Appium: OSX El Capitan
- Node.js version (unless using Appium.app|exe): 5.10.1
- Mobile platform/version under test: Android 6.0.1
- Real device or emulator/simulator: Nexus 5
- Appium CLI or Appium.app|exe: Appium CLI
## Link to Appium logs

https://gist.github.com/Hexxeh/994a5bb8bf3046fe19884c3e730b2119
## Code To Reproduce Issue [ Good To Have ]

Any sample case that launches an Appium session will trigger this.

**Comment by scottdixon** [comment] 2016-04-11 23:05
Do the logs kick back in after the hang? Can you pinpoint where the hang happens? Your logs look OK, the only delay I can see if the 20 second implicit wait (which I'm assuming is intentional).

**Comment by Hexxeh** [comment] 2016-04-11 23:23
Hang is immediately after the "Starting logcat capture" line during Appium startup. Execution does continue after the hang. These logs show a fairly short 2 minute hang, but we've seen hangs of up to 15 minutes.

**Comment by haricarana** [comment] 2016-06-22 09:49
Hi, I have the same issue with

* Appium version: Appium v1.5.3
* Desktop OS/version used to run Appium: Windows 10 Enterprise v1511
* Node.js version: v5.7.1
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Emulator (AVD) Nexus 5X
* Appium CLI or Appium.app|exe: CLI
  ADB version: 1.0.32

Log Part:
2016-06-21 11:05:28:145 - [debug] [Logcat] Starting logcat capture
2016-06-21 11:12:10:201 - [debug] [AndroidDriver] Pushing settings apk to device...

This case I have just a 7 minutes of hanging up, but often happens 15 minutes stucks.

If You could find any solution to your problems, it maybe help to me.

Thanks!

**Comment by SrinivasanTarget** [comment] 2017-07-20 07:54
There is a lot changed during an year now and i'm not able to reproduce this further so closing this.

**Closed by SrinivasanTarget** 2017-07-20 07:54 UTC
Labels: Android
