### ISSUE TITLE
Using chromedriver_autodownload - unexpected behavior

### ISSUE THREAD

**Issue by szprutamich** [appium/appium#13928] opened 2020-02-07 17:28 UTC
## Appium fails to start for consecutive runs.
We have a mapping file `chromedriverMapping.json`:
```
{
  "2.38.552522": "65.0.3325",
  "2.40.565383": "66.0.3359",
  "2.41.578700": "67.0.3360",
  "2.42.591071": "68.0.3440",
  "2.44.609551": "69.0.3497",
  "2.45.615279": "70",
  "2.46.628388": "71",
  "73.0.3683.68": "73",
  "74.0.3729.6": "74",
  "75.0.3770.140": "75",
  "76.0.3809.126": "76",
  "77.0.3865.40": "77",
  "78.0.3904.105": "78",
  "79.0.3945.36": "79",
  "80.0.3987.16": "80"
}
```
And binaries in separate directory:
```
chromedriver238  chromedriver241  chromedriver244  chromedriver246  chromedriver74  chromedriver76  chromedriver78  chromedriver80
chromedriver240  chromedriver242  chromedriver245  chromedriver73   chromedriver75  chromedriver77  chromedriver79
```
The first run goes fine, however appium downloads additional binaries - chromedriver_linux64_v79.0.3945.16, chromedriver_linux64_v79.0.3945.36 (they are not executable - that's one issue) and modifies the `chromedriverMapping.json` accordingly -
[modified_chromedriverMapping.txt](https://github.com/appium/appium/files/4172128/modified_chromedriverMapping.txt)

Every next run ends up with error - cannot create appium session.
```
[Chromedriver] Invalid Version: null
...
2020-02-07 14:48:39:026 - [debug] [W3C] Encountered internal error running command: Error: Invalid Version: null
2020-02-07 14:48:39:026 - [debug] [W3C]     at Object.errorAndThrow (/opt/testdroid/appium-1.16.0/node_modules/appium/node_modules/appium-support/lib/logging.js:74:35)
2020-02-07 14:48:39:026 - [debug] [W3C]     at Chromedriver.start (/opt/testdroid/appium-1.16.0/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:569:11)
2020-02-07 14:48:39:079 - [HTTP] <-- POST /wd/hub/session 500 18935 ms - 567
```

## Environment

* Appium version 1.16.0
* Desktop OS/version used to run Appium: Ubuntu 18.04

## Files
[appium_first.txt](https://github.com/appium/appium/files/4172147/appium_first.txt)
[appium_second.txt](https://github.com/appium/appium/files/4172149/appium_second.txt)

**Comment by imurchie** [comment] 2020-02-07 17:33
Duplicate of https://github.com/appium/appium/issues/13912?

**Comment by szprutamich** [comment] 2020-02-07 17:38
I'm not sure if that's duplicate

**Comment by mykola-mokhnach** [comment] 2020-02-07 18:46
Could you please try appium@beta?

**Comment by mykola-mokhnach** [comment] 2020-02-11 07:31
Closed because of no response

**Closed by mykola-mokhnach** 2020-02-11 07:31 UTC
Labels: Mobile Chrome, NeedsInfo
