### ISSUE TITLE
android google map view integration Slow or failed execution of tests

### ISSUE THREAD

**Issue by argeas** [appium/appium#8847] opened 2017-07-13 14:04 UTC
## The problem

The problem is that the execution of tests runs extremely slow when trying to locate/click elements and acc-id keys and sometimes even fails to locate them.

After testing various apps I believe I have narrowed it down and think that the cause is the google map integration that is used to display the map in the app and various other functionalities. ( e.g. hailing cab app )

## Environment

Appium version (or git revision) that exhibits the issue: 1.6.5
Desktop OS/version used to run Appium: Mac sierra, 
Node.js version: 7.4 
Mobile platform/version under test: Android 6,7
Real device or emulator/simulator: LG G2, Nexus 5X

## Details

The framework used utilises: Appium/Java/TestNG/Cucumber.
I created a simple project with just appium/ java and the problem still occurs. 

Another Hint is that when using the uiautomatorviewer to capture the xml screenshot of the current view I face the following issues: 
1 - takes long to capture screenshot
2 - fails if using the device screenshot ( uiautomator dump ) 
3 - only work with the Device screenshot compressed hierarchy button ( uiautomator dump - compressed)

It seems to me that the same reason that causes the uiautomatorviewer to take so long is responsible for the big delay between the appium actions since they both utilise the same method

## Link to Appium logs
The logs do not display anything wrong other than that there is a big delay between the search and result from appium commands.
Part of log here showing the delays:
https://gist.github.com/argeas/c2cfe30372c6f96dfeb0048e4973d6f3

**Comment by mykola-mokhnach** [comment] 2017-07-14 05:47
These all might be own uiautomation issues - Google does not support this framework anymore. Try to use UIAutomation2. as the automation backend

**Comment by argeas** [comment] 2017-07-14 11:48
I tried UIAutomation2 as well and same laggy performance... I see the 1.6.6 appium is gettgin ready for the espresso automator capability maybe that will solve it...

**Comment by mykola-mokhnach** [comment] 2017-07-14 11:52
@argeas the espresso driver it is currently being developed and you are welcome to take part in this process.

**Comment by jlipps** [comment] 2017-07-28 21:13
Closing since it seems that the issue is not within Appium itself. Keep an eye on the Espresso driver!

**Closed by jlipps** 2017-07-28 21:13 UTC
Labels: Android, ThirdpartyIssue

**Comment by argeas** [comment] 2017-08-29 17:46
FYI: Disabling all animations from the developer options increased the speed Dramatically. credits to https://github.com/Karamannn @Karamannn who found it
