### ISSUE TITLE
error: No profiles for 'com.facebook.WebDriverAgentRunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner')

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/appium#12674] opened 2019-05-22 05:53 UTC
## The problem
The app is continuously launching and closing when run the automation using 'Connect via network'. When I run the automation using lightning cable, it is working fine. As per the log, it seems WebDriverAgent is not built using the provisioning profile used for that device in 'Connect via network' but the same is working fine via lightning cable connection.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0-beta3
* Last Appium version that did not exhibit the issue (if applicable):1.10.0
* Desktop OS/version used to run Appium: Mac OS, v10.13.6
* Node.js version (unless using Appium.app|exe):v12.1.0
* Npm or Yarn package manager:v6.9.0
* Mobile platform/version under test: iOS/11.4.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/shivakrishnach31/89d7a9a89124e81c8aae0b3ed0217630

**Comment by mykola-mokhnach** [comment] 2019-05-22 11:00
Unfortunately Appium does not support iOS testing over WiFi. Closed as duplicate of https://github.com/appium/appium/issues/12089

**Closed by mykola-mokhnach** 2019-05-22 11:00 UTC

**Comment by shivakrishnach31** [comment] 2019-05-22 11:20
Hi @mykola-mokhnach - It was working in older versions but suddenly stopped working in the latest appium versions. What changes have been made to stop supporting this? Will it work if I use old versions like 1.9.1?

**Comment by KazuCocoa** [comment] 2019-05-22 13:39
Potentially, `appium@beta` fixes a provisioning issue. (Not sure that is related to this issue tho.)

> [Xcode] error: No profiles for 'com.facebook.WebDriverAgentRunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner')

What about changing the bundle id to match your provisioning profile?
In many cases, `com.facebook.WebDriverAgentRunner` should not be valid by provisioning profile which is valid for non-`com.facebook` organisation for real devices...
Can you install WDA via your Xcode over WiFi with the provisioning profile? If cannot, your provisioning profile and the bundleId is not matched. (not sure why it was valid for connected your device, in the case...)

---

Anyway, over wifi is not supported well, I guess as mykola addressed.

**Comment by shivakrishnach31** [comment] 2019-07-04 12:56
Hi, @KazuCocoa @mykola-mokhnach, How come it was working in the old version and suddenly stopped. That too it is not working only over WiFi. Everything is perfectly fine when the device is connected with lightning connector.

**Comment by KazuCocoa** [comment] 2019-07-04 13:04
Appium does not support running tests via WiFi officially, unfortunately

**Comment by shivakrishnach31** [comment] 2019-07-08 07:12
@KazuCocoa  - Thanks a lot for the clarification.
Excuse me if I keep asking the same question. 
Appium never supported it but I was able to run via network in older appium versions. May I know how it worked in older versions I mean running the automation via wifi. Was it handled by XCUITest or WebDriverAgent? If you can provide this info, so that, I can contact Apple or Facebook developers.
Actually I am in big trouble. Because, In my automation I have to connect lightning microphone to my iPhone/iPad and iPhone/iPad to Mac through 'Connect via Network' option in Xcode. Which actually makes wireless connection between iPhone/iPad and Mac.
In this way I was able to run automation for 3 projects.
Now I am not able to run. So now my 3 projects automation are useless. It is painful for me.
Something we(you people) can do to work automation via network with little investigation, which will be really helpful for the most of the mobile automation people.

Please at least tell me that can this be handled by WDA or XCUITest?

**Comment by KazuCocoa** [comment] 2019-07-08 07:37
from 1.13.0, I've introduced `wdaBaseUrl`. It allows Appium to communicate with WDA over the network after installing WDA via xcodebuild over the network. (Do not forget to enable an Xcode feature to connect to devices via network)

So, below is possible if your test targets exist in the test device.

1. Runs XCUITest with `wdaBaseUrl` and `wdaLocalPort`
    - Then, Appium calls xcodebuild to install WDA on the device over the network (xcodebuild feature)
    - After that, Appium makes sure the WDA is running on the device via `wdaBaseUrl` and `wdaLocalPort`
2. Runs WDA in the device initially. Appium starts as XCUITest with `webDriverAgentUrl` to connect to WDA running on the device.
    - Then, Appium tries to connect to the WDA via `webDriverAgentUrl`
        - Appium never call xcodebuild to install WDA

Because of ios-deploy's limitation, we cannot install `ipa` files over the network.

**Comment by shivakrishnach31** [comment] 2019-07-09 08:43
Hi @KazuCocoa - Thank you :)
I have installed WDA through xcodebuild over the network and I have installed my target app in iPhone. This case also Appium not able to interact with WDA. App keeps launching and closing.

As you said that you have introduced something new in v1.13.0 which broke my automation. So I have decided to use the old version(1.9.0). I was using this version of Appium without any issue before i installed .13.0

But today when I try to install 1.9.0 in my Mac Mojave, it installed 1.10.0 instead 1.9.0. That's ok for me.
While building the WDA I am seeing `Messaging unqualified id` error. 
After going through the some of the appium's Github issues, I have made some changes in the WDA project Xconfig file and that error disappeared. But after that, I am not able to use the Inspector.

Can you please help me how can I use the old version of appium in my iMac Mojave v10.14.5 like before? or fix those issues? 
Please help me @KazuCocoa . This is very important to me.

**Comment by KazuCocoa** [comment] 2019-07-09 09:30
> I have installed WDA through xcodebuild over the network and I have installed my target app in iPhone. This case also Appium not able to interact with WDA. App keeps launching and closing.

I could not say anything without logs (and this case, please create a new issue)


Did you downgrade Xcode version? Xcode 10.2 cannot build a lower version.
I have no idea except for the Xcode version issue.

**Comment by shivakrishnach31** [comment] 2019-07-10 10:09
> I could not say anything without logs (and this case, please create a new issue)
If you read this bug issue description it says what I said in my previous comment about continuous launching. Do we still need a new issue for the same issue.

**Comment by KazuCocoa** [comment] 2019-07-10 11:57
Yes, but I meant if _I have installed WDA through xcodebuild over the network and I have installed my target app in iPhone. This case also Appium not able to interact with WDA. App keeps launching and closing._ was because of `wdaBaseUrl` capability case.  But you did not address the `wdaBaseUrl`? Sorry, my misunderstanding.

let me summarise this issue...

1. maybe code signing issue (the original issue was this since this was this issue title)
    > [Xcode] error: No profiles for 'com.facebook.WebDriverAgentRunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner')
2. WiFi
    - We do not fully support the feature officially. If it worked before, it was unexpected behaviour for us.
        - this is the answer
    - But `wdaBaseUrl` (added recently) and `webDriverAgentUrl` can do it partially.
       - `wdaBaseUrl` worked on my env, btw. => https://kazucocoa.wordpress.com/2019/07/10/appiumios-handle-ios-apps-via-appium-over-the-network/ . It should be another issue if this capability has an issue
3. You could not install older Appium version
    - Perhaps, Xcode version issue since newer Xcode cannot build older

**Comment by Thilakshan17** [comment] 2022-10-29 13:16
in my case it works for a few cycles after that it does not work at that time I removed Xcode and I installed that again

**Comment by Thilakshan17** [comment] 2022-11-01 04:09
if all your steps are successful and you are still getting an error message like this you have to restart your computer after cleaning the derived data
