### ISSUE TITLE
Failure to detect present udid of iPhone when using Appium Inspector

### ISSUE THREAD

**Issue by danielvechiu** [appium/appium#19985] opened 2024-04-09 14:16 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

appium-xcuitest-driver does not detect the real device due to the check being skipped since it expects a webDriverAgentUrl capability which is not at all intuitive to use/include in Appium Inspector.

### Expected Behavior

Connection successfully established between appium-xcuitest-driver and iPhone.

### Minimal Reproducible Example

In my case, the default code is the one in the picture and I fixed the issue by removing the negation in front of `shouldCheckAvailableRealDevices`, since the real phone is detected but `isRealDeviceUdid` would never become `True`, therefore it goes into the second if and throws the Unknown device UDID error, making it impossible to connect from Appium Inspector.

![Screenshot 2024-04-09 at 16 11 20](https://github.com/appium/appium/assets/62881450/54009fbf-d90a-4719-883b-e7b9f8911f88)

### Environment

- Operating system: Sonoma MacOS
- Appium server version (output of `appium --version`):  2.5.1
- Appium driver(s) and their version(s): xcuitest@7.11.0
- Appium plugin(s) and their version(s): -
- Node.js version (output of `node --version`): 21.7.1
- `npm` version (output of `npm --version`): 10.5.1
- Last component(s) version which did _not_ exhibit the problem: -
- Platform and version under test: iOS and 16.3.1
- Real device or emulator/simulator: Real device

**Comment by mykola-mokhnach** [comment] 2024-04-09 15:28
Duplicate of https://github.com/appium/appium/issues/19980

**Closed by mykola-mokhnach** 2024-04-09 15:28 UTC
Labels: Bug, Needs Triage
