### ISSUE TITLE
Testing failed: 	Cannot link directly with dylib/framework while building WDA 

### ISSUE THREAD

**Issue by siddhantraut** [appium/appium#17497] opened 2022-09-16 02:28 UTC
## The problem

Getting error after full manual configuration while building WebDriverAgent
(  xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test )

Test session results, code coverage, and logs:
	/Users/siddhant/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs/Test/Test-WebDriverAgentRunner-2022.09.15_21-45-16--0400.xcresult

Testing failed:
	Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64
	Testing cancelled because the build failed.

** TEST FAILED **

The following build commands failed:
	Ld /Users/siddhant/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework/WebDriverAgentLib normal (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
(1 failure)
## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Last Appium version that did not exhibit the issue (if applicable): 1.21 | XCODE - 13 | MAC OS 12.3
* Desktop OS/version used to run Appium:12.5.1 / XCODE -14
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iPhone 12 PRO Max - OS version 16
* Real device or emulator/simulator:iPhone 12 PRO MAX
* Appium CLI or Appium.app|exe: CLI 

## Details

Getting error after full manual configuration 
    xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test

## Link to Appium logs

NA

## Code To Reproduce Issue [ Good To Have ]

NA

ticket created on apple developer forum as well - ref - https://developer.apple.com/forums/thread/712039?login=true&page=1#728216022

**Comment by KazuCocoa** [comment] 2022-09-16 02:35
Duplicate of https://github.com/appium/appium/issues/17174
Please use latest xcuitest driver, which has the fix, with appium 2.

**Closed by KazuCocoa** 2022-09-16 02:35 UTC

**Comment by vsadana** [comment] 2022-09-16 05:42
I am facing the same in the latest appium version as well i.e v1.22.3.  Any other alternative way to fix this?
Xcode: 14
OS: 16.0

Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64

**Comment by siddhantraut** [comment] 2022-09-17 03:05
thanks, @KazuCocoa  finally **iOS 16 with appium@next | MAC. 12.5 | XCODE 14**  EXECUTED SUCCESSFULLY :

Folks- if needed below env to work everything fine

Steps done - 
1. installed -
* Node.js v16.17.0 t 
* npm v8.15.0 
 2. npm install -g appium@next. - v2.0.0-beta.44
 3. appium plugin install execute-drivers
 4. appium start @ appium -pa /wd/hub --use-plugins execute-driver 
 5. driver installed - appium driver install xcuitest | appium driver install uiautomator2

**Comment by Digi27** [comment] 2022-09-19 12:29
@siddhantraut and @KazuCocoa I tried to perform the above steps but i am unable to get it done
Can you help me to perform it. I am completely stuck in it

**Comment by Digi27** [comment] 2022-09-19 13:11
@KazuCocoa and @siddhantraut i am running on real iOS device where i am using manual configuration build the webdriverAgent once and on that webdriveragent runner i am running my entire suite
Language i am using java

**Comment by siddhantraut** [comment] 2022-09-19 13:15
> @siddhantraut and @KazuCocoa I tried to perform the above steps but i am unable to get it done Can you help me to perform it. I am completely stuck in it

@Digi27  Could you please make sure WDA in xcode from correct - path -  **/Users/username/.appium/node_modules/appium-xcuitest-driver/node_modules/**

**Comment by Digi27** [comment] 2022-09-19 13:20
> 2\. npm install -g appium@next

@siddhantraut after this command npm install -g appium@next
i should do the above path for WDA right?

**Comment by Edwick-Raj** [comment] 2022-09-21 05:18
hy @KazuCocoa @siddhantraut @Digi27 
After Executing this command `npm install -g appium@next` , Am getting error in xcode...shows like some related packages are missing.
<img width="266" alt="Screenshot 2022-09-21 at 10 41 35 AM" src="https://user-images.githubusercontent.com/114048361/191419930-4671560e-a77d-456e-92b7-05409b83e241.png">
Could u please help?...Currently am using 
appium-1.22.3
tvos-15.6
xcode-14.
npm - 8.19.2
nodejs - 18.9.0

**Comment by KazuCocoa** [comment] 2022-09-21 06:35
I haven't seen the error, but I wonder if this was because you installed appium in root permission space and Xcode failed to open them.

**Comment by shlomobraverman** [comment] 2022-09-21 13:45
What worked for me
> installed -
> * Node.js v16.13.1
> * npm 8.9.0
> 
> run this in terminal
> 1. npm install -g appium@2.0.0-beta.44
> 2. appium plugin install execute-driver
> 3. appium -pa /wd/hub --use-plugins execute-driver
> 4. appium driver install xcuitest 
> 5. appium driver install uiautomator2

**Comment by Immanuel-Codoid** [comment] 2022-10-08 09:58
Hi @siddhantraut , I'm trying to understand your solution steps
Installed:
- Xcode - 14.0
- node v16.17.1
- npm 8.15.0
- macOS - 12.6
- iOS - 16.0.2

Steps followed:
1. npm install -g appium@2.0.0-beta.44
2. appium plugin install execute-driver
3. appium -pa /wd/hub --use-plugins execute-driver
4. appium driver install xcuitest
5. appium driver install uiautomator2

I used wda xcode proj file from this location /Users/username/.appium/node_modules/appium-xcuitest-driver/node_modules/ to build wda into connected iPhone

Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64

Facing this issue still

Help is much appreciated

**Comment by KazuCocoa** [comment] 2022-10-11 05:32
What about cleaning your xcode cache stuff such as `~/Library/Developer/Xcode/DerivedData/`? Then, please double check the installed xcuitest is latest version.

**Comment by zaphodikus** [comment] 2022-10-11 16:49
Is there a way to install the xcuitest older driver instead, for people who don't have the time to upgrade all their tests to Appium 2.0? I'm on xcode 14.0 . I rolled forward, on a single machine but it totally breaks too much of our test code to fix in a hurry, so I'd like to roll back correctly, but installing appium (1) seems to install or use the newer driver still on that machine even after uninstalling appium.

**Comment by siddhantraut** [comment] 2022-10-11 17:08
@Immanuel-Codoid could you try reinstallation(remove first) XCODE once?

**Comment by KazuCocoa** [comment] 2022-10-11 19:45
> Is there a way to install the xcuitest older driver instead, for people who don't have the time to upgrade all their tests to Appium 2.0? I'm on xcode 14.0 . I rolled forward, on a single machine but it totally breaks too much of our test code to fix in a hurry, so I'd like to roll back correctly, but installing appium (1) seems to install or use the newer driver still on that machine even after uninstalling appium.

JavaScript code in appium-xcuitest-driver/appium-webdriveragent has breaking changes internally, but the below may work:

Replace `appium/node_modules/appium-webdriveragent` (or maybe `appium/node_modules/appium-xcuitest-driver/appium-webdriveragent`) with https://github.com/appium/WebDriverAgent except for `build` and `node_modules` directories in `appium-webdriveragent`. Appium/WDA itself does not have breaking changes (but https://github.com/appium/WebDriverAgent  repo has JavaScript code), so keeping `appium-webdriveragent/build` and `appium-webdriveragent/node_modules` but replace other Xcode project stuff can do.

Let me take a look (hopefully) tonight if we could pick necessary changes up for xcode 14 for appium 1 to include only it

**Comment by zaphodikus** [comment] 2022-10-12 16:03
As a short term workaround I managed to install both appium via brew and override the node version 2 installation, then manually 
`\cd /opt/homebrew/lib/node_modules/appium-webdriveragent ; xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=00008020-001458161E12002E' test`
to start the driver and connect it in test mode to the target phone, then start appium V1 normally in my test (from brew) which promptly sees that the driver is already running and does not try to start it and then things work - at least very temporary for my developers who only installed appium this week.

Ah I see you just posted some workaround hints, that tally with my very limited java experience above showing that this can be transplanted. Will try do that tomorrow. Thanks for all the effort, will verify tomorrow and feedback.

**Comment by marcelozenjob** [comment] 2022-11-16 15:15
A quick workaround for this still using Appium 1.22.3 is to go to the `./node_modules/appium` folder and update the 
appium-xcuitest-driver to the latest version
e.g.
```
cd ./node_modules/appium
npm install appium-xcuitest-driver@latest
```

**Comment by jdmesalosada** [comment] 2022-11-30 23:24
Getting the same error with:
Appium desktop version: 1.22.3
Xcode:14.1
iOS:16.1.2
MacOs:12.6.1

**Steps to fix the issue:**
npm install -g appium@next

This installed the appium version: 2.0.0-beta.46

Then install the driver for xcuitest:
appium driver install xcuitest

Go to the folder: 
`/Users/${your_user}/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent`

Open WebDriverAgent.xcodeproj with xCode and sign it.


Then run the command: 
`xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id='{device_id}' test -allowProvisioningUpdates`

**Comment by jlipps** [comment] 2022-12-01 00:38
@mykola-mokhnach what would you think about an xcuitest driver script like this:

```
appium driver run xcuitest open-wda-proj
```

And all it does is call `open /correct/path/to/WebDriverAgent.xcodeproj`; could make it easy for people to get to the point of signing it?

**Comment by mykola-mokhnach** [comment] 2022-12-01 06:42
> @mykola-mokhnach what would you think about an xcuitest driver script like this:
> 
> ```
> appium driver run xcuitest open-wda-proj
> ```
> 
> And all it does is call `open /correct/path/to/WebDriverAgent.xcodeproj`; could make it easy for people to get to the point of signing it?

yes, I like this idea

**Comment by SkPratihar1** [comment] 2023-09-05 10:02
The following build commands failed:
        Ld /Users/it062305/Library/Developer/Xcode/DerivedData/WebDriverAgent-femkzeamkxbpckfotevcllhvvmda/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/WebDriverAgentLib normal (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
(1 failure)
2023-09-05 15:28:10.451 xcodebuild[39632:370001] [MT] IDETestOperationsObserverDebug: 0.012 elapsed -- Testing started completed.
2023-09-05 15:28:10.451 xcodebuild[39632:370001] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2023-09-05 15:28:10.451 xcodebuild[39632:370001] [MT] IDETestOperationsObserverDebug: 0.012 sec, +0.012 sec -- end
Test session results, code coverage, and logs:
        /Users/it062305/Library/Developer/Xcode/DerivedData/WebDriverAgent-femkzeamkxbpckfotevcllhvvmda/Logs/Test/Test-WebDriverAgentRunner-2023.09.05_15-28-04-+0530.xcresult
Testing failed:
        Cannot link directly with dylib/framework, your binary is not an allowed client of /Users/it062305/dev/software/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture x86_64
        Linker command failed with exit code 1 (use -v to see invocation)
        Test target WebDriverAgentRunner encountered an error (The bundle identifier for WebDriverAgentRunner-Runner.app couldn’t be read. The application may be damaged or incomplete: “/Users/it062305/Library/Developer/Xcode/DerivedData/WebDriverAgent-femkzeamkxbpckfotevcllhvvmda/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app”.)
** TEST EXECUTE FAILED **
