### ISSUE TITLE
execute_script在执行的时候抛出 Cannot execute the 'logcat' shell command.

### ISSUE THREAD

**Issue by tianyao1111** [appium/appium#14817] opened 2020-10-19 07:01 UTC
## The problem

我在每个app自动化用例执行之后，想获取app的logcat日志，所以我写了一个装饰器，如下：

```
def logcatlogger(func):
	'''用例装饰器：检查app的后台日志中的错误的日志，并记录下来'''
	def wrapper(self):
		#casename
		case_name=self.name
		#创建日志文件名
		filename=os.path.join(r'test_logcat',case_name+'_'+time.strftime("%Y-%m-%d_%H-%M-%S")+r'.log')
		self.logcat=r'../'+filename
		filename=os.path.join(root_url,filename)
		#查出e通包名对应的PID
		opts = {
			'command':'ps',
			'args':['|','grep','com.picc.nmms'],
			'includeStderr': True,
		}
		result = self.driver.execute_script('mobile:shell',opts)
		#装进程号的列表
		poc=[]
		if result['stderr']!="":
			#如果有错误，记录错误在日志文件里
			with open(filename,'w') as f:
				f.write(r'ERROR1:'+str(result['stderr']))
		elif result['stdout']=="":
			#如果没打开app，记录到日志文件里 
			with open(filename,'w') as f:
				f.write(r"没开启app")
		else:
			#提取并收集查询回来的PID
			p_list=result['stdout'].split("\r\n")[:-1]
			for i in p_list:
				poc.append(re.split(r"\s+",str(i))[1])

			opts = {
				'command':'logcat',
				'args':['-v','time','*:E','-d','|','grep']+poc,
				'includeStderr': True,
				}
				
		#执行用例
		try:
			#执行用例
			func(self)
		except:
			#用例抛错后执行
			if len(poc)!=0:
				#执行adb logcat -v time *:E，筛选e通对应的logcat错误日志
				result = self.driver.execute_script('mobile:shell',opts)
				#如果有错误，记录错误在日志文件里
				if result['stderr']!="":
					with open(filename,'w') as f:
						f.write(r'ERROR2:'+str(result['stderr']))
				else:
					with open(filename,'w') as f:
						f.write(result['stdout'])

			raise
		else:
			#用例通过后执行
			if len(poc)!=0:
				#执行adb logcat -v time *:E，筛选e通对应的logcat错误日志
				result = self.driver.execute_script('mobile:shell',opts)
				#如果有错误，记录错误在日志文件里
				if result['stderr']!="":
					with open(filename,'w') as f:
						f.write(r'ERROR2:'+str(result['stderr']))
				else:
					with open(filename,'w') as f:
						f.write(result['stdout'])

	return wrapper
```

但是，这个装饰器有时运行很好，有时**result = self.driver.execute_script('mobile:shell',opts)**这一句抛出：

[AndroidDriver] Cannot execute the 'logcat' shell command. Original error: Command 'C:\\qianfeng\\learning\\software\\software\\adt-bundle-windows-x86_64\\sdk\\platform-tools\\adb.exe -P 5037 -s 127.0.0.1\:21533 shell logcat -v time \*\:E -d \| grep 8931' exited with code 1. StdOut: . StdErr:

这个错我上网上没搜出来结果，所以来这里问一下

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):1.18.0
* Desktop OS/version used to run Appium:win10
* Node.js version (unless using Appium.app|exe):v10.16.3
* Npm or Yarn package manager:6.9.0
* Mobile platform/version under test:android7.1
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:

## Details

我要做一个收集特定app的logcat日志的装饰器
我的用例：
```
#coding=utf-8
import unittest
#将etong根目录加入环境变量
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))

from public.login import login
from public.get_driver import get_driver
from public.common2 import logcatlogger,when_error_screenshot
from public.excel_data import get_excel_data

from test_page.indexPage import indexPage
from test_page.TBCarRiskPage import TBCarRiskPage
from test_page.TBCarRiskInfoPage import TBCarRiskInfoPage
from test_page.TBCarRiskQuotePlanPage import TBCarRiskQuotePlanPage
from test_page.TBCarRiskComfirePage import TBCarRiskComfirePage

from public.common import get_elements,is_newCar
from public.common1 import car_code,car_frame_code,car_engine_code


class ET_TB_CX_case_01(unittest.TestCase):
	'''投保-车险-带牌新车-单商业全流程线上支付出单'''

	
	def setUp(self):
		#获取本文件名
		self.name=os.path.split(__file__)[-1].split(".")[0]
		#获取数据文件路径
		path1=os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
		file=os.path.join(path1,r'test_data')
		file=os.path.join(file,r'TBCXData.xlsx')
		#获取数据
		self.data=get_excel_data(file,self.name)
		#生成driver
		self.driver=get_driver()

	@when_error_screenshot
	@logcatlogger
	def test_case_01(self):
		'''case 01'''
		login(self.driver,self.data['user'],self.data['comp'],self.data['pwd'])

		#点击车险出单
		indexPage().click_menu(self.driver,self.data['risk_type'])

		#进入车险传统渠道出单页
		#判断是否为新车
		carNo=car_code()
		while not is_newCar(self.driver,carNo):
			carNo=car_code()
		#获取报价
		TBCarRiskPage().get_quote(self.driver,self.data["quoter"],carNo)

		#进入车辆信息页面
		CRIP=TBCarRiskInfoPage()

		#车辆信息
		car_info={key: value for key, value in self.data.items() if key in ["car_owner","car_model","car_type","car_usenature","carNo_type","car_color"]}
		car_info["carFrameNo"]=car_frame_code()
		car_info["engineNo"]=car_engine_code()
		car_info["carNo"]=carNo

		#被保险人信息
		BBXR_info=BBXR_info={key: value for key, value in self.data.items() if key in ["BBXR_name","BBXR_ID","BBXR_type","BBXR_gender","BBXR_birthday"]}
		#车辆信息页面录入车架号、发动机号、初登日期、车主姓名、车型、车辆种类、使用性质、品牌种类、号牌颜色（选择白牌）、点击下一步。
		CRIP.input_car_info(self.driver,car_info,BBXR_info)

		#进入报价方案页面
		CRQPP=TBCarRiskQuotePlanPage()

		#选择商业险险种（车损险、盗抢险、三者险），点击计算保费后下一步。
		CRQPP.operate_quote_plan(self.driver,self.data['quote_plan'])

		#进入投保确认页面
		RCP=TBCarRiskComfirePage()
		#添加关系人,点击转投保
		RCP.comfirm_risk(self.driver,self.data["BBXR_name"],self.data["BBXR_ID"])
		#验证转投保字样变成提交核保
		RCP.test_hb("提交核保")
		#提交核保
		RCP.click_hb(self.driver)

	def tearDown(self):
		#退出
		self.driver.quit()

if __name__ == '__main__':
	from public.MyTestRunner import TextTestRunner1
	unittest.main(testRunner=TextTestRunner1)
```

我的logcat装饰器：
```
#coding=utf-8
'''常用来修饰用例的装饰器'''
import subprocess
import re
import os
import time
from config import root_url
def logcatlogger(func):
	'''用例装饰器：检查app的后台日志中的错误的日志，并记录下来'''
	def wrapper(self):
		#casename
		case_name=self.name
		#创建日志文件名
		filename=os.path.join(r'test_logcat',case_name+'_'+time.strftime("%Y-%m-%d_%H-%M-%S")+r'.log')
		self.logcat=r'../'+filename
		filename=os.path.join(root_url,filename)
		#查出e通包名对应的PID
		opts = {
			'command':'ps',
			'args':['|','grep','com.picc.nmms'],
			'includeStderr': True,
		}
		result = self.driver.execute_script('mobile:shell',opts)
		#装进程号的列表
		poc=[]
		if result['stderr']!="":
			#如果有错误，记录错误在日志文件里
			with open(filename,'w') as f:
				f.write(r'ERROR1:'+str(result['stderr']))
		elif result['stdout']=="":
			#如果没打开app，记录到日志文件里 
			with open(filename,'w') as f:
				f.write(r"没开启app")
		else:
			#提取并收集查询回来的PID
			p_list=result['stdout'].split("\r\n")[:-1]
			for i in p_list:
				poc.append(re.split(r"\s+",str(i))[1])

			opts = {
				'command':'logcat',
				'args':['-v','time','*:E','-d','|','grep']+poc,
				'includeStderr': True,
				}
				
		#执行用例
		try:
			#执行用例
			func(self)
		except:
			#用例抛错后执行
			if len(poc)!=0:
				#执行adb logcat -v time *:E，筛选e通对应的logcat错误日志
				result = self.driver.execute_script('mobile:shell',opts)
				#如果有错误，记录错误在日志文件里
				if result['stderr']!="":
					with open(filename,'w') as f:
						f.write(r'ERROR2:'+str(result['stderr']))
				else:
					with open(filename,'w') as f:
						f.write(result['stdout'])

			raise
		else:
			#用例通过后执行
			if len(poc)!=0:
				#执行adb logcat -v time *:E，筛选e通对应的logcat错误日志
				result = self.driver.execute_script('mobile:shell',opts)
				#如果有错误，记录错误在日志文件里
				if result['stderr']!="":
					with open(filename,'w') as f:
						f.write(r'ERROR2:'+str(result['stderr']))
				else:
					with open(filename,'w') as f:
						f.write(result['stdout'])

		################################################
		#关闭logcat
		# obj.send_signal(signal)  # 向子进程发送signal信号
		# obj.terminate()  # 终止(stop)子进程
		# obj.kill()  # 杀死子进程。在Windows上，kill()和terminate()作用相同
		# 前面的的关闭只能关闭单个进程，要关闭进程组和进程树，需要用下面的方法
		# os.killpg(os.getpgid(obj.pid), 9)#linux下'
		# os.system("taskkill /t /f /pid %s >nul 2>&1" % p.pid)#windows下
		################################################
	return wrapper

def when_error_screenshot(func):
	'''当用例发生错误后截图'''
	def wrapper(self):
		try:
			#执行用例
			func(self)
		except:
			a=os.path.join(r'test_picture',self.name+' '+time.strftime("%Y-%m-%d %H-%M-%S")+r'.png')
			filename=os.path.join(root_url,a)
			#给img连接附上路径
			self.img=r"../"+a
			self.driver.save_screenshot(filename)
			raise

	return wrapper
```

GitHub 这个代码块功能真是一言难尽
## Link to Appium logs

appium：
```
C:\Users\14221\Desktop\人保新架构>appium --nodeconfig C:/Users/14221/Desktop/人保新架构/2.json --session-override  -p 4725 -bp 4726 -U  127.0.0.1:21533 --log-level error --relaxed-security
[AndroidDriver] Cannot execute the 'logcat' shell command. Original error: Command 'C:\\qianfeng\\learning\\software\\software\\adt-bundle-windows-x86_64\\sdk\\platform-tools\\adb.exe -P 5037 -s 127.0.0.1\:21533 shell logcat -v time \*\:E -d \| grep 8931' exited with code 1. StdOut: . StdErr:
```

selenium GRID：
```
13:24:03.581 ERROR - cannot forward the request 0.0.0.0:4725 failed to respond
org.apache.http.NoHttpResponseException: 0.0.0.0:4725 failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at org.openqa.grid.internal.TestSession.sendRequestToNode(TestSession.java:462)
        at org.openqa.grid.internal.TestSession.forward(TestSession.java:243)
        at org.openqa.grid.web.servlet.handler.RequestHandler.forwardRequest(RequestHandler.java:98)
        at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:132)
        at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:84)
        at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.lang.Thread.run(Thread.java:748)
```

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2020-10-19 07:10
![Fry](https://memegenerator.net/img/instances/63580868/i-hear-you-but-still-dont-understand.jpg)

**Comment by tianyao1111** [comment] 2020-10-19 07:30
简单的说：
我用appium的execute_script，执行shell（adb shell logcat -v time *:E -d | grep 8931）报错，appium给我的提示就一行：
[AndroidDriver] Cannot execute the 'logcat' shell command. Original error: Command 'C:\qianfeng\learning\software\software\adt-bundle-windows-x86_64\sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1:21533 shell logcat -v time *:E -d | grep 8931' exited with code 1. StdOut: . StdErr:

**Comment by mykola-mokhnach** [comment] 2020-10-20 07:29
Looking at the error output I could say it is a duplicate of https://github.com/appium/appium/issues/9961

Use `logcatFormat`/`logcatFilterSpecs` capabilities in order to customise the logcat output.

**Closed by mykola-mokhnach** 2020-10-20 07:29 UTC
Labels: NeedsInfo

**Comment by tianyao1111** [comment] 2020-10-21 09:42
> 查看错误输出，我可以说它是[＃9961](https://github.com/appium/appium/issues/9961)的重复项[](https://github.com/appium/appium/issues/9961)
> 
> 使用`logcatFormat`/`logcatFilterSpecs`功能以定制logcat输出。

可是我不会用`logcatFormat`/`logcatFilterSpecs`的功能，能不能给个例子？如果有python的例子就更好了，我不会java。非常感谢！！！

**Comment by tianyao1111** [comment] 2020-10-22 08:37
> 查看错误输出，我可以说它是[＃9961](https://github.com/appium/appium/issues/9961)的重复项[](https://github.com/appium/appium/issues/9961)
> 
> 使用`logcatFormat`/`logcatFilterSpecs`功能以定制logcat输出。


> 查看错误输出，我可以说它是[＃9961](https://github.com/appium/appium/issues/9961)的重复项[](https://github.com/appium/appium/issues/9961)
> 
> 使用`logcatFormat`/`logcatFilterSpecs`功能以定制logcat输出。

我跟＃9961应该不是重复项，我的命令里logcat命令加了一个参数 -d  Dump the log and then exit (don't block),所以我的logcat是马上返回的。但是我就是不知道它为什么错

**Comment by tianyao1111** [comment] 2020-11-01 15:50
> Looking at the error output I could say it is a duplicate of #9961
> 
> Use `logcatFormat`/`logcatFilterSpecs` capabilities in order to customise the logcat output.
最后，事实证明根据您的建议，我成功的获取了每个app测试用例运行时的logcat错误日志，3Q
