### ISSUE TITLE
Appium 1.13.0 not working with real device (iOS 12.2 )

### ISSUE THREAD

**Issue by SebastianSolidwork** [appium/appium#12642] opened 2019-05-15 09:02 UTC
## The problem

With Appium 1.13. i can't launch the WebDriverAgent launched on a real iPad Mini 4 with iOS 12.2.
Doesn't matter if Safari-Browser or App.
```
XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[XCUITest] xcodebuild error message:
[XCUITest] 
[XCUITest] 2019-05-15 10:46:15.286 xcodebuild[13361:314635] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos12.2-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/Admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/WebDriverAgentRunner_iphoneos12.2-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7f83d111f5e0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[XCUITest] 2019-05-15 10:46:15.286 xcodebuild[13361:314635] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos12.2-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/Admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/WebDriverAgentRunner_iphoneos12.2-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7f83d1676030 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[XCUITest] ** TEST BUILD FAILED **
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13
* Last Appium version that did not exhibit the issue (if applicable): 1.12.1 Desktop (did not tested cli)
* Desktop OS/version used to run Appium: macOS 10.14.4
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: both

## Details

If necessary, describe the problem you have been experiencing in more detail.

```
[Appium] Capabilities:
[Appium]   platformName: iOS
[Appium]   platformVersion: 12.2
[Appium]   platform: Mac
[Appium]   deviceName: ISA*
[Appium]   browserName: Safari
[Appium]   udid: auto
[Appium]   automationName: XCUITest
[Appium]   xcodeOrgId: DELETEBYME
[Appium]   xcodeSigningId: iPhone Developer
[Appium]   updatedWDABundleId: pd.appium.PDWebDriverAgentRunner
[Appium]   startIWDP: false
[Appium]   useNewWDA: true
[Appium]   newCommandTimeout: 120000
```

## Link to Appium logs

[appium log](https://gist.github.com/SebastianSolidwork/0b30823279193063a3acb7093c53f8c7)

## My guess

`[XCUITest] 		provisioningProfiles:      (null)`
Maybe the profile is dropped for what ever reason?

**Comment by mykola-mokhnach** [comment] 2019-05-15 09:17
Duplicate of https://github.com/appium/appium/issues/12581

Kindly use search first before posting a new issue.

**Closed by mykola-mokhnach** 2019-05-15 09:17 UTC

**Comment by SebastianSolidwork** [comment] 2019-05-15 11:53
@mykola-mokhnach Thanks for the hint. Looks like my investigation wasn't good enough :-(
I'm don't understand what changed from 1.12.1 to 1.13 so that my provisioning profile isn't working any longer.
And i'm troubling with the full configuration of the provisioning. Basic configuration works for 1.12.1.
The tests of the wda-project don't finish and i still got the same error at the appium server.

**Comment by mykola-mokhnach** [comment] 2019-05-15 12:17
This is always a tricky topic - it works for some people and for some other it does not. Try to apply https://github.com/appium/WebDriverAgent/pull/166 to your local source and see if it helps.

**Comment by SebastianSolidwork** [comment] 2019-05-17 10:52
@mykola-mokhnach I could resolve my problem.
I had to change the signing in the project which is included in the installed Appium Desktop.
/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
The "Full manual configuration" from http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/
"Basic (manual) configuration" worked with 1.12 but not any longer with 1.13. Is this a bug?

**Comment by mykola-mokhnach** [comment] 2019-05-17 10:57
@KazuCocoa Any thoughts ^ ?

**Comment by KazuCocoa** [comment] 2019-05-17 11:09
Was that after applying https://github.com/appium/WebDriverAgent/pull/166 on your local?

Changing the configuration by manual also fixes the same issue without https://github.com/appium/WebDriverAgent/pull/166.
If it happens after applying https://github.com/appium/WebDriverAgent/pull/166, I should take a look more...

**Comment by SebastianSolidwork** [comment] 2019-05-17 12:53
@KazuCocoa "Full manual configuration", the full WDA project, worked without applying your changes. This is what i'm using since 1.13.
The basic manual configuration, a dummy project, isn't working any longer. No matter what i change.

**Comment by olivierschmid** [comment] 2019-06-06 11:35
> al configu

Same here. Automatic signing is broken with 1.13.0. But it seems to work again with 1.14.0-beta.1

**Comment by zcmgyu** [comment] 2019-06-28 17:34
@SebastianSolidwork I think that error because of no provisioning profile.
And it's already fixed in this PR

https://github.com/appium/appium-xcuitest-driver/pull/961

**Comment by SebastianSolidwork** [comment] 2019-07-09 12:08
@KazuCocoa @zcmgyu 1.14 works out of the box. I didn't had to reapply the full manual configuration.
Thanks for that fix!
