### ISSUE TITLE
iOS:Appium inspector unable to recognize/locate keyWindow elements

### ISSUE THREAD

**Issue by SaqibSuhail** [appium/appium#14496] opened 2020-06-29 12:25 UTC
## The problem

Hello,

I have an issue where Appium inspector is not able to locate the elements on a Native iOS app.

Scenario:
While a pop-up appears on background screen, the Appium inspector is not able to recognize or locate the pop-up instead it recognizes the background screen.

The pop-up has been written using the keyWindow which is leading the Appium inspector to be blind on iOS 13.
The above scenario works on iOS version below 13.

Please help me out on this. Any suggestion/solutions are appreciated.
## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Desktop OS/version used to run Appium: macOS Catalina
* Device - Real device(iOS 13)

## Link to Appium Support

https://discuss.appium.io/t/appium-inspector-unable-to-recognize-locate-keywindow-elements/31192

**Comment by mykola-mokhnach** [comment] 2020-06-29 13:06
Please provide the server log, page source output and a screenshot if possible

**Comment by SaqibSuhail** [comment] 2020-06-30 08:41
Here's the link to the containing screenshot and page source.
We are not able to select or locate the red square which is displayed by Appium inspector.


<img width="1192" alt="iOS 13 3" src="https://user-images.githubusercontent.com/52916226/86104098-39e2f200-badb-11ea-858f-9b804646d964.png">

**Comment by mykola-mokhnach** [comment] 2020-06-30 08:55
I don't have the page source, but it looks like your issue might a duplicate of https://github.com/appium/appium/issues/14486

**Comment by SaqibSuhail** [comment] 2020-06-30 09:04
We are not trying to perform any action here, we want to just locate the red box which is visible in the screenshot using Appium inspector. So i'm not sure what server logs would be available since no action is being performed.
Please share your thoughts on this.

**Comment by mykola-mokhnach** [comment] 2020-06-30 09:08
Sorry, I don't have any other ideas except of these mentioned in the tickets above.

**Comment by mykola-mokhnach** [comment] 2020-07-05 18:51
Closed as third party issue

**Closed by mykola-mokhnach** 2020-07-05 18:51 UTC
Labels: ThirdParty, XCUITest
