### ISSUE TITLE
when I use appium to find element ,  it happens the error " uncaughtException: read ECONNRESET" 

### ISSUE THREAD

**Issue by smallhannahshen** [appium/appium#11437] opened 2018-09-26 12:30 UTC
## The problem

when I use appium to find element ,  it happens the error " uncaughtException: read ECONNRESET" . I try to use `driver.pressKeyCode(4)` to handle with the exception, but this error `failed: Connection refused: connect` happens:
```
org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'DJI-PC', ip: '10.61.122.123', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_181'
Driver info: driver.version: AndroidDriver
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: win7
* Node.js version (unless using Appium.app|exe): v8.11.4
* Mobile platform/version under test: Android 5.1.1
* Real device or emulator/simulator: Real device 
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[HTTP] <-- POST /wd/hub/session/ab112e47-79a7-4798-89c6-cce53eb4beca/element 500
 144 ms - 164
[HTTP]
[HTTP] --> POST /wd/hub/session/ab112e47-79a7-4798-89c6-cce53eb4beca/element
[HTTP] {"using":"xpath","value":"//android.widget.ImageView[@resource-id='dji.go
.v4:id/fpv_top_setting_img']"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//andr
oid.widget.ImageView[@resource-id='dji.go.v4:id/fpv_top_setting_img']","ab112e47
-79a7-4798-89c6-cce53eb4beca"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8201/w
d/hub/session/57d856f3-1019-479e-aa1d-b9039368a502/element] with body: {"strateg
y":"xpath","selector":"//android.widget.ImageView[@resource-id='dji.go.v4:id/fpv
_top_setting_img']","context":"","multiple":false}
[MJSONWP] Encountered internal error running command:  {"w3cStatus":400,"jsonwp"
:{"sessionId":"57d856f3-1019-479e-aa1d-b9039368a502","status":7,"value":"An elem
ent could not be located on the page using the given search parameters."}} Proxy
RequestError: Could not proxy command to remote server. Original error: 500 - {"
sessionId":"57d856f3-1019-479e-aa1d-b9039368a502","status":7,"value":"An element
 could not be located on the page using the given search parameters."}
[MJSONWP]     at JWProxy.proxy$ (D:\develop\node\node_global\node_modules\appium
\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:152:13)
[MJSONWP]     at tryCatch (D:\develop\node\node_global\node_modules\appium\node_
modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (D:\develop\node
\node_global\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.
js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as t
hrow] (D:\develop\node\node_global\node_modules\appium\node_modules\babel-runtim
e\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (D:\develop\node\node_global\
node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP]     at <anonymous>
[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[HTTP] <-- POST /wd/hub/session/ab112e47-79a7-4798-89c6-cce53eb4beca/element 500
 129 ms - 164
[HTTP]
uncaughtException: read ECONNRESET
        {"date":"Wed Sep 26 2018 20:11:56 GMT+0800 (中国标准时间)","process":{"p
id":15560,"uid":null,"gid":null,"cwd":"D:\\RuncaseIndependence","execPath":"D:\\
develop\\node\\node.exe","version":"v8.11.4","argv":["D:\\develop\\node\\node.ex
e","D:\\develop\\node\\node_global\\node_modules\\appium\\build\\lib\\main.js"],
"memoryUsage":{"rss":98828288,"heapTotal":76943360,"heapUsed":65722488,"external
":121690}},"os":{"loadavg":[0,0,0],"uptime":27523.2041275},"trace":[{"column":11
,"file":"util.js","function":"_errnoException","line":992,"method":null,"native"
:false},{"column":25,"file":"net.js","function":"TCP.onread","line":618,"method"
:"onread","native":false}],"stack":["Error: read ECONNRESET","    at _errnoExcep
tion (util.js:992:11)","    at TCP.onread (net.js:618:25)"]}

## Code To Reproduce Issue [ Good To Have ]

driver.pressKeyCode(4);

**Comment by mykola-mokhnach** [comment] 2018-09-26 12:45
Duplicate of https://github.com/appium/appium/issues/11315

**Closed by mykola-mokhnach** 2018-09-26 12:45 UTC
