### ISSUE TITLE
visible = false 

### ISSUE THREAD

**Issue by weizer96** [appium/appium#17272] opened 2022-07-27 09:35 UTC
The property of the element is not defined correctly. When viewing the properties in the ios application, the visible element is marked visible = false

**Comment by mykola-mokhnach** [comment] 2022-07-27 10:12
Please provide a proper issue description according to the template.
Closed as incomplete also duplicate of https://github.com/appium/appium/issues/11507

**Closed by mykola-mokhnach** 2022-07-27 10:12 UTC
