### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not find 'aapt.exe'

### ISSUE THREAD

**Issue by T-e-j-k-u-m-a-r** [appium/appium#13561] opened 2019-11-07 12:04 UTC
Please find the sample code to launch the calculator app: 

package mobileAutomation;

import java.net.MalformedURLException;
import java.net.URL;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;

public class LaunchApp {
	public static void main(String[] args) throws MalformedURLException, InterruptedException {

		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability("deviceName", "Tejkumar");
		cap.setCapability("platformName", "Android");
		cap.setCapability("platformVersion", "9");
		cap.setCapability("uuid", "DHE4C18C11002653");
		cap.setCapability("automationName", "UiAutomator2");

		cap.setCapability("appPackage", "com.android.calculator2");
		cap.setCapability("appActivity", "com.android.calculator2.Calculator");

		URL url = new URL("http://0.0.0.0:4723/wd/hub");

		// Instantiate driver object and pass URL and DESIRED CAPABILITY

		AppiumDriver<MobileElement> driver = new AndroidDriver<MobileElement>(url, cap);

		System.out.println("Mobile Automation Project");

		Thread.sleep(3000);

	}
}

------------------------
pom.xml: 

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>mobileAutomation</groupId>
	<artifactId>mobileAutomation</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<dependencies>

		
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>3.4.1</version>
		</dependency>

	</dependencies>

</project>
------------------------------------------------
APPIUM VERSION: 1.15.1
------------------------------------------------
Error Message: 

Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not find 'aapt.exe'

------------------------------------------------

**Comment by mykola-mokhnach** [comment] 2019-11-07 12:13
Duplicate of https://github.com/appium/appium/issues/13007

**Closed by mykola-mokhnach** 2019-11-07 12:13 UTC
