### ISSUE TITLE
Could not find session section for url

### ISSUE THREAD

**Issue by LatchQA** [appium/appium#11089] opened 2018-07-20 21:06 UTC
## The problem

Appium is not able to click on a particular element

https://gist.github.com/LatchQA/4dfcc4cb856cffb29764a39708d6d39b

## Environment
This is running against a real device iPhone 8 11.3.1
Appium 1.8.2-beta
Node v10.7.0
MacOS 10.13.6 (17G65)

Session seems to stop when trying to click on an element and throws this error:

Encountered internal error running command: Error: Could not proxy. Proxy error: Could not find :session section for url: /wd/hub/session/c694e9ab-ef59-42f7-9d00-f9b7c4b397bb/element/1B000000-0000-0000-5347-000000000000/click

**Comment by imurchie** [comment] 2018-07-20 21:09
Duplicate of #11081

**Closed by imurchie** 2018-07-20 21:09 UTC
