### ISSUE TITLE
Hard to debug parallel test run

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#10976] opened 2018-07-01 17:03 UTC
As server can compliment multiple client request, its hard to debug/identify from server logs to which session the failure belongs.

I remember when we got parallel testing for simulator @mykola-mokhnach did kick start this conversation.. Not sure where it ended.

**Comment by mykola-mokhnach** [comment] 2018-07-01 19:28
I assume it is a duplicate of https://github.com/appium/appium/issues/9080

**Closed** 2018-07-02 04:41 UTC
