### ISSUE TITLE
Password Field not found anymore since Appium 1.6.5

### ISSUE THREAD

**Issue by olivierschmid** [appium/appium#8771] opened 2017-07-03 08:55 UTC
## The problem

Wie have a test script working fine on Appium 1.6.4. Unfortunately it does not work anymore when updating to 1.6.5.. There is a login page with requires Username and Password. The password field cannot be selected anymore.

The field is of type XCUIElementTypeSecureTextField on iOS. The application is build with Ionic 2.

The caps are:

desired_caps['appium-version'] = '1.0'
desired_caps['platformName'] = 'iOS'
desired_caps['platformVersion'] = '10.3'
desired_caps['automationName'] = 'XCUITest'
desired_caps['newCommandTimeout'] = '360'
iphone = 'iPhone 7 Plus'
desired_caps['deviceName'] = iphone
desired_caps['app'] = os.path.abspath(
'../../mobiliar-customerapp2/platforms/ios/build/emulator/Mobiliar.app')

## Environment

* Appium version: 1.6.5
* Last Appium version that did not exhibit the issue: 1.6.4
* Desktop OS/version used to run Appium: macOS Sierra 10.12.5
* Node.js version (unless using Appium.app|exe): 6.11.0 
* Mobile platform/version under test: iOS Simulator / iOS Real Devices with iOS 10.3.2
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Happens on both environments

## Link to Appium logs

https://gist.github.com/olivierschmid/e85d410eb0889494bf6c0d8922bfa70b

## Code To Reproduce Issue [ Good To Have ]

Here is the script (python) section which references the field:

wd.find_element_by_accessibility_id("Passwort").click()
time.sleep(5)
ActionChains(wd).send_keys("xxxyyy").perform()

We then recorded with the new Appium App Recorder - that also did not work (with XPath).

el9 = driver.find_element_by_xpath("//XCUIElementTypeSecureTextField[@name=\"Passwort\"]")
el9.click()
el9.send_keys("Mobi@123")

**Comment by mykola-mokhnach** [comment] 2017-07-03 09:34
What is the output of get_page_source method on this page?

**Comment by mykola-mokhnach** [comment] 2017-07-03 09:41
Also the very last log record shows absolute different locator from what was mentioned in the issue description:

> [debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"xpath","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeWebView[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[5]/XCUIElementTypeTextField[1]","description":"unable to find an element"},"sessionId":"C40AB40B-0B72-4EDA-BE3C-E24739CC57A5","status":7}

**Comment by plaquette** [comment] 2017-07-03 10:59
i guess the locator is different since the designated element is not found, so appium just continues - hence the new locator.

the keys for the password are send, but to the wrong textfield (the one "above", the cursor stays there...) 

and it still behaves that way even if an additional click on the textfield, where the keys are supposed to end up, is performed before we send them.

[on 1.6.4 it works without a problem]

**Comment by olivierschmid** [comment] 2017-07-03 11:15
Here is the output of wd.page_source:

https://gist.github.com/olivierschmid/02dfc40417a88fe59edf1804ce4084da

**Comment by mykola-mokhnach** [comment] 2017-07-03 11:32
> wd.find_element_by_accessibility_id("Passwort").click()

This wil probably not work, since the page actually contains two elements with accessibility id "Passwort". Regarding xpath - the locator looks correct. It should work. You may also try the following locator based on iOS predicate:

```
type == 'XCUIElementTypeSecureTextField' AND name == 'Passwort'
``` 

Please attach another log if none of above works.

**Comment by plaquette** [comment] 2017-07-03 12:32
we are aware of the two elements with the same name, thats why we also tried to explicitly access the "Passwort"-textfield using its unique XPATH, but it doesn't change the outcome.

**Comment by olivierschmid** [comment] 2017-07-03 12:43
We tried:
    wd.find_element_by_xpath("//XCUIElementTypeSecureTextField[@name='Passwort']").click()
and
    wd.find_element_by_xpath("//XCUIElementTypeSecureTextField[@name=\"Passwort\"]").click()

Same outcome :-(.

**Comment by mykola-mokhnach** [comment] 2017-07-03 12:49
> Please attach another log if none of the above works.

Also, it is recommended to print page source right before locating the element - it might be that automation is too fast and the element you are looking for simply does not have enough time to appear on the page.

**Comment by olivierschmid** [comment] 2017-07-03 13:20
Here the print page before locating the element. 

https://gist.github.com/olivierschmid/ae053c853619a7a3fc598ae731248e2b

We also incremented the sleep before locating the password field. Unfortunately same outcome.

**Comment by mykola-mokhnach** [comment] 2017-07-03 13:29
How about the log? Also, I see the field is inside a webview. Probably, it would work if one switches to webview context before field location happens..

**Comment by olivierschmid** [comment] 2017-07-03 15:26
Yes - because it is a hybrid APP it runs on webview. I don't understand why only this password-field cannot be accessed while we don't have any problems at all the other components of the APP. And it's strange that it worked with 6.5.3 and 6.5.4.
I now set the capability to webview (caps["autoWebview"] = "true"). Now nothings works at all. I made a fresh recording with the new recording (with webview=true) feature of the Appium-APP. Since the recording itself works fine - playback does not.

**Comment by jlipps** [comment] 2017-07-28 22:11
@olivierschmid when in webview mode, you'll want to use the regular selenium commands, including finding by class name, id, etc... finding by accessibility id will no longer work.

iOS does show certain web elements in the native hierarchy sometimes, but when you are in a web context you will need to use the html source to guide your element finding strategy.

but maybe I don't understand what you mean when you say "nothing works at all" in webview mode. can you elaborate?

**Comment by plaquette** [comment] 2017-08-08 13:00
hi - sorry it took me so long to answer

the issue is, that the password-field (which we used be able to find using on either finding by name or id or accessibility id or XPATH) does no longer work after the update to 1.65

[our work around is the downgrade to 1.64 where it still works...]

what is meant by "nothing works at all" - is the fact that we can not click nor send keys to the specified fields.

what do you mean by "guide your element finding strategy" ?

thanks in advance, best p.

**Comment by plaquette** [comment] 2017-08-09 11:53
some additional infos:

- we updated to the newest version of appium desktop, but the issue still remains

- but we were able to isolate it a bit further. the issue is, since v. 1.65, its no longer possible to select text fields in order to send them keys. It does not matter wich field - all of them are not directly selectable:

![bildschirmfoto 2017-08-09 um 13 45 14](https://user-images.githubusercontent.com/28099660/29120108-2b40f336-7d09-11e7-821d-6cfb380b7939.png)

the same happens vice versa if we use either the mouse to click the second field in the emulator or specifically send tab-coordinates via appium:


![bildschirmfoto 2017-08-09 um 13 50 00](https://user-images.githubusercontent.com/28099660/29120234-b1f72116-7d09-11e7-9dea-a05523b1b338.png)


```
el1 = driver.find_element_by_xpath("//XCUIElementTypeTextField[@name=\"E-Mail oder Benutzername\"]")

el1.click()

el1.send_keys("random@email.com")

el2 = driver.find_element_by_xpath("//XCUIElementTypeSecureTextField[@name=\"Passwort\"]")

el2.click()

el2.send_keys("genericPW123")

TouchAction(driver).tap([(41, 193)])

el2.click()

el2.send_keys("genericPW123")

el3 = driver.find_element_by_xpath("//XCUIElementTypeTextField[@name=\"E-Mail oder Benutzername\"]")

el3.click()

el3.send_keys("random@email.com")

```

**Comment by plaquette** [comment] 2017-08-10 11:01
in order for you guys to reproduce the issue, i build a minimal example app

just two different textfields, and as you can see - the problem remains the same. its not possible to select textfields to send them keys:

![bildschirmfoto 2017-08-10 um 12 58 21](https://user-images.githubusercontent.com/28099660/29167669-a21e01a2-7dcb-11e7-8a56-e29d1ac5c153.png)


you can download the file [here](http://s000.tinyupload.com/index.php?file_id=07264766037752743654)

**Comment by plaquette** [comment] 2017-08-14 13:54
@jlipps do you mind having a look again

best, p.

**Comment by jlipps** [comment] 2017-08-14 20:59
@plaquette i would not recommend using native locators for a webview app. i would also not recommend using appium desktop. instead i would use the `setContext` command to get into the web context and use selenium locators (like `id`, `css`, etc...). this is going to be more reliable. to inspect your webview, simply open up safari and connect to your app's webview. you'll get a full debugger. i wouldn't use appium desktop for this as its hybrid support is not good.

the underlying reason you're noticing a difference between 1.6.4 and 1.6.5 probably has to do with changes in WebDriverAgent, not appium.

**Comment by plaquette** [comment] 2017-08-15 08:18
`npm install -g appium@1.6.6-beta.4`

did the trick
- it was a problem with the WebDriver
which was fixed in the above version of appium

**Comment by jlipps** [comment] 2017-08-18 00:18
excellent, thanks!

**Closed by jlipps** 2017-08-18 00:18 UTC
Labels: NeedsInfo, XCUITest

**Comment by enguyen1967** [comment] 2017-09-18 19:37
When I installed appium 1.6.6-beta.4 I to the following error 
ericn$ npm install -g appium@1.6.6-beta.4
path.js:1170
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1170:25)
    at Function.Module._resolveLookupPaths (module.js:410:17)
    at Function.Module._resolveFilename (module.js:484:22)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)

Can you please let me know how to fix it? Thanks for your help

**Comment by enguyen1967** [comment] 2017-09-18 19:42
I have the same problem with email and password fields and thanks for posting this @plaquette. But when install 1.6.6-beta.4 I got above error. Any helps are appreciated

**Comment by enguyen1967** [comment] 2017-09-18 19:45
I got fix. Just cd out of current dir and install again then it installed.

**Comment by prakashpqa** [comment] 2018-10-08 06:17
I am having this problem in appium 1.9.1. Anybody who can help!
