### ISSUE TITLE
Appium inspector throws 'AX error -25205', for iPhone 7plus with ios 10.2.1

### ISSUE THREAD

**Issue by SamyQAZ** [appium/appium#9877] opened 2017-12-29 07:58 UTC
## Appium inspector cannot inspect elements 

Use appium.app inspector to inspect elements, throws AX error -25205 error and doesn't let get through ui elements

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.2.7 (1.2.7)
* Desktop OS/version used to run Appium: macOS Sierra Version 10.12.6
* Node.js version (unless using Appium.app|exe): v7.10.0
* Mobile platform/version under test: iOS 10.2.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

Appium.app inspector doesn't allow to inspect ui elements. It throws 'AX error -25205' error. This issue cannot be reproduced for real devices with iOS version 10.3.1, 10.3.2 and 11.0.2

However, when used appium CLI to run tests it works.

## Screenshot of Issue

<img width="1067" alt="screen shot 2017-12-29 at 3 42 35 pm" src="https://user-images.githubusercontent.com/30425316/34432258-b5dab89e-ecb0-11e7-9d4f-ff4db410c7bd.png">

**Comment by mykola-mokhnach** [comment] 2017-12-29 08:02
Duplicate of https://github.com/facebook/WebDriverAgent/issues/703

**Closed by mykola-mokhnach** 2017-12-29 08:02 UTC
