### ISSUE TITLE
bug: Unable to perform double_click and context_click using Actions in Appium v2 WinAppDriver. 

### ISSUE THREAD

**Issue by testwisely** [appium/appium#17933] opened 2022-12-14 09:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am upgrading my Appium v1 tests to Appium v2.0.beta.46. I could do certain mouse operations in v1, e.g. `double_click` two ways:

1. `driver.mouse.double_click`
2. `driver.action.move_to(elem).double_click.perform`

But, neither works in Appium 2. I understand `driver.mouse` is deprecated. The action statement runs without error,  no double-click is fired (as you do with a mouse). Instead, there is a quick finger-touch ripple effect at the top-left corner of the window. 

### Expected Behavior

In my simple driving notepad (on Windows) test script, if a `double_click` is fired properly, I should see the text highlighted.

`context_click` does not work either.  I tried looking for examples of using the mouse in Appium v2 (for WinAppDriver), including appium_lib (ruby) source, the closest information I can find is:  https://appium.io/docs/en/commands/interactions/actions/

### Minimal Reproducible Example

```
require 'appium_lib'
require 'rspec'

describe "NotePad Mouse" do

  before(:all) do
    opts = {
      caps: {
        automationName: "windows",
        platformName: "Windows",
        app: "notepad.exe",
      },
      appium_lib: {
        server_url: "http://127.0.0.1:4723",
      },
    }

    @driver = Appium::Driver.new(opts).start_driver
    @main_win = @driver.find_element(:name, "Untitled - Notepad")
  end

  def main_win
    @main_win
  end

  after(:all) do
     @driver.quit 
  end
  
   #TODO failling here for v2
  it "Double click" do
    main_win.send_keys("Test Wisely")
    main_win.send_keys(:left)
    
    editor_ctrl = @driver.find_element(:name, "Text Editor")
    #  Appium V1 mouse is no longer supported, use #action instead
    # @driver.mouse.move_to(editor_ctrl)
    # @driver.mouse.double_click
    
    # runs , but  no effect
    @driver.action.move_to(editor_ctrl).double_click.perform();
    sleep 5 # keep it up to see effect
  end

end

```

### Environment

- Operating system: **Windows 10**
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): **2.0.0-beta.46**
  - Node.js version (output of `node --version`): **v18.12.1**
  - `npm` version (output of `npm --version`):  **8.19.2**
  - Last `appium` version which did _not_ exhibit the problem:  **Appium v1.19.1**
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment] 2022-12-14 20:42
Duplicate of https://github.com/appium/appium/issues/16268

**Closed by mykola-mokhnach** 2022-12-14 20:42 UTC
Labels: Bug, Needs Triage
