### ISSUE TITLE
Android: use appium to run android device and get error code 255

### ISSUE THREAD

**Issue by xsj931122** [appium/appium#12831] opened 2019-06-26 09:20 UTC
## The problem

An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/shxia/Library/Android/sdk/platform-tools/adb -P 5037 -s 535b7b7a shell pm install -g /data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk' exited with code 255'; Stderr: 'Security exception: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:445) at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:404) at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:2418) at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:907) at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:158) at android.os.ShellCommand.exec(ShellCommand.java:103) at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21856) at android.os.Binder.shellCommand(Binder.java:634) at android.os.Binder.onTransact(Binder.java:532) at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2809) at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4017) at android.os.Binder.execTransact(Binder.java:733)'; Code: '255'

**Comment by mykola-mokhnach** [comment] 2019-06-26 09:51
Duplicate of https://github.com/appium/appium/issues/12817

**Closed by mykola-mokhnach** 2019-06-26 09:51 UTC
