### ISSUE TITLE
Cannot DELETE session (driver.quit)

### ISSUE THREAD

**Issue by igalep** [appium/appium#6432] opened 2016-04-24 11:31 UTC
## The problem

The instruments don't stop after driver.quit() was executed
## Environment
- Appium version: 1.5.2
- Last Appium version that did not exhibit the issue : 1.4.16
- Desktop OS/version used to run Appium: OSX 10.11.4
- Node.js version (unless using Appium.app|exe): 0.12.6
- Mobile platform/version under test: iOS 9.1
- Real device or emulator/simulator: simulator
- Appium CLI or Appium.app|exe: Appium CLI
## Details

The instruments don't stop after driver.quit() was executed
## Link to Appium logs

[https://gist.github.com/igalep/d912a357c7fe2046c422b2b181b04f2b](https://gist.github.com/igalep/d912a357c7fe2046c422b2b181b04f2b)

**Comment by imurchie** [comment] 2016-04-24 20:26
Does Instruments never stop? Appium waits for 5 seconds and then continues if it doesn't, because there is nothing that it can do.

**Comment by igalep** [comment] 2016-04-25 06:07
@imurchie - the instruments are stack (not responding) and appium continue to run forever ...

**Comment by imurchie** [comment] 2016-04-25 15:24
I'm not sure what "stack" means.

`appium continue to run (nevertheless the test has finished but it still trying to look for the dynamic objects which are defined within the page object) forever ...`

What is "it" here? Appium? I don't see anything in the logs snippet that you provided that indicates this. Or the test? In which case, does it not get the return from the `DELETE` command to end the session?

**Comment by igalep** [comment] 2016-04-25 17:52
@imurchie this are the logs for appium 1.5.2 :
**_[iOS] Instruments didn't shut down. Error: Instruments did not terminate after 5 seconds!
[debug] [iOSLog] Stopping iOS log capture
[debug] [iOS] Reset not set, not ending sim
[Appium] Removing session 9dc7db27-0381-446d-ad04-cf35fb835dff from our master session list
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/9dc7db27-0381-446d-ad04-cf35fb835dff 200 5017 ms - 76

_**


And these are the logs for 1.4.16 :
_**Instruments didn't terminate after 3 seconds; trying to kill it
info: [debug] Killall instruments
info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Cleaning up after instruments exit
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall Simulator
info: [debug] Resetting Content and Settings for Simulator
info: node-simctl: Executing: xcrun with args: simctl erase 62B114D2-9799-4918-A63B-38078FEAE89E and timeout: 2000
info: [debug] Cleaning up appium session
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"eac600a8-ef33-408c-8354-7e7245259075"}
info: <-- DELETE /wd/hub/session/eac600a8-ef33-408c-8354-7e7245259075 200 4189.743 ms - 76 {"status":0,"value":null,"sessionId":"eac600a8-ef33-408c-8354-7e7245259075"}**_

**Comment by igalep** [comment] 2016-06-20 11:00
any update on this one ?
in appium ver 1.5.3 the problem still exists

**Comment by igalep** [comment] 2016-07-03 11:31
Guys  , any idea how to solve it ?

**Comment by bkaunteya** [comment] 2016-08-10 08:51
Hi igalep,

i'm also getting the same issue. did you get any solution?

**Comment by dpgraham** [comment] 2017-07-20 18:37
Instruments no longer supported. Closing.

**Closed by dpgraham** 2017-07-20 18:37 UTC
Labels: iOS

**Comment by romin771** [comment] 2017-10-17 11:03
that's funny , you are just closing tickets without solution :)) 

ok, i have the same issue 
this is my error in eclipse when i run my script : 


and this is the last part of my log : 

 org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS


[MJSONWP] Received response: null
[MJSONWP] But deleting session, so not returning
[MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/e653d7e1-c9b5-4142-bd87-55be503fc229 200 527 ms -


can any, anyone, help me whit this issue ?

**Comment by imurchie** [comment] 2017-10-17 11:30
@romin771 What is the issue. That little tiny bit of the logs looks perfectly fine.

**Comment by Vadim-Kovrizhkin** [comment] 2018-10-18 06:58
I have also this issue. And this is very random issue. Can not identify what is the root cause. 
I don't see much in Appium logs

```
debug] [ADB] Running '/usr/local/bin/adb -P 5037 -s J4NPCV013793MK7 shell input keyevent 3'
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Test results for WatcherResultPrinter=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Time: 139.96
[debug] [AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 4 device(s) connected
[debug] [ADB] Running '/usr/local/bin/adb -P 5037 -s J4NPCV013793MK7 shell ps'
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Getting connected devices...
[debug] [ADB] 4 device(s) connected
[debug] [ADB] Running '/usr/local/bin/adb -P 5037 -s J4NPCV013793MK7 shell am force-stop io.appium.unlock'
[debug] [AndroidDriver] App was not copied, so not deleting
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1539813934566 (18:05:34 GMT-0400 (EDT))
[debug] [W3C] Received response: null
[debug] [W3C] But deleting session, so not returning
[debug] [W3C] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/1c98cd71-6989-4fb4-82fb-4d431724f655 200 1465 ms - 76
```

but execution will hang on trying to quit driver. 
If it is on Jenkins, then Jenkins job will hang forever until I abort it. 

It is reproduced for both Android and iOS
Appium: 1.8.0
Android: 7, 8 
iOS: 11 or 12

but I think it does not matter which version

@dpgraham  can we reopen this issue?
