### ISSUE TITLE
 “WebDriverAgentRunner_iphoneos13.1-arm64.xctestrun” doesn’t exist." 

### ISSUE THREAD

**Issue by EitanBe** [appium/appium#13434] opened 2019-10-16 11:50 UTC
## The problem

xcodebuild[92960:9466326] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos13.1-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/*****/Library/Developer/Xcode/DerivedData/WebDriverAgent-aybfmcdbpyvrotdoxmdtdkhfraja/Build/Products/WebDriverAgentRunner_iphoneos13.1-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7f9fc76ee6e0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}} 2019-10-16 14:35:30:541 - [35m[Xcode][39m  2019-10-16 14:35:30:542 - [35m[Xcode][39m  2019-10-16 14:35:30:542 - [35m[Xcode][39m  2019-10-16 14:35:30:546 - [35m[Xcode][39m  2019-10-16 14:35:30:546 - [35m[Xcode][39m  2019-10-16 14:35:30:547 - [35m[Xcode][39m ** TEST BUILD FAILED **

## Environment
IOS 13.1
xcode 11.1
appium v1.15.1
real ios device

**Comment by mykola-mokhnach** [comment] 2019-10-16 11:54
Duplicate of https://github.com/appium/appium/search?q=%22Error+writing+xctestrun+file%22&type=Issues

**Closed by mykola-mokhnach** 2019-10-16 11:54 UTC

**Comment by dvillacis94** [comment] 2019-11-06 21:31
This issue is happening also on with iOS 13.2:
WebDriverAgentRunner_iphoneos13.1-arm64.xctestrun

Environment:
IOS 13.2
xcode 11.2
appium v1.15.1 (tried also appium@1.16.0-beta.1)
iPhone 11 Pro Max
