### ISSUE TITLE
Cannot verify the signature of appium-uiautomator2-server apk

### ISSUE THREAD

**Issue by sshock** [appium/appium#14724] opened 2020-09-10 21:43 UTC
## The problem

I'm running into a `Cannot verify the signature of '/home/deployer/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.12.3.apk'` error today when trying to establish a session.  I am running `appium@beta` version installed a week ago.  Somehow I never ran into this at all over the last week until just now, but now it is happening every time.  Other servers running appium 1.17.1 are not running into this.

It appears restarting appium makes the problem go away.  Apparently the problem only occurs after appium has been running for a few days...

## Environment

* Appium version (or git revision) that exhibits the issue: appium@beta (installed 1 week ago)
* Last Appium version that did not exhibit the issue (if applicable): 1.17.1
* Desktop OS/version used to run Appium: Ubuntu 18.04.4 LTS
* Node.js version (unless using Appium.app|exe): 10.22.0
* Npm or Yarn package manager: 6.14.6
* Mobile platform/version under test: Android 8.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: cli

## Details

Here is the full error:

> An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of '/home/deployer/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.12.3.apk'. Original error: Command '/usr/lib/jvm/default-java/bin/java -Xmx1024M -Xss1m -jar /usr/lib/android-sdk/build-tools/27.0.1/apksigner.jar verify --print-certs /home/deployer/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.12.3.apk' exited with code 1

When I run that directly, it has some warnings but does succeed with exit code 0:
```
[ PRODUCTION ] deployer@sd-prod-mayhem1:~$ /usr/lib/jvm/default-java/bin/java -Xmx1024M -Xss1m -jar /usr/lib/android-sdk/build-tools/27.0.1/apksigner.jar verify --print-certs /home/deployer/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.12.3.apk
Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
WARNING: META-INF/jdom-info.xml not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/services/org.xmlpull.v1.XmlPullParserFactory not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/INDEX.LIST not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/io.netty.versions.properties not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[ PRODUCTION ] deployer@sd-prod-mayhem1:~$ echo $?
0
```

## Link to Appium logs

I'm not seeing anything in the appium log related to this error, but I'll include it anyway :)

https://gist.github.com/sshock/76af5741a8ca38c7ac49c75e1d73e003

**Comment by mykola-mokhnach** [comment] 2020-09-11 05:54
There are no mentions of `apksigner.jar` in the above log at all. Are you sure it is the valid one?

**Comment by sshock** [comment] 2020-09-11 20:45
@mykola-mokhnach Thanks for asking.  I checked again on both the server in question and a few other servers running appium@beta and sadly I cannot find anything about it in the log.

Here's where it's gets interesting though.  I checked some of my servers running 1.17.1 and, if I go back a little ways, they actually do have similar failures in there!  I'm surprised I didn't notice this on the other servers, but I think this means this is not a new problem.

So..., if it helps, here is a log from one of my servers running appium 1.17.1:

https://gist.github.com/sshock/dde82100c9aed3d7f7c603304c262594

In it you will find both of these errors related to apksigner.jar:
* "Cannot use apksigner tool for signature verification."
* "Cannot use apksigner tool for signing."

**Comment by mykola-mokhnach** [comment] 2020-09-12 05:38
apksigner tool belongs to Android SDK and it is hard to say why it is failing without printing any error messages. I would try to set `skipServerInstallation` cap to `true` as a possible workaround. This will speed up session init in case you know that uia2 server binaries are already present on the device and there is no need to sign/install them.
Also, it makes sense to upgrade android SDK to the recent version

**Comment by sshock** [comment] 2020-09-12 16:56
Those are good ideas, thanks.

**Comment by mykola-mokhnach** [comment] 2020-09-15 08:31
Closed as third party issue

**Closed by mykola-mokhnach** 2020-09-15 08:31 UTC
Labels: ThirdParty, UIAutomator2

**Comment by sshock** [comment] 2020-09-15 18:20
Possibly related issues in case the comments in there help anyone: https://github.com/appium/appium-desktop/issues/327

**Comment by sshock** [comment] 2020-12-02 19:29
@mykola-mokhnach using the latest appium, 1.19.0, I now am getting more information about this error:

```
An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of '/home/deployer/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.15.0.apk'. Original error: Error occurred during initialization of VM
java.lang.Error: Properties init: Could not determine current working directory.
	at java.lang.System.initProperties(java.base/Native Method)
	at java.lang.System.initPhase1(java.base/System.java:1948)
```

Does that give enough info to help us track down and fix this problem.  Is it still a third party issue?  I'm a little confused how it works fine for a few days then all the sudden java and environment is no good anymore?

**Comment by mykola-mokhnach** [comment] 2020-12-02 19:46
I would try to explicitly set the current directory when executing the script. E.g. you could try to replace 

```
  log.debug(`Starting apksigner: ${util.quote(fullCmd)}`);
  const {stdout, stderr} = await exec(fullCmd[0], fullCmd.slice(1));
```

in `build/lib/apk-signing.js` file of `appium-adb`  module with

```
  log.debug(`Starting apksigner: ${util.quote(fullCmd)}`);
  const {stdout, stderr} = await exec(fullCmd[0], fullCmd.slice(1), {
    cwd: path.dirname(apkSignerJar)
  });
```

Then run your stuff and see if that changes something

**Comment by sshock** [comment] 2020-12-02 21:16
Cool, thanks for the suggestion.  I will give it a try soon and let you know.  It may take 2 or 3 weeks after making the change to really know that it helped ;)

**Comment by sshock** [comment] 2020-12-07 23:39
@mykola-mokhnach I finally got a free moment to go in and put this test in place on half my servers.  I'll let you know what I find out.  E.g., after a week or two if the problem re-occurs but only on the half of the servers that I didn't update, that will be pretty good indication that this did the trick...

**Comment by senchi** [comment] 2020-12-21 14:20
@mykola-mokhnach I'm not sure if related to this, but I'm getting very similar error:

```
0|appium  | [debug] [W3C] Encountered internal error running command: Error: Cannot verify the signature of '/Users/genijalno/.nvm/versions/node/v12.20.0/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.17.1.apk'. Original error: The JAVA_HOME environment variable must be set for Android Tools to work properly
0|appium  | [debug] [W3C]     at ADB.checkApkCert (/Users/genijalno/.nvm/versions/node/v12.20.0/lib/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:267:11)
0|appium  | [HTTP] <-- POST /wd/hub/session 500 12928 ms - 1133
```

The error suggests that the JAVA_HOME is not set, but it is and the bins are in the PATH as well, heres my `~/.profile`
```
export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
#export JAVA_HOME="/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home"
export ANDROID_HOME="/Users/genijalno/Library/Android/sdk"

export PATH="$PATH:$JAVA_HOME/bin:$ANDROID_HOME/platform-tools"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
```
This is the cmd output:
```
genijalno-e2e-dev:~ genijalno$ echo $JAVA_HOME 
/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
```

Not sure if important, but I'm running on "latest" [Appium forked](http://github.com/genijalno-ba/appium) with a minor [change in the appium-adb module](https://github.com/genijalno-ba/appium-adb/commit/4aacc39f73f993d2aa677f73092f634e5c15d95b).

**Comment by mykola-mokhnach** [comment] 2020-12-21 14:27
@senchi No, this is unrelated. Refer to https://github.com/appium/java-client/blob/master/docs/environment.md

**Comment by sshock** [comment] 2020-12-21 16:00
@mykola-mokhnach good news: it has been two weeks and the problem has not resurfaced.  I think we have a winner!

**Comment by mykola-mokhnach** [comment] 2020-12-21 18:13
@sshock Cool, would you like to create a PR to appium-adb?

**Comment by sshock** [comment] 2020-12-21 18:28
@mykola-mokhnach sure, I can do that; I'll put it on my todo list now...

**Comment by sshock** [comment] 2020-12-28 18:54
@mykola-mokhnach bad news: unfortunately setting CWD there did **not** fix the problem; it just so happened that it took 2.5 weeks for it to show up this last time; so waiting 2 weeks was not long enough; I just found out the hard way that all our appium jobs have been failing the last 3 days due to this error :(

**Comment by sshock** [comment] 2021-01-14 17:50
@mykola-mokhnach Can I avoid this problem completely by skipping apk verification?  There's a `noSign` option/capability (which I'm already using), but I don't see like a `noVerify` option.

**Comment by mykola-mokhnach** [comment] 2021-01-14 18:02
I would try [skipServerInstallation](https://github.com/appium/appium-uiautomator2-driver#driverserver)

**Comment by sshock** [comment] 2021-01-16 00:46
Currently I still rely on appium installing uiautomator2 for me, which becomes important both when I add a new android device and when I upgrade appium.

But at some point I am planning to add support into my own code to control various apps that I need installed on the device, and perhaps at that time I can handle uiautomator2 myself as well...

**Comment by umanniyaz** [comment] 2021-04-22 16:06
Is there any solution to this problem??

**Comment by sshock** [comment] 2021-04-22 17:05
@umanniyaz I've been resorting to restarting appium server once every two weeks.

**Comment by sshock** [comment] 2021-07-09 19:01
FYI, I finally got around to adding support to my own service to install the uiautomator2 apk (and test apk) myself before creating the appium session, and with that in place I was able to set the `skipServerInstallation` cap to `true` and I haven't looked back since :)

It's been 3 weeks and so far this error has not resurfaced; I'm pretty sure with this workaround I will never run into this problem again, yay!

**Comment by jlipps** [comment] 2021-07-12 18:15
thanks for the report @sshock !

**Comment by sonalpriya17** [comment] 2021-11-11 20:35
I am facing this issue :
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.24.0.apk'. Original error: The JAVA_HOME environment variable must be set for Android Tools to work properly

however my path is set right:

export JAVA_HOME=$(/usr/libexec/java_home)
export PATH=${JAVA_HOME}/bin:$PATH
export ANDROID_HOME=/Users/sonal.p/Library/Android/sdk
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
export ANDROID_SDK_ROOT=$ANDROID_HOME
export ANDROID_AVD_HOME=/Users/sonal.p/.android/avd @sshock

**Comment by Samiksha2703** [comment] 2021-11-24 04:45
I am facing this issue when I am using real device also emulator 

An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\samikshashende\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.21.1.apk'. Original error: Command 'C:\Program Files\Java\jdk1.8.0_301\bin\bin\java.exe' not found. Is it installed?

![ENV](https://user-images.githubusercontent.com/70154973/143176369-41327bf2-31f1-41e8-8269-4d48e9b2f6fa.PNG)
![Path](https://user-images.githubusercontent.com/70154973/143176383-0d2d381b-1ba7-4ca6-bf07-31d401af26e8.PNG)

Find image for environmental variable

**Comment by cundi** [comment] 2023-09-25 09:38
same problem with emulator, while 2023

**Comment by shomoa** [comment] 2023-11-01 21:10
Kindly help me to solve this error?
![image](https://github.com/appium/appium/assets/96208203/b3e22765-1d62-4eee-b8c8-59f39c1e920a)

**Comment by gauravkadhane** [comment] 2024-02-26 16:17
facing this issue:
Error
Failed to create session. An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\GAURAV~1\AppData\Local\Temp\2024126-12732-1xt7ok4.ivot\appium-uiautomator2-server-v4.27.0.apk'. Original error: The 'java.exe' binary could not be found neither in PATH nor under JAVA_HOME (C:\Program Files\Common Files\Oracle\Java\bin)
is there any solution?

**Comment by Hanssteps** [comment] 2024-04-04 11:58
What solved the trick for me is installing the latest Java runtime environment https://www.java.com/en/download/manual.jsp
After that the scripts ran like Usain Bolt. Amazingly fast!
