### ISSUE TITLE
Starting WebDriverAgent and Using webDriverAgentUrl capability

### ISSUE THREAD

**Issue by baclark774** [appium/appium#7681] opened 2017-01-11 14:35 UTC
## The problem

In an enterprise setup we want to build a .app package of the webdriver agent and distribute that package for all of our provisioned devices. Then launch the agent prior to test without each user having to setup code signing individually, and connect to it.

Currently I'm using ios-deploy to install and launch the app:
ios-deploy -b /path/to/the/local/WebDriverAgentRunner-Runner.app -L

Then running my appium instance with a capability as follows:
capabilities.setCapability("webDriverAgentUrl", "http://realDeviceIPAddress:8100");

But at this point the request is sent but it just hangs. My understanding was that I should be able to spin up WDA before hand using something like this approach and then connect to it with this capability?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac Sierra
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 10.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

**Comment by imurchie** [comment] 2017-01-11 14:40
Can you provide the logs so we can see what is going on?

**Comment by mykola-mokhnach** [comment] 2017-01-11 14:41
Can you check url accessibility manually? it is really listening on port 8100 at the time when appium is started?

**Comment by baclark774** [comment] 2017-01-11 15:27
Can confirm it's listening manually.

{
  "value" : "Unhandled endpoint: \/ -- http:\/\/192.168.1.23:8100\/ with parameters {\n    wildcards =     (\n        \"\"\n    );\n}",
  "sessionId" : "E81C0C00-44EF-4A98-A36C-73B965546D95",
  "status" : 1
}

**Comment by baclark774** [comment] 2017-01-11 16:03
Logs below. The last line where it tries to post to the running wda is where it just hangs forever:

[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"","bundleId”:”myappbundsle”,”deviceName":"null","platform":"MAC","webDriverAgentUrl":"http://192.168.1.23:8100","excludedDevices":"6129000567,6128001080","screenshotWaitTimeout":"5","sendKeyStrategy":"setValue","newCommandTimeout":"60","automationName":"XCUITest","browserName":"","takesScreenshot":"true","waitForAppScript":"$.delay(1000); true;","platformName":"iOS","autoAcceptAlerts":"true"},{},{"desiredCapabilities":{"app":"","bundleId”:”myappbundsle”””deviceName":"null","platform":"MAC","webDriverAgentUrl":"http://192.168.1.23:8100","excludedDevices":"6129000567,6128001080","screenshotWaitTimeout":"5","sendKeyStrategy":"setValue","newCommandTimeout":"60","automationName":"XCUITest","browserName":"","takesScreenshot":"true","waitForAppScript":"$.delay(1000); true;","platformName":"iOS","autoAcceptAlerts":"true"},"requiredCapabilities":{}},null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: ''
[Appium]   bundleId: ‘my app’
[Appium]   deviceName: 'null'
[Appium]   platform: 'MAC'
[Appium]   webDriverAgentUrl: 'http://192.168.1.23:8100'
[Appium]   excludedDevices: '6129000567,6128001080'
[Appium]   screenshotWaitTimeout: '5'
[Appium]   sendKeyStrategy: 'setValue'
[Appium]   newCommandTimeout: '60'
[Appium]   automationName: 'XCUITest'
[Appium]   browserName: ''
[Appium]   takesScreenshot: 'true'
[Appium]   waitForAppScript: '$.delay(1000); true;'
[Appium]   platformName: 'iOS'
[Appium]   autoAcceptAlerts: 'true'
[Appium]   udid: ‘mydeviceudid’
[debug] [XCUITest] XCUITestDriver version: 2.5.3
[BaseDriver] Capability 'autoAcceptAlerts' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'newCommandTimeout' changed from string ('60') to integer (60). This may cause unexpected behavior
[BaseDriver] Capability 'screenshotWaitTimeout' changed from string ('5') to integer (5). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: platform, excludedDevices, takesScreenshot.
[XCUITest] The capabilities 'autoAcceptAlerts' and 'autoDismissAlerts' do not work for XCUITest-based tests. Please adjust your alert handling accordingly.
[BaseDriver] Session created with session id: a421c209-e65a-4c8d-904e-abbe3d85f4fa
[debug] [XCUITest] Xcode version set to '8.2.1'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [XCUITest] Available devices: mydeviceudid
[debug] [XCUITest] Creating iDevice object with udid mydeviceudid
[XCUITest] Determining device to run tests on: udid: ‘mydeviceudid’, real device: true
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/Users/myuser/git/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/myuser/git/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Using provided WebdriverAgent at 'http://192.168.1.23:8100'
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://192.168.1.23:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.mtvn.VMNPlayerSampleApp","arguments":[],"environment":{},"shouldWaitForQuiescence":true}}

**Comment by pavanbachu0604** [comment] 2017-01-17 08:49
you can give when you initiate the appium 
appium p -U UDID -p PORTNUMBER --webdriveragent-port WDALOCALPORT

**Comment by imurchie** [comment] 2017-02-01 20:20
Appium 1.6.4-beta has been released (to upgrade, run `npm uninstall -g appium && npm install -g appium@beta`). How we connect to devices has been significantly changed, and should be more reliable. Please try it out.

There is some documentation here: https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

I am closing this issue since the details will have changed completely. If you still have problems, please see if there is a similar issue, or else create a new issue with as much information as possible. We are committed to tracking down these elusive problems!

**Closed by imurchie** 2017-02-01 20:20 UTC
Labels: NeedsTriage

**Comment by jeangb** [comment] 2017-02-14 15:23
Hello @imurchie,
Since I'm starting my appium servers programmatically, do you think it's doable to add a webdriventagent -port with an AppiumDriverLocalService.buildService(new AppiumServiceBuilder()... object ?

I used to manually start my second appium server with : `appium -a 127.0.0.1 --webdriveragent-port 8080` but I'm not able to reproduce it programmatically.

**Comment by imurchie** [comment] 2017-02-14 15:30
I am not sure what a `AppiumDriverLocalService` is. Is that something from Java?

**Comment by jeangb** [comment] 2017-02-14 15:33
Yes it's from java. Actually I followed this http://www.qaautomated.com/2016/01/how-to-start-appium-server-using-java.html.

**Comment by imurchie** [comment] 2017-02-14 15:41
You should check in with the folks over at https://github.com/appium/java-client

**Comment by jeangb** [comment] 2017-02-14 15:46
Allright, thanks !

**Comment by kiran-z** [comment] 2017-10-06 15:49
@baclark774 Could you tell me how do you  build  .app package of the webdriver agent to  distribute to device. I mean the xcodebuild command. 
I am looking into a similar solution to run tests.

**Comment by ochubey** [comment] 2018-01-04 07:35
@kiran-z if still actual - you need to update and run following command from mac machine where xcode installed and appium installed globally (npm install appium -g):
`export USE_PORT=8100;lsof -i tcp:8100| grep iproxy | awk '{print $2}'| xargs kill; /usr/local/bin/iproxy 8100 8100 & xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=udid_of_the_target_phone -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=11.1.1 -xcconfig ...path/to/wdaBuild.xcconfig`

where `wdaBuild.xcconfig` is an instructions file in case you need to specify:
DEVELOPMENT_TEAM = {required field}
CODE_SIGN_IDENTITY = iPhone Developer
PRODUCT_BUNDLE_IDENTIFIER = {in case you cannot use default with specific provisioning profile}
For more information - please refer to documentation: https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

But, this would only execute WDA on specified device and proxy it to local Mac machine.
