### ISSUE TITLE
Randomly issue with iOS driver inicialization Connection was refused to port xxxxx

### ISSUE THREAD

**Issue by Sergaut** [appium/appium#13761] opened 2019-12-23 10:28 UTC
## The problem
An unknown server-side error occurred while processing the command. Original error: Connection was refused to port 51042. (Port can be any other.) Issues is related only for iOS devices. Started from executing tests on iOS13. Before Appium 13 was used with all iOS versions including 12.

## Environment
* Appium version (or git revision) that exhibits the issue:
* Version 1.15.1 (1.15.1.20191013.2)
* macOS Catalina 10.15.2
* Xcode 13.3
* Node.js version (unless using Appium.app|exe): v12.13.1
* Npm or Yarn package manager: v1.0.0
* Mobile platform/version under test: iOS 13
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:
"app" -> "/Users/user/Documents/application.app"
"automationName" -> "XCUITest"
"browserName" -> ""
"databaseEnabled" -> {Boolean@3434} false
"deviceName" -> “iPhone X"
"javascriptEnabled" -> {Boolean@3438} true
"locationContextEnabled" -> {Boolean@3434} false
"networkConnectionEnabled" -> {Boolean@3434} false
"newCommandTimeout" -> {Long@3442} 600
"noReset" -> {Boolean@3438} true
"platform" -> {Platform$7@3445} "MAC"
"platformName" -> "iOS"
"platformVersion" -> "13.3"
"takesScreenshot" -> {Boolean@3438} true
"udid" -> “Xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx”
"webStorageEnabled" -> {Boolean@3434} false

## Details
Tests failing randomly with issue in Connection was refused to port 51042(port can be any). Reproducibly only on iOS devices. Tests are executing only in 13 iOS versions, so can't say nothing about other iOS versions. Very often this issue happens after android test(s). (Tests can be executed on both platforms android and iOS platforms consistently. For each platform framework has their own settings.) Can be reproduced by starting and restarting tests several times. Have the same issue and behaviour on two others Macs.

## Link to Appium logs
https://gist.github.com/Sergaut/1fb9c7ae9047bc8c91ccdb8915646dcf
also added to Appium logs, logs from Intellij IDEA

## Code To Reproduce Issue [ Good To Have ]
fails on first line with driver inicialization.
 
all tests start from here:
@BeforeMethod
 driver = new Environment().createEnviroment(os, device, port); // FAILS HERE
        page = Page.newInstance(driver);
        adbScanner = new AdbScanner();
        androidGenerator = Generator.getInstance();
        iOSGenerator = Generator.getInstance();
        softAssert = new SoftAssert();

        driver.resetApp();

all tests end with terminating application
  @AfterMethod
driver.terminateApp("xxxxxxxxxxxxxxx");

**Comment by mykola-mokhnach** [comment] 2019-12-23 13:30
Such error usually appears when WebDriverAgent stops responding to Appium commands. I would investigate the device logs for possible error traces there. Also, the connectivity issues might be the reason

**Comment by mykola-mokhnach** [comment] 2019-12-23 13:32
Also, I would not recommend using `resetApp` call, since internally it does the same as quitting and starting the session (and sues some ugly workarounds).

**Comment by Sergaut** [comment] 2019-12-24 09:21
> Such error usually appears when WebDriverAgent stops responding to Appium commands. I would investigate the device logs for possible error traces there. Also, the connectivity issues might be the reason

Thank you for such fast response.
Here is a link to device logs:
https://gist.github.com/Sergaut/59f99f0d5b5b4fd15a8fa15dd73b349e
I've provided here Appium, report, system and install logs related to time, when issue was reproduced. If you need something else, please, let me know.

**Comment by Sergaut** [comment] 2019-12-24 09:30
> Also, I would not recommend using `resetApp` call, since internally it does the same as quitting and starting the session (and uses some ugly workarounds).

Thank you for advice. But telling the truth resetApp works fine with my tests and perfectly suits to restore application to it initial state.
Besides, it's the last lines executed in tests. And issue happens at the first line. As I've mentioned, Issue could be reproduced with relaunching tests without execution afterTest method.

Thank you once again for advice, I'll keep it in mind, that resetApp contains some ugly workarounds.

**Comment by mykola-mokhnach** [comment] 2019-12-24 09:37
> https://gist.github.com/Sergaut/59f99f0d5b5b4fd15a8fa15dd73b349e

This is the log from the device where Appium server is running and I would like to see the log from the mobile device (iPhone/iPad) itself

**Comment by Sergaut** [comment] 2019-12-24 11:57
There are no created logs on test device after issue happens. Used Xcode for this (Widnow -> Device and Simulators -> view device logs)
Used a console for getting these logs. Please, take a look.
https://gist.github.com/Sergaut/836ea2a4fbf6d860fe22c2d6e8850672

**Comment by Sergaut** [comment] 2020-01-06 13:48
@mykola-mokhnach

**Comment by mykola-mokhnach** [comment] 2020-01-06 14:00
Unfortunately the provided log does not contain any traces which could be treated as suspicious. I don't have anything more to add here

**Comment by Sergaut** [comment] 2020-01-08 12:03
> Unfortunately the provided log does not contain any traces which could be treated as suspicious. I don't have anything more to add here

Could you please, take a look at following logs (Appium and device logs)? 
https://gist.github.com/Sergaut/db2a22c222dacfea949bf781ba5f3ab3
https://gist.github.com/Sergaut/a330d22e077b568c41254121b044bace

Issue is about refusing of connection real device for wda port. After a lot of attempts to connect it will work. Usually helps to recconect device and appium restart. Then it work fine, untill the issue I've described above happens.

Issue is easily to reproduce. Need to disconnect device (or stop via intellig idea) while test and try to restart any test.

**Comment by artemryazantsev** [comment] 2020-01-24 05:58
I can confirm that issue is here, faced the same behavior with the following stack:

- Appium 1.16.0
- WDA build from Appium sources
- Real iOS devices (multiple, with iOS from 11.0 to 13.3)
It throws the mentioned errors about connection was refused to port , but then connects successfully. 
I didn't face that issue with Appium 1.15.1.

**Comment by Sergaut** [comment] 2020-01-27 11:26
> I can confirm that issue is here, faced the same behavior with the following stack:
> 
> * Appium 1.16.0
> * WDA build from Appium sources
> * Real iOS devices (multiple, with iOS from 11.0 to 13.3)
>   It throws the mentioned errors about connection was refused to port , but then connects successfully.
>   I didn't face that issue with Appium 1.15.1.

Changed MAC for more powerful. With Appium 1.15.1. and Mojave 10.14.5. Have same issue. Tried to use other workarounds methods with driver, but no success results.

**Comment by mykola-mokhnach** [comment] 2020-01-27 11:45
> As I've mentioned, Issue could be reproduced with relaunching tests without execution afterTest method.

I think such sequence of actions renders the socket to an undefined state, where it is not closed, although cannot accept new connections and is only `refreshed` after some internal timeout expires. Killing the Appium server process `might` enforce the socket refresh, since the `node` process is the original token holder, although it is not guaranteed and depends on how this logic is implemented on iDevice side (which, of course, is a private implementation and is never going to be shared by Apple 🍎 ❤️ 📱 ).

**Comment by Sergaut** [comment] 2020-02-03 10:24
> > As I've mentioned, Issue could be reproduced with relaunching tests without execution afterTest method.
> 
> I think such sequence of actions renders the socket to an undefined state, where it is not closed, although cannot accept new connections and is only `refreshed` after some internal timeout expires. Killing the Appium server process `might` enforce the socket refresh, since the `node` process is the original token holder, although it is not guaranteed and depends on how this logic is implemented on iDevice side (which, of course, is a private implementation and is never going to be shared by Apple 🍎 ❤️ 📱 ).

I'm using same devices on different mac-mini. I'm 100% sure, the more you work on the same mac - the more often issue is reproducible. On previous mac issue happened very often - on current, more rare. But, the more I work - the more I'm facing with this port issue. So, the issue depend on mac, not on iDevice.
Used Mojave and Cathalina os on macs. See no diffference.

Issue is still reproducible.

**Comment by Sergaut** [comment] 2020-02-03 10:25
> I can confirm that issue is here, faced the same behavior with the following stack:
> 
> * Appium 1.16.0
> * WDA build from Appium sources
> * Real iOS devices (multiple, with iOS from 11.0 to 13.3)
>   It throws the mentioned errors about connection was refused to port , but then connects successfully.
>   I didn't face that issue with Appium 1.15.1.

Currently using Appium 1.15.1. - same problems.

**Comment by Sergaut** [comment] 2020-02-03 10:25
Have

**Comment by artemryazantsev** [comment] 2020-02-04 20:21
Moved back to 1.15.1 and don't have this message in logs , so looks like appium issue

**Comment by lhimo** [comment] 2020-04-07 09:47
Same problem, mac mini with mojave 10.14.1 and iOS 12.4.5 (appium 1.15.1)

**Comment by Sergaut** [comment] 2020-04-07 16:35
Guys, still having this issue (appium 1.15.15, Catalina 10.15.4)
Have a small workaround for one successful test(s) launch. Uncheck "Reopen windows when logging back in" when you restart mac. It helps to have at least one launch without this error. Doesn't matter how many tests. I'm doing this before executing full scope of tests. This way it does not block me while regression.
If someone has other workaround - please provide it!

**Comment by lhimo** [comment] 2020-04-09 08:51
The problem seems to be solved by using the shell version (instead of the desktop one)

**Comment by ttwu2019** [comment] 2020-05-26 06:07
Same problem, Macbook Pro with mojave 10.14.5 and iOS 12.1.0 (appium 1.15.1)

**Comment by ttwu2019** [comment] 2020-06-01 01:44
Is there an effective solution？

**Comment by Sergaut** [comment] 2020-06-04 12:29
> Is there an effective solution？

Still have the same behavior. Restarting appium every time facing this issue.  (appium 1.15.1 / Catalina 1.15.4)

**Comment by mykola-mokhnach** [comment] 2020-11-10 08:39
Closed as third party issue

**Closed by mykola-mokhnach** 2020-11-10 08:39 UTC
Labels: ThirdParty, XCUITest
