### ISSUE TITLE
Can you update appium-windows-driver to latest?

### ISSUE THREAD

**Issue by BluewareJ** [appium/appium#17177] opened 2022-07-11 09:54 UTC
Currently the appium-windows-driver is v1.19.1, and we need the new version which supports APPIUM_WAD_PATH environment variable and latest WinAppDriver.
Of course we can change appium code, but it's better to have it built-in when install appium from npm.
Thanks.

**Comment by mykola-mokhnach** [comment] 2022-07-11 12:30
Sorry, I don't quite understand what the issue is. the most recent driver version is [2.0.6](https://github.com/appium/appium-windows-driver/commit/0dc89aa7ab467a8c6f6af40cad1c223defd48644) as of now

**Comment by BluewareJ** [comment] 2022-07-12 02:23
I mean to update the appium-windows-driver dependency in appium.

**Comment by KazuCocoa** [comment] 2022-07-12 05:22
You can get the latest with appium 2, or replace `appium-windows-driver` in node_modules in global installed appium 1 with  `appium-windows-driver` v1.

**Comment by mykola-mokhnach** [comment] 2022-07-12 05:35
Closed as not an issue

**Closed by mykola-mokhnach** 2022-07-12 05:35 UTC
Labels: NotABug

**Comment by mykola-mokhnach** [comment] 2022-07-12 05:39
> or replace appium-windows-driver in node_modules in global installed appium 1 with appium-windows-driver v1.

This would probably not work as expected because drivers have multiple dependencies to Appium2-specific libs. Appium1 is not being maintained anymore though.
