### ISSUE TITLE
Can't find alert elements

### ISSUE THREAD

**Issue by felyppers** [appium/appium#9799] opened 2017-12-14 17:30 UTC
## The problem

Recently updated my XCode to 9 (using 9.2 right now) and my test cases now can't find alert elements. Some alerts I still can find the elements, but not in every alert. In some specific cases the situation gets worse (like apple login alerts in which I'm not able to find textfields or passwordfields).

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2-beta2 (XCode 9.2)
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1 (XCode 8.3)
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.16
* Node.js version (unless using Appium.app|exe): 7.4.0
* Mobile platform/version under test: iPhone 7 iOS 10.3.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI
* Language: Ruby (appium_lib)

## Details and Code to Reproduce Issue

Alert example: [Click here](https://i.imgur.com/o1tm9O2.png)

Before opening the alert, the following code recovers every element in the screen: 
`driver.find_elements :predicate,'type!=nil'`
After opening the alert, the code above recovers only a generic element of type "XCUIElementTypeAny".

I'm able to handle button clicks in the alert using the following commands:
`driver.execute_script('mobile: alert', {'action': 'accept', 'buttonLabel': 'ENTER_BUTTON_LABEL'});`
`driver.execute_script('mobile: alert', {'action': 'dismiss'});`

I'm not able to handle inputs. The keyboard appears properly, but I can't find elements or use send_keys on the alert using the code below:
`driver.switch_to.alert.send_keys 'abc'`
When I try it, it delivers: "Selenium::WebDriver::Error::NoSuchAlertError: An attempt was made to operate on a modal dialog when one was not open."

## Link to Appium logs

Gist: [Click here](https://gist.github.com/felyppers/9d05ed21cdeb330398e5ddba0edd74b1#file-appium-log)

## Additional Info

It seems that appium-xcuitest-driver is not able to find properly the textfields in alerts ([lib/commands/alert.js - line 181](https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/alert.js)) while using send_keys, what is justified since even the find_elements method is not able to do so.

**Comment by sellmito** [comment] 2017-12-14 17:35
Same here...

**Comment by felyppers** [comment] 2017-12-19 21:10
Any news on this?

**Comment by Corji** [comment] 2017-12-21 10:08
Have the same Problem. I downgraded back to Xcode 9 and everything works find, but now im not able to automate the new ios os.

**Comment by sellmito** [comment] 2017-12-21 12:38
@Corji Did you mean you downgraded to Xcode **8** and it worked fine?

**Comment by felyppers** [comment] 2018-01-08 13:19
Noticed that other devices on the farm (iPhone 6 - iOS 10.2 for instance) allow me to interact with the native alerts normally. So I decided to remove this iPhone 7 from executing tests that handle native alerts until this gets solved. Still, any news on this are welcome.

**Comment by jstumpges** [comment] 2018-01-11 20:45
Any updates on this? 

Same issue here after upgrading to Xcode 9 and using an iPhone 7 OS 10.0.2.  Also tried an older iPhone 6 OS 9.3.5 and same thing. 
iOS 11 appears to work fine as far as interacting with native alerts, or at least for an iPhone 7 OS 11.2..

**Comment by fspinillo** [comment] 2018-01-19 15:50
This was happening to me and I believe it's specific to version 1.7.2 of Appium. When I downgraded back to 1.7.1 it was able to properly handle alerts. This happened regardless of using XCUITest

I believe the problem is it's detecting the alert before the dialog is present and thus failing. If I debug my way through my code it will properly work, but it's because I'm waiting at each step. The moment it runs at full speeds it will fail.

I would recommend going back to 1.7.1 and seeing what happens.

**Comment by spartanglady** [comment] 2018-01-24 06:46
Yeah.. Reverting back to 1.7.1 fixes this issue for now

**Comment by jstumpges** [comment] 2018-01-24 18:15
@spartanglady What version of xcuitest-driver were you using? I downgraded back to Appium v1.7.1 with XCUITestDriver (v2.51.1) and my test still started failing after accepting the alert. 

I changed the implementation a bit going from accepting the native alert by finding the "Allow" button via an accessibility id, to using the built in driver's method (driver.switchTo().alert().accept()). This successfully accepted the alert, however immediately after if failed to find the the next element. In this case the next element is another native prompt - depending on the state the app is in, it may prompt the user again. In this case, the prompt did not show, and so the proxy server responded with 
`[HTTP] <-- GET /wd/hub/session/53e86074-bedb-483a-99b9-2399dc4ef8ae/alert_text 500 463 ms - 87`  

The weird thing is that even if I remove the code that checks for a second native prompt, it still won't find the next element that is clearly showing and visible (confirmed with Appium Inspector) immediately after the first prompt is dismissed. It's as if the page source isn't refreshed immediately after dismissing the prompt. 

Here's a [gist](https://gist.github.com/jstumpges/20da8820207b04a2b47d5da732229806) of the logs after a run. Another weird behavior I noticed from the logs is that the appium driver starts attempting to find elements multiple times regardless of whether the element is showing (200 response) or not (500 response), and it continues to try and find the next elements even though it didn't successfully tap on the previous one. And I've noticed this behavior only starts to occur after the first 500 response.. 

@mykola-mokhnach  or anyone else with a similar problem - any help/insight would be awesome!

**Comment by spartanglady** [comment] 2018-01-24 20:57
I Didn't find any issue with finding the next web element. I just downgraded to 1.7.1 using npm. Didn't get to cherry pick any specific version of xcuitest-driver.

**Comment by felyppers** [comment] 2018-04-02 16:35
No news yet?

**Comment by mykola-mokhnach** [comment] 2018-04-30 14:56
Closed as third party issue

**Closed by mykola-mokhnach** 2018-04-30 14:56 UTC
Labels: Bug, XCUITest

**Comment by felyppers** [comment] 2018-05-01 17:10
Hey @mykola-mokhnach, what exactly third-party is it? Is it WebDriverAgent where I should address this problem? I'm asking because I am still facing this issue =/

**Comment by mykola-mokhnach** [comment] 2018-05-01 17:37
Yes this this either XCTest or WebDriverAgent issue. There is nothing one can do on Appium side to change this behaviour
