### ISSUE TITLE
bug: On ios17, safari's native mode driver.PageSource   will time out 

### ISSUE THREAD

**Issue by haydenren** [appium/appium#19304] opened 2023-10-16 09:13 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

appium version: 2.1.3
xcuitest version: 5.7.0
ios version: 17.0   simulator
xcode: 15.0

i test app on safari, when i change driver to native mode ,i can't get pageSource
 var page = driver.PageSource;

error : The request was canceled due to the configured HttpClient.Timeout of 180 seconds elapsing.
 
when i  change  ios  to 16.2  ， it will be ok.

### Expected Behavior

driver.PageSource   return the pagesource.

### Minimal Reproducible Example

 var page = driver.PageSource;

### Environment

- Operating system: mac mini
- Appium server version (output of `appium --version`):2.1.3
- Appium driver(s) and their version(s):xcuitest   5.7
- Appium plugin(s) and their version(s):no
- Node.js version (output of `node --version`):v20.8.0
- `npm` version (output of `npm --version`):10.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: ios 17.0
- Real device or emulator/simulator: simulator

**Comment by mykola-mokhnach** [comment] 2023-10-16 09:21
Possible duplicate of https://github.com/appium/appium/issues/19297

**Comment by haydenren** [comment] 2023-10-18 09:18
I tested on an ipad 17.1 real device with no issues, so the issue seems to be related to the simulator

**Comment by mykola-mokhnach** [comment] 2023-10-18 09:31
Page source retrieval is not something we can control much and we cannot do anything if xctest either cannot fetch it or takes too long.

**Comment by mykola-mokhnach** [comment] 2023-10-24 16:19
Closed as third party issue

**Closed by mykola-mokhnach** 2023-10-24 16:19 UTC
Labels: ThirdParty, XCUITest, Needs Info
