### ISSUE TITLE
Error: Plist file doesn't exist after upgraded Appium 1.10.0

### ISSUE THREAD

**Issue by romainlouvet** [appium/appium#11754] opened 2018-11-28 08:58 UTC
## The problem

After upgraded Appium from 1.9.1 to 1.10.0
All steps for configure my real device is good (http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/).
When I try to launch my first test, Could not extract Info.plist from application: Plist file doesn't exist: '/var/folders/lr/vw_cp71916j7gww1sf66p1500000gn/T/20181028-20605-w44spe.c1vm8/appium-app.app/Info.plist'

## Environment

* Appium version : 1.10.0
* Java-client version : 6.1.0
* Desktop OS/version used to run Appium: Mac 10.13.6
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Link to Appium logs

https://gist.github.com/romainlouvet/425593a3557e7b31426d3d8a99e5a321

**Comment by mykola-mokhnach** [comment] 2018-11-28 09:04
Does the application include Info.plist file if you extract the ipa package manually? Is the .app package in temp file equal to the one that is extracted manually?

**Comment by lin907597898** [comment] 2018-11-28 10:30
I had same question

**Comment by lin907597898** [comment] 2018-11-28 10:38
I encounter the same issue.
My Appium version is 1.10.0
node version is v11.2.0
I have checked the package includes info .plist 

log:
Support] Error: Plist file doesn't exist: '/var/folders/bp/13f56cd10tdf_r3t1x7_9rwjfr4drm/T/20181028-45195-qe62m9.ym8to/appium-app.app/Info.plist'
[Support]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[Support]     at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/plist.js:22:11)
[Support]     at Generator.next (<anonymous>)
[Support]     at asyncGeneratorStep (/usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[Support]     at _next (/usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[iOS] Error: Could not extract Info.plist from application: Plist file doesn't exist: '/var/folders/bp/13f56cd10tdf_r3t1x7_9rwjfr4drm/T/20181028-45195-qe62m9.ym8to/appium-app.app/Info.plist'

**Comment by mykola-mokhnach** [comment] 2018-11-30 09:04
Please provide answers to the question above. Otherwise the issue is going to be closed due to missing information

**Comment by romainlouvet** [comment] 2018-11-30 10:02
If I unzip appium-app.app I have Payload directory with my Leboncoin.app

**Comment by mykola-mokhnach** [comment] 2018-11-30 11:20
Sorry, but this does not answer the question above

**Comment by romainlouvet** [comment] 2018-11-30 11:54
@mykola-mokhnach How to extract the ipa package manually ?

**Comment by mykola-mokhnach** [comment] 2018-11-30 11:56
it is a normal zip archive. Simply rename it

**Comment by romainlouvet** [comment] 2018-11-30 12:08
ok if 
I rename /var/folders/lr/vw_cp71916j7gww1sf66p1500000gn/T/20181028-20605-w44spe.c1vm8/appium-app.app to /tmp/appium.zip 
unzip /tmp/appium.zip -> no Info.plist

**Comment by mykola-mokhnach** [comment] 2018-11-30 12:18
Ieman you should download and unzip the original ipa file and check if there is this Plist there

**Comment by romainlouvet** [comment] 2018-11-30 13:23
@mykola-mokhnach where is the original ipa ?

**Comment by CAPie** [comment] 2018-11-30 15:56
the same issue =(

**Comment by mykola-mokhnach** [comment] 2018-11-30 16:00
@lin907597898 @CAPie Your +1 does not help to address the issue a bit. Please provide the necessary information, which can help to resolve the problem. 

The code responsible for downloading and unpacking the app can be found at https://github.com/appium/appium-base-driver/blob/f86b4c5685f90f314dc2a71369a061a1cf23ba70/lib/basedriver/helpers.js#L62

**Comment by mykola-mokhnach** [comment] 2018-11-30 16:19
I would say for now the issue could be fixed by setting the proper value to Content-Disposition or Content-Type server response headers. I've created a PR to also consider the URL extension: https://github.com/appium/appium-base-driver/pull/288

**Comment by mykola-mokhnach** [comment] 2018-11-30 17:19
Published the PR to appium@beta

**Closed by mykola-mokhnach** 2018-11-30 17:19 UTC
Labels: Enhancement
