### ISSUE TITLE
Appium server don't throws StaleElementReferenceException

### ISSUE THREAD

**Issue by HlebHalkouski** [appium/appium#10646] opened 2018-05-04 13:19 UTC
## The problem

When I'm trying to get size or location to already not existing element Appium don't throws 'org.openqa.selenium.StaleElementReferenceException'. It's just not responding: 
`2018-05-04 13:00:25:115 - [HTTP] <-- GET /wd/hub/session/ef5c88e0-e095-44c7-9021-8300fa45237e/element/6d08283e-f1b5-4382-835c-0e6278560bbc/size - - ms - -
2018-05-04 13:00:25:116 - [HTTP] `

## Environment

* Appium version (or git revision) that exhibits the issue:  1.8.0
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: macOS High Sierra
* Node.js version (unless using Appium.app|exe): v7.9.0
* Mobile platform/version under test: android 7.0
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: cli
* Automation name: uiautomator2

## Link to Appium logs

[appium 1.8.0](https://gist.github.com/HlebHalkouski/2d968eae4e3cf7cf1c08d01b048b7007)

**Comment by mykola-mokhnach** [comment] 2018-05-04 20:38
Can you also attach logcat output?

**Comment by HlebHalkouski** [comment] 2018-05-07 05:57
[log.log](https://github.com/appium/appium/files/1978611/log.log)

**Comment by mykola-mokhnach** [comment] 2018-05-07 07:17
I see the response has been sent properly on the server side, so it is rather device or network issue

**Comment by HlebHalkouski** [comment] 2018-05-07 07:31
I have the same issue with another device ( Samsung Tab A 6.0.1 ). 
And all good using appium@1.7.2

**Comment by mykola-mokhnach** [comment] 2018-05-18 14:54
@vmaxim any ideas on this?

**Comment by mykola-mokhnach** [comment] 2018-05-19 19:32
Duplicate of https://github.com/appium/appium/issues/10703

**Closed by mykola-mokhnach** 2018-05-19 19:32 UTC
Labels: ThirdParty, UIAutomator2

**Comment by HlebHalkouski** [comment] 2018-05-29 06:11
appium@v1.8.1 - fixed
