### ISSUE TITLE
Support multiple (Android) devices from a single Appium server with Robot Framework

### ISSUE THREAD

**Issue by nan2806** [appium/appium#5236] opened 2015-06-10 08:30 UTC
Can I run multiple devices from a single Appium server with one test script Robot Framework ?

**Comment by sebv** [comment] 2015-06-11 03:03
Doc is here, http://appium.io please look for robot.
Check https://discuss.appium.io/ there are threads about multiple devices.

Closing, not a bug.

**Closed by sebv** 2015-06-11 03:03 UTC
Labels: NeedsTriage
