### ISSUE TITLE
[HTTP] <-- POST /wd/hub/session 500 3398 ms - 4054

### ISSUE THREAD

**Issue by LearningIsEndless** [appium/appium#13301] opened 2019-09-26 18:29 UTC
## The problem

I am using Appium first time and trying to invoke Chrome browser on my Real device. Got below error on Appium Server
## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Window 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Redmi 7
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Link to Appium logs

The server is running
```
[Appium] Welcome to Appium v1.13.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"automationName":"Appium","browserName":"Chrome","clearSystemFiles":true,"platformName":"Android","deviceName":"Android"},"capabilities":{"firstMatch":[{"appium:automationName":"Appium","browserName":"Chrome","appium:clearSystemFiles":true,"appium:deviceName":"Android","platformName":"android"}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"automationName":"Appium","browserName":"Chrome","clearSystemFiles":true,"platformName":"Android","deviceName":"Android"},null,{"firstMatch":[{"appium:automationName":"Appium","browserName":"Chrome","appium:clearSystemFiles":true,"appium:deviceName":"Android","platformName":"android"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1569520640672 (23:27:20 GMT+0530 (India Standard Time))
[Appium] 
[Appium] ======================================================================
[Appium]   DEPRECATION WARNING:
[Appium] 
[Appium]   The 'automationName' capability was not provided in the desired 
[Appium]   capabilities for this Android session
[Appium] 
[Appium]   Setting 'automationName=UiAutomator1' by default and using the 
[Appium]   UiAutomator1 Driver
[Appium] 
[Appium]   The next minor version of Appium (1.14.x) will set 
[Appium]   'automationName=UiAutomator2' by default and use the UiAutomator2 
[Appium]   Driver
[Appium] 
[Appium]   The next major version of Appium (2.x) will **require** the 
[Appium]   'automationName' capability to be set for all sessions on all 
[Appium]   platforms
[Appium] 
[Appium]   If you are happy with 'UiAutomator1' and do not wish to upgrade 
[Appium]   Android drivers, please add 'automationName=UiAutomator1' to your 
[Appium]   desired capabilities
[Appium] 
[Appium]   For more information about drivers, please visit 
[Appium]   http://appium.io/docs/en/about-appium/intro/ and explore the 
[Appium]   'Drivers' menu
[Appium] 
[Appium] ======================================================================
[Appium] 
[Appium] Setting automation to 'UiAutomator1'. 
[Appium] Appium v1.13.0 creating new AndroidDriver (v4.15.1) session
[Appium] Capabilities:
[Appium]   browserName: Chrome
[Appium]   platformName: android
[Appium]   automationName: Appium
[Appium]   clearSystemFiles: true
[Appium]   deviceName: Android
[BaseDriver] W3C capabilities {"alwaysMatch":{"browserNam... and MJSONWP desired capabilities {"automationName":"Appium",... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"browserNam...
[BaseDriver] Session created with session id: ef025d53-4c74-4c63-83f1-f4979cde7b48
[AndroidDriver] We're going to run a Chrome-based session
[AndroidDriver] Chrome-type package and activity are com.android.chrome and com.google.android.apps.chrome.Main
[ADB] Found 1 'build-tools' folders under 'C:\Users\warrior\AppData\Local\Android\Sdk' (newest first):
[ADB]     C:/Users/warrior/AppData/Local/Android/Sdk/build-tools/29.0.2
[ADB] Using 'adb.exe' from 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: cfbdc619
[ADB] Using 'adb.exe' from 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[ADB] Setting device id to cfbdc619
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 28
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 9
[ADB] Device API level: 28
[AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[AndroidDriver] App file was not listed, instead we're going to run com.android.chrome directly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell pm list packages com.android.chrome'
[AndroidDriver] Starting Android session
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 wait-for-device'
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is not installed
[ADB] App 'C:\Users\warrior\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk' is not installed
[ADB] Installing 'C:\Users\warrior\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell 'ls -t -1 /data/local/tmp/appium_cache 2>&1 || echo _ERROR_''
[ADB] The count of applications in the cache: 1
[ADB] The application at 'C:\Users\warrior\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk' is already cached to '/data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk'
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell pm install -g /data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk'
[ADB] Getting install status for io.appium.settings
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is not installed
[ADB] App 'C:\Users\warrior\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk' is not installed
[ADB] Installing 'C:\Users\warrior\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell 'ls -t -1 /data/local/tmp/appium_cache 2>&1 || echo _ERROR_''
[ADB] The count of applications in the cache: 1
[ADB] The application at 'C:\Users\warrior\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk' is already cached to '/data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk'
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell pm install -g /data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk'
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell am force-stop io.appium.unlock'
[AndroidDriver] App was not copied, so not deleting
[BaseDriver] Event 'newSessionStarted' logged at 1569520643627 (23:27:23 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'C\:\\Users\\warrior\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s cfbdc619 shell pm install -g /data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk' exited with code 255'; Stderr: 'Security exception: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
[W3C] 
[W3C] java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
[W3C] 	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:457)
[W3C] 	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:416)
[W3C] 	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:2418)
[W3C] 	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:907)
[W3C] 	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:158)
[W3C] 	at android.os.ShellCommand.exec(ShellCommand.java:103)
[W3C] 	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21851)
[W3C] 	at android.os.Binder.shellCommand(Binder.java:634)
[W3C] 	at android.os.Binder.onTransact(Binder.java:532)
[W3C] 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2809)
[W3C] 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4008)
[W3C] 	at android.os.Binder.execTransact(Binder.java:733)'; Code: '255'
[W3C] Error: Command 'C\:\\Users\\warrior\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s cfbdc619 shell pm install -g /data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk' exited with code 255
[W3C]     at ChildProcess.proc.on.code (C:\Users\warrior\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\teen_process\lib\exec.js:94:19)
[W3C]     at ChildProcess.emit (events.js:182:13)
[W3C]     at maybeClose (internal/child_process.js:961:16)
[W3C]     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[HTTP] <-- POST /wd/hub/session 500 3071 ms - 4054
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"automationName":"Appium","browserName":"Chrome","clearSystemFiles":true,"platformName":"Android","deviceName":"Android"},"capabilities":{"firstMatch":[{"appium:automationName":"Appium","browserName":"Chrome","appium:clearSystemFiles":true,"appium:deviceName":"Android","platformName":"android"}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"automationName":"Appium","browserName":"Chrome","clearSystemFiles":true,"platformName":"Android","deviceName":"Android"},null,{"firstMatch":[{"appium:automationName":"Appium","browserName":"Chrome","appium:clearSystemFiles":true,"appium:deviceName":"Android","platformName":"android"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1569521718074 (23:45:18 GMT+0530 (India Standard Time))
[Appium] 
[Appium] ======================================================================
[Appium]   DEPRECATION WARNING:
[Appium] 
[Appium]   The 'automationName' capability was not provided in the desired 
[Appium]   capabilities for this Android session
[Appium] 
[Appium]   Setting 'automationName=UiAutomator1' by default and using the 
[Appium]   UiAutomator1 Driver
[Appium] 
[Appium]   The next minor version of Appium (1.14.x) will set 
[Appium]   'automationName=UiAutomator2' by default and use the UiAutomator2 
[Appium]   Driver
[Appium] 
[Appium]   The next major version of Appium (2.x) will **require** the 
[Appium]   'automationName' capability to be set for all sessions on all 
[Appium]   platforms
[Appium] 
[Appium]   If you are happy with 'UiAutomator1' and do not wish to upgrade 
[Appium]   Android drivers, please add 'automationName=UiAutomator1' to your 
[Appium]   desired capabilities
[Appium] 
[Appium]   For more information about drivers, please visit 
[Appium]   http://appium.io/docs/en/about-appium/intro/ and explore the 
[Appium]   'Drivers' menu
[Appium] 
[Appium] ======================================================================
[Appium] 
[Appium] Setting automation to 'UiAutomator1'. 
[Appium] Appium v1.13.0 creating new AndroidDriver (v4.15.1) session
[Appium] Capabilities:
[Appium]   browserName: Chrome
[Appium]   platformName: android
[Appium]   automationName: Appium
[Appium]   clearSystemFiles: true
[Appium]   deviceName: Android
[BaseDriver] W3C capabilities {"alwaysMatch":{"browserNam... and MJSONWP desired capabilities {"automationName":"Appium",... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"browserNam...
[BaseDriver] Session created with session id: 794022a7-5b2f-467b-bd29-1c4a9ce1c31f
[AndroidDriver] We're going to run a Chrome-based session
[AndroidDriver] Chrome-type package and activity are com.android.chrome and com.google.android.apps.chrome.Main
[ADB] Using 'adb.exe' from 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: cfbdc619
[ADB] Using 'adb.exe' from 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[ADB] Setting device id to cfbdc619
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 28
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 9
[ADB] Device API level: 28
[AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[AndroidDriver] App file was not listed, instead we're going to run com.android.chrome directly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell pm list packages com.android.chrome'
[AndroidDriver] Starting Android session
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 wait-for-device'
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is not installed
[ADB] App 'C:\Users\warrior\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk' is not installed
[ADB] Installing 'C:\Users\warrior\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell 'ls -t -1 /data/local/tmp/appium_cache 2>&1 || echo _ERROR_''
[ADB] The count of applications in the cache: 1
[ADB] The application at 'C:\Users\warrior\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk' is already cached to '/data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk'
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell pm install -g /data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk'
[ADB] Getting install status for io.appium.settings
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is not installed
[ADB] App 'C:\Users\warrior\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk' is not installed
[ADB] Installing 'C:\Users\warrior\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell 'ls -t -1 /data/local/tmp/appium_cache 2>&1 || echo _ERROR_''
[ADB] The count of applications in the cache: 1
[ADB] The application at 'C:\Users\warrior\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk' is already cached to '/data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk'
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell pm install -g /data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk'
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[ADB] Running 'C:\Users\warrior\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s cfbdc619 shell am force-stop io.appium.unlock'
[AndroidDriver] App was not copied, so not deleting
[BaseDriver] Event 'newSessionStarted' logged at 1569521721462 (23:45:21 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'C\:\\Users\\warrior\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s cfbdc619 shell pm install -g /data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk' exited with code 255'; Stderr: 'Security exception: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
[W3C] 
[W3C] java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
[W3C] 	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:457)
[W3C] 	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:416)
[W3C] 	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:2418)
[W3C] 	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:907)
[W3C] 	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:158)
[W3C] 	at android.os.ShellCommand.exec(ShellCommand.java:103)
[W3C] 	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21851)
[W3C] 	at android.os.Binder.shellCommand(Binder.java:634)
[W3C] 	at android.os.Binder.onTransact(Binder.java:532)
[W3C] 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2809)
[W3C] 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4008)
[W3C] 	at android.os.Binder.execTransact(Binder.java:733)'; Code: '255'
[W3C] Error: Command 'C\:\\Users\\warrior\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s cfbdc619 shell pm install -g /data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk' exited with code 255
[W3C]     at ChildProcess.proc.on.code (C:\Users\warrior\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\teen_process\lib\exec.js:94:19)
[W3C]     at ChildProcess.emit (events.js:182:13)
[W3C]     at maybeClose (internal/child_process.js:961:16)
[W3C]     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[HTTP] <-- POST /wd/hub/session 500 3398 ms - 4054
[HTTP] 
```
Please suggest the steps to correct this issue

**Comment by imurchie** [comment] 2019-09-26 18:32
Does the suggestion in the error not work?
```
You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
```

**Comment by mykola-mokhnach** [comment] 2019-09-26 18:44
Simply get a mobile phone, which property supports adb protocol. I saw some phone models (usually chinese ones) that simply block several adb features (like for example this one blocks permissions granting on app install) that are vital for automation.

**Comment by mykola-mokhnach** [comment] 2019-09-27 19:09
Closed as not a bug

**Closed by mykola-mokhnach** 2019-09-27 19:09 UTC
Labels: NotABug, ThirdParty

**Comment by LearningIsEndless** [comment] 2019-09-30 06:32
Thank you so much for the updates!

**Comment by Lakshmanan4233** [comment] 2022-07-04 05:10
This time it is working. Thank for your response
