### ISSUE TITLE
all elements of some pages are not identifiable  in iOS app in appium

### ISSUE THREAD

**Issue by nibedita-selenium** [appium/appium#14769] opened 2020-09-30 09:19 UTC
## Specific pages of iOS app(with lot of elements ) are not identifiable through appium , automation failing specific to that page of iOS app

I run appium test in both android and iOS app. in iOS app some pages contain lot many elements. when my test comes to that page it does not identify any element and navigating from that page to other page not possible. As there is no element identifies on those page.

## Environment

* Appium version (or git revision) that exhibits the issue: appium 1.18.2

* Desktop OS/version used to run Appium: MAC OS catalina
* Npm : 6.9.0
* Mobile platform/version under test: iOS 13 and 14 
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment] 2020-09-30 09:31
Duplicate of https://github.com/appium/appium/issues/13864

**Closed by mykola-mokhnach** 2020-09-30 09:31 UTC
