### ISSUE TITLE
Appium-uiautomator2-driver cannot recognize full screen

### ISSUE THREAD

**Issue by Comeodore** [appium/appium#18364] opened 2023-03-19 11:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Driver cannot recognize full screen on real device AOS (any versions of AOS, any models, any 
manufacturer)

<img width="807" alt="image" src="https://user-images.githubusercontent.com/55732318/226172459-4cb420bb-aed3-4484-b283-be4c38195a3e.png">

<img width="788" alt="image" src="https://user-images.githubusercontent.com/55732318/226172513-010ff0e2-752b-4943-85da-299f2ff79f85.png">

![image](https://user-images.githubusercontent.com/55732318/226172718-31a457fe-439c-4c0a-8bfa-b09a87b5ac19.png)

![image](https://user-images.githubusercontent.com/55732318/226172750-a931bb26-987d-4b24-a2eb-f2e9ab94d569.png)

![image](https://user-images.githubusercontent.com/55732318/226172755-63afa273-db25-438c-bb49-45d055fe65f7.png)

Without system navigation bar

![image](https://user-images.githubusercontent.com/55732318/226172483-6b248221-66d2-4dd9-8d9d-0bfb6b59e83d.png)

### Expected Behavior

Full screen recognized

### Minimal Reproducible Example

npm install appium@next -g
appium driver install uiautomator2
install latest version of appium inspector
run appium
run appium inspector with capabilities:

{
  "platformName": "Android",
  "appium:automationName": "UiAutomator2",
  "appium:deviceName": "udid"
}

### Environment

- Operating system: Mac OS Ventura 13.2.1
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.57
  - Node.js version (output of `node --version`): v19.5.0
  - `npm` version (output of `npm --version`):  9.3.1
  - Last `appium` version which did _not_ exhibit the problem: -
- Appium driver(s) and their version(s): uiautomator2@2.12.6
- Platform and version under test: Android any version
- Real device or emulator/simulator: real device

### Link to Appium Logs

https://gist.github.com/Comeodore/0b4b8191bedd3bd99efb7355ce90f651

**Comment by mykola-mokhnach** [comment] 2023-03-19 12:38
Unfortunately this data is coming from Google's UiAutomator and we cannot influence it.
I saw Google has released a new version of their framework, but it is still in alpha, so we cannot incorporate it.

Closed as third party issue

**Closed by mykola-mokhnach** 2023-03-19 12:38 UTC
Labels: ThirdParty, UIAutomator2

**Comment by Comeodore** [comment] 2023-03-19 16:10
@mykola-mokhnach What driver would you recommend to use that doesn't have this problem and is easy to use like this one?

**Comment by mykola-mokhnach** [comment] 2023-03-19 16:37
you could try to create a custom build of https://github.com/appium/appium-uiautomator2-server with uiautomator updated to the latest alpha and see if the problem is addressed there. Otherwise I don't have any good suggestions.
