### ISSUE TITLE
Appium does not use the device to execute the script after deviceName is specified

### ISSUE THREAD

**Issue by geekmister** [appium/appium#15773] opened 2021-08-23 02:56 UTC
## The problem

Connect to multiple Android devices simultaneously, appium does not use the device to execute the script after deviceName is specified. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): no
* Desktop OS/version used to run Appium: 1.20.2
* Node.js version (unless using Appium.app|exe): 14.16.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: I don't understand how to fill in this item

## Details

Follow my test steps and repeat:

1、Link the three devices to the PC;
2、There are two Android 9 devices and an Android 8 device:

- the first device: (deviceName: CSX0217916005829; paltform: Android 9);
- the sencond device: (deviceName: WTKDU17110000758; paltform: Android 8);
- the third device: (deivceName: AY85SC4PPN8LTSQK; platform: Android 9);

3、DeviceName: AY85SC4PPN8LTSQK is the target device I want to test；
4、I started to execute the test scripts, and eventually I found that the Appium Server always uses deviceName: CSX0217916005829 for testing;
5、I found from the log that Appium Server gets the device list first，see:
`[debug] [35m[ADB][39m Connected devices: [{"udid":"CSX0217916005829","state":"device"},{"udid":"WTKDU17110000758","state":"device"},{"udid":"AY85SC4PPN8LTSQK","state":"device"}]`
6、Appium Server will then give the platform version according to desiredCapabilities. From the obtained device list, it will determine whether the platform version of the device is consistent in sequence. If the device is consistent, it will use this device

desiredCapabilities:
`
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {
[debug] [35m[BaseDriver][39m   "appActivity": "com.cmi.jegotrip.ui.LauncherActivity",
[debug] [35m[BaseDriver][39m   "appPackage": "com.cmi.jegotrip",
[debug] [35m[BaseDriver][39m   "automationName": "UiAutomator2",
[debug] [35m[BaseDriver][39m   "deviceName": "AY85SC4PPN8LTSQK",
[debug] [35m[BaseDriver][39m   "ensureWebviewsHavePages": true,
[debug] [35m[BaseDriver][39m   "noReset": true,
[debug] [35m[BaseDriver][39m   "platformName": "Android",
[debug] [35m[BaseDriver][39m   "platformVersion": "9",
[debug] [35m[BaseDriver][39m   "newCommandTimeout": 0,
[debug] [35m[BaseDriver][39m   "connectHardwareKeyboard": true
[debug] [35m[BaseDriver][39m }
`
7、This judgment logic of Appium Server is incorrect. As a result, when devices with the same PaltForm version are connected at the same time, only the first device can be used forever

## Link to Appium logs

`
[info] [35m[HTTP][39m Waiting until the server is closed
[info] [35m[HTTP][39m Received server close event
[info] [35m[Appium][39m Welcome to Appium v1.20.2
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   relaxedSecurityEnabled: true
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"appActivity":"com.cmi.jegotrip.ui.LauncherActivity","appPackage":"com.cmi.jegotrip","automationName":"UiAutomator2","deviceName":"AY85SC4PPN8LTSQK","ensureWebviewsHavePages":true,"noReset":true,"platformName":"Android","platformVersion":"9","newCommandTimeout":0,"connectHardwareKeyboard":true}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"appActivity":"com.cmi.jegotrip.ui.LauncherActivity","appPackage":"com.cmi.jegotrip","automationName":"UiAutomator2","deviceName":"AY85SC4PPN8LTSQK","ensureWebviewsHavePages":true,"noReset":true,"platformName":"Android","platformVersion":"9","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1629448229685 (16:30:29 GMT+0800 (中国标准时间))
[info] [35m[Appium][39m Appium v1.20.2 creating new AndroidUiautomator2Driver (v1.61.2) session
[info] [35m[Appium][39m Applying relaxed security to 'AndroidUiautomator2Driver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {
[debug] [35m[BaseDriver][39m   "appActivity": "com.cmi.jegotrip.ui.LauncherActivity",
[debug] [35m[BaseDriver][39m   "appPackage": "com.cmi.jegotrip",
[debug] [35m[BaseDriver][39m   "automationName": "UiAutomator2",
[debug] [35m[BaseDriver][39m   "deviceName": "AY85SC4PPN8LTSQK",
[debug] [35m[BaseDriver][39m   "ensureWebviewsHavePages": true,
[debug] [35m[BaseDriver][39m   "noReset": true,
[debug] [35m[BaseDriver][39m   "platformName": "Android",
[debug] [35m[BaseDriver][39m   "platformVersion": "9",
[debug] [35m[BaseDriver][39m   "newCommandTimeout": 0,
[debug] [35m[BaseDriver][39m   "connectHardwareKeyboard": true
[debug] [35m[BaseDriver][39m }
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
[warn] [35m[BaseDriver][39m   connectHardwareKeyboard
[info] [35m[BaseDriver][39m Session created with session id: cb27658d-d1cc-405e-83dc-7b238cdf0578
[info] [35m[UiAutomator2][39m Starting 'com.cmi.jegotrip' directly on the device
[info] [35m[ADB][39m Using 'adb' from '/Users/itadmin/sdk/android-sdk-macosx/platform-tools/adb'
[debug] [35m[ADB][39m Running '/Users/itadmin/sdk/android-sdk-macosx/platform-tools/adb -P 5037 start-server'
[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices
[debug] [35m[ADB][39m Connected devices: [{"udid":"CSX0217916005829","state":"device"},{"udid":"WTKDU17110000758","state":"device"},{"udid":"AY85SC4PPN8LTSQK","state":"device"}]
[info] [35m[AndroidDriver][39m Looking for a device with Android '9.0.0'
[debug] [35m[ADB][39m Setting device id to CSX0217916005829
[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running '/Users/itadmin/sdk/android-sdk-macosx/platform-tools/adb -P 5037 -s CSX0217916005829 shell getprop ro.build.version.release'
[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 9
[info] [35m[AndroidDriver][39m Using device: CSX0217916005829

`

**Comment by KazuCocoa** [comment] 2021-08-23 04:16
Please consider to use `udid` in real devices.

https://github.com/appium/appium-uiautomator2-driver#general

> The name of the device under test (actually, it is not used to select a device under test). Consider setting udid for real devices and avd for emulators instead

**Comment by mykola-mokhnach** [comment] 2021-08-23 13:07
Appium server does not do any assumptions about device usage. This is expected to be done on the client side. Please provide a corresponding device id in capabilities to select appropriate device. 
Closed as duplicate of https://github.com/appium/appium/issues/10383

**Closed by mykola-mokhnach** 2021-08-23 13:07 UTC
Labels: NotABug
