### ISSUE TITLE
[iOS 10/Xcode8] Cannot run multi sessions test with appium 1.6.0

### ISSUE THREAD

**Issue by nghiadhd** [appium/appium#7012] opened 2016-10-13 14:37 UTC
## The problem

I tried to run a test with multi sessions but only one session passed, others failed
## Environment
- Appium version that exhibits the issue: 1.6.0
- Last Appium version that did not exhibit the issue: Appium 1.6.0-beta2
- Desktop OS/version used to run Appium: 10.12 (Sierra) & 10.11.6 (El capitan)
- Node.js version: v6.8.0
- Mobile platform/version under test: iOS/10.0.2
- Real device or emulator/simulator: Real device/iPhone 5c
## Details
- Start Appium with cmd:
  `node build/lib/main.js --command-timeout "7200" --debug-log-spacing --default-capabilities '{"platformName":"iOS", "automationName": "XCUITest", "xcodeConfigFile": "/Users/nghiadang/Projects/appium-1.6.0/ios-xcuitest.xcconfig"}' --webkit-debug-proxy-port 27753`
- Start iOS-webkit-debug-proxy:
  `ios_webkit_debug_proxy -c 9f8e08a6bef33f3c5e8e14fb005a075070a4dd6c:27753 -d`
- Run test
- Expected behavior: 10/10 tests passed
- Actual behavior: 1/10 tests passed
## Link to Appium logs

https://gist.github.com/nghiadhd/818abdfa9a1d420b171adde3cef6054d
## Code To Reproduce Issue

https://gist.github.com/nghiadhd/a4038a5d163f56516a817fe668a33696#file-run-loop

**Comment by saikrishna321** [comment] 2016-10-14 13:35
@nghiadhd can please send wdaLocalPort capability with different port, iproxy runs on 8100 by default, which could b the reason for it hang. @imurchie can give correct info

**Comment by pavanbachu0604** [comment] 2016-10-14 19:04
@nghiadhd : Hey if you want to change the wda localport you can use "wdaLocalPort" as capability and try giving the grid port :"4444",

**Comment by nghiadhd** [comment] 2016-10-15 03:59
@saikrishna321 

I did it but result is same. 
I assigned a port (11001) to wdaLocalPort, in the first session, it work ok but the next session, with the same port, I got exception. While I expect this port should be released for next session (we don't have enough port for 10xxxx session)
Seem `iproxy` doesn't release the socket when it's be killed. 

You can use my sample to reproduce. Weird that I can passed this test with appium1.6.0-beta2.

PS: I installed libimobiledevice --HEAD (libimobiledevice 1.2.0 got lockdown issue)
`brew install libimobiledevice --HEAD`

**Comment by saikrishna321** [comment] 2016-10-15 04:08
@nghiadhd for lockdown issue pls try this approach which helped me 

```
brew uninstall ideviceinstaller
brew uninstall libimobiledevice
brew install --HEAD libimobiledevice
brew link --overwrite libimobiledevice
brew install ideviceinstaller
brew link --overwrite ideviceinstaller
```

for iProxy issues i don't have two devices right now, will give it a try soon.

**Comment by aluedeke** [comment] 2016-10-16 10:36
i am pretty sure that the killall xcodebuild command is the cause for that problem.

https://github.com/appium/appium-xcuitest-driver/blob/962b4dae13daff3896a881a656c1e4a325225b0c/lib/webdriveragent.js#L70

**Comment by PedroUSA** [comment] 2016-10-17 20:26
I have the same problem - so in essence I have to manually stop the listener (ctrl+c on terminal) and then just start again before I can run an additional test run, otherwise the following is logged:

```
[debug] [iProxy] recv failed: Resource temporarily unavailable
[debug] [iProxy] recv failed: Operation not permitted
[XCUITest] ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up
```

I've tried using AppiumDriver .Close(), .Dispose() & .Quit(). None seemed to close the iProxy session properly.

**Comment by nghiadhd** [comment] 2016-10-18 01:46
@imurchie, @PedroUSA & @aluedeke

I see that seem an error from Xcode 8 SDK, I built a port-forward base on 'peertalk' framework. It works look like iProxy. 
It works stable with Xcode 7.3.1. However when I use 'xcode-select -s' to switch to Xcode 8. I got "connection refuse" sometime. I still not found the root cause but when I switch back to Xcode 7.3.1. I didn't see this issue any more

**Comment by wjl025** [comment] 2016-10-19 09:06
i solve issue is:
before run ,kill all PID 
ps aux|grep udid|grep -v grep|awk '{print $2}'|xargs kill -9
udid is your device

**Comment by nghiadhd** [comment] 2016-10-19 09:12
@wjl025 

Did you test with this test script?
https://gist.github.com/nghiadhd/a4038a5d163f56516a817fe668a33696#file-run-loop

In the past, I used 'Activity Monitor' app to make sure `iProxy` was killed, but next session still got `Could not proxy command to remote server` exception

**Comment by SatishKumarKV** [comment] 2017-03-15 07:48
https://youtu.be/ThcDudhMnqw?list=PLMGgSPBuQnRFKaaY11jL5E7kwhnVOoCJT

**Comment by jlipps** [comment] 2017-04-06 22:48
There's a lot going on in this thread, but seems like @aluedeke may have summed it up, @imurchie do you concur?

**Comment by imurchie** [comment] 2017-07-13 19:31
All of this logic has completely changed. Closing.

**Closed by imurchie** 2017-07-13 19:31 UTC
Labels: NeedsTriage
