### ISSUE TITLE
Can't retrieve the object/elements anymore after selecting a date in popup

### ISSUE THREAD

**Issue by peterwest83** [appium/appium#8747] opened 2017-06-28 08:17 UTC
## The problem
Since couple of months I'm working on a test automation framework for a mobile Android app. This is my first project for a mobile app and I'm also new to the tooling that we use. The framework is build in Visual Studio (C#) and we use Appium to be able to run our test. Last Friday I updated my Appium version to 1.6.4 to make it possible to run against Android 7.0 and 8.0.
I found out that Name is no longer supported, but found a workaround for this. But I couldn't found a solution for the other problem I have since the update.

I'm working for a bank and one of my tests is to add a recurring payment. During this test I need to fill in the start date and end date of the recurring payment. The date is selecter is some kind of calendar popup. But after I selected the "OK" button to confirm the selected date, my objects/elements are no longer recognized by Appium and I'm stuck. See screenshots below:

![screenshot_20170628-095945](https://user-images.githubusercontent.com/29748918/27626765-97b6478c-5be9-11e7-93ad-ef02a2013ef3.png)

![screenshot_20170628-095949](https://user-images.githubusercontent.com/29748918/27626770-9b64b74c-5be9-11e7-974e-635e481493a7.png)

## Environment
Appium Version: 1.6.4
Last working Appium Version: 1.4.X
Emulator

Yesterday I already tried some fixes with no luck:
- Initialize the object again when returning to the page
- Changed order
- Refresh the page

Hope you can help me with a working solution!

**Comment by mykola-mokhnach** [comment] 2017-06-28 09:01
Closed as duplicate of https://github.com/appium/appium/issues/8740

**Closed by mykola-mokhnach** 2017-06-28 09:01 UTC
