### ISSUE TITLE
Pickers with larger number of elements are not steerable by appium - iOS 11.x

### ISSUE THREAD

**Issue by GrzegorzSidwa** [appium/appium#10029] opened 2018-01-18 15:26 UTC
## The problem

When steering app with picker which have about 20 elements everything works correctly. When performing same operations on same app, but picker has more - like 30 and more elements then suddenly during performing operations application is crashed.
What is the most important issue described below exists only on iOS 11.x version. I've tried same scenarios on 10.x and it works correctly. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1, 1.7.2
* Desktop OS/version used to run Appium: MacOS 10.13.2
* Node.js version (unless using Appium.app|exe): 7.7.3
* Mobile platform/version under test: iOS 11.x
* Real device or emulator/simulator: real device and simulator
* Appium CLI or Appium.app|exe: appium CLI

## Details

Attaching source code of sample applications for iOS and C# project which represents issues.
In the C# project there are thread sleeps to check how app under test behaves. In case of wrong scenario (with 30 elements) application crashes before reaches thread.sleep and in case of correct scenario (with 20 elements) application is closed when driver is closed.

## Link to Appium logs

https://gist.github.com/GrzegorzSidwa/aa7162b9d7b36712b80a4e157cfb5461 -> logs when app was crashed
https://gist.github.com/GrzegorzSidwa/14eb789afc44fa2ed608e7045b701553 -> logs from correct execution

## Code To Reproduce Issue [ Good To Have ]
[appiumTest_csProject.zip](https://github.com/appium/appium/files/1643334/appiumTest_csProject.zip)
[PickerTest_iOSapp.zip](https://github.com/appium/appium/files/1643345/PickerTest_iOSapp.zip)

`using (var driver = new IOSDriver<IOSElement>(new Uri("http://10.5.17.173:4723/wd/hub"), capabilities)){
var pred = "TRUEPREDICATE";
var a = driver.FindElementsByIosNsPredicate(pred);
foreach (var elem in a)
	Console.WriteLine("TagName: " + elem.TagName);
foreach (var elem in a)
	Console.WriteLine("Attr name: " + elem.GetAttribute("name"));
foreach (var elem in a)
	Console.WriteLine("Displayed: " + elem.Displayed);
}`

**Comment by mykola-mokhnach** [comment] 2018-01-18 16:15
Duplicate of https://github.com/facebook/WebDriverAgent/issues/826

**Closed by mykola-mokhnach** 2018-01-18 16:15 UTC
