### ISSUE TITLE
Unable to install and launch webdriver agent on the real ios device .

### ISSUE THREAD

**Issue by rraj2017** [appium/appium#16476] opened 2022-02-21 09:18 UTC
## The problem

Unable to install and launch webdriveragent on real ios device.

## Environment

* Appium version  - 1.22.2 (CLI as well as Appium GUI Desktop)
* Last Appium version that did not exhibit the issue (if applicable): - Not checked
* Desktop OS/version used to run Appium: - Big Sur version 11.6.4 and xcode version - 13.2.1
* Node.js version (unless using Appium.app|exe): -node 17.3.1
* Npm or Yarn package manager: - npm version - 8.3.0
* Mobile platform/version under test: - ipad Air 2 version 14.7
* Real device or emulator/simulator: - Real device iPad Air 2 version 14.7
* Appium CLI or Appium.app|exe: - Appium CLI version 1.22.2 and appium.app - 1.22.2

## Details

I have to test a hybrid app on real ios device . I am using basic automatic as well as basic manual configuration approach to run 
the test app on iPad Air 2 real device . My test app is getting installed but webdriveragent app is not getting installed to the real device.
## Link to Appium logs

[Appium] Appium v1.22.2 creating new XCUITestDriver (v3.59.0) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "iOS",
[debug] [BaseDriver]     "appium:deviceName": "Mohit's iPad",
[debug] [BaseDriver]     "appium:automationName": "XCUITest",
[debug] [BaseDriver]     "appium:app": "/Users/rr107335/Downloads/PlayerMax27Jan2022.ipa",
[debug] [BaseDriver]     "appium:xcodeOrgId": "L7E7VRRPSC",
[debug] [BaseDriver]     "appium:xcodeSigningId": "iPhone Developer",
[debug] [BaseDriver]     "appium:udid": "223eb12bd0f463e51f5f980270a14b410dd16c34",
[debug] [BaseDriver]     "appium:updatedWDABundleId": "com.ritu45555.MyFirstTestProject84885",
[debug] [BaseDriver]     "appium:platformVersion": "14.7",
[debug] [BaseDriver]     "appium:includeSafariInWebviews": true,
[debug] [BaseDriver]     "appium:newCommandTimeout": 3600,
[debug] [BaseDriver]     "appium:connectHardwareKeyboard": true
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Session created with session id: 52cc18d4-ed40-4c76-a157-ed7e9f0aee17
[debug] [XCUITest] Current user: 'rr107335'
[debug] [XCUITest] Available devices: 223eb12bd0f463e51f5f980270a14b410dd16c34
[debug] [XCUITest] Creating iDevice object with udid '223eb12bd0f463e51f5f980270a14b410dd16c34'
[XCUITest] Determining device to run tests on: udid: '223eb12bd0f463e51f5f980270a14b410dd16c34', real device: true
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1645095608618 (16:30:08 GMT+0530 (India Standard Time))
[BaseDriver] Using local app '/Users/rr107335/Downloads/PlayerMax27Jan2022.ipa'
[debug] [BaseDriver] Unzipping '/Users/r107335/Downloads/PlayerMax27Jan2022.ipa'
[debug] [BaseDriver] Enforcing UTF-8 encoding on the extracted file names for 'PlayerMax27Jan2022.ipa'
dbug Support Found '%s' at '%s'
dbug Support unzip
dbug Support /usr/bin/unzip
[debug] [BaseDriver] Extracted 1 bundle item from '/Users/rr107335/Downloads/PlayerMax27Jan2022.ipa' in 1506ms: Payload/PlayerMax.app
[BaseDriver] Assuming 'Payload/PlayerMax.app' is the correct bundle
[BaseDriver] Unzipped local app to '/var/folders/qr/wljj65bn42s_2yqtp2pm_t2mz3kf64/T/2022117-60093-1va8fz3.duwp/PlayerMax.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1645095610356 (16:30:10 GMT+0530 (India Standard Time))
[debug] [XCUITest] Checking whether app '/var/folders/qr/wljj65bn42s_2yqtp2pm_t2mz3kf64/T/2022117-60093-1va8fz3.duwp/PlayerMax.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [XCUITest] Getting bundle ID from app '/var/folders/qr/wljj65bn42s_2yqtp2pm_t2mz3kf64/T/2022117-60093-1va8fz3.duwp/PlayerMax.app': 'com.ati.playermax'
[debug] [BaseDriver] Event 'resetStarted' logged at 1645095610358 (16:30:10 GMT+0530 (India Standard Time))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1645095610358 (16:30:10 GMT+0530 (India Standard Time))
[WebDriverAgent] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
[WebDriverAgent] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] Crash reports root '/Users/rr107335/Library/Logs/CrashReporter/MobileDevice/Mohit’s iPad' does not exist. Got nothing to gather.
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1645095610622 (16:30:10 GMT+0530 (India Standard Time))
[XCUITest] Setting up real device
[debug] [XCUITest] Verifying application platform
[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[debug] [XCUITest] Installing '/var/folders/qr/wljj65bn42s_2yqtp2pm_t2mz3kf64/T/2022117-60093-1va8fz3.duwp/PlayerMax.app' on device with UUID '223eb12bd0f463e51f5f980270a14b410dd16c34'...
[debug] [XCUITest] Using 'serial' app deployment strategy. You could change it by providing another value to the 'appInstallStrategy' capability
[debug] [XCUITest] Getting bundle ID from app '/var/folders/qr/wljj65bn42s_2yqtp2pm_t2mz3kf64/T/2022117-60093-1va8fz3.duwp/PlayerMax.app': 'com.ati.playermax'
[debug] [XCUITest] Successfully scanned the tree structure of '/var/folders/qr/wljj65bn42s_2yqtp2pm_t2mz3kf64/T/2022117-60093-1va8fz3.duwp/PlayerMax.app'
[debug] [XCUITest] Got 84 folders and 1763 files to push
[debug] [XCUITest] Successfully created the remote folder structure (85 items)
[debug] [XCUITest] Proceeding to serial files push
[debug] [WebDriverAgent] Parsed BUILD_DIR configuration value: '/Users/rr107335/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Build/Products'
[debug] [WebDriverAgent] Got derived data root: '/Users/rr107335/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu'
[debug] [XCUITest] Successfully pushed 84 folders and 1763 files within 24270ms
[debug] [XCUITest] A new application installation is going to be performed
[XCUITest] App installation succeeded after 28922ms
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1645095639709 (16:30:39 GMT+0530 (India Standard Time))
[debug] [WebDriverAgent] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device 223eb12bd0f463e51f5f980270a14b410dd16c34 on local port 8100, device port 8100
[debug] [DevCon Factory] Cached connections count: 0
[DevCon Factory] Successfully requested the connection for 223eb12bd0f463e51f5f980270a14b410dd16c34:8100
[debug] [XCUITest] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [iProxy@223eb12b:8100] Connection was refused to port 8100
[WD Proxy] socket hang up
[debug] [WebDriverAgent] WDA is not listening at 'http://127.0.0.1:8100/'
[debug] [WebDriverAgent] WDA is currently not running. There is nothing to cache
[debug] [XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1645095639917 (16:30:39 GMT+0530 (India Standard Time))
[WebDriverAgent] Launching WebDriverAgent on the device
[WebDriverAgent] WebDriverAgent does not need a cleanup. The sources are up to date (1642588727928 >= 1642588727928)
[debug] [WebDriverAgent] Killing running processes 'xcodebuild.*223eb12bd0f463e51f5f980270a14b410dd16c34' for the device 223eb12bd0f463e51f5f980270a14b410dd16c34...
[debug] [WebDriverAgent] 'pgrep -if xcodebuild.*223eb12bd0f463e51f5f980270a14b410dd16c34' didn't detect any matching processes. Return code: 1
[debug] [WebDriverAgent] Successfully updated '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj/project.pbxproj' with bundle id 'com.ritu45555.MyFirstTestProject84885'
[debug] [WebDriverAgent] Generating xcode config file for orgId 'L7E7VRRPSC' and signingId 'iPhone Developer'
[debug] [WebDriverAgent] Writing xcode config file to /var/folders/qr/wljj65bn42s_2yqtp2pm_t2mz3kf64/T/2022117-60093-1oljy1z.7jsk/appium-temp.xcconfig
[debug] [WebDriverAgent] Using Xcode configuration file: '/var/folders/qr/wljj65bn42s_2yqtp2pm_t2mz3kf64/T/2022117-60093-1oljy1z.7jsk/appium-temp.xcconfig'
[debug] [WebDriverAgent] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/rr107335/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu -destination id=223eb12bd0f463e51f5f980270a14b410dd16c34 IPHONEOS_DEPLOYMENT_TARGET=14.7 -xcconfig /var/folders/qr/wljj65bn42s_2yqtp2pm_t2mz3kf64/T/2022117-60093-1oljy1z.7jsk/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
[debug] [WebDriverAgent] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[debug] [WebDriverAgent] Waiting up to 60000ms for WebDriverAgent to start
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [iProxy@223eb12b:8100] Connection was refused to port 8100
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [iProxy@223eb12b:8100] Connection was refused to port 8100
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [iProxy@223eb12b:8100] Connection was refused to port 8100
[WD Proxy] socket hang up
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [iProxy@223eb12b:8100] Connection was refused to port 8100
[WD Proxy] socket hang up
[Xcode] 2022-02-17 16:30:44.495 xcodebuild[60114:264716] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos15.2-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/rr107335/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Build/Products/WebDriverAgentRunner_iphoneos15.2-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fd804dc66e0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] ** TEST BUILD FAILED **
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] *** If you believe this error represents a bug, please attach the result bundle at /Users/rr107335/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs/Test/Test-WebDriverAgentRunner-2022.02.17_16-30-43-+0530.xcresult
[Xcode] 
[Xcode] 
[Xcode] 2022-02-17 16:30:44.904 xcodebuild[60114:264621] [MT] IDETestOperationsObserverDebug: 0.395 elapsed -- Testing started completed.
[Xcode] 
[Xcode] 2022-02-17 16:30:44.904 xcodebuild[60114:264621] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[Xcode] 2022-02-17 16:30:44.904 xcodebuild[60114:264621] [MT] IDETestOperationsObserverDebug: 0.395 sec, +0.395 sec -- end
[Xcode] 
[Xcode] 
[Xcode] Test session results, code coverage, and logs:
[Xcode]       /Users/rr107335/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs/Test/Test-WebDriverAgentRunner-2022.02.17_16-30-43-+0530.xcresult
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode]       No profiles for 'com.ritu45555.MyFirstTestProject84885.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.ritu45555.MyFirstTestProject84885.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
[Xcode]       WebDriverAgentRunner:
[Xcode]              WebDriverAgentRunner-Runner encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/rr107335/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs/Test/Test-WebDriverAgentRunner-2022.02.17_16-30-43-+0530.xcresult. (Underlying Error: Executable Not Found. /Users/rr107335/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app is not a valid path to an executable file. Please rebuild the project to ensure that all required executables are created. Check your project settings to ensure that a valid executable will be built.))
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 

## Code To Reproduce Issue [ Good To Have ]

passing the below capabilties to create Driver session
deviceName -iPAd Air 2
platformName-iOS
platformVersion -14.7
xcodeOrgId- Team_Id
xcodeSigningId-iPhone Developer
automationName- XCUITest
updateWDABundleId - com.mydummypro1344

**Comment by mykola-mokhnach** [comment] 2022-02-21 15:24
Duplicate of https://github.com/appium/appium/issues/16470

**Closed by mykola-mokhnach** 2022-02-21 15:24 UTC

**Comment by rraj2017** [comment] 2022-02-23 08:33
I don't think its a duplicate of 16470 , if it is so how should I resolve it .
I don't find any resolution for it .
Is it due to the unpaid developer account or is it true that admin right is needed for apple account ?

**Comment by KazuCocoa** [comment] 2022-02-23 09:06
Did you tried automatic signing as the https://github.com/appium/appium/issues/16470? or manually tried xcodebuild with `allowProvisioningUpdates`?
Interestingly, `xcodebuild` itself needed to retry a couple of times to resolve the provisioning profile with the auto config flag. I wonder such case could occur.

If your provisioning profile is a free account's one, it might fail, but sometimes work. I don't know Apple's internal, but I experienced both, success and fail, cases with my free account.

https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/#troubleshooting-ideas

**Comment by rraj2017** [comment] 2022-02-23 11:51
@KazuCocoa  yes I am signing it automatically by using xcodeOrgId and xcodeSigningId capabilities .

**Comment by KazuCocoa** [comment] 2022-02-23 19:19
You could try `appium:allowProvisioningDeviceRegistration` capability that adds `allowProvisioningUpdates` in xcodebuild as the linked issue if you still did not. Somecases the flag helps to resolve the provisiong profile in xcodebuild. They can work with xcodeOrgId and xcodeSigningId caps.

**Comment by rraj2017** [comment] 2022-02-25 09:20
@KazuCocoa 
Tring with appium:allowProvisioningDeviceRegistration it now installs the webdriveragent app into real device , but it is taking alot of time to create the session and I got error message Failed to create Session , Request timed out .
How can I resolve this issue now ?

**Comment by KazuCocoa** [comment] 2022-02-25 09:30
it depends on your context. Please attach the log.

Like https://appiumpro.com/editions/77-optimizing-webdriveragent-startup-performance tips may help to reduce such timeout.
