### ISSUE TITLE
Question: Get "/wd/hub/session/:sessionId?/location" implementation.

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/appium#5135] opened 2015-05-19 14:16 UTC
Hi. There is an interesting question. 

Appium 1.4 allows to set GPS coordinates (location) but still [doesn't allow to get them](https://github.com/appium/appium/blob/68cd862c93fd0c9999cc9f3f85172dcb0d255067/lib/server/routing.js#L166). Is it going to be implemented? Is there any workaround for now?

**Comment by jlipps** [comment] 2015-05-27 16:03
the only workaround currently is to have your app print gps coordinates to some ui element and get the text from that using appium. i'll add this to the features list so we can try to add it in the future

**Comment by jlipps** [comment] 2017-07-20 17:34
duplicate of #5047.

**Closed by jlipps** 2017-07-20 17:34 UTC
Labels: Enhancement, P2
