### ISSUE TITLE
bug: incorrect coordinate calculation for iPad Pro (12.9-inch) in landscape mode

### ISSUE THREAD

**Issue by rdmrtn** [appium/appium#20486] opened 2024-08-23 07:23 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Tab by coordinates and/or swipe do not work as expected because vertical points are not calculated correctly.

### Expected Behavior

Tab by coordinates and/or swipe work as expected

### Minimal Reproducible Example

1) Start session:

{
  "appium:deviceName": "iPad Pro (12.9-inch)",
  "appium:udid": "<udid>",
  "platformName": "iOS",
  "appium:platformVersion": "16.4.1",
  "appium:noReset": true,
  "appium:automationName": "xcuitest",
  "appium:showXcodelogs": true,
  "appium:bundleId": "com.apple.freeform"
}

2) Set orientation to LANDSCAPE

3) Swipe or tap by coordinates

### Environment

- Operating system: Linux
- Appium server version (output of `appium --version`): 2.11.3
- Appium driver(s) and their version(s) (`appium driver list`): -xcuitest@7.24.17 [installed (npm)]
- Appium plugin(s) and their version(s) (`appium plugin list`): -
- Node.js version (output of `node --version`): v18.20.4
- `npm` version (output of `npm --version`): 10.7.0
- Last component(s) version which did _not_ exhibit the problem: Not sure but switching from AppiumGesture to W3CGestore may cause problem
- Platform and version under test: iOS 16.4.1
- Real device or emulator/simulator: Real Device

### Link to Appium Logs

https://gist.github.com/rdmrtn/42974cb6098cd624ffdf985f6343b257

### Further Information

As you can see from attachment, for LANDSCAPE orientation, vertical coordinate is not calculated correctly while using tab by coordinates or swipe.

https://github.com/user-attachments/assets/9e86a14a-154a-49a1-be3c-4830f141835b

**Comment by mykola-mokhnach** [comment] 2024-08-23 07:44
These coordinates are returned by XCTest. Please report the issue to Apple.

**Comment by mykola-mokhnach** [comment] 2024-08-23 07:47
As a workaround you may try to select particular elements as gesture sources instead of providing absolute coordinates (these are anyway "projected" to the XCUIApplication element)

**Comment by eglitise** [comment] 2024-08-23 08:38
Duplicate of #19385

**Comment by mykola-mokhnach** [comment] 2024-08-27 08:06
Closed as third party issue

**Closed by mykola-mokhnach** 2024-08-27 08:06 UTC
Labels: ThirdParty, XCUITest
