### ISSUE TITLE
POST appium/app/strings not returning values for all versions of Appium

### ISSUE THREAD

**Issue by albedithdiaz** [appium/appium#4568] opened 2015-02-19 05:52 UTC
After changing the android app to the gradle build system one of our Sauce Labs customers cannot access anymore the app strings trough "POST appium/app/strings"

It used to return all the strings from the strings.xml as a mapped array: => {"coupon_end_date":"Until %1$s","register_member_info":"Member Information","quantity_default":"1","global_profile_title":"Additional Information","abs__searchview_description_search":"Search","action_forgot_password":"Forgot your password?","checkoutprogress_ship":"Shipping", .... etc ....

Now it just returns an empty array:
POST appium/app/strings 
=> {}

Do you have any ideas why is this happening?
We believe that there might be an issue with the version of the Android SDK used to build the app, and the tool used to decode it (e.g., https://code.google.com/p/android-apktool/issues/detail?id=680). 

Here is the SDK version used to build the app:
<uses-sdk
android:minSdkVersion="14"
android:targetSdkVersion="21" />

**Comment by jlipps** [comment] 2015-03-03 17:32
@albedithdiaz that sounds eerily like https://github.com/appium/appium/issues/4326

I wonder if gradle actually negatively impacts the apk in terms of UiAutomator's ability to do something with it.

**Comment by imurchie** [comment] 2015-03-06 20:37
I think Gradle is a red herring here. Rather, the issue is the fact that our Android emulators run in an environment with Java 6, which is incompatible with the latest `Apktool`. We have an old version (1.5.2 is the last version that supports Java 6) that we use, but it cannot handle anything built with the higher SDK versions.

It always fails with 

```shell
info: [debug] java -jar "/Users/isaac/code/appium/submodules/appium-adb/jars/appium_apk_tools_1.6.jar" "stringsFromApk" "/var/folders/k6/h_kw_85n6x7brz0pvy4kv5nw0000gn/T/11526-51158-1p31md0/appium-app.apk" "/tmp/io.appium.android.apis"
warn: Error getting strings.xml from apk
info: [debug] Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:54)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:540)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:76)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:68)
        at io.appium.apktools.StringsXML.run(StringsXML.java:84)
        at io.appium.apktools.Main.main(Main.java:31)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
        at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
        at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:43)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:100)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:81)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
        ... 5 more

info: [debug] executing cmd: /Users/isaac/code/adt-bundle/sdk/platform-tools/adb -s emulator-5554 shell "echo '{}' > /data/local/tmp/strings.json"
```

**Comment by jlipps** [comment] 2015-03-07 09:47
Good thinking. That's already on our list to fix. Closing here because it appears to be a Sauce issue, not an Appium one.

**Closed** 2015-03-07 09:47 UTC
Labels: NeedsTriage
