### ISSUE TITLE
endpoint /executeAsync through error " Encountered internal error running command: Error: Did not get any response after 300s"

### ISSUE THREAD

**Issue by khanhdodang** [appium/appium#11925] opened 2019-01-02 08:57 UTC
## The problem

The response for endpoint `execute_async` on iOS web is 500 and makes the automation scripts failed.

## Environment

* Appium version: 1.9.1
* Mobile platform/version under test: iOS web
* Real device: iPhone 6 Plus - iOS 10.0.2

## Link to Appium logs

https://gist.github.com/khanhdodang/59121797239d6df0d85808f89dd50801

## Code To Reproduce Issue

Run automation test on iOS web:
The Java snippet code below:
```
((JavascriptExecutor) driver).executeAsyncScript("window.setTimeout(arguments[arguments.length - 1], 500);");
```

Refer to docs:
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidexecute_async
https://appium.readthedocs.io/en/stable/en/commands/web/execute-async/

**Comment by vedharish** [comment] 2019-02-08 10:11
Can reproduce this on appium 1.11.0-beta.3 for iPhone 8 as well.

Protractor tests are failing on iOS devices because of this reason. [Related Issue](https://github.com/angular/protractor/issues/2840)

**Comment by mykola-mokhnach** [comment] 2019-08-20 05:25
This may be addressed by disabling CORS using server args or by using appium@beta

**Closed by mykola-mokhnach** 2019-08-20 05:25 UTC
Labels: Mobile Safari
