### ISSUE TITLE
Turning off mock location on android

### ISSUE THREAD

**Issue by swizes** [appium/appium#14207] opened 2020-04-21 08:58 UTC
I am testing an app with emulators and real devices and the app does not allow mocked locations, it should be possible to disable "mock location" via appium desired capabilites or somewhere else. I am not sure, if such option exists

**Comment by mykola-mokhnach** [comment] 2020-04-21 09:03
Duplicate of https://github.com/appium/appium/issues/8969

**Closed by mykola-mokhnach** 2020-04-21 09:03 UTC
