### ISSUE TITLE
RecyclerView : Element id is not Visible in Appium Desktop if 2nd Page is drawn and giving error StaleElementReferenceException.

### ISSUE THREAD

**Issue by maxasha** [appium/appium#16143] opened 2021-11-22 10:16 UTC
On Recycler view when 2nd Page is drawn , Elemenid is not visible hence giving common.exceptions.StaleElementReferenceException exception error
Element Id is not available in Appium Desktop when 2nd page is drawn in recycler view in Android. 
As soon as 2nd Page is drawn for all element ElementID is missing. 
Not able to identify any element and not even able to get element attribute with text. 
But if only 1 page is drawn , All element shows element id and for all element is able to get attribute (text and other)

## Environment

* Appium version :1.21.0 Electron: 7.2.4 Nodejs:12.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
![image](https://user-images.githubusercontent.com/26781603/142840684-ef363a4d-2ce7-44ba-92d9-2255fefa6eee.png)

* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:Android
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Both

## Details

When 2nd Page is drawn Elelment id is not available and throws error stating text is not valid for element
![image](https://user-images.githubusercontent.com/26781603/142841064-8bdbb5d2-9561-4f75-bff4-eb046b7e3dea.png)
![image](https://user-images.githubusercontent.com/26781603/142841129-c38e5e38-977c-44c3-95e8-454f98517632.png)

When only 1 page is drawn in recycler view 
![image](https://user-images.githubusercontent.com/26781603/142841213-8658c65b-d791-4021-bee7-05b3914c40cc.png)
![image](https://user-images.githubusercontent.com/26781603/142841287-b60fa093-cc11-4686-ac29-c80c0e875645.png)
 

## Link to Appium logs

[Appium_1page.txt](https://github.com/appium/appium/files/7580055/Appium_1page.txt)
[Appium2ndPageIssue.txt](https://github.com/appium/appium/files/7580056/Appium2ndPageIssue.txt)

Log error on 2nd page: 
![image](https://user-images.githubusercontent.com/26781603/142843559-48161906-ff48-4f93-8216-a178b06e7288.png)

**Comment by mykola-mokhnach** [comment] 2021-11-22 12:49
Stale element exception is usually thrown if the cached element is not present anymore. Have you tried to find this element again?

**Comment by mykola-mokhnach** [comment] 2021-11-22 12:49
Stale element exception is usually thrown if the cached element is not present anymore. Have you tried to find this element again?

**Comment by maxasha** [comment] 2021-11-22 18:12
Yes multiple find is done before getting attribute and after line get attribute, attaching logs for Appium and code logs when 1 page is drawn and when 2nd page is loaded.
Logs when only 1 page is loaded 
[AppiumLogsfor_MultipleFindElelment_only1Pagedrawn.txt](https://github.com/appium/appium/files/7583421/AppiumLogsfor_MultipleFindElelment_only1Pagedrawn.txt)
[CodeLogs_MultipleFindElelment_only1Pagedrawn.txt](https://github.com/appium/appium/files/7583422/CodeLogs_MultipleFindElelment_only1Pagedrawn.txt)

Logs when only 2nd page is loaded 
[AppiumLogsfor_MultipleFindElelment_2ndPageDrawn.txt](https://github.com/appium/appium/files/7583429/AppiumLogsfor_MultipleFindElelment_2ndPageDrawn.txt)
[CodeLogs_MultipleFindElelment_2ndPageDrawn.txt](https://github.com/appium/appium/files/7583430/CodeLogs_MultipleFindElelment_2ndPageDrawn.txt)

**Comment by mykola-mokhnach** [comment] 2021-11-22 18:41
```
[HTTP] --> POST /wd/hub/session/3f1bfd68-8fe7-4704-b206-a48438b62191/elements
[HTTP] {"using":"xpath","value":"(//*[@resource-id=\"com.abc.def:id/deviceAddress\"])[2]"}
[debug] [W3C (3f1bfd68)] Calling AppiumDriver.findElements() with args: ["xpath","(//*[@resource-id=\"com.abc.def:id/deviceAddress\"])[2]","3f1bfd68-8fe7-4704-b206-a48438b62191"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [WD Proxy] Matched '/elements' to command name 'findElements'
[debug] [WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:8203/wd/hub/session/5e1dbe97-372b-4d28-a09f-dcea2cf71c43/elements] with body: {"strategy":"xpath","selector":"(//*[@resource-id=\"com.abc.def:id/deviceAddress\"])[2]","context":"","multiple":true}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"5e1dbe97-372b-4d28-a09f-dcea2cf71c43","value":[{"ELEMENT":"16a749d4-aa29-4da8-8911-3eaf45c7e501","element-6066-11e4-a52e-4f735466cecf":"16a749d4-aa29-4da8-8911-3eaf45c7e501"}]}
[debug] [W3C (3f1bfd68)] Responding to client with driver.findElements() result: [{"element-6066-11e4-a52e-4f735466cecf":"16a749d4-aa29-4da8-8911-3eaf45c7e501","ELEMENT":"16a749d4-aa29-4da8-8911-3eaf45c7e501"}]
[HTTP] <-- POST /wd/hub/session/3f1bfd68-8fe7-4704-b206-a48438b62191/elements 200 10411 ms - 139
[HTTP] 
[HTTP] --> GET /wd/hub/session/3f1bfd68-8fe7-4704-b206-a48438b62191/element/16a749d4-aa29-4da8-8911-3eaf45c7e501/attribute/text
[HTTP] {}
[debug] [W3C (3f1bfd68)] Calling AppiumDriver.getAttribute() with args: ["text","16a749d4-aa29-4da8-8911-3eaf45c7e501","3f1bfd68-8fe7-4704-b206-a48438b62191"]
[debug] [WD Proxy] Matched '/element/16a749d4-aa29-4da8-8911-3eaf45c7e501/attribute/text' to command name 'getAttribute'
[debug] [WD Proxy] Proxying [GET /element/16a749d4-aa29-4da8-8911-3eaf45c7e501/attribute/text] to [GET http://127.0.0.1:8203/wd/hub/session/5e1dbe97-372b-4d28-a09f-dcea2cf71c43/element/16a749d4-aa29-4da8-8911-3eaf45c7e501/attribute/text] with no body
[WD Proxy] Got response with status 404: {"sessionId":"5e1dbe97-372b-4d28-a09f-dcea2cf71c43","value":{"error":"stale element reference","message":"androidx.test.uiautomator.StaleObjectException","stacktrace":"io.appium.uiautomator2.common.exceptions.StaleElementReferenceException: androidx.test.uiautomator.StaleObjectException\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:45)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:262)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:256)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMe...
[debug] [W3C] Matched W3C error code 'stale element reference' to StaleElementReferenceError
[debug] [W3C (3f1bfd68)] Encountered internal error running command: io.appium.uiautomator2.common.exceptions.StaleElementReferenceException: androidx.test.uiautomator.StaleObjectException
[debug] [W3C (3f1bfd68)] 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:45)
[debug] [W3C (3f1bfd68)] 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:262)
[debug] [W3C (3f1bfd68)] 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:256)
[debug] [W3C (3f1bfd68)] 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C (3f1bfd68)] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
[debug] [W3C (3f1bfd68)] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[debug] [W3C (3f1bfd68)] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C (3f1bfd68)] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
[debug] [W3C (3f1bfd68)] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
[debug] [W3C (3f1bfd68)] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
[debug] [W3C (3f1bfd68)] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
[debug] [W3C (3f1bfd68)] 	at java.lang.Thread.run(Thread.java:929)
[debug] [W3C (3f1bfd68)] Caused by: androidx.test.uiautomator.StaleObjectException
[debug] [W3C (3f1bfd68)] 	at androidx.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:647)
[debug] [W3C (3f1bfd68)] 	at androidx.test.uiautomator.UiObject2.hashCode(UiObject2.java:105)
[debug] [W3C (3f1bfd68)] 	at java.lang.Object.toString(Object.java:291)
[debug] [W3C (3f1bfd68)] 	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2978)
[debug] [W3C (3f1bfd68)] 	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2855)
[debug] [W3C (3f1bfd68)] 	at java.util.Formatter.format(Formatter.java:2524)
[debug] [W3C (3f1bfd68)] 	at java.util.Formatter.format(Formatter.java:2459)
[debug] [W3C (3f1bfd68)] 	at java.lang.String.format(String.java:2870)
[debug] [W3C (3f1bfd68)] 	at io.appium.uiautomator2.utils.ReflectionUtils.invoke(ReflectionUtils.java:84)
[debug] [W3C (3f1bfd68)] 	at io.appium.uiautomator2.core.AxNodeInfoExtractor.extractAxNodeInfo(AxNodeInfoExtractor.java:51)
[debug] [W3C (3f1bfd68)] 	at io.appium.uiautomator2.core.AxNodeInfoExtractor.toAxNodeInfo(AxNodeInfoExtractor.java:41)
[debug] [W3C (3f1bfd68)] 	at io.appium.uiautomator2.utils.ElementHelpers.getText(ElementHelpers.java:152)
[debug] [W3C (3f1bfd68)] 	at io.appium.uiautomator2.utils.Eleme
```

The exception is caused by UiAutomator framework itself. You could try to use `findElement` instead of `findElements`, because the first would try to restore element instance if it gets stale. Otherwise I have no good suggestions.

**Comment by mykola-mokhnach** [comment] 2021-11-22 18:42
Also it makes sense to try the most recent server version

**Comment by mykola-mokhnach** [comment] 2021-11-24 17:23
Closed as third party issue

**Closed by mykola-mokhnach** 2021-11-24 17:23 UTC
Labels: ThirdParty, UIAutomator2
