### ISSUE TITLE
i have update wd to 1.4.0  but i can not use keyevent in UM2.0 as before

### ISSUE THREAD

**Issue by 541347048** [appium/appium#8952] opened 2017-08-01 08:39 UTC
logs：
Proxying [POST /wd/hub/session/2ad19c28-4828-4382-bd32-2fc8a9bc13b8/appium/device/keyevent] to [POST http://localhost:8200/wd/hub/session/6412a65c-850f-4fff-b712-2d10923d0456/appium/device/keyevent] with body: {"sessionId":"2ad19c28-4828-4382-bd32-2fc8a9bc13b8","keycode":8}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:354:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

https://github.com/admc/wd/issues/480
you can look at this .
this man said he has fixed is bug in wd@1.30    but  i have update wd to 1.40  .it is no use 

sorry .  my english is not so good .

**Comment by 541347048** [comment] 2017-08-01 08:46
please help!!

**Comment by 541347048** [comment] 2017-08-01 08:47
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined       logs

**Comment by mykola-mokhnach** [comment] 2017-08-01 10:07
Please fill out the requested information about the issue first

**Comment by 541347048** [comment] 2017-08-01 10:19
@mykola-mokhnach    @jlipps

**Comment by mykola-mokhnach** [comment] 2017-08-01 11:23
Closed as duplicate of https://github.com/appium/appium/issues/8951

**Closed by mykola-mokhnach** 2017-08-01 11:23 UTC
Labels: NeedsInfo

**Comment by mykola-mokhnach** [comment] 2017-08-01 11:26
For wd client one has to use "pressKeycode" method in order to send keypress event

**Comment by 541347048** [comment] 2017-08-02 01:25
@mykola-mokhnach thanks very mush!    i have get it
