### ISSUE TITLE
ENAMETOOLONG: name too long for default-capabilities

### ISSUE THREAD

**Issue by radoslaw-karasinski-sauce** [appium/appium#17456] opened 2022-09-07 14:27 UTC
Appium v2.0.0-beta.43 (REV dbda725634e657c1bb0c0203476f262bcb065b40) seems to be picky about order of keys in default-capabilities.

Working order:
```
./node-darwin . --base-path /wd/hub --default-capabilities '{"appium:options": {"preventWDAAttachments": true, "orientation": "PORTRAIT", "launchTimeout": 180000, "showIOSLog": false, "noReset": true, "eventTimings": true, "backendRetries": 4, "maxTypingFrequency": 8, "newCommandTimeout": 0, "derivedDataPath": "/tmp/super-secret-path-to-WebDriverAgent-aaaaaaaaaaaaaa/DerivedData/WebdriverAgent", "bootstrapPath": "/tmp/super-secret-path-to-WebDriverAgent-aaaaaaaaaaaaaa", "app": "/tmp/super-secret-path-to-my-app-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.zip", "keepKeyChains": true, "connectHardwareKeyboard": true, "simulatorPasteboardAutomaticSync": "on"}}'
[Appium] Welcome to Appium v2.0.0-beta.43 (REV dbda725634e657c1bb0c0203476f262bcb065b40)
[Appium] Non-default server args:
[Appium] {
[Appium]   basePath: '/wd/hub'
[Appium] }
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium] {
[Appium]   'appium:options': {
[Appium]     preventWDAAttachments: true,
[Appium]     orientation: 'PORTRAIT',
[Appium]     launchTimeout: 180000,
[Appium]     showIOSLog: false,
[Appium]     noReset: true,
[Appium]     eventTimings: true,
[Appium]     backendRetries: 4,
[Appium]     maxTypingFrequency: 8,
[Appium]     newCommandTimeout: 0,
[Appium]     derivedDataPath: '/tmp/super-secret-path-to-WebDriverAgent-aaaaaaaaaaaaaa/DerivedData/WebdriverAgent',
[Appium]     bootstrapPath: '/tmp/super-secret-path-to-WebDriverAgent-aaaaaaaaaaaaaa',
[Appium]     app: '/tmp/super-secret-path-to-my-app-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.zip',
[Appium]     keepKeyChains: true,
[Appium]     connectHardwareKeyboard: true,
[Appium]     simulatorPasteboardAutomaticSync: 'on'
[Appium]   }
[Appium] }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
```

Not working order (`connectHardwareKeyboard` key moved):
```
./node-darwin . --base-path /wd/hub --default-capabilities '{"appium:options": {"preventWDAAttachments": true, "orientation": "PORTRAIT", "launchTimeout": 180000, "showIOSLog": false, "noReset": true, "eventTimings": true, "backendRetries": 4, "maxTypingFrequency": 8, "newCommandTimeout": 0, "connectHardwareKeyboard": true, "derivedDataPath": "/tmp/super-secret-path-to-WebDriverAgent-aaaaaaaaaaaaaa/DerivedData/WebdriverAgent", "bootstrapPath": "/tmp/super-secret-path-to-WebDriverAgent-aaaaaaaaaaaaaa", "app": "/tmp/super-secret-path-to-my-app-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.zip", "keepKeyChains": true, "simulatorPasteboardAutomaticSync": "on"}}'

ENAMETOOLONG: name too long, open '{"appium:options": {"preventWDAAttachments": true, "orientation": "PORTRAIT", "launchTimeout": 180000, "showIOSLog": false, "noReset": true, "eventTimings": true, "backendRetries": 4, "maxTypingFrequency": 8, "newCommandTimeout": 0, "connectHardwareKeyboard": true, "derivedDataPath": "/tmp/super-secret-path-to-WebDriverAgent-aaaaaaaaaaaaaa/DerivedData/WebdriverAgent", "bootstrapPath": "/tmp/super-secret-path-to-WebDriverAgent-aaaaaaaaaaaaaa", "app": "/tmp/super-secret-path-to-my-app-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.zip", "keepKeyChains": true, "simulatorPasteboardAutomaticSync": "on"}}'
```

Issue can be related to this one: https://github.com/appium/appium/issues/17308

Additional informations:
```
./node-darwin --version
v16.13.2

npm --version
8.18.0
```

**Comment by jlipps** [comment] 2022-09-07 19:19
I thought @boneskull fixed this. Have we not released a version of the server with the fix yet? Or is this another case?

**Comment by boneskull** [comment] 2022-09-07 19:20
i'll see if it's been released

**Comment by boneskull** [comment] 2022-09-07 19:37
nope. I'll cut a release

**Comment by boneskull** [comment] 2022-09-07 19:39
dupe of #17308

**Closed by boneskull** 2022-09-07 19:39 UTC
