### ISSUE TITLE
Cannot use apksigner tool for signature verification. Original error: spawn ENOTDIR

### ISSUE THREAD

**Issue by bogdan-nica** [appium/appium#14164] opened 2020-04-09 16:30 UTC
## The problem

Appium fails to use apksigner tool for signature verification. Original error: spawn ENOTDIR

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Last Appium version that did not exhibit the issue (if applicable):1.15.1
* Desktop OS/version used to run Appium: CentOS Linux release 7.7.190
* Node.js version (unless using Appium.app|exe):10.17.0
* Npm or Yarn package manager: nmp
* Mobile platform/version under test:Android, iOS
* Real device or emulator/simulator: real devices
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/bogdan-nica/70344a7e9d7b6bffbf037114067d5871

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2020-04-09 16:33
Duplicate of https://github.com/appium/appium/issues/12660

**Closed by mykola-mokhnach** 2020-04-09 16:33 UTC
