### ISSUE TITLE
Sudden stop while script is running

### ISSUE THREAD

**Issue by erdncyz** [appium/appium#20456] opened 2024-08-15 06:25 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While running, appium suddenly stops and does not print any errors. When I examine it, it seems to suddenly stop while searching for the locater.

Appium 2.11.3
Appium plugin list 9.2.1
Uiautomator 3.7.7
Xcuitest 7.24.15

![image](https://github.com/user-attachments/assets/3977c931-4781-4b04-acf2-99ac63ac7ba5)

### Expected Behavior

Script execution must continue.

### Minimal Reproducible Example

I don't have any gist

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by eglitise** [comment] 2024-08-15 06:41
Please provide your full Appium server log.
Also it seems like you have the `device-farm` plugin active. Please check if the behavior is reproducible without this plugin.

**Comment by erdncyz** [comment] 2024-08-15 07:52
@eglitise 
My full log : https://gist.github.com/erdncyz/56a1ac4c4b170f7c9979710f493f2373

**Comment by eglitise** [comment] 2024-08-15 08:07
I noticed you also created https://github.com/AppiumTestDistribution/appium-device-farm/issues/1279 and mentioned that you did not encounter the issue after disabling the plugin. This means the cause lies with the plugin, so I am closing this issue.

**Closed by eglitise** 2024-08-15 08:07 UTC
Labels: Needs Info
