### ISSUE TITLE
testID information not visible on Appium inspector (iOS)

### ISSUE THREAD

**Issue by abhijeetkange** [appium/appium#17193] opened 2022-07-13 06:03 UTC
## The problem

Deeply nested Elements in DOM are not visible for ios 15.4 on appium inspector 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:1.22.3
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:15.4
* Real device or emulator/simulator: Iphone X
* Appium CLI or Appium.app|exe: 

## Details
Previously I was able to find the elements but after react native upgrade to  0.68 i am not able to find the deeply nested elements.
## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `examples` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in examples, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment] 2022-07-13 07:59
You could try out `snapshotMaxDepth` capability https://github.com/appium/appium-xcuitest-driver

**Comment by mykola-mokhnach** [comment] 2022-07-13 08:29
Possible duplicate of https://github.com/appium/appium/issues/14825

Note that setting snapshotMaxDepth to high values in some situations might freeze xctest completely

**Comment by abhijeetkange** [comment] 2022-07-13 09:05
I am using real device for Test Execution(iphone X 15.5) 
and also using appium inspector to find out the elements.

**Comment by abhijeetkange** [comment] 2022-07-13 09:16
check with snapshotMaxDepth capability but no success. 
We have EventCard and inside that there are several elements. 
attached screenshot for reference.
<img width="318" alt="Screenshot 2022-07-13 at 2 45 43 PM" src="https://user-images.githubusercontent.com/50511436/178697808-ce83bfe4-68ac-4ec3-a5d3-43e9f373e7ab.png">

**Comment by mykola-mokhnach** [comment] 2022-07-13 12:15
xctest sets it to `INT_MAX` by default, although we had to limit that value to 50, because xctest daemon freezes while scanning huge  accessibility hierarchies.

**Comment by abhijeetkange** [comment] 2022-07-13 12:54
I tried with 500 limit and it works for me. 
@mykola-mokhnach Thanks for all the help.

**Closed** 2022-07-13 16:34 UTC
Labels: Question, ThirdParty, XCUITest
