### ISSUE TITLE
Appium Data Load Issue

### ISSUE THREAD

**Issue by maxnava** [appium/appium#4585] opened 2015-02-23 22:06 UTC
I've been using Appium for multiple projects. Currently, we faced a new issue -

We have a heavy iOS application with 20+ images in the landing page after logging in.
When we're launching the application using appium, the Simulator tries to load the page, but complete load does not happen, and we only get the Clock loading symbol.

Appium log is also not issuing any errors, but the following warnings are generated:

info: [IOS_SYSLOG_ROW ] Jan 23 12:53:52 C02ML05UFD57 lsd[16467]: LaunchServices: Currently 0 installed placeholders: (
info: [IOS_SYSLOG_ROW ] )

info: [IOS_SYSLOG_ROW ] Jan 23 12:54:03 C02ML05UFD57 mstreamd[16448]: (Note ) PS: Media stream daemon stopping.

info: [IOS_SYSLOG_ROW ] Jan 23 12:54:03 C02ML05UFD57 mstreamd[16448]: (Note ) AS: : Shared Streams daemon has shut down.
info: [IOS_SYSLOG_ROW ] Jan 23 12:54:03 C02ML05UFD57 mstreamd[16448]: (Warn ) mstreamd: mstreamd shutting down.

Are we doing anything wrong?

How can we handle data load, for new screens, in Appium without facing this issue?

**Comment by maxnava** [comment] 2015-02-24 18:26
@jlipps - can you review this issue?

**Comment by maxnava** [comment] 2015-02-25 20:05
Any update on this issue?

Anyone else facing it?

info: [IOS_SYSLOG_ROW ] Feb 23 16:37:28 C02ML05UFD57 mstreamd[25000]: (Note ) PS: Media stream daemon stopping.

info: [IOS_SYSLOG_ROW ] Feb 23 16:37:28 C02ML05UFD57 mstreamd[25000]: (Note ) AS: <MSIOSAlbumSharingDaemon: 0x7ffa4b70aa40>: Shared Streams daemon has shut down.

info: [IOS_SYSLOG_ROW ] Feb 23 16:37:28 C02ML05UFD57 mstreamd[25000]: (Warn ) mstreamd: mstreamd shutting down.

**Comment by cajones17** [comment] 2015-03-05 21:36
Also having this issue, has there been any resolution?

**Comment by maxnava** [comment] 2015-03-05 22:27
No .. never heard back from anyone for a resolution ...

This seems to be a critical issue.

I've redone my application code making sure the data load is not heavy at all. But that is not possible on most of the cases. Issue is not happening, if we are using XCode> Instruments> Automator

So for data load issues, I'm using the Instruments Automator, for automating the iOS applications.

**Comment by eladleb** [comment] 2015-04-02 13:05
I'm also having this issue. It wasn't always like this though, just started last month.. Happens on iOS 8.1, 8.2 both iPhone and iPad.

**Comment by 0x1mason** [comment] 2015-04-02 14:03
@maxnava @eladleb Can either of you send me an application and repro steps? eric@saucelabs.com

Also, can you post more Appium logs to provide context.

**Comment by maxnava** [comment] 2015-04-02 14:56
Well this is what I know based on this issue, as I've faced it for 10+ iOS projects (can't share those apps as it's in-house) ...

1. Issue is faced when app is heavy (either too much data load, or memory load ...) at any particular screen

2. Issue appears when app uses functionalities to access backend DBs ... for me accusing just 100 lines of records ... results in this issue.

Appium log is also not issuing any errors, but the following warnings are generated:

info: [IOS_SYSLOG_ROW ] Jan 23 12:53:52 C02ML05UFD57 lsd[16467]: LaunchServices: Currently 0 installed placeholders: (
info: [IOS_SYSLOG_ROW ] )

info: [IOS_SYSLOG_ROW ] Jan 23 12:54:03 C02ML05UFD57 mstreamd[16448]: (Note ) PS: Media stream daemon stopping.

info: [IOS_SYSLOG_ROW ] Jan 23 12:54:03 C02ML05UFD57 mstreamd[16448]: (Note ) AS: : Shared Streams daemon has shut down.
info: [IOS_SYSLOG_ROW ] Jan 23 12:54:03 C02ML05UFD57 mstreamd[16448]: (Warn ) mstreamd: mstreamd shutting down.

**Comment by eladleb** [comment] 2015-04-02 15:01
@maxnava are you using core data (or restkit+core data) when the data is retrieved from the server?

@0x1mason I'm editing an email for you with the requested details.

**Comment by maxnava** [comment] 2015-04-02 16:11
@eladleb - I'm using core data

**Comment by eladleb** [comment] 2015-04-05 12:53
I'm glad to report that I have a solid lead and an acceptable workaround for this issue.

From my further inspection, it seems that the issue reproduces constantly 
when there is a single **long NSLog print** in the app.

In our app, we had restkit's logs enabled and that triggered long texts. It seems that once Appium reads that text, something bad happens, and it affects the behavior of the app as well.
It always runs fine in Xcode and always crashes with Appium so turning off the logs for the test builds seems like a good workaround for now, and it should probably be resolved within Appium server's code (if that is the case...).

Thanks for the help!

**Comment by jlipps** [comment] 2015-04-06 17:24
@eladleb thanks for the investigation. Can you do a bit more and find out whether this issue also reproduces when using instruments/UI Automation on their own (without Appium)? If it reproduces there, there may not be anything we can do about it within the Appium code itself.

But it's entirely possible Appium chokes somewhere on huge log output.

/cc @0x1mason @imurchie @sebv @Jonahss @bootstraponline I think various users are running into this issue without knowing it (there are no clear symptoms to help diagnose the issue), this is a good troubleshooting note and maybe should be added to our docs?

**Comment by Jonahss** [comment] 2015-04-06 17:29
Could/should we add some sort of analytics or detection of the message size as it passes through appium? Then at least we can see big number in the server logs.

**Comment by 0x1mason** [comment] 2015-04-06 18:26
@jlipps At least according to @maxnava, this doesn't happen without Appium, tho would be helpful to know if @eladleb experiences the same thing.

**Comment by jlipps** [comment] 2015-04-06 19:21
Oh right, missed @maxnava's comment. Looks like something we should be able to handle in appium-instruments or appium-uiauto then.

**Comment by chandrakanth1984** [comment] 2015-04-07 07:34
Hi,

I am facing the same type of issue in simulator when opened with appium,

info: [IOS_SYSLOG_ROW ] Apr  7 15:44:50 PBs-MacBook-Air.local mstreamd[5079]: (Note ) PS: Media stream daemon stopping.

info: [IOS_SYSLOG_ROW ] Apr  7 15:44:50 PBs-MacBook-Air.local mstreamd[5079]: (Note ) AS: <MSIOSAlbumSharingDaemon: 0x7f8bbad0fe00>: Shared Streams daemon has shut down.
info: [IOS_SYSLOG_ROW ] Apr  7 15:44:50 PBs-MacBook-Air.local mstreamd[5079]: (Warn ) mstreamd: mstreamd shutting down.

I am able to open an app with xcode and able to see the screen.

We found that if we have more number of accounts or data to display the above issue is breaking the functionality with appium.

Appium version:1.3.7
Xcode: version 6.2
iOS: 8.2

Please let me know the work around or solution for this problem immediately.

**Comment by eladleb** [comment] 2015-04-07 11:05
I've tested the app with Instruments and found that it depends what you choose to monitor in the process when you select the app.

When choosing System console - everything works fine.
When choosing the Instruments console - It will crash just like it does on Appium.

![image](https://cloud.githubusercontent.com/assets/1809338/7021889/eb61157e-dd2e-11e4-9b1b-1dfca6d437c8.png)
 
@chandrakanth1984 For now, I've worked around this by not printing every line of data to the console as this seems to be the breaking point.

**Comment by 0x1mason** [comment] 2015-04-07 13:20
I believe the problem here is NSLog. I've done some research and I've found what I believe are viable workarounds. Both approaches simply redirect NSLog output.

Please test these workaround and let us know how they work.

### Workaround 1
NSLog is a macro and can be redefined. E.g.,
```objectivec
#ifdef TEST
  #define NSLog(...) _BlackHoleTestLogger(__VA_ARGS__);
#endif // TEST
#ifdef TEST2
  #define NSLog(...) _StdoutTestLogger(__VA_ARGS__);
#endif // TEST2

void _BlackHoleTestLogger(NSString *format, ...) {
    //
}

void _StdoutTestLogger(NSString *format, ...) {
    va_list argumentList;
    va_start(argumentList, format); 
    NSMutableString * message = [[NSMutableString alloc] initWithFormat:format 
                                                arguments:argumentList];

    printf(message);

    va_end(argumentList);
    [message release];
}
```

### Workaround 2
Manually replace the underlying function that NSLog wraps. This method was recommended by Apple in a similar context (https://support.apple.com/kb/TA45403?locale=en_US&viewlocale=en_US)

```objectivec
extern void _NSSetLogCStringFunction(void(*)(const char *, unsigned, BOOL));

static void _GarbageFreeLogCString(const char *message, unsigned length,  
BOOL withSyslogBanner) {
   fprintf(stderr, "%s\\n", message);
}

int main (int argc, const char *argv[]) {
   NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];
   int exitCode;

   setbuf(stderr, NULL);

   _NSSetLogCStringFunction(_GarbageFreeLogCString);
   exitCode = WOApplicationMain(@"Application", argc, argv);
   [pool release];
   return exitCode;
}
```

**Comment by maxnava** [comment] 2015-04-07 15:06
We've stopped using NSLog for our projects and moved to use a personalized logger with the following setups for logging:

typedef enum
{
    kLOG_OFF = 0,
    kLOG_FATAL = 1,
    kLOG_ERROR = 2,
    kLOG_WARN = 3,
    kLOG_INFO = 4,
    kLOG_DEBUG = 5,
    kLOG_TRACE = 6
} LogLevels;

mstreamed issues related to data log gets solved as a result.

Still looking around for solutions related to image load issue (say, 10 images - 500kb each - single screen)...

**Comment by 0x1mason** [comment] 2015-04-07 15:12
@maxnava We have several memory related issues atm and I posted the workaround to the wrong thread.  Apologies.

**Comment by Jonahss** [comment] 2015-04-07 18:01
@eladleb Do you think if we modified the TraceTemplate that appium uses to launch instruments, we could keep instruments from logging as much? There's already an option for providing a custom TraceTemplate

**Comment by chandrakanth1984** [comment] 2015-04-08 12:18
Hi,

We requested developers to give us new app version by disabling the logging means debug option but this did not worked for me still app is hanging and showing the same error as mentioned previously.

For work around we created different data with small accounts and screens are loading good. I do not have any resolution for this because when I try to load app in simulator through xcode all the functionality is good but when I load app in simulator with appium it hangs.

Thanks,
Chandrakanth

**Comment by eladleb** [comment] 2015-04-08 13:21
@Jonahss I'm sorry but I really can't tell - I don't have any real ui automation experience with instruments..

**Comment by maxnava** [comment] 2015-04-08 13:28
@chandrakanth1984 - as a quick check can you verify if you have any active line in the application code with "NSLogger"/"NSLog" or any other logger present...

**Comment by MuratKus** [comment] 2015-07-14 14:52
I checked with my developer and it seems that we have no NSLogger/NSlog in any active line.

**Comment by jlipps** [comment] 2016-02-03 17:44
@maxnava are you still experiencing this issue with the latest versions of appium and ios? (try appium 1.5 beta for example)

**Comment by maxnava** [comment] 2016-02-07 17:07
Yup .. we are still facing this issue.

We started using other automation applications now, which dont give us these issues. But we are trying out every new version of appium, when they are released.

**Comment by midopa** [comment] 2016-06-01 20:57
Repros for me when opening a browser link from an app
Appium 1.5.2
XCode 6
iOS simulator 8.4

**Comment by mykola-mokhnach** [comment] 2017-11-27 06:56
Closed as obsolete

**Closed by mykola-mokhnach** 2017-11-27 06:56 UTC
Labels: Bug, iOS, P2
