### ISSUE TITLE
[iOS][W3C] Matched W3C error code 'unknown error' to UnknownError when trying to inspect elements on iOS

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#15434] opened 2021-05-28 07:32 UTC
## The problem
[W3C] Matched W3C error code 'unknown error' to UnknownError when trying to inspect elements on iOS

## Environment

* Appium version (or git revision) that exhibits the issue: Appium Desktop 1.20.2
* Desktop OS/version used to run Appium: M1 Mac Big Sur 11.4
* Node.js version (unless using Appium.app|exe): v15.13.0
* Npm or Yarn package manager: 7.8.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real device (iPhone 12 ios: 14.6), Xcode 12.5

## Details
Application is installed successfully, starts successfully but when tries to get the elements error is triggered. 

## Link to Appium logs
https://gist.github.com/vjmaiky/be81babf0f3277d3da892eba0f97d251

## Code To Reproduce Issue [ Good To Have ]
```
{
  "platformName": "ios",
  "platformVersion": "14",
  "automationName": "XCUITest",
  "deviceName": "iphone12",
  "udid": "00008101-001E70440232001E",
  "newCommandTimeout": 600,
  "wdaLaunchTimeout": "120000",
  "app": "/Users/lmihai/Desktop/FlyNet.ipa"
}
```

**Comment by mykola-mokhnach** [comment] 2021-05-28 08:04
Duplicate of https://github.com/appium/appium/issues?q=is%3Aissue+screenshotDataForQuality+is%3Aclosed

**Closed by mykola-mokhnach** 2021-05-28 08:04 UTC
