### ISSUE TITLE
Error during installation process -TimeoutError

### ISSUE THREAD

**Issue by jxm0418** [appium/appium#13218] opened 2019-09-10 20:28 UTC
## The problem

App could not be installed when i use appium@beta version 1.15.0-beta.1, I got the error during installation process on the real device- TimeoutError: operation timed out

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable): 1.14.2
* Desktop OS/version used to run Appium: Mac OS 10.14.6
* Node.js version (unless using Appium.app|exe): v12.9.0
* Npm or Yarn package manager: 6.11.2
* Mobile platform/version under test: ios 13 & ios 12.4
* Real device or emulator/simulator: Real Device

## Link to Appium logs

https://gist.github.com/jxm0418/e999d612c49d8171363721c8aae80af7

**Comment by mykola-mokhnach** [comment] 2019-09-10 21:13
Duplicate of https://github.com/appium/appium/issues/13180

**Closed by mykola-mokhnach** 2019-09-10 21:13 UTC

**Comment by jxm0418** [comment] 2019-09-10 21:30
@mykola-mokhnach                                                                                                                             13180 issue had a different Error during installation process - "Path must be a string"                            This issue had error  "TimeoutError: operation timed out" during the installation process                          Are both the same?

**Comment by gh0st2sh3ll** [comment] 2019-09-11 07:39
Hi @jxm0418 issue #13180 got anther error first, but after updating node your error ("TimeoutError: operation timed out") emerged there as well.
