### ISSUE TITLE
Error: 'null' cannot be coerced to a valid version number

### ISSUE THREAD

**Issue by Suban5** [appium/appium#12406] opened 2019-03-29 09:05 UTC
## The problem

I am trying to run the automation script in the real ios device. I am getiing the  **'null' cannot be coerced to a valid version number** error. 

## Environment

* Appium server version : 1.12.1
* Last Appium version that did not exhibit the issue : 1.10.0
* Mac OS/version used to run Appium: macOs Mojave 10.14.3
* Node.js version: v11.7.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: ios/ iphone 7/ 12.1.4
* Real device or emulator/simulator: real device

## Details

I have used following DesiredCapabilities:

```
DesiredCapabilities caps = new DesiredCapabilities();
caps.setCapability(MobileCapabilityType.UDID, udid);
caps.setCapability(MobileCapabilityType.NO_RESET, noReset);
caps.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 600);
caps.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.IOS);
caps.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone");
caps.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
caps.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
caps.setCapability("xcodeOrgId", myXcodeOrgId);
caps.setCapability("xcodeSigningId", "iPhone Developer");
caps.setCapability("showXcodeLog", true);
driver = new IOSDriver(new URL("http://" + host + ":" + port + "/wd/hub"), caps);
```

## Link to Appium logs

https://gist.github.com/Suban5/dfec05b73a8cd0b061b92d3aca15671c

**Comment by mykola-mokhnach** [comment] 2019-03-29 12:16
Duplicate of https://github.com/appium/appium/issues/12405

**Closed by mykola-mokhnach** 2019-03-29 12:16 UTC
