### ISSUE TITLE
Unable to install android and ios drivers at the same time in 2.0.0-beta.27

### ISSUE THREAD

**Issue by dlanaghen** [appium/appium#16729] opened 2022-04-07 16:09 UTC
## The problem
Between beta 25 and beta 27, a node_modules was added in the .appium directory to store the drivers.  I installed the uiautomator2 driver and then installed the xcuitest driver.  After installing the second driver, the uiautomator2 driver was no longer present in the node_modules directory.

## Environment

* Appium version 2.0.0-beta.27
* Last Appium version that did not exhibit the issue: multiple drivers worked in version 25  (I did not test 26)
* Desktop OS/version used to run Appium:  Mac OS
* Node.js version (unless using Appium.app|exe):  v17.7.2
* Npm or Yarn package manager: 8.5.2
* Mobile platform/version under test: android and ios
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
mac /tmp % `appium --version`
**2.0.0-beta.27**

### node_modules has uiautomator2 driver
mac ~ % `cd .appium`
mac .appium %` ls`
**node_modules	package.json	webdriveragent**
mac .appium % `ls node_modules`
**appium-uiautomator2-driver**
mac .appium % `appium driver list --installed`
**✔ Listing installed drivers
 uiautomator2@2.0.6 [installed (NPM)]**

### Install xcuitest driver
mac .appium % `appium driver install xcuitest`
**✔ Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver'
Driver xcuitest@4.3.5 successfully installed
-automationName: XCUITest
-platformNames: ["iOS","tvOS"]**

### Now uiautomator2 driver is missing in node_modules
mac .appium % `ls node_modules`
**appium-xcuitest-driver**

## Link to Appium logs

Logs are not relevant

## Code To Reproduce Issue [ Good To Have ]

See Details

**Comment by mykola-mokhnach** [comment] 2022-04-07 16:44
cc @boneskull

**Comment by boneskull** [comment] 2022-04-07 19:31
this should have been fixed via 0bbec13d1e386b2fdf3f9cdcb43da78d6834f28f.  I think we need to release it?  @jlipps

**Comment by boneskull** [comment] 2022-04-07 19:32
duplicate of #16674

**Closed by boneskull** 2022-04-07 19:32 UTC
Labels: v2

**Comment by jlipps** [comment] 2022-04-07 23:01
ah OK. I'll do a release now.

**Comment by jlipps** [comment] 2022-04-07 23:13
beta 28 is released
