### ISSUE TITLE
DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.WebDriverAgentRunner-Runner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running." UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(

### ISSUE THREAD

**Issue by Kitty2014** [appium/appium#9801] opened 2017-12-15 09:35 UTC
## The problem
After running devices the error shown
DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.WebDriverAgentRunner-Runner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running." UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(

**Comment by mykola-mokhnach** [comment] 2017-12-15 09:45
Duplicate of https://github.com/facebook/WebDriverAgent/issues/355

**Closed by mykola-mokhnach** 2017-12-15 09:45 UTC
