### ISSUE TITLE
WebDriver Agent Runner building on XCode12.3 is failed with error  Building for iOS, but the linked and embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator

### ISSUE THREAD

**Issue by narasimhanukala** [appium/appium#14953] opened 2020-12-16 10:40 UTC
## The problem

This issue happens while Building WebDriverAgent Runner on   XCode 12.3 and iOS14.3

## Environment

Appium version (or git revision) that exhibits the issue:1.18.3
Desktop OS/version used to run Appium:1.18.1
Node.js version (unless using Appium.app|exe):10.16.3
Npm or Yarn package manager:6.9.0
Mobile platform/version under test: iOS 14.3
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe:both

## Details

while trying to build and launch the Webdriver Agent Runner app using XCode 12.3 on iPhone connected to system, 
XCode build failed with below errors:

Building for iOS, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator

Building for iOS, but the linked and embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator

## Link to Appium logs

NA

## Code To Reproduce Issue [ Good To Have ]

Click on Run icon on Xcode which builds and then run the current scheme
then Build gets failed.

on Previous XCode i.e. 12.2 version this was not noticed.
Kindly help me on resolving this issue.

**Comment by mykola-mokhnach** [comment] 2020-12-16 10:41
Duplicate of https://github.com/appium/appium/issues/14952

**Closed by mykola-mokhnach** 2020-12-16 10:41 UTC
