### ISSUE TITLE
Encountered internal error running command: TypeError: Cannot read property 'getLogs' of undefined

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#8550] opened 2017-05-27 01:20 UTC
## The problem

Getting error while trying to retrieve the performance logs

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Node.js version (unless using Appium.app|exe): v7.5.0
* Mobile platform/version under test: iOS 10.3.2
* Real device or emulator/simulator: Real Device

Getting 

Gist to Appium [logs](https://gist.github.com/pavanbachu0604/4ef5bef010627aeeddf9d2b0c8e4c9c3)

## Code To Reproduce Issue [ Good To Have ]
		try {
			Set<String> logTypes = driver.manage().logs().getAvailableLogTypes();
			 Logs logs = driver.manage().logs();
			logTypes.stream().forEach(logType -> {
					if(logType.equals("performance"))
					{
						System.out.println("logType=" + logType);
						LogEntries logEntries = logs.get(logType);
						List<LogEntry> all = logEntries.getAll();
						all.forEach(entry -> {
							System.out.println(entry.getLevel());
							System.out.println(entry.getMessage());
							System.out.println(entry.getTimestamp());
							System.out.println(entry.toMap());
							System.out.println(entry);
						});
					} 
				});
						
	}catch(Exception e){
		logger.info("Failed");
	}

**Comment by imurchie** [comment] 2017-05-27 04:15
I am fixing the error message for this.

But the root of the problem is that performance logging is only available for safari tests (and in a webview context).

**Comment by pavanbachu0604** [comment] 2017-05-29 22:30
Will it be fixed in a beta version of Appium and also is the above mentioned way, the correct way to capture the logs ?

**Comment by imurchie** [comment] 2017-05-30 17:00
The error message will be fixed, yes. But there is _no_ way currently to get any performance logs outside of a Safari session.

**Comment by pavanbachu0604** [comment] 2017-05-30 17:21
I am talking about getting the performance logs for WebView of the
application


On Tue, May 30, 2017 at 1:00 PM, Isaac A. Murchie <notifications@github.com>
wrote:

> The error message will be fixed, yes. But there is *no* way currently to
> get any performance logs outside of a Safari session.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_appium_appium_issues_8550-23issuecomment-2D304942554&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=GrVyjk9esLjbV-UuEWevVPxUeLcsCbkcwb9nvBHhjgE&m=bp_smnmbLDLfgioZfbgnOJIe-An3m3Hj0cNy11RSdbA&s=-XDFZmNpHn2ZetiPsEteFjodvZ8LlR8vke4CfWzcZCU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AUPSxOldGs-2DVspHbstxA-5FNZPQQtV24-5Fiks5r-5FEsugaJpZM4NoMGh&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=GrVyjk9esLjbV-UuEWevVPxUeLcsCbkcwb9nvBHhjgE&m=bp_smnmbLDLfgioZfbgnOJIe-An3m3Hj0cNy11RSdbA&s=4xCPTIWj1MjFDnpRNQaIok-PdGLTZKx6NOw_sABEW2A&e=>
> .
>



-- 
Thanks
Pavan Bachu

**Comment by imurchie** [comment] 2017-05-30 17:36
Then yes, that is the way to get it. As in https://github.com/appium/appium-ios-driver/blob/master/test/e2e/safari/webview/basic-specs.js#L287-L301

**Closed** 2017-07-21 20:00 UTC
