### ISSUE TITLE
DrugTo option is not working on 1.18.3 appium

### ISSUE THREAD

**Issue by chuklov** [appium/appium#15037] opened 2021-01-20 10:06 UTC
## The problem

Using Appium for automation from Intellij IDEA I have found that starting 1.18.3 appium I cannot use the following commands: 

`(new TouchAction(driver)).press(PointOption.point(162,2)).moveTo(PointOption.point(162,400)).release().perform();`

```
Map<String, Object> params = new HashMap<>();
params.put("duration", 0.2);
params.put("fromX", 10);
params.put("fromY", 120);
params.put("toX", 10);
params.put("toY", 220);
driver.executeScript("mobile: dragFromToForDuration", params);
```

Both of them returns null:

```
[HTTP] --> POST /wd/hub/session/f02befff-e6ae-4958-8cba-7e6478ba4612/execute/sync
[HTTP] {"script":"mobile: dragFromToForDuration","args":[{"duration":1,"fromX":10,"toX":10,"fromY":10,"toY":320}]}
[debug] [W3C (f02befff)] Calling AppiumDriver.execute() with args: ["mobile: dragFromToForDuration",[{"duration":1,"fromX":10,"toX":10,"fromY":10,"toY":320}],"f02befff-e6ae-4958-8cba-7e6478ba4612"]
[debug] [XCUITest] Executing command 'execute'
[XCUITest] Proxying to WDA with an unknown route: POST /wda/dragfromtoforduration
[debug] [WD Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://127.0.0.1:52799/session/7B1745E7-C3BB-440F-991C-D14890ACB0F3/wda/dragfromtoforduration] with body: {"duration":1,"fromX":10,"fromY":10,"toX":10,"toY":320}
[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"7B1745E7-C3BB-440F-991C-D14890ACB0F3"}
[debug] [W3C (f02befff)] Responding to client with driver.execute() result: null
[HTTP] <-- POST /wd/hub/session/f02befff-e6ae-4958-8cba-7e6478ba4612/execute/sync 200 2899 ms - 14
```

```
[HTTP] --> POST /wd/hub/session/f02befff-e6ae-4958-8cba-7e6478ba4612/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"x":160,"y":5}},{"action":"moveTo","options":{"x":160,"y":400}},{"action":"release","options":{}}]}
[debug] [W3C (f02befff)] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":160,"y":5}},{"action":"moveTo","options":{"x":160,"y":400}},{"action":"release","options":{}}],"f02befff-e6ae-4958-8cba-7e6478ba4612"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"x":160,"y":5})-moveTo(options={"x":160,"y":400})-release(options={})
[debug] [WD Proxy] Proxying [POST /wda/touch/perform] to [POST http://127.0.0.1:52799/session/7B1745E7-C3BB-440F-991C-D14890ACB0F3/wda/touch/perform] with body: {"actions":[{"action":"press","options":{"x":160,"y":5}},{"action":"moveTo","options":{"x":160,"y":400}},{"action":"release","options":{}}]}
[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"7B1745E7-C3BB-440F-991C-D14890ACB0F3"}
[debug] [W3C (f02befff)] Responding to client with driver.performTouch() result: null

```

Same commands used in Appium Desktop works fine. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.3
* Last Appium version that did not exhibit the issue (if applicable): 1.17
* Desktop OS/version used to run Appium: 1.18
* Node.js version (unless using Appium.app|exe):  15.0.1
* Npm or Yarn package manager: npm@7.0.3 
* Mobile platform/version under test: ios 
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI 

Any suggestions on how to make them work?

**Comment by mykola-mokhnach** [comment] 2021-01-20 10:20
Duplicate of https://github.com/appium/appium/issues/12339

Also consider using W3C actions instead.

**Closed by mykola-mokhnach** 2021-01-20 10:20 UTC
