### ISSUE TITLE
Cannot connect Appium to Android Studio.

### ISSUE THREAD

**Issue by hugommsilva1** [appium/appium#14202] opened 2020-04-20 15:42 UTC
Encountered internal error running command: Error: The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.

![image](https://user-images.githubusercontent.com/64027942/79770883-e52a3a80-8325-11ea-845d-1c2e4f3a2937.png)

[appium-server-logs.txt](https://github.com/appium/appium/files/4504552/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment] 2020-04-20 16:45
Duplicate of https://github.com/appium/appium/issues/14001

**Closed by mykola-mokhnach** 2020-04-20 16:45 UTC
