### ISSUE TITLE
NPM install with error because of authorize-ios

### ISSUE THREAD

**Issue by ltpquang** [appium/appium#14961] opened 2020-12-21 06:47 UTC
## The problem

Installing Appium with npm raises error when chmod `authorize-ios`, since the file is not distributed anymore.

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ltpquang/.npm/_logs/2020-12-21T06_41_31_466Z-debug.log
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* Desktop OS/version used to run Appium: macOS 11.1
* Npm or Yarn package manager: 7.0.15

**Comment by mykola-mokhnach** [comment] 2020-12-21 07:02
Duplicate of https://github.com/appium/appium/issues/14901

**Closed by mykola-mokhnach** 2020-12-21 07:02 UTC
