### ISSUE TITLE
Issue on iOS with app installation

### ISSUE THREAD

**Issue by gkvappium** [appium/appium#13483] opened 2019-10-24 11:17 UTC
## The problem

Error when installing the .ipa from appium. 

## Environment

* Appium version (or git revision) that exhibits the issue:1.15
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:10.13.6
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:12.4.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:Appium CLI

## Details

[debug] [XCUITest] App is present

[debug] [BaseDriver] Event 'resetStarted' logged at 1571915311522 (16:38:31 GMT+0530 (IST))

[debug] [XCUITest] Reset: fullReset not set. Leaving as is

[debug] [BaseDriver] Event 'resetComplete' logged at 1571915311522 (16:38:31 GMT+0530 (IST))

[debug] [XCUITest] Crash reports root '/Users/macuser/Library/Logs/CrashReporter/MobileDevice/iPhone' does not exist. Got nothing to gather.

[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1571915311773 (16:38:31 GMT+0530 (IST))

[XCUITest] Setting up real device

[debug] [XCUITest] Verifying application platform

[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]

[debug] [XCUITest] Installing '/var/folders/50/31cr3h5n0gn9vs73zn3d08900000gt/T/2019924-7307-i46f7r.jhrlt/Payload/control.app' on device with UUID '30cbd11ca498428a9a19e3b4249cb38b8a41ea3d'...

[DevCon Factory] Releasing connections for 30cbd11ca498428a9a19e3b4249cb38b8a41ea3d device on any port number

[DevCon Factory] No cached connections have been found

[debug] [BaseDriver] Event 'newSessionStarted' logged at 1571915342085 (16:39:02 GMT+0530 (IST))

[debug] [MJSONWP] Encountered internal error running command: Error: Could not install app: 'Couldn't push '/var/folders/50/31cr3h5n0gn9vs73zn3d08900000gt/T/2019924-7307-i46f7r.jhrlt/Payload/control.app/AppIcon20x20@2x.png' within the timeout 30000ms'
[debug] [MJSONWP]     at IOSDeploy.install (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:41:13)

[debug] [MJSONWP]     at <anonymous>

Session info 
undefined
Could not resolve device density. Please provide offset in appium config
Appium driver has started successfully!
[HTTP] <-- POST /wd/hub/session 500 34455 ms - 326
[HTTP] 

@mykola-mokhnach ,could you please take a look?

**Comment by mykola-mokhnach** [comment] 2019-10-24 11:55
Duplicate of https://github.com/appium/appium/issues/13330
Can the same app be installed using ios-deploy?

**Closed by mykola-mokhnach** 2019-10-24 11:55 UTC

**Comment by gkvappium** [comment] 2019-10-25 06:50
Hi @mykola-mokhnach ,

The application can be installed without any problem using ios-deploy (ios-deploy -b /Users/macuser/Desktop/CAP-6354/e2e/IOS_ipa/control.ipa)

[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 65%] InstallingEmbeddedProfile
[ 70%] VerifyingApplication
[ 75%] CreatingContainer
[ 80%] InstallingApplication
[ 85%] PostflightingApplication
[ 90%] SandboxingApplication
[ 95%] GeneratingApplicationMap
[100%] Installed package /Users/macuser/Desktop/CAP-6354/e2e/IOS_ipa/control.ipa

**Comment by gkvappium** [comment] 2019-10-25 09:58
Hi @mykola-mokhnach ,

Is there any workaround for this issue? I can install it manually via the command line using ios-deploy. Not sure why there is a timeout happening from Appium

Thanks
