### ISSUE TITLE
Unable to install uiautomator2 . Getting error massage. Please HELP

### ISSUE THREAD

**Issue by davidga2007** [appium/appium#17294] opened 2022-07-31 23:42 UTC
appium version 2.0.0-beta.41

C:\Users\david>appium driver install UIAutomator2
Error: × Could not resolve driver; are you sure it's in the list of supported drivers? ["uiautomator2","xcuitest","youiengine","windows","mac","mac2","espresso","tizen","flutter","safari","gecko"]

C:\Users\david>npm appium driver install uiautomator2
Unknown command: "appium"

To see a list of supported npm commands, run:
  npm help

C:\Users\david>appium driver install uiautomator2
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code 1.

STDOUT:
STDERR:
npm ERR! code 1
npm ERR! path C:\Users\david\AppData\Roaming\npm\node_modules\appium
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\david\AppData\Local\Temp\prepare-1f3f4e63.cmd
npm ERR! > appium@2.0.0-beta.41 build
npm ERR! > babel lib --root-mode=upward --out-dir=build/lib
npm ERR! 'babel' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "C:\\WINDOWS\\system32\\cmd.exe /d /s /c C:\\Users\\david\\AppData\\Local\\Temp\\prepare-1f3f4e63.cmd\n> appium@2.0.0-beta.41 build\n> babel lib --root-mode=upward --out-dir=build/lib\n'babel' is not recognized as an internal or external command,\r\noperable program or batch file."
  }
}
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\david\AppData\Local\npm-cache\_logs\2022-07-31T23_37_59_556Z-debug-0.log

**Comment by KazuCocoa** [comment] 2022-08-01 04:36
Please fill out the issue template. Possible duplicate of https://github.com/appium/appium/issues/17287

**Comment by boneskull** [comment] 2022-08-01 18:51
dupe of #17287

**Closed by boneskull** 2022-08-01 18:51 UTC
Labels: NeedsInfo

**Comment by davidga2007** [comment] 2022-08-02 02:44
Thank you @boneskull and @KazuCocoa for your response. From the original bug comments I was able to install uiautomator2 driver using node version 14.20.0 and npm version 6.14.17

**Comment by S1saravanan** [comment] 2022-11-10 07:55
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev appium-uiautomator2-driver --json' failed with code null.

STDOUT:


STDERR:



Getting this error when i install driver please tell me what should i do?

**Comment by KazuCocoa** [comment] 2022-11-10 08:19
if you meant https://github.com/appium/appium/issues/17761 , your env may have another appium v1 dependency somewhere as https://github.com/appium/appium/issues/17614

**Comment by manikandansarvesh** [comment] 2023-04-29 11:10
@KazuCocoa  unable to update the appium driver xcuitest 

Logs for your reference


appium driver update xcuitest
✔ Checking if driver 'xcuitest' is updatable
✔ Checking if driver 'xcuitest' needs an update
⠋ Updating driver 'xcuitest' from 4.16.6 to 4.25.1⠋ Installing 'xcuitest' using ✖ Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver@4.25.1'
✖ Updating driver 'xcuitest' from 4.16.6 to 4.25.1
ℹ Update report:
✖   - 'xcuitest' failed to update: Error: ✖ Encountered an error when installing package: npm command 'install --save-dev appium-xcuitest-driver@4.25.1 --json' failed with code 190.

STDOUT:
{
  "error": {
    "code": "ENOTEMPTY",
    "summary": "ENOTEMPTY: directory not empty, rename '/Users/maniswa/node_modules/appium-dashboard' -> '/Users/maniswa/node_modules/.appium-dashboard-keMZ02Mz'",
    "detail": ""
  }
}

STDERR:
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /Users/maniswa/node_modules/appium-dashboard
npm ERR! dest /Users/maniswa/node_modules/.appium-dashboard-keMZ02Mz
npm ERR! errno -66
npm ERR! ENOTEMPTY: directory not empty, rename '/Users/maniswa/node_modules/appium-dashboard' -> '/Users/maniswa/node_modules/.appium-dashboard-keMZ02Mz'

npm ERR! A complete log of this run can be found in: /Users/maniswa/.npm/_logs/2023-04-29T11_05_13_934Z-debug-0.log

**Comment by SivaSurisetty** [comment] 2023-07-11 10:58
Uninstall Appium version 1 and then remove .appium folder from C:\Users\{user}\

**Comment by dieselTbo** [comment] 2023-11-21 14:30
[bug: Appium 2 fails to install drivers · Issue #18006 · appium/appium (github.com)](https://github.com/appium/appium/issues/18006)
[Unable to Install Chromium driver · Issue #99 · appium/appium-chromium-driver (github.com)](https://github.com/appium/appium-chromium-driver/issues/99)

two url solve this problem

**Comment by km-gupta** [comment] 2024-11-02 08:06
> appium version 2.0.0-beta.41
> 
> C:\Users\david>appium driver install UIAutomator2 Error: × Could not resolve driver; are you sure it's in the list of supported drivers? ["uiautomator2","xcuitest","youiengine","windows","mac","mac2","espresso","tizen","flutter","safari","gecko"]
> 
> C:\Users\david>npm appium driver install uiautomator2 Unknown command: "appium"
> 
> To see a list of supported npm commands, run: npm help
> 
> C:\Users\david>appium driver install uiautomator2 × Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver' Error: × Encountered an error when installing package: npm command 'install --save-dev --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code 1.
> 
> STDOUT: STDERR: npm ERR! code 1 npm ERR! path C:\Users\david\AppData\Roaming\npm\node_modules\appium npm ERR! command failed npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\david\AppData\Local\Temp\prepare-1f3f4e63.cmd npm ERR! > appium@2.0.0-beta.41 build npm ERR! > babel lib --root-mode=upward --out-dir=build/lib npm ERR! 'babel' is not recognized as an internal or external command, npm ERR! operable program or batch file. { "error": { "code": 1, "summary": "command failed", "detail": "C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\david\AppData\Local\Temp\prepare-1f3f4e63.cmd\n> appium@2.0.0-beta.41 build\n> babel lib --root-mode=upward --out-dir=build/lib\n'babel' is not recognized as an internal or external command,\r\noperable program or batch file." } } npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\david\AppData\Local\npm-cache_logs\2022-07-31T23_37_59_556Z-debug-0.log




This is because, you may not set the below path in environment variable.
![image](https://github.com/user-attachments/assets/8fcd5f4c-11ea-4c1c-8166-fe859feb49be)
![image](https://github.com/user-attachments/assets/bc11b9f0-f268-42c1-a090-b4f39ff32884)

This is work for me. May it will work for you also.
