### ISSUE TITLE
How to handle Prompt in Hybrid App ?

### ISSUE THREAD

**Issue by ios-dev-newbie** [appium/appium#9899] opened 2018-01-03 05:41 UTC
## The problem
My App is developed in a Cordova. I wanted to automate it but facing a problem while handling the Prompt. How I can handle it.

## Environment

* Appium version 1.7.1
* Desktop OS/version used to run Appium: Mac OS 10.12.6
* Node.js version (unless using Appium.app|exe): v9.3.0
* Mobile platform/version under test: iPhone 6s with iOS 10.3.3
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
Not able to handle the prompt in iOS. I can handle it in Android with the help of Xpath.
Also How to have a single script for android as well as iOS.

## Link to Appium logs
[Appium logs](https://gist.github.com/ios-dev-newbie/a03b313be3ea4e23b5c524356e8954ba)

## Code To Reproduce Issue [ Good To Have ]

[Code to reproduce issue] (https://gist.github.com/ios-dev-newbie/bbded71293df462bf0219e5da9586438)

**Comment by mykola-mokhnach** [comment] 2018-01-03 06:47
try driver.manage.alert.accept(). If it does not work then it's a duplicate of https://github.com/appium/appium/issues/9405

**Comment by ios-dev-newbie** [comment] 2018-01-03 07:21
It is a prompt of javascript where user enter the values. If we use driver.manage.alert.accept() how can we send the values?

**Comment by mykola-mokhnach** [comment] 2018-01-03 15:28
There is `/wd/hub/session/:sessionId/alert/text` / `/wd/hub/session/:sessionId/alert_text` endpoints on the server for such purpose. Please use Appium forum to ask questions

**Closed** 2018-01-03 15:28 UTC
Labels: Question
