### ISSUE TITLE
Unable to launch WebDriverAgent  for Xcode 11.3 with iOS 14.3 even i have iOS14.3 files device support in Xcode 11.3  

### ISSUE THREAD

**Issue by abdullahalmohareb** [appium/appium#14979] opened 2020-12-27 12:02 UTC
## The problem

Unable to launch WebDriverAgent 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): 15.5.0
* Npm or Yarn package manager: 7.3.0
* Mobile platform/version under test: iOS 14.3 
* Real device or emulator/simulator: real device

## Details

NotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: **Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65**
xcodebuild error message:

2020-12-27 14:52:53.530 xcodebuild[5176:34705] [MT] IDETestOperationsObserverDebug: (F426490A-567B-42F1-8BFA-162DEC3521CC) Failed to make test runner session:
Error Domain=com.apple.dt.xctest.error Code=9 "Unable to connect to test manager on 8680003000-001625fd009998E" UserInfo={NSLocalizedDescription=Unable to connect to test manager on 8680003000-001625fd009998E NSUnderlyingError=0x7fc5f98ad760 {Error Domain=XCTMobileDeviceFramework Code=34 "The service is invalid." UserInfo={NSLocalizedDescription=The service is invalid.}}}
2020-12-27 14:52:53.704 xcodebuild[5176:34705] [MT] DTDKRemoteDeviceConnection: Failed to start Instruments daemon on device “00008020-001625102E81002E”: Error Domain=com.apple.dtdevicekit Code=-402653150 "An error was encountered while attempting to communicate with this device. (The service is invalid.)" UserInfo={NSLocalizedFailureReason=Please try rebooting and reconnecting the device.

**Comment by mykola-mokhnach** [comment] 2020-12-27 12:20
Duplicate of https://github.com/appium/appium/issues/14952

**Closed by mykola-mokhnach** 2020-12-27 12:20 UTC

**Comment by abdullahalmohareb** [comment] 2020-12-27 16:41
i solved my issue with this #14952
