### ISSUE TITLE
Not able to swipe in ios using appium 1.9.1 and java client 6.1.0

### ISSUE THREAD

**Issue by Ashwini12345** [appium/appium#11492] opened 2018-10-07 16:15 UTC
## Environment

* Appium version (or git revision) that exhibits the issue:1.9.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:10.13.6
* Node.js version (unless using Appium.app|exe):v8.9.1
* Mobile platform/version under test:ios
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:1.9.1

## Details

i am using touchAction and giving the cordinates to press and move but not able to swipe.

## Link to Appium logs
[
[appium-server-logs.txt](https://github.com/appium/appium/files/2454077/appium-server-logs.txt)
](url)
pageSouce

[pagesource.txt](https://github.com/appium/appium/files/2454079/pagesource.txt)

## Code To Reproduce Issue [ Good To Have ]
<img width="960" alt="screen shot 2018-10-07 at 9 37 47 pm" src="https://user-images.githubusercontent.com/17825264/46583837-10b63e80-ca7a-11e8-9735-4746c0443a95.png">

**Comment by mykola-mokhnach** [comment] 2018-10-07 16:57
Duplicate of https://github.com/appium/appium/issues/11181

**Closed by mykola-mokhnach** 2018-10-07 16:57 UTC

**Comment by Ashwini12345** [comment] 2018-10-10 15:56
@mykola-mokhnach i followed the solution provided #11181 but still no luck, Please help in resolving this issue as its blocked our testing.

**Comment by mykola-mokhnach** [comment] 2018-10-10 16:42
Please use Appium forum for questions. This is not a bug in server code

**Comment by manishboricha** [comment] 2018-12-19 13:01
@Ashwini12345 
Hope this helps because its working fine for me

Appium : 1.9.1
Device : iPhone X - 11.4.1
io.appium - 6.1.0

https://medium.com/@manishboricha308/swipe-doesnt-work-on-appium-1-9-1-40fe80a2cd9d
