### ISSUE TITLE
App keep reopening back and forth in real device with Appium webdriveragent session error

### ISSUE THREAD

**Issue by zicostian** [appium/appium#13056] opened 2019-08-09 13:33 UTC
## The problem

Hi Everyone, i really need your help here. So did a setup on my automation prerequisite requirement for iOS real device, along with the webdriveragent as well. The problem is when i run it on Appium i got this error below:

"An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device."

What happen on my real device is, the app is launched but keep reopening or looping in open and close back and forth. While on my macbook, the appium screen is not launched the app for the selector screen.

## Environment

* Appium version 1.12.0
* Xcode 10.2.1
* Desktop OS: macOS Mojave 10.14.3
* Mobile platform iPhone X, iOS 11.2.6

## Link to Appium logs

Here's the [GIST](https://gist.github.com/zicostian/3d8610290520c4543aca71e3134247fb)
for the complete Appium logs

Please help me resolve this issue, thank you.

**Comment by mykola-mokhnach** [comment] 2019-08-09 13:48
Possible duplicate of https://github.com/appium/appium/issues/12848

**Comment by mykola-mokhnach** [comment] 2019-08-13 10:15
Have you checked the related issue? Does it work now? Also, it always make sense to upgrade the server to the most recent version

**Closed** 2019-08-16 05:10 UTC
Labels: NeedsInfo
