### ISSUE TITLE
How to solve this problem `[XCUITest] Connection to WDA timed out`

### ISSUE THREAD

**Issue by KuKiSiNi77** [appium/appium#8882] opened 2017-07-20 03:24 UTC
## The problem

Jenkins + appium +cucumber

the test ran for hours,the `[XCUITest] Connection to WDA timed out` randomly appear.

if can't absolutely handle the problem,please give me some suggest how to avoid!

Thanks !

## Environment

* Appium version (or git revision) that exhibits the issue:v1.6.5
* Desktop OS/version used to run Appium:  macOS 10.12.5
* Node.js version (unless using Appium.app|exe):v8.1.2
* Real device or emulator/simulator: Real device

```
[Appium]   platformVersion: '10.3.0'
[Appium]   platformName: 'iOS'
[Appium]   launchTimeout: 500000
[debug] [XCUITest] XCUITestDriver version: 2.28.2
[debug] [XCUITest] Xcode version set to '8.3.3' 
[debug] [XCUITest] iOS SDK Version set to '10.3'
```

## Details

About `[XCUITest] Connection to WDA timed out`, it appeared twice. It all that just to fount element to operate(click or getText etc).normally,the log`[XCUITest] Connection to WDA timed out` is closely followed by another log `[iProxy] recv failed: Operation not permitted` and `[iProxy] Error connecting to device!`

### First appearance

```
[HTTP] <-- GET /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/context 200 3 ms - 84 
[HTTP] --> POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/elements {"using":"name","value":"toolbar_button_searchCustomer"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["name","toolbar_button_searchCustomer","4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/F426EBF1-DA65-4F61-83DA-29B4D811E64E/elements] with body: {"using":"name","value":"toolbar_button_searchCustomer"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"31339091-8F2D-447B-A962-75BF094C50AE","type":"XCUIElementTypeButton","label":"toolbar_button_searchCustomer"}],"sessionId":"F426EBF1-DA65-4F61-83DA-29B4D811E64E","status":0}
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"31339091-8F2D-447B-A962-75BF094C50AE","type":"XCUIElementTypeButton","label":"toolbar_button_searchCustomer"}]
[HTTP] <-- POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/elements 200 2669 ms - 195 
[HTTP] --> POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/timeouts {"type":"implicit","ms":1000}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",1000,"4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] Set implicit wait to 1000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/timeouts 200 3 ms - 76 
[HTTP] --> POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/element/31339091-8F2D-447B-A962-75BF094C50AE/click {"id":"31339091-8F2D-447B-A962-75BF094C50AE"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/element/31339091-8F2D-447B-A962-75BF094C50AE/click] to [POST http://localhost:8100/session/F426EBF1-DA65-4F61-83DA-29B4D811E64E/element/31339091-8F2D-447B-A962-75BF094C50AE/click] with body: {"id":"31339091-8F2D-447B-A962-75BF094C50AE"}
[debug] [XCUITest] Log file for xcodebuild test: /Users/repeatlink/Library/Developer/Xcode/DerivedData/WebDriverAgent-hbxngkiyhlinsebzimsacejgzfhp/Logs/Test/810D5ED4-C1BA-4BD6-BEA0-CE422DAAE542/Session-WebDriverAgentRunner-2017-07-19_214356-pfbTjV.log
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: socket hang up
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:385:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/.5.8.24@babel-runti[HTTP] <-- POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/element/31339091-8F2D-447B-A962-75BF094C50AE/click 500 6827 ms - 280 
me/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[HTTP] --> GET /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53"]
[debug] [XCUITest] Executing command 'getScreenshot'
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/F426EBF1-DA65-4F61-83DA-29B4D811E64E/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/F426EBF1-DA65-4F61-83DA-29B4D811E64E/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/F426EBF1-DA65-4F61-83DA-29B4D811E64E/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/F426EBF1-DA65-4F61-83DA-29B4D811E64E/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/F426EBF1-DA65-4F61-83DA-29B4D811E64E/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/F426EBF1-DA65-4F61-83DA-29B4D811E64E/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/F426EBF1-DA65-4F61-83DA-29B4D811E64E/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/F426EBF1-DA65-4F61-83DA-29B4D811E64E/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/F426EBF1-DA65-4F61-83DA-29B4D811E64E/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/F426EBF1-DA65-4F61-83DA-29B4D811E64E/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:153:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:6[HTTP] <-- GET /wd/hub/session/4ed3c4d2-787a-41ab-bd2e7:40)
    at GeneratorFunctionPrototype.inv-2oke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:100eac70bcdd53/screenshot 500 9074 ms - 250 
:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/.5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
```

the log `[debug] [XCUITest] Log file for xcodebuild test: [/Users/repeatlink/Library/Developer/Xcode/DerivedData/WebDriverAgent-hbxngkiyhlinsebzimsacejgzfhp/Logs/Test/810D5ED4-C1BA-4BD6-BEA0-CE422DAAE542/Session-WebDriverAgentRunner-2017-07-19_214356-pfbTjV.log]`

please FYI  https://gist.github.com/KuKiSiNi77/5c23f45ea56ed4a9fa67453b3a8e9678

### Second appearance
```
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"element":"00C53324-278F-494A-86B9-721D0210F380"})-wait(options={"ms":1})-release(options={})
[debug] [XCUITest] Found matching gesture: longPress
[debug] [JSONWP Proxy] Proxying [POST /wda/element/00C53324-278F-494A-86B9-721D0210F380/touchAndHold] to [POST http://localhost:8100/session/AE9500E8-DD51-40BF-9A4F-947EDD7BDF3F/wda/element/00C53324-278F-494A-86B9-721D0210F380/touchAndHold] with body: {"duration":0.001}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"AE9500E8-DD51-40BF-9A4F-947EDD7BDF3F","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/touch/perform 200 2672 ms - 76 
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[HTTP] --> POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/timeouts {"type":"implicit","ms":0}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",0,"4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] Set implicit wait to 0ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/timeouts 200 2 ms - 76 
[HTTP] --> GET /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/context {}
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53"]
[debug] [XCUITest] Executing command 'getCurrentContext'
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/context 200 3 ms - 84 
[HTTP] --> POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/elements {"using":"name","value":"RL_tool_bar_title_label"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["name","RL_tool_bar_title_label","4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/AE9500E8-DD51-40BF-9A4F-947EDD7BDF3F/elements] with body: {"using":"name","value":"RL_tool_bar_title_label"}
[debug] [iProxy] Error connecting to device!
[debug] [MJSONWP] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/elements 200 14 ms - 74 
[HTTP] --> GET /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/context {}
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53"]
[debug] [XCUITest] Executing command 'getCurrentContext'
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/context 200 2 ms - 84 
[HTTP] --> POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/elements {"using":"name","value":"RL_tool_bar_title_label"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["name","RL_tool_bar_title_label","4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/AE9500E8-DD51-40BF-9A4F-947EDD7BDF3F/elements] with body: {"using":"name","value":"RL_tool_bar_title_label"}
[debug] [iProxy] Error connecting to device!
[debug] [MJSONWP] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/elements 200 7 ms - 74 
[HTTP] --> GET /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/context {}
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53"]
[debug] [XCUITest] Executing command 'getCurrentContext'
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/context 200 2 ms - 84 
[HTTP] --> POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/elements {"using":"name","value":"RL_tool_bar_title_label"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["name","RL_tool_bar_title_label","4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/AE9500E8-DD51-40BF-9A4F-947EDD7BDF3F/elements] with body: {"using":"name","value":"RL_tool_bar_title_label"}
[debug] [iProxy] Error connecting to device!
[debug] [MJSONWP] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/elements 200 9 ms - 74 
[HTTP] --> POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/timeouts {"type":"implicit","ms":1000}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",1000,"4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] Set implicit wait to 1000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/timeouts 200 2 ms - 76 
[HTTP] --> GET /wd/hub/session/4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["4ed3c4d2-787a-41ab-bd2e-2eac70bcdd53"]
[debug] [XCUITest] Executing command 'getScreenshot'
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/AE9500E8-DD51-40BF-9A4F-947EDD7BDF3F/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/AE9500E8-DD51-40BF-9A4F-947EDD7BDF3F/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/AE9500E8-DD51-40BF-9A4F-947EDD7BDF3F/screenshot] with no body
[debug] [iProxy] Error connecting to device!
[debug] [XCUITest] Log file for xcodebuild test: /Users/repeatlink/Library/Developer/Xcode/DerivedData/WebDriverAgent-hbxngkiyhlinsebzimsacejgzfhp/Logs/Test/DDA239FB-3FC0-4F7F-B1FB-29BDFD548D24/Session-WebDriverAgentRunner-2017-07-20_010759-fVUDHK.log
```

the log `[debug] [XCUITest] Log file for xcodebuild test: /Users/repeatlink/Library/Developer/Xcode/DerivedData/WebDriverAgent-hbxngkiyhlinsebzimsacejgzfhp/Logs/Test/DDA239FB-3FC0-4F7F-B1FB-29BDFD548D24/Session-WebDriverAgentRunner-2017-07-20_010759-fVUDHK.log`

please FYI  https://gist.github.com/KuKiSiNi77/ec69f23c2e345c9a8b4de99cad2da683

**Comment by mykola-mokhnach** [comment] 2017-07-20 06:17
WDA agent stopped responding on the device. This might be caused by many reasons. Looking at the device log might help a bit.

**Comment by jlipps** [comment] 2017-07-27 21:03
duplicate of #8764.

**Closed by jlipps** 2017-07-27 21:03 UTC
Labels: ThirdpartyIssue, XCUITest
