### ISSUE TITLE
Chromedriver is unable to discover open pages when switching to another webview

### ISSUE THREAD

**Issue by heidijinxujia** [appium/appium#8032] opened 2017-03-14 00:07 UTC
## The problem
I am running an automation test where upon clicking a button in App1 (WEBVIEW_com.microsoft.aad.automation.testapp), the webview in App2(WEBVIEW_com.azure.authenticator:auth) will be launched. And when trying to send args into WEBVIEW_com.azure.authenticator:auth, the ChromeDrive returned the error: unknown error: unable to discover open pages. 

## Environment
* Appium v1.6.3
* Windows NT 10.0.14393 x86_64
* Node.js v6.9.5
* Android v5.1.1
* Nexus 10
* ChromeDriver v2.28.455520

## Details
```
[debug] [AndroidDriver] Parsed pid: 25637 pkg: com.azure.authenticator:auth!
[debug] [AndroidDriver] from: u0_a170,25637,137,1646544,182140,ffffffff,00000000,R,com.azure.authenticator:auth
[debug] [AndroidDriver] returning process name: com.azure.authenticator:auth
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.microsoft.aad.automation.testapp","WEBVIEW_com.azure.authenticator:auth","WEBVIEW_com.azure.authenticator"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.microsoft.aad.automation.testapp","WEBVIEW_com.azure.authenticator:auth","WEBVIEW_com.azure.authenticator"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com.azure.authenticator:auth'
[debug] [AndroidDriver] A port was not given, using random port: 8000
[debug] [Chromedriver] Changed state to 'starting'
[Chromedriver] Set chromedriver binary as: C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
[Chromedriver] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"8000 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Spawning chromedriver with: C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --url-base=wd/hub --port=8000 --adb-port=5037
[Chromedriver] [STDOUT] Starting ChromeDriver 2.28.455520 (cc17746adff54984afff480136733114c6b3704b) on port 8000
Only local connections are allowed.
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"10.0.14393\"}}}"
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.microsoft.aad.automation.testapp","androidUseRunningApp":true,"androidDeviceSerial":"R32CA07LPZA"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"b1c35b8996a726e5b08133ef68ccbde8","status":13,"value":{"message":"unknown error: unable to discover open pages\n  (Driver info: chromedriver=2.28.455520 (cc17746adff54984afff480136733114c6b3704b),platform=Windows NT 10.0.14393 x86_64)"}}
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.microsoft.aad.automation.testapp","androidUseRunningApp":true,"androidDeviceSerial":"R32CA07LPZA"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"28cc33b8cc8bd2ec0c7bb86d537d61ef","status":13,"value":{"message":"unknown error: unable to discover open pages\n  (Driver info: chromedriver=2.28.455520 (cc17746adff54984afff480136733114c6b3704b),platform=Windows NT 10.0.14393 x86_64)"}}
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.microsoft.aad.automation.testapp","androidUseRunningApp":true,"androidDeviceSerial":"R32CA07LPZA"}}}
[HTTP] <-- POST /wd/hub/session/959700af-4088-4080-b976-1619ebc62170/context - - ms - -
[HTTP] --> GET /wd/hub/session/959700af-4088-4080-b976-1619ebc62170/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["959700af-4088-4080-b976-1619ebc62170"]
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"fe41e9cb20834a83420a7b305bbceeb2","status":13,"value":{"message":"unknown error: unable to discover open pages\n  (Driver info: chromedriver=2.28.455520 (cc17746adff54984afff480136733114c6b3704b),platform=Windows NT 10.0.14393 x86_64)"}}
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.microsoft.aad.automation.testapp","androidUseRunningApp":true,"androidDeviceSerial":"R32CA07LPZA"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"24a402fe164aa46db9edf3b6398e7624","status":13,"value":{"message":"unknown error: unable to discover open pages\n  (Driver info: chromedriver=2.28.455520 (cc17746adff54984afff480136733114c6b3704b),platform=Windows NT 10.0.14393 x86_64)"}}
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[debug] [Chromedriver] Changed state to 'stopped'
[Chromedriver] Error: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.28.455520 (cc17746adff54984afff480136733114c6b3704b),platform=Windows NT 10.0.14393 x86_64)
    at Chromedriver.callee$2$0$ (../../lib/chromedriver.js:177:15)
    at tryCatch (C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
```

## Link to Appium logs
[Appium Logs Link Here](https://gist.github.com/heidijinxujia/452bce5a10e460813ce6c08f8785b5d9)

**Comment by dpgraham** [comment] 2017-03-15 18:51
@imurchie Do you think this is an Appium issue? Judging by the logs, I'd say that something is wrong with ChromeDriver, given that it's closing unexpectedly.

**Comment by heidijinxujia** [comment] 2017-03-17 16:55
My current work around is to Capabilities.SetCapability("chromeAndroidPackage", "app_package_name"); Then I didn't get this error "error: unable to discover open pages" anymore.  But I kept coming across the “Chrome not reachable” error (logs attached below). I have searched and tried to both downgrade and upgrade the Chromedriver according to the solutions mentioned in other issues. None of them worked. 
Have you any idea about this issue? Thanks!

Environment
•	Appium v1.6.3
•	Windows NT 10.0.14393 x86_64
•	Node.js v6.9.5
•	Android v5.1.1
•	Nexus 10
Logs
```
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.microsoft.aad.automation.testapp","WEBVIEW_com.azure.authenticator:auth"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com.azure.authenticator:auth'
[debug] [AndroidDriver] A port was not given, using random port: 8000
[debug] [Chromedriver] Changed state to 'starting'
[Chromedriver] Set chromedriver binary as: C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
[Chromedriver] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"8000 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Spawning chromedriver with: C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --url-base=wd/hub --port=8000 --adb-port=5037
[Chromedriver] [STDOUT] Starting ChromeDriver 2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed) on port 8000
Only local connections are allowed.
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"10.0.14393\"}}}"
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.azure.authenticator","androidUseRunningApp":true,"androidDeviceSerial":"R32CA07LPZA"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"e90b1d9d3c96ff5f36bc7d1a7b6abaea","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 10.0.14393 x86_64)"}}

[Chromedriver] Error: chrome not reachable
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 10.0.14393 x86_64)
    at Chromedriver.callee$2$0$ (../../lib/chromedriver.js:177:15)
    at tryCatch (C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
Error: chrome not reachable
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 10.0.14393 x86_64)
    at Chromedriver.callee$2$0$ (../../lib/chromedriver.js:177:15)
    at tryCatch (C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[debug] [ADB] Getting connected devices...
[MJSONWP] Encountered internal error running command: Error: chrome not reachable
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 10.0.14393 x86_64)
    at Chromedriver.callee$2$0$ (../../lib/chromedriver.js:177:15)
    at tryCatch (C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\jinjia\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
```

**Comment by heidijinxujia** [comment] 2017-03-20 17:25
I've tried the v 1.6.4-beta Still got the same error. Is there anyone could help me with this issue? Thanks a lot.

**Comment by pandabat** [comment] 2017-03-22 15:36
I too am struggling with "chrome not reachable" errors although these can also manifest as "no such session" errors. 

Environment
• Appium v1.6.3
• Fedora 24 x64
• Node v4.7.3
• Android v4.4.2 running on STB

I've tried Appium 1.5.2, 1.5.3 & 1.6.3 with chromedrivers 2.14 through to 2.28 inclusive but I've not gotten tests (that did previously run a few months back) to work again. Alas I'm unsure what versions I was on before I started trying to upgrade and now nothing works for me. Depending on the Appium and chromedriver versions, the error may also present as "no such session" or "device not online" but for the most part it comes up as "chrome not reachable".

The issue only occurs when I try to switch to the webview in a hybrid app. Initiallly connecting to the native context doesn't seem to be an issue. See

https://discuss.appium.io/t/chrome-not-reachable-when-switching-to-webview-in-hybrid-app/15435

for further info  - I've gotten no replies there yet though. Maybe our issues are connected, maybe not but no harm in referencing it here.

**Comment by pandabat** [comment] 2017-03-22 15:46
I do reference it in my discussion thread but fwiw I did also install Appium, etc. in Windows 7 (32-bit) and got the same error when attempting to switch to webview context.

**Comment by jassid1** [comment] 2017-05-04 11:25
ok so i tried chrome driver 2.28 with google.apk version 51.0.2704.81 (x86) still no luck :(

Even tried it with chrome driver 2.25 and nothing. (sigh)

There is no issue with my coding right?

**Comment by mykola-mokhnach** [comment] 2017-05-04 11:26
Try to get the output of adb logcat - maybe there are some errors visible there

**Comment by pandabat** [comment] 2017-05-04 11:44
I'm working with a patched Chromedriver 2.28 for Linux now. 

You can grab it here if you're using 64-bit Linux. https://www.dropbox.com/s/605wm68iamhisqf/chromedriver_64_2.28_patched_xwalk?dl=0

There may be some pre-patched versions for other OSs out there. These are the broad instructions that I used for building on Linux (Fedora). They may be of use to someone else:

https://sites.google.com/a/chromium.org/chromedriver/contributing

https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md#Build-Chromium     (****FOLLOW THESE ***)

sudo dnf install git python bzip2 tar pkgconfig atk-devel alsa-lib-devel bison binutils brlapi-devel bluez-libs-devel bzip2-devel cairo-devel cups-devel dbus-devel dbus-glib-devel expat-devel fontconfig-devel freetype-devel gcc-c++ GConf2-devel glib2-devel glibc.i686 gperf glib2-devel gtk2-devel gtk3-devel java-1.*.0-openjdk-devel libatomic libcap-devel libffi-devel libgcc.i686 libgnome-keyring-devel libjpeg-devel libstdc++.i686 libX11-devel libXScrnSaver-devel libXtst-devel libxkbcommon-x11-devel ncurses-compat-libs nspr-devel nss-devel pam-devel pango-devel pciutils-devel pulseaudio-libs-devel zlib.i686 httpd mod_ssl php php-cli python-psutil wdiff xfs

Also do these: http://www.fedorafaq.org/#installfonts

https://codereview.chromium.org/2375613002/#ps80001   (*** THEN APPLY THESE as below *** to fix https://bugs.chromium.org/p/chromedriver/issues/detail?id=749)

cp chrome/test/chromedriver/chrome/adb.h chrome/test/chromedriver/chrome/adb.h.bak
patch chrome/test/chromedriver/chrome/adb.h ~/Downloads/chromedriver_patches/issue2375613002_60001_70002.diff
cp  chrome/test/chromedriver/chrome/adb_impl.h  chrome/test/chromedriver/chrome/adb_impl.h.bak
patch  chrome/test/chromedriver/chrome/adb_impl.h ~/Downloads/chromedriver_patches/issue2375613002_60001_70004.diff 
cp  chrome/test/chromedriver/chrome/adb_impl.cc  chrome/test/chromedriver/chrome/adb_impl.cc.bak
patch  chrome/test/chromedriver/chrome/adb_impl.cc ~/Downloads/chromedriver_patches/issue2375613002_60001_70003.diff 
cp  chrome/test/chromedriver/chrome/device_manager.cc  chrome/test/chromedriver/chrome/device_manager.cc.bak
patch  chrome/test/chromedriver/chrome/device_manager.cc ~/Downloads/chromedriver_patches/issue2375613002_60001_70005.diff 
cp  chrome/test/chromedriver/chrome/device_manager_unittest.cc  chrome/test/chromedriver/chrome/device_manager_unittest.cc.bak
patch  chrome/test/chromedriver/chrome/device_manager_unittest.cc ~/Downloads/chromedriver_patches/issue2375613002_60001_70006.diff

/***Change build to non-component, non-debug build (so no extra linked libraries hanging around & size is reduced due to lack of debug) ***/
run
'gn args out/Default'
and add lines to resulting file that appears, save and exit:

is_debug = false
is_component_build = false
symbol_level = 0


/**** compile/build chromedriver ***/

ninja -C out/Default chrome/test/chromedriver:chromedriver

Find output file at out/Default/chromedriver

**Comment by jassid1** [comment] 2017-05-04 12:21
[adb logcat.txt](https://github.com/appium/appium/files/976073/adb.logcat.txt)

adb logcat that i ran from cmd

**Comment by ikhilko** [comment] 2017-05-17 10:07
Any solution here? We are facing same problem...

**Comment by dpgraham** [comment] 2017-05-17 16:43
@ikhilko What version of Appium, Chromedriver, NodeJS and Android are you using? And do you have server logs that you can provide a gist for?

**Comment by AnishKumarMB** [comment] 2017-06-01 09:18
facing the same issue, after analysis found in https://github.com/appium/appium-android-driver/blob/master/lib/commands/context.js while creating

**Comment by dpgraham** [comment] 2017-06-01 21:35
@AnishKumarMB Just to confirm, you have tested that this patch works?

If so, then would you want to put in a PR for this?

I would shorten the code to 

```javascript
let appPackage = (opts.chromeOptions && opts.chromeOptions.androidPackage) || opts.appPackage;
```

**Comment by AnishKumarMB** [comment] 2017-06-02 01:19
@dpgraham Thank you for the excelled code.
We have tested for our scenario and works well.
It would be good if @heidijinxujia could also confirm if the patch works.
I can go ahead and raise a PR, but I am yet to complete https://github.com/appium/appium/blob/master/CONTRIBUTING.md
Please suggest.

**Comment by dpgraham** [comment] 2017-06-02 23:02
Since it's just a patch, don't worry too much about the CONTRIBUTING.md

You can just submit a PR and give a description of the fix, and also also post a link to this issue in the PR and that should be fine.

**Comment by AnishKumarMB** [comment] 2017-06-05 01:23
@dpgraham Thank you, will raise the PR ASAP.

**Comment by AnishKumarMB** [comment] 2017-06-05 05:28
@dpgraham I have raised the PR https://github.com/appium/appium-android-driver/pull/243

**Comment by dpgraham** [comment] 2017-06-05 16:27
Thanks @AnishKumarMB! Can you sign the agreement (it's an e-signature) and then we can merge it and close this issue.

**Comment by AnishKumarMB** [comment] 2017-06-05 23:07
@dpgraham Thanks, I have signed the agreement.

**Comment by dpgraham** [comment] 2017-06-06 00:42
The PR was merged and has been published.

It will be in the next version of Appium (1.6.6)

Thanks for your help @AnishKumarMB !

**Closed by dpgraham** 2017-06-06 00:42 UTC
Labels: Android

**Comment by AnuKadloor** [comment] 2017-07-28 12:56
@AnishKumarMB 
I have installed the latest version of appium-android-driver through npm, and on executing the tests, I'm still able to replicate the error -> Chrome Not reachable.

Appium version :- 1.6.5
Chromedriver:- 2.31
appium-android-driver:- 1.24.1

Below are the capabilities:
           capabilities.setCapability("deviceName", "Samsung");
            capabilities.setCapability("platformVersion", "7.0");
            capabilities.setCapability("platformName", "Android");
            capabilities.setCapability("appPackage", "com.someName");
            capabilities.setCapability("appActivity", "com.someActivity");
            capabilities.setCapability("fullReset", false);
            capabilities.setCapability("noReset", true);
            capabilities.setCapability("newCommandTimeout", "45000");
            capabilities.setCapability("clearSystemFiles", true);
            capabilities.setCapability("automationName", "uiautomator2");
            capabilities.setCapability("recreateChromeDriverSessions", true);
            capabilities.setCapability("chromedriverExecutable", workDir + chromeDriverPath);

Following is the link to the logs:
https://gist.github.com/AnuKadloor/016a8ef85bc769f835357f26fad4a24e

Can you confirm whether the patch has indeed fixed the issue or am I missing something?

**Comment by AnishKumarMB** [comment] 2017-08-01 09:10
@AnuKadloor just wanted to understand the scenairo you are trying to test.
as part of 
desiredCapabilites:
‘chromeOptions’: {
    androidPackage:’application_package'
    ‘androidUseRunningApp’:’true’
}
Is the above being set?

**Comment by AnuKadloor** [comment] 2017-08-01 12:46
@AnishKumarMB On checking the logs I can confirm that these capabilities are not being set by appium (for the scenarios in which I encounter the Chrome not reachable error).

So in the logs provided above, a total of 4 test cases were executed. Out of these, first 2 were executed successfully. For these 2, chromeOptions capabilities were set. However, the last 2 cases were failing and for these chromeOptions were not set.

**Comment by AnishKumarMB** [comment] 2017-08-01 13:28
@AnuKadloor could you try to explicitly set them.

**Comment by AnuKadloor** [comment] 2017-08-01 13:55
@AnishKumarMB I tried setting them explicitly as follows:-

ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.addArguments("androidPackage", "com.sg.R14A.placochauffeur.build");
chromeOptions.addArguments("androidUseRunningApp", "true");

capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);

However, on executing this, I'm getting an error.

[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[debug] [Chromedriver] Changed state to 'stopped'
[Chromedriver] Error: unknown error: cannot parse capability: chromeOptions
from unknown error: unrecognized chrome option: class
  (Driver info: chromedriver=2.31.488774 (7e15618d1bf16df8bf0ecf2914ed1964a387ba0b),platform=Mac OS X 10.12.6 x86_64)
