### ISSUE TITLE
uiautomator2 does not start 

### ISSUE THREAD

**Issue by yahman72** [appium/appium#11528] opened 2018-10-15 16:32 UTC
## The problem

uiautomator2 does not start on real device (S7 droid 7)

## Environment

* Appium version (or git revision) that exhibits the issue: v1.9.0
* Last Appium version that did not exhibit the issue (if applicable): v1.7.2 
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v8.12.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device - Samsung S7 (Android 7.0)
* Appium CLI or Appium.app|exe: 

## Details
I was actually gathering some logs for the #11527 and noticed that the uiautomator2 keeps crashing with v1.9.0, when opening the session

## Link to Appium logs
Various Scenarios: 
- OK: appium v1.7.2 + uiautomator2 (https://gist.github.com/yahman72/0d4f325dcac9c7d81c098a024c9f93b5)
- NOK: appium v1.9.0 + uiautomator2: (https://gist.github.com/yahman72/9ff1de5c72b59a3c1b9541e96d8547bb)
- NOK: after fresh win10 reboot - appium v1.9.0 + uiautomator2: (https://gist.github.com/yahman72/6d882f264f5d510cb4a724d557d499ab)

## Code To Reproduce Issue [ Good To Have ]
```
from appium import webdriver as appium_webdriver

dc_s7a7_smsr = {
    'automationName': 'uiautomator2',
    'udid': u'ce10171a6078523a03',
    'deviceName': u'Dummy',
    'appPackage': 'com.samsung.android.messaging',
    'appActivity': 'com.android.mms.ui.ConversationComposer',
    'platformName': 'Android',
    'noReset': True,
    'dontStopAppOnReset': False,
    'optionalIntentArguments': "-W",
    'skipUnlock': True,
    }

appium_webdriver.Remote('http://localhost:4723/wd/hub', dc_s7a7_smsr)
```

**Comment by mykola-mokhnach** [comment] 2018-10-15 16:54
Duplicate of https://github.com/appium/appium/issues/11234

**Closed by mykola-mokhnach** 2018-10-15 16:54 UTC
