### ISSUE TITLE
Getting java.lang.ClassNotFoundException: org.openqa.selenium.remote.AcceptedW3CCapabilityKeys

### ISSUE THREAD

**Issue by dipakkumar1225** [appium/appium#17006] opened 2022-05-29 13:32 UTC
## The problem

**Getting java.lang.ClassNotFoundException: org.openqa.selenium.remote.AcceptedW3CCapabilityKeys** at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606) 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) 	at io.appium.java_client.remote.options.BaseOptions.<clinit>(BaseOptions.java:54)

Till yesterday the same code was working fine.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v14.18.0
* Package manager name and version (we only officially support NPM): 8.7.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: cli

## Details
Using Appium-java client 8.0.0
```
public class AndroidNativeAppManager extends GenericDriverManager {
    ConfigurationProperties configurationProperties = ConfigurationManager.getConfiguration();

    @Override
    protected void createDriver(String automationName) {

        String strDeviceUUID = configurationProperties.androidDeviceUDID().isEmpty()
                ? AndroidGetDeviceInfo.getConnectedDeviceNameOrUIID() :
                configurationProperties.androidDeviceUDID();

        String[] platformInfo = configurationProperties.androidPlatformAndVersion().split(" ");
        String strPlatformName = configurationProperties.androidPlatformAndVersion().isEmpty() ? "Android" : platformInfo.length == 1 ? platformInfo[0] : "Android";
        String strPlatformVersion = configurationProperties.androidPlatformAndVersion().isEmpty() ? AndroidGetDeviceInfo.getConnectedDevicePlatformVersion() : platformInfo.length == 2 ? platformInfo[1] : AndroidGetDeviceInfo.getConnectedDevicePlatformVersion();

        List<String> pkgActivityList = AndroidGetDeviceInfo.getPackageAndLauncherName();
        String strPackageName = configurationProperties.androidAppPackage().isEmpty() ? pkgActivityList.get(0) : configurationProperties.androidAppPackage();
        String strLauncherActivityName = configurationProperties.androidAppActivity().isEmpty() ? pkgActivityList.get(1) : configurationProperties.androidAppActivity();

        UiAutomator2Options uiAutomator2Options = new UiAutomator2Options()
                .setAutomationName(automationName)
                .clearSystemFiles()
                .clearDeviceLogsOnStart()
                .setFullReset(false)
                .setNoReset(true)
                .autoGrantPermissions()
                .setDeviceName(strDeviceUUID)
                .setPlatformName(strPlatformName)
                .showChromedriverLog()
                .setPlatformVersion(strPlatformVersion)
                .setApp(new File(configurationProperties.androidApkFilePath()).getAbsolutePath())
                .setAppPackage(strPackageName)
                .setAppActivity(strLauncherActivityName)
                .setAppWaitActivity("*")
                .setAppWaitForLaunch(true)
                .setNewCommandTimeout(Duration.ofSeconds(200));
        uiAutomator2Options.setCapability(AndroidMobileCapabilityType.UNICODE_KEYBOARD, true);
        uiAutomator2Options.setCapability(AndroidMobileCapabilityType.RESET_KEYBOARD, true);


        try {
            mobileDriver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), uiAutomator2Options);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }

        mobileDriver.setSetting(Setting.IGNORE_UNIMPORTANT_VIEWS,true);
        mobileDriver.setSetting(Setting.WAIT_FOR_SELECTOR_TIMEOUT, 360000);
        mobileDriver.setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, 0);
    }
}
```

**Comment by mykola-mokhnach** [comment] 2022-05-29 14:17
Duplicate of https://github.com/appium/java-client/issues/1695

**Closed by mykola-mokhnach** 2022-05-29 14:17 UTC
