### ISSUE TITLE
Appium crashes FATAL ERROR: CALL_AND_RETRY_LAST

### ISSUE THREAD

**Issue by jplegorburu** [appium/appium#9543] opened 2017-10-26 21:30 UTC
## The problem

After running test for sometime (2h aprox for the first time, then when i reboot appium it crashes faster), appium crashes showing this message:
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

## Environment
Versions: appium@1.7.1
OSX
Node.js version - v8.g.0
iOS
Real Device

## Details
When it crashes most of the times it is at 650M of memory.
TOP log
https://gist.github.com/jplegorburu/81541649c7a394e2eb652caa5e4c6121

## Link to Appium logs
https://gist.github.com/jplegorburu/d6a3c97aef4da96b87540dc2f509af27

**Comment by dpgraham** [comment] 2017-10-27 00:43
Are you running the Appium CLI or are you running it from inside Appium Desktop?

**Comment by dpgraham** [comment] 2017-10-27 01:35
Looks like a memory leak.

If you have time, would you be able to do some profiling?

If yes, here are the instructions
* Go to where Appium is installed (found via `which appium`)
* Run `node --inspect .`
* Go to the copy the devtools link provided in logs and navigate to it in Chrome (should look like `chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/dda7d166-3b42-4be4-9ca2-11824c5ab7c6`)
* In devtools, navigate to `Memory` tab and select `Record allocation timeline` and press `Start`
* Run your tests (you probably won't need to run them for the full 2 hours, we just want to see where the memory leaks occurred)
* When you've run the tests for a while, go back to that page and stop the record allocation (right click -> stop) and save them (right click -> save)
* Send me the the `.heaptimeline` file

This can hopefully give us clues. There's probably some variable that's growing and not ever being released.

**Comment by mykola-mokhnach** [comment] 2017-10-27 06:37
There is also the second way to take process memory snapshot:

Run Appium server with _--enable-heapdump_ command line argument and send the SIGUSR2 signal to the process when necessary. More details at https://github.com/appium/appium/blob/a4dd79b8144864cbc034eb97a8f0b5d744e3435c/docs/en/writing-running-appium/server-args.md

**Comment by jplegorburu** [comment] 2017-10-27 14:52
Hi @dpgraham i did what you said. I ran the test for about 15 minutes and here is the `.heaptimline` file.
[Heap-20171027T114342.heaptimeline.zip](https://github.com/appium/appium/files/1422426/Heap-20171027T114342.heaptimeline.zip)
FYI 
I dont know if this is what is generating the memory leak, but the test are constantly taking screenshots.

**Comment by dpgraham** [comment] 2017-10-27 16:15
Awesome! Thanks a lot for doing that. 

I'm looking into it right now. The `getScreenshot` method certainly looks like the problem.

**Comment by dpgraham** [comment] 2017-10-27 21:09
Notes: 
* At https://github.com/appium/appium-base-driver/blob/b7b0b7b2f3f5db58e8827ba6dc44357a5b55f88b/lib/jsonwp-proxy/proxy.js#L134 the string that's being passed into `log.debug` is not falling out of scope
* In this screenshot the blue bars represent instances of memory being added to the heap and then not being released by the end of the heap allocation recording, which means there's a memory leak because the recording lasts 15 minutes

![screen shot 2017-10-27 at 2 04 06 pm](https://user-images.githubusercontent.com/852574/32125339-4d4d4790-bb20-11e7-86de-931a1001ae77.png)

* Every blue bar is a screenshot, and is keeping ~2mb on the heap

**Comment by mykola-mokhnach** [comment] 2017-10-27 21:28
Looking at the bug https://bugs.chromium.org/p/v8/issues/detail?id=2869 I assume I know what the problem is. @dpgraham would you like to apply the workaround, which is described in that bug description yourself? I assume the optimal fix would be to add something like `'' + s` info appium support module to apply it for all strings being logged there, since these are kept in the internal buffer.

**Comment by dpgraham** [comment] 2017-10-27 22:51
Thanks @mykola-mokhnach yeah I can apply that fix. 

That's a gnarly bug, I'll have to look into how we can prevent that type of error.

**Comment by mykola-mokhnach** [comment] 2017-11-02 15:39
The fix has been deployed to appium@beta . @jplegorburu Please update the package and try again.

**Comment by jplegorburu** [comment] 2017-11-02 17:15
Hi @mykola-mokhnach i ran again the tests for about 15min and i think now is working great. Here is the `.heaptimeline` just in case.
[Heap-20171102T141101.heaptimeline.zip](https://github.com/appium/appium/files/1438678/Heap-20171102T141101.heaptimeline.zip)
I will let you know if something comes up
Thank you guys!

**Comment by dpgraham** [comment] 2017-11-02 17:20
Looks good to me. The big blue bars are gone. There's still some but we expect that. I'm good with closing this.

Thanks a lot for helping us with this @jplegorburu! The heap recordings were very helpful.

![screen shot 2017-11-02 at 10 19 36 am](https://user-images.githubusercontent.com/852574/32340303-6e07b47a-bfb7-11e7-821a-5c2c9d395ee8.png)

**Closed by dpgraham** 2017-11-02 17:20 UTC
Labels: Bug, P1

**Comment by meetmangukiya** [comment] 2018-08-18 15:05
I am still encountering this issue on appium 1.8.1

```

<--- Last few GCs --->

[19293:0x55fafffa67b0]  7837730 ms: Mark-sweep 1369.4 (1383.0) -> 1369.3 (1380.0) MB, 186.1 / 0.0 ms  (average mu = 0.980, current mu = 0.000) last resort GC in old space requested
[19293:0x55fafffa67b0]  7837919 ms: Mark-sweep 1369.3 (1380.0) -> 1369.3 (1380.0) MB, 189.7 / 0.0 ms  (average mu = 0.960, current mu = 0.000) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x129302b841bd]
Security context: 0x2962f3b9e6c9 <JSObject>
    1: stringSlice(aka stringSlice) [0x2908ddba6a39] [buffer.js:593] [bytecode=0x2908ddbda541 offset=91](this=0x10036b0022e1 <undefined>,buf=0x442a7298611 <Uint8Array map = 0x1796d03538d1>,encoding=0x2962f3bb1b91 <String[4]: utf8>,start=0,end=29827632)
    2: toString [0x770eed0da79] [buffer.js:666] [bytecode=0x2908ddbda031 offset=145](this=0x442a7298611 <Ui...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x55fafe60c3e1 node::Abort() [node]
 2: 0x55fafe60c42f  [node]
 3: 0x55fafe7b4392 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0x55fafe7b45cf v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0x55fafeb44ca3  [node]
 6: 0x55fafeb54091 v8::internal::Heap::AllocateRawWithRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
 7: 0x55fafeb21985 v8::internal::Factory::AllocateRawWithImmortalMap(int, v8::internal::PretenureFlag, v8::internal::Map*, v8::internal::AllocationAlignment) [node]
 8: 0x55fafeb28521 v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
 9: 0x55fafeb28aba v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [node]
10: 0x55fafe7cb7bc v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [node]
11: 0x55fafe6a9b35 node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*) [node]
12: 0x55fafe62a136  [node]
13: 0x55fafe8394c0  [node]
14: 0x55fafe83aaf7  [node]
15: 0x129302b841bd 
```
