### ISSUE TITLE
"snapshotMaxDepth" greater than a certain value returns "The previously found element X is not present in the current view anymore"

### ISSUE THREAD

**Issue by Konnor5092** [appium/appium#15602] opened 2021-07-01 16:44 UTC
## The problem

When attempting to refresh the source and screenshot in the Appium inspector with a `snapshotMaxDepth` value greater than `62`, I get the following error....

`
The previously found element \"Application 'com.boomin.customer'\" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: Error kAXErrorIllegalArgument getting snapshot for element <AXUIElementRef 0x133404c80> {pid=13798} {uid=[ID:1 hash:0x0]}
`

The same error is returned when posting to...

`curl --location --request GET 'http://168.119.30.67:4723/wd/hub/session/63dc03ae-30e3-4150-9a44-7c3c3e3c9be5/source'`

## Environment

* Appium version (or git revision) that exhibits the issue: **1.21.0**
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: **macOS Big Sur 11.4**
* Node.js version (unless using Appium.app|exe): N/A
* Npm or Yarn package manager: **Npm**
* Mobile platform/version under test: **iPhone 12 Pro Max**
* Real device or emulator/simulator: **simulator**
* Appium CLI or Appium.app|exe: **Appium.app**

## Details

The application is a React Native application. The App Source tree is already pretty polluted because of this. 

Many of the elements I wish to interact with are not visible to the inspector by default. My hope was that I could increase the value of `snapshotMaxDepth` until my elements would get returned. For some reason, the limit for changing this value for my application without it returning an error is `62`. This does help a little but still doesn't show everything I need.

Setting different values for `customSnapshotTimeout` made no difference either

**Capabilities**

```json
{
  "platformName": "iOS",
  "deviceName": "iPhone 12 Pro Max",
  "app": "/Users/customer/Downloads/BoominAutomation.app",
  "automationName": "XCUITest",
  "useJSONSource": true
}
```

**Settings (`snapshotMaxDepth` is the only one of these I set manually)**

```json
{
    "autoUpdateImageElementPosition": false,
    "checkForImageElementStaleness": true,
    "defaultImageTemplateScale": 1,
    "elementResponseAttributes": "type,label",
    "fixImageFindScreenshotDims": true,
    "fixImageTemplateScale": false,
    "fixImageTemplateSize": false,
    "getMatchedImageResult": false,
    "imageElementTapStrategy": "w3cActions",
    "imageMatchThreshold": 0.4,
    "mjpegScalingFactor": 100,
    "mjpegServerFramerate": 10,
    "mjpegServerScreenshotQuality": 25,
    "nativeWebTap": false,
    "nativeWebTapStrict": false,
    "reduceMotion": null,
    "screenshotQuality": 1,
    "shouldUseCompactResponses": true,
    "snapshotMaxDepth": 65,
    "useJSONSource": true
}
```
## Link to Appium logs

These are logs after sending a value of `65` for the `snapshotMaxDepth`

https://gist.github.com/Konnor5092/4ffbe0450d962c5e072b1d63249446d8

## Code To Reproduce Issue [ Good To Have ]

As this is pre launch code for a private business, I can't share it here. I am more than happy to share the `.app` file in confidence though. 

- Start Appium Server
- Start Inspector Session
- Use the capabilities above
- Update the settings with `{ "snapshotMaxDepth": 65 }`
- Click `Refresh Source & Screenshot`
- Error and inspector fails to load the latest screen shown on the simulator

Happy to hear of any workarounds to this problem.

**Comment by mykola-mokhnach** [comment] 2021-07-01 16:53
Duplicate of https://github.com/appium/appium/issues?q=is%3Aissue+kAXErrorIllegalArgument+is%3Aclosed

This seems to be a general XCTest issue while it cannot handle large element trees. Only Apple is capable of fixing that

**Closed by mykola-mokhnach** 2021-07-01 16:53 UTC
