### ISSUE TITLE
Unable to run appium on more than 1 iOS devices

### ISSUE THREAD

**Issue by pokeahontas** [appium/appium#13827] opened 2020-01-13 11:40 UTC
## The problem

I have problems right now when trying to run Appium inspector(or actual real device test) on iOS devices(see logs below). The error says "No profiles for 'OrgId.test.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'OrgId.test.xctrunner'". 
The weird thing about it, is that it works for me on another iOS test device. Is this a bug or did I miss something?

Also when trying full manual configuration I get this error when running `xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test`: 

`error: No profiles for 'com.test.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.test.WebDriverAgentRunner.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Catalina
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iPhone XR
* Appium CLI or Appium.app|exe: 1.15.1

## Link to Appium logs

https://gist.github.com/pokeahontas/b2f5abb147ab57dfa820d57770db00b6

**Comment by mykola-mokhnach** [comment] 2020-01-13 12:38
If xcodebuild itself fails then how appium could have anything to do with the problem? 
Make sure the device is properly added to the development profile and can accept apps signed by the given dev signature

**Comment by pokeahontas** [comment] 2020-01-13 12:50
@mykola-mokhnach  the device is added to the developer profile. what exactly do you mean with "can accept apps signed by the given dev signature"?

**Comment by mykola-mokhnach** [comment] 2020-01-14 13:34
Some people say that unlocking the keychain helps to solve similar issues. In general there is nothing much to do from Appium side. Try to check the signing issue with your developers

**Comment by mykola-mokhnach** [comment] 2020-01-15 20:40
Possible duplicate of https://github.com/appium/appium/issues/13836

**Comment by mykola-mokhnach** [comment] 2020-01-17 17:15
Closed as not an issue

**Closed by mykola-mokhnach** 2020-01-17 17:15 UTC
Labels: NeedsInfo, NotABug
