### ISSUE TITLE
Unable to load appium inspector due to XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle

### ISSUE THREAD

**Issue by SatishGirajala** [appium/appium#20707] opened 2024-10-29 08:55 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

setup - 
xcode - 16 version beta 5
appium - 2.12.1
xcuitest - 7.28.3
ios version - 18.1

I have rebuild wda , clean the build folder , moved files in derived data to bin , still having same issue 

Iam able to connect simulator successfully , having below issue when trying to connect real device

I have tried the steps metioned in this issue - https://github.com/appium/appium/issues/20239 
still no use

Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance 0x3018d2e00

### Expected Behavior

appium inspector should load as expected with real device 

### Minimal Reproducible Example

Unable to connect appium inspector still its loading

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.12.1
- Appium driver(s) and their version(s) (`appium driver list`): - 
- xcuitest@7.28.3 [installed (npm)]
- uiautomator2 [not installed]
- espresso [not installed]
- mac2 [not installed]
- windows [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]
- Appium plugin(s) and their version(s) (`appium plugin list`): - 
- images [not installed]
- execute-driver [not installed]
- relaxed-caps [not installed]
- universal-xml [not installed]
- Node.js version (output of `node --version`): 20.11.0
- `npm` version (output of `npm --version`): 10.9.0
- Last component(s) version which did _not_ exhibit the problem: xcode 16 , ios 17.4
- Platform and version under test: ios 17.4
- Real device or emulator/simulator: real device

**Comment by SatishGirajala** [comment] 2024-10-29 09:27
@KazuCocoa can you please help

**Comment by eglitise** [comment] 2024-10-29 10:56
Please provide your Appium server log.

**Comment by SatishGirajala** [comment] 2024-10-29 11:30
Hi @eglitise 

here are the logs , please check 

Welcome to Appium v2.12.1
[Appium] The autodetected Appium home path: /Users/Path/.appium
[Appium] Attempting to load driver xcuitest...
[Appium] Requiring driver at /Users/Path/.appium/node_modules/appium-xcuitest-driver/build/index.js
[Appium] XCUITestDriver has been successfully loaded in 1.788s
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
	http://127.0.0.1:4723/ (only accessible from the same host)
	http://192.168.39.103:4723/
	http://169.254.4.253:4723/
[Appium] Available drivers:
[Appium]   - xcuitest@7.28.3 (automationName 'XCUITest')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] --> POST /session {"capabilities":{"alwaysMatch":{"platformName":"ios","appium:platformVersion":"18.1","appium:automationName":"XCUITest","appium:udid":"00008110-001450C814C0A01E","appium:usePrebuiltWDA":"true","appium:disableAppDecompression":"true","appium:waitForQuiescence":"false","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"ios","appium:platformVersion":"18.1","appium:automationName":"XCUITest","appium:udid":"00008110-001450C814C0A01E","appium:usePrebuiltWDA":"true","appium:disableAppDecompression":"true","appium:waitForQuiescence":"false","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
[AppiumDriver@3045] Calling AppiumDriver.createSession() with args: [{"platformName":"ios","appium:platformVersion":"18.1","appium:automationName":"XCUITest","appium:udid":"00008110-001450C814C0A01E","appium:usePrebuiltWDA":"true","appium:disableAppDecompression":"true","appium:waitForQuiescence":"false","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"ios","appium:platformVersion":"18.1","appium:automationName":"XCUITest","appium:udid":"00008110-001450C814C0A01E","appium:usePrebuiltWDA":"true","appium:disableAppDecompression":"true","appium:waitForQuiescence":"false","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[AppiumDriver@3045] Event 'newSessionRequested' logged at 1730200740792 (16:49:00 GMT+0530 (India Standard Time))
[Appium] Attempting to find matching driver for automationName 'XCUITest' and platformName 'ios'
[Appium] The 'xcuitest' driver was installed and matched caps.
[Appium] Will require it at /Users/Path/.appium/node_modules/appium-xcuitest-driver
[Appium] Requiring driver at /Users/Path/.appium/node_modules/appium-xcuitest-driver/build/index.js
[AppiumDriver@3045] Appium v2.12.1 creating new XCUITestDriver (v7.28.3) session
[AppiumDriver@3045] Checking BaseDriver versions for Appium and XCUITestDriver
[AppiumDriver@3045] Appium's BaseDriver version is 9.12.1
[AppiumDriver@3045] XCUITestDriver's BaseDriver version is 9.12.1
[XCUITestDriver@329a] 
[XCUITestDriver@329a] Creating session with W3C capabilities: {
  "alwaysMatch": {
    "platformName": "ios",
    "appium:platformVersion": "18.1",
    "appium:automationName": "XCUITest",
    "appium:udid": “hidden it for privacy ,
    "appium:usePrebuiltWDA": "true",
    "appium:disableAppDecompression": "true",
    "appium:waitForQuiescence": "false",
    "appium:includeSafariInWebviews": true,
    "appium:newCommandTimeout": 3600,
    "appium:connectHardwareKeyboard": true
  },
  "firstMatch": [
    {}
  ]
}
[BaseDriver] The 'waitForQuiescence' capability has been deprecated and must not be used anymore. Please check the driver documentation for possible alternatives.
[XCUITestDriver@329a] Capability 'usePrebuiltWDA' changed from string to boolean. This may cause unexpected behavior
[XCUITestDriver@329a] Capability 'waitForQuiescence' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The 'waitForQuiescence' capability has been deprecated and must not be used anymore. Please check the driver documentation for possible alternatives.
[XCUITestDriver@329a] The following provided capabilities were not recognized by this driver:
[XCUITestDriver@329a]   disableAppDecompression
[XCUITestDriver@329a] The desired capabilities include neither an app nor a bundleId. WebDriverAgent will be started without the default app
[e1e01ea5][XCUITestDriver@329a] Session created with session id: e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d
[e1e01ea5][XCUITest] Current user: 'Path'
[e1e01ea5][XCUITestDriver@329a] Available real devices: hidden it for privacy
[e1e01ea5][XCUITestDriver@329a] Creating iDevice object with udid 'hidden it for privacy'
[e1e01ea5][XCUITestDriver@329a] Determining device to run tests on: udid: 'hidden it for privacy, real device: true
[e1e01ea5][XCUITestDriver@329a] Event 'xcodeDetailsRetrieved' logged at 1730200740842 (16:49:00 GMT+0530 (India Standard Time))
[e1e01ea5][XCUITestDriver@329a] Event 'appConfigured' logged at 1730200740842 (16:49:00 GMT+0530 (India Standard Time))
[e1e01ea5][XCUITestDriver@329a] Event 'resetStarted' logged at 1730200740842 (16:49:00 GMT+0530 (India Standard Time))
[e1e01ea5][XCUITestDriver@329a] Reset: running ios real device reset flow
[e1e01ea5][XCUITestDriver@329a] Event 'resetComplete' logged at 1730200740842 (16:49:00 GMT+0530 (India Standard Time))
[e1e01ea5][XCUITestDriver@329a] Using WDA path: '/Users/Path/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'
[e1e01ea5][XCUITestDriver@329a] Using WDA agent: '/Users/Path/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[e1e01ea5][XCUITestDriver@329a] The pyidevice tool is not present in PATH. Skipping crash logs collection for real devices.
[e1e01ea5][XCUITestDriver@329a] Event 'logCaptureStarted' logged at 1730200741041 (16:49:01 GMT+0530 (India Standard Time))
[e1e01ea5][XCUITestDriver@329a] Setting up real device
[e1e01ea5][XCUITestDriver@329a] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[e1e01ea5][DevCon Factory] Requesting connection for device 00008110-001450C814C0A01E on local port 8100, device port 8100
[e1e01ea5][DevCon Factory] Cached connections count: 0
[e1e01ea5][DevCon Factory] Successfully requested the connection for hidden for privacy :8100
[e1e01ea5][XCUITestDriver@329a] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[e1e01ea5][WD Proxy] Matched '/status' to command name 'getStatus'
[e1e01ea5][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[e1e01ea5][WD Proxy] Got response with status 200: {"value":{"build":{"version":"8.7.0","time":"Oct 29 2024 13:41:28","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"},"os":{"testmanagerdVersion":65535,"name":"iOS","sdkVersion":"18.0","version":"18.1"},"device":"iphone","ios":{"ip":"192.168.39.47"},"message":"WebDriverAgent is ready to accept commands","state":"success","ready":true},"sessionId":"AB1393F1-CF38-4AF1-A1DC-0D3711FBBC44"}
[e1e01ea5][XCUITestDriver@329a] Upgrade timestamp of the currently bundled WDA: 1729859373016
[e1e01ea5][XCUITestDriver@329a] Upgrade timestamp of the WDA on the device: undefined
[e1e01ea5][XCUITestDriver@329a] Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[e1e01ea5][XCUITestDriver@329a] Trying to start WebDriverAgent 1 times with 10000ms interval
[e1e01ea5][XCUITestDriver@329a] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[e1e01ea5][XCUITestDriver@329a] Event 'wdaStartAttempted' logged at 1730200741101 (16:49:01 GMT+0530 (India Standard Time))
[e1e01ea5][XCUITestDriver@329a] Using provided WebdriverAgent at 'http://127.0.0.1:8100/'
[e1e01ea5][WD Proxy] Matched '/status' to command name 'getStatus'
[e1e01ea5][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[e1e01ea5][WD Proxy] Got response with status 200: {"value":{"build":{"version":"8.7.0","time":"Oct 29 2024 13:41:28","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"},"os":{"testmanagerdVersion":65535,"name":"iOS","sdkVersion":"18.0","version":"18.1"},"device":"iphone","ios":{"ip”:”hidden for privacy},”message":"WebDriverAgent is ready to accept commands","state":"success","ready":true},"sessionId":"AB1393F1-CF38-4AF1-A1DC-0D3711FBBC44"}
[e1e01ea5][XCUITestDriver@329a] Event 'wdaSessionAttempted' logged at 1730200741109 (16:49:01 GMT+0530 (India Standard Time))
[e1e01ea5][XCUITestDriver@329a] Sending createSession command to WDA
[e1e01ea5][XCUITestDriver@329a] Matched '/session' to command name 'createSession'
[e1e01ea5][XCUITestDriver@329a] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":false,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true,"forceAppLaunch":true,"useNativeCachingStrategy":true,"forceSimulatorSoftwareKeyboardPresence":false}],"alwaysMatch":{}}}
[e1e01ea5][XCUITestDriver@329a] Got response with status 200: {"value":{"sessionId":"E9CC8C1B-1F2F-450F-94EE-7BB4C406E8FE","capabilities":{"sdkVersion":"18.1","device":"iphone"}},"sessionId":"E9CC8C1B-1F2F-450F-94EE-7BB4C406E8FE"}
[e1e01ea5][XCUITestDriver@329a] Determined the downstream protocol as 'W3C'
[e1e01ea5][XCUITestDriver@329a] WDA session startup took 10ms
[e1e01ea5][XCUITestDriver@329a] Event 'wdaSessionStarted' logged at 1730200741119 (16:49:01 GMT+0530 (India Standard Time))
[e1e01ea5][XCUITestDriver@329a] Event 'wdaStarted' logged at 1730200741119 (16:49:01 GMT+0530 (India Standard Time))
[e1e01ea5][BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[e1e01ea5][BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[e1e01ea5][AppiumDriver@3045] New XCUITestDriver session created successfully, session e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d added to master session list
[e1e01ea5][AppiumDriver@3045] Event 'newSessionStarted' logged at 1730200741120 (16:49:01 GMT+0530 (India Standard Time))
[e1e01ea5][XCUITestDriver@329a] Cached the protocol value 'W3C' for the new session e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d
[e1e01ea5][XCUITestDriver@329a] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"ios","platformVersion":"18.1","automationName":"XCUITest","udid":"00008110-001450C814C0A01E","usePrebuiltWDA":true,"disableAppDecompression":"true","waitForQuiescence":false,"includeSafariInWebviews":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true}}
[e1e01ea5][HTTP] <-- POST /session 200 330 ms - 552 
[e1e01ea5][HTTP] --> GET /session/e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d/appium/settings {}
[e1e01ea5][XCUITestDriver@329a] Calling AppiumDriver.getSettings() with args: ["e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d"]
[e1e01ea5][XCUITestDriver@329a] Executing command 'getSettings'
[e1e01ea5][XCUITestDriver@329a] Responding to client with driver.getSettings() result: {"nativeWebTap":false,"nativeWebTapStrict":false,"useJSONSource":false,"webScreenshotMode":"native","shouldUseCompactResponses":true,"elementResponseAttributes":"type,label","mjpegServerScreenshotQuality":25,"mjpegServerFramerate":10,"screenshotQuality":1,"mjpegScalingFactor":100,"reduceMotion":null,"pageSourceExcludedAttributes":""}
[e1e01ea5][HTTP] <-- GET /session/e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d/appium/settings 200 7 ms - 345 
[e1e01ea5][HTTP] --> GET /session/e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d/screenshot {}
[e1e01ea5][XCUITestDriver@329a] Calling AppiumDriver.getScreenshot() with args: ["e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d"]
[e1e01ea5][XCUITestDriver@329a] Executing command 'getScreenshot'
[e1e01ea5][XCUITestDriver@329a] Taking screenshot with WDA
[e1e01ea5][XCUITestDriver@329a] Matched '/screenshot' to command name 'getScreenshot'
[e1e01ea5][XCUITestDriver@329a] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/E9CC8C1B-1F2F-450F-94EE-7BB4C406E8FE/screenshot] with no body
[e1e01ea5][XCUITestDriver@329a] Got response with status 200: {"value":"iVBORw0KGgoAAAANSUhEUgAABJIAAAnkCAIAAADZI9xUAAAAAXNSR0IArs4c6QAAAIRlWElmTU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAABIAAAAAQAAAEgAAAABAAOgAQADAAAAAQABAACgAgAEAAAAAQAABJKgAwAEAAAAAQAACeQAAAAAOMw3jQAAAAlwSFlzAAALEwAACxMBAJqcGAAAABxpRE9UAAAAAgAAAAAAAATyAAAAKAAABPIAAATyABLja5K+kOMAAEAASURBVHgBvL3rkiRJbmQ9L09y7kMuuW82fakefm8xfd0/3wGOQR3uEVldwyVXxMQEBigUcK/MCNMyj8jf/PFvPzn+8Lfv//T//fjH//whHow/fFce/diMP/3nzyD//LcfevyUrD999+Of//YToxh6/OU/8QD7yVAAGJaAlvTwWy78f/qOKt1Az8kKv+XkJ7r5dwj7L//5s4C6HNi40u9qmBsGo5vfluqqhz88gndR7MM/eDx//HTugIliTqG+LmxGoqbopLp+OoQH+/ef6l+HWVhmDbNkY7Z5Q6TLgJ90kQB0wt/On3//iRvOfPGPv9KTaHpm/I7U6mX/200tPQ9+OH/37fdd8afffUtjpzpgyTH++O1Pf/jmR2YBYGKQSEiw/IRwwmm3AeNPFk7Hnz7V9YpJFQ2dme0wy+r52++ZQ9sGdesS4oyNhz4HA6yQjACG+ZfffkM/v2w8nsabdctN+m+/+cHxQELV6Sn0s/yAbQB8+DGMDklliXzwJ2X4uY0WuvgnpTglbP6q25wgt12wPf7l2x9+++nHGu23z9j/8vX34f+Xrw8mUYzGf8ifFGDah//rn/8Ztm9rDqbsb36q8dVPRrF3LeyA9YM0Baqyv+bfuu7Mb3+N/8FT7XXp6qF53vJfXX19LgeeUNl/zeOUM1dh/7/76kp...
[e1e01ea5][XCUITestDriver@329a] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABJIAAAnkCAIAAADZI9xUAAAAAXNSR0IArs4c6QAAAIRlWElmTU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAABIAAAAAQAAAEgAAAABAAOgAQADAAAAAQABAACgAgAEAAAAAQAABJKgAwAEAAAAAQAACeQAAAAAOMw3jQAAAAlwSFlzAAALEwAACxMBAJqcGAAAABxpRE9UAAAAAgAAAAAAAATyAAAAKAAABPIAAATyABLja5K+kOMAAEAASURBVHgBvL3rkiRJbmQ9L09y7kMuuW82fakefm8xfd0/3wGOQR3uEVldwyVXxMQEBigUcK/MCNMyj8jf/PFvPzn+8Lfv//T//fjH//whHow/fFce/diMP/3nzyD//LcfevyUrD999+Of//YToxh6/OU/8QD7yVAAGJaAlvTwWy78f/qOKt1Az8kKv+XkJ7r5dwj7L//5s4C6HNi40u9qmBsGo5vfluqqhz88gndR7MM/eDx//HTugIliTqG+LmxGoqbopLp+OoQH+/ef6l+HWVhmDbNkY7Z5Q6TLgJ90kQB0wt/On3//iRvOfPGPv9KTaHpm/I7U6mX/200tPQ9+OH/37fdd8afffUtjpzpgyTH++O1Pf/jmR2YBYGKQSEiw/IRwwmm3AeNPFk7Hnz7V9YpJFQ2dme0wy+r52++ZQ9sGdesS4oyNhz4HA6yQjACG+ZfffkM/v2w8nsabdctN+m+/+cHxQELV6Sn0s/yAbQB8+DGMDklliXzwJ2X4uY0WuvgnpTglbP6q25wgt12wPf7l2x9+++nHGu23z9j/8vX34f+Xrw8mUYzGf8ifFGDah//rn/8Ztm9rDqbsb36q8dVPRrF3LeyA9YM0Baqyv+bfuu7Mb3+N/8FT7XXp6qF53vJfXX19LgeeUNl/zeOUM1dh/7/76kpJrqHH8uF8...
[e1e01ea5][HTTP] <-- GET /session/e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d/screenshot 200 409 ms - 2957928 
[e1e01ea5][HTTP] --> GET /session/e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d/window/rect {}
[e1e01ea5][XCUITestDriver@329a] Calling AppiumDriver.getWindowRect() with args: ["e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d"]
[e1e01ea5][XCUITestDriver@329a] Executing command 'getWindowRect'
[e1e01ea5][XCUITestDriver@329a] Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/E9CC8C1B-1F2F-450F-94EE-7BB4C406E8FE/window/size] with no body
[e1e01ea5][XCUITestDriver@329a] Got response with status 200: {"value":{"width":390,"height":844},"sessionId":"E9CC8C1B-1F2F-450F-94EE-7BB4C406E8FE"}
[e1e01ea5][XCUITestDriver@329a] Responding to client with driver.getWindowRect() result: {"width":390,"height":844,"x":0,"y":0}
[e1e01ea5][HTTP] <-- GET /session/e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d/window/rect 200 208 ms - 48 
[e1e01ea5][HTTP] --> GET /session/e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d/source {}
[e1e01ea5][XCUITestDriver@329a] Calling AppiumDriver.getPageSource() with args: ["e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d"]
[e1e01ea5][XCUITestDriver@329a] Executing command 'getPageSource'
[e1e01ea5][XCUITestDriver@329a] Matched '/source?format=xml&scope=AppiumAUT' to command name 'getPageSource'
[e1e01ea5][XCUITestDriver@329a] Proxying [GET /source?format=xml&scope=AppiumAUT] to [GET http://127.0.0.1:8100/session/E9CC8C1B-1F2F-450F-94EE-7BB4C406E8FE/source?format=xml&scope=AppiumAUT] with no body
[e1e01ea5][XCUITestDriver@329a] Got response with status 500: {"value":{"error":"unknown error","message":"-[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance 0x3011b0e00","traceback":"(\n\t0   CoreFoundation                      0x00000001880807d8 1532D3D8-9B3B-3F2F-B35F-55A20DDF411B + 534488\n\t1   libobjc.A.dylib                     0x00000001853532e4 objc_exception_throw + 88\n\t2   CoreFoundation                      0x00000001881868c8 1532D3D8-9B3B-3F2F-B35F-55A20DDF411B + 1607880\n\t3   CoreFoundation                      0x000000018801eb08 1532D3D8-9B3B-3F2F-B35F-55A20DDF411B + 133896\n\t4   CoreFoundation                      0x000000018801e430 _CF_forwarding_prep_0 + 96\n\t5   WebDriverAgentLib                   0x0000000108009498 -[XCUIElement(FBUtilities) fb_waitUntilStableWithTimeout:] + 308\n\t6   WebDriverAgentLib                   0x0000000107fc0ab4 +[FBXPath writeXmlWithRootElement:indexPath:elementStore:includedAttributes:writer:] + 632\n\t7   WebDriverAgentLib                   0x0000000107fc0...
[e1e01ea5][W3C] Matched W3C error code 'unknown error' to UnknownError
[e1e01ea5][XCUITestDriver@329a] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance 0x3011b0e00
    at errorFromW3CJsonCode (/Users/Path/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)
    at ProxyRequestError.getActualError (/Users/Path/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)
    at JWProxy.command (/Users/Path/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:348:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at XCUITestDriver.proxyCommand (/Users/Path/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)
    at XCUITestDriver.mobileGetSource (/Users/Path/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:50:35)
    at XCUITestDriver.getPageSource (/Users/Path/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:25:9)
[e1e01ea5][HTTP] <-- GET /session/e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d/source 500 48 ms - 1435 
[e1e01ea5][XCUITestDriver@329a] Parsed BUILD_DIR configuration value: '/Users/Path/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/build'
[e1e01ea5][XCUITestDriver@329a] Got derived data root: '/Users/Path/.appium/node_modules/appium-xcuitest-driver/node_modules'
[e1e01ea5][HTTP] --> GET /session/e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d/timeouts {}
[e1e01ea5][XCUITestDriver@329a] Calling AppiumDriver.getTimeouts() with args: ["e1e01ea5-43a3-4cbc-b7d7-fb9cf007a18d"]
[e1e01ea5][XCUITestDriver@329a] Executing command 'getTimeouts'

**Comment by eglitise** [comment] 2024-10-29 14:57
> [e1e01ea5][WD Proxy] Got response with status 200: {"value":{"build":{"version":"8.7.0"

Your WDA version is older than the one bundled with your XCUITest driver version - it should be 8.9.4 or newer. Please rebuild WDA. It is likely that the `appium:usePrebuiltWDA` capability is causing your session to use an older version.

**Comment by KazuCocoa** [comment] 2024-10-29 15:52
Yea, it's duplicate of https://github.com/appium/appium/issues/20239#issuecomment-2277352021

Please use xcuitest driver `7.24.15`+ and its bundled WDA version.
https://appium.github.io/appium-xcuitest-driver/latest/installation/requirements/

**Closed by KazuCocoa** 2024-10-29 15:52 UTC
Labels: Needs Info

**Comment by SatishGirajala** [comment] 2024-11-04 11:37
Thanks @KazuCocoa , 
Hi @eglitise 
can you pls help , I have rebuild the WDA version its still showing 8.7.0 even after uninstalling installing the xcode and creating new project in xcode and rebuild the WDA version 
I have even removed this appium:usePrebuiltWDA capability still having same issue
can you pls help how

**Comment by KazuCocoa** [comment] 2024-11-04 16:41
Please attach the full appium server log to see the entire flow

**Comment by SatishGirajala** [comment] 2024-11-05 04:21
@KazuCocoa  Thank you so much for your reply . Now I have resolved issue by downloading latest WDA - 8.9.4 from github and replaced it with existing WDA in xcode path and successfully able to load appium inspector .
