### ISSUE TITLE
element.getTagName() returns 'java.lang.ClassCastException' exception.

### ISSUE THREAD

**Issue by victor-kalmus-techery** [appium/appium#8644] opened 2017-06-09 13:42 UTC
When I use element.getTagName() it returns:
com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.lang.String

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):1.6.0
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android. MacOS
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe:

## Details

```
java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.lang.String

	at org.openqa.selenium.remote.RemoteWebElement.getTagName(RemoteWebElement.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.appium.java_client.pagefactory.ElementInterceptor.getObject(ElementInterceptor.java:40)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:62)
	at io.appium.java_client.android.AndroidElement$$EnhancerByCGLIB$$b598166c.getTagName(<generated>)
	at utils.waiters.Waiter.setText(Waiter.java:173)
	at actions.LoginActions.setLogin(LoginActions.java:15)
	at steps.LoginSteps.submitCredentials(LoginSteps.java:24)
	at steps.LoginSteps.loginWithValidCredentials(LoginSteps.java:31)
	at steps.LoginSteps.loginIfRequired(LoginSteps.java:38)
	at LoginTests.loginToApp(LoginTests.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:124)
```

#Appium Server log:

```
2017-06-09 19:07:22:405 - [HTTP] --> POST /wd/hub/session/75bc7ade-a2c8-4bd9-a904-f5f6a0c6f59b/timeouts {"type":"implicit","ms":0}
2017-06-09 19:07:22:406 - [debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",0,"75bc7ade-a2c8-4bd9-a904-f5f6a0c6f59b"]
2017-06-09 19:07:22:407 - [debug] [BaseDriver] Set implicit wait to 0ms
2017-06-09 19:07:22:407 - [debug] [MJSONWP] Responding to client with driver.timeouts() result: null
2017-06-09 19:07:22:408 - [HTTP] <-- POST /wd/hub/session/75bc7ade-a2c8-4bd9-a904-f5f6a0c6f59b/timeouts 200 3 ms - 76 
2017-06-09 19:07:22:420 - [HTTP] --> GET /wd/hub/session/75bc7ade-a2c8-4bd9-a904-f5f6a0c6f59b/context {}
2017-06-09 19:07:22:421 - [debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["75bc7ade-a2c8-4bd9-a904-f5f6a0c6f59b"]
2017-06-09 19:07:22:421 - [debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
2017-06-09 19:07:22:424 - [HTTP] <-- GET /wd/hub/session/75bc7ade-a2c8-4bd9-a904-f5f6a0c6f59b/context 200 2 ms - 84 
2017-06-09 19:07:22:436 - [HTTP] --> POST /wd/hub/session/75bc7ade-a2c8-4bd9-a904-f5f6a0c6f59b/element {"using":"id","value":"et_username"}
2017-06-09 19:07:22:436 - [debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","et_username","75bc7ade-a2c8-4bd9-a904-f5f6a0c6f59b"]
2017-06-09 19:07:22:436 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2017-06-09 19:07:22:437 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2017-06-09 19:07:22:437 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2017-06-09 19:07:22:438 - [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/3066b79a-fd62-4d88-844b-fd93ba257335/element] with body: {"strategy":"id","selector":"et_username","context":"","multiple":false}
2017-06-09 19:07:22:514 - [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"3066b79a-fd62-4d88-844b-fd93ba257335","status":0,"value":{"ELEMENT":"d43ea2c2-d65e-4afa-a737-f9083286deda"}}
2017-06-09 19:07:22:516 - [debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"d43ea2c2-d65e-4afa-a737-f9083286deda"}
2017-06-09 19:07:22:521 - [HTTP] <-- POST /wd/hub/session/75bc7ade-a2c8-4bd9-a904-f5f6a0c6f59b/element 200 83 ms - 122 
2017-06-09 19:07:22:536 - [HTTP] --> POST /wd/hub/session/75bc7ade-a2c8-4bd9-a904-f5f6a0c6f59b/timeouts {"type":"implicit","ms":1000}
2017-06-09 19:07:22:537 - [debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",1000,"75bc7ade-a2c8-4bd9-a904-f5f6a0c6f59b"]
2017-06-09 19:07:22:539 - [debug] [BaseDriver] Set implicit wait to 1000ms
2017-06-09 19:07:22:539 - [debug] [MJSONWP] Responding to client with driver.timeouts() result: null
2017-06-09 19:07:22:540 - [HTTP] <-- POST /wd/hub/session/75bc7ade-a2c8-4bd9-a904-f5f6a0c6f59b/timeouts 200 4 ms - 76 
2017-06-09 19:07:22:553 - [HTTP] --> GET /wd/hub/session/75bc7ade-a2c8-4bd9-a904-f5f6a0c6f59b/element/d43ea2c2-d65e-4afa-a737-f9083286deda/name {}
2017-06-09 19:07:22:554 - [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2017-06-09 19:07:22:555 - [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/75bc7ade-a2c8-4bd9-a904-f5f6a0c6f59b/element/d43ea2c2-d65e-4afa-a737-f9083286deda/name] to [GET http://localhost:8200/wd/hub/session/3066b79a-fd62-4d88-844b-fd93ba257335/element/d43ea2c2-d65e-4afa-a737-f9083286deda/name] with body: {}
2017-06-09 19:07:22:610 - [debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"3066b79a-fd62-4d88-844b-fd93ba257335\",\"status\":0}"
2017-06-09 19:07:22:612 - [JSONWP Proxy] Replacing sessionId 3066b79a-fd62-4d88-844b-fd93ba257335 with 75bc7ade-a2c8-4bd9-a904-f5f6a0c6f59b
2017-06-09 19:07:22:615 - [HTTP] <-- GET /wd/hub/session/75bc7ade-a2c8-4bd9-a904-f5f6a0c6f59b/element/d43ea2c2-d65e-4afa-a737-f9083286deda/name 200 61 ms - 63 
```

**Comment by mykola-mokhnach** [comment] 2017-06-09 13:45
Can you please attach full stacktrace and Appium log?

**Comment by victor-kalmus-techery** [comment] 2017-06-09 16:09
@mykola-mokhnach Added some logs. Is it enough?

**Comment by mykola-mokhnach** [comment] 2017-06-09 18:18
To me it looks more like java_client issue.
@SrinivasanTarget can you please confirm?

**Comment by SrinivasanTarget** [comment] 2017-06-09 19:05
@mykola-mokhnach works fine with legacy android driver but not with UIAutomator2.I can able to reproduce this in UIAutomator2.

**Comment by dpgraham** [comment] 2017-06-09 20:12
Similar issue: https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/5154

**Comment by j0hnsa** [comment] 2017-06-13 10:24
I'm having the same issue, how can this be solved? I'm stuck for quite long on this...

**Comment by dpgraham** [comment] 2017-06-13 17:30
@j0hnsa We have a fix for this. It will make it's way into the next Appium beta release.

**Comment by j0hnsa** [comment] 2017-06-14 09:42
Hi @dpgraham thanks for the update, looking forward for it! Regards

**Closed** 2017-06-19 23:50 UTC
Labels: Bug, UIAutomator2

**Comment by kameshbabu** [comment] 2018-07-27 06:17
Hi Everyone, Even am facing the same issue. Please help me out what was the cause of it.
java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.lang.String
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:161)
	at org.openqa.selenium.support.ui.ExpectedConditions$13.apply(ExpectedConditions.java:384)
	at org.openqa.selenium.support.ui.ExpectedConditions$13.apply(ExpectedConditions.java:380)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at com.project.hpjetadvantagelink.lib.general.TestWait.waitForTextToAppear(TestWait.java:20)
	at com.project.hpjetadvantagelink.pom.scansample.ScanSample.isScanSuccessful(ScanSample.java:462)
	at com.project.hpjetadvantagelink.test.scansample.ScanSampleTest.TestScan_ScanToFTPFolderOptions_IsSuccessful(ScanSampleTest.java:341)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at org.testng.TestNG.run(TestNG.java:996)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
