### ISSUE TITLE
Not getting "Listening on USB" when running WebDriverAgentRunner test

### ISSUE THREAD

**Issue by rpjesivac** [appium/appium#9724] opened 2017-11-30 19:07 UTC
## The problem

Hi,

I am trying to setup appium to work for testing iOS devices and I can go trough installation, signing, and building everything successfully but when I run the last test I don't get "Listening on USB" message.

I did noticed that when tests start the port of ServerURL is 0 and not 8100 and I am not sure why that is happening?

Here is just the last couple of lines of test but full log is attached.

2017-11-30 10:40:56.348883-0500 XCTRunner[354:101620] Running tests...
2017-11-30 10:40:56.413297-0500 XCTRunner[354:101620] Continuing to run tests in the background with task ID 1
2017-11-30 10:40:57.652890-0500 XCTRunner[354:101620] Continuing to run tests in the background with task ID 2
Test Suite 'All tests' started at 2017-11-30 10:40:58.702
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-11-30 10:40:58.705
Test Suite 'UITestingUITests' started at 2017-11-30 10:40:58.706
Test Case '-[UITestingUITests testRunner]' started.
t = 0.00s Start Test at 2017-11-30 10:40:58.707
t = 0.01s Set Up
2017-11-30 10:40:58.723790-0500 XCTRunner[354:101620] Built at Nov 29 2017 15:30:10
2017-11-30 10:40:58.755890-0500 XCTRunner[354:101620] ServerURLHere->http://10.234.74.142:0<-ServerURLHere

Also, if I run CURL command to test it I get connection refused on port 8100.

C1MR10FNG944:~ mesqa$ curl -X GET -H "Content-Type: application/json;charset=UTF-8, accept:application/json" http://10.234.74.142:8100/status
curl: (7) Failed to connect to 10.234.74.142 port 8100: Connection refused

Any suggestion on how to complete this successfully?

Thanks

## Environment

* Appium version (or git revision) that exhibits the issue: v1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Sierra v10.12.6 
* Node.js version (unless using Appium.app|exe):v8.9.1
* Mobile platform/version under test: iOS 10.3.3 iPad
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Link to logs

[RunLogs.txt](https://github.com/appium/appium/files/1519131/RunLogs.txt)

**Comment by mykola-mokhnach** [comment] 2017-11-30 20:01
Duplicate of https://github.com/appium/appium/issues/9547

**Closed by mykola-mokhnach** 2017-11-30 20:01 UTC

**Comment by rpjesivac** [comment] 2017-12-01 12:23
@mykola-mokhnach 

Great that did solve this port problem (USE_PORT=8100).
Now when I run the build command I can see correct port but I still dont see "Listening on USB" message.
Here is the log:
Test Suite 'All tests' started at 2017-12-01 07:14:20.486
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-12-01 07:14:20.490
Test Suite 'UITestingUITests' started at 2017-12-01 07:14:20.491
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2017-12-01 07:14:20.495
    t =     0.01s     Set Up
2017-12-01 07:14:20.511319-0500 XCTRunner[417:204744] Built at Nov 29 2017 15:30:10
2017-12-01 07:14:20.541104-0500 XCTRunner[417:204744] ServerURLHere->http://10.234.74.142:8100<-ServerURLHere

And it stops there.. so I dont get "Listening on USB"...

However, when I run CURL command now I do correct response (below). So is there still something wrong with the setup or maybe that message "Listening on USB" is not displayed anymore?
Thanks again!

Rasko

C1MR10FNG944:~ mesqa$ curl -X GET -H "Content-Type: application/json;charset=UTF-8, accept:application/json" http://10.234.74.142:8100/status
{
  "value" : {
    "state" : "success",
    "os" : {
      "name" : "iOS",
      "version" : "10.3.3"
    },
    "ios" : {
      "simulatorVersion" : "10.3.3",
      "ip" : "10.234.74.142"
    },
    "build" : {
      "time" : "Nov 29 2017 15:30:14"
    }
  },
  "sessionId" : "FC738C25-8DDD-4DE9-9851-E3FB8934AAEF",
  "status" : 0

**Comment by rpjesivac** [comment] 2017-12-01 17:21
I guess "Listening on USB" message is removed.. since everything else is working as expected.
Thanks!
