### ISSUE TITLE
bug: Unable to switch to Webview context

### ISSUE THREAD

**Issue by heychirag** [appium/appium#19209] opened 2023-09-26 12:29 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appium is unable to switch to the Webview context. The driver just hangs and the promise to `switchContext()` never gets fulfilled. After a while, webdriverio throws this:

```
2023-09-26T09:56:14.726Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
2023-09-26T09:56:14.726Z INFO webdriver: Retrying 1/3
````

### Expected Behavior

Driver should be able to switch to Webview context.

### Minimal Reproducible Example

Try switching to a webview context with the latest Webview version `Chrome/117.0.0.0`

### Environment

- Operating system: macOS 13.6
- Appium server version (output of `appium --version`): 2.1.3
- Appium driver(s) and their version(s): 
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): v16.20.2
- `npm` version (output of `npm --version`): 8.19.4
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Android
- Real device or emulator/simulator: Real Device

### Link to Appium Logs

https://gist.github.com/heychirag/85b6cf8712355ae002010060ba788616

### Further Information

Appium just hangs after this line waiting for the promise to fulfil.

```
[debug] [Chromedriver@8b10] Matched '/session' to command name 'createSession'
[debug] [Chromedriver@8b10] Proxying [POST /session] to [POST http://127.0.0.1:8000/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"app.bundle.id","androidUseRunningApp":true,"androidProcess":"app.bundle.id","androidDeviceSerial":"R3CR401YLCL"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[debug] [Chromedriver@8b10] Webview version: 'Chrome/117.0.0.0'
```

**Comment by mykola-mokhnach** [comment] 2023-09-26 12:32
Duplicate of https://github.com/appium/appium/issues/19001

Unfortunately there is nothing we could do there from the driver side.

**Closed by mykola-mokhnach** 2023-09-26 12:32 UTC
Labels: Bug, Needs Triage

**Comment by mykola-mokhnach** [comment] 2023-09-27 12:54
I assume folks at chromedriver don't really pay attention to what is in the log (e.g. don't distinguish logs generated by Appum/UIA2 driver from chromedriver-specific logs). Basically, what happens there, chromedriver freezes after session creation request is sent to it. You could probably reproduce the same for them by starting chromedriver separately, creating a port forward for it and sending the session creation request using curl. Then just collect the console output that the executable itself generates. UIA2 driver simply automates the above process.

I understand that steps above require some tech skills, although we cannot do it ourselves, because an actual app or a website is needed in order to transition chromedriver to a frozen state.

**Comment by mykola-mokhnach** [comment] 2023-09-27 13:02
> In this instance, I suspect that the problem is likely linked to either Appium itself or the application being tested, rather than being an issue with WebdriverIO.

I agree to @tamil777selvan there. The problem is specific to how chromedriver interacts with your particular web view and cannot be reproduced on random data set. That is why you are the only person which could properly report it to chromedriver for further investigation. I don't see any other possibilities on how this issue could be resolved in the current scope.

**Comment by KazuCocoa** [comment] 2023-09-27 16:22
I saw similar behavior in chrome v115+. Actually as same as https://github.com/appium/appium/issues/19001

Not all app, afaik like our sample app had no issue, but some apps (I'm not owner of these apps) might experienced "no response from the chromedriver" behavior in a new session request. (In Appium context, it happens in context switching). Chormedriver itself did not respond the response to Appium in the new session request, so the root cause was probably chromedriver itself, or the combination of chromedriver and WebView app. The chromedriver's debug log did not have helpful logs to guess the reason then.

You could verify if chromedriver's new session request have the same behavior to your WebView directly without Appium/wdio by following https://chromedriver.chromium.org/getting-started/getting-started---android . It will help Google/chrome team's investigation I assume.

**Comment by heychirag** [comment] 2023-09-27 21:46
I was able to gather verbose logs by downloading the Chromedriver executable and then simply hitting it with a POST request for a new session.

Let's see what their response is: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4577

**Comment by KazuCocoa** [comment] 2023-09-27 21:54
thank you for the reporting and sharing it

**Comment by KazuCocoa** [comment] 2023-10-30 17:07
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4595 ?
