### ISSUE TITLE
bug: error with w3c

### ISSUE THREAD

**Issue by nimairodrigues** [appium/appium#18207] opened 2023-02-15 18:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i'm trying do a tap in the cellphone's screen but it doesnt work, i'm using this method in my code:
     public void tap(int x, int y) {
		new TouchAction<>(getDriver())
		.tap(PointOption.point(new Point(x, y)))
		.perform();
	}

and i tried this method too: 
     public void tapp(int x, int y) {
		new AndroidTouchAction(getDriver())
		.tap(PointOption.point(new Point(x, y)))
		.perform();
	}

but no one worked, i'm having the same result, in the appium's log show: [W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError.

### Expected Behavior

i need do a tap using the coordinates of my screen

### Minimal Reproducible Example

public void tap(int x, int y) {
		new TouchAction<>(getDriver())
		.tap(PointOption.point(new Point(x, y)))
		.perform();
	}

### Link to Appium Logs

https://gist.github.com/nimairodrigues/ff2f4748f766d33feb5cc634db50d3ba

### Futher Information

![image](https://user-images.githubusercontent.com/112123854/219122524-8102fd52-21b5-4fe7-8e7c-6ed3b10aea9c.png)

**Comment by mykola-mokhnach** [comment] 2023-02-15 21:26
Duplicate of https://github.com/appium/appium/issues/14990

**Closed by mykola-mokhnach** 2023-02-15 21:26 UTC
Labels: Bug, Needs Triage
