### ISSUE TITLE
[Feature Request]:  Make UIAutomator2 as default if target platform is android version 7+

### ISSUE THREAD

**Issue by realdah** [appium/appium#10066] opened 2018-01-25 01:31 UTC
## The problem

I started using appium android automated testing since last Friday, I immediately noticed that there are some screens will freeze the appium for ever (getSourcePage call), and I am managed to get a workaround dirty trick to by pass this issue.

Initially, I thought this freeze issue might be from appium or with combination of android app improper implementation, because I can get the layout and screenshot by running uiautomator directly but will freeze for ever with appium.

Until today, I got another issue that appium can not get full layout from android, but uiautomator can get it!!

With these two issues and read a few more discussions online, I realized that it is due to the fact of appium is using uiautomator by default regardless which target android version.

And uiautomator has issues with android version more than 7!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium:  Mac High Sierra
* Node.js version (unless using Appium.app|exe):  7+
* Mobile platform/version under test:  Android 7 or 8
* Real device or emulator/simulator:  emulator
* Appium CLI or Appium.app|exe:  appium.app

## Suggestions
Could we either update the document or make uiautomator2 as default if target platform is android 7+?

It is obvisouly that uiautomator is incompatible with latest android 7+, and it is wasting time for new comers to figure out this problem.

**Comment by mykola-mokhnach** [comment] 2018-01-25 06:41
It's not so easy like it looks. In order to know which automation backend to use we need to get the Android device version and there are no primitives for such purpose in the main appium package. The problem is that not everybody provides platformVersion cap for Android tests.

**Comment by mykola-mokhnach** [comment] 2018-01-25 06:42
What do you think @dpgraham ?

**Comment by realdah** [comment] 2018-01-25 15:14
@mykola-mokhnach Thanks for quick response.
Without solving this issue, there will be a lot of other 'Angry' ppl to raise issue on it. :-)

Just imagine if they are testing an app against android 6 and all went good, but same code with same apk does not work in android 7+, they will get angry....

look at this one, probably it is due to this reason:  ( the attitude of this issue reporter is a bit of disgusting )
https://github.com/appium/appium/issues/10069

**Comment by mykola-mokhnach** [comment] 2018-01-25 15:44
I've created a PR: https://github.com/appium/appium/pull/10073

Don't worry regarding issue reporters attitude. It's like everywhere - be nice to other people if you want them to be nice to you :)

**Comment by mykola-mokhnach** [comment] 2018-02-06 15:16
The change has been merged to beta. Now we show a warning message in the server log if UIA1 is  used with newer android versions.

**Closed by mykola-mokhnach** 2018-02-06 15:16 UTC
Labels: Enhancement, UIAutomator2

**Comment by Denslin** [comment] 2018-03-02 18:59
can you please let me know in which version of Appium I can find this change please ?
