### ISSUE TITLE
Unable to view elements of header views of tableView that is using reusableTableHeaderFooterView. 

### ISSUE THREAD

**Issue by rpatel29** [appium/appium#10674] opened 2018-05-09 23:40 UTC
## The problem
Unable to view elements of header views of tableView that is using reusableTableHeaderFooterView. The reusable view has multiple button elements.

<img width="532" alt="screen shot 2018-05-10 at 8 49 45 am" src="https://user-images.githubusercontent.com/39140191/39843957-ebbac64c-5430-11e8-8114-4ec459842588.png">

I expect to see other button elements within the highlighted element.

## Environment

* Appium version that exhibits the issue: Version 1.3.1
* Desktop OS/version used to run Appium: MacOS version 10.12.6
* Node.js version (unless using Appium.app|exe): v6.11.3
* Mobile platform/version under test: iOS 11.1
* Real device or emulator/simulator: iPhone 7
* Appium CLI or Appium.app|exe: 1.7.2

**Comment by mykola-mokhnach** [comment] 2018-05-10 05:44
Duplicate of https://github.com/appium/appium/issues/6517

**Closed by mykola-mokhnach** 2018-05-10 05:44 UTC

**Comment by rpatel29** [comment] 2018-05-13 22:09
Tried turning off accessibility on all elements except those in the container but appium still does not see the elements. Xcode still does see the accessibility Ids

**Comment by awasthiy** [comment] 2018-06-21 10:33
@rpatel29 were you able to arrive at some conclusion? I am also stuck at same kind of issue.

**Comment by rpatel29** [comment] 2018-06-22 00:10
@awasthiy No, I'm awaiting response. 
Hi @mykola-mokhnach Did you get a chance to review this issue ?
