### ISSUE TITLE
Original error: Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by NagarajLakshatti** [appium/appium#13905] opened 2020-02-03 07:02 UTC
## The problem

i am getting error like : ''Original error: Could not proxy command to remote server. Original error: Error: socket hang up" in vivo 1807
## Environment

* Appium version (or git revision) that exhibits the issue: 
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Appium Desktop app - 1.15.0-1
* Node.js version (unless using Appium.app|exe): Node v- v12.11.1
* Npm or Yarn package manager: npm v- 6.11.3
* Mobile platform/version under test: Android v- 8.1.0
* Real device or emulator/simulator: vivo 1807
* Appium CLI or Appium.app|exe: NA

## Details

Automation Name : uiautomater2

My script code is working fine in other devices why its not working on this device vivi 1807.

## Link to Appium logs

[HTTP] 
[Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[Instrumentation] INSTRUMENTATION_CODE: 0
[Instrumentation] The process has exited with code 0
[HTTP] --> POST /wd/hub/session/6afb24bc-dd51-4cfe-ac48-3405044291bb/element
[HTTP] {"using":"xpath","value":"(//android.widget.EditText)[2]"}
[W3C (6afb24bc)] Calling AppiumDriver.findElement() with args: ["xpath","(//android.widget.EditText)[2]","6afb24bc-dd51-4cfe-ac48-3405044291bb"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 200000 ms for condition
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/9d899c6a-f474-4b42-a6bc-80f29ac0869f/element] with body: {"strategy":"xpath","selector":"(//android.widget.EditText)[2]","context":"","multiple":false}
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[W3C (6afb24bc)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
[W3C (6afb24bc)]     at JWProxy.command (/tmp/.mount_AppiumKH5pZb/resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:261:13)
[HTTP] <-- POST /wd/hub/session/6afb24bc-dd51-4cfe-ac48-3405044291bb/element 500 13 ms - 554
[HTTP] 
[HTTP] --> GET /wd/hub/session/6afb24bc-dd51-4cfe-ac48-3405044291bb/screenshot
[HTTP] {}
[W3C (6afb24bc)] Calling AppiumDriver.getScreenshot() with args: ["6afb24bc-dd51-4cfe-ac48-3405044291bb"]
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://localhost:8200/wd/hub/session/9d899c6a-f474-4b42-a6bc-80f29ac0869f/screenshot] with no body
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[W3C (6afb24bc)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
[W3C (6afb24bc)]     at JWProxy.command (/tmp/.mount_AppiumKH5pZb/resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:261:13)
[HTTP] <-- GET /wd/hub/session/6afb24bc-dd51-4cfe-ac48-3405044291bb/screenshot 500 9 ms - 554
[HTTP] 
[HTTP] --> GET /wd/hub/session/6afb24bc-dd51-4cfe-ac48-3405044291bb/screenshot
[HTTP] {}
[W3C (6afb24bc)] Calling AppiumDriver.getScreenshot() with args: ["6afb24bc-dd51-4cfe-ac48-3405044291bb"]
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://localhost:8200/wd/hub/session/9d899c6a-f474-4b42-a6bc-80f29ac0869f/screenshot] with no body
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[W3C (6afb24bc)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
[W3C (6afb24bc)]     at JWProxy.command (/tmp/.mount_AppiumKH5pZb/resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:261:13)
[HTTP] <-- GET /wd/hub/session/6afb24bc-dd51-4cfe-ac48-3405044291bb/screenshot 500 7 ms - 554
[HTTP]

**Comment by mykola-mokhnach** [comment] 2020-02-03 09:42
Duplicate of https://github.com/appium/appium-uiautomator2-server/issues/310

**Closed by mykola-mokhnach** 2020-02-03 09:42 UTC
