### ISSUE TITLE
How to scroll  and find an element

### ISSUE THREAD

**Issue by moagarwa** [appium/appium#11417] opened 2018-09-24 18:59 UTC
## The problem

With the latest release I am not able to scroll and find the element and than tap on it

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1 beta
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: 10.13.6
* Node.js version (unless using Appium.app|exe): 6.4.1
* Mobile platform/version under test: iPhone7s 11.4
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe:

## Details

Please help we are unable to scroll and click on the element that is not visible on the screen.
Our automation is completely blocked

## Code To Reproduce Issue [ Good To Have ]

final int deviceWidth = mAppiumDriver.getWidthX();
		final int deviceHeight = mAppiumDriver.getHeightY();
		int TopY = (int) (deviceHeight * 0.3);
		int BottomY = (int) (deviceHeight * 0.80);
		int constX = (int) (deviceWidth * 0.5);

		int displayed = 0;
		boolean direction = false;

		for (int i = 0; i < 30; i++) {

			if (displayed == 1 || isElementDisplayed(elemID, 1)) {

				WebElement ele = getElementUsingAccessibilityID(elemID);
				if (isElementVisibleOnScroller(elemID)) {
					System.out.println("scrollFindVertical function:  "
							+ elemID + " element found");
					return true;
				}
				displayed = 1;
				direction = checkSwipeDirection(elemID);
				/*
				 * use this when scroller needs dynamic x;
				 */
				// constX = ((MobileElement) ele).getCenter().x;
				if (!direction) {
					// mAppiumDriver.swipe(constX, BottomY, constX, TopY, 1000);
					swipeUsingCoordinates(constX, BottomY, constX, TopY);
				} else {
					// mAppiumDriver.swipe(constX, TopY, constX, BottomY, 1000);
					swipeUsingCoordinates(constX, TopY, constX, BottomY);
				}
				// if(swipeWithDirection(ele, constX, TopY, BottomY,
				// direction)){
				// return true;
				// }

			} else {
				swipeUsingCoordinates(constX, BottomY, constX, TopY);
				if (i == 20) {
					if (direction == true) {
						return false;
					}
					direction = !direction;
					System.out.println("Changed direction to " + direction);
					i = 0;
				}
			}

**Comment by mykola-mokhnach** [comment] 2018-09-24 19:16
Please attach the full server log

**Comment by mykola-mokhnach** [comment] 2018-09-24 19:19
Possible duplicate of https://github.com/appium/appium/issues/11181

**Comment by mykola-mokhnach** [comment] 2018-09-27 12:37
no logs - no luck

**Closed by mykola-mokhnach** 2018-09-27 12:37 UTC
Labels: NeedsInfo
