### ISSUE TITLE
If I am trying to find locators in my android react native app using appium inspector I am unable to get the selected element instead getting whole screen

### ISSUE THREAD

**Issue by TanmayiDevineni** [appium/appium#18864] opened 2023-07-11 04:58 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to locate elements using appium inspector for my android react native application but when using getting whole screen not the single element

### Expected Behavior

I want the inspector to inspect the selected element properly

### Minimal Reproducible Example

I cannot share the code because it is confidential

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment] 2023-07-11 05:54
It might be a duplicate of https://github.com/appium/appium/issues/14825 or your application is not properly designed for accessibility. In both cases we cannot help much, you must check the app itself with the developer in order to fix/improve it.

**Closed by mykola-mokhnach** 2023-07-11 05:54 UTC
Labels: Bug, Needs Triage
