### ISSUE TITLE
Can't connect to URL on IOS12

### ISSUE THREAD

**Issue by thaichau298** [appium/appium#11497] opened 2018-10-09 06:27 UTC
## The problem

When i run automation test on iphone then browser navigate to the site : appium.io (default) . And can't  navigate to other URL (write in scenario). The next occur to driver error   

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: macOS High Sierra (10.13.6)
* Node.js version (unless using Appium.app|exe): 10.10.0
* Mobile platform/version under test: iphone 6 (12.0)
* Real device or emulator/simulator: real device

**Comment by mykola-mokhnach** [comment] 2018-10-09 06:33
Please attach the full server log

**Comment by Moriceg** [comment] 2018-10-10 08:45
I am facing the same issue. Please find attached the log. Let me know if you need more details.

```
[HTTP] {"desiredCapabilities":{"deviceName":"iPad Air2","udid”:”xxxxx”,”platformName":"iOS","platformVersion":"12.0.0","version":"iSafari11_iPad","bundleId":"com.apple.mobilesafari","automationName":"XCUITest","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"iPad Air2","udid”:”xxxx”,”platformName":"iOS","platformVersion":"12.0.0","version":"iSafari11_iPad","bundleId":"com.apple.mobilesafari","automationName":"XCUITest","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole"},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1539091089861 (16:18:09 GMT+0300 (Eastern European Summer Time))
[Appium] Creating new XCUITestDriver (v2.94.2) session
[Appium] Capabilities:
[Appium]   deviceName: iPad Air2
[Appium]   udid: xxxxx
[Appium]   platformName: iOS
[Appium]   platformVersion: 12.0.0
[Appium]   version: iSafari11_iPad
[Appium]   bundleId: com.apple.mobilesafari
[Appium]   automationName: XCUITest
[Appium]   realDeviceLogger: /usr/local/lib/node_modules/deviceconsole/deviceconsole
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"deviceName":"iPad Air2","...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: version.
[BaseDriver] Session created with session id: b7e54f86-05ba-471b-b8fb-0345f372133b
[debug] [XCUITest] Current user: ‘xxxx’
[debug] [XCUITest] Xcode version set to '10.0' 
[debug] [XCUITest] iOS SDK Version set to '12.0'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1539091090155 (16:18:10 GMT+0300 (Eastern European Summer Time))
[debug] [XCUITest] Available devices: xxx, xxx
[debug] [XCUITest] Creating iDevice object with udid ‘xxx’
[XCUITest] Determining device to run tests on: udid: ‘xxx’, real device: true
[debug] [BaseDriver] Event 'appConfigured' logged at 1539091091164 (16:18:11 GMT+0300 (Eastern European Summer Time))
[debug] [BaseDriver] Event 'resetStarted' logged at 1539091091164 (16:18:11 GMT+0300 (Eastern European Summer Time))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1539091091165 (16:18:11 GMT+0300 (Eastern European Summer Time))
[debug] [iOSLog] Attempting iOS device log capture via deviceconsole
[debug] [iOSLog] Using 'deviceconsole' from '/usr/local/lib/node_modules/deviceconsole'
[debug] [iOSLog] Starting iOS device log capture with: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[XCUITest] Cannot get the name of the crashes folder for the device with udid ‘xxxx’. Original error: Command 'idevicename -u xxxx’ exited with code 255
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1539091092083 (16:18:12 GMT+0300 (Eastern European Summer Time))
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8103 have been found
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8103/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"12.0\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"12.0\",\n      \"ip\" : \"172.16.45.134\"\n    },\n    \"build\" : {\n      \"time\" : \"Oct  9 2018 16:03:23\"\n    }\n  },\n  \"sessionId\" : \"AF5F6C18-78FB-4AAE-9ADF-6DC109B91A41\",\n  \"status\" : 0\n}"
[debug] [XCUITest] Upgrade timestamp of the currently bundled WDA: 1539078999702
[debug] [XCUITest] Upgrade timestamp of the WDA on the device: undefined
[XCUITest] Will reuse previously cached WDA instance at 'http://localhost:8103/'. Set the wdaLocalPort capability to a value different from 8103 if this is an undesired behavior.
[debug] [XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1539091092752 (16:18:12 GMT+0300 (Eastern European Summer Time))
[XCUITest] Using provided WebdriverAgent at 'http://localhost:8103/'
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1539091092753 (16:18:12 GMT+0300 (Eastern European Summer Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8103/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"12.0\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"12.0\",\n      \"ip\" : \"172.16.45.134\"\n    },\n    \"build\" : {\n      \"time\" : \"Oct  9 2018 16:03:23\"\n    }\n  },\n  \"sessionId\" : \"AF5F6C18-78FB-4AAE-9ADF-6DC109B91A41\",\n  \"status\" : 0\n}"
[debug] [JSONWP Proxy] Matched '/session' to command name 'createSession'
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8103/session] with body: {"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha”:”xxxx”,”built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"D9C9B567-309F-40EA-89D1-D2301FB55185","capabilities":{"device":"ipad","browserName":"Safari","sdkVersion":"12.0","CFBundleIdentifier":"com.apple.mobilesafari"}},"sessionId":"D9C9B567-309F-40EA-89D1-D2301FB55185","status":0}
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1539091097588 (16:18:17 GMT+0300 (Eastern European Summer Time))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1539091097588 (16:18:17 GMT+0300 (Eastern European Summer Time))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [BaseDriver] Event 'orientationSet' logged at 1539091097589 (16:18:17 GMT+0300 (Eastern European Summer Time))
[Appium] New XCUITestDriver session created successfully, session b7e54f86-05ba-471b-b8fb-0345f372133b added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1539091097590 (16:18:17 GMT+0300 (Eastern European Summer Time))
[debug] [MJSONWP] Cached the protocol value 'MJSONWP' for the new session b7e54f86-05ba-471b-b8fb-0345f372133b
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"deviceName":"iPad Air2","udid”:”xxxx”,”platformName":"iOS","platformVersion":"12.0.0","version":"iSafari11_iPad","bundleId":"com.apple.mobilesafari","automationName":"XCUITest","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole"}
[HTTP] <-- POST /wd/hub/session 200 7731 ms - 560
[HTTP] 
[HTTP] --> POST /wd/hub/session/b7e54f86-05ba-471b-b8fb-0345f372133b/url
[HTTP] {"url":"https://URL/“}
[debug] [MJSONWP] Calling AppiumDriver.setUrl() with args: ["https://URL”,”b7e54f86-05ba-471b-b8fb-0345f372133b"]
[debug] [XCUITest] Executing command 'setUrl'
[debug] [JSONWP Proxy] Matched '/url' to command name 'setUrl'
[debug] [JSONWP Proxy] Proxying [POST /url] to [POST http://localhost:8103/session/D9C9B567-309F-40EA-89D1-D2301FB55185/url] with body: {"url":"https://URL/“}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to open https://URL/“,”sessionId":"D9C9B567-309F-40EA-89D1-D2301FB55185","status":13}
[debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
[debug] [MJSONWP] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Failed to open https://qURL/
[debug] [MJSONWP]     at errorFromMJSONWPStatusCode (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:789:10)
[debug] [MJSONWP]     at ProxyRequestError.getActualError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:683:14)
[debug] [MJSONWP]     at JWProxy.command$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:236:19)
[debug] [MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[debug] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/b7e54f86-05ba-471b-b8fb-0345f372133b/url 500 58 ms - 230
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha”:”xxxx”,”built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 2 ms - 151
[HTTP] 
[HTTP] --> POST /wd/hub/session/b7e54f86-05ba-471b-b8fb-0345f372133b/execute
[HTTP] {"script":"return document['readyState'] ? 'complete' == document.readyState : true","args":[null]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["return document['readyState'] ? 'complete' == document.readyState : true",[null],"b7e54f86-05ba-471b-b8fb-0345f372133b"]
[debug] [XCUITest] Executing command 'execute'
[debug] [MJSONWP] Encountered internal error running command: NotImplementedError: Method is not implemented
[debug] [MJSONWP]     at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:13:11)
[debug] [MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[debug] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [MJSONWP]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [MJSONWP]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[debug] [MJSONWP]     at new Promise (<anonymous>)
[debug] [MJSONWP]     at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[debug] [MJSONWP]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[debug] [MJSONWP]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [MJSONWP]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[debug] [MJSONWP]     at XCUITestDriver.callee$0$0 [as execute] (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/build/lib/commands/execute.js:27:30)
[debug] [MJSONWP]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:296:26
[debug] [MJSONWP]     at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/util.js:26:23)
[debug] [MJSONWP]     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:510:31)
[debug] [MJSONWP]     at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:584:18)
[debug] [MJSONWP]     at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:248:10)
[debug] [MJSONWP]     at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:128:12)
[debug] [MJSONWP]     at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:133:10)
[debug] [MJSONWP]     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:15:14)
[debug] [MJSONWP]     at runCallback (timers.js:694:18)
[debug] [MJSONWP]     at tryOnImmediate (timers.js:665:5)
[debug] [MJSONWP]     at processImmediate (timers.js:647:5)
[HTTP] <-- POST /wd/hub/session/b7e54f86-05ba-471b-b8fb-0345f372133b/execute 501 10 ms - 112
[HTTP] 
```

**Comment by mykola-mokhnach** [comment] 2018-10-10 08:53
@Moriceg There is known XCTest bug, which prevents URL schemes from being opened in native context on real devices. I'd use simulator for such tests

**Comment by Moriceg** [comment] 2018-10-10 09:00
> @Moriceg There is known XCTest bug, which prevents URL schemes from being opened in native context on real devices. I'd use simulator for such tests

We are using only real devices. 
Will be this issue fixed in next releases of Appium?

**Comment by mykola-mokhnach** [comment] 2018-10-10 09:12
No, it will not, because the fix only depends on Apple: https://forums.developer.apple.com/thread/25355

**Comment by Moriceg** [comment] 2018-10-10 09:21
> No, it will not, because the fix only depends on Apple: https://forums.developer.apple.com/thread/25355

Thx. I'll try to downgrade then the Appium until the issue is fixed :)

**Comment by mykola-mokhnach** [comment] 2018-10-10 13:59
@Moriceg You could try switching to webview context. Replace `bundleId: com.apple.mobilesafari` with `browserName: safari`

**Closed** 2018-10-11 08:51 UTC
Labels: NeedsInfo
