### ISSUE TITLE
io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: Timed out after 35848ms waiting for the root AccessibilityNodeInfo in the active window.

### ISSUE THREAD

**Issue by sachinerandecapita** [appium/appium#16352] opened 2022-01-19 15:09 UTC
## The problem
Facing randomly following issue.
`-> error: An unknown server-side error occurred while processing the command. Original error: io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: Timed out after 35848ms waiting for the root AccessibilityNodeInfo in the active window. Make sure the active window is not constantly hogging the main UI thread (e.g. the application is being idle long enough), so the accessibility manager could do its work (64.9s)`

Looks like in appium code timeout is hardcoded to 10000 ms (i.e. 10 seconds) to wait for root element of the page to appear. 
Needs some way this timeout can be customized / Tell some workaround.

https://github.com/appium/appium-uiautomator2-server/blob/320a3a30f48a5a89a8b18d5bcc42d798e9344da2/app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java#L33

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.1
* Last Appium version that did not exhibit the issue (if applicable):1.22.1
* Desktop OS/version used to run Appium: Windows 2019
* Node.js version (unless using Appium.app|exe): 16.13.1
* Npm or Yarn package manager: NA
* Mobile platform/version under test: Android 10, API-29 emulator image
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium android driver for .net

## Details

Facing randomly following issue.
`-> error: An unknown server-side error occurred while processing the command. Original error: io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: Timed out after 35848ms waiting for the root AccessibilityNodeInfo in the active window. Make sure the active window is not constantly hogging the main UI thread (e.g. the application is being idle long enough), so the accessibility manager could do its work (64.9s)`

Looks like in appium code timeout is hardcoded to 10000 ms (i.e. 10 seconds) to wait for root element of the page to appear. 
Needs some way this timeout can be customized / Tell some workaround.

https://github.com/appium/appium-uiautomator2-server/blob/320a3a30f48a5a89a8b18d5bcc42d798e9344da2/app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java#L33

## Link to Appium logs

No logs, just shared the error.

## Code To Reproduce Issue [ Good To Have ]

Random issue, mentioned in problem. I think it should be fine to identify.

**Comment by mykola-mokhnach** [comment] 2022-01-19 18:39
Duplicate of https://github.com/appium/appium/issues/15562

It does not make much sense to increase this timeout as we don't want to block script execution for too long when the app is still blocking the main thread. Consider forking the driver if it needs to be customised for your project.

**Closed by mykola-mokhnach** 2022-01-19 18:39 UTC

**Comment by sachinerandecapita** [comment] 2022-01-20 04:12
> 

Product perspective it's nice to have things configurable rather hardcoded. We don't want to fork/copy entire driver project just for single hardcoded field in code.
We have better alternative than what is suggested - managed to bypass this by retrying if this exception occurs,  (so no of retries * 10 seconds) = timeout what we need.
Drivers should given things customizable to consumers, it can be the environment where these android emulator runs can cause delays to page loads, so it may take more than 10 seconds some time for drivers to recognize the root node appears.

**Comment by mykola-mokhnach** [comment] 2022-01-20 10:07
My point is that delay is happening in the client application. The 10 seconds timeout there does not mean the code is going to wait 10 seconds (and in the error message itself the actual delay was 30 seconds). This is happening because the downstream code in Uia2 framework has its own delays, which being multiplied could produce really huge uncontrollable delays. 
And since the current code is already a workaound then it would be a workaround for another workaround.
