### ISSUE TITLE
Android sendKeys event is doubling text to be entered on server side

### ISSUE THREAD

**Issue by jpkrause** [appium/appium#5268] opened 2015-06-17 22:11 UTC
In a particular scenario, the sendKeys call is having the text to be entered doubled and then entered. The only thing I noticed about it that was different than before is that the field was prepopulated with the same value, but that value was being cleared and then entered twice by the server. See log snippet below for that command. This same test has been running for some time and has not had this problem before. We did change the EditText views to use the new Material Design style, which seems to have caused this issue as I just tried it on an older version of the app (with Holo style EditText) and the bug does not occur. This change involves using the design support library in order to get the new style EditText.

Tests run on a Genymotion Nexus 5 simulator OS 4.4.4 and 5.1

2015-06-17 14:42:39:347 - info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"59","text":"blahaddress@gmail.com","replace":false}]
2015-06-17 14:42:39:349 - info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"59","text":"blahaddress@gmail.com","replace":false}}
2015-06-17 14:42:39:349 - info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
2015-06-17 14:42:39:349 - info: [debug] [BOOTSTRAP] [debug] Got command action: setText
2015-06-17 14:42:39:349 - info: [debug] [BOOTSTRAP] [debug] Using element passed in.
2015-06-17 14:42:39:355 - info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
2015-06-17 14:42:45:054 - info: [debug] [BOOTSTRAP] [debug] Sending plain text to element: blahaddress@gmail.comblahaddress@gmail.com
2015-06-17 14:42:47:908 - info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"24af4430-afad-495c-885e-5af06056d12c"}
2015-06-17 14:42:47:909 - info: <-- POST /wd/hub/session/24af4430-afad-495c-885e-5af06056d12c/element/59/value 200 8562.532 ms - 76 {"status":0,"value":true,"sessionId":"24af4430-afad-495c-885e-5af06056d12c"}
2015-06-17 14:42:47:909 - info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}

**Comment by jpkrause** [comment] 2015-06-17 23:20
I see where this error is occurring. It is at [this](https://github.com/appium/appium/blob/e6927c60e2264e32eade441dbfbf57f183310b43/lib/devices/android/bootstrap/src/io/appium/android/bootstrap/handler/SetText.java#L70) line in the class SetText where `text = currText + text;` is being executed. So maybe this isn't a bug? I'm not sure why the behavior would be different than it used to be all of a sudden.

**Comment by moizjv** [comment] 2015-06-17 23:23
@jpkrause `{"cmd":"action","action":"element:setText","params":{"elementId":"59","text":"blahaddress@gmail.com","replace":false}}` replace is `false`, so it is getting current text and adding send text. What language binding are you using?

**Comment by jpkrause** [comment] 2015-06-17 23:25
I'm using the Java API for executing actions. Don't see a `replace` flag available for the `sendKeys` call.

**Comment by moizjv** [comment] 2015-06-17 23:33
Can you try using `setValue()`?

**Comment by jpkrause** [comment] 2015-06-17 23:35
I'll give that a shot. It's just weird that the same command on an app with an older EditText class does not exhibit this behavior. Here's a log from the exact same test and appium client/server run against an older version of the app:

2015-06-17 16:32:53:698 - info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"55","text":"blahaddress@gmail.com","replace":false}]
2015-06-17 16:32:53:701 - info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"55","text":"blahaddress@gmail.com","replace":false}}
2015-06-17 16:32:53:701 - info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
2015-06-17 16:32:53:701 - info: [debug] [BOOTSTRAP] [debug] Got command action: setText
2015-06-17 16:32:53:701 - info: [debug] [BOOTSTRAP] [debug] Using element passed in.
2015-06-17 16:32:53:718 - info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
2015-06-17 16:32:59:601 - info: [debug] [BOOTSTRAP] [debug] Text remains after clearing, but it appears to be hint text.
2015-06-17 16:32:59:642 - info: [debug] [BOOTSTRAP] [debug] Text not cleared. Assuming remainder is hint text.
2015-06-17 16:32:59:642 - info: [debug] [BOOTSTRAP] [debug] Sending plain text to element: blahaddress@gmail.com
2015-06-17 16:33:02:228 - info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
2015-06-17 16:33:02:229 - info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"d50d8e03-7b7d-4b0c-9e4a-431813e08d12"}

**Comment by jpkrause** [comment] 2015-06-17 23:40
Actually, there's no `setValue()` method for AndroidElement (or MobileElement), it's in IOSElement. See [this search](https://github.com/appium/java-client/search?utf8=%E2%9C%93&q=setValue)

**Comment by moizjv** [comment] 2015-06-17 23:43
[README](https://github.com/appium/java-client/blob/master/README.md)  mentions  `setValue() moved from MobileElement to AndroidElement`

**Comment by moizjv** [comment] 2015-06-17 23:45
ping @Jonahss

**Comment by jpkrause** [comment] 2015-06-17 23:50
Looks like it just got removed rather than moved. I have the latest released version (2.2.0) and that method does not exist in either `MobileElement` or `AndroidElement`.

**Comment by moizjv** [comment] 2015-06-17 23:57
Yes it might be a typo

**Comment by moizjv** [comment] 2015-06-18 00:03
is this a hint text?

**Comment by jpkrause** [comment] 2015-06-18 00:05
No, the field is pre-populated with that email upon the activity opening (it's a sign in page). A workaround that solves the problem is clearing the field before executing `sendKeys()`.

**Comment by moizjv** [comment] 2015-06-18 00:10
I see what the problem is, we fixed `sendKeys ()`. Earlier it was not clearing, now it is clearing correctly and getting current text and appending it to it. So yes clearing and `sendKeys()` is the correct approach.

**Comment by moizjv** [comment] 2015-06-18 00:16
@jpkrause shall I close the issue?

**Comment by moizjv** [comment] 2015-06-18 00:35
@jpkrause It is the correct approach to clearText and sendKeys. Going to close the issue. Let me know if you have concerns.

**Closed by moizjv** 2015-06-18 00:35 UTC
Labels: NotABug, OnGoing

**Comment by jpkrause** [comment] 2015-06-18 00:46
Sounds good, thanks for the help!
