### ISSUE TITLE
Can't select value of picker wheel with appiumlibrary

### ISSUE THREAD

**Issue by Pangp0nd** [appium/appium#6622] opened 2016-06-27 09:02 UTC
## The problem

Hello,
I have issue for select value picker wheel with appiumlibrary with robotframework. I want to select value for picker wheel but I can't set value for picker wheel .
## Environment
- Appium v1.5.3 
- OSX 10.11.5
- Node v6.2.1
- iPhone 6 (9.3)
- emulator/simulator
- appiumlibrary for robotframework.
## Details

**I use appiumlibrary with robotframework.** 

I want to select value from picker wheel but i can't do it .

**cause 1:** May be use worng keyword, i try to use input value (It Pass but value not change), click element ( message : did not match any elements ), tap and scoll  have same message click element.

**cause 2:** May be locator element wrong, i try locator by ios (copy from UIAutomation), class (use UIAPickerWheel).

Do you have other suggestions, please?
Thanks.

**Comment by mehmetboraezer** [comment] 2016-06-30 15:43
Hi, 

Firstly you can not use "input value" keyword for iOS in picker case (But it will work on Android).

My way on this issue as follows:

```
  click element  ${open_picker}
  wait until page contains  ${picker_item}
  swipe  ${x_start}  ${y_start}  ${x_end}  ${y_end}
  click element  ${target_picker_item}
  click element  ${close_picker_button}
```
Finally, check again xpath and try my suggestion. Please share your status, maybe i can help you different way.

**Comment by Pangp0nd** [comment] 2016-07-08 05:42
I have tried your way , it did not match target picker element .
But i get Good solution for this issue from @rz-robsn.
```
                                                                                              
Input Text    class=UIAPickerWheel  MyOption`                               
                                                                                           
```

**Comment by rkavalap** [comment] 2016-11-16 03:12
Closing this issue as there is a work around.

**Closed by rkavalap** 2016-11-16 03:12 UTC

**Comment by suganeby** [comment] 2017-01-09 20:57
What is the workaround? I do have same issue in appium 1.6.3. Not able to set value value to the picker wheel in ios app. I tried "sendKeys" and "setValue", both of them didnt work.

Code that i tried
List<IOSElement> wheels = driver.findElements(MobileBy.className("XCUIElementTypePickerWheel"))
wheels.get(0).sendKeys("5")

**Comment by anzhehong** [comment] 2017-03-14 03:36
> I also wanna know how to directly set the value of picker view from iOS in appium

@suganeby

**Comment by suganeby** [comment] 2017-03-14 13:10
We can not set value directly to the picker since there is an issue in XCodeUITest itself. So i am using the work around provided above. I know its very complicated when the picker has lot of values. And also editing picker value is not easy.

**Comment by luonghuynh** [comment] 2017-05-15 23:45
Besides the solution posted by @suganeby, does anyone know if the latest Appium or Java-client fix this issue?  I need to select the value from the PickerWheel via values, instead of using the index as suggested by @suganeby's above solution.

**Comment by suganeby** [comment] 2017-05-16 14:09
@luonghuynh
I wish we can set the value to the picker wheel directly. Pickers that i am testing has almost 300 values. If i need to select the last value in the picker then its a nightmare.

I am using appium 1.6.3. I am not sure if it is fixed in the newest version 1.6.4, i haven't tried the newer version.

**Comment by suganeby** [comment] 2017-05-26 13:44
@luonghuynh
@anzhehong
I just installed appium 1.6.4. I am able to set values to the picker directly.

List wheels = driver.findElements(MobileBy.className("XCUIElementTypePickerWheel"))
wheels.get(0).setValue("12")

**Comment by anzhehong** [comment] 2017-05-27 04:04
@suganeby Thanks.
But there is still some trouble
I'm using 1.6.5-beta version of Appium.

When I call 

```
test = find_elements(class: 'XCUIElementTypePickerWheel')
test[0].set_value('com.test.com')
```

I will get the error message: `NoMethodError Exception: undefined method 'set_value' for #<Selenium::WebDriver::Element:0x007f927a34a1e8>`
I have checked the document from Appium but I cannot find the exact way for calling that.

So, do you know the exact way to implement that using ruby?

**Comment by suganeby** [comment] 2017-05-31 00:29
@anzhehong 
Sorry, i spoke too soon. setValue works only for time picker. its not working for other pickers.

**Comment by anzhehong** [comment] 2017-05-31 00:32
Thanks all the same！




-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Fowafolo An

Student of Tongji University

Tongji University, China,  Shanghai, No. 4800 Caoan Road, 201804

iOS Developer, SuccessFactors Jam, SAP


SAP Beijing Software System Co., Lt, China,  Shanghai, Shanghai Pudong Software Park, 201203


E anzhehong@126.com and  fowafolo.an@sap.com

M +86 17717090116
On 05/31/2017 08:29, suganeby wrote:

@anzhehong
Sorry, i spoke too soon. setValue works only for time picker. its not working for other pickers.

**Comment by luonghuynh** [comment] 2017-05-31 01:38
@suganeby Thanks... I am trying to follow one of the threads that mentioned this workaround from development codes. https://forums.developer.apple.com/thread/16104.  It mentioned using titleForRow instead of viewForRow.  More details can be found there.  I am working with the iOS developer to make that change.

**Comment by suganeby** [comment] 2017-06-01 13:48
Any one tried selectPickerWheelValue method in appium 1.6.5 ?  Appium release notes says "Add mobile: selectPickerWheelValue method to aid in interacting with picker wheels."

**Comment by anzhehong** [comment] 2017-06-02 06:56
@suganeby I tried but failed. It uses js execution instead of cocoa framework. I'm not sure whether it works on my app... Waiting for the good news.

**Comment by luonghuynh** [comment] 2017-06-03 17:56
@suganeby I did with selectPickerWheelValue method in appium 1.6.5, it worked fine but it is pretty much like your implementation, where it shifts the picker value one by one.  So my implementation would be, to use the swipe method to scroll the picker all the way to the top first, then use the selectPickerWheelValue method to scroll down one-by-one until I reach a desired index.

**Comment by tolgaek** [comment] 2017-09-27 18:42
@suganeby thanks for the workaround but the issue is that our dropdowns are dynamic and we need to look at the values of each option and make a selection on that. Is there a way to get a list of options and their value?
