### ISSUE TITLE
App not loading on real device IOS

### ISSUE THREAD

**Issue by coolrahim29** [appium/appium#10736] opened 2018-05-23 06:54 UTC
Attached is the gist with logs and information

Any help would be great thanks.

https://gist.github.com/coolrahim29/22c750c004d4adece4dcc03573d51c98

**Comment by mykola-mokhnach** [comment] 2018-05-23 06:59
> [Xcode] Testing failed:
> [Xcode] 	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
> [Xcode] 	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.4'

This is signing issue. Closed as duplicate.

**Closed by mykola-mokhnach** 2018-05-23 06:59 UTC

**Comment by radiobrain77** [comment] 2018-07-20 05:00
What is this a duplicate of?
