### ISSUE TITLE
Can't run WebDriverAgent appium on m1 macos

### ISSUE THREAD

**Issue by nursoltan-s** [appium/appium#15195] opened 2021-03-15 15:14 UTC
## The problem
Can't run appium WebDriverAgent on m1 macos simulator. I built successfully WebDriverAgentRunner on Xcode.

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.12
* Node.js version (unless using Appium.app|exe): v14.16.0
* Npm or Yarn package manager: 6.14.11
* Mobile platform/version under test: iOS, SDK 14.3
* Real device or emulator/simulator: Simulator (iPhone 11)
* Appium CLI or Appium.app|exe:

## Details

I got this error: 
 The bundle “WebDriverAgentRunner” couldn’t be loaded because it doesn’t contain a version for the current architecture. The bundle doesn’t contain a version for the current architecture. Try installing a universal version of the bundle.  (mach-o, but wrong architecture)

## Link to Appium logs

Log: https://gist.github.com/nursoltan-s/d2f291b016176be79e32f84c19797129

Please help.

**Comment by mykola-mokhnach** [comment] 2021-03-15 16:12
Duplicate of https://github.com/appium/appium/issues/15186

**Closed by mykola-mokhnach** 2021-03-15 16:12 UTC
