### ISSUE TITLE
Java 8.3.0 is not compatible with selenium 4.8.2

### ISSUE THREAD

**Issue by Idoserovitz** [appium/appium#18402] opened 2023-03-26 07:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since all issues are managed here, adding a link: https://github.com/appium/java-client/issues/1872

java-client 8.3.0 is incompatible with selenium 4.8.2

### Expected Behavior

to work well with selenium version between 4.7.0 to 5.0

### Minimal Reproducible Example

since java client 8.3.0 version allows selenium version 4.8.2, maven updates the jar files automatically and causing test failures. Running a test project with maven or specifically with selenium-api 4.8.2 should fail because appium server cannot launch programmatically.

**Comment by mykola-mokhnach** [comment] 2023-03-26 10:18
Duplicate of https://github.com/appium/java-client/issues/1872

**Closed by mykola-mokhnach** 2023-03-26 10:18 UTC
Labels: Bug, Needs Triage
