### ISSUE TITLE
Unable to start Inspector Session due some internal issues.

### ISSUE THREAD

**Issue by romy21romy** [appium/appium#12528] opened 2019-04-22 19:37 UTC
## The problem

Unable to start Server, I have Native Appium installed on my machine if start my local server then click on Start Inspector Session. then provide all the desired Capabilities 
{
  "automationName": "UiAutomator2",
  "platformName": "Android",
  "deviceName": "Google Pixi",
  "app": "/Users/USERNAME/Documents/MY_APP_NAME.apk",
  "udid": "emulator-5554",
  "platformVersion": "9"
}
it gives me this error : Error
An unknown server-side error occurred while processing the command. Original error: packageAndLaunchActivityFromManifest failed. Original error: Command '/Users/ramandeeps/Library/Android/sdk/build-tools/29.0.0-rc1/aapt dump badging /Users/ramandeeps/Documents/app-juvoup-debugLatest.apk' exited with code 1; StdErr: W/ziparchive( 4741): Zip: missed a central dir sig (at 0) W/zipro ( 4741): Error opening archive /Users/ramandeeps/Documents/app-juvoup-debugLatest.apk: Iteration ended ERROR: dump failed because no AndroidManifest.xml found

**but the funny thing is that if I download the brand new build and use ADB INSTALL myapp.apk it works fine. 
but as soon i use it in Appium Session inspected i get some error. 
after that, if I use the same build to install via Terminal I get** 

**Performing Streamed Install
adb: failed to install /Users/USERNAME/Documents/myapp.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl1622448317.tmp/base.apk: AndroidManifest.xml]**

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.12.1 (1.12.1.20190404.1)
* Last Appium version that did not exhibit the issue (if applicable): yes earlier I did not face this but I really don't remember the version last I tried was in Jan or Feb 2019.
* Desktop OS/version used to run Appium: MAC OS Mojave 10.14.4 (18E226)
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: tried on Android 28 and 25
* Real device or emulator/simulator: tried on the emulator and Real devices both
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

https://gist.github.com/romy21romy/ee905deb3214c3fa611698881a4b8cdc

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2019-04-23 06:17
Duplicate of https://github.com/appium/appium/issues/12442

**Closed by mykola-mokhnach** 2019-04-23 06:17 UTC
