### ISSUE TITLE
IOS - Appium is unable to install app from temporary directory /var/folders

### ISSUE THREAD

**Issue by gulatinitima** [appium/appium#16109] opened 2021-11-16 17:55 UTC
## The problem
IOS -
Appium Install app command is failing for not finding Info.plist file from the app stored under temporary folder.
Could not extract Info.plist from 'Viator.app': Plist file doesn't exist: '/var/folders/jx/9lthgs0s4vg0d1ys64thq5g40000gq/T/20211014-12955-128qbz2.5yo2/XXX.app/Info.plist'

when we had a new app version, it created a temporary directory (20211014-12955-128qbz2.5yo2) and saved that app there.
2021-11-12 22:44:28:354 - [debug] [BaseDriver] A fresh copy of the application is going to be downloaded from xyz server

Every test was installing the app from /var/folder. (/var/folders/jx/9lthgs0s4vg0d1ys64thq5g40000gq/T/20211014-12955-128qbz2.5yo2/XXX.app)

but after ~10 hours it started complaining that could not install app as it could not find info.plist. 

2021-11-15 20:02:25:306 - [XCUITest] Error installing app '/var/folders/jx/9lthgs0s4vg0d1ys64thq5g40000gq/T/20211014-12955-128qbz2.5yo2/XXX.app': Could not extract Info.plist from 'XXX.app': Plist file doesn't exist: '/var/folders/jx/9lthgs0s4vg0d1ys64thq5g40000gq/T/20211014-12955-128qbz2.5yo2/XXX.app/Info.plist'
2021-11-15 20:02:26:451 - [debug] [W3C (3d8fde08)] Encountered internal error running command: Error: Could not install '/var/folders/jx/9lthgs0s4vg0d1ys64thq5g40000gq/T/20211014-12955-128qbz2.5yo2/XXX.app':

Not sure which process is deleting the info.plist from temp directory or corrupting it? but If I delete this "T" folder and rerun the test, it is able to install app. 
Could you please advise what could be the cause of the issue?
In every ~10 hours  tests are unstable and installApp() doesn’t work. 

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 13.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:IOS 15.1
* Node.js version (unless using Appium.app|exe):v17.0.1
* Npm or Yarn package manager:
* Mobile platform/version under test: IOS 15.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: 

## Link to Appium logs

https://gist.github.com/gulatinitima/5d5a5a35f3cb65b78d02b3e8f78e1af0#file-install_app_issue_appium-log

**Comment by KazuCocoa** [comment] 2021-11-16 18:01
Could you share the full log?
I wonder this could duplicate of https://github.com/appium/appium/issues/16050.

**Comment by gulatinitima** [comment] 2021-11-16 20:09
The log file is too long, so I have divided it into 4 gist links date-wise ( Nov12, Nov13, Nov14 and Nov15) . Please find the gist links for logs
https://gist.github.com/gulatinitima/78ca4693ea226ca270ed5a959e1ff179#file-appium_log_nov_12-log
https://gist.github.com/gulatinitima/7a12143cea1687fbeab40b37a6f2afa5#file-appium_log_nov_13
https://gist.github.com/gulatinitima/b0c26d2af57492f4568c402ccc1296d6#file-appium_log_nov_14-log
https://gist.github.com/gulatinitima/990c4ed6404a18b961f9c9b853d1c3f7#file-appium_log_nov_15-log

**Comment by KazuCocoa** [comment] 2021-11-16 22:33
Thank you.
mm, i guess the 16050 might be related.
I assume unzipping `.ipa` caused the issue.

Could you try out appium 1.22.1 with `APPIUM_PREFER_SYSTEM_UNZIP=false` environment variable?

**Comment by gulatinitima** [comment] 2021-11-18 16:34
> Thank you. mm, i guess the 16050 might be related. I assume unzipping `.ipa` caused the issue.
> 
> Could you try out appium 1.22.1 with `APPIUM_PREFER_SYSTEM_UNZIP=false` environment variable?

hi @mykola-mokhnach sorry, I couldn’t test it on appium 1.22.1 yesterday. looks like you have found the issue. Do I still need to try it with appium 1.22.1 and APPIUM_PREFER_SYSTEM_UNZIP=false or linked PR #541 would solve this problem?

**Comment by mykola-mokhnach** [comment] 2021-11-18 16:37
You could checkout that branch locally and let it run for a while to verify whether it resolves your issue. I plan to merge it to appium@beta as soon as it is approved

**Comment by mykola-mokhnach** [comment] 2021-11-19 19:11
The patch has been published to appium@beta

**Comment by bennid** [comment] 2021-11-22 14:34
Unfortunately the beta fix caused this: https://github.com/appium/appium/issues/16146

**Comment by mykola-mokhnach** [comment] 2021-11-25 15:41
Closed as fixed

**Closed by mykola-mokhnach** 2021-11-25 15:41 UTC
Labels: NeedsInfo
