### ISSUE TITLE
SessionNotCreatedException: Unable to create a new remote session

### ISSUE THREAD

**Issue by faprile** [appium/appium#13342] opened 2019-10-02 09:25 UTC
hi all, i have this problem, but i don't know

appium 1.12.1
katalon 6.3.3
xcode 11.0

i launched an ios simulator on katalon studio, but connection not work

java.util.concurrent.ExecutionException: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Original error: unexpected end of stream on Connection{127.0.0.1:65035, proxy=DIRECT hostAddress=/127.0.0.1:65035 cipherSuite=none protocol=http/1.1}
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'AirdiFrancesco.homenet.telecomitalia.it', ip: 'fe80:0:0:0:1851:6f56:87c6:7a67%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_181'
Driver info: driver.version: IOSDriver
	at com.kms.katalon.composer.components.impl.dialogs.ProgressMonitorDialogWithThread.runAndWait(ProgressMonitorDialogWithThread.java:49)
	at com.kms.katalon.composer.mobile.objectspy.components.MobileLocalAppComposite$12.run(MobileLocalAppComposite.java:474)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Original error: unexpected end of stream on Connection{127.0.0.1:65035, proxy=DIRECT hostAddress=/127.0.0.1:65035 cipherSuite=none protocol=http/1.1}
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'AirdiFrancesco.homenet.telecomitalia.it', ip: 'fe80:0:0:0:1851:6f56:87c6:7a67%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_181'
Driver info: driver.version: IOSDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:85)
	at com.kms.katalon.core.appium.driver.AppiumDriverManager.createMobileDriver(AppiumDriverManager.java:495)
	at com.kms.katalon.core.appium.driver.AppiumDriverManager.createMobileDriver(AppiumDriverManager.java:479)
	at com.kms.katalon.core.mobile.keyword.internal.MobileDriverFactory.startLocalMobileDriver(MobileDriverFactory.java:460)
	at com.kms.katalon.composer.mobile.objectspy.dialog.MobileInspectorController.startMobileApp(MobileInspectorController.java:191)
	at com.kms.katalon.composer.mobile.objectspy.components.MobileLocalAppComposite$12$1.call(MobileLocalAppComposite.java:479)
	at com.kms.katalon.composer.components.impl.dialogs.ProgressMonitorDialogWithThread.startThreadAndWait(ProgressMonitorDialogWithThread.java:36)
	at com.kms.katalon.composer.components.impl.dialogs.ProgressMonitorDialogWithThread.runAndWait(ProgressMonitorDialogWithThread.java:48)
	... 2 more
Caused by: java.lang.reflect.InvocationTargetException
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 20 more
Caused by: java.io.IOException: unexpected end of stream on Connection{127.0.0.1:65035, proxy=DIRECT hostAddress=/127.0.0.1:65035 cipherSuite=none protocol=http/1.1}
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:208)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at org.openqa.selenium.remote.internal.OkHttpClient$Factory$1.lambda$createClient$1(OkHttpClient.java:152)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:105)
	... 21 more
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:237)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	... 41 more

**Comment by faprile** [comment] 2019-10-02 09:41
java.util.concurrent.ExecutionException: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:64863

**Comment by hadrianjmnz90** [comment] 2019-10-02 15:12
Check if you have this capability enabled:` capabilities.setCapability("usePrebuiltWDA", true);` if so, please delete it and try again, i have experienced when it is the first time launching a device and that capability is present, i get an error like the one you got,

**Comment by mykola-mokhnach** [comment] 2019-10-17 07:02
Closed as not an issue

**Closed by mykola-mokhnach** 2019-10-17 07:02 UTC

**Comment by Mariana1111** [comment] 2020-01-16 14:26
> Check if you have this capability enabled:` capabilities.setCapability("usePrebuiltWDA", true);` if so, please delete it and try again, i have experienced when it is the first time launching a device and that capability is present, i get an error like the one you got, also please post your capabilities code.

hello hadrianjmnz90, can you please advise i can check capabilities.setCapability("usePrebuiltWDA", true)

**Comment by hadrianjmnz90** [comment] 2020-01-16 16:41
> > Check if you have this capability enabled:` capabilities.setCapability("usePrebuiltWDA", true);` if so, please delete it and try again, i have experienced when it is the first time launching a device and that capability is present, i get an error like the one you got, also please post your capabilities code.
> 
> hello hadrianjmnz90, can you please advise where can i check capabilities.setCapability("usePrebuiltWDA", true) ?

well that is a not mandatory capability, more than that, what problems are you experiencing, can you share your code?

**Comment by Mariana1111** [comment] 2020-01-17 06:09
well i'm using Katalon studio to automate mobile application, after building the WebDriverAgent.xcodeproj
i did the same steps mentioned in https://docs.katalon.com/katalon-studio/docs/mobile-on-macos.html#reference-installation-guide
note that i did navigate to /Users/apple/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Build/Products/Debug-iphoneos/ and the web WebDriverAgentRunner-Runner already exist, but has a sign as if it is not supported when i double click on it i get "“WebDriverAgentRunner-Runner” needs to be updated." as if it set being created as 32 bit and not 64 bit, but i don't know how to relunch it as 64 bit (maybe this is the real problem i think, correct me please if i am wrong)

java.util.concurrent.ExecutionException: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
xcodebuild error message:

2020-01-17 07:58:25.204 xcodebuild[33518:691734] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/apple/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f857afc51d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Test session results, code coverage, and logs:
	/Users/apple/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Logs/Test/Test-WebDriverAgentRunner-2020.01.17_07-58-24-+0200.xcresult
Testing started on 'iPhone'
Testing failed:
	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the Signing & Capabilities editor.
	WebDriverAgentRunner:
		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))
** TEST EXECUTE FAILED **. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'

**Comment by Mariana1111** [comment] 2020-01-17 07:33
i have discovered one more thing, while building the webdriveragent, i'm getting DTDeviceKit: deviceType from b6b2519c61b831da3843e5e3af27b9b83589863d was NULL

**Comment by hadrianjmnz90** [comment] 2020-01-17 15:21
> WebDriverAgentRunner:
> WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))

hi, this is the line that concerns me "WebDriverAgentRunner:
WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))"
I have seen that error many times as the cause of failure to run appium on ios devices, i do not remember the exact steps but in case you're trying to run your test on a real device you should have developer id and team id and then navigate to this route "/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj" (at least that my path), open the project with xcode and then try to run the webdriver agent on your device, when you click build there should not be any warnings or errors, but i am sure you will get that you need a provisioning profile or something.

**Comment by Mariana1111** [comment] 2020-01-20 05:47
> WebDriverAgentRunner:
> WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))
> 
> hi, this is the line that concerns me "WebDriverAgentRunner:
> WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))"
> I have seen that error many times as the cause of failure to run appium on ios devices, i do not remember the exact steps but in case you're trying to run your test on a real device you should have developer id and team id and then navigate to this route "/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj" (at least that my path), open the project with xcode and then try to run the webdriver agent on your device, when you click build there should not be any warnings or errors, but i am sure you will get that you need a provisioning profile or something.

Dear 

> WebDriverAgentRunner:
> WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))
> 
> hi, this is the line that concerns me "WebDriverAgentRunner:
> WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))"
> I have seen that error many times as the cause of failure to run appium on ios devices, i do not remember the exact steps but in case you're trying to run your test on a real device you should have developer id and team id and then navigate to this route "/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj" (at least that my path), open the project with xcode and then try to run the webdriver agent on your device, when you click build there should not be any warnings or errors, but i am sure you will get that you need a provisioning profile or something.
Dear hadrianjmnz90
note that i already did the above mention note that i did add the developer ID and the team in the xcode and in the project, but i have realized something that the WebDriverAgentRunner-Runner.app is of version 32 bit, any idea how can i change it to 64 bit?

**Comment by mani537** [comment] 2020-07-03 03:28
To resolve java.util.concurrent.ExecutionException: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session, watch the below video.
