### ISSUE TITLE
Strange problem with iOS 

### ISSUE THREAD

**Issue by shapovalovei** [appium/appium#8417] opened 2017-05-10 03:03 UTC
## The problem

I run full test-suite on 2 real iOS devices and 2 Android devices. After some times I see in [logs iPhone6](https://gist.github.com/shapovalovei/af8e9f9552634d6c4d1ed091b54e4145) some errors.

After suite finish a see 2 case passed and 200+  failed 
Before, I never had a problem with signing WebDriver, why did it break during the test?
Maybe because I ran on several devices? 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Desktop OS/version used to run Appium: OSX Sierra (10.12.4)
* Node.js version (unless using Appium.app|exe): v7.9.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real 
* Appium CLI or Appium.app|exe: cli 

## Link to Appium logs
Logs from another device  iPhone 7: 
https://gist.github.com/shapovalovei/0719f7862cf32ee51a703decf43a3a32
https://gist.github.com/shapovalovei/84ee8271fbc95bb2f80bdcd79a3540e5

**Comment by shapovalovei** [comment] 2017-05-10 04:03
Maybe in one time cant build webDriverRunner on 2 devices ?

**Comment by mykola-mokhnach** [comment] 2017-05-10 06:25
It is most likely the duplicate of https://github.com/appium/appium/issues/8406

**Comment by shapovalovei** [comment] 2017-05-10 06:29
@mykola-mokhnach Could you please explain what kind of problem it is? Maybe you have link to XCTest/WDA Issues ? 

now I use ` desiredCapabilities.setCapability("useNewWDA", true);` I need use ` desiredCapabilities.setCapability("useNewWDA", false);` ?

**Comment by mykola-mokhnach** [comment] 2017-05-10 06:51
This is most likely causes by some internal resource leaks in XCTest, but one has to ask Apple to know it for sure.
This is the related WDA issue: https://github.com/facebook/WebDriverAgent/issues/507

**Comment by shapovalovei** [comment] 2017-05-10 07:31
Thanks for help.

**Closed** 2017-05-10 10:09 UTC

**Comment by abh7nav** [comment] 2017-05-12 09:08
I have one update. I have two ios 10.3.1 device. One works on my machine but other does not and same for my colleague the device working on my machine is not working for him and the one working for him is not working for me. Strange!!
