### ISSUE TITLE
[emulator issue] adb forward does not work for emulator  on Android Q emulator

### ISSUE THREAD

**Issue by rayt8909** [appium/appium#12754] opened 2019-06-11 20:25 UTC
## The problem
Create Android 9 Q emulator and ran test.  Received 
An unknown server-side error occurred while processing the command. Original error: The instrumentation process cannot be initialized within 9000ms timeout.  I attached the adb logcat and the appium log.  I shutdown the Android 9 Q emulator and started an Android 8 emulator, and everything worked as expected with the Android 8 emulator.  The only variable which changed between the two runs was the emualtor!  

## Environment

* Current Version:  Appium 1.13.0
* Last Appium version that did not exhibit the issue (if applicable): n/a 
* Desktop OS/version used to run Appium: Mac 10.14.4
* Node.js version (unless using Appium.app|exe): v11.13.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test:  Android 9 Q
* Real device or emulator/simulator: Android emulator
* Appium CLI or Appium.app|exe:  

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/rayt8909/6adfe539009d3ff87b7a36e0990abceb

## Link to adb logcat

https://gist.github.com/rayt8909/28f81600f75d10faf97001a8e59183aa

**Comment by mykola-mokhnach** [comment] 2019-06-11 21:20
> 06-11 14:33:25.788  2024  2024 E adbd    : failed to connect to socket 'tcp:6790': Operation not permitted

I assume this is the cause. Not sure why it happens tho. Perhaps Google added new restrictions on ports forwarding? @KazuCocoa do you know something about it?

**Comment by KazuCocoa** [comment] 2019-06-12 08:04
Mmm, not sure...
@rayt8909 What was your emulator's base revision?
You can see it in SDK manager

**Comment by rayt8909** [comment] 2019-06-12 12:47
From AVD Manager 
Q Anroid 9.+ x86_64
From SDK Manager 
Android 9.+(Q)

**Comment by rayt8909** [comment] 2019-06-12 13:18
I tried it with both the Android 9.+ emulator
and Android 9.+ (Google APis) emulator
same result

**Comment by KazuCocoa** [comment] 2019-06-12 19:27
I found https://issuetracker.google.com/issues/132325318
We should wait for their fix

**Comment by ABoterberg** [comment] 2019-06-21 09:40
Hi, I encountered the same issue. 
(copy from logcat:
06-21 11:35:02.069  2025  2025 E adbd    : failed to connect to socket 'tcp:6790': Operation not permitted
)
I will try downgrading from Q to fix.

**Comment by KazuCocoa** [comment] 2019-07-07 15:24
> please wait for beta 5

from the google issue tracker.

**Comment by rayt8909** [comment] 2019-07-22 19:27
Beta 5 is out.   I downloaded the appropriate emulator files from the beta channel.  The issue still remains.

**Comment by ABoterberg** [comment] 2019-07-23 06:32
The only solution I can add is: try out as many combinations of appium versions and the software you are using as you can. Suddenly as magic it stopped giving me this error.. I know it's not magic but hey.

**Comment by KazuCocoa** [comment] 2019-07-23 07:18
https://issuetracker.google.com/issues/132325318 says the error is remaining.
Please track the tracker (and react for it)

**Comment by mraphael2101** [comment] 2019-08-01 14:15
Hi @ABoterberg, I am facing the same issue. What versions worked for you in the end, please?

**Comment by mraphael2101** [comment] 2019-08-01 15:41
@ABoterberg I have tried: 
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>5.0.4</version> 
		</dependency>

with the following Appium Server versions :
1.7.1
1.8
1.13.0

None of them worked.

**Comment by ABoterberg** [comment] 2019-08-02 06:04
@mraphael2102

You need to think broader, are you running appium desktop? Have you tried different (android) versions of your emulator? I have been updating and my emulators are still working, but I am unable to deploy to a real devices so my fix is probably not the one you should look for. ;)

**Comment by mraphael2101** [comment] 2019-08-02 08:19
Hi, @ABoterberg,

I have tried with two different emulation devices, and I am getting the same results.
 
I have installed the Appium server from the command line. However, I also have the UI version installed which includes the inspector. When I update the framework from the command-line, the UI version is updated automatically; and is synchronised with the version installed from the commandline.

**Comment by ABoterberg** [comment] 2019-08-02 08:36
I have to manually update my command line and desktop appium versions separately. So you are already one step ahead of me..
Maybe try a lower android version? 
Like I said, I'm not an expert.. `
Maybe a full clean install? I'm just guessing at this point.

**Comment by KazuCocoa** [comment] 2019-08-02 08:42
I found revision 6 today. (On macOS env)

![image](https://user-images.githubusercontent.com/5511591/62356539-4158ee80-b54c-11e9-817b-bca431dc1088.png)

After I got the revision, created a new one with it and ran tests again on it.
Then, ruby_lib_core tests worked. 
Below is `Forwarding` message then.

```
...
[debug] [ADB] Current device property 'ro.build.version.sdk': 29
[debug] [ADB] Device API level: 29
...
[debug] [ADB] Install command stdout: Success
[debug] [UiAutomator2] Waiting up to 30000ms for services to be available
[debug] [ADB] Running '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm list instrumentation'
[debug] [UiAutomator2] Instrumentation target 'io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner' is available
[debug] [UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 8200
[debug] [ADB] Forwarding system: 8200 to device: 6790
[debug] [ADB] Running '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp\:8200 tcp\:6790'
[debug] [ADB] Checking app cert for /var/folders/34/2222sh8n27d6rcp7jqlkw8km0000gn/T/201972-70192-1nz83h0.xh1x/api.apk
[debug] [ADB] Starting '/Users/kazu/Library/Android/sdk/build-tools/28.0.3/apksigner' with args '["verify","--print-certs","/var/folders/34/2222sh8n27d6rcp7jqlkw8km0000gn/T/201972-70192-1nz83h0.xh1x/api.apk"]'
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
```

**Comment by mraphael2101** [comment] 2019-08-03 19:41
Hi, I have resolved the problem by downgrading the device to platform 9, and the chromedriver to v2.4. Many thanks.

**Comment by mykola-mokhnach** [comment] 2019-08-20 05:20
The issue seems to be fixed by google in recent sdk released

**Closed by mykola-mokhnach** 2019-08-20 05:20 UTC
Labels: NotABug, ThirdParty, UIAutomator2

**Comment by trjones87** [comment] 2019-09-11 18:24
Im still having issues on q/10. I was working with rayt8909 the OP. 
Ive tried every 10/Q option available in studio and I cant get it to run. When I switch back to any 6/7/8/9 device, no problem. 
![Screen Shot 2019-09-11 at 1 23 51 PM](https://user-images.githubusercontent.com/16565610/64724098-6b7cc500-d497-11e9-9c4e-f6d049406583.png)
help?!

**Comment by trjones87** [comment] 2019-09-11 18:25
![Screen Shot 2019-09-11 at 1 25 31 PM](https://user-images.githubusercontent.com/16565610/64724200-a54dcb80-d497-11e9-8191-ed36a2b20806.png)
SDKs that have been used
