### ISSUE TITLE
bug: Unable to create driver session on Android 13, Appium 2.0.0-beta.53 and uiautomator2@2.12.3

### ISSUE THREAD

**Issue by HarshdeepSingh3009** [appium/appium#18178] opened 2023-02-09 22:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, I am getting following exception everytime I try to create a new driver session.

**_An unknown server-side error occurred while processing the command. Original error: 'GET /appium/device/pixel_ratio' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details_**

I have tried removing io.appium.uiautomator2.server and test from the device and re running the test, but then It fails to find the connected device using adb, even though executing adb.exe devices shows the device. I get following error : 
_**OpenQA.Selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability**_

![Capture 3PNG](https://user-images.githubusercontent.com/22357961/217952607-8ede2811-3f78-43c1-bd24-9503853557d4.PNG)
![Capture1](https://user-images.githubusercontent.com/22357961/217952610-6abc93c7-789b-40fb-a7e4-afe117f77556.PNG)
![Capture2](https://user-images.githubusercontent.com/22357961/217952611-375ca4bc-a6a7-4868-840e-4e5248d79175.PNG)

### Expected Behavior

Appium should be able to start a driver session and execute the tests.

### Minimal Reproducible Example

Try creating driver session using Appium 2.0.0-beta.53
Fails to install the app under test. (Event though it gets installed does not get started)
Removing appium settings app from device and retry, gives one of the 2 error/exceptions mentioned above in post.
Restarting the device does not seem to help as well.

### Environment

- Operating system: Windows/Android
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.53
  - Node.js version (output of `node --version`):18.14.0
  - `npm` version (output of `npm --version`): 9.3.1
  - Last `appium` version which did _not_ exhibit the problem: 2.0.0-beta.46
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): uiautomator2@2.12.3
- Appium plugin(s) and their version(s): N/A
- Platform and version under test: Android 13 (Platform 33.0)
- Real device or emulator/simulator: Real device (samsung galaxy s21 & google pixel 7)

**Comment by mykola-mokhnach** [comment] 2023-02-10 06:59
The exception above is thrown by UiAutomator framework and has nothing to do with UIA2 driver itself. Maybe try to use another device to tun your automated tests. Closed as duplicate of https://github.com/appium/appium/issues?q=is%3Aissue+%22uiautomation+not+connected%22+is%3Aclosed

**Closed by mykola-mokhnach** 2023-02-10 06:59 UTC
Labels: Bug, Needs Triage

**Comment by amnajamshaid** [comment] 2023-05-17 11:37
how did you solve this issue? I am facing the same exception at the moment.
