### ISSUE TITLE
How to check IOS element selected

### ISSUE THREAD

**Issue by maggie5750** [appium/appium#13677] opened 2019-12-04 07:23 UTC
## The problem

How to check IOS element selected

## Environment

* Appium version (or git revision) that exhibits the issue: Appium1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details
When call element.isSelected(), Unhandled endpoint  error shows
## Link to Appium logs

Unhandled endpoint: /session/AFE8B1D4-FD6D-4878-AC68-A56AA9DF62C2/element/49010000-0000-0000-7FB2-000000000000/selected -- http://localhost:8110/ with parameters {
    wildcards =     (
        "session/AFE8B1D4-FD6D-4878-AC68-A56AA9DF62C2/element/49010000-0000-0000-7FB2-000000000000/selected"
    );
}

**Comment by mykola-mokhnach** [comment] 2019-12-04 07:36
Duplicate of https://github.com/appium/appium/issues/13441

The change is still in beta

**Closed by mykola-mokhnach** 2019-12-04 07:36 UTC

**Comment by maggie5750** [comment] 2019-12-04 07:46
@mykola-mokhnach  Will it be published in appium 1.16.0? Does appium1.16.0-rc0 support it?

**Comment by mykola-mokhnach** [comment] 2019-12-04 07:48
yes, v 1.16 will have this change
rc0 has a known [bug](https://github.com/appium/appium/issues/13660), so I wouldn't recommend using it

**Comment by maggie5750** [comment] 2019-12-04 07:49
OK. Many thanks.
