### ISSUE TITLE
Unable to click on right element

### ISSUE THREAD

**Issue by UserAutomation** [appium/appium#8167] opened 2017-04-04 12:14 UTC
## The problem
I am trying to automate an android app but the inspector is identifying wrong element. i tried accessing it through AccessibilityID, ContentDescription, Index number, getlocation and click ,through class in short all the possible way i think of.

My script run successfully but it clicks on wrong element.
as you see i want to click on "Die Wish App" but it clicks on "Einen Kuchen"

![screen shot 2017-03-31 at 14 41 49](https://cloud.githubusercontent.com/assets/26655798/24655751/cf576bae-193f-11e7-89ff-42d9a6ed65d3.png)

so i tried to switch to webview but script fails everytime at that line where it tries to switch context to webview.
I used cssselector too but i got an error that i can not use ccSelector strategy locator.
is there a way that i can successfully click on the right button even though inspector is identifying it at wrong place. 

I put a lot of time figuring out the solution and try to do every possible thing but no success even i tried this on real android device too.

## Environment

* Appium version 1.6 beta
* Mac 10.12.3
* Android 5.1
* Real device Android 5.1

## Details

Set<String> contextHandels2 = driver.getContextHandles();
        for (String s : contextHandels2){

            System.out.println("Context: "+ s);
            //Set webview
            if (s.contains("WEBVIEW")){
                driver.context(s);
         }

        driver.findElement(MobileBy.AccessibilityId("Die Wish App")).click();

**Comment by mykola-mokhnach** [comment] 2017-04-04 12:16
Duplicate of https://github.com/appium/appium/issues/8138

**Closed by mykola-mokhnach** 2017-04-04 12:16 UTC
Labels: NeedsTriage
