### ISSUE TITLE
is_displayed returns true when element doesnt exist in the screen view 

### ISSUE THREAD

**Issue by MummanaSubramanya** [appium/appium#16166] opened 2021-11-26 13:03 UTC
## 
I have scroll view and in that my element is at the bottom of the screen which not visible but is_displayed() is returning true.
My expectation is it should return false as its not visible on the screen.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Desktop
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 15
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: Appium.app

## Code To Reproduce Issue [ Good To Have ]
driver.find_element_by_accessibility_id(locator).is_displayed()

**Comment by mykola-mokhnach** [comment] 2021-11-26 13:19
Duplicate of https://github.com/appium/appium/issues/11507

Elements visibility is returned by XCTest. There's nothing we could do about it from Appium side.

**Closed by mykola-mokhnach** 2021-11-26 13:19 UTC
