### ISSUE TITLE
[Android, help] Stock Browser closes immediately when AVD starts on lock screen

### ISSUE THREAD

**Issue by haubey** [appium/appium#2841] opened 2014-06-12 19:12 UTC
Hi everybody, I've been playing around with Appium, and I've run into an issue. When I'm testing the stock browser in an emulator, starting from when the screen is locked, I see the screen unlock, the browser open, the screen lock, the browser open, and then finally the device goes to the home page, and after a few seconds Appium returns that it couldn't get a redirect from Chromedriver. Then, while the device is on the home screen, if I try to run my tests again, the same thing happens, but I get a slightly different log message. If I restart the emulator an unlock it manually before running the tests, the browser opens and the tests will work.

I'm running on an x86 emulator with HAXM on OSX 10.9, and my tests are running on a Windows machine (they're written in C#).. I've also run into this issue on non HAXM, and on an ARM emulator. I installed Appium from npm, and am running version 1.1.0.

My capabilities are
```
    capabilities.SetCapability("appium-version", "1.1");
    capabilities.SetCapability("platformName", "Android");
    capabilities.SetCapability("deviceName", "Android Emulator");
    capabilities.SetCapability("platformVersion", "4.4");
    capabilities.SetCapability("browserName", "Browser");
```

Here are the logs from Appium:
```
info: [ADB] Waiting for device to be ready and to respond to shell commands (timeout = 5)
debug: executing: "/Users/ultilab/android-sdk/platform-tools/adb" -s emulator-5554 wait-for-device
debug: executing: "/Users/ultilab/android-sdk/platform-tools/adb" -s emulator-5554 shell "echo 'ready'"
info: Starting logcat capture
debug: Pushing unlock helper app to device...
debug: executing: "/Users/ultilab/android-sdk/platform-tools/adb" -s emulator-5554 install "/usr/local/lib/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"
debug: executing: "/Users/ultilab/android-sdk/platform-tools/adb" -s emulator-5554 shell "dumpsys window"
info: Writing dumpsys output to /usr/local/lib/node_modules/appium/.dumpsys.log
debug: Screen is locked, trying to unlock
debug: executing: "/Users/ultilab/android-sdk/platform-tools/adb" -s emulator-5554 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
debug: executing: "/Users/ultilab/android-sdk/platform-tools/adb" -s emulator-5554 shell "dumpsys window"
info: Writing dumpsys output to /usr/local/lib/node_modules/appium/.dumpsys.log
debug: Screen is locked, trying to unlock
debug: executing: "/Users/ultilab/android-sdk/platform-tools/adb" -s emulator-5554 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
debug: executing: "/Users/ultilab/android-sdk/platform-tools/adb" -s emulator-5554 shell "dumpsys window"
info: Writing dumpsys output to /usr/local/lib/node_modules/appium/.dumpsys.log
debug: Screen is unlocked, continuing
info: Creating Chrome session
info: Ensuring Chromedriver exists
info: Killing any old chromedrivers, running: ps -e | grep /usr/local/lib/node_modules/appium/build/chromedriver/mac/chromedriver | grep -v grep |grep -e '--port=9515$' | awk '{ print $1 }' | xargs kill -15
info: Successfully cleaned up old chromedrivers
info: Spawning chromedriver with: /usr/local/lib/node_modules/appium/build/chromedriver/mac/chromedriver
info: [CHROMEDRIVER] Starting ChromeDriver (v2.9.248307) on port 9515
info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session","method":"POST","json":{"sessionId":null,"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"emulator-5554"}}}}
info: Could not connect yet; retrying
info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session","method":"POST","json":{"sessionId":null,"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"emulator-5554"}}}}
error: Chromedriver create session did not work. Status was 200 and body was {"sessionId":"bd0cf2d3e1f435ca63d3e932122aa1af","status":21,"value":{"message":"timeout: Adb command timed out after 30 seconds\n  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.9.3 x86_64)"}}
info: Cleaning up appium session
```

And when you run it after that,

```
debug: Screen already unlocked, continuing.
info: Creating Chrome session
info: Ensuring Chromedriver exists
info: Killing any old chromedrivers, running: ps -e | grep /usr/local/lib/node_modules/appium/build/chromedriver/mac/chromedriver | grep -v grep |grep -e '--port=9515$' | awk '{ print $1 }' | xargs kill -15
info: Chromedriver exited with code null
info: (killed by signal SIGTERM)
info: [ADB] Getting connected devices...
debug: executing: "/Users/ultilab/android-sdk/platform-tools/adb" -s emulator-5554 devices
info: Successfully cleaned up old chromedrivers
info: Spawning chromedriver with: /usr/local/lib/node_modules/appium/build/chromedriver/mac/chromedriver
info: [ADB] 1 device(s) connected
debug: executing: "/Users/ultilab/android-sdk/platform-tools/adb" -s emulator-5554 shell "am force-stop com.android.browser"
info: [CHROMEDRIVER] Starting ChromeDriver (v2.9.248307) on port 9515
info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session","method":"POST","json":{"sessionId":null,"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"emulator-5554"}}}}
info: Could not connect yet; retrying
info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session","method":"POST","json":{"sessionId":null,"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"emulator-5554"}}}}
info: Cleaning up appium session
```

Please let me know if you need anything else, and thanks for your help!

**Comment by sandy-adi** [comment] 2015-01-09 21:51
I'm seeing the same issue even without the unlock screen

**Comment by sandy-adi** [comment] 2015-01-13 14:46
@jlipps has the cause of this issue been identified?

**Comment by jlipps** [comment] 2015-01-15 19:00
No, but we have it assigned to a milestone which means we've considered it a verified bug that will be addressed

**Comment by mgaticah** [comment] 2015-03-04 14:52
Using Appium 1.3.4, locally i have this issue using AVD and default browser 

> info: [debug] Creating Chrome session
> info: [debug] Set chromedriver binary as: C:\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [debug] Ensuring Chromedriver exists
> info: [debug] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %b))
> info: [debug] No old chromedrivers seemed to exist
> info: [debug] Spawning chromedriver with: C:\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [debug] [CHROMEDRIVER] Starting ChromeDriver (v2.10.289383) on port 9515
> Only local connections are allowed.
> info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session","method":"POST","json":{"sessionId":null,"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"emulator-5554"}}}}
> error: Chromedriver create session did not work. Status was 200 and body was {"sessionId":"5bd107dc0a6660cade01b82003ae1c4e","status":21,"value":{"message":"timeout: Adb command timed out after 30 seconds\n  (Driver info: chromedriver=2.10.289383,platform=Windows NT 6.1 SP1 x86_64)"}}
> info: [debug] Cleaning up appium session
> error: Failed to start an Appium session, err was: Error: Did not get session redirect from Chromedriver
> info: [debug] Error: Did not get session redirect from Chromedriver
>     at null.<anonymous> (C:\Appium\node_modules\appium\lib\devices\android\chromedriver.js:222:12)
>     at Request._callback (C:\Appium\node_modules\appium\lib\devices\common.js:121:5)
>     at Request.self.callback (C:\Appium\node_modules\appium\node_modules\request\request.js:121:22)
>     at Request.EventEmitter.emit (events.js:98:17)
>     at Request.<anonymous> (C:\Appium\node_modules\appium\node_modules\request\request.js:985:14)
>     at Request.EventEmitter.emit (events.js:117:20)
>     at IncomingMessage.<anonymous> (C:\Appium\node_modules\appium\node_modules\request\request.js:936:12)
>     at IncomingMessage.EventEmitter.emit (events.js:117:20)
>     at _stream_readable.js:920:16
>     at process._tickDomainCallback (node.js:459:13)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Did not get session redirect from Chromedriver)","origValue":"Did not get session redirect from Chromedriver"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 61524.957 ms - 214 

But if locally i use same code and appium but Genymotion and Chrome instead of AVD and default browser, this works

And if f remotely i use same code and a saucelabs provided AVD and default browser,  that works properly as well.

Do you know if this kidn of issue would be solved soon?

**Comment by udayanem** [comment] 2015-03-11 09:13
Hi Jonah,

Most of the people who wanted to start hands on with Appium like me, is facing this issue, and we are not able to proceed further.

Even thought try and installing Chrome also difficult working with Emulators.

For this reason, can you are your time assign high prority to this issue and fixed at earliest.

Thanks,
Uday

**Comment by mgaticah** [comment] 2015-03-11 12:53
Few days ago i've tried this combo:

Appium 1.3.4 or higher
SDK AVD 4.4.2 + default browser 

and worked properly.

if i use a minor version of SDK AVD, 4.3 and lower, i get this chromedriver error.

**Comment by nayi01j** [comment] 2015-03-12 15:10
I am getting the error when using Androind 4.3 evethought it works fine on Android 4.4 and 5.0.

**Comment by moizjv** [comment] 2015-05-05 21:44
Similar issue https://github.com/appium/appium/issues/4689 Tracking it here

**Comment by jderrien** [comment] 2015-07-21 14:15
I'm trying to setup Selenium tests with Android and I've also seen the Android browser crashing. But I didn't see any error message in the logs. I'm using Appium 1.4.8 and Android 5.1.

So far I've found two different workarounds:
- Disable the lock screen (as reported before)
- Launch the Android emulator **after** I've launched Appium

Perhaps this second workaround would give a clue about the original issue.

**Comment by nathanbelles** [comment] 2015-09-27 18:26
If you are still having this problem, sometimes using a new sdcard image helps.

**Comment by SrinivasanTarget** [comment] 2016-05-07 06:06
@haubey please raise a new issue if you hit the same in Appium 1.5.2 along with logs inform of gist

**Comment by SrinivasanTarget** [comment] 2016-05-07 06:07
@triager please close

**Closed by SrinivasanTarget** 2016-05-07 06:07 UTC
