### ISSUE TITLE
iOS13 | Getting Original error: Unable to start WebDriverAgent session because of xcodebuild failure: A new session could not be created. Details: 'capabilities' is mandatory to create a new session 

### ISSUE THREAD

**Issue by AlonaPF** [appium/appium#13336] opened 2019-10-01 13:47 UTC
## The problem

I updated my device to iOS 13.1.1, and Xcode to v11 and got the error with running tests on real device that previously worked before update (iPhone 12.3 and xCode 10.x)

`Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: A new session could not be created. Details: 'capabilities' is mandatory to create a new session Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
`

## Environment

* Appium version - 1.16.0-beta.1
* Mac Mojave v 10.14.6 
* Node - v12.10.0
* Npm - 6.11.3
* iPhone X - v 13.1.1 real device
* Appium desktop - 1.13.0

## Details
I tried many ways from google:
1. I have executed all setup as per official https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md and i run the test in console that was successful for me using this command:

`xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=myudid' clean build test`

2. Also i trusted all developer's apps on my device as well.
Before running 
3. I removed WebdriverAgentRunner app from mobile when error occurred but did not help
4. I setup the project as per:
```
mkdir -p Resources/WebDriverAgent.bundle
./Scripts/bootstrap.sh -d
```
After doing all that - When i run a test using Appium i get the error :

```
Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: A new session could not be created. Details: 'capabilities' is mandatory to create a new session Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

  0) Community guide test Verify Community guide appears for community search
     Failure/Error: start_button.click

     Selenium::WebDriver::Error::UnknownError:
       An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: A new session could not be created. Details: 'capabilities' is mandatory to create a new session Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
     # UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: A new session could not be created. Details: 'capabilities' is mandatory to create a new session Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
     #     at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
     #     at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:37)
     #     at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Link to Appium logs

https://gist.github.com/AlonaPF/8178fc74dbe3cba94de810b98c22f635

## My Capabilities:

```
platformName = "iOS"
udid = "<myudid>"
app = "/Users/alona/Library/Developer/Xcode/DerivedData/mycompany-djidfmlzcxgtuigkwefhxspxrsdp/Build/Products/Debug-iphoneos/myapp Development.app"
platformVersion = "13.1.1"
automationName = 'XCUITest'
locationServicesAuthorized = true
newCommandTimeout = 10000
deviceName = "iPhone X test device"
xcodeOrgId = "mycode"
xcodeSigningId = "iPhone Developer"
useNewWDA = true
```

**Comment by mykola-mokhnach** [comment] 2019-10-01 13:53
This trick with WebDriverAgent replacement is not going to work, since it has been switched completely to work in W3C mode. The only way to make it working with Appium desktop is to install appium 1.15 via nom and connect to it via the app.

Closed as duplicate of https://github.com/appium/appium-desktop/issues/1096

**Closed by mykola-mokhnach** 2019-10-01 13:53 UTC
