### ISSUE TITLE
mobile:scroll on Android is hanging and not scrolling.

### ISSUE THREAD

**Issue by blane1988** [appium/appium#14418] opened 2020-06-05 18:40 UTC
## The problem

`mobile:scroll` is not working on Android. As per documentation, with Appium 1.18, you can pass in the strategy ('accessibility id') and selector ('~UI Explorer') in my case. 

The behavior should be that if selector is not on screen, then it will scroll and check visibility of element again. The issue is that, indeed, the selector '~UI Explorer' is not found, but it never scrolls after that. In the Appium logs, it keeps attempting to find the selector, over and over. It 404s on finding the element, but that is sensible, since the element is not yet visible.

I have verified that there is a top-level scrollable view that the command should default to as well.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0 and 1.18.0-beta0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOSX Mojave
* Node.js version (unless using Appium.app|exe): 12.16.1
* Npm or Yarn package manager: yarn
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Command that is not working:
`await driver.execute('mobile: scroll', {strategy: 'accessibility id', selector: '~UI Explorer'});`

Of interest is this part of the log:

![image](https://user-images.githubusercontent.com/42759546/83912446-808b3980-a733-11ea-9ef7-b2e1ee23ed2a.png)

It gets a 404 (from not finding the element intially I assume) and then 200 on /rect endpoint (presumably to get rectangle dimensions before scrolling), but then hangs when initiating scroll.

## Link to Appium logs
[Appium log](https://gist.github.com/blane1988/32aa8833763af1552b2862ebc87d7227)

**Comment by mykola-mokhnach** [comment] 2020-06-05 18:50
It looks like some modules are out of date. Try to reinstall appium@beta completely

**Comment by mykola-mokhnach** [comment] 2020-06-05 18:51
Duplicate of https://github.com/appium/appium/issues/14129

**Comment by blane1988** [comment] 2020-06-05 19:43
Thanks. I have removed old Appium stuff and am trying to install fresh. Getting a 400 on chromedriver dependency download at the moment when doing `yarn global add appium@beta`; trying to resolve.

**Comment by blane1988** [comment] 2020-06-05 21:22
Same issue using npm, but I used the `--chromedriver-skip-install` to bypass it, since it is not mission-critical. Regardless, my hybrid and browser testing still passed :).

Back to original issue, I see that the scroll command is failing at `JWProxy.command`:

<img width="935" alt="Screen Shot 2020-06-05 at 4 18 22 PM" src="https://user-images.githubusercontent.com/42759546/83923801-96572980-a748-11ea-90d2-3678ab868950.png">

**Comment by mykola-mokhnach** [comment] 2020-06-05 21:30
This does look like a bug. Try https://github.com/appium/appium-uiautomator2-driver/pull/401

**Comment by blane1988** [comment] 2020-06-05 22:21
Thanks for working on this. I tried just navigating to the `general.js` file on my machine and changed the endpoint being hit as per PR diff, but when I run the test again, it is still hitting old endpoint. Do I need to "recompile" something to see change? Or, how else can I pull your change into my existing Appium install?

**Comment by blane1988** [comment] 2020-06-05 22:37
It worked! Though I had to change the endpoint string within `build//lib/commands/general.js`, which is of course not checked in. Thanks a lot! Let's get this merged soon!

**Comment by mykola-mokhnach** [comment] 2020-06-06 05:29
The PR has been merged and published

**Closed by mykola-mokhnach** 2020-06-06 05:29 UTC
Labels: Bug, NeedsInfo, UIAutomator2
