### ISSUE TITLE
iOS app gets installed but does not start

### ISSUE THREAD

**Issue by sebastiandine** [appium/appium#12936] opened 2019-07-18 07:15 UTC
## The problem

I am developing a testautomation for a small app using Appium 1.14.0 and run it on an simulator with iOS 12.2. My problem is, that the app gets installed properly once I run the automation, but it does not start the app. There seems to be no problem with the app, since I can start it manually, once I click on the icon.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): unknown
* Desktop OS/version used to run Appium: Mac OS 10.14.5 with Xcode 10.2.1
* Node.js version (unless using Appium.app|exe): using Appium.app
* Npm or Yarn package manager: npm 6.4.1  
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.exe

## Details

Test automation gets started properly. The app gets installed automatically but it doesn't get launched.

## Link to Appium logs

https://gist.github.com/sebastiandine/1e1bfe856d90e56e776cf2afa77b0bc3

## Code To Reproduce Issue [ Good To Have ]

Here is the Appium config I use:
```json
            'deviceName': "iPhone X",
            'platformName': "iOS",
            'platformVersion': "12.2",
            'app': "MyApp.app",
            'bundleId': "org.sdine.MyApp",
            'newCommandTimeout': 6000,
            'automationName': "XCUITest"
```

**Comment by sebastiandine** [comment] 2019-07-18 10:25
Thanks for the support. Unfortunately I receive the following error message when executing above mentioned script:

```
(base) MB-DEV-SD:WebDriverAgent sdine$ ./Scripts/bootstrap.sh -d
Fetching dependencies
*** Checking out RoutingHTTPServer at "v1.0.2"
*** Checking out YYCache at "1.1.0"
*** Checking out CocoaAsyncSocket at "7.6.3"
*** xcodebuild output can be found in /var/folders/rb/txhm8kys5fd0b3k5rq55_7400000gp/T/carthage-xcodebuild.dWQXii.log
*** Downloading CocoaAsyncSocket.framework binary at "Version 7.6.3"
*** Building scheme "RoutingHTTPServer tvOS" in RoutingHTTPServer.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer/RoutingHTTPServer.xcodeproj -scheme RoutingHTTPServer\ tvOS -configuration Release -derivedDataPath /Users/sdine/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/RoutingHTTPServer/v1.0.2 -sdk appletvos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/rb/txhm8kys5fd0b3k5rq55_7400000gp/T/RoutingHTTPServer SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/rb/txhm8kys5fd0b3k5rq55_7400000gp/T/carthage-xcodebuild.dWQXii.log
```

Please find attached the log mentioned in the last line.
[carthage-xcodebuild.dWQXii.log](https://github.com/appium/appium/files/3406057/carthage-xcodebuild.dWQXii.log)

**Comment by mykola-mokhnach** [comment] 2019-07-18 10:40
You should never use sudo. Make sure the current user has r/w permissions in all these folders

**Comment by sebastiandine** [comment] 2019-07-18 11:06
Unfortunately granting permission to the corresponding folders does not solve this. As we can see in the log, there are some compilation errors.

**Comment by mykola-mokhnach** [comment] 2019-07-29 10:34
I would say the problem might be in some local build environment misconfiguration. Simply get your developers and try to compile the project with them to figure out what exactly the problem is. If you manage to compile WebDriverAgent sources manually then Appium should be able to do it as well.

**Comment by sebastiandine** [comment] 2019-07-30 09:25
But how can the build environment affect syntactical errors during compilation, like mentioned in the log?

**Comment by mykola-mokhnach** [comment] 2019-07-30 10:33
Duplicate of https://github.com/appium/appium/issues/12992

**Comment by mykola-mokhnach** [comment] 2019-07-30 10:33
> But how can the build environment affect syntactical errors during compilation, like mentioned in the log?

I cannot say that. Try to build the stuff on the other machine (preferably clean) and compare the output

**Closed by mykola-mokhnach** 2019-07-30 10:33 UTC
Labels: NotABug

**Comment by sebastiandine** [comment] 2019-07-31 13:02
#12992 provides a solution for this issue
