### ISSUE TITLE
Getting "Cannot find a match for DerivedData folder path from lsof. Trying to access logs" after running multiple test cases 

### ISSUE THREAD

**Issue by niu0220** [appium/appium#9289] opened 2017-09-25 00:23 UTC
## The problem

not able to run all test cases which can execute before upgrade xcode 11, and appium 1.7

## Environment

* Appium version (or git revision) that exhibits the issue: appium 1.7
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: 10.12.6 
* Node.js version (unless using Appium.app|exe):v8.4.0
* Mobile platform/version under test: iOS 10.3.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details

problem to running multiple test cases. there is no problem if only running less than 3-4 test cases, but not more than 5

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 

[appium.log](https://github.com/appium/appium/files/1327907/appium.log)

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2017-09-25 05:36
Duplicate of https://github.com/appium/appium/issues/9273

**Closed by mykola-mokhnach** 2017-09-25 05:36 UTC
