### ISSUE TITLE
UI inspector is not starting for Android

### ISSUE THREAD

**Issue by Nithingowda29** [appium/appium#10239] opened 2018-02-22 07:32 UTC
## The problem

I am trying to open the UI inspector for Android in MAC machine and I get the following error
Encountered internal error running command: Error: ENOENT: no such file or directory, scandir '/Library/Developer/Xamarin/android-sdk-macosx/build-tools'

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.3.1
* Desktop OS/version used to run Appium: macOS High Sierra v10.13
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android v 7.1 
* Real device or emulator/simulator:Android Emulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[/build-tools error](https://gist.github.com/Nithingowda29/64251828f7f1fb0252a912128c1ec679)

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2018-02-22 08:18
Make sure that Android SDK is properly installed and ANDROID_HOME environment variable points to the correct folder

**Comment by mykola-mokhnach** [comment] 2018-02-22 14:35
Thanks @trix0 . Closed as duplicate of https://github.com/appium/appium/issues/7686

**Closed by mykola-mokhnach** 2018-02-22 14:35 UTC
Labels: NeedsInfo, NotABug
