### ISSUE TITLE
getText() getAttribute("value") returns "" values instead of actual text

### ISSUE THREAD

**Issue by jagsme** [appium/appium#13495] opened 2019-10-27 06:02 UTC
## The problem
1. Compose a text "abcd"
2. Copy and paste the text in textbox
3. Identify element pasted
4. Get text value - getText() or getAttribute("value")

Instead of capturing "abcd" as it does in previous appium versions, the captured text is ""

## Environment

* Appium v1.15.1
* Desktop OS/version used to run Appium: Mac book pro 
* Mobile platform/version under test: iOS 12.3.1
* Real device or emulator/simulator: Real device

## Link to Appium logs

2019-10-27 05:54:00:207 [WD Proxy] Matched '/element' to command name 'findElement'
2019-10-27 05:54:00:208 [WD Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/4841EB02-6B8F-48FA-A6F4-14FDA32936E2/element] with body: {"using":"accessibility id","value":"msg_edit"}
2019-10-27 05:54:00:572 [WD Proxy] Got response with status 200: {"value":{"ELEMENT":"E7010000-0000-0000-6E01-000000000000","element-6066-11e4-a52e-4f735466cecf":"E7010000-0000-0000-6E01-000000000000"},"sessionId":"4841EB02-6B8F-48FA-A6F4-14FDA32936E2"}
2019-10-27 05:54:00:573 [W3C (a53d7bd5)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"E7010000-0000-0000-6E01-000000000000","ELEMENT":"E7010000-0000-0000-6E01-000000000000"}
2019-10-27 05:54:00:573 [HTTP] <-- POST /wd/hub/session/a53d7bd5-f7b2-4241-88bf-ab2bb381c566/element 200 368 ms - 137
2019-10-27 05:54:00:573 [HTTP] 
2019-10-27 05:54:00:575 [HTTP] --> GET /wd/hub/session/a53d7bd5-f7b2-4241-88bf-ab2bb381c566/element/E7010000-0000-0000-6E01-000000000000/text
2019-10-27 05:54:00:575 [HTTP] {}
2019-10-27 05:54:00:575 [W3C (a53d7bd5)] Driver proxy active, passing request on via HTTP proxy
2019-10-27 05:54:00:576 [XCUITest] Executing command 'proxyReqRes'
2019-10-27 05:54:00:577 [WD Proxy] Matched '/wd/hub/session/a53d7bd5-f7b2-4241-88bf-ab2bb381c566/element/E7010000-0000-0000-6E01-000000000000/text' to command name 'getText'
2019-10-27 05:54:00:577 [WD Proxy] Proxying [GET /wd/hub/session/a53d7bd5-f7b2-4241-88bf-ab2bb381c566/element/E7010000-0000-0000-6E01-000000000000/text] to [GET http://localhost:8100/session/4841EB02-6B8F-48FA-A6F4-14FDA32936E2/element/E7010000-0000-0000-6E01-000000000000/text] with body: {}
2019-10-27 05:54:00:917 [WD Proxy] Got response with status 200: {
2019-10-27 05:54:00:917 [WD Proxy]   "value" : "",
2019-10-27 05:54:00:917 [WD Proxy]   "sessionId" : "4841EB02-6B8F-48FA-A6F4-14FDA32936E2"
2019-10-27 05:54:00:918 [WD Proxy] }
2019-10-27 05:54:00:918 [WD Proxy] Replacing sessionId 4841EB02-6B8F-48FA-A6F4-14FDA32936E2 with a53d7bd5-f7b2-4241-88bf-ab2bb381c566
2019-10-27 05:54:00:918 [HTTP] <-- GET /wd/hub/session/a53d7bd5-f7b2-4241-88bf-ab2bb381c566/element/E7010000-0000-0000-6E01-000000000000/text 200 344 ms - 63
2019-10-27 05:54:00:918 [HTTP] 
2019-10-27 05:54:00:929 [HTTP] --> POST /wd/hub/session/a53d7bd5-f7b2-4241-88bf-ab2bb381c566/timeouts
2019-10-27 05:54:00:930 [HTTP] {"implicit":3000}

**Comment by mykola-mokhnach** [comment] 2019-10-27 07:34
Duplicate of https://github.com/appium/appium/issues/13288

**Closed by mykola-mokhnach** 2019-10-27 07:34 UTC
