### ISSUE TITLE
Long press generates nullpointer exception on Android 8

### ISSUE THREAD

**Issue by oscheller1** [appium/appium#11246] opened 2018-08-24 12:33 UTC
## The problem

Appium crashes with Nullpointerexception when long press is performed on android 8.0 on both simulator and real device. The long press is executed, but crashes shortly afterwards.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0 beta
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: Mac os
* Node.js version (unless using Appium.app|exe): 6.4.0
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs

Python stack trace
https://gist.github.com/oscheller1/f8fc59065b042580569be6c3627d26e6

Appium logs
https://gist.github.com/oscheller1/835320efcb8a20f70ab8b520d92d6f8c

## Code to reproduce

`TouchAction.long_press(el).release().perform()`

**Comment by mykola-mokhnach** [comment] 2018-08-24 13:37
This is a complex problem, but I would say it is more an issue with python client, since it still sends tap coordinates even if you only provide the element to tap.

**Comment by mykola-mokhnach** [comment] 2018-08-24 13:39
The problem is related to https://github.com/appium/appium/issues/10581

**Comment by mykola-mokhnach** [comment] 2018-08-24 19:45
The exception itself should be addressed by https://github.com/appium/appium-uiautomator2-server/pull/185

As for now you could try to workaround the issue by providing the absolute x, y tap coordinates instead of the element itself.

**Comment by oscheller1** [comment] 2018-08-27 06:35
The error still occurs when reading the coordinates from the element and feeding them into the x and y parameters of the long_press or press method. 
My workaround is to put the long press code into a `try` block and catch the error that is thrown.

**Comment by mykola-mokhnach** [comment] 2018-08-28 16:54
The NPE fix has been published in uia2 server v1.15.1

Regarding the other issue - closing it as duplicate.

**Closed by mykola-mokhnach** 2018-08-28 16:54 UTC
Labels: Bug, UIAutomator2
