### ISSUE TITLE
"POST /wda/touchAndHold" waiting for long time 

### ISSUE THREAD

**Issue by CodoonAutomatedTest** [appium/appium#8873] opened 2017-07-18 10:49 UTC
## Question:
      driver.tap([(198,487)],2000)

      why is waiting for long time? I hope that tap the element at 2000ms, but in fact cost 245690 ms?

## Environment
* IOS10  Xcuitest

## Link to Appium logs
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"longPress","options":{"y":487,"x":198,"duration":2000}},{"action":"release","options":{}}],"40fbb2bd-1355-499a-b755-6bd1d589f0ee"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: longPress(options={"y":487,"x":198,"duration":2000})-release(options={})
[debug] [XCUITest] Found matching gesture: longPress
[debug] [JSONWP Proxy] Proxying [POST /wda/touchAndHold] to [POST http://localhost:8100/session/EB04B1CC-0263-4DF7-B22D-13ACF3524494/wda/touchAndHold] with body: {"duration":2,"x":198,"y":487}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"EB04B1CC-0263-4DF7-B22D-13ACF3524494","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/40fbb2bd-1355-499a-b755-6bd1d589f0ee/touch/perform 200 245690 ms - 76

**Comment by mykola-mokhnach** [comment] 2017-07-18 14:28
Closed as duplicate of https://github.com/appium/appium/issues/8079

**Closed by mykola-mokhnach** 2017-07-18 14:28 UTC
