### ISSUE TITLE
UiAutomator2 can't find compose elements by id

### ISSUE THREAD

**Issue by JuanCarlos-Arceredillo** [appium/appium#18081] opened 2023-01-18 16:50 UTC
Appium 2.0.0-beta.35
UiAutomator2 2.7.0

I'm checking an application made with compose and I can see some elements with their resource-id in the app source tree, but searching by id the driver responses that there isn't any element with that id.

![Captura de Pantalla 2023-01-18 a las 17 11 33](https://user-images.githubusercontent.com/85676483/213232302-7b74f76c-9a9f-4163-bee2-37f2f79de41d.png)

![Captura de Pantalla 2023-01-18 a las 17 11 40](https://user-images.githubusercontent.com/85676483/213232351-e9bc8c9d-355f-4206-9944-9f6cfc016697.png)

![Captura de Pantalla 2023-01-18 a las 17 11 45](https://user-images.githubusercontent.com/85676483/213232395-498f5d63-ce04-4078-895a-9ea849bec62c.png)

I have verified that if I add the application prefix in the resource-id and I search it including it, appium can find them properly.
With other elements I don't have this issue and I can search them only by id.

**Comment by mykola-mokhnach** [comment] 2023-01-18 17:13
Possible duplicate of https://github.com/appium/appium/issues/15138#issuecomment-1127709588

**Comment by JuanCarlos-Arceredillo** [comment] 2023-01-19 07:59
Thank you for the information @mykola-mokhnach . 

Is there any way to run this settings command from the Appium Inspector? Just to verify that these ids are found properly.

**Comment by mykola-mokhnach** [comment] 2023-01-20 05:31
Please provide the updated server log and the actual page source

**Comment by JuanCarlos-Arceredillo** [comment] 2023-01-20 09:14
Hi @mykola-mokhnach 

I've attached the server log, the source page and the appium settings exported from the appium inspector.

[server_log.txt](https://github.com/appium/appium/files/10464826/server_log.txt)
[source.txt](https://github.com/appium/appium/files/10464827/source.txt)
![settings](https://user-images.githubusercontent.com/85676483/213658778-045a5152-e335-4692-b3ca-24a6fe2fe1b0.png)

Thank you

**Comment by mykola-mokhnach** [comment] 2023-01-24 17:31
Closed because of no response

**Closed by mykola-mokhnach** 2023-01-24 17:31 UTC
Labels: UIAutomator2, Needs Info

**Comment by smworks** [comment] 2024-07-09 06:22
I'm having the same issue. Here's my appium inspector screen log:
[app-source-2024-07-09T06_12_55.981Z.xml.txt](https://github.com/user-attachments/files/16138846/app-source-2024-07-09T06_12_55.981Z.xml.txt)
Inside there is visible element with id: onboarding_skip

If I use "Get TImings" feature in appium inspector, I can see that even appium inspector doesn't find the id as shown in appium console:
` Calling AppiumDriver.findElement() with args: ["id","onboarding_skip","d050ccb9-b35e-43e9-bec1-f13be016f6a6"]
[d050ccb9][AndroidUiautomator2Driver@4263] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
[d050ccb9][AndroidUiautomator2Driver@4263] Waiting up to 0 ms for condition
[d050ccb9][AndroidUiautomator2Driver@4263] Matched '/element' to command name 'findElement'
[d050ccb9][AndroidUiautomator2Driver@4263] Proxying [POST /element] to [POST http://127.0.0.1:8200/session/1a65cdf6-6843-40c3-9d56-215f33a348f3/element] with body: {"strategy":"id","selector":"onboarding_skip","context":"","multiple":false}
[d050ccb9][AndroidUiautomator2Driver@4263] Got response with status 404: {"sessionId":"1a65cdf6-6843-40c3-9d56-215f33a348f3","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:63)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:277)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:271)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:77)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann...
[d050ccb9][W3C] Matched W3C error code 'no such element' to NoSuchElementError
[d050ccb9][AndroidUiautomator2Driver@4263] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (/Users/m/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.ts:86:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)
    at AndroidUiautomator2Driver.findElement (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)
`

Should I just use xpath instead of ids?

**Comment by KazuCocoa** [comment] 2024-07-09 06:31
`disableIdLocatorAutocompletion` via settings api didn't help? (not capabilities)
https://github.com/appium/appium-uiautomator2-driver

**Comment by smworks** [comment] 2024-07-09 06:54
@KazuCocoa , thank you. Setting it to true seems to help. Test still crashes some runs, but after adding delays before each call it seems to work, so I guess now it's all up to my test logic to handle these cases.
