### ISSUE TITLE
Appium Hangs Up and throws 'UnreachableBrowserException' after a long Safari Test Run

### ISSUE THREAD

**Issue by MUI-Pop** [appium/appium#4949] opened 2015-04-17 16:53 UTC
Whenever I schedule a long Mobile Safari Test run the Test runs fine for the first 5-6 hours, later it throws 'UnreachableBrowserException' exception. But once Appium server is restarted , Test again goes well.

Looking at appium log:
1. Appium hangs up while 'Setting XCODE Folder'.

**Comment by jlipps** [comment] 2015-04-17 18:51
Can you please provide more of the logging around the part where it errors?

**Comment by jlipps** [comment] 2015-04-17 18:52
is this one 5-6 hour session, or many sessions that all together take 5-6 hours?

**Comment by MUI-Fazy** [comment] 2015-04-18 06:41
Its many sessions that take 5-6 hours, there are 500+ Tests, each test calls webdriver 'quit()' and its a new session for each test.

Following is the log, I have pasted only the portion from where Appium fails to respond to the client

2015-03-26 20:18:58:119 - [36minfo[39m: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"70695d24-2209-471e-9213-181f534f66e1"}
2015-03-26 20:18:58:119 - [36minfo[39m: [37m<-- DELETE /wd/hub/session/70695d24-2209-471e-9213-181f534f66e1 [39m[32m200[39m[90m 1031.768 ms - 76[39m [90m{"status":0,"value":null,"sessionId":"70695d24-2209-471e-9213-181f534f66e1"}[39m
2015-03-26 20:18:58:299 - [36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"safariOpenLinksInBackground":true,"newCommandTimeout":"3600","platformVersion":"8.1","browserName":"Safari","platformName":"iOS","deviceName":"iPhone 5","launchTimeout":"120000","nativeWebTap":false}}[39m
2015-03-26 20:18:58:300 - [36minfo[39m: Client User-Agent string: undefined
2015-03-26 20:18:58:300 - [36minfo[39m: [debug] Configuring Safari session
2015-03-26 20:18:58:300 - [36minfo[39m: [debug] We're on iOS8+ so not copying mobile safari app
2015-03-26 20:18:58:300 - [36minfo[39m: [debug] Creating new appium session 245ad884-05a0-4563-9306-147a8e6561e7
2015-03-26 20:18:58:300 - [36minfo[39m: [debug] Removing any remaining instruments sockets
2015-03-26 20:18:58:300 - [36minfo[39m: [debug] Cleaned up instruments socket /tmp/instruments_sock
2015-03-26 20:18:58:300 - [36minfo[39m: [debug] Setting Xcode folder
2015-03-26 20:18:58:307 - [36minfo[39m: [debug] Setting Xcode version
2015-03-26 20:18:58:375 - [36minfo[39m: [debug] Setting iOS SDK Version
2015-03-26 20:18:58:423 - [36minfo[39m: [debug] Getting sdk version from xcrun with a timeout
2015-03-26 20:18:58:428 - [36minfo[39m: [debug] iOS SDK Version set to 8.2
2015-03-26 20:18:58:428 - [36minfo[39m: [debug] Checking whether instruments supports our device string
2015-03-26 20:18:58:429 - [36minfo[39m: [debug] Getting list of devices instruments supports
2015-03-26 20:18:58:434 - [36minfo[39m: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
2015-03-26 20:19:01:578 - [36minfo[39m: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.2","iOSSDKVersion":"8.2","deviceName":"iPhone 5","platformVersion":"8.1"}
2015-03-26 20:19:01:578 - [36minfo[39m: [debug] fixDevice is on
2015-03-26 20:19:01:578 - [36minfo[39m: [debug] Final device string is: 'iPhone 5 (8.1 Simulator)'
2015-03-26 20:19:01:578 - [36minfo[39m: [debug] iOS sim UDID is 79590EB6-7618-4C8D-A00A-28612D368A13
2015-03-26 20:19:01:579 - [36minfo[39m: [debug] Detecting automation tracetemplate
2015-03-26 20:19:01:585 - [36minfo[39m: [debug] Not auto-detecting udid, running on sim
2015-03-26 20:19:01:585 - [36minfo[39m: [debug] Localizable.strings is not currently supported when using real devices.
2015-03-26 20:19:01:585 - [36minfo[39m: [debug] Creating instruments
2015-03-26 20:19:01:585 - [36minfo[39m: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
2015-03-26 20:19:01:585 - [36minfo[39m: [debug] Preparing uiauto bootstrap
2015-03-26 20:19:01:586 - [36minfo[39m: [debug] Dynamic bootstrap dir: /Users/autoteam/Library/Application Support/appium/bootstrap
2015-03-26 20:19:01:586 - [36minfo[39m: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.10.36/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"oneByOne"}
2015-03-26 20:19:01:588 - [36minfo[39m: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
2015-03-26 20:19:01:588 - [36minfo[39m: [debug] Dynamic bootstrap path: /Users/autoteam/Library/Application Support/appium/bootstrap/bootstrap-ecaa9641a54eb5b9.js
2015-03-26 20:19:01:589 - [36minfo[39m: [debug] Reusing dynamic bootstrap: /Users/autoteam/Library/Application Support/appium/bootstrap/bootstrap-ecaa9641a54eb5b9.js
2015-03-26 20:19:01:589 - [36minfo[39m: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.2","iOSSDKVersion":"8.2","deviceName":"iPhone 5","platformVersion":"8.1"}
2015-03-26 20:19:01:589 - [36minfo[39m: [debug] fixDevice is on
2015-03-26 20:19:01:589 - [36minfo[39m: [debug] Final device string is: 'iPhone 5 (8.1 Simulator)'
2015-03-26 20:19:01:590 - [36minfo[39m: [debug] Not setting device type since we're using bundle ID and assuming app is already installed
2015-03-26 20:19:01:590 - [36minfo[39m: [debug] Checking whether we need to set app preferences
2015-03-26 20:19:01:590 - [36minfo[39m: [debug] Reset not set, not ending sim or cleaning up app state
2015-03-26 20:19:01:590 - [36minfo[39m: [debug] Not setting locale
2015-03-26 20:19:01:590 - [36minfo[39m: [debug] Setting iOS and app preferences
2015-03-26 20:19:01:590 - [36minfo[39m: [debug] Setting opening links in background to true
2015-03-26 20:19:01:590 - [36minfo[39m: [debug] Updating settings for mobileSafari
2015-03-26 20:19:01:591 - [36minfo[39m: [debug] Getting current settings for mobileSafari from /Users/autoteam/Library/Developer/CoreSimulator/Devices/79590EB6-7618-4C8D-A00A-28612D368A13/data/Containers/Data/Application/29803C2A-DD27-449E-BFA1-023BF7485819/Library/Preferences/com.apple.mobilesafari.plist
2015-03-26 20:19:01:591 - [36minfo[39m: [debug] Writing settings for mobileSafari to /Users/autoteam/Library/Developer/CoreSimulator/Devices/79590EB6-7618-4C8D-A00A-28612D368A13/data/Containers/Data/Application/29803C2A-DD27-449E-BFA1-023BF7485819/Library/Preferences/com.apple.mobilesafari.plist:
2015-03-26 20:19:01:591 - [36minfo[39m: [debug] {"WebKitLocalStorageDatabasePathPreferenceKey":"/Users/autoteam/Library/Developer/CoreSimulator/Devices/79590EB6-7618-4C8D-A00A-28612D368A13/data/Containers/Data/Application/29803C2A-DD27-449E-BFA1-023BF7485819/Library/WebKit/WebsiteData/LocalStorage","CaptiveLandingPageGeneration":0,"LastCloudHistoryConfigurationUpdateTime":448975950.693628,"WebKitStorageTrackerEnabledPreferenceKey":true,"WebKitOfflineWebApplicationCacheEnabled":true,"WebKitLocalStorageEnabledPreferenceKey":true,"ShouldCheckHistoryStoreDatabaseIntegrity":true,"UniversalSearchUserGUIDExpirationDate":{},"UniversalSearchUserGUID":"1c86d6c9-c0fe-406a-620e-9686ca86ee4d","DidImportBuiltinBookmarks":true,"OpenLinksInBackground":1,"WebKitCacheModelPreferenceKey":2,"WebKitDiskImageCacheSavedCacheDirectory":"","WebDatabaseDirectory":"/Users/autoteam/Library/Developer/CoreSimulator/Devices/79590EB6-7618-4C8D-A00A-28612D368A13/data/Containers/Data/Application/29803C2A-DD27-449E-BFA1-023BF7485819/Library/WebKit/WebsiteData/WebSQL","WebKitShrinksStandaloneImagesToFit":true,"DidMigrateYouTubeBookmarks":true}
2015-03-26 20:19:01:592 - [36minfo[39m: [debug] Starting iOS 8.* simulator log capture
2015-03-26 20:19:01:596 - [36minfo[39m: [debug] Not pre-launching simulator
2015-03-26 20:19:01:597 - [36minfo[39m: [debug] Not installing to real device since we're on sim
2015-03-26 20:19:01:597 - [36minfo[39m: [debug] Starting command proxy.
2015-03-26 20:19:01:597 - [36minfo[39m: [debug] Instruments socket server started at /tmp/instruments_sock
2015-03-26 20:19:01:597 - [36minfo[39m: [debug] Starting instruments
2015-03-26 20:28:58:303 - [36minfo[39m: [37m<-- POST /wd/hub/session [39m[32m-[39m[90m - ms - -[39m [90m[39m
2015-03-26 20:29:00:515 - [36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"safariOpenLinksInBackground":true,"newCommandTimeout":"3600","platformVersion":"8.1","browserName":"Safari","platformName":"iOS","deviceName":"iPhone 5","launchTimeout":"120000","nativeWebTap":false}}[39m
2015-03-26 20:29:00:516 - [36minfo[39m: Client User-Agent string: undefined
2015-03-26 20:29:00:516 - [36minfo[39m: Found an existing session to clobber, shutting it down first...
2015-03-26 20:29:00:516 - [36minfo[39m: Shutting down appium session
2015-03-26 20:29:00:516 - [36minfo[39m: [debug] Stopping ios
2015-03-26 20:29:00:516 - [36minfo[39m: [debug] Closing socket server.
2015-03-26 20:29:00:516 - [36minfo[39m: [debug] Instruments socket server was closed
2015-03-26 20:39:00:519 - [36minfo[39m: [37m<-- POST /wd/hub/session [39m[32m-[39m[90m - ms - -[39m [90m[39m
2015-03-26 20:39:00:645 - [36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"safariOpenLinksInBackground":true,"newCommandTimeout":"3600","platformVersion":"8.1","browserName":"Safari","platformName":"iOS","deviceName":"iPhone 5","launchTimeout":"120000","nativeWebTap":false}}[39m
2015-03-26 20:39:00:645 - [36minfo[39m: Client User-Agent string: undefined
2015-03-26 20:39:00:645 - [36minfo[39m: [debug] Configuring Safari session
2015-03-26 20:39:00:645 - [36minfo[39m: [debug] We're on iOS8+ so not copying mobile safari app
2015-03-26 20:39:00:645 - [36minfo[39m: [debug] Creating new appium session 3aa14d62-24a5-4805-a127-79f4d3743628
2015-03-26 20:39:00:645 - [36minfo[39m: [debug] Removing any remaining instruments sockets
2015-03-26 20:39:00:645 - [36minfo[39m: [debug] Cleaned up instruments socket /tmp/instruments_sock
2015-03-26 20:39:00:645 - [36minfo[39m: [debug] Setting Xcode folder
2015-03-26 20:39:00:652 - [36minfo[39m: [debug] Setting Xcode version
2015-03-26 20:39:00:711 - [36minfo[39m: [debug] Setting iOS SDK Version
2015-03-26 20:39:00:759 - [36minfo[39m: [debug] Getting sdk version from xcrun with a timeout
2015-03-26 20:39:00:765 - [36minfo[39m: [debug] iOS SDK Version set to 8.2
2015-03-26 20:39:00:765 - [36minfo[39m: [debug] Checking whether instruments supports our device string
2015-03-26 20:39:00:765 - [36minfo[39m: [debug] Getting list of devices instruments supports
2015-03-26 20:39:00:770 - [36minfo[39m: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
2015-03-26 20:39:01:705 - [36minfo[39m: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.2","iOSSDKVersion":"8.2","deviceName":"iPhone 5","platformVersion":"8.1"}
2015-03-26 20:39:01:706 - [36minfo[39m: [debug] fixDevice is on
2015-03-26 20:39:01:706 - [36minfo[39m: [debug] Final device string is: 'iPhone 5 (8.1 Simulator)'
2015-03-26 20:39:01:706 - [36minfo[39m: [debug] iOS sim UDID is 79590EB6-7618-4C8D-A00A-28612D368A13
2015-03-26 20:39:01:706 - [36minfo[39m: [debug] Detecting automation tracetemplate
2015-03-26 20:39:01:713 - [36minfo[39m: [debug] Not auto-detecting udid, running on sim
2015-03-26 20:39:01:713 - [36minfo[39m: [debug] Localizable.strings is not currently supported when using real devices.
2015-03-26 20:39:01:713 - [36minfo[39m: [debug] Creating instruments
2015-03-26 20:39:01:713 - [36minfo[39m: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
2015-03-26 20:39:01:713 - [36minfo[39m: [debug] Preparing uiauto bootstrap
2015-03-26 20:39:01:713 - [36minfo[39m: [debug] Dynamic bootstrap dir: /Users/autoteam/Library/Application Support/appium/bootstrap
2015-03-26 20:39:01:713 - [36minfo[39m: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.10.36/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"oneByOne"}
2015-03-26 20:39:01:716 - [36minfo[39m: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
2015-03-26 20:39:01:716 - [36minfo[39m: [debug] Dynamic bootstrap path: /Users/autoteam/Library/Application Support/appium/bootstrap/bootstrap-ecaa9641a54eb5b9.js
2015-03-26 20:39:01:717 - [36minfo[39m: [debug] Reusing dynamic bootstrap: /Users/autoteam/Library/Application Support/appium/bootstrap/bootstrap-ecaa9641a54eb5b9.js
2015-03-26 20:39:01:717 - [36minfo[39m: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.2","iOSSDKVersion":"8.2","deviceName":"iPhone 5","platformVersion":"8.1"}
2015-03-26 20:39:01:717 - [36minfo[39m: [debug] fixDevice is on
2015-03-26 20:39:01:717 - [36minfo[39m: [debug] Final device string is: 'iPhone 5 (8.1 Simulator)'
2015-03-26 20:39:01:717 - [36minfo[39m: [debug] Not setting device type since we're using bundle ID and assuming app is already installed
2015-03-26 20:39:01:717 - [36minfo[39m: [debug] Checking whether we need to set app preferences
2015-03-26 20:39:01:717 - [36minfo[39m: [debug] Reset not set, not ending sim or cleaning up app state
2015-03-26 20:39:01:717 - [36minfo[39m: [debug] Not setting locale
2015-03-26 20:39:01:717 - [36minfo[39m: [debug] Setting iOS and app preferences
2015-03-26 20:39:01:718 - [36minfo[39m: [debug] Setting opening links in background to true
2015-03-26 20:39:01:718 - [36minfo[39m: [debug] Updating settings for mobileSafari
2015-03-26 20:39:01:718 - [36minfo[39m: [debug] Getting current settings for mobileSafari from /Users/autoteam/Library/Developer/CoreSimulator/Devices/79590EB6-7618-4C8D-A00A-28612D368A13/data/Containers/Data/Application/29803C2A-DD27-449E-BFA1-023BF7485819/Library/Preferences/com.apple.mobilesafari.plist
2015-03-26 20:39:01:718 - [36minfo[39m: [debug] Writing settings for mobileSafari to /Users/autoteam/Library/Developer/CoreSimulator/Devices/79590EB6-7618-4C8D-A00A-28612D368A13/data/Containers/Data/Application/29803C2A-DD27-449E-BFA1-023BF7485819/Library/Preferences/com.apple.mobilesafari.plist:
2015-03-26 20:39:01:718 - [36minfo[39m: [debug] {"WebKitLocalStorageDatabasePathPreferenceKey":"/Users/autoteam/Library/Developer/CoreSimulator/Devices/79590EB6-7618-4C8D-A00A-28612D368A13/data/Containers/Data/Application/29803C2A-DD27-449E-BFA1-023BF7485819/Library/WebKit/WebsiteData/LocalStorage","CaptiveLandingPageGeneration":0,"LastCloudHistoryConfigurationUpdateTime":448975950.693628,"WebKitStorageTrackerEnabledPreferenceKey":true,"WebKitOfflineWebApplicationCacheEnabled":true,"WebKitLocalStorageEnabledPreferenceKey":true,"ShouldCheckHistoryStoreDatabaseIntegrity":true,"UniversalSearchUserGUIDExpirationDate":{},"UniversalSearchUserGUID":"1c86d6c9-c0fe-406a-620e-9686ca86ee4d","DidImportBuiltinBookmarks":true,"OpenLinksInBackground":1,"WebKitCacheModelPreferenceKey":2,"WebKitDiskImageCacheSavedCacheDirectory":"","WebDatabaseDirectory":"/Users/autoteam/Library/Developer/CoreSimulator/Devices/79590EB6-7618-4C8D-A00A-28612D368A13/data/Containers/Data/Application/29803C2A-DD27-449E-BFA1-023BF7485819/Library/WebKit/WebsiteData/WebSQL","WebKitShrinksStandaloneImagesToFit":true,"DidMigrateYouTubeBookmarks":true}
2015-03-26 20:39:01:724 - [36minfo[39m: [debug] Starting iOS 8.* simulator log capture
2015-03-26 20:39:01:729 - [36minfo[39m: [debug] Not pre-launching simulator
2015-03-26 20:39:01:729 - [36minfo[39m: [debug] Not installing to real device since we're on sim
2015-03-26 20:39:01:729 - [36minfo[39m: [debug] Starting command proxy.
2015-03-26 20:39:01:729 - [36minfo[39m: [debug] Instruments socket server started at /tmp/instruments_sock
2015-03-26 20:39:01:730 - [36minfo[39m: [debug] Starting instruments
2015-03-26 20:49:00:653 - [36minfo[39m: [37m<-- POST /wd/hub/session [39m[32m-[39m[90m - ms - -[39m [90m[39m
2015-03-26 20:49:02:863 - [36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"safariOpenLinksInBackground":true,"newCommandTimeout":"3600","platformVersion":"8.1","browserName":"Safari","platformName":"iOS","deviceName":"iPhone 5","launchTimeout":"120000","nativeWebTap":false}}[39m
2015-03-26 20:49:02:863 - [36minfo[39m: Client User-Agent string: undefined
2015-03-26 20:49:02:864 - [36minfo[39m: Found an existing session to clobber, shutting it down first...
2015-03-26 20:49:02:864 - [36minfo[39m: Shutting down appium session
2015-03-26 20:49:02:864 - [36minfo[39m: [debug] Stopping ios
2015-03-26 20:49:02:864 - [36minfo[39m: [debug] Closing socket server.
2015-03-26 20:49:02:864 - [36minfo[39m: [debug] Instruments socket server was closed
2015-03-26 20:59:02:869 - [36minfo[39m: [37m<-- POST /wd/hub/session [39m[32m-[39m[90m - ms - -[39m [90m[39m
2015-03-26 20:59:05:613 - [36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"safariOpenLinksInBackground":true,"newCommandTimeout":"3600","platformVersion":"8.1","browserName":"Safari","platformName":"iOS","deviceName":"iPhone 5","launchTimeout":"120000","nativeWebTap":false}}[39m
2015-03-26 20:59:05:613 - [36minfo[39m: Client User-Agent string: undefined
2015-03-26 20:59:05:614 - [36minfo[39m: [debug] Configuring Safari session
2015-03-26 20:59:05:614 - [36minfo[39m: [debug] We're on iOS8+ so not copying mobile safari app
2015-03-26 20:59:05:614 - [36minfo[39m: [debug] Creating new appium session 8ee4d537-1710-47ec-81ee-1e8bf8216d68
2015-03-26 20:59:05:614 - [36minfo[39m: [debug] Removing any remaining instruments sockets
2015-03-26 20:59:05:614 - [36minfo[39m: [debug] Cleaned up instruments socket /tmp/instruments_sock
2015-03-26 20:59:05:614 - [36minfo[39m: [debug] Setting Xcode folder
2015-03-26 21:09:05:619 - [36minfo[39m: [37m<-- POST /wd/hub/session [39m[32m-[39m[90m - ms - -[39m [90m[39m
2015-03-26 21:09:07:630 - [36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"safariOpenLinksInBackground":true,"newCommandTimeout":"3600","platformVersion":"8.1","browserName":"Safari","platformName":"iOS","deviceName":"iPhone 5","launchTimeout":"120000","nativeWebTap":false}}[39m
2015-03-26 21:09:07:631 - [36minfo[39m: Client User-Agent string: undefined
2015-03-26 21:09:07:631 - [36minfo[39m: Found an existing session to clobber, shutting it down first...
2015-03-26 21:09:07:631 - [36minfo[39m: Shutting down appium session
2015-03-26 21:09:07:631 - [36minfo[39m: [debug] Stopping ios
2015-03-26 21:09:07:631 - [36minfo[39m: [debug] Trying to stop instruments but it already exited
2015-03-26 21:09:07:631 - [36minfo[39m: [debug] Reset not set, not ending sim or cleaning up app state
2015-03-26 21:09:07:631 - [36minfo[39m: [debug] Cleaning up appium session
2015-03-26 21:09:07:631 - [36minfo[39m: Old session shut down OK, proceeding to new session
2015-03-26 21:09:07:631 - [36minfo[39m: [debug] Configuring Safari session
2015-03-26 21:09:07:631 - [36minfo[39m: [debug] We're on iOS8+ so not copying mobile safari app
2015-03-26 21:09:07:632 - [36minfo[39m: [debug] Creating new appium session f3342b71-a5af-4de9-8561-09a9b89649a9
2015-03-26 21:09:07:632 - [36minfo[39m: [debug] Removing any remaining instruments sockets
2015-03-26 21:09:07:632 - [36minfo[39m: [debug] Cleaned up instruments socket /tmp/instruments_sock
2015-03-26 21:09:07:632 - [36minfo[39m: [debug] Setting Xcode folder

**Comment by MUI-Fazy** [comment] 2015-04-23 08:43
Do you need any further logs ? or this is ok ?

**Comment by jlipps** [comment] 2015-05-05 22:19
can you try without --session-override?

**Comment by MUI-Fazy** [comment] 2015-05-06 12:29
Yes, I have already tried without '--session-override' flag, but it was the same.

**Comment by Jonahss** [comment] 2015-05-08 00:16
Ok well this is a bug then. Reproduction would be to run 500 tests for 5-6 hours and look for it happening -_-

Workaround is to periodically restart appium every couple hours...

**Comment by MUI-Fazy** [comment] 2015-05-08 10:50
My Current workaround is to restart appium only when the exception occurs.

**Comment by Jonahss** [comment] 2015-05-08 17:23
Ah ok. That's reasonable. We should test this and figure out where the issue is though.

**Closed** 2017-07-19 15:28 UTC
Labels: Bug
