### ISSUE TITLE
iOS tries to install myapp.app file from some random directory instead of the specified .ipa file

### ISSUE THREAD

**Issue by rubinshteyn89** [appium/appium#17385] opened 2022-08-19 18:54 UTC
## The problem
On iOS, appium tries to install myapp.app file from some random directory instead of the specified .ipa file

Message: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not install '/var/folders/6s/y12j3y2j3497pv0509mg0z4h0000gn/T/2022718-58623-1hxig02.zrq2/myApp.app':

How do I prevent appium from looking in this directory for this random myApp.app file?

In Capabilities I specify:
caps.setCapability("app", new File(IPA_PATH).getAbsolutePath());

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac OSX 12.4
* Node.js version (unless using Appium.app|exe): v16.11.1
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: iOS (all versions that I have)
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
(https://gist.github.com/rubinshteyn89/e7a85da18c039f68f168546a69dc7a6e)

**Comment by mykola-mokhnach** [comment] 2022-08-20 15:33
This is expected. .ipa files cannot be installed on their own. An .app bundle must be extracted first and stored into a cache (which is this temporary path is). A direct path to a local .app bundle must be provided in order to prevent caching.

**Comment by rubinshteyn89** [comment] 2022-08-22 17:01
Is this something thats set in capabilites?

**Comment by mykola-mokhnach** [comment] 2022-08-22 18:12
sorry, I don't understand the question

**Comment by rubinshteyn89** [comment] 2022-08-22 18:18
sorry, i meant where do i set a direct path to a local .app bundle? I currently set this in capabilities:
caps.setCapability("app", new File("/Users/user/desktop/myApp.ipa").getAbsolutePath());

**Comment by jlipps** [comment] 2022-08-22 20:06
You need to have the local .app bundle. If you do, just set the path to it using that same capability. If all you have is the ipa, then just do what you are doing. Things are working as intended.

The fact that Appium couldn't install the app inside the .ipa file is a separate problem, probably to do with your app (maybe built for the wrong architecture, for example).

**Comment by mykola-mokhnach** [comment] 2022-08-24 11:59
Closed as not an issue

**Closed by mykola-mokhnach** 2022-08-24 11:59 UTC
Labels: NotABug
