### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by liangyuan531** [appium/appium#10850] opened 2018-06-12 01:41 UTC
## The problem
I try to use Appium to get element, but it turns to be black. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Win10
* Node.js version (unless using Appium.app|exe): 8.11.1
* Mobile platform/version under test: Pixel XL  android P
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: appium.exe

## Link to Appium logs
[HTTP] 
[HTTP] --> GET /wd/hub/session/5e588cd3-cf1e-4f8e-9571-78ef8c2502e6/screenshot
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["5e588cd3-cf1e-4f8e-9571-78ef8c2502e6"]
[JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8200/wd/hub/session/1e407bc0-0aa0-4483-b40c-cb1df7b4ccec/screenshot] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"1e407bc0-0aa0-4483-b40c-cb1df7b4ccec\",\"status\":0,\"value\":\"iVBORw0KGgoAAAANSUhEUgAABaAAAAoACAIAAADIlhKYAAAAAXNSR0IArs4c6QAAAANzQklUCAgI\\n2+FP4AAAIABJREFUeJzswQEBAAAAgJD+r+4ICgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABaAAAAoACAIAAADIlhKYAAAAAXNSR0IArs4c6QAAAANzQklUCAgI\n2+FP4AAAIABJREFUeJzswQEBAAAAgJD+r+4ICgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAA...
[HTTP] <-- GET /wd/hub/session/5e588cd3-cf1e-4f8e-9571-78ef8c2502e6/screenshot 200 533 ms - 14940
[HTTP] 
[HTTP] --> GET /wd/hub/session/5e588cd3-cf1e-4f8e-9571-78ef8c2502e6/window/current/size
[HTTP] {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [GET /wd/hub/session/5e588cd3-cf1e-4f8e-9571-78ef8c2502e6/window/current/size] to [GET http://localhost:8200/wd/hub/session/1e407bc0-0aa0-4483-b40c-cb1df7b4ccec/window/current/size] with body: {}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"1e407bc0-0aa0-4483-b40c-cb1df7b4ccec\",\"status\":0,\"value\":{\"height\":2392,\"width\":1440}}"
[JSONWP Proxy] Replacing sessionId 1e407bc0-0aa0-4483-b40c-cb1df7b4ccec with 5e588cd3-cf1e-4f8e-9571-78ef8c2502e6
[HTTP] <-- GET /wd/hub/session/5e588cd3-cf1e-4f8e-9571-78ef8c2502e6/window/current/size 200 12 ms - 100
[HTTP] 
[HTTP] --> POST /wd/hub/session/5e588cd3-cf1e-4f8e-9571-78ef8c2502e6/elements
[HTTP] {"using":"xpath","value":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.LinearLayout"}
[MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.LinearLayout","5e588cd3-cf1e-4f8e-9571-78ef8c2502e6"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8200/wd/hub/session/1e407bc0-0aa0-4483-b40c-cb1df7b4ccec/elements] with body: {"strategy":"xpath","selector":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.LinearLayout","context":"","multiple":true}
[JSONWP Proxy] Got response with status 200: {"sessionId":"1e407bc0-0aa0-4483-b40c-cb1df7b4ccec","status":0,"value":[{"ELEMENT":"c1747bc3-ecf8-4b01-b944-050f900bbaca"}]}
[MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"c1747bc3-ecf8-4b01-b944-050f900bbaca"}]
[HTTP] <-- POST /wd/hub/session/5e588cd3-cf1e-4f8e-9571-78ef8c2502e6/elements 200 78 ms - 124
[HTTP] 
[HTTP] --> POST /wd/hub/session/5e588cd3-cf1e-4f8e-9571-78ef8c2502e6/elements
[HTTP] {"using":"xpath","value":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.RelativeLayout[1]"}
[MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.RelativeLayout[1]","5e588cd3-cf1e-4f8e-9571-78ef8c2502e6"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8200/wd/hub/session/1e407bc0-0aa0-4483-b40c-cb1df7b4ccec/elements] with body: {"strategy":"xpath","selector":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.RelativeLayout[1]","context":"","multiple":true}
[JSONWP Proxy] Got response with status 200: {"sessionId":"1e407bc0-0aa0-4483-b40c-cb1df7b4ccec","status":0,"value":[{"ELEMENT":"21b41494-71d0-4a05-bf6e-85692920dd5e"}]}
[MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"21b41494-71d0-4a05-bf6e-85692920dd5e"}]
[HTTP] <-- POST /wd/hub/session/5e588cd3-cf1e-4f8e-9571-78ef8c2502e6/elements 200 76 ms - 124
[HTTP] 
[HTTP] --> POST /wd/hub/session/5e588cd3-cf1e-4f8e-9571-78ef8c2502e6/elements
[HTTP] {"using":"id","value":"android:id/content"}
[MJSONWP] Calling AppiumDriver.findElements() with args: ["id","android:id/content","5e588cd3-cf1e-4f8e-9571-78ef8c2502e6"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8200/wd/hub/session/1e407bc0-0aa0-4483-b40c-cb1df7b4ccec/elements] with body: {"strategy":"id","selector":"android:id/content","context":"","multiple":true}
[JSONWP Proxy] Got response with status 200: {"sessionId":"1e407bc0-0aa0-4483-b40c-cb1df7b4ccec","status":0,"value":[{"ELEMENT":"39d6edc8-3180-47be-bce9-be2130f09a19"}]}
[MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"39d6edc8-3180-47be-bce9-be2130f09a19"}]
[HTTP] <-- POST /wd/hub/session/5e588cd3-cf1e-4f8e-9571-78ef8c2502e6/elements 200 40 ms - 124
[HTTP] 

![capture](https://user-images.githubusercontent.com/28596163/41265413-7e6dcfde-6e35-11e8-8cd2-fb301148c832.PNG)

**Comment by mykola-mokhnach** [comment] 2018-06-12 05:33
I don't observe any issues in the log. Can you please properly describe what the problem is?

**Comment by liangyuan531** [comment] 2018-06-12 05:36
@mykola-mokhnach  yes, no issues in the log. just as the screenshot, it shows as black not the pages of app.

**Comment by mykola-mokhnach** [comment] 2018-06-12 05:41
What if you try to take a screenshot manually with screencap utility on the same page? Is it also black? I assume the application under test might have some protection from screenshoting, since Appium simply uses the native screenshoting function provided by UIA2 framework. There is no magic.

**Comment by liangyuan531** [comment] 2018-06-12 05:43
@mykola-mokhnach  it is always black, no matter what you use to make a screenshot

**Comment by mykola-mokhnach** [comment] 2018-06-12 05:45
Then it must be  a problem with the app itself or with the device. In both cases we cannot help.

**Comment by mykola-mokhnach** [comment] 2018-06-13 07:39
Closed as third party issue

**Closed by mykola-mokhnach** 2018-06-13 07:39 UTC
Labels: NeedsInfo, ThirdParty, UIAutomator2
