### ISSUE TITLE
org.openqa.selenium.WebDriverException:  An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity

### ISSUE THREAD

**Issue by avanishf** [appium/appium#9898] opened 2018-01-03 01:49 UTC
## The problem
Trying to run an appium test in CI tool bitrise and seems to be throwing an issue : 

WebDriverException saying : org.openqa.selenium.WebDriverException: 
An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity (WARNING: The server did not provide any stacktrace information)

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable): latest version
* Desktop OS/version used to run Appium: MacOS Sierra
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 4.3.1
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Details
Following is the script in Bitrise which will try to run a sample UI test :

    #!/bin/bash

    find / -name *.apk

    set -ex
    npm install -g npm@4.0.5
    npm install -g appium
    appium &>/dev/null &

    mvn -v

    adb devices

    sudo cp /bitrise/deploy/app-local* app/src/test/sniip-testing.apk
    sudo cp app/src/pom.xml /bitrise/src/pom.xml

    mvn test

But its fails giving an issue saying :
org.openqa.selenium.WebDriverException:org.openqa.selenium.WebDriverException: 
An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 99.21 seconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 't20180102220153-br-cont-prod-c2-x--host-ondemand-android-019', ip: '10.240.0.17', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-57-generic', java.version: '1.8.0_151'
Driver info: driver.version: AndroidDriver
	at com.sniip.androidapp.testCases.UX107Logout.userStory209LogoutTest.beforeMethod(userStory209LogoutTest.java:14)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   userStory209LogoutTest.beforeMethod:14->Utils.setUp:92 » WebDriver An unknown ...
[INFO] 
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 2
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:18 min
[INFO] Finished at: 2018-01-02T22:16:57+00:00
[INFO] Final Memory: 27M/307M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project Sniip2.0: There are test failures.

## Link to Appium logs
https://gist.github.com/avanishf/4f58d4329f1a2a3b8c113f69ed4e89ae

## Code To Reproduce Issue [ Good To Have ]

Desired capabilities set :

    case "Android":
    try {
	DesiredCapabilities capabilities = new DesiredCapabilities();
	capabilities.setCapability("deviceName", "emulator-5554");
	capabilities.setCapability("platformVersion", "8.0");
	capabilities.setCapability("platformName", "Android");
	capabilities.setCapability("app", Paths.get(".").toAbsolutePath().normalize().toString() + 
        apkPath);
	capabilities.setCapability("appPackage", "com.sniip.androidapp." + 
        getAndroidEnvironmentProperties().replaceAll("\\s", ""));
	capabilities.setCapability("appActivity", "com.sniip.androidapp.activities.HomeActivity");
	capabilities.setCapability("noReset", true);
	capabilities.setCapability("skipUnlock", true);

	driver = new AndroidDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"), 
        capabilities);
	}

       catch (NoSuchElementException nse) {
	System.out.println("<<--APP NOT FOUND-->>" + nse.getMessage());
        }
	break;

**Comment by avanishf** [comment] 2018-01-03 02:00
Scenario 1 : When emulator is kept unlocked -
The same test runs locally, it will install the app and run a test. But not in the CI..wonder what makes a difference. 

Scenario 2 : When emulator is kept locked and run on a local machine, logs : 
https://gist.github.com/avanishf/dc32f19f27595f51e14fc49b0df47ec9

**Comment by avanishf** [comment] 2018-01-03 06:07
I also tried installing the latest version of appium using command : npm install appium@1.7.2-beta5 
but still pointing to the older version 1.7.1 which is bit strange. I also uninstalled older version and reinstalled the new bt didn't work either.

**Comment by mykola-mokhnach** [comment] 2018-01-03 06:43
Duplicate of https://github.com/appium/appium/issues/8868

**Closed by mykola-mokhnach** 2018-01-03 06:43 UTC
