### ISSUE TITLE
[iOS-RealDevice] Uncaught Error: Failed to receive any data within the timeout: 5000 error in some environment

### ISSUE THREAD

**Issue by alvarolgn** [appium/appium#16399] opened 2022-02-01 21:44 UTC
## The problem

I cannot execute in iOS Real Devices after my upgrade to Appium 2 due to a 500 error creating /wd/hub/session. After a long time investigating (appium and xcuitest reinstall, different combinations of Signing Capabilities for WebDriverAgentRunner compilation, rebooting mac and iPhones) I don't know what is going wrong her. This is my [client side error](https://gist.github.com/alvarolgn/d026d8cd7f5573cfe4e2be557f7fdafe)

## Environment

- Appium v2.0.0-beta.25
- xcuitest@3.62.0 (automationName 'XCUITest')
- relaxed-caps@1.0.3 (ACTIVE)
- execute-driver@1.0.1
- XCode version: 13.2.1 
- macOS 12.1 (21C52)
- iOS 15.3 and iOS14.2

## Link to Appium logs

[no_cached_connections](https://gist.github.com/alvarolgn/76c9843bc86903bf3c599a0d69186569)

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2022-02-01 22:01
The error in logs means that there was a failure while connecting to the device's lockdown daemon in order to establish a local proxy to it. Unfortunately it might be device-specific, so try to run your tests with another device as a possible workaround.

**Comment by alvarolgn** [comment] 2022-02-02 08:30
@mykola-mokhnach , thanks by your quick response 😃 
My Mac is on a different network than my iPhone, could it be the cause of the problem?

**Comment by mykola-mokhnach** [comment] 2022-02-02 08:35
If you phone is connected via WiFi rather than via USB then it won't work. XCUITest driver does not support wirelessly connected iOS devices

**Comment by alvarolgn** [comment] 2022-02-02 08:41
Yes, my phone is connected via USB to my Mac so thats why I think it is supposed to work... But it doesn't 😞

**Comment by mykola-mokhnach** [comment] 2022-02-02 09:01
USB is supposed to work, but like I said there are some phones that don't properly expose lockdown functionality. Please try to replace the hardware.

**Comment by alvarolgn** [comment] 2022-02-02 09:07
One of the phones is new  but I've been using the other one for next to one year without problems until I've upgraded my macOS and appium version. However, I'll try to replace them when I go to the office. Meantime I'll keep trying to solve the problem. Thanks!

**Comment by alvarolgn** [comment] 2022-02-02 12:43
May my problem has some relation with issue https://github.com/appium/appium/issues/16367 ?

**Comment by mykola-mokhnach** [comment] 2022-02-02 15:59
No that issue is unrelated

**Comment by alvarolgn** [comment] 2022-02-03 14:16
Hello again 👋 
I'm in the office now and I've verified that this issue is not related with iOS devices. I've connected those iPhone where I'm having the issue to my mac (BigSur 11.4, appium 1.22.2) and I can execute without problems so the issue seems to be related to macOS Monterey 12.1 or to appium2... Any debug idea?

**Comment by KazuCocoa** [comment] 2022-02-03 18:47
What's the log of appium2? It prints what xcuitest driver version is used.
Generally the backend of xcuitest driver has no differences between appium 1 and 2. So I assume it could be an issue in macOS 12.1.... or the Xcode version also could be related.

**Comment by alvarolgn** [comment] 2022-02-03 20:34
@KazuCocoa this is the appium log: [no_cached_connections](https://gist.github.com/alvarolgn/76c9843bc86903bf3c599a0d69186569)

I've made some upgrades and still having the same issue... Upgrades:

* xcuitest@3.62.0 (automationName 'XCUITest')
* macOS 12.2 (21D49)

**Comment by KazuCocoa** [comment] 2022-02-04 09:26
Thanks. The XCUITest version should be almost the same as appium 1.22.2's one.

In a node console, what about getting the connected drive version?

```
> i = require('appium-ios-device')
{
  Usbmux: [Getter],
  default: [class Usbmux extends BaseServiceSocket],
  utilities: {
    getConnectedDevices: [AsyncFunction: getConnectedDevices],
    getOSVersion: [AsyncFunction: getOSVersion],
    getDeviceName: [AsyncFunction: getDeviceName],
    getDeviceTime: [AsyncFunction: getDeviceTime],
    startLockdownSession: [AsyncFunction: startLockdownSession],
    connectPort: [AsyncFunction: connectPort],
    connectPortSSL: [AsyncFunction: connectPortSSL]
  },
  services: {
    startSyslogService: [AsyncFunction: startSyslogService],
    startWebInspectorService: [AsyncFunction: startWebInspectorService],
    startInstallationProxyService: [AsyncFunction: startInstallationProxyService],
    startSimulateLocationService: [AsyncFunction: startSimulateLocationService],
    startAfcService: [AsyncFunction: startAfcService],
    startNotificationProxyService: [AsyncFunction: startNotificationProxyService],
    startHouseArrestService: [AsyncFunction: startHouseArrestService]
  }
}
> v =  i.utilities.getOSVersion('242bfcc998fd156df0bd0ad1dde8ab8e0a032114')
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 557,
  [Symbol(trigger_async_id_symbol)]: 5,
  [Symbol(destroyed)]: { destroyed: false }
}
> v
Promise {
  '15.2',
  [Symbol(async_id_symbol)]: 557,
  [Symbol(trigger_async_id_symbol)]: 5,
  [Symbol(destroyed)]: { destroyed: false }
}
```

The method calls https://github.com/appium/appium-ios-device/blob/b47d5b394f884b597281ebabd48144e6fc17d23f/lib/utilities.js#L47, then https://github.com/appium/appium-ios-device/blob/b47d5b394f884b597281ebabd48144e6fc17d23f/lib/usbmux/index.js#L240 , https://github.com/appium/appium-ios-device/blob/b47d5b394f884b597281ebabd48144e6fc17d23f/lib/usbmux/index.js#L252 . It reaches the error message's log.

**Comment by KazuCocoa** [comment] 2022-02-04 09:31
My env is upgraded one from on OS 12. Potentially clean installed 12.1+ env has an issue...? (I don't have such environment though..)

**Comment by alvarolgn** [comment] 2022-02-09 07:34
Hi @KazuCocoa ,

Thanks for your response.

I've been trying to get the connected drive version with the following results:

First of all I've obtained the following error

```
> i = require('appium-ios-device')
Uncaught Error: Cannot find module 'appium-ios-device'
Require stack:
- <repl>
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '<repl>' ]
}
```

After that, I've installed it via npm (npm install appium-ios-device), and it started working:

``` 
>  i = require('appium-ios-device')
{
  Usbmux: [Getter],
  default: [class Usbmux extends BaseServiceSocket],
  services: {
    startAfcService: [AsyncFunction: startAfcService],
    startCrashLogService: [AsyncFunction: startCrashLogService],
    startHouseArrestService: [AsyncFunction: startHouseArrestService],
    startInstallationProxyService: [AsyncFunction: startInstallationProxyService],
    startNotificationProxyService: [AsyncFunction: startNotificationProxyService],
    startSimulateLocationService: [AsyncFunction: startSimulateLocationService],
    startSyslogService: [AsyncFunction: startSyslogService],
    startWebInspectorService: [AsyncFunction: startWebInspectorService]
  },
  utilities: {
    connectPort: [AsyncFunction: connectPort],
    connectPortSSL: [AsyncFunction: connectPortSSL],
    getConnectedDevices: [AsyncFunction: getConnectedDevices],
    getDeviceInfo: [AsyncFunction: getDeviceInfo],
    getDeviceName: [AsyncFunction: getDeviceName],
    getDeviceTime: [AsyncFunction: getDeviceTime],
    getOSVersion: [AsyncFunction: getOSVersion],
    startLockdownSession: [AsyncFunction: startLockdownSession]
  }
}
``` 

But the following instruction does not work:

```
 v =  i.utilities.getOSVersion('242bfcc998fd156df0bd0ad1dde8ab8e0a032114')

Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 79,
  [Symbol(trigger_async_id_symbol)]: 5,
  [Symbol(destroyed)]: { destroyed: false }
}
> Uncaught:
Error: Could not find the expected device '242bfcc998fd156df0bd0ad1dde8ab8e0a032114'
    at Object.getOSVersion (/Users/XXXX/node_modules/appium-ios-device/lib/utilities.js:51:22)
    at Usbmux.connectLockdown (/Users/XXXX/node_modules/appium-ios-device/lib/usbmux/index.js:238:13)
``` 

I don't know if another device ID is necessary here or what... Could you help me here please?

**Comment by KazuCocoa** [comment] 2022-02-09 07:38
Thanks for the trial.
Yes, `242bfcc998fd156df0bd0ad1dde8ab8e0a032114` is mine. You should specify your connected device's one.

**Comment by alvarolgn** [comment] 2022-02-09 07:39
Yes, I had tried with my id but I was obtaining the following error:

```
> v =  i.utilities.getOSVersion('00008020-001D682201D0003A’)
v =  i.utilities.getOSVersion('00008020-001D682201D0003A’)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Uncaught SyntaxError: Invalid or unexpected token
```

**Comment by KazuCocoa** [comment] 2022-02-09 07:53
Thanks. hm, it seems working that could cause the reported error.
What about skipping `relaxed-caps` plugin?

**Comment by alvarolgn** [comment] 2022-02-09 08:05
Thanks @KazuCocoa ,

I've uninstalled the `relaxed-caps` plugin and I've obtained the same error. I've attached the error log [here](https://gist.github.com/alvarolgn/2cd812c4a39144181569535f74309bdd)

**Comment by KazuCocoa** [comment] 2022-02-09 10:13
Mm, what about adding capabilities with `appium:showXcodeLog`? Then, could you remove `"appium:app"` to make it simple? Non-bundle id and non-app start a session with the home app.
One more thing, What client did you use?

I quickly tested with `Appium v2.0.0-beta.25 creating new XCUITestDriver (v4.3.0) session` env on my local. It worked, so need more information...

**Comment by alvarolgn** [comment] 2022-02-16 07:57
Hi @KazuCocoa !

I've been doing some trying this days with no positive results and I've found some suspicious logs... Does the following los tell you anything?

```
Uncaptured runtime issue reported: Automation type mismatch: computed Other from legacy attributes vs ScrollView from modern attribute.
Enqueue Failure: Application 'com.XXXX.XXXX’ does not have a process ID /Users/qacdo/.appium/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 44 1
User has disabled system data installation.
BaseMovistar: Received attributes request for element: App element pid: 45007. Attributes: (
    "XC_kAXXCAttributeElementType",
    "XC_kAXXCAttributeElementBaseType",
    "XC_kAXXCAttributeTraits",
    "XC_kAXXCAttributeAutomationType"
)
Waiting up to 2s until com.XXXX.XXXX is in idle state (including animations)
```

About what you told me:

- Appium is not printing any XCode log when using appium:showXcodeLog
- Same result with Non-bundle id and non-app start
- I don't understand which client you mean

**Comment by KazuCocoa** [comment] 2022-02-16 08:47
okay, it simply shows the appium's new session step did not reach xcodebuild stuff.

> I don't understand which client you mean

I meant your client code. So such as Ruby client etc.

Now, I wonder the error occurred around https://github.com/appium/appium-xcuitest-driver/blob/f2a432bed23f505ef9151301f972c7eec2da3a74/lib/real-device-management.js#L57-L65.

What about the below's `app` result as you did https://github.com/appium/appium/issues/16399#issuecomment-1033437167 ?

```
(async () => {
  s = await i.services.startInstallationProxyService('00008020-001D682201D0003A');
  app = await s.lookupApplications({bundleIds: 'com.apple.Maps'})
})();
```

The above `com.apple.Maps` is an example. If it worked, could you try out with `com.XXXXXXXX`?

**Comment by alvarolgn** [comment] 2022-02-17 07:58
Hello @KazuCocoa ,

First of all thanks again by your attention 😃 

My client code is Python and what you told me to do seems that is returning the same error:

```
v =  i.utilities.getOSVersion('00008020-001D682201D0003A')
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 91,
  [Symbol(trigger_async_id_symbol)]: 5,
  [Symbol(destroyed)]: { destroyed: false }
}
>   (async () => {
...   s = await i.services.startInstallationProxyService('00008020-001D682201D0003A');
...   app = await s.lookupApplications({bundleIds: 'com.apple.Maps'})
... })();
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 188,
  [Symbol(trigger_async_id_symbol)]: 5,
  [Symbol(destroyed)]: { destroyed: false }
}
> Uncaught Error: Failed to receive any data within the timeout: 5000
    at Timeout._onTimeout (/Users/qacdo/node_modules/appium-ios-device/lib/plist-service/index.js:67:16)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:510:7)
```
(Same error with my application)

**Comment by KazuCocoa** [comment] 2022-02-17 08:41
https://github.com/appium/appium-ios-device/tree/relax-timeout-lookup

1. git clone the repo
2. `cd appium-ios-device`
3. `git checkout relax-timeout-lookup`
4. `npm install`
5. `node`
6. below node cmd:
    ```
    i = require('./build/index')
    (async () => {
      s = await i.services.startInstallationProxyService('00008020-001D682201D0003A');
      app = await s.lookupApplications({bundleIds: 'com.apple.Maps'})
    })();
    ```

I've increased the timeout. Currently, I wonder your device has many apps etc, so the command needed to take a longer time...


At the time, could you open `Console.app` and watch the device's logs by starting capturing the device log?

<img width="114" alt="Screen Shot 2022-02-17 at 0 39 11" src="https://user-images.githubusercontent.com/5511591/154437537-583002fe-1bde-41e5-a936-007125624c10.png">

Then, you can find like he below `mobile_installation_proxy` string. It is the command that the above node command sends. 
Could you capture the log, especially before getting your error?

<img width="1259" alt="Screen Shot 2022-02-17 at 0 26 41" src="https://user-images.githubusercontent.com/5511591/154437382-124e6d76-dc2d-4dbf-993a-51a4cc48d2f5.png">

The log in the console app could be huge, but potentially it has more info.

**Comment by alvarolgn** [comment] 2022-02-22 15:24
Hi @KazuCocoa ,

I couldn't find any log related to mobile_installation_proxy after several tries with all my devices repeating the process from the beginning...

It finishes in the timeout error but there is not any log below the string mobile_installation_proxy:

```
> (async () => {
...   s = await i.services.startInstallationProxyService('00008020-001D682201D0003A');
...   app = await s.lookupApplications({bundleIds: 'com.XXXXXXX'})
... })();
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 460,
  [Symbol(trigger_async_id_symbol)]: 5,
  [Symbol(destroyed)]: { destroyed: false }
}
> Uncaught Error: Failed to receive any data within the timeout: 5000
    at Timeout._onTimeout (/Users/qacdo/Workspace/niji4home/appium-ios-device/lib/plist-service/index.js:67:16)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:510:7)
```

It seems that is not reaching that point in the flow... Isn't it?

Thanks,
Álvaro.

**Comment by KazuCocoa** [comment] 2022-02-28 02:06
mm... interesting...
Yea, it seems the command did not reach the device via usbmux...

**Comment by alvarolgn** [comment] 2022-03-01 08:07
Hi @KazuCocoa  😄 

 I've reinstalled all libimobiledevice, usbmux (deprecated), ios-deploy, authorize-ios and ideviceinstaller but still having the same issue.

Might it be a physical issue or any issue in usbmux?

Thanks!

**Comment by KazuCocoa** [comment] 2022-03-01 08:59
So far, I guess it is iOS side stuff. Appium succeeded to send commands over `usbmux`, but no response in some cases.

For example, `getOSVersion` worked in your env as well. It means appium <--> iOS communication path worked. But some commands such as `lookupApplications` had no response by iOS.

If you'd try something, maybe reboot the device may help. (re-install tools such as libimobiledevice does not help)

**Comment by KazuCocoa** [comment] 2022-03-05 17:20
The root cause is not so clear (since as appium/appium-ios-device succeeded to send a command, but no response by probably iOS while it is a blackbox), so what I can suggest is:

1. Find another device or host machine
2. Avoid using `lookupApplications` (since so far, the method did not get a proper response)
    1. Start a session without `app` and `bundleId`
    2. Install the app under test with https://github.com/appium/appium-xcuitest-driver#mobile-installapp or http://appium.io/docs/en/commands/device/app/install-app/
    3. Activate the app https://appium.io/docs/en/commands/device/app/activate-app/

The 2) may work if the only method that cannot get the response is `lookupApplications` related, but not sure only it is.

**Comment by alvarolgn** [comment] 2022-03-10 16:25
@KazuCocoa I've followed your steps but the point where the error 500 is returned now is when the installApp (driver.install_app) command is launched. Additionally, it is failing for is_app_installed method. I don't know if it gives you some information.... I'll keep my investigations tomorrow from this point.

Thanks!

**Comment by mykola-mokhnach** [comment] 2022-03-10 16:40
Perhaps https://github.com/appium/appium-ios-device/pull/88 could help after it's merged

**Comment by KazuCocoa** [comment] 2022-03-10 18:04
Then, what about using https://github.com/YueChen-C/py-ios-device (or similar ones) to install the app?

**Comment by KazuCocoa** [comment] 2022-03-12 09:48
Interesting... Actually https://github.com/appium/appium-ios-device/pull/88 may help, but I wonder what kind of factors are related to this behavior.

In my local test, below combinations had no like this issue.

- iPhone SE (15.4), SE 2 (15.3.1) and iPad mini (15.4)
- macOS 12.2.1 (intel mac 2016 and M1 mac 2020).
- Xcode 13.0 and 13.3

I don't have 14 for now, so haven't tested with it.

---

According to https://github.com/appium/appium/issues/16399#issuecomment-1029034055 and https://github.com/appium/appium/issues/16399#issuecomment-1029377506, macOS 12.1 and 12.2 may affect this issue but 11.4 has no issue.

**Comment by KazuCocoa** [comment] 2022-03-12 10:01
I wonder if the https://github.com/appium/appium-ios-device/pull/88 solves this real device issue, we need to create a patch release with a patch appium-ios-device version as 1.22.3 as a prior issue fix for ios 15/xcode 13 or some version matter before appium 2 stable release.

**Comment by KazuCocoa** [comment] 2022-03-12 16:13
@alvarolgn What version of openssl env did you use?
You can check it as below:
```
 % node
Welcome to Node.js v14.19.0.
Type ".help" for more information.
> process.versions
{
  node: '14.19.0',
  v8: '8.4.371.23-node.85',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.4',
  openssl: '1.1.1m',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0'
}
```

For now, the root cause is potentially by openssl v3 thing. Then, you could try out openssl 1.1.1.
https://github.com/appium/appium-ios-device/pull/88#discussion_r825315862

**Comment by douniwan5788** [comment] 2022-03-13 08:50
#16528 #16367 #16056 #15187 may be caused by the same reason and can be fixed by appium-ios-device@2.3.1 or downgrading node.js to v16(which using openssl 1.1.1).

**Comment by mykola-mokhnach** [comment] 2022-03-14 11:14
Closed as fixed. Thanks @douniwan5788

**Closed by mykola-mokhnach** 2022-03-14 11:14 UTC
Labels: iOS

**Comment by alvarolgn** [comment] 2022-04-01 08:46
I've upgrade my node and openssl versions to:

```
eve:.appium qacdo$ node
Welcome to Node.js v17.8.0.
Type ".help" for more information.
> process.versions
{
  node: '17.8.0',
  v8: '9.6.180.15-node.16',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '102',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '3.0.2+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```
and it is working now 😄 😄 

Thanks @mykola-mokhnach @douniwan5788  @KazuCocoa you are my heroes 💪

**Comment by parveenabaqus** [comment] 2023-04-26 07:23
> I downgrade the node version to 16.15.1 and it's working fine for me

It works. Thanks

**Comment by reemadaga** [comment] 2024-01-20 00:04
Test runs fine locally in simulator but fails in the real device with the following error:
"equest failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000"
Using the following
Appium - 1.22.2
NodeJS - 18
Webdriverio 8

**Comment by reemadaga** [comment] 2024-01-20 00:11
{
  node: '18.18.0',
  acorn: '8.10.0',
  ada: '2.6.0',
  ares: '1.19.1',
  brotli: '1.0.9',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '6.0.11',
  modules: '108',
  napi: '9',
  nghttp2: '1.55.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.10+quic',
  simdutf: '3.2.14',
  tz: '2023c',
  undici: '5.22.1',
  unicode: '15.0',
  uv: '1.46.0',
  uvwasi: '0.0.18',
  v8: '10.2.154.26-node.26',
  zlib: '1.2.13.1-motley'
}

**Comment by KazuCocoa** [comment] 2024-01-20 00:17
Simulators and real devices have different running environments; the former uses the host machine's tech stack. So they could have different behavior. I don't know the details without appium log, but I guess `webkitResponseTimeout` related from the value. You can increase the capability, or the root cause was Safari/WebInspector. Or try out with the latest Appium/XCUITest driver version.

**Comment by reemadaga** [comment] 2024-01-20 00:24
024-01-20T00:03:48.764Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000
[0-0] 2024-01-20T00:03:48.764Z ERROR webdriver: unknown error: An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000
[0-0]     at getErrorFromResponseBody (xxx/node_modules/webdriver/build/utils.js:195:12)
[0-0]     at NodeJSRequest._request (xxx/node_modules/webdriver/build/request/index.js:193:23)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async startWebDriverSession (xxx/node_modules/webdriver/build/utils.js:64:20)
[0-0]     at async WebDriver.newSession (xxx/node_modules/webdriver/build/index.js:19:45)
[0-0]     at async remote (xxx/node_modules/webdriverio/build/index.js:45:22)
[0-0]     at async Runner._startSession (xxx/node_modules/@wdio/runner/build/index.js:224:29)
[0-0]     at async Runner._initSession (xxx/node_modules/@wdio/runner/build/index.js:190:25)
[0-0]     at async Runner.run (xxx/node_modules/@wdio/runner/build/index.js:79:19)
[0-0] 2024-01-20T00:03:48.765Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000
[0-0]     at startWebDriverSession (xxx/node_modules/webdriver/build/utils.js:69:15)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async WebDriver.newSession (xxx/node_modules/webdriver/build/index.js:19:45)
[0-0]     at async remote (xxx/node_modules/webdriverio/build/index.js:45:22)
[0-0]     at async Runner._startSession (xxx/node_modules/@wdio/runner/build/index.js:224:29)
[0-0]     at async Runner._initSession (xxx/node_modules/@wdio/runner/build/index.js:190:25)
[0-0]     at async Runner.run (xxx/node_modules/@wdio/runner/build/index.js:79:19)

**Comment by reemadaga** [comment] 2024-01-20 02:10
@KazuCocoa Looks like a problem with NodeJS 18. Any idea?

**Comment by KazuCocoa** [comment] 2024-01-20 02:12
Could you create a new issue with proper logs in the issue template? The attached log was on the client side, not the Appium server, so there is no new information. I think it was real device/Safari/Webinspector specific issue (which might not be accessible by Appium)

**Comment by kimberlymccubbinalva** [comment] 2024-04-23 01:54
Hi there! does anyone have any update on this matter? I'm facing the same timeout problem as described in your previous comments when trying to start the iOS Inspector Tool provided by Katalon Studio with a mobile app.

- "Original error: Failed to receive any data within the timeout: 5000"

OS: Apple M2 Pro - Sonoma 14.4.1
Ccode: 15.2
Katalon: 9.0.0
Node: 21.7.1
Appium: 2.5.1

I'll appreciate any feedback. Thanks!

**Comment by Balakumar-14** [comment] 2024-05-08 09:40
I too faced this same issue.

My error log is :
```
[debug] [W3C] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{}],"alwaysMatch":{"appium:automationName":"xcuitest","appium:bundleId":"com.zoho.inhouse.oneauth","appium:commandTimeouts":"240000","appium:derivedDataPath":"/Users/bala-14246/Library/Developer/Xcode/DerivedData/WebDriverAgent-cphlemmxwkpuwxdhuksjmxonhqga","appium:deviceName":"iPhone","appium:mjpegServerPort":9118,"appium:newCommandTimeout":5000,"appium:noReset":true,"appium:platformVersion":"16.2","appium:shouldTerminateApp":true,"appium:showXcodeLog":true,"appium:udid":"00008030-00114D2A0CF0802E","appium:usePrebuiltWDA":true,"appium:wdaLocalPort":8119,"platformName":"IOS"}}]
2024-05-07 13:25:02:750 - [debug] [BaseDriver] Event 'newSessionRequested' logged at 1715068502750 (13:25:02 GMT+0530 (India Standard Time))
2024-05-07 13:25:02:991 - [Appium] Appium v1.22.3 creating new XCUITestDriver (v3.59.0) session
2024-05-07 13:25:02:992 - [Appium] Applying relaxed security to 'XCUITestDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
2024-05-07 13:25:02:993 - [debug] [BaseDriver] Creating session with W3C capabilities: {
2024-05-07 13:25:02:993 - [debug] [BaseDriver]   "alwaysMatch": {
2024-05-07 13:25:02:993 - [debug] [BaseDriver]     "platformName": "IOS",
2024-05-07 13:25:02:993 - [debug] [BaseDriver]     "appium:automationName": "xcuitest",
2024-05-07 13:25:02:993 - [debug] [BaseDriver]     "appium:bundleId": "com.zoho.inhouse.oneauth",
2024-05-07 13:25:02:993 - [debug] [BaseDriver]     "appium:commandTimeouts": "240000",
2024-05-07 13:25:02:993 - [debug] [BaseDriver]     "appium:derivedDataPath": "/Users/bala-14246/Library/Developer/Xcode/DerivedData/WebDriverAgent-cphlemmxwkpuwxdhuksjmxonhqga",
2024-05-07 13:25:02:993 - [debug] [BaseDriver]     "appium:deviceName": "iPhone",
2024-05-07 13:25:02:993 - [debug] [BaseDriver]     "appium:mjpegServerPort": 9118,
2024-05-07 13:25:02:993 - [debug] [BaseDriver]     "appium:newCommandTimeout": 5000,
2024-05-07 13:25:02:993 - [debug] [BaseDriver]     "appium:noReset": true,
2024-05-07 13:25:02:993 - [debug] [BaseDriver]     "appium:platformVersion": "16.2",
2024-05-07 13:25:02:993 - [debug] [BaseDriver]     "appium:shouldTerminateApp": true,
2024-05-07 13:25:02:993 - [debug] [BaseDriver]     "appium:showXcodeLog": true,
2024-05-07 13:25:02:993 - [debug] [BaseDriver]     "appium:udid": "00008030-00114D2A0CF0802E",
2024-05-07 13:25:02:993 - [debug] [BaseDriver]     "appium:usePrebuiltWDA": true,
2024-05-07 13:25:02:993 - [debug] [BaseDriver]     "appium:wdaLocalPort": 8119
2024-05-07 13:25:02:993 - [debug] [BaseDriver]   },
2024-05-07 13:25:02:993 - [debug] [BaseDriver]   "firstMatch": [
2024-05-07 13:25:02:993 - [debug] [BaseDriver]     {}
2024-05-07 13:25:02:993 - [debug] [BaseDriver]   ]
2024-05-07 13:25:02:993 - [debug] [BaseDriver] }
2024-05-07 13:25:02:996 - [BaseDriver] Session created with session id: 0c322d06-1320-44f3-8faf-d002f580e5a6
2024-05-07 13:25:03:021 - [debug] [XCUITest] Current user: 'bala-14246'
2024-05-07 13:25:03:032 - [debug] [XCUITest] Available devices: 00008030-00114D2A0CF0802E
2024-05-07 13:25:03:032 - [debug] [XCUITest] Creating iDevice object with udid '00008030-00114D2A0CF0802E'
2024-05-07 13:25:03:032 - [XCUITest] Determining device to run tests on: udid: '00008030-00114D2A0CF0802E', real device: true
2024-05-07 13:25:03:063 - [debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1715068503063 (13:25:03 GMT+0530 (India Standard Time))
2024-05-07 13:25:03:063 - [debug] [BaseDriver] Event 'appConfigured' logged at 1715068503063 (13:25:03 GMT+0530 (India Standard Time))
2024-05-07 13:25:03:063 - [debug] [BaseDriver] Event 'resetStarted' logged at 1715068503063 (13:25:03 GMT+0530 (India Standard Time))
2024-05-07 13:25:03:063 - [debug] [XCUITest] Reset: fullReset not set. Leaving as is
2024-05-07 13:25:03:063 - [debug] [BaseDriver] Event 'resetComplete' logged at 1715068503063 (13:25:03 GMT+0530 (India Standard Time))
2024-05-07 13:25:03:063 - [WebDriverAgent] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
2024-05-07 13:25:03:063 - [WebDriverAgent] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
2024-05-07 13:25:08:138 - [XCUITest] Continuing without capturing device logs: Failed to receive any data within the timeout: 5000
2024-05-07 13:25:08:139 - [XCUITest] Setting up real device
2024-05-07 13:25:13:207 - [XCUITest] {}
2024-05-07 13:25:13:209 - [DevCon Factory] Releasing connections for 00008030-00114D2A0CF0802E device on any port number
2024-05-07 13:25:13:210 - [DevCon Factory] No cached connections have been found
2024-05-07 13:25:13:211 - [debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
2024-05-07 13:25:13:212 - [debug] [BaseDriver] Event 'newSessionStarted' logged at 1715068513212 (13:25:13 GMT+0530 (India Standard Time))
2024-05-07 13:25:13:216 - [debug] [W3C] Encountered internal error running command: Error: Failed to receive any data within the timeout: 5000
2024-05-07 13:25:13:216 - [debug] [W3C]     at Timeout._onTimeout (/usr/local/lib/node_modules/appium/node_modules/appium-ios-device/lib/plist-service/index.js:67:16)
2024-05-07 13:25:13:216 - [debug] [W3C]     at listOnTimeout (node:internal/timers:573:17)
2024-05-07 13:25:13:216 - [debug] [W3C]     at processTimers (node:internal/timers:514:7)
2024-05-07 13:25:13:237 - [HTTP] <-- POST /wd/hub/session 500 10487 ms - 599
2024-05-07 13:25:13:237 - [HTTP] 
2024-05-07 13:25:13 DEBUG brotli4j not in the classpath; Brotli support will be unavailable.
2024-05-07 13:25:13 ERROR Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000 
Host info: host: 'bala-14246', ip: 'fe80:0:0:0:1c18:9d33:be64:8d6e%en0'
```

I encountered a similar issue, and upon inspecting the error log, it appears that there might be an issue with the WebDriverAgent (WDA) path. To troubleshoot this, I suggest checking the WDA path mentioned in the error log and ensuring it points to the correct WebDriverAgent.

To verify if there's an issue with the WDA path, you can run and test the default unit tests in the specified WebDriverAgent directory. If the tests fail or if there are any discrepancies in the path, it might indicate a misconfiguration or incorrect setup.

In my case, I had multiple installations of Appium on my Mac, and it seems there were issues with the provisioning profiles for WebDriverAgent mentioned in the log file. I resolved this by correcting the WDA paths to match the installation location of the second Appium instance.

By ensuring the correct WDA path and resolving any provisioning profile issues, you should be able to address this error and successfully start a new session.

Let me know if you need further assistance or if there's anything else I can help with!

**Comment by OshithaIdeaBits** [comment] 2024-10-16 09:30
use 
appium 2.12.0
appium-webdriveragent", "version": "8.9.3",

**Comment by dmytro-bondarenko** [comment] 2025-03-20 13:48
any updates on this? facing the same issue 

and why is that issue closed without any fix?
