### ISSUE TITLE
Appium cannot type value into html input controlled by React >= 15.6.0

### ISSUE THREAD

**Issue by ikhilko** [appium/appium#9002] opened 2017-08-09 11:18 UTC
## The problem

Appium cannot type value into html input controlled by React (webview in hybrid app). The problem appears after React 15.6.0 release, when was changed implementation of controlled inputs.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.6.6-beta.3**
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: **Mac**
* Node.js version (unless using Appium.app|exe): **v8.2.1**
* Mobile platform/version under test: **IOS 10.3.1**
* Real device or emulator/simulator: **Real device**
* Appium CLI or Appium.app|exe: **CLI**

## Details

The issue is not about appium itself, it relates [appium-remote-debugger](https://github.com/appium/appium-remote-debugger). The problem is about how appium (and selenium itself) programmatically type value into inputs. The same issue was fixed in https://github.com/cypress-io/cypress/issues/536. React wount fix it https://github.com/facebook/react/issues/10347. Possible workaround https://github.com/cypress-io/cypress/issues/536#issuecomment-308739206.

Thanks in advance.

**Comment by dpgraham** [comment] 2017-08-09 17:14
Thanks for reporting this @ikhilko 

What happens when you try inputting values? Does it get automatically cleared or does it throw an exception?

**Comment by ikhilko** [comment] 2017-08-10 07:10
@dpgraham appium itself worked without exceptions. Value is presented in input and in attribute "value" but React's onChange handler doesn't fired. 
So as I can understand appium setted "value" attribute and then fired onchange event with that value. But at that case React will prevent onChange to be called, because attribute "value" and value in event are the same. So the problem was introduced in latest versions of React, but it should work that way because when you typing value from keyboard it will fire onchange event but not set programatically value to "value" attributes.

**Comment by amedvedjev** [comment] 2017-08-10 08:46
@ikhilko just wonder how about Paste event. It should trigger also onChange...

**Comment by ikhilko** [comment] 2017-08-10 12:58
@amedvedjev all events from user-side will work right. Doesn't work automation because the way of typing value used in automation (appium|selenium) differs from native behaviour of browser.

**Comment by dpgraham** [comment] 2017-08-10 17:40
I don't know if we can fix this on the Appium/Selenium side, unless we applied a React-specific workaround.

Do you know if there's a way to force the onChange event, like using a JS execution script on the element?

**Comment by ikhilko** [comment] 2017-08-11 06:48
@dpgraham possible workaround https://github.com/cypress-io/cypress/issues/536#issuecomment-308739206 , but looks like it will not work in future React 16 and up versions..

**Comment by dilankadon** [comment] 2017-08-17 06:36
@dpgraham, 
Q. What happens when you try inputting values? Does it get automatically cleared or does it throw an exception?

A. The value gets cleared automatically.
using 1.6.6.beta.4

**Comment by ikhilko** [comment] 2017-09-05 10:16
@dpgraham Is it any possibilities to fix it?

**Comment by dpgraham** [comment] 2017-09-05 18:27
I'm not sure if it's something that we'll a fix for on the Appium side in the near future, unless somebody wants to submit a PR.

By the sounds of this, it's not just an Appium issue but also a Selenium issue. My advice would be to open a ticket with the React team and find out if there's a way to programmatically force an `onChange` event.

**Comment by amedvedjev** [comment] 2017-09-05 18:54
just in case - https://facebook.github.io/react/docs/test-utils.html#simulate

**Comment by jlipps** [comment] 2017-09-07 23:08
using `Simulate` seems like a good idea, and could probably be triggered by `executeScript`

**Comment by ikhilko** [comment] 2017-09-18 11:36
@jdeff So, your suggestion is to bundle React test-utils into production build to be able to execute Simulate function at DOM element? Sounds really not working for us..

**Comment by dpgraham** [comment] 2017-09-18 22:29
@ikhilko Couldn't you have just have a dev build that bundles react-test-utils?

**Comment by ikhilko** [comment] 2017-10-12 12:02
@dpgraham sorry, we are testing prod app. Not a great solution for us

**Comment by dhartleycs** [comment] 2017-11-14 10:17
An ugly and slow workaround for iOS Safari execution - change your iOSDriver context to native, tap on the field and then press the "Close" button. This seems to trigger the event.

**Comment by gvozdeva-ira** [comment] 2018-01-29 15:00
@ikhilko try this solution https://github.com/vitalyq/react-trigger-change , it works for me

**Comment by iwiiiwi** [comment] 2018-01-30 07:26
@gvozdeva-ira Thanks, it also works for me.

**Comment by serhatbolsu** [comment] 2018-03-14 18:56
This is still an issue if you are testing an react mobile web page. Is anyone has a solution ? 
- Android is ok, 
- Selenium is ok, from web view
- iOS Safari, is writing the field but not triggering action change

**Comment by LolaYan** [comment] 2018-07-03 03:15
This is still an issue. Is anyone has a solution ?

**Comment by simonh26** [comment] 2018-07-30 20:57
Are there any solutions for this?

**Comment by tmonautoguy** [comment] 2018-08-01 18:34
Definitely still an issue.

**Comment by simonh26** [comment] 2018-08-01 18:37
unfortunately a blocking issue for us.

**Comment by tmonautoguy** [comment] 2018-08-01 18:40
@simonh26 did you try out @dhartleycs work around? Im trying it out now.

**Comment by simonh26** [comment] 2018-08-01 18:55
@dhartleycs <https://github.com/dhartleycs> I did not please let me know
how you get on..

**Comment by gvozdeva-ira** [comment] 2018-08-02 05:42
This work around which work for me and fix the issue: 
webFile = requests.get('https://unpkg.com/react-trigger-change/dist/react-trigger-change.js')
self.driver.execute_script(webFile.text)
self.driver.find_element(*self._search_input_locator).send_keys('some text')
search_input = self.driver.find_element(*self._search_input_locator)
self.driver.execute_script("reactTriggerChange(arguments[0]);", search_input)

**Comment by silicakes** [comment] 2018-08-02 17:40
@gvozdeva-ira - I've tried the same thing, however it removes the value I've set for the input.

Here's a quick workaround for those with webdriverio/appium/browserstack/jasmine:
(assuming reactTriggerChange is injected by the app);
```
  browser.execute(() => {
      let el = document.querySelector('#mainSearchInput');
      // forcing value to always return our custom string
      Object.defineProperty(el,"value", {
        get: () => 'My search term'
      })
      reactTriggerChange(el);
      return true;
    });
```

**Comment by CoryKniefel** [comment] 2018-08-06 20:10
@gvozdeva-ira thank you, worked for me

**Comment by dheeraj1988** [comment] 2018-08-30 06:31
I had a similar issue. When i try using sendKeys() on username field, it works fine. But as soon as I click on password field to use sendKeys() again, it clears the value in username field. Then I tried doing the same thing with JavascriptExecutor and I was able to enter values in both fields but clicking on login button after that clears the value. 

Problem was react context is not firing onChange() event as we interact with the DOM using javascript. So, I had to manually do that. After so much of hassle, I found a good easy solution.

Setter .value= is not working as we wanted because React library overrides input value setter but we can call the function directly on the input as context.

`var nativeInputValueSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, "value").set;
var event = new Event('input', { bubbles: true});

nativeInputValueSetter.call(document.getElementById("username-field-id").dispatchEvent(ev);, 'username-input');
document.getElementById("username-field-id").dispatchEvent(event);`

For textarea element you should use prototype of HTMLTextAreaElement class.

**Comment by mykola-mokhnach** [comment] 2018-10-03 08:36
Linking some theory on this topic https://appiumpro.com/editions/36

**Comment by nshoes** [comment] 2019-03-12 20:08
Ran into this today as well while setting up Appium with our React app inside iOS. Input value visually changes but components state does not. I did not hit this issue on Android. Appium 1.11.1.

**Comment by vutukuriswathi** [comment] 2019-03-27 02:21
I also ran in in to the similar issue when i am testing hybrid app webviews on iOS using appium 1.10.0.I tried the below options in my java code but no use.
JavascriptExecutor jsExecutor = (JavascriptExecutor) MobileHelper.getIosDriver();
        jsExecutor.executeScript("$(arguments[0]).change();", toPort());

Can some one please help me how to resolve using appium on iOS?

Appreicated your help.

**Comment by PMudra** [comment] 2019-04-02 14:48
I was looking for a workaround for this issue today. For me a combination of different solutions worked.

#### Custom command:

```js
function setNativeValue(element, value) {
  const { set: valueSetter } = Object.getOwnPropertyDescriptor(element, 'value') || {};
  const prototype = Object.getPrototypeOf(element);
  const { set: prototypeValueSetter } = Object.getOwnPropertyDescriptor(prototype, 'value') || {};

  if (prototypeValueSetter && valueSetter !== prototypeValueSetter) {
    prototypeValueSetter.call(element, value);
  } else if (valueSetter) {
    valueSetter.call(element, value);
  } else {
    throw new Error('The given element does not have a value setter');
  }
  element.dispatchEvent(new Event('input', { bubbles: true }));
}

function customCommand(value) {
  if (driver.isIOS) {
    browser.execute(setNativeValue, this, value);
  } else {
    this.setValue(value);
  }
}

browser.addCommand('setNativeValue', customCommand, true);
```

#### Usage example:

```js
$('input[type=email]').setNativeValue('example@test.com');
```

#### References:
- https://github.com/appium/appium/issues/9002#issuecomment-438974790 by @wswebcreation 
- https://github.com/facebook/react/issues/10135#issuecomment-401496776 by @kentcdodds
- https://github.com/facebook/react/issues/10135#issuecomment-314441175 by @fatfisz

**Comment by arpitkup** [comment] 2019-04-09 01:25
Hi @gvozdeva-ira I am facing the same issue. When I convert your code into C#, I am getting error. For some reason, the "reactTriggerChange" is not getting recognised. Could you please help ? Below is my code snippet. 
            string sURL = "https://unpkg.com/react-trigger-change/dist/react-trigger-change.js";
            WebRequest wrGETURL;
            wrGETURL = WebRequest.Create(sURL);
            Stream objStream;
            objStream = wrGETURL.GetResponse().GetResponseStream();
            StreamReader reader = new StreamReader(objStream);
            string rt = reader.ReadToEnd();
            driver.ExecuteScript(rt);
            IWebElement ele2 = driver.FindElement(byLocator);
            driver.ExecuteScript("reactTriggerChange(arguments[0]);", ele2);

**Comment by ckzgraphics** [comment] 2019-06-25 13:50
[This comment](https://github.com/facebook/react/issues/11488#issuecomment-470623779) seemed to do the trick as well!

**Comment by IvanSkotar** [comment] 2020-02-01 03:10
I feel the sam e issue. After I enter a value to input field, then perform any of action as: click to anywhere (any button, input field or just to empty space), put the value to next field and so on
the entered value disappears.

Trick above are not solve an issue(

**Comment by LingeshS** [comment] 2020-02-11 01:59
> I feel the sam e issue. After I enter a value to input field, then perform any of action as: click to anywhere (any button, input field or just to empty space), put the value to next field and so on
> the entered value disappears.
> 
> Trick above are not solve an issue(
> I am working with Web app on React.js

@IvanSkotar Same issue I am also facing right now. did you get any solutions for this?

**Comment by benmacs** [comment] 2020-02-13 14:45
I don't like this solution, but it has been a consistent workaround for me whenever I need to send a value to a React input field for iOS devices. 
Depending on the version of React, this may not work.

```
	public void sendKeys_ReactJs(WebElement webElement, String valueToSend) {
		((JavascriptExecutor) driver).executeScript("let input = arguments[0];""var setValue = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set;setValue.call(input, '" + valueToSend + "');" + "var e = new Event('input', { bubbles: true });""input.dispatchEvent(e);", webElement);
	}
```

**Comment by imurchie** [comment] 2020-02-18 21:57
Can you try updating the latest Appium beta, making sure you get `appium-remote-debugger` version `8.3.0`?

**Comment by imurchie** [comment] 2020-02-18 21:57
Can you try updating the latest Appium beta, making sure you get `appium-remote-debugger` version `8.3.0`?

**Comment by CShabolotova** [comment] 2020-02-20 22:51
WebElement email = driver.findElement(By.id("username"));
        JavascriptExecutor js = (JavascriptExecutor) driver;
        // User enters email address to email box:
        js.executeScript(
                "var email = document.getElementById('username');" +
                        "var oldValue = email.value;" +
                        "email.value = 'test@gmail.com';" +
                        "var ev = new Event('input', { bubbles: true});" +
                        "ev.simulated = true;" +
                        "let tracker = email._valueTracker;" +
                        "if (tracker)" +
                        "  tracker.setValue(oldValue);" +
                        "email.dispatchEvent(ev);");

        WebElement password = driver.findElement(By.id("password"));
        // User enters password to password box:
        js.executeScript(
                "var password = document.getElementById('password');" +
                        "var oldValue = password.value;" +
                        "password.value ='test1@';" +
                        "var ev = new Event('input', { bubbles: true});" +
                        "ev.simulated = true;" +
                        "let tracker = password._valueTracker;" +
                        "if (tracker)" +
                        "  tracker.setValue(oldValue);" +
                        "password.dispatchEvent(ev);");

// Then user clicks on sign in button: this should work!

**Comment by imurchie** [comment] 2020-02-21 14:40
This should be unnecessary in the latest Appium beta.

**Comment by wswebcreation** [comment] 2020-03-15 09:42
@imurchie 

Confirmed that this works with Appium `1.17.0`, meaning this issue can be closed 🎉

**Comment by CShabolotova** [comment] 2020-03-22 21:30
@wswebcreation , I have updated appium version, issue is still there.

**Comment by imurchie** [comment] 2020-03-23 14:58
@CShabolotova Please provide the Appium server logs (as a link to a [gist](https://gist.github.com)) with the latest server.

**Comment by mykola-mokhnach** [comment] 2020-04-04 16:03
Closed as fixed

**Closed by mykola-mokhnach** 2020-04-04 16:03 UTC
Labels: NeedsInfo, ThirdParty, XCUITest

**Comment by SonaliSammy** [comment] 2021-05-29 04:12
> WebElement email = driver.findElement(By.id("username"));
> JavascriptExecutor js = (JavascriptExecutor) driver;
> // User enters email address to email box:
> js.executeScript(
> "var email = document.getElementById('username');" +
> "var oldValue = email.value;" +
> "email.value = '[test@gmail.com](mailto:test@gmail.com)';" +
> "var ev = new Event('input', { bubbles: true});" +
> "ev.simulated = true;" +
> "let tracker = email._valueTracker;" +
> "if (tracker)" +
> " tracker.setValue(oldValue);" +
> "email.dispatchEvent(ev);");
> 
> ```
>     WebElement password = driver.findElement(By.id("password"));
>     // User enters password to password box:
>     js.executeScript(
>             "var password = document.getElementById('password');" +
>                     "var oldValue = password.value;" +
>                     "password.value ='test1@';" +
>                     "var ev = new Event('input', { bubbles: true});" +
>                     "ev.simulated = true;" +
>                     "let tracker = password._valueTracker;" +
>                     "if (tracker)" +
>                     "  tracker.setValue(oldValue);" +
>                     "password.dispatchEvent(ev);");
> ```
> 
> // Then user clicks on sign in button: this should work!

this did not work

**Comment by SonaliSammy** [comment] 2021-05-29 04:17
> @imurchie
> 
> Confirmed that this works with Appium `1.17.0`, meaning this issue can be closed 🎉

No I still face the issue with Appium '1.17.0'

**Comment by li-zhixin** [comment] 2022-06-24 06:05
The same problem occurs with `appium@next`, and I observed that the fix in `appium-remote-debugger,` but `appium@next does` not seem to depend on `appium-remote-debugger`
