### ISSUE TITLE
XCUIElementTypePickerWheel makes app crash

### ISSUE THREAD

**Issue by AlexXiao2016** [appium/appium#10321] opened 2018-03-08 22:49 UTC
## The problem

I have a add credit card page, on this page, there are 3 XCUIElementTypePickerWheel elements. One is used to choose credit card type, one is used to choose expiration date, one is used to choose billing address state. the app always crashes when it tries to select one value for above fields.  

On the other add shipping address page, there is only one XCUIElementTypePickerWheel element and there is no crash issue in this page. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium:  MacOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): v9.7.1
* Mobile platform/version under test: iOS 11.2 
* Real device or emulator/simulator: iPhone 8
* Appium CLI or Appium.app|exe: Appium Desktop 1.3.1

## Details
Tested manually, there is no crash issue in add credit card page. I suspect the crash happens because of multiple XCUIElementTypePickerWheel elements in one page. 

## Link to Appium logs

https://gist.github.com/AlexXiao2016/02d5e550b5958e0815f9026c40dec373

## Code To Reproduce Issue [ Good To Have ]

``` Java
 protected void selectExpiration(int expirationMonth, int expirationYear) {
        expiration.click();
        expirationMonthPickerWheel.sendKeys(Integer.toString(monthFormatted));
        expirationYearPickerWheel.sendKeys(Integer.toString(expirationYear));
        pickerWheelDoneButton.click();
    }

public void selectState(String stateAbbreviation) {
        stateDropDown.click();
        String stateString = State.valueOfAbbreviation(stateAbbreviation).toString();
        if (isIOS()) {
            waitForElements(this, pickerWheel); 
            pickerWheel.sendKeys(stateString);
            pickerWheelDoneButton.click();
        }
}
```

**Comment by mykola-mokhnach** [comment] 2018-03-09 06:40
Duplicate of https://github.com/facebook/WebDriverAgent/issues/826

**Closed by mykola-mokhnach** 2018-03-09 06:40 UTC

**Comment by PraveenKumarQA** [comment] 2019-02-06 20:22
Hi, I may be late to the party but I was able to get around the problem using iOS - 11.4, Appium - 1.11.0-beta.3, node - v10.14.2
