### ISSUE TITLE
The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.

### ISSUE THREAD

**Issue by raulosandeep93** [appium/appium#10558] opened 2018-04-18 13:04 UTC
I'm having the below setup:
iOS version: 11.2.6 iPad Real Device
MAC version: 10.13.4
Appium version: 1.5.0 desktop version
Xcode version: 9.3
Carthage version: 0.29

I'm trying to install WebDriverAgent file using below command but getting the error 'The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.'

xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=046e4469d6cb14ff57e378599bd4b1d09390472b' test

I have almost tried all the posts on Git so please do not mark this as duplicate and please help me with this issue.

PFB, the logs.

`ICPL11611:WebDriverAgent sandeepraulo$ cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent 
ICPL11611:WebDriverAgent sandeepraulo$ xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=046e4469d6cb14ff57e378599bd4b1d09390472b' test
2018-04-18 18:31:02.178 xcodebuild[3808:68382]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/T/com.apple.dt.XCTest/IDETestRunSession-8C664E44-A785-4E56-AE87-788EA30E31B6/WebDriverAgentRunner-FC633024-6ED6-4CF0-9464-27E822506A88/Session-WebDriverAgentRunner-2018-04-18_183102-qVu7Rg.log
2018-04-18 18:31:02.179 xcodebuild[3808:68380] [MT] IDETestOperationsObserverDebug: (4F506EBD-F08F-4444-96C3-2A131D2A5D06) Beginning test session WebDriverAgentRunner-4F506EBD-F08F-4444-96C3-2A131D2A5D06 at 2018-04-18 18:31:02.179 with Xcode 9E145 on target <DVTiOSDevice: 0x7ff6b41c2650> {
		deviceSerialNumber:         DMPNWQL6G5VV
		identifier:                 046e4469d6cb14ff57e378599bd4b1d09390472b
		deviceClass:                iPad
		deviceName:                 iPad
		deviceIdentifier:           046e4469d6cb14ff57e378599bd4b1d09390472b
		productVersion:             11.2.6
		buildVersion:               15D100
		deviceSoftwareVersion:      11.2.6 (15D100)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12857221120
		deviceAvailableCapacity:    9933754368
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7ff6b3bef0c0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1,
    2
)
		applications:              (null)
		provisioningProfiles:      (null)
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		connected:                 yes
		isWirelessEnabled:         no
		connectionType:            direct
		} (11.2.6 (15D100))
=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/9aed6e76ff4bf27af89562bd422dca29/046e4469d6cb14ff57e378599bd4b1d09390472b/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/sandeepraulo/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.mrl9L1/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.mrl9L1/WebDriverAgentRunner-Runner.app_sparse.ipa
MDMDirectoryDiff_block_invoke:1473 calling writeDictToFile with: /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.mrl9L1/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.mrl9L1/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
2018-04-18 18:31:17.392924+0530 WebDriverAgentRunner-Runner[366:46778] Running tests...
2018-04-18 18:31:17.423655+0530 WebDriverAgentRunner-Runner[366:46778] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2018-04-18 18:31:17.423791+0530 WebDriverAgentRunner-Runner[366:46778] (dlopen_preflight(/var/containers/Bundle/Application/94ADA493-57B5-41DD-AE19-6001540226D4/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/RoutingHTTPServer.framework/RoutingHTTPServer
  Referenced from: /private/var/containers/Bundle/Application/94ADA493-57B5-41DD-AE19-6001540226D4/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/94ADA493-57B5-41DD-AE19-6001540226D4/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: required code signature missing for '/private/var/containers/Bundle/Application/94ADA493-57B5-41DD-AE19-6001540226D4/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer'
)
2018-04-18 18:31:17.457 xcodebuild[3808:68380] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
	Early unexpected exit, operation never finished bootstrapping - no restart will be attempted
** TEST FAILED **`

**Comment by mykola-mokhnach** [comment] 2018-04-18 13:07
Duplicate of https://github.com/facebook/WebDriverAgent/issues/902

**Closed by mykola-mokhnach** 2018-04-18 13:07 UTC
