### ISSUE TITLE
[debug] [35m[Support][39m Failed to load global package 'opencv4nodejs': The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by sajithgr** [appium/appium#14625] opened 2020-08-05 12:26 UTC
[debug] [35m[Support][39m Failed to load global package 'opencv4nodejs': The "path" argument must be of type string. Received undefined
[debug] [35m[Support][39m Linking package 'opencv4nodejs'
[debug] [35m[Support][39m Retrying load of linked package 'opencv4nodejs'
[35m[Support][39m Unable to load package 'opencv4nodejs': The specified module could not be found.

Still facing the issue on windows 10.
npm list -g --depth=0
+-- appium@1.18.0
+-- node-gyp@7.0.0
+-- opencv4nodejs@5.6.0

Any solution for this??

_Originally posted by @sajithgr in https://github.com/appium/appium/issues/11865#issuecomment-668427135_

**Comment by mykola-mokhnach** [comment] 2020-08-05 12:59
Duplicate of https://github.com/appium/appium/issues/14565

**Closed by mykola-mokhnach** 2020-08-05 12:59 UTC

**Comment by sajithgr** [comment] 2020-08-06 12:17
@mykola-mokhnach Still cant pass this issue.

**Comment by mykola-mokhnach** [comment] 2020-08-06 12:23
Unfortunately this is an issue with opencv installation itself. It has nothing to do with Appium, so we cannot help there
