### ISSUE TITLE
POSSIBLE ISSUE: The newCommandTimeout is not respected????

### ISSUE THREAD

**Issue by gauthierbuttez** [appium/appium#14110] opened 2020-03-26 13:55 UTC
## The problem

My sccript was running a test on Android 7.0 application real device.
The script need to 'start_activity' another app which open back the other app.
THen it continue the test.
Then I get this error output:
```
File "C:\Users\Nino\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 376, in find_elements_by_id
    return self.find_elements(by=By.ID, value=id_)
  File "C:\Users\Nino\AppData\Local\Programs\Python\Python37\lib\site-packages\appium\webdriver\webdriver.py", line 318, in find_elements
    'value': value})['value'] or []
  File "C:\Users\Nino\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Nino\AppData\Local\Programs\Python\Python37\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\Users\Nino\AppData\Local\Programs\Python\Python37\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\Users\Nino\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
```

So I checked the Appium log, and I saw there yellow bullet errors:

```
Got response with status 200: {"sessionId":"a64557a2-9b0d-4387-b8fd-876273456ebf","value":[]}
[BaseDriver] Waited for 1472 ms so far
[BaseDriver] Shutting down because we waited 1200 seconds for a command
[UiAutomator2] Deleting UiAutomator2 session
[Appium] Closing session, cause was 'New Command Timeout of 1200 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session 29c3d692-ef36-4ca6-8f7d-0a4ec6190e10 from our master session list
```
As you can read, Appium consider 1472 ms > 1200 seconds ???

## Environment

* Appium version :1.15.1:
* Desktop OS/version used to run Appium: Windows 10 (version 18362)
* Real device or emulator/simulator: ANdroid 7.0 on Real Smartphone
* Appium CLI or Appium.app|exe: Appium-Python-Client 0.49

## Code To Reproduce Issue [ Good To Have ]
 ```
desired_caps = {}
desired_caps['automationName'] = 'UiAutomator2'
desired_caps['platformName'] = p_os
desired_caps['platformVersion'] = p_version
desired_caps['deviceName'] = p_deviceName
desired_caps['udid'] = p_udid
desired_caps['noReset'] = 'true'
desired_caps['systemPort'] = p_systemPort
desired_caps['chromeDriverPort'] = p_systemPort
desired_caps['appWaitDuration'] = 100000
desired_caps['newCommandTimeout'] = 1200
desired_caps['uiautomator2ServerLaunchTimeout'] = 100000
desired_caps['appWaitPackage'] = 'com.myapp.android'
desired_caps['appPackage'] = 'com.myapp.android'
desired_caps['appActivity'] = 'com.myapp.android.authenticator.LaunchActivity'

driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
```

Do you think it is a bug?

**Comment by mykola-mokhnach** [comment] 2020-03-26 14:01
Possible duplicate of https://github.com/appium/appium/issues/13873

Also, please use the most recent server version

**Comment by mykola-mokhnach** [comment] 2020-03-28 12:45
Closed because of no response

**Closed by mykola-mokhnach** 2020-03-28 12:45 UTC
Labels: NeedsInfo
