### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by Sai417** [appium/appium#15173] opened 2021-03-09 06:29 UTC
## The problem

Not able to launch any app from the Appium, showing this error
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
xcodebuild error message: Quitting and uninstalling WebDriverAgent
 Shutting down sub-processes
## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac OS Big Surr - M1 Chip
* Node.js version (unless using Appium.app|exe): 
* Npm or Yarn package manager:
* Mobile platform/version under test:oS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

## Details

Getting the above error while starting the session from Appium desktop

## Link to Appium logs

Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WebDriverAgent] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Event 'wdaStartFailed' logged at 1615271086699 (11:54:46 GMT+0530 (India Standard Time))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[XCUITest] xcodebuild error message:
[XCUITest] 
[XCUITest] Quitting and uninstalling WebDriverAgent
[WebDriverAgent] Shutting down sub-processes
[iOSSim] Building bundle path map
[iOSSim] The simulator has '1' bundles which have 'WebDriverAgentRunner-Runner' as their 'CFBundleName':
[iOSSim]     'com.facebook.WebDriverAgentRunner.xctrunner'
[WebDriverAgent] Uninstalling WDAs: 'com.facebook.WebDriverAgentRunner.xctrunner'
[XCUITest] {}
[DevCon Factory] Releasing connections for 8B9EBF3F-0B34-432C-878D-96C510549704 device on any port number
[DevCon Factory] Found cached connections to release: ["8B9EBF3F-0B34-432C-878D-96C510549704:8100"]
[DevCon Factory] Cached connections count: 0
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[BaseDriver] Event 'newSessionStarted' logged at 1615271086855 (11:54:46 GMT+0530 (India Standard Time))
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[MJSONWP] xcodebuild error message:
[MJSONWP] 
[MJSONWP]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:543:15)
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:578:11
[MJSONWP]     at wrapped (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:60:13)
[MJSONWP]     at retry (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:43:13)
[MJSONWP]     at retryInterval (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:70:10)
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:558:7
[HTTP] <-- POST /wd/hub/session 500 101328 ms - 259
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found for /wd/hub/session
[HTTP] <-- DELETE /wd/hub/session 404 22 ms - 211
[HTTP] 

## Code To Reproduce Issue [ Good To Have ]

Capabilites:
{
  "platformName": "iOS",
  "deviceName": "iPhone 12 Pro Max",
  "platformVersion": "14.4",
  "automationName": "XCUITest",
  "app": "/Users/sujithreddy/Documents/EclipseWorkspace/UICatalogiOSApp-main/build/iOSAppBuild/UICatalog.app”,
  "newCommandTimeout": "600"
}

Checking simulator, Webdriver is getting installed and uninstalled.

<img width="902" alt="Screenshot 2021-03-09 at 10 14 30 AM" src="https://user-images.githubusercontent.com/36687547/110427964-89e47080-80ce-11eb-881c-bb11d950cc47.png">

**Comment by mykola-mokhnach** [comment] 2021-03-09 07:11
Please provide the full log with xcodebuild logging enabled. Also, make sure you don't have any leftovers after previous Appium versions and that you could build WDA manually from Xcode. Possible duplicate of https://github.com/appium/appium/issues/14952

**Comment by mykola-mokhnach** [comment] 2021-03-11 08:42
Closed as not an issue

**Closed by mykola-mokhnach** 2021-03-11 08:42 UTC
Labels: NeedsInfo, NotABug
