### ISSUE TITLE
Appium inspector not launching and application under tests launching multiple times and closing.

### ISSUE THREAD

**Issue by Sha-123** [appium/appium#14483] opened 2020-06-24 14:16 UTC
## The problem

Appium inspector not launching and application under tests launching multiple times and closing.

## Environment

* Appium version : 1.17
* Desktop OS/version used to run Appium: Mac OS high seiraa
* Real device or emulator/simulator: Real device iPhone 11(OSv13.5.1)

## Link to Appium logs

[appium-server-logs.txt](https://github.com/appium/appium/files/4825921/appium-server-logs.txt)

**Comment by Sha-123** [comment] 2020-06-24 14:16
Please help me to resolve this issue.

**Comment by mykola-mokhnach** [comment] 2020-06-25 17:37
I cannot reproduce the described issue locally. To me it looks like an environment issue where outdated xctest libraries are linked to WDA

**Comment by mykola-mokhnach** [comment] 2020-06-29 19:58
Closed as third party issue

**Closed by mykola-mokhnach** 2020-06-29 19:58 UTC
Labels: ThirdParty, XCUITest

**Comment by IsaacDempsey** [comment] 2020-07-15 14:27
@Sha-123 Did you find a way to resolve this issue? Having a similar situation.

**Comment by Sha-123** [comment] 2020-07-15 14:43
@IsaacDempsey I don't know the exact reason but I think problem is xcode 10.1 not supporting real device with iOS version 13.5.1.
The issue resolved when I used simulator iPhone XR with iOS version12.1
