### ISSUE TITLE
Find by ID doesn't work for Appium version 1.20.0

### ISSUE THREAD

**Issue by 232629** [appium/appium#15020] opened 2021-01-14 11:37 UTC
## The problem

*Steps*

1. Try to get element by id 
2. By.id("start_now")

*Current*
Element not found {By.id: start_now}
xpath and full resource-id works
*Expected*
Got element

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20
* Last Appium version that did not exhibit the issue (if applicable): 1.19.1
* Desktop OS/version used to run Appium: not Desktop 
* Node.js version (unless using Appium.app|exe): node -v v12.16.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe:

## Link to Appium logs
[appium.log 1.20](https://gist.github.com/232629/0aa2e32689c891897bc1cc0b9cb3690b)

## Code To Reproduce Issue [ Good To Have ]

`$(By.id("start_now").click()`

**Comment by vitalyk** [comment] 2021-01-14 11:56
I'm getting the same issue with v.1.20.0

```
Original error: Cannot rewrite element locator 'txthaveaccount' to its complete form, because the current application package name is unknown. Consider providing the app package name or changing the locator to '<package_name>:id/txthaveaccount' format.)
```

my package name is actually specified via capabilities and I can get it correct by using `driver.current_package`

**Comment by mykola-mokhnach** [comment] 2021-01-14 12:08
Duplicate of https://github.com/appium/appium/issues/15013

**Closed by mykola-mokhnach** 2021-01-14 12:08 UTC

**Comment by ganjarpanji** [comment] 2021-01-14 12:20
hi @mykola-mokhnach since so many user creating duplicated issues for this, will be better if you can use `pin issue` feature from the original feature so everyone could notice the issue is there. just my opinion
https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/pinning-an-issue-to-your-repository

**Comment by mykola-mokhnach** [comment] 2021-01-14 20:24
Thanks, pinned
