### ISSUE TITLE
Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s 98895443364a4a4 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'

### ISSUE THREAD

**Issue by rganapathy** [appium/appium#9614] opened 2017-11-10 00:34 UTC
## The problem
Appium server always timing out when launching the APP when trying to unlock

## Environment

* Appium version - v1.7.1
* Desktop OS/version used to run Appium: Windows/Mac
* Mobile platform/version under test: Android 7
* Real device or emulator/simulator: Real Device

## Appium logs

[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","98895443364a4a4","shell","am","start","-W","-n","io.appium.unlock/.Unlock","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"][debug] [ADB] Running 'C:\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","98895443364a4a4","shell","am","start","-W","-n","io.appium.unlock/.Unlock","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"][error] [ADB] Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s 98895443364a4a4a35 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'
    at Object.wrappedLogger.errorAndThrow (C:\Users\rg241w\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at ADB.callee$0$0$ (C:\Users\rg241w\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\rg241w\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\rg241w\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\rg241w\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\rg241w\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
 Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s 98895443364a4a4 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'
    at Object.wrappedLogger.errorAndThrow (C:\Users\rg241w\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at ADB.callee$0$0$ (C:\Users\rg241w\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\rg241w\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\rg241w\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\rg241w\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\rg241w\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)[debug] [AndroidDriver] Screen is locked, trying to unlock
[warn] [AndroidDriver] Using app unlock, this is going to be deprecated!

**Comment by mykola-mokhnach** [comment] 2017-11-10 06:59
Duplicate of https://github.com/appium/appium/issues/9602.

Switch to UIAutomator2 and use skipUnlock capability.

**Closed by mykola-mokhnach** 2017-11-10 06:59 UTC

**Comment by jiddewar10** [comment] 2018-07-18 10:23
I am also facing the same problem. Any solution for these?
