### ISSUE TITLE
Keep get proxy with no body - issue by chromedriver, appium 1.6.3

### ISSUE THREAD

**Issue by TELUD** [appium/appium#7884] opened 2017-02-16 06:16 UTC
## The problem

I am trying switch to the webview after setting the capabilities. However, there is a proxy problem keep happening. I did some search, some people said that is the version problem. However, I've check that the appium is already the latest version (*I am not using GUI) and the chromedriver is 25. 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium: Windows 8.1
* Node.js version (unless using Appium.app|exe): 6.0
* Mobile platform/version under test: Android 5.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

I am using the appium java client 4.1.2 and junit 4.12. The connection between the server and the device success, but when entering the app, there is a repeating problem

## Link to Appium logs

[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\android-sdk-windows\platform-tools\adb.exe
[debug] [ADB] Setting device id to DeviceNumber
[BaseDriver] Using local app 'C:\Users\Woody\Desktop\welcome_ii\welcome\platforms\android\build\outputs\apk\android-debug.apk'
[debug] [AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","wait-for-device"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","install","C:\\Users\\Woody\\AppData\\Roaming\\nvm\\v6.0.0\\node_modules\\appium\\node_modules\\io.appium.settings\\bin\\settings_apk-debug.apk"]
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","install","C:\\Users\\Woody\\AppData\\Roaming\\nvm\\v6.0.0\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk"]
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","shell","getprop","ro.build.version.release"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","shell","dumpsys","window"]
[AndroidDriver] Screen already unlocked, doing nothing
[debug] [AndroidDriver] Parsing package and activity from app manifest
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from C:\android-sdk-windows\build-tools\22.0.1\aapt.exe
[ADB] Extracting package and launch activity from manifest
[debug] [ADB] badging package: package-name
[debug] [ADB] badging act: XXXXXXXXXXXXXXXXXXXXXXX.MainActivity
[debug] [AndroidDriver] Parsed package and activity are: XXXXXXXXXXXXXXXXXX/XXXXXXXXXXX.MainActivity
[AndroidDriver] Remote apk path is /data/local/tmp/3a8dd8e010c799077268eb6789591821.apk
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","shell","ls","/data/local/tmp/3a8dd8e010c799077268eb6789591821.apk"]
[debug] [AndroidDriver] Checking if app is installed
[debug] [ADB] Getting install status for XXXXXXXXXXXXXX
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","shell","getprop","ro.build.version.sdk"]
[debug] [ADB] Device API level: 22
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","shell","pm","list","packages","-3","XXXXXXXXXXXXXXX"]
[debug] [ADB] App is  installed
[AndroidDriver] Apk is already on remote and installed, resetting
[debug] [AndroidDriver] Running fast reset (stop and clear)
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","shell","am","force-stop","XXXXXXXXXXXXXXXXXXXXXXXXX"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","shell","pm","clear","XXXXXXXXXXXXXXXXXXXX"]
[debug] [AndroidDriver] Extracting strings from apk C:\Users\Woody\Desktop\welcome_ii\welcome\platforms\android\build\outputs\apk\android-debug.apk null C:\Users\Woody\AppData\Local\Temp\XXXXXXXXXXXXXXXXXXXXXXXXX
[debug] [ADB] Extracting strings for language: default
[debug] [ADB] Device API level: 22
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","shell","getprop","persist.sys.language"]
[debug] [ADB] Current device property 'persist.sys.language': zh
[debug] [ADB] No strings.xml for language 'zh', getting default strings.xml
[debug] [ADB] Reading strings from converted strings.json
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","push","C:\\Users\\Woody\\AppData\\Local\\Temp\\package-name\\strings.json","/data/local/tmp"]
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","forward","tcp:4724","tcp:4724"]
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","push","C:\\Users\\Woody\\AppData\\Roaming\\nvm\\v6.0.0\\node_modules\\appium\\node_modules\\appium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar","/data/local/tmp/"]
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","DeviceNumber","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","package-name","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[debug] [UiAutomator] Moving to state 'online'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[debug] [ADB] Device API level: 22
[debug] [ADB] Getting connected devices...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","shell","am","start","-W","-n","package-name/packageActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Waiting for pkg: 'package-name' and activity: 'packageActivity' to be focused
[debug] [ADB] Possible activities, to be checked: packageActivity, .MainActivity, .packageActivity
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","shell","dumpsys","window","windows"]
[debug] [ADB] Found package: 'package-name' and activity: '.MainActivity'
[AndroidDriver] Setting auto webview to context 'WEBVIEW_NAME' with timeout 2000ms
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_30256 mapped to pid 30256
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","shell","ps"]
[debug] [AndroidDriver] Parsed pid: 30256 pkg: package-name!
[debug] [AndroidDriver] from: u0_a413,30256,349,3447064,126012,ffffffff,00000000,S,package-name
[debug] [AndroidDriver] returning process name: package-name
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_NAME"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_NAME"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_NAME'
[debug] [AndroidDriver] A port was not given, using random port: 8000
[debug] [Chromedriver] Changed state to 'starting'
[Chromedriver] Set chromedriver binary as: C:\Users\Woody\AppData\Roaming\nvm\v6.0.0\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
[Chromedriver] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"8000 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Spawning chromedriver with: C:\Users\Woody\AppData\Roaming\nvm\v6.0.0\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --url-base=wd/hub --port=8000 --adb-port=5037
[Chromedriver] [STDOUT] Starting ChromeDriver 2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed) on port 8000
Only local connections are allowed.
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[debug] [Chromedriver] Changed state to 'stopped'
[Chromedriver] SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at new ProxyRequestError (../../../lib/mjsonwp/errors.js:322:26)
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:126:13)
    at tryCatch (C:\Users\Woody\AppData\Roaming\nvm\v6.0.0\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Woody\AppData\Roaming\nvm\v6.0.0\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Woody\AppData\Roaming\nvm\v6.0.0\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Woody\AppData\Roaming\nvm\v6.0.0\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
 SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at new ProxyRequestError (../../../lib/mjsonwp/errors.js:322:26)
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:126:13)
    at tryCatch (C:\Users\Woody\AppData\Roaming\nvm\v6.0.0\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Woody\AppData\Roaming\nvm\v6.0.0\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Woody\AppData\Roaming\nvm\v6.0.0\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Woody\AppData\Roaming\nvm\v6.0.0\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_30256 mapped to pid 30256
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","DeviceNumber","shell","ps"]
[debug] [AndroidDriver] Parsed pid: 30256 pkg: package-name!
[debug] [AndroidDriver] from: u0_a413,30256,349,3501516,142880,ffffffff,00000000,S,package-name
[debug] [AndroidDriver] returning process name: package-name
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_NAME"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_NAME"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_NAME'
[debug] [AndroidDriver] A port was not given, using random port: 8000
[debug] [Chromedriver] Changed state to 'starting'
[Chromedriver] Set chromedriver binary as: C:\Users\Woody\AppData\Roaming\nvm\v6.0.0\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
[Chromedriver] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"8000 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Spawning chromedriver with: C:\Users\Woody\AppData\Roaming\nvm\v6.0.0\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --url-base=wd/hub --port=8000 --adb-port=5037
[Chromedriver] [STDOUT] Starting ChromeDriver 2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed) on port 8000
Only local connections are allowed.
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body

..... REPEAT THESE several times

## Code To Reproduce Issue [ Good To Have ]

`	private AppiumDriver driver = null;
	
	@Before
	public void setup() throws MalformedURLException {	
		
		DesiredCapabilities capa = new DesiredCapabilities();
		
    	File appDir = new   File("XXXXXXXXX");
		File app = new File(appDir, "XXXXX");
		
		capa.setCapability("deviceName", "XXXXXX");
		capa.setCapability(CapabilityType.BROWSER_NAME, ""); //Name of mobile web browser to automate. Should be an empty string if automating an app instead.
		capa.setCapability(CapabilityType.VERSION, "5.1");
		capa.setCapability("platformName", "Android");
		capa.setCapability("app-package", "XXXXX");
		capa.setCapability("app-activity", "XXXXXX");
		capa.setCapability("app", app.getAbsolutePath());
		capa.setCapability("device", "Android");
		capa.setCapability("autoWebview", true);
		driver = new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"), capa);
		
	}`

**Comment by mykola-mokhnach** [comment] 2017-02-16 08:42
It might be your browser/webview is already not supported by the chromedriver currently included into Appium bundle. Try to downgrade the driver or update the webview component.

Possible duplicate of https://github.com/appium/appium/issues/7816

**Comment by TELUD** [comment] 2017-02-27 06:52
@mykola-mokhnach I am sorry. There is still the proxying problem. I have seen #7816 , I think that there is no syntax error: unexpected token < in JSON there. I have already tried to downgrade and upgrade my chromedriver, but the problem still happen.

**Comment by imurchie** [comment] 2017-02-27 15:29
That is an issue with your local proxy getting in the way. Try turning off proxying for the ChromeDriver port on localhost.

**Comment by TELUD** [comment] 2017-02-28 07:14
@imurchie Thank you. However, how could I turn off proxying for the ChromeDriver port on localhost. Should I set it on the chrome, eclipse or by using server flags provided by appium?

**Comment by imurchie** [comment] 2017-02-28 13:02
None of those. This is not an Appium problem, but one with the proxy you are using between you and the internet.

**Closed** 2017-04-13 22:17 UTC
Labels: NeedsTriage
