### ISSUE TITLE
Not able to launch application correctly

### ISSUE THREAD

**Issue by sheelendragahlaut** [appium/appium#12532] opened 2019-04-23 13:18 UTC
## Not able to launch mobile application correctly

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:12.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:MacOS 10.14.4
* Node.js version (unless using Appium.app|exe):6.4.1
* Npm or Yarn package manager:npm
* Mobile platform/version under test:12.2
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe: Appium.app

## Details
 WebDriver agent runner build is successful when trying to build using XCode (IDE or command line) but when trying to launch application using Appium Inspector or Code, app under test launches and closes multiple times and at the end it fails

## Link to Appium logs

https://gist.github.com/sheelendragahlaut/93317ce49b57940209e6e16fcce45cce

## Code To Reproduce Issue [ Good To Have ]

No Code.. Just trying to launch app using Appium Inspector. Same behavior if I try to launch using code.

**Comment by mykola-mokhnach** [comment] 2019-04-23 13:36
Possible duplicate of https://github.com/appium/appium/issues/12503

**Comment by mykola-mokhnach** [comment] 2019-04-26 04:48
Closed as not an Appium issue.

**Closed by mykola-mokhnach** 2019-04-26 04:48 UTC
Labels: NotABug, XCUITest
