### ISSUE TITLE
Finding element or getting page source is delayed while Android app is downloading content

### ISSUE THREAD

**Issue by JoelWhitney** [appium/appium#14612] opened 2020-07-30 15:11 UTC
## The problem

It appears like the server gets bogged down when downloading content in the Android app I'm testing against. **This does not reproduce on the iOS companion app**

You can reproduce this by tapping Refresh Source in Appium Desktop or typing source in Appium Ruby Console, notice it takes forever to get a response (10.221 seconds compared to the normal 0.193 seconds). I originally ran into this when trying to find an element and my test was failing as by the time the request was processed the element no longer existed (it did when the request was sent out)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.15.5
* Node.js version (unless using Appium.app|exe): 12.16.3
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android Pixel 2 Emulator API 28
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

While app is downloading item and progress indicator is shown -- **`getPageSource` takes 10221 ms**
```
[HTTP] --> GET /wd/hub/session/e006a020-c800-4383-8464-1717d314759c/source
[HTTP] {}
[W3C (e006a020)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/e006a020-c800-4383-8464-1717d314759c/source' to command name 'getPageSource'
[WD Proxy] Proxying [GET /wd/hub/session/e006a020-c800-4383-8464-1717d314759c/source] to [GET http://127.0.0.1:8201/wd/hub/session/78fd767e-472c-4f72-be8d-fc2984d59aa7/source] with body: {}
[WD Proxy] Got response with status 200: {"sessionId":"78fd767e-472c-4f72-be8d-fc2984d59aa7","value":"\r\n\r\n  \r\n    \r\n      
[WD Proxy] Replacing sessionId 78fd767e-472c-4f72-be8d-fc2984d59aa7 with e006a020-c800-4383-8464-1717d314759c
[HTTP] <-- GET /wd/hub/session/e006a020-c800-4383-8464-1717d314759c/source 200 10221 ms - 26239
```

While app is NOT downloading item and progress indicator not being shown -- **`getPageSource` takes 193 ms**
```
[HTTP] --> GET /wd/hub/session/e006a020-c800-4383-8464-1717d314759c/source
[HTTP] {}
[W3C (e006a020)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/e006a020-c800-4383-8464-1717d314759c/source' to command name 'getPageSource'
[WD Proxy] Proxying [GET /wd/hub/session/e006a020-c800-4383-8464-1717d314759c/source] to [GET http://127.0.0.1:8201/wd/hub/session/78fd767e-472c-4f72-be8d-fc2984d59aa7/source] with body: {}
[WD Proxy] Got response with status 200: {"sessionId":"78fd767e-472c-4f72-be8d-fc2984d59aa7","value":"\r\n\r\n  \r\n    \r\n      
[WD Proxy] Replacing sessionId 78fd767e-472c-4f72-be8d-fc2984d59aa7 with e006a020-c800-4383-8464-1717d314759c
[HTTP] <-- GET /wd/hub/session/e006a020-c800-4383-8464-1717d314759c/source 200 193 ms - 25183
```

## Link to Appium logs

[Full Logs](https://gist.github.com/JoelWhitney/ba77237338ac75c494d12404594b22d9) see very bottom for two requests for source -- once when app is downloading content, and once when not

**Comment by mykola-mokhnach** [comment] 2020-07-30 15:25
Duplicate of https://github.com/appium/appium/issues/14594

**Closed by mykola-mokhnach** 2020-07-30 15:25 UTC

**Comment by JoelWhitney** [comment] 2020-07-30 15:35
Thanks @mykola-mokhnach didn't see that one, will try setting waitForIdleTimeout
