### ISSUE TITLE
Continuously WDA is not working after update the Iphone to 10.3.1, Xcode to 8.3 and Appium 1.6.4@beta.2

### ISSUE THREAD

**Issue by Manikanta29** [appium/appium#8192] opened 2017-04-07 12:16 UTC
## The problem

Update Xcode to 8.3 and Appium to 1.6.4@beta.2. After the update, I was able to run my code on the real device iphone(10.3.1). After some time, I am getting " xcodebuild exited with code '65' and signal 'null' ". 

Appium logs: 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/manikantav/Documents/workspace_Mars2/Claim.ipa","buldleId":"com.abc.xyz","noReset":"false","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","automationName":"XCUITEST","udid":"UDID","platformName":"iOS","deviceName":"iPhone","launchTimeout":500000}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/manikantav/Documents/workspace_Mars2/Claim.ipa","buldleId":"com.abc.xyz","noReset":"false","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","automationName":"XCUITEST","udid":"UDID","platformName":"iOS","deviceName":"iPhone","launchTimeout":500000},null,null,null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1491566367528 (17:29:27 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.27.1) session
[Appium] Capabilities:
[Appium]   app: '/Users/manikantav/Documents/workspace_Mars2/Claim.ipa'
[Appium]   buldleId: 'com.abc.xyz'
[Appium]   noReset: 'false'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   automationName: 'XCUITEST'
[Appium]   udid: 'UDID'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone'
[Appium]   launchTimeout: 500000
[debug] [XCUITest] XCUITestDriver version: 2.27.1
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: buldleId, realDeviceLogger.
[BaseDriver] Session created with session id: fbd5db84-0b86-4675-b8a9-00dc7409008a
[debug] [XCUITest] Xcode version set to '8.3' (tools v8.3.0.0.1.1490382677)
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1491566369243 (17:29:29 GMT+0530 (IST))
[debug] [XCUITest] Available devices: UDID, UDID
[debug] [XCUITest] Creating iDevice object with udid 'UDID'
[XCUITest] Determining device to run tests on: udid: 'UDID', real device: true
[BaseDriver] Using local app '/Users/manikantav/Documents/workspace_Mars2/Claim.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201737-1392-9mybrr.wm3zfiggb9/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201737-1392-9mybrr.wm3zfiggb9/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201737-1392-9mybrr.wm3zfiggb9/Payload/ClaimReporter.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1491566376925 (17:29:36 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201737-1392-9mybrr.wm3zfiggb9/Payload/ClaimReporter.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201737-1392-9mybrr.wm3zfiggb9/Payload/ClaimReporter.app': 'com.Bassett.connect.test'
[debug] [BaseDriver] Event 'resetStarted' logged at 1491566376938 (17:29:36 GMT+0530 (IST))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1491566376940 (17:29:36 GMT+0530 (IST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1491566377386 (17:29:37 GMT+0530 (IST))
[XCUITest] Setting up real device
[debug] [XCUITest] Reset requested. Removing app with id 'com.Bassett.connect.test' from the device
[debug] [XCUITest] Installing '/var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201737-1392-9mybrr.wm3zfiggb9/Payload/ClaimReporter.app' on device with UUID 'UDID'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1491566401448 (17:30:01 GMT+0530 (IST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1491566401450 (17:30:01 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[XCUITest] Cannot parse major and minor version numbers from platformVersion "null". Will build for the default platform instead
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=UDID -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/manikantav/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/E01E7A2C-2DD1-4506-AF6B-55BCD9F750AA/Session-WebDriverAgentRunner-2017-04-07_173023-3bSO3k.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2017-04-07 17:30:31.403 xcodebuild[2892:160905] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] 2017-04-07 17:30:31.127841+0530 XCTRunner[1210:224550] Running tests...
[Xcode] 2017-04-07 17:30:31.456951+0530 XCTRunner[1210:224575] Connection peer refused channel request for "dtxproxy:XCTestDriverInterface:XCTestManager_IDEInterface"; channel canceled <DTXChannel: 0x174085280>
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1491566431440 (17:30:31 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 2890)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1491566442317 (17:30:42 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[XCUITest] Cannot parse major and minor version numbers from platformVersion "null". Will build for the default platform instead
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=UDID -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/manikantav/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/0671D6B3-5BDB-4D50-842A-94EF9A2E64B9/Session-WebDriverAgentRunner-2017-04-07_173049-m2DLRd.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2017-04-07 17:30:57.086 xcodebuild[2920:161719] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] 2017-04-07 17:30:56.803849+0530 XCTRunner[1215:224922] Running tests...
[Xcode] 2017-04-07 17:30:57.142196+0530 XCTRunner[1215:224949] Connection peer refused channel request for "dtxproxy:XCTestDriverInterface:XCTestManager_IDEInterface"; channel canceled <DTXChannel: 0x174094640>
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1491566457124 (17:30:57 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 2919)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[debug] [XCUITest] Error : Command 'ios-deploy --uninstall_only --id UDID --bundle_id com.apple.test.WebDriverAgentRunner-Runner' exited with code 253
[XCUITest] Error: Could not remove app: 'Command 'ios-deploy --uninstall_only --id UDID --bundle_id com.apple.test.WebDriverAgentRunner-Runner' exited with code 253'
    at IOSDeploy.remove$ (../../lib/ios-deploy.js:25:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Could not remove app: 'Command 'ios-deploy --uninstall_only --id UDID --bundle_id com.apple.test.WebDriverAgentRunner-Runner' exited with code 253'
    at IOSDeploy.remove$ (../../lib/ios-deploy.js:25:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Could not remove app: 'Command 'ios-deploy --uninstall_only --id UDID --bundle_id com.apple.test.WebDriverAgentRunner-Runner' exited with code 253'
    at IOSDeploy.remove$ (../../lib/ios-deploy.js:25:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 100132 ms - 320 
[iOSLog] Cannot stop log capture process. Sending SIGKILL...

**Comment by mykola-mokhnach** [comment] 2017-04-07 14:05
Closed as duplicate of https://github.com/appium/appium/issues/7192

**Closed by mykola-mokhnach** 2017-04-07 14:05 UTC
Labels: NeedsTriage
