### ISSUE TITLE
Appium trying to pull base apk from /var/folders/ . Error: Error executing adbExec.

### ISSUE THREAD

**Issue by ACBNair** [appium/appium#11478] opened 2018-10-04 07:11 UTC
## The problem

I have updated my setup to the latest appium version (1.9.1) and trying to test in youtube app. Appium is not starting and the following error was shown :  

> Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/Users/mymachine/Library/Android/sdk/platform-tools/adb -P 5037 -s <udid> pull '/data/app/com.google.android.youtube-1/base.apk
> 2018-10-03 16:49:35:712 - info: [debug] [MJSONWP] package:/data/app/com.google.android.youtube-1/split_config.en.apk' /var/folders/mm/xxxxxxx/T/com.google.android.youtube.apk' exited with code 1'; Stderr: ''; Code: '1'
> 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: 10.13.6 and XCode 10 (10A255). 
* Node.js version (unless using Appium.app|exe): v8.11.3
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

I see that the appium code trying to read more things from device than the earlier. This is observerved in Youtube app (assuming systems apps), Other custom apps works fine. 

On further analysis I saw that the manifest files for youtube changed in the latest versions. The old ones (11.27.53_112753144) had a large manifest file. Latest versions(13.39.51_1339513440) have a very small one with lines like : 
```
<?xml version="1.0" encoding="UTF-8"?><manifest versionCode="1339513440" configForSplit="" package="com.google.android.youtube" split="config.en">
  <application hasCode="false">
    <meta-data name="com.android.vending.derived.apk.id" value="1"/>
  </application>
</manifest>
```
The below log shows it is trying to fetch the split and base application and fails.

I know this is a third party app and relevant to its implementation. But I believe we might need to cover such scenarios as well.

## Link to Appium logs

Relevant log lines : 

```
Running '/Users/usr/Library/Android/sdk/platform-tools/adb -P 5037 -s <devid>forward tcp\:8202 tcp\:6790'
2018-10-03 16:49:33:926 - info: [debug] [ADB] Running '/Users/usr/Library/Android/sdk/platform-tools/adb -P 5037 -s devidshell rm -rf /data/local/tmp/strings.json'
2018-10-03 16:49:33:967 - info: [debug] [ADB] Running '/Users/usr/Library/Android/sdk/platform-tools/adb -P 5037 -s devidshell pm path com.google.android.youtube'
2018-10-03 16:49:34:671 - info: [debug] [ADB] Running '/Users/usr/Library/Android/sdk/platform-tools/adb -P 5037 -s devidpull '/data/app/com.google.android.youtube-1/base.apk
2018-10-03 16:49:34:671 - info: [debug] [ADB] package:/data/app/com.google.android.youtube-1/split_config.en.apk' /var/folders/mm/j3gp_5017ps55hj2j54dfrww0000gn/T/com.google.android.youtube.apk'
2018-10-03 16:49:34:687 - info: [debug] [ADB] Running '/Users/devid/Library/Android/sdk/platform-tools/adb -P 5037 -s devidpull '/data/app/com.google.android.youtube-1/base.apk
2018-10-03 16:49:34:687 - info: [debug] [ADB] package:/data/app/com.google.android.youtube-1/split_config.en.apk' /var/folders/mm/j3gp_5017ps55hj2j54dfrww0000gn/T/com.google.android.youtube.apk'
2018-10-03 16:49:34:704 - info: [debug] [UiAutomator2] Deleting UiAutomator2 session
2018-10-03 16:49:34:707 - info: [debug] [UiAutomator2] Deleting UiAutomator2 server session
2018-10-03 16:49:34:708 - info: [debug] [JSONWP Proxy] Matched '/' to command name 'deleteSession'
2018-10-03 16:49:34:710 - warn: [UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
2018-10-03 16:49:34:711 - info: [debug] [ADB] Running '/Users/usr/Library/Android/sdk/platform-tools/adb -P 5037 -s devidshell am force-stop com.google.android.youtube'
```

## Code To Reproduce Issue [ Good To Have ]
Code just try to launch the new youtube app.

**Comment by mykola-mokhnach** [comment] 2018-10-04 07:20
The problem is fixed in appium@beta
Closed as duplicate

**Closed by mykola-mokhnach** 2018-10-04 07:20 UTC

**Comment by KazuCocoa** [comment] 2018-10-04 08:43
https://github.com/appium/appium/issues/11403#issuecomment-424178835
