### ISSUE TITLE
Appium npm issue

### ISSUE THREAD

**Issue by akalankaudesh** [appium/appium#13220] opened 2019-09-11 07:31 UTC
## The problem

I'm new to appium, but i was able to run appium correctly in desktop environment wihout getting any error. But when i run appium through npm, it through a server side error - Error executing adbExec. Original error: 'Command ''C:\\Program Files\\android_sdk\\platform-tools\\adb.exe' -P 5037 -s 192.168.133.101\:5555 forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb.exe: error: listener 'tcp:8200' not found'; Code: '1'' 

## Environment

* Appium version - v1.14.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop version of appium - v1.13.0
* Node.js version -6.11.3
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 5.0
* Real device or emulator/simulator: Genymotion Emulator and try it for my real device too.
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

**Comment by mykola-mokhnach** [comment] 2019-09-11 10:14
> [AndroidDriver] Failed to launch Appium Settings app: Condition unmet after 5345 ms. Timing out.

This the reason why the session cannot be started.

Check the logcat output for possible exception reports and verify the Appium settings helper can be started manually to find out the possible cause of the problem

**Comment by akalankaudesh** [comment] 2019-09-11 11:35
linked for android logcat- https://gist.github.com/akalankaudesh/165a87ab513d3fed5d81993db0f60898

**Comment by mykola-mokhnach** [comment] 2019-09-11 12:22
I don't observe any issues in the logcat output. However, there was already similar issue about the process detection: https://github.com/appium/appium/issues/12947

**Comment by akalankaudesh** [comment] 2019-09-11 12:37
But appium desktop version works fine. it's appium version- v1.13.0. so i downgrade the npm appium version to the current appium desktop version. but it's also didn't work. here it's log- https://gist.github.com/akalankaudesh/df674e160f8760e3031facfa566fac66

**Comment by KazuCocoa** [comment] 2019-09-11 13:03
On your device, what behaviour can you observe with below lines?

```
[debug] [ADB] Got the following command chunks to execute: [["pm","grant","io.appium.settings","android.permission.SET_ANIMATION_SCALE",";","pm","grant","io.appium.settings","android.permission.CHANGE_CONFIGURATION",";","pm","grant","io.appium.settings","android.permission.ACCESS_FINE_LOCATION",";"]]
[debug] [ADB] Running 'C:\Program Files\android_sdk\platform-tools\adb.exe -P 5037 -s 192.168.133.101\:5555 shell pm grant io.appium.settings android.permission.SET_ANIMATION_SCALE \; pm grant io.appium.settings android.permission.CHANGE_CONFIGURATION \; pm grant io.appium.settings android.permission.ACCESS_FINE_LOCATION \;'
[debug] [ADB] Running 'C:\Program Files\android_sdk\platform-tools\adb.exe -P 5037 -s 192.168.133.101\:5555 shell am start -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'C:\Program Files\android_sdk\platform-tools\adb.exe -P 5037 -s 192.168.133.101\:5555 shell pgrep \^appium\\.settings\$'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'C:\Program Files\android_sdk\platform-tools\adb.exe -P 5037 -s 192.168.133.101\:5555 shell pgrep \^appium\\.settings\$'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
```

Maybe, after `C:\Program Files\android_sdk\platform-tools\adb.exe -P 5037 -s 192.168.133.101\:5555 shell am start -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER`, you can see settings app activity on the device.
Then, what output can you get by `'C:\Program Files\android_sdk\platform-tools\adb.exe -P 5037 -s 192.168.133.101\:5555 shell pgrep ^appium\.settings$'`? or `shell pgrep -f io\.appium\.settings`

Expected behaviour is like below. Process id should be returned.
```
$ adb -P 5037 -s emulator-5554 shell pgrep -f io\.appium\.settings
2557
```

**Comment by akalankaudesh** [comment] 2019-09-11 14:15
KazuCoca , yes appium setting is launch but after that this error occured.

**Comment by KazuCocoa** [comment] 2019-09-11 14:26
Can you try some of pgrep like below? We wondered if some devices does not work pgrep well. I think they work since your appium desktop worked.

`adb shell pgrep -f io\.appium\.settings`
`adb shell pgrep -f i`

btw, could you upgrade your node version to over 10?
You probably used 6.11.3.

**Comment by akalankaudesh** [comment] 2019-09-11 16:15
KazuCocoa, the current available node version is 6.11.3, how can i upgrade to over 10

**Comment by KazuCocoa** [comment] 2019-09-11 16:34
https://nodejs.org/en/download/ , for example.
Current LTS is 10.16.3

**Comment by akalankaudesh** [comment] 2019-09-11 17:34
KazuCocoa , i dowload and upgrade it but nothing was happen. same error giving.

**Comment by akalankaudesh** [comment] 2019-09-13 06:59
so , can't you find a solution for this problem

**Comment by KazuCocoa** [comment] 2019-09-13 08:10
Unfortunately, no, I can't.
We wondered if pgrep works on your env. It worked.
So, it was maybe the environment issue rather than the pgrep logic.

You can make sure if `adb shell pgrep` works from your CLI. If it does not work. Maybe the CLI environment has an issue.

**Comment by mykola-mokhnach** [comment] 2019-09-20 05:39
Closed as third party issue

**Closed by mykola-mokhnach** 2019-09-20 05:39 UTC
Labels: Android, ThirdParty

**Comment by bhoopathisiva** [comment] 2020-04-25 05:52
> ## The problem
> I'm new to appium, but i was able to run appium correctly in desktop environment wihout getting any error. But when i run appium through npm, it through a server side error - Error executing adbExec. Original error: 'Command ''C:\Program Files\android_sdk\platform-tools\adb.exe' -P 5037 -s 192.168.133.101:5555 forward --remove tcp:8200' exited with code 1'; Stderr: 'adb.exe: error: listener 'tcp:8200' not found'; Code: '1''
> 
> ## Environment
> * Appium version - v1.14.2
> * Last Appium version that did not exhibit the issue (if applicable):
> * Desktop version of appium - v1.13.0
> * Node.js version -6.11.3
> * Npm or Yarn package manager:
> * Mobile platform/version under test: Android 5.0
> * Real device or emulator/simulator: Genymotion Emulator and try it for my real device too.
> * Appium CLI or Appium.app|exe:
> 
> ## Details
> If necessary, describe the problem you have been experiencing in more detail.
> 
> ## Link to Appium logs-https://gist.github.com/akalankaudesh/1726187a66c1b3652da61448278ce000/revisions

Please tell me if u found solution for this issue, i have been facing this same
