### ISSUE TITLE
[Feat]:Appium limitation - it see only IFrame and it ignores document which is inside the frame

### ISSUE THREAD

**Issue by AnnaSwietek** [appium/appium#18838] opened 2023-07-04 09:36 UTC
In appium inspector, appium see only IFrame and it ignores document which is inside the frame
In html document which is a base for appium the frame also is empty
In actual sources (based on mobile view in desktop chrome) there is document in IFrame.
Please take a look at attached files (appiumInspectoremptyiFrame.png, sourceFromAppium.html, sourceScreenshotIFRAME.png)

**Comment by AnnaSwietek** [comment] 2023-07-04 09:36
![sourceScreenshotIFRAME](https://github.com/appium/appium/assets/81297125/463c89cb-bc49-4c1f-9531-db8543f078ae)
![appiumInspector empty iFrame](https://github.com/appium/appium/assets/81297125/666be41c-f847-40a1-b0d5-7153289922d2)

**Comment by mykola-mokhnach** [comment] 2023-07-04 11:39
Possible duplicate of https://github.com/appium/appium/issues/10184

**Comment by jlipps** [comment] 2023-07-04 17:39
@AnnaSwietek can you confirm what the URL of the iframe is?

**Comment by AnnaSwietek** [comment] 2023-07-05 09:08
Hi Jonathan,

Please firnd video (Reproduction.mp4), url and repro steps:

1.) URL "https://commission.europa.eu/index_en"
2.) Once the url launches, open the search bar and search for the term "Europe"
3.) Wait for the search results to show up
4.) Search for the IFrame with the ID "WT_FRAME_search", this iFrame should contain the search results and some other controls but the iFrame has no content there
________________________________

**Comment by jlipps** [comment] 2023-07-05 20:05
@AnnaSwietek the `src` attribute of this iframe element is `about:blank`, which shows up as a different domain than `europa.eu`. So yes, this issue is likely duplicate of #10184. Unfortunately it seems the fix will require an update of the website since it appears Safari/Safari's remote debugger obeys the [same-origin policy](https://en.wikipedia.org/wiki/Same-origin_policy)

**Comment by AnnaSwietek** [comment] 2023-07-06 07:48
thank you Jonathan!

Kind regards,
a.
________________________________

**Comment by mykola-mokhnach** [comment] 2023-07-07 09:31
Closed as duplicate

**Closed by mykola-mokhnach** 2023-07-07 09:31 UTC
Labels: Mobile Safari, ThirdParty
