### ISSUE TITLE
Appium 1.7.1 is stuck at [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities"

### ISSUE THREAD

**Issue by shane51** [appium/appium#9645] opened 2017-11-16 07:47 UTC
## The problem

When upgraded into Appium 1.7.1, everytime app started by Appium in **Simulator** , I need to wait 2~6 mins to let test run. After check the Appium log, I found Appium paused at:
```
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.***.****","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
```

after 6 mins, Appium get the following, and start to run 
```
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"396FCBB1-11DE-4C6D-8A07-751C97CEB2DC","capabilities":{"device":"iphone","browserName":null,"sdkVersion":"11.1","CFBundleIdentifier":null}},"sessionId":"396FCBB1-11DE-4C6D-8A07-751C97CEB2DC","status":0}
```
## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0, 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5 (no issues)
* Desktop OS/version used to run Appium: Mac OS 10.12.6 
* Node.js version (unless using Appium.app|exe): v7.10.0
* Mobile platform/version under test: iOS 11.0, 11.1, 10.3.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI
* Xcode version: 9.0, 9.1

## Details

Currently, after app launched, I always need to wait 2~6 mins to let Appium responded, and start to run my test... 

Appium 1.6.5 can run it without any issue. I think it should be introduced by 1.7.0 and after.

https://github.com/appium/appium/issues/9482 has the same issue, although the issue has been closed,  she reproduced it again recently, cannot find a solution.

Great thanks!!

## Link to Appium logs

https://gist.github.com/shane51/7fe7e0d5362647ee51d7eaa591cf36bc

### Simulator logs:

https://gist.github.com/shane51/140a4f9556ecb5b9169354c348feed35

## Code To Reproduce Issue [ Good To Have ]

```

    private void iOSCaps() {
        String IOS_APP_PATH = "/src/main/resources/*** - QA.app";
        File app = new File(System.getProperty("user.dir") + IOS_APP_PATH);
        capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.IOS);
        capabilities.setCapability(MobileCapabilityType.FULL_RESET, true);
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, devicesUtils.IOS_DEVICE_NAME);
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, devicesUtils.SIMULATOR_VERSION);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
        capabilities.setCapability(MobileCapabilityType.UDID, devicesUtils.SIMULATOR_UUID);
        capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
        capabilities.setCapability("bundleId", "com.***.qa2");
        capabilities.setCapability("useNewWDA", true);
        //you are free to set additional capabilities
    }

```

**Comment by mykola-mokhnach** [comment] 2017-11-16 08:12
Try to remove useNewWDA, bundleId, MobileCapabilityType.UDID and MobileCapabilityType.FULL_RESET capabilities

**Comment by shane51** [comment] 2017-11-17 01:49
After remove the above. the app cannot launch now..

# Appium log
https://gist.github.com/shane51/c0a2228565de2f7d02c621a9a92e4967

**Comment by shane51** [comment] 2017-11-17 02:06
After I manually reset simulator, the app launched, but I still need to wait 5 mins to let test run, could you please advice is there a way to avoid it? or this is current XCUITest issue?

Great Thanks @mykola-mokhnach 

 #Appium logs:
https://gist.github.com/shane51/8ca25b2bf99484b72ba85df945bb6feb
# Simulator logs:
https://gist.github.com/shane51/781a6aeffa3de50e19de9b21edef1572

**Comment by shane51** [comment] 2017-11-17 02:22
![image](https://user-images.githubusercontent.com/4371504/32926187-6daef114-cb0b-11e7-8e1d-5824ca247584.png)

From the log, it shows XCUITest cost 5 mins to create and start wdaSession

**Comment by shane51** [comment] 2017-11-17 05:40
Hi @mykola-mokhnach  when I monitor the test in CI, I found it stuck at POST request randomly, sometimes, it starts to run test while App launched, but sometimes it still wait 5~6 mins to let POST request get the response...

**Comment by mykola-mokhnach** [comment] 2017-11-17 07:24
To me it looks like either like XCTest or application under test issue. Appium just waits for WebDriverAgent to respond and WDA itself waits for the app to say that accessibility is ready.

**Comment by shane51** [comment] 2017-11-18 03:56
@mykola-mokhnach The app under test works fine with Appium 1.6.x for half a year.
This waiting issue came out after I upgrade Appium 1.6.5 to 1.7.0. When I downgrade to 1.6.5, it works fine. So it should related some changes in 1.7.0

**Comment by deedora** [comment] 2017-11-23 17:01
Did you manage to fix the problem?

**Comment by shane51** [comment] 2017-11-24 01:53
Not yet.... I'm consider using WebdriverAgent itself to see if the issue still persist...

**Comment by deedora** [comment] 2017-11-24 10:26
Ok. Let me know if you find the fix.

**Comment by alexttransisland** [comment] 2017-11-25 22:58
When I downgraded to XCode 8.3.3 issue disappeared without magical capabilities. Just FYI as a workaround.

**Comment by OrRosenblatt** [comment] 2017-12-13 02:43
We are experiencing the same issue (Appium v1.7.1, Xcode v9.1, Mac High Sierra OS).

Downgrading Xcode version is not an option for us since some things work only with the Xcode 9 (such as the latest version of homebrew or some pods).

Any idea how to fix?

**Comment by deedora** [comment] 2017-12-18 14:25
@mykola-mokhnach Can somebody look into this?

**Comment by alexttransisland** [comment] 2017-12-18 15:34
The issue magicly disappeared for me after adding
```
    clearSystemFiles: true,
    wdaStartupRetryInterval: 1000,
    useNewWDA: true,
    waitForQuiescence: false,
    shouldUseSingletonTestManager: false
```
caps for Ruby. I didn't play around about what is optional, just a sum up after lurking through this and similar issues on internet.

**Comment by chrisjetstar** [comment] 2017-12-20 07:04
Issue is resolved with resolution from @alexttransisland  
Thanks

**Comment by deedora** [comment] 2017-12-28 08:28
For me "waitForQuiescence: false" starts test before the app has started.

**Comment by tomkeiev** [comment] 2018-01-09 12:45
I have the same issue as @deedora. Anyone knows how to solve the problem without settings 'waitForQuiescence' and 'useNewWDA' capabilities?

**Comment by alexttransisland** [comment] 2018-01-09 14:08
Why can't you make a waiter until your app is launched?
something like
```
before do
  response =  Curl.get('http://localhost:8100/status') # not sure here what exact URL should be here, but something that waits for app initalization
  wait(300).until { Curl.get('http://localhost:8100/status').body_str }.eq('OK')
end
```
or
```
before do
  response =  Curl.get('http://localhost:8100/status') # not sure here what exact URL should be here, but something that waits for app initalization. I am not sure whether it would work, just a guess.
  wait(300).until { Curl.get('http://localhost:8100/status').body_str }.eq('OK')
end
```
I mean you can programmatically check whatever Appium returns. (appium DOM, transport layer connection etc.)

**Comment by quintuschen** [comment] 2018-01-18 04:01
I have similar problem, I tried to set the caps the same as @alexttransisland suggested. It worked for  one time and when I tried to run the same case again, the problem is happening again.

**Comment by bayerjan** [comment] 2018-02-14 15:44
Got the same problem here. Using Java as a base technology, but virtually always takes long

**Comment by igorrfc** [comment] 2018-02-18 18:13
Same problem here =/ Does anyone figured out how to solve it?

**Comment by igorrfc** [comment] 2018-02-18 18:22
@alexttransisland solution worked for me. Thanks a lot dude, I was struggling trying to fix this has been a while.

**Comment by quintuschen** [comment] 2018-02-18 20:59
Hey @igorrfc with @alexttransisland 's solution, do your cases always run? For my case sometimes it runs smoothly but sometimes it still stuck.

**Comment by igorrfc** [comment] 2018-02-19 00:49
Hey @quintuschen, after add the suggested configs I have stable tests. Actually, I'm integrating the appium on my project, so I don't have many test cases. After you asked me this, I tried to add more tests, and the suite still running well. Would you like to know my environment specs or something like that?

**Comment by quintuschen** [comment] 2018-02-19 01:01
Hey @igorrfc If you could share some of your environment specs that would be awesome. My test cases are running well on Appium 1.6.5 and Xcode 8.3 but now it is very unstable. On Android it runs fine but iOS it often stuck at this stage.

**Comment by auto-mator** [comment] 2018-02-26 05:50
Any official solution to this issue? I need to be able to automate iOS 11.x the same way I am able to automate 10.3.3, and it just does not work. If I have noReset = true, all testing is fine, but I cannot uninstall and reinstall the app because the Profile is no longer trusted within General > Profiles on the device. Why is this?

**Comment by bayerjan** [comment] 2018-02-26 08:16
Hi @auto-mator This should actually be a new ticket since it is a separate issue
If I am not mistaken as long as one app with the profile (trusted) is kept on the device it will work. As soon as the last app is uninstalled then one needs to re-trust the profile. 
Coming to think of it, how would this be solved on a simulator? Is trusting necessary?

**Comment by auto-mator** [comment] 2018-02-26 15:30
That's a good point...that may work as a work-around. But why doesn't this work on iOS 11 in general, but is fine for iOS 10? I have no issues with maintaining trust when no reset is false on iOS 10

**Comment by auto-mator** [comment] 2018-03-25 05:45
Sure enough, your idea worked perfectly Bayerjan! Thank you

**Comment by jesushebra** [comment] 2018-04-05 10:54
Unfortunately, I have exactly the same problem working with newer versions that all those presented at the problem description of this issue. I work with Xcode 9.2 and I have checked that happens with these Appium versions: 1.7.0, 1.7.1, 1.7.2 and 1.8.0-beta.

This is an extract of my Appium logs. Once the app has been installed into a simulator/device, next logs are recurrent and it is impossible to run my own test cases:
...
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.xxx.yyy","arguments":[],"environment":{},"shouldWaitForQuiescence":false,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.accenture.carrefour-cuali application","sessionId":"49A826C6-A2D8-42FF-9347-9F1FF994BF7B","status":13}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1522924456876 (12:34:16 GMT+0200 (CEST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.xxx.yyy","arguments":[],"environment":{},"shouldWaitForQuiescence":false,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
[HTTP] <-- POST /wd/hub/session - - ms - -
[HTTP]
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.xxx.yyy application","sessionId":"49A826C6-A2D8-42FF-9347-9F1FF994BF7B","status":13}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1522924639155 (12:37:19 GMT+0200 (CEST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.xxx.yyy","arguments":[],"environment":{},"shouldWaitForQuiescence":false,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
...

These are all capabilities I have configured, according to previous comments:
capabilities.setCapability("deviceName", "iPhone 6");
capabilities.setCapability("platformName","iOS");
capabilities.setCapability("platformVersion", "11.2");
capabilities.setCapability("automationName", "XCUITest");
capabilities.setCapability("clearSystemFiles", true);
capabilities.setCapability("wdaStartupRetryInterval", 1000);
capabilities.setCapability("useNewWDA", true);
capabilities.setCapability("waitForQuiescence", false);
capabilities.setCapability("shouldUseSingletonTestManager", false);
capabilities.setCapability("showXcodeLog", true);
capabilities.setCapability("app", binaryFile.getAbsolutePath());

I can't come back to previous versions of Appium because I need Xcode 9 for my project. I don't find the solution to the problem. Could someone help me, please?

Thanks in advance.

**Comment by quintuschen** [comment] 2018-04-05 21:09
@jesushebra, we have been battling this issue for quite a while but we do not find the root cause. However, this might be a workaround that you could give a try. The cases won't run on my old Mac until I upgraded to a more powerful, better CPU and most importantly an SSD. Then with same settings and the same suite, they run smoothly, which makes me suspect the original problem is due to the hard disk was actually too slow to initiate the tests and it is too slow for WDA to launch. Just my guess I have no proof of that though.

**Comment by jesushebra** [comment] 2018-04-06 06:29
@quintuschen, thank you very much for your answer. I use a MacBook Pro with next properties:
SO: macOS High Sierra v10.13.3
Id: MacBookPro14,1
Processor: 2,3 GHz Intel Core i5
Memory: 8 GB 2133 MHz LPDDR3
Graphics: Intel Iris Plus Graphics 640 1536 MB

Do you think it's normal I have problems with this computer? I purchased this Mac last month. 
Thanks again

**Comment by deedora** [comment] 2018-04-09 06:31
I don't think that is the only solution. My problem disappeared after I've removed every possible trace of appium from my mac and updated to 1.7.2. Also, try to remove the app you are testing, rebuild it and then install it.

**Comment by jesushebra** [comment] 2018-04-09 06:49
@quintuschen, yes, it comes with SSD (Apple SDD SM0128L). In fact, it is a powerful Mac. However, your solution does not work for me.
@deedora, what do you mean by "I've removed every possible trace of appium from my mac"? I have uninstalled Appium and installed again (v1.7.2). I've also removed the app. However, the problem continues

**Comment by jesushebra** [comment] 2018-04-09 07:51
@deedora, I've uninstalled appium, I've deleted all files and folders and I've installed appium again. However, the problem persists (even if I rebuild the app). The situation starts to be frustrating

**Comment by zcmgyu** [comment] 2018-04-21 17:40
> useNewWDA: true
> clearSystemFiles: true 

It works for me.

**Closed** 2018-04-30 15:01 UTC
Labels: ThirdParty, XCUITest

**Comment by marlon641** [comment] 2018-04-30 22:00
Did anyone find a solution to this problem?

**Comment by Pr60** [comment] 2018-05-01 18:27
Even I'm facing this issue. Any updates on this one?

**Comment by jpita** [comment] 2018-06-13 16:40
Appium 1.8
xcode 9.4

`      capabilities.setCapability("waitForQuiescence", false)
            capabilities.setCapability("useNewWDA", true)
            capabilities.setCapability("shouldUseSingletonTestManager", false)
            capabilities.setCapability("clearSystemFiles", true)
            capabilities.setCapability("shouldUseTestManagerForVisibilityDetection", true)`

still have the issue...

**Comment by NiveditaSachan** [comment] 2018-09-18 04:17
@jpita I am also facing the same issue. it opens and closes the app 3 times and then just hangs. DId you find any workaround ?

**Comment by NiveditaSachan** [comment] 2018-09-18 10:34
@jpita Thanks for responding. It worked for me when I used Simulator build to inspect elements of my native iOS app.

**Comment by krishna8181** [comment] 2018-11-26 06:54
thank you so much guys, i have managed to fix the issue using solution proposed by @alexttransisland. making some good progress

**Comment by Marrowbones** [comment] 2018-12-12 09:04
In case anyone is still having the same problem, try upgrading everything (NPM, Appium, etc); I know it sounds obvious, but what's probably happened is that you've installed an OS upgrade that's not compatible with some component of the Appium/WebDriver setup.  For me, the problem was carthage (brew update carthage) - an easy one to overlook. Hope this helps.

**Comment by chaotive** [comment] 2018-12-19 20:11
I have this very same issue, as I reported it back again on this ticket: https://github.com/appium/appium/issues/11864

**Comment by hangyumao** [comment] 2019-01-10 09:14
> @jpita我也面临同样的问题。它打开和关闭应用程序3次，然后挂起。你找到任何解决方法吗？

hello, have you resolved the problem?

**Comment by hangyumao** [comment] 2019-01-10 09:15
> @jpita I am also facing the same issue. it opens and closes the app 3 times and then just hangs. DId you find any workaround ?

hello, have you resolved this problem?
