### ISSUE TITLE
Ability to execute adb command via appium

### ISSUE THREAD

**Issue by dienstfuchs** [appium/appium#5725] opened 2015-10-14 15:12 UTC
Is it possible to execute an adb command via appium?

**Comment by nabeel-ibrahim** [comment] 2015-10-14 16:10
you can using the using the Runtime class. Here's an example
final String[] cmd = { "/bin/sh", "-c", "adb devices" };		
try {
			final Process process = Runtime.getRuntime().exec(cmd);
			inStream = process.getInputStream();
			final BufferedReader br= new BufferedReader(
					new InputStreamReader(inStream));
			while ((line = br.readLine()) != null) {
				returnValue = returnValue + line + "\n";
			}
			br.close();
			try {
				process.waitFor();
			} catch (final InterruptedException e) {
				System.out.println(e.getMessage());
			}
		} catch (final Exception e) {
			System.out.println(e.getMessage());
		}
		System.out.println(returnValue);

**Comment by dienstfuchs** [comment] 2015-10-14 16:15
Thanks for your answer.

But this will only apply if the appium server is on the local machine. I need a solution where the server is on a different machine, or even SauceLabs.

Thanks,

Stefan

**Comment by amedvedjev** [comment] 2015-10-14 18:04
+1. highly welcome feature that will help to execute whole "adb" power without waiting to implement on server side.

**Comment by moizjv** [comment] 2015-11-05 00:59
@dienstfuchs what adb command do you want to execute? we provide lot of wrappers around it. I don't think you should be using adb directly from appium instead appium should provide you all wrappers that user would need to automate application. @jlipps @Jonahss @imurchie  @scottdixon  what do you guys think?

**Comment by Jonahss** [comment] 2015-11-05 19:55
Look back to other issues. We have a strong precedent for *not* opening up arbitrary adb commands. But with a good argument of creating a feature for a specific command, we are happy to implement.

Also feel free to implement the command you are looking for and submit a pull request. But keep in mind cross-platform functionality (what would this command look like on iOS?)

**Comment by imurchie** [comment] 2015-11-05 22:16
See in particular #3218. Closing as duplicate of that.

**Closed by imurchie** 2015-11-05 22:16 UTC
Labels: NeedsTriage

**Comment by vipinAutomation** [comment] 2018-04-03 13:37
what is this { "/bin/sh", "-c"}
