### ISSUE TITLE
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'

### ISSUE THREAD

**Issue by yuanshirenasdas24525** [appium/appium#20014] opened 2024-04-18 11:13 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/appium/appium/assets/150315853/26079c06-0a76-4edc-a3f6-e3fe8d4ccd5c)

![image](https://github.com/appium/appium/assets/150315853/255ab4a7-4a41-4592-923c-0af287ee892c)

### Expected Behavior

![image](https://github.com/appium/appium/assets/150315853/3b0934b6-0289-4fc8-a0a3-da13dcdb1bf5)

### Minimal Reproducible Example

1

### Environment

- Operating system: windows11
- Appium server version (output of `appium --version`):2.5.3
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):v20.12.2
- `npm` version (output of `npm --version`):10.5.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment] 2024-04-18 11:22
Duplicate of https://github.com/appium/appium/issues/20008

**Closed by mykola-mokhnach** 2024-04-18 11:22 UTC
Labels: Bug, Needs Triage
