### ISSUE TITLE
Appium 1.5.0-beta16: getContext() returns null with Selendroid instead of "NATIVE_APP"

### ISSUE THREAD

**Issue by adholaria** [appium/appium#6301] opened 2016-03-17 21:16 UTC
## The problem

getContext() method returns the null value instead "NATIVE_APP"

## Environment

* Appium version (or git revision) that exhibits the issue: v1.5.0-beta16 (REV ab684c4cf06772451218f6ed2d524aeca82d4ca0)
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: Mac 
* Node.js version (unless using Appium.app|exe): node v0.12.8-rc.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: no

## Details
From AppiumDriver class:

@Override
	public String getContext() {
		String contextName = String.valueOf(execute(
				DriverCommand.GET_CURRENT_CONTEXT_HANDLE).getValue());
		if (contextName.equals("null")) {
			return null;
		}
		return contextName;
	}

## Code To Reproduce Issue [ Good To Have ]

driver.getContext();

**Comment by TikhomirovSergey** [comment] 2016-03-18 18:26
This is the duplicate of ##6234

**Closed** 2016-03-18 20:32 UTC
Labels: NeedsTriage
