### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure

### ISSUE THREAD

**Issue by amitrparmar** [appium/appium#13699] opened 2019-12-10 13:23 UTC
## The problem
This issue looks so similar but I would request to see details as mentioned below.

I have observed that this issue specifically occurs with Xcode 10.1 + Appium-beta 1.16.0-beta. 
I also wanted to describe that is not occur when I use released appium.  Obviously, I am not using released appium for specific reason.  I have an issue [[([https://github.com/appium/appium/issues/13582))] with released one so I turned to beta.

I am stuck with this thing, I spent lot of time but couldn't figure out exact solution for this. Someone please guide me on this.

I have carefully followed all the documentation which are required. Also followed all below threads of issues:

https://github.com/appium/appium/issues/9035
https://github.com/facebookarchive/WebDriverAgent/issues/753
https://github.com/appium/appium/issues/8062
https://github.com/appium/appium-xcuitest-driver/pull/407

## Environment
* appium - 1.16.0-beta.3
* npm - 6.13.1
* node - 13.2.0
* Java - openJDK '13'
* Xcode - 10.1
* MAC - macOS High Sierra
* platform - iPad (iOS v. 10.3.3) (Real Device)

Test executed from windows machine.

## Logs
https://gist.github.com/amitrparmar/5a2879a35bb7530291bea0c6bbcd26b6#file-appiumbeta_xcode10-1-log

## Code To Reproduce Issue [ Good To Have ]

Not specific, not able to install WDA, I guess

**Comment by mykola-mokhnach** [comment] 2019-12-10 13:43
I think the problem is iOS 10, because it uses Xcode9 SDK, which is not supported by Appium since version 1.15

**Comment by mykola-mokhnach** [comment] 2019-12-10 13:44
Also, it is impossible to interpret the log being pasted into the issue. Please attach the full server log as gist

**Comment by amitrparmar** [comment] 2019-12-10 13:50
Thanks @mykola-mokhnach for the information.

As per your suggestion, what appium I should have with this xcode configurations. 

I also need to run with iOS 11 as well. 

Please suggest the best set up version I can have. I also concerned for the pageiD issue which I mentioned in my issue description.

**Comment by amitrparmar** [comment] 2019-12-10 13:52
Sorry for the pasted log, I am at mobile right now. I will update it when I get on my desktop.

**Comment by amitrparmar** [comment] 2019-12-11 04:05
> I think the problem is iOS 10, because it uses Xcode9 SDK, which is not supported by Appium since version 1.15

I don't think so because if it is the case then it shouldn't be working with release appium, right?

**Comment by KazuCocoa** [comment] 2019-12-11 08:56
What about building it with Xcode 10.1 directly?
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

And what about the result of xcodebuild command like below you can find it in Appium's log if the above link works?
```
xcodebuild build-for-testing test-without-building -project /Users/kazu/GitHub/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/kazu/GitHub/ruby_lib_core/tmp -destination id=f4da227d7314251e8ed0081590cd813d03064efc IPHONEOS_DEPLOYMENT_TARGET=13.2 -xcconfig /var/folders/34/2222sh8n27d6rcp7jqlkw8km0000gn/T/20191111-17922-16ejeef.uicy/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
```

I could sign on Xcode 10.2 and 11 with `xcodeOrgId`, `xcodeSigningId` and `updatedWDABundleId`. (not a personal account though).
I have no real devices which can be handled by Xcode 10.1., so I could not check your combination.


You also can remove `/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent*` to clean your xcodebuild cache. It sometimes helps to clean build dependencies.

**Comment by amitrparmar** [comment] 2019-12-13 09:23
Hi @KazuCocoa , I'm trying your suggested steps and get back to you with details.

**Comment by blane1988** [comment] 2019-12-13 15:40
Any updates @amitrparmar? I'm also trying to get WebDriverAgent to run properly.

**Comment by amitrparmar** [comment] 2019-12-14 07:01
Hi @blane1988 , I messed up my mac. I am re seting all. I get back to you very soon after weekend. Thanks for your comments.

**Comment by mykola-mokhnach** [comment] 2019-12-17 09:55
> Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor. (in target 'WebDriverAgentRunner')

This is for sure a local problem with code signing. Unfortunately there is nothing we can do there from Appium side

**Comment by mykola-mokhnach** [comment] 2019-12-19 07:00
Unfortunately, there is nothing more to do here on Appium side.

Closed as not an issue

**Closed by mykola-mokhnach** 2019-12-19 07:00 UTC
Labels: NotABug

**Comment by amitrparmar** [comment] 2019-12-20 05:10
However, it has been closed, but someone please suggest the best appium version to use with Xcode 10.1.

Because I'm still facing the issue.

**Comment by amitrparmar** [comment] 2019-12-24 14:26
Hi @KazuCocoa , I have tried your suggested command and I got below output.

** TEST BUILD SUCCEEDED **

Testing started on 'Generic iOS Device'
2019-12-24 19:51:32.315 xcodebuild[15691:394455] [MT] IDETestOperationsObserverDebug: 0.045 elapsed -- Testing started completed.
2019-12-24 19:51:32.315 xcodebuild[15691:394455] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-12-24 19:51:32.315 xcodebuild[15691:394455] [MT] IDETestOperationsObserverDebug: 0.045 sec, +0.045 sec -- end
2019-12-24 19:51:32.315 xcodebuild[15691:394455] Error Domain=IDEFoundationErrorDomain Code=1 "Testing failed" UserInfo={NSLocalizedFailureReason=A build only device cannot be used to run this target., NSLocalizedDescription=Testing failed, NSUnderlyingError=0x7fef7b643330 {Error Domain=IDEFoundationErrorDomain Code=3 "A build only device cannot be used to run this target." UserInfo={NSLocalizedDescription=A build only device cannot be used to run this target., NSLocalizedRecoverySuggestion=Please select an available device or choose a simulated device as the destination.}}}
** TEST EXECUTE SUCCEEDED **

Could you please suggest further steps please.

**Comment by amitrparmar** [comment] 2019-12-24 14:30
> > Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor. (in target 'WebDriverAgentRunner')
> 
> This is for sure a local problem with code signing. Unfortunately there is nothing we can do there from Appium side

**Comment by KazuCocoa** [comment] 2019-12-24 14:53
Could you attach the full log as gist?

**Comment by amitrparmar** [comment] 2019-12-25 07:14
Hi @KazuCocoa , I have attached log here

https://gist.github.com/amitrparmar/83c2478a3571c50e07fccea59d15e6a0

**Comment by KazuCocoa** [comment] 2019-12-25 07:57
Thanks.
It looks building the WDA was succeeded, but the execution via xcodebuild failed since perhaps 'd8a8f24c27769d00627929f291b15eb015e9e8c4' was not available by the xcodebuild command.

> admin$ xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/admin/Library/Developer/Xcode/DerivedData id=d8a8f24c27769d00627929f291b15eb015e9e8c4 IPHONEOS_DEPLOYMENT_TARGET=10.3 -xcconfig /Desktop/IPA/sign.xcconfigGCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO


Could you make sure the device is connected?
Sometimes, you should launch simulator as _Please select an available device or choose a simulated device as the destination._, restart your host machine.
(You can find similar try on the web)

I haven't met the error, but it looks xcodebuild command the environment issue...

**Comment by amitrparmar** [comment] 2019-12-25 09:00
Hi @KazuCocoa , I have already tried which you suggest. But same error. I have a thought this is the issue which appium beta + xcode 10.1. 

Why I am saying this because if I install released appium on same environment, it works without this issue. I have to use beta appium because of pageID issue because it is fixed in beta. 

And not beta is troubling me with this. 

Really, this should be addressed but it is closed. 

What other options I have now?

**Comment by KazuCocoa** [comment] 2019-12-25 09:51
>  I install released appium on same environment, it works without this issue

What about Appium 1.16.0?

---

Could you try to install the WDA built by `xcodebuild build-for-testing` to your device using ios-deploy? (And what about launching it?)
Your failure was probably happening in `test-without-building`. So, I wondered you could install the app without xcodebuild. If so, we should clarify what xcodebuild process is the cause...

Project level's change in Appium 1.16.0 was dropping Xcode 9 support.
https://github.com/appium/WebDriverAgent/pull/227

If it can work with `xcodebuild build test` instead of `xcodebuild build-for-testing test-without-building`, you can also try `useSimpleBuildTest` capability.
