### ISSUE TITLE
Appium 1.7.2 unable to find element from element

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#10107] opened 2018-01-31 17:45 UTC
## The problem

Calling findElementFromElement unable to find an element (confirmed element does exist using driver.getPageSource() and also running same code on Appium 1.7.1 where the code works). 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: Mac High Sierra 
* Node.js version (unless using Appium.app|exe): 9.4.0
* Mobile platform/version under test: Various iOS 11 devices
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Details

Using the Java bindings, we are using `final WebElement el = new WebDriverWait(driver, Constants.ELEMENT_WAIT, Constants.POLLING_RATE).until(ExpectedConditions.presenceOfElementLocated(locator));` to get parent, then calling 
`el.findElement(locator);` to get child. This throws a NoSuchElementException.

What is strange is calling this as a single chain does work:
driver.findElement(locatorParent).findElement(locatorChild).click();

The only difference I can see is the WebDriverWait's ExpectedConditions is using findElements instead of findElement for finding the parent element. They both just return a single WebElement so i don't know why that would matter though. It returns the element out of the array as you will see below.

## Link to Appium logs

Using Appium 1.7.1 it works: https://gist.github.com/jamesvanhorn/6966201fe9c77d49af0faf79203c5af7

Using Appium 1.7.2 it fails: https://gist.github.com/jamesvanhorn/136bed77b942d88c6c327e0e3b709d13

App under test was identical, so this seems like a WDA page source issue? I have the new capability useJSONSource=false for reference. I have also seen other issues with Appium 1.7.2 not finding view elements that I have assigned an accessibility ID to in XCode. It almost seems like there is some sort of source compression (similar to how Android can get compress or uncompressed source) occurring on real devices (simulators this doesn't happen). Setting useJSONSource=true does not help either, as I get this error https://github.com/facebook/WebDriverAgent/issues/797

## Code To Reproduce Issue [ Good To Have ]
Doesn't happen with all findElementFromElement() calls, so difficult to give single code snippet to reproduce

**Comment by jamesvanhorn** [comment] 2018-01-31 17:47
For reference here is the page source snippet
```
<XCUIElementTypeCell type="XCUIElementTypeCell" name="cell_recentLocation_1" enabled="true" visible="true" x="0" y="237" width="375" height="60">
            <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="California" name="label_locationManagementRecentLocDetail" label="California" enabled="true" visible="true" x="17" y="267" width="306" height="20"/>
            <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="Palo Alto" name="label_locationManagementRecentLocName" label="Palo Alto" enabled="true" visible="true" x="17" y="247" width="306" height="20"/>
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="296" width="375" height="1"/>
            <XCUIElementTypeButton type="XCUIElementTypeButton" name="button_locationManagementRecent" label="favoriteGrey" enabled="true" visible="true" x="331" y="245" width="44" height="44"/>
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="8" y="308" width="367" height="1"/>
          </XCUIElementTypeCell>
```

**Comment by mykola-mokhnach** [comment] 2018-01-31 19:26
Duplicate of https://github.com/appium/appium/issues/10101

**Closed by mykola-mokhnach** 2018-01-31 19:26 UTC
