### ISSUE TITLE
UiAutomator2: Unable to reset app(TypeError: this.grantPermissions is not a function)

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#8281] opened 2017-04-19 09:34 UTC
## The problem
On trying to reset the app, 500 is returned and  TypeError: this.grantPermissions is not a function is thrown.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 beta
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac OS10.12.4
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 7.0
* Real device or emulator/simulator: Moto g4
* Appium CLI or Appium.app|exe: CLI

## Details
The app asks to grant permissions for Media and calendar at the launch of the app.
Also setting the Grantpermission to true desired capability gives the same error.

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/7c40fdbf-aac4-4e00-872e-189af4b4f2df/appium/app/reset {}
[debug] [MJSONWP] Calling AppiumDriver.reset() with args: ["7c40fdbf-aac4-4e00-872e-189af4b4f2df"]
[AndroidDriver] Running fast reset (stop and clear)
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb' with args: ["-P",5037,"-s","ZY223DDFLZ","shell","am","force-stop","com.eab.se"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb' with args: ["-P",5037,"-s","ZY223DDFLZ","shell","pm","clear","com.eab.se"]
[MJSONWP] Encountered internal error running command: TypeError: this.grantPermissions is not a function
    at AndroidUiautomator2Driver.callee$0$0$ (../../../lib/commands/general.js:203:14)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/7c40fdbf-aac4-4e00-872e-189af4b4f2df/appium/app/reset 500 1965 ms - 210 

## Code To Reproduce Issue [ Good To Have ]
Setup.getInstance().getWebDriver().resetApp();

**Comment by mykola-mokhnach** [comment] 2017-04-19 09:35
Duplicate of https://github.com/appium/appium/issues/8272

**Closed by mykola-mokhnach** 2017-04-19 09:35 UTC
