### ISSUE TITLE
iOS Switch Element attribute value never changes

### ISSUE THREAD

**Issue by fottin** [appium/appium#13978] opened 2020-02-21 14:46 UTC
## The problem

Attempting to toggle the element XCUIElementTypeSwitch. Toggling the switch works but the attribute ‘value’ never changes (always 0). Should be either a 0 or 1. When I use Appium desktop and tap the element , the value changes.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 1.15.1
* Node.js version (unless using Appium.app|exe): v10.16.3
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: iOS v12.4.5
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: 

## Details

Include link to Appium logs with 'showIOSLog' and 'showXcodeLog' set to true.

## Link to Appium logs

<script src="https://gist.github.com/fottin/ad02fef5e08481a98d5d63847820c345.js"></script>

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2020-02-21 14:49
Duplicate of https://github.com/appium/appium/issues/13691

Possible workaround: use Xcode 10 with iOS 12  and Xcode 11 with iOS 13

**Closed by mykola-mokhnach** 2020-02-21 14:49 UTC

**Comment by fottin** [comment] 2020-02-21 15:45
I don't understand why the Appium Desktop 1.15.1 is capable of providing the correct value, when the switch is toggled, for an app that was built with Xcode 11.3.1 and installed on a real iPhone with iOS 12.4.5.

**Comment by fottin** [comment] 2020-02-21 17:27
@mykola-mokhnach I don't understand why the Appium Desktop 1.15.1 is capable of providing the correct value, when the switch is toggled, for an app that was built with Xcode 11.3.1 and installed on a real iPhone with iOS 12.4.5.

**Comment by mykola-mokhnach** [comment] 2020-02-21 17:49
most likely because of some internal snapshotting mechanics are out of sync. This is merely a black box for us, so I cannot provide more details.
