### ISSUE TITLE
ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up (after installing and launching app) 

### ISSUE THREAD

**Issue by Ashwini12345** [appium/appium#10525] opened 2018-04-11 19:11 UTC
## The problem

Getting error as below when running test case,
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: MAC OS 10.13.4
* Node.js version (unless using Appium.app|exe): v8.9.1
* Mobile platform/version under test: IOS 11.2
* Real device or emulator/simulator: Simulator (Xcode 9.3)

## Details

Running into the above error with IOS 11.2 but the same is not seen with IOS 11.3. 
Any help would be much appreciated.

## Link to Appium logs

Gist link for Appium server logs: https://gist.github.com/Ashwini12345/4d73d07038191f192f8e52c09aa8e360

**Comment by imurchie** [comment] 2018-04-11 20:05
This is, unfortunately, a known problem at the moment. iOS versions below 11.3 with Xcode 9.3 do not work.

For now, use Xcode 9.2 (the easiest way is to have both installed, and set the `DEVELOPER_DIR` environment variable when running an iOS 11.2 test (e.g., `DEVELOPER_DIR=/Applications/Xcode-9.2.app mocha my-test.js`).

**Comment by mykola-mokhnach** [comment] 2018-04-11 20:28
Closed as duplicate of https://github.com/appium/appium/issues/10475

**Closed by mykola-mokhnach** 2018-04-11 20:28 UTC
Labels: ThirdParty
