### ISSUE TITLE
chromedriver exited unexpectedly when switching to webview on Android real device

### ISSUE THREAD

**Issue by NecoleYu** [appium/appium#5616] opened 2015-09-16 01:52 UTC
I tried with Appium 1.4.10 in Android 4.4.4  and 5.1 ,  then I updated chromedriver but it still fails to switch contexts 

```
info: --> GET /wd/hub/session/4f75b033-c30f-427d-aa6f-0984919b7390/contexts {}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: /Users/necoleyu/Library/Android/sdk/platform-tools/adb -s 4d003d1a4d774169 shell "cat /proc/net/unix"
info: [debug] WEBVIEW_19172 mapped to pid 19172
info: [debug] Getting process name for webview
info: [debug] executing cmd: /Users/necoleyu/Library/Android/sdk/platform-tools/adb -s 4d003d1a4d774169 shell "ps"
info: [debug] Parsed pid: 19172 pkg: com.eg.android.MyAppRC
info: [debug] from: u0_a70,19172,1927,865880,140156,ffffffff,00000000,S,com.eg.android.MyAppRC
info: [debug] returning process name: com.eg.android.MyAppRC
info: [debug] Available contexts:
info: [debug] ["WEBVIEW_com.eg.android.MyAppRC"]
info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.eg.android.MyAppRC
info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP","WEBVIEW_com.eg.android.MyAppRC"],"sessionId":"4f75b033-c30f-427d-aa6f-0984919b7390"}
info: <-- GET /wd/hub/session/4f75b033-c30f-427d-aa6f-0984919b7390/contexts 200 169.846 ms - 126 {"status":0,"value":["NATIVE_APP","WEBVIEW_com.eg.android.MyAppRC"],"sessionId":"4f75b033-c30f-427d-aa6f-0984919b7390"}
info: --> POST /wd/hub/session/4f75b033-c30f-427d-aa6f-0984919b7390/context {"name":"WEBVIEW_com.eg.android.MyAppRC"}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: /Users/necoleyu/Library/Android/sdk/platform-tools/adb -s 4d003d1a4d774169 shell "cat /proc/net/unix"
info: [debug] WEBVIEW_19172 mapped to pid 19172
info: [debug] Getting process name for webview
info: [debug] executing cmd: /Users/necoleyu/Library/Android/sdk/platform-tools/adb -s 4d003d1a4d774169 shell "ps"
info: [debug] Parsed pid: 19172 pkg: com.eg.android.MyAppRC
info: [debug] from: u0_a70,19172,1927,865880,140156,ffffffff,00000000,S,com.eg.android.MyAppRC
info: [debug] returning process name: com.eg.android.MyAppRC
info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.eg.android.MyAppRC
info: [debug] ["WEBVIEW_com.eg.android.MyAppRC"]
info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.eg.android.MyAppRC
info: [debug] Connecting to chrome-backed webview
info: Chromedriver: Set chromedriver binary as: /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
info: Chromedriver: Killing any old chromedrivers, running: ps -ef | grep /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver | grep -v grep |grep -e '--port=9515\(\s.*\)\?$' | awk '{ print $2 }' | xargs kill -15
info: Chromedriver: Successfully cleaned up old chromedrivers
info: Chromedriver: Spawning chromedriver with: /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9515
info: Chromedriver: [STDOUT] Starting ChromeDriver 2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f) on port 9515
Only local connections are allowed.
info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
info: JSONWP Proxy: Got response with status 200: {"sessionId":"","status":0,"value":{"build":{"version":"alpha"},"os":{"arch":"x86_64","name":"Mac OS X","version":"10.10.3"}}}
info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.eg.android.MyAppRC","androidUseRunningApp":true,"androidDeviceSerial":"4d003d1a4d774169"},"loggingPrefs":{"performance":"ALL"}}}
info: JSONWP Proxy: Got response with status 200: {"sessionId":"3ce09e81fdc10e3047099cec625a4733","status":13,"value":{"message":"unknown error: Device 4d003d1a4d774169 is not online\n  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d...
info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.eg.android.MyAppRC","androidUseRunningApp":true,"androidDeviceSerial":"4d003d1a4d774169"},"loggingPrefs":{"performance":"ALL"}}}
info: JSONWP Proxy: Got response with status 200: {"sessionId":"5ab23b9d57130075fc3f30467b4ee5c9","status":13,"value":{"message":"unknown error: Device 4d003d1a4d774169 is not online\n  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d...
info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.eg.android.MyAppRC","androidUseRunningApp":true,"androidDeviceSerial":"4d003d1a4d774169"},"loggingPrefs":{"performance":"ALL"}}}
info: JSONWP Proxy: Got response with status 200: {"sessionId":"217db5306114ee00e76bc83e566c8f40","status":13,"value":{"message":"unknown error: Device 4d003d1a4d774169 is not online\n  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d...
info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.eg.android.MyAppRC","androidUseRunningApp":true,"androidDeviceSerial":"4d003d1a4d774169"},"loggingPrefs":{"performance":"ALL"}}}
info: JSONWP Proxy: Got response with status 200: {"sessionId":"14a4051e60e1a5bed2636495d3bcc4a2","status":13,"value":{"message":"unknown error: Device 4d003d1a4d774169 is not online\n  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d...
error: Chromedriver: Chromedriver exited unexpectedly with code null, signal SIGTERM
warn: Chromedriver for context WEBVIEW_com.eg.android.MyAppRC stopped unexpectedly
warn: Chromedriver quit unexpectedly, but it wasn't the active context, ignoring
error: Chromedriver: Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device 4d003d1a4d774169 is not online
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.3 x86_64))
    at JWProxy.command$ (lib/proxy.js:149:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:254:14)
    at GeneratorFunctionPrototype.runBound (domain.js:267:12)
    at run (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at process._tickDomainCallback (node.js:381:11)
 { [Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device 4d003d1a4d774169 is not online
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.3 x86_64))]
  status: 13,
  value: { message: 'unknown error: Device 4d003d1a4d774169 is not online\n  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.3 x86_64)' },
  httpCode: 200 }
```

**Comment by piotrekkmt** [comment] 2015-09-24 15:42
Guys, any update on that? It's quite possibly caused by a server-side error but it shouldn't just die on us like that. Having the same issue. The test just dies randomly.

**Comment by nabeel-ibrahim** [comment] 2015-10-07 15:18
I am getting the exact same error, I am running appium 1.4.13 on a physical android device running Android 5.1
`info: <-- GET /wd/hub/session/32d5417c-212d-49d5-837e-a68d9854db32/contexts 200 157.953 ms - 126 {"status":0,"value":["NATIVE_APP","WEBVIEW_com.fivemobile.thescore.debug"],"sessionId":"32d5417c-212d-49d5-837e-a68d9854db32"}
info: --> POST /wd/hub/session/32d5417c-212d-49d5-837e-a68d9854db32/context {"name":"WEBVIEW_com.fivemobile.thescore.debug"}
info: Chromedriver: Changed state to 'starting'
info: Chromedriver: Set chromedriver binary as: /Users/nibrahim/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
info: Chromedriver: Killing any old chromedrivers, running: ps -ef | grep /Users/nibrahim/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver | grep -v grep |grep -e '--port=9515\(\s.*\)\?$' | awk '{ print $2 }' | xargs kill -15
info: Chromedriver: Successfully cleaned up old chromedrivers
info: Chromedriver: Spawning chromedriver with: /Users/nibrahim/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9515
info: Chromedriver: [STDOUT] Starting ChromeDriver 2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281) on port 9515
Only local connections are allowed.
info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
info: JSONWP Proxy: Got response with status 200: {"sessionId":"","status":0,"value":{"build":{"version":"alpha"},"os":{"arch":"x86_64","name":"Mac OS X","version":"10.10.5"}}}
info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.fivemobile.thescore.debug","androidUseRunningApp":true,"androidDeviceSerial":"093e700f006d0cc8"}}}
info: JSONWP Proxy: Got response with status 200: {"sessionId":"704ac47337934a65d9231f0d8d5bf8a7","status":13,"value":{"message":"unknown error: Device 093e700f006d0cc8 is not online\n  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308eb...
info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.fivemobile.thescore.debug","androidUseRunningApp":true,"androidDeviceSerial":"093e700f006d0cc8"}}}
info: JSONWP Proxy: Got response with status 200: {"sessionId":"3fa66addb7224a5e10ef7683f83ace81","status":13,"value":{"message":"unknown error: Device 093e700f006d0cc8 is not online\n  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308eb...
info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.fivemobile.thescore.debug","androidUseRunningApp":true,"androidDeviceSerial":"093e700f006d0cc8"}}}
info: JSONWP Proxy: Got response with status 200: {"sessionId":"ccf5f9a8385520af23d051ec3d4cc486","status":13,"value":{"message":"unknown error: Device 093e700f006d0cc8 is not online\n  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308eb...
info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.fivemobile.thescore.debug","androidUseRunningApp":true,"androidDeviceSerial":"093e700f006d0cc8"}}}
info: JSONWP Proxy: Got response with status 200: {"sessionId":"47a2c610e4df651ce2f71cc82d0abaec","status":13,"value":{"message":"unknown error: Device 093e700f006d0cc8 is not online\n  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308eb...
error: Chromedriver: Chromedriver exited unexpectedly with code null, signal SIGTERM
info: Chromedriver: Changed state to 'stopped'
warn: Chromedriver for context WEBVIEW_com.fivemobile.thescore.debug stopped unexpectedly
warn: Chromedriver quit unexpectedly, but it wasn't the active context, ignoring
error: Chromedriver: Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device 093e700f006d0cc8 is not online
  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.10.5 x86_64))
    at JWProxy.command$ (lib/proxy.js:149:15)
    at tryCatch (/Users/nibrahim/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/nibrahim/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/nibrahim/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/nibrahim/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:250:14)
    at GeneratorFunctionPrototype.runBound (domain.js:263:12)
    at run (/Users/nibrahim/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /Users/nibrahim/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at doNTCallback0 (node.js:408:9)
    at process._tickDomainCallback (node.js:378:13)
 { [Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device 093e700f006d0cc8 is not online
  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.10.5 x86_64))]
  status: 13,
  value: { message: 'unknown error: Device 093e700f006d0cc8 is not online\n  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.10.5 x86_64)' },
  httpCode: 200 }
info: Shutting down appium session
info: <-- POST /wd/hub/session/32d5417c-212d-49d5-837e-a68d9854db32/context - - ms - - 
info: --> POST /wd/hub/session/32d5417c-212d-49d5-837e-a68d9854db32/context {"name":"WEBVIEW_com.fivemobile.thescore.debug"}
info: <-- POST /wd/hub/session/32d5417c-212d-49d5-837e-a68d9854db32/context 404 3.323 ms - 40 
info: --> GET /wd/hub/session/32d5417c-212d-49d5-837e-a68d9854db32/screenshot {}
C5277(com.score.app.AndroidTests.ScoreEnglandSoccer_27): run 1 failed
Restarting app
info: <-- GET /wd/hub/session/32d5417c-212d-49d5-837e-a68d9854db32/screenshot 404 4.938 ms - 40 
info: --> POST /wd/hub/session/32d5417c-212d-49d5-837e-a68d9854db32/appium/app/close {}
info: <-- POST /wd/hub/session/32d5417c-212d-49d5-837e-a68d9854db32/appium/app/close 404 3.185 ms - 40 

org.openqa.selenium.remote.SessionNotFoundException: 
Command duration or timeout: 6 milliseconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'Nabil-MacBook-Pro.local', ip: '192.168.56.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_60'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{app=/Users/nibrahim/IdeaProjects/QA_Automation/Android/theScoreApp-google-debug.apk, appPackage=com.fivemobile.thescore.debug, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=093e700f006d0cc8, platform=LINUX, desired={app=/Users/nibrahim/IdeaProjects/QA_Automation/Android/theScoreApp-google-debug.apk, appPackage=com.fivemobile.thescore.debug, platformVersion=5.1.1, udid=093e700f006d0cc8, platformName=Android, deviceName=google}, platformVersion=5.1.1, webStorageEnabled=false, locationContextEnabled=false, browserName=Android, takesScreenshot=true, javascriptEnabled=true, udid=093e700f006d0cc8, platformName=Android}]
Session ID: 32d5417c-212d-49d5-837e-a68d9854db32
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:164)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:189)
	at io.appium.java_client.AppiumDriver.closeApp(AppiumDriver.java:245)
	at com.Rules.Retry$1.evaluate(Retry.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
`

**Comment by shermanericSF** [comment] 2015-10-14 04:55
Here's my gist: https://gist.github.com/shermanericSF/0142244cf93b39103c6d
Genymotion:  Android 5.0 OS Nexus 7
Appium 1.4.13

**Comment by shermanericSF** [comment] 2015-10-15 20:10
This seems to happen with standalone versions 2.13-2.19 as well as the stock chromedriver in appium 1.4.13.

Here are the ways I have consistently reproduced this:
1.  Navigate to a webview
2.  available_contexts   //I see the WEBVIEW one
3.  set_context  WEBVIEW.*.whatever     //this is fine
4.  If I later go and set the context back to NATIVE, then do the set_context WEBVIEW.*.whatever again - it fails with the gist above.

Workaround (so far - still experimenting):
If I restart the chromedriver process before re-initiating a set_context (see step 4) things seem to work.

It seems like chromedriver/appium is holding on to the previous context somehow.

Hope this helps!
Let me know if I can provide any more information!
Eric

**Comment by a-padinha** [comment] 2015-10-27 11:11
Hello everybody, any updates about this ? 
I'm having the same issue.

I can Get Contexts and the output is native and webview , I can switch to native but I can't switch to webview. And every time I switch to native after that I try to get the current context and doesn't show anything, before switching I try to get the current context and nothing appears.

**Comment by shermanericSF** [comment] 2015-10-27 15:36
Hey there:
Chromedriver 2.20 recently released seemed to fix my issues.
https://sites.google.com/a/chromium.org/chromedriver/downloads

For appium, remember you have to add the chromedriverExecutable capability accordingly. I don't think 1.4.13 has the aforementioned chromedriver version 

Good luck!

**Comment by a-padinha** [comment] 2015-10-27 16:48
Has I'm using appium 1.4.13 installed with npm, I also installed the npm appium-chromedriver and it installs appium-chromedriver@2.3.8. Nothing changed I still get the same error.
I'm not sure if it's this that you mean.
How did chromedriver 2.20 fixed your issues? Using Appium?

**Comment by shermanericSF** [comment] 2015-10-27 22:08
1.  In appium I add this to my desired capabilities   (i'm in ruby
using the appium.txt file)

[caps]
...
*chromedriverExecutable = "/usr/local/bin/chromedriver"*
...

2. I download 2.20 from
https://sites.google.com/a/chromium.org/chromedriver/downloads

3. Then I move the above chromedriver to /usr/local/bin

4. Then I change permissions: chmod 7555 /usr/local/bin/chromedriver

5.  Then I check the version.  Here's my prompt

15:04 $ chromedriver --version

ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b)



Then I run appium as normal without problem.

The chromedriverExecutable allows you to specify your own chromedriver
executable thus bypassing the appium-chromedriver.


Hope this helps!

**Comment by shermanericSF** [comment] 2015-10-27 22:08
1.  In appium I add this to my desired capabilities   (i'm in ruby using the appium.txt file)
[caps]
...
chromedriverExecutable = "/usr/local/bin/chromedriver"
...
2. I download 2.20 from https://sites.google.com/a/chromium.org/chromedriver/downloads

3. Then I move the above chromedriver to /usr/local/bin

4. Then I change permissions: chmod 7555 /usr/local/bin/chromedriver

5.  Then I check the version.  Here's my prompt

15:04 $ chromedriver --version

ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b)



Then I run appium as normal without problem.
The chromedriverExecutable allows you to specify your own chromedriver executable thus bypassing the appium-chromedriver.

Hope this helps!

**Comment by harigovindov** [comment] 2015-11-05 09:08
I am Not sure about this , I too had this issue , But after closing Chrome://inspector before running test solved this issue for me ! .

**Comment by mi2pankaj** [comment] 2016-01-07 07:30
Thanks a lot shermanericSF:
This has actually fixed the issue:
chromedriverExecutable = "/usr/local/bin/chromedriver"

**Comment by mi2pankaj** [comment] 2016-01-11 06:41
Hello everyone!! I could get a fix by monitoring chromedriver all the time during test execution, chromedriver becomes unresponsive while switching back to webview from natiove_app, I developed a small piece of code available at https://github.com/mi2pankaj/chromeDriverHandler, it has solved my all problems, just add this jar chromedriverHandler.jar  to your project and use ChromedriverHandler.chromeDriverHandlerThread().start(); in your @beforeclass / @beforetest and ChromedriverHandler.chromeDriverHandlerThread().stop(); in your @afterclass / @aftertest.

**Comment by veeru273** [comment] 2016-03-23 06:30
@mi2pankaj  How do i add chromedriverExecutable path while running my scripts in MAC ?? I'm using appium command line version

**Comment by mi2pankaj** [comment] 2016-03-23 06:53
You need to add capability to driver like:
capabilities.setCapability("chromedriverExecutable", "/tpt/chromedriver");

**Comment by veeru273** [comment] 2016-03-23 07:14
I have added capability and ran my script, in the appium log i'm getting this error

```
[Chromedriver] Successfully cleaned up old chromedrivers
[Chromedriver] Spawning chromedriver with: /usr/local/Cellar/chromedriver --url-base=wd/hub --port=9515 --adb-port=5037
[MJSONWP] Encountered internal error running command: Error: Can't stop process; it's not currently running
    at SubProcess.stop$ (lib/teen_process.js:211:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)``
```

**Comment by JagatheswaranSelvakumar** [comment] 2016-07-13 06:08
I am also facing this issue.Please help me any1

**Comment by vanimamidi** [comment] 2016-08-01 12:53
Try replacing the existing chrome driver

Download chrome driver from the link https://sites.google.com/a/chromium.org/chromedriver/downloads, and place it in the appium folder: ..\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win
It worked for me.

**Comment by tusharaina92** [comment] 2017-05-15 08:30
I am also facing the same issue when trying to navigate from native to WEBVIEW in my Android app.
The steps given by @shermanericSF are identical to one i am doing in my test case 
1. Navigate to a webview
2. set_context WEBVIEW.*.whatever //this is fine
3. If I later go and set the context back to NATIVE, then do the set_context WEBVIEW.*.whatever again - it fails with the gist above.

I am using the latest version of appium 1.6.4 which have 2.28 chromedriver associated with it.
I have also downloaded the latest version of Chromedriver 2.29 and added the same to /usr/local/bin.
But still the issue is coming and not able to switch between them.
Please anyone help?

**Comment by tusharaina92** [comment] 2017-06-01 04:21
Hey this problem seems to be solved by setting the capabilities of "recreateChromeDriverSessions" to true as the it will create Chrome driver session every time we switch among from webview. By default, it is false. You can write:
capabilities.setCapability("recreateChromeDriverSessions", true);

**Closed** 2017-07-20 18:13 UTC
Labels: Android, Real Devices

**Comment by shubhamj-cuelogic** [comment] 2017-12-15 10:57
getting same error. I have tried every option suggested here like: 

- adding new chromedriver in node_module folder
- setting cap as capabilities.setCapability("recreateChromeDriverSessions", true);

anywork around will be helpful

**Comment by THEKiINGMaker** [comment] 2018-01-18 10:43
Hi,
 I got this problem using hybrid app when i try to switch the contaxt,
The log detail are below,

error: Chromedriver: Error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED
>     at JWProxy.proxy$ (lib/proxy.js:109:13)
>     at tryCatch (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:136:37)
>     at bound (domain.js:284:14)
>     at GeneratorFunctionPrototype.runBound (domain.js:297:12)
>     at run (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:89:39)
>     at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:100:28
>     at flush (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\$.microtask.js:17:13)
>     at process._tickDomainCallback (node.js:381:11)
>  [Error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED]
