### ISSUE TITLE
Can't Switch to new Tab in Chrome 76 on Android device

### ISSUE THREAD

**Issue by ishanm120** [appium/appium#13034] opened 2019-08-06 08:47 UTC
I am using Chrome browser 76 on Android Mobile.
**switchTo().window(newWindow)** is not working.

Chromedriver used: 76.0.3809.68
Chrome Browser: 76
Appium version: v1.14.0

**Appium Logs:**

[W3C (8babf53f)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/8babf53f-b7f4-42fd-9282-c9b16d357b40/window' to command name 'setWindow'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/8babf53f-b7f4-42fd-9282-c9b16d357b40/window] to [POST http://127.0.0.1:8000/wd/hub/session/7976379caff22084f4083630b04a1a03/window] with body: {"handle":"CDwindow-1"}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"7976379caff22084f4083630b04a1a03","status":61,"value":{"message":"invalid argument: 'name' must be a string\n  (Session info: chrome=76.0.3809.89)\n  (Driver info: chromedriver=76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}),platform=Mac OS X 10.14.4 x86_64)"}}
[WD Proxy] Replacing sessionId 7976379caff22084f4083630b04a1a03 with 8babf53f-b7f4-42fd-9282-c9b16d357b40
[HTTP] <-- POST /wd/hub/session/8babf53f-b7f4-42fd-9282-c9b16d357b40/window 200 4 ms - 317
[HTTP] 
[HTTP] --> GET /wd/hub/session/8babf53f-b7f4-42fd-9282-c9b16d357b40/url
[HTTP] {}
[W3C (8babf53f)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/8babf53f-b7f4-42fd-9282-c9b16d357b40/url' to command name 'getUrl'
[debug] [WD Proxy] Proxying [GET /wd/hub/session/8babf53f-b7f4-42fd-9282-c9b16d357b40/url] to [GET http://127.0.0.1:8000/wd/hub/session/7976379caff22084f4083630b04a1a03/url] with body: {}
[debug] [WD Proxy] Got response with status 200: "{\"sessionId\":\"7976379caff22084f4083630b04a1a03\",\"status\":0,\"value\":\"https://m-qa3.sephora.com/basket\"}"
[WD Proxy] Replacing sessionId 7976379caff22084f4083630b04a1a03 with 8babf53f-b7f4-42fd-9282-c9b16d357b40
[HTTP] <-- GET /wd/hub/session/8babf53f-b7f4-42fd-9282-c9b16d357b40/url 200 53 ms - 106
[HTTP]

**Comment by mykola-mokhnach** [comment] 2019-08-06 10:13
Duplicate of https://github.com/appium/appium/issues/12989

**Closed by mykola-mokhnach** 2019-08-06 10:13 UTC
