### ISSUE TITLE
Appium, iOS tablet socket hang up (Resource temporarily unavailable Operation not permitted)

### ISSUE THREAD

**Issue by laurenspp** [appium/appium#7733] opened 2017-01-23 13:08 UTC
## The problem

So when I run tests on iPhone or android tablets/phones the tests will run perfectly but when I run on iOS tablet and press a certain button the driver crashes. It is always on that specific button and it takes a bit of time to load all the assets and go to the next screen. I added the logs in the details

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS X 10.12.2 Sierra
* Node.js version (unless using Appium.app|exe): v7.4.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real device iPad tablet
* Appium CLI or Appium.app|exe:

## Details

So I press a certain button to open the menu and then Appium crashes first it says:
[debug] [iProxy] recv failed: Resource temporarily unavailable
[debug] [iProxy] recv failed: Operation not permitted

Than the socket hangs up. Even when I tap on the button manually the app crashes. This is maybe important to troubleshoot. 

## Link to Appium logs

[HTTP] <-- POST /wd/hub/session/215615ef-2c83-44f5-9c01-4a17e1c70c86/appium/app/launch 200 36711 ms - 76 
[debug] [iProxy] recv failed: Resource temporarily unavailable
[debug] [iProxy] recv failed: Operation not permitted
[debug] [WebDriverAgent] Device: Jan 23 13:57:55 MOB023 XCTRunner[1680] <Warning>: Received memory warning.
[debug] [WebDriverAgent] Device: Jan 23 13:57:58 MOB023 XCTRunner[1680] <Error>: LaunchServices: disconnect event received for service com.apple.lsd.mapdb
[debug] [XCUITest] Log file for xcodebuild test: /Users/testing/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/4C33DDFE-A635-4EAC-BD6C-80B47C2FE5B2/Session-WebDriverAgentRunner-2017-01-23_135806-3vXr64.log
[Xcode] 2017-01-23 13:58:10.955 xcodebuild[7496:122973] Error Domain=com.apple.dtdevicekit Code=-402653170 "An error was encountered while enabling development on this device." UserInfo={NSLocalizedFailureReason=Please try rebooting and reconnecting the device. (0xE800000E), com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x000000011227837b DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x0000000112278ab9 DTDK_AMDErrorToNSError + 791
	2   DTDeviceKitBase                     0x00000001122b89df __90-[DTDKRemoteDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 158
	3   DVTFoundation                       0x000000010b50a989 DVTInvokeWithStrongOwnership + 75
	4   DTDeviceKitBase                     0x00000001122b8725 -[DTDKRemoteDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1181
	5   IDEiOSSupportCore                   0x0000000111b7fe1f __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.336 + 4597
	6   DVTFoundation                       0x000000010b62ecb7 __DVTDispatchAsync_block_invoke + 827
	7   libdispatch.dylib                   0x00007fff8e792ef7 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff8e78a0b8 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff8e7a0ae5 _dispatch_queue_serial_drain + 896
	10  libdispatch.dylib                   0x00007fff8e792cd9 _dispatch_queue_invoke + 1046
	11  libdispatch.dylib                   0x00007fff8e78be70 _dispatch_root_queue_drain + 476
	12  libdispatch.dylib                   0x00007fff8e78bc47 _dispatch_worker_thread3 + 99
	13  libsystem_pthread.dylib             0x00007fff8e9d7712 _pthread_wqthread + 1299
	14  libsystem_pthread.dylib             0x00007fff8e9d71ed start_wqthread + 13
), NSLocalizedRecoverySuggestion=Please try rebooting and reconnecting the device. (0xE800000E), NSLocalizedDescription=An error was encountered while enabling development on this device.}

[Xcode] 2017-01-23 13:58:10.955 xcodebuild[7496:122973] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

[Xcode] 
Testing failed:

[Xcode] 	Run test suite UITestingUITests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
Failing tests:
	-[UITestingUITests testRunner]
** TEST FAILED **

[Xcode] 2017-01-23 13:56:30.204 XCTRunner[1680:72065] Running tests...
2017-01-23 13:56:31.917 XCTRunner[1680:72065] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2017-01-23 13:56:33.523
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-01-23 13:56:33.527
Test Suite 'UITestingUITests' started at 2017-01-23 13:56:33.532
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.01s     Start Test at 2017-01-23 13:56:33.547
    t =     0.03s     Set Up
2017-01-23 13:56:33.643 XCTRunner[1680:72065] Built at Jan 18 2017 14:32:28
2017-01-23 13:56:33.749 XCTRunner[1680:72065] ServerURLHere->http://10.154.100.52:8100<-ServerURLHere
2017-01-23 13:56:33.752 XCTRunner[1680:72065] Listening on USB
    t =     5.30s     Launch com.wanagogo.wngg
    t =     5.88s         Waiting for accessibility to load
    t =     7.15s         Wait for app to idle
    t =     8.18s     Find the Application "com.wanagogo.wngg" 0x14e16e40
    t =     8.18s         Snapshot accessibility hierarchy for com.wanagogo.wngg
    t =     8.51s     Find the Application "com.wanagogo.wngg" 0x14e16e40
    t =     8.51s         Use cached accessibility hierarchy for com.wanagogo.wngg
    t =     8.56s     Find the Application "com.wanagogo.wngg" 0x14e16e40
    t =     8.56s         Use cached accessibility hierarchy for com.wanagogo.wngg
    t =     8.66s     Find the Application "com.wanagogo.wngg" 0x14e16e40
    t =     8.67s         Snapshot accessibility hierarchy for com.wanagogo.wngg
    t =     8.99s     Find the Application "com.wanagogo.wngg" 0x14e16e40
    t =     8.99s         Use cached accessibility hierarchy for com.wanagogo.wngg
    t =     9.04s     Set device orientation to Portrait
    t =     9.54s     Find the Application "com.wanagogo.wngg" 0x14e16e40
    t =     9.55s         Snapshot accessibility hierarchy for com.wanagogo.wngg
2017-01-23 13:57:55.368 XCTRunner[1680:72065] Received memory warning.

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Shutting down because we waited 120 seconds for a command
[debug] [JSONWP Proxy] Proxying [DELETE /session/215615ef-2c83-44f5-9c01-4a17e1c70c86] to [DELETE http://localhost:8100/session/7E0A40FF-529F-49C3-B90D-05B320AB097C] with no body
[Appium] Closing session, cause was 'New Command Timeout of 120 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session 215615ef-2c83-44f5-9c01-4a17e1c70c86 from our master session list
[debug] [iProxy] Error connecting to device!
Unhandled rejection ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:126:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

## Code To Reproduce Issue [ Good To Have ]
It' just a click event...

**Comment by jlipps** [comment] 2017-01-23 18:42
If you do this on your own (without Appium), does the app also crash?

Anyway, this is symptomatic of a problem with either your app or WDA, not Appium itself.

**Comment by laurenspp** [comment] 2017-01-24 06:56
@jlipps Thanks for your answer can you maybe clarify what WDA is?

**Comment by jlipps** [comment] 2017-01-24 18:32
Interesting, so you're saying a manual click will crash the app, but only if webdriveragent is running on the device? That definitely sounds like either a webdriveragent bug or an Apple XCTest bug. I'm going to close this on the Appium side, but you should raise an issue at https://github.com/facebook/WebdriverAgent in case it's a problem @marekcirkos knows about already. Sorry we can't be of more help.

**Closed by jlipps** 2017-01-24 18:32 UTC
Labels: NeedsTriage

**Comment by marekcirkos** [comment] 2017-01-24 23:58
@laurenspp To me it sounds like app that is spin locked and keeps allocating memory. It it definitely possible that it happens only in "Testing" mode because TestManager (process controlled by Apple) directly interacts with application code and gathers some information. I personally have seen that problem once and it was caused by clashing property names used by apps and added by Apples categories. In mine case it was 'viewDelegate'. Check it out, you might be lucky and have same problem.

**Comment by laurenspp** [comment] 2017-01-25 07:02
@marekcirkos Hi Marek thanks for the response. Maybe it is good to know that the app is causing trouble on every platform (android &iOS). Sometimes simple things like tapping doesn't work and, for example the click method doesn't work on tablet. I'm pretty sure that this is not due appium because I used it before and on other apps it works really well but on this app the most simple things like hiding a keyboard doesn't work. Is it because it is an hybride app? 

I have a whole list of things that doesn't work only on this app....

**Comment by marekcirkos** [comment] 2017-01-25 09:39
@laurenspp I can't really help you without knowing the app and investigating issues. :/

**Comment by laurenspp** [comment] 2017-01-25 10:11
@marekcirkos Oké no problem. Thanks everybody anyway for the help!
