### ISSUE TITLE
driver.lock(seconds) results in method not implemented error in case of IOS

### ISSUE THREAD

**Issue by gkvappium** [appium/appium#9180] opened 2017-09-07 06:03 UTC
## The problem
driver.lock(seconds) results in method not implemented error in case of IOS. I have automated scenario's wherein I have to access the app when the screen is locked for the music player app. I have achieved this for android. But in case of IOS I get the method not implemented error

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.6 beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:IOS 10.2
* Real device or emulator/simulator:Iphone 5s real device
* Appium CLI or Appium.app|exe:

I use appium-python client.

Code to reproduce the issue is pretty straight forward.

self.driver.lock(30)

Error message: Method has not been implemented.

If this is not implemented, what is the alternate way to lock the screen and unlock in case of IOS?

@mykola-mokhnach could you please have a look?

**Comment by mykola-mokhnach** [comment] 2017-09-07 06:21
Apple's XCTest does not provide any APIs to lock/unlock device screen.

Closed as by design.

**Closed by mykola-mokhnach** 2017-09-07 06:21 UTC

**Comment by gkvappium** [comment] 2017-09-07 06:25
Thanks for the confirmation @mykola-mokhnach
