### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/2018018-10989-mszb1e.83yx'

### ISSUE THREAD

**Issue by Dipanjan1** [appium/appium#10020] opened 2018-01-18 02:07 UTC
I am trying to install Appium on Mac using the following steps:

I followed the setup process

brew install node              # get node.js
npm install -g appium      # get appium
npm install wd                  # get appium client
appium &                          # start appium

I am blocked at the Appium install process due to the following error. 

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/2018018-10989-mszb1e.83yx'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@3.1.4 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@3.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

The log is provided below.

```
34152 /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
34153 silly lifecycle appium-chromedriver@3.1.4~install: Args: [ '-c', 'node install-npm.js' ]
34154 silly lifecycle appium-chromedriver@3.1.4~install: Returned: code: 1  signal: null
34155 info lifecycle appium-chromedriver@3.1.4~install: Failed to exec install script
34156 verbose unlock done using /Users/u205188/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
34157 verbose stack Error: appium-chromedriver@3.1.4 install: `node install-npm.js`
34157 verbose stack Exit status 1
34157 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
34157 verbose stack     at emitTwo (events.js:126:13)
34157 verbose stack     at EventEmitter.emit (events.js:214:7)
34157 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
34157 verbose stack     at emitTwo (events.js:126:13)
34157 verbose stack     at ChildProcess.emit (events.js:214:7)
34157 verbose stack     at maybeClose (internal/child_process.js:925:16)
34157 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
34158 verbose pkgid appium-chromedriver@3.1.4
34159 verbose cwd /Users/u205188
34160 verbose Darwin 16.7.0
34161 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
34162 verbose node v8.9.4
34163 verbose npm  v5.6.0
34164 error code ELIFECYCLE
34165 error errno 1
34166 error appium-chromedriver@3.1.4 install: `node install-npm.js`
34166 error Exit status 1
34167 error Failed at the appium-chromedriver@3.1.4 install script.
34167 error This is probably not a problem with npm. There is likely additional logging output above.
34168 verbose exit [ 1, true ]

```

How can I resolve this issue. Any help is appreciated

**Comment by mykola-mokhnach** [comment] 2018-01-18 06:52
> Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/2018018-10989-mszb1e.83yx'

Make sure your user has write permissions under /usr/local/lib. Closed as non Appium-related issue

**Closed by mykola-mokhnach** 2018-01-18 06:52 UTC

**Comment by Dipanjan1** [comment] 2018-01-20 23:14
Thanks heaps @mykola-mokhnach.

**Comment by rkrisztian** [comment] 2018-04-06 10:27
This worked:  `sudo npm install -g appium --unsafe-perm=true --allow-root` (from #10293).

**Comment by Enelar** [comment] 2018-08-13 08:34
This is not funny, keep getting that issue, July 2018

**Comment by dabat** [comment] 2018-08-13 19:58
same issue for me trying to install 1.8.1

@rkrisztian recommendation worked for me as well.

macOS 10.13.6
Node 8.11.3
npm 6.2.0

/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js

> appium-chromedriver@4.0.0 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

(node:39841) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/2018713-39841-1hiy87t.ipqe'
(node:39841) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:39841) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info Chromedriver Install Installing Chromedriver version '2.38' for platform 'mac' and architecture '64'
info Chromedriver Install Opening temp file to write chromedriver_mac64 to...
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/2018713-39841-2pu8cj.wpzfi'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@4.0.0 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by imurchie** [comment] 2018-08-14 14:41
@dabat Sorry this is still happening. I can't reproduce, so I need to ask a few more questions:

1. Can you try installing with the command `npm install -g appium --trace-warnings`?
2. Can you try installing the latest Appium, with `npm install -g appium@beta --no-shrinkwrap`?

**Comment by dabat** [comment] 2018-08-14 19:38
@imurchie i tried both of these for you with the same results.
again `sudo npm install -g appium --unsafe-perm=true --allow-root` worked though.

sudo npm install -g appium --trace-warnings
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js

> appium-chromedriver@4.0.0 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

(node:4910) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/2018714-4910-1em8axq.099g'
(node:4910) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4910) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info Chromedriver Install Installing Chromedriver version '2.38' for platform 'mac' and architecture '64'
info Chromedriver Install Opening temp file to write chromedriver_mac64 to...
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/2018714-4910-ov5hi4.k45zc'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@4.0.0 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

sudo npm install -g appium@beta --no-shrinkwrap
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js

> appium-chromedriver@4.4.0 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

(node:4931) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/2018714-4931-wbb273.sjsj'
(node:4931) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4931) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[14:34:50] [Chromedriver Install] Installing Chromedriver version '2.41' for platform 'mac' and architecture '64'
[14:34:50] [Chromedriver Install] Opening temp file to write 'chromedriver_mac64' to...
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/2018714-4931-g920uk.04gpq'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@4.4.0 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@4.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by butomo1989** [comment] 2018-10-10 12:28
@imurchie I got the same error if I update version of nodejs to version 8.x (8.12.0) and Ubuntu 18.04 / bionic for [docker-appium project](https://github.com/appium/appium-docker-android)

**Comment by Pedro1105** [comment] 2018-10-16 17:08
Gostaria de saber como faço para configurar meu projeto para ele rodar tanto ios como android? alguém poderia me ajudar? Hoje ele ja roda para android, mas preciso implementar para ios.

**Comment by preethih78** [comment] 2019-03-07 08:15
sudo npm install -g appium --unsafe-perm=true --allow-root

This command helped me on ubuntu 18.10 version
Try and provide your feedbacks

**Comment by MikaelLuz** [comment] 2019-05-16 21:13
> This worked: `sudo npm install -g appium --unsafe-perm=true --allow-root` (from #10293).

Funcionou pra mim em 16/05/2019..
Thank you!!!

**Comment by mirao** [comment] 2019-08-28 09:54
> This worked: `sudo npm install -g appium --unsafe-perm=true --allow-root` (from #10293).

Works for me on Ubuntu 18.04/19.04 (tested in real and dockerized environment, both are affected). However it seems to be only workaround whereas [Appium docs](http://appium.io/docs/en/about-appium/getting-started/) still says `npm install -g appium` for any platform.

**Comment by mowzey** [comment] 2019-11-28 09:40
> This worked: `sudo npm install -g appium --unsafe-perm=true --allow-root` (from #10293).

Thanks, this worked for me.

**Comment by eduyubero** [comment] 2020-02-06 14:55
> This worked: sudo npm install -g appium --unsafe-perm=true --allow-root (from #10293).
Thank you - This worked for me running on a Mac OS Catalina.

**Comment by majdukovic** [comment] 2020-02-25 15:10
Had some other issues, adding `--force` solved it:
`sudo npm install -g appium --unsafe-perm=true --allow-root --force`

**Comment by lorainegarutti** [comment] 2020-06-23 17:32
This issue is still a problem with ubuntu 20, solved with 

`sudo npm install -g appium --unsafe-perm=true --allow-root`

**Comment by pozda** [comment] 2020-10-02 15:44
> This issue is still a problem with ubuntu 20, solved with
> 
> `sudo npm install -g appium --unsafe-perm=true --allow-root`

I just now did the same on macOS Catalina v10.15.13 and it worked

**Comment by hiwanz** [comment] 2020-11-20 03:42
> sudo npm install -g appium --unsafe-perm=true --allow-root
> 
> This command helped me on ubuntu 18.10 version
> Try and provide your feedbacks

Worked on macOS big sur v11.0.1 (20B29)

**Comment by Anitha0530** [comment] 2021-01-27 23:34
sudo npm install -g appium --unsafe-perm=true --allow-root

This worked on macOS big sur v11....

**Comment by jonbeacherdomuso** [comment] 2022-04-12 20:18
Its because Appium wants a global install with the -g option flag. see https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

"Make sure you have not installed Node or Appium with sudo, otherwise you'll run into problems)." https://appium.io/docs/en/about-appium/getting-started/?lang=en#getting-started

Why does Appium require a global install?
