### ISSUE TITLE
It takes too much time to find elements

### ISSUE THREAD

**Issue by ancining** [appium/appium#11597] opened 2018-10-30 08:01 UTC
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.1
* Last Appium version that did not exhibit the issue (if applicable):Never tried
* Desktop OS/version used to run Appium:1.6.3
* Node.js version (unless using Appium.app|exe):8.12.0
* Mobile platform/version under test:Android
* Real device or emulator/simulator:Real device(Galaxy J7)
* Appium CLI or Appium.app|exe:

## Details

It takes too much time to find elements，When I enter the dynamic page,Like it
![image](https://user-images.githubusercontent.com/26423615/47703893-a3eb2a00-dc5c-11e8-88b2-6012aeee037d.png),It is a clock，and “:” is always flashing

## Link to Appium logs

![image](https://user-images.githubusercontent.com/26423615/47703717-1c9db680-dc5c-11e8-8367-a031757c420b.png)

## Code To Reproduce Issue [ Good To Have ]
click_element_by_name(driver,"选择时区")
def click_element_by_name(driver,name):
    while True:
        try:
            driver.find_element_by_xpath(u"//*[@text='{}']".format(name))
            driver.find_element_by_xpath(u"//*[@text='{}']".format(name)).click()
            break
        except:
            time.sleep(0.5)

**Comment by mykola-mokhnach** [comment] 2018-10-30 10:32
Please provide full server log. Also, make sure the application under test is in idle mode while elements lookup is being performed.

**Comment by Jaspreet23** [comment] 2018-10-30 13:21
Hello,  I am facing the same issue with my script/Appium taking too long to find the elements.
Platform: iOS
>> For a simple step in my Gherkin Scenario : Click a trolley icon in Checkout
This step has to look if any unavailable items are present then handle it 

This alone step takes more than 1m and few seconds as it keeps looking for the element again and again in a loop. Attaching the logs for your reference. Please help as this issue is really making all the scripts very slow and time consuming. As an idea, the appium looks for an element which is not present for approx 20 times before it moves further which is making it extremely slow.

For finding elements, I am either relying on accessibility ids wherever I have access to those other wise I am using this approach 
@iOSXCUITFindBy(iOSNsPredicate = "name BEGINSWITH 'DRIVER INSTRUCTIONS'")

[AppiumLogs.txt](https://github.com/appium/appium/files/2529751/AppiumLogs.txt)

Kindly let me know if you want me to create a separate ticket.

**Comment by mykola-mokhnach** [comment] 2018-10-30 13:29
@Jaspreet23 Your issue is unrelated, since the original one is about Android. Also, in iOS Appium uses WebDriverAgent component, which itself is developed by Facebook. So all such issues there should also be reported to the original repository: https://github.com/facebook/WebDriverAgent

**Comment by Jaspreet23** [comment] 2018-10-30 22:40
Thanks @mykola-mokhnach for your reply. I will raise the issue in that forum.
Also ca I post this issue as a new ticket here? I am using '@iOSFindBy' too to find the elements, thats an appium component, isnt it?

**Comment by ancining** [comment] 2018-10-31 00:49
@mykola-mokhnach 
Hello,It is the full server log,thaks for answer!
[appium-server-logs.txt](https://github.com/appium/appium/files/2532217/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment] 2018-10-31 06:47
I don't see any explicit errors in the log. Most likely the problem is, that the app runs a background animation, so UIA2 must wait until it is in idle state in order to execute element lookup. I would try how it works if espresso driver is used or try to disable background animations.

**Comment by ancining** [comment] 2018-10-31 09:42
@mykola-mokhnach Now how can I avoid this situation? I am puzzled. Is this the BUG of appium?

**Comment by mykola-mokhnach** [comment] 2018-10-31 09:50
I have already answered above. This is how UiAutomator2 framework works and it has nothing to do with Appium.

**Comment by ancining** [comment] 2018-11-01 10:19
Set the "automationName" as well as "appium"

**Comment by mykola-mokhnach** [comment] 2018-11-03 10:06
Closed as not an issue

**Closed by mykola-mokhnach** 2018-11-03 10:06 UTC
Labels: ThirdParty
