### ISSUE TITLE
io.appium.java_client.remote.AppiumCommandExecutor$1lambda$

### ISSUE THREAD

**Issue by AvrahamAtia** [appium/appium#12226] opened 2019-02-26 13:52 UTC
## The problem
08:10:15 Feb 26, 2019 3:10:15 PM io.appium.java_client.remote.AppiumCommandExecutor$1lambda$0
08:10:15 INFO: Detected dialect: W3C

## Environment

java-client: 7.0.0
Appium server: 1.10.0
Node: v11.5.0
Allure: 2.10.0
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T21:49:05+02:00)
Maven home: /usr/local/Cellar/maven/3.5.3/libexec
Java version: 11.0.1, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home
Default locale: en_IL, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.4", arch: "x86_64", family: "mac"

**Comment by AvrahamAtia** [comment] 2019-02-26 14:07
Part of Appium logs:

[debug] [ADB] Install command stdout: Success
[debug] [ADB] Running '/Users/auto_android_haifa_1/Library/Android/sdk/platform-tools/adb -P 5037 -s 00d23eb3d478beb9 shell rm -rf /data/local/tmp/strings.json'
[debug] [W3C (988c715b)] Encountered internal error running command: Error: Android bootstrap socket crashed: Error: This socket has been ended by the other party
[debug] [W3C (988c715b)]     at Socket.socketClient.on.err (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/bootstrap.js:97:21)
[debug] [W3C (988c715b)]     at Socket.emit (events.js:189:13)
[debug] [W3C (988c715b)]     at Socket.writeAfterFIN [as write] (net.js:402:8)
[debug] [W3C (988c715b)]     at _bluebird.default (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/bootstrap.js:122:25)
[debug] [W3C (988c715b)]     at Promise._execute (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/debuggability.js:313:9)
[debug] [W3C (988c715b)]     at Promise._resolveFromExecutor (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/promise.js:483:18)
[debug] [W3C (988c715b)]     at new Promise (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/promise.js:79:10)
[debug] [W3C (988c715b)]     at AndroidBootstrap.sendCommand (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/bootstrap.js:118:18)
[debug] [W3C (988c715b)]     at AndroidBootstrap.sendAction (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/bootstrap.js:161:23)
[debug] [W3C (988c715b)]     at AndroidDriver.helpers.doFindElementOrEls (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:14:31)
[debug] [W3C (988c715b)]     at doFind (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:36:28)
[debug] [W3C (988c715b)]     at wrappedCondFn (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/timeout.js:157:18)
[debug] [W3C (988c715b)]     at /usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:113:26
[debug] [W3C (988c715b)]     at Generator.next (<anonymous>)
[debug] [W3C (988c715b)]     at asyncGeneratorStep (/usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[debug] [W3C (988c715b)]     at _next (/usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[debug] [W3C (988c715b)]     at /usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
[debug] [W3C (988c715b)]     at new Promise (<anonymous>)
[debug] [W3C (988c715b)]     at /usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
[debug] [W3C (988c715b)]     at spin (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:112:11)
[debug] [W3C (988c715b)]     at /usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:126:16
[debug] [W3C (988c715b)]     at Generator.next (<anonymous>)
[debug] [W3C (988c715b)]     at asyncGeneratorStep (/usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[debug] [W3C (988c715b)]     at _next (/usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[debug] [W3C (988c715b)]     at /usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
[debug] [W3C (988c715b)]     at new Promise (<anonymous>)
[debug] [W3C (988c715b)]     at /usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
[debug] [W3C (988c715b)]     at waitForCondition (/usr/local/lib/node_modules/appium/node_modules/asyncbox/build/lib/asyncbox.js:250:28)
[HTTP] <-- POST /wd/hub/session/988c715b-f783-443a-b869-86d001713c40/element 500 66 ms - 771

**Comment by mykola-mokhnach** [comment] 2019-02-26 14:16
Please properly describe the problem and attach full server log

**Comment by AvrahamAtia** [comment] 2019-02-26 14:27
I will run again and share the log, But what is this log mean?
08:10:15 Feb 26, 2019 3:10:15 PM io.appium.java_client.remote.AppiumCommandExecutor$1lambda$0
08:10:15 INFO: Detected dialect: W3C

**Comment by AvrahamAtia** [comment] 2019-02-26 14:30
[debug] [ADB] Uninstalling com.**.staging
[debug] [ADB] Getting install status for com.***.staging
[debug] [ADB] Running '/Users/auto_android_haifa_1/Library/Android/sdk/platform-tools/adb -P 5037 -s 226aa0e42a0d7ece shell dumpsys package com.***.staging'
[debug] [ADB] 'com.***.staging' is installed
[debug] [ADB] Running '/Users/auto_android_haifa_1/Library/Android/sdk/platform-tools/adb -P 5037 -s 226aa0e42a0d7ece shell am force-stop com.***.staging'
[debug] [ADB] Running '/Users/auto_android_haifa_1/Library/Android/sdk/platform-tools/adb -P 5037 -s 226aa0e42a0d7ece uninstall com.***.staging'
[HTTP] --> GET /wd/hub/session/3b7b2a43-4776-41fd-9f39-0bdf1c59066b/screenshot
[HTTP] {}
[debug] [W3C (3b7b2a43)] Calling AppiumDriver.getScreenshot() with args: ["3b7b2a43-4776-41fd-9f39-0bdf1c59066b"]
[debug] [ADB] 'adb uninstall com.***.staging' command output: Success
[ADB] com.***.staging was successfully uninstalled
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting IDs of all 'uiautomator' processes
[debug] [ADB] Running '/Users/auto_android_haifa_1/Library/Android/sdk/platform-tools/adb -P 5037 -s 226aa0e42a0d7ece shell pgrep \^uiautomator\$'
[ADB] No 'uiautomator' process has been found
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Running '/Users/auto_android_haifa_1/Library/Android/sdk/platform-tools/adb -P 5037 -s 226aa0e42a0d7ece shell am force-stop io.appium.unlock'
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1551191336932 (16:28:56 GMT+0200 (Israel Standard Time))
[debug] [W3C (23ab062d)] Received response: null
[debug] [W3C (23ab062d)] But deleting session, so not returning
[debug] [W3C (23ab062d)] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/23ab062d-3733-424b-8f7c-0dcdbbe7409d 200 2068 ms - 14
[HTTP] 
[debug] [W3C (3b7b2a43)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABDgAAAeACAYAAAArYecKAA/1tElEQVR4AazB0XVkwZYQ0YhkZq1hwA+++MQDHMABbMHxl4FOVt/SrZLU3W9gb//3//xf/df//F/YbSheKMSHeCUQQ6X4EK8E4kEgQCAeRPkgtVEpfgkQiE8yFCpAIFQqPgnEJ1EoPsRPVEbxIR7kTqHioguIUfEdleKXuFOpUBnFhxgqFSCfAgQC5CE+CcQrgbioVHySoVIbkK8CRKHik0D8mUAMXdQG5CFUKkAgvhIIEIjvyVCoeCUQQxe1AYFQGRXfE4ihUvGVQIBAvFOpGCoV/zGiUKFSfAgQBZW9A+JBIFQqVCq+EojfUSk+hErFg7yKB4FQqXgQiE/yECAPMXRRAXFRKT7EUCl+CRCIf5ZKxe8JxM/kIUAUil/iolIxdFGboVKhUnwIXUA8Ke3Nk0KhEh+KbykCFUOlAuUohkrFRaXiSaE4lKMYKvGhOBQKFJX25kmhGCoVTwrFFwrFoVAMlVGhUvGkHMV3VCpQKH6iMipeKBRDJT4UhyIQDyrtzaEIxIfijxQKlQoUiieF4p3KiA/FX1MonhSKQzmKi0qFSgUKxZNCcVGpOBSBihfKUahUoFBcVCq+UChUKoZKxZNCgUKBQoFC8VsKxVCpQKF4UoZAfCieFJUKii+UozgUiieF4qJS8aRQoFD8liIQb4onheKvKBSuRXujUvE7rkV7g0LxJyrxoUChOJSjUIk3xVCpeFIonhSBikOh+JZyFIeiQlHxHZWKQzmK31Gp+EI5CpX4Sh4qDoUCheJQngqV+FBcVEbFUKlQqXhSBCpQKFRGxXdUKlQqUAQqUChQKFTipnihUHyhHIVr0d5cVCqeFIqhUvGkCFQ8KRQvlCEPFSoVLxSKLxSKJ0WgAmUIVKBQ/DWF4guFAoXiSXlR/EiheFIofqJS8aRQfEelAoVCpeJHCoVKxUWlQqXiUAQCBOJDcVGpQKFQqUA5iu+4FhUUT4pAfCgO5ShQ...
[HTTP] <-- GET /wd/hub/session/3b7b2a43-4776-41fd-9f39-0bdf1c59066b/screenshot 200 2916 ms - 1394676

**Comment by AvrahamAtia** [comment] 2019-02-26 14:45
https://gist.github.com/AvrahamAtia/abc8604d2802d219326eaefb62f1da3f

**Comment by AvrahamAtia** [comment] 2019-02-26 14:45
https://gist.github.com/AvrahamAtia/abc8604d2802d219326eaefb62f1da3f

**Comment by AvrahamAtia** [comment] 2019-02-26 14:47
It might be retry mechanize of TestNG it is not allows in java-client?

**Comment by AvrahamAtia** [comment] 2019-02-26 15:28
Gist: https://gist.github.com/AvrahamAtia/b35b23de8773065de6a1ebc0372aebc4

**Comment by mykola-mokhnach** [comment] 2019-02-26 18:52
I still cannot understand what the problem is. Kindly describe it properly: steps plus the actual and the expected results or the ticket will be closed as incomplete.


Regarding the exception for the log - just don't use stone age frameworks for newer Android versions. Switch to espresso or UIA2.

> [debug] [W3C (988c715b)] Encountered internal error running command: Error: Android bootstrap socket crashed: Error: This socket has been ended by the other party

**Comment by AvrahamAtia** [comment] 2019-02-27 07:31
App launch and test running ok but after the test fail, the test start over again by retry mechanism app launch and closed immediately.

**Comment by AvrahamAtia** [comment] 2019-02-27 12:29
@mykola-mokhnach

**Comment by mykola-mokhnach** [comment] 2019-02-27 13:53
The response is still the same:

> don't use stone age frameworks for newer Android versions. Switch to espresso or UIA2.

**Comment by mykola-mokhnach** [comment] 2019-03-01 11:52
Closed as not an issue

**Closed by mykola-mokhnach** 2019-03-01 11:52 UTC
Labels: NeedsInfo
