### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Method has not yet been implemented

### ISSUE THREAD

**Issue by myself521** [appium/appium#12256] opened 2019-03-05 08:47 UTC
## The problem

I want use swipe to control screen to scroll,but i got a error message, I have check some information,no answer;

## Environment

Python:2.7.16
Appium:1.9.0
android:8.0.0
node:10.15.1
## Link to Appium logs
[W3C] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"y":200,"x":200}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"y":0,"x":200}},{"action":"release","options":{}}],"11b93cfb-8eeb-4937-a0ef-88ce6375e38f"]
[W3C] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[W3C]     at AndroidDriver.callee$0$0$ (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\commands\touch.js:136:11)
[W3C]     at tryCatch (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[W3C]     at invoke (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[W3C]     at enqueueResult (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
[W3C]     at new Promise (C:\Program Files (x86)\Appium\resources\app\webpack:\~\babel-polyfill\~\core-js\modules\es6.promise.js:177:1)
[W3C]     at new F (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
[W3C]     at AsyncIterator.enqueue (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
[W3C]     at AsyncIterator.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[W3C]     at Object.runtime.async (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
[W3C]     at AndroidDriver.callee$0$0 [as performTouch] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\build\lib\commands\touch.js:375:30)
[W3C]     at C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:296:26
[W3C]     at tryCatcher (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\util.js:26:23)
[W3C]     at Promise._settlePromiseFromHandler (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:510:31)
[W3C]     at Promise._settlePromiseAt (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:584:18)
[W3C]     at Promise._settlePromiseAtPostResolution (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:248:10)
[W3C]     at Async._drainQueue (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:128:12)
[W3C]     at Async._drainQueues (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:133:10)
[W3C]     at Immediate.Async.drainQueues (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:15:14)
[W3C]     at runCallback (timers.js:696:18)
[W3C]     at tryOnImmediate (timers.js:667:5)
[W3C]     at processImmediate (timers.js:649:5)
[HTTP] <-- POST /wd/hub/session/11b93cfb-8eeb-4937-a0ef-88ce6375e38f/touch/perform 404 3 ms - 3793

## Code To Reproduce Issue [ Good To Have ]
dr = webdriver.Remote('http://127.0.0.1:4723/wd/hub',des)
dr.swipe(start_x=200,start_y=200,end_x=200,end_y=0,duration=1000)

**Comment by mykola-mokhnach** [comment] 2019-03-05 09:14
the endpoint is only available in UIA2/Espresso. Also Appium Server itself should be up to date

**Comment by myself521** [comment] 2019-03-05 09:31
> 端点仅适用于UIA2 / Espresso。Appium Server本身也应该是最新的

just before i got a server update but haved a error same 。

**Comment by mykola-mokhnach** [comment] 2019-03-05 09:37
Make sure the correct automation backend is used. Closed as not a bug.

**Closed by mykola-mokhnach** 2019-03-05 09:37 UTC
Labels: NeedsInfo, NotABug

**Comment by myself521** [comment] 2019-03-05 09:41
> s used.
But I don't know how to solve this problem.
Because　i haved check some information,not solved

**Comment by KazuCocoa** [comment] 2019-03-05 11:11
Not sure what `automationName` you used because of no full log, but what about setting your automation name as `uiautomator2` or `espresso` with the latest server? ( as https://github.com/appium/appium/issues/12256#issuecomment-469601489 )
http://appium.io/docs/en/about-appium/getting-started/ 
http://appium.io/docs/en/writing-running-appium/caps/

**Comment by myself521** [comment] 2019-03-06 10:17
> Not sure what `automationName` you used because of no full log, but what about setting your automation name as `uiautomator2` or `espresso` with the latest server? ( as [#12256 (comment)](https://github.com/appium/appium/issues/12256#issuecomment-469601489) )
> http://appium.io/docs/en/about-appium/getting-started/
> http://appium.io/docs/en/writing-running-appium/caps/
thanks guys,
automationName: appium
uiautomator2 and espresso not to use,just use appium/pycharm and android mobile to work
just now i haved to use js script to conctrol screen scroll，at pc it's ok  but in H5  fail
