### ISSUE TITLE
Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj Build Failed 	Task failed with exit code 1:

### ISSUE THREAD

**Issue by narasimhanukala** [appium/appium#14699] opened 2020-09-02 15:04 UTC
## The problem

This issue happens while configuring the appium 1.18.1( with XCode12.0 and iOS14) when i run the step 
$ sudo ./Scripts/bootstrap.sh -d 

## Environment

* Appium version (or git revision) that exhibits the issue:1.18.1
* Last Appium version that did not exhibit the issue (if applicable):1.17.0
* Desktop OS/version used to run Appium:1.18.1
* Node.js version (unless using Appium.app|exe):10.16.3
* Npm or Yarn package manager:6.9.0
* Mobile platform/version under test: iOS 14.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:both

## Details

The same exception been displayed 
1. while trying to launch the app using appium desktop 
2. While building WebDriverAgentRunner on Xcode12

## Link to Appium logs

xxxxxxxMBP3:appium-webdriveragent xxxxxxxx$     ./Scripts/bootstrap.sh -d
Fetching dependencies
*** Checking out YYCache at "1.1.0"
*** Checking out CocoaAsyncSocket at "72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc"
Failed to check out repository into /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/YYCache: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “YYCache” in the folder “Checkouts”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/YYCache, NSUnderlyingError=0x7fa31c23bfe0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
xxxxxxxxx:appium-webdriveragent xxxxxxxxx$ sudo ./Scripts/bootstrap.sh -d
Fetching dependencies
*** Checking out CocoaAsyncSocket at "72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc"
*** Checking out YYCache at "1.1.0"
*** Fetching CocoaAsyncSocket
*** xcodebuild output can be found in /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/carthage-xcodebuild.sg6izT.log
*** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /var/root/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/iOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaAsyncSocket.framework/CocoaAsyncSocket /var/root/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-iphonesimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket -output /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/iOS/CocoaAsyncSocket.framework/CocoaAsyncSocket

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/carthage-xcodebuild.sg6izT.log
xxxxxxxxMBP3:appium-webdriveragent xxxxxxx$ sudo ./Scripts/bootstrap.sh -d
Password:
Fetching dependencies
*** Checking out CocoaAsyncSocket at "72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc"
*** Checking out YYCache at "1.1.0"
*** xcodebuild output can be found in /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/carthage-xcodebuild.1L1Dam.log
*** Building scheme "tvOS Framework" in CocoaAsyncSocket.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /var/root/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/tvOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/appletvos/CocoaAsyncSocket.framework/CocoaAsyncSocket /var/root/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-appletvsimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket -output /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/tvOS/CocoaAsyncSocket.framework/CocoaAsyncSocket

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/carthage-xcodebuild.1L1Dam.log
xxxxxxxxMBP3:appium-webdriveragent xxxxxxxxx$ sudo ./Scripts/bootstrap.sh -d
Fetching dependencies
*** Checking out CocoaAsyncSocket at "72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc"
*** Checking out YYCache at "1.1.0"
*** xcodebuild output can be found in /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/carthage-xcodebuild.ECaWd7.log
*** Building scheme "tvOS Framework" in CocoaAsyncSocket.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /var/root/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/tvOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/appletvos/CocoaAsyncSocket.framework/CocoaAsyncSocket /var/root/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-appletvsimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket -output /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/tvOS/CocoaAsyncSocket.framework/CocoaAsyncSocket

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/carthage-xcodebuild.ECaWd7.log

## Code To Reproduce Issue [ Good To Have ]
$sudo npm install -g appium --chromedriver-skip-install
$ sudo npm install -g appium-doctor
$ brew install libimobiledevice --HEAD
$ brew install ideviceinstaller
$ npm install -g ios-deploy
$sudo xcode-select --switch /Library/Developer/CommandLineTools
$ sudo gem install xcpretty
$cd /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent
$ brew install carthage
$ sudo npm i -g webpack
$sudo xcode-select -s /Applications/Xcode.app
$mkdir -p Resources/WebDriverAgent.bundle
$  ./Scripts/bootstrap.sh -d

after above step experiencing the issue

Kindly help me on resolving this issue.

**Comment by mykola-mokhnach** [comment] 2020-09-02 15:07
Duplicate of https://github.com/appium/appium/issues/14611

**Closed by mykola-mokhnach** 2020-09-02 15:07 UTC

**Comment by narasimhanukala** [comment] 2020-09-02 17:26
Now issue resolved after replacing bootstrap.sh file as per 
https://github.com/appium/appium/issues/14611
