### ISSUE TITLE
[Android][Appium 1.3.7] Could not parse UiSelector argument: UiScrollable has no \"scrollIntoView\" method that takes 2 arguments

### ISSUE THREAD

**Issue by vietnq254** [appium/appium#4807] opened 2015-03-30 11:12 UTC
Hello,

I have a problem with the function ```scrollToExact()```.
It work well if the text has not the ```commas```. 
```
Appium 1.3.7
Java client 2.2.0
```
Here is the code:
```
AndroidDriver dr...;
dr.scrollToExact("Photo Books, Scrapbooks, Photo Cards.")
```
And log:
```
[debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description(\"Photo Books, Scrapbooks, Photo Cards.\").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"Photo Books, Scrapbooks, Photo Cards.\").instance(0));","context":"","multiple":false}}
[debug] [BOOTSTRAP] [debug] Got command of type ACTION
[debug] [BOOTSTRAP] [debug] Got command action: find
[debug] [BOOTSTRAP] [debug] Finding new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description("Photo Books, Scrapbooks, Photo Cards.").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text("Photo Books, Scrapbooks, Photo Cards.").instance(0)); using ANDROID_UIAUTOMATOR with the contextId:  multiple: false
[debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().description("Photo Books, Scrapbooks, Photo Cards.").instance(0))
[debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
[debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
[debug] [BOOTSTRAP] [debug] Returning result: {"value":"Could not parse UiSelector argument: UiScrollable has no \"scrollIntoView\" method that takes 2 arguments","status":9}
```

**Comment by vietnq254** [comment] 2015-04-02 07:16
Reference #4482

**Comment by jlipps** [comment] 2015-04-02 17:02
this is a duplicate of that issue

**Closed by jlipps** 2015-04-02 17:02 UTC
Labels: NeedsTriage
