### ISSUE TITLE
Not able to select value from dropdown in ios

### ISSUE THREAD

**Issue by raghavbhatia02** [appium/appium#9175] opened 2017-09-06 07:46 UTC
# The problem
Not able to select value from dropdown menu in Iphone.

# Code:
```
String birthdate = "//XCUIElementTypeScrollView/XCUIElementTypeOther";
appdriver.findElementByXPath(birthdate).sendKeys("Listbox Two");

```
# Error:

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "**Keyboard is not present**" UserInfo={NSLocalizedDescription=Keyboard is not present} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 6.30 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'Darpans-MBP', ip: '192.168.43.215', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_144'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/testing/Desktop/Debugger-CBApp.app, networkConnectionEnabled=false, noReset=true, databaseEnabled=false, deviceName=Raghav’s iPhone 7 Plus, platform=MAC, platformVersion=10.3, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=2c89d9a49e7f40da5cc705ebea9f8f57dea4bfaf}]
Session ID: 069687d8-f215-4879-8696-12bb541d551c
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:272)
	at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:45)
	at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
	at io.appium.java_client.ios.IOSElement.execute(IOSElement.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:96)
	at sampleAppium.Practice.main(Practice.java:57)

# Screenshot of application:
![screen shot 2017-09-06 at 1 05 48 pm](https://user-images.githubusercontent.com/22788872/30099797-6a976d24-9304-11e7-9f7d-5e359e33de3f.png)

# Environment:
Appium : 1.6.4
Xcode : 8.3.2
Iphone 7 Plus
IOS Version: 10.3.2
IOS Inspector to locate elements

**Comment by mykola-mokhnach** [comment] 2017-09-06 07:54
If this is a control inside a web view then you need to switch to webview context and only after then interact with the element. Otherwise (if this is a native element, which I have doubts of) it is necessary to tap the element first and  then tap the corresponding item (combo item) as soon as it appears on the screen, same way one is doing that manually.

Closed as not a bug.

**Closed by mykola-mokhnach** 2017-09-06 07:54 UTC

**Comment by raghavbhatia02** [comment] 2017-09-07 10:42
This is a native element. And I am not able to select the first element or any element from the dropdown because there are no element locators for that. We are able to select element from the dropdown in **Android** but **not** for **IOS**.
