### ISSUE TITLE
iOS 13, Xcode 11 WebDriverAgentRunner tests failed

### ISSUE THREAD

**Issue by Xu-wenchao** [appium/appium#14119] opened 2020-03-30 03:51 UTC
## The problem

iOS 13, Xcode 11 WebDriverAgentRunner tests failed

## Environment

* Appium 1.15.1
* Mac OS 10.15.4
* Node.js version v13.11.0
* Npm 6.13.7
* iPhone 7 13.2.3

## Details
I built the WebDriverAgent Successful, But when I Test WebDriverAgentRunner on my iPhone 7(ios13.2.3), It tips "Test Failed", The next is the log.

## XCodeLog
2020-03-29 20:39:06.694710-0700 WebDriverAgentRunner-Runner[2817:39622] Running tests...
Test Suite 'All tests' started at 2020-03-29 20:39:12.146
Test Suite 'WebDriverAgentRunner.xctest' started at 2020-03-29 20:39:12.147
Test Suite 'UITestingUITests' started at 2020-03-29 20:39:12.147
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s Start Test at 2020-03-29 20:39:12.148
    t =     0.01s Set Up
2020-03-29 20:39:12.162222-0700 WebDriverAgentRunner-Runner[2817:39622] -[UITestingUITests internalImplementation]: unrecognized selector sent to instance 0x28053cc30
    t =     0.08s     Assertion Failure: <unknown>:0: failed: caught "NSInvalidArgumentException", "-[UITestingUITests internalImplementation]: unrecognized selector sent to instance 0x28053cc30"
(
	0   CoreFoundation                      0x0000000188ce1820 FF63481D-FB6A-353B-B2C1-AC4EAECF594D + 1226784
	1   libobjc.A.dylib                     0x0000000188a09fa4 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000188be536c FF63481D-FB6A-353B-B2C1-AC4EAECF594D + 193388
	3   CoreFoundation                      0x0000000188ce5c88 FF63481D-FB6A-353B-B2C1-AC4EAECF594D + 1244296
	4   CoreFoundation                      0x0000000188ce7a6c _CF_forwarding_prep_0 + 92
	5   WebDriverAgentLib                   0x0000000101d1e3fc -[FBFailureProofTestCase setUp] + 136
	6   XCTest                              0x0000000101366c88 __48-[XCTestCase _performSetUpSequenceWithSelector:]_block_invoke_2 + 492
	7   XCTest                              0x00000001013bc0d8 +[XCTestCase(Failures) performFailableBlock:testCase:testCaseRun:shouldInterruptTest:] + 84
	8   XCTest                              0x00000001013bbfdc -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 132
	9   XCTest                              0x0000000101366a7c __48-[XCTestCase _performSetUpSequenceWithSelector:]_block_invoke + 116
	10  XCTest                              0x00000001013cdd7c -[XCTContext _runActivityNamed:type:block:] + 248
	11  XCTest                              0x000000010136f480 -[XCTestCase startActivityWithTitle:type:block:] + 200
	12  XCTest                              0x000000010136f630 -[XCTestCase startActivityWithTitle:block:] + 72
	13  XCTest                              0x00000001013669f8 -[XCTestCase _performSetUpSequenceWithSelector:] + 108
	14  XCTest                              0x0000000101364d68 -[XCTestCase invokeTest] + 728
	15  XCTest                              0x00000001013668b8 __26-[XCTestCase performTest:]_block_invoke_2 + 44
	16  XCTest                              0x00000001013bc0d8 +[XCTestCase(Failures) performFailableBlock:testCase:testCaseRun:shouldInterruptTest:] + 84
	17  XCTest                              0x00000001013bbfdc -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 132
	18  XCTest                              0x00000001013667f0 __26-[XCTestCase performTest:]_block_invoke.366 + 96
	19  XCTest                              0x00000001013ce48c +[XCTContext runInContextForTestCase:block:] + 212
	20  XCTest                              0x00000001013660dc -[XCTestCase performTest:] + 540
	21  XCTest                              0x00000001013a986c -[XCTest runTest] + 60
	22  XCTest                              0x00000001013605c8 __27-[XCTestSuite performTest:]_block_invoke + 268
	23  XCTest                              0x000000010135fe58 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40
	24  XCTest                              0x00000001013ce48c +[XCTContext runInContextForTestCase:block:] + 212
	25  XCTest                              0x000000010135fe00 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 156
	26  XCTest                              0x0000000101360150 -[XCTestSuite performTest:] + 320
	27  XCTest                              0x00000001013a986c -[XCTest runTest] + 60
	28  XCTest                              0x00000001013605c8 __27-[XCTestSuite performTest:]_block_invoke + 268
	29  XCTest                              0x000000010135fe58 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40
	30  XCTest                              0x00000001013ce48c +[XCTContext runInContextForTestCase:block:] + 212
	31  XCTest                              0x000000010135fe00 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 156
	32  XCTest                              0x0000000101360150 -[XCTestSuite performTest:] + 320
	33  XCTest                              0x00000001013a986c -[XCTest runTest] + 60
	34  XCTest                              0x00000001013605c8 __27-[XCTestSuite performTest:]_block_invoke + 268
	35  XCTest                              0x000000010135fe58 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40
	36  XCTest                              0x00000001013ce48c +[XCTContext runInContextForTestCase:block:] + 212
	37  XCTest                              0x000000010135fe00 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 156
	38  XCTest                              0x0000000101360150 -[XCTestSuite performTest:] + 320
	39  XCTest                              0x00000001013a986c -[XCTest runTest] + 60
	40  XCTest                              0x00000001013e05f0 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 176
	41  XCTest                              0x00000001013e06f0 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.100 + 108
	42  XCTest                              0x000000010137a354 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 588
	43  XCTest                              0x00000001013e0388 -[XCTTestRunSession runTestsAndReturnError:] + 592
	44  XCTest                              0x0000000101344bbc -[XCTestDriver runTestsAndReturnError:] + 428
	45  XCTest                              0x00000001013ca424 _XCTestMain + 2396
	46  WebDriverAgentRunner-Runner         0x0000000100f27818 -[_XCTRunnerAppDelegate applicationWillResignActive:] + 0
	47  WebDriverAgentRunner-Runner         0x0000000100f27720 _XCTRunnerRunTests + 0
	48  CoreFoundation                      0x0000000188c5f5f8 FF63481D-FB6A-353B-B2C1-AC4EAECF594D + 693752
	49  CoreFoundation                      0x0000000188c5ed98 FF63481D-FB6A-353B-B2C1-AC4EAECF594D + 691608
	50  CoreFoundation                      0x0000000188c5a014 FF63481D-FB6A-353B-B2C1-AC4EAECF594D + 671764
	51  CoreFoundation                      0x0000000188c598a0 CFRunLoopRunSpecific + 464
	52  GraphicsServices                    0x0000000192bb1328 GSEventRunModal + 104
	53  UIKitCore                           0x000000018cd4a740 UIApplicationMain + 1936
	54  WebDriverAgentRunner-Runner         0x0000000100f279e4 main + 192
	55  libdyld.dylib                       0x0000000188ae4360 1DB44CE7-7030-3D97-9461-6EC743F47783 + 4960
)
    t =     0.09s Tear Down
Test Case '-[UITestingUITests testRunner]' failed (0.099 seconds).
Test Suite 'UITestingUITests' failed at 2020-03-29 20:39:12.247.
	 Executed 1 test, with 1 failure (1 unexpected) in 0.099 (0.100) seconds
Test Suite 'WebDriverAgentRunner.xctest' failed at 2020-03-29 20:39:12.248.
	 Executed 1 test, with 1 failure (1 unexpected) in 0.099 (0.101) seconds
Test Suite 'WebDriverAgentLib.framework' started at 2020-03-29 20:39:12.248
Test Suite 'WebDriverAgentLib.framework' passed at 2020-03-29 20:39:12.249.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'All tests' failed at 2020-03-29 20:39:12.259.
	 Executed 1 test, with 1 failure (1 unexpected) in 0.099 (0.113) seconds

**Comment by mykola-mokhnach** [comment] 2020-03-30 05:38
Duplicate of https://github.com/appium/appium/issues/13949

**Closed by mykola-mokhnach** 2020-03-30 05:38 UTC
