### ISSUE TITLE
Anyone got the solution for this > Cannot get 'xml' source of the current application #13831

### ISSUE THREAD

**Issue by GaneshGunaki** [appium/appium#14126] opened 2020-03-30 17:36 UTC
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment] 2020-03-30 17:52
Closing as completely incomplete.

**Closed by imurchie** 2020-03-30 17:52 UTC

**Comment by GaneshGunaki** [comment] 2020-03-30 17:57
@imurchie  , Cannot get 'xml' source of the current application #13831
 I am facing this issue , Can i get any solution for this ?

**Comment by imurchie** [comment] 2020-03-30 18:28
Did you do what was discussed in that issue?

What version of Appium are you using? What device? What are the logs?

The template for the issue is there to lead you to provide the information needed to make any kind of advice. In the absence of details there is nothing that can be done.

**Comment by GaneshGunaki** [comment] 2020-03-30 18:49
@imurchie I have updated my issue . Can you please help me on this..

**Comment by mykola-mokhnach** [comment] 2020-03-30 19:45
Please use the most recent server version and try the solution from https://github.com/appium/WebDriverAgent/pull/273
