### ISSUE TITLE
Cannot build WebDriverAgent: Cannot link directly with dylib/framework

### ISSUE THREAD

**Issue by kianreno** [appium/appium#17495] opened 2022-09-15 22:17 UTC
## The problem

It looks like webdriveragent will no longer build since upgrading to xcode 14. It is throwing an error but is working fine on xcode version 13.4.1

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Desktop OS/version used to run Appium: MacOS 12.6 on MBP with M1 Pro chip
* Node.js version (unless using Appium.app|exe): v18.6.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: 15.6.1
* Real device or emulator/simulator: both 
* Appium CLI or Appium.app|exe: not getting to this step. Can't build webdriveragent

## Details

Builds fail immediately with the error: 

error build: Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64

excluding the arm64 architecture does not resolve the problem.

**Comment by KazuCocoa** [comment] 2022-09-15 22:25
Duplicate of https://github.com/appium/appium/issues/17174

Please use latest xcuitest driver via appium 2

**Closed by KazuCocoa** 2022-09-15 22:25 UTC

**Comment by omprakashchavan01** [comment] 2022-09-20 05:06
@KazuCocoa, would it be possible to fix the issue in Appium 1.x as well until Appium 2.0 is in Beta? I would believe majority of people are still on Appium 1.x and wouldn't migrate to Appium 2.0 until stable version is out. Moreover, I believe there was a plan of having an overlapping period of 6 months to support Appium 1.x issues. Any idea what happened to that plan, is it still on?
