### ISSUE TITLE
WebDriverAgent taking too long to start running.

### ISSUE THREAD

**Issue by AnujDasari** [appium/appium#12679] opened 2019-05-23 09:51 UTC
## The problem
While running scripts on a iOS device, the webdriveragent takes more than 60 seconds to start running.

The tests eventually run and pass but the execution time of each test is extremely high.

## Environment
* Appium version (or git revision) that exhibits the issue: v1.12.1
* Desktop OS/version used to run Appium: OSX 10.14.4
* Node.js version (unless using Appium.app|exe): v10.15.3
* Mobile platform/version under test: iOS v.12.2
* Real device or emulator/simulator: Simulator iPhone Xs
## Details
On running tests on iOS device/simulator, the WebDriverAgent takes too long to start and subsequently each test takes a lot of time to run. 

## Link to Appium logs

https://gist.github.com/AnujDasari/5c342433fd47043f3dec0cadf1f1e844

## Code To Reproduce Issue [ Good To Have ]

```   
capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone Xs");
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "12.2");
capabilities.setCapability(MobileCapabilityType.APP, "/Users/anuj/Downloads/Demo.app");
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
capabilities.setCapability("useNewWDA", true);
```

**Comment by AnujDasari** [comment] 2019-05-23 09:53
I see the below in the appium logs:

```
debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
```

This continues for a random amount of time, sometimes as long as 2 minutes, before the WebDriverAgent starts running.

**Comment by mykola-mokhnach** [comment] 2019-05-23 10:06
Possible duplicate of https://github.com/appium/appium/issues/12444

**Comment by AnujDasari** [comment] 2019-05-23 10:24
@mykola-mokhnach Thank you for redirecting me to a similar issue.
However, the capabilities that helped resolve #12444 do not work for me.

I added these capabilities:

```
capabilities.setCapability("waitForQuiescence", false);
capabilities.setCapability("wdaEventloopIdleDelay", 3);
capabilities.setCapability("eventLoopIdleDelaySec", 1);
```

but still see the delay.

Since you mentioned on the issue #12444 that this is not an issue specific to Appium, is there anything else I can do to reduce this delay?

**Comment by mykola-mokhnach** [comment] 2019-05-23 10:41
> is there anything else I can do to reduce this delay?

You can try to disable `useNewWDA` cap. Setting it to true enforces WDA rebuilding for each session. Proper use of `useXctestrunFile` and  `usePrebuiltWDA` caps might also reduce the init time.

**Comment by mykola-mokhnach** [comment] 2019-05-28 05:25
Closed as third party issue

**Closed by mykola-mokhnach** 2019-05-28 05:25 UTC
Labels: ThirdParty, XCUITest
