### ISSUE TITLE
Automatic test. It takes a long time to wait between the first step and the second step, which makes the later operation impossible.

### ISSUE THREAD

**Issue by qxmingsj** [appium/appium#13490] opened 2019-10-25 02:28 UTC
[Xcode]     t =    13.84s Find the "我" Button
[Xcode] 
[Xcode]     t =    13.85s     Requesting snapshot of accessibility hierarchy for app with pid 332
[Xcode] 
[Xcode]     t =    13.93s     Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    13.94s     Find: Elements matching predicate '"我" IN identifiers'
[Xcode] 
[Xcode]     t =    13.94s     Find: Identity Binding
[Xcode] 
[Xcode]     t =    13.95s Tap "我" Button
[Xcode]     t =    13.95s     Wait for com.tencent.xin to idle
[Xcode] 
[Xcode]     t =    73.96s         App animations complete notification not received, will attempt to continue.
[Xcode] 
[Xcode]     t =    73.97s     Find the "我" Button
[Xcode] 
[Xcode]     t =    73.98s         Requesting snapshot of accessibility hierarchy for app with pid 332
[Xcode] 
[Xcode]     t =    74.09s         Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    74.09s         Find: Elements matching predicate '"我" IN identifiers'
[Xcode] 
[Xcode]     t =    74.10s         Find: Identity Binding
[Xcode] 
[Xcode]     t =    74.11s     Check for interrupting elements affecting "我" Button
[Xcode] 
[Xcode]     t =    74.12s         Requesting snapshot of accessibility hierarchy for app with pid 332
[Xcode] 
[Xcode]     t =    74.18s         Find: Descendants matching type Alert
[Xcode] 
[Xcode]     t =    74.19s     Synthesize event
[Xcode] 
[Xcode]     t =    74.25s     Wait for com.tencent.xin to idle
........
[debug] [DevCon Factory] Cached connections count: 0
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [W3C (8852403c)] Encountered internal error running command: Error: Could not proxy. Proxy error: New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability
[debug] [W3C (8852403c)]     at doJwpProxy (/usr/local/lib/node_modules/appium/node_modules/_appium-base-driver@4.1.0@appium-base-driver/lib/protocol/protocol.js:490:13)
[HTTP] <-- POST /wd/hub/session/8852403c-20c5-4ee9-97c9-3db6a9a74d23/element/13000000-0000-0000-4C01-000000000000/click 500 60330 ms - 847
[HTTP] 

Mac、Xcode ：Latest edition
appium:1.15.1（Something the matter）
appium:1.14(That's all right.)

**Comment by mykola-mokhnach** [comment] 2019-10-25 10:02
Duplicate of https://github.com/appium/appium/issues/13455

Unfortunately this is XCTest itself, who is sending the keypresses. We cannot influence this behaviour from Appium

**Closed by mykola-mokhnach** 2019-10-25 10:02 UTC
