### ISSUE TITLE
[UiAutomator] UiAutomator exited unexpectedly with code 143, signal null

### ISSUE THREAD

**Issue by testfortest06** [appium/appium#12942] opened 2019-07-20 02:08 UTC
## The problem

When i was running my script and try to perform any action then App getting closed . However Yesterday same code working fine for me but today its giving error:

In appium log says 
[UiAutomator] UiAutomator exited unexpectedly with code 143, signal null
[UiAutomator] Moving to state 'stopped'
[AndroidDriver] Shutting down Android driver
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
## Environment

* Appium version : 1.13.0
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android / 8.1.0
* Real device or emulator/simulator: Real Device
* Appium Java Client Version : 7.0.0
* Selenium version : 3.141.59

## Details
When i was running my script and try to perform any action then App getting closed . However Yesterday same code working fine for me but today its giving error:
  org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command ''C:\\Users\\Manish Kumar\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe' -P 5037 -s 35924c6f0804 shell input keyevent 3' exited with code 137'; Stderr: ''; Code: '137'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

## Link to Appium logs
Log Link: https://gist.github.com/testfortest06/9303b75b8f24075575ccdf5e1eb6d740

## Code To Reproduce Issue [ Good To Have ]
public class BaseTest {
public static AndroidDriver<MobileElement> driver;

@BeforeMethod
public void beforeTest() throws InterruptedException {
	File app=new File("D:\\APK_File\\VT.apk");
	DesiredCapabilities cap=new DesiredCapabilities();
	cap.setCapability("deviceName", "Redmi");
	cap.setCapability("platformVersion", "8.1.0");
	cap.setCapability("platformName", "Android");
	cap.setCapability("app", app.getAbsolutePath());
	cap.setCapability("noReset", true);
	cap.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "60");

	
try {
	driver=new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"),cap);
	Thread.sleep(4000);
} catch (MalformedURLException e) {
	// TODO Auto-generated catch block
	e.printStackTrace();
}
}

@Test
public void test1() throws InterruptedException {
	System.out.println("Inside Test...");
	Thread.sleep(5000);
//Tap on menu
	driver.findElement(By.id("com.veritread.veritread:id/fragment_find_freight_search_filter_image_view")).click();
	Thread.sleep(5000);
}
@AfterMethod
public void afterTest() {
	
	
		driver.quit();
	
}

}

**Comment by mykola-mokhnach** [comment] 2019-07-20 05:54
UiAutomator should not be used for Android6+ Consider switching to UiAutomator2/Espresso. Closed as not an issue

**Closed by mykola-mokhnach** 2019-07-20 05:54 UTC

**Comment by testfortest06** [comment] 2019-07-20 06:03
@mykola-mokhnach  What should i do, How to resolve this, Please guide its working yesterday but today its not working.

**Comment by mykola-mokhnach** [comment] 2019-07-20 06:06
http://appium.io/docs/en/drivers/android-uiautomator2/

**Comment by testfortest06** [comment] 2019-07-20 06:16
@mykola-mokhnach 
I have added      cap.setCapability("automationName", "UiAutomator2"); 
 
but getting an error :
[AndroidDriver] Unable to set mock location for app 'io.appium.settings': Error executing adbExec. Original error: 'Command ''C:\\Users\\Manish Kumar\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe' -P 5037 -s 35924c6f0804 shell appops set io.appium.settings android\:mock_location allow' exited with code 255'; Stderr: 'Security exception: uid 2000 does not have android.permission.UPDATE_APP_OPS_STATS.
*******************
Appium Log:  Link : https://gist.github.com/testfortest06/3e29e99216564810151049dc53f2a5a5

Please help

**Comment by KazuCocoa** [comment] 2019-07-20 06:40
The message was just a warning, but it did not block the running process.

Your root cause was probably below `INSTALL_FAILED_USER_RESTRICTED`.
What about changing your device settings following https://stackoverflow.com/questions/47239251/install-failed-user-restricted-android-studio-using-redmi-4-device ?

```
[BaseDriver] Event 'newSessionStarted' logged at 1563602843362 (11:37:23 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command ''C:\\Users\\Manish Kumar\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe' -P 5037 -s 35924c6f0804 shell pm install /data/local/tmp/appium_cache/56abf1bf10f6562619a2dd8fb060718e27c4cb28.apk' exited with code 1'; Stderr: 'Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]'; Code: '1'
[W3C] Error: Command ''C:\\Users\\Manish Kumar\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe' -P 5037 -s 35924c6f0804 shell pm install /data/local/tmp/appium_cache/56abf1bf10f6562619a2dd8fb060718e27c4cb28.apk' exited with code 1
[W3C]     at ChildProcess.proc.on.code (C:\Users\Manish Kumar\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\teen_process\lib\exec.js:94:19)
[W3C]     at ChildProcess.emit (events.js:182:13)
[W3C]     at maybeClose (internal/child_process.js:961:16)
[W3C]     at Socket.stream.socket.on (internal/child_process.js:380:11)
[W3C]     at Socket.emit (events.js:182:13)
[W3C]     at Pipe._handle.close [as _onclose] (net.js:596:12)
```

**Comment by testfortest06** [comment] 2019-07-20 06:53
@KazuCocoa @mykola-mokhnach  Now i have another error : [UiAutomator2] Unable to find instrumentation target 'io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner': The instrumentation target is not listed by Package Manager

Appium Log Link : https://gist.github.com/testfortest06/3024bf709765d81d13f6f8062d348b9c

Please Take a look..

**Comment by KazuCocoa** [comment] 2019-07-20 07:03
The installed UIA2 server looks old. Maybe npm installed remaining older resources.

Please re-install your Appium server so that Appium can use the proper version

```
[UiAutomator2]     io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner (target=io.appium.uiautomator2.server)
[UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 8200
[ADB] Forwarding system: 8200 to device: 6790
```

`io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner` shold be there instead of `io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner` in your version.

**Comment by testfortest06** [comment] 2019-07-20 09:47
Thanks you so much @mykola-mokhnach @KazuCocoa 
I have used below command now its working for me..

adb uninstall io.appium.uiautomator2.server
adb uninstall io.appium.uiautomator2.server.test

**Comment by mrk-han** [comment] 2019-11-15 17:18
Another potential workaround for UIAutomator: 
1) Clear all data of Emulator from AVD Menu in Android Studio
2) Cold Boot the device. 

This worked for me. Unfortunately the switch to UIAutomator2 cannot be done in every case, such as a large legacy codebase. So this works to get by.
