### ISSUE TITLE
Encountered internal error running command: TypeError: Invalid Version: android-8.1.0

### ISSUE THREAD

**Issue by rrandoom** [appium/appium#10327] opened 2018-03-09 10:39 UTC
code:
desired_caps = {}
desired_caps['platformName'] = 'android'
desired_caps['platformVersion'] ="5.1"
desired_caps['deviceName'] = "meizu"
desired_caps['udid'] = '59a361af'
desired_caps['automationName'] = 'UiAutomator2'
desired_caps['appPackage']='com.android.bbkcalculator'
desired_caps['appActivity']='.Calculator'

error:
[Appium] Merged W3C capabilities {"firstMatch":[{}],"alwaysMatch":{"platformName... into desiredCapabilities object {"platformName":"android","platformVersion":"5....
[Appium] Creating new AndroidUiautomator2Driver (v0.11.0) session
[Appium] Capabilities:
[Appium] platformName: android
[Appium] platformVersion: 5.1
[Appium] deviceName: meizu
[Appium] udid: 59a361af
[Appium] automationName: uiautomator2
[Appium] appPackage: com.android.bbkcalculator
[Appium] appActivity: .Calculator
[BaseDriver] Session created with session id: 0ebb3c4c-8186-4c1c-818b-c27a1fcf1182
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_144
[ADB] Checking whether adb is present
**[UiAutomator2] Deleting UiAutomator2 session**

[MJSONWP] Encountered internal error running command: TypeError: Invalid Version: android-8.1.0

version
python:3.6.1
java:1.8
appium :1.7.2  (instatlled mathon: npm  install -g appium)

**Comment by mykola-mokhnach** [comment] 2018-03-09 13:16
Duplicate of https://github.com/appium/appium/issues/10313

**Closed by mykola-mokhnach** 2018-03-09 13:16 UTC
