### ISSUE TITLE
Operations are too slow while a stream is coming

### ISSUE THREAD

**Issue by ismailyankayis** [appium/appium#12829] opened 2019-06-26 07:18 UTC
## The problem

My problem is appium runs too slow while a stream is coming. For example, when a video, song, or radio is open, find and click operations take at least 20 seconds. This problem didnot happen on version which is published 6 months ago.

## Environment

* Appium version (or git revision) that exhibits the issue: **v1.13.0**
* Last Appium version that did not exhibit the issue (if applicable): **v1.10.0 (about these version, I'm not sure )**
* Desktop OS/version used to run Appium: **Windows 10**
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: **Android 5 - Android 10**
* Real device or emulator/simulator: **Real Device**
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[LOGS](https://gist.github.com/ismailyankayis/da49cbe993bb80c6cabd66897a5aa2eb)

## Code To Reproduce Issue [ Good To Have ]
**// A Scenario Example
Scenario: 77MP VideoIzleMaxiPlayerOncekiButonu
    When I go to search page and type "Tarkan" and swipe to first video list
    And I click first video list
    Then I see video list page
    And I swipe up until I see second video name
    Then I save first video name text as the first video name
    When I click second video name
    Then I see player page
    And I click pause button
    When I click previous button
    Then I wait for 3 seconds
    When I click previous button
    Then I wait for 3 seconds
    When I click pause button
    Then I save song name text as the current video name
    And I verify the current video name equals the first video name
    Then I click minimize button
    Then I see video list page**

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2019-06-26 08:18
Try appium@beta, it contains some improvements in this area.

Duplicate of https://github.com/appium/appium-uiautomator2-server/issues/283

**Closed by mykola-mokhnach** 2019-06-26 08:18 UTC
