### ISSUE TITLE
Child elements are not available in Appium (iOS)

### ISSUE THREAD

**Issue by ochervenchuk** [appium/appium#14052] opened 2020-03-11 15:06 UTC
## The problem

Cannot get accesses to some elements which contains in table or dropdown elements. On Android platform everything is ok. Developer added AutomationProperties.IsInAccessibleTree=“True” to this elements, but it was not help. We found some issue related with compatibility between Appium and Xamarin.Forms. Last worked version for Xamarin.Frm it is 3.6, after this version this issue are stable [Link to item on Xamarin](https://github.com/xamarin/xamarin.forms/issues/6667)

![Screenshot_2](https://user-images.githubusercontent.com/36152674/76431518-5509e480-63ba-11ea-9bf7-4660be5e69c2.png)
## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: iOS (all version) 
* Real device or emulator/simulator: real device from BrowserStack

**Comment by mykola-mokhnach** [comment] 2020-03-11 15:09
Duplicate of https://github.com/appium/appium/issues/13516

Unfortunately there is nothing we can do about it on Appium side.

**Closed by mykola-mokhnach** 2020-03-11 15:09 UTC

**Comment by medright** [comment] 2020-04-14 17:52
Looks like this is an issue with how Xamarin loads accessibility id's. if you turn VoiceOver on the inspector will see them again.. just doesn't help with running your tests.. 

<img width="1680" alt="Screen Shot 2020-04-14 at 12 35 19 PM" src="https://user-images.githubusercontent.com/4702913/79257060-0fc45100-7e57-11ea-8d7d-f85499e272ce.png">
