### ISSUE TITLE
Xcode 13  Can't dismiss keyboard 

### ISSUE THREAD

**Issue by mochitest** [appium/appium#15861] opened 2021-09-17 15:55 UTC
## The problem

org.openqa.selenium.InvalidElementStateException: Error Domain=com.facebook.WebDriverAgent Code=1 "Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test." UserInfo={NSLocalizedDescription=Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test.}

## Environment

* Appium v1.22.0-beta.0

## Details
driver.hideKeyboard();

**Comment by mykola-mokhnach** [comment] 2021-09-17 16:36
Duplicate of https://github.com/appium/appium/issues/15073

**Closed by mykola-mokhnach** 2021-09-17 16:36 UTC
