### ISSUE TITLE
WebDriverAgent not installing on my appium

### ISSUE THREAD

**Issue by olubukolaaborode** [appium/appium#14163] opened 2020-04-09 11:55 UTC
## The problem

On trying to install and run an app using appium, I got this error 

"WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: Cannot launch simulated executable: no file found at /Users/<name>/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app))"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Desktop OS/version used to run Appium: macOS Catalina (version 10.15.4)
* Mobile platform/version under test: iOS / iOS 13.4
* Real device or emulator/simulator: Simulator (iPhone 11 Pro Max)

## Link to Appium logs

<script src="https://gist.github.com/olubukolaaborode/6019e74493ec4685eb720fec32d4520c.js"></script>

**Comment by mykola-mokhnach** [comment] 2020-04-09 12:08
Duplicate of https://github.com/appium/appium/issues/14102

**Closed by mykola-mokhnach** 2020-04-09 12:08 UTC
