### ISSUE TITLE
bug: Wrong "isAccessible" attribute for TableView/Collection children elements

### ISSUE THREAD

**Issue by ikharebashviliGD** [appium/appium#19625] opened 2024-01-08 12:15 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

WebDriverAgent (WDA) is providing incorrect isAccessible data for elements located inside a table (TableViewHeaderView) or within a cell.
### Details:
Firstly, let's consider the `empty_view__image` element inside the table, specifically within the `TableHeaderView`. The Xcode View Debugger indicates that the element is not accessible. However, in the screen hierarchy obtained from WDA, it is stated that `isAccessible: true`.

To further verify this, I assigned an identifier to this element in the screen's code, which should reflect its true accessibility status. For example:` imageView.accessibilityIdentifier = "empty_button_\(imageView.isAccessibilityElement)"`.

Now, the screen hierarchy displays the following:
```
{
   "isEnabled":"1",
   "isVisible":"1",
   "isAccessible":"1",
   "frame":"{{156, 168}, {81, 82}}",
   "isFocused":"0",
   "rect":{
      "y":168,
      "x":156,
      "width":81,
      "height":82
   },
   "value":null,
   "label":null,
   "type":"Image",
   "name":"empty_image_false",
   "rawIdentifier":"empty_image_false"
}
```
![XcodeViewDebugger](https://github.com/appium/appium/assets/141834593/7001e51f-b3a2-429f-92f8-cd05854b0a15)

### Expected Behavior

The **`isAccessible`** property should accurately reflect the accessibility status of elements as determined by the Xcode View Debugger. In this case, elements within the **`TableHeaderView`** or a cell that are not accessible should be reported as **`isAccessible: false`** by WDA.

### Minimal Reproducible Example

[WrongIsAccessibleField.zip](https://github.com/appium/appium/files/13859828/WrongIsAccessibleField.zip)

### Environment

- WDA version (or git revision) that exhibits the issue: v5.15.6
- Desktop OS/version used to run Appium: MacOS
- Mobile platform/version under test: iOS
- Real device or emulator/simulator: Both

**Comment by mykola-mokhnach** [comment] 2024-01-08 12:47
Duplicate of https://github.com/appium/appium/issues/16425

**Closed by mykola-mokhnach** 2024-01-08 12:47 UTC
Labels: Bug, Needs Triage
