### ISSUE TITLE
selectPickerWheelValue can't use accessibilityLabel for element?

### ISSUE THREAD

**Issue by LayMuiToh** [appium/appium#12213] opened 2019-02-23 13:39 UTC
## The problem

const SELECTORS = {
  
    IOS_PICKERWHEEL: '~Picker',
    DONE: '~Done',
   
};

class MoreFilters extends Page {

    /* 
    ** Define elements
    */
    
    get picker()  { return $(SELECTORS.IOS_PICKERWHEEL); }
    get done()  { return $(SELECTORS.DONE); }
}

 if (MoreFilters.picker.waitForVisible()) {
            browser.execute('mobile: selectPickerWheelValue', 
          { element: MoreFilters.picker, order: 'next', offset: 0.5});
        }

When running test, there is a error message:
1) More Filters test should able to tap on the More Filters and go to the More Filters Page:
An unknown server-side error occurred while processing the command. Original error: The element is expected to be a valid Picker Wheel control. '(null)' was given instead
running
Error: An unknown server-side error occurred while processing the command.
    at execute("mobile: selectPickerWheelValue", [object Object]) - index.js:312:3

**Comment by mykola-mokhnach** [comment] 2019-02-23 14:02
Please attach the full log. From what I see now there's something wrong with the input arguments received from the client code, so the method call fails

**Comment by LayMuiToh** [comment] 2019-02-23 14:35
https://gist.github.com/LayMuiToh/0411f9c5a0c870534c9f6af58004bfd3

**Comment by LayMuiToh** [comment] 2019-02-23 14:38
I just wonder what is the right value for the element in the command:
  browser.execute('mobile: selectPickerWheelValue', 
          { element: MoreFilters.picker, order: 'next', offset: 0.5});

or 
browser.execute('mobile: selectPickerWheelValue', 
          { element: '~Picker', order: 'next', offset: 0.5});

I set accessibilityLabel 'Picker' to the selectPickerWheel

**Comment by mykola-mokhnach** [comment] 2019-02-23 17:43
The above code won't work. change `MoreFilters.picker` to `MoreFilters.picker.ELEMENT`

**Comment by LayMuiToh** [comment] 2019-02-23 23:15
Thanks, however, the picker didn't move to the next row. this is a separate issue

**Comment by LayMuiToh** [comment] 2019-02-24 04:44
I got this error:
An unknown server-side error occurred while processing the command. Original error: Element id is expected to be set for selectPickerWheelValue method

**Comment by mykola-mokhnach** [comment] 2019-02-24 07:06
Duplicate of https://github.com/appium/appium/issues/12214

**Closed by mykola-mokhnach** 2019-02-24 07:06 UTC
Labels: NeedsInfo, NotABug
