### ISSUE TITLE
[BUG]  iOS Appium “ dragfromtoforduration” function  failed ， while calling this in webdrvieragent（facebook） works well

### ISSUE THREAD

**Issue by huanglik** [appium/appium#7672] opened 2017-01-10 13:11 UTC
when i write test for iOS Appium using  “ dragfromtoforduration” function  
it doesn‘t work
I check the server log of appium， it wronglly changes the “toY” and “toX”  to call wda
client send fromX，fromY（160，85.2） endX，endY（160，511.2）

**but appium changes  the value of  endX，endY to (320, 596.4)**
thus that my test fail   !!!!!!!!

![image](https://cloud.githubusercontent.com/assets/3026388/21807114/0afbeb44-d778-11e6-99c7-60342dee2528.png)

At the same time，i using this command to test wda， it works well

curl -X POST -d '{"fromX": "160", "fromY": "85.2", "toX":"160", "toY":"511.2" ,"duration":"0.8"}' 'http://localhost:8100/session/7EFFFFB1-CA11-48B2-A91D-03B9F62EE251/uiaTarget/0/dragfromtoforduration'

hope appium fix that, thanks a  lot

**Comment by mykola-mokhnach** [comment] 2017-01-10 15:07
Can you paste you code snipped for appium client? Maybe, TouchAction interface just calculates coordinates differently from what you expect?

**Comment by huanglik** [comment] 2017-01-11 03:10
In appium client ， my code is
driver.swipe(160,85.2,160,511.2,800)
it‘s nothing wrong with TouchAction interface 。

you can see the appium server log。
 MSJSONWP prints the right fromX，fromY 、endX，endY
however
JSONWP Proxy changes the value endX，endY

I think problem is in JSONWP Proxy，can you help me？

**Comment by mykola-mokhnach** [comment] 2017-01-11 07:52
Just be kind to provide what I've asked. I won't be able help without the log and full code snippet.

**Comment by huanglik** [comment] 2017-01-11 08:09
appium client
def swipe(self, start_x, start_y, end_x, end_y, duration=None)
this function input arguments here declared is  end_x and end_y (not offset_x, not offset_y)
![image](https://cloud.githubusercontent.com/assets/3026388/21840296/b052e47c-d817-11e6-821a-257d76b99406.png)

however, in appium server, it changes my arguments end_x , end_y
it is end_x, end_y,  not offset x, offset y, ok? 
 Obviously, it's bug of appium  ( appium client code did not change for a long time) 

![image](https://cloud.githubusercontent.com/assets/3026388/21840344/fda024f6-d817-11e6-9a1d-cc9b025ec72d.png)

![image](https://cloud.githubusercontent.com/assets/3026388/21840354/0cdd07e0-d818-11e6-8cba-92e5378493f2.png)

**Comment by mykola-mokhnach** [comment] 2017-01-11 08:42
yes, this might be documentation issue. These values should be calculated as relative offsets to the recent touch point. You 're welcome to push a fix for that.

**Comment by huanglik** [comment] 2017-01-11 09:52
thank you so much
I am looking forward to see the code after you fix that， plesae comment back after you fix ok
thank you so much again

**Comment by jlipps** [comment] 2017-01-19 22:02
@imurchie can you take a look at this? I'm getting more and more confused about whether the appropriate behavior is for the server to deal in absolute or relative values. I thought it was absolute, and then clients could do what they wanted? But in this example it looks like we're doing something wonky that's entirely different from that too.

**Comment by jlipps** [comment] 2017-07-24 17:56
closing as a duplicate of #7486.

**Closed by jlipps** 2017-07-24 17:56 UTC
Labels: Bug, Documentation
