### ISSUE TITLE
Swipe TopToDown execution takes longer than 240000ms and all tests are failed due to time out. 

### ISSUE THREAD

**Issue by chuklov** [appium/appium#14806] opened 2020-10-13 12:41 UTC
## The problem

After upgrade to Xcode 12 and OS Catalina all tests that using the following code are failing due to time out:

`      Map<String, Object> params = new HashMap<>();
        params.put("duration", 0.1);
        params.put("fromX", 100);
        params.put("fromY", 30);
        params.put("toX", 100);
        params.put("toY", 580);
        driver.executeScript("mobile: dragFromToForDuration", params);
`

 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.3
* Last Appium version that did not exhibit the issue (if applicable): 1.17.1
* Desktop OS/version used to run Appium: MAC OS Catalina
* Mobile platform/version under test: iOS 13.6 / iOS 14
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Details

HTTP] {"script":"mobile: dragFromToForDuration","args":[{"duration":0.1,"fromX":100,"toX":100,"fromY":30,"toY":580}]}
[debug] [W3C (36f824c5)] Calling AppiumDriver.execute() with args: ["mobile: dragFromToForDuration",[{"duration":0.1,"fromX":100,"toX":100,"fromY":30,"toY":580}],"36f824c5-a1cc-4a68-9c27-084ff99088bd"]
[debug] [XCUITest] Executing command 'execute'
[XCUITest] Proxying to WDA with an unknown route: POST /wda/dragfromtoforduration
[debug] [WD Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://127.0.0.1:59918/session/C2609ED0-D951-47AF-B53A-7E00CEB46BCB/wda/dragfromtoforduration] with body: {"duration":0.1,"fromX":100,"fromY":30,"toX":100,"toY":580}
[WD Proxy] Error: timeout of 240000ms exceeded
[WD Proxy]     at createError (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/appium-base-driver/node_modules/axios/lib/core/createError.js:16:15)
[WD Proxy]     at RedirectableRequest.handleRequestTimeout (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/appium-base-driver/node_modules/axios/lib/adapters/http.js:264:16)
[WD Proxy]     at Object.onceWrapper (events.js:428:26)
[WD Proxy]     at RedirectableRequest.emit (events.js:321:20)
[WD Proxy]     at ClientRequest.eventHandlers.<computed> (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/follow-redirects/index.js:13:24)
[WD Proxy]     at ClientRequest.emit (events.js:321:20)
[WD Proxy]     at Socket.emitRequestTimeout (_http_client.js:721:9)
[WD Proxy]     at Object.onceWrapper (events.js:427:28)
[WD Proxy]     at Socket.emit (events.js:321:20)
[WD Proxy]     at Socket._onTimeout (net.js:478:8)
[WD Proxy]     at listOnTimeout (internal/timers.js:549:17)
[WD Proxy]     at processTimers (internal/timers.js:492:7)
[debug] [W3C (36f824c5)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
[debug] [W3C (36f824c5)]     at JWProxy.command (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:275:13)
[debug] [W3C (36f824c5)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[HTTP] <-- POST /wd/hub/session/36f824c5-a1cc-4a68-9c27-084ff99088bd/execute/sync 500 60044 ms - 660
[HTTP] 
Current Running Thread Status36f824c5-a1cc-4a68-9c27-084ff99088bd
[HTTP] --> GET /wd/hub/session/36f824c5-a1cc-4a68-9c27-084ff99088bd/screenshot
[HTTP] {}
[debug] [W3C (36f824c5)] Calling AppiumDriver.getScreenshot() with args: ["36f824c5-a1cc-4a68-9c27-084ff99088bd"]
[debug] [XCUITest] Executing command 'getScreenshot'
[debug] [XCUITest] Taking screenshot with WDA
[debug] [WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[debug] [WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:59918/session/C2609ED0-D951-47AF-B53A-7E00CEB46BCB/screenshot] with no body
[debug] [WD Proxy] Got response with status 200: {"value":"iVBORw0KGgoAAAANSUhEUgAABGUAAAmECAIAAAAjR0TuAAAAAXNSR0IArs4c6QAA\r\nAHhlWElmTU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAAB\r\nAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAADYAAAAAQAAANgAAAAB\r\nAAKgAgAEAAAAAQAABGWgAwAEAAAAAQAACYQAAAAAt6JlMwAAAAlwSFlzAAAhOAAA\r\nITgBRZYxYAAAABxpRE9UAAAAAgAAAAAAAATCAAAAKAAABMIAAATCABUpq4tiqMEA\r\nAEAASURBVHgB7L17k23ZVd3JV+m6eVMWtsGYh92Ojm7csrttQCqpqvwvnFNXlcbG\r\nNG5j3LQdDvvevFUIBDYPgUASQs8iAtrQ7zbmpVJV6XP1+I0x59r7PPNk5sn7PBEr\r\ndsw915xjzTX3a45c++z8rm++8Z0r27tvfLi1/f4bH+xoH/7+G1vbd37/jSO0rcFI\r\n+c03PtjadtkfJZgXDOTdf/Thtdo3/9F3Tm1fBg64vq68AJ8jg2+88Z1T25OB5+hQ\r\nnkI9OAN69Gxt259HWx9Se5Tvvv7BrH347uvVfv+1D0/tRhn44PdfqzZLrJL8/vPR\r\nXnv/3al98O5r3T71wbvPQ/vmax/M2vvffK3aN15//8o2c5yDHE2+MoBbGnz9tQ/u\r\noL3/9de6vf7+16f27a+/fkX72mvv32n76qe+faftK5987+jt9z753tb25U++912H\r\nPBJ2840TXzoC/XumGNe1yJKM91GFE5VSBk586cSgZhl42c6Hl2O+W8nSzr/f7aFG\r\nW7tWa/oTX7o9SzzxpafJrFY5z4kv3Z5BNVkSa5rIkuQryJIM7pQsCfxOyZLAj06W\r\nBLiVLEl54ksvGtu5PfU68aUjM8ATX5qxhT0LLy9J18vBH162PxOc+NLtOcy...
[debug] [W3C (36f824c5)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABGUAAAmECAIAAAAjR0TuAAAAAXNSR0IArs4c6QAA\r\nAHhlWElmTU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAAB\r\nAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAADYAAAAAQAAANgAAAAB\r\nAAKgAgAEAAAAAQAABGWgAwAEAAAAAQAACYQAAAAAt6JlMwAAAAlwSFlzAAAhOAAA\r\nITgBRZYxYAAAABxpRE9UAAAAAgAAAAAAAATCAAAAKAAABMIAAATCABUpq4tiqMEA\r\nAEAASURBVHgB7L17k23ZVd3JV+m6eVMWtsGYh92Ojm7csrttQCqpqvwvnFNXlcbG\r\nNG5j3LQdDvvevFUIBDYPgUASQs8iAtrQ7zbmpVJV6XP1+I0x59r7PPNk5sn7PBEr\r\ndsw915xjzTX3a45c++z8rm++8Z0r27tvfLi1/f4bH+xoH/7+G1vbd37/jSO0rcFI\r\n+c03PtjadtkfJZgXDOTdf/Thtdo3/9F3Tm1fBg64vq68AJ8jg2+88Z1T25OB5+hQ\r\nnkI9OAN69Gxt259HWx9Se5Tvvv7BrH347uvVfv+1D0/tRhn44PdfqzZLrJL8/vPR\r\nXnv/3al98O5r3T71wbvPQ/vmax/M2vvffK3aN15//8o2c5yDHE2+MoBbGnz9tQ/u\r\noL3/9de6vf7+16f27a+/fkX72mvv32n76qe+faftK5987+jt9z753tb25U++912H\r\nPBJ2840TXzoC/XumGNe1yJKM91GFE5VSBk586cSgZhl42c6Hl2O+W8nSzr/f7aFG\r\nW7tWa/oTX7o9SzzxpafJrFY5z4kv3Z5BNVkSa5rIkuQryJIM7pQsCfxOyZLAj06W\r\nBLiVLEl54ksvGtu5PfU68aUjM8ATX5qxhT0LLy9J18vBH162PxOc+NLtOcyTRDjx\r\n...
[HTTP] <-- GET /wd/hub/session/36f824c5-a1cc-4a68-9c27-084ff99088bd/screenshot 200 3715 ms - 2483044
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/36f824c5-a1cc-4a68-9c27-084ff99088bd
[HTTP] {}
[debug] [W3C (36f824c5)] Calling AppiumDriver.deleteSession() with args: ["36f824c5-a1cc-4a68-9c27-084ff99088bd"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1602592404076 (15:33:24 GMT+0300 (Israel Daylight Time))
[Appium] Removing session 36f824c5-a1cc-4a68-9c27-084ff99088bd from our master session list
[debug] [WD Proxy] Matched '/session/36f824c5-a1cc-4a68-9c27-084ff99088bd' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /session/36f824c5-a1cc-4a68-9c27-084ff99088bd] to [DELETE http://127.0.0.1:59918/session/C2609ED0-D951-47AF-B53A-7E00CEB46BCB] with no body
[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":null}
[DevCon Factory] Releasing connections for 00008020-001A3D1A0286002E device on any port number
[DevCon Factory] Found cached connections to release: ["00008020-001A3D1A0286002E:59918"]
[DevCon Factory] Releasing the listener for '00008020-001A3D1A0286002E:59918'
[debug] [iProxy@00008020:59918] Closing the connection
[debug] [DevCon Factory] Cached connections count: 0
[debug] [XCUITest] Did not find the temporary XCTest logs root at '/var/folders/4_/y_kblsms2q7_z01z3p84gn_cjbs_9f/T/com.apple.dt.XCTest*/'
[XCUITest] Cleaning test logs in '/Users/chuklova/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs' folder
[debug] [iOS] Clearing log files
[debug] [iOS] Deleting '/Users/chuklova/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs'. Freeing 6.2M.
[debug] [iOS] Finished clearing log files
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1602592405214 (15:33:25 GMT+0300 (Israel Daylight Time))
[debug] [W3C (36f824c5)] Received response: null
[debug] [W3C (36f824c5)] But deleting session, so not returning
[debug] [W3C (36f824c5)] Responding to client with driver.deleteSession() result: null
Oct 13, 2020 3:33:25 PM com.appium.manager.DeviceAllocationManager freeDevice
INFO: DeAllocated Device 00008020-001A3D1A0286002E from execution list
Oct 13, 2020 3:33:25 PM com.context.SessionContext remove
INFO: Removing context for thread - 18
[debug] [W3C (36f824c5)] Destroying socket connection
[HTTP] <-- DELETE /wd/hub/session/36f824c5-a1cc-4a68-9c27-084ff99088bd 200 1141 ms - 14
[HTTP] 
FAILED: weeklyReport
        
Platform: IOS UDID: 00008020-001A3D1A0286002E Name:  Host: 127.0.0.1
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Mac-mini-2.lan', ip: 'fe80:0:0:0:1cae:9b19:1257:827f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_241'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {agentPath: /usr/local/lib/node_modules..., appiumVersion: 1.18.3, automationName: XCUITest, bootstrapPath: /usr/local/lib/node_modules..., browserName: , bundleId: com.apple.mobilesafari, clearSystemFiles: true, databaseEnabled: false, deviceName: iPhone, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, newCommandTimeout: 600, noReset: true, platform: MAC, platformName: ios, platformVersion: 13, preventWDAAttachments: true, showIOSLog: false, showXCODELog: false, takesScreenshot: true, udid: 00008020-001A3D1A0286002E, useNewWDA: false, usePrebuiltWDA: true, wdaLocalPort: 59918, webStorageEnabled: false, webkitDebugProxyPort: 59928, xcodeOrgId: 2ES97B4EP7, xcodeSigningId: iPhone Developer}
Session ID: 36f824c5-a1cc-4a68-9c27-084ff99088bd
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:489)
	at com.appium.tests.ios.SbmUITests.weeklyReport(SbmUITests.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

## Code To Reproduce Issue [ Good To Have ]

      `Map<String, Object> params = new HashMap<>();
        params.put("duration", 0.1);
        params.put("fromX", 100);
        params.put("fromY", 30);
        params.put("toX", 100);
        params.put("toY", 580);
        driver.executeScript("mobile: dragFromToForDuration", params);
`

**Comment by mykola-mokhnach** [comment] 2020-10-13 13:21
We don't do much there except of calling the native `pressForDuration:thenDragToCoordinate:` XCUICoordinate method. To me it looks more like XCTest issue. Could you please check if the issue is reproducible using native XCTest? Is there anything interesting in the device logs?

**Comment by chuklov** [comment] 2020-10-13 13:26
About device - nothing interesting. it is iOS 13.6.1 iPhone XS 
Issue starts after upgrade to Xcode 12. 

Can you please help me and navigate on how to run native XCTest?

**Comment by mykola-mokhnach** [comment] 2020-10-13 13:28
For example https://www.hackingwithswift.com/articles/83/how-to-test-your-user-interface-using-xcode

**Comment by mykola-mokhnach** [comment] 2020-10-13 14:24
I assume this confirms my previous assumption. Please report the issue to Apple. You could try to use W3C actions as a workarounds though

**Comment by mykola-mokhnach** [comment] 2020-10-16 15:47
Closed as third party issue

**Closed by mykola-mokhnach** 2020-10-16 15:47 UTC
Labels: ThirdParty, XCUITest
