### ISSUE TITLE
[uiautomator2] - [MJSONWP] Encountered internal error running command: TypeError: Path must be a string.

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#8165] opened 2017-04-04 10:43 UTC
## The problem

Trying to launch Chrome browser on real device but getting error

[caps]
automationName = "uiautomator2"
platformName = "Android"
platformVersion = "5.1"
deviceName = "placeholder string"
browserName = "Chrome"

## Environment

* Appium version (or git revision) that exhibits the issue:  1.6.4-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac  10.11.6
* Node.js version (unless using Appium.app|exe): v7.6.0
* Mobile platform/version under test:  5.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/vikramvi/427ec95708ede46c7092b64a59478a57

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2017-04-04 12:18
Duplicate of https://github.com/appium/appium/issues/8142

**Closed by mykola-mokhnach** 2017-04-04 12:18 UTC
Labels: NeedsTriage
