### ISSUE TITLE
Appium, Hangs and Hangs!

### ISSUE THREAD

**Issue by reach2jeyan** [appium/appium#8895] opened 2017-07-21 10:39 UTC
I have trouble keeping Appium UI running. When the automation starts and the logs start running in the Appium, It frequently or all the time, hangs and I cannot click on START A NEW SESSION and CLOSE LOGS button. I have to quit the Appium to start it again and this causes proxy error and gives me error code 65 for which I have to restart my device. This is very frustrating and happening in the latest build. I am using the version Version: `1.1.0-beta.4` 

I have no problem with script running but the UI hangs a lot.

**Comment by mykola-mokhnach** [comment] 2017-07-21 13:03
Closed as duplicate of https://github.com/appium/appium/issues/8889

**Closed by mykola-mokhnach** 2017-07-21 13:03 UTC
