### ISSUE TITLE
shouldWaitForQuiescence=false does not work with latest xcode version #iOS #XCODE #XCUITEST

### ISSUE THREAD

**Issue by kwhite5555** [appium/appium#11476] opened 2018-10-03 17:43 UTC
## The problem

The desired capability shouldWaitForQuiescence=false causes the web driver to fail to start on an iPhone. The iPhone will attempt to restart the web driver and this will also fail.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.9.1 on Appium Desktop 1.7.1
* Desktop OS/version used to run Appium: Mac Mojave
* Mobile platform/version under test: iPhone os 11.4 and 12.0

## Details

To reproduce try setting shouldWaitForQuiescence to false in desired capabilities on the appium desktop Inspector.

**Comment by mykola-mokhnach** [comment] 2018-10-03 17:46
Duplicate of 
https://github.com/appium/appium/issues/11464

**Closed by mykola-mokhnach** 2018-10-03 17:46 UTC
