### ISSUE TITLE
chromedriver fails to start sometimes because of adb returns wrong device name 

### ISSUE THREAD

**Issue by moizjv** [appium/appium#5686] opened 2015-10-06 05:54 UTC
``` Sending adb command: host:devices\n[0.033][DEBUG]: Received adb response: 0015emulator-5554\tdevice\n\n[0.033][INFO]: RESPONSE InitSession unknown error: Device emulator-5554 is not online\n[0.033][DEBUG]: Log type \'driver\' lost 0 entries on destruction\n[0.033][DEBUG]: Log type \'browser\' lost 0 entries on destruction\n[0.246][INFO]: COMMAND InitSession {\n   "desiredCapabilities": {\n      "chromeOptions": {\n         "androidDeviceSerial": "emulator-5554",\n         "androidPackage": "io.selendroid.testapp",\n         "androidUseRunningApp": true``` 
^^ above adb returns extra ` 0015emulator-5554\tdevice\n` which is causing test to fail. 

Chromedriver/appium should be able to retry without device name. 

cc @filmaj

**Comment by filmaj** [comment] 2015-10-06 06:02
For more context here, I have only seen this happen on Google-API flavoured emulators, on Android 4.4, 5.0 and 5.1 API levels. In fact, have only swapped out standard stock AOSP images with the Google-y ones to cause this issue. This leads me to believe the error exists in the `adbd` implementation within the Google system images for the Android emulator.

Guess how much fun this one was to figure out!

**Comment by seleniumappiumnewbie** [comment] 2015-10-11 22:05
@moizjv and @filmaj,
Are you saying Appium can't run tests on a real Android device like Nexus 9 on Android 5.1.1?
Please help. I'm confused. From the books, they say Android real device can be tested with Appium. 

I'm seeing the error "A new session could not be created. (Original error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device XYZ is not online"
When I run ads device, my device is recognized though, but not when I run a script on it with Appium.
How can I fix this issue and test with a real Android device?

Thanks for your help.

**Comment by rkrisztian** [comment] 2015-10-15 14:17
The Google API suspicion is not true. Just tried a smoke test with Android 4.4.2 emulator (target: android-19, i.e. no Google APIs), at the 6th attempt I got the same bug. So as you can read the issue has a random reproducibility rate...

**Comment by rkrisztian** [comment] 2015-10-28 19:42
FYI: People recently pointed out in #5616 that ChromeDriver 2.20 fixed the issue for them.

**Comment by doronzRumble** [comment] 2015-11-25 10:31
not for me.... running 2.20.353145 and still get the issue...

**Comment by doronzRumble** [comment] 2015-11-25 10:37
sorry could be my mistake... i wasnt running appium version 1.4.13.... just updated.... will notify if issue returns

**Comment by doronzRumble** [comment] 2015-11-25 12:10
doesn't reproduce for now on 1.4.13. will update if i encounter it again

**Comment by crashbell** [comment] 2016-01-14 18:46
I got the same problem with `1.4.16`

**Comment by ablok** [comment] 2016-02-02 10:29
Having the same issue.

**Comment by PeaceDeveloper** [comment] 2016-02-29 23:16
I installed the windows appium via executable. And to me also happened the same problem reported by the noble colleague.

I solved it this way:
1. First I accessed the folder C:\Program Files (x86)\Appium\node_modules\ appium.
2. I drove the ncu -u. With that all packages will be upgraded to the latest version. I did not notice any side effects with this act.
3. After that, everything started to work in the best possible way.

I hope I have helped someone. :)

**Comment by aaronmagi** [comment] 2016-05-10 23:21
I seem to be getting a similar error.  Has anyone seen a fix?

I can recreate this on 1.4.16.1 on 2 different devices and the same code works fine on another box.

I posted in #6493 6493

**Comment by yahman72** [comment] 2016-09-12 16:06
Same issue here with 1.4.16.1

Failure rate is ~25% for creating appium sessions with chromedriver.

Seems to be some sort of a timing issue:
- the "POST /session" always fails because the device is not found by ADB
- when it works, the device becomes online after 1-2 retries
- when it fails, the device does not become online during the 4 retries

*breaking*
<pre>
2016-09-12 17:24:09:789 - info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
2016-09-12 17:24:09:801 - info: JSONWP Proxy: Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"10.0\"}}}"
2016-09-12 17:24:09:817 - info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"80717aef8315"}}}
2016-09-12 17:24:09:864 - info: JSONWP Proxy: Got response with status 200: {"sessionId":"217cc6596a3bd2c913db2234e8543057","status":13,"value":{"message":"unknown error: Device 80717aef8315 is not online\n  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62...
2016-09-12 17:24:10:075 - info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"80717aef8315"}}}
2016-09-12 17:24:10:092 - info: JSONWP Proxy: Got response with status 200: {"sessionId":"a102e7e760a211fbdd377b79889274e3","status":13,"value":{"message":"unknown error: Device 80717aef8315 is not online\n  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62...
2016-09-12 17:24:10:306 - info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"80717aef8315"}}}
2016-09-12 17:24:10:324 - info: JSONWP Proxy: Got response with status 200: {"sessionId":"08e48e352a6b28595f5f96f7b6e5193b","status":13,"value":{"message":"unknown error: Device 80717aef8315 is not online\n  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62...
2016-09-12 17:24:10:541 - info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"80717aef8315"}}}
2016-09-12 17:24:10:557 - info: JSONWP Proxy: Got response with status 200: {"sessionId":"e755333ba54ccf3f94d8487821e230d8","status":13,"value":{"message":"unknown error: Device 80717aef8315 is not online\n  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62...
2016-09-12 17:24:10:773 - error: Chromedriver: Chromedriver exited unexpectedly with code null, signal SIGTERM
2016-09-12 17:24:10:779 - info: Chromedriver: Changed state to 'stopped'
</pre>

*working*
<pre>
2016-09-12 17:37:05:563 - info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
2016-09-12 17:37:06:069 - info: JSONWP Proxy: Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"10.0\"}}}"
2016-09-12 17:37:06:083 - info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"80717aef8315"}}}
2016-09-12 17:37:06:103 - info: JSONWP Proxy: Got response with status 200: {"sessionId":"995c5e4ff7bb720592315477f7326e73","status":13,"value":{"message":"unknown error: Device 80717aef8315 is not online\n  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62...
2016-09-12 17:37:06:311 - info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"80717aef8315"}}}
2016-09-12 17:37:11:627 - info: JSONWP Proxy: Got response with status 200: {"sessionId":"33ccee973c09957bdda8c83b74ebf8fd","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{},"cssSel...
2016-09-12 17:37:11:628 - info: Chromedriver: Changed state to 'online'
</pre>

WORKAROUND:
This (as already mentioned in #5616 ) seems to work for me: replace the chromedriver.exe ("ChromeDriver 2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a)") from Appium v1.4.16.1 (in .\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win) 
with the chromedriver.exe ("ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4)") from Appium v1.5.2 (.\node_modules\appium-android-driver\node_modules\appium-chromedriver\chromedriver\win)

Upgrading to Appium v1.5.2 should also do the trick, but this was not an option for me.

I'm also running Appium Windows 10 like #6493

**Comment by jlipps** [comment] 2016-09-12 18:51
Since we are not going to patch 1.4.16, I'll go ahead and close this. Upgrading to 1.5.x is your best option at this point.

**Closed by jlipps** 2016-09-12 18:51 UTC
Labels: Android, Bug, Hybrid Apps, Mobile Chrome, NeedsTriage
