### ISSUE TITLE
Appium + Apple Watch

### ISSUE THREAD

**Issue by moskaliukzhanna** [appium/appium#15304] opened 2021-04-26 14:18 UTC
Hi,
currently I am trying to use Appium in order to automate Apple Watch. I have added required targets to WebDriverAgent and made some small changes in XCUITest Driver to make validation pass "watchOS" as platform name and set lover version of platform Version to 7.4. 
So, simulator gets launching using Appium, but :
#1 It launches together with iPhone, however my app (the one I'm trying to launch) is only for Apple Watch.
#2 It launches, when at some point I receive following error: 
**An unknown server-side error occurred while processing the command. Original error: Simulator architecture is unsupported by the '/Users/zhannamoskaliuk/Developer/WatchCountdown/build/Release-watchos/WatchCountdown WatchKit App.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode**

I saw two folders in build folder  Release-watchos and Release-iphoneos . I've tried both paths to .app file, but nether have worked. 
There is my capabilities: 

"deviceName": "Apple Watch Series 5 - 44mm",
  "platformName": "watchOS",
  "platformVersion": "7.4",
  "app": "/Users/zhannamoskaliuk/Developer/WatchCountdown/build/Release-watchos/WatchCountdown WatchKit App.app",
  "noReset": true,
  "automationName": "XCUITest"

Thank you!

**Comment by mykola-mokhnach** [comment] 2021-04-26 14:31
Closed as duplicate of https://github.com/appium/appium/issues/4829

**Closed by mykola-mokhnach** 2021-04-26 14:31 UTC
