### ISSUE TITLE
WebDriverException: Message: u"An unknown server-side error occurred while processing the command. (Original error: Cannot call method 'getLogcatLogs' of null)" 

### ISSUE THREAD

**Issue by meegha** [appium/appium#4209] opened 2014-12-02 14:04 UTC
We found this issue while running test suite for a long time. We collect the logcat after every testcase. I'm including the appium logs also. Could you help to understand what could possibly be the reason for it, because we came across this issue after long run of the suite. After this error, the following all testcases weren't executed and threw the same error.

Appium Logs:
info: --> POST /wd/hub/session/48f85605-7593-437e-8743-c167cff370bc/log "sessionId":"48f85605-7593-437e-8743-c167cff370bc","type":"logcat"}
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Cannot call method 'getLogcatLogs' of null)","origValue":"Cannot call method 'getLogcatLogs' of null"},"sessionId":"48f85605-7593-437e-8743-c167cff370bc"}
info: <-- POST /wd/hub/session/48f85605-7593-437e-8743-c167cff370bc/log 500 3.63
3 ms - 272
info: --> GET /wd/hub/session/48f85605-7593-437e-8743-c167cff370bc/screenshot {}

info: <-- GET /wd/hub/session/48f85605-7593-437e-8743-c167cff370bc/screenshot 50
0 3.435 ms - 88
TypeError: Cannot call method 'shell' of null at async.series.cb.status(C:\Users\ssunadax\Documents\appium_v1.3.4-beta1\n
ode_modules\appium\lib\devices\android\android-controller.js:547:16)
    at C:\Users\ssunadax\Documents\appium_v1.3.4-beta1\node_modules\appium\node_
modules\async\lib\async.js:610:21
    at C:\Users\ssunadax\Documents\appium_v1.3.4-beta1\node_modules\appium\node_
modules\async\lib\async.js:249:17
    at iterate (C:\Users\ssunadax\Documents\appium_v1.3.4-beta1\node_modules\app
ium\node_modules\async\lib\async.js:149:13)
    at async.eachSeries (C:\Users\ssunadax\Documents\appium_v1.3.4-beta1\node_mo
dules\appium\node_modules\async\lib\async.js:165:9)
    at _asyncMap (C:\Users\ssunadax\Documents\appium_v1.3.4-beta1\node_modules\a
ppium\node_modules\async\lib\async.js:248:13)
    at Object.mapSeries (C:\Users\ssunadax\Documents\appium_v1.3.4-beta1\node_mo
dules\appium\node_modules\async\lib\async.js:231:23)
    at Object.async.series (C:\Users\ssunadax\Documents\appium_v1.3.4-beta1\node
_modules\appium\node_modules\async\lib\async.js:608:19)
    at androidController.getScreenshot (C:\Users\ssunadax\Documents\appium_v1.3.
4-beta1\node_modules\appium\lib\devices\android\android-controller.js:542:9)
    at Object.exports.getScreenshot [as handle](C:UsersssunadaxDocumentsapp
ium_v1.3.4-beta1node_modulesappiumlibservercontroller.js:854:14)
info: --> POST /wd/hub/session {"desiredCapabilities":{"deviceName":"Nexus 5","s
cale":1,"udid":"05b31e85004546a2","driverUrl":"http://127.0.0.1:4725/wd/hub","ne
wCommandTimeout":"360","appPackage":"com.intel.iso.pa.amsg","platformName":"Andr
oid","appActivity":"com.intel.iso.pa.amsg.EntranceActivity"}}
info: Client User-Agent string: Python-urllib/2.7
error: Failed to start an Appium session, err was: Error: Requested a new session but one was in progress
info: [debug] Error: Requested a new session but one was in progress

**Comment by vasudarch** [comment] 2015-01-15 17:36
Because of this issue, not able to run the test for long time.

**Comment by naveenjammula** [comment] 2015-01-27 07:56
can you please update the fix on this issue ??

**Comment by moizjv** [comment] 2015-04-22 23:44
@naveenjammula  @meegha  are you still facing this issue?

**Comment by vasudarch** [comment] 2015-04-22 23:52
This issue still exists

**Comment by moizjv** [comment] 2015-04-23 00:06
@vasudarch does it happen after a long test run or it does not work at all?

**Comment by vasudarch** [comment] 2015-04-23 00:11
@moizjv , the issue happen while running the script using appium GUI or command line for long duration(more than 1 hour).

**Comment by moizjv** [comment] 2015-04-23 00:27
@vasudarch i see let me try to reproduce it.

**Comment by sebv** [comment] 2015-06-03 17:32
Moving to bug: improve stability. That should be part of 1.5.

**Comment by jlipps** [comment] 2016-02-18 23:13
can you try running with the appium 1.5 beta and see if it works there?

**Closed** 2016-11-09 19:26 UTC
Labels: Bug
