### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'Appium' and platformName 'Android'. Please check your desired capabilities.

### ISSUE THREAD

**Issue by aaswissa** [appium/appium#12421] opened 2019-04-01 15:38 UTC
B"H

I've just upgraded from 1.10.0 to 1.12.0.
Tried to ran these capabilities:

{
  "automationName": "Appium",
  "platformName": "Android",
  "platformVersion": "8.1.0",
  "deviceName": "Galaxy Tab A (2016)",
  "app": "C:\\Users\\Public\\app-qa-debug.apk",
  "noReset": "true",
  "fullReset": "false",
  "appActivity": "net.balink.appsterix.ui.activities.MainActivity",
  "appPackage": "net.balink.appsterix.qa"
}

and got this error:

An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'Appium' and platformName 'Android'. Please check your desired capabilities.

I've uninstalled 1.12.0 and install 1.10.0 and issue solved!

Best,

**Comment by mykola-mokhnach** [comment] 2019-04-01 15:41
Duplicate of https://github.com/appium/appium/issues/12408

**Closed by mykola-mokhnach** 2019-04-01 15:41 UTC
