### ISSUE TITLE
App installed on emulator but no launched

### ISSUE THREAD

**Issue by pabloleal1** [appium/appium#15084] opened 2021-02-04 20:59 UTC
Hi all, 

I'm trying to automate an .app using appium  (The version 1.20.2) with a emulator. Once I click on 'Start session' from appium desktop, I get the error mentioned (Log section).

Capability: 
  "deviceName": "iPhone 11 Pro Max",
  "platformName": "iOS",
  "platformVersion": "14.4",
  "app": "/Users/bacardi/Desktop/xxx.app",
  "noReset": false,
  "automationName": "XCUITest",
  "xcodeOrgId": "xxxxxxxxxx",
  "xcodeSigningId": "iPhone Developer",
  "fullReset": true,
  "showXcodeLog": true

Log section:
WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[Xcode] 2021-02-04 21:44:22.334 xcodebuild[5798:138983] [MT] IDETestOperationsObserverDebug: (7FA70837-1D87-456C-A3DF-E9FE89886036) Finished requesting crash reports. Continuing with testing.
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] *** If you believe this error represents a bug, please attach the result bundle at /Users/bacardi/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2021.02.04_21-43-45-+0100.xcresult
[Xcode] 
[Xcode] 
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[Xcode] 2021-02-04 21:44:56.183 xcodebuild[5798:138983] [MT] IDETestOperationsObserverDebug: 65.515 elapsed -- Testing started completed.
[Xcode] 2021-02-04 21:44:56.184 xcodebuild[5798:138983] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[Xcode] 
[Xcode] 2021-02-04 21:44:56.184 xcodebuild[5798:138983] [MT] IDETestOperationsObserverDebug: 65.515 sec, +65.515 sec -- end
[Xcode] 
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[Xcode] 
[Xcode] Test session results, code coverage, and logs:
[Xcode] 	/Users/bacardi/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2021.02.04_21-43-45-+0100.xcresult
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 	Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator.
[Xcode] 	Building for iOS Simulator, but the embedded framework 'YYCache.framework' was built for iOS + iOS Simulator.
[Xcode] 	Building for iOS Simulator, but the linked and embedded framework 'YYCache.framework' was built for iOS + iOS Simulator.
[Xcode] 	Building for iOS Simulator, but the linked and embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator.
[Xcode] 	WebDriverAgentRunner:
[Xcode] 		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/bacardi/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2021.02.04_21-43-45-+0100.xcresult. (Underlying Error: Cannot launch simulated executable: no file found at /Users/bacardi/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app))
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 

Any help will very welcome!! Thanks in advance

**Comment by mykola-mokhnach** [comment] 2021-02-04 21:03
Are you sure you use the latest version and there are no leftovers from previous installs?  The recent version does not build WDA frameworks anymore

**Comment by pabloleal1** [comment] 2021-02-05 07:49
@mykola-mokhnach thanks for the reply!! :) any suggestions? Cause it's breaking my mind

**Comment by mykola-mokhnach** [comment] 2021-02-05 07:53
Make a clean server install or try it on another machine.

**Comment by pabloleal1** [comment] 2021-02-05 07:56
Hi @mykola-mokhnach once again, Thanks you ever so much! I'll let you know if it works! :-)

**Comment by mykola-mokhnach** [comment] 2021-02-09 07:49
Closed as not an issue

**Closed by mykola-mokhnach** 2021-02-09 07:49 UTC
Labels: NeedsInfo, NotABug

**Comment by barnie-xero** [comment] 2021-02-10 04:10
@pabloleal1 I am getting the same error. Did you had any luck with it?

**Comment by pabloleal1** [comment] 2021-02-10 08:10
@barnie-xero no yet :( Even installing the latest version of appium (Deleting all appium previously). I continue investigating about that, so if find any solution, please could you let me know? Thanks!!

**Comment by barnie-xero** [comment] 2021-02-10 22:30
@pabloleal1 I managed to get mine working by deleting the app and deleting the leftover files and then install 1.20 version of Appium . You can follow this document on how to delete the leftover file if you are not sure - https://mackeeper.com/blog/post/521-delete-software-leftovers-mac/

**Comment by mykola-mokhnach** [comment] 2021-02-13 08:50
Sorry, I had to delete the link above, because the software mentioned in it is known as [scareware](https://en.wikipedia.org/wiki/Scareware)

**Comment by mykola-mokhnach** [comment] 2021-02-13 09:10
Linking https://github.com/appium/appium/issues/14102

**Comment by AliciaValladares** [comment] 2022-05-11 07:34
@pabloleal1 Any update in this issue? I have the same problem

**Comment by okanulkr** [comment] 2022-06-15 14:39
> @pabloleal1 Any update in this issue? I have the same problem

There is a loopback adapter related issue. Just change `host` to `127.0.0.1` instead of `0.0.0.0`.  

![Screen Shot 2022-06-15 at 17 37 38](https://user-images.githubusercontent.com/31420008/173854645-e5db461c-89a7-4396-a5f6-0c93a58f3505.png)

**Comment by fustodexcom** [comment] 2023-10-24 04:59
I think, the issue is because you have enter a wrong bundle Idenrtifier of your app.. regards

**Comment by jane-aug** [comment] 2023-11-19 00:08
> > @pabloleal1 Any update in this issue? I have the same problem
> 
> There is a loopback related issue. Just change `host` to `127.0.0.1` instead of `0.0.0.0`.
> 
> ![Screen Shot 2022-06-15 at 17 37 38](https://user-images.githubusercontent.com/31420008/173854645-e5db461c-89a7-4396-a5f6-0c93a58f3505.png)

and don't forget to change the port
