### ISSUE TITLE
send_keys does not work on UISecureTextField on iOS Simulator

### ISSUE THREAD

**Issue by laxmiskava** [appium/appium#4622] opened 2015-03-01 07:37 UTC
I am using Appium 1.3.5/iOS 8.1/xcode 6.1.1 and Ruby 2.2
I am getting weird issue. I am trying to send_keys to UISecureTextfield it does not even recognize that field. However in the same screen I have two  UISecureTextfields, it sends value in the first one, when it comes to next it throws the below error.

info: [debug] [INST] 2015-02-28 07:09:03 +0000 Debug: target.frontMostApp().elements()[0].elements()[1].elements()[6].elements()[0] - scrollToVisible cannot be used because this element has no scrollable ancestor.

---

After doing a lot of research and trying all possible ways, I am still unable to send_keys to this field. Is this Appium bug? Can anyone help me on this issue.

Thanks.

**Comment by sebv** [comment] 2015-03-09 15:53
Looks like the issue is `scrollToVisible` rather than `sendKeys`. You could try `setImmediateValue`, or at worse a native script in `execute`.

ping @bootstraponline, this is related to ruby lib.

**Comment by bootstraponline** [comment] 2015-03-09 21:49
Please post the Ruby code you're using to send the keys. Also post the full appium server log as a gist. I'm pretty sure this isn't ruby specific if the standard send keys endpoint is being used.

**Comment by laxmiskava** [comment] 2015-04-20 18:38
Here is snippet:
 $driver.find_element(:xpath, '//UIAApplication[1]/UIAWindow[1]/UIATableView[1]/UIATableCell[6]/UIASecureTextField[1]/UIASecureTextField[1]').send_keys 'qwertyu'
 If I directly send this with xpath it doesnt send_keys, and throws error "target.frontMostApp().elements()[0].elements()[1].elements()[6].elements()[0] - scrollToVisible cannot be used because this element has no scrollable "
So, the workaround I am doing is first tap on that field,and then send_keys. 
Even if I try using this it doesnt work.
 steps %Q{
  Then I enter "qwertyy" into field of "create_account.password"
  }
Which is defined in my .yml file, however the above statement doesnt work.

**Comment by sebv** [comment] 2015-04-21 08:08
We also need the server log.

**Comment by sebv** [comment] 2015-06-04 06:00
Possible bugs, we need to doublecheck this.

**Comment by imurchie** [comment] 2017-07-18 15:52
Closing as fixed.

**Closed by imurchie** 2017-07-18 15:52 UTC
Labels: Bug, iOS
