### ISSUE TITLE
Seeing `AX error -25205` name/value put for each element in inspector after update to 1.7.1

### ISSUE THREAD

**Issue by mojojojo94** [appium/appium#9474] opened 2017-10-17 17:57 UTC
## The problem

After updating appium to 1.7.1, the appium Inspector now shows all of the elements in my app as having the name and value of `AX error -25205`. I've never seen this error before, googling it brought no search results related to the issue. 

Here is a picture to make of the issue.
![screen shot 2017-10-17 at 12 10 53 pm](https://user-images.githubusercontent.com/15100526/31680708-bb1deb32-b33a-11e7-8611-a4f8f6d53022.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: macOS Sierra 10.12.16
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 9.3
* Real device or emulator/simulator: iPhone 6 Plus
* Appium CLI or Appium.app|exe: Version 1.2.4 (1.2.4.603)

## Link to Appium logs

https://gist.github.com/mojojojo94/ea457f9d8df3cc5bca79b360db8df9e2

the logs also show this `http://localhost:8100/session/9571DC1B-B63F-4B00-B050-D2C4FCA9A3D5/elements] with body: {"using":"xpath","value":"(//XCUIElementTypeCell[@name=\"AX error -25205\"])[4]"}`

**Comment by mykola-mokhnach** [comment] 2017-10-17 18:10
Duplicate of https://github.com/facebook/WebDriverAgent/issues/703

**Closed by mykola-mokhnach** 2017-10-17 18:10 UTC

**Comment by mojojojo94** [comment] 2017-10-17 19:28
Thank you for referencing!
