### ISSUE TITLE
Appium 1.6.3 fails to launch app under test in real device

### ISSUE THREAD

**Issue by LeicaAPiQ** [appium/appium#7690] opened 2017-01-13 09:32 UTC
## The problem

I am running my test suit using appium on a real iPhone. Few tests would run fine and after that Appium fails to launch the app under test. No matter what i do from here on appium doesn't launch the app. It just launches the WebDriverAgentRunner app and gets stuck there. If I restart the phone then all starts to work fine but again only for few tests.

Please help. Thanks in advance

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Desktop OS/version used to run Appium: 10.11.6 (OSX EL Capitan)
* Node.js version (unless using Appium.app|exe): v7.4.0
* Mobile platform/version under test: 10.2
* Real device or emulator/simulator: Real device (iPhone 5C)
* Appium CLI or Appium.app|exe: Running appium from terminal and installed the appium using npm

## Link to Appium logs

https://gist.github.com/LeicaAPiQ/89f2672c7911f80c5b6234579bbebd08

**Comment by mykola-mokhnach** [comment] 2017-01-13 09:38
I saw this issue reported once. Try to keep WDA running on the device after each test instead of reinstalling it (which is the default behaviour). These capabilities might help:
**usePrebuiltWDA** (set it to _true_)
**useNewWDA** (set it to _false_)

[Here](https://github.com/appium/appium-xcuitest-driver#usage) you can find more detailed description about their purpose.

**Comment by LeicaAPiQ** [comment] 2017-01-13 10:55
@mykola-mokhnach I tried with suggested capabilities. Still the same issue.
Please find the logs with the capabilities as usePrebuiltWDA as true and useNewWDA as false
https://gist.github.com/LeicaAPiQ/a4e48a1c10e1e4aec1921b54217f9bab

**Comment by mykola-mokhnach** [comment] 2017-01-13 11:23
Try to restart your phone and update appium submodules to the most recent version:

```
npm remove -g appium && npm install -g appium --no-shrinkwrap
```

then restart your tests

**Comment by LeicaAPiQ** [comment] 2017-01-23 09:00
@mykola-mokhnach I have removed the appium and installed as you suggested. Still i am facing the same issue. Few tests would run fine after that appium fails to launch the app under test. I have attached the logs. Please need you help. Been stuck with this issue for quite a while now.

https://gist.github.com/LeicaAPiQ/a2427d1ffffd39a077a9328df717a414

**Comment by kenmcc** [comment] 2017-01-23 12:06
This sounds like a duplicate of the bug where WDA fails to launch after a few successful tests, https://github.com/facebook/WebDriverAgent/issues/446 or https://github.com/facebook/WebDriverAgent/issues/355

It's also listed in Appium as an issue https://github.com/appium/appium/issues/7192

Do you also see the black screen with battery in the corner?

WDA team say it's an XCODETEST bug, nothing they can do unless apple fixes it.

**Comment by LeicaAPiQ** [comment] 2017-01-23 14:49
@kenmcc Thanks for the update. Yes I see the black screen with battery in the corner. Is there any alternative for now till this issue is fixed ??

**Comment by kenmcc** [comment] 2017-01-23 15:10
Other than rebooting the device, the recommendation seems to be to leave WDA running as long as possible, if possible.

**Comment by jlipps** [comment] 2017-01-23 18:49
Closing as dupe of #7192, thanks @kenmcc

**Closed by jlipps** 2017-01-23 18:49 UTC
Labels: NeedsTriage
