### ISSUE TITLE
Appium doesn't use iOS simulator after first test completed

### ISSUE THREAD

**Issue by donhathuy** [appium/appium#11717] opened 2018-11-21 15:56 UTC
## The problem

I use Appium in Ruby together with Cucumber. After the first test runs completely, there's no error and the iOS simulator is still open. However, on the second run, the simulator just disappear then reopen, the application (or Safari app) doesn't open. The interesting part is the test still running somewhere, but it's not seen on the simulator like the first run. To avoid this issue, I must quit the simulator and let Appium open the new one, but it's very annoying.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.9.1
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): use Appium.app
* Mobile platform/version under test: iOS 12.1 / 12.0 - Mac OS Mojave
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details

It works smoothly with appium v 1.9.1 until I upgrade Mac OS to Mojave and Xcode version to 10.1

## Link to Appium logs
Appium log
https://gist.github.com/donhathuy/82fef594cf8e1a97f7c057b2fbe6bf6a

I suspect this part:
[debug] [RemoteDebugger] Selecting application
[debug] [RemoteDebugger] Current applications available:
[debug] [RemoteDebugger]     Application: 'PID:15166'
[debug] [RemoteDebugger]         id: "PID:15166"
[debug] [RemoteDebugger]         isProxy: false
[debug] [RemoteDebugger]         name: "Safari"
[debug] [RemoteDebugger]         bundleId: "com.apple.mobilesafari"
[debug] [RemoteDebugger]         hostId: undefined
[debug] [RemoteDebugger]         isActive: 2
[debug] [RemoteDebugger]         isAutomationEnabled: false
[debug] [RemoteDebugger]     Application: 'PID:15170'
[debug] [RemoteDebugger]         id: "PID:15170"
[debug] [RemoteDebugger]         isProxy: true
[debug] [RemoteDebugger]         name: "com.apple.WebKit.WebContent"
[debug] [RemoteDebugger]         bundleId: "com.apple.WebKit.WebContent"
[debug] [RemoteDebugger]         hostId: "PID:15166"
[debug] [RemoteDebugger]         isActive: 1
[debug] [RemoteDebugger]         isAutomationEnabled: false
[debug] [RemoteDebugger] Found app id key 'PID:15166' for bundle 'com.apple.mobilesafari'
[debug] [RemoteDebugger] Found separate bundleId 'com.apple.WebKit.WebContent' acting as proxy for 'com.apple.mobilesafari', with app id 'PID:15170'
[debug] [RemoteDebugger] Trying out the possible app ids: PID:15170

Please help me to fix this issue.

**Comment by mykola-mokhnach** [comment] 2018-11-21 16:39
This seems to be an Xcode problem. You can use fullReset capability to resetSimulator before each test.

Closed as duplicate of https://github.com/appium/appium/issues/11621

**Closed by mykola-mokhnach** 2018-11-21 16:39 UTC
