### ISSUE TITLE
Please add capability to force/prefer jsnwp protocol

### ISSUE THREAD

**Issue by kool79** [appium/appium#11523] opened 2018-10-12 14:13 UTC
## The problem
  See #11510
The reason while   #11510 occured is that appium started to use W3C protocol. This cause issues with `isDisplayed` and `getAttribute` methods when remote end use the original java-client by SeleniumHQ: thoise commands work incorrectly in w3c mode.
  Currently there are no option to fallback to jsonwp protocol.
Can you please add capability (or command-line option) to force (or prefer)  protocol jsonwp?

**Comment by mykola-mokhnach** [comment] 2018-10-12 14:35
Actually, the protocol is based on which properties the client is providing in createSession request. If you want the protocol to be mjsonwp then you probably need to patch the createSession request. See https://github.com/appium/java-client/blob/02aa5d5d700da9f44068a1ce15e43ae4f5cded71/src/main/java/io/appium/java_client/remote/NewAppiumSessionPayload.java#L124 for more details.

**Comment by mykola-mokhnach** [comment] 2018-11-08 08:16
Duplicate of https://github.com/appium/appium/issues/11599

**Closed by mykola-mokhnach** 2018-11-08 08:16 UTC
Labels: Enhancement
