### ISSUE TITLE
XCUITest isDisplayed function does not work

### ISSUE THREAD

**Issue by switch201** [appium/appium#14045] opened 2020-03-09 16:16 UTC
## The problem

When running automated tests through webdriver/appium and using the XCUITest IOS version 13.3

The isDisplayed function will always return false for elements that are clearly waited for an on the screen. This issue does not occur when doing android testing with UIAutomator2. This issue only seems to occur with XCUITest.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MAC OS
* Node.js version (unless using Appium.app|exe):13.3.0
* Npm or Yarn package manager: Yarn
* Mobile platform/version under test: IOS 13.3
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium server with webdriver IO

## Details

IsDisplayed never returns true for any of the elements in the app. but clicking and other functions of the like still work.

## Link to Appium logs
Will add later

## Code To Reproduce Issue [ Good To Have ]

spin up an environment equal to the one I provided above and attempt to check for element visibility with the isDisplayed method

**Comment by mykola-mokhnach** [comment] 2020-03-09 18:49
Duplicate of https://github.com/appium/appium/issues/13745

**Closed by mykola-mokhnach** 2020-03-09 18:49 UTC
