### ISSUE TITLE
Appium on Android - SendKeys to EditText also types default text

### ISSUE THREAD

**Issue by nimesh2207** [appium/appium#6443] opened 2016-04-28 10:45 UTC
## Problem

While using Sendkeys to Textbox having default value, sendkey sets old default value and provided value.
Example:
Text Field with Default value : 3
element.Sendkeys("12");

after execution of above line, it sets value as "312"
## Environment

Appium exe version : 1.4.13
OS:  Windows 7
Mobile OS: Android
Device: Real Device & Emulator
Appium Java CLI: 2.1.0

**Comment by imurchie** [comment] 2016-04-28 11:08
Can you try Appium 1.5.2?

And can you provide the Appium server logs? Without them it is not possible to tell what is going on.

**Comment by kcinman11358** [comment] 2016-04-28 16:06
I don't see a problem with that. You are sending keys to a field that has something in it.

I would suggest clearing the textbox first with element.clear(), then sending keys

**Comment by nimesh2207** [comment] 2016-04-29 05:27
Thanks for reply..
@imurchie .. 1.5.2 is not available in Appium.exe version. log are same as which are for other sendkeys() event
@kcinman11358 ..The text field is with some default value, so while i m using elemetn.clear() then also once statement is executed, it sets default value to text box.

**Comment by nimesh2207** [comment] 2016-04-29 06:45
Earlier, Same issue was introduced on this forum #3662. issue still exist but thread on that issue are inactive since long time, so i have introduced new thread.

**Comment by nimesh2207** [comment] 2016-05-10 09:29
@imurchie @triager  any solution or update?

**Comment by imurchie** [comment] 2016-05-10 15:10
I still don't see any logs. We need the server logs in order to diagnose.

**Comment by TFry** [comment] 2016-06-15 17:04
@imurchie 

Here is a log from my app. Basically I am inputting 10, 20, and 30 for three send_keys calls respectively into a popover. 
The result on my app is:
10
1020
102030

Rather than the expected:
10
20
30

Gist: https://gist.github.com/TFry/d853ce309c825dfd297d7a395b061efd

**Comment by imurchie** [comment] 2016-06-15 20:15
This is by design. You need to remove the old text yourself (using `clear`) and then enter new text.

**Comment by TFry** [comment] 2016-06-15 22:55
Thanks for the quick reply, that is good to know.

Two questions that brings up however:
1) The clear text function does not appear to be implemented in Ruby. 
2) See this bug https://github.com/appium/appium/issues/6433

**Comment by nimesh2207** [comment] 2016-06-16 06:39
@imurchie @TFry 
in java library, clear is there. but if Android Application is designed in such a way that text has some default non zero value then you will face above issue. coz after clear also some default assigned to text box will be there.

**Example:**

TextBox default value: 3
element.clear();
element.sendKeys("45");

in above example, after execution of clear statement value 3 will get assigned to the textbox and after sendkeys statement final value to the textbox will be "345"

**Comment by nimesh2207** [comment] 2016-06-16 06:40
@imurchie @TFry 
I am not sure whether issue with the Appium or its an android behavior but that issue exist.

**Comment by mykola-mokhnach** [comment] 2018-08-13 18:26
Closed as obsolete

**Closed by mykola-mokhnach** 2018-08-13 18:26 UTC
Labels: Android, Bug, P2
