### ISSUE TITLE
ValueError: No JSON object could be decoded while running ./Scripts/bootstrap.sh -d

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/appium#12656] opened 2019-05-17 11:07 UTC
Getting below error when I try to run ./Scripts/bootstrap.sh -d command in WebDriverAgent folder in Appium-XCUItest-driver folder. I have tried the same with Appium-Desktop and Appium CLI 1.13.0, 1.12.1 and 1.11.0 version and observed the same error.

> HYDERABADPC01:WebDriverAgent chippas$ ./Scripts/bootstrap.sh -d
> Fetching dependencies
> Usage: simctl list [-j | --json] [devices|devicetypes|runtimes|pairs]
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
>     **kw)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac High Sierra 10.13.6
* Node.js version (unless using Appium.app|exe): v12.1.0
* Npm or Yarn package manager: v6.9.0
* Mobile platform/version under test: iOS/11.4.1
* Real device or emulator/simulator: Real Device/ iPhone 8 Plus
* Appium CLI or Appium.app|exe: Appium CLI and Desktop as well

## Details
* Carthage Version: 0.33.0

**Comment by mykola-mokhnach** [comment] 2019-05-17 11:14
The problem is known and is fixed in appium@beta. Closed as duplicate of https://github.com/appium/appium/issues/12586

**Closed by mykola-mokhnach** 2019-05-17 11:14 UTC
