### ISSUE TITLE
Unexpected crash on iOS with 'undefined is not a function' error

### ISSUE THREAD

**Issue by glorylo** [appium/appium#5483] opened 2015-08-07 18:00 UTC
I found an unexpected crash error on 1.4.8 for iOS.  I am using the real device for testing.

 Here's the trace log:

```
info: [debug] Socket data received (8192 bytes)
info: [debug] Socket data received (8192 bytes)
info: [debug] Socket data received (3830 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"POF","label":"POF","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":20,"width":320,"height":548},">":[{"UIAWindow":{"@":{"name":"mainPOFWindow","label":null,"value":null,"dom":null,"enabled":true,
info: [debug] Responding to client with success: {"status":0,"value":"Successfully launched the app.","sessionId":"d8c1d9d1-a93d-4478-878d-e6059041002a"}
info: <-- POST /wd/hub/session/d8c1d9d1-a93d-4478-878d-e6059041002a/appium/app/launch 200 7524.688 ms - 104 {"status":0,"value":"Successfully launched the app.","sessionId":"d8c1d9d1-a93d-4478-878d-e6059041002a"}


info: --> POST /wd/hub/session/d8c1d9d1-a93d-4478-878d-e6059041002a/timeouts/implicit_wait {"ms":4000}


info: [debug] Set iOS implicit wait to 4000ms
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"d8c1d9d1-a93d-4478-878d-e6059041002a"}
info: <-- POST /wd/hub/session/d8c1d9d1-a93d-4478-878d-e6059041002a/timeouts/implicit_wait 200 0.905 ms - 76 {"status":0,"value":null,"sessionId":"d8c1d9d1-a93d-4478-878d-e6059041002a"}
info: --> POST /wd/hub/session/d8c1d9d1-a93d-4478-878d-e6059041002a/element {"using":"xpath","value":"//UIANavigationBar[1]/UIAStaticText[@label='POF']","locator":"xpath"}
info: [debug] Waiting up to 4000ms for condition
info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
info: [debug] Sending command to instruments: au.mainApp().getTreeForXML()


info: [debug] [INST] 2015-08-07 17:52:42 +0000 Debug: Got new command 3 from instruments: au.mainApp().getTreeForXML()

I found an unexpected crash error on 1.4.8


info: [debug] [INST] 2015-08-07 17:52:42 +0000 Debug: evaluating au.mainApp().getTreeForXML()


error: uncaughtException: undefined is not a function date=Fri Aug 07 2015 10:52:42 GMT-0700 (PDT), pid=42535, uid=250102063, gid=1734589574, cwd=/Applications/Appium.app/Contents/Resources/node_modules/appium, execPath=/Applications/Appium.app/Contents/Resources/node/bin/node, version=v0.12.7, argv=[/Applications/Appium.app/Contents/Resources/node/bin/node, /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js, --command-timeout, 7200, --session-override, --debug-log-spacing, --platform-version, 8.3, --platform-name, iOS, --app, com.pof.mobileapp.iphone, --udid, 004ef4691eb400362b9dfc1fa8c8204066409a5d, --show-ios-log, --device-name, iPhone 5s, --native-instruments-lib], rss=178618368, heapTotal=153500416, heapUsed=125309456, loadavg=[1.41650390625, 1.5361328125, 1.494140625], uptime=2791031, trace=[column=24, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js, function=null, line=1292, method=null, native=false, column=13, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=Object.async.until, line=712, method=async.until, native=false, column=23, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=null, line=708, method=null, native=false, column=19, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js, function=null, line=1286, method=null, native=false, column=20, file=fs.js, function=null, line=263, method=null, native=false, column=15, file=fs.js, function=FSReqWrap.oncomplete, line=95, method=oncomplete, native=false], stack=[TypeError: undefined is not a function,     at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js:1292:24,     at Object.async.until (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:712:13),     at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:708:23,     at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js:1286:19,     at fs.js:263:20,     at FSReqWrap.oncomplete (fs.js:95:15)]


Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --session-override --debug-log-spacing --platform-version "8.3" --platform-name "iOS" --app "com.pof.mobileapp.iphone" --udid "004ef4691eb400362b9dfc1fa8c8204066409a5d" --show-ios-log --device-name "iPhone 5s" --native-instruments-lib

```

**Comment by sebv** [comment] 2015-08-09 17:19
Not too sure, could you provide the full log.

Looks like `undefined is not a function` is caused by the screenshot.

**Comment by glorylo** [comment] 2015-08-13 21:58
hard to reproduce this one.  What I do is try to get a screenshot on error and this occurs sporadically.  Possibly on failed launching the app, which I see frequently if the app is already opened.  It will fail launch and possibly when i try to take a screenshot it is likely the culprit.  It does not always occur so it's hard to track down.

**Comment by glorylo** [comment] 2015-08-27 20:54
here's the crash log:  https://gist.github.com/glorylo/2fea457ebb75f1c3e288

**Comment by SrinivasanTarget** [comment] 2016-04-08 12:40
@glorylo please give a try in our current architecture.Install appium using npm install -g appium.Raise a new issue with logs inform of gist incase of any challenges/errors been faced.Closing this for now.

**Comment by SrinivasanTarget** [comment] 2016-04-08 12:41
@triager please close

**Closed by SrinivasanTarget** 2016-04-08 12:41 UTC
Labels: iOS, LogRequested, OnGoing
