### ISSUE TITLE
driver.closeApp() & driver.launchApp() not working as expected in iOS 15.2 & Appium 1.23 beta

### ISSUE THREAD

**Issue by narasimhanukala** [appium/appium#16287] opened 2021-12-30 16:55 UTC
## The problem

There is a requirement for me to close and launch the app i.e. Kill and Launch the App during the execution to refresh the some settings of app.
to achieve this i was calling 
driver.closeApp()  -- To Close/Kill the app
driver.launchApp() -- To Launch the app again from Home Screen

in earlier versions (iOS 14.7 and Appium 1.18, Appium 1.21), 
driver.closeApp()-- Closes/Kills the app on the screen (i.e. app is not visible on the scren). and 
driver.launchApp() -- Re launches the app again on the screen

but in latest version (iOS 15.2, and Appium 1.23 beta),
driver.closeApp()-- Doesn't closes (doesnt kill) the app i.e. app still visible on the screen (but instead Automation overlay gets disappeared from the app screen). and 
driver.launchApp() -- Doesn't Re launches the app instead application will be on same screen where driver.closeApp()  method is called and Automation overlay gets appeared on the app screen
## Environment

* Appium version (or git revision) that exhibits the issue: 1.23.0-beta.0
* Last Appium version that did not exhibit the issue (if applicable): 1.21, 1.18.1
* Desktop OS/version used to run Appium: Mac OS Monterey
* Mobile platform/version under test: iOS 15.2 
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

is there a way we can achieve the Killing the app in iOS 15.2?

**Comment by mykola-mokhnach** [comment] 2021-12-30 18:10
Duplicate of https://github.com/appium/appium/issues/16051

**Closed by mykola-mokhnach** 2021-12-30 18:10 UTC

**Comment by mykola-mokhnach** [comment] 2021-12-30 18:13
https://github.com/appium/appium-xcuitest-driver#mobile-terminateapp could be used to terminate an app

**Comment by narasimhanukala** [comment] 2021-12-30 19:19
@mykola-mokhnach 
To close the app, we can use terminateapp.
what if i want to launch the app again without calling capabilities? is there any replacement for launchapp()?

**Comment by KazuCocoa** [comment] 2021-12-30 19:34
https://github.com/appium/appium-xcuitest-driver#mobile-launchapp or https://github.com/appium/appium-xcuitest-driver#mobile-activateapp, or https://appium.io/docs/en/commands/device/app/activate-app/
