### ISSUE TITLE
Appium can't connect android emulator

### ISSUE THREAD

**Issue by crw614** [appium/appium#14859] opened 2020-11-03 12:42 UTC
## The problem
Appium can't connect to emulator which ran by appium

## Environment
* Appium version (or git revision) that exhibits the issue: 1.18.3
* Last Appium version that did not exhibit the issue (if applicable): 1.17.2
* Desktop OS/version used to run Appium: Mac OS 10.15.6
* Node.js version (unless using Appium.app|exe): v12.10.0
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: Android 6.0 (Api 23) Nexus 5X 
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

When i use appium 1.17.1 is running emulator and executing test. When i use newest appium version, appium can run emulator but can't connect it.

emulator opened by appium 1.18.3 have state offline:
`adb devices -l                                      
List of devices attached
emulator-5554          offline transport_id:8`

## Link to Appium logs

Logs from both versions: 
https://gist.github.com/crw614/538962cce12c3156986b7152d702672d

**Comment by mykola-mokhnach** [comment] 2020-11-03 12:54
Duplicate of https://github.com/appium/appium/issues/14773

**Closed by mykola-mokhnach** 2020-11-03 12:54 UTC
