### ISSUE TITLE
iOS Appium giving error: TypeError: Cannot read property 'wasThrown' of undefined

### ISSUE THREAD

**Issue by mansi1516** [appium/appium#9278] opened 2017-09-22 15:56 UTC
Problem:
I have upgraded XCode to 9 and Appium to 1.7/1.6.5 and trying to execute few test cases on mobile web.
**Code:**
```java
_DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("deviceName", "iPhone");
capabilities.setCapability("udid", "<udid>");
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("automationName", "XCUITest");
capabilities.setCapability("browserName", "Safari");
capabilities.setCapability("newCommandTimeout",180);
capabilities.setCapability("webkitResponseTimeout", 70000);
capabilities.setCapability("networkConnectionEnabled",true);
capabilities.setCapability("--session-override",true);
		
driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
Thread.sleep(5000);
driver.get("https://<url>");
Thread.sleep(10000);
driver.findElement(By.xpath("//*[@id='<>']")).click();_
```

**Sometimes the test case run properly but sometimes it gives error as mentioned below:**
_Sep 22, 2017 9:19:00 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
_**Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.**_
Build info: version: '3.5.3', revision: '**', time: '2017-08-29T12:42:44.**'
System info: host: 'MacBook-Pro.local', ip: '', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_40'
Driver info: driver.version: RemoteWebDriver
Capabilities [{networkConnectionEnabled=true, webkitResponseTimeout=70000, --session-override=true, databaseEnabled=false, deviceName=iPhone, platform=MAC, newCommandTimeout=180, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=Safari, takesScreenshot=true, javascriptEnabled=true, udid=<udid>, platformName=MAC}]
Session ID: 
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:667)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:416)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:518)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:408)
	at com.appium_ios11.testExec.main(testExec.java:64)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:139)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:87)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:161)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	... 5 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 18 more_

**Also, on looking at appium server logs, I get the below error:**
```
_[debug] [RemoteDebugger] Webkit response timeout: 70000
[debug] [RemoteDebugger] Receiving WebKit data: {"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":null}"},"wasThrown":false},"id":3}
[debug] [RemoteDebugger] Found handler for message '3'
[debug] [RemoteDebugger] Received result for atom 'click' execution: null
[debug] [MJSONWP] Responding to client with driver.click() result: null
[HTTP] <-- POST /wd/hub/session/**/element/5000/click 200 942 ms - 76 
[debug] [RemoteDebugger] Receiving WebKit data: {"method":"Canvas.canvasMemoryChanged","params":{"canvasId":"canvas:0.3","memoryCost":32000}}
TypeError: Cannot read property 'wasThrown' of undefined
    at WebKitRpcClient.receive (../../lib/webkit-rpc-client.js:117:38)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/usr/local/lib/node_modules/appium/node_modules/ws/lib/WebSocket.js:841:10)
    at /usr/local/lib/node_modules/appium/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/usr/local/lib/node_modules/appium/node_modules/ws/lib/Receiver.js:371:5)
    at /usr/local/lib/node_modules/appium/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/usr/local/lib/node_modules/appium/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/usr/local/lib/node_modules/appium/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/usr/local/lib/node_modules/appium/node_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (/usr/local/lib/node_modules/appium/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/usr/local/lib/node_modules/appium/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)_
```
Can any one please help..

**Comment by imurchie** [comment] 2017-09-22 16:02
Thanks for reporting. Investigating...

**Comment by imurchie** [comment] 2017-09-22 19:01
I'm attempting to figure out why this is happening. When this happens does it always happen when getting the `Canvas.canvasMemoryChanged` event?

**Comment by mansi1516** [comment] 2017-09-23 04:12
Yes @imurchie ..

**Comment by gauravdewan007** [comment] 2017-09-25 12:23
Many folks in teams are kind of blocked because of this issue on ios11

**Comment by imurchie** [comment] 2017-09-25 12:25
Can you provide a website that causes this? I'm not sure what it is that prompts the event. A reproducing test case would be awesome!

**Comment by mansi1516** [comment] 2017-09-25 12:29
@imurchie you can use any website.. also i have provided the code in my comments above.

**Comment by gauravdewan007** [comment] 2017-09-25 12:31
@imurchie Please try this website.
http://corehtml5canvas.com/code-live/ch01/example-1.13/example.html
 If you use driver.get("http://corehtml5canvas.com/code-live/ch01/example-1.13/example.html") then you can see this crash

**Comment by imurchie** [comment] 2017-09-25 12:59
The code above goes to `https://<url>`, which isn't particularly useful.

I'll try with the one @gauravdewan007 provided.

**Comment by nitiskum** [comment] 2017-09-25 12:59
@imurchie  Please fix this issue the above website is causing the same crash . I updated my Iphone  to IOS 11 and now stuck with this problem.

**Comment by melliot** [comment] 2017-09-25 14:49
@imurchie I'm facing with the same problem after updating iphone to IOS 11 and xcode to 9 version.

**Comment by imurchie** [comment] 2017-09-25 16:56
Thanks for the website @gauravdewan007 I can reproduce. Looking into why this is happening.

**Comment by imurchie** [comment] 2017-09-25 17:38
I've fixed this issue in `appium-remote-debugger@3.6.2`. If you re-install Appium it should work (`npm uninstall -g appium && npm install -g appium --no-shrinkwrap`).

**Comment by nitiskum** [comment] 2017-09-26 04:39
Fixed in my case, Appium is not getting crashed now.  Thanks @imurchie for a quick turnaround

**Comment by gauravdewan007** [comment] 2017-09-26 05:34
Thanks for prompt fix !!

**Comment by mansi1516** [comment] 2017-09-26 05:37
Thanks @imurchie its working for me too :)

**Closed** 2017-09-26 07:58 UTC
Labels: iOS, Mobile Safari, Real Devices
