### ISSUE TITLE
input_value() is failing to enter text in appium appium-xcuitest-driver.

### ISSUE THREAD

**Issue by sharecommute** [appium/appium#8899] opened 2017-07-23 02:29 UTC
## The problem

input_value() is failing with v.split function error.
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4/1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 5.0.3
* Mobile platform/version under test: 10.3.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: appium-python-client 0.24.0
* Xcode version : 8.3.3

## Details

Installed appium 1.6.4 , 
self.driver.input_value('login', '6503002060')

Tried with all options including:
1. Installing appium 1.6.5, 1.6.4 and 
2. selenium 3.3.1, 3.4.3, 
3. replacing WDA agent code from facebook etc..,
4. The same scenario works on macbook pro but not on the mac mini (core i5)

error:
[debug] [MJSONWP] Calling AppiumDriver.setValueImmediate() with args: [[113],"18993ED4-9A8D-430C-91AF-BA14BC20482F","d01b166e-6bfc-462b-ad8e-76b6398f8c67"]
[debug] [XCUITest] Executing command 'setValueImmediate'
[XCUITest] There is currently no way to bypass typing using XCUITest. Setting value through keyboard
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:52 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[MJSONWP] Encountered internal error running command: TypeError: v.split is not a function
    at ../../../lib/commands/element.js:164:41
    at arrayMap (/usr/local/lib/node_modules/appium/node_modules/lodash/lodash.js:660:23)
    at map (/usr/local/lib/node_modules/appium/node_modules/lodash/lodash.js:9571:14)
    at Function.flatMap (/usr/local/lib/node_modules/appium/node_modules/lodash/lodash.js:9274:26)
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/element.js:164:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.callee$0$0 [as setValue] (../../../lib/commands/element.js:179:15)
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/element.js:127:14)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.callee$0$0 [as setValueImmediate] (../../../lib/commands/element.js:124:55)
    at ../../../lib/basedriver/driver.js:207:24
    at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
https://gist.github.com/sharecommute/64a88fadeb7003e3ec8be18e4a6ef343

## Code To Reproduce Issue [ Good To Have ]

self.driver.input_value('login', '6503002060')

**Comment by sharecommute** [comment] 2017-07-23 05:26
Here are some of my desired capabilities:
{"automationName": "XCUITest",
    "showIOSLog": false,
    "setValue": 20000,
    "showXcodeLog": true,
    "iosInstallPause" : 8000,
    "platformName": "iOS",
    "platformVersion": "10.3",
    "deviceName": "iPhone",
}

**Comment by mykola-mokhnach** [comment] 2017-07-23 06:29
> [debug] [MJSONWP] Calling AppiumDriver.setValueImmediate() with args: [[113],"18993ED4-9A8D-430C-91AF-BA14BC20482F","d01b166e-6bfc-462b-ad8e-76b6398f8c67"]

You are trying to pass a number instead of a string as the input argument. This causes type conversion failure since numbers cannot be split.

**Comment by sharecommute** [comment] 2017-07-23 06:45
first its not going upto that its failing before itself.

"value":["6","5","8","3","9","1","2","4","6","6"]}
g] [IOS_SYSLOG_ROW] Jul 21 18:43:48 xxxxxxxxxxxxxx-iPhone XCTRunner(WebDriverAgentLib)[1371] <Notice>: Typing with maximum frequency 60
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:48 xxxxxxxxxxxxxx-iPhone XCTRunner(WebDriverAgentLib)[1371] <Notice>: Using singleton test manager
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:48 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:48 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:48 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Error Domain=XCTDaemonErrorDomain Code=14 \"Timed out waiting for key event to complete\" UserInfo={NSLocalizedDescription=Timed out waiting for key event to complete}","sessionId":"CF56C0C2-30EF-479E-A68D-D375770B586C","status":13}
[debug] [JSONWP Proxy] Proxying [GET /element/374D6C56-B620-4037-9F5E-0B93F7E701E3/attribute/type] to [GET http://localhost:25352/session/CF56C0C2-30EF-479E-A68D-D375770B586C/element/374D6C56-B620-4037-9F5E-0B93F7E701E3/attribute/type] with no body
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:49 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:49 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: 


Its trying to type the first number which is "6" twice and failing with the above error.

**Comment by sharecommute** [comment] 2017-07-23 07:10
Is this a concern?

[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone testmanagerd[269] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone xxxxx(UIKit)[1374] <Notice>: Can't find keyplane that supports type 4 for keyboard iPhone-Portrait-NumberPad; using 160517473_Portrait_iPhone-Simple-Pad_Default
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone xxxxx(UIKit)[1374] <Notice>: activate generator <_UIFeedbackKeyboardBehavior: 0x1701150f0: prepared=1> with style: TurnOn; activationCount: 1 -> 0; styleActivationCount: 1 -> 0
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone xxxxx(UIKit)[1374] <Notice>: feedback engine <_UIFeedbackSystemSoundEngine: 0x1702abd00: state=0, numberOfClients=1, prewarmCount=0, _isSuspended=0> state changed: Inactive -> Activating
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone xxxxx(UIKit)[1374] <Notice>: feedback engine <_UIFeedbackSystemSoundEngine: 0x1702abd00: state=3, numberOfClients=1, prewarmCount=0, _isSuspended=0> state changed: Activating -> Running
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone assertiond[63] <Notice>: Ignoring assertion request named "com.apple.UIKit.KeyboardManagement.message" from <BSProcessHandle: 0x10030d2b0; SpringBoard:53; valid: YES> because process { pid 119; bundleID (null) } is unknown.
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone SpringBoard(KeyboardArbiter)[53] <Error>: [<_UIKeyboardArbiterHandle: 0x1702fcb80; PID 119: (null) <(null)>; hosting PIDs {(
[iOSLog] [IOS_SYSLOG_ROW] )}; level 0.000000; active NO [wants NO]; suppression 0>] could not take process assertion
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone mediaserverd(AudioToolbox)[27] <Notice>: 1394: clientPID 1374(xxxxx), flag 1, ssid 1104
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone mediaserverd(AudioToolbox)[27] <Notice>: 1394: clientPID 1374(xxxxx), flag 1, ssid 1155
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone mediaserverd(AudioToolbox)[27] <Notice>: 1394: clientPID 1374(xxxxx), flag 1, ssid 1156
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone sharingd[57] <Notice>: SystemUI unknown identifier: 'xxx.xxxx.xxxxxx'
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone sharingd[57] <Notice>: SystemUI changed: 0x0 -> 0x0
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone CommCenter[75] <Notice>: #I CSIAppInfo.AppObserver: observe_block_invoke: FBSDisplayLayoutUpdateHandler: update start
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone CommCenter[75] <Notice>: #I CSIAppInfo.AppObserver: observe_block_invoke: FBSDisplayLayoutUpdateHandler: app <private> (UIApplicationElement 1 hasKeyboardFocus 1)
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone CommCenter[75] <Notice>: #I CSIAppInfo.AppObserver: observe_block_invoke: 4. app got notification state: pid=1374 for <private>
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone kbd(KeyboardServices)[138] <Notice>: -[_KSTextReplacementCKStore accountDidChange:]_block_invoke  >>> User has logged out of the account, removing local entries
[iOSLog] [IOS_SYSLOG_ROW] Jul 21 18:43:45 xxxxxxxxxxxxxx-iPhone kbd(KeyboardServices)[138] <Notice>: AppleLanguages preference: (

**Comment by mykola-mokhnach** [comment] 2017-07-23 08:19
> {"value":"Error Domain=XCTDaemonErrorDomain Code=14 "Timed out waiting for key event to complete" UserInfo={NSLocalizedDescription=Timed out waiting for key event to complete}

This is XCTest/WDA issue and it should be reported to https://github.com/facebook/WebDriverAgent/issues

Also, it might be a duplicate of https://github.com/facebook/WebDriverAgent/issues/476

**Comment by sharecommute** [comment] 2017-07-23 19:22
any workarounds as i am completely stuck with this error.

**Comment by mykola-mokhnach** [comment] 2017-07-23 19:28
[Retry](https://github.com/facebook/WebDriverAgent/issues/453) sometimes helps. You can also try to change the default value for **maxTypingFrequency** capability.
Anyway, there is nothing we can do about that in Appium.

**Closed by mykola-mokhnach** 2017-07-23 19:28 UTC
Labels: XCUITest

**Comment by sharecommute** [comment] 2017-07-23 19:29
thank you @mykola-mokhnach . i tried just now and no change. I will try with the specified capability.

**Comment by sharecommute** [comment] 2017-07-30 06:40
@mykola-mokhnach , no change even after with the specified capability.

**Comment by sharecommute** [comment] 2017-08-15 22:37
Also happening when i try to run the test case on the remote server which started on mac. Note: If i run the same test on the mac itself it passes but happens
