### ISSUE TITLE
Appium Taking Screenshot Fails Frequently when log level is low, e.g. debug

### ISSUE THREAD

**Issue by sm6995** [appium/appium#4539] opened 2015-02-13 17:34 UTC
We are continuing to have issues taking screenshots with Appium.  I downloaded the hopeful fix (commit: (https://github.com/moizjv/appium/commit/3eb3914707098b1d2a089a9f53fd1597cc7d1235) for this based on a past issue 3130 (https://github.com/appium/appium/issues/3130), from Appium the 1.3.5 Beta version. This still did not fix my issue. I even increased the retry's to 5 and added a lot of wait time in between screenshots; however, I am still seeing this error:

<pre>
<code>
WARN: Taking snapshot failed.  Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. (Original error: Timed out waiting for screenshot file. Error: ENOENT, open '/tmp/appium-instruments/Run 1/screenshot79b70972-9943-4850-b73e-ad44eff65b61.png')
</code>
</pre>

What's interesting is that all of the screenshots exist in the tmp/appium-instruments/Run 1/ file. In fact with the retry's I am seeing 3 - 5 copies of the same screenshot, so I do not understand how it is getting this error.

Here is the Appium log:

<pre>
<code>
info: [debug] Pushing command to appium work queue: "au.capture('screenshot79b70972-9943-4850-b73e-ad44eff65b61')"
info: [debug] Sending command to instruments: au.capture('screenshot79b70972-9943-4850-b73e-ad44eff65b61')
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
...
... 
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Timed out waiting for screenshot file. Error: ENOENT, open '/tmp/appium-instruments/Run 1/screenshot79b70972-9943-4850-b73e-ad44eff65b61.png')","origValue":"Timed out waiting for screenshot file. Error: ENOENT, open '/tmp/appium-instruments/Run 1/screenshot79b70972-9943-4850-b73e-ad44eff65b61.png'"},"sessionId":"dd987f00-b08a-47d0-98ee-2cd2e657ebc3"}
info: <-- GET /wd/hub/session/dd987f00-b08a-47d0-98ee-2cd2e657ebc3/screenshot 500 63217.071 ms - 470 
info: --> GET /wd/hub/session/dd987f00-b08a-47d0-98ee-2cd2e657ebc3/screenshot {}
</code>
</pre>

Setup:
appium 1.3.4 (with commit referenced above)
Xcode 6.1
iOS 8.1 (iPhone and iPad simulators)
MAC OS X 10.9.5
ruby 2.1.1p76

**Comment by sebv** [comment] 2015-02-16 13:04
Did you try increasing the screenshot delay. There is the screenshotWaitTimeout for that.

**Comment by sm6995** [comment] 2015-02-17 17:28
Yes, I have tried increasing the delay.  In the ios-controller.js, I tried increasing the timeout by multiplying  by 2000 and then 3000 for this variable:
<code>
var screenshotWaitTimeout = (this.args.screenshotWaitTimeout || 10) * 1000;
</code>
I am still receiving the same failure.

**Comment by sm6995** [comment] 2015-02-19 16:01
@sebv We were noticing that the debug info being logged out for Appium was quite a bit behind the actual test.  Once we turned up the log level to 'error' or 'warn', we stopped having issues with the screen prints.  I received all of my screen prints without errors.  Additionally, where before I was seeing 1 - 3 screen prints of the same thing, once the log level was turned up, it was able to just take one screen shot and read it without error.  Seems this might be a threading issue with the logging???

**Comment by SquareTheBase** [comment] 2015-02-24 20:07
I was running with log-level 'debug' which I think is the highest level and received the screenshot timeout with an intensive automation test.  The CPU was being tasked when the screenshot was requested.  Moved down to a 'warn' level and didn't obtain the timeout.  cc @sm6995

**Comment by sebv** [comment] 2015-03-10 04:55
Moving to 1.3.7 milestone. @0x1mason another logging issue.

**Comment by p00j4** [comment] 2015-03-20 11:14
@sebv : I think, such logs should be logged under "error", isn't it ! 
![screen shot 2015-03-20 at 4 42 00 pm](https://cloud.githubusercontent.com/assets/6470509/6750425/1a739d86-cf20-11e4-829c-e3b04aacca09.png)

**Comment by 0x1mason** [comment] 2015-03-20 12:27
Yes, you are correct.

**Comment by jlipps** [comment] 2015-03-20 15:22
I'm not sure. This log message isn't describing an error case in appium. It is an error case for your test, but Appium doesn't know that. There are plenty of times when you might intentionally try to find an element that doesn't exist to assert that it's no longer there. This isn't an error case.

The log message is merely showing what its (totally proper) response is going to be to the client.

**Comment by 0x1mason** [comment] 2015-03-21 23:24
It's the kind of thing I'd want logged even if I didn't want a debug lvl of logging. Maybe warning.

**Comment by p00j4** [comment] 2015-03-22 06:38
@jlipps : I totally agree with you [surely of use for dev of appium] 
though as a user, I too find necessity of having them else, changing log level is not of any use for a user, probably having a flag for user or dev will solve the problem for both the parties !

**Comment by jlipps** [comment] 2015-03-26 19:24
I guess I think it would be even more confusing to have this kind of output listed as 'warn' or 'err'. Those labels are reserved for warnings/errors in appium itself. That's not the category of thing we're talking about. We're talking about totally nominal, working behavior that's not in any way warn/err. I'm not sure why it's onerous to run with the 'info' or 'debug' loglevel in cases where you want to see this type of logging.

If we label this output with 'warn' or 'err', it will communicate to users watching the logs that something dangerous or wrong is going on inside of appium, when that is not the case. We'll have issues created here because people see 'error' in the logs, when they were just trying to find an element that didn't exist.

**Comment by 0x1mason** [comment] 2015-04-17 18:39
@sm6995 I'm having difficulty reproducing this v1.3.7.  Are you using the Appium.app GUI or the command line interface?  I'd also like to discover if the following change makes any difference for you:

In `<appium root>/node_modules/appium-uiauto/uiauto/vendors/mechanic.js`, change lines 420-423 to
```js
        error: function(s) { return; },
        warn: function(s) { return;  },
        debug: function(s) { return;  },
        message: function(s) { return;  },
```
Thanks

**Comment by sm6995** [comment] 2015-04-17 19:32
We have not upgraded to 1.3.7 yet.  We are still on 1.3.4.

**Comment by amedvedjev** [comment] 2015-04-25 06:36
similar setup: Mac 10.10.X, appium 1.3.4, xCode 6.3, Simulator 8.1 but java client. 
many image recognitions tests (Sikuli integrated) with native iOS client (CI with Bamboo) - issue is really rear for us maybe 1 from 100 tries to get screenshot. But due to workaround to re-try up to 5 times in case fail - never was cause test to fail due to failed to get screenshot from simulator.

more info maybe helps to find cause:
 - appium installed on MAC machine with "npm install -g appium"
 - appium starts in code as process with error log level setup like: "appium --port XXXX --session-override --log-level error"

**Comment by jlipps** [comment] 2015-05-01 14:34
@amedvedjev when you set your log-level to debug, do you see the issue?

**Comment by jlipps** [comment] 2015-05-01 14:36
sorry @sm6995 wanted to handle this as part of 1.4 but it seems we're still investigating what's going on. I'm going to roll this over to 1.5, but hopefully it will be addressed soon so you can run from master if we resolve the issue. also will update the title to reflect the bug

**Comment by sm6995** [comment] 2015-05-01 16:29
The work-around (setting the log level at warn or error) is fine for us.  We are in no hurry.
Thank you!

**Comment by amedvedjev** [comment] 2015-05-01 16:51
@jlipps we always do test suites with error log level. when i want to investigate any issue i temporarily set level to debug and run only needed test locally for debugging.

**Comment by amedvedjev** [comment] 2015-05-04 08:40
run test which we use when generate new build with new data and saving screenshots.

How:
 - appium (1.3.7) server logs where set to debug mode.
 - test was started in MacOS terminal like: mvn test -DsuiteFile=src/test/java/resources/someTest.xml - testNG file
 - client: Android client with real phone of 4.3 android version
 - screenshots are taking from client as: ImageIO.read(((AppiumDriver) driver).getScreenshotAs(OutputType.FILE));

Test statistics:
 - lines of logs generated: 42500
 - size of file if save all these logs into some txt file: 49,297,913 bytes 
 - number of screenshots made: 37
 - number of failed screenshots: 0
 - execution time: 15min

**Comment by jlipps** [comment] 2015-05-04 16:09
@amedvedjev what are the stats for running your iOS tests with --log-level error?

**Comment by amedvedjev** [comment] 2015-05-04 19:29
what will it say? we have 1 fail for 68 (67+1) tries with debug level. with error level we can have from 0 let say to 3 (just possible error rate).
i do not mind to test. just interesting what will it give...

**Comment by amedvedjev** [comment] 2015-05-05 10:53
@jlipps updated with Error log level in previous comment.
BTW we experience strange behaviour with latest xcode. depending how it was installed (updated or from zero) - we see different behaviour.

**Comment by jlipps** [comment] 2015-05-05 15:06
interesting. it does seem like there is some correlation between logging and screenshot failure. we'll keep looking into this

**Comment by SquareTheBase** [comment] 2015-05-05 15:20
@jlipps FWIW - When my tests fail with debug logging and I request a screenshot, you can continue to observe instruments debug statements print for minutes until it catches up to realtime.   Its during this time that the screenshot fails.  

Presumably because its waiting on Instruments to acknowledge the screenshot?

**Comment by yaphatak** [comment] 2015-05-05 20:02
@jlipps : is it worth using idevicescreenshot from libmobiledevice guys?
there are 2 catches to it
1.. You get very large image from idevicescreenshot . So,  you need to convert to .jpg before convert it into binary.
2. appium doesn't maintain libmobiledevice project
But we are still using it internally as we find its more stable. May be we can add capability and server-argument to choose how to take screenshot

**Comment by jlipps** [comment] 2015-05-05 22:18
i think adding a flag to use idevicescreenshot instead would be a good way of figuring out which is more reliable. can you create an issue for this @yaphatak and i'll add it to the 'features' milestone?

**Comment by yaphatak** [comment] 2015-05-08 10:18
done @jlipps  #5085

**Comment by vkyt** [comment] 2015-07-30 17:49
I got the same error when running a large suite of cucumber tests in Ruby.  When running individual feature on its own the screenshot functionality is completely functional.  Any idea what might have caused this issue?  

In the mean time, I'm going to try tune down the appium logging level in my test code.

**Comment by nirajsingh1486** [comment] 2016-06-09 09:47
is this issues fixed? i am facing issue in 1.4.13

**Comment by hajarbabour** [comment] 2016-06-09 09:48
I have the same problem!

**Comment by imurchie** [comment] 2017-07-18 15:46
Closing as inactive.

**Closed by imurchie** 2017-07-18 15:46 UTC
Labels: Bug, iOS
