### ISSUE TITLE
NoSuchElementFoundExeption in android native app

### ISSUE THREAD

**Issue by sushmitha-mk** [appium/appium#12634] opened 2019-05-13 05:21 UTC
Appium version 1.12.1 windows 10 working platform=android version 5.1.1,4.4,6.0 Not working in android version 7.1 and above

I am getting NoSuchElementFoundExeption error contineously during following scenario in android app

Before loading the page there is RestAPI call requesting data from server during this a progressDailogue is shown,so once after page loaded it shows the data with native components(textview,buttons etc) and the progressDailoogue hides.

Once the native elements are displayed I am trying to click on the element by using ID(tried by xpath) but it is showing NoSuchElementFoundExeption also I tried by using wait method and adding some delay still it is displaying the same error.

I tried by removing the process dailog box in my app where it works fine, But I wanted to find the element and click on the element without removing the process dailog box.

This is sample code tried

WebDriverWait wait = new WebDriverWait(driver, 120);
wait.until(ExpectedConditions.visibilityOf(element));
element.click();
How to get the elements click working after hiding progressDailogue.

So any help on this ???

**Comment by mykola-mokhnach** [comment] 2019-05-13 05:29
Please provide all the requested environment info along with the full server log

**Comment by mykola-mokhnach** [comment] 2019-05-13 07:21
Duplicate of https://github.com/appium/appium/issues/12635

**Closed by mykola-mokhnach** 2019-05-13 07:21 UTC
Labels: NeedsInfo

**Comment by sushmitha-mk** [comment] 2019-05-13 08:01
I have updated appium logs above please verify
This issue is native related issue , both are different issue please re visit
