### ISSUE TITLE
[ANDROID] Getting this error while starting the session. Already set the android home and java home.

### ISSUE THREAD

**Issue by zaid0080** [appium/appium#16234] opened 2021-12-09 12:22 UTC
## The problem
![image](https://user-images.githubusercontent.com/70195293/145395395-3d2d7dd2-4a28-458e-a018-7b30a6cd0c98.png)
Failed to create session. An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\zaida\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s UCVO45PFJ7JBGAFI shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Stderr: 'Exception occurred while executing 'delete': java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2393) at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1428) at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1420) at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1391) at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:576) at android.content.ContentProvider.call(ContentProvider.java:2448) at android.content.ContentProvider$Transport.call(ContentProvider.java:517) at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399) at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281) at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98) at android.os.ShellCommand.exec(ShellCommand.java:44) at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49) at android.os.Binder.shellCommand(Binder.java:936) at android.os.Binder.onTransact(Binder.java:820) at android.os.Binder.execTransactInternal(Binder.java:1166) at android.os.Binder.execTransact(Binder.java:1130) Exception occurred while executing 'delete': java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2393) at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1428) at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1420) at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1391) at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:576) at android.content.ContentProvider.call(ContentProvider.java:2448) at android.content.ContentProvider$Transport.call(ContentProvider.java:517) at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399) at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281) at android.os.BasicShell
Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2021-12-09 14:34
Duplicate of https://github.com/appium/appium/issues?q=is%3Aissue+%22Permission+denial%3A+writing+to+settings+%22+is%3Aclosed

**Closed by mykola-mokhnach** 2021-12-09 14:34 UTC
