### ISSUE TITLE
Error kAXErrorIllegalArgument getting snapshot for element

### ISSUE THREAD

**Issue by pabloleal1** [appium/appium#15585] opened 2021-06-28 10:50 UTC
For iOS as OS and using appium desktop version 1.21.0 on my mac, after tapping on an button element, the following error is shown.

"[element.click()] Error response status: 10, StaleElementReference - An element command failed because the referenced element is no longer attached to the DOM. Selenium error: The previously found element ""ShowDetailTab_1_TabTitle" StaticText" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: Error kAXErrorIllegalArgument getting snapshot for element <AXUIElementRef 0x101409db0> {pid=3862} {uid=[ID:1 hash:0x0]}"

Can you please help me to solve this issue?
Thanks,

**Comment by mykola-mokhnach** [comment] 2021-06-28 13:08
Is the button really present on the screen while clicking it? have you tried to find it again instead of using the cached element?

**Comment by pabloleal1** [comment] 2021-06-28 16:12
Once I tap the element (button) to move to another screen of my .ipa nothing happens, however when I tap for the second time the error above is shown.
Also If I move to that screen manually on my real device and refresh the appium desktop to locate the elements, that screen is  not displayed on my appium desktop. 

Any idea would be really appreciated.

**Comment by mykola-mokhnach** [comment] 2021-06-28 17:09
The error looks like an internal XCTest failure, which we cannot influence much. Most likely it fails to take a snapshot from this page, which is a duplicate of https://github.com/appium/appium/issues/15565

**Comment by mykola-mokhnach** [comment] 2021-06-30 05:49
Closed because of no response

**Closed by mykola-mokhnach** 2021-06-30 05:49 UTC
Labels: NotABug, ThirdParty, XCUITest

**Comment by kababoom** [comment] 2021-12-14 13:52
I understand this being an XCUITest issue and this is closed but like to add I still having this issue in a certain page in my app.
Appium 1.22
Xcode 13.1
iOS 15.1.1 (actually all above 15.0.1)

When retrieving screenshot the whole app crashes, increasing the timeout through settings does not help.

curl  -d '{"settings":{"customSnapshotTimeout":"60"}}' -H "Content-Type:application/json" -X POST http://127.0.0.1:8100/session/{sessionId}/appium/settings

```
[Xcode]     t =   686.33s Requesting snapshot of accessibility hierarchy for app with pid 8199
[Xcode] 
[Xcode] 2021-12-14 14:42:54.865535+0100 WebDriverAgentRunner-Runner[8212:2397740] Cannot take a snapshot with attribute(s) (
[Xcode]     "XC_kAXXCAttributeElementBaseType",
[Xcode]     "XC_kAXXCAttributeHasNativeFocus",
[Xcode]     "XC_kAXXCAttributeTruncatedValue",
[Xcode]     "XC_kAXXCAttributeViewControllerTitle",
[Xcode]     "XC_kAXXCAttributeUserTestingElements",
[Xcode]     "XC_kAXXCAttributeAutomationType",
[Xcode]     "XC_kAXXCAttributeBannerIsStickyAttribute",
[Xcode]     "XC_kAXXCAttributeIdentifier",
[Xcode]     "XC_kAXXCAttributeTraits",
[Xcode]     "XC_kAXXCAttributeFrame",
[Xcode]     "XC_kAXXCAttributeVerticalSizeClass",
[Xcode]     "XC_kAXXCAttributeViewControllerClassName",
[Xcode]     "XC_kAXXCAttributeIsUserInteractionEnabled",
[Xcode]     "XC_kAXXCAttributeLabel",
[Xcode]     "XC_kAXXCAttributeURL",
[Xcode]     "XC_kAXXCAttributeParent",
[Xcode]     "XC_kAXXCAttributeHorizontalSizeClass",
[Xcode]     "XC_kAXXCAttributePlaceholderValue",
[Xcode]     "XC_kAXXCAttributeElementType",
[Xcode]     "XC_kAXXCAttributeIsVisible"
[Xcode] ) of 'XCUIElementTypeAny' after 60.00 seconds
[Xcode] 2021-12-14 14:42:54.865629+0100 WebDriverAgentRunner-Runner[8212:2397740] This timeout could be customized via 'customSnapshotTimeout' setting
[Xcode] 2021-12-14 14:42:54.865670+0100 WebDriverAgentRunner-Runner[8212:2397740] Internal error: Timed out snapshotting com.apple.testmanagerd, app is either unresponsive or taking too long to snapshot.
[Xcode] 2021-12-14 14:42:54.865714+0100 WebDriverAgentRunner-Runner[8212:2397740] Falling back to the default snapshotting mechanism for the element 'XCUIElementTypeAny' (some attribute values, like visibility or accessibility might not be precise though)
```

**Comment by SillymanH** [comment] 2021-12-19 07:05
I'm having the same issue as @kababoom

**Comment by pabloleal1** [comment] 2022-02-07 12:37
We are still having the same issue,

Has anyone solved it?

Thanks in advance!

**Comment by SillymanH** [comment] 2022-02-07 12:49
Yes @pabloleal1, the cause of this problem is that the page/table/list refreshes when you do a certain action which causes the driver to throw a StaleElementReference exception. Meaning that the  element you are inspecting was there but after the page/table/list refreshed the element was no longer there. 

Even if the element has the same id/className/etc... since it was refreshed the driver loses it and tells you that it's no longer attached in the DOM.

The solution  is to  find the element again after being refreshed

OR

As the developer not to refresh the page/table/list after the action  you do (if it's fine to remove the refresh and does not affect application).

**Comment by kababoom** [comment] 2022-02-07 15:04
@SillymanH 

How to find the element again if the whole app has closed/crashed?

**Comment by tamaniniandre** [comment] 2023-12-07 15:03
Same issue here
