### ISSUE TITLE
Simulator click probability doesn't work 

### ISSUE THREAD

**Issue by candialala** [appium/appium#15678] opened 2021-08-01 12:41 UTC
## The problem

Click probability doesn't work 

## Environment

Appium version (or git revision) that exhibits the issue: 1.21.0
Last Appium version that did not exhibit the issue (if applicable): 1.19.0
Desktop OS/version used to run Appium: Mac OS Big Sur 11.5
Mobile platform/version under test: iOS 14.5
Real device or emulator/simulator: Simulator

## Details
I had a problem with clicking on the new element when the page/hover jumps. It found the element and clicked the element on the log without any problems, but clicking actually it didn't work. 
I think this problem exists after [self fb_waitUntilFrameIsStable] is removed, but it is a probabilistic occurrence. Is there a good way to stabilize the page before clicking? I don't want to do that much waiting in the script.
And it only happens in the simulator.

![image](https://user-images.githubusercontent.com/22468260/127771221-5eac4054-2efc-477b-a919-a44a8a15358b.png)

**Comment by KazuCocoa** [comment] 2021-08-02 07:05
Could you share the appium log with `showIOSLog`?

**Comment by candialala** [comment] 2021-08-02 08:28
> Could you share the appium log with `showIOSLog`?
<script src="https://gist.github.com/candialala/a4d277531f39f2d0102dc19295a56ac5.js"></script>

**Comment by KazuCocoa** [comment] 2021-08-03 05:28
What capabilities/settings api did you set?

It seems tap action was issued.
```
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 Df testmanagerd[82664:b7bcb7] [com.apple.BackBoard:Display] [FBSDisplaySource 2-32] did invalidate
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 Df testmanagerd[82664:b7bcb7] [com.apple.BackBoard:Display] [FBSDisplaySource 1-31] did invalidate
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 Df testmanagerd[82664:b7bcb7] [com.apple.dt.xctest:Default] normalized {283, 211} to {0.68357487922705318, 0.23549107142857142}
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 Df testmanagerd[82664:b7bcb7] [com.apple.dt.xctest:Default] Waiting up to 5.0s for TouchEventsCompleted to confirm 
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] <XCSynthesizedEventRecord 'tap display 1'>
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] Path 1:
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 	Touch down at 283.0, 211.0, offset=0.00s
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 	Touch up at 283.0, 211.0, offset=0.05s.
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 A  SpringBoard[82669:b7a530] (UIKitCore) send gesture actions
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 Df testmanagerd[82664:b7a400] [com.apple.dt.xctest:Default] Handling kAXUserTestingNotification from AX element pid: 82669, elementOrHash.elementID: 0.1 (0x131a0a7f0)
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 Df testmanagerd[82664:b7a400] [com.apple.dt.xctest:Default] Got user testing notification with payload {
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW]     event = TouchEventsCompleted;
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] }
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 Df testmanagerd[82664:b7bc91] [com.apple.dt.xctest:Default] Calling handler for AX notification kAXUserTestingNotification from AX element pid: 82669, elementOrHash.elementID: 0.1 with payload {
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW]     event = TouchEventsCompleted;
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] }
2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 Df testmanagerd[82664:b7bc91] [com.apple.dt.xctest:Default] Ev
```

I'd like to check you did not set something disabling animation wait etc such as `animationCoolOffTimeout`.

**Comment by candialala** [comment] 2021-08-03 08:19
> What capabilities/settings api did you set?
> 
> It seems tap action was issued.
> 
> ```
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 Df testmanagerd[82664:b7bcb7] [com.apple.BackBoard:Display] [FBSDisplaySource 2-32] did invalidate
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 Df testmanagerd[82664:b7bcb7] [com.apple.BackBoard:Display] [FBSDisplaySource 1-31] did invalidate
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 Df testmanagerd[82664:b7bcb7] [com.apple.dt.xctest:Default] normalized {283, 211} to {0.68357487922705318, 0.23549107142857142}
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 Df testmanagerd[82664:b7bcb7] [com.apple.dt.xctest:Default] Waiting up to 5.0s for TouchEventsCompleted to confirm 
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] <XCSynthesizedEventRecord 'tap display 1'>
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] Path 1:
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 	Touch down at 283.0, 211.0, offset=0.00s
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 	Touch up at 283.0, 211.0, offset=0.05s.
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 A  SpringBoard[82669:b7a530] (UIKitCore) send gesture actions
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 Df testmanagerd[82664:b7a400] [com.apple.dt.xctest:Default] Handling kAXUserTestingNotification from AX element pid: 82669, elementOrHash.elementID: 0.1 (0x131a0a7f0)
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 Df testmanagerd[82664:b7a400] [com.apple.dt.xctest:Default] Got user testing notification with payload {
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW]     event = TouchEventsCompleted;
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] }
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 Df testmanagerd[82664:b7bc91] [com.apple.dt.xctest:Default] Calling handler for AX notification kAXUserTestingNotification from AX element pid: 82669, elementOrHash.elementID: 0.1 with payload {
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW]     event = TouchEventsCompleted;
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] }
> 2021-08-02 16:22:58:042 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-02 16:22:58.041 Df testmanagerd[82664:b7bc91] [com.apple.dt.xctest:Default] Ev
> ```
> 
> I'd like to check you did not set something disabling animation wait etc such as `animationCoolOffTimeout`.

I set animationCoolOffTimeout = 0 at above log, but I set animationCoolOffTimeout = 1, this issue also exist.
Log: https://gist.github.com/candialala/4277631f61ffe11bbd68637e41e66c03

**Comment by KazuCocoa** [comment] 2021-08-03 17:23
Thanks.

```
021-08-03 16:08:42:266 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-03 16:08:42.264 Df testmanagerd[66295:6a8e01] [com.apple.dt.xctest:Default] Event 
2021-08-03 16:08:42:266 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] <XCSynthesizedEventRecord 'tap display 1'>
2021-08-03 16:08:42:266 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] Path 1:
2021-08-03 16:08:42:266 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 	Touch down at 283.0, 211.0, offset=0.00s
2021-08-03 16:08:42:266 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 	Touch up at 283.0, 211.0, offset=0.05s confirmed by TouchEventsCompleted.
2021-08-03 16:08:42:266 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-03 16:08:42.265 Df WebDriverAgentRunner-Runner[66305:6a76dd] (WebDriverAgentLib) Quiescence checks are disabled for com.glip.mobile.rc application. Making it to believe it is idling
2021-08-03 16:08:42:266 - [debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"2CC50212-8473-48F5-A774-729DC9563AC8"}
```

Did you set caps like `waitForQuiescence`?
Could you run the same action without any such timeout stuff? then, the behavior will be close to vanilla XCTest.

**Comment by candialala** [comment] 2021-08-04 01:14
> Thanks.
> 
> ```
> 021-08-03 16:08:42:266 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-03 16:08:42.264 Df testmanagerd[66295:6a8e01] [com.apple.dt.xctest:Default] Event 
> 2021-08-03 16:08:42:266 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] <XCSynthesizedEventRecord 'tap display 1'>
> 2021-08-03 16:08:42:266 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] Path 1:
> 2021-08-03 16:08:42:266 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 	Touch down at 283.0, 211.0, offset=0.00s
> 2021-08-03 16:08:42:266 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 	Touch up at 283.0, 211.0, offset=0.05s confirmed by TouchEventsCompleted.
> 2021-08-03 16:08:42:266 - [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-08-03 16:08:42.265 Df WebDriverAgentRunner-Runner[66305:6a76dd] (WebDriverAgentLib) Quiescence checks are disabled for com.glip.mobile.rc application. Making it to believe it is idling
> 2021-08-03 16:08:42:266 - [debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"2CC50212-8473-48F5-A774-729DC9563AC8"}
> ```
> 
> Did you set caps like `waitForQuiescence`?
> Could you run the same action without any such timeout stuff? then, the behavior will be close to vanilla XCTest.

I set appium:waitForQuiescence = false, But if waitForQuiescence is not set, it defaults to true and each operation is very slow. And I didn't set waitForIdleTimeout, it defaults to 10.

**Comment by KazuCocoa** [comment] 2021-08-04 02:46
> appium:waitForQuiescence
> Consider using waitForIdleTimeout capability instead for this purpose since Appium 1.20.0
https://github.com/appium/appium-xcuitest-driver

How about using `waitForIdleTimeout` (a bit small number) instead of `waitForQuiescence`?

I guess if the current issue was because of such no wait time, probably wait XX seconds explicitly is the primary way to avoid it. https://discuss.appium.io/ may have some good idea.

**Comment by candialala** [comment] 2021-08-04 03:02
> How about using `waitForIdleTimeout` (a bit small number) instead of `waitForQuiescence`?
> 
> I guess if the current issue was because of such no wait time, probably wait XX seconds explicitly is the primary way to avoid it. https://discuss.appium.io/ may have some good idea.

I set waitForIdleTimeout =1, it also dosen't work. Because its default value of 10 is not in effect. I have to wait time after the dump in my script, It's so unfriendly to me. And I don't want to do that much waiting in the script.
It is worth mentioning that previous versions of WDA did not have this problem.

**Comment by KazuCocoa** [comment] 2021-08-04 17:16
The method was removed as https://github.com/appium/WebDriverAgent/pull/404/files#diff-b6f0fc08b8f9f714de040ea58a281a784d2e976103c812aabb23348b98018d82L41
You could change the method on your local and try if it works. The removal was to reduce WDA hacks to follow vanilla XCTest as possible.

So, if it might also happen on vanilla XCTest, I would report it to Apple to improve their vanilla XCTest behavior.

**Comment by mykola-mokhnach** [comment] 2021-08-06 05:33
Closed as not an issue

**Closed by mykola-mokhnach** 2021-08-06 05:33 UTC
Labels: NotABug, XCUITest, NeedsInfo

**Comment by candialala** [comment] 2021-08-08 06:18
> The method was removed as https://github.com/appium/WebDriverAgent/pull/404/files#diff-b6f0fc08b8f9f714de040ea58a281a784d2e976103c812aabb23348b98018d82L41
> You could change the method on your local and try if it works. The removal was to reduce WDA hacks to follow vanilla XCTest as possible.
> 
> So, if it might also happen on vanilla XCTest, I would report it to Apple to improve their vanilla XCTest behavior.

Thanks. I change the method that add [self fb_waitUntilFrameIsStable] on my local, it works.

**Comment by candialala** [comment] 2021-08-23 06:31
> The method was removed as https://github.com/appium/WebDriverAgent/pull/404/files#diff-b6f0fc08b8f9f714de040ea58a281a784d2e976103c812aabb23348b98018d82L41
> You could change the method on your local and try if it works. The removal was to reduce WDA hacks to follow vanilla XCTest as possible.
> 
> So, if it might also happen on vanilla XCTest, I would report it to Apple to improve their vanilla XCTest behavior.

Have you ever reported this to Apple and if it hasn't been resolved, can you add back the [self fb_waitUntilFrameIsStable] method to fix this problem?

**Comment by KazuCocoa** [comment] 2021-08-23 08:15
> if it might also happen on vanilla XCTest

Did you confirm if it occurred with vanilla XCTest as well? Only you could confirm it since no one had the app. Apple will need the app to investigate the cause when you report it, I guess.

I think if we need the hack in WDA, then probably it must be configurable via settings api and be disabled by default to keep vanilla XCTest behavior.
