### ISSUE TITLE
Get "value" from elemnet located by ios_class_chain is wrong

### ISSUE THREAD

**Issue by markhuangext359** [appium/appium#14435] opened 2020-06-11 07:37 UTC
## The problem

# page_source
```
<XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="274" width="320" height="44">
    <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" enabled="true" visible="true" x="15" y="283" width="54" height="26" name="HTTPS" label="HTTPS" value="HTTPS">
    </XCUIElementTypeStaticText>
    <XCUIElementTypeSwitch type="XCUIElementTypeSwitch" enabled="true" visible="true" x="259" y="280" width="51" height="32" value="0">
    </XCUIElementTypeSwitch>
</XCUIElementTypeOther>
```

# Normal case:
Locate the switch element with class name, attribute "text" will change with switch status
```
>>> e = wd.find_element_by_ios_class_chain("**/XCUIElementTypeSwitch")
>>> e.id
u'25000000-0000-0000-5537-000000000000'
# current switch is "off"
>>> e.text
u'0'
# touch switch turn to "on"
>>> e.text
u'1'
```

# Bug case:
Use related path to find the same switch(with same element id), the "text" always return "0"
```
>>> el = wd.find_element_by_ios_class_chain("**/*[$type = 'XCUIElementTypeStaticText' and name='HTTPS'$][-2]/XCUIElementTypeSwitch")
# NOTE: the id is the same as normal case
>>> el.id
u'25000000-0000-0000-5537-000000000000'
# current switch is "on"
>>> el.text
u'0'
# touch switch turn to "off"
>>> el.text
u'0'
# touch switch turn to "on"
>>> el.text
u'0'
```

## Environment

* Appium version:
    - 1.15.1
* Desktop OS/version used to run Appium:
    - macOS 10.15.4 (19E287)
* Node.js version (unless using Appium.app|exe):
   - v12.12.0
* Npm or Yarn package manager:
   - npm
* Mobile platform/version under test:
   - iPhone 6 with iOS 11.4
* Real device or emulator/simulator:
   - Real device
* Appium CLI or Appium.app|exe:
   -  Appium CLI

## Link to Appium logs

[gist link](https://gist.github.com/markhuangext359/a1c3c0b79562c34f255fc6f30ff2aca6/)

**Comment by mykola-mokhnach** [comment] 2020-06-11 07:53
Duplicate of https://github.com/appium/appium/issues/13691

**Closed by mykola-mokhnach** 2020-06-11 07:53 UTC
