### ISSUE TITLE
Recieving an error while using Appium getActiveElement command.

### ISSUE THREAD

**Issue by mnkravets** [appium/appium#15751] opened 2021-08-18 18:04 UTC
browser.getActiveElement();

INFO webdriver: [GET] http://127.0.0.1:4723/wd/hub/session/2184cd35-6504-41ff-b264-0ead29c5cf09/element/active
[0-0] 2021-08-18T17:42:16.299Z WARN webdriver: Request failed with status 404 due to The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource

Did anyone had this problem before? What I've noticed is that webdriver.io docs states that getActiveElement command should send POST request. In my case it sends GET request.

Thank you a lot, if anyone knows the solution to this...

**Comment by jlipps** [comment] 2021-08-18 18:18
Please link to a gist of the Appium server log

**Comment by mnkravets** [comment] 2021-08-18 18:49
[WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:8201/wd/hub/session/5f2fec40-9012-46bf-a671-55715f417c97/elements] with body: {"strategy":"xpath","selector":"//android.widget.EditText[@resource-id=\"user_name\"]","context":"","multiple":true}
[WD Proxy] Got response with status 200: {"sessionId":"5f2fec40-9012-46bf-a671-55715f417c97","value":[]}
[W3C (69554c97)] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/elements 200 95 ms - 12
[HTTP] 
[HTTP] --> POST /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/touch/perform
[HTTP] {"actions":[{"action":"tap","options":{"x":182,"y":399}}]}
[W3C (69554c97)] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"x":182,"y":399}}],"69554c97-d77d-4ac0-aea4-aa212515d759"]
[WD Proxy] Proxying [POST /appium/tap] to [POST http://127.0.0.1:8201/wd/hub/session/5f2fec40-9012-46bf-a671-55715f417c97/appium/tap] with body: {"x":182,"y":399,"undefined":null}
[WD Proxy] Got response with status 200: {"sessionId":"5f2fec40-9012-46bf-a671-55715f417c97","value":null}
[W3C (69554c97)] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/touch/perform 200 166 ms - 14
[HTTP] 
[HTTP] --> GET /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/element/active
[HTTP] {}
[W3C (69554c97)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/element/active' to command name 'active'
[WD Proxy] Proxying [GET /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/element/active] to [GET http://127.0.0.1:8201/wd/hub/session/5f2fec40-9012-46bf-a671-55715f417c97/element/active] with no body
[WD Proxy] Got response with status 404: {"sessionId":null,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":"io.appium.uiautomator2.common.exceptions.UnknownCommandException: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:75)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler...
[W3C] Matched W3C error code 'unknown command' to UnknownCommandError
[HTTP] <-- GET /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/element/active 404 14 ms - 3529
[HTTP] 
[HTTP] --> GET /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/element/active
[HTTP] {}
[W3C (69554c97)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/element/active' to command name 'active'
[WD Proxy] Proxying [GET /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/element/active] to [GET http://127.0.0.1:8201/wd/hub/session/5f2fec40-9012-46bf-a671-55715f417c97/element/active] with no body
[WD Proxy] Got response with status 404: {"sessionId":null,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":"io.appium.uiautomator2.common.exceptions.UnknownCommandException: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:75)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler...
[W3C] Matched W3C error code 'unknown command' to UnknownCommandError
[HTTP] <-- GET /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/element/active 404 8 ms - 3529
[HTTP] 
[HTTP] --> GET /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/element/active
[HTTP] {}
[W3C (69554c97)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/element/active' to command name 'active'
[WD Proxy] Proxying [GET /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/element/active] to [GET http://127.0.0.1:8201/wd/hub/session/5f2fec40-9012-46bf-a671-55715f417c97/element/active] with no body
[WD Proxy] Got response with status 404: {"sessionId":null,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":"io.appium.uiautomator2.common.exceptions.UnknownCommandException: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:75)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler...
[W3C] Matched W3C error code 'unknown command' to UnknownCommandError
[HTTP] <-- GET /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/element/active 404 14 ms - 3529
[HTTP] 
[HTTP] --> GET /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/element/active
[HTTP] {}
[W3C (69554c97)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/element/active' to command name 'active'
[WD Proxy] Proxying [GET /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/element/active] to [GET http://127.0.0.1:8201/wd/hub/session/5f2fec40-9012-46bf-a671-55715f417c97/element/active] with no body
[WD Proxy] Got response with status 404: {"sessionId":null,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":"io.appium.uiautomator2.common.exceptions.UnknownCommandException: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:75)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler...
[W3C] Matched W3C error code 'unknown command' to UnknownCommandError
[HTTP] <-- GET /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759/element/active 404 8 ms - 3529
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759
[HTTP] {}
[W3C (69554c97)] Calling AppiumDriver.deleteSession() with args: ["69554c97-d77d-4ac0-aea4-aa212515d759"]
[BaseDriver] Event 'quitSessionRequested' logged at 1629312407872 (14:46:47 GMT-0400 (Eastern Daylight Time))
[Appium] Removing session 69554c97-d77d-4ac0-aea4-aa212515d759 from our master session list
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[WD Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8201/wd/hub/session/5f2fec40-9012-46bf-a671-55715f417c97] with no body
[WD Proxy] Got response with status 200: {"sessionId":"5f2fec40-9012-46bf-a671-55715f417c97","value":null}
[ADB] Running '/Users/mnkravets/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.servicenow.requestor'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8201 
[ADB] Running '/Users/mnkravets/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp:8201'
[UiAutomator2] Restoring hidden api policy to the device default configuration
[ADB] Running '/Users/mnkravets/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[BaseDriver] Event 'quitSessionFinished' logged at 1629312408203 (14:46:48 GMT-0400 (Eastern Daylight Time))
[W3C (69554c97)] Received response: null
[W3C (69554c97)] But deleting session, so not returning
[W3C (69554c97)] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/69554c97-d77d-4ac0-aea4-aa212515d759 200 332 ms - 14
[HTTP] 
[Instrumentation] .
[Instrumentation] Time: 18.1
[Instrumentation] 
[Instrumentation] OK (1 test)
[Instrumentation] The process has exited with code 0

**Comment by jlipps** [comment] 2021-08-18 19:29
I think the issue is that this driver doesn't support that command. Which makes sense, because I don't think the UiAutomator APIs give us anything like the concept of an 'active' element.

**Comment by KazuCocoa** [comment] 2021-08-18 19:34
Maybe https://github.com/appium/appium-uiautomator2-driver/pull/457 is to support it. it will be in 1.22, so you can try out appium 1.22 rc for now.

**Comment by mykola-mokhnach** [comment] 2021-08-18 20:29
Closed as not an issue as per comment above

**Closed by mykola-mokhnach** 2021-08-18 20:29 UTC
