### ISSUE TITLE
Abnormal Instruments termination

### ISSUE THREAD

**Issue by go2guy** [appium/appium#6285] opened 2016-03-15 14:11 UTC
## The problem

On IOS I'm seeing Abnornal Instruments termination when asserting on a text value on the page.  I have tried by Xpath and by Page Object using uiAutomator and it is the same result.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.0
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: MAC OSX El Capitan Version 10.11.3 (15D21)
- Node.js version (unless using Appium.app|exe): 5.5.0
- Mobile platform/version under test: Iphone 6S
- Real device or emulator/simulator: Real Device
- Appium CLI or Appium.app|exe:  CLI
- Java-Clent 3.4.0
- Selenium 2.52.0
## Details

Everything is working fine until I click on a button and goto assert on an error condition on the staticText field, to ensure the text on the screen is present. I've tripled checked the Xpath is valid using Appium.exe locator with xpath.

[Appium] Closing session, cause was 'An unknown server-side error occurred while processing the command. Original error: Abnornal Instruments termination!'

This is reproducible every time.
## Link to Appium logs

https://gist.github.com/nuggit32/6cd0d787fc28d5df0e2c
## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/nuggit32/073858c6ee65ffa22b0c

Failing on line #93 on the 
        Assert.assertEquals(
            ((IOSDriver<?>) driver).findElementByXPath("//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIAStaticText[1]"),
            "Please correct the following errors and try again.");

**Comment by scottdixon** [comment] 2016-03-15 17:25
Looks like the app crashes `The target application appears to have died`.

Does it run fine in the simulator without Appium? And do you have the same issue with 1.4.16?

Thanks for the typo report - I'll update the logs.

**Comment by nuggit32** [comment] 2016-03-15 18:37
@scottdixon one would think the app crashed.  There is no crash log to suggest the app crashed do to coding issue.

I confirmed the app is not crashing on the actual click of the submit button. After I clicked the submit button I put a thread.sleep for 30 seconds to see if the app crashed on the click.  The app is up and the error messages are displayed for the test case.  After the thread.sleep is finished an assert is called and the app dies.  
Calling an Assert should not crash an app? 
I also tried clicking another element and that as well crashed.  It appears that after the click of the submit button any type of ios driver call is making the app disappear.

I will rollback to 1.4.16 to see if the issue is there as well.

This is on a Real device and does not fail during manual intervention.

**Comment by nuggit32** [comment] 2016-03-15 18:57
@scottdixon 
Gist for 1.4.16 version
https://gist.github.com/nuggit32/cc666057bb73094671c5

My observations on this version were slightly different.  As soon as I clicked the submit button, I saw a glimpse of the error message, but the app disappeared and it appears to hang on these lines for the thread.sleep for 30 seconds before failing to find the elements in the Assert


[36minfo[39m: [debug] [90m[INSTSERVER] Instruments exited with code 0[39m
[36minfo[39m: [debug] Cleaning up after instruments exit
[36minfo[39m: [debug] Instruments exited unexpectedly
[36minfo[39m: [debug] Shutting down command proxy and ignoring any errors
[36minfo[39m: [debug] Destroying instruments client socket.
[36minfo[39m: [debug] Closing socket server.
[36minfo[39m: [debug] Instruments socket server was closed
[36minfo[39m: [debug] Stopping iOS log capture
[36minfo[39m: [debug] Running ios sim reset flow
[36minfo[39m: [debug] Killing the simulator process
[36minfo[39m: [debug] Killing any other simulator daemons
[36minfo[39m: [debug] Killall Simulator
[36minfo[39m: [debug] On a real device; cannot clean device state
[36minfo[39m: [debug] Cleaning up appium session

So in 1.5.0 - The app stays up through the thread.sleep after the submit button.
In 1.4.16 - the app dies after the submit button but the code honors the thread.sleep before failing on the assert for element not found.

I don't have a app crash log.  I will check with the developer to see if something needs enabled to get a crash log.

**Comment by nuggit32** [comment] 2016-03-15 19:38
@scottdixon I was wrong that I was not getting a crash log.  My xcode needed to be restarted to see the crash logs.  So yes the app did crash under Automation but not in a manual test.  Have you ever seen where Automation is causing the app to crash since manual testing is not crashing it?

**Comment by scottdixon** [comment] 2016-03-15 21:38
Thanks for the update. I suspect it's an Instruments bug - which would explain why it crashes under automation.

This appears to be a common instruments issue - see if any of these help: http://stackoverflow.com/questions/10317858/ios-uiautomation-simulator-5-0-the-target-application-appears-to-have-died

**Comment by shivakrishnach31** [comment] 2016-05-12 05:23
@scottdixon , I am experiencing the same issue when I uninstalled the App using removeApp() method on real device. 
Environment: Appium 1.5.2/iPad Air2/XCode 7.3.1

**Comment by nuggit32** [comment] 2016-06-22 17:27
@scottdixon  @shivakrishnach31 I'm seeing the same error on 1.5.3 Appium/Java Client 4.0.0 as well on the removeApp() method.  App uninstalled then get error.

**Comment by IevgenC** [comment] 2016-08-17 15:54
In my case tests started to crash an app after I've updated to xCode 7.3.1 on remote machine. On my local machine I have xCode 7.3 and tests are working fine. Both machines has Appium 1.5.3

**Closed** 2017-07-15 06:27 UTC
Labels: iOS
