### ISSUE TITLE
Summary: [Appium - iOS] Appium server is detecting incorrect udid and throws error message “Could not install app” on switching the iOS  devices

### ISSUE THREAD

**Issue by joepreethesh** [appium/appium#14003] opened 2020-02-28 05:26 UTC
Summary: [Appium] Appium server is detecting incorrect udid and throws error message “Could not install app” on switching the iOS  devices

Precondition:
1. Set the Appium desired capability to “auto”

Configuration:
Appium server version - 1.16.0, 1.15.1
Devices - iPad Pro, iPhone 7 Plus, iPad mini 4 (OS version -13.3) 
Mac OS - Mojave

Steps:
1. Connect a device(iPhone) to a Mac system
2. Start Appium server and run a test script
-> App launches and execution continues without any issues
3. Connect a device(iPad) to a Mac system
4. Start Appium server and run the test script
5. Check the Appium server logs

Actual Result:
1. Appium Server logs reads “Multiple devices found: <udid of phone>, <udid of iPad>” even if only one device is connected
2.”Could not install app: Couldn’t push */Assets.car" message is displayed
[appium-server-logs.txt](https://github.com/appium/appium/files/4265357/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment] 2020-02-28 06:41
The server works as designed. `auto` simply means `get the first device from the list`. It cannot detect which devices are currently `busy`.

Closed as duplicate of https://github.com/appium/appium/issues/10383

**Closed by mykola-mokhnach** 2020-02-28 06:41 UTC
