### ISSUE TITLE
appium client error

### ISSUE THREAD

**Issue by winson317** [appium/appium#13319] opened 2019-09-30 07:10 UTC
[Appium] Welcome to Appium v1.13.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 5 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"automationName":"XCUITest","bundleId":"me.ele.lpd.talaris","deviceName":"iPhone","noReset":true,"platformName":"iOS","platformVersion":"12.1.4","udid":"be2d1a4cb8a268ae0b3cdef9735fe6cad5fc0028","xcodeOrgId":"VYXZ9QYJGK","xcodeSigningId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","bundleId":"me.ele.lpd.talaris","deviceName":"iPhone","noReset":true,"platformName":"iOS","platformVersion":"12.1.4","udid":"be2d1a4cb8a268ae0b3cdef9735fe6cad5fc0028","xcodeOrgId":"VYXZ9QYJGK","xcodeSigningId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1569827353067 (15:09:13 GMT+0800 (CST))
[Appium] Appium v1.13.0 creating new XCUITestDriver (v2.113.2) session
[Appium] Capabilities:
[Appium]   automationName: XCUITest
[Appium]   bundleId: XXX
[Appium]   deviceName: iPhone
[Appium]   noReset: true
[Appium]   platformName: iOS
[Appium]   platformVersion: 12.1.4
[Appium]   udid: be2d1a4cb8a268ae0b3cdef9735fe6cad5fc3579
[Appium]   xcodeOrgId: VYXZ9QYJHF
[Appium]   xcodeSigningId: iPhone Developer
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"automationName":"XCUITest...
[BaseDriver] Session created with session id: 143a825b-21b1-4e02-93a8-42ffe00dbf8f
[XCUITest] Current user: 'chenweichun'
[XCUITest] Available devices: be2d1a4cb8a268ae0b3cdef9735fe6cad5fc0028
[XCUITest] Creating iDevice object with udid 'be2d1a4cb8a268ae0b3cdef9735fe6cad5fc0028'
[XCUITest] Determining device to run tests on: udid: 'be2d1a4cb8a268ae0b3cdef9735fe6cad5fc0028', real device: true
[XCUITest] iOS SDK Version set to '13.0'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1569827354055 (15:09:14 GMT+0800 (CST))
[BaseDriver] Event 'appConfigured' logged at 1569827354057 (15:09:14 GMT+0800 (CST))
[BaseDriver] Event 'resetStarted' logged at 1569827354058 (15:09:14 GMT+0800 (CST))
[XCUITest] Reset: fullReset not set. Leaving as is
[BaseDriver] Event 'resetComplete' logged at 1569827354059 (15:09:14 GMT+0800 (CST))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[XCUITest] Cannot get the name of the crashes folder for the device with udid 'be2d1a4cb8a268ae0b3cdef9735fe6cad5fc0028'. Original error: Command 'idevicename -u be2d1a4cb8a268ae0b3cdef9735fe6cad5fc0028' exited with code 255
[BaseDriver] Event 'logCaptureStarted' logged at 1569827354906 (15:09:14 GMT+0800 (CST))
[XCUITest] Setting up real device
[XCUITest] Calling: 'ios-deploy --exists --id be2d1a4cb8a268ae0b3cdef9735fe6cad5fc0028 --bundle_id me.ele.lpd.talaris'
[XCUITest] Stdout: '[....] Waiting for iOS device to be connected
[XCUITest] [....] Using be2d1a4cb8a268ae0b3cdef9735fe6cad5fc0028 (N56AP, iPhone 6 Plus, iphoneos, arm64) a.k.a. 'iPhone'.
[XCUITest] true
[XCUITest] '
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[XCUITest] Cannot retrieve WDA build settings. Original error: Command 'xcodebuild -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -showBuildSettings' exited with code 66
[XCUITest] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[XCUITest]     at assertPath (path.js:39:11)
[XCUITest]     at Object.normalize (path.js:1122:5)
[XCUITest]     at XCUITestDriver.normalize [as startWda] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:476:14)
[XCUITest] Cannot retrieve WDA build settings. Original error: Command 'xcodebuild -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -showBuildSettings' exited with code 66
[BaseDriver] Event 'newSessionStarted' logged at 1569827359401 (15:09:19 GMT+0800 (CST))
[MJSONWP] Encountered internal error running command: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[MJSONWP]     at assertPath (path.js:39:11)
[MJSONWP]     at Object.normalize (path.js:1122:5)
[MJSONWP]     at XCUITestDriver.normalize [as deleteSession] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:610:39)
[HTTP] <-- POST /wd/hub/session 500 6337 ms - 206
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 6 ms - 57

**Comment by mykola-mokhnach** [comment] 2019-09-30 08:04
Duplicate of https://github.com/appium/appium/issues/13318

**Closed by mykola-mokhnach** 2019-09-30 08:04 UTC

**Comment by mykola-mokhnach** [comment] 2019-09-30 08:06
This issue happens because Appium cannot figure out the derived data path root. Please update to v. 1.15 to workaround it

**Comment by mykola-mokhnach** [comment] 2019-09-30 08:07
Or fix the WDA source, so the `xcodebuild -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -showBuildSettings` does not return an error code
