### ISSUE TITLE
macOS Catalina :Command 'carthage bootstrap --platform iOS\,tvOS' exited with code 1

### ISSUE THREAD

**Issue by ishita91** [appium/appium#14501] opened 2020-06-30 21:19 UTC
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: v1.17.1
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: macOS Catalina 10.15.5
* Node.js version (unless using Appium.app|exe):6.14.4
* Npm or Yarn package manager:NA
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium Desktop client

## Details
Error remains same:
Command 'carthage bootstrap --platform iOS\,tvOS' exited with code 1 #12841

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment] 2020-07-01 00:54
1. Could you attach the full appium server log?
2. How about running the below command by manual?

```
$ cd /your/installed/path/appium/node_modules/appium-webdriveragent/
$ carthage bootstrap --platform iOS\,tvOS
```

We generally do not recommend to install appium as sudo, but if the cause is such permission issue, typical case is sudo install in my experiences.

> Make sure you have not installed Node or Appium with sudo, otherwise you'll run into problems

https://appium.io/docs/en/about-appium/getting-started/

**Comment by mykola-mokhnach** [comment] 2020-07-01 05:51
Closed as incomplete. Please look for multiple duplicates having the same header

**Closed by mykola-mokhnach** 2020-07-01 05:51 UTC
Labels: NeedsInfo
