### ISSUE TITLE
WebDriverAgentRunner tests failed on IOS 13.4.1 , Xcode  11.4.1  and Appium 1.15.0

### ISSUE THREAD

**Issue by svm0219** [appium/appium#14306] opened 2020-05-08 05:08 UTC
## The problem
WebDriverAgentRunner tests failed on IOS 13.4.1 , Xcode  11.4.1  and Appium 1.15.0

## Environment
Appium 1.15.0
Mac OS 10.15.4
iPhone 11 Pro , OS 13.4.1

## Details
 WebDriverAgent build is Successful, But when I Test WebDriverAgentRunner on iphone it gives error "Failing tests: WebDriverAgentRunner:
		-[UITestingUITests testRunner]"

## Link to Appium logs
https://gist.github.com/svm0219/6e4d50b260568ba8dbc2dd072dc0113b

## Code To Reproduce Issue [ Good To Have ]
NA

**Comment by mykola-mokhnach** [comment] 2020-05-08 07:10
Duplicate of https://github.com/appium/appium/issues/13949

**Closed by mykola-mokhnach** 2020-05-08 07:10 UTC
