### ISSUE TITLE
appium 1.6.2- beta not scroll page to find element 

### ISSUE THREAD

**Issue by kineret321** [appium/appium#7363] opened 2016-12-05 15:16 UTC
Hi,

Im using appium 1.6.2- beta,  XCUITestDriver version: 2.0.36, ios 10.0.1.
Im trying to find element on the bottom of the page, 
When i used appium 1.6.1- beta for the same page and the same code it scroll down until the element was visible and perform click, but with appium 1.6.2 it seems to perform click even if the element not visible (not sure where it perform the click) -not scroll down and search the element

element=wait.until(EC.presence_of_element_located((By.ID, "temp_slider_api_12.xml")))
element.click()

logs:
[Appium] Welcome to Appium v1.6.2
[Appium] Non-default server args:
[Appium]   log: '/Users/israellocal/Desktop/appium_log.txt'
[Appium]   showIOSLog: true
[Appium] Deprecated server args:
[Appium]   --show-ios-log => --default-capabilities '{"showIOSLog":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   showIOSLog: true
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"deviceName":"10.0.1","udid":"4ba95a2da3af6869344047620c1755dd23cdbc57","app":"/Users/israellocal/Downloads/FMLTester.ipa","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","appium-version":"1.6","xcodeConfigFile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig","newCommandTimeout":0,"platformVersion":"10.0.1","fullReset":true,"platformName":"ios","automationName":"XCUITest"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"10.0.1","udid":"4ba95a2da3af6869344047620c1755dd23cdbc57","app":"/Users/israellocal/Downloads/FMLTester.ipa","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","appium-version":"1.6","xcodeConfigFile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig","newCommandTimeout":0,"platformVersion":"10.0.1","fullReset":true,"platformName":"ios","automationName":"XCUITest"},null,null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   deviceName: '10.0.1'
[Appium]   udid: '4ba95a2da3af6869344047620c1755dd23cdbc57'
[Appium]   app: '/Users/israellocal/Downloads/FMLTester.ipa'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   appium-version: '1.6'
[Appium]   xcodeConfigFile: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig'
[Appium]   newCommandTimeout: 0
[Appium]   platformVersion: '10.0.1'
[Appium]   fullReset: true
[Appium]   platformName: 'ios'
[Appium]   automationName: 'XCUITest'
[Appium]   showIOSLog: true
[debug] [XCUITest] XCUITestDriver version: 2.0.36
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appium-version.
[BaseDriver] Session created with session id: e6d989cf-a698-4390-bb9c-6aee71104073
[debug] [XCUITest] Xcode version set to '8.1'
[debug] [XCUITest] iOS SDK Version set to '10.1'
[debug] [XCUITest] Available devices: 4ba95a2da3af6869344047620c1755dd23cdbc57
[debug] [XCUITest] Creating iDevice object with udid 4ba95a2da3af6869344047620c1755dd23cdbc57
[XCUITest] Determining device to run tests on: udid: '4ba95a2da3af6869344047620c1755dd23cdbc57', real device: true
[BaseDriver] Using local app '/Users/israellocal/Downloads/FMLTester.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/2016115-59631-bm0yjq.84lfp0t3xr/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/2016115-59631-bm0yjq.84lfp0t3xr/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/2016115-59631-bm0yjq.84lfp0t3xr/Payload/FMLTester.app'
[debug] [XCUITest] Checking whether app '/var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/2016115-59631-bm0yjq.84lfp0t3xr/Payload/FMLTester.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/2016115-59631-bm0yjq.84lfp0t3xr/Payload/FMLTester.app': 'com.pingidentity.fmltester.enterprise'
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset requested. Forcing app install after uninstall app
[debug] [XCUITest] App installed successfully.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Using Xcode configuration file: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig'
[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=4ba95a2da3af6869344047620c1755dd23cdbc57 --xcode-version 8 --xcode-config-file "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig"' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/israellocal/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/03C28903-DD7B-40A2-BA23-33C15A60FDD4/Session-WebDriverAgentRunner-2016-12-05_165543-k8ln4v.log
[XCUITest] Detected that WebDriverAgent is running at url 'http://10.8.3.3:8100'
[XCUITest] WebDriverAgent started at url 'http://10.8.3.3:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.pingidentity.fmltester.enterprise","arguments":[],"environment":{},"shouldWaitForQuiescence":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"26C2E83B-2B17-4B70-985A-71D74B1D6C4D","capabilities":{"device":"iphone","browserName":"FML Tester","sdkVersion":"10.0.1","CFBundleIdentifier":"com.pingidentity.fmltester.enterprise"}},"sessionId":"26C2E83B-2B17-4B70-985A-71D74B1D6C4D","status":0}
[debug] [XCUITest] Setting initial orientation to 'PORTRAIT'
[debug] [JSONWP Proxy] Proxying [POST /orientation] to [POST http://localhost:8100/session/26C2E83B-2B17-4B70-985A-71D74B1D6C4D/orientation] with body: {"orientation":"PORTRAIT"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"26C2E83B-2B17-4B70-985A-71D74B1D6C4D","status":0}
[Appium] New XCUITestDriver session created successfully, session e6d989cf-a698-4390-bb9c-6aee71104073 added to master session list
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"deviceName":"10.0.1","udid":"4ba95a2da3af6869344047620c1755dd23cdbc57","app":"/Users/israellocal/Downloads/FMLTester.ipa","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","appium-version":"1.6","xcodeConfigFile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig","newCommandTimeout":0,"platformVersion":"10.0.1","fullReset":true,"platformName":"ios","automationName":"XCUITest","showIOSLog":true}
[HTTP] <-- POST /wd/hub/session 200 29769 ms - 747 
[HTTP] --> POST /wd/hub/session/e6d989cf-a698-4390-bb9c-6aee71104073/timeouts/implicit_wait {"sessionId":"e6d989cf-a698-4390-bb9c-6aee71104073","ms":3000}
[debug] [MJSONWP] Calling AppiumDriver.implicitWait() with args: [3000,"e6d989cf-a698-4390-bb9c-6aee71104073"]
[debug] [XCUITest] Executing command 'implicitWait'
[debug] [BaseDriver] Set implicit wait to 3000ms
[debug] [MJSONWP] Responding to client with driver.implicitWait() result: null
[HTTP] <-- POST /wd/hub/session/e6d989cf-a698-4390-bb9c-6aee71104073/timeouts/implicit_wait 200 6 ms - 76 
[HTTP] --> POST /wd/hub/session/e6d989cf-a698-4390-bb9c-6aee71104073/element {"using":"id","sessionId":"e6d989cf-a698-4390-bb9c-6aee71104073","value":"temp_slider_api_12.xml"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","temp_slider_api_12.xml","e6d989cf-a698-4390-bb9c-6aee71104073"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 3000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/26C2E83B-2B17-4B70-985A-71D74B1D6C4D/element] with body: {"using":"id","value":"temp_slider_api_12.xml"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"B6DFB539-0095-415C-AB0A-1BA9D61DE650","type":"XCUIElementTypeStaticText","label":"temp slider api 12"},"sessionId":"26C2E83B-2B17-4B70-985A-71D74B1D6C4D","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"B6DFB539-0095-415C-AB0A-1BA9D61DE650","type":"XCUIElementTypeStaticText","label":"temp slider api 12"}
[HTTP] <-- POST /wd/hub/session/e6d989cf-a698-4390-bb9c-6aee71104073/element 200 1189 ms - 186 
[HTTP] --> POST /wd/hub/session/e6d989cf-a698-4390-bb9c-6aee71104073/element/B6DFB539-0095-415C-AB0A-1BA9D61DE650/click {"sessionId":"e6d989cf-a698-4390-bb9c-6aee71104073","id":"B6DFB539-0095-415C-AB0A-1BA9D61DE650"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/e6d989cf-a698-4390-bb9c-6aee71104073/element/B6DFB539-0095-415C-AB0A-1BA9D61DE650/click] to [POST http://localhost:8100/session/26C2E83B-2B17-4B70-985A-71D74B1D6C4D/element/B6DFB539-0095-415C-AB0A-1BA9D61DE650/click] with body: {"sessionId":"e6d989cf-a698-4390-bb9c-6aee71104073","id":"B6DFB539-0095-415C-AB0A-1BA9D61DE650"}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"B6DFB539-0095-415C-AB0A-1BA9D61DE650","value":"","sessionId":"26C2E83B-2B17-4B70-985A-71D74B1D6C4D"}
[JSONWP Proxy] Replacing sessionId 26C2E83B-2B17-4B70-985A-71D74B1D6C4D with e6d989cf-a698-4390-bb9c-6aee71104073
[HTTP] <-- POST /wd/hub/session/e6d989cf-a698-4390-bb9c-6aee71104073/element/B6DFB539-0095-415C-AB0A-1BA9D61DE650/click 200 1718 ms - 118 
[HTTP] --> POST /wd/hub/session/e6d989cf-a698-4390-bb9c-6aee71104073/element {"using":"id","sessionId":"e6d989cf-a698-4390-bb9c-6aee71104073","value":"inheritSlider"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","inheritSlider","e6d989cf-a698-4390-bb9c-6aee71104073"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 3000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/26C2E83B-2B17-4B70-985A-71D74B1D6C4D/element] with body: {"using":"id","value":"inheritSlider"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"inheritSlider","description":"unable to find an element"},"sessionId":"26C2E83B-2B17-4B70-985A-71D74B1D6C4D","status":7}
[debug] [BaseDriver] Waited for 1115 ms so far
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/26C2E83B-2B17-4B70-985A-71D74B1D6C4D/element] with body: {"using":"id","value":"inheritSlider"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"inheritSlider","description":"unable to find an element"},"sessionId":"26C2E83B-2B17-4B70-985A-71D74B1D6C4D","status":7}
[debug] [BaseDriver] Waited for 2684 ms so far
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/26C2E83B-2B17-4B70-985A-71D74B1D6C4D/element] with body: {"using":"id","value":"inheritSlider"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"inheritSlider","description":"unable to find an element"},"sessionId":"26C2E83B-2B17-4B70-985A-71D74B1D6C4D","status":7}
[HTTP] <-- POST /wd/hub/session/e6d989cf-a698-4390-bb9c-6aee71104073/element 500 4312 ms - 164 
[HTTP] --> POST /wd/hub/session/e6d989cf-a698-4390-bb9c-6aee71104073/element {"using":"id","sessionId":"e6d989cf-a698-4390-bb9c-6aee71104073","value":"inheritSlider"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","inheritSlider","e6d989cf-a698-4390-bb9c-6aee71104073"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 3000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/26C2E83B-2B17-4B70-985A-71D74B1D6C4D/element] with body: {"using":"id","value":"inheritSlider"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"inheritSlider","description":"unable to find an element"},"sessionId":"26C2E83B-2B17-4B70-985A-71D74B1D6C4D","status":7}
[debug] [BaseDriver] Waited for 1095 ms so far
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/26C2E83B-2B17-4B70-985A-71D74B1D6C4D/element] with body: {"using":"id","value":"inheritSlider"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"inheritSlider","description":"unable to find an element"},"sessionId":"26C2E83B-2B17-4B70-985A-71D74B1D6C4D","status":7}
[debug] [BaseDriver] Waited for 2649 ms so far
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/26C2E83B-2B17-4B70-985A-71D74B1D6C4D/element] with body: {"using":"id","value":"inheritSlider"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"inheritSlider","description":"unable to find an element"},"sessionId":"26C2E83B-2B17-4B70-985A-71D74B1D6C4D","status":7}
[HTTP] <-- POST /wd/hub/session/e6d989cf-a698-4390-bb9c-6aee71104073/element 500 4252 ms - 164 
[HTTP] --> POST /wd/hub/session/e6d989cf-a698-4390-bb9c-6aee71104073/element {"using":"id","sessionId":"e6d989cf-a698-4390-bb9c-6aee71104073","value":"inheritSlider"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","inheritSlider","e6d989cf-a698-4390-bb9c-6aee71104073"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 3000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/26C2E83B-2B17-4B70-985A-71D74B1D6C4D/element] with body: {"using":"id","value":"inheritSlider"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"inheritSlider","description":"unable to find an element"},"sessionId":"26C2E83B-2B17-4B70-985A-71D74B1D6C4D","status":7}
[debug] [BaseDriver] Waited for 1065 ms so far
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/26C2E83B-2B17-4B70-985A-71D74B1D6C4D/element] with body: {"using":"id","value":"inheritSlider"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"inheritSlider","description":"unable to find an element"},"sessionId":"26C2E83B-2B17-4B70-985A-71D74B1D6C4D","status":7}
[debug] [BaseDriver] Waited for 2691 ms so far
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/26C2E83B-2B17-4B70-985A-71D74B1D6C4D/element] with body: {"using":"id","value":"inheritSlider"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"inheritSlider","description":"unable to find an element"},"sessionId":"26C2E83B-2B17-4B70-985A-71D74B1D6C4D","status":7}
[HTTP] <-- POST /wd/hub/session/e6d989cf-a698-4390-bb9c-6aee71104073/element 500 4306 ms - 164 
[HTTP] --> POST /wd/hub/session/e6d989cf-a698-4390-bb9c-6aee71104073/element {"using":"id","sessionId":"e6d989cf-a698-4390-bb9c-6aee71104073","value":"inheritSlider"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","inheritSlider","e6d989cf-a698-4390-bb9c-6aee71104073"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 3000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/26C2E83B-2B17-4B70-985A-71D74B1D6C4D/element] with body: {"using":"id","value":"inheritSlider"}
[HTTP] <-- POST /wd/hub/session/e6d989cf-a698-4390-bb9c-6aee71104073/element - - ms - - 
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"inheritSlider","description":"unable to find an element"},"sessionId":"26C2E83B-2B17-4B70-985A-71D74B1D6C4D","status":7}
[debug] [BaseDriver] Waited for 1077 ms so far
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/26C2E83B-2B17-4B70-985A-71D74B1D6C4D/element] with body: {"using":"id","value":"inheritSlider"}

**Comment by viveksinghtt** [comment] 2016-12-21 12:31
@kineret321 did u find a solution for this?

**Comment by imurchie** [comment] 2016-12-21 12:40
It does not automatically scroll anymore. The upstream project cut that out. You will need to manually do it. The easiest way is to use "execute" with "mobile: scroll".

An example in JavaScript
```js
let el = await driver.elementByAccessibilityId('Sliders');
await driver.execute('mobile: scroll', {element: el, toVisible: true});
await el.click();
```

**Comment by viveksinghtt** [comment] 2016-12-21 13:43
@imurchie ok m in python...is der an api exposed for this by python client

**Comment by imurchie** [comment] 2016-12-21 13:52
Yes. http://selenium-python.readthedocs.io/api.html?highlight=execute_script#selenium.webdriver.remote.webdriver.WebDriver.execute_script

**Comment by viveksinghtt** [comment] 2016-12-21 16:33
@imurchie thanx a lot !!!!!!!!!! really appreciate the prompt help!!!!!!!

**Comment by Akulavenkatesh** [comment] 2017-01-11 06:44
@viveksinghtt were you able to solve the scroll issue?

**Comment by viveksinghtt** [comment] 2017-01-11 08:31
@Akulavenkatesh yes i was using execute_script in python with the javascript given above.

**Comment by Akulavenkatesh** [comment] 2017-01-11 08:47
@viveksinghtt will be helpful if you can share the code here

**Comment by viveksinghtt** [comment] 2017-01-11 09:30
@Akulavenkatesh something like this

    def scroll_to(self, el):
        self.driver.execute_script('mobile: scroll', {"element": el, "toVisible": True})

**Comment by Akulavenkatesh** [comment] 2017-01-11 09:56
Thanks @viveksinghtt :) I will try this

**Comment by pavanbachu0604** [comment] 2017-01-11 14:30
Anything for Java ? I am not able to scroll in Appium 1.6.3

**Comment by jlipps** [comment] 2017-01-19 21:59
closing as duplicate of https://github.com/appium/appium/issues/7573

**Closed by jlipps** 2017-01-19 21:59 UTC
Labels: NeedsTriage

**Comment by hemano** [comment] 2017-07-07 06:35
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md
