### ISSUE TITLE
iOS - cannot read attribute 'value" since XCUITest driver version 4.7.3

### ISSUE THREAD

**Issue by StephanB75** [appium/appium#17207] opened 2022-07-15 05:57 UTC
## The problem

Yesterday a new driver version of the XCUITest driver was released.
From that point on my tests cannot get the attribute "value" anymore

## Environment

* Appium version (or git revision) that exhibits the issue: appium 2beta40. / xcuiTest driver 4.7.3
* Last Appium version that did not exhibit the issue (if applicable):  4.7.2
* Desktop OS/version used to run Appium: MacOD 12.3.1
* Node.js version (unless using Appium.app|exe): 16.16.0
* Npm or Yarn package manager: 8.11
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

An unknown server-side error occurred while processing the command. Original error: -[XCElementSnapshot fb_valueForWDAttributeName:]: unrecognized selector sent to instance 0x7fe542f084b0
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'ebwao-ciios02.intern.rm.de', ip: 'fe80:0:0:0:492::5c91:2f11%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_322'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [742d41a5-5d1d-46ef-8b55-51683ba67a49, getElementAttribute {id=4E030000-0000-0000-7D04-000000000000, name=value}]
Capabilities {appium:app: /Users/jenkins/HomeOfQA/wor..., appium:automationName: XCUITest, appium:bundleId: de.rm.app.dev, appium:connectHardwareKeyboard: false, appium:databaseEnabled: false, appium:deviceName: iPhone 8 Plus, appium:forceAppLaunch: false, appium:javascriptEnabled: true, appium:keepKeyChains: false, appium:language: de, appium:locale: de_DE, appium:locationContextEnabled: false, appium:networkConnectionEnabled: false, appium:newCommandTimeout: 120, appium:noReset: false, appium:platformVersion: 15.2, appium:processArguments: {args: [-RSMScanAndGoQrCodeScanResult, 2500, -RSMMuteAppTrackingTranspar..., 1, -RSMDeactivateAccessibility..., 1, -proxyHost=, -proxyPort=, -RSMEnvOverride, RSMQAEnvironment, -RSMOptionResetAccountOnNex..., 1, -RSMOptionDidAskPreConditio..., 1, -AppleLanguages, (de), -NSLanguages, (de), -AppleLocale, de_DE]}, appium:takesScreenshot: true, appium:udid: 0D4E96D6-3341-42D6-A0EA-15D..., appium:useNewWDA: false, appium:waitForIdleTimeout: 1, appium:wdaLaunchTimeout: 60000, appium:wdaLocalPort: 8301, appium:webStorageEnabled: false, platformName: ios}
Element: [[IOSDriver:  on ios (742d41a5-5d1d-46ef-8b55-51683ba67a49)] -> id: BabyNameTextField]
Session ID: 742d41a5-5d1d-46ef-8b55-51683ba67a49

**Comment by StephanB75** [comment] 2022-07-15 06:08
looks like also other getAttributes are affecfted. Can see also a similar errors on "visible" or "label" and maybe more

**Comment by KazuCocoa** [comment] 2022-07-15 06:09
Duplicate of https://github.com/appium/appium/issues/17203.
Please use 4.7.2 for now.

**Closed by KazuCocoa** 2022-07-15 06:09 UTC
