### ISSUE TITLE
Unable to install using npm command on MAC OS 10.10.2 (14C1514)

### ISSUE THREAD

**Issue by lamp12** [appium/appium#4751] opened 2015-03-23 16:01 UTC
npm install -g appium
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.1
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/<username>/npm-debug.log

**Comment by imurchie** [comment] 2015-03-25 19:21
Are you behind a proxy or do you have bad network settings?

**Comment by lamp12** [comment] 2015-03-26 12:45
Hi Isaac,

There is no proxy set on my mac mini.Please refer the attached snapshot.
Please bear with me as i am new to appium and Mac.

![screen shot 2015-03-26 at 6 12 30 pm](https://cloud.githubusercontent.com/assets/10503356/6846378/cde0db78-d3e3-11e4-9a34-0c05e1deac45.png)

**Comment by imurchie** [comment] 2015-03-26 16:15
Can you install _anything_ from npm? If you go into a temporary directory and run

```shell
npm install nice-date
```

Does it successfully work (`nice-date` is a small module with no dependencies, so it should be fast and not do too much)?

**Comment by cdewangan** [comment] 2015-03-26 16:54
I am also facing same issue for installing appium in mac:

npm ERR! Command failed: git clone --template=/Users/<user>/.npm/_git-remotes/_templates --mirror git://github.com/vojtajina/traceur-compiler /Users/<user>/.npm/_git-remotes/git-github-com-vojtajina-traceur-compiler-f4c43c65
npm ERR! Cloning into bare repository '/Users/<user>/.npm/_git-remotes/git-github-com-vojtajina-traceur-compiler-f4c43c65'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 198.241.217.15]: errno=Connection refused

**Comment by jlipps** [comment] 2015-03-26 17:08
dupe of #4508

**Closed by jlipps** 2015-03-26 17:08 UTC
Labels: NeedsTriage

**Comment by lamp12** [comment] 2015-03-29 14:49
Hi,

I tried npm install nice-date  and it worked successfully
