### ISSUE TITLE
XCUITest Basic TouchActions are broken and Cached

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#7960] opened 2017-03-01 11:51 UTC
@imurchie @mykola-mokhnach 

myself and @SrinivasanTarget were testing the TouchActions api on the java-client latest, with appium 1.6.4beta. Basic TouchActions like tap, press with co-ordinates are failure. 

Server logs https://gist.github.com/saikrishna321/ebb597bd44ded97621c2f272d0195b1f

Java-Client command:

new TouchActions(driver).tap(a.getHeight() / 2 - 100, a.getWidth() / 2 - 50).perform().release();

When the above command is executed in loop we see the below logs 

https://gist.github.com/saikrishna321/ebb597bd44ded97621c2f272d0195b1f#file-touchactions-ios10-L862-L920

**Comment by amedvedjev** [comment] 2017-03-01 13:01
TouchActions ? Why not TouchAction from Appium java-client?

**Comment by saikrishna321** [comment] 2017-03-01 16:14
@amedvedjev sorry its TouchAction

**Comment by imurchie** [comment] 2017-03-01 16:15
That sounds like an issue with the client or the test code. The Appium server is getting impossible chained actions:

```
[HTTP] --> POST /wd/hub/session/90764eff-33f4-44d2-ba0a-279764d81cc6/touch/perform {"actions":[{"action":"tap","options":{"x":46,"y":110}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"x":46,"y":110}}],"90764eff-33f4-44d2-ba0a-279764d81cc6"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: tap
[debug] [JSONWP Proxy] Proxying [POST /wda/tap/0] to [POST http://localhost:8100/session/A54DA7B3-16DB-4910-9E91-61A804FDDB8D/wda/tap/0] with body: {"x":46,"y":110}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"A54DA7B3-16DB-4910-9E91-61A804FDDB8D","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: {}
[HTTP] <-- POST /wd/hub/session/90764eff-33f4-44d2-ba0a-279764d81cc6/touch/perform 200 539 ms - 74
[HTTP] --> POST /wd/hub/session/90764eff-33f4-44d2-ba0a-279764d81cc6/touch/perform {"actions":[{"action":"tap","options":{"x":46,"y":110}},{"action":"release","options":{}},{"action":"tap","options":{"x":146,"y":110}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"x":46,"y":110}},{"action":"release","options":{}},{"action":"tap","options":{"x":146,"y":110}}],"90764eff-33f4-44d2-ba0a-279764d81cc6"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: tap-release-tap
[HTTP] <-- POST /wd/hub/session/90764eff-33f4-44d2-ba0a-279764d81cc6/touch/perform 501 14 ms - 164
```

The first one is just a `tap`, which at least from this vantage point works fine.

The second (and subsequent) one is things that are not supported.

**Comment by saikrishna321** [comment] 2017-03-01 16:18
@imurchie even the first tap didn't work, but click() on the same element works

**Comment by imurchie** [comment] 2017-03-01 16:22
We need more information, then. That provided here indicates everything went well.

**Comment by imurchie** [comment] 2017-03-01 16:47
Well, to start, what "didn't work" means. A way to reproduce would be nice, too.

**Comment by SrinivasanTarget** [comment] 2017-03-01 16:54
Sure @imurchie We will get a sample test soon in our sample app.

**Comment by mykola-mokhnach** [comment] 2017-03-01 20:16
@saikrishna321 

```java
new TouchActions(driver).tap(a.getHeight() / 2 - 100, a.getWidth() / 2 - 50).perform().release();

```

This commands performs tap by absolute screen coordinates. Is this what you expect?

Also, I suppose, _release_ is not necessary here. One has to use _release_ together with _press_
@imurchie correct me if I'm wrong.

**Comment by huminzhi** [comment] 2017-03-01 22:42
FYI, I hit same issue...

**Comment by saikrishna321** [comment] 2017-03-02 06:30
@mykola-mokhnach 
> This commands performs tap by absolute screen coordinates. 

Yes, we are trying to tap on certain screen co-ordinates. Even the tap with Element also does not work. 

new TouchAction(driver).tap(element).perform().release();

**Comment by mykola-mokhnach** [comment] 2017-03-02 07:24
_release()_ call is not needed here. _perform()_ call should be the last one, since it applies the whole actions chain.

Do you try to tap in landscape or in portrait? Which iOS version?

**Comment by wenshi11019** [comment] 2017-03-02 16:04
I think the question in the xcuiteset driver

**Comment by imurchie** [comment] 2017-03-02 16:10
@wenshi11019 Why do you say that?

@saikrishna321 `new TouchAction(driver).tap(element).perform().release();` is not a valid command. `.perform()` should be the _last_ call. And `tap` does not take `release` (though I am adding it so `new TouchAction(driver).tap(element).release().perform();` will work.

**Comment by wenshi11019** [comment] 2017-03-02 16:18
@imurchie because i use version 2.5.3, can run success

**Comment by imurchie** [comment] 2017-03-02 16:33
Ok. Can you provide a way to reproduce? I just looped through tapping 100 times and get no issue.

**Comment by wenshi11019** [comment] 2017-03-03 01:17
`org.openqa.selenium.WebDriverException: Support for this gesture is not yet implemented. Please contact an Appium dev (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 77 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'DC.local', ip: '192.168.88.10', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.3', java.version: '1.8.0_112'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=20170208.ipa, networkConnectionEnabled=false, noReset=true, xcodeOrgId=*****, bundleId=com.adb.device, databaseEnabled=false, deviceName=iPhone 6, launchTimeout=60000, xcodeSigningId=iPhone Developer, platform=MAC, newCommandTimeout=60, platformVersion=10.2, webStorageEnabled=false, locationContextEnabled=false, automationName=XCuiTest, useNewWDA=true, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=cb004867d5b72d}]
Session ID: f570174c-29c5-44a9-8ec2-7c95d47967da
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_112]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_112]
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216) ~[selenium-remote-driver-3.0.1.jar:?]
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168) ~[selenium-remote-driver-3.0.1.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635) ~[selenium-remote-driver-3.0.1.jar:?]
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42) ~[java-client-5.0.0-BETA3.jar:?]
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1) ~[java-client-5.0.0-BETA3.jar:?]
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1) ~[java-client-5.0.0-BETA3.jar:?]
	at io.appium.java_client.PerformsTouchActions.performTouchAction(PerformsTouchActions.java:39) ~[java-client-5.0.0-BETA3.jar:?]
	at io.appium.java_client.TouchAction.perform(TouchAction.java:322) ~[java-client-5.0.0-BETA3.jar:?]
	at framework.appium.locator.AppLocator.tap(AppLocator.java:401) [classes/:?]
	at framework.appium.locator.AppLocator.longTap(AppLocator.java:427) [classes/:?]
	at framework.appium.keyword.ios.KeyWordIOSTest.testsearch(KeyWordIOSTest.java:67) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:756) [testng-6.10.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:610) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:289) [testng-6.10.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.10.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.10.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293) [testng-6.10.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218) [testng-6.10.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1133) [testng-6.10.jar:?]
	at org.testng.TestNG.run(TestNG.java:1104) [testng-6.10.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127) [testng-plugin.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:?]`

**Comment by jlipps** [comment] 2017-04-07 18:57
closing since no repro instructions were given

**Closed by jlipps** 2017-04-07 18:57 UTC
Labels: NeedsTriage
