### ISSUE TITLE
Cannot get 'xml' source of the current application in Appium Inspector

### ISSUE THREAD

**Issue by vishnuprakash9845** [appium/appium#13548] opened 2019-11-06 07:17 UTC
## The problem

When I have tried to inspect a particular page on UI elements of an IOS app in iPhone Real Device, appium inspector throws the error as follows.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Desktop OS/version used to run Appium: macOS Catalina V10.15
* Node.js version (unless using Appium.app|exe): 12.5.0
* Mobile platform/version under test:  13.2
* Real device or emulator/simulator: Real Device

Attaching the screenshot
![AppiumError](https://user-images.githubusercontent.com/24207575/68276630-6d2bc900-0093-11ea-8188-66f6b65013ac.jpg)

Is there any other tool to inspect the IOS elements for mobile automation. Can anyone help me on this issue.

**Comment by mykola-mokhnach** [comment] 2019-11-06 10:01
Duplicate of https://github.com/appium/appium/issues?q=is%3Aissue+%22source+of+the+current+application%22+is%3Aclosed

**Closed by mykola-mokhnach** 2019-11-06 10:01 UTC
