### ISSUE TITLE
Some elements that are present on a screen (being in focus) are not seen by isDisplayed()

### ISSUE THREAD

**Issue by JackLondon1** [appium/appium#4131] opened 2014-11-21 19:48 UTC
Hi,

I'm running into an issue when running my test on real device iOs (8.1.1) against appium server 1.3.1/1.3.3, certain elements that are present on a screen (being in focus) are not seen by isDisplayed().

Details:
- All elements under test have accessibility labels and the following attributes:
enabled: true
visible: false
valid: true

    Elements that are not visible to isDisplayed() during test run-time, are visible in Appium Inspector but not visible when switching Show Invisible OFF) and are found by appium server during runtime (see log below).

Questions:
- How exactly does isDisplayed() work in such situation?
- What differentiates visibility of elements to isDisplayed() when both: visible and not visible have similar element attributes values? For ex., elements that are visible to isDisplayed() during test runtime have the following attributes:
enabled: true
visible: false
valid: true

Elements that are not visible to isDisplayed() during runtime have the following attributes:
enabled: true
visible: false
valid: true

Appium server log:
//I'm looking for presence of a button called "Choose"

info: [debug] Pushing command to appium work queue: "au.getElementByName('Choose')"
info: [debug] Sending command to instruments: au.getElementByName('Choose')
info: [debug] [INST] 2014-11-20 22:25:38 +0000 Debug: evaluation finished
info: [debug] [INST] 2014-11-20 22:25:38 +0000 Debug: responding with:
info: [debug] [INST] 2014-11-20 22:25:38 +0000 Debug: Running system command #144: /Users/bzayats/local/bin/node /Users/Bzayats/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] [INST] 2014-11-20 22:25:39 +0000 Debug: Got new command 144 from instruments: au.getElementByName('Choose')
info: [debug] [INST] 2014-11-20 22:25:39 +0000 Debug: evaluating au.getElementByName('Choose')
info: [debug] [INST] 2014-11-20 22:25:39 +0000 Debug: evaluation finished
info: [debug] [INST] 2014-11-20 22:25:39 +0000 Debug: Lookup returned [object UIAButton] with the name "Choose" (id: 421).
info: [debug] Socket data received (40 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"421"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"421"},"sessionId":"e26cbb9a-e1e2-4c9f-9741-3e04a5f8c88a"}
info: <-- POST /wd/hub/session/e26cbb9a-e1e2-4c9f-9741-3e04a5f8c88a/element 200 1252.859 ms - 89 {"status":0,"value":{"ELEMENT":"421"},"sessionId":"e26cbb9a-e1e2-4c9f-9741-3e04a5f8c88a"}
info: --> GET /wd/hub/session/e26cbb9a-e1e2-4c9f-9741-3e04a5f8c88a/element/421/displayed {}
info: [debug] Pushing command to appium work queue: "au.getElement('421').isDisplayed()"
info: [debug] Sending command to instruments: au.getElement('421').isDisplayed()
info: [debug] [INST] 2014-11-20 22:25:39 +0000 Debug: responding with:
info: [debug] [INST] 2014-11-20 22:25:39 +0000 Debug: Running system command #145: /Users/bzayats/local/bin/node /Users/Bzayats/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"421"}}...
info: [debug] [INST] 2014-11-20 22:25:40 +0000 Debug: Got new command 145 from instruments: au.getElement('421').isDisplayed()
info: [debug] [INST] 2014-11-20 22:25:40 +0000 Debug: evaluating au.getElement('421').isDisplayed()
info: [debug] Socket data received (28 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":false}
info: [debug] Responding to client with success: {"status":0,"value":false,"sessionId":"e26cbb9a-e1e2-4c9f-9741-3e04a5f8c88a"}
info: <-- GET /wd/hub/session/e26cbb9a-e1e2-4c9f-9741-3e04a5f8c88a/element/421/displayed 200 1089.151 ms - 77 {"status":0,"value":false,"sessionId":"e26cbb9a-e1e2-4c9f-9741-3e04a5f8c88a"}

**Comment by mushtaque87** [comment] 2015-03-06 13:00
I found a work around . If you click on the TextField (tap) and then send Keys it works in Inspector .. So i programatically click on the textFiled and send Key in my java code , and due to strange reason i can sendKeys to that ***** . 

driver.findElement(By.xpath("//UIAApplication[1]/UIAWindow[2]/UIAKeyboard[1]/UIAButton[4]")).click();

///UIAButton[4] is the Next Button on the keyboard and it will tap on my textField. 

MobileElement password = (MobileElement) driver.findElement(By.xpath("//UIAApplication[1]/UIAWindow[1]/UIATableView[1]/UIATableCell[4]/UIASecureTextField[1]"));
password.sendKeys("xyz");

**Comment by jlipps** [comment] 2015-03-06 16:25
Maybe in appium-uiauto we could try to type and if it doesn't work, try to tap then type

**Comment by ctews** [comment] 2015-03-11 13:15
Just wondering if there's any update. I've got exact the same problem here. Using the Inspector the "visible" flag basically is just lying all the time. It always says ```visible: false``` even if the Inspector see the UIElements. 

For me I've got a UIAStaticText that is rendered properly (I can see it, Reveal can see it) but Appium just don't see it. 

Using Appium GUI Client - Version 1.3.6 (Ophiuchus) (also cli doesn't see it)
with Python bindings in the newest version.

**Comment by mushtaque87** [comment] 2015-03-11 16:05
Salam Brother ,

In my case there were 5 textfield , so i can automate the UI for first 3
and 4th one had the same issue of visible:false and when i used to manually
click on that then it was working ... So what i did was ... After typing
the 3rd Textfield i used this code

driver.findElement(By.xpath(
"//UIAApplication[1]/UIAWindow[2]/UIAKeyboard[1]/UIAButton[4]")).click();

It is the Keyboard next button , so it worked as as typing the textfield
with the hand .. So the cursor came there and the code executed rather then
failing ...


PS: Just check in the inspector what is the Keyboard xPath for you .. It
may vary ..




On Wed, Mar 11, 2015 at 6:46 PM, Christoffer Tews <notifications@github.com>
wrote:

> Just wondering if there's any update. I've got exact the same problem
> here. Using the Inspector the "visible" flag basically is just lying all
> the time. It always says visible: false even if the Inspector see the
> UIElements.
>
> For me I've got a UIAStaticText that is rendered properly (I can see it,
> Reveal can see it) but Appium just don't see it.
>
> Using Appium GUI Client - Version 1.3.6 (Ophiuchus) (also cli doesn't see
> it)
> with Python bindings in the newest version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appium/appium/issues/4131#issuecomment-78260269>.
>



-- 
Regards,
Mushtaque Ahmed
+91-9886820824.

**Comment by martinstolz** [comment] 2015-03-11 18:43
Have you also checked that the item you want to find is not displayed because it is outside of one of its parent's frame and `clipsToBounds` is set to `NO`? Or is that issue only on devices?

**Comment by ctews** [comment] 2015-03-13 08:25
That issue is in Simulator and on devices. It's perfectly in the frame of its parent and as stated every other tool apart from Appium can see the element correctly. RevealApp, XCode Beta Hierarchy View. Every other tool get the right visibility state but Appium doesn't which is really frustrating. 

The element gets set to ```hidden = YES``` and ```hidden = NO``` in between, but it es definitely visible when I run the test: for the human eye, by code, by RevealApp, by XCode. So there seems to be either a bug in Appium or UIAutomation.

**Comment by Jonahss** [comment] 2015-05-11 23:35
How best should we reproduce this? Build an app with textfields set with the same attributes described in this post? Then we can play around with different methods for discovering the visibility.

**Comment by bootstraponline** [comment] 2015-05-11 23:39
I'd start with the existing UICatalog app before building a new app.

**Comment by aluedeke** [comment] 2015-05-22 10:01
i just reproduced the issue. The element.isVisible() call to ui auto is returning 0 for the element.

I changed the code to make all elements visible by always assigning visible: true . Then i was able to focus and sendKeys. to my "invisible" TextField

@Jonahss @bootstraponline if you need more details feel free to ping me

**Comment by sebv** [comment] 2015-06-03 17:34
Ok possible bug here.

**Comment by clubnica** [comment] 2015-06-05 20:36
We have the same issue..using iOS 8.1-8.3 , device 6.1, appium 1.3.7 , instruments 6.3
Elements always return values below no matter what:
enabled: true
visible: false

Have you guys tried 1.4.0 version of appium or  using older version of xcode instruments?  there is also 1.4.1 source code of appium is available...

any progress on fixing this bug?

**Comment by clubnica** [comment] 2015-06-15 18:44
We have tried 1.4.0 and 1.4.1 appium versions for iOS.. it did not help... 
Of course it works if you directly click, send keys to element without checking is it displayed or not.. but from automation point you need to know when element is available/visible or you would need to have bunch of sleeps  before doing anything with the element  and that is not efficient...I find this bug pretty critical to support test automation of iOS 8 version

**Comment by narulacool** [comment] 2015-07-08 04:50
Even I face the issue.

Some text boxes are visible on IOS7.0/Appium1.2.0 but the same are invisible on IOS7.1/Appium1.2.0 & IOS 8.0/Appium1.2.0.

Surprisingly if I use Appium0.18 all of these elements are visible wether it be IOS7.0 or 7.1 or 8.0.

Kindly fix this as this results in tests getting failed unexpectedly when run on different IOS.

**Comment by Jonahss** [comment] 2015-07-08 20:14
That's interesting that it works fine on Appium v0.18  that could help us find the source of the issue perhaps.

Would you be able to update to the latest version (appium 1.4.7) and the latest version of Xcode (6.4)?

**Comment by narulacool** [comment] 2015-07-09 13:30
I ran on Xcode v6.3.2 with Appium v1.4 & to my surprise I was able to see these elements as visible on IOS 8.3 but they remained invisible for IOS 7.1/8.0

**Comment by Jonahss** [comment] 2015-07-09 21:53
Ooh hmmmm. Maybe this way a bug in Instruments then, and Apple has now fixed it :)

**Comment by narulacool** [comment] 2015-07-10 04:25
But then it should have also worked for IOS 7.1/8.0..!!

**Comment by aluedeke** [comment] 2015-07-10 07:35
@Tarun Actually not. There are known bugs (e.g. different ui hierarchys for
the same app on different ios versions (7 vs 8). So the buggy piece is on
the phone and not on the pc.

**Closed** 2015-07-13 21:48 UTC
Labels: Bug, iOS

**Comment by dustinlewis** [comment] 2015-09-12 01:09
I am seeing this on Xcode 6.4, appium 1.4.8 . Every element has visible: false.

**Comment by gmpeterson** [comment] 2015-09-21 18:37
A workaround for this is to pass a script to the element.. [[[[I.E > find_element(:class, 'class_name' ).execute_script("$('.class_name').click()")]]]]   --This actually allows you to get w/in whatever page that element is linked. Once here, you can continue your tests

**Comment by tk-421** [comment] 2015-09-29 20:29
Can this issue be re-opened. I'm having the same issue with: 
Xcode 7
Appium 1.4.11
iOS 9 (emulator)

All elements are reporting visible: false. I'm able to interact with most element, but cannot click specifically on CollectionCells.

logs: https://gist.github.com/tk-421/a63e6e4f00692ad342c9

**Comment by peushan** [comment] 2015-10-13 10:53
is there any work around for this issue? I continuously observing this issue in standard search in IOS. Initially it will identified the (search bar) element and can enter the desired text.

![display](https://cloud.githubusercontent.com/assets/6837109/10452931/01485682-71c6-11e5-996e-919b2d08fe21.jpg)

But after the search, none of the elements (red color pointed) will identified/visible except the search results elements. (Blue color pointed) I think the focus only point into search results.
Please see the attached screenshots.

![not display](https://cloud.githubusercontent.com/assets/6837109/10452915/e06b5536-71c5-11e5-8a1d-5a23e48b86c2.jpg)

I navigate away from the screen and came back to the same screen to see whether those elements are visible or not. But unfortunately it ain’t.  I want to clear the entered text and check.
Appium version 1.4.13
Xcode 7
iPhone 6 (IOS 9)

**Comment by AddisonGao** [comment] 2015-12-16 10:21
I guess it is a bug of UIAutomation.



Appium version 1.4.13
Xcode 7
iOS 8.1.1

**Comment by AddisonGao** [comment] 2015-12-16 10:25
@Jonahss I am seeing this on Xcode 7.1, appium 1.4.13 . Every element has visible: false.

**Comment by artgo** [comment] 2015-12-19 02:55
Same issue on XCode 7.2, appium 1.4.13

**Comment by artgo** [comment] 2015-12-19 03:03
Opened https://github.com/appium/appium/issues/5941 to track the issue with latest version

**Comment by jmolliver** [comment] 2016-04-21 20:57
Any update on this issue? Also, what attribute is the Appium Inspector using for the checkbox Show Invisible? I would love to key off that, since visible=false for everything, as of now.

**Comment by KateOgar** [comment] 2016-05-07 18:16
Facing the same problem with appium 1.5.2(

**Comment by KateOgar** [comment] 2016-05-10 10:10
may be you may know how to check that element is displayed on the screen now?

**Comment by kskrishnan** [comment] 2016-05-19 15:35
Still facing the same issue, even built appium.app from the latest source - doesn't seem to fix the problem though. Elements are shown with with visible=false, even though they are visible, displayed to the naked eye.

**Comment by s-sridevi15** [comment] 2016-06-03 19:37
I am facing same issue with appium 1.5.1 . All elements are showing visible = false and could not able to have assert whether element is displayed or not. Can somebody please respond whether it is bug in appium or not?

**Comment by dduphorn** [comment] 2016-06-06 21:54
I'm also facing this same issue.  Appium 1.5.2.

**Comment by jmolliver** [comment] 2016-06-07 01:07
I'm finding that it is only a bug with the Inspector, but if you write your tests and run them to verify visible, the test itself will pass/fail on the correct value. So for now, we have to ignore the Inspector for this value, but do continue to write tests for it.

**Comment by dduphorn** [comment] 2016-06-07 11:41
I step through my test case again and found that the issue was on my end.  :)

**Comment by prichopra** [comment] 2016-07-07 09:17
I am also facing same issue with appium 1.4.13 and 1.5.3. I am not able to find elements in Native iOS app using xpath/ID/name. I am getting error "An element could not be found using the given search parameters". Can someone help me with this?

**Comment by s-sridevi15** [comment] 2016-07-07 12:42
Yeah it seeems like issue only with inspector. Tests working fine.

**Comment by prichopra** [comment] 2016-07-07 15:18
Sorry for me...test is also not working fine.

Could you please share the desired capabilties or settings for iOS?

**Comment by prichopra** [comment] 2016-07-14 06:07
Hi All,

I have found solution for this

Try using java client 2.2.0 /2.1.0 and use this to click on an element.

driver.tap(1, driver.findElement(MobileBy.name("email")),200);

You can use xpath as well.

Thanks!!

**Comment by Hellengo** [comment] 2016-08-24 12:01
xcode 7.3.2
Mac OS X EI Capitan 10.11.5

I'm also facing this same issue. Appium 1.5.3.

run test use wd.find_element_by_name("Already have an account?").click()
error:
selenium.common.exceptions.InvalidSelectorException: Message: Locator Strategy 'name' is not supported for this session

run test use wd.find_element_by_xpath("//UIAApplication[1]/UIAWindow[1]/UIAStaticText[1]")
error:
selenium.common.exceptions.WebDriverException: Message: target.frontMostApp().elements()[0].elements()[16].elements()[0].elements()[0] could not be tapped because the element is not visible

**Comment by igalep** [comment] 2016-09-05 13:45
@Hellengo you have a next error : "InvalidSelectorException: Message: Locator Strategy 'name' is not supported for this session"

You need to use a different locator in order to find your elements (driver.findElementsById ...)

**Comment by LukasLewandowski** [comment] 2016-12-07 16:50
Still facing that problem in appium 1.5.3 and xcode 7.3.1.

**Comment by rameshshriram** [comment] 2016-12-19 13:59
Any solution for this issue?

**Comment by jmolliver** [comment] 2016-12-19 15:06
Locating element by name was intentionally removed from appium 1.5.3. That locator has been retired in this release. If you still need to locate by name, you will have to xpath to the name attribute:  elementByXpath, or use elementById or elementByAccessiblityId

**Comment by LukasLewandowski** [comment] 2017-01-03 09:22
What about that issue?

"Appium inspector showing elements as invisible which are actually visible"

Any solution for this? Clicking/tapping into "invisible" element is not working :(

(MobileBy.XPATH, '//UIAStaticText[2][@visible="false"]')

**Comment by grpratap69** [comment] 2018-07-19 11:35
facing this issue with Appium 1.6.2.....elements sometimes have attribute as true n sometimes false regardless of whether element is displayed or not.....any solution?

**Comment by Aswini-kumarPradhan** [comment] 2018-07-31 10:14
I am facing this issue with appium 1.8.1, Long pending issue i guess. Is this going to be fixed any how? any work around?
