### ISSUE TITLE
appium is crashing on startup. again

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#5018] opened 2015-04-29 01:41 UTC
The logs are [in this gist](https://gist.github.com/bootstraponline/bfaee92a8796d54123c2). I'm running the latest appium master rev and I double checked that the submodules are up to date. 

`error: Could not determine Xcode version:Could not get Xcode version. /Applications/Xcode.app/Contents/Info.plist/ does not exist on disk.`

I'm using Xcode 6.3.1 on OS X 10.10.3. I can't make a new release of the Ruby bindings because the server crashes on startup which makes executing the iOS test suite difficult.

**Comment by imurchie** [comment] 2015-04-29 18:41
Does [this](https://github.com/appium/appium-xcode/commit/376ccc029589921cb25ec24874bc5cc0530702c4) fix the problem?

**Comment by bootstraponline** [comment] 2015-04-29 21:55
no? I cloned from master and master is broken. Is `appium-xcode` suppose to be a submodule?

**Comment by imurchie** [comment] 2015-04-29 22:43
No, just an npm module.

**Comment by bootstraponline** [comment] 2015-04-29 22:46
I see `"appium-xcode": "=2.0.2"` in `package.json` on my local disk. It looks like this is what I'm already using.

**Comment by bootstraponline** [comment] 2015-04-29 22:47
`node_modules/appium-xcode/lib/xcode.js ` also shows that it contains the fix you linked to.

**Comment by imurchie** [comment] 2015-04-29 23:21
Ok. I'll leave this in the queue. I can't make it happen with the same configuration, though.

**Comment by bootstraponline** [comment] 2015-04-29 23:26
My repro steps:

1. clone appium
2. run reset
3. run ios test
4. observe crash

**Comment by imurchie** [comment] 2015-04-30 15:38
I can reproduce steps 1-3.

**Comment by jlipps** [comment] 2015-05-01 17:08
@bootstraponline you are running bare `./reset.sh`?

**Comment by jlipps** [comment] 2015-05-01 17:15
@bootstraponline i did the following:

```
$ git clone https://github.com/appium/appium
$ cd appium
$ ./reset.sh
$ node .
```

then ran an iOS test. no crash. the only difference I guess is I'm on xcode 6.3 (6D570) not 6.3.1. i'll try to download that one...

**Comment by bootstraponline** [comment] 2015-05-01 21:02
Thanks to a tip from @Jonahss I figured out how to debug the problem.

```
WARN xcodePath: /Applications/Xcode.app/Contents/Developer/ 
WARN xcode subdir: /Contents/Developer 
WARN plistPath: /Applications/Xcode.app/Contents/Info.plist/ 
WARN xcodePath: /Applications/Xcode.app/Contents/Developer/ 
WARN xcode subdir: /Contents/Developer 
WARN plistPath: /Applications/Xcode.app/Contents/Info.plist/ 
WARN xcodePath: /Applications/Xcode.app/Contents/Developer/ 
WARN xcode subdir: /Contents/Developer 
WARN plistPath: /Applications/Xcode.app/Contents/Info.plist/ 
```

```javascript
async function getVersionWithoutRetry () {

  let xcodePath = await getPath();

  // we want to read the CFBundleShortVersionString from Xcode's plist.
  // It should be in /[root]/XCode.app/Contents/
  const plistPath = xcodePath.replace(XCODE_SUBDIR, "/Contents/Info.plist");

  log.warn("xcodePath: " + xcodePath);
  log.warn("xcode subdir: " + XCODE_SUBDIR);
  log.warn("plistPath: " + plistPath);
```

The issue repros for me in the chrome dev tools.

```
var xcodePath = '/Applications/Xcode.app/Contents/Developer/';
var plistPath = xcodePath.replace("/Contents/Developer",  "/Contents/Info.plist");
"/Applications/Xcode.app/Contents/Info.plist/" // fail
```

**Comment by bootstraponline** [comment] 2015-05-01 21:09
Manually adding a trim command got me a bit further along.

```
 plistPath = plistPath.replace(new RegExp("/$"), "").trim();
```

however I'm not sure why jonahss username is in the stacktrace.

```
info: [debug] Error: Could not get Xcode version. /Applications/Xcode.app/Contents/Info.plist/ does not exist on disk.
    at /Users/jonahss/Workspace/appium-xcode/lib/xcode.js:100:11
```

**Comment by bootstraponline** [comment] 2015-05-01 21:15
The gist for the new failure is [here](https://gist.github.com/bootstraponline/70e7419f6acec7dfb065). I'm pretty sure this is a bug in appium.

**Comment by Jonahss** [comment] 2015-05-01 21:21
jlipps already committed that `trim()` fix for the symlink path.

On Fri, May 1, 2015 at 2:15 PM, bootstraponline <notifications@github.com>
wrote:

> The gist for the new failure is here
> <https://gist.github.com/bootstraponline/70e7419f6acec7dfb065>. I'm
> pretty sure this is a bug in appium.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appium/appium/issues/5018#issuecomment-98240499>.
>
   ​

**Comment by Jonahss** [comment] 2015-05-01 21:23
https://github.com/appium/appium-xcode/commit/a851f8e6fc6d6634d8c2fcca98cc054bba5b36f9

**Comment by bootstraponline** [comment] 2015-05-01 21:25
right. it's still broken. i'm using the latest appium-xcode.

**Comment by Jonahss** [comment] 2015-05-01 21:29
like, it adds the trailing slash anyways? Or is it some other issue.

**Comment by bootstraponline** [comment] 2015-05-01 21:32
> like, it adds the trailing slash anyways?

yes and when I add the code to remove the slash I get further along however there's some other piece outside of appium-xcode which still has the bug. also I'm not sure why `/Users/jonahss/Workspace` would show up in my stack trace

**Comment by jlipps** [comment] 2015-05-01 21:34
@bootstraponline that last issue might have to do with source maps and transpiling

**Comment by Jonahss** [comment] 2015-05-01 21:36
From the gist above, it looks like the same error.
ahhhhh, I think I get it.
you changed appium so it uses a modified appium-xcode, but appium-instruments also has appium-xcode as a dependency. I think npm-link should get that to work right, while modifying node_modules/appium-xcode wouldn't (you'd have to modify node_modules/appium-instruments/node_modules/appium-xcode)

**Comment by bootstraponline** [comment] 2015-05-01 21:37
oh. that makes sense. I will try again with the proper link approach.

**Comment by Jonahss** [comment] 2015-05-01 21:38
We're still learning about what work-flows are like with managing multiple modules.

**Comment by jlipps** [comment] 2015-05-01 21:50
retry from a clean master @bootstraponline. is it working now?

**Comment by bootstraponline** [comment] 2015-05-01 22:22
I tried from a clean master and it's still broken. here are [the gist logs](https://gist.github.com/bootstraponline/37bbf7b1c46b7fd74edc). I used rev b08b2523aa4cf7f01ba93943d6dc67da5f53d303

**Comment by bootstraponline** [comment] 2015-05-01 22:29
I'll submit a PR which fixes the issue in a minute.

**Closed** 2015-05-02 18:16 UTC
Labels: Bug, iOS
