### ISSUE TITLE
Not able to run Appium on real devices with iOS 9.3.4

### ISSUE THREAD

**Issue by harisudhag** [appium/appium#6760] opened 2016-08-22 23:54 UTC
## The problem

While trying to run the automation in the real devices (iPad Air with iOS 9.3.4), the instruments crashed with the below error,
[debug] [Instruments] [INST STDERR] Instruments Usage Error: Specified target process is invalid: 
<application-name hidden>
instruments, version 7.3 (60134)

The same app and the automation code runs fine with iPad Air with iOS 9.3.2

## Environment

* Appium version (or git revision) that exhibits the issue:1.5.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OSX 10.11.6
* Node.js version (unless using Appium.app|exe): v6.3.0
* Mobile platform/version under test: iOS 9.3.4
* Real device or emulator/simulator: Real device : iPad Air
* Appium CLI or Appium.app|exe: appium cli 1.5.3

**Comment by harisudhag** [comment] 2016-08-22 23:54
[appium.txt](https://github.com/appium/appium/files/431396/appium.txt)

**Comment by mykola-mokhnach** [comment] 2016-08-23 12:44
Duplicate of https://github.com/appium/appium/issues/6730

**Comment by SrinivasanTarget** [comment] 2016-08-23 12:45
@triager please close

**Closed by SrinivasanTarget** 2016-08-23 12:45 UTC
Labels: NeedsTriage
