### ISSUE TITLE
Appium breaks when take screenshot

### ISSUE THREAD

**Issue by Amrkamel1** [appium/appium#13951] opened 2020-02-17 20:58 UTC
## The problem

Im running test again mobile hybrid app, Using testng maven and allure as reporter.
i have noticed on test failure when im trying to make appium take screenshot to be attached with allure report that it breaks appium session and test will stuck on failed test, even after timeout appium wont execute the other test suite as it should 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable): i was always working normally with previous versions
* Desktop OS/version used to run Appium: windows 10
* Node.js version : v12.14.1
* Npm or Yarn package manager: 6.13.6
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

   ```
 onTestFailure method Verify_Deleting_Functionality_For_Domain failed
onTestFailure method Verify_Deleting_Functionality_For_Domain failed
Finish test suite for Login Page Test Cases
org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: 10.000
  (Session info: chrome=74.0.3729.185)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.18362 x86_64)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-0VOQJHQN', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
Driver info: io.appium.java_client.AppiumDriver
Capabilities {app: C:\Users\warrior\Desktop\Mo..., appActivity: com.trackerproducts.mobile...., appPackage: com.trackerproducts.mobile, autoGrantPermissions: true, automationName: uiautomator2, avd: Pixel, clearSystemFiles: true, databaseEnabled: false, desired: {app: C:\Users\warrior\Desktop\Mo..., appActivity: com.ss.mobile....,dsd appPackage: com.tsdscts.mobile, autoGrantPermissions: true, automationName: uiautomator2, avd: Pixel, clearSystemFiles: true, deviceName: emulator-5554, platformName: android, platformVersion: 10, showGradleLog: true}, deviceApiLevel: 29, deviceManufacturer: Google, deviceModel: Android SDK built for x86, deviceName: emulator-5556, deviceScreenDensity: 400, deviceScreenSize: 1080x2160, deviceUDID: emulator-5556, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2.5, platform: LINUX, platformName: LINUX, platformVersion: 10, showGradleLog: true, statBarHeight: 60, takesScreenshot: true, viewportRect: {height: 1980, left: 0, top: 60, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: 846cc110-68a2-465a-a752-39a991b358c5
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
 at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
 at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
 at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
 at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
 at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
 at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
 at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
 at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:295)
 at Listener.TestListener.saveScreenshotPNG(TestListener.java:23)
 at Listener.TestListener.onTestFailure(TestListener.java:81)
 at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:66)
 at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:210)
 at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:814)
 at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
 at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
 at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
 at java.util.ArrayList.forEach(ArrayList.java:1257)
 at org.testng.TestRunner.privateRun(TestRunner.java:770)
 at org.testng.TestRunner.run(TestRunner.java:591)
 at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
 at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
 at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
 at org.testng.SuiteRunner.run(SuiteRunner.java:304)
 at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
 at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
 at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
 at org.testng.TestNG.runSuitesSequentially(TestNG.java:1175)
 at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
 at org.testng.TestNG.runSuites(TestNG.java:1032)
 at org.testng.TestNG.run(TestNG.java:1000)
 at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
 at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)

```
## Link to Appium logs
    
```
    debug] [W3C (846cc110)]     at ProtocolConverter.convertAndProxy (C:\Users\warrior\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\protocol-converter.js:245:12)
[debug] [W3C (846cc110)]     at JWProxy.proxyCommand (C:\Users\warrior\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:258:12)
[debug] [W3C (846cc110)]     at JWProxy.proxyReqRes (C:\Users\warrior\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:308:36)
[debug] [W3C (846cc110)]     at Chromedriver.proxyReq (C:\Users\warrior\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:655:12)
[debug] [MJSONWP] Matched JSONWP error code 21 to TimeoutError
[HTTP] <-- GET /wd/hub/session/846cc110-68a2-465a-a752-39a991b358c5/screenshot 408 60036 ms - 1072
[HTTP]
[HTTP] --> GET /wd/hub/session/846cc110-68a2-465a-a752-39a991b358c5/screenshot
[HTTP] {}
[W3C (846cc110)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/846cc110-68a2-465a-a752-39a991b358c5/screenshot' to command name 'getScreenshot'
[debug] [WD Proxy] Proxying [GET /wd/hub/session/846cc110-68a2-465a-a752-39a991b358c5/screenshot] to [GET http://127.0.0.1:8002/wd/hub/session/354e69bbdc244d647af9b95e81686133/screenshot] with body: {}
[
```

## Code To Reproduce Issue [ Good To Have ]
    
```
    package Listener;

import Configuartion.BaseSetup;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import io.qameta.allure.Attachment;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.ITestResult;

public class TestListener extends BaseSetup implements ITestListener {

        private static String getTestMethodName(ITestResult iTestResult) {
        return iTestResult.getMethod().getConstructorOrMethod().getName();
    }

    //Screenshot attachments for Allure
    @Attachment(value = "Page screenshot", type = "image/png")
    public byte[] saveScreenshotPNG(AppiumDriver<MobileElement> driver) {
        return ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
    }

    //Text attachments for Allure
    @Attachment(value = "{0}", type = "text/plain")
    public static String saveTextLog (String message) {
        return message;
    }

    //HTML attachments for Allure
    @Attachment(value = "{0}", type = "text/html")
    public static String attachHtml(String html) {
        return html;
    }

//    //Screenshot attachment with renaming property
//    @Attachment(value = "Page screenshot", type = "image/png")
//    private static File screenshot (AndroidDriver driver) throws IOException  {
//        SimpleDateFormat sdf = new SimpleDateFormat("dd_MM_yyyy_hh_mm_ss");
//        Date date = new Date();
//        String fileName = sdf.format(date);
//        File SrcFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
//        FileUtils.copyFile(SrcFile, new File(System.getProperty("user.dir")+"//allure-results//"+fileName+".png"));
//        System.out.println("Screenshot is captured");
//        return SrcFile;
//
//    }

    @Override
    public void onStart(ITestContext iTestContext) {
        System.out.println("Starting test suite for device " + iTestContext.getName());
        iTestContext.setAttribute("AndroidDriver", this.driver);
    }

    @Override
    public void onFinish(ITestContext iTestContext) {
        System.out.println("Finish test suite for " + iTestContext.getName());

    }

    @Override
    public void onTestStart(ITestResult iTestResult) {
        System.out.println("onTestStart method " +  getTestMethodName(iTestResult) + " start");

    }

    @Override
    public void onTestSuccess(ITestResult iTestResult) {
        System.out.println("onTestSuccess method " +  getTestMethodName(iTestResult) + " succeed");
    }

    @Override
    public void onTestFailure(ITestResult iTestResult) {

        System.out.println("onTestFailure method " +  getTestMethodName(iTestResult) + " failed");

        //Allure ScreenShotRobot and SaveTestLog
        if (driver!= null) {
            saveScreenshotPNG(driver);
            System.out.println("Screenshot captured for test case:" + getTestMethodName(iTestResult));
        }
        //Save a log on allure.
        saveTextLog(getTestMethodName(iTestResult) + " failed and screenshot taken!");


    }

```

```

**Comment by Amrkamel1** [comment] 2020-02-17 21:35
update same error when im executing the test using maven command line 

```
Please refer to C:\Users\warrior\Desktop\MobileAutomationTest\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
There was an error in the forked processtimeout: Timed out receiving message from renderer: 10.000
  (Session info: chrome=74.0.3729.185)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.18362 x86_64)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-0VOQJHQN', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
Driver info: io.appium.java_client.AppiumDriver
Capabilities {app: C:\Users\warrior\Desktop\Mo..., appActivity: com.trackerproducts.mobile...., appPackage: com.trackerproducts.mobile, autoGrantPermissions: true, automationName: uiautomator2, avd: Pixel, clearSystemFiles: true, databaseEnabled: false, desired: {a
pp: C:\Users\warrior\Desktop\Mo..., appActivity: com.trackerproducts.mobile...., appPackage: com.trackerproducts.mobile, autoGrantPermissions: true, automationName: uiautomator2, avd: Pixel, clearSystemFiles: true, deviceName: emulator-5554, platformName: android,
platformVersion: 10, showGradleLog: true}, deviceApiLevel: 29, deviceManufacturer: Google, deviceModel: Android SDK built for x86, deviceName: emulator-5556, deviceScreenDensity: 400, deviceScreenSize: 1080x2160, deviceUDID: emulator-5556, javascriptEnabled: true,
locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2.5, platform: LINUX, platformName: LINUX, platformVersion: 10, showGradleLog: true, statBarHeight: 60, takesScreenshot: true, viewportRect: {height: 1980, left: 0, top: 60, width: 1080}, wa
rnings: {}, webStorageEnabled: false}
Session ID: 1e5b550a-93db-4a6f-9763-077c564202b2
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked processtimeout: Timed out receiving message from renderer: 10.000
  (Session info: chrome=74.0.3729.185)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.18362 x86_64)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-0VOQJHQN', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
Driver info: io.appium.java_client.AppiumDriver
Capabilities {app: C:\Users\warrior\Desktop\Mo..., appActivity: com.trackerproducts.mobile...., appPackage: com.trackerproducts.mobile, autoGrantPermissions: true, automationName: uiautomator2, avd: Pixel, clearSystemFiles: true, databaseEnabled: false, desired: {a
pp: C:\Users\warrior\Desktop\Mo..., appActivity: com.trackerproducts.mobile...., appPackage: com.trackerproducts.mobile, autoGrantPermissions: true, automationName: uiautomator2, avd: Pixel, clearSystemFiles: true, deviceName: emulator-5554, platformName: android,
platformVersion: 10, showGradleLog: true}, deviceApiLevel: 29, deviceManufacturer: Google, deviceModel: Android SDK built for x86, deviceName: emulator-5556, deviceScreenDensity: 400, deviceScreenSize: 1080x2160, deviceUDID: emulator-5556, javascriptEnabled: true,
locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2.5, platform: LINUX, platformName: LINUX, platformVersion: 10, showGradleLog: true, statBarHeight: 60, takesScreenshot: true, viewportRect: {height: 1980, left: 0, top: 60, width: 1080}, wa
rnings: {}, webStorageEnabled: false}
Session ID: 1e5b550a-93db-4a6f-9763-077c564202b2
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:675)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:248)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1217)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1063)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:889)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**Comment by mykola-mokhnach** [comment] 2020-02-17 21:54
Duplicate of https://github.com/appium/appium/issues/13935

**Closed by mykola-mokhnach** 2020-02-17 21:54 UTC

**Comment by Amrkamel1** [comment] 2020-02-17 23:24
@mykola-mokhnach 
i have added 
        dc.setCapability("nativeWebScreenshot",true);
and still getting same error

**Comment by mykola-mokhnach** [comment] 2020-02-18 06:27
Any chance to get the updated server log?

**Comment by Amrkamel1** [comment] 2020-02-19 13:37
@mykola-mokhnach 
My bad i have added implicit wait for 2000 and units was in sec
