### ISSUE TITLE
Can not run Android tests with emulator in headless mode

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#6755] opened 2016-08-22 09:11 UTC
## The problem

Can not run Android tests with emulator in headless mode
## Environment
- Appium version: 1.5.3
- Desktop OS/version used to run Appium: MacOS 10.11.6
## Details

When i am starting tests with Android emulator in headless mode Appium failed ping the device.
After Appium doing "adb restart" emulator goes offline.

Problem emulator start:

```
   emulator -avd emulator_name -no-skin -no-window
```

or

```
   emulator -avd emulator_name -partition-size 1024 -scale 0.25 -camera-back webcam0 -no-boot-anim -no-window
```

Working emulator start: 

```
   emulator -avd emulator_name -partition-size 1024 -scale 0.25 -camera-back webcam0 -no-boot-anim
```
## Link to Appium logs

[ADB] Using adb from /Users/Aleksei/Library/Android/sdk/platform-tools/adb
[debug] [ADB] Setting device id to emulator-5554
[BaseDriver] Using local app '/Users/Aleksei/Downloads/test_clients/XXXX.apk'
[debug] [AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[debug] [ADB] Running /Users/Aleksei/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","wait-for-device"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/Aleksei/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","echo","ping"]
[debug] [ADB] Running /Users/Aleksei/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","echo","ping"]
[debug] [ADB] Restarting adb
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected

**Comment by saikrishna321** [comment] 2016-08-22 09:35
@amedvedjev adb does not find your device, thats the reason appium fails. Appium picks devices what adb returns. Make sure when you have your emulator up and running, adb devices shows your device

**Comment by mykola-mokhnach** [comment] 2016-08-22 10:00
Have you tried to reproduce the issue manually? I guess the problem might be your headless Mac OS configuration. The OS itself automatically disables GPU acceleration in case there are no external displays attached  and there is no way to restore it back. Android emulator itself requires OpenGL to work properly.
You could try either to connect a display to your Mac to avoid the problem or to use something like this thing: http://www.fit-pc.com/web/products/fit-headless/ to workaround the problem.

**Comment by amedvedjev** [comment] 2016-08-22 10:28
@saikrishna321 
if you see in logs we see that
```
[debug] [ADB] 1 device(s) connected
```
but later after "**Restarting adb**" we see that "**0 device(s) connected**"

i was looking at what happens between on machine sending "adb devices" while test in progress.
Before "Restarting adb" i have:
```
List of devices attached
emulator-5554	device
```

After:
```
List of devices attached
emulator-5554	offline
```

**Comment by Madan-Lal** [comment] 2016-08-24 06:08
@amedvedjev kill adb server
adb kill-server

**Comment by amedvedjev** [comment] 2016-08-24 06:50
@Madan-Lal this does not help. no matter either adb server started or not before opening driver.

**Comment by SibaMvelo** [comment] 2017-05-29 07:55
asd kill-server and adb start-server  did not work for me, is there another way to solve this :emulator-5554   offline

**Comment by dpgraham** [comment] 2017-07-19 20:03
Closing this as a non appium issue. It looks like it's a problem with adb.

**Closed by dpgraham** 2017-07-19 20:03 UTC
Labels: NeedsTriage

**Comment by ash3ax** [comment] 2018-01-13 19:10
Try adb connect localhost:5554
