### ISSUE TITLE
Failed to get sockets matching: @weblayer_devtools_remote_.*12531

### ISSUE THREAD

**Issue by linpy00** [appium/appium#17276] opened 2022-07-28 03:00 UTC
## The problem
when swtiching from native context to webview context，the switching fails for the reason: Failed to get sockets matching: @weblayer_devtools_remote_.*12531

## Environment

* Appium version 1.20.2
*  webview version 103.0.5060
* mobile phone system : android 11

### （1）adb can get the right webview socket**

[debug] [35m[ADB][39m Running 'xxxxx/adb -P 5037 -s d015ec38 shell cat /proc/net/unix'
**[debug] [35m[AndroidDriver][39m Parsed 1 active devtools socket: ["@webview_devtools_remote_24056"]**

### （2）chrome version is right
debug] [35m[ADB][39m Running 'xxxx/adb -P 5037 -s d015ec38 shell dumpsys package com.google.android.webview'
[debug] [35m[Chromedriver][39m Found Chrome bundle 'com.google.android.webview' version '103.0.5060'
**[debug] [35m[Chromedriver][39m Found 1 executable capable of automating Chrome '103.0.5060'.****

### （3）when chromdriver creates a new session, it reports some error

[debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"com.xxxx","androidUseRunningApp":true,"androidDeviceSerial":"d015ec38","androidProcess":"com.android.chrome"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[35m[WD Proxy][39m Got response with status 500: {"value":{"error":"unknown error","message":"unknown error: Failed to get sockets matching: @weblayer_devtools_remote_.*14033\n  (make sure the app has its WebView/WebLayer configured for debugging)","stacktrace":"0   chromedriver_mac64_v103.0.5060.24   0x00000001029460f9 chromedriver_mac64_v103.0.5060.24 + 4448505\n1   chromedriver_mac64_v103.0.5060.24   0x00000001028d1f73 chromedriver_mac64_v103.0.5060.24 + 3972979\n2   chromedriver_mac64_v103.0.5060.24   0x000000010256c268 chromedriver_mac64_v103.0.5060.24 + 410216\n3   chromedriver_mac64_v103.0.5060.24   0x0000000102549523 chromedriver_mac64_v103.0.5060.24 + 267555\n4   chromedriver_mac64_v103.0.5060.24   0x0000000102554160 chromedriver_mac64_v103.0.5060.24 + 311648\n5   chromedriver_mac64_v103.0.5060.24   0x000000010255365e chromedriver_mac64_v103.0.5060.24 + 308830\n6   chromedriver_mac64_v103.0.5060.24   0x000000010258c34f chromedriver_mac64_v103.0.5060.24 + 541519\n7   chromedriver_mac64_v103.0.5060.24   0x00000001025c56ca chromedriver_mac64_v103.0...
[debug] [35m[W3C][39m Matched W3C error code 'unknown error' to UnknownError
[debug] [35m[Chromedriver][39m UnknownError: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get sockets matching: @weblayer_devtools_remote_.*14033
[debug] [35m[Chromedriver][39m   (make sure the app has its WebView/WebLayer configured for debugging)

### (4)chromedriver error log is as follows.

**[Chromedriver] [STDERR] [1658976225.628][DEBUG]: Sending adb command: host:transport:d015ec38|shell:grep -a '@webview_devtools_remote_.*14033' /proc/net/unix**
[Chromedriver] [STDERR] [1658976225.708][DEBUG]: Received adb response:
**[Chromedriver] [STDERR] [1658976225.708][DEBUG]: Sending adb command: host:transport:d015ec38|shell:grep -a '@weblayer_devtools_remote_.*14033' /proc/net/unix**
[Chromedriver] [STDERR] [1658976225.758][DEBUG]: Received adb response:
[Chromedriver] [STDERR] [1658976225.758][INFO]: [bcdf6634c772ac75bbb10ec59c9085b0] RESPONSE InitSession ERROR unknown error: Failed to get sockets matching: @weblayer_devtools_remote_.*14033
[Chromedriver] [STDERR]   (make sure the app has its WebView/WebLayer configured for debugging)
[Chromedriver] [STDERR] [1658976225.758][DEBUG]: Log type 'driver' lost 0 entries on destruction
[Chromedriver] [STDERR] [1658976225.758][DEBUG]: Log type 'browser' lost 0 entries on destruction
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[Chromedriver] An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get sockets matching: @weblayer_devtools_remote_.*14033
[Chromedriver]   (make sure the app has its WebView/WebLayer configured for debugging)

## I don't know why chromedriver get the **webview_devtools_remote_.*14033** socket failled, I can get it using adb in the terminal

**xxxxxxx@MacBook-Pro-4 log % adb -P 5037 -s d015ec38 shell cat /proc/net/unix | grep webview
0000000000000000: 00000002 00000000 00010000 0001 01 395484 @webview_devtools_remote_26210**

**Comment by linpy00** [comment] 2022-07-28 03:24
I found some information，adb gets webview socket  ["@webview_devtools_remote_24056"]，but chromedriver gets webview socket ["webview_devtools_remote_.14033"]。 The ports are totally differnt , but why?

**Comment by KazuCocoa** [comment] 2022-07-28 05:45
What's about with the latest appium? Appium 2 and uia2 driver 5.6.2.

**Comment by KazuCocoa** [comment] 2022-07-28 06:49
Probably duplicate of https://github.com/appium/appium/issues/17275

**Comment by KazuCocoa** [comment] 2022-07-28 07:24
copied from https://github.com/appium/appium/issues/17275#issuecomment-1197732540 ...

Used https://github.com/GoogleChrome/android-browser-helper/tree/main/demos/custom-tabs-example-app as an example. https://gist.github.com/KazuCocoa/fb96bc842db67523d5c060515bf1b211

It seems like chromedriver failed to create a session.
```
[Chromedriver@64d4] Starting W3C Chromedriver session with capabilities: {
[Chromedriver@64d4]   "capabilities": {
[Chromedriver@64d4]     "alwaysMatch": {
[Chromedriver@64d4]       "goog:chromeOptions": {
[Chromedriver@64d4]         "androidPackage": "com.brave.browser",
[Chromedriver@64d4]         "androidUseRunningApp": true,
[Chromedriver@64d4]         "androidDeviceSerial": "D0AA002182JC0202126",
[Chromedriver@64d4]         "args": [
[Chromedriver@64d4]           "--disable-popup-blocking"
[Chromedriver@64d4]         ]
[Chromedriver@64d4]       },
[Chromedriver@64d4]       "goog:loggingPrefs": {
[Chromedriver@64d4]         "browser": "ALL"
[Chromedriver@64d4]       }
[Chromedriver@64d4]     }
[Chromedriver@64d4]   }
[Chromedriver@64d4] }
[debug] [Chromedriver@64d4] Matched '/session' to command name 'createSession'
[debug] [Chromedriver@64d4] Proxying [POST /session] to [POST http://127.0.0.1:8000/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"com.brave.browser","androidUseRunningApp":true,"androidDeviceSerial":"D0AA002182JC0202126","args":["--disable-popup-blocking"]},"goog:loggingPrefs":{"browser":"ALL"}}}}
[Chromedriver@64d4] Got response with status 500: {"value":{"error":"unknown error","message":"unknown error: Failed to get sockets matching: @weblayer_devtools_remote_.*32236\n  (make sure the app has its WebView/WebLayer configured for debugging)","stacktrace":"0   chromedriver_mac64_v103.0.5060.53   0x0000000107dfa079 chromedriver_mac64_v103.0.5060.53 + 4444281\n1   chromedriver_mac64_v103.0.5060.53   0x0000000107d86403 chromedriver_mac64_v103.0.5060.53 + 3970051\n2   chromedriver_mac64_v103.0.5060.53   0x0000000107a21038 chromedriver_mac64_v103.0.5060.53 + 409656\n3   chromedriver_mac64_v103.0.5060.53   0x00000001079fe393 chromedriver_mac64_v103.0.5060.53 + 267155\n4   chromedriver_mac64_v103.0.5060.53   0x0000000107a08fb0 chromedriver_mac64_v103.0.5060.53 + 311216\n5   chromedriver_mac64_v103.0.5060.53   0x0000000107a084ae chromedriver_mac64_v103.0.5060.53 + 308398\n6   chromedriver_mac64_v103.0.5060.53   0x0000000107a4110f chromedriver_mac64_v103.0.5060.53 + 540943\n7   chromedriver_mac64_v103.0.5060.53   0x0000000107a7a44a chromedriver_mac64_v103.0...
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [Chromedriver@64d4] UnknownError: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get sockets matching: @weblayer_devtools_remote_.*32236
[debug] [Chromedriver@64d4]   (make sure the app has its WebView/WebLayer configured for debugging)
[debug] [Chromedriver@64d4]     at errorFromW3CJsonCode (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/@appium/base-driver/lib/protocol/errors.js:923:25)
[debug] [Chromedriver@64d4]     at ProxyRequestError.getActualError (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/@appium/base-driver/lib/protocol/errors.js:798:14)
[debug] [Chromedriver@64d4]     at JWProxy.command (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:340:19)
[debug] [Chromedriver@64d4]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [Chromedriver@64d4]     at Chromedriver.startSession (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:598:5)
[debug] [Chromedriver@64d4]     at Chromedriver.start (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:529:7)
[debug] [Chromedriver@64d4]     at AndroidUiautomator2Driver.setupNewChromedriver (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:471:3)
[debug] [Chromedriver@64d4]     at AndroidUiautomator2Driver.startChromedriverProxy (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:217:10)
[debug] [Chromedriver@64d4]     at AndroidUiautomator2Driver.switchContext (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:124:5)
[debug] [Chromedriver@64d4]     at AndroidUiautomator2Driver.setContext (/Users/kazuaki/GitHub/appium-flutter-driver/driver/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:51:3)
[Chromedriver@64d4] Chromedriver exited unexpectedly with code null, signal SIGTERM
[debug] [Chromedriver@64d4] Changed state to 'stopped'
```

Then... the error was probably:
https://source.chromium.org/chromium/chromium/src/+/main:chrome/test/chromedriver/chrome/device_manager.cc;l=185?q=make%20sure%20the%20app%20has%20its%20WebView%2FWebLayer&ss=chromium

**Comment by KazuCocoa** [comment] 2022-07-28 07:40
In the above case, when I killed all chrome browser processes and remove chromium browsers (e.g. Brave) from my device, the above error has gone. Potentially chromedriver confused chromium based browsers(?).

**Comment by linpy00** [comment] 2022-07-28 07:47
Thanks for your information, I will have it a try.

**Comment by mykola-mokhnach** [comment] 2022-07-28 08:18
Chrmedriver does not support other browsers/webviews based on Chromium engine. You could try https://github.com/dlenroc/appium-playwright-driver as a possible solution.

**Closed** 2022-07-28 08:19 UTC
Labels: NeedsInfo
