### ISSUE TITLE
Problem to use appium with elements that have accessibility properties in iOS

### ISSUE THREAD

**Issue by mauriparra** [appium/appium#8345] opened 2017-04-28 13:19 UTC
## The problem

I am using appium to generate automated tests but i have a problem. The developers add a accessibility property in some UI elements of the storyBoard. 

![screen shot 2017-04-27 at 10 48 48 am](https://cloud.githubusercontent.com/assets/24278482/25530258/4a0f0f2e-2beb-11e7-9b5f-4fdc0a725f48.png)

But when the element has this property accessibility checkbox as enabled, appium and appium-inspector can not detect the others UI elements that has inside. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Desktop OS/version used to run Appium: macOS Sierra 10.12
* Node.js version (unless using Appium.app|exe): 6.10.0
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: simulator
* XCode: 8.3

**Comment by mykola-mokhnach** [comment] 2017-04-28 13:47
Closed as duplicate of https://github.com/appium/appium/issues/6517

**Closed by mykola-mokhnach** 2017-04-28 13:47 UTC
