### ISSUE TITLE
driver.hideKeyboard() doesn't work in appium 1.10.0-beta.5

### ISSUE THREAD

**Issue by nenaddrop** [appium/appium#11737] opened 2018-11-26 17:16 UTC
## The problem

Calling driver.hideKeyboard() in test results in an error:

    org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: The software keyboard cannot be closed

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0-beta.5
* Last Appium version that did not exhibit the issue (if applicable): 1.9.1
* Desktop OS/version used to run Appium: macOS High Sierra (10.13.6)
* Node.js version (unless using Appium.app|exe): 10.5.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator Pixel XL API 28
* Appium CLI or Appium.app|exe: CLI

## Details

N/A

## Link to Appium logs

I'll past just part of the appium log where hide_keyboard is called:
```
[HTTP] --> POST /wd/hub/session/ecd685b6-4964-4091-9893-9c4a67d9be35/appium/device/hide_keyboard
[HTTP] {}
[debug] [W3C (ecd685b6)] Calling AppiumDriver.hideKeyboard() with args: [null,null,null,null,"ecd685b6-4964-4091-9893-9c4a67d9be35"]
[debug] [ADB] Running '/Users/nenad/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys input_method'
[debug] [ADB] Running '/Users/nenad/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell input keyevent 111'
[debug] [ADB] Running '/Users/nenad/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys input_method'
[debug] [ADB] Running '/Users/nenad/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys input_method'
[debug] [ADB] Running '/Users/nenad/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys input_method'
[debug] [ADB] Running '/Users/nenad/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys input_method'
[debug] [ADB] Running '/Users/nenad/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys input_method'
[debug] [W3C (ecd685b6)] Encountered internal error running command: Error: The software keyboard cannot be closed
[debug] [W3C (ecd685b6)]     at AndroidUiautomator2Driver.commands.hideKeyboard (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/general.js:82:13)
[HTTP] <-- POST /wd/hub/session/ecd685b6-4964-4091-9893-9c4a67d9be35/appium/device/hide_keyboard 500 2693 ms - 573
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/ecd685b6-4964-4091-9893-9c4a67d9be35
[HTTP] {}
```
## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by mykola-mokhnach** [comment] 2018-11-26 17:53
Did you try to execute `adb shell input keyevent 111` when keyboard is shown? Does it hide the keyboard?

**Comment by saikrishna321** [comment] 2018-11-26 19:01
@nenaddrop 

I was not able to reproduce this with the latest server version. 

```
[HTTP] <-- GET /wd/hub/session/926ce84a-5a0a-4326-9567-693480c58595 200 10 ms - 1111
[HTTP]
[HTTP] --> POST /wd/hub/session/926ce84a-5a0a-4326-9567-693480c58595/appium/device/hide_keyboard
[HTTP] {}
[debug] [W3C (926ce84a)] Calling AppiumDriver.hideKeyboard() with args: [null,null,null,null,"926ce84a-5a0a-4326-9567-693480c58595"]
[debug] [ADB] Running '/Users/saikrisv/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys input_method'
[debug] [ADB] Running '/Users/saikrisv/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell input keyevent 111'
[debug] [ADB] Running '/Users/saikrisv/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys input_method'
[debug] [W3C (926ce84a)] Responding to client with driver.hideKeyboard() result: null
[HTTP] <-- POST /wd/hub/session/926ce84a-5a0a-4326-9567-693480c58595/appium/device/hide_keyboard 200 1490 ms - 14
```

**Comment by mykola-mokhnach** [comment] 2018-11-27 08:36
Does this mean that executing `adb shell input keyevent 111` does not hide keyboard on the API 28 emulator? How about `adb shell input keyevent 4`?

**Comment by nenaddrop** [comment] 2018-11-27 11:53
Hi @mykola-mokhnach,

Sorry for the lack of clarity. I did a bit more investigation this morning and found the following in my app-under-test.
App uses a simple sign-up form with email and password input fields, T&C checkbox and a signup button. Emulator is Pixel XL Android 9.0 API level 28.

- `adb shell input keyevent 111` **works** when keyboard is raised by bringing email input into focus.
- `adb shell input keyevent 111` **doesn't work** when focus is on the password field.
- `adb shell input keyevent 4` **works** when focus in on the password field.

The problem is now with a specific field type, in this case the password input field. At this moment I am not sure if it might be something in how the app was developed but I've tested again on Android 8.1 API level 27 and sending keyevent 111 hides the keyboard when focus is on either input field.

**Comment by mykola-mokhnach** [comment] 2018-11-27 12:49
ok, I'll add a fallback then

**Comment by nenaddrop** [comment] 2018-11-28 10:43
> ok, I'll add a fallback then

Thank you man!

**Comment by saikrishna321** [comment] 2018-11-28 10:52
@nenaddrop https://github.com/appium/appium-android-driver

**Comment by mykola-mokhnach** [comment] 2018-12-14 13:55
The fix has been published to beta

**Closed by mykola-mokhnach** 2018-12-14 13:55 UTC
Labels: Android, Enhancement

**Comment by nenaddrop** [comment] 2018-12-17 09:51
Verified that it works on appium v1.11.0-beta.2.

**Comment by gamaitalo** [comment] 2019-03-08 11:50
I'm still having this problem with Appium v1.11.1

**Comment by jgreen210** [comment] 2019-05-01 14:31
We're running tests on an android emulator with a hardware keyboard. On at least 1.10.0, 1.10.1 and 1.12.1, hideKeyboard() is failing with:

```
2019-04-29 13:52:04:439 [MJSONWP (918362cd)] Encountered internal error running command: Error: The software keyboard cannot be closed
2019-04-29 13:52:04:440 [MJSONWP (918362cd)]     at AndroidDriver.commands.hideKeyboard (.../node_modules/appium-android-driver/lib/commands/general.js:87:9)
2019-04-29 13:52:04:440 [MJSONWP (918362cd)]     at <anonymous>
```

Removing the hideKeyboard() calls in our test script makes it pass for android (although need to keep them for testing the same React Native app with the same test script on iOS, so I've had to add a conditional wrapper).

It's therefore looking plausible that hideKeyboard() was a no-op for hardware keyboards prior to 1.10.0. If I'm right, that should probably be re-instated? ...keeping the above fixes for soft (i.e. on-screen) keyboards.

Does this explain why e.g. @gamaitalo says this hasn't been fixed?
