### ISSUE TITLE
Appium Sub-Dependency Locks Version of @babel/runtime

### ISSUE THREAD

**Issue by samuelfreiberg** [appium/appium#18739] opened 2023-06-06 22:51 UTC
Hi all,

Appium [teen_process](https://github.com/appium/node-teen_process) sub-dependency brings in a locked version of a highly-popular package, @babel/runtime. This causes a couple major problems:

1. Teams working in a JS Monorepo cannot use yarn to standardize on a single version.
2. Doesn't allow for auto-update tools (like GitHub's dependabot) and internal tools of large companies to automatically deal with version updates.

I'm suggesting that we change teen_process to bring in minor updates of @babel/runtime by using the `**^**` semantic.

This is currently a big problem for our team, and for the reasons I listed above, should be a positive change.

**Comment by jlipps** [comment] 2023-06-07 17:20
@samuelfreiberg are you using this package directly as a library or are you saying this is a problem because teen process is a dependency of appium and you're using appium? because i doubt that teen process is the only place within the appium tree where babel runtime might be included at a pinned version.

**Comment by samuelfreiberg** [comment] 2023-06-07 17:36
@jlipps Sorry, should have clarified.

Yes, I am using Appium. Teen_process is a sub-dependency for Appium and the following sub-dependencies:
•	@appium/support
•	Appium-windows-driver
•	@appium/docutils

Teen_Process is the only dependency I see in my yarn.lock that brings in a locked version of @babel/runtime. I am on 
`"appium": "2.0.0-beta.71"`

**Comment by samuelfreiberg** [comment] 2023-06-07 17:38
@jlipps So if we were to unpin @babel/runtime in teen_process, such as
`"@babel/runtime" "7.19.0"` ->> `"@babel/runtime" "**^**7.19.0"`, that would help solve this issue and all future ones

**Comment by boneskull** [comment] 2023-06-07 23:14
what needs to happen here is that we shouldn't be using babel runtime at all, because we don't need it.

**Comment by samuelfreiberg** [comment] 2023-06-07 23:19
> what needs to happen here is that we shouldn't be using babel runtime at all, because we don't need it.

Or this. The consumer should be the one using it. Why does teen_process (or any other) need it?

**Comment by jlipps** [comment] 2023-06-08 18:04
Well `teen_process` uses it because otherwise it would not work as a standalone package, which was how it was designed. But yeah, we should migrate this package to use tsc instead for building

**Comment by samuelfreiberg** [comment] 2023-06-08 18:20
@jlipps How long would something like that take? What's the process to schedule a task like that?

**Comment by samuelfreiberg** [comment] 2023-06-08 21:20
@boneskull If you have any PRs or related work regarding changing from building with Babel to TS, please let me know! This is a relatively high-pri issue for my team and I'm willing to jump in and change it!

**Comment by jlipps** [comment] 2023-06-09 18:17
@samuelfreiberg here's an example commit: https://github.com/appium/appium-android-driver/commit/2377a5cb299c8173dd43728072377afae22b70cd. many of the specific changes here might not be necessary to look at. primarily what you care about is adding tsc and tsconfig.json, updating package.json build scripts, and removing babel related deps.

**Comment by samuelfreiberg** [comment] 2023-06-12 17:05
[Creating a PR ](https://github.com/appium/node-teen_process/pull/250). Would appreciate some reviews when you have the change - thank you!

**Comment by mykola-mokhnach** [comment] 2023-06-26 15:39
Closed as fixed

**Closed by mykola-mokhnach** 2023-06-26 15:39 UTC
Labels: Node, Help Needed
