### ISSUE TITLE
Appium server not running

### ISSUE THREAD

**Issue by sowmyalakshmi** [appium/appium#5240] opened 2015-06-11 05:49 UTC
Appium server not running. Installed appium 1.4.0 and using server address 127.0.0.1 and port 4723.

Getting the below error
Launching Appium with command: '/usr/local/bin/node' lib/server/main.js --address "127.0.0.1" --command-timeout "7200" --debug-log-spacing --log-timestamp --platform-version "8.1" --platform-name "iOS" --app "/Users//Desktop/My.app" --show-ios-log --default-device

dyld: lazy symbol binding failed: Symbol not found: _node_module_register
Referenced from: /Applications/Appium.app/Contents/R
esources/node_modules/appium/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build/Release/bufferutil.node
Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
Referenced from: /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build/Release/bufferutil.node
Expected in: dynamic lookup

Please help in resolving this issue.

**Comment by sebv** [comment] 2015-06-11 06:02
```
rm -rf node_modules
npm cache clear
npm install
```

Please go to https://discuss.appium.io/ for support.

**Comment by sebv** [comment] 2015-06-11 06:02
Closing, not a bug.

**Closed by sebv** 2015-06-11 06:02 UTC
Labels: NeedsTriage
