### ISSUE TITLE
 Unable to create a new remote session. Please check the server log for more details

### ISSUE THREAD

**Issue by SaraAlDurini** [appium/appium#14983] opened 2020-12-30 18:12 UTC
## Environment

* Appium version ; 1.19.1
* Desktop OS/ windows 10 / 64bit
* Node.js v14.15.3.
* Mobile platform/version under test:  Android V 10

## Issue 

java.util.concurrent.ExecutionException: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\moust\\.katalon\\tools\\android_sdk\\platform-tools\\adb.exe -P 5037 -s MRH6O7VSUCVC99SC shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Stderr: 'Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-14TBPC0', ip: '192.168.1.62', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: SwipeableAndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\moust\\.katalon\\tools\\android_sdk\\platform-tools\\adb.exe -P 5037 -s MRH6O7VSUCVC99SC shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Stderr: 'Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
    at getResponseForW3CError (C:\Users\moust\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\moust\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:384:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-14TBPC0', ip: '192.168.1.62', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: SwipeableAndroidDriver
	at com.kms.katalon.composer.components.impl.dialogs.ProgressMonitorDialogWithThread.runAndWait(ProgressMonitorDialogWithThread.java:49)
	at com.kms.katalon.composer.mobile.objectspy.components.MobileLocalAppComposite$12.run(MobileLocalAppComposite.java:474)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\moust\\.katalon\\tools\\android_sdk\\platform-tools\\adb.exe -P 5037 -s MRH6O7VSUCVC99SC shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Stderr: 'Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-14TBPC0', ip: '192.168.1.62', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: SwipeableAndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\moust\\.katalon\\tools\\android_sdk\\platform-tools\\adb.exe -P 5037 -s MRH6O7VSUCVC99SC shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Stderr: 'Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
    at getResponseForW3CError (C:\Users\moust\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\moust\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:384:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-14TBPC0', ip: '192.168.1.62', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: SwipeableAndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at com.kms.katalon.core.appium.driver.SwipeableAndroidDriver.execute(SwipeableAndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:85)
	at com.kms.katalon.core.appium.driver.SwipeableAndroidDriver.<init>(SwipeableAndroidDriver.java:24)
	at com.kms.katalon.core.appium.driver.AppiumDriverManager.createMobileDriver(AppiumDriverManager.java:498)
	at com.kms.katalon.core.appium.driver.AppiumDriverManager.createMobileDriver(AppiumDriverManager.java:480)
	at com.kms.katalon.core.mobile.keyword.internal.MobileDriverFactory.startLocalMobileDriver(MobileDriverFactory.java:532)
	at com.kms.katalon.composer.mobile.objectspy.dialog.MobileInspectorController.startMobileApp(MobileInspectorController.java:195)
	at com.kms.katalon.composer.mobile.objectspy.components.MobileLocalAppComposite$12$1.call(MobileLocalAppComposite.java:479)
	at com.kms.katalon.composer.components.impl.dialogs.ProgressMonitorDialogWithThread.startThreadAndWait(ProgressMonitorDialogWithThread.java:36)
	at com.kms.katalon.composer.components.impl.dialogs.ProgressMonitorDialogWithThread.runAndWait(ProgressMonitorDialogWithThread.java:48)
	... 2 more
Caused by: java.lang.reflect.InvocationTargetException
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 22 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\moust\\.katalon\\tools\\android_sdk\\platform-tools\\adb.exe -P 5037 -s MRH6O7VSUCVC99SC shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Stderr: 'Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-14TBPC0', ip: '192.168.1.62', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: SwipeableAndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\moust\\.katalon\\tools\\android_sdk\\platform-tools\\adb.exe -P 5037 -s MRH6O7VSUCVC99SC shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Stderr: 'Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2295)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1370)
	at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1353)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:582)
	at android.content.ContentProvider.call(ContentProvider.java:2162)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:481)
	at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
    at getResponseForW3CError (C:\Users\moust\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\moust\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:384:37)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 23 more

**Comment by amedvedjev** [comment] 2020-12-30 18:27
1. open google
2. enter "Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS"
3. explore answers

most common: play with developer options. e.g. -> https://github.com/appium/appium/issues/13802

**Comment by mykola-mokhnach** [comment] 2020-12-30 19:41
Duplicate of https://github.com/appium/appium/issues/14209

**Closed by mykola-mokhnach** 2020-12-30 19:41 UTC
