### ISSUE TITLE
 Non http url in chrome android on real device Support

### ISSUE THREAD

**Issue by kani19** [appium/appium#5302] opened 2015-06-25 07:29 UTC
So the scenario is:

    Launch my app (abc.apk)
    Open chrome with a html
    Click on a link in above html (which is non http.. something like abc://settings?service......). This link opens my abc.apk

Now, it does not tap on this link. Or may be its tapping but not opening my app.
But the same code opens all http urls.

**Comment by Jonahss** [comment] 2015-06-30 18:49
This looks like a duplicate of #5311 
Would you agree?

**Closed by Jonahss** 2015-06-30 18:49 UTC
Labels: NeedsTriage
