### ISSUE TITLE
Input text Error

### ISSUE THREAD

**Issue by amusharraf** [appium/appium#8638] opened 2017-06-08 20:24 UTC
To begin, I am using one simulator(XCode) on my actual machine and another simulator also Xcode on a remote machine. So when I run a test, the test runs but as soon as it gets to the command "Input Text" I get the following error:

**WebDriverException: Message: Parameters were incorrect. We wanted {"required":["value"]} and you sent ["text","sessionId","id","value"]**

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 both machines
* Desktop OS/version used to run Appium: Mac OS Sierra and El Captain
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Simulators

## Link to Appium logs

https://gist.github.com/amusharraf/f1f7d31b2aca71f289bd1b1efc5892ea

**Comment by dpgraham** [comment] 2017-06-08 22:48
I don't see the error in your logs. Which lines does the error occur?

**Comment by mykola-mokhnach** [comment] 2017-06-09 06:11
This is known issue. Please update Appium to 1.6.6-beta to have it fixed or downgrade your client version

**Comment by mykola-mokhnach** [comment] 2017-06-09 07:48
Closed as duplicate of https://github.com/appium/appium/issues/8407

**Closed by mykola-mokhnach** 2017-06-09 07:48 UTC

**Comment by amusharraf** [comment] 2017-06-09 13:30
Thank you so much! this thing is a lifesaver.

**Comment by akifhazarvi** [comment] 2017-09-26 14:46
Hi Guys
I still see the same issue using conceptjs. Running a test on IOS 10.2 Iphone 6
Parameters were incorrect. We wanted {"required":["value"]} and you sent ["value","text"]
Appium 1.6.5
codeceptjs: 1.0.3
webdriverio: 4.8.0
