### ISSUE TITLE
【appium/WebDriverAgent】sessionId is null when visit 'http://localhost:8200/status' 

### ISSUE THREAD

**Issue by 201905270246** [appium/appium#14472] opened 2020-06-22 10:31 UTC
## The problem

sessionId is null when visit 'http://localhost:8200/status'
![85276645-c0cd1480-b4b4-11ea-8c25-783d90fc6ca4](https://user-images.githubusercontent.com/51073321/85277801-8a909480-b4b6-11ea-9400-8b5be8b4e7db.png)

**Comment by mykola-mokhnach** [comment] 2020-06-22 10:33
Please fill out the issue report properly

closed as incomplete (also not a bug)

**Closed by mykola-mokhnach** 2020-06-22 10:33 UTC
