### ISSUE TITLE
Unable to click on iOS alert with AppiumLibrary

### ISSUE THREAD

**Issue by zastress** [appium/appium#19891] opened 2024-03-13 10:38 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am unable to click the iOS alert on simulator since version 6, using AppiumLibrary. No error in Appium logs

### Expected Behavior

Alert button should be clicked

### Minimal Reproducible Example

- Get an iOs alert on the screen
- Try to click it

### Environment

- Operating system: MacOS Sonoma
- Appium server version (output of `appium --version`): v2.5.1
- Appium driver(s) and their version(s): xcuitest@7.3.0
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): v20.8.0
- `npm` version (output of `npm --version`): 10.2.5
- Last component(s) version which did _not_ exhibit the problem: xcuitest@5.16.1
- Platform and version under test: iOS simulator 17.2
- Real device or emulator/simulator: simulator

### Link to Appium Logs

https://gist.github.com/zastress/555c4fb9763e2f97bd5fe5bd12b4b15f

**Comment by mykola-mokhnach** [comment] 2024-03-13 11:12
Possible duplicate of https://github.com/appium/appium/issues/19874

**Comment by zastress** [comment] 2024-03-13 11:21
As you can see from the Appium logs, I tried with both click on element and tap with positions.
In other issues, popup was not visible inside Appium inspector. In this case, Appium sees the element, "clicks" on it but nothing happens.
So, is this a duplicate of the others?

**Comment by mykola-mokhnach** [comment] 2024-03-13 11:36
Have you tried to interact with alerts using dedicated methods like it is described in https://discuss.appium.io/t/unable-to-click-on-allow-once-in-ios-precise-location-pop-up/41910 ?

**Comment by zastress** [comment] 2024-03-13 12:03
I managed to get it working with `driver.execute_script 'mobile: alert', {action: 'accept', buttonLabel: 'Allow'}`.

Thanks

**Closed** 2024-03-13 12:23 UTC
Labels: Needs Info

**Comment by dzmitry999d** [comment] 2024-11-13 15:35
how to click to Allow Once?

 Device().driver.execute_script("mobile: alert",  {"action": "Allow Once"}) doesn't work
 
   Device().driver.execute_script("mobile: alert", {"action": "accept"}) the same not
