### ISSUE TITLE
XCTAutomationSupport.framework signing error after updating to High Sierra and Xcode 9.3

### ISSUE THREAD

**Issue by tsibiski** [appium/appium#10554] opened 2018-04-17 16:29 UTC
## The problem

Everything worked perfectly for me until I was forced to upgrade my iPhone 6S to 10.3, from 10.12.6.
I decided it was necessary because iOS began to harass me to update it, and no matter how many times I deleted the update from the phone's storage, it would redownload it in short order, and continuously threw up device level alerts to upgrade. For a while, this was not a big deal, as the alerts were rare, but eventually it became an issue that prevented automation from even running.

*******************************Direct Error*******************************
[Xcode] CodeSign /Users/jenkins/Library/Developer/Xcode/DerivedData/WebDriverAgent-bsdadbluubjelohktnqnosqfdiuf/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/Frameworks/XCTAutomationSupport.framework
[Xcode]     cd /usr/local/lib/node_modules/appium-ios/node_modules/appium-xcuitest-driver/WebDriverAgent
[Xcode]     export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
[Xcode]     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin"

[Xcode] Signing Identity:     "iPhone Developer: ******* ****** (**************)"
[Xcode] /usr/bin/codesign --force --sign 981AB0E0C4A2EC5A45A335855FA9E46070FBAA9F --deep --preserve-metadata=identifier,entitlements,flags --timestamp=none /Users/jenkins/Library/Developer/Xcode/DerivedData/WebDriverAgent-bsdadbluubjelohktnqnosqfdiuf/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/Frameworks/XCTAutomationSupport.framework
[Xcode] /Users/jenkins/Library/Developer/Xcode/DerivedData/WebDriverAgent-bsdadbluubjelohktnqnosqfdiuf/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/Frameworks/XCTAutomationSupport.framework: replacing existing signature
[Xcode] /Users/jenkins/Library/Developer/Xcode/DerivedData/WebDriverAgent-bsdadbluubjelohktnqnosqfdiuf/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/Frameworks/XCTAutomationSupport.framework: errSecInternalComponent
[Xcode] Command /usr/bin/codesign failed with exit code 1
*******************************End Of Error*******************************

First, I upgraded the iPhone 6S from 10.2 to 10.3
Second, I turned out that Xcode 9.2, which I was using, could not interact with iOS 10.3, so I upgraded it to Xcode 9.3
Third, I found that Xcode 9.3 was not compatible with Sierra 10.12.6, so upgraded to High Sierra, now 10.13.4

## Environment

* Appium version 1.7.2 (on High Sierra)
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2 (but on Sierra)
* Desktop OS/version used to run Appium: 10.12.6 when no issues, now 10.13.4
* Node.js version (unless using Appium.app|exe): 8.9.1
* Mobile platform/version under test: iPhone 6S (real device), 10.3 (was 10.2.6 when last worked)
* Appium CLI or Appium.app|exe:
"showXcodeLog" = True
"useNewWDA" = False
"wdaLocalPort" = 5081
"autoAcceptAlerts" = True
"app" = ./app.ipa
"udid" = ** Set to actual device udid **
"automationName" = Xcuitest
"platformName" = iOS
"platformVersion" = 11.3
"deviceName" = iPhone6S
"newCommandTimeout" = 99999
"launchTimeout" = 99999
driver = webdriver.Remote("http://127.0.0.1:5080/wd/hub", desired_capabilities)
*Note*: Using Selenium grid to run in parallel.

node /usr/local/bin/appium --session-override --nodeconfig /Users/******/Appium/ios/PHX/iPhone6/*******.json -p 5083 --log /Users/*****/jenkins-node-home/workspace/Automation/iOS/Local_QA_iOS_Auto_iPhone6/appium.log

## Link to Appium logs

Appium Log In Full
https://gist.github.com/tsibiski/0189df60941898bff5ec2845edf64ffe

## Code To Reproduce Issue [ Good To Have ]

The code isn't the issue, as it is identical between the scenario where it worked (and worked perfectly for 6 months), and today, after I updated the iPhone OS and Mac OS. The only change I made in my code is to the "platformVersion" argument above. 

That being said, I would still provide the code if it wasn't for how highly complex and parameterized it is. The scripts are designed to be able to run any device from any job using selenium for browsers, xcuitest for ios, and uiautomator2 for android. Because of that, much of it is set by variables provided by a bunch of Jenkins jobs.

**What I tried:
1) Cleared out installed apps and restarted iPhone
2) Ran above codesign command from provided xcode log error, and did not receive any errors
3) Confirmed correct appium and appium-xcuitest-driver being used (only one on system)
4) Uninstalled Xcode entirely, and removed data from ~/Library/Developers/Xcode, then reinstalled Xcode 9.3
5) Deleted and reinstalled 1.7.2 - then added signing back to WebdriverAgent.xproj
6) Made sure all Appium dependencies were fully up-to-date, restarted Mac build machine and tried again
7) Verified certificate in keychain had all required access and was still valid

I blame the issue squarely on a mistake I am making somewhere - forgetting to update something parameter-wise, or needing to update a program somewhere. That or there is some issue being caused by Mac OS. Any help locating the source of the problem to find a workaround would be amazing.

**Comment by mykola-mokhnach** [comment] 2018-04-17 17:52
> 	/private/var/containers/Bundle/Application/A5BE099F-BB4F-4181-B090-BDC643BDCBEF/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: required code signature missing for '/private/var/containers/Bundle/Application/A5BE099F-BB4F-4181-B090-BDC643BDCBEF/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer'

I assume the error is pretty clear - you must fix codesigning. If the command fails after manual execution then it will for sure fail being executed by Appium.

Also, it is recommended to use appium@beta with Xcode 9.3

**Comment by mykola-mokhnach** [comment] 2018-04-17 17:53
I would also try to delete Xcode caches

**Comment by tsibiski** [comment] 2018-04-17 17:56
I assume the error is pretty clear - you must fix codesigning. If the command fails after manual execution then it will for sure fail being executed by Appium.

It would be clear if the code signing was not correct (which it is - per my comments). The code signing did not change after upgrading to High Sierra. It stopped working then. After that, I deleted everything, and re-did the setup, with the same result. 

Also, per my comment, I already deleted Xcode caches. I will try the beta version.

**Comment by mykola-mokhnach** [comment] 2018-04-17 17:59
What if you set codesigning properties directly in Xcode? Can you build the project for the device then? Which error it shows?

**Comment by tsibiski** [comment] 2018-04-17 17:59
I did also do that, and no errors occur when I build to the device in Xcode - which seems unusual.

**Comment by mykola-mokhnach** [comment] 2018-04-17 18:25
You can try https://github.com/facebook/WebDriverAgent/pull/873

**Comment by tsibiski** [comment] 2018-04-17 18:39
Thanks for that info. So wow, really bizarre -- but I implemented the changes exactly as described in https://github.com/facebook/WebDriverAgent/pull/873/files, and that fixed the Xcode command line building of the WebDriverAgentRunner. 0 errors, and works perfectly. 

BUT the same error still occurs when Appium is launching:
Debug-iphoneos/WebDriverAgentRunner-Runner.app/Frameworks/XCTAutomationSupport.framework: errSecInternalComponent
- Command /usr/bin/codesign failed with exit code 1

**Comment by tsibiski** [comment] 2018-04-17 20:51
I just don't understand how this is failing. It works perfectly executing the command manually from the terminal, and I examined the logs to confirm that everything was signed properly. I literally copied the xcode command from my Jenkins console output to do this.

But then, when the xcode command is executed by appium, I get a completely different result, with the above error...

I'm at a loss. I think I will end up re-imaging the Mac build machine tomorrow to see if there is something fubar due to the upgrade from 10.12.6 to 10.13.4.

**Comment by tsibiski** [comment] 2018-04-18 16:27
This may be the same issue: https://github.com/facebook/WebDriverAgent/issues/902

**Comment by tsibiski** [comment] 2018-04-18 20:42
I was able to launch appium only locally by manually running the xcode build command:

xcodebuild build-for-testing -project /usr/local/lib/node_modules/appium-ios/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=MY_DEVICE_UDID IPHONEOS_DEPLOYMENT_TARGET=11.0

This builds it properly, with all code signing successful. If I do that first, and then run an appium script (which also runs that command when you start your driver...), then the WebDriverAgent is loaded on to device, and everything proceeds normally.

However, even with the above workaround when launching appium locally in the terminal, nothing works from Jenkins job launches...

**Comment by tsibiski** [comment] 2018-04-18 21:12
Noticed this difference. When appium runs the command, it does this to codesign
`/usr/bin/codesign --force --sign A8E2D7EECEB80789344455C4696E10DE87613349 --deep --entitlements /Users/jenkins/Library/Developer/Xcode/DerivedData/WebDriverAgent-bsdadbluubjelohktnqnosqfdiuf/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentRunner.build/WebDriverAgentRunner.xctest.xcent
`
When the same command is run outside of appium, this is the path used.
`/usr/bin/codesign --force --sign A8E2D7EECEB80789344455C4696E10DE87613349 --deep --preserve-metadata=identifier,entitlements,flags --timestamp=none /Users/jenkins/Library/Developer/Xcode/DerivedData/WebDriverAgent-bsdadbluubjelohktnqnosqfdiuf/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/Frameworks/XCTAutomationSupport.framework`

For some reason, it uses a different set of frameworks from under "Build/Products", and that seems to be causing the issues...

**Comment by tsibiski** [comment] 2018-04-20 14:40
Per the linked issue above, others have encountered the same issue on High Sierra with the newest Appium. Everything worked again when we downgraded the machine from High Sierra to Sierra, 10.12.6.

@mykola-mokhnach While I still highly doubt that this issue is in any way a fault within Appium, I think that the fix might have to come on Appium's side, if the cause can be isolated. I think this because everything works perfectly when running the raw Xcode build command, so as far as Xcode is likely to be concerned, there is no fault in their logic. 

The issue only occurs when running appium through a build server job.

**Comment by mykola-mokhnach** [comment] 2018-04-20 14:45
Thank you for the investigation. @tsibiski  

When I had problems with my CI builds then the first thing to fix was to gain the access to keychain for the CI user. Normally, the system would ask you for a password if you try to access the private signing key on your local machine, but it is not the case for the remote service, which does not have access to the UI. This was one of the major reasons why `keychainPath` and `keychainPassword ` caps are present in the driver.

**Comment by tsibiski** [comment] 2018-04-20 15:01
Well, I did select "Always Allow" keychain access after the first time running locally. However, I will keep that and mind and make sure I set those when I try this whole process on another machine in the near future. Thanks!

**Comment by mykola-mokhnach** [comment] 2018-04-25 08:00
Closed as third party issue

**Closed by mykola-mokhnach** 2018-04-25 08:00 UTC
Labels: NeedsInfo, NotABug, ThirdParty

**Comment by garkinv** [comment] 2018-04-26 18:24
Hi! I can't run this command
`xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=36d984b8234567890456789758d7df8' test`

Got this error message during tests run, could anyone help me with it?
https://gist.github.com/garkinv/645d72033217fdb454ca9a357d8ff357

As I see the main reason is: Library not loaded: @rpath/XCTest.framework/XCTest
I signed my WDA project

**Comment by tsibiski** [comment] 2018-04-26 19:32
@garkinv I think the key phrase to search for in that is "Warning: unable to build chain to self-signed root for signer"

I googled that error and saw a number of reports of that, and a few suggestions. Although none of the suggestions stuck out to me as the clear fix. So I recommend googling that phrase alone, and then playing around with some of the suggested fixes people reported.

**Comment by garkinv** [comment] 2018-04-27 13:28
@tsibiski thanks!
I just tried to do from these recommendations but still No luck.:
1. relogin account to xcode
2. removing all developer certificates from keychain and download it from scratch
3. tried another WDA project copy from successful setup 1.8.0 appium
4. Tried 1.7.2 and 1.8.0 appium
5. tried to link binary with libraries on Build Phases tab in Xcode project

I assume my user doesn't have permission for something, but I don't know to what.

Maybe any other help from people who stuck with this problem, thanks!
I see error when run Test build from xcode or from commandline:

`: Warning: unable to build chain to self-signed root for signer "iPhone Developer: Vladimir (5PU8&&&&&2)"Warning: unable to build chain to self-signed root for signer "iPhone Developer: Vladimir (5PU8&&&&&2)"Warning: unable to build chain to self-signed root for signer "iPhone Developer: Vladimir (5PU8&&&&&2)"`

And

```
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /var/containers/Bundle/Application/3542A8DB-83B2-47E6-B20A-94D57C28D1FA/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner
  Reason: no suitable image found.
```

**Comment by garkinv** [comment] 2018-05-01 19:49
@mykola-mokhnach @tsibiski maybe you found this issue reproducible for other machines?
Because I stuck with this on 2 machines with setup from scratch using appium installation guide for mac.
Used this - https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/

**Comment by garkinv** [comment] 2018-05-01 20:39
@tsibiski they don't help :( I added libs to target -> build phase. WDA compiled(as before) but tests are failed due to error I mentioned above

**Comment by garkinv** [comment] 2018-05-03 14:05
@tsibiski @mykola-mokhnach 
I solved my issue after - I untrusted all manually trusted developer and root certificates in keychain.
All certificates should be - Use system defaults.

**Comment by SoundaryaBhavanam** [comment] 2019-02-08 20:27
@tsibiski And @[garkinv](/garkinv) I am also facing the same issue while running scripts though jenkins 

I tried all your suggestions, but still issue is not resolved yet .With the below workaround able to proceed for now .
1. Added apple developer account in desired capabilities 
cap.setCapability("xcodeSigningId", "iPhone Developer");
cap.setCapability("xcodeOrgId", "XXXXX");
2.cap.setCapability(IOSMobileCapabilityType.USE_NEW_WDA, false);


@[mykola-mokhnach](/mykola-mokhnach) With latest mac version(Mojave) i am facing this issue
