### ISSUE TITLE
 Cannot read property 'extsprintf' of undefined

### ISSUE THREAD

**Issue by Ankur008** [appium/appium#7543] opened 2016-12-15 06:40 UTC
## The problem

I am trying to install appium using cmd:

sudo npm install -g appium

but end up getting the error:

Cannot read property 'deep-extend' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.2.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v4.7.0
npm ERR! npm  v4.0.3

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/itstym/npm-debug.log

## Environment

 Linux 4.2.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v4.7.0
npm ERR! npm  v4.0.3

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

appium log. 

https://gist.github.com/Ankur008/9747fbc7d24d8671a06b425f9850eb44

**Comment by mykola-mokhnach** [comment] 2016-12-15 07:36
Duplicate of https://github.com/appium/appium/issues/7525

**Closed by mykola-mokhnach** 2016-12-15 07:36 UTC
Labels: NeedsTriage
