### ISSUE TITLE
Recording parallel runs on iOS (Simulator) records only the screen of the first device

### ISSUE THREAD

**Issue by maheshchaudharCoupa** [appium/appium#16988] opened 2022-05-26 11:23 UTC
## The problem
When am running a parallel session with screen recording enabled then appium only records the first device screen.

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.34
* Last Appium version that did not exhibit the issue (if applicable): NA
* Driver version that exhibits the issue (only for Appium2): xcuitest@4.4.1
* Last driver version that did not exhibit the issue (if applicable, only for Appium2): NA
* Desktop OS/version used to run Appium:  MAC OS Monterey, 12.3.1
* Node.js version (unless using Appium.app|exe):
* Package manager name and version (we only officially support NPM): npm
* Mobile platform/version under test: iOS Simulator version: 15.5
* Real device or emulator/simulator: Simlurator
* Appium CLI or Appium.app|exe: Appium cli

## Details
I have followed all required steps as per below doc.
https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md

## Link to Appium logs

https://gist.github.com/maheshchaudharCoupa/0cfa8961199834095be9efe29b0bab2d

**Comment by amedvedjev** [comment] 2022-05-26 12:34
doc a bit wrong. you should provide to iOS different `mjpegServerPort` also. see https://github.com/appium/appium-xcuitest-driver

in your logs port always default = 9100 which means only one first device.

**Comment by mykola-mokhnach** [comment] 2022-05-26 17:26
Duplicate of https://github.com/appium/appium/issues/16554

**Closed by mykola-mokhnach** 2022-05-26 17:26 UTC
