### ISSUE TITLE
Problem with Appium Inspector

### ISSUE THREAD

**Issue by chris3jang** [appium/appium#5284] opened 2015-06-19 22:15 UTC
I apologize in advanced if anything I post involves noob-worthy errors/fixes, I am very new to not only appium but coding in general.  If there is anything I am doing wrong in terms of how I am approaching the community for help, whether it be related to conventional practices, or online manners, I'd be so grateful to be educated on what I am doing wrong or how I can do it better.  

I have Appium installed hopefully correctly, according to the online tutorial.  The only aspect of my installation that may be causing the issue I am experiencing is that at the end of the process after running reset.sh, I failed to authorize with the command 

sudo ‘which grunt’; authorize 

because when I did I got 

sudo: which grunt: command not found
-bash: authorize: command not found 

and was advised to move on from it.  Still, Appium Doctor checks out fine.  

I give the iOS settings only three things, the App Path to the .app file which I built through Xcode Archive and extracted from its Package contents onto my desktop (with the App Path box checked), the device which I have set to iPhone 5 (with the Force Device box checked), and Platform Version which I have set to 7.1.  I change nothing else. 

When I launch, it seems to be working without issue.  When I click Appium Inspector I get issues.

Here's the log:

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --debug-log-spacing --platform-version "7.1" --platform-name "iOS" --app "/Users/chrisjang/Desktop/StarMaker.app" --device-name "iPhone 5"

info: Welcome to Appium v1.4.1 (REV ce6220829063679bcccf5724515c29569c4a16d9)

info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"app":"/Users/chrisjang/Desktop/StarMaker.app","deviceName":"iPhone 5","platformName":"iOS","platformVersion":"7.1","defaultCommandTimeout":7200,"debugLogSpacing":true}
info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: <-- GET /wd/hub/status 200 8.900 ms - 104 {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: <-- GET /wd/hub/status 200 4.165 ms - 104 {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}
info: <-- GET /wd/hub/status 200 0.996 ms - 104 {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}
info: --> GET /wd/hub/sessions {}
info: [debug] Responding to client with success: {"status":0,"value":[]}
info: <-- GET /wd/hub/sessions 200 0.955 ms - 23 {"status":0,"value":[]}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"7.1","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPhone 5"}}
info: Client User-Agent string: Appium (unknown version) CFNetwork/720.3.13 Darwin/14.3.0 (x86_64)
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: [debug] Using local app from command line: /Users/chrisjang/Desktop/StarMaker.app
info: [debug] Creating new appium session 21260728-33e2-45fe-a09e-fa68e8f246cb

info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version

info: [debug] Xcode version set to 6.3.2

info: [debug] Setting iOS SDK Version
info: [debug] iOS SDK Version set to 8.3
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.3.2","iOSSDKVersion":"8.3","deviceName":"iPhone 5","platformVersion":"7.1"}

info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 5 (7.1 Simulator)'
info: [debug] iOS sim UDID is 4916BB67-BEA2-4756-A841-3DC4E08CFEB9
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim

info: [debug] Could not parse plist file (as binary) at /Users/chrisjang/Desktop/StarMaker.app/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Users/chrisjang/Desktop/StarMaker.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/chrisjang/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/chrisjang/Library/Application Support/appium/bootstrap/bootstrap-4e580d338a12229a.js
info: [debug] Reusing dynamic bootstrap: /Users/chrisjang/Library/Application Support/appium/bootstrap/bootstrap-4e580d338a12229a.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.3.2","iOSSDKVersion":"8.3","deviceName":"iPhone 5","platformVersion":"7.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 5 (7.1 Simulator)'

info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.3.2","iOSSDKVersion":"8.3","deviceName":"iPhone 5","platformVersion":"7.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 5 (7.1 Simulator)'
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Wrote new app Info.plist with device type
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator

info: [debug] Cleaning sim data files
info: Executing: xcrun simctl erase 4916BB67-BEA2-4756-A841-3DC4E08CFEB9 with timeout 2000

info: [debug] Cleaning app data files

warn: Applications directory /Users/chrisjang/Library/Developer/CoreSimulator/Devices/4916BB67-BEA2-4756-A841-3DC4E08CFEB9/data/Applications doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Not setting locale

info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS 8.* simulator log capture

info: [debug] Not pre-launching simulator
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on iPhone 5 (7.1 Simulator)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 5 (7.1 Simulator)" /Users/chrisjang/Desktop/StarMaker.app -e UIASCRIPT "/Users/chrisjang/Library/Application Support/appium/bootstrap/bootstrap-4e580d338a12229a.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6/InstrumentsShim.dylib","LIB_PATH":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6"}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST] Waiting for device to boot...

This opens the simulator, but the app fails to launch.  I get a yellow exclamation window with the message: Exception encountered connecting to CoreSimulatorBridge: connection went invalid while waiting for a reply.  When I exit the inspector function, I get an error window with the Appium icon titled "Could Not Launch Appium Inspector" with the message "Could not start a new session...Be sure the Appium server is running with an application opened by using the "App Path" parameter in Appium.app (along with package and activity for Android) or by connecting with selenium client and supplying this in the desired capabilities object."

Unfortunately these settings are not the only parameters I need working, I changed the device to iPhone 6 and version to 8.1.

Here's the log for this change:

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --debug-log-spacing --platform-version "8.1" --platform-name "iOS" --app "/Users/chrisjang/Desktop/StarMaker.app" --device-name "iPhone 6"

info: Welcome to Appium v1.4.1 (REV ce6220829063679bcccf5724515c29569c4a16d9)

info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"app":"/Users/chrisjang/Desktop/StarMaker.app","deviceName":"iPhone 6","platformName":"iOS","platformVersion":"8.1","defaultCommandTimeout":7200,"debugLogSpacing":true}
info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: <-- GET /wd/hub/status 200 9.757 ms - 104 {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}
info: <-- GET /wd/hub/status 200 3.706 ms - 104 {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}
info: --> GET /wd/hub/sessions {}
info: [debug] Responding to client with success: {"status":0,"value":[]}
info: <-- GET /wd/hub/sessions 200 1.060 ms - 23 {"status":0,"value":[]}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"8.1","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPhone 6"}}

info: Client User-Agent string: Appium (unknown version) CFNetwork/720.3.13 Darwin/14.3.0 (x86_64)
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: [debug] Using local app from command line: /Users/chrisjang/Desktop/StarMaker.app
info: [debug] Creating new appium session 48a06fe4-225c-49d1-95c2-939cdaffb614
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version

info: [debug] Xcode version set to 6.3.2

info: [debug] Setting iOS SDK Version

info: [debug] iOS SDK Version set to 8.3
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.3.2","iOSSDKVersion":"8.3","deviceName":"iPhone 6","platformVersion":"8.1"}

info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
info: [debug] iOS sim UDID is 2E127FC0-3EA1-46F6-B51E-0043CDA9CC7B
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim

info: [debug] Could not parse plist file (as binary) at /Users/chrisjang/Desktop/StarMaker.app/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Users/chrisjang/Desktop/StarMaker.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/chrisjang/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}

info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/chrisjang/Library/Application Support/appium/bootstrap/bootstrap-4e580d338a12229a.js
info: [debug] Reusing dynamic bootstrap: /Users/chrisjang/Library/Application Support/appium/bootstrap/bootstrap-4e580d338a12229a.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.3.2","iOSSDKVersion":"8.3","deviceName":"iPhone 6","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.3.2","iOSSDKVersion":"8.3","deviceName":"iPhone 6","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Wrote new app Info.plist with device type
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator

info: [debug] Cleaning sim data files

info: Executing: xcrun simctl erase 2E127FC0-3EA1-46F6-B51E-0043CDA9CC7B with timeout 2000

info: [debug] Cleaning app data files

warn: Applications directory /Users/chrisjang/Library/Developer/CoreSimulator/Devices/2E127FC0-3EA1-46F6-B51E-0043CDA9CC7B/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
warn: Applications directory /Users/chrisjang/Library/Developer/CoreSimulator/Devices/2E127FC0-3EA1-46F6-B51E-0043CDA9CC7B/data/Containers/Bundle/Application doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Not setting locale
info: [debug] No iOS / app preferences to set

info: [debug] Starting iOS 8.* simulator log capture

info: [debug] Not pre-launching simulator
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on iPhone 6 (8.1 Simulator)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 6 (8.1 Simulator)" /Users/chrisjang/Desktop/StarMaker.app -e UIASCRIPT "/Users/chrisjang/Library/Application Support/appium/bootstrap/bootstrap-4e580d338a12229a.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6/InstrumentsShim.dylib","LIB_PATH":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6"}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST] Waiting for device to boot...

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"},"isShuttingDown":false},"sessionId":"48a06fe4-225c-49d1-95c2-939cdaffb614"}
info: <-- GET /wd/hub/status 200 1.342 ms - 178 {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"},"isShuttingDown":false},"sessionId":"48a06fe4-225c-49d1-95c2-939cdaffb614"}

info: [debug] [INST STDERR] Instruments Trace Error : Target failed to run: Failed looking up pid of launched process

info: [debug] [INSTSERVER] Instruments exited with code 253

info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iOS Simulator

In this case, the simulator opens, and the app again fails to run, but instead of an error window I get sent into a loop in which the simulator tries to open the app but fails after 1-2 seconds before it tries again.  I need to stop the inspector function, and I get the same window titled "Could Not Launch Appium Inspector".  

These all seem to be relatively generic errors, but again I am very new to this and have bad trouble shooting skills.  I have copypasted the numerous warning and error messages I have gotten from this process (some that I didn't even post here) into google, and the issues and fixes discussed that I was able to find had little to do with my situation.  Any sort of assistance, advice, or suggestions for a beginner is beyond appreciated and not taken for granted, just trying to learn as much as I can.  

I am all ears, thank you all in advanced.

**Comment by moizjv** [comment] 2015-06-19 22:34
looks like dot-app thing. We have [dot-app](https://github.com/appium/appium-dot-app) project which handles gui aspect of appium. Are you sure you followed all the instruction in that project? You can also ask at [forum](http://discuss.appium.io) to ask questions.

**Comment by chris3jang** [comment] 2015-06-19 22:59
@moizjv 

Thank you for the quick reply!  I did indeed, copypaste this issue into the forum you linked me to, under issues.  

Forgive me for my ignorance, I am not entirely sure what you mean by "looks like dot-app thing".  I just clicked on the link and can't seem to find a set of instructions aside from the 3 steps in the readme file (download the latest version, mount the disc image, drag into apps folder) which I have obviously done, so I'm still confused if there is a set of instructions "in that project" that you're referring to.  But if there is, I would be grateful to know where these instructions are, because I definitely did not complete a set of instructions for Appium GUI specifically, I only completed the installation set up instructions under Install Ruby at http://appium.io/slate/en/tutorial/ios.html?java#install-ruby.  Again, these instructions were enough to get me through the AppiumDoctor checklist.  I will now go read up on Appium GUI and GUIs in general, to maybe figure out what the difference is.  Thank you for your help @moizjv.

**Comment by chris3jang** [comment] 2015-06-19 23:06
@moizjv 
if appium GUI refers to the appium application( with a launch button, buttons for ios and android settings with their respective icons, a magnifying glass button for inspector, and a stethoscope button for appiumdoctor, then i do indeed have this installed) versus accessing appium through say terminal (sorry if this sounds dumb, i'm not even sure if this is possible) then I do indeed have the application installed, if there is a set of steps that differ from either the 3 steps on the readme page of where your dot-app link sends me, or from the set of steps that I link to in my previous comment, let me know where I could find these.  thanks again.

**Comment by moizjv** [comment] 2015-06-19 23:19
@chris3jang so I am confused now. What are you trying to achieve here?

**Comment by chris3jang** [comment] 2015-06-19 23:29
@moizjv 

sorry, I'll try and keep this simpler

i followed installation steps from the tutorial posted on appium.io, appium doctor says I have no problems with setups,  when I launch, the log I get suggests everything works fine.  then I click the inspector button, and get various errors, with specifics I posted above.  I really have no knowledge of how to approach the fixing errors the log gives me, for they seem general and I am new.  you mentioned there is a "dot-app project which handles gui aspect of appium".  I don't believe I followed the specific set of instructions in "that project", nor can I find a set of instructions I haven't tried under the link you sent me.  if these instructions exist, please let me know where specifically.  If I misunderstood your comment and what I am talking about doesn't exist, any advice on how to approach troubleshooting this would be appreciated.  Thank you, endlessly.

**Comment by moizjv** [comment] 2015-06-20 00:06
@chris3jang ok for `sudo ‘which grunt’; authorize` can you install grunt?

**Comment by chris3jang** [comment] 2015-06-20 00:15
@moizjv 
to my understanding grunt is installed, when I run
grunt --version
I get    grunt-cli v0.1.13
however, according to the appium tutorial I mentioned I followed through, when running grunt --version I am also supposed to additionally get    grunt v0.4.2
I tried using google to figure out what it means if only grunt-cli version was given and not just grunt when running --version

with all that being said, sudo 'which grunt'; authorize gives me command not found errors, which was always confusing to me because I know for certain grunt-cli is installed

**Comment by chris3jang** [comment] 2015-06-20 00:29
@moizjv 

update:  

I managed to install grunt through brew (I swear I tried this a while back), but now when I run grunt --version, it gives me both grunt-cli v0.1.13 AND grunt v.0.4.5

still though, when I run sudo 'which grunt'; authorize, I get:

sudo: which grunt: command not found
-bash: authorize: command not found

**Comment by moizjv** [comment] 2015-06-20 00:29
@chris3jang what happens if you try to launch and run app using gui?

**Comment by chris3jang** [comment] 2015-06-20 00:35
@moizjv  

I encountered all of these issues running Appium through GUI, I did not use terminal to run the application, only to follow installation steps

**Comment by moizjv** [comment] 2015-06-20 00:56
@chris3jang are you able to launch `StarMaker.app` without appium?

**Comment by chris3jang** [comment] 2015-06-20 01:13
@moizjv  yes I am able to

**Comment by moizjv** [comment] 2015-06-20 05:20
ping @bootstraponline

**Comment by bootstraponline** [comment] 2015-06-20 13:41
I think this is a user error situation and not a bug in appium. discuss.appium.io is the proper place for help.

**Comment by moizjv** [comment] 2015-06-20 21:07
@chris3jang this is not defect in appium. I will try to support you on forum. Closing issue here.

**Closed by moizjv** 2015-06-20 21:07 UTC
Labels: GUI, iOS, OnGoing, Question

**Comment by chris3jang** [comment] 2015-06-22 17:23
@moizjv 

Sorry I went blank for the weekend.  I made basically the same post here:
https://discuss.appium.io/t/problem-with-appium-inspector/4843

Let me know if this is in the wrong place.
