### ISSUE TITLE
Infinite loop and cannot get the screenshot running on real iOS device

### ISSUE THREAD

**Issue by billylamch** [appium/appium#15395] opened 2021-05-20 04:25 UTC
The application is successfully installed in my iOS 14.5 device but the appium cannot generate screenshot and occur a infinite loop.
<img width="1079" alt="error1" src="https://user-images.githubusercontent.com/30723312/118918993-45930d80-b966-11eb-8efb-96c6ce951e41.png">

The error log begins here:
roxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/E374C39B-A48C-4FF7-B780-8B90B44AA240/screenshot] with no body
[WD Proxy] Got response with status 500: {"value":{"error":"unknown error","message":"-[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x2815246c0","traceback":"(\n\t0   CoreFoundation                      0x00000001a8c025c8 58500388-BF36-397C-84CF-17315A3445B6 + 1217992\n\t1   libobjc.A.dylib                     0x00000001bd6817a8 objc_exception_throw + 60\n\t2   CoreFoundation                      0x00000001a8b05a9c 58500388-BF36-397C-84CF-17315A3445B6 + 182940\n\t3   CoreFoundation                      0x00000001a8c0510c 58500388-BF36-397C-84CF-17315A3445B6 + 1229068\n\t4   CoreFoundation                      0x00000001a8c076b0 _CF_forwarding_prep_0 + 96\n\t5   WebDriverAgentLib                   0x0000000109d9393c -[XCUIDevice(FBHelpers) fb_rawScreenshotWithQuality:error:] + 156\n\t6   WebDriverAgentLib                   0x0000000109d93808 -[XCUIDevice(FBHelpers) fb_screenshotWithError:] + 88\n\t7   WebDriverAgentLib                   0x0000000109d33350 +[FBScreenshotCommands handleGetScreenshot:] + 1...
[W3C] Matched W3C error code 'unknown error' to UnknownError
[XCUITest] Error getting screenshot: An unknown server-side error occurred while processing the command. Original error: -[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x2815246c0
[XCUITest] Taking screenshot with WDA
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/E374C39B-A48C-4FF7-B780-8B90B44AA240/screenshot] with no body
[WD Proxy] Got response with status 500: {"value":{"error":"unknown error","message":"-[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x281536280","traceback":"(\n\t0   CoreFoundation                      0x00000001a8c025c8 58500388-BF36-397C-84CF-17315A3445B6 + 1217992\n\t1   libobjc.A.dylib                     0x00000001bd6817a8 objc_exception_throw + 60\n\t2   CoreFoundation                      0x00000001a8b05a9c 58500388-BF36-397C-84CF-17315A3445B6 + 182940\n\t3   CoreFoundation                      0x00000001a8c0510c 58500388-BF36-397C-84CF-17315A3445B6 + 1229068\n\t4   CoreFoundation                      0x00000001a8c076b0 _CF_forwarding_prep_0 + 96\n\t5   WebDriverAgentLib                   0x0000000109d9393c -[XCUIDevice(FBHelpers) fb_rawScreenshotWithQuality:error:] + 156\n\t6   WebDriverAgentLib                   0x0000000109d93808 -[XCUIDevice(FBHelpers) fb_screenshotWithError:] + 88\n\t7   WebDriverAgentLib                   0x0000000109d33350 +[FBScreenshotCommands handleGetScreenshot:] + 1...
[W3C] Matched W3C error code 'unknown error' to UnknownError
[XCUITest] Taking screenshot with WDA
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/E374C39B-A48C-4FF7-B780-8B90B44AA240/screenshot] with no body
[WD Proxy] Got response with status 500: {"value":{"error":"unknown error","message":"-[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x2815253c0","traceback":"(\n\t0   CoreFoundation                      0x00000001a8c025c8 58500388-BF36-397C-84CF-17315A3445B6 + 1217992\n\t1   libobjc.A.dylib                     0x00000001bd6817a8 objc_exception_throw + 60\n\t2   CoreFoundation                      0x00000001a8b05a9c 58500388-BF36-397C-84CF-17315A3445B6 + 182940\n\t3   CoreFoundation                      0x00000001a8c0510c 58500388-BF36-397C-84CF-17315A3445B6 + 1229068\n\t4   CoreFoundation                      0x00000001a8c076b0 _CF_forwarding_prep_0 + 96\n\t5   WebDriverAgentLib                   0x0000000109d9393c -[XCUIDevice(FBHelpers) fb_rawScreenshotWithQuality:error:] + 156\n\t6   WebDriverAgentLib                   0x0000000109d93808 -[XCUIDevice(FBHelpers) fb_screenshotWithError:] + 88\n\t7   WebDriverAgentLib                   0x0000000109d33350 +[FBScreenshotCommands handleGetScreenshot:] + 1...
[W3C] Matched W3C error code 'unknown error' to UnknownError
[MJSONWP (aeb63721)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x2815253c0
[MJSONWP (aeb63721)]     at errorFromW3CJsonCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
[MJSONWP (aeb63721)]     at ProxyRequestError.getActualError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
[MJSONWP (aeb63721)]     at JWProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:273:19)
[MJSONWP (aeb63721)]     at runMicrotasks ()
[MJSONWP (aeb63721)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[HTTP] <-- GET /wd/hub/session/aeb63721-6810-4049-993c-f667d56a3c0e/screenshot 500 1064 ms - 273
[HTTP]

**Comment by mykola-mokhnach** [comment] 2021-05-20 04:29
Duplicate of https://github.com/appium/appium/issues/15309

**Closed by mykola-mokhnach** 2021-05-20 04:29 UTC

**Comment by billylamch** [comment] 2021-05-20 05:17
But I have tried to run in another iPhone with iOS 12.4.9, it still fails.!

> Duplicate of #15309
