### ISSUE TITLE
updating appium-xcuitest-driver past version 4.21.0 causes npm ci to fail on linux

### ISSUE THREAD

**Issue by BryceLTaylor** [appium/appium#18554] opened 2023-04-20 18:19 UTC
I am not sure why the change from 4.21.0 to 4.21.1 causes this issue. If I run `npm ci` in Github Actions on ubuntu I get this error:

> npm ERR! code EBADPLATFORM
> npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
> npm ERR! notsup Valid OS:    darwin
> npm ERR! notsup Valid Arch:  undefined
> npm ERR! notsup Actual OS:   linux

This does not happen when using version 4.21.0 of appium-xcuitest-driver.

I am using appium version ^2.0.0-beta.65

**Comment by boneskull** [comment] 2023-04-20 19:15
AFAIK, the only way this can happen is if `npm` is running with `strict-engines` enabled.  I can't really diagnose that for you, but you can run `npm config list` in CI and see if it's in there.

There's nothing that changed between v4.21.0 and v4.21.1 that'd cause this.

**Comment by BryceLTaylor** [comment] 2023-04-21 13:34
I agree that there's nothing in that change that should cause this, but that is the dividing line.  in 4.21.0 and before I don't have this problem and in 4.21.1 and onward I do.  

I ran npm config list (and with the -l) and I didn't see anything set one way or another for `strict-engines`.

**Comment by jlipps** [comment] 2023-04-21 20:45
@BryceLTaylor where are you running `npm ci`? Are you saying that you have `appium-xcuitest-driver` as a dependency in your nodejs project?

**Comment by BryceLTaylor** [comment] 2023-04-21 20:53
There is a step in my workflow in github actions to run npm ci.  It is being run on ubuntu.  I do have appium-xcuitest-driver as a dependency in my nodejs project.

**Comment by jdmeer** [comment] 2023-05-12 16:05
Something very similar is happening to me on Windows but it seems to occur between versions 4.21.7 & 4.21.8.
npm: '9.6.6',  
node: '18.16.0',

![image](https://github.com/appium/appium/assets/7095177/d05e1da1-aa39-4e82-8113-0c3fe888f2ac)

**Comment by jdmeer** [comment] 2023-05-12 16:27
I just noticed that the number of packages installed doubled between 4.21.7 & 4.21.8

It went from 909 to 1811 packages added.

**Comment by jlipps** [comment] 2023-05-12 18:11
It is probably due to https://github.com/appium/appium-xcuitest-driver/commit/f0a54e5a3f1e151084d23ae2f1bf2f3ac00f0f99 then. Maybe NPM is installing multiple versions of packages instead of deduping them based on a less strict version policy.

**Comment by boneskull** [comment] 2023-05-18 19:07
`EBADPLATFORM` will only happen if `engines-strict` is true in your npm config.  See [docs](https://docs.npmjs.com/cli/v9/using-npm/config?v=true#engine-strict)

If this configuration out of your control, you can use `npm ci --force` instead.

**Comment by boneskull** [comment] 2023-05-18 19:08
Whatever the problem is, I think it's outside of Appium's control.  closing this

**Closed by boneskull** 2023-05-18 19:08 UTC
Labels: Needs Triage, Node

**Comment by nderevjanik-fond** [comment] 2023-12-01 18:39
@boneskull are there no other solutions to this problem? 

I recently upgraded the driver from 4.x to 5.x and now I'm getting the same issue (within CircleCI).

As you can see in the output below (from CircleCI), `engine-strict` is `false`.

```
; node bin location = /opt/circleci/.nvm/versions/node/v20.10.0/bin/node
; node version = v20.10.0
; npm local prefix = /home/circleci/project
; npm version = 10.2.3
; cwd = /home/circleci/project
; HOME = /home/circleci
; Run `npm config ls -l` to show all defaults.
; "default" config from default values

_auth = (protected) 
access = null 
all = false 
allow-same-version = false 
also = null 
audit = true 
audit-level = null 
auth-type = "web" 
before = null 
bin-links = true 
browser = null 
ca = null 
cache = "/home/circleci/.npm" 
cache-max = null 
cache-min = 0 
cafile = null 
call = "" 
cert = null 
cidr = null 
color = true 
commit-hooks = true 
cpu = null 
depth = null 
description = true 
dev = false 
diff = [] 
diff-dst-prefix = "b/" 
diff-ignore-all-space = false 
diff-name-only = false 
diff-no-prefix = false 
diff-src-prefix = "a/" 
diff-text = false 
diff-unified = 3 
dry-run = false 
editor = "vi" 
engine-strict = false 
fetch-retries = 2 
fetch-retry-factor = 10 
fetch-retry-maxtimeout = 60000 
fetch-retry-mintimeout = 10000 
fetch-timeout = 300000 
force = false 
foreground-scripts = false 
format-package-lock = true 
fund = true 
git = "git" 
git-tag-version = true 
global = false 
global-style = false 
globalconfig = "/opt/circleci/.nvm/versions/node/v20.10.0/etc/npmrc" 
heading = "npm" 
https-proxy = null 
if-present = false 
ignore-scripts = false 
include = [] 
include-staged = false 
include-workspace-root = false 
init-author-email = "" 
init-author-name = "" 
init-author-url = "" 
init-license = "ISC" 
init-module = "/home/circleci/.npm-init.js" 
init-version = "1.0.0" 
init.author.email = "" 
init.author.name = "" 
init.author.url = "" 
init.license = "ISC" 
init.module = "/home/circleci/.npm-init.js" 
init.version = "1.0.0" 
install-links = false 
install-strategy = "hoisted" 
json = false 
key = null 
legacy-bundling = false 
legacy-peer-deps = false 
link = false 
local-address = null 
location = "user" 
lockfile-version = null 
loglevel = "notice" 
logs-dir = null 
logs-max = 10 
; long = false ; overridden by cli
maxsockets = 15 
message = "%s" 
node-options = null 
noproxy = [""] 
npm-version = "10.2.3" 
offline = false 
omit = [] 
omit-lockfile-registry-resolved = false 
only = null 
optional = null 
os = null 
otp = null 
pack-destination = "." 
package = [] 
package-lock = true 
package-lock-only = false 
parseable = false 
prefer-dedupe = false 
prefer-offline = false 
prefer-online = false 
prefix = "/opt/circleci/.nvm/versions/node/v20.10.0" 
preid = "" 
production = null 
progress = false 
provenance = false 
provenance-file = null 
proxy = null 
read-only = false 
rebuild-bundle = true 
registry = "https://registry.npmjs.org/" 
replace-registry-host = "npmjs" 
save = true 
save-bundle = false 
save-dev = false 
save-exact = false 
save-optional = false 
save-peer = false 
save-prefix = "^" 
save-prod = false 
sbom-format = null 
sbom-type = "library" 
scope = "" 
script-shell = null 
searchexclude = "" 
searchlimit = 20 
searchopts = "" 
searchstaleness = 900 
shell = "/bin/bash" 
shrinkwrap = true 
sign-git-commit = false 
sign-git-tag = false 
strict-peer-deps = false 
strict-ssl = true 
tag = "latest" 
tag-version-prefix = "v" 
timing = false 
umask = 0 
unicode = true 
update-notifier = true 
usage = false 
user-agent = "npm/{npm-version} node/{node-version} {platform} {arch} workspaces/{workspaces} {ci}" 
userconfig = "/home/circleci/.npmrc" 
version = false 
versions = false 
viewer = "man" 
which = null 
workspace = [] 
workspaces = null 
workspaces-update = true 
yes = null 

; "cli" config from command line options

long = true
```
