### ISSUE TITLE
Error trying to run test on Safari on iPad Device

### ISSUE THREAD

**Issue by IlyasPatel** [appium/appium#4596] opened 2015-02-24 19:42 UTC
Hi, I'm new to Appium and I'm trying to run tests on Safari iPad device. I have Safari Launcher on the device running but I get this error when trying to runs test - http://pastebin.com/ceD9wsgE

This is the capabilities I am using

capabilities.setCapability("appium-version", "1.3.4");
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("deviceName", "eFC's iPad");
capabilities.setCapability("udid", "removed");
capabilities.setCapability("bundleId", "com.safariLauncher.safariLauncher");
capabilities.setCapability("browserName", "safari");

Here is the log:

info: [debug] Could not parse plist file (as binary) at /var/folders/fv/glww6zh11hx0hthzmg_1ycn00000gp/T/115124-954-1uj39ij/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
`parseFileSync()` is deprecated. Use `parseStringSync()` instead.
info: [debug] Could not parse plist file (as XML) at /var/folders/fv/glww6zh11hx0hthzmg_1ycn00000gp/T/115124-954-1uj39ij/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings; assuming it doesn't exist
info: [debug] Creating instruments
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/efctech/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.10.36/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"grouped"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. D...ot manually modify!
info: [debug] Dynamic bootstrap path: /Users/efctech/Library/Application Support/appium/bootstrap/bootstrap-05c4b2c4f0f8bebf.js
info: [debug] Reusing dynamic bootstrap: /Users/efctech/Library/Application Support/appium/bootstrap/bootstrap-05c4b2c4f0f8bebf.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"eFC's iPad","platformVersion":null}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'eFC's iPad (8.1 Simulator)'
info: [debug] Not setting device type since we're on a real device
info: [debug] Checking whether we need to set app preferences
info: [debug] Not setting iOS and app preferences since we're on a real device
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] On a real device; cannot clean device state
info: [debug] Not setting locale because we're using a real device
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS device log capture via deviceconsole
error: Log capture did not start in a reasonable amount of time
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Log capture did not start in a reasonable amount of time

Any help would be appreciated.

**Comment by GindiKhangura** [comment] 2015-02-24 23:17
Might want to look at https://github.com/appium/appium/issues/4216.

**Comment by sebv** [comment] 2015-06-03 16:22
Try the following:
- drop the `capabilities.setCapability("bundleId", "com.safariLauncher.safariLauncher");`
- increase launchTimeout if running on a slow system.

**Comment by sebv** [comment] 2015-06-10 06:11
Closing, not a bug.

**Closed by sebv** 2015-06-10 06:11 UTC
Labels: iOS, OnGoing
