### ISSUE TITLE
Unable to start WebDriverAgent session with iOS 12.0 Public Beta 3

### ISSUE THREAD

**Issue by dnch-chernov** [appium/appium#11090] opened 2018-07-20 23:28 UTC
## The problem

Appium is unable to establish connection to device with latest iOS 12.0 public beta 3, fails with error: "Original error: Error: read ECONNRESET. Getting status of WebDriverAgent on device timed out".
It worked fine with iOS 12.0 beta 2, but started to fail after iOS update.
I'm using latest Xcode 10 beta 4.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.13.5
* Node.js version (unless using Appium.app|exe): v8.8.1
* Mobile platform/version under test: iOS 12.0 (16A5327f) Public Beta 3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Link to Appium logs

https://gist.github.com/dnch-chernov/ef0d8bcf9f974654b89fd347bd321d08

**Comment by mykola-mokhnach** [comment] 2018-07-21 06:34
Please attach the device log as well

**Comment by mykola-mokhnach** [comment] 2018-07-21 20:02
Are there any crashes of WebDriverAgent process in Crashes tab of Device organiser? 

I can only observe this error so far

```
default 12:07:10.898803 -0700 ReportCrash Process:             testmanagerd [12391]
Path:                /Developer/usr/libexec/testmanagerd
OS Version:          iPhone OS 12.0 (16A5327f)
default 12:07:10.899055 -0700 ReportCrash Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Symbol not found: _UIAccessibilityAutomationEventButtonEventsCompleted | Referenced from: /Developer/usr/libexec/testmanagerd | Expected in: dyld shared cache | in /Developer/usr/libexec/testmanagerd
Triggered by Thread:  0
default 12:07:10.901489 -0700 ReportCrash Thread 0 Crashed:
0   dyld                            0x00000001003403cc 0x1002fc000 + 279500
1   dyld                            0x000000010033fa14 0x1002fc000 + 277012
2   dyld                            0x000000010033fa44 0x1002fc000 + 277060
3   dyld                            0x00000001003009ac 0x1002fc000 + 18860
4   dyld                            0x00000001003039a8 0x1002fc000 + 31144
5   dyld                            0x00000001002fd044 0x1002fc000 + 4164
default 12:07:10.901783 -0700 ReportCrash Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000004   x2: 0x000000016fd4aba0   x3: 0x000000000000007f
    x4: 0x000000016fd4a7a0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x000000016fd4af70
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x65786562696c2f72  x11: 0x616d747365742f63
   x12: 0x752f7265706f6c65  x13: 0x786562696c2f7273  x14: 0x6d747365742f6365  x15: 0x0064726567616e61
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016fd4a7a0  x21: 0x000000000000007f  x22: 0x000000016fd4aba0  x23: 0x0000000000000004
   x24: 0x0000000000000006  x25: 0x0000000100363000  x26: 0x0000000100363000  x27: 0x0000000100363000
   x28: 0x00000000000b4000   fp: 0x000000016fd4a770   lr: 0x000000010033fa14
    sp: 0x000000016fd4a730   pc: 0x00000001003403cc cpsr: 0x00000000
```

But it happens somewhere inside the internal lib.

**Comment by dcnt** [comment] 2018-07-21 20:51
16A5327f is beta 4
We observe the same issue after updating to beta 4.

**Comment by mykola-mokhnach** [comment] 2018-07-22 11:09
@dcnt This has been already mentioned above. Are there any symbolicated crash reports. Otherwise one cannot retrieve any useful info from this report.

**Comment by dnch-chernov** [comment] 2018-07-22 19:02
@mykola-mokhnach No, there are no WebDriverAgent crashes.

**Comment by mykola-mokhnach** [comment] 2018-07-22 19:07
Then it is most likely an internal beta issue. I would try to report it to Apple and to https://github.com/facebook/WebDriverAgent Most likely we won't be able to do much on Appium side.

**Comment by dnch-chernov** [comment] 2018-07-22 19:32
@mykola-mokhnach Thanks! Will try with next beta as soon as it become available and post results here.

**Comment by dcnt** [comment] 2018-07-23 07:49
@mykola-mokhnach i just wanted to point out  that title of the issue is a bit incorrect
If I can help with any logs, please let me know

**Comment by mykola-mokhnach** [comment] 2018-07-23 15:20
Closing this as duplicate of https://github.com/facebook/WebDriverAgent/issues/968

We anyway must wait until the fix is present in the main repository.

**Closed by mykola-mokhnach** 2018-07-23 15:20 UTC
Labels: ThirdParty, XCUITest
