### ISSUE TITLE
Appium 1.6.4 Beta - Failed to create WDA session - Socket hang up

### ISSUE THREAD

**Issue by hqhung0809** [appium/appium#7899] opened 2017-02-21 06:41 UTC
## The problem

Failed to create WDA session - socket hang up when I tried to launch mobile app by cmd

## Environment

* Appium version 1.6.4 beta
* Desktop OS/version used to run Appium: OS X Elcapitan version 10.11.6
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: iOS version 10.0
* Real device or emulator/simulator: iphone 5s (real device)
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Launch app by cml, Failed to create WDA session.

## Link to Appium logs

[debug] [XCUITest] iproxy exited with code 'null'
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGINT'
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Failed to create WDA session. Retrying...

**Comment by mykola-mokhnach** [comment] 2017-02-21 07:45
Might be a duplicate of https://github.com/appium/appium/issues/7192
Quick solution: use 64-bit device to run automated tests.

**Comment by hqhung0809** [comment] 2017-02-21 08:08
your mean 64 bit mobile or computer device?

**Comment by mykola-mokhnach** [comment] 2017-02-21 08:09
I mean iDevice. Read the linked thread for more details.

**Comment by hqhung0809** [comment] 2017-02-21 08:18
that's mean I have to test on iphone 5s or above ?

**Comment by mykola-mokhnach** [comment] 2017-02-21 08:22
iPhone 6 or newer would be a good match. But check the device log first to make sure you have exactly this problem. I wrote "possible duplicate".

**Comment by hqhung0809** [comment] 2017-02-21 08:24
Could you guide me how to check device log ?

**Comment by mykola-mokhnach** [comment] 2017-02-21 08:27
There is Appium forum for howto type of questions. Here we help to solve issues

**Comment by hqhung0809** [comment] 2017-02-21 08:30
Thank u so much mykola, I will closed this issue.

**Comment by hqhung0809** [comment] 2017-03-06 04:13
Hi mykola-mokhnach
I am using device 64 bit, but this issue still happens on my device, I can't create WDA session right now ?

Could you tell me why ?

**Comment by mykola-mokhnach** [comment] 2017-03-06 07:17
I cannot without seeing the log. Preferably both - from Appium and from the device.

**Comment by hqhung0809** [comment] 2017-03-06 07:37
Hi mykola,
Pls get attachment to see log drom Appium and Web Driver Agent
[Appium_log.txt](https://github.com/appium/appium/files/820402/Appium_log.txt)
[Session-WebDriverAgentRunner-2017-03-06_140838-STUy8z.txt](https://github.com/appium/appium/files/820404/Session-WebDriverAgentRunner-2017-03-06_140838-STUy8z.txt)

**Comment by mykola-mokhnach** [comment] 2017-03-06 08:28
I don't see any problems in the attached logs. BTW, the device log is still missing there

**Comment by hqhung0809** [comment] 2017-03-06 08:33
Could you tell me where I can get device log ?

**Comment by hqhung0809** [comment] 2017-03-06 09:47
Hi mykola,
Pls get attachment to see device log
[device_log.txt](https://github.com/appium/appium/files/820693/device_log.txt)

**Comment by mykola-mokhnach** [comment] 2017-03-06 12:25
```
[iOSLog] [IOS_SYSLOG_ROW] Mar  6 16:43:41 Orchid SpringBoard(FrontBoard)[57] <Info>: [FBSystemService][0x2ac0] Open "UsersQATeamDocumentsZippi.ipa" request from testmanagerd:448 failed with error: <NSError: 0x17584dad0; domain: FBSOpenApplicationServiceErrorDomain; code: 1 (RequestDenied); reason: "The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "UsersQATeamDocumentsZippi.ipa" is unknown to FrontBoard")."> {
[iOSLog] [IOS_SYSLOG_ROW]     description = "The request to open "UsersQATeamDocumentsZippi.ipa" failed.";
[iOSLog] [IOS_SYSLOG_ROW]     failureReason = "The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "UsersQATeamDocumentsZippi.ipa" is unknown to FrontBoard").";
[iOSLog] [IOS_SYSLOG_ROW]     underlyingError = <NSError: 0x17445ec60; domain: FBSOpenApplicationErrorDomain; code: 4 (NotFound); reason: "Application "UsersQATeamDocumentsZippi.ipa" is unknown to FrontBoard."> {
[iOSLog] [IOS_SYSLOG_ROW]         description = "The operation couldn\M-b\M^@\M^Yt be completed. Application "UsersQATeamDocumentsZippi.ipa" is unknown to FrontBoard.";
[iOSLog] [IOS_SYSLOG_ROW]         failureReason = "Application "UsersQATeamDocumentsZippi.ipa" is unknown to FrontBoard.";
[iOSLog] [IOS_SYSLOG_ROW]     };
[iOSLog] [IOS_SYSLOG_ROW] }
[iOSLog] [IOS_SYSLOG_ROW] Mar  6 16:43:41 Orchid SpringBoard(MobileCoreServices)[57] <Notice>: _LSFailedToOpenURL:(null) withBundle:<private>
```

Seems like you provide some incorrect capabilities. The server itself works as expected.

Please switch to Appium forum for howto question. Here we only handle issues.

**Closed by mykola-mokhnach** 2017-03-06 12:25 UTC
Labels: NeedsTriage

**Comment by qiyan12366** [comment] 2017-04-26 08:08
@hqhung0809 hi  , where can i find the log of Web Driver Agent? i can only find the log of appium, but i don't know where to find the log of Web Driver Agent
