### ISSUE TITLE
iOS react-navigation v5 issue

### ISSUE THREAD

**Issue by nickmccomb** [appium/appium#13940] opened 2020-02-14 06:10 UTC
## The problem

Appium is not navigating on iOS.  We are using react-navigation v5.   Appium presses the button, which Appium says is successful, although the app does not navigate to the next screen (it does when manually testing, so the navigation is hooked up and working correctly). Appium navigates correctly on Android, just not iOS.  I'm hoping someone else has had this issue and has found a way to solve it.  

## Environment
Node: v13.7.0
React Native: 0.61.5
appiumVersion: '1.16.0' (tried many previous versions too)

## Link to Appium logs

https://gist.github.com/nickmccomb/aea239307a2e6b2f372e1a76b1961891

## Code To Reproduce Issue [ Good To Have ]

```
    <Button
        accessibilityLabel={'submit button'}
        accessible={true}
        onSubmitEditing={() => submit()}
        title="Submit"
        onPress={() => navigation.navigate(Texts.screens.Home)}
    />
```

**Comment by mykola-mokhnach** [comment] 2020-02-14 06:34
Possible duplicate of https://github.com/appium/appium/issues/13907

**Comment by mykola-mokhnach** [comment] 2020-02-19 06:48
As a workaround one could also try to tap by coordinates. It might be that not the whole element's area is responsive to touches, so the actual hit point, which xctest calculates for the element is not a valid one.

**Comment by imurchie** [comment] 2020-02-24 18:47
@nickmccomb Please try the latest Appium beta. There has been a fix for text input which might affect the functionality here.

**Comment by mykola-mokhnach** [comment] 2020-02-27 12:12
Closed because of no response

**Closed by mykola-mokhnach** 2020-02-27 12:12 UTC
Labels: NeedsInfo, ThirdParty, XCUITest

**Comment by kirillzyusko** [comment] 2020-04-24 21:40
@nickmccomb Hi! Did you find a solution?

**Comment by phillipkey** [comment] 2020-10-20 16:33
This issue should be repoened. It is still reproducible as of 10/20 on the latest release of appium
