### ISSUE TITLE
Lost mouse support after 1.19.2-rc.1 for WinAppDriver

### ISSUE THREAD

**Issue by Wolfe1** [appium/appium#15159] opened 2021-03-03 19:56 UTC
## The problem

After Appium version 1.19.2-rc.1 Winappdriver loses support to click and move the mouse:
`{"status":104,"value":{"error":"unsupported operation","message":"Currently only pen and touch pointer input source types are supported"}}`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.0-rc.1+
* Last Appium version that did not exhibit the issue (if applicable): 1.19.2-rc.1
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe): v14.15.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Windows
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Currently testing this in robotframework, prior to 1.20.0 actions controlling the mouse would work just fine. 

After updating to 1.20.0-rc.1 and beyond an error is received saying that only pen and touch pointer options are available.

## Link to Appium logs

https://gist.github.com/Wolfe1/c38cd45b69151d2c272c54851b9be1cf

## Code To Reproduce Issue [ Good To Have ]

1. Have the latest winappdriver installed: https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.1
2. `pip install robotframework-zoomba`
3. Run this sample test: https://github.com/Accruent/robotframework-zoomba/blob/appium_issue/samples/Appium-DesktopTests-example.robot
   a. `robot path/to/test/Appium-DesktopTests-example.robot`
   
![image](https://user-images.githubusercontent.com/3010366/109864150-194dd780-7c28-11eb-806c-dfd75a289a87.png)

**Comment by mykola-mokhnach** [comment] 2021-03-03 19:59
Duplicate of https://github.com/appium/python-client/issues/592

**Closed by mykola-mokhnach** 2021-03-03 19:59 UTC

**Comment by bwomsm1** [comment] 2022-10-19 06:51
Dear @mykola-mokhnach @jlipps, 
Guys, we need your help with that issue, 
It seems that `WinAppDriver` team needs to do some adaptations for using `w3c`. 
Automation developers around the world all suffering from the same issue, I was trying to talk to their devs but nothing really came out of it. 

Please advise. 

Thanks, 
Boaz
Israel.
