### ISSUE TITLE
Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up

### ISSUE THREAD

**Issue by arvinds97** [appium/appium#14645] opened 2020-08-12 07:28 UTC
## The problem

It was working peacfully and all of a sudden I get this error ? What is wrong?! It runs once and the next time you run, it says unknown server error ?

## Environment

* Appium version (or git revision) that exhibits the issue:
Appium : 1.18
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
Windows 10
* Node.js version (unless using Appium.app|exe):
Appium Desktop App
* Npm or Yarn package manager:
* Mobile platform/version under test:
Android 8.1.0
* Real device or emulator/simulator:
Real Device
* Appium CLI or Appium.app|exe:
Appium desktop app

## Details
I have tried everything.. updating sdk manager.. rebooting the device.. restarting appium...starting all over again.. everything ends up in the same pickle !
## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

https://gist.github.com/arvinds97/ff046e348352270fca5ff9723d3476fa

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.
package appiumtests;

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.By;
import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;

public class ChromeTest {

	
	static AppiumDriver driver;
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
			OpenChrome();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			System.out.println(e.getCause());
			System.out.println(e.getMessage());
			e.printStackTrace();
		}

	}
	
	public static void OpenChrome() throws MalformedURLException {
		DesiredCapabilities cap = new DesiredCapabilities();
		
		
		cap.setCapability("deviceName", "------");
		cap.setCapability("udid", "5203432ff4307383");
		cap.setCapability("platformName", "Android");
		cap.setCapability("platformVersion", "8.1.0");
		cap.setCapability("appPackage", "com.sec.android.app.popupcalculator");
		cap.setCapability("appActivity", "com.sec.android.app.popupcalculator.Calculator");
		
		URL url = new URL("http://127.0.0.1:4723/wd/hub");
		
		driver = new AppiumDriver<MobileElement>(url, cap);
		
		System.out.println("Application Started....");
	
		
	}

**Comment by arvinds97** [comment] 2020-08-12 13:37
Logcat for approximate timeframe : https://gist.github.com/arvinds97/7bd03cc2dc99a59a23ab8feeb90a5549

**Comment by mykola-mokhnach** [comment] 2020-08-12 13:42
Unfortunately I don't observe any issues in the attached log. It looks like the session creation happens later

**Comment by arvinds97** [comment] 2020-08-12 13:48
Sorry about that, let me try it again ...

**Comment by arvinds97** [comment] 2020-08-12 13:52
HI @mykola-mokhnach !, Please find the updated log :)

**Comment by arvinds97** [comment] 2020-08-12 13:52
https://gist.github.com/arvinds97/7bd03cc2dc99a59a23ab8feeb90a5549

**Comment by mykola-mokhnach** [comment] 2020-08-12 16:27
still nothing.

**Comment by KazuCocoa** [comment] 2020-08-13 03:02
I heard similar issue by a friend of mine. I haven't met this though.

I wondered like below link then since when the socket hang happened, no request in uia2 server.
Even after the socket hang message, following requests to the uia2 server worked. The uia2 server on the device under test actually worked...
https://stackoverflow.com/questions/53340878/econnreset-in-express-js-node-js-with-multiple-requests

It could happen 1 of 500 times requests according to the friend.
(Then, client-side retry helped. It meant when a client sent the same request after the socket error, it worked)

I wondered node version might affect, not no good idea...

**Comment by mykola-mokhnach** [comment] 2020-08-17 07:38
I'm closing this issue, since the provided info has no details which could be helpful in finding the cause of it. Feel free to provide more info, so we could continue the triage.

**Closed by mykola-mokhnach** 2020-08-17 07:38 UTC
Labels: NeedsInfo, UIAutomator2
