### ISSUE TITLE
Cannot swipe in IOS overlay screen. No problems in other screens and in Android

### ISSUE THREAD

**Issue by gkvappium** [appium/appium#11194] opened 2018-08-16 14:10 UTC
## The problem

There is an image in the home screen. When tapped , it opens an overlay screen. There is a pager implemented wherein we can swipe between pages. On IOS swipe doesn't work. Appium doesn't throw any error, but swipe doesn't work. The same swipe method works in other screens and also on android. I've tried multiple ways of swiping. None work in the overlay screen on IOS

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2@beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:IOS 11.4 iphone6
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/gkvappium/18b0b41b3ed9b36fd4764cc61438d09d 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

I've pasted below couple of functions that I use which works across different screens but not on IOS overlay screen.

        async genericPointToPointMovement(startx:Number, starty:Number, endx:Number, endy:Number) {  
        let action = new (<any>(this._driver.wd())).TouchAction(this._driver.driver);
            action.press({x: startx, y: starty})
                  .moveTo({x: endx, y: endy})
                  .release();
            await action.perform();
    }

    async swipeLeft() {
        let size = await this._driver.driver.getWindowSize();
        let x = size.width;
        let y = size.height * 0.8;
        if (this._driver.isAndroid) {
            await this._driver.swipe(y, x - 200, y, 1000, 20);
        }
        else {
            await this._driver.driver.execute('mobile: swipe', {direction: 'left'});
        }
    }

@mykola-mokhnach , can you kindly have a look into this issue?

**Comment by robin-xl** [comment] 2018-08-16 16:51
you can try this, to add wait time after call `.press()` before `.moveTo`,  E.g:`.wait(200ms)`

**Comment by mykola-mokhnach** [comment] 2018-08-16 19:09
Closed as duplicate of https://github.com/appium/appium/issues/11181

**Closed by mykola-mokhnach** 2018-08-16 19:09 UTC

**Comment by gkvappium** [comment] 2018-08-17 06:37
Thanks @robin-xl  @mykola-mokhnach ,

wait betweeen press and move seems to resolve the problem. Thanks a ton.

Cheers
