### ISSUE TITLE
Appium fails to start a session on Apple Silicone iOS Simulator 14.4

### ISSUE THREAD

**Issue by tuobraun** [appium/appium#15085] opened 2021-02-06 12:53 UTC
## The problem

When I start an Inspector session for iOS Simulator 14.4 on Apple Silicone (MacOS 11.2) Appium fails to start.

## Environment

* Appium version: 1.19.1, 1.20.0
* Carthage version: 0.37.0
* Desktop OS/version: Apple Silicone MacOS 11.2
* Node.js version: 15.8.0
* Mobile platform/version under test: iOS 14.4
* Real device or emulator/simulator: Simulator

## Link to full Appium logs:
https://gist.github.com/tuobraun/2c406c0940fc2283899cdebca69594d5

Errors from the log:
```
[Xcode] 2021-02-05 18:42:48.640 xcodebuild[2846:139279] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphonesimulator14.4-x86_64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/tuobraun/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/WebDriverAgentRunner_iphonesimulator14.4-x86_64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7f8fdb4a7850 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

[Xcode] Testing failed:
[Xcode] 	Building for iOS Simulator, but the linked and embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator.
[Xcode] 	Building for iOS Simulator, but the linked and embedded framework 'YYCache.framework' was built for iOS + iOS Simulator.
[Xcode] 	Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator.
[Xcode] 	Building for iOS Simulator, but the embedded framework 'YYCache.framework' was built for iOS + iOS Simulator.
[Xcode] 	WebDriverAgentRunner:
[Xcode] 		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/tuobraun/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2021.02.05_18-42-47-+0400.xcresult. (Underlying Error: Cannot launch simulated executable: no file found at /Users/tuobraun/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app))
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode]
[Xcode] Testing started
[Xcode] 
[WebDriverAgent] xcodebuild exited with code '65' and signal 'null'
```

**Comment by mykola-mokhnach** [comment] 2021-02-06 13:13
Duplicate of https://github.com/appium/appium/issues/15084. Make sure you use the most recent server version and there are no leftovers from previous installs

**Closed by mykola-mokhnach** 2021-02-06 13:13 UTC
