### ISSUE TITLE
Unable to build WDA for iOS 14

### ISSUE THREAD

**Issue by SDLarmo** [appium/appium#14736] opened 2020-09-16 17:54 UTC
## The problem

Hi. I'm unable to build WDA with iOS 14/Xcode 12 beta 6:
`./Scripts/bootstrap.sh -d`
Tried this localy and in azure devops pipeline - both ways don't work.

## Result:
https://gist.github.com/SDLarmo/3945719ddb09d84494bfeb5b95a10d2a
## Log:
https://gist.github.com/SDLarmo/cf95f5f59a12222489278f12fd9e10f2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.1
* Desktop OS/version used to run Appium: MacOS 10.15 Catalina
* Node.js version (unless using Appium.app|exe): v10.18.1
* Npm or Yarn package manager: npm 6.13.4
* Mobile platform/version under test: iOS 14
* Real device or emulator/simulator: Emulator

## Details
I've checked https://github.com/appium/appium/issues/14696 and my CocoaAsyncSocket is up to date.

**Comment by mykola-mokhnach** [comment] 2020-09-16 19:00
Duplicate of https://github.com/appium/appium/issues/14611

**Closed by mykola-mokhnach** 2020-09-16 19:00 UTC
