### ISSUE TITLE
Xcode WDA build failed with code 70 error in appium -Failed to create session. An unknown server-side error occurred while processing the command.

### ISSUE THREAD

**Issue by Annjames1** [appium/appium#17539] opened 2022-09-30 10:44 UTC
I am facing an issue with my AppleTV - TVOS 15.6 test automation set up and configuration. I am able to launch my apps manually, but not working when i’m executing via Appium inspector as well as appium script. Getting error as xcode build failure 70.
The proper set up has been followed for the configuration, but seems like some issues with the WebDriver agent or Appium - Appium project is able to build successfully.

Version Details as follows:-
Xcode 14 , Mac OS- 12.5, Appium 1.22.3 .

Error ScreenShot-
<img width="379" alt="Xcode" src="https://user-images.githubusercontent.com/94349457/193252884-d122877b-f4f6-47d3-b342-c1e1a60a049d.png">

Appium server logs

`UITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
[XCUITest] xcodebuild error message:
[XCUITest] . Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest] Quitting and uninstalling WebDriverAgent
[WebDriverAgent] Shutting down sub-processes
[WD Proxy] Error: timeout of 1000ms exceeded
[WD Proxy]     at createError (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/axios/lib/core/createError.js:16:15)
[WD Proxy]     at RedirectableRequest.handleRequestTimeout (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/axios/lib/adapters/http.js:280:16)
[WD Proxy]     at RedirectableRequest.emit (events.js:310:20)
[WD Proxy]     at Timeout._onTimeout (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/follow-redirects/index.js:166:12)
[WD Proxy]     at listOnTimeout (internal/timers.js:549:17)
[WD Proxy]     at processTimers (internal/timers.js:492:7)
[iProxy@d1efeb90:8100] Unexpected data: {"header":{"length":294,"version":1,"type":8,"tag":1},"payload":{"MessageType":"Result","Number":2}}
[iProxy@d1efeb90:8100] Unexpected data: {"header":{"length":294,"version":1,"type":8,"tag":1},"payload":{"MessageType":"Result","Number":2}}
[iProxy@d1efeb90:8100] Unexpected data: {"header":{"length":294,"version":1,"type":8,"tag":1},"payload":{"MessageType":"Result","Number":2}}
[WebDriverAgent] No WDAs on the device.
[XCUITest] {}
[DevCon Factory] Releasing connections for d1efeb90ddf39692b89bd9ec625ca98238d8a5c5 device on any port number
[DevCon Factory] Found cached connections to release: ["d1efeb90ddf39692b89bd9ec625ca98238d8a5c5:8100"]
[DevCon Factory] Releasing the listener for 'd1efeb90ddf39692b89bd9ec625ca98238d8a5c5:8100'
[iProxy@d1efeb90:8100] Closing the connection
[DevCon Factory] Cached connections count: 0
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iProxy@d1efeb90:8100] The connection has been closed
[BaseDriver] Event 'newSessionStarted' logged at 1664532456618 (15:37:36 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
[W3C] xcodebuild error message:
[W3C] . Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[W3C]     at quitAndUninstall (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:585:15)
[W3C]     at /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:620:11
[W3C]     at wrapped (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:60:13)
[W3C]     at retry (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:43:13)
[W3C]     at retryInterval (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:70:10)
[W3C]     at /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:600:7
[HTTP] <-- POST /wd/hub/session 500 74482 ms - 1413
[HTTP]`

**Comment by mykola-mokhnach** [comment] 2022-09-30 10:50
Duplicate of https://github.com/appium/appium/issues/17174
Xcode 14 won't work with the driver bundled to Appium 1

**Closed by mykola-mokhnach** 2022-09-30 10:50 UTC

**Comment by Annjames1** [comment] 2022-09-30 12:14
we have updated appium to version 2.0.0-beta.44 and found that the  WDA file is missing 
in the old version 1.22.3 the WDA was available  in this location
.usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj

But   in this  appium desktop(1.22.3) version it is available  
Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj.  

But in Xcode the build got success ,on creating session in appium it is still  throwing  xcode error 70.

**Comment by KazuCocoa** [comment] 2022-09-30 17:03
appium2's home is APPIUM_HOME. It is `~/.appium` by default. Maybe your local also has the `~/.appium/ if you installed xcuitest driver with appium 2.

Could you share the appium server log when it has the error? (as GIST is better)

**Comment by pmsviacom** [comment] 2022-10-03 05:54
I am also facing the same issue on my Apple TV TVOS - 15.3. Looks like the config and xcode WDA project built success.
but Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code ‘70’ 
xcodebuild: error: Unable to find a destination matching the provided destination specifier:

https://discuss.appium.io/t/unable-to-launch-webdriveragent-because-of-xcodebuild-failure-xcodebuild-failed-with-code-70/37366

Can someone help me on this? , Shall i reopen this Issue?

**Comment by KazuCocoa** [comment] 2022-10-03 07:23
it would be nice to create a new issue with your appium log with `appium:showXcodeLog` log. (then, it would be nice to try the latest xcuitest)

Btw, i googled like https://stackoverflow.com/questions/69708958/unable-to-find-a-destination-matching-the-provided-destination-specifier post. it seems like xcodebuild itself could lost the destination..

According to `Destinations` in `man xcodebuild`, the destination should be either `id` or `name`, so the id should be correct by the documentation by Apple. Then, potentially xcodebuild might have an issue to detect the destination.
```
     tvOS               A tvOS device, which supports the following keys:

                        id    The identifier of the device to use, as shown in the Devices window. A valid destination specifier must provide either id or name, but not both.

                        name  The name of the device to use. A valid destination specifier must provide either id or name, but not both.
```

**Comment by pmsviacom** [comment] 2022-10-03 11:52
@KazuCocoa , Thanks for the reply and the issue has been reported here - https://github.com/appium/appium/issues/17545.
Request to take a look and help.
