### ISSUE TITLE
Unknown server error when swiping

### ISSUE THREAD

**Issue by andreiaionitoaiesv** [appium/appium#8799] opened 2017-07-07 08:46 UTC
[Appium] Appium v1.6.5
[Appium] platformName: 'iOS'
[Appium] platformVersion: '10.0.2'
[debug] [XCUITest] XCUITestDriver version: 2.30.0
[debug] [XCUITest]  Xcode version set to '7.3' 
[debug] [XCUITest] iOS SDK Version set to '11.0'
Appium-Python Client

So I'm trying to make a swipe to element and nothing happens. I've tried using:

```
 action = TouchAction(self)
 action.press(origin_el).move_to(destination_el).release().perform()
```
and

`self.driver.execute_script('mobile: scroll', {'name': accesibilityID, 'direction': 'down'})`

Both are failing with:

self = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x7f9d03117c50>
response = {'status': 500, 'value': '{"status":13,"value":{"message":"An unknown server-side error occurred while processing the ...lement/64B3C4E7-966E-4E00-8DD1-7059DE52EF0A/scroll\"\n    );\n}"},"sessionId":"9d240acd-0f99-4f76-a119-f4a524d6cc7e"}'}

In appium server logs I see this:

2017-07-07 08:00:36:451 - [debug] [JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoint: /session/20855DB0-87E5-4FB3-9477-244E18DD37AC/wda/element/64B3C4E7-966E-4E00-8DD1-7059DE52EF0A/scroll -- http://127.0.0.1:8100/ with parameters {\n    wildcards =     (\n        \"session/20855DB0-87E5-4FB3-9477-244E18DD37AC/wda/element/64B3C4E7-966E-4E00-8DD1-7059DE52EF0A/scroll\"\n    );\n}","sessionId":"20855DB0-87E5-4FB3-9477-244E18DD37AC","status":1}

**Comment by mykola-mokhnach** [comment] 2017-07-07 10:59
closed as duplicate of the issue, which has been reported to WDA

**Closed by mykola-mokhnach** 2017-07-07 10:59 UTC
Labels: ThirdpartyIssue, XCUITest
