### ISSUE TITLE
Locator not working/locatable with Appium 1.15.0 and Xcode 11

### ISSUE THREAD

**Issue by MonarkA** [appium/appium#13302] opened 2019-09-26 18:45 UTC
Hi Team,

Some of the locators, popup messages, alerts message, error message are not locatable on iOS 13 which are working fine on iOS 12

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable):1.14.2
* Desktop OS/version used to run Appium:MacOS 10.14.6 and iOS 13.0
* Node.js version (unless using Appium.app|exe):12.10.0
* Npm or Yarn package manager:6.11.3
* Mobile platform/version under test:iOS 13
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.
Facing below issues:
1. Some Locators are not locatable on iOS 13 like app error message, popup as well which are working fine on iOS 13 with Xcode 11 and Appium 1.15.0.
2. Many Locators are not locatable on iOS 12.* even the locators which are working fine on iOS 13 with Xcode 11 and Appium 1.15.0.
3. On Xcode 10.3 and with Appium 1.15.0, locators working fine.
4. Facing same issue with iOS with Appium latest beta version as well

**Comment by mykola-mokhnach** [comment] 2019-09-26 18:46
Sorry, but such issue description is zero helpful. Please provide the necessary details and log comparisons, so we could investigate it.

**Comment by MonarkA** [comment] 2019-09-26 18:49
do you need Appium logs?

**Comment by mykola-mokhnach** [comment] 2019-09-26 18:52
Everything, which could help to resolve the problem - logs, page source snapshots, screenshots, etc.

**Comment by MonarkA** [comment] 2019-09-26 18:54
I can not get page source as Appium inspector also not working with Xcode 11 and Appium 1.15.0

**Comment by MonarkA** [comment] 2019-09-26 19:11
I am getting below error when I am trying to launch Appium inspector:

An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: Unable to start iproxy. Make sure libusbmuxd is installed and PATH contains the folder, where the binary is located.. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

**Comment by mAiNiNfEcTiOn** [comment] 2019-09-26 21:16
@MonarkA if you're using Node (JS) you can use `driver.getPageSource()` doing: `fs.writeFileSync('./pageSource.log', await driver.getPageSource(), { encoding: 'utf8' });`

**Comment by MonarkA** [comment] 2019-09-27 06:22
ok, thanks for the info @mAiNiNfEcTiOn

could you please confirm one thing i.e. the app that I am using is build on Xcode 10 and I am using Xcode 11. is it possible that this can be an issue?

**Comment by MonarkA** [comment] 2019-09-27 08:28
Please find attached PageSource and Appium logs files
[PageSource.txt](https://github.com/appium/appium/files/3661722/PageSource.txt) 

[AppiumLogs.txt](https://github.com/appium/appium/files/3661721/AppiumLogs.txt)

**Comment by mykola-mokhnach** [comment] 2019-09-27 09:16
So what is the problem in this log? I don't observe any errors there

**Comment by MonarkA** [comment] 2019-09-27 10:09
In the last few lines of AppiumLogs.txt:

[debug] [W3C (2cbe1025)] Calling AppiumDriver.getAttribute() with args: ["value","1F000000-0000-0000-4501-000000000000","2cbe1025-a0ec-48a9-9c67-2f70f83b817a"]
[debug] [XCUITest] Executing command 'getAttribute'
[debug] [WD Proxy] Matched '/element/1F000000-0000-0000-4501-000000000000/attribute/value' to command name 'getAttribute'
[debug] [WD Proxy] Proxying [GET /element/1F000000-0000-0000-4501-000000000000/attribute/value] to [GET http://localhost:7883/session/F0169CA8-4DE8-4C69-A51B-AF96E9AD417D/element/1F000000-0000-0000-4501-000000000000/attribute/value] with no body
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : null,
[debug] [WD Proxy]   "sessionId" : "F0169CA8-4DE8-4C69-A51B-AF96E9AD417D"
[debug] [WD Proxy] }
[debug] [W3C (2cbe1025)] Responding to client with driver.getAttribute() result: null
[HTTP] <-- GET /wd/hub/session/2cbe1025-a0ec-48a9-9c67-2f70f83b817a/element/1F000000-0000-0000-4501-000000000000/attribute/value 200 198 ms - 14
[HTTP] 

This shows that value attribute is null. However, if you check below PageSource part, value attribute is there with value 0 i.e. 
<XCUIElementTypeOther type="XCUIElementTypeOther" value="0" name="automationNavigationHeaderBasketButton" label="automationNavigationHeaderBasketButton" enabled="true" visible="true" x="319" y="46" width="40" height="40"/>

**Comment by marekniedbach-silvair** [comment] 2019-09-27 11:04
I have a similar issue when trying to read `.text` property of WebElement for UITableViewCell where  `accessibilityValue` has been set. It looks like it is returning only `accessibilityLabel` or empty string in this property rather than extracting `accessibilityValue`. When I checked by Appium iOS Inspector I can see value there.

In Appium logs there is just empty value when getting `/value`.

Hope it helps tracking this issue.

**Comment by ochubey** [comment] 2019-09-27 12:26
Seams like the same issue from my side. I'm getting the text of the text field, but it's not the actual one, but placeholder (example: "Email" instead of entered "some@email.org"). No changes to the app/test scripts were done, but upgrade of the Appium version from 1.14.1 to 1.15.
Additionally page source shows value of the field correctly.

**Comment by marekniedbach-silvair** [comment] 2019-09-27 13:16
It seems to be worth to mention that it is working ok on when run on iOS13, so it may be an issue with WDA rather than appium itself.

**Comment by sheikhjebran** [comment] 2019-09-27 21:06
@MonarkA 
Upgrade the Appium to 1.15.0 using below command

`npm install -g appium@1.15.0`

make sure that you also update the project nuget packges

**Comment by MonarkA** [comment] 2019-09-30 17:21
@mykola-mokhnach any update on this issue? I tried latest beta as well i.e 1.16.0-beta.1 but facing same issue on that as well.

**Comment by mykola-mokhnach** [comment] 2019-09-30 18:15
Unfortunately, I cannot reproduce the issue and cannot confirm whether this a WDA issue or XCTest problem. So, no, no updates.

**Comment by automationpss** [comment] 2019-09-30 21:04
Hi, I could not found dmg file at https://github.com/appium/appium-desktop/releases/tag/v1.15.0. Where can I get dmg file for appium desktop 1.15.0?

**Comment by marekniedbach-silvair** [comment] 2019-10-01 06:30
@mykola-mokhnach have you tried to set `accessibilityValue` on some UIView-like element (UITableViewCell in my situation) and reading it from appium through `.text` property of WebElement?
But issue occurs only with appium 1.15.0 + Xcode 11 + iOS 12.x device. I can read this property successfully after updating iOS device to iOS13 or downgrading appium to 1.14.x

**Comment by mykola-mokhnach** [comment] 2019-10-01 07:48
@marekniedbach-silvair See https://github.com/appium/appium/issues/13288

**Comment by MonarkA** [comment] 2019-10-02 18:30
@mykola-mokhnach I tried using capability "includeNonModalElements" by setting it true but still it can not help me to identify locators. is there any other Appium capability that can help?

**Comment by marekniedbach-silvair** [comment] 2019-10-03 14:39
@mykola-mokhnach sadly, none of the flags described there helped in my issue.

**Comment by Zaykona** [comment] 2019-10-10 10:05
get value return empty string with Appium 1.15 and Xcode 11.1 for iOS 12.Is there any updates for this issue? Or workaround?

**Comment by Shibo786** [comment] 2019-10-22 00:15
With Appium Java client I see iOS >13 is working slow but with iOS<13 sendKeys() and clear() are not working. Had to downgrade myself to 1.13.0 and Xcode 10.3....... For test suite run I am looking to run for devices with iOS range >12 and <= 13.1.3. Any suggestions anyone?

**Comment by KazuCocoa** [comment] 2019-10-22 00:22
> iOS >13 is working slow

It is XCTest framework issue if the element is inside `XCUIElementTypeWebView` https://github.com/appium/appium/issues/13455

> with iOS<13 sendKeys() and clear() are not working

Xcode 11 and non-iOS 13 combination error... https://github.com/appium/appium/issues/13288

Only Apple can fix them.
So, Xcode 10.3 x iOS 12 and lower version and Xcode 11 x iOS 13 are current way..

**Comment by Shibo786** [comment] 2019-10-22 00:26
Hmm so we cannot run our test suites on iOS >13 as of now it seems :(

**Comment by juandg** [comment] 2019-10-22 21:59
Has anyone filed a bug with Apple? 

It would be great if we can make Apple aware of the issue so they can fix it. "Radar" is now gone so it has to be done through the new Feedback Assistant -> https://feedbackassistant.apple.com

**Comment by mykola-mokhnach** [comment] 2019-10-25 13:12
Closed as third party issue

**Closed by mykola-mokhnach** 2019-10-25 13:12 UTC
Labels: ThirdParty, XCUITest

**Comment by mrk-han** [comment] 2019-12-03 16:51
@mykola-mokhnach @KazuCocoa 

Is there a maintained list of bugs that are third party related for Appium? Specifically, Xcode/XCTest related?

(e.g. XCTest reporting certain table view fields as not visible, or getText/clear not working)

**Comment by KazuCocoa** [comment] 2019-12-04 01:24
No, but you can find XCTest labelled issues like https://github.com/appium/appium/issues?q=label%3AXCUITest
