### ISSUE TITLE
Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos12.2-arm64.xctestrun” doesn’t exist.

### ISSUE THREAD

**Issue by guowang94** [appium/appium#12636] opened 2019-05-13 07:10 UTC
## The problem

Unable to run WebDriverAgent on the real device using Appium Desktop.

# Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0-beta.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Mojave version 10.14.3
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: 12.1.4
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

server log
https://gist.github.com/guowang94/ec923da6a3b77aca06a902c450200238

appium.app error message
https://gist.github.com/guowang94/ef2c5bb5bcc617baa2af19418e9a8b8e

**Comment by mykola-mokhnach** [comment] 2019-05-13 07:24
Duplicate of https://github.com/appium/appium/issues/12581

**Closed by mykola-mokhnach** 2019-05-13 07:24 UTC

**Comment by guowang94** [comment] 2019-05-13 07:51
@mykola-mokhnach I have tried the solution given by @aryalakshmi. I have tried adding additional capabilities and it did not work. The reason for failing is also different from @aryalakshmi.

`Testing failed:
[debug] [MJSONWP]       An empty identity is not valid when signing a binary for the product type 'UI Testing Bundle'. (in target 'WebDriverAgentRunner')
[debug] [MJSONWP]       WebDriverAgentRunner:
[debug] [MJSONWP]               WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))`

**Comment by mykola-mokhnach** [comment] 2019-05-13 07:53
> An empty identity is not valid when signing a binary for the product type 'UI Testing Bundle

The error there is pretty clear - you must fix the signing. There is nothing that has to do with Appium

**Comment by guowang94** [comment] 2019-05-13 07:58
Do I need a paid developer account to sign com.facebook.WebDriverRunner? because right now I am not using a paid developer account

**Comment by mykola-mokhnach** [comment] 2019-05-13 07:59
Please use Appium forum to ask questions

**Comment by hardik-plume** [comment] 2019-05-21 03:23
@mykola-mokhnach i tried upgrading from appium 1.10.1 to 1.13.0 and i am seeing this error. Uninstalled and went back to 1.10.1 and the issue does not appear so can you explain why with latest appium we are getting the code signing issue? What specifically has changed that can cause this? I even tried appium 1.12 version and that has its own issues.

**Comment by coolshree4u** [comment] 2019-07-16 07:35
@guowang94 "The folder “WebDriverAgentRunner_iphoneos12.2-arm64.xctestrun”  is not present so causing this error. If you are able to run from the terminal then at the same location i.e. `/Users/****UserName****/Library/Developer/Xcode/DerivedData` you will get another folder named `WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy` (Automatically created by running with help of terminal) in my case and your appium desktop will create another folder at same location like `WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs`.

Step to remove this error:
1. Make sure the content of the folder created by running tests through terminal should be present at new folder created by appium desktop application(Removed the error in my case). i.e. from `WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy` to `WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs`

**Comment by strongSoda** [comment] 2025-03-05 14:03
This error generally indicates that the system is unable to find a specific file or shortcut, likely because it has been moved, deleted, or is incorrectly linked.

Here’s how you can fix it:

- Confirm the File or Shortcut Exists: Check to ensure the file or shortcut you're trying to access is still in the correct location and hasn't been moved or deleted.
- Recreate the Shortcut: If the shortcut is broken, delete it and create a new one pointing to the correct file.
- Check File Permissions: Make sure you have the proper permissions to access the file by reviewing its settings.
- Restart your Mac: Rebooting your Mac can sometimes help resolve system-level issues causing this error.

[Step-by-step solutions and methods](https://rref-calculator.com/blog/errordomain-nscocoaerrordomain-errormessage-could-not-find-the-specified-shortcut-errorcode-4/)
