### ISSUE TITLE
org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: Locator map:  

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#9780] opened 2017-12-12 08:12 UTC
## The problem

1.7.2-beta2 + java client version  5.0.4

1.   I had an element which was working in earlier version of appium
```
@AndroidFindBy(xpath="//android.widget.Button[@content-desc='button-lets-begin']")
@iOSFindBy(xpath="//XCUIElementTypeButton[@name='button-lets-begin']")
private WebElement LetsBeginButton;
```

2.  

```
org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: Locator map: 
- native content: "By.id: LetsBeginButton" 
- html content: "by id or name "LetsBeginButton""
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:102)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:61)
	at org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4.click(<generated>)
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2-beta2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.0
* Desktop OS/version used to run Appium: Mac OS 
* Node.js version (unless using Appium.app|exe): v8.4.0
* Mobile platform/version under test: iOS Simulator 11.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:  CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/vikramvi/53556a6fe2cef7e5363c8b75a50d5f8e

## Code To Reproduce Issue [ Good To Have ]

NA

**Comment by mykola-mokhnach** [comment] 2017-12-12 10:02
Duplicate of https://github.com/appium/appium/issues/9762

**Closed by mykola-mokhnach** 2017-12-12 10:02 UTC

**Comment by vikramvi** [comment] 2017-12-12 10:11
@mykola-mokhnach this is not duplicate, please re-open. error message in this ticket doesn't match with that of 9762 or 9756.

The app which I'm automating is built with react native, not sure your intention / root cause of marking this as duplicate.

Please clarify.

**Comment by mykola-mokhnach** [comment] 2017-12-12 10:16
> [debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"

It is the same issue. Apple did some changes in Xcode 9.2 SDK, so some elements disappeared from the page source as a result.  Appium anyway cannot do anything to fix this, because it is just a proxy between WDA/XCTest and the client code.

**Comment by vikramvi** [comment] 2017-12-12 12:46
Thanks @mykola-mokhnach for clarification, is there any workaround for this ? 
e.g. going back to older version of iOS ?

**Comment by mykola-mokhnach** [comment] 2017-12-12 13:02
> going back to older version of iOS ?

yes, perhaps this would be the best solution for now

**Comment by vikramvi** [comment] 2017-12-13 07:22
Issue is reproducible with iOS version 10.3.1 as well, I doubt if this is duplicate of issue you mentioned earlier.

**Comment by Maxim-P** [comment] 2017-12-13 13:27
Hi. 
I have this issue too at iOS 11.0 & 11.1 emulator with Serenity framework. 
@vikramvi if you find any workaround for this problem, pls, share in this topic.

**Comment by Maxim-P** [comment] 2017-12-13 15:09
Annotation:
```
@iOSFindBy(id = "MainTable")
    WebElement tabBar;
```

Try to debug:
Class DefaultElementByBuilder
![image](https://user-images.githubusercontent.com/9475698/33941693-853cc74c-e024-11e7-8e14-0326e9770113.png)

`mobilyNativeBy: By.id: MainTable`
Looks OK

Class AppiumElementLocatorFactory
![image](https://user-images.githubusercontent.com/9475698/33941818-fb1c67d8-e024-11e7-81e1-e77e84058803.png)

..still looks OK for Native app
![image](https://user-images.githubusercontent.com/9475698/33943106-1dc0c410-e029-11e7-94ac-f3dab3fe3d4c.png)
![image](https://user-images.githubusercontent.com/9475698/33943182-6c01d664-e029-11e7-9037-0c929292454f.png)

but in this step we have exception
Maybe its cuz appium try found WebElement on https page but not on Native

**Comment by vikramvi** [comment] 2017-12-13 19:48
@mykola-mokhnach  this is definitely not related to XCode 9.2

I could able to reproduce this with XCode 9.0 as well.

getPageSource output

https://gist.github.com/vikramvi/a99c751475cd04500937352c3e80dc06

**Comment by vikramvi** [comment] 2017-12-13 19:49
@Maxim-P 

Please give below info

1. serenity-core version
2. XCode version 

> Hi.
> I have this issue too at iOS 11.0 & 11.1 emulator with Serenity framework.
> @vikramvi if you find any workaround for this problem, pls, share it in this topic.

**Comment by mykola-mokhnach** [comment] 2017-12-13 19:55
> https://gist.github.com/vikramvi/a99c751475cd04500937352c3e80dc06

I don't see any element with `LetsBeginButton` identifier there

**Comment by mykola-mokhnach** [comment] 2017-12-13 19:57
I assume the stuff has been changed in java client (particularly the format of chained locators annotations) and has nothing to do with the server. @TikhomirovSergey can you please confirm?

**Comment by Maxim-P** [comment] 2017-12-14 07:00
@vikramvi 
Sure!
1. Serenity-core Version 1.8.5 
2. XCode Version 9.2 (9C40b)

**Comment by vikramvi** [comment] 2017-12-14 07:25
`@iOSFindBy(xpath="//XCUIElementTypeButton[@name='**button-lets-begin**']")
`
@mykola-mokhnach  this is the identifier, `LetsBeginButton` is just element name

> https://gist.github.com/vikramvi/a99c751475cd04500937352c3e80dc06
> 
> I don't see any element with LetsBeginButton identifier there

**Comment by Maxim-P** [comment] 2017-12-14 15:38
@vikramvi 
i fix my issue.

_XCode: 9.1
iOS: 11.1_
I check your repository **AppiumSerenityPOC** and saw version serenity-core _1.5.12._ 
With 1.5.12 my element was found well...

**Comment by vikramvi** [comment] 2017-12-14 18:44
@Maxim-P serenity-core current version is `1.8.7` , can you please clarify from where you're referring to `1.5.12` ?

**Comment by Maxim-P** [comment] 2017-12-15 09:01
@vikramvi 
https://github.com/vikramvi/AppiumSerenityPOC/blob/master/pom.xml#L17

Ex. of fails:
With serenity-core 1.5.12 (io.appium:java-client:5.0.3) catch:
```
net.serenitybdd.core.exceptions.SerenityManagedException: The following error occurred: Can't locate an element by this strategy: Locator map: 
- native content: **"By.chained({By.AccessibilityId: MainTableFalse})"** 
- html content: "by id or name "tabBar""
```
Its OK, cuz element valid ID must be "MainTable"

Some case with serenity-core 1.8.7 (io.appium:java-client:5.0.4) catch:

```
net.serenitybdd.core.exceptions.SerenityManagedException: The following error occurred: Can't locate an element by this strategy: Locator map: 
- native content: **"By.id: tabBar"** 
- html content: "by id or name "tabBar""
```
Its incorrect, ID must be some as previous case.

Element:
```
    @iOSFindBy(accessibility = "MainTableFalse")
    private WebElement tabBar;
```

Method:
    public void mainPageOpened() {
        tabBar.isDisplayed();
    }

**Comment by vikramvi** [comment] 2017-12-15 09:45
@Maxim-P I won't recommend using very old version of serenity-core but instead use latest one. 

I've submitted PR to include latest version of Appium Java client, once new version of serenity-core is out let me check again.

**Comment by vikramvi** [comment] 2017-12-16 08:51
@TikhomirovSergey  can you please look into this issue

- It happens with serenity-core version v1.8.9 which has got latest appium java client.
- getPageSource does show element but it can't be clicked because of error

**Comment by tcanascimento** [comment] 2018-01-29 16:24
I have been the same issue by running tests on AWS Farm, where is running Xcode '7.3' 
and iOS SDK Version set to '11.0'.

**Comment by Anuj-HH** [comment] 2018-03-21 11:27
Hi @vikramvi, Have you got any workaround/fix for this? I am also facing this with react-native app. The element could be found separately for Android and iOS if I only use @FindBy, This does not help in Cross-platform though.

**Comment by vikramvi** [comment] 2018-03-21 11:43
@Anuj-HH I didn't check this with latest version of [Serenity framework](https://github.com/serenity-bdd/serenity-core).

I recommend to test with latest versions of appium server, java client and serenity.

**Comment by ppzzss** [comment] 2018-05-03 12:10
Below annotations work well in Appium 1.7.2

@iOSXCUITFindBy (xpath = "xxxx")
@AndroidFindBy (id = "bbbb")
public WebElement usernameTextField;
