### ISSUE TITLE
Appium not able to locate visible element

### ISSUE THREAD

**Issue by rajkumar-cp** [appium/appium#12422] opened 2019-04-01 17:32 UTC
After clicking a particular element in mobile application appium is not able to find any other elements present in the page.

## Environment

* Appium version (or git revision) that exhibits the issue:1.10.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: android 8.0
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe:vAppium.exe

## Details

I am interacting with one particular element with xpath value : //android.widget.ImageView[@content-desc='abc_action_menu_overflow_description']

after interacting with this elemnt appium is not able to interact with any other elements in the application. It waits for some time with response as OK and after sometime we are recieving this error message 
	01-huhtikuuta-2019 19:41:56:007 INFO  [RetryExec] I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://10.7.0.88:5004: The target server failed to respond 
[16:41:58]	01-huhtikuuta-2019 19:41:56:008 INFO  [RetryExec] Retrying request to {}->http://10.7.0.88:5004 

## Link to Appium logs

https://gist.github.com/rajkumar-cp/47f5a641b663b87deae423af1b0d8363

**Comment by mykola-mokhnach** [comment] 2019-04-01 17:54
> [warn] [35m[Appium][39m Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.

**Comment by rajkumar-cp** [comment] 2019-04-02 12:14
@mykola-mokhnach 
On setting automationname as uiautomator2 in capabilities we were receiving the below mentioned error

https://gist.github.com/rajkumar-cp/de6f0b8e7d290e04721457bd02064da1

Note: I tried to remove that capability from the code after recieving this error but even after then by default irt is setting automationname as uiautomator2.

**Comment by mykola-mokhnach** [comment] 2019-04-02 14:42
socket timeout error means that the server stops responding unexpectedly. This might be caused by multiple reasons. At first, I would try to get the logcat output.

**Comment by rajkumar-cp** [comment] 2019-04-02 15:27
@mykola-mokhnach 
PFA the logs
https://gist.github.com/rajkumar-cp/157f2938188e7a0c11a66733def14447

**Comment by mykola-mokhnach** [comment] 2019-04-03 14:11
> 2019-04-03 10:19:07.568 7142-7174/? D/appium: payload: {"strategy":"id","selector":"connecting_progress","context":"","multiple":false}
> 2019-04-03 10:19:07.569 7142-7174/? I/appium: find element command using 'id' with selector 'connecting_progress'.
> 2019-04-03 10:19:07.916 7142-7176/? I/appium: channel read invoked!
> 2019-04-03 10:19:07.916 7142-7176/? I/appium: channel read: DELETE /wd/hub/session/20a08b51-36c7-44f8-8e9f-35071d48c697
> 2019-04-03 10:19:07.917 7142-7176/? I/appium: Delete session command
> 2019-04-03 10:19:07.917 7142-7176/? D/appium: Stopping toast notification listener.
> 2019-04-03 10:19:07.925 1777-3002/system_process W/AppOps: Bad call: specified package io.appium.uiautomator2.server.test under uid 10085 but it is really 10086
>     java.lang.RuntimeException: here
>         at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1319)
>         at com.android.server.AppOpsService.getOpLocked(AppOpsService.java:1351)
>         at com.android.server.AppOpsService.finishOperation(AppOpsService.java:1198)
>         at com.android.server.power.Notifier.onWakeLockReleased(Notifier.java:299)
>         at com.android.server.power.PowerManagerService.notifyWakeLockReleasedLocked(PowerManagerService.java:1275)
>         at com.android.server.power.PowerManagerService.removeWakeLockLocked(PowerManagerService.java:1159)
>         at com.android.server.power.PowerManagerService.releaseWakeLockInternal(PowerManagerService.java:1131)
>         at com.android.server.power.PowerManagerService.-wrap23(Unknown Source:0)
>         at com.android.server.power.PowerManagerService$BinderService.releaseWakeLock(PowerManagerService.java:4153)
>         at android.os.IPowerManager$Stub.onTransact(IPowerManager.java:94)
>         at android.os.Binder.execTransact(Binder.java:674)
> 2019-04-03 10:19:07.938 7142-7176/? I/appium: Stopping uiautomator2 io.appium.uiautomator2.http io.appium.uiautomator2.server
> 2019-04-03 10:19:07.949 7142-7176/? I/appium: AppiumResponse: {"sessionId":"20a08b51-36c7-44f8-8e9f-35071d48c697","status":0,"value":"Session deleted"}
> 2019-04-03 10:19:07.949 7142-7174/? D/appium: Updated findElement locator strategy: com.mfiles.mobile:id/connecting_progress
> 2019-04-03 10:19:07.957 7142-7174/? I/appium: AppiumResponse: {"sessionId":"20a08b51-36c7-44f8-8e9f-35071d48c697","status":0,"value":{"ELEMENT":"60ebec6e-b3b4-410d-b2e3-262a1f288e78"}}
> 2019-04-03 10:19:08.030 1394-1394/? E/adbd: failed to connect to socket 'tcp:6790': Connection refused
> 2019-04-03 10:19:08.168 1394-1394/? E/adbd: failed to connect to socket 'tcp:6790': Connection refused
> 2019-04-03 10:19:08.289 7142-7159/? I/TestRunner: finished: startServer(io.appium.uiautomator2.server.test.AppiumUiAutomator2Server)
> 2019-04-03 10:19:08.291 7142-7142/? I/MonitoringInstrumentation: Activities that are still in CREATED to STOPPED: 0
> 2019-04-03 10:19:08.293 7142-7159/? I/TestRunner: run finished: 1 tests, 0 failed, 0 ignored
> 2019-04-03 10:19:08.329 1394-1394/? E/adbd: failed to connect to socket 'tcp:6790': Connection refused
> 

The logcat shows that the server has received the DELETE command somewhere in the middle. Although I cannot figure out what exactly is sending it.

**Comment by rajkumar-cp** [comment] 2019-04-03 16:54
@mykola-mokhnach 
Does this has anything to do with the emulator proxy settings? I am not observing this issue when i am not using that capability.

**Comment by mykola-mokhnach** [comment] 2019-04-03 20:16
I don't know exactly what is going on there, just sharing my log observations

**Comment by mykola-mokhnach** [comment] 2019-04-08 11:45
I don't think there is anything to do on Appium side.
Closed as third party issue

**Closed by mykola-mokhnach** 2019-04-08 11:45 UTC
Labels: ThirdParty, UIAutomator2
