### ISSUE TITLE
An error (response status: 13) occurred when performaing the gestures.

### ISSUE THREAD

**Issue by yaosum** [appium/appium#10764] opened 2018-05-28 09:08 UTC
## 

I upgraded the appium to 1.8.0, then I perform the gesture operation like tap the element. But it response "status: 13". Before I upgrade the appium tool, I use the same script to peroform gesture operation, it is normally. The version of appium I used is 1.7.2. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: 1.6.1
* Node.js version (unless using Appium.app|exe): 6.11.0
* Mobile platform/version under test: iPhone 6s Plus(10.3.3)
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: appium.app

## Details

I used appium inspector tool to perform gesture operation, but it response error.
[performTouchAction([{"action":"press","options":{"x":369,"y":151}},{"action":"moveTo","options":{"x":-326,"y":2}},{"action":"release","options":{}}])] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: An error occurred

## Link to Appium logs

https://gist.github.com/yaosum/d884b3e4cddfbb04037a651a15619b38

## Code To Reproduce Issue [ Good To Have ]

The script I use is that.
el1 = driver.get_window_size()  # 获取当前屏幕的大小
width = el1.get('width')
height = el1.get('height')
start_x = width * 4 / 5
 y = height * 2 / 5
end_x = width * 1 / 5
driver.glide(start_x, y, end_x, y)
 sleep(1)

**Comment by mykola-mokhnach** [comment] 2018-05-28 10:39
Since 1.8.0 moveTo coordinates are absolute. Also, if you'd like to perform swipe gesture then add at least 600 ms wait item after press.

Closed as designed.

**Closed by mykola-mokhnach** 2018-05-28 10:39 UTC

**Comment by yaosum** [comment] 2018-05-29 06:57
But I just performed tap operation, it also occured error.
[info] [HTTP] <-- GET /wd/hub/session/80c8e25b-d301-4942-884c-f9f95a36d0dc/window/current/size 200 530 ms - 98
[info] [HTTP] [info] [HTTP] --> POST /wd/hub/session/80c8e25b-d301-4942-884c-f9f95a36d0dc/touch/perform
[info] [HTTP] {"actions":[{"action":"tap","options":{"x":122,"y":705}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"x":122,"y":705}}],"80c8e25b-d301-4942-884c-f9f95a36d0dc"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: tap(options={"x":122,"y":705})
[debug] [JSONWP Proxy] Proxying [POST /wda/touch/perform] to [POST http://localhost:8100/session/D846F1E0-C382-4E06-91D2-E6A44C1922FA/wda/touch/perform] with body: {"actions":[{"action":"tap","options":{"x":122,"y":705}}]}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoint: /session/D846F1E0-C382-4E06-91D2-E6A44C1922FA/wda/touch/perform -- http://localhost:8100/ with parameters {\n    wildcards =     (\n        \"session/D846F1E0-C382-4E06-91D2-E6A44C1922FA/wda/touch/perform\"\n    );\n}","sessionId":"D846F1E0-C382-4E06-91D2-E6A44C1922FA","status":1}
[error] [MJSONWP] Encountered internal error running command: Error: An error occurred
[error] [MJSONWP]     at JWProxy.command$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
[error] [MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[error] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[error] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[error] [MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[error] [MJSONWP]     at <anonymous>
[info] [HTTP] <-- POST /wd/hub/session/80c8e25b-d301-4942-884c-f9f95a36d0dc/touch/perform 500 23 ms - 188
[info] [HTTP]

**Comment by mykola-mokhnach** [comment] 2018-05-29 07:02
Are you in webview context? If yes then the error is expected
