### ISSUE TITLE
Failed to create WDA session (A new session could not be created. Details: Failed to launch

### ISSUE THREAD

**Issue by deepeshpk** [appium/appium#14339] opened 2020-05-15 03:58 UTC
## The problem
Able to run the appium automation scripts in my machine without any issue.
I am using Catalina 10.15.1, Xcode 11.3.1 and Appium 1.15.1

But when I moved this code to a different mac mini, it is failing with the following logs.

Catalina 10.15.4
Xcode  :  11.4.1
iPhone X : iOS 13.4
## Environment

[35m[Appium][39m Welcome to Appium v1.17.0
[35m[Appium][39m Non-default server args:
[35m[Appium][39m   port: 6020
[35m[Appium][39m   bootstrapPort: 6025
[35m[Appium][39m   udid: 6763e1801a5fe3d53d1470c20fa07a3d3b0e9c7e
[35m[Appium][39m Deprecated server args:
[35m[Appium][39m   [31m-U,--udid[39m => --default-capabilities '{"udid":"6763e1801a5fe3d53d1470c20fa07a3d3b0e9c7e"}'
[35m[Appium][39m Default capabilities, which will be added to each request unless overridden by desired capabilities:
[35m[Appium][39m   udid: 6763e1801a5fe3d53d1470c20fa07a3d3b0e9c7e
[35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:6020
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[35m[HTTP][39m [90m{"desiredCapabilities":{"bundleId":"org.kp.tpmg.preventivecare.beta","explicitTimeout":"60","deviceName":"iPhone8","platform":"IOS","wdaLocalPort":"6025","scriptTimeout":"120","pageLoadTimeout":"120","acceptSslCerts":true,"build":"localbuild","newCommandTimeout":"10","platformVersion":"13.3","automationName":"XCUITest","name":"verifyTempAccessTest","browserName":"","deviceOrientation":"portrait","runlocal":"true","platformName":"iOS","udid":"6763e1801a5fe3d53d1470c20fa07a3d3b0e9c7e"},"capabilities":{"firstMatch":[{"acceptSslCerts":true,"appium:automationName":"XCUITest","browserName":"","build":"localbuild","appium:bundleId":"org.kp.tpmg.preventivecare.beta","appium:deviceName":"iPhone8","deviceOrientation":"portrait","explicitTimeout":"60","name":"verifyTempAccessTest","appium:newCommandTimeout":"10","pageLoadTimeout":"120","platform":"IOS","platformName":"ios","appium:platformVersion":"13.3","runlocal":"true","scriptTimeout":"120","appium:udid":"6763e1801a5fe3d53d1470c20fa07a3d3b0e9c[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"bundleId":"org.kp.tpmg.preventivecare.beta","explicitTimeout":"60","deviceName":"iPhone8","platform":"IOS","wdaLocalPort":"6025","scriptTimeout":"120","pageLoadTimeout":"120","acceptSslCerts":true,"build":"localbuild","newCommandTimeout":"10","platformVersion":"13.3","automationName":"XCUITest","name":"verifyTempAccessTest","browserName":"","deviceOrientation":"portrait","runlocal":"true","platformName":"iOS","udid":"6763e1801a5fe3d53d1470c20fa07a3d3b0e9c7e"},null,{"firstMatch":[{"acceptSslCerts":true,"appium:automationName":"XCUITest","browserName":"","build":"localbuild","appium:bundleId":"org.kp.tpmg.preventivecare.beta","appium:deviceName":"iPhone8","deviceOrientation":"portrait","explicitTimeout":"60","name":"verifyTempAccessTest","appium:newCommandTimeout":"10","pageLoadTimeout":"120","platform":"IOS","platformName":"ios","appium:platformVersion":"13.3","runlocal":"true","scriptTimeout":"120","appium:udid":"6763e1801a5fe3d53d1470c20fa07a3d3b0e9c7e","appium:wdaLocalPort":"6025"}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1589513529501 (20:32:09 GMT-0700 (Pacific Daylight Time))
[35m[BaseDriver][39m The following capabilities are not standard capabilities and should have an extension prefix:
[35m[BaseDriver][39m   acceptSslCerts
[35m[BaseDriver][39m   build
[35m[BaseDriver][39m   deviceOrientation
[35m[BaseDriver][39m   explicitTimeout
[35m[BaseDriver][39m   name
[35m[BaseDriver][39m   pageLoadTimeout
[35m[BaseDriver][39m   platform
[35m[BaseDriver][39m   runlocal
[35m[BaseDriver][39m   scriptTimeout
[35m[BaseDriver][39m Number capability passed in as string. Functionality may be compromised.
[35m[Appium][39m Appium v1.17.0 creating new XCUITestDriver (v3.17.0) session
[debug] [35m[BaseDriver][39m W3C capabilities and MJSONWP desired capabilities were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {
[debug] [35m[BaseDriver][39m   "alwaysMatch": {
[debug] [35m[BaseDriver][39m     "appium:acceptSslCerts": true,
[debug] [35m[BaseDriver][39m     "browserName": "",
[debug] [35m[BaseDriver][39m     "appium:build": "localbuild",
[debug] [35m[BaseDriver][39m     "appium:deviceOrientation": "portrait",
[debug] [35m[BaseDriver][39m     "appium:explicitTimeout": "60",
[debug] [35m[BaseDriver][39m     "appium:name": "verifyTempAccessTest",
[debug] [35m[BaseDriver][39m     "appium:pageLoadTimeout": "120",
[debug] [35m[BaseDriver][39m     "appium:platform": "IOS",
[debug] [35m[BaseDriver][39m     "platformName": "ios",
[debug] [35m[BaseDriver][39m     "appium:runlocal": "true",
[debug] [35m[BaseDriver][39m     "appium:scriptTimeout": "120",
[debug] [35m[BaseDriver][39m     "appium:automationName": "XCUITest",
[debug] [35m[BaseDriver][39m     "appium:bundleId": "org.kp.tpmg.preventivecare.beta",
[debug] [35m[BaseDriver][39m     "appium:deviceName": "iPhone8",
[debug] [35m[BaseDriver][39m     "appium:newCommandTimeout": "10",
[debug] [35m[BaseDriver][39m     "appium:platformVersion": "13.3",
[debug] [35m[BaseDriver][39m     "appium:udid": "6763e1801a5fe3d53d1470c20fa07a3d3b0e9c7e",
[debug] [35m[BaseDriver][39m     "appium:wdaLocalPort": "6025"
[debug] [35m[BaseDriver][39m   },
[debug] [35m[BaseDriver][39m   "firstMatch": [
[debug] [35m[BaseDriver][39m     {}
[debug] [35m[BaseDriver][39m   ]
[debug] [35m[BaseDriver][39m }
[35m[BaseDriver][39m Number capability passed in as string. Functionality may be compromised.
[35m[BaseDriver][39m Number capability passed in as string. Functionality may be compromised.
[35m[BaseDriver][39m Capability 'newCommandTimeout' changed from string ('10') to integer (10). This may cause unexpected behavior
[35m[BaseDriver][39m Capability 'wdaLocalPort' changed from string ('6025') to integer (6025). This may cause unexpected behavior
[35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
[35m[BaseDriver][39m   acceptSslCerts
[35m[BaseDriver][39m   build
[35m[BaseDriver][39m   deviceOrientation
[35m[BaseDriver][39m   explicitTimeout
[35m[BaseDriver][39m   name
[35m[BaseDriver][39m   pageLoadTimeout
[35m[BaseDriver][39m   platform
[35m[BaseDriver][39m   runlocal
[35m[BaseDriver][39m   scriptTimeout
[35m[BaseDriver][39m Session created with session id: 0f4a7f29-2ecf-43b2-9f5b-7ce308453703
[debug] [35m[XCUITest][39m Current user: 'mdoadmin'
[debug] [35m[XCUITest][39m Available devices: 6763e1801a5fe3d53d1470c20fa07a3d3b0e9c7e
[debug] [35m[XCUITest][39m Creating iDevice object with udid '6763e1801a5fe3d53d1470c20fa07a3d3b0e9c7e'
[35m[XCUITest][39m Determining device to run tests on: udid: '6763e1801a5fe3d53d1470c20fa07a3d3b0e9c7e', real device: true
[debug] [35m[BaseDriver][39m Event 'xcodeDetailsRetrieved' logged at 1589513530124 (20:32:10 GMT-0700 (Pacific Daylight Time))
[debug] [35m[BaseDriver][39m Event 'appConfigured' logged at 1589513530124 (20:32:10 GMT-0700 (Pacific Daylight Time))
[debug] [35m[BaseDriver][39m Event 'resetStarted' logged at 1589513530125 (20:32:10 GMT-0700 (Pacific Daylight Time))
[debug] [35m[XCUITest][39m Reset: running ios real device reset flow
[debug] [35m[BaseDriver][39m Event 'resetComplete' logged at 1589513530126 (20:32:10 GMT-0700 (Pacific Daylight Time))
[debug] [35m[XCUITest][39m Crash reports root '/Users/mdoadmin/Library/Logs/CrashReporter/MobileDevice/Deepesh Kumar’s iPhone' does not exist. Got nothing to gather.
[debug] [35m[BaseDriver][39m Event 'logCaptureStarted' logged at 1589513530316 (20:32:10 GMT-0700 (Pacific Daylight Time))
[35m[XCUITest][39m Setting up real device
[35m[WebDriverAgent][39m Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
[35m[WebDriverAgent][39m Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[debug] [35m[WebDriverAgent][39m Error: Command 'lsof -ti tcp\:6025' exited with code 1
[debug] [35m[WebDriverAgent][39m     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/teen_process/lib/exec.js:113:19)
[debug] [35m[WebDriverAgent][39m     at ChildProcess.emit (events.js:315:20)
[debug] [35m[WebDriverAgent][39m     at maybeClose (internal/child_process.js:1051:16)
[debug] [35m[WebDriverAgent][39m     at Socket.<anonymous> (internal/child_process.js:442:11)
[debug] [35m[WebDriverAgent][39m     at Socket.emit (events.js:315:20)
[debug] [35m[WebDriverAgent][39m     at Pipe.<anonymous> (net.js:671:12)
[debug] [35m[WebDriverAgent][39m No obsolete cached processes from previous WDA sessions listening on port 6025 have been found
[35m[DevCon Factory][39m Requesting connection for device 6763e1801a5fe3d53d1470c20fa07a3d3b0e9c7e on local port 6025, device port 6025
[debug] [35m[DevCon Factory][39m Cached connections count: 0
[35m[DevCon Factory][39m Successfully requested the connection for 6763e1801a5fe3d53d1470c20fa07a3d3b0e9c7e:6025
[debug] [35m[XCUITest][39m Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:6025/status] with no body
[35m[WD Proxy][39m Got response with unknown status: {"code":"ESOCKETTIMEDOUT","connect":false}
[debug] [35m[WebDriverAgent][39m WDA is not listening at 'http://127.0.0.1:6025/'
[debug] [35m[WebDriverAgent][39m WDA is currently not running. There is nothing to cache
[debug] [35m[XCUITest][39m Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [35m[XCUITest][39m These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [35m[BaseDriver][39m Event 'wdaStartAttempted' logged at 1589513533638 (20:32:13 GMT-0700 (Pacific Daylight Time))
[35m[WebDriverAgent][39m Launching WebDriverAgent on the device
[35m[WebDriverAgent][39m Fetching dependencies
[35m[WebDriverAgent][39m Dependencies up-to-date
[debug] [35m[WebDriverAgent][39m Killing running processes 'xcodebuild.*6763e1801a5fe3d53d1470c20fa07a3d3b0e9c7e' for the device 6763e1801a5fe3d53d1470c20fa07a3d3b0e9c7e...
[debug] [35m[WebDriverAgent][39m Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=6763e1801a5fe3d53d1470c20fa07a3d3b0e9c7e IPHONEOS_DEPLOYMENT_TARGET=13.3 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
[debug] [35m[WebDriverAgent][39m Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[debug] [35m[WebDriverAgent][39m Waiting up to 60000ms for WebDriverAgent to start
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:6025/status] with no body
[debug] [35m[iProxy@6763e180:6025][39m Connection was refused to port 6025
[35m[WD Proxy][39m Got response with unknown status: {"code":"ECONNRESET"}
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:6025/status] with no body
[debug] [35m[iProxy@6763e180:6025][39m Connection was refused to port 6025
[35m[WD Proxy][39m Got response with unknown status: {"code":"ECONNRESET"}
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:6025/status] with no body
[debug] [35m[iProxy@6763e180:6025][39m Connection was refused to port 6025
[35m[WD Proxy][39m Got response with unknown status: {"code":"ECONNRESET"}
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:6025/status] with no body
[debug] [35m[iProxy@6763e180:6025][39m Connection was refused to port 6025
[35m[WD Proxy][39m Got response with unknown status: {"code":"ECONNRESET"}
[debug] [35m[WebDriverAgent][39m Log file for xcodebuild test: /Users/mdoadmin/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs/Test/Test-WebDriverAgentRunner-2020.05.14_20-32-16--0700.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-B3E84610-0FA2-4102-A971-CC5E32884365/WebDriverAgentRunner-8C40688D-5E08-4FA3-BEA6-EDA5C3CECBF5/Session-WebDriverAgentRunner-2020-05-14_203217-ijq9yl.log
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:6025/status] with no body
[debug] [35m[iProxy@6763e180:6025][39m Connection was refused to port 6025
[35m[WD Proxy][39m Got response with unknown status: {"code":"ECONNRESET"}
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:6025/status] with no body
[debug] [35m[iProxy@6763e180:6025][39m Connection was refused to port 6025
[35m[WD Proxy][39m Got response with unknown status: {"code":"ECONNRESET"}
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:6025/status] with no body
[debug] [35m[iProxy@6763e180:6025][39m Connection was refused to port 6025
[35m[WD Proxy][39m Got response with unknown status: {"code":"ECONNRESET"}
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:6025/status] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {
[debug] [35m[WD Proxy][39m   "value" : {
[debug] [35m[WD Proxy][39m     "message" : "WebDriverAgent is ready to accept commands",
[debug] [35m[WD Proxy][39m     "state" : "success",
[debug] [35m[WD Proxy][39m     "os" : {
[debug] [35m[WD Proxy][39m       "name" : "iOS",
[debug] [35m[WD Proxy][39m       "version" : "13.4.1",
[debug] [35m[WD Proxy][39m       "sdkVersion" : "13.4"
[debug] [35m[WD Proxy][39m     },
[debug] [35m[WD Proxy][39m     "ios" : {
[debug] [35m[WD Proxy][39m       "simulatorVersion" : "13.4.1",
[debug] [35m[WD Proxy][39m       "ip" : "10.237.180.51"
[debug] [35m[WD Proxy][39m     },
[debug] [35m[WD Proxy][39m     "ready" : true,
[debug] [35m[WD Proxy][39m     "build" : {
[debug] [35m[WD Proxy][39m       "upgradedAt" : "1589311036316",
[debug] [35m[WD Proxy][39m       "time" : "May 14 2020 20:22:28",
[debug] [35m[WD Proxy][39m       "productBundleIdentifier" : "com.facebook.WebDriverAgentRunner"
[debug] [35m[WD Proxy][39m     }
[debug] [35m[WD Proxy][39m   },
[debug] [35m[WD Proxy][39m   "sessionId" : "A7350D18-1652-41B2-87D3-E22B5BE68D6D"
[debug] [35m[WD Proxy][39m }
[debug] [35m[WebDriverAgent][39m WebDriverAgent information:
[debug] [35m[WebDriverAgent][39m {
[debug] [35m[WebDriverAgent][39m   "message": "WebDriverAgent is ready to accept commands",
[debug] [35m[WebDriverAgent][39m   "state": "success",
[debug] [35m[WebDriverAgent][39m   "os": {
[debug] [35m[WebDriverAgent][39m     "name": "iOS",
[debug] [35m[WebDriverAgent][39m     "version": "13.4.1",
[debug] [35m[WebDriverAgent][39m     "sdkVersion": "13.4"
[debug] [35m[WebDriverAgent][39m   },
[debug] [35m[WebDriverAgent][39m   "ios": {
[debug] [35m[WebDriverAgent][39m     "simulatorVersion": "13.4.1",
[debug] [35m[WebDriverAgent][39m     "ip": "10.237.180.51"
[debug] [35m[WebDriverAgent][39m   },
[debug] [35m[WebDriverAgent][39m   "ready": true,
[debug] [35m[WebDriverAgent][39m   "build": {
[debug] [35m[WebDriverAgent][39m     "upgradedAt": "1589311036316",
[debug] [35m[WebDriverAgent][39m     "time": "May 14 2020 20:22:28",
[debug] [35m[WebDriverAgent][39m     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
[debug] [35m[WebDriverAgent][39m   }
[debug] [35m[WebDriverAgent][39m }
[debug] [35m[WebDriverAgent][39m WebDriverAgent successfully started after 7971ms
[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1589513541804 (20:32:21 GMT-0700 (Pacific Daylight Time))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[WD Proxy][39m Matched '/session' to command name 'createSession'
[debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:6025/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"org.kp.tpmg.preventivecare.beta","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[35m[WD Proxy][39m Got response with status 500: {"value":{"error":"session not created","message":"Failed to launch org.kp.tpmg.preventivecare.beta application","traceback":""},"sessionId":"A7350D18-1652-41B2-87D3-E22B5BE68D6D"}
[debug] [35m[W3C][39m Matched W3C error code 'session not created' to SessionNotCreatedError
[debug] [35m[XCUITest][39m Failed to create WDA session (A new session could not be created. Details: Failed to launch org.kp.tpmg.preventivecare.beta application). Retrying...
[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1589513789075 (20:36:29 GMT-0700 (Pacific Daylight Time))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[WD Proxy][39m Matched '/session' to command name 'createSession'
[debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:6025/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"org.kp.tpmg.preventivecare.beta","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[32m-[39m [90m- ms - -[39m
[35m[HTTP][39m [90m[39m
[35m[Appium][39m Received SIGINT - shutting down
[debug] [35m[Appium][39m There are no active sessions for cleanup

**Comment by deepeshpk** [comment] 2020-05-15 04:01
@mykola-mokhnach   : Could you plz take a look into the above logs

**Comment by KazuCocoa** [comment] 2020-05-15 05:05
> �[35m[WD Proxy]�[39m Got response with status 500: {"value":{"error":"session not created","message":"Failed to launch org.kp.tpmg.preventivecare.beta application","traceback":""},"sessionId":"A7350D18-1652-41B2-87D3-E22B5BE68D6D"}

The app failed to launch. (It seems WDA launched correctly)
Could you attach the full log with `showIOSLog` and `showXcodeLog` capabilities as GIST?

**Comment by mykola-mokhnach** [comment] 2020-05-15 05:27
Duplicate of https://github.com/appium/appium/issues/11197

Please replace the device under test, since this one has modified firmware, which does not support all features, that a stock Android firmware does.

**Comment by mykola-mokhnach** [comment] 2020-05-15 05:30
It also makes sense to set noReset to true if the app is expected to be already installed on the device

**Comment by deepeshpk** [comment] 2020-05-15 05:31
I am trying to get the xcode logs
'

**Comment by deepeshpk** [comment] 2020-05-15 06:57
Attached is the full log with showIOSLog showXcodeLog noReset value="true".

**Comment by deepeshpk** [comment] 2020-05-15 07:13
i was able to build both WebDriverAgentLib and WebDriverAgentRunner and successfully run the sh Scripts/bootStrap.sh.

**Comment by mykola-mokhnach** [comment] 2020-05-15 15:26
> Unable to launch org.kp.tpmg.preventivecare.beta because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user

It looks like you are trying to use an app, which is not signed with dev signature or the device itself is not provisioned.

**Comment by mykola-mokhnach** [comment] 2020-05-17 05:54
Closed as not an issue

**Closed by mykola-mokhnach** 2020-05-17 05:54 UTC
Labels: NeedsInfo, NotABug

**Comment by deepeshpk** [comment] 2020-05-17 15:04
@mykola-mokhnach @KazuCocoa 
One quick question to you : Verified the device provisioning profile and everything is looking good. But the device in in a server room and it is connected to internet via wired. (Hard Wired )..  And the iPhone is connected to internet via Wifi.   That might be the problem ???

**Comment by deepeshpk** [comment] 2020-05-17 15:06
Both are connected to the same network.  
For me there is no option to change the hard wired Mac mini to connect to same WiFi network as that of iPhone.

**Comment by mykola-mokhnach** [comment] 2020-05-17 15:14
Appium does not support automation of devices connected via WiFi

**Comment by mykola-mokhnach** [comment] 2020-05-17 15:15
> Verified the device provisioning profile 

Again, is this a development profile? If yes then no validation should be required for it

**Comment by deepeshpk** [comment] 2020-05-17 15:19
At my local, we do have Mac Mini and iPhone connected to XYZ network via wifi and have Catalina 10.15.4 Xcode 11.4.1 with Appium 1.15.1 setup and automation is working without any issue.  Could you please explain bit more your statement of  " Appium does not support automation of devices connected via WiFi"

I am using my local Appium server instance which is running at port 6020 for my execution.

**Comment by deepeshpk** [comment] 2020-05-17 15:20
> > Verified the device provisioning profile
> 
> Again, is this a development profile? If yes then no validation should be required for it

Yes, it is Development provisioning profile.

**Comment by deepeshpk** [comment] 2020-05-17 16:04
@mykola-mokhnach  @KazuCocoa 
[debug] [35m[WebDriverAgent][39m WebDriverAgent information:
[debug] [35m[WebDriverAgent][39m {
[debug] [35m[WebDriverAgent][39m   "message": "WebDriverAgent is ready to accept commands",
[debug] [35m[WebDriverAgent][39m   "state": "success",
[debug] [35m[WebDriverAgent][39m   "os": {
[debug] [35m[WebDriverAgent][39m     "name": "iOS",
[debug] [35m[WebDriverAgent][39m     "version": "13.4.1",
[debug] [35m[WebDriverAgent][39m     "sdkVersion": "13.4"
[debug] [35m[WebDriverAgent][39m   },
[debug] [35m[WebDriverAgent][39m   "ios": {
[debug] [35m[WebDriverAgent][39m     "simulatorVersion": "13.4.1",
[debug] [35m[WebDriverAgent][39m     "ip": "10.237.180.51"
[debug] [35m[WebDriverAgent][39m   },
[debug] [35m[WebDriverAgent][39m   "ready": true,
[debug] [35m[WebDriverAgent][39m   "build": {
[debug] [35m[WebDriverAgent][39m     "upgradedAt": "1589311036316",
[debug] [35m[WebDriverAgent][39m     "time": "May 14 2020 20:22:28",
[debug] [35m[WebDriverAgent][39m     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
[debug] [35m[WebDriverAgent][39m   }
[debug] [35m[WebDriverAgent][39m }


Does the above log says, the appium server was able to perform the handshake with the WDA at iPhone

**Comment by KazuCocoa** [comment] 2020-05-17 16:40
Appium/WDA itself had no issue. Your app under test was handled as invalid application (signature) by XCTest framework.

> [35m[IOSDeviceLog][39m May 14 23:04:03 Deepesh-Kumars-iPhone trustd[197] <Notice>: OCSPResponse: single response has extension(s).
[35m[IOSDeviceLog][39m May 14 23:04:03 Deepesh-Kumars-iPhone SpringBoard(FrontBoard)[58] <Notice>: [FBSystemService][0x4e8b] Open "org.kp.tpmg.preventivecare.beta" request from testmanagerd:883 failed with error: <NSError: 0x2828fdbf0; domain: FBSOpenApplicationServiceErrorDomain; code: 1 (RequestDenied); reason: "The request was denied by service delegate (SBMainWorkspace) for reason: Security ("Unable to launch org.kp.tpmg.preventivecare.beta because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user")."> {
[35m[IOSDeviceLog][39m     userInfo = {
[35m[IOSDeviceLog][39m         FBSOpenApplicationRequestID = 0x4e8b;
[35m[IOSDeviceLog][39m     }
[35m[IOSDeviceLog][39m     underlyingError = <NSError: 0x2828fd410; domain: FBSOpenApplicationErrorDomain; code: 3 (Security); reason: "Unable to launch org.kp.tpmg.preventivecare.beta because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user.">;
[35m[IOSDeviceLog][39m }
[35m[IOSDeviceLog][39m May 14 23:04:03 Deepesh-Kumars-iPhone testmanagerd(FrontBoardServices)[883] <Error>: [FBSSystemService][0x4e8b] Error handling open request for org.kp.tpmg.preventivecare.beta: <NSError: 0x103e11610; domain: FBSOpenApplicationServiceErrorDomain; code: 1 (RequestDenied); reason: "The request was denied by service delegate (SBMainWorkspace) for reason: Security ("Unable to launch org.kp.tpmg.preventivecare.beta because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user")."> {
[35m[IOSDeviceLog][39m     userInfo = {
[35m[IOSDeviceLog][39m         FBSOpenApplicationRequestID = 0x4e8b;
[35m[IOSDeviceLog][39m     }
[35m[IOSDeviceLog][39m     underlyingError = <NSError: 0x103e1cd70; domain: FBSOpenApplicationErrorDomain; code: 3 (Security); reason: "Unable to launch org.kp.tpmg.preventivecare.beta because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user.">;
[35m[IOSDeviceLog][39m }
[35m[IOSDeviceLog][39m May 14 23:04:03 Deepesh-Kumars-iPhone testmanagerd[883] <Error>: Error launching app: Error Domain=FBSOpenApplicationErrorDomain Code=3 "Unable to launch org.kp.tpmg.preventivecare.beta because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user." UserInfo={BSErrorCodeDescription=Security, NSLocalizedFailureReason=Unable to launch org.kp.tpmg.preventivecare.beta because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user.}
[35m[IOSDeviceLog][39m May 14 23:04:03 Deepesh-Kumars-iPhone assistant_service(libboringssl.dylib)[230] <Notice>: boringssl_session_handshake_incomplete(170) [C24.1:2][0x13fb54c60] Handshake incomplete: waiting for data to read [2]

**Comment by KazuCocoa** [comment] 2020-05-17 16:41
e.g. You should valid the profile via settings app on the iOS, but haven't
