### ISSUE TITLE
Appium 2.0 beta cannot start a session on some Windows OS machines

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#16489] opened 2022-02-23 08:09 UTC
## The problem
I am trying to start a test against new Appium Beta-25 version, with real Android device, on top of Windows 10 OS machine. 
The problem is that appium is showing an error on the appium server side as follow:
```
[HTTP] {"capabilities":{"firstMatch":[{"appium:noReset":true,"appium:fullReset":false,"appium:appPackage":"com.shs.wanderguard","appium:appActivity":"com.shs.wanderguard.activity.SplashActivity","appium:udid":"HGAGTKE7","appium:automationName":"UiAutomator2","appium:uiautomator2ServerInstallTimeout":"120000","appium:app":"C:\\workspace\\builds\\wg\\wg.apk","appium:newCommandTimeout":"500","appium:allowTestPackages":true,"appium:autoGrantPermissions":true,"appium:wdaLocalPort":"4723","platformName":"Android"}]},"desiredCapabilities":{"noReset":true,"fullReset":false,"appPackage":"com.shs.wanderguard","appActivity":"com.shs.wanderguard.activity.SplashActivity","udid":"HGAGTKE7","automationName":"UiAutomator2","uiautomator2ServerInstallTimeout":"120000","app":"C:\\workspace\\builds\\wg\\wg.apk","newCommandTimeout":"500","allowTestPackages":true,"autoGrantPermissions":true,"wdaLocalPort":"4723","platformName":"Android"}}
[debug] [HTTP] No route found for /wd/hub/session
[HTTP] <-- POST /wd/hub/session 404 1 ms - 211
[HTTP]
appiu[Appium] Received SIGINT - shutting down
[debug] [Appium] There are no active sessions for cleanup
[HTTP] Waiting until the server is closed
[HTTP] Received server close event

```

The problem is not happening on top of Mac OS machine.

I am starting the appium server with the following CLI command:
```
appium --base-path /wd/hub
```

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.25
* Last Appium version that did not exhibit the issue (if applicable): 1.22.1
* Desktop OS/version used to run Appium: Windows OS 10
* Node.js version (unless using Appium.app|exe): v16.13.2
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android OS 8
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
- Listing available drivers
√ Listing available drivers
- windows@2.0.1 [installed (NPM)]
- uiautomator2@2.0.3 [installed (NPM)]

## Link to Appium logs
https://github.com/bwomsm1/AppiumLogs/blob/master/appium_win.log

## Code To Reproduce Issue [ Good To Have ]
Just try to launch any empty test on Windows OS env

**Comment by KazuCocoa** [comment] 2022-02-23 08:21
Please attach the full appium log (as GIST). It has many info that helps us

**Comment by bwomsm1** [comment] 2022-02-23 08:26
> Please attach the full appium log (as GIST). It has many info that helps us

Attached.
https://github.com/bwomsm1/AppiumLogs/blob/master/appium_win.log

**Comment by KazuCocoa** [comment] 2022-02-23 08:39
as https://github.com/appium/appium/issues/15059#issuecomment-1046203178 , it looks like particular? Windows env appends `C:/Program Files/Git` for the base path

```
[35m[Appium][39m Welcome to Appium v2.0.0-beta.25
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { basePath: [32m'C:/Program Files/Git/wd/hub'[39m }
[35m[Appium][39m Attempting to load driver windows...
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723
[35m[Appium][39m Available drivers:
[35m[Appium][39m   - windows@2.0.1 (automationName 'Windows')
[35m[Appium][39m   - uiautomator2@2.0.3 (automationName 'UiAutomator2')
[35m[Appium][39m No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[debug] [35m[HTTP][39m Request idempotency key: aff38155-35b9-4703-8eaf-cc3ce3d48f35
```

while my local powershell on Win 10 shown as below.

```
(in node_modules/appium by npm install appium@next)
> node . --base-path /wd/hub
[Appium] Welcome to Appium v2.0.0-beta.25
[Appium] Non-default server args:
[Appium] {
[Appium]   basePath: '/wd/hub'
[Appium] }
[Appium] Attempting to load driver windows...
```

This is just a note.

**Comment by bwomsm1** [comment] 2022-02-23 08:43
@KazuCocoa yes, 
I cannot understand it my self too. <br>
Where this `C:/Program Files/Git` path is coming from? I am experiencing this problem on a 3 win OS machines.

**Comment by KazuCocoa** [comment] 2022-02-23 08:52
i have no idea for now since i'm not familiar with Win env. We need to dig the reason in.

The relevant code is:

https://github.com/appium/appium/blob/2.0/packages/base-driver/lib/express/server.js#L79
https://github.com/appium/appium/blob/83493941eee36aadbe571e877d4a2dfeb2824580/packages/base-driver/lib/express/server.js#L196-L211
`basePath` is the value of `--base-path`.

**Comment by bwomsm1** [comment] 2022-02-27 05:23
Hi Appium team,
Is there maybe a progress with that issue? Maybe more info from my side? 

(if you have instructions how I can run the server side in debug mode, I can look into it as well, I am less experienced with Javascript but I can try)

**Comment by KazuCocoa** [comment] 2022-02-27 10:21
Still i have no idea. powershell and command prompt in my Win 10 env worked well. The env was not development purpose, so I wonder some development stuff affected it while afaik 

Does your machine have environment variables etc about `C:/Program Files/Git` somewhere?

**Comment by KazuCocoa** [comment] 2022-02-27 18:38
You can run appium 2.0 from the source as https://github.com/appium/appium/blob/2.0/docs/en/contributing-to-appium/appium-from-source.md . Then, please make sure your branch is `2.0`.

For example, you can add `console.log`  in https://github.com/appium/appium/blob/2.0/packages/appium/lib/main.js#L221
```diff
    // otherwise parse from CLI
    preConfigParsedArgs = parser.parseArgs();
  }

+  console.log(preConfigParsedArgs);
```

Then, it prints the list of provided server arguments as below:

```
npm run build
./packages/appium/index.js --base-path /wd/hub

{
  subcommand: 'server',
  address: undefined,
  allow_cors: undefined,
  allow_insecure: undefined,
  basePath: '/wd/hub',
  callback_address: undefined,
  callback_port: undefined,
...
[Appium] Welcome to Appium v2.0.0-beta.25 (REV 2e15c85f447dad6897412fa75cdfb571a2d06620)
[Appium] Non-default server args:
[Appium] {
[Appium]   basePath: '/wd/hub'
[Appium] }
```

(Please tweak the path `/` for your win env.)
Maybe somewhere adds `C:/Program Files/Git/` in your environment.

**Comment by jlipps** [comment] 2022-03-02 13:18
Just another random thing to try: do you need to mayabe add quotes in Windows? like `appium --base-path="/wd/hub"` like maybe /wd/hub on its own is somehow getting converted from a local path to an absolute one by the shell?

**Comment by bwomsm1** [comment] 2022-03-02 17:22
@jlipps nope, just tried it, did not help...

(I am trying to find time to run appium server in debug)

**Comment by bwomsm1** [comment] 2022-03-02 17:30
But I think that we are almost there, 
when I tired `appium --base-path=\\/wd\\/hub`

My output log got improved and it prints:
`[Appium] { basePath: '\\/wd\\/hub' }`

Without the C:/Git....

**Comment by jlipps** [comment] 2022-03-03 13:22
which shell are you using?

**Comment by bwomsm1** [comment] 2022-03-03 13:24
> which shell are you using?

GitBash

**Comment by jlipps** [comment] 2022-03-03 14:58
it looks like this is the issue: https://github.com/moby/moby/issues/24029. so it's git-bash's fault. the workaround/solution is [here](https://stackoverflow.com/questions/7250130/how-to-stop-mingw-and-msys-from-mangling-path-names-given-at-the-command-line). i.e.

```
MSYS_NO_PATHCONV=1 appium --base-path="/wd/hub"
```

you may want to export that env var so it's always on for your terminal sessions.

closing this issue since we've confirmed this is a git bash issue, not an Appium one.

**Closed by jlipps** 2022-03-03 14:58 UTC
Labels: Windows, Help Needed
