### ISSUE TITLE
Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted"

### ISSUE THREAD

**Issue by abh7nav** [appium/appium#8438] opened 2017-05-12 08:43 UTC
## The problem

I am trying to start WebDriverAgent on my device but it always giving me below error:
Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted"

I tried following:
Reinstalled following :
	•	brew install node
	•	brew install npm
	•	brew install ideviceinstaller
	•	npm install -g appium
	•	npm install wd
	•	brew install ios-webkit-debug-proxy
	•	brew install --HEAD libimobiledevice
	•	brew install usbmuxd
	•	brew install carthage 
	•	npm install -g ios-deploy

Reinstalled XCode. 
Restarted device and system but none has helped.

I am using Appium 1.6.4, ipad mini with ios 10.3.1

I have check WebDriverAgent signing and it is correct. It do not show any issue. I have signed many times till now but this is issue has just popped up after upgrading to Appium 1.6.4

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium: Mac os Sierra
* Node.js version (unless using Appium.app|exe): node v7.10.0
* Mobile platform/version under test: ios 10.3.1
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

I am trying to start appium but it is giving error as below:
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2017-05-12 14:03:15.605 xcodebuild[26488:108818] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] 2017-05-12 14:03:15.304326+0530 XCTRunner[431:41592] Running tests...
[Xcode] 2017-05-12 14:03:15.603638+0530 XCTRunner[431:41611] Connection peer refused channel request for "dtxproxy:XCTestDriverInterface:XCTestManager_IDEInterface"; channel canceled <DTXChannel: 0x174092ac0>
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1494577995622 (14:03:15 GMT+0530 (IST))

## Link to Appium logs
Appium logs:
https://gist.github.com/abh7nav/aa3f55dcd4f922b94660e4727a73f5b0

XCode build logs
https://gist.github.com/abh7nav/6299f2c95569ca9aae20652917a54903

## Code To Reproduce Issue [ Good To Have ]

I am running `appium` command from terminal and then trying to open appium inspector from appium GUI. Same is happening correctly on other machine and same device.

I have check WebDriverAgent signing and it is correct. It do not show any issue.

**Comment by mykola-mokhnach** [comment] 2017-05-12 08:45
Closed as duplicate of https://github.com/appium/appium/issues/8417

**Closed by mykola-mokhnach** 2017-05-12 08:45 UTC

**Comment by abh7nav** [comment] 2017-05-12 08:49
@mykola-mokhnach thanks for your great response and close it as soon as possible as you are working as a bot to close issues out asap. It would also be helpful if the bot within yourself can post relevant comments which can help users like me to know about solution or at least reason to have some pointer. otherwise, you are a great BOT!!!

**Comment by mykola-mokhnach** [comment] 2017-05-12 08:55
Sorry for you being lazy to use search and check whether any similar issues have been already reported.

**Comment by abh7nav** [comment] 2017-05-12 09:08
I have one update. I have two ios 10.3.1 device. One works on my machine but other does not and same for my colleague the device working on my machine is not working for him and the one working for him is not working for me. Strange!!

**Comment by abh7nav** [comment] 2017-05-12 09:26
Resetting the device has worked as of now.

**Comment by PavithraNavaneeth** [comment] 2017-06-05 03:57
@abh7nav  Any other solution for this?
I get the same error even after restarting or resetting the device its the same issue.

**Comment by abh7nav** [comment] 2017-06-05 06:07
@PavithraNavaneeth  using latest appium has resolved the issue. I am no longer observing the issue. Also, try using 64 bit devices

**Comment by thejuskrishna** [comment] 2017-06-29 14:28
The same issue happening on my 10.2.1 device and appium 1.6.5
Appium v1.6.5 (REV 40e40975ebd3593d08c3f83de2546258f7ddf11d)

**Comment by pavanbachu0604** [comment] 2017-06-29 15:57
When i restarted my device, it started working normally.

On Thu, Jun 29, 2017 at 10:29 AM, Thejus Krishna <notifications@github.com>
wrote:

> The same issue happening on my 10.2.1 device and appium 1.6.5
> Appium v1.6.5 (REV 40e40975ebd3593d08c3f83de2546258f7ddf11d)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_appium_appium_issues_8438-23issuecomment-2D311984101&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=GrVyjk9esLjbV-UuEWevVPxUeLcsCbkcwb9nvBHhjgE&m=_saWsdVhajoj2giqaVqECt_yBVmSq2oIEP7N3Jk21jo&s=z4xnMlifQAl8Pq-iijvYsNH0dBqDhZMA1W3ihq_FdZk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AUPSxIonJ2Wkzzhw7NyYzK5ZtFXyDygfks5sI7TEgaJpZM4NZAKV&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=GrVyjk9esLjbV-UuEWevVPxUeLcsCbkcwb9nvBHhjgE&m=_saWsdVhajoj2giqaVqECt_yBVmSq2oIEP7N3Jk21jo&s=vzpdCr1djmEHiq10kXn7pRkMGYaSwb6CBGxhiJwklzA&e=>
> .
>



-- 
Thanks
Pavan Bachu

**Comment by thejuskrishna** [comment] 2017-06-29 16:27
I tried rebooting. But it is still the same. Do we need to upgrade to 10.3.2?

**Comment by Arun-AG** [comment] 2017-07-06 10:15
am also getting the same issue. "code =6 early unexpected error". I restarted my device as well as MAC . IOs 10.2.1 appium 1.65

**Comment by ggtasrif** [comment] 2017-07-12 07:23
I am also having the same issue with xcode 8.3.1, appium 1.6.5, iPhone 5S (10.1.1). After running the appium server it keep showing " Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}". Please someone help us out.

**Comment by jerzynowakowski** [comment] 2017-09-14 12:00
I have important discovery here 
while connecting iphone via hub - this is reproduced.
while connecting via mac native usb - no problem with connection. This worked for me

**Comment by PavithraNavaneeth** [comment] 2017-10-17 05:36
Hi,
Can anyone pinpoint the correct solution for this issue ? I am stuck up with this issue for few months now. Even after wiping everything multiple times and reinstalling - I keep ending up with same error. One of my colleague uses the same dev certificate and it works for him. Same setting, same configuration doesn't work for me and throws the below error:

command: xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=8e82ea984d9807b78b7e2b2f03c891bce1d5b039 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.1.1 -xcconfig /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/appium-config.xcconfig


Error:
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /var/containers/Bundle/Application/B554D04A-9B9B-4B98-9E95-29F89D2C10B8/WebDriverAgentRunner-Runner.app/XCTRunner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/B554D04A-9B9B-4B98-9E95-29F89D2C10B8/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/B554D04A-9B9B-4B98-9E95-29F89D2C10B8/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
	/private/var/containers/Bundle/Application/B554D04A-9B9B-4B98-9E95-29F89D2C10B8/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/B554D04A-9B9B-4B98-9E95-29F89D2C10B8/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
2017-10-17 16:27:15.676 xcodebuild[6035:138392] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **

Details:
Appium 1.7.1
Mac OS - 10.12.5
Xcode - 8.3.3
Device - iPhone 5c/IOS 10.1.1

Installed all the dependencies like Carthage, libimobiledevice, iso-deploy, bootstrap dependencies.
Added the XCTest framework to WebDriverLib - Target in Xcode. Deleted the derived data folder many times before building the project. Deleted the developer certificate, provisioning profiles and re added everything from scratch. But nothing works :-( 

Every post says it could be signing issue or different versions of Carthage. Since it is working in other Mac with same certificate - I doubt there is no signing issue. I ensured Carthage is installed in only one location (there is no .nvm).

**Comment by jerzynowakowski** [comment] 2017-10-17 05:50
@PavithraNavaneeth just my raw ideas:
1. I'm not sure whether you will be forced to use XCode 9 and upgrade your iphone to 11.0.3 (latest atm)
2. Try to connect to a native USB than use hubs. They are missing DC / Power sometimes despite connected and seems ok.
3. Clean the project first in xcode before running the command line. You need to have certificate accepted on iPhone in settings, otherwise you often have this error. So first run will fail, you need to accept the cert.
Hope above will help. Good luck!

**Comment by dmshantanu** [comment] 2017-11-22 02:08
I am also facing the same issue.
I followed following steps:
1]  I removed all the remnants from xcode using following command
sudo rm -rf ~/Library/Developer/Xcode/DerivedData/WebDriverAgent-*  
2] uninstall appium.   "npm uninstall -g appium"
3] Install appium 1.7.1:  "npm install -g appium@1.7.1"

This worked on one machine but when I tried it on another machine I am getting the same problem. Same setup steps do not give same result every time.

**Comment by jerzynowakowski** [comment] 2017-11-22 08:52
@dmshantanu 
To run on 9.1 xcode - you need a master webdriver to run it from appium.
Download it from web site as zip and unpack / substitute to appium webdriver folder, then try to compile. In my case it helped with 9.1 xcode + see my previous post here on power supply / reboot: https://github.com/appium/appium/issues/8438#issuecomment-337124965

**Comment by eliezercazares** [comment] 2018-05-31 19:15
Mykola enjoys closing tickets without further info

**Comment by Jiurong-Yang** [comment] 2018-08-10 23:52
Another update for anyone having issues with this. I was running my command line appium server on my mac mini through a SSH tunnel and it was throwing this error. But when I run the server in a terminal on the mac mini this issues went away. I feel like I need to start sacrificing goats to avoid issues with WebDriverAgent.
