### ISSUE TITLE
Appium :: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session

### ISSUE THREAD

**Issue by kiranhungama1** [appium/appium#13701] opened 2019-12-11 11:46 UTC
1. Updated to MacOS catalina
 2. Updated appium desktop 1.15.1
 3. Xcode 11.2.1
4. java client - 7.3.0
5. Testng 7.0.0 

Below is the exception on the appium server

>[Appium] Appium v1.15.1 creating new XCUITestDriver (v2.133.1) session [Appium] Applying relaxed security to 'XCUITestDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided [BaseDriver] Creating session with W3C capabilities: { [BaseDriver] "alwaysMatch": { [BaseDriver] "platformName": "ios", [BaseDriver] "appium:automationName": "XCUITest", [BaseDriver] "appium:bundleId": "ZZZZZZZZZZZZZZZZZZZZZZZZZZZ", [BaseDriver] "appium:deviceName": "iPhone7_Hml", [BaseDriver] "appium:newCommandTimeout": 160, [BaseDriver] "appium:noReset": true, [BaseDriver] "appium:platformVersion": "13.2", [BaseDriver] "appium:udid": "89c4364185f2f1dba22992faaae1179e32a4eb41", [BaseDriver] "appium:xcodeOrgId": "XXXXXXXXXXXXXXXXXXXX", [BaseDriver] "appium:xcodeSigningId": "iPhone Developer" [BaseDriver] }, [BaseDriver] "firstMatch": [ [BaseDriver] {} [BaseDriver] ] [BaseDriver] } [BaseDriver] Session created with session id: ee9f8be2-da63-44d3-9f8a-0d433ea9f2f8 [XCUITest] Current user: 'Yayati' [XCUITest] Available devices: 89c4364185f2f1dba22992faaae1179e32a4eb41, ccfe00fee87aa9140b71a98eedc18c88a214121d, 3bdf2f4113dfccd88c17e26b56dc2e03b53f2812, 9f993665a8a2abf6b22fec56e576487a4b40a818 [XCUITest] Creating iDevice object with udid '89c4364185f2f1dba22992faaae1179e32a4eb41' [XCUITest] Determining device to run tests on: udid: '89c4364185f2f1dba22992faaae1179e32a4eb41', real device: true [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1575638568501 (18:52:48 GMT+0530 (IST)) [BaseDriver] Event 'appConfigured' logged at 1575638568501 (18:52:48 GMT+0530 (IST)) [BaseDriver] Event 'resetStarted' logged at 1575638568501 (18:52:48 GMT+0530 (IST)) [XCUITest] Reset: fullReset not set. Leaving as is [BaseDriver] Event 'resetComplete' logged at 1575638568501 (18:52:48 GMT+0530 (IST)) [XCUITest] Continuing without capturing device logs: Connection was refused to port 53356 [XCUITest] Setting up real device [XCUITest] Error: Connection was refused to port 53359 [XCUITest] at Usbmux.connect (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-device/lib/usbmux/index.js:183:13) [DevCon Factory] Releasing connections for 89c4364185f2f1dba22992faaae1179e32a4eb41 device on any port number [DevCon Factory] No cached connections have been found [BaseDriver] Event 'newSessionStarted' logged at 1575638608946 (18:53:28 GMT+0530 (IST)) [W3C] Encountered internal error running command: Error: Connection was refused to port 53359 [W3C] at Usbmux.connect (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-device/lib/usbmux/index.js:183:13) [HTTP] <-- POST /wd/hub/session 500 40502 ms - 702

NOTE : Before the update it was working properly.

 Below are the logs that I Get on eclipse console ::
    
    FAILED CONFIGURATION: @BeforeTest beforeTest
    org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Connection was refused to port 53359
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
    System info: host: 'M16IMACHDMGG7J.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.1', java.version: '12.0.1'
    Driver info: driver.version: IOSDriver
    remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Connection was refused to port 53359
        at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
        at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:388:37)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
    System info: host: 'M16IMACHDMGG7J.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.1', java.version: '12.0.1'
    Driver info: driver.version: IOSDriver
    	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
    	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
    	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
    	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
    	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
    	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
    	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
    	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
    	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:323)
    	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
    	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
    	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:86)
    	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:96)
    	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:92)
    	at utils.Capability.capability_phone(Capability.java:53)
    	at testcases.search.beforeTest(search.java:74)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
    	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
    	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
    	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
    	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
    	at org.testng.TestRunner.beforeRun(TestRunner.java:529)
    	at org.testng.TestRunner.run(TestRunner.java:497)
    	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
    	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
    	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
    	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
    	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
    	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
    	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
    	at org.testng.TestNG.runSuites(TestNG.java:1049)
    	at org.testng.TestNG.run(TestNG.java:1017)
    	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
    	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
    	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
    Caused by: java.lang.reflect.InvocationTargetException
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
    	... 39 more
    Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Connection was refused to port 53359
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
    System info: host: 'M16IMACHDMGG7J.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.1', java.version: '12.0.1'
    Driver info: driver.version: IOSDriver
    remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Connection was refused to port 53359
        at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
        at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:388:37)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
    	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
    	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
    	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
    	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
    	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
    	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
    	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
    	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
    	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
    	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
    	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
    	... 44 more

---

    Capability which I am using are as follows :
    
     public static IOSDriver capability_phone() throws MalformedURLException {
     final String URL_STRING = "http://0.0.0.0:4723/wd/hub";
     url = new URL(URL_STRING);
    DesiredCapabilities cap = new DesiredCapabilities();
    cap.setCapability("deviceName","iPhone7_Hml");
    cap.setCapability("udid","89c4364185f2f1dba22992faaae1179e32a4eb41");
    cap.setCapability("platformVersion","13.2");
    cap.setCapability("platformName","IOS");
    cap.setCapability("automationName", "XCUITest");
    cap.setCapability("bundleId","com.hungama.myplay");
    cap.setCapability("noReset",true);
    cap.setCapability("xcodeSigningId", "iPhone Developer");
     cap.setCapability("xcodeOrgId", "XXXXXXXXXXXXXXXXXXXX");
     cap.setCapability("newCommandTimeout", 160);
     we = new IOSDriver(url, cap);
     we.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
    System.out.println(" ~~~ !!! Setting the capabilities !!! ~~~ ");
     return we;
        	}

-----------------------------

[XCUITest] Continuing without capturing device logs: Connection was refused to port 57483
[XCUITest] Setting up real device
[XCUITest] Error: Connection was refused to port 57486
[XCUITest]     at Usbmux.connect (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-device/lib/usbmux/index.js:183:13)
[DevCon Factory] Releasing connections for f29645da08dedad0760f2efa2e451949ea4124d2 device on any port number
[DevCon Factory] No cached connections have been found
[BaseDriver] Event 'newSessionStarted' logged at 1576053574827 (14:09:34 GMT+0530 (IST))
[W3C] Encountered internal error running command: Error: Connection was refused to port 57486
[W3C]     at Usbmux.connect (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-device/lib/usbmux/index.js:183:13)
[HTTP] <-- POST /wd/hub/session 500 80492 ms - 702

**Comment by kiranhungama1** [comment] 2019-12-11 11:57
Log from Appium server : 

[W3C] Calling AppiumDriver.createSession() with args: [{"noReset":true,"xcodeOrgId":"S2TS234264","bundleId":"com.hungama.myplay","deviceName":"iPhone 7","xcodeSigningId":"iPhone Developer","waitForQuiescence":false,"wdaLaunchTimeout":5000,"newCommandTimeout":160,"platformVersion":"12.1","automationName":"XCUITest","platformName":"IOS","udid":"f29645da08dedad0760f2efa2e451949ea4124d2"},null,{"firstMatch":[{"appium:automationName":"XCUITest","appium:bundleId":"com.hungama.myplay","appium:deviceName":"iPhone 7","appium:newCommandTimeout":160,"appium:noReset":true,"platformName":"ios","appium:platformVersion":"12.1","appium:udid":"f29645da08dedad0760f2efa2e451949ea4124d2","waitForQuiescence":false,"appium:wdaLaunchTimeout":5000,"appium:xcodeOrgId":"S2TS234264","appium:xcodeSigningId":"iPhone Developer"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1576065129147 (17:22:09 GMT+0530 (IST))
[BaseDriver] The capabilities ["waitForQuiescence"] are not standard capabilities and should have an extension prefix
[Appium] Appium v1.15.1 creating new XCUITestDriver (v2.133.1) session
[Appium] Applying relaxed security to 'XCUITestDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[BaseDriver] Creating session with W3C capabilities: {
[BaseDriver]   "alwaysMatch": {
[BaseDriver]     "platformName": "ios",
[BaseDriver]     "appium:waitForQuiescence": false,
[BaseDriver]     "appium:automationName": "XCUITest",
[BaseDriver]     "appium:bundleId": "com.hungama.myplay",
[BaseDriver]     "appium:deviceName": "iPhone 7",
[BaseDriver]     "appium:newCommandTimeout": 160,
[BaseDriver]     "appium:noReset": true,
[BaseDriver]     "appium:platformVersion": "12.1",
[BaseDriver]     "appium:udid": "f29645da08dedad0760f2efa2e451949ea4124d2",
[BaseDriver]     "appium:wdaLaunchTimeout": 5000,
[BaseDriver]     "appium:xcodeOrgId": "S2TS234264",
[BaseDriver]     "appium:xcodeSigningId": "iPhone Developer"
[BaseDriver]   },
[BaseDriver]   "firstMatch": [
[BaseDriver]     {}
[BaseDriver]   ]
[BaseDriver] }
[BaseDriver] Session created with session id: d8c545f3-d651-4828-a420-31daedcdd38b
[XCUITest] Current user: 'Yayati'
[XCUITest] Available devices: 2a7f9e3738f59eb053c58a85e2c72f70b6c8ad20, 3bdf2f4113dfccd88c17e26b56dc2e03b53f2812, f29645da08dedad0760f2efa2e451949ea4124d2
[XCUITest] Creating iDevice object with udid 'f29645da08dedad0760f2efa2e451949ea4124d2'
[XCUITest] Determining device to run tests on: udid: 'f29645da08dedad0760f2efa2e451949ea4124d2', real device: true
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1576065129213 (17:22:09 GMT+0530 (IST))
[BaseDriver] Event 'appConfigured' logged at 1576065129213 (17:22:09 GMT+0530 (IST))
[BaseDriver] Event 'resetStarted' logged at 1576065129213 (17:22:09 GMT+0530 (IST))
[XCUITest] Reset: fullReset not set. Leaving as is
[BaseDriver] Event 'resetComplete' logged at 1576065129213 (17:22:09 GMT+0530 (IST))
[XCUITest] Continuing without capturing device logs: Connection was refused to port 49693
[XCUITest] Setting up real device
[XCUITest] Error: Connection was refused to port 49696
[XCUITest]     at Usbmux.connect (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-device/lib/usbmux/index.js:183:13)
[DevCon Factory] Releasing connections for f29645da08dedad0760f2efa2e451949ea4124d2 device on any port number
[DevCon Factory] No cached connections have been found
[BaseDriver] Event 'newSessionStarted' logged at 1576065157180 (17:22:37 GMT+0530 (IST))
[W3C] Encountered internal error running command: Error: Connection was refused to port 49696
[W3C]     at Usbmux.connect (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-device/lib/usbmux/index.js:183:13)
[HTTP] <-- POST /wd/hub/session 500 28034 ms - 702

**Comment by mykola-mokhnach** [comment] 2019-12-11 13:38
cc @umutuzgur

**Comment by kiranhungama1** [comment] 2019-12-16 14:19
any suggestions ?? I am still facing the same issue...

**Comment by mykola-mokhnach** [comment] 2019-12-18 06:32
I see you have `noReset` option set to `true`. Are you sure the WDA server is running and is listening on the device under test?

**Comment by kiranhungama1** [comment] 2019-12-18 10:33
Yes...WDA is running as this error comes randomly during the execution of testcases...
After this error everything fails...
Before updating everything was working fine. I have updated the MAC to catalina. Appium was also updated to 1.15.1 from 1.13

**Comment by mykola-mokhnach** [comment] 2019-12-18 10:40
> Yes...WDA is running as this error comes randomly during the execution of testcases...

How do you know it is running? Are you able to manually get the response on that port while connecting to the device manually?

**Comment by kiranhungama1** [comment] 2019-12-18 10:52
How to check that thing manually ?? 
I usually run  the test suite...It has 150 plus testcases... After successful execution of some testcases(10 to 15), it throws this error...

**Comment by kiranhungama1** [comment] 2020-01-02 09:56
[AppiumLogsError.txt](https://github.com/appium/appium/files/4015462/AppiumLogsError.txt)

Latest logs from Run....It works fine & "Usbmux.connect" error comes up...after some excecutions...
I have another Mac running the same code but Mac OS(mojave & appium desktop version 1.13.0).
The code & testcases works perfect on the second mac.

**Comment by yashaka** [comment] 2020-02-04 16:57
same issue on my side:
catalina & appium desktop 1.15.1

same behaviour - sometimes passes, sometimes fails...

Session can be created manually through Appium Desktop. 

I recalled that also had changed version of Appium from 1.16 to 1.15.1. Thought that wda on the phonne was somehow broken... So reinstalled it from 1.15.1 sources, but... It did not help :(

Rebooting Mac OS did not help... It helps just for the first run, if last run failed before reboot.

**Comment by fousiak** [comment] 2020-05-09 15:02
I am also facing the same issue. Is there any solution for this? I am using latest appium version 1.17.1 & MAc OS Catalina(10.15.4)

**Comment by meenalj27** [comment] 2020-07-28 19:09
Hello , currently I am also working on the appium just started learning . I have installed appium version - 1.17.1 on my MAC OS Catalina 10.15.3. As I have resolved may errors currently I am facing the above issue and unable to resolve this. Can any one please help me in this its been a while I am stuck on this issue.

**Comment by huynhphuong10284** [comment] 2020-11-14 03:06
I got the same issue:
[Appium] Welcome to Appium v1.18.3
[Appium] Non-default server args:
[Appium]   port: 46435
[Appium]   bootstrapPort: 40468
[Appium]   sessionOverride: true
[Appium]   logFile: /home/phuong/Documents/phuong/test/appium.log
[Appium]   udid: ce0116018b572b2a03
[Appium] Deprecated server args:
[Appium]   -U,--udid => --default-capabilities '{"udid":"ce0116018b572b2a03"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   udid: ce0116018b572b2a03
[Appium] Appium REST http interface listener started on 0.0.0.0:46435

org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: The file at '/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' does not exist or is not accessible
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'phuong', ip: '192.168.1.100', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1127.19.1.el7.x86_64', java.version: '1.8.0_262'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: The file at '/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' does not exist or is not accessible
    at getResponseForW3CError (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:381:37)
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'phuong', ip: '192.168.1.100', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1127.19.1.el7.x86_64', java.version: '1.8.0_262'

**Comment by kmohanavelu** [comment] 2020-12-18 11:27
I am also getting the same issue. Please find the exception stack trace below,

org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: Appium Server Error due to some reason please check Hub/AppiumStdErr logs for more Information (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 31.28 seconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
Driver info: driver.version: Driver
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
Driver info: driver.version: Driver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:90)
	at hid.seos.util.Driver.setPcloudyIOSCapabilties(Driver.java:120)
	at hid.seos.util.Driver.initalizeDriver(Driver.java:53)
	at hid.seos.util.UITest.executeBeforeTest(UITest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
	at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
	at org.testng.TestRunner.beforeRun(TestRunner.java:609)
	at org.testng.TestRunner.run(TestRunner.java:580)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 35 more
Caused by: org.openqa.selenium.SessionNotCreatedException: Appium Server Error due to some reason please check Hub/AppiumStdErr logs for more Information (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 31.28 seconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
Driver info: driver.version: Driver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$errorHandler$0(JsonWireProtocolResponse.java:54)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 40 more

**Comment by amankhanp** [comment] 2020-12-28 07:28
I'm also facing the same issue with android.

**Comment by satishkumar96** [comment] 2022-12-15 15:52
I'm also facing the same issue with android.

`
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\SatishKumar\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.27.0.apk'. Original error: Could not find 'apksigner.jar' in ["E:\\android-sdk\\platform-tools\\apksigner.jar","E:\\android-sdk\\emulator\\apksigner.jar","E:\\android-sdk\\cmdline-tools\\latest\\bin\\apksigner.jar","E:\\android-sdk\\tools\\apksigner.jar","E:\\android-sdk\\tools\\bin\\apksigner.jar","E:\\android-sdk\\apksigner.jar"]. Do you have Android Build Tools installed at 'E:\android-sdk'? 
Host info: host: 'SATISHK', ip: '192.168.1.34'
Build info: version: '4.7.2', revision: '4d4020c3b7'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [null, newSession {capabilities=[{appium:appActivity=com.android.calculator2.Calculator, appium:appPackage=com.coloros.calculator, appium:deviceName=Realme X7 Max, platformName=ANDROID, appium:platformVersion=12, appium:udid=YTYTDECI99WC4DIF}], desiredCapabilities=Capabilities {appActivity: com.android.calculator2.Cal..., appPackage: com.coloros.calculator, deviceName: Realme X7 Max, platformName: ANDROID, platformVersion: 12, udid: YTYTDECI99WC4DIF}}]
Capabilities {}
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:148)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:133)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:194)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:262)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:535)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:229)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:156)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:80)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:92)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:117)`

**Comment by mykola-mokhnach** [comment] 2023-10-19 06:40
Closed as obsolete

**Closed by mykola-mokhnach** 2023-10-19 06:40 UTC
Labels: XCUITest

**Comment by sidneydemoraes** [comment] 2024-03-22 12:37
@mykola-mokhnach how was it completed? Which version fixed the issue? Could you provide more details please? It will help us not opening new issues.
