### ISSUE TITLE
does not have permission android.permission.CLEAR_APP_USER_DATA to clear data of package com.linkedin.android

### ISSUE THREAD

**Issue by i24Seven** [appium/appium#11949] opened 2019-01-05 17:03 UTC
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by i24Seven** [comment] 2019-01-05 17:05
[W3C] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'D\:\\APPIUMTOOLS\\ANDROIDSDK\\platform-tools\\adb.exe -P 5037 -s a0fde0547d94 shell pm clear com.linkedin.android' exited with code 1'; Stderr: 'Error: java.lang.SecurityException: PID 26686 does not have permission android.permission.CLEAR_APP_USER_DATA to clear data of package com.linkedin.android'; Code: '1'

**Comment by mykola-mokhnach** [comment] 2019-01-05 21:03
Please fill out the issue reporting from properly

**Comment by mykola-mokhnach** [comment] 2019-01-06 10:04
On some phone models (many chinese phones fall into this category) it is impossible to clear application data via adb. The only way to execute an app there is to use `noReset` option, which skips data cleanup.

Closed as duplicate of https://github.com/appium/appium/issues/9807

**Closed by mykola-mokhnach** 2019-01-06 10:04 UTC
Labels: NeedsInfo
