### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: Could not sign with default certificate. Original error Command 

### ISSUE THREAD

**Issue by vladbelo** [appium/appium#9465] opened 2017-10-17 00:15 UTC
## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: MacSierra 
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test:
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Appium.app

## Details

{
	"appName" : "dlr",
	"platform" : "Android",
	"platformVersion" : "6.0",
	"deviceName" : "Android Emulator",
	"seleniumUrl" : "http://0.0.0.0:4723",
	"environment" : "",
	"mobileApplicationPath" : "/Users//Downloads/",
	
}

## Link to Appium logs

[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users//Downloads/VVV.apk","appPackage":"","noReset":"false","platformVersion":"6.0","appWaitActivity":"com.disney.wdpro.park.activities.TutorialSecondLevelActivity , .FinderActivity","automationName":"uiautomator2","platformName":"Android","deviceName":"Android Emulator","fullReset":true,"autoAcceptAlerts":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users//Downloads/vvv.apk","appPackage":"vvv","noReset":"false","platformVersion":"6.0","appWaitActivity":"com.disney.wdpro.park.activities.TutorialSecondLevelActivity , com.disney.wdpro.park.activities.FinderActivity","automationName":"uiautomator2","platformName":"Android","deviceName":"Android Emulator","fullReset":true,"autoAcceptAlerts":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1508199177213 (17:12:57 GMT-0700 (PDT))
[Appium] Creating new AndroidUiautomator2Driver (v0.6.5) session
[Appium] Capabilities:
[Appium]   app: '/Users//Downloads/k'
[Appium]   appPackage: 'com.disney.wdpro.dlr'
[Appium]   noReset: 'false'
[Appium]   platformVersion: '6.0'
[Appium]   appWaitActivity: '.activities.TutorialSecondLevelActivity , com.disney.wdpro.park.activities.FinderActivity'
[Appium]   automationName: 'uiautomator2'
[Appium]   platformName: 'Android'
[Appium]   deviceName: 'Android Emulator'
[Appium]   fullReset: true
[Appium]   autoAcceptAlerts: true
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: autoAcceptAlerts.
[BaseDriver] Session created with session id: 710737b9-328c-4d12-a52f-308fecc1b9e5
[BaseDriver] Using local app '/Users/vladimir.belonenko/Downloads/DLR.apk'
[UiAutomator2] Checking whether app is actually present
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_144
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/vladimir.belonenko/Library/Android/sdk/platform-tools/adb
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android '6.0'
[ADB] Setting device id to emulator-5554
[ADB] Getting device platform version
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/vladimir.belonenko/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.release"]
[ADB] Current device property 'ro.build.version.release': 6.0
[AndroidDriver] Using device: emulator-5554
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/vladimir.belonenko/Library/Android/sdk/platform-tools/adb
[ADB] Setting device id to emulator-5554
[AndroidDriver] Parsing package and activity from app manifest
[ADB] Checking whether aapt is present
[ADB] Using aapt from /Users/vladimir.belonenko/Library/Android/sdk/build-tools/26.0.1/aapt
[ADB] Extracting package and launch activity from manifest
[ADB] badging package: com.disney.wdpro.dlr
[ADB] badging act: com.disney.wdpro.park.activities.LoaderActivity
[AndroidDriver] Parsed package and activity are: com.disney.wdpro.dlr/com.disney.wdpro.park.activities.LoaderActivity
[ADB] Getting device platform version
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/vladimir.belonenko/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.release"]
[ADB] Current device property 'ro.build.version.release': 6.0
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/vladimir.belonenko/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","wm","size"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/vladimir.belonenko/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.product.model"]
[ADB] Current device property 'ro.product.model': Android SDK built for x86
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/vladimir.belonenko/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.product.manufacturer"]
[ADB] Current device property 'ro.product.manufacturer': unknown
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/vladimir.belonenko/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.uiautomator2.server"]
[ADB] Checking whether aapt is present
[ADB] Using aapt from /Users/vladimir.belonenko/Library/Android/sdk/build-tools/26.0.1/aapt
[ADB] Getting install status for io.appium.uiautomator2.server
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/vladimir.belonenko/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","packages","io.appium.uiautomator2.server"]
[ADB] App is not installed
[ADB] Getting install status for io.appium.uiautomator2.server.test
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/vladimir.belonenko/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","packages","io.appium.uiautomator2.server.test"]
[ADB] App is not installed
[ADB] Checking app cert for /private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.8.apk.
[ADB] App not signed with debug cert.
[ADB] Resigning apk.
[ADB] Error: Could not sign with default certificate. Original error Command '/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java -jar /private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/jars/sign.jar /private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.8.apk --override' exited with code 1
    at Object.wrappedLogger.errorAndThrow (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:63:13)
    at ADB.callee$0$0$ (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:25:9)
    at tryCatch (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Could not sign with default certificate. Original error Command '/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java -jar /private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/jars/sign.jar /private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.8.apk --override' exited with code 1
    at Object.wrappedLogger.errorAndThrow (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:63:13)
    at ADB.callee$0$0$ (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:25:9)
    at tryCatch (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/vladimir.belonenko/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","com.disney.wdpro.dlr"]
[UiAutomator2] Capability 'fullReset' set to 'true', Uninstalling 'com.disney.wdpro.dlr'
[ADB] Uninstalling com.disney.wdpro.dlr
[ADB] Getting install status for com.disney.wdpro.dlr
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/vladimir.belonenko/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","packages","com.disney.wdpro.dlr"]
[ADB] App is not installed
[ADB] com.disney.wdpro.dlr was not uninstalled, because it was not present on the device
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running '/Users/vladimir.belonenko/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","forward","--remove","tcp:8200"]
[ADB] Running '/Users/vladimir.belonenko/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","forward","--remove","tcp:8200"]
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/Users/vladimir.belonenko/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[MJSONWP] Encountered internal error running command: Error: Could not sign with default certificate. Original error Command '/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java -jar /private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/jars/sign.jar /private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.8.apk --override' exited with code 1
    at Object.wrappedLogger.errorAndThrow (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:63:13)
    at ADB.callee$0$0$ (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:25:9)
    at tryCatch (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/3y/wkrdg6rd36338b729hz54xd8gvkb1n/T/AppTranslocation/3E801643-8FCB-4E29-BA81-044D7788D337/d/Appium-4.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 2567 ms - 778 

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2017-10-17 06:21
Do you execute Appium.app into from /Applications folder?

**Comment by Shahunks** [comment] 2017-10-17 09:56
@mykola-mokhnach - i am facing the same issue

**Comment by vladbelo** [comment] 2017-10-17 14:46
I click on appium icon on desktop thats it.

**Comment by mykola-mokhnach** [comment] 2017-10-17 14:56
You must copy Appium.app to /Applications folder and run it from there.
Closed as not a bug.

**Closed by mykola-mokhnach** 2017-10-17 14:56 UTC
Labels: NotABug

**Comment by vladbelo** [comment] 2017-10-17 15:27
Thanks a lot it worked.
