### ISSUE TITLE
Driver.Manage().Window.Size doesn't change when rotating device

### ISSUE THREAD

**Issue by bart-tricentis** [appium/appium#11656] opened 2018-11-08 14:05 UTC
## The problem

When calling Driver.Manage().Window.Size before and after a screen rotation (doesn't matter if physical action or from code) returns the same value. Whereas in the past the values for height and width were inverted 

## Environment

* Appium version: 1.9.2-beta
* Last Appium version that did not exhibit the issue: 1.8.0
* Desktop OS/version used to run Appium: Windows and Mac
* Node.js version (unless using Appium.app|exe): 7.7.3
* Mobile platform/version under test: Android 
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Appium CLI

## Code To Reproduce Issue [ Good To Have ]

driver = new AndroidDriver<IWebElement>(AndroidServerUri, capabilities);

var size1 = driver.Manage().Window.Size;

driver.Orientation = ScreenOrientation.Landscape;

var size2 = driver.Manage().Window.Size;

if (size1 == size2) {
    Console.WriteLine("nope");
}

**Comment by bart-tricentis** [comment] 2018-11-09 06:41
Here you go
[logs.txt](https://github.com/appium/appium/files/2564852/logs.txt)

**Comment by mykola-mokhnach** [comment] 2018-11-09 11:02
I don't observe any significant changes in the code since 1.8.0
Can you provide the log from the version which worked?

**Comment by mykola-mokhnach** [comment] 2018-11-09 11:44
I see what the problem is now. Will fix it soon. Thanks

**Comment by mykola-mokhnach** [comment] 2018-11-10 08:53
The fix has been published in appium@beta

**Closed by mykola-mokhnach** 2018-11-10 08:53 UTC
Labels: Bug, UIAutomator2
