### ISSUE TITLE
[Android, Hybrid-app, Real Device] Interacting with dismissed web view causes Appium server to hang

### ISSUE THREAD

**Issue by SirApropos** [appium/appium#4573] opened 2015-02-20 20:07 UTC
We have a hybrid app. At some point in the flow, it exits the webview. Unfortunately, driver.getContextHandles() still returns that the web view is available. However, attempting to interact with the web view (in this case, by finding an element), it causes the appium server to silently hang. It still responds to status when hooked up to a grid, but it accepts no new commands and never causes cleanup from command timeout. No error is ever displayed. It just makes the device completely unavailable until the appium server is restarted.

Platform: android
automationName: appium
Device: Samsung Galaxy S5 (Android 4.4.4), real device
Client: io.appium java-client 2.1
Appium version: 1.3.4
Selenium version: 2.44.0

**Comment by SirApropos** [comment] 2015-02-20 20:28
It may be worth noting that Selendroid properly returns the available contexts and also doesn't cause the server to hang if attempting to interact with the unavailable context.

**Comment by imurchie** [comment] 2015-03-09 18:17
Sorry for the delay. Can you provide the Appium server logs for this?

**Comment by SirApropos** [comment] 2015-03-09 22:24
Doesn't look like I can attach a log file, so here's a pastebin:
http://pastebin.com/MMdbcFda

At line 500 is where it presses the back button (exiting the web view).

Line 511 is where we try to find elements with class 'invalid' (still in the webview context). The driver never returns from this command. Our timeout is 30 seconds, but you can see that the driver never exits/is cleaned up. It continues responding to status but does not respond to any other commands.

**Comment by imurchie** [comment] 2015-03-09 22:39
Seeing this log, this is a duplicate of #4429. Closing in lieu of that bug that is in the next milestone.

**Closed by imurchie** 2015-03-09 22:39 UTC
Labels: NeedsTriage

**Comment by sourabhjain2208** [comment] 2015-04-07 06:47
Easy way to reproduce it would be 

1. Switch from Native view to Webview
2. From Webview switch to NativeView.
3. Switch  to webview from NativeView and now Appium won't respond further.
