### ISSUE TITLE
How to  deal with permissions when use Android 8.0.0 to run

### ISSUE THREAD

**Issue by Hanson889** [appium/appium#12696] opened 2019-05-27 08:42 UTC
## The problem

when use android 8.0.0 to run test case, it will prompt "io.appium.settings is already running. There is no need to reset its permissions."
## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Desktop
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: android 8.0.0
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"Android"}},"desiredCapabilities":{"platformName":"Android","automationName":"UiAutomator2","platformVersion":"8.0.0","deviceName":"f29b3cab","appPackage":"com.juzix.wallet","appActivity":"component.ui.view.SplashActivity","newCommandTimeout":"2000"}}
[W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","automationName":"UiAutomator2","platformVersion":"8.0.0","deviceName":"f29b3cab","appPackage":"com.juzix.wallet","appActivity":"component.ui.view.SplashActivity","newCommandTimeout":"2000"},null,{"firstMatch":[{}],"alwaysMatch":{"platformName":"Android"}}]
[BaseDriver] Event 'newSessionRequested' logged at 1558945662166 (16:27:42 GMT+0800 (中国标准时间))
[Appium] Could not parse W3C capabilities: 'deviceName' can't be blank
[Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
[BaseDriver] The capabilities ["automationName","platformVersion","deviceName","appPackage","appActivity","newCommandTimeout"] are not standard capabilities and should have an extension prefix
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[Appium] Creating new AndroidUiautomator2Driver (v1.29.1) session
[Appium] Capabilities:
[Appium]   platformName: Android
[Appium]   automationName: UiAutomator2
[Appium]   platformVersion: 8.0.0
[Appium]   deviceName: f29b3cab
[Appium]   appPackage: com.juzix.wallet
[Appium]   appActivity: component.ui.view.SplashActivity
[Appium]   newCommandTimeout: 2000
[BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"platformName":"Android","... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[BaseDriver] Capability 'newCommandTimeout' changed from string ('2000') to integer (2000). This may cause unexpected behavior
[BaseDriver] Session created with session id: ddcc91e0-33c9-4687-ab8d-df4cc9655766
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android '8.0.0'
[ADB] Setting device id to f29b3cab
[ADB] Getting device platform version
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 8.0.0
[AndroidDriver] Using device: f29b3cab
[ADB] Setting device id to f29b3cab
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 26
[ADB] Device API level: 26
[AndroidDriver] No app sent in, not parsing package/activity
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab wait-for-device'
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell dumpsys package io.appium.settings'
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.14.0' >= '2.14.0')
[ADB] There is no need to install/upgrade 'C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell 'pgrep --help; echo $?''
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell pgrep \^appium\\.settings\$'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell appops set io.appium.settings android\:mock_location allow'
[AndroidDriver] Unable to set mock location for app 'io.appium.settings': Error executing adbExec. Original error: 'Command 'D\:\\Android\\platform-tools\\adb.exe -P 5037 -s f29b3cab shell appops set io.appium.settings android\:mock_location allow' exited with code 4294967295'; Stderr: 'Security exception: uid 2000 does not have android.permission.UPDATE_APP_OPS_STATS.
[AndroidDriver] 
[AndroidDriver] java.lang.SecurityException: uid 2000 does not have android.permission.UPDATE_APP_OPS_STATS.
[AndroidDriver] 	at android.app.ContextImpl.enforce(ContextImpl.java:1745)
[AndroidDriver] 	at android.app.ContextImpl.enforcePermission(ContextImpl.java:1758)
[AndroidDriver] 	at com.android.server.AppOpsService.setMode(AppOpsService.java:715)
[AndroidDriver] 	at com.android.server.AppOpsService.onShellCommand(AppOpsService.java:2077)
[AndroidDriver] 	at com.android.server.AppOpsService$Shell.onCommand(AppOpsService.java:1851)
[AndroidDriver] 	at android.os.ShellCommand.exec(ShellCommand.java:96)
[AndroidDriver] 	at com.android.server.AppOpsService.onShellCommand(AppOpsService.java:2025)
[AndroidDriver] 	at android.os.Binder.shellCommand(Binder.java:576)
[AndroidDriver] 	at android.os.Binder.onTransact(Binder.java:476)
[AndroidDriver] 	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:351)
[AndroidDriver] 	at android.os.Binder.execTransact(Binder.java:681)'; Code: '4294967295'
[Logcat] Starting logcat capture
[ADB] Getting install status for io.appium.uiautomator2.server
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell dumpsys package io.appium.uiautomator2.server'
[ADB] 'io.appium.uiautomator2.server' is installed
[ADB] Getting package info for 'io.appium.uiautomator2.server'
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell dumpsys package io.appium.uiautomator2.server'
[ADB] The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('3.2.2' >= '3.2.2')
[UiAutomator2] io.appium.uiautomator2.server installation state: sameVersionInstalled
[ADB] Checking app cert for C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v3.2.2.apk
[ADB] Starting 'D:\Android\build-tools\28.0.3\apksigner.bat' with args '["verify","--print-certs","C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v3.2.2.apk"]'
[ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[ADB] 
[ADB] 'C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v3.2.2.apk' is already signed.
[ADB] Checking app cert for C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
[ADB] Starting 'D:\Android\build-tools\28.0.3\apksigner.bat' with args '["verify","--print-certs","C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk"]'
[ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[ADB] 
[ADB] 'C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is already signed.
[UiAutomator2] Server packages are not going to be (re)installed
[UiAutomator2] Waiting up to 30000ms for services to be available
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell pm list instrumentation'
[UiAutomator2] Instrumentation target 'io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner' is available
[UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 8200
[ADB] Forwarding system: 8200 to device: 6790
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab forward tcp\:8200 tcp\:6790'
[UiAutomator2] No app capability. Assuming it is already on the device
[ADB] Getting install status for com.juzix.wallet
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell dumpsys package com.juzix.wallet'
[ADB] 'com.juzix.wallet' is installed
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell am force-stop com.juzix.wallet'
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell pm clear com.juzix.wallet'
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell am force-stop com.juzix.wallet'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab forward --remove tcp\:8200'
[BaseDriver] Event 'newSessionStarted' logged at 1558945671659 (16:27:51 GMT+0800 (中国标准时间))
[W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'D\:\\Android\\platform-tools\\adb.exe -P 5037 -s f29b3cab shell pm clear com.juzix.wallet' exited with code 1'; Stderr: 'Error: java.lang.SecurityException: PID 26032 does not have permission android.permission.CLEAR_APP_USER_DATA to clear data of package com.juzix.wallet'; Code: '1'
[W3C] Error: Command 'D\:\\Android\\platform-tools\\adb.exe -P 5037 -s f29b3cab shell pm clear com.juzix.wallet' exited with code 1
[W3C]     at ChildProcess.proc.on.code (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\teen_process\lib\exec.js:94:19)
[W3C]     at ChildProcess.emit (events.js:182:13)
[W3C]     at ChildProcess.EventEmitter.emit (domain.js:442:20)
[W3C]     at maybeClose (internal/child_process.js:961:16)
[W3C]     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[HTTP] <-- POST /wd/hub/session 500 9495 ms - 1316
Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2019-05-27 08:49
That exception is not critical and can be ignored. the driver fails because of 

> [W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell pm clear com.juzix.wallet' exited with code 1'; Stderr: 'Error: java.lang.SecurityException: PID 26032 does not have permission android.permission.CLEAR_APP_USER_DATA to clear data of package com.juzix.wallet'; Code: '1'
> [W3C] Error: Command 'D:\Android\platform-tools\adb.exe -P 5037 -s f29b3cab shell pm clear com.juzix.wallet' exited with code 1

which is duplicate of https://github.com/appium/appium/issues/9807

Unfortunately there is nothing we can do from Appium side. As a workaround you could use a device from an other manufactures.

**Closed by mykola-mokhnach** 2019-05-27 08:49 UTC

**Comment by Hanson889** [comment] 2019-05-27 09:03
But why no can run at android 7.1.0 under the same manufacture

**Comment by mykola-mokhnach** [comment] 2019-05-27 09:04
I think this would be a good question to their customer support

**Comment by Hanson889** [comment] 2019-05-27 09:12
No way to solve the problem with Appium? or don't support android 8.0.0 uppers ? if support, can list some devices which can run with android 8.0 uppers?

**Comment by KazuCocoa** [comment] 2019-05-27 10:36
No, unfortunately. Manufacture restricted the feature when they released their devices.

I ran tests on Xperia, Nexus and some Android 8 devices (and 9 as well.) before, but have no exact list.
Not sure in your case, but I saw a comment it worked after enabling USB debugging in the development menu.

You can set `noReset: true` and `fullReset: false` to skip the clearing the device data phase.(It might avoid the issue) In the case, local data in the app remains tho. You must uninstall it to clear the local data.
