### ISSUE TITLE
1.7.2 install failed,"Failed to exec install script"

### ISSUE THREAD

**Issue by TomHappy** [appium/appium#9921] opened 2018-01-05 08:39 UTC
## The problem

There was an issue when i tried to intall appium 1.7.2

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.2
* Last Appium version that did not exhibit the issue (if applicable):1.7.1
* Desktop OS/version used to run Appium:windows 10
* Node.js version (unless using Appium.app|exe):8.9.1
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

I had try many times , but still doesn't work.Anyone who can help, thanks!

## Link to Appium logs
PS C:\WINDOWS\system32> npm install appium -g
C:\Users\my\AppData\Roaming\npm\appium -> C:\Users\my\AppData\Roaming\npm\node_modules\appium\build\lib\main.js

> appium-chromedriver@3.1.4 install C:\Users\my\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.33' for platform 'win' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.com/2.33/chromedriver_win32.zip...
RequestError: Error: read ECONNRESET
    at new RequestError (C:\Users\my\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise\lib\errors.js:11:15)
    at Request.RP$callback [as _callback] (C:\Users\my\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise\lib\rp.js:60:32)
    at self.callback (C:\Users\my\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\my\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[            ......] \ install: info lifecycle appium-chromedriver@3.1.4~install: Failed to exec install script

**Comment by mykola-mokhnach** [comment] 2018-01-05 09:01
Duplicate of https://github.com/appium/appium/issues/7222

**Closed by mykola-mokhnach** 2018-01-05 09:01 UTC
