### ISSUE TITLE
Issue with Appium desktop. Getting the following error "org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Command 'java -version' exited with code 2 (WARNING: The server did not provide any stacktrace information)" Working fine with command line.

### ISSUE THREAD

**Issue by Tanushee** [appium/appium#9901] opened 2018-01-03 05:44 UTC
## Getting "org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Command 'java -version' exited with code 2 (WARNING: The server did not provide any stacktrace information)" When trying to run AndroidDriver through Appium desktop.

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium client version (or git revision) that exhibits the issue: 6.0.0-BETA2
* Desktop OS/version used to run Appium: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_152' 
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android
* Real device or emulator/simulator: not working on either emulator or real device
* Appium.app|exe: Version 1.2.7 (1.2.7)

## Details

Error occurs while opening android driver only with Appium desktop. Works fine for iOS. Tried running androidDriver through command line. Works fine.

## Link to Appium logs
https://gist.github.com/Tanushee/7b93e3430b43289b9d035ac574711c39

## Code To Reproduce Issue 

        DesiredCapabilities capabilities = new DesiredCapabilities();

            capabilities.setCapability("deviceName", "emulator-5554");
            capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
            capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "100");
            capabilities.setCapability(MobileCapabilityType.NO_RESET, "true");
            capabilities.setCapability(MobileCapabilityType.APP,  "/Users/tanusheearya/Documents/TestData/app-qa-debug.apk");
            capabilities.setCapability("showXcodeLog", true);
            try {
                return new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
            } catch (MalformedURLException e) {
                e.printStackTrace();

**Comment by mykola-mokhnach** [comment] 2018-01-03 06:51
Duplicate of https://github.com/appium/appium/issues/8356

**Closed by mykola-mokhnach** 2018-01-03 06:51 UTC
