### ISSUE TITLE
[iOS] (1.21.0) hideKeyboard() throws invalid element state exception

### ISSUE THREAD

**Issue by alei01** [appium/appium#15462] opened 2021-06-03 09:11 UTC
## The problem
hideKeyboard() method throws invalid element state exception:
```[WD Proxy] Got response with status 400: {"value":{"error":"invalid element state","message":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test.\" UserInfo={NSLocalizedDescription=Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test.}","traceback":""},"sessionId":"7B8AA654-89D1-49B6-B173-1EB302096A4D"}```

## Environment
* Appium version (or git revision) that exhibits the issue:
1.21.0
* Last Appium version that did not exhibit the issue (if applicable):
1.19.1, 1.20.2
* Desktop OS/version used to run Appium:
macOS Big Sur (11.3.1)
* Node.js version (unless using Appium.app|exe):
v15.10.0
* Npm package manager:
6.14.12
* Mobile platform/version under test:
iOS 14.5.1, 14.3
* Real device or emulator/simulator:
Real

## Details

After upgrading to the latest 1.21.0 Appium version hideKeyboard() start throwing invalid element state exception.

## Link to Appium logs
[appium-server-log](https://gist.github.com/alei01/66e34eabe5598d6432ebbbd48674c2fb)

**Comment by mykola-mokhnach** [comment] 2021-06-03 09:16
Duplicate of https://github.com/appium/appium/issues?q=is%3Aissue+%22Did+not+know+how+to+dismiss+the+keyboard%22+is%3Aclosed

**Closed by mykola-mokhnach** 2021-06-03 09:16 UTC

**Comment by alei01** [comment] 2021-06-07 11:55
Hi @mykola-mokhnach, the issue is reproducing with the appium-xcuitest-driver  >=3.35.1 and works fine with the 3.34.0 version. 
Any chance to investigate this case?
