### ISSUE TITLE
Android devices - Chrome: - Chrome: Find element throwing INVALID LOCATOR exception

### ISSUE THREAD

**Issue by rodicaDan** [appium/appium#13999] opened 2020-02-27 15:17 UTC
## The problem
Finding element not working on Android Chrome
Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version: 1.15 and 1.16
* Last Appium version: 1.13:
* Desktop OS/version used to run Appium: tested with both Appium Desktop (1.15 ) on WIN 10, and wiht appium 1.1.6 on UBUNTU
* Node.js version (unless using Appium.app|exe):
* Npm version: 6.10.3
* Mobile platform/version under test: Samsung Galaxy S8, Android 9, Chrom 80
Samsung Galaxy S7, Android 8,  Chrome 78
* Real device or emulator/simulator: real devices
* Appium CLI or Appium.app|exe:

## Details
The text below was attempted through code (python), but also in Appium desktop.
In appium desktop: when selecting an element, the info displayed shows the ID. But if I try to perform a SEARCH, by ID with that valid ID - I get zero results.
However when I click to send keys to that element, I can see appium applies an xpath to it.

Through python:
1. Open website under test.
2. Open registration page.
3. Search for element by valid ID, or valid CSS selector.

Expected:
The element is found.

Actual:
The element is not found!

Notes: 
1. The same steps used to work, and no changes were made to the website.
 2. With appium desktop, tried to perorm sarch by ID of an element on the authentication page of ebay website (just to make sure it's not my website's issue) and same problem.

## Link to Appium logs
2020-02-27 12:02:56,772 - RegisterForm - ERROR - Could not find: FIRST_NAME_FIELD! Message: invalid argument: invalid locator
  (Session info: chrome=80.0.3987.99)
Stacktrace:
#0 0x55dde4c6ad29 <unknown>
 (base.py:184)
2020-02-27 12:02:56,772 - RegisterForm - ERROR - Failed to type text into (('id', 'formEl_173'), 'FIRST_NAME_FIELD') field (decorators.py:21)

## Code To Reproduce Issue [ Good To Have ]
The ELEMENT is:
<input type="text" id="formEl_173" placeholder="Nombres" name="firstname" class="generic_firstName" autocomplete="given-name" autocorrect="off" autocapitalize="off" spellcheck="false">

A. By ID:
    print ("Looking for field by ID: ", context.register_form.browser.find_element_by_id("formEl_173"))
B. BY CSS:
 context.register_form.browser.find_element_by_css_selector("#application input[id=\"formEl_173\"]"))
C. By class name:
context.register_form.browser.find_element_by_class_name("generic_firstName"))
D. By name:
context.register_form.browser.find_element_by_name("firstname"))

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2020-02-27 15:21
Duplicate of https://github.com/appium/appium/issues/13306

**Closed by mykola-mokhnach** 2020-02-27 15:21 UTC

**Comment by rodicaDan** [comment] 2020-02-27 15:59
@mikola-mokhnach

Thank you for your reply, but:
- element is not found by css either
- setting w3c: false does not solve the solution.

- is there any workaround?
Thanks a lot!

**Comment by mykola-mokhnach** [comment] 2020-02-27 17:52
> setting w3c: false does not solve the solution.

I cannot say anything without the log

> is there any workaround?

all workarounds I know of are already stated in that issue

**Comment by rodicaDan** [comment] 2020-02-28 10:19
AI m providing here the server logs for testing with:
Appium Desktop 1.15 -  WIN 10 OS
Device Capabilities:
  "platformName": "Android",
  "platformVersion": "8.0.0",
  "deviceName": "Samsung_Galaxy_S7",
  "udid": "10.30.0.101:7409",
  "browserName": "Chrome 78",
  "automationName": "uiautomator2",
  "w3c": false,
  "showChromedriverLog": true


chromedriver: 78

Web Element unner test:
<input type="text" id="formEl_173" placeholder="Nombres" name="firstname" class="generic_firstName" autocomplete="given-name" autocorrect="off" autocapitalize="off" spellcheck="false">

Steps:
1. On mobile device, browser Chrome, go to web page with element udner test,
2. From Appiun Desktop, select SEARCH button.
3. Search by valid ID, by valid name, by valid class name.
Expected:
Element founf.

Actual:
Element not found.

Note:
If this logs are not enough, I can also provide for Samsung Galaxy S8, with Android 9, Chrome 80.
I can also provide for appium server on linux - v 1.16.

[appium-server-logs-android8.txt](https://github.com/appium/appium/files/4266502/appium-server-logs-android8.txt)

**Comment by mykola-mokhnach** [comment] 2020-02-28 10:40
> [debug] [35m[MJSONWP (d7b4ec80)][39m Calling AppiumDriver.findElements() with args: ["name","firstname","d7b4ec80-c020-48c1-82cf-1b3e90c698bf"]
> [debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
> [debug] [35m[MJSONWP (d7b4ec80)][39m Encountered internal error running command: InvalidSelectorError: Locator Strategy 'name' is not supported for this session

I don't see any issues there. The `name` locator strategy is not supported in native context and this is clearly stated in the log.

**Comment by mykola-mokhnach** [comment] 2020-02-28 10:41
Also, `w3c` is a chrome option, not the Appium driver capability. That is why the following warning is shown:

```
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
[warn] [35m[BaseDriver][39m   w3c
```

**Comment by rodicaDan** [comment] 2020-02-28 10:44
{"using":"class name","value":"generic_firstName"}[39m
[debug] [35m[MJSONWP (d7b4ec80)][39m Calling AppiumDriver.findElements() with args: ["class name","generic_firstName","d7b4ec80-c020-48c1-82cf-1b3e90c698bf"]
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [35m[BaseDriver][39m Waiting up to 0 ms for condition
[debug] [35m[WD Proxy][39m Matched '/elements' to command name 'findElements'

So it does not find the element by class name either, nor by ID - and class name and ID are valid locators. :(

**Comment by mykola-mokhnach** [comment] 2020-02-28 16:15
> [debug] �[35m[MJSONWP (d7b4ec80)]�[39m Calling AppiumDriver.findElements() with args: ["class name","generic_firstName","d7b4ec80-c020-48c1-82cf-1b3e90c698bf"]

`generic_firstName` does not look like a valid class name. Are you sure you understand properly how element location strategies work?

**Comment by rodicaDan** [comment] 2020-03-02 08:09
@mykola-mokhnach 
I used the value of the class attribute in the element:
<input type="text" id="formEl_173" placeholder="Nombres" name="firstname" class="generic_firstName" autocomplete="given-name" autocorrect="off" autocapitalize="off" spellcheck="false">

**Comment by mykola-mokhnach** [comment] 2020-03-02 08:35
I believe some entities got mixed here. UIA2 has its own source tree generated by the accessibility inspector. It has nothing to do with the html source tree of the application under test

**Comment by bwomsm1** [comment] 2022-01-02 18:52
@rodicaDan did you might solve that annoying issue?

**Comment by bwomsm1** [comment] 2022-01-02 18:55
> Also, `w3c` is a chrome option, not the Appium driver capability. That is why the following warning is shown:
> 
> ```
> [warn] �[35m[BaseDriver]�[39m The following capabilities were provided, but are not recognized by Appium:
> [warn] �[35m[BaseDriver]�[39m   w3c
> ```

Are we able to run appium with ChromeOptions? Asking care that my test is on mobile chrome browser.
