### ISSUE TITLE
Appium desktop fails to load Screenshot when WebDriverAgent is built using Xcode 12.5 beta 2

### ISSUE THREAD

**Issue by rakurati7** [appium/appium#15200] opened 2021-03-19 09:24 UTC
## The problem

When Web driver agent is created using Xcode 12.5 Beta, appium desktop fails to load Screenshot

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: macOS 11.2.1 BigSur
* Node.js version (unless using Appium.app|exe): 
* Npm or Yarn package manager:
* Mobile platform/version under test: 14.5, 13.7, 12.4.1
* Real device or emulator/simulator: iPhone 8plus (real device)
* Appium CLI or Appium.app|exe: Appium.app

## Details

Every thing works fine when WDA is built on Xcode 12.4 and Appium (1.20.2) you can see the logs [here](https://gist.github.com/rakurati7/3edb4141e32d8d90bff8e28a62551c21)

Note: i have not included iOS logs if required please let me know

Once I updated the Xcode to 12.5, Appium desktop fails to load the Screenshot (get screenshot() returns some error) logs for the same is [here](https://gist.github.com/rakurati7/71cd0aace7301f98b375aef064955e59)

<img width="1082" alt="Screenshot 2021-03-09 at 10 57 31 PM" src="https://user-images.githubusercontent.com/28534128/111760240-7c946680-88c4-11eb-8dc0-1557db94c753.png">

**Comment by mykola-mokhnach** [comment] 2021-03-19 09:51
Duplicate of https://github.com/appium/appium/issues/15199

Please use appium@beta

**Closed by mykola-mokhnach** 2021-03-19 09:51 UTC

**Comment by rakurati7** [comment] 2021-03-19 10:36
I tried using latest Appium Beta 1.21.0 beta.0 on Xcode 12.5

Issue still exist - [logs](https://gist.github.com/rakurati7/ec3dcec2ace8f065fa7ef357fd3ac10f)
