### ISSUE TITLE
PageSource is extremely slow on combination of iOS 11 + Xcode 9

### ISSUE THREAD

**Issue by muratme** [appium/appium#9522] opened 2017-10-25 08:12 UTC
## The problem

PageSource is extremely slow on combination of iOS 11 + Xcode 9
Test execution time dramatically increased with Appium 1.7.1 - Xcode9 combination. Each action waits too much to execute.

## Environment

* APPIUM : 1.7.1
* OS : macOS High Sierra 10.13
* NODE : v8.7.0
* TEST DEVICE : Iphone 7 with 11.0.3
* REAL DEVICE

**Comment by mykola-mokhnach** [comment] 2017-10-25 08:50
Duplicate of https://github.com/facebook/WebDriverAgent/issues/744

**Closed by mykola-mokhnach** 2017-10-25 08:50 UTC
