### ISSUE TITLE
Unable to locate an element in IOS due to more hierarchies in the app source.

### ISSUE THREAD

**Issue by kalyan7h** [appium/appium#15633] opened 2021-07-15 09:26 UTC
## Unable to locate an element in IOS due to more hierarchies in the app source.

Able to see the required control in the app source. It has accessibility enabled. findByElement thru IOS class chain strategy immediately gives me "NoSuchElement" response. Am able to identify its immediate parent thru locator. After some investigation found that, if a couple of parent hierarchies is reduced then the control can be identified. Due to technical aspects, dev decided not to remove any parent hierarchy.

 Is there a way to increase the depth of findelementBy query (tried snapshotMaxDepth, no luck)

## Above behavior is seen on below Environments
Appium Version: 1.19, 1.20
IOS Version: 13.3 & 14
Hybrid mobile app

![image](https://user-images.githubusercontent.com/12005480/125763751-6d624341-e74e-4b56-a36e-7b017e6b6bbd.png)

Appium Server Response:
Calling AppiumDriver.findElement() with args: ["-ios class chain","**/XCUIElementTypeOther[`name='Payee Name: shop'`]","3bc75c94-28ee-4a85-a31a-27730ca02553"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 3000 ms for condition
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/0F80722F-47EF-4D04-8AED-E3D2D46671BD/element] with body: {"using":"class chain","value":"**/XCUIElementTypeOther[`name='Payee Name: shop'`]"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'class chain', value '**/XCUIElementTypeOther[`name='Payee Name: shop'`]'","traceback":"(\n\t0   WebDriverAgentLib                   0x0000000104cf7c3d FBNoSuchElementErrorResponseForRequest + 301\n\t1   WebDriverAgentLib                   0x0000000104cf79e9 +[FBFindElementCommands handleFindElement:] + 425\n\t2   WebDriverAgentLib                   0x0000000104cd4926 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t3   WebDriverAgentLib                   0x0000000104cbc71b __37-[FBWebServer registerRouteHandlers:]_block_invoke + 555\n\t4   RoutingHTTPServer                   0x0000000104dce683 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136\n\t5   RoutingHTTPServer                   0x0000000104dcefc6 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47\n\t6   libdispatch.dylib                   0x00007fff5223f7b9 _dispatch_client_callout + 8\n\t7   libdispatch.d...

**Comment by mykola-mokhnach** [comment] 2021-07-15 10:05
Duplicate of https://github.com/appium/appium/issues/14825

**Closed by mykola-mokhnach** 2021-07-15 10:05 UTC
