### ISSUE TITLE
Locator method timing slowed ~200x creating scenarios to fail

### ISSUE THREAD

**Issue by aquigriffin** [appium/appium#16269] opened 2021-12-22 18:52 UTC
## The problem

While investigating an issue where our tests were running extremely slow, I discovered a prevalent issue where locator find methods by id, accessibility id, and xpath were slowed by ~200x the regular find times when the Android keyboard is on screen. Forcing the soft keyboard hidden via desired capabilities and/or hiding during the scenario did not improve times. I suspect this issue is the underlying issue for many other situations, e.g. keyboard typing slowness.

## Environment

Appium Inspector - App Version: 2021.9.2, Electron: 13.5.0, Node.js: 14.16.0
Appium Server GUI - App Version: 1.22.0, Electron: 7.3.3, Node.js: 12.8.1
Android Emulator - Pixel 3 Android 11 (also replicable on Android 9 & 10)

## Details

The following are screenshots of timings taken from the Appium Inspector to demonstrate the difference between emulator keyboard being displayed/hidden.

![find_by_keyboard_up](https://user-images.githubusercontent.com/723135/147141111-c30f55c7-299d-421d-918f-fce77091a09d.png)
![find_by_keyboard_down](https://user-images.githubusercontent.com/723135/147141126-e4ebb34b-4abb-4a02-bb34-411ededed9d9.png)

**Comment by mykola-mokhnach** [comment] 2021-12-22 22:03
Possible duplicate of https://github.com/appium/appium/issues/14594

**Comment by mykola-mokhnach** [comment] 2021-12-27 16:54
Closed because of no response

**Closed by mykola-mokhnach** 2021-12-27 16:54 UTC
Labels: Android, ThirdParty, NeedsInfo
