### ISSUE TITLE
Cannot find Elements in a webview using UiAutomator2 but the same elements are found with Appium(default)

### ISSUE THREAD

**Issue by AlexK07** [appium/appium#10957] opened 2018-06-27 05:43 UTC
## The problem

Hi,
I have an issue with UiAutomator2, I cannot use this one to find elements on a web view. The same elements are found with Appium which is by default UiAutomator1 (if I’m not wrong). I tried with different API versions but I got the same results.
Every time when I’m using Uiatomator2  I'm getting "Caused by: org.openqa.selenium.NoSuchElementException: Cannot locate an element using By.id: buttonSubmitLogin"
Do you have any idea what can I do in this case?

## Environment
I am using Appium desktop v1.8.1
Appium v is 6.0.0
Android versions: 5.0, 8.0

## Details
Here are the Capabilities : 

public DesiredCapabilities HuaweiP20Lite() {
DesiredCapabilities capabilities = DesiredCapabilities.android();
capabilities.setCapability(“deviceName”, “WCY4C18602004318”);
capabilities.setCapability(CapabilityType.BROWSER_NAME, “Android”);
capabilities.setCapability(CapabilityType.VERSION, “8.0”);
capabilities.setCapability(“platformName”, “Android”);
capabilities.setCapability(“appPackage”, “com.lego.common.legolife.live.nightly”);
capabilities.setCapability(“appActivity”, “com.lego.common.legolife.ui.interfaces.LauncherActivity”);
capabilities.setCapability(“automationName”, “UiAutomator2”);
capabilities.setCapability(“newTimeoutCommand”, “300”);
capabilities.setCapability(“noReset”,true);
return capabilities;
}

## Link to Appium logs

https://gist.github.com/AlexK07/2c46d7594c85e46299e2e68d05ea27e8 . -the log for UIAutomator2

https://gist.github.com/AlexK07/ed720ff8a6479da0942a7086c56b984b . - the log for Appium

**Comment by mykola-mokhnach** [comment] 2018-06-27 05:46
Duplicate of https://github.com/appium/appium/issues/10917

**Closed by mykola-mokhnach** 2018-06-27 05:46 UTC
