### ISSUE TITLE
Can't setup AppiumServer via Jenkins shell Script（for Mac）

### ISSUE THREAD

**Issue by 1aoying** [appium/appium#11100] opened 2018-07-24 02:16 UTC
## The problem

I can't setup AppiumServer via Jenkins ，but can set up Appium server on my mac local
 for shell: appium & 
 
jenkins build shell like this:

OLD_BUILD_ID=$BUILD_ID
echo $OLD_BUILD_ID
BUILD_ID=DONTKILLME 
echo $BUILD_ID
nohup sudo appium --session-override -a 127.0.0.1 -p 4723 --log ~/jenkins/appium.log &
#sh startappium.sh
BUILD_ID=$OLD_BUILD_ID
echo "$(whoami)"
echo "$USER"
sleep 5

Now I want to run autotest via tomcat+ jenkins+maven+AppiumServer, but just setup AppiumServer by myself in local mac machine terminal like :appim &

Please help me!

## Environment
 
* Appium Server version: 1.8.1
* Desktop OS/version used to run Appium:10.13.5
* Node.js version (unless using Appium.app|exe):v10.7.0
* Mobile platform/version under test:11.4
* Real device or emulator/simulator:iPhone 6P real device
* Appium CLI or Appium.app|exe:Appium.app

## Details
I try to do :
1.  rebuild my WebDriverAgent  and reset the device. 
2. update AppiumServer,Node  to lateset version

it seems doesn't any affect,still error:
stack=[Error: write EPIPE,     at WriteWrap.afterWrite (net.js:836:14)]

local run shell :appium &,then I can build jenkins jobs successful! If there have some authority question for mac bash shell?

## Link to Appium logs

2018-07-23 12:23:42:372 - info: [Appium] Welcome to Appium v1.8.1
2018-07-23 12:23:42:375 - info: [Appium] Non-default server args:
2018-07-23 12:23:42:375 - info: [Appium]   address: 127.0.0.1
2018-07-23 12:23:42:375 - info: [Appium]   sessionOverride: true
2018-07-23 12:23:42:376 - info: [Appium]   log: appium.log
2018-07-23 12:23:42:418 - info: [Appium] Appium REST http interface listener started on 127.0.0.1:4723
2018-07-23 12:24:14:665 - info: [HTTP] --> POST /wd/hub/session
2018-07-23 12:24:14:666 - info: [HTTP] {"capabilities":[{"desiredCapabilities":{"app":"/Users/caoying/MailMaster/mail.ipa","no_reset":false,"appiumVersion":"1.8.0","platformVersion":"11.4","xcodeOrgId":"7ASX6BDY42","automationName":"XCUITest","platformName":"iOS","udid":"6cd169b2c30282316829f9cf25880497d1abfaea","deviceName":"iPhone 6p","xcodeSigningId":"iPhone Developer"}},{"requiredCapabilities":{}}],"desiredCapabilities":{"app":"/Users/caoying/MailMaster/mail.ipa","no_reset":false,"appiumVersion":"1.8.0","platformVersion":"11.4","xcodeOrgId":"7ASX6BDY42","automationName":"XCUITest","platformName":"iOS","udid":"6cd169b2c30282316829f9cf25880497d1abfaea","deviceName":"iPhone 6p","xcodeSigningId":"iPhone Developer"},"requiredCapabilities":{}}
2018-07-23 12:24:14:669 - info: [debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/caoying/MailMaster/mail.ipa","no_reset":false,"appiumVersion":"1.8.0","platformVersion":"11.4","xcodeOrgId":"7ASX6BDY42","automationName":"XCUITest","platformName":"iOS","udid":"6cd169b2c30282316829f9cf25880497d1abfaea","deviceName":"iPhone 6p","xcodeSigningId":"iPhone Developer"},{},[{"desiredCapabilities":{"app":"/Users/caoying/MailMaster/mail.ipa","no_reset":false,"appiumVersion":"1.8.0","platformVersion":"11.4","xcodeOrgId":"7ASX6BDY42","automationName":"XCUITest","platformName":"iOS","udid":"6cd169b2c30282316829f9cf25880497d1abfaea","deviceName":"iPhone 6p","xcodeSigningId":"iPhone Developer"}},{"requiredCapabilities":{}}]]
2018-07-23 12:24:14:670 - info: [debug] [BaseDriver] Event 'newSessionRequested' logged at 1532348654670 (20:24:14 GMT+0800 )
2018-07-23 12:24:14:671 - info: [Appium] Creating new XCUITestDriver (v2.87.0) session
2018-07-23 12:24:14:672 - info: [Appium] Capabilities:
2018-07-23 12:24:14:672 - info: [Appium]   app: /Users/caoying/MailMaster/mail.ipa
2018-07-23 12:24:14:672 - info: [Appium]   no_reset: false
2018-07-23 12:24:14:672 - info: [Appium]   appiumVersion: 1.8.0
2018-07-23 12:24:14:672 - info: [Appium]   platformVersion: 11.4
2018-07-23 12:24:14:672 - info: [Appium]   xcodeOrgId: 7ASX6BDY42
2018-07-23 12:24:14:672 - info: [Appium]   automationName: XCUITest
2018-07-23 12:24:14:673 - info: [Appium]   platformName: iOS
2018-07-23 12:24:14:673 - info: [Appium]   udid: 6cd169b2c30282316829f9cf25880497d1abfaea
2018-07-23 12:24:14:673 - info: [Appium]   deviceName: iPhone 6p
2018-07-23 12:24:14:673 - info: [Appium]   xcodeSigningId: iPhone Developer
2018-07-23 12:24:14:677 - info: [debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"/Users/caoying/Mail...
2018-07-23 12:24:14:683 - warn: [BaseDriver] The following capabilities were provided, but are not recognized by appium: no_reset, appiumVersion.
2018-07-23 12:24:14:684 - info: [BaseDriver] Session created with session id: d40eb29d-2117-4f26-a0f9-59527b109cc2
2018-07-23 12:24:14:728 - error: uncaughtException: write EPIPE date=Mon Jul 23 2018 20:24:14 GMT+0800 , pid=4988, uid=501, gid=20, cwd=/Users/caoying/jenkins/jenkins_home/workspace/AppiumServerAStart, execPath=/usr/local/Cellar/node/10.7.0/bin/node, version=v10.7.0, argv=[/usr/local/Cellar/node/10.7.0/bin/node, /usr/local/bin/appium, --session-override, -a, 127.0.0.1, -p, 4723, --log, appium.log], rss=88784896, heapTotal=64835584, heapUsed=58313928, external=78963, loadavg=[2.68603515625, 2.12060546875, 2.095703125], uptime=14515, trace=[column=14, file=net.js, function=WriteWrap.afterWrite, line=836, method=afterWrite, native=false], stack=[Error: write EPIPE,     at WriteWrap.afterWrite (net.js:836:14)]
#

**Comment by mykola-mokhnach** [comment] 2018-07-24 09:43
This is because you're using `nohup`. Check https://unix.stackexchange.com/questions/75176/redirection-to-file-issues-with-nohup-and-pipe for more details

**Comment by 1aoying** [comment] 2018-07-25 02:23
@mykola-mokhnach I try delete : nohup,but still can't run my job.

**Comment by mykola-mokhnach** [comment] 2018-07-25 04:49
You must wait until the server start listening if you execute the server in background. Closed as duplicate of https://github.com/appium/appium/issues/10538

**Comment by 1aoying** [comment] 2018-07-25 08:51
@mykola-mokhnach  I update my java-client version from
5.0.0-BETA8 to 6.0.0-BETA4 ，cast excetiion ：java.lang.NoClassDefFoundError: com/google/common/base/Function”Then，I  import selenium-server-standalone-2.53.1.jar into my eclipse there have another question:FAILED CONFIGURATION: @BeforeClass setUp
java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;)V
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:143)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:82)
	at com.netease.mailmaster.test.MailIOSUITest.BaseTest.setUp(BaseTest.java:84)
	at com.netease.mailmaster.test.MailIOSUITest.LoginTest.setUp(LoginTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)

**Comment by mykola-mokhnach** [comment] 2018-07-25 08:56
This is not a server issue

**Comment by 1aoying** [comment] 2018-07-25 08:57
@mykola-mokhnach 
This is my pom 

<dependencies>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.9.10</version>
		</dependency>
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			
			<version>6.0.0-BETA4</version>		
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.6</version>
			<scope>test</scope>
		</dependency>
		<dependency>
    		<groupId>log4j</groupId>
    		<artifactId>log4j</artifactId>
    		<version>1.2.17</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.2.4</version>
		</dependency>
	</dependencies>

**Comment by 1aoying** [comment] 2018-07-25 08:57
<dependencies>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.9.10</version>
		</dependency>
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			
			<version>6.0.0-BETA4</version>		
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.6</version>
			<scope>test</scope>
		</dependency>
		<dependency>
    		<groupId>log4j</groupId>
    		<artifactId>log4j</artifactId>
    		<version>1.2.17</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.2.4</version>
		</dependency>
	</dependencies>

**Comment by 1aoying** [comment] 2018-07-25 08:58
@mykola-mokhnach  yes ,but I need run it on local eclipse first of  all

**Comment by mykola-mokhnach** [comment] 2018-07-25 09:00
Please use appium forum to ask questions

**Comment by 1aoying** [comment] 2018-07-25 09:03
ok

**Comment by 1aoying** [comment] 2018-07-27 02:58
@mykola-mokhnach  hi！mykola-mokhnach，Sorry to bother you again。
I uset the method [#10538](https://github.com/appium/appium/issues/10538) but still fail run my real device test! appium Sever is OK ,can via shell script build.but still can't run my automated test scripts

**Comment by 1aoying** [comment] 2018-07-27 03:01
I don’t konw there have any anthoer questions in my code

code：

```
private static final String SERVER_URL = String.format("http://127.0.0.1:%d/wd/hub", 4723);
private static final Duration RESTART_TIMEOUT = Duration.ofMinutes(1);

public static boolean waitUntilIsRunning(Duration timeout) throws Exception {
	       System.out.println("Validating whether the url is up and running.");
	       final URL status = new URL(SERVER_URL + "/sessions");
	       try {
	           new UrlChecker().waitUntilAvailable(timeout.getSeconds(), TimeUnit.SECONDS, status);
	           System.out.println("Url is up and running!");
	           return true;
	       } catch (UrlChecker.TimeoutException e) {
	           System.out.println("Url is not running ");
	           return false;
	       }
	   }
	   
	   @BeforeTest
public void setUp() throws Exception {
		String path = "/Users/caoying/MailMaster/mail.ipa";
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("platformName", "IOS");
        capabilities.setCapability("appiumVersion", "1.8.1");
        capabilities.setCapability("platformVersion", "11.4");
        capabilities.setCapability("deviceName", "iPhone 6p");
        capabilities.setCapability("app", path);
        capabilities.setCapability("automationName", "XCUITest");
        capabilities.setCapability("udid","6cd169b2c30282316829f9cf25880497d1abfaea");
        capabilities.setCapability("no_reset", NO_RESET);

        
        if (waitUntilIsRunning(RESTART_TIMEOUT)) {
        	driver = new IOSDriver<WebElement>(new URL(SERVER_URL), capabilities);
        }
       
        
		System.out.println(driver.getPageSource());
		BasePage basepage = new BasePage();
		PageFactory.initElements(new AppiumFieldDecorator(driver), basepage);
		
	}

```

appium.log:
 
 
 ```
 2018-07-27 02:35:15:076 - info: [Appium] Welcome to Appium v1.8.1
2018-07-27 02:35:15:080 - info: [Appium] Non-default server args:
2018-07-27 02:35:15:080 - info: [Appium]   address: 127.0.0.1
2018-07-27 02:35:15:081 - info: [Appium]   sessionOverride: true
2018-07-27 02:35:15:081 - info: [Appium]   log: /Users/caoying/jenkins/appium.log
2018-07-27 02:35:15:132 - info: [Appium] Appium REST http interface listener started on 127.0.0.1:4723
2018-07-27 02:38:48:769 - info: [HTTP] --> GET /wd/hub/sessions
2018-07-27 02:38:48:769 - info: [HTTP] {}
2018-07-27 02:38:48:771 - info: [debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
2018-07-27 02:38:48:773 - info: [debug] [MJSONWP] Responding to client with driver.getSessions() result: []
2018-07-27 02:38:48:778 - info: [HTTP] <-- GET /wd/hub/sessions 200 7 ms - 40
2018-07-27 02:38:48:778 - info: [HTTP] 
2018-07-27 02:38:48:781 - error: uncaughtException: write EPIPE date=Fri Jul 27 2018 10:38:48 GMT+0800 (中国标准时间), pid=29803, uid=501, gid=20, cwd=/Users/caoying/jenkins/jenkins_home/workspace/AppiumServerAStart, execPath=/usr/local/Cellar/node/10.7.0/bin/node, version=v10.7.0, argv=[/usr/local/Cellar/node/10.7.0/bin/node, /usr/local/bin/appium, --session-override, -a, 127.0.0.1, -p, 4723, --log, /Users/caoying/jenkins/appium.log], rss=86720512, heapTotal=63262720, heapUsed=55974784, external=70764, loadavg=[2.11572265625, 2.00537109375, 2.14453125], uptime=305590, trace=[column=14, file=net.js, function=WriteWrap.afterWrite, line=836, method=afterWrite, native=false], stack=[Error: write EPIPE,     at WriteWrap.afterWrite (net.js:836:14)]

 ```

**Comment by 1aoying** [comment] 2018-07-27 03:02
```
FAILED CONFIGURATION: @BeforeClass setUp
org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused (Connection refused)
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'Mac-mini-4.local', ip: '169.254.77.65', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '1.8.0_161'
Driver info: driver.version: IOSDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:177)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:112)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:78)
	at com.netease.mailmaster.test.MailIOSUITest.BaseTest.setUp(BaseTest.java:104)
	at com.netease.mailmaster.test.MailIOSUITest.LoginTest.setUp(LoginTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:139)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:87)
	at io.appium.java_client.remote.AppiumProtocolHandShake.createSession(AppiumProtocolHandShake.java:114)
	at io.appium.java_client.remote.AppiumProtocolHandShake.createSession(AppiumProtocolHandShake.java:76)
	at io.appium.java_client.remote.AppiumCommandExecutor.doExecute(AppiumCommandExecutor.java:111)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:162)
	... 37 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 52 more
```

**Closed** 2018-08-03 20:09 UTC
Labels: Question
