### ISSUE TITLE
Appium throws "ideviceinstaller" not found when launched through Eclipse - Java

### ISSUE THREAD

**Issue by prashantnagrecha** [appium/appium#5033] opened 2015-04-30 23:39 UTC
Hi, 
While launching an app on real device through Appium Inspector there are no issues. It works perfect. The issue lies when I invoke to launch an app through Java. I'm specifying standard set of desired capabilities, port etc. Appium is launched but the moment it tries to open app - it throws an error stating Could not initialize ideviceinstaller; make sure it is installed and works on your system

Btw, idevideinstaller is perfectly installed on my Mac.

I guess issue in config or something, any inputs will be appreciated.

**Comment by moizjv** [comment] 2015-05-01 22:12
can you paste appium logs. How are you running appium server?

**Comment by srikanthsadhu** [comment] 2015-05-02 07:03
This happens might be because I device object not found , I device occasionally hangs due to usbmuxd error in SYS log imply remote peer socket connection closed.
We raised with I device and no use none looking since 3 weeks .
Only way it may work is replug device problem gets resolved by itself.

**Comment by moizjv** [comment] 2015-05-02 23:13
@srikanthsadhu I do not think this is appium issue? Can you ask in [forum](http://discuss.appium.com) ?

**Comment by Jonahss** [comment] 2015-05-06 23:04
Uh oh, this looks like a duplicate of #5039 
Read my last comment there, does it apply to you?

**Comment by prashantnagrecha** [comment] 2015-05-07 04:50
I think I shall uninstall everything and re-install appium and see how it goes.

**Comment by Jonahss** [comment] 2015-05-07 19:14
Tell us how it goes :)

**Comment by prashantnagrecha** [comment] 2015-05-07 23:43
Hi all, I did everything but unfortunately the latest version of appium v1.3.7 throws error stating ideviceinstaller not found when launched through Java...to me keep my project running, i revert to v1.3.4 where it works without any issues. Hopefully in some time i can install the latest version where ideviceinstaller issue is resolved.

**Comment by Jonahss** [comment] 2015-05-08 00:46
You can also install ideviceinstaller from source. it IS kind of a pain though.

**Closed** 2015-05-08 00:46 UTC
Labels: NeedsTriage, OnGoing
