### ISSUE TITLE
driver.getPageSource() call return errors, Java client 5.0.4, appium 1.7.1

### ISSUE THREAD

**Issue by jensen7up** [appium/appium#9397] opened 2017-10-06 17:12 UTC
## The problem

driver.getPageSource() call return errors, Java client 5.0.4, appium 1.7.1

The call returns:
Example:
name:introScreenGradient  label:AX error -25205  value:AX error -25205

link to gist: https://gist.github.com/jensen7up/027a9f6018dfe734289e343a8cd99df7

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Java client 5.0.4
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: ios 9, using xcode 9
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

Example:
name:introScreenGradient  label:AX error -25205  value:AX error -25205

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by dpgraham** [comment] 2017-10-06 17:13
Can you provide a [gist](https://gist.github.com/) of your Appium logs.

**Comment by jensen7up** [comment] 2017-10-06 17:25
Done. The link: https://gist.github.com/jensen7up/027a9f6018dfe734289e343a8cd99df7

**Comment by mykola-mokhnach** [comment] 2017-10-06 18:13
Duplicate of https://github.com/facebook/WebDriverAgent/issues/703

**Closed by mykola-mokhnach** 2017-10-06 18:13 UTC
Labels: NeedsInfo
