### ISSUE TITLE
autoAcceptAlerts not working correctly on iOS9 

### ISSUE THREAD

**Issue by marciok** [appium/appium#5663] opened 2015-09-28 14:46 UTC
Hi,
I just upgraded to Xcode7 and I'm running my tests on iOS9 with Appium 1.4.11. 

Everything It's working, but the option `autoAcceptAlerts = true`, which is not enabling the given system alert, it's actually doing the opposite, it's tapping on 'Don't Allow'.
It was working before the update.

Any ideas on how to overcome that problem?

Thanks a lot.

**Comment by marciok** [comment] 2015-09-28 15:31
I guess it is the same issue https://github.com/appium/appium/issues/5463

**Comment by newthomas** [comment] 2015-09-28 18:34
Facing same issues. Also Xcode 7, iOS9 and current Appium 1.4.11.

**Comment by marciok** [comment] 2015-09-28 19:27
@newthomas I did a quick-fix until the issue is over:  `execute_script 'target.frontMostApp().alert().buttons()[1].tap()' `

**Comment by newthomas** [comment] 2015-09-28 19:31
Ive read that. Will try it also. Looks like back to the '(ui-automation-javascript) roots'... ;)

**Comment by marciok** [comment] 2015-09-28 19:34
@newthomas ;)

**Comment by eugenluca** [comment] 2015-09-29 12:18
Hi guys,

I think I found the problem with the alert.

In the node_modules/appium-uiauto/uiauto/lib/mechanic-ext/alert-ext.js file you will find:

acceptAlert: function () {
      var alert = getAlert();
      if (!alert.isNil()) {
        var acceptButton = alert.defaultButton();
        var buttonCount = alert.buttons().length;
        // iOS9.1 returns 'cancel' as the default button.
        if ((parseFloat($.systemVersion) >= 9.1 && buttonCount > 0) ||
            (acceptButton.isNil() && buttonCount > 0)) {
          // last button is accept
          acceptButton = alert.buttons()[buttonCount - 1];
        }
        acceptButton.tap();
        this.waitForAlertToClose(alert);
      } else {
        var ios7AlertButtons = this._getElementsByXpath("actionsheet/button");
        if (ios7AlertButtons.length > 0) {
          ios7AlertButtons[0].tap();
        } else {
          throw new ERROR.UnknownError();
        }
      }
    }

The problem here is that cancel is also default on iOS 9.0

// iOS9.1 returns 'cancel' as the default button.
        if ((parseFloat($.systemVersion) >= 9.1 && buttonCount > 0) ||

so the right code should be 

// iOS9.0 returns 'cancel' as the default button.
        if ((parseFloat($.systemVersion) >= 9.0 && buttonCount > 0) ||

This fixed the issue for me :D

**Comment by marciok** [comment] 2015-09-29 12:26
Oh yeah, that fix it's definitely more neat than mine.
Thanks @eugenluca.

**Comment by eugenluca** [comment] 2015-09-29 12:28
@marciok 
Took me 4 hours to find it :))

**Comment by amedvedjev** [comment] 2015-09-30 13:38
note that there are at least 2 types of alerts:
 - with "UIAAlert" tag e.g. when system asks to allow location service.
 - with "UIACollectionView" tag e.g. when in application code we use system alert functionality and alerting something.

in first case with iOS 9.0 it is broken. in second case "accept()" continues to work correctly.

**Comment by savishy** [comment] 2016-01-21 10:23
Is this issue still valid? 
I have two separate devices. I tried `driver.manage.alerts.accept()` first on iPhone 6+ / iOS 9.0.2 where the **alert was not accepted.**
Then I tried the same code (no changes) on an iPhone 5 / iOS 9.2. 
The alert **was accepted properly.**

**Comment by knreddy036** [comment] 2016-07-07 16:43
@eugenluca --- I have followed your steps ,i am still facing same issue .I am testng on iPhone6s(9.3.2) version.Will this scenario work for iPhone6s(9.3.2) on safari browser

**Comment by smccarthy** [comment] 2016-07-12 17:15
Is this still an issue for iOS 9.3.2 ? I opened #6617 which might be the same issue. autoAcceptAlerts is not working. There is a reproducable case in #6617

**Comment by smccarthy** [comment] 2016-07-28 14:55
Has anyone tried 9.3 ? My autoAcceptAlerts is not working on 9.3, and thinking maybe it acts similar to 9.0 ?

**Comment by dpgraham** [comment] 2016-12-07 19:18
Closing this issue. If anyone sees this issue come up when using Appium 1.6.x please comment here and I'll re-open.

**Closed by dpgraham** 2016-12-07 19:18 UTC
Labels: NeedsTriage

**Comment by smccarthy** [comment] 2016-12-07 19:38
@dpgraham Isn't this still an issue with XCUITest on real devices ? Or is that considered a separate issue ?

**Comment by dpgraham** [comment] 2016-12-07 21:10
Yes, you're correct @smccarthy. 'autoAcceptAlerts' is indeed broken on XCUI Test.

I'm going to keep this issue closed as a duplicate. For status updates on this issue please follow: https://github.com/appium/appium/issues/6864
