### ISSUE TITLE
UiAutomator2 deletes session after app launch.Error: Cannot start the application

### ISSUE THREAD

**Issue by milauac** [appium/appium#13098] opened 2019-08-20 13:07 UTC
## The problem
 When UiAutomator2 is chosen as 'automationName', app is launched on phone or emulator and after that session is deleted with  error and suggestion to increase  adbExecTimeout. Timeout value doesn't make influence on behavior. Tried to increase up to 75000. And actually app is already started on phone/emulator. Works fine with 'automationName' = 'Espresso'

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0, 1.12.1
* Desktop OS/version used to run Appium: macOSMojave 10.14.6
* Node.js version: v12.5.0
* Npm  package manager: 6.9.0
* Mobile platform/version under test: 7, 8.1
* Real device or emulator/simulator: both

## Details

App has 3 activities;

With 'appWaitActivity' capability logs and errors are the same.

_adb -P 5037 -s emulator-5554 shell am start -W -n com.app.assist.app/host.exp.exponent.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000_ command starts the app on phone/device and stuck after 
 _Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.app.assist.app/host.exp.exponent.MainActivity }_

didn't provide any output more.

## Link to Appium logs

 [GIST](https://gist.github.com/milauac/74618a93acf08e4754755985d8459ee7)

**Comment by mykola-mokhnach** [comment] 2019-08-20 14:30
Possible duplicate of https://github.com/appium/appium/issues/12962

**Comment by milauac** [comment] 2019-08-20 16:17
thanks, you are right . For me works as well with appWaitForLaunch = false and appium@beta

**Closed** 2019-08-20 17:04 UTC
Labels: NeedsInfo, UIAutomator2
