### ISSUE TITLE
increase event listener max to avoid warning message

### ISSUE THREAD

**Issue by jmehtaebates** [appium/appium#7644] opened 2017-01-04 22:50 UTC
When I try 'Ctrl + C' to shut down the appium server I get the below error

```
[Appium] Received SIGINT - shutting down
(node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Server.addListener (events.js:239:17)
    at Server.once (events.js:265:8)
    at Server.close (net.js:1490:12)
    at ../../../lib/express/server.js:26:7
    at new Promise (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:201:7)
    at callee$1$0$ (../../../lib/express/server.js:24:18)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)

```
I see there are few more users facing similar issue @ https://discuss.appium.io/t/appium-1-6-0-beta3-memory-leak/12787

Any pointers how to fix this?

**Comment by jlipps** [comment] 2017-01-04 23:14
I don't think this is a memory leak. I think we just use a lot of event emitters. I guess we can set the max emitter value in Appium so the warning is printed. But I don't think this is causing any actual issues unless you've noticed other bad behavior.

**Comment by jmehtaebates** [comment] 2017-01-04 23:45
Yes. Limiting the event emitters should help. 

Currently I see that the server does not stop for a really long time (it took several minutes before I had to terminate the process) with the above warning been seen multiple times. Will limiting the event emitters help in this case ?

**Comment by jlipps** [comment] 2017-01-04 23:48
No, it wouldn't help. And I'm not talking about limiting them, I'm talking about _increasing_ the limit, so that the warning goes away. But it sounds like there's actual strange behavior we should look into. We'll need to understand more of what's going on in your case to repro though.

**Comment by jmehtaebates** [comment] 2017-01-04 23:59
I thought so too :(
I am not doing anything different. I launch the appium server via terminal (cmd I use: 'appium'). Once i am done, I hit ctrl+c to exit but i see the above warnings and the server doesn't stop until several minutes and I have to terminate the process

**Comment by jlipps** [comment] 2017-01-05 00:02
@jmehtaebates in that case the issue you're experience may be a duplicate of https://github.com/appium/appium/issues/7328

**Comment by jmehtaebates** [comment] 2017-01-05 00:07
Looks like that. The logs look similar. Do we have any workaround for now or terminating the process is the only way for time being?

**Comment by imurchie** [comment] 2017-07-20 14:28
Terminating the process has been fixed. Closing.

**Closed by imurchie** 2017-07-20 14:28 UTC
