### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: 'Console' domain was not found

### ISSUE THREAD

**Issue by ShubhamPagarwar** [appium/appium#12542] opened 2019-04-24 14:18 UTC
I am execution script on iPhone XS MAX real device in safari.
It is giving below error:
An unknown server-side error occurred while processing the command. Original error: 'Console' domain was not found

It launches appium.io url but it unable to launch given url.

Version details:
Xcode 10.2.1
Appium 1.12.1
macOS 10.14.3

Please find the logs below:

[Appium] Welcome to Appium v1.12.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"webkitDebugProxyPort":"27753","platformVersion":12.2,"safariAllowPopups":true,"automationName":"XCUITest","browserName":"Safari","autoWebview":"true","platformName":"iOS","startIWDP":"true","udid":"00008020-000E603E016A002E","deviceName":"iPhone","wdaLocalPort":"8100"},"capabilities":{"firstMatch":[{"appium:autoWebview":"true","appium:automationName":"XCUITest","browserName":"Safari","appium:deviceName":"iPhone","platformName":"ios","appium:platformVersion":12.2,"appium:safariAllowPopups":true,"appium:startIWDP":"true","appium:udid":"00008020-000E603E016A002E","appium:wdaLocalPort":"8100","webkitDebugProxyPort":"27753"}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"webkitDebugProxyPort":"27753","platformVersion":12.2,"safariAllowPopups":true,"automationName":"XCUITest","browserName":"Safari","autoWebview":"true","platformName":"iOS","startIWDP":"true","udid":"00008020-000E603E016A002E","deviceName":"iPhone","wdaLocalPort":"8100"},null,{"firstMatch":[{"appium:autoWebview":"true","appium:automationName":"XCUITest","browserName":"Safari","appium:deviceName":"iPhone","platformName":"ios","appium:platformVersion":12.2,"appium:safariAllowPopups":true,"appium:startIWDP":"true","appium:udid":"00008020-000E603E016A002E","appium:wdaLocalPort":"8100","webkitDebugProxyPort":"27753"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1556115200318 (19:43:20 GMT+0530 (IST))
[BaseDriver] The capabilities ["webkitDebugProxyPort"] are not standard capabilities and should have an extension prefix
[Appium] Appium v1.12.1 creating new XCUITestDriver (v2.110.1) session
[Appium] Capabilities:
[Appium]   browserName: Safari
[Appium]   platformName: ios
[Appium]   webkitDebugProxyPort: 27753
[Appium]   autoWebview: true
[Appium]   automationName: XCUITest
[Appium]   deviceName: iPhone
[Appium]   platformVersion: 12.2
[Appium]   safariAllowPopups: true
[Appium]   startIWDP: true
[Appium]   udid: 00008020-000E603E016A002E
[Appium]   wdaLocalPort: 8100
[BaseDriver] W3C capabilities {"alwaysMatch":{"browserNam... and MJSONWP desired capabilities {"webkitDebugProxyPort":"27... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"browserNam...
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[BaseDriver] Capability 'autoWebview' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'startIWDP' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'wdaLocalPort' changed from string ('8100') to integer (8100). This may cause unexpected behavior
[BaseDriver] Capability 'webkitDebugProxyPort' changed from string ('27753') to integer (27753). This may cause unexpected behavior
[BaseDriver] Session created with session id: 021bf37a-55d2-40e5-9383-76d1746ac92f
[XCUITest] Current user: 'shubhampagarwar'
[XCUITest] Available devices: 00008020-000E603E016A002E
[XCUITest] Creating iDevice object with udid '00008020-000E603E016A002E'
[XCUITest] Determining device to run tests on: udid: '00008020-000E603E016A002E', real device: true
[XCUITest] Xcode version set to '10.2.1' 
[XCUITest] iOS SDK Version set to '12.2'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1556115200425 (19:43:20 GMT+0530 (IST))
[XCUITest] Safari test requested
[BaseDriver] Event 'appConfigured' logged at 1556115200426 (19:43:20 GMT+0530 (IST))
[BaseDriver] Event 'resetStarted' logged at 1556115200426 (19:43:20 GMT+0530 (IST))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1556115200426 (19:43:20 GMT+0530 (IST))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[XCUITest] Crash reports root '/Users/shubhampagarwar/Library/Logs/CrashReporter/MobileDevice/shubham iPhone' does not exist. Got nothing to gather.
[BaseDriver] Event 'logCaptureStarted' logged at 1556115200561 (19:43:20 GMT+0530 (IST))
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/Applications/Appium 6.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium 6.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"12.2\",\n      \"sdkVersion\" : \"12.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"12.2\",\n      \"ip\" : \"192.168.1.172\"\n    },\n    \"build\" : {\n      \"upgradedAt\" : \"1555852681644\",\n      \"time\" : \"Apr 24 2019 18:42:08\",\n      \"productBundleIdentifier\" : \"com.facebook.WebDriverAgentRunner\"\n    }\n  },\n  \"sessionId\" : \"031E14DC-A06B-45CD-A8A7-A6AEA1BBE2B9\",\n  \"status\" : 0\n}"
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[XCUITest] Upgrade timestamp of the currently bundled WDA: 1555852681644
[XCUITest] Upgrade timestamp of the WDA on the device: 1555852681644
[XCUITest] Will reuse previously cached WDA instance at 'http://localhost:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[BaseDriver] Event 'wdaStartAttempted' logged at 1556115200647 (19:43:20 GMT+0530 (IST))
[XCUITest] Using provided WebdriverAgent at 'http://localhost:8100/'
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"12.2\",\n      \"sdkVersion\" : \"12.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"12.2\",\n      \"ip\" : \"192.168.1.172\"\n    },\n    \"build\" : {\n      \"upgradedAt\" : \"1555852681644\",\n      \"time\" : \"Apr 24 2019 18:42:08\",\n      \"productBundleIdentifier\" : \"com.facebook.WebDriverAgentRunner\"\n    }\n  },\n  \"sessionId\" : \"031E14DC-A06B-45CD-A8A7-A6AEA1BBE2B9\",\n  \"status\" : 0\n}"
[BaseDriver] Event 'wdaSessionAttempted' logged at 1556115200660 (19:43:20 GMT+0530 (IST))
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":["-u","http://appium.io"],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[WD Proxy] Got response with status 200: {"value":{"sessionId":"9657FBBF-3113-450C-94ED-427FE149E8A3","capabilities":{"device":"iphone","browserName":"Safari","sdkVersion":"12.2","CFBundleIdentifier":"com.apple.mobilesafari"}},"sessionId":"9657FBBF-3113-450C-94ED-427FE149E8A3","status":0}
[BaseDriver] Event 'wdaSessionStarted' logged at 1556115201938 (19:43:21 GMT+0530 (IST))
[WD Proxy] Matched '/url' to command name 'setUrl'
[WD Proxy] Proxying [POST /url] to [POST http://localhost:8100/session/9657FBBF-3113-450C-94ED-427FE149E8A3/url] with body: {"url":"http://appium.io"}
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[WD Proxy] Got response with status 200: {"value":{},"sessionId":"9657FBBF-3113-450C-94ED-427FE149E8A3","status":0}
[BaseDriver] Event 'wdaStarted' logged at 1556115202148 (19:43:22 GMT+0530 (IST))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[BaseDriver] Event 'orientationSet' logged at 1556115202149 (19:43:22 GMT+0530 (IST))
[BaseDriver] Event 'iwdpStarting' logged at 1556115202149 (19:43:22 GMT+0530 (IST))
[iOS] Starting ios_webkit_debug_proxy at port 27753 on device 00008020-000E603E016A002E
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[BaseDriver] Event 'iwdpStarted' logged at 1556115202238 (19:43:22 GMT+0530 (IST))
[XCUITest] Started ios_webkit_debug proxy server at: http://localhost:27753
[XCUITest] Waiting for initial webview
[iOS] Waiting for 3000 ms before navigating to view.
[iOS] Navigating to most recently opened webview
[iOS] Retrieving contexts and views
[iOS] Selecting by url: true (expected url: 'http://appium.io')
[RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[RemoteDebugger] Sending request to: http://localhost:27753/json
[RemoteDebugger] Page element JSON: [{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:27753/devtools/page/1","faviconUrl":"","thumbnailUrl":"/thumb/about:blank","title":"","url":"about:blank","webSocketDebuggerUrl":"ws://localhost:27753/devtools/page/1","appId":"PID:388"}]
[iOS] Retrieving contexts and views
[iOS] Selecting by url: true (expected url: 'http://appium.io')
[RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[RemoteDebugger] Sending request to: http://localhost:27753/json
[RemoteDebugger] Page element JSON: [{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:27753/devtools/page/1","faviconUrl":"","thumbnailUrl":"/thumb/about:blank","title":"","url":"about:blank","webSocketDebuggerUrl":"ws://localhost:27753/devtools/page/1","appId":"PID:388"}]
[iOS] Picking webview 'WEBVIEW_1'
[iOS] Attempting to set context to 'WEBVIEW_1'
[RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/1
[RemoteDebugger] Starting to listen for JavaScript console
[RemoteDebugger] Sending WebKit data: {"method":"Console.enable","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true}}
[RemoteDebugger] Webkit response timeout: 5000
[RemoteDebugger] Received WebKit data: '{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"page-1","type":"page"}}}'
[RemoteDebugger] Found method 'Target.targetCreated'
[RemoteDebugger] There is no handler scheduled for method 'Target.targetCreated' in the recent message
[RemoteDebugger] Received WebKit data: '{"error":{"code":-32601,"message":"'Console' domain was not found","data":[{"code":-32601,"message":"'Console' domain was not found"}]},"id":1}'
[RemoteDebugger] Found method 'Console.enable' for '1' message
[XCUITest] [object Object]
[WD Proxy] Matched '/session/021bf37a-55d2-40e5-9383-76d1746ac92f' to command name 'deleteSession'
[WD Proxy] Proxying [DELETE /session/021bf37a-55d2-40e5-9383-76d1746ac92f] to [DELETE http://localhost:8100/session/9657FBBF-3113-450C-94ED-427FE149E8A3] with no body
[WD Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"7FAAE7F6-D1BC-4B13-AF54-607C89D5C6AE\",\n  \"status\" : 0\n}"
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[XCUITest] In a web session. Removing remote debugger
[RemoteDebugger] Disconnecting from WebKit remote debugger
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[RemoteDebugger] WebKit remote debugger socket disconnected
[BaseDriver] Event 'newSessionStarted' logged at 1556115206297 (19:43:26 GMT+0530 (IST))
[W3C] Encountered internal error running command: 'Console' domain was not found
[HTTP] <-- POST /wd/hub/session 500 5981 ms - 694
[HTTP]

**Comment by ShubhamPagarwar** [comment] 2019-04-24 14:19
Please help me out to resolve this issue

**Comment by imurchie** [comment] 2019-04-24 14:20
Update to the latest beta to get full support for iOS 12.2.

`npm uninstall -g appium && npm install -g appium@beta`

**Comment by mykola-mokhnach** [comment] 2019-04-24 14:26
Duplicate of https://github.com/appium/appium/issues/12518

**Closed by mykola-mokhnach** 2019-04-24 14:26 UTC
