### ISSUE TITLE
Appium Error>[MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: 'com.****.activity.****LauncherActivity' never started Appium Error>    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)

### ISSUE THREAD

**Issue by avrahamShutterFly** [appium/appium#9170] opened 2017-09-05 10:21 UTC
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version : 1.6.5-betta
* Mac 
* Node.js version: v7.5.0
* Mobile platform/version under test: Samsung S7 verizon 6.0.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details
When I run from eclipse or Jenkins
## Link to Appium logs
Any time you see in log  **** I put it instead our company name
Appium log:
08:22:36 Appium Output>[debug] [ADB] Incorrect package and activity. Retrying.
08:22:37 Appium Output>[debug] [ADB] Getting focused package and activity
08:22:37 Appium Output>[debug] [ADB] Getting connected devices...
08:22:37 Appium Output>[debug] [ADB] 1 device(s) connected
08:22:37 Appium Output>[debug] [ADB] Running '/Users/automacil/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","488a9be5","shell","dumpsys","window","windows"]
08:22:37 Appium Output>[debug] [ADB] Found package: 'com.--.staging' and fully qualified activity name : 'com.--.activity.--MainActivity'
08:22:37 Appium Output>[debug] [ADB] Incorrect package and activity. Retrying.
08:22:38 Appium Output>[debug] [ADB] Getting focused package and activity
08:22:38 Appium Output>[debug] [ADB] Getting connected devices...
08:22:38 Appium Output>[debug] [ADB] 1 device(s) connected
08:22:38 Appium Output>[debug] [ADB] Running '/Users/automacil/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","488a9be5","shell","dumpsys","window","windows"]
08:22:38 Appium Output>[debug] [ADB] Found package: 'com.--.staging' and fully qualified activity name : 'com.--.activity.--MainActivity'
08:22:38 Appium Output>[debug] [ADB] Incorrect package and activity. Retrying.
08:22:39 Appium Output>[debug] [ADB] Getting focused package and activity
08:22:39 Appium Output>[debug] [ADB] Getting connected devices...
08:22:39 Appium Output>[debug] [ADB] 1 device(s) connected
08:22:39 Appium Output>[debug] [ADB] Running '/Users/automacil/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","488a9be5","shell","dumpsys","window","windows"]
08:22:39 Appium Output>[debug] [ADB] Found package: 'com.--.staging' and fully qualified activity name : 'com.--.activity.--MainActivity'
08:22:39 Appium Output>[debug] [ADB] Incorrect package and activity. Retrying.
08:22:39 Appium Output>[debug] [ADB] Getting focused package and activity
08:22:39 Appium Output>[debug] [ADB] Getting connected devices...
08:22:39 Appium Output>[debug] [ADB] 1 device(s) connected
08:22:39 Appium Output>[debug] [ADB] Running '/Users/automacil/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","488a9be5","shell","dumpsys","window","windows"]
08:22:40 Appium Output>[debug] [ADB] Found package: 'com.--.staging' and fully qualified activity name : 'com.--.activity.--MainActivity'
08:22:40 Appium Output>[debug] [ADB] Incorrect package and activity. Retrying.
08:22:40 Appium Output>[debug] [ADB] Getting focused package and activity
08:22:40 Appium Output>[debug] [ADB] Getting connected devices...
08:22:40 Appium Output>[debug] [ADB] 1 device(s) connected
08:22:40 Appium Output>[debug] [ADB] Running '/Users/automacil/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","488a9be5","shell","dumpsys","window","windows"]
08:22:40 Appium Output>[debug] [ADB] Found package: 'com.--.staging' and fully qualified activity name : 'com.--.activity.--MainActivity'
08:22:40 Appium Output>[debug] [ADB] Incorrect package and activity. Retrying.
08:22:41 Appium Output>[debug] [ADB] Getting focused package and activity
08:22:41 Appium Output>[debug] [ADB] Getting connected devices...
08:22:41 Appium Output>[debug] [ADB] 1 device(s) connected
08:22:41 Appium Output>[debug] [ADB] Running '/Users/automacil/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","488a9be5","shell","dumpsys","window","windows"]
08:22:41 Appium Output>[debug] [ADB] Found package: 'com.****.staging' and fully qualified activity name : 'com.****.activity.****MainActivity'
08:22:41 Appium Output>[debug] [ADB] Incorrect package and activity. Retrying.
08:22:42 Appium Output>[debug] [ADB] Getting focused package and activity
08:22:42 Appium Output>[debug] [ADB] Getting connected devices...
08:22:42 Appium Output>[debug] [ADB] 1 device(s) connected
08:22:42 Appium Output>[debug] [ADB] Running '/Users/automacil/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","488a9be5","shell","dumpsys","window","windows"]
08:22:42 Appium Output>[debug] [ADB] Found package: 'com.--.staging' and fully qualified activity name : 'com.--.activity.--MainActivity'
08:22:42 Appium Output>[debug] [ADB] Incorrect package and activity. Retrying.
08:22:43 Appium Error>[ADB] Error: Error occured while starting App. Original error: 'com.--.activity.--LauncherActivity' never started
08:22:43 Appium Error>    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
08:22:43 Appium Error>    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:101:9)
08:22:43 Appium Error>    at tryCatch (/Users/automacil/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
08:22:43 Appium Error>    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/automacil/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
08:22:43 Appium Error>    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/automacil/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
08:22:43 Appium Error>    at GeneratorFunctionPrototype.invoke (/Users/automacil/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
08:22:43 Appium Error> Error: Error occured while starting App. Original error: 'com.--.activity.--LauncherActivity' never started
08:22:43 Appium Error>    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
08:22:43 Appium Error>    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:101:9)
08:22:43 Appium Error>    at tryCatch (/Users/automacil/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
08:22:43 Appium Error>    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/automacil/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
08:22:43 Appium Error>    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/automacil/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
08:22:43 Appium Error>    at GeneratorFunctionPrototype.invoke (/Users/automacil/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
08:22:43 Appium Output>[debug] [AndroidDriver] Shutting down Android driver
08:22:43 Appium Output>[debug] [ADB] Getting connected devices...
08:22:43 Appium Output>[debug] [ADB] 1 device(s) connected
08:22:43 Appium Output>[debug] [ADB] Running '/Users/automacil/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","488a9be5","shell","am","force-stop","com.--.staging"]
08:22:44 Appium Output>[debug] [ADB] Pressing the HOME button
08:22:44 Appium Output>[debug] [ADB] Getting connected devices...
08:22:44 Appium Output>[debug] [ADB] 1 device(s) connected
08:22:44 Appium Output>[debug] [ADB] Running '/Users/automacil/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","488a9be5","shell","input","keyevent",3]
08:22:45 Appium Output>[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
08:22:45 Appium Output>[debug] [AndroidBootstrap] Received command result from bootstrap
08:22:45 Appium Output>[debug] [UiAutomator] Shutting down UiAutomator
08:22:45 Appium Output>[debug] [UiAutomator] Moving to state 'stopping'
08:22:45 Appium Output>[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
08:22:45 Appium Output>[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
08:22:45 Appium Output>[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
08:22:45 Appium Output>[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
08:22:45 Appium Output>[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
08:22:45 Appium Output>[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
08:22:45 Appium Output>[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
08:22:45 Appium Output>[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
08:22:45 Appium Output>[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
08:22:45 Appium Output>[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1
08:22:45 Appium Output>[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0
08:22:45 Appium Output>[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=
08:22:45 Appium Output>[debug] [AndroidBootstrap] [UIAUTO STDOUT] Test results for WatcherResultPrinter=.
08:22:45 Appium Output>[debug] [AndroidBootstrap] [UIAUTO STDOUT] Time: 27.815
08:22:45 Appium Output>[debug] [AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
08:22:45 Appium Output>[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
08:22:45 Appium Output>[debug] [UiAutomator] UiAutomator shut down normally
08:22:45 Appium Output>[debug] [UiAutomator] Moving to state 'stopped'
08:22:45 Appium Output>[debug] [ADB] Attempting to kill all uiautomator processes
08:22:45 Appium Output>[debug] [ADB] Getting all processes with uiautomator
08:22:45 Appium Output>[debug] [ADB] Getting connected devices...
08:22:45 Appium Output>[debug] [ADB] 1 device(s) connected
08:22:45 Appium Output>[debug] [ADB] Running '/Users/automacil/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","488a9be5","shell","ps"]
08:22:45 Appium Output>[ADB] No uiautomator process found to kill, continuing...
08:22:45 Appium Output>[debug] [UiAutomator] Moving to state 'stopped'
08:22:45 Appium Output>[debug] [Logcat] Stopping logcat capture
08:22:45 Appium Output>[debug] [ADB] Getting connected devices...
08:22:45 Appium Output>[debug] [ADB] 1 device(s) connected
08:22:45 Appium Output>[debug] [ADB] Running '/Users/automacil/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","488a9be5","shell","am","force-stop","io.appium.unlock"]
08:22:45 Appium Output>[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
08:22:45 Appium Error>[MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: 'com.****.activity.****LauncherActivity' never started
08:22:45 Appium Error>    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
08:22:45 Appium Error>    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:101:9)
08:22:45 Appium Error>    at tryCatch (/Users/automacil/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
08:22:45 Appium Error>    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/automacil/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
08:22:45 Appium Error>    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/automacil/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
08:22:45 Appium Error>    at GeneratorFunctionPrototype.invoke (/Users/automacil/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
08:22:46 Appium Output>[HTTP] <-- POST /wd/hub/session 500 43232 ms - 253

**Comment by mykola-mokhnach** [comment] 2017-09-05 12:39
You need to set correct activity names to _appActivity_ and, probably, to _appWaitActivity_ capabilities. Closed as duplicate.

**Closed by mykola-mokhnach** 2017-09-05 12:39 UTC

**Comment by avrahamShutterFly** [comment] 2017-09-05 13:15
Why you I run the same project and the same configuration and its working in one machine and in another one won't

**Comment by mykola-mokhnach** [comment] 2017-09-05 13:24
I cannot say for sure why it works on the other machine. There might be multiple reasons. I can only do conclusions from what I see in the log and in previous issue reports.

**Comment by avrahamShutterFly** [comment] 2017-09-05 13:40
@mykola-mokhnach I set on app=<path to APK>, why do I need more capabilities as appActivity/appWaitActivity?

**Comment by avrahamShutterFly** [comment] 2017-09-05 14:14
OK, I add this capabilities and it's work but it's strange that it's work on one machine and in another  not...

**Comment by imurchie** [comment] 2017-09-05 14:26
The problem is that the Android tools are not necessarily consistent on what they extract, both beforehand (how Appium pulls what it expects to be running from the app) and during the run (when it is trying to figure out what is running). Different versions (even patch versions) of the tools can differ in what they report.

Explicit naming (either of the `appPackage`/`appActivity`, which specifies what is launched, or `appWaitPackage`/`appWaitActivity`, which specifies what to look for to have launched) is often necessary.

**Comment by avrahamShutterFly** [comment] 2017-09-05 14:58
OK, Thanks @imurchie

**Comment by avrahamShutterFly** [comment] 2017-09-06 06:21
@imurchie @mykola-mokhnach  After I add appActivity and appPackage it's working but after 10 second the app closed, but in anther machine it's works fine, why?
