### ISSUE TITLE
Android Simulator -Hybrid App - Chrome version must be >= 53.0.2785.0

### ISSUE THREAD

**Issue by siggerzz** [appium/appium#8181] opened 2017-04-06 10:12 UTC
## The problem

When attempting to execute a test for my hybrid app in a simulator, I get the following error:

[Error: unknown error: Chrome version must be >= 53.0.2785.0
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 10.0.14393 x86_64)]

Downgrading the Appium Chromedriver to 2.20 seems to fix the issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows/MacOS
* Node.js version (unless using Appium.app|exe): 4.6.1
* Mobile platform/version under test: Android/7.1.1
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://gist.github.com/siggerzz/d4c693ba1902a4b761a19d427e22bf0d

**Comment by mykola-mokhnach** [comment] 2017-04-06 10:20
Closed as duplicate of https://github.com/appium/appium/issues/7138

**Closed by mykola-mokhnach** 2017-04-06 10:20 UTC
Labels: NeedsTriage
