### ISSUE TITLE
Unable to move seek bar in Anoid App and giving error "The coordinates provided to an interactions operation are invalid"

### ISSUE THREAD

**Issue by sanjaykumar5115** [appium/appium#7285] opened 2016-11-24 09:08 UTC
Hi All,

I am using Appium windows App with .net driver client. While i am trying to move seek bar in App, it is giving following error.
--------Log cat---------------------------
```
info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
info: Appium REST http interface listener started on 127.0.0.1:4723
info: [debug] Non-default server args: {"address":"127.0.0.1","bootstrapPort":47
25,"noReset":true,"localTimezone":true,"selendroidPort":8082,"chromeDriverPort":
9516}
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"Appium"
,"deviceName":"MotoG3 7605","app":"E:\\selenium-beanbag\\BeanbagApp-debug_public
_network.apk","browserName":"Andriod","platformName":"Android","newCommandTimeou
t":300,"platform":"WINDOWS","platformVersion":"4.4","autoWebview":false,"ignoreU
nimportantViews":false}}
info: Client User-Agent string: undefined
info: [debug] The following desired capabilities were provided, but not recogniz
ed by appium. They will be passed on to any other services running on this serve
r. : platform
info: [debug] No appActivity desired capability or server param. Parsing from ap
k.
info: [debug] No appPackage desired capability or server param. Parsing from apk
.
info: [debug] Using local app from desired caps: E:\selenium-beanbag\BeanbagApp-
debug_public_network.apk
info: [debug] Creating new appium session 6d5f5c06-ea57-40a7-aa62-7bc51cfb363b
info: Starting android appium
info: [debug] Getting Java version
info: Java version is: 1.6.0_29
info: [debug] Checking whether adb is present
info: [debug] Using adb from C:\AndroidSdk\sdk\platform-tools\adb.exe
info: [debug] Parsing package and activity from app manifest
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from C:\AndroidSdk\sdk\build-tools\android-4.3\aapt.exe

info: [debug] Extracting package and launch activity from manifest.
info: [debug] executing cmd: C:\AndroidSdk\sdk\build-tools\android-4.3\aapt.exe
dump badging E:\selenium-beanbag\BeanbagApp-debug_public_network.apk
info: [debug] badging package: com.secure.beanbag
info: [debug] badging act: com.secure.beanbag.app.Core.View.SplashActivity
info: [debug] Parsed package and activity are: com.secure.beanbag/com.secure.bea
nbag.app.Core.View.SplashActivity
info: [debug] Using fast reset? false
info: [debug] Preparing device for session
info: [debug] Checking whether app is actually present
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe devices
info: [debug] 1 device(s) connected
info: Found device ZY22282R9H
info: [debug] Setting device id to ZY22282R9H
info: [debug] Waiting for device to be ready and to respond to shell commands (t
imeout = 5)
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H wait-for-device
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Getting device API level
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 23
info: Device API level is: 23
info: [debug] Extracting strings for language: default
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H shell "getprop persist.sys.language"
info: [debug] Current device persist.sys.language:
info: [debug] java -jar "E:\appiumsetup\Appium\node_modules\appium\node_modules\
appium-adb\jars\appium_apk_tools_1.6.jar" "stringsFromApk" "E:\selenium-beanbag\
BeanbagApp-debug_public_network.apk" "C:\Users\sanjaykr\AppData\Local\Temp\com.s
ecure.beanbag"
info: [debug] No strings.xml for language '', getting default strings.xml
info: [debug] java -jar "E:\appiumsetup\Appium\node_modules\appium\node_modules\
appium-adb\jars\appium_apk_tools_1.6.jar" "stringsFromApk" "E:\selenium-beanbag\
BeanbagApp-debug_public_network.apk" "C:\Users\sanjaykr\AppData\Local\Temp\com.s
ecure.beanbag"
warn: Error getting strings.xml from apk
info: [debug] Exception in thread "main" brut.androlib.AndrolibException: Could
not decode arsc file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:54)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibRes
ources.java:540)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.jav
a:76)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.jav
a:68)
        at io.appium.apktools.StringsXML.run(StringsXML.java:84)
        at io.appium.apktools.Main.main(Main.java:31)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
        at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
        at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:43)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:10
0)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:81)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
        ... 5 more
Picked up JAVA_TOOL_OPTIONS: -agentlib:jvmhook
Picked up _JAVA_OPTIONS: -Xrunjvmhook -Xbootclasspath/a:"C:\Program Files (x86)\
HP\Unified Functional Testing\bin\java_shared\classes";"C:\Program Files (x86)\H
P\Unified Functional Testing\bin\java_shared\classes\jasmine.jar"

warn: Could not get strings, continuing anyway
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H shell "echo '{}' > /data/local/tmp/strings.json"
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from C:\AndroidSdk\sdk\build-tools\android-4.3\aapt.exe

info: [debug] Retrieving process from manifest.
info: [debug] executing cmd: C:\AndroidSdk\sdk\build-tools\android-4.3\aapt.exe
dump xmltree E:\selenium-beanbag\BeanbagApp-debug_public_network.apk AndroidMani
fest.xml
info: [debug] Set app process to: com.secure.beanbag
info: [debug] Not uninstalling app since server not started with --full-reset
info: [debug] Checking app cert for E:\selenium-beanbag\BeanbagApp-debug_public_
network.apk.
info: [debug] executing cmd: java -jar E:\appiumsetup\Appium\node_modules\appium
\node_modules\appium-adb\jars\verify.jar E:\selenium-beanbag\BeanbagApp-debug_pu
blic_network.apk
info: [debug] App already signed.
info: [debug] Zip-aligning E:\selenium-beanbag\BeanbagApp-debug_public_network.a
pk
info: [debug] Checking whether zipalign is present
info: [debug] Using zipalign from C:\AndroidSdk\sdk\build-tools\25.0.0\zipalign.
exe
info: [debug] Zip-aligning apk.
info: [debug] executing cmd: C:\AndroidSdk\sdk\build-tools\25.0.0\zipalign.exe -
f 4 E:\selenium-beanbag\BeanbagApp-debug_public_network.apk C:\Users\sanjaykr\Ap
pData\Local\Temp\1161024-7112-1dnd415\appium.tmp
info: [debug] MD5 for app is 944c3a9aac1fde44d324b8412f6c6b94
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H shell "ls /data/local/tmp/944c3a9aac1fde44d324b8412f6c6b94.apk"
info: [debug] Getting install status for com.secure.beanbag
info: [debug] Getting device API level
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 23
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H shell "pm list packages -3 com.secure.beanbag"
info: [debug] App is installed
info: [debug] Forwarding system:4725 to device:4724
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H forward tcp:4725 tcp:4724
info: [debug] Pushing appium bootstrap to device...
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H push "E:\\appiumsetup\\Appium\\node_modules\\appium\\build\\android_bootstra
p\\AppiumBootstrap.jar" /data/local/tmp/
info: [debug] Pushing settings apk to device...
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H install "E:\appiumsetup\Appium\node_modules\appium\build\settings_apk\settin
gs_apk-debug.apk"
info: [debug] Pushing unlock helper app to device...
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H install "E:\appiumsetup\Appium\node_modules\appium\build\unlock_apk\unlock_a
pk-debug.apk"
info: Starting App
info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H shell "ps 'uiautomator'"
info: [debug] No matching processes found
info: [debug] Running bootstrap
info: [debug] spawning: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282R9H s
hell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Boot
strap -e pkg com.secure.beanbag -e disableAndroidWatchers false
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRun
ner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.andro
id.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] [BOOTSTRAP] [debug] json loading complete.
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] Waking up device if it's not alive
info: [debug] Pushing command to appium work queue: ["wake",{}]
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action"
:"wake","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: wake
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H shell "dumpsys window"
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
info: [debug] Screen already unlocked, continuing.
info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action"
:"getDataDir","params":{}}
info: [debug] dataDir set to: /data/local/tmp
info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy"
,{"compressLayout":false}]
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data\
/local\/tmp"}
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action"
:"compressedLayoutHierarchy","params":{"compressLayout":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
info: [debug] Getting device API level
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H shell "getprop ro.build.version.sdk"
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":false}
info: [debug] Device is at API Level 23
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H shell "am start -S -a android.intent.action.MAIN -c android.intent.category.
LAUNCHER -f 0x10200000 -n com.secure.beanbag/com.secure.beanbag.app.Core.View.Sp
lashActivity"
info: [debug] Waiting for pkg "com.secure.beanbag" and activity "com.secure.bean
bag.app.Core.View.SplashActivity" to be focused
info: [debug] Getting focused package and activity
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H shell "dumpsys window windows"
info: [debug] executing cmd: C:\AndroidSdk\sdk\platform-tools\adb.exe -s ZY22282
R9H shell "getprop ro.build.version.release"
info: [debug] Device is at release version 6.0
info: [debug] Device launched! Ready for commands
info: [debug] Setting command timeout to 300 secs
info: [debug] Appium session started with sessionId fcfbaa8e-9572-484b-9432-e0cb
7320cae4
info: <-- POST /wd/hub/session 303 8272.006 ms - 74
info: --> GET /wd/hub/session/fcfbaa8e-9572-484b-9432-e0cb7320cae4 {}
info: [debug] Responding to client with success: {"status":0,"value":{"platform"
:"WINDOWS","browserName":"Andriod","platformVersion":"6.0","webStorageEnabled":f
alse,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"ne
tworkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desir
ed":{"automationName":"Appium","deviceName":"MotoG3 7605","app":"E:\\selenium-be
anbag\\BeanbagApp-debug_public_network.apk","browserName":"Andriod","platformNam
e":"Android","newCommandTimeout":300,"platform":"WINDOWS","platformVersion":"4.4
","autoWebview":false,"ignoreUnimportantViews":false},"automationName":"Appium",
"deviceName":"ZY22282R9H","app":"E:\\selenium-beanbag\\BeanbagApp-debug_public_n
etwork.apk","platformName":"Android","newCommandTimeout":300,"autoWebview":false
,"ignoreUnimportantViews":false},"sessionId":"fcfbaa8e-9572-484b-9432-e0cb7320ca
e4"}
info: <-- GET /wd/hub/session/fcfbaa8e-9572-484b-9432-e0cb7320cae4 200 5.544 ms
- 835 {"status":0,"value":{"platform":"WINDOWS","browserName":"Andriod","platfor
mVersion":"6.0","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnab
led":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationConte
xtEnabled":false,"warnings":{},"desired":{"automationName":"Appium","deviceName"
:"MotoG3 7605","app":"E:\\selenium-beanbag\\BeanbagApp-debug_public_network.apk"
,"browserName":"Andriod","platformName":"Android","newCommandTimeout":300,"platf
orm":"WINDOWS","platformVersion":"4.4","autoWebview":false,"ignoreUnimportantVie
ws":false},"automationName":"Appium","deviceName":"ZY22282R9H","app":"E:\\seleni
um-beanbag\\BeanbagApp-debug_public_network.apk","platformName":"Android","newCo
mmandTimeout":300,"autoWebview":false,"ignoreUnimportantViews":false},"sessionId
":"fcfbaa8e-9572-484b-9432-e0cb7320cae4"}
info: --> POST /wd/hub/session/fcfbaa8e-9572-484b-9432-e0cb7320cae4/element {"us
ing":"id","value":"com.secure.beanbag:id/seek_mode_heating"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"id","se
lector":"com.secure.beanbag:id/seek_mode_heating","context":"","multiple":false}
]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action"
:"find","params":{"strategy":"id","selector":"com.secure.beanbag:id/seek_mode_he
ating","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding com.secure.beanbag:id/seek_mode_heatin
g using ID with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.
secure.beanbag:id/seek_mode_heating]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"ELEMEN
T":"1"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":
"1"},"sessionId":"fcfbaa8e-9572-484b-9432-e0cb7320cae4"}
info: <-- POST /wd/hub/session/fcfbaa8e-9572-484b-9432-e0cb7320cae4/element 200
57.610 ms - 87 {"status":0,"value":{"ELEMENT":"1"},"sessionId":"fcfbaa8e-9572-48
4b-9432-e0cb7320cae4"}
info: --> GET /wd/hub/session/fcfbaa8e-9572-484b-9432-e0cb7320cae4/element/1/loc
ation {}
warn: location will be removed in a future version of Appium, please use locatio
n_in_view
info: [debug] Pushing command to appium work queue: ["element:getLocation",{"ele
mentId":"1"}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action"
:"element:getLocation","params":{"elementId":"1"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getLocation
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"x":124
,"y":676}}
info: [debug] Responding to client with success: {"status":0,"value":{"x":124,"y
":676},"sessionId":"fcfbaa8e-9572-484b-9432-e0cb7320cae4"}
info: <-- GET /wd/hub/session/fcfbaa8e-9572-484b-9432-e0cb7320cae4/element/1/loc
ation 200 42.172 ms - 89 {"status":0,"value":{"x":124,"y":676},"sessionId":"fcfb
aa8e-9572-484b-9432-e0cb7320cae4"}
info: --> GET /wd/hub/session/fcfbaa8e-9572-484b-9432-e0cb7320cae4/element/1/siz
e {}
info: [debug] Pushing command to appium work queue: ["element:getSize",{"element
Id":"1"}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action"
:"element:getSize","params":{"elementId":"1"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getSize
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"width"
:516,"height":36}}
info: [debug] Responding to client with success: {"status":0,"value":{"width":51
6,"height":36},"sessionId":"fcfbaa8e-9572-484b-9432-e0cb7320cae4"}
info: <-- GET /wd/hub/session/fcfbaa8e-9572-484b-9432-e0cb7320cae4/element/1/siz
e 200 25.903 ms - 97 {"status":0,"value":{"width":516,"height":36},"sessionId":"
fcfbaa8e-9572-484b-9432-e0cb7320cae4"}
info: --> GET /wd/hub/session/fcfbaa8e-9572-484b-9432-e0cb7320cae4/element/1/loc
ation {}
info: [debug] Pushing command to appium work queue: ["element:getLocation",{"ele
mentId":"1"}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action"
:"element:getLocation","params":{"elementId":"1"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getLocation
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"x":124
,"y":676}}
info: [debug] Responding to client with success: {"status":0,"value":{"x":124,"y
":676},"sessionId":"fcfbaa8e-9572-484b-9432-e0cb7320cae4"}
info: <-- GET /wd/hub/session/fcfbaa8e-9572-484b-9432-e0cb7320cae4/element/1/loc
ation 200 36.516 ms - 89 {"status":0,"value":{"x":124,"y":676},"sessionId":"fcfb
aa8e-9572-484b-9432-e0cb7320cae4"}
info: --> POST /wd/hub/session/fcfbaa8e-9572-484b-9432-e0cb7320cae4/touch/perfor
m {"actions":[{"action":"press","options":{"x":124,"y":676}},{"action":"moveTo",
"options":{"x":516,"y":676}}]}
info: [debug] Pushing command to appium work queue: ["element:touchDown",{"x":12
4,"y":676}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action"
:"element:touchDown","params":{"x":124,"y":676}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchDown
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][720,1184]
info: [debug] [BOOTSTRAP] [debug] Performing TouchDown using element? false x: 1
24, y: 676
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":64
0,"y":1352}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action"
:"element:touchMove","params":{"x":640,"y":1352}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][720,1184]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":29,"value":"Coordi
nate [x=640.0, y=1352.0] is outside of element rect: [0,0][720,1184]"}
info: [debug] Responding to client with error: {"status":29,"value":{"message":"
The coordinates provided to an interactions operation are invalid.","origValue":
"Coordinate [x=640.0, y=1352.0] is outside of element rect: [0,0][720,1184]"},"s
essionId":"fcfbaa8e-9572-484b-9432-e0cb7320cae4"}
info: <-- POST /wd/hub/session/fcfbaa8e-9572-484b-9432-e0cb7320cae4/touch/perfor
m 500 25.413 ms - 242
```
____________End Log cat_____________________________________

My code  is as

```java
            AndroidElement seek_bar = FrameworkCommonLibrary.AppiumAndroiddriver.FindElement(By.Id("com.secure.beanbag:id/seek_mode_heating"));
            // get start co-ordinate of seekbar
            int start = seek_bar.Location.X;
            //Get width of seekbar
            int end = seek_bar.Size.Width;
            
            //get location of seekbar vertically
            int y = seek_bar.Location.Y;

            // Select till which position you want to move the seekbar
            TouchAction action = new TouchAction(FrameworkCommonLibrary.AppiumAndroiddriver);

            //Move it will the end
            action.Press(start, y).MoveTo(end, y).Perform();
```
Environment -
1. net driver version -2.0.1.1
2. Window 7
3. visual studio
4. Latest Appium APP v1.4.16
5. Device Android-6.0 

Please help me what i do

**Comment by dpgraham** [comment] 2016-11-25 20:03
Duplicate of https://github.com/appium/appium/issues/7291

**Closed by dpgraham** 2016-11-25 20:03 UTC
Labels: NeedsTriage
