### ISSUE TITLE
Xcode 12.5.1 Can't dismiss keyboard

### ISSUE THREAD

**Issue by extr3mal** [appium/appium#15618] opened 2021-07-08 14:43 UTC
## The problem

When i run test on latest xcode , i get an error 

InvalidElementStateException: Message: Error Domain=com.facebook.WebdriverAgent Code=1 "Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test."

**Comment by mykola-mokhnach** [comment] 2021-07-08 14:50
Duplicate of https://github.com/appium/appium/issues/15073

**Closed by mykola-mokhnach** 2021-07-08 14:50 UTC
