### ISSUE TITLE
Cannot install drivers with beta 26 and up, breaks node_modules

### ISSUE THREAD

**Issue by nextlevelbeard** [appium/appium#16650] opened 2022-03-24 10:30 UTC
```shell
npm i appium@2.0.0-beta.26 --save-dev
npx appium driver install uiautomator2
✖ Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: Encountered an error when installing package: npm command 'install --no-save --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code 1.

STDOUT:


STDERR:
...
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "from" argument must be of type string. Received undefined
{
  "error": {
    "code": "ERR_INVALID_ARG_TYPE",
    "summary": "The \"from\" argument must be of type string. Received undefined",
    "detail": ""
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2022-03-24T10_25_55_907Z-debug-0.log
```

**Comment by GDiBiase** [comment] 2022-03-24 16:01
same on version 2.0.0-beta.26, after install the iOS and android driver , when launch Appium command , this error appear: 

`[Appium] Welcome to Appium v2.0.0-beta.27
[Appium] Attempting to load driver xcuitest...
[Appium] Could not load driver 'xcuitest', so it will not be available. Error in loading the driver was: Cannot find module`

**Comment by boneskull** [comment] 2022-03-25 17:44
@nextlevelbeard I'm having trouble reproducing this. Can you please provide your `package.json`? Do you have an `APPIUM_HOME` set?

**Comment by boneskull** [comment] 2022-03-25 17:45
@GDiBiase How did you install the drivers?

**Comment by boneskull** [comment] 2022-03-25 17:47
Also if you have `~/.appium/extensions.yaml` or `./node_modules/.cache/appium/extensions.yaml` please provide these

**Comment by boneskull** [comment] 2022-03-25 17:48
(I'm guessing what happened in @GDiBiase's case was that Appium could not find the driver where `extensions.yaml` thought it was, and it then found a new path for it and updated `extensions.yaml` accordingly.  I'm curious if it works again now without error)

**Comment by boneskull** [comment] 2022-03-25 17:49
@nextlevelbeard Please upgrade to 2.0.0-beta.27 and try again.

**Comment by GDiBiase** [comment] 2022-03-28 08:31
@boneskull i install via terminal : 

npm install -g appium@next
appium driver install xcuitest
appium driver install uiautomator2

**Comment by boneskull** [comment] 2022-03-29 18:40
This is a duplicate of #16674. Or rather #16674 is a dupe of this.  Either way, this one should be closed.

**Closed by boneskull** 2022-03-29 18:40 UTC
Labels: Bug, v2

**Comment by mwmcode** [comment] 2022-06-20 19:52
Hello,

I'm currently facing the same issue with 2.0.0-beta.40 (Node 16.15): 
```sh
❯❯❯❯ appium --version
2.0.0-beta.40
📂︎〖Desktop〗
❯❯❯❯ appium driver install xcuitest
✖ Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver'
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --save-exact --global-style --no-package-lock appium-xcuitest-driver --json' failed with code 1.

STDOUT:


STDERR:
npm ERR! Cannot read properties of null (reading 'parent')
{
  "error": {
    "code": null,
    "summary": "Cannot read properties of null (reading 'parent')",
    "detail": ""
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mm/.npm/_logs/2022-06-20T19_48_59_171Z-debug-0.log

```
