### ISSUE TITLE
i'm getting errors like this, what can i do for solve?

### ISSUE THREAD

**Issue by getahead92** [appium/appium#12740] opened 2019-06-08 20:25 UTC
## The problem

An unknown server-side error occurred while processing the command. Original error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\getah\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release' exited with code 3221226356'; Stderr: ''; Code: '3221226356'

## Environment

* Appium version (or git revision) that exhibits the issue:          ==          appium 1.13.0
* Last Appium version that did not exhibit the issue (if applicable):         ==     none
* Desktop OS/version used to run Appium:           ==       windows / 10
* Node.js version (unless using Appium.app|exe): ==        appium.exe
* Npm or Yarn package manager:                         ==        composer
* Mobile platform/version under test:                   ==       Android / 7.0 x86
* Real device or emulator/simulator:                     ==       emulator
* Appium CLI or Appium.app|exe:                         ==        Appium.exe

## Details

{
  "platformName": "Android",
  "platformVersion": "7.0",
  "deviceName": "Pxcel 3",
  "app": "C:\\testapp\\airbnb\\Airbnb_v18.43_apkpure.com.apk",
  "automationName": "Appium",
  "newCommandTimeout": 300,
  "appPackage": "com.airbnb.android"
}

i'm Create Desired Capabilities in appium on windows and click start session button, but don't work and got errors ,,,, 

## Link to Appium logs

https://gist.github.com/getahead92/bc0a412a1f52179e6240055273823a73

**Comment by mykola-mokhnach** [comment] 2019-06-08 20:32
Duplicate of https://github.com/appium/appium/issues/12736

**Closed by mykola-mokhnach** 2019-06-08 20:32 UTC
