### ISSUE TITLE
iOS 13 beta text field visible always false

### ISSUE THREAD

**Issue by justinhinze** [appium/appium#13099] opened 2019-08-20 22:17 UTC
## The problem

Using Appium Desktop to inspect elements

Given The same XCUIElementTypeTextField or XCUIElementTypeSecureTextField element
When using a simulator with iOS 12.2 the _visible_ attribute is **true**
But when using a simulator with iOS 13.0 the _visible_ attribute is **false** 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.1
* Desktop OS/version used to run Appium: 1.13.0 (1.13.0.20190505.6)
* Mobile platform/version under test: iOS 12.2/13.0
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.app

### Desired Capabilities for iOS 13.0
`{
  "desiredCapabilities": {
    "app": "<full-path-to-app>",
    "deviceName": "iPhone X",
    "platformName": "iOS",
    "platformVersion": "13.0",
    "newCommandTimeout": 0,
    "connectHardwareKeyboard": true
  }
}`

### Desired Capabilities for iOS 12.2
`{
  "desiredCapabilities": {
    "app": "<full-path-to-app>",
    "deviceName": "iPhone X",
    "platformName": "iOS",
    "platformVersion": "12.2",
    "newCommandTimeout": 0,
    "connectHardwareKeyboard": true
  }
}`

**Comment by KazuCocoa** [comment] 2019-08-20 23:45
Can you try the latest `appium@beta`? It has some fixes for iOS 13.

**Comment by justinhinze** [comment] 2019-08-21 00:53
Hey @KazuCocoa, same behavior with Appium version 1.14.0-beta.2

I also tried with Appium version 1.14.2-rc.0 and received a different error that appears to have something to do with the page source or window dimensions. I'm not sure if it is related or not, [logs](https://pastebin.com/j442Zca3).

**Comment by KazuCocoa** [comment] 2019-08-21 02:25
Thanks.
Maybe, we need more info about the view structure or simple view which happens it, unfortunately.

Below is a part of `source` with master (available in `appium@beta`) on Xcode 11 beta6 x iOS 13. Test app is https://github.com/appium/ios-uicatalog/pull/15 from apple's UIKIt Catalog sample.

```
  </XCUIElementTypeOther>
  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="15" y="186" width="360" height="2">
  </XCUIElementTypeOther>
  <XCUIElementTypeTextField type="XCUIElementTypeTextField" enabled="true" visible="true" x="97" y="148" width="220" height="35" label="" value="Placeholder text">
  </XCUIElementTypeTextField>
</XCUIElementTypeCell>
<XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="197" width="414" height="39" name="TINTED">
  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="197" width="414" height="39" name="TINTED" label="TINTED">
  </XCUIElementTypeOther>
</XCUIElementTypeOther>
<XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" visible="true" x="0" y="235" width="414" height="45">
  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="235" width="414" height="1">
  </XCUIElementTypeOther>
  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="279" width="414" height="1">
  </XCUIElementTypeOther>
  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="15" y="278" width="360" height="2">
  </XCUIElementTypeOther>
  <XCUIElementTypeTextField type="XCUIElementTypeTextField" enabled="true" visible="true" x="97" y="240" width="220" height="35" label="" value="Placeholder text">
  </XCUIElementTypeTextField>
</XCUIElementTypeCell>
<XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="289" width="414" height="39" name="SECURE">
  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="289" width="414" height="39" name="SECURE" label="SECURE">
  </XCUIElementTypeOther>
```

<img src="https://user-images.githubusercontent.com/5511591/63397504-b14ced00-c405-11e9-9afa-9c654e477237.png" width=200>

----

1.14.2-rc.0 has no iOS 13 fix. So, you can ignore it, btw.

**Comment by justinhinze** [comment] 2019-08-21 14:44
It's good to know a fix is in the works but currently I seem to be getting different results with appium@beta and Xcode Version 11.0 beta 6. 

`  <XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" visible="false" x="0" y="119" width="320" height="45">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="119" width="320" height="1"/>
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="163" width="320" height="1"/>
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="15" y="162" width="305" height="2"/>
    <XCUIElementTypeTextField type="XCUIElementTypeTextField" value="Placeholder text" label="" enabled="true" visible="false" x="50" y="126" width="220" height="31"/>
  </XCUIElementTypeCell>
  <XCUIElementTypeOther type="XCUIElementTypeOther" name="TINTED" enabled="true" visible="true" x="0" y="173" width="320" height="39">
    <XCUIElementTypeOther type="XCUIElementTypeOther" name="TINTED" label="TINTED" enabled="true" visible="false" x="0" y="173" width="320" height="39"/>
  </XCUIElementTypeOther>
  <XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" visible="false" x="0" y="211" width="320" height="45">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="211" width="320" height="1"/>
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="255" width="320" height="1"/>
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="15" y="254" width="305" height="2"/>
    <XCUIElementTypeTextField type="XCUIElementTypeTextField" value="Placeholder text" label="" enabled="true" visible="false" x="50" y="218" width="220" height="31"/>
  </XCUIElementTypeCell>`

<img width="393" alt="Screen Shot 2019-08-21 at 8 57 57 AM" src="https://user-images.githubusercontent.com/44032652/63441592-abeca400-c3ff-11e9-88e2-6f684c3c6dbf.png">

[Appium Log](https://pastebin.com/bpQtS4n1)

**Comment by KazuCocoa** [comment] 2019-08-21 15:26
Did you build the app with `npm run install:ios13` on https://github.com/appium/ios-uicatalog/pull/15?
If it was built by `npm run install`, the issue is the sample app side. XCTest framework returns wrong coordinates.

**Comment by justinhinze** [comment] 2019-08-21 19:29
No, I neglected to read the instructions and built it with xcodebuild. To correct this issue we'll need to change the design or build of the app under test?

**Comment by KazuCocoa** [comment] 2019-08-22 00:05
Yes. You need to update your apps so that XCTest framework can handle them correctly, so far.

**Comment by mykola-mokhnach** [comment] 2019-08-24 12:33
Closed as third party issue

**Closed by mykola-mokhnach** 2019-08-24 12:33 UTC
Labels: ThirdParty, XCUITest

**Comment by ishpreetnanda14** [comment] 2019-10-07 22:11
This workaround worked for me- 
new TouchAction(driver).tap(point(driver.findElement(By.name("xyzzy").getCenter() )).perform().release();

**Comment by gnpavan4444** [comment] 2019-11-28 12:11
We are also facing the same issue visible always false, even though the elements are present on the screen in iOS 13. Ours is a native iOS app. We are running in the iOS simulator, by building the .app file from Xcode.
Can you please let me know, how to build npm run install:ios13 from command line? Please let me know if there is any documentation to do it. Thanks.
