### ISSUE TITLE
Could not find info.plist when install app

### ISSUE THREAD

**Issue by 18516329677** [appium/appium#16246] opened 2021-12-14 05:40 UTC
## The problem

App install failed when Appium try to launch driver. The Appium log show info.plist not exist. When i open the extracted app folder which show in Appium log, no app file exist. This happens after run case with Appium for a long time (a few hours). At the beginning, case will run as normally, but after a few hours, Appium will show launch driver failed. After i clean the cache folder, it will run normally, but after a few hours, this issue will happen again.

## Environment

* Appium version (or git revision) that exhibits the issue:1.22.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac os 12.0.1
* Node.js version (unless using Appium.app|exe): v17.2.0
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 15.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Link to Appium logs
https://gist.github.com/18516329677/8a23f6207e98a06b1ac59dba755effae

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment] 2021-12-14 05:50
Possible duplicate of https://github.com/appium/appium/issues/16050
Then, `APPIUM_PREFER_SYSTEM_UNZIP ` may help https://github.com/appium/appium/blob/master/CHANGELOG.md#general

**Comment by 18516329677** [comment] 2021-12-14 06:06
> APPIUM_PREFER_SYSTEM_UNZIP
Set this environment variable in system path?

**Comment by mykola-mokhnach** [comment] 2021-12-14 07:02
You could also try appium@beta. The caching algorithm has been improved there

**Comment by KazuCocoa** [comment] 2021-12-14 17:53
It is environment variable, so you can try it out as something like `APPIUM_PREFER_SYSTEM_UNZIP=false appium`

**Comment by mykola-mokhnach** [comment] 2021-12-16 17:39
Closed because of no response

**Closed by mykola-mokhnach** 2021-12-16 17:39 UTC
Labels: NeedsInfo
