### ISSUE TITLE
Appium cannot connect to iOS real devices

### ISSUE THREAD

**Issue by xuwintery** [appium/appium#14147] opened 2020-04-06 06:48 UTC
## The problem

“xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=440086824b11d827c600a3e09202b73b89595c78' test”  is works.
 But when I use appium server it gives an error

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.17.0
* Desktop OS/version used to run Appium:Appium server
* python version (unless using Appium.app|exe):  @2.17.0
* Mobile platform/version under test: 13.3
* Real device or emulator/simulator:Real device iPhone 6S Plus 
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

encompasss-iMac:appium-webdriveragent encompass$ appium
[Appium] Welcome to Appium v1.17.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{"appium:xcodeSigningId":"iPhone Developer","appium:name":"Sample Test","appium:noReset":true,"appium:xcodeOrgId":"X68WQ3RQ6W","appium:newCommandTimeout":50000,"appium:udid":"440086824b11d827c600a3e09202b73b89595c78","appium:bundleId":"com.appiu.test","appium:deviceName":"myiPhone","appium:platformVersion":"13.3","platformName":"iOS"}]},"desiredCapabilities":{"deviceName":"my的iPhone","name":"Sample Test","xcodeOrgId":"X68WQ3RQ6W","udid":"440086824b11d827c600a3e09202b73b89595c78","noReset":true,"xcodeSigningId":"iPhone Developer","newCommandTimeout":50000,"platformVersion":"13.3","platformName":"iOS","bundleId":"com.appiu.test"}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"deviceName":"my的iPhone","name":"Sample Test","xcodeOrgId":"X68WQ3RQ6W","udid":"440086824b11d827c600a3e09202b73b89595c78","noReset":true,"xcodeSigningId":"iPhone Developer","newCommandTimeout":50000,"platformVersion":"13.3","platformName":"iOS","bundleId":"com.appiu.test"},null,{"firstMatch":[{"appium:xcodeSigningId":"iPhone Developer","appium:name":"Sample Test","appium:noReset":true,"appium:xcodeOrgId":"X68WQ3RQ6W","appium:newCommandTimeout":50000,"appium:udid":"440086824b11d827c600a3e09202b73b89595c78","appium:bundleId":"com.appiu.test","appium:deviceName":"myiPhone","appium:platformVersion":"13.3","platformName":"iOS"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1586154296167 (14:24:56 GMT+0800 (CST))
[Appium] DeprecationWarning: 'automationName' capability was not provided. Future versions of Appium will require 'automationName' capability to be set for iOS sessions.
[Appium] Requested iOS support with version >= 10, using 'XCUITest' driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[debug] [Appium] SyntaxError: Invalid regular expression: /^[ \t]*(?<pid>\d+)[ \t]+(?<ppid>\d+)[ \t]+(?<uid>\d+)[ \t]+(?<cpu>\d+\.\d+)[ \t]+(?<memory>\d+\.\d+)[ \t]+/: Invalid group
[debug] [Appium]     at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/ps-list/index.js:69:23)
[debug] [Appium]     at Module._compile (module.js:653:30)
[debug] [Appium]     at Object.Module._extensions..js (module.js:664:10)
[debug] [Appium]     at Module.load (module.js:566:32)
[debug] [Appium]     at tryModuleLoad (module.js:506:12)
[debug] [Appium]     at Function.Module._load (module.js:498:3)
[debug] [Appium]     at Module.require (module.js:597:17)
[debug] [Appium]     at require (internal/module.js:11:18)
[debug] [Appium]     at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/fkill/index.js:8:16)
[debug] [Appium]     at Module._compile (module.js:653:30)
[debug] [Appium]     at Object.Module._extensions..js (module.js:664:10)
[debug] [Appium]     at Module.load (module.js:566:32)
[debug] [Appium]     at tryModuleLoad (module.js:506:12)
[debug] [Appium]     at Function.Module._load (module.js:498:3)
[debug] [Appium]     at Module.require (module.js:597:17)
[debug] [Appium]     at require (internal/module.js:11:18)
[debug] [Appium]     at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-ios-simulator/lib/utils.js:11:1)
[debug] [Appium]     at Module._compile (module.js:653:30)
[debug] [Appium]     at Object.Module._extensions..js (module.js:664:10)
[debug] [Appium]     at Module.load (module.js:566:32)
[debug] [Appium]     at tryModuleLoad (module.js:506:12)
[debug] [Appium]     at Function.Module._load (module.js:498:3)
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1586154297301 (14:24:57 GMT+0800 (CST))
[debug] [W3C] Encountered internal error running command: Error: Could not load a driver for platformName 'iOS'. Please verify your Appium installation
[debug] [W3C]     at AppiumDriver.getDriverAndVersionForCaps (/usr/local/lib/node_modules/appium/lib/appium.js:237:11)
[debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:311:66)
[debug] [W3C]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:330:9)
[debug] [W3C]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:344:15)
[debug] [W3C]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:520:26)
[debug] [W3C]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:309:34)
[debug] [W3C]     at app.(anonymous function) (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:15)
[debug] [W3C]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [W3C]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [W3C]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[debug] [W3C]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [W3C]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [W3C]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [W3C]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [W3C]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [W3C]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [W3C]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [W3C]     at /usr/local/lib/node_modules/appium/node_modules/body-parser/lib/read.js:130:5
[debug] [W3C]     at invokeCallback (/usr/local/lib/node_modules/appium/node_modules/raw-body/index.js:224:16)
[debug] [W3C] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 1186 ms - 689

## Code To Reproduce Issue [ Good To Have ]

# coding=utf-8
from appium import webdriver

desired_capabilities = {
    "platformName": "iOS",
    "platformVersion": "13.3",
    "deviceName": "MyiPhone",
    "bundleId": "com.appiu.test",
    "udid":"440086824b11d827c600a3e09202b73b89595c78",
    "xcodeOrgId":"X68WQ3RQ6W",
    "xcodeSigningId": "iPhone Developer",
    'browserName':'safari',
}
driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_capabilities)

operation result：

Traceback (most recent call last):
  File "/Users/encompass/Desktop/test_script_Appium/appiumREvIos.py", line 14, in <module>
    driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_capabilities)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/appium/webdriver/webdriver.py", line 133, in __init__
    proxy
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/appium/webdriver/webdriver.py", line 208, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not load a driver for platformName 'iOS'. Please verify your Appium installation

**Comment by xuwintery** [comment] 2020-04-06 06:52
@ KazuCocoa Excuse me, I may need your help

**Comment by xuwintery** [comment] 2020-04-06 06:54
@KazuCocoa K  
Excuse me, I may need your help

**Comment by mykola-mokhnach** [comment] 2020-04-06 08:10
Duplicate of https://github.com/appium/appium/issues/14104

**Closed by mykola-mokhnach** 2020-04-06 08:10 UTC
