### ISSUE TITLE
Cannot start Appium with Chrome

### ISSUE THREAD

**Issue by boris779** [appium/appium#13325] opened 2019-09-30 14:05 UTC
Cannot start a Session via Appium Desktop/Selenim

## Environment
* Appium-Desktop 1.13
* Windows 10 and ubuntu 18.04
* Android 9
* Real Devices: Samsung Galaxy S10, Nexus 5, Xiaomi RedMi 7 , etc.

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[GIST](https://gist.github.com/boris779/77c56ddae413670da577d41b44cfad8d.js)

Session parameters:
```{
  "automationName": "UiAutomator2",
  "deviceName": "de61d149",
  "platformName": "Android",
  "platformVersion": "9",
  "browserName": "Chrome",
  "chromeDriverUseSystemExecutable": false,
  "chromedriverExecutableDir": "C:\\Users\\boris\\.m2\\repository\\webdriver\\chromedriver\\win32\\74.0.3729.6"
}```

**Comment by mykola-mokhnach** [comment] 2019-09-30 14:08
Duplicate of https://github.com/appium/appium/search?q=%22The+adb+command+failed%22&type=Issues

**Closed by mykola-mokhnach** 2019-09-30 14:08 UTC
