### ISSUE TITLE
bug: No Chromedriver found on mobile platform MacOS - Appium 

### ISSUE THREAD

**Issue by Redinbox** [appium/appium#19721] opened 2024-01-27 03:29 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to run mobile browser tests, I am getting "Error: No Chromedriver found that can automate Chrome"

What I tries: I have tried by passing chromedriverexecutable path for current version on emulator '103.0.5060' - Results --> getting the same error
2nd way I upgraded to higher version of chrome 121.06167.101 ..in the case also getting the same error

Code: to start server
```
return AppiumDriverLocalService.buildService(new AppiumServiceBuilder()
                .usingDriverExecutable(new File(nodePath))
                .withAppiumJS(new File(mainJSPath))
                .usingAnyFreePort()
                .withArgument(GeneralServerFlag.SESSION_OVERRIDE)
                .withArgument(GeneralServerFlag.USE_DRIVERS, "uiautomator2")
                .withArgument (GeneralServerFlag.LOG_LEVEL, "debug")
                .withArgument(GeneralServerFlag.RELAXED_SECURITY)
                //.withArgument(GeneralServerFlag.ALLOW_INSECURE, "adb_screen_streaming, chromedriver_autodownload")
                .withArgument (ALLOW_INSECURE, "chromedriver_autodownload")
                .withLogFile(new File("appium.log"))
```
for Browser :
```
UiAutomator2Options androidOptions = new UiAutomator2Options()
                        .setAutomationName(AutomationName.ANDROID_UIAUTOMATOR2)
                        .setPlatformName(platform)
                        .setDeviceName(deviceName)
                        .setAvd(avd)
                        .setAutoGrantPermissions(true)
                        .setUiautomator2ServerLaunchTimeout(Duration.ofSeconds(150))
                    androidOptions.withBrowserName(browserName);
                    ChromeOptions chromeOptions = new ChromeOptions();
                    chromeOptions.addArguments("--disable-popup-blocking");
                    chromeOptions.addArguments("--start-maximized");
                    chromeOptions.addArguments("chromeDriverExecutable","src/test/resources/drivers/chromedriver");
                    androidOptions.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
```

### Expected Behavior

Chrome driver should get downloaded automatically for latest version.
In case of lower version, it should accept and work on user customised chrome driver path with correct version.

### Minimal Reproducible Example

Code: to start server
```
return AppiumDriverLocalService.buildService(new AppiumServiceBuilder()
                .usingDriverExecutable(new File(nodePath))
                .withAppiumJS(new File(mainJSPath))
                .usingAnyFreePort()
                .withArgument(GeneralServerFlag.SESSION_OVERRIDE)
                .withArgument(GeneralServerFlag.USE_DRIVERS, "uiautomator2")
                .withArgument (GeneralServerFlag.LOG_LEVEL, "debug")
                .withArgument(GeneralServerFlag.RELAXED_SECURITY)
                //.withArgument(GeneralServerFlag.ALLOW_INSECURE, "adb_screen_streaming, chromedriver_autodownload")
                .withArgument (ALLOW_INSECURE, "chromedriver_autodownload")
                .withLogFile(new File("appium.log"))
```
for Browser :
```
UiAutomator2Options androidOptions = new UiAutomator2Options()
                        .setAutomationName(AutomationName.ANDROID_UIAUTOMATOR2)
                        .setPlatformName(platform)
                        .setDeviceName(deviceName)
                        .setAvd(avd)
                        .setAutoGrantPermissions(true)
                        .setUiautomator2ServerLaunchTimeout(Duration.ofSeconds(150))
                    androidOptions.withBrowserName(browserName);
                    ChromeOptions chromeOptions = new ChromeOptions();
                    chromeOptions.addArguments("--disable-popup-blocking");
                    chromeOptions.addArguments("--start-maximized");
                    chromeOptions.addArguments("chromeDriverExecutable","src/test/resources/drivers/chromedriver");
                    androidOptions.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
```

### Environment

- Operating system: macOS 1Sonoma 4.2.1 (23C71)
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s): 

1. uiautomator2@2.42.0 [installed (npm)]
2. xcuitest@5.13.2 [installed (npm)]
3. gecko@1.2.10 [installed (npm)]
4. mac2@1.9.0 [installed (npm)]
5. safari@3.5.9 [installed (npm)]
6. chromium@1.3.3 [installed (npm)]

- Appium plugin(s) and their version(s): NA
- Node.js version (output of `node --version`): V21.5.0
- `npm` version (output of `npm --version`): 10.2.4
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: android 
- Real device or emulator/simulator: emulator

### Link to Appium Logs

https://gist.github.com/Redinbox/d087f1eda16ed5e587a92bf8becd8951

### Further Information

I am not this is bug but yes its blocking now

**Comment by mykola-mokhnach** [comment] 2024-01-27 07:27
> 2024-01-27 03:04:40:921 [Chromedriver@8f0f] Found Chrome bundle 'com.android.chrome' version '103.0.5060'
> 2024-01-27 03:04:41:451 [Chromedriver@8f0f] Cannot synchronize local chromedrivers with the remote storage: self-signed certificate in certificate chain

Chrome autodownload does not work because of local certificate setup issues. It's the duplicate of https://github.com/appium/appium/issues/19711

As you can see the installed chrome's major version is 103. Please provide the log where the matching driver version is supplied manually, because the above one supplied v 120, which does not match.

**Comment by mykola-mokhnach** [comment] 2024-01-30 07:47
Closed as not an issue

**Closed by mykola-mokhnach** 2024-01-30 07:47 UTC
Labels: Needs Info
