### ISSUE TITLE
[appium 1.16.0-rc.1]Not "Products" in /Library/Developer/Xcode/DerivedData/WebDriverAgent-xxxxxxxx/Build even after building wda in xcode

### ISSUE THREAD

**Issue by maggie5750** [appium/appium#13711] opened 2019-12-12 07:55 UTC
## The problem

[appium 1.16.0-rc.1]Not "Products" in /Library/Developer/Xcode/DerivedData/WebDriverAgent-xxxxxxxx/Build even after building wda in xcode

## Environment

* Appium version (or git revision) that exhibits the issue: appium 1.16.0-rc.1
* Last Appium version that did not exhibit the issue (if applicable): appium 1.15.1
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 10.13.0
* Npm or Yarn package manager:  6.9.0
* Mobile platform/version under test:
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details
1. Install appium 1.16.0-rc.1 and run below 3 commands: 

> cd node_modules/appium/node_modules/appium-webdriveragent/
> mkdir -p Resources/WebDriverAgent.bundle
> sh ./Scripts/bootstrap.sh -d

2. Open WebDriverAgent with xcode and build WebDriverAgentLib and WebDriverAgentRunner on simulator and real device

3. Start appium server and run test, See below appium log

_Navigate to /Users/xxx/Library/Developer/Xcode/DerivedData/WebDriverAgent-bcgbrossqxdjaghexqvvissdhlpx/Build and no "Products" below "Build" folder_

## Link to Appium logs

```
2019-12-12 15:44:28:114 - [debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8101/status] with no body
2019-12-12 15:44:28:124 - [iProxy@00008030] Error: Connection was refused to port 8101
2019-12-12 15:44:28:124 - [iProxy@00008030]     at Usbmux.connect (/Users/xxx/Documents/Appium/appium1.16.0-rc1/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/usbmux/index.js:207:13)
2019-12-12 15:44:28:126 - [WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
2019-12-12 15:44:28:210 - [Xcode] 2019-12-12 15:44:28.210 xcodebuild[83037:8053263] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/xxx/Library/Developer/Xcode/DerivedData/WebDriverAgent-bcgbrossqxdjaghexqvvissdhlpx/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fe4ae2dbe00 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

**Comment by KazuCocoa** [comment] 2019-12-12 14:41
Could you attach the server log?
Especially, would like to see Xcode/xcodebuild stuff

**Comment by maggie5750** [comment] 2019-12-13 02:45
@KazuCocoa what server log would you like? I don't catch your meaning about "would like to see Xcode/xcodebuild stuff"

**Comment by KazuCocoa** [comment] 2019-12-13 05:18
I meant the full appium server log. (It includes Xcode/xcodebuild related lines)

**Comment by maggie5750** [comment] 2019-12-13 08:41
The capability "showXcodeLog" need set to true, right?

**Comment by maggie5750** [comment] 2019-12-13 09:37
> I meant the full appium server log. (It includes Xcode/xcodebuild related lines)
@KazuCocoa Log attached. Check if it is enough as the log is too large and some are covered.
[appium_log.pdf](https://github.com/appium/appium/files/3960067/appium_log.pdf)

**Comment by KazuCocoa** [comment] 2019-12-13 15:46
Thanks.

Your log had below `test-without-building` but no `build-for-testing`. It means your environment did not build WDA. 

```
xcodebuild test-without-building -project /Users/xxx/Appium/appium1.16.0-rc1/
node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/
appium-webdriveragent/WebDriverAgent.xcodeproj -scheme
WebDriverAgentRunner -destination id=9B6FD0C8-AC8B-448A-A472-
EEDBBDCC5FF1 IPHONEOS_DEPLOYMENT_TARGET=13.2
GCC_TREAT_WARNINGS_AS_ERRORS=0
COMPILER_INDEX_STORE_ENABLE=NO
```

The log should be like below:
```
xcodebuild build-for-testing test-without-building -project /Users/xxx/Appium/appiu....
```

Perhaps your capabilities had some items related to WDA build.

**Comment by maggie5750** [comment] 2019-12-16 06:06
@KazuCocoa  But actually I build via below method:
1. Install appium 1.16.0-rc.1 and run below 3 commands:
```
cd node_modules/appium/node_modules/appium-webdriveragent/
mkdir -p Resources/WebDriverAgent.bundle
sh ./Scripts/bootstrap.sh -d
```

2. Open WebDriverAgent with xcode and build WebDriverAgentLib and WebDriverAgentRunner on simulator and real device

**Comment by KazuCocoa** [comment] 2019-12-16 06:26
Did the Xcode's _WebDriverAgent-xxxxxxxx_ in _DerivedData_ and Appium's xcodebuild refer the same path? The path is managed by Xcode/xcodebuild automatically by default.

**Comment by maggie5750** [comment] 2019-12-17 01:00
Yes. Xcode's WebDriverAgent-xxxxxxxx is generated in DerivedData, just no Products folder below WebDriverAgent-xxxxxxxx/Build/

**Comment by KazuCocoa** [comment] 2019-12-17 01:35
ah, maybe I misunderstood.
You could not build the app even with Xcode. I thought you were able to build it with Xcode, but could not install it via Appium.

If the cause is a permission issue in your node module (e.g. carthage stuff), the below steps might help.
https://github.com/appium/appium/issues/12841#issuecomment-507100168

**Comment by maggie5750** [comment] 2019-12-18 05:21
@KazuCocoa I have tried but it doesn't help.

**Comment by maggie5750** [comment] 2019-12-20 05:32
@KazuCocoa It seems I get the problem. When I build WebDriverAgent via xcode the WebDriverAgentRunner-Runner.app is generated. But when run test case via appium it will build again and generate another WebDriverAgent-xxxx folder which is not the same and then try to get WebDriverAgentRunner-Runner.app in new folder which doesn't have WebDriverAgentRunner-Runner.app

**Comment by mykola-mokhnach** [comment] 2019-12-22 11:49
Closed as not an issue

**Closed by mykola-mokhnach** 2019-12-22 11:49 UTC
Labels: NotABug, XCUITest

**Comment by maggie5750** [comment] 2019-12-26 08:21
@mykola-mokhnach @KazuCocoa, Why there were 2 appium-webdriveragent folders: one is in "appium_1.16.0/node_modules/appium/node_modules/appium-webdriveragent" and another one is "appium_1.16.0/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent".  Before I built the WebDriverAgent under "appium_1.16.0/node_modules/appium/node_modules/appium-webdriveragent", it can not work.

**Comment by KazuCocoa** [comment] 2019-12-26 08:39
https://github.com/appium/appium/pull/13634#discussion_r350535249
Maybe, the `node_modules/appium/node_modules/appium-webdriveragent` comes from flutter driver. (No response to update the dependency by the flutter-driver's author)

xcuitest driver should refer `appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent`

**Comment by maggie5750** [comment] 2019-12-26 08:48
OK. Got it. Thanks
