### ISSUE TITLE
XCUITest: 1.10.0 error suggesting appium server needs to be >= 1.6.0

### ISSUE THREAD

**Issue by gbrhaz** [appium/appium#11759] opened 2018-11-28 18:04 UTC
## The problem

When running iOS XCUITest driver:

Appium 1.9.1 works
Appium 1.10.0 does not work

On driver.start the scenario exits with error:

message='XCUITest requires Appium version >= 1.6.0 (Appium - -Core - -Error - -NotSupportedAppiumServer)

I'm going to make a guess and suggest this is a string equality issue?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): 1.9.1
* Desktop OS/version used to run Appium: OSX High Sierra 10.13.6
* Node.js version (unless using Appium.app|exe): 8.9.4
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI doesn't work; desktop does (uses 1.9.1)

**Comment by imurchie** [comment] 2018-11-28 18:07
This is a problem with the Ruby client. Please upgrade the Ruby library.

**Comment by imurchie** [comment] 2018-11-28 18:08
Closing as duplicate of https://github.com/appium/ruby_lib/issues/838

**Closed by imurchie** 2018-11-28 18:08 UTC
