### ISSUE TITLE
Driver.setGeoLocation have problems for IOS Emulator.

### ISSUE THREAD

**Issue by herbert-soares-ifood** [appium/appium#13037] opened 2019-08-06 20:20 UTC
## The problem
When I run my tests on IOS an error is presented. It says I have to allow access on my computer. But I already released the 2 hits: Appium.app and Terminal.app.

Note: With Android it works normally.

## Environment
* Appium version: 7.0.0

## Details
Message for error:
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not complete operation. Make sure Simulator UI is running and the parent Appium application (e. g. Appium.app or Terminal.app) is present in System Preferences > Security & Privacy > Privacy > Accessibility list. If the operation is still unsuccessful then it is not supported by this Simulator. Original error: Command 'osascript -e '

## Print Error:
![image](https://user-images.githubusercontent.com/50626795/62574244-6ad88980-b86e-11e9-9ca6-77a869d2ffb5.png)

**Comment by loadin799** [comment] 2019-08-06 20:36
+1

**Comment by eduardo-finotti-ifood** [comment] 2019-08-06 20:37
The same problem here! :(

**Comment by KazuCocoa** [comment] 2019-08-07 01:26
Duplicate of https://github.com/appium/appium/issues/13010 ? Try out recnet `appium@beta`

Appium also has `idb` logic to reduce such AppleScript flakiness. Please check appium-doctor if your env has idb.

**Closed by KazuCocoa** 2019-08-07 01:26 UTC

**Comment by herbert-soares-ifood** [comment] 2019-08-07 17:09
Tks @KazuCocoa .Very very Good.

**Comment by herbert-soares-ifood** [comment] 2019-08-07 17:10
Link for appium idb install: https://github.com/appium/appium-idb
