### ISSUE TITLE
Chrome options error. Unrecognized chrome option: prefs

### ISSUE THREAD

**Issue by eugenepi** [appium/appium#8830] opened 2017-07-12 14:40 UTC
Chrome option 'prefs' is used to disable 'save password' dialog in Chrome browser.

Appium returns error:  Encountered internal error running command: Error: unknown error: cannot parse capability: chromeOptions from unknown error: unrecognized chrome option: prefs.

Example in Java:
```java
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("deviceName", "device");
capabilities.setCapability("platformName", "Android");
capabilities.setCapability(MobileCapabilityType.UDID, "xxxxxxxxxx");
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "chrome");

ChromeOptions chromeOptions = new ChromeOptions();
Map<String, Object> prefs = new HashMap<>();
prefs.put("credentials_enable_service", false);
prefs.put("profile.password_manager_enabled", false);
chromeOptions.setExperimentalOption("prefs", prefs);
capabilities.setCapability("chromeOptions", chromeOptions);
AndroidDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4002/wd/hub"), capabilities);
driver.get("http://www.google.com");
```

## Environment

* Appium version (or git revision) that exhibits the issue:
1.6.3, 1.6.4, 1.6.5
* Desktop OS/version used to run Appium:
Windows 8
* Node.js version (unless using Appium.app|exe):
7.4.0
* Mobile platform/version under test:
Android 6.0.1
* Real device or emulator/simulator:
Real device

## Link to Appium logs
```
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"chrome","chromeOptions":{"args":[],"extensions":[],"prefs":{"credentials_enable_service":false,"profile.password_manager_enabled"
:false}},"platformName":"Android","udid":"05157df578afa005","deviceName":"samsung"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"browserName":"chrome","chromeOptions":{"args":[],"extensions":[],"prefs":{"credentials_enable_service":false,"profile.password_mana
ger_enabled":false}},"platformName":"Android","udid":"05157df578afa005","deviceName":"samsung"},null,null,null,null]
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   browserName: 'chrome'
[Appium]   chromeOptions: { args: [],
  extensions: [],
  prefs:
   { credentials_enable_service: false,
     'profile.password_manager_enabled': false } }
[Appium]   platformName: 'Android'
[Appium]   udid: '05157df578afa005'
[Appium]   deviceName: 'samsung'
[debug] [AndroidDriver] AndroidDriver version: 1.10.38
[BaseDriver] Session created with session id: 42c5d5e4-df51-4a93-9b0d-6d1c41974cde
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_121
[AndroidDriver] We're going to run a Chrome-based session
[AndroidDriver] Chrome-type package and activity are com.android.chrome and com.google.android.apps.chrome.Main
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\evgeniypi\AppData\Local\Android\android-sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: 05157df578afa005
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\evgeniypi\AppData\Local\Android\android-sdk\platform-tools\adb.exe
[debug] [ADB] Setting device id to 05157df578afa005
[AndroidDriver] App file was not listed, instead we're going to run com.android.chrome directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\evgeniypi\AppData\Local\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","05157df578afa005","shell","pm","list","packages","com.android.chrome"]
[AndroidDriver] Starting Android session
[debug] [ADB] Running 'C:\Users\evgeniypi\AppData\Local\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","05157df578afa005","wait-for-device"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\evgeniypi\AppData\Local\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","05157df578afa005","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [AndroidDriver] Pushing unlock helper app to device...
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\evgeniypi\AppData\Local\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","05157df578afa005","shell","getprop","ro.build.version.release"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\evgeniypi\AppData\Local\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","05157df578afa005","shell","dumpsys","window"]
[AndroidDriver] Screen already unlocked, doing nothing
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [AndroidDriver] No app capability. Assuming it is already on the device
[debug] [AndroidDriver] Running fast reset (stop and clear)
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\evgeniypi\AppData\Local\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","05157df578afa005","shell","am","force-stop","com.android.chrome"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\evgeniypi\AppData\Local\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","05157df578afa005","shell","pm","clear","com.android.chrome"]
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4003 to device: 4724
[debug] [ADB] Running 'C:\Users\evgeniypi\AppData\Local\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","05157df578afa005","forward","tcp:4003","tcp:4724"]
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running 'C:\Users\evgeniypi\AppData\Local\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","05157df578afa005","push","C:\\Appium\\node_modules\\appium\\node_modules
\\appium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar","/data/local/tmp/"]
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\evgeniypi\AppData\Local\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","05157df578afa005","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","05157df578afa005","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.a
ndroid.chrome","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[debug] [UiAutomator] Moving to state 'online'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Loading json...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[AndroidDriver] Starting a chrome-based browser session
[debug] [Chromedriver] Changed state to 'starting'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[Chromedriver] Set chromedriver binary as: C:\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
[Chromedriver] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"4005 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I c
hromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Spawning chromedriver with: C:\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --url-base=wd/hub --port=4005 --adb-port=5037
[Chromedriver] [STDOUT] Starting ChromeDriver 2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41) on port 4005
Only local connections are allowed.
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:4005/wd/hub/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"6.
3.9600\"}}}"
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4005/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","args":[],"exte
nsions":[],"prefs":{"credentials_enable_service":false,"profile.password_manager_enabled":false},"androidDeviceSerial":"05157df578afa005"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"7a32f5ee4985566ae942636ea8075d94","status":13,"value":{"message":"unknown error: cannot parse capability: chromeOptions\nfrom unknown
 error: unrecognized chrome option: prefs\n  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.3.9600 x86_64)"}}
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4005/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","args":[],"exte
nsions":[],"prefs":{"credentials_enable_service":false,"profile.password_manager_enabled":false},"androidDeviceSerial":"05157df578afa005"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"46682351cbdac17aba9aee46f100d3e5","status":13,"value":{"message":"unknown error: cannot parse capability: chromeOptions\nfrom unknown
 error: unrecognized chrome option: prefs\n  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.3.9600 x86_64)"}}
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4005/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","args":[],"exte
nsions":[],"prefs":{"credentials_enable_service":false,"profile.password_manager_enabled":false},"androidDeviceSerial":"05157df578afa005"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"30b1e4de5b79fabdcafcc47d065c1c8f","status":13,"value":{"message":"unknown error: cannot parse capability: chromeOptions\nfrom unknown
 error: unrecognized chrome option: prefs\n  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.3.9600 x86_64)"}}
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4005/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","args":[],"exte
nsions":[],"prefs":{"credentials_enable_service":false,"profile.password_manager_enabled":false},"androidDeviceSerial":"05157df578afa005"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"e94cfc2dc65f8e13b643eb885bccc225","status":13,"value":{"message":"unknown error: cannot parse capability: chromeOptions\nfrom unknown
 error: unrecognized chrome option: prefs\n  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.3.9600 x86_64)"}}
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[debug] [Chromedriver] Changed state to 'stopped'
[Chromedriver] Error: unknown error: cannot parse capability: chromeOptions
from unknown error: unrecognized chrome option: prefs
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.3.9600 x86_64)
    at Chromedriver.callee$2$0$ (../../lib/chromedriver.js:177:15)
    at tryCatch (C:\Appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
 Error: unknown error: cannot parse capability: chromeOptions
from unknown error: unrecognized chrome option: prefs
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.3.9600 x86_64)
    at Chromedriver.callee$2$0$ (../../lib/chromedriver.js:177:15)
    at tryCatch (C:\Appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[debug] [AndroidDriver] Shutting down Android driver
[debug] [ADB] Pressing the HOME button
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\evgeniypi\AppData\Local\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","05157df578afa005","shell","input","keyevent",3]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Test results for WatcherResultPrinter=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Time: 2.137
[debug] [AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\evgeniypi\AppData\Local\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","05157df578afa005","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\evgeniypi\AppData\Local\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","05157df578afa005","shell","am","force-stop","io.appium.unlock"]
[debug] [Logcat] Stopping logcat capture
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[MJSONWP] Encountered internal error running command: Error: unknown error: cannot parse capability: chromeOptions
from unknown error: unrecognized chrome option: prefs
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.3.9600 x86_64)
    at Chromedriver.callee$2$0$ (../../lib/chromedriver.js:177:15)
    at tryCatch (C:\Appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Appium\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 7981 ms - 367
```

**Comment by mykola-mokhnach** [comment] 2017-07-12 15:02
I think this is rather chromedriver issue. Check these bugreports:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1014
https://monorail-prod.appspot.com/p/chromedriver/issues/detail?id=1206

**Comment by imurchie** [comment] 2017-07-12 15:04
Yes, seems like ChromeDriver for Android. Works fine for desktop Chrome.

**Comment by jlipps** [comment] 2017-07-28 21:17
Closing since the issue is in ChromeDriver for Android, not Appium.

**Closed by jlipps** 2017-07-28 21:17 UTC
Labels: Android, ThirdpartyIssue
