### ISSUE TITLE
Error: chrome not reachable

### ISSUE THREAD

**Issue by livastar** [appium/appium#9187] opened 2017-09-11 06:19 UTC
## The problem

Hi to all. I know about this problem, I've read a lot of info about this issue, but neither this  #7138, neither https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/chromedriver.md didn't solve the issue. 

I've tried to upgrade chrome at mobile device to the latest version. Successfully upgraded but with the same issue from Appium v1.7.0-beta, BUT on real device it works fine.

## Environment

* Appium: v.1.7.0-beta
* Node.js version: v8.4.0
* Mobile platform/version: Android 7.1.1 (Without Google Play Services) and Andriod 8.0 (With Google Play Services)
* Real device or emulator/simulator: *Emulator*

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/livastar/bcec66b3608a8d90c03d95ea0ac931f0

**Comment by imurchie** [comment] 2017-09-12 16:43
Duplicate of #8958

**Closed by imurchie** 2017-09-12 16:43 UTC
Labels: Android
