### ISSUE TITLE
[iOS] Appium getPageSource return different dom (xml) from the same Page in different hosts

### ISSUE THREAD

**Issue by hcleldaddonio** [appium/appium#13476] opened 2019-10-23 08:35 UTC
## The problem

I have been using 2 Mac computers that run Appium. Both of them have the same versions (will be detailed below) and the only difference between them is that one is mac mini and the other MacBook pro.
When I call getPageSource return different dom for the same page. The dom from MacBookPro has 2 XML rows (elements) that the Mac mini doesn't have. Does the way the dom is being built depend on the operating system host?

## Environment
 Env1 - MacMini
* Appium version (or git revision) that exhibits the issue: 1.15
* Last Appium version that did not exhibit the issue (if applicable):1.14
* Desktop OS/version used to run Appium: Mac OSX 10.15
* Node.js version (unless using Appium.app|exe): 10.16.3
* Mobile platform/version under test: iPhone SE, version 13.1.2
* Real device or emulator/simulator: Real Device

 Env2 - MacBook pro
* Appium version (or git revision) that exhibits the issue: 1.15
* Last Appium version that did not exhibit the issue (if applicable):1.14
* Desktop OS/version used to run Appium: Mac OSX 10.15
* Node.js version (unless using Appium.app|exe): 10.16.3
* Mobile platform/version under test: iPhone SE, version 13.1.2
* Real device or emulator/simulator: Real Device

## Link to Appium logs
Link to Doms:
https://gist.github.com/hcleldaddonio/c2ed6e4031864d4cfb24fafdc021e742

**Comment by hcleldaddonio** [comment] 2019-10-23 08:49
MacBookPro Dom:
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<AppiumAUT>
  <XCUIElementTypeApplication enabled="true" height="568" label="TestApp" name="Altoro-App" type="XCUIElementTypeApplication" visible="true" width="320" x="0" y="0">
  <XCUIElementTypeWindow enabled="true" height="568" type="XCUIElementTypeWindow" visible="true" width="320" x="0" y="0">
    <XCUIElementTypeOther enabled="true" height="568" type="XCUIElementTypeOther" visible="true" width="320" x="0" y="0">
      <XCUIElementTypeOther enabled="true" height="568" type="XCUIElementTypeOther" visible="true" width="320" x="0" y="0">
        <XCUIElementTypeOther enabled="true" height="568" type="XCUIElementTypeOther" visible="true" width="320" x="0" y="0">
          <XCUIElementTypeNavigationBar enabled="true" height="44" name="View" type="XCUIElementTypeNavigationBar" visible="true" width="320" x="0" y="20">
            <XCUIElementTypeButton enabled="true" height="44" label="Back" name="Back" type="XCUIElementTypeButton" visible="true" width="65" x="0" y="20"/>
          </XCUIElementTypeNavigationBar>
            <XCUIElementTypeOther enabled="true" height="568" type="XCUIElementTypeOther" visible="true" width="320" x="0" y="0">
              <XCUIElementTypeOther enabled="true" height="568" type="XCUIElementTypeOther" visible="true" width="320" x="0" y="0">
              </XCUIElementTypeOther>
            </XCUIElementTypeOther>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow enabled="true" height="568" type="XCUIElementTypeWindow" visible="false" width="320" x="0" y="0">
    <XCUIElementTypeOther enabled="true" height="568" type="XCUIElementTypeOther" visible="false" width="320" x="0" y="0">
      <XCUIElementTypeOther enabled="true" height="568" type="XCUIElementTypeOther" visible="false" width="320" x="0" y="0"/>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
</XCUIElementTypeApplication>
</AppiumAUT>

**Comment by mykola-mokhnach** [comment] 2019-10-23 10:52
Yes, this totally depends on the Xcode SDK.

**Comment by hcleldaddonio** [comment] 2019-10-23 11:14
but I'm using same Xcode version. xcode 11.1. 
The SDK supposed to be the same... am I wrong?

**Comment by hcleldaddonio** [comment] 2019-10-24 13:16
?

**Comment by KazuCocoa** [comment] 2019-10-24 13:40
What the result of `@driver.execute_script 'mobile: source', { format: :description }`? (<= is Ruby)
It returns debugDescription by xcuitest. (no modifications)

**Comment by hcleldaddonio** [comment] 2019-10-27 09:17
when I ran the above command the response was the same as getPageSource. are you sure this is the command or am I doing something wrong?
This was the command I ran:
((JavascriptExecutor) driver).executeScript("mobile: source", ImmutableMap.of("format:","description"));

can you maybe provide example for the response?

**Comment by KazuCocoa** [comment] 2019-10-27 09:36
Perhaps, `ImmutableMap.of("format:","description")` should be `ImmutableMap.of("format","description")` (No `:` in `format`)

The response will be like https://github.com/appium/appium/issues/13227#issuecomment-531162468

**Comment by hcleldaddonio** [comment] 2019-10-27 09:47
https://gist.github.com/hcleldaddonio/c2ed6e4031864d4cfb24fafdc021e742#gistcomment-3066975

**Comment by KazuCocoa** [comment] 2019-10-27 11:21
Thanks.

I checked both XML and the output.
The missing xml position looks wired...
Appium resolves elements recursively, so, except for timing issue when Appium got accessibility snapshot, they should have been the same. The `description` output also had two `XCUIElementTypeOther`. So, the xml source also should have them as the xml output.

- pro
```
  <XCUIElementTypeApplication enabled="true" height="568" label="TestApp" name="TestApp" type="XCUIElementTypeApplication" visible="true" width="320" x="0" y="0">
  <XCUIElementTypeWindow enabled="true" height="568" type="XCUIElementTypeWindow" visible="true" width="320" x="0" y="0">
    <XCUIElementTypeOther enabled="true" height="568" type="XCUIElementTypeOther" visible="true" width="320" x="0" y="0">
      <XCUIElementTypeOther enabled="true" height="568" type="XCUIElementTypeOther" visible="true" width="320" x="0" y="0">
        <XCUIElementTypeOther enabled="true" height="568" type="XCUIElementTypeOther" visible="true" width="320" x="0" y="0">
          <XCUIElementTypeNavigationBar enabled="true" height="44" name="View" type="XCUIElementTypeNavigationBar" visible="true" width="320" x="0" y="20">
```

- mini
```
  <XCUIElementTypeApplication enabled="true" height="568" label="TestApp" name="TestApp" type="XCUIElementTypeApplication" visible="true" width="320" x="0" y="0">
  <XCUIElementTypeWindow enabled="true" height="568" type="XCUIElementTypeWindow" visible="true" width="320" x="0" y="0">
    <XCUIElementTypeOther enabled="true" height="568" type="XCUIElementTypeOther" visible="true" width="320" x="0" y="0">
      <XCUIElementTypeNavigationBar enabled="true" height="44" name="View" type="XCUIElementTypeNavigationBar" visible="true" width="320" x="0" y="20">
```

hm..

**Comment by hcleldaddonio** [comment] 2019-10-27 11:30
What else can I do ? any additional information that I can provide?

**Comment by hcleldaddonio** [comment] 2019-10-27 11:33
Also it important to mention that I also tried another MacBookPro and Another MacMini and the problem still occurred. Same missing fields on macmini.

**Comment by KazuCocoa** [comment] 2019-10-27 11:54
My assumption is Xcode 11 stuff or timing...

- What the result of xml source after calling `ImmutableMap.of("format","description")`?
    - The description format looks it has the missing 2 xml items. So, I wondered get xml source after getting the description which has the missing xml items.
- What about applying `includeNonModalElements` before getting source?
    - http://appium.io/docs/en/advanced-concepts/settings/
- What about the number of `XCUIElementTypeOther` elements?
    - I mean getting XCUIElementTypeOther by `find elements by class name` and the name is `XCUIElementTypeOther`

**Comment by hcleldaddonio** [comment] 2019-10-27 11:59
1) Yes, the result XML has missing 2 XML items.
2) I will try.
3) What about them? we have missing 2 XML items. both of them are from this type.

Since we have different doms on the different host we get different results.
There are few more applications in which this issue also appears there.

**Comment by hcleldaddonio** [comment] 2019-10-27 13:50
Hey,
I tried using the includeNonModalElements option.
It didn't solve the issues but maybe it gets us closer for a solution.
Now I experience a different issue.
On the same machine, for the same page, I get the same dom but in different elements order...
Is there anything to do with that new issue?

**Comment by KazuCocoa** [comment] 2019-10-27 14:54
> Is there anything to do with that new issue?

Nothing for Appium.
Appium refers to different API to resolve elements by XCTest framework. Other logics have no differences. So, the structure etc depend on XCTest framework by Apple.

---

How about `useJSONSource: true` in capability and get source?
A bit different logic to resolve elements. (But maybe the result will be the same)

Perhaps, something different in returned value by xctest framework.
So, need to debug with breakpoints in some methods like below...
https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBXPath.m#L304
https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIElement+FBUtilities.m#L219

**Comment by hcleldaddonio** [comment] 2019-10-28 07:58
> 
> 
> > Is there anything to do with that new issue?
> 
> Nothing for Appium.
> Appium refers to different API to resolve elements by XCTest framework. Other logics have no differences. So, the structure etc depend on XCTest framework by Apple.
> 





> 
> 
> > Is there anything to do with that new issue?
> 
> Nothing for Appium.
> Appium refers to different API to resolve elements by XCTest framework. Other logics have no differences. So, the structure etc depend on XCTest framework by Apple.
> 
> How about `useJSONSource: true` in capability and get source?
> A bit different logic to resolve elements. (But maybe the result will be the same)
> 
So the different results come from the XCTest framework? and appium only base it resolution on it?


> Perhaps, something different in returned value by xctest framework.
> So, need to debug with breakpoints in some methods like below...
> https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBXPath.m#L304
> https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIElement+FBUtilities.m#L219

tried, still has issues..

**Comment by hcleldaddonio** [comment] 2019-10-28 11:59
so this problem is related to Apple ?

**Comment by KazuCocoa** [comment] 2019-10-28 13:02
As far as I know of, yes.
Appium depends on accessibility snapshots by XCTest framework to get source trees and resolve elements. Thus, I have no good idea about the cause of such missing two elements on the position in Appium side for now.

**Comment by mykola-mokhnach** [comment] 2019-10-30 09:14
Closed as third party issue

**Closed by mykola-mokhnach** 2019-10-30 09:14 UTC
Labels: ThirdParty, XCUITest
