### ISSUE TITLE
Tap with duration (longPress) broken between python-client and appium-xcuitest-driver

### ISSUE THREAD

**Issue by Ysoko** [appium/appium#8405] opened 2017-05-09 00:31 UTC
## The problem
Using the python-client, tried to perform a `WebDriver.tap(positions=[(10,10)], duration=500)`. The following error occurs:
`selenium.common.exceptions.WebDriverException: Message: Support for longPress(options={"y":10,"x":10,"duration":500})-release(options={}) gesture is not implemented. Try to use "mobile: *" interface to workaround the issue. Only these gestures are supported:
	doubleTap: 		doubletap
		tap(options={"count":2})
	tap: 		tap
		tap-release
		press-release
	longPress: 		longpress
		press-wait-release
	drag: 		press-wait-moveTo-release
	scroll: 		press-moveTo-release`

## Environment
* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS X 10.12.4
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: iOS 9.3.2 (using automationName=XCUITest)
* Real device or emulator/simulator: Real iPhone SE
* Appium CLI or Appium.app|exe: Appium CLI

## Details
Looking at the source code for python-client, it looks like the following two lines:
https://github.com/appium/python-client/blob/master/appium/webdriver/webdriver.py#L223
https://github.com/appium/python-client/blob/master/appium/webdriver/webdriver.py#L234
Perform the following actions:
`[{action: 'longpress'}, {action: 'release'}]`

But appium-xcuitest-driver defines a long press action as follows:
https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/gesture.js#L89
`        [{action: 'longpress'}],
        [{action: 'press'}, {action: 'wait'}, {action: 'release'}]`

## Link to Appium logs
https://gist.github.com/Ysoko/de96d6c4df9944d29a1a1c9f90f611d0#file-appium-log

## Code To Reproduce Issue [ Good To Have ]
https://gist.github.com/Ysoko/de96d6c4df9944d29a1a1c9f90f611d0#file-main-py

**Comment by dpgraham** [comment] 2017-05-11 18:19
@mykola-mokhnach submitted a fix for this. Can you update your appium node modules and try again? If it still is broken, let me know and I'll re-open the ticket.

**Closed by dpgraham** 2017-05-11 18:19 UTC
Labels: Enhancement, XCUITest

**Comment by mykola-mokhnach** [comment] 2017-05-11 18:20
The fix is available in Appium 1.6.5-beta

**Comment by cindysongzi** [comment] 2017-05-12 07:35
I have encountered this problem as well. I run on python 3.5, appium 1.6.5-beta:
TouchAction(driver).long_press(el=None, x=ori_x,y=ori_y).move_to(x=end_x, y=end_y).wait(hold_time).release().perform()

Error:
selenium.common.exceptions.WebDriverException: Message: Support for longPress(options={"x":716.5,"y":569,"duration":1000})-moveTo(options={"x":-4.5,"y":18})-wait(options={"ms":1000})-release(options={}) gesture is not implemented. Try to use "mobile: *" interface to workaround the issue. Only these gestures are supported:
	doubleTap: 		doubletap
		tap(options={"count":2})
	tap: 		tap
		tap-release
		press-release
	longPress: 		longpress
		longpress-release
		press-wait-release
	drag: 		press-wait-moveTo-release
		longpress-moveTo-release
	scroll: 		press-moveTo-release

**Comment by mykola-mokhnach** [comment] 2017-05-12 08:27
@cindysongzi I assume the error message you get is pretty clear to understand what the problem is if you compare your chain and the supported ones:
> longPress(options={"x":716.5,"y":569,"duration":1000})-moveTo(options={"x":-4.5,"y":18})-wait(options={"ms":1000})-release(options={}

> drag: press-wait-moveTo-release
longpress-moveTo-release

**Comment by cindysongzi** [comment] 2017-05-12 10:06
@mykola-mokhnach Thank for your reply. It works now! 
Can you help explain the x, y in moveTo(x, y)?  Are they relative to the original coordinate?  or they could be absolute coordinate?

**Comment by mykola-mokhnach** [comment] 2017-05-12 10:07
relative

**Comment by Ysoko** [comment] 2017-05-12 20:32
@dpgraham I updated appium-xcuitest-driver from 2.28.5 to 2.29.0, and ran my code to reproduce, and no longer receive a WebDriverException. Looks good from here, thanks guys!

**Comment by dpgraham** [comment] 2017-05-12 21:03
Great. Thanks @Ysoko and @mykola-mokhnach!

**Comment by pluie-cloud** [comment] 2017-05-17 09:39
@Ysoko  I have update appium-xcuitest-driver to 2.29.0 but no user,still Support for press(options={"x":28,"y":152})-press(options={"x":127,"y":152}) gesture is not implemented. Try to use "mobile: *" interface to workaround the issue. Only these gestures are supported:

**Comment by batuozk** [comment] 2017-08-24 19:51
This is how I "worked around" for pinch action, as expressed in the error output on Appium 1.6.4

```
Map<String, Object> params = new HashMap<>();
params.put("scale", "0.5");
params.put("velocity", "-1.1");
params.put("element", element.getId());
driver.executeScript("mobile: pinch", params);
```

**Comment by BlayerB** [comment] 2017-08-29 14:05
Hi,
Anyone found any way to make a multi-directional swipe (like when setting a "lock pattern" in a mobile)?
b.t.w. I'm using java, not python.
