### ISSUE TITLE
Android PressKeyCode for Search is not working

### ISSUE THREAD

**Issue by eduardoreynoso** [appium/appium#10989] opened 2018-07-03 22:27 UTC
I am trying to press the Search button on the keyboard (the little magnifying glass in the bottom right corner, see attached screenshot) 
I have tried with many key codes defined here: 
https://developer.android.com/reference/android/view/KeyEvent
I have tried for ENTER, SEARCH, NEXT, DONE and many more with no luck.
I see that the python client library recently added meta state and flags to the press key code method, I have also tried setting some of those flags with no success.
Sending other key codes like BACK or special characters do work. Which makes me believe that i might be sending the incorrect key code.

## Environment
* Appium version (or git revision) that exhibits the issue: v1.8.0-beta5
* Desktop OS/version used to run Appium: MacOS High Sierra 10.13.3
* Node.js version (unless using Appium.app|exe): v10.5.0
* Mobile platform/version under test: Android Oreo 8.1
* Real device or emulator/simulator: Emulator
* Appium Python Client 0.26

## Link to Appium logs
I do not see anything relevant in the logs, all appium press key code events are marked as successful
Thanks!

## Screenshots
<img src="https://user-images.githubusercontent.com/531256/42247310-e917f588-7ee5-11e8-8366-df35c3343941.png" width="300px"/>

**Comment by mykola-mokhnach** [comment] 2018-07-04 05:02
Duplicate of https://github.com/appium/java-client/issues/916

**Closed by mykola-mokhnach** 2018-07-04 05:02 UTC

**Comment by mykola-mokhnach** [comment] 2018-07-05 20:34
Make sure the necessary field is focused. Otherwise I have no more ideas

**Comment by eduardoreynoso** [comment] 2018-07-06 17:08
@mykola-mokhnach I cant seem to get it working, im going to try to set it up on JAVA since you mentioned on the other issue that it was working. If it works with JAVA ill try to debug the issue with the python client, if it doesnt work with the JAVA client then ill try to click by coordinates.
Thanks for your help!
