### ISSUE TITLE
[ANDROID] Adb unable to install packages due to /data/app partition filling up

### ISSUE THREAD

**Issue by Jiurong-Yang** [appium/appium#13957] opened 2020-02-19 02:45 UTC
Appium Version: 1.15.1

Running into an issue for OS Version (7, 8, 9, 10). When we run tests on these devices continuously it seems like the device's /data/app partition is filling up with something, since the partition is extremely protected i cannot see what's in there nor how big the actual space is. 

The issues is the phone's **SD card have plenty of space (22 gb free)** but when we run appium we get the error message 

Appium Log: 
17:47:05 E       selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/opt/android/platform-tools/adb -P 5037 -s 936Y18F87 install -r /tmp/2020118-7622-1cbub4i.4z8x/appium-uiautomator2-server-v4.3.0.apk' exited with code 1'; Stderr: 'adb: failed to install /tmp/2020118-7622-1cbub4i.4z8x/appium-uiautomator2-server-v4.3.0.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE: Scanning Failed.: Package io.appium.uiautomator2.server could not be assigned a valid UID]'; Code: '1'

Logcat: 
02-18 17:46:08.173  1016  1075 E         : Couldn't opendir /data/app/vmdl1849548063.tmp: No such file or directory
02-18 17:46:08.173  1016  1075 E installd: Failed to delete /data/app/vmdl1849548063.tmp: No such file or directory
02-18 17:46:08.174  1384  2998 D PackageInstallerSession: Ignoring abandon after commit relinquished control
02-18 17:46:08.207   881   881 I Zygote  : Process 10750 exited due to signal 9 (Killed)

Currently when this happens for a device we need to either go clear all the user cache from other apps (It think this open solves the symptom but not the actual problem) which frees some space in the /data/app special partition. Or a factory reset which wipes the /data/app 

Since /data/app is super protected I can't even see what is filling this partition up. 

I can however look at the directory /data/local/tmp and specifically /data/local/tmp/appium_cache which did have some APK caches generated from appium. But deleting these files did not fix this issue. 

I was looking into the Desired Capabilities and it seems like androidInstallPath but it doesn't seem to fix the problem. 

Not sure if anyone else have ran into this issue or knows of a better fix than to factory reset the device every time this happens.

**Comment by mykola-mokhnach** [comment] 2020-02-19 06:42
it is possible to tell Appium not to use the device cache by setting the `remoteAppsCacheLimit` cap to `0`, but otherwise it looks like a server-unrelated issue to me.

**Comment by Jiurong-Yang** [comment] 2020-02-19 21:28
Already set the remoteAppsCacheLimit cap to 0. Doesn't seem to help the issue. I wonder if ADB is leaving some caches in there and it's not being cleaned up.

**Comment by mykola-mokhnach** [comment] 2020-02-19 21:35
This could a bug in device's firmware as well. Try to use the device from another manufacturer for automated testing

**Comment by Jiurong-Yang** [comment] 2020-02-19 22:04
We have about 16 devices under testing. And this issue have came up in multiple phones. Samsung, pixel, LG, etc. I'm looking into rooting one of our devices currently having this issue so I can get read permission on the partition so I can see what exactly is filling it up. And also it seems like using fastboot command it's possible to wipe the cache partition so that might be a clean up work around. But I don't know what is the side effect of cache partition wipe yet.

**Comment by mykola-mokhnach** [comment] 2020-02-27 18:22
Please let us know if there are any findings on this issue.

Closed as third party issue.

**Closed by mykola-mokhnach** 2020-02-27 18:22 UTC
Labels: Android, ThirdParty

**Comment by danielkiedrowski** [comment] 2021-01-27 07:52
Are there any updates on this? We are currently running into this issue on a Pixel 3 as well.

**Comment by Korop** [comment] 2021-03-02 16:27
The Same issue with Pixel3 Android 11.

When trying to install manually

root@0f204e2b20b1:~# adb -s 95BX208W4 install -r /root/apps/20210226_091054_935_M0xrrkdq_auto-tests_my_slot_qa.45824_en_480p_arm.apk
Performing Streamed Install
adb: failed to install /root/apps/20210226_091054_935_M0xrrkdq_auto-tests_my_slot_qa.45824_en_480p_arm.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE: Scanning Failed.: Package com.my.slot could not be assigned a valid UID]

adb logcat:

03-02 18:16:45.887  1545  1631 I ActivityManager: Killing 12943:com.google.android.videos/u0a169 (adj 975): empty for 1975s
03-02 18:16:45.926  1983  1983 V AvrcpMediaPlayerList: onActiveSessionsChanged: number of controllers: 0
03-02 18:16:45.927  1004  1004 I Zygote  : Process 12943 exited due to signal 9 (Killed)
03-02 18:16:45.929  1545  1631 I PackageManager: Integrity check passed for file:///data/app/vmdl314051544.tmp
03-02 18:16:45.934  1545  1609 I libprocessgroup: Successfully killed process cgroup uid 10169 pid 12943 in 46ms
03-02 18:16:46.030  1545  1631 W PackageManager: Package com.my.slot could not be assigned a valid UID
03-02 18:16:46.030  1545  1631 W PackageManager: Scanning Failed.
03-02 18:16:46.030  1545  1631 W PackageManager: com.android.server.pm.PackageManagerException: Package com.my.slot could not be assigned a valid UID
03-02 18:16:46.030  1545  1631 W PackageManager: 	at com.android.server.pm.Settings.registerAppIdLPw(Settings.java:877)
03-02 18:16:46.030  1545  1631 W PackageManager: 	at com.android.server.pm.PackageManagerService.optimisticallyRegisterAppId(PackageManagerService.java:11060)
03-02 18:16:46.030  1545  1631 W PackageManager: 	at com.android.server.pm.PackageManagerService.installPackagesLI(PackageManagerService.java:16862)
03-02 18:16:46.030  1545  1631 W PackageManager: 	at com.android.server.pm.PackageManagerService.installPackagesTracedLI(PackageManagerService.java:16222)
03-02 18:16:46.030  1545  1631 W PackageManager: 	at com.android.server.pm.PackageManagerService.lambda$processInstallRequestsAsync$22$PackageManagerService(PackageManagerService.java:14388)
03-02 18:16:46.030  1545  1631 W PackageManager: 	at com.android.server.pm.-$$Lambda$PackageManagerService$9znobjOH7ab0F1jsW2oFdNipS-8.run(Unknown Source:6)
03-02 18:16:46.030  1545  1631 W PackageManager: 	at android.os.Handler.handleCallback(Handler.java:938)
03-02 18:16:46.030  1545  1631 W PackageManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-02 18:16:46.030  1545  1631 W PackageManager: 	at android.os.Looper.loop(Looper.java:223)
03-02 18:16:46.030  1545  1631 W PackageManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
03-02 18:16:46.030  1545  1631 W PackageManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
03-02 18:16:46.038  1226  1246 E installd: Couldn't opendir /data/app/vmdl314051544.tmp: No such file or directory
03-02 18:16:46.038  1226  1246 E installd: Failed to delete /data/app/vmdl314051544.tmp: No such file or directory
03-02 18:16:46.049  1545  1545 W Binder:1545_F: type=1400 audit(0.0:227745): avc: denied { getopt } for scontext=u:r:system_server:s0 tcontext=u:r:shell:s0 tclass=unix_stream_socket permissive=0
03-02 18:16:46.049  1545  1545 I chatty  : uid=1000 system_server identical 1 line

**Comment by mykola-mokhnach** [comment] 2021-03-02 17:02
After investigated the Android source code it turns out that it has a hardcoded limit of 10000 UIDs. Each UID is created upon new app installation, which means one could install up to 10000 apps until the system starts to throw the error above. The only way to "fix" this error is to restart the phone, which would reset the UIDs counter.
Also, it is important to mention that a new UID is only created if a new app installed. Reinstalling the same app (`adb install -r`) won't increment it.

**Comment by Jiurong-Yang** [comment] 2021-03-02 17:10
Glad you guys are looking into it. But i know for a fact that this does not work. We've tried rebooting the phone and it only fixes the problem rarely. And at instances where it does fix it by rebooting the problem comes back a lot faster than if we do a factory reset. I suspect that by rebooting the Android OS sometimes free up some space on the SD card that's why it starts working again but obviously the majority of the junk data isn't cleared. So it only helps a little.

We've been running into this problem for years. Let me know if you guys want additional data points.

**Comment by Korop** [comment] 2021-03-11 13:01
@mykola-mokhnach 
In my case the Pixel restarting helps to install app  with` adb install -r`. And I can repeat this several times without any issue till I deleted the package via separate command  like `adb uninstall` or another uninstall command. After that I could not install the app via adb because of error mentioned above. 
When I restart the Pixel again the issue was gone but the thing which breaks this - was uninstallation of the package as separate cmd.
So the usual restart doesn't fix the issue completely and allow do correct install / uninstall only once.

>>only way to "fix" this error is to restart the phone
Did you mean full factory reset to defaults or just restart?

**Comment by sharmaajay201291** [comment] 2022-01-04 07:57
Any update or fix for this issue. We are also facing the same issue with Pixel 4a Android 12. This is working fine with Samsung Devices with Android 9. 
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\spaunikar\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s 16171JEC201193 install -r --no-incremental C:\\Users\\ajsharma\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v4.27.0.apk' exited with code 1'; Command output: adb: failed to install C:\Users\ajsharma\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.27.0.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE: Scanning Failed.: Package io.appium.uiautomator2.server could not be assigned a valid UID] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: 'INPUN1AUTO09WIN', ip: '10.70.8.92', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221' Driver info: driver.version: AndroidDriver remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\spaunikar\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s 16171JEC201193 install -r --no-incremental C:\\Users\\ajsharma\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v4.27.0.apk' exited with code 1'; Command output: adb: failed to install C:\Users\ajsharma\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.27.0.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE: Scanning Failed.: Package io.appium.uiautomator2.server could not be assigned a valid UID] at getResponseForW3CError (C:\Users\ajsharma\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9) at asyncHandler (C:\Users\ajsharma\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37) Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: 'INPUN1AUTO09WIN', ip: '10.70.8.92', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221' Driver info: driver.version: AndroidDriver

**Comment by pr4bh4sh** [comment] 2023-07-26 10:26
For future reference:
The issue is with OS: https://issuetracker.google.com/issues/170867658

Solution: https://kazucocoa.wordpress.com/2022/06/05/android-install_failed_insufficient_storage-scanning-failed-package-could-not-be-assigned-a-valid-uid-in-android/
