### ISSUE TITLE
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up.

### ISSUE THREAD

**Issue by anniegandhi** [appium/appium#15270] opened 2021-04-13 17:29 UTC
## The problem

While I was writing appium code to write testcases for my app , I surprizingly encountered one issue . My tests could not get executed because it got failed in the start only.

The same code was running earlier and with no change I saw this issue in the appium logs .

**Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up.

 at UIA2Proxy.command (C:\Users\Zscaler\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:275:13)
[debug] [W3C]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[debug] [W3C]     at AndroidUiautomator2Driver.commands.getDevicePixelRatio (C:\Users\Zscaler\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\commands\viewport.js:14:10)
[debug] [W3C]     at AndroidUiautomator2Driver.fillDeviceDetails (C:\Users\Zscaler\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:239:28)
[debug] [W3C]     at AndroidUiautomator2Driver.createSession (C:\Users\Zscaler\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:225:7)
[debug] [W3C]     at AppiumDriver.createSession (C:\Users\Zscaler\AppData\Roaming\npm\node_modules\appium\lib\appium.js:371:35)
[HTTP] <-- POST /wd/hub/session 500 11815 ms - 1323**
[HTTP]
## Environment

* Appium version :1.20.0:
* Using emulator .
* Using Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/anniegandhi/46fc9c880fe5d5860979ae9ca8495d17

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/anniegandhi/aef248692162b913d7fb1b38585d7c4d

**Comment by mykola-mokhnach** [comment] 2021-04-13 18:19
Socket hang up error means the UIAutomator2 server stopped responding to requests. Please attach the logcat output for the given time period

**Comment by anniegandhi** [comment] 2021-04-14 04:54
Hi ..I am not sure what do you mean by logcat output. Could you please explain.

**Comment by KazuCocoa** [comment] 2021-04-14 05:10
They are:
https://developer.android.com/studio/debug/am-logcat
https://developer.android.com/studio/command-line/logcat
https://github.com/appium/appium-uiautomator2-driver#mobile-startlogsbroadcast

**Comment by anniegandhi** [comment] 2021-04-14 06:57
https://gist.github.com/anniegandhi/81fba5218ccadf4a25bc2841151a19a5

**Comment by mykola-mokhnach** [comment] 2021-04-14 07:00
The log chynk above is not enough to figure out anything. Please attach the full log for the given time range

**Comment by anniegandhi** [comment] 2021-04-14 07:10
https://gist.github.com/anniegandhi/81fba5218ccadf4a25bc2841151a19a5

Updated

**Comment by mykola-mokhnach** [comment] 2021-04-14 08:10
> 04-13 23:41:23.405 16258 16276 W Binder  : java.lang.SecurityException: Calling from not trusted UID!
> 04-13 23:41:23.405 16258 16276 W Binder  :      at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:465)
> 04-13 23:41:23.405 16258 16276 W Binder  :      at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:369)
> 04-13 23:41:23.405 16258 16276 W Binder  :      at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:216)
> 04-13 23:41:23.405 16258 16276 W Binder  :      at android.os.Binder.execTransact(Binder.java:697)

Seems to be a duplicate of https://github.com/appium/appium/issues/15154
Nothing much we could do there

**Comment by anniegandhi** [comment] 2021-04-14 08:18
Is there any workaround of the same . I tried restarting the device as well
as appium server . Nothing helped.

Anything else I can do to get it working.


Regards,
Aashima

**Comment by mykola-mokhnach** [comment] 2021-04-16 18:18
Unfortunately we don't know about any other workarounds. Try to ask at Google support forums

**Closed by mykola-mokhnach** 2021-04-16 18:18 UTC
Labels: Android, ThirdParty

**Comment by anniegandhi** [comment] 2021-04-17 05:43
Thanks for spending your time looking into this.


Regards,
Aashima

**Comment by anniegandhi** [comment] 2021-05-31 11:46
Hi ,

Need one help .

I am using :driver.pressKeyCode(AndroidKeyCode.BACK);  to goBack  with
these classes :
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.android.AndroidKeyCode;

But still I am getting  below exception :

java.lang.NoSuchMethodError: 'void
io.appium.java_client.android.AndroidDriver.pressKeyCode(int)'
at
ZscalerAppiumLib.organizationSummary.validate_Goback(organizationSummary.java:154)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

Could you please check once


Regards,
Aashima
