### ISSUE TITLE
Appium 1.6.2 :Tap element using xy co-ordinates do not work.

### ISSUE THREAD

**Issue by SonaliBurghate** [appium/appium#7379] opened 2016-12-06 09:20 UTC
The problem

I am working on a test script which taps on a element using device xy co-ordinates. I have used driver.tap(int fingers,x,y,int duration); however it throws An unknown server-side error. 

 Environment
* Appium version (or git revision) that exhibits the issue: 1.6.2
* Last Appium version that did not exhibit the issue (if applicable): 1.4.8
* Desktop OS/version used to run Appium: Mac 10.11.6
* Node.js version (unless using Appium.app|exe): NA
* Mobile platform/version under test:iOS 10.0.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Not sure

**Comment by mykola-mokhnach** [comment] 2016-12-06 10:55
Any logs?

**Comment by SonaliBurghate** [comment] 2016-12-06 11:17
Thanks for the reply, I have following error available with me. Will soon update you with detail logs.

_An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/195C04FF-44B2-43D6-BC23-07AC408BE613/touchAndHold -- http://localhost:8100/ with parameters ._

**Comment by ptsiakos77** [comment] 2016-12-06 13:32
The tap event is not working for me as well event when clicking without coordinates using Appium 1.6.2

**Comment by SonaliBurghate** [comment] 2016-12-07 06:41
@mykola-mokhnach Please find complete error logs :

An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/6658A7EF-FD24-4C36-99A6-B01AD5B41024/touchAndHold -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/6658A7EF-FD24-4C36-99A6-B01AD5B41024/touchAndHold"
    );
} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 12 milliseconds
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'nileshs-mini.cybage.com', ip: '172.27.46.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_60'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/nilesh/Desktop/Phase8/src/main/resources/apps/QaTestApp_3.14.0.20_8_default-resigned.ipa, networkConnectionEnabled=false, orientation=PORTRAIT, noReset=true, appiumVersion=1.6.2, xcodeConfigFile=/Users/nilesh/Desktop/Config.xcconfig, databaseEnabled=false, fullReset=false, deviceName=iPhone 6s, platform=MAC, showIOSLog=true, sendKeyStrategy=setValue, newCommandTimeout=7200, realDeviceLogger=/usr/local/lib/node_modules/deviceconsole/deviceconsole, platformVersion=10.0.2, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, name=iOS, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=345825e63e36efd63aef74e283455a2f35e4959b}]
Session ID: 75056264-bd3a-44b1-9a5b-4d709c0842b4

**Comment by SonaliBurghate** [comment] 2016-12-07 07:33
@mykola-mokhnach Please refer below logs :
 _An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/E60A4E3C-D2E3-4413-AFDB-C47076FF9767/touchAndHold -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/E60A4E3C-D2E3-4413-AFDB-C47076FF9767/touchAndHold"
    );
} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 56 milliseconds
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'nileshs-mini.cybage.com', ip: '172.27.46.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_60'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/xyz/Desktop/testSuite/src/main/resources/apps/TestApp.ipa, networkConnectionEnabled=false, orientation=PORTRAIT, noReset=true, appiumVersion=1.6.2, xcodeConfigFile=/Users/nilesh/Desktop/Config.xcconfig, databaseEnabled=false, fullReset=false, deviceName=iPhone 6s, platform=MAC, showIOSLog=true, sendKeyStrategy=setValue, newCommandTimeout=7200, realDeviceLogger=/usr/local/lib/node_modules/deviceconsole/deviceconsole, platformVersion=10.0.2, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, name=iOS, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=345825e63e36efd63aef74e283455a2f35e4959b}]
Session ID: fbaeec62-ec90-44b1-9d98-0970fcd3bb07_

**Comment by imurchie** [comment] 2016-12-09 23:08
I'm not able to reproduce. Can you provide the _full_ logs (as a [gist](https://gist.github.com)) so we can see the context and what is going on.

Log snippet for the call from a run locally:

```
info HTTP --> POST /wd/hub/session/4ae7c8ae-22b6-41c2-823b-a6ac0ec23bf5/touch/perform {"actions":[{"action":"press","options":{"x":18,"y":127}},{"action":"wait","options":{"ms":500}},{"action":"release","options":{}}]}
dbug MJSONWP Calling XCUITestDriver.performTouch() with args: [[{"action":"press","options":{"x":18,"y":127}},{"action":"wait","options":{"ms":500}},{"action":"release","options":{}}],"4ae7c8ae-22b6-41c2-823b-a6ac0ec23bf5"]
dbug XCUITest Executing command 'performTouch'
dbug XCUITest Received the following touch action: press-wait-release
dbug JSONWP Proxy Proxying [POST /touchAndHold] to [POST http://localhost:8100/session/A271664B-011E-412F-91E8-7508D917D403/touchAndHold] with body: {"duration":0.5,"x":18,"y":127}
dbug JSONWP Proxy Got response with status 200: {"value":{},"sessionId":"A271664B-011E-412F-91E8-7508D917D403","status":0}
dbug MJSONWP Responding to client with driver.performTouch() result: {}
info HTTP <-- POST /wd/hub/session/4ae7c8ae-22b6-41c2-823b-a6ac0ec23bf5/touch/perform 200 1392 ms - 74
```

**Comment by KBhatti** [comment] 2017-01-09 21:37
@SonaliBurghate is driver.tap or touchaction tap working for you? It doesn't work for me with Appium 1.6.3/iOS10.2

**Comment by dilsreccse** [comment] 2017-01-10 04:19
I am also facing same issue. Not able to tap on elements using x,y co-ordinates. Is there any fix for this?

**Closed** 2017-04-17 22:41 UTC
Labels: NeedsTriage
