### ISSUE TITLE
Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present"

### ISSUE THREAD

**Issue by lucasdaniele1** [appium/appium#8412] opened 2017-05-09 14:17 UTC
## The problem
SendKeys is not working on numeric keyboard:

## Environment

Appium Desktop : Version 1.0.0 (1.0.0)

Appium --version
1.6.4

Mac OS
node --version
v7.9.0
Simulator -Iphone SE OS 10.3

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/c05f2815-b46c-4c81-add0-577b90cd329a/element/E4B34429-A069-45E1-9F45-72B0F4832B2C/value {"id":"E4B34429-A069-45E1-9F45-72B0F4832B2C","value":["3579284"]}
[MJSONWP] Calling AppiumDriver.setValue() with args: [["3579284"],"E4B34429-A069-45E1-9F45-72B0F4832B2C","c05f2815-b46c-4c81-add0-577b90cd329a"]
[XCUITest] Executing command 'setValue'
[JSONWP Proxy] Proxying [POST /element/E4B34429-A069-45E1-9F45-72B0F4832B2C/value] to [POST http://localhost:8100/session/FD798DED-5D57-4EE2-A3B5-3BF861D1ABBD/element/E4B34429-A069-45E1-9F45-72B0F4832B2C/value] with body: {"value":["3","5","7","9","2","8","4"]}
[JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Keyboard is not present\" UserInfo={NSLocalizedDescription=Keyboard is not present}","sessionId":"FD798DED-5D57-4EE2-A3B5-3BF861D1ABBD","status":13}
[JSONWP Proxy] Proxying [GET /element/E4B34429-A069-45E1-9F45-72B0F4832B2C/attribute/type] to [GET http://localhost:8100/session/FD798DED-5D57-4EE2-A3B5-3BF861D1ABBD/element/E4B34429-A069-45E1-9F45-72B0F4832B2C/attribute/type] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"XCUIElementTypeOther\",\n  \"sessionId\" : \"FD798DED-5D57-4EE2-A3B5-3BF861D1ABBD\",\n  \"status\" : 0\n}"
[HTTP] <-- POST /wd/hub/session/c05f2815-b46c-4c81-add0-577b90cd329a/element/E4B34429-A069-45E1-9F45-72B0F4832B2C/value 500 5892 ms - 304 
[HTTP] --> DELETE /wd/hub/session/c05f2815-b46c-4c81-add0-577b90cd329a {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["c05f2815-b46c-4c81-add0-577b90cd329a"]
[BaseDriver] Event 'quitSessionRequested' logged at 1494338380098 (10:59:40 GMT-0300 (ART))
[JSONWP Proxy] Proxying [DELETE /session/c05f2815-b46c-4c81-add0-577b90cd329a] to [DELETE http://localhost:8100/session/FD798DED-5D57-4EE2-A3B5-3BF861D1ABBD] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"5B1A5A95-FEBC-4E7B-BD8F-BFBFF55F23B1\",\n  \"status\" : 0\n}"
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 66500)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Found WDA derived data folder: '/Users/ldaniele/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs'
[XCUITest] Setting '755' permissions to '/Users/ldaniele/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Attachments' folder
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[Appium] Removing session c05f2815-b46c-4c81-add0-577b90cd329a from our master session list
[BaseDriver] Event 'quitSessionFinished' logged at 1494338380635 (10:59:40 GMT-0300 (ART))
[MJSONWP] Received response: null
[MJSONWP] But deleting session, so not returning
[MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/c05f2815-b46c-4c81-add0-577b90cd329a 200 537 ms - 76 

## Code To Reproduce Issue [ Good To Have ]
itemNumber.sendKeys(number);

**Comment by mykola-mokhnach** [comment] 2017-05-09 17:34
Try to tap numeric buttons by locating them as normal page elements as a workaround.

**Comment by mykola-mokhnach** [comment] 2017-05-10 10:11
Closed as duplicate of https://github.com/facebook/WebDriverAgent/issues/574

**Closed by mykola-mokhnach** 2017-05-10 10:11 UTC

**Comment by lucasdaniele1** [comment] 2017-05-10 12:58
Yes for now we are doing that, but it is to slow. Thanks

**Comment by mykola-mokhnach** [comment] 2017-05-10 13:03
Of course it's slow if you locate a keyboard button each time before to click it. I'd rather get all buttons using single lookup and then just put their coordinates into a cache. Next time when keyboard is visible one can simply perform tap by cached coordinates, since the keyboard will be always located at the same place.

**Comment by lucasdaniele1** [comment] 2017-05-10 13:40
good, thanks

**Comment by ToniChaz** [comment] 2017-06-06 13:48
Same error here.
_Error: [element.sendKeys("optest@mail.com")] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present_

This works: 
```
<View style={styles.textInputView}>
          <TextInput
            style={styles.textInput}
            onChangeText={(password) => this.setState({password})}
            value={this.state.password}
            accessibilityLabel='Password'
            secureTextEntry={true}
            autoCapitalize='none'
            autoCorrect={false}
          />
</View>
```

This not wolks:
```
<View style={styles.textInputView}>
          <Text style={styles.textInputLabel}>Password</Text> // Add this line as label
          <TextInput
            style={styles.textInput}
            onChangeText={(password) => this.setState({password})}
            value={this.state.password}
            accessibilityLabel='Password'
            secureTextEntry={true}
            autoCapitalize='none'
            autoCorrect={false}
          />
</View>
```

In Android works fine but in iOS get an error.
