### ISSUE TITLE
Could not reuse existing WDA on real iPhone device.

### ISSUE THREAD

**Issue by amokmen** [appium/appium#12259] opened 2019-03-05 14:38 UTC
## The problem

Problem is that Appium **could not reuse existing WDA on real iPhone device** - every next _test script run_ there would be unsuccessful try to get response, deleting existing WDA and installing new WDA.

There are some interesting things:
1) For http://localhost:8100/status request THERE IS response **200**! But later "Failed to create WDA session"

2) Strange line `[XCUITest]     at quitAndUninstall (/Users/admin/appium/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:476:13)`
Seems like buggy log output.

## Environment

* Appium server v1.11.1
* Node.js v10.15.1
* Npm 6.8.0
* Mobile platform/version under test: iOS 12.1
* Real device: iPhone X

## Link to Appium logs

[GIST appuim_log_XCUITest_real_device_could_not_reuse_WDA](https://gist.github.com/amokmen/4919b7b79209a1a90c7dc893d1dc2a4f).

**Comment by KazuCocoa** [comment] 2019-03-06 08:57
Below response returned in https://gist.github.com/amokmen/4919b7b79209a1a90c7dc893d1dc2a4f#file-appuim_log_xcuitest_real_device_could_not_reuse_wda-L17 . 

```
2019-03-05 16:40:18:301 - [debug] [WD Proxy] Matched '/status' to command name 'getStatus'
2019-03-05 16:40:18:301 - [debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
2019-03-05 16:40:18:311 - [WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
2019-03-05 16:40:18:312 - [debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
2019-03-05 16:40:19:322 - [debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1551793219322
2019-03-05 16:40:19:323 - [debug] [XCUITest] Sending createSession command to WDA
```

Could you share a gist with `showXcodeLog` and `showIOSLog`?
Need to find the cause of `ECONNREFUSED` (Killed the process by system or crashed for example)

**Comment by mykola-mokhnach** [comment] 2019-03-09 07:22
@amokmen Please provide the detailed logs or the issue is going to be closed as incomplete

**Comment by amokmen** [comment] 2019-03-10 07:05
I didn't forget. Just trying to understand what is happening deeply, to make _good_ response.

**Comment by amedvedjev** [comment] 2019-03-12 09:14
I have same behavior when i start new appium server.
 - e.g. executed one test. updated testNG xml to another test and run.

I do not have this issue during long runs of many tests while using same appium server session.
 -e.g. in testNG xml specified to run multiple tests and appium server starts only one time in beforeSuite method.

**Comment by amokmen** [comment] 2019-03-12 12:18
I've lost 8 hours yesterday trying to understand what the hell is going on.

First sight on problem: Appium **every new session** unsuccessfully trying to run already installed `WDA` on iPhone, then uninstall it from device, build and install new `WDA`, successfully use it to communicate. Next Appium run do the same loop.

So, I decided to do some steps manually: run `iproxy` and was trying to run `WDA` on device, but `WDA` didn't run! It was look like I tap on `WDA` icon, app starts, shows me black screen and immediately closes. I checked logs from device (used filter by "WebDriver") - there were errors. So, I could not communicate with `WDA` on phone from Mac mini through `iproxy` (for doing this I used `Postman` for sending request to `http://localhost:8100/status`).

[Logs from device while trying to run `WDA` manually (filter "WebDrive" is active)](https://gist.github.com/amokmen/f2c6824763785b0ce38426b7f8d92483).

While trying to understand what is going on, I started build `WDA` manually and become to conclusion (which need to be approved) that `WDA` could be run ONLY in live session (probably according security reason from Apple).

More words to explain my thought: when `xcodebuild` builds and installs `WDA` on device there is some live test session between `xcodebuild` and `WDA` app. While `xcodebuild` is running - I could open `WDA` at device and could communicate with it! But if I interrupt `xcodebuild` build&test session by `CTRL+C`, I could not start `WDA` anymore!

So, my questions are:
1) Why I could not manually build&install `WDA` on device and run it manually when I want to communicate with it through `iproxy`?
2) Is there any security reason from Apple to block running `WDA` on device on it is own? Like app could initiate some malicious session and send some data to USB port? So, there should be initialization of such running app ONLY from outside of device?

**Comment by amokmen** [comment] 2019-03-12 16:16
It seems I got it.

If you **sign app** with iOS **Developer** certificate and trying to **run it on device manually** without connection to `Xcode` or command line `xcodebuild` - **app simple would not run**! F*g Apple security reasons...

**Comment by mykola-mokhnach** [comment] 2019-03-20 08:49
Thanks for the investigation @amokmen . Would you mind to describe this solution and add it to Appium documentation, so other people could solve similar problems?

**Comment by amokmen** [comment] 2019-03-22 17:35
@mykola-mokhnach I am still in deep research. Rather unsuccessful...

We have paid Apple Developer account (as Organization), so I've created **iOS Distribution certificate** and **AdHoc provisioning profile** (with included my 2 mobile devices and wildcard bundle id like com.company.test.*).

**I want to build WDARunner with Distribution certificate to install and normally run on my real devices.**

I am able to do `xcodebuild archive` and after `xcodebuild -exportArchive` to install _simple created in Xcode application_ to real mobile device. 

But I could not do the same with WebDriverAgentRunner!
There are 2 errors:
```
error: Provisioning profile "HERE_PP_NAME" doesn't match the entitlements file's value for the get-task-allow entitlement. (in target 'WebDriverAgentRunner')
```
and
```
WebDriverAgentLib has conflicting provisioning settings. WebDriverAgentLib is automatically signed, but provisioning profile HERE_PP_NAME has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor, or switch to manual signing in the project editor. (in target 'WebDriverAgentLib')
```

I don't understand first error. I've googled for 2 days... Something wrong with WebDriverAgentRunner project? I don't know...

Second error simply stupid... When doing `xcodebuild archive` I am using `PROVISIONING_PROFILE=RIGHT_PP_UUID_HERE`.

And there is dilemma:
1) if I use PP - I get this error: **WebDriverAgentRunnerLib** could not be build (because Lib should be **autosigned** and there is really no need in provisioning profile).
2) If I don't use PP - I got error that without PP there could not be build **WebDriverAgentRunner** (but for building WebDriverAgentRunner there is should be provisioning profile!).

But to archive WDARunner app I need to build them both - WebDriverAgentRunner and WebDriverAgentRunnerLib!

Dead end.

My build command line for simple-example Xcode app:
```
xcodebuild archive \
   -archivePath /Users/admin/wda_build/MyApp3214.xcarchive \
   -project /Users/admin/mySimpleTestApp/TestSigning/DelMe_WithTests/DelMe_WithTests.xcodeproj \
   -scheme DelMe_WithTests \
   -configuration Debug \
   CODE_SIGN_IDENTITY="HERE_RIGHT_STRING" \
   PROVISIONING_PROFILE=HERE_RIGHT_PP_UUID \
   DEVELOPMENT_TEAM=HERE_TEAM_ID \
   -verbose
```
and export archive to get *.ipa file for distribution:
```
xcodebuild \
   -exportArchive \
   -exportFormat IPA \
   -archivePath /Users/admin/wda_build/MyApp3214.xcarchive \
   -exportPath /Users/admin/wda_build/MyApp3214.ipa \
   -exportProvisioningProfile HERE_RIGHT_PP_UUID
```
later install to real device by USB:
```
ios-deploy -b /Users/admin/wda_build/MyApp3214.ipa/DelMe_WithTests.ipa
```

**Comment by amokmen** [comment] 2019-03-22 19:30
Another info according to starting message of this issue.

Now, in desperate mind, I decided to build WDARunner without command line, just simple autosigning in Xcode and with my personal free Apple developer account.

I build and install it on real device.

And again, **without active test session with Xcode WDArunner is crashing**.
I write logs from device and start carefully examine them and FOUND:
```
22:01:14.984472 +0300	999	Default	testmanagerd	Not permitting UI test control for client with pid 2429, no matching control session found
```
and later:
```
22:01:15.040312 +0300	2229	proc_state	symptomsd	2429 com.apple.test.WebDriverAgentRunner-Runner: Terminated (most elevated: Terminated)
```

Pid 2429 is WDARunner. So, all as I thought before - but now it's clear:
**if WDARunner started without active external test session, daemon _testmanagerd_ blocking application**

And my question is:
**Am I first person in the world who discovered it?**

**Comment by mykola-mokhnach** [comment] 2019-03-22 19:47
> Am I first person in the world who discovered it? Am I only one person who using Appium for testing on iOS real devices?

Not many people are digging deep into this topic, since nothing there is documented and most of the stuff can only be figured out based on engineering the logs/observing the actual behaviour. Welcome to the Apple world. 

Although, we would only be happy if you could use your knowledge/results of your invetigation to improve Appium.

**Comment by amokmen** [comment] 2019-03-22 20:33
I am in full frustration state of mind and just could not believe in this: that I am junior tester who just start using Appium could see all this bugs/strange behavior - and no one else could?! Am I f*g genius? But I am not. It's all so strange for me... Like people working (But how they could work with it?! 1 basic test run takes more than 1 minute! Is that 'production'?!) and I come and start asking **simple** questions and suddenly no one could answer this simple questions. Like all just blind and could see nothing... Or like they didn't understand me because they work with Appium's infrastructure **in different way**... Very strange feeling... **I am not blaming anyone, no. Just trying to understand how that could be in reality.** Like I am one in desert and only wind blows in my face... :)

I could understand if my questions would be complex - no one probably could answer. But I am still in hello-world stage! Hello-world stage, Karl! No special cases - all simple and as described in docs... And tons of pain and questions at every step... Probably I am just very unlucky person? :)

According to helping to Appium project - Am I not helping now, by creating this issues and answering to myself after weeks of investigation? :)

**Comment by mykola-mokhnach** [comment] 2019-03-22 20:43
Don't underestimate yourself and don't think everyone is a genius. There are simply too many things in this world to work on and not only this particular one. You've already helped a lot to yourself and potentially to other people who are stuck with similar problems. To be honest I've started doing appium development myself because no one could answer my "simple" questions at the beginning.

**Comment by KazuCocoa** [comment] 2019-03-23 06:39
I investigated it further. Maybe,  https://github.com/appium/appium-xcuitest-driver/pull/909 can alleviate re-using existing WDA behaviour. (I appreciate your investigation btw.)

----

Below is just fyi:

In ruby_lib_core test suite has an example to use `useXctestrunFile` capability in order to reduce WDA build time to use `xcodebuild test-without-build` when launch xcodebuild process on simulator/real devices. [example](https://kazucocoa.wordpress.com/2019/03/15/appium-prevent-building-wda-with-usexctestrunfile-or-useprebuiltwda/)
https://github.com/appium/ruby_lib_core/blob/master/test/test_helper.rb#L92

According to https://discuss.appium.io/t/automatic-signing-is-unable-to-resolve-an-issue-with-the-webdriveragentrunner-targets-entitlements/25516/11 , some guys fased `get-task-allow...` signing issue in their personal account was fixed by re-creating account. just fyi in https://github.com/appium/appium/issues/12259#issuecomment-475712076

**Closed** 2019-03-23 15:18 UTC
Labels: Bug, Documentation
