### ISSUE TITLE
IOS: WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not navigate to webview; there are none!

### ISSUE THREAD

**Issue by jlee6890** [appium/appium#12514] opened 2019-04-18 06:50 UTC
# The problem

When trying to execute mobile web test, Safari browser opens up, but nothing happens and test eventually throws exception and errors out.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.12.1**
* Desktop OS/version used to run Appium: **macOS Mojave 10.14.4**
* Node.js version (unless using Appium.app|exe): **v10.12.0**
* Npm or Yarn package manager: **Npm (6.9.0)**
* Mobile platform/version under test: **iOS 12.2**
* Real device or emulator/simulator: **Real device**
* Appium CLI or Appium.app|exe: **Appium CLI**

## Details

The following exception is thrown:

> WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not navigate to webview; there are none!

Capabilities i'm using:
```
{
  "udid": "920ede9282b6f7b595a391f2a966f19ef17865cf",
  "deviceName": "QA iPhone 7 Plus",
  "platformName": "iOS",
  "platformVersion": "12.2",
  "browserName": "Safari",
  "newCommandTimeout": 3000,
  "startIWDP": true
}
```

## Link to Appium logs
https://gist.github.com/jlee6890/f159559c76d204efaf914fd3a79b6d65

**Comment by mykola-mokhnach** [comment] 2019-04-18 07:56
Can you list the web view in IWDP from terminal? Is IWDP up to date?

**Comment by jlee6890** [comment] 2019-04-18 16:35
@mykola-mokhnach how do you list web view in IWDP from terminal? Do you mean running `ios_webkit_debug_proxy -c 920ede9282b6f7b595a391f2a966f19ef17865cf:27753 -d`?

I updated IWDP to 1.8.4, but i'm getting a new exception:

> WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'Console' domain was not found

Here are the updated Appium logs:
https://gist.github.com/jlee6890/56098690fcbb84713f6e5281d4e6a1bf

**Comment by mykola-mokhnach** [comment] 2019-04-18 18:27
Duplicate of https://github.com/appium/appium/issues/12518

**Comment by jlee6890** [comment] 2019-04-18 18:39
@mykola-mokhnach, wait so how do you list web view in IWDP from terminal?

**Comment by mykola-mokhnach** [comment] 2019-04-24 14:41
Try https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter

**Comment by mykola-mokhnach** [comment] 2019-04-26 04:49
Closed as duplicate

**Closed by mykola-mokhnach** 2019-04-26 04:49 UTC
Labels: Mobile Safari, NeedsInfo
