### ISSUE TITLE
IOS Objects are shown as invisible even though they are clearly visible 

### ISSUE THREAD

**Issue by Jiurong-Yang** [appium/appium#11529] opened 2018-10-15 22:43 UTC
When inspecting from the Appium inspector(And also during test runs) A lot of elements are marked as invisible even though they are displayed on the screen. 

## Environment
Appium: 1.9.1, 1.9.0, 1.8.1

![img](https://user-images.githubusercontent.com/1619565/46982275-7913aa00-d090-11e8-8437-00ad06962ada.jpg)

As you can see the elements on the pop up are all visible. But the XML is returning invisible. This is an issue for us because visible/not visible is the only way we can determine if an element is actually displayed or if it's just in the page source. 

On a side note. All the elements on the webview of this app is shown as invisible (I believe it's developed using the safari webview sdk). And I think If i enable the ios-webview-debug-proxy I'll be able to see the source html but in the NATIVE_APP context all the elements show up in the XML just with the property of invisible.

**Comment by mykola-mokhnach** [comment] 2018-10-16 05:17
Closed as duplicate of https://github.com/appium/appium/issues/11507

Also third party issue, which cannot be fixed on appium side.

**Closed by mykola-mokhnach** 2018-10-16 05:17 UTC

**Comment by mykola-mokhnach** [comment] 2018-10-16 05:19
A general recommendation: only interact with webview element inside webview context.
