### ISSUE TITLE
Android Application open & closed without any error [Version - 1.16.0-rc.0]

### ISSUE THREAD

**Issue by sp090** [appium/appium#13676] opened 2019-12-04 06:00 UTC
When I switch to these version 1.16.0-rc.0 & try to start the application it's directly closed without any reason.

**Comment by mykola-mokhnach** [comment] 2019-12-04 07:13
Please provide a proper issue description. Closed as incomplete. 

Also, possible duplicate of https://github.com/appium/appium/issues/13660

**Closed by mykola-mokhnach** 2019-12-04 07:13 UTC
