### ISSUE TITLE
appium 1.6.3 crashed due to process out of memory

### ISSUE THREAD

**Issue by xinufo** [appium/appium#7531] opened 2016-12-14 06:57 UTC
## The problem

appium 1.6.3 crashed due to process out of memory

## Environment

* Appium version (or git revision) that exhibits the issue: **1.6.3**
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: **Windows 7 SP1 x64**
* Node.js version (unless using Appium.app|exe): **4.6.0**
* Mobile platform/version under test: **android**
* Real device or emulator/simulator: **simulator**
* Appium CLI or Appium.app|exe: **Appium CLI**

## Details

I'm testing a hybird app with appium 1.4.16, after about 15 minutes, appium crashed and got the message of node "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory". I updated appium to 1.6.3, the result is same.

## Link to Appium logs

- appium log: https://github.com/xinufo/AppiumMemoryLeakTest/blob/master/logs/appium_log.txt
- memory: https://github.com/xinufo/AppiumMemoryLeakTest/blob/master/logs/memory.png

## Code To Reproduce Issue [ Good To Have ]

all the codes, logs and apk are here
https://github.com/xinufo/AppiumMemoryLeakTest.git

**Comment by jlipps** [comment] 2016-12-14 21:10
Interesting. Does the amount of memory used change based on the frequency of commands? I'm trying to ascertain whether the leak is due to the number of commands run or whether it's just due to the amount of time Appium is open.

Another thing you could try: set `newCommandTimeout` capability to 0 to turn it off, then just have it sit there for 15 minutes, sending in no new commands, and see if memory usage still increases. That would help narrow down what the issue might be.

**Comment by estellemasso** [comment] 2016-12-14 22:09
I am consistently running into this process out of memory error after running about 30 tests each taking about a minute and half.

**Comment by xinufo** [comment] 2016-12-15 02:01
@jlipps 

I tried it, and I think the leak has relation to the amount of time Appium is open

## Steps:
1. set newCommandTimeout capability to 0
2. create an AndroidDriver
3. switch to webview
4. do nothing in 15 minutes

## Results:
1. memory keeps increasing all the time
2. if I don't switch to webview, memory also keeps increasing but more slowly

## Memory
- in webview: https://github.com/xinufo/AppiumMemoryLeakTest/blob/master/logs/memory_webview.png
- in native_app: https://github.com/xinufo/AppiumMemoryLeakTest/blob/master/logs/memory_native_app.png

**Comment by jlipps** [comment] 2016-12-15 17:16
@xinufo thanks for the research. Can you attach the appium log for when you tried with appium 1.6.3? Also, do you have access to a mac by any chance? I'm wondering if this is isolated to Windows because I've never seen it before.

**Comment by estellemasso** [comment] 2016-12-15 17:44
I am using a mac and I am experiencing the exact same issue described by @xinufo

**Comment by jlipps** [comment] 2016-12-15 23:47
It seems to be isolated to the android driver then; I've had it sitting with an ios session open for an hour and no memory issues that I can see.

**Comment by jlipps** [comment] 2016-12-15 23:49
Anyway, I'll add it to our backlog to try and repro and see if we can track anything down.

**Comment by estellemasso** [comment] 2016-12-16 00:03
I am consistently seeing this issue on iOS though.

**Comment by estellemasso** [comment] 2016-12-16 00:03
It is not Android specific.

**Comment by jlipps** [comment] 2016-12-16 00:10
Then there must be something else going on as it is not universally reproducible. I've had a session sitting open for over an hour now with no problem. We'll ask more questions when we dig in to see what that could be.

**Comment by xinufo** [comment] 2016-12-16 01:26
@jlipps 
I used mac, and the result is same as Windows, but more slowly. Maybe you could try using the apk here to reproduce it.
apk: https://github.com/xinufo/AppiumMemoryLeakTest/raw/master/src/main/java/aut.apk
log appium 1.6.3: https://github.com/xinufo/AppiumMemoryLeakTest/blob/master/logs/appium%201.6.3.txt

**Comment by HasaanAli** [comment] 2017-02-10 15:03
@jlipps

**Comment by HasaanAli** [comment] 2017-02-10 15:27
@jlipps i restarted my mac and now 8GB is free. But I believe it will fill again when i'll run tests.

**Comment by imurchie** [comment] 2017-02-10 15:28
@HasaanAli That is a different issue altogether. But it is resolved by using the `preventWDAAttachments` desired capability.

**Comment by HasaanAli** [comment] 2017-02-11 05:18
Woo. Thanks a lot imurchie. Also I deleted the 35GB Test folder in the User/hasaan/Library/Developer/Xcode/DerivedData/WebDriverAgent-abced.../Logs/Test. 
Mentioned full path here for other people

Will now try the capability mentioned above.

**Closed** 2017-07-20 20:16 UTC
Labels: Bug
