### ISSUE TITLE
"getAlertText" was executed while no alert was displayed in the WebView context, resulting in the error "no such alert."

### ISSUE THREAD

**Issue by fatahillahardhi** [appium/appium#20557] opened 2024-09-10 18:40 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

I’m encountering an issue with Appium when it executes the `getAlertText` command even though no alert is shown. Sometimes, Appium gets stuck and fails to proceed with the steps. When I set `webviewAtomWaitTimeout` to 5, 10, 15, 30 or 60 seconds, I get the error `Did not get any response for atom execution` However, if the getAlertText command finishes before the timeout (but still the Appium will stuck or not doing anything), it runs smoothly, but more often, it results in a timeout.

I’ve tried setting the capability `setAutoAcceptAlerts` to false and managing the alerts manually. I used `driver.switchTo().alert().accept` or `iosDriver.executeScript("mobile: alert", args)`, but I frequently receive the error no such alert.

If I get the error `Did not get any response for atom execution`, the pipeline will show an error like this:
```
Sep 11, 2024 12:52:36 AM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '408' -> incorrect JSON status mapping for 'timeout' (500 expected)
```

### Expected Behavior

'getAlertText' was not executed and did not cause Appium to get stuck or result in the error `Did not get any response for atom execution`, nor did it trigger the error `INFO: HTTP Status: '408' -> incorrect JSON status mapping for 'timeout' (500 expected)`

### Minimal Reproducible Example

use webview/hybrid app

### Environment

- Operating system: macos sonoma 14.1.1
- Appium server version (output of `appium --version`): 2.11.3
- Appium driver(s) and their version(s) (`appium driver list`): XCUITest 7.24.9
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`): 18.7.1
- `npm` version (output of `npm --version`): 9.8.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iOS Simulator and iPhone
- Real device or emulator/simulator: both

### Further Information

- https://gist.github.com/fatahillahardhi/2f416075997c175fc9664f17e469905c
- issue with `Did not get any response for atom execution` https://gist.github.com/fatahillahardhi/ded2862c4c5a75802bc161ef7debb967

**Comment by mykola-mokhnach** [comment] 2024-09-10 20:22
The above behaviour is expected if no response is retrieved from webinspector within the timeout. Duplicate of https://github.com/appium/appium/issues/16222#issuecomment-988556235

**Comment by fatahillahardhi** [comment] 2024-09-11 02:11
@mykola-mokhnach Is there a way to avoid waiting for the atom to complete so it can directly execute the element without the need for an alert check? From what I observe, the elements have already appeared, but the atom keeps waiting (I’m not sure what it’s waiting for). This causes Appium to be slower than usual, and sometimes the error `Did not get any response for atom execution` frequently appears due to a timeout, even though I can see that the elements have already appeared on the device.

**Comment by mykola-mokhnach** [comment] 2024-09-11 05:15
>  Is there a way to avoid waiting for the atom to complete so it can directly execute the element without the need for an alert check?

Unfortunately I don't know any. Feel free to propose a patch if you have a proper workaround in mind.

**Comment by mykola-mokhnach** [comment] 2024-09-13 11:54
Closed as third party issue

**Closed by mykola-mokhnach** 2024-09-13 11:54 UTC
Labels: Mobile Safari, ThirdParty
