### ISSUE TITLE
Not able to run tests after upgrading to Xcode 11

### ISSUE THREAD

**Issue by Madhavip3** [appium/appium#13407] opened 2019-10-10 23:45 UTC
## The problem

Not able to run any tests after upgrading to xcode 11. Tried installing the latest desktop version. The app installs but crashes on launch. Also tried the same with the appium beta version from command line and still see the same issue. 

## Environment: Mac

* Appium version (or git revision) that exhibits the issue:1.15.0
* Last Appium version that did not exhibit the issue (if applicable):1.14
* Desktop OS/version used to run Appium:Mac OS Mohave 10.14.4
* Node.js version (unless using Appium.app|exe):12.10.0
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test:IOS 13
* Real device or emulator/simulator:Simulator
* Appium CLI or Appium.app|exe:Appium.app

## Link to Appium logs

https://gist.github.com/Madhavip3/2476814334fc9daf773b41f3f9cfdea6

**Comment by KazuCocoa** [comment] 2019-10-11 02:39
> [info] [35m[WD Proxy][39m Got an unexpected response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.adobe.gemini.dev' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350\n\t1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff23b987a9 -[NSException raise] + 9\n\t3   WebDriverAgentLib                   0x0000000106a04aa8 -[FBSession activeApplication] + 728\n\t4   WebDriverAgentLib                   0x0000000106a10707 +[FBSessionCommands currentCapabilities] + 87\n\t5   WebDriverAgentLib                   0x0000000106a105d9 +[FBSessionCommands sessionInformation] + 233\n\t6   WebDriverAgentLib                   0x0000000106a0dbfe +[FBSessionCommands handleCreateSession:] + 2958\n\t7   WebDriverAgentLib                   0x00000001069e3d56 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t8   WebDriverAgentLib                   0...

What about adding `showIOSLog`? Maybe the log has a hint about the crash if your app.
(Or if you have bug reporting system like crashlytics, it will also help you.)

**Comment by sadase** [comment] 2019-10-11 04:14
Have you set the Command Line Tools to the Xcode you are using? 
(Xcode > Preferences > Locations > Command Line Tools)

**Comment by KazuCocoa** [comment] 2019-10-11 04:30
I use the default version.
e.g. Xcode 11.1 => 11.1 (11A1027)

**Comment by Madhavip3** [comment] 2019-10-11 17:24
@sadase Yes the command line tools are set . I also installed the command  line tools from apple developer website and still see the same issue. The app just launches and freezes. This also messes the simulator and I have to reset the simulator to run the app from xcode.

**Comment by Madhavip3** [comment] 2019-10-11 17:26
@KazuCocoa https://gist.github.com/Madhavip3/d95bded166f5398cc0b4de1f4861f39d - Logs with xcode.

**Comment by KazuCocoa** [comment] 2019-10-12 08:55
Thanks.
mm... it looks WDA could not responde by XCTest framework...

```
[debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.adobe.gemini.dev","arguments":["-AppleLanguages","(en)","-NSLanguages","(en)"],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[error] [35m[Xcode][39m     t =  1181.59s Open com.adobe.gemini.dev
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m     t =  1181.59s     Launch com.adobe.gemini.dev
[error] [35m[Xcode][39m [error] [35m[Xcode][39m 2019-10-11 09:56:54.534768-0700 WebDriverAgentRunner-Runner[64643:593643] Enqueue Failure: Failed to launch com.adobe.gemini.dev: Timed out attempting to launch app. /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 38 1
[error] [35m[Xcode][39m [error] [35m[Xcode][39m 2019-10-11 09:57:54.538836-0700 WebDriverAgentRunner-Runner[64643:593643] Enqueue Failure: activate application '<XCUIApplicationImpl: 0x6000031d2340 com.adobe.gemini.dev>' (current state: Not Running) /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 38 1
[error] [35m[Xcode][39m     t =  1271.60s         Setting up automation session
[error] [35m[Xcode][39m     t =  1271.60s         Wait for com.adobe.gemini.dev to idle
[error] [35m[Xcode][39m [error] [35m[Xcode][39m 2019-10-11 09:58:00.581991-0700 WebDriverAgentRunner-Runner[64643:593643] The application 'com.adobe.gemini.dev' is not running in foreground after 5.00 seconds
[error] [35m[Xcode][39m 
[info] [35m[WD Proxy][39m Got an unexpected response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.adobe.gemini.dev' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350\n\t1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff23b987a9 -[NSException raise] + 9\n\t3   WebDriverAgentLib                   0x000000010a51caa8 -[FBSession activeApplication] + 728\n\t4   WebDriverAgentLib                   0x000000010a528707 +[FBSessionCommands currentCapabilities] + 87\n\t5   WebDriverAgentLib                   0x000000010a5285d9 +[FBSessionCommands sessionInformation] + 233\n\t6   WebDriverAgentLib                   0x000000010a525bfe +[FBSessionCommands handleCreateSession:] + 2958\n\t7   WebDriverAgentLib                   0x000000010a4fbd56 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t8   WebDriverAgentLib                   0...
[debug] [35m[W3C][39m Matched W3C error code 'invalid element state' to InvalidElementStateError
```

Can you launch the app with Xcode 10 x Appium 1.15.0? (x iOS 12 since Xcode 10 cannot handle iOS 13)


We simply wait 5 sec https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/FBApplication.m#L30
You can increate number and try it out on your environment to verify it can fix with increasing the timeout.

**Comment by Madhavip3** [comment] 2019-10-14 22:02
@KazuCocoa That works fine for us. The issue is only with Xcode 11. Tried uninstalling and re-installing all the packages and still see the issue.Also increased the timer still see the same issue.

**Comment by GRyabkin** [comment] 2019-10-15 00:01
@KazuCocoa  I have the same problem. I build the app using `fastlane`

```
lane :simulator_app do
    run_tests(scheme: "AppName",
      derived_data_path: "./artifacts",
      build_for_testing: true
    )
  end
```
Environment: Xcode 11.1, Catalina, iOS 13.1 iPhone 11 Pro simulator, appium 1.15, latest fatlane


I see labels that the issue isn't a bug, could you give details why it stopped working after Xcode update?

**Comment by KazuCocoa** [comment] 2019-10-15 01:04
Will `waitForQuiescence` help?
https://github.com/appium/appium-xcuitest-driver

**Comment by Madhavip3** [comment] 2019-10-15 23:01
@KazuCocoa Still seeing the same issue. Is there anything else we are missing here.Right now this is blocking our tests development.

**Comment by KazuCocoa** [comment] 2019-10-16 08:52
Perhaps, WDA cannot get `processIdentifier` by `XCAccessibilityElement`(XCTest framework).
https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIApplication%2BFBHelpers.m#L39-L49

btw, how about providing `bundleId` instead of `app`?
I mean try to set `com.apple.Maps`, for example, as bundleId in your capability instead of your test `app`, and create a new session if the map app launches.

**Comment by Madhavip3** [comment] 2019-10-17 02:02
@KazuCocoa I tried with jus the bundleid and Still the same issue.The app launches and quits. This is done for about 5/6 times and the tests finally fails.

**Comment by GRyabkin** [comment] 2019-10-17 19:27
I experienced the same problem. My app was build using **fastlane**. I changed a lane for building app and now it runs ok.

```
  lane :simulator_project do
    xcodebuild(workspace: "ProjectName.xcworkspace",
      scheme: "ProjectName",
      configuration: "Debug",
      sdk: "iphonesimulator13.1",
      derivedDataPath: "./artifacts"
    )
  end
```

**Comment by KazuCocoa** [comment] 2019-10-18 04:04
Thanks, but something happens in your Xcode environment I haven't met. hm..
@Madhavip3

**Comment by hassanaziz19** [comment] 2019-10-23 09:37
@Madhavip3 I am facing with the same issue. It started after updating to xcode 11. The app closes during the test execution. Have you found the solution or a work around?

**Comment by mykola-mokhnach** [comment] 2019-10-24 06:21
Closed as third party issue

**Closed by mykola-mokhnach** 2019-10-24 06:21 UTC
Labels: NeedsInfo, ThirdParty

**Comment by michellebenedetti** [comment] 2019-11-12 12:51
I have the same problem. Follow the environment: Appium: 1.15.1, Xcode 11.0, Mobile Iphone 11. @KazuCocoa, Could you help me, please? Thanks.

**Comment by KazuCocoa** [comment] 2019-11-12 13:18
Cannot say anything if it was in xcodebuild/XCTet side or Appium can help it without the full log with `showIOSLog`, unfortunately.

**Comment by michellebenedetti** [comment] 2019-11-14 12:51
Hello @Madhavip3, did you solve the problem?

**Comment by mikalaikarol** [comment] 2019-11-14 15:07
Same problem as @michellebenedetti and @Madhavip3

**Comment by Madhavip3** [comment] 2019-11-14 17:40
@michellebenedetti I was able to run on devices but not in simulator yet. It works fine with an IOS12 simulator. Still figuring out a way to run on IOS13 simulator. It also happens to couple of my team members as well.

**Comment by michellebenedetti** [comment] 2019-11-14 18:04
@Madhavip3 thanks for answering, what capabilities did you use to use IOS12 device? Can you help me?

**Comment by adamec31** [comment] 2019-11-19 14:58
I get the same problem in my test with iOS 13.2 simulator

**Comment by Madhavip3** [comment] 2019-11-20 00:29
@KazuCocoa there are others seeing the same issue as well. And I still see it with IOS 13 simulators.Can you please help?

**Comment by KazuCocoa** [comment] 2019-11-20 00:43
How about coordinating the launch stuff with below capabilities?
- `waitForQuiescence` and `wdaEventloopIdleDelay` capabilities also could help
    - https://github.com/appium/appium-xcuitest-driver

**Comment by Madhavip3** [comment] 2019-11-20 00:44
@KazuCocoa that didn't seem to help for me.

**Comment by KazuCocoa** [comment] 2019-11-20 00:50
Another workaround is:

- `autoLaunch: false` in caps
- Calls http://appium.io/docs/en/commands/device/app/activate-app/ to launch the app after the create session

If the issue is still happening, I guess the root cause is XCTest internal. If so, only Apple can fix it.

You can also try to launch the app via vanilla XCUITest like https://gist.github.com/KazuCocoa/e90738298d8409bb0acbf44720a44f0b to ensure it also happens on XCUITest framework. (The active-app calls the same command though)

**Comment by sachin-a-s** [comment] 2019-11-20 11:50
Similar issue is observed with

Appium Desktop Version: 1.15.1
iOS - 13.2
Xcode 11

    t =  1579.77s Find the Application 'com.Facilisight.Ionic.App'
    t =  1579.77s     Requesting snapshot of accessibility hierarchy for app with pid 366
    t =  1715.11s Open com.Facilisight.Ionic.App
    t =  1715.12s     Launch com.Facilisight.Ionic.App
    t =  1715.12s         Terminate com.Facilisight.Ionic.App:366
    t =  1717.00s         Setting up automation session
    t =  1717.03s         Wait for com.Facilisight.Ionic.App to idle
2019-11-20 17:03:30.411485+0530 WebDriverAgentRunner-Runner[359:21288] Cannot request the screen point at NSPoint: {64, 64}: Error Domain=XCTDaemonErrorDomain Code=11 "No AXElement found at {64 64}: kAXErrorInvalidUIElement" UserInfo={NSLocalizedDescription=No AXElement found at {64 64}: kAXErrorInvalidUIElement}
2019-11-20 17:03:30.596015+0530 WebDriverAgentRunner-Runner[359:21288] Cannot request the screen point at NSPoint: {64, 64}: Error Domain=XCTDaemonErrorDomain Code=11 "No AXElement found at {64 64}: kAXErrorInvalidUIElement" UserInfo={NSLocalizedDescription=No AXElement found at {64 64}: kAXErrorInvalidUIElement}
2019-11-20 17:03:30.758241+0530 WebDriverAgentRunner-Runner[359:21961] Cannot request the screen point at NSPoint: {64, 64}: Error Domain=XCTDaemonErrorDomain Code=11 "No AXElement found at {64 64}: kAXErrorInvalidUIElement" UserInfo={NSLocalizedDescription=No AXElement found at {64 64}: kAXErrorInvalidUIElement}
 2019-11-20 17:03:34.826694+0530 WebDriverAgentRunner-Runner[359:17138] The application 'com.Facilisight.Ionic.App' is not running in foreground after 5.00 seconds

**Comment by Lei-Zhang888** [comment] 2020-03-18 07:18
Hey, any solution here? I met the same issue

**Comment by mennatallah** [comment] 2020-04-09 17:53
i have same issue to run the XCUItest as the permission request to open the app on the semulation then the build falied

**Comment by pranav21keshav** [comment] 2020-04-25 14:52
Did anyone find the solution for this problem.  I am also facing the same problem. The application launches and just freezes there?

**Comment by goa** [comment] 2020-05-21 10:43
Same here.

**Comment by nazarsh** [comment] 2021-02-02 13:25
I know this is rather old, but in case somebody bumps into this, try: https://github.com/google/ios-webkit-debug-proxy for debugging, which will lead you to making sure your phone's Safari's settings are covered:
```
Settings > Safari > Advanced > Web Inspector = ON
```
That same settings page includes a "Remote Automation" option 
https://webkit.org/blog/9395/webdriver-is-coming-to-safari-in-ios-13/

**Comment by kajali09** [comment] 2022-03-15 11:56
Hey, Did any one found the solution. 
I have started facing this issue after 
upgraded my device to 15.3.1
Appium to V1.22.2
Xcode Version 13.2.1

**Comment by Mr-Ples** [comment] 2022-10-06 14:00
Was able to solve this with the `waitForQuiescence=True` default capability + removing the `waitForIdleTimeout` capability (or giving it a very long timeout) + `autoLaunch=False`
