### ISSUE TITLE
Can't inspect element and can't operate on screen that contains DateTimePicker

### ISSUE THREAD

**Issue by VTDuyen1** [appium/appium#13853] opened 2020-01-20 08:03 UTC
## The problem

I could not inspect the element and could not perform any operations on the screen that contained DateTimePicker.

## Environment

* Appium version : 1.15.1
* Desktop OS/version used to run Appium: 1.15.1
* Node.js version (unless using Appium.app|exe): v12.1.0
* Mobile platform/version under test: 12.4.4
* Real device or emulator/simulator: Real device (iPhone 6+)
* Appium CLI or Appium.app|exe: CLI and Appium.app

## Link to Appium logs
Cannot click on the "Set" button in DateTimePicker:
https://gist.github.com/VTDuyen1/8764dc17d844cefd54df631b52616a40

When I use the appium desktop I get a log:
https://gist.github.com/VTDuyen1/020cd41b81f8e7d572796198624238ff

## Code To Reproduce Issue [ Good To Have ]

it("Choose date: f3", function () {
	return driver
		.elementByAccessibilityId('Set')
		.tap();
})

![DateTimePicker1](https://user-images.githubusercontent.com/34959487/72708677-d781df00-3b95-11ea-878a-a6e8edce8c6e.jpg)
![DateTimePicker2](https://user-images.githubusercontent.com/34959487/72708678-d781df00-3b95-11ea-9e98-06f5a28eb52e.jpg)

**Comment by mykola-mokhnach** [comment] 2020-01-20 09:37
> [Xcode] 2019-07-15 09:57:09.731547+0700 WebDriverAgentRunner-Runner
> [327:13647] Getting the snapshot timed out after 15 seconds 
> [Xcode] 2019-07-15 09:57:09.731793+0700 WebDriverAgentRunner-Runner
> [327:13647] Internal error: Error Domain=com.apple.dt.xctest.automation-support.error Code=8 "Error getting main window kAXErrorCannotComplete" UserInfo={NSLocalizedDescription=Error getting main window kAXErrorCannotComplete} 

This is the cause of the issue. Unfortunately the problem happens on the XCTest side, so there is nothing much we can do there from Appium. You could also try appium@beta, which contains some workarounds, which might be helpful there.

**Comment by VTDuyen1** [comment] 2020-01-20 09:52
Thanks @mykola-mokhnach , I will try appium@beta now.

**Comment by VTDuyen1** [comment] 2020-01-21 02:48
Hi @mykola-mokhnach, I used appium@beta but the results have not changed. Do you have any suggestions?

**Comment by mykola-mokhnach** [comment] 2020-01-21 05:48
Describe the problem to Apple?

**Comment by mykola-mokhnach** [comment] 2020-01-21 05:53
I would also try to play with `activeAppDetectionPoint` and `includeNonModalElements` settings. Perhaps, this could help

**Comment by VTDuyen1** [comment] 2020-01-21 06:48
Yes, I hope good news from you.

**Comment by mykola-mokhnach** [comment] 2020-01-24 12:24
Closed as third party issue

**Closed by mykola-mokhnach** 2020-01-24 12:24 UTC
Labels: NeedsInfo, ThirdParty, XCUITest
