### ISSUE TITLE
how to get package name and launcher activity name

### ISSUE THREAD

**Issue by tarunHub** [appium/appium#4609] opened 2015-02-26 09:20 UTC
How to get the package name and launcher activity name for native app as the same is required to be passed in desired capabilities.

**Comment by prattpratt** [comment] 2015-02-26 10:09
try this http://stackoverflow.com/questions/6289149/resolving-the-package-name-of-android-apk

**Comment by tarunHub** [comment] 2015-02-26 12:00
@prattpratt can u help me with the windows...
we need to pass activity name as well.. how can we get the app activity name

**Comment by amedvedjev** [comment] 2015-02-26 18:42
easiest solution - 
1) download Appium GUI (for mac or windows)
2) press on android settings
3) set in "App Path" path to apk
4) now in list "Package" see your apk package name
5) in "Launch Activity" - first is 99% your first activity to start with. you can set it and try to start inspector by starting first Appium with Launch button and then hitting inspector Button. If it is not correct - then in logs will be said what activity is active instead you set in "Launch Activity"

**Comment by tarunHub** [comment] 2015-03-02 06:59
@amedvedjev 
1 I have set the "app path" to apk in  android settings
result:  I cannot see the apk package name in list "package" and launch activity name in list "launch activity"

**Comment by amedvedjev** [comment] 2015-03-02 08:32
example on Appium Mac GUI - http://screencast.com/t/GaPcBeeuIVd

**Comment by tarunHub** [comment] 2015-03-02 09:41
example on appium windows GUI
![image](https://cloud.githubusercontent.com/assets/10140395/6438375/6589b656-c0ee-11e4-83bb-32470278277d.png)

**Comment by tarunHub** [comment] 2015-03-02 10:00
Example on appium window GUI
![git](https://cloud.githubusercontent.com/assets/10140395/6438614/ee312e7e-c0f0-11e4-8acd-b2118a1619ef.png)

**Comment by dqthebt** [comment] 2015-04-17 01:44
You can type command: aapt list -a <path of .apk file> > <path of out put file(.txt file)> 
Then, you open output file by notepad and search "android manifest" and read informations of apk file.
ex:  appt list -a "D:\ApkFiles\racing.apk" > "D:\output.txt"
Then you open file output.txt and search "android manifest" and read.

**Comment by moizjv** [comment] 2015-05-05 21:50
@dqthebt @amedvedjev @prattpratt thanks! @tarunHub appium will figure out if you dont pass in those two capabilities from your androidmanifest.xml . Can you use [forum](http://discuss.appium.io) for asking questions. Closing it as it is not a bug.

**Closed by moizjv** 2015-05-05 21:50 UTC
Labels: NeedsTriage

**Comment by mayankgupta804** [comment] 2017-04-27 09:44
another way to find the package name and the launchable activity: 
1. Go to the terminal.
2.Then type ` aapt dump badging <Absolute/Relative path to the SDK> | grep package:\ name  ` to get the package name.
3. To get the launchable activity name, type ` appt dump badging <Absolute/Relative path to SDK> | grep launchable-activity:\ name `

**Comment by sachitanandkumar** [comment] 2018-05-13 13:43
@mayankgupta804 - aapt & appt is not internal/external command showing

**Comment by sachitanandkumar** [comment] 2018-05-13 13:44
m not sure about this- As per new appium version- app package/app activity not require to add in script
