### ISSUE TITLE
Accessibility ids are not showing in inspector ( Appium 1.7.2 Beta, Xcode 9 ) 

### ISSUE THREAD

**Issue by rakeshsukla53** [appium/appium#9519] opened 2017-10-24 18:17 UTC
## The problem

I updated `appium to 1.7.2 beta` and `Xcode to 9.2`, and noticed all the accessibility ids are not showing in inspector anymore. These accessibility ids used to get automatically created when I was using Xcode 8.3 and Appium 1.6.6. 

If you see the image below, all the elements have `AX error -25205` as their id now. I am not sure why this is happening ?

<img width="1409" alt="screen shot 2017-10-24 at 2 09 22 pm" src="https://user-images.githubusercontent.com/9192661/31960205-04a8e04c-b8c5-11e7-9eeb-d9f72a13dbf6.png">

## Environment

* Appium version  - `1.7.2 Beta`
* Last Appium version that did not exhibit the issue (if applicable): `1.6.6`
* Desktop OS/version used to run Appium: `MacOS Sierra , Version 10.12.6` 
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: `iOS` 
* Real device or emulator/simulator: `Simulator `
* Appium CLI or Appium.app|exe: `Appium CLI`

**Comment by mykola-mokhnach** [comment] 2017-10-24 18:18
Closed as duplicate of https://github.com/facebook/WebDriverAgent/issues/703

**Closed by mykola-mokhnach** 2017-10-24 18:18 UTC
