### ISSUE TITLE
Appium taking 10-15 minutes in switching to webview context and getting current url 

### ISSUE THREAD

**Issue by areeb-malik-1** [appium/appium#20211] opened 2024-06-07 05:13 UTC
In my app there are multiple webviews and single native view
Below is the code snippet that I am using to switch from native to webview, which is taking 10-15 mins to execute and ultimately gets failed due to exception:

<img width="812" alt="Screenshot 2024-06-07 at 10 39 01 AM" src="https://github.com/appium/appium/assets/102204001/be73d440-9b05-4c0f-9b90-e5c1e87a9aa4">

And logs on extent report
<img width="734" alt="Screenshot 2024-06-07 at 10 43 25 AM" src="https://github.com/appium/appium/assets/102204001/084e815f-b24a-4a12-b007-cab8b7214aed">

**Comment by KazuCocoa** [comment] 2024-06-07 05:17
Please attach the full appium log as well by following bug template. 
https://github.com/appium/appium/issues/new?assignees=&labels=Bug%2CNeeds+Triage&projects=&template=bug_report.yml&title=bug%3A+%3Ctitle%3E

Possibly this is WebInspector/mobile safari related slowness.

**Comment by areeb-malik-1** [comment] 2024-06-07 05:28
@KazuCocoa I hope below logs will help
```
[Xcode]     t = 369176.23s Get all elements bound by index for: Elements matching predicate 'elementType IN {7, 5, 46}'
[Xcode] 
[Xcode]     t = 369176.23s     Requesting snapshot of accessibility hierarchy for app with pid 5042
[Xcode] 
[RemoteDebugger] Current applications available:
[RemoteDebugger]     Application: "PID:5162"
[RemoteDebugger]         id: "PID:5162"
[RemoteDebugger]         isProxy: false
[RemoteDebugger]         name: "amsengagementd"
[RemoteDebugger]         bundleId: "com.apple.amsengagementd"
[RemoteDebugger]         hostId: undefined
[RemoteDebugger]         isActive: false
[RemoteDebugger]         isAutomationEnabled: "Unknown"
[RemoteDebugger]     Application: "PID:10533"
[RemoteDebugger]         id: "PID:10533"
[RemoteDebugger]         isProxy: false
[RemoteDebugger]         name: "reversetemplated"
[RemoteDebugger]         bundleId: "process-reversetemplated"
[RemoteDebugger]         hostId: undefined
[RemoteDebugger]         isActive: false
[RemoteDebugger]         isAutomationEnabled: "Unknown"
[RemoteDebugger]     Application: "PID:10513"
[RemoteDebugger]         id: "PID:10513"
[RemoteDebugger]         isProxy: true
[RemoteDebugger]         name: "Safari"
[RemoteDebugger]         bundleId: "com.apple.SafariViewService"
[RemoteDebugger]         hostId: undefined
[RemoteDebugger]         isActive: false
[RemoteDebugger]         isAutomationEnabled: "Unknown"
[RemoteDebugger]     Application: "PID:35899"
[RemoteDebugger]         id: "PID:35899"
[RemoteDebugger]         isProxy: false
[RemoteDebugger]         name: "com.apple.WebKit.WebContent"
[RemoteDebugger]         bundleId: "process-com.apple.WebKit.WebContent"
[RemoteDebugger]         hostId: undefined
[RemoteDebugger]         isActive: false
[RemoteDebugger]         isAutomationEnabled: "Unknown"
[RemoteDebugger] Checking for bundle identifiers: com.apple.WebKit.WebContent, process-com.apple.WebKit.WebContent, process-SafariViewService, com.apple.SafariViewService, *, com.mobile.ios.Example.dev
[RemoteDebugger] Found app id key 'PID:35899' for bundle 'com.apple.WebKit.WebContent'
[RemoteDebugger] Found app id key 'PID:35899' for bundle 'process-com.apple.WebKit.WebContent'
[RemoteDebugger] Found app id key 'PID:35899' for bundle 'process-SafariViewService'
[RemoteDebugger] Found app id key 'PID:10513' for bundle 'com.apple.SafariViewService'
[RemoteDebugger] Found app id key 'PID:35899' for bundle '*'
[RemoteDebugger] Found app id key 'PID:35899' for bundle 'com.mobile.ios.Example.dev'
[RemoteDebugger] Trying out the possible app ids: PID:35899, PID:10513 (try #1 of 20)
[RemoteDebugger] Skipping app 'PID:35899' because it is not active
[RemoteDebugger] Skipping app 'PID:10513' because it is not active
[Xcode]     t = 369176.27s     Find: Descendants matching type Any
[Xcode] 
[Xcode]     t = 369176.27s     Find: Elements matching predicate 'elementType IN {7, 5, 46}'
[Xcode] 
[RemoteDebugger] Current applications available:
[RemoteDebugger]     Application: "PID:5162"
[RemoteDebugger]         id: "PID:5162"
[RemoteDebugger]         isProxy: false
[RemoteDebugger]         name: "amsengagementd"
[RemoteDebugger]         bundleId: "com.apple.amsengagementd"
[RemoteDebugger]         hostId: undefined
[RemoteDebugger]         isActive: false
[RemoteDebugger]         isAutomationEnabled: "Unknown"
[RemoteDebugger]     Application: "PID:10533"
[RemoteDebugger]         id: "PID:10533"
[RemoteDebugger]         isProxy: false
[RemoteDebugger]         name: "reversetemplated"
[RemoteDebugger]         bundleId: "process-reversetemplated"
[RemoteDebugger]         hostId: undefined
[RemoteDebugger]         isActive: false
[RemoteDebugger]         isAutomationEnabled: "Unknown"
[RemoteDebugger]     Application: "PID:10513"
[RemoteDebugger]         id: "PID:10513"
[RemoteDebugger]         isProxy: true
[RemoteDebugger]         name: "Safari"
[RemoteDebugger]         bundleId: "com.apple.SafariViewService"
[RemoteDebugger]         hostId: undefined
[RemoteDebugger]         isActive: false
[RemoteDebugger]         isAutomationEnabled: "Unknown"
[RemoteDebugger]     Application: "PID:35899"
[RemoteDebugger]         id: "PID:35899"
[RemoteDebugger]         isProxy: false
[RemoteDebugger]         name: "com.apple.WebKit.WebContent"
[RemoteDebugger]         bundleId: "process-com.apple.WebKit.WebContent"
[RemoteDebugger]         hostId: undefined
[RemoteDebugger]         isActive: false
[RemoteDebugger]         isAutomationEnabled: "Unknown"
[RemoteDebugger] Checking for bundle identifiers: com.apple.WebKit.WebContent, process-com.apple.WebKit.WebContent, process-SafariViewService, com.apple.SafariViewService, *, com.mobile.ios.Example.dev
[RemoteDebugger] Found app id key 'PID:35899' for bundle 'com.apple.WebKit.WebContent'
[RemoteDebugger] Found app id key 'PID:35899' for bundle 'process-com.apple.WebKit.WebContent'
[RemoteDebugger] Found app id key 'PID:35899' for bundle 'process-SafariViewService'
[RemoteDebugger] Found app id key 'PID:10513' for bundle 'com.apple.SafariViewService'
[RemoteDebugger] Found app id key 'PID:35899' for bundle '*'
[RemoteDebugger] Found app id key 'PID:35899' for bundle 'com.mobile.ios.Example.dev'
[RemoteDebugger] Trying out the possible app ids: PID:35899, PID:10513 (try #1 of 20)
[RemoteDebugger] Skipping app 'PID:35899' because it is not active
[RemoteDebugger] Skipping app 'PID:10513' because it is not active
[RemoteDebugger] Could not connect to a valid app after 20 tries.
[XCUITestDriver@8c74 (248285e5)] No available web pages: Could not connect to a valid app after 20 tries.
[XCUITestDriver@8c74 (248285e5)] No web frames found.
[XCUITestDriver@8c74 (248285e5)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
```

**Comment by KazuCocoa** [comment] 2024-06-07 05:37
Could you share the full log as GIST?

**Comment by areeb-malik-1** [comment] 2024-06-07 09:42
Hi @KazuCocoa this is the GIST link for logs:
https://gist.github.com/areeb-malik-1/8b7731ea0a929f0be5a9eedeb3b017fb

**Comment by KazuCocoa** [comment] 2024-06-08 00:44
Perhaps what you addressed was Appium XCUITest driver was not able to attach to the app via WebInspector protocol. Around: https://github.com/appium/appium-remote-debugger/blob/393d0bcff9ef26b5c930ff5f0bc1ce6f16e6399d/lib/rpc/rpc-client.js#L650-L654
So, a getting contexts endpoint took a long time.

The behavior could depend on the device/mobile safari side. Then, unfortunately we could not help to improve the behavior for now.

Is it a specific page or a kind of random page?

**Comment by areeb-malik-1** [comment] 2024-06-09 13:11
Okay @KazuCocoa, yes this is happening on a specific page.

**Comment by KazuCocoa** [comment] 2024-06-10 15:42
What happens when you open the WebView page with desktop Safari's Web Inspector? Perhaps the Desktop Safari's WebInspector also does the same/similar thing to attach to the page.

**Comment by areeb-malik-1** [comment] 2024-06-11 18:16
I'll check and let you know soon.

**Comment by areeb-malik-1** [comment] 2024-06-13 07:43
Sorry for delayed response @KazuCocoa 
Safari's Web Inspector is connecting fine with webview without delay.

**Comment by KazuCocoa** [comment] 2024-06-13 08:28
Then, the next would be which part is taking long time
e.g.
if it was a comment to webinspector like https://github.com/appium/appium-remote-debugger/blob/393d0bcff9ef26b5c930ff5f0bc1ce6f16e6399d/lib/rpc/rpc-client.js#L650-L654 , perhaps appium can do nothing, but it is Appium related, we could improve something.

Ideally debug with appium code, but `appium:safariLogAllCommunication` may print some communication info, which will help some kind of investigation. `--log-timestamp` appium argument would help to log timestamp and find which part is slow.

**Comment by mykola-mokhnach** [comment] 2024-07-01 05:56
Closed as third party issue

**Closed by mykola-mokhnach** 2024-07-01 05:56 UTC
Labels: Mobile Safari, ThirdParty

**Comment by caseycling** [comment] 2025-06-03 19:04
Hey team, I'm also experiencing this issue.

@mykola-mokhnach what third party issue was this determined to be? Do you have any solutions you could share?

@areeb-malik-1 were you able to resolve this?

**Comment by caseycling** [comment] 2025-06-09 18:55
Can anyone provide insight as to the resolution for this issue? I see it was deemed to be a third-party issue. What ended up being the cause?
