### ISSUE TITLE
Stopping video recording take huge time

### ISSUE THREAD

**Issue by SrinivasanTarget** [appium/appium#11516] opened 2018-10-11 18:23 UTC
## The problem

Server takes huge time to stop video recording and proceed with next steps. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.2-beta 1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: ios & android
* Real device or emulator/simulator: both 
* Appium CLI or Appium.app|exe:

## Details

https://gist.github.com/SrinivasanTarget/5e420f0bbe01f2d9c5bb19183ca47c37

**Comment by mykola-mokhnach** [comment] 2018-10-11 18:33
I don't observe any issues in the attached log. The calls to start/stop the video took 798/669 ms each

**Comment by saikrishna321** [comment] 2018-10-11 22:47
@mykola-mokhnach https://vimeo.com/294677928 after the video is stopped u will notice in the video that it takes a long time to jump to next step

**Comment by mykola-mokhnach** [comment] 2018-10-12 09:14
I tried to reproduce the problem locally and was not able to do it. Make sure you use the recent beta build

**Comment by saikrishna321** [comment] 2018-10-12 16:35
@mykola-mokhnach no luck its still the same as u see in the video

**Comment by mykola-mokhnach** [comment] 2018-10-12 16:36
no idea. Try another computer

**Comment by saikrishna321** [comment] 2018-10-17 11:19
@mykola-mokhnach nope its the same

**Comment by mykola-mokhnach** [comment] 2018-10-22 17:08
https://github.com/appium/WebDriverAgent/pull/123/files might be related to this problem

**Comment by mykola-mokhnach** [comment] 2018-11-08 08:16
To me this looks like some problem with the local environment, because we were not able to reproduce the issue. I close it unless we get more similar reports from other users

**Closed by mykola-mokhnach** 2018-11-08 08:16 UTC
Labels: XCUITest

**Comment by saikrishna321** [comment] 2018-11-08 09:07
@mykola-mokhnach yes, this is a local environment issue. I tried on different mac pro and it works fine without any issues.
