### ISSUE TITLE
Managing drivers in Appium 2.0 without Extension CLI

### ISSUE THREAD

**Issue by pauliusguzas** [appium/appium#18808] opened 2023-06-26 14:20 UTC
Hello,

In Appium 1 I could add all needed packages to package.json like this
```
    "dependencies": {
        "@wdio/appium-service": "7.19.5",
        "@wdio/cli": "7.19.5",
        "@wdio/local-runner": "7.19.5",
        "@wdio/mocha-framework": "7.19.5",
        "@wdio/spec-reporter": "7.19.5",
        "appium": "1.22.3",
    },
```
then do `yarn` or `npm i` or whahever and that would install all packages

Now is there a way for me to do this in Appium 2 without using Extension CLI. I just want to add packages to package.json, do `yarn `and that's it

```
    "dependencies": {
        "@wdio/appium-service": "7.19.5",
        "@wdio/cli": "7.19.5",
        "@wdio/local-runner": "7.19.5",
        "@wdio/mocha-framework": "7.19.5",
        "@wdio/spec-reporter": "7.19.5",
        "appium": "2.0.0-rc.3",
        "appium-xcuitest-driver": "4.32.9",
    },
```
Tried adding above packages to package.json and after installing them, cli says that there is no xcuitest driver installed and that I need it to install with `appium driver install`

Thanks in advance

**Comment by mykola-mokhnach** [comment] 2023-06-26 14:46
Possible duplicate of https://github.com/appium/appium/issues/18135

We do not provide other interfaces except of the command line one to manage installed drivers/plugins.

**Comment by Higgens75** [comment] 2023-06-26 14:49
Maybe adding scripts to package.json which install the drivers afterwards

"scripts": {
"postinstall": " npx appium driver install xcuitest"
},

**Comment by pauliusguzas** [comment] 2023-06-27 06:40
https://appium.io/docs/en/2.0/guides/managing-exts/ actually docs write about this and what I said in the ticket that doesn't work in reality does work with fresh node project, so probably some issue with my local project

**Comment by jlipps** [comment] 2023-06-27 20:18
OK, if this works in a fresh node project then I'm going to close as not reproducible. Feel free to drop a comment if you figure out what the cause was in your other project.

**Closed by jlipps** 2023-06-27 20:18 UTC
Labels: Needs Triage

**Comment by pauliusguzas** [comment] 2023-09-20 19:16
@jlipps the cause was that packages were added in monorepo, https://github.com/flexn-io/graybox/tree/main/packages/graybox#adding-graybox-to-your-project step 6 has the solution for this issue
