### ISSUE TITLE
bug: iOS specific popups are not detected by appium

### ISSUE THREAD

**Issue by revathikanakachalam** [appium/appium#20383] opened 2024-07-16 10:13 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

iOS popups not detected by appium.
I am new to iOS automation. I am automation Native app, while launching our app, a iOS popup asking for permission to allow Notifications is asked. This popup is not detected by appium, I am unable to click on the elements in the popup. I checked in Appium inspector app and in the xml, this popup is not available. Appreciate any help. Below is the popup
![image](https://github.com/user-attachments/assets/c327798b-5fbf-4f07-8b2c-c49d6656dc55)

### Expected Behavior

iOS popup should be detected by appium and should be able to interact with elements

### Minimal Reproducible Example

This issue is occurs for all iOS specific popup, checked with Photos app in iOS

### Environment

Operating system: MacBook Pro
Appium server version (output of appium --version): 2.11.2
Appium driver(s) and their version(s) (appium driver list):
**$appium driver list
✔ Listing available drivers
- uiautomator2@3.7.1 [installed (npm)]
- chromium@1.3.27 [installed (npm)]
- xcuitest@7.24.0 [installed (npm)]
- espresso [not installed]
- mac2 [not installed]
- windows [not installed]
- safari [not installed]
- gecko [not installed]
Appium plugin(s) and their version(s) (appium plugin list):
✔ Listing available plugins
- images [not installed]
- execute-driver [not installed]
- relaxed-caps [not installed]
- universal-xml [not installed]
Node.js version (output of node --version): v22.2.0
npm version (output of npm --version): 10.7.0
Last component(s) version which did not exhibit the problem:
Platform and version under test:
iOS device: iPhone 14 plus
iOS version: 17.4.1
App type: Native App
RF version: 6.1.1
Real device or emulator/simulator: Real device

**Comment by mykola-mokhnach** [comment] 2024-07-16 10:22
Duplicate of https://github.com/appium/appium/issues/19874

**Closed by mykola-mokhnach** 2024-07-16 10:22 UTC
Labels: Bug, Needs Triage

**Comment by eglitise** [comment] 2024-07-16 10:35
Please refer to the [XCUITest driver documentation](https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/#interact-with-dialogs-managed-by-comapplespringboard) for handling such alerts.
