### ISSUE TITLE
need to document env var approach to driver install params in 2.0 migration guide

### ISSUE THREAD

**Issue by StephanB75** [appium/appium#15822] opened 2021-09-09 06:59 UTC
Is the chromedriver part of the uiautomator2 driver ?
In the past it was possible to add the --chromedriver-skip-install flag to the npm installation.
This is currently also possible when i install appium with 
`npm install appium@next --chromedriver-skip-install --drivers=uiautomator2`

But its not possible if i want to install via
`appium driver install uiautomator2`

Would it be possible to add the flag there also ?

_Originally posted by @StephanB75 in https://github.com/appium/appium/discussions/15812#discussioncomment-1299645_

**Comment by mykola-mokhnach** [comment] 2021-09-09 09:15
Looks like a duplicate of https://github.com/appium/appium/issues/15805

**Comment by mykola-mokhnach** [comment] 2021-09-09 09:15
@jlipps to confirm

**Comment by jlipps** [comment] 2021-09-09 16:18
I think it's a different issue. `--chromedriver-skip-install` is not a driver CLI arg, it gets wrapped up into `process.env` automatically by NPM (NPM has special support for using custom flags during `npm install`).

I think the unfortunate reality here is that we won't be able to support these flags, since we are abstracting away from NPM. I think we'll need to rely on and document an environment-variable based approach (which in this case is already supported, as @KazuCocoa mentioned in #15812).

**Comment by jlipps** [comment] 2021-09-09 16:19
alternatively we could come up with some system for 'driver/plugin installation arguments', but this seems unnecessary when this is a pretty minor use case and env vars do the trick already.

**Comment by mykola-mokhnach** [comment] 2021-09-09 16:22
I am ok with the the env-var based approach

**Comment by KazuCocoa** [comment] 2021-09-09 16:40
im also ok. we need to address this in the 2.0 migration guide ✅

**Comment by jlipps** [comment] 2021-09-09 16:44
@KazuCocoa if you can collect the correct env vars to use, I can add a new section to the guide

**Comment by KazuCocoa** [comment] 2021-09-09 16:49
so far, i found `--chromedriver_cdnurl` and `--chromedriver-skip-install` in https://github.com/appium/appium-chromedriver
They should be `CHROMEDRIVER_CDNURL` and `APPIUM_SKIP_CHROMEDRIVER_INSTALL`.

I think we can just address like:
> `appium install` command does not accept arguments. instead, you should use environment variable. e.g. ` npm install appium --chromedriver-skip-install --drivers=uiautomator2` should be `APPIUM_SKIP_CHROMEDRIVER_INSTALL=true appium driver install uiautomator2` in `appium` command

**Comment by StephanB75** [comment] 2021-09-10 06:08
yes the environment variable "APPIUM_SKIP_CHROMEDRIVER_INSTALL=true" works for both perfectly. Thank you for the tip !

**Closed** 2022-02-15 16:58 UTC
Labels: Documentation, Help Needed, v2
