### ISSUE TITLE
WebElement getLocation/getSize are diffrent from actual

### ISSUE THREAD

**Issue by NirBY** [appium/appium#14400] opened 2020-06-01 16:14 UTC
## The problem

When query for Element getLocation/getSize getting different data then in actual screen/page source.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.17.1
* Last Appium version that did not exhibit the issue (if applicable): v1.17.0
* Desktop OS/version used to run Appium: iMAC
* Node.js version (unless using Appium.app|exe): >V10
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iPhone 8 IOS V13.4.1/XCUITest
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Java Client

## Details

**Attached is Appium page source, with actual size**: 
[20200531075429_499.txt](https://github.com/appium/appium/files/4712254/20200531075429_499.txt)

**The Element - marked in red**:
![image](https://user-images.githubusercontent.com/9214815/83428909-e6c64280-a43b-11ea-99fb-a099cda1f2f2.png)

## Link to Appium logs
**Attached are Appium Logs (only where the issue started)**:
[Appium_Log.txt](https://github.com/appium/appium/files/4712248/Appium_Log.txt)

## Code To Reproduce Issue [ Good To Have ]

Point p = element.getLocation();
Dimension d = element.getSize();

**Comment by mykola-mokhnach** [comment] 2020-06-01 16:24
- What is the output of `mobile: source` with `format: description`?
- Is the issue not reproducible with v. 1.17.0?

**Comment by NirBY** [comment] 2020-06-01 17:39
1a. There is no `mobile: source` option - [http://appium.io/docs/en/commands/mobile-command/](url) how can I run it?
1b. `format: description` where can I find it? [http://appium.io/docs/en/commands/session/source/](url)

2. I don't believe this is Appium ver related. probably an IOS one because iPhone upgraded recently (13.4.1). If it needed I can downgrade and test again.

**Comment by mykola-mokhnach** [comment] 2020-06-01 18:03
> 1a. There is no mobile: source option - http://appium.io/docs/en/commands/mobile-command/ how can I run it?
> 1b. format: description where can I find it? http://appium.io/docs/en/commands/session/source/

https://github.com/appium/appium/pull/14401

**Comment by NirBY** [comment] 2020-06-02 13:16
mobile: source - attached.
[mobile.source.txt](https://github.com/appium/appium/files/4717342/mobile.source.txt)

**Comment by mykola-mokhnach** [comment] 2020-06-02 14:15
As you can see in the description source there are two static text views with SIP label. Consider making a more specific locator for it

**Comment by mykola-mokhnach** [comment] 2020-06-02 14:19
Also it might be that the given overlay is called via IPC. I would try to play with `defaultActiveApplication` and/or `activeAppDetectionPoint` WDA settings in such case

**Comment by NirBY** [comment] 2020-06-03 09:17
1. How do you explain original page source - [https://github.com/appium/appium/files/4712254/20200531075429_499.txt](url)?
I have used: driver.getPageSource()

1. How do you suggest taking pagesources?

**Comment by mykola-mokhnach** [comment] 2020-06-03 11:12
I cannot say nothing for sure, because I don't have the original app to test with. The description page source is generated by XCTest itself and is used to run all types of lookup requests except of xpath one. WDA is using non-documented private snapshots API in order to build xml page source. Of course there might be corner cases that we don't know about while using these undocumented APIs.

**Comment by NirBY** [comment] 2020-06-03 12:21
OK, fair enough.
My workaround in this case, and like @mykola-mokhnach suggested, adding `AND visible == 1` to  iOSNsPredicateString.

**Comment by mykola-mokhnach** [comment] 2020-06-05 07:29
Closed as third party issue

**Closed by mykola-mokhnach** 2020-06-05 07:29 UTC
Labels: ThirdParty, XCUITest
