### ISSUE TITLE
Appium inspector can't create session while using "PreinstalledWDA" on iOS 17.0 

### ISSUE THREAD

**Issue by gebitang** [appium/appium#19288] opened 2023-10-12 11:39 UTC
Appium version: 2.1.3
xcuitest driver: 4.35.0
wda version: 5.10.0
iPhone X, OS version: iOS 17.0 

Xcode: 15
MacOS: 13.5.2

using the following caps, everything works well. appium use xcodebuild to built, install and launch wda.  
```
{
  "platformName": "iOS",
  "appium:deviceName": "iPhone 12 Pro Max",
  "appium:platformVersion": "17.0",
  "appium:showXcodeLog": true,
  "appium:udid": "00008101-0009113A2139001E",
  "appium:bundleId": "com.ccb.ecpmobile.ecp",
  "appium:automationName": "XCUITest"
}
```

if using preInstalledWDA as following caps as [Run Preinstalled WebDriverAgentRunner](https://appium.github.io/appium-xcuitest-driver/4.35/run-preinstalled-wda/) suggested, error occurred:  

>Unable to launch WebDriverAgent because of failure: Unexpected data: {"Error":"InvalidService","Request":"StartService","Service":"com.apple.testmanagerd.lockdown.secure"}. 

```
{
  "platformName": "iOS",
  "appium:deviceName": "iPhone 12 Pro Max",
  "appium:platformVersion": "17.0",
  "appium:showXcodeLog": true,
  "appium:usePreinstalledWDA": true,
  "appium:updatedWDABundleId": "com.ccbft.imc.WebDriverAgentRunner",
  "appium:udid": "00008101-0009113A2139001E",
  "appium:bundleId": "com.ccb.ecpmobile.ecp",
  "appium:automationName": "XCUITest"
}
```
"com.ccbft.imc.WebDriverAgentRunner" is our custumed bundleId for WDA project in   '/Users/zhiwei/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj' 

here is the server log 

```
2023-10-12 11:36:00:093 [HTTP] {"capabilities":{"alwaysMatch":{"platformName":"iOS","appium:deviceName":"iPhone 12 Pro Max","appium:platformVersion":"17.0","appium:showXcodeLog":true,"appium:usePreinstalledWDA":true,"appium:updatedWDABundleId":"com.ccbft.imc.WebDriverAgentRunner","appium:udid":"00008101-0009113A2139001E","appium:bundleId":"com.ccb.ecpmobile.ecp","appium:automationName":"XCUITest","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"iOS","appium:deviceName":"iPhone 12 Pro Max","appium:platformVersion":"17.0","appium:showXcodeLog":true,"appium:usePreinstalledWDA":true,"appium:updatedWDABundleId":"com.ccbft.imc.WebDriverAgentRunner","appium:udid":"00008101-0009113A2139001E","appium:bundleId":"com.ccb.ecpmobile.ecp","appium:automationName":"XCUITest","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
2023-10-12 11:36:00:100 [AppiumDriver@72e8] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","appium:deviceName":"iPhone 12 Pro Max","appium:platformVersion":"17.0","appium:showXcodeLog":true,"appium:usePreinstalledWDA":true,"appium:updatedWDABundleId":"com.ccbft.imc.WebDriverAgentRunner","appium:udid":"00008101-0009113A2139001E","appium:bundleId":"com.ccb.ecpmobile.ecp","appium:automationName":"XCUITest","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"iOS","appium:deviceName":"iPhone 12 Pro Max","appium:platformVersion":"17.0","appium:showXcodeLog":true,"appium:usePreinstalledWDA":true,"appium:updatedWDABundleId":"com.ccbft.imc.WebDriverAgentRunner","appium:udid":"00008101-0009113A2139001E","appium:bundleId":"com.ccb.ecpmobile.ecp","appium:automationName":"XCUITest","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
2023-10-12 11:36:00:103 [AppiumDriver@72e8] Event 'newSessionRequested' logged at 1697110560102 (19:36:00 GMT+0800 (中国标准时间))
2023-10-12 11:36:00:111 [Appium] Attempting to find matching driver for automationName 'XCUITest' and platformName 'iOS'
2023-10-12 11:36:00:112 [Appium] The 'xcuitest' driver was installed and matched caps.
2023-10-12 11:36:00:112 [Appium] Will require it at /Users/zhiwei/.appium/node_modules/appium-xcuitest-driver
2023-10-12 11:36:00:115 [Appium] Requiring driver at /Users/zhiwei/.appium/node_modules/appium-xcuitest-driver
2023-10-12 11:36:00:116 [AppiumDriver@72e8] Appium v2.1.3 creating new XCUITestDriver (v4.35.0) session
2023-10-12 11:36:00:116 [AppiumDriver@72e8] Checking BaseDriver versions for Appium and XCUITestDriver
2023-10-12 11:36:00:116 [AppiumDriver@72e8] Appium's BaseDriver version is 9.3.20
2023-10-12 11:36:00:116 [AppiumDriver@72e8] XCUITestDriver's BaseDriver version is 9.3.20
2023-10-12 11:36:00:124 [XCUITestDriver@ba7f] Creating session with W3C capabilities: {
2023-10-12 11:36:00:125 [XCUITestDriver@ba7f]   "alwaysMatch": {
2023-10-12 11:36:00:125 [XCUITestDriver@ba7f]     "platformName": "iOS",
2023-10-12 11:36:00:125 [XCUITestDriver@ba7f]     "appium:deviceName": "iPhone 12 Pro Max",
2023-10-12 11:36:00:126 [XCUITestDriver@ba7f]     "appium:platformVersion": "17.0",
2023-10-12 11:36:00:126 [XCUITestDriver@ba7f]     "appium:showXcodeLog": true,
2023-10-12 11:36:00:126 [XCUITestDriver@ba7f]     "appium:usePreinstalledWDA": true,
2023-10-12 11:36:00:126 [XCUITestDriver@ba7f]     "appium:updatedWDABundleId": "com.ccbft.imc.WebDriverAgentRunner",
2023-10-12 11:36:00:126 [XCUITestDriver@ba7f]     "appium:udid": "00008101-0009113A2139001E",
2023-10-12 11:36:00:126 [XCUITestDriver@ba7f]     "appium:bundleId": "com.ccb.ecpmobile.ecp",
2023-10-12 11:36:00:126 [XCUITestDriver@ba7f]     "appium:automationName": "XCUITest",
2023-10-12 11:36:00:126 [XCUITestDriver@ba7f]     "appium:includeSafariInWebviews": true,
2023-10-12 11:36:00:127 [XCUITestDriver@ba7f]     "appium:newCommandTimeout": 3600,
2023-10-12 11:36:00:127 [XCUITestDriver@ba7f]     "appium:connectHardwareKeyboard": true
2023-10-12 11:36:00:127 [XCUITestDriver@ba7f]   },
2023-10-12 11:36:00:127 [XCUITestDriver@ba7f]   "firstMatch": [
2023-10-12 11:36:00:127 [XCUITestDriver@ba7f]     {}
2023-10-12 11:36:00:128 [XCUITestDriver@ba7f]   ]
2023-10-12 11:36:00:128 [XCUITestDriver@ba7f] }
2023-10-12 11:36:00:143 [XCUITestDriver@ba7f (07e4b07e)] Session created with session id: 07e4b07e-9a0d-4406-9639-58e38d7077ab
2023-10-12 11:36:00:161 [XCUITest] Current user: 'zhiwei'
2023-10-12 11:36:00:176 [XCUITestDriver@ba7f (07e4b07e)] Available devices: 00008101-0009113A2139001E
2023-10-12 11:36:00:177 [XCUITest] Creating iDevice object with udid '00008101-0009113A2139001E'
2023-10-12 11:36:00:177 [XCUITestDriver@ba7f (07e4b07e)] Determining device to run tests on: udid: '00008101-0009113A2139001E', real device: true
2023-10-12 11:36:00:179 [XCUITestDriver@ba7f (07e4b07e)] Event 'xcodeDetailsRetrieved' logged at 1697110560179 (19:36:00 GMT+0800 (中国标准时间))
2023-10-12 11:36:00:181 [XCUITestDriver@ba7f (07e4b07e)] Event 'appConfigured' logged at 1697110560180 (19:36:00 GMT+0800 (中国标准时间))
2023-10-12 11:36:00:181 [XCUITestDriver@ba7f (07e4b07e)] Event 'resetStarted' logged at 1697110560181 (19:36:00 GMT+0800 (中国标准时间))
2023-10-12 11:36:00:181 [XCUITest] Reset: running ios real device reset flow
2023-10-12 11:36:00:182 [XCUITestDriver@ba7f (07e4b07e)] Event 'resetComplete' logged at 1697110560181 (19:36:00 GMT+0800 (中国标准时间))
2023-10-12 11:36:00:182 [XCUITestDriver@ba7f (07e4b07e)] Using WDA path: '/Users/zhiwei/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'
2023-10-12 11:36:00:183 [XCUITestDriver@ba7f (07e4b07e)] Using WDA agent: '/Users/zhiwei/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
2023-10-12 11:36:00:381 [XCUITest] Crash reports root '/Users/zhiwei/Library/Logs/CrashReporter/MobileDevice/iPhone12 17.0' does not exist. Got nothing to gather.
2023-10-12 11:36:00:381 [XCUITestDriver@ba7f (07e4b07e)] Event 'logCaptureStarted' logged at 1697110560381 (19:36:00 GMT+0800 (中国标准时间))
2023-10-12 11:36:00:382 [XCUITestDriver@ba7f (07e4b07e)] Setting up real device
2023-10-12 11:36:00:720 [XCUITestDriver@ba7f (07e4b07e)] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
2023-10-12 11:36:00:721 [DevCon Factory] Requesting connection for device 00008101-0009113A2139001E on local port 8100, device port 8100
2023-10-12 11:36:00:721 [DevCon Factory] Cached connections count: 0
2023-10-12 11:36:00:723 [DevCon Factory] Successfully requested the connection for 00008101-0009113A2139001E:8100
2023-10-12 11:36:00:723 [XCUITestDriver@ba7f (07e4b07e)] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
2023-10-12 11:36:00:724 [XCUITestDriver@ba7f (07e4b07e)] Trying to start WebDriverAgent 1 times with 10000ms interval
2023-10-12 11:36:00:724 [XCUITestDriver@ba7f (07e4b07e)] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
2023-10-12 11:36:00:724 [XCUITestDriver@ba7f (07e4b07e)] Event 'wdaStartAttempted' logged at 1697110560724 (19:36:00 GMT+0800 (中国标准时间))
2023-10-12 11:36:01:071 [XCUITest] The executable name for the bundle id 'com.ccbft.imc.WebDriverAgentRunner.xctrunner' was 'WebDriverAgentRunner-Runner'
2023-10-12 11:36:01:247 [XCUITest] Failed to kill 'com.ccbft.imc.WebDriverAgentRunner.xctrunner'. Original error: Unexpected data: {"Error":"InvalidService","Request":"StartService","Service":"com.apple.instruments.remoteserver.DVTSecureSocketProxy"}
2023-10-12 11:36:01:249 [XCUITestDriver@ba7f (07e4b07e)] Launching WebDriverAgent on the device without xcodebuild
2023-10-12 11:36:01:474 [ios-device] Xctest for com.ccbft.imc.WebDriverAgentRunner.xctrunner on device 00008101-0009113A2139001E has stopped!
2023-10-12 11:36:01:475 [XCUITestDriver@ba7f (07e4b07e)] Launching WebDriverAgent on the device without xcodebuild
2023-10-12 11:36:01:702 [ios-device] Xctest for com.ccbft.imc.WebDriverAgentRunner.xctrunner on device 00008101-0009113A2139001E has stopped!
2023-10-12 11:36:01:703 [XCUITestDriver@ba7f (07e4b07e)] Event 'wdaStartFailed' logged at 1697110561703 (19:36:01 GMT+0800 (中国标准时间))
2023-10-12 11:36:02:025 [XCUITest] The executable name for the bundle id 'com.ccbft.imc.WebDriverAgentRunner.xctrunner' was 'WebDriverAgentRunner-Runner'
2023-10-12 11:36:02:199 [XCUITest] Failed to kill 'com.ccbft.imc.WebDriverAgentRunner.xctrunner'. Original error: Unexpected data: {"Error":"InvalidService","Request":"StartService","Service":"com.apple.instruments.remoteserver.DVTSecureSocketProxy"}
2023-10-12 11:36:02:200 [XCUITestDriver@ba7f (07e4b07e)] {}
2023-10-12 11:36:02:201 [DevCon Factory] Releasing connections for 00008101-0009113A2139001E device on any port number
2023-10-12 11:36:02:201 [DevCon Factory] Found cached connections to release: ["00008101-0009113A2139001E:8100"]
2023-10-12 11:36:02:201 [DevCon Factory] Releasing the listener for '00008101-0009113A2139001E:8100'
2023-10-12 11:36:02:202 [iProxy@00008101:8100] Closing the connection
2023-10-12 11:36:02:202 [DevCon Factory] Cached connections count: 0
2023-10-12 11:36:02:204 [iProxy@00008101:8100] The connection has been closed
2023-10-12 11:36:02:205 [AppiumDriver@72e8] Event 'newSessionStarted' logged at 1697110562205 (19:36:02 GMT+0800 (中国标准时间))
2023-10-12 11:36:02:206 [AppiumDriver@72e8] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of failure: Unexpected data: {"Error":"InvalidService","Request":"StartService","Service":"com.apple.testmanagerd.lockdown.secure"}. Please make sure if the com.ccbft.imc.WebDriverAgentRunner.xctrunner exists and it is launchable. https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md may help to complete the preparation.
2023-10-12 11:36:02:206 [AppiumDriver@72e8]     at /Users/zhiwei/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:888:19
2023-10-12 11:36:02:206 [AppiumDriver@72e8]     at wrapped (/Users/zhiwei/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:95:13)
2023-10-12 11:36:02:206 [AppiumDriver@72e8]     at retry (/Users/zhiwei/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:68:13)
2023-10-12 11:36:02:206 [AppiumDriver@72e8]     at retryInterval (/Users/zhiwei/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:105:10)
2023-10-12 11:36:02:206 [AppiumDriver@72e8]     at /Users/zhiwei/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:833:7
2023-10-12 11:36:02:208 [HTTP] <-- POST /session 500 2128 ms - 1494
2023-10-12 11:36:02:209 [HTTP] 

```

**Comment by mykola-mokhnach** [comment] 2023-10-12 11:40
Duplicate of https://github.com/appium/appium/issues/19206

**Closed by mykola-mokhnach** 2023-10-12 11:40 UTC

**Comment by KazuCocoa** [comment] 2023-10-12 14:41
This error message is expected as:

> Note This method does not work for iOS 17/tvOS 17 environment for now due to platform changes. Please use the xcodebuild method.

https://appium.github.io/appium-xcuitest-driver/5.6/run-preinstalled-wda/
