### ISSUE TITLE
Using browser.react$ return "Method is not implemented"

### ISSUE THREAD

**Issue by cjmme** [appium/appium#13500] opened 2019-10-28 07:10 UTC
## Environment

 Appium version (or git revision) that exhibits the issue: Appium version 1.13.0, git version 2.13.0.windows.1
 Desktop OS/version used to run Appium: Windows 10.
Node.js version: 8.16.0
* Npm or Yarn package manager: package-lock.json
* Mobile platform/version under test:  9
* Real device or emulator/simulator: Android emulator 
* Appium client : webdriverio, version 5.13.0
appium log:
https://gist.github.com/cjmme/68a5e7ac3edfb4e52d241580d8cdfba6

## Code To Reproduce Issue [ Good To Have ]

browser.$react("MyComponent");

![image](https://user-images.githubusercontent.com/20895790/67658607-07ee1e80-f995-11e9-876f-44be26d8c1b8.png)

**Comment by mykola-mokhnach** [comment] 2019-10-28 07:11
Duplicate of https://github.com/appium/appium/issues/12600

**Closed by mykola-mokhnach** 2019-10-28 07:11 UTC
