### ISSUE TITLE
Error: The instrumentation process cannot be initialized.

### ISSUE THREAD

**Issue by yenyu-chang** [appium/appium#14032] opened 2020-03-05 09:45 UTC
## The problem

Using appium to run app tests on Android emulator with AVD. Session can't start only any emulator environment due to the occurring error "An unknown server-side error occurred while processing the command. Original error: The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output."

## Environment

Appium 1.15.1 exe
Window 10.0.18362.657
npm 6.13.4
Android Studio 3.6.1 ADV

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/yenyu-chang/c6556e121cf8353ffeca608ec423a318

## Code To Reproduce Issue [ Good To Have ]

{
  "deviceName": "emulator-5554",
  "platformName": "Android",
  "appPackage": "de.parkhere.work.stage",
  "appActivity": "de.parkhere.work.MainActivity",
  "noReset": true
}

**Comment by mykola-mokhnach** [comment] 2020-03-05 11:59
Please try the most recent Appium version installed by `npm`

**Comment by mykola-mokhnach** [comment] 2020-03-05 15:12
Possible duplicate of https://github.com/appium/appium/issues/14001

**Comment by mykola-mokhnach** [comment] 2020-03-05 17:46
Actually, it is the duplicate. It turn out to be Android SDK bug of 29.0.3
See the related issue for more details.
Closed as third party issue.

**Closed by mykola-mokhnach** 2020-03-05 17:46 UTC
Labels: NeedsInfo
