### ISSUE TITLE
Not able to accept popup blockers on real iPhone device[Safari Browser]

### ISSUE THREAD

**Issue by afreen07** [appium/appium#12789] opened 2019-06-18 07:18 UTC
## The problem

I am clicking on a FAQ link of my application, which navigates to another window, before opening that window a popup with message "This site is attempting to open a pop up window" is displayed.I want to click on allow button so that I can switch to the new window.But I am not able to do that using 
driver.switchTo().alert().accept()

## Environment
iPhone 6
iOS version: 12.1.4
Appium Version: 1.12.1

## Details
I have also added following capabilities
capabilities.setCapability("autoAcceptAlerts","true");
capabilities.setCapability("unexpectedAlertBehaviour","true");
capabilities.setCapability("safariAllowPopups", "true"); capabilities.setCapability("safariIngoreFraudWarning", "true"); 
  
For the device that I am using I have also disabled following safari settings:
Block Pop-ups
Fraudulent Website Warning
 I followed https://github.com/appium/appium/issues/6864, but no luck  
## Link to Appium logs
An attempt was made to operate on a modal dialog when one was not open.
org.openqa.selenium.NoAlertPresentException: An attempt was made to operate on a modal dialog when one was not open.
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_20'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {autoAcceptAlerts: true, automationName: XCUITest, browserName: safari, databaseEnabled: false, deviceName: iPhone6, javascriptEnabled: true, launchTimeout: 50000, locationContextEnabled: false, networkConnectionEnabled: false, newCommandTimeout: 50000, platform: MAC, platformName: MAC, platformVersion: 12.1.4” -Dsession-override=..., safariAllowPopups: true, safariIngoreFraudWarning: true, showIOSLog: true, startIWDP: true, takesScreenshot: true, udid: 655***********************e62b1..., unexpectedAlertBehaviour: true, unhandledPromptBehavior: true, useNewWDA: false, usePrebuiltWDA: true, wdaConnectionTimeout: 50000, wdaLaunchTimeout: 50000, wdaStartupRetries: 4, wdaStartupRetryInterval: 50000, webStorageEnabled: false}

Could someone please help me with this.

**Comment by mykola-mokhnach** [comment] 2019-06-18 07:48
Duplicate of https://github.com/appium/appium/issues/8582

**Closed by mykola-mokhnach** 2019-06-18 07:48 UTC
