### ISSUE TITLE
Finding elements in Native app is taking too much time.

### ISSUE THREAD

**Issue by rajatdoodi** [appium/appium#13417] opened 2019-10-12 12:41 UTC
## The problem
Finding elements using resource-id is taking 20 secs and higher.

## Environment

* Appium version: 1.13.0 
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): NA
* Npm or Yarn package manager: NA
* Mobile platform/version under test: Android 8.1.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.exe

## Details

I am running a test suite on a native android app, at the starting of the execution the time to find elements and interact with them is fine but after some actions the time to find elements using resource-id and AndroidUIAutomator takes time in range of 20-60 secs.

## Link to Appium logs

https://gist.github.com/rajatdoodi/59e96fc23e4719cf70f6b96c215a9a67

**Comment by mykola-mokhnach** [comment] 2019-10-12 13:27
Possible duplicate of https://github.com/appium/appium/issues?q=is%3Aissue+%22waitForIdleTimeout%22+is%3Aclosed

Please read through the filtered issues and check if the same conditions/solutions apply to your case

**Comment by rajatdoodi** [comment] 2019-10-12 14:33
Adding 'waitForIdleTimeout' value as 500 ms brought down the execution time drastically. Thanks @mykola-mokhnach for the help.

**Closed** 2019-10-12 14:33 UTC
Labels: NeedsInfo, ThirdParty, UIAutomator2
