### ISSUE TITLE
Test execution remains hanging even the Appium server throws an exception - Espresso 

### ISSUE THREAD

**Issue by Scott-20** [appium/appium#16552] opened 2022-03-10 15:58 UTC
## The problem

Calling driver.findElement() for an element that is not displayed on the page, the Appium server throws the exception "io.appium.espressoserver.lib.handlers.exceptions.NoSuchElementException" but the execution does not stop.

## Environment

* Appium version 2.0.0-beta.25
* espresso@2.1.1
* JavaClient 8.0.0
* jdk-11.0.13
* TestNG 7.5
* Desktop OS: Mac OS
* Npm version 8.5.3
* Mobile platform: Android 9
* Application development: Jetpack Compose
* Real device or emulator/simulator: Samsung tab device

## Details

This issue is also reproducible trying to rotate the screen orientation of a device with screen rotation locked or using a dynamic wait for element visibility. The execution remains hanging for about an hour until the max runtime is achieved. 

Also reproducible with other java-client versions: 7.6.0, 8.0.0-beta, 8.0.0-beta2

## Appium logs
Logs in case of wait method:
Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/8f550aae-603e-4891-8081-9a269a668378/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/8f550aae-603e-4891-8081-9a269a668378/element] to [POST http://127.0.0.1:8300/session/d8a991bc-2a74-4206-94f6-3935b3f4c73f/element] with body: {"using":"xpath","value":"//*[@text='LoginNotFound']"}
[WD Proxy] Got response with status 404: {"id":"8fa84bb4-587c-4317-97e7-08296c5fe3b9","sessionId":"d8a991bc-2a74-4206-94f6-3935b3f4c73f","value":{"error":"no such element","message":"Could not find espresso element with strategy XPATH and selector //*[@text='LoginNotFound']","stacktrace":"io.appium.espressoserver.lib.handlers.exceptions.NoSuchElementException: Could not find espresso element with strategy XPATH and selector //*[@text='LoginNotFound']\n\tat io.appium.espressoserver.lib.handlers.FindElement.handleEspresso(FindElement.kt:39)\n\tat io.appium.espressoserver.lib.handlers.FindElement.handleEspresso(FindElement.kt:27)\n\tat io.appium.espressoserver.lib.handlers.RequestHandler$DefaultImpls.invokeStrategy(RequestHandler.kt:35)\n\tat io.appium.espressoserver.lib.handlers.FindElement.invokeStrategy(FindElement.kt:27)\n\tat io.appium.espressoserver.lib.handlers.FindElement.invokeStrategy(FindElement.kt:27)\n\tat io.appium.espressoserver.lib.handlers.RequestHandler$DefaultImpls.handleInternal(RequestHandler.kt:29)\n\tat io.appium.espressoserve...

**Comment by mykola-mokhnach** [comment] 2022-03-10 16:04
Possible duplicate of https://github.com/appium/appium-espresso-driver/issues/756

**Comment by mykola-mokhnach** [comment] 2022-04-11 20:11
The issue is fixed in the master branch. Should be published in the next Appium2 version coming after beta28

**Comment by mykola-mokhnach** [comment] 2022-04-13 10:50
This should be fixed in the resent Appium2 releases beta30+

**Closed by mykola-mokhnach** 2022-04-13 10:50 UTC
Labels: Bug
