### ISSUE TITLE
[Android][Emulator] Turning AC power off causes session to die

### ISSUE THREAD

**Issue by ndinoia** [appium/appium#11378] opened 2018-09-17 18:26 UTC
## The problem

Every time we do `driver.setPowerAC(PowerACState.OFF);` the appium session is ended with `ECONNREFUSED`.

## Environment

* Appium version (or git revision) that exhibits the issue: `1.9.0`
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: `Mac OS High Sierra 10.13.4`
* Node.js version (unless using Appium.app|exe): `10.3.0`
* Mobile platform/version under test: Android Emulator `PixelXL` `API26` using `uiautomator2` and `android-sdk/build-tools/28.0.2`
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

When using `driver.setPowerAC(PowerACState.OFF);` or even if I manually toggle AC off in the emulator menu during a test, appium is unable to run any command on the emulator. Every subsequent command receives an error:

`Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:64667`

## Appium logs

```
...
2018-09-17 14:10:21:121 - info: [HTTP] --> POST /wd/hub/session/f974df40-af07-4a12-a682-b363ebce9e9c/appium/device/power_ac
2018-09-17 14:10:21:121 - info: [HTTP] {"state":"off"}
2018-09-17 14:10:21:122 - debug: [W3C] Calling AppiumDriver.powerAC() with args: ["off","f974df40-af07-4a12-a682-b363ebce9e9c"]
2018-09-17 14:10:21:123 - debug: [ADB] Getting connected emulators
2018-09-17 14:10:21:123 - debug: [ADB] Getting connected devices...
2018-09-17 14:10:21:138 - debug: [ADB] 1 device(s) connected
2018-09-17 14:10:21:138 - debug: [ADB] 1 emulator(s) connected
2018-09-17 14:10:21:139 - debug: [ADB] Overriding /Users/ndinoia/.emulator_console_auth_token with an empty string to avoid telnet authentication for emulator commands
2018-09-17 14:10:21:140 - debug: [ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s emulator-5554 emu power ac off'
2018-09-17 14:10:21:150 - debug: [W3C] Responding to client with driver.powerAC() result: null
2018-09-17 14:10:21:151 - info: [HTTP] <-- POST /wd/hub/session/f974df40-af07-4a12-a682-b363ebce9e9c/appium/device/power_ac 200 30 ms - 14
2018-09-17 14:10:21:152 - info: [HTTP] 
2018-09-17 14:10:21:277 - info: [HTTP] --> GET /wd/hub/session/f974df40-af07-4a12-a682-b363ebce9e9c
2018-09-17 14:10:21:277 - info: [HTTP] {}
2018-09-17 14:10:21:278 - debug: [W3C] Calling AppiumDriver.getSession() with args: ["f974df40-af07-4a12-a682-b363ebce9e9c"]
2018-09-17 14:10:21:279 - debug: [UiAutomator2] Getting session details from server to mix in
2018-09-17 14:10:21:280 - debug: [JSONWP Proxy] Matched '/' to command name 'getSession'
2018-09-17 14:10:21:280 - debug: [JSONWP Proxy] Proxying [GET /] to [GET http://localhost:64667/wd/hub/session/c1e58be8-b728-45a5-849d-921d80a94733] with body: {}
2018-09-17 14:10:21:302 - error: [W3C] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
2018-09-17 14:10:21:302 - error: [W3C]     at JWProxy.command$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:371:13)
2018-09-17 14:10:21:302 - error: [W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
2018-09-17 14:10:21:302 - error: [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
2018-09-17 14:10:21:303 - error: [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
2018-09-17 14:10:21:303 - error: [W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
2018-09-17 14:10:21:304 - info: [HTTP] <-- GET /wd/hub/session/f974df40-af07-4a12-a682-b363ebce9e9c 500 26 ms - 1099
...
```

## Code To Reproduce Issue [ Good To Have ]

`driver.setPowerAC(PowerACState.OFF);`

**Comment by mykola-mokhnach** [comment] 2018-09-17 18:31
Duplicate of https://github.com/appium/appium/issues/11315

You must recreate your session after this endpoint is called. there is nothing that can be done on Appium side do change this behaviour.

**Closed by mykola-mokhnach** 2018-09-17 18:31 UTC

**Comment by ndinoia** [comment] 2018-09-17 19:09
Thanks @mykola-mokhnach, that worked! One catch was that I had to remove `-wipe-data` from my AVD_ARGS capability because it causes appium to kill the emulator on session end even if `NO_RESET` is set to true.

It might help to update the android docs for this workaround, if you send me a link to the right place in the docs repo I'd be glad to make a PR.

Thanks again

**Comment by mykola-mokhnach** [comment] 2018-09-17 20:05
@dpgraham Do you know where this case can be documented?

**Comment by dpgraham** [comment] 2018-09-17 20:20
@mykola-mokhnach I recommend the troubleshooting doc: https://github.com/appium/appium/edit/master/docs/en/writing-running-appium/other/troubleshooting.md
