### ISSUE TITLE
Can you put content list file in each doc directory?

### ISSUE THREAD

**Issue by tbwork** [appium/appium#10835] opened 2018-06-11 03:43 UTC
Each directory of documents only has a list of sub-directories, which is very confusing to our fresh of appium.
Hope you can notice this problem.

**Comment by mykola-mokhnach** [comment] 2018-06-11 05:36
Can you please properly describe what the problem is? Which directory it is? Which structure do you expect there (need an example), etc?

**Comment by tbwork** [comment] 2018-06-11 08:31
@mykola-mokhnach  Hi，buddy. Almost every directory in the docs has no readme.md to list that what this directory is for: e.g., [main doc entry for English reader](https://github.com/appium/appium/tree/master/docs/en), [writing-running-appium](https://github.com/appium/appium/tree/master/docs/en/writing-running-appium), etc.

**Comment by imurchie** [comment] 2018-06-11 13:41
This seems like a reasonable thing to do. I'll add it to our work. Thanks for the suggestion!

**Comment by tbwork** [comment] 2018-06-11 13:44
Thanks for providing such an awesome tool~ @imurchie

**Comment by mykola-mokhnach** [comment] 2018-08-01 19:09
Closed as fixed

**Closed by mykola-mokhnach** 2018-08-01 19:09 UTC
Labels: Documentation, P1
