### ISSUE TITLE
Fail to locate an web element using "findElementByImage" on Android 9 using Appium 1.16.0

### ISSUE THREAD

**Issue by raosumanth** [appium/appium#13956] opened 2020-02-18 21:57 UTC
## The problem

After updated Appium to 1.16.0., "findElementByImage" does not work in Web view (Chrome browser). This works perfectly fine for Native Apps
The testing is on android chrome with chromedriver v80.
The log didn't help much, it just responded error code "400"

Did not try rolling back as this is the first version I tried, the only change I made is that I ran appium with the following command (as it does recognize the latest chrome driver 80) - appium --chromedriver-executable /usr/local/bin/chromedriver 

## Environment

* Appium version - 1.16.0
* Chromedriver - 80.0.3987.106
* Desktop OS/version used to run Appium: Mac
* Mobile platform/version under test: Android - Moto G7
* Real device or emulator/simulator: 
* Appium CLI 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[W3C (1ed3953a)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/1ed3953a-bc52-4cee-8cf3-b822fa1c226a/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/1ed3953a-bc52-4cee-8cf3-b822fa1c226a/element] to [POST http://127.0.0.1:8001/wd/hub/session/1a24d60cbd1e81f4e76c2219d2653264/element] with body: {"using":"-image","value":"iVBORw0KGgoAAAANSUhEUgAAAIAAAACKCAYAAABipUKtAAAMTGlDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnltSSWiBUKSE3kQRBAJICaFFEJAqiEpIAgklxoSgYkeWVXDtIgrqiq6KuOhaAFkr9rIo9r5YUFlZF1exofImBXT1le+d75t7/5w585+SmbkzAOjV8GWyfFQfgAJpoTwhMpQ1Li2dRXoEEGANKMAbDOULFDJOfHwMgDLw/qe8vgatoVx2V3F92/9fxUAoUggAQOIhzhIqBAUQ7wUALxHI5IUAENlQbze1UKbCGRAbyWGAEMtUOEeDS1U4S4Or1DZJCVyIdwBApvH58hwAdJuhnlUkyIE8ujcg9pAKJVIA9MgQBwnEfCHEURAPLSiYrMLQDjhnfcGT8w/OrEFOPj9nEGtyUQs5TKKQ5fOn/5/l+N9SkK8c8OEIG00sj0pQ5QzrdiNvcrQK0yDulmbFxkFsCPFbiVBtDzFKFSujkjX2qIVAwYU1A0yIPYT8sGiILSCOkObHxmj1WdmSCB7EcIag0ySFvCTt2AUiRXiilrNGPjkhbgBny7kc7dgGvlztV2V/XJmXzNHy3xCLeAP8r4rFSakQUwHAqEWSlFiIdSE2UuQlRmtsMNtiMTd2wEauTFDFbw8xWySNDNXwYxnZ8ogErb2sQDGQL1YmlvBitbiqUJwUpakPtl3AV8dvCnGjSMpJHuARKcbFDOQiFIWFa3LH2kTSZG2+2D1ZYWiCdmyPLD9ea4+TRfmRKr0txOaKokTtWHxUIZyQGn48RlYYn6SJE8/M5Y+O18SDF4EYwAVhgAWUsGWBySAXSNq6m7rhL01PBOADOcgBIuCu1QyMSFX3SOEzERSDPyESAcXguFB1rwgUQf3HQa3m6Q6y1b1F6hF54DHEBSAa5MPfSvUo6aC3FPAIaiTfeBfAWPNhU/V9q+NATYxWoxzgZekNWBLDiWHEKGIE0QU3x4PwAD...
[WD Proxy] Got an unexpected response with status 400: {"value":{"error":"invalid argument","message":"invalid argument: invalid locator\n  (Session info: chrome=80.0.3987.99)","stacktrace":"0   chromedriver                        0x00000001079ce329 chromedriver + 3838761\n1   chromedriver                        0x0000000107968123 chromedriver + 3420451\n2   chromedriver                        0x00000001076dc62f chromedriver + 751151\n3   chromedriver                        0x00000001076499a4 chromedriver + 149924\n4   chromedriver                        0x0000000107675297 chromedriver + 328343\n5   chromedriver                        0x00000001076664ed chromedriver + 267501\n6   chromedriver                        0x000000010767338b chromedriver + 320395\n7   chromedriver                        0x00000001076667b3 chromedriver + 268211\n8   chromedriver                        0x00000001076400bd chromedriver + 110781\n9   chromedriver                        0x0000000107641055 chromedriver + 114773\n10  chromedriver                        0x000000010798febf chro...
[debug] [W3C (1ed3953a)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 400 - {"value":{"error":"invalid argument","message":"invalid argument: invalid locator\n  (Session info: chrome=80.0.3987.99)","stacktrace":"0   chromedriver                        0x00000001079ce329 chromedriver + 3838761\n1   chromedriver                        0x0000000107968123 chromedriver + 3420451\n2   chromedriver                        0x00000001076dc62f chromedriver + 751151\n3   chromedriver                        0x00000001076499a4 chromedriver + 149924\n4   chromedriver                        0x0000000107675297 chromedriver + 328343\n5   chromedriver                        0x00000001076664ed chromedriver + 267501\n6   chromedriver                        0x000000010767338b chromedriver + 320395\n7   chromedriver                        0x00000001076667b3 chromedriver + 268211\n8   chromedriver                        0x00000001076400bd chromedriver + 110781\n9   chromedriver                        0x0000000107641055 chromedriver + 114773\n10  chromedriver                        0x000000010798febf chromedriver + 3583679\n11  chromedriver                        0x000000010799ce4a chromedriver + 3636810\n12  chromedriver                        0x000000010799cbe7 chromedriver + 3636199\n13  chromedriver                        0x0000000107973839 chromedriver + 3467321\n14  chromedriver                        0x000000010799d707 chromedriver + 3639047\n15  chromedriver                        0x0000000107985cc7 chromedriver + 3542215\n16  chromedriver                        0x00000001079b3324 chromedriver + 3728164\n17  chromedriver                        0x00000001079d4387 chromedriver + 3863431\n18  libsystem_pthread.dylib             0x00007fff64874e65 _pthread_start + 148\n19  libsystem_pthread.dylib             0x00007fff6487083b thread_start + 15\n"}}
[debug] [W3C (1ed3953a)]     at JWProxy.proxy (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:222:13)
[debug] [W3C] Matched W3C error code 'invalid argument' to InvalidArgumentError
[HTTP] <-- POST /wd/hub/session/1ed3953a-bc52-4cee-8cf3-b822fa1c226a/element 400 30 ms - 1784
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/1ed3953a-bc52-4cee-8cf3-b822fa1c226a
[HTTP] {}
[debug] [W3C (1ed3953a)] Calling AppiumDriver.deleteSession() with args: ["1ed3953a-bc52-4cee-8cf3-b822fa1c2

## Code To Reproduce Issue [ Good To Have ]

1. Try to load an image in the web version (Chrome) in the Google maps and then take a screenshot.
2. After a screenshot is taken, load that screenshot (Original), crop image for comparison (To compare)
3. Note that the below code works fine and I am able to get the Image difference.
OccurrenceMatchingResult result1 = driver
                .findImageOccurrence(DestFile, partDestFile, new OccurrenceMatchingOptions()
                        .withEnabledVisualization());
        byte[] result_png2 = result1.getVisualization();
        byte[] result_png3 = Base64.decodeBase64(result_png2);
       
        BufferedImage img1 = ImageIO.read(new ByteArrayInputStream(result_png3));
        ImageIO.write(img1, "png", new File("images/result_png.png") );
4. The following code blows up by giving the following logs - 
final String greenButton2 = getReferenceImageB64("Marker1.png");
driver.findElementByImage(greenButton2);

org.openqa.selenium.InvalidArgumentException: invalid argument: invalid locator
  (Session info: chrome=80.0.3987.99)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'xxxxx-MacBook-Pro.local', ip: '192.168.1.1xx', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.3', java.version: '11.0.5'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: com.google.android.apps.chr..., appPackage: com.android.chrome, automationName: UiAutomator2, browserName: Chrome, databaseEnabled: false, desired: {automationName: UiAutomator2, browserName: Chrome, deviceName: Android Emulator, mjpegScreenshotUrl: http://192.168.1.117:8080/s..., noReset: true, platformName: android, platformVersion: 9.0, udid: ZY3XXXXXXX}, deviceApiLevel: 28, deviceManufacturer: motorola, deviceModel: moto g(6), deviceName: ZY323D8HFD, deviceScreenDensity: 480, deviceScreenSize: 1080x2160, deviceUDID: ZY3XXXXXXX, javascriptEnabled: true, locationContextEnabled: false, mjpegScreenshotUrl: http://192.168.1.xxx:8080/s..., networkConnectionEnabled: true, noReset: true, pixelRatio: 3, platform: LINUX, platformName: Android, platformVersion: 9, statBarHeight: 72, takesScreenshot: true, udid: ZY3XXXXXXX viewportRect: {height: 1944, left: 0, top: 72, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: a2b0039e-3fd3-4cb1-8bef-4d90e38e3a86
*** Element info: {Using=-image, value=iVBORw0KGgoAAAANSUhEUgAAAeAAAAF8CAYAAAAXcGitAAAMTGlDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnltSSWiBUKSE3kQRBAJICaFFEJAqiEpIAgklxoSgYkeWVXDtIgrqiq6KuOhaAFkr9rIo9r5YUFlZF1exofImBXT1le+d75t7/5w585+SmbkzAOjV8GWyfFQfgAJpoTwhMpQ1Li2dRXoEEGANKMAbDOULFDJOfHwMgDLw/qe8vgatoVx2V3F92/9fxUAoUggAQOIhzhIqBAUQ7wUALxHI5IUAENlQbze1UKbCGRAbyWGAEMtUOEeDS1U4S4Or1DZJCVyIdwBApvH58hwAdJuhnlUkyIE8ujcg9pAKJVIA9MgQBwnEfCHEURAPLSiYrMLQDjhnfcGT8w/OrEFOPj9nEGtyUQs5TKKQ5fOn/5/l+N9SkK8c8OEIG00sj0pQ5QzrdiNvcrQK0yDulmbFxkFsCPFbiVBtDzFKFSujkjX2qIVAwYU1A0yIPYT8sGiILSCOkObHxmj1WdmSCB7EcIag0ySFvCTt2AUiRXiilrNGPjkhbgBny7kc7dgGvlztV2V/XJmXzNHy3xCLeAP8r4rFSakQUwHAqEWSlFiIdSE2UuQlRmtsMNtiMTd2wEauTFDFbw8xWySNDNXwYxnZ8ogErb2sQDGQL1YmlvBitbiqUJwUpakPtl3AV8dvCnGjSMpJHuARKcbFDOQiFIWFa3LH2kTSZG2+2D1ZYWiCdmyPLD9ea4+TRfmRKr0txOaKokTtWHxUIZyQGn48RlYYn6SJE8/M5Y

**Comment by mykola-mokhnach** [comment] 2020-02-18 22:12
Duplicate of https://github.com/appium/appium/issues/11638

Current location by image is only supported in native context

**Closed by mykola-mokhnach** 2020-02-18 22:12 UTC
