### ISSUE TITLE
Password Exposed in the logs

### ISSUE THREAD

**Issue by gautamqa** [appium/appium#13234] opened 2019-09-13 20:20 UTC
## The problem

I was automating a signing page in one of the application and I masked the password in my code (however, when typing in the password field i am decrypting it and entering the text).

Since appium considers it as a text, it actually exposes the password in the logs.

Is it possible to turn off the log for a specific field or convey to appium that for this element, I need to mask the text.

**Comment by mykola-mokhnach** [comment] 2019-09-13 20:56
Duplicate of https://github.com/appium/appium/issues/7622

**Closed by mykola-mokhnach** 2019-09-13 20:56 UTC
