### ISSUE TITLE
when in android webview,driver.get_window_size() fail

### ISSUE THREAD

**Issue by leeyc0704** [appium/appium#14941] opened 2020-12-10 09:22 UTC
## The problem

when in android webview,driver.get_window_size() fail, when in native it can work correctly, it seems the session crash
the wrong appium log is bellow
2020-12-10 15:30:50:831 [MJSONWP (3debe252)] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: socket hang up

## Environment

* Appium version (or git revision) that exhibits the issue:1.14.1
* Desktop OS/version used to run Appium:Android 8.0.0
* Mobile platform/version under test:Huawei Mate8
* Real device or emulator/simulator:eal device

**Comment by mykola-mokhnach** [comment] 2020-12-10 09:31
Duplicate of https://github.com/appium/appium/issues/13925

**Closed by mykola-mokhnach** 2020-12-10 09:31 UTC
