### ISSUE TITLE
[Android] MultiTouch Action on Android real device not working When zoom in/pinch

### ISSUE THREAD

**Issue by jackyxiao126** [appium/appium#15139] opened 2021-02-25 06:22 UTC
## The problem

MultiTouch Action on Android real device not working When zoom in/pinch, but IOS is working fine:
```
MultiTouchAction action= new MultiTouchAction(driver);
        TouchAction finger1= new TouchAction(driver);
        finger1.press(point(centrePoint.x,centrePoint.y-50))
                .waitAction(waitOptions(Duration.ofMillis(1000)))
                .moveTo(point(centrePoint.x, centrePoint.y-100))
                .waitAction(waitOptions(Duration.ofMillis(1000)))
                .release();

        TouchAction finger2= new TouchAction(driver);
        finger2.press(point(centrePoint.x,centrePoint.y+50))
                .waitAction(waitOptions(Duration.ofMillis(1000)))
                .moveTo(point(centrePoint.x, centrePoint.y+100))
                .waitAction(waitOptions(Duration.ofMillis(1000)))
                .release();

        action.add(finger1).add(finger2);
        action.perform();
```

## Environment

* Appium version: 1.19.1
* Desktop OS/version used to run Appium: Mac pro
* Node.js version: v15.5.0
* Real device or emulator/simulator: pixel 2 or sumsung note 8

**Comment by mykola-mokhnach** [comment] 2021-02-25 07:21
Duplicate of https://github.com/appium/appium/issues/14642

**Comment by mykola-mokhnach** [comment] 2021-02-25 07:23
Also, the recent Appium server version implement basic [mobile gestures](https://github.com/appium/appium-uiautomator2-driver#mobile-gesture-commands).

**Comment by mykola-mokhnach** [comment] 2021-02-27 07:57
Closed as not an issue

**Closed by mykola-mokhnach** 2021-02-27 07:57 UTC
Labels: NeedsInfo, NotABug
