### ISSUE TITLE
Appium automatically selects the first element in pop-up menu

### ISSUE THREAD

**Issue by shbadawy** [appium/appium#14991] opened 2021-01-05 07:53 UTC
## The problem

While running tests on iOS simulators, when a pop-up menu and wait for a while, Appium selects the first element of the menu automatically. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.3
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: macOS Big Sur
* Node.js version (unless using Appium.app|exe): 15.5.0
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iPhone 8/11, iOS 14.2
* Real device or emulator/simulator: Simulator.
* Appium CLI or Appium.app|exe: Appium command line tools and desktop app.

## Details

While running tests on iOS simulators, when a pop-up menu appears and wait for a while (the pop-up menu still in view), Appium selects the first element of the menu automatically. The issue happens also when trying the scenario manually (while the webDriverAgent app is installed on the simulator). But when uninstalling the webDriverAgent app, and try the scenario manually, the issue disappears. The issue happens while using the Appium from the command line and the desktop app. 

* I have attached 2 screen recording of the issue (below)

## Link to Appium logs

https://gist.github.com/shbadawy/f0f4d9c5e4fe305db347df020fb600f7

## Screen recording 

https://user-images.githubusercontent.com/22125302/103620164-14301d00-4f44-11eb-8ae3-a6d0e3719217.mov
https://user-images.githubusercontent.com/22125302/103620179-1abe9480-4f44-11eb-9e8b-7c6a48d19ad3.mov

**Comment by mykola-mokhnach** [comment] 2021-01-05 10:30
Duplicate of https://github.com/appium/appium/issues/14900

**Closed by mykola-mokhnach** 2021-01-05 10:30 UTC
