### ISSUE TITLE
appium-uiautomator2-driver@0.3.3 : Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server.

### ISSUE THREAD

**Issue by benz-philip** [appium/appium#8595] opened 2017-06-01 12:21 UTC
## The problem

Failed to install the appium-uiautomator2-server-debug-androidTest.apk and appium-uiautomator2-server-v0.1.5.apk automatically.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.6.5
* Desktop OS/version used to run Appium: MAC 10.12.1
* Node.js version (unless using Appium.app|exe): v6.9.5
* Mobile platform/version under test: Android 7.0

## Details

appium-uiautomator2-server-debug-androidTest.apk and appium-uiautomator2-server-v0.1.5.apk automatically is not installed automatically so that the below mentioned error occurs while running the test.

But, by installing both manually the test runs as expected.
adb install /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-debug-androidTest.apk

adb install /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.5.apk

Re-installed appium-uiautomator2-driver@0.3.3, but couldn't solve the issue!

## Error
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:153:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by mykola-mokhnach** [comment] 2017-06-01 13:31
"socket hang up" means that the server stopped to respond to Appium requests. However, there might be a reason why it died. Usually, it is possible to find something in adb logcat output.

**Comment by priyankshah217** [comment] 2017-06-02 07:21
I see something issue with UIAutomatot2, but i see this is grey area because when i restarted device it works fine. So the actual problem i can see sometime UIAutomator2 stuck or did not close gracefully.
I make a practice so every time i uninstall uiautomator2 server/test app before launching appium server, again this is not a solution but u can proceed ahead with ur work.

**Comment by amias-channer** [comment] 2017-06-22 14:30
I have this error as well , my logcat shows this when it happens- 
channel read: DELETE /wd/hub/session/4ec86cbd-7462-4615-a97d-96bc06da99ae
06-22 12:16:56.372  5368  5632 I appium  : Delete session command
06-22 12:16:56.378  1623  2195 W AppOps  : Bad call: specified package io.appium.uiautomator2.server.test under uid 10074 but it is really 10075
06-22 12:16:56.378  5368  5632 I appium  : Stopping uiautomator2 io.appium.uiautomator2.http io.appium.uiautomator2.server
06-22 12:16:56.379  5368  5632 I appium  : AppiumResponse: {"sessionId":"4ec86cbd-7462-4615-a97d-96bc06da99ae","status":0,"value":"Session deleted"}
06-22 12:16:56.882  5368  5383 I TestRunner: finished: startServer(io.appium.uiautomator2.server.test.AppiumUiAutomator2Server)
06-22 12:16:57.028  1623  2115 I ActivityManager: Force stopping io.appium.uiautomator2.server appid=10074 user=0: finished inst
06-22 12:16:57.028  1623  2115 I ActivityManager: Killing 5368:io.appium.uiautomator2.server/u0a74 (adj 0): stop io.appium.uiautomator2.server

How do you restart the uiautomator2 server ?

**Comment by aaltat** [comment] 2017-11-01 15:05
I am facing same issue with Appium 1.7.1, my Appium log can be found from: https://gist.github.com/aaltat/651ac84f8e7e1f2352ba9470d654373e 

I am running with Ubuntu with this Android SDK: 
```
  Path                 | Version | Description                    | Location
  -------              | ------- | -------                        | -------
  build-tools;22.0.1   | 22.0.1  | Android SDK Build-Tools 22.0.1 | build-tools/22.0.1/
  build-tools;23.0.3   | 23.0.3  | Android SDK Build-Tools 23.0.3 | build-tools/23.0.3/
  build-tools;24.0.3   | 24.0.3  | Android SDK Build-Tools 24.0.3 | build-tools/24.0.3/
  build-tools;25.0.3   | 25.0.3  | Android SDK Build-Tools 25.0.3 | build-tools/25.0.3/
  build-tools;26.0.2   | 26.0.2  | Android SDK Build-Tools 26.0.2 | build-tools/26.0.2/
  emulator             | 26.1.4  | Android Emulator               | emulator/
  patcher;v4           | 1       | SDK Patch Applier v4           | patcher/v4/
  platform-tools       | 26.0.1  | Android SDK Platform-Tools     | platform-tools/
  platforms;android-22 | 2       | Android SDK Platform 22        | platforms/android-22/
  platforms;android-23 | 3       | Android SDK Platform 23        | platforms/android-23/
  platforms;android-24 | 2       | Android SDK Platform 24        | platforms/android-24/
  platforms;android-25 | 3       | Android SDK Platform 25        | platforms/android-25/
  platforms;android-26 | 2       | Android SDK Platform 26        | platforms/android-26/
  tools                | 26.1.1  | Android SDK Tools              | tools/
```

And I have this NodeJS installed: 
```
{ npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '56.1',
  modules: '48',
  node: '6.11.2',
  openssl: '1.0.2l',
  uv: '1.11.0',
  v8: '5.1.281.103',
  zlib: '1.2.11' }
```

And I am using Samsung J5 with Android OS 6.0.1

And the problem is annoying because it is a random problem.  Does anyone have workaround or some solution for the problem?

**Comment by aaltat** [comment] 2017-11-02 12:44
I did find a way to reproduce the problem. It seems that sometimes I have two Appium sessions running for the same server (it looks like I have bug in test teardown, somewhere)  and when the second sessions timeouts, it also kills the first sessions UIAutomator2. I can reproduce the problem with this code: 
```
import time
from appium import webdriver

url = 'http://localhost:4723/wd/hub'
caps = {"platformVersion": "6.0.1",
        "appPackage": "com.android.settings",
        "platformName": "android",
        "appActivity": ".Settings",
        "deviceName": "Samsung"}
driver1 = webdriver.Remote(url, caps)
print driver1.session_id
print 'driver1'
print driver1.find_elements_by_xpath('//*')[0]
time.sleep(1)

print '2. starting'
driver2 = webdriver.Remote(url, caps)
print driver2.session_id
print 'driver2'
print driver2.find_elements_by_xpath('//*')[0]

i = 0
while i < 180:
    print driver2.find_elements_by_xpath('//*')[0]
    print 'index {}'.format(i)
    time.sleep(30)
    i += 30

print 'kill driver2'
driver2.quit()
```

Then I see this in the console: 
```
525addb0-7fd6-495b-b883-3a5d98eb611e
driver1
<appium.webdriver.webelement.WebElement (session="525addb0-7fd6-495b-b883-3a5d98eb611e", e
lement="0748a826-7839-4279-82dc-c626b8cb6415")>
2. starting
f8a277bf-8e23-4acf-8ca2-5aa2c95356dc
driver2
<appium.webdriver.webelement.WebElement (session="f8a277bf-8e23-4acf-8ca2-5aa2c95356dc", e
lement="f9fa134f-427c-459d-b928-4f254e6df42c")>
<appium.webdriver.webelement.WebElement (session="f8a277bf-8e23-4acf-8ca2-5aa2c95356dc", e
lement="687f385e-4861-4e58-82d0-14067015955e")>
index 0
<appium.webdriver.webelement.WebElement (session="f8a277bf-8e23-4acf-8ca2-5aa2c95356dc", e
lement="43a9cde6-9ddd-4cc6-b213-3318d6686778")>
index 30
<appium.webdriver.webelement.WebElement (session="f8a277bf-8e23-4acf-8ca2-5aa2c95356dc", e
lement="aad08ef9-8380-4d02-89dd-5a19dc9ef22e")>
index 60
Traceback (most recent call last):
  File "tmp.py", line 24, in <module>
    print driver2.find_elements_by_xpath('//*')[0]
  File "C:\PYTHON27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 377, i
n find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "C:\PYTHON27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 871, i
n find_elements
    'value': value})['value'] or []
  File "C:\PYTHON27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, i
n execute
    self.error_handler.check_response(response)
  File "C:\PYTHON27\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check
_response
    raise wde
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occur
red while processing the command. Original error: Could not proxy command to remote server
. Original error: Error: read ECONNRESET
```

And there is full [Appium server logs](https://gist.github.com/aaltat/8ac5e179c04490cf87614a2b2015d491). But I can overcome the problem by starting my server with `--session-override` flag.

**Comment by mykola-mokhnach** [comment] 2020-11-16 17:07
Closed as obsolete

**Closed by mykola-mokhnach** 2020-11-16 17:07 UTC
Labels: Bug, P2, UIAutomator2
