### ISSUE TITLE
appium is not working on the release builds. (Obfuscated).

### ISSUE THREAD

**Issue by ramkumary** [appium/appium#12880] opened 2019-07-09 12:19 UTC
## The problem

appium is not working on the release builds. (Obfuscated). The exception is thrown at the root AccessibilityNodeInfo class.

## Environment

* Appium version - appium-java-client - 7.0.0.
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v10.16.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: Android API 29
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: appium service

## Details

Appium is not working with release builds which were obfuscated. At the time, it is working fine with debug build.

## Link to Appium logs

https://gist.github.com/ramkumary/bff89fd5ef9f914ae844d44003ab86b4

## Code To Reproduce Issue [ Good To Have ]

1. Download the redbus android play store build.
2. Run the basic test.

**Comment by mykola-mokhnach** [comment] 2019-07-09 12:43
Unfortunately there is nothing that can be done on Appium side, since the error is caused by UiAutomation2 framework itself. Try Espresso driver, - perhaps it performs better.

**Comment by ramkumary** [comment] 2019-07-10 03:57
I changed the automation name to espresso. Still no luck, I am getting different error altogether. 
Log gist attached.
[Logs](https://gist.github.com/ramkumary/c790808d0d07f744563df89eb6cb4cc6)

**Comment by KazuCocoa** [comment] 2019-07-10 04:17
`-android uiautomator` locator strategy does not work in Espresso driver
http://appium.io/docs/en/commands/element/find-elements/index.html#selector-strategies

**Comment by mykola-mokhnach** [comment] 2019-07-12 11:24
Closed as third party issue

**Closed by mykola-mokhnach** 2019-07-12 11:24 UTC
Labels: ThirdParty, UIAutomator2
