### ISSUE TITLE
IOS - TouchAction function doesn't work

### ISSUE THREAD

**Issue by jeangb** [appium/appium#8325] opened 2017-04-25 16:10 UTC
## The problem

I'm working with the java-client and an iOs real device.
My goal is to click on a offset of a MobileElement.
After I saw that driver.tap was deprecated, I tried to use IOSTouchAction but it doesn't work. 
I think **myMobileElement.click()** and **new IOSTouchAction(myDriver).tap(myMobileElement)** should do the same but only the first one works.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5-beta
* Desktop OS/version used to run Appium: Mac OS 10
* Node.js version (unless using Appium.app|exe): 3.10.10
* Mobile platform/version under test: iOS 9.3.5
* Real device or emulator/simulator: iPhone 6 plus

## Details
- First method with mobileElement.click works:
```
MobileElement beforeLastBubble= roomPageA.bubblesList.get(roomPageA.bubblesList.size()-2);
beforeLastBubble.click();
```
Appium server logs are: https://gist.github.com/jeangb/24ba085e2c8f686cc78e684d2b76f636

- Second method with TouchAction doesn't work:
`new IOSTouchAction(myDriver).tap(beforeLastBubble);`
(The driver used to instanciate the IOSTouchAction is the same used to create my MobileElement object)
Appium server logs returns 

> [MJSONWP] Responding to client with driver.performTouch() result: null

Full logs here: https://gist.github.com/jeangb/ce8b48fd65180a2c208f26d10f447f2d

For me the second method is the equivalent of the first one, why it doesn't work ?

**Comment by imurchie** [comment] 2017-04-25 17:06
The underlying system things that this `tap` action has worked. Returning `null` is the expected behavior.

Are the coordinates you are tapping correct?

**Comment by mykola-mokhnach** [comment] 2017-04-25 18:33
Is it landscape mode?  Also it looks suspicious that the **x** click coordinate equals to zero.

**Comment by jeangb** [comment] 2017-04-25 19:07
Hi,

@imurchie Well I tried with and without coordinates. I guess without coordinates it should click on the center of the MobileElement, but it didn't work.
I tried several times with coordinates (I want to hit the left side of the element) and it didn't work neither.

@mykola-mokhnach no it's portrait mode. This item's width is about the width of the application's one. I guess 0 is the x coordinate of the top left of the mobileelement. So maybe the tap function doesn't tap at the center finally.

**Comment by mykola-mokhnach** [comment] 2017-04-25 19:23
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md

Try to calculate coordinates manually and use **tap** gesture

**Comment by jeangb** [comment] 2017-04-25 19:28
Thanks @mykola-mokhnach I will try that.
I would like to avoid to hardcode these coordinates because the item I want to click on it has a relative location.

Anyway I'm a bit confused :) . I don't understand why it's not possible anymore to use functions like swipe, tap directly on the mobileelement and instead use an other object (TouchAction).

**Comment by mykola-mokhnach** [comment] 2017-04-25 19:32
it is not mandatory to hardcode coordinates. It is possible to get the size/location of an element to calculate them.

Regarding TouchAction functionality - it only guarantees the tap action will be performed on the element, but does not exactly say where the tap should happen: at the top left corner or at the center. So I assume everything works as expected.

**Comment by jeangb** [comment] 2017-04-25 20:08
I tried driver.tap(x, y) if I remember correctly, calculating x or y with mobileElement.getCoordinates().getX().

For TouchAction, I guess whenever I use tap on the mobilement (and if mobileElement.click works) it should hit on the object. 
But maybe during my tries it didn't click on the hitbox of the object if ever there is one.

**Comment by jeangb** [comment] 2017-04-26 08:03
@mykola-mokhnach : I'm trying touchaction with coordinates, but I don't have traces in the appium server for these.

`new IOSTouchAction(myDriver.tap(beforeLastBubble);`
I have traces in appium server.

But for:
```
new IOSTouchAction(myDriver).tap(beforeLastBubble,100,10);
new IOSTouchAction(myDriver).tap(40, 260);
```
I don't have a single trace in appium server.

**Comment by LiuYuXuans** [comment] 2017-05-03 09:27
I had the same problem .The tap action seems to be not functioning .Would you tell me how to manage this problem please?

**Comment by mykola-mokhnach** [comment] 2017-05-05 11:37
@jeangb you are possibly missing _perform_ call, which is mandatory to apply the action.

**Comment by danielMayberg** [comment] 2017-05-16 14:42
tap action not working for me as well, using appium 1.6.4 with ruby client, on iOS10 iphone 6 simulator.

**Comment by dpgraham** [comment] 2017-07-20 23:29
Closing this issue. If it still didn't work with call to `.perform` I'll re-open.

**Closed by dpgraham** 2017-07-20 23:29 UTC

**Comment by prabhjotAppmobi** [comment] 2017-12-14 05:48
I have been getting the similar issue on iOS. I am testing ionic App with Appium in Java. For Android tests, The following works fine. The below might be an issue with safari. Is this possible? Please suggest any work around. Thanks

new Actions(driver).moveToElement(driver.findElement(Id)
		 .click().sendKeys("Test@1234").build().perform();
