### ISSUE TITLE
Appium 1.19.1 unknown error

### ISSUE THREAD

**Issue by EscudoEscobar** [appium/appium#15002] opened 2021-01-07 13:29 UTC
## The problem

Hello. I use Appium first time and I have a problem
I start Appium with these configuration (via simulator)
`{
  "app": "/Users/Escudo/Downloads/car.app",
  "deviceName": "iPhone 11 Pro Max (14.3)",
  "udid": "D316BD0B-927E-4404-9F27-096B2C34***7",
  "automationName": "XCUITest",
  "platformName": "iOS",
  "useNewWDA": true
}`

Simulator start
App installed
And then I have these error

`An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message: 2021-01-07 14:28:02.875 xcodebuild[20435:1839790] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphonesimulator14.3-x86_64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/Escudo/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/WebDriverAgentRunner_iphonesimulator14.3-x86_64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7f8cb74158d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}} ** TEST BUILD FAILED ** 2021-01-07 14:28:02.893 xcodebuild[20435:1839790] IDETestOperationsObserverDebug: Writing diagnostic log for test session to: /Users/Escudo/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2021.01.07_14-28-01-+0100.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-BDE7CECA-7068-401D-A127-77B6246EF0B8/WebDriverAgentRunner-792FF8A3-81D4-4A0B-90F3-D75E30480FEB/Session-WebDriverAgentRunner-2021-01-07_142802-Q3nfNK.log 2021-01-07 14:28:02.894 xcodebuild[20435:1839724] [MT] IDETestOperationsObserverDebug: (9F6BC1FF-1A11-48DF-9796-56736C6C9C8B) Beginning test session WebDriverAgentRunner-9F6BC1FF-1A11-48DF-9796-56736C6C9C8B at 2021-01-07 14:28:02.895 with Xcode 12C33 on target <DVTiPhoneSimulator: 0x7f8cba9e5c20> { SimDevice: iPhone 11 Pro Max (D316BD0B-927E-4404-9F27-096B2C34C857, iOS 14.3, Booted) } (14.3 (18C61)) 2021-01-07 14:28:02.902 xcodebuild[20435:1839724] [MT] IDETestOperationsObserverDebug: (9F6BC1FF-1A11-48DF-9796-56736C6C9C8B) Finished requesting crash reports. Continuing with testing. *** If you believe this error represents a bug, please attach the result bundle at /Users/Escudo/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2021.01.07_14-28-01-+0100.xcresult 2021-01-07 14:28:05.248 xcodebuild[20435:1839724] [MT] IDETestOperationsObserverDebug: 2.363 elapsed -- Testing started completed. 2021-01-07 14:28:05.248 xcodebuild[20435:1839724] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start 2021-01-07 14:28:05.248 xcodebuild[20435:1839724] [MT] IDETestOperationsObserverDebug: 2.363 sec, +2.363 sec -- end Test session results, code coverage, and logs: /Users/Escudo/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2021.01.07_14-28-01-+0100.xcresult Testing failed: Building for iOS Simulator, but the linked and embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator. Building for iOS Simulator, but the linked and embedded framework 'YYCache.framework' was built for iOS + iOS Simulator. Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator. Building for iOS Simulator, but the embedded framework 'YYCache.framework' was built for iOS + iOS Simulator. WebDriverAgentRunner:`

## Environment
MasOs BigSur 11.1
Appium 1.19.1
Xcode Version 12.3 (12C33)
Intellej IDEA

**Comment by mykola-mokhnach** [comment] 2021-01-07 15:27
Duplicate of https://github.com/appium/appium/issues/14952

**Closed by mykola-mokhnach** 2021-01-07 15:27 UTC
