### ISSUE TITLE
[appium@1.15.0] get element text/value incorrect on IOS 11/ iOS 12

### ISSUE THREAD

**Issue by maggie5750** [appium/appium#13439] opened 2019-10-17 03:17 UTC
## The problem
[appium@1.15.0] get element text/value incorrect on IOS 11/ iOS 12. driver.getPageSource could find the correct text/value, but find element and get its text/value is incorrect.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): appium 1.14.0
* Desktop OS/version used to run Appium: Mac 10.14.4
* Node.js version (unless using Appium.app|exe): v10.13.0
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 11/ iOS 12
* Real device or emulator/simulator: real device & simulator
* Appium CLI or Appium.app|exe:

## Details

The same element get value of element, on IOS 12 return "1", on IOS 13 return "5 items".

## Link to Appium logs

`2019-10-17 10:57:28:523 - [debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8102/session/CC00E251-9053-4CE3-8D81-0A46A17A5EC6/element] with body: {"using":"class chain","value":"**/XCUIElementTypeTabBar/**/XCUIElementTypeButton[$name=='tabMessagesBtn'$]"}
2019-10-17 10:57:28:777 - [debug] [WD Proxy] Got response with status 200: {"value":{"ELEMENT":"C4000000-0000-0000-F27F-000000000000","element-6066-11e4-a52e-4f735466cecf":"C4000000-0000-0000-F27F-000000000000"},"sessionId":"CC00E251-9053-4CE3-8D81-0A46A17A5EC6"}
2019-10-17 10:57:28:777 - [debug] [W3C (6bdccfc2)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"C4000000-0000-0000-F27F-000000000000","ELEMENT":"C4000000-0000-0000-F27F-000000000000"}
2019-10-17 10:57:28:777 - [HTTP] <-- POST /wd/hub/session/6bdccfc2-0e9a-4632-9018-ff4bbc82bdec/element 200 278 ms - 137
2019-10-17 10:57:28:778 - [HTTP]
2019-10-17 10:57:30:437 - [HTTP] --> GET /wd/hub/session/6bdccfc2-0e9a-4632-9018-ff4bbc82bdec/element/C4000000-0000-0000-F27F-000000000000/attribute/value
2019-10-17 10:57:30:437 - [HTTP] {}
2019-10-17 10:57:30:438 - [debug] [W3C (6bdccfc2)] Calling AppiumDriver.getAttribute() with args: ["value","C4000000-0000-0000-F27F-000000000000","6bdccfc2-0e9a-4632-9018-ff4bbc82bdec"]
2019-10-17 10:57:30:438 - [debug] [XCUITest] Executing command 'getAttribute'
2019-10-17 10:57:30:439 - [debug] [WD Proxy] Matched '/element/C4000000-0000-0000-F27F-000000000000/attribute/value' to command name 'getAttribute'
2019-10-17 10:57:30:439 - [debug] [WD Proxy] Proxying [GET /element/C4000000-0000-0000-F27F-000000000000/attribute/value] to [GET http://localhost:8102/session/CC00E251-9053-4CE3-8D81-0A46A17A5EC6/element/C4000000-0000-0000-F27F-000000000000/attribute/value] with no body
2019-10-17 10:57:30:602 - [debug] [WD Proxy] Got response with status 200: {
2019-10-17 10:57:30:602 - [debug] [WD Proxy]   "value" : "1",
2019-10-17 10:57:30:602 - [debug] [WD Proxy]   "sessionId" : "CC00E251-9053-4CE3-8D81-0A46A17A5EC6"`

## Appium driver Page Source
`<XCUIElementTypeTabBar type="XCUIElementTypeTabBar" enabled="true" visible="true" x="0" y="813" width="414" height="83">
        <XCUIElementTypeButton type="XCUIElementTypeButton" value="5 items" name="tabMessagesBtn" label="tabMessagesBtn" enabled="true" visible="true" x="2" y="814" width="80" height="48"/>
      </XCUIElementTypeTabBar>`

**Comment by xuwintery** [comment] 2019-10-17 05:46
I had the same problem，
Environment：
Node.js version (unless using Appium.app|exe): v11.6.0
Mobile platform/version under test: iOS 12
Appium version (or git revision) that exhibits the issue: Appium 1.15.1

**Comment by mykola-mokhnach** [comment] 2019-10-17 06:51
Duplicate of https://github.com/appium/appium/issues/13288

**Closed by mykola-mokhnach** 2019-10-17 06:51 UTC
