### ISSUE TITLE
Real-time test apps continue to exit

### ISSUE THREAD

**Issue by zhouyawei123** [appium/appium#12560] opened 2019-04-29 06:16 UTC
An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: +[XCAXClient_iOS sharedClient]: unrecognized selector sent to class 0x10031c130 ( 0 CoreFoundation 0x0000000183f311d0 <redacted> + 148 1 libobjc.A.dylib 0x000000018296855c objc_exception_throw + 56 2 CoreFoundation 0x0000000183f381a8 <redacted> + 0 3 CoreFoundation 0x0000000183f35270 <redacted> + 916 4 CoreFoundation 0x0000000183e2e80c _CF_forwarding_prep_0 + 92 5 WebDriverAgentLib 0x0000000101e382a4 __37+[FBApplication fb_activeApplication]_block_invoke + 52 6 WebDriverAgentLib 0x0000000101e113d4 -[FBRunLoopSpinner spinUntilTrue:error:] + 152 7 WebDriverAgentLib 0x0000000101e11314 -[FBRunLoopSpinner spinUntilTrue:] + 84 8 WebDriverAgentLib 0x0000000101e38004 +[FBApplication fb_activeApplication] + 128 9 WebDriverAgentLib 0x0000000101e23a48 -[FBSession application] + 332 10 WebDriverAgentLib 0x0000000101e2a818 +[FBSessionCommands currentCapabilities] + 124 11 WebDriverAgentLib 0x0000000101e2a6d4 +[FBSessionCommands sessionInformation] + 288 12 WebDriverAgentLib 0x0000000101e29d0c +[FBSessionCommands handleCreateSession:] + 1404 13 WebDriverAgentLib 0x0000000101e0fdf4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 220 14 WebDriverAgentLib 0x0000000101e06294 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 504 15 RoutingHTTPServer 0x0000000101ec63cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144 16 RoutingHTTPServer 0x0000000101ec6b80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44 17 libdispatch.dylib 0x0000000182dba1bc <redacted> + 16 18 libdispatch.dylib 0x0000000182dcb084 <redacted> + 320 19 libdispatch.dylib 0x0000000182dba1bc <redacted> + 16 20 libdispatch.dylib 0x0000000182dbed68 _dispatch_main_queue_callback_4CF + 1000 21 CoreFoundation 0x0000000183ede810 <redacted> + 12 22 CoreFoundation 0x0000000183edc3fc <redacted> + 1660 23 CoreFoundation 0x0000000183e0a2b8 CFRunLoopRunSpecific + 444 24 Foundation 0x000000018494726c <redacted> + 304 25 WebDriverAgentLib 0x0000000101e052a0 -[FBWebServer startServing] + 416 26 WebDriverAgentRunner 0x00000001018f3be8 -[UITestingUITests testRunner] + 124 27 CoreFoundation 0x0000000183f37150 <redacted> + 144 28 CoreFoundation 0x0000000183e29eac <redacted> + 284 29 XCTest 0x000000010021200c __24-[XCTestCase invokeTest]_block_invoke_2.200 + 68 30 XCTest 0x000000010021a61c -[XCTestCase assertInvalidObjectsDeallocatedAfterScope:] + 136 31 XCTest 0x0000000100211f98 __24-[XCTestCase invokeTest]_block_invoke.194 + 196 32 XCTest 0x0000000100266ed4 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 64 33 XCTest 0x0000000100266dec -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 108 34 XCTest 0x0000000100211bc8 __24-[XCTestCase invokeTest]_block_invoke + 808 35 XCTest 0x000000010026ce8c -[XCUITestContext performInScope:] + 144 36 XCTest

**Comment by mykola-mokhnach** [comment] 2019-04-29 06:21
Duplicate of https://github.com/appium/appium/issues/12462

**Closed by mykola-mokhnach** 2019-04-29 06:21 UTC
