### ISSUE TITLE
iOS Horizontal Swipe is performed as Vertical Swipe in Appium 1.7.0-beta

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium#9288] opened 2017-09-24 10:04 UTC
## The problem

When swiping horizontally on iOS the application is actually scrolling vertically

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0-beta
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4 (probably even 1.6.5 and 1.6.6 beta)
* Desktop OS/version used to run Appium: macOS 10.12.6
* Node.js version (unless using Appium.app|exe): 7.0.0
* Mobile platform/version under test: iOS 10.3 & iOS 11
* Real device or emulator/simulator: iPhone 5s Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs
```

[HTTP] --> POST /wd/hub/session/11bea224-b5fc-4d5a-b244-773e742d1d2a/touch/perform {"actions":[{"action":"press","options":{"x":320,"y":535}},{"action":"wait","options":{"ms":5}},{"action":"moveTo","options":{"x":-320,"y":0}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":320,"y":535}},{"action":"wait","options":{"ms":5}},{"action":"moveTo","options":{"x":-320,"y":0}},{"action":"release","options":{}}],"11bea224-b5fc-4d5a-b244-773e742d1d2a"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"x":320,"y":535})-wait(options={"ms":5})-moveTo(options={"x":-320,"y":0})-release(options={})
[debug] [XCUITest] Found matching gesture: drag
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:6789/session/73404F73-8868-4792-8FAF-6E48E20C6419/wda/dragfromtoforduration] with body: {"fromX":320,"fromY":535,"toX":0,"toY":535,"duration":0.005}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"73404F73-8868-4792-8FAF-6E48E20C6419","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: null
```

## Code To Reproduce Issue [ Good To Have ]

```
    public static void swipeRightToLeftOnIosElement(MobileElement element) {
        int xStart = element.getLocation().getX() + element.getSize().getWidth();
        int yCoordinate = element.getCenter().getY();
        int xStop = element.getLocation().getX();
        final int durationMillis = 5;
        getDriver().swipe(xStart, yCoordinate, xStop, yCoordinate, durationMillis);
    }
```

**Comment by mykola-mokhnach** [comment] 2017-09-24 10:19
Closed as duplicate of https://github.com/facebook/WebDriverAgent/issues/705

**Closed by mykola-mokhnach** 2017-09-24 10:19 UTC

**Comment by cosminstirbu** [comment] 2017-09-24 14:37
I've checked out your fix on WebDriverAgent and it didn't solve my issue.

After further investigations, regardless of passing YES or NO to `shouldApplyOrientationWorkaround` in WDA it still didn't make any difference.

The fix was to pass a value smaller than the screen's width:

So instead of passing {"fromX":320,"fromY":535,"toX":0,"toY":535,"duration":0.005}, if I pass {"fromX":319,"fromY":535,"toX":0,"toY":535,"duration":0.005} - the scroll works :).

Thank you for looking into this though.
