### ISSUE TITLE
Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 404 

### ISSUE THREAD

**Issue by vs111** [appium/appium#13506] opened 2019-10-29 13:59 UTC
## The problem

Today I upgraded my Appium version to v1.13 to v1.15.1. and also upgraded the chrome driver version (78.0.3904.70). unknown error occurred.
## Environment

* Appium version: 1.15.1
* Last Appium version :1.13
* Desktop OS/version used to run Appium: win8.1 pro
* Node.js version (unless using Appium.app|exe):10.15.3
* Npm or Yarn package manager:6.4.1
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: real device(oneplus)
* Appium CLI or Appium.app|exe:Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

PFA log file

## Code To Reproduce Issue [ Good To Have ]

public class Homepage {
	static AppiumDriver<MobileElement> driver; 
	
	@BeforeTest
	public void launch () throws IOException, InterruptedException
	{
		
		DesiredCapabilities caps = new DesiredCapabilities();
	
		caps.setCapability("deviceName", "vs");
		caps.setCapability("udid", "edab6d0d");
		caps.setCapability("platformVersion", "9.0.9");
		caps.setCapability("platformName", "Android");
		caps.setCapability("browserName", "Chrome");
	
		URL url=new URL("http://0.0.0.0:4723/wd/hub");
	       driver =new AppiumDriver<MobileElement>(url,caps);
	      driver=new AndroidDriver<MobileElement>(url,caps);
				
	      driver.get("https://www.facebook.com");
		
	}
}

[appium-server-logs error.txt](https://github.com/appium/appium/files/3783867/appium-server-logs.error.txt)

**Comment by mykola-mokhnach** [comment] 2019-10-29 14:22
Duplicate of https://github.com/appium/java-client/issues/1242

**Closed by mykola-mokhnach** 2019-10-29 14:22 UTC
