### ISSUE TITLE
android flutter app element.click()  Cannot invoke method public void androidx.test.uiautomator.GestureController.performGesture(androidx.test.uiautomator.PointerGesture[])

### ISSUE THREAD

**Issue by zczh8** [appium/appium#15838] opened 2021-09-11 16:33 UTC
## The problem

Call to 'tap' failed
[element.click()] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Cannot invoke method public void androidx.test.uiautomator.GestureController.performGesture(androidx.test.uiautomator.PointerGesture[]) on object androidx.test.uiautomator.GestureController@7f6e355 with parameters [[Landroidx.test.uiautomator.PointerGesture;@1fb5e0c]

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0 Desktop
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:MacBook Pro (13-inch, M1, 2020) version:11.4(20F71)
* Node.js version (unless using Appium.app|exe):v14.17.1
* Npm or Yarn package manager:npm 6.14.13
* Mobile platform/version under test:android 
* Real device or emulator/simulator:Real device (xiaomi 5x)
* Appium CLI or Appium.app|exe:Appium.app

## Details

Call to 'tap' failed
[element.click()] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Cannot invoke method public void androidx.test.uiautomator.GestureController.performGesture(androidx.test.uiautomator.PointerGesture[]) on object androidx.test.uiautomator.GestureController@7f6e355 with parameters [[Landroidx.test.uiautomator.PointerGesture;@1fb5e0c]

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/c9aba214-3047-4ffe-ac03-1e9e0f50a1e8/element/4b6273bb-4054-45a7-bac7-e8ee55e2c2df/click
[HTTP] {}
[MJSONWP (c9aba214)] Calling AppiumDriver.click() with args: ["4b6273bb-4054-45a7-bac7-e8ee55e2c2df","c9aba214-3047-4ffe-ac03-1e9e0f50a1e8"]
[WD Proxy] Matched '/element/4b6273bb-4054-45a7-bac7-e8ee55e2c2df/click' to command name 'click'
[WD Proxy] Proxying [POST /element/4b6273bb-4054-45a7-bac7-e8ee55e2c2df/click] to [POST http://127.0.0.1:8202/wd/hub/session/789570e8-5ba0-4f99-85b8-e8aede5e5711/element/4b6273bb-4054-45a7-bac7-e8ee55e2c2df/click] with body: {"element":"4b6273bb-4054-45a7-bac7-e8ee55e2c2df"}
[WD Proxy] Got response with status 500: {"sessionId":"789570e8-5ba0-4f99-85b8-e8aede5e5711","value":{"error":"unknown error","message":"Cannot invoke method public void androidx.test.uiautomator.GestureController.performGesture(androidx.test.uiautomator.PointerGesture[]) on object androidx.test.uiautomator.GestureController@7f6e355 with parameters [[Landroidx.test.uiautomator.PointerGesture;@1fb5e0c]","stacktrace":"io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: Cannot invoke method public void androidx.test.uiautomator.GestureController.performGesture(androidx.test.uiautomator.PointerGesture[]) on object androidx.test.uiautomator.GestureController@7f6e355 with parameters [[Landroidx.test.uiautomator.PointerGesture;@1fb5e0c]\n\tat io.appium.uiautomator2.utils.ReflectionUtils.invoke(ReflectionUtils.java:84)\n\tat io.appium.uiautomator2.model.internal.GestureController.performGesture(GestureController.java:64)\n\tat io.appium.uiautomator2.model.internal.GestureController.click(GestureController.java:89)\n\tat io.appium.uiautomator2...
[W3C] Matched W3C error code 'unknown error' to UnknownError
[MJSONWP (c9aba214)] Encountered internal error running command: An unknown server-side error occurred while processing the command. Original error: Cannot invoke method public void androidx.test.uiautomator.GestureController.performGesture(androidx.test.uiautomator.PointerGesture[]) on object androidx.test.uiautomator.GestureController@7f6e355 with parameters [[Landroidx.test.uiautomator.PointerGesture;@1fb5e0c]
[MJSONWP (c9aba214)] io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: Cannot invoke method public void androidx.test.uiautomator.GestureController.performGesture(androidx.test.uiautomator.PointerGesture[]) on object androidx.test.uiautomator.GestureController@7f6e355 with parameters [[Landroidx.test.uiautomator.PointerGesture;@1fb5e0c]
[MJSONWP (c9aba214)] 	at io.appium.uiautomator2.utils.ReflectionUtils.invoke(ReflectionUtils.java:84)
[MJSONWP (c9aba214)] 	at io.appium.uiautomator2.model.internal.GestureController.performGesture(GestureController.java:64)
[MJSONWP (c9aba214)] 	at io.appium.uiautomator2.model.internal.GestureController.click(GestureController.java:89)
[MJSONWP (c9aba214)] 	at io.appium.uiautomator2.core.AxNodeInfoHelper.click(AxNodeInfoHelper.java:112)
[MJSONWP (c9aba214)] 	at io.appium.uiautomator2.model.BaseElement.click(BaseElement.java:64)
[MJSONWP (c9aba214)] 	at io.appium.uiautomator2.handler.Click.safeHandle(Click.java:37)
[MJSONWP (c9aba214)] 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)
[MJSONWP (c9aba214)] 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:262)
[MJSONWP (c9aba214)] 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:256)
[MJSONWP (c9aba214)] 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)
[MJSONWP (c9aba214)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[MJSONWP (c9aba214)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[MJSONWP (c9aba214)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[MJSONWP (c9aba214)] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[MJSONWP (c9aba214)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[MJSONWP (c9aba214)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[MJSONWP (c9aba214)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[MJSONWP (c9aba214)] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
[MJSONWP (c9aba214)] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[MJSONWP (c9aba214)] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[MJSONWP (c9aba214)] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
[MJSONWP (c9aba214)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[MJSONWP (c9aba214)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[MJSONWP (c9aba214)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[MJSONWP (c9aba214)] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
[MJSONWP (c9aba214)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[MJSONWP (c9aba214)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[MJSONWP (c9aba214)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[MJSONWP (c9aba214)] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
[MJSONWP (c9aba214)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[MJSONWP (c9aba214)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[MJSONWP (c9aba214)] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
[MJSONWP (c9aba214)] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
[MJSONWP (c9aba214)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
[MJSONWP (c9aba214)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
[MJSONWP (c9aba214)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
[MJSONWP (c9aba214)] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
[MJSONWP (c9aba214)] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
[MJSONWP (c9aba214)] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
[MJSONWP (c9aba214)] 	at java.lang.Thread.run(Thread.java:764)
[MJSONWP (c9aba214)] Caused by: java.lang.reflect.InvocationTargetException
[MJSONWP (c9aba214)] 	at java.lang.reflect.Method.invoke(Native Method)
[MJSONWP (c9aba214)] 	at io.appium.uiautomator2.utils.ReflectionUtils.invoke(ReflectionUtils.java:82)
[MJSONWP (c9aba214)] 	... 39 more
[MJSONWP (c9aba214)] Caused by: java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
[MJSONWP (c9aba214)] 	at android.os.Parcel.readException(Parcel.java:2016)
[MJSONWP (c9aba214)] 	at android.os.Parcel.readException(Parcel.java:1962)
[MJSONWP (c9aba214)] 	at android.app.IUiAutomationConnection$Stub$Proxy.injectInputEvent(IUiAutomationConnection.java:283)
[MJSONWP (c9aba214)] 	at android.app.UiAutomation.injectInputEvent(UiAutomation.java:501)
[MJSONWP (c9aba214)] 	at androidx.test.uiautomator.GestureController.performGesture(GestureController.java:150)
[MJSONWP (c9aba214)] 	... 41 more
[MJSONWP (c9aba214)] 
[HTTP] <-- POST /wd/hub/session/c9aba214-3047-4ffe-ac03-1e9e0f50a1e8/element/4b6273bb-4054-45a7-bac7-e8ee55e2c2df/click 500 112 ms - 438
[HTTP]

**Comment by mykola-mokhnach** [comment] 2021-09-11 16:44
The original issue there is `Caused by: java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission`, which an exception generated by UiAutomator framework itself. There are several traces of it in google search, which you could try as a possible workaround, but generally there is nothing we could do about it from Appium side:
- https://stackoverflow.com/questions/22163424/android-java-lang-securityexception-injecting-to-another-application-requires

**Comment by KazuCocoa** [comment] 2021-09-11 17:21
Potentially the device has a security preference to allow some actions...?

> Real device (xiaomi 5x)

I don't know if such preferences exist, but Chinese phones tend to have such security preference recently.

**Comment by mykola-mokhnach** [comment] 2021-09-13 18:13
Closed as third party issue

**Closed by mykola-mokhnach** 2021-09-13 18:13 UTC
Labels: ThirdParty, UIAutomator2
