### ISSUE TITLE
Appium takes too long to find elements (iOS)

### ISSUE THREAD

**Issue by khubaib321** [appium/appium#13540] opened 2019-11-04 10:47 UTC
## The problem

When the page source is large, Appium takes a huge amount of time just to get one element on screen. As a result tests run very slow and a lot of times TimeOut Exceptions are thrown so the tests are not stable enough.

## Environment

* Appium version: 1.15.0
* Operating system: Mac OS Mojave 10.14.5
* Node version is 12.11.1
* Mobile platform/version under test: iOS 13.2
* Using iOS Simulator
* Xcode version: 11.2

## Details

In the app there is a scrolling list view, which is basically a search results page. The result list keeps populating in the background as data is returned, so the it keeps growing until the search is complete. This list reaches up-to 1000 results or even exceeds that sometimes.
Another example is a Map view which has lots of points of interest shown as pins on the map. User can tap on a pin and it shows the relevant information.

On the Android side this is not an issue as only those elements are returned which are displayed on the screen. So even with a 1000+ results only 3-5 results are fetched which are visible on the screen.
On iOS side Appium gets full page source and this includes all elements on the page (visible or invisible). The desktop version gets stuck on inspection page, keeps working to get page source and takes minutes and does not return proper XML. As a workaround I have tried using another app inspector ([Macaca](https://macacajs.github.io/app-inspector/)) which works but its only for inspection. Now after inspection and figuring out the proper locator strategy, when it comes to finding elements on screen none of the strategies help. I guess this is because Appium cannot get the page source in the first place so it cannot move forward to find elements on the page.

Locator strategies I have tried:
- Accessibility ID
- Class Name
- iOS Predicate
- iOS Class Chain
- xPath (already not recommended)

Additional things that I have tried:
- Using the `useJSONSource` desired capability (https://appiumpro.com/editions/24).
- Using the `simpleIsVisibleCheck` desired capability (https://appiumpro.com/editions/24). 

## Link to Appium logs
https://gist.github.com/khubaib321/254b5c9d35f11fc0ebfc808aaf6b3c10

**Comment by mykola-mokhnach** [comment] 2019-11-04 10:55
You could try to enable `useFirstMatch` setting and see if it helps. Also you'll need to make sure your locators are not of `xpath` type and are supposed to find a single element (not multiple) in order for this setting to work as expected. Otherwise I don't have any good solutions since the lookup is done on XCTest side and we have no influence to this process

**Comment by khubaib321** [comment] 2019-11-04 11:15
> You could try to enable `useFirstMatch` setting and see if it helps. Also you'll need to make sure your locators are not of `xpath` type and are supposed to find a single element (not multiple) in order for this setting to work as expected. Otherwise I don't have any good solutions since the lookup is done on XCTest side and we have no influence to this process

On the results page there are unique elements as well, for example a back button, list sorting button. These are single elements on page with their unique ID. So trying to get those with their own accessibility ID takes a lot of time as well. I will check the `useFirstMatch` setting and update here.

**Comment by emzubair** [comment] 2019-11-05 09:48
I'm also facing an issue of this nature, whenever I try to get an element from a page with `XCUIElementTypeTable` if number of results `(XCUIElementTypeCell)` are more than 50 I face `TimeOut` issue even if the element is present on the page. If results are more around 100 `Appium ` gets stuck, no further commands processed.

**Comment by uterator** [comment] 2019-11-05 10:27
From my experience, an element is hardly found if the page content is more than 1200 lines, not sure if it is related directly to Appium but WDA or XCUITest framework.

**Comment by emzubair** [comment] 2019-11-05 11:00
> From my experience, an element is hardly found if the page content is more than 1200 lines, not sure if it is related directly to Appium but WDA or XCUITest framework.

And on the top of it, it also includes off screen elements in iOS, as if there weren't any less issues already.

**Comment by khubaib321** [comment] 2019-11-08 14:41
I have tried using `useFirstMatch` setting but unfortunately did not see any noticeable difference. Getting elements on page by their accessibility ID still takes a lot of time. If the same Android test takes around 2 minutes to complete, then on iOS it takes 10 minutes or more to complete which is very slow. And most of the time difference is found on pages having a large number of elements.

The other app inspector I mentioned ([Macaca](https://macacajs.github.io/app-inspector/)) gets the page source significantly faster than Appium. So that gives me a clue that the issue is probably not on XCTest side. I think the Macaca app inspector uses an implementation of WebDriverAgent ([link](https://github.com/macacajs/XCTestWD)) which seems to be a lot faster in getting the page source. I am wondering if it's possible for Appium to use that to speed up this process?

**Comment by mykola-mokhnach** [comment] 2019-11-08 14:55
Element lookup by Id/class name does not have any additional layers, which could potentially make it slower in WDA. XPath lookup and page source are expected to be slow, since the page source that we generate contains many additional attributes, like visibility, which must be calculated for each node in the tree.

Although we are always open to proposals and pull requests, so if you have any ideas on how to improve the current performance then feel free to contribute.

**Comment by mykola-mokhnach** [comment] 2019-11-08 14:57
Also, there is a possibility in Appium to see the native (fast) XCTest source tree: https://github.com/appium/appium/issues/13160#issuecomment-526676143

**Comment by mykola-mokhnach** [comment] 2019-11-08 15:13
> The other app inspector I mentioned (Macaca) gets the page source significantly faster than Appium. So that gives me a clue that the issue is probably not on XCTest side. I think the Macaca app inspector uses an implementation of WebDriver (link) which seems to be a lot faster in getting the page source. I am wondering if it's possible for Appium to use that to speed up this process?

I did check Macaca's WDA sources and it looks like a very simple algorithm for element visibility detection is used there (which does not always return precise results). Also, the invisible blocks are being automatically excluded from the page source, which speeds up the process as well.

**Comment by mykola-mokhnach** [comment] 2019-11-08 15:17
I remember one more possible workaround: https://github.com/appium/WebDriverAgent/pull/181

Check your device logs if they contain `Cannot take the snapshot of ...` traces. If yes then increase the default snapshot timeout (`snapshotTimeout`)  setting value, which is 15 seconds by default

**Comment by mykola-mokhnach** [comment] 2019-11-10 08:40
Closed as third party issue

**Closed by mykola-mokhnach** 2019-11-10 08:40 UTC
Labels: ThirdParty, XCUITest

**Comment by sandaliqbal1** [comment] 2019-11-11 07:09
I'm also facing the same issue. Can you tell me how to use the useFirstMatch setting? Should it be set as a capability?

**Comment by khubaib321** [comment] 2019-11-11 07:23
> I'm also facing the same issue. Can you tell me how to use the useFirstMatch setting? Should it be set as a capability?

`useFirstMatch` is a session setting. See documentation links:
http://appium.io/docs/en/advanced-concepts/settings/index.html
http://appium.io/docs/en/commands/session/settings/update-settings/

**Comment by sandaliqbal1** [comment] 2019-11-11 09:46
These are the settings I see in my java client version 7.0.0:

    IGNORE_UNIMPORTANT_VIEWS("ignoreUnimportantViews"),
    WAIT_FOR_IDLE_TIMEOUT("waitForIdleTimeout"),
    WAIT_FOR_SELECTOR_TIMEOUT("waitForSelectorTimeout"),
    WAIT_SCROLL_ACKNOWLEDGMENT_TIMEOUT("scrollAcknowledgmentTimeout"),
    WAIT_ACTION_ACKNOWLEDGMENT_TIMEOUT("actionAcknowledgmentTimeout"),
    KEY_INJECTION_DELAY("keyInjectionDelay"),
    NATIVE_WEB_TAP("nativeWebTap"),
    IMAGE_MATCH_THRESHOLD("imageMatchThreshold"),
    FIX_IMAGE_FIND_SCREENSHOT_DIMENSIONS("fixImageFindScreenshotDims"),
    FIX_IMAGE_TEMPLATE_SIZE("fixImageTemplateSize"),
    CHECK_IMAGE_ELEMENT_STALENESS("checkForImageElementStaleness"),
    UPDATE_IMAGE_ELEMENT_POSITION("autoUpdateImageElementPosition"),
    NORMALIZE_TAG_NAMES("normalizeTagNames"),
    IMAGE_ELEMENT_TAP_STRATEGY("imageElementTapStrategy");

**Comment by sandaliqbal1** [comment] 2019-11-12 04:21
@mykola-mokhnach it would be great if we could speed findElements on ios simulator at least as that makes test 2-3 times slower on ios than on android. Maybe an alternative better way of getting page source.

**Comment by vzenzo** [comment] 2020-08-10 05:59
Why are these issues getting closed while problem isn't solved? 

I haven't found one solution to slow ios testing, where can I find a solution because none of these work

**Comment by emzubair** [comment] 2020-09-30 13:55
> Why are these issues getting closed while problem isn't solved?
> 
> I haven't found one solution to slow ios testing, where can I find a solution because none of these work
> The useFirstMatch is not recognized by Appium

@vzenzo in `iOS` element is searched from top to bottom in the `XML` tree, so whenever the first match is found it returns that element so `userFirstMatch` is the default behaviour in `iOS`. 
The main issue remains in place, in case of large `XML` it is quite slow to find the element.

**Comment by vivek-git-checkout** [comment] 2023-02-05 19:59
Still facing this problem, using latest Appium 2.0 Beta. Appium takes too long to find element or timeout if page is big (even below the fold elements shows up in page source). Even page is smaller, sometime it takes ~700ms to find element and sometimes it takes ~32000ms for the same element on same page. Very inconsistent. This causes our test run to take sometimes 1 hour and sometimes 4-5 hours to complete.

**Comment by uterator** [comment] 2023-02-06 09:15
@vivek-git-checkout can you give more information about how much "big" is the page? how many lines has the page source? how much is the maximum hierarchy depth of the page?, which locator strategy is used?

**Comment by babar-igor** [comment] 2023-11-30 13:37
Hi @vivek-git-checkout,
Have you resolved your issue? I'm still experiencing the same problem for  long time. Appium hangs on the "big" pages.
If yes, could you please share the solution?

p.s. I use the last version of Appium (2.2.2), but tried the previous ones as well - the issue is still reproduced anyway on iOS.
