### ISSUE TITLE
element identifiers not working in IOS 13.1 Appium v1.15.0, betav1.16

### ISSUE THREAD

**Issue by abilashkar** [appium/appium#13358] opened 2019-10-04 09:38 UTC
## The problem

element identifiers Xpath, Id is not working properly. It is failing by the identifier not found. but the element Identifier is visible on the screen.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.15.0, betav1.16
* Last Appium version that did not exhibit the issue (if applicable): Appium v1.14.0, beta v1.14
* Desktop OS/version used to run Appium: IOS 13.0
* Node.js version (unless using Appium.app|exe): v10.15.3
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Mobile Platform
* Real device or emulator/simulator: Real device 
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2019-10-04 10:08
Possible duplicate of https://github.com/appium/appium/issues/13341

The current issue description is not helpful and requires logs/screenshots/comparison and all the necessary details to figure out the possible cause.

**Comment by abilashkar** [comment] 2019-10-06 04:56
as per   #13341 comments I have checked the page source that path was not fount in page source. using Appium 1.14 inspector the element is displayed. Also I noticed one more issue 
using clear method the text field is not getting cleared. 
driver.findElement(By.xpath("****")).clear(); //this is not working 
driver.findElement(By.xpath("****")).sendKeys(""); // this is working  same text field .


I have requested  to the management for logs/screenshots/ Bec of security policy it cannot be posted Open.  for sharing log/screenshot give me some time.

**Comment by abilashkar** [comment] 2019-10-06 05:18
in a web page given xpath is available Appium is not identifying 
<img width="1000" alt="Screenshot 2019-10-06 at 10 41 44 AM" src="https://user-images.githubusercontent.com/18739593/66264639-d87d4380-e826-11e9-9a62-085c94cb5f26.png">

[debug] [iOS] Checking if page needs to load
[debug] [iOS] New page listing is same as old, doing nothing
[debug] [iOS] Redirected from '****'
[HTTP] --> POST /wd/hub/session/4077233a-f5c3-4d2d-a385-4fc790d5bed8/element
[HTTP] {"using":"xpath","value":"//select[@name='fqdn_tenantid']"}
[debug] [W3C (4077233a)] Calling AppiumDriver.findElement() with args: ["xpath","//select[@name='fqdn_tenantid']","4077233a-****-****-****-*********"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [RemoteDebugger] Executing atom 'find_element'
[debug] [RemoteDebugger] Executing 'find_element' atom in default context
[debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var k=this;functi...'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:1156', page '1', target 'page-6' (id: 32)
[Xcode] 2019-10-06 10:38:14.452 xcodebuild[4353:199333] Error Domain=com.apple.platform.iphoneos Code=-13 "Lost connection to DTServiceHub" UserInfo={NSLocalizedDescription=Lost connection to DTServiceHub}
[Xcode] 
[Xcode] 
[Xcode] Test session results, code coverage, and logs:
[Xcode] 	/Users/a-7944/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs/Test/Test-WebDriverAgentRunner-2019.10.06_10-32-47-+0530.xcresult
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 	WebDriverAgentRunner:
[Xcode] 		testRunner encountered an error (Encountered a problem with the test runner after launch. (Underlying error: Lost connection to DTServiceHub))
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode]

**Comment by abilashkar** [comment] 2019-10-06 05:21
in page application same issue is present 

[debug] [iOS] Checking if page needs to load
[debug] [iOS] New page listing is same as old, doing nothing
[debug] [iOS] Redirected from '*********'
[HTTP] --> POST /wd/hub/session/4077233a-*****
<img width="1010" alt="Screenshot 2019-10-06 at 10 51 12 AM" src="https://user-images.githubusercontent.com/18739593/66264658-40cc2500-e827-11e9-97d8-f0ee791ac5f5.png">
-****-****-************/element
[HTTP] {"using":"xpath","value":"//select[@name='fqdn_tenantid']"}
[debug] [W3C (4077233a)] Calling AppiumDriver.findElement() with args: ["xpath","//select[@name='fqdn_tenantid']","4077233a-f5c3-4d2d-a385-4fc790d5bed8"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [RemoteDebugger] Executing atom 'find_element'
[debug] [RemoteDebugger] Executing 'find_element' atom in default context
[debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var k=this;functi...'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:1156', page '1', target 'page-6' (id: 32)
[Xcode] 2019-10-06 10:38:14.452 xcodebuild[4353:199333] Error Domain=com.apple.platform.iphoneos Code=-13 "Lost connection to DTServiceHub" UserInfo={NSLocalizedDescription=Lost connection to DTServiceHub}
[Xcode] 
[Xcode] 
[Xcode] Test session results, code coverage, and logs:
[Xcode] 	/Users/a-7944/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs/Test/Test-WebDriverAgentRunner-2019.10.06_10-32-47-+0530.xcresult
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 	WebDriverAgentRunner:
[Xcode] 		testRunner encountered an error (Encountered a problem with the test runner after launch. (Underlying error: Lost connection to DTServiceHub))
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode]

**Comment by abilashkar** [comment] 2019-10-06 05:23
in page application same issue is present 

[debug] [iOS] Checking if page needs to load
[debug] [iOS] New page listing is same as old, doing nothing
[debug] [iOS] Redirected from '*********'
[HTTP] --> POST /wd/hub/session/4077233a-*****
<img width="1010" alt="Screenshot 2019-10-06 at 10 51 12 AM" src="https://user-images.githubusercontent.com/18739593/66264658-40cc2500-e827-11e9-97d8-f0ee791ac5f5.png">
-****-****-************/element
[HTTP] {"using":"xpath","value":"//select[@name='fqdn_tenantid']"}
[debug] [W3C (4077233a)] Calling AppiumDriver.findElement() with args: ["xpath","//select[@name='fqdn_tenantid']","4077233a-f5c3-4d2d-a385-4fc790d5bed8"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [RemoteDebugger] Executing atom 'find_element'
[debug] [RemoteDebugger] Executing 'find_element' atom in default context
[debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var k=this;functi...'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:1156', page '1', target 'page-6' (id: 32)
[Xcode] 2019-10-06 10:38:14.452 xcodebuild[4353:199333] Error Domain=com.apple.platform.iphoneos Code=-13 "Lost connection to DTServiceHub" UserInfo={NSLocalizedDescription=Lost connection to DTServiceHub}
[Xcode] 
[Xcode] 
[Xcode] Test session results, code coverage, and logs:
[Xcode] 	/Users/a-7944/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs/Test/Test-WebDriverAgentRunner-2019.10.06_10-32-47-+0530.xcresult
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 	WebDriverAgentRunner:
[Xcode] 		testRunner encountered an error (Encountered a problem with the test runner after launch. (Underlying error: Lost connection to DTServiceHub))
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 

<img width="1010" alt="Screenshot 2019-10-06 at 10 51 12 AM" src="https://user-images.githubusercontent.com/18739593/66264670-812ba300-e827-11e9-847b-f96f941b1944.png">

**Comment by KazuCocoa** [comment] 2019-10-07 03:39
https://github.com/appium/appium/issues/13288 could happen if you use Xcode 11 and iOS 12 combination. Which Xcode version did you use?

https://github.com/appium/appium/issues/13270 might resolve the safari case?

**Comment by abilashkar** [comment] 2019-10-07 04:37
@KazuCocoa Xcode version Version 11.0 (11A420a) 
MACOS : 10.14.4 (18E226)
Ipad OS: 13.1.2

**Comment by KazuCocoa** [comment] 2019-10-07 05:03
Thanks.

Not sure your query in `driver.findElement(By.xpath("")).clear()`, but what about getting the text field by `XCUIElementTypeTextField`?

iOS 13 returns different source tree than iOS 12 (returned values by Apple's framework has been changed). I saw a case wich has two different element type names, `XCUIElementTypeTextField` and `XCUIElementTypeOther`, when they had the same value. Then, it was needed to specify `XCUIElementTypeTextField` to get text field element.
This possible case could happen.

https://github.com/appium/appium/issues/13288

**Comment by abilashkar** [comment] 2019-10-07 07:48
@KazuCocoa we issue got resolved Thanks you very much. 

Now working on native application will look into the suggestion and get back if the change Is happened then we have to change all the elements according to XCUIElemtType

**Comment by mykola-mokhnach** [comment] 2019-10-07 12:22
Closed as not an issue

**Closed** 2019-10-07 12:22 UTC
Labels: NeedsInfo

**Comment by Satyam-Kumar1** [comment] 2020-02-13 14:32
> @KazuCocoa we issue got resolved Thanks you very much.
> 
> Now working on native application will look into the suggestion and get back if the change Is happened then we have to change all the elements according to XCUIElemtType

@abilashkar Could you please let me know how the issue resolved as we are getting the same.

**Comment by vzenzo** [comment] 2020-08-07 10:02
This is still not working
