### ISSUE TITLE
Capturing incorrect coordinates of element and then translating web coordinates to real coordinates and not click on proper element (iOS Safari)

### ISSUE THREAD

**Issue by jwsargent** [appium/appium#6428] opened 2016-04-21 20:37 UTC
## The problem

Appium is capturing incorrect x&y coordinates of mobile web elements and then translating the web coordinates that I am attempting to click on to real coordinates which will not click on the desired element. Appium can see the element and the number of those elements with the same class, but when I attempt to actually click on one of them the coordinates are off-- the click will occur elsewhere on the screen or completely off the screen which will yield a message that the coordinates are not on the screen. 
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.0
- Last Appium version that did not exhibit the issue (if applicable): N/A
- Desktop OS/version used to run Appium: OS X 10.11.4
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: 4.4.1
- Real device or emulator/simulator: iOS Simulator iOS 9.3 and real device 
- Appium CLI or Appium.app|exe:
## Details

When I attempt to click on an element on the screen, I cannot click on this particular item. I have found that it is converting the web coordinates to real coordinates, which is altering the Y axis value of the click (sometimes it will even translate it to be a negative number example- x: 60, y: -541)
## Link to Appium logs

<script src="https://gist.github.com/jwsargent/be6092bd28b5ba46652764347d4655fb.js"></script>

**Comment by jwsargent** [comment] 2016-04-21 21:15
Appium logs: https://gist.github.com/jwsargent/be6092bd28b5ba46652764347d4655fb

**Comment by jwsargent** [comment] 2016-04-22 15:06
To follow up, find_elements(:class, "class_name")[1].location shows x-71, y=287, then when I attempt the click function Appium translates the coordinates to web coordinates (x=94, y=286) and THEN it converts the web coordinates into real coordinates (x=94, y= -15).

Is there a way to disable or modify this translation? Or is there a reason why this translation is taking place?

Thanks!

**Comment by imurchie** [comment] 2016-04-22 15:38
Thanks for the detailed report. I will take a look!

**Comment by imurchie** [comment] 2016-04-22 15:43
To clarify, since the logs are only partial, you are doing

```
el = find_elements(:class, "class_name")[1]
el.click()
```

or somesuch? And this is in a web context? Like Safari? Or a webview within a hybrid app?

**Comment by jwsargent** [comment] 2016-04-22 15:45
Exactly. And yes, it is on a webpage within an iOS simulator.

**Comment by imurchie** [comment] 2016-04-22 15:46
Thanks! That makes things easier!

**Comment by jwsargent** [comment] 2016-04-22 15:48
No problem, thank you! I found a translateWebCoords function in the web.js file that I suspect may be part of the problem? Not seeing how its actually manipulating the coordinate values though.

**Comment by imurchie** [comment] 2016-04-22 15:52
It's in the `nativeWebTap` method. I'm surprised this is happening on a real device, since it ought to be turned off for that.

**Comment by jwsargent** [comment] 2016-04-22 15:59
I have nativeWebTap set to true, I found that I wasn't able to click on anything when it was false. 

In that method, I am seeing: 
`x = x + (width / 2);
  y = y + (height / 2);` 
Would removing the `(width/2)` allow it to click on the absolute value of x and y? 
Also, and Im not sure if this is outside of this particular issue, I am noticing that the y values are dynamic based upon where elements show up in the simulator (example: if you scroll down on the screen, the y value of the targeted element changes). Is there any way to make these values absolute as well?

**Comment by imurchie** [comment] 2016-04-22 16:27
No those lines are just making sure that the tap is in the center of the element. We get the top left coordinates, then the size of the element, and from that, the center.

The y value is necessarily dynamic, since on a scroll elements move up and down on the y axis.

**Comment by imurchie** [comment] 2016-04-22 16:29
Are you scrolling before this click (this is why the full logs are generally requested)?

The problem I'm seeing is that Instruments returns the following for the rectangle of the webview: `{"status":0,"value":{"origin":{"x":0,"y":-564},"size":{"width":424,"height":2000}}}`. This means it is saying that the webview began at `-564` on the vertical.

**Comment by jwsargent** [comment] 2016-04-22 16:32
I was not scrolling to that point before attempting to click. However, if I manually move the simulator to have the element in the middle of the screen, it still cannot click on it. Do happen to know offhand what the scroll to command would be in Ruby?

**Comment by jwsargent** [comment] 2016-04-22 16:33
So when you scroll down, it makes the top point of the page negative? I have attempted to get the location of it when it is above the screen and it will only show the y value as 0, I have not been able to replicate it being negative outside of the click command.

**Comment by imurchie** [comment] 2016-04-22 18:04
I have a reproducing case. I'll try to figure out a solution.

**Comment by jwsargent** [comment] 2016-04-22 20:46
Great, thank you @imurchie!

**Comment by imurchie** [comment] 2016-04-24 03:00
Older Xcode does not work, either. :(

This does not help, but I wanted to document.

**Comment by jwsargent** [comment] 2016-05-10 20:05
Hi @imurchie @scottdixon, any update on this issue? Thanks!

**Comment by mzbedat** [comment] 2016-12-21 10:15
Hi,
Any resolution for this issue?
I'm facing a similar issue: [appium library #147](https://github.com/serhatbolsu/robotframework-appiumlibrary/issues/147#issuecomment-268484827)

BR

**Comment by vfennerac** [comment] 2017-02-02 20:05
I have a similar issue, but I am working with WebdriverIO + appium

Calling the click command for the same element twice actually fixes the issue for me. On checking the logs I noticed that the elements had different coordinates. Here is the relevant log part:
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","sup-j-profile-addButton-WorkingExperiences","46f6efca-f60e-4a18-881f-47ed73c333ec"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [RemoteDebugger] Executing 'find_element' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var l=this;functi...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Received applicationSentData response
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":{"ELEMENT":":wdc:1486064428...'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1486064428971"}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"5015"}
[HTTP] <-- POST /wd/hub/session/46f6efca-f60e-4a18-881f-47ed73c333ec/element 200 506 ms - 90 
[HTTP] --> POST /wd/hub/session/46f6efca-f60e-4a18-881f-47ed73c333ec/element/5015/click {}
[debug] [MJSONWP] Calling AppiumDriver.click() with args: ["5015","46f6efca-f60e-4a18-881f-47ed73c333ec"]
[debug] [XCUITest] Executing command 'click'
[debug] [RemoteDebugger] Executing 'get_top_left_coordinates' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var h,l=this;func...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Received applicationSentData response
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":{"x":73.75,"y":0,"clone":"f...'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] Received result for atom 'get_top_left_coordinates' execution: {"x":73.75,"y":0}
[debug] [RemoteDebugger] Executing 'get_size' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var g,l=this;func...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Received applicationSentData response
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":{"width":265,"height":28}}'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] Received result for atom 'get_size' execution: {"width":265,"height":28}
[debug] [XCUITest] Translating coordinates ({"x":206.25,"y":14}) to web coordinates
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/F12845F9-2BB7-46A5-A35D-4508531BB3B7/elements] with body: {"using":"class name","value":"XCUIElementTypeWebView"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"CDD6C7C0-4DDD-4098-AC17-02F5EC318434","type":"XCUIElementTypeWebView","label":null}],"sessionId":"F12845F9-2BB7-46A5-A35D-4508531BB3B7","status":0}
[XCUITest] Could not find webview at index 18417.1, taking last available one for clicking purposes
[debug] [JSONWP Proxy] Proxying [GET /element/CDD6C7C0-4DDD-4098-AC17-02F5EC318434/rect] to [GET http://localhost:8100/session/F12845F9-2BB7-46A5-A35D-4508531BB3B7/element/CDD6C7C0-4DDD-4098-AC17-02F5EC318434/rect] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 0,\n    \"x\" : 0,\n    \"width\" : 375,\n    \"height\" : 667\n  },\n  \"sessionId\" : \"F12845F9-2BB7-46A5-A35D-4508531BB3B7\",\n  \"status\" : 0\n}"
[debug] [RemoteDebugger] Sending javascript command (function () { return {w: document.documentElem...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Received applicationSentData response
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"w":375,"h":559}'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [XCUITest] Converted web coords {"x":206.25,"y":14} into real coords {"x":206,"y":78}
[debug] [JSONWP Proxy] Proxying [POST /tap/nil] to [POST http://localhost:8100/session/F12845F9-2BB7-46A5-A35D-4508531BB3B7/tap/nil] with body: {"x":206,"y":78}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"F12845F9-2BB7-46A5-A35D-4508531BB3B7","status":0}
[debug] [MJSONWP] Responding to client with driver.click() result: null
[HTTP] <-- POST /wd/hub/session/46f6efca-f60e-4a18-881f-47ed73c333ec/element/5015/click 200 3861 ms - 76 
[HTTP] --> POST /wd/hub/session/46f6efca-f60e-4a18-881f-47ed73c333ec/element {"using":"id","value":"sup-j-profile-addButton-WorkingExperiences"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","sup-j-profile-addButton-WorkingExperiences","46f6efca-f60e-4a18-881f-47ed73c333ec"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [RemoteDebugger] Executing 'find_element' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var l=this;functi...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Received applicationSentData response
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":{"ELEMENT":":wdc:1486064428...'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1486064428971"}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"5016"}
[HTTP] <-- POST /wd/hub/session/46f6efca-f60e-4a18-881f-47ed73c333ec/element 200 507 ms - 90 
[HTTP] --> POST /wd/hub/session/46f6efca-f60e-4a18-881f-47ed73c333ec/element/5016/click {}
[debug] [MJSONWP] Calling AppiumDriver.click() with args: ["5016","46f6efca-f60e-4a18-881f-47ed73c333ec"]
[debug] [XCUITest] Executing command 'click'
[debug] [RemoteDebugger] Executing 'get_top_left_coordinates' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var h,l=this;func...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Received applicationSentData response
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":{"x":73.75,"y":346,"clone":...'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] Received result for atom 'get_top_left_coordinates' execution: {"x":73.75,"y":346}
[debug] [RemoteDebugger] Executing 'get_size' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var g,l=this;func...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Received applicationSentData response
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":{"width":265,"height":28}}'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] Received result for atom 'get_size' execution: {"width":265,"height":28}
[debug] [XCUITest] Translating coordinates ({"x":206.25,"y":360}) to web coordinates
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/F12845F9-2BB7-46A5-A35D-4508531BB3B7/elements] with body: {"using":"class name","value":"XCUIElementTypeWebView"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"27DF7D99-3D4E-45AA-8709-3AB4C56485E5","type":"XCUIElementTypeWebView","label":null}],"sessionId":"F12845F9-2BB7-46A5-A35D-4508531BB3B7","status":0}
[XCUITest] Could not find webview at index 18417.1, taking last available one for clicking purposes
[debug] [JSONWP Proxy] Proxying [GET /element/27DF7D99-3D4E-45AA-8709-3AB4C56485E5/rect] to [GET http://localhost:8100/session/F12845F9-2BB7-46A5-A35D-4508531BB3B7/element/27DF7D99-3D4E-45AA-8709-3AB4C56485E5/rect] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 0,\n    \"x\" : 0,\n    \"width\" : 375,\n    \"height\" : 667\n  },\n  \"sessionId\" : \"F12845F9-2BB7-46A5-A35D-4508531BB3B7\",\n  \"status\" : 0\n}"

**Comment by PaulinkaS** [comment] 2017-03-21 12:58
I am facing the same problem as originally described by @jwsargent while trying to tap on a specific coordinates in Safari. 
Is there any known solution/workaround for this?

**Comment by vfennerac** [comment] 2017-03-21 15:42
@PaulinkaS sometimes sending the click action again corrects the coordinates

**Comment by PaulinkaS** [comment] 2017-03-21 16:05
@vfennerac Unfortunately I need to perform touch-tap action in this case, not click. For this I need correct native coordinates of my web control.

**Comment by dpgraham** [comment] 2017-07-20 21:06
Closing because we don't support Instruments.

**Closed by dpgraham** 2017-07-20 21:06 UTC
Labels: iOS, Real Devices

**Comment by prabha393** [comment] 2018-02-11 14:12
- 

- 

1.

**Comment by jenniferneale** [comment] 2018-05-23 22:15
What do click and tap have to do with Instruments? I am experiencing this problem with Appium 1.8.0, iOS 11.1.
