### ISSUE TITLE
When I am trying to print current page  URL and page source  it is displaying different  URL and page source 

### ISSUE THREAD

**Issue by sushmitha-mk** [appium/appium#12695] opened 2019-05-27 07:37 UTC
## The problem

I am trying to click on the element in android web view where it is showing NoSuchElementFoundException, when i am trying to get the current page url it is displaying different url 

	Set<String> availableContexts = driver.getContextHandles();

		try {
			Thread.sleep(10000);
			System.out.println(availableContexts);
			
				availableContexts = driver.getContextHandles();
			
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		System.out.println(availableContexts);

		if(osName.equalsIgnoreCase("android")) {
		for (String context : availableContexts) {
			
			if (context.contains("WEBVIEW_")) {

				System.out.println(context);
				
				driver.context(context);
				if (driver.getCurrentUrl().contains("URL")) {
					System.out.println("Current Context: ------------------------------------------------ " + driver.getContext());
					System.out.println("Current url: -----------------------------------------" + driver.getCurrentUrl());
					
				}

				else {
					System.out.println("Current Context: +++++++++++++++++++++++++++++++++++++ " + driver.getContext());

					//System.out.println("Current url: ++++++++++ " +driver.getCurrentUrl());
					break;
				
			}

Also it is displaying different page source 

driver.getPageSource();

## Environment

* Appium version 1.12.1
* Desktop OS/version used to run Appium: windows 10
* Mobile platform/version under test: android 5.0 and above
* Real device or emulator/simulator: Real device

## Link to Appium logs

https://gist.github.com/sushmitha-mk/cc678b35d948c59718927c1902e710f4

**Comment by mykola-mokhnach** [comment] 2019-05-27 07:47
Is it duplicate of https://github.com/appium/appium/issues/12635 ?

**Comment by sushmitha-mk** [comment] 2019-05-27 10:04
@mykola-mokhnach  No, #12635  is different issue there I have mentioned that I am not able to switch the context from native to web view, Here available contexts are [NATIVE_APP, WEBVIEW_com.xxx.xxxapp] I can able to switch the context to web view context

**Comment by mykola-mokhnach** [comment] 2020-09-30 14:17
Closed as inactive

**Closed by mykola-mokhnach** 2020-09-30 14:17 UTC
Labels: Mobile Chrome, UIAutomator2
