### ISSUE TITLE
Getting timed out error when running appium inspector

### ISSUE THREAD

**Issue by dinesha87** [appium/appium#16060] opened 2021-11-09 23:57 UTC
## The problem

I tried with both app and desktop version of new appium inspector but no luck. Every-time app is loading in simulator but i’m getting timeout error from appium inspector. 

## Environment

- macOS-11.6
- appium server GUI - v1.22.0
- appium inspector - 2021.9.2

## Details

When running the tests using selenium all the tests are working, but when i tried to run the appium inspector getting timed out error and simulator snapshot is not loading in inspector

## Link to Appium logs

https://gist.github.com/dinesha87/ee7f64a7dbd49a850d37383ff857a1f7

## Appium inspector setting as below.

![Capability](https://user-images.githubusercontent.com/56371935/141024505-ff6ce24d-1eed-409b-b6c0-f9aa63b102b2.png)

![Inspector](https://user-images.githubusercontent.com/56371935/141024522-35fe9703-9935-4b15-ba67-9901d3f8ddf6.png)

**Comment by mykola-mokhnach** [comment] 2021-11-10 06:54
Duplicate of https://github.com/appium/appium/issues/16015

Consider using older Xcode SDK and, probably, older Appium releases for older Simulator platforms

**Closed by mykola-mokhnach** 2021-11-10 06:54 UTC
