### ISSUE TITLE
.find_element_by_xpath() not working after .find_element_by_name()

### ISSUE THREAD

**Issue by Diolor** [appium/appium#4774] opened 2015-03-25 10:07 UTC
The following has been tested with both python and Appium Gui for Macs and fails:

Here is a python test:

```
class NavigationTest(unittest.TestCase):
    def setUp(self):
        self.wd = webdriver.Remote('http://0.0.0.0:4723/wd/hub', desired_caps)

    def tearDown(self):
        self.wd.quit()

    def test_forgot_password_up_button(self):
        self.wd.find_element_by_name(login).click()
        self.wd.find_element_by_xpath(forgot_password).click()
```

Assuming above that the login is a `Login` string and forgot_password a xpath string.

The first command animates an Android fragment while the second finds a element on the new fragment and clicks it.

The above tests fails on the last line because it couldn't find an element. Is that a bug or should I insert some kind of "wait" mechanism before the second command?

Log:
```
info: --> POST /wd/hub/session/088b2039-dc8f-43d9-a020-753db14d5c8e/element {"using":"name","value":"Login"}

info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"name","selector":"Login","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"name","selector":"Login","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding Login using NAME with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[DESCRIPTION=Login, INSTANCE=0]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"ELEMENT":"10"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"10"},"sessionId":"088b2039-dc8f-43d9-a020-753db14d5c8e"}
info: <-- POST /wd/hub/session/088b2039-dc8f-43d9-a020-753db14d5c8e/element 200 53.971 ms - 88 {"status":0,"value":{"ELEMENT":"10"},"sessionId":"088b2039-dc8f-43d9-a020-753db14d5c8e"}
info: --> POST /wd/hub/session/088b2039-dc8f-43d9-a020-753db14d5c8e/element/10/click {}
info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"10"}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"10"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: click
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"088b2039-dc8f-43d9-a020-753db14d5c8e"}
info: <-- POST /wd/hub/session/088b2039-dc8f-43d9-a020-753db14d5c8e/element/10/click 200 291.988 ms - 76 {"status":0,"value":true,"sessionId":"088b2039-dc8f-43d9-a020-753db14d5c8e"}
info: --> POST /wd/hub/session/088b2039-dc8f-43d9-a020-753db14d5c8e/element {"using":"xpath","value":"//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2]"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"xpath","selector":"//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2]","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2]","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding //android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2] using XPATH with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":7,"value":"Could not find an element using supplied strategy. "}
info: [debug] Condition unmet after 80ms. Timing out.
info: [debug] Responding to cli
ent with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":"Could not find an element using supplied strategy. "},"sessionId":"088b2039-dc8f-43d9-a020-753db14d5c8e"}
info: <-- POST /wd/hub/session/088b2039-dc8f-43d9-a020-753db14d5c8e/element 500 81.358 ms - 230 
info: --> GET /wd/hub/session/088b2039-dc8f-43d9-a020-753db14d5c8e/source {}
info: [debug] Pushing command to appium work queue: ["source",{}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"source","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: source
```

**Comment by amedvedjev** [comment] 2015-03-25 18:07
you can increase default driver timeout to whatever like e.g. with Java - driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS) or Python like driver.manage.timeouts.implicit_wait = 30

**Comment by sebv** [comment] 2015-06-03 13:48
The `find` commands are synchronous, the `click` commands are not, so you need a wait mechanism after the `click`.

**Comment by Diolor** [comment] 2015-06-04 08:59
@sebv Oh, I see. I think there is no callback mechanism, right?
Would it not be a good idea to have a callback when click is performed? Is it possible to be implemented?

**Comment by sebv** [comment] 2015-06-04 09:31
I don't think there is a way to implement "click is performed" in a generic way?

**Comment by sebv** [comment] 2015-06-10 06:05
Closing, not a bug.

**Closed by sebv** 2015-06-10 06:05 UTC
Labels: OnGoing
