### ISSUE TITLE
iOS 13.3 Appium not responding after switchContext to WebView

### ISSUE THREAD

**Issue by markdon** [appium/appium#13809] opened 2020-01-08 01:41 UTC
## The problem

Appium stops responding after attempting to switchContext('WEBVIEW...').

## Environment

* Appium version: 1.16.0
* Node.js version: 10.17.0
* Npm: 6.13.3
* Mobile platform/version under test: iOS 13.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI via webdriver.io

## Details

In my setup I have a cordova app that successfully installs and launches. When attempting to switch to the webview context, Appium stops responding. The POST requests to /context time out. 

Might be a wdio thing but if I enter debug first (`browser.debug()`) and `browser.switchContext('WEBVIEW...')` no response is received, further commands are ignored.

This issue does not occur on an iOS 13.2.2 simulator. [Here's how to install older simulators if you need to get around this](https://stackoverflow.com/a/8477254/4853706).

Similar to #13361 and #13799 but they're running older iOS versions.

## Link to Appium logs

[Appium and wdio logs](https://gist.github.com/markdon/fa2d986126a1207199acc78d31e26ef7)

## Code To Reproduce Issue [ Good To Have ]
This is using the wdio cli with Mocha. You probably get the idea of what it's doing otherwise.

``` javascript
let pollCount = 0;
const pollForWebview = async () => {
    const contexts = await browser.getContexts();
    const webContext = contexts.find(context => context.startsWith('WEBVIEW'));
    if(webContext) return webContext;
    if(pollCount < 3) return browser.pause(1000).then(pollForWebview);
}

describe('app:', () => {
    it('loads', async () => {
        console.log('hello!');
        const webContext = await pollForWebview();
        await browser.switchContext(webContext);
        const context = await browser.getContext();
        console.log(context);
    });
});
```

**Comment by mykola-mokhnach** [comment] 2020-01-08 06:49
Possible duplicate of https://github.com/appium/appium/issues/13799

**Comment by imurchie** [comment] 2020-01-08 15:19
Is this just a basic Cordova app? 

Can you run with timestamps on (start the server with `--log-timestamps`) and post the logs?

**Comment by markdon** [comment] 2020-01-09 04:07
> Is this just a basic Cordova app?

I couldn't reproduce this in a brand new cordova project so I started narrowing down the cause in my project. Eventually I found that there needs to be an `<input type='text'>` (maybe others too) element on the page. So I build a [minimal cordova project](https://github.com/markdon/cordova-sample) that reproduces the issue. 

I think there are a few environment prerequisites to build and run (latest xcode, brew, xcode cli tools, node) but if those are all available, the project can be run with just a few steps in the [readme](https://github.com/markdon/cordova-sample/blob/master/README.md). 

If it's useful, here's [my .app](https://iswaus-my.sharepoint.com/:f:/g/personal/mark_kudosapps_com/Et2j3EOCTWhEpfrKrWBK6TQBaI3W-nv69i-r_-70C9KNng?e=BKzaKf).

> Can you run with timestamps on (start the server with `--log-timestamps`) and post the logs?

[New logs from this basic cordova app are here](https://gist.github.com/markdon/55f474618f0e3b0a1c30614898521655)

**Comment by markdon** [comment] 2020-01-09 04:32
I noticed that when I switch between running each app with Appium, sometimes they actually work the first time. Subsequent runs of the same app stop at switchContext.

**Comment by imurchie** [comment] 2020-01-09 14:19
Thanks for getting this together! I will see what I can do!

**Comment by imurchie** [comment] 2020-01-10 14:23
@markdon Can you try with the latest beta of Appium? It should have `appium-remote-debugger@7.5.0`.

**Comment by markdon** [comment] 2020-01-13 01:16
`npm i -g appium@beta` gave me the versions below. 
```
└─┬ appium@1.16.0-beta.3
  ├─┬ appium-flutter-driver@0.0.20
  │ └─┬ appium-xcuitest-driver@2.133.1
  │   └── appium-remote-debugger@5.7.0 
  ├─┬ appium-ios-driver@4.5.0
  │ └── appium-remote-debugger@4.5.0 
  └─┬ appium-xcuitest-driver@3.12.0
    └── appium-remote-debugger@7.5.1
```

The test now gets  past switchContext, getContext also returns, but further commands are unresponsive. Maybe this is a different issue. I've updated the test in the repo to set the value of the input. [Logs for this are here](https://github.com/markdon/cordova-sample/tree/master/testing/artifacts/logs).

**Comment by imurchie** [comment] 2020-01-15 16:44
Can you update to the latest of everything (`appium-webdriveragent@2.5.2` and `appium-remote-debugger@7.5.1`)? 

Also try adding `safariGarbageCollect` capability, set to `true`.

**Comment by markdon** [comment] 2020-01-16 07:40
npm i -g appium@beta gave me the versions below.

```
└─┬ appium@1.16.0-beta.3
  ├─┬ appium-flutter-driver@0.0.20
  │ └─┬ appium-xcuitest-driver@2.133.1
  │   ├── appium-remote-debugger@5.7.0 
  │   └── appium-webdriveragent@1.3.5 
  ├─┬ appium-ios-driver@4.5.0
  │ └── appium-remote-debugger@4.5.0 
  └─┬ appium-xcuitest-driver@3.12.1
    ├── appium-remote-debugger@7.5.1  <---
    └── appium-webdriveragent@2.5.2    <---
```
Tested both the test app and my prod app. All my tests ran perfectly! 👌
Seems to work without `safariGarbageCollect : true`. 

Thanks @imurchie ! It's really nice to be able to get something fixed so quickly! I hope I helped!

**Comment by mykola-mokhnach** [comment] 2020-01-16 09:33
Closed as fixed

**Closed by mykola-mokhnach** 2020-01-16 09:33 UTC
Labels: Mobile Safari

**Comment by imurchie** [comment] 2020-01-16 14:25
Excellent! Glad it got working!
