### ISSUE TITLE
Appium 1.6.4 taking too much of time to find element

### ISSUE THREAD

**Issue by shyam27** [appium/appium#8322] opened 2017-04-25 10:39 UTC
## The problem

Appium takes more time to Find element. In our mobile app there is a form which contains multiple fields as it doing sendkeys to first element little faster coming to next field to identify, its taking minimum 5mins to identify element. 

In some of the posts found that if we downgrade the appium-xcuitest-driver to 2.15.0 version it will work.

Tried to downgrade, while building WDA getting Error :  'openURL:' deprecated.

Currently Appium version is 1.6.4 and appium-xcuitest-driver version is  2.27.

Please help me to how to fasten my tests

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Desktop OS/version used to run Appium: 10.12.1
* Node.js version (unless using Appium.app|exe): 7.9.0
* Mobile platform/version under test: 10.3.1
* Real device or emulator/simulator: iPad

## Link to Appium logs

https://gist.github.com/shyam27/74a802167499f0370c36f93b69652016

**Comment by mykola-mokhnach** [comment] 2017-04-25 10:50
1. Avoid using xpath locators Try to use location by predicates or class chain where possible.
2. I see several "Enqueue Failure: UI Testing Failure - Failure fetching attributes" errors in the log. They seriously slow down elements lookup, since there is hardcoded 15s delay after each log record of such type. These are caused by XCTest itself and cannot be fixed on Appium side. You may report this either to Apple issue tracker or to https://github.com/facebook/WebDriverAgent/issues
3. Try to limit search scope by using nested searches.
4. Try to cache as much stuff as possible to minimize the count of WDA calls.

**Closed by mykola-mokhnach** 2017-04-25 10:50 UTC
