### ISSUE TITLE
GET /session/:sessionId/element/:id/text returns selector/accessibility label instead of displayed text on iOS

### ISSUE THREAD

**Issue by JakeBent** [appium/appium#10349] opened 2018-03-13 18:31 UTC
## The problem

In a react native project, the `GET /session/:sessionId/element/:id/text` returns the specified element's accessibilityID instead of the actual displayed text on iOS. It works as intended on Android.

## Environment

* Appium v1.7.2
* Could not find version it worked correctly in (checked 1.7.0, 1.6.5, 1.6.2)
* Mac OS Sierra 10.12.6
* Node v8.2.0
* iOS 11.2/10.3, Android 6.0
* Emulator/simulator:
* CLI

## Details

Every UI test in our app is currently checking the existence of elements on iOS while on Android the actual text of elements can be tested. 

## Link to Appium logs

[Android logs](https://gist.github.com/JakeBent/474ee46a525000e2f0a810e187e9adb7)
[iOS logs](https://gist.github.com/JakeBent/b76457336fb319eb515561f731ba8c9d)

## Code To Reproduce Issue [ Good To Have ]

Here are screenshots of the [iOS](https://i.imgur.com/UzSvwOZ.png) and [Android](https://i.imgur.com/OTIbSyj.png) layouts as captured by the Appium desktop client mid-test showing the correct text in a chat bubble.

Spent a bit of time trying to recreate the issue out (https://github.com/JakeBent/AppiumBugExample). I didn't get the iOS appium config working and don't have more time to spend on this.

**Comment by bsneha90** [comment] 2018-03-14 08:26
@JakeBent The behaviour is due a react-native change done in version 0.50 and above. Please find the details [here](https://github.com/facebook/react-native/commit/915a020fcaaefc8c8c5a2016e79e9d6127c6e008).

**Comment by bsneha90** [comment] 2018-03-15 10:19
You could fix the issue by not passing accessibilityLabel for ios, like below:
`
let textProps={}
if(Platform.OS==='android')
textProps. accessibilityLabel = "welcomeLabel"
 ...
...
...
 <Text
          style={styles.welcome}
          {...textProps}
          testID="welcomeLabel"
        >
....
...
`

**Comment by saikrishna321** [comment] 2018-03-15 11:10
Closing as non-appium issue

**Closed by saikrishna321** 2018-03-15 11:10 UTC
Labels: ThirdParty

**Comment by Rovack** [comment] 2018-03-27 13:56
@bsneha90 Correct me if I'm wrong, but the RN 0.50 change affected the way accessibility labels between parents and children interact, right? What this issue seems to be talking about isn't that, but rather the fact that for an individual component (unrelated to its parent), trying to get the text returns the accessibility label instead.

As for not passing an accessibility label to the element, that might work, but then how would you find the element in the first place?
If you need to first find an element and then assert something on the text it has, it would appear both accessibility label and text are necessary.

(@saikrishna321 Given this, I think perhaps this issue should be re-opened.)

**Comment by mykola-mokhnach** [comment] 2018-03-27 14:00
@Rovack The value returned by `/text` endpoint is not controlled by Appium itself, but rather taken from [WDA](https://github.com/facebook/WebDriverAgent). If you believe the described behaviour is wrong then please file an issue to them.

**Comment by bsneha90** [comment] 2018-03-28 02:59
@Rovack we can conditionally pass the accessibilityLabel to android and pass only testID to iOS as mentioned earlier. The testID would be your accessibility id in case of iOS apps. But as @mykola-mokhnach mentioned this behaviour is react native specific and any concerns needs to raised to them.

**Comment by Rovack** [comment] 2018-03-28 16:06
@bsneha90 Ah, right. I missed the testID part of your suggestion, which should make it work on iOS.
Alright, that sounds like it could be the solution for now then.
Separately, the underlying problem should be fixed, but if that's caused by webdriver, then it's not part of this Issue.
Thank you!
