### ISSUE TITLE
[Appium 1.7 - iOS 11] Cannot get screenshot to inspect in Appium Desktop 1.2.1

### ISSUE THREAD

**Issue by luisromanwp** [appium/appium#9267] opened 2017-09-21 18:46 UTC
## The problem

I want to use the Appium Inspector in the latest Appium Desktop to Inspect my app in iOS 11 but it appears an error in the log when it tries to get the screenshot

Looks there's a problem with the idevicescreenshot in iOS 11
[XCUITest] Cannot take a screenshot from the device 0bbe0a323f3d295cff9230bc3a7c92d364c2108f using idevicescreenshot. Original error: Command 'idevicescreenshot -u 0bbe0a323f3d295cff9230bc3a7c92d364c2108f /var/folders/l_/8zl87nfs26qg7991wg19rskw0000gn/T/2017821-31063-126m0qq.h842fq1tt9/screenshot-0bbe0a323f3d295cff9230bc3a7c92d364c2108f.tiff' exited with code 255

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Desktop OS/version used to run Appium: Mac OS Sierra
* Mobile platform/version under test: iPhone 7 - 11.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium Desktop 1.2.1

## Link to Appium logs

https://gist.github.com/luisromanwp/9724362d8537fa5e844e2cde05d77e9a

**Comment by mykola-mokhnach** [comment] 2017-09-21 18:52
Closed as duplicate of https://github.com/appium/appium/issues/9259

**Closed by mykola-mokhnach** 2017-09-21 18:52 UTC
