### ISSUE TITLE
 Permission Denial - Android 7.0 Emulator

### ISSUE THREAD

**Issue by emanaltal** [appium/appium#10179] opened 2018-02-12 12:27 UTC
## The problem

Im unable to start main activity using appium and android emulator 7.0
problem is not encountered when using emulator 6.0

## Environment

* Appium version : 1.7.3
* Desktop OS/version : Windows 10
* Node.js version (unless using Appium.app|exe): 9.5.0
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: emulator

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

(C:\Users\eman.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$0$0$ (C:\Users\eman.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\eman.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\eman.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\eman.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\eman.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at 
 Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\eman.a\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell am start -W -n com.sssports.sssports/com.sssports.sssports.ui.main.MainActivity -S' exited with code 1'; Stderr: 'java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.sssports.sssports/.ui.main.MainActivity } from null (pid=3633, uid=2000) not exported from uid 10084
	at android.os.Parcel.readException(Parcel.java:1683)
	at android.os.Parcel.readException(Parcel.java:1636)
	at android.app.ActivityManagerProxy.startActivityAndWait(ActivityManagerNative.java:3178)
	at com.android.commands.am.Am.runStart(Am.java:630)
	at com.android.commands.am.Am.onRun(Am.java:388)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
	at com.android.commands.am.Am.main(Am.java:121)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)'; Code: '1'
    at Object.wrappedLogger.errorAndThrow (C:\Users\eman.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at ADB.callee$0$0$ (C:\Users\eman.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:101:9)
    at tryCatch (C:\Users\eman.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\eman.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\eman.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\eman.a\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at 
[AndroidDriver] Shutting down Android driver
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\eman.a\AppData\Local\Android\Sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","com.sssports.sssports"]
[ADB] Pressing the HOME button
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\eman.a\AppData\Local\Android\Sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","input","keyevent",3]
[AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] Received command result from bootstrap
[UiAutomator] Shutting down UiAutomator
[UiAutomator] Moving to state 'stopping'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[UiAutomator] UiAutomator shut down normally
[UiAutomator] Moving to state 'stopped'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\eman.a\AppData\Local\Android\Sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Moving to state 'stopped'
[Logcat] Stopping logcat capture
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\eman.a\AppData\Local\Android\Sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.unlock"]
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\eman.a\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell am start -W -n com.sssports.sssports/com.sssports.sssports.ui.main.MainActivity -S' exited with code 1'; Stderr: 'java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.sssports.sssports/.ui.main.MainActivity } from null (pid=3633, uid=2000) not exported from uid 10084
	at android.os.Parcel.readException(Parcel.java:1683)
	at android.os.Parcel.readException(Parcel.java:1636)

**Comment by vjmaiky** [comment] 2018-02-12 13:45
'1.7.2-beta4': '2017-12-18T19:36:38.516Z',
     '1.7.2-beta5': '2017-12-22T12:49:30.105Z',
     '1.7.2': '2018-01-03T13:35:04.036Z',
     '1.8.0-beta': '2018-01-17T15:16:00.010Z',
     '1.8.0-beta2': '2018-01-29T21:12:03.961Z',
     '1.8.0-beta3': '2018-01-30T17:12:40.312Z' }

i do not see any 1.7.3 appium in the releases; are you sure it's 1.7.3?

**Comment by mykola-mokhnach** [comment] 2018-02-12 13:48
Duplicate of https://github.com/appium/appium/issues/9956

... and many other issue

**Closed by mykola-mokhnach** 2018-02-12 13:48 UTC
