### ISSUE TITLE
[iOS] "Original error: Command '/usr/bin/python' not found" appear when use setLocation of a iOS Emulator on MAC Apple Silicon (M1)

### ISSUE THREAD

**Issue by peterlight90** [appium/appium#17334] opened 2022-08-08 16:20 UTC
## The problem

When I call setLocation function appium return error "Original error: Command '/usr/bin/python' not found" and break test.
<img width="820" alt="Screen Shot 2022-08-08 at 23 10 18" src="https://user-images.githubusercontent.com/32845863/183463418-36b42af2-ac32-4e35-b36b-52753c408e61.png">

## Environment

* Appium version (or git revision) that exhibits the issue: **Appium 1.22.3**
* Last Appium version that did not exhibit the issue (if applicable): **N/A**
* Desktop OS/version used to run Appium: **macOS Monterey 12.5 - M1Pro**
* Node.js version (unless using Appium.app|exe): **v18.7.0**
* Npm or Yarn package manager: **npm**
* Mobile platform/version under test: iOS 15.5
* Real device or emulator/simulator: XCode Emulator
* Appium CLI or Appium.app|exe: Appium.app

## Details
The error appear when I hit command: 
`driver.setLocation(new Location(0,0,0));`

## Link to Appium logs
[Gist](https://gist.github.com/peterlight90/378fc8ae1943e9d6db95b4e994c9e963)

## Code To Reproduce Issue [ Good To Have ]
`driver.setLocation(new Location(0,0,0));`

**Comment by KazuCocoa** [comment] 2022-08-08 16:38
Perhaps duplicate of https://github.com/appium/appium/issues/17031. Please try out latest xcuitest-driver with Appium 2.

**Comment by mykola-mokhnach** [comment] 2022-08-08 20:18
The issue has been fixed. Please use the recent driver release (only available as part of Appium2)

**Closed by mykola-mokhnach** 2022-08-08 20:18 UTC
Labels: NeedsInfo

**Comment by peterlight90** [comment] 2022-08-09 01:47
Thank you for you info
