### ISSUE TITLE
Appium server does not take screenshot for 1 screen only i.e map integrated with list view

### ISSUE THREAD

**Issue by grpratap69** [appium/appium#10773] opened 2018-05-29 06:51 UTC
<img width="876" alt="screen shot 2018-05-29 at 12 30 29 pm" src="https://user-images.githubusercontent.com/37795475/40642963-33feda1e-633c-11e8-8b3d-913f77965abd.png">
## The problem

Using ios 11.2.1 device to get screenshot but there seems to be some issue while taking screen shot of the screen having map and list view together.

## Environment
Appium- 1.4.1
Mac pro
real device
Java client-3.3.0

## Link to Appium logs

[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/0E6339C6-83FB-4126-89E1-766B2B7ED951/source] with no body

After this, server keeps trying but without any success of getting screenshot

## Code To Reproduce Issue [ Good To Have ]

"platformName": "ios",
  "deviceName": "iPhone6S",
  "bundleId": "com.mbrdi.travelbook.iOS.iPhone-ece-pDev",
  "udid": "0adf5d0253e61da105fdb6e59e83877b5bb83849",
  "app": "/Users/sjainar/TravelBook/TravelBook/Test_App/Travelbook.ipa",
  "noReset": "true",
  "platformVersion": "11.2.1"
}

**Comment by mykola-mokhnach** [comment] 2018-05-29 07:05
Try the newest server version (1.8.1)
Alos, the full server log is missing

**Comment by grpratap69** [comment] 2018-05-29 07:08
This progress bar is not disappearing and no logs are coming after this.

[Xcode]     t =   781.48s Snapshot accessibility hierarchy for app with pid 2640

This 1 came now

**Comment by grpratap69** [comment] 2018-05-29 07:08
i tried with 1.6.1 without any success

**Comment by grpratap69** [comment] 2018-05-29 07:10
Got this now..






[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"0243B8FC-0BBF-437B-AEC7-A8A40EB0F013"}],"sessionId":"757359F3-3646-4AE2-98A2-D81AF5ED8123","status":0}
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/757359F3-3646-4AE2-98A2-D81AF5ED8123/elements] with body: {"using":"xpath","value":"//XCUIElementTypeApplication[@name=\"Travelbook\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther"}
[MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"0243B8FC-0BBF-437B-AEC7-A8A40EB0F013"}]
[HTTP] <-- POST /wd/hub/session/715eefa5-a3b3-464c-b0fe-05bf791ef429/elements 200 116995 ms - 124 
[JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"10F184FF-AA4A-4905-9526-9BA6B92F3F7E"}],"sessionId":"757359F3-3646-4AE2-98A2-D81AF5ED8123","status":0}
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/757359F3-3646-4AE2-98A2-D81AF5ED8123/elements] with body: {"using":"xpath","value":"//XCUIElementTypeApplication[@name=\"Travelbook\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther"}
[MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"10F184FF-AA4A-4905-9526-9BA6B92F3F7E"}]
[HTTP] <-- POST /wd/hub/session/715eefa5-a3b3-464c-b0fe-05bf791ef429/elements 200 161924 ms - 124 
[JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"E6F33061-1563-4D02-8809-390572146B13"},{"ELEMENT":"4E1B6CC4-19E4-496A-85DB-50A0DFC7A91E"},{"ELEMENT":"139FAE72-B5B8-45EB-B6EF-6F623BCF4A7A"}],"sessionId":"757359F3-3646-4AE2-98A2-D81AF5ED8123","status":0}
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/757359F3-3646-4AE2-98A2-D81AF5ED8123/elements] with body: {"using":"xpath","value":"//XCUIElementTypeApplication[@name=\"Travelbook\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable"}
[MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"E6F33061-1563-4D02-8809-390572146B13"},{"ELEMENT":"4E1B6CC4-19E4-496A-85DB-50A0DFC7A91E"},{"ELEMENT":"139FAE72-B5B8-45EB-B6EF-6F623BCF4A7A"}]
[HTTP] <-- POST /wd/hub/session/715eefa5-a3b3-464c-b0fe-05bf791ef429/elements 200 214402 ms - 226 
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"757359F3-3646-4AE2-98A2-D81AF5ED8123","status":0}
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/757359F3-3646-4AE2-98A2-D81AF5ED8123/elements] with body: {"using":"xpath","value":"//XCUIElementTypeApplication[@name=\"Travelbook\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther"}
[MJSONWP] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/715eefa5-a3b3-464c-b0fe-05bf791ef429/elements 200 257845 ms - 74 
[Xcode] 10s     Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   106.97s Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   148.41s Find the Application "com.mbrdi.travelbook.iOS.iPhone-ece-pDev" 0x1c00cdac0
[Xcode]     t =   148.41s     Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   149.24s Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   149.24s Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   150.90s Find the Application "com.mbrdi.travelbook.iOS.iPhone-ece-pDev" 0x1c00cdac0
[Xcode]     t =   150.90s     Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   151.65s Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   222.38s Find the Application "com.mbrdi.travelbook.iOS.iPhone-ece-pDev" 0x1c00cdac0
[Xcode]     t =   222.39s     Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   228.77s Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   228.77s Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   233.29s Find the Application "com.mbrdi.travelbook.iOS.iPhone-ece-pDev" 0x1c00cdac0
[Xcode]     t =   233.29s     Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   234.06s Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   277.43s Find the Application "com.mbrdi.travelbook.iOS.iPhone-ece-pDev" 0x1c00cdac0
[Xcode]     t =   277.43s     Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   278.20s Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   278.21s Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   279.91s Find the Application "com.mbrdi.travelbook.iOS.iPhone-ece-pDev" 0x1c00cdac0
[Xcode]     t =   279.91s     Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   280.67s Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   324.64s Find the Application "com.mbrdi.travelbook.iOS.iPhone-ece-pDev" 0x1c00cdac0
[Xcode]     t =   324.64s     Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   325.40s Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   325.40s Get all elements bound by index for: Elements matching predicate 'wdUID IN {185, 186, 189} AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode]     t =   325.41s     Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   326.64s     Find: Descendants matching type Other
[Xcode]     t =   326.65s     Find: Elements matching predicate 'wdUID IN {185, 186, 189} AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode]     t =   326.65s Snapshot accessibility hierarchy for app with pid 2640
[Xcode]     t =   327.90s Find: Descendants matching type Other
[Xcode]     t =   327.91s Find: Elements matching predicate 'wdUID IN {185, 186, 189} AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode]     t =

**Comment by mykola-mokhnach** [comment] 2018-05-29 07:17
It is always a bad idea to use xpath locators with XCTest

**Comment by mykola-mokhnach** [comment] 2018-05-29 07:18
https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance

closed as third party issue

**Closed by mykola-mokhnach** 2018-05-29 07:18 UTC
Labels: NeedsInfo

**Comment by grpratap69** [comment] 2018-05-29 07:48
Already know that....i am using ids only...its not working so i have to check it with screenshot......understood issue now or not?

**Comment by grpratap69** [comment] 2018-05-29 07:49
How is it third party issue....m unable to see the attributes only through appium server

**Comment by mykola-mokhnach** [comment] 2018-05-29 08:03
This is what I observe in the attached log. If you have another one, where the problem is visible better then please provide it.

**Comment by grpratap69** [comment] 2018-05-29 08:11
ok...I got screenshot of the screen comes before this screen but not for this screen.

[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAIAAABFtaRRAAAAAXNSR0IArs4c6QAA\r\nABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAACimZRH1EYAAEAASURBVHgB\r\n7N0HnB5Vufjxs/u+20s22U3vCQmEUEKI9BIgQAKhdyG9bAqEJogFUREUK4pixWsB\r\ny1W5VhCpIqBSRWoSQBRsV7zXW739/n/zPpvDsEkgAa8f//p7OUzmPXPmzMx3z8z7\r\nvGfKm5IvBRRQQAEFFPizE6hLiZQq1ZwaUyJ11FJTSqS+V101Fak2w5YPo7paFTHa\r\nt8TaPxWWvCH11bxhaf6rgAIKKKCAAgq8tEBfYGEo89JUllBAAQUUUECBPz2Baqon\r\npVStpYaUSMV4JdWT+gKdogCpmBrlt3wY9TSm+pxqVdXXOnhioQxjuTH80zNyjRRQ\r\nQAEFFFDgT1bAUOZP9k/jiimggAIKKKDASwtEv0tcsNJ3tUqlPpGq1SLFeK1Xpq7o\r\npOnrp4m5tmQYV9v01R+9O33X3DSkOlLt+ptaP9CGoOql19kSCiiggAIKKKBAn4Ch\r\njE1BAQUUUEABBf5/Fqhdr5JvI2Kk78KYuI6lFumUe1/6psbFM1syjJmjZF+dXCiz\r\nYc5S/aVbnf5/9nTdFVBAAQUUUOCPKmAoA3eVc2nEcPX1dXV1DBmvVCoxkt9GJkNe\r\nkRkjzMKrlv3yB7nCqIK3UWcMY/WYlNczLykvmpGopKmp7/75PCnymbe8FKY2NhI+\r\nPr8tuc5NjuRVYmrGifEoH5UzibdRmPG8DjHCkFfeiigcsztU4GULRNujaVFD3lkY\r\nL+fQ2GJSZJabayw38mM8psY4w5gx19BvahRraOC2hb4lRg5zRZ0Mo6nnRecKoyRT\r\nmRTVlif1mz0K52GeSk6uOVcYI5tc1VyDIwpsiUBuaXxkRItiGE2a2aPFvmRLy7tA\r\n...
[HTTP] <-- GET /wd/hub/session/7f1c8604-8524-452e-a1a2-24f6820f1767/screenshot 200 90 ms - 107198 
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[HTTP] --> GET /wd/hub/session/7f1c8604-8524-452e-a1a2-24f6820f1767/source {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["7f1c8604-8524-452e-a1a2-24f6820f1767"]
[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/BEA5520D-5658-4D15-BE50-7EE321DC1841/source] with no body

In above logs, Result for previous screen is mentioned in first few lines and logs for current screen starts from this line    ....  [XCUITest] Connection to WDA timed out

**Comment by mykola-mokhnach** [comment] 2018-05-29 08:18
> [XCUITest] Connection to WDA timed out
> [iProxy] recv failed: Operation not permitted

This means that WebDriverAgent itself stopped responding to Appium requests. There is nothing we can do about it. Try to create an issue in https://github.com/facebook/WebDriverAgent/issues and attach device logs there

**Comment by grpratap69** [comment] 2018-06-07 03:51
getting an error that says ios 11.2.1 in not present in simctl devices in xcode
