### ISSUE TITLE
isElementDisplayed is returning false on appium 1.9.1

### ISSUE THREAD

**Issue by vsadineni1** [appium/appium#12143] opened 2019-02-08 23:52 UTC
## The problem
on iOS Safari browser, an element is shown on the screen but **isElementDisplayed** command is returning **false**.
Subsequently the **getText()** method call is returning empty string for the element text value.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.0
* Desktop OS/version used to run Appium: Mac OS Sierra 10.12.6 with simulator versions: iOS 11.2 & iOS 12.0 both have this problem
* Node.js version (unless using Appium.app|exe): v8.6.0
* Npm or Yarn package manager: 5.3.0
* Mobile platform/version under test: iOS 11.2 or 12.0 both exhibit the same issue
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:
Appium java client: 3.2.0

## Details
When I upgraded from appium: 1.8.0 to 1.9.1, I noticed that for iOS Safari tests, one of the elements that is displayed on the screen, we are trying to get the element text. The text is coming as empty string in appium: 1.9.1.
isElementDisplayed command is returning false
isElementEnabled is true.
But the same is working fine for appium: 1.8.0

## Link to Appium logs
In the below appium server logs, you can see the calls for AppiumDriver.elementDisplayed(), AppiumDriver.elementEnabled(), AppiumDriver.getText()

Appium 1.8.0 Logs - https://gist.github.com/vsadineni1/5e93fb13f751e32cc64df932f0c21935
Appium 1.9.1 Logs - https://gist.github.com/vsadineni1/a1f0df7ad999c05ae3dc0a8b97eb36e4

**Comment by mykola-mokhnach** [comment] 2019-02-09 07:46
Please report the problem to Apple. There is nothing to do on Appium side.

Closed as duplicate of https://github.com/appium/appium/issues/11507

**Closed by mykola-mokhnach** 2019-02-09 07:46 UTC

**Comment by vsadineni1** [comment] 2019-02-11 00:44
@mykola-mokhnach Here the issue is happening with the same iOS version(11.2) but when I change
the appium version from 1.8.0 to 1.9.1.
iOS 11.2 + appium 1.8.0 --> Works fine, no issue
iOS 11.2 + appium 1.9.1 --> Visibility issue.

So is not this related to appium ?

**Comment by saikrishna321** [comment] 2019-02-11 07:23
The actual element visibility is returned by XCUITest. There is nothing Appium can do about that.

**Comment by vsadineni1** [comment] 2019-02-11 17:30
@saikrishna321 Does the XCUITest version change when we upgrade appium version but keep the same iOS version?
I am thinking XCUITest version changes when we upgrade the iOS version. Is it not correct?

**Comment by saikrishna321** [comment] 2019-02-11 19:14
@vsadineni1 Yes, XCUITest version change when we upgrade appium version
