### ISSUE TITLE
Error An unknown server-side error occurred while processing the command. Original error: Xcode version '0.3'. Support for Xcode 0.3 is not supported. Please upgrade to version 7.3 or higher

### ISSUE THREAD

**Issue by kushbeat** [appium/appium#13260] opened 2019-09-19 10:20 UTC
Here I am using 
Xcode version :  10.3 (10G8)
Appium Version : 1.8.1 
When I start inspector seesion in real iOS device(12.4.1)
it show below error message 

[XCUITest] Error: Xcode version '0.3'. Support for Xcode 0.3 is not supported. Please upgrade to version 7.3 or higher
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at getAndCheckXcodeVersion$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:63:9)
[XCUITest]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at 
[XCUITest] Error: Xcode version '0.3'. Support for Xcode 0.3 is not supported. Please upgrade to version 7.3 or higher
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at getAndCheckXcodeVersion$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:63:9)
[XCUITest]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at 
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[BaseDriver] Event 'newSessionStarted' logged at 1568888318916 (15:48:38 GMT+0530 (IST))
[MJSONWP] Encountered internal error running command: Error: Xcode version '0.3'. Support for Xcode 0.3 is not supported. Please upgrade to version 7.3 or higher
[MJSONWP]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[MJSONWP]     at getAndCheckXcodeVersion$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:63:9)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- POST /wd/hub/session 500 211 ms - 237

**Comment by mykola-mokhnach** [comment] 2019-09-19 10:23
Duplicate of https://github.com/appium/appium/search?q=%22Please+upgrade+to+version+7.3%22&type=Issues

Consider upgrading the server to the recent version

**Closed by mykola-mokhnach** 2019-09-19 10:23 UTC
