### ISSUE TITLE
Test for unicode keyboard to be 'working'?

### ISSUE THREAD

**Issue by hughstephens** [appium/appium#5367] opened 2015-07-13 07:54 UTC
Hi all

We've had occasional (luckily rare) issues with the unicode keyboard packaged with appium => 1.2.0.

Sometimes the keyboard seems to just crap out in a session – it's not something highly reproducible from what I can tell (running the exact same test doesn't give the same result) but it results in the sendKeys characters being typed/visible (e.g. &SAPY-).

This is rather problematic for us as it's the caption for a social media post, so these characters appear instead of the customer's intended ones!

I know it's a bit useless until I can provide you some code that consistently reproduces the issue - but in the meantime, is there a (preferably reliable) test for the keyboard to work? Or am I going to need to do some kind of crazy workaround to check the number of characters in a field after typing one unicode character, prior to running our test/posting....

Thanks!

**Comment by Jonahss** [comment] 2015-07-14 22:55
Hm, there should be a way to check, we can try to add it if it will help you to track down a way to reproduce it.

I'm assuming you're using just Android?

@imurchie do you have any suggestions for how to detect wether the keyboard was set up properly?

There might be an adb command for this.

**Comment by imurchie** [comment] 2015-07-14 23:05
There _is_ an `adb` command for it. There is also an Appium command. In Python you can do `driver.active_ime_engine`. If the Unicode keyboard is active it should return the string `io.appium.android.ime/.UnicodeIME`.

**Comment by purigarcia** [comment] 2015-07-22 09:10
Hi, I am having a similar issue.
If I set the unicodeKeyboard, some letters are losing when typing in an input.
Normally the last one, but it does not happen all the time in the same input.
is it possible to set the unicodeKeyboard only for a textfield and then reset to the normal one in the same test?

**Comment by imurchie** [comment] 2015-07-22 15:45
That is possible. The client you are using should have methods for updating the IME. For instance, Python has `available_ime_engines`, `is_ime_active`, `activate_ime_engine`, `deactivate_ime_engine`, and `active_ime_engine`.

**Comment by purigarcia** [comment] 2015-07-22 15:49
Thanks @imurchie.
Are this options available also for java?
I am using capabilities.setCapability("unicodeKeyboard", true); Is that the way?

**Comment by imurchie** [comment] 2015-07-22 15:54
That will allow you to set it for the whole test. I'm not familiar enough with the Java client to tell what the methods are there. @Jonahss ?

**Comment by Jonahss** [comment] 2015-07-23 16:22
It's already part of the Selenium java client. org.openqa.selenium.WebDriver.ImeHandler

https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebDriver.ImeHandler.html

**Comment by purigarcia** [comment] 2015-07-30 07:40
Thanks, @Jonahss 
What I am trying to do, is write special characters as á, é... in an input. but it is not working.
I check this example https://github.com/Jonahss/appium-ime-example
and I try to do using com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
Could you give me an example of how to write specials characters? Thanks in advance

**Comment by purigarcia** [comment] 2015-08-17 07:50
I am working with the unicode keyboard, 
This is the code I am using
 ```AndroidDriver.ImeHandler ime = driver.manage().ime();
 ime.activateEngine("io.appium.android.ime/.UnicodeIME");
....
newFolderNameField.sendKeys(newFolderName + "\n");```

If newFolderName is alo, it works perfect
But if it has some special characters as á, &... it does not work

When I set it in the capabilities, 
```capabilities.setCapability("unicodeKeyboard", true);```
it works fine.
But I do not want to use all the time the unicodeKeyboard, because it missed letters too often and the test fails with no reason.
@Jonahss , could you indicate me what I am doing wrong? or is the io.appium.android.ime/.UnicodeIME not working?

**Comment by imurchie** [comment] 2015-08-17 15:21
You can't just turn on the IME manually, because the Appium code that sends in the text does not know to encode it. The problem with the Android UI Automator is that it strips out all of the non-ASCII text. The `unicodeKeyboard` capability tells Appium to encode any other text as ASCII, and send it. The IME then decodes it to the original. Both sides need to be in play, or it does not work.

**Comment by imurchie** [comment] 2015-08-17 15:21
The bigger problem is that characters are being missed when `unicodeKeyboard` is being used. Can you provide more information about that so we can attempt to fix it?

**Comment by purigarcia** [comment] 2015-08-18 12:46
Thanks, now it works. I have to use 
```capabilities.setCapability("unicodeKeyboard", true);```
And also the other code.

In thar example, capability is not use.
https://github.com/Jonahss/appium-ime-example/blob/master/src/main/java/Main.java

About the problem of missing characters, it happens to me when I only use 
```capabilities.setCapability("unicodeKeyboard", true);```
It does not give me any error message.
It happens to me everytime I launch 10 test in a row

This is how I setup the enviroment
```File rootPath = new File(System.getProperty("user.dir"));
		File appDir = new File(rootPath,"src/test/resources");
		File app = new File(appDir,"apk");
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("platformName", "Android");
		capabilities.setCapability("deviceName", "test");
		capabilities.setCapability("app", app.getAbsolutePath());
		capabilities.setCapability("appPackage", "package");
		capabilities.setCapability("appActivity", ".ui.activity.FileDisplayActivity");	
		capabilities.setCapability("appWaitActivity", ".authentication.AuthenticatorActivity");
		capabilities.setCapability("unicodeKeyboard", true);
		capabilities.setCapability("resetKeyboard", true);
		driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
		driver.manage().timeouts().implicitlyWait(waitingTime,TimeUnit.SECONDS);
		wait = new WebDriverWait(driver, waitingTime, 50);```

Hope this helps to find the problem

**Comment by elyanivson** [comment] 2016-06-05 10:02
@purigarcia
Thanks it worked

**Comment by Zawel1** [comment] 2017-01-25 12:48
This bug still occurs in latest version of appium. Any chance that it will be fixed soon? It makes testing very unstable.

**Comment by jlipps** [comment] 2017-07-20 21:21
@Zawel1 can you provide logs and a repro case with Appium 1.6.5?

**Comment by SamyQAZ** [comment] 2017-09-27 02:54
Unable to use unicode keyboard for Appium CLI 1.6.6-beta.3. 
Using unicodeKeyboard=True    resetKeyboard=True
Trying to enter text in browser and search it.
Some how keyboard search/go/enter key cannot be pressed. 
I am using robot framework, Press Keycode  66 to search on android(5.1.1) device.
Tested with couple of other android version devices still no luck.

Does anyone have idea how to press search after entering text for in app browser?

**Comment by mykola-mokhnach** [comment] 2018-10-23 12:08
There is no need for the unicode keyboard in never Android version and UIA2 does not use it as well, since setText API properly handles Unicode input since API19

**Closed by mykola-mokhnach** 2018-10-23 12:08 UTC
Labels: Android, Bug, OnGoing, P2
