### ISSUE TITLE
v1.9.0 - "automationName" : "Espresso" to use view-tags in my tests

### ISSUE THREAD

**Issue by eMTe123** [appium/appium#11272] opened 2018-08-28 13:38 UTC
## The problem

Hello!

I am trying to use 1.9.0 with "automationName" : "Espresso". I get the error below, using both appium inspector and running my tests with this capability set. 

>  Error: Could not sign with default certificate.

I tried to update SDK tools, delete temp folder and re-run, as well as changing file permissions.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v9.7.1 (also tried appium.exe)
* Mobile platform/version under test: Android 8.1
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Tried both

## Details

I want to launch appium with the mentioned capability set for mye app. When I run see the following in my temp folder:
- io.appium.espressoserver.test_1.0.0-beta.9_<app>
- AndroidManifest.xml.apk
- AndroidManifest (zip)

## Link to Appium logs

https://gist.github.com/eMTe123/96c5920794c365a627882475d6a5f889

## Code To Reproduce Issue [ Good To Have ]

Just want to launch appium with capability: "automationName" : "Espresso"
E.G.
`      platformName: 'android',
      platformVersion: '8.1',
      app: 'C:/apks/app-y-release.apk',
      automationName: 'uiautomator2',
      deviceName: 'Android Emulator',
      appPackage: 'x.mobil.radio',
      appActivity: 'x.mobil.radio.MainActivity'`

**Comment by mykola-mokhnach** [comment] 2018-08-28 13:40
Duplicate of https://github.com/appium/appium/issues/11266

**Closed by mykola-mokhnach** 2018-08-28 13:40 UTC

**Comment by eMTe123** [comment] 2018-08-28 13:48
Sorry! Posted the wrong log in gist!

I don't think it's a duplicate as I get an error saying:

> Encountered internal error running command: Error: Could not sign with default certificate.
