### ISSUE TITLE
opencv4nodejs not found even after installing and linking it ro appium

### ISSUE THREAD

**Issue by smrtyviks** [appium/appium#15540] opened 2021-06-18 12:55 UTC
## The problem

I am facing issue with image recognition setup, when i try to run my test with findelementbyimage option i get an error:

"org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: 'opencv4nodejs' module is required to use OpenCV features. Please install it first ('npm i -g opencv4nodejs') and restart Appium."

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium:MacOS
* Node.js version (unless using Appium.app|exe):14.15.5
* Npm or Yarn package manager: 7.15.1
* Mobile platform/version under test:14.4
* Real device or emulator/simulator:iPhone XR real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Not able to execute image recognition with appium

## Link to Appium logs

https://gist.github.com/smrtyviks/a61876df75caaf7eb18ac37be9483605

## Code To Reproduce Issue [ Good To Have ]
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileBy;
import io.appium.java_client.MobileElement;
import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Base64;

public class baseclass {

     static AppiumDriver<MobileElement> driver;
    @BeforeClass
    public static void setup() throws MalformedURLException {
        /*File rootPath = new File(System.getProperty("user.dir"));
        File src = new File(rootPath,"/IdeaProjects/TestMaven/src/test/Resources/apps/");
        File appPath = new File(src,"LEGOBuildingInsstructions.ipa");*/

        DesiredCapabilities caps=new DesiredCapabilities();
        caps.setCapability(MobileCapabilityType.PLATFORM_NAME,"iOS");
        caps.setCapability(MobileCapabilityType.PLATFORM_VERSION,"14.4");
        caps.setCapability(MobileCapabilityType.UDID,"0000-xxxxxx");
        caps.setCapability(MobileCapabilityType.DEVICE_NAME,"iPhone");
        caps.setCapability(MobileCapabilityType.AUTOMATION_NAME,"XCUITest");
        caps.setCapability(MobileCapabilityType.APP,"/users/username/IdeaProjects/TestMaven/src/test/Resources/apps/testPP.ipa");
        URL url=new URL("http://127.0.0.1:4723/wd/hub");

        //URL url=new URL("https://oauth-vikrant.sarkaniya-e0378:bdb036c4-19c0-4f38-bbf0-c1d969217f6d@ondemand.eu-central-1.saucelabs.com:443/wd/hub");
        driver =new AppiumDriver<MobileElement>(url,caps);
        //driver=new IOSDriver<MobileElement>(url,caps);
        //driver.installApp("/users/username/IdeaProjects/TestMaven/src/test/Resources/apps/testapp.ipa");

    }

    @Test
    public void sampletest() throws Exception {

        Thread.sleep(5000);
        driver.findElementByAccessibilityId("OK").click();
        System.out.println(" i am inside test");
      String logoImage = getRefImage ("homepage");

        driver.findElement(MobileBy.image(logoImage));

        driver.findElementByImage(logoImage).isDisplayed();
    }
    protected String getRefImage(String refImgName) throws Exception {

        File file = new File(System.getProperty("user.dir") +"/src/test/Resources/images/" + refImgName + ".png");
        Path path = file.toPath();
        return Base64.getEncoder().encodeToString(Files.readAllBytes(path));
    }
    @AfterClass
    public static void teardown(){
    driver.close();
    }
}

**Comment by mykola-mokhnach** [comment] 2021-06-18 13:05
Duplicate of https://github.com/appium/appium/issues?q=is%3Aissue+opencv4nodejs+is%3Aclosed

**Closed by mykola-mokhnach** 2021-06-18 13:05 UTC
