### ISSUE TITLE
[UIAutomator2] Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#8159] opened 2017-04-03 14:45 UTC
## The problem

During ARC command execution, suddenly commands stops working with error

Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac 10.11.6
* Node.js version (unless using Appium.app|exe): v7.6.0
* Mobile platform/version under test: Nexus 5,  6.0.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

Using ARC to probe the app and look into locators.  While doing this it's observed that commands stops working with error 

Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

## Link to Appium logs

https://gist.github.com/vikramvi/c18c280af8384cd52858359452b36de3#file-gistfile1-txt-L260

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by vikramvi** [comment] 2017-04-03 14:52
After this I stopped appium server and arc as well. Restarted both and getting new kind of errors

https://gist.github.com/vikramvi/133acc65a4704d34185a9b0f2ae1c7fc

When I rund adb devices, it does show device name under list of devices

**Comment by vikramvi** [comment] 2017-04-03 15:10
I had to restart device -> appium server -> arc to get whole setup up and running again.

Please let me know if you need more info / logs on this issue

**Comment by mykola-mokhnach** [comment] 2017-04-03 15:20
Duplicate of https://github.com/appium/appium/issues/8100
It looks like something is broken in Android SDK - probably updating it will help

**Comment by vikramvi** [comment] 2017-04-04 09:33
@mykola-mokhnach can you please clarify how is this related to SDK older version ? I'm trying to run automation on real device and not on emulator.

Real device is running Android OS 6.0.1

**Comment by sravanmedarapu** [comment] 2017-04-05 05:18
@vikramvi, Can you share adb logs ?

**Comment by amias-channer** [comment] 2017-06-21 13:37
I am seeing this intermittently with android devices on Appium 1.6.5 desktop (with updates) and using the ruby Appium_lib gem 9.4.7.  I am not having any particular issues with adb , although I've noticed that when Appium is running it seems to be able to make adb unreliable. I've updated everything in Android Studio. The same suite run on the same hardware produces different results each time :(

**Comment by YannickXiong** [comment] 2017-12-25 02:03
i met this error too.  
appium version 1.7.1
mac os 10.12

- I used desired_caps['automationName'] = 'Uiautomator2' in a python scritp to catch toast message, while got a error msg that appium-uiautomator2-server-v0.1.8.apk doesn't exist;
- Then I used npm -g install appium-uiautomator2-driver@0.1.8 to install , however, it failed, there were not 0.1.8 vesion availabe;
- Next I used npm -g install appium-uiautomator2-driver, it successd, the version is v-0.2.1
- Next I run my python scription(with out desired_caps['automationName'] = 'Uiautomator2', the scription runs normally), I met the fellowing errors at last.

[debug] [ADB] Running '/Users/*******/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","ime","set","io.appium.android.ime/.UnicodeIME"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/*******/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.hx58wallet"]
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/Users/*******/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","forward","--remove","tcp:8200"]
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:152:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

**Comment by zyjin** [comment] 2018-02-01 03:14
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET (WARNING: The server did not provide any stacktrace information)

**Comment by gamesguru** [comment] 2018-04-13 15:41
I'm getting this error a lot, frustrating just to get appium connected to the device sometimes... I think it may be a fault of node, or how it communicates to appium. 

```
...waiting for driver to connect with appium on the samsung SM-J327P...

waiting up to  3s

[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: read ECONNRESET
    at JWProxy.proxy$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:152:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

 ===============
  --Exception--
 ===============
param: 
4/13/2018 11:35:09 AM
WebDriver, -2146233079
System.Collections.ListDictionaryInternal
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET


Void UnpackAndThrowOnError(OpenQA.Selenium.Remote.Response)
  at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError (OpenQA.Selenium.Remote.Response errorResponse) [0x000fe] in <6a93e12c6bde4af79c4b6c5665da6798>:0 
  at OpenQA.Selenium.Remote.RemoteWebDriver.Execute (System.String driverCommandToExecute, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters) [0x0003d] in <6a93e12c6bde4af79c4b6c5665da6798>:0 
  at OpenQA.Selenium.Appium.AppiumDriver`1[W].Execute (System.String driverCommandToExecute, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters) [0x00000] in <9b3ceeffa60d410090f33f3b9ea8ebde>:0 
  at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession (OpenQA.Selenium.ICapabilities desiredCapabilities) [0x0004b] in <6a93e12c6bde4af79c4b6c5665da6798>:0 
  at OpenQA.Selenium.Remote.RemoteWebDriver..ctor (OpenQA.Selenium.Remote.ICommandExecutor commandExecutor, OpenQA.Selenium.ICapabilities desiredCapabilities) [0x0001e] in <6a93e12c6bde4af79c4b6c5665da6798>:0 
  at OpenQA.Selenium.Appium.AppiumDriver`1[W]..ctor (OpenQA.Selenium.Remote.ICommandExecutor commandExecutor, OpenQA.Selenium.ICapabilities desiredCapabilities) [0x00000] in <9b3ceeffa60d410090f33f3b9ea8ebde>:0 
  at OpenQA.Selenium.Appium.AppiumDriver`1[W]..ctor (System.Uri remoteAddress, OpenQA.Selenium.ICapabilities desiredCapabilities, System.TimeSpan commandTimeout) [0x00008] in <9b3ceeffa60d410090f33f3b9ea8ebde>:0 
  at OpenQA.Selenium.Appium.AppiumDriver`1[W]..ctor (System.Uri remoteAddress, OpenQA.Selenium.ICapabilities desiredCapabilities) [0x00000] in <9b3ceeffa60d410090f33f3b9ea8ebde>:0 
  at OpenQA.Selenium.Appium.Android.AndroidDriver`1[W]..ctor (System.Uri remoteAddress, OpenQA.Selenium.Remote.DesiredCapabilities desiredCapabilities) [0x0000d] in <9b3ceeffa60d410090f33f3b9ea8ebde>:0 
  at appiumUnitTests.testLogic.runTests (appiumUnitTests.Program+device de) [0x00846] in /Users/sjaroch/Desktop/repos/appium_ios_unitTests/appiumUnitTests/testLogic.cs:230 
 ===================
  --End exception--
 ===================
```

Timeouts at 60 seconds are also common
```
...waiting for driver to connect with appium on the samsung SM-J327P...

waiting up to  0s
 ===============
  --Exception--
 ===============
param: 
4/13/2018 11:38:38 AM
appium-dotnet-driver, -2146233088
System.Collections.ListDictionaryInternal
The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/wd/hub/session timed out after 60 seconds.


OpenQA.Selenium.Remote.Response Execute(OpenQA.Selenium.Remote.Command)
  at OpenQA.Selenium.Appium.Service.AppiumCommandExecutor.Execute (OpenQA.Selenium.Remote.Command commandToExecute) [0x0005e] in <9b3ceeffa60d410090f33f3b9ea8ebde>:0 
  at OpenQA.Selenium.Remote.RemoteWebDriver.Execute (System.String driverCommandToExecute, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters) [0x00014] in <6a93e12c6bde4af79c4b6c5665da6798>:0 
  at OpenQA.Selenium.Appium.AppiumDriver`1[W].Execute (System.String driverCommandToExecute, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters) [0x00000] in <9b3ceeffa60d410090f33f3b9ea8ebde>:0 
  at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession (OpenQA.Selenium.ICapabilities desiredCapabilities) [0x0004b] in <6a93e12c6bde4af79c4b6c5665da6798>:0 
  at OpenQA.Selenium.Remote.RemoteWebDriver..ctor (OpenQA.Selenium.Remote.ICommandExecutor commandExecutor, OpenQA.Selenium.ICapabilities desiredCapabilities) [0x0001e] in <6a93e12c6bde4af79c4b6c5665da6798>:0 
  at OpenQA.Selenium.Appium.AppiumDriver`1[W]..ctor (OpenQA.Selenium.Remote.ICommandExecutor commandExecutor, OpenQA.Selenium.ICapabilities desiredCapabilities) [0x00000] in <9b3ceeffa60d410090f33f3b9ea8ebde>:0 
  at OpenQA.Selenium.Appium.AppiumDriver`1[W]..ctor (System.Uri remoteAddress, OpenQA.Selenium.ICapabilities desiredCapabilities, System.TimeSpan commandTimeout) [0x00008] in <9b3ceeffa60d410090f33f3b9ea8ebde>:0 
  at OpenQA.Selenium.Appium.AppiumDriver`1[W]..ctor (System.Uri remoteAddress, OpenQA.Selenium.ICapabilities desiredCapabilities) [0x00000] in <9b3ceeffa60d410090f33f3b9ea8ebde>:0 
  at OpenQA.Selenium.Appium.Android.AndroidDriver`1[W]..ctor (System.Uri remoteAddress, OpenQA.Selenium.Remote.DesiredCapabilities desiredCapabilities) [0x0000d] in <9b3ceeffa60d410090f33f3b9ea8ebde>:0 
  at appiumUnitTests.testLogic.runTests (appiumUnitTests.Program+device de) [0x00846] in /Users/sjaroch/Desktop/repos/appium_ios_unitTests/appiumUnitTests/testLogic.cs:230 
 ===================
  --End exception--
 ===================
appium failed to start.. let's try again
killing old node server...
```

**Comment by senshu7** [comment] 2018-04-20 07:36
also met this problem a lot,but i still have no idea about it.

**Comment by dmlemeshko** [comment] 2018-06-22 21:21
Reproduced with Appium Server **1.8.1** on real device at **SauceLabs cloud**:
```
18:17:37	VERBOSE:	[HTTP] --> POST /wd/hub/session/b3c27bdb-f3c2-422d-9095-7d8138fea837/elements
18:17:37	VERBOSE:	[HTTP] {"using":"id","value":"auction_gallery_container"}
18:17:37	VERBOSE:	[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["id","auction_gallery_container","b3c27bdb-f3c2-422d-9095-7d8138fea837"]
18:17:37	VERBOSE:	[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
18:17:37	VERBOSE:	[debug] [BaseDriver] Waiting up to 100 ms for condition
18:17:37	VERBOSE:	[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8219/wd/hub/session/188052d1-6851-49fb-b2e4-da39fc3ed5d8/elements] with body: {"strategy":"id","selector":"auction_gallery_container","context":"","multiple":true}
18:17:38	VERBOSE:	[debug] [UiAutomator2] [UIAutomator2] 
18:17:38	VERBOSE:	[debug] [UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
18:17:38	VERBOSE:	[Logcat] Logcat terminated with code 0, signal null
18:17:38	VERBOSE:	[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up
18:17:38	VERBOSE:	[MJSONWP]     at JWProxy.proxy$ (/root/appium/appium/1.8.1/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:152:13)
18:17:38	VERBOSE:	[MJSONWP]     at tryCatch (/root/appium/appium/1.8.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
18:17:38	VERBOSE:	[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/root/appium/appium/1.8.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
18:17:38	VERBOSE:	[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/root/appium/appium/1.8.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
18:17:38	VERBOSE:	[MJSONWP]     at GeneratorFunctionPrototype.invoke (/root/appium/appium/1.8.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
18:17:38	VERBOSE:	[MJSONWP]     at <anonymous>
18:17:38	VERBOSE:	[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:188:7)
18:17:38	VERBOSE:	[HTTP] <-- POST /wd/hub/session/b3c27bdb-f3c2-422d-9095-7d8138fea837/elements 500 273 ms - 250
```

**Comment by Jeeveshk** [comment] 2018-07-12 08:04
I am also facing the same issue, are there any fixed for this ?

**Comment by mykola-mokhnach** [comment] 2018-08-04 11:31
Socket hang up issue might pop up due to multiple reasons, which, usually, have nothing to do with Appium or UIA2 server component. For example: problems with device hardware, network issues, adb issues, etc. Getting adb logcat output and analysing it for possible stack traces/crashes might help to catch a problem in some cases though.

**Closed by mykola-mokhnach** 2018-08-04 11:31 UTC
Labels: ThirdParty, UIAutomator2

**Comment by manishthackray** [comment] 2018-08-07 07:53
:( 👎

**Comment by imurchie** [comment] 2018-08-07 15:09
@manishthackray Since no one has ever produced the device logs (from `adb logcat`, as has been requested multiple times) there is nothing that can be helped here.

**Comment by auto-mator** [comment] 2018-08-20 18:31
From adb log:

--------- beginning of crash
08-20 11:06:58.250 31880 31938 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 31938 (bt_workqueue)
08-20 11:06:58.272 31880 31938 F libc    : crash_dump helper failed to exec
08-20 11:06:58.272 31880 31938 F libc    : failed to wait for crash_dump helper: No child processes
08-20 11:19:23.277  1204  1204 E AndroidRuntime: FATAL EXCEPTION: main
08-20 11:19:23.277  1204  1204 E AndroidRuntime: Process: io.appium.uiautomator2.server, PID: 1204
08-20 11:19:23.277  1204  1204 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: src.length=7 srcPos=0 dst.length=7 dstPos=1 length=7
08-20 11:19:23.277  1204  1204 E AndroidRuntime: 	at java.lang.System.arraycopy(Native Method)
08-20 11:19:23.277  1204  1204 E AndroidRuntime: 	at java.util.ArrayList.addAll(ArrayList.java:591)
08-20 11:19:23.277  1204  1204 E AndroidRuntime: 	at android.view.accessibility.AccessibilityNodeInfo.init(AccessibilityNodeInfo.java:3248)
08-20 11:19:23.277  1204  1204 E AndroidRuntime: 	at android.view.accessibility.AccessibilityNodeInfo.refresh(AccessibilityNodeInfo.java:903)
08-20 11:19:23.277  1204  1204 E AndroidRuntime: 	at android.view.accessibility.AccessibilityCache$AccessibilityNodeRefresher.refreshNode(AccessibilityCache.java:564)
08-20 11:19:23.277  1204  1204 E AndroidRuntime: 	at android.view.accessibility.AccessibilityCache.refreshCachedNodeLocked(AccessibilityCache.java:206)
08-20 11:19:23.277  1204  1204 E AndroidRuntime: 	at android.view.accessibility.AccessibilityCache.onAccessibilityEvent(AccessibilityCache.java:170)
08-20 11:19:23.277  1204  1204 E AndroidRuntime: 	at android.view.accessibility.AccessibilityInteractionClient.onAccessibilityEvent(AccessibilityInteractionClient.java:611)
08-20 11:19:23.277  1204  1204 E AndroidRuntime: 	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1732)
08-20 11:19:23.277  1204  1204 E AndroidRuntime: 	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
08-20 11:19:23.277  1204  1204 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
08-20 11:19:23.277  1204  1204 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
08-20 11:19:23.277  1204  1204 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6888)
08-20 11:19:23.277  1204  1204 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-20 11:19:23.277  1204  1204 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
08-20 11:19:23.277  1204  1204 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1370)
08-20 11:37:01.388 15702 15745 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 15745 (bt_workqueue)
08-20 11:37:01.416 15702 15745 F libc    : crash_dump helper failed to exec
08-20 11:37:01.416 15702 15745 F libc    : failed to wait for crash_dump helper: No child processes
08-20 11:37:15.866 15788 15830 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 15830 (bt_workqueue)
08-20 11:37:15.899 15788 15830 F libc    : crash_dump helper failed to exec
08-20 11:37:15.899 15788 15830 F libc    : failed to wait for crash_dump helper: No child processes
08-20 11:37:30.334 15876 15918 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 15918 (bt_workqueue)
08-20 11:37:30.364 15876 15918 F libc    : crash_dump helper failed to exec
08-20 11:37:30.365 15876 15918 F libc    : failed to wait for crash_dump helper: No child processes
08-20 11:37:44.847 15970 16015 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 16015 (bt_workqueue)
08-20 11:37:44.875 15970 16015 F libc    : crash_dump helper failed to exec
08-20 11:37:44.875 15970 16015 F libc    : failed to wait for crash_dump helper: No child processes
08-20 11:37:59.244 16038 16082 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 16082 (bt_workqueue)
08-20 11:37:59.276 16038 16082 F libc    : crash_dump helper failed to exec
08-20 11:37:59.276 16038 16082 F libc    : failed to wait for crash_dump helper: No child processes
08-20 11:38:13.624 16107 16155 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 16155 (bt_workqueue)
08-20 11:38:13.652 16107 16155 F libc    : crash_dump helper failed to exec
08-20 11:38:13.652 16107 16155 F libc    : failed to wait for crash_dump helper: No child processes
08-20 11:38:28.185 16176 16220 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 16220 (bt_workqueue)
08-20 11:38:28.213 16176 16220 F libc    : crash_dump helper failed to exec
08-20 11:38:28.213 16176 16220 F libc    : failed to wait for crash_dump helper: No child processes

**Comment by auto-mator** [comment] 2018-09-21 15:16
@imurchie ^^^^^^^^^

**Comment by auto-mator** [comment] 2018-09-21 15:17
@mykola-mokhnach ^^^

**Comment by fpuy** [comment] 2018-10-12 14:20
I was using Android Version 9.0 on emulator. Created a new AVD with version 6.0 Marshmallow and it worked.

**Comment by Ucoon** [comment] 2018-11-09 03:00
Hi, I'm facing the same issue. I'm running this on an Windows7, Appium Desktop 1.7.0, Is there any solution?
this is my serevr log:
```
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/a45cac15-4fad-4fd8-a6a2-1a0ed1c284a0/element [39m[32m200[39m [90m1300 ms - 122[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/a45cac15-4fad-4fd8-a6a2-1a0ed1c284a0/element[39m
[info] [35m[HTTP][39m [90m{"using":"-android uiautomator","value":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"确定\").instance(0));","sessionId":"a45cac15-4fad-4fd8-a6a2-1a0ed1c284a0"}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.findElement() with args: ["-android uiautomator","new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"确定\").instance(0));","a45cac15-4fad-4fd8-a6a2-1a0ed1c284a0"]
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [35m[BaseDriver][39m Waiting up to 0 ms for condition
[debug] [35m[JSONWP Proxy][39m Matched '/element' to command name 'findElement'
[debug] [35m[JSONWP Proxy][39m Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/c73e897f-c702-4d9a-a3a8-404fb5cbc90c/element] with body: {"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"确定\").instance(0));","context":"","multiple":false}
[debug] [35m[JSONWP Proxy][39m Got response with status 200: {"sessionId":"c73e897f-c702-4d9a-a3a8-404fb5cbc90c","status":0,"value":{"ELEMENT":"a7972d3c-084c-461d-9f7f-4ee3422eff98"}}
[debug] [35m[MJSONWP][39m Responding to client with driver.findElement() result: {"ELEMENT":"a7972d3c-084c-461d-9f7f-4ee3422eff98"}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/a45cac15-4fad-4fd8-a6a2-1a0ed1c284a0/element [39m[32m200[39m [90m84 ms - 122[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/a45cac15-4fad-4fd8-a6a2-1a0ed1c284a0/element/a7972d3c-084c-461d-9f7f-4ee3422eff98/click[39m
[info] [35m[HTTP][39m [90m{"id":"a7972d3c-084c-461d-9f7f-4ee3422eff98","sessionId":"a45cac15-4fad-4fd8-a6a2-1a0ed1c284a0"}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.click() with args: ["a7972d3c-084c-461d-9f7f-4ee3422eff98","a45cac15-4fad-4fd8-a6a2-1a0ed1c284a0"]
[debug] [35m[JSONWP Proxy][39m Matched '/element/a7972d3c-084c-461d-9f7f-4ee3422eff98/click' to command name 'click'
[debug] [35m[JSONWP Proxy][39m Proxying [POST /element/a7972d3c-084c-461d-9f7f-4ee3422eff98/click] to [POST http://localhost:8200/wd/hub/session/c73e897f-c702-4d9a-a3a8-404fb5cbc90c/element/a7972d3c-084c-461d-9f7f-4ee3422eff98/click] with body: {"element":"a7972d3c-084c-461d-9f7f-4ee3422eff98"}[debug] [35m[UiAutomator2][39m [UIAutomator2] 
[debug] [35m[UiAutomator2][39m [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
[error] [35m[MJSONWP][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
[error] [35m[MJSONWP][39m     at JWProxy.command$ (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:371:13)
[error] [35m[MJSONWP][39m     at tryCatch (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[error] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[error] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[error] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[error] [35m[MJSONWP][39m     at <anonymous>
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/a45cac15-4fad-4fd8-a6a2-1a0ed1c284a0/element/a7972d3c-084c-461d-9f7f-4ee3422eff98/click [39m[31m500[39m [90m295 ms - 250[39m
```

**Comment by PHUITesting** [comment] 2019-05-06 17:36
Seeing this as well, too many dependencies for appium to pinpoint the issue?
