### ISSUE TITLE
Xcode version '0.0'. Support for Xcode 0.0 is not supported. Please upgrade to version 7.3 or higher

### ISSUE THREAD

**Issue by Ashwini12345** [appium/appium#11229] opened 2018-08-22 10:06 UTC
## The problem

Unable to run tests using the latest XCode10 on iOS 12

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:v1.8.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:IOS 12 beta
* Real device or emulator/simulator:Simulator
* Appium CLI or Appium.app|exe:

## Details

I haved referered the solutions provided in this ticked but this is not helping me https://github.com/appium/appium/issues/10810

## Link to Appium logs

[appium-server-logs.txt](https://github.com/appium/appium/files/2309831/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment] 2018-08-22 10:08
> [info] [Appium] Welcome to Appium v1.8.1

The log is generated by Appium 1.8.1. This issue is addressed in Appium@beta only

**Closed by mykola-mokhnach** 2018-08-22 10:08 UTC

**Comment by Ashwini12345** [comment] 2018-08-22 10:12
@mykola-mokhnach  can you help me with any ticket no to refer or link or anything with which it can help me to resolve this isuue.

**Comment by mykola-mokhnach** [comment] 2018-08-22 11:30
Just make sure that appium is at `beta` version. It should be enough to address the problem

**Comment by KazuCocoa** [comment] 2018-08-22 11:34
Appium desktop has Appium 1.8.1 so far. Please use appium@beta directly. Or wait for the next release.

If you would like to use the 1.9.0-beta via the desktop app, you can git clone the repository, update the Appium version and build it on your local.
(But sorry, I’m not sure if it works with 1.9.0-beta since I haven’t confirmed it)
