### ISSUE TITLE
Starting app with Espresso Driver fails

### ISSUE THREAD

**Issue by gyarang** [appium/appium#13002] opened 2019-07-31 07:44 UTC
## The problem

I try to use Espresso driver with appium. But test application keep crushed when it start with espresso.
My test apk is build with signed key as debug-apk file and it works well with UIAutomator2 driver.

`com.testworks.appium_test_app E/MonitoringInstr: Exception encountered by: com.testworks.appium_test_app.MainActivity@a55759d. Dumping thread state to outputs and pining for the fjords.`
`    android.content.res.Resources$NotFoundException: Drawable com.testworks.appium_test_app:id/message with resource ID #0x7f070059`
`    Caused by: android.content.res.Resources$NotFoundException: Resource "com.testworks.appium_test_app:id/message" (7f070059) is not a Drawable (color or path): TypedValue{t=0x12/d=0x0 a=2 r=0x7f070059}`

It's error log on Android studio Logcat.
Error occurred with code `super.onCreate(savedInstanceState);` in onCreate() method

## Environment

Appium version: 1.13.0
Desktop OS: Windows 10
Test device: LG V30(Android ver.8.0.0), Galaxy S8(Android 9)
Python version: 3.7

## Link to Appium logs

https://gist.github.com/gyarang/a5b769cbde8593c70213c20b77a0f935

## Code To Reproduce Issue [ Good To Have ]

```
desired_caps = {'platformName': 'Android',
                            'automationName': self.automation,
                            'platformVersion': self.android_version,
                            'deviceName': self.device_name,
                            'udid': self.udid,
                            'app': self.app_file_name,
                            'autoGrantPermissions': True}
self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
```

**Comment by mykola-mokhnach** [comment] 2019-07-31 08:54
Duplicate of https://github.com/appium/appium-espresso-driver/issues?utf8=✓&q=is%3Aissue+is%3Aopen+%22is+not+a+Drawable%22

Unfortunately, there is nothing to do there from the Espresso driver side

**Closed by mykola-mokhnach** 2019-07-31 08:54 UTC
