### ISSUE TITLE
Not able to do any actions on ui controls of my iPad app on real device using Appium 1.6

### ISSUE THREAD

**Issue by gopi09m** [appium/appium#7306] opened 2016-11-28 20:16 UTC
Description

Unable to click/tap on a label or uiastatictext field using appium 1.6

Environment

java client build version or git revision if you use some shapshot: 1.8
Appium server version or git revision if you use some shapshot: 1.6
Desktop OS/version used to run Appium if necessary: macOS
Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: latest
Mobile platform/version under test: iOS IPad App .ipa
Real device or emulator/simulator: Real Device
Details

Unable to click/tap on a label or uiastatictext or button field using appium 1.6 . I was able to find element though.Tried the below code.I tried iosDriver.findElement(By.xpath("//XCUIElementTypeCell[1]")).click() but result is same. I am able to read all the elements but commands to do any actions are not working. And i see the property filedetector mobilelement is null for the returned element,.

Code To Reproduce Issue [ Good To Have ]

          tableViews = iosDriver.findElementsByClassName("XCUIElementTypeButton");
		
		
		System.out.println(iosDriver.getPageSource());
		 
		
		for (MobileElement mElement : tableViews) {
			
			if (mElement!=null  ) {
				System.out.println(mElement.getText());
				mElement.click();
				
				if( mElement.getText()==null) {
					continue;
			}
				if( !mElement.getText().contains("ScanDriverLicence")) {
					continue;
			}

            List<MobileElement>  elemetns = iosDriver.findElementsByClassName("UIAStaticText");
	for (MobileElement mElement : elemetns) {
		System.out.println(mElement.getText());
		if (mElement.getText().contains("Branch108")) {
			
			String originalContext = iosDriver.getContext();
		    Point coordinate = mElement.getLocation();
		    Dimension loc = mElement.getSize();
		    int centerX = loc.getWidth() / 2 + coordinate.getX();
		    int centerY = loc.getHeight() / 2 + coordinate.getY();
		    iosDriver.context("NATIVE_APP");
		    iosDriver.tap(1, centerX, centerY, 2);
		    iosDriver.context(originalContext);
		    
		    mElement.tap(1, 1);
		    mElement.click();
		    
		    
		    JavascriptExecutor js = (JavascriptExecutor) iosDriver;
		    HashMap<String, Double> tapObject = new HashMap<String, Double>();
		    tapObject.put("x", (double) centerX);
		    tapObject.put("y", (double) centerY);
		    tapObject.put("duration", 1.0);
		    tapObject.put("touchCount", 1.0);
		    tapObject.put("tapCount", 1.0);

		    js.executeScript("mobile: tap", tapObject);
		    
		    
			//webElement.submit();
			iosDriver.tap(1, mElement, 2);
			//iosDriver.tap(2, webElement, 1);
			iosDriver.tap(1, mElement, 1);
		
			mElement.click();
			
			break;
		}
The pageSource looks like below:

             <AppiumAUT>
      <XCUIElementTypeApplication name="Customer" label="Customer" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0" x="0" y="0" width="768" height="1024">
    <XCUIElementTypeWindow name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0" x="0" y="0" width="1024" height="768">
        <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0" x="0" y="0" width="1024" height="768">
            <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0" x="0" y="0" width="1024" height="768">
                <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/0" x="120" y="134" width="784" height="500">
                    <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/0/0" x="537" y="134" width="367" height="500">
                        <XCUIElementTypeTable name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/0/0/0" x="537" y="134" width="367" height="500">
                            <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/0/0/0/0" x="537" y="134" width="367" height="98">
                                <XCUIElementTypeStaticText name="Branch108" label="Branch108" value="Branch108" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/0/0/0/0/0" x="552" y="142" width="344" height="21">
                                </XCUIElementTypeStaticText>

**Comment by mykola-mokhnach** [comment] 2016-11-28 21:15
Duplicate of https://github.com/appium/appium/issues/6994

@triager please close

**Closed by mykola-mokhnach** 2016-11-28 21:15 UTC
Labels: NeedsTriage

**Comment by gopi09m** [comment] 2016-11-29 19:15
Does it mean i need to upgrade to appium@1.6.1 ? For me even in the portrait mode the clicks are not working .
