### ISSUE TITLE
Error: Command 'path\\adb.exe -P 5037 -s e93d53d2 shell settings delete global hidden_api_policy_pre_p_apps' exited with code 255

### ISSUE THREAD

**Issue by stenes90** [appium/appium#14481] opened 2020-06-24 10:01 UTC
## The problem

I am not able to start the appium server. I have added ignoreHiddenApiPolicyError capability but I still have this problem. I tried using Appium 1.5, 1.71, 1.80(beta) but every time I am facing the same issue. 

LOGS: https://github.com/appium/appium/files/4824596/appium-server-logs.txt

SetUp: https://user-images.githubusercontent.com/34161502/85535081-28e53d00-b612-11ea-8427-0f28bf2280a7.png

**Comment by mykola-mokhnach** [comment] 2020-06-24 10:03
Duplicate of https://github.com/appium/appium/issues?q=is%3Aissue+%22+writing+to+settings+requires%22+is%3Aclosed

Consider replacing the device model under test

**Closed by mykola-mokhnach** 2020-06-24 10:03 UTC

**Comment by KazuCocoa** [comment] 2020-06-24 10:18
or the capability can identify since 1.18.0 (`appium@beta` for now)
```
[info] [35m[Appium][39m Welcome to Appium v1.17.1
...
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
[warn] [35m[BaseDriver][39m   ignoreHiddenApiPolicyError
../
```
https://github.com/search?q=org%3Aappium+ignoreHiddenApiPolicyError&type=Code
