### ISSUE TITLE
KeepAliveFailure on Android

### ISSUE THREAD

**Issue by ndson040496** [appium/appium#10704] opened 2018-05-17 16:14 UTC
## The problem

It works fine with iOS, but got this error recently with Android 

**This is the error I got from visual studio:**
OpenQA.Selenium.WebDriverException: 'A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://1.2.3.4:4725/wd/hub/session. The status of the exception was KeepAliveFailure, and the message was: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.'

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Desktop OS/version used to run Appium:1.6.1
* Node.js version (unless using Appium.app|exe):v8.0.0
* Mobile platform/version under test:Android API 27 and 23
* Real device or emulator/simulator: Pixel_2_API_27 (emulator)

## Link to Appium logs

https://gist.github.com/ndson040496/e1733898da9e5f173987f1ede2138d4a

## Code To Reproduce Issue [ Good To Have ]

AppiumDriver<IWebElement> driver = new AndroidDriver<IWebElement>(new Uri("http://1.2.3.4:4725/wd/hub"), new DesiredCapabilities(), TimeSpan.FromSeconds(400));

appium --address 1.2.3.4 --port 4725 --default-capabilities '{"platformName":"Android", "deviceName":"Pixel_2_API_27", "avd":"Pixel_2_API_27", "avdLaunchTime":"5000", "appActivity":"com.a.b.activity.Login", "automationName":"UiAutomator2", "newCommandTimeout":"300", "autoGrantPermissions":true, "app":"/Users/devuser/.jenkins/jobs/Automation/workspace/Prod.apk"}'

**Comment by mykola-mokhnach** [comment] 2018-05-17 16:28
Duplicate of https://github.com/appium/appium-dotnet-driver/issues/206

**Closed by mykola-mokhnach** 2018-05-17 16:28 UTC

**Comment by ndson040496** [comment] 2018-05-17 18:11
I don't really see any specific solution for this from other threads.
