### ISSUE TITLE
[Feat]:I'm trying to install uiautomator2 driver in my system but i am getting errror please help me anyone

### ISSUE THREAD

**Issue by S1saravanan** [appium/appium#17761] opened 2022-11-10 06:07 UTC
C:\Users\Saravanan>appium driver install uiautomator2
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev appium-uiautomator2-driver --json' failed with code null.

STDOUT:

STDERR:
                                                              And 

C:\Users\Saravanan>appium driver install uiautomator2
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev appium-uiautomator2-driver --json' failed with code 1.
STDOUT:
STDERR:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: appium@1.22.3
npm ERR! node_modules/appium
npm ERR!   appium@"^1.22.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer appium@"^2.0.0-beta.40" from appium-uiautomator2-driver@2.10.2
npm ERR! node_modules/appium-uiautomator2-driver
npm ERR!   dev appium-uiautomator2-driver@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Saravanan\AppData\Local\npm-cache\eresolve-report.txt for a full report.
{
  "error": {
    "code": "ERESOLVE",
    "summary": "unable to resolve dependency tree",
    "detail": "\nWhile resolving: undefined@undefined\nFound: appium@1.22.3\nnode_modules/appium\n  appium@\"^1.22.3\" from the root project\n\nCould not resolve dependency:\npeer appium@\"^2.0.0-beta.40\" from appium-uiautomator2-driver@2.10.2\nnode_modules/appium-uiautomator2-driver\n  dev appium-uiautomator2-driver@\"*\" from the root project\n\nFix the upstream dependency conflict, or retry\nthis command with --force, or --legacy-peer-deps\nto accept an incorrect (and potentially broken) dependency resolution.\n\nSee C:\\Users\\Saravanan\\AppData\\Local\\npm-cache\\eresolve-report.txt for a full report."
  }
}
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Saravanan\AppData\Local\npm-cache\_logs\2022-11-10T05_12_19_498Z-debug-0.log

**Comment by mykola-mokhnach** [comment] 2022-11-10 06:59
Duplicate of https://github.com/appium/appium/issues/17614

**Closed by mykola-mokhnach** 2022-11-10 06:59 UTC
