### ISSUE TITLE
click element with error 500

### ISSUE THREAD

**Issue by Chris8711** [appium/appium#16282] opened 2021-12-29 03:02 UTC
## The problem

click element with error 500
this element is a system alert dialog
I want to click "取消" button 
![image](https://user-images.githubusercontent.com/84142225/147623423-38857342-7985-402a-a70c-3da6823d8157.png)

## Environment

App Version: 1.22.0
Electron: 7.3.3
Node.js: 12.8.1
xcode: 13.2
real phone: ios: 14

## Link to Appium logs
[HTTP] --> POST /wd/hub/session/64cd2e1d-a21d-4936-af1c-246b7b9cd8dd/element/89010000-0000-0000-3C07-000000000000/click
[HTTP] {"id":"89010000-0000-0000-3C07-000000000000"}
[W3C (64cd2e1d)] Driver proxy active, passing request on via HTTP proxy
[XCUITest] Executing command 'proxyReqRes'
[WD Proxy] Matched '/wd/hub/session/64cd2e1d-a21d-4936-af1c-246b7b9cd8dd/element/89010000-0000-0000-3C07-000000000000/click' to command name 'click'
[WD Proxy] Proxying [POST /wd/hub/session/64cd2e1d-a21d-4936-af1c-246b7b9cd8dd/element/89010000-0000-0000-3C07-000000000000/click] to [POST http://127.0.0.1:8100/session/BA529BF0-470D-4F6F-93C1-C1234A316F2B/element/89010000-0000-0000-3C07-000000000000/click] with body: {"id":"89010000-0000-0000-3C07-000000000000"}
[WD Proxy] Got response with status 500: {"value":{"error":"unknown error","message":"*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil","traceback":"(\n\t0   CoreFoundation                      0x0000000186ef1128 F80FCA31-BF76-3293-8BC6-1729588AE8B6 + 1155368\n\t1   libobjc.A.dylib                     0x000000019a717cb4 objc_exception_throw + 56\n\t2   CoreFoundation                      0x0000000186f5b398 F80FCA31-BF76-3293-8BC6-1729588AE8B6 + 1590168\n\t3   CoreFoundation                      0x0000000186f58bec F80FCA31-BF76-3293-8BC6-1729588AE8B6 + 1580012\n\t4   CoreFoundation                      0x0000000186dd9cf0 F80FCA31-BF76-3293-8BC6-1729588AE8B6 + 11504\n\t5   XCUIAutomation                      0x000000010233ee70 __104-[XCAXClient_iOS interruptingUIElementsAffectingSnapshot:checkForHandledElement:containsHandledElement:]_block_invoke + 1008\n\t6   XCTestCore                          0x000000010249da84 -[XCTContext _runActivityNamed:type:block:] + 244\n\t7   XCTestCore                          0x000000010249ccc8 +[XCTConte...
[W3C] Matched W3C error code 'unknown error' to UnknownError
[HTTP] <-- POST /wd/hub/session/64cd2e1d-a21d-4936-af1c-246b7b9cd8dd/element/89010000-0000-0000-3C07-000000000000/click 500 337 ms - 890

**Comment by mykola-mokhnach** [comment] 2021-12-29 07:31
Duplicate of https://github.com/appium/appium/issues/16025

**Closed by mykola-mokhnach** 2021-12-29 07:31 UTC
