### ISSUE TITLE
Deprecation warning for os.tmpDir() when using node 7.0.0 

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/appium#7177] opened 2016-11-03 20:01 UTC
node 7.0.0 apparently changed os.tmpDir() to os.tmpdir() # hooray change for the sake of change!

If you run Appium 1.6.0 with node 7.0.0, the following warning appears

`(node:78496) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.`

## Workaround
Roll back to node 6.7.0

## Environment
* Appium version (or git revision) that exhibits the issue: 1.6.0
* Desktop OS/version used to run Appium: OS X 10.12.1
* Node.js version (unless using Appium.app|exe): 7.0.0
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment] 2016-11-03 20:20
Duplicate of https://github.com/appium/appium/issues/7157

**Comment by imurchie** [comment] 2016-11-03 20:39
Fixed in next release.

**Closed by imurchie** 2016-11-03 20:39 UTC
Labels: NeedsTriage
