### ISSUE TITLE
Facing "This page is private"(Most likey SSl error page in browser) error page when i execute my web application in IOS simulator.

### ISSUE THREAD

**Issue by Aditya1209** [appium/appium#9649] opened 2017-11-16 13:39 UTC
## The problem

I am planning to execute My Web Application in IOS simulator. When i kicked off execution i am getting "This page is private" error it is most likely SSL certificate kind of issue in Desktop browsers. I tried to resolve this issue by giving "ACCEPT_SSL_CERTS" and "acceptInsecureCerts" these capabilities but still issue not resolved.Please provide me solution on the same.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: IOS 10.12.6
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: Xcode-9
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: appium.app

## Code To Reproduce Issue [ Good To Have ]

			DesiredCapabilities des=new DesiredCapabilities();
				des.setCapability("platfromName","IOS");
				des.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");
				des.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
				des.setCapability("deviceName", "iPhone 6s");
				driver=new IOSDriver(new URL("https://0.0.0.0:4723/wd/hub"), des);

driver.get(""); //provide any site URL which is not secure.() When i provided google URL it was navigating with out any error.

**Comment by mykola-mokhnach** [comment] 2017-11-16 14:04
Duplicate of https://github.com/appium/appium/issues/9536

It looks like Apple did some changes there and now the algorithm needs to be reverse engineered again in order to fix the problem.

**Closed by mykola-mokhnach** 2017-11-16 14:04 UTC
