### ISSUE TITLE
Appium 1.6.4 - get string table using uiautomator2 with language=<languagecode> parameter doesn't work

### ISSUE THREAD

**Issue by lnnp1910** [appium/appium#8317] opened 2017-04-24 23:18 UTC
## The problem

It used to work with by calling driver.app_strings(language='fr') to retrieve french string table. With uiautomator2, it maps to the current device's language (for example, en) and loads English every time. I can't use app_strings function to perform localization testing in multiple languages without changing the device's language anymore with uiautomator2. Any plan for this enhancement?

## Details

If I change the device language to another language, the string table got pulled will reflect that language. The language code ('fr') which got passed into the function driver.app_strings(language='fr') does not take effect. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 (found in 1.6.3)
* Last Appium version that did not exhibit the issue (if applicable): (1.5.3)
* Desktop OS/version used to run Appium: MacOS (with Appium Python Client)
* Node.js version (unless using Appium.app|exe): 7.2.0
* Mobile platform/version under test: 7.1.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Test Scenario:
I tried to load French string table (which has more than 1000 string ids), but it still load the "en" string table, which only contains <10 string ids. I

## Link to Appium logs
- appium log: https://gist.github.com/lnnp1910/b4349b04da5f601d43246c13bbfed178

**Comment by mykola-mokhnach** [comment] 2017-04-25 06:39
Closed as duplicate of https://github.com/appium/appium/issues/8318

**Comment by lnnp1910** [comment] 2017-04-25 17:40
@mykola-mokhnach I think #8318 and #8317 are two different issues. #8318 uses AndroidBootstrap which I believe using uiautomator 1 framework as the backbone. #8317 refers to uiautomator2 with extra added capability of {"automationName": "uiautomator2"}. The logs and errors of the two issues are different as well.

**Comment by mykola-mokhnach** [comment] 2017-04-25 18:39
Then please format the issue summary and description properly so it's clearly visible where the problem is. Also, add all the necessary details, like full logs and code examples.

**Comment by lnnp1910** [comment] 2017-04-25 22:11
@mykola-mokhnach just did for both issues.

**Comment by dpgraham** [comment] 2017-07-20 23:24
Are you still experiencing this issue @lnnp1910?

**Comment by jlipps** [comment] 2017-08-04 20:00
closing due to inactivity, also probably a duplicate of #8930

**Closed by jlipps** 2017-08-04 20:00 UTC
Labels: Bug, NeedsInfo, UIAutomator2
