### ISSUE TITLE
The app will be closed automatically when execute driver.findElements

### ISSUE THREAD

**Issue by 13817458995** [appium/appium#13096] opened 2019-08-20 04:39 UTC
## The problem

The test app will be closed when execute driver.findElements method. It is only will be closed in specific time.
Eg:
driver.findElements
driver.findElements
driver.findElements
driver.findElements

1,2,3 is fine to execute and 4 will close the app.

## Environment

* Appium version (or git revision) that exhibits the issue:1.14.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac 10.14.5
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: 12.3.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

**Comment by mykola-mokhnach** [comment] 2019-08-20 05:08
Please provide the full appium server log along with iOS device logs

**Comment by 13817458995** [comment] 2019-08-20 08:21
> Please provide the full appium server log along with iOS device logs

[HTTP] --> POST /wd/hub/session/59b049bb-bb58-462e-82ea-48f85ba333ca/elements
[HTTP] {"using":"-ios predicate string","value":"value == '例: 23XXXXXXXX@aaaa.cn'"}
[W3C (59b049bb)] Calling AppiumDriver.findElements() with args: ["-ios predicate string","value == '例: 23XXXXXXXX@aaaa.cn'","59b049bb-bb58-462e-82ea-48f85ba333ca"]
[XCUITest] Executing command 'findElements'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 10000 ms for condition
[WD Proxy] Matched '/elements' to command name 'findElements'
[WD Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/140616E4-35D9-43F2-B362-4A649D5B90E5/elements] with body: {"using":"predicate string","value":"value == '例: 23XXXXXXXX@aaaa.cn'"}
[WD Proxy] Got response with status 200: {"value":[],"sessionId":"140616E4-35D9-43F2-B362-4A649D5B90E5","status":0}
[BaseDriver] Waited for 1311 ms so far
[WD Proxy] Matched '/elements' to command name 'findElements'
[WD Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/140616E4-35D9-43F2-B362-4A649D5B90E5/elements] with body: {"using":"predicate string","value":"value == '例: 23XXXXXXXX@aaaa.cn'"}
[WD Proxy] Got response with status 200: {"value":[],"sessionId":"140616E4-35D9-43F2-B362-4A649D5B90E5","status":0}
[BaseDriver] Waited for 2687 ms so far
[WD Proxy] Matched '/elements' to command name 'findElements'
[WD Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/140616E4-35D9-43F2-B362-4A649D5B90E5/elements] with body: {"using":"predicate string","value":"value == '例: 23XXXXXXXX@aaaa.cn'"}
[WD Proxy] Got response with status 200: {"value":"The application under test with bundle id 'com.aaaa' is not running, possibly crashed","sessionId":"140616E4-35D9-43F2-B362-4A649D5B90E5","status":889}
[WD Proxy] Got an unexpected response: {"value":"The application under test with bundle id 'com.aaaa' is not running, possibly crashed","sessionId":"140616E4-35D9-43F2-B362-4A649D5B90E5","status":889}
[MJSONWP] Matched JSONWP error code 889 to UnknownError
[BaseDriver] Waited for 3302 ms so far
[WD Proxy] Matched '/elements' to command name 'findElements'
[WD Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/140616E4-35D9-43F2-B362-4A649D5B90E5/elements] with body: {"using":"predicate string","value":"value == '例: 23XXXXXXXX@aaaa.cn'"}
[WD Proxy] Got response with status 200: {"value":"The application under test with bundle id 'com.aaaa' is not running, possibly crashed","sessionId":"140616E4-35D9-43F2-B362-4A649D5B90E5","status":889}

**Comment by mykola-mokhnach** [comment] 2019-08-20 08:26
> [WD Proxy] Got response with status 200: {"value":"The application under test with bundle id 'com.aaaa' is not running, possibly crashed","sessionId":"140616E4-35D9-43F2-B362-4A649D5B90E5","status":889}

I think the error message is pretty clear

**Comment by 13817458995** [comment] 2019-08-20 08:54
> > [WD Proxy] Got response with status 200: {"value":"The application under test with bundle id 'com.aaaa' is not running, possibly crashed","sessionId":"140616E4-35D9-43F2-B362-4A649D5B90E5","status":889}
> 
> I think the error message is pretty clear

I want to know why the app is closed. what will be crashed?

**Comment by mykola-mokhnach** [comment] 2019-08-20 08:56
Most likely because of a bug in that app. I would try to investigate application logs to find the cause

**Comment by 13817458995** [comment] 2019-08-20 09:00
> Most likely because of a bug in that app. I would try to investigate application logs to find the cause

Only got this error in some machines and some can execute without any error for the same version app

**Comment by mykola-mokhnach** [comment] 2019-08-22 16:32
There is nothing to do here on Appium side. Consider debugging your app.

Closed as not an issue

**Closed by mykola-mokhnach** 2019-08-22 16:32 UTC
Labels: NotABug
