### ISSUE TITLE
appium automation testing

### ISSUE THREAD

**Issue by Gudibanda-Suresh** [appium/appium#19969] opened 2024-04-05 06:37 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Original error: Could not find 'apksigner.jar' in ["D:\\android-sdk\\platform-tools\\apksigner.jar","D:\\android-sdk\\emulator\\apksigner.jar","D:\\android-sdk\\cmdline-tools\\latest\\bin\\apksigner.jar","D:\\android-sdk\\tools\\apksigner.jar","D:\\android-sdk\\tools\\bin\\apksigner.jar","D:\\android-sdk\\apksigner.jar"]. Do you have Android Build Tools installed at 'D:\android-sdk'?
<img width="820" alt="appiumIssue" src="https://github.com/appium/appium/assets/109528504/0ce52f3a-a14e-4f69-a69c-9c35a4766869">

### Expected Behavior

while start session in appium inspector it should automate in android app

### Minimal Reproducible Example

{
  "appium:deviceName": "suresh",
  "appium:udid": "d27d6eef",
  "platformName": "Android",
  "appium:platformVersion": "12 SKQ1.211019.001",
  "appium:appPackage": "com.miui.calculator",
  "appium:appActivity": "com.miui.calculator.cal.CalculatorActivity - Calculator",
  "appium:automationName": "UiAutomator2",
  "appium:autoGrantPermissions": true,
  "appium:noReset": false
}

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

in my mobile appium setting app is installed, but not opening. if one faced this issue requested you to explain clearly how to resolve this issue

**Comment by eglitise** [comment] 2024-04-05 07:11
The error message already states the problem - `Do you have Android Build Tools installed at 'D:\android-sdk'?`
Please check is this is the case.

**Comment by byKosta** [comment] 2024-04-05 08:14
@Gudibanda-Suresh are you using android-studio?

**Comment by Gudibanda-Suresh** [comment] 2024-04-05 08:16
> @Gudibanda-Suresh are you using android-studio?

No, I separately downloaded sdk

**Comment by byKosta** [comment] 2024-04-05 08:17
@Gudibanda-Suresh check the paths. I think problem may be that it was installed in wrong place.

**Comment by byKosta** [comment] 2024-04-05 08:23
> > @Gudibanda-Suresh check the paths. I think problem may be that it was installed in wrong place.
> 
> Ok, Android studio not required right? Only sdk enough

Yeah, but I'm using android studio

**Comment by byKosta** [comment] 2024-04-05 08:48
@Gudibanda-Suresh btw I think there should be many threads on stackoverflow about this and maybe find a solution there. Most likely the problem is with path. Thanks

**Comment by eglitise** [comment] 2024-04-05 12:37
Using Android Studio does make it easier because it comes equipped with many of the prerequisites, but installing separately is fine too. [Check the quickstart tutorial](https://appium.io/docs/en/latest/quickstart/uiauto2-driver/#set-up-android-automation-requirements) for more details.

**Comment by mykola-mokhnach** [comment] 2024-04-06 07:23
Closed as not an issue

**Closed by mykola-mokhnach** 2024-04-06 07:23 UTC
Labels: Needs Info
