### ISSUE TITLE
Appium server crashes when`press_keycode`call fails

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#14214] opened 2020-04-22 09:25 UTC
## The problem
The appium server stop responding to calls with an error `Original error: Error: socket hang up`after that press_keycode call failed. 
Our problem is mainly why does the `press_keycode` failed. 

The error I get for the failed `press_keycode` is:
`[HTTP] --> POST /wd/hub/session/bc8ce412-ad4b-44d5-bef3-7105bfac7e7e/appium/device/press_keycode
[HTTP] {"keycode":23,"sessionId":"bc8ce412-ad4b-44d5-bef3-7105bfac7e7e"}
[debug] [W3C (bc8ce412)] Calling AppiumDriver.pressKeyCode() with args: [23,null,null,"bc8ce412-ad4b-44d5-bef3-7105bfac7e7e",null,"bc8ce412-ad4b-44d5-bef3-7105bfac7e7e"]
[debug] [WD Proxy] Matched '/appium/device/press_keycode' to command name 'pressKeyCode'
[debug] [WD Proxy] Proxying [POST /appium/device/press_keycode] to [POST http://127.0.0.1:8209/wd/hub/session/6d942af4-f8fb-4156-b9ab-bb3edd872f3e/appium/device/press_keycode] with body: {"keycode":23,"metastate":null,"flags":null}
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [W3C (bc8ce412)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
[debug] [W3C (bc8ce412)]     at JWProxy.command (/Users/boazwarshawsky/.nvm/versions/node/v8.16.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:270:13)
[debug] [W3C (bc8ce412)]     at <anonymous>
[HTTP] <-- POST /wd/hub/session/bc8ce412-ad4b-44d5-bef3-7105bfac7e7e/appium/device/press_keycode 500 15 ms - 588
[HTTP]
[HTTP] --> GET /wd/hub/session/bc8ce412-ad4b-44d5-bef3-7105bfac7e7e/screenshot`

## Environment
* Appium version (or git revision) that exhibits the issue: 1.15.1 and 1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: CLI
* Node.js version (unless using Appium.app|exe): 12.16.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android TV
* Real device or emulator/simulator: Android Emulator
* Appium CLI or Appium.app|exe: CLI 

## Details

The problem is not reproducing 100% of the time. but it does from time to time.

## Link to Appium logs
https://assets-secure.applicaster.com/qa/zapp_qa/manual/boaz/sending_key_code.log

## Code To Reproduce Issue [ Good To Have ]
Call: `self.driver_.press_keycode(key_code)`

**Comment by mykola-mokhnach** [comment] 2020-04-22 10:25
Duplicate of https://github.com/appium/appium/issues/13873

**Closed by mykola-mokhnach** 2020-04-22 10:25 UTC
