### ISSUE TITLE
Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)

### ISSUE THREAD

**Issue by MaisGurbanov** [appium/appium#8143] opened 2017-04-01 14:23 UTC
Hello guys,

After update of Xcode to 8.3, I got problem with WebDriverAgent. It successfully installs on device but while testing it opens/closes immediately at the same time and returns error.

Equipments:
Appium 1.6.3
Xcode 8.3
iPhone 5s 10.0.1

Please find log in below link:

[Log.txt](https://github.com/appium/appium/files/887702/Log.txt)

Thanks in advance.

**Comment by mykola-mokhnach** [comment] 2017-04-01 15:40
Closed as duplicate of https://github.com/appium/appium/issues/8137

**Closed by mykola-mokhnach** 2017-04-01 15:40 UTC
Labels: NeedsTriage

**Comment by MaisGurbanov** [comment] 2017-04-01 16:06
@mykola-mokhnach I added -Wno-partial-availability to ProjectSettings file but it is still the same situation.

**Comment by mykola-mokhnach** [comment] 2017-04-01 16:07
You need update to 1.6.4-beta first

**Comment by MaisGurbanov** [comment] 2017-04-01 16:09
@mykola-mokhnach I uninstalled appium and installed beta 1.6.4-beta.2. Configured WebDriverAgent file according to documentation. All settings are done properly.

**Comment by MaisGurbanov** [comment] 2017-04-01 16:14
It is the result when I try to build and test from terminal:

https://gist.github.com/MaisGurbanov/9d1e3b1e81177dc1e90aa7551e933bdd

**Comment by mykola-mokhnach** [comment] 2017-04-01 16:22
you need to run bootstrap and download third-party modules to make it compiling
```
./Scripts/bootstrap.sh -d
```

**Comment by MaisGurbanov** [comment] 2017-04-01 16:33
@mykola-mokhnach I followed the below steps:

1. npm install -g appium@beta
2. cd path/to/WebDriverAgent folder
3. mkdir -p Resources/WebDriverAgent.bundle
4. ./Scripts/bootstrap.sh -d
5. open WebDriverAgent.xcodeproj
6. configured it as in attached screenshots
7. run xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test


![1](https://cloud.githubusercontent.com/assets/15858992/24580511/53217f74-171a-11e7-80cd-e242b7d8eddf.png)
![2](https://cloud.githubusercontent.com/assets/15858992/24580512/5361d024-171a-11e7-8687-164534ea2879.png)
![3](https://cloud.githubusercontent.com/assets/15858992/24580513/5362c114-171a-11e7-89bc-54d9e7e3f139.png)
![4](https://cloud.githubusercontent.com/assets/15858992/24580514/5365c4f4-171a-11e7-8db2-992202102bad.png)

**Comment by mykola-mokhnach** [comment] 2017-04-01 17:25
Looks good, but such errors

```
2017-04-01 20:09:48.733204 XCTRunner[363:30792] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2017-04-01 20:09:48.733324 XCTRunner[363:30792] (dlopen_preflight(/var/containers/Bundle/Application/CD438479-34B4-4F0D-8BE3-3F10DB1B9C2D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/RoutingHTTPServer.framework/RoutingHTTPServer
  Referenced from: /private/var/containers/Bundle/Application/CD438479-34B4-4F0D-8BE3-3F10DB1B9C2D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Reason: no suitable image found.  Did find:
        /private/var/containers/Bundle/Application/CD438479-34B4-4F0D-8BE3-3F10DB1B9C2D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: required code signature missing for '/private/var/containers/Bundle/Application/CD438479-34B4-4F0D-8BE3-3F10DB1B9C2D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.f)

```

are usually shown if the source is missing something.

**Comment by MaisGurbanov** [comment] 2017-04-01 18:04
@mykola-mokhnach what do you suggest to do?

**Comment by mykola-mokhnach** [comment] 2017-04-01 18:25
delete appium completely, make sure there are no leftovers and try the same steps one more time.

**Comment by MaisGurbanov** [comment] 2017-04-01 19:34
@mykola-mokhnach I uninstalled and installed appium 1.6.4-beta.2 again. But the problem is still continuing. Maybe there is problem with Xcode 8.3 version?

**Comment by mykola-mokhnach** [comment] 2017-04-01 19:38
Shouldn't be - it works for other people. Probably, check it with iOS developers.

**Comment by MaisGurbanov** [comment] 2017-04-02 15:11
@mykola-mokhnach is it possible for you to connect remotely to my laptop and try to configure appium? Maybe I did something wrong. I tried all possible solutions all night but nothing helped.

**Comment by MaisGurbanov** [comment] 2017-04-02 21:17
@mykola-mokhnach it worked for me. At last I removed developer certificate from keychain and added new one. But now there is another issue: https://github.com/appium/appium/issues/8146

**Comment by mykola-mokhnach** [comment] 2017-04-03 05:51
This one looks like a bug in Appium. Please temporary disable screenshoting to workaround it. I'll create a patch soon
