### ISSUE TITLE
Socket hang up running tests on Android device 

### ISSUE THREAD

**Issue by getloud** [appium/appium#14362] opened 2020-05-20 16:21 UTC
## The problem

Cannot run my test for hybrid app on android, app closed at the begging of run

## Environment

* Appium version (or git revision) that exhibits the issue: v1.17.1-beta.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.15.5 Beta (19F83c)
* Node.js version (unless using Appium.app|exe): 14.3.0
* Npm or Yarn package manager: 6.14.5
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Pixel 2 real device
* Appium CLI or Appium.app|exe: 
* chromedriver 81.0.4044.138
* WebView 81.0.4044.138
* selenide 5.11.1

## Details

1) run tests
2) hybrid app is opened 
3) app is closed and test is stoped with error (check logs)

## Link to Appium logs
https://gist.github.com/getloud/74264ec747d88bf86453e54649818f22

**Comment by mykola-mokhnach** [comment] 2020-05-20 17:14
> [Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTRAP

Seems like Chromedriver itself is crashing. Please report the issue to Google.

**Comment by mykola-mokhnach** [comment] 2020-05-20 17:14
Could be a duplicate of https://github.com/appium/appium/issues/13925

**Comment by getloud** [comment] 2020-05-20 19:21
Thanks

**Comment by mykola-mokhnach** [comment] 2020-05-22 07:55
There is nothing more we could do on this issue. closed as third party

**Closed by mykola-mokhnach** 2020-05-22 07:55 UTC
Labels: Mobile Chrome, ThirdParty
