### ISSUE TITLE
Changing locale capability doesn't change the keyboard language

### ISSUE THREAD

**Issue by facusantillo** [appium/appium#15319] opened 2021-05-03 09:51 UTC
## The problem

Changing local capability is not switching the keyboard layout (emulator and real devices)

## Environment

* Appium version (or git revision) that exhibits the issue: latest
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: latest
* Node.js version (unless using Appium.app|exe): 12.18
* Npm or Yarn package manager: yarn
* Mobile platform/version under test: iOS 14.4
* Real device or emulator/simulator: Simulator and real device
* Appium CLI or Appium.app|exe:

## Details

Setting the appium locale capability is changing the language of the OS but when using the keyboard the language is not being changed, resulting in unexpected behaviours. 

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2021-05-03 10:56
Duplicate of https://github.com/appium/appium/issues/13348

Feel free to add a PR if you know how to implement such feature

**Closed by mykola-mokhnach** 2021-05-03 10:56 UTC
