### ISSUE TITLE
Longpress throws a java.lang.NumberFormatException.

### ISSUE THREAD

**Issue by ReaperMantis** [appium/appium#14616] opened 2020-08-02 04:49 UTC
## The problem

LongPress throws a java.lang.NumberFormatException.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.18.0
* Last Appium version that did not exhibit the issue (if applicable): v1.17.1
* Desktop OS/version used to run Appium: Linux/Ubuntu 20.04
* Node.js version (unless using Appium.app|exe): N/A
* Npm or Yarn package manager: N/A
* Mobile platform/version under test: Android v10
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: AppImage

## Details

When creating a new TouchAction longPress with LongPressOptions, a java.lang.NumberFormatException error will be thrown.

## Link to Appium logs

[https://gist.github.com/ReaperMantis/16a2e5abbdca82acdc00c80f6aa2ab6b](url)

## Code To Reproduce Issue [ Good To Have ]

`import io.appium.java_client.MobileElement;
import io.appium.java_client.TouchAction;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.touch.LongPressOptions;
import io.appium.java_client.touch.offset.ElementOption;
import org.openqa.selenium.By;
import org.openqa.selenium.remote.DesiredCapabilities;

import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

public class Test {
    private static AndroidDriver driver;

    private static final String shortcutName="Keep Notes";

    public static void main(String[] args) {
        DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
        desiredCapabilities.setCapability("platformName", "Android");
        desiredCapabilities.setCapability("deviceName", "Android Device");
        desiredCapabilities.setCapability("automationName", "UiAutomator2");
        URL remoteUrl = null;
        try {
            remoteUrl = new URL("http://localhost:4723/wd/hub");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        driver = new AndroidDriver(remoteUrl, desiredCapabilities);

        TouchAction action = new TouchAction(driver);
        MobileElement e = (MobileElement) driver.findElement(By.xpath("//android.widget.TextView[contains(@content-desc,\""+shortcutName+"\")]"));
        
        /* The following line will throw a java.lang.NumberFormatException */
        action.longPress(LongPressOptions.longPressOptions().withElement(ElementOption.element(e)).withDuration(Duration.ofSeconds(3))).release().perform();

        driver.quit();
    }
}`

**Comment by mykola-mokhnach** [comment] 2020-08-02 06:24
Duplicate of https://github.com/appium/appium/issues/14601

**Closed by mykola-mokhnach** 2020-08-02 06:24 UTC
