### ISSUE TITLE
iOS: Large disk space consumption

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#14944] opened 2020-12-11 12:46 UTC
## The problem

It was found out that executing iOS tests eats disk space. Reason of this that temp "file" creates in (examples of folders):
```
/private/var/folders/q3/02m9wscj2rg93_l37d7wsd3r0000gq/T/20201110-48659-qux1f6.1c7h
/private/var/folders/q3/02m9wscj2rg93_l37d7wsd3r0000gq/T/20201110-71904-1rpeavl.qgbh
```
where "file" is app under test in ".app" format.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18 ... 1.19
* Desktop OS/version used to run Appium: MacOS 10.15.7 and earlier
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device

## Details
1. remember current disk space
2. execute some test with real device which also include app replace on phone
3. check again disk space

Result: disk space reduced to size of app x number of tests executed. It cause easy to eat 100Gb for us in few days.

## Log
```
2020-12-11 12:41:09:018 - [debug] [BaseDriver] Extracted 1238 items from '/Users/xxx/Documents/test/app/xxx.ipa' in 2985ms
2020-12-11 12:41:09:022 - [debug] [BaseDriver] Matched 1 item in the extracted archive. Assuming 'Payload/xxx.app' is the correct bundle
2020-12-11 12:41:09:024 - [BaseDriver] Unzipped local app to '/var/folders/_r/nbsgp9v95gq0ht_43kqc1lqc0000gq/T/20201111-78468-xfhuv4.0u4tn/xxx.app'
2020-12-11 12:41:09:025 - [debug] [BaseDriver] Event 'appConfigured' logged at 1607690469025 (14:41:09 GMT+0200 (Eastern European Standard Time))
2020-12-11 12:41:09:025 - [debug] [XCUITest] Checking whether app '/var/folders/_r/nbsgp9v95gq0ht_43kqc1lqc0000gq/T/20201111-78468-xfhuv4.0u4tn/xxx.app' is actually present on file system
2020-12-11 12:41:09:025 - [debug] [XCUITest] App is present
```

## Workaround:
restart mac removes these files

**Comment by mykola-mokhnach** [comment] 2020-12-11 15:02
Duplicate of https://github.com/appium/appium/issues/14550

**Comment by amedvedjev** [comment] 2020-12-11 15:42
by some reason it was not an issue few months ago.... anyway thanks will try workaround

**Closed** 2020-12-14 06:19 UTC
Labels: NeedsInfo, NotABug
