### ISSUE TITLE
 dyld: Library not loaded: @rpath/XCTest.framework/XCTest || xcodebuild failed with code 65

### ISSUE THREAD

**Issue by anshu1987** [appium/appium#10224] opened 2018-02-20 18:55 UTC
## The problem

Trying to Execute Automation Test on  iOS Real Device.Appium and Web Driver are successfully Setup.
But after executing getting error xcodebuild failed with code 65.
## Environment

* Appium version (or git revision) that exhibits the issue: 1.7
* Last Appium version that did not exhibit the issue (if applicable): 1.7
* Desktop OS/version used to run Appium: 10.12.6(Mac)
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:11.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Link to Appium Logs : https://gist.github.com/anshu1987/de2c7f2c85da06573000d1b957f4bb7f

## Code To Reproduce Issue [ Good To Have ]
My Desired capabilties:
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
capabilities.setCapability(MobileCapabilityType.SUPPORTS_JAVASCRIPT, true);
capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 120);
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, getDeviceName());
capabilities.setCapability(MobileCapabilityType.UDID, getUDID());
capabilities.setCapability(CapabilityType.BROWSER_NAME, BrowserUtil.getBrowser().getPropertyValue());
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, PropertiesLoader.getPlatformName());
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, getVersion());
capabilities.setCapability("xcodeOrgId", "2YVWH85J83");
capabilities.setCapability("xcodeSigningId", "iPhone Developer");

**Comment by anshu1987** [comment] 2018-02-20 18:59
@imurchie  : Any Suggestion.

**Comment by mykola-mokhnach** [comment] 2018-02-20 19:28
Duplicate of https://github.com/facebook/WebDriverAgent/issues/664

**Closed** 2018-02-22 12:52 UTC
Labels: NotABug, ThirdParty
