### ISSUE TITLE
[Appium 1.5] IOS coordinate reversed, vertical is x, horizontal is y.

### ISSUE THREAD

**Issue by HailongZhang** [appium/appium#6257] opened 2016-03-09 03:23 UTC
## The problem

IOS coordinate is reversed, vertical is x, horizontal is y, so swipe and tap coordinate not working after upgrade. Android platform works well, no change.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.0
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: Mac 10.11.3
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iphone 6s
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

After upgrade appium from 1.4.16 to 1.5.0, Appium::TouchAction.new.press(x: start_x, y: start_y).wait(duration).move_to(x: end_x, y:  end_y).release.perform not working. I found start_x changed to start_y, start_y changed to start_x. 

## Code To Reproduce Issue [ Good To Have ]
 Not working: Appium::TouchAction.new.press(x: 300, y: 100).wait(500).move_to(x: 50, y:  100).release.perform.  # swipe from right to left, ever worked in 1.4.16
If switch start_x and start_y, it works:
Appium::TouchAction.new.press(x: 100, y: 300).wait(500).move_to(x: 100, y:  50).release.perform
![screen shot 2016-03-08 at 10 33 50 am](https://cloud.githubusercontent.com/assets/16573179/13624449/375064da-e5e9-11e5-8e47-78656a584448.png)

**Comment by scottdixon** [comment] 2016-03-09 18:25
Thanks for reporting @HailongZhang. Looking into it. Can you please include your Appium logs as a gist?

**Comment by HailongZhang** [comment] 2016-03-10 09:05
@scottdixon 
I think the log is not much useful. If the coordinate is with screen, the action is success, no error message, if the coordinate is out of screen , it shows as the attached screenshot.

Thanks

![screen shot 2016-03-10 at 5 00 32 pm](https://cloud.githubusercontent.com/assets/16573179/13664377/d828abd0-e6e1-11e5-92ae-6a09522a2bae.png)

**Comment by scottdixon** [comment] 2016-03-10 17:24
The logs would be helpful in determining where the problem lies (ruby client, Appium or instruments). Please post your 'success' logs.

**Comment by shermanericSF** [comment] 2016-03-10 23:54
Hey Scott.  I work with Zhe who originally posted this.  I'll put some
gists up in addition to whatever Zhe may have.
Specifically:

    *1.4.16.touchaction.ios9.2.sim
<https://gist.github.com/shermanericSF/250c63a42f14cfd27b8c>  (success) *
https://gist.github.com/shermanericSF/250c63a42f14cfd27b8c
    *1.5.touchaction_ios_9.2_sim
<https://gist.github.com/shermanericSF/a231c3c3695206f3aa99>
(failure) https://gist.github.com/shermanericSF/a231c3c3695206f3aa99
<https://gist.github.com/shermanericSF/a231c3c3695206f3aa99>*


Nothing is different between the success and failure gists except for the
appium version.  (I think Zhe used iPhone 6s I used 5S but essentially I'm
seeing the same thing Zhe is.


Here are the gems we are using.
Thanks in advance!
Eric

source 'https://www.rubygems.org'

gem 'appium_lib',         '~> 8.0.0'
gem 'rest-client',        '~> 1.8.0'
gem 'rspec',              '~> 2.14.1'
gem 'cucumber',           '~> 1.3.15'
gem 'rspec-expectations', '~> 2.14.5'
gem 'spec',               '~> 5.3.4'
gem 'sauce_whisk',        '~> 0.0.13'
gem 'test-unit',          '~> 2.5.5' # required for bundle exec ruby
xunit_android.rb
gem 'nokogiri',           '~> 1.6.6'
gem 'awesome_print',      '~> 1.6'
gem 'json',               '~> 1.8'
gem 'selenium-webdriver', '~> 2.48'
gem 'toml',               '~> 0.0'
gem 'rake-hooks',         '~>1.2.3'
gem 'eyes_selenium',      '~> 2.23.0'
gem 'net-ssh',            '~> 3.0', '>= 3.0.1'
gem 'net-scp',            '~> 1.2', '>= 1.2.1'

**Comment by shermanericSF** [comment] 2016-03-10 23:56
Hey Scott.  I work with Zhe who originally posted this.  I'll put some gists up in addition to whatever Zhe may have.
**Specifically**
    1.4.16.touchaction.ios9.2.sim: [https://gist.github.com/shermanericSF/250c63a42f14cfd27b8c]
    1.5.touchaction_ios_9.2_sim  (failure) [https://gist.github.com/shermanericSF/a231c3c3695206f3aa99]

**Note:**
Nothing is different between the success and failure gists except for the appium version.  (I think Zhe used iPhone 6s I used 5S but essentially I'm seeing the same thing Zhe is.


Here are the gems we are using.
Thanks in advance!
Eric


'
source 'https://www.rubygems.org'

gem 'appium_lib',         '~> 8.0.0'
gem 'rest-client',        '~> 1.8.0'
gem 'rspec',              '~> 2.14.1'
gem 'cucumber',           '~> 1.3.15'
gem 'rspec-expectations', '~> 2.14.5'
gem 'spec',               '~> 5.3.4'
gem 'sauce_whisk',        '~> 0.0.13'
gem 'test-unit',          '~> 2.5.5' # required for bundle exec ruby xunit_android.rb
gem 'nokogiri',           '~> 1.6.6'
gem 'awesome_print',      '~> 1.6'
gem 'json',               '~> 1.8'
gem 'selenium-webdriver', '~> 2.48'
gem 'toml',               '~> 0.0'
gem 'rake-hooks',         '~>1.2.3'
gem 'eyes_selenium',      '~> 2.23.0'
gem 'net-ssh',            '~> 3.0', '>= 3.0.1'
gem 'net-scp',            '~> 1.2', '>= 1.2.1'
'

**Comment by scottdixon** [comment] 2016-03-11 00:48
Thanks, Eric. Looking into it.

**Comment by scottdixon** [comment] 2016-03-11 21:00
I just ran the below on [this app](https://github.com/lukagabric/LGDragDrop) and 1.4 + 1.5 were consistent.

@shermanericSF @HailongZhang Any chance you could share the app (or a failing app example) + test script so I can reproduce this?

```
var desired = { 
  platformName: 'iOS',
  deviceName: 'iPhone 6',
  platformVersion: 9.2,
  app: 'LGDragDrop.app'
}

driver
.init(desired)
.elementById('Show Drag/Drop View').then(function(element){
  return element.tap();
})
.then(function(){
  var action = new TouchAction(driver);
  action
    .press({x:140, y:115})
    .wait(2500)
    .moveTo({x: 0, y: 255})
    .wait(2500)
    .moveTo({x: 100, y: 0})
    .wait(2500)
    .moveTo({x: 0, y: -255})
    .wait(2500)
    .moveTo({x: -200, y: 0})
    .wait(2500)
    .moveTo({x: 0, y: 255})
    .wait(2500)
    .moveTo({x: 100, y: 0})
    .wait(2500)
    .release();
  return action.perform();
})
.fin(function(){ 
  return driver.quit();
});
```

**Comment by shermanericSF** [comment] 2016-03-14 17:25
Hi Scott,
Is it possible for me to directly email you?  I'm not sure on the ruleset
of publicly making our app available to the world.  I could give you
specifics there.

Thanks!!
Eric

**Comment by scottdixon** [comment] 2016-03-14 17:37
@shermanericSF - that would be great: scottdixon *at* saucelabs *dot* com

**Comment by shermanericSF** [comment] 2016-03-14 18:55
Awesome!
I sent something from my work account.  Hope it makes sense.  You can email
me directly if Problems.
Thanks!!

**Comment by scottdixon** [comment] 2016-03-15 17:59
Thanks for the sample app - I was able to reproduce. It looks like 1.4 uses absolute positioning for iOS, whereas 1.5 is relative to the initial press. I've run this by @imurchie who confirms 1.5 is using the correct method and 1.4 (iOS) was broken.

Here are two examples dragging from 100,100 to 200,200 and back to 0,0

**1.5 is relative to the initial press:**
```
.press({x:100, y:100}) // Start at 100,100
.moveTo({x: 100, y: 100}) // Move to 200,200 (as in, an additional 100 in each direction)
.moveTo({x: -200, y: -200}) // Move to 0,0
```

**1.4 is absolute (iOS Only, Android works correctly):**
```
.press({x:100, y:100}) // Start at 100,100
.moveTo({x: 200, y: 200}) // Move to 200,200
.moveTo({x: 0, y: 0}) // Move to 0,0
```

So you'll need to update your test - to swipe left you can:
```
press(x: 200, y: 300).move_to(x: -200, y: 0).release.perform
```

Let me know if this resolves your issue.

**Comment by SrinivasanTarget** [comment] 2016-03-15 18:04
@scottdixon Would be good if we document this? What do you say?

**Comment by scottdixon** [comment] 2016-03-15 18:08
@SrinivasanTarget - in progress

**Comment by SrinivasanTarget** [comment] 2016-03-15 18:10
Thanks @scottdixon

**Comment by marcallenbetts** [comment] 2016-03-15 18:29
Would this change in 1.5 account for the swipe() methods in the Java client to not work correctly?

**Comment by scottdixon** [comment] 2016-03-15 21:43
@marcallenbetts - could do, can you please file an issue with more info (specifically, logs)?

**Comment by shermanericSF** [comment] 2016-03-15 22:11
Thanks Scott!!
Scott:  I'm good if you want to close this

(FYI:  for anyone reading this - relates to our company's code, not Appium source :) )

@HailongZhang I've verified in our  bbCommon.rb > bb_swipe_pixel, specifically this:
bb_swipe_pixel(200,300,-200,0,500)

That what @scottdixon is saying is confirmed and correct.  I was able to swipe to the next page in bb student.

let me know if you want me to try and update this - although you may be closer to our code and have more time :)

**Comment by scottdixon** [comment] 2016-03-15 22:15
Thanks for the update @shermanericSF and thanks for flagging this @HailongZhang  - updating docs to avoid confusion in future.

**Closed by scottdixon** 2016-03-15 22:15 UTC
Labels: iOS
