### ISSUE TITLE
Unable to run tests against 1.5 beta8 on Android

### ISSUE THREAD

**Issue by JaniJegoroff** [appium/appium#5936] opened 2015-12-18 12:05 UTC
I'm unable to run Android tests against Appium server `1.5 beta8`. According to logs error is about app was not launched which is wrong since app is launched fine on device. Everything is working fine with Appium server `1.4.16`.

Environment
```
Mac OS X 10.11.2
Ruby 2.1.5p273
node v5.1.1
npm 3.3.12
```
Steps
```
1. Globally install Appium 1.5 beta 8 server
2. Connect Android device
3. Start Appium server
4. Launch the tests
```
Expected result
```
Tests are running as smoothly as with Appium server version 1.4.16
```
Actual result
```
Janis-MacBook-Air:appium janijegoroff$ appium
[Appium] Welcome to Appium v1.5.0-beta8 (REV 300441be033c7e47ae26de29137aa985ad7169d4)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
<clip>
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/janijegoroff/android-development/sdk/platform-tools/adb with args: ["-s","fc56bab7","shell","dumpsys","window","windows"]
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/janijegoroff/android-development/sdk/platform-tools/adb with args: ["-s","fc56bab7","shell","dumpsys","window","windows"]
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/janijegoroff/android-development/sdk/platform-tools/adb with args: ["-s","fc56bab7","shell","dumpsys","window","windows"]
[ADB] Error: MY-APP.activities.local/.MY-APP.activity.FirstLaunchActivity never started
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/apk-utils.js:130:7)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
 [Error: MY-APP.activities.local/.MY-APP.activity.FirstLaunchActivity never started]
[ADB] Error: Error occured while starting App. Original error: MY-APP.activities.local/.MY-APP.activity.FirstLaunchActivity never started
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/apk-utils.js:80:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
 [Error: Error occured while starting App. Original error: MY-APP.activities.local/.MY-APP.activity.FirstLaunchActivity never started]
[debug] [AndroidDriver] Shutting down Android driver
<clip>
```

Am I missing something here?

**Comment by JaniJegoroff** [comment] 2016-01-04 15:19
Alright, debugged this a bit further and looks like Appium confuses about `package name` and `application id`. Workaround is to change `application id`.

Package name: `"com.aa.bb.android.cc"`
Activities are defined like this: `".activity.FirstLaunchActivity"`

Currently not working:
```
app id: "com.aa.bb.android.cc.activities.local"
```
Workaround:
```
app id: "com.aa.bb.android.cc.activity"
```

Hope this helps to identify and fix the issue on Appium side since releases `1.4.x` are working fine with the same app.

**Comment by apallin** [comment] 2016-01-13 18:10
+1 I am experiencing the same issues.  We shouldn't have to change what app configuration we are waiting for a new Appium release.  Any movement on this?

**Comment by apallin** [comment] 2016-01-13 18:28
This is also occurring on 1.5 beta11 as well.

**Comment by moizjv** [comment] 2016-01-25 19:44
Looking at it

**Comment by moizjv** [comment] 2016-01-25 21:47
@apallin @JaniJegoroff can you paste full logs for appium 1.4.16 and appium 1.5 beta. I am unable to reproduce this, it would be really helpful to look at logs of what is parsed as package and activity in 1.5 as opposed to 1.4.16. Thanks

**Comment by JaniJegoroff** [comment] 2016-01-25 22:14
@moizjv Here are the full logs: https://gist.github.com/JaniJegoroff/052edc52632e99048dbe

**Comment by moizjv** [comment] 2016-01-25 22:50
@JaniJegoroff thanks for that! looks like we are parsing the same things for both versions.

For 1.4.16
```
info: [debug] Parsing package and activity from app manifest
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from /Users/janijegoroff/android-development/sdk/build-tools/android-4.4W/aapt
info: [debug] Extracting package and launch activity from manifest.
info: [debug] executing cmd: /Users/janijegoroff/android-development/sdk/build-tools/android-4.4W/aapt dump badging /Users/janijegoroff/projects/mobile-android-app/bdd/app-local-debug.apk
info: [debug] badging package: com.ga.aaa.android.bbb.activities.local
info: [debug] badging act: com.ga.aaa.android.bbb.activity.FirstLaunchActivity
info: [debug] Parsed package and activity are: com.ga.aaa.android.bbb.activities.local/com.ga.aaa.android.bbb.activity.FirstLaunchActivity
```
for 1.5

```
[debug] [ADB] badging package: com.ga.aaa.android.bbb.activities.local
[debug] [ADB] badging act: com.ga.aaa.android.bbb.activity.FirstLaunchActivity
[debug] [AndroidDriver] Parsed package and activity are: com.ga.aaa.android.bbb.activities.local/com.ga.aaa.android.bbb.activity.FirstLaunchActivity
[debug] [ADB] Uninstalling com.ga.aaa.android.bbb.activities.local
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/janijegoroff/android-development/sdk/platform-tools/adb with args: ["-s","emulator-5554","shell","am","force-stop","com.ga.aaa.android.bbb.activities.local"]
[debug] [ADB] Running /Users/janijegoroff/android-development/sdk/platform-tools/adb with args: ["-s","emulator-5554","uninstall","com.ga.aaa.android.bbb.activities.local"]
```

And we are waiting for same things in both versions

1.4.16:
```
Waiting for pkg "com.ga.aaa.android.bbb.activities.local" and activity "com.ga.aaa.android.bbb.activity.FirstLaunchActivity" to be focused
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /Users/janijegoroff/android-development/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
```
1.5:

```
Waiting for pkg: com.ga.aaa.android.bbb.activities.local and activity: com.ga.aaa.android.bbb.activity.FirstLaunchActivity to be focusedv
```

Not sure what we are missing. Can you send this apk or similar apk so we can reproduce this issue?

**Comment by JaniJegoroff** [comment] 2016-01-25 22:58
@moizjv Unfortunately I cannot send this apk and at the moment I don't have similar in hand.

@apallin Do you have apk that could be used to reproduce the issue?

**Comment by moizjv** [comment] 2016-01-25 22:59
@JaniJegoroff to go in little more depth, we use `adb -s emulator-5554 shell "dumpsys window windows"` command to get information about focused activity and package.

**Comment by moizjv** [comment] 2016-01-25 22:59
can you get that information around time when it actually tries it?

**Comment by moizjv** [comment] 2016-01-25 23:03
that information should be same for both the appium versions, only way we consume it should change, it will be interesting to see what is different in both the versions

**Comment by JaniJegoroff** [comment] 2016-01-25 23:31
I updated gist with `adb -s emulator-5554 shell "dumpsys window windows"` dumps. For me both dumps looks exactly the same.

**Comment by JaniJegoroff** [comment] 2016-01-29 16:19
This seems to be fixed now. I can start tests without problems. :+1:

**Comment by TikhomirovSergey** [comment] 2016-01-31 14:41
I could reproduce this problem in Selendroid mode: 

```java
        private static int SELENDROID_PORT = 9999;
...

        AppiumServiceBuilder builder = new AppiumServiceBuilder().withArgument(GeneralServerFlag.AUTOMATION_NAME, AutomationName.SELENDROID);
        service = builder.build();
        service.start();

        File appDir = new File("src/test/java/io/appium/java_client");
        File app = new File(appDir, "ApiDemos-debug.apk");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
        capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
        capabilities.setCapability(MobileCapabilityType.SELENDROID_PORT, SELENDROID_PORT);
        driver = new AndroidDriver<WebElement>(service.getUrl(), capabilities);
```

The server output: https://gist.github.com/TikhomirovSergey/d462ec3c42dcb56d8837

**Comment by TikhomirovSergey** [comment] 2016-01-31 14:50
https://github.com/appium/java-client/issues/302

**Comment by TikhomirovSergey** [comment] 2016-01-31 14:59
https://github.com/appium/appium-dotnet-driver/issues/136

**Closed** 2016-02-01 16:25 UTC
Labels: 1.5-beta, Android, Bug
