### ISSUE TITLE
Next generation appium documentation roadmap

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#5684] opened 2015-10-05 04:05 UTC
**Overview**

A number of large JavaScript / node.js based projects have migrated their documentation to GitHub. There's an opportunity to significantly improve the appium documentation experience by rethinking our current approach.

**Roadmap**
- Delete Slate
- Rewrite deployment script in node.js
- Bootstrap language selector
  - See [Apache Spark example](https://spark.apache.org/examples.html)
  - [Nav tabs](http://getbootstrap.com/components/#nav-tabs) are a perfect fit
- Use Jekyll to render static HTML pages
  - Electron [has a great docs page](http://electron.atom.io/docs/v0.33.0/) and [uses markdown](https://github.com/atom/electron/tree/master/docs)
- New CSS design that works well on mobile & desktop
  - Either commission a web designer or find an existing open source option

**Related blog posts**
- [How GitHub uses GitHub to document GitHub](https://github.com/blog/1939-how-github-uses-github-to-document-github)
- [Electron Documentation architecture](http://blog.atom.io/2015/06/04/electron-doumentation.html)
- [Visual Studio Code documentation](http://blogs.msdn.com/b/vscode/archive/2015/09/11/vscode-documentation-moves-to-github.aspx)

**Comment by bootstraponline** [comment] 2016-05-03 18:37
https://docs.microsoft.com/teamblog/introducing-docs-microsoft-com/ looks awesome. all their docs are markdown on github

**Comment by SrinivasanTarget** [comment] 2016-05-03 18:41
Wow this looks cool

**Comment by bootstraponline** [comment] 2016-05-03 18:50
processing scripts are in node:
https://github.com/Microsoft/vscode-docs/tree/master/scripts

**Comment by dpgraham** [comment] 2017-06-21 20:13
Closing this as duplicate of: https://github.com/appium/appium/issues/8586

**Closed by dpgraham** 2017-06-21 20:13 UTC
Labels: Enhancement
