### ISSUE TITLE
Appium server cannot connect to Android R (11) device because of the ‘platformVersion’

### ISSUE THREAD

**Issue by jlshipman** [appium/appium#14151] opened 2020-04-07 15:10 UTC
## The problem

Appium server cannot connect to Android R (11) device because of the ‘platformVersion’

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator:emulator
* Appium CLI or Appium.app|exe:{"version":"1.16.0","git-sha":"7f8bec63e9c50a13fbcd6212385d66c102452661","built":"2019-12-23T20:12:47Z"}

## Details

I am trying to connect appium with android devices that are running android R.

Appium version: 1.16.0
Android version: 11.0 (R, API: R)

I first tried to set the ‘platformVersion’ capability to 11.0, but then after I tried to start the session, an error was thrown that no device with platform version 11.0 is connected.

However, after I executed the following command:
adb -s emulator-5556 shell getprop ro.build.version.release

I understood that the platformVersion is ‘R’.

But when I try to use R as a value for ‘platformVersion’ key, this error is thrown by the server:
An unknown server-side error occurred while processing the command. Original error: The provided platform version value 'null' cannot be coerced to a valid version number

How can I overcome this issue and be able to connect appium with android devices running Android 11 R ?

https://discuss.appium.io/t/appium-server-cannot-connect-to-android-r-11-device-because-of-the-platformversion/29767

## Link to Appium logs

https://gist.github.com/jlshipman/3fd2857b61637d9617676a79121034ef

**Comment by mykola-mokhnach** [comment] 2020-04-07 16:40
Duplicate of https://github.com/appium/appium/issues/13983

**Closed by mykola-mokhnach** 2020-04-07 16:40 UTC
