### ISSUE TITLE
Getting Error:Device emulator-5554 was not in the list of connected devices on Fire TV

### ISSUE THREAD

**Issue by Jitu1888** [appium/appium#6468] opened 2016-05-04 12:11 UTC
## The problem

I am trying to automate Fire Tv , but getting an error Device emulator-5554 was not in the list of connected devices.

## Environment

* Appium version :1.4.16
* Desktop win 7 used to run Appium:
* Mobile platform: Fire OS 5.0.5.1
* Real device 

## Link to Appium logs
erver. : version, platform, androidPackage, webviewSupport, device
> info: [debug] Using local app from desired caps: C:\Users\jitu.patel\Desktop\Phone_DishAnywhere_4.7.24_signed.apk
> info: [debug] Creating new appium session 27740b6e-32df-42a7-988c-cd4d37ca34b7
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_77
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from D:\Automation\sdk\platform-tools\adb.exe
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: D:\Automation\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> warn: UiAutomator did not shut down fast enough, calling it gone
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> error: Failed to start an Appium session, err was: Error: Device emulator-5554 was not in the list of connected devices
> info: [debug] Error: Device emulator-5554 was not in the list of connected devices
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android-common.js:405:19)
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:621:9)
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:853:7)
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:180:9)
>     at ChildProcess.exithandler (child_process.js:742:7)
>     at ChildProcess.emit (events.js:110:17)

**Comment by Jitu1888** [comment] 2016-05-04 12:12
Need a urgent help

**Comment by imurchie** [comment] 2016-05-04 14:49
Duplicate of #6467

**Closed by imurchie** 2016-05-04 14:49 UTC
Labels: NeedsTriage
