### ISSUE TITLE
Wire new platform support from node-simctl into drivers

### ISSUE THREAD

**Issue by imurchie** [appium/appium#12009] opened 2019-01-15 15:05 UTC
## The problem

`node-simctl` now supports platforms other than `"iOS"`. This needs to be brought up into the driver layer so that we can support them.

Cc: @simongranger

**Comment by mykola-mokhnach** [comment] 2019-04-27 11:42
I assume the problem is fixed now since xcuitest driver supports tvos as well as ios

**Closed by mykola-mokhnach** 2019-04-27 11:42 UTC
Labels: Enhancement, iOS
