### ISSUE TITLE
autoAcceptAlerts/autoDismissAlerts broken

### ISSUE THREAD

**Issue by SConrad-Whoop** [appium/appium#5000] opened 2015-04-24 16:53 UTC
I've got autoAcceptAlerts and autoDismissAlerts set to true in my environment variables but the notifications popup that appears at app start does not get accepted or dismissed. 

I've tried each by themselves as well as both at the same time, neither appears to be working. 

Unsure where to go from here. Happy to provide more information, just let me know what you need.

**Comment by jlipps** [comment] 2015-05-01 17:35
closing as a duplicate of https://github.com/appium/appium/issues/4178

**Closed by jlipps** 2015-05-01 17:35 UTC
Labels: NeedsTriage
