### ISSUE TITLE
"code":"ECONNRESET" when GET http://localhost:8200/wd/hub/status

### ISSUE THREAD

**Issue by Erez-VoiceSense** [appium/appium#12866] opened 2019-07-07 08:36 UTC
## The problem
while running appium test i am getting en error in appium server ECONRESET when trying to GET http://localhost:8200/wd/hub/status

## Environment

* Appium version 1.13
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: win 10
* Node.js version (unless using Appium.app|exe):10.16.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: android studio 3.4.1
* Real device or emulator/simulator: emulator

## Link to Appium && ADB logs
https://gist.github.com/Erez-VoiceSense/468b45cc0ad7c36cb0075c2e3b87a3e5

## Code To Reproduce Issue [ Good To Have ]

package Tests;
 
import java.net.MalformedURLException;
import java.net.URL;
 
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
 
public class AppiumTest {
	
	public static void main(String[] args) {
		
		//Set the Desired Capabilities
		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
		caps.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10");
		caps.setCapability(MobileCapabilityType.DEVICE_NAME,"Galaxy Nexus API 29");
"com.google.android.finsky.activities.MainActivity");
		caps.setCapability("automationName", "UiAutomator2");
		caps.setCapability(MobileCapabilityType.APP,"C:/Users/erez/Downloads/Voicesense-113-(1.1.3).apk");
		
		//Instantiate Appium Driver
		try {
				@SuppressWarnings("unused")
				AppiumDriver<MobileElement> driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), caps);
			
		} catch (MalformedURLException e) {
			System.out.println(e.getMessage());
		}
	}
 
}

**Comment by mykola-mokhnach** [comment] 2019-07-07 10:29
Duplicate of https://github.com/appium/appium/issues/12754

**Closed by mykola-mokhnach** 2019-07-07 10:29 UTC

**Comment by Erez-VoiceSense** [comment] 2019-07-07 11:41
then how can i write automation to android ? can i user anything else?

**Comment by KazuCocoa** [comment] 2019-07-07 11:56
1. Use non-Q android emulators ( because of https://github.com/appium/appium/issues/12754#issuecomment-501422323 )
2. Use real devices

**Comment by Erez-VoiceSense** [comment] 2019-07-07 12:10
can you direct me to one? thx in advance
