### ISSUE TITLE
Support multiple localizable.strings files

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#3869] opened 2014-10-21 21:47 UTC
I thought we already had an issue for this. I couldn't find it so I've opened a new one. As mentioned on [appium discuss](https://discuss.appium.io/t/how-to-locate-elements-using-multiple-strings-files/957/2) it's common to have multiple localizable.strings files on iOS. Currently appium only looks at one.

**Comment by jlipps** [comment] 2017-07-18 22:33
duplicate of #2391

**Closed by jlipps** 2017-07-18 22:33 UTC
Labels: Enhancement, iOS
