### ISSUE TITLE
bug: Some nested elements are not showing in the App Source tree.

### ISSUE THREAD

**Issue by mountither** [appium/appium#19156] opened 2023-09-15 00:48 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Child list items are not showing in App Source tree. 

### Expected Behavior

List items should show on the Appium's app source tree and be able to tap on a specific list item.

### Minimal Reproducible Example

The following screenshots indicate the child elements are not rendering in the app source tree.
![Screen Shot 2023-09-15 at 9 26 12 am](https://github.com/appium/appium/assets/53046782/44c96433-ccf4-48b0-ae97-8da43e6ac905)

### Environment

- Operating system: MacOS
- Appium server version (output of `appium --version`): 2.1.3
- Node.js version (output of `node --version`): v16.17.0
- `npm` version (output of `npm --version`):  8.15.0
- Platform and version under test: iOS v16.1
- Real device or emulator/simulator: simulator using BrowserStack as a cloud provider.

**Comment by KazuCocoa** [comment] 2023-09-15 01:29
Perhaps `snapshotMaxDepth` could help if these nested ones exited deep place.
https://appium.github.io/appium-xcuitest-driver/5.1/settings/

If they were also not available with `description` format by https://appium.github.io/appium-xcuitest-driver/5.1/execute-methods/#mobile-source , maybe XCTest is not able to detect them. (Appium rely on XCTest)

**Comment by mykola-mokhnach** [comment] 2023-09-16 14:50
Possible duplicate of https://github.com/appium/appium/issues/14825

**Comment by mykola-mokhnach** [comment] 2023-09-18 13:36
Closed because of no response

**Closed by mykola-mokhnach** 2023-09-18 13:36 UTC
Labels: Needs Info
