### ISSUE TITLE
Encountered internal error running command: Error: The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability. 

### ISSUE THREAD

**Issue by userraj** [appium/appium#14043] opened 2020-03-08 18:31 UTC
Facing this issue on execution ---  

Encountered internal error running command: Error: The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability. 

On start execution facing this issue

**## Environment**

capabilities.setCapability("platformName", "Android");
	capabilities.setCapability("fullReset", true);
	capabilities.setCapability("newCommandTimeout", 10800);
	capabilities.setCapability("platformVersion", 10);
	capabilities.setCapability("deviceName", "emulator-5554");
	capabilities.setCapability("app", file.getAbsolutePath());
	capabilities.setCapability("appPackage", "com.***.****");
	capabilities.setCapability("appActivity", ".MainActivity");
	capabilities.setCapability("systemPort", "7100");
	capabilities.setCapability("automationName", "uiautomator2");  

**## Details**

Tried with uiautomator2, Uiautomator2, Uiautomator 2, and uiautomator1 cases

**## Link to Appium logs**

[BaseDriver] Event 'newSessionStarted' logged at 1583691622423 (23:50:22 GMT+0530 (IST))
[W3C] Encountered internal error running command: Error: The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability. 
[W3C]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:79:13)
[W3C]     at UiAutomator2Server.errorAndThrow [as startSession] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/uiautomator2.js:216:15)
[HTTP] <-- POST /wd/hub/session 500 41615 ms - 1132

## Code To Reproduce Issue [ Good To Have ]

File file = new File("/Users/fmaily/Downloads/app-production-release.apk");
	//Set up desired capabilities and pass the Android app-activity and app-package to Appium
	DesiredCapabilities capabilities = new DesiredCapabilities();	
	capabilities = new DesiredCapabilities();
	//capabilities.setCapability("avd", "Pixel 2 API 29");
	capabilities.setCapability("platformName", "Android");
	capabilities.setCapability("fullReset", true);
		//capabilities.setCapability("noSign",true); 
	capabilities.setCapability("newCommandTimeout", 10800);
	capabilities.setCapability("platformVersion", 10);
	capabilities.setCapability("deviceName", "emulator-5554");
	capabilities.setCapability("app", file.getAbsolutePath());
	capabilities.setCapability("appPackage", "com.***.***");
	capabilities.setCapability("appActivity", ".MainActivity");
	capabilities.setCapability("systemPort", "7100");
	capabilities.setCapability("automationName", "uiautomator2");    
   driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

Please help me out soon it will be very helpful. thanks in advance

<img width="944" alt="Screenshot 2020-03-08 at 11 58 18 PM" src="https://user-images.githubusercontent.com/34085411/76168772-b6eb0400-6198-11ea-9c7f-a47bac4e0234.png">

**Comment by mykola-mokhnach** [comment] 2020-03-08 19:30
Please provide the full server log and the logcat log

**Comment by Aathimanirajb** [comment] 2020-03-10 11:51
[test.txt](https://github.com/appium/appium/files/4312245/test.txt) - full server log

Facing this issue only on virtual devices & in real device working as expected. Please help me.

**Comment by mykola-mokhnach** [comment] 2020-03-10 12:28
Please provide the logcat output as well

**Comment by userraj** [comment] 2020-03-10 14:07
Attaching logcat output
[logcat.txt](https://github.com/appium/appium/files/4312844/logcat.txt)

**Comment by mykola-mokhnach** [comment] 2020-03-10 14:17
> 03-10 19:34:08.826  7517  8015 I appium  : Started UiAutomator2 io.appium.uiautomator2.http io.appium.uiautomator2.server on port 6790

The log says that the server has been started successfully, however the client still cannot connect to it. Might be a duplicate of https://github.com/appium/appium/issues/13509

**Comment by mykola-mokhnach** [comment] 2020-03-13 07:16
Closed because of no reponse

**Closed by mykola-mokhnach** 2020-03-13 07:16 UTC
Labels: NeedsInfo, UIAutomator2

**Comment by antonydass** [comment] 2020-04-10 06:36
Hi,

am facing same kind of issue. kindly help on this

**Comment by bryanboyko** [comment] 2020-09-14 23:06
Also running into the same issue. Would love some assistance

**Comment by HariharanGa** [comment] 2021-04-23 13:55
Hi im still facing this issue when i use a remote machine to connect to my devices

org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'rajakumarganji1.hyd.corp.google.com', ip: '100.103.248.236', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.24-1rodete2-amd64', java.version: '11.0.11-ea'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'rajakumarganji1.hyd.corp.google.com', ip: '100.103.248.236', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.24-1rodete2-amd64', java.version: '11.0.11-ea'
Driver info: driver.version: AndroidDriver

Upgarded the Appium to 1.20
installed npm list -g appium-uiautomator2-driver

Please help to resolve this issue.

**Comment by aditya-inevitableinfotech** [comment] 2022-03-23 09:09
[RemoteTestNG] detected TestNG version 7.4.0
Cause is : java.lang.reflect.InvocationTargetException
Message is : Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/home/invlko-026/Android/Sdk/platform-tools/adb -P 5037 -s SB52210900125 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 1'; Command output: adb: device 'SB52210900125' not found

Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'aditya', ip: '172.17.0.1', [os.name](http://os.name/): 'Linux', os.arch: 'amd64', os.version: '5.13.0-37-generic', java.version: '1.8.0_312'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/home/invlko-026/Android/Sdk/platform-tools/adb -P 5037 -s SB52210900125 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 1'; Command output: adb: device 'SB52210900125' not found
at getResponseForW3CError (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
at asyncHandler (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)
