### ISSUE TITLE
(React-Native) Unable to find WebView on iOS 14.0.1

### ISSUE THREAD

**Issue by thetin95** [appium/appium#14788] opened 2020-10-06 09:09 UTC
## The problem

(React-Native) Unable to find WebView on iOS 14.0.1

## Environment

* Appium version (or git revision) that exhibits the issue: V1.18.0
* Desktop OS/version used to run Appium: macOs Catalina Version 10.15.6
* Node.js version (unless using Appium.app|exe): v12.18.4
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 14.0.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium Desktop

## Details

Automated test tool is Robot Framework

## Link to Appium logs

https://gist.github.com/thetin95/c1020aa63e5d32746c631cf0032ca596

Anyone has any suggestion?
Thanks in advance!

**Comment by mykola-mokhnach** [comment] 2020-10-06 09:43
Possible duplicate of https://github.com/appium/appium/issues/14760

**Comment by mykola-mokhnach** [comment] 2020-10-06 09:43
Possible duplicate of https://github.com/appium/appium/issues/14760

**Comment by thetin95** [comment] 2020-10-06 10:28
@mykola-mokhnach My app is developed with react native.
thanks for your advice.

**Comment by mykola-mokhnach** [comment] 2020-10-06 10:32
Simply try if the solutions from the issue above work for you

**Comment by thetin95** [comment] 2020-10-06 10:49
It doesn't work for me.

**Comment by mykola-mokhnach** [comment] 2020-10-06 11:07
Please describe in details what did you try and what did not work

**Comment by thetin95** [comment] 2020-10-07 03:52
@mykola-mokhnach https://github.com/google/ios-webkit-debug-proxy

**Comment by mykola-mokhnach** [comment] 2020-10-07 05:08
![Fry](https://imgflip.com/s/meme/Futurama-Fry.jpg)

**Comment by mykola-mokhnach** [comment] 2020-10-09 12:39
Closed because of no response

**Closed by mykola-mokhnach** 2020-10-09 12:39 UTC
Labels: Mobile Safari, NeedsInfo
