### ISSUE TITLE
element.getAttribute("value")) returns null though the value is set

### ISSUE THREAD

**Issue by fdPoornima** [appium/appium#13508] opened 2019-10-29 15:17 UTC
## The problem

I am automating a native ios application. After an item selection, a particular tab item gets enabled and a value of "1 item" is assigned to the element. This is visible in the appium inspector as well snapshot attached
![Screenshot 2019-10-29 at 15 09 47](https://user-images.githubusercontent.com/30728492/67781889-f1f96000-fa5f-11e9-8b1a-d7d0fb55e1cc.png)
. However when element.getAttribute("value") is run in the script, it returns null.

## Environment
Appium version (or git revision) that exhibits the issue: 1.16.0-beta.1
Last Appium version that did not exhibit the issue (if applicable): NA
Desktop OS/version used to run Appium: MAC OS mojave 10.14.3
Node.js version (unless using Appium.app|exe): v8.11.2
Npm or Yarn package manager: v8.11.2
Mobile platform/version under test: ios version 12.1.2
Real device or emulator/simulator: Simulator
Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
INFO: Checking for visibility... of elementBy.AccessibilityId: Testiteration -0
The propertynull

## Code To Reproduce Issue [ Good To Have ]

WebElement element = driver.findElement(MobileBy.AccessibilityId(test));
System.out.println("The property"+element.getAttribute("value"));

**Comment by mykola-mokhnach** [comment] 2019-10-29 15:26
Duplicate of https://github.com/appium/appium/issues/13477

**Closed by mykola-mokhnach** 2019-10-29 15:26 UTC
