### ISSUE TITLE
XCUITest DerivedData folder filled (1.6.x)

### ISSUE THREAD

**Issue by skyline-gleb** [appium/appium#7242] opened 2016-11-16 09:28 UTC
Use Appium 1.6, XCode 8.1 and ios10 simulators i find problem with very big folder `Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments/` (It contains many screenshots), which was not on ios9 and Appium 1.5.3.

How disable getting screenshots?

**Comment by mykola-mokhnach** [comment] 2016-11-16 09:43
@imurchie yep, I can confirm that. I suppose it would be enough to add one more default parameter to xcodebuild  , which prepares WDA, like it is described [here](http://stackoverflow.com/questions/35697867/how-to-turn-off-automatic-screenshots-on-ui-testing-xcode/35853146):

```
 -derivedDataPath '/dev/null'
```

This will also allow us to save a lot of space and, probably, will speed up tests execution.

**Comment by mykola-mokhnach** [comment] 2016-11-16 09:48
BTW this article contains more information about the general structure of the data generated by Xcode

**Comment by skyline-gleb** [comment] 2016-11-16 09:53
Am I correct in assuming that i not can set this parameter from tests or appium run?

**Comment by mykola-mokhnach** [comment] 2016-11-16 09:55
you can manually edit Appium source and add it there unless a fix is merged to a new version. But yeah, there is no API to do it.

**Comment by skyline-gleb** [comment] 2016-11-16 10:17
I got it, thanks.

**Comment by imurchie** [comment] 2016-11-16 12:44
You can have those files deleted in 1.6.1 by setting the `clearSystemFiles` desired capability to `true`.

**Comment by imurchie** [comment] 2016-11-16 12:56
Using `-derivedDataPath '/dev/null'` does not work, since the build process tries to access things in the derived data path, so it fails.

**Comment by amedvedjev** [comment] 2016-11-16 13:17
met same issue. log size just eat ALL disk space with reaching 970Gb size. "rm -rf" for this folder took 1.5 day :-). now i added workaround execute before each run:
 rm -fR /Users/YOUR_USER_NAME/Library/Developer/Xcode/DerivedData/* || true

**Comment by skyline-gleb** [comment] 2016-11-16 14:05
@imurchie but this setting not save me from read/write operations on system disk, right?

**Comment by imurchie** [comment] 2016-11-16 14:12
No. Apple forces that upon you.

**Comment by skyline-gleb** [comment] 2016-11-16 14:16
Thanks Apple for this.
@imurchie thank you for answer.

**Comment by mykola-mokhnach** [comment] 2016-11-16 20:25
@imurchie It looks like it is possible to do something there. At least I know where to start digging:
https://github.com/facebook/FBSimulatorControl/blob/cd76578c685fccbc7d9077e91ec1404d3d701b6b/XCTestBootstrap/Bundles/FBApplicationDataPackage.m
https://github.com/facebook/FBSimulatorControl/blob/cd76578c685fccbc7d9077e91ec1404d3d701b6b/XCTestBootstrap/Bundles/FBTestConfiguration.m

They create special configuration file (plist format) inside xctest bundle with 'bundle_name'.xctest.xctestconfiguration file name and write some special parameters there. I suppose this file is supposed to be picked up by XCTest runner after the test actually starts.

**Comment by imurchie** [comment] 2016-11-17 14:11
Interesting. Is there any way to change that at startup time?

**Comment by mykola-mokhnach** [comment] 2016-11-17 14:33
@imurchie I think yes. I've also found _testEnvironmentWithSpecifiedTestConfiguration_ method in 

https://github.com/facebook/xctool/blob/c5d98ef3fee4467e163498fdeb59ac1cf38ec2b3/xctool/xctool/OCUnitTestRunner.m

which might give some hints for us. 

How I imagine the process for myself:

1. We need to build the source for test.
2. We need to prepare new/replace existing xctestconfiguration file and put it together with prebuilt tests. File structure itself is based on XCTestConfiguration class
3. XCTest framework will pick up and apply our custom settings from xctestconfiguration file after the test has been executed.

I've also posted a question to Apple Dev forum, but I don't expect to get any response soon, since the stuff is totally undocumented there. I wonder how Facebook guys got so much information about this stuff %)

**Comment by mykola-mokhnach** [comment] 2016-11-17 16:23
@imurchie OK, I did it stupid way, but it works :)

I just executed a test to let WDA to create the stuff inside DerivedData folder. It's usually a folder with starts with _WebDriverAgent-_ prefix plus some random suffix. Then I used fswatch to monitor when XCTest creates

```
Logs/Test/Attachments
```

subfolder there. Then I just executed

```bash
chmod -w  $root/Logs/Test/Attachments
```

And this did the trick and didn't crash xcodebuild. Changing permissions for parent Test folder crashes xcodebuild though %)

My second idea was to temporarily mount some kind of virtual blackhole file system instead of Test folder, but this would be too complicated.

**Comment by imurchie** [comment] 2016-11-17 16:31
That is weird! Do you feel like making a PR with this? Even if it's hacky, if it works it would be good to have it (maybe behind a desired capability so it can be turned off if people want access to all that info).

**Comment by mykola-mokhnach** [comment] 2016-11-17 16:34
I want to test the implementation locally first. Also, we may use the existing capability for this purpose, which was introduced in 1.6.1: _clearSystemFiles_

**Comment by imurchie** [comment] 2016-11-17 16:35
That was meant to clear after the fact, and means that in Android. Suppressing the generation is a different thing.

Yes! Test locally. :)

**Comment by imurchie** [comment] 2017-01-31 20:18
`preventWDAAttachments` cap will fix this now.

**Closed by imurchie** 2017-01-31 20:18 UTC
Labels: NeedsTriage
