### ISSUE TITLE
Multiple context switching is causing appium to hang

### ISSUE THREAD

**Issue by shivakr** [appium/appium#8290] opened 2017-04-20 09:27 UTC
## The problem

We have an Hybrid app for testing and it needs lot of context switching and following the context switch scenarios and the results:

NATIVE_APP -> WEBVIEW -> NATIVE_APP  - Works with out any issue
NATIVE_APP -> WEBVIEW -> NATIVE_APP  ->WEBVIEW - now when we change from NAVITE_APP to WEBVIEW second time, I have see 2 instances of WEBVIEW and appium dont switch to any of those even after asking appium to choose any available WEBVIEW.

Please let me know if I am doing anything wrong or is it an issue with APPIUM.

Appium version I am using through node is 1.6.3 with patched chromedriver

## Environment

* Desktop OS/version used to run Appium: Mac OS sierra
* Node.js version (unless using Appium.app|exe): 7.8.0
* Mobile platform/version under test: Android 6.0 API 23
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment] 2017-04-20 10:22
Please attach Appium log

**Comment by dpgraham** [comment] 2017-07-20 22:49
Closing as duplicate of https://github.com/appium/appium/issues/8257

**Closed by dpgraham** 2017-07-20 22:49 UTC
Labels: Android, LogRequested
