### ISSUE TITLE
Android emulator does not quit automatically

### ISSUE THREAD

**Issue by SteffenL** [appium/appium#7552] opened 2016-12-16 00:34 UTC
## The problem

When running Selenium tests on an Android virtual device, the device does not power off after the test ends, and the emulator does not quit.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.12.2
* Node.js version (unless using Appium.app|exe): 7.1.0
* Mobile platform/version under test: Android 5.1.1, 6.0, 7.1.1
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I have a basic Python script that runs a simple test with Selenium and Appium in a web browser.

The test runs all right but afterwards, the emulator itself never quits. I expected that it would behave like the iOS simulator.

Since the emulator does not quit automatically, I can also not conveniently run tests on another virtual device on the same host machine (attempting to do so can lead Appium to crash).

## Link to Appium logs

https://gist.github.com/SteffenL/2f01cad53d43bf5ec34a54e00c386aaf

## Code To Reproduce Issue [ Good To Have ]

Sample code:  sample-code/examples/python/android_simple.py

A simpler example:
```
from selenium import webdriver

cap = {"browserName": "Browser", "platformName": "Android", "deviceName": "Android Emulator", "platformVersion": "5.1.1", "automationName": "Appium", "avd": "Nexus_5_5.1.1"}
driver = webdriver.Remote("http://localhost:4723/wd/hub", cap)
driver.get("http://www.seleniumhq.org/")
driver.quit()
```

**Comment by jlipps** [comment] 2016-12-16 01:12
> Since the emulator does not quit automatically, I can also not conveniently run tests on another virtual device on the same host machine (attempting to do so can lead Appium to crash).

what is the crash you are getting?

I think it's by design we don't kill the emulator after each session, since you should be able to reuse them without problem.

**Comment by SteffenL** [comment] 2016-12-16 01:27
Logs from the point where I start tests with a different virtual device:
https://gist.github.com/SteffenL/d2a9a4055efc0fd1a323c46a5a6f0739

At this point, the screen of the new device is black and never boots up.
If I try to quit one of the emulators before reaching the error in the log above, Appium crashes:
```
Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:572:26)
```
I guess I did something out of the ordinary to make the crash happen though.

**Comment by SteffenL** [comment] 2016-12-20 22:44
I just learned that the emulator blocks system restarts on macOS:

![qemu-failed-to-quit](https://cloud.githubusercontent.com/assets/1543854/21370716/6aeec06a-c70d-11e6-9587-f90ecc69114d.png)

If Appium can quit the emulator after tests end, I think this will be one less problem to worry about.

**Comment by jlipps** [comment] 2016-12-21 21:32
I'm open to adding a capability that will kill the emu in between tests if Appium started it. Adding as an enhancement

**Comment by SteffenL** [comment] 2016-12-22 11:29
Thank you! Since it is currently impossible for me to first run tests on one virtual device and then run tests on a different virtual device, this would help a lot!

Are we actually supposed to be able to test on different devices (sequentally at least)? I think that the only way that can work (for me) is to run Appium on multiple computers (virtual or physical) where each has only one virtual device.

**Comment by SteffenL** [comment] 2016-12-22 13:31
I tried two things so far:

- Run two separate Appium server instances on the same machine, managing one virtual device each.
- Run a single Appium server instance, managing multiple virtual devices.

The result is the same in both cases; the second emulator instance shows a black screen and never boots up. The log indicates that Appium is trying to communicate with both emulator instances.

**Comment by SteffenL** [comment] 2016-12-24 11:40
I came across the Android-only command line parameter `--reboot`. It seems to do more or less what I wanted. Maybe we can close this issue? 👍 

When using this parameter, I can now run tests on more than one Android device/platform on the same host machine. The only unexpected behavior now is that this seems to cause the client to throw an exception:

```
...
[debug] [ADB] Running '/usr/local/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","emu","kill"]
[Logcat] Logcat terminated with code 0, signal null
[debug] [ADB] Running '/usr/local/opt/android-sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.unlock"]
[ADB] successfully killed emulator 'Nexus_5_7.1.1'
[Appium] Had trouble ending session cd3cee9b-30a1-48d6-bb55-0f59c9fb59df: Error executing adbExec. Original error: 'Command '/usr/local/opt/android-sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock' exited with code 1'; Stderr: 'error: device 'emulator-5554' not found'; Code: '1'
[Appium] Removing session cd3cee9b-30a1-48d6-bb55-0f59c9fb59df from our master session list
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/usr/local/opt/android-sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock' exited with code 1'; Stderr: 'error: device 'emulator-5554' not found'; Code: '1'
    at ADB.execFunc$ (../../../lib/tools/system-calls.js:195:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- DELETE /wd/hub/session/cd3cee9b-30a1-48d6-bb55-0f59c9fb59df 500 886 ms - 412 
```

**Comment by dmlemeshko** [comment] 2016-12-26 21:42
@SteffenL are you stopping Appium server before you are calling `adb reboot`?
From the stack race it looks like Appium server is being stopped after emulator was already off and it causes error.

**Comment by SteffenL** [comment] 2017-01-02 11:41
@dmlemeshko Sorry for the late reply. I did not call `adb reboot` or stop the emulator myself by any other means.

Full log since requesting a session:
https://gist.github.com/SteffenL/17709c1a454b99d5510c7336ea0f28be

This happens while using the `--reboot` parameter. For some reason, this does not seem to happen in some cases. When my test is running as part of a Jenkins build, I get this error; when running it manually outside of Jenkins, I do not get the error. When I do not use `--reboot`, then it works fine when part of my Jenkins build as well as manually.

This is my Appium configuration:
```
{
  "capabilities": [
    {
      "browserName": "safari",
      "platformName": "MAC",
      "maxInstances": 1,
      "applicationName": "ios-device"
    },
    {
      "browserName": "chrome",
      "platformName": "ANDROID",
      "maxInstances": 1,
      "applicationName": "android-7.1-device"
    },
    {
      "browserName": "browser",
      "platformName": "ANDROID",
      "maxInstances": 1,
      "applicationName": "android-5.1-device"
    }
  ],
  "configuration": {
    "cleanUpCycle": 2000,
    "timeout": 30000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "url": "http://localhost:4723/wd/hub",
    "host": "localhost",
    "port": 4723,
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4445,
    "hubHost": "localhost"
  }
}
```

Default capabilities:
```
{
    "avdArgs": "-dns-server 127.0.0.1"
}
```

Command to start Appium:
```
appium --nodeconfig nodeconfig.json --default-capabilities default-capabilities.json
```

**Comment by BrianJWatson** [comment] 2017-02-27 00:18
I too am running into this issue and would find it most helpful to support a way of stopping the Android Emulator from an Appium session.  Either a specific command you could send through Appium to shut down or restart the Emu.  Or even better, if you could build the Emulator restart into the 'fullReset' capability for Android.  That way, it would behave just like the iOS one where it closes and restarts the simulator, as well as reloading the app/apk file.  :)

**Comment by artgo** [comment] 2017-05-07 21:07
+1 how can we influence to increase the priority of this ticket? :)

**Comment by jlipps** [comment] 2017-07-24 17:54
I will bump the priority of this feature request. I think baking it into `fullReset` is a good idea. But it should go hand-in-hand with Appium starting the emulator. I.e., if you have requested for Appium to manage your emu lifecycle, then this functionality will be present. If you _haven't_ (i.e., if you are not using the `avdName` capability), then Appium won't close it for you.

**Comment by fdPoornima** [comment] 2018-07-25 08:14
Hello, has this feature been added yet? Desperately looking for a solution as my emulator runs into memmory issues after being open for so long and the next run a couple of hours later usually fails. Is there any workaround I can do temporarily to restart the emulator/ preventing it from crashing

**Comment by Brian-Watson** [comment] 2018-07-25 17:49
I ended up just adding a post-build step command-line to my Jenkins job that kicks off the Android automation at scheduled times throughout the day...

adb emu kill

This seems to have cleared up a lot of my previous issues of the emulator getting "flakey".

**Comment by fdPoornima** [comment] 2018-07-26 08:13
Thanks @Brian-Watson , will try that out

**Comment by YuriiTsap** [comment] 2019-08-30 09:36
Hi, not sure if that is relevant still. Nevertheless I'll share my experience with this issue. I'm not running automation(selenium, apium etc.) - I'm facing this issue just when I want to shut down my emulator, as result it just ends up in a frozen state. Looks like something is leaked on a system level and can't be released. Force quit isn't helpful at all. My solution is just to kill emulator if it isn't responding, that is probably hard to define on Jenkins or any other build machine.
Anyway in such state you won't be able to obtain feedback from your emulator while sending adb commands or key events or something else, so after some kind of `connection timeout` you need to kill it. That are just thoughts in terms how that could be spotted while playing with automation.

I'm killing emulator instance through system terminal:

- call `top` command - it will show all processes running right now, example:
<img width="684" alt="Screen Shot 2019-08-30 at 12 24 14 PM" src="https://user-images.githubusercontent.com/6748328/64010050-ad198180-cb21-11e9-9109-9fcd63061453.png">

- call `kill -9 4023`. 
`-9` is the signal(basically saying it has higher priority to kill), which you are sending to defined process, which has `PPID 4023`

That's all we can start another instance of emulator. Docs on [kill](https://ss64.com/osx/kill.html) and [top](https://ss64.com/osx/top.html) commands provided.

**Comment by mykola-mokhnach** [comment] 2020-04-20 14:30
In appium@beta UIA2 driver got a [feature](https://github.com/appium/appium-android-driver/pull/630), which allows to directly the emulator using its console commands.

**Closed by mykola-mokhnach** 2020-04-20 14:30 UTC
Labels: Android, Enhancement, P1

**Comment by tavramov** [comment] 2020-10-23 00:07
> In appium@beta UIA2 driver got a [feature](https://github.com/appium/appium-android-driver/pull/630), which allows to directly control the emulator using its console commands.

I think this UIA2 feature works to close the emulator but i think there is a little bit of a chicken-and-egg problem. The issue is that if you call driver.executeScript("mobile: execEmuConsoleCommand", "kill", "device_udid") before driver.quit(), driver.quit() will fail because emulator is gone. And you cant execute the kill command after driver.quit() because session will be null. IMO, closing the emulator needs to be made part of the driver.quit() call routine. Agree with @jlipps previous suggestion that maybe the kill command in driver.quit() can be conditional on the avd capability. 
Does this sound reasonable?
