### ISSUE TITLE
Impossible to upload files in safari, iOS

### ISSUE THREAD

**Issue by Nikikuzi** [appium/appium#13722] opened 2019-12-15 09:50 UTC
## The problem

Impossible to upload files to form like this - http://the-internet.herokuapp.com/upload

element.send_keys("path_to_file") returns {ElementNotVisibleException}Message: The object is in an invalid state.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1, 1.16.0-rc.1
* Desktop OS/version used to run Appium: MacOS
* Mobile platform/version under test: iOS 12.4, 13.2
* Real device or emulator/simulator: Simulator

**Comment by mykola-mokhnach** [comment] 2019-12-15 11:52
Unfortunately such functionality is not supported. Duplicate of https://github.com/appium/appium/issues/13156

**Closed by mykola-mokhnach** 2019-12-15 11:52 UTC

**Comment by lorenpan** [comment] 2021-07-12 09:15
Is there any updated for this problem? If the latest version of appium could support upload files with safari on ios?

**Comment by jlipps** [comment] 2021-07-12 18:09
As the issue says, the functionality is not supported and there is no plan to support it. The way to automate file upload is to perform the same steps that a user would. There is no "upload" API.

**Comment by valsky4** [comment] 2024-05-30 09:00
This is not cool, as it is one of the most frequently used commands with browsers. Imagine how much more user-friendly it would be if you could do this with Appium instead of going through the entire process of context switching, all the clicking for a single upload... @jlipps any plans to do it in future or it's still nope.

**Comment by jlipps** [comment] 2024-05-31 18:04
I can't think of any way it'd even be technically possible to implement this, especially for mobile.
