### ISSUE TITLE
iOS: Appium creates lots of temp files in "/private/var/folders/"

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#14550] opened 2020-07-14 12:45 UTC
## The problem

While executing tests with reals iPhones was mentioned dramatically space consuming in "/private/var/folders/".
e.g. just start of "appium -v" = create empty folder like "/private/var/folders/q3/02m9wscj2rg93_l37d7wsd3r0000gq/T"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0-beta.0
* Desktop OS/version used to run Appium: MacOS 10.15.5
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real device

## Details

while tests executing we see there 2 files creating:
 - "appium-temp.xcconfig"
 - "xxx.app" where 'xxx' is app under test name
in many subfolders of "/private/var/folders/q3/".

Thus space easy eating (e.g. with our case was eaten 70Gb).

mac restart helps to remove these temp files.

It looks like "xxx.app" creates during app install (but not sure)

**Comment by mykola-mokhnach** [comment] 2020-07-14 14:26
Unfortunately the given information is not enough to make any assumptions. Could be a duplicate of https://github.com/appium/appium/issues/14366

**Comment by amedvedjev** [comment] 2020-07-14 18:30
@mykola-mokhnach thanks! Just exactly same issue. Will try to remove kill server by port while we use override session on start. Will add commnent later ...

**Comment by amedvedjev** [comment] 2020-07-16 06:24
increasing 10-15Gb for us each day...

**Comment by KazuCocoa** [comment] 2020-07-17 08:16
`--tmp` may help to customise Appium's tmp directory. This option may help to observe Appium or other tools such as xcodebuild use the space. You also can remove the tmp directory every finalising the appium process
http://appium.io/docs/en/writing-running-appium/server-args/

**Comment by mykola-mokhnach** [comment] 2020-07-19 17:56
Closed as not issue. 

Consider reviewing the server startup/shutdown logic or switch to custom temporary folder management as @KazuCocoa has advised above

**Closed by mykola-mokhnach** 2020-07-19 17:56 UTC
Labels: NeedsInfo, NotABug
