### ISSUE TITLE
iOS | Appium miss 'value' attribute

### ISSUE THREAD

**Issue by DenisTravinConst** [appium/appium#13688] opened 2019-12-05 16:16 UTC
## The problem

Appium miss 'value' attribute in 1.15.* versions. It return 'label' attribute value as text and return 'null' as 'value' attribute value.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.*(1.15.1, 1.15.0), 1.16.0-beta.3
* Last Appium version that did not exhibit the issue (if applicable): 1.12.0 was OK
* Desktop OS/version used to run Appium: 1.15.1
* Node.js version (unless using Appium.app|exe): 13.2.0
* Npm or Yarn package manager: npm 6.13.1
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: iPhone 7+ simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details
Element data:
value = "Search value"
label = "Search..."

Element data from getPageSource() method:
```
<XCUIElementTypeSearchField type="XCUIElementTypeSearchField" enabled="true" visible="true" x="20" y="22" width="314" height="40" name="searchBar.searchController.textField" label="Search..." value="Search value">
```

element.getText() return: "Search..."
element.getAttribute("label") return: "Search..."
element.getAttribute("value") return: null

Logs for getText(), getAttribute('label') and getAttribute('value') requests.
https://gist.github.com/DenisTravinConst/c604a67e4be65daee684643cbb0623a2

**Comment by mykola-mokhnach** [comment] 2019-12-05 18:52
Duplicate of https://github.com/appium/appium/issues/13288

**Closed by mykola-mokhnach** 2019-12-05 18:52 UTC
