### ISSUE TITLE
Unable to install appium-windows-driver version 2.7.0

### ISSUE THREAD

**Issue by StuartFerguson** [appium/appium#18257] opened 2023-02-27 10:17 UTC
I am currently using  Appium v2.0.0-beta.56 for testing my Android Apps and wanted to start testing with Windows applications as well.

When I try to install appium-window-driver with the command:

**appium driver install --source=npm appium-windows-driver**

I get the error below:
```
PS C:\WINDOWS\system32> appium driver install --source=npm appium-windows-driver
× Installing 'appium-windows-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev appium-windows-driver --json' failed with code 1.

STDOUT:
{
  "error": {
    "code": "ERESOLVE",
    "summary": "unable to resolve dependency tree",
    "detail": "\nWhile resolving: undefined@undefined\nFound: appium@1.22.3\nnode_modules/appium\n  appium@\"^1.22.3\" from the root project\n\nCould not resolve dependency:\npeer appium@\"^2.0.0-beta.40\" from appium-windows-driver@2.7.0\nnode_modules/appium-windows-driver\n  dev appium-windows-driver@\"*\" from the root project\n\nFix the upstream dependency conflict, or retry\nthis command with --force or --legacy-peer-deps\nto accept an incorrect (and potentially broken) dependency resolution."
  }
}

STDERR:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: appium@1.22.3
npm ERR! node_modules/appium
npm ERR!   appium@"^1.22.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer appium@"^2.0.0-beta.40" from appium-windows-driver@2.7.0
npm ERR! node_modules/appium-windows-driver
npm ERR!   dev appium-windows-driver@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\stuar\AppData\Local\npm-cache\_logs\2023-02-27T10_10_43_222Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\stuar\AppData\Local\npm-cache\_logs\2023-02-27T10_10_43_222Z-debug-0.log
```

Does anyone have any idea why this isnt installing and if there is anything I can do to install this driver?

Thanks in Advance

**Comment by mykola-mokhnach** [comment] 2023-02-27 10:35
Duplicate of https://github.com/appium/appium/issues/17614

Make sure you deleted all leftovers from the previous Appium 1 deployment.

**Closed by mykola-mokhnach** 2023-02-27 10:35 UTC
