### ISSUE TITLE
“WebDriverAgentRunner_iphonesimulator14.3-x86_64.xctestrun” doesn’t exist."

### ISSUE THREAD

**Issue by ericzhang1124** [appium/appium#14980] opened 2020-12-28 09:31 UTC
## The problem

My app can install on simulator,but can't launch.I hava iOS 13.3 Simulator SDK and i use it ,but when i run,Xcode tell me “WebDriverAgentRunner_iphonesimulator14.3-x86_64.xctestrun” doesn’t exist."

## Environment

* Appium version (or git revision) that exhibits the issue:1.19.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:MacOS Catalina 10.15.7
* Node.js version (unless using Appium.app|exe):v14.15.2
* Npm or Yarn package manager:npm 6.14.9
* Mobile platform/version under test:13.3 
* Real device or emulator/simulator:Simulaotr
* Appium CLI or Appium.app|exe:Appium.app

## Details
[info] [35m[WD Proxy][39m connect ECONNREFUSED 127.0.0.1:8120[error] [35m[Xcode][39m 2020-12-28 17:05:03.888 xcodebuild[77421:2011449] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphonesimulator14.3-x86_64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/chenzhang/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/WebDriverAgentRunner_iphonesimulator14.3-x86_64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7f888e037490 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

## Link to Appium logs
https://gist.github.com/ericzhang1124/abda8e0c39a8d8cb6d6c180c6885c073

**Comment by KazuCocoa** [comment] 2020-12-28 10:04
Duplicate of https://github.com/appium/appium/issues/14952
You have updated Xcode to 12.3.

**Closed by KazuCocoa** 2020-12-28 10:04 UTC
