### ISSUE TITLE
[BaseDriver] The following capabilities were provided, but are not recognized by appium: "appium:platform”,  "appium:automationName”, ”appium:fullReset”, “appium:youiEngineAppAddress”, ”appium:noReset”,  "appium:udid”, “appium:autoGrantPermissions”,”appium:app”, ”appium:appPackage"

### ISSUE THREAD

**Issue by prathapJonnadula** [appium/appium#14631] opened 2020-08-07 03:16 UTC
## The problem
     While trying to create driver for Youi engine  with following capabilities. appium is not recognizing these capabilities
   capabilities: [
      {
 
        'platformName': 'Android',
        'appium:udid':'35565a5a574ad3098',
        'appium:automationName': 'YouiEngine',
        'appium:platform': 'ANDROID',
        'appium:youiEngineAppAddress': '192.168.1.2',
        //'appium:systemPort': '8242',
        //'appium:noSign':'true',
        'appium:app': '/Users/smart/Desktop/Builds/ClientApp.apk',
        //'appium:deviceName': 'MM14-S9',
        //'appium:adbExecTimeout': '10000',
        'appium:appPackage': 'com.mobile.phoenix',
        'appium:autoGrantPermissions': true,
        'appium:fullReset': false,
        'appium:noReset': true,
        'appium:formFactor' : 'MOBILE',
      },
## Environment
      device connected to selenium grid. using below capabilites

    "capabilities":
        [
            {
                "platformName": "Android",
                "platform":"ANDROID",
		"DeviceName":"AndroidPhone-S9",
                "appium:automationName": "YouiEngine",
                "appium:appPackage" : "com.att.mobile.dfw.phoenix",
                "appium:udid": "35565a5a574ad3098",
                "appium:systemPort": "8242"
            }
        ],
    "configuration":
    {
      "cleanUpCycle":2000,
      "timeout":30000,
      "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
      "maxSession": 10,
      "register": true,
      "registerCycle": 5000,
      "hubPort": 8080,
      "hubHost": “<hostIP>”,
      "hubProtocol": "http",
      "role":"node",
      "debug":true
    }
  }

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable):1.17.1
* Desktop OS/version used to run Appium:1.17.1
* Node.js version (unless using Appium.app|exe):10.22.0
* Npm or Yarn package manager: yarn
* Mobile platform/version under test:android
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:appium cli

## Link to Appium logs

https://gist.github.com/prathapJonnadula/3cbaac14f5200e062f5d7451e923e9f5 

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2020-08-07 05:29
The log clearly states that most of the capability names are not recognized, because the server is operating in MJSONWP mode and knows nothing about prefixes. Also, the required platformName capability itself is not provided at all.

**Comment by prathapJonnadula** [comment] 2020-08-07 11:12
@mykola-mokhnach, my very first capability it self is "platformName", Please let me know how can I avoid this problem.

**Comment by mykola-mokhnach** [comment] 2020-08-07 11:30
Provide correct capabilities?

**Comment by prathapJonnadula** [comment] 2020-08-07 11:40
capabilities: [
      {
  
        'platformName': 'ANDROID',
        'appium:udid':'35565a5a574a3098',
        'appium:automationName': 'YouiEngine',
        'platform': 'ANDROID',
        'appium:youiEngineAppAddress': '192.168.1.2',
        'appium:systemPort': '8242',
        'appium:app': '/Users/smart/Desktop/Builds/ClientApp.apk',
        'appium:deviceName': 'MM14-S9',
        'appium:appPackage': 'com.att.mobile.dfw.phoenix',
        'appium:autoGrantPermissions': true,
        'appium:fullReset': false,
        'appium:noReset': true,
        'appium:formFactor' : 'MOBILE',
      },
    ],

**Comment by prathapJonnadula** [comment] 2020-08-07 11:54
With same capabilities I am able to create driver in 1.17.1 with out any issues

Calling AppiumDriver.createSession() with args: [{"platformName":"ANDROID","appium:udid":"35565a5a574a3098","appium:automationName":"YouiEngine","platform":"ANDROID","appium:youiEngineAppAddress":"192.168.1.2","appium:systemPort":"8242","appium:app":"/Users/smart/Desktop/Builds/ClientApp.apk","appium:deviceName":"MM14-S9","appium:appPackage":"com.att.mobile.dfw.phoenix","appium:autoGrantPermissions":true,"appium:fullReset":false,"appium:noReset":true,"appium:formFactor":"MOBILE"},null,{"alwaysMatch":{"platformName":"ANDROID","appium:udid":"35565a5a574a3098","appium:automationName":"YouiEngine","platform":"ANDROID","appium:youiEngineAppAddress":"192.168.1.2","appium:systemPort":"8242","appium:app":"/Users/smart/Desktop/Builds/ClientApp.apk","appium:deviceName":"MM14-S9","appium:appPackage":"com.att.mobile.dfw.phoenix","appium:autoGrantPermissions":true,"appium:fullReset":false,"appium:noReset":true,"appium:formFactor":"MOBILE"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1596800684340 (04:44:44 GMT-0700 (Pacific Daylight Time))
[BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
[BaseDriver]   platform
[Appium] Appium v1.17.1 creating new YouiEngineDriver (v1.2.3) session
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
[debug] [BaseDriver]   "platformName": "ANDROID",
[debug] [BaseDriver]   "udid": "35565a5a574a3098",
[debug] [BaseDriver]   "automationName": "YouiEngine",
[debug] [BaseDriver]   "platform": "ANDROID",
[debug] [BaseDriver]   "youiEngineAppAddress": "192.168.1.2",
[debug] [BaseDriver]   "systemPort": "8242",
[debug] [BaseDriver]   "app": "/Users/smart/Desktop/Builds/ClientApp.apk",
[debug] [BaseDriver]   "deviceName": "MM14-S9",
[debug] [BaseDriver]   "appPackage": "com.att.mobile.dfw.phoenix",
[debug] [BaseDriver]   "autoGrantPermissions": true,
[debug] [BaseDriver]   "fullReset": false,
[debug] [BaseDriver]   "noReset": true,
[debug] [BaseDriver]   "formFactor": "MOBILE"
[debug] [BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   platform
[BaseDriver]   youiEngineAppAddress
[BaseDriver]   systemPort
[BaseDriver]   app
[BaseDriver]   appPackage
[BaseDriver]   autoGrantPermissions
[BaseDriver]   formFactor
[BaseDriver] Session created with session id: 4c8cff52-4070-4e79-aa5e-a47d8665d1f7
[YouiEngineDriver] Starting an Android proxy session
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
[debug] [BaseDriver]   "platformName": "ANDROID",
[debug] [BaseDriver]   "udid": "35565a5a574a3098",
[debug] [BaseDriver]   "automationName": "YouiEngine",
[debug] [BaseDriver]   "platform": "ANDROID",
[debug] [BaseDriver]   "youiEngineAppAddress": "192.168.1.2",
[debug] [BaseDriver]   "systemPort": "8242",
[debug] [BaseDriver]   "app": "/Users/smart/Desktop/Builds/ClientApp.apk",
[debug] [BaseDriver]   "deviceName": "MM14-S9",
[debug] [BaseDriver]   "appPackage": "com.att.mobile.dfw.phoenix",
[debug] [BaseDriver]   "autoGrantPermissions": true,
[debug] [BaseDriver]   "fullReset": false,
[debug] [BaseDriver]   "noReset": true,
[debug] [BaseDriver]   "formFactor": "MOBILE",
[debug] [BaseDriver]   "newCommandTimeout": 0
[debug] [BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   platform
[BaseDriver]   youiEngineAppAddress
[BaseDriver]   systemPort
[BaseDriver]   formFactor
[BaseDriver] Session created with session id: 356a3d11-7442-4a6e-ae82-fe3c11dc1abf
[ADB] Found 1 'build-tools' folders under '/Users/smart/Library/Android/sdk' (newest first):

**Comment by mykola-mokhnach** [comment] 2020-08-13 16:06
Since version 1.18 Appium does not remove capability prefixes for JSONWP sessions, which is expected. 

Closed as not an issue

**Closed by mykola-mokhnach** 2020-08-13 16:06 UTC
Labels: NotABug

**Comment by prathapJonnadula** [comment] 2020-08-20 10:15
Tried in different ways, Selenium grid accepts with "appium" prefix. please suggest other way to solve this problem

**Comment by mykola-mokhnach** [comment] 2020-08-20 10:24
> [HTTP] {"desiredCapabilities":{"server:CONFIG_UUID":"269f731f-943e-4681-8d0e-e50452b19b28","appium:formFactor":"MOBILE","appium:platform":"ANDROID","appium:automationName":"YouiEngine","appium:fullReset":false,"appium:youiEngineAppAddress":"deviceIP","appium:noReset":true,"appium:udid":"35565a5a574a3098","appium:autoGrantPermissions":true,"platformName":"android","appium:app":"/Users/smart/Desktop/Builds/ClientApp.apk","appium:appPackage":"com.att.mobile.dfw.phoenix"},"capabilities":{"firstMatch":[{"appium:app":"/Users/smart/Desktop/Builds/ClientApp.apk","appium:appPackage":"com.att.mobile.dfw.phoenix","appium:autoGrantPermissions":true,"appium:automationName":"YouiEngine","appium:formFactor":"MOBILE","appium:fullReset":false,"appium:noReset":true,"appium:platform":"ANDROID","appium:udid":"35565a5a574a3098","appium:youiEngineAppAddress":"deviceIP","platformName":"android","server:CONFIG_UUID":"269f731f-943e-4681-8d0e-e50452b19b28"}]}}


the problem is in this line. `desiredCapabilities` are the actual JSONWP capabilities and they should not contain any prefixes but they do. Your client is sending them. Not sure which client it is, because it's not stated in the issue description.

**Comment by prathapJonnadula** [comment] 2020-08-20 11:12
@mykola-mokhnach , These capabilities are sent by Selenium Grid

**Comment by mykola-mokhnach** [comment] 2020-08-20 11:28
Then the issue report should probably go to grid
