### ISSUE TITLE
Appium fails to launch app bundle because it is Busy

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#11155] opened 2018-08-06 13:53 UTC
## The problem

Happens randomly while trying to launch app under test or an existing app bundle on device already.

Attached Gist has full info, but the important snippet is 
```
[iOSLog] [IOS_SYSLOG_ROW] Aug  6 09:39:30 iPhone SpringBoard(FrontBoard)[55] <Notice>: [FBSystemService][0xe0bf] Received request to open "com.apple.Preferences" from testmanagerd:255.
[iOSLog] [IOS_SYSLOG_ROW] Aug  6 09:39:30 iPhone testmanagerd[255] <Notice>: <private>
[iOSLog] [IOS_SYSLOG_ROW] Aug  6 09:39:30 iPhone SpringBoard(FrontBoard)[55] <Notice>: [FBSystemService] Trusting entitled client <private>.
[iOSLog] [IOS_SYSLOG_ROW] Aug  6 09:39:30 iPhone SpringBoard(FrontBoard)[55] <Notice>: [FBSystemService][0xe0bf] Application "com.apple.Preferences" is installing (0), uninstalling (1), or pending uninstall (0) and cannot be launched.
[iOSLog] [IOS_SYSLOG_ROW] Aug  6 09:39:30 iPhone SpringBoard(FrontBoard)[55] <Notice>: [FBSystemService][0xe0bf] Open "com.apple.Preferences" request from testmanagerd:255 failed with error: <NSError: 0x1056e7730; domain: FBSOpenApplicationServiceErrorDomain; code: 1 (RequestDenied); reason: "The request was denied by service delegate (SBMainWorkspace) for reason: Busy ("Application "com.apple.Preferences" is installing or uninstalling, and cannot be launched")."> {
[iOSLog] [IOS_SYSLOG_ROW]     description = "The request to open "com.apple.Preferences" failed.";
[iOSLog] [IOS_SYSLOG_ROW]     failureReason = "The request was denied by service delegate (SBMainWorkspace) for reason: Busy ("Application "com.apple.Preferences" is installing or uninstalling, and cannot be launched").";
[iOSLog] [IOS_SYSLOG_ROW]     userInfo = {
[iOSLog] [IOS_SYSLOG_ROW]         FBSOpenApplicationRequestID = <__NSCFNumber: 0xb0000000000e0bf3>;
[iOSLog] [IOS_SYSLOG_ROW]     }
[iOSLog] [IOS_SYSLOG_ROW]     underlyingError = <NSError: 0x107660340; domain: FBSOpenApplicationErrorDomain; code: 6 (Busy); reason: "Application "com.apple.Preferences" is installing or uninstalling, and cannot be launched."> {
[iOSLog] [IOS_SYSLOG_ROW]         description = "The operation couldn\M-b\M^@\M^Yt be completed. Application "com.apple.Preferences" is install
[iOSLog] [IOS_SYSLOG_ROW] Aug  6 09:39:30 iPhone WebDriverAgentRunner-Runner(WebDriverAgentLib)[431] <Notice>: Enqueue Failure: Failed to launch com.apple.Preferences: The operation couldn\M-b\M^@\M^Yt be completed. Application "com.apple.Preferences" is installing or uninstalling, and cannot be launched. /Users/jamesvanhorn/.nvm/versions/node/v10.1.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable): I think this started with 1.8.0?
* Desktop OS/version used to run Appium: Mac High Sierra
* Node.js version (unless using Appium.app|exe): 10.1.0
* Mobile platform/version under test: iOS 11.4.1
* Real device or emulator/simulator: Both (This is a real device log for reference)
* Appium CLI or Appium.app|exe: CLI

## Details

Gist should have all info. Not sure why the device think com.apple.Preferences is installing or uninstalling and cannot be launched. Capabilities passed for this are below. I can try turning off waitForQuiescense, but that will break simulator runs, as the app under test never reports itself as ready when waitForQuiescence is true/omitted. Note, this failing to launch scenario does happen exactly the same way when i have a valid path to a .app/.apk file and no bundle ID for my company's app.

```
app :- 
automationName :- XCUITest
bundleId :- com.apple.Preferences
commandTimeouts :- 180000
deviceName :- iPhone 8 Plus
language :- en
locale :- en_US
maxTypingFrequency :- 5
newCommandTimeout :- 500
platformName :- iOS
platformVersion :- 11.4
showIOSLog :- true
showXcodeLog :- false
udid :- <REMOVED>
waitForQuiescence :- false
xcodeOrgId :- <REMOVED>
```

## Link to Appium logs

https://gist.github.com/jamesvanhorn/10ecd4e917f14c33a7f28257d46d0b3b

## Code To Reproduce Issue [ Good To Have ]

Its just normal driver creation code, nothing worth posting.

**Comment by mykola-mokhnach** [comment] 2018-08-06 13:57
I don't thinks there is anything that can be done in Appium to address this.

**Comment by imurchie** [comment] 2018-08-06 13:58
By "this failing to launch scenario does happen exactly the same way when i have a valid path" do you mean that you are launching your app but the error is still for `com.apple.Preferences`? Or it has the same message but for your app?

**Comment by mykola-mokhnach** [comment] 2018-08-06 14:00
Perhaps, it makes sense to set `noReset` to true

**Comment by imurchie** [comment] 2018-08-06 14:01
I would also experiment with removing `language` and `locale`, just to see. :(

**Comment by jamesvanhorn** [comment] 2018-08-06 14:19
@imurchie same message but bundleId replace with my app. Basically, the error doesn't seem to be related to either use of `app` (implying a fresh install) or `bundleId` (implying noReset no install scenario) capabilities. It would make more sense to me if this was only happening with my app on an actual install, then i could use iosInstallPause as a fix. Makes no sense to me the device is saying im trying install/uninstall an app i have no control over.

**Comment by jamesvanhorn** [comment] 2018-08-06 15:08
Restarting the device fixes it (at least for a little while). I put in some extra changes too when we invoke pre-installed apps. Making sure to set noReset true, fullReset false, and removing the app capability entirely in that scenario. 

My entirely unfounded wild guess is the mix of capabilities we sent in were trying to uninstall/reinstall 
 com.apple.Preferences (since `noReset` was not set and `app` was there but empty), and that eventually put com.apple.Preferences into a bad state?

**Comment by mykola-mokhnach** [comment] 2018-08-10 11:58
Closed as not a bug

**Closed by mykola-mokhnach** 2018-08-10 11:58 UTC
Labels: NotABug
