### ISSUE TITLE
Appium driver set timeout not working

### ISSUE THREAD

**Issue by nieschumi** [appium/appium#6400] opened 2016-04-12 22:14 UTC
## The problem

I'm running the same code for test on appium 1.4.16, but when I upgrade to appium 1.5.1, I found out appium driver is not set with a wait time, tests are fast fail on not able to find an element.

## Environment

Appium 1.5.1 and 1.4.16
Desktop OS/version used to run Appium: OS X EI Capitan 10.11.3 and 10.11.1
Node.js version (unless using Appium.app|exe): v0.12.7 and v4.2.1
Mobile platform/version under test: Android 6.0
Real device or emulator/simulator: emulator

## Link to Appium logs

https://gist.github.com/nieschumi/bec15ba6bc75006e2e3fc3a52e24b6c3

## Code To Reproduce Issue [ Good To Have ]

     `public static DesiredCapabilities capabilities = new DesiredCapabilities();
      capabilities.setCapability("deviceName", "Nexus6");
      capabilities.setCapability("platformVersion", "6.0");
      capabilities.setCapability("platformName", "Android");
      capabilities.setCapability("avd", "Nexus6");
      capabilities.setCapability("waitForAppScript", true);
      capabilities.setCapability("locationServicesEnabled", true);
      capabilities.setCapability("autoAcceptAlerts", true);
      capabilities.setCapability("noReset", true);
      capabilities.setCapability("sendKeyStrategy", "setValue");

      public static AppiumDriver driver;
      driver = new AndroidDriver(new URL(remoteAddress), capabilities);
      ((AndroidDriver) driver).setNetworkConnection(new NetworkConnectionSetting(false, true, true));           
      driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);`

**Comment by SrinivasanTarget** [comment] 2016-04-13 07:43
@nieschumi Can you please try with newCommandTimeout option in your desired capabilities?

**Comment by nieschumi** [comment] 2016-04-13 15:29
@SrinivasanTarget  I added `capabilities.setCapability("newCommandTimeout", 10);`

Appium log still shows 
[HTTP] --> POST /wd/hub/session/ccfeb030-63cf-4739-b25a-d8a7ded4d65e/timeouts {"type":"implicit","ms":15000}
[MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",15000,"ccfeb030-63cf-4739-b25a-d8a7ded4d65e"]
[MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/ccfeb030-63cf-4739-b25a-d8a7ded4d65e/timeouts 200 2 ms - 76 
[HTTP] --> POST /wd/hub/session/ccfeb030-63cf-4739-b25a-d8a7ded4d65e/element {"using":"id","value":"launchPageLogInButton"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","launchPageLogInButton","ccfeb030-63cf-4739-b25a-d8a7ded4d65e"]
[debug] [BaseDriver] Waiting up to 0 ms for condition

**Comment by brtu** [comment] 2016-04-13 16:22
there's a forum thread about the issues as well here: https://discuss.appium.io/t/implicit-wait-is-not-working-in-appium-1-5/9167

**Comment by trigoesrodrigo** [comment] 2016-04-13 20:29
It happened to me with 1.4 when implicitWait was set at the beggining of tests and I used an explicit sleep afterwards (I was using node + Mocha)

**Comment by imurchie** [comment] 2016-04-13 20:50
This is an issue with how the base driver deals with timeouts. This will be fixed. In the meantime, you can set the the implicit wait explicitly (not sure how to do it in your client, but it should be possible).

**Comment by imurchie** [comment] 2016-04-15 16:11
I've updated the base driver to fix this. You can re-install appium with the `--no-shrinkwrap` flag, or wait for 1.5.2.

**Comment by SrinivasanTarget** [comment] 2016-05-07 06:04
@nieschumi Incase if you hit the same in Appium 1.5.2, please reopen with logs inform of gist.

**Comment by SrinivasanTarget** [comment] 2016-05-07 06:04
@triager please close

**Closed by SrinivasanTarget** 2016-05-07 06:04 UTC
Labels: NeedsTriage

**Comment by sgt00kb** [comment] 2017-09-12 18:21
I am on Appium 1.6.5, but and this just happened to me. Any suggestion? 

[debug] [MJSONWP] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/87b9e763-d46b-4289-92ee-f230a647ddf9/elements 200 203 ms - 74
[HTTP] --> POST /wd/hub/session/87b9e763-d46b-4289-92ee-f230a647ddf9/timeouts {"type":"implicit","ms":120000}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",120000,"87b9e763-d46b-4289-92ee-f230a647ddf9"]
[debug] [BaseDriver] Set implicit wait to 120000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null

**Comment by imurchie** [comment] 2017-09-12 18:58
@sgt00kb I do not understand what the issue is. The bit of log you present shows things working correctly.

Does the timeout not show up when you go to find an element?

**Comment by sgt00kb** [comment] 2017-09-12 19:23
@imurchie  
I thought "[debug] [MJSONWP] Responding to client with driver.timeouts() result: null" means the timeout didn't happen. 

But, anyway, the behavior I'm seeing here is, no matter what I set for time or TimeUnit, Appium doesn't wait. 

I can provide more log as well.

**Comment by imurchie** [comment] 2017-09-12 19:33
That log line just means the operation does not return anything.

Please provide the full logs (as a link to a [gist](https://gist.github.com)) where you set the implicit wait and then try to find an element (preferably one that is either not there or does not appear for a bit, so the implicit wait actually has some affect).

**Comment by sgt00kb** [comment] 2017-09-12 19:42
This is one part of a code I have, is this what you mean by set the implicit wait to find an element? 
Also, thank you so much for getting back to me so quickly. :) 


`        while(driver.findElementsByAccessibilityId(EMAIL_ACL).size() == 0){
            driver.manage().timeouts().implicitlyWait(20, TimeUnit.MINUTES);
        }`

**Comment by imurchie** [comment] 2017-09-12 19:46
No. I'm not sure what you're trying to do there. I mean setting the implicit wait on the server, and then trying to find a single element. Finding multiple elements does not use the implicit wait.

Something like
```java
driver.manage().timeouts().implicitlyWait(20, TimeUnit.MINUTES);
driver.findElementByAccessibilityId(EMAIL_ACL);
```

**Comment by sgt00kb** [comment] 2017-09-12 19:52
[Here is the git](https://gist.github.com/sgt00kb/f4ef28499e1b6f0127cff89a1e7422cc)

Code that I used: 
@Before

@Test
`        driver.manage().timeouts().implicitlyWait(120, TimeUnit.MINUTES);
        driver.findElementByAccessibilityId(EMAIL_ACL);`

@After

**Comment by imurchie** [comment] 2017-09-12 20:05
@sgt00kb This looks like it is working fine. The lines like `[debug] [BaseDriver] Waited for 2856 ms so far` indicate that the implicit wait is set and things are waiting.

If you were to do this, but try to find an element that does not exist, you would wait 7200000 ms (assuming the server doesn't timeout for other reasons).

**Comment by sgt00kb** [comment] 2017-09-12 20:18
Ohhh, I see where I misunderstood everything. I got an impression([Shamelessly blaming here](https://stackoverflow.com/questions/28799420/how-to-wait-to-activity-using-appium-on-begin-and-during-test-itself)) of, if I use implicityWait, the drive will just wait for X TimeUnit, like TimeUnit.SECONDS.sleep(30); in Java. 

Thank you so much for making things clear. :)))

**Comment by imurchie** [comment] 2017-09-12 20:21
Ah! That would be an _explicit_ wait. http://docs.seleniumhq.org/docs/04_webdriver_advanced.jsp#explicit-and-implicit-waits

**Comment by sgt00kb** [comment] 2017-09-12 20:42
@imurchie  
Thank you for the link! 
In our code, we have some other third party library popping things up with no id. So I had to go with either wait in Java or threadwait. :(
