### ISSUE TITLE
[Appium][XCUITest]How to display [XCUITest] System log exited with code '0'

### ISSUE THREAD

**Issue by TranTrieuLamQuynh** [appium/appium#13784] opened 2020-01-02 09:38 UTC
Hi all,
I have a little problem with XCUITest.
I run test success but log "[XCUITest] System log exited with code '0'" not display.
Is it because my config is missing? Hope everybody help please.
Thanks

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Desktop OS/version used to run Appium: 10.15
* Node.js version (unless using Appium.app|exe):13.2
* Npm or Yarn package manager:6.13
* Mobile platform/version under test:iOS
* Real device: 12.2

## Link to Appium logs
[Appium] Welcome to Appium v1.15.1
[Appium] Non-default server args:
[Appium]   relaxedSecurityEnabled: true
[Appium]   udid: 0394d3e54f63ced8b8a59b5ef97270cff2351aee
[Appium] Deprecated server args:
[Appium]   -U,--udid => --default-capabilities '{"udid":"0394d3e54f63ced8b8a59b5ef97270cff2351aee"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   udid: 0394d3e54f63ced8b8a59b5ef97270cff2351aee
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
Run options: include {:feature=>"ios"}
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appium-version":"1.15.1","platformName":"iOS","platformVersion":"12.1.1","deviceName":"*","noReset":true,"autoLaunch":false,"app":"/Users/JerrySWAT/gst.earth.autof/helpers/ipa/SSC KIB.ipa","bundleId":"jp.shinkin.ib.app.03","automationName":"XCUITest","skipUnlock":true,"newCommandTimeout":6000,"wdaLocalPort":"8100"},"capabilities":{"firstMatch":[{"appium:appium-version":"1.15.1","platformName":"iOS","appium:platformVersion":"12.1.1","appium:deviceName":"*","appium:noReset":true,"appium:autoLaunch":false,"appium:app":"/Users/JerrySWAT/gst.earth.autof/helpers/ipa/SSC KIB.ipa","appium:bundleId":"jp.shinkin.ib.app.03","appium:automationName":"XCUITest","appium:skipUnlock":true,"appium:newCommandTimeout":6000,"appium:wdaLocalPort":"8100"}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"appium-version":"1.15.1","platformName":"iOS","platformVersion":"12.1.1","deviceName":"*","noReset":true,"autoLaunch":false,"app":"/Users/JerrySWAT/gst.earth.autof/helpers/ipa/SSC KIB.ipa","bundleId":"jp.shinkin.ib.app.03","automationName":"XCUITest","skipUnlock":true,"newCommandTimeout":6000,"wdaLocalPort":"8100"},null,{"firstMatch":[{"appium:appium-version":"1.15.1","platformName":"iOS","appium:platformVersion":"12.1.1","appium:deviceName":"*","appium:noReset":true,"appium:autoLaunch":false,"appium:app":"/Users/JerrySWAT/gst.earth.autof/helpers/ipa/SSC KIB.ipa","appium:bundleId":"jp.shinkin.ib.app.03","appium:automationName":"XCUITest","appium:skipUnlock":true,"appium:newCommandTimeout":6000,"appium:wdaLocalPort":"8100"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1577957798202 (16:36:38 GMT+0700 (Indochina Time))
[BaseDriver] The capabilities ["udid"] are not standard capabilities and should have an extension prefix
[Appium] Appium v1.15.1 creating new XCUITestDriver (v2.133.1) session
[Appium] Applying relaxed security to 'XCUITestDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "iOS",
[debug] [BaseDriver]     "appium:udid": "0394d3e54f63ced8b8a59b5ef97270cff2351aee",
[debug] [BaseDriver]     "appium:appium-version": "1.15.1",
[debug] [BaseDriver]     "appium:platformVersion": "12.1.1",
[debug] [BaseDriver]     "appium:deviceName": "*",
[debug] [BaseDriver]     "appium:noReset": true,
[debug] [BaseDriver]     "appium:autoLaunch": false,
[debug] [BaseDriver]     "appium:app": "/Users/JerrySWAT/gst.earth.autof/helpers/ipa/SSC KIB.ipa",
[debug] [BaseDriver]     "appium:bundleId": "jp.shinkin.ib.app.03",
[debug] [BaseDriver]     "appium:automationName": "XCUITest",
[debug] [BaseDriver]     "appium:skipUnlock": true,
[debug] [BaseDriver]     "appium:newCommandTimeout": 6000,
[debug] [BaseDriver]     "appium:wdaLocalPort": "8100"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[BaseDriver] Capability 'wdaLocalPort' changed from string ('8100') to integer (8100). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   appium-version
[BaseDriver]   skipUnlock
[BaseDriver] Session created with session id: 64dc497d-bc8a-48ca-8590-434d7f48f53c
[debug] [XCUITest] Current user: 'JerrySWAT'
[debug] [XCUITest] Available devices: 0394d3e54f63ced8b8a59b5ef97270cff2351aee
[debug] [XCUITest] Creating iDevice object with udid '0394d3e54f63ced8b8a59b5ef97270cff2351aee'
[XCUITest] Determining device to run tests on: udid: '0394d3e54f63ced8b8a59b5ef97270cff2351aee', real device: true
[XCUITest] Normalized platformVersion capability value '12.1.1' to '12.1'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1577957798745 (16:36:38 GMT+0700 (Indochina Time))
[BaseDriver] Using local app '/Users/JerrySWAT/gst.earth.autof/helpers/ipa/SSC KIB.ipa'
[debug] [BaseDriver] Unzipping '/Users/JerrySWAT/gst.earth.autof/helpers/ipa/SSC KIB.ipa'
[debug] [BaseDriver] Extracted 115 item(s) from '/Users/JerrySWAT/gst.earth.autof/helpers/ipa/SSC KIB.ipa'
[debug] [BaseDriver] Matched 114 item(s) in the extracted archive. Assuming 'Payload/SSC KIB.app' is the correct bundle
[BaseDriver] Unzipped local app to '/var/folders/5w/rw5n2fg916l1_27vm1wkfdzc0000gn/T/202002-68022-1uf3bux.v4jd/Payload/SSC KIB.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1577957799529 (16:36:39 GMT+0700 (Indochina Time))
[debug] [XCUITest] Checking whether app '/var/folders/5w/rw5n2fg916l1_27vm1wkfdzc0000gn/T/202002-68022-1uf3bux.v4jd/Payload/SSC KIB.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [BaseDriver] Event 'resetStarted' logged at 1577957799530 (16:36:39 GMT+0700 (Indochina Time))
[debug] [XCUITest] Reset: fullReset not set. Leaving as is
[debug] [BaseDriver] Event 'resetComplete' logged at 1577957799530 (16:36:39 GMT+0700 (Indochina Time))
[debug] [XCUITest] Crash reports root '/Users/JerrySWAT/Library/Logs/CrashReporter/MobileDevice/Jimmy Hoang’s iPad' does not exist. Got nothing to gather.
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1577957799742 (16:36:39 GMT+0700 (Indochina Time))
[XCUITest] Setting up real device
[debug] [XCUITest] Verifying application platform
[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[debug] [XCUITest] Installing '/var/folders/5w/rw5n2fg916l1_27vm1wkfdzc0000gn/T/202002-68022-1uf3bux.v4jd/Payload/SSC KIB.app' on device with UUID '0394d3e54f63ced8b8a59b5ef97270cff2351aee'...
[debug] [XCUITest] Pushed the app files successfully after 2899ms
[XCUITest] Installation is successful after 3740ms
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1577957803717 (16:36:43 GMT+0700 (Indochina Time))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device 0394d3e54f63ced8b8a59b5ef97270cff2351aee on local port 8100, device port 8100
[debug] [DevCon Factory] Cached connections count: 0
[DevCon Factory] Port #8100 is busy
[DevCon Factory] Successfully requested the connection for 0394d3e54f63ced8b8a59b5ef97270cff2351aee:8100
[debug] [XCUITest] Parsed BUILD_DIR configuration value: '/Users/JerrySWAT/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Build/Products'
[debug] [XCUITest] Got derived data root: '/Users/JerrySWAT/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu'
[debug] [XCUITest] Starting WebDriverAgent initialization with the synchronization key '/Users/JerrySWAT/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@0394d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'
[debug] [XCUITest] WDA is currently not running. There is nothing to cache
[debug] [XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1577957807433 (16:36:47 GMT+0700 (Indochina Time))
[XCUITest] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Dependencies up-to-date
[debug] [XCUITest] Killing running processes 'xcodebuild.*0394d3e54f63ced8b8a59b5ef97270cff2351aee' for the device 0394d3e54f63ced8b8a59b5ef97270cff2351aee...
[debug] [XCUITest] 'pgrep -ifn xcodebuild.*0394d3e54f63ced8b8a59b5ef97270cff2351aee' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/JerrySWAT/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu -destination id=0394d3e54f63ced8b8a59b5ef97270cff2351aee IPHONEOS_DEPLOYMENT_TARGET=12.1 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
[debug] [XCUITest] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@0394d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@0394d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@0394d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [XCUITest] Log file for xcodebuild test: /Users/JerrySWAT/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs/Test/Test-WebDriverAgentRunner-2020.01.02_16-36-49-+0700.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-046FD5F5-6CA1-4B27-9016-806D92AE1CC1/WebDriverAgentRunner-05C94A4B-90A1-4E1F-83B9-5328A5864F18/Session-WebDriverAgentRunner-2020-01-02_163650-S5b7Cd.log
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@0394d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@0394d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@0394d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@0394d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@0394d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@0394d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : {
[debug] [WD Proxy]     "message" : "WebDriverAgent is ready to accept commands",
[debug] [WD Proxy]     "state" : "success",
[debug] [WD Proxy]     "os" : {
[debug] [WD Proxy]       "name" : "iOS",
[debug] [WD Proxy]       "version" : "12.1.1",
[debug] [WD Proxy]       "sdkVersion" : "13.0"
[debug] [WD Proxy]     },
[debug] [WD Proxy]     "ios" : {
[debug] [WD Proxy]       "simulatorVersion" : "12.1.1",
[debug] [WD Proxy]       "ip" : "10.16.191.56"
[debug] [WD Proxy]     },
[debug] [WD Proxy]     "ready" : true,
[debug] [WD Proxy]     "build" : {
[debug] [WD Proxy]       "upgradedAt" : "1576210592072",
[debug] [WD Proxy]       "time" : "Jan  2 2020 16:08:55",
[debug] [WD Proxy]       "productBundleIdentifier" : "com.facebook.WebDriverAgentRunner"
[debug] [WD Proxy]     }
[debug] [WD Proxy]   },
[debug] [WD Proxy]   "sessionId" : "975B9376-819F-4C1A-B234-87D152876065"
[debug] [WD Proxy] }
[debug] [XCUITest] WebDriverAgent information:
[debug] [XCUITest] {
[debug] [XCUITest]   "message": "WebDriverAgent is ready to accept commands",
[debug] [XCUITest]   "state": "success",
[debug] [XCUITest]   "os": {
[debug] [XCUITest]     "name": "iOS",
[debug] [XCUITest]     "version": "12.1.1",
[debug] [XCUITest]     "sdkVersion": "13.0"
[debug] [XCUITest]   },
[debug] [XCUITest]   "ios": {
[debug] [XCUITest]     "simulatorVersion": "12.1.1",
[debug] [XCUITest]     "ip": "10.16.191.56"
[debug] [XCUITest]   },
[debug] [XCUITest]   "ready": true,
[debug] [XCUITest]   "build": {
[debug] [XCUITest]     "upgradedAt": "1576210592072",
[debug] [XCUITest]     "time": "Jan  2 2020 16:08:55",
[debug] [XCUITest]     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
[debug] [XCUITest]   }
[debug] [XCUITest] }
[debug] [XCUITest] WebDriverAgent successfully started after 9988ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1577957817460 (16:36:57 GMT+0700 (Indochina Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"capabilities":{"firstMatch":[{"arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[debug] [WD Proxy] Got response with status 200: {"value":{"sessionId":"DA870FC2-53D3-4B4F-BBD0-69C4F7CA6DF9","capabilities":{"device":"ipad","browserName":" ","sdkVersion":"12.1.1","CFBundleIdentifier":"com.apple.springboard"}},"sessionId":"DA870FC2-53D3-4B4F-BBD0-69C4F7CA6DF9"}
[WD Proxy] Determined the downstream protocol as 'W3C'
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1577957817595 (16:36:57 GMT+0700 (Indochina Time))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1577957817596 (16:36:57 GMT+0700 (Indochina Time))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [BaseDriver] Event 'orientationSet' logged at 1577957817596 (16:36:57 GMT+0700 (Indochina Time))
[Appium] New XCUITestDriver session created successfully, session 64dc497d-bc8a-48ca-8590-434d7f48f53c added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1577957817597 (16:36:57 GMT+0700 (Indochina Time))
[debug] [W3C (64dc497d)] Cached the protocol value 'W3C' for the new session 64dc497d-bc8a-48ca-8590-434d7f48f53c
[debug] [W3C (64dc497d)] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"iOS","udid":"0394d3e54f63ced8b8a59b5ef97270cff2351aee","appium-version":"1.15.1","platformVersion":"12.1.1","deviceName":"*","noReset":true,"autoLaunch":false,"app":"/Users/JerrySWAT/gst.earth.autof/helpers/ipa/SSC KIB.ipa","bundleId":"jp.shinkin.ib.app.03","automationName":"XCUITest","skipUnlock":true,"newCommandTimeout":6000,"wdaLocalPort":8100}}
[HTTP] <-- POST /wd/hub/session 200 19408 ms - 640
[HTTP] 
[HTTP] --> POST /wd/hub/session/64dc497d-bc8a-48ca-8590-434d7f48f53c/timeouts
[HTTP] {"implicit":0}
[debug] [W3C (64dc497d)] Calling AppiumDriver.timeouts() with args: [null,null,null,null,0,"64dc497d-bc8a-48ca-8590-434d7f48f53c"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] W3C timeout argument: {"implicit":0}}
[debug] [BaseDriver] Set implicit wait to 0ms
[debug] [W3C (64dc497d)] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/64dc497d-bc8a-48ca-8590-434d7f48f53c/timeouts 200 46 ms - 14
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.15.1"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[HTTP] --> POST /wd/hub/session/64dc497d-bc8a-48ca-8590-434d7f48f53c/appium/device/activate_app
[HTTP] {"bundleId":"jp.shinkin-ib.app.03"}
[debug] [W3C (64dc497d)] Calling AppiumDriver.activateApp() with args: ["jp.shinkin-ib.app.03",null,null,null,"64dc497d-bc8a-48ca-8590-434d7f48f53c"]
[debug] [XCUITest] Executing command 'activateApp'
[debug] [WD Proxy] Proxying [POST /wda/apps/launch] to [POST http://localhost:8100/session/DA870FC2-53D3-4B4F-BBD0-69C4F7CA6DF9/wda/apps/launch] with body: {"bundleId":"jp.shinkin-ib.app.03"}
[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"DA870FC2-53D3-4B4F-BBD0-69C4F7CA6DF9"}
[debug] [W3C (64dc497d)] Responding to client with driver.activateApp() result: null
[HTTP] <-- POST /wd/hub/session/64dc497d-bc8a-48ca-8590-434d7f48f53c/appium/device/activate_app 200 1181 ms - 14
[HTTP] 
[HTTP] --> POST /wd/hub/session/64dc497d-bc8a-48ca-8590-434d7f48f53c/appium/device/terminate_app
[HTTP] {"appId":"jp.shinkin-ib.app.03"}
[debug] [W3C (64dc497d)] Calling AppiumDriver.terminateApp() with args: ["jp.shinkin-ib.app.03",null,null,null,"64dc497d-bc8a-48ca-8590-434d7f48f53c"]
[debug] [XCUITest] Executing command 'terminateApp'
[debug] [WD Proxy] Proxying [POST /wda/apps/terminate] to [POST http://localhost:8100/session/DA870FC2-53D3-4B4F-BBD0-69C4F7CA6DF9/wda/apps/terminate] with body: {"bundleId":"jp.shinkin-ib.app.03"}
[debug] [WD Proxy] Got response with status 200: {"value":true,"sessionId":"DA870FC2-53D3-4B4F-BBD0-69C4F7CA6DF9"}
[debug] [W3C (64dc497d)] Responding to client with driver.terminateApp() result: true
[HTTP] <-- POST /wd/hub/session/64dc497d-bc8a-48ca-8590-434d7f48f53c/appium/device/terminate_app 200 1094 ms - 14
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/64dc497d-bc8a-48ca-8590-434d7f48f53c
[HTTP] {}
[debug] [W3C (64dc497d)] Calling AppiumDriver.deleteSession() with args: ["64dc497d-bc8a-48ca-8590-434d7f48f53c"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1577957819948 (16:36:59 GMT+0700 (Indochina Time))
[Appium] Removing session 64dc497d-bc8a-48ca-8590-434d7f48f53c from our master session list
[debug] [WD Proxy] Matched '/session/64dc497d-bc8a-48ca-8590-434d7f48f53c' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /session/64dc497d-bc8a-48ca-8590-434d7f48f53c] to [DELETE http://localhost:8100/session/DA870FC2-53D3-4B4F-BBD0-69C4F7CA6DF9] with no body
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : null,
[debug] [WD Proxy]   "sessionId" : "D932BF25-3CBD-437E-A839-69C6C3C07C15"
[debug] [WD Proxy] }
[DevCon Factory] Releasing connections for 0394d3e54f63ced8b8a59b5ef97270cff2351aee device on any port number
[DevCon Factory] Found cached connections to release: ["0394d3e54f63ced8b8a59b5ef97270cff2351aee:8100"]
[DevCon Factory] Releasing the listener for '0394d3e54f63ced8b8a59b5ef97270cff2351aee:8100'
[debug] [DevCon Factory] Cached connections count: 0
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1577957819962 (16:36:59 GMT+0700 (Indochina Time))
[debug] [W3C (64dc497d)] Received response: null
[debug] [W3C (64dc497d)] But deleting session, so not returning
[debug] [W3C (64dc497d)] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/64dc497d-bc8a-48ca-8590-434d7f48f53c 200 15 ms - 14
[HTTP]

**Comment by mykola-mokhnach** [comment] 2020-01-02 10:21
I don't understand what the issue is? Could you please describe it more precisely? Like, actual steps and the expected/actual result

**Comment by TranTrieuLamQuynh** [comment] 2020-01-03 02:10
@mykola-mokhnach 
Some examples on the net I see have the log 
"[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 61556)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Shutting down Logger process (pid 61562)
[XCUITest] System log exited with code '0' "
But mine is not. We need to capture the log "[XCUITest] System log exited with code '0'" to identify the completed process.
Thanks for your help.

**Comment by mykola-mokhnach** [comment] 2020-01-03 07:47
> We need to capture the log "[XCUITest] System log exited with code '0'" to identify the completed process.

I still don't quite understand the issue. The actual log lines might be different in different Appium versions. Since Appium 1.15 the xcuitest driver uses direct connection to iOS device via appium-ios-device lib, so such log line does not exist.

**Comment by mykola-mokhnach** [comment] 2020-01-06 06:27
Closed as not an issue

**Closed by mykola-mokhnach** 2020-01-06 06:27 UTC
Labels: NeedsInfo, NotABug
