### ISSUE TITLE
React Native Project - Android Tests Taking Way Longer than iOS

### ISSUE THREAD

**Issue by tpasinetti** [appium/appium#15481] opened 2021-06-10 05:03 UTC
## The problem

I am automating a react native app and no matter what locator I use for the Android tests, it takes ages for each step in the test. One test on iOS runs in 30 seconds, and on Android it takes up to 7 mins.

The test that is in the logs below is a simple test, it closes an overlay tutorial screen, then verifies if 2 buttons and 2 links are displayed on the screen.

Appium v 1.19.1

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/tpasinetti/d5d8941d2f16af4a9c1bed1c9e9d7f91

**Comment by mykola-mokhnach** [comment] 2021-06-10 05:11
Possible duplicate of https://github.com/appium/appium/issues/9147

**Comment by tpasinetti** [comment] 2021-06-10 05:16
> Possible duplicate of #9147

Even once I move past closing the overlay every single appium step takes > 30 seconds. e.g. clicking an element, typing input in a field

**Comment by tpasinetti** [comment] 2021-06-10 05:31
Actually I think I solved the issue by adding the waitforidletimeout settings, thanks for posting the possible duplicate issue: 
There is about 3 seconds difference now between Android and iOS instead of multiple minutes.

For anyone else who has this issue this is what I added to get it to work:

((HasSettings) driver).setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, 500);

**Closed** 2021-06-10 06:35 UTC
Labels: NeedsInfo, ThirdParty, UIAutomator2
