### ISSUE TITLE
Failed to get PID for the following process:<pakageName>(process name must be specified if not equal to package name) 

### ISSUE THREAD

**Issue by wanghengkun** [appium/appium#15192] opened 2021-03-14 13:44 UTC
## The problem
Failed to get PID for the following process:<pakageName>
(process name must be specified if not equal to package name) 

## Environment
appium 1.13.0/ 1.19.1/ 1.20.2
java-client 6.1.0/7.0.0/7.4.1
Android 7.1.1  1+ 5plus  
Third party app  root+xposed+webviewdebughook
windows10

## Details
// 1、 androidDriver.getContextHandles  success
Set<String> contextHandles = androidDriver.getContextHandles();
//return  [NATIVE_APP, WEBVIEW_\<pakageName\>]

// 2、 androidDriver.context error
androidDriver.context("WEBVIEW_\<pakageName\>");
//throw Failed to get PID for the following process:\<pakageName\>

root+xposed+webviewdebughook + Third party Hybrid app  able to connect using chrome remote debugger,but can not context webview

## Link to Appium logs
https://gist.github.com/wanghengkun/e5c26fd6db7820cf977411cc084696bc

**Comment by mykola-mokhnach** [comment] 2021-03-14 20:58
The error is coming from chromedriver itself. Please report it to Google. I don't observe any issues on the Appium side there

**Comment by mykola-mokhnach** [comment] 2021-03-14 21:01
Also duplicate of https://github.com/appium/appium/issues/13621 https://github.com/appium/appium/issues/14293

**Comment by wanghengkun** [comment] 2021-03-15 02:25
## chromedriver doc
The following capabilities are only applicable to WebView apps.
androidActivity: Name of the Activity hosting the WebView.
androidProcess: (Optional) Process name of the Activity hosting the WebView (as given by ps). If not given, the process name is assumed to be the same as androidPackage. 

How do I set up AndroidProcess via AppIum？

**Comment by mykola-mokhnach** [comment] 2021-03-15 06:02
Check https://github.com/appium/appium-uiautomator2-driver#web-context

Closed as not an issue

**Closed by mykola-mokhnach** 2021-03-15 06:02 UTC
Labels: Mobile Chrome, ThirdParty
