### ISSUE TITLE
Failed to action tap due to padding at the bottom of the application

### ISSUE THREAD

**Issue by Lerner17** [appium/appium#14563] opened 2020-07-16 15:46 UTC
## The problem
On some smartphones, there is some kind of indentation at the bottom of the application. The touch-action does not work within the padding, but others, such as a long press or multi-touch, work. When do tap returns an error: `selenium.common.exceptions.InvalidArgumentException: Message: the coordinate [x = 54.0, y = 1387.0] is outside the element rectangle: [0,0] [720,1369]`

## Environment

* Appium 1.17.1
* Desktop OS: Mac OS / Linux
* Android 9
* Samsung Galaxy S10, Xiaomi Redmi 8

## Details

We conduct tests of our own keyboard for Android. On some smartphones, a problem arises: Indentation appears at the bottom of the phone, which can be seen in the screenshot. When you try to make a tap action, an exception occurs and everything ends. Other actions work, such as multitap, long press, etc. Because of this, it is not possible to test the bottom row of keys on the keyboard.

[Screenshot 1](https://ibb.co/wr7bxGM)
[Screenshot 2](https://ibb.co/C5N2yPh)

## Link to Appium logs

[GIST](https://gist.github.com/Lerner17/682330f9f83b512ff92e51dc0830c74e)

**Comment by mykola-mokhnach** [comment] 2020-07-16 20:48
This is a limitation of UiAutomator framework. Please let us know if you find a workaround for it

**Comment by mykola-mokhnach** [comment] 2020-07-16 21:50
Duplicate of https://github.com/appium/appium/issues/11244

**Comment by mykola-mokhnach** [comment] 2020-07-19 15:38
Perhaps using adb overscan could be somehow helpful in this situation: https://android.stackexchange.com/questions/115484/resize-screen-to-display-only-on-working-part-of-semi-functional-touchscreen

**Comment by mykola-mokhnach** [comment] 2020-07-22 06:27
Closed as third party issue

**Closed by mykola-mokhnach** 2020-07-22 06:27 UTC
Labels: ThirdParty, UIAutomator2

**Comment by Kertic** [comment] 2021-05-20 14:40
> This is a limitation of UiAutomator framework. Please let us know if you find a workaround for it

https://github.com/appium/appium/issues/8724#issuecomment-414044097

This is a workaround for it. I would really like to see this being used instead., especially considering they've removed overscan.
