### ISSUE TITLE
iPad real device test and inspecting speed is extremely slow

### ISSUE THREAD

**Issue by senevit4** [appium/appium#9985] opened 2018-01-15 11:44 UTC
## The problem

iPad real device test and inspecting speed is still extremely slow. Comparing with iPhone iPad is 5 and more times slower (100 seconds on iPhone and 400 on iPad for the same test execution). Also it looks like getPageSource() slowness is not fixed on iPad or even become worse.
## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2 including latest beta.
* Desktop OS/version used to run Appium: OS X 10.13.2
* Node.js version (unless using Appium.app|exe): 9.4.0
* Mobile platform/version under test: iOS 11
* Real device or emulator/simulator: iPad
* Appium CLI or Appium.app|exe: both

## Link to Appium logs

No any special logs with errors or something else are available , everything looks ok except reactions on commands comes after a huge  amount of time.

**Comment by mykola-mokhnach** [comment] 2018-01-15 12:51
Duplicate of https://github.com/facebook/WebDriverAgent/issues/639

**Closed by mykola-mokhnach** 2018-01-15 12:51 UTC
