### ISSUE TITLE
npm install -g appium

### ISSUE THREAD

**Issue by DavidEngNJ** [appium/appium#12369] opened 2019-03-22 15:32 UTC
## The problem

Appium installation fails at downloading chromedriver.  When I checked the folder the driver is there, so not sure why it fails.  I WAS able to download the Appium client, WS; just not Appium server.

[Snippet]
[17:47:56] [Chromedriver Install] Downloading https://chromedriver.storage.googleapis.com/2.46/chromedriver_win32.zip...
RequestError: Error: connect ETIMEDOUT 172.217.164.144:443

[Full message]
```
c:\node-v10.15.3-win-x64>npm install -g appium
npm WARN deprecated fsevents@2.0.1: Not Ready For Production
c:\node-v10.15.3-win-x64\authorize-ios -> c:\node-v10.15.3-win-x64\node_modules\appium\node_modules\.bin\authorize-ios
c:\node-v10.15.3-win-x64\appium -> c:\node-v10.15.3-win-x64\node_modules\appium\build\lib\main.js

> appium-chromedriver@4.11.0 install c:\node-v10.15.3-win-x64\node_modules\appium\node_modules\appium-chromedriver
> node install-npm.js

[17:47:56] [Chromedriver Install] Installing Chromedriver version '2.46' for platform 'win' and architecture '32'
[17:47:56] [Chromedriver Install] Opening temp file to write 'chromedriver_win32' to...
[17:47:56] [Chromedriver Install] Opened temp file 'C:\Users\deng\AppData\Local\Temp\2\2019221-1936-1huogvw.no7ui\chromedriver_win32.zip'
[17:47:56] [Chromedriver Install] Downloading https://chromedriver.storage.googleapis.com/2.46/chromedriver_win32.zip...
RequestError: Error: connect ETIMEDOUT 172.217.164.144:443
    at new RequestError (c:\node-v10.15.3-win-x64\node_modules\appium\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (c:\node-v10.15.3-win-x64\node_modules\appium\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (c:\node-v10.15.3-win-x64\node_modules\appium\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (c:\node-v10.15.3-win-x64\node_modules\appium\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.onRequestError (c:\node-v10.15.3-win-x64\node_modules\appium\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.1 (node_modules\appium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@4.11.0 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@4.11.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\deng\AppData\Roaming\npm-cache\_logs\2019-03-22T00_49_07_467Z-debug.log

c:\node-v10.15.3-win-x64>
```

## Environment

* Appium version: the latest one that npm installs
* Last Appium version that did not exhibit the issue (if applicable): unsure
* Desktop OS/version used to run Appium:  Win 7
* Node.js version (unless using Appium.app|exe): 10.15.3
* Npm or Yarn package manager: NPM 6.4.1
* Mobile platform/version under test: Appium
* Real device or emulator/simulator: unsure
* Appium CLI or Appium.app|exe: unsure

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
1. Open CMD
2, execute command: npm install -g appium

**Comment by dpgraham** [comment] 2019-03-22 15:44
This is probably a network issue. What happens if you try downloading https://chromedriver.storage.googleapis.com/2.46/chromedriver_win32.zip directly?

**Comment by DavidEngNJ** [comment] 2019-03-22 16:00
It downloads to my download folder.

**Comment by dpgraham** [comment] 2019-03-22 16:29
Are you behind a firewall?

**Comment by dpgraham** [comment] 2019-03-22 16:30
https://stackoverflow.com/questions/33350604/what-could-cause-connect-etimedout-error-when-the-url-is-working-in-browser

**Comment by DavidEngNJ** [comment] 2019-03-22 16:42
I am behind a firewall.  But, I was able to "npm install ws" (the client to Appium).  I followed the example in:
https://jjasonclark.com/how-to-setup-node-behind-web-proxy/

**Comment by DavidEngNJ** [comment] 2019-03-22 16:43
I am not a developer.  QA guy trying to npm install package.

**Comment by mykola-mokhnach** [comment] 2019-03-22 18:36
[developer!](https://imgflip.com/i/2wpfjx)

**Comment by mykola-mokhnach** [comment] 2019-03-22 18:42
Appium installer does not use proxies for chrome download. This is known.

**Comment by mykola-mokhnach** [comment] 2019-03-22 18:45
Possible duplicate of https://github.com/appium/appium/issues/7163

**Comment by DavidEngNJ** [comment] 2019-03-22 19:10
Hi Mykola.  I tried the suggestions in #7163 but still get the same error messages shown in my original post.  The thing is, I'm pretty sure my proxy is configured correctly as suggested in https://jjasonclark.com/how-to-setup-node-behind-web-proxy/.  And, I was able to "npm install <package>" for another package other than Appium.  So, I don't understand why only Appium cannot get past the chromedriver installation part.

npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080

**Comment by mykola-mokhnach** [comment] 2019-03-22 19:23
> So, I don't understand why only Appium cannot get past the chromedriver installation part.

Because this is not supported like I said above. You're welcome to implement such functionality yourself

**Comment by DavidEngNJ** [comment] 2019-03-22 19:30
So, I cannot use "npm install -g appium"?

**Comment by mykola-mokhnach** [comment] 2019-03-22 19:32
Not behind a proxy. Although, you can still apply a workaround by putting the chromedrriver downloaded from a browser to some local http server and pointing appium to that URL.

**Comment by DavidEngNJ** [comment] 2019-03-22 19:59
Can I just downloaded / install from http://appium.io/?  Is this the same as doing it via "npm install -g appium"?   Sorry for these newbie questions.

**Comment by dpgraham** [comment] 2019-03-22 20:08
@DavidEngNJ you can download Appium Desktop from http://appium.io... it's a GUI with Appium bundled in it.

**Comment by DavidEngNJ** [comment] 2019-03-22 20:10
Thanks @dpgraham @mykola-mokhnach

**Comment by dpgraham** [comment] 2019-03-22 20:28
You're welcome! I'm going to close this ticket. Any more questions I'd recommend discuss.appium.io

**Closed by dpgraham** 2019-03-22 20:28 UTC
Labels: NeedsInfo, NotABug

**Comment by juditraj** [comment] 2019-05-16 06:57
Set the proxy from console where you are running the command
set HTTP_PROXY=http://user:password@proxy.domain.com:port
set HTTPS_PROXY=http://user:password@proxy.domain.com:port

It should work.
Note: so proxy setup is in two places. 
1. Inside npmrc file
2. Set from command line.

**Comment by abhinavgoyal02** [comment] 2019-06-04 03:17
@juditraj
Your analysis was right about proxy setup in 2 places.
Worked exactly how it is supposed to. 
Thanks a lot.
