### ISSUE TITLE
Unable to inspect React native iOS app elements using appium inspector

### ISSUE THREAD

**Issue by shreyapz** [appium/appium#14784] opened 2020-10-05 09:59 UTC
## The problem

I am trying to locate the below highlighted meeting information. However in Appium desktop inspector all the elements are combined and shown in a single container. 
Three elements highlighted in red has different test id's but when I try to inspect it shows all three as one element. Hence I am not able to interact with any specific element on iOS.
I can inspect the same three elements as different elements in android app. It works fine for android.
p.s - I have also tried to inspect elements using accessibility inspector. the result is the same.

## Environment

* Appium desktop version- 1.18.0-2
* Desktop OS/version used to run Appium: MAC Catalina 10.15.6
* Mobile platform/version under test: iOS 13.6, 13.7, 14.0.1 
* Real device or emulator/simulator: Real device and emulator

## Link to Appium logs

https://gist.github.com/shreyapz/b7734442fd59a4c5e9728be609160021

![Screenshot 2020-10-05 at 11 22 31](https://user-images.githubusercontent.com/41265615/95065946-ffa07680-0701-11eb-9a2d-53d17d244fd4.png)

**Comment by mykola-mokhnach** [comment] 2020-10-05 10:01
Duplicate of https://github.com/appium/appium/issues/6517

**Closed by mykola-mokhnach** 2020-10-05 10:01 UTC
