### ISSUE TITLE
newer UiAutomation versions allow execution of adb shell methods

### ISSUE THREAD

**Issue by jlipps** [appium/appium#4943] opened 2015-04-16 22:02 UTC
Which suggests that on these platforms we should allow uiautomator itself to do it. It should be faster and less flakey then running `adb shell` via `exec` from appium.

**Comment by jlipps** [comment] 2015-04-16 22:02
(originally discussed in #4449)

**Comment by bootstraponline** [comment] 2015-04-16 22:10
Updated the title. UiAutomation != uiautomator

This is relevant because if we use a different backend (ex: droiddriver), we can still benefit from this feature. That wouldn't be the case if it was in uiautomator.

**Comment by bootstraponline** [comment] 2015-04-16 22:17
I think this is a dupe of #2977?

**Comment by jlipps** [comment] 2015-04-16 22:18
i think this issue is specifically about adding code to appium which, based on api level, sends adb commands to the android automation backend vs calling out to shell from the appium js code

**Comment by bootstraponline** [comment] 2015-04-16 22:27
:+1:

**Comment by ShiranDadon** [comment] 2015-06-08 17:19
Hi, saw there is a new version - is it in?
If not - do you have a due date for it? Thanks!

**Comment by jlipps** [comment] 2015-06-08 21:04
no, there is no ETA for this feature as of yet

**Comment by mykola-mokhnach** [comment] 2019-08-08 12:07
I did some testing on this topic before and can say this feature only  reliably works since Android 6, however UiAutomator2 is supposed to support Android 5 as well. Adding more conditions into the code will make it overcomplicated and harder to support.

Also, I would be happy to review some concrete proposals, like which endpoints are not very effective from the performance perspective and should be optimised. The current feature description is too broad.

**Closed by mykola-mokhnach** 2019-08-08 12:07 UTC
Labels: Android, Enhancement, P2
