### ISSUE TITLE
Unable to locate certain xcuitest elements when using simulator build

### ISSUE THREAD

**Issue by denisha** [appium/appium#8780] opened 2017-07-05 11:43 UTC
## The problem
I have built an .app for use on iOS simulator on appium. My tests fail because they are unable to locate specific  xcuitest elements which are missing from a collection view. If i build an .ipa for real device, then the collection view loads these xcuitest elements.
 
 
## Environment
 
* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Mac OS 10.12.1 
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.3 (also tried 9.3)
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app() but also broken on Saucelabs simulators 
 
## Details
 
I have done a comparison of the app source code on the simulator app vs the .ipa real device app and found that there are collection views missing see https://www.diffchecker.com/PF4y3OhU
I have built the simulator app via the following command: e.g.
`xcodebuild -workspace '/Users/.../apps_ios/<app>.xcworkspace' -scheme 'dev' -arch x86_64  -sdk iphonesimulator10.3`
I am trying to locate the ‘Sort’ and ‘Filter’ buttons as per screenshots attached
 
If necessary, describe the problem you have been experiencing in more detail.
 
## Link to Appium logs

https://gist.github.com/denisha/9d1f3cf1c18fe1ebabb7351faa8b58b5
 
**Simulator build:** 
![simulatorapp](https://user-images.githubusercontent.com/1721580/27862852-a6dce43e-6187-11e7-8874-b36d00152b9b.png)
**Real device build:** 
Here I am able to inspect the sort button
![realdeviceipa](https://user-images.githubusercontent.com/1721580/27862851-a6cc342c-6187-11e7-8a54-55473b45452c.png)

**Comment by mykola-mokhnach** [comment] 2017-07-05 11:52
Might be a duplicate of https://github.com/appium/appium/issues/6517

**Closed** 2017-07-11 06:53 UTC
Labels: ThirdpartyIssue, XCUITest
