### ISSUE TITLE
Time Out when loading the page with many data on iOS Simulator 15.2

### ISSUE THREAD

**Issue by mochitest** [appium/appium#16379] opened 2022-01-26 22:46 UTC
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

Appium version (or git revision) that exhibits the issue: Appium v1.23.0-beta.0
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: macOS Big Sur 11.6
Node.js version (unless using Appium.app|exe): v16.13.0
Npm or Yarn package manager: 0.37.2
Mobile platform/version under test: iOS 15.2
Real device or emulator/simulator: iPhone 8 simulator

## Details

A page has lots of data, when using appium to find the page element, it gets time out and page froze.
Appium is not able to interact with the application any more.

## Link to Appium logs

[Xcode]     "XC_kAXXCAttributeIsElement"
[Xcode] ). Original error: Error Domain=com.apple.dt.xctest.automation-support.error Code=11 "Accessibility error kAXErrorInvalidUIElement from AXUIElementCopyMultipleAttributeValues for 2016" UserInfo={accessibility-error=-25202, NSLocalizedDescription=Accessibility error kAXErrorInvalidUIElement from AXUIElementCopyMultipleAttributeValues for 2016}
[Xcode] 2022-01-26 17:35:56.016717-0500 WebDriverAgentRunner-Runner[85190:1928901] Cannot retrieve element attribute(s) (

Calling AppiumDriver.getTimeouts() with args: ["8799fb8f-f79a-44cc-9b28-9a63efe2b832"]
[debug] [XCUITest] Executing command 'getTimeouts'
[WD Proxy] Got response with status 404: {"value":{"error":"stale element reference","message":"The previously found element \"Application " is not present in the current view anymore. Make sure the application UI has the expected state. Original error: Unable to perform work on main run loop, process main thread busy for 30.0s","traceback":"(\n\t0   CoreFoundation                      0x00007fff203feba4 __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007fff201a1be7 objc_exception_throw + 48\n\t2   WebDriverAgentLib                   0x0000000102471f36 -[XCUIElement(FBUtilities) fb_takeSnapshot] + 886\n\t3   WebDriverAgentLib                   0x0000000102469024 -[XCUIElement(WebDriverAttributesForwarding) fb_snapshotForAttributeName:] + 756\n\t4   WebDriverAgentLib                   0x0000000102469205 -[XCUIElement(WebDriverAttributesForwarding) forwardingTargetForSelector:] + 149\n\t5   CoreFoundation                      0x00007fff20402bfb ___forwarding___ + 232\n\t6   CoreFoundati...
[debug] [W3C] Matched W3C error code 'stale element reference' to StaleElementReferenceError

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment] 2022-01-27 02:12
It seems the error is by XCTest internal to get the element snapshot. Possibly you could report it to Apple.

**Comment by KazuCocoa** [comment] 2022-01-27 19:25
Thank you for the confirmation.

Then, yes, perhaps appium can work.
Could you share the appium log?

The error itself is by XCTest, but I assume it is avoidable by tuning Appium query.
e.g. with `useFirstMatch` https://github.com/appium/appium-xcuitest-driver#settings-api , timing issue etc

**Comment by mochitest** [comment] 2022-01-27 21:30
022-01-26 23:37:25:147 [W3C (2d4a84e2)] Responding to client with driver.findElements() result: []
2022-01-26 23:37:25:151 [HTTP] <-- POST /wd/hub/session/2d4a84e2-4f1a-4def-b4d5-d920ca1dae05/elements 200 60217 ms - 12
2022-01-26 23:37:25:151 [HTTP] 
2022-01-26 23:37:25:164 [HTTP] --> POST /wd/hub/session/2d4a84e2-4f1a-4def-b4d5-d920ca1dae05/timeouts
2022-01-26 23:37:25:164 [HTTP] {"implicit":60000}
2022-01-26 23:37:25:165 [W3C (2d4a84e2)] Calling AppiumDriver.timeouts() with args: [null,null,null,null,60000,"2d4a84e2-4f1a-4def-b4d5-d920ca1dae05"]
2022-01-26 23:37:25:165 [XCUITest] Executing command 'timeouts'
2022-01-26 23:37:25:165 [BaseDriver] W3C timeout argument: {"implicit":60000}}
2022-01-26 23:37:25:165 [BaseDriver] Set implicit wait to 60000ms
2022-01-26 23:37:25:185 [W3C (2d4a84e2)] Responding to client with driver.timeouts() result: null
2022-01-26 23:37:25:187 [HTTP] <-- POST /wd/hub/session/2d4a84e2-4f1a-4def-b4d5-d920ca1dae05/timeouts 200 21 ms - 14
2022-01-26 23:37:25:187 [HTTP] 
2022-01-26 23:37:25:202 [HTTP] --> POST /wd/hub/session/2d4a84e2-4f1a-4def-b4d5-d920ca1dae05/timeouts
2022-01-26 23:37:25:202 [HTTP] {"implicit":60000}
2022-01-26 23:37:25:203 [W3C (2d4a84e2)] Calling AppiumDriver.timeouts() with args: [null,null,null,null,60000,"2d4a84e2-4f1a-4def-b4d5-d920ca1dae05"]
2022-01-26 23:37:25:203 [XCUITest] Executing command 'timeouts'
2022-01-26 23:37:25:203 [BaseDriver] W3C timeout argument: {"implicit":60000}}
2022-01-26 23:37:25:203 [BaseDriver] Set implicit wait to 60000ms
2022-01-26 23:37:25:204 [W3C (2d4a84e2)] Responding to client with driver.timeouts() result: null
2022-01-26 23:37:25:205 [HTTP] <-- POST /wd/hub/session/2d4a84e2-4f1a-4def-b4d5-d920ca1dae05/timeouts 200 2 ms - 14
2022-01-26 23:37:25:205 [HTTP] 
2022-01-26 23:37:25:209 [HTTP] --> POST /wd/hub/session/2d4a84e2-4f1a-4def-b4d5-d920ca1dae05/execute/sync
2022-01-26 23:37:25:209 [HTTP] {"script":"mobile: source","args":[{"format":"xml","excludedAttributes":"visible"}]}
2022-01-26 23:37:25:210 [W3C (2d4a84e2)] Calling AppiumDriver.execute() with args: ["mobile: source",[{"format":"xml","excludedAttributes":"visible"}],"2d4a84e2-4f1a-4def-b4d5-d920ca1dae05"]
2022-01-26 23:37:25:210 [XCUITest] Executing command 'execute'
2022-01-26 23:37:25:214 [WD Proxy] Matched '/source?format=xml&scope=AppiumAUT&excluded_attributes=visible' to command name 'getPageSource'
2022-01-26 23:37:25:215 [WD Proxy] Proxying [GET /source?format=xml&scope=AppiumAUT&excluded_attributes=visible] to [GET http://127.0.0.1:6194/session/9A57A74C-09AA-437F-8C62-8FA6FF43DC06/source?format=xml&scope=AppiumAUT&excluded_attributes=visible] with no body
2022-01-26 23:38:25:269 [WD Proxy] Got response with status 404: {"value":{"error":"stale element reference","message":"The previously found element \"Application 'APPLICATION'\" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: XCTPerformOnMainRunLoop work timed out after 60.0s","traceback":"(\n\t0   CoreFoundation                      0x0000000100b1fba4 __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x000000010083abe7 objc_exception_throw + 48\n\t2   WebDriverAgentLib                   0x0000000123f5df36 -[XCUIElement(FBUtilities) fb_takeSnapshot] + 886\n\t3   WebDriverAgentLib                   0x0000000123f5e1e7 -[XCUIElement(FBUtilities) fb_snapshotWithAttributes:maxDepth:] + 183\n\t4   WebDriverAgentLib                   0x0000000123f0fae9 +[FBXPath writeXmlWithRootElement:indexPath:elementStore:includedAttributes:writer:] + 777\n\t5   WebDriverAgentLib                   0x0000000123f0f18b +[FBXPath xmlRepresentationWithRootElement:writer:elementStore:query...
2022-01-26 23:38:25:287 [W3C] Matched W3C error code 'stale element reference' to StaleElementReferenceError
2022-01-26 23:38:25:291 [W3C (2d4a84e2)] Encountered internal error running command: StaleElementReferenceError: The previously found element "Application 'APPLICATION'" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: XCTPerformOnMainRunLoop work timed out after 60.0s
2022-01-26 23:38:25:291 [W3C (2d4a84e2)]     at errorFromW3CJsonCode (/home/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
2022-01-26 23:38:25:291 [W3C (2d4a84e2)]     at ProxyRequestError.getActualError (/home/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
2022-01-26 23:38:25:291 [W3C (2d4a84e2)]     at JWProxy.command (/home/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:272:19)
2022-01-26 23:38:25:291 [W3C (2d4a84e2)]     at runMicrotasks (<anonymous>)
2022-01-26 23:38:25:292 [W3C (2d4a84e2)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2022-01-26 23:38:25:292 [W3C (2d4a84e2)]     at XCUITestDriver.proxyCommand (/home/appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)
2022-01-26 23:38:25:292 [W3C (2d4a84e2)]     at XCUITestDriver.mobileGetSource (/home/appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:51:10)
2022-01-26 23:38:25:292 [W3C (2d4a84e2)]     at XCUITestDriver.executeMobile (/home/appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:158:10)
2022-01-26 23:38:25:292 [W3C (2d4a84e2)]     at XCUITestDriver.execute (/home/appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:32:12)
2022-01-26 23:38:25:312 [HTTP] <-- POST /wd/hub/session/2d4a84e2-4f1a-4def-b4d5-d920ca1dae05/execute/sync 404 60083 ms - 1562

**Comment by mykola-mokhnach** [comment] 2022-01-27 21:34
> Original error: XCTPerformOnMainRunLoop work timed out after 60.0s

It is clearly visible the error is caused by XCTest.

**Comment by mykola-mokhnach** [comment] 2022-01-29 14:01
Closed as third party issue

**Closed by mykola-mokhnach** 2022-01-29 14:01 UTC
Labels: ThirdParty, XCUITest
