### ISSUE TITLE
method getAttribute() return null

### ISSUE THREAD

**Issue by Phoenix124** [appium/appium#13418] opened 2019-10-14 10:14 UTC
## The problem

Try to get attribute `value` - but get **null** 
```
lastMessage.getAttribute("value")
@iOSXCUITFindBy(xpath = "(//XCUIElementTypeTextView[@name='messageTextViewId'])[last()]")
private IOSElement lastMessage;
```

## Environment

* Appium version - 1.15
* npm version - 6.11.2
* node version - 10.15.3  
* iOS version - 12.0

## Details

```
<XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="21" y="500" width="228" height="20">
    <XCUIElementTypeTextView type="XCUIElementTypeTextView" enabled="true" visible="true" x="21" y="500" width="228" height="20" name="messageTextViewId" value="From_iostest_knqsErFRBK">
     </XCUIElementTypeTextView>
</XCUIElementTypeOther>
```

## Link to Appium logs

```
[debug] [MJSONWP (8a81277e)] Calling AppiumDriver.getAttribute() with args: ["value","DB0F0000-0000-0000-AD45-010000000000","8a81277e-33f7-4f14-b075-210bf3b2fcf0"]
[debug] [XCUITest] Executing command 'getAttribute'
[debug] [WD Proxy] Matched '/element/DB0F0000-0000-0000-AD45-010000000000/attribute/value' to command name 'getAttribute'
[debug] [WD Proxy] Proxying [GET /element/DB0F0000-0000-0000-AD45-010000000000/attribute/value] to [GET http://localhost:8105/session/944BD0D8-E262-42B8-9BBF-88C84E750208/element/DB0F0000-0000-0000-AD45-010000000000/attribute/value] with no body
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : null,
[debug] [WD Proxy]   "sessionId" : "944BD0D8-E262-42B8-9BBF-88C84E750208"
[debug] [WD Proxy] }
```

**Comment by mykola-mokhnach** [comment] 2019-10-14 10:34
Duplicate of https://github.com/appium/appium/issues/13288

**Closed by mykola-mokhnach** 2019-10-14 10:34 UTC

**Comment by Phoenix124** [comment] 2019-10-14 10:43
@mykola-mokhnach 
but on the iOS 13 it's work correctly

**Comment by mykola-mokhnach** [comment] 2019-10-14 10:48
Unfortunately such value is returned by XCTest itself. There's nothing we can do about it
