### ISSUE TITLE
Encountered internal error running command: Error: Installing 

### ISSUE THREAD

**Issue by shreyasdraut** [appium/appium#6914] opened 2016-09-29 16:55 UTC
## The problem

I am not able to run automation on iOS devices. 
Encountered internal error running command: Error: Installing 
## Environment

I am running on iOS 9.3.5 on iPhone 6plus and iPhone 6
on Appium 1.5.3
## Details

[MJSONWP] Encountered internal error running command: Error: Installing /var/folders/js/hjtj7md91px0prd9v7s881fm7627_4/T/2016829-6512-wj6pnt/Payload/MBOMobile.app failed
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)

**Comment by mykola-mokhnach** [comment] 2016-10-02 16:11
Make sure your application is signed with developer signature and can be installed manually using _ideviceinstaller_ command line tool.

**Comment by imurchie** [comment] 2016-10-03 11:38
Can you provide more of the logs? Preferably _all_ of them?

**Comment by bharath99notout** [comment] 2016-10-06 19:19
[MJSONWP] Encountered internal error running command: Error: Installing /var/folders/75/cvmyjw9s7wzfx3dl5fyz9vs40000gp/T/201697-6681-152s83v/Payload/Medlife.app failed
    at /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[HTTP] <-- POST /wd/hub/session 500 2129 ms - 243 
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 13 ms - 121 
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 10 ms - 121 
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 11 ms - 121 
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 15 ms - 121 
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 2 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","newCommandTimeout":"7200","app":"/Users/bhkuma/Documents/Bharath/web-automation/web-test-automation/src/test/java/com/medlife/customerapp/apps/Medlife12.ipa","platformVersion":"9.3.4","deviceName":"Iphone","bundleId":"com.medlife.gorx.customer","automationName":"Appium","udid":"f9115d7e5bc714a161b348536f28b8c3f7dd9fb4"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","new...
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   newCommandTimeout: '7200'
[Appium]   app: '/Users/bhkuma/Documents/Bharath/web-automation/web-test-automation/src/test/java/com/medlife/customerapp/apps/Medlife12.ipa'
[Appium]   platformVersion: '9.3.4'
[Appium]   deviceName: 'Iphone'
[Appium]   bundleId: 'com.medlife.gorx.customer'
[Appium]   automationName: 'Appium'
[Appium]   udid: 'f9115d7e5bc714a161b348536f28b8c3f7dd9fb4'
[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior
[BaseDriver] Session created with session id: d2c9f245-b118-4e24-9ec4-812c34c8db6a
[debug] [iOS] Not auto-detecting udid.
[BaseDriver] Using local app '/Users/bhkuma/Documents/Bharath/web-automation/web-test-automation/src/test/java/com/medlife/customerapp/apps/Medlife12.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/75/cvmyjw9s7wzfx3dl5fyz9vs40000gp/T/201697-6681-1i3qs53/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/75/cvmyjw9s7wzfx3dl5fyz9vs40000gp/T/201697-6681-1i3qs53/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/75/cvmyjw9s7wzfx3dl5fyz9vs40000gp/T/201697-6681-1i3qs53/Payload/Medlife.app'
[debug] [iOS] Removing any remaining instruments sockets
[debug] [iOS] Cleaned up instruments socket /var/folders/75/cvmyjw9s7wzfx3dl5fyz9vs40000gp/T/instruments_sock
[debug] [iOS] No language specified. Using default strings
[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
[iOS] Could not file localizable strings file 'Localizable.strings'!
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/bhkuma/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/75/cvmyjw9s7wzfx3dl5fyz9vs40000gp/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
...bug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
[debug] [UIAuto] Dynamic bootstrap path: /Users/bhkuma/Library/Application Support/appium/bootstrap/bootstrap-9861303b5d17cad3.js
[debug] [UIAuto] Reusing dynamic bootstrap: /Users/bhkuma/Library/Application Support/appium/bootstrap/bootstrap-9861303b5d17cad3.js
[debug] [iOS] Running ios real device reset flow
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [iOS] Creating iDevice object with udid f9115d7e5bc714a161b348536f28b8c3f7dd9fb4
[debug] [iOS] App is not installed. Will try to install.
[MJSONWP] Encountered internal error running command: Error: Installing /var/folders/75/cvmyjw9s7wzfx3dl5fyz9vs40000gp/T/201697-6681-1i3qs53/Payload/Medlife.app failed
    at /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[HTTP] <-- POST /wd/hub/session 500 1496 ms - 243 
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 12 ms - 121

**Comment by bharath99notout** [comment] 2016-10-06 19:21
i am not able to open IPA file in real device through. I updated xocde 8.0 then downgraded to 7.3.1.
Appium : 1.5.3.

Please help

**Comment by shreyasdraut** [comment] 2016-10-06 19:49
what was the error?

**Comment by shreyasdraut** [comment] 2016-10-06 19:53
try to run this command on terminal
sudo chmod 777 /var/db/lockdown

there is some iTunes issue that causes the error.

**Comment by huig1149** [comment] 2016-10-20 02:12
@shreyasdraut  I solve this problem.
Get the latest libimobiledevice, which has a fix for this particular issue:
open the terminal, type the commands below:

1. brew uninstall ideviceinstaller 
2. brew uninstall libimobiledevice 
3. brew install --HEAD libimobiledevice 
4. brew link --overwrite libimobiledevice 
5. brew install ideviceinstaller 
6. brew link --overwrite ideviceinstaller

If you hava not installed the homebrew, it will not work. Try this:
[https://github.com/Homebrew/brew/blob/master/docs/Installation.md]

**Comment by zhuchuji** [comment] 2016-12-01 07:22
@shreyasdraut I solved the problem with your suggestion. But why? Is it because iTunes issue as you said?

**Closed** 2017-01-31 19:19 UTC
Labels: NeedsTriage
