### ISSUE TITLE
Appium server freeze on onePlus6T device

### ISSUE THREAD

**Issue by Gopihegde** [appium/appium#12313] opened 2019-03-15 10:29 UTC
## The problem

Appium Server execution stops in between and it freezes

## Environment
Appium 1.11.1

## Details
[HTTP] 
[HTTP] --> POST /wd/hub/session/67959962-03a6-4698-b73e-648a7b2ac738/element
[HTTP] {"using":"id","value":"forgotPasswordSubmitBtn"}
[W3C (67959962)] Calling AppiumDriver.findElement() with args: ["id","forgotPasswordSubmitBtn","67959962-03a6-4698-b73e-648a7b2ac738"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 30000 ms for condition
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/1461916e-6053-42c7-aa21-17c6879b1772/element] with body: {"strategy":"id","selector":"forgotPasswordSubmitBtn","context":"","multiple":false}
[WD Proxy] Got an unexpected response: {"code":"ESOCKETTIMEDOUT","connect":false}
[W3C (67959962)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
[W3C (67959962)]     at JWProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:236:13)
[HTTP] <-- POST /wd/hub/session/67959962-03a6-4698-b73e-648a7b2ac738/element 500 240169 ms - 565

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
https://gist.github.com/Gopihegde/50d8609b19494b9a62104d3b26530f75

**Comment by Raymio** [comment] 2019-03-15 13:45
Faced this problem today as well but I managed to fix it by updating SDK and restarting Appium

**Comment by Gopihegde** [comment] 2019-03-15 13:50
Hey Raymio

Which sdk version are you using?

**Comment by mykola-mokhnach** [comment] 2019-03-15 14:20
Possible duplicate of https://github.com/appium/appium/issues/12217. Try to avoid using `launchApp`

**Comment by Gopihegde** [comment] 2019-03-15 14:27
Let me try with activate app/terminate app . Btw what would be causing this problem in certain devices.same code works very well with NOKIA 6.1 PLUS and Samsung with OS 9.

**Comment by Gopihegde** [comment] 2019-03-19 06:02
@mykola-mokhnach activateApp and Terminate App does not help.  Appium Server continue to freeze.

**Comment by mykola-mokhnach** [comment] 2019-03-20 10:14
Logs please

**Comment by Gopihegde** [comment] 2019-03-20 10:53
https://gist.github.com/Gopihegde/50d8609b19494b9a62104d3b26530f75

**Comment by mykola-mokhnach** [comment] 2019-03-20 14:32
I don't see anything is changed in the log. `launchApp` is still used there:

> [W3C (67959962)] Calling AppiumDriver.launchApp() with args: ["67959962-03a6-4698-b73e-648a7b2ac738"]

**Comment by Gopihegde** [comment] 2019-03-21 10:36
Hi mykola,

i faced issue without launch app / close app. Scroll up/Down also caused the same.

Logs are updated in the same link.

Thank you

**Comment by mykola-mokhnach** [comment] 2019-03-21 12:31
What's in the logical output after

> 2019-03-21 15:58:01.829 19148-19172/io.appium.uiautomator2.server I/appium: JSON Payload : {"startX":490,"startY":414,"endX":490,"endY":1659,"steps":56}

Are there any exceptions/warnings?

**Comment by Gopihegde** [comment] 2019-03-21 12:34
got SOCKETTIMEDOUT.. expected is it should scroll Up. No response from the server.

**Comment by mykola-mokhnach** [comment] 2019-03-21 12:43
`SOCKETTIMEDOUT` means that there might networking issues or problems with the device itself. It is important to know in what state the server is. You could also try to perform W3C actions as a workaround: https://appiumpro.com/editions/29

**Comment by Gopihegde** [comment] 2019-03-22 06:36
Thanks. Device side socket was closing on port 6790. i restarted it manually . worked fine..Dont know what is wrong with device.

**Comment by mykola-mokhnach** [comment] 2019-03-22 06:49
There might be many problems, for example overheating or problems with the firmware, which has anyway has nothing to do with Appium.

Closing as third party issue

**Closed by mykola-mokhnach** 2019-03-22 06:49 UTC
Labels: NeedsInfo, UIAutomator2
