### ISSUE TITLE
TypeError: Invalid Version: android-4.4W     at new SemVer 

### ISSUE THREAD

**Issue by jiemachina** [appium/appium#10068] opened 2018-01-25 03:29 UTC
## The problem

[Appium] Welcome to Appium v1.7.2
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"requiredCapabilities":{},"desiredCapabilities":{"deviceName":"MI 3","app":"/Users/majie/Desktop/测试数据/邮箱SDK.apk","noReset":true,"platformVersion":"5.1","appPackage":"com.u51.android.mail","platformName":"Android","appActivity":"com.u51.android.MainActivity"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"MI 3","app":"/Users/majie/Desktop/测试数据/邮箱SDK.apk","noReset":true,"platformVersion":"5.1","appPackage":"com.u51.android.mail","platformName":"Android","appActivity":"com.u51.android.MainActivity"},{},null]
[BaseDriver] Event 'newSessionRequested' logged at 1516850631561 (11:23:51 GMT+0800 (CST))
[Appium] Creating new AndroidDriver (v1.37.0) session
[Appium] Capabilities:
[Appium]   deviceName: MI 3
[Appium]   app: /Users/majie/Desktop/测试数据/邮箱SDK.apk
[Appium]   noReset: true
[Appium]   platformVersion: 5.1
[Appium]   appPackage: com.u51.android.mail
[Appium]   platformName: Android
[Appium]   appActivity: com.u51.android.MainActivity
[BaseDriver] Session created with session id: 55f09ad9-ba73-4ce6-abfe-595cc5a5c39f
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_91
[ADB] Checking whether adb is present
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[MJSONWP] Encountered internal error running command: TypeError: Invalid Version: android-4.4W
    at new SemVer (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/semver/semver.js:293:11)
    at compare (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/semver/semver.js:566:10)
    at rcompare (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/semver/semver.js:576:10)
    at Array.sort (native)
    at Array.sort (/Applications/Appium.app/Contents/Resources/app/webpack:/~/babel-polyfill/~/core-js/modules/es6.array.sort.js:21:1)
    at ADB.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:89:17)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at 

## Environment

*  Appium v1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac 
* Node.js version (unless using Appium.app|exe): v7.7.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device 
* Appium CLI or Appium.app|exe: Appium.app

**Comment by mykola-mokhnach** [comment] 2018-01-25 06:43
Duplicate of https://github.com/appium/appium/issues/9926

**Closed by mykola-mokhnach** 2018-01-25 06:43 UTC
