### ISSUE TITLE
[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun' not found. Is it installed?

### ISSUE THREAD

**Issue by keshavwy** [appium/appium#9454] opened 2017-10-13 14:56 UTC
## The problem

Not able to use xcrun even though it is installed.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Mobile platform/version under test: iOS (10.3.3)
* Real device or emulator/simulator:iphone (real device)
* Appium CLI or Appium.app|exe:

## Details

Whenever I try to run my code using testng.Xml, I am hitting the above-mentioned error. If I run the test cases separately it works fine. 

## Link to Appium logs

Here is a link: https://gist.github.com/keshavwy/d7beaa9e85e156ad0f5c3cf252e74019#file-gistfile1-txt

**Comment by imurchie** [comment] 2017-10-13 15:08
Seems like it is probably that your PATH is not available to whatever is running `testng.xml`. I have no idea how to make it available, though.

**Comment by mykola-mokhnach** [comment] 2017-10-13 15:51
Duplicate of https://github.com/appium/appium/issues/6743

**Closed by mykola-mokhnach** 2017-10-13 15:51 UTC
Labels: NotABug, XCUITest
