### ISSUE TITLE
sendKeys is not working (iOS)

### ISSUE THREAD

**Issue by otaviolandim** [appium/appium#11240] opened 2018-08-23 16:50 UTC
## The problem

I'm facing a related problem when I try to invoke sendKeys() on an input. Visually the input gets the value I send, but the input's onChange isn't fired. For instance, my input is a search input; whenever my test tries to search something, the search input is updated, by the list is still the same.

## Environment

* Appium version (or git revision) that exhibits the issue: n/a
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: n/a
* Node.js version (unless using Appium.app|exe): v8.11.3
* Mobile platform/version under test: 11.4
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: n/a

**Comment by mykola-mokhnach** [comment] 2018-08-23 17:03
Is the input field inside react webview? This might be a duplicate of 
https://github.com/appium/appium/issues/9753

**Closed** 2018-08-26 16:14 UTC
Labels: NeedsInfo
