### ISSUE TITLE
Get error when use input text method while set automationName to UIAutomator2

### ISSUE THREAD

**Issue by shenjianyun** [appium/appium#12986] opened 2019-07-29 09:02 UTC
## Environment

* Appium version (or git revision) that exhibits the issue: appium-desktop 1.12.1; robotframework 3.1.2; robotframework-appiumlibrary 1.5.0.4 
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac os 10.14.5
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: SM-N9100(android 6.0.1)
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

in the screenshot:
![image](https://user-images.githubusercontent.com/48910607/62032816-32f19680-b21d-11e9-99cb-c945233fabf7.png)
The edit text with the same layout, i want to modify the phone
1. Desired capabilities automation name with default, appium will set automationName to UiAutomator1, clear text work well with all edit text(ex nickname, first name and last name) work well except phone number
2. Then i set automationName to UiAutomator2, then clear work well for phone number too! the next problem is can't input text in phone text edit

so, my problem is can't use input text with UiAutomator2

## Link to Appium logs

GIST for the appium server log for the UiAutomator2 case with the bug 

https://gist.github.com/shenjianyun/741f49d728caa83357f2d8c18887079b

## Code To Reproduce Issue [ Good To Have ]

I use robot framework-ride with Appium library, here is the script:
Input Phone in Profile Setting Page
    [Arguments]    ${phone}
    Wait Until Element Is Visible    id=xx.dev:id/phoneEditText
    Clear Text    id=xx.dev:id/phoneEditText
    Input Text    id=xx.dev:id/phoneEditText    ${phone}
    Run Keyword If    '${PLATFORM}'=='ios'    Click Element    nsp=name=="Done"

**Comment by mykola-mokhnach** [comment] 2019-07-29 10:46
Possible duplicate of https://github.com/appium/appium/issues/12026 or https://github.com/appium/appium/issues/12271

UIA1 uses a special adb hack to enter keys and UIA2 uses the clean approach with native typeText helper, which is also sensitive to the element selection.

**Comment by shenjianyun** [comment] 2019-07-30 02:35
@mykola-mokhnach , ok, got it, thanks your replay

**Comment by mykola-mokhnach** [comment] 2019-08-01 11:08
Closed as not an issue

**Closed by mykola-mokhnach** 2019-08-01 11:08 UTC
Labels: NotABug, UIAutomator2
