### ISSUE TITLE
WebDriverAgent.xcodeproj Building for iOS, but the embedded framework 'YYCache.framework' was built for iOS + iOS Simulator.

### ISSUE THREAD

**Issue by chenchengyuan** [appium/appium#14952] opened 2020-12-16 08:28 UTC
## The problem

Xcode 12.3 build WDA for iPhone failed.
Failed log: Building for iOS, but the embedded framework 'YYCache.framework' and  'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

![1234.png](https://i.loli.net/2020/12/16/1drtcPS4AExUZlv.png)

**Comment by KazuCocoa** [comment] 2020-12-16 08:33
Duplicate of https://github.com/appium/appium/issues/14951

**Closed by KazuCocoa** 2020-12-16 08:33 UTC

**Comment by KazuCocoa** [comment] 2020-12-16 08:53
note: `appium@beta` has the fix. (appium-webdriveragent module should be `2.32.0`)

**Comment by chenchengyuan** [comment] 2020-12-16 10:51
I clone the wda master branch , then build wda succeed, copy it to appium/node_modules/appium-webdriveragent, but run case failed with another exception. 
node 12 also failed

```
[debug] [Appium] /Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/node_modules/appium-webdriveragent/index.js:1
[debug] [Appium] import * as dependencies from './lib/check-dependencies';
[debug] [Appium] ^^^^^^
[debug] [Appium]
[debug] [Appium] SyntaxError: Cannot use import statement outside a module
[debug] [Appium]     at wrapSafe (internal/modules/cjs/loader.js:979:16)
[debug] [Appium]     at Module._compile (internal/modules/cjs/loader.js:1027:27)
[debug] [Appium]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[debug] [Appium]     at Module.load (internal/modules/cjs/loader.js:928:32)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[debug] [Appium]     at Module.require (internal/modules/cjs/loader.js:952:19)
[debug] [Appium]     at require (internal/modules/cjs/helpers.js:88:18)
[debug] [Appium]     at Object.<anonymous> (/Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:5:1)
[debug] [Appium]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[debug] [Appium]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[debug] [Appium]     at Module.load (internal/modules/cjs/loader.js:928:32)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[debug] [Appium]     at Module.require (internal/modules/cjs/loader.js:952:19)
[debug] [Appium]     at require (internal/modules/cjs/helpers.js:88:18)
[debug] [Appium]     at Object.<anonymous> (/Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/node_modules/appium-xcuitest-driver/index.js:5:1)
[debug] [Appium]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1608115546221 (18:45:46 GMT+0800 (中国标准时间))
[debug] [W3C] Encountered internal error running command: Error: Could not load a driver for automationName 'XCUITest' and platformName 'iOS'. Please verify your Appium installation
[debug] [W3C]     at AppiumDriver.getDriverAndVersionForCaps (/Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/lib/appium.js:247:11)
[debug] [W3C]     at AppiumDriver.createSession (/Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/lib/appium.js:319:66)
[debug] [W3C]     at commandExecutor (/Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:334:9)
[debug] [W3C]     at AppiumDriver.executeCommand (/Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:348:15)
[debug] [W3C]     at AppiumDriver.executeCommand (/Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/lib/appium.js:528:26)
[debug] [W3C]     at asyncHandler (/Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:300:34)
[debug] [W3C]     at /Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:439:15
[debug] [W3C]     at Layer.handle [as handle_request] (/Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C]     at next (/Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [W3C]     at Route.dispatch (/Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [W3C]     at Layer.handle [as handle_request] (/Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C]     at /Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[debug] [W3C]     at Function.process_params (/Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [W3C]     at next (/Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [W3C]     at logger (/Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [W3C]     at Layer.handle [as handle_request] (/Users/server/.nvm/versions/node/v14.15.2/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C] Destroying socket connection
```

**Comment by KazuCocoa** [comment] 2020-12-16 17:46
It seems your node module dependencies broke someway.
Please make sure you install appium beta via `npm install -g appium@beta` to keep dependencies in each module.

**Comment by dduphorn** [comment] 2020-12-16 22:36
I got passed this by updating the WebDriverAgent -> Build Settings -> Build Options -> Validate Workspace = Yes.

**Comment by chenchengyuan** [comment] 2020-12-17 05:06
> It seems your node module dependencies broke someway.
> Please make sure you install appium beta via `npm install -g appium@beta` to keep dependencies in each module.

The same issue use Appium v1.20.0-beta.0(replace appium-webdriveragent with wda master)

**Comment by chenchengyuan** [comment] 2020-12-17 05:09
> I got passed this by updating the WebDriverAgent -> Build Settings -> Build Options -> Validate Workspace = Yes.
> 
> I also had to update it for the iOS project/app

Nice, solved it（Appium v1.20.0-beta.0 & current appium-webdriveragent）

**Comment by KazuCocoa** [comment] 2020-12-17 05:31
Interesting. > Validate Workspace

The configuration is not in Xcode 10, but in newer ones.
Let me check if the value can set in supported Xcode versions. (If lower Xcode also works with it, we'll be able to add it.)

**Comment by KazuCocoa** [comment] 2020-12-17 07:53
@chenchengyuan @dduphorn What about setting the value as `NO`?
According to https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built , 'YES' or 'NO' was no matter. The attribute itself solved their issue.
Then, we'd like to keep it `NO` (default value)

**Comment by chenchengyuan** [comment] 2020-12-17 09:47
> @chenchengyuan @dduphorn What about setting the value as `NO`?
> According to https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built , 'YES' or 'NO' was no matter. The attribute itself solved their issue.
> Then, we'd like to keep it `NO` (default value)

1. The wda v2.32.1 , both 'YES' and 'NO' can build success. When run case, it has dependencies issue.
2. The current wda in appium(`appium/node_modules/appium-webdriveragent`), set 'Yes' build success, 'No' failed.

**Comment by KazuCocoa** [comment] 2020-12-17 16:34
Thanks. It is expected. Will keep NO explicitly as the default value

**Comment by hkhan314** [comment] 2020-12-17 20:46
> I got passed this by updating the WebDriverAgent -> Build Settings -> Build Options -> Validate Workspace = Yes.
> 
> I also had to update it for the iOS project/app

What would I do if I'm using Appium desktop? There's no WebDriverAgent project I can find. I was using v1.18.3 and it was working fine. It started giving me this error after updating to the newest version, and when I switched back it's giving me the same error. 

> Building for iOS Simulator, but the linked and embedded framework 'YYCache.framework' was built for iOS + iOS Simulator.
>         Building for iOS Simulator, but the linked and embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator.
>         Building for iOS Simulator, but the embedded framework 'YYCache.framework' was built for iOS + iOS Simulator.
>         Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator.
>         WebDriverAgentRunner:
>                 WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/humza/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2020.12.17_15-27-42--0500.xcresult. (Underlying Error: Cannot launch simulated executable: no file found at /Users/humza/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app))

It does't seem to have a /Products directory.

**Comment by KazuCocoa** [comment] 2020-12-17 21:35
https://github.com/appium/appium-desktop#connect-to-local-appium-server should help to connect to local `appium@beta` for Appium Desktop.

**Comment by HanCIT** [comment] 2020-12-18 01:58
@KazuCocoa Is there a corresponding beta desktop we can download?

**Comment by KazuCocoa** [comment] 2020-12-18 09:48
https://github.com/appium/appium-desktop/releases/tag/v1.20.0-beta.0 has appium-webdriveragent 2.32.2.

**Comment by larsthorup** [comment] 2020-12-24 08:08
> note: `appium@beta` has the fix. (appium-webdriveragent module should be `2.32.0`)

Note: I had to `npm uninstall appium && npm install appium@beta` to get the updated version.

**Comment by lihiM-99** [comment] 2020-12-26 23:34
Hey, 
I did everything that was written in this thread.
since I upgrade my mac to big sure 11.1 I can't run my IOS simulator using Xcode.

I'm using Xcode version 12.3 and Appium version 1.19.1 (I tried to install beta version of Appium and it still updated to 1.19.1 )
and when Im running my code I get the error: Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

** I did all the relevant settings in the webdriveragent in the xcode

I'm looking for a solution for days

please help :)

**Comment by aaustin-orionlabs** [comment] 2020-12-29 00:22
yeah, beta fixes it 

npm install -g appium@beta

**Comment by baligit** [comment] 2020-12-29 13:24
> I got passed this by updating the WebDriverAgent -> Build Settings -> Build Options -> Validate Workspace = Yes.
> 
> I also had to update it for the iOS project/app

I can not find Validate Workspace. Did you mean this section?
<img width="535" alt="image" src="https://user-images.githubusercontent.com/63911430/103286875-82735d80-49e1-11eb-8457-573873c72e92.png">

**Comment by baligit** [comment] 2020-12-29 13:32
> yeah, beta fixes it
> 
> npm install -g appium@beta

As I run this command in the terminal, I got the following error: 


`npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /usr/local/Cellar/node/15.0.1/lib/node_modules/appium/node_modules/.bin/authorize-ios
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/Cellar/node/15.0.1/lib/node_modules/appium/node_modules/.bin/authorize-ios'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bali/.npm/_logs/2020-12-29T13_31_07_009Z-debug.log` 

Any support?

**Comment by lihiM-99** [comment] 2020-12-29 13:41
I had to downgrade Xcode to version 11.7 and now everything works okay

**Comment by baligit** [comment] 2020-12-29 13:50
Fixed by Validate Workspace form 'No' to 'YES' <img width="951" alt="image" src="https://user-images.githubusercontent.com/63911430/103288323-ea777300-49e4-11eb-98f2-739c35e449a4.png">

**Comment by vani20goyal** [comment] 2020-12-30 07:37
Thank you @baligit - This above screenshot about Validate Workspace worked

**Comment by andrewgill02** [comment] 2021-01-05 16:37
I also have this issue, I've tried all the work arounds listed here and none have worked, I can't install appium@beta as I get this error.

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Yet the files exist as a symlink to the appium-ios-driver/index.js file.

**Comment by vani20goyal** [comment] 2021-01-05 20:35
> I also have this issue, I've tried all the work arounds listed here and none have worked, I can't install appium@beta as I get this error.
> 
> ```
> npm ERR! code ENOENT
> npm ERR! syscall chmod
> npm ERR! path /usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios
> npm ERR! errno -2
> npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent
> ```
> 
> Yet the files exist as a symlink to the appium-ios-driver/index.js file.

Try deleting ios authorize file located in above folder. And re install through brew

**Comment by KazuCocoa** [comment] 2021-01-05 21:55
1.20.0 has been released.
(appium-ios-driver is no longer there.)

**Comment by parisaguilera** [comment] 2021-01-17 03:18
finally solved, uninstall your appium desktop app-> 

1.- Download: https://github.com/appium/appium-desktop/releases/tag/v1.20.0 and install
2.- Open Xcode , and open project: "Webdriveragent"  ->(/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/webdriver...)
3.- Click in the "WebDriverAgent" , click "Info" and click in "All" and click "Combined". Then search "validate workspace" and select "YES" in validate workspace.
4.- build project -> (Product -> Build).
5.- Solved

THX @baligit , @KazuCocoa

**Comment by ps1logi** [comment] 2021-02-13 08:29
@parisaguilera @KazuCocoa thank you issue got solved
