### ISSUE TITLE
Appium clicks not working on Galaxy S10 due to incorrect coordinates

### ISSUE THREAD

**Issue by GadgetFreakUK** [appium/appium#14810] opened 2020-10-16 08:23 UTC
## The problem

Clicks are failing on Galaxy S10 due to Appium reporting the incorrect bounds for an element.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium Desktop

## Details

Run any Unity3D app, and invoke any kind of system dialog/pop-up. Start an inspector session and the element bounds will not align with what is shown in the screenshot. Make a note of the coordinates of one of the bounds, then launch uiautomatorviewer.bat from the android SDK\tools\bin. The element bounds reported from the Android SDK viewer will differ from what is reported by Appium, and be correct whereas Appium's bounds are incorrect.

Using UIAutomator2.

https://imgur.com/boH6vbI
https://imgur.com/qpnuud1

Problem also reproduced on a OnePlus 6T

## Code To Reproduce Issue [ Good To Have ]

No code required, the issue can be reproduced using an inspector session.

**Comment by mykola-mokhnach** [comment] 2020-10-16 08:52
By default Appium calculates element visible area rather than its absolute screen bounds. We've made that configurable in appium@beta using the `simpleBoundsCalculation` setting.

**Comment by GadgetFreakUK** [comment] 2020-10-16 08:57
Where can I download Appium Desktop beta from?

**Comment by mykola-mokhnach** [comment] 2020-10-16 09:17
You can use beta version of the server installed via NPM together with desktop UI.

**Comment by GadgetFreakUK** [comment] 2020-10-16 10:28
Are there any instructions on how to do this, I've tried installing appium@beta but the desktop fails to run after that.

According to the documentation the simpleBoundsCalculation was introduced in 1.18.0, and I am already on 1.18.3.
http://appium.io/docs/en/advanced-concepts/settings/

Running an inspector session with these settings, it makes no difference if simpleBoundsCalculation is true or false, the bounds are incorrect either way

  "platformName": "Android",
  "automationName": "UIAutomator2",
  "settings[simpleBoundsCalculation]": true

**Comment by mykola-mokhnach** [comment] 2020-10-16 10:58
use `npm i appium@beta` command to install the recent beta

**Comment by GadgetFreakUK** [comment] 2020-10-16 12:10
[12:58:40] Error trying to install Chromedriver binary. Waiting 1000ms and trying again: Cannot find module 'source-map-support/register'
Require stack:
- C:\Users\richardt\AppData\Local\Programs\Appium\resources\app\node_modules\es6-mapify\build\lib\main.js
- C:\Users\richardt\AppData\Local\Programs\Appium\resources\app\node_modules\asyncbox\build\lib\asyncbox.js
- C:\Users\richardt\AppData\Local\Programs\Appium\resources\app\node_modules\appium-chromedriver\build\lib\install.js
- C:\Users\richardt\AppData\Local\Programs\Appium\resources\app\node_modules\appium-chromedriver\install-npm.js

Downgrade nodejs to 8.17, reinstall appium, try again

> appium-windows-driver@1.13.0 install C:\Users\richardt\AppData\Local\Programs\Appium\resources\app\node_modules\appium-windows-driver
> node install-npm.js

C:\Users\richardt\AppData\Local\Programs\Appium\resources\app\node_modules\readdir-glob\index.js:62
async function* exploreWalkAsync(dir, path, followSyslinks, useStat, shouldSkip, strict) {
              ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\richardt\AppData\Local\Programs\Appium\resources\app\node_modules\archiver\lib\core.js:9:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
npm WARN notsup Unsupported engine for semver@7.3.2: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: semver@7.3.2
npm WARN notsup Unsupported engine for lru-cache@6.0.0: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})

+ many more Not compatible with your version of node errors

**Comment by mykola-mokhnach** [comment] 2020-10-16 15:16
The error is expected. NodeJs version must be 10 or greater

**Comment by GadgetFreakUK** [comment] 2020-10-16 15:24
With node 10 or greater I get this error

[12:58:40] Error trying to install Chromedriver binary. Waiting 1000ms and trying again: Cannot find module 'source-map-support/register'
Require stack:

C:\Users\richardt\AppData\Local\Programs\Appium\resources\app\node_modules\es6-mapify\build\lib\main.js
C:\Users\richardt\AppData\Local\Programs\Appium\resources\app\node_modules\asyncbox\build\lib\asyncbox.js
C:\Users\richardt\AppData\Local\Programs\Appium\resources\app\node_modules\appium-chromedriver\build\lib\install.js
C:\Users\richardt\AppData\Local\Programs\Appium\resources\app\node_modules\appium-chromedriver\install-npm.js

To get past this error I have to go back to node 8, but then get the other errors. I think this is distracting from the issue of the coordinates being incorrect though, because as far as I can tell your changes for simpleBoundsCalculation are in 1.18.3 which I'm using, but setting it to either true or false gives exactly the same outcome - the coordinates are incorrect

**Comment by mykola-mokhnach** [comment] 2020-10-16 15:47
I cannot reproduce this error locally. Perhaps, something is wrong with your local setup. Unfortunately I cannot advice any other solutions.

**Comment by GadgetFreakUK** [comment] 2020-10-19 10:14
Please refer to these 3 images. All are of the same screen, but on the S10 you can change the screen resolution. All 3 resolutions are reporting exactly the same bounds for the native dialog, all of which are still wrong compared to the android sdk's automation viewer. Looks like its not taking scaling into account

https://imgur.com/pbdfjrG (1520x720)
https://imgur.com/vcKRLUo (2280x1080)
https://imgur.com/kjphSpp (3040x1440)

**Comment by mykola-mokhnach** [comment] 2020-10-19 10:58
This is the code responsible for bounding rect calculation: https://github.com/appium/appium-uiautomator2-server/blob/cdefb8306da32b7310e4ca4345461e1d32f3eb88/app/src/main/java/io/appium/uiautomator2/core/AxNodeInfoHelper.java#L183

I cannot neither confirm nor reject that this is an actual issue. I also don't have the corresponding device to check on. Try to debug the server code locally and apply the necessary fixes. We'd be happy to review the PR
You could also try Espresso driver as a possible alternative

**Comment by mykola-mokhnach** [comment] 2020-12-12 09:04
Closed as third party issue

**Closed by mykola-mokhnach** 2020-12-12 09:04 UTC
Labels: ThirdParty, UIAutomator2
