### ISSUE TITLE
Couldn't load inspector

### ISSUE THREAD

**Issue by teymurg** [appium/appium#15308] opened 2021-04-29 01:10 UTC
## The problem

Cannot load inspector, I believe because of `Original error: -[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x282aa22c0` error

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2-4
* Desktop OS/version used to run Appium: Mac IOS 14.0
* Node.js version (unless using Appium.app|exe): 12.8.1
* Mobile platform/version under test: iPadOS 14.4
* Real device or emulator/simulator: real device

## Link to Appium logs

```
[HTTP] --> GET /wd/hub/session/66463d1f-a2b6-47c6-86bf-88f1f640186d/screenshot
[HTTP] {}
[MJSONWP (66463d1f)] Calling AppiumDriver.getScreenshot() with args: ["66463d1f-a2b6-47c6-86bf-88f1f640186d"]
[XCUITest] Executing command 'getScreenshot'
[XCUITest] Taking screenshot with WDA
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/17DC4E28-456A-4AC7-B8BA-43A04F17F93C/screenshot] with no body
[WD Proxy] Got response with status 500: {"value":{"error":"unknown error","message":"-[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x282aa22c0","traceback":"(\n\t0   CoreFoundation                      0x00000001a7882880 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1202304\n\t1   libobjc.A.dylib                     0x00000001bc89dc50 objc_exception_throw + 60\n\t2   CoreFoundation                      0x00000001a778995c 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 182620\n\t3   CoreFoundation                      0x00000001a7885438 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1213496\n\t4   CoreFoundation                      0x00000001a7887740 _CF_forwarding_prep_0 + 96\n\t5   WebDriverAgentLib                   0x00000001079681bc -[XCUIDevice(FBHelpers) fb_rawScreenshotWithQuality:error:] + 156\n\t6   WebDriverAgentLib                   0x0000000107968088 -[XCUIDevice(FBHelpers) fb_screenshotWithError:] + 88\n\t7   WebDriverAgentLib                   0x00000001079070fc +[FBScreenshotCommands handleGetScreenshot:] + 1...
[W3C] Matched W3C error code 'unknown error' to UnknownError
[XCUITest] Error getting screenshot: An unknown server-side error occurred while processing the command. Original error: -[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x282aa22c0
[XCUITest] Taking screenshot with WDA
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/17DC4E28-456A-4AC7-B8BA-43A04F17F93C/screenshot] with no body
[WD Proxy] Got response with status 500: {"value":{"error":"unknown error","message":"-[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x282aa2540","traceback":"(\n\t0   CoreFoundation                      0x00000001a7882880 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1202304\n\t1   libobjc.A.dylib                     0x00000001bc89dc50 objc_exception_throw + 60\n\t2   CoreFoundation                      0x00000001a778995c 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 182620\n\t3   CoreFoundation                      0x00000001a7885438 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1213496\n\t4   CoreFoundation                      0x00000001a7887740 _CF_forwarding_prep_0 + 96\n\t5   WebDriverAgentLib                   0x00000001079681bc -[XCUIDevice(FBHelpers) fb_rawScreenshotWithQuality:error:] + 156\n\t6   WebDriverAgentLib                   0x0000000107968088 -[XCUIDevice(FBHelpers) fb_screenshotWithError:] + 88\n\t7   WebDriverAgentLib                   0x00000001079070fc +[FBScreenshotCommands handleGetScreenshot:] + 1...
[W3C] Matched W3C error code 'unknown error' to UnknownError
[XCUITest] Taking screenshot with WDA
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/17DC4E28-456A-4AC7-B8BA-43A04F17F93C/screenshot] with no body
[WD Proxy] Got response with status 500: {"value":{"error":"unknown error","message":"-[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x282a97540","traceback":"(\n\t0   CoreFoundation                      0x00000001a7882880 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1202304\n\t1   libobjc.A.dylib                     0x00000001bc89dc50 objc_exception_throw + 60\n\t2   CoreFoundation                      0x00000001a778995c 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 182620\n\t3   CoreFoundation                      0x00000001a7885438 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1213496\n\t4   CoreFoundation                      0x00000001a7887740 _CF_forwarding_prep_0 + 96\n\t5   WebDriverAgentLib                   0x00000001079681bc -[XCUIDevice(FBHelpers) fb_rawScreenshotWithQuality:error:] + 156\n\t6   WebDriverAgentLib                   0x0000000107968088 -[XCUIDevice(FBHelpers) fb_screenshotWithError:] + 88\n\t7   WebDriverAgentLib                   0x00000001079070fc +[FBScreenshotCommands handleGetScreenshot:] + 1...
[W3C] Matched W3C error code 'unknown error' to UnknownError
[MJSONWP (66463d1f)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x282a97540
[MJSONWP (66463d1f)]     at errorFromW3CJsonCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
[MJSONWP (66463d1f)]     at ProxyRequestError.getActualError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
[MJSONWP (66463d1f)]     at JWProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:273:19)
[MJSONWP (66463d1f)]     at runMicrotasks ()
[MJSONWP (66463d1f)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[HTTP] <-- GET /wd/hub/session/66463d1f-a2b6-47c6-86bf-88f1f640186d/screenshot 500 1068 ms - 273
[HTTP] 
```

**Comment by mykola-mokhnach** [comment] 2021-04-29 05:32
Duplicate of https://github.com/appium/appium/issues/15262

**Closed by mykola-mokhnach** 2021-04-29 05:32 UTC
