### ISSUE TITLE
Unable to see appium stderr in console/command window with 1.3.7

### ISSUE THREAD

**Issue by pmneve** [appium/appium#4882] opened 2015-04-09 22:04 UTC
With 1.2.0 I could see the stderr debug messages in the command window or Rubymine console depending on where script was launched.  How can I get all appium server output echoed to the console with 1.3.7?

**Comment by 0x1mason** [comment] 2015-04-11 02:11
Can you give me an example of information you expect to see but don't see? What logging level are you using?

**Comment by pmneve** [comment] 2015-04-13 18:30
Eric,

With 1.2.0 was seeing debug messages logging adb device queries, chromedriver startup, finding of emulator, waiting on boot animation etc.

With 1.3.7 I see none of those.

Running at default logging level of 'debug'

Same whether running in windows command window or in Rubymine.

pat

**Comment by pmneve** [comment] 2015-04-14 22:02
Here is example from log file.  Expect to see all of these lines in console, but see none of them.

2015-04-14 21:53:30:601 - info: Welcome to Appium v1.3.7 (REV 72fbfaa116d3d9f6a862600ee99cf02f6d0e2182)
2015-04-14 21:53:30:602 - info: Appium REST http interface listener started on 0.0.0.0:4723
2015-04-14 21:53:30:603 - info: [debug] Non-default server args: {"log":"C:/projects/wria2/wf2/src/wf2-automation/tests/automation/log/appium_demo_appium_20150414145324.log","logTimestamp":true}
2015-04-14 21:53:30:604 - info: Console LogLevel: debug
2015-04-14 21:53:30:604 - info: File LogLevel: debug
2015-04-14 21:53:30:809 - info: --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":600,"androidDeviceReadyTimeout":420,"avdLaunchTimeout":240000,"avdReadyTimeout":240000,"deviceName":"My_device","platformName":"Android","avd":"poc","browserName":"Browser","avdArgs":"-no-audio -http-proxy 151.151.15.250:8080 -dns-server 10.27.206.11:55,10.27.206.101:55,10.91.218.197:55","chromeOptions":{"args":["ignore-certificate-errors=true","homepage=about:blank","test_type=true"]},"chrome.switches":["ignore-certificate-errors=true","homepage=about:blank","test_type=true"]}}
2015-04-14 21:53:30:811 - info: Client User-Agent string: appium/ruby_lib/6.0.0
2015-04-14 21:53:30:811 - warn: Converting cap chrome.switches to string, since it was an object. This might be a user error. Original value was: ["ignore-certificate-errors=true","homepage=about:blank","test_type=true"]
2015-04-14 21:53:30:812 - info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : androidDeviceReadyTimeout, chromeOptions, chrome.switches
2015-04-14 21:53:30:813 - info: Set mode: Proxying straight through to Chromedriver
2015-04-14 21:53:30:813 - info: [debug] Looks like we want chrome on android
2015-04-14 21:53:30:814 - info: [debug] Creating new appium session 48c4afab-c7d0-43d3-a41c-949fc6984240
2015-04-14 21:53:30:816 - info: [debug] Checking whether adb is present
2015-04-14 21:53:30:818 - info: [debug] Using adb from C:\android\sdk\platform-tools\adb.exe
2015-04-14 21:53:30:819 - info: [debug] Using fast reset? true
2015-04-14 21:53:30:819 - info: [debug] Preparing device for session
2015-04-14 21:53:30:819 - info: [debug] Not checking whether app is present since we are assuming it's already on the device
2015-04-14 21:53:30:819 - info: [debug] Trying to find poc emulator
. . .

**Comment by sebv** [comment] 2015-06-03 12:40
tried `node . --log ./bid.log` from master, got both log file and console.log, but I think it is in stdout.

**Comment by sebv** [comment] 2015-06-10 05:54
Closing, not a bug.

**Closed by sebv** 2015-06-10 05:54 UTC
Labels: OnGoing
