### ISSUE TITLE
Appium throwing 'Device is not online' error for Android on Mac

### ISSUE THREAD

**Issue by AppiumUserForMobile** [appium/appium#5704] opened 2015-10-09 17:23 UTC
I am using Appium 1.4.8 and using 5.0.1 Android version.
'adb devices' command is  recognizing the device but appium is throwing error saying 'Device is not online'.
I tried connecting this device to multiple Mac machines and tried with multiple devices as well. 
I have tried every suggestion online and none of them  worked. 

Here is what I tried:
Under 'Developer options' ->USB debugging is ON
Changed USB computer connection from MTP to PTP.
Changed USB cable, used USB cable which came with phone.
JAVA_HOME, ANDROID_HOME and PATH variables are set correctly.
Updated Android SDK.
Restarted everything.
Killed additional  adb processes.
Replacing chrome driver under appium with latest one 2.19. 
Tried reinstalling appium and android sdk.
Turning USB debugging ON and OFF.

Here is the stack trace. Have been struggling to get our this error from past 3 days. Appreciate your help !!

info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"04150df4ab488039"}}}

info: JSONWP Proxy: Got response with status 200: {"sessionId":"c1c1307719715ee0add5cde197addb01","status":13,"value":{"message":"unknown error: Device 04150df4ab488039 is not online\n  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d...

info: Chromedriver stopped unexpectedly on us, shutting down then calling back up with the on-die callback

error: Chromedriver: Chromedriver exited unexpectedly with code null, signal SIGTERM

error: Chromedriver: Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device 04150df4ab488039 is not online
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.5 x86_64))
    at JWProxy.command$ (lib/proxy.js:149:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:254:14)
    at GeneratorFunctionPrototype.runBound (domain.js:267:12)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at process._tickDomainCallback (node.js:381:11)
 { [Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device 04150df4ab488039 is not online
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.5 x86_64))]
  status: 13,
  value: { message: 'unknown error: Device 04150df4ab488039 is not online\n  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.5 x86_64)' },
  httpCode: 200 }

info: [debug] Cleaning up appium session

error: Failed to start an Appium session, err was: Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device 04150df4ab488039 is not online
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.5 x86_64))

info: [debug] Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device 04150df4ab488039 is not online
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.5 x86_64))
    at JWProxy.command$ (lib/proxy.js:149:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:254:14)
    at GeneratorFunctionPrototype.runBound (domain.js:267:12)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at process._tickDomainCallback (node.js:381:11)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device 04150df4ab488039 is not online\n  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.5 x86_64)))","status":13,"value":{"message":"unknown error: Device 04150df4ab488039 is not online\n  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.5 x86_64)"},"httpCode":200,"origValue":"An unknown server-side error occurred while processing the command. (Original error: unknown error: Device 04150df4ab488039 is not online\n  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.5 x86_64))"},"sessionId":null}
info: <-- POST /wd/hub/session 500 6343.417 ms - 857 
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
info: [debug] [BOOTSTRAP] [debug] Closed client connection
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
info: [debug] [UIAUTOMATOR STDOUT] Time: 1.494
info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 
-1
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...

info: [debug] UiAutomator shut down normally

**Comment by seleniumappiumnewbie** [comment] 2015-10-11 21:54
I'm seeing this error also using  new Appium 1.4.13 and Nexus 9 with Android 5.1.1.

info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)

info: Appium REST http interface listener started on 0.0.0.0:4723

info: [debug] Non-default server args: {"app":"browser","deviceName":"HT4CJJT00982","platformName":"Android","platformVersion":"5.1","automationName":"Appium","browserName":"Chrome","defaultCommandTimeout":7200,"debugLogSpacing":true}

info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: <-- GET /wd/hub/status 200 8.739 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
info: <-- GET /wd/hub/status 200 2.938 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"Chrome","platformName":"Android","deviceName":"HT4CJJT00982","platformVersion":"5.1.1"}}

info: Client User-Agent string: Apache-HttpClient/4.4.1 (Java/1.8.0_60)
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************

info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: Set mode: Proxying straight through to Chromedriver
info: [debug] Looks like we want chrome on android
info: [debug] Creating new appium session fbab9231-f787-4815-8069-63e37cc87cc3
info: [debug] Checking whether adb is present
info: [debug] Using adb from /Users/vnvdm/Documents/android-sdk-macosx/platform-tools/adb
info: [debug] Using fast reset? true
info: [debug] Preparing device for session
info: [debug] Not checking whether app is present since we are assuming it's already on the device
info: Retrieving device
info: [debug] Trying to find a connected android device

info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/vnvdm/Documents/android-sdk-macosx/platform-tools/adb devices

info: [debug] 1 device(s) connected

info: Found device HT4CJJT00982
info: [debug] Setting device id to HT4CJJT00982
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)

info: [debug] executing cmd: /Users/vnvdm/Documents/android-sdk-macosx/platform-tools/adb -s HT4CJJT00982 wait-for-device

info: [debug] executing cmd: /Users/vnvdm/Documents/android-sdk-macosx/platform-tools/adb -s HT4CJJT00982 shell "echo 'ready'"

info: [debug] Starting logcat capture

info: [debug] Pushing unlock helper app to device...

info: [debug] executing cmd: /Users/vnvdm/Documents/android-sdk-macosx/platform-tools/adb -s HT4CJJT00982 install "/usr/local/lib/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"

info: [debug] executing cmd: /Users/vnvdm/Documents/android-sdk-macosx/platform-tools/adb -s HT4CJJT00982 shell "dumpsys window"

info: [debug] Screen already unlocked, continuing.

info: [debug] Forwarding system:4724 to device:4724
info: [debug] executing cmd: /Users/vnvdm/Documents/android-sdk-macosx/platform-tools/adb -s HT4CJJT00982 forward tcp:4724 tcp:4724

info: [debug] Pushing appium bootstrap to device...

info: [debug] executing cmd: /Users/vnvdm/Documents/android-sdk-macosx/platform-tools/adb -s HT4CJJT00982 push "/usr/local/lib/node_modules/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/

info: Starting App

info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: /Users/vnvdm/Documents/android-sdk-macosx/platform-tools/adb -s HT4CJJT00982 shell "ps 'uiautomator'"

info: [debug] No matching processes found

info: [debug] Running bootstrap
info: [debug] spawning: /Users/vnvdm/Documents/android-sdk-macosx/platform-tools/adb -s HT4CJJT00982 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.android.browser -e disableAndroidWatchers false

info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1

info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1

info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724

info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready

info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data\/local\/tmp"}
info: [debug] dataDir set to: /data/local/tmp
info: Chromedriver: Changed state to 'starting'

info: Chromedriver: Set chromedriver binary as: /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
info: Chromedriver: Killing any old chromedrivers, running: ps -ef | grep /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver | grep -v grep |grep -e '--port=9515\(\s.*\)\?$' | awk '{ print $2 }' | xargs kill -15

info: Chromedriver: Successfully cleaned up old chromedrivers

info: Chromedriver: Spawning chromedriver with: /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9515

info: Chromedriver: [STDOUT] Starting ChromeDriver 2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281) on port 9515
Only local connections are allowed.

info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body

info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body

info: JSONWP Proxy: Got response with status 200: {"sessionId":"","status":0,"value":{"build":{"version":"alpha"},"os":{"arch":"x86_64","name":"Mac OS X","version":"10.11.0"}}}

info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"HT4CJJT00982"}}}

info: JSONWP Proxy: Got response with status 200: {"sessionId":"7ffcbd3b3311371342457c5cb29fbd5f","status":13,"value":{"message":"unknown error: Device HT4CJJT00982 is not online\n  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e...

info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"HT4CJJT00982"}}}

info: JSONWP Proxy: Got response with status 200: {"sessionId":"7cb6a6f37ff18e26e87fd79d7dec6862","status":13,"value":{"message":"unknown error: com.android.browser is not installed on device HT4CJJT00982\n  (Driver info: chromedriver=2.18.343837 (52...

info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"HT4CJJT00982"}}}

info: JSONWP Proxy: Got response with status 200: {"sessionId":"a43198a05fcc6a716d05f8f9c02d4653","status":13,"value":{"message":"unknown error: com.android.browser is not installed on device HT4CJJT00982\n  (Driver info: chromedriver=2.18.343837 (52...

info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"HT4CJJT00982"}}}

info: JSONWP Proxy: Got response with status 200: {"sessionId":"60e009238b150c02f7a93cc4edf54962","status":13,"value":{"message":"unknown error: Device HT4CJJT00982 is not online\n  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e...

info: Chromedriver: Changed state to 'stopped'

error: Chromedriver: Chromedriver exited unexpectedly with code null, signal SIGTERM

info: Chromedriver stopped unexpectedly on us, shutting down then calling back up with the on-die callback

error: Chromedriver: Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device HT4CJJT00982 is not online
  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.11.0 x86_64))
    at JWProxy.command$ (lib/proxy.js:149:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:254:14)
    at GeneratorFunctionPrototype.runBound (domain.js:267:12)
    at run (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at process._tickDomainCallback (node.js:381:11)
 { [Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device HT4CJJT00982 is not online
  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.11.0 x86_64))]
  status: 13,
  value: { message: 'unknown error: Device HT4CJJT00982 is not online\n  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.11.0 x86_64)' },
  httpCode: 200 }

info: [debug] Cleaning up appium session

error: Failed to start an Appium session, err was: Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device HT4CJJT00982 is not online
  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.11.0 x86_64))

info: [debug] Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device HT4CJJT00982 is not online
  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.11.0 x86_64))
    at JWProxy.command$ (lib/proxy.js:149:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:254:14)
    at GeneratorFunctionPrototype.runBound (domain.js:267:12)
    at run (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at process._tickDomainCallback (node.js:381:11)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Device HT4CJJT00982 is not online\n  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.11.0 x86_64)))","status":13,"value":{"message":"unknown error: Device HT4CJJT00982 is not online\n  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.11.0 x86_64)"},"httpCode":200,"origValue":"An unknown server-side error occurred while processing the command. (Original error: unknown error: Device HT4CJJT00982 is not online\n  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.11.0 x86_64))"},"sessionId":null}
info: <-- POST /wd/hub/session 500 5221.693 ms - 845 
info: [debug] UiAutomator shut down normally
info: [debug] executing cmd: /Users/vnvdm/Documents/android-sdk-macosx/platform-tools/adb -s HT4CJJT00982 shell "am force-stop com.android.browser"
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
info: [debug] [BOOTSTRAP] [debug] Closed client connection
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
info: [debug] [UIAUTOMATOR STDOUT] Time: 2.651
info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
info: [debug] [UIAUTOMATOR STDOUT] INSTRU
MENTATION_STATUS_CODE: -1

info: [debug] Stopping logcat capture

info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] Cleaning up appium session

**Comment by moizjv** [comment] 2015-10-11 21:56
duplicate of https://github.com/appium/appium/issues/5686

**Closed** 2015-10-11 21:57 UTC
Labels: NeedsTriage

**Comment by saurabhsaagu** [comment] 2016-04-29 09:46
I came across this issue twice.
On one occasion switching the USB debugging mode from charging to MTP solved it.
At other instance, i checked the build path and realized that a couple of JARs had their location changed, adding the correct location fixed it.

**Comment by JMVM** [comment] 2016-11-09 09:20
The same issue with Samsung Galaxy Note 4 and Android 5.1.1.

Disabling and re enabling 'USB debugging' option fixed.
