### ISSUE TITLE
Android app is getting crashed on launching (with appium session alive)

### ISSUE THREAD

**Issue by aditya369Bhargav** [appium/appium#16104] opened 2021-11-16 08:53 UTC
## The problem

Android app is getting crashed on launching

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Desktop OS/version used to run Appium:MacOs BigSur 11.5.2
* Node.js version (unless using Appium.app|exe): v16.9.1
* Npm or Yarn package manager: 7.21.1
* Mobile platform/version under test: Android 11,8.1.0,9
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Both

## Details

Step Followed:
1.Launched an appium server
2.Connected an app with server with appium client (java) code
3.After few seconds(say 40 sec) app is getting crashed

Note:-
1.Tried manually and able to lauch and use app for long time without any issues
2.Same app we deployed over ios and working fine with apppium

## Adb Logs To Reproduce Issue [ Good To Have ]

  --------- beginning of crash
2021-11-12 17:13:06.576 7900-7923/io.appium.uiautomator2.server E/AndroidRuntime: FATAL EXCEPTION: Instr: androidx.test.runner.AndroidJUnitRunner
    Process: io.appium.uiautomator2.server, PID: 7900
    java.lang.IllegalStateException: UiAutomation not connected!
        at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1096)
        at android.app.UiAutomation.disconnect(UiAutomation.java:275)
        at android.app.Instrumentation.finish(Instrumentation.java:242)
        at androidx.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:367)
        at androidx.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:415)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:404)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2075)
2021-11-12 17:13:06.592 7900-7923/io.appium.uiautomator2.server I/Process: Sending signal. PID: 7900 SIG: 9
2021-11-12 17:13:06.643 950-986/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2021-11-12 17:13:06.644 950-986/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2021-11-12 17:13:06.646 950-964/? I/ActivityManager: Process io.appium.uiautomator2.server (pid 7900) has died: fore FGS 
2021-11-12 17:13:06.647 950-988/? W/zygote64: kill(-7900, 9) failed: No such process
2021-11-12 17:13:06.647 950-988/? I/zygote64: Successfully killed process cgroup uid 11700 pid 7900 in 0ms
2021-11-12 17:13:06.648 950-964/? W/ActivityManager: Crash of app io.appium.uiautomator2.server running instrumentation ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner}
2021-11-12 17:13:06.649 950-964/? I/ActivityManager: Force stopping io.appium.uiautomator2.server appid=11700 user=0: finished inst
2021-11-12 17:13:06.650 950-986/? W/ActivityManager: Error shutting down UiAutomationConnection
2021-11-12 17:13:06.654 950-9178/? W/Binder: Outgoing transactions from this process must be FLAG_ONEWAY
    java.lang.Throwable
        at android.os.BinderProxy.transact(Binder.java:752)
        at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:160)
        at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
2021-11-12 17:13:06.655 950-9178/? I/ActivityManager: Failure reporting to instrumentation watcher: comp=ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner} results=Bundle[{shortMsg=Process crashed.}]
2021-11-12 17:13:06.829 950-1561/? I/ActivityManager: Force stopping io.appium.uiautomator2.server.test appid=11701 user=0: from pid 9182
2021-11-12 17:13:06.835 1536-1536/? D/CarrierSvcBindHelper: No carrier app for: 0
2021-11-12 17:13:06.853 695-695/? E/adbd: failed to connect to socket 'tcp:6790': Connection refused
2021-11-12 17:13:06.854 2079-2079/? D/RegisteredNfcFServicesCache: Service unchanged, not updating
2021-11-12 17:13:07.058 9184-9184/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
2021-11-12 17:13:07.143 9184-9184/? D/ICU: Timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
2021-11-12 17:13:07.160 9184-9184/? I/app_process: The ClassLoaderContext is a special shared library.
2021-11-12 17:13:07.194 9184-9184/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
2021-11-12 17:13:07.201 950-2141/? I/ActivityManager: Force stopping io.appium.uiautomator2.server appid=11700 user=0: start instr
2021-11-12 17:13:07.215 950-2141/? I/ActivityManager: Start proc 9195:io.appium.uiautomator2.server/u0a1700 for added application io.appium.uiautomator2.server
2021-11-12 17:13:07.231 9195-9195/? I/zygote64: Late-enabling -Xcheck:jni
2021-11-12 17:13:07.425 9195-9195/io.appium.uiautomator2.server I/zygote64: The ClassLoaderContext is a special shared library.
2021-11-12 17:13:07.428 9195-9195/io.appium.uiautomator2.server I/zygote64: The ClassLoaderContext is a special shared library.
2021-11-12 17:13:07.431 9195-9195/io.appium.uiautomator2.server W/zygote64: ClassLoaderContext classpath element mismatch for position 0. expected=/system/framework/android.test.mock.jar, found=/system/framework/android.test.runner.jar (PCL[/system/framework/android.test.mock.jar*1065265343:/system/framework/android.test.runner.jar*1742119008] | PCL[/system/framework/android.test.runner.jar*1742119008:/system/framework/android.test.mock.jar*1065265343])
2021-11-12 17:13:07.435 9195-9195/io.appium.uiautomator2.server W/zygote64: ClassLoaderContext classpath size mismatch for position 0. expected=0, found=4 (PCL[] | PCL[/system/framework/android.test.runner.jar*1742119008:/system/framework/android.test.mock.jar*1065265343:/data/app/io.appium.uiautomator2.server.test-Ti3ii2y5Wf5YZH5tpirH4w==/base.apk*809781538:/data/app/io.appium.uiautomator2.server.test-Ti3ii2y5Wf5YZH5tpirH4w==/base.apk!classes2.dex*4010845360])
2021-11-12 17:13:07.437 9195-9195/io.appium.uiautomator2.server W/zygote64: Found duplicate classes, falling back to extracting from APK : /data/app/io.appium.uiautomator2.server-D2jj6ZP3CqhTkn9769OwRg==/base.apk
2021-11-12 17:13:07.438 9195-9195/io.appium.uiautomator2.server W/zygote64: NOTE: This wastes RAM and hurts startup performance.
2021-11-12 17:13:07.438 9195-9195/io.appium.uiautomator2.server W/zygote64: Found duplicated class when checking oat files: 'Ljunit/runner/BaseTestRunner;' in /data/app/io.appium.uiautomator2.server-D2jj6ZP3CqhTkn9769OwRg==/base.apk and /system/framework/android.test.runner.jar
2021-11-12 17:13:07.587 9195-9195/io.appium.uiautomator2.server W/System: ClassLoader referenced unknown path: 
2021-11-12 17:13:07.609 9195-9195/io.appium.uiautomator2.server I/MonitoringInstr: Instrumentation started!
2021-11-12 17:13:07.637 9195-9195/io.appium.uiautomator2.server I/MonitoringInstr: No JSBridge.
2021-11-12 17:13:07.645 9216-9216/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
2021-11-12 17:13:07.714 9195-9218/io.appium.uiautomator2.server I/UsageTrackerFacilitator: Usage tracking disabled
2021-11-12 17:13:07.719 9216-9216/? D/ICU: Timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
2021-11-12 17:13:07.729 9195-9218/io.appium.uiautomator2.server I/TestRequestBuilder: Scanning classpath to find tests in paths [/data/app/io.appium.uiautomator2.server.test-Ti3ii2y5Wf5YZH5tpirH4w==/base.apk]
2021-11-12 17:13:07.734 9216-9216/? I/app_process: The ClassLoaderContext is a special shared library.
2021-11-12 17:13:07.736 9195-9218/io.appium.uiautomator2.server W/zygote64: Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?
2021-11-12 17:13:07.766 9216-9216/? D/AndroidRuntime: Calling main entry com.android.commands.pm.Pm
2021-11-12 17:13:07.777 9216-9216/? I/app_process: System.exit called, status: 0
2021-11-12 17:13:07.777 9216-9216/? I/AndroidRuntime: VM exiting with result code 0.
2021-11-12 17:13:07.781 9216-9227/? W/MessageQueue: Handler (android.os.Handler) {302c8da} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {302c8da} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:545)
        at android.os.Handler.enqueueMessage(Handler.java:662)
        at android.os.Handler.sendMessageAtTime(Handler.java:631)
        at android.os.Handler.sendMessageDelayed(Handler.java:601)
        at android.os.Handler.post(Handler.java:357)
        at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:57)
        at com.android.internal.os.IResultReceiver$Stub.onTransact(IResultReceiver.java:58)
        at android.os.Binder.execTransact(Binder.java:697)
2021-11-12 17:13:07.861 695-695/? E/adbd: failed to connect to socket 'tcp:6790': Connection refused
2021-11-12 17:13:08.011 9230-9230/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
2021-11-12 17:13:08.096 9230-9230/? D/ICU: Timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
2021-11-12 17:13:08.112 9230-9230/? I/app_process: The ClassLoaderContext is a special shared library.
2021-11-12 17:13:08.144 9230-9230/? D/AndroidRuntime: Calling main entry com.android.commands.pm.Pm
2021-11-12 17:13:08.161 9230-9239/? W/MessageQueue: Handler (android.os.Handler) {5a56343} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {5a56343} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:545)
        at android.os.Handler.enqueueMessage(Handler.java:662)
        at android.os.Handler.sendMessageAtTime(Handler.java:631)
        at android.os.Handler.sendMessageDelayed(Handler.java:601)
        at android.os.Handler.post(Handler.java:357)
        at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:57)
        at com.android.internal.os.IResultReceiver$Stub.onTransact(IResultReceiver.java:58)
        at android.os.Binder.execTransact(Binder.java:697)

**Comment by mykola-mokhnach** [comment] 2021-11-16 18:05
Duplicate of https://github.com/appium/appium/issues?q=is%3Aissue+%22UiAutomation+not+connected%22+is%3Aclosed

This exception is happening ion a level which is beyond Appium's control. Try to test on another device as a possible workaround

**Comment by mykola-mokhnach** [comment] 2021-11-18 19:33
Closed as third party issue

**Closed by mykola-mokhnach** 2021-11-18 19:33 UTC
Labels: Android, ThirdParty
