### ISSUE TITLE
Allow to restart app without resetting the app data

### ISSUE THREAD

**Issue by Sanjo** [appium/appium#4955] opened 2015-04-19 05:28 UTC
This is a feature request / suggestion to add a `restart app` command.

**Use case:**
I want to test that a user, who already has logged in before, sees a specific page when he reopens the app later.

I'm aware of the `noReset` capability. But I want to have this set to `false` because each test scenario should start with a clean state. I do this with the `reset` command.

I already have read the similar issues:
- https://github.com/appium/appium/issues/3553
- https://github.com/appium/appium/issues/3783

Let me know if this is something that could be added. I can try to implement it.

**Comment by Jonahss** [comment] 2015-05-08 00:04
Interesting yes. What about a single test, where you first start a driver with `no-reset`, start the app and immediately end the session. Then start a second driver (still in the same test) and this time `no-reset` is `false` so the next test starts fresh?

**Comment by Sanjo** [comment] 2015-05-08 03:11
I use Sauce Labs. So I think that I cannot start a new session without loosing the state of the previous session.

**Comment by Jonahss** [comment] 2015-05-08 17:55
Ah yes, that would certainly be a limitation.
@jlipps what do you think?

**Comment by jlipps** [comment] 2015-05-08 18:15
@Sanjo can you just use `driver.startApp` with the package/activity of the home screen? then use it again with your app's package/activity. just wondering if that does the trick. 

otherwise i'm wondering how we would restart the app with adb?

**Comment by Jonahss** [comment] 2015-05-08 18:28
You could also press the home button. Then use startApp.

**Comment by sebv** [comment] 2015-06-03 11:32
@Sanjo does it answer your question? Or should we put this in new feature?

**Comment by kenkrzeminski** [comment] 2015-06-08 16:29
This feature would be handy. I often write tests that need a quick way to reset the force quit the app on iOS and re-launch it, without clearing the session. When noReset is set to true, the old session is preserved in simulator. I experimented with various settings and commands including driver.update_settings (I'm using the Ruby lib) but nothing seemed to enable me to create a setup where the session is cleared on initializing the tests while allowing the app to be quit/re-launched during the tests.

Essentially, I need a clean slate at the start of a test run every single time, but the ability to quit and re-launch the app without clearing the session. This doesn't seem possible with iOS simulator at the moment.

**Comment by jlipps** [comment] 2015-06-08 21:00
how would you do this outside of appium?

**Comment by sebv** [comment] 2015-06-12 09:25
Not sure if actionable, but moving to feature.

**Comment by toejough** [comment] 2015-08-17 20:57
+1.  exactly what @kenkrzeminski said.  

In response to @jlipps - I'm not sure how to do it for ios, but for android, you quit the app (list open apps with the squarish icon, swipe your app off the screen), then go into the app menu and re-open your app.

**Comment by michaelz-slalom** [comment] 2016-06-24 20:52
A year later, still looking for this functionality in iOS.

**Comment by reach2jeyan** [comment] 2017-05-08 06:54
Is this fixed in android? I would exactly want what @Sanjo mentioned in the first comment. Currently, I will have to have this sign up process each time I am running the scenario. `no reset = true` and `full reset = false` doesn't seem to help, as appium seems to every time reset the `appdata` before launching the application

I tried, removing the `AppPath` and have only the `package name` and `launch activity` name in appium, but, that is not closing the application.

I am running the tests with ruby with `appium_lib`. Is there a way, once I do the sign up, it would start the home page on the rest of my tests each time? This would prevent each time using the sign up account kit activity, plus save a lot of time.

**Comment by mayukataoka** [comment] 2017-05-13 07:02
Noticing the same that @reach2jeyan described in Android.

**Comment by reach2jeyan** [comment] 2017-05-18 06:13
@mayukataoka somehow fixed it with a workaround for now that I got from the appium community..

Force stopping the application with `adb` and starting it with 

```
  app_hash = {
      app_package: '',
      app_activity: ''
  }
  appium_device.start_activity app_hash
end
```

So, mentioning this in the `hooks.rb` After each scenario I force stop the application and launch before each scenario, than reinstalling it.

**Comment by jlipps** [comment] 2017-07-20 17:31
going to close this as a duplicate of #3743. we already have a `startActivity` command which solves half of this problem. the other half can be solved by having a command to stop arbitrary apps, which is what #3743 covers.

**Closed by jlipps** 2017-07-20 17:31 UTC
Labels: Android, Enhancement
