### ISSUE TITLE
Try changing the 'normalizeTagNames' driver setting to 'true' in order to workaround the problem.

### ISSUE THREAD

**Issue by HaidongSong** [appium/appium#13945] opened 2020-02-15 13:50 UTC
## The problem

when I used two processes to implement two devices running, an error was reported. Follow the prompts I set "normalizeTagNames": True, but it is useless (android5.1.1 appium version v1.15.1).
## Error message：
```shell
Process Process-2:
Traceback (most recent call last):
  File "d:\program files (x86)\python\python37-32\Lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "d:\program files (x86)\python\python37-32\Lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\17846\PycharmProjects\app_crawling\crawler\test_multipross_appium.py", line 46, in handle_appium
    if WebDriverWait(driver, 10).until(lambda x: x.find_element_by_xpath("//android.widget.EditText[@resource-id='com.hipu.yidian:id/edtKeyword']")):
  File "C:\Users\haidong\Envs\spider\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\17846\PycharmProjects\app_crawling\crawler\test_multipross_appium.py", line 46, in <lambda>
    if WebDriverWait(driver, 10).until(lambda x: x.find_element_by_xpath("//android.widget.EditText[@resource-id='com.hipu.yidian:id/edtKeyword']")):
  File "C:\Users\haidong\Envs\spider\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\haidong\Envs\spider\lib\site-packages\appium\webdriver\webdriver.py", line 284, in find_element
    'value': value})['value']
  File "C:\Users\haidong\Envs\spider\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\haidong\Envs\spider\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\Users\haidong\Envs\spider\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\Users\haidong\Envs\spider\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error in building: Ill-formed XML document (missing opening tag for android.widget.FrameLayout). Try changing the 'normalizeTagNames' driver setting to 'true' in order to workaround the problem.
```
## Environment
- appium v1.15.1
- android 5.1.1

## Link to Appium logs
-  abnormal operation appium log
https://gist.github.com/HaidongSong/74ecfaa253376ba8c24b9f52bc3ee134#file-abnormal-operation_appium_log
- normal operation appium log
https://gist.github.com/HaidongSong/74ecfaa253376ba8c24b9f52bc3ee134#file-normal-operation

### Program based on python3.7
```python
import time
from selenium.webdriver.support.ui import WebDriverWait
from appium import webdriver
import multiprocessing

def get_size(driver):
    x = driver.get_window_size()['width']
    y = driver.get_window_size()['height']
    return x, y


def handle_appium(devices, port):
    desired_caps = {
            "platformName": "Android",
            "deviceName": devices,
            "udid": devices,  
            "platformVersion": "5",
            "appPackage": "com.hipu.yidian",
            "appActivity": "com.yidian.news.ui.guide.UserGuideActivity",
            "noReset": True,          
            "unicodeKeyboard": True,  
            "resetKeyboard": True,     
            "normalizeTagNames": True,

        }

    driver = webdriver.Remote('http://localhost:'+str(port)+'/wd/hub', desired_caps)
    try:
        # 点击搜索
        if WebDriverWait(driver, 50).until(lambda x: x.find_element_by_xpath(
                "//android.widget.ImageView[@resource-id='com.hipu.yidian:id/search_image']")):

            driver.find_element_by_xpath(
                "//android.widget.ImageView[@resource-id='com.hipu.yidian:id/search_image']").click()
    except:
        pass

    if WebDriverWait(driver, 10).until(lambda x: x.find_element_by_xpath("//android.widget.EditText[@resource-id='com.hipu.yidian:id/edtKeyword']")):
 
        driver.find_element_by_xpath("//android.widget.EditText[@resource-id='com.hipu.yidian:id/edtKeyword']").send_keys('新华社')
        while driver.find_element_by_xpath(
                "//android.widget.EditText[@resource-id='com.hipu.yidian:id/edtKeyword']").text != '新华社':
            driver.find_element_by_xpath(
                "//android.widget.TextSwitcher[@resource-id='com.hipu.yidian:id/txtSearch']").send_keys('新华社')
            time.sleep(0.1)


    driver.find_element_by_xpath("//android.widget.TextView[@resource-id='com.hipu.yidian:id/btnSearch']").click()

    if WebDriverWait(driver,2).until(lambda x: x.find_element_by_xpath("//android.widget.TextView[@resource-id='com.hipu.yidian:id/navi_title' and @text='一点号']")):
        driver.find_element_by_xpath("//android.widget.TextView[@resource-id='com.hipu.yidian:id/navi_title' and @text='一点号']").click()

    if WebDriverWait(driver, 2).until(lambda x: x.find_element_by_xpath(
            "//android.support.v7.widget.RecyclerView/android.widget.RelativeLayout[1]")):
        driver.find_element_by_xpath(
            "//android.support.v7.widget.RecyclerView/android.widget.RelativeLayout[1]").click()

if __name__ == '__main__':
    # handle_yidian(driver)
    m_list = []
    devices_list = ['127.0.0.1:62025', '127.0.0.1:62026']
    for device in range(len(devices_list)):
        port = 4723 + device * 2
        m_list.append(multiprocessing.Process(target=handle_appium, args=(devices_list[device], port)))
    for m1 in m_list:
        m1.start()
    for m2 in m_list:
        m2.join()
```

**Comment by mykola-mokhnach** [comment] 2020-02-15 13:51
> [warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
> [warn] [35m[BaseDriver][39m   normalizeTagNames

It is a setting, not a capability

**Comment by mykola-mokhnach** [comment] 2020-02-15 13:53
Also Android5 itself has a known bug while serializing complex unicode characters like smiles. Unfortunately there is no workaround for that except of upgrading the Android OS itself or switching to UiAutomator1

**Comment by HaidongSong** [comment] 2020-02-15 14:36
@Thank you very much for your answer.But i am a beginner, can you tell me in detail how to set "normalizeTagNames"?

**Comment by mykola-mokhnach** [comment] 2020-02-15 17:00
http://appium.io/docs/en/advanced-concepts/settings/

**Comment by HaidongSong** [comment] 2020-02-16 13:40
@mykola-mokhnach I don't know where to set this parameter, can you tell me more in detail? thank
😢

**Comment by mykola-mokhnach** [comment] 2020-02-16 16:09
I did tell what I know. If you are looking for code examples, consider using [Appium forum](https://discuss.appium.io).

**Comment by HaidongSong** [comment] 2020-02-17 04:58
@mykola-mokhnach According to this URL https://pypi.org/project/Appium-Python-Client/ .I ’ve set ‘’ normalizeTagNames ’but I still get the same error message after running the program，
![enter description here](https://gitee.com/margan/pictures/raw/master/小书匠/1581914993828.png)

**Comment by mykola-mokhnach** [comment] 2020-02-17 06:27
if it still does not work then your issue seem to be the duplicate of the one I mentioned above. Either upgrade the Android OS or change the driver to UiAutomator1 to workaround it.

**Comment by HaidongSong** [comment] 2020-02-17 07:10
@mykola-mokhnach When i change the driver to UiAutomator and set “settings” to {"normalizeTagNames": True}, it can work normly.Thank you very much

**Closed** 2020-02-17 08:44 UTC
Labels: NeedsInfo, NotABug
