### ISSUE TITLE
Images plugin - possible memory leak

### ISSUE THREAD

**Issue by vwillamsModestTree** [appium/appium#18466] opened 2023-04-06 13:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use the driver.findElement(AppiumBy.image(imageToFind)) in consecutive tests, there comes a point where I eventually get a **org.openqa.selenium.StaleElementReferenceException: An element command failed because the referenced element is no longer attached to the DOM.** on the Appium Client console. This is with the knowledge that if run by itself, that test will not have that failure and will pass. It is only when I run multiple tests that use the find elment by image functionality, that it eventually fails.

### Expected Behavior

I expect there to be no errors, and be able to use driver.findElement(AppiumBy.image(imageToFind)) consecutively.

### Minimal Reproducible Example

I am using a cucumber framework for testing, so I have a Feature FIle, a java Step Defintion file,  as well as a Java test runner file.
They are included in the following zip file.
[CalculatorSteps.zip](https://github.com/appium/appium/files/11171135/CalculatorSteps.zip)

### Environment

- Operating system: Windows 10
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.58
  - Node.js version (output of `node --version`):18.15.0
  - `npm` version (output of `npm --version`): 9.6.3
- Appium driver(s) and their version(s): WindowsDriver 2.7.1
- Appium plugin(s) and their version(s): Images 2.0.8
- Platform and version under test: Windows Calculator
- Real device or emulator/simulator: Real Device

I am also using Junit to run the tests.

### Futher Information

Appium Server Logs: 
[AppiumServerLog.txt](https://github.com/appium/appium/files/11171017/AppiumServerLog.txt)

Appium Client Error:
[AppiumClientError.txt](https://github.com/appium/appium/files/11171088/AppiumClientError.txt)

**Comment by mykola-mokhnach** [comment] 2023-04-07 13:32
StaleElementReferenceException usually indicates you try to perform an action on a cached element that does not exist on the screen anymore. Try to find the element again before executing an action on it

**Comment by mykola-mokhnach** [comment] 2023-04-07 13:34
Another possible workaround would be to just fetch element coordinates and click by coordinates

**Comment by mykola-mokhnach** [comment] 2023-04-11 20:06
I assume the error might be thrown by opencv asmjs itself. Then we won't be able to track it down. 

I don't have any other ideas except of the ones mentioned above.

**Comment by jlipps** [comment] 2023-04-11 22:22
I don't see that error string (6632608) anywhere in the Appium log? Are you sure this log includes the issue? It was so long simply scrolling through would not be feasible.

**Comment by vwillamsModestTree** [comment] 2023-04-12 11:56
The error I quoted above was from the client, the file I attached was from the server. I see at the bottom of the server log what could be in reference to the error:


```
[debug] [38;5;32m[WindowsDriver@902c (4111508d)][0m Content-Type: application/json
[38;5;48m[ImageElementPlugin][0m Screenshot size matched screen size
[38;5;16m[AppiumDriver@e722][0m Command 'findElement' was *not* handled by the following behaviours or plugins, even though they were registered to handle it: ["default"]. The command *was* handled by these: ["images"].
[38;5;32m[WindowsDriver@902c (4111508d)][0m The thrown error object does not seem to be a valid instance of the Error class. This might be a genuine bug of a driver or a plugin.
[debug] [38;5;32m[WindowsDriver@902c (4111508d)][0m Encountered internal error running command: undefined
```

**Comment by vwillamsModestTree** [comment] 2023-04-13 16:34
I created a public repository with all the files that you can use to reproduce this issue. https://github.com/vwillamsModestTree/CalculatorAutomation

Should I also consider posting this as in issue in https://github.com/appium/appium-windows-driver as well?

**Comment by jlipps** [comment] 2023-04-14 18:03
Unfortunately I don't have a windows environment handy so I'm not able to check out the repro. The next thing I would try is to add some logging to the various places in the image plugin code to see why an error is being thrown and why it's undefined

**Comment by jlipps** [comment] 2023-04-14 18:03
Can you repro this with the android driver at all?

**Comment by vwillamsModestTree** [comment] 2023-04-14 18:30
I haven't tried the images plugin with the android driver yet, but I will in the future. That will take me some time to set up though.

**Comment by vwillamsModestTree** [comment] 2023-04-17 20:03
Hi. So I think I figured out the issue. When I commented out `appSession.setSetting("getMatchedImageResult", true);` and commented out all of the functions associated with that setting, I was able to run all of the tests together as expected. I also noticed that even when I didn't have any functions associated with that setting, but the setting was uncommented, the issue still appeared. So my guess is that maybe there are some memory issues occuring when that setting is enabled and a certain amount of elements are involved.

**Comment by jlipps** [comment] 2023-04-17 20:28
that could be. opencv was converted into webassembly js so who knows how performant it ultimately is in this mode. you can turn on and off that setting if you want to use it for one or two lines in your script, also.

**Comment by vwillamsModestTree** [comment] 2023-04-18 12:43
So essentially, this setting is unstable when used with large tests? Could we expect this issue to be fixed some time in the future?

**Comment by jlipps** [comment] 2023-04-18 22:04
I have no idea what the root issue is, and therefore no idea if it will be fixed in the future. If you'd like to run some tests with memory profiling on, maybe you could help us to figure out if there's an issue either in the opencv code or in our code.

**Comment by vwillamsModestTree** [comment] 2023-04-19 13:46
Is there a way to do that in appium directly? All I could find was an appium server argument called `--enable-heapdump`, but that was for appium 1.5. I can't seem to find the equivalent for appium 2.

**Comment by vwillamsModestTree** [comment] 2023-04-19 15:40
Ok. So I ran the code with `getMatchedImageResult` enabled and watched the node.exe process in the task manager. I noticed that the process started at around 300 MB memory and ended up at around 1GB memory by the time it started failing.

![MemoryUsedByApium](https://user-images.githubusercontent.com/110922661/233128108-b3a04bac-b127-4b48-8bbf-09b131025f98.png)

**Comment by jlipps** [comment] 2023-04-19 18:41
OK, yeah that's a good indicator there may be a memory leak somewhere. I've adjusted the title to reflect this issue and we can investigate whether the leak is in the plugin or somewhere else

**Comment by jlipps** [comment] 2023-04-19 23:49
@mykola-mokhnach you've done memory leak investigations before, can you see anywhere obvious in our image plugin code where we should maybe use an LRU cache or something (and I thought we already were tbh)

**Comment by mykola-mokhnach** [comment] 2023-04-20 14:00
Unfortunately I don't have time trying to reproduce it. I could help with the memory dump investigation though. All is needed to be done is just to take the heap dump snapshot when the memory usage gets too high as described in https://nodejs.org/en/docs/guides/diagnostics/memory/using-heap-snapshot

**Comment by vwillamsModestTree** [comment] 2023-04-21 12:59
Hi. Here is the heap snapshot file I managed to get:

[CalculatorHeapSnapshot.zip](https://github.com/appium/appium/files/11295883/CalculatorHeapSnapshot.zip)

Please let me know if you needed anything else.

**Comment by mykola-mokhnach** [comment] 2023-04-23 20:06
I can observe the most part of the memory is occupied with binary arrays, which are probably leftovers some non-freed opencv entities. I am currently working on several refactoring for images plugin and will include a fix to one of them.

@vwillamsModestTree I will let you know when a new version of the plugin with necessary fixes is published

**Comment by mykola-mokhnach** [comment] 2023-04-26 05:29
The patch is now available in the master branch of the server and could be verified.

**Comment by mykola-mokhnach** [comment] 2023-05-04 18:49
Closed because of no response

**Closed by mykola-mokhnach** 2023-05-04 18:49 UTC
Labels: Bug, Needs Info, Plugin
