### ISSUE TITLE
Unable to use 'visible' property when locating element by iOS Class Chain, on iOS 16 simulator

### ISSUE THREAD

**Issue by autouser88** [appium/appium#17343] opened 2022-08-09 10:15 UTC
## The problem

Including the visible property when locating an element by iOS Class Chain causes the element to not be found.

## Environment

* Appium version: 2.0.0-beta.40 with xcuitest 4.9.0
* Desktop OS/version used to run Appium: Mac OS Monterey 12.4
* Node.js version: 14.15.4
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 16
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: cli
* Appium Inspector version: 2022.7.1

## Details

Including the visible property when locating an element by iOS Class Chain causes the element to not be found, even though Appium Inspector shows correct visibility when element is selected from the tree in the inspector panel.  This is only an issue on the iOS 16 simulator.  For example, "**/XCUIElementTypeCell[name == 'Name' AND visible == 1]" results in element not found even though the visible property is correct, whereas "**/XCUIElementTypeCell[name == 'Name'" results in the element being found.

## Link to Appium logs

[Appium log](https://gist.github.com/autouser88/9a45abb3f24f917d389ccfe97caa0113)

**Comment by mykola-mokhnach** [comment] 2022-08-09 10:22
Please add page source call before element lookup is being executed and attach the actual output

**Comment by mykola-mokhnach** [comment] 2022-08-09 14:28
I mean the runtime page source might be different from the static one which is visible in the inspector. Unfortunately I don't think we would be able to help anything there without having an actual app to check with and without the page source.

**Comment by autouser88** [comment] 2022-08-10 11:17
I've been able to replicate the error in a simpler app ("Reminders" - default app on new simulator creation) and can now attach page source along with videos showing the behaviour difference between simulators running iOS 15.5 and iOS 16.0.

xcuitest has been updated to 4.9.0, and appium inspector version is 2022.7.1

Steps to reproduce:
1. Given you are using an iOS 16 simulator
2. And the 'Reminders' app has been opened
3. And there is a list with at least one Reminder
4. When you open the list
5. And when you inspect the app
6. Then the XCUIElementTypeTable that contains the reminders should be able to be found by the following class chain '**/XCUIElementTypeTable'
7. And the XCUIElementTypeTable that contains the reminders should be able to be found by the following class chain '**/XCUIElementTypeTable[`visible==1`]'
8. And the XCUIElementTypeTable that contains the reminders should NOT be able to be found by the following class chain '**/XCUIElementTypeTable[`visible==0`]'

[iOS 15.5 page source](https://gist.github.com/autouser88/d4f9185cf6eb09daf67b4a169d253d13)
[iOS 16.0 page source](https://gist.github.com/autouser88/3300e5feab93978e103b3ca788f23702)

[15.5 recording.zip](https://github.com/appium/appium/files/9299526/15.5.recording.zip)
[16.0 recording.zip](https://github.com/appium/appium/files/9299530/16.0.recording.zip)

**Comment by Dan-Maor** [comment] 2022-08-11 07:13
Which Xcode beta are you using?
I'm unable to reproduce the reminders scenario with the latest beta (5) on a simulator nor on a real device running its corresponding beta.
I am, however, able to reproduce the issue with a simulator using Xcode beta 4.

**Comment by autouser88** [comment] 2022-08-11 08:52
ah, I'm using Xcode beta 3.  If it's definitely not reproducible on 5 I'll upgrade

**Comment by autouser88** [comment] 2022-08-11 13:28
Confirming: this isn't an issue on Xcode beta 5

**Comment by mykola-mokhnach** [comment] 2022-08-11 13:46
Closed as third party issue

**Closed by mykola-mokhnach** 2022-08-11 13:46 UTC
Labels: ThirdParty, XCUITest
