### ISSUE TITLE
ffmpeg fails to record iOS screen video

### ISSUE THREAD

**Issue by Trane9991** [appium/appium#11295] opened 2018-08-31 12:57 UTC
## The problem

ffmpeg crashes on screen record 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Desktop OS/version used to run Appium: Mac OS X 10.13.6
* Node.js version (unless using Appium.app|exe): v10.9.0
* Mobile platform/version under test: iOS 12 beta
* Real device or emulator/simulator: simulator

## Details

ffmpeg crashes on screen record and resulting video size is 0 bytes.
I verified that video stream exists on http://localhost:9100

Also, ffmpeg seems to have mjpeg codec installed
```
$ ffmpeg -codecs | grep mjpeg
 DEVIL. mjpeg                Motion JPEG
 D.VIL. mjpegb               Apple MJPEG-B
 D.A.L. adpcm_ima_smjpeg     ADPCM IMA Loki SDL MJPEG
```

## Link to Appium logs

[appium-ffmpeg.log](https://github.com/appium/appium/files/2340083/appium-ffmpeg.log)

**Comment by mykola-mokhnach** [comment] 2018-08-31 13:08
Duplicate of https://github.com/appium/appium/issues/11279

**Closed by mykola-mokhnach** 2018-08-31 13:08 UTC
