### ISSUE TITLE
Android: Unable to turn off Wifi using setConnection

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#8957] opened 2017-08-01 15:20 UTC
## The problem

I can switch on Wi-Fi using the getWebDriver().setConnection(Connection.WIFI);

But i am unable to turn off the wifi programmatically, Since airplane mode will not work for Android 7 and higher.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6 beta3
* Desktop OS/version used to run Appium: MacOS 10.12.6
* Mobile platform/version under test: Android 6 and Android 7
* Real device or emulator/simulator: Moto G4, HTC
* io.appium.settings app version: 2.1

## Details

Need to mention that i tried it on both  uiAutomator2 and uiAutomator.
getWebDriver().setConnection(Connection.None);

on **uiAutomator** it din't give any errors but also din't turn off the wifi.
https://gist.github.com/mayureshshirodkar/488923dce9a3959622e83169e6d02428

on **uiAutomator2** it gave an error and din't turn off wifi
https://gist.github.com/mayureshshirodkar/9e7d4288bee2d33f2333986f491863c3

Workaround for Android 6 was to switch to Airplane mode,but this solution doesn't work with Android 7.

I have also tried running below command manually. But  Wifi setting was on mode and din't toggle.
adb shell am broadcast -a io.appium.settings.wifi --es setstatus disable

Referred:
https://github.com/appium/io.appium.settings
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/network_connection.md

**Comment by dpgraham** [comment] 2017-08-01 16:04
Looks like the problem is that it's setting the network connection type to 0 (None), it should be setting it to 2 (WiFi).

Can you try debugging at the line `getWebDriver().setConnection(Connection.WIFI);` and checking what Connection.WIFI is? It might be a problem with the Java client.

**Comment by mayureshshirodkar** [comment] 2017-08-01 16:09
@dpgraham here's the java client code that i am using:
Java client version: 4.1.2

Code for Connection.class:
package io.appium.java_client.android;

public enum Connection {
    NONE(0),
    AIRPLANE(1),
    WIFI(2),
    DATA(4),
    ALL(6);

    final int bitMask;

    private Connection(int bitMask) {
        this.bitMask = bitMask;
    }
}

**Comment by dpgraham** [comment] 2017-08-01 17:06
You're right, it should be. I misunderstood what the Connections meant.

**Comment by dpgraham** [comment] 2017-08-01 17:19
The `NotYetImplemented` error is expected. It falls back to running an Android ADB command, is shown by:

`[debug] [ADB] Running '/Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb' with args: ["-P",5037,"-s","ZY223DDFLZ","shell","am","broadcast","-a","io.appium.settings.data_connection","--es","setstatus","disable"]`

Can you try running this from your terminal to see if it disables the WiFi

`adb shell am broadcast -a io.appium.settings.wifi --es setstatus disable`

**Comment by mayureshshirodkar** [comment] 2017-08-01 17:27
I tried setting wifi off with this command manually, but din't work.
adb shell am broadcast -a io.appium.settings.wifi --es setstatus disable

This were the logs on adb logcat:
08-01 18:13:13.005 10046 10046 E ExtendedServiceUtils: Failed to load libdashplayer.so : dlopen failed: library "libdashplayer.so" not found
08-01 18:13:13.009 10046 10046 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
08-01 18:13:13.013 10046 10046 D AndroidRuntime: CheckJNI is OFF
08-01 18:13:13.077 10046 10046 D ICU : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
08-01 18:13:13.110 10046 10046 I Radio-JNI: register_android_hardware_Radio DONE
08-01 18:13:13.127 10046 10046 D AndroidRuntime: Calling main entry com.android.commands.am.Am
08-01 18:13:13.139 10046 10046 D AndroidRuntime: Shutting down VM

**Comment by dpgraham** [comment] 2017-08-01 17:49
@vrunoa, do you know what the issue is?

**Comment by SrinivasanTarget** [comment] 2017-08-01 18:30
@jlipps Current API implementation is flaky, that we are aware of [here](https://github.com/appium/appium/issues/6615#issuecomment-273025249).

I see toggle location services API is implemented via key event which is more error prone than this. Why don't we implement or rewrite the existing [toggleWIFI](https://github.com/appium/appium-base-driver/blob/master/lib/mjsonwp/routes.js#L381) like below,

`adb shell am start -a android.intent.action.MAIN -n com.android.settings/.wifi.WifiSettings` - Open up wifi intent then disable via key events. @vrunoa What do you say?

**Comment by mykola-mokhnach** [comment] 2017-08-01 18:56
@SrinivasanTarget We actually use different approaches for emulator and for real devices. On real devices the WiFi service is disabled via Appium Settings helper (`adb shell am broadcast -a io.appium.settings.wifi --es setstatus disable`). However, one has to make sure the correct version of this app is installed (should be 2.1 or newer).

On emulator it is possible to control network state by using `adb emu` commands set. 

The actual device type verification is based on the fact that **avd** capability value (whether it's set or not).

**Comment by vrunoa** [comment] 2017-08-01 22:44
@mykola-mokhnach is right. We separate the implementation to toggle the wifi since setting the wifi state in the emu using the app wasnt working, but was working for real devices. 
@mayureshshirodkar I'll try to reproduce it on my Pixel and give you some feedback. I dont think the JNI error you posted it's related, but maybe i'm wrong.

**Comment by mykola-mokhnach** [comment] 2017-08-02 09:27
@mayureshshirodkar What is the version of Appium Setting app installed on the phone?

**Comment by mayureshshirodkar** [comment] 2017-08-02 09:33
@mykola-mokhnach Appium settings app is on version 2.1.

**Comment by mayureshshirodkar** [comment] 2017-08-16 09:40
@vrunoa were you able to reproduce this?

**Comment by vrunoa** [comment] 2017-08-16 15:20
@mayureshshirodkar I can reproduce the issue on my Pixel with Android 7.1.2 and I got a solution(kinda). Disabling the wifi wasnt working for me until I ran the io.appium.settings app manually. I ran 3 tests and the wifi wasnt been disabled. Just to be curious I rant the settings app manually and run the test again, and it started working. 

You can reproduce this manually; by uninstalling the settings app, run a test and let it fail.
Once you're there run:
```adb shell am broadcast -a io.appium.settings.wifi --es setstatus disable
Broadcasting: Intent { act=io.appium.settings.wifi (has extras) }
Broadcast completed: result=0``` you will see  the wifi not been disabled. 

Now, run the settings app manually and re-run the command:
```adb shell am broadcast -a io.appium.settings.wifi --es setstatus disable
Broadcasting: Intent { act=io.appium.settings.wifi (has extras) }
Broadcast completed: result=-1``` now the wifi got disabled. 
Let me know if you can reproduce this. 

@mykola-mokhnach I guess we can try to launch the io.appium.settings app before starting the session on 7.1.x, as a quick solution.

**Comment by mykola-mokhnach** [comment] 2017-08-16 15:25
@vrunoa I would be happy to review your PR with a fix

**Comment by mayureshshirodkar** [comment] 2017-08-16 15:31
@vrunoa  I manually opened the Appium settings app as you mentioned and was able to enable/ disable Wifi settings on the Moto G4 (7.0)

**Comment by vrunoa** [comment] 2017-08-16 15:47
@mykola-mokhnach @mayureshshirodkar i'll try to create a PR by the end of the week

**Comment by vrunoa** [comment] 2017-08-17 13:28
@mayureshshirodkar do you have a real device with android 6 or below to verify this is also not happening ?

**Comment by mayureshshirodkar** [comment] 2017-08-17 14:25
@vrunoa i tried commands on Android 6.0.1, and they turn Wifi on/off only after i open the appium settings app manually. So the issue exists on Android 6 too.

**Comment by vrunoa** [comment] 2017-08-17 14:39
https://github.com/appium/appium-android-driver/pull/261

**Comment by tfcardoso** [comment] 2017-08-23 16:58
Hi, 

even with the fix published in appium-android-driver@1.25.0. it still does not work for data mobile connection.

Even tried manually with:
adb shell am start -n io.appium.settings/.Settings -e data off
adb shell am broadcast -a io.appium.settings.data_connection --es setstatus disable

**Comment by mykola-mokhnach** [comment] 2018-05-01 10:09
Closed as fixed

**Closed by mykola-mokhnach** 2018-05-01 10:09 UTC
Labels: Bug, P1, UIAutomator2

**Comment by vijay-simha** [comment] 2018-05-11 04:38
Hi All,wifi enable and disable work using adb command

Runtime.getRuntime().exec("adb shell am broadcast -a io.appium.settings.wifi --es setstatus enable");

But when i perform **Batch execution** for 20 -30 scripts continuous regression it fails for Wifi and Gps 

Runtime.getRuntime().exec("adb shell settings put secure location_providers_allowed -gps");
Runtime.getRuntime().exec("adb shell settings put secure location_providers_allowed -network");

**How  to resolve for batch process execution.**
Appium 4.1.2 javaclients
server 1.7.2

**Comment by NewtQA** [comment] 2018-05-17 12:07
In my virtual device mobile data is not getting ON. Can anyone pls hlp me.
