### ISSUE TITLE
Can't select a value in a XCUIElementTypePickerWheel

### ISSUE THREAD

**Issue by pisarenco92** [appium/appium#7305] opened 2016-11-28 16:24 UTC
## The problem

I use sendkeys()/setValue() to select a value from XCUIElementTypePickerWheel, but the value is not selected. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1
* Desktop OS/version used to run Appium: macOS Sierra 10.12
* Mobile platform/version under test: iOS 10/10.1
* Real device or emulator/simulator: Simulator

## Details

![screen shot 2016-11-28 at 6 20 50 pm 2](https://cloud.githubusercontent.com/assets/15072906/20676202/a86772ca-b597-11e6-9255-06cb952edcd7.png)

## Link to Appium logs

https://gist.github.com/pisarenco92/d21148578f51fe4102b0683f7984c135

**Comment by mykola-mokhnach** [comment] 2016-11-28 16:38
Might be a duplicate of https://github.com/appium/appium/issues/6962

**Comment by suganeby** [comment] 2017-01-09 19:57
I have the same issue too. Not able to set value to the picker wheel. I tried 'sendKeys' and 'setValue', none of them worked. 
It seems to be an issue with XCodeUITest. But not sure when apple would fix the issue because issue seems to be there for over an year. In XCodeUITest, setting value to the picker wheel is achieved by tapping also. So I dont think this issue would get any attention by apple.

Is there any work around from appium side?

**Comment by kcinman11358** [comment] 2017-01-13 23:22
@jlipps any help with pickerwheels?

**Comment by jlipps** [comment] 2017-01-17 23:49
Pretty sure I have seen reports of this working for folks, and it's also in our testsuite. @mykola-mokhnach can you confirm whether this is supposed to work with WDA in general?

**Comment by mykola-mokhnach** [comment] 2017-01-18 07:35
@jlipps yes, it works in general, but there is an XCTest issue, that prevents setting values for some PickerWheel controls with special attributes. See my comments to https://github.com/appium/appium/issues/6962 for more details.

**Comment by kcinman11358** [comment] 2017-01-18 17:09
@mykola-mokhnach, thank you very much for providing that. I talked to my dev and had them reimplement the pickerwheel as you suggested and it is now working fine. One thing to note is that the new implementation did change the font size. If someone has an issue again, they should provide us with a screen shot because it is pretty easy to tell if they just have a bad implementation that xcui can't interact with

**Comment by jlipps** [comment] 2017-01-18 17:22
I added a note about PickerWheel api usage in the xcuitest migration doc for further reference.

**Closed by jlipps** 2017-01-18 17:22 UTC

**Comment by chhavisingh** [comment] 2018-05-31 08:18
Any resolution for this?

**Comment by jeetendra50** [comment] 2019-04-04 10:54
> @mykola-mokhnach I have the same issue too. Not able to set value to the picker wheel. I tried 'sendKeys' and 'setValue', none of them worked.
> It seems to be an issue with XCodeUITest. But not sure when apple would fix the issue because issue seems to be there for over an year. In XCodeUITest, setting value to the picker wheel is achieved by tapping also. So I dont think this issue would get any attention by apple.
> 
> Is there any work around from appium side?
> 
> Here is the code that I am using
> List wheels = driver.findElements(MobileBy.className("XCUIElementTypePickerWheel"))
> wheels.get(0).sendKeys("4")

I tried with above workaround, but its not working in my case.
Actually value is selecting in pickerwheel but taking more than  3min time to complete operation.

**Comment by suganeby** [comment] 2019-04-04 14:38
@jeetendra50, I had same issue with the older version. 
I dont see have this issue now in the versions Xcode 10.0, appium 1.9.0. 
What version are you using?

**Comment by suganeby** [comment] 2019-04-04 14:45
@jeetendra50, this is the work around i found for the picker issue in the older version. It worked but little slow if the picker has lot of values.

List wheels = driver.findElements(MobileBy.className("XCUIElementTypePickerWheel"))

Point p1=wheels.get(0).getLocation()
Dimension d1 = wheels.get(0).getSize()

//-100 scrolls up (taps the value below the currently selected value)
driver.tap(1, p1.getX(), p1.getY() + d1.getHeight() -100, 500)

//+100 scrolls down (taps the value above the currently selected value)
driver.tap(1, p1.getX(), p1.getY() +100, 500)

**Comment by jeetendra50** [comment] 2019-04-05 09:10
Thanks for taking time, but this workaround is not working in my case,
Still its taking too much time.

Any one has another solution, I'm running scripts on Browser Stack so not
sure which server version is running, I'll bring more details & let you
know.
