### ISSUE TITLE
Cannot send keys with non-english text when opened keyboard is English (iOS 13.5)

### ISSUE THREAD

**Issue by Phoenix124** [appium/appium#14381] opened 2020-05-26 18:05 UTC
## The problem

Try to sendKeys() non-English text to input. In log text send -  but in input no text typing
When switch to another keyboard - text send to input

## Environment

* Appium version: 1.17.1
* Desktop OS/version used to run Appium: Mac os 10.15.4
* Node.js version (unless using Appium.app|exe): 10.20.1
* Npm or Yarn package manager: 6.14.5
* Mobile platform/version under test: iOS 13.5
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI
## Link to Appium logs

```
[HTTP] --> POST /wd/hub/session/d67b0749-42b5-4ec5-865f-89e8c6f67b98/element/82000000-0000-0000-2167-000000000000/value
[HTTP] {"id":"82000000-0000-0000-2167-000000000000","value":["Йцукен12"]}
[debug] [MJSONWP (d67b0749)] Calling AppiumDriver.setValue() with args: [["Йцукен12"],"82000000-0000-0000-2167-000000000000","d67b0749-42b5-4ec5-865f-89e8c6f67b98"]
[debug] [XCUITest] Executing command 'setValue'
[debug] [WD Proxy] Matched '/element/82000000-0000-0000-2167-000000000000/value' to command name 'setValue'
[debug] [Protocol Converter] Added 'text' property "Йцукен12" to 'setValue' request body
[debug] [WD Proxy] Proxying [POST /element/82000000-0000-0000-2167-000000000000/value] to [POST http://127.0.0.1:8104/session/8E552CBC-E0A1-43B0-8900-776BB49F30E7/element/82000000-0000-0000-2167-000000000000/value] with body: {"value":["Й","ц","у","к","е","н","1","2"],"text":"Йцукен12"}
[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"8E552CBC-E0A1-43B0-8900-776BB49F30E7"}
[debug] [MJSONWP (d67b0749)] Responding to client with driver.setValue() result: null
[HTTP] <-- POST /wd/hub/session/d67b0749-42b5-4ec5-865f-89e8c6f67b98/element/82000000-0000-0000-2167-000000000000/value 200 16701 ms - 76
[HTTP] 
```

**Comment by mykola-mokhnach** [comment] 2020-05-26 18:48
I cannot reproduce the issue with the integration app, tried Japanese and Cyrillic chars - all worked.

**Comment by Phoenix124** [comment] 2020-05-26 19:05
@mykola-mokhnach https://github.com/appium/appium/issues/12618 check this bug, probably the same

**Comment by mykola-mokhnach** [comment] 2020-05-26 19:36
If this happens inside a web view then you could try to change the context. Otherwise I don't have any good suggestions except of reporting it to Apple.

**Comment by Phoenix124** [comment] 2020-05-27 08:06
@mykola-mokhnach I try to do in native context - the same problem

**Comment by Phoenix124** [comment] 2020-05-27 16:16
@mykola-mokhnach btw, I forget to clarify, I type text in secureTextField, try to do this text

**Comment by KazuCocoa** [comment] 2020-05-27 16:28
I forgot which issue, but I saw it was XCTest's behaviour for secureTextField for now

**Comment by mykola-mokhnach** [comment] 2020-05-27 16:36
You could try to copy and paste the actual value into the field as a workaround

**Comment by Phoenix124** [comment] 2020-05-27 16:41
@KazuCocoa yep, the same issue XCTest's

**Comment by mykola-mokhnach** [comment] 2020-05-29 09:07
Closed as third party issue. Consider reporting it to Apple.

**Closed by mykola-mokhnach** 2020-05-29 09:07 UTC
Labels: ThirdParty, XCUITest
