### ISSUE TITLE
Appium doesn't start some simulators on 1.8.0 beta

### ISSUE THREAD

**Issue by mirmitri** [appium/appium#10358] opened 2018-03-16 07:07 UTC
## The problem

Trying to start appium with iPhone 8 simulator fails (also on some others like iPhone 8 plus). But works with iPhone 7.

## Environment

Appium version (or git revision) that exhibits the issue: 1.8.0-beta3
Last Appium version that did not exhibit the issue (if applicable): 1.7,2
Desktop OS/version used to run Appium: macOS Sierra 10.12.6
Node.js version (unless using Appium.app|exe): 9.8.0
Mobile platform/version under test: iOS
Real device or emulator/simulator: Real device 11.2.1
Appium CLI or Appium.app|exe: appium from npm

## Details

An unknown server-side error occurred while processing the command. Original error: Cannot read property 'major' of null

## Link to Appium logs

https://gist.github.com/anonymous/c24724b013affc1d0428214f6baadaaa

## Code To Reproduce Issue
Simple c# code.
https://gist.github.com/mirmitri/649a7c800daa40e939e12158379aa634

**Comment by mykola-mokhnach** [comment] 2018-03-16 08:51
Duplicate of https://github.com/appium/appium/issues/10300. Reinstall your beta to get the fix in

**Closed by mykola-mokhnach** 2018-03-16 08:51 UTC
