### ISSUE TITLE
Add udid to "updateResetArgsFromCaps"

### ISSUE THREAD

**Issue by jamescaldwell** [appium/appium#4283] opened 2014-12-17 22:47 UTC
When continuing an existing session with a different android device/avd, it will not be recognized, as the udid parameter is only recognized if passed on the command line.  When set in desiredCapabilities, it should be set in args as well.

Add line in function updateResetArgsFromCaps:
  this.setArgFromCap("udid", "udid");

**Comment by imurchie** [comment] 2015-02-04 19:53
I cannot reproduce this. I have a simulator and two real devices attached, and can switch between them at will by changing the `udid` I send in the desired capabilities. 

Does this still happen? Does the problem happen during any particular operation?

**Comment by imurchie** [comment] 2015-02-12 02:43
Closing, as there doesn't seem to be any action.

**Closed by imurchie** 2015-02-12 02:43 UTC
Labels: NeedsTriage
