### ISSUE TITLE
Appium problem with exexute UI tests on android images armeabi-v7a 

### ISSUE THREAD

**Issue by karcio** [appium/appium#13041] opened 2019-08-07 10:17 UTC
## The problem
Trying to execute my UI tests using appium/selenium/maven on docker but when I use old architecture armeabi-v7a execution fails when I use x86 all works fine. Reason I use armeabi-v7a that travis or any VM does not support KVM 
https://developer.android.com/studio/run/emulator-acceleration

## Environment
Docker on ubuntu

* Appium version 1.14.1
* Desktop OS/version used to run Appium: Docker on ubuntu 
* Node.js version v10.16.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: ANDROID SYSTEM_API=25, system-images;android-22;google_apis;armeabi-v7a 
* Real device or emulator/simulator: emulator
* Appium CLI : yes 

## Details
[debug] ^[[35m[W3C]^[[39m Error: Command '/root/android-sdk-linux/platform-tools/adb -P 5037 -s emulator-5554 shell pm grant io.appium.settings android.permission.SET_ANIMATION_SCALE \; pm grant io.appium.settings android.permission.CHANGE_CONFIGURATION \; pm grant io.appium.settings android.permission.ACCESS_FINE_LOCATION \;' timed out after 20000ms
[debug] ^[[35m[W3C]^[[39m     at Timeout.setTimeout (/usr/lib/node_modules/appium/node_modules/teen_process/lib/exec.js:106:19)
[debug] ^[[35m[W3C]^[[39m     at ontimeout (timers.js:436:11)
[debug] ^[[35m[W3C]^[[39m     at tryOnTimeout (timers.js:300:5)
[debug] ^[[35m[W3C]^[[39m     at listOnTimeout (timers.js:263:5)
[debug] ^[[35m[W3C]^[[39m     at Timer.processTimers (timers.js:223:10)
^[[35m[HTTP]^[[39m ^[[37m<-- POST /wd/hub/session ^[[39m^[[31m500^[[39m ^[[90m52672 ms - 1403^[[39m

## Link to Appium logs
https://gist.github.com/karcio/57b421a3f6b9d06db9b776075e0ef71b

**Comment by mykola-mokhnach** [comment] 2019-08-07 11:04
> [debug] ^[[35m[ADB]^[[39m Install command stdout: Error: Could not access the Package Manager.  Is the system running?

The emulator on Travis is not just slow - it's super slow. Make sure your emulator is fully booted before starting the tests. Feel free to use https://github.com/appium/appium-adb/blob/master/.travis.yml as an example

**Comment by mykola-mokhnach** [comment] 2019-08-07 11:05
...or switch to Azure ;)

**Comment by karcio** [comment] 2019-08-07 11:11
@mykola-mokhnach 

But those logs I've included are from my docker container on local physical machine, I want to be sure that all is working before I move to travis.

**Comment by mykola-mokhnach** [comment] 2019-08-07 11:20
It does not make much difference. As you can see in the error message emulator boot is completed, but services are still starting and it takes a lot of time. The timeout above is caused by adb itself. Appium was waiting for the command to complete for 20 seconds and didn't get any response.

**Comment by karcio** [comment] 2019-08-07 11:24
ok, 
Should I change those two then? 
caps.setCapability("uiautomator2ServerInstallTimeout", 20000);
caps.setCapability("uiautomator2ServerLaunchTimeout", 20000);

**Comment by mykola-mokhnach** [comment] 2019-08-07 11:35
I'd focus on the root cause rather than on consequences. 20 seconds is already too long for an automated test.

**Comment by mykola-mokhnach** [comment] 2019-08-14 05:48
Closed as not an issue

**Closed by mykola-mokhnach** 2019-08-14 05:48 UTC
Labels: NotABug, Question
