### ISSUE TITLE
Unable to getText value from XCUIElementTypeTextField in Xcode 11

### ISSUE THREAD

**Issue by ganjarpanji** [appium/appium#13594] opened 2019-11-13 05:37 UTC
## The problem
The returned string was `""` empty string.
I tried changing the appium version from 14.beta2 to 15.1 the issue still happens.
Then I tried to revert back from Xcode 11 to Xcode 10.3 and the getText value is successfully performed.

## Environment

* Appium version (or git revision) that exhibits the issue: 14.beta2 15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2019-11-13 06:28
The issue is known and is XCTest regression. Use Xcode 10 SDK to test iOS 12 and below and Xcode11 for iOS13.

Closed as duplicate

**Closed by mykola-mokhnach** 2019-11-13 06:28 UTC

**Comment by ebonom-mfam** [comment] 2022-01-28 13:31
Hi, please I would like to know if there has been any fix to this issue apart from the solution provided by @mykola-mokhnach 3 years ago?

**Comment by diego-epicura** [comment] 2022-12-19 13:34
it's 2022 and I am still experiencing this regression. Can't be possible!

**Comment by lajoshanko** [comment] 2023-02-15 17:21
2023 and still happens.

**Comment by diego-epicura** [comment] 2023-02-16 08:22
> The issue is known and is XCTest regression. Use Xcode 10 SDK to test iOS 12 and below and Xcode11 for iOS13.
> 
> Closed as duplicate

Duplicate of which isssue (link)?
