### ISSUE TITLE
Anddroid application does not start following uiautomator2 driver upgrade from 2.0.1 => 2.7.1

### ISSUE THREAD

**Issue by dlanaghen** [appium/appium#17602] opened 2022-10-12 17:52 UTC
## The problem
Following upgrade of android driver from 2.0.1 => 2.7.1, my mobile application no longer starts when the driver is created.

## Environment

- Appium version (or git revision) that exhibits the issue: v2.0.0-beta.25
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: macOS 12.6
- Node.js version (unless using Appium.app|exe): v17.3.0
- Npm or Yarn package manager: 8.3.0
- Mobile platform/version under test: 2 different android devices
- Real device or emulator/simulator: real device
- Appium CLI or Appium.app|exe: java client 7.6.0

## Details

Yesterday I was dealing with iOS [issue 17596](https://github.com/appium/appium/issues/17596) creating a snapshot file.   Upgrading the xcuitest driver to the latest resolved my problem.  Today, I moved on to android.  I was seeing sporadic issues creating a snapshot as well.  I upgraded the uiautomator2 driver and now my application does not start on either of my 2 android test devices.

When running my test the application, the application normally starts when the driver is created in my test.  Following the appium uiautomator2 driver upgrade, the application never starts on my phone although there is no error indicating any issue in the logs.

Please advise how to provide more useful information.

Also, is it possible to downgrade my driver back to 2.0.1?  If so, what command would I use?

## Link to Appium logs

I have included logs for my [first](https://gist.github.com/dlanaghen/8003db7811149bb0adb8de9b8686e478) device and [second](https://gist.github.com/dlanaghen/68f7a48adc0a2a76e99468455e202cbd) device, but they reveal little.

If you search for the string ` Calling AppiumDriver.findElement() with args: ["id","com.garmin.android.apps.connectmobile:id/toolbar_device_image_view"`, I would expect some kind of error in this neighborhood indicating that the application did not start, but instead it just begins searching for elements

**Comment by mykola-mokhnach** [comment] 2022-10-12 18:15
> 2022-10-12 10:52:01:225 [AndroidUiautomator2Driver@97a4 (cf6f4ed7)] Starting 'com.garmin.android.apps.connectmobile/GCMActivityStartup and waiting for 'com.garmin.android.apps.connectmobile/.myday.MyDayActivity'
> 2022-10-12 10:52:01:225 [ADB] Getting IDs of all 'com.garmin.android.apps.connectmobile' processes
> 2022-10-12 10:52:01:226 [ADB] Running '/Users/lanaghendavid/Library/Android/sdk/platform-tools/adb -P 5037 -s 3336485434393498 shell pgrep -f \(\[\[:blank:\]\]\|\^\)com\.garmin\.android\.apps\.connectmobile\(\[\[:blank:\]\]\|\$\)'
> 2022-10-12 10:52:01:322 [AndroidUiautomator2Driver@97a4 (cf6f4ed7)] 'com.garmin.android.apps.connectmobile' is already running

The app seems to be already running. And since noReset is set to `true`, no changes are applied to it. See https://github.com/appium/appium/issues/17455 for more details. You could call https://github.com/appium/appium-uiautomator2-driver#mobile-activateapp in order to put the app to the foreground

**Comment by jlipps** [comment] 2022-10-12 18:15
Looks like Appium thinks your requested app and activity is already running:

> 2022-10-12 10:52:01:322 [AndroidUiautomator2Driver@97a4 (cf6f4ed7)] 'com.garmin.android.apps.connectmobile' is already running

**Comment by jlipps** [comment] 2022-10-12 18:16
Since you're using an existing app on your device and Appium isn't installing it, it will not stop/restart the app. It will only launch it if it's not running. But it's already running. (I guess just not foregrounded?).

**Comment by dlanaghen** [comment] 2022-10-12 19:18
Interesting.  There is new behavior with this driver. 

I have the following appium desired capabilities for my android app

None of my desired capabilities has changed and my noReset value of true has always been the same.
```
appPackage: com.garmin.android.apps.connectmobile
appActivity: GCMActivityStartup  
appWaitActivity: .myday.MyDayActivity
```

Previously, regardless of whether the application was running or not, or whether it was running in the background or foreground, when a new driver was created, the application would start if needed, come to the foreground, and start on the specified appWaitActivity screen.  Now that is no longer the case.  Instead there are a variety of new behaviors

| Application | Explicit call to activateApp | Outcome |
| --- | --- | --- |
| App not running | not calling activeApp() | Application does not start.  Logs say already running when it is not |
| App not running | call activeApp() | App starts and runs.  But log also says application is already running |
| App in background | not calling activateApp() | Application not brought to foreground. Log says application running | 
| App in background | call activateApp() | Application brought to foreground.  Still on previous screen.  Does not start on .myDay.MyDayActivity |

My iOS version using the current xcuidriver does not require doing any kind of special activateApp and behaves like it used to before the appium driver upgrade.

**Comment by jlipps** [comment] 2022-10-12 19:47
> Application does not start. Logs say already running when it is not

If Appium thinks the app is running but it's not, then there may be a bug in how it is parsing adb output. Can you run the commands that Appium runs to check whether it's running, and verify yourself that Appium is somehow reading them incorrectly?

**Comment by mykola-mokhnach** [comment] 2022-10-12 19:50
> Interesting. There is new behavior with this driver.
> 
> I have the following appium desired capabilities for my android app
> 
> None of my desired capabilities has changed and my noReset value of true has always been the same.
> 
> ```
> appPackage: com.garmin.android.apps.connectmobile
> appActivity: GCMActivityStartup  
> appWaitActivity: .myday.MyDayActivity
> ```
> 
> Previously, regardless of whether the application was running or not, or whether it was running in the background or foreground, when a new driver was created, the application would start if needed, come to the foreground, and start on the specified appWaitActivity screen. Now that is no longer the case. Instead there are a variety of new behaviors
> 
> Application	Explicit call to activateApp	Outcome
> App not running	not calling activeApp()	Application does not start. Logs say already running when it is not
> App not running	call activeApp()	App starts and runs. But log also says application is already running
> App in background	not calling activateApp()	Application not brought to foreground. Log says application running
> App in background	call activateApp()	Application brought to foreground. Still on previous screen. Does not start on .myDay.MyDayActivity
> My iOS version using the current xcuidriver does not require doing any kind of special activateApp and behaves like it used to before the appium driver upgrade.

Have you checked the issue link above? There was a bugfix to align the driver behavior with other drivers for noReset=true.

**Comment by mykola-mokhnach** [comment] 2022-10-12 19:51
Closed as duplicate of https://github.com/appium/appium/issues/17594

**Closed by mykola-mokhnach** 2022-10-12 19:51 UTC
Labels: NotABug, UIAutomator2, NeedsInfo
