### ISSUE TITLE
Unable to connect to running WebDriverAgent

### ISSUE THREAD

**Issue by BenjaminFausett** [appium/appium#8158] opened 2017-04-03 14:43 UTC
## The problem

Unable to connect to running WebDriverAgent: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta.2
* Desktop OS/version used to run Appium: Sierra 10.12.4
* Node.js version (unless using Appium.app|exe): 6.10.1
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/BenjaminFausett/893ceec555c5068ec9b71b45a808f8fe

**Comment by imurchie** [comment] 2017-04-03 15:05
Can you turn on xcode logging (set the desired capability `showXcodeLog` to `true`) and check the logs again?

**Comment by mykola-mokhnach** [comment] 2017-04-03 15:17
Duplicate of https://github.com/appium/appium/issues/8149

**Comment by BenjaminFausett** [comment] 2017-04-03 15:20
Logs with showXcodeLog set to true:

https://gist.github.com/BenjaminFausett/29f7075970e7ae250bb44985365e129d

**Comment by cbalea** [comment] 2017-04-04 10:39
I see that @BenjaminFausett is using the same OS X version as myself: 10.12.4 in the duplicate bug of #8149. 

I've tested the same setup on OS X 10.12 and everything is working correctly.

@mykola-mokhnach, @imurchie is there a chance that the 10.12.4 OS X update has introduced this problem?

**Comment by imurchie** [comment] 2017-04-04 11:26
It totally could be. I'm on the same system, and I see the same problem for 10.1 and 10.2 tests. 10.3 works fine.

Unfortunately Xcode 8.3 was also released at the same time so that is another moving part. I'm going to try things out on an older machine.

**Comment by cbalea** [comment] 2017-04-04 11:28
To diminish moving parts, you can downgrade Xcode to 8.2.1. I did this and it always replicates the issue.

**Comment by imurchie** [comment] 2017-04-04 11:29
But in his logs he's still got xcode command line tools version 8.3.

**Comment by cbalea** [comment] 2017-04-04 11:31
How about my logs in #8149 ?

**Comment by imurchie** [comment] 2017-04-04 11:32
Yes:
```
[debug] [XCUITest] Xcode version set to '8.2.1' (tools v8.3.0.0.1.1490382677)
```

**Comment by cbalea** [comment] 2017-04-04 11:58
@imurchie I can confirm that using command line tools still reproduces the issue.

I've downgraded to `[debug] [XCUITest] Xcode version set to '8.2.1' (tools v8.2.0.0.1.1480973914)` but still cannot run WDA.

**Comment by imurchie** [comment] 2017-04-04 12:07
Alrighty! Thanks!

**Comment by BenjaminFausett** [comment] 2017-04-04 12:27
Success! I was able to start WDA and run a test by changing my Xcode version from 8.2.1 to 8.3!

I have included the logs from the success if that is helpful for anyone.

https://gist.github.com/BenjaminFausett/d6c6554525933309764c1dc740086d73

**Comment by imurchie** [comment] 2017-04-04 12:29
The tests run fine with the latest drivers on the following configuration.
* MacOS 10.11.6
* iOS 10.2
* Xcode 8.2.1

I'm going to upgrade Xcode and see if 10.2 still works.

**Comment by imurchie** [comment] 2017-04-04 12:29
@BenjaminFausett 10.3 seems to work perfectly fine in my experience. Can you try running a 10.2 test (or a bunch, since it is not immediate always).

**Comment by imurchie** [comment] 2017-04-04 13:58
Using my wife's computer I was able to verify that this following configuration works:
* MacOS 10.12.3
* iOS 10.2
* Xcode 8.3

So it would appear the problem is with the MacOS 10.12.4 update.

**Comment by cbalea** [comment] 2017-04-04 14:07
On OS X 10.12.3 + XCode 8.2.1 everything was working ok for me. It has to be something in the MacOS 10.12.4 update.

**Comment by imurchie** [comment] 2017-04-04 14:10
Yes. :(

**Comment by cbalea** [comment] 2017-04-04 16:21
I managed to get success with the following configuration:
- Mac OS 10.12.4
- iOS 10.3
- Xcode 8.3
- App built with Xcode 8.2.1 (iOS sdk 10.2)

**Comment by imurchie** [comment] 2017-04-04 16:23
Yes, iOS 10.3 seems to work fine.

**Closed** 2017-04-05 08:43 UTC
Labels: NeedsTriage

**Comment by cbalea** [comment] 2017-04-05 10:20
@mykola-mokhnach how come the bug is closed? Don't we need to support ios 10.2 simulators?

**Comment by mykola-mokhnach** [comment] 2017-04-05 10:29
This is not Appium bug, but rather WDA or even XCTest itself. We cannot do anything to fix it - only acknowledge the fact and propose a workaround.

**Comment by cbalea** [comment] 2017-04-05 11:35
Ok. If a workaround will be found, that's good. We'd need to support all ios 10 versions.

**Comment by mayukataoka** [comment] 2017-04-19 20:22
I am not using OS 10.12.4  yet, but I was getting the same error intermittently when running multiple tests.  

-iOS Simulator 10.2
-Mac OS 10.12.3
-Xcode 8.3

I was using --full-reset flag.  If I stop using this flag, it consistently connects to WebDriverAgent.  Hope this helps if anyone else is having the same issue.

**Comment by zhzhl1993** [comment] 2017-05-31 05:41
I have received same error when running testing ,but I solved it by reinstall webpack.   run `npm i -g webpack` in terminal or reinstall all environmental include carthage and WebDriverAgent ,it may be perfect for you!

**Comment by vaznoe** [comment] 2017-08-15 16:05
I have a problem with 
[MJSONWP] Encountered internal error running command: Error: Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100

Link to Appium logs: https://gist.github.com/vaznoe/8473bcc4bc6b95c3a891a11f77e58ef5
please help me

**Comment by Sbdkg** [comment] 2019-01-10 11:08
Facing same issue for below configurations:

Mac OS – macOS High Sierra (10.13.6)
XCode : 10.1 beta
iPhone used – Model 5S (real device)
iOS version – 10.3.1
Appium used : v1.10.0

Please assist.
