### ISSUE TITLE
Unable to tap ‘search’ button on Android softKeyboard for searching text in Global Search box

### ISSUE THREAD

**Issue by aman-daharwal** [appium/appium#10996] opened 2018-07-04 10:24 UTC
## The problem

I am trying to search a keyword in search box which doesn't have search icon, searching of text only happen via `search button` in Android soft Keyboard, but the appium libraries doesn't have any Key or key event for `search button`.
I tried with `Enter` key but the whole entered text get selected and get erased after pressing `Enter` Key/ after executing below line

`driver.getKeyboard().pressKey(Keys.ENTER);` or `driver.getKeyboard().sendKeys(Keys.ENTER);`

Screen shot image link : https://www.screencast.com/t/3jmV7bqzg

## Environment

<groupId>io.appium</groupId>
<artifactId>java-client</artifactId>
<version>5.0.4</version>

 <groupId>org.seleniumhq.selenium</groupId>
 <artifactId>selenium-java</artifactId>
 <version>3.11.0</version>

With Android Device Version 7.1.1

## Link to Appium logs

https://gist.github.com/aman-daharwal/b34cb9695fe22bed278e1c2bd70e5a3e

## Code To Reproduce Issue [ Good To Have ]

@FindBy(id = "com.ebay.mobile:id/search_src_text")
WebElement globalSearchBox;

globalSearchBox.sendKeys(text);

driver.getKeyboard().sendKeys(Keys.ENTER);

Kindly advice if anything else is required

**Comment by mykola-mokhnach** [comment] 2018-07-04 10:29
Duplicate of https://github.com/appium/appium/issues/10989

**Closed by mykola-mokhnach** 2018-07-04 10:29 UTC

**Comment by aman-daharwal** [comment] 2018-07-04 10:51
@mykola-mokhnach I don't see any progress or anything new on duplicated issues, it seems to me a feature missing for search button or a bug on appium side, as `search button` is available on Android Keyboard, 
and also other framework/tools do support such kind of searching

**Comment by mykola-mokhnach** [comment] 2018-07-04 15:03
> other framework/tools do support such kind of searching

Any examples please

**Comment by aman-daharwal** [comment] 2018-07-05 05:02
@mykola-mokhnach 

If you have used **Robotium**, which allows users to press Android Soft keys

Robotium 5.1 proudly presents to you `pressSoftKeyboardSearchButton()`
and for earlier versions we with 2-3 lines of code this can be achieved simply.

I hope **appium** will introduce this feature in incoming versions and will provide some simple workaround to overcome this in current and previous versions.

**Comment by mykola-mokhnach** [comment] 2018-07-05 05:28
I've checked Robotium source and found this: https://github.com/RobotiumTech/robotium/blob/b69dcf740baabec48c91999e523377faef79682e/robotium-solo/src/main/java/com/robotium/solo/Presser.java

The key difference here is that Robotium has access to the application views hierarchy unlike UIA2 framework, where can only rely on the accessibility hierarchy. This means it is technically impossible to do the same in Appium (at least for UIA driver), so we try to generate the event on the lower level by emulating the corresponding hardware input action. If this does not work for you then I don't think anything else would work.
