### ISSUE TITLE
Unable to create session for android in appium

### ISSUE THREAD

**Issue by Dhansv** [appium/appium#14340] opened 2020-05-15 03:58 UTC
## The problem

I am trying to create a session in appium by adding the desired capabilities but when I click on create session, I am getting the following error message

**An unknown server-side error occurred while processing the command. 
Original error: Error executing adbExec.
Original error: 'Command 'C:\\Users\\xxxxx\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s b8d1c2880904 shell pm install -g /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk' exited with code 1'; 
Stderr: 'Error: java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag'; Code: '1'**

## Environment

* Appium version 1.15.1
* Desktop OS/version used to run Appium: 10
* Node.js version 8.12.0
* Npm 6.4.1
* Mobile platform/version under test:  8.1.0 OPM1.171017.018
* Real device: Redmi Note 5
* Android Studio version: 3.6.3

Thanks in advance...

**Comment by KazuCocoa** [comment] 2020-05-15 04:57
Could you share the full Appium log as GIST?

**Comment by mykola-mokhnach** [comment] 2020-05-15 05:29
Duplicate of #11197

Please replace the device under test, since this one has modified firmware, which does not support all features, that a stock Android firmware does.

**Closed by mykola-mokhnach** 2020-05-15 05:29 UTC
Labels: NeedsInfo, NotABug

**Comment by Dhansv** [comment] 2020-05-15 06:00
> Could you share the full Appium log as GIST?

yes, please find below,

[info] [35m[Appium][39m Welcome to Appium v1.15.1
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/sessions[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[GENERIC][39m Calling AppiumDriver.getSessions() with args: []
[debug] [35m[GENERIC][39m Responding to client with driver.getSessions() result: []
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/sessions [39m[32m200[39m [90m6 ms - 40[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"appActivity":"com.android.settings.Settings","appPackage":"com.android.settings","deviceName":"b8d1c2880904","platformName":"Android","platformVersion":"8.1","newCommandTimeout":0,"connectHardwareKeyboard":true}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"appActivity":"com.android.settings.Settings","appPackage":"com.android.settings","deviceName":"b8d1c2880904","platformName":"Android","platformVersion":"8.1","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1589521940863 (11:22:20 GMT+0530 (India Standard Time))
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m ======================================================================
[warn] [35m[Appium][39m   DEPRECATION WARNING:
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   The 'automationName' capability was not provided in the desired 
[warn] [35m[Appium][39m   capabilities for this Android session
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   Setting 'automationName=UiAutomator2' by default and using the 
[warn] [35m[Appium][39m   UiAutomator2 Driver
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   The next major version of Appium (2.x) will **require** the 
[warn] [35m[Appium][39m   'automationName' capability to be set for all sessions on all 
[warn] [35m[Appium][39m   platforms
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   In previous versions (Appium <= 1.13.x), the default was 
[warn] [35m[Appium][39m   'automationName=UiAutomator1'
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   If you wish to use that automation instead of UiAutomator2, please 
[warn] [35m[Appium][39m   add 'automationName=UiAutomator1' to your desired capabilities
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   For more information about drivers, please visit 
[warn] [35m[Appium][39m   http://appium.io/docs/en/about-appium/intro/ and explore the 
[warn] [35m[Appium][39m   'Drivers' menu
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m ======================================================================
[warn] [35m[Appium][39m 
[info] [35m[Appium][39m Appium v1.15.1 creating new AndroidUiautomator2Driver (v1.37.2) session
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {
[debug] [35m[BaseDriver][39m   "appActivity": "com.android.settings.Settings",
[debug] [35m[BaseDriver][39m   "appPackage": "com.android.settings",
[debug] [35m[BaseDriver][39m   "deviceName": "b8d1c2880904",
[debug] [35m[BaseDriver][39m   "platformName": "Android",
[debug] [35m[BaseDriver][39m   "platformVersion": "8.1",
[debug] [35m[BaseDriver][39m   "newCommandTimeout": 0,
[debug] [35m[BaseDriver][39m   "connectHardwareKeyboard": true
[debug] [35m[BaseDriver][39m }
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
[warn] [35m[BaseDriver][39m   connectHardwareKeyboard
[info] [35m[BaseDriver][39m Session created with session id: 1950e54f-9f96-4fd1-851d-96c7ac8c98cb
[info] [35m[UiAutomator2][39m Starting 'com.android.settings' directly on the device[info] [35m[ADB][39m Found 1 'build-tools' folders under 'C:\Users\xxxx\AppData\Local\Android\Sdk' (newest first):
[info] [35m[ADB][39m     C:/Users/xxxx/AppData/Local/Android/Sdk/build-tools/29.0.3
[info] [35m[ADB][39m Using 'adb.exe' from 'C:\Users\xxxx\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices...[debug] [35m[ADB][39m Connected devices: [{"udid":"b8d1c2880904","state":"device"}]
[info] [35m[AndroidDriver][39m Looking for a device with Android '8.1'
[debug] [35m[ADB][39m Setting device id to b8d1c2880904
[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running 'C:\Users\xxxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s b8d1c2880904 shell getprop ro.build.version.release'[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 8.1.0
[info] [35m[AndroidDriver][39m Using device: b8d1c2880904
[info] [35m[ADB][39m Using 'adb.exe' from 'C:\Users\xxxx\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[debug] [35m[ADB][39m Setting device id to b8d1c2880904
[debug] [35m[ADB][39m Running 'C:\Users\xxxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s b8d1c2880904 shell getprop ro.build.version.sdk'[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 27
[debug] [35m[ADB][39m Device API level: 27
[warn] [35m[AndroidDriver][39m No app sent in, not parsing package/activity
[debug] [35m[ADB][39m Running 'C:\Users\xxxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s b8d1c2880904 wait-for-device'[debug] [35m[ADB][39m Running 'C:\Users\xxxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s b8d1c2880904 shell echo ping'[debug] [35m[AndroidDriver][39m Pushing settings apk to device...
[debug] [35m[ADB][39m Getting install status for io.appium.settings
[debug] [35m[ADB][39m Running 'C:\Users\xxxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s b8d1c2880904 shell dumpsys package io.appium.settings'[debug] [35m[ADB][39m 'io.appium.settings' is not installed
[debug] [35m[ADB][39m App 'C:\Users\xxxx\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk' is not installed
[debug] [35m[ADB][39m Installing 'C:\Users\xxxx\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[debug] [35m[ADB][39m Running 'C:\Users\xxxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s b8d1c2880904 shell 'ls -t -1 /data/local/tmp/appium_cache 2>&1 || echo _ERROR_''[debug] [35m[ADB][39m The count of applications in the cache: 2
[info] [35m[ADB][39m The application at 'C:\Users\xxxx\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk' is already cached to '/data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk'
[debug] [35m[ADB][39m Running 'C:\Users\xxxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s b8d1c2880904 shell pm install -g /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk'[debug] [35m[ADB][39m Getting install status for io.appium.settings
[debug] [35m[ADB][39m Running 'C:\Users\xxxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s b8d1c2880904 shell dumpsys package io.appium.settings'[debug] [35m[ADB][39m 'io.appium.settings' is not installed
[debug] [35m[ADB][39m App 'C:\Users\xxxx\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk' is not installed
[debug] [35m[ADB][39m Installing 'C:\Users\xxxx\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[debug] [35m[ADB][39m Running 'C:\Users\xxxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s b8d1c2880904 shell 'ls -t -1 /data/local/tmp/appium_cache 2>&1 || echo _ERROR_''[debug] [35m[ADB][39m The count of applications in the cache: 2
[info] [35m[ADB][39m The application at 'C:\Users\xxxx\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk' is already cached to '/data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk'
[debug] [35m[ADB][39m Running 'C:\Users\xxxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s b8d1c2880904 shell pm install -g /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk'[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 session
[debug] [35m[ADB][39m Running 'C:\Users\xxxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s b8d1c2880904 shell am force-stop com.android.settings'[debug] [35m[ADB][39m Removing forwarded port socket connection: 8200 
[debug] [35m[ADB][39m Running 'C:\Users\xxxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s b8d1c2880904 forward --remove tcp\:8200'[warn] [35m[UiAutomator2][39m Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'C:\\Users\\xxxx\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s b8d1c2880904 forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb.exe: error: listener 'tcp:8200' not found'; Code: '1''
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1589521947117 (11:22:27 GMT+0530 (India Standard Time))
**[debug] [35m[MJSONWP][39m Encountered internal error running command: Error executing adbExec. Original error: 'Command 'C:\\Users\\xxxx\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s b8d1c2880904 shell pm install -g /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk' exited with code 1'; Stderr: 'Error: java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag'; Code: '1'**
[debug] [35m[MJSONWP][39m Error: Command 'C:\\Users\\xxxx\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s b8d1c2880904 shell pm install -g /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk' exited with code 1
[debug] [35m[MJSONWP][39m     at ChildProcess.proc.on.code (C:\Users\xxxx\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\teen_process\lib\exec.js:113:19)
[debug] [35m[MJSONWP][39m     at ChildProcess.emit (events.js:182:13)
[debug] [35m[MJSONWP][39m     at maybeClose (internal/child_process.js:961:16)
[debug] [35m[MJSONWP][39m     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m6256 ms - 617[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mDELETE[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[HTTP][39m No route found. Setting content type to 'text/plain'
[info] [35m[HTTP][39m [37m<-- DELETE /wd/hub/session [39m[33m404[39m [90m3 ms - 57[39m
[info] [35m[HTTP][39m [90m[39m

**Comment by KazuCocoa** [comment] 2020-05-15 06:14
`-g` option in installing should work Android 23+ according to Android documentation, but the device seems did not allow. (by the manufacture's limitation?)

`autoGrantPermissions: false` may work, but Appium does not work fully. `mobile:getPermissions` and `mobile:changePermissions` http://appium.io/docs/en/commands/mobile-command/ probably help to grant permissions after the launch.

But replacing the device is easier to work as Mykola suggested.
