### ISSUE TITLE
Appium server stops actions arbitrarily, resumes when physically clicking the simulator or waiting more than usual

### ISSUE THREAD

**Issue by Joskony** [appium/appium#11193] opened 2018-08-16 11:42 UTC
## The problem

I wrote a test suite that is able to test several browser games of the same kind on several devices, can't go in to detail here. What usually happens is that my suite tests the games for their basic functionalities. This usually happens in a matter of seconds. But now I've noticed, that with some games the Appium server takes ages to issue the next command. This problem only happens on an iOS simulator. Now this could be an issue on my end or with the games, which are all really identical to each other by the way. But the thing that makes it hard for me to pinpoint the issue is, that as soon as the Appium server stops issuing/receiving commands it can be activated again by literately clicking inside the simulator window. I basically have to click several times to run through this one test instance, after that it works again for a while.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2-beta (Previously on 1.8.1)
* Last Appium version that did not exhibit the issue (if applicable): / (Would need to try older versions with the specific games, this has not been an issue in the past)
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 10.5.0
* Mobile platform/version under test: iPhone SE/7/X - 11.2/9.3
* Real device or emulator/simulator: Simulator 

## Link to Appium logs

 [logs](https://gist.github.com/Joskony/12233f06431430fdb6be6bcf3650139f)

**Comment by mykola-mokhnach** [comment] 2018-08-16 19:08
Can you please point at which exact log line the freeze happens?

@imurchie https://gist.github.com/Joskony/12233f06431430fdb6be6bcf3650139f#file-appium-log-L612 looks quite suspicious

**Comment by Joskony** [comment] 2018-08-18 15:17
https://gist.github.com/Joskony/12233f06431430fdb6be6bcf3650139f#file-appium-log-L3011

The issue might have been initiated earlier, but as you can see the line after the linked command is executed 6 minutes later. Other than the absurd time frame I couldn't see anything suspicious about it.

**Comment by mykola-mokhnach** [comment] 2018-08-18 16:26
Does it help if you set `safariGarbageCollect` to false?

**Comment by Joskony** [comment] 2018-08-20 08:49
> Does it help if you set safariGarbageCollect to false?
Tried it, without success.

What also happens is the following: One would expect the server to timeout after a while, but as seen in the previous logs it does not. But in the following an error is being thrown when executing a timeout. 

https://gist.github.com/Joskony/6c4b4d3225859a3ceca38ed68caded57#file-appium_2-log-L58

This happened regardless of safariGarbageCollect turned on or off, I just forgot about it since it doesn't always happen. Do you want full logs with safariGarbageCollect on false? They look pretty much the same and freeze at the same position as well.

**Comment by mykola-mokhnach** [comment] 2018-08-20 09:36
Can you also try to get the IOS logs for the time when the freeze happens?

**Comment by Joskony** [comment] 2018-08-20 10:01
Here are the full appium logs with safariGarbageCollect on false.
https://gist.github.com/Joskony/5530d81087144cabbc65edfdab9daa3d

And here is a part of the iOS logs.
https://gist.github.com/Joskony/a086a0d00306e013266e80ddd41d2e21

**Comment by mykola-mokhnach** [comment] 2018-08-20 10:16
These device logs don't contain any details. Please enable `showIOSLog` capability and try again

**Comment by mykola-mokhnach** [comment] 2018-08-20 10:17
Also, please enable timestamps there

**Comment by Joskony** [comment] 2018-08-20 10:56
This should be what you wanted:

https://gist.github.com/Joskony/a8b597c35193deb2c7352569bb7764f3

At the very beginning one successful test ran through, the freeze should be a bit before 10:30:04:536 and at 10:38:22:538 I clicked in to the simulator to see what happens in the logs.

**Comment by mykola-mokhnach** [comment] 2018-08-20 12:48
I don't see 10:30 there. The log finishes at `2018-08-20 10:29:23:627`

**Comment by Joskony** [comment] 2018-08-20 12:52
Gist shortened the file. You should have the option to view the full file at the start of the gist. Otherwise here is the full file:

https://gist.githubusercontent.com/Joskony/a8b597c35193deb2c7352569bb7764f3/raw/338842a34d0146659b926a914370b98072397e11/appium_ios.log

**Comment by mykola-mokhnach** [comment] 2018-08-20 13:33
I don't observe any visible problems in the log. Perhaps the issue is somehow related with frames switching and high CPU usage by WebKit, but I cannot say anything for sure. It could be @imurchie knows more

**Comment by mykola-mokhnach** [comment] 2018-09-13 05:35
Closed as third party issue

**Closed by mykola-mokhnach** 2018-09-13 05:35 UTC
Labels: Mobile Safari, ThirdParty
