### ISSUE TITLE
TouchAction move_to() uses relative coordinates and does not accept negative values 

### ISSUE THREAD

**Issue by alexvlade** [appium/appium#5243] opened 2015-06-11 08:44 UTC
If I try to drag, wait and drop element in other place it always counts coordinates relative to place where I dragged element. So basically in code below it will move element 50px to right and 50px down from current position, but not to absolute coordinate on screen (as it should be).
In addition, it doesn't accept negative values, so if I put -50, it will throw an exception that coordinates are wrong.
Reproducible on Android, didn't check how it works on iOS.
My code:

``` python
action = TouchAction(driver)
action.press(element).wait(ms=500)
action.move_to(x=50, y=50)
action.wait(ms=800).release().perform()
```

**Comment by sebv** [comment] 2015-06-11 08:54
is it on iOS or Android?

**Comment by alexvlade** [comment] 2015-06-11 08:58
It's on Android.

**Comment by sebv** [comment] 2015-06-11 09:00
It's probably a duplicate of this: https://github.com/appium/appium/issues/3021 , but I didn't about the negative being rejected.

ping @jlipps we should probably bump this bug priority.

**Comment by alexvlade** [comment] 2015-06-11 09:10
#3021 says "on Android it uses absolute coordinates" which is not true (or maybe it used to be some time ago). So yep, I have nothing against merging these two issues in one, but then we need change description, so it affects both platforms.

**Comment by sebv** [comment] 2015-06-11 09:23
Let wait for @imurchie  he'll know better about those issues.

**Comment by imurchie** [comment] 2015-06-11 16:27
The statement quoted from the JavaDoc is wrong (and was [updated](https://github.com/appium/java-client/commit/d7874ca6b93f3e72f612402beea61964033ce9fe)). Android uses relative coordinates. I will look into the rejection of negative values for `x` and `y`. That should not be.

**Comment by BenWaller** [comment] 2015-06-29 20:45
I've been able to reproduce this issue. Negative values won't work with the relative touchActions as in the case below where I move up 7, and right 52 for the last part of this circle I'm drawing. I'm using java-client:2.1.0 and appium 1.4.3

        int sides = 50;
        double step = 2*Math.PI/sides;
        int h = maxWidth / 2;
        int k = maxHeight / 3;
 touchAction.press(h, k);
for(double theta=0;  theta < 2*Math.PI;  theta+=step) {

            int xDelta = (int)Math.round(radius*Math.cos(theta));
            int yDelta = (int)Math.round(radius*Math.sin(theta));

            touchAction.moveTo(xDelta, yDelta);
        }
        touchAction.release().perform();

If I were to change the for loop to "for(double theta=0;  theta < Math.PI/2;  theta+=step)" It works fine, because all of the relative movements are in the positive direction (first quarter of the circle being drawn clockwise)

info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":488,"y":599}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":488,"y":599}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1776]
info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 488, y: 599
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":540,"y":592}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":540,"y":592}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1776]
info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 540, y: 592
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":540,"y":592}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":540,"y":592}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1776]
info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 540, y: 592
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
info: [debug] Pushing command to appium work queue: ["element:touchUp",{"x":52,"y":-7}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchUp","params":{"x":52,"y":-7}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchUp
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1776]
info: [debug] Responding to client with error: {"status":29,"value":{"message":"The coordinates provided to an interactions operation are invalid.","origValue":"Coordinate [x=52.0, y=-7.0] is outside of element rect: [0,0][1080,1776]"},"sessionId":"e7507050-5ce0-4d47-816b-4ac8585ba142"}
info: <-- POST /wd/hub/session/e7507050-5ce0-4d47-816b-4ac8585ba142/touch/perform 500 1442.335 ms - 240 
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":29,"value":"Coordinate [x=52.0, y=-7.0] is outside of element rect: [0,0][1080,1776]"}
info: --> DELETE /wd/hub/session/e7507050-5ce0-4d47-816b-4ac8585ba142 {}
info: Shutting down appium session

**Comment by BenWaller** [comment] 2015-07-17 13:28
@imurchie Is there anything else I can provide to help with this issue?

**Comment by SrinivasanTarget** [comment] 2016-11-11 18:00
@triager please close. Closing this because of inactivity.

**Closed by SrinivasanTarget** 2016-11-11 18:00 UTC
Labels: OnGoing, ReproNeeded
