### ISSUE TITLE
Appium fails to find element by id on Mobile Web Browser apps

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#16293] opened 2022-01-02 14:18 UTC
## The problem
The app which I am trying to run is a web app that is running on my android device browser (chrome browser) 

I am getting an appium server error when performing find by id:
```
[W3C (80312f1a)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/80312f1a-f720-43b4-9b14-ad5cef6ecf91/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/80312f1a-f720-43b4-9b14-ad5cef6ecf91/element] to [POST http://127.0.0.1:8001/wd/hub/session/8e5e03396c7402b509dc2c9c17ba06c8/element] with body: {"using":"id","value":"input-username-login"}
[WD Proxy] Got response with status 400: {"value":{"error":"invalid argument","message":"invalid argument: invalid locator\n  (Session info: chrome=96.0.4664.104)","stacktrace":"0   chromedriver                        0x00000001058cc269 __gxx_personality_v0 + 582729\n1   chromedriver                        0x0000000105857c33 __gxx_personality_v0 + 106003\n2   chromedriver                        0x0000000105414e28 chromedriver + 171560\n3   chromedriver                        0x0000000105449e21 chromedriver + 388641\n4   chromedriver                        0x000000010544a591 chromedriver + 390545\n5   chromedriver                        0x000000010547c6b4 chromedriver + 595636\n6   chromedriver                        0x00000001054679fd chromedriver + 510461\n7   chromedriver                        0x000000010547a462 chromedriver + 586850\n8   chromedriver                        0x0000000105467c23 chromedriver + 511011\n9   chromedriver                        0x000000010543d75e chromedriver + 337758\n10  chromedriver                        0x000000...
[debug] [W3C] Matched W3C error code 'invalid argument' to InvalidArgumentError
[HTTP] <-- POST /wd/hub/session/80312f1a-f720-43b4-9b14-ad5cef6ecf91/element 400 26 ms - 1937
```

## Important note
When I am calling to `driver.find_element_by_tag_name('input')` and then looping the result I am getting back tag which I want with the expected id: `input-username-login`.
But when I am searching directly the element with find_element_by_id I do not get a result. 

My tag looks as follow:
```
<div class="mat-form-field-infix ng-tns-c72-3"><input
                                                                _ngcontent-ctj-c81="" type="email" matinput=""
                                                                formcontrolname="username" id="input-username-login"
                                                                autocomplete="username"
                                                                class="mat-input-element mat-form-field-autofill-control ng-tns-c72-3 ng-untouched ng-pristine ng-valid cdk-text-field-autofill-monitored"
                                                                aria-invalid="false" aria-required="false"><span
                                                                class="mat-form-field-label-wrapper ng-tns-c72-3"><label
                                                                class="mat-form-field-label ng-tns-c72-3 mat-empty mat-form-field-empty ng-star-inserted"
                                                                id="mat-form-field-label-3" for="input-username-login"
                                                                aria-owns="input-username-login"><!----><mat-label
                                                                _ngcontent-ctj-c81=""
                                                                class="ng-tns-c72-3 ng-star-inserted">
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.1
* Last Appium version that did not exhibit the issue (if applicable): Never
* Desktop OS/version used to run Appium: Mac os
* Node.js version (unless using Appium.app|exe): 16.13.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: android
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://github.com/bwomsm1/AppiumLogs/blob/master/appium_web_browser.log

**Comment by mykola-mokhnach** [comment] 2022-01-02 14:29
Duplicate of https://github.com/appium/appium/issues/13999

**Closed by mykola-mokhnach** 2022-01-02 14:29 UTC

**Comment by bwomsm1** [comment] 2022-01-02 16:33
@mykola-mokhnach sorry, but I really did not manage to understand what is the solution from #13999 ticket.

**Comment by bwomsm1** [comment] 2022-01-02 18:45
@mykola-mokhnach I am trying to start the appium session with `w3s=False` but without any success,
Do you mind instructing me with that?

**Comment by KazuCocoa** [comment] 2022-01-02 18:50
It was because W3C spec no longer supports the `id` locator in WebContext. (I mean by chromedriver)
The fact in selenium clients converts some of the legacy locators to CSS one as https://github.com/appium/python-client/blob/master/appium/webdriver/webdriver.py#L427-L437 , but Appium needs them for the native context.

So Appium clients do not do such hacks inside clients. If you could not find Web elements with W3C compatible locators, probably chromedriver itself cannot find them.

**Comment by bwomsm1** [comment] 2022-01-02 19:14
Thanks @KazuCocoa ,
Can I run Appium with other browsers on the Android device? Like Edge/Safari?

**Comment by KazuCocoa** [comment] 2022-01-02 22:03
It depends on if they can work with chromedriver (WEBVIEW context in Appium) or native context.
https://appium.io/docs/en/writing-running-appium/web/hybrid/

They might have technical limitation for it (by Android's design)
