### ISSUE TITLE
bug: getPageSource is stuck on iOS simulator 17.0 and xcode 15

### ISSUE THREAD

**Issue by PencuAlex** [appium/appium#19429] opened 2023-11-17 13:49 UTC
The getPageSource() method is loading indefinitely.
- Appium version 2.2.2 
- XCUITest version 5.8.2

Logs:
[XCUITestDriver@956a (13a21898)] Executing command 'getTimeouts'
[Xcode] 2023-11-17 15:41:06.735666+0200 WebDriverAgentRunner-Runner[6163:59070] Cannot take a snapshot with attribute(s) (
[Xcode]     "XC_kAXXCAttributeLabel",
[Xcode]     "XC_kAXXCAttributeTraits",
[Xcode]     "XC_kAXXCAttributeHorizontalSizeClass",
[Xcode]     "XC_kAXXCAttributePlaceholderValue",
[Xcode]     "XC_kAXXCAttributeBannerIsStickyAttribute",
[Xcode]     "XC_kAXXCAttributeIdentifier",
[Xcode]     "XC_kAXXCAttributeWindowDisplayId",
[Xcode]     "XC_kAXXCAttributeIsUserInteractionEnabled",
[Xcode]     "XC_kAXXCAttributeURL",
[Xcode]     "XC_kAXXCAttributeUserTestingElements",
[Xcode]     "XC_kAXXCAttributeHasNativeFocus",
[Xcode]     "XC_kAXXCAttributeVerticalSizeClass",
[Xcode]     "XC_kAXXCAttributeTruncatedValue",
[Xcode]     "XC_kAXXCAttributeViewControllerTitle",
[Xcode]     "XC_kAXXCAttributeFrame",
[Xcode]     "XC_kAXXCAttributeWindowContextId",
[Xcode]     "XC_kAXXCAttributeSystemAutomationProperties",
[Xcode]     "XC_kAXXCAttributeParent",
[Xcode]     "XC_kAXXCAttributeAutomationType",
[Xcode]     "XC_kAXXCAttributeViewControllerClassName",
[Xcode]     "XC_kAXXCAttributeElementType",
[Xcode]     "XC_kAXXCAttributeElementBaseType",
[Xcode]     "XC_kAXXCAttributeIsVisible"
[Xcode] 
[Xcode] ) of 'XCUIElementTypeAny' after 15.00 seconds
[Xcode] 2023-11-17 15:41:06.737059+0200 WebDriverAgentRunner-Runner[6163:59070] This timeout could be customized via 'customSnapshotTimeout' setting
[Xcode] 2023-11-17 15:41:06.738056+0200 WebDriverAgentRunner-Runner[6163:59070] Internal error: Error kAXErrorIPCTimeout getting snapshot for element <AXUIElementRef 0x600000c4c090> {pid=9285} {uid=[ID:1 hash:0x0]}
[Xcode] 2023-11-17 15:41:06.738291+0200 WebDriverAgentRunner-Runner[6163:59070] Falling back to the default snapshotting mechanism for the element 'XCUIElementTypeAny' (some attribute values, like visibility or accessibility might not be precise though)
[Xcode]

**Comment by mykola-mokhnach** [comment] 2023-11-17 14:14
Duplicate of https://github.com/appium/appium/issues/19382

**Closed by mykola-mokhnach** 2023-11-17 14:14 UTC
Labels: Bug, Needs Triage
