### ISSUE TITLE
Appium continues test run while WDA is building

### ISSUE THREAD

**Issue by mel-OR** [appium/appium#14190] opened 2020-04-16 16:31 UTC
## The problem

I am running my tests via webdriverio and rely on its service to kick off appium. When I start my tests from a fresh project build, it pulls appium-webdriveragent and downloads and builds the required XCode projects for YYCache and RoutingHTTPServer. However, this seems to be taking much longer after my Xcode 11.4 upgrade and my tests then fail because the webdriver agent is not available and Appium continues to run with other steps rather than wait for the webdriveragent build to complete. It takes 4-5 builds to get that project downloaded and built. If I do not use the webdriverio Appium service and instead rely on the desktop Appium, then the issue goes away since these services are already built in to that executable.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Last Appium version that did not exhibit the issue (if applicable): 1.15.1 only if XCode was not updated (since the webdriveragent project was also updated when XCode version update was released). The older version of WebDriverAgent that gets pulled with the Appium 1.15.1 dependencies does not work at all.
* Desktop OS/version used to run Appium: n/a, running via node
* Node.js version (unless using Appium.app|exe): 12.8.1
* Npm or Yarn package manager: yarn 1.21.1
* Mobile platform/version under test: iOS 13.x
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: 

## Details
XCode 11.4
The Appium install pulled these dependencies' versions:
appium-xcuitest-driver = 3.20.0
appium-webdriveragent = 2.11.0

## Link to Appium logs

https://gist.github.com/mel-OR/1e1add9c865a905d2b31d7fb4756c0e1
The WebDriverAgent attempts to connect, and then at the end, starts to build the dependencies.

## Code To Reproduce Issue [ Good To Have ]

Use @wdio/appium-service to start appium, and add appium as a dependency to the test project (do not use desktop app). If Appium is started command line and the service is not used, I see the same issue with the WebDriverAgent XCode dependency project builds.

**Comment by KazuCocoa** [comment] 2020-04-16 17:19
Did `Cartfile.resolved` exist in `/Users/mp/Code/bumped-app/node_modules/appium-webdriveragent/Carthage` after test running? Appium check if it should run carthage command in https://github.com/appium/WebDriverAgent/blob/master/lib/check-dependencies.js#L73
If your carthage was old, I guess updating carthage also may help.

**Comment by mykola-mokhnach** [comment] 2020-04-16 18:04
The dependencies resolution process happens only once after a fresh version of appium-webdriveragent module is installed. It would be possible to run the `./Scripts/bootstrap.sh -d` script manually there once in order to resolve them and then just reuse the same sources till the next WDA module update.

**Comment by mel-OR** [comment] 2020-04-16 21:19
@KazuCocoa: I have the most up-to-date carthage version, 0.34.0

Cartfile.resolved exists in the appium-webdriver folder after the package is installed. Once I start my test, then I see a Carthage folder with another copy of Cartfile.resolved, a Checkouts folder, then Build folder created. While the build is running for YYCache and RoutingHTTPServer, the Appium server stops and the test fails, as the log indicates.

@mykola-mokhnach  It is strange to have to build this manually when this was building fine before when part of my test run. I feel running the script manually is just a work-around, this feels like a regression. It's possible my hardware makes the build take longer with the newer XCode, but I think that Appium should take this into account and not move on and kill the server before the project files are available for the WebDriverAgent.

**Comment by mykola-mokhnach** [comment] 2020-04-17 06:19
Yes this is a workaround like many others things we do, since the process relies on many third party services we don't have any influence to. In your particular case the cause might be https://github.com/appium/WebDriverAgent/pull/261. We are just trying to make the default behaviour as reliable as possible. Thus sometimes the speed is often sacrificed because of general unification or reliability needs. However, there is always a possibility to optimize the stuff for the local run as much as possible. Only a tiny effort (and documentation tour) is needed.

**Comment by mel-OR** [comment] 2020-04-17 15:06
@mykola-mokhnach  I'll add the extra step in our setup documentation, and see if our CI servers run into this (the only other hardware setup that is different from devs). Not a terrible workaround. I definitely learned more about Appium dependencies than I ever thought I would. Thank you.

**Comment by mykola-mokhnach** [comment] 2020-04-20 08:35
Closed as not an issue

**Closed by mykola-mokhnach** 2020-04-20 08:35 UTC
Labels: NeedsInfo, NotABug
