### ISSUE TITLE
Issue testing on physical iOS device (Log capture did not start)

### ISSUE THREAD

**Issue by GindiKhangura** [appium/appium#4216] opened 2014-12-03 20:21 UTC
I have "Googled" the issue and have found a few issues similar to what I'm seeing, but those are from older versions of Appium, and there is also a post saying that a fix was pushed out.

https://discuss.appium.io/t/log-capture-did-not-start-in-a-reasonable-amount-of-time/1075
https://discuss.appium.io/t/log-capture-did-not-start-in-a-reasonable-amount-of-time/1204
https://github.com/appium/appium/issues/3503
https://github.com/appium/appium/issues/3902

<b>Capabilities setup:</b>
```java
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("deviceName", "GK025917 iPade");
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("platformVersion", "8.1");
capabilities.setCapability("browserName", "safari");
capabilities.setCapability("udid", "448C2FC8A26BA4D59B1D2BA27144345F124834DB");
capabilities.setCapability("noReset", "true");
capabilities.setCapability("forceIpad", "true");
driver = new IOSDriver(new URL("http://<MAC IP>:4723/wd/hub"), capabilities);
```
where driver is a class member variable and yes, the device name and UDID are correct.

<b>Server log:</b>
```
info: --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"8.1","platformName":"iOS","deviceName":"GK025917 iPade","browserName":"safari","udid":"448C2FC8A26BA4D59B1D2BA27144345F124834DB","forceIpad":"true","noReset":"true"}}
info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
warn: Converting cap forceIpad from string to boolean. This might cause unexpected behavior.
warn: Converting cap noReset from string to boolean. This might cause unexpected behavior.
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : forceIpad
info: [debug] Configuring Safari session
info: [debug] Using local .zip from command line: /usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip
info: [debug] Copying local zip to tmp dir
info: [debug] /usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip copied to /var/folders/3f/7nhpwrhj0gggy20lxh63ym74dryp2v/T/114113-5302-17jmwhn/appium-app.zip
info: [debug] Unzipping /var/folders/3f/7nhpwrhj0gggy20lxh63ym74dryp2v/T/114113-5302-17jmwhn/appium-app.zip
info: [debug] Testing zip archive: /var/folders/3f/7nhpwrhj0gggy20lxh63ym74dryp2v/T/114113-5302-17jmwhn/appium-app.zip
info: [debug] Zip archive tested clean
info: [debug] Unzip successful
info: [debug] Using locally extracted app: /var/folders/3f/7nhpwrhj0gggy20lxh63ym74dryp2v/T/114113-5302-17jmwhn/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app
info: [debug] Creating new appium session 9a2069be-2d98-4405-9859-ba4d10e9d268
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 8.1
info: [debug] Not checking whether simulator is available since we're on a real device
info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Could not parse plist file (as binary) at /var/folders/3f/7nhpwrhj0gggy20lxh63ym74dryp2v/T/114113-5302-17jmwhn/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /var/folders/3f/7nhpwrhj0gggy20lxh63ym74dryp2v/T/114113-5302-17jmwhn/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings; assuming it doesn't exist
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/gk025917/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.10.33_1/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"grouped"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. D...ot manually modify!
info: [debug] Dynamic bootstrap path: /Users/gk025917/Library/Application Support/appium/bootstrap/bootstrap-53ce4583016f26ea.js
info: [debug] Reusing dynamic bootstrap: /Users/gk025917/Library/Application Support/appium/bootstrap/bootstrap-53ce4583016f26ea.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":true,"xcodeVersion":"6.1","iOSSDKVersion":"8.1","deviceName":"GK025917 iPade","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'GK025917 iPade (8.1 Simulator)'
info: [debug] Not setting device type since we're on a real device
info: [debug] Checking whether we need to set app preferences
info: [debug] Not setting iOS and app preferences since we're on a real device
info: [debug] Reset not set, not ending sim or cleaning up app state
info: [debug] Not setting locale because we're using a real device
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS device log capture via deviceconsole
error: Log capture did not start in a reasonable amount of time
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Log capture did not start in a reasonable amount of time
info: [debug] Error: Log capture did not start in a reasonable amount of time
    at null._onTimeout (/usr/local/lib/node_modules/appium/lib/devices/ios/ios-log.js:137:10)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Log capture did not start in a reasonable amount of time)","origValue":"Log capture did not start in a reasonable amount of time"},"sessionId":null}
info: <-- POST /wd/hub/session 500 10142.063 ms - 234 
info: [debug] Not pre-launching simulator
info: [debug] Checking app install status using: /usr/local/lib/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id 448C2FC8A26BA4D59B1D2BA27144345F124834DB --bundle com.bytearc.SafariLauncher
```

Also, why does it state "Final device string is: 'GK025917 iPade (8.1 Simulator)'" when I have already defined the name and have made it clear that I'm not using a simulator?

On a side note, this test does successfully work on a simulator. I also have the developer settings enabled on the device. What I don't have is an XCode developer's license on the Mac machine. My setup is as the following:
* iMac with Appium 1.3.4 installed using Node.js
* iPad Air with iOS 8.1 connected to the iMac via USB
* Windows PC running jUnits which connects to the Appium server running on the iMac (server is started using only 'Appium' and no other flags)

**Comment by adigrinvald** [comment] 2015-01-27 07:22
@sebv 
hi 
i tried it without --force-ipad and still i get the same error
posted the appium log here:
https://discuss.appium.io/t/error-when-trying-to-run-ios-tests-on-a-remote-appium-server-appium-log-attached/2563/1

**Comment by kani19** [comment] 2015-02-06 07:54
Same issue. XCode 5.1 ,iPhone4S 7.0, Appium 1.3.4

DesiredCapabilities:

	       	DesiredCapabilities capabilities_safari = new DesiredCapabilities();  
	        capabilities_safari.setCapability("automationName", "Appium"); 
	       	capabilities_safari.setCapability("platformName", "iOS");
	       	capabilities_safari.setCapability("deviceName", "iPhone");
	       	capabilities_safari.setCapability("platformVersion", "7.0");
	       	capabilities_safari.setCapability("browserName", "Safari");
	       	capabilities_safari.setCapability("noReset", "true");
	       	capabilities_safari.setCapability("udid","c88361f2aaea4c0fad53e208fe55981c3a900eb3");

	        driver2 = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities_safari);  


________________
Logs:
________________

Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"udid":"c88361f2aaea4c0fad53e208fe55981c3a900eb3"}
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"Appium","platformVersion":"7.0","deviceName":"iPhone","platformName":"iOS","browserName":"Safari","udid":"c88361f2aaea4c0fad53e208fe55981c3a900eb3","noReset":"true"}}
info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
warn: Converting cap noReset from string to boolean. This might cause unexpected behavior.
info: [debug] Configuring Safari session
info: [debug] Using local .zip from command line: /usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip
info: [debug] Copying local zip to tmp dir
info: [debug] /usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip copied to /var/folders/4f/btlszrcn2l93br16lvbm_2000000gq/T/11516-4749-4zhntw/appium-app.zip
info: [debug] Unzipping /var/folders/4f/btlszrcn2l93br16lvbm_2000000gq/T/11516-4749-4zhntw/appium-app.zip
info: [debug] Testing zip archive: /var/folders/4f/btlszrcn2l93br16lvbm_2000000gq/T/11516-4749-4zhntw/appium-app.zip
info: [debug] Zip archive tested clean
info: [debug] Unzip successful
info: [debug] Using locally extracted app: /var/folders/4f/btlszrcn2l93br16lvbm_2000000gq/T/11516-4749-4zhntw/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app
info: [debug] Creating new appium session aaa57e0a-f6b5-46ab-a9a7-4b91948b0c1d
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 7.1
info: [debug] Not checking whether simulator is available since we're on a real device
info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Could not parse plist file (as binary) at /var/folders/4f/btlszrcn2l93br16lvbm_2000000gq/T/11516-4749-4zhntw/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
`parseFileSync()` is deprecated. Use `parseStringSync()` instead.
info: [debug] Could not parse plist file (as XML) at /var/folders/4f/btlszrcn2l93br16lvbm_2000000gq/T/11516-4749-4zhntw/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings; assuming it doesn't exist
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/kvedi/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.10.36/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"grouped"}
...o: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
info: [debug] Dynamic bootstrap path: /Users/kvedi/Library/Application Support/appium/bootstrap/bootstrap-05c4b2c4f0f8bebf.js
info: [debug] Reusing dynamic bootstrap: /Users/kvedi/Library/Application Support/appium/bootstrap/bootstrap-05c4b2c4f0f8bebf.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"5.1","iOSSDKVersion":"7.1","deviceName":"iPhone","platformVersion":"7.0"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone - Simulator - iOS 7.0'
info: [debug] Not setting device type since we're on a real device
info: [debug] Checking whether we need to set app preferences
info: [debug] Not setting iOS and app preferences since we're on a real device
info: [debug] Reset not set, not ending sim or cleaning up app state
info: [debug] Not setting locale because we're using a real device
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS device log capture via deviceconsole
error: Log capture did not start in a reasonable amount of time
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Log capture did not start in a reasonable amount of time
info: [debug] Error: Log capture did not start in a reasonable amount of time
    at null._onTimeout (/usr/local/lib/node_modules/appium/lib/devices/ios/ios-log.js:137:10)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Log capture did not start in a reasonable amount of time)","origValue":"Log capture did not start in a reasonable amount of time"},"sessionId":null}
info: <-- POST /wd/hub/session 500 11622.692 ms - 234 
info: [debug] Not pre-launching simulator
info: [debug] Checking app install status using: /usr/local/lib/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id c88361f2aaea4c0fad53e208fe55981c3a900eb3 --bundle com.bytearc.SafariLauncher
info: [debug] Installing app using cmd: /usr/local/lib/node_modules/appium/build/fruitstrap/fruitstrap install --id c88361f2aaea4c0fad53e208fe55981c3a900eb3 --bundle "/var/folders/4f/btlszrcn2l93br16lvbm_2000000gq/T/11516-4749-4zhntw/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app"

**Comment by GindiKhangura** [comment] 2015-02-09 15:57
The issue still exists after omitting "forceIpad". I was not able to figure out what to do with the ios-webkit proxy that you linked me to, as the setup for the proxy was done using brew install, and I have no idea where it installed to.

Regardless, Appium was unable to launch the application as it still faced the "Log capture did not start in a reasonable amount of time" issue. The issue does not seem to be with the proxy, as my understanding is that the proxy is only needed for webviews in a native app, and is not needed to launch the app.

**Comment by GindiKhangura** [comment] 2015-02-19 19:04
I'll check with the latest Appium 1.3.5 and update this post with my findings.

**Comment by MatthewPatey** [comment] 2015-02-19 20:39
Still having the same problem on 1.3.5. For me it's a problem when using iOS 8, but iOS 7 works fine.

**Comment by ShiranDadon** [comment] 2015-02-24 13:19
Hi, don't know if it will help, but I had this error and then I noticed the UDID I entered was wrong...

**Comment by GindiKhangura** [comment] 2015-02-24 22:11
I tried installing Appium 1.3.5, but ran into this issue:
https://github.com/appium/appium/issues/4543

I then downloaded the Appium app 1.3.5 and configured the settings to connect to the hub. My first attempt failed due to some reason, so I ran the "Doctor" feature and found that the command line tools were not installed properly (thought I had done that step initially when setting up Appium). I allowed the app to fix the issue for me, and was then able to launch the application successfully.

I will try the Appium JAR and post an update. I would recommend installing the Appium app and running the Doctor in case there is something missing.

**Comment by kirillzh** [comment] 2015-02-24 22:23
I am facing this issue as well, and that's happening when device can return any logs. I think device is collecting to many logs, so it can't log any more. Only reboot help.

**Comment by GindiKhangura** [comment] 2015-02-25 22:18
I am unable to reproduce the issue using Appium 1.3.4.
It might have been the missing/incorrect Command Line Tools which the Appium app fixed for me.
Other than that, I also did a clean install using: <b>npm clean cache</b>, <b>npm install npm</b>, <b>npm uninstall -g appium</b>, <b>npm install -g appium@1.3.4</b> in case that helps anybody. FYI, I used <b>@1.3.4</b> as I'm having issues with installing 1.3.5.

Can someone else encountering this issue verify that the above steps resolves the issue for them?

**Comment by IlyasPatel** [comment] 2015-02-26 18:10
Hi, I tried the above commands and I still get the same error.

As I am new to this I'm not sure if I'm missing any other step. I'm happy to share screen and show you if that would help.

**Comment by IlyasPatel** [comment] 2015-02-26 18:19
Just tried appium 1.3.5 and get the same error.

Not to sound silly but as the error relates to logging (Log capture did not start in a reasonable amount of time), could I try disabling the logs?

**Comment by GindiKhangura** [comment] 2015-02-26 19:51
Alright, I figured it out, and when I realized what it was, I became sad :(

@ShiranDadon was correct about the UDID being incorrect. On my Windows device, I retrieved the UDID from iTunes (not sure where else to get it from on Windows), and <b>iTunes makes all characters in the UDID uppercase</b>. If you use XCode on a Mac to get the UDID, the alphabetic characters are all lowercase (as least for my device).

By using the uppercase UDID, I am able to reproduce the issue. By using the correct UDID from XCode, the issue is <b>NOT</b> reproducible.

Can someone working on Appium please make this issue more apparent in the log messages, and also update the online documentation?

**Comment by GindiKhangura** [comment] 2015-02-26 19:55
I noticed that in the log files and capabilities declaration for the other posters facing this issue, their UDIDs are not all uppercase like mine. Perhaps there is another configuration issue that also results in a similar error message (incorrect device name, etc)?

**Comment by IlyasPatel** [comment] 2015-02-27 14:34
Thanks, updated my UDID. I now get a new error:

info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Unable to install [/var/folders/fv/glww6zh11hx0hthzmg_1ycn00000gp/T/115127-862-ww2vke/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app] to device with id [74ffe7adc637bca4b9ffc7f92cf9c2cabe7864d6]. Error [Error: Command failed: ]
info: [debug] Error: Unable to install [/var/folders/fv/glww6zh11hx0hthzmg_1ycn00000gp/T/115127-862-ww2vke/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app] to device with id [74ffe7adc637bca4b9ffc7f92cf9c2cabe7864d6]. Error [Error: Command failed: ]
    at /usr/local/lib/node_modules/appium/lib/devices/common.js:147:10
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Unable to install [/var/folders/fv/glww6zh11hx0hthzmg_1ycn00000gp/T/115127-862-ww2vke/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app] to device with id [74ffe7adc637bca4b9ffc7f92cf9c2cabe7864d6]. Error [Error: Command failed: ])","origValue":"Unable to install [/var/folders/fv/glww6zh11hx0hthzmg_1ycn00000gp/T/115127-862-ww2vke/submodules/SafariLauncher/build/Release-iphoneos/SafariLauncher.app] to device with id [74ffe7adc637bca4b9ffc7f92cf9c2cabe7864d6]. Error [Error: Command failed: ]"},"sessionId":null}

**Comment by GindiKhangura** [comment] 2015-02-28 04:26
@IlyasPatel I also run into the same issue that you do when attempting to test Safari on an iOS device. Applications should work fine though. I have looked up the issue and there are a few posts regarding the issue, but the solutions are not very user-friendly (e.g. compiling SafariLauncher in XCode and deploying to device).

**Comment by IlyasPatel** [comment] 2015-03-03 22:09
I'm trying again by following the steps here: 

https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/mobile-web.md

When I try to run this command:  ./reset.sh --ios --real-safari

I get the below error. Previously it was issues with lodash but managed to install that but can't get passed this error.
```
MLGBEFCTECH877:appium efctech$ ./reset.sh --ios --real-safari --verbose
---- Resetting / Initializing Appium ----
RESETTING NPM
* Installing new or updated NPM modules (including devDeps)
npm WARN package.json md5calculator@0.0.3 No repository field.
npm WARN package.json node-idevice@0.1.4 No repository field.
npm WARN package.json utf7@1.0.0 No repository field.
npm WARN package.json vargs@0.1.0 No repository field.
npm WARN package.json assert@1.3.0 assert is also the name of a node core module.
npm WARN package.json path@0.11.14 path is also the name of a node core module.
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/appium-adb requires appium-support@'=0.0.3' but will load
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/appium-support,
npm WARN unmet dependency which is version 0.0.5
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/appium-adb requires ncp@'~0.5.1' but will load
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/ncp,
npm WARN unmet dependency which is version 1.0.1
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/appium-adb requires q@'~1.0.1' but will load
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/q,
npm WARN unmet dependency which is version 1.1.2
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/appium-adb requires underscore@'~1.6.0' but will load
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/underscore,
npm WARN unmet dependency which is version 1.8.2
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/appium-adb requires winston@'~0.7.3' but will load
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/winston,
npm WARN unmet dependency which is version 0.9.0
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/appium-instruments requires underscore@'~1.7.0' but will load
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/underscore,
npm WARN unmet dependency which is version 1.8.2
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/appium-instruments requires winston@'~0.8.3' but will load
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/winston,
npm WARN unmet dependency which is version 0.9.0
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/appium-uiauto requires argparse@'~0.1.15' but will load
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/argparse,
npm WARN unmet dependency which is version 1.0.1
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/appium-uiauto requires winston@'~0.8.3' but will load
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/winston,
npm WARN unmet dependency which is version 0.9.0
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/node-simctl/node_modules/rtts-assert/node_modules/gulp-traceur requires gulp-util@'^2.2.5' but will load
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/gulp-util,
npm WARN unmet dependency which is version 3.0.4
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/node-simctl/node_modules/rtts-assert/node_modules/gulp-traceur requires traceur@'^0.0.32' but will load
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/node-simctl/node_modules/traceur,
npm WARN unmet dependency which is version 0.0.74
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/grunt-contrib-jshint/node_modules/jshint/node_modules/cli requires glob@'~ 3.2.1' but will load
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/glob,
npm WARN unmet dependency which is version 4.4.1
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/gulp-jshint/node_modules/jshint/node_modules/cli requires glob@'~ 3.2.1' but will load
npm WARN unmet dependency /Users/efctech/development/appium/node_modules/glob,
npm WARN unmet dependency which is version 4.4.1
RESETTING GENERAL
* Setting git revision data
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'appium-adb'
```

**Comment by GindiKhangura** [comment] 2015-03-04 03:48
The SafariLauncher issue should be discussed in another thread by opening a new issue as it does not pertain to this original one.

**Comment by IlyasPatel** [comment] 2015-03-05 14:07
ok I will.  Out of interest, am i better off using an older version of iOS? Currently I'm using Mavericks.

**Comment by GindiKhangura** [comment] 2015-03-06 04:11
Take a look at this document (http://appium.io/slate/en/master/?ruby#automating-mobile-web-apps); it looks like you will need to deploy the SafariLauncherApp to the device using a provisioning profile.

**Comment by sebv** [comment] 2015-03-09 16:35
Ok closing since you figure out the open issue (And thanks I myself did not know about this windows issue). Open other issues for the other problems if needed. For the profile error, just install any app on the device direcly from xCode, and that should setup everything for you.

**Closed by sebv** 2015-03-09 16:35 UTC
Labels: OnGoing
