### ISSUE TITLE
Unable to acknowledge iOS ATT popup

### ISSUE THREAD

**Issue by irramya** [appium/appium#19910] opened 2024-03-20 16:55 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ATT popup options are available in the DOM/element tree.
However, a click operation on it fails

### Expected Behavior

Click should allow user to acknowledge the popup and close it

### Minimal Reproducible Example

AppiumLibrary.Click Element    xpath=//XCUIElementTypeButton[@name="Allow"]

<img width="415" alt="Screenshot 2024-03-20 at 9 16 01 PM" src="https://github.com/appium/appium/assets/53593299/8f307f15-b1bf-476c-a8b0-3f2d6e09f536">

### Environment

- Operating system: Mac Ventura 13.3
- Appium server version (output of `appium --version`): 2.5.1
- Appium driver(s) and their version(s): v6.0.1 or v7.3.1
- Appium plugin(s) and their version(s):NA
- Node.js version (output of `node --version`):20.11.1
- `npm` version (output of `npm --version`):10.5.0
- Last component(s) version which did _not_ exhibit the problem: xcuitest driver v5.16.1
- Platform and version under test: iOS 17.2
- Real device or emulator/simulator: Simulator iPhone 14 Pro Max

**Comment by KazuCocoa** [comment] 2024-03-20 16:59
Possibly https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/#interact-with-dialogs-managed-by-comapplespringboard

**Comment by mykola-mokhnach** [comment] 2024-03-20 18:52
Duplicate of https://github.com/appium/appium/issues/19908

**Closed by mykola-mokhnach** 2024-03-20 18:52 UTC
Labels: Needs Info
