### ISSUE TITLE
Android swtich to new tab throw exception

### ISSUE THREAD

**Issue by sripappula** [appium/appium#13062] opened 2019-08-12 09:00 UTC
## The problem

I'm trying to switch to new tab using below command 

Browser.SwitchTo().Window(Browser.WindowHandles.LastOrDefault())

Throwing a exception 

{"invalid argument: 'name' must be a string\n  (Session info: chrome=76.0.3809.89)\n  (Driver info: chromedriver=76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}),platform=Windows NT 10.0.17134 x86_64)"}

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0 and 1.14.0
* Android driver version - (appium-android-driver@4.16.3)
* Base driver version - (appium-base-driver@3.16.0)

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
[HTTP] 
[HTTP] --> POST /wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/execute/sync
[HTTP] {"script":"var bounding = arguments[0].getBoundingClientRect(); return ( bounding.top >= 0 && bounding.left >= 0 && bounding.bottom <= (window.innerHeight || document.documentElement.clientHeight) && bounding.right <= (window.innerWidth || document.documentElement.clientWidth) ); return bounding; ","args":[{"element-6066-11e4-a52e-4f735466cecf":"0.01150615410608391-1","ELEMENT":"0.01150615410608391-1"}]}
[W3C (31c61360)] Calling AppiumDriver.execute() with args: ["var bounding = arguments[0].getBoundingClientRect(); return ( bounding.top >= 0 && bounding.left >= 0 && bounding.bottom <= (window.innerHeight || document.documentElement.clientHeight) && bounding.right <= (window.innerWidth || document.documentElement.clientWidth) ); return bounding; ",[{"element-6066-11e4-a52e-4f735466cecf":"0.01150615410608391-1","ELEMENT":"0.01150615410608391-1"}],"31c61360-f519-49c2-9cde-4f91fb1213bf"]
[WD Proxy] Matched '/execute/sync' to command name 'execute'
[Protocol Converter] Did not know how to rewrite the original URL '/execute/sync' for W3C protocol
[WD Proxy] Proxying [POST /execute/sync] to [POST http://127.0.0.1:8000/wd/hub/session/1a69acec1814e47a422bb72b01d4c8e9/execute/sync] with body: {"script":"var bounding = arguments[0].getBoundingClientRect(); return ( bounding.top >= 0 && bounding.left >= 0 && bounding.bottom <= (window.innerHeight || document.documentElement.clientHeight) && bounding.right <= (window.innerWidth || document.documentElement.clientWidth) ); return bounding; ","args":[{"element-6066-11e4-a52e-4f735466cecf":"0.01150615410608391-1","ELEMENT":"0.01150615410608391-1"}]}
[WD Proxy] Got response with status 200: {"sessionId":"1a69acec1814e47a422bb72b01d4c8e9","status":0,"value":true}
[W3C (31c61360)] Responding to client with driver.execute() result: true
[HTTP] <-- POST /wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/execute/sync 200 70 ms - 14
[HTTP] 
[HTTP] --> POST /wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/element/0.01150615410608391-1/click
[HTTP] {}
[W3C (31c61360)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/element/0.01150615410608391-1/click' to command name 'click'
[WD Proxy] Proxying [POST /wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/element/0.01150615410608391-1/click] to [POST http://127.0.0.1:8000/wd/hub/session/1a69acec1814e47a422bb72b01d4c8e9/element/0.01150615410608391-1/click] with body: {}
[WD Proxy] Got response with status 200: {"sessionId":"1a69acec1814e47a422bb72b01d4c8e9","status":0,"value":null}
[WD Proxy] Replacing sessionId 1a69acec1814e47a422bb72b01d4c8e9 with 31c61360-f519-49c2-9cde-4f91fb1213bf
[HTTP] <-- POST /wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/element/0.01150615410608391-1/click 200 948 ms - 76
[HTTP] 
[HTTP] --> GET /wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window/handles
[HTTP] {}
[W3C (31c61360)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window/handles' to command name 'getWindowHandles'
[Protocol Converter] Did not know how to rewrite the original URL '/wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window/handles' for W3C protocol
[WD Proxy] Proxying [GET /wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window/handles] to [GET http://127.0.0.1:8000/wd/hub/session/1a69acec1814e47a422bb72b01d4c8e9/window/handles] with body: {}
[WD Proxy] Got response with status 200: "{\"sessionId\":\"1a69acec1814e47a422bb72b01d4c8e9\",\"status\":0,\"value\":[\"CDwindow-0\",\"CDwindow-1\"]}"
[WD Proxy] Replacing sessionId 1a69acec1814e47a422bb72b01d4c8e9 with 31c61360-f519-49c2-9cde-4f91fb1213bf
[HTTP] <-- GET /wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window/handles 200 12 ms - 99
[HTTP] 
[HTTP] --> GET /wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window/handles
[HTTP] {}
[W3C (31c61360)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window/handles' to command name 'getWindowHandles'
[Protocol Converter] Did not know how to rewrite the original URL '/wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window/handles' for W3C protocol
[WD Proxy] Proxying [GET /wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window/handles] to [GET http://127.0.0.1:8000/wd/hub/session/1a69acec1814e47a422bb72b01d4c8e9/window/handles] with body: {}
[WD Proxy] Got response with status 200: "{\"sessionId\":\"1a69acec1814e47a422bb72b01d4c8e9\",\"status\":0,\"value\":[\"CDwindow-0\",\"CDwindow-1\"]}"
[WD Proxy] Replacing sessionId 1a69acec1814e47a422bb72b01d4c8e9 with 31c61360-f519-49c2-9cde-4f91fb1213bf
[HTTP] <-- GET /wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window/handles 200 14 ms - 99
[HTTP] 
[HTTP] --> POST /wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window
[HTTP] {"handle":"CDwindow-1"}
[W3C (31c61360)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window' to command name 'setWindow'
[WD Proxy] Proxying [POST /wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window] to [POST http://127.0.0.1:8000/wd/hub/session/1a69acec1814e47a422bb72b01d4c8e9/window] with body: {"handle":"CDwindow-1"}
[WD Proxy] Got response with status 200: {"sessionId":"1a69acec1814e47a422bb72b01d4c8e9","status":61,"value":{"message":"invalid argument: 'name' must be a string\n  (Session info: chrome=76.0.3809.89)\n  (Driver info: chromedriver=76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}),platform=Windows NT 10.0.17134 x86_64)"}}
[WD Proxy] Replacing sessionId 1a69acec1814e47a422bb72b01d4c8e9 with 31c61360-f519-49c2-9cde-4f91fb1213bf
[HTTP] <-- POST /wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window 200 4 ms - 322
[HTTP] 
[HTTP] --> GET /wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window/handles
[HTTP] {}
[W3C (31c61360)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window/handles' to command name 'getWindowHandles'
[Protocol Converter] Did not know how to rewrite the original URL '/wd/hub/session/31c61360-f519-49c2-9cde-4f91fb1213bf/window/handles' for W3C protocol

**Comment by mykola-mokhnach** [comment] 2019-08-12 09:02
The cause of this issue is the same as for #12989

It was fixed in appium@beta

**Closed by mykola-mokhnach** 2019-08-12 09:02 UTC
