### ISSUE TITLE
HideKeyboard Doesn't Hide Keyboard - iOS Simulator

### ISSUE THREAD

**Issue by awhisler-nutrien** [appium/appium#13401] opened 2019-10-09 21:44 UTC
## The problem
webdriverio + appium using hideKeyboard() just moves to the previous field and does not hide the keyboard

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0 (and below)
* Node.js version (unless using Appium.app|exe): 12.6.0
* Yarn package manager: 1.17.3
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium.app

## Code To Reproduce Issue

await signUp.inputEmail(email);
await signUp.checkTerms();
await driver.hideKeyboard()
await signUp.clickSubmit();
await verification.linkSentPage("Verification Sent.");
await verification.backToSignInButton();

**Comment by mykola-mokhnach** [comment] 2019-10-10 05:59
Duplicate of https://github.com/appium/appium/issues/12997

**Closed by mykola-mokhnach** 2019-10-10 05:59 UTC

**Comment by awhisler-nutrien** [comment] 2019-10-10 15:39
@mykola-mokhnach if it is a duplicate - why is that one also closed?

**Comment by mykola-mokhnach** [comment] 2019-10-10 15:54
In general Apple does not provide any APIs, which could close the keyboard. One can only do it by pressing Done or Return button (if it is present there and if the keyboard is closeable). From the bigger perspective the only way to close on-screen keyboard is to emulate the same interaction a normal user would do in order to achieve that.

The issue has been closed as duplicate, because it is not a bug and there is no point to repeat the same answer again.

**Comment by awhisler-nutrien** [comment] 2019-10-10 16:06
@mykola-mokhnach is there a way to access they keyboard keys 'done' or 'return' in Appium?

Additionally, I'm confused why you don't think it's a bug as "hideKeyboard()" does not hide the keyboard in iOS

**Comment by mykola-mokhnach** [comment] 2019-10-10 16:51
> @mykola-mokhnach is there a way to access they keyboard keys 'done' or 'return' in Appium?

depending on the client there might be additional parameter to this call, which allows to provide the button name to click. Although the same result could be achieved by simply clicking the corresponding button element

> Additionally, I'm confused why you don't think it's a bug as "hideKeyboard()" does not hide the keyboard in iOS

I would be if we could fix it. Although, only Apple can do it.

**Comment by awhisler-nutrien** [comment] 2019-10-10 17:37
@mykola-mokhnach right but right now, I cannot see the button because the keyboard is up and I can't hide the keyboard apparently, so the only way to do what I need seems to be clicking the keys in the keyboard for 'Go' but I don't know how to access them. What is the method in Appium/webdriverio to do this?

**Comment by mykola-mokhnach** [comment] 2019-10-10 18:43
Please use Appium forum for questions

**Comment by MarcSteven** [comment] 2020-07-18 07:55
@mykola-mokhnach But now the issue is still existing, I cannot find any solutions to fix it.
