### ISSUE TITLE
Android: uiautomator2: After update 2.2.0 -> 2.7.1 app does not restart on driver start

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#17594] opened 2022-10-11 13:18 UTC
## The problem

App does not restart any more on driver open. Tried play with AUTO_LAUNCH + DONT_STOP_APP_ON_RESET not helps.

caps:
Capabilities {allowTestPackages: true, app: /Users/qa/Documents/test/ap..., appWaitActivity: com.xxx.*, autoGrantPermissions: true, automationName: UIAutomator2, clearSystemFiles: true, deviceName: nokia_5.3_11, disableAndroidWatchers: true, enableMultiWindows: true, fullReset: true, newCommandTimeout: 180, noReset: false, noSign: true, platformName: ANDROID, systemPort: 5411, udid: xxx} 

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.44 with uiautomator2@2.7.1
* Last Appium version that did not exhibit the issue (if applicable): 2.0.0-beta.35 with uiautomator2@2.2.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device

## Link to Appium logs

https://gist.github.com/amedvedjev/03d0047a932231abbee5ea3eb1845fed

**Comment by mykola-mokhnach** [comment] 2022-10-11 15:26
Duplicate of https://github.com/appium/appium/issues/17455

**Comment by amedvedjev** [comment] 2022-10-11 15:59
@mykola-mokhnach is there any solution restart app on driver start? 
in most cases terminateApp on driver quit should help BUT! sometimes app may still left running and we need solution terminate before driver start. I can use ADB command to make this but still not nice way.

**Comment by mykola-mokhnach** [comment] 2022-10-11 16:11
Passing noReset=true means the client is responsible for app lifecycle management. The only way to restart the app in such case is to call the appropriate APIs (e.g. https://github.com/appium/appium-uiautomator2-driver#mobile-terminateapp or https://github.com/appium/appium-uiautomator2-driver#mobile-activateapp)

**Comment by amedvedjev** [comment] 2022-10-11 16:13
not convenient. specially for new Appium users.

**Comment by jlipps** [comment] 2022-10-12 19:58
new Appium users should probably not use `noReset=true`. i never recommend setting `noReset` to true unless you want to deal with different session start app state yourself. i don't think there's a way to guarantee starting an app in a clean slate state without resetting all its data (something you explicitly opt out of when setting `noReset` to `true`).

**Comment by jlipps** [comment] 2022-10-12 20:39
Yep. Maybe the change should have been labeled breaking? I'm not sure what the rationale was there exactly. But in any case you can definitely use a specific version of the driver, try something like this:

```
appium driver uninstall uiautomator2
appium driver install uiautomator2@2.0.1
```

**Comment by dlanaghen** [comment] 2022-10-12 21:40
There are a couple of differences in the adb commands between drivers, but the key one centers around the desired capability of `appActivity: GCMActivityStartup`

The old version of the driver used to execute an adb command:
`adb -P 5037 -s 520032834252c58d shell am start -W -n com.garmin.android.apps.connectmobile/GCMActivityStartup -S'`
This no longer occurs.

[Here](https://gist.githubusercontent.com/dlanaghen/7b8397fb39b7954193cbbd11d8c40a20/raw/8363107def516f14c8b42da28bdeca08a1ff8188/gistfile1.txt) is a gist of the adb commands for 2 different conditions.  One, when the app is not started, and another when the app is in the background.

Hope this helps and and always I appreciate you guys helping.

**Comment by amedvedjev** [comment] 2022-10-13 09:13
@jlipps currently I use following logic in test suites -> https://discuss.appium.io/t/different-capabilities-for-different-scenarios/16694/3
```
 if (devicePlatform.contains("fullReset")) { // uninstall and install client
            System.out.println("  Driver DO FULL-RESET");
            capabilities.setCapability(MobileCapabilityType.FULL_RESET, true);
            capabilities.setCapability(MobileCapabilityType.NO_RESET, false);
        } else if (devicePlatform.contains("fastReset")) { // clears cache and settings without reinstall for Android / reinstall app for iOS
            System.out.println("  Driver DO FAST-RESET");
            capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
            capabilities.setCapability(MobileCapabilityType.NO_RESET, false);
        } else { // just start client
            System.out.println("  Driver DO NORMAL start"); 
            capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
            capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
        }
```

now i added after each test terminateApp + added ADB command to kill app before start driver for sure. It is not a problem for 1 test while we execute 1800+ every second means 1800/60 = 30 min total additional time.

**Comment by mykola-mokhnach** [comment] 2022-10-13 14:13
If it is only necessary to restart the app then calling https://github.com/appium/appium-uiautomator2-driver#mobile-startactivity with `stop` arg set to `true` would do the job, so we'd have one api call instead of two. See https://stackoverflow.com/questions/4567904/how-to-start-an-application-using-android-adb-tools for more details

**Comment by amedvedjev** [comment] 2022-10-14 07:42
so why not make it capability that clearly will say restart app on driver start or not? e.g. iOS app with same settings continue restarting. it is better make default behavior similar. it will be real help for beginners....

**Comment by dlanaghen** [comment] 2022-10-14 18:42
I like @amedvedjev 's idea.  I have to believe there are are a lot of people relying on the current behavior and this reduces the pain of migration.

**Comment by jlipps** [comment] 2022-10-24 20:53
@mykola-mokhnach what do you think? a combination of `noReset=true` and a new cap like `restartApp=true`?

**Comment by mykola-mokhnach** [comment] 2022-10-24 22:30
@jlipps I think the behaviour should be consistent across drivers. At least these that we maintain

**Comment by jlipps** [comment] 2022-10-27 18:48
and is that currently the case? i'm having a little trouble keeping this issue clear in my head

**Comment by amedvedjev** [comment] 2022-10-31 09:29
@jlipps iOS has `appium:forceAppLaunch`
```
Specify if the app should be forcefully restarted if it is already running on session startup. This capability only has an effect if an application identifier has been passed to the test session (either explicitly, by setting bundleId, or implicitly, by providing app). Default is true unless noReset capability is set to true.
```

**Comment by jlipps** [comment] 2022-11-01 20:07
@mykola-mokhnach what about implementing this capability for android?

**Comment by mykola-mokhnach** [comment] 2022-11-02 14:23
@jlipps I don't mind if someone wants to contribute

**Comment by mykola-mokhnach** [comment] 2022-12-08 07:47
Added the capability to uia2 driver in the PR above

**Closed by mykola-mokhnach** 2022-12-08 07:47 UTC
Labels: Enhancement, UIAutomator2
