### ISSUE TITLE
bug: adb setting device id failed on android 14

### ISSUE THREAD

**Issue by kevinycm** [appium/appium#19717] opened 2024-01-26 09:38 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

using Appium  InSpector connecting to appium server，
appium server log shows that AndroidUiautomator2Driver could found device 29261FDH3007FD，
while ADB failed on setting device id，
the following is exception: 
Encountered internal error running command: Error: Error getting device API level. Original error: Error executing adbExec. Original error: 'Command '/Users/ycm/Library/Android/sdk/platform-tools/adb -P 5037 -s  shell getprop ro.build.version.sdk' exited with code 1'; Command output: error: device '' not found

### Expected Behavior

ADB could set device id successfully

### Minimal Reproducible Example

```

from appium import webdriver
from appium.options.android import UiAutomator2Options
from selenium.webdriver.support.ui import WebDriverWait


class Crawling(object):
    def __init__(self) -> None:
        desired_caps = {}

        desired_caps['platformName'] = 'Android'
        desired_caps['platformVersion'] = "14"
        desired_caps['deviceName'] = '29261FDH3007FD'
        desired_caps['appPackage'] = 'com.tencent.mm'
        desired_caps['appActivity'] = '.ui.LauncherUI'
        desired_caps['noReset'] = 'true'
        desired_caps['automationName'] = 'uiautomator2'
        
        self.driver = webdriver.Remote('http://127.0.0.1:4723', options=UiAutomator2Options().load_capabilities(desired_caps))

        self.wait = WebDriverWait(self.driver, 300)

        
if __name__ == "__main__":
    test = Crawling()


```

### Environment

- Operating system: macOS 14.2.1
- Appium server version (output of `appium --version`):2.4.1
- Appium driver(s) and their version(s):
- -  uiautomator2@2.43.0 (automationName 'UiAutomator2')
- -  xcuitest@5.14.1 (automationName 'XCUITest')
- Appium plugin(s) and their version(s):
- -  images@3.0.1
- Node.js version (output of `node --version`):v20.11.0
- `npm` version (output of `npm --version`):10.2.4
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator: Pixel 7 Pro

### Link to Appium Logs

https://gist.github.com/kevinycm/262d9eb11fc8983af9634a2d1a4de121

### Further Information

looking forward someone's help

**Comment by mykola-mokhnach** [comment] 2024-01-26 09:39
Duplicate of https://github.com/appium/appium/issues/19713

**Closed by mykola-mokhnach** 2024-01-26 09:39 UTC
Labels: Bug, Needs Triage
