### ISSUE TITLE
Logcat capture failed-Spawn EONET Error while running Appium

### ISSUE THREAD

**Issue by archu-test** [appium/appium#5128] opened 2015-05-16 10:43 UTC
I am getting this error continuously while running appium1.4. I have set the environment variable- Android_home correctly without spaces. C:\Androidnew\sdk
Also added the location of tools and platform-tools folder in path variable.
Kindly suggest.
Find the script below:

public class abc {
	private AppiumDriver driver;

    @Before
    public void setUp() throws Exception {
        // set up appium
        
        File app = new File("C:\\Android\\sdk\\build-tools\\android-4.4W\\myapp.apk");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName","25e5d556");
        capabilities.setCapability("platformName","Android");
        capabilities.setCapability("platformVersion", "4.4.2");
        capabilities.setCapability("app", app.getAbsolutePath());
        capabilities.setCapability("appPackage", "com.functionx.myapp.WelcomeActivity");
        capabilities.setCapability("appActivity", ".WelcomeActivity");
        driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        driver.manage().timeouts().implicitlyWait(80,TimeUnit.SECONDS);
        //driver.quit();
    }

    @After
    public void tearDown() throws Exception {
        driver.quit();
    }
	public static void main(String args[]) throws Exception
	{
		abc a = new abc();
		a.setUp();
		a.tearDown();
		
	}
	}

**Comment by vijay0850** [comment] 2015-05-17 04:41
Did you tried with some other system?

**Comment by nabeel-ibrahim** [comment] 2015-05-19 22:38
I had the same issue, I reinstalled Eclipse and that solved my problem.

**Comment by sebv** [comment] 2015-06-03 10:06
Could you provide full server log (in gist)? thx.

**Comment by sebv** [comment] 2015-06-11 14:25
Closing, not a bug please go to appium discuss for support: https://discuss.appium.io/

**Closed by sebv** 2015-06-11 14:25 UTC
Labels: OnGoing

**Comment by archu-test** [comment] 2015-07-17 14:01
Hi,
I got the issue resolved by reentering Android sdk path in Appium Settings.
Thank you all for the support.
