### ISSUE TITLE
UiAutomator 2 certificate signing issues while testing Android phones v7 and below

### ISSUE THREAD

**Issue by ajschwieterman** [appium/appium#14554] opened 2020-07-14 17:42 UTC
## The problem

Appium fails to launch the app on an Android phone using Android v7 and below.  Looking at the logs, it seems to be an issue with certificate signing of UiAutomator 2.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.17.1
* Mobile platform/version under test: Android v7 and below
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI
## Link to Appium logs

https://gist.github.com/ajschwieterman/ea8d72fca52f79628edadea22b99bc77#file-appiumlog-txt

**Comment by mykola-mokhnach** [comment] 2020-07-14 18:16
Duplicate of https://github.com/appium/appium/issues/14542

**Closed by mykola-mokhnach** 2020-07-14 18:16 UTC

**Comment by mykola-mokhnach** [comment] 2020-07-14 18:18
I would try to install build tools v28 as a possible solution
