### ISSUE TITLE
Space in directory name causes server to reinstall every time

### ISSUE THREAD

**Issue by kamza-tricentis** [appium/appium#11704] opened 2018-11-19 10:33 UTC
## The problem

When AndroidSDK and Appium directories are held in locations that does have space in their name the apksigner is not working correctly which causes server (UiAutomator2 in this case) to reinstall each time the driver is created.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0, 1.9.2-beta.2
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe): 7.7.3
* Mobile platform/version under test: Android
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: appium cli

## Link to Appium logs

https://gist.github.com/kamza-tricentis/191507ea91c43fa8098b6d3daccdf761

**Comment by imurchie** [comment] 2018-11-19 14:10
This is odd. [teen_process](https://github.com/appium/node-teen_process) is supposed to handle this case. Will investigate.

**Comment by mykola-mokhnach** [comment] 2018-11-19 15:09
I assume the problem is Windows-specific. We had already something similar: https://github.com/appium/appium-adb/pull/315

**Comment by mykola-mokhnach** [comment] 2018-11-19 15:15
https://github.com/nodejs/node-v0.x-archive/issues/25895

**Comment by imurchie** [comment] 2018-11-19 15:35
Yes, it works fine on Mac. I'm trying to get my Windows environment up to date to check this out further.

**Comment by imurchie** [comment] 2018-11-19 15:59
I do find it weird that adb calls work fine, despite also being `exec`-ed.

**Comment by mykola-mokhnach** [comment] 2018-11-20 07:01
Please check if https://github.com/appium/appium-adb/pull/384 patch works for you

**Comment by kamza-tricentis** [comment] 2018-11-20 07:56
Yes, thank you, the fix there works like a charm.

**Comment by mykola-mokhnach** [comment] 2018-11-20 08:08
Cool. I'll publish it soon

**Comment by mykola-mokhnach** [comment] 2018-11-20 08:43
The fix has been published in appium@beta

**Closed by mykola-mokhnach** 2018-11-20 08:43 UTC
Labels: Android, Bug
