### ISSUE TITLE
Appium uses private variables from Selenium

### ISSUE THREAD

**Issue by firelightrpg** [appium/appium#20713] opened 2024-10-30 18:30 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am encountering this issue. 
`AttributeError: 'AppiumConnection' object has no attribute '_ca_certs'`

I fixed it by pegging selenium. I have a couple of setups running appium and one was exhibiting this issue, but the other was not. After running an update on the packages, this appeared in the system that was previously working. I looked at the logs and noticed   - Updating selenium (4.25.0 -> 4.26.0) I then pegged selenium to 4.25.0 and it started working again.

Note - a semver update of the minor should not break the api, but, appium is addressing a private var in selenium (? _ca_certs). A private variable is not intended to be used by a consumer and is not guaranteed to remain stable. While pegging selenium may fix the issue for you, ultimately, the appium package should not be relying on private variable access from the selenium package.

### Expected Behavior

Appium shouldn't trigger an attribute error when launching the driver. 

### Minimal Reproducible Example

Start an appium driver after updating appium and selenium. 

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

Any (happens with both PC and linux with latest appium/ selenium)

**Comment by KazuCocoa** [comment] 2024-10-30 19:07
duplicate of https://github.com/appium/python-client/issues/1053
It is planed work in https://github.com/appium/python-client/pull/1045 to reduce some code from appium python client (not yet though)

https://github.com/appium/python-client?tab=readme-ov-file#compatibility-matrix is current compatibility matrix

**Closed by KazuCocoa** 2024-10-30 19:07 UTC
Labels: Bug, Needs Triage
