### ISSUE TITLE
App is crashing when calls reset driver

### ISSUE THREAD

**Issue by juhlila** [appium/appium#7247] opened 2016-11-17 16:59 UTC
## The problem

In the middle of the tests, when i call driver.reset, it crashes and doesnt open again, saying bad app (the same app path that was previously used to install). it happens only on ipad realdevice, iphone works fine

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.1
* Last Appium version that did not exhibit the issue (if applicable): 1.5.1
* Desktop OS/version used to run Appium: mac sierra (xcode set to 7)
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: ipad mini ios 9
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs

https://gist.github.com/juhlila/3994146494524f2b00533ee44a406237

## Code To Reproduce Issue [ Good To Have ]
just call driver.reset

i am using ruby lib, heres the output

```
     Failure/Error: if e = error()
     
     Selenium::WebDriver::Error::UnknownError:
       An unknown server-side error occurred while processing the command. Original error: Bad app: /Users/julia/workspace/appium-tests/bike-race/ipa/cheats.ipa. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
```

which is weird cause the same app path was used before to install the app, and i just want to reset, the problem only happen on ipad, it works on iphone

**Comment by mykola-mokhnach** [comment] 2016-11-19 20:01
Is it reproducible on 1.6.1beta?

**Comment by juhlila** [comment] 2016-11-23 14:28
@mykola-mokhnach i am using this version because i want to use instruments until the knowm problems on 1.6 is fixed, so i cannot try that on 1,6 right now :/

**Comment by juhlila** [comment] 2016-11-23 15:16
Heres the error that shows on screen, not the log

```
[10] pry(#<RSpec::ExampleGroups::Integration>)> driver.reset    
[Support] Error: ENOENT: no such file or directory, open '/var/folders/k0/s803_jl52hvggnvg9sbdbbf00000gn/T/20161023-48798-g3lh83.y1fj8xgvi/appium-app.zip'
    at Error (native)
 { Error: ENOENT: no such file or directory, open '/var/folders/k0/s803_jl52hvggnvg9sbdbbf00000gn/T/20161023-48798-g3lh83.y1fj8xgvi/appium-app.zip'
    at Error (native)
  cause: 
   { Error: ENOENT: no such file or directory, open '/var/folders/k0/s803_jl52hvggnvg9sbdbbf00000gn/T/20161023-48798-g3lh83.y1fj8xgvi/appium-app.zip'
       at Error (native)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/var/folders/k0/s803_jl52hvggnvg9sbdbbf00000gn/T/20161023-48798-g3lh83.y1fj8xgvi/appium-app.zip' },
  isOperational: true,
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/folders/k0/s803_jl52hvggnvg9sbdbbf00000gn/T/20161023-48798-g3lh83.y1fj8xgvi/appium-app.zip' }
[iOS] Error: ENOENT: no such file or directory, open '/var/folders/k0/s803_jl52hvggnvg9sbdbbf00000gn/T/20161023-48798-g3lh83.y1fj8xgvi/appium-app.zip'
    at Error (native)
 { Error: ENOENT: no such file or directory, open '/var/folders/k0/s803_jl52hvggnvg9sbdbbf00000gn/T/20161023-48798-g3lh83.y1fj8xgvi/appium-app.zip'
    at Error (native)
  cause: 
   { Error: ENOENT: no such file or directory, open '/var/folders/k0/s803_jl52hvggnvg9sbdbbf00000gn/T/20161023-48798-g3lh83.y1fj8xgvi/appium-app.zip'
       at Error (native)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/var/folders/k0/s803_jl52hvggnvg9sbdbbf00000gn/T/20161023-48798-g3lh83.y1fj8xgvi/appium-app.zip' },
  isOperational: true,
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/folders/k0/s803_jl52hvggnvg9sbdbbf00000gn/T/20161023-48798-g3lh83.y1fj8xgvi/appium-app.zip' }
[iOS] Bad app: '/Users/julia/workspace/appium-tests/ipa/cheats.ipa'. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
[MJSONWP] Encountered internal error running command: Error: Bad app: /Users/julia/workspace/appium-tests/ipa/cheats.ipa. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
    at IosDriver.configureApp$ (lib/driver.js:246:13)
    at tryCatch (/Users/julia/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/julia/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/julia/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/julia/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Bad app: /Users/julia/workspace/appium-tests/ipa/cheats.ipa. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
from /Users/julia/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'

```

**Comment by dpgraham** [comment] 2017-07-18 21:25
Closing because we no longer support Instruments.

**Closed by dpgraham** 2017-07-18 21:25 UTC
Labels: NeedsTriage
