### ISSUE TITLE
Cannot set the element to 'value'. Did you interact with the correct element?

### ISSUE THREAD

**Issue by lendra061097** [appium/appium#14815] opened 2020-10-17 15:29 UTC
## The problem

Hi,

I am trying to Set Text on Edit Text Mobile Object on Katalon. I can tap the Object but when i want to SetText The Test Case Failed with Error Log :

Reason:
com.kms.katalon.core.exception.StepFailedException: Cannot send keys 'value' on test object 'Object Repository/EditTextFocused'. (Root cause: org.openqa.selenium.InvalidElementStateException: Cannot set the element to 'value'. Did you interact with the correct element?

I already use Set text and Send Keys but the result same.

anyone please help. Thanks.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.2 and 1.18.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Catalina Version 10.15.7
* Node.js version (unless using Appium.app|exe): Node.js Version 12.19.0
* Npm or Yarn package manager: NPM Version 6.14.8
* Mobile platform/version under test: Mobile Android OS 10 Samsung A50s
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Code To Reproduce Issue [ Good To Have ]

import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import static com.kms.katalon.core.testobject.ObjectRepository.findWindowsObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import com.kms.katalon.core.windows.keyword.WindowsBuiltinKeywords as Windows
import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.core.mobile.keyword.internal.MobileDriverFactory as MobileDriverFactory
import io.appium.java_client.android.AndroidDriver as AndroidDriver
import io.appium.java_client.android.AndroidKeyCode as AndroidKeyCode
import org.openqa.selenium.Keys as Keys

Mobile.startApplication("File Location", false)

Mobile.tap(findTestObject('Object Repository/EditTextFocused'), 0)

Mobile.sendKeys(findTestObject("Object Repository/EditTextFocused"),"value")

**Comment by mykola-mokhnach** [comment] 2020-10-17 15:44
Duplicate of https://github.com/appium/appium/issues/12250

**Closed by mykola-mokhnach** 2020-10-17 15:44 UTC
