### ISSUE TITLE
Appium : "Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch"

### ISSUE THREAD

**Issue by Logakarti** [appium/appium#8828] opened 2017-07-12 06:33 UTC
## The problem
"Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch" exception throws between the app runtime while triggering the app suite in Amazon device farm. I could automate the cases without issue in my iOS real device and simulators.

## Environment
* Appium version : 1.6.3
* Real device : iPhone 5s 9.3.5

## Link to Appium logs
https://gist.github.com/Logakarti/ccad1788a1ab1d4ec6e33eb27f77f065

## Code To Reproduce Issue [ Good To Have ]
```java
        final String URL_STRING = "http://127.0.0.1:4723/wd/hub";
        URL url = new URL ( URL_STRING );
        //Use a empty DesiredCapabilities object
        DesiredCapabilities capabilities = new DesiredCapabilities ();
        driver = new IOSDriver<MobileElement> ( url, capabilities );
        capabilities.setCapability("newCommandTimeout", "50000");
        capabilities.setCapability("recreateChromeDriverSessions", true);
        capabilities.setCapability("startIWDP", "true");
        capabilities.setCapability ("webkitResponseTimeout", "60000");
        driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS );
        try {
            Thread.sleep( 15000 );
        } catch (InterruptedException e) {
            e.printStackTrace ( );
        }
```
Please let me know your comments.

**Comment by Logakarti** [comment] 2017-07-12 06:34
@mykola-mokhnach

**Comment by imurchie** [comment] 2017-07-12 13:50
Does this only happen when running `reset`? 

I would check in with Amazon's technical support.

**Comment by Logakarti** [comment] 2017-07-13 06:26
Not happens in "reset" time. It's happening between the execution time after launching the app.

**Comment by jlipps** [comment] 2017-07-28 21:15
If the issue is not present with your local device but is popping up on Amazon's Device Farm, I would do as @imurchie suggests and convey this information to their support team. Meanwhile, closing this issue here.

**Closed by jlipps** 2017-07-28 21:15 UTC
Labels: iOS

**Comment by Logakarti** [comment] 2017-07-29 09:21
Let me know once this issue is resolved.

**Comment by jlipps** [comment] 2017-07-31 23:21
@Logakarti we can't resolve the issue, as it appears to be a problem inside Amazon's Device Farm.

**Comment by Logakarti** [comment] 2017-08-02 06:41
Thanks @jlipps

**Comment by sridhar-vadlamani-ck** [comment] 2018-02-23 19:40
@Logakarti Any update on how you fixed this? We're having the same issue on Device Farm.

**Comment by Logakarti** [comment] 2018-02-24 15:38
Till the issue not yet fixed



On 24-Feb-2018 1:10 AM, "Sridhar Vadlamani" <notifications@github.com>
wrote:

@Logakarti <https://github.com/logakarti> Any update on how you fixed this?
We're having the same issue on Device Farm.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/appium/appium/issues/8828#issuecomment-368117501>, or mute
the thread
