### ISSUE TITLE
Setting driver.updateSettings({ snapshotMaxDepth: 60 }) doesn't have any effect

### ISSUE THREAD

**Issue by razvan-avi** [appium/appium#18085] opened 2023-01-19 17:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Setting a custom snapshotMaxDepth doesn't work

The problem was discovered after upgrading the Appium XCUITestDriver driver from `4.12.2` to `4.12.3` . Setting a custom snapshotMaxDepth works with driver version `4.12.2` but doesn't seem to have any affect with `4.12.3` or any of the versions above that.
From a quick check it seems the problem might have been introduced here:
https://github.com/appium/WebDriverAgent/pull/638
https://github.com/appium/WebDriverAgent/compare/v4.10.9...v4.10.10

### Expected Behavior

Elements nested deeper than 50 levels in the DOM can still be found by increasing the snapshotMaxDepth.

### Minimal Reproducible Example

**Using Appium `2.0.0-beta.52` and xcuitest@4.12.3**

1. Find an element that could only be found by increasing the snapshotMaxDepth
2. Set a custom snapshotMaxDepth by calling the Webdriverio Appium command `driver.updateSettings({ snapshotMaxDepth: 60 })`
3. Element can NOT be found

**Using Appium `2.0.0-beta.52` and xcuitest@4.12.2**

1. Find an element that could only be found by increasing the snapshotMaxDepth
2. Set a custom snapshotMaxDepth by calling the Webdriverio Appium command `driver.updateSettings({ snapshotMaxDepth: 60 })`
3. Element CAN be found

### Environment

- appium version 2.0.0-beta.52
- xcuitest@4.12.3 
- node version v19.1.0
- iOS simulator -> iOS 15.4 , iOS16.1, iOS 16.2

### Link to Appium Logs

https://gist.github.com/razvan-avi/028664cff16dec6f880302401f40268b

**Comment by mykola-mokhnach** [comment] 2023-01-19 19:22
Is the destination element present in the page source after the setting is changed?

**Comment by razvan-avi** [comment] 2023-01-19 19:54
No, the element is not present in the page source after the setting is changed. But if I use xcuitest@4.12.2 or an older version, the element is present after the setting is changed.

**Comment by mykola-mokhnach** [comment] 2023-01-19 20:04
The above change did not touch anything related to page source generation. Only elements lookup. 
Unfortunately I cannot help much without having an application to test with.

**Comment by mykola-mokhnach** [comment] 2023-01-23 14:37
Like I said we cannot help on this issue without possibility to consistently reproduce it in local env. Thus closing

**Comment by razvan-avi** [comment] 2023-01-24 11:05
@mykola-mokhnach, you cannot really set "session settings" in any session with `xcuitest 4.12.3` or above. The thing that [changed from 4.12.2 to 4.12.3](https://github.com/appium/appium-xcuitest-driver/compare/v4.12.2...v4.12.3) is also upgrading `appium-webdriveragent` to 4.10.10
<img width="618" alt="image" src="https://user-images.githubusercontent.com/105639844/214073965-d4d982e7-cb30-474a-af40-ce40241855d8.png">

This new version contains some changes that explicitly touched the "session settings" https://github.com/appium/WebDriverAgent/pull/629
Could it be, now that we are resetting the session-specific settings on startup we are also interfering with actually setting them?


**Some additional findings:**
Initializing a setting via capabilities doesn't work
`'appium:settings[snapshotMaxDepth]': 500`

Using webdriverio command doesn't work: 
`driver.updateSettings({ snapshotMaxDepth: 60 })`

both options were working previously.
Interestingly enough I can see the settings being set using `driver.getSettings()` they just don't have any effect.
```
[0-0] 2023-01-23T16:25:50.588Z INFO webdriver: COMMAND getSettings()
[0-0] 2023-01-23T16:25:50.589Z INFO webdriver: [GET] http://localhost:4723/session/d3223d57-f622-40d6-a467-19a6bbf78ab4/appium/settings
[0-0] 2023-01-23T16:25:50.591Z INFO webdriver: RESULT {
[0-0]   nativeWebTap: false,
[0-0]   nativeWebTapStrict: false,
[0-0]   useJSONSource: false,
[0-0]   shouldUseCompactResponses: true,
[0-0]   elementResponseAttributes: 'type,label',
[0-0]   mjpegServerScreenshotQuality: 25,
[0-0]   mjpegServerFramerate: 10,
[0-0]   screenshotQuality: 1,
[0-0]   mjpegScalingFactor: 100,
[0-0]   reduceMotion: null,
[0-0]   snapshotMaxDepth: 60,
[0-0]   ignoreUnimportantViews: true
[0-0] }
```
Also using the Appium inspector I can still properly set the snapshotMaxDepth successfully like so which allows me to identify +50 nested elements:
  `"appium:settings[snapshotMaxDepth]": "60",`

Not sure if this helps in any way, just wanted to add some additional findings. Let me know if I can help out investigating this further. thanks!

**Comment by mykola-mokhnach** [comment] 2023-01-24 19:46
Thanks for checking it. I have prepared a [PR](https://github.com/appium/WebDriverAgent/pull/655), but not quite sure if it affects your issue. Could you please try to test it locally by replacing WDA sources?

**Comment by razvan-avi** [comment] 2023-01-25 17:36
I installed `xcuitest-driver` locally and replaced the WDA sources with the changes from your [branch](https://github.com/appium/WebDriverAgent/tree/defaults) but unfortunately it doesn't seem to fix the problem. 
Let me know if you need help with any other testing, now that I have the projects set up locally it should be easier.

**Comment by mykola-mokhnach** [comment] 2023-01-25 17:57
Maybe @Dan-Maor could also help us later with testing as I don't posses necessary assets to run it locally as mentioned above.

**Comment by mykola-mokhnach** [comment] 2023-01-25 17:59
Maybe https://github.com/appium/appium/issues/18107 has something in common with this issue as well

**Comment by Dan-Maor** [comment] 2023-01-26 09:00
Hello @razvan-avi , I tried to run a few tests this morning on a real device running iOS 16.3 on both branches the test apps I have which are deep-nested appear to be working correctly on both branches.

Few questions:
* I saw that you're executing your tests on simulators, are you using the latest Xcode?
* Is the issue reproducible when using all iOS versions on the latest Xcode?
* Does using a previous version of Xcode cause a different behavior for the older simulator version?
* Will it be possible for you to share a sample project in which the issue can be reproduced?

**Comment by razvan-avi** [comment] 2023-01-26 15:38
> * I saw that you're executing your tests on simulators, are you using the latest Xcode?

Yes I am using Xcode Version 14.2 

> * Is the issue reproducible when using all iOS versions on the latest Xcode?

I managed to reproduce it using:
**Simulators:**
- iPhone 14, iOS `16.1`, `16.2`
- iPhone 13 iOS  `15.4`
- iPhone 12 iOS   `14.5` 

**Physical device:**
- iPhone 11, iOS `16.2`


> * Does using a previous version of Xcode cause a different behavior for the older simulator version?

Unfortunately I couldn't find an easy way to downgrade Xcode on macOS Ventura. I think Ventura only supports Xcode 14+



> * Will it be possible for you to share a sample project in which the issue can be reproduced?

I cannot share the project as it contains sensitive information. I would have to fork it and remove a lot of code which will take a while 


Extra note:
I also just tried it out and it looks like snapshotMaxDepth setting works properly on a real device using `xcuitest@4.12.2`. Tried it with - iPhone 11, iOS `16.2`

**Comment by dylanhillier** [comment] 2023-01-27 22:19
I just battled something very similar.

1. My python based tests (for testing react-native on iOS) were setting the capabilities including `snapshotMaxDepth`. However, it never took effect, it looked like whatever i was setting it to resulted in some kind of default value being used.
2. Using appium inspector would result in the correct output using the same settings as configured in my tests.

I.e - appium inspector config:
```
{
  "appium:automationName": "XCUITest",
  "platformName": "IOS",
  "appium:settings[snapshotMaxDepth]": 65
}
```

Output from my appium server on startup:

```
[Appium] Welcome to Appium v2.0.0-beta.48 (REV 9600617c52d0d2e48493424c529ac6c945d2775b)
[Appium] Non-default server args:
[Appium] {
[Appium]   address: 'localhost',
[Appium]   basePath: '/wd/hub'
[Appium] }
[Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at /Users/roosack/.appium/node_modules/appium-xcuitest-driver
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at /Users/roosack/.appium/node_modules/appium-uiautomator2-driver
[Appium] Appium REST http interface listener started on localhost:4723
[Appium] Available drivers:
[Appium]   - xcuitest@4.16.6 (automationName 'XCUITest')
[Appium]   - uiautomator2@2.12.1 (automationName 'UiAutomator2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
```

This was caused by my tests calling `driver.reset()`, which appears to nuke any previously set `snapshotMaxDepth` value.

**Comment by Dan-Maor** [comment] 2023-01-29 09:44
@razvan-avi  I think I understand the issue, but just to confirm - can you please attach the Appium server log while enabling showXcodeLog?

**Comment by traviswimer** [comment] 2023-01-29 20:18
I noticed another detail that I don't think has been mentioned. It seems that setting `snapshotMaxDepth` is somehow making it impossible to select **any** elements. 

In my scenario, I have two elements. One is at a shallow depth and the other is at a deep depth.

I was originally not setting `snapshotMaxDepth` and I was able to select the shallow element, but unable to select the deeply nested element, so I set `snapshotMaxDepth` to `100`. Surprisingly, this resulted in the shallow element selector also failing.

Knowing this, I attempted to select the highest level element in my app, and that also failed.

So, I think either `snapshotMaxDepth` is getting set to zero, or this bug is somehow completely breaking the selector code.

Can anyone else reproduce being unable to select the top level element when `snapshotMaxDepth` is set?

**Comment by Dan-Maor** [comment] 2023-01-31 11:28
My assumption of what's happening - and correlated with local testing of a sample app created with an artificial deep element structure - is that when the max depth is set to a high value and the tested application _has_ relevant deeply nested elements, then a snapshot cannot be taken at all, hence no element including the topmost can be found.

@traviswimer Can you please try to validate it by setting `snapshotMaxDepth` to `100` while enabling the `showXcodeLog` capability and attach the Appium server log?

**Comment by traviswimer** [comment] 2023-02-02 19:07
@Dan-Maor For some reason, I can't seem to get `showXcodeLog` to work. I've never used that capability before, but there don't seem to be any additional logs printed from Xcode when I enable it.

I am running on a simulator with the following capabilities:

```javascript
{
    platformName: 'iOS',
    'appium:automationName': 'XCUITest',
    'appium:deviceName': 'iPhone 14',
    'appium:platformVersion': '16.2',
    'appium:app': '../path/to/MyApp.app',
    'appium:settings[snapshotMaxDepth]': 100,
    'appium:showXcodeLog': true
}
```
Does something else need set for `showXcodeLog` to work?

The only meaningful logs I'm seeing in the output are these: (but I doubt it's what you're looking for)

```
[0-0] 2023-02-02T18:50:00.696Z INFO webdriver: COMMAND findElement("css selector", "#my_button")
[0-0] 2023-02-02T18:50:00.697Z INFO webdriver: [POST] http://127.0.0.1:4723/session/be6772c5-f3fc-4e1c-b5cb-8ae3d9f26a51/element
[0-0] 2023-02-02T18:50:00.697Z INFO webdriver: DATA { using: 'css selector', value: '#my_button' }
[0-0] 2023-02-02T18:50:00.959Z INFO webdriver: RESULT {
[0-0]   error: 'no such element',
[0-0]   message: 'An element could not be located on the page using the given search parameters.',
[0-0]   stacktrace: 'NoSuchElementError: An element could not be located on the page using the given search parameters.\n' +
[0-0]     '    at XCUITestDriver.doNativeFind (/path/to/my/project/node_modules/appium-xcuitest-driver/lib/commands/find.js:129:11)\n' +
[0-0]     '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
[0-0]     '    at XCUITestDriver.findNativeElementOrElements (/path/to/my/project/node_modules/appium-xcuitest-driver/lib/commands/find.js:89:10)\n' +
[0-0]     '    at XCUITestDriver.findElOrEls (/path/to/my/project/node_modules/appium-xcuitest-driver/lib/commands/find.js:22:12)\n' +
[0-0]     '    at XCUITestDriver.findElOrElsWithProcessing (/path/to/my/project/node_modules/@appium/base-driver/lib/basedriver/commands/find.js:81:16)\n' +
[0-0]     '    at XCUITestDriver.findElement (/path/to/my/project/node_modules/@appium/base-driver/lib/basedriver/commands/find.js:21:14)'
[0-0] }
```
Let me know if there is something else you'd like me to try. Thanks.

**Comment by mykola-mokhnach** [comment] 2023-02-06 19:51
Closed because of no response

**Closed by mykola-mokhnach** 2023-02-06 19:51 UTC
Labels: XCUITest, Needs Info

**Comment by jgolden** [comment] 2023-03-13 21:43
Saw the fix in https://github.com/appium/WebDriverAgent/pull/666 mentioned a possible solution for this issue, in appium-webdriveragent 4.13.0, but still seeing this issue after testing with that version of webdriveragent.

appium: 2.0.0-beta.53
appium-xcuitest-driver: 4.19.0
appium-webdriveragent: 4.13.0

Test:
```
await driver.pause(15000);
await driver.getPageSource();
await driver.pause(15000);
```

With:
`driver.updateSettings({ snapshotMaxDepth: 60 });`

Page source returns elements.

```
[debug] [XCUITestDriver@3310 (ecb76e6e)] Calling AppiumDriver.getPageSource() with args: ["ecb76e6e-0531-49df-96f8-7293231ced3f"]
[debug] [XCUITestDriver@3310 (ecb76e6e)] Executing command 'getPageSource'
[debug] [XCUITestDriver@3310 (ecb76e6e)] Matched '/source?scope=AppiumAUT' to command name 'getPageSource'
[debug] [XCUITestDriver@3310 (ecb76e6e)] Proxying [GET /source?scope=AppiumAUT] to [GET http://127.0.0.1:8100/session/98FA7F4B-D53C-4ABE-A507-CC375E38AF9D/source?scope=AppiumAUT] with no body
[debug] [XCUITestDriver@3310 (ecb76e6e)] Got response with status 200: {"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AppiumAUT>\n  <XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" name=\"DaveDebug\" label=\"DaveDebug\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"390\" height=\"844\" index=\"0\">\n    <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"390\" height=\"844\" index=\"0\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"390\" height=\"844\" index=\"0\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"390\" height=\"844\" index=\"0\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"390\" height=\"844\" index=\"0\">\n            <XCUIElementTypeOther type=\"...
[debug] [XCUITestDriver@3310 (ecb76e6e)] Responding to client with driver.getPageSource() result: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AppiumAUT>\n  <XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" name=\"DaveDebug\" label=\"DaveDebug\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"390\" height=\"844\" index=\"0\">\n    <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"390\" height=\"844\" index=\"0\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"390\" height=\"844\" index=\"0\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"390\" height=\"844\" index=\"0\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"390\" height=\"844\" index=\"0\">\n            <XCUIElementTypeOther type=\"XCUIEleme...
[HTTP] <-- GET /session/ecb76e6e-0531-49df-96f8-7293231ced3f/source 200 11018 ms - 29449
[HTTP] 
```

With:
`driver.updateSettings({ snapshotMaxDepth: 65 });`

Page source errors out.

```
[debug] [XCUITestDriver@7067 (6cb0f6d6)] Calling AppiumDriver.getPageSource() with args: ["6cb0f6d6-5d38-4ef0-814d-d5a4823a1c29"]
[debug] [XCUITestDriver@7067 (6cb0f6d6)] Executing command 'getPageSource'
[debug] [XCUITestDriver@7067 (6cb0f6d6)] Matched '/source?scope=AppiumAUT' to command name 'getPageSource'
[debug] [XCUITestDriver@7067 (6cb0f6d6)] Proxying [GET /source?scope=AppiumAUT] to [GET http://127.0.0.1:8100/session/644713E6-FF62-4E08-8C2B-615E5B94B930/source?scope=AppiumAUT] with no body
[Xcode] 2023-03-13 13:37:47.634974-0700 WebDriverAgentRunner-Runner[27620:4534967] Getting the most recent active application (out of 1 total items)
[Xcode] 
[Xcode] 2023-03-13 13:37:47.636365-0700 WebDriverAgentRunner-Runner[27620:4534967] The following attributes were requested to be included into the XML: {(
[Xcode]     FBTypeAttribute,
[Xcode]     FBYAttribute,
[Xcode]     FBLabelAttribute,
[Xcode]     FBIndexAttribute,
[Xcode]     FBXAttribute,
[Xcode]     FBNameAttribute,
[Xcode]     FBHeightAttribute,
[Xcode]     FBAccessibleAttribute,
[Xcode]     FBValueAttribute,
[Xcode]     FBVisibleAttribute,
[Xcode]     FBWidthAttribute,
[Xcode]     FBEnabledAttribute
[Xcode] )}
[Xcode] 
[Xcode] 2023-03-13 13:37:47.636642-0700 WebDriverAgentRunner-Runner[27620:4534967] Waiting up to 2s until com.trydave.dave.testing is in idle state (including animations)
[Xcode]     t =   149.78s Wait for com.trydave.dave.testing to idle
[Xcode] 
[Xcode]     t =   149.79s Requesting snapshot of accessibility hierarchy for app with pid 5177
[Xcode] 
[XCUITestDriver@7067 (6cb0f6d6)] Got response with status 404: {"value":{"error":"stale element reference","message":"The previously found element \"Application 'com.trydave.dave.testing'\" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: Error kAXErrorIllegalArgument getting snapshot for element <AXUIElementRef 0x6000027f2610> {pid=5177} {uid=[ID:1 hash:0x0]}","traceback":"(\n\t0   CoreFoundation                      0x00007ff8004288ab __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007ff80004dba3 objc_exception_throw + 48\n\t2   WebDriverAgentLib                   0x000000010f554fd3 -[XCUIElement(FBUtilities) fb_takeSnapshot] + 723\n\t3   WebDriverAgentLib                   0x000000010f555287 -[XCUIElement(FBUtilities) fb_snapshotWithAttributes:maxDepth:] + 183\n\t4   WebDriverAgentLib                   0x000000010f506b8a +[FBXPath writeXmlWithRootElement:indexPath:elementStore:includedAttributes:writer:] + 778\n\t5   WebDriverAgentLib                   0x000000010f5061cb +[FB...
[debug] [W3C] Matched W3C error code 'stale element reference' to StaleElementReferenceError
[debug] [XCUITestDriver@7067 (6cb0f6d6)] Encountered internal error running command: StaleElementReferenceError: The previously found element "Application 'com.trydave.dave.testing'" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: Error kAXErrorIllegalArgument getting snapshot for element <AXUIElementRef 0x6000027f2610> {pid=5177} {uid=[ID:1 hash:0x0]}
[debug] [XCUITestDriver@7067 (6cb0f6d6)]     at errorFromW3CJsonCode (/Users/jeremiahgolden/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1034:25)
[debug] [XCUITestDriver@7067 (6cb0f6d6)]     at ProxyRequestError.getActualError (/Users/jeremiahgolden/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:909:14)
[debug] [XCUITestDriver@7067 (6cb0f6d6)]     at JWProxy.command (/Users/jeremiahgolden/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:340:19)
[debug] [XCUITestDriver@7067 (6cb0f6d6)]     at runMicrotasks (<anonymous>)
[debug] [XCUITestDriver@7067 (6cb0f6d6)]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [XCUITestDriver@7067 (6cb0f6d6)]     at XCUITestDriver.proxyCommand (/Users/jeremiahgolden/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:95:12)
[debug] [XCUITestDriver@7067 (6cb0f6d6)]     at XCUITestDriver.getNativePageSource (/Users/jeremiahgolden/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:26:19)
[debug] [XCUITestDriver@7067 (6cb0f6d6)]     at XCUITestDriver.getPageSource (/Users/jeremiahgolden/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:22:10)
[HTTP] <-- GET /session/6cb0f6d6-5d38-4ef0-814d-d5a4823a1c29/source 404 80 ms - 1733
```

**Comment by hdesai-dave** [comment] 2023-03-13 22:51
@Dan-Maor above comment has the info you asked for https://github.com/appium/appium/issues/18085#issuecomment-1410191521

**Comment by Dan-Maor** [comment] 2023-03-14 10:56
@hdesai-dave the fix in question is related to element lookup by Xpath, the page source flow does not go through this route.

Previously _locating_ elements nested in a depth of 54 was not possible when increasing the snapshot max depth, however it is possible after this change (in combination of setting the snapshot max depth to 60).

I've increased the tree depth of my test app to 60 and tried to use the page source command to retrieve the elements tree and was only successful after limiting the snapshot max depth specifically to 62. It seems that any value larger than 62 (at least in my test application) causes the snapshot retrieval to fail in the testmanagerd side with a `Too many nested arrays or dictionaries` CoreFoundation error. Unfortunately we have no influence of that limit (this error originates from CoreFoundation, meaning this limit is from the OS level), so it looks like 62 is the maximum value testmanagerd can handle.

**Comment by sidferreira** [comment] 2023-05-23 22:26
I'm having a similar issue... The first test/file will run OK, but the 2nd one will ignore the setting...
Even if I use `getSettings` and it returns `snapshotMaxDepth` as 60

**Comment by mykola-mokhnach** [comment] 2023-05-24 06:14
> I'm having a similar issue... The first test/file will run OK, but the 2nd one will ignore the setting...
> Even if I use `getSettings` and it returns `snapshotMaxDepth` as 60

Settings are reset to their default values if a session is killed. Make sure it is set for each test where it is needed

**Comment by sidferreira** [comment] 2023-05-24 15:53
@mykola-mokhnach, it was in the same session...

Anyways, this did the trick:

```
export const refreshSettings = async (): Promise<void> => {
  const s1 = await driver.getSettings();
  s1.snapshotMaxDepth = 61;
  await driver.updateSettings(s1);
  const s2 = await driver.getSettings();
  s2.snapshotMaxDepth = 60;
  await driver.updateSettings(s2);
};
```
Note that 60 was the initial value anyways...

**Comment by farouksabbek** [comment] 2023-08-02 14:00
I'm testing an iOS app,
I'm using this capabilitys on my Appium Inspector
```
{
  "appium:deviceName": "iPhone 14",
  "appium:platformName": "ios",
  "appium:platformVersion": "16.2",
  "appium:bundleId": "********",
  "appium:automationName": "XCUITest",
  "appium:settings[snapshotMaxDepth]": 70,
  "appium:settings[customSnapshotTimeout]": "50000"
}
```

I'm using Appium 2

Appium Inspector still loading and I don't the app source


I want to get xpath element with Appium inspector

Any help please

**Comment by sidferreira** [comment] 2023-08-02 14:53
> I'm testing an iOS app,
> I'm using this capabilitys on my Appium Inspector
> ```
> {
>   "appium:deviceName": "iPhone 14",
>   "appium:platformName": "ios",
>   "appium:platformVersion": "16.2",
>   "appium:bundleId": "********",
>   "appium:automationName": "XCUITest",
>   "appium:settings[snapshotMaxDepth]": 70,
>   "appium:settings[customSnapshotTimeout]": "50000"
> }
> ```
> 
> I'm using Appium 2
> 
> Appium Inspector still loading and I don't the app source
> 
> 
> I want to get xpath element with Appium inspector
> 
> Any help please

Depth must be below 63. 62 is max

**Comment by farouksabbek** [comment] 2023-08-03 07:43
> 

When I use depth 62, I still have element not visible, I can't get them? any solution please?

**Comment by sidferreira** [comment] 2023-08-03 19:45
> > 
> 
> When I use depth 62, I still have element not visible, I can't get them? any solution please?

Yes, it probably means it is too deeply nested

**Comment by jlipps** [comment] 2023-08-04 17:02
> so any solution to get the elements please?

work with your dev team to adjust the number of elements or to adjust accessibility settings so only relevant elements are exposed to the accessibility layer.

**Comment by Thenlie** [comment] 2023-10-13 22:30
> Depth must be below 63. 62 is max

Would you mind sharing the documentation where you found this?

**Comment by hdesai-dave** [comment] 2023-10-16 20:34
> > so any solution to get the elements please?
> 
> work with your dev team to adjust the number of elements or to adjust accessibility settings so only relevant elements are exposed to the accessibility layer.

Haven’t found any way to do it with react native apps, what this thread is about I guess. I would suggest putting a disclaimer in docs about no react native iOS support for appium!

**Comment by ggroce** [comment] 2023-11-20 15:47
I also found I had to set snapshotMaxDepth to 62 to prevent errors.  I originally had it set to 100, in a React Native iOS app.  Suddenly, on one specific screen, Appium began failing to see the screen, and it wasn't giving good feedback as to why.  I began dissecting the screen, removing React components as I thought it was a problem with the React Native code.  After a fair bit of trouble shooting, I realized it was a snapshotMaxDepth issue, and at some point in production, the application's depth was pushed beyond Appium's limit, (62).

**Comment by Dor-bl** [comment] 2024-01-14 09:25
@jlipps @mykola-mokhnach, If I set the value to 20 and I still get much more than that on nested elements, should I open a new issue?

**Comment by jlipps** [comment] 2024-01-15 21:34
@Dor-bl sure, just open a new issue with all the relevant logs

**Comment by tamaniniandre** [comment] 2024-04-11 14:04
Hey guys,
I created this topic in the Apple's forum, maybe if everyone send some message to bump up this subject, we can get some help from the Apple on it:

https://developer.apple.com/forums/thread/749918

**Comment by trevor-coleman** [comment] 2024-05-14 17:26
Been investigating this for a client, and I think I may have found a clue as to the root cause.

In several threads about this people have reported using XCTest and getting a CoreFoundation error `Too many nested arrays or dictionaries`.

So I searched for that and found this thread on the Apple Developer Forums:
https://forums.developer.apple.com/forums/thread/688010

There, someone reports that a change in iOS 14.4 resulted in them getting errors when creating XML Property Lists over 100 items:

> Ever since iOS 14.4, the process fails at dataWithPropertyList, with errors as: "Property list invalid for format: 100 (Too many nested arrays or dictionaries)" and in iOS 14.7 a little more verbose: "Property list invalid for format: 100 (Too many nested arrays or dictionaries please use kCFPropertyListBinaryFormat_v1_0 instead which supports references)"

And the response indicates that this was a deliberate change:

> his was a deliberate change to improve security and reliability (r. 61207578). The specific limit is arbitrary, but it reflects that fact that property lists were always intended to be a convenient way to wrangle a relatively simple data structure, rather than the ultimate API for serialization.

So I think one of the actors in the chain is using a PropertyList for serialization, and that it's running in to this arbitrary limit imposed on the class. The error is coming out of CoreFramework, because that's where the serialization is being done, but the problem is really the place where that is being called. 

The solution would be to use a different type of serialization, that wouldn't be subject to the 100-item limit. I'll take a look to see if I can find it, but I'm not the most experienced at this level of depth, so i'd encourage others to investigate as well.

Not sure where this serialization would be happening -- between React Native and
