### ISSUE TITLE
Can't switch back to native app view from webview in 1.4.0 against saucelab env.

### ISSUE THREAD

**Issue by moshimoshibye** [appium/appium#5122] opened 2015-05-14 23:23 UTC
Found a regression in 1.4.0 that is blocking us from running our Appium scripts against SauceLab environment. We have a hybrid application and once you switch to the WEBVIEW, you can no longer switch back to the NATIVE_APP. 

Related post:
https://discuss.appium.io/t/cant-switch-back-to-native-app-view-from-web-view-for-android-4-4-on-sauce/1460/6
And: https://github.com/appium/appium/issues/4429

It was fixed in 1.3.7: https://github.com/appium/appium/issues/4702

But it's broken in 1.4.0 again.

**Comment by moshimoshibye** [comment] 2015-05-14 23:24
@jlipps

**Comment by jlipps** [comment] 2015-05-27 16:09
have you created a sauce labs help ticket?

**Comment by sebv** [comment] 2015-06-03 10:09
@imurchie @moizjv any ideas?

**Comment by Jonahss** [comment] 2015-07-01 20:53
Duplicate of #5305

The issue is that appium was responding with the chromedriver session id, which it should keep private. The python client would pick up this new session id and try to run commands with it (rather than keeping the same session id as the test was started in). We are releasing version 1.4.7 specifically to fix this issue smile

Expect this to be released today or tomorrow.

If you think your issue was different, please respond here.

**Closed by Jonahss** 2015-07-01 20:53 UTC
Labels: Android, Bug
