### ISSUE TITLE
How does the UI automator2 noReset behave from v2.7.0 vs v2.4.7

### ISSUE THREAD

**Issue by Auto81** [appium/appium#17503] opened 2022-09-17 01:55 UTC
### Discussed in https://github.com/appium/appium/discussions/17489

<div type='discussions-op-text'>

<sup>Originally posted by **Auto81** September 15, 2022</sup>
https://github.com/appium/appium-uiautomator2-driver/pull/537

Having just updated to uiautomator2 driver (v2.7.0 from 2.4.7) how does the above change now affect devices under test

Have been using

noReset:true
forceAppLaunch:true

Which kept our app under test registered on a device (noReset), and always started our app up into the login screen (forceAppLaunch)

This was applicable to the windows driver and the XCUITest driver too. ie all 3 drivers would force the app to open to the login screen as expected. 

however now the android app is staying logged in rather than relaunching the app to the login screen on android.

looks like there is now disparity between the drivers?</div>

**Comment by mykola-mokhnach** [comment] 2022-09-17 07:34
Possible duplicate of https://github.com/appium/appium/issues/17455

**Closed** 2022-09-26 08:07 UTC
Labels: UIAutomator2
