### ISSUE TITLE
(iOS) App not found (UIAElementNil is not a function)

### ISSUE THREAD

**Issue by mgehlen** [appium/appium#4464] opened 2015-01-30 18:08 UTC
Hello,

I am using Appium now to test six Apps in total (3 for iOS and 3 for Android).
Five out of these six Apps work fine, but the last one on iOS troubles me.

When I use the Inspector, arc or try to run my tests the App and its elements are simply not found. Furthermore the App hangs when I try to use Appium, but works fine when I use it without Appium.

The behavior is especially strange since all iOS Apps are basically the same, but for different countries. They use mostly the same code and features, but some features are activated only for one country. 
The problematic App is the only one, which shows an Advertisement as a Rollover page pretty much at the start, but when I received a version with the Rollover deactivated I still run into the problem.

Here is my output for page:

[8] pry(main)> page
````
get /context
get /context
post /execute
{
    :script => "UIATarget.localTarget().frontMostApp().windows()[0].getTree()"
}
Selenium::WebDriver::Error::JavascriptError: UIAElementNil is not a function (evaluating 'UIATarget.localTarget().frontMostApp().windows()[0].getTree()')
from /Users/marcelg/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/response.rb:52:in `assert_ok'
[9] pry(main)>
````

source does not give me anything either:
````
[10] pry(main)> source
get /source
<?xml version="1.0" encoding="UTF-8"?>
<AppiumAUT>
  <UIAApplication name="" label="" value="" dom="" enabled="false" valid="false" visible="false" hint="" path="/0" x="0" y="0" width="0" height="0">
    </UIAApplication>
</AppiumAUT>
````
In my appium log file I see the following message:
````
warn: Remote debugger did not list mx.myApp.client.iphone among its available apps
info: [debug] [REMOTE] Disconnecting from remote debugger
info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP"],"sessionId":"4c15ca41-a92d-4d10-9aef-13c558ac67ce"}
info: <-- GET /wd/hub/session/4c15ca41-a92d-4d10-9aef-13c558ac67ce/contexts 200 5.599 ms - 86 {"status":0,"value":["NATIVE_APP"],"sessionId":"4c15ca41-a92d-4d10-9aef-13c558ac67ce"}
info: [debug] [REMOTE] Debugger socket disconnected
````

I am not sure if this is a red herring, since I see the message for other Apps, which work fine, too.

I am using Appium 1.3.4, iOS 8.1 and I am working with the simulator.

Does anyone know what might break the communication between App and Appium here?

Thank you very much,

  mgehlen

**Comment by mgehlen** [comment] 2015-01-30 18:15
the symptoms seem pretty comparable to this issue:
#4455 IOS: Issue with page source parsing

But I face the problem right from the start and waiting does not change the behavior

**Comment by bootstraponline** [comment] 2015-01-30 23:03
This is the same issue I reported a few days ago.

- https://github.com/appium/appium/issues/4456

iOS automation is broken.

**Comment by jlipps** [comment] 2015-03-26 21:00
closing as dupe of #4456

**Closed by jlipps** 2015-03-26 21:00 UTC
Labels: NeedsTriage
