### ISSUE TITLE
driver.contexts not reliably finding webview

### ISSUE THREAD

**Issue by EricDusseau** [appium/appium#10059] opened 2018-01-23 18:56 UTC
Appium server: 1.7.2
Simulator iOS
osx: 10.12
Appium-Python-Client==0.26
ios: 11.2

Using the following I would expect to find two views, native and a webview. The native view is always returned but 9/10 times it fails to return the webview context.

```
        contexts = self.driver.contexts
        print "List of contexts " + str(contexts)
        webview = contexts[1]
        appview = contexts[0]
        self.driver.switch_to.context(webview)
        print "Switched to " + str(webview)
        # Click on link in webview
        self.driver.find_element_by_xpath('/html/body/p[2]/a').click()
```
Because the only finds the native context it obviously then fails with the following error

```
test_1_sso (__main__.SmokeTest) ... List of contexts [u'NATIVE_APP']
ERROR

======================================================================
ERROR: test_1_sso (__main__.SmokeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_sso_ios.py", line 121, in test_1_sso
    webview = contexts[1]
IndexError: list index out of range
```
Server Log:
https://gist.github.com/EricDusseau/c4ba26cb25cd3ce0ee53c69f3aae18f3

**Comment by mykola-mokhnach** [comment] 2018-01-23 18:59
Please attach full server log.

**Comment by EricDusseau** [comment] 2018-01-23 19:18
Updated comment with full server log

**Comment by mykola-mokhnach** [comment] 2018-01-23 20:39
Possible duplicate of https://github.com/appium/appium/issues/10028

**Comment by EricDusseau** [comment] 2018-01-25 12:39
I don't believe this is the same issue as [#10028](https://github.com/appium/appium/issues/10028).  The resolution of that was an update to the java appium client.  In my case, it seems to be a server-side thing.   In the server logs I'm seeing "No web frames found" and "Responding to client with driver.getContexts() result: ["NATIVE_APP"]"


As I mentioned before, there is a small success rate for finding the webview context.  This morning it was able to find the webview on the first try.  However, on the following runs it failed each time with no change to the code or environment. 

Here is the server log from the successful run:
https://gist.github.com/EricDusseau/fa7fdeb80ebd5f7b7f70d2e1fafca80c

**Comment by imurchie** [comment] 2018-01-30 14:59
This seems like a timing issue. Can you run the server with `--log-timestamp` and re-post the logs? This will show where the time is going on the context command.

**Comment by EricDusseau** [comment] 2018-01-30 18:42
Server logs with timestamps

https://gist.github.com/EricDusseau/0796a52b83470cf8ec5ce9a575995af9

**Comment by imurchie** [comment] 2018-01-30 19:28
Not sure what went wrong, but there were no timestamps added. Logs should look something like
```
$ appium --log-timestamp                                                                                                                 6.12.0
2018-01-30 19:27:21:582 - [Appium] Welcome to Appium v1.7.2 (REV 40e40975ebd3593d08c3f83de2546258f7ddf11d)
2018-01-30 19:27:21:585 - [Appium] Non-default server args:
2018-01-30 19:27:21:586 - [Appium]   logTimestamp: true
2018-01-30 19:27:21:639 - [Appium] Appium REST http interface listener started on 0.0.0.0:4723
```

**Comment by EricDusseau** [comment] 2018-01-31 12:20
Whoops, wires got crossed there somehow.  Correct log (with timestamps)
https://gist.github.com/EricDusseau/0796a52b83470cf8ec5ce9a575995af9

**Comment by bniehuser** [comment] 2018-06-08 20:08
any update on this?  we are finding this to still be an issue in our tests.

**Comment by mykola-mokhnach** [comment] 2018-08-27 09:08
Closed as inactive

**Closed by mykola-mokhnach** 2018-08-27 09:08 UTC
Labels: Mobile Safari
