### ISSUE TITLE
Original error: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\SanSkp\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk

### ISSUE THREAD

**Issue by Sanskp** [appium/appium#15224] opened 2021-03-26 05:31 UTC
## The problem

(Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\SanSkp\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk'. Original error: Could not find 'apksigner.jar' in ["C:\\android-sdk\\platform-tools\\apksigner.jar","C:\\android-sdk\\emulator\\apksigner.jar","C:\\android-sdk\\cmdline-tools\\latest\\bin\\apksigner.jar","C:\\android-sdk\\tools\\apksigner.jar","C:\\android-sdk\\tools\\bin\\apksigner.jar","C:\\android-sdk\\apksigner.jar"]. Do you have Android Build Tools installed at 'C:\android-sdk'?) 
 this type error occur when run the program 

## Environment
Appium version (or git revision) that exhibits the issue: 1.20.2
Mobile platform/version under test: Android
Real device or emulator/simulator: real device with android 10

## Details

java.lang.reflect.InvocationTargetException
Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\SanSkp\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk'. Original error: Could not find 'apksigner.jar' in ["C:\\android-sdk\\platform-tools\\apksigner.jar","C:\\android-sdk\\emulator\\apksigner.jar","C:\\android-sdk\\cmdline-tools\\latest\\bin\\apksigner.jar","C:\\android-sdk\\tools\\apksigner.jar","C:\\android-sdk\\tools\\bin\\apksigner.jar","C:\\android-sdk\\apksigner.jar"]. Do you have Android Build Tools installed at 'C:\android-sdk'?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'SANSKPLAPTOP', ip: '192.168.0.112', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.10'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\SanSkp\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk'. Original error: Could not find 'apksigner.jar' in ["C:\\android-sdk\\platform-tools\\apksigner.jar","C:\\android-sdk\\emulator\\apksigner.jar","C:\\android-sdk\\cmdline-tools\\latest\\bin\\apksigner.jar","C:\\android-sdk\\tools\\apksigner.jar","C:\\android-sdk\\tools\\bin\\apksigner.jar","C:\\android-sdk\\apksigner.jar"]. Do you have Android Build Tools installed at 'C:\android-sdk'?
    at getResponseForW3CError (C:\Users\SanSkp\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\SanSkp\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'SANSKPLAPTOP', ip: '192.168.0.112', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.10'
Driver info: driver.version: AppiumDriver
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\SanSkp\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk'. Original error: Could not find 'apksigner.jar' in ["C:\\android-sdk\\platform-tools\\apksigner.jar","C:\\android-sdk\\emulator\\apksigner.jar","C:\\android-sdk\\cmdline-tools\\latest\\bin\\apksigner.jar","C:\\android-sdk\\tools\\apksigner.jar","C:\\android-sdk\\tools\\bin\\apksigner.jar","C:\\android-sdk\\apksigner.jar"]. Do you have Android Build Tools installed at 'C:\android-sdk'?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'SANSKPLAPTOP', ip: '192.168.0.112', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.10'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\SanSkp\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk'. Original error: Could not find 'apksigner.jar' in ["C:\\android-sdk\\platform-tools\\apksigner.jar","C:\\android-sdk\\emulator\\apksigner.jar","C:\\android-sdk\\cmdline-tools\\latest\\bin\\apksigner.jar","C:\\android-sdk\\tools\\apksigner.jar","C:\\android-sdk\\tools\\bin\\apksigner.jar","C:\\android-sdk\\apksigner.jar"]. Do you have Android Build Tools installed at 'C:\android-sdk'?

**Comment by mykola-mokhnach** [comment] 2021-03-26 05:46
Duplicate of https://github.com/appium/appium/issues/15185

**Closed by mykola-mokhnach** 2021-03-26 05:46 UTC
