### ISSUE TITLE
Unable to accept alert 

### ISSUE THREAD

**Issue by Sandarekha** [appium/appium#8120] opened 2017-03-29 04:58 UTC
## The problem

I want to automate to save photo in my device. But in first time I have to give permission. I have used "accept alert", but cannot accept the alert for allow to access the photo library. It shows the test passed in green , when I execute the test, but this popup still appear in view and photo is not saved.

![screen shot 2017-03-28 at 4 30 13 pm](https://cloud.githubusercontent.com/assets/24934240/24439185/4104b872-146a-11e7-9161-41eaf9d913f9.png)

## Environment

Appium v1.6.4-beta 
Xcode 8.2 
macOs Sierra 10.12

## Details
I have used capabilities, accept alert, xpath, findelementByName.. but none worked here. 

With capabilities , it says 
    [XCUITest] The capabilities ‘autoAcceptAlerts’ and ‘autoDismissAlerts’ do not work for XCUITest-based tests. Please adjust your alert handling accordingly 

## Code To Reproduce Issue [ Good To Have ]

    //Check Save 
    driver.findElement(By.id("Save")).click();
    driver.switchTo().alert().accept();

    capabilities.setCapability("autoAcceptAlerts", true);

**Comment by mykola-mokhnach** [comment] 2017-03-29 06:13
Please attach full applium log containing alert.accept invokation.

**Comment by Sandarekha** [comment] 2017-03-29 06:23
Thanks, here it is.. 
https://gist.github.com/Sandarekha/6fe7d50efb9ba143219694af7e41b353 

This alert still appears in the screen and then it says unable to find the next element "kidsdesk_toolbar_right_home".
This is my code in java.
https://gist.github.com/Sandarekha/f350a6a4c52bbbf68096fa4459a3afb3

**Comment by mykola-mokhnach** [comment] 2017-03-29 06:28
I probably know what the problem is. XCTest has a know [bug](https://github.com/facebook/WebDriverAgent/issues/300) about interactions in landscape mode. Just change to portrait, accept the alert and then change back to landscape to workaround it.

**Comment by Sandarekha** [comment] 2017-03-29 06:50
@mykola-mokhnach 
No luck .

	
    	//Check Save 
    	driver.findElement(By.id("Save")).click();
    	driver.rotate(ScreenOrientation.PORTRAIT);
		driver.switchTo().alert().accept();
    	

It fails with this msg
 org.openqa.selenium.WebDriverException: Unable To Rotate Device 
Command duration or timeout: 7.03 seconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:44 -0700'
System info: host: 'Supuns-Mac-mini.local', ip: '192.168.8.106', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12', java.version: '1.8.0_121'
Driver info: io.appium.java_client.ios.IOSDriver

Appium log
https://gist.github.com/Sandarekha/a2b89d300fcb8db274ce64c7b83081c3

Is there anything to do to accept this alert?

**Comment by mykola-mokhnach** [comment] 2017-03-29 07:06
You can try to [tap by coordinates](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md). But it will be necessary to literally guess the correct tap coordinate.

**Comment by Sandarekha** [comment] 2017-03-29 07:09
I have tried with 
    driver.tap(fingers, x, y, duration);

Is there a way to get java code for mobile: tap?

**Comment by mykola-mokhnach** [comment] 2017-03-29 07:11
There is a link in my recent message. Just make sure your beta contains the recent release of xcuitest driver

**Comment by Sandarekha** [comment] 2017-03-29 07:27
Well, now..

org.openqa.selenium.UnsupportedCommandException: Unknown command, all the mobile commands except scroll and swipe have been removed. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 42 milliseconds

This is what I have used. 
HashMap<String, String> tfTap = new HashMap<String, String>();  	tfTap.put("element","//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeImage[1]");
    		    driver.executeScript("mobile: tap", tfTap);

My reference library java-client-5.0.0-BETA6.jar

**Comment by mykola-mokhnach** [comment] 2017-03-29 07:28
> Just make sure your beta contains the recent release of xcuitest driver

Simply reinstall your appium beta to achieve this

**Comment by Sandarekha** [comment] 2017-03-29 07:32
https://github.com/appium/appium-desktop/releases
appium-desktop-1.0.0-beta.5.dmg
correct?

**Comment by mykola-mokhnach** [comment] 2017-03-29 07:39
```
npm remove -g appium
npm install -g appium@1.6.4-beta
```

**Comment by Sandarekha** [comment] 2017-03-29 09:03
Please have a look.. 
This does not work. Why? 

        float[] tftap = {500f,400f};  
    	 driver.executeScript("mobile: tap", tftap);

Error 
java.lang.ClassCastException: [F cannot be cast to [Ljava.lang.Object;

**Comment by dpgraham** [comment] 2017-07-18 22:41
Closing this. If this is still a problem I'll re-open.

**Closed by dpgraham** 2017-07-18 22:41 UTC
Labels: NeedsTriage
