### ISSUE TITLE
Error during installation process - Path must be a string

### ISSUE THREAD

**Issue by jovana119** [appium/appium#13180] opened 2019-09-04 13:06 UTC
## The problem

When I start using appium@beta version 1.14.0-beta.2, I got the error during installation process on the real device: **Path must be a string. Received undefined.**

## Environment

* Appium version: 1.14.0-beta.2
* Real device or emulator/simulator: real device
* Mobile platform/version under test: 13.0
* Npm: 6.11.3
* Node: 8.12.0

## Details

This is my capabilities:    
```
DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
desiredCapabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 5000);
desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, System.getProperty("deviceName"));
desiredCapabilities.setCapability(MobileCapabilityType.UDID, System.getProperty("deviceUdid"));
desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, System.getProperty("platformVersion"));
desiredCapabilities.setCapability(MobileCapabilityType.APP, System.getProperty("appFilePath"));
desiredCapabilities.setCapability("autoGrantPermissions", true);
desiredCapabilities.setCapability(MobileCapabilityType.FULL_RESET, true);
desiredCapabilities.setCapability(MobileCapabilityType.NO_RESET, false);
desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, Settings.IOS_AUTOMATION_NAME);
desiredCapabilities.setCapability("usePrebuiltWDA", true);
mobileDriver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), desiredCapabilities);
```

## Link to Appium logs

Here are the logs: https://gist.github.com/jovana119/2db809a17d8eb00736a807a3d763bccf

**Comment by mykola-mokhnach** [comment] 2019-09-04 13:08
Possible duplicate of https://github.com/appium/appium/issues/13115

Please reinstall appium@beta to get the recent fixes and try again

**Comment by jovana119** [comment] 2019-09-04 14:01
@mykola-mokhnach  I already tried that and the same error is happening.

**Comment by mykola-mokhnach** [comment] 2019-09-04 14:02
@umutuzgur Perhaps, It's something for you

**Comment by umutuzgur** [comment] 2019-09-04 14:10
I see that node 8 is being used. Please try it with node 10

**Comment by jovana119** [comment] 2019-09-05 07:32
@umutuzgur  I tried and it didn't help. Now I have npm:6.9.0 and node:10.16.3 and I just got the other error:
```
2019-09-05 07:27:12:785 - [debug] ESC[35m[XCUITest]ESC[39m Installing '/Users/Desktop/test.app' on device with UUID 'cc31a72a3e22b907ae22668a1e426e20216881ed'...
2019-09-05 07:27:12:966 - ESC[35m[XCUITest]ESC[39m Error was thrown during the installation process
2019-09-05 07:27:13:045 - ESC[35m[XCUITest]ESC[39m TimeoutError: operation timed out
2019-09-05 07:27:13:045 - ESC[35m[XCUITest]ESC[39m     at afterTimeout (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/timers.js:46:19)
2019-09-05 07:27:13:045 - ESC[35m[XCUITest]ESC[39m     at Timeout.timeoutTimeout [as _onTimeout] (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/timers.js:76:13)
2019-09-05 07:27:13:045 - ESC[35m[XCUITest]ESC[39m     at ontimeout (timers.js:436:11)
2019-09-05 07:27:13:045 - ESC[35m[XCUITest]ESC[39m     at tryOnTimeout (timers.js:300:5)
2019-09-05 07:27:13:045 - ESC[35m[XCUITest]ESC[39m     at listOnTimeout (timers.js:263:5)
2019-09-05 07:27:13:045 - ESC[35m[XCUITest]ESC[39m     at Timer.processTimers (timers.js:223:10)
2019-09-05 07:27:13:060 - ESC[35m[XCUITest]ESC[39m Error: Could not install app: 'operation timed out'
2019-09-05 07:27:13:060 - ESC[35m[XCUITest]ESC[39m     at IOSDeploy.install (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:41:13)
2019-09-05 07:27:13:061 - [debug] ESC[35m[BaseDriver]ESC[39m Event 'newSessionStarted' logged at 1567668433061 (09:27:13 GMT+0200 (Central European Summer Time))
2019-09-05 07:27:13:062 - [debug] ESC[35m[W3C]ESC[39m Encountered internal error running command: Error: Could not install app: 'operation timed out'
2019-09-05 07:27:13:062 - [debug] ESC[35m[W3C]ESC[39m     at IOSDeploy.install (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:41:13)
2019-09-05 07:27:13:226 - ESC[35m[HTTP]ESC[39m ESC[37m<-- POST /wd/hub/session ESC[39mESC[31m500ESC[39m ESC[90m9089 ms - 585ESC[39m
```

**Comment by mykola-mokhnach** [comment] 2019-09-06 19:54
Have you tried to reboot the phone?

**Comment by jovana119** [comment] 2019-09-09 07:31
Yes and it didn't help. I'm still getting operation timed out error during installation.

**Comment by Winning117** [comment] 2019-09-13 19:34
I'm getting this timeout error as well

* Appium version (or git revision) that exhibits the issue: 1.15.0-beta.1
* Desktop OS/version used to run Appium: 10.14.5
* Node.js version: 10.16.2
* Npm version: 6.11.3
* Mobile platform/version under test: iOS XS Max 13.1
* Real device or emulator/simulator: Real device


Log:
`[debug] [35m[W3C][39m Encountered internal error running command: Error: Could not install app: 'operation timed out'`
`[debug] [35m[W3C][39m     at IOSDeploy.install (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:41:13)`



I can manually transfer the app via Xcode, but if I try to transfer it using ios-deploy it will hang. I tried `ios-deploy -id 00008020-000829EA1428002E --bundle test.ipa`
And it prints out the following:
`[....] Waiting for iOS device to be connected`
`Skipping 00008020-000829EA1428002E (D331pAP, D331pAP, uknownos, unkarch) a.k.a. 'XS Max iPhone'.`
Normally this process only takes a few seconds and doesn't hang.

**Comment by hardik-plume** [comment] 2019-09-17 15:21
Any update here? 2 days for ios13 to hit customers. How do we release apps without running automation?

**Comment by Winning117** [comment] 2019-09-17 15:26
> Any update here? 2 days for ios13 to hit customers. How do we release apps without running automation?

Read the reference right above your post.

**Comment by hardik-plume** [comment] 2019-09-17 15:55
Have you tried latest beta and confirmed the fix?

**Comment by Winning117** [comment] 2019-09-17 16:01
@hardik-plume The fix isn't included in the latest beta because it wasn't patched until after, so no.

**Comment by imurchie** [comment] 2019-09-17 16:07
The beta works such that it should get the latest versions of things.

**Comment by hardik-plume** [comment] 2019-09-17 16:38
I will try in couple hours and update

**Comment by hardik-plume** [comment] 2019-09-17 16:58
able to install the app now.

**Comment by mykola-mokhnach** [comment] 2019-09-17 18:10
Closed as fixed. Kudos to @Volune for finding the problem cause and fixing it

**Closed by mykola-mokhnach** 2019-09-17 18:10 UTC
Labels: ThirdParty, XCUITest
