### ISSUE TITLE
UIAutomator2(1.6.5) StaleElementReferenceException

### ISSUE THREAD

**Issue by wangtao169447** [appium/appium#8940] opened 2017-07-30 13:19 UTC
## The problem
execute button.get_attribute('text') ,throw StaleElementReferenceException, detail logs like below:
https://gist.github.com/wangtao169447/6e63a8ab514e1db3778a6e20064b0af0

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac os
* Node.js version (unless using Appium.app|exe):v8.1.3
* Mobile platform/version under test:android 7.0
* Real device or emulator/simulator:real devices
* Appium CLI or Appium.app|exe: Appium CLI

## Details
execute button.get_attribute('text') function

**Comment by mykola-mokhnach** [comment] 2017-07-30 14:32
Duplicate of https://github.com/appium/appium/issues/7517

**Closed by mykola-mokhnach** 2017-07-30 14:32 UTC
