### ISSUE TITLE
fatal error when building scheme "RoutingHTTPServer tvOS" in RoutingHTTPServer.xcodeproj with "sh Scripts/bootstrap.sh -d"

### ISSUE THREAD

**Issue by nana110110** [appium/appium#15093] opened 2021-02-09 14:35 UTC
## The problem

I am experiencing a fatal error when I run "sh Scripts/bootstrap.sh -d" for appium-webdriveragent.

## Environment

* Appium version 1.20.0
* Desktop OS/version used to run Appium:   macOS 11.0.1
* Xcode: 12.4

## Details

I am seeing the following error when I run "sh Scripts/bootstrap.sh -d" for appium-webdriveragent.

-e Fetching dependencies
*** Checking out RoutingHTTPServer at "v1.2.2"
*** Checking out YYCache at "1.1.0"
*** Cloning RoutingHTTPServer
*** Cloning YYCache
*** xcodebuild output can be found in /var/folders/nv/qb95pl7s5rx0vnbmj1wsgf000000gq/T/carthage-xcodebuild.SJXfDe.log
*** Building scheme "RoutingHTTPServer tvOS" in RoutingHTTPServer.xcodeproj
A shell task (/usr/bin/xcrun lipo -create /Users/projection/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/RoutingHTTPServer/v1.2.2/Build/Intermediates.noindex/ArchiveIntermediates/RoutingHTTPServer\ tvOS/IntermediateBuildFilesPath/UninstalledProducts/appletvos/RoutingHTTPServer.framework/RoutingHTTPServer /Users/projection/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/RoutingHTTPServer/v1.2.2/Build/Products/Release-appletvsimulator/RoutingHTTPServer.framework/RoutingHTTPServer -output /Users/projection/.Trash/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/tvOS/RoutingHTTPServer.framework/RoutingHTTPServer) failed with exit code 1:
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/projection/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/RoutingHTTPServer/v1.2.2/Build/Intermediates.noindex/ArchiveIntermediates/RoutingHTTPServer tvOS/IntermediateBuildFilesPath/UninstalledProducts/appletvos/RoutingHTTPServer.framework/RoutingHTTPServer and /Users/projection/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/RoutingHTTPServer/v1.2.2/Build/Products/Release-appletvsimulator/RoutingHTTPServer.framework/RoutingHTTPServer have the same architectures (arm64) and can't be in the same fat output file

Building universal frameworks with common architectures is not possible. The device and simulator slices for "RoutingHTTPServer" both build for: arm64
Rebuild with --use-xcframeworks to create an xcframework bundle instead.

-------------------------------------------------------------------------------------------------------------

I can still open WebDriverAgent.xcodeproj but build will fail due to "RoutingHTTPServer/RoutingConnection.h' file not found"

Can anyone help solve this problem. Thank you.

**Comment by mykola-mokhnach** [comment] 2021-02-09 15:11
Duplicate of https://github.com/appium/appium/issues/15084

Since v. 1.20 xcuitest driver does not need to fetch Carthage dependencies

**Closed by mykola-mokhnach** 2021-02-09 15:11 UTC

**Comment by houshuo521** [comment] 2021-09-03 08:25
this is wda，what about appium？

**Comment by jerimiah797** [comment] 2021-09-24 19:56
A couple points - 

1) You shouldn't use the old, archived Facebook WDA anymore. Any tutorial you are following that shows that method is outdated. It's all built in to Appium at this point. 

2) The solution to the compilation problem that worked for me is to run the command 'carthage update --use-xcframeworks' after the bootstrap.sh script, just in case you are curious or are grandfathered into using the old solution.
