### ISSUE TITLE
Appium doesn't work for testing WKWebViews

### ISSUE THREAD

**Issue by jvoll** [appium/appium#5839] opened 2015-11-16 23:05 UTC
See discussion thread: https://discuss.appium.io/t/appium-and-wkwebview/4769

We are unable to run our Appium tests  on our iOS apps after switching to WKWebView (from UIWebView). This is a blocker for us as we don't want our entire test-suite to become useless but do want the benefits that WKWebView gives us.

WKWebViews are still visible in desktop safari for debugging, but Appium seems to be unable to find them.

**Comment by mobify-derrick** [comment] 2016-01-20 20:47
This is a pretty blocking issue as more apps are moving towards using WKWebView.

**Comment by vicwomg** [comment] 2016-01-21 19:17
+1 our app is moving to WKWebViews, as I imagine all modern apps will be, and we can no longer switch to these contexts

**Comment by subodhbakshi** [comment] 2016-01-25 01:08
+1, we moved the WKWebViews in a recent app refactor and this has caused high impact on our automation tests that switch context to webviews

**Comment by ellenmobify** [comment] 2016-01-27 03:40
Throwing in my +1 as I really hope Appium supports this soon.

**Comment by joshuarh** [comment] 2016-02-14 06:54
+1 This currently puts devs to a choice between creating a fast, modern hybrid app and being able to test it! Would love to have the best of both worlds here. :)

**Comment by konobi** [comment] 2016-02-26 18:20
It looks like apple have changed the way they want to do automated interaction with WKWebViews. It seems that UIAutomator doesn't have the ability to instrument WKWebViews like it can with UIWebView. So it looks like there'll need to be some sort of adaptor needed to get appium to use the javascript bridge for automating the WKWebView rather than trying with UIAutomation.

@jlipps does that sound about right?

**Comment by jlipps** [comment] 2016-02-27 00:40
@konobi hey man! Actually @scottdixon has done some work on this recently and it turns out that in recent versions of iOS appium works with WKWebView just fine. However if you have multiple WKWebViews going at once Appium can get confused about it. I believe there is a fix forthcoming for that. @scottdixon might have more details.

**Comment by bakshib4u** [comment] 2016-04-01 17:29
@scottdixon @jlipps Any further update on the fix for Appium getting confused with multiple WKWebViews? Is the fix forthcoming?

**Comment by elsh** [comment] 2016-04-06 22:51
Is there a fix or any workaround for the problem @bakshib4u and @subodhbakshi mentioned above?  Please give us some updates!

**Comment by adholaria** [comment] 2016-04-13 18:34
@scottdixon have any fix for handling multiple WKWebViews ?

**Comment by scottdixon** [comment] 2016-04-13 18:37
@adholaria - not yet. It's on the radar.

**Comment by adholaria** [comment] 2016-04-13 18:40
Okay. Thanks for the update. :)

**Comment by ericwengelking** [comment] 2016-04-13 20:15
FYI @wuhao5 @rafael-chavez

**Comment by VasilijSviridov** [comment] 2016-05-12 10:41
Any news ?

**Comment by jlipps** [comment] 2016-05-12 16:40
We're investigating more this week

**Comment by VasilijSviridov** [comment] 2016-06-10 14:19
any news ?

**Comment by imurchie** [comment] 2016-06-10 14:51
Appium 1.5.3 has support for WkWebViews, at least in our tests. It would be awesome if people who use WkWebViews could try it out and let us know how it works out in the real world. :)

**Comment by VasilijSviridov** [comment] 2016-06-10 15:05
well I tested it on iOS 8.3 iPhone 6 plus real device, and Appium gui doesn't see the WkWebView :/

**Comment by scottdixon** [comment] 2016-06-10 15:05
^ @ellenmobify

**Comment by scottdixon** [comment] 2016-06-10 15:07
@vasilijSviridov I think the latest GUI is 1.5.2. You'll need to install via NPM or from source until 1.5.3 GUI is released.

**Comment by VasilijSviridov** [comment] 2016-06-10 15:11
got it, give me some time to check it via npm

**Comment by VasilijSviridov** [comment] 2016-06-10 15:12
and the latest GUI  I have 1.5.3(Ara) :) @scottdixon

**Comment by VasilijSviridov** [comment] 2016-06-10 16:17
nope its not working with npm 1.5.3, same ids same strategy for iOS 8.* and for iOS 9.*, on 9.* device its working with 1.5.3 and 1.4.*, with iOS 8 its not working neither with 1.4.* neither with latest 1.5.3.
I double checked by getPageSource, on iOS 9.* device you get the whole set of webelements loaded via WKWebViews, on iOS 8 elements which are loaded via WKWebViews not exist(they are just missing)

**Comment by imurchie** [comment] 2016-06-10 17:25
Ok. As much information as you can provide (logs, commands, details of the test) would help with adding support.

**Comment by vicwomg** [comment] 2016-06-14 23:55
I'm seeing the same thing. WKWebviews work fine on iOS 9 now, but on iOS 8  the behavior is the same as before: they are not recognized.

**Comment by imurchie** [comment] 2016-06-15 20:56
Can you provide the logs? I cannot reproduce the problem with iOS 8.

**Comment by vicwomg** [comment] 2016-06-16 23:13
I think the issue surfaces when there are multiple wkwebviews. For iOS 8, appium does not return all the webviews that we're expecting. Probably just returns only the first one found. 

This is basically what I'm running in my test to demonstrate the issue:
> Set<String> s = client().getContextHandles(); 
> System.out.println("Available windows: " + s.toString());

iOS 8 returns: "Available windows: [NATIVE_APP, WEBVIEW_44442.1]"
iOS 9 returns: "Available windows: [NATIVE_APP, WEBVIEW_44667.5, WEBVIEW_44679.1, WEBVIEW_44675.1, WEBVIEW_44677.1]"

iOS8 log: https://gist.github.com/vicwomg/4ce9faec082404f88768a9c5fd3f1c25
iOS9 log: https://gist.github.com/vicwomg/42dbd8d9d2dfab9bc33063047a3b26f0

**Comment by VasilijSviridov** [comment] 2016-06-20 14:50
@vicwomg Ithink you are right, the same issue here, for iOS9 there is more than 2 webviews, for iOS8 only one.

**Closed** 2017-07-19 17:11 UTC
Labels: Enhancement

**Comment by adamhong** [comment] 2018-03-09 22:03
whats the status of this?

**Comment by chandrajeetvedadri** [comment] 2018-04-26 08:08
Any update on this please?
