### ISSUE TITLE
Cannot verify the signature appium-uiautomator2-server-v4.15.0.apk Original error: Error occurred during initialization of VM

### ISSUE THREAD

**Issue by NightClown** [appium/appium#14984] opened 2020-12-31 03:44 UTC
## The problem

I often run into this when I'm concurrently calling multiple devices to perform tests simultaneously, but the actual Appium service is already running in the background

## Environment

* Appium version (or git revision) that exhibits the issue:1.19.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Centos7.9
* Node.js version (unless using Appium.app|exe):v14.15.1
* Npm or Yarn package manager:6.14.8
* Mobile platform/version under test:android 10
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:appium server

## Details

When I call pytest concurrently to execute the test, multithreading execute

## Link to Appium logs

 [ADB] Checking app cert for /opt/nodejs/node-v14.15.1-linux-x64/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.15.0.apk
[ADB] Using 'apksigner.jar' from '/home/autotest/Android/Sdk/build-tools/30.0.3/lib/apksigner.jar'
[debug] [ADB] Starting apksigner: /usr/local/java/jdk1.8.0_271/bin/java -Xmx1024M -Xss1m -jar /home/autotest/Android/Sdk/build-tools/30.0.3/lib/apksigner.jar verify --print-certs /opt/nodejs/node-v14.15.1-linux-x64/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.15.0.apk
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [ADB] Running '/home/autotest/Android/Sdk/platform-tools/adb -P 5037 -s THFNW19B01001485 shell am force-stop tv.danmaku.bili'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 6149
[debug] [ADB] Running '/home/autotest/Android/Sdk/platform-tools/adb -P 5037 -s THFNW19B01001485 forward --remove tcp:6149'
[UiAutomator2] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/home/autotest/Android/Sdk/platform-tools/adb -P 5037 -s THFNW19B01001485 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1609328590182 (19:43:10 GMT+0800 (中国标准时间))
[debug] [W3C] Encountered internal error running command: Error: Cannot verify the signature of '/opt/nodejs/node-v14.15.1-linux-x64/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.15.0.apk'. Original error: Error occurred during initialization of VM
[debug] [W3C] java.lang.Error: Properties init: Could not determine current working directory.
[debug] [W3C] 	at java.lang.System.initProperties(Native Method)
[debug] [W3C] 	at java.lang.System.initializeSystemClass(System.java:1166)
[debug] [W3C]
[debug] [W3C]
[debug] [W3C]     at ADB.checkApkCert (/opt/nodejs/node-v14.15.1-linux-x64/lib/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:267:11)
[debug] [W3C]     at UiAutomator2Server.installServerApk (/opt/nodejs/node-v14.15.1-linux-x64/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/uiautomator2.js:94:13)
[debug] [W3C]     at AndroidUiautomator2Driver.initUiAutomator2Server (/opt/nodejs/node-v14.15.1-linux-x64/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:484:7)
[debug] [W3C]     at AndroidUiautomator2Driver.startUiAutomator2Session (/opt/nodejs/node-v14.15.1-linux-x64/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:379:5)
[debug] [W3C]     at AndroidUiautomator2Driver.createSession (/opt/nodejs/node-v14.15.1-linux-x64/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:224:7)
[debug] [W3C]     at AppiumDriver.createSession (/opt/nodejs/node-v14.15.1-linux-x64/lib/node_modules/appium/lib/appium.js:366:35)
[debug] [W3C] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 2007 ms - 1423

**Comment by mykola-mokhnach** [comment] 2020-12-31 08:18
Duplicate of https://github.com/appium/appium/issues/14724

Please report the issue to Google. We don't know any workarounds for the original apksigner issue

**Closed by mykola-mokhnach** 2020-12-31 08:18 UTC

**Comment by mykola-mokhnach** [comment] 2020-12-31 08:25
>  /usr/local/java/jdk1.8.0_271/bin/java

Also Jaba 8 won't work with Android SDK 30+. You need Java9 or a newer version
