### ISSUE TITLE
Click() works on Android emulator but not iOS

### ISSUE THREAD

**Issue by ghost** [appium/appium#10244] opened 2018-02-22 16:46 UTC
## The problem

I have a test on an ionic hybrid application selecting an element by class name, and then performing a click. This works on Android but not iOS. The alert modal does not close with the click on iOS, and it times out after 60 sec. 
```javascript
let alrt = await driver.waitForElementByClassName('popup-buttons',10000).then(async function(alrt){
            alrt.click()
        })

//This code returns true for iOS and Android
        let alrt = await driver.waitForElementByClassName('popup-buttons',10000)
        let alert = await alrt.isEnabled(); 
        return alert; //true
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.72
* Desktop OS/version used to run Appium: Mac High Sierra 10.13.3
* Node.js version (unless using Appium.app|exe): 6.10.3
* Mobile platform/version under test: Android 7.1, iOS 10.3
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

### HTML
  ```<div class="popup-buttons" ng-show="buttons.length"><!-- ngRepeat: button in buttons --><button ng-repeat="button in buttons" ng-click="$buttonTapped(button, $event)" class="button ng-binding brand-button--primary" ng-class="button.type || 'button-default'" ng-bind-html="button.text" style="">Okay</button><!-- end ngRepeat: button in buttons --></div>```
If necessary, describe the problem you have been experiencing in more detail.

## Appium logs
```bash
[HTTP] --> POST /wd/hub/session/4191fa4f-0a35-4f68-9c1c-6f6e927dec22/elements {"using":"class name","value":"popup-buttons"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/4191fa4f-0a35-4f68-9c1c-6f6e927dec22/elements] to [POST http://127.0.0.1:8000/wd/hub/session/f153d7c70b354723d02c81d9006756e8/elements] with body: {"using":"class name","value":"popup-buttons"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"f153d7c70b354723d02c81d9006756e8","status":0,"value":[]}
[JSONWP Proxy] Replacing sessionId f153d7c70b354723d02c81d9006756e8 with 4191fa4f-0a35-4f68-9c1c-6f6e927dec22
[HTTP] <-- POST /wd/hub/session/4191fa4f-0a35-4f68-9c1c-6f6e927dec22/elements 200 13 ms - 74
[BaseDriver] Shutting down because we waited 60 seconds for a command
```

**Comment by mykola-mokhnach** [comment] 2018-02-22 16:54
Possible duplicate of https://github.com/appium/appium/issues/6702

**Comment by mykola-mokhnach** [comment] 2018-08-02 11:26
Closed as third party issue

**Closed by mykola-mokhnach** 2018-08-02 11:26 UTC
Labels: Mobile Safari, ThirdParty
