### ISSUE TITLE
Android Find Element Problem on Appium master HEAD

### ISSUE THREAD

**Issue by umutuzgur** [appium/appium#12734] opened 2019-06-07 09:25 UTC
## The problem

At Saucelabs, we now do a Release Validation on the master of Appium and we detected an anomaly with the latest master on Android. A simple Appium test started to fail on the Appium master where as it is working all good on 1.13.0

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.14.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable): 1.13.0
* Desktop OS/version used to run Appium: Linux
* Node.js version (unless using Appium.app|exe): node 8
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 7 and should be more 
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Link to Appium logs

Failed test artifacts on Appium v1.14.0-beta.1 (appium and logcat logs)
https://gist.github.com/umutuzgur/d69aded9cdb6d0083cd6453292003d53

Passed test artifacts on Appium 1.13.0 (appium and logcat logs)
https://gist.github.com/umutuzgur/9d122796ebec4b53d95c31b746fc352e

**Comment by imurchie** [comment] 2019-06-07 12:28
So the error is in getting the `com.testobject.httprequest:id/response_status` element?

Working: https://gist.github.com/umutuzgur/9d122796ebec4b53d95c31b746fc352e#file-appium-passed-log-L336-L345
Failing starting with: https://gist.github.com/umutuzgur/d69aded9cdb6d0083cd6453292003d53#file-appium-failed-log-L346-L355

**Comment by mykola-mokhnach** [comment] 2019-06-07 12:37
I think the problem is that getText returns an empty string after the element was found. This might be a race condition on the client side though. @umutuzgur Can you try top add a timer there to verify the text is not empty instead of a single getText call?

**Comment by umutuzgur** [comment] 2019-06-07 13:00
@imurchie I looked at it with @mykola-mokhnach and we think that the test is failing due to Appium Settings app crashing and the orientation of the phone gets weird

**Comment by imurchie** [comment] 2019-06-07 13:02
Interesting!

**Comment by mykola-mokhnach** [comment] 2019-06-07 13:43
```
MAMInfo : MAMInfo initialized. Debug=false, UseTestAgent=false, ManagedDialogDisabled=false, DeprecationDialogDisabled=false, PolicyRequired=false, MultiIdentityEnabled=true, FullBackupContent=true, UseDefaultEnrollment=false, ExceptionOnInit=false, Debuggable=false
10:29:36    DEBUG:    mali_winsys : EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [2560x1440]-format:1
10:29:36    ERROR:    ViewRootImpl : sendUserActionEvent() mView == null
10:29:36    DEBUG:    AndroidRuntime : Shutting down VM
10:29:36    DEBUG:    AndroidRuntime : --------- beginning of crash
10:29:36    ERROR:    AndroidRuntime : FATAL EXCEPTION: main
10:29:36    ERROR:    AndroidRuntime : Process: io.appium.settings, PID: 22283
10:29:36    ERROR:    AndroidRuntime : java.lang.IllegalStateException: GoogleApiClient is not connected yet.
10:29:36    ERROR:    AndroidRuntime : at com.google.android.gms.common.api.internal.zaak.execute(Unknown Source)
10:29:36    ERROR:    AndroidRuntime : at com.google.android.gms.common.api.internal.zabe.execute(Unknown Source)
10:29:36    ERROR:    AndroidRuntime : at com.google.android.gms.common.api.internal.zaaw.execute(Unknown Source)
10:29:36    ERROR:    AndroidRuntime : at com.google.android.gms.internal.location.zzq.requestLocationUpdates(Unknown Source)
10:29:36    ERROR:    AndroidRuntime : at io.appium.settings.LocationTracker.onConnected(LocationTracker.java:103)
10:29:36    ERROR:    AndroidRuntime : at com.google.android.gms.common.internal.GmsClientEventManager.onConnectionSuccess(Unknown Source)
10:29:36    ERROR:    AndroidRuntime : at com.google.android.gms.common.api.internal.zaaw.zab(Unknown Source)
10:29:36    ERROR:    AndroidRuntime : at com.google.android.gms.common.api.internal.zaak.zaaq(Unknown Source)
10:29:36    ERROR:    AndroidRuntime : at com.google.android.gms.common.api.internal.zaak.onConnected(Unknown Source)
10:29:36    ERROR:    AndroidRuntime : at com.google.android.gms.common.api.internal.zabe.onConnected(Unknown Source)
10:29:36    ERROR:    AndroidRuntime : at com.google.android.gms.common.api.internal.zaq.onConnected(Unknown Source)
10:29:36    ERROR:    AndroidRuntime : at com.google.android.gms.common.internal.zaf.onConnected(Unknown Source)
10:29:36    ERROR:    AndroidRuntime : at com.google.android.gms.common.internal.BaseGmsClient$zzf.zzm(Unknown Source)
10:29:36    ERROR:    AndroidRuntime : at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(Unknown Source)
10:29:36    ERROR:    AndroidRuntime : at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(Unknown Source)
10:29:36    ERROR:    AndroidRuntime : at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source)
10:29:36    ERROR:    AndroidRuntime : at android.os.Handler.dispatchMessage(Handler.java:102)
10:29:36    ERROR:    AndroidRuntime : at android.os.Looper.loop(Looper.java:154)
10:29:36    ERROR:    AndroidRuntime : at android.app.ActivityThread.main(ActivityThread.java:6682)
10:29:36    ERROR:    AndroidRuntime : at java.lang.reflect.Method.invoke(Native Method)
10:29:36    ERROR:    AndroidRuntime : at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
10:29:36    ERROR:    AndroidRuntime : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
10:29:36    DEBUG:    Debug : !@DumpState : SHIP
10:29:36    DEBUG:    Debug : !@DumpState : debug level:0x4f4c
10:29:36    DEBUG:    Debug : !@Dumpstate : Finally, system will skip dumpstate
10:29:36    DEBUG:    FirebaseApp : com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
10:29:36    DEBUG:    FirebaseApp : com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
```

**Comment by mykola-mokhnach** [comment] 2019-06-07 13:44
It scares me a bit that the stuff fails because it is not connected in onConnect handles, but I'll try to optimise this code.

**Comment by mykola-mokhnach** [comment] 2019-06-12 20:11
Closed as fixed. Also the android driver where monkey is not used for settings startup has been published to beta

**Closed by mykola-mokhnach** 2019-06-12 20:11 UTC
Labels: Bug, UIAutomator2
