### ISSUE TITLE
safariAllowPopups capability is not honored

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7433] opened 2016-12-06 15:43 UTC
@midopa commented on [Thu Oct 20 2016](https://github.com/appium/appium-xcuitest-driver/issues/254)

I'm seeing the same problem for popups in Safari. It seems related. If not, let me know and I can open another issue.
- OSX El Capitan
- Node 6.7.0
- Appium @ v1.6.0 tag with modified package.json to point to 2.0.29 XCUITest driver
- XCode 8
- iOS 10, iPad Air simulator

Capabilities:

```
[Appium] Capabilities:
[Appium]   deviceName: 'iPad Air'
[Appium]   browserName: 'Safari'
[Appium]   platformVersion: '10.0'
[Appium]   safariAllowPopups: true
[Appium]   platformName: 'iOS'
[Appium]   port: 12344
```

My test code:

```
driver.get('http://localhost:8000')
driver.find_element_by_id('asd').click()
```

My test website:

```
<a id="asd" href="https://www.google.com" target="_blank">asdasd</a>
```

Log: https://gist.github.com/midopa/8318247111f524d6c42504a909e71445

**Comment by dpgraham** [comment] 2017-07-19 18:03
Closing as duplicate of https://github.com/appium/appium/issues/8280

**Closed by dpgraham** 2017-07-19 18:03 UTC
Labels: NeedsTriage
