### ISSUE TITLE
[Appium][XCUITest] Can't get value of elemnt "XCUIElementTypeSecureTextField"

### ISSUE THREAD

**Issue by markhuangext359** [appium/appium#13790] opened 2020-01-03 10:11 UTC
## The problem

The value of XCUIElementTypeSecureTextField can get form source 

 GET /wd/hub/session/8849b391-3b53-4cd2-a7c7-d589020749a8/source
```<XCUIElementTypeSecureTextField type="XCUIElementTypeSecureTextField" enabled="true" visible="true" x="15" y="239" width="293" height="26" value="••••••••">```

But ```element/[element_id]/text``` or ```element/[element_id]/attribute/value``` , output is wrong

GET /wd/hub/session/8849b391-3b53-4cd2-a7c7-d589020749a8/element/38000000-0000-0000-8E4B-000000000000/text
```
2020-01-03 09:45:25:961 [WD Proxy] Got response with status 200: {
2020-01-03 09:45:25:961 [WD Proxy]   "value" : "",
2020-01-03 09:45:25:961 [WD Proxy]   "sessionId" : "0E9313D1-785E-42F8-B3E5-09F4EC6845C6"
2020-01-03 09:45:25:961 [WD Proxy] }
```

GET /wd/hub/session/8849b391-3b53-4cd2-a7c7-d589020749a8/element/38000000-0000-0000-8E4B-000000000000/attribute/value
```
2020-01-03 09:46:33:830 [WD Proxy] Got response with status 200: {
2020-01-03 09:46:33:830 [WD Proxy]   "value" : null,
2020-01-03 09:46:33:830 [WD Proxy]   "sessionId" : "0E9313D1-785E-42F8-B3E5-09F4EC6845C6"
2020-01-03 09:46:33:830 [WD Proxy] }
```
## Environment

* Appium version: 1.15.1
* Desktop OS/version used to run Appium: MacOS 10.14.1
* Node.js version (unless using Appium.app|exe):  v12.12.0
* Npm or Yarn package manager: npm 6.11.3
* Mobile platform/version under test: iOS 11.4,
* Real device or emulator/simulator: real device iPhone6

## Link to Appium logs

https://gist.github.com/markhuangext359/03cd92fbb8dd022f3d6f2cf596c28e7c

**Comment by mykola-mokhnach** [comment] 2020-01-03 11:00
Duplicate of https://github.com/appium/appium/issues/13691

A Possible workaround would be to test older iOS version with older Xcode SDKs.

**Closed by mykola-mokhnach** 2020-01-03 11:00 UTC

**Comment by imurchie** [comment] 2020-01-03 15:15
Apple will _not_ return a value for secure text fields, for security reasons I imagine. Nothing can be done about it.
