### ISSUE TITLE
tap on elements does work properly on iPad 10.0+ in landscape mode for Appium 1.6.0

### ISSUE THREAD

**Issue by mmuntakim15** [appium/appium#7060] opened 2016-10-19 23:17 UTC
## The problem

tap() action does not work on iPad 10.0+ in landscape mode for Appium 1.6.0

## Environment

Appium version (or git revision) that exhibits the issue: 1.6.0 @ XCUITest
Last Appium version that did not exhibit the issue (if applicable): 1.5.3
Desktop OS/version used to run Appium: 10.11
Node.js version (unless using Appium.app|exe): 5.4.1
Mobile platform/version under test: iOS 10.0
Real device or emulator/simulator: iPad Air Simulator Landscape
Appium CLI or Appium.app|exe: CLI

## Code To Reproduce Issue [ Good To Have ]

MobileElement element = driver.findElement(byElement)
element.tap(1,1)

**Comment by mykola-mokhnach** [comment] 2016-10-20 06:45
Duplicate of https://github.com/appium/appium/issues/6994

**Closed** 2016-10-20 21:31 UTC
Labels: NeedsTriage
