### ISSUE TITLE
Not used changed appium-scodebuild-driver xcodebuild.js file

### ISSUE THREAD

**Issue by ddubtsov35** [appium/appium#12489] opened 2019-04-12 10:19 UTC
Hey guys! I have capability showXcodeLog = false, but after some error 
"Error Domain=com.apple.dt.xctest.automation-support.error Code=8 "Error getting main window"",  
xcode log is showing.

It's feature appium-xcuitest-driver (https://github.com/appium/appium/issues/11347), 
but I change xcodebuild.js and string:
logXcodeOutput = true; to logXcodeOutput = false;

After save file and rerun tests nothing not change(
How apply my changes?

**Comment by mykola-mokhnach** [comment] 2019-04-12 10:58
Duplicate of https://github.com/appium/appium/issues/12466

**Closed by mykola-mokhnach** 2019-04-12 10:58 UTC

**Comment by ddubtsov35** [comment] 2019-04-12 11:21
@mykola-mokhnach  ok, I see your yesterday commit in appium-xcuitest-driver repository with fix this problem, but i have one common question:
when this commit enter in new appium-xcuitest-driver release, how I can add release in my appium?
Do i should download release and add his in appium directory or waiting appium release with new  appium-xcuitest-driver release?

**Comment by mykola-mokhnach** [comment] 2019-04-12 11:27
https://appiumpro.com/editions/47

**Comment by imurchie** [comment] 2019-04-12 11:29
Or our documentation, of which the above is just a rehash: http://appium.io/docs/en/contributing-to-appium/appium-from-source/

**Comment by ddubtsov35** [comment] 2019-04-12 11:33
Thank you!

**Comment by ddubtsov35** [comment] 2019-04-12 19:13
@mykola-mokhnach @mykola-mokhnach  sorry, guys, but i have problem) 
I did all actions from https://appiumpro.com/editions/47, and appium-xcuitest-driver/WebDriverAgent folder was empty and after run test i has error: 
"Trying to use WebDriverAgent project at '/WORK/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj' but the file does not exist"

Next I try  git clone appium/WebDriverAgent and copy this folder to appium-xcuitest-driver/WebDriverAgent. In this attempt i has error:
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

How i can use  appium-xcuitest-driver?

**Comment by imurchie** [comment] 2019-04-12 20:38
In you installation of `appium-xcuitest-driver` you need to run the command `git submodule update --init`.
