### ISSUE TITLE
add capability for waiting for idle animations to new uiautomator2 driver

### ISSUE THREAD

**Issue by RetAdmFloyd** [appium/appium#4488] opened 2015-02-04 15:11 UTC
For example, my test clicks on a button, and this button appears on the screen with slow animation. Sometimes test fails with InvocationTargetException because the button is not reached to its place (still beyond the screen, I guess).

How can I wait until animation is finished?

Calabash has http://calabashapi.xamarin.com/ios/Calabash/Cucumber/WaitHelpers.html#wait_for_none_animating-instance_method for this purpose.

**Comment by sebv** [comment] 2015-02-16 13:03
I don't think we have this kind of methods, you'll need to write your own, moving to 1.5 for investigation.

**Comment by jlipps** [comment] 2016-02-11 22:59
@bootstraponline are you aware of any hooks in the android libraries that allow us to detect whether an element is animating?

**Comment by bootstraponline** [comment] 2016-02-11 23:31
@jlipps 
We can wait for some kinds of animations to finish by using `InstrumentationRegistry.getInstrumentation().waitForIdleSync();`

This doesn't work for system animations or app specific animations. This will require the new driver since uiautomator v1 doesn't have access to instrumentation.

**Comment by jlipps** [comment] 2016-02-12 00:08
Can the user introspect animation state on an element instead? Then we wouldn't have to build new endpoints for this.

**Comment by bootstraponline** [comment] 2016-02-12 00:12
> Can the user introspect animation state on an element instead?

No. I don't know of any such API. The best that we can do is attempt to detect if the app is busy (which may or may not be due to an animation).

> all view operations with the UI thread as well as AsyncTasks
>
> https://developer.android.com/reference/android/support/test/espresso/IdlingResource.html

**Comment by bootstraponline** [comment] 2016-02-12 00:15
> Then we wouldn't have to build new endpoints for this.

Typically waitForIdleSync is automatically run by the framework, it's not something a user invokes. This is how protractor and Apple's XCUITest work (`Wait for app to idle`).

**Comment by jlipps** [comment] 2016-02-12 17:08
I see. still strikes me as something that might backfire for a lot of cases. I'm on the fence as to whether it should be a feature. I guess it could be an optional thing turned on by a capability.

**Comment by mykola-mokhnach** [comment] 2017-09-04 13:44
@jlipps is it a duplicate of https://github.com/appium/appium/issues/5400 ?

**Comment by jlipps** [comment] 2017-09-07 16:47
@mykola-mokhnach looks like it might be. is waiting for window animations to complete the same thing as waiting for the app to idle? If so I think we can close this.

**Comment by mykola-mokhnach** [comment] 2018-06-04 09:27
Closed as duplicate. UIA2 contains `disableWindowAnimation` argument as well

**Closed by mykola-mokhnach** 2018-06-04 09:27 UTC
Labels: Android, Enhancement, P2, UIAutomator2
