### ISSUE TITLE
Execution not moving forward on Pixel devices using Espresso after the app is launched

### ISSUE THREAD

**Issue by sonugupta029** [appium/appium#16512] opened 2022-03-01 06:11 UTC
## The problem

Execution not moving forward on Pixel devices using Espresso after the app is launched

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2, 1.21.0, 1.22.0
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Catalina, 10.15.7
* Node.js version (unless using Appium.app|exe): 17.4.0
* Npm or Yarn package manager: 8.3.1
* Mobile platform/version under test: Pixel 5 OS 11 and Pixel 4XL OS 12
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI 

## Details

Trying to run automation on Pixel devices. The same set up works fine for Samsung devices. Appium is able to launch the app using espresso but the next commands are not running and execution does not move forward.

## Link to Appium logs
https://gist.github.com/sonugupta029/fb952aa6c4cdcfd46f0eb4aedd93b993

Adb Logcat logs:
https://gist.github.com/sonugupta029/8b6016bd70b765e1cbcf370c62fbdb60

## Code To Reproduce Issue [ Good To Have ]

Launching app using desired capabilities for espresso

**Comment by mykola-mokhnach** [comment] 2022-03-01 06:25
https://gist.github.com/sonugupta029/8b6016bd70b765e1cbcf370c62fbdb60#file-pixeladblogs-log-L2791

This seems like some internal Espresso error. I was not able to find much info about it though.

**Comment by mykola-mokhnach** [comment] 2022-03-01 06:27
In the Espresso core the same error is thrown inside of https://androidx.tech/artifacts/test.espresso/espresso-core/3.1.0-alpha2-source/androidx/test/espresso/base/UiControllerImpl.java.html, which makes me think there is some issue with application idling (e.g. it is not in idle mode for too long, so all Espresso commands time out).

**Comment by sonugupta029** [comment] 2022-03-01 22:27
Thanks @mykola-mokhnach for prompt response. So what do you think is the issue with espresso or the app under test? Should I try adding some dependency to espressoBuildConfig which can help me resolve this issue. These are dependencies which are already part of espressoBuildConfig capability currently
espressoBuildConfig={ "additionalAppDependencies": [ "com.google.android.material:material:1.5.0-alpha02", "androidx.lifecycle:lifecycle-extensions:2.1.0", "org.reduxkotlin:redux-kotlin-jvm:0.5.5", "org.reduxkotlin:redux-kotlin-threadsafe-jvm:0.5.5", "org.reduxkotlin:redux-kotlin-thunk:0.5.5" ] }

**Comment by mykola-mokhnach** [comment] 2022-03-02 04:42
I don't know for sure what the issue is. Like I said I **assume** it could be related to the fact that the application under test is not idling long enough.

**Comment by mykola-mokhnach** [comment] 2022-03-08 16:00
Closed as third party issue

**Closed by mykola-mokhnach** 2022-03-08 16:00 UTC
Labels: ThirdParty, Espresso
