### ISSUE TITLE
fail to record screen for iOS

### ISSUE THREAD

**Issue by earlif** [appium/appium#16372] opened 2022-01-26 05:54 UTC
## The problem

When try to record screen on iOS, encounter this exception: An unknown server-side error occurred while processing the command. Original error: The screen recorder utility has failed to store the actual screen recording at '/var/folders/1f/3xzbmsz91vnfk0cz1zzp389h0000gn/T/2022026-17083-hg9lo3.a5ked/appium_bfcfba.mp4'

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC 12.0.1
* Node.js version (unless using Appium.app|exe):17.4.0
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 14.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

<script src="https://gist.github.com/earlif/a3781a0576d004eb14c8e21b1d2f96bd.js"></script>

## Code To Reproduce Issue [ Good To Have ]

   public void startRecording() {
        System.out.println("start recording");
        ((CanRecordScreen) driver)
                .startRecordingScreen(new IOSStartScreenRecordingOptions().withVideoScale("1080x1920"));
    }
    
    public void stopRecording() {
        System.out.println("* End recording video...");
        String base64Video = ((CanRecordScreen) driver).stopRecordingScreen(); //exception on this line
        createDirectory("target/recordings/");
        String videoPath = "target/recordings/" + "videoName.mov";
        try {
            Files.write(Paths.get(videoPath), Base64.getDecoder().decode(base64Video));
            System.out.println("Video is saved successfully: " + videoPath);
        } catch (IOException e) {
            System.out.println("Failed to save video: " + e.getLocalizedMessage());
        }
    }

**Comment by KazuCocoa** [comment] 2022-01-26 08:04
What about giving the scale as `1080:1920` instead of `x`.
https://appium.io/docs/en/commands/device/recording-screen/start-recording-screen/
Perhaps it needs to adjust ffmpeg parameters.

**Comment by earlif** [comment] 2022-01-26 08:29
tried
((CanRecordScreen) driver).startRecordingScreen(new IOSStartScreenRecordingOptions().withVideoScale("1080:1920"));
and 
((CanRecordScreen) driver).startRecordingScreen(new IOSStartScreenRecordingOptions());

No luck. They give the same exception.

**Comment by earlif** [comment] 2022-01-26 09:16
It works with Appium desktop 1.21.0 and ((CanRecordScreen) driver).startRecordingScreen(new IOSStartScreenRecordingOptions().withVideoScale("1080:1920"));

**Comment by earlif** [comment] 2022-01-26 09:41
> It works with Appium desktop 1.21.0 and ((CanRecordScreen) driver).startRecordingScreen(new IOSStartScreenRecordingOptions().withVideoScale("1080:1920"));

Can generate video file, but cannot play.

**Comment by KazuCocoa** [comment] 2022-01-26 10:14
> Can generate video file, but cannot play.

What video player did you use?
QickTime in macOS cannot play well in some mp4 encoded video even the video is not broken (It seems QuickTime did not handle metadata correctly in some cases). VLC is more reliable to play video.


Btw, can you see mjpeg streaming when you open http://127.0.0.1:9100/ via browser during the appium session?

It generally depends on taking screenshot API to get images. Appium 1.22 updated the taking screenshot API to a new one for iOS 15. If the mjpeg stream has an issue (e.g. very slow, cannot see images etc), the API could have an issue in some simulators. Then, probably only Apple can fix it. Appium should stay current API to support iOS 15 and newer one.

It is appreciated to check if the same issue occurs in iOS 15 as well.

**Comment by mykola-mokhnach** [comment] 2022-01-26 13:32
You could try to debug the source stream same way as described in https://github.com/appium/appium/issues/16294
Basically, there might be nothing to consume for ffmpeg if no screenshots could be taken from the device or if there are issues with their transport.

**Comment by mykola-mokhnach** [comment] 2022-01-26 13:35
I assume the reason is the same as in https://github.com/appium/appium/issues/16373#issuecomment-1022202487

XCTest is unable to take any screenshot, so ffmpeg does not get supplied with the necessary data. I don't think we could do anything about it.

**Comment by earlif** [comment] 2022-01-27 06:53
> 

VLC can play the video. Tested on iOS 15.2, no this issue.

**Comment by earlif** [comment] 2022-01-27 06:54
> > Can generate video file, but cannot play.
> 
> What video player did you use? QickTime in macOS cannot play well in some mp4 encoded video even the video is not broken (It seems QuickTime did not handle metadata correctly in some cases). VLC is more reliable to play video.
> 
> Btw, can you see mjpeg streaming when you open http://127.0.0.1:9100/ via browser during the appium session?
> 
> It generally depends on taking screenshot API to get images. Appium 1.22 updated the taking screenshot API to a new one for iOS 15. If the mjpeg stream has an issue (e.g. very slow, cannot see images etc), the API could have an issue in some simulators. Then, probably only Apple can fix it. Appium should stay current API to support iOS 15 and newer one.
> 
> It is appreciated to check if the same issue occurs in iOS 15 as well.

VLC can play the video. Tested on iOS 15.2, no this issue.

**Comment by mlynch** [comment] 2022-01-27 23:11
I am seeing the same issue on Appium 1.22.0 and an iOS 15.2 simulator. All I see in my logs is 

```
http://localhost:4723/session/354db803-194f-4c44-8014-83bbfbde647a/appium/stop_recording_screen
The screen recorder utility has failed to store the actual screen recording at '/var/folders/86/yc6qnb5n1n577f1_pcs929lc0000gn/T/2022027-11409-1o913mx.ozih/appium_984c42.mp4'
```

I am using WebdriverIO and calling it before and after each test, like this:

```
  browser.startRecordingScreen({
      videoType: 'mpeg4'
    }));
```

```
  browser.saveRecordingScreen('./video.mp4')
```

I am not seeing ffmpeg anywhere in my logs, so it's unclear where this issue is coming from.

**Comment by KazuCocoa** [comment] 2022-01-27 23:56
@earlif
Thanks. Appium/WDA use the new screenshot api with selector. So, it seems like the new screenshot API by Apple has an issue for iOS 14.3 simulators. Our logic uses the new screenshot API if available with selector. https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBScreenshot.m#L36-L43

@mlynch What about appium server log? The log is probably client side log.

**Comment by mlynch** [comment] 2022-01-28 18:27
@KazuCocoa here are the appium server logs: https://gist.github.com/mlynch/39357fe485251e048310f9bd1e45f3dc. I notice no errors from ffmpeg except it receives signal 15 (`SIGTERM`) so I'm guessing it was terminated before it could finish and appium isn't waiting for it to finish? The more I look at this the more I think the issue is that `deleteSession` is being sent too soon by my client (webdriverio), causing the ffmpeg process to be terminated before it can finish, and this isn't an appium issue. Curious if you see anything suspect in there though.

**Comment by KazuCocoa** [comment] 2022-01-29 10:23
it seems like around https://gist.github.com/mlynch/39357fe485251e048310f9bd1e45f3dc#file-wdio-appium-log-L3631-L3648 got async requests. The last one was a delete request, so it started cleaning the session up at the request.
Probably each request waits with `await`, at least they work without interrupting running commands.

**Comment by mykola-mokhnach** [comment] 2022-01-31 08:47
Closed as not an issue

**Closed by mykola-mokhnach** 2022-01-31 08:47 UTC
Labels: ThirdParty, NotABug, NeedsInfo
