### ISSUE TITLE
APKs in /data/app cause INSTALL_FAILED_INSUFFICIENT_STORAGE

### ISSUE THREAD

**Issue by hwulfmeyer** [appium/appium#14446] opened 2020-06-12 13:14 UTC
This is related to: https://github.com/appium/appium/issues/13970

I believe there needs to be another folder/file that needs to be deleted.
See https://stackoverflow.com/questions/4709137/solution-to-install-failed-insufficient-storage-error-on-android

This is the only thing that helped me with my issue.
Everytime I quit the driver I am deleting all APKs of my package in /data/app/

```
List<String> args = Arrays.asList(
		"-rf",
		" /data/app/[package_name]-*"
);
Map<String, Object> cmd = ImmutableMap.of(
		"command", "rm",
		"args", args
);
this.executeScript("mobile: shell", cmd);
```

**Comment by mykola-mokhnach** [comment] 2020-06-12 13:15
You could try to create a patch yourself: https://github.com/appium/appium-adb/blob/e560fd9cda8fd9e58a6fbc6c7e9e884d55a5ea69/lib/tools/apk-utils.js#L585

**Comment by Jiurong-Yang** [comment] 2020-06-16 00:18
@wulfihm Would this solution only work with simulator and rooted devices? For our devices this folder "/data/app" is protected (not even read permission). For Android OS 7,8,9 and 10

**Comment by wulfihm** [comment] 2020-06-17 18:57
@Jiurong-Yang  Seems like it would only work on rooted devices and the emulator. If you have this issue, did you try set `remoteAppsCache=0`?

**Comment by Jiurong-Yang** [comment] 2020-08-18 19:59
It seems like i found a solution to this problem. All you need to do is periodically reboot the android device (we run real devices). I'm assuming that the Android OS have some files that builds up over that that i doesn't or couldn't clean up while running and requires a reboot for those files to be cleaned up. I'm still unaware what are these files exactly since I don't have a rooted devices so I cannot fully explore the FS. 

Maybe this should be something that is documented? Although I'm not sure where this would belong to in the documentation

**Comment by mykola-mokhnach** [comment] 2020-10-15 11:25
It looks like this behaviour is caused by a system bug in Android. We've investigated and reported it. Let see if there is any feedback from devs

**Comment by mykola-mokhnach** [comment] 2020-10-24 17:19
https://issuetracker.google.com/issues/170867658

**Comment by mykola-mokhnach** [comment] 2020-10-27 19:11
Android developers mentioned this is the expected system behaviour. A workaround would be to restart all device services by running `adb stop`/`adb start` commands. Closing this as there is nothing more we could do in Appium.

**Closed by mykola-mokhnach** 2020-10-27 19:11 UTC
Labels: Android, Enhancement, ThirdParty
