### ISSUE TITLE
inal error:  exited with code 255

### ISSUE THREAD

**Issue by luobs** [appium/appium#7542] opened 2016-12-15 02:07 UTC
## The problem

When I installed the appium 1.6.3, run is always at fault:

`inal error: Unable to start WebDriverAgent: Error: Command 'idevicedate -u a58bdd10033efffd5261d606ec221744c973b6d9' exited with code 255`

There's nothing wrong with it.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   deviceName: 'iPhone'
[Appium]   unicodeKeyboard: 'True'
[Appium]   udid: 'a58bdd10033efffd5261d606ec221744c973b6d9'
[Appium]   app: '/Users/mac/Library/Developer/Xcode/DerivedData/ECLite-dglkdcoapbwyzxeyygdccvctpxxf/Build/Products/Debug-iphoneos/ECLite.app'
[Appium]   resetKeyboard: 'True'
[Appium]   platformVersion: '10.1.1'
[Appium]   platformName: 'IOS'
[Appium]   AUTOMATION_NAME: 'XCUITest'
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] The following capabilities were provided, but are not recognized by appium: unicodeKeyboard, resetKeyboard, AUTOMATION_NAME.
[BaseDriver] Session created with session id: 62d46196-575f-4ee8-8cca-a226316bda78
[debug] [XCUITest] Xcode version set to '8.2'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [XCUITest] Available devices: a58bdd10033efffd5261d606ec221744c973b6d9
[debug] [XCUITest] Creating iDevice object with udid a58bdd10033efffd5261d606ec221744c973b6d9
[XCUITest] Determining device to run tests on: udid: 'a58bdd10033efffd5261d606ec221744c973b6d9', real device: true
[BaseDriver] Using local app '/Users/mac/Library/Developer/Xcode/DerivedData/ECLite-dglkdcoapbwyzxeyygdccvctpxxf/Build/Products/Debug-iphoneos/ECLite.app'
[debug] [XCUITest] Checking whether app '/Users/mac/Library/Developer/Xcode/DerivedData/ECLite-dglkdcoapbwyzxeyygdccvctpxxf/Build/Products/Debug-iphoneos/ECLite.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/Users/mac/Library/Developer/Xcode/DerivedData/ECLite-dglkdcoapbwyzxeyygdccvctpxxf/Build/Products/Debug-iphoneos/ECLite.app': 'com.ec.ECLite'
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=a58bdd10033efffd5261d606ec221744c973b6d9 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u a58bdd10033efffd5261d606ec221744c973b6d9' exited with code 255
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u a58bdd10033efffd5261d606ec221744c973b6d9' exited with code 255
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: undefined
[HTTP] <-- POST /wd/hub/session 500 1510 ms - 262 
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2016-12-15 07:34
Closed as duplicate of https://github.com/appium/appium/issues/7540

**Closed by mykola-mokhnach** 2016-12-15 07:34 UTC
Labels: NeedsTriage

**Comment by luobs** [comment] 2016-12-15 09:59
Tried to Command `brew upgrade /usr/localCellar/idevicelibrary` and  `sudo chomd 777 /var/db/lockdown`  Still not.

**Comment by dcaric** [comment] 2016-12-16 12:37
I have the same issue. I wrote this https://github.com/appium/appium/issues/7521 and I tested Integration App on simulator. There it works fine but on real dev,.. nothing
