### ISSUE TITLE
Start and close the App after update the Appium v.1.12.1

### ISSUE THREAD

**Issue by mochafizIH** [appium/appium#12543] opened 2019-04-25 04:39 UTC
## The problem

After updating the Appium to v.1.12.1, when I try to launch the inspector, it will open the app then will close again in a few seconds. It's happening for multiple times until error logs are show

## Environment

* Appium version (or git revision) that exhibits the issue: v.1.12.1
* Last Appium version that did not exhibit the issue (if applicable): v.1.7.1
* Desktop OS/version used to run Appium: MacOs Mojave
* Node.js version (unless using Appium.app|exe): v8.15.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iphone6s/ v.12
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/mochafizIH/559bddcd6692b1af2cb33b2d0677a38b

## Code To Reproduce Issue [ Good To Have ]
Desirecapability: {
  "automationName": "XCUITest",
  "deviceName": "iPhone 7",
  "platformName": "iOS",
  "platformVersion": "11.4",
  "bundleId": "xxx",
  "noReset": true,
  "language": "en",
  "showXcodeLog": true,
  "clearSystemFiles": true,
  "launchTimeout": 30000,
  "udid": "xxx",
  "xcodeOrgId": "xxx",
  "xcodeSigningId": "iPhone Developer"
}

**Comment by mykola-mokhnach** [comment] 2019-04-25 05:20
Duplicate of https://github.com/appium/appium/issues/12503

**Closed by mykola-mokhnach** 2019-04-25 05:20 UTC
