### ISSUE TITLE
Not able to access children class elements in React Native application 

### ISSUE THREAD

**Issue by Pratik-27** [appium/appium#15317] opened 2021-05-03 06:39 UTC
So i'm not able to access Text View class for the **App Collector Check** text,  it just stops at View class with text written there. Please refer to the image provided for more details.

![Appium](https://user-images.githubusercontent.com/49270636/116846403-d26b6680-ac05-11eb-9499-110cc9e302d1.png)

**Comment by mykola-mokhnach** [comment] 2021-05-03 06:54
Duplicate of https://github.com/appium/appium/issues/14825

In general, if the element is not accessible then there's nothing we could do from Appium side.

**Closed by mykola-mokhnach** 2021-05-03 06:54 UTC
