### ISSUE TITLE
Unable to build the WebDriverAgent on Xcode 12.3 With Appium 1.19.1

### ISSUE THREAD

**Issue by RonCocoa** [appium/appium#14963] opened 2020-12-21 11:21 UTC
## The problem
Unable to build the WebDriverAgent on Xcode 12.3 with Appium version 1.19.1

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1 with Xcode 12.3
* Last Appium version that did not exhibit the issue (if applicable): 1.18.3 with Xcode 12.1
* Desktop OS/version used to run Appium: 1.19.1
* Node.js version (unless using Appium.app|exe): 12.8.1
* Mobile platform/version under test: iOS 14.2
* Real device or emulator/simulator: Both

## Details

/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj Building for iOS Simulator, but the linked and embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator.

/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj Building for iOS Simulator, but the linked and embedded framework 'YYCache.framework' was built for iOS + iOS Simulator.

**Comment by mykola-mokhnach** [comment] 2020-12-21 12:57
Duplicate of https://github.com/appium/appium/issues/14952

**Closed by mykola-mokhnach** 2020-12-21 12:57 UTC
