### ISSUE TITLE
Appium Inspector throws error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file

### ISSUE THREAD

**Issue by deepaksporty** [appium/appium#8113] opened 2017-03-28 08:06 UTC
I ran my Appium server from terminal. Appium version 1.6.4-beta
and then opened the Appium Desktop 1.5.3 and just clicked on inspector. I got the below error.

Appium logs:
Last login: Tue Mar 28 13:22:18 on ttys002
BLRDTIWA386367:~ dtiwa1$ appium --address 127.0.0.1 --port 4723 --session-override --log-level debug
[Appium] Welcome to Appium v1.6.4-beta
[Appium] Non-default server args:
[Appium]   address: '127.0.0.1'
[Appium]   sessionOverride: true
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session {"capabilities":[{"desiredCapabilities":{"app":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/Tesco_SAYS.ipa","agentPath":"/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj","bootstrapPath":"/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent","platformVersion":"10.2","automationName":"XCUITest","bundleId":"com.tesco.scanasyoushop","xcodeConfigFile":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/XCodeConfig.xcconfig","platformName":"iOS","udid":"d7e9ea82703b2905bf0f5a969d925dc8692ef56c","fullReset":false,"deviceName":"Tesco's iPhone"}},{"requiredCapabilities":{}}],"desiredCapabilities":{"app":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/Tesco_SAYS.ipa","agentPath":"/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj","bootstrapPath":"/usr/local/lib/node_modul
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/Tesco_SAYS.ipa","agentPath":"/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj","bootstrapPath":"/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent","platformVersion":"10.2","automationName":"XCUITest","bundleId":"com.tesco.scanasyoushop","xcodeConfigFile":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/XCodeConfig.xcconfig","platformName":"iOS","udid":"d7e9ea82703b2905bf0f5a969d925dc8692ef56c","fullReset":false,"deviceName":"Tesco's iPhone"},{},[{"desiredCapabilities":{"app":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/Tesco_SAYS.ipa","agentPath":"/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj","bootstrapPath":"/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent","platformVersion":"10.2","automationName":"...
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1490687935014 (13:28:55 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.23.1) session
[Appium] Capabilities:
[Appium]   app: '/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/Tesco_SAYS.ipa'
[Appium]   agentPath: '/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[Appium]   bootstrapPath: '/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent'
[Appium]   platformVersion: '10.2'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'com.tesco.scanasyoushop'
[Appium]   xcodeConfigFile: '/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/XCodeConfig.xcconfig'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'd7e9ea82703b2905bf0f5a969d925dc8692ef56c'
[Appium]   fullReset: false
[Appium]   deviceName: 'Tesco\'s iPhone'
[debug] [XCUITest] XCUITestDriver version: 2.23.1
[BaseDriver] Session created with session id: 00e74029-5d18-4957-a4c0-06dd1d80ea1c
[debug] [XCUITest] Xcode version set to '8.2.1' (tools v8.2.0.0.1.1480973914)
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1490687935122 (13:28:55 GMT+0530 (IST))
[debug] [XCUITest] Available devices: d7e9ea82703b2905bf0f5a969d925dc8692ef56c
[debug] [XCUITest] Creating iDevice object with udid 'd7e9ea82703b2905bf0f5a969d925dc8692ef56c'
[XCUITest] Determining device to run tests on: udid: 'd7e9ea82703b2905bf0f5a969d925dc8692ef56c', real device: true
[BaseDriver] Using local app '/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/Tesco_SAYS.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/8w/66v1v211569blvqh41krj1vj3hrvc7/T/2017228-59375-71bqc5.nrmypkfbt9/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/8w/66v1v211569blvqh41krj1vj3hrvc7/T/2017228-59375-71bqc5.nrmypkfbt9/appium-app.zip
[debug] [BaseDriver] Got a relaxed match for app in zip, be careful for app match errors
[BaseDriver] Unzipped local app to '/var/folders/8w/66v1v211569blvqh41krj1vj3hrvc7/T/2017228-59375-71bqc5.nrmypkfbt9/Payload/Tesco SAYS.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1490687935753 (13:28:55 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/var/folders/8w/66v1v211569blvqh41krj1vj3hrvc7/T/2017228-59375-71bqc5.nrmypkfbt9/Payload/Tesco SAYS.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [BaseDriver] Event 'resetStarted' logged at 1490687935754 (13:28:55 GMT+0530 (IST))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1490687935755 (13:28:55 GMT+0530 (IST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1490687935872 (13:28:55 GMT+0530 (IST))
[XCUITest] Setting up real device
[debug] [XCUITest] Reset requested. Removing app with id 'com.tesco.scanasyoushop' from the device
[debug] [XCUITest] Installing '/var/folders/8w/66v1v211569blvqh41krj1vj3hrvc7/T/2017228-59375-71bqc5.nrmypkfbt9/Payload/Tesco SAYS.app' on device with UUID 'd7e9ea82703b2905bf0f5a969d925dc8692ef56c'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1490687938578 (13:28:58 GMT+0530 (IST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1490687938580 (13:28:58 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using Xcode configuration file: '/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/XCodeConfig.xcconfig'
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=d7e9ea82703b2905bf0f5a969d925dc8692ef56c -configuration Debug -xcconfig /Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/XCodeConfig.xcconfig' in directory '/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-gvltwgknevnwclanwpylmjozekma/Logs/Test/CC72E2BA-777E-4EF6-A348-37F419A10F0A/Session-WebDriverAgentRunner-2017-03-28_132904-Jw99p8.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.2\",\n      \"ip\" : \"10.1.8.152\"\n    },\n    \"build\" : {\n      \"time\" : \"Mar 27 2017 14:02:53\"\n    }\n  },\n  \"sessionId\" : \"8D5ED121-C828-4E71-8D0B-E2E7FA6C0617\",\n  \"status\" : 0\n}"
[debug] [XCUITest] WebDriverAgent running on ip '10.1.8.152'
[debug] [XCUITest] WebDriverAgent successfully started after 6977ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1490687950693 (13:29:10 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.tesco.scanasyoushop","arguments":[],"environment":{},"shouldWaitForQuiescence":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"405D2DE5-46C9-4AB8-9070-EA6B7DAB3784","capabilities":{"device":"iphone","browserName":"Tesco SAYS","sdkVersion":"10.2","CFBundleIdentifier":"com.tesco.scanasyoushop"}},"sessionId":"405D2DE5-46C9-4AB8-9070-EA6B7DAB3784","status":0}
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1490687951877 (13:29:11 GMT+0530 (IST))
[debug] [XCUITest] Found WDA derived data folder: '/Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy'
[XCUITest] Setting '555' permissions to '/Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments' folder
[debug] [XCUITest] Found WDA derived data folder: '/Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-ezuopqwfavbnkhaftmsayyfzxuuc'
[debug] [XCUITest] Found WDA derived data folder: '/Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-gvltwgknevnwclanwpylmjozekma'
[XCUITest] Setting '555' permissions to '/Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-gvltwgknevnwclanwpylmjozekma/Logs/Test/Attachments' folder
[debug] [BaseDriver] Event 'wdaPermsAdjusted' logged at 1490687951882 (13:29:11 GMT+0530 (IST))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1490687951882 (13:29:11 GMT+0530 (IST))
[debug] [XCUITest] Setting initial orientation to 'PORTRAIT'
[debug] [JSONWP Proxy] Proxying [POST /orientation] to [POST http://localhost:8100/session/405D2DE5-46C9-4AB8-9070-EA6B7DAB3784/orientation] with body: {"orientation":"PORTRAIT"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"405D2DE5-46C9-4AB8-9070-EA6B7DAB3784","status":0}
[debug] [BaseDriver] Event 'orientationSet' logged at 1490687951994 (13:29:11 GMT+0530 (IST))
[Appium] New XCUITestDriver session created successfully, session 00e74029-5d18-4957-a4c0-06dd1d80ea1c added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1490687951996 (13:29:11 GMT+0530 (IST))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"app":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/Tesco_SAYS.ipa","agentPath":"/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj","bootstrapPath":"/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent","platformVersion":"10.2","automationName":"XCUITest","bundleId":"com.tesco.scanasyoushop","xcodeConfigFile":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/XCodeConfig.xcconfig","platformName":"iOS","udid":"d7e9ea82703b2905bf0f5a969d925dc8692ef56c","fullReset":false,"deviceName":"Tesco's iPhone"}
[HTTP] <-- POST /wd/hub/session 200 16989 ms - 913 
[HTTP] --> GET /wd/hub/session/00e74029-5d18-4957-a4c0-06dd1d80ea1c {}
[debug] [MJSONWP] Calling AppiumDriver.getSession() with args: ["00e74029-5d18-4957-a4c0-06dd1d80ea1c"]
[debug] [XCUITest] Executing command 'getSession'
[debug] [JSONWP Proxy] Proxying [GET /] to [GET http://localhost:8100/session/405D2DE5-46C9-4AB8-9070-EA6B7DAB3784] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"sessionId\" : \"405D2DE5-46C9-4AB8-9070-EA6B7DAB3784\",\n    \"capabilities\" : {\n      \"device\" : \"iphone\",\n      \"browserName\" : \"Tesco SAYS\",\n      \"sdkVersion\" : \"10.2\",\n      \"CFBundleIdentifier\" : \"com.tesco.scanasyoushop\"\n    }\n  },\n  \"sessionId\" : \"405D2DE5-46C9-4AB8-9070-EA6B7DAB3784\",\n  \"status\" : 0\n}"
[XCUITest] Merging WDA caps over Appium caps for session detail response
[debug] [MJSONWP] Responding to client with driver.getSession() result: {"udid":"d7e9ea82703b2905bf0f5a969d925dc8692ef56c","app":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/Tesco_SAYS.ipa","agentPath":"/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj","bootstrapPath":"/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent","platformVersion":"10.2","automationName":"XCUITest","bundleId":"com.tesco.scanasyoushop","xcodeConfigFile":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/XCodeConfig.xcconfig","platformName":"iOS","fullReset":false,"deviceName":"Tesco's iPhone","device":"iphone","browserName":"Tesco SAYS","sdkVersion":"10.2","CFBundleIdentifier":"com.tesco.scanasyoushop"}
[HTTP] <-- GET /wd/hub/session/00e74029-5d18-4957-a4c0-06dd1d80ea1c 200 80 ms - 829 
[HTTP] --> GET /wd/hub/session/00e74029-5d18-4957-a4c0-06dd1d80ea1c {}
[debug] [MJSONWP] Calling AppiumDriver.getSession() with args: ["00e74029-5d18-4957-a4c0-06dd1d80ea1c"]
[debug] [XCUITest] Executing command 'getSession'
[debug] [JSONWP Proxy] Proxying [GET /] to [GET http://localhost:8100/session/405D2DE5-46C9-4AB8-9070-EA6B7DAB3784] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"sessionId\" : \"405D2DE5-46C9-4AB8-9070-EA6B7DAB3784\",\n    \"capabilities\" : {\n      \"device\" : \"iphone\",\n      \"browserName\" : \"Tesco SAYS\",\n      \"sdkVersion\" : \"10.2\",\n      \"CFBundleIdentifier\" : \"com.tesco.scanasyoushop\"\n    }\n  },\n  \"sessionId\" : \"405D2DE5-46C9-4AB8-9070-EA6B7DAB3784\",\n  \"status\" : 0\n}"
[XCUITest] Merging WDA caps over Appium caps for session detail response
[debug] [MJSONWP] Responding to client with driver.getSession() result: {"udid":"d7e9ea82703b2905bf0f5a969d925dc8692ef56c","app":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/Tesco_SAYS.ipa","agentPath":"/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj","bootstrapPath":"/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent","platformVersion":"10.2","automationName":"XCUITest","bundleId":"com.tesco.scanasyoushop","xcodeConfigFile":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/XCodeConfig.xcconfig","platformName":"iOS","fullReset":false,"deviceName":"Tesco's iPhone","device":"iphone","browserName":"Tesco SAYS","sdkVersion":"10.2","CFBundleIdentifier":"com.tesco.scanasyoushop"}
[HTTP] <-- GET /wd/hub/session/00e74029-5d18-4957-a4c0-06dd1d80ea1c 200 53 ms - 829 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.4-beta","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 11 ms - 88 
[HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[debug] [MJSONWP] Responding to client with driver.getSessions() result: [{"id":"00e74029-5d18-4957-a4c0-06dd1d80ea1c","capabilities":{"app":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/Tesco_SAYS.ipa","agentPath":"/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj","bootstrapPath":"/usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent","platformVersion":"10.2","automationName":"XCUITest","bundleId":"com.tesco.scanasyoushop","xcodeConfigFile":"/Users/dtiwa1/git/mSays-AutomationSuiteForAndroid/MSAYS_Automation/src/main/resources/APKs/XCodeConfig.xcconfig","platformName":"iOS","udid":"d7e9ea82703b2905bf0f5a969d925dc8692ef56c","fullReset":false,"deviceName":"Tesco's iPhone"}}]
[HTTP] <-- GET /wd/hub/sessions 200 2 ms - 746 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"10.2","udid":"d7e9ea82703b2905bf0f5a969d925dc8692ef56c","automationName":"Appium","bundleId":"com.tesco.scanasyoushop","deviceName":"iPhone 7"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","platformVersion":"10.2","udid":"d7e9ea82703b2905bf0f5a969d925dc8692ef56c","automationName":"Appium","bundleId":"com.tesco.scanasyoushop","deviceName":"iPhone 7"},null,null,null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1490687965454 (13:29:25 GMT+0530 (IST))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.23.1) session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.2'
[Appium]   udid: 'd7e9ea82703b2905bf0f5a969d925dc8692ef56c'
[Appium]   automationName: 'Appium'
[Appium]   bundleId: 'com.tesco.scanasyoushop'
[Appium]   deviceName: 'iPhone 7'
[Appium] Session override is on. Deleting other sessions.
[Appium]     Deleting session '00e74029-5d18-4957-a4c0-06dd1d80ea1c'
[debug] [JSONWP Proxy] Proxying [DELETE /session/00e74029-5d18-4957-a4c0-06dd1d80ea1c] to [DELETE http://localhost:8100/session/405D2DE5-46C9-4AB8-9070-EA6B7DAB3784] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"156561FC-CC26-478F-B25E-1F8A8FD467CC\",\n  \"status\" : 0\n}"
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 59414)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Shutting down iproxy process (pid 59412)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Found WDA derived data folder: '/Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy'
[XCUITest] Setting '755' permissions to '/Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments' folder
[debug] [XCUITest] Found WDA derived data folder: '/Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-ezuopqwfavbnkhaftmsayyfzxuuc'
[debug] [XCUITest] Found WDA derived data folder: '/Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-gvltwgknevnwclanwpylmjozekma'
[XCUITest] Setting '755' permissions to '/Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-gvltwgknevnwclanwpylmjozekma/Logs/Test/Attachments' folder
[debug] [iOSLog] Stopping iOS log capture
[Appium] Removing session 00e74029-5d18-4957-a4c0-06dd1d80ea1c from our master session list
[debug] [XCUITest] XCUITestDriver version: 2.23.1
[BaseDriver] Session created with session id: 5632fb7c-4a2a-4389-8307-5abf12e9ea28
[debug] [XCUITest] Xcode version set to '8.2.1' (tools v8.2.0.0.1.1480973914)
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1490687965728 (13:29:25 GMT+0530 (IST))
[debug] [XCUITest] Available devices: d7e9ea82703b2905bf0f5a969d925dc8692ef56c
[debug] [XCUITest] Creating iDevice object with udid 'd7e9ea82703b2905bf0f5a969d925dc8692ef56c'
[XCUITest] Determining device to run tests on: udid: 'd7e9ea82703b2905bf0f5a969d925dc8692ef56c', real device: true
[debug] [BaseDriver] Event 'appConfigured' logged at 1490687965808 (13:29:25 GMT+0530 (IST))
[debug] [BaseDriver] Event 'resetStarted' logged at 1490687965808 (13:29:25 GMT+0530 (IST))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1490687965809 (13:29:25 GMT+0530 (IST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1490687965861 (13:29:25 GMT+0530 (IST))
[XCUITest] Setting up real device
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1490687965862 (13:29:25 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=d7e9ea82703b2905bf0f5a969d925dc8692ef56c -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.2\",\n      \"ip\" : \"10.1.8.152\"\n    },\n    \"build\" : {\n      \"time\" : \"Mar 27 2017 14:02:53\"\n    }\n  },\n  \"sessionId\" : \"156561FC-CC26-478F-B25E-1F8A8FD467CC\",\n  \"status\" : 0\n}"
[debug] [XCUITest] WebDriverAgent running on ip '10.1.8.152'
[debug] [XCUITest] WebDriverAgent successfully started after 455ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1490687971454 (13:29:31 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.tesco.scanasyoushop","arguments":[],"environment":{},"shouldWaitForQuiescence":true}}
[debug] [XCUITest] Log file for xcodebuild test: /Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/CCE71BBC-8EEE-4D24-9A90-E80B0BFEAD33/Session-WebDriverAgentRunner-2017-03-28_132932-pna4SY.log
[Xcode] 2017-03-28 13:29:32.155 xcodebuild[59492:1237670] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/dtiwa1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fd277fb1cd0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2017-03-28 13:29:32.155 xcodebuild[59492:1237670] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'

Webdriveragent Logs:
13:29:32.145 xcodebuild[59492:1237670] Beginning test session WebDriverAgentRunner-58219052-9E2A-4771-8B85-424DE49EAE73 at 2017-03-28 13:29:32.144 with Xcode 8C1002 on target <DVTiOSDevice: 0x7fd277c24fc0> {
		deviceSerialNumber:         FFMT3FRVHFLR
		identifier:                 d7e9ea82703b2905bf0f5a969d925dc8692ef56c
		deviceClass:                iPhone
		deviceName:                 TESCO’s iPhone
		deviceIdentifier:           d7e9ea82703b2905bf0f5a969d925dc8692ef56c
		productVersion:             10.2
		buildVersion:               14C92
		deviceSoftwareVersion:      10.2 (14C92)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        27747680256
		deviceAvailableCapacity:    22016360448
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7fd2755f78b0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (10.2 (14C92))
13:29:32.146 xcodebuild[59492:1237670] 	/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
build-for-testing
test-without-building
-project
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
-scheme
WebDriverAgentRunner
-destination
id=d7e9ea82703b2905bf0f5a969d925dc8692ef56c
-configuration
Debug
13:29:32.146 xcodebuild[59492:1237670] Launching with Xcode.IDEFoundation.Launcher.PosixSpawn
13:29:32.147 xcodebuild[59492:1237670] Initializing test infrastructure.
13:29:32.152 xcodebuild[59492:1237670] Launch session started, setting a disallow-finish-token on the run operation.
13:29:32.153 xcodebuild[59492:1237670] Launch session expired.
13:29:32.154 xcodebuild[59492:1237670] Test operation failure: Launch session expired before checking in.
13:29:32.155 xcodebuild[59492:1237670] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Launch session expired before checking in." UserInfo={NSLocalizedDescription=Launch session expired before checking in.} didCancel: 1

**Comment by mykola-mokhnach** [comment] 2017-03-28 08:44
duplicate of https://github.com/appium/appium/issues/8106

**Closed by mykola-mokhnach** 2017-03-28 08:44 UTC
Labels: NeedsTriage
