### ISSUE TITLE
Facing issue with running IOS scripts with Appium 1.12.1 and 1.13 version; Error : 'null' cannot be coerced to a valid version number

### ISSUE THREAD

**Issue by JasWoolieX** [appium/appium#12637] opened 2019-05-14 03:01 UTC
## The problem

I upgraded my appium version to 1.12.1 but when I run the iOS script its now failing with the following error message:
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: 'null' cannot be coerced to a valid version number
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'NSUR01MAC091', ip: 'fe80:0:0:0:844:bf54:37a8:adee%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.3', java.version: '1.8.0_201'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'null' cannot be coerced to a valid version number

I have also tried with 1.13 version of appium and it also didn't work for IOS.

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.2@beta
* Desktop OS/version used to run Appium: 10.14.3
* Node.js version (unless using Appium.app|exe): v11.12.0
* Npm or Yarn package manager: 6.7.0
* Mobile platform/version under test: 12.1.4
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
I have tried giving platformVersion capability as "12.1.4" but that also doesn't work.
My capabilities :

 "appiumServerCapabilities": {
          "app": "qauat.ipa",
          "platformName": "iOS",
          "automationName": "XCUITest",
          "printPageSourceOnFailure":true

        },
        "iOSOnlyCapabilities": {
          "launchTimeout": 30000,
          "bundleId": "com.******.uat.supersonline",
          "noReset":true,
          "fullReset":false,
          "autoAcceptAlerts":true,
          "autoGrantPermissions": true,
          "xcodeOrgId": "*******",
          "xcodeSigningId":"iPhone Developer",
          "updatedWDABundleId":"au.com.****.WebDriverAgentRunnerAppium",
          "clearSystemFiles":true,
          "simpleIsVisibleCheck":true
        }

## Link to Appium logs
https://gist.github.com/JasWoolieX/d1729ff7c3f2fe0f96d664e2d6c9487f

**Comment by KazuCocoa** [comment] 2019-05-14 03:09
> Appium 1.12.1 platformVersion needed for real iOS device #12394

What about adding platformVersion?

**Comment by JasWoolieX** [comment] 2019-05-14 03:23
I have tried adding platformVersion as one of the capability as
"platformVersion" : "12.1.4" (As the device connected is on OS 12.1.4)
But it returns back with Error as Device not found with 12.1.4

Is this platformVersion the version of OS of the device connected?

**Comment by KazuCocoa** [comment] 2019-05-14 03:46
Can you attach the log with platformVersion?

**Comment by JasWoolieX** [comment] 2019-05-14 04:14
Sure, Attaching the log when I run with platformVersion
Error Message:
Execution failed for task ':runFragmentation'.
> com.testvagrant.commons.exceptions.DeviceMatchingException: No devices found with platform version 12.1.4

https://gist.github.com/JasWoolieX/dc7e15a7c66228e6a9948210c65aaf7f

Also can I bypass this platformVersion capability? As in If  I have to run on more than 1 device how will it be then?
Thanks for looking into this.

**Comment by KazuCocoa** [comment] 2019-05-14 04:35
Do you use any libraries?
`com.testvagrant.commons.exceptions.DeviceMatchingException` looks out of Appium.
You need to ask the library owner about the exception.

I expected your capabilities would be like below:

```
[Appium] Appium v1.12.1 creating new XCUITestDriver (v2.110.1) session
[Appium] Capabilities:
[Appium]   platformName: ios
[Appium]   printPageSourceOnFailure: true
[Appium]   app: /Users/njbh1/Documents/Official/woolworths-app-automation/app/qauat.ipa
[Appium]   autoAcceptAlerts: true
[Appium]   autoGrantPermissions: true
[Appium]   automationName: XCUITest
[Appium]   bundleId: com.woolworths.uat.supersonline
[Appium]   clearSystemFiles: true
[Appium]   deviceName: jaspreet’s iPhone
[Appium]   fullReset: false
[Appium]   launchTimeout: 30000
[Appium]   noReset: true
[Appium]   simpleIsVisibleCheck: true
[Appium]   udid: xxxx
[Appium]   updatedWDABundleId: xxxxxx
[Appium]   xcodeOrgId: xxxxx
[Appium]   xcodeSigningId: iPhone Developer
[Appium]   platformVersion: 12.1.4 # <= platformVersion
```

**Comment by mykola-mokhnach** [comment] 2019-05-14 05:31
Set platformVersion to `12.1` instead. Apple ignores patch numbers

**Comment by JasWoolieX** [comment] 2019-05-14 12:19
Thanks @KazuCocoa and @mykola-mokhnach 
Yes I am using third party library. platformVersion: 12.1 also hasn't worked for me. So for appium > 12, platformVersion is a mandatory capability to be given?

**Comment by mykola-mokhnach** [comment] 2019-05-14 13:15
Yes, it is mandatory. Since Appium 1.13.1 we are trying to autodetect it from ideviceinfo output, so it is less strict for real devices, but in general such information is important In order to properly init the driver and cannot be omitted.

**Comment by mykola-mokhnach** [comment] 2019-05-15 09:24
> platformVersion: 12.1 also hasn't worked for me

Care to attach the updated logs?

**Comment by JasWoolieX** [comment] 2019-05-16 04:16
Hello @mykola-mokhnach 
Here is the log when I use 
 "appiumServerCapabilities": {
          "app": "qauat.ipa",
          "platformName": "iOS",
          "deviceName": "jaspreet’s iPhone",
          "platformVersion": "12.1",
          "automationName": "XCUITest",
          "printPageSourceOnFailure":true
        },
**Error Message:** com.testvagrant.commons.exceptions.DeviceMatchingException: No devices found with platform version 12.1
**Error Message when I don't use platformVersion:**
xcodebuild[11508:2065327] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/njbh1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f7f99de8af0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}


**Logs with platformVersion12.1** :https://gist.github.com/JasWoolieX/009581b901aaf45207dc5eec71aab16c
**Logs without platformVersion:**
https://gist.github.com/JasWoolieX/717f56e1a417a8ee526d058598e053f5

**Comment by mykola-mokhnach** [comment] 2019-05-16 05:36
> java.lang.NullPointerException
>        at com.testvagrant.monitor.radiator.MongoWriter.lambda$updateBuildWithUniqueScenarios$1(MongoWriter.java:260)

This looks like a client error, but I anyway cannot say much, because the server log is still missing

> 2019-05-16 04:08:00:380 [Xcode] 	"WebDriverAgentRunner" requires a provisioning profile. Select a provisioning profile for the "Debug" build configuration in the project editor. (in target 'WebDriverAgentRunner')

The second log says the source is not signed properly, which has nothing to do with Appium itself.

**Comment by JasWoolieX** [comment] 2019-05-16 06:05
> > java.lang.NullPointerException
> > at com.testvagrant.monitor.radiator.MongoWriter.lambda$updateBuildWithUniqueScenarios$1(MongoWriter.java:260)
> 
> This looks like a client error, but I anyway cannot say much, because the server log is still missing
> Thanks @mykola-mokhnach I am checking the client library for this error.
> > 2019-05-16 04:08:00:380 [Xcode] 	"WebDriverAgentRunner" requires a provisioning profile. Select a provisioning profile for the "Debug" build configuration in the project editor. (in target 'WebDriverAgentRunner')
> 
> The second log says the source is not signed properly, which has nothing to do with Appium itself.
> Nothing was changed when it comes to signing the provision profile or Xcode and it was working fine for us before we updated our appium version to 13. 
I have this in my json file:
  "xcodeSigningId":"iPhone Developer",
   "updatedWDABundleId":"au.com.woolworths.WebDriverAgentRunnerAppium",
If I check this project WebDriverAgentRunnerAppium, it has been signed properly. Lemme know if you need more info.

Also where should this file be "The file “WebDriverAgentRunner-Runner.app” ?

**Comment by mykola-mokhnach** [comment] 2019-05-16 06:25
> Also where should this file be "The file “WebDriverAgentRunner-Runner.app”

This is the resulting app, which is installed on the phone after compilation finishes. Try to run the above xcodebuild command manually to debug the problem. It also might be a duplicate of https://github.com/appium/appium/issues/12581

**Comment by imurchie** [comment] 2019-05-16 11:59
> Also where should this file be "The file “WebDriverAgentRunner-Runner.app” ?

From your logs, it would eventually (when the build succeeds) be in `/Users/njbh1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app,`:
```
xcodebuild[11508:2065327] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/njbh1/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f7f99de8af0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

**Comment by mykola-mokhnach** [comment] 2019-05-18 07:35
Closed as not an issue

**Closed by mykola-mokhnach** 2019-05-18 07:35 UTC
Labels: NeedsInfo, NotABug
