### ISSUE TITLE
unrecognized selector sent to instance 0x280801d40

### ISSUE THREAD

**Issue by simonsymhoven** [appium/appium#15251] opened 2021-04-06 12:09 UTC
## The problem

I am trying connect to an iOS real device. The connection via the cli is successfully initialized, but when i get 
a screenshot via the driver in the corresponding python code, the error "unrecognized selector sent to instance" 
occurs. 
The same issue occurs when i create a new session to the device with the Appium Desktop software. 
The connection is successfully initialized, but the screen does not load with the same error as mentioned above.

## Environment

* XCode Version: 12.5 beta 2
* Mac OS: Big Sur (11.2.3)
* Appium Verison: 1.20.2
* iOs Version: iOS 14.4 and iOS 14.5 (Beta)
* Node: 15.13.0
* Device under Test: iPhone Xs
* Appium Doctor Log: appium-doctor.txt
* Appium Server Log: appium.txt

## Link to Appium logs

https://gist.github.com/simonsymhoven/3dea6cc0e62b6019ba8cff9c0f7b3eff

## Code To Reproduce Issue [ Good To Have ]

```
driver = web driver.Remote(command_executor=host, desired_capabilties= desired_capabilties)
driver.get_screenshot_as_base64()
```

or just create a new session via the Appium Desktop software.

**Comment by mykola-mokhnach** [comment] 2021-04-06 12:35
Duplicate of https://github.com/appium/appium/issues/15199

**Closed by mykola-mokhnach** 2021-04-06 12:35 UTC
