### ISSUE TITLE
bug: appium-doctor broken links for optional dependencies

### ISSUE THREAD

**Issue by ptmkenny** [appium/appium#19273] opened 2023-10-09 20:47 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run `appium-doctor`, I get this message:

```
WARN AppiumDoctor  ➜ Why applesimutils is needed and how to install it: http://appium.io/docs/en/drivers/ios-xcuitest/
WARN AppiumDoctor  ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it
WARN AppiumDoctor  ➜ gst-launch-1.0 and gst-inspect-1.0 are used to stream the screen of the device under test. Please read https://appium.io/docs/en/writing-running-appium/android/android-screen-streaming/ to install them and for more details

```

However, all three of these links are broken:

* http://appium.io/docs/en/drivers/ios-xcuitest/
* http://appium.io/docs/en/writing-running-appium/android/android-appbundle/
* https://appium.io/docs/en/writing-running-appium/android/android-screen-streaming/

### Expected Behavior

I expect the links to go to the docs.

### Minimal Reproducible Example

`appium-doctor` on a system without the optional dependencies installed.

### Environment

Appium Doctor v.2.0.25

**Comment by mykola-mokhnach** [comment] 2023-10-10 06:37
Duplicate of https://github.com/appium/appium/issues/18761

**Closed by mykola-mokhnach** 2023-10-10 06:37 UTC
Labels: Bug, Needs Triage

**Comment by kwhirayama** [comment] 2025-06-03 06:28
1 is fixed, but 2 and 3 are not fixed.

> 1. applesimutils
> http://appium.io/docs/en/drivers/ios-xcuitest/
> 
> 2. bundletool.jar
> http://appium.io/docs/en/writing-running-appium/android/android-appbundle/
> 
> 3. gst-launch-1.0 and gst-inspect-1.0
> https://appium.io/docs/en/writing-running-appium/android/android-screen-streaming/

**Comment by KazuCocoa** [comment] 2025-06-03 07:50
Do you refer to `appium driver doctor uiautomator2`?
https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#doctor

Current bundletools points to https://github.com/google/bundletool/releases/
the gst is https://gstreamer.freedesktop.org/documentation/installing/index.html?gi-language=c
