### ISSUE TITLE
While running script on Iphone simulator- iOS app is getting stuck when loader appears on screen. Manually with xcode It works fine.

### ISSUE THREAD

**Issue by ssdev1510** [appium/appium#14679] opened 2020-08-26 11:31 UTC
Summary-
Issue seems like with WDA, as when i am deleting WDA app from simulator then trying to perform action with loader on screen- it works fine manually.
I performed manually it works fine with appium and xcode simulator.
While running script app get stuck.

Using :
Appium 1.17-1
xcode 11.5 for iphone 11 simulator.
MacOS catalina

**Comment by mykola-mokhnach** [comment] 2020-08-26 12:31
Duplicate of https://github.com/appium/appium/issues/13580

This is the issue of XCTest/app under test itself.
You could try to play with `waitForQuiescence`/`wdaEventloopIdleDelay` capability values to workaround it.

**Closed by mykola-mokhnach** 2020-08-26 12:31 UTC
Labels: ThirdParty, XCUITest
