### ISSUE TITLE
app element tree (on IOS) not looking good 

### ISSUE THREAD

**Issue by orevron** [appium/appium#10654] opened 2018-05-07 12:16 UTC
## The problem

i have a **react native** app that i want to test
when i open the appium app inspector with the android version of this app, the element tree is looking well and i can identify all elements as i want too..
but when i try the ios version all the accessibility ids that i added (those that seen good on android) are all on the same element (see attachment for screenshot to understand better)

## Environment
Appium version (or git revision) that exhibits the issue: 1.7.2
Desktop OS/version used to run Appium: High Sierra 10.13.4
Node.js version (unless using Appium.app|exe): 9.8.4
Mobile platform/version under test: 11.3
Real device or emulator/simulator: android emulator -> looking good; ios simulator -> not good
Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://gist.github.com/orevron/75a818ee0640dd81bc1fbb1e642de3ea
![screen shot 2018-05-07 at 2 19 18 pm](https://user-images.githubusercontent.com/20145882/39701418-b89546da-5209-11e8-9634-7d4627abc969.png)

the app is here: https://drive.google.com/open?id=1idGFzK-Ry229bqU6v6f0_zYPlR5yCh3o

**Comment by hakkori** [comment] 2018-05-31 11:44
We are currently facing the same issue and so far we've tried; 

- changing react-native's version from 0.55.3 to the previous one which was 0.51.0, 
- removing testId to accessibilityLabel plugin: https://github.com/jribeiro/babel-plugin-jsx-property-alias
- Xcode's own inspector

none of them seems to be working. Hope this information will help

**Comment by mykola-mokhnach** [comment] 2018-05-31 11:48
@hakkori One should switch to webview context if working with react.

**Comment by hakkori** [comment] 2018-05-31 12:02
@mykola-mokhnach I have no problem finding elements with appium driver without switching to webview, but the text of the elements I can not get it. getText(), getAttribute("text/value/name..") these all return the same value which is the accessibilityLabel.

I also actually opened a ticket on appium discuss: https://discuss.appium.io/t/react-native-app-on-ios-element-has-the-same-value-for-name-values-text-accessibilitylabel-etc/22237

But if switching to webview would help I could give it a try

**Comment by hakkori** [comment] 2018-05-31 12:07
@mykola-mokhnach and as @orevron mentioned, android version is fine, same elements I can manipulate, get text, click etc.. but on ios finding element no problem, tapping it no problem, getting elements' text = problem.

**Comment by mykola-mokhnach** [comment] 2018-05-31 12:10
@hakkori Feel free to ping Facebook and Apple developers regarding how they render react webviews and what is visible to the accessibility manager there.

**Comment by orevron** [comment] 2018-05-31 12:11
my issue is a bit different from yours (as you can see in my screenshot the whole data the shown on the page is part of my accessibility label)...

as for the element interaction with the IPhone, I can't even find them... let alone interact with them.

and yet same app on android working perfect!

**Comment by stevesouth** [comment] 2018-06-14 08:24
Same issue here, has anyone made any progress?

**Comment by orevron** [comment] 2018-06-14 08:34
@stevesouth nope... didn't find solution... still hope that someone will solve it

**Comment by muxe** [comment] 2018-07-16 15:33
Still no solution?
I have the same on Appium 1.8.1, iOS 11.4, RN 0.56.0

Android works fine, iOS looks like above

**Comment by orevron** [comment] 2018-07-17 06:32
@muxe @stevesouth  "TouchableWithoutFeedback" is the react native component that causes the mess with testIDs and elements tree.

try not using them

**Comment by muxe** [comment] 2018-07-17 09:43
sadly I'm not even using * TouchableWithoutFeedback*. The RN Code might be as simple as:
```js
import React, {Component} from 'react';
import {Text, View} from 'react-native';

export default class App extends Component {
  render() {
    return (
      <View>
        <Text accessibilityLabel="simple-test">Simple Text</Text>
      </View>
    )
  }
}
```

For iOS there is no way to get the actual text content.

How it looks for android:
<img width="1107" alt="screen shot 2018-07-17 at 11 40 25" src="https://user-images.githubusercontent.com/356123/42809671-6e447be8-89b6-11e8-8d01-f6ec4e33453c.png">
 
How it looks for iOS:
<img width="1108" alt="screen shot 2018-07-17 at 11 39 01" src="https://user-images.githubusercontent.com/356123/42809670-6e2c56da-89b6-11e8-927d-05d641c992ad.png">

**Comment by saikrishna321** [comment] 2018-07-17 14:14
@muxe refer this https://github.com/appium/VodQAReactNative/blob/master/screens/DrapAndDrop.js#L55-L57

accessibilityLabel --> Is for android
testID --> Is for iOS


Closing this issue as its not related to appium

**Closed by saikrishna321** 2018-07-17 14:14 UTC

**Comment by Vinothbk** [comment] 2018-09-10 06:09
@saikrishna321 Can you please tell me what is the solution and how can we proceed with appium for such kind of issues?

**Comment by Vinothbk** [comment] 2018-09-10 06:11
I am also facing the same issue. 
![image](https://user-images.githubusercontent.com/8637812/45279302-579e2c00-b4ee-11e8-9a31-d04dd9f2b486.png)
can anyone please tell me the solution for this issue.

**Comment by saikrishna321** [comment] 2018-09-10 09:10
@Vinothbk the App needs to be testable, you need to ask your developers to make changes 

https://github.com/appium/VodQAReactNative/blob/master/screens/LongPress.js#L28-L31

Please ask questions in discuss.appium.io

**Comment by khause** [comment] 2019-05-14 11:20
This is still an issue, I am unable to get the displayed text from any element using it's `accessibilityLabel` on an ReactNative application. If I use `getText()`, it just returns the `accessibilityLabel` value.

**Comment by ZacMonroe** [comment] 2019-05-14 22:30
I am having this same issue

**Comment by ujnatg** [comment] 2020-05-18 22:31
still have issues with testing using Appium

**Comment by Edward-MS** [comment] 2020-07-29 18:26
Same issue here. To show details element tree, the app may need to launch with instrument mode, but don't know how to do it in appium. In appium studio, it only require a checked checkbox. 
iOS App : React Native
Appium Version : 1.16.0

**Comment by shreyapz** [comment] 2020-10-05 08:29
> I am also facing the same issue.
> ![image](https://user-images.githubusercontent.com/8637812/45279302-579e2c00-b4ee-11e8-9a31-d04dd9f2b486.png)
> can anyone please tell me the solution for this issue.

@Vinothbk are you able to find the workaround for the same? I am facing the same issue with react native iOS app. All the elements are combined in to one element and Appium is not letting me identify a single element. The same app works absolutely fine on android.

**Comment by haunguyen-agilityio** [comment] 2020-10-08 03:18
@samaitra @Vinothbk any updates here? How do we fix this issue?

**Comment by piotrponikowski** [comment] 2020-10-16 15:04
As a workaround you can try to add accessibility label also to parent of the element you want to select. For example update
```jsx
<View>
    <Text accessibilityLabel="simple-test">Simple Text</Text>
</View>
```
to 
```jsx
<View accessibilityLabel="simple-test-wrapper">
    <Text accessibilityLabel="simple-test">Simple Text</Text>
</View>
```

**Comment by jcerrutti** [comment] 2020-11-27 14:07
Hi folks! Had you find any solution for this? I'm facing exactly the same issue with iOS. Android version works perfect.

**Comment by piotrponikowski** [comment] 2020-11-27 14:34
Did you try my solution?

**Comment by jcerrutti** [comment] 2020-11-27 14:44
> Did you try my solution?

Yes, I just tried and works fine when I render just a View and some child element inside.

But on my app, where I have multiple views, I only can see the first View (multiple times) but anything else inside, where I have more views (with this props).

![image](https://user-images.githubusercontent.com/5330226/100460409-e4206f00-30a5-11eb-8af9-c9331b4cd9c5.png)

**Comment by piotrponikowski** [comment] 2020-11-27 15:11
This is also how it behave on my side: parent is inheriting labels from children on iOS. For all cases I had, adding dummy label for parent views work. In most cases I didn't even need these labels for Android, and I was not referencing them from my appium tests.

**Comment by gauravg27** [comment] 2021-04-14 18:02
@piotrponikowski  : Its duplicating accessibilitylabel value of view in all element under it  making

**Comment by kat-max** [comment] 2021-06-07 15:47
Any progress on this one? I'm also having the same issue :/

**Comment by gauravg27** [comment] 2021-06-08 11:52
Not yet .. Waiting for response from community

**Comment by jlipps** [comment] 2021-06-10 00:35
@wswebcreation has a good tutorial/strategy that should address this; do you mind sharing the link in this issue as well?

**Comment by wswebcreation** [comment] 2021-06-10 07:05
@jlipps 

Thanks for pinging me.

@gauravg27 and @kat-max , this has nothing to do with Appium, but with the way ReactNative is handling the accessibilityIDs. For iOS you should use the `testID` in the code, see for example the RN View component [here](https://reactnative.dev/docs/view#testid)

What I previously did was using this helper for RN apps https://github.com/webdriverio/native-demo-app/blob/main/src/config/TestProperties.ts#L8. I added it in for example a button component like [this](https://github.com/webdriverio/native-demo-app/blob/38c7427588c2181343f3a7919bdd8340ebb08075/src/components/Button.tsx)

The support for `testID` has become better now for newer versions of RN so you don't need to pollute the RN components with `accessibilityID`s for Android. `testId` should now also work for Android on the latest versions. My example is just to make sure that it's backwards compatible with older versions of RN

**Comment by irramya** [comment] 2021-06-21 10:48
I struggled with this issue for almost a month. I tried locating the elements on different versions of appium desktop, added all combinations of accessibilityLabel and testID too. Nothing worked.

Finally, I realized that the issue in my case was because of using Touchable* tags in the react-native code.
All the Touchable* tags are accessible by default making the children inaccessible.
They are also the reason why all the parent tags have the same name and label.
So, my fix was to explicitly add accessible={false} in all the Touchable* tags and now I can locate individual elements without any trouble.

Touchable* = TouchableOpacity, TouchableWithoutFeedback, etc.
Hope this solution helps.

**Comment by jlipps** [comment] 2021-06-22 04:10
thanks for that really helpful research, @irramya!

**Comment by Konnor5092** [comment] 2021-06-23 15:11
I'm really struggling with this one.

The Appium inspector for my react native `.app` file running on an iOS simulator stops here.... 

![Inspector](https://user-images.githubusercontent.com/18048889/123116781-0db03780-d3f6-11eb-8a4b-2ddfccb3d413.png)

I've tried all sorts of combinations of `accessible={false}` and `testID` or `accessibilityLabel` but nothing seems to work. This is the function I have settled on...

```javascript
import { Platform } from 'react-native';

export function accessibility(id?: string) {
  return Platform.OS === 'android'
    ? { accessibilityLabel: id }
    : {
        accessible: false,
        testID: id
      };
}
```
I've then tried to basically spam it everywhere from the lowest point for a custom `Button` component...
```javascript
  return (
    <AnimatedPressable
      {...accessibility('IAMASPOONANIMATEDPRESS')}
      onPress={onPress}
      onPressIn={() => setPressed(true)}
      onPressOut={() => setPressed(false)}
      scale={0.98}
      //accessible
      //accessibilityHint={`A button to complete or start the action; ${title}`}
      //accessibilityLabel={title}
      {...props}
      style={props.style ?? undefined}
    >
      <View
        {...accessibility('IAMASPOONVIEW')}
        style={[
          styles.buttonContainer,
          props.disabled && styles.disabledButton
        ]}
      >
        <Text
          {...accessibility('IAMASPOONTEXT')}
          numberOfLines={1}
          ellipsizeMode="tail"
          style={[styles.textStyle, props.disabled && styles.disabledText]}
        >
          {title}
        </Text>
      </View>
    </AnimatedPressable>
  );
};
```
`AnimatedPressable` is a custom component that wraps the react-native `Pressable` component. I've also tried using my function on that as well...
```javascript
<Pressable
  //accessibilityState={{ ...props.accessibilityState, disabled: !!disabled }}
  //accessibilityLabel={props.accessibilityLabel}
  {...accessibility('IAMASPOONPRESSABLE')}
  focusable={!disabled}
  hitSlop={10}
  onPressIn={() => {
    if (onPressIn !== undefined) {
      onPressIn();
    }
    timing(containerScale, {
      duration: 400,
      toValue: scale === undefined ? 0.99 : scale,
      easing: EasingNode.elastic(2)
    }).start();
  }}
  onPressOut={() => {
    if (onPressOut !== undefined) {
      onPressOut();
    }
    timing(containerScale, {
      duration: 400,
      toValue: 1,
      easing: EasingNode.elastic(2)
    }).start();
  }}
  onPress={onPress}
  disabled={disabled}
  style={style}
  {...props}
>
  <Animated.View
    style={[
      styles.container,
      extraStyle,
      { transform: [{ scale: containerScale }] }
    ]}
  >
    {children}
  </Animated.View>
</Pressable>
```
Then for example my button is used here...
```javascript
return (
    <View style={styles.container} {...accessibility('IAMASPOONTOPLEVEL')}>
      <MdTitleMackinacBold style={styles.title}>
        Welcome to the new powerful property portal.
      </MdTitleMackinacBold>
      <Body style={styles.body}>
        Sign up and take advantage of all that Boomin has to offer.
      </Body>

      <Button
        {...accessibility('IAMASPOONTOPLEVEL')}
        title="Log in / Sign up"
        onPress={() => navigation.navigate('Auth')}
        mode="primary"
      />
    </View>
  );
```
 No 'SPOON' exists anywhere in the inspector.

If anyone is available for some paid consultancy to look into this let me know

**Comment by wswebcreation** [comment] 2021-06-23 15:27
@Konnor5092 

Do you have a reproducible example somewhere that I can help debug?

**Comment by Konnor5092** [comment] 2021-06-23 15:33
@wswebcreation I could demo this privately but unfortunately as it's in a massive private company repository I won't be able to post the app in its current.

I may try to extract everything that is used in the single button I'm attempting to locate although I'm not sure how long that will take me.

**Comment by wswebcreation** [comment] 2021-06-23 15:36
Reason for asking, and it might be far-fetched, is that with RN we have a lot of views, especially you are using a specific version of the RN navigation. Basically a _polluted_ tree. AFAIK Appium can only give back a certain amount elements, the depth.

Have your tried playing with this capability?



snapshotMaxDepth | int | Changes the value of maximum depth for traversing elements source tree. It may help to prevent out of memory or timeout errors while getting the elements source tree, but it might restrict the depth of source tree. Please consider restricting this value if you observed an error like Timed out snapshotting com.apple.testmanagerd... message or Cannot get 'xml' source of the current application in your Appium log since they are possibly timeout related. A part of elements source tree might be lost if the value was too small. Defaults to 50
-- | -- | --

See https://github.com/appium/appium-xcuitest-driver

**Comment by Konnor5092** [comment] 2021-06-23 15:45
I tried with these settings on the the inspector and it didn't make any difference to the depth of elements displayed

```json
{
  "platformName": "iOS",
  "deviceName": "iPhone 12 Pro Max",
  "app": "/Users/matthewoconnor/Downloads/Boomin.app",
  "automationName": "XCUITest",
  "snapshotMaxDepth": 500
}
```

**Comment by wswebcreation** [comment] 2021-06-24 07:27
@Konnor5092 

Sorry, you need to set this value via the [Settings Api](https://appium.io/docs/en/advanced-concepts/settings/), setting it in the caps will not work. you can call the settings api in Appium Desktop via the Actions Tab, next to the Source tap

**Comment by Konnor5092** [comment] 2021-06-24 08:40
@wswebcreation 

I _think_ I've done this right?....

![image](https://user-images.githubusercontent.com/18048889/123229779-84b8ff00-d4ce-11eb-94f6-8cb9d0130ab8.png)
 
This returned `<-- POST /wd/hub/session/eb78d872-c99d-4efc-a701-b33ce8e6ce95/elements 200 49 ms - 74` in the Appium Server desktop logs.

Unfortunately it made no difference to the visible elements in the inspector. 

I suspect I might be experiencing [this](https://github.com/appium/appium/issues/14825) issue as well. I'll see if I can recreate part of the app and see where it starts to go wrong. :(

**Comment by wswebcreation** [comment] 2021-06-24 09:55
Happy to jump on a call sometime to further try to debug this, but the issue mentioned was also what I was referring to in my previous comment

**Comment by Konnor5092** [comment] 2021-06-24 10:13
> Happy to jump on a call sometime to further try to debug this, but the issue mentioned was also what I was referring to in my previous comment

Ta. I've dropped you an email

**Comment by sharan-SKY** [comment] 2021-06-28 02:13
Has anybody found the solution for this please?

**Comment by nuvolarmobileteam** [comment] 2021-07-01 06:02
We are facing the exact same problem here. Since we moved to react-navigation v5 we can not reach all the accessibility id's. I've followed the same process that @Konnor5092 described here: https://github.com/appium/appium/issues/10654#issuecomment-867453774 and it had no impact. 50 nested levels are the maximum appium can reach.

Any workaround you guys can think of?

Thanks in advance!

**Comment by nuvolarmobileteam** [comment] 2021-07-13 08:21
After some more investigation we realised that the issue is not related to the settings themselves. We are able to change the `snapshotMaxDepth ` but when we reach the nested view below level 63 we get the error reported by @Konnor5092:

`[WD Proxy] Got response with status 404: {"value":{"error":"stale element reference","message":"The previously found element \"Application 'com.boomin.customer'\" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: Error kAXErrorIllegalArgument getting snapshot for element  {pid=3104} {uid=[ID:1 hash:0x0]}","traceback":"(\n\t0   CoreFoundation                      0x000000010bbabfba __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x000000010ba55ff5 objc_exception_throw + 48\n\t2   WebDriverAgentLib                   0x0000000132251e35 -[XCUIElement(FBUtilities) fb_takeSnapshot] + 1077\n\t3   WebDriverAgentLib                   0x00000001322520eb -[XCUIElement(FBUtilities) fb_snapshotWithAttributes:maxDepth:] + 187\n\t4   WebDriverAgentLib                   0x00000001321ef699 +[FBXPath writeXmlWithRootElement:indexPath:elementStore:includedAttributes:writer:] + 937\n\t5   WebDriverAgentLib                   0x00000001321ee9c9 +[FBXPath x...`

Any idea why this may be happening?

**Comment by ncoma** [comment] 2021-07-14 18:15
@nuvolarmobileteam I've been dealing with that exact problem. I found out that it was being caused by making some views "accessible={false}". Now I can't just set every custom view or whatever "accessible={false}" since it would throw me that stale element error so I have to be careful with which views I'll make not accessible.

**Comment by nuvolarmobileteam** [comment] 2021-07-15 06:59
hey @ncoma,

That is really interesting. We are using `accessible={false}` because otherwise touchable opacities group all the subviews into the parent one and if so, we have no access to the nested ones.

I'd say that you stop having the issue removing `accessible={false}` because this reduces the number of nested views (as it merges all subviews inside).

In the project we are having this problem, I removed parent views from the view hierarchy (as a test), and using the views that have `accessible={false}` the system would work again. This is not a proper solution since I broke the whole navigation stack of the app.
So IMO the problem is still the number of nested levels in the view hierarchy

After several days of debugging (Appium and iOS Web Driver) I could not find why this is happening when reaching such a level of nesting so as a workaround I had to go back to react-navigation 4 that reduces drastically the number of child views.

**Comment by tommaso-sebastianelli** [comment] 2021-09-28 10:53
After spending hours facing this problem I think i finally found the cause: it should be caused by React Native SectionList.
Its property **accessibilityLabel** has this description: 

_Overrides the text that's read by the screen reader when the user interacts with the element. By default, the label is constructed by traversing all the children and accumulating all the Text nodes separated by space._

I my case setting that props successfully breaks the string accumulation label issue :tada:.

**Comment by hamidmunir10pearls** [comment] 2021-11-22 05:18
Hey guy i had same issue in ios app and  i resolved this by a simple setting:
Go to Appium inspector and launch your app
click on Actions
Go to Session
Go to Settings and and the following json setting
{ "customSnapshotTimeout": 50000, "snapshotMaxDepth": 60 }
Add the following setting inside your scripts for ios app only where you are initialising driver
iosDriver.setSetting("snapshotMaxDepth", 59);
iosDriver.setSetting("customSnapshotTimeout", 50000);

**Comment by abhijeetkange** [comment] 2022-07-13 11:39
snapshotMaxDepth worked for me and now i am able find the elements

**Comment by arthurgeron-work** [comment] 2022-12-09 18:22
We consistently reproduced this issue by wrapping inner text input fields/touchables with a wrapping "TouchableOpacity" or "TouchableWithoutFeedback" component

**Comment by farouksabbek** [comment] 2023-08-02 14:01
I'm testing an iOS app,
I'm using this capabilitys on my Appium Inspector
```
{
  "appium:deviceName": "iPhone 14",
  "appium:platformName": "ios",
  "appium:platformVersion": "16.2",
  "appium:bundleId": "********",
  "appium:automationName": "XCUITest",
  "appium:settings[snapshotMaxDepth]": 70,
  "appium:settings[customSnapshotTimeout]": "50000"
}
```

I'm using Appium 2

Appium Inspector still loading and I don't the app source


I want to get xpath element with Appium inspector

Any help please

**Comment by dataforce-michael** [comment] 2023-10-25 05:35
🙏 @irramya 

Just to add:
```jsx
<TouchableOpacity accessible={!__DEV__} >
...
```
We probably still need it to be accessible in Prod.

**Comment by arthurgeron-work** [comment] 2023-10-27 15:01
> 🙏 @irramya
> 
> Just to add:
> 
> ```js
> <TouchableOpacity accessible={!__DEV__} >
> ...
> ```
> 
> We probably still need it to be accessible in Prod.

Yes, it's definitely a less than ideal solution, given that that actually interferes with screen readers.
