### ISSUE TITLE
isDisplayed() return false but element actually displayed in screen

### ISSUE THREAD

**Issue by SpeakSugar** [appium/appium#14463] opened 2020-06-18 08:36 UTC
## The problem

in daily ci task
when call element.isDisplayed() it sometimes return false but the element is actually displayed

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS10.15.4
* Node.js version (unless using Appium.app|exe): 10.16.3
* Npm or Yarn package manager: npm
* Mobile platform/version under test: ios 13.5
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: appium cli

## Details

when i get the element , then call element.isDisplay() it sometimes return false in the same condition

## Link to Appium logs

[GIST](https://gist.github.com/SpeakSugar/0d5d9a6607cd7350528da40a7516029d)

**Comment by mykola-mokhnach** [comment] 2020-06-18 08:38
Unfortunately there is nothing we could do there from Appium side. Closed as duplicate of https://github.com/appium/appium/issues/11507

**Closed by mykola-mokhnach** 2020-06-18 08:38 UTC
