### ISSUE TITLE
Application crashed on launch

### ISSUE THREAD

**Issue by sjrjanardhana** [appium/appium#4308] opened 2014-12-23 17:24 UTC
We are observing application crash uncaught Exception error some times on app launch. please find the  appium server logs below.

nfo: [debug] [INST] 2014-12-23 17:22:13 +0000 Debug: Got new command 6 from instruments: au.capture('screenshot0743e303-0e46-445c-8e3c-b860a6d2f640')

info: [debug] [INST] 2014-12-23 17:22:13 +0000 Debug: evaluating au.capture('screenshot0743e303-0e46-445c-8e3c-b860a6d2f640')

info: [debug] [INST] 2014-12-23 17:22:13 +0000 Debug: target.captureRectOnScreenWithName("{origin:{x:0.00,y:256.00}, size:{height:768.00,width:1024.00}}", UIScreen, "screenshot0743e303-0e46-445c-8e3c-b860a6d2f640")

info: [debug] Socket data received (25 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}

info: [debug] [INST] 2014-12-23 17:21:00 +0000 Fail: The target application appears to have died

info: [debug] [INST] Instruments Trace Complete (Duration : 46.605282s; Output : /tmp/appium-instruments/instrumentscli0.trace)

info: [debug] [INSTSERVER] Instruments exited with code 0

info: [debug] Cleaning up after instruments exit
info: [debug] Instruments exited unexpectedly
info: [debug] Shutting down command proxy and ignoring any errors
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator

info: [debug] Killing any other simulator daemons

info: [debug] On a real device; cannot clean device state
info: [debug] Cleaning up appium session

info: [debug] Pushing command to appium work queue: "au.getScreenOrientation()"

info: [debug] Pushing command to appium work queue: "au.capture('screenshot0743e303-0e46-445c-8e3c-b860a6d2f640')"

error: uncaughtException: undefined is not a function date=Tue Dec 23 2014 22:51:08 GMT+0530 (IST), pid=5930, uid=501, gid=20, cwd=/Applications/Appium.app/Contents/Resources/node_modules/appium, execPath=/Applications/Appium.app/Contents/Resources/node/bin/node, version=v0.10.32, argv=[/Applications/Appium.app/Contents/Resources/node/bin/node, /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js, --command-timeout, 7200, --session-override, --app, com.dishnetwork.DANY-Mobile, --udid, bbf20e0c5fc880d54d1e3a9491284d2150e059a0, --device-name, iPad Air, --launch-timeout, 90000, --native-instruments-lib], rss=76312576, heapTotal=62339584, heapUsed=39089568, loadavg=[1.6123046875, 1.40576171875, 1.48486328125], uptime=174224, trace=[column=15, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js, function=null, line=1253, method=null, native=false, column=28, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=null, line=709, method=null, native=false, column=28, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js, function=null, line=1243, method=null, native=false, column=20, file=fs.js, function=null, line=207, method=null, native=false, column=15, file=fs.js, function=Object.oncomplete, line=107, method=oncomplete, native=false], stack=[TypeError: undefined is not a function,     at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js:1253:15,     at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:709:28,     at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js:1243:28,     at fs.js:207:20,     at Object.oncomplete (fs.js:107:15)]

**Comment by ahmedmemon93** [comment] 2015-01-26 11:42
Hi, 

I am facing the same issue. did you find the solution or cause ?

**Comment by ahmedmemon93** [comment] 2015-01-26 11:42
Hi, 

I am facing the same issue. did you find the solution or cause ?

**Comment by sjrjanardhana** [comment] 2015-02-04 15:56
No resolution yet....

**Comment by imurchie** [comment] 2015-02-04 23:22
Can you provide a little more detail about the circumstances? It appears to be a real device. Are you running from the command line? What capabilities? The _full_ logs would help reproduce and diagnose.

**Comment by imurchie** [comment] 2015-03-04 17:50
At least the version of Appium this is happening in would be helpful.

**Comment by imurchie** [comment] 2015-03-09 18:52
I'm closing, since nothing seems to be happening.

**Closed by imurchie** 2015-03-09 18:52 UTC
Labels: NeedsTriage
