### ISSUE TITLE
ERROR in Page source

### ISSUE THREAD

**Issue by pr4bh4sh** [appium/appium#9402] opened 2017-10-08 14:31 UTC
## The problem
I'm getting Error text in the Page Source DOM.
![image](https://user-images.githubusercontent.com/6311526/31317430-b30a9734-ac5e-11e7-9bbb-a9975e578488.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: Appium desktop (1.2.3)
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 10.0
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app
* Xcode: Version 9.0 (9A235)
* App used: https://github.com/saikrishna321/AppiumTestDistribution/blob/master/VodQAReactNative.zip

## Details
Steps:
1. Start Appium Desktop at 4723
2. Start the session with the caps(provided in code to reproduce section)

## Link to Appium logs
https://gist.github.com/pr4bh4sh/8163c6bc719c4900634293b4b45fe3a8

## Code To Reproduce Issue :
I'm using Appium Desktop, here's the caps
```json
{
  "app": "/Users/prabhashs/Downloads/VodQAReactNative.zip",
  "automationName": "XCUITest",
  "deviceName": "iPhone 6",
  "platformVersion": "10.0",
  "platformName": "iOS",
  "noReset": true
}
```
On iOS 11, I do not see this issue.

**Comment by mykola-mokhnach** [comment] 2017-10-08 16:31
Duplicate of https://github.com/facebook/WebDriverAgent/issues/703

**Closed by mykola-mokhnach** 2017-10-08 16:31 UTC
