### ISSUE TITLE
Unable to run automated test on iOS simulator: "No WDA on the device"

### ISSUE THREAD

**Issue by ayimaster** [appium/appium#16350] opened 2022-01-18 23:34 UTC
## Unable to run the automated test on iOS simulator. 

I have ran these same tests before updating Mac OS to Monterrey and updating xcode and it worked. 
After the update as soon as I run the same test the errors are: 

`The simulator has '0' bundles which have 'WebDriverAgentRunner-Runner' as their 'CFBundleName':
[debug] [35m[WebDriverAgent][39m No WDAs on the device.`

`[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[info] [35m[WD Proxy][39m connect ECONNREFUSED 127.0.0.1:8100
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'`

## Environment

* Appium version 1.22.2
* Last Appium version that did not exhibit the issue (if applicable):1.22.1
* Desktop OS/version used to run Appium: Mac OS 12.01
* Node.js version (unless using Appium.app|exe): v16.13.0
* Npm or Yarn package manager: npm 8.1.0
* Mobile platform/version under test: iOS (iPhone 11, 12)
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium Server GUI

## Details

As soon as the test runs, the app gets installed, but the tests do not run.

## Link to Appium logs

GIST File: https://gist.github.com/ayimaster/65bf26e0b97c8864f73b35ee187d3af5

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2022-01-18 23:50
> [debug] [35m[XCUITest][39m No real device with udid 'C5C46651-D747-443B-83D9-AF33570CA3F0'. Looking for simulator[info] [35m[iOSSim][39m Constructing iOS simulator for Xcode version 13.2.1 with udid 'C5C46651-D747-443B-83D9-AF33570CA3F0'

It does not make sense to provide UUID for a simulator. It is only needed for real devices

Please provide the full log. From the existing one I could assume WDA does not have enough time to compile, which would be a duplicate of https://github.com/appium/appium/issues/16258

**Comment by ayimaster** [comment] 2022-01-19 08:37
@mykola-mokhnach thank you for replying. 
I added the capabilities provided in #16258 but now it is giving the famous `xcodebuild exited with code '65' and signal 'null'  `
Looking at appium documentation for manual configuration, `Given this installation location, /path/where/installed/bin/appium, WebDriverAgent project will be found in /path/where/installed/lib/node_modules/appium/node_modules/appium-webdriveragent. Open a terminal and go to the location, then run the next script.`
webdriveragent folder does not exist anymore, correct? 
My appium version is above 1.22 so there is no need to manually configure WDA. I guess this is related to xcode settings, outside of appium scope, but I do not know how to solve this issue. 
Please see the GIST file with the logs : https://gist.github.com/ayimaster/e05c24cad0de4602d4c2e9bfada40460

**Comment by mykola-mokhnach** [comment] 2022-01-19 09:50
AFAIK the log above looks pretty fine, the test did run properly. Where exactly is the issue there?

**Comment by ayimaster** [comment] 2022-01-19 10:01
@mykola-mokhnach, there are three questions: 
1. if I am running on simulator, can I leave the port in Appium (desktop) as it is: 4723, without touching WebDriverAgent port: 8100? 
2. Once I run the script, in the simulator it installs the TheApp and WebDriverAgent (app), so I can see two apps being installed, is this normal? 
3. At the end of the log, there are errors: 
`[error] [35m[Xcode][39m Failing tests:
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m 	WebDriverAgentRunner:
[error] [35m[Xcode][39m 		-[UITestingUITests testRunner]
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m ** TEST EXECUTE FAILED **
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m [error] [35m[Xcode][39m Testing started
[error] [35m[Xcode][39m 
[error] [35m[WebDriverAgent][39m xcodebuild exited with code '65' and signal 'null'`
Is this the way it should be? 
Thank you.

**Comment by mykola-mokhnach** [comment] 2022-01-19 10:36
@ayimaster kindly use Appium forum to ask questions.

Closing this thread as not an issue.

**Closed by mykola-mokhnach** 2022-01-19 10:36 UTC
Labels: NotABug, NeedsInfo
