### ISSUE TITLE
Not Able to send Keys to the Text filed even if Element is enable

### ISSUE THREAD

**Issue by gs-rsrivastav** [appium/appium#14743] opened 2020-09-18 09:02 UTC
## Not Able to send Keys to the Text filed even if Element is enable 

Our app is using node-base 2.12.0 for UI implementation, I am trying to provide input to text box but getting following error 
` Encountered internal error running command: InvalidElementStateError: Error Domain=com.facebook.WebDriverAgent Code=1 "'"subDomainInputFld" Other' is not ready for a text input. Neither the accessibility element itself nor its accessible descendants have the input focus" UserInfo={NSLocalizedDescription='"subDomainInputFld" Other' is not ready for a text input. Neither the accessibility element itself nor its accessible descendants have the input focus}`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac OS 10.15.6
* Node.js version (unless using Appium.app|exe): 14.5.0 (Appium.app|exe version -v 1.18.0-1)
* Npm or Yarn package manager:  Yarn 1.22.4
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: tried both

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2020-09-18 09:44
Duplicate of https://github.com/appium/java-client/issues/1386

**Closed by mykola-mokhnach** 2020-09-18 09:44 UTC
