### ISSUE TITLE
Android: "Original error: Cannot verify the signature of appium-uiautomator2-server-v4.12.4.apk" 

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#14752] opened 2020-09-22 18:07 UTC
## The problem

Error appears right on start driver with full reset options. Problem dit not happen with Appium 1.18.1 version.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.0-beta.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: real device with android 10

## Details

Tried 2 build tools (30.0.2 + 29.0.2) both same result:
```
An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.12.4.apk'. Original error: Command '/Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java -Xmx1024M -Xss1m -jar /Users/qa/Library/Android/sdk/build-tools/30.0.2/lib/apksigner.jar verify --print-certs /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.12.4.apk' exited with code 1

An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.12.4.apk'. Original error: Command '/Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java -Xmx1024M -Xss1m -jar /Users/qa/Library/Android/sdk/build-tools/29.0.2/lib/apksigner.jar verify --print-certs /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.12.4.apk' exited with code 1
```

**Comment by mykola-mokhnach** [comment] 2020-09-22 18:10
The error is expected. SDK 30 required java9+

**Comment by amedvedjev** [comment] 2020-09-22 18:11
wow. thanks!

**Comment by amedvedjev** [comment] 2020-09-22 18:12
what about SDK "29.0.2" ?

**Comment by mykola-mokhnach** [comment] 2020-09-22 18:13
Try to run the command manually and see what it prints

**Comment by amedvedjev** [comment] 2020-09-22 18:15
output:
```
Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
WARNING: META-INF/jdom-info.xml not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/services/org.xmlpull.v1.XmlPullParserFactory not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/INDEX.LIST not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/io.netty.versions.properties not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
```

**Comment by mykola-mokhnach** [comment] 2020-09-22 18:17
This looks good, but the tool still returns code 1, which means an error. Could be a bug in Android SDK

**Comment by amedvedjev** [comment] 2020-09-22 18:18
bug that does not reproduce in appium 1.18.1 ?

**Comment by mykola-mokhnach** [comment] 2020-09-22 18:20
This is just an assumption. Let us know if you have better ideas.

> manual run returns correct result per your comment

did you check the actual exit code?

**Comment by amedvedjev** [comment] 2020-09-22 18:28
how to check exit code pls with macOS console?

**Comment by amedvedjev** [comment] 2020-09-22 18:29
```
qa's Mac:~ qa$ /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.12.4.apk'. Original error: Command '/Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java -Xmx1024M -Xss1m -jar /Users/qa/Library/Android/sdk/build-tools/29.0.2/lib/apksigner.jar verify --print-certs /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.12.4.apk
-bash: /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.12.4.apk. Original error: Command /Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java: No such file or directory
qa's Mac:~ qa$ echo exit code: $?
exit code: 127
```

**Comment by amedvedjev** [comment] 2020-09-23 05:40
what a shame.... tried everything... but simple mac restart solved everything....

**Comment by amedvedjev** [comment] 2020-09-23 10:38
it was found out that issue re-appears after not graceful appium close. quite was not done. looking for workaround... @mykola-mokhnach please suggest anything look into

**Comment by mykola-mokhnach** [comment] 2020-09-23 16:45
Duplicate of https://github.com/appium/appium/issues/14724

Try the solution proposed to @sshock 
I don't know what else could be done there from Appium side based on the given data

**Comment by amedvedjev** [comment] 2020-09-23 19:03
@mykola-mokhnach i use "skipServerInstallation" with all tests accept very first one when we update app version. thanks anyway. will continue search for other solutions. strange that issue did not happen for 2y and suddenly started.

**Comment by mykola-mokhnach** [comment] 2020-09-23 19:07
Previously we were falling back to our own verifier tool written in java. Although the tool got pretty outdated and nobody was maintaining it, so we decided to solely use apksigner script from Android SDK, since it's maintained by Google and is recommended officially to manage APK signing. Although, it looks like apksigner is not ideal :(

**Comment by sshock** [comment] 2020-09-24 03:15
I still haven't gotten past this yet; in my case appium works fine for several days then seemingly out of nowhere starts failing on this.  I would like to get it working without having to do `skipServerInstallation` if I can.

Just a couple days ago I upgraded half my servers to appium 1.18.2, so I'm going to let that run for a week or two and see how it goes...

**Comment by amedvedjev** [comment] 2020-09-24 07:50
@mykola-mokhnach for me it looks like more problem in appium server. when "node" process continues occupy port after broken job and REST service not create. After close "node" forcibly issue gone (for some time :-) at least).

**Comment by sshock** [comment] 2020-09-24 14:52
Hmm, that is really confusing.  I don't understand how failing to start the REST interface would translate into failing to execute `java -jar apksigner.jar`.  Also, why would appium try to set up the REST interface again if it's already been up for days?

**Comment by zastress** [comment] 2020-09-25 09:35
saw this problem before. Go to your apps list on your Android and uninstall Appium Settings, com.apple.uiautomator2-server and com.apple.uiautomator2-client and then relaunch the test. Should be fine.

**Comment by amedvedjev** [comment] 2020-09-25 10:11
@zastress fullReset does the same! First step remove all from phone. But problem still producing.

PS after node update problem was not catched. Maybe not lucky yet....

**Comment by mykola-mokhnach** [comment] 2020-09-29 10:53
Closed as third party issue. Unfortunately there is nothing much to do there for us based on the provided information

**Closed by mykola-mokhnach** 2020-09-29 10:53 UTC
Labels: Android, NeedsInfo, ThirdParty

**Comment by gauthierbuttez** [comment] 2021-02-08 21:13
Hi, any update regarding this issue?

**Comment by saifsms91** [comment] 2021-02-10 11:22
Hi, any temporary fix to avoid this error?

**Comment by manodipmachinesense** [comment] 2021-04-08 11:28
Hi, any update on this issue ? I am also facing same...

**Comment by manodipmachinesense** [comment] 2021-04-08 13:46
Any kind of help appreciated....

**Comment by manodipmachinesense** [comment] 2021-04-12 05:13
Latest version has some issue, So I have downgraded the version now its working...

**Comment by Rivsinghal12** [comment] 2021-06-12 05:01
same issue , i am still facing

**Comment by Disturbed-Rover** [comment] 2021-09-13 10:11
Is there any update how to fix this?

**Comment by sshock** [comment] 2021-09-14 04:24
@Rivsinghal12 @Disturbed-Rover Here is how I worked around the problem: https://github.com/appium/appium/issues/14724#issuecomment-877395758

**Comment by sikku123344** [comment] 2022-09-08 06:12
> Is there any update how to fix this?

I think the apisigner.exe file is missing in the platform-tools folder
You can add the apisigner.exe file inside the platform-tools folder and run 
You can find the apisigner file [https://drive.google.com/file/d/17Tw_EvXMknIudU7PurQfziSfL1ygrXEd/view?usp=sharing](here)
It works for me I hope it works for you as well 

Windows 10 
Devicename :RealmeC21
Android version :11
Api level :30

**Comment by sikku123344** [comment] 2022-09-08 06:17
> ## The problem
> Error appears right on start driver with full reset options. Problem dit not happen with Appium 1.18.1 version.
> 
> ## Environment
> * Appium version (or git revision) that exhibits the issue: 1.19.0-beta.0
> * Mobile platform/version under test: Android
> * Real device or emulator/simulator: real device with android 10
> 
> ## Details
> Tried 2 build tools (30.0.2 + 29.0.2) both same result:
> 
> ```
> An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.12.4.apk'. Original error: Command '/Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java -Xmx1024M -Xss1m -jar /Users/qa/Library/Android/sdk/build-tools/30.0.2/lib/apksigner.jar verify --print-certs /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.12.4.apk' exited with code 1
> 
> An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.12.4.apk'. Original error: Command '/Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java -Xmx1024M -Xss1m -jar /Users/qa/Library/Android/sdk/build-tools/29.0.2/lib/apksigner.jar verify --print-certs /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.12.4.apk' exited with code 1
> ```

I think the apisigner.exe file is missing in the platform-tools
You can add the apisigner.exe file inside the platform-tools folder and run 
You can find the apisigner file [here](https://drive.google.com/file/d/17Tw_EvXMknIudU7PurQfziSfL1ygrXEd/view?usp=sharing)

Windows 10
Device: Realme C21
Android version: 11
API Level: 30.

It works for me I hope it works for you as well 

Thank you.

**Comment by DanilloVidal** [comment] 2023-09-14 17:40
im have same issue, update appium last version, update all SKD tools, Update java sdk to 20.0....


{
  "platformName": "android",
  "appium:platformVersion": "12",
  "appium:deviceName": "emulator-5554",
  "appium:automationName": "UiAutomator2",
  "appium:skipServerInstallation ": true
}

 at AndroidUiautomator2Driver.createSession (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:229:7)
[W3C]     at AppiumDriver.createSession (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/lib/appium.js:387:35)
[HTTP] <-- POST /wd/hub/session 500 1761 ms - 1071



Failed to create session. An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of '/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.27.0.apk'. Original error: spawn Unknown system error -86

Any help?

**Comment by biel164ainha-art** [comment] 2026-07-05 11:13
Subject: 1.2.840.113549.1.9.1=#1613616e64726f696440616e64726f69642e636f6d,CN=Android,OU=Android,O=Android,L=Mountain View,ST=California,C=US
Issuer: 1.2.840.113549.1.9.1=#1613616e64726f696440616e64726f69642e636f6d,CN=Android,OU=Android,O=Android,L=Mountain View,ST=California,C=US
Issued Date: Thu Feb 28 22:33:46 GMT-03:00 2008
Expiry Date: Mon Jul 16 22:33:46 GMT-03:00 2035
Algorithm: SHA1withRSA, Type: X.509, Version: 3
Serial Number: 936eacbe07f201df

Checksums
MD5: e89b158e4bcf988ebd09eb83f5378e87
SHA1: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
SHA-256: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc

Public Key
MIIBIDANBgkqhkiG9w0BAQEFAAOCAQ0AMIIBCAKCAQEA1pMZBN7GCySx7cdi4NnYJT4+zWzrHeL/Boyo6LyozWvTeG6nCqds5g67D5k1Wf/ZPnepQ+foPUtkuOT+otPmVvHiZ6gbv7IwtXjCBEO+THIYuEb1IRWG8DihTonCvjh/jr7Pj8rD2h7jMMnqk9Cnw9xK81AiDVAIBzLggJcX7moFM1nmppTsLLPyhKCkZsh6lNg7MQk6ZzcuL2QSwG5tQvFYGN/+A4HMDNRE2mzdw7gkWBlIAbMlZBNPv96YySh3SNv1Z2pUDYFUyLvKB7niR1UzEcRrmvdv3uzMjmnnyKLQjngmIJQ/mXJ9PAT+cpkdmd+brjigshd/ox1bav7pHwIBAw==
