### ISSUE TITLE
WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: Cannot launch simulated executable: no file found at /Users/rahulv/Library/Developer/Xcode/DerivedData/WebDriverAgent-folfazwwukpzfkegdblpnfuwlvfn/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app))

### ISSUE THREAD

**Issue by rahulv-tech** [appium/appium#14188] opened 2020-04-16 09:30 UTC
## The problem

WebDriverAgentRunner-Runner.app encountered an error . On Appium, logs keep running..
App got install on simulator. WebDriver is not working...

I am new to Appium. Not able to find any solution for error. Please help

## Environment

* Appium version (or git revision) that exhibits the issue:1.14.0
* Desktop OS/version used to run Appium: macOS Catalina 10.15.4
* Mobile platform/version under test:IOS
* Real device or emulator/simulator:Simulator
* Device iPhone 6
*OS 12.4

## Details

WebDriverAgentRunner-Runner.app encountered an error . On Appium, logs keep running.

## Link to Appium logs

https://gist.github.com/rahulv-tech/2cfc9238c5c8a93294c9686c70d7bd73

## Code To Reproduce Issue [ Good To Have ]

public class Base {

	public static void main(String[] args) throws MalformedURLException {
		// TODO Auto-generated method stub
		
		
		
		DesiredCapabilities cap=new DesiredCapabilities();
		
		cap.setCapability("deviceName", "iPhone 6");
		cap.setCapability("platformName", "IOS");
		cap.setCapability("platformVersion", "12.4");
		cap.setCapability(MobileCapabilityType.UDID, "9CCD8709-BC38-419B-AD21-95D5995B8F5F");
		cap.setCapability("automationName", AutomationName.IOS_XCUI_TEST);
		
		
		cap.setCapability("app","/Users/rahulv/Library/Developer/Xcode/DerivedData/UICatalog-bwvhendgzwirxucdbzcqpricmimp/Build/Products/Debug-iphonesimulator/UICatalog.app");
		
		
		IOSDriver<MobileElement> d = new IOSDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), cap);
		
		d.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
		
		
	}

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use

**Comment by mykola-mokhnach** [comment] 2020-04-16 10:02
Duplicate of https://github.com/appium/appium/issues/14102

**Closed by mykola-mokhnach** 2020-04-16 10:02 UTC
