### ISSUE TITLE
Test run fails out on Appium Settings app installation when running on device with settings app already installed

### ISSUE THREAD

**Issue by jraczak** [appium/appium#6789] opened 2016-08-30 18:45 UTC
## The problem

Test run fails when Appium attempts to install/reinstall Appium Settings app.  

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3
* Desktop OS/version used to run Appium: OSX 10.10.5
* Node.js version (unless using Appium.app|exe): Appium.app
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device (LG Nexus 5X)
* Appium CLI or Appium.app|exe: Appium.app

## Details

Test run fails during installation of Appium Settings app when running on a device that already has settings app installed.

## Link to Appium logs

https://gist.github.com/jraczak/30011224c91b32057eebf5b1db4b1d4f

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by jraczak** [comment] 2016-08-30 19:03
Same symptom occurs for the Unlock helper app.

**Comment by jraczak** [comment] 2016-08-30 19:31
This same error causes test run failure at the _end_ of a test run, after starting successfully by manually removing settings and unlock apps.

**Comment by mykola-mokhnach** [comment] 2016-08-30 20:48
Duplicate of https://github.com/appium/appium/issues/6665

**Comment by SrinivasanTarget** [comment] 2016-08-31 06:08
@triager please close

**Closed by SrinivasanTarget** 2016-08-31 06:08 UTC
Labels: NeedsTriage
