### ISSUE TITLE
Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1

### ISSUE THREAD

**Issue by rogermorgado** [appium/appium#8060] opened 2017-03-20 09:39 UTC
Hi Guys

I'm struggling with getting the new Appium desktop GUI to work for iOS 10. I've installed all dependencies as per: https://github.com/appium/appium-xcuitest-driver

Seems like a permissions issue but not sure how to fix it. Here's the log:

[HTTP] <-- POST /wd/hub/session 500 128792 ms - 178 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/roger/Downloads/CityPair_Beta.app","automationName":"XCUITest","deviceName":"iPhone 7","noReset":true,"platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/roger/Downloads/CityPair_Beta.app","automationName":"XCUITest","deviceName":"iPhone 7","noReset":true,"platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1490002411217 (11:33:31 GMT+0200 (SAST))
[Appium] Creating new XCUITestDriver (v2.20.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/roger/Downloads/CityPair_Beta.app'
[Appium]   automationName: 'XCUITest'
[Appium]   deviceName: 'iPhone 7'
[Appium]   noReset: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.3'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.20.0
[BaseDriver] Session created with session id: b2ceddc3-7c68-4154-abe1-32b6e2bb3154
[XCUITest] Xcode version set to '8.3' (tools v8.2.0.0.1.1480973914)
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1490002417239 (11:33:37 GMT+0200 (SAST))
[iOSSim] Constructing iOS simulator for Xcode version 8.3 with udid '4539C402-E620-4A58-B0D0-FEF6D2746DE8'
[XCUITest] Determining device to run tests on: udid: '4539C402-E620-4A58-B0D0-FEF6D2746DE8', real device: false
[BaseDriver] Using local app '/Users/roger/Downloads/CityPair_Beta.app'
[BaseDriver] Event 'appConfigured' logged at 1490002419298 (11:33:39 GMT+0200 (SAST))
[XCUITest] Checking whether app '/Users/roger/Downloads/CityPair_Beta.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/Users/roger/Downloads/CityPair_Beta.app': 'com.travelstart.citypair-beta'
[XCUITest] Setting 'connectHardwareKeyboard' Simulator option to 'on'
[BaseDriver] Event 'resetStarted' logged at 1490002419308 (11:33:39 GMT+0200 (SAST))
[XCUITest] Reset: noReset is on. Leaving simulator as is
[BaseDriver] Event 'resetComplete' logged at 1490002419309 (11:33:39 GMT+0200 (SAST))
[iOSLog] Starting iOS 10.3 simulator log capture
[iOSLog] System log path: /Users/roger/Library/Logs/CoreSimulator/4539C402-E620-4A58-B0D0-FEF6D2746DE8/system.log
[BaseDriver] Event 'logCaptureStarted' logged at 1490002419584 (11:33:39 GMT+0200 (SAST))
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid '4539C402-E620-4A58-B0D0-FEF6D2746DE8' already booted
[BaseDriver] Event 'simStarted' logged at 1490002419824 (11:33:39 GMT+0200 (SAST))
[XCUITest] App 'com.travelstart.citypair-beta' is already installed. No need to reinstall.
[BaseDriver] Event 'appInstalled' logged at 1490002420018 (11:33:40 GMT+0200 (SAST))
[BaseDriver] Event 'wdaStartAttempted' logged at 1490002420024 (11:33:40 GMT+0200 (SAST))
[XCUITest] Using WDA path: '/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] *** Downloading peertalk.framework binary at "v1.0"
[XCUITest] *** Skipped installing peertalk.framework binary due to the error:
[XCUITest] 	"Failed to write to /private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “iOS” because the volume is read only." UserInfo={NSFilePath=/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7fd486d4b2a0 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}}"
[XCUITest] *** Checking out peertalk at "v1.0"
[XCUITest] Failed to check out repository into /private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/peertalk: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “peertalk” because the volume is read only." UserInfo={NSFilePath=/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/peertalk, NSUnderlyingError=0x7fd486eb6690 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}})
[BaseDriver] Event 'wdaStartFailed' logged at 1490002426137 (11:33:46 GMT+0200 (SAST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaStartAttempted' logged at 1490002437624 (11:33:57 GMT+0200 (SAST))
[XCUITest] Using WDA path: '/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] *** Downloading peertalk.framework binary at "v1.0"
[XCUITest] *** Skipped installing peertalk.framework binary due to the error:
[XCUITest] 	"Failed to write to /private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “iOS” because the volume is read only." UserInfo={NSFilePath=/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7f90a0d8cce0 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}}"
[XCUITest] *** Checking out peertalk at "v1.0"
[XCUITest] Failed to check out repository into /private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/peertalk: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “peertalk” because the volume is read only." UserInfo={NSFilePath=/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/peertalk, NSUnderlyingError=0x7f90a0d5a230 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}})
[BaseDriver] Event 'wdaStartFailed' logged at 1490002439058 (11:33:59 GMT+0200 (SAST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:368:15)
    at tryCatch (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:368:15)
    at tryCatch (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:368:15)
    at tryCatch (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/35/7x40ctyd0ddcc6pnfjry3ny00000gn/T/AppTranslocation/BCC0D34F-A1F7-4BDE-B860-FBDDA0BE5B55/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by mykola-mokhnach** [comment] 2017-03-20 10:41
Closed as duplicate of https://github.com/appium/appium/issues/8033

**Closed by mykola-mokhnach** 2017-03-20 10:41 UTC
Labels: NeedsTriage
