### ISSUE TITLE
iOS fails to hide_keyboard on appium-xcuitest-driver 3.35.1

### ISSUE THREAD

**Issue by tommeier** [appium/appium#15073] opened 2021-02-01 07:14 UTC
## The problem

Believe it is related to this PR: https://github.com/appium/WebDriverAgent/pull/453

It was working on appium-xcuitest-driver 3.34.0 but fails on 3.35.1

`driver.hide_keyboard` fails to hide keyboard with error:

```
Selenium::WebDriver::Error::ElementNotInteractableError: Error Domain=com.facebook.WebDriverAgent Code=1 "Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test." UserInfo={NSLocalizedDescription=Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test.}
from InvalidElementStateError: Error Domain=com.facebook.WebDriverAgent Code=1 "Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test." UserInfo={NSLocalizedDescription=Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test.}
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): 1.20.1
* Desktop OS/version used to run Appium: Mac Big Sur
* Node.js version (unless using Appium.app|exe): v15.3.0
* Npm or Yarn package manager: Yarn
* Mobile platform/version under test: iOS 14.1
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

  * https://gist.github.com/tommeier/d56e8e3dead664cf77317dcaf890ce31

## Code To Reproduce Issue [ Good To Have ]

`driver.hide_keyboard`

**Comment by mykola-mokhnach** [comment] 2021-02-01 08:13
The method is now made more strict. This means if the iOS keyboard does not have a dedicated button, which closes it, then the downstream logic fails the method call as XCTest API does not provide anything else to close it

**Comment by mykola-mokhnach** [comment] 2021-02-01 08:15
Also, on Simulators the keyboard is usually disabled by default via "Connect Hardware Keyboard" option

**Comment by tommeier** [comment] 2021-02-01 09:06
hi @mykola-mokhnach 

> Also, on Simulators the keyboard is usually disabled by default via "Connect Hardware Keyboard" option

Usually yes, but we ensure we're testing animated flows with keyboard moving in and out continue to not break the setup.


> This means if the iOS keyboard does not have a dedicated button, which closes it, then the downstream logic fails the method call as XCTest API does not provide anything else to close it

Yes, these keyboard screens do not have a `Done` or `Finished` - the default used to be to click outside of the keyboard to clear - now its failing, so there is no way to hide a keyboard without a closing button?

**Comment by mykola-mokhnach** [comment] 2021-02-01 09:10
> Yes, these keyboard screens do not have a Done or Finished - the default used to be to click outside of the keyboard to clear - now its failing, so there is no way to hide a keyboard without a closing button?

Yes, there is no way to do that on iOS via APIs that Apple provides. Clicking outside of the keyboard is not safe if it is done on the server side, since it would select random coordinates for that. So there is no guarantee the click would be performed on a "safe" area. That is why it makes more sense if the client itself performs that action, because there it's known at which position the click should happen.

**Comment by tommeier** [comment] 2021-02-01 09:19
Thanks for the explanation 🙏  - I'll lock to 3.34.0 for now and look to run my own 'click anywhere' to hide.

**Closed** 2021-02-01 09:19 UTC
Labels: NeedsInfo, XCUITest

**Comment by kvinay729** [comment] 2021-05-22 13:24
@mykola-mokhnach So whats the workaround here, is it planned to be fixed? I upgraded to latest appium and its failing my tests.

**Comment by ncoma** [comment] 2021-12-20 16:27
> @mykola-mokhnach So whats the workaround here, is it planned to be fixed? I upgraded to latest appium and its failing my tests.

My workaround is to send '\n' at the end of the value I'm sending. No issues so far.

**Comment by vvelusamy1** [comment] 2021-12-21 01:38
"\n" worked for textfield if thats not in the login screen.

**Comment by diego-epicura** [comment] 2022-10-24 09:11
I don't know why people insists to close this issue while

driver.hideKeyboard()

DOES NOT WORK ON APPIUM WITH IOS.

**Comment by diego-epicura** [comment] 2022-10-24 09:19
> > @mykola-mokhnach So whats the workaround here, is it planned to be fixed? I upgraded to latest appium and its failing my tests.
> 
> My workaround is to send '\n' at the end of the value I'm sending. No issues so far.

this does not work if element is a Textarea.

**Comment by jlipps** [comment] 2022-10-24 17:19
the most robust and correct solution is to do whatever a user would do to hide the keyboard. what would a user to do hide the keyboard in that case? just do that.

**Comment by diego-epicura** [comment] 2022-10-25 06:49
Yeah I am testing on a simulator with iPhone8 for compatibility, so no keys to hide. I had to tap in a random point on the screen, which is the worst way to standardize a test. I still wonder why if there's a command related to an API on this framework, and this does not work, those issues are still being closed.

**Comment by jlipps** [comment] 2022-10-27 18:51
the hideKeyboard command is a best guess heuristic. the problem is there is no apple-provided way of reliably hiding the keyboard. that is why the other issues are closed. there's nothing to do about it.

the appropriate solution is for you to do what a user would do. if it's hard for a user to hide the keyboard, then it will be hard for you to do in the test as well. like if it takes special human knowledge to hide the keyboard, something like "tap outside the keyboard but make sure it's not on any other element", then, yeah, that's a burden you're putting on the user as well as yourself as a tester.

it might help to complain to apple about the lack of an api for hiding the keyboard via xcuitest.

**Comment by JerryAlbert** [comment] 2023-01-20 14:49
Any solution for this issue so far?

**Comment by dearirshad2** [comment] 2023-03-03 16:44
Im doing this to hide the keyboard on IOS 

```
List<MobileElement> allTxt = MobileDriverManagerIOS.getDriver().findElementsByXPath("//XCUIElementTypeStaticText");
MobileElement element      = allTxt.get(allTxt.size()-1);
MobileActionsIOS.click(element);
```

This will get list of all TextViews and then click the last element to avoid any scroll issues.

**Comment by mitsukuri** [comment] 2024-01-29 20:49
> "\n" worked for textfield if thats not in the login screen.

Finally a viable workaround, thank you!

**Comment by baselalali** [comment] 2024-02-07 14:08
```
 @iOSXCUITFindBy(accessibility = "Return")
    private WebElement returnKey;

IOSDriver iosDriver = DriverFactory.getIOSDriver(driver);
            if (iosDriver.isKeyboardShown()) {
                returnKey.click();
            }
        }
```
Works with mee
