### ISSUE TITLE
Unable launch app - Error : Building for iOS, but the linked framework 'CocoaAsyncSocket.framework' was built for tvOS + tvOS Simulator when running real device

### ISSUE THREAD

**Issue by ivantay2003** [appium/appium#14102] opened 2020-03-25 07:13 UTC
## The problem

I am not able to launch app in OS X / real device . This used to work till I update my xcode today.  There are no changes in the script . 

## Environment
Appium 1.15.1
Mac OS X Catalina 10.15.4 
XCode 11.4 (11E146)

* Appium version (or git revision) that exhibits the issue: Appium 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): Appium 1.15.1
* Desktop OS/version used to run Appium: Mac OS X Catalina 10.15.4 
* Node.js version (unless using Appium.app|exe):  12.11.1
* Npm or Yarn package manager:
* Mobile platform/version under test: OS X 12.4.5
* Real device or emulator/simulator: Real Device / iPhone 6
* Appium CLI or Appium.app|exe: Both - CLI and Appium app

## Details
Launch Appium Desktop
Go to App Inspector
Start Session (I am using Netflix as an example) in real device from Appium Desktop

If necessary, describe the problem you have been experiencing in more detail.
This used to work before I update XCode today.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
https://gist.github.com/ivantay2003/f1dc3362e0fc84bd1f6ce69392a84133

Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
1. Launch Appium Desktop app
2. Go to Inspector
3. Start session

Error (see log)
This used to work before i update my xcode. It is repro on both the app and cli.

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment] 2020-03-25 08:32
How about clean `/Users/ivantay/Library/Developer/Xcode/DerivedData` and `appium-webdriveragent/Carthage` once? It helps to avoid xcodebuild cache etc after upgrading Xcode versions.
Perhaps, it is easy to re-install appium and clean `DerivedData`.

**Comment by ivantay2003** [comment] 2020-03-25 08:40
I have cleaned the DerivedData folder, delete the appium-webdriveragent/Carthage and reboot the device. However, the error are the same.

**Comment by ivantay2003** [comment] 2020-03-25 08:42
The errors from the WebDriverAgent log is 


Showing Recent Messages
WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))

**Comment by KazuCocoa** [comment] 2020-03-25 09:12
I confirmed. Could you update to the latest appium version?
I reproduced the build error with 1.15.1, but it was resolved in the latest one.

**Comment by ivantay2003** [comment] 2020-03-25 12:08
Thanks KazuCocoa, 

I tried the 1.17.0 desktop app , it say 
"Appium" can't be opened because Apple cannot check it for malicious software.

**Comment by ivantay2003** [comment] 2020-03-25 12:20
Acknowledge, I have tested it , it is working (though I found a bug in 1.17 desktop and will file it separately in the app inspector)



Thanks.

**Closed** 2020-03-25 12:55 UTC
Labels: NotABug

**Comment by olubukolaaborode** [comment] 2020-04-09 12:14
@ivantay2003 May I ask how you got the issue fixed pls? I am having same issue. My appium desktop version is 1.15.1 while the appium version installed via npm command is 1.17.0.

**Comment by captainTao** [comment] 2020-04-11 08:56
I have the same issue:
macos:   Catalina - 10.15.2
Appium desktop: version 1.15.1
xcode: Version 11.4 (11E146)

**Comment by Whiperdief** [comment] 2020-04-27 08:39
Same issue. None of the above helps. (iOS)
Reinstalled appium-desktop.
Reinstalled appium CLI.
Reinstalled node.
Removed everything appium/node related.
Run appium-doctor, no errors or warning.

I did find a "solution" to my problem.

When I execute JAVA code testing following folder is generated:
... Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu

When I execute appium-desktop following folder is generated:
... Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz

Both folders will be random generated, just keep track which Appium generates which folder.
The CLI appium generated folder has a folder named 'build'. Copy paste that into the folder generated by appium-dekstop. And it works for me. The folder generated by appium-desktop is missing the webdriveragent. The 'build' folder generated by CLI has a working webdriver agent.
I hope this helps some people out.

**Comment by KazuCocoa** [comment] 2020-04-30 05:37
Xcode (xcodebuild) manages `DerivedData`, so Appium does not control it by default, so `derivedDataPath` capability helps to specify it

**Comment by fousiak** [comment] 2020-04-30 16:52
This worked for me. Thanks

**Comment by sfarbota** [comment] 2020-05-10 08:01
@Whiperdief - Yes, that did the trick! Thank you!! Perhaps I'm missing something, but this seems like a pretty big issue considering the latest version of Appium Desktop doesn't seem to work on macOS without this convoluted workaround.

**Comment by MarcSteven** [comment] 2020-05-14 02:52
But the issue is still existing now, cannot be solved.
I used appium1.15.1 and Xcode11.4.1, run simulator not real device, but it's still have this issue

**Comment by KazuCocoa** [comment] 2020-05-14 02:58
Did you try out newer Appium versions? https://github.com/appium/appium-desktop#connect-to-local-appium-server

I confirmed Xcode 11.4 issue on Appium 1.15.1 https://github.com/appium/appium/issues/14102#issuecomment-603728765 (We fixed some issues in newer Appium versions for newer Xcode versions, btw)

https://github.com/appium/appium/issues/14102#issuecomment-619824759 helps when Xcode handles DerivedData for Appium Desktop and Appium.

**Comment by MarcSteven** [comment] 2020-05-14 03:09
@KazuCocoa  I am downloading the 1.17.0 and then retry, hope it can be solved.

Hope the document has some complete details to describe something.

**Comment by KazuCocoa** [comment] 2020-05-14 03:27
We're working voluntarily. So, the GitHub release is very helpful to use with free (and low maintenance cost).
I hope GitHub will improve the download speed in various regions. (Btw, we cannot push AppiumDesktop via AppStore since Appium itself has hacky code for iOS)

**Comment by BlueMona** [comment] 2020-05-14 20:23
Hello, I attempted the instructions at https://github.com/appium/appium-desktop#connect-to-local-appium-server (using server version 1.17.1) and I still encounter the issue. I have also looked at https://stackoverflow.com/questions/60626534/how-to-build-appium-desktop-from-source-code and the commands to build and launch do not all work (are not present). When will there be a download available for the latest versions? My desktop version (1.15.1) can not find updates.

**Comment by ivarbanovv** [comment] 2020-05-18 09:22
I hit the same issue `(WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory))))` with Appium desktop v1.15.1 on MacOs 10.15.4 with Xcode 11.4.1.
it works well with Appium CLI tho.

**Comment by ivantay2003** [comment] 2020-05-18 10:06
I fixed this issue by reinstall the latest appium. I delete off the carthage and reinstall it. 
I document the steps of setting up here:

https://medium.com/@ivantay2003/setting-up-appium-in-os-x-ecd9e7108a9c

**Comment by mykola-mokhnach** [comment] 2020-05-18 10:24
@ivantay2003 Thanks for the link.

Yes, unfortunately the official docs are maintained badly, but that just because no-one does that. We'd very appreciate it if you could contribute there.

**Comment by Niv-K** [comment] 2020-05-27 18:30
I followed steps given by you but still having same issue
/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj Building for iOS, but the linked framework 'CocoaAsyncSocket.framework' was built for tvOS + tvOS Simulator.
Can you please help.
 ./Scripts/bootstrap.sh -d
Fetching dependencies
*** Checking out RoutingHTTPServer at "v1.0.2"
*** Checking out YYCache at "1.1.0"
*** Checking out CocoaAsyncSocket at "7.6.3"
*** xcodebuild output can be found in /var/folders/c0/8bv3_35539v3b28n9hrh6wrh0000gn/T/carthage-xcodebuild.Tnuyjg.log
*** Downloading CocoaAsyncSocket.framework binary at "Version 7.6.3"
*** Building scheme "RoutingHTTPServer tvOS" in RoutingHTTPServer.xcodeproj
*** Building scheme "RoutingHTTPServer iOS" in RoutingHTTPServer.xcodeproj
*** Building scheme "YYCache tvOS" in YYCache.xcodeproj
*** Building scheme "YYCache iOS" in YYCache.xcodeproj

**Comment by johnendres** [comment] 2020-05-28 19:33
Same issue for me despite all the troubleshooting steps outlined above.  Given the state of the "documentation", the fact that the Appium process SIGTERMs if you fully install according to instructions and Appium-doctor (Notable IDB), and non-working examples among other things, should we consider this a dead project?

**Comment by mykola-mokhnach** [comment] 2020-05-28 19:45
> Given the state of the "documentation", the fact that the Appium process SIGTERMs if you fully install according to instructions and Appium-doctor (Notable IDB), and non-working examples among other things, should we consider this a dead project?

Considering one is using Appium version, which has been released 8 months ago and is two minor releases behind the master - yes, it is dead.

The documentation for sure could be in a better state. Although, there are nobody who would like to contribute there. Sad but true.

**Comment by johnendres** [comment] 2020-05-28 20:04
You sir are a genius, and I thank you!  My Appium version didn't get updated somehow.  Shows how things get missed when you are frustrated because of silent failures and other things.

I miss the old days where something wasn't considered done until the documentation was printed.

**Comment by suaadBatis** [comment] 2020-05-31 16:53
I fixed this issue ..
 **Environment**
Appium Version 1.17.1 (1.15.1.20191013.2)
MacOS Catakina v 10.15.4 (19E287)
-xcode Version 11.4.1 (11E503a)
**The solution**  
1- reinstall the appium  >> take care to run   brew insatll  carthage  + brew link carthage 
2- ~/ appium-webdriveragent >>
 run   mkdir -p Resources/WebDriverAgent.bundle
3- run ./Scripts/bootstrap.sh -d
4- add this to your capiblity >desiredCapabilities.setCapability ("showXcodeLog", true);>> very useful

**Comment by BoazWarshawsky** [comment] 2020-06-27 20:06
Does the fix available in Appium 1.16.0 as well?

**Comment by KazuCocoa** [comment] 2020-06-28 04:02
No, we basically do not provide any patches for older versions.

**Comment by jyotiprk991** [comment] 2020-09-08 07:24
I was facing the same issue, upgraded to the latest Appium 1.18.0. Here I am able to Build.
But I am not able to access Xpath in this version, which results in a lot of failure in my framework.
Will there be any fix for that issue?

**Comment by M-Smits** [comment] 2020-09-15 11:53
> I was facing the same issue, upgraded to the latest Appium 1.18.0. Here I am able to Build.
> But I am not able to access Xpath in this version, which results in a lot of failure in my framework.
> Will there be any fix for that issue?

Yes. 
https://github.com/appium/appium/releases/tag/v1.18.1

**Comment by plomte** [comment] 2020-12-16 05:37
Hi,
Iam having the same issue getting the error

**Comment by nikoskyr** [comment] 2020-12-16 09:58
Same problem here. 
After upgrading to Xcode 12.3, these error logs appeared again. I tried the workaround but it didn't solve the issue.
Now, I am trying to downgrade the Xcode version and run again the WebDriver to see if it helps.

**Comment by irimiecernea** [comment] 2020-12-16 12:30
Same problem here with XCode 12.3 and Appium 1.19.1 along with macOS Catalina 10.15.7.

When running `xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id='xxxx' test`, where xxxx is my phone's UDID , I'm getting:

`note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
error: Building for iOS, but the linked and embedded framework 'YYCache.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
error: Building for iOS, but the linked and embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
error: Building for iOS, but the embedded framework 'YYCache.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
error: Building for iOS, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')


Test session results, code coverage, and logs:
	/Users/whoami/Library/Developer/Xcode/DerivedData/WebDriverAgent-gpoggdlltxcpsphismwukxhyeumw/Logs/Test/Test-WebDriverAgentRunner-2020.12.16_14-21-07-+0200.xcresult

Testing failed:
	Building for iOS, but the linked and embedded framework 'YYCache.framework' was built for iOS + iOS Simulator.
	Building for iOS, but the linked and embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator.
	Building for iOS, but the embedded framework 'YYCache.framework' was built for iOS + iOS Simulator.
	Building for iOS, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator.
	Testing cancelled because the build failed.

** TEST FAILED **`

**Comment by irimiecernea** [comment] 2020-12-16 13:38
I solved the problem by downgrading to XCode 12.2 until this is fixed.

**Comment by KazuCocoa** [comment] 2020-12-16 17:45
For Xcode 12.3 persons https://github.com/appium/appium/issues/14952

**Comment by hex0cter** [comment] 2021-01-11 21:54
Appium 1.20 worked for me. For Appium desktop I had to upgrade to 1.20.0-beta.0 (https://github.com/appium/appium-desktop/releases)

**Comment by GRyabkin** [comment] 2021-02-10 10:40
Setting `WebDriverAgent -> Build Settings -> Build Options -> Validate Workspace = Yes` for each target of the workspace

For **Desktop Appium** the project located here:
`(/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/webdriver...)`

For **console appium** the project located here:
`/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent`

**Comment by MarcSteven** [comment] 2021-02-13 02:03
Yeah it should be ok, it works well !

**Comment by Djkmichaela** [comment] 2021-02-13 14:14
@M-Smits can you make a video of your fix because i dont get what you meant

**Comment by dovban-ds** [comment] 2024-07-08 11:31
I was looking for a solution to the problem, and the firewall suddenly reported that it was blocking the connection and I just needed to give it permission
