### ISSUE TITLE
Appium: [ADB] Error: Error attempting to start URI. Original error: Error: Error executing adbExec.

### ISSUE THREAD

**Issue by harikapanyala** [appium/appium#6601] opened 2016-06-19 10:58 UTC
[AppiumLogFile.txt](https://github.com/appium/appium/files/323138/AppiumLogFile.txt)
When i execute Appium test using Selenium Grid, it throws an error after opening the URL. It opens the same URL twice and then it throws error. Below is the Appium error. Attached complete log file. 

```
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 7 ms - 83
[AppiumLogFile.txt](https://github.com/appium/appium/files/322256/AppiumLogFile.txt)

[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[ADB] Error: Error attempting to start URI. Original error: Error: Error executing adbExec. Original error: Command ''F:\\APPIUM\\Android SDK\\platform-tools\\adb.exe' -P 5037 -s WKZLMJLB7L8TR8SW shel
t.action.VIEW -d http://www.google.com com.android.chrome' timed out after 20000ms{"stdout":"Starting: Intent { act=android.intent.action.VIEW dat=http://www.google.com pkg=com.android.chrome }\r\r\n"
```

BUT when i try to run the same test normally without grid [Both with Appium UI and launching appium through command line as wel ], it is getting executed without any issues.

**Below is the Json file using :** 

```
{
  "capabilities":
    [
      {
        "browserName": "chrome",
        "version":"4.4.2",
        "maxInstances": 1,
        "platform":"Android",
        "deviceName":"HJIUYLMJL34eR8SW"
      }
    ],
  "configuration":
  {
    "cleanUpCycle":5000,
    "timeout":10800,
    "url":"http://127.0.0.1:4723/wd/hub",
    "host": "127.0.0.1",
    "port": 4723,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": "10.0.0.4"
  }
}

```

**Executing below command to start Appium** 
`appium --nodeconfig path_to_config_file`

**Below is the test script:**

```
public class GoogleExample{
    public WebDriver driver;
    String AppURL = "http://www.google.com";

    @BeforeTest
    @Parameters({"portNumber","deviceName"})
    public void setup(String portNumber, String deviceName) throws MalformedURLException {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("browsername", "chrome");
        capabilities.setCapability("deviceName", deviceName);
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("appPackage", "com.android.chrome");
        capabilities.setCapability("appActivity", "com.google.android.apps.chrome.Main");

        driver = new AndroidDriver<>(new URL("http://127.0.0.1:"+portNumber+"/wd/hub"), capabilities);
        driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
    }

    @Test
    public void testGoogleTitleAppium() {
        driver.get(AppURL);
        String homePageTitle = driver.getTitle();
        Assert.assertEquals(homePageTitle, "Google");
       }

    public void tearDown() {
        driver.quit();
    }

}
```

**Below is testng.xml file which im using to run my tests**

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Main Test Suite" verbose="1">
    <test name="Device Test 1">
    <parameter name="portNumber" value="4723"/>
     <parameter name="deviceName" value="HJIUYLMJL34eR8SW"/>
        <classes>
        <class name="com.app.googleExample"/>
        </classes>
    </test>
</suite>
```

**Environment details :** 
Appium Version 1.4.16.1
Android device : 4.4.2
Windows 8
Java 1.7
Let me know if im missing any thing here.

Thanks

**Comment by ChaitanyaQA** [comment] 2016-06-20 07:53
@harikapanyala 
Could you please attach complete log file...

**Comment by harikapanyala** [comment] 2016-06-20 10:01
@ChaitanyaQA 
Attached complete log file. Please check.

**Comment by ChaitanyaQA** [comment] 2016-07-05 10:07
@harikapanyala 
Add parameters "parallel="tests"  thread-count="5" " in your suite tag under testng.xml

**Comment by harikapanyala** [comment] 2016-07-05 17:51
@ChaitanyaQA 
Actually im not trying to execute tests in parallel.

But even after applying parameters, I'm still facing the same issue. 

I also tried with Appium 1.5.3.

**Comment by tiagoshibata** [comment] 2016-07-30 15:04
Hi,

I can confirm that it's broken on latest GIt Appium, tested on Windows 8 and 10. Appium is using some native function to convert paths and is rewriting Android paths as Windows-like absolute paths.

[This log](https://gist.github.com/tiagoshibata/040e6145250d9b36616977500c0ba4d0), for example, shows broken screenshot and pull commands:

```
...
[debug] [ADB] Running C:\adb\platform-tools\adb.exe with args: ["-P",5037,"-s","T099706ZXD","shell","/system/bin/rm","C:\\data\\local\\tmp\\screenshot.png;","/system/bin/screencap","-p","C:\\data\\local\\tmp\\screenshot.png"]
...
[debug] [ADB] Running C:\adb\platform-tools\adb.exe with args: ["-P",5037,"-s","T099706ZXD","pull","C:\\data\\local\\tmp\\screenshot.png","C:\\Users\\DEWOTT\\AppData\\Local\\Temp\\appium116619-5360-5w53za.abpjc680k9.png"]
```

@harikapanyala, where did you get your 1.4.16.1? I believe the one from the [downloads page](https://bitbucket.org/appium/appium.app/downloads/) worked for me.

**Comment by tiagoshibata** [comment] 2016-07-30 20:44
The problem seems to be [using the path module to build paths for Android, which has different behavior in Windows](https://nodejs.org/api/path.html#path_windows_vs_posix). Using `path.posix` for paths on the device should fix the issue, [eg. here](https://github.com/appium/appium-android-driver/blob/master/lib/commands/actions.js#L165).

I have a Windows machine at home and can get a PR done.

**Comment by ssynix** [comment] 2016-08-24 18:56
I tried running the adb command that Appium uses directly on a phone that experienced this problem. What I noticed is that the adb command works successfully if the chrome app is not already launched. However, it waits an unreasonably long amount of time if the browser is already open:

```bash
# First attempt
 >>> adb shell am start -W -a android.intent.action.VIEW -d http://www.google.com com.android.chrome
Starting: Intent { act=android.intent.action.VIEW dat=http://www.google.com/... pkg=com.android.chrome }
Status: ok
Activity: com.android.chrome/org.chromium.chrome.browser.ChromeTabbedActivity
ThisTime: 440
TotalTime: 572
WaitTime: 607
Complete

# Now chrome is already open and has loaded the page in a tab
>>> adb shell am start -W -a android.intent.action.VIEW -d http://www.google.com com.android.chrome
Starting: Intent { act=android.intent.action.VIEW dat=http://www.google.com/... pkg=com.android.chrome }
Status: ok
Activity: com.android.vending/com.google.android.finsky.activities.MainActivity
ThisTime: 735
TotalTime: 1191504
WaitTime: 13251
Complete

>>> adb shell am start -W -a android.intent.action.VIEW -d http://www.google.com com.android.chrome
Starting: Intent { act=android.intent.action.VIEW dat=http://www.google.com/... pkg=com.android.chrome }
Status: ok
Activity: com.chrome.beta/org.chromium.chrome.browser.ChromeTabbedActivity
ThisTime: 425
TotalTime: 2884024
WaitTime: 1179257
Complete
```

It seems that, for reasons that I have not yet discovered, Appium times out waiting for this command to finish, which results in the error mentioned above.

**Comment by ssynix** [comment] 2016-11-09 18:00
@jlipps @imurchie any ideas on how we can best work around this? I can still reliably reproduce this on an Android 6.0.1 phone, running Chrome 54.

**Comment by jlipps** [comment] 2016-11-09 19:37
@ssynix if you stop the activity before starting it again, does it help? we could have appium do that, maybe

**Comment by Ravi-ratnakaram** [comment] 2017-02-06 04:57
I am also facing the same issue while running the test on real device " adb -P 5037 -s d3baaeb0 shell am start -W -a android.intent.action.VIEW -d https://www.test.com/ com.android.chrome' timed out after 20000ms{"stdout":"Starting: Intent { act=android.intent.action.VIEW dat=https://www.test.com/... pkg=com.android.chrome }\r\n","stderr":"","code":null} . 

appium 4.1.2
Selenium : 2.53.1
androoid:6.0.1
chrome version: 55.0

Test opens the chrome browser and enters the provided url. But, fails before entering value to login form. I observed that chrome instance opened twice with provided url, not sure why it's invoked twice. 

Can someone please suggest me possible fix or workaround ? 

Thanks in advance..

**Comment by chanugithub** [comment] 2017-03-13 20:47
@Ravi-ratnakaram Hello ravi, are you able to resolve the issue. I am getting same error that you are getting. chrome is invoking multiple times for me and then throwing error

Please let me know how you you resolved the issue

**Comment by chanugithub** [comment] 2017-03-16 16:29
I fixed it by by providing the right chrome driver and setting in capabilities
cap.setCapability("chromedriverExecutable", "/usr/local/bin/chromedriver");

**Comment by jlipps** [comment] 2017-04-06 22:24
seems like using an updated chromedriver helps, closing this

**Closed by jlipps** 2017-04-06 22:24 UTC
Labels: NeedsTriage

**Comment by chanugithub** [comment] 2017-04-06 23:54
yes you can close this ...it got fixed by updated chrome driver and also placing the chrome driver in /usr/local/bin/
and then mentioning in same in script --------   cap.setCapability("chromedriverExecutable", "/usr/local/bin/chromedriver");

**Comment by vassassins** [comment] 2018-03-27 10:27
Thanks above steps help to solve same Issue.
