### ISSUE TITLE
Random "TypeError: _appiumSupport.logger.warn is not a function" on IOSSimulatorLog.killLogSubProcess

### ISSUE THREAD

**Issue by nacfe** [appium/appium#15383] opened 2021-05-17 09:14 UTC
## The problem

I have some test runs that open an iOS simulator, with Touch or Face ID turned on, and then run an entire test suite, but sometimes one random test gets this error when calling the endpoint to reset the app:

"TypeError: _appiumSupport.logger.warn is not a function"

After this all subsequent tests on the suite will fail with the same error. I have no idea why this is happening. Is this familiar to anyone?

## Environment

* Appium version: 1.20.2
* OS: macOS Big Sur 11.2.1
* Node.js version: 15.3.0
* Mobile platform/version under test: iOS 13.7, XCode 12.3
* Device: Simulator
* Appium CLI: Java client

## Link to Appium logs

https://gist.github.com/nacfe/95395a7ca8e1c08b0e202ac75821bd39

**Comment by mykola-mokhnach** [comment] 2021-05-17 09:40
Duplicate of https://github.com/appium/appium/issues/15229
Fixed since v1.21.0+

**Closed by mykola-mokhnach** 2021-05-17 09:40 UTC
