### ISSUE TITLE
SendKeys not working on XCUIElementTypePickerWheel for Dates

### ISSUE THREAD

**Issue by yotsubakoiwai** [appium/appium#10144] opened 2018-02-07 08:06 UTC
## The problem

I have an XCUIElementTypePickerWheel that allows me to select date, time, minutes, and AM/PM from the control. I can successfully use SendKeys() for the time, minutes and AM/PM but can't set for the date, where format e.g. Mon Apr 9

The "Today" stays as is and wheel won't move. I tried the driver.ExecuteScript("mobile: scroll") but it only scrolls up or down and to a certain position. It won't go to the value that you want.

And there's no way getting all the values listed on the Date pickerWheel, so you can loop.

## Environment

* Appium Desktop: 1.3.1 
* Appium Server: 1.7.2
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.3
* Node.js version (unless using Appium.app|exe): 8.9.4
* Mobile platform/version under test: iPhone 6s
* Real device or emulator/simulator: Simulator

## Example of the UI

[
![simulator screen shot - appiumtest-e130e201-bf55-4922-89d4-9e9f58c6b655 - 2018-02-07 at 13 32 57](https://user-images.githubusercontent.com/26672384/35904720-255f8a72-0c1f-11e8-83c1-3a8aa122e8e0.png)
](url)

## Link to Appium logs

[https://gist.github.com/yotsubakoiwai/1d5ce8a7baa077ec0651f605c2a428d6](url)

## Code To Reproduce Issue

`            

            //set time -- WORKS!!!
            driver.FindElementByXPath("//XCUIElementTypeApplication[@name='tableAndPicker']/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeDatePicker/XCUIElementTypeOther/XCUIElementTypePickerWheel[2]").SendKeys("2");

            //set minutes -- WORKS!!!
            driver.FindElementByXPath("//XCUIElementTypeApplication[@name='tableAndPicker']/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeDatePicker/XCUIElementTypeOther/XCUIElementTypePickerWheel[3]").SendKeys("59");

            //set AM or PM -- WORKS!!!
            driver.FindElementByXPath("//XCUIElementTypeApplication[@name='tableAndPicker']/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeDatePicker/XCUIElementTypeOther/XCUIElementTypePickerWheel[4]").SendKeys("PM");

`

But this piece of code is not working (for the date part)

`            //set date -- NOT WORKING!!!
            driver.FindElementByXPath("//XCUIElementTypeApplication[@name='tableAndPicker']/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeDatePicker/XCUIElementTypeOther/XCUIElementTypePickerWheel[1]").SendKeys("Mon, Apr 9");
`

**Comment by mykola-mokhnach** [comment] 2018-02-07 09:11
Duplicate of https://github.com/appium/appium/issues/6962

**Closed by mykola-mokhnach** 2018-02-07 09:11 UTC

**Comment by prat3ik** [comment] 2018-03-14 17:08
@yotsubakoiwai  We can only select next or previous date Using Appium(selectPickerWheelValue), read this:  https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md


> **mobile: selectPickerWheelValue**
> Performs selection of the next or previous picker wheel value. This might be useful if these values are populated dynamically, so you don't know which one to select or value selection does not work because of XCTest bug.
> 
> Supported arguments
> element: PickerWheel's internal element id (as hexadecimal hash string) to perform value selection on. The element must be of type XCUIElementTypePickerWheel. Mandatory parameter
> order: Either next to select the value next to the current one from the target picker wheel or previous to select the previous one. Mandatory parameter
> offset: The value in range [0.01, 0.5]. It defines how far from picker wheel's center the click should happen. The actual distance is culculated by multiplying this value to the actual picker wheel height. Too small offset value may not change the picker wheel value and too high value may cause the wheel to switch two or more values at once. Usually the optimal value is located in range [0.15, 0.3]. 0.2 by default
> Usage examples
> // Java
> JavascriptExecutor js = (JavascriptExecutor) driver;
> Map<String, Object> params = new HashMap<>();
> params.put("order", "next");
> params.put("offset", 0.15);
> params.put("element", ((RemoteWebElement) element).getId());
> js.executeScript("mobile: selectPickerWheelValue", params);
