### ISSUE TITLE
Feature: Support Huawei phones without google suite

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#15268] opened 2021-04-12 08:05 UTC
## The problem

Can't start session with Huawei_P40

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Real Huawei_P40

## Details

Driver fails to start.

## Link to Appium logs
https://gist.github.com/amedvedjev/7edd09a615cca5bf15d1b7e2c88e98ec

**Comment by mykola-mokhnach** [comment] 2021-04-12 09:39
Duplicate of https://github.com/appium/appium/issues/15239

**Closed by mykola-mokhnach** 2021-04-12 09:39 UTC

**Comment by amedvedjev** [comment] 2021-04-12 10:40
thanks @mykola-mokhnach ! beta works.
