### ISSUE TITLE
bug: Cannot access to the Elements of iOS 

### ISSUE THREAD

**Issue by akh-mr** [appium/appium#18673] opened 2023-05-22 11:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We try to update the react-navigation/native library from v4.4.2 to v6.0.13 for our application.
Then, we found that most of the elements for iOS are missing on the Appium Inspector.
We suspect too many nested view causes the unaccessible state.
As a result, we cannot detect the testId for these elements and our automation test does not work.
This issue is reproduced on both simulator and real device
It looks like the elements under “ScrollView”, “Flatlist” and “Sectionlist” are missing.

### Expected Behavior

All of the elements for iOS are shown on the Appium Inspector.

### Minimal Reproducible Example

We cannot provide our internal code.
But we found the source code that reproduce same issue.
Other enginner posted same issue to react-navigation team with sample source code 
https://github.com/react-navigation/react-navigation/issues/9132#issue-758513927

We compile this sample  code and verified to reproduce the issueon our side
Depnedencies package information is below

"dependencies": {
  "react": "17.0.2",
  "react-native": "0.68.2",
  "react-native-paper": "4.9.2",
  "react-native-screens": "^3.18.2",
  "@react-navigation/stack": "^6.3.4",
  "@react-navigation/native": "^6.0.13",
  "react-native-gesture-handler": "2.2.0",
  "@react-navigation/bottom-tabs": "*",
  "react-native-safe-area-context": "^4.4.1"
}

### Environment

- Operating system:
   Mac mini
    Mac OS- Monterey: 12.6.4
    Processor- Intel
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
     a)2.0.0-beta.67
     b) 1.22.3
     c) 1.21.0
  - Node.js version (output of `node --version`):
    v16.17.1
  - `npm` version (output of `npm --version`):
    8.15.0
  - Last `appium` version which did _not_ exhibit the problem:
- If running Appium Desktop, its version:
   1.22.3, 1.21.0
- Appium driver(s) and their version(s):
  xcuitest@4.29.2
- Appium plugin(s) and their version(s):
  NA
- Platform and version under test:
   iOS 16.4
   iOS 15.4
   iOS14.6, 14.4
- Real device or emulator/simulator:
   Both Real device/Simulator

### Futher Information

We also put our query in Appium web site as below.
https://discuss.appium.io/t/cannot-access-to-the-elements-of-ios-on-appium/39097

Same issue was reported on react-navigation
https://github.com/react-navigation/react-navigation/issues/9132#issue-758513927

**Comment by mykola-mokhnach** [comment] 2023-05-22 12:06
Duplicate of https://github.com/appium/appium/issues/14825

Unfortunately we do not have any updates on that. Deep hierarchies are impossible to test using XCTest framework because of Apple's Core Foundation objects nesting limitations.

**Closed by mykola-mokhnach** 2023-05-22 12:06 UTC
Labels: Bug, Needs Triage
