### ISSUE TITLE
Appium unable to parse session ID

### ISSUE THREAD

**Issue by ReggTheSecond** [appium/appium#12548] opened 2019-04-26 09:56 UTC
## The problem

When running automated tests via appium CLI 1.12.1 on a real iOS device if mobile device wifi is enabled iproxy is not used to communicate with the device and commands are not able to be sent to the device.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1 (Installed NPM)
* Last Appium version that did not exhibit the issue (if applicable):
1.9.1 (Installed NPM)
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.6
* Node.js version (unless using Appium.app|exe): v8.12.0
* NPM: 6.4.1
* Mobile platform/version under test: iOS 12.1.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

While executing tests on a real iOS device if mobile device wifi is enabled, when Appium requests the session ID from the WebdriverAgent application, Appium is unable to parse the session ID `Cannot read property 'sessionId' of undefined` from the response.

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/ReggTheSecond/4410a3367d604007833af49356abbd88

After investigation I believe this to be the most relivent part of the above log file.
```[debug] [WD Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.bluebridgetech.iris.app.adhoc","arguments":[],"environment":{},"eventloopIdleDelaySec":10,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":false}}
[debug] [WD Proxy] Got response with status 200:
[WD Proxy] Got an unexpected response:
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Cannot read property 'sessionId' of undefined). Retrying...
```

## Code To Reproduce Issue

```python
def get_desired_capabilities():
    desired_caps = {
        "app": get_path_to_app(),
        "platformName": "IOS",
        "deviceName": "iPhone 5s",
        "platformVersion": "12.1",
        "fullReset": True,
        "udid": get_device_id()
        "deviceName": "iPod Touch"
        "xcodeOrgId": "EXAMPLE"
        "xcodeSigningId"]: "iPhone Developer"
        "showIOSLog"]: True
        "automationName": "XCUITest"
    }

desired_capabilities = get_desired_capabilities()
        context.driver = webdriver.Remote(
            "http://localhost:4723/wd/hub", desired_capabilities
        )
```

**Comment by imurchie** [comment] 2019-04-26 10:09
Is there any chance you can turn off iOS logging and re-post the logs?

**Comment by mykola-mokhnach** [comment] 2019-04-26 11:04
> 2019-04-26 09:41:07:087 [WD Proxy] Got response with status 200: ""

Duplicate of https://github.com/appium/appium/issues/12503

**Closed** 2019-04-29 11:13 UTC
Labels: NeedsInfo, NotABug
