### ISSUE TITLE
iPhonX simulator can't record screen

### ISSUE THREAD

**Issue by huotaihe** [appium/appium#11312] opened 2018-09-04 07:43 UTC
## The problem

Hi ,
I'm trying to record iPhone simulator with startRecordingScreen() API but it seems that it doesn't work properly for iOS.

## Environment

* Appium version : 1.9.0
* Desktop OS/version used to run Appium: Mac os 10.13.6
* Node.js version (unless using Appium.app|exe): v10.9.0
* Mobile platform/version under test: iPhone X simulator/ 11.4
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: simulator

## Details

I tried to use the ‘startRecordingScreen’ and ‘stopRecordingScreen’ screens, but the returned screen results are empty.

## Link to Appium logs

[HTTP] <-- POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/url 200 2173 ms - 14
[HTTP]
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: 'complete'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] readyState was "complete"
[debug] [RemoteDebugger] Page is ready
[HTTP] --> POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/appium/start_recording_screen
[HTTP] {"options":{"timeLimit":10,"videoType":"mp4","videoQuality":"low"}}
[debug] [W3C] Calling AppiumDriver.startRecordingScreen() with args: [{"timeLimit":10,"videoType":"mp4","videoQuality":"low"},"2c771158-b356-4300-9568-84a25a8f6043"]
[debug] [XCUITest] Executing command 'startRecordingScreen'
[XCUITest] Checking if there is/was a previous screen recording. Set 'forceRestart' option to 'true' if you'd like to skip this step.
[XCUITest] Screen recording is not running. There is nothing to stop.
[ffmpeg] ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
[ffmpeg]
[ffmpeg]   built with Apple LLVM version 9.1.0 (clang-902.0.39.2)
[ffmpeg]   configuration: --prefix=/usr/local/Cellar/ffmpeg/4.0.2 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
[ffmpeg]
[ffmpeg]   libavutil      56. 14.100 / 56. 14.100
[ffmpeg]   libavcodec     58. 18.100 / 58. 18.100
[ffmpeg]   libavformat    58. 12.100 / 58. 12.100
[ffmpeg]   libavdevice    58.  3.100 / 58.  3.100
[ffmpeg]
[ffmpeg]   libavfilter     7. 16.100 /  7. 16.100
[ffmpeg]   libavresample   4.  0.  0 /  4.  0.  0
[ffmpeg]   libswscale      5.  1.100 /  5.  1.100
[ffmpeg]   libswresample   3.  1.100 /  3.  1.100
[ffmpeg]   libpostproc    55.  1.100 / 55.  1.100
[ffmpeg]
[debug] [RemoteDebugger] Received page change notice for app 'PID:21967' but listening for 'PID:21960'. Ignoring.
[debug] [RemoteDebugger] Page changed: {"1":{"WIRTitleKey":"I am a page title - Sauce Labs","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"https://saucelabs.com/test/guinea-pig","WIRPageIdentifierKey":1,"WIRConnectionIdentifierKey":"0a671764-7ce3-4673-b955-163280d37cb6"}}
[debug] [iOS] Remote debugger notified us of a new page listing: {"appIdKey":"21967","pageArray":[{"id":1,"title":"I am a page title - Sauce Labs","url":"https://saucelabs.com/test/guinea-pig","isKey":true}]}
[debug] [iOS] Checking if page needs to load
[debug] [iOS] New page listing is same as old, doing nothing
[XCUITest] Starting screen capture on the device 'CB9EB650-AE7A-4F99-8CD6-1E4320B84D93' with command: 'ffmpeg -f mjpeg -r 10 -i http://localhost:9100 -vcodec mjpeg -y /var/folders/jg/t_2pv7fs48900r3s45jtgp_c0000gn/T/201884-90173-1kun7hc.mwss/appium_39166e.mp4'. Will timeout in 10ms
[debug] [W3C] Responding to client with driver.startRecordingScreen() result: ""
[HTTP] <-- POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/appium/start_recording_screen 200 5021 ms - 12
[HTTP]
[ffmpeg] [mjpeg @ 0x7f8cd1800000] bits 190 is invalid
[ffmpeg]
[ffmpeg] [mjpeg @ 0x7f8cd2800000] decoding for stream 0 failed
[ffmpeg]
[ffmpeg] [mjpeg @ 0x7f8cd2800000] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown), lossless): unspecified size
[ffmpeg] Consider increasing the value for the 'analyzeduration' and 'probesize' options
[ffmpeg]
[ffmpeg] Input #0, mjpeg, from 'http://localhost:9100':
[ffmpeg]   Duration: N/A
[ffmpeg] , bitrate: N/A
[ffmpeg]     Stream #0:0: Video: mjpeg, none(bt470bg/unknown/unknown), lossless, 10 tbr, 1200k tbn, 10 tbc
[ffmpeg]
[ffmpeg] Stream mapping:
[ffmpeg]
[ffmpeg]   Stream #0:0 -> #0:0
[ffmpeg]  (mjpeg (native) -> mjpeg (native))
[ffmpeg] Press [q] to stop, [?] for help
[ffmpeg]
[ffmpeg] Cannot determine format of input stream 0:0 after EOF
[ffmpeg] Error marking filters as finished
[ffmpeg]
[ffmpeg] Exiting normally, received signal 2.
[ffmpeg]
[HTTP] --> POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/appium/settings
[HTTP] {"settings":{"nativeWebTap":true}}
[debug] [W3C] Calling AppiumDriver.updateSettings() with args: [{"nativeWebTap":true},"2c771158-b356-4300-9568-84a25a8f6043"]
[debug] [XCUITest] Executing command 'updateSettings'
[debug] [W3C] Responding to client with driver.updateSettings() result: null
[HTTP] <-- POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/appium/settings 200 5 ms - 14
[HTTP]
[HTTP] --> POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/element
[HTTP] {"using":"id","value":"i am a link"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["id","i am a link","2c771158-b356-4300-9568-84a25a8f6043"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [RemoteDebugger] Executing 'find_element' atom in default context
[debug] [RemoteDebugger] Garbage collecting with 5000ms timeout
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{}'
[debug] [RemoteDebugger] Original command: garbageCollect
[debug] [RemoteDebugger] Garbage collection successful
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var k=this;functi...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":{"ELEMENT":":wdc:1536046569...'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1536046569337"}
[debug] [W3C] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"5000"}
[HTTP] <-- POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/element 200 225 ms - 56
[HTTP]
[HTTP] --> POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/element/5000/click
[HTTP] {"id":"5000"}
[debug] [W3C] Calling AppiumDriver.click() with args: ["5000","2c771158-b356-4300-9568-84a25a8f6043"]
[debug] [XCUITest] Executing command 'click'
[debug] [XCUITest] Using native web tap
[debug] [RemoteDebugger] Executing 'get_text' atom in default context
[debug] [RemoteDebugger] Garbage collecting with 5000ms timeout
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Received page change notice for app 'PID:21967' but listening for 'PID:21960'. Ignoring.
[debug] [RemoteDebugger] Page changed: {"1":{"WIRTitleKey":"I am a page title - Sauce Labs","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"https://saucelabs.com/test/guinea-pig","WIRPageIdentifierKey":1,"WIRConnectionIdentifierKey":"0a671764-7ce3-4673-b955-163280d37cb6"}}
[debug] [iOS] Remote debugger notified us of a new page listing: {"appIdKey":"21967","pageArray":[{"id":1,"title":"I am a page title - Sauce Labs","url":"https://saucelabs.com/test/guinea-pig","isKey":true}]}
[debug] [iOS] Checking if page needs to load
[debug] [iOS] New page listing is same as old, doing nothing
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{}'
[debug] [RemoteDebugger] Original command: garbageCollect
[debug] [RemoteDebugger] Garbage collection successful
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var h,l=this;func...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":"i am a link"}'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] Received result for atom 'get_text' execution: "i am a link"
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Matched '/element' to command name 'findElement'
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/7BBE6BE0-D372-4D02-BB0B-5346A7BBAF8B/element] with body: {"using":"accessibility id","value":"i am a link"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"1C000000-0000-0000-CF55-000000000000"},"sessionId":"7BBE6BE0-D372-4D02-BB0B-5346A7BBAF8B","status":0}
[debug] [JSONWP Proxy] Matched '/element/1C000000-0000-0000-CF55-000000000000/rect' to command name 'getElementRect'
[debug] [JSONWP Proxy] Proxying [GET /element/1C000000-0000-0000-CF55-000000000000/rect] to [GET http://localhost:8100/session/7BBE6BE0-D372-4D02-BB0B-5346A7BBAF8B/element/1C000000-0000-0000-CF55-000000000000/rect] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 123,\n    \"x\" : 3,\n    \"width\" : 40,\n    \"height\" : 13\n  },\n  \"sessionId\" : \"7BBE6BE0-D372-4D02-BB0B-5346A7BBAF8B\",\n  \"status\" : 0\n}"
[debug] [XCUITest] Received the following touch action: tap(options={"x":23,"y":129.5})
[debug] [JSONWP Proxy] Proxying [POST /wda/touch/perform] to [POST http://localhost:8100/session/7BBE6BE0-D372-4D02-BB0B-5346A7BBAF8B/wda/touch/perform] with body: {"actions":[{"action":"tap","options":{"x":23,"y":129.5}}]}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"7BBE6BE0-D372-4D02-BB0B-5346A7BBAF8B","status":0}
[debug] [W3C] Responding to client with driver.click() result: null
[HTTP] <-- POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/element/5000/click 200 855 ms - 14
[HTTP]
[HTTP] --> GET /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/title
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.title() with args: ["2c771158-b356-4300-9568-84a25a8f6043"]
[debug] [XCUITest] Executing command 'title'
[debug] [RemoteDebugger] Executing 'title' atom in default context
[debug] [RemoteDebugger] Garbage collecting with 5000ms timeout
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{}'
[debug] [RemoteDebugger] Original command: garbageCollect
[debug] [RemoteDebugger] Garbage collection successful
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":"I am a page title - Sauce ...'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] Received result for atom 'title' execution: "I am a page title - Sauce Labs"
[debug] [W3C] Responding to client with driver.title() result: "I am a page title - Sauce Labs"
[HTTP] <-- GET /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/title 200 144 ms - 42
[HTTP]
[debug] [RemoteDebugger] Frame navigated, unloading page
[debug] [RemoteDebugger] Page loaded, verifying whether ready
[HTTP] --> GET /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/title
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.title() with args: ["2c771158-b356-4300-9568-84a25a8f6043"]
[debug] [XCUITest] Executing command 'title'
[debug] [RemoteDebugger] Executing 'title' atom in default context
[debug] [RemoteDebugger] Garbage collecting with 5000ms timeout
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{}'
[debug] [RemoteDebugger] Original command: garbageCollect
[debug] [RemoteDebugger] Garbage collection successful
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":"I am another page title - ...'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] Received result for atom 'title' execution: "I am another page title - Sauce Labs"
[debug] [W3C] Responding to client with driver.title() result: "I am another page title - Sauce Labs"
[HTTP] <-- GET /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/title 200 93 ms - 48
[HTTP]
[HTTP] --> POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/back
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.back() with args: ["2c771158-b356-4300-9568-84a25a8f6043"]
[debug] [XCUITest] Executing command 'back'
[debug] [RemoteDebugger] Executing 'execute_script' atom in default context
[debug] [RemoteDebugger] Garbage collecting with 5000ms timeout
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Page changed: {"1":{"WIRTitleKey":"I am another page title - Sauce Labs","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"https://saucelabs.com/test-guinea-pig2.html","WIRPageIdentifierKey":1,"WIRConnectionIdentifierKey":"0a671764-7ce3-4673-b955-163280d37cb6"}}
[debug] [iOS] Remote debugger notified us of a new page listing: {"appIdKey":"21967","pageArray":[{"id":1,"title":"I am another page title - Sauce Labs","url":"https://saucelabs.com/test-guinea-pig2.html","isKey":true}]}
[debug] [iOS] Checking if page needs to load
[debug] [iOS] New page listing is same as old, doing nothing
[debug] [iOS] Redirected from 'https://saucelabs.com/test/guinea-pig' to 'https://saucelabs.com/test-guinea-pig2.html'
[debug] [RemoteDebugger] Received page change notice for app 'PID:21967' but listening for 'PID:21960'. Ignoring.
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{}'
[debug] [RemoteDebugger] Original command: garbageCollect
[debug] [RemoteDebugger] Garbage collection successful
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var e=this;
[debug] [RemoteDebugger] funct...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":null}'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] Received result for atom 'execute_script' execution: null
[debug] [W3C] Responding to client with driver.back() result: null
[HTTP] <-- POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/back 200 74 ms - 14
[HTTP]
[debug] [RemoteDebugger] Frame navigated but we were warned about it, not considering page state unloaded
[HTTP] --> GET /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/title
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.title() with args: ["2c771158-b356-4300-9568-84a25a8f6043"]
[debug] [XCUITest] Executing command 'title'
[debug] [RemoteDebugger] Executing 'title' atom in default context
[debug] [RemoteDebugger] Garbage collecting with 5000ms timeout
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{}'
[debug] [RemoteDebugger] Original command: garbageCollect
[debug] [RemoteDebugger] Garbage collection successful
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":"I am a page title - Sauce ...'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] Received result for atom 'title' execution: "I am a page title - Sauce Labs"
[debug] [W3C] Responding to client with driver.title() result: "I am a page title - Sauce Labs"
[HTTP] <-- GET /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/title 200 190 ms - 42
[HTTP]
[HTTP] --> POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/appium/settings
[HTTP] {"settings":{"nativeWebTap":false}}
[debug] [W3C] Calling AppiumDriver.updateSettings() with args: [{"nativeWebTap":false},"2c771158-b356-4300-9568-84a25a8f6043"]
[debug] [XCUITest] Executing command 'updateSettings'
[debug] [RemoteDebugger] Checking document readyState
[debug] [RemoteDebugger] Garbage collecting with 5000ms timeout
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [W3C] Responding to client with driver.updateSettings() result: null
[HTTP] <-- POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/appium/settings 200 5 ms - 14
[HTTP]
[HTTP] --> POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/element
[HTTP] {"using":"id","value":"i am a link"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["id","i am a link","2c771158-b356-4300-9568-84a25a8f6043"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [RemoteDebugger] Executing 'find_element' atom in default context
[debug] [RemoteDebugger] Garbage collecting with 5000ms timeout
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Page changed: {"1":{"WIRTitleKey":"I am a page title - Sauce Labs","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"https://saucelabs.com/test/guinea-pig","WIRPageIdentifierKey":1,"WIRConnectionIdentifierKey":"0a671764-7ce3-4673-b955-163280d37cb6"}}
[debug] [iOS] Remote debugger notified us of a new page listing: {"appIdKey":"21967","pageArray":[{"id":1,"title":"I am a page title - Sauce Labs","url":"https://saucelabs.com/test/guinea-pig","isKey":true}]}
[debug] [iOS] Checking if page needs to load
[debug] [iOS] New page listing is same as old, doing nothing
[debug] [iOS] Redirected from 'https://saucelabs.com/test-guinea-pig2.html' to 'https://saucelabs.com/test/guinea-pig'
[debug] [RemoteDebugger] Received page change notice for app 'PID:21967' but listening for 'PID:21960'. Ignoring.
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{}'
[debug] [RemoteDebugger] Original command: garbageCollect
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{}'
[debug] [RemoteDebugger] Original command: garbageCollect
[debug] [RemoteDebugger] Garbage collection successful
[debug] [RemoteDebugger] Sending javascript command (function (){ return document.readyState; })()
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Garbage collection successful
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var k=this;functi...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: 'complete'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] readyState was "complete"
[debug] [RemoteDebugger] Page is ready
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":{"ELEMENT":":wdc:1536046569...'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1536046569337"}
[debug] [W3C] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"5001"}
[HTTP] <-- POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/element 200 93 ms - 56
[HTTP]
[HTTP] --> POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/element/5001/click
[HTTP] {"id":"5001"}
[debug] [W3C] Calling AppiumDriver.click() with args: ["5001","2c771158-b356-4300-9568-84a25a8f6043"]
[debug] [XCUITest] Executing command 'click'
[debug] [RemoteDebugger] Executing 'click' atom in default context
[debug] [RemoteDebugger] Garbage collecting with 5000ms timeout
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{}'
[debug] [RemoteDebugger] Original command: garbageCollect
[debug] [RemoteDebugger] Garbage collection successful
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":null}'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] Received result for atom 'click' execution: null
[debug] [W3C] Responding to client with driver.click() result: null
[HTTP] <-- POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/element/5001/click 200 235 ms - 14
[HTTP]
[HTTP] --> GET /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/title
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.title() with args: ["2c771158-b356-4300-9568-84a25a8f6043"]
[debug] [XCUITest] Executing command 'title'
[debug] [RemoteDebugger] Executing 'title' atom in default context
[debug] [RemoteDebugger] Garbage collecting with 5000ms timeout
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Frame navigated, unloading page
[debug] [RemoteDebugger] Page loaded, verifying whether ready
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{}'
[debug] [RemoteDebugger] Original command: garbageCollect
[debug] [RemoteDebugger] Garbage collection successful
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
[debug] [RemoteDebugger] Found data handler for response
[debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":"I am another page title - ...'
[debug] [RemoteDebugger] Original command: sendJSCommand
[debug] [RemoteDebugger] Received result for atom 'title' execution: "I am another page title - Sauce Labs"
[debug] [W3C] Responding to client with driver.title() result: "I am another page title - Sauce Labs"
[HTTP] <-- GET /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/title 200 152 ms - 48
[HTTP]
[HTTP] --> POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/appium/stop_recording_screen
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.stopRecordingScreen() with args: [null,"2c771158-b356-4300-9568-84a25a8f6043"]
[debug] [XCUITest] Executing command 'stopRecordingScreen'
[debug] [XCUITest] The size of the file is 0 B
[debug] [W3C] Responding to client with driver.stopRecordingScreen() result: ""
[HTTP] <-- POST /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043/appium/stop_recording_screen 200 5 ms - 12
[HTTP]
[HTTP] --> DELETE /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.deleteSession() with args: ["2c771158-b356-4300-9568-84a25a8f6043"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1536046571888 (15:36:11 GMT+0800 (China Standard Time))
[Appium] Removing session 2c771158-b356-4300-9568-84a25a8f6043 from our master session list
[debug] [JSONWP Proxy] Matched '/session/2c771158-b356-4300-9568-84a25a8f6043' to command name 'deleteSession'
[debug] [JSONWP Proxy] Proxying [DELETE /session/2c771158-b356-4300-9568-84a25a8f6043] to [DELETE http://localhost:8100/session/7BBE6BE0-D372-4D02-BB0B-5346A7BBAF8B] with no body
[debug] [RemoteDebugger] Application 'PID:21960' disconnected. Removing from app dictionary.
[debug] [RemoteDebugger] Current app is PID:21960
[debug] [RemoteDebugger] No longer have app id. Attempting to find new one.
[debug] [RemoteDebugger] Application 'PID:21967' disconnected. Removing from app dictionary.
[debug] [RemoteDebugger] Current app is undefined
[debug] [RemoteDebugger] Application 'PID:21960' disconnected. Removing from app dictionary.
[debug] [RemoteDebugger] Current app is PID:21967
[debug] [RemoteDebugger] Application 'PID:21967' disconnected. Removing from app dictionary.
[debug] [RemoteDebugger] Current app is PID:21967
[debug] [RemoteDebugger] No longer have app id. Attempting to find new one.
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"16A0FDD3-2837-49E6-A67B-CB7E336E9D35\",\n  \"status\" : 0\n}"
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [XCUITest] In a web session. Removing remote debugger
[debug] [RemoteDebugger] Disconnecting from remote debugger
[debug] [RemoteDebugger] Cleaning up listeners
[debug] [iOSLog] Stopping iOS log capture
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1536046572239 (15:36:12 GMT+0800 (China Standard Time))
[debug] [W3C] Received response: null
[debug] [W3C] But deleting session, so not returning
[debug] [W3C] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/2c771158-b356-4300-9568-84a25a8f6043 200 352 ms - 14
[HTTP]
[debug] [RemoteDebugger] Not connected to an application. Ignoring page load

## Code To Reproduce Issue [ Good To Have ]

I test with java-client test case [https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/ios/IOSNativeWebTapSettingTest.java](source code)

    @Test public void nativeWebTapSettingTest() throws InterruptedException {

        driver.get("https://saucelabs.com/test/guinea-pig");
        String recordingScreenData = driver.startRecordingScreen(new IOSStartScreenRecordingOptions().withVideoType(VideoType.MP4)
            .withVideoQuality(VideoQuality.LOW)
            .withTimeLimit(Duration.ofSeconds(10)));
        Thread.sleep(100);
        // do a click with nativeWebTap turned on, and assert we get to the right page
        driver.nativeWebTap(true);
        WebElement el = driver.findElementById("i am a link");
        el.click();
        assertTrue(new WebDriverWait(driver, 30)
                .until(ExpectedConditions.titleIs("I am another page title - Sauce Labs")));
        driver.navigate().back();
        // now do a click with it turned off and assert the same behavior
        assertTrue(new WebDriverWait(driver, 30)
                .until(ExpectedConditions.titleIs("I am a page title - Sauce Labs")));
        driver.nativeWebTap(false);
        el = driver.findElementById("i am a link");
        el.click();
        assertTrue(new WebDriverWait(driver, 30)
                .until(ExpectedConditions.titleIs("I am another page title - Sauce Labs")));
        String mediaString = driver.stopRecordingScreen();
    }

**Comment by mykola-mokhnach** [comment] 2018-09-04 08:29
Duplicate of https://github.com/appium/appium/issues/11279

**Closed by mykola-mokhnach** 2018-09-04 08:29 UTC

**Comment by huotaihe** [comment] 2018-09-04 08:56
#11279 Can't record screen because error '[ffmpeg] [tcp @ 0x7feb24000300] Connection to tcp://localhost:9100 failed '

But there are not this error in my log.

My English is poor, I hope you can understand what I mean.

**Comment by mykola-mokhnach** [comment] 2018-09-04 08:58
Yes I did understand. The problem should be addressed in appium@beta
