### ISSUE TITLE
[XCODE]: Error XCUISiriService' is partial: introduced in iOS 10.3

### ISSUE THREAD

**Issue by skumar1122** [appium/appium#8132] opened 2017-03-30 16:37 UTC
## The problem

Building WebDriverAgent throws an error ,
Testing failed:
	'XCUISiriService' is partial: introduced in iOS 10.3
	Could not build module 'XCTest'
** TEST FAILED **

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6@beta
* Desktop OS/version used to run Appium: 10.12.14
* Node.js version (unless using Appium.app|exe):v6.3.1
* Mobile platform/version under test: iOS10.2
* Real device or emulator/simulator:iPhone6 real device
* Xcode: 8.3

## Details
I am facing this issue after updating to new version of Xcode 8.3 and I am getting error while building WebDriverAgent. It worked for me before and I am facing issues with new version only. I tried to build manually wda and please check the screenshot from Xcode error.

![screen shot 2017-03-30 at 17 34 16](https://cloud.githubusercontent.com/assets/20112173/24515345/422d64fa-156f-11e7-89d3-b0c7f68d1c92.png)

## Link to Appium logs

https://gist.github.com/skumar1122/9b6e6b1d469ae607b6efd990f801b802.js

Suggestions please ?

Thanks
SK

**Comment by dpgraham** [comment] 2017-03-30 17:07
This is a duplicate of this issue: https://github.com/appium/appium/issues/7952

**Closed by dpgraham** 2017-03-30 17:07 UTC
Labels: NeedsTriage
