### ISSUE TITLE
Android Driver : driver.getKeyboard().sendKeys("String") isn't working

### ISSUE THREAD

**Issue by Mohannad91** [appium/appium#10900] opened 2018-06-19 15:08 UTC
## The problem

after upgrading from Appium 1.7.2 to 1.8.0.

## Environment

* Appium version : 1.8.0
* Last Appium version that did not exhibit the issue : 1.7.2
* Desktop OS/version used to run Appium: Windows 10
* Node.js version : 8.10.0
* Mobile platform/version under test: Android 7.1.1 
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I was able to use driver.getKeyboard().sendKeys("String") when a keyboard is already shown but now  it will cause an (org.openqa.selenium.UnsupportedCommandException: sendKeysToActiveElement) error.

## Link to Appium logs

https://gist.github.com/Mohannad91/c6689129fbe79dd573f0cf7180d91be8

## Code To Reproduce Issue [ Good To Have ]
        AppiumDriverLocalService service = AppiumDriverLocalService.buildDefaultService();
        service.start();
        DesiredCapabilities MobileDevice = DesiredCapabilities.android();
        MobileDevice.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
        MobileDevice.setCapability(MobileCapabilityType.DEVICE_NAME, DeviceName);
        MobileDevice.setCapability(MobileCapabilityType.PLATFORM_VERSION, AndroidVersion);
        MobileDevice.setCapability(MobileCapabilityType.NO_RESET, "True");
        MobileDevice.setCapability(MobileCapabilityType.APP, ApplicationPath);
        MobileDevice.setCapability("autoGrantPermissions", "true");

        driver = new AndroidDriver (service.getUrl(), MobileDevice);

	// in another class
	driver.findElement(searchButtonLocator).click();
        driver.getKeyboard().sendKeys("String");

**Comment by mykola-mokhnach** [comment] 2018-06-19 15:42
It is a duplicate of https://github.com/SeleniumHQ/selenium/issues/4546
Long story short: the command is not present in W3C specification and is not supported by Selenium API anymore. You should either replace it with supported commands or switch back MJSOWP protocol (not recommended).

**Closed by mykola-mokhnach** 2018-06-19 15:42 UTC

**Comment by jhenkie** [comment] 2018-07-03 03:09
@mykola-mokhnach i use this driver.getKeyboard().sendKeys("String"); for ios automation.
may i know the other supported commands?

**Comment by mykola-mokhnach** [comment] 2018-07-03 05:52
You could send keys one by one. Check, for example, https://github.com/appium/java-client/blob/d8e477c1d6766b643b8aadc5cc110291ac8cf27f/src/test/java/io/appium/java_client/android/KeyCodeTest.java#L41

**Comment by jhenkie** [comment] 2018-07-03 06:04
@mykola-mokhnach thank you for you answer but currently i'm using IOSDriver and i can't found pressKey at there.

**Comment by mykola-mokhnach** [comment] 2018-07-03 06:05
On iOS the keyboard is present in the accessibility tree, so you can simply locate and tap the necessary keys by their ids

**Comment by jhenkie** [comment] 2018-07-03 06:10
@mykola-mokhnach oh god! i just realized it after i can press the expand element. thanks a lot

**Comment by oyablonskyi** [comment] 2018-07-03 14:22
@mykola-mokhnach Your solution is workaround but it does not fix issue with sendKeys method from Keyboard interface(like driver.getKeyboard().sendKeys("String");)

**Comment by mykola-mokhnach** [comment] 2018-07-03 14:25
@oyablonskyi Feel free to push a PR if you can implement it in a better way

**Comment by 0neel** [comment] 2018-08-09 11:39
Today I've found out that `element.setValue("...")` uses `adb shell input text` internally! This is even better for us :)

**Comment by adrianth** [comment] 2018-12-04 03:36
@mykola-mokhnach Is this just a temporary hiccup or are we saying that the syntax `driver.getKeyboard().sendKeys()` will not be supported ever again? If the underlying platform (UiAutomator2, XCUITest, etc.) supports this, shouldn't we be able to invoke it via Appium? Is yes, we should reopen this issue. Otherwise, we should probably remove the syntax `driver.getKeyboard().sendKeys()` from all language bindings. I would appreciate if you could weigh in on this, as I don't have enough insight into the potential solutions or workarounds to this. Thanks.

**Comment by jromero** [comment] 2019-03-07 14:27
Why is this issue closed? It appears to still be an issue. Calling this method returns unimplemented when it could easily be implemented.

**Comment by nageshc** [comment] 2019-09-18 07:00
Hi All,

I also facing same issue for sendkeys for Android OS version 7.0 and above.

I have used following solution:
            otpElement.click();
            ((AndroidDriver)driver).pressKeyCode(AndroidKeyCode.KEYCODE_1);
            ((AndroidDriver)driver).pressKeyCode(AndroidKeyCode.KEYCODE_3);
            ((AndroidDriver)driver).pressKeyCode(AndroidKeyCode.KEYCODE_4);
            ((AndroidDriver)driver).pressKeyCode(AndroidKeyCode.KEYCODE_5);
            ((AndroidDriver)driver).pressKeyCode(AndroidKeyCode.KEYCODE_8);
            ((AndroidDriver)driver).pressKeyCode(AndroidKeyCode.KEYCODE_6);

Thanks

**Comment by p-funky** [comment] 2024-10-11 19:56
`
await driver.execute('mobile: shell', {
    command: 'input',
    args: ['text', "Your text here"]
});
`
but you'd have to update services in your wdio config to allow it like this => `services: [['appium', {args: {allowInsecure: 'adb_shell'}}]]`
