### ISSUE TITLE
Could Not Launch Appium Inspector | Appium Inspector not supporting/working for iOS Native Apps 

### ISSUE THREAD

**Issue by Automation-Test** [appium/appium#8478] opened 2017-05-17 15:22 UTC
## The problem

I have been used the Appium Inspector for identify the elements for Android Native Apps, however I tried the same way for iOS Native Apps to get the elements . The iOS Native Apps was installed in my real devices but inspector window in not open and I got an error message says that 

[MJSONWP] Encountered internal error running command: Error: Command failed: ideviceinstaller -u 81e1a267c01927XXXXXXXXX -i /Users/XXXXX/Downloads/ios.app.

 at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
[HTTP] <-- POST /wd/hub/session 500 16864 ms - 256 

Could not start a new session

Be sure the Appium server is running with an application opened by using the "App Path" parameter in Appium.app (along with package and activity for Android) or by connecting with selenium client and supplying this in the desired capabilities object.

## Environment

* Appium version 1.5.3 , 1.6.4 beta and 1.6.4 
* Desktop OS/version used to run Appium: iOS 
* Node.js version : v7.7.3
* Real devices Mobile platform/version under test: iPhone 6s ( 10.3.1) and iPhone 5c (10.2.1) 
   

Please help me on this.

**Comment by dpgraham** [comment] 2017-05-17 17:17
Are you trying to run this on a real device?

If you are, then a .app won't work you need a .ipa

**Comment by imurchie** [comment] 2017-05-17 18:25
Can you post a link to a [gist](https://gist.github.com) of the _full_ Appium server logs? This is not enough to go on, other than to say that `ideviceinstaller` is failing to install the app. This is a known problem, and the current release of appium does not use `ideviceinstaller`. You can try running `ideviceinstaller -u 81e1a267c01927XXXXXXXXX -i /Users/XXXXX/Downloads/ios.app` manually to see that it does not work.

Appium 1.5.3 will _not_ work, since it does not know how to automate iOS devices above version 9.3. 1.6.4 ought to work.

**Comment by Automation-Test** [comment] 2017-05-17 19:11
@imurchie https://gist.github.com/Automation-Test/6140e9744e92eb32f4e10170874b12fe Thank you.

**Comment by Automation-Test** [comment] 2017-05-17 19:13
@dpgraham I tried with .ipa file as well.

**Comment by imurchie** [comment] 2017-05-17 19:16
This is a duplicate of https://github.com/appium/appium/issues/8442

Essentially, an upstream dependency was deleted by its owner, and now Appium 1.6.3 will not work unless it was already working (i.e., if the dependency was already downloaded).

The only solution is to upgrade to the latest Appium version (`npm uninstall -g appium && npm install -g appium`).

**Comment by Automation-Test** [comment] 2017-05-17 19:18
Thank for your quick responses , I will upgrade version now and share the results .

**Comment by Automation-Test** [comment] 2017-05-17 19:45
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","newCommandTimeout":"7200","app":"/Users/xxx/Downloads/ios.app","platformVersion":"10.3.1","deviceName":"iPhone 6s","bundleId":"com.app.iOS","automationName":"Appium","udid":"81e1a267c027decdd9faadda9ad51f5375d1f7"},null,null,null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1495049619002 (15:33:39 GMT-0400 (EDT))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.27.2) session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   newCommandTimeout: '7200'
[Appium]   app: '/Users/xxxxxx/Downloads/ios.app'
[Appium]   platformVersion: '10.3.1'
[Appium]   deviceName: 'iPhone 6s'
[Appium]   bundleId: 'com.ios.iOS'
[Appium]   automationName: 'Appium'
[Appium]   udid: '81e1a267c01927decdd9faadda9ad51f5375d1f7'
[debug] [XCUITest] XCUITestDriver version: 2.27.2
[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior
[BaseDriver] Session created with session id: cfb9a745-32ac-4845-8b83-54328d5ba892
[debug] [XCUITest] Xcode version set to '8.3.2' (tools v8.3.2.0.1.1492020469)
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1495049619118 (15:33:39 GMT-0400 (EDT))
[debug] [XCUITest] Available devices: 81e1a267c01927decdd9faadda9ad51f5375d1f7
[debug] [XCUITest] Creating iDevice object with udid '81e1a267c01927decdd9faadda9ad51f5375d1f7'
[XCUITest] Determining device to run tests on: udid: '81e1a267c01927decdd9faadda9ad51f5375d1f7', real device: true
[BaseDriver] Using local app '/Users/xxxx/Downloads/ios.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1495049619313 (15:33:39 GMT-0400 (EDT))
[debug] [XCUITest] Checking whether app '/Users/xxxxx/Downloads/ios.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [BaseDriver] Event 'resetStarted' logged at 1495049619314 (15:33:39 GMT-0400 (EDT))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1495049619314 (15:33:39 GMT-0400 (EDT))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1495049619482 (15:33:39 GMT-0400 (EDT))
[XCUITest] Setting up real device
[debug] [XCUITest] Installing '/Users/XXXXX/Downloads/iOS.app' on device with UUID '81e1a267c01927decdd9faadda9ad51f5375d1f7'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1495049630324 (15:33:50 GMT-0400 (EDT))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1495049630324 (15:33:50 GMT-0400 (EDT))
[XCUITest] Using WDA path: '/Users/XXXX/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/xxxxx/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Users/xxxx/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=81e1a267c01927decdd9faadda9ad51f5375d1f7 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/Users/xxxxx/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/xxxxx/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Logs/Test/14E12560-F02D-4358-94BE-A5BDD338EDB7/Session-WebDriverAgentRunner-2017-05-17_153358-bGLqOf.log
[Xcode] 2017-05-17 15:33:58.223 xcodebuild[16999:859628] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/xxx/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fe82a488410 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 2017-05-17 15:33:58.223 xcodebuild[16999:859628] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'

Can you please provide your advices  Thank you.

**Comment by imurchie** [comment] 2017-05-17 19:48
This is now a code signing issue. See https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md

**Comment by Automation-Test** [comment] 2017-05-17 20:34
Thanks a lots , One more information needed , Do i need an apple developer id for iOS native apps automation ? without developer id can i start the automation?

**Closed** 2017-06-23 06:42 UTC
