### ISSUE TITLE
Appium Installation on Ubuntu Linux

### ISSUE THREAD

**Issue by barotashish** [appium/appium#10618] opened 2018-04-27 12:47 UTC
## The problem
When I am trying to install Appium on my Ubuntu Linux 17.10 I am getting following error :- 

ashish@ashish-barot:~$ appium
internal/util.js:360
    const filename = frame.getFileName();
                           ^

TypeError: frame.getFileName is not a function
    at isInsideNodeModules (internal/util.js:360:28)
    at showFlaggedDeprecation (buffer.js:149:8)
    at new Buffer (buffer.js:174:3)
    at retrieveSourceMap (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:118:21)
    at mapSourcePosition (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:140:21)
    at wrapCallSite (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:303:20)
    at /home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:338:26
    at Array.map (<anonymous>)
    at Function.prepareStackTrace (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:337:24)
    at process.emit (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/asyncbox/node_modules/source-map-support/source-map-support.js:387:52)
    at process._fatalException (internal/bootstrap/node.js:435:27)

## Environment

* Appium version (or git revision) that exhibits the issue:
* Desktop OS/version used to run Appium: Ubuntu Linux - 17.10 on Lenovo Ideapad 350

**Comment by imurchie** [comment] 2018-04-27 12:49
This is a problem with Node 10. Duplicate of #10609

**Closed by imurchie** 2018-04-27 12:49 UTC

**Comment by barotashish** [comment] 2018-04-30 05:10
Thanks Isaac for close observation. 
Sorry, for duplicate bug filing. 

Regards,
Ashish Barot.
