### ISSUE TITLE
appium 2.0 : no route found for /wd/hub/status

### ISSUE THREAD

**Issue by StephanB75** [appium/appium#15813] opened 2021-09-06 11:52 UTC
## The problem

i tried to upgrade my appium project to 2.0
i'm starting the server programmatically and this seems to work but i get an error

## Environment

* Appium version : 2.0 beta.13
* Last Appium version that did not exhibit the issue (if applicable): 1.21
* Desktop OS/version used to run Appium: Mac BigSur
* Node.js version (unless using Appium.app|exe): 12.19.1
* Npm or Yarn package manager: 6.14.8
* Mobile platform/version under test: Android
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: appium cli

## Link to Appium logs

 [Appium] Welcome to Appium v2.0.0-beta.13 (REV 6ca23f9960181fea1e2a597de190cc0cb5d8a463)
2021-09-06 13:44:59:757 - [Appium] Non-default server args:
2021-09-06 13:44:59:758 - [Appium]   address: 127.0.0.1
2021-09-06 13:44:59:758 - [Appium]   port: 4726
2021-09-06 13:44:59:759 - [Appium]   callbackPort: 4726
2021-09-06 13:44:59:759 - [Appium]   sessionOverride: true
2021-09-06 13:44:59:760 - [Appium]   logFile: /Users/appium_Droid.Smoke_Test$2.log
2021-09-06 13:44:59:760 - [Appium]   logTimestamp: true
2021-09-06 13:44:59:761 - [Appium]   localTimezone: true
2021-09-06 13:44:59:761 - [Appium]   logNoColors: true
2021-09-06 13:44:59:761 - [Appium]   tmpDir: /var/folders/xf/5vvrnm2s2zq_30nz44g59kg1nrqgg2/T
2021-09-06 13:44:59:762 - [Appium]   defaultCapabilities: {
2021-09-06 13:44:59:762 - [Appium]     noReset: false
2021-09-06 13:44:59:762 - [Appium]   }
2021-09-06 13:44:59:762 - [Appium]   relaxedSecurityEnabled: true
2021-09-06 13:44:59:763 - [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
2021-09-06 13:44:59:763 - [Appium]   noReset: false
2021-09-06 13:44:59:764 - [Appium] Attempting to load driver uiautomator2...
2021-09-06 13:45:02:841 - [Appium] Appium REST http interface listener started on 127.0.0.1:4726
2021-09-06 13:45:02:841 - [Appium] Available drivers:
2021-09-06 13:45:02:842 - [Appium]   - uiautomator2@1.67.0 (automationName 'UiAutomator2')
2021-09-06 13:45:02:844 - [Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
2021-09-06 13:45:03:136 - [HTTP] --> GET /wd/hub/status
2021-09-06 13:45:03:137 - [HTTP] {}
2021-09-06 13:45:03:146 - [debug] [HTTP] No route found for /wd/hub/status
2021-09-06 13:45:03:152 - [HTTP] <-- GET /wd/hub/status 404 14 ms - 211

Exception :
io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: 
The local appium server has not been started. The given Node.js executable: /usr/local/bin/node Arguments: [/Users/stephan.bast/git/project/target/../node_modules/.bin/appium, --port, 4726, --address, 127.0.0.1, --log, /Users/stephan.bast/git/java/appium_Droid.Smoke_Test$2.log, --log-level, debug, --local-timezone, --relaxed-security, --session-override, --log-no-colors, --callback-port, 4726, --log-timestamp, --default-capabilities, {"noReset":"false"}] 
Process output: und for /wd/hub/status

## Code To Reproduce Issue [ Good To Have ]

starting server :
                builder = new AppiumServiceBuilder().withLogFile(new File("appium_"+className+".log"));
		builder.withIPAddress("127.0.0.1");
		builder.usingPort(getAppiumPort());
		builder.withCapabilities(cap);
		builder.withArgument(GeneralServerFlag.SESSION_OVERRIDE);
		builder.withArgument(GeneralServerFlag.LOG_LEVEL, getAppiumLogLevel());
		builder.withArgument(GeneralServerFlag.RELAXED_SECURITY);
		builder.withArgument(GeneralServerFlag.LOG_NO_COLORS);
		builder.withArgument(GeneralServerFlag.CALLBACK_PORT, Integer.toString(getAppiumPort()));
		builder.withArgument(GeneralServerFlag.LOG_TIMESTAMP);
		builder.withArgument(GeneralServerFlag.LOCAL_TIMEZONE);

        	service = AppiumDriverLocalService.buildService(builder);
		service.start();

initialize driver :
		driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4726/wd/hub"), caps);

**Comment by StephanB75** [comment] 2021-09-06 13:43
seems to work if i start the server from commandline with
node appium -p 4726 --base-path /wd/hub

Can anyone help me, how i pass the serverArgument with the AppiumServiceBuilder ?

**Comment by mykola-mokhnach** [comment] 2021-09-06 13:50
Duplicate of https://github.com/appium/appium/issues/15261

**Comment by mykola-mokhnach** [comment] 2021-09-06 13:50
> Can anyone help me, how i pass the serverArgument with the AppiumServiceBuilder ?

Kindly use Appium forum to ask questions

**Closed by mykola-mokhnach** 2021-09-06 13:50 UTC

**Comment by StephanB75** [comment] 2021-09-06 13:54
Thx . sorry i have not found that post.
may still helpful if anyone comes to this issue.
Solution for appiumServerBuilder was adding the base-path
builder = new AppiumServiceBuilder().withArgument(() -> "--base-path", "/wd/hub");
