### ISSUE TITLE
Incorrect element co-ordinates in iOS real devices. 

### ISSUE THREAD

**Issue by sabarishnarain** [appium/appium#11362] opened 2018-09-13 18:03 UTC
## The problem

Appium returns incorrect element co-ordinates for the buttons within activitylistview

## Environment

* Appium version : 1.7
* Last Appium version that did not exhibit the issue (if applicable):  Not sure 
* Desktop OS/version used to run Appium: 1.7
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device i iphone 10. IOS 11.4.1. This happens in ipads as well. 

## Details

Note the download button's actual location which is at the bottom of the phone screen, but Appium shows it's co-ordinates as (261,136) corresponding to the blue highlight.

## Code To Reproduce Issue 

I can't share our app. I guess if you try any app that contains the native sharing options such as Message or Mail, it should be fairly reproducible. 

![image](https://user-images.githubusercontent.com/5652384/45506623-6b979700-b755-11e8-87d9-6b852ad9d44c.png)

**Comment by mykola-mokhnach** [comment] 2018-09-13 19:07
Duplicate of https://github.com/appium/appium/issues/11324

**Closed by mykola-mokhnach** 2018-09-13 19:07 UTC

**Comment by sabarishnarain** [comment] 2018-09-14 05:56
It's very strange that these co-ordinates are still shown incorrectly from one of the iPad Pro (iOS 11.4) but the tests does appear to tap on the element during run time. I logged the x,y co-ordinates from my tests and they are the similar to the above snapshot. Though they are incorrect the click is fired at the right element. 

I'm still investigating what's special in this device.

**Comment by mykola-mokhnach** [comment] 2018-09-14 06:04
Element coordinates are not needed to perform the click. Each XCTest element has `hitPoint` property, which is calculated properly for such views even if `frame` coordinates are shifted.

**Comment by sabarishnarain** [comment] 2018-09-14 14:07
Then do you any clue how it works on this particular devices and not anywhere else ?
