### ISSUE TITLE
bug: call to 'switchContext' failed for hybrid application

### ISSUE THREAD

**Issue by diebold2000** [appium/appium#19001] opened 2023-08-18 16:50 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appium Inspector shows loading spinner for a long time and then alert blows up

![switch context failed](https://github.com/appium/appium/assets/7875241/f6f4725d-48ad-41e9-a281-2009786e5513)

### Expected Behavior

Context switched successfully to WEBVIEW and I can see web view screen elements structure in inspector.

### Minimal Reproducible Example

Just use steps
I'm using Appium Inspector.
When I'm on the application screen where webview context expected to be I do:
1. Get contexts list
2. Copy WEBVIEW context ID
3. Set context

### Environment

- Operating system: macOS 13.4 (22F66)
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s): 
  - xcuitest@4.21.29 (automationName 'XCUITest')
  - uiautomator2@2.29.4 (automationName 'UiAutomator2')
- Appium plugin(s) and their version(s):
  - images@2.0.10
  - device-farm@6.0.0
  - appium-dashboard@v2.0.2
  No plugins activated.
- Node.js version (output of `node --version`): v16.13.1
- `npm` version (output of `npm --version`): 8.1.2
- Last component(s) version which did _not_ exhibit the problem: hard to recall but first it was a problem with downloading new chromedriver version 115. Then I've updated appium server and uiautomator2 driver and this issue appeared.
- Platform and version under test: Android 12
- Real device or emulator/simulator: real device Google Pixel 3

### Link to Appium Logs

https://gist.github.com/diebold2000/4b2261ee0da486d5cf70dcb980b100a3

### Further Information

Appium start command

`appium --base-path=/wd/hub --port 4723 --session-override --relaxed-security --log-timestamp --local-timezone`

**Comment by mykola-mokhnach** [comment] 2023-08-18 17:01
This looks like chromedriver issue to me. It just never responds to the session creation request.
Please enable chromedriver logging and attach the updated log, maybe it contains additional details of the cause

**Comment by diebold2000** [comment] 2023-08-18 17:16
Thank you @mykola-mokhnach . Could you please advise how to enable chromedriver logging in inspector?

**Comment by diebold2000** [comment] 2023-08-18 17:40
Nevermind seems I found the flag showChromedriverLog

**Comment by diebold2000** [comment] 2023-08-18 18:57
Here is appium log with chromedriver logs https://gist.github.com/diebold2000/7f06742247e3ab6a4b8e753b422de24d

**Comment by mykola-mokhnach** [comment] 2023-08-18 19:11
It is clearly visible from the log that chromedriver eventually stops and either dies or just freezes without any further output. Please report your issue to Google along with the above log. Btw, have you tried to open this web view using Chrome Remote debugger?

**Comment by diebold2000** [comment] 2023-08-18 19:20
Yep. It work perfectly in DevTools with  Chrome desktop Version 116.0.5845.96 (Official Build) (arm64). Thank you for the help! I'll report it to google then.

**Comment by mykola-mokhnach** [comment] 2023-08-19 16:14
Let us know when there is a response from Google. Closing the issue as third party one for now

**Closed by mykola-mokhnach** 2023-08-19 16:14 UTC
Labels: Mobile Chrome, ThirdParty

**Comment by diebold2000** [comment] 2023-08-21 14:03
Sure. https://bugs.chromium.org/p/chromedriver/issues/detail?id=4547
