### ISSUE TITLE
Getting version with 'getprop ro.build.version.release' raises error 3221226356

### ISSUE THREAD

**Issue by SergeySerj** [appium/appium#12751] opened 2019-06-10 15:45 UTC
## The problem

I'm getting Appium error at session starting:
`[W3C] Encountered internal error running command: Error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\SergeyPolschak\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release' exited with code 3221226356'; Stderr: ''; Code: '3221226356'`

[Similar closed issue](https://github.com/appium/appium/issues/12302)
[Similar closed issue](https://github.com/appium/appium/issues/12736)

Running command directly `adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release` returns:
`9`
Therefore it is not ADB issue, thus I'm creating new issue

## Environment

* Appium version (or git revision) that exhibits the issue: Appium Desktop 1.13.0
* Last Appium version that did not exhibit the issue (if applicable): Appium Desktop 1.12.1
* Desktop OS/version used to run Appium: Windows 10 x64 1803
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: Npm 6.1.0
* Mobile platform/version under test: Android 8.1.0, Android 9.0
* Real device or emulator/simulator: AVD Android Emulator
* Appium CLI or Appium.app|exe: Appium.exe
* ADB: 1.0.41

## Link to Appium logs

[Appium logs](https://gist.github.com/SergeySerj/7d9ec400b0b03335db92559063f99a9e)

**Comment by mykola-mokhnach** [comment] 2019-06-10 17:31
Do you execute adb from the same path as the Appium script (`C:\Users\SergeyPolschak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release`) ?

**Comment by mykola-mokhnach** [comment] 2019-06-11 05:20
Duplicate of https://github.com/appium/appium/issues/12749

**Closed by mykola-mokhnach** 2019-06-11 05:20 UTC
Labels: Android, NeedsInfo, ThirdParty

**Comment by mykola-mokhnach** [comment] 2019-06-11 05:22
https://github.com/appium/appium/issues/12736#issuecomment-500644829

**Comment by SergeySerj** [comment] 2019-06-11 06:49
> Do you execute adb from the same path as the Appium script (`C:\Users\SergeyPolschak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release`) ?

yes, I've updated description including path to ADB.

**Comment by SergeySerj** [comment] 2019-06-11 08:26
was able to resolve the issue by updating SDK tools [details](https://github.com/appium/appium/issues/12736#issuecomment-500738217)
