### ISSUE TITLE
[C#] “Could not find adb please set ANDROID_HOME” only happens using code to start appium server instead of opening appium manually (desktop or commond line) 

### ISSUE THREAD

**Issue by galenyjl** [appium/appium#10342] opened 2018-03-13 02:32 UTC
## The problem

Hi guys,

I have set all path in bash_profile.

export ANDROID_HOME=/Users/xxx/Library/Android/sdk
export JAVA_HOME=$(/usr/libexec/java_home)
export PATH=${JAVA_HOME}/bin:$PATH
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platforms-tools
export PATH=${PATH}:${ANDROID_HOME}/build-tools/27.0.1
export PATH=${PATH}:${JAVA_HOME}

When I open Appium desktop and start the server at first, everything is fine and enable to detect adb device. Also, using the command line like (appium -p 4723) no issues.

However, if I directly run in visual studio without opening appium server at first,

            AppiumServiceBuilder appiumServiceBuilder = new AppiumServiceBuilder()
                .UsingAnyFreePort();

            AppiumLocalService appiumLocalService = appiumServiceBuilder.Build();
            if (!appiumLocalService.IsRunning)
                appiumLocalService.Start();
            DesiredCapabilities capabilities = new DesiredCapabilities();

            capabilities.SetCapability("deviceName", "EM1");
            capabilities.SetCapability("platformVersion", "6.0");
            capabilities.SetCapability("platformName", "Android");
            capabilities.SetCapability("appPackage", "com.thlonline.telme");
            capabilities.SetCapability("appActivity", "com.thlonline.telme.MainActivity");
        
            AndroidDriver<AndroidElement> androidDriver = new AndroidDriver<AndroidElement (appiumLocalService, capabilities);

the error occurs as follows:
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: MAC
* Node.js version (unless using Appium.app|exe): 8.9.1
* Mobile platform/version under test: Android & iOS
* Real device or emulator/simulator: emulator

## Details

I investigated the whole day, looks like in Java needs to set ANDROID_HOME in the IDE, but I don’t know how to do this in visual studio using C#. Please help, many thanks!
## Link to Appium logs

https://gist.github.com/galenyjl/495e66b4dc7abbdc67d9ffcde4d34485

**Comment by galenyjl** [comment] 2018-03-13 03:42
@sah @tanob @admc @hugs @tonetheman

**Comment by mykola-mokhnach** [comment] 2018-03-13 06:31
the problem is that `AppiumServiceBuilder` does not inherit system env for executed Appium process by default. You should set it manually while building the executor. Closed as non-server issue

**Closed by mykola-mokhnach** 2018-03-13 06:31 UTC

**Comment by galenyjl** [comment] 2018-03-13 07:50
@mykola-mokhnach Thanks for your feedback! Could you tell how should I set it manually? Becuase I tried usingDriverExecutable and withAppiumJS, still not working...

**Comment by mykola-mokhnach** [comment] 2018-03-13 07:59
No idea. I know nothing about c sharp.
