### ISSUE TITLE
Can't run tests with espresso driver, because process crashes caused by not found resource ID #0x7f070059

### ISSUE THREAD

**Issue by AndrewMaster** [appium/appium#12644] opened 2019-05-15 13:18 UTC
## The problem

I'm testing an app and I faced an issue that I can't run tests with espresso driver, because process crashes (the app is opened and then immediately closed). I tried to run it on multiply Android versions, from 5 to 9, and on each one tests fail. I have no problem to run these tests with UiAutomator2.

**These are the capabilities I use:**
forceEspressoRebuild: true
platformName: android
app: C:\Users\Lenovo\IdeaProjects\my-test-suite\apps\android\app-test-debug.apk
appActivity: com.test.myapp.StartingActivity
appPackage: app.myApp.test.com.myApp
autoAcceptAlerts: true
autoGrantPermissions: true
automationName: Espresso
deviceName: Android
noReset: false
platformVersion: 8

## Environment

* Appium version (or git revision) that exhibits the issue: v1.13.0-beta.3
* EspressoDriver version: 1.12.3
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: Windows 10 Pro x64
* Node.js version (unless using Appium.app|exe): v10.15.3
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: Android 8
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/AndrewMaster/7a38d03695dd81713c24ea395bdb5252

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2019-05-15 14:31
Duplicate of https://github.com/appium/appium-espresso-driver/issues/449

I don't think there is anything to do there on Appium side. This looks more like an Espresso issue.

**Closed by mykola-mokhnach** 2019-05-15 14:31 UTC
