### ISSUE TITLE
TypeError inside the argparse formatter file

### ISSUE THREAD

**Issue by HeIsIdeus** [appium/appium#10230] opened 2018-02-21 14:28 UTC
## The problem

After running the command < appium doctor > from the command line, I get a TypeError. This is a problem because I know that my installation of Appium is broken and needs to be fixed. I know this is the case because if I type the "appium doctor" command, I need to see there are no problems with my install. 

## Environment

* Appium version (or git revision) that exhibits the issue: **v1.7.2**
* Last Appium version that did not exhibit the issue (if applicable): **Never used Appium before**
* Desktop OS/version used to run Appium: **MacOS High Sierra 10.13.3**
* Node.js version (unless using Appium.app|exe): **v9.5.0**
* Mobile platform/version under test: iOS native / **v11.2**
* Real device or emulator/simulator: **iPhone X**
* Appium CLI or Appium.app|exe: **Appium.app**

## Details

From scratch, I installed v1.7.2 from the command line on my mac. Then ran the "appium doctor" command from the command line. 

## Link to Appium logs

**https://gist.github.com/HeIsIdeus/06b5efe3b560da08b052328ad372afad.js**

## Code To Reproduce Issue [ Good To Have ]

**<npm install -g appium>**

**Comment by mykola-mokhnach** [comment] 2018-02-21 15:00
Duplicate of https://github.com/appium/appium/issues/9529

**Closed by mykola-mokhnach** 2018-02-21 15:00 UTC

**Comment by HeIsIdeus** [comment] 2018-02-21 15:10
@mykola-mokhnach, okay I understand that there is a pull request in from the third party dependency that will fix this issue in the next release. What is the solution for me? Do I uninstall v1.7.2 and downgrade to a later version of Appium, then run that version that's error free until the new release is available? I need to proceed with using Appium for my development.

**Comment by mykola-mokhnach** [comment] 2018-02-21 16:09
try to get appium@beta
