### ISSUE TITLE
ios10 swipe method error

### ISSUE THREAD

**Issue by dengwei729** [appium/appium#7055] opened 2016-10-19 11:41 UTC
public void swipe(int startx, int starty, int endx, int endy, int duration)

endx 所传参数应该是增量
endy 所传参数应该是增量

[HTTP] --> POST /wd/hub/session/97559adb-a894-40d2-9f87-7341aac8d530/touch/perform {"actions":[{"action":"press","options":{"x":187,"y":517}},{"action":"wait","options":{"ms":300}},{"action":"moveTo","options":{"x":187,"y":50}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","option...
[debug] [XCUITest] Executing command 'performTouch'
[JSONWP Proxy] Proxying [POST /uiaTarget/0/dragfromtoforduration] to [POST http://localhost:8100/session/70E712D5-44E1-447B-826F-86A460A555C7/uiaTarget/0/dragfromtoforduration] with body: {"fromX":187,"fromY":517,"toX":374,"toY":567,"duration":0.3}

**Comment by imurchie** [comment] 2016-10-19 15:06
I'm sorry, but what is the problem here?

**Comment by dengwei729** [comment] 2016-10-25 12:17
expected： 
`{"action":"press","options":{"x":187,"y":517}},{"action":"wait","options":{"ms":300}},{"action":"moveTo","options":{"x":187,"y":50}`
actual：
`{"fromX":187,"fromY":517,"toX":374,"toY":567,"duration":0.3}`

topoint is wrong

**Comment by jlipps** [comment] 2016-10-25 22:51
@dengwei729 it looks like it is using relative coordinates. try using relative coordinates instead?

**Comment by mykola-mokhnach** [comment] 2017-02-22 18:32
Please install the recent Appium 1.6.4-beta containing appium-xcuitest-driver v. 2.10.0 or higher and try to reproduce the issue

**Comment by crlsblnc** [comment] 2017-03-31 09:16
Hi, upgraded to 1.6.4-beta.2, including appium-xcuitest-driver@2.25.0, and got similar results:

I'm using Robot Framework _swipe_ keyword:
`Swipe 200 800 200 100 2`

This is what Appium sends to the device:
```
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"y":"800","x":"200"}},{"action":"wait","options":{"ms":"2000"}},{"action":"moveTo","options":{"y":"100","x":"200"}},{"action":"release","options":{}}],"77c76ea8-74fb-47cc-8c1a-286a72fae7b5"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"y":"800","x":"200"})-wait(options={"ms":"2000"})-moveTo(options={"y":"100","x":"200"})-release(options={})
[debug] [XCUITest] Found matching gesture: drag
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8100/session/8A953803-DC86-4714-8E56-DDE434D9264A/wda/dragfromtoforduration] with body: {"fromX":"200","fromY":"800","toX":"200200","toY":"800100","duration":2}
```

The issue is when moveTo calculates the offset: `"toX":"200200","toY":"800100"` instead of `"toX":"200","toY":"100"`

**Comment by mykola-mokhnach** [comment] 2017-03-31 09:20
@crlsblnc It works as designed. Coordinates provided to moveTo methods are expected to be relative to the recent chain point (which means these numbers can also be negative or zeroes).

**Comment by mykola-mokhnach** [comment] 2017-03-31 09:26
@crlsblnc this looks like a bug and will be fixed soon. Can you show the client code, which executes this action?
For now you can try ["mobile: dragFromToForDuration"](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md) as a workaround.

**Comment by crlsblnc** [comment] 2017-03-31 10:17
@mykola-mokhnach thanks! but there is no `swipe down` keyword available in Robot Framework at the moment. I'll need to do some research in the meantime...

**Comment by mykola-mokhnach** [comment] 2017-03-31 11:11
It is not needed. Use **Execute Script** to make it working

**Comment by mykola-mokhnach** [comment] 2017-03-31 11:17
Also, you may workaround the problem if you pass coordinate values explicitly as numbers from RF by enclosing them into curly brackets: 
```
100 -> ${100}
```

**Comment by crlsblnc** [comment] 2017-03-31 11:44
Thank you @mykola-mokhnach I had just workaround the problem by creating a new swipe method and explicitly converting to int the values.

**Closed** 2017-03-31 11:52 UTC
Labels: NeedsTriage
