### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by Rohithnm** [appium/appium#7736] opened 2017-01-24 02:15 UTC
## The problem

If we keep appium for long run with latest version of Appium 1.6.0 after the execution for around 10 hours node or appium server is throwing following error.

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: OS X 10.11
* Node.js version (unless using Appium.app|exe): 7.2.1
* Mobile platform/version under test: iOS 10.1
* Real device or emulator/simulator: Real device iPhone
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Here i am keeping iOS for long run by creating only one session for all 350 test scripts. After execution of 120 test scripts the appium or node is throwing following error and stops the server.

## Link to Appium logs

<--- Last few GCs --->

41072588 ms: Mark-sweep 1397.0 (1455.3) -> 1397.0 (1455.3) MB, 1179.0 / 0 ms [allocation failure] [GC in old space requested].
41073756 ms: Mark-sweep 1397.0 (1455.3) -> 1396.8 (1455.3) MB, 1167.6 / 0 ms [last resort gc].
41074925 ms: Mark-sweep 1396.8 (1455.3) -> 1396.8 (1455.3) MB, 1169.6 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x24a0675e3ac1 <JS Object>
    1: outputHandler [/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-adb/build/lib/logcat.js:~126] [pc=0x1c4d3c5c7e3a] (this=0x3b7cf0b96309 <a Logcat with map 0xd9dadae7d19>,output=0x3498c9028659 <String[54]\: 01-04 21:14:20.361  5655  5681 D sqcNumber: Value: 20\r>)
    2: /* anonymous */ [/Applications/Appium.app/Contents...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

/bin/bash: line 1:  1155 Abort trap: 6           
'/Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js

Kindly waiting for inputs on above issue.

**Comment by mykola-mokhnach** [comment] 2017-01-24 08:56
Duplicate of https://github.com/appium/appium/issues/7731

**Closed by mykola-mokhnach** 2017-01-24 08:56 UTC
Labels: NeedsTriage
