### ISSUE TITLE
Unable to use otherApps Desired Capability with Python Client

### ISSUE THREAD

**Issue by sraheem** [appium/appium#11286] opened 2018-08-30 17:23 UTC
## The problem

The app I’m testing requires a 2 other apps to be installed before I can run my test. Therefore I’m trying to use the ‘otherApps’ desired capability the prerequisite apps installed.

I have tried various formats to specify a JSON array, but I get different errors. I think this might be a bug in the python client.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium Desktop 1.6.2
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): n/a
* Mobile platform/version under test: Android 5.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.exe (Appium Desktop v1.6.2)

## Code/Log snippets
```
desired_caps['otherApps'] = ["C:\\Users\\sraheem\\Downloads\\ttm-backbone.apk", "C:\\Users\\sraheem\\Downloads\\service-debug.apk"]

Message: 'otherApps' must be of type string
```

```
desired_caps['otherApps'] = "["C:\\Users\\sraheem\\Downloads\\ttm-backbone.apk", "C:\\Users\\sraheem\\Downloads\\service-debug.apk"]"

SyntaxError: invalid syntax
```

```
desired_caps['otherApps'] = "[\"C:\\Users\\sraheem\\Downloads\\ttm-backbone.apk\", \"C:\\Users\\sraheem\\Downloads\\service-debug.apk\"]"

...Original error: The application at '["C:\Users\sraheem\Downloads\ttm-backbone.apk", "C:\Users\sraheem\Downloads\service-debug.apk"]' does not exist or is not accessible
```

**Comment by mykola-mokhnach** [comment] 2018-08-30 18:26
Closed as duplicate of https://github.com/appium/appium/issues/10592

**Closed by mykola-mokhnach** 2018-08-30 18:26 UTC
