### ISSUE TITLE
Appium gets killed on openapplication

### ISSUE THREAD

**Issue by aryalakshmi** [appium/appium#13117] opened 2019-08-25 15:27 UTC
## The problem

Appium is getting killed during open application

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0-beta.2
* Last Appium version that did not exhibit the issue (if applicable): 1.13
* Desktop OS/version used to run Appium: macOS Mojave 10.14.5
* Node.js version (unless using Appium.app|exe):v12.1.0
* Npm or Yarn package manager:6.9.0
* Mobile platform/version under test:iOS
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: CLI

## Details

Appium is getting killed on openapplication
Observing xcode build failed with 75 error
Using iPad Air with iOS version 12.3
XCODE 10.3

## Link to Appium logs

https://gist.github.com/aryalakshmi/53f47897247ffd9b8805d3d95e0f84a4

**Comment by mykola-mokhnach** [comment] 2019-08-25 16:38
Detailed xcodebuild log can be enabled by `showXcodeLog` capability. Also, it is necessary to make sure the 8100 port is not used by any other processes.

**Comment by mykola-mokhnach** [comment] 2019-08-27 07:48
Duplicate of https://github.com/appium/appium/issues/13127

**Closed by mykola-mokhnach** 2019-08-27 07:48 UTC
Labels: NeedsInfo
