### ISSUE TITLE
Python binding element.is_displayed returns False for element that is displayed

### ISSUE THREAD

**Issue by gergm** [appium/appium#10644] opened 2018-05-03 22:50 UTC
## The problem

The method element.is_displayed returns False when the element is actually displayed. Note that this issue occurs with appium V1.8.0, but not with appium V1.7.2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: macOS High Sierra V 10.13.4
* Node.js version (unless using Appium.app|exe): V8.2.1
* Mobile platform/version under test: iPhone 7, iOS 11.1, Xcode V9.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details

Its just a simple call to WebElement.is_displayed()

## Link to Appium logs

https://gist.github.com/gergm/7424611dfb8d28779c242e6d0cebf419

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2018-05-04 05:10
Duplicate of https://github.com/facebook/WebDriverAgent/issues/914

**Closed by mykola-mokhnach** 2018-05-04 05:10 UTC
