### ISSUE TITLE
Appium 1.17.1 doesn't display all the elements.

### ISSUE THREAD

**Issue by leighannag** [appium/appium#14467] opened 2020-06-18 23:16 UTC
This issue may be an issue with my devs but I need to check this isn't an Appium issue to cover my bases.

I've worked on a project that has a search feature. I've noticed that since I've update Appium, I haven't been able to view all of the elements on the search's results page anymore. I can't see anything for any result... nothing but a few windows. This might be an Appium issue because I can use the "Search for Element" and find elements using IDs, names, etc. I can also run old automation tests and they are able to interact with elements I can't see in the page source. So the web elements are available and Appium can see them and interact with them, but for some reason I can't access it through the page source tree in the inspector. 

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.17.1
* Last Appium version that did not exhibit the issue (if applicable): Appium 1.15.1
* Desktop OS/version used to run Appium: Mac OS Catalina (10.15.4)
* Node.js version (unless using Appium.app|exe): v12.13.0
* Npm or Yarn package manager: 6.12.0
* Mobile platform/version under test: iOS 13.4
* Real device or emulator/simulator: iPhone 11 (sim)
* Appium CLI or Appium.app|exe: I think Appium.app

## Details

I'm not sure if this necessary, but for the search result page, this is the furthest element:

//XCUIElementTypeApplication[@name="Project"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther[1]

As you can see, it doesn't go that far. If I clear the search results and "refresh the source & screenshot" for this page, it shows more than that. It shows web elements for the search bar, button, the empty space where the search results would be. It's just the results page that I cannot see all of the elements.

## Link to Appium logs

I'm not sure if logs are necessary since there were no error messages, but I will post if necessary.

Let me know if I need to add anything to this post.

**Comment by KazuCocoa** [comment] 2020-06-19 00:51
Please attach the full server log as GIST since it helps us to understand the situation.
And page source in 1.15.1 and 1.17.1 are also helpful.

**Comment by mykola-mokhnach** [comment] 2020-06-19 06:25
Could be a duplicate of https://github.com/appium/appium/issues/6517

**Comment by lukeyoui** [comment] 2020-06-19 16:08
To add on to this thread with more information, I was also able to reproduce this issue. 

I was able to isolate the issue to the 1.17.1 inspector (not the server), as I was able to use the bundled server from the 1.17.1 desktop app with an older inspector (1.15.1) and there were no visible issues.

If this is indeed a unique issue I will log a ticket [here](https://github.com/appium/appium-desktop/issues) for visibility. I will attempt to reproduce this issue later with my own server to attach logs if none are provided.

**Comment by leighannag** [comment] 2020-06-20 08:03
Sorry for the delay. Here's the gist: https://gist.github.com/leighannag/d163420efff6beb510acd177d20f508f

I can provide a page source for 1.17.1 tomorrow, but whenever I try to use 1.15.1, I get an error trying to start the app up using the inspector.

**Comment by leighannag** [comment] 2020-06-22 15:40
Again sorry for the delay. Had to check with my manager. I can't show you the full Appium inspector window, but I hope this will suffice. 
![Screen Shot 2020-06-22 at 8 35 49 AM](https://user-images.githubusercontent.com/39280612/85306889-fa296400-b463-11ea-85c4-38bad3af8a35.png)

**Comment by leighannag** [comment] 2020-06-23 19:47
I was able to get Appium 1.15.1 to work so here's the screenshot of the page source.
![Screen Shot 2020-06-23 at 12 44 59 PM](https://user-images.githubusercontent.com/39280612/85452330-a09e6380-b54f-11ea-9a1d-8741171fc257.png)

**Comment by KazuCocoa** [comment] 2020-06-24 02:21
Is there any differences `mobile:source, {format: 'description'}`?
https://appium.io/docs/en/commands/mobile-command/
The mobile command work for both 1.15 and 1.17

**Comment by dmitriy-ardelyan** [comment] 2020-06-24 11:06
Hi there, having the same problem on 1.17, could anyone please hand me the link to a third party issue which caused this problem (want to track progress if it is possible)? 
Maybe anyone knows working workaround?

**Comment by leighannag** [comment] 2020-06-24 16:04
@KazuCocoa I'm not sure what you're asking.

**Comment by KazuCocoa** [comment] 2020-06-24 17:09
The mobile:source command returns low debug description data by xctest framework. So, I meant if the low data had differences.

**Comment by KazuCocoa** [comment] 2020-06-25 00:44
Another possible idea is https://github.com/appium/appium-desktop/issues/1199#issuecomment-646952738

**Comment by ajling** [comment] 2020-06-25 07:46
I've also been getting this issue in both v1.17 and v1.17.1 of Appium Desktop. Here is the link for my gist with server logs from both versions: https://gist.github.com/ajling/d1ea2a683a5e156db50c87bdcdb7c892

I'm using Appium Desktop v1.17.1, running my app on an iPhone 8 Plus simulator - unfortunately I'm not able to provide code / the app.

Looking at some of the logs I can actually see some of the ID's I'm expecting - i.e. [com.apple.dt.xctest:Default] StaticText, identifier: 'TimeSlotLabelId' is not actually a child of Other, including at this point anyway (rdar://problem/20738636)

Hope this can get solved as I'm at a standstill with my automated testing on iOS

**Comment by leighannag** [comment] 2020-06-25 15:42
@KazuCocoa I'm not sure how that is related to Appium's Inspector issues. If I'm using the same app build, why would one version of Appium return different Page Source than another version of Appium? I'm sorry, I don't know anything about mobile:source and the current Appium version we're using to run the tests are Appium 1.15.1, so I suspect running that in my test will return what I've posted above.

**Comment by KazuCocoa** [comment] 2020-06-25 17:21
Ah, I read the above comments again, and maybe I misunderstood.

>  If I clear the search results and "refresh the source & screenshot" for this page, it shows more than that. It shows web elements for the search bar, button, the empty space where the search results would be. It's just the results page that I cannot see all of the elements.

Web Elements did not appear on the inspector first, but once you reloaded the view again, then they appeared.

Inspector's data depends on the page source result by Appium server. So, I guess the timing to get the source was early.
If it was something WebInspector and newer Appium's logic stuff behind Appium server, increasing `webviewConnectTimeout` capability might help. https://github.com/appium/appium-xcuitest-driver

**Comment by leighannag** [comment] 2020-06-25 22:55
@KazuCocoa 
Lemme try again.

Steps:
1. Go to the search page before a search is executed.
2. Grab a screenshot to look at the elements in Appium's Inspector -- the elements for search bar and what not are there.
3. Execute a search.
4. Grab a screenshot to look at the elements in Appium's Inspector -- the elements look like the screenshot I provided for Appium 1.17.1

**Comment by KazuCocoa** [comment] 2020-06-26 00:57
https://github.com/appium/WebDriverAgent/pull/357 may be related to. https://github.com/appium/appium/issues/14486#issuecomment-649842693
If this change fixes your issue, I guess it was timing issue when XCTest framework resolve the view elements.

**Comment by ajling** [comment] 2020-06-26 14:37
> [appium/WebDriverAgent#357](https://github.com/appium/WebDriverAgent/pull/357) may be related to. [#14486 (comment)](https://github.com/appium/appium/issues/14486#issuecomment-649842693)
> If this change fixes your issue, I guess it was timing issue when XCTest framework resolve the view elements.

Hi @KazuCocoa 
Thanks for replying with that info. I've done a build of that branch and managed to get it deploying on the emulator, however when I do a POST to the settings and then call the GET I don't see that setting 'boundElementsByIndex'. After doing this there is no change to the inspector but maybe its due to the setting not being applied...

Just in case I've missed something this is the info on the session from Appium and also the POST I made to that session of Appium.

**Appium Status:**
{
  "value" : {
    "message" : "WebDriverAgent is ready to accept commands",
    "state" : "success",
    "os" : {
      "testmanagerdVersion" : 28,
      "name" : "iOS",
      "sdkVersion" : "13.4",
      "version" : "13.2.2"
    },
    "ios" : {
      "simulatorVersion" : "13.2.2",
      "ip" : "192.168.1.224"
    },
    "ready" : true,
    "build" : {
      "upgradedAt" : "1593081282088",
      "time" : "Jun 26 2020 13:07:35",
      "productBundleIdentifier" : "com.facebook.WebDriverAgentRunner"
    }
  },
  "sessionId" : "508DF0FE-F4B6-4A23-BF85-80C838432A1B"
}

**Appium Settings:**
{
  "value" : {
    "screenshotOrientation" : "auto",
    "shouldUseCompactResponses" : true,
    "mjpegServerFramerate" : 10,
    "snapshotMaxDepth" : 50,
    "activeAppDetectionPoint" : "64.00,64.00",
    "acceptAlertButtonSelector" : "",
    "snapshotTimeout" : 15,
    "elementResponseAttributes" : "type,label",
    "keyboardPrediction" : 0,
    "screenshotQuality" : 1,
    "keyboardAutocorrection" : 0,
    "useFirstMatch" : false,
    "reduceMotion" : false,
    "defaultActiveApplication" : "auto",
    "mjpegScalingFactor" : 100,
    "mjpegServerScreenshotQuality" : 25,
    "dismissAlertButtonSelector" : "",
    "includeNonModalElements" : false
  },
  "sessionId" : "508DF0FE-F4B6-4A23-BF85-80C838432A1B"
}

**POST Request to the settings for Appium:**

http://localhost:8100/session/508DF0FE-F4B6-4A23-BF85-80C838432A1B/appium/settings

**Headers & Body:**
Accept: */*
Accept-Encoding: gzip, deflate
Content-Type: text/plain
Accept-Language: en-gb

{
  settings: {
   boundElementsByIndex : true
  }
}

Response was a 200 and the settings returned are the same as above.

Thanks

**Comment by KazuCocoa** [comment] 2020-06-26 15:04
hm, thanks.
If you can manually modify your WDA, simply you can switch `allElementsBoundByAccessibilityElement` with `allElementsBoundByIndex` by manual on Xcode. https://github.com/appium/WebDriverAgent/pull/357
It is easier than calling update settings for just checking.

**Comment by ajling** [comment] 2020-06-26 15:06
> hm, thanks.
> If you can manually modify your WDA, simply you can switch `allElementsBoundByAccessibilityElement` with `allElementsBoundByIndex` by manual on Xcode. [appium/WebDriverAgent#357](https://github.com/appium/WebDriverAgent/pull/357)
> It is easier than calling update settings for just checking.

Thanks @KazuCocoa will give it a try now

**Comment by leighannag** [comment] 2020-06-26 15:40
@KazuCocoa What change? Change in Appium or a change I'd have to do manually?

**Comment by ajling** [comment] 2020-06-26 16:26
@leighannag it would be a manual change in WebDriverAgent project.

@KazuCocoa I've given that a try and while other areas of my app are fine, the one page I'm having issues with is still the same.

**Comment by mykola-mokhnach** [comment] 2020-06-29 19:56
Duplicate of https://github.com/appium/appium/issues/13958

**Closed by mykola-mokhnach** 2020-06-29 19:56 UTC
Labels: ThirdParty, XCUITest

**Comment by ganjarpanji** [comment] 2020-09-29 08:54
Im out of topic, hi @leighannag just curious how you named all of those element on the app? is it manually for every element using `.accessiiblitIdentifier="blabalba"` or is there any mechanism how your dev could do it automatically? thanks

> I was able to get Appium 1.15.1 to work so here's the screenshot of the page source.
> ![Screen Shot 2020-06-23 at 12 44 59 PM](https://user-images.githubusercontent.com/39280612/85452330-a09e6380-b54f-11ea-9a1d-8741171fc257.png)
> 
> It seems like Appium 1.17.1 isn't finding the first window that contains all of these elements.

**Comment by ddubtsov35** [comment] 2021-07-21 12:36
> Есть ли отличия `mobile:source, {format: 'description'}`?
> https://appium.io/docs/en/commands/mobile-command/
> Мобильная команда работает как для версии 1.15, так и для версии 1.17.

@KazuCocoa 
Hello! 
I have this problem on the Appium 1.21.0
Element XCUIElementWebView don't have inner elements in Appium Desktop Inspector, but if i execute mobile:source, then elements exists. Also inner element find with the help "Search for element"
Desired capability "snapshotMaxDepth = 1500" don't help

**Comment by samiaAcodad** [comment] 2023-01-04 09:51
I have the same issue Appium can't reach elements in iOS source tree, they are too deep. it Works fine in android
I added desired capability {"snapshotMaxDepth" :600} but still have the same problem 
any one can help.?
