### ISSUE TITLE
Cannot run java automation tests on android “Cannot call non W3C standard command while in W3C mode”

### ISSUE THREAD

**Issue by getloud** [appium/appium#13440] opened 2019-10-17 06:29 UTC
Env:

Appium - v1.15.1
Chromedriver - 77.0.3865.40
appium/java-client - '7.2.0',
testngVersion - '6.14.3',
selenideVersion - '5.3.1',
Chrome - 77.0.3865.116
Android - 10

When I run my tests I get next exception:

 ` java.lang.IllegalArgumentException: org.openqa.selenium.UnsupportedCommandException: unknown command: Cannot call non W3C standard command while in W3C mode`

Can someone help me please?

**Comment by mykola-mokhnach** [comment] 2019-10-17 06:53
Duplicate of https://github.com/appium/java-client/issues/1242

**Closed by mykola-mokhnach** 2019-10-17 06:53 UTC
