### ISSUE TITLE
driver.close_app() or driver.quit() does not work in IOS Appium 1.22.0

### ISSUE THREAD

**Issue by MummanaSubramanya** [appium/appium#16140] opened 2021-11-20 10:51 UTC
## The problem

Im trying to close app using driver.close_app but it doesnt work anymore. 

driver.terminate_app('com.apple.Preferences') works fine but it uninstalls webdriveragent everytime.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS15.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

I was using the below code

1) suite setup --> driver = IOSDriver(url, desiredCapabilities);
2) Test setup --> self.driver.launch_app()
3) Test teardown --> self.driver.close_app()
4) Suite teardown --> --> self.driver.quit()

**Comment by mykola-mokhnach** [comment] 2021-11-20 14:00
Please provide the full server log. 

launch_app and close_app methods are deprecated and won't be supported. See https://github.com/appium/appium/issues/15807 for more details.

Possible duplicate of https://github.com/appium/appium/issues/15958. Basically, version 1.22 got a bugfix which only terminates an application under test on test termination if this particular app was executed by this test. If one starts an app using mobile extensions then it is expected then the app lifecycle must also be managed in a custom manner.

**Comment by MummanaSubramanya** [comment] 2021-11-21 18:05
> Please provide the full server log.
> 
> launch_app and close_app methods are deprecated and won't be supported. See #15807 for more details.
> 
> Possible duplicate of #15958. Basically, version 1.22 got a bugfix which only terminates an application under test on test termination if this particular app was executed by this test (e.g. by session capabilities). If one starts an app using mobile extensions then it is expected that the app lifecycle must also be managed in a custom manner.

Thanks for the info.  I followed the suggestion of terminating the app even with noReset set to true, set appium:shouldTerminateApp to true as well works fine but sometimes my tests are failing.
please find the gist https://gist.github.com/MummanaSubramanya/a2e8abb3b969d14903c7dc4c5f8b3a38

Exception: WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100 Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

**Comment by mykola-mokhnach** [comment] 2021-11-21 18:10
I don't observe any explicit issues in the attached log. Make sure sessions are managed properly from the client code (e.g. a new session is created before each test and is properly quit in test teardown)

**Comment by MummanaSubramanya** [comment] 2021-11-21 18:52
Im simply creating new driver session before every test with below capabilties 
{
  "platformName": "iOS",
  "appium:platformVersion": "15.0",
  "appium:deviceName": "iPhoneXr",
  "appium:automationName": "XCUITest",
  "appium:app": "/Users/mummana/Document/test_app_react.ipa",
  "appium:udid": "XXXXXXXXXXXXX,
  "appium:noReset": true,
  "shouldTerminateApp": true
}

and since Im using "shouldTerminateApp": true, I'm not doing anything in after test. Please let me know if Im missign anything here?

**Comment by mykola-mokhnach** [comment] 2021-11-21 21:47
I don't know what else to advice based on the provided information. Don't see any server issues there though

**Comment by KazuCocoa** [comment] 2021-11-22 08:39
What about the entire appium server log?
https://github.com/appium/appium/issues/16140#issuecomment-974865698 was partial one.

**Comment by MummanaSubramanya** [comment] 2021-11-22 09:39
let me share the latest logs

**Comment by MummanaSubramanya** [comment] 2021-11-22 10:03
https://gist.github.com/MummanaSubramanya/25bb2177f3189cc8779d40a02d10e9d6 here is the complete log.

You can see line number 4470 in the gist and I end up with below exception--
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100 Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

**Comment by mykola-mokhnach** [comment] 2021-11-22 16:52
> [warn] [35m[DevCon Factory][39m Port #8100 is busy. Did you quit the previous driver session(s) properly?

Once again, make sure the session management is set up properly in the client code

**Comment by KazuCocoa** [comment] 2021-11-23 09:10
Yea, the attached log had the below lines.
It means as the above comment, the previous session (d66dd868-31a5-4ebe-b039-b9ec89f4096e) kept running, but the next new session request tried to create a new session with the same ports (8100 etc).
```
[debug] [35m[WD Proxy][39m Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/277F7DE3-617C-4CDF-99F2-B1DF9D84D780/elements] with body: {"using":"accessibility id","value":"bottom-tab-tasks"}
[error] [35m[Xcode][39m     t =   103.35s     Find: Descendants matching type Any
[error] [35m[Xcode][39m     t =   103.35s     Find: Elements matching predicate 'elementType IN {7, 5, 46}'
[error] [35m[Xcode][39m 2021-11-22 15:19:18.321362+0530 WebDriverAgentRunner-Runner[8763:1769592] Getting the most recent active application (out of 1 total items)
[error] [35m[Xcode][39m     t =   103.36s Get all elements bound by accessibility element for: Elements matching predicate 'wdName == "bottom-tab-tasks" AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0 OR selected == 0)'
[error] [35m[Xcode][39m     t =   103.36s     Requesting snapshot of accessibility hierarchy for app with pid 8774
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m     t =   103.42s     Find: Descendants matching type Any
[error] [35m[Xcode][39m     t =   103.42s     Find: Elements matching predicate 'wdName == "bottom-tab-tasks" AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0 OR selected == 0)'
[error] [35m[Xcode][39m 
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":[],"sessionId":"277F7DE3-617C-4CDF-99F2-B1DF9D84D780"}
[debug] [35m[MJSONWP (d66dd868)][39m Responding to client with driver.findElements() result: []
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/d66dd868-31a5-4ebe-b039-b9ec89f4096e/elements [39m[32m200[39m [90m88 ms - 74[39m
[info] [35m[HTTP][39m [90m[39m
[debug] [35m[HTTP][39m Request idempotency key: a1d3f5b4-857a-4989-b5a0-9261533e1d24
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"capabilities":{"firstMatch":[{"platformName":"iOS","appium:platformVersion":"15.0","appium:deviceName":"iPhoneXr","appium:app":"/Users/mummana/Documents/RFWProjects/leonard247-auto-tests/Apps/Leonardo247.ipa","appium:udid":"00008020-0006115A3EDA002E","appium:bundleId":"","appium:automationName":"XCUITest","appium:noReset":"True","appium:autoAcceptAlerts":"True","appium:shouldTerminateApp":"True"}]},"desiredCapabilities":{"platformName":"iOS","platformVersion":"15.0","deviceName":"iPhoneXr","app":"/Users/mummana/Documents/RFWProjects/leonard247-auto-tests/Apps/Leonardo247.ipa","udid":"00008020-0006115A3EDA002E","bundleId":"","automationName":"XCUITest","noReset":"True","autoAcceptAlerts":"True","shouldTerminateApp":"True"}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","platformVersion":"15.0","deviceName":"iPhoneXr","app":"/Users/mummana/Documents/RFWProjects/leonard247-auto-tests/Apps/Leonardo247.ipa","udid":"00008020-0006115A3EDA002E","bundleId":"","automationName":"XCUITest","noReset":"True","autoAcceptAlerts":"True","shouldTerminateApp":"True"},null,{"firstMatch":[{"platformName":"iOS","appium:platformVersion":"15.0","appium:deviceName":"iPhoneXr","appium:app":"/Users/mummana/Documents/RFWProjects/leonard247-auto-tests/Apps/Leonardo247.ipa","appium:udid":"00008020-0006115A3EDA002E","appium:bundleId":"","appium:automationName":"XCUITest","appium:noReset":"True","appium:autoAcceptAlerts":"True","appium:shouldTerminateApp":"True"}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1637574480468 (10:48:00 GMT+0100 (Central European Standard Time))
[info] [35m[Appium][39m Could not parse W3C capabilities: 'noReset' must be of type boolean
[info] [35m[Appium][39m Trying to fix W3C capabilities by merging them with JSONWP caps
[warn] [35m[BaseDriver][39m The following capabilities are not standard capabilities and should have an extension prefix:
[warn] [35m[BaseDriver][39m   platformVersion
```

**Comment by jlipps** [comment] 2021-11-23 18:32
what @mykola-mokhnach means is you should still be calling `driver.quit()` after each test. it doesn't matter than you have terminate app set to true. that is talking about the app, not the session. sessions should be cleaned up by your test code.

**Comment by mykola-mokhnach** [comment] 2021-11-25 15:40
Closed as not an issue

**Closed by mykola-mokhnach** 2021-11-25 15:40 UTC
Labels: NotABug, NeedsInfo
