### ISSUE TITLE
fail to create wda session

### ISSUE THREAD

**Issue by robin-xl** [appium/appium#11397] opened 2018-09-21 05:18 UTC
## The problem

can not create wda session 

## Environment

* Appium version (or git revision) that exhibits the issue:1.9.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:mojave
* Node.js version (unless using Appium.app|exe):8.11.2
* Mobile platform/version under test:ios 12
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:

## Link to Appium logs

[appium log](https://gist.github.com/robin-xl/43467d80547a677ab053ad952114d3d4)

**Comment by mykola-mokhnach** [comment] 2018-09-21 05:29
Duplicate of https://github.com/facebook/WebDriverAgent/issues/993#issuecomment-423397008

**Closed by mykola-mokhnach** 2018-09-21 05:29 UTC
