### ISSUE TITLE
 element located successfully in Appium Inspector, but the same element not found from the code

### ISSUE THREAD

**Issue by dipakkumar1225** [appium/appium#17213] opened 2022-07-15 13:53 UTC
## The problem

Successfully able to locate element in Appium Inspector, but same locator giving issue from code.
Locator Type: uiAutomator 

![image](https://user-images.githubusercontent.com/46619348/179236802-c4c65949-b5b1-4f75-b6c4-fbbd49994cad.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v14.18.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Moto G20 fusion  Android 11
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

Using Appium java-client : 8.1.1

Android Driver Inililization
```
UiAutomator2Options uiAutomator2Options = new UiAutomator2Options()
			.setAutomationName(AutomationName.ANDROID_UIAUTOMATOR2)
			.clearSystemFiles()
			.clearDeviceLogsOnStart()
			.setFullReset(false)
			.setNoReset(true)
			.autoGrantPermissions()
			.setUdid(params.getUDID())
			.setDeviceName(params.getDeviceName())
			.setPlatformName(params.getPlatformName())
			.showChromedriverLog()
			.setSystemPort(Integer.parseInt(params.getSystemPort()))
			.setChromedriverPort(Integer.parseInt(params.getChromeDriverPort()))
			.setApp(new File(configurationProperties.appAndroidApkFilePath()).getAbsolutePath())
			.setAppPackage(strPackageName)
			.setAppActivity(strLauncherActivityName)
			.setAppWaitActivity("*")
			.setAppWaitForLaunch(true)
			.setNewCommandTimeout(Duration.ofSeconds(200));
uiAutomator2Options.setCapability(AndroidMobileCapabilityType.UNICODE_KEYBOARD, true);
uiAutomator2Options.setCapability(AndroidMobileCapabilityType.RESET_KEYBOARD, true);
try {
	driver = new AndroidDriver(new AppiumServerManager().getServer().getUrl(), uiAutomator2Options);
} catch (Exception e) {
	e.printStackTrace();
}
driver.setSetting(Setting.IGNORE_UNIMPORTANT_VIEWS, true);
driver.setSetting(Setting.WAIT_FOR_SELECTOR_TIMEOUT, 120000);
driver.setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, 0);
```
Locator used : uiAutomator 
```
@AndroidFindBy(uiAutomator = "new UiSelector().resourceId(\"com.app.uat:id/cvLimit\").childSelector(new UiSelector().className(\"android.view.View\"))")
private WebElement webElement;

public void doClick(){
       driver.setSetting(Setting.IGNORE_UNIMPORTANT_VIEWS, false); // I tried this, but still element not found
        webElement.click();
    }
```

## Link to Appium logs  when element located in  Inspector
https://gist.github.com/dipakkumar1225/57c40877b3db344afc5f871cf9337f0f

## Link to Appium logs when code executed
https://gist.github.com/dipakkumar1225/d0594c7b7f4ae6664fd0ed6b94f75522

**Comment by mykola-mokhnach** [comment] 2022-07-15 16:06
> driver.setSetting(Setting.IGNORE_UNIMPORTANT_VIEWS, false);

Try to disable it completely for the whole session.

In general if an element is not found then it is up to UiAutomator. We cannot influence that process. You could also print the page source before the lookup is done to make sure the destination element is there.

**Comment by dipakkumar1225** [comment] 2022-07-16 05:10
Today when I executed the same script, element now located successfully from code too.

**Comment by mykola-mokhnach** [comment] 2022-07-19 06:07
Closed as third party issue

**Closed by mykola-mokhnach** 2022-07-19 06:07 UTC
Labels: ThirdParty, UIAutomator2, NeedsInfo

**Comment by olivia2046** [comment] 2023-02-12 02:20
> Today when I executed the same script, element now located successfully from code too.

Hello Deepak, did you encounter this issue again? I have the same issue. Element can be found in Appium Inspector(and in page source), but not found by code using Appium(neither in page source). Both using default UIAutomator2.
Besides, I tested on 3 local devices. On Samsung S9/Android 10, Vivo X30/Android 10 the code runs fine. On Redmi K50/Android 13 I have this issue. And on cloud provider(browserstack, lambdatest) I have this issue(only on one device I tested on Lambdatest the code sometimes runs fine)

**Comment by olivia2046** [comment] 2023-02-12 02:29
And I've tried to debug code and attach to the session of code in appium inspector, when using 'search for element' function, the element cannot be found(while using the function in session initiated by Appium Inspector, they can be found)

**Comment by pandabat** [comment] 2023-03-06 20:59
I am seeing something similar with Appium 1.22.3 on an Android 13 device (a non-consumer device running Android 13 based on the x86 project). We are running our tests on Appium using robotframework-appiumlibrary. I can use the Appium Inspector and see the elements within the app (e.g. com.company.appname:id/buttonName), and if we log the source from the app then we can see these elements listed in the page's XML but, for some reason, Appium/UIAutomator2 appears to be intermittently unable to see/find these elements in native context. It doesn't happen every time - sometimes all the tests pass, sometimes they fail but rarely in the same place twice. We did not have this issue on the same device in Android 11, only since the recent upgrade to Android 13. It is interesting to note that you also only see the issue on Android 13 @olivia2046

**Comment by PraveenHalhalli9** [comment] 2024-04-05 16:08
I get below exception when i am using with Java client 7.6 and selenium 3.14

Caused by: java.lang.UnsupportedOperationException: setSettings command with settings {waitForIdleTimeout=100} is not supported

**Comment by dipakkumar1225** [comment] 2024-04-11 13:32
Yes still the issue exists

**Comment by joshua-strickland** [comment] 2024-04-25 23:53
Hey there, I was running into this same thing.

I was able to finally get resource ID to work, but I needed up to date versions of both the appium clients & server.

When appium server is 2.4.1 & java client is 9.2.2 the following snippet allows resource IDs to be found

`val options: UiAutomator2Options = UiAutomator2Options()
            .setApp("bs://f4c726b5af015bdc95f66ff1b9ce3cdb3e63f984")
            .setPlatformVersion("12.0")
            .setDeviceName("Google Pixel 6")
            .amend("disableIdLocatorAutocompletion", true)
            .amend("bstack:options",browserstackOptions)`

**Comment by Raushan-kumar-yadav** [comment] 2025-02-05 05:40
Still encountering same issue . when i run the code something it's able to find element and sometimes it's give error 'no such element found' does anyone have solutions 

Please help

**Comment by Ervin202** [comment] 2025-06-03 20:24
Same issue encountered, sometimes my test is passed 10 times and sometimes got failed one time after 10 times. Moreover in appium inspector i cannot find Element then restarting the appium inspector 1-2-3 times and then I able to find locator. Do you have anyone good solution for it?
Also tried retry mechanism with different locator strategies but sometimes nothing found.
