### ISSUE TITLE
UI.ClearText() is not working 

### ISSUE THREAD

**Issue by emreaksoy92** [appium/appium#11811] opened 2018-12-11 11:34 UTC
## The problem

Apparently UI.ClearText() function is not working properly, when i try to send values of ("2022") with sendKeys() function, Appium takes the previous value of the cell which is ("2018"), append it to the new text and send new value ("20182022"). I use the Clear() function, but it shows no effect on appium.

## Link to Appium logs

https://gist.github.com/emreaksoy92/97db3eb34fb06a32c4e77058425a7b36

## Code To Reproduce Issue

[FindsBy(How = How.XPath, Using = "//*[@class='android.widget.NumberPicker' and @index='1']//*[@class='android.widget.EditText' and @index='1']")]
public IWebElement mobile_numberpicker1 { get; set; }

mobile_numberpicker1.Clear();
mobile_numberpicker1.SendKeys("2022");

## Environment

* Appium serve version v1.10.0
* Appium framework 4.0.0.4-beta
* Samsung S9 with Android v8.0.0

**Comment by mykola-mokhnach** [comment] 2018-12-11 12:19
Duplicate of https://github.com/appium/appium/issues/11805
UIA1 is not expected to work properly on newer Android versions.

**Closed by mykola-mokhnach** 2018-12-11 12:19 UTC
