### ISSUE TITLE
org.openqa.selenium.UnsupportedCommandException: Method is not implemented

### ISSUE THREAD

**Issue by Akhila666** [appium/appium#13793] opened 2020-01-04 06:25 UTC
Hi All I am new to appium . 
i am facing issue in get attribute method . it is showing error like Method is not implemented. 
can any one help me .. please ...

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: linex 
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:7.1.1
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: 1.15.1

**Comment by mykola-mokhnach** [comment] 2020-01-04 10:39
Please provide the full server log

**Comment by Akhila666** [comment] 2020-01-04 12:33
hi mykola,
please find below log. 

org.openqa.selenium.UnsupportedCommandException: Method is not implemented
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'revaladm-ThinkCentre-M72e', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-72-generic', java.version: '11.0.5'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {Reset: false, appActivity: com.revalsys.vst.MainActivity, appPackage: com.revalsys.vst, browserName: , databaseEnabled: false, desired: {Reset: false, appActivity: com.revalsys.vst.MainActivity, appPackage: com.revalsys.vst, browserName: , deviceName: 192.168.57.101, platformName: android, platformVersion: 7.1.1}, deviceApiLevel: 25, deviceManufacturer: Genymotion, deviceModel: Custom Phone, deviceName: 192.168.57.101:5555, deviceScreenDensity: 320, deviceScreenSize: 768x1280, deviceUDID: 192.168.57.101:5555, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2, platform: LINUX, platformName: LINUX, platformVersion: 7.1.1, statBarHeight: 48, takesScreenshot: true, viewportRect: {height: 1136, left: 0, top: 48, width: 768}, warnings: {}, webStorageEnabled: false}
Session ID: 54886140-abfd-4911-872c-22e0d8779365
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
	at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:326)
	at uiEntireFlow.Forgotpassword.forgotpassword(Forgotpassword.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

**Comment by mykola-mokhnach** [comment] 2020-01-04 12:34
This is the client exception stack trace. I'd like to see the Appium server log

**Comment by Akhila666** [comment] 2020-01-04 13:02
Hi mykola, 

Please find below appium server log .

[HTTP] --> POST /wd/hub/session/f15d7601-4f93-4e48-b9ae-b8693adc55ee/element
[HTTP] {"value":"//*[@content-desc='YTD SS (CFC)']/following::android.view.View[1]","using":"xpath"}
[W3C (f15d7601)] Calling AppiumDriver.findElement() with args: ["xpath","//*[@content-desc='YTD SS (CFC)']/following::android.view.View[1]","f15d7601-4f93-4e48-b9ae-b8693adc55ee"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8222/wd/hub/session/39b5a19c-2ce4-4971-bcb5-ccc96495bbe4/element] with body: {"strategy":"xpath","selector":"//*[@content-desc='YTD SS (CFC)']/following::android.view.View[1]","context":"","multiple":false}
[WD Proxy] Got response with status 200: {"sessionId":"39b5a19c-2ce4-4971-bcb5-ccc96495bbe4","value":{"ELEMENT":"cf89e981-9c79-4c76-8cce-02a4ea37e43b","element-6066-11e4-a52e-4f735466cecf":"cf89e981-9c79-4c76-8cce-02a4ea37e43b"}}
[W3C (f15d7601)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"cf89e981-9c79-4c76-8cce-02a4ea37e43b","ELEMENT":"cf89e981-9c79-4c76-8cce-02a4ea37e43b"}
[HTTP] <-- POST /wd/hub/session/f15d7601-4f93-4e48-b9ae-b8693adc55ee/element 200 771 ms - 137
[HTTP] 
[HTTP] --> POST /wd/hub/session/f15d7601-4f93-4e48-b9ae-b8693adc55ee/execute/sync
[HTTP] {"script":"return (function(){return function(){var d=this;function f(a){return\"string\"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||\"\";a=this.a.replace(/((?:^|\\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\\s\\xa0]+/g,\"\")});b=a.length-5;if(0>b||a.indexOf(\"Error\",b)!=b)a+=\"Error\";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||\"\"}\n(function(){var a=Error;function b(){}b.prototype=a.prototype;h.b=a.prototype;h.prototype=new b;h.prototype.constructor=h;h.a=function(b,c,g){for(var e=Array(arguments.length-2),k=2;k
[W3C (f15d7601)] Calling AppiumDriver.execute() with args: ["return (function(){return function(){var d=this;function f(a){return\"string\"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||\"\";a=this.a.replace(/((?:^|\\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\\s\\xa0]+/g,\"\")});b=a.length-5;if(0>b||a.indexOf(\"Error\",b)!=b)a+=\"Error\";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||\"\"}\n(function(){var a=Error;function b(){}b.prototype=a.prototype;h.b=a.prototype;h.prototype=new b;h.prototype.constructor=h;h.a=function(b,c,g){for(var e=Array(arguments.length-2),k=2;k
[W3C (f15d7601)] Encountered internal error running command: NotImplementedError: Method is not implemented
[W3C (f15d7601)]     at AndroidUiautomator2Driver.execute (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/execute.js:14:11)
[W3C (f15d7601)]     at curCommandCancellable._bluebird.default.resolve.then (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:353:75)
[W3C (f15d7601)]     at tryCatcher (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/bluebird/js/release/util.js:16:23)
[W3C (f15d7601)]     at Promise._settlePromiseFromHandler (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/bluebird/js/release/promise.js:547:31)
[W3C (f15d7601)]     at Promise._settlePromise (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/bluebird/js/release/promise.js:604:18)
[W3C (f15d7601)]     at Promise._settlePromiseCtx (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/bluebird/js/release/promise.js:641:10)
[W3C (f15d7601)]     at _drainQueueStep (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/bluebird/js/release/async.js:97:12)
[W3C (f15d7601)]     at _drainQueue (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/bluebird/js/release/async.js:86:9)
[W3C (f15d7601)]     at Async._drainQueues (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/bluebird/js/release/async.js:102:5)
[W3C (f15d7601)]     at Immediate.Async.drainQueues (/tmp/.mount_Appiumk7Fo0H/resources/app/node_modules/appium/node_modules/bluebird/js/release/async.js:15:14)
[W3C (f15d7601)]     at runCallback (timers.js:696:18)
[W3C (f15d7601)]     at tryOnImmediate (timers.js:667:5)
[W3C (f15d7601)]     at processImmediate (timers.js:649:5)
[HTTP] <-- POST /wd/hub/session/f15d7601-4f93-4e48-b9ae-b8693adc55ee/execute/sync 405 13 ms - 1725
[HTTP]

**Comment by mykola-mokhnach** [comment] 2020-01-04 13:03
Duplicate of https://github.com/appium/java-client/issues/1239

**Closed by mykola-mokhnach** 2020-01-04 13:03 UTC
Labels: NeedsInfo

**Comment by Akhila666** [comment] 2020-01-04 13:09
hi 

i am using java client 7.2.0

**Comment by Akhila666** [comment] 2020-01-04 13:13
hi

i am using latest version of java client 7.2.0

but i am facing this issue . please help me ...

**Comment by swatitest-prog** [comment] 2023-02-21 11:06
hi @Akhila666 i am facing the same issue can you help me ?

**Comment by rjtvalderrama** [comment] 2024-02-16 03:36
The duplicate https://github.com/appium/java-client/issues/1239 is not resolving this issue, can someone update if they have already resolved it?
