### ISSUE TITLE
Appium2.0 tests the APP on Android12 or later, often there is no response for a long time, there is no error, the log has not been updated, and sometimes even if the element is found, it does not click, and it runs normally on Android11

### ISSUE THREAD

**Issue by newleek** [appium/appium#20113] opened 2024-05-18 16:46 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I was using WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.XPATH, "//*[@text=' download ']"))), the interface was slow to load. After waiting for about 10 seconds, the appium log no longer updates, even after 30 seconds of the set error, I don't know why, here is the last run log, and then stuck here, not only this operation, often happens on different behaviors, but not on Android version 11. The elements are queried even if the wait time is long, and the log is updated
[AndroidUiautomator2Driver@6510 (cbf4c58c)] Calling AppiumDriver.findElement() with args:  [" xpath ", "/ / * [@ text = 'download']", "cbf4c58c f5b 4-6 d5a - ad77-9957 e9ab739c"]
[AndroidUiautomator2Driver@6510 (cbf4c58c)] Valid locator strategies for this request:  xpath, id, class name, accessibility id, css selector, -android uiautomator
[AndroidUiautomator2Driver@6510 (cbf4c58c)] Waiting up to 0 ms for condition
[AndroidUiautomator2Driver@6510 (cbf4c58c)] Matched '/element' to command name 'findElement'
[AndroidUiautomator2Driver@6510 (cbf4c58c)] Proxying [POST /element] to [POST  http://127.0.0.1:8202/session/eb595310-cdaa-43ea-b0f9-703ce82141e7/element] with the body: {" strategy ":" xpath ", "selector" : "/ / * [@ text = 'download']", "context" : ""," multiple ": false}

### Expected Behavior

On Android version 12 or higher, Use WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.XPATH, "//*[@text=' download ']"))). As long as the click, input and other behaviors are found within the timeout period, the timeout will throw an exception, and the log will not be updated, and no error will be reported

### Minimal Reproducible Example

ele = WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.XPATH, "//*[contains(@text, 'SIM快捷')]")))
ele.click()

### Environment

- Operating system:windows
- Appium server version (output of `appium --version`):2.5.4
- Appium driver(s) and their version(s) (`appium driver list`):uiautomator2@3.5.0
- Appium plugin(s) and their version(s) (`appium plugin list`):no
- Node.js version (output of `node --version`):v20.13.1
- `npm` version (output of `npm --version`):10.5.2
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:Android 13/OPPO A1
- Real device or emulator/simulator:Real device

### Further Information

[AndroidUiautomator2Driver@f2ab (7ade18ac)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"00000000-0000-01aa-ffff-ffff0000027c","ELEMENT":"00000000-0000-01aa-ffff-ffff0000027c"}
[HTTP] <-- POST /session/7ade18ac-c5c8-4b35-86b3-a647a6410895/element 200 935 ms - 137
[HTTP]
[HTTP] --> POST /session/7ade18ac-c5c8-4b35-86b3-a647a6410895/element/00000000-0000-01aa-ffff-ffff0000027c/click
[HTTP] {}
[AndroidUiautomator2Driver@f2ab (7ade18ac)] Calling AppiumDriver.click() with args: ["00000000-0000-01aa-ffff-ffff0000027c","7ade18ac-c5c8-4b35-86b3-a647a6410895"]
[AndroidUiautomator2Driver@f2ab (7ade18ac)] Matched '/element/00000000-0000-01aa-ffff-ffff0000027c/click' to command name 'click'
[AndroidUiautomator2Driver@f2ab (7ade18ac)] Proxying [POST /element/00000000-0000-01aa-ffff-ffff0000027c/click] to [POST http://127.0.0.1:8220/session/7bdac3a1-cb4b-4e9b-a3d5-ba5f37e792ac/element/00000000-0000-01aa-ffff-ffff0000027c/click] with body: {"element":"00000000-0000-01aa-ffff-ffff0000027c"}
[AndroidUiautomator2Driver@f2ab (7ade18ac)] Got response with status 200: {"sessionId":"7bdac3a1-cb4b-4e9b-a3d5-ba5f37e792ac","value":null}
[AndroidUiautomator2Driver@f2ab (7ade18ac)] Responding to client with driver.click() result: null
[HTTP] <-- POST /session/7ade18ac-c5c8-4b35-86b3-a647a6410895/element/00000000-0000-01aa-ffff-ffff0000027c/click 200 685 ms - 14
[HTTP]
[HTTP] --> POST /session/7ade18ac-c5c8-4b35-86b3-a647a6410895/element
[HTTP] {"using":"id","value":"com.cmcc.hebao:id/rl_title_back"}
[AndroidUiautomator2Driver@f2ab (7ade18ac)] Calling AppiumDriver.findElement() with args: ["id","com.cmcc.hebao:id/rl_title_back","7ade18ac-c5c8-4b35-86b3-a647a6410895"]
[AndroidUiautomator2Driver@f2ab (7ade18ac)] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
[AndroidUiautomator2Driver@f2ab (7ade18ac)] Waiting up to 0 ms for condition
[AndroidUiautomator2Driver@f2ab (7ade18ac)] Matched '/element' to command name 'findElement'
[AndroidUiautomator2Driver@f2ab (7ade18ac)] Proxying [POST /element] to [POST http://127.0.0.1:8220/session/7bdac3a1-cb4b-4e9b-a3d5-ba5f37e792ac/element] with body: {"strategy":"id","selector":"com.cmcc.hebao:id/rl_title_back","context":"","multiple":false}
[AndroidUiautomator2Driver@f2ab (7ade18ac)] Got response with status 200: {"sessionId":"7bdac3a1-cb4b-4e9b-a3d5-ba5f37e792ac","value":{"ELEMENT":"00000000-0000-01a1-ffff-ffff00000504","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-01a1-ffff-ffff00000504"}}
[AndroidUiautomator2Driver@f2ab (7ade18ac)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"00000000-0000-01a1-ffff-ffff00000504","ELEMENT":"00000000-0000-01a1-ffff-ffff00000504"}
[HTTP] <-- POST /session/7ade18ac-c5c8-4b35-86b3-a647a6410895/element 200 542 ms - 137
[HTTP]
[HTTP] --> POST /session/7ade18ac-c5c8-4b35-86b3-a647a6410895/element/00000000-0000-01a1-ffff-ffff00000504/click
[HTTP] {}
[AndroidUiautomator2Driver@f2ab (7ade18ac)] Calling AppiumDriver.click() with args: ["00000000-0000-01a1-ffff-ffff00000504","7ade18ac-c5c8-4b35-86b3-a647a6410895"]
[AndroidUiautomator2Driver@f2ab (7ade18ac)] Matched '/element/00000000-0000-01a1-ffff-ffff00000504/click' to command name 'click'
[AndroidUiautomator2Driver@f2ab (7ade18ac)] Proxying [POST /element/00000000-0000-01a1-ffff-ffff00000504/click] to [POST http://127.0.0.1:8220/session/7bdac3a1-cb4b-4e9b-a3d5-ba5f37e792ac/element/00000000-0000-01a1-ffff-ffff00000504/click] with body: {"element":"00000000-0000-01a1-ffff-ffff00000504"}

**Comment by mykola-mokhnach** [comment] 2024-05-18 19:50
Could you please be more explicit where the issue is observed in the above log?

In general elements lookup is performed by the UiAutomator framework and we cannot influence it from the driver side. You could also try to reduce the idling timeout as a possible workaround if the app under test is not idling enough. See https://github.com/appium/appium/issues/16298 for more details.

**Comment by newleek** [comment] 2024-05-20 02:08
This is the full appium log, it doesn't move here, it doesn't respond, it doesn't report errors, it's stuck here, I'm running on Anroid 14
[Uploading logcat.txt…]()

**Comment by newleek** [comment] 2024-05-20 02:11
After about five minutes, it reports an error and exits. The error is as follows：

[AndroidUiautomator2Driver@f84c (a200d135)] AxiosError: timeout of 240000ms exceeded
[AndroidUiautomator2Driver@f84c (a200d135)]     at RedirectableRequest.handleRequestTimeout (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\axios\lib\adapters\http.js:647:16)
[AndroidUiautomator2Driver@f84c (a200d135)]     at RedirectableRequest.emit (node:events:513:28)
[AndroidUiautomator2Driver@f84c (a200d135)]     at Timeout.<anonymous> (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\follow-redirects\index.js:210:12)
[AndroidUiautomator2Driver@f84c (a200d135)]     at listOnTimeout (node:internal/timers:564:17)
[AndroidUiautomator2Driver@f84c (a200d135)]     at processTimers (node:internal/timers:507:7)
[AndroidUiautomator2Driver@f84c (a200d135)]     at Axios.request (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\axios\lib\core\Axios.js:45:41)
[AndroidUiautomator2Driver@f84c (a200d135)]     at runNextTicks (node:internal/process/task_queues:60:5)
[AndroidUiautomator2Driver@f84c (a200d135)]     at listOnTimeout (node:internal/timers:533:9)
[AndroidUiautomator2Driver@f84c (a200d135)]     at processTimers (node:internal/timers:507:7)
[AndroidUiautomator2Driver@f84c (a200d135)]     at UIA2Proxy.request (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:100:14)
[AndroidUiautomator2Driver@f84c (a200d135)]     at UIA2Proxy.proxy (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:234:39)
[AndroidUiautomator2Driver@f84c (a200d135)]     at ProtocolConverter.convertAndProxy (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\protocol-converter.js:266:12)
[AndroidUiautomator2Driver@f84c (a200d135)]     at UIA2Proxy.proxyCommand (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:336:12)
[AndroidUiautomator2Driver@f84c (a200d135)]     at UIA2Proxy.proxyCommand (C:\Users\Fsx\.appium\node_modules\appium-uiautomator2-driver\lib\uiautomator2.js:33:12)
[AndroidUiautomator2Driver@f84c (a200d135)]     at UIA2Proxy.command (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:32)
[AndroidUiautomator2Driver@f84c (a200d135)]     at AndroidUiautomator2Driver.doFindElementOrEls (C:\Users\Fsx\.appium\node_modules\appium-uiautomator2-driver\lib\commands\find.js:40:5)
[AndroidUiautomator2Driver@f84c (a200d135)]     at doFind (C:\Users\Fsx\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.ts:47:17)
[AndroidUiautomator2Driver@f84c (a200d135)]     at wrappedCondFn (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\timeout.ts:137:14)
[AndroidUiautomator2Driver@f84c (a200d135)]     at spin (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\lib\asyncbox.js:219:20)
[AndroidUiautomator2Driver@f84c (a200d135)]     at waitForCondition (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\lib\asyncbox.js:236:10)
[AndroidUiautomator2Driver@f84c (a200d135)]     at AndroidUiautomator2Driver.implicitWaitForCondition (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\timeout.ts:139:12)
[AndroidUiautomator2Driver@f84c (a200d135)]     at AndroidUiautomator2Driver.findElOrEls (C:\Users\Fsx\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.ts:70:5)
[AndroidUiautomator2Driver@f84c (a200d135)]     at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:60:12)
[AndroidUiautomator2Driver@f84c (a200d135)]     at AndroidUiautomator2Driver.findElement (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:75:12)
[AndroidUiautomator2Driver@f84c (a200d135)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
[AndroidUiautomator2Driver@f84c (a200d135)]     at UIA2Proxy.command (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:355:13)
[AndroidUiautomator2Driver@f84c (a200d135)]     at runNextTicks (node:internal/process/task_queues:60:5)
[AndroidUiautomator2Driver@f84c (a200d135)]     at listOnTimeout (node:internal/timers:533:9)
[AndroidUiautomator2Driver@f84c (a200d135)]     at processTimers (node:internal/timers:507:7)
[AndroidUiautomator2Driver@f84c (a200d135)]     at AndroidUiautomator2Driver.doFindElementOrEls (C:\Users\Fsx\.appium\node_modules\appium-uiautomator2-driver\lib\commands\find.js:40:5)
[AndroidUiautomator2Driver@f84c (a200d135)]     at doFind (C:\Users\Fsx\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.ts:47:17)
[AndroidUiautomator2Driver@f84c (a200d135)]     at wrappedCondFn (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\timeout.ts:137:14)
[AndroidUiautomator2Driver@f84c (a200d135)]     at spin (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\lib\asyncbox.js:219:20)
[AndroidUiautomator2Driver@f84c (a200d135)]     at waitForCondition (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\asyncbox\lib\asyncbox.js:236:10)
[AndroidUiautomator2Driver@f84c (a200d135)]     at AndroidUiautomator2Driver.implicitWaitForCondition (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\timeout.ts:139:12)
[AndroidUiautomator2Driver@f84c (a200d135)]     at AndroidUiautomator2Driver.findElOrEls (C:\Users\Fsx\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.ts:70:5)
[AndroidUiautomator2Driver@f84c (a200d135)]     at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:60:12)
[AndroidUiautomator2Driver@f84c (a200d135)]     at AndroidUiautomator2Driver.findElement (C:\Users\Fsx\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:75:12)
[HTTP] <-- POST /session/a200d135-f147-493c-a337-338e1eb08236/element 500 240028 ms - 2245
[HTTP]
[HTTP] --> DELETE /session/a200d135-f147-493c-a337-338e1eb08236
[HTTP] {}
[AndroidUiautomator2Driver@f84c (a200d135)] Calling AppiumDriver.deleteSession() with args: ["a200d135-f147-493c-a337-338e1eb08236"]
[AppiumDriver@e4de] Event 'quitSessionRequested' logged at 1716170865913 (10:07:45 GMT+0800 (中国标准时间))
[AppiumDriver@e4de] Removing session a200d135-f147-493c-a337-338e1eb08236 from our master session list
[AndroidUiautomator2Driver@f84c (a200d135)] Deleting UiAutomator2 session
[AndroidUiautomator2Driver@f84c (a200d135)] Deleting UiAutomator2 server session
[AndroidUiautomator2Driver@f84c (a200d135)] Matched '/' to command name 'deleteSession'
[AndroidUiautomator2Driver@f84c (a200d135)] Proxying [DELETE /] to [DELETE http://127.0.0.1:8201/session/acc22b42-da64-422f-9cbf-98a28e8e8649] with no body
[AndroidUiautomator2Driver@f84c (a200d135)] Got response with status 200: {"sessionId":"acc22b42-da64-422f-9cbf-98a28e8e8649","value":null}
[ADB] Running 'D:\AndroidSdk\platform-tools\adb.exe -P 5037 -s f4bac1bd shell dumpsys activity services io.appium.settings/.recorder.RecorderService'
[ADB] Running 'D:\AndroidSdk\platform-tools\adb.exe -P 5037 -s f4bac1bd shell am force-stop com.cmcc.hebao'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8201
[ADB] Running 'D:\AndroidSdk\platform-tools\adb.exe -P 5037 -s f4bac1bd forward --remove tcp:8201'
[AndroidUiautomator2Driver@f84c (a200d135)] Restoring hidden api policy to the device default configuration
[ADB] Running 'D:\AndroidSdk\platform-tools\adb.exe -P 5037 -s f4bac1bd shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[AppiumDriver@e4de] Event 'quitSessionFinished' logged at 1716170938581 (10:08:58 GMT+0800 (中国标准时间))
[AppiumDriver@e4de] Received response: null
[AppiumDriver@e4de] But deleting session, so not returning
[AppiumDriver@e4de] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /session/a200d135-f147-493c-a337-338e1eb08236 200 72672 ms - 14
[HTTP]
[Instrumentation] .
[Instrumentation] Time: 341.66
[Instrumentation]
[Instrumentation] OK (1 test)
[Instrumentation] The process has exited with code 0

**Comment by KazuCocoa** [comment] 2024-05-20 03:15
Perhaps the link in https://github.com/appium/appium/issues/20113#issuecomment-2119541460 failed to upload the file

**Comment by newleek** [comment] 2024-05-20 04:17
yes，Will disconnection occur because appium communication is restricted on Android 14
[logcat.txt](https://github.com/appium/appium/files/15372630/logcat.txt)

**Comment by KazuCocoa** [comment] 2024-05-20 04:37
Perhaps logcat info will help. Do you have logcat when the behavior occur?
The attached log said the device was Oppo. We saw that Chinese devices tended to customize Android behavior like customizing background processes. e.g. https://github.com/appium/appium/issues/13802 . (This is not Appium specific)
I don't have such Oppo devices thus cannot dig into the possible device side config but methods addressed in https://github.com/appium/appium/issues/13802  may help to dig into possible manufacture customization that could restrict Appium/UIA2 server behavior.

**Comment by newleek** [comment] 2024-05-20 06:28
Can you recommend which mobile device can better use appium? I can buy it

**Comment by KazuCocoa** [comment] 2024-05-20 06:30
I think usually Google's official ones

**Comment by newleek** [comment] 2024-05-20 06:57
Could you recommend a specific phone name and model, or one that you often test? Thank you

**Comment by newleek** [comment] 2024-05-20 07:21
@mykola-mokhnach Can I see the problem according to my latest logcat

**Closed** 2024-05-22 15:54 UTC
Labels: UIAutomator2, Needs Info

**Comment by Silencesoulz** [comment] 2024-05-24 03:44
@newleek have you figured it out yet?, i also facing this issue as well

**Comment by arvyandwi** [comment] 2024-06-04 10:52
@newleek @mykola-mokhnach  i'm using Poco X5 5G with Android 14 HyperOS and facing the same issue.

Here is the log:
`2024-06-04 16:59:15:725 - [HTTP] --> GET /wd/hub/session/c896af16-3212-436a-89ca-8caef21ea658/window/rect
2024-06-04 16:59:15:726 - [HTTP] {}
2024-06-04 16:59:18:144 - [HTTP] --> GET /wd/hub/status
2024-06-04 16:59:18:145 - [HTTP] {}
2024-06-04 16:59:18:147 - [HTTP] <-- GET /wd/hub/status 200 3 ms - 110
2024-06-04 16:59:18:147 - [HTTP] 
2024-06-04 17:00:13:948 - [HTTP] --> GET /wd/hub/status
2024-06-04 17:00:13:949 - [HTTP] {}
2024-06-04 17:00:13:952 - [HTTP] <-- GET /wd/hub/status 200 4 ms - 110
2024-06-04 17:00:13:952 - [HTTP] 
2024-06-04 17:00:15:714 - [AndroidUiautomator2Driver@54a5 (c896af16)] AxiosError: timeout of 240000ms exceeded
2024-06-04 17:00:15:714 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at RedirectableRequest.handleRequestTimeout (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/node_modules/axios/lib/adapters/http.js:647:16)
2024-06-04 17:00:15:714 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at RedirectableRequest.emit (node:events:512:28)
2024-06-04 17:00:15:714 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at Timeout.<anonymous> (/opt/homebrew/lib/node_modules/appium/node_modules/follow-redirects/index.js:210:12)
2024-06-04 17:00:15:714 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at listOnTimeout (node:internal/timers:568:17)
2024-06-04 17:00:15:714 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at processTimers (node:internal/timers:511:7)
2024-06-04 17:00:15:715 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at Axios.request (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/node_modules/axios/lib/core/Axios.js:45:41)
2024-06-04 17:00:15:715 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at runNextTicks (node:internal/process/task_queues:60:5)
2024-06-04 17:00:15:715 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at listOnTimeout (node:internal/timers:537:9)
2024-06-04 17:00:15:715 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at processTimers (node:internal/timers:511:7)
2024-06-04 17:00:15:715 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at UIA2Proxy.request (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:100:14)
2024-06-04 17:00:15:715 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at UIA2Proxy.proxy (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:234:39)
2024-06-04 17:00:15:715 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at ProtocolConverter.convertAndProxy (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/protocol-converter.js:270:12)
2024-06-04 17:00:15:715 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at UIA2Proxy.proxyCommand (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:336:12)
2024-06-04 17:00:15:715 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at UIA2Proxy.proxyCommand (/Users/admin/.appium/node_modules/appium-uiautomator2-driver/lib/uiautomator2.js:34:12)
2024-06-04 17:00:15:715 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at UIA2Proxy.command (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:350:32)
2024-06-04 17:00:15:715 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at AndroidUiautomator2Driver.commands.getWindowSize (/Users/admin/.appium/node_modules/appium-uiautomator2-driver/lib/commands/general.js:95:10)
2024-06-04 17:00:15:715 - [AndroidUiautomator2Driver@54a5 (c896af16)]     at AndroidUiautomator2Driver.commands.getWindowRect (/Users/admin/.appium/node_modules/appium-uiautomator2-driver/lib/commands/general.js:100:27)
2024-06-04 17:00:15:734 - [HTTP] <-- GET /wd/hub/session/c896af16-3212-436a-89ca-8caef21ea658/window/rect 500 240069 ms - 1023`

Is the any update regarding this issue? 

Thanks in advance.

**Comment by KazuCocoa** [comment] 2024-06-05 05:53
For `window/rect`, it depends on what value the device returns. Potentially the device itself did not return the value to the caller (uia2 driver). I would check the logcat as well.
https://github.com/appium/appium-uiautomator2-server/blob/bb18a50f6131b0ffa8c353de7f995ab48a59ae2b/app/src/main/java/io/appium/uiautomator2/handler/GetDeviceSize.java#L38-L42

**Comment by arvyandwi** [comment] 2024-06-05 09:54
Hi @KazuCocoa here is our full logcat, perhaps it could help. Often times I didn't get any response from `window/rect` and disrupting the automation run. Hence, I always manually stop the automation run from the client side (i use Katalon Studio to run the Automation). Looking forward for your response. Thanks in advance.
[logcat_report.txt](https://github.com/user-attachments/files/15584910/logcat_report.txt)
