### ISSUE TITLE
inspector could not show app page source with ios 12

### ISSUE THREAD

**Issue by yuesongjie** [appium/appium#11559] opened 2018-10-22 07:53 UTC
as picture shows
![image](https://user-images.githubusercontent.com/29249726/47282638-9c030880-d612-11e8-98f9-486048878170.png)

**Comment by mykola-mokhnach** [comment] 2018-10-22 13:15
Duplicate of https://github.com/appium/appium/issues/11558

**Closed by mykola-mokhnach** 2018-10-22 13:15 UTC
