### ISSUE TITLE
Appium 1.16 beta version dropping the values of the Textbox

### ISSUE THREAD

**Issue by KS261187** [appium/appium#13620] opened 2019-11-20 00:19 UTC
## The problem

So I have recently downloaded Appium beta 1.16 and noticed this wired issue where my text box has very limited properties. Looks like Appium when inspecting the elements drops some of the properties which are present inside the text box. This works perfectly fine with the 1.15.1 release.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16 beta
* Last Appium version that did not exhibit the issue (if applicable): 1.15.1
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

So with the Appium beta 1.16, iam noticing the values inside the text box are all getting dropped and hence the command get attribute("value") does not yield any results. This was perfectly working fine with Appium 1.15.1. I am attaching the screenshots from both the versions for your reference.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
<img width="1070" alt="Appium 1 16 Beta" src="https://user-images.githubusercontent.com/26659582/69197935-ac790180-0af8-11ea-8cc6-0e1215c42c21.png">
<img width="1072" alt="Appium 1 15" src="https://user-images.githubusercontent.com/26659582/69198081-23ae9580-0af9-11ea-89f9-803b31965ffd.png">

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2019-11-20 08:44
What is the iOS version on the device?

**Comment by KS261187** [comment] 2019-11-20 19:45
IOS version is 13.1.3
Device: Iphone 7

**Comment by mykola-mokhnach** [comment] 2019-11-20 19:47
I assume it is an XCTest issue. Try to upgrade the phone and Xcode to iOS 13.2

**Comment by KS261187** [comment] 2019-11-20 20:00
My Xcode version is already pointing to 11.2.1 and my iOS is 13.1.3. Not sure what I need to update here?

**Comment by mykola-mokhnach** [comment] 2019-11-20 20:08
The recent iOS version is [13.2](https://en.wikipedia.org/wiki/IOS_version_history#13.2.3)

**Comment by KS261187** [comment] 2019-11-20 20:22
I just updated it and that didn't help either. It still drops the properties.

**Comment by mykola-mokhnach** [comment] 2019-11-21 06:52
Unfortunately, I'm out of ideas then.

**Comment by KS261187** [comment] 2019-11-25 05:50
This issue started to happen only after upgrading my Appium to beta. This still works with the Appium 1.15.1. So I am not sure how you can relate this to XCUITEST. If I run the same thing against the Appium 1.15.1 and with the iOS version 13.2 and the Xcode 11.2, this works perfectly fine. Looks like the Appium update broke this certainly. Thoughts?

**Comment by KazuCocoa** [comment] 2019-11-25 07:36
Could you share the page sources and the full appium log with `showIOSLog: true` and `showXcodeLog: true` as https://gist.github.com/new?

I assume you compared below environment:

- Xcode 11.2.1?, iOS 13.2.2? (real device), and Appium 1.16.beta
- Xcode 11.2.1?, iOS 13.2.2? (real device), and Appium 1.15.1

We haven't changed the fundamental logic to get elements/attributes by XCTest since Appium 1.15.1.
https://github.com/appium/WebDriverAgent/commits/master

**Comment by KS261187** [comment] 2019-11-25 16:28
Yes I did compared the Appium beta with 1.15.1 using the above credentials. I have also added the page source to the GitHub under KS261187/Page Source for Appium Beta and 1.15.1

**Comment by KazuCocoa** [comment] 2019-11-25 17:01
Did you enter a space in the text field? Your source had `"￼"`.
How about clearing the space and getting the source again? (Can it be clear?)

```
<XCUIElementTypeTextField type="XCUIElementTypeTextField" value="￼" label="" enabled="true" visible="true" x="16" y="218" width="343" height="43"/>
```

**Comment by KS261187** [comment] 2019-11-25 17:52
I tried but that did not help either. I follow the same steps with Appium 1.15.1 and it gets the properties perfectly fine. It should be there in the logs too.

**Comment by KS261187** [comment] 2019-11-25 17:58
Also if you look at the screenshot attached, the "username" text is inside the textfield but the weird part is it is able to get the text for the Password field which has the text called Password. Not sure why it is not getting it for Username.

**Comment by KazuCocoa** [comment] 2019-11-26 01:42
Can I get the app via app store?

Btw, can you get the element by `find_element :name, 'Username'` for example (not via XPath)?
A possible case was perhaps XPath improvement affected that.

**Comment by KS261187** [comment] 2019-11-26 07:06
Yes you can get the app via App Store and it is called as CED Connect. So are you asking me to get the element via xpath using find element(@name,'username')?

**Comment by KS261187** [comment] 2019-11-26 07:09
findelementByname works. Wow, you nailed it.

**Comment by KS261187** [comment] 2019-11-26 07:09
is that a bug?

**Comment by KazuCocoa** [comment] 2019-11-26 08:12
hm...
I could not say it is a bug in appium since your view had a value as `value` like below. (debugdescription `value` by XCTest) Not sure, but object was inserted as `value`??
![image](https://user-images.githubusercontent.com/5511591/69610042-5236ee00-106e-11ea-824c-81fcd928fbfe.png)

So, Appium returned the `value` as source than a placeholder after some improvements. (e.g. https://github.com/appium/WebDriverAgent/pull/245 ). Then, the `value` was handled correctly.
Not sure, but perhaps we can control the priority, but I think it is better to fix your code not to have such wrong `value` in your view.

BTW, 'password' was in both value and placeholder.
![image](https://user-images.githubusercontent.com/5511591/69610288-d12c2680-106e-11ea-919d-3a858f01baaf.png)

**Comment by mykola-mokhnach** [comment] 2019-11-30 08:06
Thanks for the invastigation @KazuCocoa 
I don't observe any issues here on WDA side. Closed as not a bug

**Closed by mykola-mokhnach** 2019-11-30 08:06 UTC
Labels: NotABug, XCUITest
