### ISSUE TITLE
Can not found a photo using simulator iOS

### ISSUE THREAD

**Issue by baligit** [appium/appium#14414] opened 2020-06-04 10:23 UTC
## The problem

I am trying to choose a photo form photo gallery. After clicking on the app, that i am testing, choose photo pop up the following screen ![image](https://user-images.githubusercontent.com/63911430/83744565-9ed23600-a65c-11ea-8a9c-cd19b239c443.png)
with the following inspector 
![image](https://user-images.githubusercontent.com/63911430/83745291-99c1b680-a65d-11ea-8319-0c83d908f05e.png) 

By running the server i have got the following: _An element could not be located on the page using the given search parameters._
 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Mobile platform/version under test: Mac
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Code To Reproduce Issue [ Good To Have ]

  `              getIOSDriver().findElementByXPath("//XCUIElementTypeCell[@name=\"Alle Fotos\"]").click();`

**Comment by mykola-mokhnach** [comment] 2020-06-04 10:41
Duplicate of https://github.com/appium/appium/issues/14400

**Comment by baligit** [comment] 2020-06-04 10:48
Can you please explain your comment: https://github.com/appium/appium/issues/14400#issuecomment-637573951

**Comment by mykola-mokhnach** [comment] 2020-06-04 11:15
This depends on how the app under test is built. I cannot reproduce the issue locally with my app under test - all elements on the Photos overlay are found properly.

Try to retrieve the page source right before the lookup is executed and check what's there.

**Comment by baligit** [comment] 2020-06-04 12:26
i have show the page source, before the lookup is executed. But it did not work.

**Comment by mykola-mokhnach** [comment] 2020-06-04 12:28
> i have show the page source, before the lookup is executed. But it did not work.

Where is it? I mean it makes sense to attach it to this issue
What exactly did not work?

**Comment by baligit** [comment] 2020-06-04 12:45
```
@iOSFindBy(xpath = "//XCUIElementTypeCell[@label=\"Momente\"]")
    private WebElement moments; 

                moments.click();
```
This is the error: 
```
org.openqa.selenium.NoSuchElementException: Timed out after 1 seconds. Element not found
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
```


[page source.txt](https://github.com/appium/appium/files/4730087/page.source.txt)

**Comment by mykola-mokhnach** [comment] 2020-06-04 12:50
Are you sure the page source is taken right before the lookup? Have you tried to use findElement call instead of an annotation? Or replace the xpath locator with a predicate one?

**Comment by baligit** [comment] 2020-06-04 13:08
yes. i am sure the page source conforms the lookup. And i tried to with using the findeElement. but i have the same error :
`An element could not be located on the page using the given search parameters.
`

**Comment by mykola-mokhnach** [comment] 2020-06-04 13:08
How about changing the locator type?

**Comment by Phoenix124** [comment] 2020-06-04 13:11
@baligit try to use `@iOSXCUITFindBy(iOSNsPredicate = "name CONTAINS 'All'")` locator

**Comment by baligit** [comment] 2020-06-04 13:11
I have used: @iOSFindBy(xpath = "//XCUIElementTypeCell[@name=\"Momente\"]") and @iOSFindBy(xpath = "//XCUIElementTypeCell[@label=\"Momente\"]"). but i have got the error.

**Comment by mykola-mokhnach** [comment] 2020-06-04 13:13
"change locator type" means anything except of xpath

**Comment by baligit** [comment] 2020-06-04 13:41
i have tried `getIOSDriver().findElementByAccessibilityId("Momente").getSize()`

i have got the same error  
`An element could not be located on the page using the given search parameters.`

**Comment by baligit** [comment] 2020-06-04 14:00
> @baligit try to use `@iOSXCUITFindBy(iOSNsPredicate = "name CONTAINS 'All'")` locator

did you mean in my case `@iOSXCUITFindBy(iOSNsPredicate = "Alle Fotos")

**Comment by mykola-mokhnach** [comment] 2020-06-04 14:07
No, the locator must be a valid ios predicate. Read 
https://github.com/appium/appium/blob/fe293dcaf4621ae68f4d61f891b872442f7627bc/docs/en/writing-running-appium/ios/ios-predicate.md  
https://kapeli.com/cheat_sheets/NSPredicate.docset/Contents/Resources/Documents/index
for more details

**Comment by baligit** [comment] 2020-06-04 14:14
Thank you i understand it. i tryed: `    @iOSXCUITFindBy(iOSNsPredicate = "name CONTAINS 'All'")'. That means, find any Predicate, that contains the name 'All'. Unfortunately  the error is occurred agin "Element not found"

**Comment by mykola-mokhnach** [comment] 2020-06-04 14:20
> Unfortunately the error is occurred agin "Element not found"

In such case there is nothing more we could there from Appium side. Predicate search uses the same native lookup call that vanilla xctest code would do. Consider reporting your issue to Apple.

**Comment by baligit** [comment] 2020-06-05 11:36
just for info this is my capabilites:  
`{
  "deviceName": "iPhone 11",
  "platformName": "iOS",
  "platformVersion": "13.4",
  "app": "....app",
  "noRest": true,
  "automationName": "XCUItest",
  "language": "de",
  "locale": "DE",
  "autoAcceptAlerts": true,
  "autoDismissAlerts": true
}`

**Comment by baligit** [comment] 2020-06-05 13:53
It works now must execute `moments.click();` directly after executing `chosePhoto.click();` for tow time. But don't know why it is currently working.

**Closed** 2020-06-05 17:08 UTC
Labels: ThirdParty, XCUITest
