### ISSUE TITLE
Getting the error, "Unable to start WebDriverAgent: Error: Command 'idevicedate -u device_id' exited with code 255"

### ISSUE THREAD

**Issue by mirza-ae** [appium/appium#7540] opened 2016-12-14 23:01 UTC
## The problem

Hello,

When I run a test after executing the "appium" command in Terminal, I get a weird error.

Unable to start WebDriverAgent: Error: Command 'idevicedate -u the_device_udid' exited with code 255

The logs are located below:

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Desktop OS/version used to run Appium: Mac OSX 10.11.6
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: iPad 4 i,e iPad Retina

## Link to Appium logs
https://gist.github.com/mirza-ae/c597078dd300a1216f38cdce2f69d743

**Comment by mykola-mokhnach** [comment] 2016-12-14 23:04
try to update your idevicelibrary from --HEAD branch and/or fix lockdown privileges:

```
sudo chmod 777 /var/db/lockdown
```

Closed as duplicate of https://github.com/appium/appium/issues/7520

**Closed by mykola-mokhnach** 2016-12-14 23:04 UTC
Labels: NeedsTriage

**Comment by dcaric** [comment] 2016-12-16 12:37
Me to, I have https://github.com/appium/appium/issues/7521 same thing

**Comment by vikramvi** [comment] 2017-01-18 14:26
@mykola-mokhnach did both steps mentioned in your comment but it didn't fix the issue.

I've appium 1.6.3 and trying to install on real device with iOS 10.2. 

Please clarify
