### ISSUE TITLE
Appium finding and clicking element take long

### ISSUE THREAD

**Issue by wulfihm** [appium/appium#14281] opened 2020-05-05 12:59 UTC
## The problem

I am testing an app and for some activities the finding and clicking of elements is very slow.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1 (CLI)
* Desktop OS/version used to run Appium: Manjaro (also tested with different windows machines)
* Node.js version (unless using Appium.app|exe): 14.1
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Details

The app is developed in Xamarin.
All the elements are slow in detection and interaction. The issue is only in the activity where the stream is being created and the streaming is done.  As far as I know they are the same activity with different views/fragments. See the image (creating stream):
![mycrocast](https://user-images.githubusercontent.com/9419801/81066712-cdce7e00-8edd-11ea-8703-35e6dbcb0d19.png)

Using accessibility IDs (I coded them into the app for 2 elements for testing purposes) for the finding and clicking did not improve the speed.

I also tested it with Appium Desktop (1.15.1). Same issue. 

## Link to Appium logs

At the bottom of the gist there is a shorter log which only contains the relevant passage where the element is searched.
https://gist.github.com/wulfihm/6db7020cf38ee450e25f6765a31637f0

* at "2020-05-05 12:25:55:804" I am doing a "findElement", takes about 10s
* at "2020-05-05 12:26:05:928" a click is issued which takes about 20s
* overall 30s for a single interaction, way too long

## Code To Reproduce Issue [ Good To Have ]

I suggest to reproduce the bug with Appium Desktop. Finding and Clicking will likely timeout there as I increased the timeout time in my tests.

Here is some code (misses the desired capabilities) if you want to reproduce with coded tests.
https://gist.github.com/wulfihm/6ec20d8a95cdd2110b3422ab24788ab8

**Comment by mykola-mokhnach** [comment] 2020-05-05 15:01
Possible duplicate of https://github.com/appium/appium/issues/14155

**Comment by wulfihm** [comment] 2020-05-06 09:20
> Possible duplicate of #14155

Can confirm.
Logcat output showed waiting for idle state.
Doing driver.setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, 100) fixed the issue.

**Comment by KazuCocoa** [comment] 2020-05-06 12:45
You can set it in capabilities as `settings[settingsKey]`
https://appium.io/docs/en/writing-running-appium/caps/

**Closed** 2020-05-06 19:42 UTC
Labels: NeedsInfo, NotABug
