### ISSUE TITLE
Cannot Scroll To iOS Element via mobile:scroll

### ISSUE THREAD

**Issue by ajschwieterman** [appium/appium#13083] opened 2019-08-15 13:23 UTC
## The problem

I am trying to scroll to a non-visible element on the screen via mobile:scroll.  If the element is already visible, Appium does not scroll, which is expected.  When an element is not visible, Appium cannot find the element on the screen and reaches the max scroll count limit, but I can see the element on the phone being scrolled past.  I have a list of 24 elements that I search through, and the elements in the middle (indexes 10-14) do not get recognized by Appium.

I've tried other strategies to accomplish this goal using mobile:scroll, but none of them have worked for me. (https://developers.perfectomobile.com/pages/viewpage.action?pageId=25199704)

## Environment

* Appium version 1.14.0
* macOS Mojave v10.14.5
* Node.js v11.4.0
* Npm package manager
* iOS v12.4
* iPhone 6s - real device
* Appium CLI

## Link to Appium logs

https://gist.github.com/ajschwieterman/be01445442a9fe22f672018b2aff6554

## Code To Reproduce Issue [ Good To Have ]

MobileElement element = driver.findElementByName(elementText);
HashMap scrollObjects = new HashMap();
scrollObjects.put("element", element.getId());
scrollObjects.put("toVisible", "true");
driver.executeScript("mobile:scroll", scrollObjects);

**Comment by mykola-mokhnach** [comment] 2019-08-15 13:35
Duplicate of https://github.com/appium/appium/issues/13038

**Comment by mykola-mokhnach** [comment] 2019-08-20 05:09
Closed as third party issue

**Closed by mykola-mokhnach** 2019-08-20 05:09 UTC
Labels: ThirdParty, XCUITest
