### ISSUE TITLE
tap: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint:

### ISSUE THREAD

**Issue by epankaj1** [appium/appium#8261] opened 2017-04-14 13:54 UTC
## The problem

when trying to tap on button on native iOS application getting error "An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint:

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium:  Mac OS Sierra 10.12.14 
* Node.js version (unless using Appium.app|exe): v 7.9.0
* Mobile platform/version under test: apple iPhone 6s iOS 10.3.1
* Real device or emulator/simulator: Real Device ( issue is not reproducible in Simulator 10.3)
* Appium CLI or Appium.app|exe: Appium CLI
* Java Client used : 5.0.0 -BETA7 ( also tried with Java Client 4.1.2)

I build a native iOS App on iphone 6s  using Xcode 8.3.1 .
Appium 1.6.4 WebDriverAgent also build successfully on iPhone 6s using Xcode 8.3.1 ( Auto Signing )

## Details
When i am trying to tap on the button on the First page i am getting unhandled endpoint exception.

## Link to Appium logs

https://gist.github.com/epankaj1/df519f0e26aafdc8d4ad5519a81082ae

## Code To Reproduce Issue [ Good To Have ]

public class Tap {
private IOSDriver driver;
	
	@Test
	public void setUp() throws MalformedURLException {
		
		DesiredCapabilities caps = new DesiredCapabilities();
			caps.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.IOS);
		caps.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.3");
		caps.setCapability(MobileCapabilityType.DEVICE_NAME, " chandra Sambangi's iPhone");
		caps.setCapability("bundleid", "com.curam.mobile.Test123");
		caps.setCapability(MobileCapabilityType.APP, "/Users/watsonhealth/Documents/PANKAJ/WatsonHealthNativeApp/V&VNative.ipa");
	    caps.setCapability(MobileCapabilityType.UDID, "89825b99211488fa90ce578f24dbb5f860f0f9c7");
	    caps.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
	
		caps.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT, 500000);
		
		caps.setCapability(MobileCapabilityType.FULL_RESET, false);
		caps.setCapability(MobileCapabilityType.NO_RESET, true);
		
		driver = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"), caps);
		
		driver.tap(1,driver.findElementByAccessibilityId("Next"), (int) 10);
					
		assertEquals(driver.getPageSource().contains("Second ViewController"),true);
        driver.closeApp();
	}

}

**Comment by imurchie** [comment] 2017-04-14 14:17
`tap` is failing when invoked through Touch Action chain.

```
[HTTP] --> POST /wd/hub/session/47a54b37-39b3-4644-811e-ea5b13c80ea4/touch/perform {"actions":[{"action":"tap","options":{"element":"7BA4C7C0-4AE4-4336-9C1C-CBC270A18098"}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"element":"7BA4C7C0-4AE4-4336-9C1C-CBC270A18098"}}],"47a54b37-39b3-4644-811e-ea5b13c80ea4"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: tap(options={"element":"7BA4C7C0-4AE4-4336-9C1C-CBC270A18098"})
[debug] [XCUITest] Found matching gesture: tap
[debug] [JSONWP Proxy] Proxying [POST /wda/tap/7BA4C7C0-4AE4-4336-9C1C-CBC270A18098] to [POST http://localhost:8100/session/094A8646-A2A6-4255-A832-978EF7675922/wda/tap/7BA4C7C0-4AE4-4336-9C1C-CBC270A18098] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoint: /session/094A8646-A2A6-4255-A832-978EF7675922/wda/tap/7BA4C7C0-4AE4-4336-9C1C-CBC270A18098 -- http://localhost:8100/ with parameters {\n    wildcards =     (\n        \"session/094A8646-A2A6-4255-A832-978EF7675922/wda/tap/7BA4C7C0-4AE4-4336-9C1C-CBC270A18098\"\n    );\n}","sessionId":"094A8646-A2A6-4255-A832-978EF7675922","status":1}
[HTTP] <-- POST /wd/hub/session/47a54b37-39b3-4644-811e-ea5b13c80ea4/touch/perform 500 20 ms - 462 
```

**Comment by epankaj1** [comment] 2017-04-14 14:23
i did not understand..is it some set-up issue or my code issue or its bug.

**Comment by imurchie** [comment] 2017-04-14 14:25
I cannot reproduce:

```
info HTTP --> POST /wd/hub/session/5543469e-0cf8-47a0-b36c-dc36aa43c2ef/touch/perform {"actions":[{"action":"tap","options":{"element":"D647CE06-8E5E-4D80-B176-721C1E0CE5BD"}}]}
dbug MJSONWP Calling XCUITestDriver.performTouch() with args: [[{"action":"tap","options":{"element":"D647CE06-8E5E-4D80-B176-721C1E0CE5BD"}}],"5543469e-0cf8-47a0-b36c-dc36aa43c2ef"]
dbug XCUITest Executing command 'performTouch'
dbug XCUITest Received the following touch action: tap(options={"element":"D647CE06-8E5E-4D80-B176-721C1E0CE5BD"})
dbug XCUITest Found matching gesture: tap
dbug JSONWP Proxy Proxying [POST /wda/tap/D647CE06-8E5E-4D80-B176-721C1E0CE5BD] to [POST http://localhost:8100/session/3AA56C8A-33C8-4B5B-B49B-6F1D73887125/wda/tap/D647CE06-8E5E-4D80-B176-721C1E0CE5BD] with body: {}
dbug JSONWP Proxy Got response with status 200: {"value":{},"sessionId":"3AA56C8A-33C8-4B5B-B49B-6F1D73887125","status":0}
dbug MJSONWP Responding to client with driver.performTouch() result: null
info HTTP <-- POST /wd/hub/session/5543469e-0cf8-47a0-b36c-dc36aa43c2ef/touch/perform 200 537 ms - 76
```

**Comment by epankaj1** [comment] 2017-04-14 14:29
what could be the root cause, how to debug further. The issue is only reproducible on real device . The Code works fine on Simulator...Any Suggestion..for debugging the issue / any workaround...

**Comment by imurchie** [comment] 2017-04-14 14:59
I'm looking into it. I have no real advice on how to debug, since it doesn't really make sense.

**Comment by epankaj1** [comment] 2017-04-14 15:00
WebElement myElement = driver.findElementByAccessibilityId("Next");
            org.openqa.selenium.Point myPoint = myElement.getLocation();
            int x = myPoint.x;
            int y = myPoint.y;

        JavascriptExecutor js = (JavascriptExecutor) driver;
        HashMap<String, Object> tapObject = new HashMap<String, Object>();
        //tapObject.put("fromX",myPoint.x);
     //tapObject.put("fromY",myPoint.y);
     
     tapObject.put("fromX",x);
     tapObject.put("fromY",y);
     
     js.executeScript("mobile: tap", tapObject);    

// do i need to write code to tap ?

**Comment by epankaj1** [comment] 2017-04-14 15:03
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md  ( i was checking this...)

**Comment by epankaj1** [comment] 2017-04-14 15:09
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"7A930B04-FBE3-4156-B4C9-DE5C778BBFFE","type":"XCUIElementTypeButton","label":"Next"},"sessionId":"ED6F676C-A23E-4165-BE39-627C039CB502","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"7A930B04-FBE3-4156-B4C9-DE5C778BBFFE","type":"XCUIElementTypeButton","label":"Next"}
[HTTP] <-- POST /wd/hub/session/299691cb-542b-4347-81d6-747851e55f3c/element 200 221 ms - 168 
[HTTP] --> GET /wd/hub/session/299691cb-542b-4347-81d6-747851e55f3c/element/7A930B04-FBE3-4156-B4C9-DE5C778BBFFE/location {}
[debug] [MJSONWP] Calling AppiumDriver.getLocation() with args: ["7A930B04-FBE3-4156-B4C9-DE5C778BBFFE","299691cb-542b-4347-81d6-747851e55f3c"]
[debug] [XCUITest] Executing command 'getLocation'
[debug] [JSONWP Proxy] Proxying [GET /element/7A930B04-FBE3-4156-B4C9-DE5C778BBFFE/rect] to [GET http://localhost:8100/session/ED6F676C-A23E-4165-BE39-627C039CB502/element/7A930B04-FBE3-4156-B4C9-DE5C778BBFFE/rect] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 240,\n    \"x\" : 200,\n    \"width\" : 200,\n    \"height\" : 50\n  },\n  \"sessionId\" : \"ED6F676C-A23E-4165-BE39-627C039CB502\",\n  \"status\" : 0\n}"
[debug] [MJSONWP] Responding to client with driver.getLocation() result: {"x":200,"y":240}
[HTTP] <-- GET /wd/hub/session/299691cb-542b-4347-81d6-747851e55f3c/element/7A930B04-FBE3-4156-B4C9-DE5C778BBFFE/location 200 135 ms - 89 
[HTTP] --> POST /wd/hub/session/299691cb-542b-4347-81d6-747851e55f3c/execute {"script":"mobile: tap","args":[{"x":200,"y":240}]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: tap",[{"x":200,"y":240}],"299691cb-542b-4347-81d6-747851e55f3c"]
[debug] [XCUITest] Executing command 'execute'
[debug] [JSONWP Proxy] Proxying [POST /wda/tap/0] to [POST http://localhost:8100/session/ED6F676C-A23E-4165-BE39-627C039CB502/wda/tap/0] with body: {"x":200,"y":240}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoint: /session/ED6F676C-A23E-4165-BE39-627C039CB502/wda/tap/0 -- http://localhost:8100/ with parameters {\n    wildcards =     (\n        \"session/ED6F676C-A23E-4165-BE39-627C039CB502/wda/tap/0\"\n    );\n}","sessionId":"ED6F676C-A23E-4165-BE39-627C039CB502","status":1}
[HTTP] <-- POST /wd/hub/session/299691cb-542b-4347-81d6-747851e55f3c/execute 500 13 ms - 392 
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted

**Comment by epankaj1** [comment] 2017-04-14 15:31
I am getting the same issue for Scroll 

JavascriptExecutor js = (JavascriptExecutor) driver; 
			HashMap<String, String> scrollObject = new HashMap<String, String>();
			scrollObject.put("direction", "down"); 
			js.executeScript("mobile: scroll", scrollObject);

**Comment by epankaj1** [comment] 2017-04-14 15:32
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",20000,"025d9df2-3319-4840-a399-a92d770a6c22"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] Set implicit wait to 20000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/025d9df2-3319-4840-a399-a92d770a6c22/timeouts 200 3 ms - 76 
[HTTP] --> POST /wd/hub/session/025d9df2-3319-4840-a399-a92d770a6c22/execute {"script":"mobile: scroll","args":[{"direction":"down"}]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: scroll",[{"direction":"down"}],"025d9df2-3319-4840-a399-a92d770a6c22"]
[debug] [XCUITest] Executing command 'execute'
[debug] [BaseDriver] Waiting up to 20000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/CB3F3A16-6429-47F9-B9FD-C6BAB755CA70/element] with body: {"using":"class name","value":"XCUIElementTypeApplication"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"4576128E-0F67-4576-A83D-1017A1D20FA1","type":"XCUIElementTypeApplication","label":"UICatalog"},"sessionId":"CB3F3A16-6429-47F9-B9FD-C6BAB755CA70","status":0}
[debug] [JSONWP Proxy] Proxying [POST /wda/element/4576128E-0F67-4576-A83D-1017A1D20FA1/scroll] to [POST http://localhost:8100/session/CB3F3A16-6429-47F9-B9FD-C6BAB755CA70/wda/element/4576128E-0F67-4576-A83D-1017A1D20FA1/scroll] with body: {"direction":"down"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoint: /session/CB3F3A16-6429-47F9-B9FD-C6BAB755CA70/wda/element/4576128E-0F67-4576-A83D-1017A1D20FA1/scroll -- http://localhost:8100/ with parameters {\n    wildcards =     (\n        \"session/CB3F3A16-6429-47F9-B9FD-C6BAB755CA70/wda/element/4576128E-0F67-4576-A83D-1017A1D20FA1/scroll\"\n    );\n}","sessionId":"CB3F3A16-6429-47F9-B9FD-C6BAB755CA70","status":1}
[HTTP] <-- POST /wd/hub/session/025d9df2-3319-4840-a399-a92d770a6c22/execute 500 196 ms - 484 
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted

**Comment by epankaj1** [comment] 2017-04-14 16:16
WebElement myElement = driver.findElementByAccessibilityId("Next");
            org.openqa.selenium.Point myPoint = myElement.getLocation(); 
        int centerx = myElement.getLocation().getX() + (myElement.getSize().getWidth() / 2);
      int centery = myElement.getLocation().getY() + (myElement.getSize().getHeight() / 2);		

        JavascriptExecutor js = (JavascriptExecutor) driver;
        HashMap<String, Object> tapObject = new HashMap<String, Object>();
       
     tapObject.put("x",centerx);
     tapObject.put("y",centery);
     
     js.executeScript("mobile: tap", tapObject);

// tried to click on the center of the element
// getting unhandled endpoint exception

**Comment by epankaj1** [comment] 2017-04-14 16:18
[debug] [XCUITest] Executing command 'getSize'
[debug] [JSONWP Proxy] Proxying [GET /element/193BD5BB-B997-49A3-954D-09623612BA84/rect] to [GET http://localhost:8100/session/67659CE4-3053-41CD-9290-EA039FC18E82/element/193BD5BB-B997-49A3-954D-09623612BA84/rect] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 240,\n    \"x\" : 200,\n    \"width\" : 200,\n    \"height\" : 50\n  },\n  \"sessionId\" : \"67659CE4-3053-41CD-9290-EA039FC18E82\",\n  \"status\" : 0\n}"
[debug] [MJSONWP] Responding to client with driver.getSize() result: {"width":200,"height":50}
[HTTP] <-- GET /wd/hub/session/50837045-911a-4a95-9f3d-f26a8b411fc8/element/193BD5BB-B997-49A3-954D-09623612BA84/size 200 433 ms - 97 
[HTTP] --> POST /wd/hub/session/50837045-911a-4a95-9f3d-f26a8b411fc8/execute {"script":"mobile: tap","args":[{"x":300,"y":265}]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: tap",[{"x":300,"y":265}],"50837045-911a-4a95-9f3d-f26a8b411fc8"]
[debug] [XCUITest] Executing command 'execute'
[debug] [JSONWP Proxy] Proxying [POST /wda/tap/0] to [POST http://localhost:8100/session/67659CE4-3053-41CD-9290-EA039FC18E82/wda/tap/0] with body: {"x":300,"y":265}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoint: /session/67659CE4-3053-41CD-9290-EA039FC18E82/wda/tap/0 -- http://localhost:8100/ with parameters {\n    wildcards =     (\n        \"session/67659CE4-3053-41CD-9290-EA039FC18E82/wda/tap/0\"\n    );\n}","sessionId":"67659CE4-3053-41CD-9290-EA039FC18E82","status":1}
[HTTP] <-- POST /wd/hub/session/50837045-911a-4a95-9f3d-f26a8b411fc8/execute 500 13 ms - 392 
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted

**Comment by mykola-mokhnach** [comment] 2017-04-14 16:55
@epankaj1 try to remove WDA application from the device and clear xcode cache to make sure you have no leftovers from previous Appium installations

**Comment by epankaj1** [comment] 2017-04-14 17:24
i removed the webdriverAgent by longpressing and clicking on the Cross icon at my iphone. Then Checked in iTunes...i dont see this app. Then i opened the project in xcode 8.3.1 and product-> clean  ( got message cleaned) ...do i need to do anything else

**Comment by imurchie** [comment] 2017-04-14 17:25
rm -rf /Users/watsonhealth/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy

**Comment by epankaj1** [comment] 2017-04-14 18:02
Thanks a lot , i run the above command and build the WDA again from Xcode 8.3.1 and script worked fine...for all my scripts...really appreciate your help...

**Comment by mykola-mokhnach** [comment] 2017-04-15 05:50
closed as resolved

**Closed by mykola-mokhnach** 2017-04-15 05:50 UTC
Labels: iOS, XCUITest

**Comment by shubhamdubey0011** [comment] 2018-11-16 12:40
> brdadhpuduowllgivnnvuygpwhzy

"brdadhpuduowllgivnnvuygpwhzy"  - do i have to use the same arbitrary  string ?
