### ISSUE TITLE
unzipping trace.zip  file give me alot of folders instead of one trace file 

### ISSUE THREAD

**Issue by Hamzastreamwide** [appium/appium#14804] opened 2020-10-12 13:58 UTC
## The problem

I launched a performance test with an ios app using time profiler instrument after getting back instruments trace.zip file 
i unzip it and i got folders instead of one trace file . like the unzipping process didnt work correctly 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.2
* Desktop OS/version used to run Appium: catalina 10.15.6 (19G2021)
* Real device or emulator/simulator: ipad 13.6
xcode : 12

## Link to Appium logs

https://gist.github.com/Hamzastreamwide/0592918c6f10856b4ed7112c2a4c367a

## Code To Reproduce Issue [ Good To Have ]

   @Test
    public void testAppActivity() throws Exception {

        try {
            HashMap<String, Object> args = new HashMap<>();
            args.put("timeout", 60000);
            args.put("pid", "current");
            args.put("profileName", "Time Profiler");
            driver.executeScript("mobile: startPerfRecord", args);

            testchannelnumbers(driver);
            OpenChannelDeviceOne(driver);
            PTT(driver);

            args = new HashMap<>();
            args.put("profileName", "Time Profiler");
            String b64Zip = (String)driver.executeScript("mobile: stopPerfRecord", args);
            byte[] bytesZip = Base64.getMimeDecoder().decode(b64Zip);
            FileOutputStream stream = new FileOutputStream(traceZip);
            stream.write(bytesZip);
            stream.close();
        } finally {
            driver.quit();

        }
    }

[trace.zip](https://github.com/appium/appium/files/5365550/trace.zip)

**Comment by mykola-mokhnach** [comment] 2020-10-12 14:16
Duplicate of https://github.com/appium/appium/issues/14738

Simply extract the unpacked content into a folder and rename that folder to "<your_name>.xctrace". I assume the way these files are archived is nor very obvious. I'll fix that

**Comment by Hamzastreamwide** [comment] 2020-10-12 14:20
i will try that thanks

**Comment by Hamzastreamwide** [comment] 2020-10-12 14:31
it worked but i renamed it <name>.trace

**Comment by mykola-mokhnach** [comment] 2020-10-13 14:33
the patch has been published to appium@beta

**Closed by mykola-mokhnach** 2020-10-13 14:33 UTC
Labels: Bug
