### ISSUE TITLE
Issue with Appium inspector :"jsonwire-error":{"detail":"An unknown server-side error occurred while processing the command.","status":13,"summary":"UnknownError"},"message":"[source()] Error response status: 13, ,

### ISSUE THREAD

**Issue by chennareddy08** [appium/appium#9549] opened 2017-10-27 21:30 UTC
## The problem

Could not obtain source: {"cause":{"sessionId":"12509fca-f7ef-4709-a9f3-f238b073943d","status":13,"value":{"message":"An unknown server-side error occurred while processing the command. Original error: Cannot get '(null)' source of the current application"}},"jsonwire-error":{"detail":"An unknown server-side error occurred while processing the command.","status":13,"summary":"UnknownError"},"message":"[source()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Cannot get '(null)' source of the current application","status":13}

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.7.1
* Desktop OS/version used to run Appium:Version 1.2.6 (1.2.6)
* Node.js version (unless using Appium.app|exe): Appium.app
* Mobile platform/version under test:ipod touch 9.3.5
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/chennareddy08/4f91749b6e001611d48f87512b75a85c

## Code To Reproduce Issue [ Good To Have ]
Run appium desktop 
Click on start inspector session  and observe
Try to launch inspector using ipod touch 9.3.5

OR call getPageSource()  more than 2  time in the script 

![34](https://user-images.githubusercontent.com/8956347/32125951-ee9a84da-bb8b-11e7-9a92-a576a9c6b66a.png)
[appiumissue.txt](https://github.com/appium/appium/files/1423517/appiumissue.txt)

**Comment by mykola-mokhnach** [comment] 2017-10-27 21:35
Duplicate of https://github.com/facebook/WebDriverAgent/issues/752

**Closed by mykola-mokhnach** 2017-10-27 21:35 UTC

**Comment by mykola-mokhnach** [comment] 2017-10-27 21:37
WebDriverAgent detected that application under test is not running anymore and so then it cannot get the source.

**Comment by hzgoucheng** [comment] 2017-11-01 05:41
@mykola-mokhnach The "Application local.pid.X is not running" does not happen in Xcode8 on ios 10, but often happens in Xcode 9 on ios 10，and sometimes cannot get the page source。Then,I
decompiled XCTest.framework of Xcode8 and Xcode9, then found the
source code of applicationWithPID and appWithPID is very different. So, i suspect that the "applicationWithPID" is not compatible ios 10(ios 10-)?
