### ISSUE TITLE
iOS 12.1 - Incorrect value retrieved from XCUIElementTypeSwitch

### ISSUE THREAD

**Issue by Cory-Berg** [appium/appium#13738] opened 2019-12-17 15:06 UTC
## The problem

Toggling system settings on an XS Max iOS 12.1.2 value retrieved for switches is always zero.
Run the same script against an X on iOS 13.2.3 and the appropriate values are returned.

Example is toggling airplane mode.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS 10.15.2
* Node.js version (unless using Appium.app|exe): 13.3.0
* Npm or Yarn package manager: 6.13.4
* Mobile platform/version under test: iOS 12.1.2 && 13.2.3
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

Launching system settings. Finding airplane mode toggle. Reading value and flipping the switch if not desired value. On iOS 12 the values being returned with updated system are always returning '0' even when the switch has been toggled on.

## Link to Appium logs

https://gist.github.com/Cory-Berg/8c4887d82ec540193885d1569907678f

**Comment by mykola-mokhnach** [comment] 2019-12-17 16:52
Duplicate of https://github.com/appium/appium/issues/13691

**Closed by mykola-mokhnach** 2019-12-17 16:52 UTC
