### ISSUE TITLE
Can't create session with JSONWP protocol with selenium grid

### ISSUE THREAD

**Issue by bastenf** [appium/appium#11786] opened 2018-12-05 08:20 UTC
## The problem
We try to use JSONWP mode to do some special actions that W3C can't do.
**If we don't use the selenium grid, directly call appium, it created with JSONWP mode**

But if we use selenium grid, appium created session with W3C mode.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10
* Last Appium version that did not exhibit the issue (if applicable):1.8.2-beta
* Desktop OS/version used to run Appium:mac os 10.13.5
* Node.js version (unless using Appium.app|exe):10.5
* Mobile platform/version under test:android 7
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:CLI

## Details
We used selenium grid 3.12 and the latest 3.14, for the client, we use java_client 6.1.0

Appium determine JSONWP or W3C in this article https://github.com/dpgraham/appium-w3c-explanation/blob/master/README.md

also attached the log that grid passed to appium, we found in the log, grid added "capabilities" capability, that's lead to appium create W3C session.

**I think appium's determination is not so good, since selenium is stepping to W3C, the  "capabilities" will be always there. In my opinion, could we pass the forceMjsonwp capability to appium server, let server to determine which one to use?**

## Link to Appium logs

[HTTP] {"desiredCapabilities":{"appPackage":"com.tencent.mm","server:CONFIG_UUID":"060d53a2-0b8d-498b-9b79-7ad912f70428","clearSystemFiles":true,"noReset":true,"chromeUseRunningApp":"true","deviceName":"uuuu","chromeAndroidProcess":"com.tencent.mm:tools","appium:bastenTestName":"com.cntaiping.tpyb.tests.dwt.UATCarCopy","appium:bastenHub":"192.168.8.15","chromedriverExecutable":"/basten/selenium/chromedriver_2_28","newCommandTimeout":120,"automationName":"UIAutomator2","skipUnlock":true,"unicodeKeyboard":true,"platformName":"android","udid":"M960BDQG229P9","applicationName":"TPYB","resetKeyboard":true,"recreateChromeDriverSessions":false,"noSign":true,"appActivity":"com.tencent.mm.ui.LauncherUI","autoGrantPermissions":true,"fastReset":false,"autoAcceptAlerts":true},"capabilities":{"firstMatch":[{"appium:bastenHub":"192.168.8.15","appium:bastenTestName":"com.cntaiping.tpyb.tests.dwt.UATCarCopy","platformName":"android","server:CONFIG_UUID":"060d53a2-0b8d-498b-9b79-7ad912f70428"}]}}

**Comment by mykola-mokhnach** [comment] 2018-12-05 10:01
duplicate of https://github.com/appium/appium/issues/11599

**Closed by mykola-mokhnach** 2018-12-05 10:01 UTC
