### ISSUE TITLE
Collection view cell cannot be find on screen

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#11306] opened 2018-09-03 13:54 UTC
## The problem
Originally what I was trying to do is to search from text on UICollectionViewCell with iOS predicate, what I resized eventually is that the cell is not even recognise by Appium. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): Unknonwn
* Desktop OS/version used to run Appium: Desktop
* Node.js version (unless using Appium.app|exe):v8.11.2
* Mobile platform/version under test: iOS 11
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium app.

## Details
See the snapshot and you will understand everything. you can see there that Appium cannot reach the cell where it says TestLiveChannel

I even tried force adding this in app native code for each cell:
[cell setIsAccessibilityElement:YES];
[cell setAccessibilityIdentifier:@"cell_boaz"];

## Link to Appium logs
Will attach if necessary

**Comment by BoazWarshawsky** [comment] 2018-09-03 13:54
![screen shot 2018-09-03 at 16 34 27](https://user-images.githubusercontent.com/32813176/44990552-00ea9c80-af9a-11e8-8a5d-2e9e0e495f88.png)

**Comment by KazuCocoa** [comment] 2018-09-09 14:31
@BoazWarshawsky 
Can you get the page source with `useJSONSource: true` ? ( https://github.com/appium/appium-xcuitest-driver ) Not via the desktop inspector. 

> I even tried force adding this in app native code for each cell:
> [cell setIsAccessibilityElement:YES];
> [cell setAccessibilityIdentifier:@"cell_boaz"];

Couldn't you find the element with `accessibility_id` strategy, right?

**Comment by michelsousacarvalho** [comment] 2018-09-14 13:59
I have the same problem. You fixed it?

**Comment by gabrieldezena** [comment] 2018-09-14 14:00
@BoazWarshawsky I have the same problem. You fixed it? Help me please.

**Comment by michelsousacarvalho** [comment] 2018-09-17 14:35
@BoazWarshawsky I was the same problem, I removed the accessibility id of collectionView and I got access collectionViewCell. If you need access to a label inside collectionViewCell you need remove accessibility id of collectionViewCell too.
When put an accessibility id on parent, do not have access to child's views.

**Comment by KazuCocoa** [comment] 2018-09-18 04:44
@michelsousacarvalho 
thanks for the tips. I didn't know that ... > `collectionView` and `collectionViewCell`

**Comment by mykola-mokhnach** [comment] 2018-09-23 14:01
Closed as duplicate of https://github.com/appium/appium/issues/6517

**Closed by mykola-mokhnach** 2018-09-23 14:01 UTC
