### ISSUE TITLE
Appium : Cannot get 'xml' source of the current application

### ISSUE THREAD

**Issue by shivani-rana** [appium/appium#13725] opened 2019-12-16 09:34 UTC
While trying to launch application through appium desktop 1.15.1 for iOS 13.3, and refreshing the page source to inspect elements facing below issue :

Matched '/source' to command name 'getPageSource'
[debug] [WD Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/6E9991CD-47DA-4C4B-9890-B63933A4FA01/source] with no body
[debug] [WD Proxy] Got response with status 500: {
[debug] [WD Proxy]   "value" : {
[debug] [WD Proxy]     "error" : "unknown error",
[debug] [WD Proxy]     "message" : "Cannot get 'xml' source of the current application",
[debug] [WD Proxy]     "traceback" : ""
[debug] [WD Proxy]   },
[debug] [WD Proxy]   "sessionId" : "6E9991CD-47DA-4C4B-9890-B63933A4FA01"
[debug] [WD Proxy] }
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [XCUITest] Taking screenshot with WDA
[debug] [WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[debug] [WD Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/6E9991CD-47DA-4C4B-9890-B63933A4FA01/screenshot] with no body
[debug] [MJSONWP (73907e02)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot get 'xml' source of the current application
[debug] [MJSONWP (73907e02)]     at errorFromW3CJsonCode (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:802:25)
[debug] [MJSONWP (73907e02)]     at ProxyRequestError.errorFromW3CJsonCode [as getActualError] (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:685:14)
[debug] [MJSONWP (73907e02)]     at JWProxy.getActualError [as command] (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:259:19)

**Comment by mykola-mokhnach** [comment] 2019-12-16 13:25
Duplicate of https://github.com/appium/appium/issues/13705

**Closed by mykola-mokhnach** 2019-12-16 13:25 UTC
