### ISSUE TITLE
AppiumDesktop v1.13, Android 8 UIA2 element not found while Android6 UIA1 works well

### ISSUE THREAD

**Issue by JeffKAndroid** [appium/appium#13204] opened 2019-09-08 04:20 UTC
## The problem
With AppiumDesktop v1.13.0, on Android 8 device, UIA2, test failed with element not found. While on  Android 6 device,  UIA1, the same code works well.

## Environment
* Appium Desktop ver 1.13.0
* Windows 10, Windows 8
* Real device Android 8 and Android 6

## Details
Same java testing code, real device Android 8 and Android 6 running the same app. Android 8 device UIA2 stuck and then failed, checking log know it's "An element could not be located on the page using the given search parameters." the element's ID is "btnSignupLogin".
Because there is a 20 seconds timeout java code wait before the error is thrown, during the wait, if I finger touch any element of the page on phone, then the element can be found by code and testing app continues until it hits the next "element not found".
Output Page Source right before the waiting and the ID "btnSignupLogin" can be found in the Page Source.
the Android 6 works well with UIA1.

## Link to Appium logs
Android 6 UIA1 success log:
https://github.com/JeffKAndroid/public/blob/master/android6.ok.txt

Android 8 UIA2 failed log:
https://github.com/JeffKAndroid/public/blob/master/android8.uia2.ele.not.found.txt
Page Source:
https://github.com/JeffKAndroid/public/blob/master/android8.uia2.ele.not.found.page.source.txt

Android 8 UIA2 manually touching screen during wait leads to success:
https://github.com/JeffKAndroid/public/blob/master/android8.uia2.touch.then.ok.txt

**Comment by mykola-mokhnach** [comment] 2019-09-08 06:12
Is the element present in page source?

**Comment by JeffKAndroid** [comment] 2019-09-08 12:47
I don't know how to check "page source". Just updated my post with something new I found: during the wait finger touch any element of the screen then testing code found the element properly.

**Comment by aiden520** [comment] 2019-09-08 12:55
**1. Environment**

-  Appium Desktop ver 1.13.0
- MacOS 10.15
- Real device Android 9

**2. Details**

today i found the same problem on mac but UIA1 is ok.  if switching to UIA2, the 'WD PROXY' server is always blocked after running a period of time, so my program cannot get response from it

**Comment by mykola-mokhnach** [comment] 2019-09-08 13:12
Possible duplicate of https://github.com/appium/appium/issues/12250

Without the actual page source I cannot suggest anything more.

**Comment by JeffKAndroid** [comment] 2019-09-09 00:52
@ mykola-mokhnach Please help to figure out the issue. I got Page Source and updated my post with the new link to Page Source. The ID "btnSignupLogin" that couldn't be found by appium is in the page source.

**Comment by JeffKAndroid** [comment] 2019-09-09 00:56
and I think the issue is different from #12250 because there is no web view in my app.

**Comment by KazuCocoa** [comment] 2019-09-09 01:07
How about getting it as `com.xxxx:id/btnSignupLogin` instead of `btnSignupLogin`?

**Comment by mykola-mokhnach** [comment] 2019-09-09 04:54
> and I think the issue is different from #12250 because there is no web view in my app.

It does not matter which view type it is. UIA2 might not trigger events that the application under test expects, so it does not show the button

**Comment by JeffKAndroid** [comment] 2019-09-09 13:38
@KazuCocoa Yes I tried with "com.xxx:id/yyyy" and had the same issue.

**Comment by JeffKAndroid** [comment] 2019-09-09 13:41
How do we explain this: if manually touch the screen during wait then the button can be found. 
Android 8 UIA2 manually touching screen during wait leads to success:
https://github.com/JeffKAndroid/public/blob/master/android8.uia2.touch.then.ok.txt

**Comment by mykola-mokhnach** [comment] 2019-09-13 08:49
Closed as not an issue

**Closed by mykola-mokhnach** 2019-09-13 08:49 UTC
Labels: NotABug, UIAutomator2

**Comment by JeffKAndroid** [comment] 2019-09-14 19:51
@mykola-mokhnach so you think I can do something in my java code so that appium will act differently and then the button can be found automatically without manual interaction? What kind of code change it may look like?
