### ISSUE TITLE
Getting Socket Hang Up error

### ISSUE THREAD

**Issue by sudhanshuprakash** [appium/appium#15042] opened 2021-01-21 13:10 UTC
## The problem

I am trying to run multiple test cases using testng. But everytime after 4 or 5 test cases I am getting "[ERROR] An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up (WARNING: The server did not provide any stacktrace information
)"

## Environment
Appium version (or git revision) that exhibits the issue: 1.18.0
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium:10
Node.js version (unless using Appium.app|exe):v12.14.0
Npm or Yarn package manager:
Mobile platform/version under test:7.1.1
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: Appium.exe

## Details

https://gist.github.com/sudhanshuprakash/74e3c462e14db9f13f04ca29f5eb1049#file-appium-socket-hang-up

## Link to Appium logs
https://gist.github.com/sudhanshuprakash/5b7a0a57c3ead847e9767316262e8399#file-appium-logs

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2021-01-21 14:35
Duplicate of https://github.com/appium/appium/issues/9676

Make sure you properly close all you sessions before staring new ones.

**Closed by mykola-mokhnach** 2021-01-21 14:35 UTC

**Comment by sudhanshuprakash** [comment] 2021-01-21 14:59
@mykola-mokhnach so you mean I have to provide driver.quit() at end of every test case ?
