### ISSUE TITLE
After pop up appium can't find any elements on hybrid app

### ISSUE THREAD

**Issue by vladbelo** [appium/appium#14011] opened 2020-03-02 00:58 UTC
## The problem
I have a Hybrid Android application with native views and webviews. The ‘click’ WebElement method works fine for native views before pop up. When I delete a message there is a pop up to confirm a deletion and once  the popup is closed I am unable to click on any elements. Before the pop up everything clicks but after pop up  even DOM does not appear with elements.  I tried putting app in background for couple seconds and thread sleeping and still does not work. When I switch my app from native to web view context it clicks on different element it feels like   location coordinates and the actual coordinates are different in webview context.

## [Environment](url)
* Appium version 1.15.1
*Mac OsCatalina
* Android Version 9.0
Galaxy S10 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/vladbelo/e5ca924f2b4958c1c39006a1cda78ebb

## Code To Reproduce Issue [ Good To Have ]
```

@AndroidFindBy(xpath = "(//android.view.View[contains(@resourceid,'titlebar')]//android.view.View[contains(@resource-id,'button')])[2]")
@AndroidFindBy(xpath = "(//android.view.View[contains(@resource-id,'titlebar')]//android.view.View[contains(@resource-id,'button')])[1]")
private MobileElement saveButtonsss;

@AndroidFindBy(uiAutomator = "new UiSelector().resourceId(\"deleteImg\")")
 private MobileElement deleteMessage;

@AndroidFindBy(uiAutomator = "new UiSelector().className(\"android.view.View\").textMatches(\"(Yes\")")
private MobileElement yesConfirmPopUp;


deleteMessage.click(); // Pop up pop ups
yesConfirmPopUp.click(); //Confirm select yes on pop up
if (yesText.equalsIgnoreCase("Delete")) {
           saveButtonsss.click(); // This element does not work still same page screen native screen.

// Tried with webview option clicks on different element outside of  the original element

driver.contextView("WebView");
/WebElement saveButton = driver.findElement(By.xpath("//span[contains(@class,'x-button-icon x-font-icon x-shown ico-title-save')]"));
  saveButton.click(); //webview clicks on wrong part of the page 



```

Elements before  pop up displaying
<img width="1268" alt="Screen Shot 2020-03-01 at 6 18 08 PM" src="https://user-images.githubusercontent.com/3719297/75640240-2dac5e00-5be9-11ea-97aa-9737adb0c4b3.png">

Elements after pop up do not display
<img width="1118" alt="Screen Shot 2020-03-01 at 6 25 31 PM" src="https://user-images.githubusercontent.com/3719297/75640516-32bddd00-5bea-11ea-9f63-463a2ba6f32d.png">

WebView Elements After I switched to WebView Context 
<img width="1215" alt="webViewElements" src="https://user-images.githubusercontent.com/3719297/75638816-9e9c4780-5be2-11ea-86a5-2baafcf2c43c.png">

**Comment by mykola-mokhnach** [comment] 2020-03-02 06:26
Duplicate of https://github.com/appium/appium/issues/8582

**Comment by mykola-mokhnach** [comment] 2020-03-02 06:27
I don't think there is anything we can do about that from Appium side, since the page source is generated by the chrome driver. I would try to switch to native context, handle the alert and then switch back

**Comment by mykola-mokhnach** [comment] 2020-03-02 06:29
In the worst case one could try to fully reinit the web view by closing the session and starting it again with noReset option

**Comment by mykola-mokhnach** [comment] 2020-03-02 06:31
> When I switch my app from native to web view context it clicks on different element it feels like location coordinates and the actual coordinates are different in webview context.

This is quite possible and deprends on how the web view exposes its content to the accessiblity system. Unfortunately, there's nothing we could influence in that process (except of working in web view context)

**Comment by mykola-mokhnach** [comment] 2020-03-05 07:18
Closed because of no response

**Closed by mykola-mokhnach** 2020-03-05 07:18 UTC
Labels: Mobile Chrome, NeedsInfo

**Comment by ndeztea** [comment] 2022-06-10 10:17
@mykola-mokhnach  I get similiar issue, which when hybrid app open webview page, and on that webview open popup modal.. that modal cant be detected by appium inspector 
<img width="1265" alt="Screen Shot 2022-06-10 at 17 15 29" src="https://user-images.githubusercontent.com/5906480/173044869-793438b8-a6dd-4a01-aa80-3315ca9143e1.png">

**Comment by lucas234** [comment] 2022-12-06 06:19
you can try： add Desired Capabilities params：autoGrantPermissions=ture

**Comment by ridepaldev** [comment] 2024-07-08 12:36
I am getting same error the popup is not showing in appium inserter.
