### ISSUE TITLE
iOS 13 beta native test fails as webdriver cannot find the keyboard

### ISSUE THREAD

**Issue by sadafyadegari** [appium/appium#13080] opened 2019-08-15 02:21 UTC
## The problem

iOS 13 beta native test fails as the webdriver cannot find the keyboard even though keyboard is present on the screen.

## Environment

* Appium version (or git revision) that exhibits the issue: 68981b79b6cf904c0188c72e899c70ea1f9d4d3e
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): v12.5.0
* Npm or Yarn package manager: npm 6.9.0
* Mobile platform/version under test: iOS 13
* Real device or emulator/simulator: iPhone Xs Max
* Appium CLI or Appium.app|exe: Appium-Python-Client 0.46

## Details

test fails as iOS 13 beta native test fails as the webdriver cannot find the keyboard even though keyboard is present on the screen.

## Link to Appium logs

[Appium logs](https://gist.github.com/sadafyadegari/bfd194817c198ce095e1a8f55ad6b47a) 

## Code To Reproduce Issue [ Good To Have ]

[python test](https://gist.github.com/sadafyadegari/b5341e8e73268bdd64c193caade89b66)

**Comment by mykola-mokhnach** [comment] 2019-08-15 06:26
Duplicate of https://github.com/appium/appium/issues/12960

**Closed by mykola-mokhnach** 2019-08-15 06:26 UTC
