### ISSUE TITLE
[Android] cannot refresh Appium

### ISSUE THREAD

**Issue by dana-h-cha** [appium/appium#15169] opened 2021-03-08 01:55 UTC
## The problem

cannot refresh Appium. Whenever I click the refresh button, it gives me like: 
Call to 'source' failed
[sessionCapabilities()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: 'GET /' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.0 -beta / 1.20.2 both
* Desktop OS/version used to run Appium: Windows 10
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium.exe

## Details

it suddenly gave me this error when I clicked the refresh button while running my script and then it keeps happening

## Link to Appium logs
[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/400e441d-7ef8-4215-bdd6-efb87cf51307/context[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP (400e441d)][39m Calling AppiumDriver.getCurrentContext() with args: ["400e441d-7ef8-4215-bdd6-efb87cf51307"]
[debug] [35m[MJSONWP (400e441d)][39m Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/400e441d-7ef8-4215-bdd6-efb87cf51307/context [39m[32m200[39m [90m1 ms - 84[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/400e441d-7ef8-4215-bdd6-efb87cf51307[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP (400e441d)][39m Calling AppiumDriver.getSession() with args: ["400e441d-7ef8-4215-bdd6-efb87cf51307"]
[debug] [35m[UiAutomator2][39m Getting session details from server to mix in
[debug] [35m[MJSONWP (400e441d)][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
[debug] [35m[MJSONWP (400e441d)][39m     at UIA2Proxy.command (C:\Users\HeejinCha\AppData\Local\Programs\Appium\resources\app\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:275:13)
[debug] [35m[MJSONWP (400e441d)][39m     at runMicrotasks (<anonymous>)
[debug] [35m[MJSONWP (400e441d)][39m     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/400e441d-7ef8-4215-bdd6-efb87cf51307 [39m[31m500[39m [90m4 ms - 353[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[WD Proxy][39m Got response with status 404: {"sessionId":"61781e67-26a5-4a46-ab81-079827606bbe","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.findElement(FindElement.java:91)\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:68)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:261)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:255)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerCont...

**Comment by KazuCocoa** [comment] 2021-03-08 02:49
Could you share the logcat as GitHub GIST to see the below detail?

> [debug] �[35m[UiAutomator2]�[39m Getting session details from server to mix in
[debug] �[35m[MJSONWP (400e441d)]�[39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
[debug] �[35m[MJSONWP (400e441d)]�[39m at UIA2Proxy.command (C:\Users\HeejinCha\AppData\Local\Programs\Appium\resources\app\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:275:13)
[debug] �[35m[MJSONWP (400e441d)]�[39m at runMicrotasks ()
[debug] �[35m[MJSONWP (400e441d)]�[39m at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by dana-h-cha** [comment] 2021-03-08 04:27
https://gist.github.com/dana-h-cha/132e2bde20862ea0ade0b8eeffd75863
did you mean this?

**Comment by mykola-mokhnach** [comment] 2021-03-08 07:53
> https://gist.github.com/dana-h-cha/132e2bde20862ea0ade0b8eeffd75863
> did you mean this?

No, this is the server log. Please attach the device log instead

**Comment by dana-h-cha** [comment] 2021-03-08 08:17
https://gist.github.com/dana-h-cha/4540a44eb6c352338d162801a7bf86c8

**Comment by mykola-mokhnach** [comment] 2021-03-08 10:07
> https://gist.github.com/dana-h-cha/4540a44eb6c352338d162801a7bf86c8

Unfortunately this log is not helpful. Please attach the log for the time period when the 

> Original error: 'GET /' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

issue happens

**Comment by dana-h-cha** [comment] 2021-03-09 01:31
it seems it gives me a different log whenever I run, but this is the latest one.

https://gist.github.com/dana-h-cha/27c0ba76ce45bc71849077b2142d37ae

**Comment by KazuCocoa** [comment] 2021-03-09 02:42
Was this entire logcat when the issue happened?

_UiAutomator2 server because the instrumentation process is not running (probably crashed)_ message means perhaps the device has something messages like crash, error or warning corresponding to uiautomator, appium or Android system.
If your attached one was when just you got `Original error: 'GET /' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details`, perhaps earlier messages have the cause.

Could you attach more wider time period? (It is fine to attach entire the logcat from your test started)

**Comment by dana-h-cha** [comment] 2021-03-09 04:00
Here is the full logcat. I ran Appium again, but it seems different from the pre one.

https://gist.github.com/dana-h-cha/a29e14c7010218aa23cad2f611234470

**Comment by mykola-mokhnach** [comment] 2021-03-09 07:16
> First and last ten lines of log:

It seems like your phone settings actually limit the log size. Please change these settings, so we could get the full log.

**Comment by dana-h-cha** [comment] 2021-03-09 08:12
Oh, sorry about it. Here is the full log. The error's probably at the very beginning.
https://gist.github.com/dana-h-cha/8accd3a1864d46ed90d57300fe31cefb

**Comment by mykola-mokhnach** [comment] 2021-03-09 09:11
From the server log it looks like there are two parallel sessions and the getSession command is being sent to a session, which is crashed/stopped. Please review your framework logic there. I don't see any issues on the server side there.

**Comment by dana-h-cha** [comment] 2021-03-10 01:24
> From the server log it looks like there are two parallel sessions and the getSession command is being sent to a session, which is crashed/stopped. Please review your framework logic there. I don't see any issues on the server side though.

Can you tell me where I should check please? cuz I didn't do anything except for setting desired capabilities on Appium and my code and other things look fine..

**Comment by KazuCocoa** [comment] 2021-03-10 02:52
The original error is probably in https://github.com/appium/appium-uiautomator2-driver/blob/896533f05612d88eb1389814903afc5f88175251/lib/uiautomator2.js#L23-L29

We assumed your instrumentation process has been stopped by some reason.
https://github.com/appium/appium-uiautomator2-driver/blob/896533f05612d88eb1389814903afc5f88175251/lib/uiautomator2.js#L261-L279

You could find a message like `The process has exited with code` in your appium log what exit code the instrumentation process got.


---

Based on your attached log, below sections were possibly such stoping instrumentation processes.

```
[2021-03-09T17:07:42+0900] [ALL] 03-09 08:07:42.045  4316  4316 D AndroidRuntime: Calling main entry com.android.commands.am.Am
[2021-03-09T17:07:42+0900] [ALL] 03-09 08:07:42.053   526  1499 I ActivityManager: Force stopping io.appium.uiautomator2.server appid=10160 user=0: start instr
[2021-03-09T17:07:42+0900] [ALL] 03-09 08:07:42.054   526  1499 I ActivityManager: Killing 3979:io.appium.uiautomator2.server/u0a160 (adj 0): stop io.appium.uiautomator2.server due to start instr
[2021-03-09T17:07:42+0900] [ALL] 03-09 08:07:42.056   526  1499 W ActivityManager: Crash of app io.appium.uiautomator2.server running instrumentation ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner}
[2021-03-09T17:07:42+0900] [ALL] 03-09 08:07:42.056   526  1499 I ActivityManager: Force stopping io.appium.uiautomator2.server appid=10160 user=0: finished inst
[2021-03-09T17:07:42+0900] [ALL] 03-09 08:07:42.058  3964  3978 W Binder  : Caught a RuntimeException from the binder stub implementation.
[2021-03-09T17:07:42+0900] [ALL] 03-09 08:07:42.058  3964  3978 W Binder  : java.lang.SecurityException: Calling from not trusted UID!
[2021-03-09T17:07:42+0900] [ALL] 03-09 08:07:42.058  3964  3978 W Binder  : 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
[2021-03-09T17:07:42+0900] [ALL] 03-09 08:07:42.058  3964  3978 W Binder  : 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
[2021-03-09T17:07:42+0900] [ALL] 03-09 08:07:42.058  3964  3978 W Binder  : 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
[2021-03-09T17:07:42+0900] [ALL] 03-09 08:07:42.058  3964  3978 W Binder  : 	at android.os.Binder.execTransactInternal(Binder.java:1159)
[2021-03-09T17:07:42+0900] [ALL] 03-09 08:07:42.058  3964  3978 W Binder  : 	at android.os.Binder.execTransact(Binder.java:1123)
[2021-03-09T17:07:42+0900] [ALL] 03-09 08:07:42.059  3964  3964 D AndroidRuntime: Shutting down VM
[2021-03-09T17:07:42+0900] [ALL] 03-09 08:07:42.062   526  1499 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10160; state: DISABLED
[2021-03-09T17:07:42+0900] [ALL] 03-09 08:07:42.065   526   553 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10160; state: DISABLED
[2021-03-09T17:07:42+0900] [ALL] 03-09 08:07:42.075   287   287 D Zygote  : Forked child process 4333
```

To make more accurate, could you get Appium log `--log-timestamp` and the logcat to compare each timestamp? It will help more to dig the cause in.
https://appium.io/docs/en/writing-running-appium/server-args/

**Comment by dana-h-cha** [comment] 2021-03-11 04:58
https://gist.github.com/dana-h-cha/f17af901eb4739299f7aef2c31530819  - appium log
https://gist.github.com/dana-h-cha/3d9915754307d2a34ce7280802693b05 -logcat
Here are my new logs and the error's probably at the very beginning.
Thanks again.

**Comment by KazuCocoa** [comment] 2021-03-11 05:12
You sent new session requests twice without deleting sessions against emulator-5554 device.
https://gist.github.com/dana-h-cha/f17af901eb4739299f7aef2c31530819#file-gistfile1-txt-L18
https://gist.github.com/dana-h-cha/f17af901eb4739299f7aef2c31530819#file-gistfile1-txt-L369

UIA2 server stopped in the 2nd one. So, the 1st session raised the reported error.
The behavior is expected, so you should fix the 2nd time's request on your side.

**Comment by dana-h-cha** [comment] 2021-03-11 05:24
hmm, okay. but how do I fix it?

**Comment by dana-h-cha** [comment] 2021-03-11 05:25
hmm, okay. but how do I fix it? Is it the problem in the code?

**Comment by KazuCocoa** [comment] 2021-03-11 05:32
I don't know your code/framework, but Appium got two new session requests as my previous comment.

Perhaps you should prevent sending the 2nd one (the below is the request) in your code.

> [2021-03-11 01:35:16][HTTP] --> POST /wd/hub/session
> [2021-03-11 01:35:16][HTTP] {"desiredCapabilities":{"appActivity":"com.enablewow.showtap.ui.SplashActivity","appPackage":"com.enablewow.showtap","platformName":"Android","deviceName":"Galaxy_s10_API_30"},"capabilities":{"firstMatch":[{"appium:appActivity":"com.enablewow.showtap.ui.SplashActivity","appium:appPackage":"com.enablewow.showtap","appium:deviceName":"Galaxy_s10_API_30","platformName":"android"}]}}

**Comment by dana-h-cha** [comment] 2021-03-11 07:14
I use selenium and here's my code for your information
https://gist.github.com/dana-h-cha/ac791495e0304f957025f93479ab3435
It's strange that I didn't do any settings that sending two session requests at one time

**Comment by KazuCocoa** [comment] 2021-03-11 07:35
Your code seems the 2nd one https://gist.github.com/dana-h-cha/f17af901eb4739299f7aef2c31530819#file-gistfile1-txt-L369
Then, probably the 1st one https://gist.github.com/dana-h-cha/f17af901eb4739299f7aef2c31530819#file-gistfile1-txt-L18 was from somewhere on your machine.

How to manage your appium server?
Did you launch https://www.npmjs.com/package/appium directly

**Comment by dana-h-cha** [comment] 2021-03-11 08:54
No. I don't use npm. I ran Appium desktop. or sometimes use appium.exe on cmd.

**Comment by KazuCocoa** [comment] 2021-03-11 08:58
Did you start the inspector before starting your Java code?
The inspector in AD establishes a connection to the embedded appium server. You should not send any new session requests after it.

**Comment by dana-h-cha** [comment] 2021-03-12 03:51
Oh, yes, I did. but wasn't it the right way? I remember I used to work that way, but it worked fine before.

**Comment by KazuCocoa** [comment] 2021-03-12 04:39
Because we improved to watch UIA2 server process on the device. Previous implementation did not catch some issues on UIA2.
Basically, a device should have one session. Appium itself can handle multiple sessions.

**Comment by dana-h-cha** [comment] 2021-03-15 03:44
Hmm, okay. Then is there any other way to connect to the running session? except for using a real device or session override?

**Comment by KazuCocoa** [comment] 2021-03-15 05:16
It depends on clients. Some clients can attach to an existing session with the session id with the regular feature or some tricks. Technically, `curl` command also can communicate with the running session with the session id.

I don't know if the Java client can. Then, https://discuss.appium.io/ may help for such questions. Or Java client's documentation might know.

**Comment by KazuCocoa** [comment] 2021-03-15 05:18
Close this issue for now since this behavior itself was expected for two sessions case.

**Closed by KazuCocoa** 2021-03-15 05:18 UTC
Labels: NotABug
