### ISSUE TITLE
Appium 1.10.0 W3C protocol expects any of script, pageLoad or implicit to be set

### ISSUE THREAD

**Issue by CedricD123** [appium/appium#11880] opened 2018-12-20 08:58 UTC
## The problem

Hi,
I recently upgraded my Appium and XCode to the newer version due to some problems I had when automating iOS, everything works locally, but my devices are connected on a Selenium grid. When I want to run via the grid I get an error message.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: 10.14.2
* Node.js version (unless using Appium.app|exe): 11.5.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iphone7 plus, ipadmini4, iphone8
* Selenium grid: v.3.141.59
* XCode: 10.1

## Details
I use a mac with all the devices connected to it. Via the grid I can remote connect to my devices and run my scripts.
The scripts all start when I try to run, but the implicit wait isn't applied in the scripts.

This is the error I get:
Error: Parameters were incorrect. We wanted "W3C protocol expects any of script, pageLoad or implicit to be set" and you sent {"type":"implicit","ms":30000}

I found people who had this issue before with Appium 1.8. But it should be fixed with the 1.9.0-1 version.

Note (Not sure if this helps):
When we execute the ./Scripts/bootstrap.sh in the WebDriver folder we get 137 problems, but we can still build everything. We tried this on fresh installed mac and we got the same issues.

## Link to Appium logs

https://gist.github.com/CedricD123/2608a896f8b3c04c45482b397efb9e83

**Comment by mykola-mokhnach** [comment] 2018-12-20 14:55
Please provide the full log

**Comment by mykola-mokhnach** [comment] 2018-12-20 15:31
This is a duplicate of https://github.com/appium/appium/issues/10682

The original issues lies in webdriverio client, which does not support W3C protocol.

**Closed by mykola-mokhnach** 2018-12-20 15:31 UTC
Labels: NeedsInfo
