### ISSUE TITLE
[iOS 13.3 only] Cannot find elements on Auth0 page with error XCTDaemonErrorDomain Code=11

### ISSUE THREAD

**Issue by nimaiwalsh** [appium/appium#13731] opened 2019-12-16 22:37 UTC
## The problem

Appium is not able to locate elements on a AuthO Salesforce page on **iOS 13.3**. It has worked on all previous iOS versions. When appium is not running, you can easily manually click and enter details into the text inputs and use the page. 

This also occurs when using the Element Inspector with Appium Studio, no elements can be located and the screen appears to freeze.

## Environment

* Appium : 1.15.1
* MacOS Catalina 10.15.1:
* Node.js version: 10.17.0
* Yarn 1.19.1
* Apple iPhone 7 iOS **13.3** only:

## Details

Error in logs when trying find the elements on the page using **driver.pageSource()**

`[Xcode] 2019-12-17 08:18:03.043097+1000 WebDriverAgentRunner-Runner[1256:255088] Cannot request the screen point at NSPoint: {187.5, 525.74933333333331}: Error Domain=XCTDaemonErrorDomain Code=11 "No AXElement found at {188 526}: kAXErrorCannotComplete" UserInfo={NSLocalizedDescription=No AXElement found at {188 526}: kAXErrorCannotComplete}`

It appears similar to this issue: https://github.com/facebookarchive/WebDriverAgent/issues/372 and also occurs when an Auth0 pop up page for Salesforce is displayed.

**Comment by mykola-mokhnach** [comment] 2019-12-16 23:06
You could try the solution from https://github.com/appium/appium/issues/13681 as the possible workaround. We cannot do much there on Appium side there since the error is caused by XCTest itself

**Comment by KS261187** [comment] 2019-12-19 23:36
@nimaiwalsh nimaiwalsh, any luck with this issue?. I am also facing the same issue and I did followed the steps mentioned in 13681 but it is of no help.

**Comment by nimaiwalsh** [comment] 2019-12-20 04:28
Hi @KS261187 unfortunately nothing yet. We currently have to hold off all testing on iOS 13.3 until we can also figure out a solution. We also run many of our tests on AWS Device Farm. I will post in this thread if we can come up with a fix.

**Comment by mykola-mokhnach** [comment] 2019-12-23 16:25
Closed as third party issue

**Closed by mykola-mokhnach** 2019-12-23 16:25 UTC
Labels: ThirdParty, XCUITest

**Comment by KS261187** [comment] 2019-12-24 05:07
So if i am not wrong, your app is built using ionic framework correct?. The reason I am asking this is we have similar apps built using phone gap and ionic and both these apps are not working with 13.3. However I tried downloading other phone gap apps from App Store and it is working fine as expected. Really clueless at this point.

**Comment by nimaiwalsh** [comment] 2019-12-28 00:51
Our app is built using Xamarin and is currently a mixture of Forms and Native

**Comment by KS261187** [comment] 2019-12-28 02:43
> Our app is built using Xamarin and is currently a mixture of Forms and Native. Yer I’m completely clueless too considering everything was previously working fine. At this stage it is only an Auth0 pop-up that is causing the issue, unfortunately for tests to start we require the user to be logged in 😂

**Comment by nimaiwalsh** [comment] 2019-12-28 06:04
Yes I can login manually and it works like a charm. However if I log in manually, and inspect the Salesforce Auth0 pop up with Appium Inspector it sort of freezes up too. It’s not until I close Appium Inspector down and restart the app the it works correctly again. Manually login is not viable for our tests so we definitely need to get this fixed moving forward too.

**Comment by KS261187** [comment] 2019-12-30 15:59
So i got a hunch. Looks like the issue is with the textbox in 13.3. I logged in manually and went to a page where there is no textfield and it worked like a charm. Please give it a try where there is no textfield and try to inspect on that page.

**Comment by nimaiwalsh** [comment] 2020-01-02 04:43
Hi @KS261187,

Yer the Salesforce Auth0 page has a text box to input credentials. This is the page we are having issues with. If the user is already logged in, all the other elements are found and the tests work as expected. Any other ideas?

**Comment by KS261187** [comment] 2020-01-02 05:26
I guess this is a bug with Apple . I can already see most of the people reported the same issue both with web and native view under xcuitest forum. Looks like they broke the text fields completely with iOS 13.3. Let’s hope they fix this with Xcode 12. Let me know if you have got any ideas but for now all we can do is to wait for the fix from their end.

**Comment by nimaiwalsh** [comment] 2020-01-02 05:42
Thanks. Let's hope the get another update shortly to fix the issue 😄

**Comment by KS261187** [comment] 2020-01-13 23:10
So suddenly my app started to work with iOS 13.3. All I did was uninstall the Appium beta, reinstall Appium beta and updated the node version to 13.6 and then started using the inspector using custom server and it started to show up fine. The issue is still there with Appium 1.15.1. So don't use that.

**Comment by nimaiwalsh** [comment] 2020-01-14 06:47
Thanks for the tip, 

I just updated Appium to the latest minor release as mentioned (1.16) and reinstalled webdriveragentrunner on the device and now it is all working as expected.

**Comment by KS261187** [comment] 2020-01-14 07:21
Glad it worked👍
