### ISSUE TITLE
WebDriverWait not working in appium 1.14.0 and appium client 7.1.0

### ISSUE THREAD

**Issue by shagupta92042** [appium/appium#13040] opened 2019-08-07 10:10 UTC
## The problem

We are using WebDriverWait in our code which is working fine with appium server 1.12.1 and appium client 6.1.0 but when we switched to appium server 1.14.0 and appium client 7.1.0 , it does not wait for the expected conditions and test case get failed.

## Environment

* Appium version that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): 1.12.1
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe):  5.6.0
* Npm or Yarn package manager:
* Mobile platform/version under test: 8.1.0
* Real device or emulator/simulator: Nexus 6P
* Appium CLI or Appium.app|exe: 1.14.0
Appium client : 7.1.0

## Details

We are using WebDriverWait in our code which is working fine with appium server 1.12.1 and appium client 6.1.0 but when we switched to appium server 1.14.0 and appium client 7.1.0 , it does not wait for the expected conditions and test case get failed but It works fine when we use thread.sleep() so it means that the expected conditions are not working when we upgraded our appium server and client and selenium java jar.

Error : 
org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {message=no such element: Unable to locate element: {"method":"xpath","selector":"//div/following::span[text()='CMX COP']/following-sibling::span[text()='MAY22']"}
  (Session info: chrome=76.0.3809.89)

## Link to error logs

https://gist.github.com/shagupta92042/cdd776e7eede4e03808653b84bdd03e1

## Link to Appium logs

https://gist.github.com/shagupta92042/9c2ef97d3c0178426f626597397946cd

## Link to Dependencies

https://gist.github.com/shagupta92042/e94f75fcb7e1a1f166dad873762c2b4d

## Code To Reproduce Issue [ Good To Have ]

Ppublic ElementConditions(WebDriver driver) {
		this.driver = driver;
		wait = new WebDriverWait(driver,60);

	}

	public void elementToBeClickable(WebElement element) {
		wait.until(ExpectedConditions.elementToBeClickable(element));
	}

	public void visibilityOfElement(WebElement element) {

		wait.until(ExpectedConditions.visibilityOf(element));
	}

**Comment by mykola-mokhnach** [comment] 2019-08-07 11:00
The cause of this issue is the same as for https://github.com/appium/appium/issues/12989

It was fixed in appium@beta

**Closed by mykola-mokhnach** 2019-08-07 11:00 UTC

**Comment by shagupta92042** [comment] 2019-08-07 11:10
Now i have installed 1.14.0-beta2 version but getting below error as it does not support for 76 chrome version.

[debug] [W3C (871ebed5)] Encountered internal error running command: Error: No Chromedriver found that can automate Chrome '76.0.3809'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details. You could also try to enable automated chromedrivers download server feature
[debug] [W3C (871ebed5)]     at Object.wrappedLogger.errorAndThrow (C:\Users\Shashank.Gupta\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\logging.js:78:13)
[debug] [W3C (871ebed5)]     at Chromedriver.errorAndThrow [as start] (C:\Users\Shashank.Gupta\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:508:11)
[debug] [W3C (871ebed5)]     at <anonymous>
