### ISSUE TITLE
Upgrading XCode to 9.1 and iOS Simulator to iOS 11.1 has slowing down Appium-java based tests drastically 

### ISSUE THREAD

**Issue by laxmikantm** [appium/appium#9842] opened 2017-12-22 15:56 UTC
## The problem

Upgrading XCode to 9.1 and iOS Simulator to iOS 11.1 has slowing down Appium-java based tests drastically.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):1.7.1
* Desktop OS/version used to run Appium:Version 1.2.7 
* Node.js version (unless using Appium.app|exe):5.6.0
* Mobile platform/version under test:iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

Upgrading XCode to 9.1 and iOS Simulator to iOS 11.1 has slowing down Appium-java based tests drastically.

My set-up

Appium-ide: 1.2.7
Appium command-line: 1.7.1
IOS: macOS Sierra 10.12.6
XCode: 9.1(9B55)
iOS Simulator: iOS 11.1
Previously it was as below & tests were running with speed

XCode: 8.3
iOS Simulator: iOS 10.3

**Comment by mykola-mokhnach** [comment] 2017-12-22 16:02
Duplicate of https://github.com/facebook/WebDriverAgent/issues/639

**Closed by mykola-mokhnach** 2017-12-22 16:02 UTC
