### ISSUE TITLE
Appium 1.6.3 - Can't stop appium, hangs

### ISSUE THREAD

**Issue by benzhou29** [appium/appium#7659] opened 2017-01-06 19:36 UTC
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

Can't quit appium using control + C.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.6.0
* Desktop OS/version used to run Appium: macOS Sierra 10.12.2
* Node.js version (unless using Appium.app|exe): v7.1.0
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Describe in more detail the problem you have been experiencing, if necessary.

Normally, I run appium from the command line and I just stop it by using control + C. With appium 1.6.3, it just hangs. The only way around it is to close terminal and open a new one.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

These are the last few lines of the logs:

^C[Appium] Received SIGINT - shutting down
[XCUITest] Simulator log exited with code 'null'
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGINT'
^C[Appium] Received SIGINT - shutting down

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment] 2017-01-06 19:39
Duplicate of #7328

**Closed by imurchie** 2017-01-06 19:39 UTC
Labels: NeedsTriage
