### ISSUE TITLE
Tests do not recognize list view children on iOS

### ISSUE THREAD

**Issue by KthProg** [appium/appium#13005] opened 2019-07-31 14:09 UTC
I have a view that has a table, which is dynamically populated with children. When I inspect the UI hierarchy, the children exist and the accessibility IDs are correct, yet Appium times out when waiting for the children to load.

**Comment by umutuzgur** [comment] 2019-07-31 14:12
@KthProg Could you fill the issue template please? We can't investigate issues unless the requested info is filled. It might look quite simple for you but there are a lot of edge cases between iOS versions and Xcode versions. That is the reason why we need the data in the initial template.

**Comment by KthProg** [comment] 2019-07-31 14:14
This is iOS 12.4, iPhone Xs Max simulator. When I print out the page source, it does not show the list/table children, even though debugging with XCode does. I'll fill out some more information soon.

**Comment by KazuCocoa** [comment] 2019-07-31 14:23
Could you check the result of below command, too?

It returns vanilla debugDescription string by XCTest framework.

```ruby
# ruby
@driver.execute_script 'mobile: source', { format: :description }
```
the `mobile` command it:
http://appium.io/docs/en/commands/mobile-command/

**Comment by KthProg** [comment] 2019-07-31 14:25
## The problem

I'm waiting for list (table in iOS I think) children to be displayed in a WebDriverWait. This times out in the test, and printing the page source from Appium does not show the children, despite the fact that the children show up in the XCode debugging tools with the correct accessibility IDs.

## Environment

* Appium version: 1.14.0
* Desktop OS/version: MacOS Mojave (10.14.5) 
* Node.js version: 10.16.0
* Npm or Yarn package manager: NPM 6.9.0
* Mobile platform/version under test: iOS 12.4
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: What?

## Details

The list children are loaded dynamically, after the view has been rendered. I'm not sure if this contributes to the problem or not.

## Link to Appium logs

There's nothing in the logs that clarifies the issue. It's a simple timeout not being able to find the elements.

## Code To Reproduce Issue [ Good To Have ]

I will try to make a reproducible example, but I don't have the time right now.

**Comment by KthProg** [comment] 2019-07-31 14:25
@KazuCocoa What would that look like in C#?

**Comment by KazuCocoa** [comment] 2019-07-31 14:28
maybe below (The format is from the mobile command link)
```
driver.ExecuteScript("mobile: source", new Dictionary<string, string> { { "format", "description" } });
```

**Comment by KthProg** [comment] 2019-07-31 14:38
Here is the full output:

`Attributes: Window (Main), {{0.0, 0.0}, {414.0, 896.0}}
Element subtree:
 →Window (Main), 0x600001518700, {{0.0, 0.0}, {414.0, 896.0}}
    Other, 0x600001519420, {{0.0, 0.0}, {414.0, 896.0}}
      Other, 0x600001518d20, {{0.0, 0.0}, {414.0, 896.0}}
        Other, 0x600001518b60, {{0.0, 0.0}, {414.0, 896.0}}
          Other, 0x600001518460, {{0.0, 0.0}, {414.0, 896.0}}
            Other, 0x6000015189a0, {{0.0, 0.0}, {414.0, 896.0}}
              Other, 0x600001519b20, {{0.0, 0.0}, {414.0, 896.0}}, identifier: 'RvDetailSelectionPageGrid'
                Table, 0x6000015188c0, {{0.0, 250.0}, {414.0, 570.0}}, label: 'Empty list'
                Button, 0x600001518540, {{16.0, 832.0}, {382.0, 52.0}}, identifier: 'Continue', label: 'Continue >>', Disabled
                Other, 0x600001518a80, {{0.0, 0.0}, {414.0, 250.0}}
                Image, 0x60000151a140, {{298.0, 40.0}, {100.0, 30.0}}
                ActivityIndicator, 0x600001518fc0, {{372.7, 103.0}, {20.0, 20.0}}, label: 'Progress halted', value: 0
                  Image, 0x600001519ce0, {{372.7, 103.0}, {20.0, 20.0}}
                StaticText, 0x600001519ea0, {{0.0, 0.0}, {0.0, 0.0}}
                StaticText, 0x600001519f80, {{16.0, 139.8}, {382.0, 26.3}}, label: 'SELECT YEAR'
                StaticText, 0x600001519a40, {{140.7, 182.2}, {257.0, 18.7}}, label: 'Scroll to select the year your RV was made.'
                Image, 0x600001519dc0, {{16.0, 40.0}, {16.0, 30.0}}
                StaticText, 0x60000151bf00, {{36.0, 45.0}, {36.7, 19.0}}, label: 'Back'
Path to element:
 →Application, pid: 76554, label: 'OneControl'
  ↳Window (Main), {{0.0, 0.0}, {414.0, 896.0}}
Query chain:
 →Find: Application 'com.lippertcomponents.onecontrol'
  Output: {
    Application, pid: 76554, label: 'OneControl'
  }
  ↪︎Find: Children matching type Any
    Output: {
      Window (Main), {{0.0, 0.0}, {414.0, 896.0}}
      Window, {{0.0, 0.0}, {414.0, 896.0}}
      Window, {{0.0, 0.0}, {414.0, 896.0}}
    }
    ↪︎Find: Identity Binding
      Output: {
        Window (Main), {{0.0, 0.0}, {414.0, 896.0}}
      }


Attributes: Window, {{0.0, 0.0}, {414.0, 896.0}}
Element subtree:
 →Window, 0x600001518ee0, {{0.0, 0.0}, {414.0, 896.0}}
    Other, 0x6000015195e0, {{0.0, 0.0}, {414.0, 896.0}}
      Other, 0x600001519c00, {{0.0, 896.0}, {414.0, 243.0}}
Path to element:
 →Application, pid: 76554, label: 'OneControl'
  ↳Window, {{0.0, 0.0}, {414.0, 896.0}}
Query chain:
 →Find: Application 'com.lippertcomponents.onecontrol'
  Output: {
    Application, pid: 76554, label: 'OneControl'
  }
  ↪︎Find: Children matching type Any
    Output: {
      Window (Main), {{0.0, 0.0}, {414.0, 896.0}}
      Window, {{0.0, 0.0}, {414.0, 896.0}}
      Window, {{0.0, 0.0}, {414.0, 896.0}}
    }
    ↪︎Find: Identity Binding
      Output: {
        Window, {{0.0, 0.0}, {414.0, 896.0}}
      }


Attributes: Window, {{0.0, 0.0}, {414.0, 896.0}}
Element subtree:
 →Window, 0x600001518380, {{0.0, 0.0}, {414.0, 896.0}}
    StatusBar, 0x6000015196c0, {{0.0, 0.0}, {414.0, 44.0}}
      Other, 0x600001519880, {{0.0, 0.0}, {414.0, 44.0}}
        Other, 0x600001519960, {{0.0, 0.0}, {414.0, 44.0}}
          Other, 0x600001518620, {{8.0, -6.0}, {197.0, 11.3}}
          Other, 0x600001519180, {{210.0, -6.0}, {197.0, 11.3}}
          Other, 0x6000015190a0, {{8.0, 17.0}, {197.0, 11.3}}
          Other, 0x600001518e00, {{21.0, 14.7}, {72.3, 13.7}}
            StaticText, 0x600001518c40, {{35.7, 13.0}, {43.0, 19.3}}, label: '10:35 AM'
          Other, 0x6000015197a0, {{29.0, 8.0}, {61.0, 22.0}}
          Other, 0x6000015182a0, {{210.0, 17.0}, {197.0, 11.3}}
          Other, 0x6000015180e0, {{319.3, 14.7}, {73.0, 13.7}}
            Other, 0x600001519260, {{319.3, 16.7}, {18.3, 11.7}}, label: 'Cellular', value: No signal
            Other, 0x600001519500, {{343.7, 16.7}, {16.3, 11.7}}, identifier: '3 of 3 Wi-Fi bars', value: SSID, 3 of 3 Wi-Fi...
            Other, 0x6000015c1ea0, {{366.0, 16.3}, {26.3, 12.3}}, label: '100% battery power', value: Not charging
          Other, 0x6000015c0c40, {{319.3, 14.7}, {73.0, 13.7}}
        Other, 0x6000015c3020, {{8.7, 24.7}, {81.3, 13.3}}
Path to element:
 →Application, pid: 76554, label: 'OneControl'
  ↳Window, {{0.0, 0.0}, {414.0, 896.0}}
Query chain:
 →Find: Application 'com.lippertcomponents.onecontrol'
  Output: {
    Application, pid: 76554, label: 'OneControl'
  }
  ↪︎Find: Children matching type Any
    Output: {
      Window (Main), {{0.0, 0.0}, {414.0, 896.0}}
      Window, {{0.0, 0.0}, {414.0, 896.0}}
      Window, {{0.0, 0.0}, {414.0, 896.0}}
    }
    ↪︎Find: Identity Binding
      Output: {
        Window, {{0.0, 0.0}, {414.0, 896.0}}
      }`

**Comment by KthProg** [comment] 2019-07-31 14:39
Notice it does not show any children in the table, however the XCode debugger does and visually, there are clearly children in the app.

**Comment by KthProg** [comment] 2019-07-31 14:40
I wonder if Appium is skipping over its children because it is labeled "Empty list"?

**Comment by KazuCocoa** [comment] 2019-07-31 14:53
it means you cannot them via XCTest framework, unfortunately.

I have no exact answer since WDA tried to resolve views using various process. The result of debugDescription could depend on XCtest framework version (Xcode version), too.


I think you can find the table like `find_element_by_name("Empty list")` tho.

**Comment by KthProg** [comment] 2019-07-31 14:55
I wonder if it's related to this?
https://stackoverflow.com/questions/41845309/xctest-ui-tests-can-not-find-collectionview-within-a-table-cell

**Comment by KazuCocoa** [comment] 2019-07-31 14:58
ah, it's interesting.
It's wort to try if explicit `isAccessibilityElement = false` makes children visible for accessibility services.

**Comment by KthProg** [comment] 2019-07-31 15:09
I just looked in the XCode debugger and I can verify it is _not_ an accessibility element, so that isn't the issue sadly.

**Comment by KthProg** [comment] 2019-07-31 15:23
![Screen Shot 2019-07-31 at 11 22 42 AM](https://user-images.githubusercontent.com/3527476/62225025-a31b2c00-b385-11e9-97ac-655b97b0ee9b.png)

Here is the Xcode debugger layout.

**Comment by KthProg** [comment] 2019-07-31 15:50
This is happening on many other screens as well. It appears that Appium is only recognizing elements that can be interacted with?I'm really not sure, but many many elements are not being displayed in the page source. Sometimes their children are displayed, sometimes not. I'm not sure what rules are being used to determine what elements are available to Appium, and it's hard to say if it's an XCTest issue or Appium.

**Comment by mykola-mokhnach** [comment] 2019-07-31 17:54
https://github.com/appium/appium/issues/6517 might be a duplicate of this issue

**Comment by KthProg** [comment] 2019-07-31 20:33
I don't think so. That's the same solution as I showed above, but my UI is laid out correctly. The container is _not_ accessible, and the child elements _are_, yet the page source does not show the children, and Appium cannot access them, despite the accessibility tools and XCode debugger both showing that they are there.

**Comment by KazuCocoa** [comment] 2019-08-01 00:08
I did not Xcode internals well, but Appium depends on XCTest framework rather than Xcode debugger. Appium calls https://developer.apple.com/documentation/xctest/xcuielementquery/1500679-matchingidentifier?language=objc for find by accessibility id for example.

btw, I wondered also how Accessibility Inspector worked. Below is the official Twitter app's search icon on real device. It did not show coordinate etc via inspector tools while it can detect via Appium (XCTest framework). So, they were not same tech. (The perform also did not work)
<img src="https://user-images.githubusercontent.com/5511591/62255933-5d6c6b00-b43a-11e9-9c7b-84c7a681f7c2.png" width=300>

```
<XCUIElementTypeOther type="XCUIElementTypeOther" name="Moments_tab" label="Search and Explore tab" enabled="true" visible="true" x="80" y="519" width="80" height="49"/>

```

**Comment by KthProg** [comment] 2019-08-01 13:03
I guess the question is, how doe XCTest build a UI structure then, and why would it be unable to find these elements? (In fact it appears to think they don't exist). And is there any way to narrow down whether the cause is XCTest or Appium? My only point was to show that the element are on the page and are laid out correctly. So either XCTest or Appium have a bug, hopefully a known one.

**Comment by KazuCocoa** [comment] 2019-08-01 13:12
That is black box for Appium.
Appium gets data via https://github.com/appium/WebDriverAgent/blob/master/PrivateHeaders/XCTest/XCTestManager_ManagerInterface-Protocol.h#L29 in XCTest framework.

The only way is raising issues to Apple.

**Comment by KthProg** [comment] 2019-08-01 13:16
snapshotForElement is how it gets the full page source? Or does it make a series of calls? Maybe I can create a reproducible example for Apple to take a look at.

**Comment by KazuCocoa** [comment] 2019-08-01 15:16
For `driver.ExecuteScript("mobile: source", new Dictionary<string, string> { { "format", "description" } });`
Entry point: https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIApplication+FBHelpers.m#L147-L157
Root data comes from https://developer.apple.com/documentation/xctest/xcuielementquery/1500816-allelementsboundbyaccessibilitye?language=objc

Maybe, ^ is easier to explain.

---

XML format also gets elements via allelementsboundbyaccessibilitye . And resolved their attributes via _XCT_snapshotForElement.

**Comment by mykola-mokhnach** [comment] 2019-08-03 07:36
Closed as third party issue

**Closed by mykola-mokhnach** 2019-08-03 07:36 UTC
Labels: ThirdParty, XCUITest
