### ISSUE TITLE
cannot deploy app to device / emulator since upgrading to AS 3

### ISSUE THREAD

**Issue by igalep** [appium/appium#9822] opened 2017-12-19 13:54 UTC
## The problem

We've update to AS 3 , and since then the `adb install` command stoped working
Here [https://commonsware.com/blog/2017/10/31/android-studio-3p0-flag-test-only.html](url) you can find a great explanation for the problem (Thanks to CommonsWare)

The solution is to run `adb install -t` instead ... 
Therefore this part should be fixed in appium's side as well

## Environment

* Appium version : 1.7.1

## Link to Appium logs

`Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm install -r /data/local/tmp/027188cea6fb44201196dca04b3a5184.apk' exited with code 1'; Stderr: 'Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]'; Code: '1'`

**Comment by mykola-mokhnach** [comment] 2017-12-19 14:43
how about removing `android:testOnly="true"` parameter from the manifest?

**Comment by igalep** [comment] 2017-12-20 13:06
@mykola-mokhnach I cannot change the "manifest"

**Comment by mykola-mokhnach** [comment] 2017-12-20 14:10
Ok, I'll consider it as feature request

**Comment by tspanindra** [comment] 2018-04-16 18:53
Is there any update on this?

**Comment by mykola-mokhnach** [comment] 2018-06-04 09:20
Duplicate of https://github.com/appium/appium/issues/10758

**Closed by mykola-mokhnach** 2018-06-04 09:20 UTC
Labels: Android, Enhancement
