### ISSUE TITLE
Getting the Page Source timeouts on iOS 14.4

### ISSUE THREAD

**Issue by bart-tricentis** [appium/appium#15155] opened 2021-03-03 12:47 UTC
## The problem

On an iPhone 8 simulator running iOS 14.4 on a page with a very long scroll view (30+ rows) the appium sessions timeouts.
The app is made using Swift

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS 11.2
* Node.js version (unless using Appium.app|exe): v14.13.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 14.4
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

[pagesource.txt](https://github.com/appium/appium/files/6076038/pagesource.txt)

**Comment by mykola-mokhnach** [comment] 2021-03-03 13:57
Duplicate of https://github.com/appium/appium/issues/13595

You could also try to limit the value of `snapshotMaxDepth` setting, which reduces the tree size. In general this is the XCTest issue and only Apple could change that behaviour

**Closed by mykola-mokhnach** 2021-03-03 13:57 UTC
