### ISSUE TITLE
Android 10: _appiumSupport.util.pluralize is not a function (Permissions not granted)

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#14129] opened 2020-03-31 07:00 UTC
## The problem

Unable to grant permission on Android 10 Device.
I have added autoGrantPermissions to true in desired capabilities.

`Unable to grant permission requested. Original error: _appiumSupport.util.pluralize is not a function`

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.17.0
* Desktop OS/version used to run Appium: MacOS 10.14.6
* Node.js version (unless using Appium.app|exe): v12.13.0
* Npm or Yarn package manager: 6.12.0
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Pixel 2

## Link to Appium logs

https://gist.github.com/mayureshshirodkar/75e40d4387749b40c0e89469da8da607

**Comment by mykola-mokhnach** [comment] 2020-03-31 08:34
Could you please provide the output of `npm ls` for `android-adb` package?

**Comment by mayureshshirodkar** [comment] 2020-03-31 08:47
@mykola-mokhnach Here is the output android-adb package:

```
$ pwd
/usr/local/lib/node_modules/appium/node_modules/appium-adb

$ npm ls
appium-adb@7.27.1 /usr/local/lib/node_modules/appium/node_modules/appium-adb
├── UNMET DEPENDENCY @babel/runtime@^7.0.0
├── UNMET DEPENDENCY adbkit-apkreader@^3.1.2
├── UNMET DEPENDENCY appium-support@^2.37.0
├── UNMET DEPENDENCY async-lock@^1.0.0
├── UNMET DEPENDENCY asyncbox@^2.3.1
├── UNMET DEPENDENCY bluebird@^3.4.7
├── UNMET DEPENDENCY lodash@^4.0.0
├── UNMET DEPENDENCY lru-cache@^5.0.0
├── UNMET DEPENDENCY semver@^7.0.0
├── UNMET DEPENDENCY shell-quote@^1.6.1
├── UNMET DEPENDENCY source-map-support@^0.5.5
├── UNMET DEPENDENCY teen_process@^1.11.0
└── UNMET DEPENDENCY utf7@^1.0.2

npm ERR! missing: @babel/runtime@^7.0.0, required by appium-adb@7.27.1
npm ERR! missing: adbkit-apkreader@^3.1.2, required by appium-adb@7.27.1
npm ERR! missing: appium-support@^2.37.0, required by appium-adb@7.27.1
npm ERR! missing: async-lock@^1.0.0, required by appium-adb@7.27.1
npm ERR! missing: asyncbox@^2.3.1, required by appium-adb@7.27.1
npm ERR! missing: bluebird@^3.4.7, required by appium-adb@7.27.1
npm ERR! missing: lodash@^4.0.0, required by appium-adb@7.27.1
npm ERR! missing: lru-cache@^5.0.0, required by appium-adb@7.27.1
npm ERR! missing: semver@^7.0.0, required by appium-adb@7.27.1
npm ERR! missing: shell-quote@^1.6.1, required by appium-adb@7.27.1
npm ERR! missing: source-map-support@^0.5.5, required by appium-adb@7.27.1
npm ERR! missing: teen_process@^1.11.0, required by appium-adb@7.27.1
npm ERR! missing: utf7@^1.0.2, required by appium-adb@7.27.1
```

**Comment by mykola-mokhnach** [comment] 2020-03-31 08:53
Isn't the issue obvious? The package deployment is broken. Please try to reinstall it. The proper result should contain no errors

**Comment by mayureshshirodkar** [comment] 2020-03-31 09:06
@mykola-mokhnach Even after re-installing Appium 1.17.0 i see this dependency issues.
Is there a problem with the way Appium is installed?

```
rm -rf /usr/local/lib/node_modules/appium
npm cache verify
npm install -g appium --verbose 
```

**Comment by mykola-mokhnach** [comment] 2020-03-31 09:09
It might be that your company is using its own npm repository mirror, which is out of date. I don't know the cause: I've just tried to reinstall 1.17 on my computer and everything worked.

**Comment by mayureshshirodkar** [comment] 2020-03-31 10:58
@mykola-mokhnach 
Anyone facing this issue i fixed it by this steps.
After performing npm install and then running npm ls under android-adb package, gives no errors.

```
rm -rf /usr/local/lib/node_modules/appium
npm cache verify
npm install -g appium --verbose 
cd usr/local/lib/node_modules/appium/node_modules/appium-adb/
npm install
```

**Comment by mykola-mokhnach** [comment] 2020-03-31 11:13
> rm -rf /usr/local/lib/node_modules/appium

The correct way to uninstall npm modules is `npm uninstall -g <module_name>`

**Comment by mykola-mokhnach** [comment] 2020-03-31 11:13
closed as not an issue

**Closed by mykola-mokhnach** 2020-03-31 11:13 UTC
Labels: NeedsInfo, NotABug
