### ISSUE TITLE
"Error: socket hang up" in iOS tests

### ISSUE THREAD

**Issue by insidiaGithub** [appium/appium#13017] opened 2019-08-01 13:29 UTC
## The problem

Hi all! I try to update appium from 1.9.1 to 1.14.0. We have 35 tests. After update, my tests sometimes failed (6-10 random tests from 35). Everytime I get error:
1) From Visual Studio
`An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: socket hang up`
2) I found it in appium logs
`[XCUITest] xcodebuild exited with code 'null' and signal 'SIGKILL'
[WD Proxy] Got an unexpected response: {"code":"ECONNRESET"}
[W3C (98e37bd1)] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: socket hang up`
3) And this one from simulator logs everytime
`Aug  1 12:19:13 macmini-3 com.apple.CoreSimulator.SimDevice.999E28FA-88CE-4E3D-9D05-499EFDE3A5DD[30232] (UIKitApplication:com.apple.test.WebDriverAgentRunner-Runner[0x48b5][30254][30748]): Service exited with abnormal code: 74`

It's may happens in random place in test. When the test starts it deletes old simulator and creates new one on mac-mini with last macOS Mojave. At the same time, I have two running tests. Each appium I run with other ports:
1) appium -p 4723 --webdriveragent-port 8100
2) appium -p 4730 --webdriveragent-port 8105

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): 1.9.1
* Desktop OS/version used to run Appium: macOS Mojave 10.14.6
* Node.js version (unless using Appium.app|exe): 10.16.0
* Npm or Yarn package manager: npm 6.10.1
* Mobile platform/version under test: iOS 12.4
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI
* Xcode: 10.3
* Xcode-select version 2354

## Details

My Capabilities:
```
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.PlatformVersion, "12.4");
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.App, _deviceSettings.BuildUrl);
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.NewCommandTimeout, 900);
            appiumOptions.AddAdditionalCapability("wdaLaunchTimeout", 360000);
            appiumOptions.AddAdditionalCapability("wdaConnectionTimeout", 360000);
            appiumOptions.AddAdditionalCapability("reduceMotion", true);
            appiumOptions.AddAdditionalCapability("skipLogCapture", true);
            appiumOptions.AddAdditionalCapability("iosInstallPause", 8000);`
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.DeviceName, _deviceSettings.Hostname);
            appiumOptions.AddAdditionalCapability("wdaLocalPort", _deviceSettings.Port);
```

I've tried to remove/change
```
            appiumOptions.AddAdditionalCapability("wdaLaunchTimeout", 360000);
            appiumOptions.AddAdditionalCapability("wdaConnectionTimeout", 360000);
            appiumOptions.AddAdditionalCapability("iosInstallPause", 8000);
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.NewCommandTimeout, 900);
```

but it is not helps me.

## Link to Appium logs

Appium logs: https://gist.github.com/insidiaGithub/c652b3b96be4403d7a4f3489a5276055
Simulator logs: https://gist.github.com/insidiaGithub/e29c52e28e0d56986c583bdd53d353e9

## Code To Reproduce Issue [ Good To Have ]
Random failed on random places

**Comment by mykola-mokhnach** [comment] 2019-08-01 13:59
Make sure the usbmuxd library is up to date or try appium@beta, where this lib is not used anymore.

**Comment by insidiaGithub** [comment] 2019-08-01 14:02
> Make sure the usbmuxd library is up to date or try appium@beta, where this lib is not used anymore.

I've tried to use appium@beta (beta 2) and I've installed usbmuxd with brew install --HEAD usbmuxd. It didn't help me

**Comment by mykola-mokhnach** [comment] 2019-08-01 14:05
Try to get iOS system logs when socket hang event happens, maybe they contain some useful info

**Comment by insidiaGithub** [comment] 2019-08-01 14:07
> Try to get iOS system logs when socket hang up event happens, maybe they contain some useful info

System log from emulator is not it?

**Comment by mykola-mokhnach** [comment] 2019-08-01 14:08
no, it is different

**Comment by insidiaGithub** [comment] 2019-08-01 14:09
> no, it is different

Ok. I'll try it. Thanks

**Comment by insidiaGithub** [comment] 2019-08-05 10:11
> Try to get iOS system logs when socket hang up event happens, maybe they contain some useful info

Hi! Did you mean logs which creates in ~/Library/Logs/DiagnosticReports?

I find `(UIKitApplication:com.apple.test.WebDriverAgentRunner-Runner[0x48b5][30254][30748]): Service exited with abnormal code: 74` in emulator logs, but in "~/Library/Logs/DiagnosticReports" I coudn't find WebDriverAgent crash log.

**Comment by insidiaGithub** [comment] 2019-08-05 10:22
I will try to catch error in Console.app also

**Comment by mykola-mokhnach** [comment] 2019-08-05 11:55
No I mean the one which is collected if `showIOSLog` cap is set to true

**Comment by insidiaGithub** [comment] 2019-08-06 11:47
> No I mean the one which is collected if `showIOSLog` cap is set to true

This is my log (I removed a lot of logs in the middle because it very big):
https://gist.github.com/insidiaGithub/d3a38d4e7c7c73a46c36f79389302e80

I've found some information about WebDriver in the end of log:
`[iOSLog] [IOS_SYSLOG_ROW] 2019-08-06 11:01:06.017 E  WebDriverAgentRunner-Runner[28385:2dd675] (XCTest) Exiting due to IDE disconnection.
[iOSLog] [IOS_SYSLOG_ROW] 2019-08-06 11:01:06.018 E  assertiond[27970:2ddb4c] [com.apple.assertiond:process_info] [WebDriverAgentR:28385] SyscallError: setpriority(PRIO_DARWIN_ROLE, 28385, 3): No such process
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGKILL'
[iOSLog] [IOS_SYSLOG_ROW] 2019-08-06 11:01:06.194 Df testmanagerd[28376:2ddae2] [com.apple.dt.testmanagerd:Default] offset 1.317
[iOSLog] [IOS_SYSLOG_ROW] 2019-08-06 11:01:06.194 Df testmanagerd[28376:2ddae2] [com.apple.dt.testmanagerd:Default] before/after Touch down at 187.0, 633.7, offset=0.00s Move to 187.0, 266.8, offset=1.60s
[iOSLog] [IOS_SYSLOG_ROW] 2019-08-06 11:01:06.195 A  Acumatica[28386:2d6c62] (UIKitCore) send gesture actions
[iOSLog] [IOS_SYSLOG_ROW] 2019-08-06 11:01:06.194 Df testmanagerd[28376:2ddae2] [com.apple.dt.testmanagerd:Default] touch move {187, 331.73666381835938}
[iOSLog] [IOS_SYSLOG_ROW] 2019-08-06 11:01:06.194 Df testmanagerd[28376:2ddae2] [com.apple.dt.testmanagerd:Default] normalized {187, 331.73666381835938} to {0.49866666666666665, 0.4973563175687547}
[WD Proxy] Got an unexpected response: {"code":"ECONNRESET"}
[iOSLog] [IOS_SYSLOG_ROW] 2019-08-06 11:01:06.217 Df assertiond[27970:2ddb4d] [com.apple.assertiond:process_info] [WebDriverAgentR:28385] Port death watcher fired.`

**Comment by mykola-mokhnach** [comment] 2019-08-07 08:49
> [XCUITest] xcodebuild exited with code 'null' and signal 'SIGKILL'

When xcodebuild process is killed then WDA process is terminated as well, this is expected. Although, it is not clear why it is killed.

**Comment by insidiaGithub** [comment] 2019-08-07 10:48
> When xcodebuild process is killed then WDA process is terminated as well, this is expected. Although, it is not clear why it is killed.

I understand. Thanks. May be it will be fixed with new xcode and ios13

**Comment by deedora** [comment] 2019-08-19 21:49
Appium 1.14.1
MacOS Mojave 10.14.5
Xcode 10.2.1
Real device iPhone 8 12.3

I have the same issue with Appium v1.14.1 and 1.13.0.
Everything was working last Friday on 1.13.0 and now on Monday, I started having issues so I've updated to v1.14.1 and after a few runs I get the same error "Original error: Could not proxy command to remote server. Original error: Error: socket hang up"
I've also reinstalled carthage, libimobiledevice, ios-deploy and usbmuxd. Nothing helps. Few times it started working after restarting the mac but error reappears after a few runs.
Appium logs with showIOSLog set to true
https://gist.github.com/deedora/281d56e57c8c9d40adb22da9bb559948

**Comment by mykola-mokhnach** [comment] 2019-08-20 05:15
Closed as third party issue. 
Unfortunately, the disconnect happens on iproxy side and we cannot control that part much. Appium@beta has already dripped the usage of this tool in favour of direct communication with lockdown daemon. This might be more stable in the future perspective.

**Closed by mykola-mokhnach** 2019-08-20 05:15 UTC
Labels: ThirdParty, XCUITest

**Comment by deedora** [comment] 2019-08-20 12:30
Thanks. Appium@beta seems to be working.

**Comment by insidiaGithub** [comment] 2019-08-20 13:16
> Thanks. Appium@beta seems to be working.

But not for me, unfortunately =(

**Comment by deedora** [comment] 2019-08-20 13:25
> > Thanks. Appium@beta seems to be working.
> 
> But not for me, unfortunately =(

You are still getting Error: socket hang up on beta? Beta randomly crashes for me, but tests are working.

**Comment by insidiaGithub** [comment] 2019-08-20 13:29
I've written in this issue that:
After update, my tests sometimes failed (6-10 random tests from 35).

In appium@beta I have the same situation

**Comment by deedora** [comment] 2019-08-20 13:32
I was getting mine error at the setup, not in the middle of testing, and it's working ok now with beta :/

**Comment by AymarN** [comment] 2019-10-08 14:18
> Thanks. Appium@beta seems to be working.

@deedora Can you please detail each steps of your installation starting from Carthage to usbmuxd cause it doesn't work on my side. I will really appreciate it.

**Comment by deedora** [comment] 2019-10-10 10:31
@AymarN I was just following instructions from Appiums web page.

**Comment by AymarN** [comment] 2019-10-18 17:03
@deedora thank you for your reply.
On the appium webpage https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md there is nothing about usbmuxd
Did you set up usbmuxd at the last step ?

**Comment by youran1024** [comment] 2019-10-19 15:12
when i restart the computer ，the problem is resolved。

good luck

**Comment by youran1024** [comment] 2019-10-19 15:12
> > When xcodebuild process is killed then WDA process is terminated as well, this is expected. Although, it is not clear why it is killed.
> 
> I understand. Thanks. May be it will be fixed with new xcode and ios13

when i restart the computer ，the problem is resolved。
good luck
