### ISSUE TITLE
bug: Cannot install uiauatomator2 behind corporate proxy

### ISSUE THREAD

**Issue by luceat-lux-vestra** [appium/appium#19742] opened 2024-01-31 08:24 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

C:\Users\user.id>appium driver install uiautomator2
✔ Checking if 'appium-uiautomator2-driver' is compatible
✖ Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --no-progress --no-audit --omit=peer --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code 1.

STDOUT:
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "C:\\WINDOWS\\system32\\cmd.exe /d /s /c node install-npm.js\n[17:16:01] Error installing Chromedriver: Request failed with status code 400\n[17:16:01] AxiosError: Request failed with status code 400\n    at settle (C:\\Users\\user.id\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\user.id\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\adapters\\http.js:589:11)\n    at IncomingMessage.emit (node:events:530:35)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (C:\\Users\\user.id\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at retrieveData (C:\\Users\\user.id\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-chromedriver\\lib\\utils.js:92:5)\n[17:16:01] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable."
  }
}

STDERR:
npm WARN config global-style This option has been deprecated in favor of `--install-strategy=shallow`
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\user.id\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\@appium\\support\\node_modules\\axios',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\user.id\.appium\node_modules\appium-uiautomator2-driver\node_modules\@appium\support\node_modules\axios\lib'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\user.id\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\@appium\\support\\node_modules\\axios\\lib'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\user.id\\.appium\\node_modules\\appium-uiautomator2-driver',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\user.id\.appium\node_modules\appium-uiautomator2-driver\node_modules\resolve\test'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\user.id\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\resolve\\test'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\user.id\\.appium\\node_modules\\appium-uiautomator2-driver',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\user.id\.appium\node_modules\appium-uiautomator2-driver\node_modules\resolve'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\user.id\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\resolve'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\user.id\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install-npm.js
npm ERR! [17:16:01] Error installing Chromedriver: Request failed with status code 400
npm ERR! [17:16:01] AxiosError: Request failed with status code 400
npm ERR!     at settle (C:\Users\user.id\.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\settle.js:19:12)
npm ERR!     at IncomingMessage.handleStreamEnd (C:\Users\user.id\.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\adapters\http.js:589:11)
npm ERR!     at IncomingMessage.emit (node:events:530:35)
npm ERR!     at endReadableNT (node:internal/streams/readable:1696:12)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR!     at Axios.request (C:\Users\user.id\.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\Axios.js:45:41)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at retrieveData (C:\Users\user.id\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver\lib\utils.js:92:5)
npm ERR! [17:16:01] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.

npm ERR! A complete log of this run can be found in: C:\Users\user.id\scoop\persist\nodejs-lts\cache\_logs\2024-01-31T08_15_29_234Z-debug-0.log

### Expected Behavior

I can install chromedriver while installing uiautomator2

### Minimal Reproducible Example

> appium driver install uiautomator2

### Environment

- Operating system: Windows 11 23H2
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): v20.11.0
- `npm` version (output of `npm --version`): 10.2.4
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

same as #16155 but tested I can download drivers from [official site](https://googlechromelabs.github.io/chrome-for-testing/#stable)

But `appium driver install uiautomator2` doesn't work.

Thanks.

**Comment by KazuCocoa** [comment] 2024-01-31 09:03
it looks like axios whcih downloads chromedriver got 400 error. Not sure if the body came from your company proxy though.

```
npm ERR! [17:16:01] Error installing Chromedriver: Request failed with status code 400
npm ERR! [17:16:01] AxiosError: Request failed with status code 400
npm ERR! at settle (C:\Users\user.id.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\settle.js:19:12)
npm ERR! at IncomingMessage.handleStreamEnd (C:\Users\user.id.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\adapters\http.js:589:11)
npm ERR! at IncomingMessage.emit (node:events:530:35)
npm ERR! at endReadableNT (node:internal/streams/readable:1696:12)
npm ERR! at processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! at Axios.request (C:\Users\user.id.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\Axios.js:45:41)
```

`APPIUM_SKIP_CHROMEDRIVER_INSTALL=1`  environment argument, or environment variables may help:

>   // You can also define your proxy using the conventional `http_proxy` and
>   // `https_proxy` environment variables. If you are using environment variables
https://github.com/axios/axios


> I can download drivers from [official site](https://googlechromelabs.github.io/chrome-for-testing/#stable)

Did you mean another nodejs process with axios had no issue to download it?

**Comment by mykola-mokhnach** [comment] 2024-01-31 09:14
Duplicate of https://github.com/appium/appium/issues/19711

**Closed by mykola-mokhnach** 2024-01-31 09:14 UTC
Labels: Needs Info

**Comment by mykola-mokhnach** [comment] 2024-01-31 09:27
I am not quite convinced that setting a global axios proxy is a good idea as it might corrupt other communication (e.g. driver-to-server). the best idea in such case would be to skip automated CD download and manage it on a custom basis
