### ISSUE TITLE
iOS: Hide keyboard does not work correctly on different machines

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#5054] opened 2015-05-05 12:31 UTC
appium 1.3.6 (fresh installed on both machines)
MacOS all updated
xcode 6.3.1 (both fresh installed)
iOS simulators (any 8.3, 8.1 ...)

Command:
((IOSDriver) driver).hideKeyboard(HideKeyboardStrategy.PRESS_KEY, "Hide keyboard")

With some machines it is 100% working always with others 100% fails always.
Same test and client. Same way of start from command line.

even with Fail keyboard is hiding successfully but tests fail due to error on server.

Can someone suggest where to dig?

Logs:

SUCCESS:

[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/d8dd4204-a126-4d5d-a069-67b102733595/appium/device/hide_keyboard[39m [90m{"strategy":"pressKey","key":"Hide keyboard"}[39m
[36minfo[39m: [debug] Pushing command to appium work queue: "au.hideKeyboard('pressKey','Hide keyboard')"
[36minfo[39m: [debug] Sending command to instruments: au.hideKeyboard('pressKey','Hide keyboard')
[36minfo[39m: [debug] [32m[INST] 2015-05-05 12:18:51 +0000 Debug: Got new command 76 from instruments: au.hideKeyboard('pressKey','Hide keyboard')[39m
[36minfo[39m: [debug] [32m[INST] 2015-05-05 12:18:51 +0000 Debug: evaluating au.hideKeyboard('pressKey','Hide keyboard')[39m
[36minfo[39m: [debug] [32m[INST] 2015-05-05 12:18:51 +0000 Debug: Hiding keyboard with keyName Hide keyboard[39m
[36minfo[39m: [debug] [32m[INST] 2015-05-05 12:18:51 +0000 Debug: target.frontMostApp().keyboard().buttons()["Hide keyboard"].tap()[39m
[36minfo[39m: [debug] [32m[INST] 2015-05-05 12:18:52 +0000 Debug: evaluation finished[39m
[36minfo[39m: [debug] [32m[INST] 2015-05-05 12:18:52 +0000 Debug: responding with:[39m
[36minfo[39m: [debug] [32m[INST] 2015-05-05 12:18:52 +0000 Debug: Running system command #77: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...[39m
[36minfo[39m: [debug] Socket data received (25 bytes)
[36minfo[39m: [debug] Socket data being routed.
[36minfo[39m: [debug] Got result from instruments: {"status":0,"value":""}
[36minfo[39m: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"d8dd4204-a126-4d5d-a069-67b102733595"}
[36minfo[39m: [37m<-- POST /wd/hub/session/d8dd4204-a126-4d5d-a069-67b102733595/appium/device/hide_keyboard [39m[32m200[39m[90m 918.078 ms - 74[39m [90m{"status":0,"value":"","sessionId":"d8dd4204-a126-4d5d-a069-67b102733595"}[39m

FAILED:

info: --> POST /wd/hub/session/443adfcd-cfb0-49f3-98b5-af7b63e12e8e/appium/device/hide_keyboard {"strategy":"pressKey","key":"Hide keyboard"}
info: [debug] Pushing command to appium work queue: "au.hideKeyboard('pressKey','Hide keyboard')"
info: [debug] Sending command to instruments: au.hideKeyboard('pressKey','Hide keyboard')
info: [debug] [INST] 2015-05-05 11:08:08 +0000 Debug: Got new command 76 from instruments: au.hideKeyboard('pressKey','Hide keyboard')
info: [debug] [INST] 2015-05-05 11:08:08 +0000 Debug: evaluating au.hideKeyboard('pressKey','Hide keyboard')
info: [debug] [INST] 2015-05-05 11:08:08 +0000 Debug: Hiding keyboard with keyName Hide keyboard
info: [debug] [INST] 2015-05-05 11:08:08 +0000 Debug: target.frontMostApp().keyboard().buttons()["Hide keyboard"].tap()
info: [debug] Socket data received (50 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":17,"value":"Failed to hide keyboard."}
info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"Failed to hide keyboard."},"sessionId":"443adfcd-cfb0-49f3-98b5-af7b63e12e8e"}
info: <-- POST /wd/hub/session/443adfcd-cfb0-49f3-98b5-af7b63e12e8e/appium/device/hide_keyboard 500 17159.748 ms - 185

**Comment by Jonahss** [comment] 2015-05-06 22:17
What do you mean "with different machines". Do you mean different host computers with the same iOS simulators? Or do you mean different simulators? (8.3, 8.2, ipad, iphone).

**Comment by amedvedjev** [comment] 2015-05-07 07:25
i mean physically different machines.
we all have Mac-s. Mac Pro (personal) and Mac mini (as server for CI).
with all machines we did following:
 1) re-installed Appium 1.3.6 :
      - npm remove -g Appium
      - npm install -g Appium@1.3.6
 2) re-installed xCode 6.3.1 :
      - xcode removed from Application folder
      - deleted following folders:
          - /Library/Developer/CoreSimulator
          - /Users/Active_User/Library/Developer/CoreSimulator
          - /Users/Active_User/Library/Developer/Xcode
      - Recycle Box emptied
      - machine rebooted
      - installed XCode 6.3.1
  3) repeated same test with keyboard hide using same client and any same simulator e.g. 8.1

Result:
   - with 2 machines we have 100% 500 Error in Appium logs
   - with 2 machines we have 100% success status
   - in all cases keyboard hiding

**Comment by Jonahss** [comment] 2015-05-07 18:50
Oh my goodness, that sounds frustrating.
@imurchie any ideas?

**Comment by imurchie** [comment] 2015-05-13 19:01
I consistently get an error that the key is wrong:

```shell
info: --> POST /wd/hub/session/0a4f6414-0178-4d95-ae14-a0d545ffe59f/appium/device/hide_keyboard {"strategy":"pressKey","key":"Hide keyboard"}
info: [debug] Pushing command to appium work queue: "au.hideKeyboard('pressKey','Hide keyboard')"
info: [debug] Sending command to instruments: au.hideKeyboard('pressKey','Hide keyboard')
info: [debug] [INST] 2015-05-13 17:05:09 +0000 Debug: Got new command 7 from instruments: au.hideKeyboard('pressKey','Hide keyboard')
info: [debug] [INST] 2015-05-13 17:05:09 +0000 Debug: evaluating au.hideKeyboard('pressKey','Hide keyboard')
info: [debug] [INST] 2015-05-13 17:05:09 +0000 Debug: Hiding keyboard with keyName Hide keyboard
info: [debug] Socket data received (43 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":17,"value":"Invalid key name."}
info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"Invalid key name."},"sessionId":"0a4f6414-0178-4d95-ae14-a0d545ffe59f"}
info: <-- POST /wd/hub/session/0a4f6414-0178-4d95-ae14-a0d545ffe59f/appium/device/hide_keyboard 500 421.853 ms - 178
```

Is it possible to get a failed test while using the `--show-ios-log` server flag? This might provide more information to go on.

**Comment by sebv** [comment] 2015-06-10 05:33
You need to check if there is a "Hide keyboard" key.

There are different startegy you may try:
```
hideKeyboard() -> cb(err)
hideKeyboard(keyName, cb) -> cb(err)
hideKeyboard({strategy: 'pressKey', key:'<key>'}) -> cb(err)
hideKeyboard({strategy: 'tapOutside'}) -> cb(err)
```

**Comment by sebv** [comment] 2015-06-12 08:54
Closing, not a bug, may be reopened if needed.

**Closed by sebv** 2015-06-12 08:54 UTC
Labels: OnGoing

**Comment by priyankshah217** [comment] 2015-12-03 14:29
@sebv , can you open this issue. because i am also facing the same. I am using Appium 1.4.13 with java-client 3.2.0. 
Java code:
 `
((IOSDriver) wd).hideKeyboard(HideKeyboardStrategy.PRESS_KEY,"Hide keyboard");
`

Appium server log:
`
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"2e2eb9cc-7afe-4191-be1e-075e096faa5c"}
info: <-- POST /wd/hub/session/2e2eb9cc-7afe-4191-be1e-075e096faa5c/element/3/click 200 1334.928 ms - 74 {"status":0,"value":"","sessionId":"2e2eb9cc-7afe-4191-be1e-075e096faa5c"}
info: --> POST /wd/hub/session/2e2eb9cc-7afe-4191-be1e-075e096faa5c/appium/device/hide_keyboard {}
info: [debug] Pushing command to appium work queue: "au.hideKeyboard('default')"
info: [debug] Sending command to instruments: au.hideKeyboard('default')

info: [debug] [INST] 2015-12-03 14:27:06 +0000 Debug: Got new command 16 from instruments: au.hideKeyboard('default')

info: [debug] [INST] 2015-12-03 14:27:06 +0000 Debug: evaluating au.hideKeyboard('default')

info: [debug] [INST] 2015-12-03 14:27:06 +0000 Debug: target.frontMostApp().mainWindow().tapWithOptions({})

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"2e2eb9cc-7afe-4191-be1e-075e096faa5c"}
info: <-- GET /wd/hub/status 200 1.622 ms - 179 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"2e2eb9cc-7afe-4191-be1e-075e096faa5c"}

info: [debug] Socket data received (50 bytes)
info: [debug] Socket data being routed.

info: [debug] Got result from instruments: {"status":17,"value":"Failed to hide keyboard."}
info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"Failed to hide keyboard."},"sessionId":"2e2eb9cc-7afe-4191-be1e-075e096faa5c"}

info: <-- POST /wd/hub/session/2e2eb9cc-7afe-4191-be1e-075e096faa5c/appium/device/hide_keyboard 500 25699.763 ms - 185 
info: [debug] [INST] 2015-12-03 14:27:30 +0000 Error: VerboseError: Failed to hide keyboard.
`

Thanks,
Priyank Shah

**Comment by smccarthy** [comment] 2016-01-22 20:05
I get a similar error as @priyankshah217 .
I am using SauceLabs with Appium 1.4.16 and java-client 3.3.0.

((IOSDriver)sh.getDriver()).hideKeyboard(HideKeyboardStrategy.PRESS_KEY, "Done");
Causes :
org.openqa.selenium.WebDriverException: An error occurred while executing user supplied JavaScript. (WARNING: The server did not provide any stacktrace information)

On SauceLabs I see :
Command: POST appium/device/hide_keyboard 
Parameters:  {"key":"Done","strategy":"pressKey"} 
Response:  => {"message":"An error occurred while executing user supplied JavaScript.","origValue":"Invalid key name."}

**Comment by mmcintyre123** [comment] 2017-01-05 18:12
This works for me!  		
.elementByAccessibilityId('Hide keyboard')
Appium 1.5.3, Mocha, Javascript, iOS 9.3.4.

**Comment by shabana-parveen** [comment] 2017-06-08 09:17
I m still getting same error when I run my automation suit in saucelabs, I tried all, but couldn't luck. I tried with below capabilities as well:

		caps.setCapability("unicodekeyboard", true);
		caps.setCapability("resetkeyboard", true);

Valuable response will be appreciated.

**Comment by shabana-parveen** [comment] 2017-07-05 10:34
I solved above issue by mentioning driver.hidekeyboard() in try catch block like below: 
try{driver.hideKeyboard();}catch(Exception e){e.printStackTrace();}

but, some how driver.hidekeyboard() functionality is not working properly, Some time it works, sometime not.

**Comment by praveentata** [comment] 2017-08-14 23:53
When I perform hideKeyboard() it works fine but then deleted two characters from the field where the focus is.
For eg. First Name --> 'Test'
hideKeyboard(); --> will hide the keyboard.
Then it will delete s and t. Now First Name will have --> 'Te'

Is this a know issue or am I doing something wrong?

Thanks.

**Comment by shabana-parveen** [comment] 2017-08-16 06:12
@praveentata , please provide thread sleep before calling hidekeyboard(); it happens sometime.

**Comment by praveentata** [comment] 2017-08-16 14:07
Thanks for the reply. I will try that.

*Thank You,*

*Regards,*

*Praveen Tata.*

 *Please don't print this e-mail unless you really need to, save paper,
save the planet.*

**Comment by VasaviUppada** [comment] 2017-11-06 18:51
Hi @shabana-parveen,
I tried your resolution but it didn't workout for me for IOS.
try{driver.hideKeyboard();}catch(Exception e){e.printStackTrace();}

Is there any workaround to achieve this. 
Currently it is a blocker for me.

Is there any other solution for this issue?
![image](https://user-images.githubusercontent.com/30246758/32458105-1e765e58-c2e0-11e7-93db-309996db32f4.png)

This is how screen looks like. I can find the only way to hide keyboard is to click outside of the keyboard. but it is not working out for me.

I tried all below & nothing worked out for me.
            IOSDriver<MobileElement> iosDriver = (IOSDriver<MobileElement>) driver;
            try{
            		iosDriver.hideKeyboard();
            	} catch(Exception e){
            		e.printStackTrace();
            	}
//   iosDriver.hideKeyboard(HideKeyboardStrategy.TAP_OUTSIDE);  // not working
//   iosDriver.hideKeyboard(HideKeyboardStrategy.PRESS_KEY, "RETURN");	// not working
//   iosDriver.getKeyboard().pressKey("\n");	// not working 
//   iosDriver.getKeyboard().releaseKey(Keys.RETURN);	// not working
//   iosDriver.getKeyboard().pressKey(Keys.RETURN);	// not working

**Comment by praveentata** [comment] 2017-11-07 00:08
Hi Vu,

I am not an expert in this but one workaround can be tapping on "Get
Started" text that I can see in your snapshot. Or try scrolling into view
of some text present on your screen which you can tap on to hide the
keyboard.

You can refer to this blog on how to scroll into a view in appium :
http://www.qaautomated.com/2016/02/how-to-scroll-in-appium.html

I hope this helps.

*Thank You,*

*Regards,*

*Praveen Tata.*

 *Please don't print this e-mail unless you really need to, save paper,
save the planet.*

**Comment by shabana-parveen** [comment] 2017-11-07 04:10
@VasaviUppada , I agreed with @praveentata , please try.. I also do the same.. sometime I scrolled, or click on non clickable elements.

**Comment by VasaviUppada** [comment] 2017-11-07 05:24
Hi @praveentata,

I exactly did the same. clicked on "Get Started" button & scrolled up. It is working fine as well.

Thanks much for prompt reply. & is this a bug in IOS devices or appium ?
I feel like this is not an appropriate way to hide a keyboard. Still I'm following the same as we need to proceed further without any blocker.

**Comment by shabana-parveen** [comment] 2017-11-07 07:40
I understand your pain, cause I faced the same, I already discussed this issue on different-2 blogs(Stackoverflow github etc..) but this one is the only solution provided to me.
