### ISSUE TITLE
Version 1.22.1 throwing ClassCastException when using XPath special functions on Android 5 (API 21)

### ISSUE THREAD

**Issue by igorgiumellizup** [appium/appium#16145] opened 2021-11-22 12:44 UTC
## The problem

The Xpath locator ```//android.widget.EditText[@text='writing e-mail with expression']/following::android.widget.EditText[1]```worked with version 1.22.0.

With 1.22.1 it's breaking:

> An unknown server-side error occurred while processing the command. Original error: java.lang.ClassCastException: java.util.AbstractList$FullListIterator cannot be cast to org.eclipse.wst.xml.xpath2.processor.internal.types.NodeType
> Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
> System info: host: 'ZUP-2784.local', ip: '2804:7f5:948c:ab3d:2437:2063:2fea:f499%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.5', java.version: '11.0.11'
> Driver info: io.appium.java_client.android.AndroidDriver
> Capabilities {app: /Users/igordgzup/workspaces..., appActivity: .activity.MainActivity, appPackage: br.com.zup.beagle.appiumapp, automationName: UiAutomator2, databaseEnabled: false, desired: {app: /Users/igordgzup/workspaces..., appActivity: .activity.MainActivity, appPackage: br.com.zup.beagle.appiumapp, automationName: UiAutomator2, deviceName: ci_pixel_api_21, newCommandTimeout: 100000, platformName: android, platformVersion: 5, uiautomator2ServerInstallTimeout: 90000}, deviceApiLevel: 21, deviceManufacturer: unknown, deviceModel: Android SDK built for x86, deviceName: emulator-5554, deviceScreenDensity: 420, deviceScreenSize: 1080x1920, deviceUDID: emulator-5554, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 100000, pixelRatio: 2.625, platform: LINUX, platformName: Android, platformVersion: 5.0.2, statBarHeight: 66, takesScreenshot: true, uiautomator2ServerInstallTimeout: 90000, viewportRect: {height: 1728, left: 0, top: 66, width: 1080}, warnings: {}, webStorageEnabled: false}
> Session ID: 7d098af9-6dfe-47a6-bbc1-813e350011d2
> *** Element info: {Using=xpath, value=//android.widget.EditText[@text='writing e-mail with expression']/following::android.widget.EditText[1]}
> org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: java.lang.ClassCastException: java.util.AbstractList$FullListIterator cannot be cast to org.eclipse.wst.xml.xpath2.processor.internal.types.NodeType
> Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
> System info: host: 'ZUP-2784.local', ip: '2804:7f5:948c:ab3d:2437:2063:2fea:f499%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.5', java.version: '11.0.11'
> Driver info: io.appium.java_client.android.AndroidDriver
> Capabilities {app: /Users/igordgzup/workspaces..., appActivity: .activity.MainActivity, appPackage: br.com.zup.beagle.appiumapp, automationName: UiAutomator2, databaseEnabled: false, desired: {app: /Users/igordgzup/workspaces..., appActivity: .activity.MainActivity, appPackage: br.com.zup.beagle.appiumapp, automationName: UiAutomator2, deviceName: ci_pixel_api_21, newCommandTimeout: 100000, platformName: android, platformVersion: 5, uiautomator2ServerInstallTimeout: 90000}, deviceApiLevel: 21, deviceManufacturer: unknown, deviceModel: Android SDK built for x86, deviceName: emulator-5554, deviceScreenDensity: 420, deviceScreenSize: 1080x1920, deviceUDID: emulator-5554, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 100000, pixelRatio: 2.625, platform: LINUX, platformName: Android, platformVersion: 5.0.2, statBarHeight: 66, takesScreenshot: true, uiautomator2ServerInstallTimeout: 90000, viewportRect: {height: 1728, left: 0, top: 66, width: 1080}, warnings: {}, webStorageEnabled: false}
> Session ID: 7d098af9-6dfe-47a6-bbc1-813e350011d2
> *** Element info: {Using=xpath, value=//android.widget.EditText[@text='writing e-mail with expression']/following::android.widget.EditText[1]}
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
> 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
> 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
> 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
> 	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
> 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
> 	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
> 	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
> 	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
> 	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
> 	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:61)
> 	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
> 	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
> 	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
> 	at io.appium.java_client.DefaultGenericMobileDriver.findElementByXPath(DefaultGenericMobileDriver.java:151)
> 	at io.appium.java_client.AppiumDriver.findElementByXPath(AppiumDriver.java:1)
> 	at io.appium.java_client.android.AndroidDriver.findElementByXPath(AndroidDriver.java:1)
> 	at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
> 	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
> 	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:57)
> 	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
> 	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
> 	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:182)
> 	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:179)
> 	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)

## Environment

* Appium version (or git revision) that exhibits the issue: **java-client 7.6.0**
* Desktop OS/version used to run Appium: **macOS Big Sur 11.6**
* Node.js version (unless using Appium.app|exe): **14.16.0**
* Npm or Yarn package manager: **7.10.0**
* Mobile platform/version under test: **Android 5**
* Real device or emulator/simulator:  **Android Emulator, pixel profile, Android 5**
* Appium CLI or Appium.app|exe: **Appium Server 1.22.1**

**Comment by mykola-mokhnach** [comment] 2021-11-22 12:46
Duplicate of https://github.com/appium/appium/issues/16142

XPath2 has stricter parsing rules, so the locator must be updated to satisfy these.

**Closed by mykola-mokhnach** 2021-11-22 12:46 UTC
