### ISSUE TITLE
Beta 20 broke integration with @wdio/appium-service

### ISSUE THREAD

**Issue by nextlevelbeard** [appium/appium#16676] opened 2022-03-28 18:50 UTC
With beta 20 and up, integration stops working.
See https://github.com/webdriverio/webdriverio/issues/8012 

Diff of beta 19 -> beta 20
https://github.com/appium/appium/compare/appium@2.0.0-beta.19...appium@2.0.0-beta.20

Also, with beta 19 this WDIO config works:
```js
['appium', {
  args: {
    port: 4446,
    'allow-insecure': ['execute_driver_script', 'chromedriver_autodownload', 'adb_shell'],
  },
}],
```

This doesn't:
```js
['appium', {
  args: {
    port: 4446,
    'allow-insecure': ['execute_driver_script', 'chromedriver_autodownload', 'adb_shell'],
    'use-plugins': ['device-farm' , 'appium-dashboard'],
  },
}],
```
logging
```shell
2022-03-28T18:51:26.264Z DEBUG @wdio/appium-service: Will spawn Appium process: node /Users/REDACTED/repos/REDACTED/node_modules/appium/build/lib/main.js --base-path / --port 4446 --allow-insecure execute_driver_script,chromedriver_autodownload,adb_shell --use-plugins device-farm,appium-dashboard
2022-03-28T18:51:26.801Z ERROR @wdio/appium-service: Appium exited before timeout (exit code: 2)
usage: main.js [-h] [-v] {server,driver,plugin} ...

2022-03-28T18:51:26.801Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Appium exited before timeout (exit code: 2)
usage: main.js [-h] [-v] {server,driver,plugin} ...

    at ChildProcess.<anonymous> (/Users/REDACTED/repos/REDACTED/node_modules/@wdio/appium-service/build/launcher.js:110:22)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)

Continue...
```

Can developers provide some context/documentation on what exactly changed and what should be updated in the `@wdio/appium-service` [codebase](https://github.com/webdriverio/webdriverio/tree/main/packages/wdio-appium-service)?

**Comment by mykola-mokhnach** [comment] 2022-03-28 19:58
I assume this is related to the recent changes to the command line arguments parser.
@boneskull do we have the changes documented anywhere yet?

**Comment by jlipps** [comment] 2022-03-29 22:02
All the changes are in the [migration guide](https://github.com/appium/appium/blob/2.0/docs/en/advanced-concepts/migrating-to-appium-2.0.md). We don't have a changelog of within-beta releases though, so let's see what @boneskull says.

Meanwhile, what if instead of 

```
node /Users/REDACTED/repos/REDACTED/node_modules/appium/build/lib/main.js --base-path / --port 4446 --allow-insecure execute_driver_script,chromedriver_autodownload,adb_shell --use-plugins device-farm,appium-dashboard
```

You ran

```
node /Users/REDACTED/repos/REDACTED/node_modules/appium/build/lib/main.js server --base-path / --port 4446 --allow-insecure execute_driver_script,chromedriver_autodownload,adb_shell --use-plugins device-farm,appium-dashboard
```

Also, not sure that it would matter, but I usually write these args like `--arg=val` instead of `--arg val`.

**Comment by boneskull** [comment] 2022-03-30 21:49
The following flags are correct:

```bash
node /Users/REDACTED/repos/REDACTED/node_modules/appium/build/lib/main.js --base-path / --port 4446 --allow-insecure execute_driver_script,chromedriver_autodownload,adb_shell --use-plugins device-farm,appium-dashboard
```

Appium reports configuration:

```
[Appium] Non-default server args:
[Appium] {
[Appium]   allowInsecure: [
[Appium]     'execute_driver_script',
[Appium]     'chromedriver_autodownload',
[Appium]     'adb_shell'
[Appium]   ],
[Appium]   basePath: '/',
[Appium]   port: 4446,
[Appium]   usePlugins: [
[Appium]     'device-farm',
[Appium]     'appium-dashboard'
[Appium]   ]
[Appium] }
```

...so I'm not sure what's happening here.  There's really not enough information in the logs given in the issue description.

**Comment by boneskull** [comment] 2022-03-30 21:52
@nextlevelbeard Looks like you'll need to tease more output from the subprocess out of wdio.  The ellipsis in the log output...

```
usage: main.js [-h] [-v] {server,driver,plugin} ...
```

...is doing a _lot_ of work here.  :wink:

**Comment by nextlevelbeard** [comment] 2022-03-31 08:06
@boneskull I'll see if I can grab that output.

In the meantime, as pointed out by @Plazzko in https://github.com/webdriverio/webdriverio/issues/8012, it seems that the service is waiting for output from `stdout` before proceeding.
```js
process.stdout.on('data', (data) => {
            if (data.includes('Appium REST http interface listener started')) {
                log.debug(`Appium started with ID: ${process.pid}`)
                callback(null, process)
            }
        })
```

Changing it to `stderr` seems to solve the issue.
Is this desired behavior?

**Comment by jlipps** [comment] 2022-03-31 17:06
In our code we are simply using the `.info` method of our logger, and this hasn't changed. I also can't reproduce it being sent to stderr. When run from the terminal it is being written to stdout. What do you see when you run Appium from the command line? Is it possible the wdio service is doing some stream redirection? Still, not sure why this would show up as a regression.

**Comment by mykola-mokhnach** [comment] 2022-09-01 19:16
Closed as fixed

**Closed by mykola-mokhnach** 2022-09-01 19:16 UTC
Labels: Documentation, NeedsInfo, v2
