### ISSUE TITLE
Could not acquire lock on /tmp/uia2_device_port_guard

### ISSUE THREAD

**Issue by sshock** [appium/appium#14682] opened 2020-08-27 18:48 UTC
## The problem

I'm seeing this error a lot in appium.log after upgrading to appium 1.18.0.  I never saw it before when running appium 1.17.1.  Is it serious or can it be safely ignored?

```
[UiAutomator2] Unable to remove system port forward: Could not acquire lock on /tmp/uia2_device_port_guard. Original error: Error: EEXIST: file already exists, open '/tmp/uia2_device_port_guard'
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable): 1.17.1
* Desktop OS/version used to run Appium: Ubuntu 18.04
* Node.js version (unless using Appium.app|exe): 10.22.0
* Npm or Yarn package manager: npm 6.14.6
* Mobile platform/version under test: android
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: cli

## Details

There are no timestamps in appium.log, so it's hard to tell exactly how often this is occurring, but on one server it shows up in the log 206 times, which is over a course of two or three weeks maybe.  On all my other appium 1.18.0 servers it has only occurred about 5-10 times.  On my appium 1.17.1 servers it has never occurred.

## Link to Appium logs

This is the log from the server where it occurred over 200 times:

https://gist.github.com/sshock/afa15b1d2b32944e6aee227475ce8f60

**Comment by mykola-mokhnach** [comment] 2020-08-27 19:53
Since v 1.18 uia2 driver uses file-based locks on device port allocation operations to avoid unexpected port conflicts when multiple drivers running in parallel are trying to acquire the same system port. The log is very messy and it is hard to understand what is going on there. Looking at the exception itself, I have created https://github.com/appium/appium-support/pull/204 patch. But this is just a pure guess and it needs to be tested to confirm it makes the difference.

**Comment by sshock** [comment] 2020-08-27 20:25
Cool, well it's worth a try.  Is there an easy way for me to hot-patch this fix into place to test it?

Also, I just did did an ls and it appears this file not only exists but was created like 6 days ago:

```
$ ls -l /tmp/uia2_device_port_guard
-rw-rw-r-- 1 deployer deployer 0 Aug 21 04:17 /tmp/uia2_device_port_guard
```

That makes me wonder if maybe appium should be deleting that file on start-up?  Of course, with the fix you just made, maybe that won't matter.

**Comment by mykola-mokhnach** [comment] 2020-08-28 04:34
Simply check out the patch locally, transpile it and then link the module to your local npm rep similar to what is described at https://github.com/appium/appium/issues/13227#issuecomment-531812534

**Comment by mykola-mokhnach** [comment] 2020-08-28 04:35
> That makes me wonder if maybe appium should be deleting that file on start-up? Of course, with the fix you just made, maybe that won't matter.

Appium must not assume anything about this file, because this is a cross-process lock and we never know what another processes are doing at this time.

**Comment by sshock** [comment] 2020-08-28 16:17
> Simply check out the patch locally, transpile it and then link the module to your local npm rep similar to what is described at [#13227 (comment)](https://github.com/appium/appium/issues/13227#issuecomment-531812534)

Ok, I've never done much with npm, but I'll see if I can give it a try soon.  Note though that the problem already hasn't reproduced again ever since I deleted the file manually yesterday.

**Comment by sshock** [comment] 2020-08-28 16:20
> > That makes me wonder if maybe appium should be deleting that file on start-up? Of course, with the fix you just made, maybe that won't matter.
> 
> Appium must not assume anything about this file, because this is a cross-process lock and we never know what another processes are doing at this time.

Really?  I've only ever seen a single `node` process that runs appium.  Am I missing something?

**Comment by mykola-mokhnach** [comment] 2020-08-28 16:20
This could be a sort of race conditions, which is quite hard to reproduce. It also could be that the process crash due to out of memory error actually lead the lock to transition to a weird state, while some scheduled actions were not performed on it.

**Comment by sshock** [comment] 2020-08-28 16:22
> This could be a sort of race conditions, which is quite hard to reproduce. It also could be that the process crash due to out of memory error actually lead the lock to transition to a weird state, while some scheduled actions were not performed on it.

Yeah, my guess is that appium crashed at a certain point that caused the lock file to be left around.  That's kind of why I was asking about clearing it at start-up.

**Comment by mykola-mokhnach** [comment] 2020-08-28 16:23
> Really? I've only ever seen a single node process that runs appium. Am I missing something?

Appium supports two parallel execution scenarios: multiple sessions within single node process or multiple sessions within multiple processes. We never know which one is used by a client

**Comment by sshock** [comment] 2020-08-28 16:40
> Appium supports two parallel execution scenarios: multiple sessions within single node process or multiple sessions within multiple processes. We never know which one is used by a client

Cool, I had no idea running multiple instances of appium was a supported workflow.  Good to know.

This is probably a bad idea, but maybe it could try to detect if any other appiums are running and wipe out the lock file if there aren't any?  Alternatively, maybe it could check the timestamp on the lock file and delete it if it is very old?

Although, with the patch you came up with maybe we don't even need to worry about the problem of this lock file getting left behind after a crash...

**Comment by alexander-poulikakos** [comment] 2020-08-31 19:57
I also had the same problem (lockfile: uia2_device_port_guard was created Aug 28 18:29 ) but problem disappeared after removing the file manually.

I think what happened on aug 28 was the device ran out of battery.

**Comment by sshock** [comment] 2020-09-01 22:30
To test this I went ahead and reproduced the problem by manually creating the `/tmp/uia2_device_port_guard` file.  Then I updated appium-support under node_module/appium to the latest master with the patch by running `npm install git+https://github.com/appium/appium-support#4b4f85e`.  Then I verified that both `appium-support/lib/util.js` and `appium-support/build/lib/util.js` now had the change of the patch.

Unfortunately, it did **not** fix the problem.  I ran into the exact same error.

**Comment by sshock** [comment] 2020-09-01 22:59
Just to be sure, I tried to redo this test but building everything from scratch as follows:

```
git clone https://github.com/appium/appium.git
git clone https://github.com/appium/appium-uiautomator2-driver.git
git clone https://github.com/appium/appium-support.git
cd appium-support && npm link && cd ..
cd appium-uiautomator2-driver && npm link appium-support && npm link && cd ..
cd appium && npm link appium-uiautomator2-driver && npm link
npm install
node .
```

Unfortunately after doing all that although it appeared to run fine at first, after only a few seconds I got a bunch of error about yargs that look like this:

```
[debug] [Appium] import yargs from 'yargs';
[debug] [Appium]        ^^^^^
[debug] [Appium]
[debug] [Appium] SyntaxError: Unexpected identifier
```

So then I tried `npm install yargs`, but sadly that didn't help.

I'm not familiar with nodejs or npm at all so to test this manually I would need some more explicit instructions.

Of course, this is all just an extra test just to be sure, since I'm not positive that how I tested it as mentioned in the comment above was a proper way to do it.

@mykola-mokhnach maybe you or someone else can test this more easily than me.  It's real easy to reproduce (just manually create that file, then start appium and try to create a sesion; it will fail after a couple minutes with the EEXIST error).

**Comment by mykola-mokhnach** [comment] 2020-09-02 09:28
Thanks for checking it. I did several local tests and it looks like such issue might only happen if the process has been forcefully terminated using sigkill or something like that, so it did not get a chance to do a proper cleanup. The EEXIST error message is just the result of timeout on file lock operation: https://github.com/npm/lockfile/issues/26

I'm currently adding several changes to both the support lib and uia2 driver to have a proper workaround.

**Comment by sshock** [comment] 2020-09-02 16:19
Awesome, thanks!  I'll look forward to testing it.

**Comment by mykola-mokhnach** [comment] 2020-09-03 05:47
I have merged the patch to uia2 driver and published it to appium@beta. It is ready for testing.

**Comment by sshock** [comment] 2020-09-03 20:41
This appears to be working.  After updating to the new appium, I then created the lock file manually and then started appium and the file went away and I was able to connect to several devices no problem.

**Comment by mykola-mokhnach** [comment] 2020-09-04 05:43
Thanks for verifying it

**Closed by mykola-mokhnach** 2020-09-04 05:43 UTC
Labels: NeedsInfo, UIAutomator2

**Comment by kazzmir** [comment] 2020-09-22 19:09
The pr in uiautomator2 to delete the file and retry the lock seems reasonable, but would it be better to avoid the locking situation entirely if ops.systemPort is already set by virtue of the `systemPort` capability being passed in by the user?

**Comment by mykola-mokhnach** [comment] 2020-09-22 19:27
@kazzmir Feel free to push a PR if you think avoiding the lock would improve the performance

**Comment by ShouryaMishra712** [comment] 2020-10-27 15:23
I just removed 'uia2_device_port_guard' file from the path 'C:\Users\shm71\AppData\Local\Temp\uia2_device_port_guard'
and the error is gone....
