### ISSUE TITLE
io.appium.uiautomator2  Cached elements 'By.xpath: */child::*' do not exist in DOM anymore when scrolling through a ListView

### ISSUE THREAD

**Issue by bart-tricentis** [appium/appium#14586] opened 2020-07-22 12:29 UTC
## The problem

When scrolling through a ListView and gathering the child elements the "Cached elements 'By.xpath: */child::*' do not exist in DOM anymore" exception is thrown.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18
* Last Appium version that did not exhibit the issue (if applicable): 1.9.1
* Desktop OS/version used to run Appium: Windows 10 64bit
* Node.js version (unless using Appium.app|exe): 12.18.2
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 8/10
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: CLI

## Details

I have an app with a list view that contain 20 elements but only 11 are visible at once. I need all of the child elements so in a loop I gather all the visible ones, then swipe a bit. After that I collect the new child elements and if no new elements appear after a swipe I finish the loop. 100% of the time, when I make the final swipe that does not change the contents of the list view I get the exceptions. (Occasionally I get it in one of the "mid" swipes)

## Link to Appium logs

[appium_log.txt](https://github.com/appium/appium/files/4959883/appium_log.txt)

## Code To Reproduce Issue [ Good To Have ]
```
            var capabilities = getAndroidOptions(AppPath);
            driver = new AndroidDriver<IWebElement>(AndroidServerUri,
                capabilities);
            driver.ResetApp();
            Size device = driver.Manage().Window.Size;
            var bar = (AppiumWebElement)driver.FindElementById("android:id/tabs");
            ReadOnlyCollection<AppiumWebElement> children = bar.FindElementsByXPath("*/child::*");
            children[9].Click();
            var button = driver.FindElementById("com.tricentis.androidtestapp:id/openListView");
            button.Click();
            Thread.Sleep(300);
            var list = (AppiumWebElement)driver.FindElementById("android:id/select_dialog_listview");
            ReadOnlyCollection<AppiumWebElement> listItems = list.FindElementsByXPath("*/child::*");
            List<string> labels = new List<string>();
            bool breaking;

            while (true) {
                breaking = true;
                Thread.Sleep(500);
                listItems = list.FindElementsByXPath("*/child::*");
                foreach (AppiumWebElement item in listItems) {
                    if (!labels.Contains(item.Text)) {
                        labels.Add(item.Text);
                        breaking = false;
                    }
                }

                if (breaking) {
                    break;
                }

                TouchAction swipe = new TouchAction(driver);
                swipe.Press(device.Width / 2, device.Height / 2).Wait(300)
                    .MoveTo(device.Width / 2, device.Height * 0.3).Release();
                swipe.Perform();               
            }

            driver.CloseApp();




private static AppiumOptions getAndroidOptions(string app)
        {
            var capabilities = new AppiumOptions();
            capabilities.AddAdditionalCapability(AndroidMobileCapabilityType.NoSign, true);
            capabilities.AddAdditionalCapability(MobileCapabilityType.PlatformName, "Android");
            capabilities.AddAdditionalCapability(MobileCapabilityType.Udid, "emulator-5554");
            capabilities.AddAdditionalCapability(MobileCapabilityType.AutomationName,
                AutomationName.AndroidUIAutomator2);
            capabilities.AddAdditionalCapability(AndroidMobileCapabilityType.UnicodeKeyboard, true);
            capabilities.AddAdditionalCapability(AndroidMobileCapabilityType.ResetKeyboard, true);
            //capabilities.AddAdditionalCapability(MobileCapabilityType.App, app);
            capabilities.AddAdditionalCapability("dontStopAppOnReset", true);
            capabilities.AddAdditionalCapability("noReset", true);
            capabilities.AddAdditionalCapability("fullReset", false);
            capabilities.AddAdditionalCapability("appActivity", "MainActivity");
            capabilities.AddAdditionalCapability("appPackage", ****);
            return capabilities;
        }
```

**Comment by sme81** [comment] 2020-07-22 13:46
Was about to raise this same issue myself.

Doing a pageSource/xml dump at the end shows that the element exists.

Has worked for me since appium 1.12 through to 1.17. Upgrading to 1.18 causes issue, downgrading to 1.17 behaves as expected.

**Comment by mykola-mokhnach** [comment] 2020-07-22 14:06
This is most likely caused by https://github.com/appium/appium-uiautomator2-server/pull/363, which was a result of another bug fix.

**Comment by sme81** [comment] 2020-07-22 14:22
The intended behaviour in 1.18.0 is still what @bart-tricentis and myself expect and do see in 1.17.1, correct?

**Comment by mykola-mokhnach** [comment] 2020-07-22 14:27
I assume it will be necessary to change the xpath locator to make it working in 1.18+

**Comment by KazuCocoa** [comment] 2020-07-22 14:45
Ah... then, it is necessary to address the update stuff in our release note if the XPath locator update was necessary

**Comment by mykola-mokhnach** [comment] 2020-07-22 14:48
@KazuCocoa Makes sense. This is only relevant for a very limited amount of cases where one uses xpath locator, which points or relates on the root element and that root element is a result of another search

**Comment by sme81** [comment] 2020-07-23 07:48
Similarly, I have a listView that needs scrolled to bring new options onto screen to click. Even when scrolled and items 1 to 11 are now gone, with the screen showing items 31 to 41, doing a listView.FindElements() will return only items 1 to 11. 

This seems like established accepted functionality is changing? And only if you use xpath?

**Comment by mykola-mokhnach** [comment] 2020-07-23 08:59
@sme81 I think I know what the cause might be. Please check if the fix https://github.com/appium/appium-uiautomator2-server/pull/371 works for you

**Comment by sme81** [comment] 2020-07-23 15:01
looks to be behaving as expected

**Comment by mykola-mokhnach** [comment] 2020-07-23 15:36
The fix has been published to appium@beta

**Closed by mykola-mokhnach** 2020-07-23 15:36 UTC
Labels: Bug, UIAutomator2
