### ISSUE TITLE
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null with Genymotion

### ISSUE THREAD

**Issue by danielMayberg** [appium/appium#9119] opened 2017-08-30 08:28 UTC
## The problem
When running test suites from jenkins, I get on at least one of my runs a series of test failures with
UiAutomator exited unexpectedly with code 0

## Environment
Appium 1.6.4
Ruby
genymotion emulator running on mac
Galaxy S6 api23 emulator on genymotion

## Details

I'm not sure what causes the problem, it may be the test starting to execute prior to the emulator finishing to load the app. I read similar issues on the forum but still could not fix. would love for some help/suggestions. Thanks

## Link to Appium logs
Appium log:
[appium_log.txt](https://github.com/appium/appium/files/1262846/appium_log.txt)

This is the exception that I see from the genymotion emulator log:
ter_android_hardware_Radio DONE
08-28 04:11:51.753 D/AndroidRuntime(19839): Calling main entry com.android.commands.uiautomator.Launcher
08-28 04:11:51.759 D/AndroidRuntime(19839): Shutting down VM
08-28 04:11:51.761 E/UiAutomatorTestRunner(19839): uncaught exception
08-28 04:11:51.761 E/UiAutomatorTestRunner(19839): java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.accessibility.IAccessibilityManager.registerUiTestAutomationService(android.os.IBinder, android.accessibilityservice.IAccessibilityServiceClient, android.accessibilityservice.AccessibilityServiceInfo)' on a null object reference
08-28 04:11:51.761 E/UiAutomatorTestRunner(19839): 	at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:337)
08-28 04:11:51.761 E/UiAutomatorTestRunner(19839): 	at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:89)
08-28 04:11:51.761 E/UiAutomatorTestRunner(19839): 	at android.app.UiAutomation.connect(UiAutomation.java:197)
08-28 04:11:51.761 E/UiAutomatorTestRunner(19839): 	at com.android.uiautomator.core.UiAutomationShellWrapper.connect(UiAutomationShellWrapper.java:32)
08-28 04:11:51.761 E/UiAutomatorTestRunner(19839): 	at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:118)
08-28 04:11:51.761 E/UiAutomatorTestRunner(19839): 	at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
08-28 04:11:51.761 E/UiAutomatorTestRunner(19839): 	at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
08-28 04:11:51.761 E/UiAutomatorTestRunner(19839): 	at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
08-28 04:11:51.761 E/UiAutomatorTestRunner(19839): 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-28 04:11:51.761 E/UiAutomatorTestRunner(19839): 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)

**Comment by ashwither** [comment] 2017-08-30 09:17
This looks like it could be a duplicate of #9055

**Comment by mykola-mokhnach** [comment] 2017-08-30 09:24
This might be an internal UIAutomation issue. I would try to use UIAutomation2 backend instead.

**Comment by danielMayberg** [comment] 2017-08-30 09:50
mykola-mokhnach , I tried UIAutomator2 but it caused too many crashes so I returned to UiAutomator1, do you think there is another possibility?

**Comment by mykola-mokhnach** [comment] 2017-08-30 10:19
We are working on espresso driver now, but it's in early beta stage . You could join the development, so you'd have another possibility.

**Closed** 2017-09-14 18:17 UTC
Labels: Android, ThirdParty

**Comment by otoniel-isidoro** [comment] 2017-09-24 19:58
This error looks like occurs just when the process `com.android.commands.monkey` is running. After I kill it the appium runs the test normally.
To kill it just run:
`adb shell ps | grep com.android.commands.monkey | awk '{print $2}' | xargs adb shell kill -9`

**Comment by SamyQAZ** [comment] 2017-09-27 08:47
Same with mer too.

Got this error in Appium logs:
Unhandled rejection Error: Error executing adbExec. Original error: 'Command '/Users/apple/android-sdk/platform-tools/adb -P 5037 -s 92b9b098 shell ime set io.appium.android.ime/.UnicodeIME' exited with code 1'; Stderr: 'error: device '92b9b098' not found'; Code: '1'
    at ADB.execFunc$ (../../../lib/tools/system-calls.js:234:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
