### ISSUE TITLE
Fails when I run using iOS 15

### ISSUE THREAD

**Issue by 146613** [appium/appium#16244] opened 2021-12-13 16:14 UTC
## The problem

Fails when I run using iOS 15

## Environment

* Appium version 1.18 or 1.22
* iOS 15
* Apple beta xcode

## Details
I am receiving 

self = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x10737f640>
response = {'status': 500, 'value': '{"value":{"error":"unknown error","message":"An unknown server-side error occurred while pro...UI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:373:25)"}}'}

The app that I am automating has a pop-up window after the application launch that must be accepted.  At this point, the error occurs

## Link to Appium logs

This only occurs with iOS 15 and Appuim 1.18 or 1.22.  If I use anything under 15 (14 and below) there is no issue
[appium-server-logs_1_22.txt](https://github.com/appium/appium/files/7705219/appium-server-logs_1_22.txt)
[appium-server-logs_1.18.3.txt](https://github.com/appium/appium/files/7705220/appium-server-logs_1.18.3.txt)

**Comment by mykola-mokhnach** [comment] 2021-12-13 16:22
Duplicate of https://github.com/appium/appium/issues/16025

**Closed by mykola-mokhnach** 2021-12-13 16:22 UTC
