### ISSUE TITLE
iOS simulator always restart( reboot ) before appium test.

### ISSUE THREAD

**Issue by amitrparmar** [appium/appium#13916] opened 2020-02-05 11:35 UTC
## The problem

I am trying to run test on simulator but the issue is, when request hits the appium, simulator starts rebooting. Every time it occurs.

I have also set no reset to false but it didn't worked as expected. It still reboots.

I have also looked into below closed issues but it didn't addressed I guess. So I think it is better to open a new issue item.

## Environment

* appium - 1.16.0-beta.1
* npm - 6.12.1
* node - 12.12.0
* Java - openJDK '13'
* Xcode - 11.3
* MAC - macOS Cataline

##  Closed Issues
* https://github.com/appium/appium/issues/6475
* https://github.com/appium/appium/issues/2136

**Comment by mykola-mokhnach** [comment] 2020-02-05 13:30
Please provide the full server log

**Comment by mykola-mokhnach** [comment] 2020-02-05 13:32
Might be also a duplicate of https://github.com/appium/appium/issues/13503#issuecomment-581790787

**Comment by amitrparmar** [comment] 2020-02-06 11:44
Hi @mykola-mokhnach , 

There are two options which are noReset and fullREset. Might be conflicting in my case. So I am investiging more on this. I also get few reference from ( https://discuss.appium.io/t/difference-between-noreset-and-fullreset/14312 ) item.

I am not able to test that because from today, I continuously getting issue like 

* (INFO: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: The simulator 2A18F3A7-1942-4330-BA14-0A486F27677E has failed to finish booting after 120.014s.) 

Emulator test runs too much slow.

I am expecting just reinstall my application on emulator but not wanted to reboot emulator. It would be really helpful if you can suggest valid capability setting. 

And also suggest how can I make it faster.

I also request to keep this issue open until we correct it.
Thanks.

**Comment by KazuCocoa** [comment] 2020-02-06 12:01
Please attache the full log as gist since we could not track what exactly happened on your environment
https://github.com/appium/appium/issues/13916#issuecomment-582407866

**Comment by amitrparmar** [comment] 2020-02-07 09:37
Hi @KazuCocoa , 

Please see log here below

Test Log (Having Full Reset = true)


### Environment
* appium        - 1.16.0-beta.3    
* npm        - 6.13.1    
* node        – 13.2.0    
* Java        - openJDK '13'    
* Xcode        - 10.1    
* Emulator        - iPad Pro (12.9-inch)(2nd generation) - 11.1    
* MAC        - macOS High Sierra (v. 10.13.6)

https://gist.github.com/amitrparmar/850497df103468d8c3d461382da18626#file-full-reset-false-emulator-error-logs-log

If you suggest any other way, I'll test accordingly and provide more logs. Thanks.

**Comment by mykola-mokhnach** [comment] 2020-02-07 11:12
It is expected that after a full reset the simulator booting would take more time than usual. Although, it might be that the machine where tests are running it too slow to support modern Xcode SDK and needs to be upgraded. How much time the Simulator cold boot takes if resetted manually?

**Comment by amitrparmar** [comment] 2020-02-07 13:05
It takes around 3-4 minutes, sometimes more. Is there any workaround to make it run. 

Any emulator available in mac so it can behave like real device. 

I wanted to make it run any how. Please guide.

**Comment by mykola-mokhnach** [comment] 2020-02-07 13:12
Currently the simulator boot timeout is hardcoded to 2 minutes: https://github.com/appium/appium-ios-simulator/blob/1f1140bf46bb0af7d6f06e31c3337aa517a14156/lib/simulator-xcode-8.js#L17

There is no capability in xcuitest driver to customise it, but it could be easily added

**Comment by amitrparmar** [comment] 2020-02-10 05:27
Thanks @mykola-mokhnach , I have changed that settings which you suggested. 

But did you get the change to have a look into the second log which I mentioned. Not I'm getting that error. 

Please have a look one and guide.

### Log 2

https://gist.github.com/amitrparmar/db42463bf572a10e90dea05a9a048ffe#file-full-reset-false-emulator-error-logs_-2-log

**Comment by mykola-mokhnach** [comment] 2020-02-10 10:30
> [WD Proxy] Got an unexpected response with status 500: {"value":{"error":"session not created","message":"Failed to launch StayinFrontTouch application","traceback":""},"sessionId":"151E66B8-49A0-4406-8AD3-7A5A682F2365"}

The error is coming from WDA/XCTest itself. You could check the device log to see more details about it

**Comment by bogdancucosel** [comment] 2020-02-13 13:57
Hi,

Not sure, if it is related, but I struggled with this for the last 2 days.
No matter the capabilities sent, (noReset, fullReset), when, after each test I was calling resetApp, the iOS simulator got restarted.

The behavior was the same on a local machine (version 1.16.0) and on sauce (version 1.15.0 the latest for iOS).

The first issues I was having was that the bool capabilities I was sending them as string; it seems that some do not get parsed as bool , and for example resetOnSessionStartOnly was string and the sim always got restarted.

After fixing the above, I tried on Sauce but I was having the same behavior.

I realized that I left some other caps, and removed them all, and then the resetApp was behaving the way I wanted.

It seems that sending enableAsyncExecuteFromHttps : true, was causing this behavior on sauce (version 1.15.0)

Maybe this helps

**Comment by mykola-mokhnach** [comment] 2020-02-13 14:02
I can confirm there are some capabilities, which implicitly force simulator restart. This is related to the implicit requirement that Simulator process should not be running in order to edit its preferences or databases. Otherwise these would be either locked or will not be picked up till the next Simulator restart.

**Comment by mykola-mokhnach** [comment] 2020-02-19 21:37
xcuitest driver in appium@beta got the `simulatorStartupTimeout` capability, which allows to customize Simulator startup timeout

**Closed by mykola-mokhnach** 2020-02-19 21:37 UTC
Labels: Enhancement

**Comment by fllaryora** [comment] 2020-05-22 15:37
Hi,  I am having the same issue, 
Cold you re-open the issue?
Environment
appium - v1.17.1
npm - 6.11.3
node - 1v12.12.0
Java - OpenJDK Runtime Environment (Zulu 8.44.0.9-CA-macosx)
Xcode - 11.2.1
MAC - macOS Cataline
