### ISSUE TITLE
The WDA  support Unlock the grid sudokus ?

### ISSUE THREAD

**Issue by Kitty2014** [appium/appium#10247] opened 2018-02-23 07:06 UTC
The problem
The WDA  support Unlock the grid ?
sudokus cannot be unlock with Three-point displacement

Environment

iOS Demo
https://github.com/ZLFighting/GestureLockDemo

refer to  code

TouchAction(driver).press(x=180, y=598).move_to(x=0, y=0).wait(100).move_to(x=0, y=181).wait(100).move_to(x=0, y=181).wait(100).move_to(x=181, y=0).wait(100).move_to(x=181,y=0).release().perform()

**Comment by mykola-mokhnach** [comment] 2018-02-23 07:18
Duplicate of https://github.com/facebook/WebDriverAgent/issues/872

**Closed by mykola-mokhnach** 2018-02-23 07:18 UTC
