### ISSUE TITLE
sendKeys on XCUIElementTypeTextView is typing 1 character at a time and fails out with NoSuchDriverError exception

### ISSUE THREAD

**Issue by rahulcode** [appium/appium#13444] opened 2019-10-17 10:02 UTC
## The problem

sendKeys on XCUIElementTypeTextView is typing 1 character at a time and sometimes fails out with NoSuchDriver Exception

Works fine for XCUIElementTypeTextField.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): 1.13.0
* Desktop OS/version used to run Appium: 10.14.5.
* Node.js version (unless using Appium.app|exe): v10.12.0
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: iOS 13.0
* Real device or emulator/simulator: iPhone 6S Plus
* Appium CLI or Appium.app|exe:
Client : 6.1.0
## Details

findBy return the element for me, there is only 1 element on the screen.
## Link to Appium logs
<img width="767" alt="Screenshot 2019-10-17 at 2 57 29 PM" src="https://user-images.githubusercontent.com/19573187/66997614-6e9b4e80-f0f0-11e9-8493-7fb5e40be6bf.png">

https://gist.github.com/rahulcode/3c60d72ef4fc29c420a4e21f28ec0d7c

## Code To Reproduce Issue [ Good To Have ]

Sample
`
			element = findBy(identifier, timeout);
			if (element != null) {

				// element.clear();
				Logger.log("Entering text : " + textToBeTyped);
				element.sendKeys(textToBeTyped);

			}`

**Comment by rahulcode** [comment] 2019-10-17 10:05
Behavior is same for both sendkeys() and clear()
Both are actually typing or clearing up 1 character at a time.

Please let me know any more information is needed.

**Comment by mykola-mokhnach** [comment] 2019-10-17 10:42
> [35m[Appium][39m Closing session, cause was 'Appium did not get any response from 'setValue' command in 60000 ms'

The error seems to be expected. I don't see the capabilities , but I assume that commandTimeouts is set and setValue call simply expires after one minute

**Comment by rahulcode** [comment] 2019-10-17 11:39
Hi @mykola-mokhnach 

You are correct that the capability	
`	                 capabilities.setCapability("clearSystemFiles", true);
			capabilities.setCapability("sendKeyStrategy", "grouped");
			capabilities.setCapability("maxTypingFrequency", 20);
			capabilities.setCapability("newCommandTimeout", 60000);
			capabilities.setCapability("commandTimeouts", "60000");
			capabilities.setCapability("includeSafariInWebviews", true);`
is set in capabilities.

But before the typing used to be fast for TextView( I am just entering 10-12 characters )
60 Seconds for 10-12 characters ( it takes 4-5 seconds for each character ) different from the way t enters text in TestFields.
Issue which I am trying to bring to notice is slow typing, wherein the session times out until the complete text is typed.

**Comment by mykola-mokhnach** [comment] 2019-10-17 11:53
`maxTypingFrequency` is the only setting we can control there. There is no other way to change the typing speed or any other parameters for xctest from Appium side.

**Comment by imurchie** [comment] 2019-10-17 17:19
Is the view customized at all? Any setting changed or anything? Our test app works fine in this regard, so it would be nice to be able to get the precise configuration to try to reproduce.

Here is the configuration we are using (code is here:  https://github.com/appium/ios-uicatalog/blob/master/UIKitCatalog/UIKitCatalog/TextViewController.swift#L159-L197):
```Swift
func configureTextView() {
    let bodyFontDescriptor = UIFontDescriptor.preferredFontDescriptor(withTextStyle: UIFont.TextStyle.body)
    let bodyFont = UIFont(descriptor: bodyFontDescriptor, size: 0)
            
    textView.font = bodyFont
    textView.backgroundColor = UIColor(named: "text_view_background")
     
    textView.isScrollEnabled = true

    // Apply different attributes to the text (bold, tinted, underline, etc.).
    reflowTextAttributes()
        
    // Insert symbols as image attachments.
    let text = textView.text! as NSString
    let attributedText = NSMutableAttributedString(attributedString: textView.attributedText!)
    let symbolsSearchRange = text.range(of: NSLocalizedString("symbols", comment: ""))
    var insertPoint = symbolsSearchRange.location + symbolsSearchRange.length
    attributedText.insert(symbolAttributedString(name: "heart"), at: insertPoint)
    insertPoint += 1
    attributedText.insert(symbolAttributedString(name: "heart.fill"), at: insertPoint)
    insertPoint += 1
    attributedText.insert(symbolAttributedString(name: "heart.slash"), at: insertPoint)
        
    // Add the image as an attachment.
    if let image = UIImage(named: "text_view_attachment") {
        let textAttachment = NSTextAttachment()
        textAttachment.image = image
        textAttachment.bounds = CGRect(origin: CGPoint.zero, size: image.size)
        let textAttachmentString = NSAttributedString(attachment: textAttachment)
        attributedText.append(textAttachmentString)
        textView.attributedText = attributedText
    }
        
    textView.usesStandardTextScaling = true
}
```

**Comment by mykola-mokhnach** [comment] 2019-10-24 06:20
Closed as duplicate of https://github.com/appium/appium/issues/13455

**Closed by mykola-mokhnach** 2019-10-24 06:20 UTC
Labels: ThirdParty, XCUITest
