### ISSUE TITLE
Error running bootstrap.sh for WebDriverAgent

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#14680] opened 2020-08-26 18:42 UTC
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OSX 10.15.6
* Node.js version (unless using Appium.app|exe): 12.14.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 14
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

Running into an error when Carthage is fetching dependencies for WDA

Snippet from Appium log showing all error info

```
[WebDriverAgent] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Installing/updating dependencies for platforms 'iOS', 'tvOS'
[debug] [WebDriverAgent] *** Checking out YYCache at "1.1.0"
[debug] [WebDriverAgent] *** Checking out CocoaAsyncSocket at "72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc"
[debug] [WebDriverAgent] *** xcodebuild output can be found in /var/folders/mn/gn6wr60s65dfqnvd6ccgzdlh0000gn/T/carthage-xcodebuild.rqaCsm.log
[debug] [WebDriverAgent] *** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
[debug] [WebDriverAgent] Build Failed
[debug] [WebDriverAgent] 	Task failed with exit code 1:
[debug] [WebDriverAgent] 	/usr/bin/xcrun lipo -create /Users/jamesvanhorn/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/iOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaAsyncSocket.framework/CocoaAsyncSocket /Users/jamesvanhorn/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-iphonesimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket -output /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/iOS/CocoaAsyncSocket.framework/CocoaAsyncSocket
[debug] [WebDriverAgent] This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/mn/gn6wr60s65dfqnvd6ccgzdlh0000gn/T/carthage-xcodebuild.rqaCsm.log
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1598466941504 (14:35:41 GMT-0400 (Eastern Daylight Time))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'carthage bootstrap --platform iOS\,tvOS' exited with code 1
```

## Link to Appium logs

xcodebuild log as directed
[carthage-xcodebuild.CXrkCS.log](https://github.com/appium/appium/files/5131656/carthage-xcodebuild.CXrkCS.log]

**Comment by jamesvanhorn** [comment] 2020-08-26 18:43
Note, this happens whether Appium tries to run bootstrap.sh or I try to run it manually

**Comment by mykola-mokhnach** [comment] 2020-08-26 18:43
Duplicate of https://github.com/appium/appium/issues/14611

**Closed by mykola-mokhnach** 2020-08-26 18:43 UTC
