### ISSUE TITLE
"scroll to" method is not working 

### ISSUE THREAD

**Issue by prathimak** [appium/appium#4989] opened 2015-04-22 14:49 UTC
Hi ,  

When i try to use "scroll to" method received below error
Could not parse UiSelector argument: problem using reflection to call this method (Selenium::WebDriver::Error::UnknownCommandError)
    in `button_displayed_with_scroll' 

 def button_displayed_with_scroll buttonText
    if exists { button(buttonText) } == false
      scroll_to buttonText
    end
    exists { button(buttonText) }
  end

Thanks

**Comment by moizjv** [comment] 2015-04-22 15:50
duplicate of #4311. Should be fixed with 1.4 release.

**Closed by moizjv** 2015-04-22 15:50 UTC
