### ISSUE TITLE
Cannot build WebDriverAgentRunner

### ISSUE THREAD

**Issue by markhsbc** [appium/appium#17583] opened 2022-10-07 22:52 UTC
Trying to build the WebDriverAgent project using the Full manual configuration.  system configuration:
MacOS: Version 12.5.1 (Monterey)
XCode Version: 13.4.1 (13F100)
Appium Server GUI: v1.22.3. (Appium-webdriveragent project under this directory)

I setup the proper signing & capabilities for the WebDriverAgentLib and WebDriverAgentRunner targets as instructed in the thread.  I executed the command line build call:
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -allowProvisioningUpdates -destination 'id=<id>’ test

I get the following error:

Testing failed:
	There are no accounts registered with Xcode. Add your developer account to Xcode
	No profiles for 'com.saddleback.healthychurchapp.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.saddleback.healthychurchapp.xctrunner'.
	Testing cancelled because the build failed.

My account is added to Xcode.

**Comment by KazuCocoa** [comment] 2022-10-08 02:46
So, you succeeded the build with Xcode, but did not with xcodebuild?

It seems like something xcodebuild internal stuff...  Did you reboot the host machine once?

**Comment by Immanuel-Codoid** [comment] 2022-10-08 05:07
Hi @KazuCocoa I'm trying to build wda on my iPhone 13 which runs 
iOS - 16.0.2
Xcode - 14.0
macOS - monterey 12.6
Appium - 2.0.0-beta.44 
```
mac@macs-MacBook-Pro ~ % appium --version 
info Appium Setting NODE_PATH to '/usr/local/lib/node_modules'
2.0.0-beta.44
```

**Steps to reproduce:**
1. Build integration app - successfully build and installed in the iPhone and launched
2. Build WebDriverAgent - Build successful but app is not installed in the iPhone

What combination of version is best to solve the issue, or am I making any mistake here?
Help is much appreciated

**Comment by KazuCocoa** [comment] 2022-10-08 16:46
> Build WebDriverAgent - Build successful but app is not installed in the iPhone

So, this installation was failed via Xcode? Could you share your appium log with `appium:showXcodeLog`?

**Comment by Immanuel-Codoid** [comment] 2022-10-09 05:58
HI @KazuCocoa I was able to sort the issue out, there were some compatibility issue with my xcode version and the webdriveragent that I tried to build, so I downgraded my xcode version to 13, and it worked fine. Thanks for the response.

**Comment by maxckelly** [comment] 2022-10-09 22:41
Has anyone found a solution for this other than downgrading?

**Comment by KazuCocoa** [comment] 2022-10-10 17:34
Could you share your log with showXcodeLog as GIST to see the output?

**Comment by markhsbc** [comment] 2022-10-10 19:21
Hi @KazuCocoa, no the build fails.  Therefore, nothing gets installed on the iOS real device.  BTW, my real device has version 15.6 on it.  However, when I build the WebDrivverAgent project under the Xcode GUI it installs the IntegrationApp on the Device.  Here is the entire build log from the terminal window:2022-10-07 11:44:32.808 xcodebuild[4184:224254] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-10-07 11:44:32.808 xcodebuild[4184:224254] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -allowProvisioningUpdates -destination id=a50309a6b7dcc2a5a049d551681ed333c9f0c038 test

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

note: Using new build system
note: Planning
Analyze workspace

Create build description
Build description signature: e89c7353005c3bd6793feb2d22f18add
Build description path: /var/root/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou/Build/Intermediates.noindex/XCBuildData/e89c7353005c3bd6793feb2d22f18add-desc.xcbuild

note: Build preparation complete
note: Building targets in dependency order
error: There are no accounts registered with Xcode. Add your developer account to Xcode (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
error: No profiles for 'com.saddleback.healthychurchapp.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.saddleback.healthychurchapp.xctrunner'. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')

Test session results, code coverage, and logs:
	/var/root/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou/Logs/Test/Test-WebDriverAgentRunner-2022.10.07_11-44-34--0700.xcresult

Testing failed:
	There are no accounts registered with Xcode. Add your developer account to Xcode
	No profiles for 'com.saddleback.healthychurchapp.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.saddleback.healthychurchapp.xctrunner'.
	Testing cancelled because the build failed.

** TEST FAILED **

markhamilton@Marks-MacBook-Air appium-webdriveragent %

**Comment by KazuCocoa** [comment] 2022-10-11 05:20
The error said the xcodebuild could not find a proper provisioning profile, or failed to resolve it.

> when I build the WebDrivverAgent project under the Xcode GUI it installs the IntegrationApp on the Device

Did you configure the same project with auto sign? Then, the xcodebuild may work without giving appium capabilities for building the app since the WebDriverAgent.xcodeproj may keep the config.

**Comment by maxckelly** [comment] 2022-10-11 11:42
I updated to Appium 2 using `npm i -g appium@next` it's not the best solution but it has fixed the issue for me.

**Comment by mykola-mokhnach** [comment] 2022-10-13 06:24
Closed as not an issue

**Closed by mykola-mokhnach** 2022-10-13 06:24 UTC
Labels: NotABug, NeedsInfo
