### ISSUE TITLE
XCUIElementTypeAlert not being detected from v6 upwards

### ISSUE THREAD

**Issue by gusoard** [appium/appium#19821] opened 2024-02-22 16:34 UTC
### Do I have the most recent component updates?

- [ ] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently I have a test that starts the application and checks if the Notifications permission is displayed. I'm not interest in autoaccepting it, since is part of the test to check if the actual permission is asked

I've been using WDA 5.14.0 until last week and update it to 6.0.2... Everything worked like a charm, except the check of the "XCUIElementTypeAlert" element is not recognised, even though is displayed on the screen

I've checked with Appium Inspector (to avoid something in my code) and it does not appear in the source XML...

I've checked this [issue](https://github.com/appium/appium/issues/19814), but I'm not sure if related, since that one is originally about timings

Here is in 5.14.0. The Source XML not only contains more elements, but also the XCUIElementTypeAlert is displayed
<img width="746" alt="source_xml_wda_5_14_0" src="https://github.com/appium/appium/assets/5107662/be395e95-2ab8-4f4c-9490-ee35eb78eb0f">

Here is in 6.0.2. The Source XML not only contains way less elements, but the Alert element is not present
<img width="878" alt="source_xml_wda_6_0_2" src="https://github.com/appium/appium/assets/5107662/4ea4cb83-b3e7-4ae3-9942-40ecdf7b0a98">

I'm working with 3 different apps that display this kind of alerts, and is the same in all scenarios

### Expected Behavior

XCUIElementTypeAlert displayed on the source XML

### Minimal Reproducible Example

Appium version 2.4.1

❌ WDA version 6.0.2
✅  WDA version 5.14.0

Open an application that display a XCUIElementTypeAlert element (i.e. notifications permissions)

### Environment

- Operating system: MacOS
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s): 6.0.2
- Appium plugin(s) and their version(s): None
- Node.js version (output of `node --version`): v21.5.0
- `npm` version (output of `npm --version`): 10.2.4
- Last component(s) version which did _not_ exhibit the problem: 5.14.0
- Platform and version under test: iOS 16.3
- Real device or emulator/simulator: Real Device

**Comment by mykola-mokhnach** [comment] 2024-02-22 16:43
Duplicate of https://github.com/appium/appium/issues/19786

**Closed by mykola-mokhnach** 2024-02-22 16:43 UTC
Labels: Bug, Needs Triage
