### ISSUE TITLE
Error in startServer(io.appium.uiautomator2.server.test.AppiumUiAutomator2Server)

### ISSUE THREAD

**Issue by WilliamCKTang** [appium/appium#14763] opened 2020-09-25 09:37 UTC
## The problem
Android mobile app not launched whenever I ran my test from Visual Studio 2017. From the physical device, I can see the script installed the app but never launches it. In appium log I can see there is a Network error and then there is failure to start uiautomator2 server.

## Environment
Windows 10 (1809)
Appium 1.18.2
Node 10.16.3
JDK 1.8.0_261
Android SDK
Installed packages:=====================] 100% Computing updates...
  Path                 | Version | Description                       | Location
  -------              | ------- | -------                           | -------
  build-tools;28.0.3   | 28.0.3  | Android SDK Build-Tools 28.0.3    | build-tools\28.0.3\
  emulator             | 28.0.25 | Android Emulator                  | emulator\
  patcher;v4           | 1       | SDK Patch Applier v4              | patcher\v4\
  platform-tools       | 30.0.4  | Android SDK Platform-Tools 30.0.4 | platform-tools\
  platforms;android-26 | 2       | Android SDK Platform 26           | platforms\android-26\
  
Real device (samsung - Galaxy S8, Android 9) connected via Mobile Labs deviceBridge

Command to launch appium:
appium --port 4724 --udid ce0417144bd734ff0c --session-override --log-timestamp --local-timezone --log C:\Tools\selenium\ce0417144bd734ff0c\logs\appium.log --suppress-adb-kill-server

## Details
Key errors spotted in the log file:
2020-09-25 19:15:25:426 [Instrumentation] Error in startServer(io.appium.uiautomator2.server.test.AppiumUiAutomator2Server):
2020-09-25 19:15:25:427 [Instrumentation] java.lang.ExceptionInInitializerError
2020-09-25 19:15:25:453 [Instrumentation] Caused by: java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@108f3c8already registered!

2020-09-25 19:17:53:832 [WD Proxy] Got response with status 503: <HTML><HEAD>
2020-09-25 19:17:53:833 [WD Proxy] <TITLE>Network Error</TITLE>

2020-09-25 19:17:53:863 [UiAutomator2] The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.

## Link to Appium logs
https://github.com/WilliamCKTang/appium_issue/blob/master/appium_issue.txt

## Code To Reproduce Issue [ Good To Have ]
public void PingIDMobileTest()
{
	var options = new AppiumOptions();
	int MaxTimeout = 120000;
	int maxWait = 20000;
	options.AddAdditionalCapability(MobileCapabilityType.Udid, "ce0417144bd734ff0c");
	options.AddAdditionalCapability(MobileCapabilityType.AutomationName, "UiAutomator2");
	options.AddAdditionalCapability(MobileCapabilityType.NewCommandTimeout, MaxTimeout);
	options.AddAdditionalCapability("app", "C://Projects//SGE//PingID.apk");
	options.AddAdditionalCapability("fullReset", true);
	options.AddAdditionalCapability("noReset", false);
	options.AddAdditionalCapability("clearSystemFiles", true);

	options.AddAdditionalCapability("adbExecTimeout", MaxTimeout);
	options.AddAdditionalCapability("uiautomator2ServerInstallTimeout", MaxTimeout);
	options.AddAdditionalCapability("appWaitForLaunch", true);
	options.AddAdditionalCapability("skipServerInstallation", false);
	options.AddAdditionalCapability("uiautomator2ServerLaunchTimeout", MaxTimeout);
	options.AddAdditionalCapability("androidUninstallTimeout", MaxTimeout);
	options.AddAdditionalCapability("androidInstallTimeout", MaxTimeout);
	options.AddAdditionalCapability(MobileCapabilityType.PlatformName, "ANDROID");
	options.AddAdditionalCapability("appActivity", "com.accells.access.AppMgr");
	AndroidDriver<AndroidElement> appiumDriver = new AndroidDriver<AndroidElement>(new Uri("http://localhost:4724/wd/hub"), options, TimeSpan.FromSeconds(180));
	WebDriverWait appiumDriverWait = new WebDriverWait(appiumDriver, TimeSpan.FromSeconds(Convert.ToInt16(180)));
	Thread.Sleep(5000);
	AndroidElement termacceptBtn = (AndroidElement)appiumDriver.FindElementById("prod.com.pingidentity.pingid:id/terms_accept");
	appiumDriverWait.Until(ExpectedConditions.ElementToBeClickable(termacceptBtn));
	termacceptBtn.Click();
	appiumDriver.Quit();
}

**Comment by mykola-mokhnach** [comment] 2020-09-25 09:46
Duplicate of https://github.com/appium/appium/issues/10862

**Closed by mykola-mokhnach** 2020-09-25 09:46 UTC
