### ISSUE TITLE
stuck in self.driver.page_source and then throw exception 10min later

### ISSUE THREAD

**Issue by s-xq** [appium/appium#9343] opened 2017-09-30 08:53 UTC
## The problem

When i was use `self.driver.page_source`to get the page source , this just stuck and never return until an exception occur (see it in the end of this log file).
[appium_20170930160111_self.driver.page_source.txt](https://github.com/appium/appium/files/1346276/appium_20170930160111_self.driver.page_source.txt)
 This problem happened quite a lot in these few days . Please tell me how can i solve this problem.
Thank you !

## Environment
* Appium version (or git revision) that exhibits the issue:Appium v1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:OS X EI Capitan 10.11.6
* Node.js version (unless using Appium.app|exe):v7.10.0
* Mobile platform/version under test:Android7.0
* Real device or emulator/simulator:real device,nexus
* Appium CLI or Appium.app|exe:Appium CLI

## Details
Python verison : 2.7.10

## Link to Appium logs
This is comlete appium logs.

```
2017-09-30 15:50:12:244 - [HTTP] <-- GET /wd/hub/session/392fe7ca-0b96-4f0d-b9c5-20f9f57ecdb1/screenshot 200 5170 ms - 296506 
2017-09-30 15:50:15:305 - [HTTP] --> GET /wd/hub/session/392fe7ca-0b96-4f0d-b9c5-20f9f57ecdb1/source {}
2017-09-30 15:50:15:305 - [debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["392fe7ca-0b96-4f0d-b9c5-20f9f57ecdb1"]
2017-09-30 15:50:15:306 - [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"source","params":{}}
2017-09-30 15:50:15:311 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"source","params":{}}
2017-09-30 15:50:15:311 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
2017-09-30 15:50:15:311 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: source
2017-09-30 15:50:23:521 - [HTTP] --> GET /wd/hub/session/392fe7ca-0b96-4f0d-b9c5-20f9f57ecdb1/screenshot {}
2017-09-30 15:50:23:521 - [debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["392fe7ca-0b96-4f0d-b9c5-20f9f57ecdb1"]
2017-09-30 16:00:15:292 - [HTTP] <-- GET /wd/hub/session/392fe7ca-0b96-4f0d-b9c5-20f9f57ecdb1/source - - ms - - 
2017-09-30 16:00:23:547 - [HTTP] <-- GET /wd/hub/session/392fe7ca-0b96-4f0d-b9c5-20f9f57ecdb1/screenshot - - ms - - 
2017-09-30 16:01:11:680 - [debug] [UiAutomator] Moving to state 'stopped'
2017-09-30 16:01:11:691 - [debug] [AndroidDriver] Shutting down Android driver
2017-09-30 16:01:11:694 - [Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
2017-09-30 16:01:11:694 - [Appium] Removing session 392fe7ca-0b96-4f0d-b9c5-20f9f57ecdb1 from our master session list
2017-09-30 16:01:11:698 - [debug] [AndroidDriver] Resetting IME to io.appium.android.ime/.UnicodeIME
2017-09-30 16:01:11:699 - [debug] [ADB] Getting connected devices...
2017-09-30 16:01:14:863 - [debug] [ADB] 1 device(s) connected
2017-09-30 16:01:14:866 - [debug] [ADB] Running '/Users/sxq/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","84B7N15C11003162","shell","ime","set","io.appium.android.ime/.UnicodeIME"]
2017-09-30 16:01:15:572 - [debug] [ADB] Getting connected devices...
2017-09-30 16:01:15:594 - [debug] [ADB] 1 device(s) connected
2017-09-30 16:01:15:595 - [debug] [ADB] Running '/Users/sxq/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","84B7N15C11003162","shell","am","force-stop","com.sxq.demo"]
2017-09-30 16:01:16:340 - [debug] [ADB] Pressing the HOME button
2017-09-30 16:01:16:341 - [debug] [ADB] Getting connected devices...
2017-09-30 16:01:16:366 - [debug] [ADB] 1 device(s) connected
2017-09-30 16:01:16:367 - [debug] [ADB] Running '/Users/sxq/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","84B7N15C11003162","shell","input","keyevent",3]
2017-09-30 16:01:16:989 - [AndroidBootstrap] Cannot shut down Android bootstrap; it has already shut down
2017-09-30 16:01:16:993 - [debug] [Logcat] Stopping logcat capture
2017-09-30 16:01:16:994 - [debug] [Logcat] Logcat already stopped
2017-09-30 16:01:16:995 - [debug] [ADB] Getting connected devices...
2017-09-30 16:01:17:022 - [debug] [ADB] 1 device(s) connected
2017-09-30 16:01:17:023 - [debug] [ADB] Running '/Users/sxq/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","84B7N15C11003162","shell","am","force-stop","io.appium.unlock"]
2017-09-30 16:01:17:628 - [debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.

```

## Code To Reproduce Issue [ Good To Have ]
```
cmd = "appium --log-level debug:error --log-timestamp --local-timezone --session-override -p %d -bp %d >> ./log/appium4.log" % (4729, 4730)
  self.appium_server_t = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
```
```
self.driver = webdriver.Remote('http://localhost:4729/wd/hub', desired_caps)
```
```
tmp_source = self.driver.page_source
```

**Comment by mykola-mokhnach** [comment] 2017-09-30 09:58
Closed as duplicate of https://github.com/appium/appium/issues/9342 (the reason for both issues is most likely the same)

**Closed by mykola-mokhnach** 2017-09-30 09:58 UTC
