### ISSUE TITLE
Original error: Error: socket hang up with IntelliJ running tests on Android device

### ISSUE THREAD

**Issue by samm52** [appium/appium#13807] opened 2020-01-07 18:45 UTC
## The problem
Goal is to run multiple groovy test files within a folder. I ran the four tests once, successfully. I ran them by selecting the tests and running.
The second time, the first two tests passed successfully. I ran the folder this time. During the third test, I got the following error:

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up (WARNING: The server did not provide any stacktrace information)

The test continued running after this, and test four was able to start and passed. Tests are being run on a real device and not in parallel.

## Environment

* Appium version: 1.14.0-beta.1
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 12.13.1
* Npm: 6.12.1
* Mobile platform/version under test: Android 9

## Link to Appium logs

Here is a [GIST of IntelliJ IDEA logs](https://gist.github.com/samm52/b5b1e0f200cbd965515a1d4aef992cc2)

Here is a [GIST of Appium logs](https://gist.github.com/samm52/b5404d7d64998ea4f55e290b5ecb6bd4)

## Code To Reproduce Issue [ Good To Have ]
In the groovy file, the lines that caused the error included:

```
expect: "text"
methodName()

def methodName() {
   ArrayList<WebElement> data = driver.findElements(By.id("com.companyName.companyAppName:id/program_data_text_view"))

        totalScore = 0
        bestScore = 0
        numScores = data.size()

        for(int i=0; i < data.size(); i++){
            int curFloat = Integer.parseInt(data.get(i).getAttribute('text').trim())
            totalScore += curFloat

            if(curFloat > bestScore)
                bestScore = curFloat
        }
        avgScore = (Double)totalScore/(Double)(data.size())
}
```

**Comment by mykola-mokhnach** [comment] 2020-01-09 15:51
`socket hang up` usually means that the server running on the device stopped responding to client requests. There might be multiple reasons to this like issues with the device itself, adb issues, network issues, bugs in the server itself. The device logcat output for the period when disconnect happens might sometimes contain some useful information.

I've seen similar issues before and the cause was the Doze mode on the device, which was silently killing appium server in the background. The [solution](https://github.com/appium/appium-uiautomator2-server/issues/310) was to add the server to the list of whitelisted apps.

**Comment by mykola-mokhnach** [comment] 2020-01-14 07:05
Closed as third party issue

**Closed by mykola-mokhnach** 2020-01-14 07:05 UTC
Labels: NeedsInfo, ThirdParty, UIAutomator2

**Comment by samm52** [comment] 2020-01-14 14:08
@mykola-mokhnach Appium works a solid 90% of the time for my team. However, when this socket hang up occurs, restarting Appium is what fixes the issue. I was running a different setup of tests yesterday and after running 10-20 tests, one randomly had this error. I didn't take the logs but the device was fine, adb was over Wi-Fi, and Appium hadn't been restarted in a while.

**Comment by mykola-mokhnach** [comment] 2020-01-14 14:11
Unfortunately the attached logs contain no useful information about the actual issue

**Comment by samm52** [comment] 2020-01-14 14:26
@mykola-mokhnach What information should be searched for in Appium, Intellij IDEA, or device logs, for this issue?

**Comment by mykola-mokhnach** [comment] 2020-01-14 19:58
Most likely the device logs, but like I said above, it can be anything

**Comment by vpkhachane** [comment] 2020-04-09 09:13
@mykola-mokhnach  I am also getting the same error. I am using the Appium 1.17 version. Please help me I am stuck in it.

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Erro
r: socket hang up
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-9RLF69M', ip: '192.168.184.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: com.namutek.kash.MainActivity, appPackage: com.namutek.kash, autoGrantPermissions: true, automationName: appium, databaseEnabled: false, desired: {appActivity:
 com.namutek.kash.MainActivity, appPackage: com.namutek.kash, autoGrantPermissions: true, automationName: appium, deviceName: emulator, fastReset: true, platformName: android, platformVe
rsion: 9, resetKeyboard: true, unicodeKeyboard: true}, deviceApiLevel: 28, deviceManufacturer: Google, deviceModel: AOSP on IA Emulator, deviceName: emulator-5554, deviceScreenDensity: 4
20, deviceScreenSize: 1080x1920, deviceUDID: emulator-5554, fastReset: true, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2.625, pl
atform: LINUX, platformName: Android, platformVersion: 9, resetKeyboard: true, statBarHeight: 63, takesScreenshot: true, unicodeKeyboard: true, viewportRect: {height: 1731, left: 0, top:
 63, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: d040ca74-e3d6-4835-98d6-5691b75714a9
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
        at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
        at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
        at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:39)
        at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:56)
        at io.appium.java_client.HasSessionDetails.getPlatformName(HasSessionDetails.java:65)
        at io.appium.java_client.pagefactory.AppiumFieldDecorator.<init>(AppiumFieldDecorator.java:96)
        at io.appium.java_client.pagefactory.AppiumFieldDecorator.<init>(AppiumFieldDecorator.java:144)
        at Pages.LoginScreen.<init>(LoginScreen.java:53)
        at StepDefination.DebitCardstepDefination.iShouldBeOnHomescreen(DebitCardstepDefination.java:48)
        at ?.And User should be on Homescreen(src/test/java/Feature/TC_002_DebitCard.feature:11)

FAILED: feature(Add_New_Debit_Card)
        Runs Cucumber Feature
cucumber.runtime.CucumberException: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to
 remote server. Original error: Error: socket hang up
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-9RLF69M', ip: '192.168.184.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: com.namutek.kash.MainActivity, appPackage: com.namutek.kash, autoGrantPermissions: true, automationName: appium, databaseEnabled: false, desired: {appActivity:
 com.namutek.kash.MainActivity, appPackage: com.namutek.kash, autoGrantPermissions: true, automationName: appium, deviceName: emulator, fastReset: true, platformName: android, platformVe
rsion: 9, resetKeyboard: true, unicodeKeyboard: true}, deviceApiLevel: 28, deviceManufacturer: Google, deviceModel: AOSP on IA Emulator, deviceName: emulator-5554, deviceScreenDensity: 4
20, deviceScreenSize: 1080x1920, deviceUDID: emulator-5554, fastReset: true, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2.625, pl
atform: LINUX, platformName: Android, platformVersion: 9, resetKeyboard: true, statBarHeight: 63, takesScreenshot: true, unicodeKeyboard: true, viewportRect: {height: 1731, left: 0, top:
 63, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: d040ca74-e3d6-4835-98d6-5691b75714a9
        at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
        at Myrunner.TestRunnerTestNG.feature(TestRunnerTestNG.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:648)
        at org.testng.TestRunner.run(TestRunner.java:505)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
        at org.testng.SuiteRunner.run(SuiteRunner.java:364)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
        at org.testng.TestNG.runSuites(TestNG.java:1049)
        at org.testng.TestNG.run(TestNG.java:1017)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original
error: Error: socket hang up
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-9RLF69M', ip: '192.168.184.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: com.namutek.kash.MainActivity, appPackage: com.namutek.kash, autoGrantPermissions: true, automationName: appium, databaseEnabled: false, desired: {appActivity:
 com.namutek.kash.MainActivity, appPackage: com.namutek.kash, autoGrantPermissions: true, automationName: appium, deviceName: emulator, fastReset: true, platformName: android, platformVe
rsion: 9, resetKeyboard: true, unicodeKeyboard: true}, deviceApiLevel: 28, deviceManufacturer: Google, deviceModel: AOSP on IA Emulator, deviceName: emulator-5554, deviceScreenDensity: 4
20, deviceScreenSize: 1080x1920, deviceUDID: emulator-5554, fastReset: true, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2.625, pl
atform: LINUX, platformName: Android, platformVersion: 9, resetKeyboard: true, statBarHeight: 63, takesScreenshot: true, unicodeKeyboard: true, viewportRect: {height: 1731, left: 0, top:
 63, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: d040ca74-e3d6-4835-98d6-5691b75714a9
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
        at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
        at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
        at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:39)
        at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:56)
        at io.appium.java_client.HasSessionDetails.getPlatformName(HasSessionDetails.java:65)
        at io.appium.java_client.pagefactory.AppiumFieldDecorator.<init>(AppiumFieldDecorator.java:96)
        at io.appium.java_client.pagefactory.AppiumFieldDecorator.<init>(AppiumFieldDecorator.java:144)
        at Pages.LoginScreen.<init>(LoginScreen.java:53)
        at StepDefination.DebitCardstepDefination.iShouldBeOnHomescreen(DebitCardstepDefination.java:48)
        at ?.And User should be on Homescreen(src/test/java/Feature/TC_002_DebitCard.feature:11)


===============================================
    D:/Coinca/CoincaAutomation/BitBucketCode/kash_automated_testing
    Tests run: 1, Failures: 1, Skips: 0
===============================================

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 245.979 s <<< FAILURE! - in TestSuite
[ERROR] feature(Myrunner.TestRunnerTestNG)  Time elapsed: 241.67 s  <<< FAILURE!
cucumber.runtime.CucumberException:
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Erro
r: socket hang up
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-9RLF69M', ip: '192.168.184.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: com.namutek.kash.MainActivity, appPackage: com.namutek.kash, autoGrantPermissions: true, automationName: appium, databaseEnabled: false, desired: {appActivity:
 com.namutek.kash.MainActivity, appPackage: com.namutek.kash, autoGrantPermissions: true, automationName: appium, deviceName: emulator, fastReset: true, platformName: android, platformVe
rsion: 9, resetKeyboard: true, unicodeKeyboard: true}, deviceApiLevel: 28, deviceManufacturer: Google, deviceModel: AOSP on IA Emulator, deviceName: emulator-5554, deviceScreenDensity: 4
20, deviceScreenSize: 1080x1920, deviceUDID: emulator-5554, fastReset: true, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2.625, pl
atform: LINUX, platformName: Android, platformVersion: 9, resetKeyboard: true, statBarHeight: 63, takesScreenshot: true, unicodeKeyboard: true, viewportRect: {height: 1731, left: 0, top:
 63, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: d040ca74-e3d6-4835-98d6-5691b75714a9
        at Myrunner.TestRunnerTestNG.feature(TestRunnerTestNG.java:50)
Caused by: org.openqa.selenium.WebDriverException:
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-9RLF69M', ip: '192.168.184.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: com.namutek.kash.MainActivity, appPackage: com.namutek.kash, autoGrantPermissions: true, automationName: appium, databaseEnabled: false, desired: {appActivity:
 com.namutek.kash.MainActivity, appPackage: com.namutek.kash, autoGrantPermissions: true, automationName: appium, deviceName: emulator, fastReset: true, platformName: android, platformVe
rsion: 9, resetKeyboard: true, unicodeKeyboard: true}, deviceApiLevel: 28, deviceManufacturer: Google, deviceModel: AOSP on IA Emulator, deviceName: emulator-5554, deviceScreenDensity: 4
20, deviceScreenSize: 1080x1920, deviceUDID: emulator-5554, fastReset: true, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2.625, pl
atform: LINUX, platformName: Android, platformVersion: 9, resetKeyboard: true, statBarHeight: 63, takesScreenshot: true, unicodeKeyboard: true, viewportRect: {height: 1731, left: 0, top:
 63, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: d040ca74-e3d6-4835-98d6-5691b75714a9

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures: 
[ERROR]   TestRunnerTestNG.feature:50 » Cucumber org.openqa.selenium.WebDriverException:...
[INFO]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[ERROR] There are test failures.

Please refer to D:\Coinca\CoincaAutomation\BitBucketCode\kash_automated_testing\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ Coinca ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: D:\Coinca\CoincaAutomation\BitBucketCode\kash_automated_testing\target\Coinca-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-cucumber-reporting:3.13.0:generate (execution) @ Coinca ---
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogg
er.level' to TRACE to show Log4j2 internal initialization logging.
[INFO] About to generate Cucumber report.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:19 min
[INFO] Finished at: 2020-04-09T14:39:03+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.masterthought:maven-cucumber-reporting:3.13.0:generate (execution) on project Coinca: Error Found:: BUILD FAILED - Check Report For Details -> [Help 1]

[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by QaAut** [comment] 2020-04-15 15:00
@vpkhachane Have the same error. I'm using Appium with Serenity BDD framework. Please tell me if you find a bulletproof solution for it

**Comment by clarabez** [comment] 2021-03-27 01:37
facing the same using Appium Desktop itself, event to start a new session this error is happening. It was working fine few days ago, we will keep investigating it.
