### ISSUE TITLE
Unable to find visible elements

### ISSUE THREAD

**Issue by ale07** [appium/appium#12098] opened 2019-01-30 11:54 UTC
Hi,

system characteristics:

**iPhone 6s
iOS 10.2
Appium Desktop 1.10.0
Xcode 10.1
MacOS High Sierra 10.13.6

iPhone 7
iOS 12.2
Appium Desktop 1.10.0
Xcode 10.1
MacOS High Sierra 10.13.6**

In a specific section of the application under test, I tried to find all 'XCUIElementTypeStaticText' visible, but only one element was returned (in the pictures at the bottom). 

When I tried to run the following query by **iPhone 6s**:

- **Predicate iOS: type == 'XCUIElementTypeStaticText' and visible == 1**

![screenshot at jan 30 11-53-31](https://user-images.githubusercontent.com/28478760/51977472-d983f700-2487-11e9-87aa-a94c8e7a1b0e.png)

![screenshot at jan 30 11-55-58](https://user-images.githubusercontent.com/28478760/51977477-e0ab0500-2487-11e9-80ba-05ca4933ab17.png)

- **Class Chain: **/XCUIElementTypeStaticText[`visible == 1`]**

![screenshot at jan 30 11-57-53](https://user-images.githubusercontent.com/28478760/51977490-e7d21300-2487-11e9-9516-4039ab326711.png)

![screenshot at jan 30 11-58-14](https://user-images.githubusercontent.com/28478760/51977496-ea346d00-2487-11e9-9ff4-8f33dfa3f6f1.png)

- **Xpath: //XCUIElementTypeStaticText[@visible = 'true']**

![screenshot at jan 30 11-59-03](https://user-images.githubusercontent.com/28478760/51977498-ee608a80-2487-11e9-9b21-5b681c56fa8c.png)

![screenshot at jan 30 12-00-45](https://user-images.githubusercontent.com/28478760/51977506-f3bdd500-2487-11e9-9c1f-23aa6be3f2c2.png)

As you can see for Xpath the elements retrieved are correct.

When I tried to run the following query by **iPhone 7**:

- **Predicate iOS: type == 'XCUIElementTypeStaticText' and visible == 1**

![screenshot at jan 30 12-23-25](https://user-images.githubusercontent.com/28478760/51978736-4f3d9200-248b-11e9-8a63-6311825cd8e0.png)

![screenshot at jan 30 12-23-45](https://user-images.githubusercontent.com/28478760/51978784-7300d800-248b-11e9-979a-e6c315db6698.png)

- **Class Chain: **/XCUIElementTypeStaticText[`visible == 1`]**

![screenshot at jan 30 12-24-53](https://user-images.githubusercontent.com/28478760/51978802-814ef400-248b-11e9-8e8e-27c093da79c8.png)

![screenshot at jan 30 12-25-07](https://user-images.githubusercontent.com/28478760/51978797-7e540380-248b-11e9-9d69-cce35aa451bd.png)

- **Xpath: //XCUIElementTypeStaticText[@visible = 'true']**

![screenshot at jan 30 12-36-19](https://user-images.githubusercontent.com/28478760/51978843-aba0b180-248b-11e9-9090-727326c5d69c.png)

![screenshot at jan 30 12-29-12](https://user-images.githubusercontent.com/28478760/51978813-8c098900-248b-11e9-9df8-1af56718e1f2.png)

Moreover, as you see in the picture at the bottom, the application's elements, although them are visible, have set up visible attribute to false on iPhone 7, instead with iPhone6 the attribute visible is true.

![screenshot at jan 30 11-43-27](https://user-images.githubusercontent.com/28478760/51976175-5319e600-2484-11e9-9368-831a8a37db95.png)

Finally, the find action is very slow also when is captured the screenshot and page source.

This is the link pointing to log file that include all action described: [appium.log](https://github.com/facebook/WebDriverAgent/files/2812343/appium.log)

**Comment by mykola-mokhnach** [comment] 2019-01-30 13:33
Closed as duplicate of https://github.com/appium/appium/issues/11507

Please report the issue to Apple

**Closed by mykola-mokhnach** 2019-01-30 13:33 UTC

**Comment by ale07** [comment] 2019-01-30 14:57
Thank you for your reply,

I read the topic #11507 but I don't know, in my case, because Appium version 1.8.1 retrieves the elements correctly with the same iOS version 10.2 by iPhone 6s.

In new Appium version 1.9.1 happened this issue although the system characteristics by iPhone 6s are the same.

How can this happen?

**Comment by mykola-mokhnach** [comment] 2019-01-30 15:03
At some point of time Appium started to use the visibility attribute provided by XCTest instead of the custom hacky logic. This is how it happened.

**Comment by ale07** [comment] 2019-01-30 15:20
Thank you for the clarification.

**Comment by mrk-han** [comment] 2019-11-18 18:02
@mykola-mokhnach Do you know if anyone reported this to Apple yet? Is the workaround for this using `simpleIsVisibleCheck`?

Is there a way to enable that in the appium desktop inspector too?
