### ISSUE TITLE
bug: GPS location flickers with set location command in appium 2.x.x.

### ISSUE THREAD

**Issue by rushi04** [appium/appium#19402] opened 2023-11-10 13:19 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

GPS location flickers with set location command with appium 2.x.x. Whereas the same is not observed with appium 1.21.0 or 1.22.0. 

- In [this](https://github.com/appium/appium/assets/35609501/07b12455-666e-4eaf-803d-1b0de6d5041b) screen recording it can be seen that post setting location to {"latitude":48.1709325,"longitude":16.3333336}} it keeps on flickering to original device location. 
- It seems that the issue is due to fused location not being set as the following log line is seen for 2.x.x in logcat  ` E MOCKED LOCATION SERVICE: Could not set location for 'fused'` 

### Expected Behavior

GPS location should remain steady.

### Minimal Reproducible Example

1. Start appium session with appium version greater than 2.0.0.
2. set gps location using set_location command. 
3. get gps location in loop using driver.location() Or use custom app to get gps location and we can see the flickering.

### Environment

- Operating system: Mac OS 
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s): uiautomator2 2.29.5
- Node.js version (output of `node --version`): 16
- Platform and version under test: Android os 13
- Real device or emulator/simulator: Real device

### Link to Appium Logs

https://gist.github.com/rushi04/36ea52fe91319960ad4c1ffbe4a2d14b

**Comment by Jayarams99** [comment] 2024-01-05 18:14
@mykola-mokhnach Can you please help on this ticket

**Comment by mykola-mokhnach** [comment] 2024-01-05 19:21
I don't know how I can help

**Comment by mykola-mokhnach** [comment] 2024-01-21 22:33
@KazuCocoa Might it be a duplicate of https://github.com/appium/appium/issues/19238?

**Comment by KazuCocoa** [comment] 2024-01-22 04:50
Possibly yes, I guess...

**Comment by mykola-mokhnach** [comment] 2024-01-23 10:47
@rushi04 Please try the latest driver version if the above issue is still reproducible there

**Comment by mykola-mokhnach** [comment] 2024-01-30 07:48
Closed because of no response

**Closed by mykola-mokhnach** 2024-01-30 07:48 UTC
Labels: Android, Needs Info
