### ISSUE TITLE
bug: Failed to create session, because Shell does not have permission to access user 10

### ISSUE THREAD

**Issue by Shakter666** [appium/appium#20366] opened 2024-07-11 10:11 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am getting such issue, while I am trying to connect with appium 2.11.1 (Ubuntu). The case is I have MDM on this Android device and there are two users: with id 0 and with id 10, and appium is trying to connect by default to user 10 which doesn't have permissions. Basically I think it is adb issue, but when I use adb command and select user 0 it is working like: adb shell -s <udid> -user 0 (...), but I can not find if appium 2 is supporting such parameters like selecting specific user. Changing device or removing MDM is not the solution and becasue corpo I can not grant any accesses on this user

`Failed to create session. An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/home/<username>/Android/Sdk/platform-tools/adb -P 5037 -s <udid> shell cmd package list packages' exited with code 255'; Command output: Exception occurred while executing 'list': java.lang.SecurityException: Shell does not have permission to access user 10 com.android.server.am.ActivityManagerService.handleIncomingUser:15970 android.app.ActivityManager.handleIncomingUser:5152 com.android.server.pm.PackageManagerShellCommand.translateUserId:3733 at com.android.server.am.UserController.handleIncomingUser(UserController.java:2892) at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:15970) at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:5152) at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3733) at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:1074) at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:960) at com.android.server.pm.PackageManagerShellCommand.runList(PackageManagerShellCommand.java:80`

### Expected Behavior

select android user while connection to device

### Minimal Reproducible Example

N/A

### Environment

- Operating system: Ubuntu 20
- Appium server version (output of `appium --version`): appium --version
- Appium driver(s) and their version(s) (`appium driver list`):  Listing available drivers
- uiautomator2@3.7.2 [installed (npm)]
- xcuitest@7.23.1 [installed (npm)]
- espresso [not installed]
- mac2 [not installed]
- windows [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]

- Appium plugin(s) and their version(s) (`appium plugin list`): ✔ Listing available plugins
- images [not installed]
- execute-driver [not installed]
- relaxed-caps [not installed]
- universal-xml [not installed]

- Node.js version (output of `node --version`): v20.12.2
- `npm` version (output of `npm --version`): 10.5.0
- Last component(s) version which did _not_ exhibit the problem: latest version
- Platform and version under test: Android 14
- Real device: Samsung S23

**Comment by mykola-mokhnach** [comment] 2024-07-11 10:17
Duplicate of https://github.com/appium/appium-uiautomator2-driver/issues/795

**Closed** 2024-07-17 09:25 UTC
Labels: Android, ThirdParty
