### ISSUE TITLE
Very slow to start interacting after the WDA Runner is installed

### ISSUE THREAD

**Issue by sasasa42** [appium/appium#11819] opened 2018-12-12 10:04 UTC
## The problem

When I run the automation script, after the WebDriverAgentRunner is installed, appium takes around one minute to start interacting with the app.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.0-beta.0
* Last Appium version that did not exhibit the issue (if applicable): 1.9.0
* Desktop OS/version used to run Appium: mac
* Node.js version (unless using Appium.app|exe): 8.11.1
* Mobile platform/version under test: iOS 12.1.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Earlier, when I was on Appium 1.9.0 and XCode 9.4.1 i did not face the issue. But after switching to XCode 10.1 and Appium 1.11.0, I started seeing there is so much of a delay in starting and interacting

## Link to Appium logs

https://gist.github.com/sasasa42/bd293b05af6c1de750c6bd6ebe746440

**Comment by mykola-mokhnach** [comment] 2018-12-12 11:32
I saw similar reports before and have no idea why this is happening. Most likely there's some problem inside XCTest/WebDriverAgent, but these all are just pure guesses. Perhaps someone could debug it with a failing application and point out where the problem is.

**Comment by Dan-Maor** [comment] 2018-12-12 14:02
Can you to set the shouldWaitForQuiescence capability to true?
Pretty sure it's the same issue as https://github.com/facebook/WebDriverAgent/issues/993

**Comment by Siddh010** [comment] 2018-12-14 06:34
I am also facing now same issue.

**Comment by Siddh010** [comment] 2018-12-17 07:03
After setting   "WaitForQuiescence" : true , it started working for me.

**Comment by Siddh010** [comment] 2018-12-17 11:21
Set shouldWaitForQuiescence = false and WaitForQuiescence = true/false was able to start session soon but facing  slowness  while selecting Date Picker components.

**Comment by sasasa42** [comment] 2018-12-17 15:37
> Set shouldWaitForQuiescence = false and WaitForQuiescence = true/false was able to start session soon but facing slowness while selecting Date Picker components.

This does not work for me. May be you can show the code snippet. But I strongly feel this would not work. I have tried all combinations.

**Comment by tfcardoso** [comment] 2018-12-17 17:16
With waitForQuiescence = false it waits for around 1 minute (real device iOS12/XCode10). Without this, it waits 5/6 minutes

**Comment by mykola-mokhnach** [comment] 2018-12-20 06:52
Closed as third party issue. Please report to https://github.com/facebook/WebDriverAgent/issues

**Closed by mykola-mokhnach** 2018-12-20 06:52 UTC
Labels: ThirdParty, XCUITest
