### ISSUE TITLE
IOS app elements doesn't appear in the app source hierarchy

### ISSUE THREAD

**Issue by kalyan7h** [appium/appium#14819] opened 2020-10-19 10:15 UTC
I've a mobile screen with some 100+ transaction rows. Some 10 are visible on the screen, user has to scroll down to see the rest.
When i inspect any element thru appium inspector, the controls don't appear in source hierarchy. [issue seen only on this screen]
Appium Version: v1.18.3 (same issue seen with appium version v1.17 too)
IOS simulator Version: 13.3

Capabilities
"platformName": "ios",
  "platformVersion": "13.3",
  "deviceName": "iPhone Simulator",
  "app": "/Users/kgrandhi/Downloads/appFile.zip",
  "noReset": true,
  "automationName": "XCUITest",
  "bundleId": "com.XXX.XXX"

The same issue doesn't appear with the below combination, but the inspector takes its own time to present the app hierarchy.
Appium Version:v1.15.1
IOS simulator Version: 11.2

My requirement is to run the scripts with the latest appium version and on IOS version 13.2 or more. How to solve the issue. Appreciate help. 

Attached log files with appium v1.18.3 where the issue is seen.
[appium-server-logs copy.txt](https://github.com/appium/appium/files/5401039/appium-server-logs.copy.txt)

**Comment by mykola-mokhnach** [comment] 2020-10-19 10:48
Duplicate of https://github.com/appium/appium/issues/13958

Unfortunately we are not under control of which elements to show in the page source. It is up to XCTest and the system accessibility framework. Consider also checking https://github.com/appium/appium/issues/6517

**Closed by mykola-mokhnach** 2020-10-19 10:48 UTC

**Comment by kalyan7h** [comment] 2020-10-19 13:50
If it were an APPLE issue, then I should be seeing the same with appium version 1.15 too, but that is not the case.

**Comment by mykola-mokhnach** [comment] 2020-10-19 13:57
There are too many changes between different iOS SDKs. also these are complete black boxes without a source code. This means it is nearly impossible to figure out what exactly was changed under the hood, where and why.

**Comment by kalyan7h** [comment] 2020-10-19 14:22
ok, how to handle it, do you have any workaround. One observation this mainly happens if the screen has many record rows(50+), if i limit my rows to some 15 to 20, mostly it works.

**Comment by mykola-mokhnach** [comment] 2020-10-19 14:44
I'd try to play with the source command as described in https://github.com/appium/appium/issues/13595

**Comment by kalyan7h** [comment] 2020-10-20 09:02
One observation, Appium Version 1.15 works well on my IOS simulator version 13.3. But Appium Version 1.17 or 1.18 on IOS version 13.3 see the issue in fetching the elements into appium inspector.
