### ISSUE TITLE
Question about clear Safari Cookies for mobile web Real Device, using deleteAllCookies() or deleteCookies() is not working on iPhone Safari Browser.

### ISSUE THREAD

**Issue by nageshc** [appium/appium#11126] opened 2018-07-30 10:27 UTC
## The problem

I have used deleteAllCookies or deleteCookie (Java + appium 1.8.0) to delete the cookies but these methods are not working on Safari iPhone 6s Real device. I want to start new clean session after i open the website in safari on iOS 10.1.1 (iPhone 6s real device),through appium-xcuitest-driver.

However if I run test about 'user login', so the users' cookies will always been there for other following scenarios, so I'd like to clear cookies at the very top of each scenario, but it doesn't work.

do we have some options to clear the safari sessions (I already search a lot on internet, but unfortunately no suitable answer)

## Environment

* Appium version (or git revision) that exhibits the issue: **1.8.0**
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: **macOS High Sierra Version: 10.13.6**
* Node.js version (unless using Appium.app|exe): **v8.6.0**
* Mobile platform/version under test: **iPhone 6s iOS 10.1.1(14B100)** 
* Real device or emulator/simulator: **Real Device**
* Appium CLI or Appium.app|exe:

## Details

I have used following Desired Capabilities:
`capabilities.setCapability("cleanSession","true");
capabilities.setCapability("ensureCleanSession","true");`

`driver.manage().deleteallcookies()`

1. Appium version = 1.8.0
2. Selenium version = 3.9.1
3. Appium java client = 6.0.0 BETA5

So is there any way to deletecookies on iPhone safari browser. or starts new session on iPhone safari real devices.

Thank you

**Comment by mykola-mokhnach** [comment] 2018-07-30 11:37
Closed as duplicate of https://github.com/appium/appium/issues/10568

**Closed by mykola-mokhnach** 2018-07-30 11:37 UTC
