### ISSUE TITLE
Compile of WebDriverAgent failes with XCode Version 10.2 beta 3 (10P99q) due messaging unqualified id

### ISSUE THREAD

**Issue by DGandalf** [appium/appium#12272] opened 2019-03-08 07:01 UTC
## The problem

I want to check my current Appium tests on iOS 12.2 Beta 4. For this case you have also to upgrade the XCode Compiler to the latest (Beta)Version available because XCTest of XCode Version 10.1 (10B61) does not support iOS 12.2

When compiling with the XCode Beta, then I got some "messaging unqualified id" errors.
As mentioned from bikeracer on 5 Feb  in https://github.com/core-plot/core-plot/issues/384

"Just tested CorePlot with the new XC 10.2 betas and this warning **seems to be now a dead-stop error**! Although couldn't find any hints in related XC release notes..."

## Environment

* Appium 10.0 and Appium 11.1
* Last Appium version that did not exhibit the issue (if applicable): Seems to be an XCode problem
* Desktop OS/version used to run Appium: MacOS 10.14.3 (18D109)
* Node.js version (unless using Appium.app|exe): See Point 1
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: iOS 12.2 Beta 4
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium-App

## Details

See above

## Code To Reproduce Issue [ Good To Have ]

Just replace the XCode compiler and try make a Build of a new WebDriverAgent when calling the Inspector-Window.

**Comment by DGandalf** [comment] 2019-03-08 07:06
I also googled about the messaging unqualified id problem and did not get any useful hints... :(
Because this error flag (-Wno-messaging-id) seems to be relatively new..

**Comment by mykola-mokhnach** [comment] 2019-03-08 07:19
Duplicate of https://github.com/appium/appium/issues/12101
The partial support of Xcode10.2 has been added to appium@beta though

**Comment by DGandalf** [comment] 2019-03-08 07:20
See also at this GIST https://gist.github.com/sadafyadegari/607af4c32d38de888a1f85c150a830f8
Which commes from : https://github.com/appium/appium/issues/12239

[35m[Xcode][39m       [[FBXCTRunnerDaemonSessionClass sharedSession] useLegacyEventCoordinateTransformationPath]) {
[35m[Xcode][39m        ^
[35m[Xcode][39m 
[35m[Xcode][39m /Users/gooduser/appium_test/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXCTestDaemonsProxy.m:86:10:
[35m[Xcode][39m  
[35m[Xcode][39m warning
[35m[Xcode][39m : 
[35m[Xcode][39m **messaging unqualified id [-Wobjc-messaging-id]**

**Closed by mykola-mokhnach** 2019-03-08 07:19 UTC
