### ISSUE TITLE
Click command not finished if after it Native iOS dialog shown

### ISSUE THREAD

**Issue by sasha943** [appium/appium#13549] opened 2019-11-06 08:20 UTC
## The problem

After click on element (webview) I have model Native dialog (iOS platform). But could not change context due click command finished with error.  
Command failed after 10 minutes timeout

**This behavior reproduce sometimes**

## Environment

* Appium version: 1.16.0-beta.1
* Node.js version: **v12.11.1**
* Npm: 6.11.3
* Mobile platform/version under test: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', 
* Simulator: iPad iOS 12.4

## Link to Appium logs

`HTTP] --> POST /wd/hub/session/f0b0a3f9-38bf-4285-b4bc-5bc2de125a0b/elements
[HTTP] {"using":"id","value":"QuestionLabel24690118"}
[HTTP] <-- POST /wd/hub/session/f0b0a3f9-38bf-4285-b4bc-5bc2de125a0b/elements 200 4 ms - 137
[HTTP] 
[HTTP] --> GET /wd/hub/session/f0b0a3f9-38bf-4285-b4bc-5bc2de125a0b/element/5008/displayed
[HTTP] {}
[HTTP] <-- GET /wd/hub/session/f0b0a3f9-38bf-4285-b4bc-5bc2de125a0b/element/5008/displayed 200 4 ms - 76
[HTTP] 
[HTTP] --> POST /wd/hub/session/f0b0a3f9-38bf-4285-b4bc-5bc2de125a0b/element
[HTTP] {"using":"id","value":"QuestionLabel24690118"}
[HTTP] <-- POST /wd/hub/session/f0b0a3f9-38bf-4285-b4bc-5bc2de125a0b/element 200 4 ms - 135
[HTTP] 
[HTTP] --> POST /wd/hub/session/f0b0a3f9-38bf-4285-b4bc-5bc2de125a0b/element/5009/click
[HTTP] {"id":"5009"}
[HTTP] <-- POST /wd/hub/session/f0b0a3f9-38bf-4285-b4bc-5bc2de125a0b/element/5009/click - - ms - -
[HTTP] 
[HTTP] --> POST /wd/hub/session/f0b0a3f9-38bf-4285-b4bc-5bc2de125a0b/element/5009/click
[HTTP] {"id":"5009"}
[HTTP] <-- POST /wd/hub/session/f0b0a3f9-38bf-4285-b4bc-5bc2de125a0b/element/5009/click 500 480012 ms - 206`

**Error:**

`An unknown server-side error occurred while processing the command. Original error: Did not get any response after 300s (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'mingam.eu.wappds.com', ip: 'fe80:0:0:0:1c46:527:c610:e212%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '11.0.4'
Driver info: *****
Capabilities {app: build/resources/16/15730264..., autoGrantPermissions: true, automationName: XCuiTest, browserName: , commandTimeouts: 40000, databaseEnabled: false, derivedDataPath: path, deviceName: Simulator_161573026495847, enforceFreshSimulatorCreation: true, fullReset: true, isHeadless: false, javascriptEnabled: true, launchTimeout: 240000, locationContextEnabled: false, nativeWebTap: false, networkConnectionEnabled: false, newCommandTimeout: 240, orientation: LANDSCAPE, platform: MAC, platformName: iOS, platformVersion: 12.4, resetOnSessionStartOnly: true, showIOSLog: false, showXcodeLog: true, simpleIsVisibleCheck: true, takesScreenshot: true, udid: 5E5BFB2C-C0F2-43A8-A82D-B99..., useNewWDA: true, usePrebuiltWDA: false, wdaLocalPort: 17859, webStorageEnabled: false}
Session ID: f0b0a3f9-38bf-4285-b4bc-5bc2de125a0b
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Did not get any response after 300s (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'mingam.eu.wappds.com', ip: 'fe80:0:0:0:1c46:527:c610:e212%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '11.0.4'
Driver info: ****
Capabilities {app: build/resources/16/15730264..., autoGrantPermissions: true, automationName: XCuiTest, browserName: , commandTimeouts: 40000, databaseEnabled: false, derivedDataPath: /Users/qa/IdeaProjects/Auto..., deviceName: Simulator_161573026495847, enforceFreshSimulatorCreation: true, fullReset: true, isHeadless: false, javascriptEnabled: true, launchTimeout: 240000, locationContextEnabled: false, nativeWebTap: false, networkConnectionEnabled: false, newCommandTimeout: 240, orientation: LANDSCAPE, platform: MAC, platformName: iOS, platformVersion: 12.4, resetOnSessionStartOnly: true, showIOSLog: false, showXcodeLog: true, simpleIsVisibleCheck: true, takesScreenshot: true, udid: 5E5BFB2C-C0F2-43A8-A82D-B99..., useNewWDA: true, usePrebuiltWDA: false, wdaLocalPort: 17859, webStorageEnabled: false}
Session ID: f0b0a3f9-38bf-4285-b4bc-5bc2de125a0b
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:276)
	at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:45)
	at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
	at io.appium.java_client.ios.IOSElement.execute(IOSElement.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)`

**Any advice on how I can handle this case or manage timeout???**

**Comment by sasha943** [comment] 2019-11-11 06:27
any updates??

**Comment by majchman** [comment] 2020-02-24 08:55
Encountered the same issue (see #13979 for details)

Attaching appium (v1.16.0-beta.3) logs with `safariLogAllCommunication` enabled: https://gist.github.com/majchman/0dcc9e926e0a8ef7ed86df693fa0b0e0

**Comment by mykola-mokhnach** [comment] 2020-03-02 06:51
Duplicate of https://github.com/appium/appium/issues/8582

**Closed by mykola-mokhnach** 2020-03-02 06:51 UTC
Labels: Mobile Safari
