### ISSUE TITLE
Error encountred , after turning off the wifi of iphone , the scripted failed and could'nt continue 

### ISSUE THREAD

**Issue by Hamzastreamwide** [appium/appium#15522] opened 2021-06-17 09:10 UTC
## The problem

After i turn of wifi the test fails Original error: Could not proxy. Proxy error: Could not proxy command to the remote server. Original error: socket hang up

## Environment

* Appium version (or git revision) that exhibits the issue: v1.22.0-beta.0
* Last Appium version that did not exhibit the issue (if applicable):  i think 1.21.0
* Desktop OS/version used to run Appium: mac os catalina
* Node.js version (unless using Appium.app|exe):v14.5.0
* Npm or Yarn package manager: 6.14.5
* Mobile platform/version under test: iphone 12.4.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: appium.app

## Details

i have a scenario where i need to turn off wifi than go back to my origianl app and continue the script , the scenario i tested it before it worked fine , today i revisited the senario and launched the test , when the step wifi is turned off , the script stops and fails due internal error  [debug] [W3C (0ac857ef)] Encountered internal error running command: Error: Could not proxy. Proxy 
## Link to Appium logs
https://gist.github.com/Hamzastreamwide/84a18387b0d99e54d4bc544448446819
Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
https://gist.github.com/Hamzastreamwide/a8ca02230a1ad555856a2a3d660339cd
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2021-06-17 09:26
Duplicate of https://github.com/appium/appium/issues/15499

**Closed by mykola-mokhnach** 2021-06-17 09:26 UTC
