### ISSUE TITLE
Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by igorek9191** [appium/appium#14971] opened 2020-12-23 18:14 UTC
## The problem

I'm trying to start appium test with selenium grid on iOS simulator. It fails with message `xcodebuild failed with code 65`
I've found your article https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md
In paragraph **Basic (manual) configuration** I have done all the instructions and advise to run WebDriverAgentRunner tests of xcode project
`xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test`
and here is a thing - I see errors in result of command
`Testing failed:
	Building for iOS Simulator, but the linked and embedded framework 'YYCache.framework' was built for iOS + iOS Simulator.
	Building for iOS Simulator, but the linked and embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator.`
So why it happens? And how to fix the errors ?
## Environment

* Appium version 1.18.3
* Desktop OS/version used to run Appium: mac 10.15.7 Catalina
* Node.js version (unless using Appium.app|exe): v14.15.3
* Npm or Yarn package manager: 6.14.9
* Real device or emulator/simulator: iPhone 12 Pro Max (simulator), 14.3

**Comment by KazuCocoa** [comment] 2020-12-23 18:17
Probably duplicate of https://github.com/appium/appium/issues/14952

**Comment by mykola-mokhnach** [comment] 2020-12-23 18:26
It's for sure is:

> 14.3

**Closed by mykola-mokhnach** 2020-12-23 18:26 UTC
