### ISSUE TITLE
get_log not working starting with appium-xcuitest-driver v. 4.3.6

### ISSUE THREAD

**Issue by shaky** [appium/appium#16764] opened 2022-04-13 10:45 UTC
## The problem:

get_log is not working after installing appium-xcuitest-driver v. 4.3.6 https://www.npmjs.com/package/appium-xcuitest-driver/v/4.3.6

## Environment:

appium version  `2.0.0-beta.25`
appium-xcuitest-driver version  `4.3.6.` installed using `appium driver install xcuitest@4.3.6`

## Code To Reproduce Issue:

```
    def test_get_syslog(self):
        my_syslog = self.driver.get_log('syslog')
        return my_syslog
```

Exception returned:
`Message: An unknown server-side error occurred while processing the command. Original error: Unsupported log type 'syslog'. Supported types: {}`

`get_log`  works fine on appium-xcuitest-driver v. `4.3.5`
`4.3.7` (latest public) has the same behavior (it errors)

**Comment by mykola-mokhnach** [comment] 2022-04-13 10:47
Duplicate of https://github.com/appium/appium/issues/16738

**Comment by shaky** [comment] 2022-04-13 10:48
thanks @mykola-mokhnach

**Closed by mykola-mokhnach** 2022-04-13 10:47 UTC
