### ISSUE TITLE
getPageSource() does not return full element hierarchy

### ISSUE THREAD

**Issue by ljoshenjka** [appium/appium#14386] opened 2020-05-29 07:15 UTC
## The problem

Some of the application pages does not contain most of the element hierarchy returned with getPageSource(). Happens only on iOS, no issue observed on Android.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1, 1.18.0-beta.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Catalina 10.15.4
* Node.js version (unless using Appium.app|exe): v14.3.0
* Npm or Yarn package manager: 6.14.4
* Mobile platform/version under test: iOS 13.4.1
* Real device or emulator/simulator: iPhone 8 Plus / iPhone XR real device
* Appium CLI or Appium.app|exe: CLI

## Details

With updated Xamarin.Forms to version 4.6.0.800 from 4.5 Appium does not return full element hierarchy for half of the application pages on iOS devices. Pages does not have anything similar from technical perspective and might have all kind of UI elements present. Full element hierarchy is not shown neither in runtime by executing getPageSource() nor with Appium inspector. Executing findElement also does not retrieve needed elements. 

While exploring element hierarchy with Xcode Accessibility Inspector i can see full elements tree.

All the pages where problem appeared page source retrieved looks similar despite the fact that on UI that might be completely different screens:
DOM:
```
<?xml version="1.0" encoding="UTF-8"?>
<AppiumAUT>
    <XCUIElementTypeApplication type="XCUIElementTypeApplication" name="testapp" label="testapp" enabled="true" visible="true" x="0" y="0" width="414" height="736">
        <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="false" x="0" y="0" width="414" height="736">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="414" height="736">
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="414" height="736" />
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="736" width="414" height="226" />
            </XCUIElementTypeOther>
        </XCUIElementTypeWindow>
    </XCUIElementTypeApplication>
</AppiumAUT>
```

## Link to Appium logs

[GIST](https://gist.github.com/ljoshenjka/7f37f9cc59951216abc764a046f579ff)

**Comment by mykola-mokhnach** [comment] 2020-05-29 09:05
Duplicate of https://github.com/appium/appium/issues/13958

**Closed by mykola-mokhnach** 2020-05-29 09:05 UTC
