### ISSUE TITLE
There is no click propagation to Shadow Dom on iOS

### ISSUE THREAD

**Issue by Sam55555** [appium/appium#15874] opened 2021-09-21 15:07 UTC
## The problem

If click event is added to element inside shadow dom, then there is no click propagation. Single click on shadow dom host causes no action on iOS.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.1
* Last Appium version that did not exhibit the issue (if applicable): 1.20.1
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iPad Air (4th generation)
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

[ShadowRootClickOnIOS.zip](https://github.com/appium/appium/files/7204195/ShadowRootClickOnIOS.zip)

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2021-09-21 15:10
Duplicate of https://github.com/appium/appium/issues/9733

**Closed by mykola-mokhnach** 2021-09-21 15:10 UTC
