### ISSUE TITLE
bug: appium-adb nonconfigurable timeout

### ISSUE THREAD

**Issue by magwas** [appium/appium#18248] opened 2023-02-24 11:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In a slow CI I get.
org.openqa.selenium.SessionNotCreatedException: 
Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Appium Settings app is not running after 5000ms

There is no corresponding capability to set the timeout to any other value than 5000ms

### Expected Behavior

Ability to set the timeout.

### Minimal Reproducible Example

Test an android app in a slooow CI.

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by magwas** [comment] 2023-02-24 11:23
https://github.com/appium/appium-adb/pull/635 fixes this.

**Comment by mykola-mokhnach** [comment] 2023-02-24 11:45
Could you confirm that increasing the timeout resolves the issue? Usually 5 seconds is more than enough to verify that settings helper is running

**Comment by magwas** [comment] 2023-02-24 12:02
I can confirm that the timeout is effectively modified by the capability.
Unfortunately the settings server did not come online after 600 000ms, so there could be another problem here...

**Comment by magwas** [comment] 2023-02-24 19:05
The case right now looks like:
I modified the Makefile by inserting a '-' in the beginning of the line doing the end-to-end test, so its failure does not fail the build.
Added a line right after that with an adb logcat and an exit.
Haven't see the error since. Even after reverted those changes.
The CI uses a docker container to make sure that the builds are highly reproducible...

**Comment by mykola-mokhnach** [comment] 2023-02-24 19:44
Sorry, I still don't understand what the cause was. Did the increased timeout help? Or it was something else?

**Comment by magwas** [comment] 2023-02-24 20:17
I neither understand it. It was not the increased timeout. And could not be anything in the android emulator, the android SDK, Appium code, or underlying libraries behind any of them, as those guaranteed not to change. Even the system load was similar.

**Comment by mykola-mokhnach** [comment] 2023-02-25 17:40
Shall we then close this report as not an issue?

**Closed** 2023-02-27 20:02 UTC
Labels: Needs Info
