### ISSUE TITLE
Even though the elements are visible,appium is showing visible as false.

### ISSUE THREAD

**Issue by syedmahamood** [appium/appium#12659] opened 2019-05-17 20:06 UTC
## The problem
Even though the elements are visible,appium is showing visible as false.

## Environment
macOS Mojave 10.14.4
Appium Desktop 1.13.0
selenium-java 3.141.59
testng 6.14.3
java-client 6.1.0

## Details
Text box elements visible property is showing as false in Appium while it is visible and can enter text manually. However the buttons visible property shows true and action can be performed.

## Link to Appium logs

[]([](https://github.com/facebookarchive/WebDriverAgent/issues/1121))

**Comment by mykola-mokhnach** [comment] 2019-05-17 20:57
Duplicate of https://github.com/appium/appium/issues/11507

This property is returned by Apple's Accessibility. There is nothing that can be changed there on Appium side.

**Closed by mykola-mokhnach** 2019-05-17 20:57 UTC

**Comment by syedmahamood** [comment] 2019-05-18 09:24
thanks @mykola-mokhnach, Do you suggest that we talk with developer to modify the program to display visible as true. Any pointers/info to make the change in the program to the developer appreciated.

**Comment by mykola-mokhnach** [comment] 2019-05-18 16:20
I don't have any particular recommendations, since it is not clear how the accessibility framework calculates the value. It is a black box. Try different approaches in your code and see if it works.
