### ISSUE TITLE
GetPageSource goes in loop with after met error

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#7034] opened 2016-10-17 08:43 UTC
## The problem

There is known issues that some screens fail to load due to known errors on pageSource. When we meet with this problem Appium server goes into LOOP. Example of logs attached.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6.0
- Last Appium version that did not exhibit the issue (if applicable): 1.5.3
- Desktop OS/version used to run Appium:
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: iOS xCode 8
- Real device or emulator/simulator: Simulator 10.0
- Appium CLI or Appium.app|exe:
## Link to Appium logs

```
[debug] [XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [POST /source] to [POST http://localhost:8100/session/204AA610-4CD4-473B-871D-C9A89861068C/source] with no body
[debug] [WebDriverAgent] Sim: Oct 17 11:37:48 aleks XCTRunner[38682]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x618000447f50> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Oct 17 11:38:03 aleks XCTRunner[38682]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x618000459cb0> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Oct 17 11:38:19 aleks XCTRunner[38682]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x61800025ddc0> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Oct 17 11:38:34 aleks XCTRunner[38682]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x618000450ec0> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Oct 17 11:38:49 aleks XCTRunner[38682]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x61800025d3a0> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Oct 17 11:39:04 aleks XCTRunner[38682]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x61800024b340> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
```

**Comment by mykola-mokhnach** [comment] 2016-10-18 11:18
Might be fixed by https://github.com/facebook/WebDriverAgent/pull/332

**Comment by imurchie** [comment] 2016-10-18 13:30
Let me know when that PR gets through (I'll keep an eye out, too), and I'll start the process of getting it in here. Thanks!

**Comment by amirwaisman** [comment] 2016-10-18 13:57
I'm getting the same issue:

[JSONWP Proxy] Proxying [POST /source] to [POST http://localhost:8100/session/AC341A43-8F80-4477-BF0C-440180A517D0/source] with no body
[debug] [WebDriverAgent] Sim: Oct 18 15:56:43 BLMOT-MACBOOK-92 XCTRunner[77755]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x7fbe8e813410> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Oct 18 15:56:59 BLMOT-MACBOOK-92 XCTRunner[77755]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x7fbe8e817930> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Oct 18 15:57:14 BLMOT-MACBOOK-92 XCTRunner[77755]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x7fbe89cf8c50> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[HTTP] <-- GET /wd/hub/session/f953977d-05bd-469c-b35f-54009e8837a1/source - - ms - -

**Comment by tolgatanriverdi** [comment] 2016-10-18 20:05
This is another log which waits too long: 

```
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["a12ee8dd-0ec3-4d62-9482-2...
[debug] [XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [POST /source] to [POST http://localhost:8100/session/CB9E2FE8-0334-4AE3-8507-C198ADA90901/source] with no body
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...

```

**Comment by amirwaisman** [comment] 2016-10-27 07:49
Any news on this? Very critical

**Comment by mykola-mokhnach** [comment] 2016-10-27 09:38
@amirwaisman you can patch you local WDA with this diff https://github.com/facebook/WebDriverAgent/pull/332 and see whether it resolves the problem.

**Comment by imurchie** [comment] 2016-11-01 21:02
The latest release of the xcuitest driver has this patch in it. Can you re-install Appium without shrinkwrap and see if things are working

```
npm uninstall -g appium
npm install -g appium --no-shrinkwrap
```

**Comment by amirwaisman** [comment] 2016-11-02 13:12
@mykola-mokhnach, could you please specify where should I apply the patch?

./node_modules/webdriveragent/WebDriverAgent/WebDriverAgentLib/Categories/XCUIElement+FBIsVisible.m

OR

./WebDriverAgent/WebDriverAgentLib/Categories/XCUIElement+FBIsVisible.m

Thanks in advance!

**Comment by mykola-mokhnach** [comment] 2016-11-02 13:16
Like @imurchie already mentioned the patched driver should be already included into Appium release. Just follow the steps he has provided.

**Comment by amirwaisman** [comment] 2016-11-02 13:17
Perfect, thanks.

**Comment by davidschwab** [comment] 2016-11-23 20:57
I too was having this issue.

I just tried with the latest appium (currently 1.6.1-beta) and wda using the following:
```
npm install -g appium@beta --no-shrinkwrap
```

Unfortunately, the latest wda didn’t resolve the issue.

However, in my case, I was able to workaround the issue by introducing a 1 second delay prior to executing the getPageSource(). Not ideal. It would be nicer if facebook wda could handle this automatically so we don’t have to put in delays/wait.until all over the place.

**Comment by mykola-mokhnach** [comment] 2016-11-24 08:02
@davidschwab I bet this delay is because of the running animation. I've created a [PR](https://github.com/facebook/WebDriverAgent/pull/369) to WDA to avoid such hardcoded delays, but project owner has closed it, because he wants to find better/safer method for getting elements visibility instead.

**Comment by muratme** [comment] 2016-11-29 12:39
@imurchie tried to reinstall appium as you mentioned 

npm uninstall -g appium
npm install -g appium --no-shrinkwrap

but nothing changed still got same error while inpecting application
`
[debug] [WebDriverAgent] Sim: Nov 29 15:40:24 murat-mercans-MacBook-Pro XCTRunner[21845]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x608000242700> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
`

**Comment by amirwaisman** [comment] 2016-11-29 13:22
Same here, definitely didn't solve this issue...

**Comment by mykola-mokhnach** [comment] 2016-11-29 14:00
It happens because of https://github.com/facebook/WebDriverAgent/issues/372 No way to workaround it from Appium.

**Comment by KBhatti** [comment] 2016-12-10 02:10
@imurchie did you have a solution for this yet please:
Traviss-Mac XCTRunner[7358]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x600000255120> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Dec 10 01:40:51 Traviss-Mac XCTRunner[7358]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x600000455480> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Dec 10 01:41:07 Traviss-Mac XCTRunner[7358]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x600000455510> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Dec 10 01:41:22 Traviss-Mac XCTRunner[7358]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x60000024a1a0> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1

**Comment by pengboZheng** [comment] 2016-12-13 15:49
same issue with 1.6.3:

> [debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["3b27d51e-ed54-4bde-b424-863c1e4ec355"]
[debug] [XCUITest] Executing command 'getPageSource'
[debug] [JSONWP Proxy] Proxying [POST /source] to [POST http://localhost:8100/session/1D9B5D23-5BA6-4F29-8504-2B6E76CC7301/source] with no body
[debug] [WebDriverAgent] Device: Dec 13 10:44:52 Odells-iPhone XCTRunner[1158] <Warning>: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x160076e10> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [WebDriverAgent] Device: Dec 13 10:45:07 Odells-iPhone XCTRunner[1158] <Warning>: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x16000b8a0> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [WebDriverAgent] Device: Dec 13 10:45:23 Odells-iPhone XCTRunner[1158] <Warning>: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x16006dd50> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1

**Comment by wangtao169447** [comment] 2016-12-20 07:08
@imurchie 
I have tryed
`npm uninstall -g appium
npm install -g appium --no-shrinkwrap`
but it is not work.

**Comment by michalkaftanski-airhelp** [comment] 2016-12-20 09:40
Got similar problem which happened possibly since 1.6.1. Time executions of all tests on iPhone 6S simulator have increased a lot or gives negative failures. Randomly there are looped:
`
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/A73FAC83-F374-4E98-AE8E-41E51C413807/elements] with body: {"using":"xpath","value":"//XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeButton[2]"}
[debug] [WebDriverAgent] Sim: Dec 20 10:37:35   XCTRunner[25916]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x60000124d260> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Dec 20 10:37:51   XCTRunner[25916]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x60000144b2e0> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Dec 20 10:38:07   XCTRunner[25916]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x600000851160> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
`

Any confirmed workaround so far?

**Comment by vikramvi** [comment] 2017-01-26 14:20
https://github.com/facebook/WebDriverAgent/pull/369 this PR is closed but still getting same issue on iPhone SE simulator with 10.2

I have a login screen, after entering credentials, I check for post login screen element to make sure login in successful.

During this it throws error

`[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeApplication[contains(@label,'Crew')]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]//XCUIElementTypeButton[contains(@label,'More')]","81339064-da30-4f59-89f7-08821b3fa62b"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/62ECCF70-E50E-46CA-8EB9-6BFDDBEB7E0B/element] with body: {"using":"xpath","value":"//XCUIElementTypeApplication[contains(@label,'Crew')]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]//XCUIElementTypeButton[contains(@label,'More')]"}
[debug] [WebDriverAgent] Sim: Jan 26 15:11:47 Vikrams-MacBook-Pro XCTRunner[76316]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x610000649690> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Jan 26 15:12:02 Vikrams-MacBook-Pro XCTRunner[76316]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x610000849f30> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Jan 26 15:12:17 Vikrams-MacBook-Pro XCTRunner[76316]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x61000064fcf0> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"38C1BDDC-2EB6-4405-BAE5-B3BF76F392A8","type":"XCUIElementTypeButton","label":"More"},"sessionId":"62ECCF70-E50E-46CA-8EB9-6BFDDBEB7E0B","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"38C1BDDC-2EB6-4405-BAE5-B3BF76F392A8","type":"XCUIElementTypeButton","label":"More"}
`

**Comment by vikramvi** [comment] 2017-01-26 14:48
@mykola-mokhnach some more update on this , steps to reproduce in arc

1.  I'm in log-in page, enter valid details and press enter
2. In post login screen, I look for expected element
3. It take really long to say if element is there for first time as appium is looking for this new element in login screen itself instead of 2nd screen. Somehow old screen is still catched in appium

```
[HTTP] <-- GET /wd/hub/session/07a5447d-1869-4f1e-a833-cca3532f96ab/source 200 468 ms - 24512 
[HTTP] --> POST /wd/hub/session/07a5447d-1869-4f1e-a833-cca3532f96ab/element {"using":"xpath","value":"//XCUIElementTypeApplication[contains(@label,'Crew')]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]//XCUIElementTypeButton[contains(@label,'More')]"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeApplication[contains(@label,'Crew')]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]//XCUIElementTypeButton[contains(@label,'More')]","07a5447d-1869-4f1e-a833-cca3532f96ab"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/B81A2CDB-5DDD-48F1-85C0-43A292D31F48/element] with body: {"using":"xpath","value":"//XCUIElementTypeApplication[contains(@label,'Crew')]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]//XCUIElementTypeButton[contains(@label,'More')]"}
[Xcode]         Find: Descendants matching type Button
[Xcode]         Find: Descendants matching type Button
    t =   151.89s         Find: Element at index 0
    t =   151.89s     Find the Button
    t =   151.89s         Use cached accessibility hierarchy for
.....
2017-01-26 15:43:30.984 XCTRunner[76504:6797102] Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x6000004406f0> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
2017-01-26 15:43:46.008 XCTRunner[76504:6797102] Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x600000056680> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
2017-01-26 15:44:01.027 XCTRunner[76504:6797635] Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x600000250380> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
    t =   285.69s     Get all elements bound by index for: Descendants matching type Button
    t =   285.72s         Snapshot accessibility hierarchy 
```

**Comment by mykola-mokhnach** [comment] 2017-01-26 14:53
This has not been completely fixed, only some parts of it. Try to update WDA sources from the recent master [branch](https://github.com/facebook/WebDriverAgent), where visibility attribute has been excluded from XML. This might help to make things running better.

**Comment by vikramvi** [comment] 2017-01-26 14:57
@mykola-mokhnach I've installed appium 1.6.3 with npm. 

can you please clarify how to update only WDA version ?

Is there any workaround to this problem ?

**Comment by mykola-mokhnach** [comment] 2017-01-26 14:59
Appium on MacOS keeps WDA sources in 

```
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
```

folder by default.

**Comment by imurchie** [comment] 2017-01-26 15:33
You can also clone WDA wherever you'd like, and then pass in the full path to the directory using the `bootstrapPath` desired capability.

**Comment by vikramvi** [comment] 2017-01-26 16:53
@imurchie I didn't find this cap under https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md, is this added newly ?

**Comment by imurchie** [comment] 2017-01-26 17:04
No. It's for debugging and trying things out, and purposefully undocumented. Normally it should not be used, since there are often breaking changes in WDA and if you use your own copy that we haven't incorporated into the Appium driver for it, things can be broken.

**Comment by vsaraydarova-broadsoft** [comment] 2017-01-30 13:35
"visibility attribute has been excluded from XML" is this temporary or this is intended? No more "visible" attribute for elements for iOS 9.x and 10.? 
I updated to the latest WDA source, and I saw that visible attributes are missing. I have side navigation control and I can't recognize if it is open or not. When I launch my application, side navigation items are missing in page source, but if I open ones the side navigation bar and close it, items are always available in page source even if they are not visible?

**Comment by Aswini-kumarPradhan** [comment] 2017-02-16 14:39
I was too facing this issue. Did the following 

npm uninstall -g appium
npm install -g appium --no-shrinkwrap

It resolved my driver.getpagesource to go into loop.

**Comment by vikramvi** [comment] 2017-02-16 16:25
@imurchie can you please clarify if;  appium beta & all future versions also needs to be installed with --no-shrinkwrap option ?

**Comment by imurchie** [comment] 2017-02-16 16:28
Beta releases are not shrinkwrapped. Installing `appium@beta` gets the latest of everything. Full releases _are_ shrinkwrapped, so the dependencies are locked. If someone wants the latest from a full release `--no-shrinkwrap` is necessary.

**Comment by KBhatti** [comment] 2017-02-17 03:01
so the solution is to just install with no-shrinkwrap...we do not need to go into the xcuitest folder path and update the xcuitest driver? btw what version do we update it to..as in npm update xcuitestdriver@2.5.1 ?

**Comment by jlipps** [comment] 2017-04-13 22:50
Correct:

```
npm uninstall -g appium
npm install -g appium@beta
```

Will get the un-shrinkwrapped beta.

**Closed by jlipps** 2017-04-13 22:50 UTC
Labels: NeedsTriage
