### ISSUE TITLE
appium inspector not launching and crashing the application under test multiple times

### ISSUE THREAD

**Issue by Sha-123** [appium/appium#14523] opened 2020-07-07 10:41 UTC
## The problem

An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Invalid pid 0 Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

## Environment

* Appium version : 1.17.1
* Desktop OS/version used to run Appium: mac os hight sierra 10.13.6
* Real device or emulator/simulator: real device iphone 11(os 13.5.1)

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by Sha-123** [comment] 2020-07-07 10:44
[appium-server-logs.txt](https://github.com/appium/appium/files/4884267/appium-server-logs.txt)
Please find the attached logs

**Comment by mykola-mokhnach** [comment] 2020-07-07 11:12
I cannot reproduce the issue locally. Try to run the test on a clean machine.

**Comment by mykola-mokhnach** [comment] 2020-07-07 11:15
Possible duplicate of https://github.com/appium/WebDriverAgent/issues/338

**Comment by mykola-mokhnach** [comment] 2020-07-10 12:57
Closed as third party issue

**Closed by mykola-mokhnach** 2020-07-10 12:57 UTC
Labels: ThirdParty, XCUITest
