### ISSUE TITLE
Root certificate not installed correctly for ios 11 simulator

### ISSUE THREAD

**Issue by JonathanWylie** [appium/appium#9536] opened 2017-10-26 09:24 UTC
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: OSX High Sierra
* Node.js version (unless using Appium.app|exe): v8.6.0
* Mobile platform/version under test: ios 11.0.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.app
* Tested with x-code 9.0 and 9.1

## Details
Specifying customSSLCert is not working.
When I specify my root certificate in the capabilities (customSSLCert), then I can see when I look in the settings: General -> About -> Certificate Trust Settings I can see my root certificate is listed and is trusted. But when I visit a site using it, then it says the site is "Not Trusted".

If I install the certificate manually via email attachment, then I can see a profile is created, and I have to manually trust it in "Certificate Trust Settings". Under these circumstances I can visit my site, and it trusts the certificate.

So there is some difference (maybe the profile?) which means it trusts the certificate when installed manually, but not when appium installs it.

Frustratingly Safari in iOS won't tell me why it doesn't trust the certificate. Neither am I able to get the web inspector connected (develop menu does not show "simulators") so I can't use that to try to debug it.

**Comment by LukasLewandowski** [comment] 2017-10-27 09:57
I have also experienced some problem with ssl certification when trying to run appium tests on iOS11. Appium was returning some problem with ssl certificate for launching hybrid cordova build app.

**Comment by mykola-mokhnach** [comment] 2017-10-27 10:57
Please attach full server log

**Comment by dpgraham** [comment] 2017-10-28 16:11
Is this something that was working in prior Appium versions and then stopped working in 11?

**Comment by dpgraham** [comment] 2017-10-28 16:11
*prior IOS versions

**Comment by JonathanWylie** [comment] 2017-10-30 09:09
@dpgraham I havn't tried previous versions of ios with appium. So I am not sure if it worked with appium before. The documentation implies that it should work, so I assume it worked when it was first added to appium. I have previously been using ios-driver with older versions of ios, together with https://github.com/ADVTOOLS/ADVTrustStore/blob/master/iosCertTrustManager.py which did work with old versions of ios (It worked with iOS 8). It looks to me like it does the same thing as Appium.

@mykola-mokhnach I have attached appium logs to this comment.
[appiumLogs.txt](https://github.com/appium/appium/files/1426577/appiumLogs.txt)

**Comment by dpgraham** [comment] 2017-11-01 20:42
@JonathanWylie I'm able to reproduce this issue. Looks like something happened with a recent version of IOS/Xcode that broke it.

I think it's related to this: https://support.apple.com/en-ca/HT204477

We'll need to find a way to programatically set the Certificate Trust Settings.

**Comment by JonathanWylie** [comment] 2017-11-02 04:33
@dpgraham what is strange is that it seems like the simulator thinks the certificate is trusted. If I look in settings  certificate trust settings, then I see it there, and I see it says it is trusted. Despite that it seems to in reality not to be trusted.

**Comment by dpgraham** [comment] 2017-11-02 16:56
Are you saying that when you navigate to `Settings > General > About > Certificate Trust Settings` it shows the domain as being toggled but it doesn't open the page? Like this...

![screen shot 2017-11-02 at 9 55 12 am](https://user-images.githubusercontent.com/852574/32339164-249c6b3a-bfb4-11e7-84e6-a91683c4ad47.png)

**Comment by JonathanWylie** [comment] 2017-11-03 01:14
@dpgraham Yes exactly.

**Comment by JonathanWylie** [comment] 2017-11-03 10:18
@dpgraham Here is some more information that might help you.

I compared the TrustStore.sqlite3 entry between an appium installed CA certificate and a manually installed CA certificate.

The difference was in the certificate subject column. 
I got back different types, the manually installed one was <type 'buffer'>
The appium installed one was <type 'unicode'>

When I print them to the console, I get mostly unreadable output for the manually installed certificate. Some of it is plain text, and it seems to be parts of the certificate not included in the plain text version.
So it looks like both different content and in a different format.

I tried copying the TrustStore.sqlite3 from the manually installed simulator to the appium one.
To my suprise it worked. I was suprised, because when I tried this before, it did not work.
When I tried it again with another simulator it did not work. It looks like the page is loading OK, but I get a blank page.

**Comment by JonathanWylie** [comment] 2017-11-03 11:40
@dpgraham 
So details I found so far:
- When copying a correct db to a fresh simulator which is not started yet
  - The certificate is not even listed in the Certificate Trust Store Settings.
  - Safari will not load the page, complaining certificate is untrusted
- When I use appium to install the certificate
  - It shows up in the Certificate Trust Store list
  - It shows as trusted
  - Safari doesn't seem to really trust it
- When appium installs the certificate and I toggle trust off and on the Certificate Trust Settings
  - Safari still does not trust it
- What appium writes to the db is different to what the simulator writes to the db when the certificate is manually installed.
- When the certificate is manually installed from an email attachment. 
  - A profile is installed in addition to the certificate appearing in Certifcate Trust Settings
  - When it is manually toggled to trusted
  - Safari will trust the certificate and load the page.

**Comment by dpgraham** [comment] 2017-11-03 18:11
Awesome thanks a lot for the research @JonathanWylie!

What I'm thinking I could do next is try running [Charles Proxy](https://www.charlesproxy.com/). Charles is a reverse-proxying tool that adds certs to IOS Simulators and IOS Devices. If they were able to make it work somehow, that means that it is possible to programmatically add a certificate (and I could perhaps email them to ask how they did it). If not, then there may not be a fix.

**Comment by Aditya1209** [comment] 2017-11-20 13:42
Do we have any further update on this? because this is blocking me as well.
 One clarification: can we work with xcode 8 with out his issue ? if yes can you please provide steps to do that ?

**Comment by dpgraham** [comment] 2017-11-21 07:44
@Aditya1209 It doesn't look very promising, to be honest. I've done a fair bit of digging on this and I don't know if it's even possible to programmatically enable it.

You can indeed use an older version. Xcode 8 with iOS Simulator version <= 10.2 will work

It looks like iOS 10.3 introduced this issue.

**Comment by Aditya1209** [comment] 2017-11-22 09:35
@dpgraham  Thanks for your replay Dan.

Now i downgraded Xcode version to 8, and when i start execution still i am facing "can not verify server identity" pop up when i hit HTTPS page URL. Can you please provide steps to over come this problem through code?

Right now i am using Accept insecure certs and accept ssl certs capabilities but still no luck. 

Please help me on this.

**Comment by dpgraham** [comment] 2017-11-22 10:22
Can you provide the Appium logs? And you're providing the `customSSLCert` capability, correct?

**Comment by Aditya1209** [comment] 2017-11-22 13:49
No i have not provided customSSLCert capability in my code.

can you please send me description link about that capability so that i can do that.

**Comment by Aditya1209** [comment] 2017-11-22 13:52
@dpgraham just for clarification, we need to pass the customSSLCert path to this capability am i correct?

**Comment by Aditya1209** [comment] 2017-11-22 14:04
@dpgraham  i added customSSLCert capability and when i executed i am facing below error.

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: unable to load certificate
1920:error:0906D06C:PEM routines:PEM_read_bio:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/crypto/pem/pem_lib.c:648:Expecting: TRUSTED CERTIFICATE

**Comment by dpgraham** [comment] 2017-11-23 08:06
@Aditya1209 Yeah it has to be the `customSSLCert` as a string. So you just need to open your `.pem` file and then cut and paste the contents into your `customSSLCert` string.

**Comment by JonathanWylie** [comment] 2017-12-04 02:14
So I found a way to programmatically install the certificate. It's not ideal, because it's a bit slow.
What I have done is used webdriver to automate the manual install process.
- setup a webserver serving the certificate
- start webdriver session with safari
- Load the url which provides the certificate you want to install
- (In native mode) follow click on the various ok, install etc buttons to complete the installation process. 
- Close the safari webdriver session
- Start webdriver session using the android settings
- Navigate to the Certificate Trust Settings section
- Click the switch to enable the certificate that was just installed

One advantage of this solution is that presumably it would also work if you want to test on a real device. The old solution  (which no longer works) only works for simulators, because it hacks the sqllite security database for the simulator.

**Comment by dpgraham** [comment] 2018-01-11 17:09
@JonathanWylie I'm looking at re-visiting this issue. What happens if you use `customSSLCert` and then navigate directly to `Certificate Trust Settings`. Does that not work? Or do you _have to_ accept the certificate from Safari?

**Comment by JonathanWylie** [comment] 2018-01-19 01:28
@dpgraham I'm pretty sure I tried that, and it didn't work.
I found that using customSSLCert does not result in a profile being created. 
I never managed to get https to work in Safari without the profile, and I never found a way to create the profile (in a simulator) without installing the certificate through Safari.

Feel free to try again though, perhaps there are some changes in the Simulator since then, which solve this problem.

**Comment by dpgraham** [comment] 2018-02-03 00:25
Looks like there may be a fix for this after all. I think the issue was that we needed to reboot the Simulator after installing the SSL cert in order for the change to take effect. I have a PR in for it now.

**Comment by dpgraham** [comment] 2018-02-07 21:28
Turns out the fix was a lot simpler then I thought it would be.

The way to programmatically install an SSL cert on IOS Simulators (10.3+) is to:

1. Boot up the Simulator
2. Install the SSL certificate
3. Restart the Simulator

This fix will be in the next version

**Comment by RobYed** [comment] 2018-04-16 08:41
For me it looks like this is still an issue. Since I had the same problems with version 1.7.2, I started to use **1.8.0-beta5**. Indeed, it actually installs the certificate and correctly sets the "full trust for root certificates" setting - at least in the settings screen. Nevertheless, the page is still handled as unsecure within the WebDriverAgent.

When I manually start a simulator instance, install the same certificate and activate "full trust for root certificates", it loads the page without any problems. Of course, as soon as appium starts its own simulator instance these settings are gone. Thus I need to use the `customSSLCert` capability.

Am I missing something or might this capability still not work as expected?

I am running:
- Appium version (or git revision) that exhibits the issue: 1.8.0-beta5
- Desktop OS/version used to run Appium: OSX Sierra (10.12.6)
- Node.js version (unless using Appium.app|exe): v9.10.1
- Mobile platform/version under test: ios 11.2
- Real device or emulator/simulator: simulator
- Appium CLI or Appium.app|exe: Appium CLI
- Tested with x-code 9.2

My capabilities look like this:
```js
exports.config.capabilities = {
  browserName: 'safari',
  platformName: "iOS",
  deviceName: 'iPhone 8',
  automationName: 'XCUITest',
  customSSLCert: fs.readFileSync('src/test/js/integration/conf/root-ca.pem', 'utf8')
};
```

I would be very thankful to get some feedback on this.

**Comment by JonathanWylie** [comment] 2018-04-17 00:50
We had the same problem as you @RobYed . So we stayed with using webdriver to install the certificate in the same way you would install it manually, just by automating those manual steps.
Using customSSLCert makes the certificate trusted in the settings, but does not create a "profile". You can see that when you install the certificate manually and go to the settings, you can see a profile has been created too. I suspect this is what is missing.

**Comment by RobYed** [comment] 2018-04-17 06:38
@dpgraham Thanks for your fast reply! As far as I can tell the simulator restarts. It seems to happen directly after the loading screen and right before the unlock screen usually appears. Is that right?

> Have you tried using an older version of Xcode with a version of IOS < 11.2?

The important point here is the Xcode version, right? Just to get sure: What you are asking me to do is to uninstall Xcode and reinstall an older version, say Xcode 8?

**Comment by RobYed** [comment] 2018-04-17 06:47
> So we stayed with using webdriver to install the certificate in the same way you would install it manually, just by automating those manual steps.

@JonathanWylie Oh thanks, sounds like a legit workaround. Would you mind sharing some details on how you did it? I am new to iOS automation and do not really have a starting point for something like this. I usually write Selenium tests for the web only.

**Comment by dpgraham** [comment] 2018-04-17 17:58
There's a tool called xcode-select that lets you switch between versions of Xcode. And yeah the Xcode version is probably the most relevant detail.

**Comment by RobYed** [comment] 2018-04-18 14:26
@dpgraham Thanks for the tip.

Unfortunately it neither worked with the following versions:
Xcode 9.01 + iOS 11.0 or 11.1
Xcode 8.3.3 + iOS 10.3

WebdriverAgent always prevents the site from loading. A difference compared to Xcode 9.2 + iOS 11.2 is, that the simulator window actually restarts - it disappears after the first system load, appears again and then executes the tests. 

I am pretty sure that the rest of my test setup works as expected. I questioned every part of it multiple times. So, I will now try one of the older Xcode Versions with the "older" Appium 1.7.2. Maybe this combination works. If you have any other idea on what I can do else, let me know.

**Comment by RobYed** [comment] 2018-04-18 14:31
This observation by @JonathanWylie still bothers me:
> Using customSSLCert makes the certificate trusted in the settings, but does not create a "profile". You can see that when you install the certificate manually and go to the settings, you can see a profile has been created too. I suspect this is what is missing.

I actually can confirm his observation. Maybe this is the missing part? Its not that I have a lot of expertise in this, only guessing...

**Comment by RobYed** [comment] 2018-04-18 15:05
Also no success with Xcode 8.3.3 + iOS 10.0 / 10.3 + Appium 1.7.2

I have no idea, what's the problem. As soon as I _manually_ install the certificate, Safari is happy.

**Comment by JonathanWylie** [comment] 2018-04-19 00:35
@RobYed I gave the list of steps to get webdriver to automate the manual process of installing the certificate in a comment earlier, https://github.com/appium/appium/issues/9536#issuecomment-348843177 .

**Comment by RobYed** [comment] 2018-04-19 05:48
@JonathanWylie Seems like I have overseen this comment... thanks!

**Comment by mykola-mokhnach** [comment] 2018-04-19 05:54
@JonathanWylie I'm going to implement you suggestion in the xcuitest driver: https://github.com/appium/appium-xcuitest-driver/pull/652. It should not be too hard, since Appium already acts as a web server.

**Comment by mykola-mokhnach** [comment] 2018-05-10 11:06
The feature has been merged to appium@beta: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-install-certificate.md

**Comment by mykola-mokhnach** [comment] 2018-06-05 05:47
Closing the issue as resolved. Please let us know if there are still any problems.

**Closed by mykola-mokhnach** 2018-06-05 05:47 UTC
Labels: NeedsInfo, P1, XCUITest
