### ISSUE TITLE
autograntpermission capability on android does not work with certain devices

### ISSUE THREAD

**Issue by pri-gadhiya** [appium/appium#17952] opened 2022-12-16 11:46 UTC
autograntpermission capability on android **does not work with certain devices eg: Oppo**

the [following command runs](https://github.com/appium/appium-adb/blob/f14a6609dd7059e951976ffa56ca8aaac78fa7b8/lib/tools/adb-commands.js#L367) to get and set the permissions, output of the same comand on oppo devices includes a suffix : **restricted=true**

```js
adb -s XXXXX shell dumpsys package com.sample.login | sed -n '/requested permissions:/,/install permissions:/{//!p;}' | grep "android.permission"

android.permission.INTERNET
      android.permission.SEND_SMS: restricted=true
      android.permission.READ_SMS: restricted=true
      android.permission.GET_ACCOUNTS
      android.permission.RECEIVE_BOOT_COMPLETED
      android.permission.ACCESS_NETWORK_STATE
      android.permission.ACCESS_FINE_LOCATION
      android.permission.ACCESS_COARSE_LOCATION
      android.permission.READ_EXTERNAL_STORAGE: restricted=true
      android.permission.WRITE_EXTERNAL_STORAGE: restricted=true
      android.permission.WAKE_LOCK
      android.permission.USE_BIOMETRIC
      android.permission.USE_FINGERPRINT
      android.permission.RECORD_AUDIO
      android.permission.QUERY_ALL_PACKAGES
```

**we try to grant the permission like android.permission.SEND_SMS: restricted=true it fails with an exception,
not only for SEND_SMS, anything that can be done with android.permission.<>: restricted=true**

```js
adb -s XXXXX shell pm grant com.sample.login android.permission.SEND_SMS: restricted=true

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown permission: android.permission.SEND_SMS:
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2256)
	at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:133)
	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.grantRuntimePermission(PermissionManagerService.java:3338)
	at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:6617)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2030)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:238)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23965)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5400)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4765)
	at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java:83)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
```
Which is flagged as an [error](https://github.com/appium/appium-adb/blob/f14a6609dd7059e951976ffa56ca8aaac78fa7b8/lib/tools/adb-commands.js#L376) and ignored silently.

Expected Behaviour: the capability should ideally auto-grant permissions requested by the app on all the devices. 

Issue: Due to the issue mentioned here about  android.permission.<>: **restricted=true** , permissions are not granted which results in unexpected permissions pop-ups post session start. **Also as mentioned at the start we don't see restricted=true for all devices but on some, one of the observed device is Oppo**

[link to old issue](https://github.com/appium/appium/issues/17877)

**Comment by mykola-mokhnach** [comment] 2022-12-16 14:19
Unfortunately there is nothing we could do about it. Perhaps, these devices provide some special settings to make permissions change more flexible. Consider contacting their customer support or asking at specialised forums.

**Comment by KazuCocoa** [comment] 2022-12-16 17:34
I wonder if https://github.com/appium/appium/issues/13802#issuecomment-702789411 (addressed in https://github.com/appium/appium-uiautomator2-driver/blob/master/docs/activity-startup.md#possible-problems-and-solutions), especially "Disable Permission Monitoring", helps

**Comment by pri-gadhiya** [comment] 2022-12-19 06:16
Ok, Thanks @KazuCocoa
Let me check if this helps us

**Comment by mykola-mokhnach** [comment] 2022-12-22 21:53
Possible duplicate of https://github.com/appium/appium/issues/14031#issuecomment-1360981556

**Comment by mykola-mokhnach** [comment] 2022-12-29 16:07
Closed as third party issue

**Closed by mykola-mokhnach** 2022-12-29 16:07 UTC
Labels: ThirdParty, UIAutomator2
