### ISSUE TITLE
Appium fails to find the simplest images using image search.

### ISSUE THREAD

**Issue by Rup1** [appium/appium#14884] opened 2020-11-12 17:12 UTC
## The problem

Hard to tell if this is an Appium or wdio issue. Appium is unable to find the number "1" on macos calculator using an image file, returns `'no such element'` error even though element is on the screen and represents a very basic image:

![image](https://user-images.githubusercontent.com/15389183/98969984-6bce8100-24dd-11eb-8ac1-502c204b7b5f.png)

calculator:
![image](https://user-images.githubusercontent.com/15389183/98970036-7ee15100-24dd-11eb-9435-6bc4ca344f5c.png)

I've tried a bunch of different images, and initially tried on ios. Never works, and I havent' found any working examples online.
## Environment

* Appium version (or git revision) that exhibits the issue: `1.18.3
* Desktop OS/version used to run Appium: MacOS Catalina 10.15.7
* Node.js version (unless using Appium.app|exe): 12.18.2
* Npm or Yarn package manager: npm 6.14.5
* Mobile platform/version under test: MacOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: appium npm package.

## Details
While I'm using the macdriver for this example, I initiallly tried this on a real ios device and  had the same result. All elements are easily found by appium using other locator strategies.

## Link to Appium logs
https://gist.github.com/Rup1/2e25a51b26483beb894351cddebeb6d8

## Code To Reproduce Issue
Clone the following repository, run `npm i` and then run `node macOsCalculator`.
You need to have `opencv4nodejs` installed on your machine for image search to work.

https://github.com/Rup1/appium-findbyimage

**Comment by mykola-mokhnach** [comment] 2020-11-13 06:16
Search by image never worked for mac driver, it's just not implemented for this particular driver.
Closed as duplicate of https://github.com/appium/appium/issues/14424

**Closed by mykola-mokhnach** 2020-11-13 06:16 UTC
