### ISSUE TITLE
Appium Server logs for particular session

### ISSUE THREAD

**Issue by swngarg-lt** [appium/appium#15416] opened 2021-05-24 07:00 UTC
## The problem
While passing session-id to fetch server logs, it's not giving logs for that particular session, it's giving all the logs for all the sessions. Is this normal?

## Environment

* Appium version - 1.18.2, 1.20.1, and latest versions

**Comment by mykola-mokhnach** [comment] 2021-05-24 08:41
Please provide a proper issue description according to the given template together with the logs.

We also need steps to reproduce the issue, the description of the actual and the expected result

**Comment by swngarg-lt** [comment] 2021-05-24 08:51
Steps: 

Running Appium with `--relaxed-security` flag and fetch server logs using this api [http://appium.io/docs/en/commands/session/logs/get-log/](url) 

Result: 
Suppose we executed 10 session on server but when we're calling above api with particular session id, it gives logs for all 10 sessions.

Expected Results: 
It should give Appium logs for that particular session only.

**Comment by mykola-mokhnach** [comment] 2021-05-24 08:55
This is the expected behaviour. Unfortunately the architecture of Appium does not allow to clearly split lo lines between sessions, because 
- There are logs that cannot be assigned to any session (for example driver startup logs)
- Logging in Appium is based on components rather than session (for example Appium Support component or simctl component)

Only API requests/responses have the first 8 chars of the actual session id in them

**Comment by jlipps** [comment] 2021-05-24 20:30
The best practice for service providers is 1 appium instance per session (kill server between sessions). It's not ideal, but it's a pretty small price to pay for increased security and stability.

**Comment by mykola-mokhnach** [comment] 2021-05-26 06:26
Closed as not an issue

**Closed by mykola-mokhnach** 2021-05-26 06:26 UTC
Labels: NeedsInfo, NotABug
