### ISSUE TITLE
execute  js error

### ISSUE THREAD

**Issue by herolyle** [appium/appium#12889] opened 2019-07-11 02:27 UTC
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

```
[HTTP] --> POST /wd/hub/session/494092dd-cbc4-4b55-b9f1-d8372a4fb75f/execute
[HTTP] {"sessionId":"494092dd-cbc4-4b55-b9f1-d8372a4fb75f","args":[],"script":"element=document.getElementById(\"Alert-ok\");var abs={x:0,y:0};if(document.documentElement.getBoundingClientRect){abs.x=element.getBoundingClientRect().left;abs.y=element.getBoundingClientRect().top;abs.x+=window.screenLeft+document.documentElement.scrollLeft-document.documentElement.clientLeft;abs.y+=window.screenTop+document.documentElement.scrollTop-document.documentElement.clientTop}else{while(element!=document.body){abs.x+=element.offsetLeft;abs.y+=element.offsetTop;element=element.offsetParent}abs.x+=window.screenLeft+document.body.clientLeft-document.body.scrollLeft;abs.y+=window.screenTop+document.body.clientTop-document.body.scrollTop}abs.x+=element.offsetWidth/2;abs.y+=element.offsetHeight/2;return(abs);"}
[debug] [MJSONWP (494092dd)] Calling AppiumDriver.execute() with args: ["element=document.getElementById(\"Alert-ok\");var abs={x:0,y:0};if(document.documentElement.getBoundingClientRect){abs.x=element.getBoundingClientRect().left;abs.y=element.getBoundingClientRect().top;abs.x+=window.screenLeft+document.documentElement.scrollLeft-document.documentElement.clientLeft;abs.y+=window.screenTop+document.documentElement.scrollTop-document.documentElement.clientTop}else{while(element!=document.body){abs.x+=element.offsetLeft;abs.y+=element.offsetTop;element=element.offsetParent}abs.x+=window.screenLeft+document.body.clientLeft-document.body.scrollLeft;abs.y+=window.screenTop+document.body.clientTop-document.body.scrollTop}abs.x+=element.offsetWidth/2;abs.y+=element.offsetHeight/2;return(abs);",[],"494092dd-cbc4-4b55-b9f1-d8372a4fb75f"]
[debug] [XCUITest] Executing command 'execute'
[debug] [RemoteDebugger] Executing atom 'execute_script'
[debug] [RemoteDebugger] Executing 'execute_script' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var e=this;
[debug] [RemoteDebugger] funct...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Target.sendMessageToTarget","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"message":{"method":"Runtime.evaluate","params":{"e...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Received WebKit data: '{"result":{},"id":3}'
[debug] [RemoteDebugger] Received receipt for message '3'
[debug] [RemoteDebugger] Received WebKit data: '{"method":"Target.dispatchMessageFromTarget","params":{"targetId":"page-1","message":"{\"result\":{\"result\":{\"type\":\"object\",\"value\":{\"status\":13,\"value\":{\"message\":\"null is not an o...'
[debug] [RemoteDebugger] Found method 'Target.dispatchMessageFromTarget' for message '3'
[debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
[debug] [MJSONWP (494092dd)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: null is not an object (evaluating 'element.getBoundingClientRect')
[debug] [MJSONWP (494092dd)]     at errorFromMJSONWPStatusCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:789:10)
[debug] [MJSONWP (494092dd)]     at WebKitRemoteDebugger.convertResult (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-remote-debugger/lib/remote-debugger.js:700:13)
[debug] [MJSONWP (494092dd)]     at WebKitRemoteDebugger.convertResult (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-remote-debugger/lib/webkit-remote-debugger.js:127:18)
[debug] [MJSONWP (494092dd)]     at WebKitRemoteDebugger.convertResult [as execute] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-remote-debugger/lib/remote-debugger.js:660:17)
[debug] [MJSONWP (494092dd)]     at WebKitRemoteDebugger.executeAtom (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-remote-debugger/lib/remote-debugger.js:413:19)
[HTTP] <-- POST /wd/hub/session/494092dd-cbc4-4b55-b9f1-d8372a4fb75f/execute 500 35 ms - 237

```

**Comment by mykola-mokhnach** [comment] 2019-07-11 05:16
Please fill out the issue reporting form properly and provide an example of the client code that causes this error

**Comment by herolyle** [comment] 2019-07-11 06:16
> Please fill out the issue reporting form properly and provide an example of the client code that causes this error
appium : 1.14.0
platform:ios 12.2


`
new WebDriverWait(driver, 30)
                .until(ExpectedConditions.presenceOfElementLocated(By.id("Alert-ok")))
                .click();
`

**Comment by mykola-mokhnach** [comment] 2019-07-11 06:22
@imurchie FYI

**Comment by imurchie** [comment] 2019-07-22 13:38
The JavaScript code being sent in:
```js
function getAbsPosition (element) {
  var abs = {x:0,y:0};
  if (document.documentElement.getBoundingClientRect {
    abs.x = element.getBoundingClientRect().left;
    abs.y = element.getBoundingClientRect().top;
    abs.x += window.screenLeft + document.documentElement.scrollLeft - document.documentElement.clientLeft;
    abs.y += window.screenTop + document.documentElement.scrollTop - document.documentElement.clientTop
  } else {
    while (element != document.body) {
      abs.x += element.offsetLeft;
      abs.y += element.offsetTop;
      element = element.offsetParent
    }
    abs.x += window.screenLeft + document.body.clientLeft - document.body.scrollLeft;
    abs.y += window.screenTop + document.body.clientTop - document.body.scrollTop
  }
  return (abs);
};
return getAbsPosition(document.getElementById("%s"));
```
The error:
```js
null is not an object (evaluating 'element.getBoundingClientRect')
```

I presume the problem is that `document.getElementById("Alert-ok")` must return `null`.

**Comment by mykola-mokhnach** [comment] 2019-07-31 08:55
Closed as third party issue

**Closed by mykola-mokhnach** 2019-07-31 08:55 UTC
Labels: Mobile Safari, ThirdParty
