### ISSUE TITLE
Unable to load package 'opencv4nodejs' when I use find_element_by_image

### ISSUE THREAD

**Issue by dannyke** [appium/appium#15360] opened 2021-05-12 02:48 UTC
## The problem

"Unable to load package 'opencv4nodejs'" shown when I use find_element_by_image method to locator the element

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Desktop OS/version used to run Appium: Mac 10.15.7
* Node.js version (unless using Appium.app|exe): 16.1.0
* Npm or Yarn package manager: npm verison is 7.11.2
* Mobile platform/version under test: iPad 14.4
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

### For appium-doctor check result:
info AppiumDoctor Appium Doctor v.1.16.0
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 16.1.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage. Installed version is: 0.36.0
info AppiumDoctor  ✔ HOME is set to: /Users/dannyke
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
info AppiumDoctor  ✔ opencv4nodejs is installed at: /usr/local/lib. Installed version is: 5.6.0
info AppiumDoctor  ✔ ffmpeg is installed at: /usr/local/bin/ffmpeg. ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
info AppiumDoctor  ✔ mjpeg-consumer is installed at: /usr/local/lib. Installed version is: 2.0.0
info AppiumDoctor  ✔ set-simulator-location is installed
info AppiumDoctor  ✔ idb and idb_companion are installed
WARN AppiumDoctor  ✖ applesimutils cannot be found
info AppiumDoctor  ✔ ios-deploy is installed at: /usr/local/bin/ios-deploy. Installed version is: 1.11.3
info AppiumDoctor ### Diagnostic for optional dependencies completed, one fix possible. ###
info AppiumDoctor
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why applesimutils is needed and how to install it: http://appium.io/docs/en/drivers/ios-xcuitest/
info AppiumDoctor
info AppiumDoctor ###
info AppiumDoctor
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor

## Link to Appium logs

[Debug Logs](https://gist.github.com/dannyke/e2ab658bdd526d48eab34272b3d7793b)

**Comment by mykola-mokhnach** [comment] 2021-05-12 04:23
Duplicate of https://github.com/appium/appium/issues?q=is%3Aissue+opencv4nodejs+is%3Aclosed

**Closed by mykola-mokhnach** 2021-05-12 04:23 UTC
