### ISSUE TITLE
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200

### ISSUE THREAD

**Issue by phemasundar** [appium/appium#14390] opened 2020-05-30 10:10 UTC
## The problem

While executing the multiple automation test cases, randomly below error is coming and failing all the test cases post that.
```org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200```

As this is happening frequently, it is becoming very difficult to maintain the stability of automation test results.

## Environment
* Windows 10
* Appium 1.15.1
* Mobile platform/version under test: 7.1.2
* Real device
* Appium CLI

## Link to Appium logs
https://gist.github.com/phemasundar/a759e44681de1973f11f6e5246e865c5

## Actual error from Server logs file
2020-05-30 14:01:46:706 [HTTP] --> POST /wd/hub/session/33ea45f7-828f-4913-aabd-9f4669ce07d9/elements
2020-05-30 14:01:46:706 [HTTP] {"using":"id","value":"counts_linearlayout_adhoc_item"}
2020-05-30 14:01:48:412 [HTTP] <-- POST /wd/hub/session/33ea45f7-828f-4913-aabd-9f4669ce07d9/elements 200 1704 ms - 12
2020-05-30 14:01:48:412 [HTTP] 
2020-05-30 14:01:48:913 [HTTP] --> POST /wd/hub/session/33ea45f7-828f-4913-aabd-9f4669ce07d9/elements
2020-05-30 14:01:48:914 [HTTP] {"using":"id","value":"counts_linearlayout_adhoc_item"}
2020-05-30 14:01:49:301 [Logcat] Logcat terminated with code 0, signal null
2020-05-30 14:01:50:495 [WD Proxy] Got an unexpected response with status undefined: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
2020-05-30 14:01:50:498 [HTTP] <-- POST /wd/hub/session/33ea45f7-828f-4913-aabd-9f4669ce07d9/elements 500 1585 ms - 592
2020-05-30 14:01:50:499 [HTTP] 
2020-05-30 14:01:50:513 [HTTP] --> GET /wd/hub/session/33ea45f7-828f-4913-aabd-9f4669ce07d9/screenshot
2020-05-30 14:01:50:513 [HTTP] {}
2020-05-30 14:01:51:526 [WD Proxy] Got an unexpected response with status undefined: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
Thanks in advance.

**Comment by mykola-mokhnach** [comment] 2020-05-30 13:50
Possible duplicate of https://github.com/appium/appium/issues/14372

Please also attach the logcat output for the period when connection reset happens.

**Comment by mykola-mokhnach** [comment] 2020-06-02 14:21
Closed because of no response

**Closed by mykola-mokhnach** 2020-06-02 14:21 UTC
Labels: Android, NeedsInfo
