### ISSUE TITLE
iOS - findElementsByAccessibilityId and findElementByName not working

### ISSUE THREAD

**Issue by Rajesh902** [appium/appium#4852] opened 2015-04-03 11:55 UTC
I am doing hybrid app iOS automation using Appium. Not able to find the element using findElementsByAccessibilityId and findElementByName. Only findElementByXpath is working fine. 
Can you tell me why i am not able to use other two properties

driver.findElementsByAccessibilityId("Contact Us") - not working
driver.findElementByName("Contact Us") - not working
driver.findElementByXpath(" //UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIAWebView[1]/UIAStaticText[46]") - working fine

Below is captured from inspector.

**name: Contact Us
type: UIAStaticText
value: 
label: Contact Us
enabled: true
visible: false
valid: true
location: {169, 597}
size: {80, 23}
xpath: //UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIAWebView[1]/UIAStaticText[46]**

**Comment by Jonahss** [comment] 2015-05-08 00:49
Can you post the XML output of the view, when you call `/source`?

**Comment by sebv** [comment] 2015-06-10 05:55
You need to switch context.

**Comment by sebv** [comment] 2015-06-10 05:55
Closing, not a bug.

**Closed by sebv** 2015-06-10 05:55 UTC
Labels: OnGoing
