### ISSUE TITLE
Appium fails to fetch the content of the webview for some of the webpages.

### ISSUE THREAD

**Issue by rakurati7** [appium/appium#13967] opened 2020-02-20 14:41 UTC
## The problem

For few webpages appium fails to fetch the complete page source. For webpages having huge content like bbc.com or washingtonpost.com or nytimes.com on triggering getPageSource webview content is not fetched

## Environment

* Appium version : 1.16.0 beta 3
* Last Appium version that did not exhibit the issue : 1.14
* Desktop OS/version used to run Appium: Mac OS 10.15.3
* Node.js version (unless using Appium.app|exe): 13.5.0
* Npm or Yarn package manager: 6.13.4
* Mobile platform/version under test: iOS 12.4.1 & iOS 13.4 beta 1
* Real device or emulator/simulator: iPhone & iPad
* Appium CLI or Appium.app|exe: Both

## Details

The webview type is wkwebview

## Link to Appium logs
https://gist.github.com/rakurati7/eefd16971db7dc26e6d67b00e21bd5c9

**Comment by imurchie** [comment] 2020-02-20 14:46
What happens if you get it in the webview context?

**Comment by rakurati7** [comment] 2020-02-20 14:53
I tried to get driver.page_source and I see the following difference between working webview and not working

linkedin.com (working):
https://gist.github.com/rakurati7/2521e4e74bda01a4e4803648c1cb00a0

sina.com.cn(fail to fetch webview content):
https://gist.github.com/rakurati7/ef976a2ef58fcd6dfe5f3635f810b24a

**Comment by mykola-mokhnach** [comment] 2020-02-20 15:02
@imurchie I assume we are talking about native context only here. 

@rakurati7 I suppose some web pages might be quite large, so XCTest is unable to get snapshots of their structure within acceptable timeouts. Check the discussion on https://github.com/appium/WebDriverAgent/pull/273 for possible workarounds.

**Comment by rakurati7** [comment] 2020-02-20 15:41
@mykola-mokhnach Thank you I will try to use it and update you if it works

**Comment by rakurati7** [comment] 2020-02-20 17:14
@mykola-mokhnach I tried using 'settings[snapshotMaxDepth]' to 100 still no luck.

**Comment by mykola-mokhnach** [comment] 2020-02-20 18:14
I would rather try to set it to a lower value, not higher

**Comment by rakurati7** [comment] 2020-02-20 18:50
I tried using various values from '20' to '75' still appium fails to fetch the content of the webview. I am sharing here the logs for snapshotMaxDepth of 60

Appium log: https://gist.github.com/rakurati7/ad183cf3b9a3424b888e7e7bab95b12a

 driver.page_source returns: https://gist.github.com/rakurati7/7784e795ff3cb01bb4c0622d6e167ee9

**Comment by mykola-mokhnach** [comment] 2020-02-21 06:33
Unfortunately I don't have any other good solutions to that. Please let us know if you find one

**Comment by mykola-mokhnach** [comment] 2020-02-21 06:33
...or switch to web view context

**Comment by rakurati7** [comment] 2020-02-21 07:53
The application I am testing is chrome iOS app (com.google.chrome.ios) and appium fails to fetch webpage content for large websites. Load the websites (sina.com.cn) and call driver.context I get only [u'NATIVE_APP'].

I am having a same issue when I work with safari app too

**Comment by mykola-mokhnach** [comment] 2020-02-21 13:42
You must make sure the web view is debuggable. It would not be possible to detect it with Appium if it cannot be open with Safari remote debugger. Closed as duplicate of https://github.com/appium/appium/issues/13870

**Closed by mykola-mokhnach** 2020-02-21 13:42 UTC
Labels: ThirdParty, XCUITest
