### ISSUE TITLE
App continually crashing when attempting to run android simulator test. 

### ISSUE THREAD

**Issue by markring** [appium/appium#10060] opened 2018-01-23 20:25 UTC
## The problem

When running Android Simulator test the App crashes with every start, however I am able to run iOS simulator tests without issue. 

## Environment
* mac OS Sierra
* Appium 1.7.2
* Node 6.10.3
* Android 7.0
* Simulator
* Appium CLI

## Details

When running the test the app will open, and then crash. It will attempt to open multiple times before Appium server stops. This behavior only occurs on Android and not iOS simulator. 

## Link to Appium logs
Appium Log File: [GIST](https://gist.github.com/markring/76c1d93fb322a206adda37c3dde73e59) 
## Link to Settings Files
Settings File1: [GIST](https://gist.github.com/markring/e4738a85557c3a3c0290d06f2445c9a0)
Settings File2: [GIST](https://gist.github.com/markring/cdd560181851d0407a8bc43d0d33c7cc)

**Comment by mykola-mokhnach** [comment] 2018-01-23 20:37
Duplicate of https://github.com/appium/appium/issues/10027

**Closed by mykola-mokhnach** 2018-01-23 20:37 UTC

**Comment by markring** [comment] 2018-01-24 00:44
How is this a duplicate of 10027?
