### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure

### ISSUE THREAD

**Issue by baghel087** [appium/appium#14124] opened 2020-03-30 12:39 UTC
## The problem

While opening application in ios simulator for inspection i am getting error:
An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message: 2020-03-30 15:34:06.364 xcodebuild[54091:2710503] Error Domain=IDEFoundationErrorDomain Code=1 "Cannot launch simulated executable: no file found at /Users/rakesh.baghel/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app" UserInfo={NSLocalizedDescription=Cannot launch simulated executable: no file found at /Users/rakesh.baghel/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app} Test session results, code coverage, and logs: /Users/rakesh.baghel/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2020.03.30_15-34-00-+0530.xcresult Testing failed: Building for iOS Simulator, but the linked framework 'CocoaAsyncSocket.framework' was built for tvOS + tvOS Simulator. WebDriverAgentRunner: WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: Cannot launch simulated executable: no file found at /Users/rakesh.baghel/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app)) ** TEST EXECUTE FAILED ** Testing started on 'iPhone 8 Plus

**Comment by mykola-mokhnach** [comment] 2020-03-30 14:49
Duplicate of https://github.com/appium/appium/issues/14102

**Closed by mykola-mokhnach** 2020-03-30 14:49 UTC
