### ISSUE TITLE
Unable to switch to WebView in hybrid app in android- not found. Is it installed? - error

### ISSUE THREAD

**Issue by dineshchakravarthy5** [appium/appium#9472] opened 2017-10-17 14:33 UTC
## The problem

Unable to switch to Webview in hybrid app in Android, getting error while using context("WebView").

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Win 10
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: Android 5.0/5.1.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.exe
* Appium client : java-client-5.0.0-BETA8
* Chrome Version/Chrome driver: Chrome 60.0.3112.116/ ChromeDriver 2.33
## Details

Unable to switch to webview , instead giving "org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Command 'C:\Users\user\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win' not found. Is it installed? (WARNING: The server did not provide any stacktrace information)" error.

But Appium able to identify WebView , using getContextHandles able to print NATIVE_APP, WEBVIEW_chrome. but throwing error when tried to switch to webview using "((AndroidDriver) driver).context(contextName);"

if I comment "chromedriverExecutable" capability mentioned below execution is taking much longer at context("WebView") and throws "Encountered internal error running command: Error: chrome not reachable" error.

Error: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: chrome not reachable

## Link to Appium logs

https://gist.github.com/dineshchakravarthy5/b93d287b7fee4def2c479d19c4dbf475

## Code To Reproduce Issue [ Good To Have ]

  capabilities.setCapability("deviceName", deviceName);
				capabilities.setCapability("platformName", platform);
				capabilities.setCapability("platformVersion", platformVersion);
				if (app != null) {
					File appFile = new File(app);
					capabilities.setCapability("app", appFile.getAbsolutePath());
				}
				capabilities.setCapability("appPackage", appPackage);
				capabilities.setCapability("appActivity", activityName);
				capabilities.setCapability("unicodeKeyboard", true);
				capabilities.setCapability("resetKeyboard", true);
		        capabilities.setCapability("noReset", false);
	            capabilities.setCapability("fullReset", false);
	         capabilities.setCapability("chromedriverExecutable", "C:\\Users\\user\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\node_modules\\appium-chromedriver\\chromedriver\\win");
		        try {
					this.driver = new AndroidDriver(new URL(appiumUrl+ "/wd/hub/"), capabilities);
				} catch (MalformedURLException e) {
					basetestsuite.extent.addSystemInfo("fail",
							"Either appium is not running or Server port addresses are not matching, Check appium settings");
					basetestsuite.extent.addSystemInfo("warning", e.toString());
				}

=============
  Set<String> contextNames = ((AppiumDriver) driver).getContextHandles();
        for (String contextName : contextNames) {
            System.out.println(contextNames); 
            	if(contextName.contains("WEBVIEW")){
            		
            		((AppiumDriver) driver).context(contextName);
            	}
        }

**Comment by mykola-mokhnach** [comment] 2017-10-17 14:53
Duplicate of https://github.com/appium/appium/issues/9469

**Comment by imurchie** [comment] 2017-10-17 15:54
There is something wrong with the figuring out the chromedriver executable. Does the file `C:\Users\user\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe` exist?

You can try a temporary workaround of setting the `chromedriverExecutable` desired capabilities to `C:\Users\user\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe` (assuming it exists).

**Comment by imurchie** [comment] 2017-10-17 15:56
Sorry, just looked at the caps you were using. You are passing in the wrong `chromedriverExecutable` capability. Make sure it points to the actual executable, not a directory.

**Comment by dineshchakravarthy5** [comment] 2017-10-18 05:19
@imurchie 
I tried setting the path to executable chromeDriver.  now I am getting chrome not reachable error.
I am using  Chrome 60.0.3112.116/ ChromeDriver 2.33 - Android 5.0: win10

Please find below Appium server log:
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"10.0.10586\"}}}"
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"air.com.app.mobile.cash","androidUseRunningApp":true,"androidDeviceSerial":"YHWSHYYT695H9LJV"}}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"00f720a0d1d08ff4c900f0a2653dec45","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.10586 x86_64)"}}
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"air.com.ace2three.mobile.cash","androidUseRunningApp":true,"androidDeviceSerial":"YHWSHYYT695H9LJV"}}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"3ed3dfc0ee128b8b04366f6222c93385","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.10586 x86_64)"}}
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"air.com.ace2three.mobile.cash","androidUseRunningApp":true,"androidDeviceSerial":"YHWSHYYT695H9LJV"}}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"937d63f7fbc527ede0d28c151260471a","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.10586 x86_64)"}}
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"air.com.ace2three.mobile.cash","androidUseRunningApp":true,"androidDeviceSerial":"YHWSHYYT695H9LJV"}}}
[JSONWP Proxy] Got response with status 200: **{"sessionId":"358953872473012bd20f9a04cf2e0682","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.10586 x86_64)"}}
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[Chromedriver] Changed state to 'stopped'
[Chromedriver] Error: chrome not reachable**
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.10586 x86_64)
    at Chromedriver.callee$2$0$ (C:\Users\dineshsoma\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:197:15)
    at tryCatch (C:\Users\dineshsoma\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\dineshsoma\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\dineshsoma\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\dineshsoma\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
 Error: chrome not reachable
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.10586 x86_64)
    at Chromedriver.callee$2$0$ (C:\Users\dineshsoma\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:197:15)
    at tryCatch (C:\Users\dineshsoma\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\dineshsoma\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\dineshsoma\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\dineshsoma\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP] Encountered internal error running command: Error: chrome not reachable
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.10586 x86_64)
    at Chromedriver.callee$2$0$ (C:\Users\dineshsoma\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:197:15)
    at tryCatch (C:\Users\dineshsoma\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\dineshsoma\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\dineshsoma\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\dineshsoma\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)

**Comment by dineshchakravarthy5** [comment] 2017-10-23 11:49
Hi @imurchie,

Is there any update or work around for the above issue ?
Thanks in advance.

**Comment by saikrishna321** [comment] 2018-02-16 04:40
@dineshchakravarthy5 can you please try with the latest appium server and latest chrome

**Closed** 2018-04-30 15:00 UTC
Labels: Android, NotABug
