### ISSUE TITLE
bug: XCUIElementTypeAlert: not visible any more

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#19874] opened 2024-03-08 13:24 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am managing iOS alerts manually in code. While updating xcuitest driver found out that such alerts are not visible any more.
To check issue i did following test:
 - run app
 - stop on screen with alert (allow location or similar)
 - print `driver.getPageSource()` result

I got results:

```
// alerts EXIST in page source!
xcuitest@5.7.0
xcuitest@5.10.0
xcuitest@5.12.0
xcuitest@5.13.0

// alerts ABSENT in page source!
xcuitest@5.14.0
xcuitest@5.15.0
xcuitest@6.0.0
xcuitest@7.3.0
```

### Expected Behavior

alerts should be visible in pagesource

### Minimal Reproducible Example

To check issue i did following test:
 - run app
 - stop on screen with alert (allow location or similar)
 - print `driver.getPageSource()` result

### Environment

- Operating system: macOS
- Appium server version (output of `appium --version`): no matter, with 2.1.3 or 2.5.1
- Appium driver(s) and their version(s): mentioned in behavior
- Last component(s) version which did _not_ exhibit the problem: mentioned in behavior
- Platform and version under test: iOS
- Real device or emulator/simulator: real phone

**Comment by mykola-mokhnach** [comment] 2024-03-08 16:10
Duplicate of https://github.com/appium/appium/issues/19786

**Closed by mykola-mokhnach** 2024-03-08 16:10 UTC

**Comment by amedvedjev** [comment] 2024-03-11 10:54
@mykola-mokhnach and how now we can accept alert that text could be one of ?
```
"(name == 'Allow While Using App' OR name == 'Allow' OR name == 'OK' OR label == 'Yes')"
```

**Comment by NBS-LLC** [comment] 2024-06-06 00:12
FYI- if you are using a version of the xcuitest driver > 5 the following setting might help (worked for me):

`respectSystemAlerts`

> Currently we detect the app under test as active if XCTest returns XCUIApplicationStateRunningForeground state for it. In case the app under test is covered by a system alert from the Springboard app this approach might be confusing as we cannot interact with it unless an alert is properly handled. If this setting is set to true (by default it is false) then it forces WDA to verify the presence of alerts shown by Springboard and return the latter while performing the automated app detection. It affects the performance of active app detection, but might be more convenient for writing test scripts (e.g. eliminates the need of proactive switching between system and custom apps). Also, this behavior emulates the legacy active application detection logic before version 6 of the driver.

https://appium.github.io/appium-xcuitest-driver/latest/reference/settings/

I added this setting via my capabilities:

`'appium:settings[respectSystemAlerts]': 'true'`

https://appium.io/docs/en/latest/guides/settings/#initializing-settings-via-capabilities
