### ISSUE TITLE
NoSuchElementException when using `ExpectedConditions.visibilityOf` with appium 2.0.

### ISSUE THREAD

**Issue by attrideepak** [appium/appium#16424] opened 2022-02-08 09:14 UTC
## The problem

Getting NoSuchElementException when using `ExpectedConditions.visibilityOf` with appium 2.0.

## Environment

* Appium version (or git revision) that exhibits the issue: v2.0.0-beta.25 (REV 5b3d188b83f27ec31d97f3f3e6e49220e09b6985)
* Last Appium version that did not exhibit the issue (if applicable): 1.22.0
* Desktop OS/version used to run Appium: MAC OS BigSur version 11.6.3
* Node.js version (unless using Appium.app|exe): v17.3.0
* Npm or Yarn package manager: 8.3.0
* Mobile platform/version under test: Android 
* Real device or emulator/simulator: Android Emulator API 29
* Appium CLI or Appium.app|exe: Appium CLI

## Details
I am using appium v2.0.0-beta.25 and appium java client 7.6.0 with espresso driver. I am using `ExpectedConditions.visibilityOf` to wait for the elements and it gives NoSuchElementException.

I have tried the same code with appium v1.22(Desktop application) and appium java client 7.6.0 with espresso driver and it works fine.

I have also tried the same code with appium v1.22(Desktop application) and appium java client 7.6.0 with UIAutomator2 driver and it works fine.

Removing webdriverwait and adding Thread.Sleep with appium v2.0.0-beta.25 and appium java client 7.6.0 with espresso driver also wotks fine.

## Link to Appium logs

[Appium v1.22(Desktop App) logs](https://gist.github.com/attrideepak/bde24e876a992802a00abce10e8eb9a6) :

[Appium v2.0.0-beta.25 logs:](https://gist.github.com/attrideepak/108a1b242f9964d87ff79a648c060cb4)

## Code To Reproduce Issue 
[Sample Code](https://gist.github.com/attrideepak/0b09a00e2533f47df13ee91edfa915cb)

**Comment by mykola-mokhnach** [comment] 2022-02-08 09:26
Try to wait for the element presence first and then visibility

**Comment by mykola-mokhnach** [comment] 2022-02-08 09:46
try to print the page source before locating the element and make sure it's there

**Comment by attrideepak** [comment] 2022-02-08 10:22
Printed pageSource before 
`wait.until(ExpectedConditions.presenceOfElementLocated(By.id("email_verify_subtitle")));`
element is not there.

**Comment by mykola-mokhnach** [comment] 2022-02-08 11:14
If the element is not present in page source then the fact it is not found is not a bug, but rather the expected result.

It would be interesting to see the difference in logs between `wait.until(ExpectedConditions.presenceOfElementLocated(By.id("email_verify_subtitle")));` and `wait.until(ExpectedConditions.presenceOfAllElementsLocatedBy(By.id("email_verify_subtitle")));` because in theory both calls should return similar results

**Comment by attrideepak** [comment] 2022-02-08 11:18
Will add logs for both

**Comment by attrideepak** [comment] 2022-02-08 11:46
ExpectedConditions.presenceOfAllElementsLocatedBy: [Logs](https://gist.github.com/attrideepak/efef98665261339212508e90df0d47c0)
Corresponding Java Code:
 ```
public void sampleTest() {
        System.out.println("Driver session create successfully");
        WebDriverWait wait = new WebDriverWait(driver, 5);
        MobileElement emailEditBox = driver.findElementById("txt_email");
        emailEditBox.sendKeys("deepak-stage-001.user-xxxx@test.yyyy.com");
        driver.findElementById("btn_next").click();
        wait.until(ExpectedConditions.presenceOfAllElementsLocatedBy(By.id("email_verify_subtitle")));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("email_verify_subtitle")));
        WebElement webElement = driver.findElement(By.id("email_verify_subtitle"));
        System.out.println(webElement.getText());
}
```
ExpectedConditions.presenceOfElementLocated: [Logs](https://gist.github.com/attrideepak/a974e6c615ea1d0fdb2b1c7836a99916)
Corresponding Java Code:
```
public void sampleTest() {
        System.out.println("Driver session create successfully");
        WebDriverWait wait = new WebDriverWait(driver, 5);
        MobileElement emailEditBox = driver.findElementById("txt_email");
        emailEditBox.sendKeys("deepak-stage-001.user-xxxx@test.yyyy.com");
        driver.findElementById("btn_next").click();
        wait.until(ExpectedConditions.presenceOfElementLocated(By.id("email_verify_subtitle")));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("email_verify_subtitle")));
        WebElement webElement = driver.findElement(By.id("email_verify_subtitle"));
        System.out.println(webElement.getText());
}
```

**Comment by mykola-mokhnach** [comment] 2022-02-08 15:22
AFAIK this is a bug in Selenium API. It does not properly handle NoSuchElementException in `presenceOfElementLocated` expected condition. As a workaround you could create your own fluent wait similar to
```
 *   // Waiting 30 seconds for an element to be present on the page, checking
 *   // for its presence once every 5 seconds.
 *   Wait<WebDriver> wait = new FluentWait<WebDriver>(driver)
 *       .withTimeout(30, SECONDS)
 *       .pollingEvery(5, SECONDS)
 *       .ignoring(NoSuchElementException.class);
 *
 *   WebElement foo = wait.until(new Function<WebDriver, WebElement>() {
 *     public WebElement apply(WebDriver driver) {
 *       return driver.findElement(By.id("foo"));
 *     }
 *   });
```

**Comment by mykola-mokhnach** [comment] 2022-02-10 08:15
Closed as not a server issue

**Closed by mykola-mokhnach** 2022-02-10 08:15 UTC
Labels: NotABug, NeedsInfo
