### ISSUE TITLE
Error on starting Appium server from Java code on MAC. 

### ISSUE THREAD

**Issue by Hashili** [appium/appium#10404] opened 2018-03-23 10:04 UTC
## The problem

Error on starting Appium server from Java code on MAC.  

## Environment

* Appium version (or git revision) that exhibits the issue: appium CLI 1.7.2
* Node.js version (unless using Appium.app|exe): 8.
* Mobile platform/version under test: Iphone iOS 11.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
2018-03-22 18:38:44 INFO  Mobile:- Getting driver properties....
2018-03-22 18:38:44 INFO  Mobile:- Getting driver properties done!
2018-03-22 18:38:44 INFO  Mobile:- Starting appium server on 0.0.0.0:4724, Please wait...!
[Appium] Welcome to Appium v1.7.2
[Appium] Non-default server args:
[Appium]   port: 4724
[Appium]   sessionOverride: true
[Appium] Appium REST http interface listener started on 0.0.0.0:4724
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.2","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 20 ms - 72 
2018-03-22 18:38:48 INFO  Mobile:- Appium server started!
2018-03-22 18:38:48 INFO  Mobile:- Setting driver capability....
2018-03-22 18:38:48 INFO  Mobile:- Setting driver capability done!
2018-03-22 18:38:48 INFO  Mobile:- Getting driver....
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/EYMTT/Documents/workspace/EYMobileFrameworkV2/resources/aut/ClaimAdjuster.ipa","platformVersion":"11.2","automationName":"XCUITest","browserName":"null","platformName":"iOS","udid":"f5ad0846a74171f84e0fad4c276b2678582a5718","deviceName":"AppiumiPhone"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"/Users/EYMTT/Documents/workspace/EYMobileFrameworkV2/resources/aut/ClaimAdjuster.ipa","platformVersion":"11.2","automationName":"XCUITest","browserName":"null","platformName":"iOS","udid":"f5ad0846a74171f84e0fad4c276b2678582a5718","deviceName":"AppiumiPhone"},"requiredCapabilities":{},"alwaysMatch":{"browserName":"null","platformName":"iOS"},"firstMatch":[]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/EYMTT/Documents/workspace/EYMobileFrameworkV2/resources/aut/ClaimAdjuster.ipa","platformVersion":"11.2","automationName":"XCUITest","browserName":"null","platformName":"iOS","udid":"f5ad0846a74171f84e0fad4c276b2678582a5718","deviceName":"AppiumiPhone"},{},{"desiredCapabilities":{"app":"/Users/EYMTT/Documents/workspace/EYMobileFrameworkV2/resources/aut/ClaimAdjuster.ipa","platformVersion":"11.2","automationName":"XCUITest","browserName":"null","platformName":"iOS","udid":"f5ad0846a74171f84e0fad4c276b2678582a5718","deviceName":"AppiumiPhone"},"requiredCapabilities":{},"alwaysMatch":{"browserName":"null","platformName":"iOS"},"firstMatch":[]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1521724128517 (18:38:48 GMT+0530 (IST))
[Appium] Merged W3C capabilities {"desiredCapabilities":{"app":"/Users/EYMTT/Doc... into desiredCapabilities object {"app":"/Users/EYMTT/Documents/workspace/EYMobi...
[Appium] Creating new XCUITestDriver (v2.64.0) session
[Appium] Capabilities:
[Appium]   app: /Users/EYMTT/Documents/workspace/EYMobileFrameworkV2/resources/aut/ClaimAdjuster.ipa
[Appium]   platformVersion: 11.2
[Appium]   automationName: XCUITest
[Appium]   browserName: null
[Appium]   platformName: iOS
[Appium]   udid: f5ad0846a74171f84e0fad4c276b2678582a5718
[Appium]   deviceName: AppiumiPhone
[BaseDriver] Session created with session id: 0f9ae5cc-59b1-4132-b9bf-fbc06c066e57
[debug] [XCUITest] Current user: 'EYMTT'
[debug] [XCUITest] Unable to get version of libimobiledevice: Command 'brew' not found. Is it installed?
[debug] [XCUITest] Xcode version set to '9.2' (tools v9.2.0.0.1.1510905681)
[debug] [XCUITest] iOS SDK Version set to '11.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1521724128712 (18:38:48 GMT+0530 (IST))
[XCUITest] The 'idevice_id' program is not installed. If you are running a real device test it is necessary. Install with 'brew install libimobiledevice --HEAD'
[debug] [XCUITest] Available devices: 
[XCUITest] Error: Unknown device or simulator UDID: 'f5ad0846a74171f84e0fad4c276b2678582a5718'
    at XCUITestDriver.determineDevice$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:622:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Unknown device or simulator UDID: 'f5ad0846a74171f84e0fad4c276b2678582a5718'

## Code To Reproduce Issue [ Good To Have ]

	public static void appiumStart(String serverURL, String APPIUM_PORT, String APPIUM_JS) throws IOException {

		LogUtil.info("Starting appium server on "+serverURL+":"+APPIUM_PORT+", Please wait...!");

		try {
			builder = new AppiumServiceBuilder();
			builder.withAppiumJS(new File(APPIUM_JS));
			builder.withIPAddress(serverURL);
			builder.usingPort(Integer.parseInt(APPIUM_PORT));
			builder.withArgument(GeneralServerFlag.SESSION_OVERRIDE);

			//Start the server with the builder
			appiumService = AppiumDriverLocalService.buildService(builder);
			appiumService.start();
		}catch(Exception e) {
			LogUtil.error("Error on Appium server start! : "+e.getMessage());
		}

		LogUtil.info("Appium server started!");
	}

**Comment by mykola-mokhnach** [comment] 2018-03-23 10:05
Duplicate of https://github.com/appium/appium/issues/10376

**Closed by mykola-mokhnach** 2018-03-23 10:05 UTC

**Comment by Hashili** [comment] 2018-03-23 10:39
@mykola-mokhnach 

The issue still exists even after updating to latest client version


<dependency>
    <groupId>io.appium</groupId>
    <artifactId>java-client</artifactId>
    <version>6.0.0-BETA4</version>
</dependency>

**Comment by vikramvi** [comment] 2018-03-23 11:01
@Hashili please file this issue under https://github.com/appium/java-client
