### ISSUE TITLE
Does WebDriverAgentRunner generally support iOS 17 or not?

### ISSUE THREAD

**Issue by El-hombre-del-fuego** [appium/appium#19471] opened 2023-12-05 08:08 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On iOS 17: 
When I build the latest release (https://github.com/appium/WebDriverAgent/releases/tag/v5.15.3) with Xcode 15, I get the following error: https://github.com/appium/WebDriverAgent/issues/817

When I install an Xcode 14 build, I get following error:
_Please make sure if the at.handyparken.WebDriverAgentRunner.xctrunner exists and it is launchable_

In both cases, the WebDriverAgentRunner ist not launchable! 
However, the Xcode 14 build works with iOS 16.

### Expected Behavior

That WebDriverAgentRunner starts on iOS 17.

### Minimal Reproducible Example

none

### Environment

- Operating system: MacOS Sonoma 14.1.2
- Appium server version (output of `appium --version`): 2.1.3
- Appium driver(s) and their version(s): xcuitest@5.7.0 (automationName 'XCUITest'), uiautomator2@2.29.5 (automationName 'UiAutomator2')
- Appium plugin(s) and their version(s): No plugins have been installed.
- Node.js version (output of `node --version`): v18.18.0
- `npm` version (output of `npm --version`): 9.8.1
- Last component(s) version which did _not_ exhibit the problem: Xcode 14 build on iPhone 8Plus, iOS 16
- Platform and version under test:
- Real device or emulator/simulator: iPhone 12 (Real device)

### Link to Appium Logs

[appium.log](https://github.com/appium/appium/files/13558261/appium.log)

**Comment by mykola-mokhnach** [comment] 2023-12-05 08:42
Please fill out the issue report properly and provide the server log with xcodebuild logging enabled

**Comment by mykola-mokhnach** [comment] 2023-12-05 08:43
The error from https://github.com/appium/WebDriverAgent/issues/817 has nothing to do with WDA build. It is probably a duplicate of https://github.com/appium/appium/issues/19206

**Comment by El-hombre-del-fuego** [comment] 2023-12-05 09:59
Filled out and appium.log added.

**Comment by mykola-mokhnach** [comment] 2023-12-05 10:17
> [debug] [XCUITestDriver@cbb1]     "appium:usePreinstalledWDA": true,

This is definitely the duplicate of the above issue. Unfortunately the usage of the precompiled binary is not possible in iOS 17 unless somebody could add the appropriate iOS17 support.

Closed as duplicate

**Closed by mykola-mokhnach** 2023-12-05 10:17 UTC
Labels: Needs Info
