### ISSUE TITLE
Appium end session during execution without code error  

### ISSUE THREAD

**Issue by AliceMeng0821** [appium/appium#14171] opened 2020-04-10 10:20 UTC
## The problem

During execute scripts , encounter error "connect ECONNREFUSED 127.0.0.1:4723" 
in each execution , this error keeping happened after the scripts executed 3 mins later , I have try on different test scripts and devices .the failed time is same for each run and test scenario.   I  checked the scripts , there is no error in scripts level .

This issue happened on BitBar (mobile cloud service ) , My scripts working well on Android in the same framework and the same scripts working fine in my local on simuator , no 'connect ECONNREFUSED 127.0.0.1:4723'  error

## Environment
* Appium version:  v1.16.0
* xcode : 11.3
 * Jest -cucumber
*  Javascripts
*  wd.js

## Details
package.json:

{
  "name": "jest-cucumber",
  "version": "1.0.0",
  "description": "Execute Gherkin scenarios in Jest",
  "main": "dist/src/index.js",
  "scripts": {
    "test": "jest --color"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@babel/plugin-transform-runtime": "^7.6.0",
    "@babel/runtime": "^7.6.0",
    "@types/jest": "^24.0.7",
    "@types/node": "^11.9.4",
    "babel-core": "^6.26.0",
    "babel-jest": "^24.1.0",
    "babel-loader": "^8.0.6",
    "babel-plugin-module-resolver": "^3.1.0",
    "babel-preset-env": "^1.6.1",
    "babel-runtime": "^6.26.0",
    "gherkin": "^5.1.0",
    "got": "^9.6.0",
    "hashmap": "^2.4.0",
    "jest": "^24.1.0",
    "jest-cucumber": "^2.0.11",
    "json-server": "^0.15.1",
    "mssql": "^5.1.0",
    "nock": "^11.3.5",
    "node-cmd": "^3.0.0",
    "selenium-webdriver": "^4.0.0-alpha.5",
    "ts-jest": "^24.0.0",
    "tslint": "^5.10.0",
    "typescript": "^3.3.3",
    "wd": "^1.12.1",
    "webpack": "^4.40.2"
  },
  "jest": {
    "transform": {
      "^.+\\.jsx?$": "babel-jest"
    },
    "testMatch": [
      "**/*.steps.js"
    ],
    "moduleFileExtensions": [
      "js",
      "jsx"
    ]
  },
  "devDependencies": {
    "@babel/cli": "^7.6.0",
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.6.0",
    "babel-preset-es2015": "^6.24.1",
    "tap": "^14.6.5"
  }
}

## Link to Appium logs
https://gist.github.com/AliceMeng0821/01ef03e55ee2499816f0bcfd1d8deebb

##Link to Console logs : 
https://gist.github.com/AliceMeng0821/60bbeb7158b7bd87b619f3166a9e357a
##  one of test scripts 
https://gist.github.com/AliceMeng0821/4066030c38a59060bd9ee088d859541b

**Comment by mykola-mokhnach** [comment] 2020-04-10 13:42
I don't observe any errors in the server log. Did you try to connect to the server manually after the issue happens?

Also, consider using the most recent server version.

**Comment by mykola-mokhnach** [comment] 2020-04-10 13:43
This is also very likely to be a cloud issue

**Comment by AliceMeng0821** [comment] 2020-04-11 01:44
Thanks mykola-mokhnach  for your quick response .

As App I tested need 3-4 mins to launched .  I 'm suspected something went wrong on capabilities . 
So I try to increase the newCommandTimeout to 3600000 , but got the error right after XCUITestDriver session created. 
'[Appium] Closing session, cause was 'New Command Timeout of 3600000 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability''

here is the appium log : https://gist.github.com/AliceMeng0821/4808b51214e6de3df3e7f766e37c02da

Is there any maximum limit to the value of 'newCommandTimeout' ?

Thanks 
Alice

**Comment by mykola-mokhnach** [comment] 2020-04-11 02:27
You may set the new command timeout to zero in order to cancel the timeout, although I'd rather try to upgrade the server first.

> As App I tested need 3-4 mins to launched

Does it also need so much time for the startup being executed manually? Have you tried the solution from https://github.com/appium/appium/issues/12444

**Comment by mykola-mokhnach** [comment] 2020-04-11 02:36
btw, is so long iosInstallPause really necessary?

**Comment by AliceMeng0821** [comment] 2020-04-11 11:10
Hi mykola-mokhnach , Thanks for your information

I remove the iosInstallPause time and update the newcommandtimeout to 0 , add wdaEventloopIdleDelay :3  into capabilities, unlucky, still got the same error .
Is there any other ways i can try to workaround 
https://gist.github.com/AliceMeng0821/edf503b71e1a549b4ebebcda00cecaae
https://gist.github.com/AliceMeng0821/e65cdebdbe3f2e22f8851678e5e3efda

Thanks 
Alice

**Comment by mykola-mokhnach** [comment] 2020-04-11 11:14
>  add wdaEventloopIdleDelay :3 into capabilities, unlucky, still got the same error 

This cap usually works in combination with waitForQuiescence

Also, I don't observe the issue in the recent log anymore after newCommandTimeout has been set to zero. The disconnection happens on the client side now

**Comment by AliceMeng0821** [comment] 2020-04-11 11:45
in Appium log , no error show , 
in the console log , I can see the error occured 
 test Error: [element.click()] connect ECONNREFUSED 127.0.0.1:4723

**Comment by AliceMeng0821** [comment] 2020-04-11 11:46
I will add the waitForQuiescence, and have a try 
Thanks 
Alice

**Comment by mykola-mokhnach** [comment] 2020-04-11 11:49
> test Error: [element.click()] connect ECONNREFUSED 127.0.0.1:4723

It is practically impossible to know the exact reason for client disconnection. `ECONNREFUSED` means the client cannot establish the connection to the server. There might be multiple reasons for this including network issues or third-party software interference.

**Comment by AliceMeng0821** [comment] 2020-04-11 12:00
yes , the error log too high level . 
The wired is , this issue will happened in 3 mins when the scripts start execute.  
I have try run several different test scripts , all has the same issue  and the same scripts run in my local on simulator, no error ,working fine .  

Thanks 
Alice

**Comment by AliceMeng0821** [comment] 2020-04-11 12:04
I suspect if any things  wrong in my capabilities setting . Could you please help to review
 platformName: 'iOS',
  automationName: 'XCUITest',
  deviceName: 'Local Device',   /// this is the required from cloud 
 // platformVersion: process.env.PLATFORM_VERSION,
  waitForAppScript: 'true',
  autoAcceptAlerts: 'true',
  app:path.resolve('application.ipa'),
  //showIOSLog: "false",
  //connectHardwareKeyboard: 'false',
  udid: process.env.IOS_UDID,
  newCommandTimeout:0,
  wdaEventloopIdleDelay:3,
  waitForQuiescence:'false',
 // includeNonModalElements:'true',
  wdaLaunchTimeout:1800000,
  wdaConnectionTimeout:1800000,

**Comment by mykola-mokhnach** [comment] 2020-04-11 12:57
The capabilities look reasonable except of boolean values should not be strings. I don't think they have to do with the actual connection reset issue.

**Comment by AliceMeng0821** [comment] 2020-04-11 13:17
Thanks for help review the capabilities setting.

I call http://127.0.0.1:8100/status  after the error 'ECONNREFUSED 127.0.0.1:4723', catched 
got   Error: connect ECONNREFUSED 127.0.0.1:8100, 
does it mean the appium session been terminated or still has some possible on third-party software interference issue

Thanks 
Alice

**Comment by mykola-mokhnach** [comment] 2020-04-11 14:14
This means that Appium server is fine, but the webdriver agent on the device does not respond anymore. Perhaps, there is more information in device logs about why that happens

**Comment by AliceMeng0821** [comment] 2020-04-11 15:41
Thanks for your help to fond the real issue on .
So is there any capabilities can be used to rebuild and launch the web driver agents when the webdriver agent no response

Thanks 
Alice

**Comment by mykola-mokhnach** [comment] 2020-04-11 15:50
There is `commandTimeouts` cap, which stops the driver if proxy timeout happens. Then it would be necessary to completely restart the session/create a new driver instance

**Comment by AliceMeng0821** [comment] 2020-04-12 08:09
Hi  mykola-mokhnach ,
Thanks for your feedback . I added the commandTimeout to my capnow . Is there any required for this value . do i need to keep the this value same with newCommandTimeout ?
I added showIOSLog to the caps . and i found there are some error in the logs during uninstall the app from device after the appium server start . some times it take long time .
Today i have try to execute several test on the Cloud , all failed right after the uninstall app or install app steps .  the execute terminated before the WDA session launched.  .
Does this related to some time outs time i setting not correctly ??, please help to take a look , below is the appium log 

https://gist.github.com/AliceMeng0821/7f4f8b40190ba91ac2 bfad83b00020ee

Thanks 
Alice

**Comment by AliceMeng0821** [comment] 2020-04-12 08:15
oh, in my scripts , i start the appium with--session-override 
'appium -a 127.0.0.1 -p 4723 --session-override',

add after the appium server start , wait for 90000 ms  then start the init the driver , after the driver created , wait for 12000 ms thefore start execute test scritps

**Comment by AliceMeng0821** [comment] 2020-04-12 11:18
I think my issue is quite similar with this issue
https://github.com/facebookarchive/WebDriverAgent/issues/1046

The app take long time to launch and then scripts start to execute ,but within 3 mins , disconnect to WDA

**Comment by mykola-mokhnach** [comment] 2020-04-12 11:46
It could be that the application under test is designed purely, so that it hugs the main event loop and xctest daemon is unable to run anything on it and has to wait forever until the timeout happens. Do you observe similar delays if native xcui tests are executed on the app?

**Comment by AliceMeng0821** [comment] 2020-04-13 04:33
The app is the first app in my company and maybe has some poor designed , app i tested is designed with a video in launch page , it will auto play the video . This will take sometime to launch. I execute the scripts in my local on simulator ,working fine . the scripts can execute from begging to the end . not like the execution on cloud real devices , terminated in 3 mins after the scripts execute . 

I have one doubt , for the wda command time out or appium time out , is there any delay to end the session . because in my scenario, the scripts already start to run and then terminated in 3 mins 

Thanks
Alice

**Comment by mykola-mokhnach** [comment] 2020-04-13 06:19
>  it will auto play the video 

This might be the cause of the long startup. I would ask developers to add a flag/workaround to disable the video playback. It will allow to shorten app startup time significantly. 

>  the scripts can execute from begging to the end . not like the execution on cloud real devices , terminated in 3 mins after the scripts execute .

It confirms again, that the issue does not lie in Appium, but the cloud provider. Consider contacting their customer support.

Closed as not an issue.

**Closed by mykola-mokhnach** 2020-04-13 06:19 UTC
Labels: NeedsInfo, NotABug
