### ISSUE TITLE
Ignore 'capabilities' if it isn't a plain JS object

### ISSUE THREAD

**Issue by senevit4** [appium/appium#9984] opened 2018-01-15 11:01 UTC
## The problem

Got "InvalidArgumentError: The capabilities argument was not valid for the following reason(s): "capabilities" must be a JSON object." while if trying to launch tests or launch inspector from desktop app on the latest appium beta  1.7.2-beta 5 installed at  january 15, 2018.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2-beta 5 installed at  january 15, 2018.
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2-beta 5 installed at  january 12, 2018.
* Desktop OS/version used to run Appium: Mac OS X 10.13.2
* Node.js version (unless using Appium.app|exe): 9.4.0
* Mobile platform/version under test: iOS 11
* Real device or emulator/simulator: real device.
* Appium CLI or Appium.app|exe: Both cli and app version 1.3.1

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/senevit4/8e3815552d4a7b7edfb663e264415aae

**Comment by mykola-mokhnach** [comment] 2018-01-15 12:49
Possible duplicate of https://github.com/appium/appium/issues/9981

**Comment by senevit4** [comment] 2018-01-15 13:30
On XCUITestDriver v2.64.0 there is no such error. Everything els is the same.

**Comment by senevit4** [comment] 2018-01-15 13:53
On XCUITestDriver v2.65.0 error is present.
https://gist.github.com/senevit4/5ba245d80adbc4bd61966392716a0d0a

**Comment by mykola-mokhnach** [comment] 2018-01-15 13:56
@senevit4 Can you please attach the full log?

**Comment by mykola-mokhnach** [comment] 2018-01-15 14:06
@dpgraham Can you please check the recent log?

**Comment by dpgraham** [comment] 2018-01-15 19:36
I'm working on a fix for this. I'll let you know when it's ready. Hopefully it will be out today.

**Closed** 2018-01-16 00:48 UTC
Labels: Bug, P0

**Comment by seavan** [comment] 2018-01-16 03:33
@dpgraham so is it fixed? i am getting this issue on all our circleci instances as well.

**Comment by mykola-mokhnach** [comment] 2018-01-16 07:01
It's [fixed](https://github.com/appium/appium-base-driver/commit/98251e0b4f48f92bc9be89ea5383dc47f303a48e), but is not published yet. We'll let you know when the fix is available in beta

**Comment by sytolk** [comment] 2018-01-16 10:51
@mykola-mokhnach this [fix](https://github.com/appium/appium-base-driver/commit/98251e0b4f48f92bc9be89ea5383dc47f303a48e) will open new issue: https://github.com/appium/appium/issues/9981#issuecomment-357922003

**Comment by dpgraham** [comment] 2018-01-16 17:00
Fix is publish to 2.20.1 (https://www.npmjs.com/package/appium-base-driver)
