### ISSUE TITLE
swipe ms == s

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7440] opened 2016-12-06 15:45 UTC
@toejough commented on [Mon Nov 21 2016](https://github.com/appium/appium-xcuitest-driver/issues/306)

Not sure where this belongs (here or the WDA project), but the swipe duration that used to be in ms is now in s.

Specifically, the command
```
[HTTP] --> POST /wd/hub/session/2f68760d-ccec-42e5-8836-8c3d72ce3393/touch/perform {"sessionId":"2f68760d-ccec-42e5-8836-8c3d72ce3393","actions":[{"options":{"x":187,"y":133},"action":"press"},{"options":{"ms":1000},"action":"wait"},{"options":{"x":0,"y":400},"action":"moveTo"},{"options":{},"action":"release"}]}
```
is always resulting in a long-press instead of a swipe action.

After searching around a bit, I found https://github.com/facebook/WebDriverAgent/issues/344, in which @marekcirkos says a user's `800` is too long for duration, and the system might interpret it as a long-touch.

Sure enough, if I send `1` instead of `1000` in the "ms" field of the above request, it results in a 1s-long swipe.

The full log for that request has truncated lines - I'm not sure why, but here's what they are:
```
[HTTP] --> POST /wd/hub/session/2f68760d-ccec-42e5-8836-8c3d72ce3393/touch/perform {"sessionId":"2f68760d-ccec-42e5-8836-8c3d72ce3393","actions":[{"options":{"x":187,"y":133},"action":"press"},{"options":{"ms":1000},"action":"wait"},{"options":{"x":0,"y":400},"action":"moveTo"},{"options":{},"action":"release"}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"options":{"x":187,"y":1...
[debug] [XCUITest] Executing command 'performTouch'
[JSONWP Proxy] Proxying [POST /uiaTarget/0/dragfromtoforduration] to [POST http://localhost:8100/session/3172B36F-75FC-449B-BA91-FB8B9FE12416/uiaTarget/0/dragfromtoforduration] with body: {"fromX":187,"fromY":133,"t...
[JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"31...
[MJSONWP] Responding to client with driver.performTouch() result: {}
[HTTP] <-- POST /wd/hub/session/2f68760d-ccec-42e5-8836-8c3d72ce3393/touch/perform 200 3272 ms - 74
```

---

@jlipps commented on [Mon Nov 21 2016](https://github.com/appium/appium-xcuitest-driver/issues/306#issuecomment-262100505)

@imurchie maybe WDA is using seconds instead of milliseconds, and we should convert?

---

@marekcirkos commented on [Tue Nov 22 2016](https://github.com/appium/appium-xcuitest-driver/issues/306#issuecomment-262201748)

@jlipps I would double check differences in Xcode. Apple might have change "mind" in new xcode and interpret them as seconds instead of milliseconds. In that case conversion should happen on WDA site.

**Comment by asnaith** [comment] 2016-12-07 23:38
I am also experiencing issues with a bunch of previous built gestures in my framework since this was changed, they work fine on Android but not on iOS (swipes being recognized as long press taps). 

Maybe this is a candidate for a new "desired capability" where you can set whether you are sending commands in ms or seconds. Then the Appium server could then convert to seconds if necessary and pass that on to WDA?

**Comment by asnaith** [comment] 2016-12-21 23:58
@imurchie @jlipps Should Appium be handling the conversion to seconds if that's what WDA is using?

**Comment by jlipps** [comment] 2016-12-21 23:59
@asnaith yes. Appium should keep accepting whatever it was before, and if WDA is using something different, Appium should convert (and tell WDA to change! :-))

**Comment by asnaith** [comment] 2016-12-22 00:13
@jlipps Thank you for the clarification. So maybe the conversion could be linked to a bool "convertToSecs" desired capability and then if WDA switch back to milliseconds people can just set that capability back to false?

**Comment by jlipps** [comment] 2016-12-22 00:15
What I'm saying is we shouldn't have a capability at all. If WDA isn't doing the right thing, Appium should intercept the command, convert the number appropriately, and only then proxy the command to WDA.

**Comment by asnaith** [comment] 2016-12-22 00:27
@jlipps ah ok, thanks Jonathan. This issue is becoming a big blocker for my iOS 10 testing so maybe I need to see if I can attempt the conversion fix. I don't know javascript or how this project is structured but I can at least investigate and give it a try. 

Perhaps leave the bug unassigned for now though because if someone with more experience has capacity to take it on that would probably be better.

**Comment by asnaith** [comment] 2016-12-29 17:25
@jlipps I've unsuccessfully looked into this but am not sure where to start. Could you help point me in the right direction where a fix would need to be please? I'm totally lost.

**Comment by jlipps** [comment] 2017-01-06 19:01
@asnaith just to follow up: it looks like we're already doing this. Check out https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/gesture.js#L153. Notice that we're getting the `ms` of the duration, then turning into seconds for WDA. So I'm unsure why you're experiencing this.

**Comment by asnaith** [comment] 2017-01-10 19:29
@jlipps Thanks for following up. This is strange, I'll put it on 1.6.3 and I'll give it another go and print a log to see.

**Comment by asnaith** [comment] 2017-01-10 20:07
@jlipps When I look through my logs (for a test on Appium 1.6.3) I see that it's still passing 3000 ms for a gesture and that is in turn being interpreted as a long press by the app. 

`2017-01-10 19:39:34:982 - info: [debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":187,"y":428}},{"action":"wait","options":{"ms":3000}},{"action":"moveTo","options":{"x":187,"y":179}},{"action":"release"}],"bfc47edd-2e27-4b38-91dc-b42ad715e89e"]
2017-01-10 19:39:34:982 - info: [debug] [XCUITest] Executing command 'performTouch'
2017-01-10 19:39:34:983 - info: [debug] [XCUITest] Received the following touch action: press-wait-moveTo-release`

(full log file attached). 

Would love to test more / provide more info to help but unsure what you need. 
[log.txt](https://github.com/appium/appium/files/697228/log.txt)

**Comment by jlipps** [comment] 2017-01-24 00:54
@asnaith but see what happens when Appium sends this data to WDA:

> 2017-01-10 19:35:46:806 - info: [debug] [JSONWP Proxy] Proxying [POST /uiaTarget/0/dragfromtoforduration] to [POST http://localhost:8100/session/C4C63B99-65B7-4CEB-AB86-A830BD593DAA/uiaTarget/0/dragfromtoforduration] with body: {"fromX":187,"fromY":428,"toX":374,"toY":607,"duration":3}

It converts it as expected into seconds for WDA. If it's being interpreted as a long press rather than a drag, it seems like it's a WDA issue instead.

....and confirmed. I just looked at the WDA source code, check out this section: https://github.com/facebook/WebDriverAgent/blob/eeaa1a3bbc9559d41ff3779c73c6678c7715a3d0/WebDriverAgentLib/Commands/FBElementCommands.m#L295-L306

It does indeed look like this does a press for the duration specified, and only _then_ does the drag (for some unspecified amount of time?) @marekcirkos is this the intended behavior? press-for-duration-then-drag-for-unspecified-duration? Rather than simply drag-for-duration?

**Comment by marekcirkos** [comment] 2017-01-24 23:52
Yeah, this is drag and drop kind of thing. I think we should implement action interface instead of pre gesture endpoints.

**Comment by jlipps** [comment] 2017-01-24 23:58
Yes, that would be awesome!

**Comment by marekcirkos** [comment] 2017-01-25 00:01
https://github.com/facebook/WebDriverAgent/issues/463 - to follow.

**Comment by jlipps** [comment] 2017-01-25 00:06
Closing this since the mystery is resolved; the current behavior is expected on the part of WDA, but that will hopefully change soon.

**Closed by jlipps** 2017-01-25 00:06 UTC
Labels: Bug, iOS, XCUITest

**Comment by asnaith** [comment] 2017-01-26 18:36
@jlipps Thank you so much for digging into this and finding the true issue here
