### ISSUE TITLE
Webdriver Agent Will not install when launching inspector tool

### ISSUE THREAD

**Issue by lefty1975** [appium/appium#14139] opened 2020-04-02 17:41 UTC
## The problem

When I try to launch the inspector tool for iOS, it just spins and finally errors out. The WebdriverAgent is never installed to the simulator. However, if I run this command `xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination ‘id=DeviceID’ test` the webdriverAgent does get installed and if I hit the inspector option from the desktop client, it finally opens my application but doesn't let me inspect.

I have read so many threads and searched high and low for solutions. Installed/uninstalled numerous times that I have no idea what I can try next to resolve this matter.

I just simply would like to inspect my application on an iOS simulator. I have NO issues doing this on the Android platform.

## Environment

* Desktop 1.15
* npm version: 1.17.1-beta.0
* Desktop OS/version used to run Appium: mac OS Catalina 10.15.3
* Node.js version (unless using Appium.app|exe): v12.11.1
* Npm or Yarn package manager: Npm 6.14.4
* Mobile platform/version under test: iPhone Xs Max (12.2)

## Link to Appium logs

https://gist.github.com/lefty1975/6fa45eb6498b08029364b4642f40e3ba

**Comment by mykola-mokhnach** [comment] 2020-04-02 17:50
Duplicate of https://github.com/appium/appium/issues/14102

**Closed by mykola-mokhnach** 2020-04-02 17:50 UTC

**Comment by lefty1975** [comment] 2020-04-02 17:58
If the duplicate issue doesn’t solve my issue, then what?

I have been trying to solve this issue for days and to have someone close it within minutes is discouraging.

**Comment by mykola-mokhnach** [comment] 2020-04-02 18:00
Everything that needs to be done is just Appium server upgrade. Version 1.15 is out of date

**Comment by lefty1975** [comment] 2020-04-02 18:15
@mykola-mokhnach 

You were right. Many thank you's to you.

I lost all of my saved capabilities, but I can deal with that considering the struggles I went through.

**Comment by npandey-qa** [comment] 2020-04-15 02:07
Upgraded to the latest 1.17 version using CLI and not appium desktop and it solved the issue

**Comment by Irfanap** [comment] 2021-06-30 11:30
When I try to launch the inspector tool for iOS. It throughing the error code 65 i tried to set signing capbilities every thing but no luck. The WebdriverAgent is never installed to the simulator. However, if I run this command xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination ‘id=DeviceID’ test the webdriverAgent does get installed and if I hit the inspector option from the desktop client, it opens integration app not which i mentioned in JSon.

Could any one have any solution for this??
