### ISSUE TITLE
Facing problem with inspecting elements on real device

### ISSUE THREAD

**Issue by greathjh** [appium/appium#14123] opened 2020-03-30 10:51 UTC
## The problem

Hi, everyone.I am currently facing the problem. I am trying to inspect elements on real iOS device using Appium desktop.

## Environment

Appium client: 1.17.0
MacBook system：macOS Mojave version：10.14.6
Mobile phone: iPhone 7 plus
Mobile platform/version: iOS 13.1.2
xcode:11.3

## Details

i pull lastest code form the https://github.com/appium/appium.and update the carthage/libimobiledevice/ios-deploy.i can use Appium test launch app by iPhone Simulator,but i cann't inspect elements on real iOS device using Appium desktop.

## Link to Appium logs

[Appium] Welcome to Appium v1.17.0
[Appium] Non-default server args:
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"automationName":"XCUITest","bundleId":"com.leihou.OOLaGongYi","deviceName":"iPhone 7 Plus","noReset":true,"platformName":"iOS","platformVersion":"13.1","udid":"3b8ea39bab820e51a2abcd5b3602df42407baacd","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","bundleId":"com.leihou.OOLaGongYi","deviceName":"iPhone 7 Plus","noReset":true,"platformName":"iOS","platformVersion":"13.1","udid":"3b8ea39bab820e51a2abcd5b3602df42407baacd","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[Appium] Appium v1.17.0 creating new XCUITestDriver (v3.17.0) session
[BaseDriver] Creating session with MJSONWP desired capabilities: {
[BaseDriver]   "automationName": "XCUITest",
[BaseDriver]   "bundleId": "com.leihou.OOLaGongYi",
[BaseDriver]   "deviceName": "iPhone 7 Plus",
[BaseDriver]   "noReset": true,
[BaseDriver]   "platformName": "iOS",
[BaseDriver]   "platformVersion": "13.1",
[BaseDriver]   "udid": "3b8ea39bab820e51a2abcd5b3602df42407baacd",
[BaseDriver]   "newCommandTimeout": 0,
[BaseDriver]   "connectHardwareKeyboard": true
[BaseDriver] }
[BaseDriver] Session created with session id: ba986d8a-d23b-4f73-a3fa-8e6d938e829c
[XCUITest] Current user: 'admin'
[XCUITest] Available devices: 3b8ea39bab820e51a2abcd5b3602df42407baacd
[XCUITest] Creating iDevice object with udid '3b8ea39bab820e51a2abcd5b3602df42407baacd'
[XCUITest] Determining device to run tests on: udid: '3b8ea39bab820e51a2abcd5b3602df42407baacd', real device: true
[XCUITest] Setting up real device
[WebDriverAgent] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent'
[WebDriverAgent] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[WebDriverAgent] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device 3b8ea39bab820e51a2abcd5b3602df42407baacd on local port 8100, device port 8100
[DevCon Factory] Cached connections count: 0
[DevCon Factory] Successfully requested the connection for 3b8ea39bab820e51a2abcd5b3602df42407baacd:8100
[WebDriverAgent] Parsed BUILD_DIR configuration value: '/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products'
[WebDriverAgent] Got derived data root: '/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp'
[XCUITest] Starting WebDriverAgent initialization with the synchronization key '/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp'
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] Got response with status 200: {
[WD Proxy]   "value" : {
[WD Proxy]     "state" : "success",
[WD Proxy]     "os" : {
[WD Proxy]       "name" : "iOS",
[WD Proxy]       "version" : "13.1.2"
[WD Proxy]     },
[WD Proxy]     "ios" : {
[WD Proxy]       "simulatorVersion" : "13.1.2",
[WD Proxy]       "ip" : "192.168.1.9"
[WD Proxy]     },
[WD Proxy]     "build" : {
[WD Proxy]       "time" : "Mar 30 2020 15:43:17"
[WD Proxy]     }
[WD Proxy]   },
[WD Proxy]   "sessionId" : "F3C04C8E-1522-4525-BA19-7661AF07437F",
[WD Proxy]   "status" : 0
[WD Proxy] }
[WebDriverAgent] Upgrade timestamp of the currently bundled WDA: 1585302523285
[WebDriverAgent] Upgrade timestamp of the WDA on the device: undefined
[WebDriverAgent] Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[WebDriverAgent] Using provided WebdriverAgent at 'http://127.0.0.1:8100/'
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] Got response with status 200: {
[WD Proxy]   "value" : {
[WD Proxy]     "state" : "success",
[WD Proxy]     "os" : {
[WD Proxy]       "name" : "iOS",
[WD Proxy]       "version" : "13.1.2"
[WD Proxy]     },
[WD Proxy]     "ios" : {
[WD Proxy]       "simulatorVersion" : "13.1.2",
[WD Proxy]       "ip" : "192.168.1.9"
[WD Proxy]     },
[WD Proxy]     "build" : {
[WD Proxy]       "time" : "Mar 30 2020 15:43:17"
[WD Proxy]     }
[WD Proxy]   },
[WD Proxy]   "sessionId" : "F3C04C8E-1522-4525-BA19-7661AF07437F",
[WD Proxy]   "status" : 0
[WD Proxy] }
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.leihou.OOLaGongYi","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":"F3C04C8E-1522-4525-BA19-7661AF07437F","status":13}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided). Retrying...
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.leihou.OOLaGongYi","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":"F3C04C8E-1522-4525-BA19-7661AF07437F","status":13}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided). Retrying...
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.leihou.OOLaGongYi","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":"F3C04C8E-1522-4525-BA19-7661AF07437F","status":13}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided). Retrying...
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.leihou.OOLaGongYi","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":"F3C04C8E-1522-4525-BA19-7661AF07437F","status":13}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided). Retrying...
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.leihou.OOLaGongYi","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":"F3C04C8E-1522-4525-BA19-7661AF07437F","status":13}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided). Retrying...
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.leihou.OOLaGongYi","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":"F3C04C8E-1522-4525-BA19-7661AF07437F","status":13}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided). Retrying...
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.leihou.OOLaGongYi","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":"F3C04C8E-1522-4525-BA19-7661AF07437F","status":13}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided). Retrying...
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.leihou.OOLaGongYi","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":"F3C04C8E-1522-4525-BA19-7661AF07437F","status":13}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided). Retrying...
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.leihou.OOLaGongYi","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":"F3C04C8E-1522-4525-BA19-7661AF07437F","status":13}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided). Retrying...
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.leihou.OOLaGongYi","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":"F3C04C8E-1522-4525-BA19-7661AF07437F","status":13}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided). Retrying...
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.leihou.OOLaGongYi","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":"F3C04C8E-1522-4525-BA19-7661AF07437F","status":13}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided). Retrying...
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.leihou.OOLaGongYi","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":"F3C04C8E-1522-4525-BA19-7661AF07437F","status":13}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided). Retrying...
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.leihou.OOLaGongYi","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":"F3C04C8E-1522-4525-BA19-7661AF07437F","status":13}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided). Retrying...
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.leihou.OOLaGongYi","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":"F3C04C8E-1522-4525-BA19-7661AF07437F","status":13}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided). Retrying...
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.leihou.OOLaGongYi","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":"F3C04C8E-1522-4525-BA19-7661AF07437F","status":13}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided). Retrying...
[XCUITest] UnknownError: An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided
[XCUITest]     at errorFromMJSONWPStatusCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:767:10)
[XCUITest]     at ProxyRequestError.getActualError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:661:14)
[XCUITest]     at JWProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:264:19)
[XCUITest] Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest] Quitting and uninstalling WebDriverAgent
[WebDriverAgent] Shutting down sub-processes
[WebDriverAgent] Uninstalling WDAs: 'com.facebook.WebDriverAgentRunner.xctrunner'
[XCUITest] Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:525:15)
[XCUITest]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:586:11
[XCUITest]     at wrapped (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:35:13)
[XCUITest]     at retry (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:18:13)
[XCUITest]     at retryInterval (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:45:10)
[XCUITest]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:535:7
[DevCon Factory] Releasing connections for 3b8ea39bab820e51a2abcd5b3602df42407baacd device on any port number
[DevCon Factory] Found cached connections to release: ["3b8ea39bab820e51a2abcd5b3602df42407baacd:8100"]
[DevCon Factory] Releasing the listener for '3b8ea39bab820e51a2abcd5b3602df42407baacd:8100'
[iProxy@3b8ea39b:8100] Closing the connection
[DevCon Factory] Cached connections count: 0
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[MJSONWP]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:525:15)
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:586:11
[MJSONWP]     at wrapped (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:35:13)
[MJSONWP]     at retry (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:18:13)
[MJSONWP]     at retryInterval (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:45:10)
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:535:7
[MJSONWP] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 20876 ms - 568
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 8 ms - 57
[HTTP] 
[iProxy@3b8ea39b:8100] The connection has been closed

**Comment by mykola-mokhnach** [comment] 2020-03-30 10:55
Duplicate of https://github.com/appium/appium/issues/13646

**Closed by mykola-mokhnach** 2020-03-30 10:55 UTC
