### ISSUE TITLE
set_clipboard (iOS) does not work

### ISSUE THREAD

**Issue by simonsymhoven** [appium/appium#15324] opened 2021-05-04 12:14 UTC
## The problem

I have a python script and execute `self._driver.set_clipboard_text("some string")`. Then I performed a `clip = self._driver.get_clipboard_text()` and `clip` ist empty although the http call is successfully triggered.

## Environment

* Appium version (or git revision) that exhibits the issue: Python Client: 1.1.0, Appium Server: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): Don'T know.
* Desktop OS/version used to run Appium: Mac OS Bis Sur 11.3.1
* Node.js version (unless using Appium.app|exe): 15.13.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 14.5
* Real device or emulator/simulator: Xcode 12.5
* Appium CLI or Appium.app|exe: both

## Link to Appium logs

[Logs](https://gist.github.com/simonsymhoven/ddc2b0a9b18b6d7fe159feb31d3edeb5)

**Comment by mykola-mokhnach** [comment] 2021-05-04 12:17
This behaviour is expected on real devices (Apple's security limitation)

Closed as duplicate of https://github.com/appium/appium/issues/14568

**Closed by mykola-mokhnach** 2021-05-04 12:17 UTC

**Comment by simonsymhoven** [comment] 2021-05-04 12:47
@mykola-mokhnach Thank you! Sorry didn't found this issue..
