### ISSUE TITLE
Unable to start appium session

### ISSUE THREAD

**Issue by shyam6363** [appium/appium#20025] opened 2024-04-22 02:12 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

C:\Users\Healthcubed>appium --allow-cors
[Appium] Welcome to Appium v2.5.3
[Appium] Non-default server args:
[Appium] {
[Appium]   allowCors: true
[Appium] }
[Appium] The autodetected Appium home path: C:\Users\Healthcubed\.appium
[Appium] You have enabled CORS requests from any host. Be careful not to visit sites which could maliciously try to start Appium sessions on your machine
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium]        http://192.168.0.103:4723/
[Appium]        http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] No drivers have been installed in C:\Users\Healthcubed\.appium. Use the "appium driver" command to install the one(s) you want to use.
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.

![image](https://github.com/appium/appium/assets/34148561/59b7983f-6a20-4f6f-9ffc-f7ab1f3f159e)

C:\Users\Healthcubed>appium driver list
√ Listing available drivers
- uiautomator2 [not installed]
- xcuitest [not installed]
- mac2 [not installed]
- espresso [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]

C:\Users\Healthcubed>appium install driver uiautomator2

[ERROR] Unrecognized arguments: install driver uiautomator2

C:\Users\Healthcubed>appium driver install uiautomator2
√ Checking if 'appium-uiautomator2-driver' is compatible
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev --no-progress --no-audit --omit=peer --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code EINVAL.

STDOUT:

STDERR:

### Expected Behavior

C:\Users\Healthcubed>appium --allow-cors
[Appium] Welcome to Appium v2.5.3
[Appium] Non-default server args:
[Appium] {
[Appium]   allowCors: true
[Appium] }
[Appium] The autodetected Appium home path: C:\Users\Healthcubed\.appium
[Appium] You have enabled CORS requests from any host. Be careful not to visit sites which could maliciously try to start Appium sessions on your machine
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium]        http://192.168.0.103:4723/
[Appium]        http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] No drivers have been installed in C:\Users\Healthcubed\.appium. Use the "appium driver" command to install the one(s) you want to use.
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.

![image](https://github.com/appium/appium/assets/34148561/59b7983f-6a20-4f6f-9ffc-f7ab1f3f159e)

C:\Users\Healthcubed>appium driver list
√ Listing available drivers
- uiautomator2 [not installed]
- xcuitest [not installed]
- mac2 [not installed]
- espresso [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]

C:\Users\Healthcubed>appium install driver uiautomator2

[ERROR] Unrecognized arguments: install driver uiautomator2

C:\Users\Healthcubed>appium driver install uiautomator2
√ Checking if 'appium-uiautomator2-driver' is compatible
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev --no-progress --no-audit --omit=peer --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code EINVAL.

STDOUT:

STDERR:

### Minimal Reproducible Example

C:\Users\Healthcubed>appium --allow-cors
[Appium] Welcome to Appium v2.5.3
[Appium] Non-default server args:
[Appium] {
[Appium]   allowCors: true
[Appium] }
[Appium] The autodetected Appium home path: C:\Users\Healthcubed\.appium
[Appium] You have enabled CORS requests from any host. Be careful not to visit sites which could maliciously try to start Appium sessions on your machine
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium]        http://192.168.0.103:4723/
[Appium]        http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] No drivers have been installed in C:\Users\Healthcubed\.appium. Use the "appium driver" command to install the one(s) you want to use.
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.

![image](https://github.com/appium/appium/assets/34148561/59b7983f-6a20-4f6f-9ffc-f7ab1f3f159e)

C:\Users\Healthcubed>appium driver list
√ Listing available drivers
- uiautomator2 [not installed]
- xcuitest [not installed]
- mac2 [not installed]
- espresso [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]

C:\Users\Healthcubed>appium install driver uiautomator2

[ERROR] Unrecognized arguments: install driver uiautomator2

C:\Users\Healthcubed>appium driver install uiautomator2
√ Checking if 'appium-uiautomator2-driver' is compatible
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev --no-progress --no-audit --omit=peer --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code EINVAL.

STDOUT:

STDERR:

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

NA

**Comment by mykola-mokhnach** [comment] 2024-04-22 05:34
Duplicate of https://github.com/appium/appium/issues/20008

**Closed by mykola-mokhnach** 2024-04-22 05:34 UTC
Labels: Bug, Needs Triage
