### ISSUE TITLE
Are there any plans to support Smart TV automation testing?

### ISSUE THREAD

**Issue by vitalets** [appium/appium#7780] opened 2017-01-31 11:04 UTC
Hi! it seems that appium architecture should allow to support automation of Smart TV Apps testing.
Do you have any roadmap for that?
Thanks!

**Comment by mykola-mokhnach** [comment] 2017-01-31 12:46
duplicate of https://github.com/appium/appium/issues/7688

**Comment by vitalets** [comment] 2017-01-31 14:12
I don't think it's really duplicate. Apple TV and for example Samsung Tizen or LG webOS are absolutely different platforms that seems to need own drivers.

**Comment by mykola-mokhnach** [comment] 2017-01-31 14:31
Nothing of these are neither supported nor tested for compatibility with Appium for now. But we will be happy if one starts to contribute in this direction.

**Comment by vitalets** [comment] 2017-01-31 15:38
@mykola-mokhnach 
You are right, it seems to be blank field now.
The most popular SO question is this one: http://stackoverflow.com/questions/15874501/test-automation-tool-for-smart-tv-apps

As first step I can discuss with our partners in Samsung.
Anyway I would ask to keep this issue open as technically it has nothing with Apple TV in #7688

**Comment by vitalets** [comment] 2017-01-31 16:10
@monster-mj 
Hi Minjoo, could you give us some comments, are there any plans in Samsung Tizen TV to provide API for automation frameworks?

thx)

**Comment by toien44** [comment] 2018-07-16 20:31
Yeah I'd like some info if it comes up on Roku and Apple TV myself. Thanks for leaving this open.

**Comment by huse** [comment] 2018-08-01 21:45
I'm planning to do it, any suggestion or clue for where can I start or which file in appium should be modified, really appreciated.

**Comment by mykola-mokhnach** [comment] 2018-08-01 22:02
@huse https://github.com/facebook/WebDriverAgent/pull/55

**Comment by dpgraham** [comment] 2019-03-06 20:52
I'm going to close this (unless you have any objections @mykola-mokhnach)

* Samsung released a Tizen Driver which should supports Samsung TV
* TvOS support is in progress
* LG OS won't be supported by the internal Appium team and will need to be developed by LG

**Closed by dpgraham** 2019-03-06 20:52 UTC
Labels: Enhancement, P3, Question

**Comment by BoazWarshawsky** [comment] 2019-05-23 06:35
@mykola-mokhnach @dpgraham  can you share example of how to use Tizen Driver which should supports Samsung TV?

**Comment by imurchie** [comment] 2019-05-23 14:09
@BoazWarshawsky You should check with https://github.com/Samsung/appium-tizen-driver. As far as I know, no one in the core Appium team has done any development on Tizen.

**Comment by shoshins** [comment] 2019-07-23 15:03
Sorry for persistence, but what about Roku? 
They are released Unit Tests platform, it may helps, I suppose.
https://github.com/rokudev/unit-testing-framework/blob/master/docs/unit-test-framework.md
