### ISSUE TITLE
Will the agent be executed? Similar to the proxy service provided by selenium,

### ISSUE THREAD

**Issue by timwang-ai** [appium/appium#17355] opened 2022-08-11 08:27 UTC
## The problem

When executing appium startup service, you want to execute proxy service forwarding when starting, similar to: myproxy =“ http://149.215.113.110:70 "
proxy = Proxy({
'proxyType': ProxyType.MANUAL,
'httpProxy': myProxy,
'ftpProxy': myProxy,
'sslProxy': myProxy,
'noProxy':''})

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `examples` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in examples, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2022-08-11 08:34
Duplicate of https://github.com/appium/appium/issues/17044

Appium does not support proxies

**Closed by mykola-mokhnach** 2022-08-11 08:34 UTC

**Comment by KazuCocoa** [comment] 2022-08-11 16:44
Selenium's the caps one is proxy in the browser under test. As Appium, you could set proxy up in the device under test by yourself (not by appium server itself as mykola's comment)

**Comment by timwang-ai** [comment] 2022-08-12 08:15
I don't want to set the phone's proxy, but through the Appium proxy, just like setting the language, set the language of the current App, without setting the language of the entire phone

**Comment by KazuCocoa** [comment] 2022-08-12 17:32
I don't know if mobile devices can set proxy up per process. It might be helpful if you know the way.
