### ISSUE TITLE
iOS - Exception: Cannot set the selection end when SendKeys to element

### ISSUE THREAD

**Issue by siggerzz** [appium/appium#8927] opened 2017-07-27 14:20 UTC
## The problem

When trying to SendKeys to a particular element on iOS I get the exception: 

```
Message: System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.InvalidOperationException : An unknown server-side error occurred while processing the command. Original error: Error while executing atom: Cannot set the selection end (status: 13)
```

From what I've seen online, this is caused when trying to SendKeys to an element which has the 'contenteditable' attribute. I'm assuming this is an iOS issue, since the test works fine on Android.

Other Examples of this issue:
https://github.com/appium/appium/issues/6506
https://github.com/appium/appium/issues/1001
https://discuss.appium.io/t/sendkeys-is-not-working-in-ipad-safari/3466

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3, 1.6.4, 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS Sierra
* Node.js version (unless using Appium.app|exe): 6.10.3
* Mobile platform/version under test: iOS - 10.3.2
* Real device or emulator/simulator: Real Device - iPad Mini 4
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[Appium Logs](https://gist.github.com/siggerzz/03788907d213f8c125c79a8a4f35fd07)

HTML Element that I'm trying to SendKeys to:

< div class="full-page-texteditor__content js-full-page-texteditor-content wysihtml-sandbox wysihtml-editor wysihtml-editor-frame" style="min-height: 570px;" contenteditable="true"><p> </p></div >

**Comment by jlipps** [comment] 2017-07-31 22:21
This would be an issue with the Selenium Atoms which are used to enable hybrid testing on iOS. Unfortunately, if the atoms are not working, you'll either need to seek help with the Selenium project, or see if you can mess with the field while in native mode (I'm guessing not since it's not actually an input element). Unfortunately there is no other way to automate Safari than by sending javascript via the remote debugger, which is how we get the Atoms across.

Duplicate of #1001.

**Comment by barancev** [comment] 2017-08-31 13:53
Which atom is broken? Is it broken in all browsers (including desktop ones) or iOS only? The phrase "since the test works fine on Android" hints us that it's not globally broken.

**Comment by siggerzz** [comment] 2017-08-31 14:01
@barancev  I'm afraid I'm fairly new Selenium/Appium, so apologies in advance.

Which atom is broken? - How can I go about finding this out for you?

And yeah, you're right. I'm currently using Appium to automate a hybrid web app on iOS/Android. I've only seen the issue on iOS. As for desktop browsers, I'm not entirely sure which ones are affected, since I'm not testing against any. However I did see someone have the same issue on [Safari](https://discuss.appium.io/t/sendkeys-is-not-working-in-ipad-safari/3466):

I can try testing some other desktop browsers, but I'd need to update my solution before I can get back to you.

**Comment by barancev** [comment] 2017-08-31 14:05
@siggerzz It's mostly the question to Appium devs, they should know what atom exactly do they use.

**Comment by imurchie** [comment] 2017-09-01 11:43
We have just updated the to the latest Se atoms. Please re-install the latest beta and try again.

**Comment by siggerzz** [comment] 2017-09-01 13:53
@imurchie I reinstalled the latest beta, and I'm no longer able to find any elements on iOS (Android is still okay).

After downgrading back to 1.6.5, I'm able to find elements again on iOS.

Is it possible the atoms update caused this to break?

**Comment by siggerzz** [comment] 2017-09-06 08:46
Hey, any update on this?

**Comment by siggerzz** [comment] 2017-09-13 08:55
@jlipps @imurchie

**Comment by imurchie** [comment] 2017-09-13 15:21
I guess it could be possible, though they seem to work for all our cases.

Can you provide logs for this, so we can see what is going on?

**Comment by siggerzz** [comment] 2017-09-13 16:08
@imurchie Sure! Okay, so I'm seeing slightly different behaviour on 1.6.6-beta-4 now.

I'm now able to find elements on iOS and run my test, however now it finds the element, attempts to set the value (but doesn't) and then executes the next step of my test.

Appium 1.6.5 - https://gist.github.com/siggerzz/2765ca881b4520d6cc94cf65f1d40823

Appium 1.6.6-beta-4 - The element in question is on line 34. - https://gist.github.com/siggerzz/4a8216c038ab95bfd3d4c2cc22d0c411

**Comment by siggerzz** [comment] 2017-09-18 10:37
@imurchie @jlipps  Is it possible to reopen this ticket?

**Comment by siggerzz** [comment] 2017-09-19 09:07
Re-opening a new ticket for this since I'm now seeing different behaviour in 1.7.0

**Comment by imurchie** [comment] 2017-09-19 13:17
What is the behavior seen now?

**Comment by siggerzz** [comment] 2017-09-19 13:18
@imurchie - https://github.com/appium/appium/issues/9243

**Comment by imurchie** [comment] 2017-09-19 13:36
Ok. Re-closing this one in preference of that.

**Closed by imurchie** 2017-09-19 13:36 UTC
Labels: XCUITest
