### ISSUE TITLE
Unable to start inspector with appium 1.3.2 and UIAutomator2

### ISSUE THREAD

**Issue by mjevtovic** [appium/appium#10249] opened 2018-02-23 11:22 UTC
## The problem

I am not able to start inspector with appium 1.3.2 and UIAutomator2. It throws error that 'appPackage' option is required although I have that capability properly configured. 
If I use appium w/o UIAUtomator2 capability everything works fine.

## Environment

* Appium version 1.3.2
* Last Appium version that did not exhibit the issue (if applicable): 1.3.1
* Desktop OS/version used to run Appium: macOS Sierra 10.12.1
* Node.js version (unless using Appium.app|exe): using Appium.app
* Mobile platform/version under test: android-22
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

Here is screenshot. (note that amazon app i previously installed on emulator)
![screen shot 2018-02-21 at 4 30 54 pm](https://user-images.githubusercontent.com/10105654/36591899-c74cd24c-1893-11e8-9925-04bcfac5d60b.png)

**Comment by mykola-mokhnach** [comment] 2018-02-23 13:03
Please attach the full server log

**Comment by mjevtovic** [comment] 2018-02-26 14:21
Here is the log file.

https://gist.github.com/mjevtovic/e4c764143bce3ff06a27bdbaf861fef3

**Comment by mykola-mokhnach** [comment] 2018-02-26 14:32
Is the problem reproducible in appium@beta?

**Comment by mykola-mokhnach** [comment] 2018-02-27 06:19
Duplicate of https://github.com/appium/appium/issues/10248

**Closed by mykola-mokhnach** 2018-02-27 06:19 UTC
Labels: NeedsInfo

**Comment by mjevtovic** [comment] 2018-02-27 11:41
It works with 1.8.0-beta3
