### ISSUE TITLE
[Bug]: unable to install xcuitest driver on appium v2

### ISSUE THREAD

**Issue by nir-tal-talkspace** [appium/appium#17670] opened 2022-10-27 09:13 UTC
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

unable to install xcuitest driver on appium v2

## Environment

* Appium version (or git revision) that exhibits the issue:  2.0.0-beta.46
* Last Appium version that did not exhibit the issue (if applicable): 2.0.0-beta.38
* Desktop OS/version used to run Appium: MAC 
* Node.js version (unless using Appium.app|exe): v18.2.0
* Npm or Yarn package manager: npm

## Details
run "appium driver install xcuitest" on command line to install driver

## Link to Appium logs
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev appium-xcuitest-driver --json' failed with code 1.

STDOUT:

STDERR:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: appium@1.22.3
npm ERR! node_modules/appium
npm ERR!   appium@"^1.22.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer appium@"^2.0.0-beta.40" from appium-xcuitest-driver@4.12.1
npm ERR! node_modules/appium-xcuitest-driver
npm ERR!   dev appium-xcuitest-driver@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/nirtal/.npm/eresolve-report.txt for a full report.
{
  "error": {
    "code": "ERESOLVE",
    "summary": "unable to resolve dependency tree",
    "detail": "\nWhile resolving: undefined@undefined\nFound: appium@1.22.3\nnode_modules/appium\n  appium@\"^1.22.3\" from the root project\n\nCould not resolve dependency:\npeer appium@\"^2.0.0-beta.40\" from appium-xcuitest-driver@4.12.1\nnode_modules/appium-xcuitest-driver\n  dev appium-xcuitest-driver@\"*\" from the root project\n\nFix the upstream dependency conflict, or retry\nthis command with --force, or --legacy-peer-deps\nto accept an incorrect (and potentially broken) dependency resolution.\n\nSee /Users/nirtal/.npm/eresolve-report.txt for a full report."
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nirtal/.npm/_logs/2022-10-27T09_09_30_267Z-debug-0.log

**Comment by mykola-mokhnach** [comment] 2022-10-27 09:29
Duplicate of https://github.com/appium/appium/issues/17614

**Closed by mykola-mokhnach** 2022-10-27 09:29 UTC
