### ISSUE TITLE
Appium gets stuck when log File reaches about 30 MB or more

### ISSUE THREAD

**Issue by LimeDang** [appium/appium#4638] opened 2015-03-03 10:54 UTC
Appium gets stuck when log File reaches about 30 MB or more.
My Mac machine have hundreds of GB free and the memory is 8GB and almost free.

I saw this bug a long time ago and now it still exists, so I post this issue.

When executing tests with Safari browser in debug mode, it prints out many texts about elements on the page, it causes the log increases bigger and bigger. But I do not understand why Appium always get stuck when the log reach the limitation (about 30 MB or more). I guess may be the buffer memory of Appium is reach to the limitation or somethings.

This causes the tests to execute on Safari can not be long (especially on a large page, the log rapidly reaches to the limitation).

**Comment by amedvedjev** [comment] 2015-03-03 17:50
how you start appium server in code ?

**Comment by fangmobile** [comment] 2015-03-04 05:53
I had the exact same problem a while ago. Even though I did not calculate the exact size of the log, it is huge.
But a developer in my team figured out it that it is NOT Appium's fault. Rather, UIAutomation should take the blame. 
Just do a simple test, profile the same app using instrument automation, and generate the same amount of log. You should see the same "freeze".
We file a bug with Apple and they closed it as "duplicate". God know when it will be fixed.

**Comment by LimeDang** [comment] 2015-03-04 07:50
@jlipps do you have any idea?

Because I think for testing on iOS Safari browser, Appium use ios-webkit-debug-proxy to interact with Safari not UIAutomation. Then Appium will handle the log, right?

**Comment by fangmobile** [comment] 2015-03-04 08:00
may be I should not say UIAutomation.
I believe in any case Appium uses instrument to launch automation, using an automation template. It is not about what is used to interact.
why not try it manually? cmd + I then select automation, them perform the steps that generates the logs. See what happens?

**Comment by amedvedjev** [comment] 2015-03-05 21:14
we have very similar issue when we started appium in Java code as "Process process = Runtime.getRuntime().exec(some_arguments,executed_url);" - right after some amount of test execution = freeze without any error. the fix was is use "ProcessBuilder builder" instead. 

that is why i asked - how appium starting.

**Comment by LimeDang** [comment] 2015-03-06 03:18
Yes, I am using ProcessBuilder not Runtime to exec

I have thought that may be the buffer memory of Java is reach to the limitation when Appium log out, then I have tried to redirectOutput the log to a file to free the out put of Java. So I have tried 2 these ways:

ProcessBuilder pb = new ProcessBuilder(cmd);
Process process = pb.start();

or

ProcessBuilder pb = new ProcessBuilder(cmd);
pb.redirectOutput(new File(appiumLog));
Process process = pb.start();

But Appium is still freezed at that time !

**Comment by 0x1mason** [comment] 2015-03-09 01:09
This is probably related to issues we'be heard about with logging and memory leaks.

**Comment by AndrewDryga** [comment] 2015-03-14 18:40
We have same issue in our App, sometimes with disabled NSLog.

I think is corresponding to this post: http://stackoverflow.com/questions/26390000/application-hangs-when-profiling-with-instrument-in-xcode-6-0-1

**Comment by LimeDang** [comment] 2015-03-16 03:12
@AndrewDryga This issue is different with your issue, your NSLog issue is here https://github.com/appium/appium/issues/4032#issuecomment-70513517

**Comment by 0x1mason** [comment] 2015-04-03 14:21
@LimeDang This is when you have Appium log to file?

**Comment by LimeDang** [comment] 2015-04-05 08:20
Yes @0x1mason . I have tried these 2 ways and got the same result.

1. Using Appium server args to log to a file.

2. Do not using Appium server args to log to a file, but redirect output of java process to a file, this is the code:
ProcessBuilder pb = new ProcessBuilder(startAppiumServerCmd);
pb.redirectOutput(new File(appiumLog));
Process process = pb.start();

**Comment by 0x1mason** [comment] 2015-04-07 14:29
@LimeDang Does this repro with Instruments and no Appium?

I'm wondering if this isn't related to NSLog.  I haven't been able to repro so far.  Can you also try this workaround and let me know if it makes a difference? https://github.com/appium/appium/issues/4585#issuecomment-90549600

**Comment by jlipps** [comment] 2015-04-07 17:19
These are interesting workarounds. We could add them to our troubleshooting docs while we figure out whether there's something we can do on the Appium side.

**Comment by LimeDang** [comment] 2015-04-11 07:19
@0x1mason even I do not use (delete all) NSLog in the test application, the issue still happens.

**Comment by jlipps** [comment] 2015-04-20 23:20
@LimeDang does this reproduce when you are running the appium server on its own from the command line?

**Comment by knreddy036** [comment] 2016-06-29 06:59
Scripts are running very slow with appium 1.5.2 version , but with appium 1.4.3 version ,it is very fast .Suppose for each testscript in appium 1.4.3 ,it takes 80 sec ,but with appium 1.5.2 ,it is taking 400 sec .Any Idea how to fix this one ?

**Comment by knreddy036** [comment] 2016-06-29 07:00
Scripts are running very slow with appium 1.5.2 version , but with appium 1.4.3 version ,it is very fast .Suppose for each testscript in appium 1.4.3 ,it takes 80 sec ,but with appium 1.5.2 ,it is taking 400 sec .Any Idea how to fix this one ?

**Comment by SrinivasanTarget** [comment] 2016-07-26 08:24
Closing this because of inactivity.I dont see any issues been reported on Appium 1.5.x on this.

**Comment by SrinivasanTarget** [comment] 2016-07-26 08:24
@triager please close

**Closed by SrinivasanTarget** 2016-07-26 08:24 UTC
Labels: Bug, iOS
