### ISSUE TITLE
[XCTestDriver managerProxy]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by romainlouvet** [appium/appium#8114] opened 2017-03-28 13:45 UTC
## The problem

Trying to setValue of my XCUIElementTypeTextField after upgrading my iphone 10.3 & Xcode 8.3

## Environment

* Appium version : 1.6.3
* Java-client : 4.1.2
* Last Appium version that did not exhibit the issue (if applicable):
* Xcode 8.3
* Mobile platform/version under test: iOS 10.3
* Real device 

## Link to Appium logs

Appium server log
https://gist.github.com/romainlouvet/389f842c9c3ebd72448ed626fe42c692

Java-client log
https://gist.github.com/romainlouvet/9d915eed40ecb72529f11822dadd76a7

**Comment by mykola-mokhnach** [comment] 2017-03-28 13:48
Duplicate of https://github.com/facebook/WebDriverAgent/issues/465
Update Appium to 1.6.4-beta to have the recent WDA sources included.

**Closed by mykola-mokhnach** 2017-03-28 13:48 UTC

**Comment by romainlouvet** [comment] 2017-03-28 14:05
When I upgrade Appium 1.6.4-beta with new WDA

xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=67ce1f493620f9108ed0fe02df0b92536f6b6ab2' clean build test
->
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Categories/XCUIElement+FBClassChain.h:10:9: fatal error: could not build module 'XCTest'
#import <XCTest/XCTest.h>
 ~~~~~~~^
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 8.1.0 (clang-802.0.38)
Target: aarch64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.

2017-03-28 16:05:04.680 xcodebuild[5939:980225] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/romainlouvet/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/32A5D38F-8B72-4563-90D6-49D1F88AD5D9/Session-WebDriverAgentRunner-2017-03-28_160504-28pexA.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/romainlouvet/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/32A5D38F-8B72-4563-90D6-49D1F88AD5D9/Session-WebDriverAgentRunner-2017-03-28_160504-28pexA.log}

Testing failed:
	'XCUISiriService' is partial: introduced in iOS 10.3
	Could not build module 'XCTest'
** TEST FAILED **

**Comment by mykola-mokhnach** [comment] 2017-03-28 14:11
Try to replace /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent with WDA sources downloaded from recent [master](https://github.com/facebook/WebDriverAgent) and build this from Xcode.

**Comment by romainlouvet** [comment] 2017-03-28 14:37
same result with recent master @mykola-mokhnach

**Comment by mykola-mokhnach** [comment] 2017-03-28 14:43
I'd create an issue report for WDA then. This has nothing to do with Appium.

**Comment by mykola-mokhnach** [comment] 2017-03-28 15:05
Try [this patch](https://github.com/facebook/WebDriverAgent/pull/525/files) with your local source. It should do the job

**Comment by romainlouvet** [comment] 2017-03-29 08:23
Thanks ! @mykola-mokhnach
