### ISSUE TITLE
Appium 1.3.1, Xcode6.1 iOS 8.1 simulator - error: Could not reset simulator. Leaving as is. Error: Command failed:  // stderr: 

### ISSUE THREAD

**Issue by ywang24** [appium/appium#4042] opened 2014-11-12 17:37 UTC
I keep seeing this issue when I'm using Appium 1.3.1 inspector (I also get this problem through command line start sometimes), and if I get this error, I won't be able to launch iOS app through simulator even manually, I'll get a blackscreen. 

I have to restart my laptop to get my iOS simulator work again. I've tried to 'Reset Content and Settings', but it won't help. And run [xcrun simctl erase F615A835-3295-42ED-8BCA-398039748377] in command line is fine. Can anyone please give me some help here? Thank you very much!

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1","iOSSDKVersion":"8.1","deviceName":"iPhone 6","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1","iOSSDKVersion":"8.1","deviceName":"iPhone 6","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
info: [debug] Parsed app Info.plist (as binary)

info: [debug] Wrote new app Info.plist with device type
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons

info: [debug] Cleaning sim data files

info: [debug] Executing: xcrun simctl erase F615A835-3295-42ED-8BCA-398039748377

info: [debug] Executing: xcrun simctl erase F615A835-3295-42ED-8BCA-398039748377

info: [debug] Executing: xcrun simctl erase F615A835-3295-42ED-8BCA-398039748377

info: [debug] Executing: xcrun simctl erase F615A835-3295-42ED-8BCA-398039748377

info: [debug] Executing: xcrun simctl erase F615A835-3295-42ED-8BCA-398039748377

error: Could not reset simulator. Leaving as is. Error: Command failed:  // stderr: 

info: [debug] Cleaning app data files

info: Couldn't find app directories to delete. Probably it's not installed

info: [debug] Not setting locale
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS 8.* simulator log capture

info: [debug] Not pre-launching simulator

info: [debug] No device id or app, not installing to real device.
info: [debug] Starting command proxy.

info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: Launching instruments
info: [debug] Attempting to run app on iPhone 6 (8.1 Simulator)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 6 (8.1 Simulator)" /Users/ywang24/Library/Developer/Xcode/DerivedData/SamsClub-hjnpzezvbpydptbhjfdzvtzpncrn/Build/Products/Debug-iphonesimulator/SamsClub-iPhone.app -e UIASCRIPT "/Users/ywang24/Library/Application Support/appium/bootstrap/bootstrap-60f23230385b0cfa.js" -e UIARESULTSPATH /tmp/appium-instruments

info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6/InstrumentsShim.dylib","LIB_PATH":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6"}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST] Waiting for device to boot...

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:24 L-SB8L129FD5-M syslogd[8428]: --- syslogd restarted ---

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:24 L-SB8L129FD5-M syslogd[8428]: Configuration Notice:
info: [IOS_SYSLOG_ROW ] ASL Module "com.apple.cloudd" claims selected messages.
info: [IOS_SYSLOG_ROW ] Those messages may not appear in standard system log files or in the ASL database.
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:24 L-SB8L129FD5-M syslogd[8428]: Configuration Notice:
info: [IOS_SYSLOG_ROW ] ASL Module "com.apple.clouddocs" claims selected messages.
info: [IOS_SYSLOG_ROW ] Those messages may not appear in standard system log files or in the ASL database.
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:24 L-SB8L129FD5-M syslogd[8428]: Configuration Notice:
info: [IOS_SYSLOG_ROW ] ASL Module "com.apple.testmanagerd" claims selected messages.
info: [IOS_SYSLOG_ROW ] Those messages may not appear in standard system log files or in the ASL database.
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:00 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404]: assertion failed: 13F34: launchd_sim + 161136 [AAAFA861-0E11-3137-B438-BDDAD2793F55]: 0xd
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:00 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.instruments.deviceservice): The JetsamProperties key is not available on this platform.
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:00 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.assertiond): This service is defined to be constantly running and is inherently inefficient.

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:00 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.backboardd): Unknown key for Boolean: HighPriorityIO
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:00 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.backboardd): This service is defined to be constantly running and is inherently inefficient.
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:00 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.assetsd.nebulad): The JetsamProperties key is not available on this platform.
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:00 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.assetsd.notificationServer): The HideUntilCheckIn property is an architectural performance issue. Please transition away from it.
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:00 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.assetsd): The JetsamProperties key is not available on this platform.
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:01 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.calaccessd.xpc): The HideUntilCheckIn property is an architectural performance issue. Please transition away from it.
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:01 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.calaccessd): The JetsamProperties key is not available on this platform.
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:01 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.certui.relay): ThrottleInterval set to zero. You're not that important. Ignoring.
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:01 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.certui.relay): The JetsamProperties key is not available on this platform.

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:29 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.imfoundation.IMRemoteURLConnectionAgent): The _DirtyJetsamMemoryLimit key is not available on this platform.

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:29 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.accounts.dom): The _DirtyJetsamMemoryLimit key is not available on this platform.

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:30 L-SB8L129FD5-M.local configd_sim[8436]: network changed: v4(utun0+:172.29.223.160, en0+:192.168.1.102) DNS+ Proxy+

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:35 L-SB8L129FD5-M.local locationd[8432]: Logging binary sensor data to /Users/ywang24/Library/Developer/CoreSimulator/Devices/F615A835-3295-42ED-8BCA-398039748377/data/Library/Caches/locationd/locationdSensors.bin

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:36 L-SB8L129FD5-M.local locationd[8432]: NBB-Could not get UDID for stable refill timing, falling back on random

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:37 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.imfoundation.IMRemoteURLConnectionAgent): The _DirtyJetsamMemoryLimit key is not available on this platform.

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:39 --- last message repeated 1 time ---

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:39 L-SB8L129FD5-M.local CoreSimulatorBridge[8441]: Switching to keyboard: en

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"},"isShuttingDown":false},"sessionId":"ca127c4f-1750-4c0b-ae9d-e717bbdfa806"}

info: <-- GET /wd/hub/status 200 0.663 ms - 178 {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"},"isShuttingDown":false},"sessionId":"ca127c4f-1750-4c0b-ae9d-e717bbdfa806"}

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:51 L-SB8L129FD5-M.local distnoted[8541]: # distnote server daemon  absolute time: 1469.153415963   civil time: Wed Nov 12 08:57:51 2014   pid: 8541 uid: 358088359  root: yes

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:53 L-SB8L129FD5-M.local securityd[8546]: unable to access hwaes key

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:54 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.imfoundation.IMRemoteURLConnectionAgent): The _DirtyJetsamMemoryLimit key is not available on this platform.

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:54 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.imdpersistence.IMDPersistenceAgent): The _DirtyJetsamPriority key is not available on this platform.
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:54 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.imdpersistence.IMDPersistenceAgent): The _DirtyJetsamMemoryLimit key is not available on this platform.
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:54 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.lakitu): The JoinExistingSession key is not available on this platform.

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:55 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.imfoundation.IMRemoteURLConnectionAgent): The _DirtyJetsamMemoryLimit key is not available on this platform.

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:58 L-SB8L129FD5-M.local backboardd[8430]: void __IOHIDPlugInLoadBundles(): Loaded 0 HID plugins

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:58 L-SB8L129FD5-M.local backboardd[8430]: ____IOHIDSessionScheduleAsync_block_invoke: thread_id=0x109bd5000

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:58 L-SB8L129FD5-M.local backboardd[8430]: HID Session async scheduling initiated.
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:58 L-SB8L129FD5-M.local backboardd[8430]: HID Session async root queue running at priority 63 and schedule 2.
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:58 L-SB8L129FD5-M.local backboardd[8430]: HID Session async scheduling complete.
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:58 L-SB8L129FD5-M.local backboardd[8430]: Successfully opened the IOHIDSession
info: [IOS_SYSLOG_ROW ] Nov 12 08:57:58 L-SB8L129FD5-M.local lsd[8540]: LaunchServices: Seeding database

info: [IOS_SYSLOG_ROW ] Nov 12 08:57:59 L-SB8L129FD5-M.local identityservicesd[8427]: [Warning] DeviceHeartbeat - Failed loading device heartbeat data from keychain -25300

info: [IOS_SYSLOG_ROW ] Nov 12 08:58:03 L-SB8L129FD5-M.local installd[8426]: 0x109b7a310 main: Reboot detected

info: [IOS_SYSLOG_ROW ] Nov 12 08:58:05 L-SB8L129FD5-M.local fileproviderd[8421]: (Note ) FileProvider: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/FileProvider.framework/Support/fileproviderd starting.

info: [IOS_SYSLOG_ROW ] Nov 12 08:58:08 L-SB8L129FD5-M.local installd[8426]: 0x109b7a310 is_build_upgrade: Current build version (12B411) equal to last version recorded; skipping upgrade

info: [IOS_SYSLOG_ROW ] Nov 12 08:58:08 L-SB8L129FD5-M.local installd[8426]: 0x109b7a310 __47-[MIDeveloperDiskImageTracker checkMountPoint:]_block_invoke: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/Developer/Applications is not present now or before

info: [IOS_SYSLOG_ROW ] Nov 12 08:58:11 L-SB8L129FD5-M com.apple.CoreSimulator.SimDevice.F615A835-3295-42ED-8BCA-398039748377.launchd_sim[8404] (com.apple.imfoundation.IMRemoteURLConnectionAgent): The _DirtyJetsamMemoryLimit key is not available on this platform.

warn: Instruments socket client never checked in; timing out (global)

info: [debug] Killall instruments

info: [debug] [INSTSERVER] Instruments exited with code null

**Comment by malafeev01** [comment] 2015-04-20 10:01
@Jonahss this issue is still reproduced. Appium ver. 1.3.1, Xcode 6.2.
Interesting to note: when this issue is reproduced, all installed simulators disappear. I mean, after error happens, I go to the XCode -> Devices and usually I see here lots of simulators, but after it happened there are no simulators at all. If I want to start Appium again I'll get "Instruments socket client never checked in; timing out (global)" as described above. Simulators is restored automatically after system reboot.

**Comment by Jonahss** [comment] 2015-04-21 18:15
We changed the way we refresh simulators around that version of Appium, can you update to the latest version and try it there?

**Comment by Jonahss** [comment] 2015-05-11 23:27
Closing due to inactivity. If this is still an issue (seems possible) please comment here.

**Closed by Jonahss** 2015-05-11 23:27 UTC
Labels: NeedsTriage, OnGoing
