### ISSUE TITLE
Socket hang up error occurs on Sauce Labs iOS Simulators, during clean/setValue into Text Field

### ISSUE THREAD

**Issue by ochubey** [appium/appium#7818] opened 2017-02-07 12:24 UTC
## The problem

Socket hang up error occurs when tests are executed on Sauce Labs iOS Simulators, during clean/setValue into Text Field.
To reproduce this issue I've created [small project](https://github.com/ochubey/SetTextValueOnSimulatorWithAppium.git) and contacted Sauce Labs support. For now - this issue is 100% reproducible with example app (available to everyone) and application under test (cannot be shared). In case if tests would be executed with -DisXCUITest=true parameter (enables _setCapability("automationName", "XCUITest")_) - socket hangs up on 2nd/3rd iteration, otherwise - all 20 iterations of clean/setValue pass successfully.
Also issue is not reproducible locally with same codebase, Appium/iOS version and app tested.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3 (with XCUITest)
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3 (without XCUITest)
* Desktop OS/version used to run Appium: Mac 10.11
* Node.js version (unless using Appium.app|exe): not sure, Sauce Labs default VM configuration
* Mobile platform/version under test: iOS/9.3, 10.0
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

setCapability("automationName", "XCUITest") leads to socket hang up error with https://s3.amazonaws.com/appium/TestApp8.4.app.zip on Sauce Labs iOS Simulator.

## Link to Appium logs

https://gist.github.com/ochubey/55712a202bc54ce7618465adf11ab384
https://gist.github.com/ochubey/dff9b8c612c3a04aca80f1619d826025

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/ochubey/a7216c2c53bdee6db025dabc61fb1255 - simpliest way to reproduce the issue;
or https://github.com/ochubey/SetTextValueOnSimulatorWithAppium.git

**Comment by mykola-mokhnach** [comment] 2017-02-07 14:27
This might be a duplicate of https://github.com/appium/appium/issues/7801

The issue usually happens if CPU load on the target machine where test is running is too high. People say that disabling hardware keyboard for simulator sometimes helps to improve the thing.
Check https://github.com/facebook/WebDriverAgent/issues/453 for more details.

**Closed by mykola-mokhnach** 2017-02-07 14:27 UTC
Labels: NeedsTriage

**Comment by ochubey** [comment] 2017-02-07 14:48
Really quick resolution, @mykola-mokhnach.
So you'r saying that Sauce Labs providing machines with pure capabilities, so 2 minutes test fails?
Would try to dissable keyboard as you mentioned and report back about results.
