### ISSUE TITLE
NotImplementedError: Method is not implemented: /wd/hub/session/{session_id}/execute/sync - Appium: 1.9.1

### ISSUE THREAD

**Issue by vsadineni1** [appium/appium#11623] opened 2018-11-02 18:08 UTC
## The problem
I have updated my appium server version, iOS version after which my test is failing with the below error

[debug] [XCUITest] Executing command 'execute'
**[debug] [W3C] Encountered internal error running command: NotImplementedError: Method is not implemented**

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1 with iOS version: 12.0
* Last Appium version that did not exhibit the issue (if applicable): 1.8.0 with iOS version: 11.2
* Desktop OS/version used to run Appium: macOS High Sierra (10.13.6)
* Node.js version (unless using Appium.app|exe): $ node --version
v9.3.0)

* Mobile platform/version under test: iOS 12.0
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details

After upgrading my Appium server version: 1.9.1 (from 1.8.0) and iOS version: 12.0 (from 11.2), when I run the test, I see the below error:

[debug] [W3C] Responding to client with driver.findElements() result: [{"element-6066-11e4-a52e-4f735466cecf":"23000000-0000-0000-AC89-000000000000"}]
[HTTP] <-- POST /wd/hub/session/77c6e083-0310-4033-927b-4a8aa8f8dec8/elements 200 205 ms - 90
[HTTP] 
[HTTP] --> POST /wd/hub/session/77c6e083-0310-4033-927b-4a8aa8f8dec8/execute/sync
[HTTP] {"script":"return (function(){return function(){var k=this;function l(a){return void 0!==a}function m(a){return\"string\"==typeof a}function aa(a,b){a=a.split(\".\");var c=k;a[0]in c||!c.execScript||c.execScript(\"var \"+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&l(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}\nfunction ba(a){var b=typeof a;if(\"object\"==b)if(a){if(a instanceof Array)return\"array\";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(\"[object Window]\"==c)return\"object\";if(\"[object Array]\"==c||\"number\"==typeof a.length&&\"undefined\"!=typeof a.splice&&\"undefined\"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(\"[object Function]\"==c||\"undefined\"!=typeof a.call&&\"undefined\"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(\"call\"))return\"function\"}else return\"null\";\nelse if(\"function\"==b&&\"undefined\"==typeof a.call)return\"object\";return b}function ca(
[debug] [W3C] Calling AppiumDriver.execute() with args: ["return (function(){return function(){var k=this;function l(a){return void 0!==a}function m(a){return\"string\"==typeof a}function aa(a,b){a=a.split(\".\");var c=k;a[0]in c||!c.execScript||c.execScript(\"var \"+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&l(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}\nfunction ba(a){var b=typeof a;if(\"object\"==b)if(a){if(a instanceof Array)return\"array\";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(\"[object Window]\"==c)return\"object\";if(\"[object Array]\"==c||\"number\"==typeof a.length&&\"undefined\"!=typeof a.splice&&\"undefined\"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(\"[object Function]\"==c||\"undefined\"!=typeof a.call&&\"undefined\"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(\"call\"))return\"function\"}else return\"null\";\nelse if(\"function\"==b&&\"undefined\"==typeof a.call)return\"object\";return b}function ca(a,b,c){return a.call.apply(a.b...
[debug] [XCUITest] Executing command 'execute'
[debug] [W3C] Encountered internal error running command: NotImplementedError: Method is not implemented

## Link to Appium logs

Link to Gist - https://gist.github.com/vsadineni1/ba2955d8e7abd1a21e7bbe13a9e3adaf

## Code To Reproduce Issue [ Good To Have ]
I can not share the app code, but it is failing right on the first screen before we click on the "I Accept" eula button.

**Comment by mykola-mokhnach** [comment] 2018-11-02 18:09
Make sure your client is up to date. Closed as not a bug

**Closed by mykola-mokhnach** 2018-11-02 18:09 UTC

**Comment by vsadineni1** [comment] 2018-11-02 18:11
@mykola-mokhnach - Currently I am using appium java-client: 3.2.0. 
Is this the problem that I am using an older version of java-client?
What is the minimum version I should get upgraded to?

**Comment by mykola-mokhnach** [comment] 2018-11-02 18:12
You must either use the recent one (6.1.0) or avoid upgrading the server
