### ISSUE TITLE
Click function on an element, in a iOS mobile app is not doing anything, but shows 200 status for the click request

### ISSUE THREAD

**Issue by fottin** [appium/appium#13952] opened 2020-02-17 21:05 UTC
## The problem

[HTTP] <-- POST /wd/hub/session/4ffb0663-96c8-4d72-9e9a-a5c8de8ed96d/element/19000000-0000-0000-4602-000000000000/click 200 888 ms - 65

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac 10.15.2
* Node.js version (unless using Appium.app|exe): 10.16.3
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: iOS 13.3 iPhoneXs
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium.exe

## Details
I’m using Multiremote in the WDIO Testrunner with two different iPhone models. My page object model has a class called loginPage with a function called loginUser. loginUser begins by clicking on the login button. 
In my test script I created two instances of loginPage, one for each device. Example, 
let device1 = new loginPage(driver.device1);
let device2 = new loginPage(driver.device2);
device1.loginUser(userName);
device2.loginUser(userName);
Device2 responds to the button click and moves onto  the next screen, while device1 the screen does not change.
The logs look the same for each device with the exception of the sessionId and the elementId.

## Link to Appium logs

<script src="https://gist.github.com/fottin/097f42e4fd8e74ea62e9a492f17a5691.js"></script>

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2020-02-17 21:58
Possible duplicate of https://github.com/appium/appium/issues/13907

**Comment by fottin** [comment] 2020-02-18 16:31
I went back to testing one device at a time. I'm encountering the same problem. One device (iPhone 6, iOS 12.4.5) works fine and the other device (iPhone XS, iOS 13.3) fails to respond on the screen although the Appium logs show success. This is the same device that failed in Multiremote. Odd, the individual tests on that device (iPhone XS, iOS 13.3) were succeeding prior to MultiRemote testing. Don't understand what changed.

**Comment by KazuCocoa** [comment] 2020-02-21 07:54
`showIOSLog` and `showXcodeLog` might help to observe the behaviour.
If something happened in XCUITest layer, nothing can do in Appium side

**Comment by mykola-mokhnach** [comment] 2020-02-27 18:22
Closed as third party issue

**Closed by mykola-mokhnach** 2020-02-27 18:22 UTC
Labels: ThirdParty, XCUITest
