### ISSUE TITLE
can't switch back to NATIVE_APP view after switching context to  'WEBVIEW_com.tencent.mm:toolsmp'

### ISSUE THREAD

**Issue by Jesse1321** [appium/appium#16750] opened 2022-04-12 08:27 UTC
## The problem

when testing webview in WeChat app, after switching to 'WEBVIEW_com.tencent.mm:toolsmp', it works fine, but can't switch back to NATIVE_APP view

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: VIVO iQOO U3 + Android 10
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details
when tried to switch context back to native view, and try to find element by xpath, i got error like this:
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8210/wd/hub/session/dd2cfdf9-1dd3-4e82-87ba-ebdd2523fe33/element] with body: {"strategy":"xpath","selector":"(//android.widget.ImageView)[last()]","context":"","multiple":false}
[WD Proxy] Got response with status 500: {"sessionId":"dd2cfdf9-1dd3-4e82-87ba-ebdd2523fe33","value":{"error":"unknown error","message":"io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: Timed out after 15522ms waiting for the root AccessibilityNodeInfo in the active window. Make sure the active window is not constantly hogging the main UI thread (e.g. the application is being idle long enough), so the accessibility manager could do its work","stacktrace":"io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: Timed out after 15522ms waiting for the root AccessibilityNodeInfo in the active window. Make sure the active window is not constantly hogging the main UI thread (e.g. the application is being idle long enough), so the accessibility manager could do its work\n\tat io.appium.uiautomator2.core.AccessibilityNodeInfoDumper.findNodes(AccessibilityNodeInfoDumper.java:226)\n\tat io.appium.uiautomator2.utils.ElementLocationHelpers.getXPathNodeMatch(ElementLocatio...

## Link to Appium logs

https://gist.github.com/Jesse1321/9200324d70bac5822704c0fc4c7c5a9e

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment] 2022-04-12 09:01
This error is caused by UiAutomator framework itself and there is nothing that could be done from Appium side. Make sure the app under test is idling enough time (it would probably be necessary to change its source code for that).

**Comment by mykola-mokhnach** [comment] 2022-04-19 05:21
Closed as third party issue

**Closed by mykola-mokhnach** 2022-04-19 05:21 UTC
Labels: ThirdParty, NotABug, UIAutomator2

**Comment by aoaostar** [comment] 2023-02-15 09:55
Is this problem solved? I use wechat 32-bit normally (can switch back and forth), and 64-bit usage is abnormal (page_source empty after switching back to NATIVE_APP from webview).

**Comment by Jesse1321** [comment] 2023-07-06 06:41
@DanielWu0402 
use 1 session for wechat or wework
"appium -p 4723  --relaxed-security -U device_name --session-override --local-timezone --log-timestamp"
desired_capabilities:
'noReset': True,
'dontStopAppOnReset': True,

Then on webview page, recreate wechat driver, since 1 session is using, it will override the old session, and 'dontStopAppOnReset' is specified, wechat app will not stop and still open on webview page. 

        self.driver_wechat1 = webdriver.Remote('http://127.0.0.1:4723/wd/hub',desired_capabilities)

 hope this helps!
