### ISSUE TITLE
support iOS 8.2

### ISSUE THREAD

**Issue by jlipps** [appium/appium#4097] opened 2014-11-18 22:33 UTC
this is now in beta. adding to next feature milestone

**Comment by 0x1mason** [comment] 2015-01-06 23:52
@jlipps @imurchie Associating 8.2 support with 1.3.5.

**Comment by 0x1mason** [comment] 2015-01-06 23:53
Nm, closing because duplicate with #4278 .

**Comment by imurchie** [comment] 2015-01-07 00:00
Reopening, in case there is something that needs to happen when the full 6.2 xcode is released.

**Comment by moizjv** [comment] 2015-04-23 18:41
duplicate of #4828

**Closed by moizjv** 2015-04-23 18:41 UTC
