### ISSUE TITLE
Xcode 14 beta 3: Failed to build WDA as XCTAutomationSupport.framework/XCTAutomationSupport linking failure

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#17174] opened 2022-07-10 19:34 UTC
## The problem

This happens only `XCTAutomationSupport.framework/XCTAutomationSupport` included in Xcode 14 beta 3. `XCTAutomationSupport` in Xcode 14 beta 2 did not have. So as a workaround, you can use Xcode 14 beta 3 by replacing `XCTAutomationSupport` in Xcode 14 beta 3 with Xcode beta 2 for now.

(This does not mean Appium/WDA does not work on iOS 16 beta 3.)

mac2/WDA does not have this issue since it does not have a binary link to XCTAutomationSupport.

## Environment

* Xcode 14 beta 3 x https://github.com/appium/WebDriverAgent
    * not appium version dependent

## Details

Xcode build caused below errors:

- simulator (on an intel mac)
```
error build: Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture x86_64
```

- real device
```
error build: Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64
```

Xcode build example...:

```
xcodebuild build-for-testing -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=00008030-000C51E13C29802E IPHONEOS_DEPLOYMENT_TARGET=15.4 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
```

then:

```
ld: cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

So far, the workaround is to replace `XCTAutomationSupport.framework/XCTAutomationSupport` in beta 3 with the framework binary in beta 2.

## Code To Reproduce Issue [ Good To Have ]

Build Appium/WDA with Xcode 14 beta 3.

**Comment by mykola-mokhnach** [comment] 2022-07-10 20:11
We'd have to change WDA code to avoid dependencies on private frameworks. It looks like Apple is becoming more and more paranoid: https://developer.apple.com/forums/thread/124782

**Comment by Dan-Maor** [comment] 2022-07-11 11:33
Here are my findings upon an initial investigation:
- Apple are indeed make things a little more strict, looks like XCTest's private frameworks were compiled with `allowable_client` flags specifying which clients are allowed to link to the `XCTAutomationSupport` framework (new LC_SUB_CLIENT load commands were added).
> For dynamically linked shared libraries that are subframework of an umbrella framework they can allow clients other than the umbrella framework or other subframeworks in the same umbrella framework.  To do this the subframework is built with "-allowable_client client_name" and an LC_SUB_CLIENT load command is created for each -allowable_client flag.  The client_name is usually a framework name.  It can also be a name used for bundles clients where the bundle is built with "-client_name client_name".
- As of Xcode 14 beta 3 `XCTAutomationSupport` is defined to only allow the following clients: `AutomationInfrastructureIntegrationTests`, `IDEApplicationTests`, `IDETestingFoundationTests`, `IDEXcodeUITesting`, `XCTAutomationSupportTests`, `XCTDaemon`, `XCTDaemonControl`, `XCTDaemonControlTests`, `XCTDaemonTests`, `XCTHarness`, `XCTest-AppHostedTests`, `XCTest-PerformanceTests`, `XCTest-ToolHostedTests`, `XCTest-UITests-iOS`, `XCTest-UITests-macOS`, `XCTest-UITests-tvOS`, `XCTestCore`, `XCUIAutomation`, `XCUIRecorderService`, `testmanagerd`, `xctest`.
- We can tell the linker to use one of the whitelisted client names by adding `-client_name xctest` to the other linkers flags section of `WebDriverAgentLib`, however then the compiler will complain that the flag can only be used when building a _bundle_, not a _dynamic library_. Changing `WebDriverAgentLib`'s Mach-O type to Bundle will result in an inability for the main test bundle to link against it, stating that only dynamic libraries can be linked against.
- As of now, the only solution I can think of in order to build with Xcode 14 beta 3 is to change the project structure by removing the `WebDriverAgentLib` target entirely and add all linked libraries references, header files and source files directly to the WebDriverAgent runner targets. After combining this method with the added flag (the main test bundle is already defined as a Mach-O bundle type) and adding the frameworks search path from `WebDriverAgentLib` (so that the XCTest frameworks can be located during link time) I managed to get WebDriverAgent runner to run on a simulator and on my iPhone running the iOS 16.0 beta 3.

Information regarding load commands taken from here:
https://opensource.apple.com/source/cctools/cctools-921/include/mach-o/loader.h

**Comment by KazuCocoa** [comment] 2022-07-12 05:12
thank you for the detailed investigation @Dan-Maor 

Would you mind asking a question..? How did you find allowed clients you addressed as below?
> As of Xcode 14 beta 3 XCTAutomationSupport is defined to only allow the following clients:...


I initially guessed to remove dynamic links, but haven't tried well yet.

**Comment by Dan-Maor** [comment] 2022-07-12 07:16
@KazuCocoa I retrieved the list from Hopper by going through the load commands and listing the strings of the `LC_SUB_CLIENT` load commands.

They can also be retrieved in the same manner by using `otool -l` on the `XCTAutomationSupport` framework.

**Comment by KazuCocoa** [comment] 2022-07-12 17:14
thank you! I've learned the tool and the way...

**Comment by mykola-mokhnach** [comment] 2022-07-14 08:10
Closed as fixed

**Closed by mykola-mokhnach** 2022-07-14 08:10 UTC
Labels: OnGoing, TechDebt, XCUITest

**Comment by jagdish24** [comment] 2022-09-22 13:40
> Here are my findings upon an initial investigation:
> 
>     * Apple are indeed make things a little more strict, looks like XCTest's private frameworks were compiled with `allowable_client` flags specifying which clients are allowed to link to the `XCTAutomationSupport` framework (new LC_SUB_CLIENT load commands were added).
> 
> 
> > For dynamically linked shared libraries that are subframework of an umbrella framework they can allow clients other than the umbrella framework or other subframeworks in the same umbrella framework.  To do this the subframework is built with "-allowable_client client_name" and an LC_SUB_CLIENT load command is created for each -allowable_client flag.  The client_name is usually a framework name.  It can also be a name used for bundles clients where the bundle is built with "-client_name client_name".
> 
>     * As of Xcode 14 beta 3 `XCTAutomationSupport` is defined to only allow the following clients: `AutomationInfrastructureIntegrationTests`, `IDEApplicationTests`, `IDETestingFoundationTests`, `IDEXcodeUITesting`, `XCTAutomationSupportTests`, `XCTDaemon`, `XCTDaemonControl`, `XCTDaemonControlTests`, `XCTDaemonTests`, `XCTHarness`, `XCTest-AppHostedTests`, `XCTest-PerformanceTests`, `XCTest-ToolHostedTests`, `XCTest-UITests-iOS`, `XCTest-UITests-macOS`, `XCTest-UITests-tvOS`, `XCTestCore`, `XCUIAutomation`, `XCUIRecorderService`, `testmanagerd`, `xctest`.
> 
>     * We can tell the linker to use one of the whitelisted client names by adding `-client_name xctest` to the other linkers flags section of `WebDriverAgentLib`, however then the compiler will complain that the flag can only be used when building a _bundle_, not a _dynamic library_. Changing `WebDriverAgentLib`'s Mach-O type to Bundle will result in an inability for the main test bundle to link against it, stating that only dynamic libraries can be linked against.
> 
>     * As of now, the only solution I can think of in order to build with Xcode 14 beta 3 is to change the project structure by removing the `WebDriverAgentLib` target entirely and add all linked libraries references, header files and source files directly to the WebDriverAgent runner targets. After combining this method with the added flag (the main test bundle is already defined as a Mach-O bundle type) and adding the frameworks search path from `WebDriverAgentLib` (so that the XCTest frameworks can be located during link time) I managed to get WebDriverAgent runner to run on a simulator and on my iPhone running the iOS 16.0 beta 3.
> 
> 
> Information regarding load commands taken from here: https://opensource.apple.com/source/cctools/cctools-921/include/mach-o/loader.h

how to implement this flag? can you help me with that? i tried to install updated driver but still getting same issue.

**Comment by KazuCocoa** [comment] 2022-09-22 17:14
https://github.com/appium/WebDriverAgent/pull/596 fixed the situation. You can try it out with latest appium 2 and xcuitest driver. (the top of this issue's description described how to install it)

**Comment by ashwithpoojary98** [comment] 2022-10-12 10:23
tried with Appium 2 still issue is reproducible
[test2.log](https://github.com/appium/appium/files/9763985/test2.log)

**Comment by JeremyCaltranz** [comment] 2022-10-14 18:51
This item is closed but the fix given above doesn't resolve the build error. 

I removed Xcode completely

Installed Xcode version 14.1 beta 3

I then ran these commands:

npm install --location=global appium@next
appium driver install xcuitest
appium server --base-path=/wd/hub

Not sure what else to do on this... Any suggestions?

Error in Xcode is still: Cannot link directly with dylib/framework, your binary is not an allowed client of /Users/xxxxxxxxxxx/Documents/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64

**Comment by KazuCocoa** [comment] 2022-10-15 06:24
What about calling `appium driver uninstall xcuitest` once before the installation? Appium stuff is in `~/.appium` or APPIUM_HOME, so your local remained old WDA

**Comment by bwomsm1** [comment] 2022-10-20 05:54
Hi, 
I am still getting that issue:
```

Showing All Messages
Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64
```

I am not sure I understand what I should do from the thread above?

**Comment by JeremyCaltranz** [comment] 2022-10-24 23:15
Another note is to make sure the build is set to "Build for Testing":

<img width="548" alt="Screen Shot 2022-10-24 at 4 13 43 PM" src="https://user-images.githubusercontent.com/1087810/197647422-632489e9-8a65-46c5-9a19-d40557cc7fd9.png">

**Comment by bwomsm1** [comment] 2022-10-25 10:59
@KazuCocoa I am facing the problem too:
```
Showing All Messages
Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64
```
appium version - `2.0.0-beta.45`
xCode version - `14.0.1`
iOS device version - `16.0.0`

Please advise, Thanks!

**Comment by bwomsm1** [comment] 2022-10-25 11:10
I managed to build the `WebDriverAgent` with that version of https://github.com/appium/WebDriverAgent/releases/tag/v4.9.0

**Comment by KazuCocoa** [comment] 2022-10-25 15:47
Could you share the log with showXcodeLog caps as a GitHub GIST? (especially xcodebuild command and the result)

**Comment by KazuCocoa** [comment] 2022-10-25 17:52
Or maybe you can call `appium driver uninstall xcuitest` and install it again, or `appium driver update xcuitest`

**Comment by bwomsm1** [comment] 2022-10-25 17:58
Actually if I will be more precise, just uninstalling and reinstalling `xcuitest` was not enough, seems like there were some leftovers in `~/.appium/` folder.

**Comment by KazuCocoa** [comment] 2022-10-25 18:23
oh, i see, thanks for the info

**Comment by vmalakhov-salesforce** [comment] 2023-01-27 23:19
Can't run `appium driver install xcuitest`
/usr/local/bin/appium: error: unrecognized arguments: server

**Comment by KazuCocoa** [comment] 2023-01-28 06:23
What version of appium did you use?
If you already installed Appium 1.x, could you run `npm uninstall -g appium` before installing Appium 2.0 to avoid unexpected path handling?
https://github.com/appium/appium/blob/master/packages/appium/docs/en/guides/migrating-1-to-2.md

**Comment by vmalakhov-salesforce** [comment] 2023-01-29 04:24
@KazuCocoa thank you for quick response. After `npm uninstall -g appium` version of the Appium remains the same (1.22.3) How do I remove it completely?

**Comment by KazuCocoa** [comment] 2023-01-29 08:51
Have you installed it via `homebrew`? We don't provided homebrew officially, but you may be able to install appium via homebrew. Then, you need to uninstall it via homebrew as well.

**Comment by Haochenyu2021** [comment] 2023-02-23 03:41
I still got the error Unable build a WebDriver agent. Getting xcode build failed with code 65 from Appium with the following versions. Anyone please could help?
Appium 2
Appium desktop: 1.22.3
Xcode: 14.0.1
iOS MacOS: 13.2.1 
iOS simulator: 14.5
<img width="624" alt="image" src="https://user-images.githubusercontent.com/78565108/220816454-674e2268-1830-4596-9509-f4baf9cd8e3f.png">

**Comment by KazuCocoa** [comment] 2023-02-23 08:51
Not sure of the exact reason, but you may need to use appium inspector, and attach to the Appium 2

**Comment by Haochenyu2021** [comment] 2023-02-23 20:55
> Not sure of the exact reason, but you may need to use appium inspector, and attach to the Appium 2

I'm using inspector...😭

**Comment by jlipps** [comment] 2023-02-23 21:22
You need to use Appium Inspector, not Appium Desktop (you mentioned you are using Appium Desktop, which is not supported)

**Comment by Haochenyu2021** [comment] 2023-02-24 01:05
> 



> You need to use Appium Inspector, not Appium Desktop (you mentioned you are using Appium Desktop, which is not supported)
Appium 1.22.3 requires us to use Appium Inspector anyway.. so yes, I'm using Inspector

**Comment by KazuCocoa** [comment] 2023-02-24 08:00
Appium's server log has `xcodebuild` which Appium ran. You could run the same command by manual to see what error occurs.

**Comment by Haochenyu2021** [comment] 2023-02-25 03:59
> Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

In log the error is also Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

**Comment by KazuCocoa** [comment] 2023-02-25 05:59
Maybe it shows more information such as the code sign did not work etc, but your environment was for a simulator, and Appium 2 and newer XCUITest driver, then potentially some other issues might be there. Could you share the full log as GIST?

**Comment by Haochenyu2021** [comment] 2023-02-26 00:28
> Maybe it shows more information such as the code sign did not work etc, but your environment was for a simulator, and Appium 2 and newer XCUITest driver, then potentially some other issues might be there. Could you share the full log as GIST?

Hi @KazuCocoa Here is the log....
[appium-server-logs.txt](https://github.com/appium/appium/files/10832610/appium-server-logs.txt)

**Comment by KazuCocoa** [comment] 2023-02-26 03:10
Thanks, but I meant the vanilla xcodebuild instead of the Appium log at this time (sorry)

**Comment by Haochenyu2021** [comment] 2023-02-26 05:04
> Thanks, but I meant the vanilla xcodebuild instead of the Appium log at this time (sorry)

Thanks @KazuCocoa - I use xcrun simctl spawn <UDID> log stream | grep Appium to check the xcodebuild for the simulator, got no such file or directory for this UDID.
I guess there's no log created from xcode because from appium we could see: [xcodebuild error message:] is null here

**Comment by KazuCocoa** [comment] 2023-02-26 06:29
I meant xcodebuild with the below command directly.

> [debug] [35m[WebDriverAgent][39m Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/emily/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou -destination id=DFBB176D-22E6-42B3-B6BD-5B2C84F6ECB7 IPHONEOS_DEPLOYMENT_TARGET=15.0 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent'

I noticed you used Appium 1.22.3 embedded in Appium Desktop 1.22.3, which is not Appium 2 and newer Appium XCUITest driver. Our Appium inspector means https://github.com/appium/appium-inspector

**Comment by Haochenyu2021** [comment] 2023-02-26 07:04
> I meant xcodebuild with the below command directly.
> 
> > [debug] �[35m[WebDriverAgent]�[39m Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/emily/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou -destination id=DFBB176D-22E6-42B3-B6BD-5B2C84F6ECB7 IPHONEOS_DEPLOYMENT_TARGET=15.0 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent'
> 
> I noticed you used Appium 1.22.3 embedded in Appium Desktop 1.22.3, which is not Appium 2 and newer Appium XCUITest driver. Our Appium inspector means https://github.com/appium/appium-inspector

hi @KazuCocoa sorry for the version number - The correct ones should be:
Appium Server GUI 1.22.3  & Appium Inspector 2023.2.1

**Comment by KazuCocoa** [comment] 2023-02-27 01:26
Then, could you try out Appium 2.0 with latest appium-xcuitest-driver?

**Comment by Haochenyu2021** [comment] 2023-02-27 01:36
> Then, could you try out Appium 2.0 with latest appium-xcuitest-driver?

Hi @KazuCocoa - I'm using the latest appium-xcuitest-driver, which is 4.18.1

**Comment by KazuCocoa** [comment] 2023-02-27 01:38
Then, could you share the version's xcodebuild command result?

**Comment by Haochenyu2021** [comment] 2023-02-27 04:20
> Then, could you try out Appium 2.0 with latest appium-xcuitest-driver?

hey @KazuCocoa - just another question.. should we build Integration App onto simulator through xcode as well? How about WebDriverAgentLib and WebDriverAgentRunner?

**Comment by Haochenyu2021** [comment] 2023-02-27 04:47
> Then, could you share the version's xcodebuild command result?

I found I got an error of WebDriverAgentRunner-Runner.app
System: The bundle identifier for WebDriverAgentRunner-Runner.app couldn't be read
<img width="446" alt="image" src="https://user-images.githubusercontent.com/78565108/221476061-38f90859-0cff-4391-b6aa-06f4b203287d.png">
But I have successfully built WebDriverAgentLib, WebDriverAgentRunner, and IntegrationApp onto simulator from xcode

And another thing is my Appium folder is under usr\local\lib\node_modules
But appium drivers are under user\username\.appium\node_modules
Does this matter?

**Comment by KazuCocoa** [comment] 2023-02-27 09:01
The drivers' path was expected.  https://appium.github.io/appium/docs/en/2.0/guides/migrating-1-to-2/

Did you try out xcodebuild command the same as Appium 2 issued like below? (The below's one was what you shared before. In appium 2 appium log also may have the same `xcodebuild build-for-testing test-without-building ...` command result. I meant the entire build result.

> xcodebuild build-for-testing test-without-building -project /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/emily/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou -destination id=DFBB176D-22E6-42B3-B6BD-5B2C84F6ECB7 IPHONEOS_DEPLOYMENT_TARGET=15.0 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent

**Comment by dduphorn** [comment] 2023-05-04 20:47
I got the message error build: Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64

npm install --location=global appium@next
appium driver install xcuitest  # or "appium driver update xcuitest"
appium server --base-path=/wd/hub

Then I got the error /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64

I removed the XCTAutomationSupport Linked Binary and now I"m getting the error

Undefined symbol: _OBJC_CLASS_$_XCAccessibilityElement
Undefined symbol: _OBJC_CLASS_$_XCDeviceEvent
Undefined symbol: _OBJC_CLASS_$_XCElementSnapshot
Linker command failed with exit code 1 (use -v to see invocation)

Any idea what I'm missing?
