### ISSUE TITLE
appium-android-driver unlock using pattern does not work

### ISSUE THREAD

**Issue by CoryWritesCode** [appium/appium#11915] opened 2018-12-28 14:25 UTC
## The problem

When using the unlock capabilities set to 'pattern' it doesn't follow the correct pattern. Tested on Pixel 1 running android 8 and Samsung Galaxy S9 also on android 8.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1, tested also on 1.10.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac Mojave
* Node.js version (unless using Appium.app|exe): 10.3.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator:Pixel 1, Samsung Galaxy S9

## Link to Appium logs

https://gist.github.com/CoryWritesCode/af287ce1371508c0d7f2e1b38293a97b

**Comment by mykola-mokhnach** [comment] 2018-12-28 16:38
Duplicate of https://github.com/appium/appium/issues/10240
Feel free to commit a PR with a fix

**Closed by mykola-mokhnach** 2018-12-28 16:38 UTC
