### ISSUE TITLE
Unable to set value for iOS PickerWheel 

### ISSUE THREAD

**Issue by kcinman11358** [appium/appium#7695] opened 2017-01-14 20:10 UTC
## The problem

When attempting to set the value of a UIAPickerWheel, Appium thinks it sets the value, but does not. This used to work with Appium version 1.5.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3 (via command line)
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: MacMini iOS 10.12.2 Sierra
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:
* C# 3.0.0.1

## Details
This used to work, and appium thinks it is clicking on it, but it is not

## Link to Appium logs

https://gist.github.com/kcinman11358/ddf710914ae85016cce354cd860c3152

## Code To Reproduce Issue 
                driver.FindElement(By.ClassName("UIATextField")).ElementAt(1).Click(); //Click on the textbox to open pickerwheel
                driver.FindElement(By.ClassName("UIAPickerWheel")).SendKeys(account); //This should be setting the value of the picker wheel

**Comment by mykola-mokhnach** [comment] 2017-01-14 20:17
Possible duplicate of https://github.com/appium/appium/issues/6962

**Comment by amedvedjev** [comment] 2017-01-15 18:36
UIAPickerWheel ? with XCTest?

**Comment by kcinman11358** [comment] 2017-01-16 00:11
are you thinking it is not finding it @amedvedjev  ?

**Comment by amedvedjev** [comment] 2017-01-16 10:32
with XCUITest i use "XCUIElementTypePickerWheel"

**Comment by kcinman11358** [comment] 2017-01-16 22:25
are you able to interact with it using sendKeys?

Can you provide working code? I am unable to interact with it

**Comment by amedvedjev** [comment] 2017-01-17 08:14
@kcinman11358 yes. i am with 1.6.3. mine working code is:

`driver.findElement(MobileBy.className("XCUIElementTypePickerWheel")).setValue(countryName)`

**Comment by kcinman11358** [comment] 2017-01-17 15:11
@amedvedjev i'm guessing you are using java. I am using C# and don't have setValue as an option.

**Comment by kcinman11358** [comment] 2017-01-17 16:25
It came down to having to ask the dev the change the implementation. 

Hooray for TDD

**Closed** 2017-01-17 16:25 UTC
Labels: NeedsTriage

**Comment by ManishKabra** [comment] 2017-01-31 14:23
@kcinman11358  could you please explain the  implementation change done by developer?

In my case it's working for System date picker but not for Picker implemented by developer.
Current I am using  XCODE 8,iOS 10 and Appium1.6.3 version
It was working with XCode7,iOS 9 and below version and Appium1.5.3

**Comment by kcinman11358** [comment] 2017-01-31 17:12
@ManishKabra 

I sent my dev this and he knew what to do
https://github.com/appium/appium/issues/6962#issuecomment-264732117

**Comment by ManishKabra** [comment] 2017-02-07 18:40
@kcinman11358 : Thanks, our dev followed the same and it works for me too :+1:

**Comment by PraveenKumarQA** [comment] 2019-02-06 20:22
Hi, I may be late to the party but I was able to get around the problem using iOS - 11.4, Appium - 1.11.0-beta.3, node - v10.14.2
