### ISSUE TITLE
Appium shows "shortened" XML source for app screen from iOS & could not find element.

### ISSUE THREAD

**Issue by amokmen** [appium/appium#14020] opened 2020-03-03 13:08 UTC
## The problem

1. Appium shows "shortened" XML source for app screen from iOS.
2. Appium could not find element by `accessibility-id` at iOS (probably because 1).

## Environment

* Appium version: **1.16.0**
* Desktop OS/version used to run Appium: **macOS Catalina 10.15.3**
* Node.js version: **12.14.1**
* Npm package manager: **6.13.4**
* Mobile platform/version under test: **iOS 13.3**
* Real device or emulator/simulator: **Simulator iPhone 8**

## Details

There is React Native app. One element has `accessibility-id`/`content-desc` `'qwerty321'`.

I could find this element manually through **XCode** debug session (_menu Debug - View Debugging - Capture View Hierarchy_). And `accessibility-id` is there too.

But **Appium** could not find this element with _findElement()_. And even more strange thing - in app screen source, which I am getting with _getPageSource()_, there is no such element at all! It looks like source provided by **Appium** is not full!

## Appium log (partially)

```
2020-03-03 14:52:56:664 - [debug] [W3C (eb2479b5)] Calling AppiumDriver.findElement() with args: ["accessibility id","qwerty321","eb2479b5-70ce-419e-85fe-f5e7235eb9b2"]
2020-03-03 14:52:56:665 - [debug] [XCUITest] Executing command 'findElement'
2020-03-03 14:52:56:665 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
2020-03-03 14:52:56:665 - [debug] [BaseDriver] Waiting up to 20000 ms for condition
2020-03-03 14:52:56:667 - [debug] [WD Proxy] Matched '/element' to command name 'findElement'
2020-03-03 14:52:56:667 - [debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/155C6198-D2E6-4CDC-AD41-0A9AD3EB7D2C/element] with body: {"using":"accessibility id","value":"qwerty321"}
2020-03-03 14:52:56:787 - [WD Proxy] Got an unexpected response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'accessibility id', value 'qwerty321'","traceback":"(\n\t0   WebDriverAgentLib                   0x000000010deb3a0d FBNoSuchElementErrorResponseForRequest + 301\n\t1   WebDriverAgentLib                   0x000000010deb37b1 +[FBFindElementCommands handleFindElement:] + 433\n\t2   WebDriverAgentLib                   0x000000010de8fe76 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t3   WebDriverAgentLib                   0x000000010de7b2fb __37-[FBWebServer registerRouteHandlers:]_block_invoke + 555\n\t4   RoutingHTTPServer                   0x000000010df7ea43 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136\n\t5   RoutingHTTPServer                   0x000000010df7f356 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47\n\t6   libdispatch.dylib                   0x00007fff5223f7b9 _dispatch_client_callout + 8\n\t7   libdispatch.dylib                   0x00007fff522...
2020-03-03 14:52:56:787 - [debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
...
trying to find until timeout
```

## Same part from XML-source from iOS and Android

iOS (missed child elements)
```
<XCUIElementTypeOther type="XCUIElementTypeOther" name="Something here" label="Something here" enabled="true" visible="true" x="0" y="336" width="375" height="189">
    <XCUIElementTypeOther type="XCUIElementTypeOther" name="here is accessibility-id" label="Something here" enabled="true" visible="true" x="0" y="336" width="375" height="53"/>
        here should be missed child element (with 2 more) with accessibility-id
</XCUIElementTypeOther>
```
Android (all are OK; element that I want to find is one with `content-desc="qwerty321"`)
```
<android.view.ViewGroup index="2" package="pkg_name_here" class="android.view.ViewGroup" text="" content-desc="here is content-desc" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,968][1080,1126]" displayed="true">
    <android.view.ViewGroup index="0" package="pkg_name_here" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[46,968][1034,1126]" displayed="true">
        <android.widget.TextView index="0" package="pkg_name_here" class="android.widget.TextView" text="Something here 1" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[46,1017][442,1085]" displayed="true" />
        <android.widget.TextView index="1" package="pkg_name_here" class="android.widget.TextView" text="Something here 2" content-desc="qwerty321" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[787,1017][972,1085]" displayed="true" />
        <android.widget.TextView index="2" package="pkg_name_here" class="android.widget.TextView" text="Something here 3" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[986,1027][1033,1075]" displayed="true" />
    </android.view.ViewGroup>
</android.view.ViewGroup>
```

**Comment by amedvedjev** [comment] 2020-03-03 16:55
Missing elements is common iOS XCUITest problem. Specially when elements are putting inside button element.

We struggle this with help of iOS dev by putting needed elements mapping accesibility elements in init funtion. In such case they appear in page source outside e.g. button in tree BUT we can see and interact with them.

**Comment by mykola-mokhnach** [comment] 2020-03-03 21:33
Duplicate of https://github.com/appium/appium/issues/13958

**Comment by mykola-mokhnach** [comment] 2020-03-03 21:34
Consider switching to web view mode while testing hybrid apps

**Closed by mykola-mokhnach** 2020-03-03 21:33 UTC

**Comment by amokmen** [comment] 2020-03-04 06:56
> Consider switching to web view mode while testing hybrid apps

Our app is not hybrid. And has no Web View context:
```
currentContexts -->  [ 'NATIVE_APP' ]
```

**Comment by amokmen** [comment] 2020-03-04 07:36
Thank you for response! 

> Missing elements is common iOS XCUITest problem.
_(Enraged crying)_

> We struggle this with help of iOS dev by putting needed elements mapping accesibility elements in init funtion. In such case they appear in page source outside e.g. button in tree BUT we can see and interact with them.
My dev said that we probably could not use your advice because our app is React Native based...

**Comment by amokmen** [comment] 2020-03-04 07:40
@amedvedjev Thank you for response!

> Missing elements is common iOS XCUITest problem.

_(Enraged crying)_

> We struggle this with help of iOS dev by putting needed elements mapping accesibility elements in init funtion. In such case they appear in page source outside e.g. button in tree BUT we can see and interact with them.

My dev said that we probably could not use your advice because our app is React Native based...
But could you explain it a bit more?
