### ISSUE TITLE
Update appium-remote-debugger to 5.7.0, but there is no adaptation

### ISSUE THREAD

**Issue by fb0122** [appium/appium#15301] opened 2021-04-26 08:44 UTC
## The problem

It seems that appium-ios-driver 4.8.0 depends on appium-remote-debug 5.7.0, but it is not adapted。

## Environment

* Appium version : 1.20.2。（Install via npm）

## Details

It seems that appium-ios-driver 4.8.0 depends on appium-remote-debug 5.7.0, but it is not adapted. For example WebKitRemoteDebugger no longer exists，but context.js is still in use.

**Comment by mykola-mokhnach** [comment] 2021-04-26 09:28
Duplicate of https://github.com/appium/appium/issues/14513

Feel free to make a PR to deprecate that component. It would greatly help the project

**Closed by mykola-mokhnach** 2021-04-26 09:28 UTC
