### ISSUE TITLE
In listview, isDisplayed() and isSelected() return incorrect value

### ISSUE THREAD

**Issue by maesiva** [appium/appium#8664] opened 2017-06-13 18:29 UTC
## The problem

In a scrollable List View, for an element that is not currently on the screen, isDisplayed() returns true.
For all the elements that are available in the list, isDisplayed() returns true.

And, isSelected() always returns false, even if the element is selected.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): v6.3.0
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Samsung Galaxy Tab S2
* Appium CLI or Appium.app|exe: appium 1.6.5 via command mode
* App: Cordova based hybrid app, release version (without webview) and on native view.

## Details

isDisplayed() should return false when the element is currently not on screen.
isSelected() should return true when the element is selected in the list.

## Code To Reproduce Issue [ Good To Have ]

	String item01_xp = "//android.view.View[@content-desc='Item_01']";
	String item25_xp = "//android.view.View[@content-desc='Item_25']";
	WebElement e1 = driver.findElement(By.xpath(item01_xp)); //item is visible on screen and seleted
	WebElement e2 = driver.findElement(By.xpath(item25_xp)); // item is not visible on screen. its down in the scroll list.

	System.out.println("isDisplayed()" + e1.isDisplayed());
	System.out.println("isSelected()" + e1.isSelected());

	System.out.println("isDisplayed()" + e2.isDisplayed());
	System.out.println("isSelected()" + e2.isSelected());

>> actual output:
true
false
true
false

>> expected output:
true
true
false
false

**Comment by amedvedjev** [comment] 2017-06-14 12:03
if element outside screen = it should not be found in android and thus produce null pointer exception with your code.  so it is look like something was found and you can check it location and size where is it on screen :-)

**Comment by maesiva** [comment] 2017-06-14 16:28
In this case, no null pointer exception (element is found).  When I get the location of it, it gives the bottom edge point of the list area, which is incorrect.

**Comment by dpgraham** [comment] 2017-07-21 21:50
Can you provide the Appium logs

**Comment by maesiva** [comment] 2017-07-21 23:06
Sure. Would you mind sharing an email id to send the logs?
Due to corp policy, I won't be able to post the logs over here/gist..
Thank you.

**Comment by maesiva** [comment] 2017-07-24 21:10
Sent logs, code, screenshot. Thanks.

**Comment by dpgraham** [comment] 2017-07-28 21:33
I don't see any errors in the logs. I think it's probably an issue with UIAutomator2 (the underlying test framework) and not an Appium issue.

Have you tested using appium desktop?

**Comment by maesiva** [comment] 2017-07-28 22:00
Yup.. there is no error as such.
but, the values returned by the methods are incorrect.

Yes, had tried with Appium desktop 1.1.0 beta, same behaviour.
I see there is a new release of Appium desktop 1.1.1 today. I will check with that too and update the results.
Thanks.

**Comment by jlipps** [comment] 2017-08-14 20:48
@dpgraham do you know what uiautomator methods are being called behind the scenes in response to the isDisplayed and isSelected appium client methods?

**Comment by dpgraham** [comment] 2017-08-14 21:25
I'm not sure. I just searched uiautomator driver for 'isDisplayed' and found nothing.

**Comment by jlipps** [comment] 2017-08-29 22:22
@dpgraham I did some research. It looks like to determine "displayed" we are getting whether the element has accessibilityNodeInfo (https://github.com/appium/appium-uiautomator2-server/blob/ba99ab6e757c5df266e8a1db16949b699b2b1c82/app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java#L114). And to determine "selected" we are getting the `isSelected()` value of the accessibility node (https://github.com/appium/appium-uiautomator2-server/blob/9a6eb9947c1b646c056d1bcc4a7aa632d83b1ff4/app/src/main/java/io/appium/uiautomator2/model/UiAutomationElement.java#L82). I'm not sure how these map to common understandings of "displayed" and "selected". Can you comment, @sravanmedarapu?

**Comment by jlipps** [comment] 2017-09-15 18:41
going to mark this as a P1 bug, looks like clarification is necessary

**Comment by vsadineni1** [comment] 2017-11-15 00:32
@jlipps Any idea when this bug will be fixed? Appium 1.7.2? We have some tests failing.

**Comment by vmaxim** [comment] 2017-11-15 09:53
https://issuetracker.google.com/issues/37122135

**Comment by vmaxim** [comment] 2017-11-15 09:55
@vsadineni1 Can you provide steps to reproduce your issues?

**Comment by lanzelot1989** [comment] 2017-12-20 13:07
We have the same problem where a new view is stacked on top of another one when navigating away from it.

**Comment by vsadineni1** [comment] 2018-03-05 15:30
I have a simple html page with one web element. When I looked Appium Desktop inspector, I found that appium think the element is not shown as displayed. Please see the below screen-shot.

We noticed this issue after upgrading to Selenium 3.6. It was working fine with Selenium 2.5.3.

appium: 1.7.2
selenium: 3.6

Appium Desktop Screen-shot shown below.
![image](https://user-images.githubusercontent.com/24640164/36982356-9027633c-2044-11e8-8902-c1f3c1432316.png)

I have created gist file for the html view. I am trying to click on the '**Tap to Test**' element.

Here is the source code: https://gist.github.com/vsadineni1/63dc2fef49e68383033df9237861a5ed

Html Page source: UiTest.html
Test Code: IOSDriverUtilImplTest.java
Implementation: IOSDriverUtilImpl.java


Test Name: **testTapOnElement** in the file IOSDriverUtilTest.java

This is the error message I get:
_org.openqa.selenium.WebDriverException: Error Domain=com.facebook.WebDriverAgent Code=1 "The element '"Tap to Test" StaticText' is not visible on the screen and thus is not interactable" UserInfo={NSLocalizedDescription=The element '"Tap to Test" StaticText' is not visible on the screen and thus is not interactable}_

Session ID: 0b9dbf42b77247cd82ceb94f456c5db4
at sun.reflect.GeneratedConstructorAccessor8438.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
at test.util.webdriver.SfdcRemoteWebDriver.execute(SfdcRemoteWebDriver.java:212)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
at sun.reflect.GeneratedMethodAccessor1301.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:376)
at com.sun.proxy.$Proxy960.click(Unknown Source)
at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.click(EventFiringWebDriver.java:389)
at test.util.webdriver.IOSDriverUtilImpl.tap(IOSDriverUtilImpl.java:147)
at test.frameworktest.uiautomation.infrastructure.IOSDriverUtilTest.testTapOnElement(IOSDriverUtilTest.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by mykola-mokhnach** [comment] 2018-08-21 09:35
The inspector simply shows what UIA framework provides to it. Please raise the issue to Google or switch the automation name.

**Closed** 2018-08-21 09:36 UTC
Labels: Android, ThirdParty
