### ISSUE TITLE
safari tests fails due to default page apple.com

### ISSUE THREAD

**Issue by zhangmeng712** [appium/appium#5188] opened 2015-06-01 06:01 UTC
Hi, I'm using webdriverIO and Appium to test for webapp in safari, my appium config is as followings

,my code is as followings , when I execute the code, the simulator runs but it stucks with apple.com, and load the page for 4 more times without opening my page, is there any solutions?
var webdriverio = require('webdriverio');
var options = {
    host: 'localhost',
    port: 4999,
    desiredCapabilities: {
        'browserName': 'Safari',
        'appiumVersion': '1.3.7',
        'deviceName': 'iPhone 5s',
        'device-orientation': 'portrait',
        'platformVersion': '8.2',
        'platformName': 'iOS',
        'app': 'safari'
    }
};
webdriverio
    .remote(options)
    .init()
    .url('http://www.google.com')
    .title(function(err, res) {
        console.log('Title was: ' + res.value);
    })

**Comment by imurchie** [comment] 2015-06-01 15:52
What version of Xcode are you using?

**Comment by jlipps** [comment] 2015-06-01 16:43
looks like a duplicate of #4865

**Comment by zhangmeng712** [comment] 2015-06-02 03:20
xcode version 6.2, Appium version 1.3.7, and it happens when using new tab to open new url in safari default setting, any solution?

**Comment by sebv** [comment] 2015-06-03 08:31
Try to upgrade to 1.4, the logic has been modified to skip the apple page.

**Comment by zhangmeng712** [comment] 2015-06-04 14:23
hi, sebv   I'v using appium-1.3.7.dmg on mac, where I can get appium version 1.4?

**Comment by sebv** [comment] 2015-06-10 05:03
```
npm install appium -g 
```

**Comment by moizjv** [comment] 2015-06-20 00:12
@zhangmeng712 did you manage to get it working?

**Comment by moizjv** [comment] 2015-06-25 20:04
Closing due to inactivity. This has been fixed in 1.4.6

**Closed by moizjv** 2015-06-25 20:04 UTC
Labels: iOS, NoActivity
