### ISSUE TITLE
Xcode version 9.0 not yet supported message shown while launching the Simulator

### ISSUE THREAD

**Issue by kommuswamy** [appium/appium#9124] opened 2017-08-30 12:07 UTC
## The problem
While launching the simulator through the appium gui , I am unable to launch the simulator and I am seeing an error Xcode version not yet supported error message. I have attached gist folder for logs.
**## Environment**

* Appium version (or git revision) that exhibits the issue: 1.6.5 (1.1.1)and latest beta version 1.2.0 beta 3
* Desktop OS/version used to run Appium: 10.12.6
* Node.js version (unless using Appium.app|exe): 6.11.2
* Mobile platform/version under test: iOS 11.0 /MAC
* Real device or emulator/simulator: Simulator

## Link to Appium logs
<script src="https://gist.github.com/kommuswamy/acdd8552fcd10ca0d1bf6c943c192fb3.js"></script>

**Comment by kommuswamy** [comment] 2017-08-30 12:08
appium logs : https://gist.github.com/kommuswamy/acdd8552fcd10ca0d1bf6c943c192fb3

**Comment by mykola-mokhnach** [comment] 2017-08-30 12:08
Closed as duplicate of https://github.com/appium/appium/issues/9072

**Closed by mykola-mokhnach** 2017-08-30 12:08 UTC
