### ISSUE TITLE
Switch to frame is not working in mobile safari(IOS)

### ISSUE THREAD

**Issue by anshu1987** [appium/appium#11075] opened 2018-07-19 13:43 UTC
## The problem

WebDriver for Appium iOS real device doesn't switch to nested inner iframe.

## Environment
Appium version (or git revision) that exhibits the issue: 1.8.0-beta
Desktop OS/version used to run Appium: macOS High Sierra 10.13.5
Mobile platform/version under test: iOS
Real device or emulator/simulator: Real Device , Safari Browser

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

Appium Log:

[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":18,\"value\":{\"message\":\"Blocked a frame with origin \"https://something.com\" from accessing a frame with origin \\...'

[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"newCommandTimeout":6000,"platformVersion":"11.3","automationName":"XCUITest","browserName":"safari","javascriptEnabled":true,"startIWDP":true,"udid":"auto","platformName":"iOS","version":"","deviceName":"iPhone","platform":"MAC"},{},{"desiredCapabilities":{"newCommandTimeout":6000,"platformVersion":"11.3","automationName":"XCUITest","browserName":"safari","javascriptEnabled":true,"startIWDP":true,"udid":"auto","platformName":"iOS","version":"","deviceName":"iPhone","platform":"MAC"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"iOS"},"firstMatch":[{"browserName":"safari"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1532009527392 (19:42:07 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.87.0) session
[Appium] Capabilities:
[Appium]   newCommandTimeout: 6000
[Appium]   platformVersion: 11.3
[Appium]   automationName: XCUITest
[Appium]   browserName: safari
[Appium]   javascriptEnabled: true
[Appium]   startIWDP: true
[Appium]   udid: auto
[Appium]   platformName: iOS
[Appium]   version: 
[Appium]   deviceName: iPhone
[Appium]   platform: MAC
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"newCommandTimeout":6000,"...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: javascriptEnabled, version, platform.
[BaseDriver] Session created with session id: 7aa452b0-e60e-49b7-8f90-4446f797d2c8

[debug] [RemoteDebugger] Found handler for message '40'

[MJSONWP] Encountered internal error running command: Error: Error while executing atom: Blocked a frame with origin "https://something-..com" from accessing a frame with origin "https://something.com". Protocols, domains, and ports must match. (status: 18)

  at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/web.js:197:11)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)

    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

    at <anonymous>

Cannot access iframe content on iOS test due to same-origin policy #9464 , 
The other similar issue are also in closed state  :t ( #5560 #5553 #5832 ).

Can you please help with the issue?

**Comment by mykola-mokhnach** [comment] 2018-07-19 16:32
Duplicate of https://github.com/appium/appium/issues/10184

**Closed by mykola-mokhnach** 2018-07-19 16:32 UTC
