### ISSUE TITLE
Appium 1.12.1: Could not find a driver for automationName 'appium' and platformName 'Android'.

### ISSUE THREAD

**Issue by ikhaled28** [appium/appium#12408] opened 2019-03-29 09:48 UTC
## The problem
Encountered internal error running command: Error: Could not find a driver for automationName 'appium' and platformName 'Android'. Please check your desired capabilities.
Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). 

## Environment

* Appium version: (or git revision) that exhibits the issue: 1.12.1 
* Last Appium version that did not exhibit the issue (if applicable): 1.10.0 
* Desktop OS/version used to run Appium: MacOS Mojave 10.14.4
* Using Appium App/NodeJs : 11.6.0
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Deivce
* Appium CLI or Appium.app|exe: Appium.app

## Details
My desired capabilities : 

{
  "app": "/users/izabulkhaled/appium/app-storeFlavor-debug.apk",
  "platformName": "Android",
  "udid": "01f14a5aa04c4df8",
  "deviceName": "Google Pixel 3",
  "automationName": "appium",
  "appWaitActivity": "de.*",
  "noReset": true
}

I am trying to run the app from inspector but its showing the above error. It works fine with uiautomator2 but for some purposes I need the default appium automation also.

## Link to Appium logs

https://gist.github.com/ikhaled28/cd47df687c8226455f360b67d1a5cab7

## Code To Reproduce Issue [ Good To Have ]

Just setup any compatibility set with automation name appium and platformName android.

**Comment by mykola-mokhnach** [comment] 2019-03-29 12:26
Duplicate of https://github.com/appium/appium/issues/12383

**Closed by mykola-mokhnach** 2019-03-29 12:26 UTC

**Comment by ikhaled28** [comment] 2019-03-29 12:29
But it didn't solved for appium if I am not wrong.

**Comment by imurchie** [comment] 2019-03-29 15:25
@ikhaled28 Remove the `automationName` capability.
