### ISSUE TITLE
Grid 4 setup for Appium

### ISSUE THREAD

**Issue by thangaraj-d** [appium/appium#15305] opened 2021-04-27 09:09 UTC
## The problem

I have tried to setup the grid 3 for Appium but i'm not able to register the node, while connecting the node getting the following error:
"An attempt to register with the grid was unsuccessful: Request failed with status code 404
[debug] [Appium] Hub down or not responding: Request failed with status code 404"

As per the official site (Please note Grid 3 is not supported anymore and the Selenium project recommends to use Grid 4) the Grid 3 will not work anymore, So i tried to setup the Appium in Grid 4 but there is no proper commands to register the Appium node to the respective hub.

I would be very thankful if i get the commands for setup the Grid 4 in Appium. Looking forward to get the update from your end.

<img width="973" alt="Screenshot 2021-04-27 at 2 31 06 PM" src="https://user-images.githubusercontent.com/83275421/116215572-6e5c2480-a765-11eb-8ea7-1c547398e1f6.png">

**Comment by mykola-mokhnach** [comment] 2021-04-27 09:55
Duplicate of https://github.com/appium/appium/issues/14848

**Closed by mykola-mokhnach** 2021-04-27 09:55 UTC
