### ISSUE TITLE
Unable to start appium ( 1.6.1 beta ) in iPad “Error: Command ‘idevicedate -u … exited with code 255:” - Works fine on Simulator

### ISSUE THREAD

**Issue by Kirubaharan235** [appium/appium#7569] opened 2016-12-19 13:21 UTC
## The problem
iOS : JAVA : Eclipse : Appium 1.6.1 beta :Unable to start WebDriverAgent: Error: Command 'idevicedate -u 8fxxxxxxxxxx4a2aa6154cf29bd79ac6cd93686c' exited with code 255

I am running appium for iOS using iPad 9.3.3 using JAVA in ECLIPSE.

Just now I updated to appium 1.6.1 beta and tried running the code which was running OK with 1.6.0.
But I am getting the below error.

"Unable to start WebDriverAgent: Error: Command 'idevicedate -u 8fxxxxxxxxxx4a2aa6154cf29bd79ac6cd93686c' exited with code 255"

unable to proceed. I tried updating libimobiledevice,but still no help.
Please help.

## Environment
iOS : JAVA : Eclipse : Appium 1.6.1 beta

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs
Below are the logs:

Starting Appium
[Appium] Welcome to Appium v1.6.1-beta
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.1-beta","revision":null}}
_[HTTP] <-- GET /wd/hub/status 200 19 ms - 88 _
Appium server started http://0.0.0.0:4723/wd/hub
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/kiruba-3665/Library/Developer/Xcode/DerivedData/zohoform-apfvajhhubdtpddzzgymxvssgkev/Build/Products/Release-iphoneos/Zoho Forms.app","noReset":true,"version":"","deviceName":"Zoho forms testing iPad","fullReset":false,"platform":"iOS","realDeviceLogger":"/usr/local/lib/nodemodules/deviceconsole/deviceconsole","platformVersion":"9.3.3","automationName":"XCUITest","locationContextEnabled":true,"browserName":"","coreSimulator":"/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework","udid":"8faa9215c8314a2aa6154cf29bd79ac6cd93686c","platformName":"iOS"}}_
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/kiruba-3665/Library/Developer/Xcode/DerivedData/zohoform-apfvajhhubdtpddzzgymxvssgkev/Build/Products/Release-iphoneos/Zoho Forms.app","noReset":true,"version":"","deviceName":"Zoho forms testing iPad","fullReset":false,"platform":"iOS","realDeviceLogger":"/usr/local/lib/nodemodules/deviceconsole/deviceconsole","platformVersion":"9.3.3","automationName":"XCUITest","locationContextEnabled":true,"browserName":"","coreSimulator":"/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework","udid":"8faa9215c8314a2aa6154cf29bd79ac6cd93686c","platformName":"iOS"},null,null,null,null]_
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium] app: '/Users/kiruba-3665/Library/Developer/Xcode/DerivedData/zohoform-apfvajhhubdtpddzzgymxvssgkev/Build/Products/Release-iphoneos/Zoho Forms.app'
[Appium] noReset: true
[Appium] version: ''
[Appium] deviceName: 'Zoho forms testing iPad'
[Appium] fullReset: false
[Appium] platform: 'iOS'
[Appium] realDeviceLogger: '/usr/local/lib/nodemodules/deviceconsole/deviceconsole'_
[Appium] platformVersion: '9.3.3'
[Appium] automationName: 'XCUITest'
[Appium] locationContextEnabled: true
[Appium] browserName: ''
[Appium] coreSimulator: '/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework'
[Appium] udid: '8faa9215c8314a2aa6154cf29bd79ac6cd93686c'
[Appium] platformName: 'iOS'
[debug] [XCUITest] XCUITestDriver version: 2.4.3
[BaseDriver] The following capabilities were provided, but are not recognized by appium: version, platform, locationContextEnabled, coreSimulator.
[BaseDriver] Session created with session id: d93b29e1-e97d-4dac-ad8e-d44601cc0d1f
[debug] [XCUITest] Xcode version set to '7.3'
[debug] [XCUITest] iOS SDK Version set to '9.3'
[debug] [XCUITest] Available devices: 8faa9215c8314a2aa6154cf29bd79ac6cd93686c
[debug] [XCUITest] Creating iDevice object with udid 8faa9215c8314a2aa6154cf29bd79ac6cd93686c
[XCUITest] Determining device to run tests on: udid: '8faa9215c8314a2aa6154cf29bd79ac6cd93686c', real device: true
[BaseDriver] Using local app '/Users/kiruba-3665/Library/Developer/Xcode/DerivedData/zohoform-apfvajhhubdtpddzzgymxvssgkev/Build/Products/Release-iphoneos/Zoho Forms.app'
[debug] [XCUITest] Checking whether app '/Users/kiruba-3665/Library/Developer/Xcode/DerivedData/zohoform-apfvajhhubdtpddzzgymxvssgkev/Build/Products/Release-iphoneos/Zoho Forms.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/Users/kiruba-3665/Library/Developer/Xcode/DerivedData/zohoform-apfvajhhubdtpddzzgymxvssgkev/Build/Products/Release-iphoneos/Zoho Forms.app': 'com.zoho.zohoform'
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using WDA path: '/usr/local/lib/nodemodules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'_
[XCUITest] Using WDA agent: '/usr/local/lib/nodemodules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'_
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger '/usr/local/lib/nodemodules/deviceconsole/deviceconsole'_
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/nodemodules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=8fxxxxxxxxxx4a2aa6154cf29bd79ac6cd93686c -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'_
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u 8fxxxxxxxxxx4a2aa6154cf29bd79ac6cd93686c' exited with code 255
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u 8faa9215c8314a2aa6154cf29bd79ac6cd93686c' exited with code 255
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Reset not set, continuing
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: undefined
[HTTP] <-- POST /wd/hub/session 500 1937 ms - 262

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment] 2016-12-19 14:01
What is the problem when you update `libimobiledevice`? You will need to uninstall the old one and install the latest:

```
brew uninstall libimobiledevice
brew install libimobiledevice --HEAD
```

**Comment by Kirubaharan235** [comment] 2016-12-20 05:24
Hi imurchie,
The problem is not with libimobiledevice. I already have the latest version 1.2.0.(if thats the latest version).
I am getting the error 
"Unable to start WebDriverAgent: Error: Command 'idevicedate -u 8fxxxxxxxxxx4a2aa6154cf29bd79ac6cd93686c' exited with code 255".

So I thought it could be a problem with old version of libimobiledevice. But it seems that I have the latest version.

**Comment by Kirubaharan235** [comment] 2016-12-20 07:45
Also I tried working with simulator iPad 2 , it is working without any issue. Only with real device it is causing this issue.Please help.

**Comment by mykola-mokhnach** [comment] 2016-12-20 11:01
1.2.0 is the latest stable version, which is different from HEAD. Closing as duplicate of https://github.com/appium/appium/issues/7520

**Closed by mykola-mokhnach** 2016-12-20 11:01 UTC
Labels: NeedsTriage

**Comment by Kirubaharan235** [comment] 2016-12-20 11:04
Hi mykola,the issue is not about ideviceinstaller.

The issue is ,appovum doesn't start on my iPad after latest appovum 1.6.2 beta.


Please reopen this.
