### ISSUE TITLE
Facing issue on Android 8.0.0 with Appium 15.0 

### ISSUE THREAD

**Issue by Sourabh25** [appium/appium#13367] opened 2019-10-04 20:16 UTC
## The problem

Getting the  error Cannot call non W3C standard command while in W3C mode when I am trying to work on Chrome browser on Android

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macosMojave
* Node.js version (unless using Appium.app|exe): 12.6
* Npm or Yarn package manager: mpm
* Mobile platform/version under test: Android 8.0.0
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/Sourabh25/212e2fc1b9427030965053b3d9e3f385

## Code To Reproduce Issue [ Good To Have ]
String osName = System.getProperty("os.name").toLowerCase();
		String deviceName = frameworkContext.getParamValue(FrameworkConstants.APP_ANDROID_DEVICENAME);
		String platformVersion = frameworkContext.getParamValue(FrameworkConstants.APP_ANDROID_PLATFORM_VERSION);

		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("clearSystemFiles", true);
		capabilities.setCapability("platformName", platformName);
		capabilities.setCapability("deviceName", deviceName);
		capabilities.setCapability("platformVersion", platformVersion);
		capabilities.setCapability(CapabilityType.BROWSER_NAME, "Chrome");
		String broweserDir;
		if(osName.contains("mac")) {
			broweserDir = TestUtils.getRelativePath()+File.separator + "src/main/resources/BrowserSpecificDrivers/chromedriver";
		}else {
			broweserDir = TestUtils.getRelativePath()+File.separator + "src/main/resources/BrowserSpecificDrivers/chromedriver.exe";
		}
		
		capabilities.setCapability("chromedriverExecutable",broweserDir);
		
		driver = new AndroidDriver(
				new URL("http://" + frameworkContext.getParamValue(FrameworkConstants.APP_MOBILE_SERVER) + ":"
						+ frameworkContext.getParamValue(FrameworkConstants.APP_MOBILE_PORT) + "/wd/hub"),
				capabilities);
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

**Comment by mykola-mokhnach** [comment] 2019-10-04 20:39
Duplicate of https://github.com/appium/java-client/issues/1242

**Closed by mykola-mokhnach** 2019-10-04 20:39 UTC
