### ISSUE TITLE
Appium does not detect the right webview version 

### ISSUE THREAD

**Issue by megolee** [appium/appium#10868] opened 2018-06-13 08:55 UTC
## The problem

Android device with chrome 65 and Android System Webview 63 installed. But when try to switch the Webview, appium logs shows that Webview version: 'Chrome/57.0.2987.132' 

## Environment

Appium version : 1.8.0
Desktop OS/version used to run Appium: Mac OS 10.13.4
Node.js version (unless using Appium.app|exe): 10.0.0
Mobile platform/version under test: Android 8.0.0
Real device or emulator/simulator: Real Device

## Details

Above shows the problem. 

## Link to Appium logs

https://gist.github.com/megolee/890f489727702218c4621d6e4b64d167

**Comment by mykola-mokhnach** [comment] 2018-06-13 09:33
Duplicate of https://github.com/appium/appium/issues/10847

**Closed by mykola-mokhnach** 2018-06-13 09:33 UTC

**Comment by imurchie** [comment] 2018-06-13 14:34
Appium itself is finding the correct version (see https://gist.github.com/megolee/890f489727702218c4621d6e4b64d167#file-gistfile1-txt-L964-L965). Chromedriver is finding the version as `Chrome/57.0.2987.132` (see https://gist.github.com/megolee/890f489727702218c4621d6e4b64d167#file-gistfile1-txt-L1024). Chromedriver finds the version by checking the Chrome DevTools. You can see the process by turning on logging with the `showChromedriverLog` desired capability (set to true).
