### ISSUE TITLE
Error Domain=com.facebook.WebDriverAgent Code=1 "'"Enter Address" TextField' is not ready for a text input.

### ISSUE THREAD

**Issue by rajarlm007** [appium/appium#14768] opened 2020-09-30 08:24 UTC
## The problem

Not able to enter text value in XCUIElementTypeTextField.

Error Domain=com.facebook.WebDriverAgent Code=1 "'"Enter Address" TextField' is not ready for a text input. Neither the accessibility element itself nor its accessible descendants have the input focus" UserInfo={NSLocalizedDescription='"Enter Address" TextField' is not ready for a text input. Neither the accessibility element itself nor its accessible descendants have the input focus}

## Environment
* Appium version: v1.18
* Desktop OS/version used to run Appium: iOS 10.15.6
* Mobile platform/version under test: Native App
* Real device or emulator/simulator: simulator

## Details

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=mscorlib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OpenQA.Selenium.Appium.PageObjects.Interceptors.SearchingInterceptor.Intercept(IInvocation invocation)
   at OpenQA.Selenium.Appium.PageObjects.Interceptors.ElementInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IMobileElement`1Proxy.SendKeys(String text)
   at Honeywell.GLSS.SW.Automation.PageObjects.iOSPageObjects.CheckPointPage.AddBuildingNotes() in C:\repos\CLSSAutomation\glss-systemtestautomation\Honeywell.GLSS.SW.Automation\PageObjects\iOSPageObjects\CheckPointPage.cs:line 288
   at Honeywell.GLSS.SW.BDDTests.StepDefinitions.CLSSiOSMobileSteps.ThenBuildingNotesShouldContainCustomerSiteAndAddressOfBuilding() in C:\repos\CLSSAutomation\glss-systemtestautomation\Honeywell.GLSS.SW.BDDTests\StepDefinitions\CLSSiOSMobileSteps.cs:line 1044

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
InvalidElementStateException: Error Domain=com.facebook.WebDriverAgent Code=1 "'"Add a Title" TextField' is not ready for a text input. Neither the accessibility element itself nor its accessible descendants have the input focus" UserInfo={NSLocalizedDescription='"Add a Title" TextField' is not ready for a text input. Neither the accessibility element itself nor its accessible descendants have the input focus}

**Comment by mykola-mokhnach** [comment] 2020-09-30 08:27
Duplicate of https://github.com/appium/java-client/issues/1386

**Closed by mykola-mokhnach** 2020-09-30 08:27 UTC
