### ISSUE TITLE
perform() action chain - Getting exception 

### ISSUE THREAD

**Issue by cswarnan** [appium/appium#12161] opened 2019-02-14 09:34 UTC
## The problem

I was using the action chain, and now for some reason, it is not working and I am getting the error:

InvalidArgumentException: Message: invalid argument
from invalid argument: 'element' is missing

The action chain is used to perform a click on the element.

## Environment

* Appium version: 1.11.0
* Last Appium version that did not exhibit the issue (if applicable): Not sure
* Desktop OS/version used to run Appium: macOS 10.14
* Node.js version (unless using Appium.app|exe): 10.1.0
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: Android 8
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

My old code for action chain used to work to click on element/move element, but all sudden I don't what changed, (my application code is still same), it stopped working with following error
InvalidArgumentException: Message: invalid argument
from invalid argument: 'element' is missing
(Session info: chrome=72.0.3626.105)
  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.0 x86_64)

**Comment by mykola-mokhnach** [comment] 2019-02-14 09:49
Please attach the full server log

**Comment by cswarnan** [comment] 2019-02-14 10:25
[HTTP] <-- GET /wd/hub/session/4aa174a8-5267-46cc-b4ab-d1aaeac8f09a/element/0.288656498975032-41/location 200 24 ms - 172
[HTTP] 
[HTTP] --> POST /wd/hub/session/4aa174a8-5267-46cc-b4ab-d1aaeac8f09a/actions
[HTTP] {"sessionId":"4aa174a8-5267-46cc-b4ab-d1aaeac8f09a","actions":[{"parameters":{"pointerType":"mouse"},"type":"pointer","id":"mouse","actions":[{"duration":250,"x":0,"type":"pointerMove","y":0,"origin":{"element-6066-11e4-a52e-4f735466cecf":"0.288656498975032-53"}},{"duration":250,"x":227,"type":"pointerMove","y":-19,"origin":"pointer"},{"duration":0,"button":0,"type":"pointerDown"},{"duration":0,"button":0,"type":"pointerUp"},{"duration":250,"x":-178,"type":"pointerMove","y":-7,"origin":{"element-6066-11e4-a52e-4f735466cecf":"0.288656498975032-41"}}]},{"type":"key","id":"key","actions":[{"duration":0,"type":"pause"},{"duration":0,"type":"pause"},{"duration":0,"type":"pause"},{"duration":0,"type":"pause"},{"duration":0,"type":"pause"}]}]}
[W3C (4aa174a8)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/4aa174a8-5267-46cc-b4ab-d1aaeac8f09a/actions' to command name 'performActions'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/4aa174a8-5267-46cc-b4ab-d1aaeac8f09a/actions] to [POST http://127.0.0.1:8000/wd/hub/session/a91096629eabc16adb492f83b6dcf1cc/actions] with body: {"sessionId":"4aa174a8-5267-46cc-b4ab-d1aaeac8f09a","actions":[{"parameters":{"pointerType":"mouse"},"type":"pointer","id":"mouse","actions":[{"duration":250,"x":0,"type":"pointerMove","y":0,"origin":{"element-6066-11e4-a52e-4f735466cecf":"0.288656498975032-53"}},{"duration":250,"x":227,"type":"pointerMove","y":-19,"origin":"pointer"},{"duration":0,"button":0,"type":"pointerDown"},{"duration":0,"button":0,"type":"pointerUp"},{"duration":250,"x":-178,"type":"pointerMove","y":-7,"origin":{"element-6066-11e4-a52e-4f735466cecf":"0.288656498975032-41"}}]},{"type":"key","id":"key","actions":[{"duration":0,"type":"pause"},{"duration":0,"type":"pause"},{"duration":0,"type":"pause"},{"duration":0,"type":"pause"},{"duration":0,"type":"pause"}]}]}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"a91096629eabc16adb492f83b6dcf1cc","status":61,"value":{"message":"invalid argument\nfrom invalid argument: 'element' is missing\n  (Session info: chrome=72.0.3626.105)\n  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.0 x86_64)"}}
[WD Proxy] Got an unexpected response: {"sessionId":"a91096629eabc16adb492f83b6dcf1cc","status":61,"value":{"message":"invalid argument\nfrom invalid argument: 'element' is missing\n  (Session info: chrome=72.0.3626.105)\n  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.14.0 x86_...
[debug] [W3C (4aa174a8)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: The request to /wd/hub/session/4aa174a8-5267-46cc-b4ab-d1aaeac8f09a/actions has failed
[debug] [W3C (4aa174a8)]     at JWProxy.proxy (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:180:13)
[debug] [MJSONWP] Matched JSONWP error code 61 to InvalidArgumentError

**Comment by ibiautomation** [comment] 2019-02-14 10:36
I am also facing same issue with latest appium 1.11.0 version

**Comment by mykola-mokhnach** [comment] 2019-02-14 10:43
Thanks. I think I know why this is happening

**Comment by cswarnan** [comment] 2019-02-14 11:13
@mykola-mokhnach - sorry, but when we can expect this fix?

**Comment by dpgraham** [comment] 2019-02-14 22:47
The fix for this is published Appium 1.11.1-rc.0 (release candidate) 

(cc: @cswarnan)

**Closed** 2019-02-15 05:22 UTC
Labels: Bug, W3C

**Comment by cswarnan** [comment] 2019-02-15 05:25
@dpgraham - Thanks for the update. When do we expect that beta release?

**Comment by dpgraham** [comment] 2019-02-15 18:40
@cswarnan it's out now.... except install 1.11.1-rc.1 instead.

**Comment by cswarnan** [comment] 2019-04-03 07:30
@mykola-mokhnach / @dpgraham  - I updated my appium to 1.12.1 still getting issue with action chain 

here is the log:

[debug] [WD Proxy] Proxying [POST /actions] to [POST http://localhost:8100/session/D5CF5A81-F9B1-4C95-A32C-83983C4CBBA8/actions] with body: {"actions":[{"parameters":{"pointerType":"touch"},"type":"pointer","id":"mouse","actions":[{"duration":250,"x":0,"type":"pointerMove","y":0,"origin":{"ELEMENT":"5155","element-6066-11e4-a52e-4f735466cecf":"5155"}},{"duration":250,"x":170,"type":"pointerMove","y":-19,"origin":"pointer"},{"duration":0,"button":0,"type":"pointerDown"},{"duration":0,"button":0,"type":"pointerUp"},{"duration":250,"x":-114,"type":"pointerMove","y":-7,"origin":{"ELEMENT":"5147","element-6066-11e4-a52e-4f735466cecf":"5147"}}]},{"type":"key","id":"key","actions":[]}]}
[debug] [WD Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Unsupported origin type '{\n    ELEMENT = 5155;\n    \"element-6066-11e4-a52e-4f735466cecf\" = 5155;\n}' is set for '{\n    duration = 250;\n    origin =     {\n        ELEMENT = 5155;\n        \"element-6066-11e4-a52e-4f735466cecf\" = 5155;\n    };\n    type = pointerMove;\n    x = 0;\n    y = 0;\n}' action item. Supported origin types: (\n    pointer,\n    viewport\n) or an element instance\" UserInfo={NSLocalizedDescription=Unsupported origin type '{\n    ELEMENT = 5155;\n    \"element-6066-11e4-a52e-4f735466cecf\" = 5155;\n}' is set for '{\n    duration = 250;\n    origin =     {\n        ELEMENT = 5155;\n        \"element-6066-11e4-a52e-4f735466cecf\" = 5155;\n    };\n    type = pointerMove;\n    x = 0;\n    y = 0;\n}' action item. Supported origin types: (\n    pointer,\n    viewport\n) or an element instance}","sessionId":"D5CF5A81-F9B1-4C95-A32C-83983C4CBBA8","status":13}
[WD Proxy] Got an unexpected response: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Unsupported origin type '{\n    ELEMENT = 5155;\n    \"element-6066-11e4-a52e-4f735466cecf\" = 5155;\n}' is set for '{\n    duration = 250;\n    origin =     {\n        ELEMENT = 5155;\n        \"element-6066-11e4-a52e-4f735466cecf\" = 5...
[debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[debug] [W3C (e9389987)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Unsupported origin type '{
[debug] [W3C (e9389987)]     ELEMENT = 5155;
[debug] [W3C (e9389987)]     "element-6066-11e4-a52e-4f735466cecf" = 5155;
[debug] [W3C (e9389987)] }' is set for '{
[debug] [W3C (e9389987)]     duration = 250;
[debug] [W3C (e9389987)]     origin =     {
[debug] [W3C (e9389987)]         ELEMENT = 5155;
[debug] [W3C (e9389987)]         "element-6066-11e4-a52e-4f735466cecf" = 5155;
[debug] [W3C (e9389987)]     };
[debug] [W3C (e9389987)]     type = pointerMove;
[debug] [W3C (e9389987)]     x = 0;
[debug] [W3C (e9389987)]     y = 0;
[debug] [W3C (e9389987)] }' action item. Supported origin types: (
[debug] [W3C (e9389987)]     pointer,
[debug] [W3C (e9389987)]     viewport
[debug] [W3C (e9389987)] ) or an element instance" UserInfo={NSLocalizedDescription=Unsupported origin type '{
[debug] [W3C (e9389987)]     ELEMENT = 5155;
[debug] [W3C (e9389987)]     "element-6066-11e4-a52e-4f735466cecf" = 5155;
[debug] [W3C (e9389987)] }' is set for '{
[debug] [W3C (e9389987)]     duration = 250;
[debug] [W3C (e9389987)]     origin =     {
[debug] [W3C (e9389987)]         ELEMENT = 5155;
[debug] [W3C (e9389987)]         "element-6066-11e4-a52e-4f735466cecf" = 5155;
[debug] [W3C (e9389987)]     };
[debug] [W3C (e9389987)]     type = pointerMove;
[debug] [W3C (e9389987)]     x = 0;
[debug] [W3C (e9389987)]     y = 0;
[debug] [W3C (e9389987)] }' action item. Supported origin types: (
[debug] [W3C (e9389987)]     pointer,
[debug] [W3C (e9389987)]     viewport
[debug] [W3C (e9389987)] ) or an element instance}
[debug] [W3C (e9389987)]     at errorFromMJSONWPStatusCode (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:789:10)
[debug] [W3C (e9389987)]     at ProxyRequestError.errorFromMJSONWPStatusCode [as getActualError] (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:683:14)
[debug] [W3C (e9389987)]     at JWProxy.getActualError [as command] (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:234:19)


Can you please help?

**Comment by mykola-mokhnach** [comment] 2019-04-03 14:49
No, we cannot help there, since touch actions don't work for web view elements and this is by design
