### ISSUE TITLE
Flick doesn't work correctly starting from Appium 1.15.1

### ISSUE THREAD

**Issue by liviulupei** [appium/appium#13743] opened 2019-12-18 12:17 UTC
## The problem

The Flick method doesn't seem to work correctly starting from Appium 1.15.1.

If I give the Flick method the parameters to go -300 pixels on the Y coordinate, it should scroll 300 pixels down. 

But it actually scrolls all the way to the bottom of the page.

This is the piece of code:
driver.flick(138, 420, 0, -300)

It works as expected with Appium 1.15.0, scrolling down only 300px.

It does not work correctly with Appium 1.15.1, scrolling all the way to the bottom.

In the text logs from BrowserStack, that piece of codes translates into this:
actions[{"action":"press","options":{"y":420,"x":138}},{"action":"moveTo","options":{"y":" -300","x":"0"}},{"action":"release","options":{}}]

I ran the test on the Wikipedia Android app, you can download the app from here:
https://endtest-files.s3.us-west-2.amazonaws.com/HTTmxZAxHaVEr8fkznb5vZy6uMIJbu/WikipediaSample.apk

I ran the tests on the Google Pixel 3a XL real device from BrowserStack, it's available in their free trial.  

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.15.0 
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Google Pixel 3a XL
* Appium CLI or Appium.app|exe:

## Details

I can provide other details if necessary.

## Link to Appium logs

Logs for Appium 1.15.0 where it works as expected:
https://github.com/liviulupei/debug/blob/master/appium_logs_1150

Logs for Appium 1.15.1 it does not work correctly and it scrolls down too much:
https://github.com/liviulupei/debug/blob/master/appium_logs_1151

## Code To Reproduce Issue [ Good To Have ]

driver.flick(138, 420, 0, -300)

**Comment by mykola-mokhnach** [comment] 2019-12-18 13:01
Please provide appropriate server logs. The currently attached ones are impossible to read. 

Have you also tried to reproduce the issue locally?

**Comment by liviulupei** [comment] 2019-12-18 13:12
**Scenario where Flick does not work as expected:**
Appium 1.15.1 logs for Flick action:
https://gist.github.com/liviulupei/21d1c647e5370c45808e646737c800a6
Device logs for Flick action: 
https://gist.github.com/liviulupei/1ab9af5a4a471168fcbda1d3f4902794

**Scenario where Flick works as expected:**
Appium 1.15.0 logs for Flick action:
https://gist.github.com/liviulupei/7be4334c62e04eb6376b69e146137613
Device logs for Flick action: 
https://gist.github.com/liviulupei/096d8b13e81fcaa02f41a071ae195ca5

Is that better?

I did not try to reproduce it locally, because I'm using Endtest and BrowserStack, which are using Appium and real mobile devices. 

I also exported the code and that's where I got it from.

Just try to reproduce the issue on your side, you will see that it's happening.

I provided the APK file and the instructions.

**Comment by mykola-mokhnach** [comment] 2019-12-18 13:31
> I did not try to reproduce it locally, because I'm using Endtest and BrowserStack, which are using Appium and real mobile devices.

Have you tried to contact their customer support?

The version of Android driver has not been changed between Appium 1.15.0 and 1.15.1, which means they must behave exactly the same. Also, I cannot guarantee that BS does not have anything on top of what the "raw" Appium is doing.

**Comment by liviulupei** [comment] 2019-12-18 14:25
@mykola-mokhnach 

You have the APK file, the detailed steps, the logs, I described exactly what's happening.

I didn't just paste some generic error and added a title with "Broken. Please fix.".

I don't have an Appium Server installed locally and I don't have time to install one, I might have time in a few weeks, but I'm not sure.

BrowserStack just runs an Appium server and I checked the exact Appium code which is executed. 
There is nothing on top of that Appium.

Yes, I did contact their Customer Support. but I also opened this issue here.

I am not blocked by this issue, I can just keep using version 1.15.0 for as long as I want. 

I opened this issue to help you. I'm guessing you have Appium installed locally, it would take you 3 minutes to check and see that the issue that I reported is present. 

If you're just looking for reasons to close this issue, be my guest. 

By the way:
I looked in the changelog from Appium:
https://raw.githubusercontent.com/appium/appium/master/CHANGELOG.md

And here's what it says:
CHANGES IN VERSION 1.5.2 (from 1.5.1)
===================================
....
#### Android
- fix failure when `apk` file is too large
- re-implement setting geolocation so it does not use Telnet.
- add support for Chromium browser
**- fix issues with `flick`**

I couldn't find what exactly was that **flick** issue fixed in 1.5.2.

**Comment by mykola-mokhnach** [comment] 2019-12-18 14:34
> If you're just looking for reasons to close this issue, be my guest.

There is no point in closing issues without first trying to address them. It anyway seems weird to me, since UIA2 provides a separate [endpoint](https://github.com/appium/appium-uiautomator2-server/blob/752a8a8551b7e8cf7050182b826e234c0839a548/app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java#L130) for `flick` operation, although the client (I don't see which particular client is used though) sends the actions chain instead (which is very hard to debug btw)

**Comment by liviulupei** [comment] 2019-12-18 14:46
These are the input capabilities, I don't know if this information helps:
autoDismissAlerts = true
gpsEnabled = true
browserstack.networkLogs = true
build = Python Android
device = Google Pixel 3a XL
browserstack.video = false
autoAcceptAlerts = true
acceptSslCert = false
detected_language = selenium/3.141.0 (python windows)
browserstack.appiumLogs = true
appPackage = org.wikipedia.alpha
appActivity = org.wikipedia.main.MainActivity
bundleID = org.wikipedia.alpha
browserstack.deviceLogs = true
nativeWebScreenshot = true

**Comment by mykola-mokhnach** [comment] 2019-12-18 15:15
I did briefly check the current implementation and it is clearly visible the endpoint is implemented differently in different clients.

I don't really want to do any changes there to not break the existing stuff for users.
As a possible workaround I would recommend to build the actions chain manually using the TouchAction class or the new W3C actions API [implementation](https://appiumpro.com/editions/29)

Although, if anyone wants to perform fixes then we would be happy to review PRs

**Comment by KazuCocoa** [comment] 2019-12-18 15:17
Sorry, I'm confusing.

Your 1.15.1 log said as below. : https://gist.github.com/liviulupei/21d1c647e5370c45808e646737c800a6

> 2019-12-18 12:03:13:666 - [Appium] Creating new AndroidUiautomator2Driver (v0.5.2) session


But 1.15.0 was : https://gist.github.com/liviulupei/7be4334c62e04eb6376b69e146137613

> 2019-12-18 11:52:45:535 - [Appium] Appium v1.15.0 creating new AndroidUiautomator2Driver (v1.37.2) session


I believe the 1.15.1 is not Appium 1.15.1 which has been released next to 1.15.0.

**Comment by liviulupei** [comment] 2019-12-18 15:22
@KazuCocoa 
If it's not Appium 1.15.1, then what is it?
The AndroidUiautomator2Driver version does seem very old for that supposedly Appium 1.15.1.

**Comment by KazuCocoa** [comment] 2019-12-18 15:39
Appium 1.15.1 has appium-uiautomator2-driver 1.37.2 on my local.

The 0.5.2 seems in 2017's one. https://github.com/appium/appium-uiautomator2-driver/commits/master?after=a655d5a65420fa04f4a0ea34b1a07375c9b0b4a7+279
You should ask BS.

**Comment by liviulupei** [comment] 2019-12-18 15:40
@KazuCocoa 
Yes, it seems the default version of Appium for Android on BrowserStack is actually 1.6.5, not 1.15.1 as I thought. 
https://www.browserstack.com/app-automate/capabilities
My apologies for that.

**Comment by KazuCocoa** [comment] 2019-12-18 15:48
Okay, np 👌So, the difference is BS side.

Closed.

**Closed by KazuCocoa** 2019-12-18 15:48 UTC
Labels: UIAutomator2
