### ISSUE TITLE
Appium 1.6 : Type/SendKeys/setValue command fails to type or gets stuck while executing 200+ test cases.

### ISSUE THREAD

**Issue by SatishKumarKV** [appium/appium#8112] opened 2017-03-28 06:49 UTC
## The problem

Appium 1.6 : Type/SendKeys/setValue command fails to type or gets stuck while executing 200+ test cases.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3 and also tried with 1.6.4 beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator: Device
* Appium CLI or Appium.app|exe: CLI

## Details

1. Running 4 suites of 200 test cases each overnight.
2. 2 Suites are getting executed without any issues , But when 3rd suite execution starts..
I am facing issues around setValue which get stuck after executing 2 suites without any issues and suite executing doesn't proceed furthur

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/f58da62f-6ba8-4890-b5bd-ff1bf4478384/elements {"using":"name","value":"Enter Folder Name"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["name","Enter Folder Name","f58da62f-6ba8-4890-b5bd-ff1bf4478384"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8384/session/3EE7075D-F1D6-46F6-897E-46DF34EB83F4/elements] with body: {"using":"name","value":"Enter Folder Name"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"F5151109-7568-42F5-ACDD-0C0B721CFC0F","type":"XCUIElementTypeTextField","label":""}],"sessionId":"3EE7075D-F1D6-46F6-897E-46DF34EB83F4","status":0}
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"F5151109-7568-42F5-ACDD-0C0B721CFC0F","type":"XCUIElementTypeTextField","label":""}]
[HTTP] <-- POST /wd/hub/session/f58da62f-6ba8-4890-b5bd-ff1bf4478384/elements 200 958 ms - 169 
Size of found elements 1
[HTTP] --> GET /wd/hub/session/f58da62f-6ba8-4890-b5bd-ff1bf4478384/element/F5151109-7568-42F5-ACDD-0C0B721CFC0F/displayed {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/f58da62f-6ba8-4890-b5bd-ff1bf4478384/element/F5151109-7568-42F5-ACDD-0C0B721CFC0F/displayed] to [GET http://localhost:8384/session/3EE7075D-F1D6-46F6-897E-46DF34EB83F4/element/F5151109-7568-42F5-ACDD-0C0B721CFC0F/displayed] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"3EE7075D-F1D6-46F6-897E-46DF34EB83F4\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId 3EE7075D-F1D6-46F6-897E-46DF34EB83F4 with f58da62f-6ba8-4890-b5bd-ff1bf4478384
[HTTP] <-- GET /wd/hub/session/f58da62f-6ba8-4890-b5bd-ff1bf4478384/element/F5151109-7568-42F5-Size of found elements true
ACDD-0C0B721CFC0F/displayed 200 419 ms - 76 
[HTTP] --> POST /wd/hub/session/f58da62f-6ba8-4890-b5bd-ff1bf4478384/element/F5151109-7568-42F5-ACDD-0C0B721CFC0F/clear {"id":"F5151109-7568-42F5-ACDD-0C0B721CFC0F"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/f58da62f-6ba8-4890-b5bd-ff1bf4478384/element/F5151109-7568-42F5-ACDD-0C0B721CFC0F/clear] to [POST http://localhost:8384/session/3EE7075D-F1D6-46F6-897E-46DF34EB83F4/element/F5151109-7568-42F5-ACDD-0C0B721CFC0F/clear] with body: {"id":"F5151109-7568-42F5-ACDD-0C0B721CFC0F"}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"F5151109-7568-42F5-ACDD-0C0B721CFC0F","value":"","sessionId":"3EE7075D-F1D6-46F6-897E-46DF34EB83F4"}
[JSONWP Proxy] Replacing sessionId 3EE7075D-F1D6-46F6-897E-46DF34EB83F4 with f58da62f-6ba8-4890-b5bd-ff1bf4478384
[HTTP] <-- POST /wd/hub/session/f58da62f-6ba8-4890-b5bd-ff1bf4478384/element/F5151109-7568-42F5-ACDD-0C0B721CFC0F/clear 200 1345 ms - 118 
[HTTP] --> POST /wd/hub/session/f58da62f-6ba8-4890-b5bd-ff1bf4478384/element/F5151109-7568-42F5-ACDD-0C0B721CFC0F/value {"id":"F5151109-7568-42F5-ACDD-0C0B721CFC0F","value":["IBM Connections AutoFolder"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["IBM Connections AutoFolder"],"F5151109-7568-42F5-ACDD-0C0B721CFC0F","f58da62f-6ba8-4890-b5bd-ff1bf4478384"]
[debug] [XCUITest] Executing command 'setValue'
[debug] [JSONWP Proxy] Proxying [POST /element/F5151109-7568-42F5-ACDD-0C0B721CFC0F/value] to [POST http://localhost:8384/session/3EE7075D-F1D6-46F6-897E-46DF34EB83F4/element/F5151109-7568-42F5-ACDD-0C0B721CFC0F/value] with body: {"value":["I","B","M"," ","C","o","n","n","e","c","t","i","o","n","s"," ","A","u","t","o","F","o","l","d","e","r"],"simple":true}
[HTTP] <-- POST /wd/hub/session/f58da62f-6ba8-4890-b5bd-ff1bf4478384/element/F5151109-7568-42F5-ACDD-0C0B721CFC0F/value - - ms - - 
[HTTP] --> POST /wd/hub/session/f58da62f-6ba8-4890-b5bd-ff1bf4478384/element/F5151109-7568-42F5-ACDD-0C0B721CFC0F/value {"id":"F5151109-7568-42F5-ACDD-0C0B721CFC0F","value":["IBM Connections AutoFolder"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["IBM Connections AutoFolder"],"F5151109-7568-42F5-ACDD-0C0B721CFC0F","f58da62f-6ba8-4890-b5bd-ff1bf4478384"]
[debug] [XCUITest] Executing command 'setValue'
[HTTP] <-- POST /wd/hub/session/f58da62f-6ba8-4890-b5bd-ff1bf4478384/element/F5151109-7568-42F5-ACDD-0C0B721CFC0F/value - - ms - -

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by kenmcc** [comment] 2017-03-28 07:41
I've seen similar with a simple test case;
```
launch youtube
loop doing:
    tap the search icon
    select the search text field 
    enter the text of a video to search, terminated with a '\n'
    tap the first video in the list
    swipe it away after a while
    press the left arrow button to enable search again
```

after a while, sometimes short sometimes long, the text in the field would remain half-entered. e.g. if you were trying to type in 'November Rain' it might get as far as 'Novemb' and then stick essentially forever.

Seen on both an iPadPro 9.7" and an iPhone6, all running 10.2 or 10.2.1

**Comment by mykola-mokhnach** [comment] 2017-03-28 07:45
Duplicate of https://github.com/facebook/WebDriverAgent/issues/476
We cannot do anything from Appium side to fix this bug. Please report it to Apple.

**Closed by mykola-mokhnach** 2017-03-28 07:45 UTC
Labels: NeedsTriage

**Comment by SatishKumarKV** [comment] 2017-03-28 07:59
Bug filed with Apple : 31293498
