### ISSUE TITLE
bug: Unable to perform multiple consecutive taps in IOS system

### ISSUE THREAD

**Issue by zhouhyi** [appium/appium#19680] opened 2024-01-19 10:50 UTC
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My confusion:
I want to perform 5 quick consecutive clicks on a button in my iPhone app to fast forward 50s (n*10s) of the video I'm playing. However, I cannot achieve continuous rapid clicks using the following method, resulting in the inability to fast forward the video.
By the way, before I upgraded to appium2 & selenium4 & Java-client8, using this method could achieve the expected results.
Wondering what is the correct way to do multiple consecutive clicks in Appium Java? Or is this a current limitation of Appium?

Testing code:
```
    public static void multipleTabElementWithOffset(WebElement webElement, WebElement waitElement, int count, int x, int y) {
        Point point = webElement.getLocation();
        int xOffset = point.getX() + x;
        int yOffset = point.getY() + y;
        RPLogger.trace("multiple tapping on the screen: " + xOffset + " , " + yOffset);
        for (int i = 0; i < count; i++) {
            Map<String, Object> args = new HashMap<>();
            args.put("x", xOffset);
            args.put("y", yOffset);
            ((AppiumDriver)WebDriverUtils.getDriver()).executeScript("mobile: tap", args);
        }
    }
```
    
![image](https://github.com/appium/appium/assets/28880427/7a8c376b-3b01-475f-aa86-9ad3fe4368d5)

### Expected Behavior

Can be clicked multiple times in succession.

### Minimal Reproducible Example

```
 public static void multipleTabElementWithOffset(WebElement webElement, int count, int x, int y) {
        Point point = webElement.getLocation();
        int xOffset = point.getX() + x;
        int yOffset = point.getY() + y;
        for (int i = 0; i < count; i++) {
                Map<String, Object> args = new HashMap<>();
                args.put("x", xOffset);
                args.put("y", yOffset);
                ((AppiumDriver)WebDriverUtils.getDriver()).executeScript("mobile: tap", args);
            }
    }
```

### Environment

- Operating system:
- Appium server version (output of `appium --version`):2.2.2
- Appium driver(s) and their version(s): xcuitest@5.11.8, uiautomator2@2.34.2
- Node.js version (output of `node --version`):v20.8.0
- `npm` version (output of `npm --version`):10.1.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iPhone13 IOS 17.2.1
- Real device or emulator/simulator:Real device
- Selenium version: 4.9.1
- java-client version: 8.5.0

### Link to Appium Logs

https://gist.github.com/zhouhyi/d26ebf53a6d8215648b7574e7a2d25a3

**Comment by jensakejohansson** [comment] 2024-01-19 12:13
People in my team have seen this issue with "mobile: tap" (on IPhone) as well. The action as no effect. I don't have the logs in front of me now,  just wanted to confirm that this seems to be a problem.

**Comment by eglitise** [comment] 2024-01-19 12:54
One option is `mobile: tapWithNumberOfTaps`, although it also requires the element ID. If 2 taps are enough, there is `mobile: doubleTap` (no element ID required), in my experience it is relatively fast.

**Comment by mykola-mokhnach** [comment] 2024-01-19 17:52
I assume it is not interpreted as expected because there is always a latency between each server command. Try the above API as @eglitise suggested or build a W3C actions chain.

**Comment by emre89** [comment] 2024-01-19 18:07
> People in my team have seen this issue with "mobile: tap" (on IPhone) as well. The action as no effect. I don't have the logs in front of me now, just wanted to confirm that this seems to be a problem.

The logs are here :

`Calling AppiumDriver.getTimeouts() with args: ["fa674d35-1d25-4d43-9797-fd127fa993d4"]
[XCUITestDriver@f54e (fa674d35)] Executing command 'getTimeouts'
[XCUITestDriver@f54e (fa674d35)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /session/fa674d35-1d25-4d43-9797-fd127fa993d4/timeouts 304 1 ms - -
[HTTP] 
[HTTP] Request idempotency key: 43315b7b-98bb-4a2c-9882-dea77c95c5c8
[HTTP] --> POST /session/074de159-4c43-4b6b-b0d5-3a0a4364831a/execute/sync
[HTTP] {"script":"mobile: tap","args":[{"element":"E5000000-0000-0000-CE1C-000000000000","x":134,"y":373}]}
[XCUITestDriver@2672 (074de159)] Calling AppiumDriver.execute() with args: ["mobile: tap",[{"element":"E5000000-0000-0000-CE1C-000000000000","x":134,"y":373}],"074de159-4c43-4b6b-b0d5-3a0a4364831a"]
[XCUITestDriver@2672 (074de159)] Executing command 'execute'
[XCUITestDriver@2672 (074de159)] Proxying to WDA with an unknown route: POST /wda/tap/E5000000-0000-0000-CE1C-000000000000
[XCUITestDriver@2672 (074de159)] Setting custom timeout to 150000 ms for 'Unknown' command
[XCUITestDriver@2672 (074de159)] Proxying [POST /wda/tap/E5000000-0000-0000-CE1C-000000000000] to [POST http://127.0.0.1:8100/session/7DF3AF65-A305-4274-8D64-142F719866B0/wda/tap/E5000000-0000-0000-CE1C-000000000000] with body: {"x":134,"y":373}
[XCUITestDriver@2672 (074de159)] Got response with status 200: {"value":null,"sessionId":"7DF3AF65-A305-4274-8D64-142F719866B0"}
[XCUITestDriver@2672 (074de159)] Responding to client with driver.execute() result: null
[HTTP] <-- POST /session/074de159-4c43-4b6b-b0d5-3a0a4364831a/execute/sync 200 518 ms - 14
[HTTP] 
[HTTP] --> GET /session/fa674d35-1d25-4d43-9797-fd127fa993d4/timeouts
[HTTP] {}
[XCUITestDriver@f54e (fa674d35)] Calling AppiumDriver.getTimeouts() with args: ["fa674d35-1d25-4d43-9797-fd127fa993d4"]
[XCUITestDriver@f54e (fa674d35)] Executing command 'getTimeouts'
[XCUITestDriver@f54e (fa674d35)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /session/fa674d35-1d25-4d43-9797-fd127fa993d4/timeouts 304 2 ms - -
[HTTP] 
[HTTP] --> GET /session/fa674d35-1d25-4d43-9797-fd127fa993d4/timeouts
[HTTP] {}
[XCUITestDriver@f54e (fa674d35)] Calling AppiumDriver.getTimeouts() with args: ["fa674d35-1d25-4d43-9797-fd127fa993d4"]
[XCUITestDriver@f54e (fa674d35)] Executing command `'getTimeouts'``

**Comment by mykola-mokhnach** [comment] 2024-01-24 05:50
@burtonemily Your issue is unrelated and is caused by the invalid input.

Closed as not an issue

**Closed by mykola-mokhnach** 2024-01-24 05:50 UTC
Labels: Needs Info
