### ISSUE TITLE
'Could not proxy' and one more error, while trying to perform mouse actions on windows

### ISSUE THREAD

**Issue by winiarski21** [appium/appium#15166] opened 2021-03-05 19:00 UTC
I'm writting automated tests on WPF application, ane evertyhing worked fine, untill I tried to perform some mouse actions (e.g. MoveToElement). 

Fore example when I try to execute:
```
Actions.MoveToElement(popUp, 0, 0);
otherActions.Perform();
```
every time I receive an exception:

> OpenQA.Selenium.WebDriverException: 'An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Request failed with status code 501'
> 
> OpenQA.Selenium.WebDriverException
>   HResult=0x80131500
>   Message=An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Request failed with status code 501
>   Source=WebDriver
>   StackTrace:
>    at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
>    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
>    at OpenQA.Selenium.Remote.RemoteWebElement.get_Size()
>    at OpenQA.Selenium.Appium.AppiumWebElement.get_Size()
>    at OpenQA.Selenium.Interactions.Actions.MoveToElement(IWebElement toElement, Int32 offsetX, Int32 offsetY, MoveToElementOffsetOrigin offsetOrigin)
>    at OpenQA.Selenium.Interactions.Actions.MoveToElement(IWebElement toElement, Int32 offsetX, Int32 offsetY)
>    at AppiumProofOfConcept.UnitTest1.PopUpCheck() in C:\Users\winiarsk-1\source\repos\AppiumProofOfConcept\AppiumProofOfConcept\UnitTest1.cs:line 112

And one more thing. When using this function

`Actions.MoveByOffset(20,20);`

I get 

> OpenQA.Selenium.WebDriverException: 'Currently only pen and touch pointer input source types are supported'

Correct me if I'm wrong, but this function should work on WPF app with 'normal' mouse pointer.

I tried to find the solution in other topics, but there wasn't exact same problem.

**Comment by mykola-mokhnach** [comment] 2021-03-05 19:03
Duplicate of https://github.com/appium/python-client/issues/592

**Closed by mykola-mokhnach** 2021-03-05 19:03 UTC

**Comment by winiarski21** [comment] 2021-03-08 14:51
@mykola-mokhnach I have read linkes issue, but Is it possible to add this capability in C# 
`"forceMjsonwp": True`
?

**Comment by mykola-mokhnach** [comment] 2021-03-08 14:53
I don't know. Try to ask at Appium forum
