### ISSUE TITLE
Device ID is not specified in is_app_installed. Fails for more than 1 devices connected.

### ISSUE THREAD

**Issue by anazir-aa** [appium/appium#4731] opened 2015-03-18 14:19 UTC
Hi, 
Appium version = 1.3.5
Appium python client
Platform = Android API level 19
Device = Samsung Galaxy S4
Host OS = OS X 10.10.2
Server logs included below

Looking at the appium logs for is_app_installed, the following command fails when more than one devices is connected, because this command doesn't specify device ID. 

<b>adb shell "pm list packages com.myapp.stg"</b>

Running on command line the same command:
<b>$ adb shell "pm list packages com.myapp.stg"
error: more than one device and emulator</b>

<b>Server Logs for is_app_installed call:</b>

info: [debug] Getting install status for com.myapp.stg
info: [debug] Getting device API level
info: [debug] executing cmd: /Users/qa/Library/Android/sdk/platform-tools/adb shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level \* daemon not running. starting it now on port 5037 *

daemon started successfully \* 19 info: [debug] executing cmd: /Users/qa/Library/Android/sdk/platform-tools/<b>adb shell "pm list packages com.myapp.stg"</b> info: [debug] App is not installed info: [debug] Responding to client with success: {"status":0,"value":false,"sessionId":"14c30364-7a17-47b5-868a-8341fb66b25d"} info: <-- POST /wd/hub/session/14c30364-7a17-47b5-868a-8341fb66b25d/appium/device/app_installed 200 4061.856 ms - 77 {"status":0,"value":false,"sessionId":"14c30364-7a17-47b5-868a-8341fb66b25d"} info: --> POST /wd/hub/session/14c30364-7a17-47b5-868a-8341fb66b25d/appium/device/app_installed {"sessionId":"14c30364-7a17-47b5-868a-8341fb66b25d","bundleId":"com.myapp.stg"} info: [debug] Getting install status for com.myapp.stg info: [debug] Getting device API level info: [debug] executing cmd: /Users/qa/Library/Android/sdk/platform-tools/adb shell "getprop ro.build.version.sdk" info: [debug] Device is at API Level 19 info: [debug] executing cmd: /Users/qa/Library/Android/sdk/platform-tools/adb shell "pm list packages -3 com.myapp.stg"

**Comment by moizjv** [comment] 2015-05-05 23:00
Duplicate of https://github.com/appium/appium/issues/4608

**Comment by moizjv** [comment] 2015-05-05 23:01
@anazir-aa can you paste complete appium logs?

**Comment by sebv** [comment] 2015-06-03 14:38
Moved to bug.

**Closed** 2017-07-18 16:26 UTC
Labels: Android, Bug
