### ISSUE TITLE
Simulator fails to launch

### ISSUE THREAD

**Issue by menyp** [appium/appium#9633] opened 2017-11-13 19:54 UTC
## The problem
I am trying to run iOS app on a simulator.
I have added the simulator udid & the device name to the capabilities however after the app & the wda were installed the app fails to launch.
If I attempt to launch the app manually (outside the code after it is installed) then it fails to launch as well.
Do notice that on the regular device it works fine meaning the app is installed & launched.

## Environment

* Appium version 1.7.1
* macOS sierra 10.12.6
* Node.js version 2.1.0
* Mobile platform/version under test:
* simulator:
* Appium CLI 

## Link to Appium logs

Log:
Last login: Thu Nov 9 23:15:57 on ttys000
Menys-MacBook-Pro:~ menypeled$ appium &
[1] 27279
Menys-MacBook-Pro:~ menypeled$ [Appium] Welcome to Appium v1.7.2-beta
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
Menys-MacBook-Pro:~ menypeled$ [HTTP] --> POST /wd/hub/session {“desiredCapabilities”:{“app”:"/Users/menypeled/Documents/workspace/iOS_Appium/SkyGiraffe_5.12.3.app",“newCommandTimeout”:60,“platformVersion”:“11.0.1”,“xcodeOrgId”:“7Y5J2RJXYV”,“automationName”:“XCUITest”,“useNewWDA”:“false”,“udid”:“F11C4DF5-BB1F-4584-BD47-3A639529CBB6”,“platformName”:“iOS”,“deviceName”:“iPhone 8\t “,“updatedWDABundleId”:“beta.SkyGiraffe.SkyGiraffe”,“xcodeSigningId”:“iPhone Developer”}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{“app”:”/Users/menypeled/Documents/workspace/iOS_Appium/SkyGiraffe_5.12.3.app”,“newCommandTimeout”:60,“platformVersion”:“11.0.1”,“xcodeOrgId”:“7Y5J2RJXYV”,“automationName”:“XCUITest”,“useNewWDA”:“false”,“udid”:“F11C4DF5-BB1F-4584-BD47-3A639529CBB6”,“platformName”:“iOS”,“deviceName”:"iPhone 8\t ",“updatedWDABundleId”:“beta.SkyGiraffe.SkyGiraffe”,“xcodeSigningId”:“iPhone Developer”},null,null]
[debug] [BaseDriver] Event ‘newSessionRequested’ logged at 1510262414967 (23:20:14 GMT+0200 (IST))
[Appium] Creating new XCUITestDriver (v2.54.2) session
[Appium] Capabilities:
[Appium] app: ‘/Users/menypeled/Documents/workspace/iOS_Appium/SkyGiraffe_5.12.3.app’
[Appium] newCommandTimeout: 60
[Appium] platformVersion: ‘11.0.1’
[Appium] xcodeOrgId: ‘7Y5J2RJXYV’
[Appium] automationName: ‘XCUITest’
[Appium] useNewWDA: ‘false’
[Appium] udid: ‘F11C4DF5-BB1F-4584-BD47-3A639529CBB6’
[Appium] platformName: ‘iOS’
[Appium] deviceName: 'iPhone 8\t '
[Appium] updatedWDABundleId: ‘beta.SkyGiraffe.SkyGiraffe’
[Appium] xcodeSigningId: ‘iPhone Developer’
[BaseDriver] Capability ‘useNewWDA’ changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Session created with session id: 114197fa-376c-4df4-8661-639159e4440d
[debug] [XCUITest] Xcode version set to ‘9.0.1’ (tools v9.0.1.0.1.1506734476)
[debug] [XCUITest] iOS SDK Version set to ‘11.0’
[debug] [BaseDriver] Event ‘xcodeDetailsRetrieved’ logged at 1510262415184 (23:20:15 GMT+0200 (IST))
[debug] [XCUITest] Changing deviceName from 'iPhone 8	’ to ‘iPhone2017-A’
[iOSSim] Constructing iOS simulator for Xcode version 9.0.1 with udid ‘F11C4DF5-BB1F-4584-BD47-3A639529CBB6’
[XCUITest] Determining device to run tests on: udid: ‘F11C4DF5-BB1F-4584-BD47-3A639529CBB6’, real device: false
[BaseDriver] Using local app ‘/Users/menypeled/Documents/workspace/iOS_Appium/SkyGiraffe_5.12.3.app’
[debug] [BaseDriver] Event ‘appConfigured’ logged at 1510262415627 (23:20:15 GMT+0200 (IST))
[debug] [XCUITest] Checking whether app ‘/Users/menypeled/Documents/workspace/iOS_Appium/SkyGiraffe_5.12.3.app’ is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app ‘/Users/menypeled/Documents/workspace/iOS_Appium/SkyGiraffe_5.12.3.app’: ‘beta.SkyGiraffe.SkyGiraffe’
[debug] [BaseDriver] Event ‘resetStarted’ logged at 1510262415639 (23:20:15 GMT+0200 (IST))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[debug] [BaseDriver] Event ‘resetComplete’ logged at 1510262415760 (23:20:15 GMT+0200 (IST))
[debug] [iOSLog] Starting iOS 11.0 simulator log capture
[debug] [iOSLog] System log path: /Users/menypeled/Library/Logs/CoreSimulator/F11C4DF5-BB1F-4584-BD47-3A639529CBB6/system.log
[debug] [BaseDriver] Event ‘logCaptureStarted’ logged at 1510262415943 (23:20:15 GMT+0200 (IST))
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[debug] [iOSSim] Setting common Simulator preferences to {“ConnectHardwareKeyboard”:false}
[debug] [iOSSim] Updated shared Simulator preferences at ‘/Users/menypeled/Library/Preferences/com.apple.iphonesimulator.plist’ with {“ConnectHardwareKeyboard”:false}
[debug] [iOSSim] The count of running Simulator UI client instances is 0
[iOSSim] Booting Simulator with UDID F11C4DF5-BB1F-4584-BD47-3A639529CBB6…
[iOSSim] Starting Simulator UI with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID F11C4DF5-BB1F-4584-BD47-3A639529CBB6 -ConnectHardwareKeyboard 0
[debug] [iOSSim] The count of running Simulator UI client instances is 1
[iOSSim] Simulator with UDID F11C4DF5-BB1F-4584-BD47-3A639529CBB6 booted in 24 seconds
[debug] [BaseDriver] Event ‘simStarted’ logged at 1510262440373 (23:20:40 GMT+0200 (IST))
[debug] [XCUITest] Reset requested. Removing app with id ‘beta.SkyGiraffe.SkyGiraffe’ from the device
[debug] [XCUITest] Installing ‘/Users/menypeled/Documents/workspace/iOS_Appium/SkyGiraffe_5.12.3.app’ on Simulator with UUID ‘F11C4DF5-BB1F-4584-BD47-3A639529CBB6’…
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event ‘appInstalled’ logged at 1510262460510 (23:21:00 GMT+0200 (IST))
[XCUITest] Using WDA path: ‘/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent’
[XCUITest] Using WDA agent: ‘/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj’
[debug] [XCUITest] Capability ‘useNewWDA’ set to false, so trying to reuse currently running WDA instance at ‘http://localhost:8100/’
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at ‘http://localhost:8100/’. Rebuilding…
[debug] [BaseDriver] Event ‘wdaStartAttempted’ logged at 1510262460920 (23:21:00 GMT+0200 (IST))
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: ‘/usr/local/bin/carthage’
[debug] [XCUITest] Killing running processes ‘xcodebuild.*F11C4DF5-BB1F-4584-BD47-3A639529CBB6, iproxy 8100, F11C4DF5-BB1F-4584-BD47-3A639529CBB6.*XCTRunner’ for the device F11C4DF5-BB1F-4584-BD47-3A639529CBB6…
[debug] [XCUITest] ‘pgrep -nif xcodebuild.*F11C4DF5-BB1F-4584-BD47-3A639529CBB6’ didn’t detect any matching processes. Return code: 1
[debug] [XCUITest] ‘pgrep -nif iproxy 8100’ didn’t detect any matching processes. Return code: 1
[debug] [XCUITest] ‘pgrep -nif F11C4DF5-BB1F-4584-BD47-3A639529CBB6.*XCTRunner’ didn’t detect any matching processes. Return code: 1
[debug] [XCUITest] Using Xcode 9.0.1, so fixing WDA codebase
[debug] [XCUITest] Beginning test with command ‘xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=F11C4DF5-BB1F-4584-BD47-3A639529CBB6 IPHONEOS_DEPLOYMENT_TARGET=11.0’ in directory ‘/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent’
[debug] [XCUITest] Output from xcodebuild will not be logged. To see xcode logging, use ‘showXcodeLog’ desired capability
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/mr/lbh2rfw568g5v74x7g7vgx440000gn/T/com.apple.dt.XCTest/IDETestRunSession-0933A387-5D41-42A9-B935-C19E99CD36CC/WebDriverAgentRunner-134CD079-C450-44DA-AC48-402D134CAE94/Session-WebDriverAgentRunner-2017-11-09_232112-DPyMfU.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: “{\n “value” : {\n “state” : “success”,\n “os” : {\n “name” : “iOS”,\n “version” : “11.0.1”\n },\n “ios” : {\n “simulatorVersion” : “11.0.1”,\n “ip” : “192.168.1.100”\n },\n “build” : {\n “time” : “Nov 9 2017 22:47:22”\n }\n },\n “sessionId” : “8AC5DB0F-470C-4051-8289-BF1B4F56F024”,\n “status” : 0\n}”
[debug] [XCUITest] WebDriverAgent running on ip ‘192.168.1.100’
[debug] [XCUITest] WebDriverAgent successfully started after 19311ms
[debug] [BaseDriver] Event ‘wdaSessionAttempted’ logged at 1510262480371 (23:21:20 GMT+0200 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {“desiredCapabilities”:{“bundleId”:“beta.SkyGiraffe.SkyGiraffe”,“arguments”:[],“environment”:{},“shouldWaitForQuiescence”:true,“shouldUseTestManagerForVisibilityDetection”:false,“maxTypingFrequency”:60,“shouldUseSingletonTestManager”:true}}
[debug] [JSONWP Proxy] Got response with status 200: {“value”:“Failed to launch beta.SkyGiraffe.SkyGiraffe application”,“sessionId”:“8AC5DB0F-470C-4051-8289-BF1B4F56F024”,“status”:13}
[debug] [XCUITest] Failed to create WDA session. Retrying…
[debug] [BaseDriver] Event ‘wdaSessionAttempted’ logged at 1510262663687 (23:24:23 GMT+0200 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {“desiredCapabilities”:{“bundleId”:“beta.SkyGiraffe.SkyGiraffe”,“arguments”:[],“environment”:{},“shouldWaitForQuiescence”:true,“shouldUseTestManagerForVisibilityDetection”:false,“maxTypingFrequency”:60,“shouldUseSingletonTestManager”:true}}
open

**Comment by mykola-mokhnach** [comment] 2017-11-13 20:33
This is the problem of the application itself. Closed as duplicate of https://github.com/appium/appium/issues/9627

**Closed by mykola-mokhnach** 2017-11-13 20:33 UTC

**Comment by menyp** [comment] 2017-11-13 20:46
Can you be kind & point how to overcome this one? or what should our dev do
in order to build the .app successfully?

**Comment by jdsghuman** [comment] 2017-11-14 00:47
I was having a similar issue when running the scripts with Appium server.
No issues when I switched to using the GUI 1.7.1. Using that as a work
around for my issue for now.
