### ISSUE TITLE
Message: Locator Strategy 'css selector' is not supported for this session for find_element_by_name()

### ISSUE THREAD

**Issue by Jaspreet1354** [appium/appium#12439] opened 2019-04-04 13:55 UTC
## The problem
I am getting Message: Locator Strategy 'css selector' is not supported for this session for find_element_by_name() in Xcode 10.1, and the same things used to work before. I used all the necessary appium versions for this situation but no luck making it work.

## Environment

* npm uninstall -g appium && npm install -g appium@1.8.2beta
npm uninstall -g appium && npm install -g appium@beta
* IOS 12.1
* Desktop OS/version used to run Appium:
* NODE version:- v11.1.0
* Npm version: 6.9.0
* Mobile platform/version under test: IOS
* emulator/simulator:
* Python language

## Details
All my tests used to work before I upgraded my Xcode and appium version.
Now either I get CSS selector error or Implicit wait error.

## Link to Appium logs
gist:75561921b25cfac762eab427245ae0ac

## **Code To Reproduce Issue**

import os
from time import sleep
import unittest
import string
import sys
import pytest
import time
import HtmlTestRunner
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from appium import webdriver
from selenium import webdriver
from appium.webdriver.common.touch_action import TouchAction
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
from argparse import Action
from selenium.webdriver.common.touch_actions import TouchActions
from lib2to3.tests.support import driver
from appium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

# Returns abs path relative to this file and not cwd
from selenium.webdriver.support.wait import WebDriverWait

PATH = lambda p: os.path.abspath(os.path.join(os.path.dirname(__file__), p))

class D2DCellular1(unittest.TestCase):
    def setUp(self):
        desired_caps = {}
        desired_caps['platformName'] = 'iOS'
        desired_caps['platformVersion'] = '12.1'
        desired_caps['automationName'] = 'xcuitest'
        desired_caps['deviceName'] = 'iPhone Simulator'
        desired_caps['app'] = PATH(
            '/Users/directedelectronics/Library/Developer/Xcode/DerivedData/Viper-dwrfhhtvlbopywahjhbhvaaeqtvx/Build/Products/Viper-iphonesimulator/Viper.app')
        desired_caps['autoGrantPermissions'] = True
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

    def tearDown(self):
        self.driver.quit()

    def test_find_elements(self):
        self.driver.implicitly_wait(30)

        # Application_Loading_Login_button(1st time)
        self.driver.find_element_by_xpath('//XCUIElementTypeButton[@name="LOGIN"]').click()

        # Enter U_name
        self.driver.find_element_by_xpath('//XCUIElementTypeApplication[@name="SmartStart"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeTextField').send_keys('Testbench@directed.com')

        # Enter P_wrd
        self.driver.find_element_by_xpath('//XCUIElementTypeApplication[@name="SmartStart"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeSecureTextField').send_keys('Test123!')

        # Click_Login/GO
        self.driver.find_element_by_xpath('//XCUIElementTypeButton[@name="Go"]').click()
        sleep(15)

        # Click_WelCome_Screen(LET'S GET STARTED)
        self.driver.find_element_by_name("LET'S GET STARTED").click()
        sleep(4)

        # Click on OK Button
        self.driver.find_element_by_xpath("//XCUIElementTypeButton[@name='OK']").click()
        sleep(5)

        # Code to handle Location POP-Up
        try:
            self.driver.execute_script("mobile:alert", {"action": "accept"})
        except:
            print('ok')

        # Choose DashBoard(Classic)
        self.driver.find_element_by_xpath("//XCUIElementTypeStaticText[@name ='Classic']").click()

        # Click_Continue(SELECT)
        self.driver.find_element_by_xpath("//XCUIElementTypeButton[@name='CONTINUE']").click()

        # Code to handle Location POP-Up
        try:
            self.driver.execute_script("mobile:alert", {"action": "accept"})
        except:
            print('ok')

        # Click on the IMAGE
        self.driver.execute_script("mobile:swipe", {"direction": "left"})
        sleep(4)

        sleep(10)

        # Click on Lock Button
        self.driver.find_element_by_xpath('//XCUIElementTypeApplication[@name="SmartStart"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeButton[1]').click()
        sleep(10)

        # Verify the status on the Dashboard
        temp = ''
        thislist = self.driver.find_elements_by_class_name('XCUIElementTypeStaticText')
        for x in thislist:
            temp = str(x.get_attribute('name')) + temp
        if "Locked at" in temp:
            print("Locked at is present on the Dashboard")
        else:
            print("Locked at is not present on the Dashboard")
            # Just to fail the TC
            self.driver.find_element_by_id('dfdd')

        # Check the Status in the Vehicle Status page
        self.driver.find_element_by_xpath("//XCUIElementTypeNavigationBar/XCUIElementTypeStaticText/XCUIElementTypeButton").click()

        # Click on the Refresh Button
        self.driver.find_element_by_xpath("//XCUIElementTypeButton[@name='reload']").click()
        sleep(7)

        # Find the Status of doors locked and unlocked(It should be locked)
        tempy = ''
        thislist = self.driver.find_elements_by_class_name('XCUIElementTypeStaticText')
        for y in thislist:
            tempy = str(y.get_attribute('name')) + tempy
        if "DOORS (LOCKED/UNLOCKED) LOCKED" in tempy:
            print("Doors are closed in the vehicle status page")
        else:
            print("Doors locked status is wrong in vehicle status page")
            # Just to fail the Test case
            self.driver.find_element_by_id('fdfd')

        # GO back to the Dashboard by clicking cross button
        self.driver.find_element_by_xpath("//XCUIElementTypeButton[@name='bt close gray']").click()
        sleep(4)

        # UnLock Arms(door)
        self.driver.find_element_by_xpath("//XCUIElementTypeApplication[@name='SmartStart']/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeButton[2]").click()
        sleep(6)

        # Verify the status on the Dashboard
        tempz = ''
        thislist = self.driver.find_elements_by_class_name('XCUIElementTypeStaticText')
        for z in thislist:
            tempz = str(z.get_attribute('name')) + tempz
        if "Unlocked at" in tempz:
            print("Unlocked at is present on the Dashboard")
        else:
            print("Unlocked at is not present on the Dashboard")
            # Just to fail the TC
            self.driver.find_element_by_id('dfdd')

        # Check the Status in the Vehicle Status page
        self.driver.find_element_by_xpath("//XCUIElementTypeNavigationBar/XCUIElementTypeStaticText/XCUIElementTypeButton").click()

        # Click on the Refresh Button
        self.driver.find_element_by_xpath("//XCUIElementTypeButton[@name='reload']").click()
        sleep(7)

        # Verify the status of DOORs(LOCKED/UNLOCKED)
        tempc = ''
        thislist = self.driver.find_elements_by_class_name('XCUIElementTypeStaticText')
        for c in thislist:
            tempc = str(c.get_attribute('name')) + tempc
        if "DOORS (LOCKED/UNLOCKED) UNLOCKED" in tempc:
            print("Doors are Unlocked in the vehicle status page")
        else:
            print("Doors Unlocked status is wrong in vehicle status page")
            # Just to fail the Test case
            self.driver.find_element_by_id('fdfd')

        # Come to the Dashboard again
        self.driver.find_element_by_xpath("//XCUIElementTypeButton[@name='bt close gray']").click()

        # Click on the panic button
        self.driver.find_element_by_xpath("//XCUIElementTypeApplication[@name='SmartStart']/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeButton[4]").click()
        sleep(7)

        # Verify the status on the Dashboard for PANIC
        tempp = ''
        thislist = self.driver.find_elements_by_class_name('XCUIElementTypeStaticText')
        for p in thislist:
            tempp = str(p.get_attribute('name')) + tempp
        if "Panic received at" in tempp:
            print("Panic received at is present on the Dashboard")
        else:
            print("Panic received at is not present on the Dashboard")
            # Just to fail the TC
            self.driver.find_element_by_id('dfdd')

        # Check the Status in the Vehicle Status page
        self.driver.find_element_by_xpath("//XCUIElementTypeNavigationBar/XCUIElementTypeStaticText/XCUIElementTypeButton").click()

        # Click on the Refresh Button
        self.driver.find_element_by_xpath("//XCUIElementTypeButton[@name='reload']").click()
        sleep(10)

        # Scroll Down

        self.driver.execute_script("mobile:scroll", {"direction": "down"})
        sleep(3)

        # Verify the status on the Vehicle settings page for the PANIC after 10 seconds
        temppanic = ''
        thislist = self.driver.find_elements_by_class_name('XCUIElementTypeStaticText')
        for panic in thislist:
            temppanic = str(panic.get_attribute('name')) + temppanic
        if "PANIC YES" in temppanic:
            print("PANIC is YES even after 10 + seconds")
        else:
            print("Wrong Panic status after 10 + Seconds")
            # Just to fail the Test case
            self.driver.find_element_by_id('fdfd')

        # Click on the Refresh Button
        self.driver.find_element_by_xpath("//XCUIElementTypeButton[@name='reload']").click()
        sleep(20)

        # Verify the status on the Vehicle settings page for the PANIC after 30 + seconds
        temppanic = ''
        thislist = self.driver.find_elements_by_class_name('XCUIElementTypeStaticText')
        for panic in thislist:
            temppanic = str(panic.get_attribute('name')) + temppanic
        if "PANIC YES" in temppanic:
            print("PANIC is ON even after 30 + seconds")
        else:
            print("Wrong Panic status after 30 + Seconds")
            # Just to fail the Test case
            self.driver.find_element_by_id('fdfd')

        # Come to the Dashboard again
        self.driver.find_element_by_xpath("//XCUIElementTypeButton[@name='bt close gray']").click()

        # Click on the unlock button
        # UnLock Arms(door)
        self.driver.find_element_by_xpath("//XCUIElementTypeApplication[@name='SmartStart']/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeButton[2]").click()
        sleep(7)

        # Check the Status in the Vehicle Status page
        self.driver.find_element_by_xpath("//XCUIElementTypeNavigationBar/XCUIElementTypeStaticText/XCUIElementTypeButton").click()

        # Click on the Refresh Button
        self.driver.find_element_by_xpath("//XCUIElementTypeButton[@name='reload']").click()
        sleep(7)

        # Scroll Down

        self.driver.execute_script("mobile:scroll", {"direction": "down"})
        sleep(3)

        # Verify the status on the Vehicle settings page for the PANIC after clicking unlock button
        temppanic = ''
        thislist = self.driver.find_elements_by_class_name('XCUIElementTypeStaticText')
        for panic in thislist:
            temppanic = str(panic.get_attribute('name')) + temppanic
        if "PANIC NO" in temppanic:
            print("PANIC is NO after unlocking the button")
        else:
            print("Wrong panic status in the Dashboard")
            # Just to fail the Test case
            self.driver.find_element_by_id('fdfd')

        # Switch to the dashboard
        self.driver.find_element_by_xpath("//XCUIElementTypeButton[@name='bt close gray']").click()

        # Click on the Trunk Button
        self.driver.find_element_by_xpath("//XCUIElementTypeApplication[@name='SmartStart']/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeButton[5]").click()

        # Click on No Button
        self.driver.find_element_by_xpath("//XCUIElementTypeButton[@name='No']").click()

        # Click on the Trunk Button
        self.driver.find_element_by_xpath("//XCUIElementTypeApplication[@name='SmartStart']/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeButton[5]").click()

        # Click on OK Button
        # Open Trunk(OK)
        self.driver.find_element_by_xpath("//XCUIElementTypeButton[@name='Yes']").click()
        sleep(7)

        # Verify the status on the Dashboard for the TRUNK
        tempTrunk = ''
        thislist = self.driver.find_elements_by_class_name('XCUIElementTypeStaticText')
        for trunk in thislist:
            tempTrunk = str(trunk.get_attribute('name')) + tempTrunk
            print(tempTrunk)
        if "Trunk opened at" in tempTrunk:
            print("Trunk opened status is present on the Dashbaord")
        else:
            print("Trunk opened at is not present in the dashboard")
            # Just to fail the Test case
            self.driver.find_element_by_id('fdfd')

        # Click on SMART START
        self.driver.find_element_by_xpath("//XCUIElementTypeApplication[@name='SmartStart']/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeButton[3]").click()
        sleep(10)

        # Verify the status on the Dashboard for SMARTSTART/Engine Start
        tempsmartstart = ''
        thislist = self.driver.find_elements_by_class_name('XCUIElementTypeStaticText')
        for st in thislist:
            tempsmartstart = str(st.get_attribute('name')) + tempsmartstart
        if "Engine started at" in tempsmartstart:
            print("Engine started at is present in the dashboard")
        else:
            print("Engine started at is not present in the dashboard")
            # Just to fail the Test case
            self.driver.find_element_by_id('fdfd')

        # Verification for remaining runtime
        elsmartstartremaining = "Remaining runtime" in tempsmartstart
        if (elsmartstartremaining == True):
            print('Remaining runtime is present in the dashboard')
        else:
            print('Remaining runtime is not present in the dashboard')
            # Just to fail the TC
            self.driver.find_element_by_id('sfdfd')

        # Check the Status in the Vehicle Status page
        self.driver.find_element_by_xpath("//XCUIElementTypeNavigationBar/XCUIElementTypeStaticText/XCUIElementTypeButton").click()

        # Click on the Refresh Button
        self.driver.find_element_by_xpath("//XCUIElementTypeButton[@name='reload']").click()
        sleep(7)

        # Verify the REMOTE STARTER status in the vehicle activity page
        tempremotestart = ''
        thislist = self.driver.find_elements_by_class_name('XCUIElementTypeStaticText')
        for rs in thislist:
            tempremotestart = str(rs.get_attribute('name')) + tempremotestart
        if "REMOTE STARTER ACTIVE / RUNNING" in tempremotestart:
            print("Remote starter status is ACTIVE")
        else:
            print("Remote Starter status is wrong")
            # Just to fail the Test case
            self.driver.find_element_by_id('fdfd')

**Comment by mykola-mokhnach** [comment] 2019-04-04 15:15
This is a problem of an outdated client library. Closed as duplicate: https://github.com/appium/appium/search?q=%22Locator+Strategy+%27css+selector%27+is+not+supported+%22&type=Issues

**Closed by mykola-mokhnach** 2019-04-04 15:15 UTC

**Comment by Jaspreet1354** [comment] 2019-04-04 15:39
@mykola-mokhnach I updated the libraries, PIP and everything
Still I am facing the same issue.

**Comment by mykola-mokhnach** [comment] 2019-04-04 16:49
> self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

The problem is here. The driver class should be the one imported from appium python lib. This will not work with the default selenium's one

**Comment by Jaspreet1354** [comment] 2019-04-05 15:31
@mykola-mokhnach It seems correct to me, according to the python appium library .40 present on "https://github.com/appium/python-client".
Please let me know, which is the correct one.

Below one is taken from the "https://github.com/appium/python-client"
# iOS environment
import unittest
from appium import webdriver

desired_caps = {}
desired_caps['platformName'] = 'iOS'
desired_caps['platformVersion'] = '11.4'
desired_caps['automationName'] = 'xcuitest'
desired_caps['deviceName'] = 'iPhone Simulator'
desired_caps['app'] = PATH('../../apps/UICatalog.app.zip')

self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

**Comment by KazuCocoa** [comment] 2019-04-05 16:02
```
from appium import webdriver
from selenium import webdriver
from appium.webdriver.common.touch_action import TouchAction
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
```

Your code in the description looks importing selenium's webdriver after appium's one.
What about removing `from selenium import webdriver`?

**Comment by Jaspreet1354** [comment] 2019-04-05 17:23
@KazuCocoa I removed all the selenium libraries present there, I still face the same problem

**Comment by KazuCocoa** [comment] 2019-04-06 02:40
Can you take a look at the instance like below?
I picked as below from the latest python-client's test code which was able to call `find_element_by_name`

```
print('{}'.format(self.driver))
<appium.webdriver.webdriver.WebDriver (session="9b3c4ef3-858d-4eef-811a-1ac0b49c009d")>
```

**Comment by Jaspreet1354** [comment] 2019-04-08 13:35
@KazuCocoa Apparently it seems to be working with ""npm uninstall -g appium && npm install -g appium@1.8.2beta""
But, Please take care of the latest versions of the Appium, Element by name is still not working for the latest Appium. I might have tried more than 10 versions(Beta and Others).

**Comment by KazuCocoa** [comment] 2019-04-08 14:23
The reason is over Appium 1.9.0 follows W3C spec. The `css selector` issue happens in selenium-client when it follows WebDriver W3C spec.

You can set `forceMjsonwp` like https://github.com/appium/python-client/blob/e3f8cb3a377f4c74a4155722d8c16ee52da31374/test/unit/webdriver/webdriver_test.py#L71-L77 with the latest appium(1.12.1) and python-client(0.40). Then, the python-client sends MJSONWP(non-W3C) spec. It works as 1.8.2 with MJSONWP.

The converting logic has been removed from current python client. So, i wondered how to reach the code in your environment after removing python-selenium client completely from your env.
https://github.com/appium/python-client/blob/e3f8cb3a377f4c74a4155722d8c16ee52da31374/appium/webdriver/webdriver.py#L243
https://github.com/appium/python-client/blob/e3f8cb3a377f4c74a4155722d8c16ee52da31374/appium/webdriver/webelement.py#L222

**Comment by Jaspreet1354** [comment] 2019-04-08 14:32
Thank you very much for your support, I will let you know if I find something not working.
