### ISSUE TITLE
'visible' attribute does not update on elements after scrolling

### ISSUE THREAD

**Issue by Soupcodes** [appium/appium#13531] opened 2019-11-01 14:07 UTC
## The problem

'value' attribute does not update on in a simulator

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): N/a
* Desktop OS/version used to run Appium: macOS Mojave 10.14.5
* Node.js version (unless using Appium.app|exe): 10.16.3
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: ios 13.1
* Real device or emulator/simulator: simulator (iPhone 6 and above)
* Appium CLI or Appium.app|exe: Appium.app (But connecting via Python scripts)

## Details

I am building an automated test suite for an iOS app, and have some toggle-able buttons that I need to be able to press depending on when they're 'on or off'

I am able to isolate to the button, but the 'value' attribute does not update when I run the tests on iPhone platform version 12.4 (The tests run fine with platform version 13.1)

Is this something to do with Appium holding onto the state of the 'value' in the original screenshot? 

## Link to Appium logs

[Appium Error Logs](https://gist.github.com/Soupcodes/eb84a1c5f0345051cc1f7927627a8b2c#file-appium_log-txt) 

I've linked the most recent errors that I encounter once I hit the issue

**Comment by mykola-mokhnach** [comment] 2019-11-01 14:43
We are aware of such problem, but cannot do nothing about it, since it's Xctest-related issue. 
Possible workaround: test iOS12 using Xcode10 SDK

Closed as duplicate of https://github.com/appium/appium/issues/13288

**Closed by mykola-mokhnach** 2019-11-01 14:43 UTC
