### ISSUE TITLE
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException

### ISSUE THREAD

**Issue by HavenChen** [appium/appium#14888] opened 2020-11-16 07:45 UTC
## The problem

I am sending a [Long Press] command to an real android device, but the error as title thrown.
According to the server log, it is because of a non int x/y location value which is calculate by Appium itself, not customer testing script.

[WD Proxy] Proxying [POST /touch/down] to [POST http://127.0.0.1:8200/wd/hub/session/8898cab9-4d60-49cd-92c0-0340d95d12ca/touch/down] with body: {"params":{"element":null,"x":540,"y":**991.5**}}

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:1.8.0
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 6.0 and 10.0
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

[WD Proxy] Proxying [POST /touch/down] to [POST http://127.0.0.1:8200/wd/hub/session/8898cab9-4d60-49cd-92c0-0340d95d12ca/touch/down] with body: {"params":{"element":null,"x":540,"y":991.5}}
[WD Proxy] Got response with status 400: {"sessionId":"8898cab9-4d60-49cd-92c0-0340d95d12ca","value":{"error":"invalid argument","message":"com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 991.5 at line 1 column 44 path $.params.y","stacktrace":"io.appium.uiautomator2.common.exceptions.InvalidArgumentException: 

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/64f63f78-a096-4cda-b1c0-065f634afb97/elements
[HTTP] {"using":"xpath","value":"//android.widget.EditText[@resource-id=\"codeInput\"]"}
[MJSONWP (64f63f78)] Calling AppiumDriver.findElements() with args: ["xpath","//android.widget.EditText[@resource-id=\"codeInput\"]","64f63f78-a096-4cda-b1c0-065f634afb97"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 20000 ms for condition
[WD Proxy] Matched '/elements' to command name 'findElements'
[WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:8200/wd/hub/session/8898cab9-4d60-49cd-92c0-0340d95d12ca/elements] with body: {"strategy":"xpath","selector":"//android.widget.EditText[@resource-id=\"codeInput\"]","context":"","multiple":true}
[WD Proxy] Got response with status 200: {"sessionId":"8898cab9-4d60-49cd-92c0-0340d95d12ca","value":[{"ELEMENT":"b2900880-1b60-4af5-a8fb-055231ee4921","element-6066-11e4-a52e-4f735466cecf":"b2900880-1b60-4af5-a8fb-055231ee4921"}]}
[MJSONWP (64f63f78)] Responding to client with driver.findElements() result: [{"element-6066-11e4-a52e-4f735466cecf":"b2900880-1b60-4af5-a8fb-055231ee4921","ELEMENT":"b2900880-1b60-4af5-a8fb-055231ee4921"}]
[HTTP] <-- POST /wd/hub/session/64f63f78-a096-4cda-b1c0-065f634afb97/elements 200 91 ms - 201
[HTTP] 
[HTTP] --> POST /wd/hub/session/64f63f78-a096-4cda-b1c0-065f634afb97/touch/perform
[HTTP] {"actions":[{"action":"longPress","options":{"element":"b2900880-1b60-4af5-a8fb-055231ee4921"}},{"action":"wait","options":{"ms":3000}},{"action":"release","options":{}}]}
[MJSONWP (64f63f78)] Calling AppiumDriver.performTouch() with args: [[{"action":"longPress","options":{"element":"b2900880-1b60-4af5-a8fb-055231ee4921"}},{"action":"wait","options":{"ms":3000}},{"action":"release","options":{}}],"64f63f78-a096-4cda-b1c0-065f634afb97"]
[UiAutomator2] calling get location: b2900880-1b60-4af5-a8fb-055231ee4921
[WD Proxy] Matched '/element/b2900880-1b60-4af5-a8fb-055231ee4921/location' to command name 'getLocation'
[WD Proxy] Proxying [GET /element/b2900880-1b60-4af5-a8fb-055231ee4921/location] to [GET http://127.0.0.1:8200/wd/hub/session/8898cab9-4d60-49cd-92c0-0340d95d12ca/element/b2900880-1b60-4af5-a8fb-055231ee4921/location] with no body
[WD Proxy] Got response with status 200: {"sessionId":"8898cab9-4d60-49cd-92c0-0340d95d12ca","value":{"x":162,"y":924}}
[WD Proxy] Matched '/element/b2900880-1b60-4af5-a8fb-055231ee4921/size' to command name 'getSize'
[WD Proxy] Proxying [GET /element/b2900880-1b60-4af5-a8fb-055231ee4921/size] to [GET http://127.0.0.1:8200/wd/hub/session/8898cab9-4d60-49cd-92c0-0340d95d12ca/element/b2900880-1b60-4af5-a8fb-055231ee4921/size] with no body
[WD Proxy] Got response with status 200: {"sessionId":"8898cab9-4d60-49cd-92c0-0340d95d12ca","value":{"height":135,"width":756}}
[WD Proxy] Matched '/touch/down' to command name 'touchDown'
[WD Proxy] Proxying [POST /touch/down] to [POST http://127.0.0.1:8200/wd/hub/session/8898cab9-4d60-49cd-92c0-0340d95d12ca/touch/down] with body: {"params":{"element":null,"x":540,"y":991.5}}
[WD Proxy] Got response with status 400: {"sessionId":"8898cab9-4d60-49cd-92c0-0340d95d12ca","value":{"error":"invalid argument","message":"com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 991.5 at line 1 column 44 path $.params.y","stacktrace":"io.appium.uiautomator2.common.exceptions.InvalidArgumentException: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 991.5 at line 1 column 44 path $.params.y\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:47)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:257)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:247)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:50)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerCo...
[W3C] Matched W3C error code 'invalid argument' to InvalidArgumentError
[MJSONWP (64f63f78)] Encountered internal error running command: io.appium.uiautomator2.common.exceptions.InvalidArgumentException: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 991.5 at line 1 column 44 path $.params.y
[MJSONWP (64f63f78)] 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:47)
[MJSONWP (64f63f78)] 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:257)
[MJSONWP (64f63f78)] 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:247)
[MJSONWP (64f63f78)] 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:50)
[MJSONWP (64f63f78)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[MJSONWP (64f63f78)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[MJSONWP (64f63f78)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[MJSONWP (64f63f78)] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[MJSONWP (64f63f78)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[MJSONWP (64f63f78)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[MJSONWP (64f63f78)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[MJSONWP (64f63f78)] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
[MJSONWP (64f63f78)] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[MJSONWP (64f63f78)] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[MJSONWP (64f63f78)] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
[MJSONWP (64f63f78)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[MJSONWP (64f63f78)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[MJSONWP (64f63f78)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[MJSONWP (64f63f78)] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
[MJSONWP (64f63f78)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[MJSONWP (64f63f78)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[MJSONWP (64f63f78)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[MJSONWP (64f63f78)] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
[MJSONWP (64f63f78)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[MJSONWP (64f63f78)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[MJSONWP (64f63f78)] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
[MJSONWP (64f63f78)] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
[MJSONWP (64f63f78)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
[MJSONWP (64f63f78)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
[MJSONWP (64f63f78)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
[MJSONWP (64f63f78)] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
[MJSONWP (64f63f78)] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
[MJSONWP (64f63f78)] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
[MJSONWP (64f63f78)] 	at java.lang.Thread.run(Thread.java:929)
[MJSONWP (64f63f78)] Caused by: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 991.5 at line 1 column 44 path $.params.y
[MJSONWP (64f63f78)] 	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:228)
[MJSONWP (64f63f78)] 	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
[MJSONWP (64f63f78)] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
[MJSONWP (64f63f78)] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
[MJSONWP (64f63f78)] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
[MJSONWP (64f63f78)] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
[MJSONWP (64f63f78)] 	at com.google.gson.Gson.fromJson(Gson.java:932)
[MJSONWP (64f63f78)] 	at com.google.gson.Gson.fromJson(Gson.java:897)
[MJSONWP (64f63f78)] 	at com.google.gson.Gson.fromJson(Gson.java:846)
[MJSONWP (64f63f78)] 	at com.google.gson.Gson.fromJson(Gson.java:817)
[MJSONWP (64f63f78)] 	at io.appium.uiautomator2.utils.ModelUtils.toModel(ModelUtils.java:17)
[MJSONWP (64f63f78)] 	at io.appium.uiautomator2.handler.BaseTouchAction.safeHandle(BaseTouchAction.java:51)
[MJSONWP (64f63f78)] 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)
[MJSONWP (64f63f78)] 	... 33 more
[MJSONWP (64f63f78)] Caused by: java.lang.NumberFormatException: Expected an int but was 991.5 at line 1 column 44 path $.params.y
[MJSONWP (64f63f78)] 	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1205)
[MJSONWP (64f63f78)] 	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:226)
[MJSONWP (64f63f78)] 	... 45 more
[MJSONWP (64f63f78)] 
[HTTP] <-- POST /wd/hub/session/64f63f78-a096-4cda-b1c0-065f634afb97/touch/perform 500 190 ms - 222

**Comment by mykola-mokhnach** [comment] 2020-11-16 07:50
Duplicate of https://github.com/appium/appium/issues/14601

**Closed by mykola-mokhnach** 2020-11-16 07:50 UTC
