### ISSUE TITLE
Tried everything to accept/dismiss device alert on iOS with appium-xcuitest-driver

### ISSUE THREAD

**Issue by Asyranok** [appium/appium#7785] opened 2017-01-31 21:51 UTC
I feel as if I have read the whole internet trying to get the xcuitest driver to work. 

I know that it is/was a known issue, and saw indications in 1.6.2 that is had been fixed, which isn't the case. In the pull requests, I noticed a suggested fix for the issue, by changing FBAlert.m directly, and this change did not work either.

I have appium 1.6.3 and appium-xcuitest-driver 2.6. Our application does not support portrait mode, so I do not have the luxury of switching to portrait mode to select the alert, and then switch back.

I grabbed the page source and can find the element just fine using the name "OK" from the page source. driver.findElement() result: {"ELEMENT":"AF086E6E-BC45-473D-B71B-902831792DEB","type":"XCUIElementTypeButton","label":"OK"}

Performing a touch action tap on this (or any touch action) does nothing. I tried driver.switch_to.alert.accept() as well.

I even tried just clicking pixel positions as well. I know that this alert is exactly in the middle of the screen, so I used a while loop to continually click an x/y coordinate while adding to the y coordinate to click upwards on the screen by 10 pixels each time. I also reversed the coordinates in the case that the driver thinks the orientation is portrait when it is in landscape mode. This should, to my knowledge, have guaranteed that the OK button would have been clicked. That didn't work either.

I am completely stuck. Are there any other workarounds? Thanks!

**Comment by Asyranok** [comment] 2017-01-31 22:24
Found a viable workaround. 

If you do not have the luxury of rotating your app into portrait view, do this to accept/decline alerts!

**This is python**

Add to Capabilities:
-This will pull the driver out of the default assumption of portrait view -
        desired_capabilities_cloud["orientation"] = "LANDSCAPE"
        desired_capabilities_cloud["deviceOrientation"] = "LANDSCAPE"

Then, in your test:
- We know that the device alerts are always exactly in the center of the screen. This will get the devices x/y max vals, and cut the x in half. Then, add 10 to always click affirmative, or remove 10 to always select the negatory. Next, just to be sure, I start 2/5 of the way up the screen, clicking every ten pixels, and stop at 4/5 of the screen height, as we will have already clicked the button. Adjust as needed.

        # Try to dismiss any iOS account alerts.
        acceptButton = self.driver.find_element_by_name("OK")
        dimensions = self.driver.get_window_size()
        width = dimensions["width"] / 2
        width += 10 # Will always select "Accept/OK". Minus ten to select "Dismiss/Don't Allow"
        height = dimensions["height"]
        
        max_tap_height = height * 0.6
        start_height = height * 0.4
        current_height = start_height
        
        while current_height < max_tap_height:
            try:
                action = TouchAction(self.driver)
                action.tap(x=width, y=current_height).perform()
            except BaseException as e:
                log("Exception! " + str(e))
            current_height += 10
        
        log("OK y coord " + str(height))
        log("OK x coord " + str(width))

**Comment by mykola-mokhnach** [comment] 2017-01-31 22:29
duplicate of https://github.com/appium/appium/issues/7779

**Closed by mykola-mokhnach** 2017-01-31 22:29 UTC

**Comment by jlipps** [comment] 2017-02-01 14:19
Thanks for documenting your workaround, @Asyranok!

**Comment by Asyranok** [comment] 2017-02-01 18:40
I have a more robust example for getting around this issue. 

If you need to dismiss an iOS alert in landscape mode, this method will work for you. It clicks in a square 10x pixels away from the exact center of the screen until hitting the alert. My automation framework is all client side, as unusual as that might sound, so I only need appium to dismiss device level alerts. After that, I do not need something to instantly detect and break from this loop. So adjust this code for that behavior as necessary. This is Python.

      ```
      # Get screen middle
       dimensions = self.driver.get_window_size()
       middle_width = dimensions["width"] / 2
       middle_height = dimensions["height"] /2
       action = TouchAction(self.driver)
       pixel_additive = 0;
       action.tap(x=middle_width, y=middle_height).perform() # Exact Center.

       try:
           while pixel_additive <= 50:
               # Tap in square of increasing size.
               action.tap(x=middle_width, y=middle_height + pixel_additive).perform()
               action.tap(x=middle_width, y=middle_height - pixel_additive).perform()
               action.tap(x=middle_width + pixel_additive, y=middle_height).perform()
               action.tap(x=middle_width - pixel_additive, y=middle_height).perform()
               action.tap(x=middle_width + pixel_additive, y=middle_height + pixel_additive).perform()
               action.tap(x=middle_width - pixel_additive, y=middle_height - pixel_additive).perform()
               action.tap(x=middle_width + pixel_additive, y=middle_height - pixel_additive).perform()
               action.tap(x=middle_width - pixel_additive, y=middle_height + pixel_additive).perform()
               pixel_additive += 10
       except BaseException as e:
           log(str(e))
```
