### ISSUE TITLE
Appium 1.7.2-beta not accept a alert

### ISSUE THREAD

**Issue by helenhan2001** [appium/appium#9544] opened 2017-10-27 01:46 UTC
## The problem

Just update to Appium 1.7.2-beta from Appium 1.7.1. but test a few times. Found the appium not accept the alert. 

## Environment 
appium 1.7.2 beta:
xcode 9 simulator:
## Link to Appium logs

[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/935575ea-1aa3-43bc-a320-557ea079356a/element/2E63C7AD-42BD-4711-B456-3998DF786AB9/click] to [POST http://localhost:8100/session/972173B8-0BCF-4A4B-9F17-C6D181E0B0CA/element/2E63C7AD-42BD-4711-B456-3998DF786AB9/click] with body: {"id":"2E63C7AD-42BD-4711-B456-3998DF786AB9"}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"2E63C7AD-42BD-4711-B456-3998DF786AB9","value":"","sessionId":"972173B8-0BCF-4A4B-9F17-C6D181E0B0CA"}
[JSONWP Proxy] Replacing sessionId 972173B8-0BCF-4A4B-9F17-C6D181E0B0CA with 935575ea-1aa3-43bc-a320-557ea079356a
[HTTP] <-- POST /wd/hub/session/935575ea-1aa3-43bc-a320-557ea079356a/element/2E63C7AD-42BD-4711-B456-3998DF786AB9/click 200 740 ms - 118 
[HTTP] --> GET /wd/hub/session/935575ea-1aa3-43bc-a320-557ea079356a/alert_text {}
[debug] [MJSONWP] Calling AppiumDriver.getAlertText() with args: ["935575ea-1aa3-43bc-a320-557ea079356a"]
[debug] [XCUITest] Executing command 'getAlertText'
[debug] [JSONWP Proxy] Proxying [GET /alert/text] to [GET http://localhost:8100/session/972173B8-0BCF-4A4B-9F17-C6D181E0B0CA/alert/text] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"972173B8-0BCF-4A4B-9F17-C6D181E0B0CA\",\n  \"status\" : 27\n}"
[MJSONWP] Encountered internal error running command: Error: An attempt was made to operate on a modal dialog when one was not open.
    at JWProxy.command$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[HTTP] <-- GET /wd/hub/session/935575ea-1aa3-43bc-a320-557ea079356a/alert_text 500 304 ms - 242 
[HTTP] --> POST /wd/hub/session/935575ea-1aa3-43bc-a320-557ea079356a/timeouts {"type":"implicit","ms":0}

## Code To Reproduce Issue [ Good To Have ]

 driver.switchTo().alert().accept();

**Comment by mykola-mokhnach** [comment] 2017-10-27 06:38
> An attempt was made to operate on a modal dialog when one was not open.

WebDriverAgent complains there is no alert on the page. Can you also attach the output of getPageSource command?

**Comment by helenhan2001** [comment] 2017-10-30 00:41
1.7.2

[TestNG] Running:
  /private/var/folders/hs/lqmxgj0j0rx9dhx0n9v2hcb40000gn/T/testng-eclipse--1264185468/testng-customsuite.xml

<?xml version="1.0" encoding="UTF-8"?><AppiumAUT><XCUIElementTypeApplication type="XCUIElementTypeApplication" name=" " label=" " enabled="true" visible="true" x="0" y="0" width="375" height="667">
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="false" x="0" y="0" width="375" height="667">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667"/>
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667"/>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="false" x="0" y="0" width="375" height="667">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667"/>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="false" x="0" y="0" width="375" height="667">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667">
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667">
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667"/>
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667">
                  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667">
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667"/>
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667"/>
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667"/>
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667"/>
                  </XCUIElementTypeOther>
                </XCUIElementTypeOther>
              </XCUIElementTypeOther>
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667"/>
            </XCUIElementTypeOther>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667"/>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334"/>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334"/>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334"/>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334"/>
      </XCUIElementTypeOther>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334"/>
      </XCUIElementTypeOther>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334"/>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334"/>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334"/>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="750" height="1334"/>
  </XCUIElementTypeOther>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="false" x="0" y="0" width="375" height="667">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667"/>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="false" x="0" y="0" width="375" height="667">
    <XCUIElementTypeStatusBar type="XCUIElementTypeStatusBar" enabled="true" visible="false" x="0" y="0" width="375" height="20">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="20"/>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="20">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="6" y="0" width="39" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" value="SSID" name="3 of 3 Wi-Fi bars" label="3 of 3 Wi-Fi bars" enabled="true" visible="false" x="50" y="0" width="13" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="11:34 AM" label="11:34 AM" enabled="true" visible="false" x="162" y="0" width="55" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="-100% battery power" label="-100% battery power" enabled="true" visible="false" x="337" y="0" width="33" height="20"/>
      </XCUIElementTypeOther>
    </XCUIElementTypeStatusBar>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="375" height="667">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667"/>
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667"/>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667"/>
      <XCUIElementTypeAlert type="XCUIElementTypeAlert" name="“Insight Timer” Would Like to Send You Notifications" label="“Insight Timer” Would Like to Send You Notifications" enabled="true" visible="true" x="52" y="244" width="271" height="179">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="52" y="244" width="271" height="179">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="52" y="244" width="271" height="179">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="52" y="244" width="271" height="179">
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="52" y="244" width="271" height="179"/>
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="52" y="244" width="271" height="179">
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="52" y="244" width="271" height="179"/>
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="52" y="244" width="271" height="179"/>
              </XCUIElementTypeOther>
            </XCUIElementTypeOther>
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="52" y="244" width="271" height="179">
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="52" y="244" width="271" height="135">
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="52" y="244" width="271" height="135">
                  <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="“Insight Timer” Would Like to Send You Notifications" name="“Insight Timer” Would Like to Send You Notifications" label="“Insight Timer” Would Like to Send You Notifications" enabled="true" visible="true" x="68" y="264" width="239" height="43"/>
                  <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="Notifications may include alerts, sounds, and icon badges. These can be configured in Settings." name="Notifications may include alerts, sounds, and icon badges. These can be configured in Settings." label="Notifications may include alerts, sounds, and icon badges. These can be configured in Settings." enabled="true" visible="true" x="68" y="310" width="239" height="48"/>
                </XCUIElementTypeOther>
              </XCUIElementTypeOther>
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="52" y="378" width="271" height="1">
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="52" y="378" width="271" height="1"/>
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="52" y="378" width="271" height="1"/>
              </XCUIElementTypeOther>
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="52" y="379" width="271" height="44">
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="52" y="379" width="271" height="44">
                  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="52" y="379" width="271" height="44">
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="52" y="379" width="136" height="44">
                      <XCUIElementTypeButton type="XCUIElementTypeButton" name="Don’t Allow" label="Don’t Allow" enabled="true" visible="true" x="52" y="379" width="136" height="44"/>
                    </XCUIElementTypeOther>
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="187" y="379" width="1" height="44">
                      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="187" y="379" width="1" height="44"/>
                      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="187" y="379" width="1" height="44"/>
                    </XCUIElementTypeOther>
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="188" y="379" width="135" height="44">
                      <XCUIElementTypeButton type="XCUIElementTypeButton" name="Allow" label="Allow" enabled="true" visible="true" x="188" y="379" width="135" height="44"/>
                    </XCUIElementTypeOther>
                  </XCUIElementTypeOther>
                </XCUIElementTypeOther>
              </XCUIElementTypeOther>
            </XCUIElementTypeOther>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
      </XCUIElementTypeAlert>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
</XCUIElementTypeApplication></AppiumAUT>

**Comment by mykola-mokhnach** [comment] 2017-11-06 13:55
The info I asked for is still not provided. I'm going to close this report

**Comment by helenhan2001** [comment] 2017-11-06 22:35
Hi Mykola. I already attached what you need as above, please check. Thanks

**Comment by saikrishna321** [comment] 2017-11-07 00:30
@helenhan2001 
>I already attached what you need as above 

I can't see any attached above. Pls provide the getPageSource logs

**Comment by helenhan2001** [comment] 2017-11-07 00:58
[PageSource_Alert.docx](https://github.com/appium/appium/files/1448277/PageSource_Alert.docx)

**Comment by mykola-mokhnach** [comment] 2017-11-07 06:50
This looks like an issue in WebDriverAgent. Please report it to https://github.com/facebook/WebDriverAgent/issues

**Closed by mykola-mokhnach** 2017-11-07 06:50 UTC
Labels: NeedsInfo, XCUITest

**Comment by kamikrazeguy** [comment] 2017-11-07 21:49
You did not provide what Mykola asked for, can you do a driver.getpagesource when the alert is displayed or go into the appium inspector with the alert view in display and export the xml and attach it here for mykola to view. Also another question is based on what you provided, when the getalerttext gets called, it looks like the alert is not present, so i might suggest you provide an explicit wait until the alert is present.

**Comment by kamikrazeguy** [comment] 2017-11-07 21:51
i noticed there are two XCUIElementAlertType, can that be the reason? Not sure without more insight to what you are doing, just my thought when looking at the pagesource.

**Comment by jamesvanhorn** [comment] 2017-12-19 22:31
Was there any resolution on this or a workaround? I am running into it also. We Use 
`final Alert a = wait.until(ExpectedConditions.alertIsPresent());` in a loop until it hits a timeout, accepting all alerts found. in 1.7.2beta4 the alerts are found/accepted, but this error is thrown when the alerts are done and we want to time out, moving on. Seems like we might need to just try/catch this and ignore it for now? 

It's not lying that there is no modal to getAlertText from, so maybe this was intended, and we just cant use the`alertIsPresent()` until its fixed/changed. Didn't check into that method source, but it seems to just call session/alert/text until it either the timeout is reached out or the response contains some text.

**Comment by fuzzybinary** [comment] 2018-01-30 23:02
I've been attempting to debug this issue and can't figure out exactly what's happening but with all current code commands to /alert/text correctly reply with error code 27, but the appium server interprets this as an unexpected error which is then not passed on to the calling client.

Logs:

>     at JWProxy.command$ (/Users/jeffward/Projects/appium-full/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
>     at tryCatch (/Users/jeffward/Projects/appium-full/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jeffward/Projects/appium-full/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.forEach.prototype.(anonymous function) [as next] (/Users/jeffward/Projects/appium-full/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (/Users/jeffward/Projects/appium-full/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
> [HTTP] <-- GET /wd/hub/session/7b5f41c6-1391-4f2c-92b8-059e51fe616d/alert_text 500 4090 ms - 242 

With all current code this should be incredibly easy to reproduce. Simply send a request to /alert/text and it should reply with a 200 status 27, instead it replies with a 500 internal error.
