### ISSUE TITLE
Takes long time to get page source while opening iOS Settings app through Appium Deskto

### ISSUE THREAD

**Issue by akashkhandelwal** [appium/appium#9290] opened 2017-09-25 12:36 UTC
## The problem

Appium is taking lot of time to load App Source for iOS Settings app, when tried to open via Appium Inspector. It doesn't load the app source even after 8 minutes

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium: 10.12.6
* Node.js version (unless using Appium.app|exe): 7.5.0
* Mobile platform/version under test: 11.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium Desktop

## Link to Appium logs

https://gist.github.com/akashkhandelwal/1ec50a9ec2d06004a3a3ca79bd4ed0fc

**Comment by pavanbachu0604** [comment] 2017-09-25 13:52
Can u try to run this command before start of test : ps -ax|grep -i "iproxy"|grep -v grep|awk '{print "kill -9" $1}'|sh

**Comment by mykola-mokhnach** [comment] 2017-09-25 13:53
Closed as duplicate of https://github.com/facebook/WebDriverAgent/issues/711

**Closed by mykola-mokhnach** 2017-09-25 13:53 UTC
